### ISSUE TITLE
Putting a paper on a paperstack will open the paperstack in a window

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#10022]
**Problem Description**:
The paperstack will be opened in a window if another paper is put on it.

**What did you expect to happen**: 
You just putting the paper on the stack. No window opening

**What happened instead**:
A window opened

**Why is this bad/What are the consequences:**
More an annoyance than anything

**Steps to reproduce the problem**:
1. make a paper stack
2. put another paper on it

**When did the problem start happening**:
Since the start of my gaming

**Comment by warior4356** [comment]
This is, unfortunately, a side effect of making the window update when you add something to the stack. This leaves two options:
1. You have to click the stack to make the UI update after adding something.
2. It behaves as it currently does opening the UI when you add something.

The only way to fix this issue would be to rework paperwork as the current system is stuck with the above choice. 

@variableundefined It may be best to close this, as I don't see a fix without converting paperwork to nanoui.

**Comment by variableundefined** [comment]
I guess this make this more of a design issue.
