### ISSUE TITLE
Giving items and buying stuff from the Merch Computer  have infinite range

### ISSUE THREAD

**Issue by PootisMan1559** [ParadiseSS13/Paradise#10039]
**Problem Description**:
You can get items from anywhere as long as you have the window open for receiving an item or confirming the purchase.

**What did you expect to happen**: 
Not receiving the item when I walked away from the merch computer or a person giving me an item.

**What happened instead**:
I still received an item even though I walked away from it.

**Why is this bad/What are the consequences:**
You could pull out guitars and snap pops out of nowhere, or anything that you can purchase from the Merch Computer

**Steps to reproduce the problem**:
Select an item to purchase from Merch Computer (snap pops for example), walk away with the "Are you sure you wish to purchase Snap-Pops for §200?" window open, and then confirm the purchase by hitting "yes". You do not need to stand near the merch computer to receive the item, this works similarly to giving an item to someone. Walk up to them, do the "give" command, walk away, and then have them accept the item from far away. They will still receive it.

**Comment by variableundefined** [comment]
Simple adjacent check I think. Normal UI also prevent this, might be because of the UI.

Merch Computer has horrifying code.
