### ISSUE TITLE
Issuing a kill command to a maintenance drone doesn't properly kill it

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#10034]
**Problem Description**:
If you shut down a maintenance drone via the console, it can re-enter its corpse to boot back up.

**What did you expect to happen**: 
Drones should be remotely terminated with no coming back.

**What happened instead**:
I double-clicked my old corpse, and rebooted just fine.

**Why is this bad/What are the consequences:**
The only way to kill a drone is via beating it up

**Steps to reproduce the problem**:
1. be a drone
2. Kill yourself via the console
3. Re-enter corpse; or double-click your chassis
4. Move around fine

**When did the problem start happening**:
Not sure, never tried this before.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
N/A

**Comment by Regen1** [comment]
Please close this bug @variableundefined  @Citinited
