### ISSUE TITLE
Capitalization Issue with Clown/Mime EVA suits

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#10047]
**Problem Description**:
The clown and mime EVA suits show up as 'eva suit' and 'eva helmet' when inspected.

**What did you expect to happen**: 
I expected them to show up as 'Mime EVA helmet/suit' and 'Clown EVA helmet/suit.'

**What happened instead**:
They show up as 'mime eva helmet/suit' and 'clown eva helmet/suit' like some sort of savage wrote it.

**Why is this bad/What are the consequences:**
_It's not but it's really annoying._

**Steps to reproduce the problem**:
Examine the gear, or someone wearing the gear.

**When did the problem start happening**:
Not sure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: IT'S NOT A BIG DEAL BUT I HATE IT.
![image](https://user-images.githubusercontent.com/38596550/47650056-12d95d80-db4d-11e8-93bb-aebf947a4310.png)

**Comment by variableundefined** [comment]
Item names are not capitalized by default here.

**Comment by Breenland** [comment]
No, I uh...I mean the EVA part of it.
