### ISSUE TITLE
Greys with genetic-blindness can still see (mostly)

### ISSUE THREAD

**Issue by Ionward** [ParadiseSS13/Paradise#10044]
**Problem Description**:
Greys afflicted with the blindness gene retain full vision in their gamescreen, but the chatlog functions correctly, displaying no emotes and whatnot.

**What did you expect to happen**: 
I expected to have my screen blackened out like normal after injecting.

**What happened instead**:
The chatlog said "You can't seem to see anything." after injecting myself with the SE, a Grey in Genetics and I could still see things and was confused.

**Why is this bad/What are the consequences:**
When you're blind you should be truly blind, and it seems really easy to just deal with blindness for your chatlog for -15 gene instability. 

**Steps to reproduce the problem**:
Be a Grey, enable blindness geneblock, continue to see.

**When did the problem start happening**:
Really close to roundstart, maybe 10 minutes in.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The gamemode was traitor, not sure if auto or normal traitor, and I was just doing normal gene block testing when I caught it.

**Comment by farie82** [comment]
Sounds like the UI is not updated in this case.

**Comment by Agameofscones** [comment]
I've had this happen on other races. One round with genetic blindness from loadout, the blindness overlay simply stopped drawing half way into the round
