### ISSUE TITLE
Arrythmic Knife doesnt work on Diona

### ISSUE THREAD

**Issue by ScratKnapp** [ParadiseSS13/Paradise#10040]
**Problem Description**:
Arrythmic Knife doesnt work on Diona

**What did you expect to happen**: 
For wielding this Chaplain's holy weapon to randomly increase or decrease speed, even as a naturally slow Diona

**What happened instead**:
It doesn't do anything at all

**Why is this bad/What are the consequences:**
Makes the knife a useless choice for Diona Chaplains, as you just get a bulky knife that you cant really put away

**Steps to reproduce the problem**:
1: Select Diona
2: Select Chaplain
3: Select arrhythmic knife as holy weapon
4: Do some walking around 
5: Notice your speed never changes

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by variableundefined** [comment]
Not sure if bug or intended - Most speed boost are not intended to work on Diona due to balance issue. Diona used to be able to meth / hyperzine.

**Comment by variableundefined** [comment]
Classifying this as not a bug - Diona is not meant to have most speed boost work on them.
