### ISSUE TITLE
Surgery 1 Holosign doesnt work

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#10049]
**Problem Description**:
Surgery 1 Holosign doesnt work

**What did you expect to happen**: 
The sign to activate

**What happened instead**:
The sign did not activate

**Why is this bad/What are the consequences:**
***MUH IMMERSION***

**Steps to reproduce the problem**:
Press the button in surgery 1

**When did the problem start happening**:
Probably when @FreeStylaLT remapped the medbay, ages ago

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
N/A

**Comment by warior4356** [comment]
Fix PR posted #10054
