### ISSUE TITLE
Using a megaphone stops you slurring your voice

### ISSUE THREAD

**Issue by TatsumakiMagi** [ParadiseSS13/Paradise#10052]
**Problem Description**:
If you become drunk enough to start slurring and then use a megaphone to speak you will not slur.

**What did you expect to happen**: 
You should still be slurring when you're using the megaphone

**Why is this bad/What are the consequences:**
I want to be drunk AND loud

**Steps to reproduce the problem**:
Get a megaphone, get drunk, start slurring, use megaphone, "no officer, I'm quite sober. yes."

**Comment by warior4356** [comment]
Addressed in #10056
