### ISSUE TITLE
Slimes can't regrow limbs if they're missing both legs

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#10066]
**Problem Description**:
If a slime is missing both legs and are not buckled to a chair or roller bed or something, then they can't regrow any missing limbs. They get this error:

You begin to focus on regrowing your missing left leg... (This will take 45 seconds, and you must hold still.)

You need to hold still in order to regrow a limb!

**What did you expect to happen**: 
To be able to regrow missing limbs while immobilized.

**What happened instead**:
Unable to regrow limbs while missing both legs.

**Why is this bad/What are the consequences:**
It's a bit of a downer on the racial ability if it can't fix the exact sort of thing it's meant to be able to fix.

**Steps to reproduce the problem**:
Be a slime, have both legs amputated or otherwise removed, and try to grow them back.

**Comment by Mitchs98** [comment]
Can confirm. Reproduces every single time. Annoying as hell x.x

**Comment by Necaladun** [comment]
Does it work with resting? Might be a workaround for now. If not, can you regrow an arm while resting and have both legs?

**Comment by Jountax** [comment]
As long as you have at least one leg you can regrow any limb while standing up, including your other leg or your feet. I didn't try resting though.

**Comment by alex-gh** [comment]
Yeah, that is a bug as far as I'm concerned.

Workaround for now is to be buckled into a chair.
