### ISSUE TITLE
Sec Borgs can continue using stunbatons with low/no charge

### ISSUE THREAD

**Issue by Xantholne** [ParadiseSS13/Paradise#10063]
**Problem Description**:
Security Cyborgs can still have a stunbaton in slot and use it with low/no charge

**What did you expect to happen**: 
To have the item return to inventory due to low charge
**What happened instead**:
How is what happened different from what you expected?
I was still able to hold the item and was permitted to still baton people with it
**Why is this bad/What are the consequences:**
Even if a Sec borg uses their entire charge batoning you over and over, they can still continue to baton

**Steps to reproduce the problem**:
Have low/no charge, for me it was a 30k cell with 36 charge left. Have baton active inventory, use something else to drain battery

**When did the problem start happening**:
Several months back

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Vampires, seen it similarly happening on Cult aswell.

I can't be 100% certain it wasn't going to get put away, but other items such as my laser gun were turned off and no longer usable because of the lower power. My baton however in inventory still had power and let me continue using it from 400/30k power to 38/30k power before I had been hit too much

**Comment by variableundefined** [comment]
Is using stunbaton without charge consistent with other borg items? Does it allow you to keep stunning people? Or only on harmbaton mode?

**Comment by Xantholne** [comment]
When it happened, both previous round as of right now with me as a sec borg, and yesterday with another sec borg during a cult round, you can regular baton and harmbaton with the baton still set to active. I am fairly sure it needs to already be active for this to happen.

**Comment by variableundefined** [comment]
Seems to be a bug then.
