### ISSUE TITLE
Server won't connect to SQL databases if ENABLE_STAT_TRACKING isn't set in dbconfig.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#1006]
Title pretty much says it all.

**Comment by tigercat2000** [comment]
I.. think this is intentional, the example should probably have it enabled.

**Comment by Rohaneanew** [comment]
Update to this:

The server will NOT connect properly to the SQL database if you don't have your feedback tracking set to anything other than paradise. This comment is mostly as a warning to future server owners who are lazy and attempted to copy/paste their previous db.config while transferring codebases.

**Comment by tigercat2000** [comment]
@Fox-McCloud This is still a valid issue report, it should be left open in case someone does every decide to change this to make a hint of sense.

**Comment by tigercat2000** [comment]
Given that ENABLE_STAT_TRACKING isn't a thing anymore and has been renamed to ENABLE_SQL, this can probably be closed
