### ISSUE TITLE
Changelings' can headslug from lockers.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#10083]
**Problem Description**:
Welded a changeling into a locker after summarily beating it into near crit to deliver it to security. Security arrived sorta stared at it, it headslugged before I could explain the problem due to being mutestung. The headslug, somehow, exited the locker and went into a vent. The locker remained welded shut.

**What did you expect to happen**: 
Considering the head and other limbs, gibs, and headset stayed in the locker I expected the headslug to stay in the locker to be moved to a room and beaten to death.

**What happened instead**:
Headslug popped and got out 100% fine through a welded shut locker, somehow.

**Why is this bad/What are the consequences:**
Changelings can freely escape lockers, the locker will remain welded in the process. Changelings should NOT be magically headslugging out of a locker without 1. the locker being open or 2. It forcing the locker open/destroying the locker in the process.

**Steps to reproduce the problem**:
1. Weld a changeling into a locker.
2. Wait.
3. Watch it headslug and the headslug be free.

**When did the problem start happening**:
Literally happened this morning around 3 AM CST. Not sure of when they were able to do this, possibly forever.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:  Changeling game mode. Though I doubt it's directly related to the specific game mode. Nothing else out of the ordinary happened.

**Comment by KasparoVy** [comment]
Spawned the headslug on the same tile as the locker that's it that's all, might have to add a check to put the headslug in exactly the same `loc`. I wonder if it simply uses `get_turf`

**Comment by Mitchs98** [comment]
Yeah that's what our resident pink haired nerd told me on discord. I'll check it out after I'm done with my current thing I'm doing if no one else has.
