### ISSUE TITLE
SecHUD Comment Log no longer works.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#10080]
**Problem Description**:
SecurityHUD Comment Log no longer works when you set someone to arrest. Used to you viewed the comment log to check someones' arrest reason if it wasn't written in under the crimes section. Now it just shows up blank.

**What did you expect to happen**: 
I expected the HoS to know why I set someone to arrest when I told them to view the comment log.

**Why is this bad/What are the consequences:**
More security confusion than normal.
**What happened instead**:
It showed blank. Literally showed nothing at all.

**Steps to reproduce the problem**:
1. Be sec.
2. Set someone to arrest.
3. Write a reason.
4. Try to view it.
5. Fail because it doesn't show a reason.

**When did the problem start happening**:
Today as far as I'm aware it worked previously.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Possibly related due to the paper window fix. Not actually sure what broke it, but it was definitely working before today.

**Comment by farie82** [comment]
confirmed. The comments won't get updated. No entry is placed here. Entries can be placed manually using the add comment method both using the secHUD and the sec console.
