### ISSUE TITLE
Lighting somebody else his cigarette won't update the sprite

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#10107]
**Problem Description**:
As stated in the title. If you light another persons cigarette it won't update the sprite. The glow will be there but the cig won't be updated to the lighted sprite

**What did you expect to happen**: 
The cig to be lighted

**What happened instead**:
The cig sprite stayed the same. Re equiping fixed this

**Why is this bad/What are the consequences:**
MAH MURSION. Nah but it's probably an easy fix.

**Steps to reproduce the problem**:
1. have somebody put a cig in their mouth
2. Light that cig using the target mouth then click on them thing.
3. Behold the glow coming from a seemingly unlit cig

**When did the problem start happening**:
For a while I think

**Comment by AzuleUtama** [comment]
I actually just got someone to do this for me on the main server and the sprite updated correctly for me. 

Both the icon and character sprites worked. This was with a cheap lighter though, were you lighting it in a specific way?

**Comment by farie82** [comment]
It's when lighting somebody else his cig when it happens. I used a match back then but I don't think it matters what item you use.
