### ISSUE TITLE
Ancient Station creates alarms visible on main station

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#10127]
**Problem Description**:
https://github.com/ParadiseSS13/Paradise/pull/9949 added Beta, Charlie, and Delta ancient mining stations. Unfortunately, they generate alarms for the AI on the main station during certain conditions. E.g. "Beta Station Atmospherics" can generate an atmos alarm that shows up on main station atmos computers.

**What did you expect to happen**: 
Beta/Charlie/Delta should not create alarms visible to main station AI or computer consoles.

**What happened instead**:
It did.

**Why is this bad/What are the consequences:**
Its annoying. Harmless, but annoying. Not a major bug, but still a mapping error.

**Steps to reproduce the problem**:
Put the air alarms on the ancient station into an alarm state.
Observe that they show up on main station atmos alarm terminals.

**Comment by variableundefined** [comment]
This is somewhat alarming
