### ISSUE TITLE
Screwdrivering a holopad will reset its sprite after a few seconds

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#10120]
**Problem Description**:
If you screwdriver a holopad to open it, you will get an icon that looks like it's been screwdrivered open, but after 2 seconds it'll revert to its default sprite.

**What did you expect to happen**: 
The sprite shouldn't update until someone screws it back to how it was

**What happened instead**:
Sprite reverted to default

**Why is this bad/What are the consequences:**
Hard to tell when it's been screwed

**Steps to reproduce the problem**:
1. Screw holopad
2. Watch sprite change

**Comment by variableundefined** [comment]
Well this is screwed up
