### ISSUE TITLE
Can be Activated in Auto-Traitor even if Ineligible for Antag

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#10123]
**Problem Description**:
I chose to be Ineligible for antag for this round. 20 minutes later, I was activated as a Traitor.

**What did you expect to happen**: 
I chose not to be an antag that round.

**What happened instead**:
I was activated as a traitor 20 minutes in.

**Why is this bad/What are the consequences:**
It means Auto-Traitor rounds can ignore people's antag preferences for that round.

**Steps to reproduce the problem**:
1. Set self to be Ineligible for Antags.
2. Be activated as a traitor anyway.

**Comment by variableundefined** [comment]
Your issue title need to be more clear. Who can be activated, as what?

A better title would be,"You can get traitor on auto-traitor gamemode when global antag preferences is turned off"
