### ISSUE TITLE
pipemanifolds make a black and static tile

### ISSUE THREAD

**Issue by thanatossage** [ParadiseSS13/Paradise#10137]
**Problem Description**:
What is the problem?
pipe manifolds make a black and static square

**What did you expect to happen**: 
Why do you think this is a bug?
*shrugs no clue missing sprite *shrugs

**What happened instead**:
How is what happened different from what you expected?
there is no normal art there at all

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
you cant see the thing

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
stumbled upon it

**When did the problem start happening**:
If your report is about something that used to work but no longer does. When was the last time you remember it working?
noticed it this round around midnight on [11/6/18]

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
![image](https://user-images.githubusercontent.com/44797292/48047201-eb8e1c00-e15c-11e8-9647-fcb87e14d419.png)
![image](https://user-images.githubusercontent.com/44797292/48047213-f8ab0b00-e15c-11e8-9760-ef8c364706ae.png)

**Comment by Shadow-Quill** [comment]
Can't reproduce.
