### ISSUE TITLE
Claw Game gives double prizes

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#10130]
**Problem Description**:
When you win the Claw Game, you get a 'double prize' every singular win.

**What did you expect to happen**: 
When you win the Claw Game, the expected result is to receive a singular prize: there is a possibility for "Claw Game beeps, "DOUBLE PRIZE!"" to happen, but if that happens now, you get three prizes: the singular win giving you two prizes, and the double prize giving you the extra prize. I expected to receive a single prize upon winning with no extra bonuses applied.

**What happened instead**:
Upon winning with no extra bonuses applied, I receive two prizes consistently. Upon winning with "Claw Game beeps, "DOUBLE PRIZE!"" applied, I receive three prizes.

**Why is this bad/What are the consequences:**
As a minor bug, this at most negates the "double prize" bonus.

**Steps to reproduce the problem**:
In boxstation, during any gamemode, visit the arcade and play the Claw Game. Win the claw game with no extra bonuses applied and see two prizes spawn.

**When did the problem start happening**:
Until recently, this problem only happened occasionally. I cannot remember an exact date as to when it started happening constantly.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by Sihsse** [comment]
Can someone confirm this? I'm unable to replicate this issue on my private server.

**Comment by dovydas12345** [comment]
Wasn't able to reproduce it in my private server, but was able to reproduce it in non-private the other day. So i am confused...

**Comment by charliehershberger** [comment]
I was unable to reproduce this on the public server

**Comment by iantine** [comment]
Took a few pics of it in action.
![2](https://user-images.githubusercontent.com/26665535/55093226-2abb0a80-5108-11e9-942b-869d794d7cca.png)
Receiving two prizes when it should be one. Can't post the gif I took as I accidentally caught an mhelp in it, however-
![3](https://user-images.githubusercontent.com/26665535/55093262-3c041700-5108-11e9-9ac1-539428663b58.gif)
![4](https://user-images.githubusercontent.com/26665535/55093263-3c9cad80-5108-11e9-85ef-c9e5d4d854be.png)
Receiving the Double Prize! and getting an extra prize somehow, making it three.
