### ISSUE TITLE
github contributing.md nitpick

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#10131]
**Problem Description**:
the file says there are at most 3 maintainers at once, then lists 4 maintainers.

**What did you expect to happen**: 
the file to not give conflicting information.

**What happened instead**:
It did.

**Why is this bad/What are the consequences:**
The 2 people that read the contributing guidelines could be briefly confused.

**Steps to reproduce the problem**:
look at contributing.md

**Comment by variableundefined** [comment]
Just cut the line from the contribution.md. 

No token for this one sorry.

**Comment by TDSSS** [comment]
Oh nooooo, not my precious token.

Don't worry, didn't expect it either.
