### ISSUE TITLE
missing limb not showing up right on examine text?

### ISSUE THREAD

**Issue by sampaiii** [ParadiseSS13/Paradise#10136]
**Problem Description**:
For some reason a missing limb was showing up like "He is missing his ."

**What did you expect to happen**: 
For it to tell me which limb is missing.

**What happened instead**:
It says, "He is missing his ." and I have no idea what is missing or if anything is missing.

**Why is this bad/What are the consequences:**
You can't tell what limb is actually missing, if something IS even missing.

**Steps to reproduce the problem**:
1. Examine someone.
2. See that the missing limb text is weird.

**When did the problem start happening**:
Just last round when I was playing borg is the first time I saw this happen.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
It was uhh, a traitor round, I was playing borg, I dunno if this stuff is related.
Image below is the weird text I guess, sorry I don't have the entire examine text, nothing else was weird aside from this though.
![image](https://user-images.githubusercontent.com/26171954/48041803-89292180-e144-11e8-8fa9-b1247b03a680.png)

**Comment by alex-gh** [comment]
Could not reproduce that one. 

Can you remember if it was any specific species?

**Comment by moxian** [comment]
Just happened on live.
According to the sprite, the missing part was left foot.
The mob in question was a human and a changeling (the last part might be important).
![dreamseeker-20201025-011044](https://user-images.githubusercontent.com/7831163/97097804-46ccb800-166d-11eb-88f8-2ac4a99b6680.png)
![dreamseeker-20201025-011118](https://user-images.githubusercontent.com/7831163/97097805-46ccb800-166d-11eb-8b97-0ca4b05f2acb.png)

**Comment by lewcc** [comment]
https://github.com/ParadiseSS13/Paradise/pull/21691 seems to have likely fixed this.

**Comment by DGamerL** [comment]
No additional reports of this bug, so it seems that #21691 has fixed this issue. If it happens again, feel free to make a new report!
