### ISSUE TITLE
Pineapple unable to be sliced.

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#10150]
**Problem Description**:
Pineapples can't be sliced with a knife.

**Why is this bad/What are the consequences:**
Can't produce pineapple pizza.

**Steps to reproduce the problem**:
Use knife on a pineapple.

I haven't verified this bug, it was reported by a couple of people on discord.

**Comment by variableundefined** [comment]
Appears to also apply to all grown snacks that's supposed to sliceable - Melon.

Tested myself.
