### ISSUE TITLE
Canisters seem to eat up stupid amounts of CPU 4no raisins

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#10152]
**Problem Description**:
Something about canisters makes them call `update_icon` all the time, which causes them to eat up far too much CPU for doing nothing

**What did you expect to happen**: 
Not a bug so much as a code issue, but I don't think they should update their icon unless the gas inside them changes. Canisters not hooked up to anything shouldn't even bother calling `update_icon`, for example.

**What happened instead**:
Canisters update icon all the time.

**Why is this bad/What are the consequences:**
That CPU could be better utilised elsewhere. Also less lag.

**Steps to reproduce the problem**:
Start a game and profile it, look at the CPU usage

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

See below for a picture of my profiling. In this game I didn't touch canisters at all, so `update_icon` shouldn't even have been called, but it was.

![image](https://user-images.githubusercontent.com/18459142/48153813-0d071900-e2bf-11e8-8146-2040044433c2.png)

EDIT: I think this line may be to blame, as it's trying to check a contained tank's pressure, but it's checking the canister's tank instead. IDK though 😄 https://github.com/ParadiseSS13/Paradise/blob/62bd7ff06366e4786c1ef21620bdf4a2eafca8ab/code/game/machinery/atmoalter/canister.dm#L145

**Comment by KasparoVy** [comment]
`dank_pressure`

**Comment by Squirgenheimer** [comment]
I profiled a little bit myself, and I saw that return_pressure had a self CPU time of 0.245 over 226409 calls, while check_change had a self CPU time of 0.245 with _22x less_  calls. Does this mean the issue is with the rest of the code in the check_change proc (or the number of calls)?
Then again, I'm not that familiar with the profiler.

**Comment by Citinited** [comment]
I think that means that `return_pressure` is 22 times less intensive than `check_change`, like-for-like.

Also `return_pressure` is doing a bunch of stuff for more than just canisters, so I don't think it is to blame for this.

**Comment by Birdtalon** [comment]
Anything involving atmospherics is just cursed.

**Comment by Citinited** [comment]
Closing as not a bug and I don't think this is likely to be fixed without touching atmoscode
