### ISSUE TITLE
Chaplain unable to name religion with runtime

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#10169]
**Problem Description**:
Chaplain did not get popup to select religion

**What did you expect to happen**: 
Name / select religion popup to appear

**What happened instead**:
It didnt

**Steps to reproduce the problem**:
Join as chaplain

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: 
![image](https://user-images.githubusercontent.com/20497797/48253279-e509d980-e3d4-11e8-8e02-e5012d15054b.png)

https://github.com/ParadiseSS13/Paradise/blob/6fe83a698757f023d26171355fff906d95ee764b/code/game/jobs/job/support_chaplain.dm#L89

Using the "Select Equipment" menu allowed them to name their religion.

**Comment by farie82** [comment]
Tried to reproduce. Didn't get the runtime on my end. Although i saw it happen to a player a round ago. Yet i can't reproduce it locally.

**Comment by farie82** [comment]
Easy fix:
Add a check if the client is null or not. If it's null it should stop.

**Comment by FunnyMan3595** [comment]
This has likely been fixed sometime in the intervening years.
