### ISSUE TITLE
character floats as if in zero gravity under some pod-related circumstances

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#10172]
**Problem Description**:
When you enter a spacepod in gravity, go out into space, hop out and back in and then fly back to the station and get out, your character still 'floats'/jiggles up and down as if in space, even when affected by gravity

**What did you expect to happen**: 
The character to be displayed properly.

**What happened instead**:
It looks like I am in zero g

**Why is this bad/What are the consequences:**
It's a visual bug, but it's annoying.

**Steps to reproduce the problem**:
1. Enter spacepod, take pod into space.
2. exit pod in zero-g, notice you're now floating up and down. Re-enter your space pod
3. take spacepod back to station, leave spacepod
4. notice you're still floating up and down.

**When did the problem start happening**:
Has been like that for a while.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I assume the issue is the 'floating in space' animation is only checked/removed when you cross into/out of gravity, but it isn't checked if you're in a pod.

I usually fix it by taking my pod back out into space, exiting it, entering gravity and then from gravity entering my pod and taking it back across.

**Comment by Twinmold93** [comment]
I'll have to look at it sometime in the near future.
