### ISSUE TITLE
Layering vulp issue

### ISSUE THREAD

**Issue by IntentEldiablo** [ParadiseSS13/Paradise#10188]
**Problem Description**:
Layering issue due to byond 512.
playing as a vulp security officer, the Security hud does not layer properly over the vulp eyes, one side is normal the other displays the eye colours over the glasses

**What did you expect to happen**: 
hud glasses to layer over the eyes

**What happened instead**:
only 50% of the glasses layered over the eyes

**Why is this bad/What are the consequences:**
it is a visual bug and shows issues with layering

**Steps to reproduce the problem**:
http://prntscr.com/lgmx2p screenshot of the character and any layers it might be using, otherwise playing as a vulp character and placing hud glasses on should replicate

**When did the problem start happening**:
todays date, 10/11/2018

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
nothing out of the ordinary, gamemode unknown at the time
![ipsum error](https://user-images.githubusercontent.com/32814291/48301195-c2191b80-e4e1-11e8-89a1-4820d64f5874.jpg)

**Comment by KasparoVy** [comment]
Do you happen to know if this round was during a test-merge of the icon generation overhaul?

Otherwise, this is the criteria for rendering eyes over things for that 'glow' effect.
https://github.com/ParadiseSS13/Paradise/blob/fa87762d7e996d6e8c368561db11e35f0bf363f4/code/modules/mob/living/carbon/human/human.dm#L1532

I'll try to check into this a bit further later

**Comment by IntentEldiablo** [comment]
i believe it is during the test merge yes

**Comment by Birdtalon** [comment]
This only happens with vulp or you were just playing vulp at the time?

**Comment by variableundefined** [comment]
How long ago was the changes noticed? Because this could be caused by 512. I had a report of this happening when my sprite accessories were in (It isn't now), and when the human icon TM was in. An attempt to compile on earlier version or revision shows that this seems to be not related to any PR

**Comment by IntentEldiablo** [comment]
just playing vulp at the time

**Comment by KasparoVy** [comment]
Oh wow, so even with the current human icon and sprite accessory PRs merged, if byond is on an older version it's fine? Wack.

**Comment by variableundefined** [comment]
I believe the codebase would be screwed up if it is compiled on an older version now.

**Comment by Henri215** [comment]
Couldnt replicate, it was probably solved since we moved past version 512.
