### ISSUE TITLE
Custom syndicate borg does not display custom sprites properly

### ISSUE THREAD

**Issue by variableundefined** [ParadiseSS13/Paradise#10183]
**Problem Description**:
As per title. Fluff syndicate borg sprites does not select properly.

This issue can be found in robot.dm - Custom sprites is checked in pick module and there's no entry for syndicate whatsoever.

**Comment by tigercat2000** [comment]
I'm not sure this is a bug, syndiborgs aren't meant to have custom sprites, they're supposed to be extremely identifiable...

**Comment by variableundefined** [comment]
In that case we'd need to make an administrative ruling that syndicate custom borg is not allowed anymore.

**Comment by variableundefined** [comment]
We've discussed this internally and decided to consistently rule from now on that custom syndicate borg sprite is no longer allowed as they affect balance. Crew need to be able to tell it's a borg coming for them at first glance.

**Comment by tigercat2000** [comment]
(they never worked anyways)
