### ISSUE TITLE
Eva Suit Control Module (Emergency) Plasma Cutter Doesnt Work

### ISSUE THREAD

**Issue by ScratKnapp** [ParadiseSS13/Paradise#10181]
**Problem Description**:
The RIG Emergency module (the one an admin must spawn) has a built in plasma cutter, but it doesnt work

**What did you expect to happen**: 
For me to be able to shoot plasma cutter projectiles and cut down walls and shit

**What happened instead**:

Middle-clicking with it fully selected doesn't do anything. Middle-clicking again displays an error that it cannot be used again so soon.

**Why is this bad/What are the consequences:**
Rarely spawned rigsuit module has a broken function in the rare event you get your mitts on it to begin with

**Steps to reproduce the problem**:
1: Spawn an "Emergency' Hardsuit Module, the back mounted Engineering kind
2: Put it on
3: Seal and deploy the hardsuit
4: Select the Plasma Cutter module
5: Try to use it with middle click
6: doesnt work

**When did the problem start happening**:
I just noticed it today. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I picked it up inside a bathroom stall, and don't know what might've been done to it before I grabbed it.

**Comment by variableundefined** [comment]
We oughta nuke RIGsuit already.

**Comment by AffectedArc07** [comment]
Closed by purging rigsuits.
