### ISSUE TITLE
dionae healing seems broken

### ISSUE THREAD

**Issue by pazneria12** [ParadiseSS13/Paradise#1019]
even when I have a light on my head and pda, I don't heal as dionae unless I stand next to two flood lights aswell it seems, and unless I have the tray lid with light on, then I don't seem to be able to grow dionae pods either.

**Comment by veganzombeh** [comment]
To add to this, I've seen at least two dionae spontaneously dying in well-light areas.

**Comment by pazneria12** [comment]
ive been one of them XD
