### ISSUE TITLE
Shrinking whole screen in multicam mode

### ISSUE THREAD

**Issue by Luxyleathehat** [ParadiseSS13/Paradise#10203]
**Problem Description**:
What is the problem? 
When looking at the singularity with multicam mode, the whole screen shrinks

**What did you expect to happen**: 
Why do you think this is an issue?
For the screen to remain the same size

**What happened instead**:
How is what happened different from what you expected?
It was smaller

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Makes it much more difficult to see anything

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Had an admin activate multicam mode, made 3 cams and put one at the Particle accelerator, Moved that cam down after awhile to the singularity to check on it and the whole screen with all the cameras shrunk

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: Gamemode: Cling & Traitor
Anything else you can tell us.

**Comment by Contrabang** [comment]
Multicam is gone
