### ISSUE TITLE
SM archs electricity, can break containment in delta

### ISSUE THREAD

**Issue by Eniraz** [ParadiseSS13/Paradise#10207]
**Problem Description**:
What is the problem?
The super matter archs electricity when beeing hit with an emitter beam, which damages and eventually breaks nearby stuff, even airlocks.

**What did you expect to happen**: 
Why do you think this is an issue?
I did not expect the SM to arch electricity, and break the SM chamber airlocks because of it

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Acquire super matter shard or play on delta station
2. Shoot it with a emitter to generate more power
3. Watch as it archs all over the place, destroying airlocks, radiation collectors etc. (doesn't break walls or windows)

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Not sure for how long this has been a thing, haven't played around with the SM before

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
It was on Delta station, but the archs happen on the cyveriad aswell if you get the SM from cargo.

**Comment by TDSSS** [comment]
Easiest way to fix this would probably mapping in a grounding rod or two.
