### ISSUE TITLE
Delta: eng secure storage button in CE office does not work

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#10219]
**Problem Description**:
The button to open eng secure storage in the CE office does not work.

**What did you expect to happen**: 
The three blast doors at 106,120 to open.

**What happened instead**:
They did not open.

**Why is this bad/What are the consequences:**
Secure storage is useful.

**Steps to reproduce the problem**:
Spawn as CE.
Use the "Engineering  Secure Storage Control" in your office.
Observe that the doors don't open.

**Comment by Kyep** [comment]
@SamHPurp

**Comment by Shadow-Quill** [comment]
@Anasari this has been fixed
