### ISSUE TITLE
Non working wall mounted flashes [Delta]

### ISSUE THREAD

**Issue by Eniraz** [ParadiseSS13/Paradise#10223]
**Problem Description**:
What is the problem?
The HoP line flash button does nothing and the flashes in perma don't even have buttons to activate them.
![image](https://user-images.githubusercontent.com/43669790/48503073-68965100-e841-11e8-8ee8-cddd8b8d92a3.png)

**What did you expect to happen**: 
Why do you think this is an issue?
I expected to be able to flash people on the HoP line and to be able to flash perma prisoners
**What happened instead**:
How is what happened different from what you expected?
HoP's wall mounted flash button did nothing, perma flashes just dont have buttons

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
The HoP cant flash anyone trying to climb the counter or riots or anything else going on in the HoP line. Officers can't safely flash perma prisoners.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be HoP in Delta station
2. Press flash button

1. Be sec officer/warden/HoS in Delta station
2. Look for the buttons to flash perma prisoners
3. Find none

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Last time i played Delta, a day or two ago

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Jazz23** [comment]
I fixed it and did a PR: https://github.com/ParadiseSS13/Paradise/pull/10228
