### ISSUE TITLE
Some stuff about the CE's office [Delta]

### ISSUE THREAD

**Issue by Eniraz** [ParadiseSS13/Paradise#10227]
**Problem Description**:
Neither the transit tube lockdown button, nor the secure storage button work (as noted in #10219 by Kyep). There are 2 advanced magboots too, one in the office and the other in the CE's suit storage unit.. The privacy shutter don't seem to be too private, as they don't block view from the engineering entrance. The Chief Engineer's stamp is also absent.
![image](https://user-images.githubusercontent.com/43669790/48520039-85497d80-e86f-11e8-8f0c-7fdc85f7d4cd.png)
![notsoprivate](https://user-images.githubusercontent.com/43669790/48520087-a14d1f00-e86f-11e8-9be7-32e025ca61e3.png)

**Comment by Jazz23** [comment]
https://github.com/ParadiseSS13/Paradise/pull/10240
