### ISSUE TITLE
NTSL2 Buglist

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#10232]
***NOTE:***
This issue does not follow the standard format due to the way I plan to write it up. If you need it to follow standard format, I will re-create the issue.

**MAJOR ISSUES**
*These issues directly affect NTSL2, and should be addressed soon*

Issue 1:
JSON uploading does not work at all

The idea of import/export is so that you can, well, import and export configurations. Upon creating a configuration, I saved it then exported it. Upon re-importing, it spammed the admin log (More later) and didnt upload configuration. I checked runtimes to see if anything had broken, but this is what I saw.
![image](https://user-images.githubusercontent.com/25063394/48568599-abb2fb80-e8f7-11e8-8cc0-b7580787246b.png)

I tried uploading regular JSON, minified JSON, with and without certain fields, even re-importing the JSON that I had just exported, but changing 1 setting. That still didnt work. In short, JSON is broken.
Sidenote: When uploading JSON, it fully breaks the UI, so it wont even work when manually adding JSON, essentially bricking the configuration.

Issue 2:
Admin logging is a complete mess

Currently, this happens when you go to load a script in.
![2018-11-15_17-03-30](https://user-images.githubusercontent.com/25063394/48568924-693dee80-e8f8-11e8-8313-6670f7e77072.gif)

This will instantly fill and admin's chat, probably inconveniencing them. My suggestion for this is to add a popout href to show the script uploaded
```
ADMIN LOG: AffectedArc07 uploaded an NTSL2 configuration. [VIEW JSON]
```

Issue 3:
Regex table doesn't work except for bottom entry

When filling the regex table, only the bottom entry works
![image](https://user-images.githubusercontent.com/25063394/48569648-35fc5f00-e8fa-11e8-8bc7-fb7c832a9f19.png)
![image](https://user-images.githubusercontent.com/25063394/48569735-70fe9280-e8fa-11e8-93dd-e035d064a40b.png)
*Ignore the random rules, that was when I was testing issue 4*

**MINOR ISSUES**
*These are not important, and could almost be considered feature requests*

Issue 4:
You can use several pencode pieces you should not be able to use over radio, Examples include: 
- [logo]
- [sign]
- [hr]
Examples below:
![image](https://user-images.githubusercontent.com/25063394/48569820-a99e6c00-e8fa-11e8-8723-48a6f07ec5ff.png)
![image](https://user-images.githubusercontent.com/25063394/48569834-b8851e80-e8fa-11e8-8868-f446b5d780a4.png)

Issue 5:
There is a lack of colour in NTSL2. This is probably me just having withdrawals from NTSL, and wanting fancy colours back for chat highlights, which IC sort of make no sense but it added a lot to tcomms. If this were to be addressed, it could probably be done with pencode colouring, that could even work if you use a multicoloured pen

Issue 6:
This is going to be extremely nitpicky, but there are a lot of references to it being called NTSL. This annoys me as the new version contains absolutely no scripting, so calling it NTSL makes no sense. Again, very nitpicky, but I would like to see this changed.
Examples:
![image](https://user-images.githubusercontent.com/25063394/48570150-963fd080-e8fb-11e8-8724-9da487f1f441.png)
![image](https://user-images.githubusercontent.com/25063394/48570156-9fc93880-e8fb-11e8-9d2c-8de735fcea6c.png)
![image](https://user-images.githubusercontent.com/25063394/48570172-a9eb3700-e8fb-11e8-8e1b-ab7a56e6e07f.png)

Again, tell me if this needs to be re-created in standard issue format

**Comment by KasparoVy** [comment]
That's bloody hilarious hahaha, excellent. Anon

**Comment by tigercat2000** [comment]
>  You can use several pencode pieces you should not be able to use over radio, Examples include:

Not a bug.

>  There is a lack of colour in NTSL2. This is probably me just having withdrawals from NTSL, and wanting fancy colours back for chat highlights, which IC sort of make no sense but it added a lot to tcomms. If this were to be addressed, it could probably be done with pencode colouring, that could even work if you use a multicoloured pen

Feature request.

> This is going to be extremely nitpicky, but there are a lot of references to it being called NTSL. This annoys me as the new version contains absolutely no scripting, so calling it NTSL makes no sense. Again, very nitpicky, but I would like to see this changed.

It's official name is NTSL2.

**Comment by AffectedArc07** [comment]
>Not a bug
Acceptable
>Feature request
Acceptable
>Its official name is NTSL2
I spoke with you on discord just now about this. This contains 0 scripting. It being called NTSL2 is probably why people are trying to paste in scripts, bricking the config. I would like to see it changed, considering in the UI you call it NTTC, but in the titles you call it NTSL
