### ISSUE TITLE
Flashbang, Banana, Mousetrap launcher are broken

### ISSUE THREAD

**Issue by variableundefined** [ParadiseSS13/Paradise#10241]
**Problem Description**:
When fired the projectile spawn at the mech's feet instead of working as intended. Funnily enough the missile rack & bola launcher still works.

Affected includes:
Flashbang
Banana
Mousetrap
Clusterbang

It comes with a runtime:

![image](https://user-images.githubusercontent.com/40092670/48621531-b72d2200-e9de-11e8-84ea-128d2bcdeef6.png)

**Comment by Deelite34** [comment]
When I played with honkmech today, 95% of time launched bananas went under my mech, 5% the got launched
