### ISSUE TITLE
Dizziness genetics disability takes long time to go away

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#10243]
**Problem Description**:
What is the problem?
Dizziness genetics disability takes long time to go away when you eat mutadone, about few minutes, compared to few seconds with all other powers.
**What did you expect to happen**: 
Why do you think this is an issue?
Shaking screen can be very annoying, and all other genetic powers go away in few seconds when you eat mutadone pill

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Unwanted dizziness is annoying, and is annoying for few minutes after you lose that disability.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Get dizzy dissability 2. eat mutadone. 3 have to wait minutes for it to go awayy
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Always as far as I remember.

**Comment by KasparoVy** [comment]
Could set dizziness to 0 on deactivation 🤔

**Comment by KasparoVy** [comment]
Hell yeah
