### ISSUE TITLE
A rather specific but easy to make combination of reagents can break atmos

### ISSUE THREAD

**Issue by Eniraz** [ParadiseSS13/Paradise#10249]
**Problem Description**:
What is the problem?
If you detonate a grenade with 2.5u of chlorine trifluoride and 2.5u of firefighting foam, it causes the ambient temperature to instantly drop below -240ºC, if 2 or more grenades detonate in close proximity at the same time negative moles of oxygen and a saturation of CO2 can appear. The negative mole thing is rather inconsistent, but not isolated incidents, all of the following screenshots are from different rounds.
![wat](https://user-images.githubusercontent.com/43669790/48654522-d3948300-ea0d-11e8-8f6d-6950d82294f8.PNG) ![wat2](https://user-images.githubusercontent.com/43669790/48654524-d4c5b000-ea0d-11e8-920e-d389cdf3ff61.jpg)

**What did you expect to happen**: 
Why do you think this is an issue?
I accidentally discovered this, expecting a non-scaling explosion, as it is supposed to be.

**What happened instead**:
How is what happened different from what you expected?
The ambient temperature instantly dropped to -240ºC and when i used an air analyzer a while later i saw this: 
![oxigeno_negativo](https://user-images.githubusercontent.com/43669790/48654617-c1ffab00-ea0e-11e8-892d-6aad08419786.PNG). 

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It completely messes up the atmos on a significant area, causes fastmos due to the instant low pressure (making it hard to scape) and can sometimes cause the negative mole thing, making the whole thing way deadlier than already is. And worst of all, it can be mass produced by any chemist/scientist from roundstart.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Get 2.5u of chlorine trifluoride into a beaker
2. Get 2.5u of firefighting foam into another beaker
3. Make a grenade and put the two beaker in it
4. Detonate the grenade
   4.1. Detonate 2 grenades very close to eachother at the same time using signalers and maybe get 
          negative moles

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
I have no idea for how long this was possible

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by KasparoVy** [comment]
Holy fuck, reminds me of the time some chemist broke atmos in the chemlab then it leaked across the whole station and mercilessly slaughtered everyone

**Comment by hal9000PR** [comment]
fastmos doesn't exist anymore.

**Comment by AffectedArc07** [comment]
> fastmos doesn't exist anymore.

For now
