### ISSUE TITLE
Dream Daemon killing connection

### ISSUE THREAD

**Issue by Raeschen** [ParadiseSS13/Paradise#10245]
**Problem Description**:
On trying to connect, get the following; https://i.imgur.com/LXrLhSy.png

**What did you expect to happen**: 
to be able to connect

**What happened instead**:
always that error message

**Why is this bad/What are the consequences:**
unable to play :(

**Steps to reproduce the problem**:
Potentially, clearing cache and then trying to connect?

**When did the problem start happening**:
After i cleared the cache due to some other random issues, about midday GMT+1 today. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Tried different accounts, different hardware, different internet connections. tried uninstalling/reinstalling, different versions, restarts, so on.
Other servers work fine.
Partner's PC/account also has the problem.
Talking to some people in discord seemed to indicate it MIGHT (might not) be related to a PR on caching? this: https://github.com/ParadiseSS13/Paradise/pull/10235/files

**Comment by SomeSortaSquid** [comment]
I can pretty much confirm it's cache-related.
Error appears only if Paradise cache is not present.
Cache of a private server running an outdated server code got properly updated and allowed connection.
Shared said cache with people who experienced the error and it solved the issue.

No idea what causes it, but it seems like the server currently can't create its own cache.
Normally, it should download resources into a temporary folder and then compress them into byond.rsc.
During Dream Daemon killing connection error, temporary folder is created, but nothing is downloaded.

**Comment by Raeschen** [comment]
can confirm, recieved a copy of byond.rsc and it fixed the problem for me allowing me to connect - works well as a workaround until the problem is fixed

**Comment by variableundefined** [comment]
Likely to be a server issue. We're working on it.
