### ISSUE TITLE
Syndicate borgs are 'Agent Colour' in traitor radio.

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#10248]
**Problem Description**:
Syndicate borgs show up as 'Agent Colour' in the unkn comms (traitor comms)

**What did you expect to happen**: 
They should appear with their borg name; they only appear on nukie rounds.

**What happened instead**:
They get weird Agent names when they should not.

**Why is this bad/What are the consequences:**
Can be slightly confusing for nukies.

**Steps to reproduce the problem**:
Be Syndicate borg.
Talk in traitor comms.
Cry as your labelled something you are not.

**When did the problem start happening**:
Almost certainly after #9902

**Comment by KasparoVy** [comment]
Agent beep, boop, clabk and clunk.

**Comment by alex-gh** [comment]
Oops. I'll fix it up later today.
