### ISSUE TITLE
NTTC Reset doesnt update console

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#10257]
**Problem Description**:
NTTC admin reset verb doesnt work properly

**What did you expect to happen**: 
The configuration to get cleared and console updates

**What happened instead**:
![image](https://user-images.githubusercontent.com/25063394/48661989-f73de480-ea72-11e8-8130-6bcadecec0c2.png)
The config cleared but console didnt update

**Why is this bad/What are the consequences:**
Using this verb bricks configuration until reboot

**Steps to reproduce the problem**:
Install or make NTTC config
Press verb
Speak in radio
Look at console
Notice difference
SCREAM

**When did the problem start happening**:
When NTTC got merged

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

**Comment by AffectedArc07** [comment]
The console doesn't update, but actual comms does, debating whether to leave this open or not

**Comment by Shadow-Quill** [comment]
@Fox-McCloud This has been fixed.
