### ISSUE TITLE
you can set sechud statuses on people while dead.

### ISSUE THREAD

**Issue by craftxbox** [ParadiseSS13/Paradise#10250]
**Problem Description**:
you can set sechud statuses on people while dead

**What did you expect to happen**: 
it to not set the status

**What happened instead**:
it set the status

**Why is this bad/What are the consequences:**
dead sec officers marking their murderer as wanted while dead

**Steps to reproduce the problem**:
die
examine someone
click criminal status link
set status

probably works with medhud aswell, but not confirmed.

**Comment by craftxbox** [comment]
i plan on PRing a fix for this, so others know.

**Comment by KasparoVy** [comment]
Bad boys bad boys, what you gonna do...
