### ISSUE TITLE
Can't Mousewheel Scroll with Fancy NanoUI

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#10251]
**Problem Description**:
What is the problem?
Can't use scrollwheel to move window contents up and down in fancy nanoUI

**What did you expect to happen**: 
I expected to move the contents of the window up and/or down using my mouse's scroll wheel

**What happened instead**:
Nothing at all, I had to click the bar and move it like a heathen

**Why is this bad/What are the consequences:**
I have a wheel and I cannot scroll with it

**Steps to reproduce the problem**:
Open a fancy nanoUI and scroll

**When did the problem start happening**:
After #10221

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I was a nerd nuking genomes and my fancy nanoUI window was unscrollable on all of the machines I interacted with in the round (clothing vendors, cryotubes, cloning/DNA consoles)

**Comment by tigercat2000** [comment]
This happened after #10221, I tested it on vanilla nano because I noticed the behavior while working on fancy nano. The issue is that IE is shit and focusing on the wrong elements will render it unscrollable.

**Comment by KasparoVy** [comment]
Shit. Editing the issue to mention 10211 instead

Is this still an issue or just IE being what it is?

**Comment by tigercat2000** [comment]
It's an issue but I have no idea how to fix it.

**Comment by Certhic** [comment]
@tigercat2000 I think you're blaming the wrong change.

Remove this style line and scrolling should work:
https://github.com/ParadiseSS13/Paradise/blob/7cff5db998b88685e6f12e49864068e79c1e1699/nano/styles/_fancy.less#L9

It's not going to be pretty though.

**Comment by KasparoVy** [comment]
What's that do in our case, out of curiosity?

**Comment by Certhic** [comment]
That rule belongs to #cornerWrapper, which is the element that has the focus. The overflow rule determines if you can scroll through an element.

**Comment by KasparoVy** [comment]
Thanks for the explanation.
Is there a way to drop a hook in scrolling to move the focus to a scrollable element then move back once scrolling is done?

Hacky as fuck but I've no clue if that's a workable idea.

**Comment by tigercat2000** [comment]
@Certhic `overflow: auto` means you can scroll in that element if it's too long for the window... infact, the reason UI windows work when you first open them is becasue #cornerWrapper is focused... the issue is when you focus on any other elements...
