### ISSUE TITLE
Supermatter shard doesn't dust people it slams into

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10256]
**Problem Description**:
What is the problem?
At least when moved by genetics telekinesis power, sm shard won't dust mobs it slams into.

**What did you expect to happen**: 
Why do you think this is an issue?
dude gets slamdunked by SM and turn to bones

**What happened instead**:
How is what happened different from what you expected?
dude gets donked and nothing happens unless he's a dumbdumb and touch the SM himself

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

RIP epic genetics hijack greentext unless this is fixed 

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. get genetics telekinesis 
2. throw sm shard using grab intent telekinesis into someone
3. they fine

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

probably always been that way, just oversight

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
only tested locally for some strange reason I can't get a sm shard and dust people with it every round

**Comment by Citinited** [comment]
Somehow I'm glad this is a bug 😄

**Comment by KasparoVy** [comment]
Glad this exists.

**Comment by datlo** [comment]
if somebody gets 1. hijack 2. telekinesis 3. a sm shard they deserve to stomp the station using em

either way the SM shard shouldn't be movable by telekinesis in the first place if it's a balance concern, right now it's just logically inconsistent

**Comment by variableundefined** [comment]
Probably best by giving it move resist and have telekinesis check for it or something like that.

**Comment by Mitchs98** [comment]
Can't give it move resist until the port is merged ;p.

That being said. I don't entirely consider this a bug, a bug the SM can be moved by TK yes. A bug you can't loldust with it...not really.

**Comment by datlo** [comment]
This was fixed with SM update.
