### ISSUE TITLE
Antag banned mobs can't be revived

### ISSUE THREAD

**Issue by Xantholne** [ParadiseSS13/Paradise#10266]
**Problem Description**:
Players that are antag banned, and have a ghost forced into their body, cannot have the mob be revived through traditional means outside admin rejuvs and healing staves because both ckeys are tied to the same mob.

**What did you expect to happen**: 
The mob in question to be revived.

**What happened instead**:
One would be in the mob, the other client would receive the being revived, please enter body message.

**Why is this bad/What are the consequences:**
It completely removes people from the round while making it seem like they are there

**Steps to reproduce the problem**:
Be antag banned player, get forced into revolution, cult, etc. Ghost player is instantly forced into mob. Ghost player dies as the original mob, both ghost player and original player cannot be in the same mob at once.

**When did the problem start happening**:
Unknown if it was always here or not and no one noticed

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Vampires+Agents with a forced Revolution and random Revenant spawn.

**Comment by SabreML** [comment]
Saw this on a Blood Cult testmerge on 05/11/2020, so it's still an issue.
