### ISSUE TITLE
NanoUI/Asset Caching issue

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#10267]
**Problem Description**:
Right, well. Ever since the NanoUI updates I've had major issues with the UI of vendors and such at times. It just doesn't show up whatsoever. Reconnecting sometimes fixes it, sometimes not. I tried clearing cache and such but no dice. I'm not sure why, it doesn't happen 100%, but it does happen. The Changelog also wouldn't load.

**What did you expect to happen**: 
I expected to be able to use vendors and other such things with menus freely.

**What happened instead**:
White screen of death. https://i.gyazo.com/bb1551f6e4133d6a45bfa28ae55d0d4b.png

**Why is this bad/What are the consequences:**
The inability to use ANYTHING that requires windows. Very, very bad.

**Steps to reproduce the problem**:
1. Join Game.
2. Try to use a vendor.
3. Cry at the white screen.

It's not a 100% occurring problem but it DOES happen.

**When did the problem start happening**:
Ever since the NanoUI and asset caching PR's happened.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

**Comment by Spartan6** [comment]
Uplink also does not have its normal background, has a big ol NT logo.

**Comment by AffectedArc07** [comment]
^ Same with syndicate nuke

**Comment by Spartan6** [comment]
Safe is also fucked.

**Comment by tigercat2000** [comment]
>The Changelog also wouldn't load.

This leads me to suspect you have an asset issue, not Nano. The changelog is plain HTML with a handful of cache assets. 

>Uplink also does not have its normal background, has a big ol NT logo.
>^ Same with syndicate nuke
>Safe is also fucked.

These, however, are definitely issues with fancy NanoUI, because I forgot to update a few element references to the new element that actually determines the background. @Spartan6 @AffectedArc07 Please make a new issue chain for those issues.

**Comment by tigercat2000** [comment]
@variableundefined Could you mark this PR `Cannot reproduce` - 
I seriously cannot manage to make this problem appear no matter what testing I do. In the following steps, I couldn't make it occur

>Clone a fresh copy of Paradise directly from GitHub

>Uninstall BYOND and delete the {Documents}/BYOND/cache/ folder entirely

>Reinstall BYOND from scratch with the 1454 installer on byond.com

>Run dm.exe on paradise.dme and compile the new repo as-is from GitHub

>Copy-paste my config files in so that the codebase doesn't scream about SQL

>Start DD

>Connect through the `Open` button in the BYOND pager as soon as the server says "Initializations complete"

>Start the round at 180 seconds remaining (out of 260)

>Open a UI window immediately

>It works fine...

**Comment by Mitchs98** [comment]
Again, it's not a 100% chance to happen. It can be reproduced, I'm assuming only on a live copy of the server rather than a local copy. 

Though that said here; 

> This leads me to suspect you have an asset issue, not Nano. The changelog is plain HTML with a handful of cache assets.

It's probably the asset caching PR that is at times causing the issues and not the NanoUI then.
