### ISSUE TITLE
After SR revival you can still hear cult speak as non cultist

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#10268]
**Problem Description**:
You keep the ability to hear cult speak when revived using SR as a non cultist.

**What did you expect to happen**: 
Not to hear the nerds talk about their books

**What happened instead**:
Slith could hear them discuss the harry potter books in full detail

**Why is this bad/What are the consequences:**
This will give away a lot of knowledge to non cultists

**Steps to reproduce the problem**:
1. Die
2. Get revived by SR
3. (optional maybe) stay in the revival area
4. Let a cultist talk using cult speak
5. Hear the cult speak as if you're a ghost. It has the F to follow in the text.

**When did the problem start happening**:
Slith reported this yesterday. I myself have not heard it happen before.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Cult round ofcourse. It seems as if the cult speak didn't close after he was revived.

**Comment by Ty-Omaha** [comment]
No clue whats wrong but here's relevant (I think) files

https://github.com/ParadiseSS13/Paradise/blob/4bc1a1c1efbc5e5aa379e5c75e9edb55ecf0cc0a/code/game/gamemodes/cult/cult_comms.dm#L33-L37

https://github.com/ParadiseSS13/Paradise/blob/2ee4d10516475a144195f17be617f1ae5e0cf1ef/code/modules/reagents/chemistry/reagents/medicine.dm#L710

https://github.com/ParadiseSS13/Paradise/blob/73091bf78c29d6699348b17a5412cf3b2a2a3b17/code/modules/mob/living/stat_states.dm#L42

https://github.com/ParadiseSS13/Paradise/blob/6a6100c0dd75cf555f3fcc4a17ce4e3487b7c115/code/modules/mob/living/carbon/human/death.dm#L118

**Comment by Deelite34** [comment]
As far as I remember with my cultist-cloning experiences, you can hear cultist "radio", can use cultist stuff, but can't speak in cult speak. It sounds more as if you are still a cultist, but some spaghetti code makes you lose ability to speak in cultish.

**Comment by farie82** [comment]
Slith wasn't a cultist before dying. He just kept hearing the ghost chatter while he was alive.

**Comment by Deelite34** [comment]
I just thought off something... didn't we get a feature merged in past, where you can would be able to hear ghost talk, if you are close enough to death? If so, it could be related. Ghosts can hear ghost chat, antag mind speech, and robots, and close-to-deaht person inherits it?

**Comment by farie82** [comment]
Haven't heard it happening for a while now
