### ISSUE TITLE
Plasma statue can be ignited by disbler

### ISSUE THREAD

**Issue by variableundefined** [ParadiseSS13/Paradise#10265]
**Problem Description**:
As per title. Somewhat like #7234 but this time disabler can set it off.

**Comment by KasparoVy** [comment]
I ahelped this the other night thinking it was grief, hilarious that it was really just a disabler

**Comment by variableundefined** [comment]
Yeah, I investigated further and the poor guy who got beaned did not intend it at all.

Look in statue.dm for how to fix this - It is a hardcoded typepath check for any projectile of the beam or ion type and nothing else. 

Change it to check for projectile burn damage and/or brute damage.

**Comment by KasparoVy** [comment]
I believe similar logic can be found on welding fuel tanks too
