### ISSUE TITLE
The safe is too indestructible, now admin proof guaranteed

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#10273]
**Problem Description**:
The safe cannot be deleted using the right click delete or buildmode.

**What did you expect to happen**: 
Us to be able to remove the safe or any spawned safes using a delete function.

**What happened instead**:
The safe is indestructible to everything, even admin intervention.

**Why is this bad/What are the consequences:**
We like to delete things when needed.

**Steps to reproduce the problem**:
Be admin.
Right click on safe.
Hit delete.
Log spawns to say it is deleted, safe is still there.

**Comment by Birdtalon** [comment]
lmao

**Comment by Citinited** [comment]
When you need your safe to be uncrackable
