### ISSUE TITLE
All space ruins teleportation locked

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#10282]
**Problem Description**:
Every single space ruin is teleportation protected.

**What did you expect to happen**: 
For the teleporter beacons that spawn in some ruins at round start to be accessible from the station.

**What happened instead**:
Every single ruin is teleportation locked.  Possibly something the happened to all ruins during Tzo's Syndicate depot revamp which added teleportation protection enmasse there.

**Why is this bad/What are the consequences:**
It prevents ruins that should be available for teleportation too at round start, from being teleported to.  Example is the space bar ruin which comes round start with a teleporter beacon.

**Steps to reproduce the problem**:
Let ruins spawn in round start, try doing anything teleportation related with them, and it will not work.

**When did the problem start happening**:
Since the space ruins started spawning again.

**Comment by Denthamos** [comment]
This bug still has yet to be addressed which is an issue for some antag modes.  There is no reason for random spawn placement and spawn % ruins like the bunker, space bar, ect to be tele locked since they are not in the same location every single round.

**Comment by Aurorablade** [comment]
okay looking at it the tele_proof var that was set up for the syndicate depot stuff by DEFUALT should be set to 0 for all areas save for the depot and one away mission. so unless the logic is fouled up this should NOT be the issue. The only thing i can think of right at the top of my head is its something in the ruin placement code vs the teleport code. or something in how the level traits are supplied.

**Comment by Reyblood** [comment]
I've been to space bar a few times, and the Beacon there is always off. Maybe the problem with the space bar is because the teleporter beacon is off? As everytime i turned it on, i was able to teleport onto the space bar.

**Comment by Denthamos** [comment]
Appears to be fixed now, closing bug report.
