### ISSUE TITLE
(potential) lack of materials in wizard gateway away mission

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#10298]
**Problem Description**:
The right 'maintenance/engine section' area of the wizard school gateway has an incomplete telecoms setup, which is probably intended to be buildable. You get 3 machine frames, 3 circuit boards (receiver, sender, mainframe) and a pile of specific components like 'subspace ansibles' and so on.
The intent is clearly that you can use them to build the machines. Except that they aren't the right kind of components. You are missing 2 micro manipulators and a hyperweave filter, and have a scanning module leftover.

**What did you expect to happen**: 
The entire setup is set up so that you can build the stuff, so I expected to have the materials to build the stuff.

**What happened instead**:
I was sad and couldn't finish the telecom mainframe.

**Why is this bad/What are the consequences:**
the room of the gateway becomes totally pointless. People waste their time. With such specific components there, it seems clear you are supposed to be able to build it, but I expect at some point after the gateway was made the components needed for a telecom mainframe were changed and nobody updated the mission.

**Steps to reproduce the problem**:
Go to the wizard gateway mission, head right after the bathrooms, try to put the components there into the machine.

**When did the problem start happening**:
no clue

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
This might not, strictly speaking, be a bug, but it seems very clearly intended to be buildable. unless it's supposed to be a bait and switch? If it is, please close this issue.

**Comment by Spacemanspark** [comment]
It's intentional. I'd make a post on the forums as this isn't a bug.

**Comment by TDSSS** [comment]
I can't fathom why you'd decide to bait and switch people like that, but alright. Not an issue then.
