### ISSUE TITLE
Genetics bug with chameleon and cloak of darkness

### ISSUE THREAD

**Issue by alphaJackal** [ParadiseSS13/Paradise#1030]
Injecting one's self with both seems to disable both of them.

EDIT: After some experimentation, it seems that cloak of darkness doesn't function at all.

**Comment by Robertha89** [comment]
it's kinda intended, but also not, they work with reducing the alpha of the icon, as i did balance chameleon to be as good as cloak of darkness. both powers got their strength and weaknesses, and having both seems pointless, if it ain't dark, you need to stand still, if it's dark you don't need to stand still.

But both powers work, not sure how cloak of darkness work with the new lighting system.

**Comment by alphaJackal** [comment]
Whenever I stood in shadow with just cloak of darkness, having removed chameleon, my character's visibility was completely unchanged.
