### ISSUE TITLE
Mime Outfits Don't Mix With Sec Gear

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#10306]
**Problem Description**:
When wearing a mime outfit, putting on armor or an armored security jacket looks goddamn awful.

**What did you expect to happen**: 
I expected to have the items on over my mime clothes like usual.

**What happened instead**:
It looks absolutely horrid, with some weird grey/white mixture. The jacket looks particularly bad. (I had screenshots but lost them when they didn't save right)

**Why is this bad/What are the consequences:**
It's bad because it looks bad and security mimes **will be a thing.**

**Steps to reproduce the problem**:
1. Be Mime
2. Acquire security armor or jacket
3. Put on the items and recoil in horror.

**When did the problem start happening**:
It might have to do with the new jacket, or some of the clothing changes.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I was a drask mime, and drask have clothing issues in general. It might be related to that.

**Comment by Mitchs98** [comment]
The new jacket isn't new, it's been in the code. It was only recently just added to the lockers. I'm assuming it's to do with the clothing changes or another issue to do with item overlays with BYOND or something like quite a lot of other things are broken from.

**Comment by Breenland** [comment]
I’m not home now, but I’ll try to grab one. Alternatively you can test it personally. For clarification, it’s not the HOS jacket, but the recently implemented security jackets.

**Comment by Mitchs98** [comment]
Again; they aren't recently implemented. They just were loadout only until I put them in the lockers :p

**Comment by Breenland** [comment]
What I mean, is they’re there and they weren’t (outside of loadouts) easily accessible. The issue might have been present previously, but wouldn’t have had a real opportunity to cause it, haha.

**Comment by Henri215** [comment]
Tested and those outfits dont have any issues with them anymore.

**Comment by warriorstar-orion** [comment]
Can't reproduce on 2c96b00fc41960325f5555bbd8e8c3c587535410, which was a day before the issue was filed, which makes me assume it's a BYOND rendering thing from 512, similar to other issues filed around the same time, so no real use in attempting to bisect it further.

![2023_05_30__10_37_11__Paradise Station 13](https://github.com/ParadiseSS13/Paradise/assets/59303604/25ac7c72-3ded-48ff-b6c7-09945ec7c6b6)
