### ISSUE TITLE
Teleporter maintenance isn't shielded from radiations

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10309]
**Problem Description**:
What is the problem?
Teleporter maintenance below cappy's office looks like a small maintenance area but isn't technically one, so it's not rad shielded.

**What did you expect to happen**: 
Why do you think this is an issue?
Looks like maintenance, should act like maintenance.

**What happened instead**:
How is what happened different from what you expected?
Isn't maintenance. Aaaah rads.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
everybody ded

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

1. radstorm
2. go into teleporter maintenance
3. i diagnose you with dead

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

dunno

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

seen not working on 22/11/2018 at 11:46 am UK time on live server

**Comment by Spartan6** [comment]
This would involve allocating it as it’s own maintenance. It would probably be better to convert it to some form of hallway to just avoid confusion rather than make an APC for a 3 time area.

**Comment by datlo** [comment]
Yeah I'd agree making it into a hallway. Why is there a shitty maintenance area next to the captain's office anyway? Roll out the red carpet for the captain going to his teleporter. And the tators breaking in.
