### ISSUE TITLE
Internals box sprites dont show up

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#10312]
**Problem Description**:
Internals box sprites dont show up

**What did you expect to happen**: 
The sprite to render

**What happened instead**:
This
![image](https://user-images.githubusercontent.com/25063394/48917238-a6b4f580-ee7d-11e8-93ce-be11e0fd3ddd.png)

**Why is this bad/What are the consequences:**
The box not having a sprite means its hard to interact with

**Steps to reproduce the problem**:
Spawn in and open bag

**When did the problem start happening**:
Probably with the merge of #10300 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

**Comment by Citinited** [comment]
Mapdiffbot and icondiffbot worked at some point, not sure when they broke haha 😄
