### ISSUE TITLE
Blood crawling slaughter demons make rubber duckies squeak

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#10334]
**Problem Description**:
see title

**What did you expect to happen**: 
not to make things squeak when moving through them via blood crawl

**What happened instead**:
ducky sqeauked

**Why is this bad/What are the consequences:**
high-tech slaughter demon detection technique

**Steps to reproduce the problem**:
be demon
bloodcrawl
move over rubber ducky

**When did the problem start happening**:
happened today, no idea how long it was a thing, but I suspect the squeak component thingy is to blame.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I think I was an admin-spawned slaughter demon as there was no wizard in the round (unless slaughter demon is a super-rare event I don't know about)

**Comment by Denthamos** [comment]
It does this jaunts too from vampires, shadowlings, and wizard.  Passing over a duck/horn/ect will cause them to make noise.

**Comment by chuga-git** [comment]
This is still a thing and due to how jaunts and Crossed() interact.
