### ISSUE TITLE
Defib's are not working under most circumstances.

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#10333]
**Problem Description**:
Defibs are not working against mobs with a ckey under various repeatable circumstances.

**What did you expect to happen**: 
When a person's ghost is in their body and the defib is applied within the time limit with no damage, the defib to be successful.

**What happened instead**:
The defib gave a `The defibrillator buzzes: Resuscitation failed.` error. No information on why.

**Why is this bad/What are the consequences:**
Defibs are important to getting players back into the round quickly.

**Steps to reproduce the problem**:
Spawn two human mobs and a defib.
Give one human 400 damage and then -500.
Give the other a defib and attempt to revive.
If the mob has no assigned ckey, this will work and revive them. If they have an assigned ckey, this will not revive them under any circumstances. This was tested with both the other user not ghosting after dying and ghosting after dying, and was replicating with multiple tests, including with borg defibs.

**When did the problem start happening**:
As far as I'm aware, today is when it started to occur, I don't see any other complaints about it prior.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I saw this runtime in the logs but was not sure if this was a part of the issue.
`[2018-11-24T15:36:14] Runtime in code/game/objects/items/weapons/defib.dm,506: Ghost of name Ruum-Ovv-Oumn is bound to Ruum-Ovv-Oumn, but lacks a client. Deleting ghost.`
`src: Unknown (as Ruum-Ovv-Oumn) (blessedtuna) (/mob/living/carbon/human)`
`src.loc: The floor (142,112,1) (/turf/simulated/floor/plasteel)`
`usr: JeffBot (thesardele) (/mob/living/silicon/robot)`
`usr.loc: The floor (142,113,1) (/turf/simulated/floor/plasteel)`

However, I don't believe this is anything to do with it. 10272 10330 are also test merged, but I'm not sure if either of these are to do with it either.

**Comment by Spartan6** [comment]
This was an issue with #10272 while test merged.

**Comment by Ty-Omaha** [comment]
it's been fixed https://github.com/ParadiseSS13/Paradise/pull/10272/commits/0833b5e05cd9909f8be2a66be083cb608547026e
