### ISSUE TITLE
Vampire Space Suit Bug

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#1033]
Im guessing this comes from some snowflake vampire code.

A vampire can't attatch a helmet to a spacesuit, and would have to use one of the types that don't need it, can probably be used for meta.

While vampires can't travel in space too safely, the station is often vented.

**Comment by tigercat2000** [comment]
Unable to replicate, were you aiming for the actual head zone?

**Comment by Robertha89** [comment]
I was, i might have had another intent, cause i noticed something today that indicated that other intents prevents it.
