### ISSUE TITLE
Can't Drop Mime Gun/Mime Gun Persists

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#10346]
**Problem Description**:
Yes, I know this is intentional for the most part. However the way I'm talking about dropping it is likely not intended. If you use the mime finger gun(I only tested the fake one) and break your vow of silence the gun persists instead of deleting itself or getting an option to drop it so it CAN delete itself. It just stays in your hand forever until you're able to redo your vow 5 minutes later.

**What did you expect to happen**: 
I expected it to disappear and me to retain normal use of my hand.

**What happened instead**:
It stayed the full time, disallowing me to use my hand.

**Why is this bad/What are the consequences:**
It's not too major of an issue, I am unsure if it's even fixable. However. It's quite annoying and not immediately obvious considering you can't even activate the spell without vow turned on.

**Steps to reproduce the problem**:
1. Get Finger Gun Manual.
2. Learn.
3. Toggle Vow.
4. Deploy gun.
5. Toggle Vow Off.
6. Scream as you have an antidrop pointless thing in your hand for 5 minutes.

**When did the problem start happening**:
Since its origins, I assume.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: N/A

**Comment by datlo** [comment]
Well i guess i forgot to actually have that explained by the item but you can use the gun in hand to holster it. 

Id add this explained to the string when you try to fire with vow of silence off
Alternatively just qdel when you fire without vow
