### ISSUE TITLE
non-eared species require ears to hear.

### ISSUE THREAD

**Issue by craftxbox** [ParadiseSS13/Paradise#10344]
**Problem Description**:
non-eared species require ears to hear.

**What did you expect to happen**: 
to be able to hear, without ears on any non-eared species

**What happened instead**:
built IRC's, and assumably slime people aswell require ear organs to hear

**Why is this bad/What are the consequences:**
IRC require organic ears to hear, slime people need ears when they shouldnt need to

**Steps to reproduce the problem**:
create an irc in robotics
irc is unable to hear

**When did the problem start happening**:
probably #10166 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Mitchs98** [comment]
I can confirm slime people require ears to hear where they should not. Their core is their omni-organ for lack of a better term, it should not be. IRC's and also Golems spawn earless, when they should not have ears at all.

IPC's also for some reason have ears, where they should not need them at all either.

**Comment by tigercat2000** [comment]
This isn't a bug in the way it's presented. These species require ear organs like the rest of them, including IPCs and IRCs. The actual issue here is that those races require some fucky hacks to make them actually work - IPCs and IRCs will eventually get mechanical ears when I have some time to add them.

**Comment by craftxbox** [comment]
its more an oversight than a bug.

**Comment by taukausanake** [comment]
I can already see people ripping off the ears of furry races just so they can hear. Unless we still don't have that functionality, which we should
