### ISSUE TITLE
Showing Paper does not work.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#10353]
**Problem Description**:
So basically, if you try to thrust paper into someones face to show them it it no longer works. It instead outputs. "You show the paper to X." even if you're not the one showing the paper.

**What did you expect to happen**: 
I expected to be shown the contents of the paper.

**What happened instead**:
Nothing happened.

**Why is this bad/What are the consequences:**
I had to manually read the paper.

**Steps to reproduce the problem**:
1. Get paper.
2. Write.
3. Thrust into nearest face.
4. Marvel as it does nothing.

**When did the problem start happening**:
Unsure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: N/A

**Comment by SabreML** [comment]
Half fixed by #15270, not sure about it not showing up though.
