### ISSUE TITLE
IPCs don't revive when posibrain replaced

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10356]
**Problem Description**:
What is the problem?

After removing a posibrain from an IPC, if the posibrain is replaced, the IPC doesn't revive.

**What did you expect to happen**: 
Why do you think this is an issue?

The IPC to revive when the posibrain is placed inside.

**What happened instead**:
How is what happened different from what you expected?

They did not.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

IPC peeps can't come back if posibrain is placed back in it's cubby.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

1. Remove posibrain from IPC.
2. Return to IPC
3. Observe how they're dead, Jim.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

Unknown.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

N/A

**Comment by KasparoVy** [comment]
Rest In Positronics

**Comment by sampaiii** [comment]
i'm late here but, the IPC can revive if they exit their corpse and re-enter it after inserting the brain
still strange, though

**Comment by craftxbox** [comment]
workaround: fixed by having the person in the brain ghost then return to corpse.

**Comment by Shadow-Quill** [comment]
Seems to also be fixed if you perform percussive maintenance

**Comment by Spaghetti-bit** [comment]
No longer an issue.
