### ISSUE TITLE
AI Minisat

### ISSUE THREAD

**Issue by Ridgyaxe** [ParadiseSS13/Paradise#10368]
**Problem Description**:
As the Sat is right now, everybody breaks in through the back. EVERYONE. Not a SINGLE time has anyone came after me as AI, and gone through the actual minisat. This is a problem, as the Minisat is supposed to be a defensive 'wall' I would imagine, for people that want to break in.

**What did you expect to happen**: 
Far too easy to kill the AI, even without Ions. Especially without Ions. The CE can just break in through the back, use his RCD to build walls, and waltz right on in.

**What happened instead**:
Isn't it supposed to be a defensive barrier from other players that want to get you?

**Why is this bad/What are the consequences:**
Again, the AI minisat does NOT protect the AI, it just lets everyone know where it is.

Anything else you can tell us. Maybe make the minisat more circular/square in shape, so that people actually have to go through the sat to get at it.

**Comment by Taaketa** [comment]
This is why rogue AIs have tools to assist in core defence and Borgs. There have been plenty of Rogue AIs who have won rounds without a problem. He'll the cheesy tactic for the walls to the rear is to have an engineer borg with sheet metal patch the wall has they disassemble it. Or alt-shift click and RCD windows on the floor with go over the walls. So now they've got to blast apart windows too.

**Comment by Spartan6** [comment]
This is not a bug. If you wish to actually change this, make a suggestion on the forums, speak in #coder_chat on the discord or make a Pull Request to change the layout.

**Comment by AffectedArc07** [comment]
What spartan said
