### ISSUE TITLE
Deck of cards related issue, infinite playing cards

### ISSUE THREAD

**Issue by PootisMan1559** [ParadiseSS13/Paradise#10366]
**Problem Description**:
You are able to take a card from a "hand of cards" infinite times, you also don't have to be near the "hand of cards" You can also deal cards through walls and one sided windows.

**What did you expect to happen**: 
I did not expect to break reality by pulling inifnite cards from one hand of card. And not being able to throw cards through walls.

**What happened instead**:
I can make infinite cards, even when I don't have the "hand of card" in my hand. I am a wizard and can do magics with cards.

**Why is this bad/What are the consequences:**
You can make infinite cards, and you can pull a card from a "hand of card" anywhere; because you do not need to have it near or on you to work. You can throw cards through a window or wall.

**Steps to reproduce the problem**:

**Steps for the duplicating of cards**
-Acquire a deck of cards.
-Take three cards and put them together to make a "hand of cards"
-Click the "remove a card" icon in the top left corner of the screen multiple times.
-Keep the window asking you which card you want to remove from your hand open.
-Throw the "hand of cards" away (this can be skipped, just pointing it out that it can be done even if you don't have it on you or near you)
-Remove a card. If you clicked the "remove a card" multiple times, you can remove the same card and create a duplicate; as the window asking you which card to remove keeps popping up.

**Steps for the throwing cards through windows and walls**
-Acquire a deck of cards.
-Walk infront of a window/wall
-Click the "deal" or "deal multiple card" in the top left corner of the screen
-Deal a card to yourself while looking at the window/wall

**When did the problem start happening**:
When the deck of cards got changed.

**Comment by Mitchs98** [comment]
Ahhh yes. The old infinite fish method, though in card form. :clap:

**Comment by Scout360Pyro** [comment]
From what I see the root issue is that window interface asking what card you want can be brought up multiple times. I think if you put in a line to check first if another instance of the window is already open the problem should be fixed.
