### ISSUE TITLE
AI Cannot Recall Emergency Shuttle (Non-Crew Transfer)

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10360]
**Problem Description**:
What is the problem?

AI can't recall the emergency shuttle.

**What did you expect to happen**: 
Why do you think this is an issue?

AI to be able to recall the emergency shuttle.

**What happened instead**:
How is what happened different from what you expected?

AI was not able to recall the emergency shuttle.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

The AI cannot recall the shuttle in event of Command Member requesting it be recalled or Quarantine Laws in effect.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

1. Be AI.
2. Call Emergency Shuttle.
3. Marvel how neither the HUD button or the verb panel cannot recall the shuttle.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

Unknown.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Nope.

**Comment by Kyep** [comment]
AI isn't meant to be able to recall the shuttle, for balance reasons.

**Comment by Shadow-Quill** [comment]
Guess everyone on the discord was lying to me :P
