### ISSUE TITLE
Asset Caching Issue

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#10378]
**Problem Description**:
I'm not sure why it was closed the first time without it being addressed at all. However, I and some others have been having a _lot_ of issues with menus not loading properly. All menus, including the changelog. Tigercat said it was an asset caching issue which leads me to believe it was something that happened with the asset caching PR. Ever since then I've been white screening on vendor menus, even the changelog, at random. Reconnecting _sometimes_ fixes it, but often not, including reconnecting 10 times in a row.

**What did you expect to happen**: 
I expected to not have to relog constantly to be able to use the majority of the games' functions.

**What happened instead**:
I had to relog to even have a chance to use the games functions that revolve around menus.

**Why is this bad/What are the consequences:**
80% of things to do in the game revolve around using a menu at some point to do so. This affects everything with a menu, including PDA. Fix NanoUI does not consistently fix it so it leads me to believe it's an asset issue as Tiger suggested.

**Steps to reproduce the problem**:
1. Try to use anything.
2. Watch it whitescreen and bar you from doing so.
3. Cry as you can no longer do most things.

**When did the problem start happening**:
Ever since the asset caching PR.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: N/A

**Comment by tigercat2000** [comment]
I said it sounds like an asset problem on _nano_ windows.
The changelog doesn't even use the actual asset_cache system. It can't be it's fault. 
How long, exactly, are you giving the game before you try to open the window, and how many times do you try to open it before relogging?

**Comment by Mitchs98** [comment]
I give it several minutes each time I do it, and generally try 5 or so times to open it before relogging. I've relogged and been able to open one window then the next window there on not work. I've tried relogging 5 times in a row before and it still hasn't worked. It's sporadic when it actually happens but when it does it's hell trying to get it to work again, sometimes it just doesn't work again at all like the most recent round I played where I could access no vendors except the merchvendor.

**Comment by Mitchs98** [comment]
It's honestly seeming to get worse/be more frequent. Last round I had to reconnect twenty times and some things still did not work or stopped working at random, INCLUDING PAPER. I have no idea what is going on, it wasn't doing this at all until recent month or two.

**Comment by Shadow-Quill** [comment]
I'm sorry, your paper cannot be loaded at this time. Please try reading at a later time, or refreshing your eyes.

**Comment by KasparoVy** [comment]
`say *blink_r`
`say *blink_r`
`say *blink_r`
`say *blink_r`
`say *blink_r`

**Comment by Mitchs98** [comment]
Turns out a temporary fix to this is clearing IE cache and adding Dream Seeker to your firewall? It may actually be a BYOND issue.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/issues/13728
