### ISSUE TITLE
Gamebreaking Infinite Gibber Bug

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#10372]
**Problem Description**:
Righto. So. Last round I found out there's a _very_ gamebreaking bug with the Gibber. Rather, server crashing. If you load a thing in and spam click it, despite it saying it cannot do, you will infinitely stack gibbing procs and thus infinitely gib the same target over and over in very quick succession to the point that it'll kill the server. Didn't think to check to see if it was a runtime causing it or not...I'll do that tomorrow if no one else does.

**What did you expect to happen**: 
I expected my meat sack to gib once and no longer exist.

**What happened instead**:

I made 500000000 meats. Sulfur did the same and nearly crashed the server.

**Why is this bad/What are the consequences:**
You can literally very easily crash the server.

**Steps to reproduce the problem**:
1. Grab anything gibbable.
2. Shove it right into the gibber.
3. Spam click it like its goin' outta style.
4. Watch your server crash and burn.

**When did the problem start happening**:
I have no idea.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: N/A

**Comment by Necaladun** [comment]
Thanks so much for reporting this, hopefully fixed soon, 'cause having to stand watch over the gibber/deleting it at round start is gonna be boring AF!

**Comment by Birdtalon** [comment]
It'll just be lack of a sanity check. Easy fix.
