### ISSUE TITLE
Opening / closing closets or crates with rubber ducks, horns etc. will make squeaking noises

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#10371]
**Problem Description**:
Title

**What did you expect to happen**: 
Merely opening and closing crates / closets shouldn't make things squeak

**What happened instead**:
They squeaked

**Why is this bad/What are the consequences:**
Oh god imagine if the clown got 100 horns and a locker

**Steps to reproduce the problem**:
1. Put rubber duck inside crate
2. Open/close repeatedly
3. Listen to incessant quacking

**When did the problem start happening**:
Since the squeak component refactor, most likely

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Apparently this also happens with backpacks? Probably anything that causes a change in `loc` I'm guessing

**Comment by variableundefined** [comment]
Not a bug but WAD. You might want to consider expanidng the delay.

**Comment by Citinited** [comment]
Aahh, noted!

🦆 🦆 🦆

**Comment by variableundefined** [comment]
You might want to consider refactoring forcemove so it can optionally not call crossed
