### ISSUE TITLE
can't smash a beer bottle on a monkeys head

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#10370]
**Problem Description**:
I wanted to abuse my virology monkeys with my alchoholic beverages but instead of smashing it over their heads I tried to force feed them it.

**What did you expect to happen**: 
I expected a head to be smashed in with a bottle

**What happened instead**:
It said the bottle was empty and i couldn't give beer to my monkeys

**Why is this bad/What are the consequences:**
I need to discharge my anger at something. Thats what these monkeys are for right?

**Steps to reproduce the problem**:
1. Grab a beer bottle (haven't checked with other bottles)
2. Try to smash it over a monkeys head

**When did the problem start happening**:
I've tried this on 29-11-2018

**Comment by variableundefined** [comment]
Not really an issue. Beer bottle as a subtype of soda can, not bottle, so they can't be smashed.
