### ISSUE TITLE
Nuclear Emergancy round end "TC used" list not displaying all bought items

### ISSUE THREAD

**Issue by Daylight2** [ParadiseSS13/Paradise#10375]
**Problem Description**:
At the end of the round on a nukie game, only some (perhaps one agents) TC purchases are noted in the end of the round report

**What did you expect to happen**: 
Why do you think this is an issue?
Be able to see everything the nukies have bought (separated into what each individual agent bought if possible)

**What happened instead**:
Only some of the TC purchases were noted down
![capture](https://user-images.githubusercontent.com/18598676/49234220-518a5e00-f400-11e8-82b7-92ef138ae1c7.PNG)

**Why is this bad/What are the consequences:**
It would be nice to know what gear the nukies bought

**Steps to reproduce the problem**:
Play on a nuclear emergancy round, look at the round end report

**When did the problem start happening**:
As far as i know, this has been a problem for a long time. Just thought it might be appropriate to make a issue for it

**Comment by daylight2** [comment]
Also, just noticed that "disk" is misspelled on the end of round report (see .PNG above)

**Comment by Ar3nn** [comment]
Nuke ops usually buy as a team giving all their tc to the leader anyway, so individual op purchases would just show the leader bought everything. So that's a wash but showing everything should be a thing
