### ISSUE TITLE
Borgs can flap their wings

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10385]
**Problem Description**:
What is the problem?

Title.

**What did you expect to happen**: 
Why do you think this is an issue?

No flappies.

**What happened instead**:
How is what happened different from what you expected?

Flappies.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Borgs are not birds. They need to acknowlege this.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

1. Be cyborg.
2. *aflap
3. _ANGRY BIRD NOISES_

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

Today.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Nope.

**Comment by Citinited** [comment]
Humans also aren't birds but that doesn't stop them either *aflap

**Comment by KasparoVy** [comment]
Ain't nuffin wrong.

**Comment by Mitchs98** [comment]
Seems like a feature to me.
