### ISSUE TITLE
Dance machine runtimes with watched by AI

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#10388]
**Problem Description**:
[2018-12-01T03:25:01] Runtime in dance_machine.dm,399: undefined variable /mob/camera/aiEye/var/resting
   proc name: dance4 (/obj/machinery/disco/proc/dance4)
   src: the radiant dance machine mark... (/obj/machinery/disco)
   src.loc: Light floor (185,139,1) (/turf/simulated/floor/light)
   call stack:
   the radiant dance machine mark... (/obj/machinery/disco): CKEY(CHARNAME (AI Eye) (/mob/camera/aiEye))

**What did you expect to happen**: 
No runtimes when AI Eye watches a dance machine.

**What happened instead**:
Runtimes

**Why is this bad/What are the consequences:**
Runtimes

**Steps to reproduce the problem**:
Be an AI.
Move your eye to an active dance machine.

**Comment by Citinited** [comment]
Ghosts probably also runtime
