### ISSUE TITLE
Bugged Blindness

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#10380]
**Problem Description**:
There was two players who had blindness that had no recorded damage and isn't from genetics. They had blindness that would be caused by damage but yet isn't. I fixed their eyes with a brute trauma kit in surgery but the game said they had no damage, I allowed the kit to heal anyway to be sure and it fixed theirs eyes and allowed them to see.
**What did you expect to happen**: 
I expected to be able to fix it via oculine or mutadone.
**What happened instead**:
Oculine did not repair it and it was not a issue of genetics but instead required me to fix it via surgery.

**Why is this bad/What are the consequences:**
It's a problem that most players will not know and once they try surgery, they will think it isn't that and stop midway since the game tells them there is no damage and will not proceed fully with the brute trauma kit. This may result in the player missing out on game-play and most likely result in them being willingly killed and cloned wasting their time and the time of the medical staff in game. (I do not know if cloning would actually fix the blindness)

**Steps to reproduce the problem**:
I do not know how to reproduce the issue but I think a rad storm is a variable/source of the problem since the QM stayed in it and became a walking radiation man, which I swiftly fixed but found later he was blind for some reason.

**When did the problem start happening**:
11/29/18 around 10:20 PM PST
**Possibly related stuff (which game mode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It was a Traitor/Vampire round, Hive-lord Cores could not fix the issue, they had nothing wrong with their genetic structure which I manually checked in a DNA Modifier in genetics, and oculine didn't repair any damage. I think the rad storm that happened that round may have something to do with it. I also ahelped it and two admins said he had no issues with his eyes or any genetic defects to make sure it was bugged and it turned out to be.

**Comment by FunnyMan3595** [comment]
There's not enough information to reproduce this, and the issue has likely been fixed sometime in the intervening years.
