### ISSUE TITLE
Captain's Protective Case Drops Bolts

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10384]
**Problem Description**:
What is the problem?

When breaking the Display Case in the Captain's Office, the bolts drop even when power was cut to the APC.

**What did you expect to happen**: 
Why do you think this is an issue?

The alarm to not go off, and the bolts to not drop.

**What happened instead**:
How is what happened different from what you expected?

The siren sounded, and the bolts dropped.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Tatortots that try to  be smart about stealing the gun can't be smart about stealing the gun.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

1. Cut power to Captain's Office via APC.
2. Smash Display Case.
3. Revel in the sound of the alarm, and notice how the bolts drop.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

Today.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Nope.

**Comment by KasparoVy** [comment]
Backup power ⚡👽👌⚡

**Comment by Mitchs98** [comment]
As stated, backup power for airlocks is a thing. This is probably the case.

**Comment by Shadow-Quill** [comment]
Cutting power to the APC also cuts power to the doors in normal operation

**Comment by Pennwick** [comment]
Bolting doesn't require power though, they're just dropped. You could argue that the sensor should be off but if the alarm still goes off then the door bolts should still probably trigger.

**Comment by datlo** [comment]
Alarm shouldn't be triggered with the power off in the room. Then the bolting isn't an issue in the first place.

**Comment by Denthamos** [comment]
Technically ANY airlock anywhere can still be bolted by pulsing/cutting the bolt wire when there is no power supplied to it.  Something to do with hydraulics and a power surge?  Something to consider though.
