### ISSUE TITLE
Call other Holopad function broken

### ISSUE THREAD

**Issue by Pennwick** [ParadiseSS13/Paradise#10407]
**Problem Description**:
Holopad to Holopad calling does not function, failing at the call stage after selecting a holopad to call.

**What did you expect to happen**: 
For the other holopad to beep and for the receiving pad to be able to accept, or reject my call.

**What happened instead**:
Immedately get the message(in the chat feed): 
The holopad beeps, "Connection failure."
The Holopad interface says:
Dialing...
The receiving holopad displays no indications.

**Why is this bad/What are the consequences:**
I can't harass the captain for the Chain of Command as RnD. And other more legitimate holopad uses.

**Steps to reproduce the problem**:
Stand on a holopad, call another holopad, preferably one nearby. 
Get the Connection failure message. Other Holopad does not beep.

**When did the problem start happening**
It works as far as dailing for sure on my test server from 11/15 code. Hard to test if it fully works as a solo player but the receiving holopad beeps and I don't get an error.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Tested as an IPC, did not work for two separate rounds.

**Comment by Citinited** [comment]
Holopads have been broken ever since the PR that sorted the list of holopads was merged, FYI.
