### ISSUE TITLE
Teleporting containers (and Odysseus) with Instant Summons

### ISSUE THREAD

**Issue by bolognaman00** [ParadiseSS13/Paradise#10417]
**Problem Description**:
It is possible to teleport full closets/crates, and even an Odysseus mech with the Instant Summons spell, if the summoned item is inside the container.

**What did you expect to happen**: 
For the item to get pulled from the container and teleported by itself.

**What happened instead**:
When summoned, it would teleport the entire container onto the tile the player is standing on, including anything that was inside the container. If you happen to be inside an Odysseus sleeper (or presumably piloting any mech) when summoning an item within a container, the container will spawn inside the mech. Summoning the item again will cause the entire mech to teleport.

**Why is this bad/What are the consequences:**
It seems unintended. Could be used to move other unintended things.

**Steps to reproduce the problem**:
1. Obtain Instant Summons spellbook from gateway - I did not test this with the legit wizard spell.
2. Assign an object for summoning (an EVA suit in my case)
3. Place object in container (closet, crate, trashcan) and close it
4. Summon the object
To teleport a mech:
5. Enter the sleeper of an Odysseus (or presumably pilot a mech)
6. Summon the object
7. Exit mech
8. Summon the object again, this time it will teleport the entire mech to you

**When did the problem start happening**:
n/a

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It can also teleport bolted containers, such as the trashcan outside the kitchen.

**Comment by Deelite34** [comment]
pls delet, it kinda reveals my secret steal-backpack-fu magic.
Anyway, while locker teleporting maybe might be fine, I agree that mech teleporting is too much.

**Comment by datlo** [comment]
this is working as designed. teleporting a locker, teleporting a mech? the only difference is in your mind, young one

**Comment by DGamerL** [comment]
Not an issue and working as intended. If you disagree, you're free to ask the design team if they want this  changed
