### ISSUE TITLE
Diona nymphs lose abilities under specific circumstances

### ISSUE THREAD

**Issue by Mithrandalf** [ParadiseSS13/Paradise#10411]
**Problem Description**:
I spawned as a diona nymph from ghost, being held by someone. Escaped from their hold using the resist command, and when I was released, all nymph abilities (blood sample, evolve, etc) vanished. Presumably this is replicable.

**What did you expect to happen**: 
I'm assuming these forms are semi-mandatory so I'll fill them in stating the obvious. What should have happened is that I should have dropped to the ground and retained all my normal abilities.

**What happened instead**:
I lost the abilities, which bites and turns me into a generic animal mob that cant do anything. In addition, the ability to access them via the text and tab input is gone.

**Why is this bad/What are the consequences:**
It's pretty specific in terms of circumstances, but it's hardly something that isnt going to happen again and again.

**Steps to reproduce the problem**:
Person A is a humanoid and holds NPC diona nymph
Person B is a ghost and chooses that nymph from the 'spawn as npc' menu
Person B types resist to escape the grip of person A
Person B realizes they are a brainslug without eggs

Here's a screenshot. Notice the lack of a special ability tab.
![](https://puu.sh/Cdnzw/411a158fcd.jpg)

**Comment by Mithrandalf** [comment]
oh my god did I accidentally hit f12 and cause this

there should still be the tab though right

if this is me hitting f12 I'm gonna wallow in shame for a week

**Comment by lass9030** [comment]
Yes. Yes you did.
Now go and wallow in shame.
This can be closed.
