### ISSUE TITLE
Active rig modules can remain active indefinitely.

### ISSUE THREAD

**Issue by PsiOmegaDelta** [ParadiseSS13/Paradise#1043]
**How to reproduce**
* Check your remaining rig charge level.
* Activate a module such that there will be less charge remaining than the active cost requires but not exactly 0.
* Activate the module.
* The cell charge decreases until it's less than the required charge/tick and stays there.

For example: Active charge cost is 100, if the remaining cell charge reaches 75 it'll remain stuck there and the modules will remain active.
Modules will only de-activate if the battery charge becomes exactly 0.

**Comment by PsiOmegaDelta** [comment]
Ops, sorry..

**Comment by Fox-McCloud** [comment]
Ummm. *chuckles* Hey there, @PsiOmegaDelta .
