### ISSUE TITLE
infinite powercell is appearing

### ISSUE THREAD

**Issue by thanatossage** [ParadiseSS13/Paradise#10437]
**Problem Description**:
What is the problem?
the infinite power cell is appearing (not the yellow core but the yellow brown powercell) it seems to be appearing in the mining loot. 

**What did you expect to happen**: 
Why do you think this is an issue?
it is appearing in the mining loot. I hear it can cause game errors when its emped. and isn't supposed to appear due to that.

**What happened instead**:
How is what happened different from what you expected?
i believe it isn't supposed to appear due to possible issues with emps

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
i hear it can cause some bad issues with the game

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
be lucky while mining

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by lass9030** [comment]
Tested EMP on the infinite powercell, it returns no runtimes or errors, and acts as any other powercell when EMP'd. It can also recharge like any other.
