### ISSUE TITLE
Library computer printing the wrong books

### ISSUE THREAD

**Issue by Rustybuckets6601** [ParadiseSS13/Paradise#10435]
**Problem Description**:
When printing a book from the "Check in/Check out" computer in the library, choosing certain books don't always give you the book you want. For example, printing the book "A guide to faxes" gave me "EVA Gear and You: Not Spending All Day Inside". 

**What did you expect to happen**: 
Print out the correct book instead of the wrong one

**What happened instead**:
Pressing the button got me a different book

**Why is this bad/What are the consequences:**
It makes finding the book you want a hassle

**Steps to reproduce the problem**:
Went to the computer as a librarian, tried to get "a guide to faxes" got "EVA Gear and You: Not Spending All Day Inside". Tested multiple times, kept happening

**Comment by Shadow-Quill** [comment]
Did you get the same book if you tried printing again?

**Comment by Rustybuckets6601** [comment]
> g

yes, the same book. There were a few other books that did the same thing, but I can't test due to being dead in the round at the moment.

**Comment by datlo** [comment]
yeah this is easy to reproduce, happens at the bottom of the list of manuals you can print. i suspect there might be a missing reference of some sort, all the books at the bottom of the list are one "slot" down from where they should be

**Comment by Birdtalon** [comment]
Off by one error 👌
