### ISSUE TITLE
Theoretical bomb explosion size not showing up in array.

### ISSUE THREAD

**Issue by Alliostra** [ParadiseSS13/Paradise#10443]
**Problem Description**:
Theoretical Bomb explosion size did not show up in the Tachyon-doppler array. 

**What did you expect to happen**: 
I expected the array to show the theoretical size, as the bomb clearly was above maxcap level.

**What happened instead**:
the array listed n/a under theoretical size.

**Why is this bad/What are the consequences:**
I spent two hours on making a 1200 u nitroglycerin bomb and got nothing.

**Steps to reproduce the problem**:
Get four Bluepsace beakers, fill them with nitro components, make a bomb payload, put beakers in the payload, put beakers in bomb assembly. screwdriver, set timer, actiavte it, receive error message. ask admins to detonate it, get it detonated by admins. look at tachyon-doppler array, see "n/a" under theoretical size. cry.

**When did the problem start happening**:
never used bombs before

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I was uable to start the countdown of the bomb. I received the message "Device error: User intervention required", so i asked admins about it and they detoanted it for me. admins did not get a theoretical explosion size in their logs either. Another player said they experienced a similar bug (bomb not showing theoretical explosion size despite being above maxcap)

**Comment by Citinited** [comment]
Did the admins detonate the bomb on the test range?

**Comment by datlo** [comment]
Reproduced using admin tools.

However, using a toxin bomb that goes above maxcap showed the theoretical size correctly.

![image](https://user-images.githubusercontent.com/22121511/49868129-66092600-fe04-11e8-8420-37f1461a77f8.png)

**Comment by Alliostra** [comment]
> 
> 
> Did the admins detonate the bomb on the test range?

Indeed.

**Comment by Alliostra** [comment]
I just made another test usinga 2100 u nitroglycerin bomb. it was not admin- detonated this time, but did not show a theoretical size either.
