### ISSUE TITLE
Lighting Likely Causes Major Performance Issues

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1044]
Ever since the lighting patch I've been having major major performance issues with the server. My ping, which normally hangs around 0.19 to 0.26 is now hanging around 0.3 to 0.5. 

This is borderline unplayable for anything other than base level RP. ...either case, this didn't seem to start occurring until the lighting patch.

It's not on my side; it's literally the ping to the server, itself. A number of others have been experiencing crashes or client-side lag when moving from area to area (especially when jumping). 

My PC is, to say the least, very very robust--it's highly highly unlikely it's the cause of the increase latency and other related issues--especially sine others seem to be reporting and experiencing the same thing.

@Tigercat2000

**Comment by Spacemanspark** [comment]
A shame if this is the case, the new lighting system is amazing.

**Comment by Robertha89** [comment]
Can confirm, it's as if my cpu spikes randomly repeatedly, but everything else seems fine, byond client also been prone to freezing and crashing du to not responding lately.

**Comment by fj45** [comment]
New lighting is great, I really hope we can have it at some point in time.

**Comment by ZomgPonies** [comment]
I've got a single lighting runtime at round start:
runtime error: invalid view size
proc name: apply lum (/datum/light_source/proc/apply_lum)
  source file: light_source.dm,145
  usr: null
  src: /datum/light_source (/datum/light_source)
  call stack:
/datum/light_source (/datum/light_source): apply lum()
lighting (/datum/controller/process/lighting): doWork()
lighting (/datum/controller/process/lighting): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(lighting (/datum/controller/process/lighting))

**Comment by ZomgPonies** [comment]
Tiger ported the PR too fast and was missing some crucial scheck() calls in the overlay update procs. We
ll need to merge https://github.com/ParadiseSS13/Paradise/pull/1051 and see how performance looks now.

**Comment by ZomgPonies** [comment]
Performance is better, but still a lot of client-side crashes.

**Comment by Fox-McCloud** [comment]
It's definitely better, but update_lighting_overlay is consistently the most expensive proc, outside of Del(), as well.

**Comment by PJB3005** [comment]
Fixing the lighting update overlay lag can be done by disabling transitions, we did this on /vg/ and it's all lag gone.

I did implement math to prevent redundant calls of the proc though, which will help
