### ISSUE TITLE
Lightning Spell doesn't work if you use the UI button instead of the verb in the spells tab

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#10447]
**Problem Description**:
Using the Lightning spell doesn't work unless you click the verb in the Spells tab instead of the UI action button

**What did you expect to happen**: 
for it to shoot lightning after I pressed it while it was charging up

**What happened instead**:
it didnt

**Why is this bad/What are the consequences:**
because it should

**Steps to reproduce the problem**:
1. Give yourself the noclothes spell
2. Give yourself the lightning spell
3. Spawn in a human beside you
4. Click the UI action button and you will begin charging
5. Click again WHILE you are still charging, observe nothing happening
6. Go into the Spells tab and click the spell in there, observe it working (while you are still charging)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
https://github.com/ParadiseSS13/Paradise/blob/6fe83a698757f023d26171355fff906d95ee764b/code/datums/spells/lightning.dm#L25

https://github.com/ParadiseSS13/Paradise/blob/44eaec1c9dc74a6724861bd4f7417544ecaf8227/code/datums/spell.dm#L64

**Comment by Kyep** [comment]
... so that is why it never worked for me.
