### ISSUE TITLE
Airlocks beep at you when you try to open one, even if it's power has been cut

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10459]
**Problem Description**:

Airlocks play the "Access Denied" sound even when power is cut.

**What did you expect to happen**: 

Airlocks to not have magical power producing abilities.

**What happened instead**:

Airlocks have magical power producing abilities.

**Why is this bad/What are the consequences:**

_**BEEPBEEP BEEPBEEP BEEPBEEP**_ when there should be no power for the beepers.

**Steps to reproduce the problem**:

1) Cut power to airlock (On the airlock ai menu or wires, don't know about apc)
2) Apply face to airlock.
3) BEEPBEEP BEEPBEEP BEEPBEEP BEEPBEEP BEE-

**When did the problem start happening**:

Today.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

No.

**Comment by Ty-Omaha** [comment]
Just tested this and it seems to only be an issue when Backup Power is on, which doesn't really sound like an issue anyways because..backup power

**Comment by Ty-Omaha** [comment]
Weird, what door did you test it on?

**Comment by Birdtalon** [comment]
Can you please make your issue title actually meaningful?

**Comment by Shadow-Quill** [comment]
Not a bug anymore.
