### ISSUE TITLE
Flares are neither bright enough or colourful enough.

### ISSUE THREAD

**Issue by fj45** [ParadiseSS13/Paradise#1045]
Sorry for not having any pics, but looking at a flare sitting on the ground, it just isn't bright enough.

**Comment by fj45** [comment]
@tigercat2000

**Comment by MrBauer24** [comment]
The brightness is currently at 7 and the colour hex code is:
#e58775
This is the colour for you:
http://ffffff.eu/index.php?b=E58775

**Comment by fj45** [comment]
Right, thanks.

I'll see about getting a screenshot.

**Comment by tigercat2000** [comment]
Er, sorry, got put aside, I guess MrBauer is working on it now

**Comment by fj45** [comment]
No problem mate.

**Comment by MrBauer24** [comment]
I will do my best for you :)

**Comment by TheDZD** [comment]
Closed via #1070.

**Comment by TheDZD** [comment]
Closed via #1070.

**Comment by fj45** [comment]
Thanks Bauer!
