### ISSUE TITLE
Opening exosuit controls as AI crashes byond 

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10463]
**Problem Description**:
What is the problem?
Opening exosuit controls as AI crashes byond 

**What did you expect to happen**: 
Why do you think this is an issue?
EMP the mech

**What happened instead**:
How is what happened different from what you expected?
Window opened but game froze

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Game froze

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Have the exosuit control console left on a mech's action log. Have the mech do a ton of shit.
2. Open the window as AI. Tons of shit logs open, and freeze the game.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Probably always been.

**Comment by Sinestia** [comment]
Still exists; ran into this issue today. 


 Tgui conversion will hopefully resolve it.

**Comment by datlo** [comment]
This is most likely fixed by tgui.
