### ISSUE TITLE
Certain Cyborg Depletable Resources Don't Regenerate 

### ISSUE THREAD

**Issue by Surrealistik** [ParadiseSS13/Paradise#1047]
When you fully deplete trauma or burn packs for a Medborg they do not regenerate when you go back to the charger.

Apparently this is an issue for floor tiles as well concerning Engineering Cyborgs, and I'm sure it affects other depletable resources as well.

**Comment by IAmBigCoat** [comment]
I tried placing floor tiles with the drone. I ran out, but the blank module was still equipped and still let me place floor tiles.

This might be unrelated.

**Comment by MrBauer24** [comment]
Working on a fix
