### ISSUE TITLE
Drask crusader helmet is invisible

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#10486]
**Problem Description**:
What is the problem?
Drask crusader helmet is invisible
**What did you expect to happen**: 
Why do you think this is an issue?
Invisible, not suppossed to

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Can't wear voice gas mask, cannot wear stuff under helmet on face, without looking suspicious, as that stuff is suppossed to be not visible, since helmet covers it.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be Drask chaplain
2. Put Chaplain helmet on.
3. It's invisible, everyone can see your face even though they are not supossed to

**Comment by Mithrandalf** [comment]
Just tested it and recreated it.

I'm gonna give this one a try.
