### ISSUE TITLE
"Bork Bork!" persists through tapegags

### ISSUE THREAD

**Issue by Drayko-the-Sheep** [ParadiseSS13/Paradise#10483]
**Problem Description**:
When people with the "swedish accent" disability are tapegagged, the "bork bork" is not converted to mumbles.

**What did you expect to happen**: 
"Bork bork" to become "mmph mmph," I guess?

**What happened instead**:
~~Antics and laughter~~
Er, I mean, the speech came out as "Mmphmph, bork bork!"

**Why is this bad/What are the consequences:**
As funny as it is, it kinda breaks immersion?

**Steps to reproduce the problem**:
Pick the swedish accent. Tapegag yourself. Keep talking until your character randomly borks.

**When did the problem start happening**:
I noticed it last night.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Extended roleplay mode, and not really doing anything special?

**Comment by Mitchs98** [comment]
The power of Bork is too strong.

**Comment by KasparoVy** [comment]
Brilliant, hahaha. This is a good one
