### ISSUE TITLE
The Syndicate is outsourcing their recruitment to NT.

### ISSUE THREAD

**Issue by EvadableMoxie** [ParadiseSS13/Paradise#10491]
**Problem Description**:
Syndicate Officer appears as an available job when someone checks job postings on a newscaster.

**What did you expect to happen**: 
The Syndicate to not use NT for their recruitment needs.

**What happened instead**:
NT appears to be doing the Syndicate's recruiting.

**Why is this bad/What are the consequences:**
It's a bit out of character for NT to be recruiting Syndicate officers.

**Steps to reproduce the problem**:
Check a newscaster.

**When did the problem start happening**:
When Syndicate Officer was added as an admin job

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

![syndicaterecruitment](https://user-images.githubusercontent.com/27022582/50390395-d1a49a80-0704-11e9-94b4-e5b70c783d80.png)

**Comment by v0idp** [comment]
Oh wow, how can I apply ? You got me at Syndicate.
No seriously, it looks like it shouldn't be there.

**Comment by Shadow-Quill** [comment]
Sign me up.

**Comment by v0idp** [comment]
Made a PR to fix this: #10492
