### ISSUE TITLE
Low priority - missiles spin when fired

### ISSUE THREAD

**Issue by Mithrandalf** [ParadiseSS13/Paradise#10518]
**Problem Description**:
When you fire missiles, in this case using a seraph, they spin in their air as if they'd been thrown.

**What did you expect to happen**: 
I expected the missiles to fly in a straight line like normal missiles

**What happened instead**:
The missiles spin around as they fly and it looks very silly

**Why is this bad/What are the consequences:**
It just looks really dumb

**Steps to reproduce the problem**:
Get in mech w/ missiles
Click

![image](https://user-images.githubusercontent.com/16275811/50456572-5a157c00-094d-11e9-945e-d3637108fad0.png)

**Comment by KasparoVy** [comment]
Offending line is [here](https://github.com/ParadiseSS13/Paradise/blob/07769ba3b9590fd7abae38a3fe5793d201cd2a7c/code/game/mecha/equipment/weapons/weapons.dm#L349)
Needs to be changed from
`M.throw_at(target, missile_range, missile_speed)`
to
`M.throw_at(target, missile_range, missile_speed, spin = FALSE)`

**Comment by Mithrandalf** [comment]
Wow that seems simple

**Comment by v0idp** [comment]
I think there is a mistake with your fix, the spin you are trying to apply is at the parameter spot where ``mob/thrower`` is supposed to be. can you actually say ``spin = FALSE`` to tell the proc to set the spin to FALSE ? Never saw something like this in another language.

**Comment by KasparoVy** [comment]
Yep @v0idp it is
You can do it the traditional way by specifying all arguments but it ain't necessary here since we're using the default value for the one we don't specify
