### ISSUE TITLE
Oculine does not fix ear damage

### ISSUE THREAD

**Issue by Superhats** [ParadiseSS13/Paradise#10515]
**Problem Description**:
What is the problem?
Oculine does not fix ear damage.

**What did you expect to happen**: 
Why do you think this is an issue?
Oculine is meant to fix hearing

**What happened instead**:
How is what happened different from what you expected?
Ear still broke

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
That forces medical to do surgery

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Ear machine broke
Apply oculine
ear still broke
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Problem noticed on 26/12/2018

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by variableundefined** [comment]
@Superhats Is this a balance issue? Was this changed recently? AFAIK it was supposed to fix ear damage but the wiki is often more than wrong.

**Comment by Superhats** [comment]
Looking at the code, it is supposed to fix ear damage.

**Comment by Fox-McCloud** [comment]
it fixes it, but high ear damage is difficult to repair.
