### ISSUE TITLE
The Syndicate is still outsourcing their recruitment

### ISSUE THREAD

**Issue by Decemviri1** [ParadiseSS13/Paradise#10510]
**Problem Description**:
HoPs can see the Syndicate Officer Admin job in their job management console

**What did you expect to happen**: 
Job management should not see admemery

**What happened instead**:
HoPs can see the glorious memes.

**Why is this bad/What are the consequences:**
Oversight in adminjob creation confusing players

**Steps to reproduce the problem**:
Plug valid ID into job management console, scroll to the bottom

**When did the problem start happening**:
Related to the Syndicate Officer Admin job added in #10474 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Normal round, HoP was syndicate agent. 

![image](https://user-images.githubusercontent.com/36930781/50426344-70570580-0883-11e9-9c0a-505eea777902.png)
![image](https://user-images.githubusercontent.com/36930781/50426346-7816aa00-0883-11e9-8b65-602e8a2648cb.png)

**Comment by v0idp** [comment]
I will take a look thanks.
