### ISSUE TITLE
Diona dont suffer without light

### ISSUE THREAD

**Issue by Mithrandalf** [ParadiseSS13/Paradise#10517]
**Problem Description**:
Dionas can hang around in maint lockers as long as they want, despite the 'no light' icon, they receive no ill effects other than losing their regen.

**What did you expect to happen**: 
As the wiki says in a few places, Diona supposedly 'require light'. I expected them to somehow actually require light. Which they don't.

**What happened instead**:
There's an icon that warns you about lacking light. That's about it.

**Why is this bad/What are the consequences:**
Seems like a pretty important part of the counterbalance to Diona healing in light.

**Steps to reproduce the problem**:
Be Diona.
Be somewhere without light
???
Profit

**Comment by datlo** [comment]
I believe the way that works and is designed to is that diona require light as nutrition, not as a vital requirement like oxygen would be. So this is working as intended.

**Comment by DesolateG** [comment]
Diona get hungry without light. Not a bug

**Comment by Mithrandalf** [comment]
I went AFK for a pretty long while as diona in a maint locker and came back to nothing saying I was malnourished or similar. It might not have been for long enough though. 

Unless someone does it before me, I'll run a test in a couple hours to see if that's borked.

**Comment by Mithrandalf** [comment]
Cool, confirmed it. No bugs here.

**Comment by Pixelzilla** [comment]
Diona nymphs used to die without light. They got broken when moved to simple mobs and no one fixed that. It's only reasonable to assume that if Diona Nymphs are supposed to die slowly in darkness that Diona themselves would also do so.
