### ISSUE TITLE
Sofa left and right types are inversed

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10548]
**Problem Description**:
Sofa left end looks like the right end and vice versa

**Why is this bad/What are the consequences:**
Makes it slightly annoying to build sofa because the UI gives you wrong info due to the types being wrong

Fixing should be swapping the sprites for the two ends and changing all instances of sofa ends to each other in maps with em

**Comment by taukausanake** [comment]
The funny thing about ends like this is you're either looking at the right-end of the sofa or you're sitting on the left-end of it. It's all a matter of relativity and therefore not really a bug

**Comment by datlo** [comment]
this isnt actually a real issue and more of a point of view thing, literally, so closing this I guess
