### ISSUE TITLE
Turn any vendor into any other vendor

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#10544]
**Problem Description**:
You can turn a vending machine into any other vending machine if you have the parts for another vending machine handy.

**What did you expect to happen**: 
Vendors should reject parts that aren't of the correct type, shouldn't be able to edit the board type if it's not in your hands

**Why is this bad/What are the consequences:**
Vendors aren't supposed to be magical

**Steps to reproduce the problem**:
1. Disassemble any vending machine
2. Screwdriver the circuitboard to get the popup
3. Insert circuitboard into machine frame
4. Change the board type to desired vendor (this step can be done any time the board is inside the unfinished machine frame)
5. Insert restocking units that match the board that you originally inserted
6. Screwdriver to finish, admire the new vendor

**When did the problem start happening**:
Probably since forever

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

**Comment by datlo** [comment]
While this should obviously be fixed, this doesn't cause any real balance issue and isnt high priority, right?

**Comment by Citinited** [comment]
I'd agree with that
