### ISSUE TITLE
Things that talk in chat broke

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10551]
**Problem Description**:

Title.

**What did you expect to happen**: 

**THE CAPTAIN HAS DIED IN THE BRIDGE.** or
Cell 6 released prisoner. or
Beepsky is arresting someone for a level 6 infraction in the Central Primary Hallway.

**What happened instead**:

_cough_

**Why is this bad/What are the consequences:**

🤔 

**Steps to reproduce the problem**:

1. Implant yourself with a deathalarm/start a Cell timer/get arrested by beepsky.
2. Murderize yourself. (with deathalarms)
3. Note the lack of people being alarmed/notified.

**When did the problem start happening**:

When NTSL2 came, I belive. Not quite sure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

No.

**Comment by alex-gh** [comment]
I bisected it and this is the commit that broke it: e567504

It is getting too late for me to investigate this further though.
