### ISSUE TITLE
Radio emotes stutter if you're in crit.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1056]
For some reason, if you're in critical, and you emote over the radio (Or use say, "! (Emote here)" to emote in general), the emote will stutter.
![http://i.imgur.com/XviNYIO.png](http://i.imgur.com/XviNYIO.png)

**Comment by FalseIncarnate** [comment]
You want to put "![image](link)" to have an image display

**Comment by Spacemanspark** [comment]
The mime can't emote over the radio.

**Comment by MrBauer24** [comment]
I have looked in the say code and I cannot find anything related to this. It's a difficult one!

**Comment by KasparoVy** [comment]
Isn't there a way to add an exception sort of thing where if you're using ! to emote over radio, the message is automatically exempt from the crit stutter effect?

**Comment by Fox-McCloud** [comment]
I'll be honest, I'm not sure if this should be fixed...otherwise we'll start getting people utilizing emotes to "speak" clearly over comms like mimes do when they're in poor condition/stunned/etc.

**Comment by tigercat2000** [comment]
@Fox-McCloud Not fixing a bug over "maybe players will abuse this to powergame out of stutters" is a bad plan. Languages should have a way to override speech effects.

**Comment by tigercat2000** [comment]
This is actually a thing on baydev, the NO_STUTTER flag. If anyone wants to port it, pretty simple.

**Comment by tigercat2000** [comment]
@Spacemanspark Is this fixed? I added the no stutter flag a while back.

**Comment by Crazylemon64** [comment]
This is fixed.

**Comment by Tastyfish** [comment]
I thought it was, but wasn't really sure enough to even bring this one up.
