### ISSUE TITLE
Ghosts get moved by dark matter blob

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#10569]
**Problem Description**:
See title

**What did you expect to happen**: 
Not to be moved

**What happened instead**:
See title

**Why is this bad/What are the consequences:**
Makes it annoying to be an observer. 

**Steps to reproduce the problem**:
Be ghost. Be close to dark matter blob hitting people.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
round type was blob (duh)

**Comment by Shadow-Quill** [comment]
So strong it sucks the spirits of those it killed

**Comment by Dinarzad** [comment]
As a note: It also does this with Soarium blobs too.
