### ISSUE TITLE
security bots see arrest status trough all possible cover

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#10567]
**Problem Description**:
What is the problem?
security bots see arrest status trough all possible cover
**What did you expect to happen**: 
Why do you think this is an issue?
Punishes being stealthy.
**What happened instead**:
How is what happened different from what you expected?
Secbot should not ignore different id, hidden face, different suit, and see arrest status with bluespace powers
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Punishes stealthy playstyles.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Hide your face with mask. Wear different ID, whole different suit.
2. Sec bot uses bluespace powers to find out that you are wanted, and goes to arrest you

**Comment by Nicaragua1** [comment]
I have tested this. It happens 100% of the time. Will take a look

**Comment by Pckables** [comment]
Can confirm that it happened to me today.
Had a SecHUD on and noticed my normal Identity was wanted, so I put on a stolen ID and gasmask. SecHUD and examine showed I was fully disguised and not wanted. Despite this, A beepsky instantly came to arrest me, ignoring the disguise completely. It completely breaks stealth and encourages Beepsky dragging meta.
