### ISSUE TITLE
rank is a reserved keyword on MySQL 8.0.2+

### ISSUE THREAD

**Issue by Nopm** [ParadiseSS13/Paradise#10568]
**Problem Description**:
On MySQL 8.0.2 and up, `rank` is a reserved keyword. It causes issues with `load_admins()`, specifically this line `"SELECT ckey, rank, level, flags FROM [format_table_name("admin")]`

**What did you expect to happen**: 
For admin ranks to be correctly loaded.

**What happened instead**:
`"SELECT ckey, rank, level, flags FROM [format_table_name("admin")]` returns a syntax error on MySQL Server 8.0.2 and up.

**Why is this bad/What are the consequences:**
Because MySQL 8.0.2 is very heavily used, specially by people who cannot afford to downgrade to an older version with security vulnerabilities, or by people who do not have the permissions/knowledge required to install MariaDB.

**Steps to reproduce the problem**:
It's quite simple. Install MySQL 8.0.2 and enable DB-based administration. Admins will not get correctly loaded due to a syntax error, which conveniently does not show up in the console, even with `#TESTING` defined.

**When did the problem start happening**:
After I moved my Paradise instance to a Windows Server 2016 dedicated server, which uses MySQL 8.0.2 as a database.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
There's not much else.

**Comment by AffectedArc07** [comment]
~~Solution: Use MariaDB~~

**Comment by Allfd** [comment]
This is a pretty serious problem.

**Comment by Kyep** [comment]
I am not sure this applies anymore.
Our mysqld.exe reports version 10.3, and it accepts:
SELECT ckey, rank, level, flags FROM admin limit 3;
