### ISSUE TITLE
Reflective blob tendrils not reflecting Pod Lasers

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#10570]
**Problem Description**:
As it says, space pod lethal lasers do not reflect of the reflective blob tendrils and instead destroy them.

**What did you expect to happen**: 
The lasers should reflect.

**What happened instead**:
The pod lasers completely ignored the reflection tendrils

**Why is this bad/What are the consequences:**
They should be reflecting all lasers, which is their intended purpose.

**Steps to reproduce the problem**:
Spawn a reflective tendril, shoot lethal space pod lasers at it.  It does not reflect.

**When did the problem start happening**:
Possibly never worked properly from the start.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Blob

**Comment by Ty-Omaha** [comment]
I saw it working in a round a few days ago and just tested again, it's possible you just had bad RNG with the probability chance

![](https://i.gyazo.com/fc7c6d7194ae6dfc4396ad2506ffc293.gif)
