### ISSUE TITLE
Kicked from the server after using a Xenobio transference potion

### ISSUE THREAD

**Issue by StaticMeow** [ParadiseSS13/Paradise#10583]
**Problem Description**:
Using a Xenobio transference potion on a mob while someone else is also using a transference potion seems to make the game think that you're multi-logging.

**What did you expect to happen**: 
I expected to take control of Slith's blob zombie.

**What happened instead**:
I got DC'd from the game, and when I rejoined, was hit with the multi-logging message.
https://imgur.com/a/oxCe1LT

**Why is this bad/What are the consequences:**
It disconnected me from the server, and when I rejoined, after going through the multi-logging message, I was able to rejoin the round as any available job.

**Steps to reproduce the problem**:
Slith and I were in Xenobiology. He used a transference potion to enter a lesser hellhound. I then attempted to use a transference potion to enter his old body, which was now possessed by a blob spore, turning him into a blob zombie. It seems that another person attempted to do a transfer to the blob zombie as well, and as soon as I transferred, the server DC'd me.

**When did the problem start happening**:
I discovered it a few minutes ago.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing abnormal was happening.

**Comment by datlo** [comment]
oof this is some spaghetti that's gonna be hard to fix
