### ISSUE TITLE
The damp rag has a lid

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#10599]
To reproduce: click the rag in your hand as if it were a glass beaker.

![image](https://user-images.githubusercontent.com/18459142/50728355-41148400-1120-11e9-8749-db29b733f647.png)

🤔

**Comment by Spartan6** [comment]
True next level.

**Comment by FalseIncarnate** [comment]
Well that's obviously missing an override on attack_self like drinks have... That or a wider-scale addition of a new flag for reagent containers that can be used in the base container's attack_self for determining if the thing can be covered (something like HASLID to go along with OPENCONTAINER)

**Comment by datlo** [comment]
This thing needs to be redone entirely, it's absolute 🍝
