### ISSUE TITLE
Automatacly decline ghost roles if typing 

### ISSUE THREAD

**Issue by Daylight2** [ParadiseSS13/Paradise#10608]
**Problem Description**:
It would be neat if the blob spl- *Would you like to play as blob?* - *no*
Fuq
**What did you expect to happen**: 
Not to automatacly decline all 'would you like to play as __' prompts if typing 

**What happened instead**:
Automatacly decline the prompt as punishment for talking in dchat 

**Why is this bad/What are the consequences:**
It would be nice not to be punished for using dchat

**Steps to reproduce the problem**:
Be ghost 
Type 
Get prompt 
Automatacly say no because the 'no' button is automatacly selected on the prompt, and pressing any key activates it 
**When did the problem start happening**:
Ever since the 'would you like to play as __' got its buttons changed around to include the 'no' button as the first button in the list

**Comment by Allfd** [comment]
That happened because people kept clicking yes to things they didn't want to play and would ghost out.

**Comment by daylight2** [comment]
Still quite annoying though. Perhaps add a clicabke link in chat too so you could still change your vote before the role is rolled?

**Comment by Birdtalon** [comment]
More of an issue with the way Byond sends popups to the user.

**Comment by datlo** [comment]
Use the "T" hotkey to send messages instead of typing in the command bar. Ya should probably be doing that all the time anyway and use hotkey mode 😛

**Comment by datlo** [comment]
The other way to do this would be to get rid of the popup entirely and announce event spawn by chat to ghosts, with a link to sign up. Not sure how easy or difficult that'd be to code.

**Comment by daylight2** [comment]
If you do change it to a chat-only pop-up, please add a costum sound for it, so alt-tabbed ghosts don't have to sift trough chat every time they hear a ping, just to find out it was an announcement.

**Comment by Shadow-Quill** [comment]
Probably could use some code that borers/swarmers/robobrains/tspiders do

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/13710

**Comment by AffectedArc07** [comment]
No longer relevant
