### ISSUE TITLE
Maintenance Drone lost metalsheet stack

### ISSUE THREAD

**Issue by Ionward** [ParadiseSS13/Paradise#10601]
**Problem Description**:
Maintenance drones (possibly engineering cyborgs, too) can glitch out and lose the ability to replenish their metal (other materials too?) from Cyborg Rechargers.

**What did you expect to happen**: 
Go in to recharger, replenish metal sheets

**What happened instead**:
Replenished everything else, and no matter what I tried I couldn't get a usable stack of metal to show up in my inventory.

**Why is this bad/What are the consequences:**
Maintenance drones need metal to do their main function, and if this issue can lead to other materials not replenishing in other silicons this could create a big problem.

**Steps to reproduce the problem**:
I'm not sure exactly about this one. I was a maintenance drone, crawling through vents and occaisionally popping into a recharger, when I noticed no metal stacks. Reconnected, sat longer in the chargers, and nada.

**When did the problem start happening**:
Maybe an hour, an hour thirty into a round with me being a maint drone for probably most of that.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Vampire round, I was repairing the old bar systems. I did fall into a disposal chute I set up earlier but I think I had metal still after it.

**Comment by Shadow-Quill** [comment]
Did you pull something out of your storage and put it back in? Sometimes inventories don't update.

**Comment by davidchan13** [comment]
I've had this happen with Drone wood stacks, use all your wood and recharging doesn't regenerate it. I think I solved it by disassembling the charger and upgrading it but I have a feeling that was more of a coincidence than an actual fix to the problem.

The better solution to trying to fix this would be to just change how all cyborg modules work so they don't actually use materials but rather use battery power for each use of a material or tool, thus improving their power cell would equally improve the capacity of all their limited use tools.

**Comment by bolognaman00** [comment]
I had this same issue with cable a few days ago. Entering a different cyborg charger brought the cable coil back into my inventory.
