### ISSUE TITLE
Eye Implants render over everything else

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#10618]
**Problem Description**:
What is the problem?
Eye implant sprites render over everything, including eyewear, helmets, even hardsuits.
**What did you expect to happen**: 
Why do you think this is an issue?
Glasses/helmets/hardsuits to display above the eye implant layer.
**What happened instead**:
How is what happened different from what you expected?
You can tell the type of eye implant someone has from a glance, even if they're wearing a helmet/suit/glasses. Especially jarring as grey, and likely drask or kidan.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It ruins my immersion
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Get an eye implant, try wearing anything that covers the eyes.
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
I've seen it happen with welding shield and meson implants. Presumably others would be the same, but I'm unsure.

**Comment by KasparoVy** [comment]
Related to https://github.com/ParadiseSS13/Paradise/pull/10617
