### ISSUE TITLE
Toy handcuffs seem to disable actions after resisting out of them

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10616]
**Problem Description**:
After removing toy handcuffs by resisting, you're still unable to do actions for a few seconds

**What did you expect to happen**: 
Break out of toy handcuffs, do things

**What happened instead**:
Break out of toy handcuffs, can't do things for a few seconds

**Why is this bad/What are the consequences:**
Doesn't work properly

**Steps to reproduce the problem**:
1. Handcuff yourself with toy handcuffs
2. resist, handcuffs are removed immediately properly
3. can't do anything as if handcuffed for a few seconds

**Comment by Mithrandalf** [comment]
Neat. I'll look into it.

**Comment by Sirryan2002** [comment]
Apparently this shit is an intended feature
```dm
#define CLICK_CD_HANDCUFFED 10
```
```dm
/mob/proc/changeNext_move(num)
	next_move = world.time + ((num+next_move_adjust)*next_move_modifier)
```
```dm
if(restrained())
		changeNext_move(CLICK_CD_HANDCUFFED) //Doing shit in cuffs shall be vey slow
		RestrainedClickOn(A)
		return
```
