### ISSUE TITLE
Reviving as a cling makes you bald

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#10614]
**Problem Description**:
You lose your hair when you revive as a cling. Making you stand out quite a bit when you revive. Other than the fact that you just came back from the dead.

**What did you expect to happen**: 
Not to become a greytider

**What happened instead**:
I became bald as if I shaved myself with my arm blade.

**Why is this bad/What are the consequences:**
Annoying since you stand out quite a bit.

**Steps to reproduce the problem**:
1. Die as a cling
2. Regenerate and become bald

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I've also noticed that clings lose their hand, feet and head slots. This is probably due to the limbs regenerating or something. Might also be considered a bug

**Comment by KasparoVy** [comment]
The Closest of Shaves(tm) guaranteed or your genomes back
