### ISSUE TITLE
NT rep doesn't have access to his own office door button

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10620]
![image](https://user-images.githubusercontent.com/22121511/50885232-0f800f00-13e5-11e9-8ee8-36243d764120.png)

See title. I assume the access wasn't set properly on mapping the new buttons.

**Comment by dovydas12345** [comment]
Crap must have forgotten to set the correct access to Nt Rep button..

**Comment by Decemviri1** [comment]
Blueshield office is the same
