### ISSUE TITLE
APC contruction

### ISSUE THREAD

**Issue by stellachipmate** [ParadiseSS13/Paradise#1062]
I'm not seeing it listed here but a few days ago when I believe the light update went in, APC construction stop working. You can put the APC frame on the wall, but the terminal is not added on the floor in front on it. It then acts as if it's fully constructed except you can't access the APC menu or deconstruct it.

**Comment by tigercat2000** [comment]
did you crowbar the floor first? Adding wire to the APC is supposed to generate the terminal, it doesn't just appear on first place

**Comment by stellachipmate** [comment]
Yes I have. Try the APC construction in the assembly line or the old bar as a quick test. The assembly line has the wall ready for the APC to be constructed on it so it is the easiest.

I recorded a video of it: https://youtu.be/7m_aUHxhLeE

Steps I took at the assembly line:

-Place APC frame on the wall
-APC shows up on the wall already closed and completed
-I try clicking on the APC multiple times but can't access the menu
-I open the APC with a screwdriver to expose wires
-Try to use crowbar to open panel for battery but can't. Cover is locked.
-Closed the APC with screwdriver and use my card to unlock the APC interface.
-I try clicking on the APC multiple times but can't access the menu
-Unscrewed the APC again and cut all the wires

**Comment by Spacemanspark** [comment]
The APC's that are already in the assembly room/ old bar are broken. Just those, I've tested the one in the assembly room.
Just build new APC's in those rooms.

**Comment by stellachipmate** [comment]
How do you build new APC's in those rooms. If you try it says the area already has an APC. And you can't deconstruct the old one because the you can't access the menu to unlock the cover.

I recorded another video to show this: http://youtu.be/Xe6nFmjC8KA

**Comment by Spacemanspark** [comment]
I was able to make a new APC in the assembly room before... with the other APC in it.

**Comment by Spacemanspark** [comment]
I think I did something to the other APC before building it.
I just know I didn't take it apart completely.
