### ISSUE TITLE
Problem with IPCs and Dark Blessing

### ISSUE THREAD

**Issue by Medizeal22** [ParadiseSS13/Paradise#10629]
**Problem Description**:
My IPC briefly lost his Dark Blessing despite being attacked and damaged on the wrong side of his body. This occurred after a weeping angel attacked my character and tore off it's right arm despite the blade being on the left.

**What did you expect to happen**: 
When I was attacked, I expected the right side of my body, which was injured, to be damaged but my armblade to still be present.

**What happened instead**:
Instead, I lost my right arm AND the blade was found on the ground. After picking up the blade it remelded to my arm without a message. Note that I could not pick up the blade in my Right hand because it was missing and my left hand, which is where it was in the first place, was able to pick it up without issue.

**Why is this bad/What are the consequences:**
If this happens during PVP or PVE scenarios, the chaplain is defenseless.

**Steps to reproduce the problem**:
As an IPC chaplain, put the Dark blessing on your left arm. Be attacked by an angel and lose your Right arm. You will likely find the blade about 3 blocks away.

**When did the problem start happening**:
Today at the time of this report.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
May be due to the angel event.

**Comment by taukausanake** [comment]
Maybe you somehow dropped it during the attack and when you picked it up it just stuck right back on? They aren't supposed to be dropped so maybe that's what happened

**Comment by 1080pCat** [comment]
This was an issue with how NO_DROP was handling loosing hands, however this issue was fixed with #22462
