### ISSUE TITLE
Malf AI gets all comms. Twice.

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10630]
**Problem Description**:

Title.

**What did you expect to happen**: 

```
[Security] Detective "okey."
```

**What happened instead**:

```
[Security] Detective "okey."
(Intercepted) [Security] Detective "okey."
```

**Why is this bad/What are the consequences:**

AI comms are even spammier than usual.

**Steps to reproduce the problem**:

1) Be Malf/Traitor AI.
2) Speak on comms, or have someone speak.
3) Note how all comms appear twice, except for traitor comms (.t) [Since it can't be intercepted.]

**When did the problem start happening**:

No clue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

Traitor, AI was one.

**Comment by datlo** [comment]
Duplicate of #9310
