### ISSUE TITLE
Kinetic Accelerator Fire Rate Bug

### ISSUE THREAD

**Issue by Rindali** [ParadiseSS13/Paradise#10640]
**Problem Description**:
The short version is that it seems to be the case when carrying two KA's that have the reduced cooldown mod, the mod no longer functions.

**What did you expect to happen**: 
I expected the KA's to function with the mod as normal.

**What happened instead**:
They fired at a rate more akin to an unmodded KA.

**Why is this bad/What are the consequences:**
It negates the ability to carry multiple KAs, either for faster mining or to have one for fighting monsters and one for digging.

**Steps to reproduce the problem**:
Essentially, anytime 2 KAs with the cooldown reduction mod (or possibly one without, have not tested that) are being held, either in hand or on the belt or in inventory, firing the KA results in a longer cooldown rather than a shorter one.  Dropping a KA immediately fixes this change, so I believe it is somehow tied to having two KAs equipped to a single character.

**When did the problem start happening**:
I believe I noticed it as early as last week (late December 2018) but possibly earlier.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
No additional comments.

**Comment by AzuleUtama** [comment]
After having a look into this and asking around discord, it seems that increasing the cooldown for KAs when you have more than one on you is intentional and was done to prevent halving the cooldown by simply dual wielding them rather than using the modkits.
