### ISSUE TITLE
Buttons do not work past an effective range of ~35, regardless of the 'range' variable setting

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#10646]
**Problem Description**:
Button doesn't work on shutter if outside of a range of 35 tiles, regardless of 'range' setting.

**What did you expect to happen**: 
For it to work based on the range value, not some odd arbitrary maximum

**What happened instead**:
It didn't work

**Why is this bad/What are the consequences:**
Can't make big maps 😢 

**Steps to reproduce the problem**:
Have a shutter / blast door with the same 'id_tag' as the 'id' variable of a button be placed 35+ tiles away from the button. Set the button's range to anything above 35 (50, 200, whatever). Try to use the button.
The shutter outside of the 35 tile range will not work.

**When did the problem start happening**:
It's been around at least since the first two Brig remaps.

**Comment by Kyep** [comment]
I'm fairly sure I fixed this with https://github.com/ParadiseSS13/Paradise/pull/10777 and this issue can be closed.
