### ISSUE TITLE
When you die you can still feel needles

### ISSUE THREAD

**Issue by MrBauer24** [ParadiseSS13/Paradise#1064]
My character was dead and a doctor injected me, it said in red writing 'you feel a tiny prick'

**Comment by tigercat2000** [comment]
Not really a bug or issue, needle messages don't check for people being dead before telling them that they feel a tiny prick. It really isn't worth a snowflake check for people being dead, if you ask me.

**Comment by Fox-McCloud** [comment]
Going to concur with Tigercat on this one.
