### ISSUE TITLE
Medical borg dropping scanner, causing bugged scanner to weld to peoples hands on pickup.

### ISSUE THREAD

**Issue by Imotepchief** [ParadiseSS13/Paradise#10643]
**Problem Description**:
While playing as a medical cyborg, I was following an injured clown, who was pulling a closet.
I tried to scan the clown with my inbuilt medical scanner as he was moving and my scanner was dropped.
I was unable to pick it up again, seeing as borgs can't pick things up, but if anyone else did pick it up, it would fuse to their hand and they would need it amputating in order to drop it again.

**What did you expect to happen**: 
Not this.

**What happened instead**:
If I can't pick it up, why should I be able to drop it.

**Why is this bad/What are the consequences:**
Having to amputate 4 different peoples hands, 1 person twice, because people casually grab things.

**Steps to reproduce the problem**:
Follow what I described initially, have someone pulling a closet and while as a borg try to scan them.

**When did the problem start happening**:
12 Jan 2019, 11:45pm |GMT| is when it happened for me.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Was a cult round, nothing out of the ordinary.

**Comment by alex-gh** [comment]
Could not reproduce it with solo testing, despite clicking wildly. Maybe it really needs multiple people to trigger?

**Comment by Mitchs98** [comment]
Unable to reproduce as Alex said.

**Comment by Contrabang** [comment]
Unable to reproduce after 4 years, and I haven't heard of anything happening like this since
