### ISSUE TITLE
Statue Mobs Push Singularities

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#10658]
**Problem Description**:
The Statue mob can push a singularity and not be destroyed

**What did you expect to happen**: 
...Its a singularity and whatever touches it should be destroyed

**What happened instead**:
The statue pushed the singularity when then flew off in the opposite direction from it while the statue remained alive

**Why is this bad/What are the consequences:**
Messes with the wizard gateway horribly as it can push the singularities around near the gateway which can then go and eat the gateway leaving no way out.

**Steps to reproduce the problem**:
Get the singularity in the wizard gateway, put a statue next to it, and wait.

**When did the problem start happening**:
Possibly around the time the move force PR was merged.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The statues can also push anything that is not wall.  Engine containment generators, shield generators, airlocks, doors, machines, windows, ect.  I noticed goliaths can also do the same with airlocks so it may be possible they can push singularities too.

**Comment by TDSSS** [comment]
I just tried it with a goliath and the goliath got gibbed the moment he walked into the singulo, without moving the singulo.
