### ISSUE TITLE
Turbine parts sometimes have to be rotated fully for it to work 

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10674]
**Problem Description**:

You have to rotate the turbine pieces in order for it to work. (If built vertically, compressor at the top)

**What did you expect to happen**: 

The generator piece to automatically link to the compressor if it was built in the correct position.

**What happened instead**:

The piece was "broken and non-functional" until it was rotated 360°.

**Why is this bad/What are the consequences:**

New Atmosians may not realise the issue, and think they're doing something wrong.

**Steps to reproduce the problem**:

1) Build generator stage of turbine
2) Build compressor stage one tile up
3) Note how the generator does not generate until it is rotated four times.

**When did the problem start happening**:
Unknown.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

N/A

**Comment by silverplatedelta** [comment]
Pretty sure I fixed this in #21343. Thanks for the report!
