### ISSUE TITLE
Research Director does not automatically spawn with a translator implant

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#10687]
**Problem Description**:
What is the problem?

If you spawn in as a Grey RD without the Translator Implant preference set to Yes, you will not be automatically spawned in with one.
**What did you expect to happen**: 
Why do you think this is an issue?

I believe that every member of Command, in addition to mindshielded staff, are supposed to automatically spawn with a translator implant, if I read the information on the translation implant PR correctly.
**What happened instead**:
How is what happened different from what you expected?

I had to ahelp to receive a translator implant.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Because I enjoy playing normal jobs WITHOUT the implant, but I understand that it is important for Command members.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Play Grey, have the Voice Translator preference set to "No", and join as the Research Director.
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

As far as I know, it's been this way since the translators were implemented.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
This applies to both latejoining and roundstart RDs.

**Comment by datlo** [comment]
found the issue, making a PR to fix
shame on me for not testing this throughly enough I guess
