### ISSUE TITLE
Can't deconstruct completed AI cores

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10690]
**Problem Description**:

Title.

**What did you expect to happen**: 

To be able to deconstruct an AI core after it's complete.

**What happened instead**:

Couldn't deconstruct it. 👀 

**Why is this bad/What are the consequences:**

Cannot deconstruct empty AI cores, or cores that shouldn't have been built. Can't get the brain back if you desperately need a temporary AI, but don't need the temp. one for the entire round.

**Steps to reproduce the problem**:
1) Build an AI core, or use the one in the AI sattelite.
2) Once the reinforced glass has been screwed in (and the core is inactive/has an AI in it) attempt to screwdriver the glass out.
3) Observe how your screwdriver deviates from where the screws are, and then stabs itself into the core.

**When did the problem start happening**:

Not sure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

N/A

**Comment by dovydas12345** [comment]
Looks intentional to me.
![image](https://user-images.githubusercontent.com/37041561/55023231-01fe1c80-5005-11e9-9307-d80de7f35a80.png)

**Comment by DGamerL** [comment]
They can be deconstructed now.
Fixed by:

- #14479
- #14477
