### ISSUE TITLE
Bat swarm is an absolutely broken simple mob with the same sprite as the easy to kill bats.

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10694]
**Problem Description**:
Bat swarms can be spawned by reality tears or chemical/xenobio reactions. This mob is intended for the admin only ancient vampire, have the same sprite as regular bats, and are EXTREMELY ROBUST.

**What did you expect to happen**: 
Bash bats a couple of times with my baton, heal the little brute damage I take, go on my merry way

**What happened instead**:
i ded pls nerf

**Why is this bad/What are the consequences:**
Mob that's probably a 100 times more robust than the original shouldn't share the same sprite. This wouldn't be an issue if admin only, but they can be spawned without admin intervention.

**Steps to reproduce the problem**:
Get swarm bats spawned by reality tears event or xenobio angry gold spawns. Get absolutely robusted. Cry.

**When did the problem start happening**:
Probably always been the case since bat swarm was added.

**Comment by datlo** [comment]
This is the bat swarm code for reference.
```
/mob/living/simple_animal/hostile/scarybat/batswarm
	name = "bat swarm"
	desc = "A swarm of vicious, angry-looking space bats."
	speed = 1
	harm_intent_damage = 25
	maxHealth = 300
	melee_damage_lower = 10
	melee_damage_upper = 30
	a_intent = INTENT_HARM
	pass_flags = PASSTABLE
	universal_speak = 1
	universal_understand = 1
```

**Comment by MrMagolor** [comment]
I mean, can this be any more broken than xenobio alien queens or Lesser Hellhounds?

**Comment by datlo** [comment]
The issue isn't the mob's strength, it's that it has the same sprites as regular bats

**Comment by Nicaragua1** [comment]
Maybe changing their eyes colours
