### ISSUE TITLE
Syndie encryption key intercepts bypass jammers/interferance

### ISSUE THREAD

**Issue by craftxbox** [ParadiseSS13/Paradise#10701]
**Problem Description**:
Syndie encryption key intercepts bypass jammers/interferance

**What did you expect to happen**: 
to see/hear garbled data

**What happened instead**:
message and sender came through perfectly, as if jamming never happened

**Why is this bad/What are the consequences:**
i dont believe you can 'decrypt' interference.

**Steps to reproduce the problem**:
1: have syndicate encryption key
2: have someone in radius of an active jammer
3: be outside the radius of the jammer yourself
4: have the jammed person try to use radio
5: observe how intercepted messages are fine, but regular ones are not.

**When did the problem start happening**:
not sure

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
nope

**Comment by datlo** [comment]
This is probably because syndi comms work on magic and bypass basically all comms systems.

Bit of an edge case, although logically it should work as you describe

**Comment by DGamerL** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/a4ab9f1c-6ef5-4c86-a786-68fbbbf75554)

This is working as intended, thank you for making the report!
