### ISSUE TITLE
Chameleon flag doesn't explode immediately when lit

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10704]
**Problem Description**:
Chameleon flag description says "There is a heat sensitive bomb loaded into the pole that will be detonated if the flag is lit on fire.", this implies the flag will explode on the one that sets the flag on fire. 
The flag only explodes once it's done burning into ashes, which is like several minutes later and doesn't make sense from either a logic or game design perspective

**What did you expect to happen**: 
Light syndi flag on fire, get exploded for daring to offend the Syndicate, learn a valuable lesson in modesty

**What happened instead**:
Light syndi flag on fire, go along my business, some random clown that passes by later explodes for no reasons

**Why is this bad/What are the consequences:**
Makes the flag only useful as an expensive, delayed minibomb which isn't what its purpose should be

**Steps to reproduce the problem**:
Light flag on fire, doesn't explode immediately

**Comment by datlo** [comment]
The flag is literally not working as the description is written and is clearly designed to work (Someone light syndi/clown/whatever flag on fire = explosion as vengeance against them)

I'm not sure if this is because the flag is old and the procs were changed causing this not to work as designed or just because it was not coded properly, but this is clearly isn't working properly either way.

**Comment by Citinited** [comment]
The description isn't quite accurate I'll agree, but it does explode eventually after being on fire for a bit. Nowhere does it indicate that it's meant to be used for vengeance, so it's not unintentional that it doesn't immediately explode.

I think it's always behaved this way since it was originally added to paradise

**Comment by datlo** [comment]
So according to the original commit this is working as intended... Doesn't make any sense to me. I'll close this issue, but this should still be changed.
