### ISSUE TITLE
Robotic brain module vanishes completely from the game when 'inhabitant' suicides

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#10720]
**Problem Description**:
What is the problem?
When you get in a robotic brain (for example through the ghost prompt when a roboticist activates one) and commit suicide while you're in a robotic brain, and not yet in any body, the whole robotic brain module vanishes.

**What did you expect to happen**: 
The robotic brain would 'flatline' and would be able to be re-activated to get another ghost in.

Why do you think this is an issue?
Robotic brain modules get wasted and it's a major mindfuck because people haven't figured it out and think someone took the brain or whatever.

**What happened instead**:

The whole module vanished.

How is what happened different from what you expected?
See above
**Why is this bad/What are the consequences:**
See above
Why do you think this is an important issue?
It's not a major issue, but I don't think it's how it's intended to work regardless.
**Steps to reproduce the problem**:
Get into a robotic brain, commit suicide
The most important section. Review everything you did leading up to causing the issue.
See above
**When did the problem start happening**:
Since robotic brains were seperate from posibrains I guess.
If your report is about something that used to work but no longer does, when was the last time you remember it working?
N/A
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: 
N/A
Anything else you can tell us.
N/A

**Comment by aleksix** [comment]
Fun fact: the robotic brain doesn't get wasted, it just becomes invisible. Just a bug with robobrains and their "dead" graphics
