### ISSUE TITLE
Put_in_hands can put an item in a non-existent hand

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10730]
**Problem Description**:
If your arms/hands are removed for whatever reason, you can still get items put in your hands by the put_in_hands proc. Example : Mime fingergun, grabbing a chair by dragging it to you when placed, grabbing something out of an engineering cart, and MANY more situations.

**What did you expect to happen**: 
Can't grab something without hands.

**What happened instead**:
In a lot of situations, you can.

**Why is this bad/What are the consequences:**
This is inconsistent and should be fixed.

**Steps to reproduce the problem**:
1. lose hands
2. cast fingergun/drag placed chair to you/whatever many situations calls the put_in_hands proc

**When did the problem start happening**:
No clue, but probably a whiiiile back.

**Comment by datlo** [comment]
this is a bug that affects everything that uses "put_in_hands" because it doesn't check if you HAVE hands even though it should 😠

**Comment by Diegoflores31** [comment]
You can also wield with one hand (crusher)
