### ISSUE TITLE
Biogenerator Bug

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#1076]
Biogenerator in Hydroponics gets stuck when you accidentally try to generate more Robust Harvest than the beaker currently in it can hold. It also counts as "Processing" still, so you can't take it apart with a screwdriver+crowbar. This makes it completely inoperable.

**Comment by MrBauer24** [comment]
There is code there to prevent that. It is strange you are experiencing this. I will see what I can do.

**Comment by MrBauer24** [comment]
Fixed with latest patch
