### ISSUE TITLE
When downloading the code for paradise and doing the correct procedures, The map does not load.

### ISSUE THREAD

**Issue by JackTheThinker** [ParadiseSS13/Paradise#10764]
**Problem Description**:
I downloaded the latest paradise code using Git Bash and compiled the code correctly with zero errors and tried to launch the server with dream deamon, it worked but as soon as I try to force the round to start....The server does nothing but just show the starting screen also the panel for setup characters,observe and etc. is not there.

**What did you expect to happen**: 
I expected the server to start up like any normal server

**What happened instead**:
The server did not start up

**Why is this bad/What are the consequences:**
Well I mean its best to fix all the bugs so that we can have a good and balanced out game plus I wanna test out some things on my own.

**Steps to reproduce the problem**:
1.Well download the paradise code with git bash or just download it straight from github.
2.Open the file and find config/examples and copy and paste it out side the folder.
3.Open up the executable and click on build and compile.
4.Launch the server with dream daemon

**When did the problem start happening**:
When I tried to run the paradise code for the first time

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nope it just didn't show the setup character panel and I could not talk while at the title screen like OOC

**Comment by datlo** [comment]
I've had this bug multiple times while I had another dream daemon running a server in the background, causing runtimes and the server not to start properly.

Ensure you've got no server instances up and running at all before launching your local server.

Unless this happens even after you've rebooted your computer completely, this issue should be closed.

**Comment by datlo** [comment]
Can't help you unless we get more details like any occuring runtimes, you can see them in the debug tab, "view runtimes", if you have admin rights

**Comment by JackTheThinker** [comment]
Well fuck me....It just works now......I am.....In awe.......really.....So I think I had to move the files first first then compile it and it fixed my issue......wow

**Comment by datlo** [comment]
Please close this issue, then, glad you got it working

**Comment by Shadow-Quill** [comment]
@Fox-McCloud Issue resolved.
