### ISSUE TITLE
Loading template app (pda_main_menu) failed!

### ISSUE THREAD

**Issue by DrKrieger1999** [ParadiseSS13/Paradise#10760]
**Problem Description**:
Sometimes if i open the PDA there is shown: ERROR: "Loading template app (pda_main_menu) failed!"
And that keeps opening mutible windows of the error.

**What did you expect to happen**: 
Normaly the Hud main Menu should be shown.

**What happened instead**:
It showed an error Message.
![unbenannt](https://user-images.githubusercontent.com/3455769/51806269-50e33c00-2278-11e9-9d0d-b410b04194da.png)

**Why is this bad/What are the consequences:**
Need to restart game because of it. And the error is hard to close, because it opens queite fast and unlimited.

**Steps to reproduce the problem**:
Run Server. Join and open PDA. Happend on my private Server also on Paradise Station official sometimes. 
Can be fixed by reconnect to the Server.

Gamemode was extendet.

**Comment by Kyep** [comment]
I've had this happen to me. It is extremely annoying.

I'm not certain what causes it, but I have heard that corrupted caches might be a factor. Try clearing your BYOND cache.

**Comment by JohnBigless** [comment]
It rarely happens upon reconnecting.

I'm not sure why, or how, but if you interact with a console, the problem will instantly fix itself.

**Comment by moxian** [comment]
PDAs are TGUI since #14403 , so this particular error should not be happening anymore.

**Comment by AffectedArc07** [comment]
PDA nano hell is purged,
