### ISSUE TITLE
Virology mechanics Broken

### ISSUE THREAD

**Issue by Imotepchief** [ParadiseSS13/Paradise#10762]
**Problem Description**:
While trying to isolate and acquire new virus symptoms, any sample taken from a bottle, placed into a separate beaker and altered in any way, will also affect the bottle the originally came from, making it impossible to keep symptoms isolated.

**What did you expect to happen**: 
I have quite a lot of experience with the virology mechanics at this point, the effect I described has not occurred before today as far as I am aware and is certainly not desirable, as it makes virology effectively useless. 

**What happened instead**:
Normally symptoms can be isolated down and different containers are not linked together mystically

**Why is this bad/What are the consequences:**
Virology is Shrek'd

**Steps to reproduce the problem**:
On the paradise server, take you normal starting serum, move 1u of it using the pipette into a separate beaker, then apply virus plasma to that separate beaker, which will add a new effect, check it in the pandemic to see the new symptom, then remove from pandemic and place the original source bottle into pandemic, it will now also have the new symptom. That is not how it is supposed to work.

**When did the problem start happening**:
The problem started occurring at a shift starting at roughly 11pm GMT, the previous shift the problem was not present, but is now still occurring.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The normal secret para gamemode.
Nothing else out of the ordinary occurred that I am aware of.

**Comment by farie82** [comment]
Confirmed. Instead of copying the data it gives a reference to the virus. How this happens I have no clue due to it being copied instead of referenced in the code.
Making a new culture will not give a reference to the original virus and thus avoiding the problem.
It seems that the list.Copy() method is broken.
