### ISSUE TITLE
EXPERIMENTOR fails to produce intended items due to flaw populating valid_items

### ISSUE THREAD

**Issue by SpessX** [ParadiseSS13/Paradise#10774]
**Problem Description**:
When irradiation is selected as the correct test for one of the few critical items (e.g. slime cores), the EXPERIMENTOR's code is meant to transform it into a random food, stock part, chemical grenade or kitchen item. It has been failing to do so for a couple years, producing instead the same set of booze bottles.

The cause (tested on local server) is the way valid_items is populated in experimentor.dm. valid_items gets populated first with a large number food items. When calculating the item that will be produced, it succeeds at finding one way before it gets to any non-food items in the valid_items list.

It behaves as expected by shuffling the items beforehand, e.g. replacing:

`for(var/I in typesof(/obj/item))`

with:

`for(var/I in shuffle(typesof(/obj/item)))`

Note that valid_items is a list of probability, item, probability, item, probability, item, value pairs, so it can't be shuffled directly.

Shuffling the list of items makes it not affected by changes in the order items are loaded into valid_items / changes in the number of items in those categories. The items already have a probability weighting in the EXPERIMENTOR code to control how often they appear.

**What did you expect to happen**: 
EXPERIMENTOR used to produce the intended items when irradiating valid critical items, and should still be doing so.

**What happened instead**:
EXPERIMENTOR ceased to produce the items at some point a couple years ago. The way valid_items is populated makes it sensitive to any change in the order for the global list of items, and any change in the number of food items, so it was very likely victim of changes elsewhere.

**Why is this bad/What are the consequences:**
The feature itself is supposed to provide an alternative way of boosting research by obtaining some higher level items from it. It's balanced by requiring critical items that are already high level themselves, and by the chance of actually getting higher level items having a high RNG component. Without it Research progress is more linear and involves fewer complicated / risky mechanics.

EXPERIMENTOR is already on life support due to few people ever exploring the critical items feature. The feature being broken makes it more likely to be removed altogether, despite the EXPERIMENTOR being along toxins a main risk/events source working the science department.

Antagonists have to break into the visible research room to source chemical grenades, when the EXPERIMENTOR is more accessible, though slower/harder to use for the purpose.

Currently the EXPERIMENTOR is also the main way to restart xenobiology from used grey slime cores, as the duplication feature will produce fresh grey cores from used ones. This would be lost if the EXPERIMENTOR was removed due to having broken features.

**Steps to reproduce the problem**:
1. Load slime core into experimentor (or any of the other critical items)
2. Irradiate the slime core.
3. If the experiment fails, rebuild the experimentor and try again until it rolls irradiate as the valid test for that core type.
4. Observe the item the core has been transformed to. It'll be one of a set of booze bottles, a holy water flask or a unholy water flask.
5. Eject till the EXPERIMENTOR is empty and repeat again.
6. Observe that the result is still the same few bottles.
7. Repeat on different rounds. Observe the same results.

**When did the problem start happening**:
It worked approximately two years ago, roughly around the time the feature to increase tech levels was removed from the EXPERIMENTOR. I stopped then messing with irradiating critical items with the EXPERIMENTOR as it was now producing identical uninteresting results every round.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Although EXPERIMENTOR was already nerfed when this feature was working, and this feature was balanced by requiring critical items that aren't common / are already high tech level, if it required rebalancing due to the passage of time it should happen by tweaking the probWeight formulas. A single change on an integer is enough to increase the chances of obtaining relatively useless food items.

**Comment by DGamerL** [comment]
The inital problem is indeed to just make the list shuffle, however, this has some other issues as there are definitely stock parts and food items that should be restricted, will not be, causing some chaos if those are not accounted for.
