### ISSUE TITLE
On White mode changelog button is not the same white as other buttons

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#10782]
**Problem Description**:
When on white mode changelog button not same color as other buttons.

![image](https://user-images.githubusercontent.com/37041561/51983409-4788e800-24a1-11e9-88dd-817dc7f0fa04.png)

**What did you expect to happen**: 
For it to be the same color.

**What happened instead**:
Its slightly off in color!

**Why is this bad/What are the consequences:**
Muh OCD is angry.

**Steps to reproduce the problem**:
I saw that there was something new added so i clicked on the button to check out and make it not flashy.... Instead i got this.

**When did the problem start happening**:
After dark mode was added

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Just that.

**Comment by dovydas12345** [comment]
Some extra info: It would appear it only becomes that when going from dark mode into normal mode.... Or something like that

**Comment by AffectedArc07** [comment]
This is because I used `WINSET` to make the button pure white, a fix is being worked on to make the changelog button integrate with the darkmode better, and this should be fixed in it
