### ISSUE TITLE
Cult Cuffs Don't Poof

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10799]
**Problem Description**:

The cultist cuffs created by the cuff talisman do not correctly go away when they're removed/taken off/broken out of.

**What did you expect to happen**: 

Dissapearing cuffs to dissapear.

**What happened instead**:

Dissapearing cuffs did not dissapear.

**Why is this bad/What are the consequences:**

Cult magic does not look like zipties.

**Steps to reproduce the problem**:

1) Cuff someone with a cuff talisman.
2) Breakout/remove the cuffs.
3) Observe the cuffs now laying on the ground.

**When did the problem start happening**:

Unknown.

**Comment by someanonredditor** [comment]
Do you get the message "x's shackles shatter in a discharge of dark magic!"?

**Comment by Shadow-Quill** [comment]
I indeed do.
