### ISSUE TITLE
Atmos Distro connected to Filter

### ISSUE THREAD

**Issue by Muhdi345** [ParadiseSS13/Paradise#10803]
**Problem Description**:
the latest merge for the piping: https://github.com/ParadiseSS13/Paradise/pull/10754

It creates the problem that distro is connected to the filter in this spot:
![atmos](https://user-images.githubusercontent.com/47270900/52163439-44306f00-26e2-11e9-97d1-06080b1b52dc.png)

If the adapter is connected, which it is at roundstart, it'll connect distro to the filter, you cannot wrench the adapter into this position normally.

**What did you expect to happen**: 
Not having distro connected to the filter at roundstart

**What happened instead**:
Distro is connected to the filter at roundstart.

**Why is this bad/What are the consequences:**
The filter will continually push breathable air back to the filter. And if scrubbers catch any plasma or hazardous gasses, it'll push it to the vents too.

**Steps to reproduce the problem**:
Start a round, notice distro and filter have the same pressure.

**When did the problem start happening**:
Just noticed it after the piping merge.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Any round is fine.

**Comment by FreeStylaLT** [comment]
I figured that clustertruck would cause issues.
