### ISSUE TITLE
Dying as maint drone sometimes removes midround role rights.

### ISSUE THREAD

**Issue by possunn** [ParadiseSS13/Paradise#10808]
**Problem Description**:
Maint. drones often make you ineligible for midround antag roles, or any rights to respawn as an NPC after death, and generally behave as if you had ghosted or turned on antagHUD.

**What did you expect to happen**: 
To be able to rejoin the round as a midround role, given the drone hadn't ghosted/enabled antagHUD.

**What happened instead**:
Server acts as though the user had forfeited respawn rights, when they have not.

**Why is this bad/What are the consequences:**
Dissuades further maintenance drone play, considering a drone receiving a kill command or being destroyed by crew will no longer be able to take part in the round in any form.

**Steps to reproduce the problem**:
- I tried using a suicide command as a maint. drone sometime in late 2018. This happened at least twice, though I'm not sure exactly how long I'd been a drone at that point in the round.

- I joined as an observer before round, then joined as a drone. In one incident I was sent a kill order, deactivating myself. Again, having my ghost reset did nothing, and I was informed further action could not be taken by an admin. I had been alive for around 10 minutes.

- The same happened after beating myself to death with a wrench as a drone. I had been a drone for around forty minutes at this stage.

**When did the problem start happening**:
I'd say the suicide incidents happened through October-December 2018, but it began happening in succession on 03/02/19.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Between these incidents, there had been times where I've died as a drone and been able to revive as other roles just fine, especially beating myself to death with a tool instead of using the suicide verb.

**Comment by SpessX** [comment]
I confirm it started happening around those dates. I regularly started rounds as drone then suicided to observe mid round.

Normally, valid suicides gave you an invisible ghost sprite, while actual ghosting gave you the drone sprite. All deaths give you a drone sprite as ghost now as well as count as ghosted. 

Cause of death doesn't seem to matter. Hitting yourself with rods, getting zapped at the engine, deactivating yourself with the console or having the emagged drone timer expire all leave you excluded from ghost roles.
