### ISSUE TITLE
More piping issues

### ISSUE THREAD

**Issue by Muhdi345** [ParadiseSS13/Paradise#10810]
**Problem Description**:
Piping has disappeared from this spot to the space cooling loop:
![space loop](https://user-images.githubusercontent.com/47270900/52167312-87f29b00-2719-11e9-93a1-e70ac387c9a8.png)

And the right airlock to containment has lost it's vents and piping:
![missing vents](https://user-images.githubusercontent.com/47270900/52167315-9c369800-2719-11e9-8c23-f5b195ce33c1.png)

Unconnected anchored air tanks:
![air tanks](https://user-images.githubusercontent.com/47270900/52167424-13206080-271b-11e9-92be-6a624b72edbf.png)

Unconnected connector:
![connector](https://user-images.githubusercontent.com/47270900/52167430-292e2100-271b-11e9-8ca6-29a1b0c0746b.png)

**What did you expect to happen**: 
the piping should be available at shift start, since it was there before the merge.

**What happened instead**:
They're gone! KAPUT

**Why is this bad/What are the consequences:**
More QoL for now. It's not hard to miss.

**Steps to reproduce the problem**:
Start a shift, any shift as an engineer or atmos

**When did the problem start happening**:
After the recent piping merge. https://github.com/ParadiseSS13/Paradise/pull/10754

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
More piping issues probably coming up as I find them.

**Comment by FreeStylaLT** [comment]
The first two are issues, the third / fourth are odd:
![img](https://cdn.discordapp.com/attachments/195271472992878592/541419035913486361/dreammaker_2019-02-03_09-44-55.png)
Piping already exists there.

**Comment by KasparoVy** [comment]
Rest in Pipes, begone with the gripes

🤣

**Comment by Muhdi345** [comment]
Guess what, the left containment airlock has no more piping now.
