### ISSUE TITLE
Cloning Removes Special Reagent Healing

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#10829]
**Problem Description**:
When cloned, Mimes lose their ability to heal from drinking Nothing

**What did you expect to happen**: 
When cloned, drink some delicious Nothing and heal.

**What happened instead**:
When cloned, drank some delicious Nothing and nothing happened.

**Why is this bad/What are the consequences:**
An important part of being a Mime is being able to recover from drinking Nothing. Losing this upon cloning may cause Mime players to be less risk-taking.

**Steps to reproduce the problem**:
1. Be Mime
2. Die
3. Get cloned
4. Drink Nothing and cry.

**When did the problem start happening**:
A fairly long time ago, not exactly sure when it started.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
This **may** also affect Clowns and their Banana Juice healing, and maybe Security being healed by Donuts and Frosted Donuts, as well as any others who get specific reagent healing bonuses.

**Comment by Spacemanspark** [comment]
I see Nothing wrong here

**Comment by someanonredditor** [comment]
Looks like the cloner doesn't transfer `/mob/living .job` to the new body.

This means cloning might also break banana juice healing for clowns, prayer bread nullification of clowns, the Codex Gigas for all roles who can use it, sprinkles for security, and possibly the "pray" verb for Chaplains.
