### ISSUE TITLE
Unpowered/Unclaimed Tile

### ISSUE THREAD

**Issue by Muhdi345** [ParadiseSS13/Paradise#10821]
**Problem Description**:
This tile is unpowered and doesn't seem belong to the atmos room:
![unpowered](https://user-images.githubusercontent.com/47270900/52174887-f1ff5480-279a-11e9-94dd-5cadc97ea151.png)

**What did you expect to happen**: 
Having a powered volume pump

**What happened instead**:
It's unpowered!

**Why is this bad/What are the consequences:**
Makes the space loop useless if an atmosian doesn't know what's happening.

**Steps to reproduce the problem**:
Start a round, try to enable the volume pump.

**When did the problem start happening**:
After the piping merge/fixes of the piping merge. https://github.com/ParadiseSS13/Paradise/pull/10754

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing else of note.

**Comment by FreeStylaLT** [comment]
what the heck do you in your free time, actually _work on Atmos_?!

**Comment by DesolateG** [comment]
Just add an apc to space... power the galaxy!

**Comment by Muhdi345** [comment]
Piping is my life!

**Comment by DesolateG** [comment]
So are plasma fires in the turbine room

**Comment by Muhdi345** [comment]
Now now... I think I've grown beyond those... for now.

**Comment by Muhdi345** [comment]
So, at least the other containment airlock (the left one) is broken as well now.
![containment airlock2](https://user-images.githubusercontent.com/47270900/52181214-e38f5800-27ef-11e9-89c8-cab274bf8c20.png)

An airlock in arrival maint is unpowered. (unsure if this is because of tampering but I can't ghost interface it)
![unpowered airlock](https://user-images.githubusercontent.com/47270900/52181222-f4d86480-27ef-11e9-9fde-91abf2ae4f98.png)

More airlocks I can't interface with or use the Airlock Controller, Also the Engineering airlock seems broken:
![aft starboard solars](https://user-images.githubusercontent.com/47270900/52181240-1fc2b880-27f0-11e9-8206-4fff45be13b3.png)

**Comment by Pennwick** [comment]
I'll have to ask the AI to turn off and on that APC until this is fixed.
