### ISSUE TITLE
Prisoner deletes Perma door with Potted Plant

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#10828]
**Problem Description**:
A Perma prisoner managed to delete the main door into Perma by breaking the reinforced glass above it (exposing the grille) and then throwing a potted plant twice at it.

**What did you expect to happen**: 
Nothing.

**What happened instead**:
First throw, sparks flew off. Second throw, the Perma door just _disappeared_. It was utterly gone.

**Why is this bad/What are the consequences:**
Perma prisoners can break out of Perma with just the potted plant.

**Steps to reproduce the problem**:
1. Break reinforced glass above Perma door.
2. Back up about 3 tiles.
3. Throw potted plant twice (at door? At grille? Couldn't tell.)

**When did the problem start happening**:
Saw it tonight on the new Perma layout.

**Comment by Deelite34** [comment]
The power of ELECTRIFICATION destroys some near stuff, when you throw items at electrified grille. I'd say it's not a bug, and prisoners can't do anything very useful with that, except destruction of that middle inside perma door, and electrification of near shitcurity.
