### ISSUE TITLE
Handcuffed Players Can Freely Get Up From Surgery Tables

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#10846]
**Problem:**
A player with handcuffs/zipties/etc. is normally buckled in place when put on a chair or bed; however, if you try to put them on a surgery table, they can get back up almost immediately and run off freely, as it breaks your drag.

**What Should Happen:**
Handcuffed players should be buckled when put on surgery tables, so they can't just run out the door immediately.

**Why It's A Problem:**
Makes Brig Physician's job harder, since Surgery on a rowdy prisoner becomes impossible without Anesthetics. If they're a race that can't breath it, Ether is the only option, as pain-killers don't knock them out, letting them run away mid-surgery.

Makes antagonistic surgery nearly impossible, since Ether is even less readily available, and Anesthetics may not be present.
Also kills any chance for torture on a surgery bed.

**How To Reproduce:**
Cuff someone, put them on a surgery table. They should be able to get up fairly unopposed and run away.

**When did it start happening?:**
Unsure, It wasn't a problem when I last played several months ago, but it's proven a regular problem now.

**Other Stuff**:
I haven't been on the cuffed end myself, but every cuffed person I've tried to put on a surgery table while awake has easily gotten up and ran away, so it's not a hard-to-find strategy.

**Comment by Fox-McCloud** [comment]
Not a bug. This is a feature request.
