### ISSUE TITLE
Linking discord account issue.

### ISSUE THREAD

**Issue by CornMyCob** [ParadiseSS13/Paradise#10874]
**Problem Description**:
When admins/mentors link their discord account, their ckey shows up as "The [ckey]" in adminwho for that round.

**What did you expect to happen**: 
My ckey not to change.

**What happened instead**:
My ckey changed.

**Why is this bad/What are the consequences:**
It's just a bit weird.

**Steps to reproduce the problem**:
Link your discord account or unlink+relink, check adminwho.

**When did the problem start happening**:
When Affected's PR got merged, presumably.  Hello @AffectedArc07 please fix.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A.

**Comment by AffectedArc07** [comment]
wtf
