### ISSUE TITLE
Free golems can be selected as assassination targets

### ISSUE THREAD

**Issue by EvadableMoxie** [ParadiseSS13/Paradise#10886]
**Problem Description**:
Free golems can become assassination targets if the original target cryos.

**What did you expect to happen**: 
For them to not be considered, given that they are now crew.

**What happened instead**:
They are considered.

**Why is this bad/What are the consequences:**
Assassinate targets should be crew. 

**Steps to reproduce the problem**:
Should have a chance to happen whenever an assassination target is assigned.

**When did the problem start happening**:
Probably when free golems were added.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

![image](https://user-images.githubusercontent.com/27022582/52610070-92b1dc00-2e4d-11e9-874f-4dc6a906e28f.png)

**Comment by datlo** [comment]
related to #10729
gonna fix soonTM
