### ISSUE TITLE
Can't not remove Bolas from self.

### ISSUE THREAD

**Issue by davidchan13** [ParadiseSS13/Paradise#10893]
**Problem Description**:
**When struck with a hand crafted Bola, it fails to remove every time.**

**What did you expect to happen**: 
**After a 5 second cooldown, the bola would be removed.**

**What happened instead**:
**The game prompted me to wait 5 seconds, I did not move. Leg cuffed remaned no matter how many times I redid the resist to escape.**

**Why is this bad/What are the consequences:**
**You can be permanently leg cuffed, moving at a snails pace until someone else removes the leg cuff. Bolas are meant to be a minor annoyance, not a non removable malus. 

**Steps to reproduce the problem**:
**Have someone craft bolas (metal sheets + wire)**
**Have them throw bolas at you.**
**Become legcuffed**
**Stand completely still, resist and be prompted to wait .005 minutes**
**Watch the bar completely fill, but never received a message if you failed or successfully removed the legcuff, watch as your sprite remains leg cuffed and you infinitely retry to free yourself.**

**When did the problem start happening**:
I was an IPC miner, a clown was slipping people and stealing items near arrivals. When I confronted and chased them, they leg cuffed me and I was completely unable to remove the cuff. Admins were oblivious to how or why this was happening.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
See above, Changeling round.

**Comment by farie82** [comment]
Could not reproduce. Removing the bola myself just dropped it on the floor

**Comment by dovydas12345** [comment]
Could not reproduce either. It removed perfectly fine.

**Comment by Shadow-Quill** [comment]
Couldn't reproduce.
@Fox-McCloud

**Comment by Crazylemon64** [comment]
sounds like a runtime but I can't do much without further details
