### ISSUE TITLE
Nanopaste Can't Repair Robotic Limbs

### ISSUE THREAD

**Issue by Surrealistik** [ParadiseSS13/Paradise#1090]
Per the title. Noticed this repeatedly as a Mediborg.

**Comment by FalseIncarnate** [comment]
Unless I am mistaken, Nanopaste is meant for assisted/mechanical organs only, not limbs.

You repair robotic limbs with a welder or cables.

**Comment by Krausus** [comment]
Nanopaste actually is meant to be able to repair robotic limbs and mechanical organs, but was sufficiently broken that it couldn't do either. It will be able to do both when this fix is patched in.
