### ISSUE TITLE
Floor cluwne noises don't go away if you do this

### ISSUE THREAD

**Issue by TheMadTrickster** [ParadiseSS13/Paradise#10909]
**Problem Description**: Floor cluwne noises will stay permanently bugged in wherever the person gets snagged into the floor if the person has a living player-controlled in their backpack, such as a mouse, and most likely a diona nymph

**What did you expect to happen**: I expected the mouse to just disappear with my body, and end up dead and talking in dchat.

**What happened instead**: Mouse stayed alive, was able to keep emoting and talking and squikking, but its physical body was gone, and the cluwne noises bugged and permanently stayed in that spot. 

**Why is this bad/What are the consequences:** It's bad because its loud as hell and bugged noises are no good.

**Steps to reproduce the problem**: Fart on bible, Summon floor cluwne, Take player controlled mouse, put it in satchel or backpack, let floor cluwne take you

**When did the problem start happening**: I never did something like this before, so I didn't know it was broken all this time until now.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: I dunno what could be related, Nothing else was out of the ordinary.

**Comment by farie82** [comment]
Most likely due to the backpack being deleted by the gibbing. Will probably also happen when a person gets gibbed normally with a pet inside his bag.
