### ISSUE TITLE
Invisible bluespace crystals

### ISSUE THREAD

**Issue by Superhats** [ParadiseSS13/Paradise#10924]
**Problem Description**:
What is the problem?
When breaking down the entirety of a bluespace crystal cluster, you end up left with an invisible bluespace crystal in your hand, along with the ones on the ground. This crystal serves no purpose other than clogging up your hand slot, as it doesn't fit in machines.

**What did you expect to happen**: 
Why do you think this is an issue?
I shouldn't have anything left in my hand after breaking a cluster

**What happened instead**:
How is what happened different from what you expected?
I certainly didn't expect an invisible bluespace crystal in my hand

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Acquire multiple crystals from the ORM, resulting in a crystal cluster
Break down crystals from the cluster until none are left
Try to use hand
No hand

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Pressing the drop hotkey fixes the issue.

**Comment by Jazz23** [comment]
Yea I noticed this issue a long ass time ago but never bothered to post an issue. I would also like to add that throwing bluespace crystals will delete them. Don't know if this is intentional but yea. Also, personally I found to get the invisible crystals its like a separate stack on top of the refined stack, so after you done crushing clicking on the new stack of refined crystals yields an invisible one.

**Comment by Shadow-Quill** [comment]
Bluespace crystals are fragile, and will shatter if thrown. Polycrystals should be more stable. (Aka: yes, bluespace crystals being removed after being thrown is intended afaik)

**Comment by MrMagolor** [comment]
> Bluespace crystals are fragile, and will shatter if thrown. Polycrystals should be more stable. (Aka: yes, bluespace crystals being removed after being thrown is intended afaik)

I believe they mean the inhand-use option you get with polycrystals, to break them down at a 1:1 ratio of polycrystal to "refined bluespace crystal" i.e. for quantum pad/teleporter construction.

**Comment by Shadow-Quill** [comment]
"I would also like to add that throwing bluespace crystals will delete them. Don't know if this is intentional but yea."
