### ISSUE TITLE
Security cyborgs cannot be moved by pushing them on aggresive intent.

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#10922]
**Problem Description**:
What is the problem?
Dead security cyborgs cannot be moved by pushing them on aggresive intent.
**What did you expect to happen**: 
Why do you think this is an issue?
Everything is pushable, unwrenched machines, and humans, dead cyborg is not
**What happened instead**:
How is what happened different from what you expected?
Be able to push dead cyborg.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Everyone is pushable, except cyborgs, who are special for no reason.

**Comment by datlo** [comment]
This is working as intended, security cyborgs cannot be pushed.

**Comment by MarsM0nd** [comment]
While they are supposed to not be pushable, like having a riot shield, they probably should be able to be pushed when dead, which seems to be the issue.

**Comment by Deelite34** [comment]
I mean dead security cyborgs, they are not wrenched to floor on death, they are not heavier than lockers, vendors, that you can move with ease, they are alive mobile machines, that when death should be pushable. if you can pull dead cyborg, you should be able to push it.

**Comment by Fox-McCloud** [comment]
This is, indeed, working as intended and is definitely a request.

Mediborgs and secborgs are both immune to bumping under any circumstance or condition.

**Comment by someanonredditor** [comment]
Why can they be pulled then, if they're so immovable? Seems inconsistent.

**Comment by Fox-McCloud** [comment]
the point is that for an active combat/conflict situation, they can perform their job; as long as player agency is there, the fact they can still be pulled *usually* doesn't matter much.
