### ISSUE TITLE
Toxins mixing chamber vent pump missing

### ISSUE THREAD

**Issue by trexter555** [ParadiseSS13/Paradise#10931]
The vent pump used for pumping hot gas back into a canister is missing for some reason

**Comment by iantine** [comment]
![pic](https://user-images.githubusercontent.com/26665535/55401092-6daf2f00-559b-11e9-9e32-2f39bbd20434.png)
Picture to clarify - the red circle is where the vent should be. The pipe and connector leading down are useless as they currently lead to nothing.
