### ISSUE TITLE
Infinityblood bug

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#1094]
Found and confirmed by Deadeagle, he has no account, so posting his account of reproducing the bug:

Draw multiple samples at once
When first sample draws
Inject 5 units (possible 10) into a beaker
Then when it takes the second, it should become a sort of bottomless syringe
Anything it draws it deletes
Then take a second sample
Should be infinite blood

**Comment by TheDZD** [comment]
Already documented, #645.
