### ISSUE TITLE
Cult Sacrifice Objective Requires Admin Intervention To Complete

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#10958]
It's an old and well-known bug, I know, but it might as well be put up on the Github as a reminder.

**Problem Description**:
The Cult's Objective to "_Sacrifice [Crew Member]_" can not be completed normally, and requires an admin to manually set the objective as complete.

**What did you expect to happen**: 
After placing the target on the Tribute rune with 3 total invokers, for the sacrifice to go through, and to get the message: "_Yes! This is the one I desire! You have done well._" from the cult god, before being given the next objective.

**What happened instead**:
Whether the target is alive or dead, the cult god gives the message: "_I accept this sacrifice._" as if it was a non-target that was sacrificed. No further objectives are given.

**Why is this bad/What are the consequences:**
Cult rounds can't progress without admins being on-duty. Gives admins more work.

**Steps to reproduce the problem**:
Be in a cult of 4+; if sacrifice is not the current objective, complete the objective until it is given.
Capture the indicated sacrifice target and place them over a Tribute rune with 3+ cultists adjacent, then use the rune. Target's state doesn't seem to make a difference.

**When did the problem start happening**:
Possibly for more than a year at this point.

**Other Notes**:
Did some diving in hopes of helping a bit. For ease, the problem likely lies in files are listed below:
[Cult_Objectives](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/cult/cult_objectives.dm)
[Cult Runes](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/cult/runes.dm) (Lines 383-459)
[Cult](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/cult/cult.dm) 
EDIT: Problem described by Aurorablade below.

**Comment by Aurorablade** [comment]
Aware. It has to do with the mind. I need to convert that antag to antag datums. I had a PR for it. I need to clear a one or two other prs, should make it eaiser to fix.
Fun fact cult objectives aren't somemuch objectives as they are DIRECTLY...WRITTEN..TO THE MIND..

**Comment by Pckables** [comment]
Glad to hear it's being worked on! I wanted to put this up since I couldn't find any active PRs or other issues addressing this.
I wish you the best of luck.

**Comment by Pennwick** [comment]
If I had to guess it would be with the target ghosting before they're sacrificed. Which really I'm a bit confused by why it doesn't do the same thing as a soul stone. Soul stones try to force the soul back in the body so the cult isn't robbed of a construct. While the sacrifice rune just gibs the target even if the cult gets nothing from it. At least if they still had the body they could use it for the rite of resurrection.

**Comment by Pckables** [comment]
No, the problem persists if the target is alive and in their body while sacrificed. The only difference is that the target being dead results in them being put in a soulstone.
