### ISSUE TITLE
Genetics Syringes In Trader Event Do Not Work

### ISSUE THREAD

**Issue by possunn** [ParadiseSS13/Paradise#10952]
**Problem Description**:
See title. The genetics powers in the syringes that can be sold during trader events don't work.

**What did you expect to happen**: 
For them to pass on the labelled power they are sold as.

**What happened instead**:
They did nothing.

**Why is this bad/What are the consequences:**
It'll end up meta dissuading crew from buying genetics powers from the traders, considering it doesn't work. Ends up being a useless addition to the ship's stock.

**Steps to reproduce the problem**:
Spawn traders in. Try to use the SE syringes that spawn in with them. 

**When did the problem start happening**:
I noticed this happen the first time I bought one, then again when I sold one as a trader. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
TK and regeneration were the syringes I tried.

**Comment by Kyep** [comment]
I tested a bunch of syringes just now, but the only one that doesn't work is TK.

It produces this runtime:

[2019-02-26T13:38:28] Runtime in dna_injector.dm,81: Cannot read null.types
   proc name: inject (/obj/item/dnainjector/proc/inject)
   usr: CHARNAME (CKEY) (/mob/living/carbon/human)
   usr.loc: The floor (106,28,2) (/turf/simulated/shuttle/floor)
   src: DNA-Injector (Tele.) (/obj/item/dnainjector/telemut)
   src.loc: CHARNAME (CKEY)  (/mob/living/carbon/human)
   call stack:
   DNA-Injector (Tele.) (/obj/item/dnainjector/telemut): inject(Colin Black (/mob/living/carbon/human), CHARNAME (CKEY)  (/mob/living/carbon/human))
