### ISSUE TITLE
dupping bug

### ISSUE THREAD

**Issue by tecroach** [ParadiseSS13/Paradise#10979]
**Problem Description**:
What is the problem?  Dup bug

**What did you expect to happen**:  removing the small grill thing
Why do you think this is an issue?  coding error

**What happened instead**:  duping rods
How is what happened different from what you expected? 

**Why is this bad/What are the consequences:** free metal
Why do you think this is an important issue? it's free metal so maybe

**Steps to reproduce the problem**: Step by step how to do it, one remove window but with tools and then bash the grill then remove other window with tools at assembly line above toolbelt then remove table with tool then replace table in the same spot and then use tool to remove the rest of the grill and boom duping rods
The most important section. Review everything you did leading up to causing the issue.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?  mmm i was fixing the grill and that how it happen

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:  N/A
Anything else you can tell us.  uh well i was arrested by a borg while trying to get the welding goggles then was briged then went back and got them and then looted the tool box and try to rebuild the window.

**Comment by taukausanake** [comment]
I thought the duplication with rods was not a thing? Break the grille and you get some rods, snip the remains and you get the rest of the rods. You sure you counted the number of rods you got?

**Comment by tecroach** [comment]
uh  i can keep cutting too i over ran the server with rods

**Comment by tecroach** [comment]
easy to redo the dupping bug

**Comment by tecroach** [comment]
![bug](https://user-images.githubusercontent.com/16874350/53689674-bb304600-3d28-11e9-83e9-227893535b7e.png)

**Comment by tecroach** [comment]
mmmm  when the glass is remove from under me it stop duping the rods...

**Comment by tecroach** [comment]
the glass is the key for the bug to start duping

**Comment by tecroach** [comment]
no wait, it any items

**Comment by tecroach** [comment]
any items under you will trigger it

**Comment by tecroach** [comment]
and found anywhere that like that will end up duping the rods

**Comment by Pennwick** [comment]
I think this bug is probably related to stacking maybe. There are a bunch of single stack rods when they should merge and there are even 0 stack rods. It also seems to have maybe come into being at the same time #10962 was merged.

**Comment by KasparoVy** [comment]
I've had a wack issue with stacking where dragging rods/metal sheets would eventually produce stacks of 0 as well as glitch my character into not being able to proc .moveup, down, left or right in any capacity. Closing and re-opening my client fixes that.

**Comment by tecroach** [comment]
well in this case it make both stacks of 0 and then in some case it really dups the rod and gives a +1 rod
