### ISSUE TITLE
Holoparasite Can't See Their Intent

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#10987]
**Problem**:
Holoparasites can switch between help and harm intent, but don't have a UI element telling them which they are on.

**Why is this bad/What are the consequences:**
Your master tells you to beat up their target, and you end up nuzzling them 10 times instead.

**Steps to reproduce the problem**:
Be a holoparasite on hotkey mode. Press 1 to switch to help, or 4 to be on harm. The only indicator is what happens when you click on someone.

**Possibly related stuff**:
I took over the holoparasite after the user chose to have a different person as their holoparasite.

**Comment by KasparoVy** [comment]
Embrace not erase
