### ISSUE TITLE
Fat disability not working.

### ISSUE THREAD

**Issue by vxnillx** [ParadiseSS13/Paradise#10986]
**Problem Description**:
Fat roundstart disability stops 20 minutes in.

**What did you expect to happen**: 
Be fat through the whole round.

**What happened instead**:
Slimmed down after 20 minutes or so.

**Why is this bad/What are the consequences:**
I cant RP as my fat old man

**Steps to reproduce the problem**:
Be fat roundstart. 

**When did the problem start happening**:
probably when disabilites were changed

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/53701399-b5079b80-3df4-11e9-8772-202ec4b0a2cd.png)

**Comment by Ty-Omaha** [comment]
The questions in bold are meant to be answered...

**Comment by vxnillx** [comment]
ive never used this site before im just gonna try again

**Comment by Ty-Omaha** [comment]
you can edit your post in the top right there's 3 dots click that

**Comment by vxnillx** [comment]
This is also probably not right

**Comment by AffectedArc07** [comment]
@vxnillx press this 
![image](https://user-images.githubusercontent.com/25063394/53701890-79230500-3df9-11e9-8e73-a985706a5cec.png)

**Comment by datlo** [comment]
assuming i'm following what you're saying correctly this is working as intended

fat makes you obese roundstart but you can still lose the weight (by walking around and not eating)

it also makes it easier to get fat again IIRC

**Comment by vxnillx** [comment]
I still expected it to work throughout the round, maybe that can be changed? also. I fixed it for real this time.

**Comment by Fox-McCloud** [comment]
Working as intended. Not a bug. THis is a feature request.
