### ISSUE TITLE
White Ship Issues

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#1099]
The most glaring one is that the pod doors does not work, other issue is the lack of supplies to contruct the computer. In this case a cable coil. Probably a toolbox or a wrench and a screwdriver. The latter is more a suggestion rather then an issue.

**Comment by tigercat2000** [comment]
Eeeerrr can you specify what you mean by "the pod doors does not work"?
they don't open? They don't respond to spacepod requests?

**Comment by Robertha89** [comment]
don't respond to the spacepod request.
