### ISSUE TITLE
You can't utilize the 'customize' surgery on robotic hands, feet, and lower body.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#10997]
I forgot how much I hate this format system.

**Problem Description**:
You can't utilize the 'customize' surgery on robotic hands, feet, and lower body.

**What did you expect to happen**: 
I can't make IRCs into one complete model, making me a very sad roboticist.

**What happened instead**:
Unbranded hands/ feet for days.

**Why is this bad/What are the consequences:**
Every IRC looks ugly unless they're completely Unbranded.

**Steps to reproduce the problem**:
Do surgery- oh wait don't because you can't :^(

**When did the problem start happening**:
N/A

**Possibly related stuff**:
Spark was X

**Comment by MrMagolor** [comment]
>What did you expect to happen:
I can't make IRCs into one complete model, making me a very sad roboticist.

There is a workaround: use robotic limbs inhand to change their model.

Why the system is so inconsistent is beyond me.

**Comment by Spacemanspark** [comment]
Doesn't work for the lower body, though.

**Comment by MrMagolor** [comment]
Actually, are there even alternate sprites for the lower torso? For all I know the upper body changes the visuals of both, for IRCs.

**Comment by Spacemanspark** [comment]
There are alternate sprites for the lower torso, yes.
