### ISSUE TITLE
Camera plays haunting sounds to non-chaplains.

### ISSUE THREAD

**Issue by someanonredditor** [ParadiseSS13/Paradise#11007]
**Problem Description**:
The ordinary camera (not the camera obscura) plays creepy sounds when you are not the chaplain. I think this effect was intended for the camera obscura.

Offending code is here:
https://github.com/ParadiseSS13/Paradise/blob/3fee0f2019bb83f27aca6f44c0f0770187a7ed59/code/modules/paperwork/photography.dm#L328

**What did you expect to happen**: 
Camera would take a photo without demonic noises as it is just a camera.

**What happened instead**:
I took a photo and every couple photos some creepy noise would play.

**Why is this bad/What are the consequences:**
Ordinary cameras don't open auditory gates to hell.

**Steps to reproduce the problem**:
Get ordinary camera, take a few pictures.

**Comment by taukausanake** [comment]
I would imagine that check to be made in the spooky camera object rather than the normal camera. I get the spooky is inheriting the afterattack() proc but this makes it so the normal camera makes spooks too
