### ISSUE TITLE
You can use a guest ID to unlock personal lockers

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11001]
**Problem Description**:
If you make a guest ID which has the same name as an ID used to lock a personal locker, it can lock and unlock that personal locker.

**What did you expect to happen**: 
Using a guest ID on a personal locker should fail

**What happened instead**:
The locker opened

**Why is this bad/What are the consequences:**
You shouldn't be able to bypass personal lockers so easily

**Steps to reproduce the problem**:
1. Lock a personal locker using an ID
2. Make guest ID that shares a name with the ID used to lock it
3. Open locker with guest ID

**When did the problem start happening**:
Likely forever

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

Personal locker code is trash and should be rewritten

**Comment by MINIMAN10000** [comment]
Hah and here someone was recommending I copy personal locker in order to identify what personal is for an actual ID.

Yes person locker looks at the name of an ID to determine ownership. An alternative more secure ( and probably doesn't work with a guest pass ) would be to take all card ownership data ( it's named something like that as a function ) and just md5 hash it to obfuscate the info

**Comment by Citinited** [comment]
Or just assign the card directly to a variable, and check it's that exact card

**Comment by MINIMAN10000** [comment]
Then you have the problem that even though someone creates a duplicate card through HOP or Secret Agent they would not have "That exact card" which is unexpected behavior that causes HOP and Secret Agent to be unable to create a duplicate card when they should be able to.

**Comment by Citinited** [comment]
Well if that happens they can just get a new locker

**Comment by datlo** [comment]
honestly the fact a personal locker can be opened by a fake ID using the same name seems like a feature to me
but it shouldnt be doable by using a guest pass ID
