### ISSUE TITLE
I found yet another issue with anti-drop implants. 

### ISSUE THREAD

**Issue by Anoonki** [ParadiseSS13/Paradise#11005]
**Problem Description**:
Krav maga, when used on someone with nodrop implants activated results in duped items that are still flagged with nodrop. 

**What did you expect to happen**: 
Not to be able to disarm the guy with a nodrop implant

**What happened instead**:
I disarmed the guy with a nodrop implant, got his stun baton, he disarmed me back, and we got yet another stun baton, resulting in 3 stun batons that couldn't be dropped. 

**Why is this bad/What are the consequences:**
Allows people to clone the HECK out of the same item, makes a lot of cursed clones of that item that make peoples' hands permanently stuck. 

**Steps to reproduce the problem**:
Make a dummy, give said dummy an anti-drop implant, give them any item and turn the anti-drop implant on. 
Make a second dummy, give it krav maga, have it disarm the first dummy using Krav's special disarm. 
You now have two linked items that are horribly glitchy. 

**When did the problem start happening**:
7/3/19, 19:00.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Regular round, round type probably not relevant. 
#7300 probably related. 
I don't know if this is a dupe, but this seems specific enough that it might not have been discovered.
Just go ahead and close this if this IS a dupe.

**Comment by Fox-McCloud** [comment]
I question if this is really cloning the object so much as an object having multiple `loc`s.

Why dream maker allows this is beyond me.

**Comment by Anoonki** [comment]
Realistically that's what's happening, but all of the batons are functional, and even admin tools that force you to drop all of your items can't remove them from your hands (Or so I'm lead to believe, an admin had tried, and had to actually delete and replace me via player panel, they couldn't varedit the batons I was holding.)

This is really awful, but at the end of the day not a huge issue I guess because only one guy can have krav without admin shenanigans, and I don't think either of the traitor martial arts have the item snatch on disarm.
