### ISSUE TITLE
Surplus crates give unusable hijack-only items

### ISSUE THREAD

**Issue by Edefff** [ParadiseSS13/Paradise#11002]
**Problem Description**:
Surplus crates give hijack-only items like power sinks and syndicate bombs that aren't usable in most cases for regular traitors, wasting a lot of TC on their purchase.

**What did you expect to happen**: 
Every item in the surplus crates should at least be usable as per server rules
 
**What happened instead**:
I got a power sink and a syndicate bomb that that ate up 21TC of my surplus crate

**Why is this bad/What are the consequences:**
Wastes a lot of TC; causes confusion for newer players that might think it's ok to use these items; and just silly in general to give items that it's against the rules to use.

**Steps to reproduce the problem**:
Buy a surplus crate and get unlucky

**Comment by Citinited** [comment]
Uh... syndicate bombs and powersinks aren't hijack only

**Comment by Pckables** [comment]
I wouldn't consider a Powersink Hijack-only, but stuff like maxcap bombs and atmos grenades are definitely way too big for your average traitor.

**Comment by Edefff** [comment]
@Citinited  I've asked admins several times whether I could use those items and every time the answer has been no. Bundles also come with power sinks.

**Comment by taukausanake** [comment]
> syndicate bombs and powersinks aren't hijack only

Those are most certainly hijack only. You are not expected to destroy the station unless you have hijack. You're more like an undercover agent or bribed NT employee to minorly irritate NT for the Syndicate

**Comment by Pennwick** [comment]
Neither of those are Hijack only items. The only Hijack restricted items are His Grace and the Singularity/Tesla beacon. Maybe a case could be made for the bomb to be on the list but the idea of the power sink being hijack only is absurd. It's disruptive sure but as harmless as it gets.

**Comment by Citinited** [comment]
/shrug

Fair enough

**Comment by taukausanake** [comment]
Oh wait I somehow got powersink mixed up with singulo beacon. Wow I'm dumb.
Yeah powersink is fine to make the station scramble a bit but could also result in destruction if used to or allows for the engine to release itself. Not a problem if the engine is made self containing but eh, not your fault by that point

**Comment by davidchan13** [comment]
I don't know what admin told you these items are hijack only, but they are not.

Power sink can be used by any antagonist so long as they are not intentionally setting it to release the engine.

Bombs can be used by traitors so long as they are not used in main hallways. There is certainly discouragement of using them to bomb for lulz (such as blowing up the kitchen or dorms) but using them to kill a target or prevent revival methods are valid, though in almost every case a TTV is going to be more efficient and quicker.

**Comment by Henri215** [comment]
The syndicate bomb has been made into a hijack only item since the making of this issue by PR #16273.
After checking the code on all items that can be included in the surplus, i can say that no hijack items are among them.
If you think that a certain item shouldn't be included then feel free to make a suggestion.
