### ISSUE TITLE
blob zombified ssd people still keep their ssd miasma

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11004]
**Problem Description**:
If a ssd person dies and becomes a blob zombie he keeps the miasma

**What did you expect to happen**: 
He losing the miasma once zombified

**What happened instead**:
He kept the miasma

**Why is this bad/What are the consequences:**
People will hesitate to kill these zombies due to the ssd signs. BWOINK

**Steps to reproduce the problem**:
1. Go ssd
2. Die
3. Become a blob zombie

**When did the problem start happening**:
Since the miasma was added.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Blob round eh

**Comment by taukausanake** [comment]
Are you talking about the miasma in #10853? That hasn't been merged yet and I haven't heard miasma until that PR was made

**Comment by Kyep** [comment]
It is probably testmerged.

**Comment by farie82** [comment]
Correct it's test merged. I'll move the issue to the PR
