### ISSUE TITLE
Karma gain is off by default

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11015]
**Problem Description**:
What is the problem?
Karma gain is off by default, you have to enable it, as if it was not a standard feature until now, but something experimental, voluntary.
It should be on by default, so whoever doesn't want karma can disable the gain

**Comment by AffectedArc07** [comment]
Attempt to reproduce, used default settings, was able to award karma to someone by default. That means that this isn't reproducible easily


# Fuck

**Comment by Deelite34** [comment]
Weird, first time I clicked the option, karma gain was enabled for me.. I'll add, that every round start, it shows that karma gain is disabled, even though it is enabled for me

**Comment by Couls** [comment]
Hey, sorry about this happening. I think i've found the issue and it has to do with the order in which it updates your karma preferences. I'm compiling now and will make a hotfix very soon hopefully

**Comment by Shadow-Quill** [comment]
@Fox-McCloud Reportedly fixed.
