### ISSUE TITLE
Location hint inconsistent when multiple objects exist

### ISSUE THREAD

**Issue by Tayyyyyyy** [ParadiseSS13/Paradise#11010]
**Problem Description**:
Objective items aren't always unique, which results in bad hints. For example, there are CE boots in the admin room so it will hint that the CE boots are in the admin room

**What did you expect to happen**: 
The location hint should prefer locations on the station z level first

**Why is this bad/What are the consequences:**
It's a little bad for immersion and can be confusing for new players

**Steps to reproduce the problem**:
Get a theft objective for the CE boots

**When did the problem start happening**:
After #9205

**Comment by taukausanake** [comment]
I thought it was limited to z-level 1? That sounds like one of the first if not last thing that would have been noticed before the PR was merged

**Comment by SkeletalElite** [comment]
> I thought it was limited to z-level 1? That sounds like one of the first if not last thing that would have been noticed before the PR was merged

I know this comment is a bit late, but, that doesnt seem to be the case, as I got an objective telling me to get mag boots and that they were in the admin room.

**Comment by KasparoVy** [comment]
Holy shit hahah that's funny

Good luck

**Comment by craftxbox** [comment]
Example of this happening: https://crxb.tk/ycoq1c.png
Only seems to happen in autotraitor or admin-made traitors
