### ISSUE TITLE
Patients with no heart can have heart attacks.

### ISSUE THREAD

**Issue by ungauss** [ParadiseSS13/Paradise#11013]
**Problem Description**:
A patient was having a heart attack, so I attempted to correct it with a defibrillator. I got the message: "Resuscitation failed - Failed to pick up any heart electrical activity.", which is what you get when they have no heart. They were alive, just revived through strange reagent. The heart attack continued after they died again and were revived - same issue.

**What did you expect to happen**: 
For no heart attack to be able to happen without a heart, or for me to be able to fix a heart attack with a defibrillator regardless.

**What happened instead**:
Patient kept dying from an impossible heart attack I couldn't fix.

**Why is this bad/What are the consequences:**
A patient's body can be permanently bugged, requiring cloning or brain transplant.

**Steps to reproduce the problem**:
Not sure, I've only seen it once. There doesn't seem to be any logic in the code preventing people without hearts from getting heart attacks though.

**When did the problem start happening**:
Since cardiac arrest was added probably.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
They went through gateway to fight the blob in an event, died and got really messed up (broken bones, etc), then were revived with SR. They were a bright green furry thing (maybe Vulpakin? Not sure).

**Comment by Fox-McCloud** [comment]
If you don't have a heart, your'e going to continuously take damage; you don't get to pull a cheesy move of letting someone die, removing their hearts, reviving them, then sending them on their way. Likewise if the heart is dead.

You're going to have to give them a replacement heart if you want to fix this problem. This is working as intended. Dead, missing, or cardiac arrest all incur the same damage.

**Comment by someanonredditor** [comment]
How can you have a heart attack without a heart? They were alive with no heart, having a heart attack.

**Comment by datlo** [comment]
flash news : people need a heart to live more at 5

srsly tho it could be more explicit that the issue isnt a heart attack but a heart straight up missing. but yes this is working as intended.

**Comment by Pennwick** [comment]
Yeah. Its kind of an issue of the status description. I think the only ways it would happen is heartworms or a badly botched surgery.
