### ISSUE TITLE
mice setting off ai upload turrets

### ISSUE THREAD

**Issue by vxnillx** [ParadiseSS13/Paradise#11027]
**Problem Description**:
AI Upload turrets firing at mice and vent crawl pets

**What did you expect to happen**: 
They shouldnt fire at mouse and other pets because It doesnt do any damage to them and theres no point of making them do that if mice cant even do anything 

**What happened instead**:
All turrets fired on me as a mouse when it does absolutely no damage to me 

**Why is this bad/What are the consequences:**
it raises concerns for every person on the birdge that somehow a bad guy got in there or someone ventcrawled in.

**Steps to reproduce the problem**:
Be mouse. Ventcrawl into AI upload. Profit.

**When did the problem start happening**:
It has been probably happening for awhile. I just dont think it should happen,

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

**Comment by taukausanake** [comment]
I can only imagine an AI going "EEEEEEEE MOUSE!" and then a disabler/laser show commencing

**Comment by Shadow-Quill** [comment]
Not really a bug. Turrets set to "Target Non-Synthetics" would target mice as they aren't synthetics.
