### ISSUE TITLE
Cryoing with certain unique items removes them from the game

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11021]
**Problem Description**:
Items such as the ambulance key, the sec pod key and the janitors key for example are unique and won't be saved once somebody cryos with them. The NAD pinpointer is one of them as well for instance but there are plenty more

**What did you expect to happen**: 
Them to be stored in the cryo storage

**What happened instead**:
Sucked into the cryostorage to be burned with the bodies

**Why is this bad/What are the consequences:**
Makes certain tools and objects unusable if somebody cryos with them. Especially if said person just SSD's.

**Steps to reproduce the problem**:
Cryo with an item that won't be saved

Easy fix:
Add the items to the cryo check list

**Comment by Mitchs98** [comment]
According to the code they SHOULD be preserved/stored, unless I'm looking at it all wrong or a fix has since been merged :thinking:
