### ISSUE TITLE
IPCs dont have necks

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#11025]
**Problem Description**:
IPCs dont have necks (The shellguard one atleast)
![image](https://user-images.githubusercontent.com/25063394/54218874-4908ef80-44e6-11e9-90f5-48601dd4fbc8.png)

**What did you expect to happen**: 
The neck to be connected

**What happened instead**:
I dont have a neck

**Why is this bad/What are the consequences:**
***muh immersion***

**Steps to reproduce the problem**:
Set head as shellguard
Look to the side

**When did the problem start happening**:
Unknown

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

**Comment by Ty-Omaha** [comment]
![ipcneck](https://user-images.githubusercontent.com/20497797/54219406-d25bfa00-44c5-11e9-8ba4-023ada97449d.png)

isn't that a neck?

**Comment by AffectedArc07** [comment]
You cannot tell me this is intentional with how far out the jumpsuit sticks. This looks jarring as all fuck

**Comment by KasparoVy** [comment]
They just got a pencilneck. This head is meant to fit into the shell guard torso which has a slim neck at the back like that. Check out the other shell guard heads for ref, maybe even with the full shell guard body

**Comment by Spacemanspark** [comment]
My IPCs all have necks

**Comment by AffectedArc07** [comment]
Not an issue
