### ISSUE TITLE
[META] The air cycling airlocks don't have a cycling system

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11034]
**Problem Description**:
The airlocks to space are just normal airlocks. No cycling system

**What did you expect to happen**: 
To have a cycling system there

**What happened instead**:
Walk out into space on accident a lot

**Why is this bad/What are the consequences:**
Makes EVAing way harder and people will die a lot more while exploring.

**Steps to reproduce the problem**:
Go to space

**When did the problem start happening**:
Today (13-3-2019) on Metastation

**Comment by Citinited** [comment]
It's always been a design feature on meta that none of the airlocks are cycling ones.

If maintainers would rather see that changed then I can just fix this in #10942
