### ISSUE TITLE
[META] CE got no access to AI Sat.

### ISSUE THREAD

**Issue by Calecute** [ParadiseSS13/Paradise#11038]
**Problem Description**:
Ce has no access to AI sat, more specifically to the door after the teleporter

**What did you expect to happen**: 
Ce having access to ai sat

**Why is this bad/What are the consequences:**
Ce should have access to AI sat to take care of tcomms and sat power and atmos, he has access to tcomms and sat maint inside the sat, but can't get pass the teleporter. This prevents a promptly response by CE to tcomms and Ai sat problems.

**Steps to reproduce the problem**:
Spawn as CE, try to go AI sat

**When did the problem start happening**:
Possibly a problem with meta since the beggining, not sure, just saw it today, but had never played CE on meta before

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It was in Meta, nothing else i can add i think

**Comment by Shadow-Quill** [comment]
@Crazylemon64 Not a bug.
