### ISSUE TITLE
[META] brig timers don't work

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11032]
**Problem Description**:
The brig cell timers don't work. They start and say it in the chat but they don't actually work. Cell doesn't get closed nor does the status get set. And after the time expired it doesn't say anything.

**What did you expect to happen**: 
It to work

**What happened instead**:
Only a chat message. Nothing more

**Why is this bad/What are the consequences:**
Makes security rather unplayable

**Steps to reproduce the problem**:
Use the brig cell timers

**When did the problem start happening**:
Today (13-3-2019) when testing meta station

**Comment by Couls** [comment]
Can't reproduce. Seems fine on my test server

**Comment by Shadow-Quill** [comment]
@Crazylemon64 Couldn't reproduce on latest master.
