### ISSUE TITLE
[META] Crashing near science

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11037]
**Problem Description**:
Me and others have crashed multiple times now when approaching science on metastation

**What did you expect to happen**: 
Not to crash

**What happened instead**:
CRASH

**Why is this bad/What are the consequences:**
It crashes you and takes you out of the game for 30+ seconds (yes ads that don't load)

**Steps to reproduce the problem**:
Walk near science. It happend to me in the hallway to escape

**Comment by farie82** [comment]
Update. About 10+ people just crashed almost at the same spot. Just a bit below medbay.
![image](https://user-images.githubusercontent.com/15887760/54323684-a9895100-45fa-11e9-9f92-3481ea8a39cd.png)
in the middle of that picture. Or somewhere there.

**Comment by Abydos2** [comment]
Kinda shortened the area around here when I was watching the area and saw 4 people go SSD both going down and up from it.
![Capture](https://user-images.githubusercontent.com/15679133/54324286-0da91680-45f5-11e9-9ebc-22633170a4c9.PNG)

**Comment by Calecute** [comment]
I did crash going thorugh that corridor, didn't think much of it at the time.

**Comment by Spacemanspark** [comment]
Same.

**Comment by KasparoVy** [comment]
I witnessed myself and 5 other dudes crash in that corridor last night.

**Comment by MrMagolor** [comment]
I didn't suffer from this myself: but I saw a good few golems that I made crash while dragging them along the corridor.

**Comment by taukausanake** [comment]
Perhaps it's a different BYOND version being used by the clients? Might want to double check that

**Comment by MrMagolor** [comment]
> Perhaps it's a different BYOND version being used by the clients? Might want to double check that

I imagine if their BYOND version was incompatible with this server in any way, they'd probably have issues on the Cyberiad, too.
