### ISSUE TITLE
[META] No shotgun rounds in the armory except rubber

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11033]
**Problem Description**:
No other rounds are in the armory except rubber rounds

**What did you expect to happen**: 
Buckshot and slugs to be there

**What happened instead**:
Only rubber shots are there

**Why is this bad/What are the consequences:**
Makes shotguns only useful for non lethal when an emergency appears. 

**Steps to reproduce the problem**:
Watch the armory

**When did the problem start happening**:
Today (13-3-2019) on Metastation

**Comment by Couls** [comment]
#11035

**Comment by farie82** [comment]
You can add the following to your PR to make it auto resolve this issue:
fixes: #11033
