### ISSUE TITLE
[META] ERT has no ERT shuttle

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11036]
**Problem Description**:
ERT have to use the ferry shuttle on CC instead of having their own shuttle with a camera system to track ERT members and rechargers for their guns.

**What did you expect to happen**: 
A special shuttle to be available for ERT

**What happened instead**:
They had to take a ferry.

**Why is this bad/What are the consequences:**
Doesn't happen often but the shuttle is quite handy to watch your men as commander. Or just to recharge.

It's on the meta station map

**Comment by MrMagolor** [comment]
You know, how infeasible would it be to just have the same CC for all maps?

**Comment by taukausanake** [comment]
About as infeasible it is for different stations to have the same escapes, escape shuttles, maybe the cargo shuttle, you know little things. I rather they stay different though. Different flavors and all

**Comment by AffectedArc07** [comment]
Fixed since standardisation.
