### ISSUE TITLE
Revs don't spawn on Metastation (possibly other entities)

### ISSUE THREAD

**Issue by Drobe50** [ParadiseSS13/Paradise#11031]
**Problem Description**:
What is the problem?

Revenant fails to spawn on Metastation.

**What did you expect to happen**: 
Why do you think this is an issue?

Being asked as a ghost "Do you want to play as a Revenant?" Then having one not spawn is really a bummer.

**What happened instead**:
How is what happened different from what you expected?

The Rev did not spawn.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Major event failing to spawn after asking ghosts if they want to play as it removes the fun out of it.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Play Metastation>Rev event>Doesen't spawn.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

Since we've been playing on Metastation this week.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Gamemode is vampires.
Map: Metastation.

This may just be a once in a life time bug, considering rev is a rare event it's probably not common.

**Comment by Couls** [comment]
Seems like an issue with events in general on metastation

**Comment by hal9000PR** [comment]
meta was remapped.
