### ISSUE TITLE
Wall mounted thingys seem to be haunted.

### ISSUE THREAD

**Issue by Sotrennel** [ParadiseSS13/Paradise#1104]
Sometimes when you make an explosion, such as using an IED, the station intercom and fire alarm and probably other things flip off the walls or to neighbouring walls.

**Comment by Fox-McCloud** [comment]
Explosions throw things around now; this is intentional.

**Comment by Sotrennel** [comment]
It just feels strange intercoms and fire alarms being flipped over the space, and still working.

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/1306
