### ISSUE TITLE
[META] Lack of surgery tools, robotics locker, mechanical first aid kits in robotics, copier access

### ISSUE THREAD

**Issue by Pennwick** [ParadiseSS13/Paradise#11040]
**Problem Description**:
Robtics is lacking a lot of the basics that they need to function.

**What did you expect to happen**: 
Robotics locker, both for duffle bags, and oil cans
Mechanical First Aid kits, not 100% neccisary but they're on box station (Also contains oil cans and analyzer which is otherwise limited to 1
A full set of surgery tools, while SoP reccomends going to medbay to get implants installed it indicates that Robotics is fine
A copier somewhere where Robotics can get to it, God damn I need a copier for all these cyborgization contracts

**What happened instead**:
No robotics locker, had to find a dufflebag elsewhere
No mechanical first aid kits, hand to order them from cargo just to have an oil can
Only hemostat, retractor, scalpel, and bonesaw for surgeries (No space cleaner, *scream)
Closest copier was probably in the library
(No access to the RnD room to talk to scientists and beg for basics, had to walk up to their window like a peasant)

**Why is this bad/What are the consequences:**
Robotics struggles to do their job unless they leave their office to go fetch materials.

**Comment by Couls** [comment]
#11035
