### ISSUE TITLE
Chitinous Mass Freezes Game on Examine

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#11054]
**Problem**:
Changelings (or admins) covered/wearing chitinous mass (such as the organic shield or organic space suit) will cause players who try to examine them to lag, freezing their game for 1-2 seconds.

**Why is this bad/What are the consequences:**
Could cause a player to freeze during a critical moment in combat, especially since chitinous mass is a very combat oriented item.

**Steps to reproduce the problem**:
Have a changeling use the organic shield or space suit, or an admin cover a body part in chitinous mass, and examine them. Watch your game freeze for a short period of time each examine.

**When did the problem start happening**:
Has been an issue for a very long time, but nobody's really addressed it since it's not a critical issue.

**Possibly related stuff**:
Its cause may be tied to the Chitinous Mass not having a proper sprite in examine, as shown in the image.
![ChitinousMassLag](https://user-images.githubusercontent.com/35735195/54484292-8d272780-4839-11e9-8b32-d213c0730032.PNG)

**Comment by Pennwick** [comment]
That image looks like a very tiny spritesheet. Is it somehow possibly outputting the whole thing each time?

**Comment by taukausanake** [comment]
I think I can confirm that `icons\obj\clothing\suits.dmi` is missing a sprite while the `mob` dmi does have its sprite. `obj` file doesn't have a null or empty sprite like other files do so it might be pushing the whole sheet or what it can push from it. Then again I can't say I know anything.

Easiest solution is to just copy/paste the mob sprite into the obj sprite. Not like the lingspacesuit has a special sprite

**Comment by MrMagolor** [comment]
Could it be possible to "hide" the chitinous masses on examine, similar to golem shells/face/hands/etc.? They're pretty visual obvious already regardless, and part of the changeling's body.
