### ISSUE TITLE
Secret Files stored in bibles don't count

### ISSUE THREAD

**Issue by OsmiumAnchor** [ParadiseSS13/Paradise#11053]
**Problem Description**:
What is the problem? 

Traitor secret files stored in bibles don't count as on your person for end-round win statistics, even if you're actively holding the aforementioned bible or the bible is in your backpack.

**What did you expect to happen**: 
Why do you think this is an issue? 

Because traitors that accomplished their mission in this manner aren't recognized as having completed their secret files objective in end-round stats.

**What happened instead**:
How is what happened different from what you expected? 

I expected to receive credit for completing my traitor secret files objective regardless that the objective items were stored in a bible on my person, but I did not.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue? 

Because if this problem extends to more traitor objective items than simply traitor secret files, potentially more difficult objectives that were completed may not receive recognition... And, I'm not totally sure if anything is actually gained from completing said objectives other than the opportunity to be mischievous within reason during the round, but I doubt that those rewards are being dished out if there are any and this bug extends to more than secret files.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue. 

I acquired both files very early in the round, and stored them in a bible the entire round. For the majority of the round, the bible was in a backpack on my character at all times. I never removed the files from the bible, and I _know_ I had the files on my person, in the bible, when the round ended because I was staring at them the whole escape shuttle flight, while idly opening and closing the bible out of both boredom and to half-assedly assure myself that it wasn't just a graphical bug.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Obviously it was a Traitor round, and the only unusual thing that I noticed was a directional glass pane briefly phased through my character, and trapped me in space.

**Comment by farie82** [comment]
Looking at the code this should work. A storage object. Which the bible is will put it's contents in a list and the game will check said list for the items. Did you maybe have an empty document folder? Some traitors use that trick.

**Comment by MrMagolor** [comment]
bibles share contents with other bibles right? That might affect it
