### ISSUE TITLE
Tiles disappearing

### ISSUE THREAD

**Issue by HopeLessSou1** [ParadiseSS13/Paradise#11063]
**Problem Description**:
What is the problem?
Tiles disappearing
**What did you expect to happen**: 
Why do you think this is an issue?
The item floor tiles to stay
**What happened instead**:
How is what happened different from what you expected?
The floor tile item disappeared once I placed a floor tile on a floor
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It leaves the floor exposed of pipes and wires
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Umm...
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
When I started replacing tiles to take off the space lube but I relize their was less tiles
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
This is insanely vague. Could you clarify?

**Comment by Mitchs98** [comment]
I believe I know what they're referring to. At times when replacing tiles the tile sprite can outright disappear/turn invisible, leaving anything underneath it exposed and it looking like there's no tile there when there, in-fact, is a tile there.

**Comment by SpessX** [comment]
Maybe it's similar to the state a few tiles in the abandoned mining station are in, when you clear the xeno weeds. They are invisible but you actually have to crowbar them up and place them back to fix the visibility.

**Comment by moxian** [comment]
This should be fixed by #11063 ; i don't remember anyone complaining about this lately.

**Comment by AffectedArc07** [comment]
Cannot be reproduced. Feel free to re-open this at a later date if you can reliably reproduce this issue
