### ISSUE TITLE
Changelings who transform while they have armblades or shields out can't retract them.

### ISSUE THREAD

**Issue by Odieman1** [ParadiseSS13/Paradise#11068]
**Problem Description**:
As a changeling, if you robust some nerd and decide to transform into him while you have your armblade and shield out, you will still have it out on your sprite but it won't be in your hands UI.  You can't retract them as it only says "[Name] retracts their armblade!" or something to that extent ad infinitum.

**What did you expect to happen**: 
Upon transforming, I still have my armblade out and can retract it normally.

**What happened instead**:
In the UI my armblade is gone, however it is still there on my sprite and still does damage.  If I attempt to retract it, I cannot.

**Why is this bad/What are the consequences:**
A bit hard to be inconspicuous with an arm blade and shield you can't retract.  Security may question you. 

**Steps to reproduce the problem**:
1. Be Changeling
2. Get Armblade and Shield, and have at least one DNA different from your own.
3. Make sure Armblade and shield are currenty enabled, visible in your hands UI, etc and then transform.
4. Attempt to retract Armblade or shield.  You cannot.

**When did the problem start happening**:
I was a changeling yesterday and Breenland helped me after I got miffed about with my armblade shenanigans.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:  I had a hardsuit on, my Chameleon was active, and I was transforming to a new race.  Something that also happened but I cannot recreate is that I was stuck and couldn't move.  I was surrounded by walls to my east and south, and was facing south.  I was under a shower.  Specifically, I was in the maints shower directly south of Cargo, absorbing a guy.

**Comment by Jazz23** [comment]
Just tested it, bug only happens if you switch races while having the armblade or shield out. This means any switch, not just changeling (stable mutagen for example).

**Comment by Emanthealmighty** [comment]
I suggest to just make it so you cannot transform while you are "wearing" any of the changeling items.

**Comment by farie82** [comment]
it only happens when the cling changes species. It's a problem in the specie transformation code.

**Comment by farie82** [comment]
Also due to the cling items having DROPDEL as a flag. Meaning they get deleted once unequiped. This is what the specie transform code does.
