### ISSUE TITLE
Explosive Holopara creates a null object upon picking up.

### ISSUE THREAD

**Issue by Odieman1** [ParadiseSS13/Paradise#11067]
**Problem Description**:
When picking up an item that your guardian set to explode, it will say you disarmed it.  This is all good and well, however, you instead pick up a null object, "/obj/item/guardian_bomb" which you have to drop on the ground.  From the players perspective, it appears nothing is in your hand.

**What did you expect to happen**: 
Either the item you are picking up turns you into spaghetti and meatballs or you just pick it up and it says you disarmed it.

**What happened instead**:
You neither pick it up nor explode.  Rather, you pick up an invisible object with no indication that you have anything in your hand.  Only when you try and use that hand to pick up other objects is it apparent something is wrong.

**Why is this bad/What are the consequences:**
Invisible objects are generally frowned upon and can lead to quite a bit of havoc if a chameleon projector is used on them.  Also, if you don't know to drop it, you might try and grab something without knowing you have something already in your hands.

**Steps to reproduce the problem**:
Step 1: Get an explosive Holoparasite
Step 2: Have the parasite make an object explosive, example:  A pen.
Step 3: Try and pick up that pen.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: Traitor generally, as it's related to an uplink item.  Probably works with Wizard guardians as well.

**Comment by Kyep** [comment]
Verified, happened the first time I tried it.
Invisible object left in-hand was a /obj/item/guardian_bomb
