### ISSUE TITLE
Radiation Storm Cures Roundstart Disabilities

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#11062]
**Problem Description**:
What is the problem?
Roundstart disabilities are wiped out if you are exposed to the radiation storm event (green STALKER blowout).

**What did you expect to happen**: 
Why do you think this is an issue?
Roundstart disabilities are supposed to be resistant to changing.

**What happened instead**:
How is what happened different from what you expected?
I expected my roundstart disabilities to persist, but to get mega messed up by the radstorm ones.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Inconsistent genetic behaviour.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I run the blind, colourblind and nearsighted roundstart disabilities on a character and got mega crunk. I was so crunk, in fact, that I couldn't walk into maintenance and ended up radiated. My roundstart disabilities were promptly cured and I got tourettes.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Not sure

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
![para ss13 radiation cures all disabilities](https://user-images.githubusercontent.com/12377767/54500814-aeab1080-4918-11e9-9b1e-3f3bcfd433f5.PNG)

**Comment by Fox-McCloud** [comment]
`Roundstart disabilities are supposed to be resistant to changing.`

Unfortunately, this isn't the case.

We would *like* this to be the case, but it's definitely not. The genetic system is a bit of a mess, right now; until it's converted over to the traits sytem, we don't really have a good way of preventing these mutations from being adde/dremoved by mutadone or any other source that scrambles your genes.

When traits are added, this will be possible and will have my full support (and it'll be easier to do), but right now? Unfortunatelyyyy this is completely "as intended".

**Comment by KasparoVy** [comment]
No worries, sounds like I misunderstood how it works rn. Thanks for explaining!
