### ISSUE TITLE
Slime person with chief engineer hardsuit is not hot-resistant.

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11083]
**Problem Description**:
What is the problem?
Slime person with chief engineer hardsuit is not hot-resistant. CE hardsuit protects from Fire and hot.
**What did you expect to happen**: 
Why do you think this is an issue?
CE hardsuit should always protect from pressure/temperature
**What happened instead**:
How is what happened different from what you expected?
Slime person without breathing mask, with CE hardsuit got hot, while on fire, in hot place.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be slime person, with CE hardsuit on
2. Slime people do not breathe air, so do not need gas tanks as well.
3. Go into plasma fire, you will get hot.
4. Since CE hardsuit protects from pressure, it means you are separated from outside pressure. That means temperature should not matter as well. But due to not having gas mask on, nor internals, you are apparently not separated from outside temperature, meaning you will get deadly hot if on fire inside plasma fire, but high pressure won't hurt you. Meaning you are separated from outside, and not separated from outside at once.

Anything else you can tell us.
I'm positive it happends when you are slime person + without gas mask and/or internals
https://imgur.com/a/f3PyWfC

**Comment by Pennwick** [comment]
There are several problems in that screenshot. Somehow there is negative pressure and CO2. Not sure whats causing that. However as for the burn damage thats likely intentional, firesuits only protect so high. 35,000 for suits and 30,000 for helmets. The temp where you're standing is 40,000. No I remember some is lost when converting to K I think but not 5000 degrees worth.

**Comment by Deelite34** [comment]
I did more tests, my theory that gas mask + oxy tank have influence on that is false. The bug is same as #10934 . Chief engineer hardsuit fails to protect from high temperature (Like 50 000+ C), if you are NOT on fire. If you are on fire, it can hold much higher temperature than that without problem.

**Comment by KasparoVy** [comment]
Flame on.
