### ISSUE TITLE
Swarmers Lack Intent UI Indicator

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#11087]
**Problem**:
Swarmers do not have an indicator in their UI showing their intent (Which would be more akin to Disable and Shock instead of Help and Harm respectively).

**Why is this bad/What are the consequences:**
Someone who accidentally hits the 4 button will no longer be able to shoot disablers and have no idea why.

**Steps to reproduce the problem**:
Hit 1 to shoot disablers, or hit 4 to switch to melee-only. Notice a lack of indicator to this.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I had no idea Swarmers even had intents until someone pointed it out today. Noticed I couldn't shoot after switching to "harm" intent, and realized the issue.

**Comment by MrMagolor** [comment]
Swarmers aren't meant to attack things anyways- perhaps their harm attack could be removed, like non-sentience event corgis?
