### ISSUE TITLE
pAI Millitary PDA visibility

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#11113]
**Problem Description**:
a pAI using digital messenger is able to see millitary PDA on the list

**What did you expect to happen**: 
pAIs not to be able to see military PDAs on the list

**What happened instead**:
![image](https://user-images.githubusercontent.com/589709/54882289-11446500-4e61-11e9-9eb6-6eca3ef9c745.png)

**Why is this bad/What are the consequences:**
It allows pAIs to easily metagame the gamemode or allow others to do so if they dont know what military PDA means

**Steps to reproduce the problem**:
Get downloaded as a pAI, Imprinted, Downloaded unversal translator, crew manifest and digital messenger, Opened messenger and turned receiver on

**Comment by Spacemanspark** [comment]
Doesn't the military PDA spawn every round, though?

Not that I'm saying this shouldn't be fixed; that's clearly unintentional and pretty bad lmao.

**Comment by Joonasm** [comment]
It might actually. i think I've seen it on every round i got digital
messenger on

**Comment by Kyep** [comment]
@AffectedArc07 please link this to the TGUI issue so its fixed by whoever does TGUI PAI code.

**Comment by AffectedArc07** [comment]
Should be fixed.
