### ISSUE TITLE
You can't change suit sensors, or take off items off others, while on vehicle(janicart, paramedic-cart, etc)

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11115]
**Problem Description**:
What is the problem?
You can't change other person's suit sensors, or take off items, while on vehicle (janicart, paramedic-cart, etc)
**What did you expect to happen**: 
Why do you think this is an issue?
It's annoying, that you cannot maximize sensors of nerds as paramedic, while on paramedics cart.

**What happened instead**:
How is what happened different from what you expected?
To be able to at least change sensors of others, while on vehicle.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Get on janicart, or similiar
2. Try to change sensors of other person, menu where you change sensors does not pop up when you click button.

**Comment by Pennwick** [comment]
This is likely due to you being buckled to the cart. You similarly can't do these things when sitting down on the escape shuttle. Not sure how much of this is intended.

**Comment by farie82** [comment]
Got changed somewhere down the line. Can't find the specific PR quickly
