### ISSUE TITLE
Given items to people who are resting will stay in their hands as if they have antidrop

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11116]
**Problem Description**:
When you give an item to somebody who is resting it'll stay in his hands. Just like as if the person has antidrop. He can fully use said item and throw it.

**What did you expect to happen**: 
The item falling on the ground.

**What happened instead**:
The item stayed in the persons hand and he was able to use it.

**Why is this bad/What are the consequences:**
It's a bug in the current rest system. Since you will have to drop everything if you rest unless you have antidrop.

**Steps to reproduce the problem**:
1. Rest on the ground. Unbuckled
2. Have somebody give you something
3. Profit

**Comment by KasparoVy** [comment]
https://github.com/ParadiseSS13/Paradise/issues/10024

**Comment by farie82** [comment]
aye it's a dupe. Closing it
