### ISSUE TITLE
Bombs blowing up in toxins range do not increase toxins tech level in R&D

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11118]
**Problem Description**:
What is the problem?
Bombs blowing up in toxins range do not increase toxins tech level in R&D.
**What did you expect to happen**: 
Why do you think this is an issue?
Can't raise toxins level

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Blow up bomb in toxins test range.
2. Doppler logs it.
3. Toxins level is still 1 in R&D.

**Comment by datlo** [comment]
Working as intended. As the machine says after a succesful test, you need to swipe a tech disk and save the data onto it.

**Comment by dovydas12345** [comment]
It is working as intended. Need to swipe the tech disk as said and the upload on the database.

**Comment by Deelite34** [comment]
My bad, gonna close it
