### ISSUE TITLE
Viewing the bridge console station cameras gives xray vision

### ISSUE THREAD

**Issue by procdrone** [ParadiseSS13/Paradise#11124]
**Problem Description**:
When using the bridge security camera console, viewing any camera grants total xray vision. (you literally see everything, no line of sight. Lighting apply still). Only for the duration of the camera viewing. Closing camera view restores normal vision.

**When did the problem start happening**:
It happened right now, as of 25/03/2019 - 02:00 CET

Along with the game admin Kyet, the issue was confirmed with another player, so it is not a client side problem. 

![a1](https://user-images.githubusercontent.com/46283583/54888850-42448a00-4ea1-11e9-9993-3b230121693c.png)
![a2](https://user-images.githubusercontent.com/46283583/54888851-42dd2080-4ea1-11e9-995f-4a6ceeaf1a2c.jpg)

**Comment by farie82** [comment]
I noticed this as well. It is not set in stone which camera's have xray vision though.

**Comment by taukausanake** [comment]
Does this happen with other camera consoles? Should check that next. I'd imagine all cameras on the station should not be upgraded and just standard

**Comment by moxian** [comment]
Camera consoles were completely reworked in #13750

**Comment by AffectedArc07** [comment]
No longer relevant due to cam console overhaul
