### ISSUE TITLE
Dust Event Does Nothing

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#11133]
**Problem Description**:
The event /datum/event/dust doesn't do anything.

**What did you expect to happen**: 
It should spawn a meteor wave.

**What happened instead**:
It doesn't do anything, nothing at all.

**Why is this bad/What are the consequences:**
If you wish you wish to send a meteor wave, instead of a meaty ore wave or meteor shower, you can't.

**Steps to reproduce the problem**:
1. Debug tab
2. Trigger event dust
3. Nothing happens.

**When did the problem start happening**:
A couple weeks ago, though I didn't think about making a report at the time. Yay!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: The event /datum/event/dust/meaty works just fine.

**Comment by Ty-Omaha** [comment]
Thats not the meteor wave event:

https://github.com/ParadiseSS13/Paradise/blob/6fe83a698757f023d26171355fff906d95ee764b/code/modules/events/meteors.dm

https://github.com/ParadiseSS13/Paradise/blob/2ee08523408798f47c6586b12dc79b836da65b0c/code/modules/events/event_container.dm#L194

**Comment by Breenland** [comment]
Yes, the meteor wave and meteor shower are different events.

**Comment by Ty-Omaha** [comment]
Meteor wave:
https://github.com/ParadiseSS13/Paradise/blob/2ee08523408798f47c6586b12dc79b836da65b0c/code/modules/events/event_container.dm#L194

Meteor shower:
https://github.com/ParadiseSS13/Paradise/blob/2ee08523408798f47c6586b12dc79b836da65b0c/code/modules/events/event_container.dm#L154
