### ISSUE TITLE
Plasma Golem Explosions Don't Log Initiator

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#11135]
**Problem Description**:
When a plasma golem detonates, there is no log showing the name or key of the person who detonated.

**What did you expect to happen**: 
When the explosion goes off, for the person who caused it's name to appear.

**What happened instead**:
A log simply showing an explosion and it's size appeared.

**Why is this bad/What are the consequences:**
It makes it difficult to track griefing and other issues.

**Steps to reproduce the problem**:
1. Be admin
2. Watch plasma golem explode
3. No log on their name.
![image](https://user-images.githubusercontent.com/38596550/54973173-c0b23200-4f5c-11e9-9027-0c258d906be3.png)

**When did the problem start happening**:
I imagine it started when mineral golems were introduced.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing I can think of.

**Comment by ingles98** [comment]
Oh shit i did this yesterday... It wasn't on purpose i swear. To redeem myself i will attempt to fix that..

**Comment by Crazylemon64** [comment]
(This fix wasn't cited correctly, so it didn't auto-close with the PR merging)
