### ISSUE TITLE
Auto processing of cloners

### ISSUE THREAD

**Issue by Jazz23** [ParadiseSS13/Paradise#11145]
**Problem Description**:
If you have multiple clone pods, auto processing will clone a person in all the pods, leaving a bunch of catatonic bodies and one good one. Only when you scan them via auto-processing, however.

**What did you expect to happen**: 
Auto-processing to only initiate one clone pod per person.

**What happened instead**:
All available pods were initiated with the same person

**Why is this bad/What are the consequences:**
Auto-processing is useless (with respect to auto-scanning) with multiple clone pods

**Steps to reproduce the problem**:
Build multiple clone pods, upgrade the DNA modifier and enable auto processing, take a sentient dead body and put it in the DNA scanner with auto-processing enabled.

**When did the problem start happening**:
Probably infinity.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It sucked when there's a fat line for cloning and all the pods get used up.

**Comment by KasparoVy** [comment]
Would be nice if it would just evaluate all the pods to see which one has the most biomass (or is selected) and then choose that

**Comment by Fox-McCloud** [comment]
sounds like the lack of a `break` function...

**Comment by KasparoVy** [comment]
tfw `break` is `broke`
