### ISSUE TITLE
Crash Tiles at the Armory

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#11142]
**Problem Description**:
The crashing hallway tiles on metastation seem to now happen on the Cyberiad, though in the brig armory area. The small spot with the vendor and the secure armory itself. Once again random where exactly it happens. Happened on two separate rounds, does not always happen where it did previously or even at all.

**What did you expect to happen**: 
I expected to not crash when entering the armory.

**What happened instead**:
Myself and 3-4 other officers crashed when entering the armory.

**Why is this bad/What are the consequences:**
Number of reasons. Being chased by an antag, trying to gear up for a threat, generally existing to go recharge your gear.

**Steps to reproduce the problem**:
1. Be sec.
2. Go into the armory room.
3. Walk around on the tiles until you possibly crash.

**When did the problem start happening**:
About a few days ago is when I noticed it when I started playing security again.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing relevant.

**Comment by Sikroth** [comment]
I've crashed a few times in the past days while circling around security through space as well, if that helps. From memory I think it was around the area between the armory and the sec bathroom.

**Comment by Brutus-Amungus** [comment]
Yeah seems the equipment area in front with the vendor and the armory itself have been causing more crashes then usual when ive played sec.

**Comment by Ty-Omaha** [comment]
maybe its the range targets with the bullet overlays after being shot since canvas' used to do that too

**Comment by Spacemanspark** [comment]
It never did that before tho
