### ISSUE TITLE
Spontaneous Combustion virus symptom not working correctly

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#11152]
**Problem Description**:
Spontaneous Combustion is supposed to add fire stacks and ignite you on activation, giving a big red message along with it. Currently it instead **removes** said stacks. You can find out this by examining yourself right after a message and noticing you're now randomly soaked.

**What did you expect to happen**: 
Burning and pain.

**What happened instead**:
You scream every now and then but it has literally no other effect.

**Why is this bad/What are the consequences:**
A symptom that's supposed to be dangerous and lethal is now harmless.

**Steps to reproduce the problem**:
- Get spontaneous combustion symptom
- Inject self and wait for stage 4 or 5.
- Examine self before and after activation message.

**When did the problem start happening**:
I have no idea. This happened just now, during the last shift of the newcrit testmerge I believe. It might possibly be related?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

Virus was stealthy enough to not show up in health analyzer, if that's relevant at all.

Picture of examine tests, with the negative burnstacks as mentioned:

![spntcmb](https://user-images.githubusercontent.com/7857084/55126986-f4cd5480-510e-11e9-8e9c-d98c01723cca.png)

**Comment by farie82** [comment]
Might be due to the virus having negative stats for the SC. It relies on a few stats which affect the stack size. Unsure if these can be negative. Ill check in a bit

**Comment by farie82** [comment]
Aye it's certainly possible that you get negative stacks. Math for it is (at stage 5):
sqrt(20 + stagespeed * 3) - sqrt(16 + stealth)
So if the stage speed is negative and the stealth is high it will deal negative stacks instead.

**Comment by Sikroth** [comment]
So it's because of the virus stats. That makes some sense, but it's probably unintended behaviour anyway. Considering it's spontaneous *combustion*, some sort of actual burning-related effect should maybe happen even with non optimized stats.
