### ISSUE TITLE
Infinite Chemicals in Cyborg beakers

### ISSUE THREAD

**Issue by Dinarzad** [ParadiseSS13/Paradise#1116]
Sooo.
Was a skeleton crew shift, nobody in medical except for myself as a Med-borg, a Geneticist and a Virologist.

I loaded up my beaker with both the starting beakers of Cryox to prepare the Cryo tubes like you usually do.
Only. I was able to load BOTH tubes with the same beaker that I had filled up (55 units of cryoxadone total), and still have a beaker full of cryox left over.

Basically duplicating the same cryox beaker into both machines and still having it in my inventory.

**Comment by veganzombeh** [comment]
It's not quite infinite chemicals. You can add the beaker to the machine, but it won't leave your inventory, so you can add the beaker to multiple machines.

**Comment by Taaketa** [comment]
I experienced this yesterday. But I left my beaker in the tablet dispensor in chemistry.

Ironically my beaker could be remotely filled. However, putting it back into storage means you cannot recall it again.

**Comment by Fox-McCloud** [comment]
Sounds like a potential qdel() problem.

**Comment by Alex6511** [comment]
Make it use power from the borg, now  the borg synthesizes the beaker with materials in it. Its a feature!

**Comment by Fox-McCloud** [comment]
should be fixed by various beaker/cryo fixes.
