### ISSUE TITLE
When multiple telecoms are built, if one goes down telecoms goes down

### ISSUE THREAD

**Issue by MINIMAN10000** [ParadiseSS13/Paradise#11167]
**Problem Description**:
If multiple telecoms are setup, if one telecoms goes down all of telecoms stops working
**What did you expect to happen**: 
If multiple telecoms are setup, if one telecoms goes down the other one will continue working

**What happened instead**:
I expected high availability where if one system went down the telecomms would stay online because another is still functioning.

**Why is this bad/What are the consequences:**
The behavior is unexpected, the consequence is building a secondary telecoms just increases the chances of telecoms instead of providing redundancy like one would expect.

**Steps to reproduce the problem**:
A bit nebulous here because I was just winging it but I was following the chart here https://nanotrasen.se/wiki/images/8/83/SpessChart.png for linking instructions. Receiver to bus, bus to processor, processor to bus, bus to server, server to broadcaster. The following machine circuits were build into their respective things. Subspace receiver, bus mainframe, processor unit, channel server, and Subspace broadcaster, telecommunications monitor, telecommunications server monitor, telecommunications traffic control

**When did the problem start happening**:
Unknown

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The telecoms related equipment was running out of power thus resulting in telecoms going down. The room was built within medical maintenance just south of medical where blood and a paramedic uniform can be found. All computers were still powered.

**Comment by AffectedArc07** [comment]
I dont quite understand your wording here. Youre saying if one machine dies they all die? Or the ionspheric event knocks out all tcomms?

See if you can explain this a little better

**Comment by MINIMAN10000** [comment]
When power to my telecomms room in the station went down, telecomms went down. There were no ionspheric events.

**Comment by MINIMAN10000** [comment]
Hmm after running on my own server it looks like the moderate event "Communication blackout" has no messages and appears to be what happened. So it appears this isn't a bug just an event without any identification.
