### ISSUE TITLE
Medical Cyborgs Defibrilator paddles dont restart hearts in cardic arrest

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#11178]
**Problem Description**:
A Medical Cyborg is unable to restart a heart in cardic arrest

**What did you expect to happen**: 
The heart to be restarted

**What happened instead**:
the message "patient not in valid state" was shown

**Why is this bad/What are the consequences:**
This means that if a patient goes into cardic arrest the only thing a medical cyborg can do is wait for them to die and then defib them afterwards barring crew intervention

**Steps to reproduce the problem**:
Have a patient go into cardiac arrest. Try to use medical cyborgs defib

**Comment by Fox-McCloud** [comment]
In the meantime, stop using full-sized defibs for just cardiac arrest; use the handheld defib. It's what it's meant for.

This does still need to be fixed, of course.

**Comment by Joonasm** [comment]
I should probably make a new issue but i don't think they have handheld defibs. i couldn't find one when i played medical Borg,

**Comment by Joonasm** [comment]
Yeah, i just checked on local server, They dont get handheld ones #11191

**Comment by Contrabang** [comment]
Cannot reproduce, likely fixed sometime before #19987

**Comment by Contrabang** [comment]
see above
