### ISSUE TITLE
You dont hear sounds if youre inside containers/vehicles

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#11174]
**Problem Description**:
You dont hear sound if in a container or a vehicle (Mecha/spacepod)

**What did you expect to happen**: 
Be able to hear

**What happened instead**:
You couldn't hear anything happening

**Why is this bad/What are the consequences:**
Lockers, spacepods, mechs, etc, are not fully soundproof

**Steps to reproduce the problem**:
Enter a container or vehicle
Try and make any form of sound
Scream

**When did the problem start happening**:
Merge of https://github.com/ParadiseSS13/Paradise/pull/11173

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

**Comment by KasparoVy** [comment]
Busted by #11173 cuz if you view variables a dude who's in a closet their z level is different, therefore closeted people meet the new condition for the sound optimization

**Comment by AffectedArc07** [comment]
No longer an issue
