### ISSUE TITLE
Tcomms console breaks sometimes, when you try to add colour to regex word.

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11183]
**Problem Description**:
What is the problem?
Tcomms console breaks sometimes, when you try to add colour to regex word.
Example:
"Green" into `<font color="#009933">Green</font>` broke the console, meaning you can't click any button, because nothing happends. Had to ahelp to reset it.
**What did you expect to happen**: 
Why do you think this is an issue?
Can't do nice tcomms thing, without console breaking, requiring admin reseting it

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Can't make nicer tcomm scripts, sometimes they break, sometimes not.

**Comment by Shadow-Quill** [comment]
@Fox-McCloud This could be closed as well.

**Comment by Deelite34** [comment]
Tcomms is gone, rip tcomms
