### ISSUE TITLE
Medical Cyborgs dont have handheld defibs

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#11191]
**Problem Description**:
Medical cyborgs dont have access to handheld defibs

**What did you expect to happen**: 
To be able to equip one from my inventory

**What happened instead**:
Only full sized paddles were present in the inventory

**Why is this bad/What are the consequences:**
It means cyborgs are unable to heal people with heart attacks

**Steps to reproduce the problem**:
Spawn in as medical cyborg

![image](https://user-images.githubusercontent.com/589709/55288252-574b7c80-53bd-11e9-82ea-5517df3a16c5.png)

**Comment by Fox-McCloud** [comment]
Yep, they're supposed to have one.
