### ISSUE TITLE
Slip/Stun Delay

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#11201]
**Problem Description**:
People who get slipped or stun are going down 1-2 seconds after the event.

**What did you expect to happen**: 
When someone gets tased or slipped, for them to go down immediately.

**What happened instead**:
After the event, they go down a short time later.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
1. Find target
2. Stun or slip them
3. Watch them go down late

**When did the problem start happening**:
I noticed it today, but I'm not sure how long it has been happening.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
No other information.

**Comment by KasparoVy** [comment]
Reminds me of old Goon, heheheh.

Too bad we don't have full-speed sideways spacemen like they did.

**Comment by Breenland** [comment]
Personally, I'm a fan of the delayed taser reaction, though the slipping needs to be fixed.

**Comment by Mitchs98** [comment]
Makes no sense for any of them to be delayed really. But hey that's just me.

**Comment by Kyep** [comment]
This is a big deal.
I can run 7 tiles past the tile I slip on before I actually fall over. That's long enough for me to run into another room.

**Comment by Breenland** [comment]
Adding to this, this affects all stuns. Glares from vampires, and even simply RESTING.

**Comment by KasparoVy** [comment]
I wonder what PR is even related to this? Possibly https://github.com/ParadiseSS13/Paradise/pull/11188?

**Comment by Mitchs98** [comment]
I put up a revert PR #11206 It should probably fix it.

**Comment by Fox-McCloud** [comment]
HOnkkkkkkkk.

April Fool'sssss.

**Comment by Mitchs98** [comment]
Henkity Honkity.

**Comment by KasparoVy** [comment]
That was a deep ass meme

well done @Fox-McCloud hahaha

It felt like goon for a while minus the sideways full-speed movement

yorpyorpyorp taught me so
