### ISSUE TITLE
deathnettle cannot be picked up

### ISSUE THREAD

**Issue by EvadableMoxie** [ParadiseSS13/Paradise#11208]
**Problem Description**:
Deathnettle cannot be picked up, even with gloves

**What did you expect to happen**: 
For it to be picked up when clicked on.

**What happened instead**:
Nothing happens

**Why is this bad/What are the consequences:**
It's basically unusable.

**Steps to reproduce the problem**:
Try to pick up deathnettle

**When did the problem start happening**:
Reported today.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Using a plant bag directly on the deathnettle places it into the bag.  However trying to take it out of the bag immediately drops it, even with gloves on.  It's basically acting like you don't have gloves even when you do, although with gloves you won't take damage.

**Comment by farie82** [comment]
Probably broken by me due to the no gifting when resting pr. Shouldnt be to hard to fix.

**Comment by Fox-McCloud** [comment]
I wonder what else this broke.

**Comment by farie82** [comment]
It shouldn't have broken to much. There only where a few items that actually used onpickup
