### ISSUE TITLE
Telecomms bbcode in regex can be slightly abused

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11219]
**Problem Description**:
What is the problem?
You can project things, that don't enchance telecomms, like [logo] or [hr] from pen code onto telecomms regex.

**What did you expect to happen**: 
Why do you think this is an issue?
To not be able to project nanotrasen logo into radio.
**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Can be abused to meme on everyone, with something that can't exist IC, since you can't hear images, or horizontal lines

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Use regex in telecomms, to change words into things you would not expect, using pen code, like [logo] or [hr] or [br]
Example:
[hr] [center][i][u][logo][br]Everyone and AI are a comdom[/u][/i][br]Signed by:[i]Centcomm second officer Steve[/i][/center][hr]

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
![bug](https://user-images.githubusercontent.com/35972878/55485750-5881e100-562b-11e9-8bf9-cb72360ad3af.png)

**Comment by Fox-McCloud** [comment]
Remove tcomms scripting when?

**Comment by MINIMAN10000** [comment]
Uhh... so like now we need some sort of [] whitelist or something for telecomms?

**Comment by Shadow-Quill** [comment]
@Fox-McCloud I think this can be closed.
