### ISSUE TITLE
AI that takes control of mech using AI control beacon cannot use its weapons freely

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11233]
**Problem Description**:
What is the problem?
AI that takes control of mech using AI control beacon cannot use its weapons freely. You can shoot at windows, items, wall mounts, players, but not by clicking on walls or floors, like you do 70% of times as mech user.
**What did you expect to happen**: 
Why do you think this is an issue?
To raise weapon, middle mouse button click like instructions say, and shoot in direction of criminal scum, by clicking on floor/wall.
**What happened instead**:
How is what happened different from what you expected?
You have to click exactly on target human/item to shoot it. This is not melee combat, you are mech, you mostly shoot at general direction of targets by clicking on floor/wall, not by having to spam middle click in hope you will hit the mobile human target.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Cannot shoot by clicking at floor/wall, mech ai, no matter if paladin, or shunted rogue has much harder time using it

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be AI
2. left click on mech with ai control beacon, and take control of it(or shunt into it as rogue, but didnt test with shunting)
3. Instructions say, that lmb is for ai commands, and mmb is for shooting mech pew pews
4. Click middle mouse button at floor/wall, in order to shoot at direction of enemy. Nothing happens, you have to directly middle click on target to shoot him.

**Comment by farie82** [comment]
Fixed in #12968
