### ISSUE TITLE
Sec HUD glasses lose ability to change arrest status

### ISSUE THREAD

**Issue by Brutus-Amungus** [ParadiseSS13/Paradise#11238]
**Problem Description**:
Seemingly at random or later on in shifts, the Sec HUDs lose their ability to change the arrest status of individuals. Everything that includes [none, wanted, released, paroled, etc] simply cant be selected, let alone the menu opened. 

**What did you expect to happen**: 
I expected to be able to change the wanted status of players.

**What happened instead**:
I cannot open the warrant menu when selecting a player status option.

**Why is this bad/What are the consequences:**
Sec will be unable to set criminals to arrest unless they use a records console.

**Steps to reproduce the problem**:
Early shift seems to allow for use of the warrant menu, but later on it stops at random. Usually after someone has been put into a cell for some time.

**When did the problem start happening**:
Seems to be a recent problem, within the month at most. It's also been noted that this could have started after the RND sec HUDS update, where they could be used to change status if they were crafted. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Dosent seem to be connected to the equipment, and re-logging does not solve the issue.

**Comment by Markolie** [comment]
This is probably caused by a runtime somewhere. Next time this happens, could you ask an admin to check the runtime log right as you click on the arrest status option?

**Comment by Brutus-Amungus** [comment]
Ill be sure to contact and admin next time it happens
