### ISSUE TITLE
Banana tumour unable to be removed from a cluwne's head/brain

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#11241]
**Problem Description**:
What is the problem?
If you target the head and select organ manipulation on a cluwne, you get the option to remove (when you're at that stage) the banana tumour from their head, but when you select the option, the menu just closes and nothing happens.
**What did you expect to happen**: 
To remove the banana tumour
Why do you think this is an issue?
I couldn't remove the tumour when I wanted to
**What happened instead**:
Menu closed, no tumour removed
How is what happened different from what you expected?
See above
**Why is this bad/What are the consequences:**
It hinders medical science
Why do you think this is an important issue?
Medical science is important
**Steps to reproduce the problem**:
Get a cluwne, perform surgery until you're at the stage where you can remove organs, then try to do it
The most important section. Review everything you did leading up to causing the issue.

**When did the problem start happening**:
I think it's always been there, I dunno, I started the experiments today
If your report is about something that used to work but no longer does, when was the last time you remember it working? / 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: In medbay, practicing my malpractice fantasies, before the malpractice insurance ran out. Also it was a cluwne so they deserved it.
Anything else you can tell us.
I'm sure the cluwne didn't mind

**Comment by Landerlow** [comment]
ADDENDUM: I codedived and see this is working as intended (tm) -- I would like it to be removable though.

Thoughts?

**Comment by Landerlow** [comment]
Though I understand, since it's a punishment

**Comment by Landerlow** [comment]
Actually, what if, by removing the tumour, the BRAIN IS REMOVED IN THE PROCESS, but you keep the tumour?!

**Comment by Aurorablade** [comment]
No at this point this is a feature request not a issue report

**Comment by Aurorablade** [comment]
Plus the tumor deletes itself when removed

**Comment by Aurorablade** [comment]
And as the person who coded them they are fine as is *sorry for multi comment ay work on mobile,

**Comment by Landerlow** [comment]
Yeah. Nevermind, this isn't an issue. I'll close it. or something, if I can
