### ISSUE TITLE
Windoors do not give airlock boards when disassembled

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#11248]
**Problem Description**:
Windoors do not drop the airlock boards put in them when disassembled. When the airlock board is pried out, a message is placed in the chat indicating that you pry the airlock board from the windoor, but the airlock board seems to be deleted altogether, as it isn't dropped on the floor nor placed in your hands.

**What did you expect to happen**: 
Whilst disassembling a windoor, I expect, especially receiving the message that I removed the airlock board, that it would be given back to me intact, just as it would be when disassembling an airlock.

**What happened instead**:
The airlock board seems to be deleted during the removal step.

**Why is this bad/What are the consequences:**
You cannot recycle the airlock board, need to fetch a new one (difficult if you're not an engineer/don't have access), makes things harder in general when deconstructing and reconstructing windoors.

**Steps to reproduce the problem**:
1. Have a regular windoor, either already made or constructed. Have not tested with reinforced windoors.
2. Deconstruct the windoor until you reach the point of prying out the airlock board. Continue.
3. Notice that you receive the in-chat message of prying out the board, and yet no board appears. Be without airlock board.

**When did the problem start happening**:
I noticed it several months ago, and was reminded of it about an hour ago.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
As said, I have not tested this with reinforced windoors. Boxstation.

**Comment by farie82** [comment]
Only works when you construct one yourself it seems. The prespawned one in engineering did do it's thing till I remade it myself.
