### ISSUE TITLE
Nukie Shuttle Doesn't Accommodate for New Crit

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#11258]
**Problem Description**:
The Medbay corner in the nukie shuttle is a little outdated now, and can't properly fix a team mate who has gone into critical nearby.

**Suggestion**:
Add a handheld defib and atropine syringe into the surgery duffel. This way nukies who get too injured in or near their shuttle (which happens frequently) can be patched up instead of doomed to die from cardiac failure.

**Why is this bad/What are the consequences:**
We need more nukies and less flukies.

**Other Notes**:
The Surgery Duffel may also be missing a trauma kit, but I haven't had the opportunity to double check, as it's possible another operative ended up nabbing it.

**Comment by Fox-McCloud** [comment]
A valid feature request, but a feature request none the less.
