### ISSUE TITLE
Vault Safe Issues

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11250]
**Problem Description**:
Getting multiple reports from people in round trying to hack the vault safe but never being able to.  They do not hear the correct noises as per the wiki when using a stethoscope, issue only appeared recently and does not happen every round.  Some players even could not open it when they had the codes for it.

**What did you expect to happen**: 
Prevents players from breaking into the safe unless they use a drill.

**What happened instead**:
Stethoscope appears to not work at all with the safe anymore randomly on some rounds.

**Why is this bad/What are the consequences:**
Obvious reasons - Antags cannot safe crack.

**Steps to reproduce the problem**:
It might possible be an issue with the new NanoUI for the safe which also causes the white screen windows for some people.  Try cracking the vault safe with a stethoscope, the safe will not give you the noise prompts for when to turn

**When did the problem start happening**:
I first started hearing of this issue as of 2-3 weeks ago..

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Was getting reports of this bug around the same time that people were reporting the white screen bug with nano ui windows.

**Comment by Markolie** [comment]
Are you sure you started hearing about this for the first time longer than a week ago?

**Comment by Denthamos** [comment]
@Markolie It is possible it has been an issue for longer, but seeing as how I have only been hearing complaints about it for around 2-3 weeks ago and before that I was busy for a near 3 weeks there and not able to play much 🤷‍♂️ .

No one else wanted to take the time to file a git report about it despite being asked to in game.
