### ISSUE TITLE
You can go an infinite distance from a defib with its paddles while on an ambulance.

### ISSUE THREAD

**Issue by craftxbox** [ParadiseSS13/Paradise#11256]
**Problem Description**:
You can go an infinite distance from a defib with its paddles. while on an ambulange

**What did you expect to happen**: 
the paddles to snap back when i moved 2 tiles away

**What happened instead**:
paddles stay in my inventory endlessly

**Why is this bad/What are the consequences:**
remote defibrilation from tens of tiles away

**Steps to reproduce the problem**:
get on ambulance
remove paddles from defib
walk away

**Comment by craftxbox** [comment]
Just checked, you can actually use them from such far away, trying to test on other z levels

**Comment by craftxbox** [comment]
update: its because of the ambulance, the ambulance prevents things from snapping back, but it still works off z level too

**Comment by craftxbox** [comment]
regular defibs also have this bug

**Comment by SomeSortaSquid** [comment]
Defib makes adjacency check using on_mob_move proc.
Riding does not trigger on_mob_move.

Given the fact you can't move off the vehicle and you are limited to one hand, I think using this bug would actually make paramedic's life much harder. Especially with newcrit punishing repeated defibrillations. Even if you wanted to use it to attack people, you would have to stash away the key, equip the paddles and... by that time they are probably gone.

**Comment by Spacemanspark** [comment]
Still something that should be fixed.
