### ISSUE TITLE
Wizard Stuck in Void

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11268]
**Problem Description**:
If the wizard casts blink or rod while jaunted, it seems to make them disappear into the void.

**What did you expect to happen**: 
Such spell usage should be disabled while jaunted to prevent such bluespace fuckery.

**What happened instead**:
Wizard was stunned, jaunted, then blinked/rodded and got stuck in the void.  Could not exit the void.

**Why is this bad/What are the consequences:**
...Kind of puts the wizard in a place they cannot escape from without admin intervention.

**Steps to reproduce the problem**:
Be stunned, jaunt, then blink and rod while jaunted.

**When did the problem start happening**:
Just noticed it today during a wizard round.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Wizard was in stun crit, jaunted, then blinked and rodded while jaunted.

**Comment by taukausanake** [comment]
That's what happens when you play with Bluespace I guess. Also kind of sounds like the wizard went sub-atomic

**Comment by farie82** [comment]
Similar method of reproducing:
1. Jaunt
2. Blink
3. Rod
You're now stuck as a rod till you jaunt again. The rod also doesn't dissapear
