### ISSUE TITLE
Fake revolver shoots you when you try to put it away in storage

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11262]
**Problem Description**:
The syndicate fake revolver kills you if you try to stow it away in lets say a syndicate belt

**What did you expect to happen**: 
It not to shoot my face right off

**What happened instead**:
It shot me and I died

**Why is this bad/What are the consequences:**
Doesn't make sense to shoot you when you try to put it away.

**Steps to reproduce the problem**:
Get the gun. Put it away in lets say a syndicate belt

**When did the problem start happening**:
Since it was merged

**Comment by Fox-McCloud** [comment]
Russian revolver can do this too.
