### ISSUE TITLE
His Grace Doesn't Bind

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#11274]
**Problem Description**:
His grace doesn't bind and therefore you dont get the stun immunity, the healing, or the ability to use its anti drop.

**What did you expect to happen**: 
For his grace to be an item that binds when I pick it up and I get all it's special powers.

**What happened instead**:
It's just a green toolbox that you can pickup and its anti drop action button doesn't do anything.

**Why is this bad/What are the consequences:**
20 TC hijack only chaplain only traitor item doesn't work

**Steps to reproduce the problem**:
Be hijack chaplain, buy his grace, be disappointed.

**When did the problem start happening**:
Probably when #10968 was merged

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I used an antag token to become a tot

**Comment by Mitchs98** [comment]
Can confirm this isn't always the case. A miner Unathi by the name of Eku had a His Grace last night. It very much bound to the user and gave all the above perks. Healing, stun immunity, damage buff, etc. Not sure what caused this, but, it _did_ work last night.

**Comment by SkeletalElite** [comment]
Well I had a round and I bought his grace and it put it into my hand and no matter what I did (activate, drop, pickup again) I couldn't use the action button (said I didn't know how to use this or something along those lines) and it never made the noise that it does when it binds, (that screech sound)

**Comment by SkeletalElite** [comment]
Also if a miner had it that means either an admin spawned it or it came in a crate. Maybe the bug only occurs if you actually but it in the uplink.

**Comment by Mitchs98** [comment]
Both are viable reasons. Honestly unsure. Just saying that I did in-fact see it work for someone.

:man_shrugging:

**Comment by Fox-McCloud** [comment]
You have to actually try to open the thing up before it accepts you. This was documented in the changelog. 

Please read the changelogs before posting bug reports.

**Comment by SkeletalElite** [comment]
> You have to actually try to open the thing up before it accepts you. This was documented in the changelog.
> 
> Please read the changelogs before posting bug reports.

I did open it Fox, didnt do anything

**Comment by Fox-McCloud** [comment]
So you had the toolbox in your hands and then you tried to open it with your other hand?

**Comment by SkeletalElite** [comment]
I opened it with my other hand by dragging the toolbox Sprite to myself (how I usually open toolboxes) do you have to open it by clicking instead?

**Comment by Fox-McCloud** [comment]
>I opened it with my other hand by dragging the toolbox Sprite to myself (how I usually open toolboxes) do you have to open it by clicking instead?

Yes.
