### ISSUE TITLE
Mouth Tape Bug

### ISSUE THREAD

**Issue by indijosh** [ParadiseSS13/Paradise#11272]
**Problem Description**:
What is the problem?
When your mouth is taped shut, you can rip the tape off over and over if you click it fast enough.

**What did you expect to happen**: 
Why do you think this is an issue?
You should only be able to rip the tape off your mouth once.

**What happened instead**:
How is what happened different from what you expected?
I expected to rip the tape off my mouth and have the "old duct tape" in my hand or on the floor. It does appear to work and the tape removed from my mouth, but I can click my mouth again and rip off an invisible piece of tape.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Spamming an infinite number of old duct tape.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Take a tape roll, apply it to your mouth by clicking your character. Once applied, take an empty hand and click on the "mask" slot to remove the tape. Click it repeatedly to keep ripping off tape.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
It's pretty easy to reproduce. If you have any more questions about it, though, you can find me in-game as Jeb Taylor or Byond name IndiJosh.

**Comment by Citinited** [comment]
Similar to #9743 for anyone looking to fix this
