### ISSUE TITLE
Spawned in cult constructs cannot see cultists

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11275]
**Problem Description**:
Manually spawning in cultist constructs despite having the cult faction, cannot see the cultist symbol on the HUD.  You cannot make spawned in constructs a cultist either via the traitor menu, but you can make them a traitor?  (Honestly what the shit?)

**What did you expect to happen**: 
To open the traitor panel on constructs and turn them to cultists

**What happened instead**:
Cannot make spawned in constructs via the create mob menu cultists

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
Spawn a construct, open its traitor panel.  No cult open.

**When did the problem start happening**:
Has been in for quite some time I assume.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Cult mode.

**Comment by Allfd** [comment]
Yeah, simple mobs can't be cultists from traitor panel, you have to do it manually with VV and proc calls.
