### ISSUE TITLE
Cannot *salute or *bow while buckled into something

### ISSUE THREAD

**Issue by JedDeLagged** [ParadiseSS13/Paradise#11290]
**Problem Description**:
Cannot *salute or *bow while buckled into something

**What did you expect to happen**: 
For the emote to work like the other emotes - I've tested them all, and only these two don't work while buckled. You can *flip, but not *salute!

**What happened instead**:
There is no error or message, nothing happens just like no action was performed

**Why is this bad/What are the consequences:**
How am I supposed to honor the Captain or other heads of staff when I'm sitting at the Cargo counter? Super rude.

**Steps to reproduce the problem**:
-Buckle yourself to something, chair or table
-*bow or *salute

**When did the problem start happening**:
Problem has always existed as far as I know, but I have only been doing this for about six months.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I've tested all the emotes as a human, only these two don't work. There might be others that are race specific that I've not tested.

**Comment by Ralta** [comment]
You want to show respect, but you refuse to stand and bow or salute?

The NT Rep will hear of this!

**Comment by JedDeLagged** [comment]
If this is by design, can you at least put in a message?
If there is a way to unbuckle via emote, then this would be fine, but it's super annoying typing away, then having to click to unbuckle if you want to bow or salute....

**Comment by Ralta** [comment]
It may or may not be by design, but I assume it is. Most of SS13 works that way, to be fair; typing and clicking to accomplish simple tasks.

Protip: You can create macros in the SS13 window so that you can do an emote just by pressing a certain key. For example, I have my numpad 1 mapped to *flip and have various others on other numpad keys.

**Comment by farie82** [comment]
It's due to being buckled kinda being like you've strapped yourself on the chair. Sometimes the code mistakes this as being restrained. It should be easy to fix if you find the right code for it.

**Comment by alex-gh** [comment]
Well, there is an explicit check for being buckled with this two emotes:

https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/emote.dm#L289

So it appears to be by design.

**Comment by JohnBigless** [comment]
Bit of a workaround, you can use `me "salutes.` instead of `say* salute`

**Comment by Spacemanspark** [comment]
^
