### ISSUE TITLE
PM sends to the wrong client when the previous client left

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11295]
**Problem Description**:
When a client left and you try to send a PM to him it'll send it to somebody else

**What did you expect to happen**: 
To get a message saying the person left

**What happened instead**:
You send a message to an unsuspecting player who suddenly gets bwoinked

**Why is this bad/What are the consequences:**
You can send information to other players. And it just scares them shitless.

**Steps to reproduce the problem**:
0. be online with 2 clients. Then have another join after step 2
1. Mhelp/Ahelp something
2. logout.
3. Click on the pm href in the a/mhelp.
4. See that it is send to the wrong person. Possibly the new client

**When did the problem start happening**:
Since forever

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Most likely due to how the PM's are handled. A UID is given to the client. And this one is used. It seem that the UID is reused after the client leaves.
client procs.dm line 75 - 81
```
var/client/C = locate(href_list["priv_msg"])
if(ismob(C)) 		//Old stuff can feed-in mobs instead of clients
	var/mob/M = C
	C = M.client
if(!C) // Might be a stealthmin ID, so pass it in straight
	C = href_list["priv_msg"]
cmd_admin_pm(C, null, href_list["type"])
```

admin.dm line 43-50
```
if(C && C.holder && C.holder.fakekey && !include_name)
	if(include_link)
		. += "<a href='?priv_msg=[C.findStealthKey()];type=[type]'>"
		. += "Administrator"
	else
		if(include_link && C)
			. += "<a href='?priv_msg=[C.UID()];type=[type]'>"
		. += key
```

**Comment by Ty-Omaha** [comment]
happens mainly when they leave the original mob too

**Comment by farie82** [comment]
> happens mainly when they leave the original mob too I think

That one is using the "old" system then. I did some research while fixing this singulair instance. And some of the PM code still gives a mob with the code. If you know what cases use that then I can fix those as well

**Comment by farie82** [comment]
Whoops didn't put the fix tag infront
