### ISSUE TITLE
Cannot open char prefrences / Runtime in preferences_setup

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#11309]
**Problem Description**:
As a vulp, I cannot open my character preferences.

**What did you expect to happen**: 
Char prefs window to open.

**What happened instead**:
DEBUG: Runtime in preferences_setup.dm,387: Cannot read null.sprite_sheets [view]
DEBUG: Runtime in preferences.dm,237: bad resource file [view]

**Why is this bad/What are the consequences:**
Unable to edit my character at all.

**Steps to reproduce the problem**:
1) Be vulp.
2) Use latest github (NOT live server)
3) Be using mysql database
4) Click setup / character preferences.

**When did the problem start happening**:
After https://github.com/ParadiseSS13/Paradise/issues/11301 was merged.
@KasparoVy

**Comment by KasparoVy** [comment]
Any other species or just vulpkanin?

**Comment by Kyep** [comment]
Possibly. I haven't tested other species.
Its bad enough its stopping me running the latest code on live, even if it only affects vulps.

**Comment by KasparoVy** [comment]
I think I've spotted it, might just need an extra set of brackets around the conditionals that determine which icon file to use. Finishing testing

**Comment by KasparoVy** [comment]
Can't seem to replicate it with or without the extra brackets around conditionals in 387, 394, 401. Trying a bunch of different setups with different species, characters, etc.

What version of BYOND and what undergarments are you using?
Still troubleshooting but the information might be relevant

**Comment by KasparoVy** [comment]
I can't get this to happen regardless of species or undergarment, whether the character auto-loads when I host the server/load in or whether I'm swapping between characters.

I tested by spawning in and 'respawning', trying to load in a character-- species swapping to the nines, scrambling undergarments, it's being very elusive.

**Comment by KasparoVy** [comment]
Alright, I've some code I'd like you to test @Kyep - want me to link you my branch or PR on your fork?

**Comment by Kyep** [comment]
@KasparoVy 
That appears to fix it. I'm going to close the PR on my repo, but you should re-submit that against Paradise itself.

**Comment by KasparoVy** [comment]
Perfect, thank you for testing. I appreciate the timely comms, I'll post the PR now.
