### ISSUE TITLE
Reviving a SSD person doesn't give them the SSD ZZZ interface

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#11306]
**Problem Description**:
Reviving someone who SSD doesn't give them the interface which says "ZZZ" near the SSD person.

**What did you expect to happen**: 
I expected the SSD person to have it

**What happened instead**:
It was not there

**Why is this bad/What are the consequences:**
Can cause confusion

**Steps to reproduce the problem**:
1. Get a SSD person
2. Kill them/Them being dead and leaving the round works fine too
3. Revive them while they are SSD

**When did the problem start happening**:
Since the interface was added i would like to think

**Comment by Shockpoint** [comment]
Note that this also happens if an SSD player is rejuvenated for any reason as well. (see: griefer)
