### ISSUE TITLE
Heating oil explodes chemistry

### ISSUE THREAD

**Issue by ID404-NotFound** [ParadiseSS13/Paradise#11308]
**Problem Description**:
What is the problem?
You want to make ash, heating oil, new property of oil is explosion once reaching reaction temperature for ash, explosion is large enough to set off one or both weldertanks in chemistry

**What did you expect to happen**: 
Why do you think this is an issue?
At first, didn't know the change, just expected to get ash.

**What happened instead**:
How is what happened different from what you expected?
Explosion that destroyed chemistry

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Chemistry explodes most rounds now
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Heat oil in heater

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
About a week ago? Unsure

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Paper to make ash is not infinite, oil is. Shouldn't explode so violently.

**Comment by Fox-McCloud** [comment]
This is working as intended. Use smaller batches of oil or make ash via an alternative source.
