### ISSUE TITLE
maint spawned food get ants on them while laying on something like a rack

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11302]
**Problem Description**:
Food that spawns in maint gets ants on it due to it not being spawned on tables

**What did you expect to happen**: 
Ants not to infect my maint donks

**What happened instead**:
ANTS!

**Why is this bad/What are the consequences:**
Makes maint food rather useless

**Steps to reproduce the problem**:
1. Spawn in.
2. See a donk pocket laying on something like a rack and see those ants walking around it

**When did the problem start happening**:
Since the ant PR

Issue is easily solved by making racks (and other table like things) act like tables for the ant code.

**Comment by taukausanake** [comment]
Why are individual donk pockets being spawned in Maint? One would think they'd be in a box or something. Is someone just leaving a perfectly good food thing out there?

**Comment by Fox-McCloud** [comment]
This is "working as intended". If you want donks that aren't ant infested, you're going to have to grab them quickly or get them from a safer source.
