### ISSUE TITLE
Cult Summon Locations Pulling from other Maps

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11307]
**Problem Description**:
For the cultist summoning objective which lets them only summon in specific areas, noticed that some of the locations are often locations not even on the box map we run.  An example is the fitness room which is on meta/delta but not box.

**What did you expect to happen**: 
For only locations on the map being used to be used for summoning locations.  Kind of hard to summon in an location which does not exist.

**What happened instead**:
Cultists are getting summoning locations that do not exist in the game.

**Why is this bad/What are the consequences:**
Limits or straight out prevents the cult from summoning.

**Steps to reproduce the problem**:
Its RnG for the game mode when you get the summoning.  Sometimes you get all box locations, sometimes you get locations not on box.

**When did the problem start happening**:
Most likely when the cult location summoning was added.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Cult round.

**Comment by Twinmold93** [comment]
My guess is the objective is either checking for all areas, or more likely a list of whitelisted areas.
