### ISSUE TITLE
Crashing when trying to host.

### ISSUE THREAD

**Issue by GoonOnMoon** [ParadiseSS13/Paradise#1131]
Basically this: http://nanotrasen.se/phpBB3/viewtopic.php?f=48&t=4214&p=26387&hilit=byond+crashing#p26387

Even after deleting the config and dbconfig nothing works. Not sure how to go about fixing this myself.

**Comment by CrAzYPiLoT-SS13** [comment]
I had this too, it fixed itself after a got redownload into a separate
folder and than removing the config and dbconfig.
