### ISSUE TITLE
Vampire Glare isn't Logged

### ISSUE THREAD

**Issue by Sihsse** [ParadiseSS13/Paradise#11321]
**Problem Description**:
When vampires glare there isn't an attack log recording it.

**What did you expect to happen**: 
An attack log to be recorded for when the vampire initiates a glare.

**What happened instead**:
No log recorded, unable to confirm if an individual was glared unless I physically see it.

**Why is this bad/What are the consequences:**
When contacting individuals regarding interaction with vampire antagonists we can only go on the word of the individual and hopefully have a truthful antagonist otherwise there is no way we can verify the action happen.

**Steps to reproduce the problem**:
Be vampire, glare, cry when you check and see an empty attack log.

**When did the problem start happening**:
Noticed as of 04/18/19

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Game mode was vampire. Attempt was done utilizing game panel and traitor panel tools.

**Comment by Markolie** [comment]
I can’t believe such a glaring issue has been around for so long 😎.

**Comment by Shockpoint** [comment]
@Markolie That is the worst pun I've ever seen with my own two eyes.
