### ISSUE TITLE
Cultist talk hear-able in Main Menu

### ISSUE THREAD

**Issue by Wolfsyndrome** [ParadiseSS13/Paradise#11346]
**Problem Description**:
When my last round started but I didn't join in, I found that I could hear the Cult talking to eachother. Refer to the image below for detailed meaning.

**What did you expect to happen**: 
/

**What happened instead**:
/

**Why is this bad/What are the consequences:**
Could be used/abused by people joining after round start/later into the round to valid-hunt/whatever. 

**Steps to reproduce the problem**:
Couldn't say, it just sorta happened. 

**When did the problem start happening**:
I only noticed it just now, but it might be a recurring problem? No idea. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
/ 

Anything else you can tell us.

Refer to image for detail. The vote caused the OOC-channel to get enabled and disabled a few times, but the round basically started right after the vote was closed, and that's when the first Cult messages started showing up.  
![dreamseeker_2019-04-21_12-14-06](https://user-images.githubusercontent.com/23321184/56468617-2516c300-642f-11e9-93cf-ca743b2770ad.png)

**Comment by Ty-Omaha** [comment]
https://github.com/ParadiseSS13/Paradise/blob/f4357d92946fa68da9395d700300db0b69131019/code/game/gamemodes/cult/cult_comms.dm#L45

lobby players might count as dead

**Comment by taukausanake** [comment]
Pretty sure they do count as dead. They certainly aren't alive
