### ISSUE TITLE
Xeno devoured nested victims still nested after regurgitation.

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#11352]
**Problem**:
If a Xenomorph nests someone, devours them, then regurgitates them somewhere else, the regurgitated will still act as if stuck in a nest, complete with struggle prompts, despite not being on a nest anymore.

**What did you expect to happen**: 
For victims to be un-nested when devoured, or to not be able to devour nested people.

**Why is this bad/What are the consequences:**
It's funky.
I havent gotten to test it thoroughly, but it might cause issues with others ability to free them or nesting multiple in a single nest.

**Steps to reproduce the problem**:
Drag someone into a xeno nest, devour them, move somewhere else, regurgitate. They will still act as if nested.

**When did the problem start happening**:
Probably forever. I doubt this was an often noticed bug.

**Comment by taukausanake** [comment]
I doubt this is strictly xenos too. I bet you can replicate this with any buckled mob if moved into some other container. Not sure of any others off the top of my head besides xenos
