### ISSUE TITLE
Stable Mutagen from Strange Plants doesn't cause transformation.

### ISSUE THREAD

**Issue by AdvnetureDrake** [ParadiseSS13/Paradise#11366]
**Problem Description**:
Stable Mutagen from Strange Plants doesn't have the normal transformation effect when mixed with blood.

**What did you expect to happen**: 
Stable Mutagen, when mixed with blood, should transform the person injected into a copy of the person the blood comes from.

**What happened instead**:
The Stable Mutagen from the Strange Plant caused burn and toxin damage, but no other effects happened.

**Why is this bad/What are the consequences:**
All chemicals from strange plants should work as intended, as they may be useful to station crew or antagonists.

**Steps to reproduce the problem**:
Take a Strange Plant with the Stable Mutagen trait. Grind it, and then mix the resulting stable mutagen at a ratio of about five units of blood per ten units of stable mutagen. Inject into a organic species with genes (such as a monkey). The monkey will take radiation damage, but will not transform.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Discovered it today while playing botany. A hacked vendor strange seed came with the stable mutagen trait. I tried grinding the fruit and mixing the stable mutagen with blood, but when injected, it didn't cause any transformation.

**Comment by Couls** [comment]
I think you were using UNSTABLE mutagen not stable as I don’t recall any plants providing stable mutagen

**Comment by farie82** [comment]
The plants stable mutagen is no different from normal smutagen. I think that what Couls said happened.

**Comment by AdvnetureDrake** [comment]
No, I am 100% sure the plant chem was labeled as Stable Mutagen. I even took a sample of it to science, and they too said it was Stable Mutagen.
