### ISSUE TITLE
IRCs dont start properly

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#11379]
**Problem Description**:
IRCs dont start properly after being constructed

**What did you expect to happen**: 
I expected the IRC to start as soon as I put the bent in

**What happened instead**:
I had to hit it with a wrench to damage it, and update the health to make it work.

**Why is this bad/What are the consequences:**
 It made me feel like a TF2 engineer

**Steps to reproduce the problem**:
Make IRC
Put brain in IRC
Realise it didnt wake up
Hit with wrench
~~Sentry~~ **IRC** going up

**When did the problem start happening**:
Probably when IRCs were added

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

**Comment by taukausanake** [comment]
> It made me feel like a TF2 engineer

I fail to see this as a consequence. It should be a feature if anything for all borgs

**Comment by Spacemanspark** [comment]
This actually does effect borgs too, although only after they've been destroyed and repaired.

**Comment by Fox-McCloud** [comment]
RIP sentry IPCs.

You will be missed.
