### ISSUE TITLE
Round time broken

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#11388]
**Problem Description**:
ROUND TIME STARTS AT 23 HOURS
further testing shows that this might be an issue with world.time or the worldtime2text proc
**What did you expect to happen**: 
ACCURATE ROUND TIME

**What happened instead**:
INACCURATE ROUND TIME

**Why is this bad/What are the consequences:**
IT LOOKS BAD

**Steps to reproduce the problem**:
Host locally, compile code, launch, ROUND TIME IS WRONG

**When did the problem start happening**:
SOMETIME AFTER APRIL 8TH

images of issue as requested: 
![image](https://user-images.githubusercontent.com/30060146/56841815-129cef00-685e-11e9-9a7e-e70598b05f47.png)
![image](https://user-images.githubusercontent.com/30060146/56842486-8e4d6a80-6863-11e9-9a66-db856c1bbeba.png)
![image](https://user-images.githubusercontent.com/30060146/56842534-0ae04900-6864-11e9-8d67-e2cd2303028d.png) (issue is not present in check_antagonists proc because it doesn't use world.time or worldtime2text proc to check)

**Comment by Mitchs98** [comment]
Related to this. Round Time is currently ticking by at the tick rate. It's updating as fast as the in game time used to, whilst the Station Time is updating as fast as the Round Time should.

Boxen is also pulling the inaccurate round time due to this.
