### ISSUE TITLE
Photocopiers can get negative toner

### ISSUE THREAD

**Issue by craftxbox** [ParadiseSS13/Paradise#11383]
**Problem Description**:
photocopiers can get negative toner

**What did you expect to happen**: 
to cap at 0 displaying the no toner error

**What happened instead**:
went negative and stopped working

**Why is this bad/What are the consequences:**
it.. has negative toner.

**Steps to reproduce the problem**:
optional: fill photocopier with toner
1: load paper into photocopier
2: spam click on photocopy
3: enjoy

**Comment by Twinmold93** [comment]
So, I'm guessing that with the mass clicking, you and stacking the copying before it adjusts toner used, has a small delay, then uses the toner, when the check for toner is before the delay.

**Comment by Sirryan2002** [comment]
This is because the `copy()` `photocopy()` and `bundlecopy()` parent procs that the fax machine calls deduct toner as part of their normal operation.
