### ISSUE TITLE
Fireaxe sprite bug - Wielded fireaxe being put onto back

### ISSUE THREAD

**Issue by Stutternov** [ParadiseSS13/Paradise#11382]
**Problem Description**:
When placing a firearm (wielded) onto your back it does not appear as a sprite as it normally would. Such as putting it into your backpack slot without wielding it. The "Off-hand" icon appears in your hand but you can simply drop it.

**What did you expect to happen**: 
I expected it to look as the normal fireaxe sprite being put onto your back looks.

**What happened instead**:
The fireaxe sprite does not show up. Only upon examination it will say it is on your back "(wielded)"

**Why is this bad/What are the consequences:**
You can essentially glitch the sprite to make it appear concealed unless someone examines you.

**Steps to reproduce the problem**:
Wield a fireaxe in both hands, place it into your backpack slot, drop the 'off-hand' item.

**When did the problem start happening**:
I'm assuming this has existed for awhile but been a small thing. It is the first time I noticed it. Reporting this right after round end.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Only thing that /may/ make a difference is I was wearing an armor piece. Doubt this effected it though.

Images attached. 1- Description of character doing it. 2- Lack of sprite, front. 3- Lack of sprite, back. 4- Proper sprite, front. 5- Proper sprite, back.
![Text Description](https://user-images.githubusercontent.com/47883419/56776936-dce40180-679c-11e9-8487-27789b85ab24.png)
![Lack of sprite - front](https://user-images.githubusercontent.com/47883419/56776945-e7060000-679c-11e9-85db-3589197b9553.png)
![Lack of sprite - back](https://user-images.githubusercontent.com/47883419/56776961-fa18d000-679c-11e9-9c59-04ea5ccdf9f8.png)
![Proper sprite - front](https://user-images.githubusercontent.com/47883419/56776967-fd13c080-679c-11e9-9823-4de1a6faf4ff.png)
![Proper sprite - back](https://user-images.githubusercontent.com/47883419/56776969-ff761a80-679c-11e9-8403-bbe3b33d2bd6.png)

**Comment by taukausanake** [comment]
You mean to say two-handed items haven't been handled properly when being put into inventory slots? _That's awful_

**Comment by Citinited** [comment]
There's another bug floating round with two-handed stuff not unequipping properly that's sort of related, but I'll make a separate issue for that.

**Comment by Sirryan2002** [comment]
this was fixed
