### ISSUE TITLE
Observer HUD buttons inconsistent

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11385]
**Problem Description**:
The behaviour of the new observer HUD buttons added by #11300 is inconsistent with how other buttons work. They cannot be moved and are at the bottom middle of the screen instead of at the top left, they also cannot be hidden/collapsed with the arrow like usual.
EDIT: Also just noticed they don't have hover text like other buttons, either.
The buttons are also (as far as I can tell) of slightly different size than usual. See picture:

![Capture](https://user-images.githubusercontent.com/32099540/56802878-8240b900-6821-11e9-9221-71d6fba45e30.PNG)

**What did you expect to happen**: 
To be able to move the button like other buttons, to move them out of the way and to hide them.

**What happened instead**:
They didn't move.

**Why is this bad/What are the consequences:**
Unable to customize UI or hide them if you don't need them. They take up a lot of space in the middle of the screen rather than being out of the way in the upper left.

**Steps to reproduce the problem**:
Join as observer, try to drag and drop buttons, notice you can't.

**When did the problem start happening**:
When  #11300  was merged.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

**Comment by davidchan13** [comment]
Objects in your top left are spells, abilities or item functions. These can be moved and hidden by clicking the arrow.

The Ghost HUD is an actual HUD, like the Vampire, Changling, Xeno and Blob. These buttons are static almost on purpose so they can't be changed and lost. You can hide these buttons by turning HUDs off (F12)

**Comment by craftxbox** [comment]
NAB, as explained above observer hud is a hud, disable it with f12
