### ISSUE TITLE
Picking up a two-handed object while resting makes the thing "wielded" and leaves you with an offhand grab

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11394]
Not much to say on this except it's not really gamebreaking, you can drop the grab but it won't let you hold both the twohanded thing and another item (as far as I can tell anyway)

**Steps to reproduce**
1. Rest
2. Click on something that requires two hands e.g. potted plant
3. See that it puts an offhand grab in your offhand, and the object is classed as wielded

![image](https://user-images.githubusercontent.com/18459142/56855149-12722180-693a-11e9-8106-e4fca53c7aeb.png)

**Comment by Sirryan2002** [comment]
No longer an issue due to crawling PR
