### ISSUE TITLE
gravgen apc/sme problem

### ISSUE THREAD

**Issue by realtaac** [ParadiseSS13/Paradise#11401]
**Problem Description**:Gravgen apc does not charge

**What did you expect to happen**: when there is external power for the apc to charge.

**What happened instead**: external power good, but not charging

**Why is this bad/What are the consequences:** because gravity runs out

**Steps to reproduce the problem**:
1. get on as an engineer or anyone with gravgen access
2.check gravgen apc
**When did the problem start happening**:I noticed it today but i have a feeling it was a problem for longer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:. gravgen sme is also not wired correctly.

**Comment by Fox-McCloud** [comment]
need to be specific. Is it the APC or the SMES that isn't charging? They're very different things.

**Comment by realtaac** [comment]
the apc is not charging, the sme doesn't have wires connected to it at round start

**Comment by Shadow-Quill** [comment]
Can't reproduce.
