### ISSUE TITLE
Free golems get autotraitored

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11408]
**Problem Description**:
As a free golem, I was made a traitor in the middle of a round, and I don't think it was an admin messing around.

**What did you expect to happen**: 
To be a good, non-syndie golem

**What happened instead**:
got made traitor.

**Why is this bad/What are the consequences:**
non-crew shouldn't be autotraitors. Also I didn't get an uplink because I had neither a pda nor a radio.

**Steps to reproduce the problem**:
be golem, roll autotator, I assume?

**When did the problem start happening**:
No idea.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Gamemode was autotraitor

**Comment by Taaketa** [comment]
Do you even have access to a PDA to be able to use your Traitor items?

**Comment by Pckables** [comment]
Unless it was fixed, Regular golems can get auto-traitored as well.
