### ISSUE TITLE
Ian is broken when Mining injected

### ISSUE THREAD

**Issue by icem419** [ParadiseSS13/Paradise#11402]
**Problem Description**:
Ian can not pull or climb on things when revived with the mining injector

**What did you expect to happen**: 
Be able to interact with item still as ian

**What happened instead**:
I couldn't

**Why is this bad/What are the consequences:**
It makes Ian far less fun as my round was ended instantly as a miner

**Steps to reproduce the problem**:
Be Ian
Die
Get revived by mining injector thingy
not be able to interact

**When did the problem start happening**:
N/A

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was 
N/A

**Comment by chuga-git** [comment]
This bug no longer exists on current live.
