### ISSUE TITLE
Constantly blinded from portable flasher as borg

### ISSUE THREAD

**Issue by milkde** [ParadiseSS13/Paradise#11411]
**Problem Description**:
I played as a security borg and got blinded from one of those portable flashers in brig. I didn't recover, even if I was far away from them (like being in robotics). I didn't recover even after around 10 minutes. Movement and sight was blocked the whole time (stunmode during flash).
My status were good, shown trait was "blind" and power charge was low.

Edit:
After a restart module were installed, I was able to move again. Though, I got an upgrade afterwards and I was in the stunned state again. Even after the repairs were done, I was stuck in the stunned mode.
When examined it showed the message "It doesn't seem to be responding."

**What did you expect to happen**: 
Normally you would recover after a while.

**What happened instead**:
I didn't recover from the flash and was constantly in blindmode, even after a long timespan.

**Why is this bad/What are the consequences:**
Unable to play after getting stunned. 

**Steps to reproduce the problem**:
I wasn't able to reproduce it yet, since I'm writing the report while I have the issue. I'm still blinded and cannot try it again at the moment. Perhaps I may have the chance to suffer from this issue again.

**When did the problem start happening**:
Since I usually don't play as a borg, this happend to me on 29.04.2019 around 22:30 for the first time.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I was playing as a borg, dragging a person into brig and got flashed by one of the portable devices which were placed. From this moment I wasn't able to attend in the round any further.

**Comment by farie82** [comment]
Sounds like update_stat wasn't called here when it needed to. Borgs have had a few problems with this a while back. Seems it's still not fully fixed

**Comment by DGamerL** [comment]
After some testing, it seems like borgs are now unaffected by portable flashers. I tried triggering one as an engineering borg, which did nothing.
If this does still happen on live, feel free to make a new issue report!
