### ISSUE TITLE
Mentor help interface sometimes doesn't show that it received a response or that it was taken

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#11417]
**Problem Description**:
The text which says that it hasn't received a response shows up even though it had a response. It also didn't say that the mhelp was taken.

**What did you expect to happen**: 
For it to not show those things!

**What happened instead**:
It was wrong and showed!

**Why is this bad/What are the consequences:**
Could cause some confusion between mentors.

**Steps to reproduce the problem**:
I am not certain how why it happens so i cannot tell the steps to do it.

**When did the problem start happening**:
Probably since the time the interface was added.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The mentor didn't have any other mhelps taken and was the only mhelp they answered at the time.
Picture for a example:
![mhelp](https://user-images.githubusercontent.com/37041561/56966884-b50fe780-6b68-11e9-831d-6094d7a897ea.png)

**Comment by SteelSlayer** [comment]
I've seen this happen to myself. Basically if a mentor takes a ticket, responds to the ticket and then crashes or reconnects, the game will "forget" that they took the ticket.

**Comment by silverplatedelta** [comment]
Fairly sure this was fixed with the PM revamp a few months back. if this still happens, I will re-open this issue.
