### ISSUE TITLE
mining redemption points failing to update

### ISSUE THREAD

**Issue by makkenhoff** [ParadiseSS13/Paradise#11458]
**Problem Description**:
What is the problem?
Mining isn't giving points when you drop ore off at the machine. (Observable in one specific round incident, with my son being the operator, and my watching to see exactly what he was doing.)

**What did you expect to happen**: 
Why do you think this is an issue?
Rewarding miners is one of the key things that actually gets them to go down and mine.

**What happened instead**:
How is what happened different from what you expected?
Usually, when ore is dropped at the redemption machine, you can claim the points. Something is causing points to not be able to be claimed, possibly, someone is causing a bug with a specific action.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Without carrot to entice mining, science gameplay will suffer.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Insert ID, dump ore into processor via mining bag, no points show up to claim.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
As far as I know, he said it never works for him. I'll be testing the issue myself shortly, if possible.

**Comment by makkenhoff** [comment]
I actually found on my own character, that it did the same thing to me. Is this a known issue perhaps?

**Comment by Henri215** [comment]
Tested and this issue was fixed by https://github.com/ParadiseSS13/Paradise/pull/16421 too.
