### ISSUE TITLE
Spooking APCs is broken

### ISSUE THREAD

**Issue by SpessX** [ParadiseSS13/Paradise#11459]
**Problem Description**:
Using the "boo" spell on APCs fails to turn them blue for 10 ticks as the code seems to intend.

**What did you expect to happen**: 
According to /obj/machinery/power/apc/proc/spookify() in  Paradise/code/modules/power/apc.dm , APCs should be spookifiable i.e. they appear emagged for 10 ticks.

**What happened instead**:
APC remains all peachy when booing near it, both for ghosts and living crew.

**Why is this bad/What are the consequences:**
Spooky rates are lower than normal across the station, causing unnecessary frustration for dead people. 

**Steps to reproduce the problem**:
1. Don't be alive.
2. Stand on or near an APC.
3. Boo.
4. Observe APC failing to be spooked.

**When did the problem start happening**:
Bug origin is lost to the ages, maybe during old malf AI round tweaks. Spaghetti code so stale you could cut a shiv out of it.

**Comment by Citinited** [comment]
This has been a bug since forever

**Comment by taukausanake** [comment]
Could it be that APCs don't have a check in `update_icons()` for if they are spooky, and thereby don't update their icon? `spookify()` sets a `spooky` var and uses that to update the icon. Just spit-balling here

**Comment by Citinited** [comment]
Basically, yes. But the code needs to be rewritten entirely, as it is terribad. I've got a PR in the works
