### ISSUE TITLE
Abductor sleep lasts far too long (potentially forever?)

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11468]
**Problem Description**:
After I was abducted by abductors and then sent back to the station, I just...didn't wake up. At least 5 ingame minutes passed without me waking up.

**What did you expect to happen**: 
To wake up after a reasonable amount of time. I was also a vampire using powered-up rejuvenation, which only woke me up for 1 or 2 seconds before I instantly fell unconscious again. I expected rejuvenation to remove sleep.

**What happened instead**:
I lay there for at least 5 minutes. A sec officer was also lying there, probably suffering the same fate. Then a radstorm happened and we died.

Also, I got a message about my abduction objective fading away before I even woke up to try and carry it out, which definitely can't be working as intended.

**Why is this bad/What are the consequences:**
Once you get abducted, you're potentially out for 10+ minutes, lying there, looking at a 1 tile distance around you.

**Steps to reproduce the problem**:
1. Be abducted and put to sleep with abductor baton
2. (Maybe be a vampire spamming rejuv?)
3. Get sent back
4. Don't wake up.

**When did the problem start happening**:
It has been a while since I was last abducted, no clue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Gamemode was vampire. Looking at the abductor baton code, it is only supposed to put you to sleep for 60 seconds/ticks or whatever. It definitely was longer than that.

**Comment by TDSSS** [comment]
Update: Having trouble reproducing this on my test server. Though on my test server, I also don't even wake up for a moment when using rejuv, which is weird.

**Comment by TDSSS** [comment]
Starting to think I was just dosed with an extremely high amount of ether or something by the abductors.

**Comment by Shadow-Quill** [comment]
Sleep ends up lasting for ~2 minutes 7 seconds.

**Comment by Fox-McCloud** [comment]
Yeah, abductor batons last a while, but either the `Life` loop broke, or you were hit with more than just the baton.
