### ISSUE TITLE
Antagonist selection bug

### ISSUE THREAD

**Issue by Allfd** [ParadiseSS13/Paradise#1147]
I was selected to be an antagonist (vampire) despite having selected only synthetic and a loyalty implanted job.  I was given text to this extent but was placed back in the lobby having not gotten any of  my selected jobs and having that selected as my preference for this occurrence.

I then joined the round as a BlueShield and was not presented with any antagonist interface.

On round end I was listed as a vampire with objectives.

**Comment by tigercat2000** [comment]
Is your job selector preference turned to "go back to lobby if prefs not avalible"? With the antag picker choosing before jobs, the job controller won't put you in protected roles, it will cycle to the next behavior, which if you have that preference set to lobby, it will just give up.
