### ISSUE TITLE
Using vampire rejuv in the moment you'd fall asleep prevents blindness while sleeping

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11478]
**Problem Description**:
See title, using vampire rejuv (and I assume it will also work with say a changeling's anti-stun power etc.) the moment you fall asleep, as in while your sprite is turning horizontal, prevented the 'sleeping/blindness' overlay from showing up. It stayed like this even after I woke up and went to sleep again.
![Untitled](https://user-images.githubusercontent.com/32099540/57237099-c5233d80-7026-11e9-862c-93f5b03535c2.png)

**What did you expect to happen**: 
to not be able to see.

**What happened instead**:
I can see everything around me.

**Why is this bad/What are the consequences:**
you can see what happens in your sleep!

**Steps to reproduce the problem**:
I dosed myself with shitloads of ether and kept spamming rejuv+ in the process of trying to reproduce another bug when I noticed it. You probably need very accurate timing for this.

**When did the problem start happening**:
No idea.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Using admin rejuvenate on the mob fixed it and he properly went blind when sleeping afterwards again.

**Comment by matttheficus** [comment]
Overlay and Rejuv both greatly changed since issue made, stale.
