### ISSUE TITLE
Placing wires doesn't work the same now

### ISSUE THREAD

**Issue by ID404-NotFound** [ParadiseSS13/Paradise#11481]
**Problem Description**:
What is the problem?
I cannot make wire art with diagonal wires meeting at a tile.
**What did you expect to happen**: 
Instead of clicking a diagonal tile from me twice, resulting in a diagonal wire on the tile I clicked, and then a diagonal wire appearing on the tile I am standing on, without combining with any wire present, I got a diagonal wire on the tile I clicked, and then a vertical wire on the tile I was on.

**Steps to reproduce the problem**:
Stand on plating, click diagonal spot with plating, see diagonal wire, click same spot, instead of diagonal wire below you, either vertical or nothing.

**When did the problem start happening**:
At least a week ago, I remember on Easter making a summon symbol with corners made from diagonal wires meeting to summon elys during Easter Sunday event

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It's all the time

**Comment by Mitchs98** [comment]
I saw a wire made similar to what you wanted by David Flufferton when re-wiring the Captain's office not too long ago. So I know it's still possible, but perhaps buggy.

**Comment by DGamerL** [comment]
Heya! Thanks for making the report! It seems that this issue has been fixed along the way! You can do proper diagonal wires again - I made some nice wire art with it today :)
If you notice another bug with it, feel free to make a new issue report!
