### ISSUE TITLE
Windoors can no longer be kept open

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11487]
**Problem Description**:
You used to be able to click windoors with an empty hand to open them permanently. This is no longer possible.

**Why is this bad/What are the consequences:**
It is annoying as HOP/security not to have that option

**Steps to reproduce the problem**:
1. Click windoor with empty hand
2. It closes after a few seconds when it shouldnt

**When did the problem start happening**:
No clue. Sometimes in the last month(s?)

**Comment by Markolie** [comment]
Caused by https://github.com/ParadiseSS13/Paradise/pull/11443.
