### ISSUE TITLE
Dying and getting revived (not cloned) gives you xray

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11488]
**Problem Description**:
Dying and then being revived gives the user xray vision without the night vision.

**What did you expect to happen**: 
Not to get xray

**What happened instead**:
Got xray. Not the block. Just the vision

**Why is this bad/What are the consequences:**
Wallhacks are not to be given to those who die. They are to be earned

**Steps to reproduce the problem**:
1. Die.
1.? Might have to get out of your body first
2. Get revived. (SR in my case)

**When did the problem start happening**:
New lightning system PR

**Comment by farie82** [comment]
Being dead was also very bright. As in overly bright.

**Comment by Ralta** [comment]
Clearly you were blessed with a gift from the great BYOND.
