### ISSUE TITLE
Chameleon kit does not adapt to species sprite

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11485]
**Problem Description**:
When wearing a chameleon clothing item and changing it to a different sprite, this sprite will not adapt to the species' even if the item morphed into has a special sprite for them, causing clipping.

**What did you expect to happen**: 
Disguise as sec officer. Be sneaky.

**What happened instead**:
Helmet is too smol for big grey forehead. Obvious there is something wrong.

**Why is this bad/What are the consequences:**
Looks bad and is a tell that the item is fake

**Steps to reproduce the problem**:
1. Be grey (I have seen other species having the issue but big forehead make it obvious)
2. Change the chameleon cap into a security officer helmet or any other item with grey specific sprite
3. looks like regular human item causing clipping

**When did the problem start happening**:
I assume since #11428

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Happened on a regular round on live

**Comment by MarsM0nd** [comment]
Will be fixed in #11466

**Comment by datlo** [comment]
Closing this then, sweet
