### ISSUE TITLE
Entering Ore into the ORM by hand gives 0 points.

### ISSUE THREAD

**Issue by Kamesya** [ParadiseSS13/Paradise#11491]
**Problem Description**:
Entering Ore into the ORM by hand gives 0 points. This is achieved by carrying the ore from elsewhere, not having a crate, not dropping it on the tile before the ORM, etc. Whether in stacks of hundreds or just individual pieces of ore.

**What did you expect to happen**: 
I see no reason that placing ore in by hand should not give points - I expected to receive points for redemption/addition to my ID but did not.

**What happened instead**:
Whether my ID was in or out at the time of placement and no matter the rarity of ore, no points accrued. I was later informed by those who have worked the system before that most folk empty their bags or crates on the preceding tile for the machine to automatically collect.

**Why is this bad/What are the consequences:**
If no crates are present or someone is in a hurry, or if a new person (like myself) is working the system, there might be a lot of frustration and confusion over the lack of accrued points.

**Steps to reproduce the problem**:
I emptied my crate two tiles (north, west) from the ORM's in-area deposit point, picked up the ore stacks in my hand, and clicked the ORM to deposit them. The ORM produced metals and gems, but not points. I repeated the same three tiles away from what I would later learn was the usual point of dumping (north, north, north) & repeated the process with my ID in instead, to the same effect. I left, retrieved rarer goods (bluespace, diamonds, etc) and tried with both my ID in and out to the same effect before learning of the usual dumping procedure second-hand from the active quartermaster.

**Comment by MrMagolor** [comment]
I'm pretty sure this is a feature, otherwise you could have any scientist get infinite points with xenobio crystals.

**Comment by datlo** [comment]
Err they can do that anyway. Just let the scientist in. Or scientist can just break in if cargo isnt there. That is definitely not a good reason...

**Comment by matttheficus** [comment]
Unsure if this still holds true OR is intended behavior to prevent point farming? Will need to check

**Comment by Henri215** [comment]
PR https://github.com/ParadiseSS13/Paradise/pull/16421 supposedly fixed this

**Comment by Henri215** [comment]
Tested and it was indeed fixed by that PR.
