### ISSUE TITLE
Service borg bugs

### ISSUE THREAD

**Issue by Imotepchief** [ParadiseSS13/Paradise#11505]
**Problem Description**:
The service borg can move and talk without power cell charge.
Also the shaker is sporadic in what it will regenerate when filling glasses and what it won't.
I had an issue where in an attempt to make a "Servo", the mix failed to actually make the drink, but still regenerated the failed liquids when pouring out a glass, but then failed to replicate a successful drink (Milkshake).

**What did you expect to happen**: 
Didn't expect to move or talk without power and expected the shaker to work with successfully mixed drinks.

**What happened instead**:
What I stated in the description.

**Why is this bad/What are the consequences:**
Borgs being able to move and talk without power seems counter intuitive.
**Steps to reproduce the problem**:
I used the money fabrication to drain my power, then turned lights to max.

**When did the problem start happening**:
I only noticed it today 10/05/19, but I hadn't played service borg up until this point.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I was just doing generic drink mixes, trying to work out and push through the shaker issue.
My power cell was drained, while doing some fun role play with others as a chess piece... don't ask...

**Comment by taukausanake** [comment]
I think I've seen a few borgs that are able to move while on a dead battery. I think it's a "player friendly" way of not letting them die out in the open due to their own fault but I could be wrong. Personally I think they should stop operating once their battery dies

**Comment by BiancaWilkson** [comment]
Cyborg power and shakers have both since been reworked, which have fixed the issues mentioned.
