### ISSUE TITLE
ghosts cannot travel trough z levels, by movement

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11509]
**Problem Description**:
What is the problem?
You can't travel trough z levels as ghost by moving
**What did you expect to happen**: 
Why do you think this is an issue?
I should be able to move trough z levels, by moving.
**What happened instead**:
How is what happened different from what you expected?
I did not change z level, I faceplanted into border of level, black pitch void.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
You can't travel trough z levels by moving.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be ghost
2. Press movement key, to start moving in one direction
3. Reach border of space continuum, void, black pitchness, after not leaving z level as you should

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
I think since merging of SS things, like ssmapping, and plenty of others

**Comment by Denthamos** [comment]
Can confirm, not even as admin can you leave the Z level as ghost.
