### ISSUE TITLE
Mindslave status persist through cloning

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#11514]
**Problem Description**:
As the title says, mindslave status will carry on through cloning, despite the fact that the mindslave implant is, obviously, an implant that'll stay in the old body. Furthermore, I've been told that the only way to remove this mindslave status would be to remove the implant from the *old, mindless corpse*.

**What did you expect to happen**: 
Mindslave doesn't transfer through cloning, as it's caused by an implant in the body.

**What happened instead**:
It carries through cloning and behaves really oddly, requiring the old body's implant to be removed.

**Why is this bad/What are the consequences:**
It's really counter intuitive and I'd argue very unintended, or at least very unclear. I personally don't think the mindslave status persisting is a bad thing by itself, but then it should probably not be an implant in the first place.

**Steps to reproduce the problem**:
- Be mindslaved by someone.
- Die and be cloned.
- Note how the mindslave objective is still there

**When did the problem start happening**:
No idea.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Gamemode was traitors. The person implanted when I noticed this was also a traitor.

**Comment by Couls** [comment]
It's definitely a weird situation, I like to think that the mindslave implant modifies your mind and thats whats being cloned which is why the objective persists through cloning but it wouldn't explain why you'd lose it when the implant is removed and its essentially impossible to remove a mindslave implant from a cloned person because they likely won't have it

**Comment by Sikroth** [comment]
Yeah as I said, I think it'd make sense to keep the mind slaving after cloning. Just then it probably shouldn't be an implant, but rather some sort of... I dunno, brainwash, hypnosis or whatever that's not a physical item in your body.

**Comment by DGamerL** [comment]
According to Qwertytoforty this still happens
