### ISSUE TITLE
Invisible equipment

### ISSUE THREAD

**Issue by AguliRojo** [ParadiseSS13/Paradise#11517]
**Problem Description**:
What is the problem?
Equipment is invisible, and it doesnt work.
[https://imgur.com/a/ugx5IRy](url)

**What did you expect to happen**: 
I tried to use engineer radio but "i didnt have it on myself"

**What happened instead**:
I talked to my area

**Why is this bad/What are the consequences:**
Beucause i cannot contact with crew

**Steps to reproduce the problem**:
1. Get zapped by sec.
2. Checkout
3. Get zapped again 
4. Checkout
5. I tried to communicate
6. I took secound radio from dep.( I had none on my equipment)
7. Now i have 2 radios.(used "e" Equip)
(there is simmilar problem with statuses(oxygen deprivation, toxins, and so on, but i doont have proofs or ways to replicate)

**When did the problem start happening**:
Today, and earlier, but rarely.

**Comment by AguliRojo** [comment]
Wht might be interesting, after reconnecting i dont see any equipment on myself, yet wearing it, automatically puts it into pockets

**Comment by Emanthealmighty** [comment]
Also happens when switching through Buds (F12)

**Comment by JohnBigless** [comment]
Upon recconecting, the clothing UI becomes invisible.
Closing and opening the clothes UI fixes the problem.

When Aghosting and re-posessing the entity you aghosted from (Eg. Yourself), sometimes, ALL OF THE EQUIPMENT in the HuD becomes invisible.
Hiding the HuD with F12 and showing it again fixes the problem.
