### ISSUE TITLE
Antag not forced to join ingame

### ISSUE THREAD

**Issue by SplinterGP** [ParadiseSS13/Paradise#11527]
**Problem Description**:
i rolled  antag and i wans't forced into round

**What did you expect to happen**: 
I should be forced into the round seeing that i am antag

**What happened instead**:
I just stayed at the lobby normally

**Why is this bad/What are the consequences:**
Because people probably can see they are antag and choose his job because of it

**Steps to reproduce the problem**:
no idea actually, the only thing that i think it was is that i pressed ready with only 2 seconds left

**Possibly related stuff: Character was a Grey, with wingdings and trasnlator implant, Chaplain as high

[Image1](https://imgur.com/TIlQcs8) [Image2](https://imgur.com/qAry5ib)

**Comment by farie82** [comment]
Fixed in #12896
