### ISSUE TITLE
Nanotrasen Minebot Meson Scanner Not working

### ISSUE THREAD

**Issue by garbagestinkman** [ParadiseSS13/Paradise#11531]
**Problem Description**:
Nanotrasen Minebot's meson scanners are toggled on and then turn off a couple of seconds after.

**What did you expect to happen**: 
The meson scanner to stay on.

**What happened instead**:
The meson scanner turned off almost immediately..

**Why is this bad/What are the consequences:**
Cannot see ore in rocks, forced to clear rocks and get ore by chance and guess work. This is an issue because it hinders my ability to be useful for the person who has created me. I can no longer see any clearings that could have potential enemies in them.

**Steps to reproduce the problem**:
Left click the meson scanner toggle button in the top left.

**When did the problem start happening**:
A few days ago I was a nanotrasen minebot and it worked fine with no issue. Today I am one and it is no longer working.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The game mode on Paradise is secret. I was created during a fight between a basilisk and the player who created me. I helped him kill it. Afterwards I turned on the meson scanner and it turned off again almost immediately without any message in chat. I told him the meson scanner wasn't working and he said that was odd and he would get an upgrade for it. After returning to the ship he went to the mining vendor and couldn't find an upgrade. I decided to just deal with it and we continued mining. I'm not sure if it's related, but yesterday I had constant disconnections from the Paradise server after a couple of minutes being connected. I couldn't play. Other servers did not give me the same problem. Today my connection is fine. I tried swapping modes, but that didn't seem to help. Swapping between Harm and Help intent didn't work either. I asked a mentor about it and they told me to submit a bug report here.
I'm unsure if this is helpful, but here is me turning it on over and over again without any alert that it's been turned off. 
![ss (2019-05-16 at 06 26 13)](https://user-images.githubusercontent.com/50679413/57807075-c92c2980-77a3-11e9-9114-1dc6015ecc2a.png)

**Comment by Taaketa** [comment]
Know issue due to the TG lighting change. All measons are broken and is something that has to be addressed

**Comment by Markolie** [comment]
> Know issue due to the TG lighting change. All measons are broken and is something that has to be addressed

Mesons are actually working fine. It's just the mesons for minebots that are broken, but I'm working on fixing this now. It wasn't actually a known issue by the way; I wasn't aware of it as nobody had made an issue report. I appreciate you doing so @garbagestinkman!
