### ISSUE TITLE
Item overlays sometimes dissapear

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11538]
**Problem Description**:
Overlays on items. Such as beakers or bottles sometimes just vanish. Same for the captains gun.
The health overlay also breaks. Unsure if it's related or not

**What did you expect to happen**: 
You miss visual information due to this. Is the gun charged? No clue

**What happened instead**:
The icons lost their overlays sometimes. When used they returned or after a short while.

**Why is this bad/What are the consequences:**
You will miss information due to this

**Steps to reproduce the problem**:
No clue it's rather random. Just have a bag full of beakers open and go walk around

**When did the problem start happening**:
About 1 or 2 months ago?

**Comment by Couls** [comment]
BYOND issue: https://github.com/tgstation/tgstation/issues/36936

**Comment by S34NW** [comment]
TG issue states it has been fixed
