### ISSUE TITLE
Middle-click Point doesnt work at all

### ISSUE THREAD

**Issue by Vaebryn** [ParadiseSS13/Paradise#11530]
**Problem Description**:
I cannot middle click to point, or point at all.

**What did you expect to happen**: 
Point.

**What happened instead**:
Not Point

**Why is this bad/What are the consequences:**
Pointing is pretty vital to the game

**Steps to reproduce the problem**:
It seemed to happen randomly. Toggling Hotkey didn't work. Restarting didn't work. It's not a character issue as others can take over my body fine and point.

**When did the problem start happening**:
Yesterday evening

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It just sort of happened. I don't know how. Perhaps something to do with genetics since I was that a lot last night?

**Comment by AffectedArc07** [comment]
If other people can do it and you cant, are you sure your middle mouse isn’t broken?

*i know it’s a stupid question but things gotta be asked*

**Comment by Vaebryn** [comment]
I will attempt to see if thats the problem. Cant seem to find a good way to test. Most games don't use middle click. Scrollwheel still works

**Comment by Vaebryn** [comment]
Yeah. I think thats the problem. I guess I'll need to rekebind it if I can even do that

**Comment by Citinited** [comment]
If it's a problem with your hardware, this issue can probably be closed

**Comment by KasparoVy** [comment]
perhaps shift+alt click to point, or space+click
