### ISSUE TITLE
Macrobombs don't stack

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#11540]
**Problem Description**:
Macrobombs don't stack and the code for it is very freaking confusing

**What did you expect to happen**: 
Macrobombs should stack like microbombs or at least have code to show that stacking isn't intended

**What happened instead**:
Macrobomb isn't stacking

**Why is this bad/What are the consequences:**
The code is misleading

**Steps to reproduce the problem**:
Take two macrobomb implants, use them on yourself

![image](https://user-images.githubusercontent.com/30060146/57964350-305ff000-7902-11e9-8007-a0cf2c8bbaef.png)
Why does this have the same check twice?

**Comment by datlo** [comment]
this is working as intended, macrobombs dont stack because it reaches the explosion cap of explosive implants with a single one

**Comment by Sirryan2002** [comment]
working as intended
