### ISSUE TITLE
Sometimes certain hotkeys don't work

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#11542]
**Problem Description**:
Sometimes certain hotkeys don't work during a round. The hotkeys that didn't work were: Drop,Throw, Equip. I am not the only one having the problem and it has happened more than once now.

**What did you expect to happen**: 
For the hotkeys to work.

**What happened instead**:
Pressing the hotkey buttons did nothing.

**Why is this bad/What are the consequences:**
Not being able to use hotkeys can slow people down as well as maybe even ruin their rounds.

**Steps to reproduce the problem**:
I am not certain as it seems random. 

**When did the problem start happening**:
First time it happened was around the middle of April.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Asked the admins if any runtimes were happening, but none.
Not sure on the gamemodes, but one of the times was blob gamemode. (Not sure if it would have to do something with it, but maybe?)

**Comment by Sikroth** [comment]
I'm not sure if it's the same, or even a related issue, but I've had problems with hotkeys if I played a silicon (borg, or drone probably), and then later respawned as a humanoid (for example in an ERT). Did something similar to this happen or am I completely off?

**Comment by dovydas12345** [comment]
Nope each time it happened to me was at roundstart.

**Comment by Markolie** [comment]
This is almost certainly related to silicons, yes. Joining as a robot sets your hotkey mode to cyborg, but joining as a human doesn't reset it. You can manually force this to fix itself by setting your hotkey mode to QWERTY or AZERTY under the preferences tab. I was going to fix this, but with the hotkey mode refactor PR up there's not much point.

**Comment by dovydas12345** [comment]
Oh, now that i think about it I did play silicon the round before! Guess i was mistakened. Great to know the cause at least.

**Comment by dovydas12345** [comment]
This is no longer a problem, since the refactor PR was merged.
