### ISSUE TITLE
Grid check event releasing engines

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11548]
**Problem Description**:
The grid check event sometimes now is resulting in the engine releasing somehow.  Based on what I saw across a few rounds now with it, the containment SMES still will be outputting power based on its settings, there will be power along the wires, and the emitters will still be firing.  However the actual containment shield generators will turn off to a default state as if they were not turned on.

**What did you expect to happen**: 
The event should not be affecting engineering as it can obviously result in round ending possibilities.

**What happened instead**:
The containment shield generators are turning off for some reason.

**Why is this bad/What are the consequences:**
It can release the tesla/singularity into the station.

**Steps to reproduce the problem**:
Set up the engine, get it stable, que up the grid check event.  The issue with this is it does not happen every time.

**When did the problem start happening**:
Breenland reports it happening a few months ago, I remember it happening two weeks ago as well.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing out of the ordinary.  Only have seen it happen with the tesla engine, however that could be because most people use the tesla instead of singularity.

**Comment by TDSSS** [comment]
Might be related to #11393 ? Did it happen before that too?

**Comment by Citinited** [comment]
I wonder if this happened due to the engine being wired to the rest of the grid (which is something that doesn't often happen). I don't know the code but if all it does is a simple `if not engineering then drain` check then it may also drain the engine powernet if the two are linked.

**Comment by Fox-McCloud** [comment]
Quite frankly, if you're hotwiring it to the grid and lose control of the engine because someone powersinks it, that's on you, and shouldn't be something we code against, specifically.

Hotwiring is supposed to be a riskier thing that has consequences to, and not a "this is the optimal thing to do every shift regardless of context".

**Comment by Denthamos** [comment]
@Fox-McCloud @Citinited I can confirm the engine was not hotwired into the grid when the grid check happened.

**Comment by AffectedArc07** [comment]
No longer relevant
