### ISSUE TITLE
Atmos Controller Issue

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11549]
**Problem Description**:
The atmos controller is getting overloaded when the entire station is getting filled with a icon based gas like nitrogen/plasma now.  Brings the CPU up to 150-180 on its usage, the atmos controller reaching 800%, ping for players entering 500+, and causes the server to enter DEFCON status.

**What did you expect to happen**: 
For the system to handle the atmos adjustments of gasses like how it used to.

**What happened instead**:
It nearly crashed the server and required a station wide atmos reset which fixed the issue.

**Why is this bad/What are the consequences:**
Because it can crash the server.

**Steps to reproduce the problem**:
Start filling the station with the new gasses with icons like N2 and plasma.

**When did the problem start happening**:
Noticed this on 5/18/19.  May have started when the visuals for gasses was changed.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
There was multiple breaches across the station where gasses were constantly leaking out through, so it could of exacerbated the situation.

**Comment by Allfd** [comment]
This sounds like a Linda issue related to hotspot calculations.  I don't think there is a fix other then replacing Linda or preventing that many hotspots from being added to the controller somehow.

**Comment by Denthamos** [comment]
Have not noticed this type of crash happen in some time.  Closing this PR due to lack of recent crashes from this.
