### ISSUE TITLE
Toy disintegrate spell will trigger beepsky.

### ISSUE THREAD

**Issue by VEN0M5** [ParadiseSS13/Paradise#11569]
**Problem Description**:
The toy plastic disintegrate spell when its in your hand will cause beepsky and ED-209 bots to trigger a lvl 4 infraction and go after you.

**What did you expect to happen**: 
Beepsky ignores the toy spell and went on its merry way.

**What happened instead**:
Beepsky chases me across the station for lvl 4 infraction.

**Why is this bad/What are the consequences:**
Security comms could be spammed by beepsky's lvl 4 infraction over a toy.

**Steps to reproduce the problem**:
1) Purchase the toy spellbook from the arcade.
2) Use the book and activate the spell and keep it on hand.
3) Find beepsky or any other security bots.
4) Get stunned to oblivion.

**When did the problem start happening**:
Only noticed it 3 days ago but that was the first time I got the toy spell. No idea how long did it exists.

**Possibly related stuff (which gamemode was it?)**:
Any rounds would work.

**Comment by taukausanake** [comment]
That's hilarious. If it didn't spam sec radio I'd say leave it in. Police brutality. Probably should be fixed though

**Comment by KalevTait** [comment]
Looks like an oversight.
The mime version of this, /obj/item/gun/projectile/revolver/fingergun, correctly overrides needs_permit to 0 (set to 1 in parent class gun)
/obj/item/melee/touch_attack/fake_disintegrate doesn't override needs_permit to 0 (set to 1 in parent class melee)

Should be a very easy fix.
