### ISSUE TITLE
Some misplaced gas meters

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11578]
See image below, been like this since all the gas pipes were remapped I believe

![image](https://user-images.githubusercontent.com/18459142/58201622-6e2b9280-7ccd-11e9-9084-d4d7877f1b7f.png)

**Comment by Couls** [comment]
working as intended:tm:

**Comment by Muhdi345** [comment]
I noticed it some time ago when I nagged about all the other things when the piping remap went through. But since I already did 3 of them I just made myself believe they were there for quirkiness.

**Comment by AffectedArc07** [comment]
Dunno when exactly we fixed this but we did with a sci remap a while ago.
