### ISSUE TITLE
Venus Human Traps are invisible

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#11580]
![InvisibleVenusManTrap](https://user-images.githubusercontent.com/35735195/58226997-1144d200-7cf7-11e9-8bfd-2026cc5b3356.PNG)

**Problem**:
Venus Human Traps spawned by flowering space vines are invisible killing machines.

**Why is this bad**
No one can see/attack them unless you alt+click the tile, and by then they've likely already broken a bone or killed you if you're an IPC.

**Steps to reproduce the problem**:
Let Kudzu go crazy. Watch flowering vines spawn invisible enemies.

**When did the problem start happening**:
Likely only in the last month or two.

**Possibly related stuff.*:
Vines were extremely out of control, but they were all invisible across all the space vines.

**Comment by Arkatos1** [comment]
Ooops, this one is my bad, I have probably removed the sprite when I was modifying animal sprites, sorry. The PR above should fix this.
