### ISSUE TITLE
Guns still shoot in random directions, on byond version 512.1469

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11594]
**Problem Description**:
What is the problem?
Guns don't shoot where you aim about 80% of time.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It was fixed according to lumox in byond 512.1469
It is not, it did happen on that version of byond, on both my private server(version is somewhere from march/april), and live paradise server.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Have gun, aim somewhere with mouse.
2. Click, you shoot backwards, or sideways, or rarely where you aim.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Tested on byond 512.1469, private paradise server downloaded from github 21.03,
and on live paradise server yesterday.

**Comment by MrMagolor** [comment]
I can definitely occur that this happens still.

Was very annoying when trying to shoot terror webs WITHOUT hitting random civs.

**Comment by Markolie** [comment]
512.1470 was just released, which apparently fixes the remainder of the clicking issues.

**Comment by Deelite34** [comment]
Did tests on 1470 private server, and I wasn't able to replicate this issue anymore. I'll assume, that it's fixed on live server as well, and close it.
