### ISSUE TITLE
Mouses squik post mortem when you walk on them.

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11596]
**Problem Description**:
What is the problem?
You walk on mouse, it squiks. You kill it, then walk on it, and it keeps making noises, even though its dead. Security hears, and comes to you.

**What happened instead**:
How is what happened different from what you expected?
I expected for dead mouse to not make noises, when you walk over it.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Makes you less stealthy.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. kill mouse
2. walk over it, it will squik
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
since few weeks ago I think

**Comment by Citinited** [comment]
I'm fairly sure that #11493 is the culprit - removing the squeak component from mice upon death should fix this
