### ISSUE TITLE
Conveyor belt not moving items when placed under autolathes

### ISSUE THREAD

**Issue by le7emenain** [ParadiseSS13/Paradise#11595]
**Problem Description**:
Conveyor belts aren't moving items when placed under an autolathe

![SS13ConveyorBeltIssue](https://user-images.githubusercontent.com/35875966/58382075-bac0e780-7fc5-11e9-8991-7307bbe975ed.jpg)

**What did you expect to happen**: 
Items under the autolathe should be moved by the conveyor belt.

**What happened instead**:
items wouldn't be moved by the conveyor belt.

**Why is this bad/What are the consequences:**
Conveyor belts under autolathes were really useful for cargo, to make efficient setups for us lazy cargonians.

**Steps to reproduce the problem**:
Place a conveyor belt linked to a switch, build an autolathe on top of said belt, activate the belt, print something with the autolathe. witness the lack of movement from the printed item.

**When did the problem start happening**:
It used to work a few weeks ago, I just noticed it the 26.05.2019

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Standard shift, nothing out of the ordinary. Same setup that I always build and wich usually works.

**Comment by Citinited** [comment]
I'll take a look at it tomorrow, did it eventually move or was it completely stationary?

**Comment by Pckables** [comment]
I've had this issue as well, and the items never moved, whether you waited or turned the conveyors off and on again. The following belts would work, just not the one under the autolathe.
