### ISSUE TITLE
AI robot control window broken

### ISSUE THREAD

**Issue by RobloxPlayer16** [ParadiseSS13/Paradise#11607]
**Problem Description**:
What is the problem?
The AI's robot control window does not list any bots. Querying the network doesn't do anything. This has happened over several rounds consistently.

**What did you expect to happen**: 
Why do you think this is an issue?
The bots list should be populated with all active bots.

**What happened instead**:
How is what happened different from what you expected?
There is nothing. 

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
AI can no longer control bots remotely and must search them out. If settings must be changed or bots turned off, the AI can no longer do that. The AI can also no longer call bots to any location at all, as the only way to do that was from that interface. 

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Play as AI, click on robot control. 

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
I took a break from SS13 for about a month but when I came back a week ago, probably may 20th, I noticed the problem. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Screenshot of the empty interface below. The query button does not do anything. There were several active bots at that time in the round.
https://i.gyazo.com/5829c9091cc3141b90a41e61cf951aae.png

**Comment by Spacemanspark** [comment]
Can confirm, this is happening. Kinda fucks with the AI, especially considering Pingsky is one of its best defenses on the satellite atm.
