### ISSUE TITLE
Can hear Cultist chatter and IC announcements in the lobby

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#11603]
**Problem Description**:
I was able to hear Cultist chatter and bridge announcements from the lobby.

![Untitled-1](https://user-images.githubusercontent.com/42044220/58405298-18d8e380-8035-11e9-843c-fd8ef87487fc.jpg)

**What did you expect to happen**: 
Not to be able to hear these things.

**What happened instead**:
I heard these things.

**Why is this bad/What are the consequences:**
Obviously this can be used for metagaming, as you can see what kind of round it is before joining the game, and even see the names of the cultists.

**Steps to reproduce the problem**:
It appears totally random whether you can see the chatter or not. Sometimes I've had rounds where I sit in the lobby and see no cultist chatter, only to join and find out its cult. Other rounds, such as this one, I can see the chatter from the lobby.

1) Wait for the game to start
2) Sit in the lobby and hope its a cult round

**When did the problem start happening**:
I saw this first happen about a few weeks ago, thought it was just a random bug. Then it happened again, and I decided to report it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Two other mentors also reported that they could see the cultist chatter from the lobby.

**Comment by taukausanake** [comment]
The cult chat should have been fixed in #11362. And the announcements in an even older PR I think
