### ISSUE TITLE
[Lavaland] Vulpkanin have no explorer gas mask sprite

### ISSUE THREAD

**Issue by Xantholne** [ParadiseSS13/Paradise#11625]
**Problem Description**:
No sprite for vulps with explorers mask

**What did you expect to happen**: 
Its invisible

**What happened instead**:
Should have had a gas mask sprite

**Why is this bad/What are the consequences:**
Makes it look like you have no mask on

**Steps to reproduce the problem**:
Be vulp
put on explorer mask

**When did the problem start happening**:
Always

**Comment by Markolie** [comment]
For now I'll have them use the standard human sprite. Somebody will have to sprite the alternative ones though. Drask and Grey ones will be added shortly.

**Comment by Deelite34** [comment]
Tarajan don't have one as well, other non human races probably too
