### ISSUE TITLE
Mining lavaland pods can be used on the station

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11631]
**Problem Description**:
You can deploy the lavaland shelter pods on the station

**What did you expect to happen**: 
Not to be able to drop the pod on the station

**What happened instead**:
It fucked up the part of the station it got deployed

**Why is this bad/What are the consequences:**
Able to destroy part of the station and rebuild them anew is not quite wanted I assume

**Steps to reproduce the problem**:
Get the shelter and use it on another Z level than lavaland

**When did the problem start happening**:
LAVALAND!!!!

**Comment by Markolie** [comment]
I'm pretty sure this is intentional: the shelters can be placed anywhere as long as it doesn't conflict with walls.

**Comment by farie82** [comment]
Copy that. I expected them to not be removable and that they would remove items in the way. Closing it due to it being removable and not being destructive
