### ISSUE TITLE
Resources are not being send, sprites glitching

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11636]
**Problem Description**:
Multiple issues with I believe the same source. Not sure what.
1. People becoming invisible (sprites dissapearing)
2. Items losing their overlay (beakers etc)
3. Equipment tab, armor etc becoming invisible (sprites gone)
4. Resources of windows not being shown (crew monitor)
Probably more I can't remember
It's a trend that started with the first one. Then the second one, third and now the 4th issue

![image](https://user-images.githubusercontent.com/15887760/58758649-703bef80-851e-11e9-97ea-d422df4e4504.png)

**What did you expect to happen**: 
Not to have missing sprites/resources

**What happened instead**:
Sprites dissapeared, couldn't open windows

**Why is this bad/What are the consequences:**
Paradise code is slowly dying from it. To a point where it becomes unplayable

**Steps to reproduce the problem**:
Play the game and see the sprites dissapearing at random. Roundstart usually has this as virologist for instance

**When did the problem start happening**:
Since a month or 2-3 now

**Comment by Couls** [comment]
BYOND issue https://github.com/tgstation/tgstation/issues/36936

**Comment by DGamerL** [comment]
Just like the TG issues, there haven't been any reports of overlay issues, meaning that most likely the Byond bug has been fixed. Thanks for making this report, and feel free to make a new one if this happens again!
