### ISSUE TITLE
Grey cannot change hair color in preferences

### ISSUE THREAD

**Issue by TheSardele** [ParadiseSS13/Paradise#11646]
**Problem Description**:
As title.

**What did you expect to happen**: 
To be able to change the hair color in preferences/set up character. Changing it in game via a mirror works.

**What happened instead**:
Clicking the "Hair" or "Facial hair" Color buttons does nothing.

**Why is this bad/What are the consequences:**
While it might seem like giving an entirely bald species the ability to change the color of their hair, for example kitty and mouse ears. If Greys want to wear those and have them a certain color, they will have to change it every single round at a mirror.

**Steps to reproduce the problem**:
Create a Grey, try changing the hair or facial hair color.

**Comment by taukausanake** [comment]
Greys have hair?

**Comment by Burzah** [comment]
Since Greys and other species do not have certain appearance options, there would be no need to have appearance options for something that can't be changed for specific species. I am closing this issue as not planned. Thank you for the report!
