### ISSUE TITLE
Sec Escape Pod Airlock Button Hard To See

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#11649]
**Problem Description**:
The airlock above the security escape pod is hard to see.

**What did you expect to happen**: 
The button should be easily visible on a nearby wall.

**What happened instead**:
The button is in the reinforced glass next to a wall, which makes it visible over a black square. It can be hard to miss.

**Why is this bad/What are the consequences:**
Some players already reported having to alt+click on the tile to interact with the button, so it can either make it difficult or impossible to quickly cycle the airlock.

**Steps to reproduce the problem**:
1. Go to the airlock north of the security escape pod
2. Look at the button
3. It may be invisible under a black block, or visible on a black block.

**When did the problem start happening**:
I first saw it today, so I'm not terribly sure. It may have happened with the remap of the area, but no one noticed.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
No other info really, just a couple screenshots. Second image I had to brighten.
![image](https://user-images.githubusercontent.com/38596550/58763017-9dd36980-851b-11e9-8fd9-a8258a7d89f8.png)
![image](https://user-images.githubusercontent.com/38596550/58763046-e5f28c00-851b-11e9-8fe0-f121cc2972de.png)

**Comment by taukausanake** [comment]
We should give buttons and other machinery some glowing overlays like how some eyes shine/glow in the dark. Best solution I think

**Comment by florkeger** [comment]
Perhaps buttons like that can emit a permanent light source?

**Comment by taukausanake** [comment]
Light source seems to be too much I feel. They aren't very large, think like LED bulbs

**Comment by matttheficus** [comment]
Fixed in #16504
