### ISSUE TITLE
Re-Integrate Noble Donor Uniform

### ISSUE THREAD

**Issue by PandaCG** [ParadiseSS13/Paradise#11644]
**Problem Description**:
The noble uniform is missing from the donor load-out (but the boots still show).

**What did you expect to happen**: 
I donated to get my outfit I made from donor items back.

**What happened instead**:
It existed previous, and the boots still show despite the uniform being missing or removed. When I donated to get it back, it was no longer there.

**Why is this bad/What are the consequences:**
It's false advertisement on the patreon page of rewards that no longer exist (https://i.gyazo.com/036aa76a21f1ad622ea44af9f65b3851.png) and I personally loved the outfit as it was a staple of all my characters.

**Steps to reproduce the problem**:
Go to the setup character > loadout > donor. Many of the items listed on the patreon are missing.

**When did the problem start happening**:
I've only rejoined recently and noticed it today. I'm not sure how long it's been happening as I can't find any reports on it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Unsure. I just re-donated when I re-joined the server.

**Comment by Kyep** [comment]
I think:
- It is this item: https://github.com/ParadiseSS13/Paradise/blob/c2a339e431d4e01e7b9c43cc1429f898c4ffedf8/code/modules/clothing/suits/miscellaneous.dm#L863
- I'm not sure why it was removed, but I suspect sprite bugs. I think at one point it had a sprite bug where it showed up on your character, but not in your hand, or vice versa.

**Comment by PandaCG** [comment]
Thanks to the help of head of staff Kyet I was able to track down the issue to a fault somewhere between these three pull requests https://i.gyazo.com/ead5ba0635e6ae6e8bc5d6cf00c36cfe.png

The path for the item still exists, along with many other donor items that have yet to be added back in (for reasons I personally don't know). It appears to be a simple oversight as Kyet suggested! The missing code must be added back here: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/client/preference/loadout/loadout_donor.dm

```
/datum/gear/donor/noble_clothes
	display_name = "Noble Clothes"
	path = /obj/item/clothing/under/noble_clothes
```

A lot of the donor info included in the image in my original post also still exists here: https://github.com/ParadiseSS13/Paradise/tree/master/code/modules/clothing and I'd reccomend looking at them to see if they're broken or not and potentially adding them back in!! Thank you!!

**Comment by Kyep** [comment]
Yeah, apparently I removed it myself in https://github.com/ParadiseSS13/Paradise/pull/11399/files and forgot I did.
I've just re-tested it in-game and it appears to work fine (tested on floor sprite, in-hand sprite and equipped sprite).
It should be relatively easy to re-add this block to loadout_donor.dm, easy first fix PR for whoever wants to do it.

**Comment by PandaCG** [comment]
Made my own pull after some help from Kyet! Not sure if I did it right, but hopefully this resolves the issue: https://github.com/ParadiseSS13/Paradise/pull/11645

**Comment by AffectedArc07** [comment]
Closed as per the PR
