### ISSUE TITLE
Lavaland Syndie base issues

### ISSUE THREAD

**Issue by Norwes1** [ParadiseSS13/Paradise#11647]
**Problem Description**:
1: The Lavaland Syndie base is supposed to be powered by a turbine. However, activating the turbine and opening its vents will spill burning plasma out and rapidly destroy the base.
2: The Syndie base lacks any sort of static turret defenses to its south-west (south of the telecomms relay room and telecomms monitoring room), and the airlock on the south side additionally lacks a "foyer" from which agents inside can shoot.

**What did you expect to happen**: 
1: This issue has repeatedly destroyed the entire base, as the nearby walls can't contain the burning plasma.
2: Aside from miners or other spawners using this as a point to attack, this area leaves the entire base far too vulnerable to simple mobs (goliaths, watchers, and even legions) destroying the base's telecomms through simply wandering into it.

**Why is this bad/What are the consequences:**
1: This issue will continue to destroy the Syndicate base until it's addressed, as unaware players attempt to activate the turbine and flood it with plasma in the process.
2: Although much less critical, this issue (and other exposed flanks on the base) leads to the entire base being left vulnerable on different sides.

**Steps to reproduce the problem**:
1: Attempt to activate the Turbine, including opening its vents. While this process would work in a vacuum, on the atmosphere of Lavaland it will instead cause a plasma flood - and the nearby plastititanium walls are not very heat-resistant.
2: Place simple mobs near the Syndie base, and attempt to fire on them from inside with either base turrets or by standing at the airlocks.

**Recommended fixes**
1: Replace the Turbine walls with heat-resistant r-walls, and remove the vent entirely.
2: Add "front steps" in front of the base's airlocks, allowing agents inside to more easily see and shoot out.

**Comment by Markolie** [comment]
https://github.com/ParadiseSS13/Paradise/pull/11643 already addresses the fire issue.

**Comment by Markolie** [comment]
#1 has been fixed. #2 I'm not sure about, because more turrets also attracts more megafauna.

**Comment by taukausanake** [comment]
Please stop pinging old PRs :cry:
