### ISSUE TITLE
Death Squad borgs are vastly underpowered

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#11657]
**Problem Description**:
What is the problem?
Death squad borgs lack several features that you would expect, making them almost inferior to gamma borgs.
**What did you expect to happen**: 
Why do you think this is an issue?
Death Squad borgs should be at least as competent as their organic counterparts.
**What happened instead**:
How is what happened different from what you expected?
No energy shield to prevent friendly fire;
No self-repair;
No self-recharge to counteract incredible power loss;
As vulnerable to damage as a regular borg
Also still incredibly vulnerable to ion (not as important)
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
As stated above, picking borg should not feel like it's actively harming the DS.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Step 1. Pick DS borg
Step 2. Get on station
Step 3. Watch as you die almost immediately
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Forever afaik
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Not really

**Comment by DesolateG** [comment]
You would probably be better off posting a thread for discussion of DS borgs here:

https://nanotrasen.se/forum/91-code-discussion/

This isn't really a bug/issue as more of a feature request.
