### ISSUE TITLE
Xeno ruined by viruses and wasted face huggers

### ISSUE THREAD

**Issue by Imotepchief** [ParadiseSS13/Paradise#11668]
**Problem Description**:
Alien Xeno are destroyed by viruses with no counter, they cannot be cured, meaning that often in a xeno antag round, the xeno's simply die off to a virus they contract while trying to acquire victims, or in some cases, when a competent virologist infects them intentionally.

The problem is further exasperated by viruses such as Lycancoughy that cause those suffering from them to cough up animals, which will draw the attention of the Xeno Facehuggers, which will latch onto the simple mobs and be used up, without causing an egg infection.
Meaning that not only are the xeno directly dying to the virus, but no replacements are being made as all the facehuggers are being consumed by the simple mobs created.

**What did you expect to happen**: 
Xeno shouldn't be affected by viruses and facehuggers shouldn't attack basic simple mobs.

**What happened instead**:
Xeno shouldn't be affected by viruses and facehuggers shouldn't attack basic simple mobs.

**Why is this bad/What are the consequences:**
It completely breaks and ruins the Xeno Alien antag.

**Steps to reproduce the problem**:
Expose a xeno to a virus that spreads either airborne or via contact.

**When did the problem start happening**:
I am unsure when it originally started occurring, but it has been a problem for a long time.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
https://gyazo.com/a24477f85095c362bada99b9f25ab579
It's pretty typical for the Xeno Antag to be robusted by a virus, generally spanish flu.

**Comment by Mitchs98** [comment]
Sounds less like a bug report and more like a feature. Perhaps the part about face huggers is, but not the virus. If anything it sounds like a viable counter to xenomorphs. God knows they need one beyond mech spam or getting unlucky and being found early. It takes a competent virus as it is to release the virus and not harm/kill crew in the process. I've rarely...or well, actually never, seen viral warfare used against them.

A non-issue and arguably intended imo given they process reagents too.

**Comment by Imotepchief** [comment]
The problem is, today there was a xeno antag event, alongside a level 7 virus event, Lycancoughy, which infected the xeno as they tried to capture crew.
The Lycancoughy killed the xeno, wasted their facehuggers, the crew interaction was absolutely minimal, which just makes it crap and pointless.

**Comment by Mitchs98** [comment]
Sounds like a case of bad luck to me? Besides that, not many people like dealing with xenos in their current form. Sometimes they're interesting to deal with, but most of the time it just results in salt due to how hilariously OP they are. Terror Spiders? Much more interesting, as you can actually combat those far easier than xenos. 

All in all. Sounds more like a bit of bad luck, and well, shit happens.

**Comment by someanonredditor** [comment]
Not that it really matters for balancing - but xenomorphs ARE suspectible to disease in the canon comics. Paul Church observes them being infected and killed by a fungal mold, and the USCM deploys biological weapons against hives with reasonable success.

It'd be more interesting to make this into a feature - make xenos immune to all diseases, then give virology a chance to produce a disease that only harms them. Balancing preserved, no accidental xeno losses, and virology made more interesting.
