### ISSUE TITLE
AI/borgs still receive air alarm alerts from the syndicate base

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11665]
see https://github.com/ParadiseSS13/Paradise/issues/11654. the bug was not fixed with the PR that closed it, synthethics still get alarms from syndi base

**Comment by Markolie** [comment]
I just tested it, and the AI nor borgs receive atmospherics alarms from the Syndicate base. So the issue mentioned there was indeed fixed.

However, it does seem that **fire** alarms still cause alerts.

**Comment by datlo** [comment]
Haha fair enough
