### ISSUE TITLE
Ghosts Randomly Stop Hearing Talk In Lavaland Z-level

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#11661]
**Problem**:
As a ghost, whether being on top of or away from someone on the Lavaland/asteroid Z-level, with or without Ghost Ears activated, things said by people in lavaland will not appear in the ghost's chat.
This seems to be client-specific as well, since others were able to hear chatter fine while they were mute on my end.

**Why is this bad/What are the consequences:**
Severely miss out on the observing experience since I can't hear people talk in Mining.

**Steps to reproduce the problem**:
Unknown. I've had it happen multiple times, but i'm not positive of the trigger.

**When did the problem start happening**:
One or two months ago. I noticed it happened on the Asteroid as well, so it's not Lavaland specific. Miners weren't usually the most entertaining to watch on the asteroid so I mostly ignored it.

**Possibly related stuff:**:
Traitor round: I could hear a Holoparasite talk just fine, but could not hear anything the host said, even in guardian talk.
Was hearing people fine on lavaland for a bit, then suddenly all chatter on the Z-level was muted, Main Station chatter was fine.
Emotes on Lavaland were still heard, just not actual talking/comms.
Xenobio was spamming dying monkeys that shift, which often breaks the chatbox for ghosts.
Reconnecting SOMETIMES fixes the problem? Doesn't stop it from occurring again.

**Comment by Xantholne** [comment]
This is due to low pressure in the area theyre in. Structures like pods create oxygen, and when their walls get destroyed they continue to create oxygen. But when you leave the area in which was provided a minor atmosphere it reverts to low pressure which is pretty much a whisper.

**Comment by Citinited** [comment]
Check your ghostradio is definitely enabled when this happens. You may have been too far away from a station intercom to hear anything.

**Comment by Pckables** [comment]
Like I said, ghost ears/radio made no difference on or off, I was even orbiting the person talking and heard nothing. Not even their Guardian Communication. I was still hearing people talk on the station Z-level while I was orbiting someone on Lavaland, but no chat from lavaland would appear in the chat box.

And this was as an observer/ghost, so low pressure making people whisper is unrelated.
