### ISSUE TITLE
Jump Boots over lava do not cause you to not get set on fire

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#11660]
**Problem Description**:
What is the problem?
Using jump boots to leap over a thin patch of lava still results in you getting set on fire.
**What did you expect to happen**: 
Why do you think this is an issue?
To leap over a thin lava river and avoid burning to death.
**What happened instead**:
How is what happened different from what you expected?
ALMOST burned to death.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Kinda ruins the whole immersion of jump boots causing you to, y'know, jump?
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Step 1. Buy jump boots
Step 2. Find thin patch of lava
Step 3. Try to jump over
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Probably whenever lavaland was merged.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
I was a diona, but I don't think that affects your odds of being SET on fire?

**Comment by Markolie** [comment]
Fixing this is fairly difficult, as outlined on /tg/ here: https://github.com/tgstation/tgstation/pull/34279.

**Comment by KasparoVy** [comment]
> +4/-3 diff

Shiiiiit.

**Comment by Markolie** [comment]
Keep in mind that PR was not actually merged but closed, because the fix would have unintended side effects.

**Comment by Burzah** [comment]
Closing this issue, as you no longer catch on fire while wearing jump boots. Thank you for making the report!
