### ISSUE TITLE
RCD is able to construct walls/floor over lava, and deconstruct lavaland rock floor and you get lava

### ISSUE THREAD

**Issue by Carthusia** [ParadiseSS13/Paradise#11667]
**Problem Description**:
What is the problem?

The RCD when it constructs a wall over lava in lavaland, and then deconstructed it leaves behind plateing, thus allowing people to create say a walkable safety bridge over to the syndicate base

It can also deconstruct lavalands ash rock floors to create more lava

**What did you expect to happen**: 
Why do you think this is an issue?

Honestly im not 100% sure it IS an issue, as i feel its just apart of the RCD creating proper foundation, or being able to rip away the surface rock, but figured it report it anyways to confirm one way or the other.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

I dont feel its really all that important, but I was told to put this potential issue here so that it can be decided if its actualy an issue.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Use the RCD set to walls, on lava, deconstruct wall, it will leave behind plating.
Use the RCD set to deconstruct the rock floor and you get more lava

Pictures showing what it looks like:

https://gyazo.com/1213fe45869219033453fc9ded7745e7

https://gyazo.com/0e545184dfc8e3c6e5d99d4259c2b7f4

https://gyazo.com/f3dcebbf068ca60f23805927c82414e2

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
It has probably been a thing since lavaland was implimented.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Markolie** [comment]
Thank you for the very detailed report! 

The RCD is indeed supposed to build over lava. It's one of the ways of dealing with lava

The basalt floors always have lava underneath them as well, so if you use an RCD to build over them and then remove the wall the resulting lava is also intentional.

**Comment by Carthusia** [comment]
Cool, great to know its intended.

**Comment by Shadow-Quill** [comment]
@Anasari NAB
