### ISSUE TITLE
Disk Compartmentalizer wont accept disks

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#11671]
**Problem Description**:
What is the problem?
It won't take plant data disks, which is its function. 
I did discover that it will take plants however, which means its another smart fridge instead?

**What did you expect to happen**: 
Why do you think this is an issue?
Because it was made to store disks?

**What happened instead**:
How is what happened different from what you expected?
It won't take them it accepts plants instead 

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
A giant pile of unsorted plant data disks

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Try to put in a plant data disk, it refuses to accept it.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Just today, the third of June

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Its related to the Diona in lava land, since that is the only place Ive seen the compartmentalizer

**Comment by Xantholne** [comment]
We dont actually have this as a fully functional botany machine as I recall. It was kinda just there in the seed ship due to direct port. Thus the invisible look unless that's been fixed by now.
