### ISSUE TITLE
Cryogenic Oversight Computer Deconstruction Problem

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#11678]
**Problem Description**:
If the Cryogenic Oversight Console gets deconstructed and reconstructed, it can't be reconnected to the pods (I believe). 

**What did you expect to happen**: 
For the console to connect to the pods and allow access to the items within.

**What happened instead**:
Items were not accessible, and when forced to despawn the items instead popped out over the pod along with a hilarious and creepy limb doll.

**Why is this bad/What are the consequences:**
Traitors or Command who wish to access the items in there are unable to if the console is deconstructed or destroyed. Additionally, if someone is despawned, ANYONE can take the items as they are in the open.

**Steps to reproduce the problem**:
1. Deconstruct/destroy the Cryogenic Oversight Console
2. Attempt to view logs (make sure something is in there first, so you can see they're not there)
3. Despawn someone and look at the creepy caricature of a person pop out.

**When did the problem start happening**:
Not sure. I noticed it once in the past but didn't consider making a report about it as it seemed like a one off issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing that I can think of. Here's a screenshot of the issue though.
![image](https://user-images.githubusercontent.com/38596550/58890174-bc6a6980-86af-11e9-8013-9e0839e2398f.png)

**Comment by Citinited** [comment]
Interesting... cryogenics console destruction is something I've looked into before (mostly to see if it can be abused) but I don't remember all the items popping out like that. I think this is a recent change?

**Comment by DGamerL** [comment]
In an unknown PR, the ability for cryogenic consoles to be deconstructed has been removed, thank you for making the report!
