### ISSUE TITLE
Ashwalkers can pilot mechs

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11685]
**Problem Description**:
Ashwalkers are able to pilot mechs (Ripley at least but I assume all others)

**What did you expect to happen**: 
Cave lizards shouldnt have the faculty to pilot mechs

**What happened instead**:
DRILL INVADERS BASE REEEEEEEE

**Why is this bad/What are the consequences:**
Was told by admins not to use the mech and I destroyed it instead when I reported it so I assume its not intended to work that way

**Steps to reproduce the problem**:
Spawn as an ashwalker, find a mech, enter it

**When did the problem start happening**:
Lavaland PR

**Comment by Markolie** [comment]
This is intentional (or at least not unintended).

**Comment by datlo** [comment]
Closing this then since its more of a feature request
