### ISSUE TITLE
Humans have up to 10 normal fingers but have an infinite number of negative fingers

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11680]
**Problem Description**:
As a human, I can do `*signal-` followed by a negative number of any size, resulting in confusion

![image](https://user-images.githubusercontent.com/18459142/58898034-95cd2280-86f1-11e9-87d5-881c7cd30515.png)

**Any other info**
Also works with aliens doing `*sign-`

**Comment by KasparoVy** [comment]
Fuck that's so funny
