### ISSUE TITLE
MAJOR Tesla can get Wormhole'd

### ISSUE THREAD

**Issue by Muhdi345** [ParadiseSS13/Paradise#11689]
**Problem Description**:
Tesla can get teleported through a wormhole, possibly the singularity too, maybe. I don't need to explain how bad this is.

**What did you expect to happen**: 
Get wormholes event, possibly get inside the engine containment through the wormholes, and NOT THE ENGINE COMING TO ME 

**What happened instead**:
Tesla got teleported all over the station. Pretty much ending the round.

**Why is this bad/What are the consequences:**
Since the tesla moves regularly, the possibility of going inside a wormhole is significant. 

**Steps to reproduce the problem**:
Have a tesla, engage wormholes. Laugh your ass off.

**When did the problem start happening**:
Unknown

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing else comes to mind.

**Comment by Couls** [comment]
#11664
