### ISSUE TITLE
Couple of Surgeries are Broken

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1169]
Currently, there's two surgeries that are still broken:

- Limb re-attachment
- Head re-attachment

Very similar; basically, you don't have to go through the necessary steps of preparing a limb for being roboticized/a head to be re-attached; you just click a decapped head onto a headless body and after a few short seconds, the head is re-attached...same goes for limbs; just click the robotic limb on the limb missing and it'll attach, regardless of being prepped or not.

**Comment by FalseIncarnate** [comment]
Personally I like that you can quite literally just slap a new robotic limb on, at least for IPCs. If we could somehow retain that for them but fix the issue for other races, I'd really like that.

Being able to just stick the head back on like a piece of chewed gum though doesn't make sense for anyone (except maybe Slimes, who are effectively giant wads of gum). Lots of stuff with nerves and spines that would need to be handled for that.

**Comment by Zuhayr** [comment]
This was part of the limb rewrite, it isn't a bug. Can't do surgery on a non-existant limb, so the steps were just removed.

**Comment by Fox-McCloud** [comment]
Oh. Thanks for clearing that up then; I figured that the surgery would somehow be maintained given how ridiculously easy it is to replace limbs now (but now lengthy it is to repair bones).

Thanks for clearing it up.

**Comment by Zuhayr** [comment]
I may be changing it so that you need to implant sockets into a meat chest before you can attach a robolimb, but that will be some way down the track. I'm sure you can port it if you don't decide to just do it yourselves.
