### ISSUE TITLE
Ripleys not sped up on Lavaland

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#11707]
**Problem Description**:
What is the problem?
Ripley speed is not increased on lavaland as it was with the asteroid.
**What did you expect to happen**: 
Why do you think this is an issue?
To have Ripleys act the same across the different mining zones.
**What happened instead**:
How is what happened different from what you expected?
Using a Ripley is painful on lavaland, not to mention useless.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Given the relative effort between getting normal mining tools and a Ripley, it should be at least as effective, if not more.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Step 1. Get Ripley
Step 2. Take to lavaland
Step 3. Realize you still move at snailspeed
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Probably whenever lavaland was merged.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Lavaland also lacks the special airtight flaps for a mech-bay that the asteroid had.

**Comment by Markolie** [comment]
Will be fixed in https://github.com/ParadiseSS13/Paradise/pull/11694 or https://github.com/ParadiseSS13/Paradise/pull/11633, whichever goes through first.
