### ISSUE TITLE
Poddoors on escape shuttle move each time it moves

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11708]
**Problem Description**:
Each time the escape shuttle moves, any poddoors I placed on it get moved. A 4 tile door moved 3 tiles up, a 2 tile door moved 1 tile up each time the shuttle transitions a z level.

**What did you expect to happen**: 
for pod doors to stay where they are.

**What happened instead**:
they moved.

**Why is this bad/What are the consequences:**
I wanted to make a cool shuttle with a pod docking port so the sec pod pilot can get in there while guarding the shuttle from space.

**Steps to reproduce the problem**:
open map editor, place a pod door on the shuttle, start a round. Since the shuttle immediately moves to z2, jump to z2 and see the new door location.

**When did the problem start happening**:
No clue

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The white ship has pod doors and those don't work, so I dunno what's special about the escape shuttle.

**Comment by taukausanake** [comment]
Oh, so this is a map editing issue. That's interesting. Yeah I would like pod doors on an escape shuttle. Imagine a shuttle that only allows you to enter if you have a spacepod. I'd make that
