### ISSUE TITLE
Beating dead corpses with maximum brain damage gives brain damage death messages

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11709]
**Problem Description**:
If I beat up a corpse that died of brain damage then I can cause it to display the `X goes limp, their facial expression utterly lifeless` message over and over (see pic)

**What did you expect to happen**: 
Beating dead bodies shouldn't cause unnecessary messages to appear

**What happened instead**:
They became super limp

**Why is this bad/What are the consequences:**
It's not game breaking it's just funny

**Steps to reproduce the problem**:
1. Cause death by brain damage.
2. Punch them lots until this message appears

![image](https://user-images.githubusercontent.com/18459142/59153241-c80db580-8a4c-11e9-9525-f525b82d258b.png)

**When did the problem start happening**:
Probably since newcrit? Not sure
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Noticed this on a test server but no reason to think why this wouldn't be on live too.

**Comment by KasparoVy** [comment]
LMFAO, that's pretty hilarious man. Especially with the bible.

**Comment by PidgeyThePirate** [comment]
Tried to replicate this and couldn't. It's probably been fixed.

**Comment by AffectedArc07** [comment]
Cannot be reproduced. Feel free to re-open this at a later date if you can reliably reproduce this issue
