### ISSUE TITLE
Space pods shooting self(mining KA burst)

### ISSUE THREAD

**Issue by RadiantFlash7** [ParadiseSS13/Paradise#11703]
**Problem Description**:
If you move forward in any direction and fire a mining KA shot thing, You will hit your own pod rather then what you are moving towards.

**What did you expect to happen**: 
Being able to move forward and still fire.

**What happened instead**:
Shot my own pod, knocking a large hunt of integrity off of it.

**Why is this bad/What are the consequences:**
Makes pod useless for mining, and could easily kill you if you weren't aware.

**Steps to reproduce the problem**:
Install mining weapon system on pod. Drive forward while firing.

**When did the problem start happening**:
No idea when it started.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I had a pod built on lavaland. I couldn't mine rocks without hitting myself, until I realized I have to stop moving to fire, lest I blow up my pod.

**Comment by iantine** [comment]
https://github.com/ParadiseSS13/Paradise/issues/8341 Reported here.
