### ISSUE TITLE
Lavaland doesn't have enough of suits on highpop

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#11710]
**Problem Description**:
You can get more miners that there are suits on the station.

**What did you expect to happen**: 
For every miner to have a suit.

**What happened instead**:
There were 5 miners, but only 4 suits.

**Why is this bad/What are the consequences:**
Having 5 miners, but only 4 of which can go out and mine.

**Steps to reproduce the problem**:
Get Highpop
Notice that there are 5+ miners
Only 4 suits

**When did the problem start happening**:
Since lavaland was merged in

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

**Comment by datlo** [comment]
QM can order additional miner supplies. Also I dont think theres more slots than suits, probably the HOP just hired more?

**Comment by dovydas12345** [comment]
I am not certain about that, but they did say they were missing a suit at round start? Could be possible.

**Comment by MrMagolor** [comment]
The issue here lies in the fact that mining conscription kits don't contain a suit.

**Comment by SteelSlayer** [comment]
Fixed in https://github.com/ParadiseSS13/Paradise/pull/11674, as there are now 8 explorer suits

**Comment by dovydas12345** [comment]
Closing since it is fixed now.
