### ISSUE TITLE
"Teleport" and "Orbit" verbs no longer allow autocompletion

### ISSUE THREAD

**Issue by Visscera** [ParadiseSS13/Paradise#11720]
**Problem Description**:
Before some recent updates (one adding ghost GUI and replacing Following with Orbiting, I believe) the Teleport and Follow verbs had an autocompletion feature. You could type "Teleport synd", press [Space] (IIRC?) and a floating pop-up showed up a list of possible locations that included "synd" in their name. This was very helpful as you could quickly find the desired area/entity instead of looking through a looong, potentially unsorted list of all possible ones. You could still see this behavior in some admin verbs such as "Jump-To-Area" and "Jump-To-Mob", but us ghosts without adminpowers no longer have access to this useful feature. I'm surprised this wasn't reported before!

**What did you expect to happen**: 
Autocompletion option working well, as before, allowing to quickly find the desired entity to follow or area to teleport to instead of painstakingly scrolling through a long, unsorted list.

**What happened instead**:
Teleport/Orbit verbs no longer have autocompletion in text mode.

**Why is this bad/What are the consequences:**
It takes much longer now to find someone/something as a ghost, and this is very sad. I am sad.

**Steps to reproduce the problem**:
1) Enter text mode with [Tab], if you were in hotkey mode before. The text prompt below the game area will turn red.
2) Type "Teleport synd" and press [Space]. Nothing happens! Same thing with the Orbit verb.
3) Now erase that, type instead "Jump-To-Area synd" and press [Space]. If you're an admin, you will be immediately prompted with a list of suggested areas - just like Teleport and Follow verbs used to work before.

**When did the problem start happening**:
Recent Paradise updates... When ghost GUI was added, I think?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Don't think there is anything more to tell!

**Comment by Tayyyyyyy** [comment]
The way the new verbs are written doesn't allow for byond autocompletion, but I'm adding an autocomplete input in #11570. The nice thing is that it'll be useful for things that can't be tied to verbs, like crew pinpointers for example.
