### ISSUE TITLE
Going through any kind of portal makes you unable to move after

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#11727]
**Problem Description**:
You get stuck in place and unable to move when you go through any kind of portal. No matter if its the teleporter or any kind of other teleporting portal.

**What did you expect to happen**: 
To be able to move after teleporting

**What happened instead**:
People were unable to move after teleporting

**Why is this bad/What are the consequences:**
People get stuck in place and unable to move after teleporting using a portal

**Steps to reproduce the problem**:
1. Go through a portal
2. Be unable to move

**When did the problem start happening**:
Started happening today as far as I know

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
If you reconnect it goes away and you are able to move.

**Comment by Markolie** [comment]
You sure there weren't any other circumstances in play? Teleporting seems to work fine for me.

**Comment by MarsM0nd** [comment]
Happened again in another round. Teleportation was done with a bluespace wormhole projector, on portal inside the station, one outside, they were unable to move when they moved through the inner portal. They were able to return by clicking on the portal they were unable to move off. After returning, they were still unable to move.
The teleportation also left the sparks effect on the tiles, one tile was a lattice in space, the other a normal tile.

**Comment by MarsM0nd** [comment]
What might also be related is that you can't move after the nuke goes off, and you survive it, reconnect in that small timeframe and waking up restores movment, a plain admin-rejuv doesn't.

**Comment by dovydas12345** [comment]
I am not exactly certain what was special about that round to make the portals break, but I couldn't make it appear again. All I know is that multiple people were frozen in place when they went through a portal. Seems like it has happened again, just like Marsmond said.

**Comment by Couls** [comment]
Seems to break when going through two portals multiple times in a short period and it breaks it the whole shift

**Comment by dovydas12345** [comment]
It happened again and I think Coul was correct?
