### ISSUE TITLE
syndicate depot alert levels goes up by itself

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11737]
**Problem Description**:
What is the problem?
syndicate depot alert levels go up by themselves, most likely because of syndie mobs hitting airlocks next to them

**What did you expect to happen**: 
Why do you think this is an issue?
To be able to explore depot, without alert raising itself for no reason.

**What happened instead**:
How is what happened different from what you expected?
Syndie officers/qm hit airlocks, get spooked by themselves, and report it, raising alert level.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
You can't check even half of outside rooms in depot, before alert raises itself to red.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Enter depot, kill some syndicate soldiers in outside room, without raising alert level.
2. Level randomly goes up.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Since AI related pull request being merged

**Comment by Kyep** [comment]
Thank you for reporting this on Github.
It is a known bug. There's a fix already written for it, included in the PR I just linked.
