### ISSUE TITLE
Quantum-entangled paper fax

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#11736]
**Problem Description**:
Faxes sent to CC seem to just open the paper that was sent.

**What did you expect to happen**: 
The fax to be copied.

**What happened instead**:
You get a reference to and open the original, even if it changes.

**Why is this bad/What are the consequences:**
Faxes that got destroyed on the station can't be read, and if modified also recieve that modification.

**Steps to reproduce the problem**:
Get a long range fax and a paper, fax it, remove it from the fax, edit it to see the edits in the fax panel, delete it by any means to make it unviewable.

**When did the problem start happening**:
Not sure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nonthing out of the ordinary, happened on different rounds.

**Comment by 1080pCat** [comment]
A newer report of this issue exists, with slightly more information. #26760
And as this one has already been tagged with the stale tag for some time now, this'll be closed in favor of the newer one.
