### ISSUE TITLE
Water Tanks cannot be damaged by mech gunfire

### ISSUE THREAD

**Issue by Ctr-Truescreen** [ParadiseSS13/Paradise#11742]
**Problem Description**:
Water Tanks are left undamaged when pelted with mech gunfire

**What did you expect to happen**: 
Shoot Water Tank a couple times, it gets destroyed.

**What happened instead**:
Water Tank took no damage at all.

**Why is this bad/What are the consequences:**
Terror Spiders and other shifty individuals can use this to block mech shots.

**Steps to reproduce the problem**:
Step 1. Obtain Durand with LMG
Step 2. Locate Water Tank
Step 3. Fire several volleys of bullets at Water Tank
Step 4. Water Tank survives
Step 5. Profit

**When did the problem start happening**:
Started happening 22.06.2019, 22:18 GMT +1, during a round where terror spiders infiltrated Robotics. The terror spiders reteated to Xenobio after discovering we had mechs, (Read they picked the wrong robotics department.) A red terror spider used a Water Tank as a shield.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Not much, i guess. Please fix.

**Comment by Couls** [comment]
Fixed in #11528
