### ISSUE TITLE
Viro Traitor Hypospray

### ISSUE THREAD

**Issue by EldrinKanthos** [ParadiseSS13/Paradise#11746]
**Problem Description**:
The traitor hypospray is supposed to look like a pipette, but act as a hypo. It just is a pipette. no extra functions.

**What did you expect to happen**: 
I expected to inject my target with virus. Instead I just dripped it on them like a pipette.

**What happened instead**:
I expected an injection and maybe more than 1u storage. Instead was pipette.

**Why is this bad/What are the consequences:**
It is bad because it wastes telecrystals and leaves the traitor possibly revealed.

**Steps to reproduce the problem**:
Play Viro, be traitor. Get the traitor hypo.

**When did the problem start happening**:
Not sure. But happened this last round.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Autotraitor mode I believe. I was in maint being a lurk and tried to hypo my target in the middle of conversation and instead dripped it in their eyes really suspicious like.

**Comment by farie82** [comment]
I believe that the person you tried to inject was protected at the point you aimed at. For instance the body if he had a hardsuit on or such. If the prior injection fails it'll continue to behave like a normal pipette

**Comment by EldrinKanthos** [comment]
I tested on a lab monkey and it dripped inti eyes reguardless of targeting

**Comment by farie82** [comment]
Tested it locally on the newest code. Works for me. Injected both myself and a monkey with it.

**Comment by AffectedArc07** [comment]
Cannot be reproduced. Feel free to re-open this at a later date if you can reliably reproduce this issue
