### ISSUE TITLE
Bees still apply toxins even if they nuzzle a target

### ISSUE THREAD

**Issue by Ionward** [ParadiseSS13/Paradise#11751]
**Problem Description**:
Fairly self explanatory, a sentient bee was on station and was being friendly to people on the station, and it ended up that everyone they nuzzled had to run to medbay to deal with a massive dose of toxins.
**What did you expect to happen**: 
I expected to sit with a bee nuzzling me.
**What happened instead**:
I had massive toxin damage!
**Why is this bad/What are the consequences:**
Aside from just being annoying for the bee trying to be cute and nice, if it wasn't a problem we could identify easily ingame, a source of a massive amount of toxins that no one pays attention to is kind of on par with some antagonist tools.
**Steps to reproduce the problem**:
Sentient bee clicks an organic on help intent a bunch, observe toxins rise

**When did the problem start happening**:
After a sentience event, presumably, and I was unaware of it until today.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
We got a healing virus after finding out the bee was accidentally giving out toxins, and I think the virus had toxcomp, so there may be some interference there.

**Comment by KasparoVy** [comment]
That's some tough love lmao. What a silly bug

**Comment by Pckables** [comment]
Terror spiders do the same thing.

**Comment by Citinited** [comment]
Terror spiders one is fixed by #11724
