### ISSUE TITLE
Emergency NanoMed Vendor locked access

### ISSUE THREAD

**Issue by Ionward** [ParadiseSS13/Paradise#11755]
**Problem Description**:
The emergency nanomed vendors (the little wall units in cargo, dorms, medbay and others) have locked access for everyone, both in the public places and doctors are locked out of their medbay ones. 

**What did you expect to happen**: 
I expected to be able to heal a little bit at the dorms emergency nanomed

**What happened instead**:
*Access DENIED* and I'm left bleeding and sad.

**Why is this bad/What are the consequences:**
Medicine vendors that can be useful for everyone to treat minor injuries not dispensing possibly lifesaving aid is a workplace hazard! /s 
no but the vendor should vend, thats its whole purpose

**Steps to reproduce the problem**:
Be doctor in medbay or anyone else and try vending anything out of an emergency nanomed.

**When did the problem start happening**:
I'm not sure exactly when but these used to work at one point, it has to be somewhat recently.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Seemed pretty consistently access-locked from the rounds I've tried it.

**Comment by JohnBigless** [comment]
This has been quite the problem sometimes. Coders, pls fix.
