### ISSUE TITLE
Syntax Error in SQL Schema

### ISSUE THREAD

**Issue by MrDj200** [ParadiseSS13/Paradise#11758]
**Problem Description**:
SQL Schema syntax error

**What did you expect to happen**: 
Because it doesnt work

**What happened instead**:
It doesnt work

**Why is this bad/What are the consequences:**
It doesnt work (at least the last table)

**Steps to reproduce the problem**:
execute `paradise_schema.sql` in sql

**When did the problem start happening**:
When I first tried the script today

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
https://github.com/ParadiseSS13/Paradise/blob/master/SQL/paradise_schema.sql#L549 this line misses a ','

**Comment by Markolie** [comment]
https://github.com/ParadiseSS13/Paradise/pull/11692 will fix that.

**Comment by Kyep** [comment]
@AffectedArc07 This can be closed.
