### ISSUE TITLE
Refill doesn't work on AI Sat Air Alarms

### ISSUE THREAD

**Issue by florkeger** [ParadiseSS13/Paradise#11750]
**Problem Description**:
What is the problem?
Refill in all AI Sat rooms doesn't seem to be working. Siphoning is normal, though the second you want to refill the room, the pressure values don't rise.

**What did you expect to happen**: 
Why do you think this is an issue?
Because the Refill is supposed to work in order to stabilize the atmosphere without having to rely on other players.

**What happened instead**:
How is what happened different from what you expected?
Because it's broken.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because the AI Satellite can be pretty vulnerable, and fixing atmospherics issues should be possible to be handled like that without issues.

**Steps to reproduce the problem**:
Click an Air Alarm in the AI Sat, press Refill, watch how nothing changes.

**When did the problem start happening**:
I don't remember it not working as I never used it before.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing e.se

**Comment by Muhdi345** [comment]
Are you sure you pumped air pressure into the pipes first? I don't remember clearly, but the pipes in AI Sat start out empty. 

There's 1 or 2 air canisters in the AI sat and pumps below them, connect the canisters to the connectors if they aren't already and enable the pumps. It should work then.
