### ISSUE TITLE
Construction Permits consumed even when failed to use.

### ISSUE THREAD

**Issue by JKnutson101** [ParadiseSS13/Paradise#11759]
**Problem Description**:
Construction Permits disappear when you select 'Mark new area' and the area is invalid for whatever reason. Also when prompted to name the new area, if you choose to cancel, the permit disappears.

**What did you expect to happen**: 
I expected the permit to be usable on failure or cancellation.

**What happened instead**:

Instead, the permit disappears if the new area isn't airtight or one chooses to cancel usage. 

**Why is this bad/What are the consequences:**
This is bad because a simple mistake of forgetting to seal a room, or deciding against marking 
the area could lead to a lot of wasted time trying to get a new permit.

**Steps to reproduce the problem**:
Take a construction permit. Try to mark a new area in an invalid area, or try to mark a valid area and select cancel.

**When did the problem start happening**:
No idea how long this has been a thing, construction permits aren't used with a high frequency.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing else to say about it.

**Comment by Citinited** [comment]
https://github.com/ParadiseSS13/Paradise/blob/936bde2da4315a0b3c71ef149b1ad53b81c0e9f2/code/game/objects/items/blueprints.dm#L67

This is the offending line - it should be a simple enough fix to check that `create_area()` did its thing before deleting itself
