### ISSUE TITLE
The wizard round doesn't end if a wizard or his apprentice is put into a MMI, cyborg

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#11766]
**Problem Description**:
The round doesn't end when both wizard and his apprentice dead as long as one of them is put into a cyborg, MMI.

**What did you expect to happen**: 
I expected the round to end when the final wizard was killed.

**What happened instead**:
Round didn't end because the apprentice was inside of a MMI.

**Why is this bad/What are the consequences:**
People expect the round to end when wizard dies, but it doesn't, because people in MMI are still counted as alive.

**Steps to reproduce the problem**:
1. Become a wizard with a apprentice or another wizard.
2. Kill one of them.
3. Put the one you killed inside of a MMI.
4. Kill the rest.
5. Round doesn't end

**When did the problem start happening**:
Probably has always been happening, since the gamemode was added.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It probably works the same way for nukies as well. Since when a syndicate borg is alive or just disabled and not destroyed the round still goes on. On ragin mages round if a wizard is borged or put into a MMI new wizards don't spawn because it counts the borged one still as alive.

**Comment by taukausanake** [comment]
I want a wizard borg now. *Wizard dies, leaves brain, dumb Roboticist borgs it, ET NATH BITCH I'M A WIZBOT NOW*
