### ISSUE TITLE
Fuel tank explosions ignore Fire Immune armor

### ISSUE THREAD

**Issue by SpinningSalami** [ParadiseSS13/Paradise#11763]
**Problem Description**:
What is the problem?
Fuel tank explosions bypass fire immune armors and burn the wearer.

**What did you expect to happen**: 
Why do you think this is an issue?
Fire proof suits like drake armor and atmos suits should be immune to all types of fire.

**What happened instead**:
How is what happened different from what you expected?
You should be immune to all fire when wearing fireproof clothing.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
This makes fireproof armor inconsistent.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Wear slime fireproofed clothing, drake armor, or an atmos hardsuit. Stand within fireball range of an exploding fuel tank.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Don't know. Probably when fox updated the fuel tanks here #11078

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Muhdi345** [comment]
I don't know. The thing is, you are extremely resistant to heat BUT not immune. Although wizard fireballs never increase body heat with fireproofed clothing like welderbombs do, so there's that too....

Welderbombs raising temperatures over 35000 Kelvin is ludicrous now that I think a little further.

**Comment by matttheficus** [comment]
Fixed by #15944
