### ISSUE TITLE
Color blidness doesn'y work on photos

### ISSUE THREAD

**Issue by michiel-schoofs** [ParadiseSS13/Paradise#11778]
**Problem Description**:
I chose the disability colourblind however I was able to see photographs taken with a camera in full colors. 

**What did you expect to happen**: 
The photographs should show up in black and white. 

**What happened instead**:
The photographs were in color

**Why is this bad/What are the consequences:**
It's not necessarily bad just a bit odd. 

**Steps to reproduce the problem**:
Take a photograph with colourblind character and look at it.

**Comment by taukausanake** [comment]
Oooo, this is going to be interesting. However this is a feature request as there are a few things color that colorblind can still see. I think wire colors are one of those things.

Is there a gray scale filter BYOND can push images through? It would be a good addition
