### ISSUE TITLE
Terror Spider Gateway

### ISSUE THREAD

**Issue by Muhdi345** [ParadiseSS13/Paradise#11782]
**Problem Description**:
I don't know how to exactly explain it. But it seems like the gateway doesn't properly start itself. The Queen spider does not lay eggs, the death of the white spider does not open the command blast doors and the rest of the spiders don't lay webs either.

**What did you expect to happen**: 
That the gateway isn't a gigantic snore fest that can only be completed with an emag.

**What happened instead**:
Once the initial spiders are dead, there are no threats leftover. Making it pretty much the empty station gateway.

**Why is this bad/What are the consequences:**
The Terror Spider Gateway is the only gateway left that's worth doing. Since it's unlikely we'll get Wild West back at this point.

**Steps to reproduce the problem**:
Start a round with the Terror Spider Gateway, look at the spiders and see no webs, no eggs, nothing.

**When did the problem start happening**:
I think it happened after the lavaland merge. I don't know for sure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
![spooders](https://user-images.githubusercontent.com/47270900/60572589-39076b00-9d76-11e9-88b0-95fe3e58886f.png)

**Comment by Couls** [comment]
I think #11450 is the culprit

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/issues/11506

**Comment by Emanthealmighty** [comment]
This really needs to be fixed... it ruins any sort of mob that is supposed to do things on its own, takes away a lot of possibilities.
