### ISSUE TITLE
Game freezes when interactine with PDA or terminals.

### ISSUE THREAD

**Issue by Radithor** [ParadiseSS13/Paradise#11785]
**Problem Description**:
What is the problem?

The game freezes when I interface with terminals or my pda. I have uninstalled beyond, refreshed caches...

**What did you expect to happen**: 
Why do you think this is an issue?

I can't access anything that is a machine or has a menu.

**What happened instead**:
How is what happened different from what you expected?

I open a terminal screen, game freezes when I expect to be able to select functions.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Noone can play the game in this state, this issue takes a whole chunk out of the game.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

-Opened my PDA, went to messages...freeze.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

One or two weeks ago, I tried to ignore it. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/issues/13728 may fix this

**Comment by AffectedArc07** [comment]
Likely fixed by TGUI.
