### ISSUE TITLE
RESOURCE_URLs / preload_rsc does not work

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#11780]
**Problem Description**:
The RESOURCE_URLs config setting that is meant to enable web delivery of the game's cached RSC file, does not work.

**What did you expect to happen**: 
1) Set RESOURCE_URLS http://nanotrasen.se/paradise.rsc.zip in config.txt
2) Clear byond cache
3) Fire up 'Resource Monitor' windows program, switch to 'overview' then in the 'network' box, sort by 'Receive (B/sec)'.
4) Re-open BYOND, reconnect to game server
5) Observe that there is a 100M download in approximately 10 seconds from an IP that is different to the game server (IE: is cloudfront/website)
6) Successfully connect to the game faster than normal

**What happened instead**:
During step 5, the game downloads the .rsc or .rsc.zip from the actual game server, then initiates a completely unnecessary second download, in the background, re-downloading the same file from the website

**Why is this bad/What are the consequences:**
I want to use RESOURCE_URLS / preload_rsc to have clients download the .rsc or .rsc.zip from a web server instead of the game server. Currently, that doesn't appear to be possible - it downloads twice (game server first) which is slower and negates the point of the exercise.
This is bad because I suspect that serving >100MB file downloads to clients who connect midround is a major cause of lag spikes during normal play for everyone currently connected.

**Steps to reproduce the problem**:
See above

**When did the problem start happening**:
Unknown, possibly broken for years

**Extra Information**:
In the code, if you change:
 preload_rsc = 1 // This is 0 so we can set it to an URL once the player logs in and have them download the resources from a different server.    
To:
preload_rsc = "http://nanotrasen.se/paradise.rsc.zip"

And comment out this block:
if(config.resource_urls)
 preload_rsc = pick(config.resource_urls)
else preload_rsc = 1 // If config.resource_urls is not set, preload like normal.

Then connect to the server, it will download the rsc/rsc.zip from the correct web URL.... but it never actually launches the game.

So, right now, the .rsc/.rsc.zip files are there, regenerated with every server code compile, but the game code itself doesn't seem to support actually using them, which is a shame. If we could start using them, initial download would be faster (up to 20x faster) and it might help resolve some of our lag issues with clients connecting midround.

Related:
Explanation of preload_rsc values (Byond docs): 
![preload_rsc_explanation](https://user-images.githubusercontent.com/16434066/60563883-0c8b2900-9d4d-11e9-821f-9c59ba1633d9.png)

TG's system: 
https://github.com/tgstation/tgstation/search?q=preload_rsc&unscoped_q=preload_rsc

Explanation of TG's system:
https://github.com/tgstation/tgstation/blob/master/README.md
(scroll to: "WEB/CDN RESOURCE DELIVERY")

**Comment by Couls** [comment]
Gonna see if I can get this working with our code
