### ISSUE TITLE
If Cult Target Cryos, is listed as Gibbed, Cult Auto-Fails

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#11796]
**Problem Description**:
Three Point Fourteen, the Magistrate and the cult's sacrificial target, went into Cryo.

**What did you expect to happen**: 
The cult would get a new target.

**What happened instead**:
He was listed as "Gibbed" and the cult objective auto-failed.

**Why is this bad/What are the consequences:**
A cult round became unwinnable because someone Cryo'ed.

**Steps to reproduce the problem**:
1. Be Cult target.
2. Cryo.
3. Check the end-of-round antag listings.

**When did the problem start happening**:
Occurred on July 6th, 2019.

**Comment by Kyep** [comment]
@Aurorablade

**Comment by datlo** [comment]
I wish I knew this would do this and that i was the target before I cryod :(
