### ISSUE TITLE
Engineering Shuttle Mid-Transit Spacing warps you into Lavaland Wall

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#11790]
**Problem Description**:
If you're space mid-transit from the Engineering Shuttle, you get warped into solid rock on Lavaland.

**What did you expect to happen**: 
I expected to be floating in space instead.

**What happened instead**:
I got warped into a wall in Lavaland.

**Why is this bad/What are the consequences:**
I had to Ahelp to get out of the wall before I suffocated to death.

**Steps to reproduce the problem**:
1. Put Engineering Shuttle into transit.
2. Get spaced mid-transit.

**When did the problem start happening**:
Unknown

**Comment by Deelite34** [comment]
I can confirm, but same thing did happen with mining shuttle instead.

**Comment by Bookdrizzt** [comment]
Same thing happened with Escape Shuttle, but not on Labor Shuttle, oddly enough.

**Comment by Sirryan2002** [comment]
engineering shuttle was removed, IIRC this is also working as intended.
