### ISSUE TITLE
Teleport ghost verb doesnt work to some areas

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11803]
**Problem Description**:
The new 'teleport' ghost verb doesnt teleport to the wizard den (and possibly other areas). The area is shown on the list but selecting does nothing

**What did you expect to happen**: 
Teleport to wizard den

**What happened instead**:
Nothing

**Why is this bad/What are the consequences:**
Not functionning properly

**Steps to reproduce the problem**:
Be ghost, try to teleport to wizard den

**When did the problem start happening**:
Today, yesterday? Extremely recent. Cant pinpoint the PR that changed the ghost teleport verb.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Happened on live today.

**Comment by Ty-Omaha** [comment]
tried this, no runtime appeared.

didn't work for me either

**Comment by Arkatos1** [comment]
Another area that does not work is Mr. Chang's, which gives us a valuable clue why - both Wizard's Den and Mr. Chang's have ' character, which does not show in the list and therefore the teleportation to these areas does not work properly. Actually, nothing after the ' shows - in the new list, Wizard's Den is marked only as "Wizard".
