### ISSUE TITLE
If you are a larva and is pipe walking, if you go thru a valve the pipes at the other side will be invisible.

### ISSUE THREAD

**Issue by sugoikore** [ParadiseSS13/Paradise#11813]
**Problem Description**:
If you are pipe walking as a larva (not sure about other stuff that can also walk inside pipes) the path at the other side of the valve will be invisible, it's allways the other side.

**What did you expect to happen**: 
You should be able to see all the route

**What happened instead**:
The path was invisible.

**Why is this bad/What are the consequences:**
It's hard to walk around the map

**Steps to reproduce the problem**:
Alien larva, went into the vents and walked thru a valve. Screenshot added.

**When did the problem start happening**:
Not sure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
![image](https://user-images.githubusercontent.com/26089259/60936609-08f32700-a2a4-11e9-9e7a-cc458ab48fda.png)
![image](https://user-images.githubusercontent.com/26089259/60936640-1a3c3380-a2a4-11e9-89d7-e8ff20625cec.png)
![image](https://user-images.githubusercontent.com/26089259/60936666-2e803080-a2a4-11e9-85df-21382a678f1d.png)

**Comment by iantine** [comment]
https://github.com/ParadiseSS13/Paradise/issues/10439 https://github.com/ParadiseSS13/Paradise/issues/7389 Related- error is that if you are any vent crawling mob, you can't switch between pipenets and have your visible pipe update to the new pipe.

**Comment by warior4356** [comment]
This is resolved in PR #14432
