### ISSUE TITLE
Paperwork Field Bug

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#11811]
**Problem Description**:
What is the problem?
Making fields in paperwork always makes new lines, which makes paperwork look a lot less appealing than it used to.
**What did you expect to happen**: 
Why do you think this is an issue?
For [field] to create a standard field without being a new line.
**What happened instead**:
How is what happened different from what you expected?
My paperwork forms, and those on the wiki as well, look considerably less appealing.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It really ruins the HoP/NT rep game when your forms/faxes don't look top-notch
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Try to write paperwork with a [field] or two, for example from the Example Paperwork page on the wiki
2. Notice that it looks awful
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
I first noticed it today: possibily coincides with some other text-based change?
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
I didn't try making new paperwork, only copy-pasting pre-existing samples.

**Comment by Tayyyyyyy** [comment]
This is an issue with #11562. This is the next thing that I'll be looking at to fix.
