### ISSUE TITLE
AI does not have any intent.

### ISSUE THREAD

**Issue by Emanthealmighty** [ParadiseSS13/Paradise#11822]
**Problem Description**:
AI does not have any intent. This renders it unable to punch people by using exosuits.

**What did you expect to happen**: 
It cannot punch people when in an exosuit. Only push them since the default intent is help.

**What happened instead**:
The AI should have an option to choose its intent like cyborgs, even if it's only useful for when controlling a mech.

**Why is this bad/What are the consequences:**
AI cannot beat people up by using a mech.

**Comment by Citinited** [comment]
IMO there should only be an intent when the AI's inside a mech, otherwise there'll be an on-screen icon that's useless 99.9999% of the time.

**Comment by Emanthealmighty** [comment]
There's already two buttons that are pretty useless 100% of the time, those being "new camera" and "multicamera mode". Don't think it's necessary to make it hidden until you're in a mech.
