### ISSUE TITLE
Vox dont have a sprite for the jester costume

### ISSUE THREAD

**Issue by Carthusia** [ParadiseSS13/Paradise#11820]
**Problem Description**:
What is the problem?

Vox dont have a sprite for the jester outfit

**What did you expect to happen**: 
Why do you think this is an issue?
Vox jesters are a great form or morale, as with clowns

**What happened instead**:
How is what happened different from what you expected?
I expected a vox jester

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Its not so much super important, but good to note for future updates to add a sprite in for it

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
https://i.gyazo.com/2274a926768a1c57bf596fbccffad06b.png
Simply be a vox and try to put the jester outfit on, and it turns into a grey jumpsuit

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

No idea

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Not much more to say, simply equip the jester suit as a vox and it turns into a grey jumpsuit

**Comment by KasparoVy** [comment]
Sorry for the bother @Fox-McCloud, #11820 fixes this but because the 'fixes X' was added after the initial PR creation it didn't autoclose this
