### ISSUE TITLE
Plasma graphic (occasionally) remains on tile after being scrubbed/cleared.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#1183]
![image](https://cloud.githubusercontent.com/assets/6721066/7845839/8b6dd460-0487-11e5-9b39-e54174d61a72.png)

If I had to guess, I'd say it has something to do with trace amounts of plasma still being there. Removing the floor tile removed the effect, though, so... Probably something to do with not updating tile graphics.

**Comment by Fox-McCloud** [comment]
Yeah, guessing this is due to the update tiles sprite not being properly called in some instance (our floor code is HORRENDOUS).

**Comment by orelbon** [comment]
can we port someone elses? lol

**Comment by Fox-McCloud** [comment]
Should be fixed by Mark's most recent PR.
