### ISSUE TITLE
Switching intent quickly with 1 2 3 4 doesn't work

### ISSUE THREAD

**Issue by Tourte-Yaya** [ParadiseSS13/Paradise#11838]
**Problem Description:**
Switching  intent quickly with 1 2 3 4 doesn't work

**What did you expect to happen:**
Switching intent quickly when i press a number 

**What happened instead:**
Intent did not change

**Why is this bad/What are the consequences:**
I can only switch intent with the mouse which is annoying.

**Steps to reproduce the problem:**
1. Spawn in a round.
2. Try switch intent on azerty or qwerty.
3. Intent unchanged

**When did the problem start happening:**
Today. Around the time diagonal movement was merged.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):**
 Nothing out of the ordinary was happening. I was mostly Infront the bridge like always. Changing between QWERTY and AZERTY did nothing.

**Comment by Couls** [comment]
Need more info, were you on an english keyboard and were you using numpad keys?
