### ISSUE TITLE
F1 (ahelp hotkey) now brings up two prompts

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11839]
**Problem Description**:
Pressing F1 to bring up ahelp opens two prompts

**What did you expect to happen**: 
to get the old thingy asking if I want to mhelp or ahelp

**What happened instead**:
First an ahelp input prompt shows up, once it's closed, the old mhelp or ahelp prompt appears

**Why is this bad/What are the consequences:**
It's annoying and redundant

**Steps to reproduce the problem**:
press F1, click cancel on ahelp input prompt

**When did the problem start happening**:
With diagonal movement

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Couls** [comment]
fixed in #11829
