### ISSUE TITLE
New keyboard hotkeys breaks qwerty

### ISSUE THREAD

**Issue by Allfd** [ParadiseSS13/Paradise#11846]
**Problem Description**:
The new diagonal movement system breaks all the traditional hotkeys.

**What did you expect to happen**: 
For the function keys to do what they used to.

**What happened instead**:
They are all remapped to different functions.

**Why is this bad/What are the consequences:**
5 Years of muscle memory result in instead of opening the player window, I enter build mode.  All of a sudden everywhere I click becomes a wall, usually someplace very public, wall just appears out of nowhere as I am now in build mode.

Also, the old say (F3) is now Asay, so about half of my IC things I say end up in ASAY, and I then have to copy and paste them into Say

**Steps to reproduce the problem**:
Use QWERTY hotkeys, push any of the function keys.

**When did the problem start happening**:
After the merge of diagonal moment.

@Couls

**Comment by Couls** [comment]
#11829
