### ISSUE TITLE
Another pAI bug.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1184]
While playing a pAI I was hit by a flashbang. This caused me to be unable to move until I closed my chassis, which is normal. But it also carried the affect of preventing me from being able to hear anything for the rest of the round.

**Comment by Plotron** [comment]
Had a similar issue after being hit by a flashbang as a construct (wraith to be precise), and then later the same round as a secborg. The result was semi-permanent deafness (goes away only after death, obviously).

**Comment by Spacemanspark** [comment]
Turns out this is all synthetics, had this issue as a cyborg.
And apparently constructs.
