### ISSUE TITLE
Reviving a dead upgraded cyber heart causes constant messages about It trying to correct a cardiac event

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#11840]
**Problem Description**:
Reviving a dead upgraded cyber heart results in minor chat spam by constantly giving the user a notification about it trying to correct a cardiac event despite myself suffering from no negative effects

**What did you expect to happen**: 
To have my cyber heart restored with no further issues

**What happened instead**:
I got chat spam

**Why is this bad/What are the consequences:**
Chat spam is annoying

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**When did the problem start happening**:
I died to space then my heart clearly died after I was revived with SR, the doctor repaired the heart with nanopaste then re-implanted it into me, I then proceeded to get chat spam despite the heart being fully repaired and not suffering any negative effects.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by Spaghetti-bit** [comment]
The interval on the heart trying to correct the BPM is no longer spamming the client and hasn’t done so in a few years.
