### ISSUE TITLE
No one was able to move. Runtime appeared in Input.dm

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#11849]
**Problem Description**:
No one was able to move.
There was a runtime in input.dm.
`
[2019-07-13T19:33:54] Runtime in input.dm,123: Cannot execute null.keyLoop().
   proc name: fire (/datum/controller/subsystem/input/fire)
   src: Input (/datum/controller/subsystem/input)
   call stack:
   Input (/datum/controller/subsystem/input): fire(0)
   Input (/datum/controller/subsystem/input): ignite(0)
   Master (/datum/controller/master): RunQueue()
   Master (/datum/controller/master): Loop()
   Master (/datum/controller/master): StartProcessing(0)
`

**What did you expect to happen**: 
Everything to work normally.

**What happened instead**:
No one was able to move. Input runtimed.

**Why is this bad/What are the consequences:**
Its a game breaking bug.

**When did the problem start happening**:
The only PR that changed something with input was diagonal moving. Best guess that is the PR that caused it.

**Comment by Deelite34** [comment]
You were not able to move normally, but things like moving other person, and other person moving you, using wheelchairs + fire extinguishers, jumping over other person, by blue grabbing them and jumping let you move. I also saw someone moving normally that round, while dragging other people.

**Comment by Couls** [comment]
Looking into it
