### ISSUE TITLE
Infinite cable coil using an SMES

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11848]
**Problem Description**:
You can deconstruct an SMES' terminal multiple times, giving loads of cable coil from nowhere.

**What did you expect to happen**: 
You can deconstruct a terminal only once.

**What happened instead**:
Multiple deconstructions of a terminal allowed.

**Why is this bad/What are the consequences:**
Shouldn't be able to get infinite resources from anywhere.

**Steps to reproduce the problem**:
1. Open up an SMES
2. Spam-click the SMES using wirecutters
3. Watch cable coils appear from nowhere.

**When did the problem start happening**:
Probably since forever

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A

**Comment by SteelSlayer** [comment]
I was able to recreate this. I also discovered that when adding cables to create a terminal, it never subtracted the cable from my hand.

**Comment by Citinited** [comment]
> I also discovered that when adding cables to create a terminal, it never subtracted the cable from my hand.

Interesting
