### ISSUE TITLE
Preferences don't get saved

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11854]
**Problem Description**:
Preferences like. Mute deadchat and ghostears don't get saved.

**What did you expect to happen**: 
That my settings were saved

**What happened instead**:
I had deadchat muted and ghostears full in the new round

**Why is this bad/What are the consequences:**
Annoying mostly and shouldn't work like this

**Steps to reproduce the problem**:
Join the server. Set the preferences.
Join the server again in a new round

**When did the problem start happening**:
I think since the diagonal PR got merged

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Same as #11281

**Comment by AffectedArc07** [comment]
This is what happens when I stop reviewing PRs
