### ISSUE TITLE
Devouring mice (other animals too?) causes uncontrollable fullness (unsure if intended)

### ISSUE THREAD

**Issue by Tectuu** [ParadiseSS13/Paradise#11850]
**Problem Description**:
When devouring a mouse, sometimes the nutrition gain doesn't stop, making you full and fat.

**What did you expect to happen**: 
I expected to gain SOME nutrition, but a reasonable amount.

**What happened instead**:
My character is stuck at the "fat" level of hunger (gray bar) and can't eat anything. I'm unable to control this, even by drinking ten weight loss shakes.

**Why is this bad/What are the consequences:**
The consequences are potentially being unable to eat things that may heal you in a pinch, and possibly weight gain to the point that you burst out of your clothing.

**Steps to reproduce the problem**:
My character, a Tajaran, ate two mice - one alive and one seemingly dead. Try doing the same with a Tajaran and other species who can devour animals.

**When did the problem start happening**:
Possibly within the last month or so, I can't quite remember. It has happened a few times before this, though.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The gamemode was possibly traitor this time, but I unfortunately don't remember anything else unusual. If this is SUPPOSED to happen, please ignore this. I just want to be sure either way.

**Comment by SteelSlayer** [comment]
I tested this out on a private server. Used a Tajaran character and ate about 15 mice, got a reasonable amount of hunger from each. The mice never moved me up into grey hunger, and my hunger seemed to decay at the normal rate. I'm unable to reproduce this bug

**Comment by Tectuu** [comment]
Try having the mouse (or other animal) be resting when you devour them. If you never get a message like "The mouse stops moving..." then the bug is in effect, as far as I can tell.

**Comment by TheSardele** [comment]
I had a look into it, the closest thing I could find was eating a sentient mouse. Sentience adds 200 health to an animal, pushing a mouse up to 205, from 5. Digesting one of these mice would thus take 41 times as long, adding 41 times as much nutrition. Working as intended-ish I would say.
