### ISSUE TITLE
Multiply any chem by using humanoid bodies as beakers

### ISSUE THREAD

**Issue by Wookie1411** [ParadiseSS13/Paradise#11857]
**Problem Description**:
You can basically multiply chems inside humanoids by filling them up with the chem and then filling them up with Phosphorus, Sugar and Potassium to smoke the chemical. The humanoid will then release the chems they had in their body as smoke but the chems in their body don't get used up so the chems double inside their body because they still have the chems inside them and inhale the chems they should've smoked out.

**What did you expect to happen**: 
I wanted to fart out a saline glucose cloud from my body.

**What happened instead**:
I farted out a saline glucose smoke but the chems inside my body doubled for some reason and everyone who was in range also got the same amount of saline into their body.

**Why is this bad/What are the consequences:**
Unlimited rare chems for example intrioprodril.

**Steps to reproduce the problem**:
1. Inject yourself (or another humanoid) with any chemical.
2. Drink (or force feed it to the humanoid) 10u potassium, 10u phosphorus and 10u sugar.
3. ???
4. Profit. You now doubled the initial amount of chemicals inside your body.

**When did the problem start happening**:
It still works.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
:)

**Comment by datlo** [comment]
'Unlimited rare chems for example intrioprodril.'

I dont think injecting yourself with initropidil is going to end well. :joy:

**Comment by Wookie1411** [comment]
inject it into a monkey
