### ISSUE TITLE
Sentience event fires 10 times.

### ISSUE THREAD

**Issue by Shockpoint** [ParadiseSS13/Paradise#11874]
**Problem Description**:
The Sentience event fires 10 times, instead of just once.

**What did you expect to happen**: 
The event to fire once.

**What happened instead**:
It fired 10 times.

**Why is this bad/What are the consequences:**
It spams admins and ghosts about the event. It also leads to far too many sentient animals in the round.

**Steps to reproduce the problem**:
Force Sentience through the Event Manager.

**When did the problem start happening**:
When Bryan spawned 10 blobs in his sleep. (He never did, but the mid-round blob event fired 10 times when it came up and that was an absolute shitstorm.)
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
This happens basically every round. I personally just end up disabling the event altogether as it's an annoyance over a benefit to the round.
![Screenshot (379)](https://user-images.githubusercontent.com/43954438/61368994-5c3d1a80-a84c-11e9-98df-6b5a1ca4b59d.png)

**Comment by Couls** [comment]
I think this is intended? It's called the major sentience event or something. I'll look into it later or maybe @SteelSlayer can

**Comment by Shockpoint** [comment]
From what I can tell, it's not intended, and there isn't a major sentience event. It's just the mundane level one.

**Comment by Shockpoint** [comment]
Picture added to show how annoying that is.

**Comment by Ty-Omaha** [comment]
there was another event like this that did this something to do with swtiching the timer or something

**Comment by Ty-Omaha** [comment]
https://github.com/ParadiseSS13/Paradise/pull/11606
