### ISSUE TITLE
Mining Drone has invisible ghost

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#11878]
**Problem Description**:
What is the problem?
Dying as a mining drone/minebot causes your ghost to be invisible.
**What did you expect to happen**: 
Why do you think this is an issue?
Makes it hard to see yourself, or in case admins want to see your ghost.
**What happened instead**:
How is what happened different from what you expected?
Literally too spooky for me
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
The ghost should actually represent the mob that died
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Step 1. Be minebot
Step 2. Die to something on lavaland or elsewhere
Step 3. Be confused as to where your ghost is
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
I believe this problem has existed pre-lavaland; and probably as long as minebots have existed.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Nothing else to note.

**Comment by Spacemanspark** [comment]
I think this has something to do with brainless mobs being completely destroyed. Drones have the same issue too when they explode, for example.

**Comment by matttheficus** [comment]
The above PR makes it seem like a feature? Ill leave it to the Design people.

**Comment by Spacemanspark** [comment]
A 'restore ghost character' button might not be a bad idea for you guys tbh
