### ISSUE TITLE
Legal SOP book missing most content

### ISSUE THREAD

**Issue by Boolean-Buckeye** [ParadiseSS13/Paradise#11879]
**Problem Description**:
The Legal SOP book is missing most of the content from the wiki page, leaving out many important parts.

**What did you expect to happen**: 
Most SOP books contain the entire SOP but the Legal one is missing most of it. I expected it to contain all the content.

**What happened instead**:
Most SOP books contain the entire SOP but the Legal one is missing most of it.

**Why is this bad/What are the consequences:**
It is not convenient.

**Steps to reproduce the problem**:
I opened the Legal SOP book.

**When did the problem start happening**:
It's probably always happened.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I think you're asking too many questions. /s

**Comment by florkeger** [comment]
Upon testing it on a local server, the Legal SOP book worked just fine for me.

I'll check it on the live server if the problem occurs there too.

**Comment by Kyep** [comment]
@AffectedArc07 Works just fine when tested, issue can be closed.
