### ISSUE TITLE
Inventory buttons dont work half the time.

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11893]
**Problem Description**:
I click on stuff like a crowbar in my pocket and like half the time nothing happens until its eventually working again.

**What did you expect to happen**: 
Grab the crowbar.

**What happened instead**:
Half the time nothing happens and its frustrating.

**Why is this bad/What are the consequences:**
EXTREMELY FRUSTRATING CANNOT PLAY LIKE THIS AAAH.

**Steps to reproduce the problem**:
1. Click on item equipped/in inventory
2. Sometimes nothing happens

**When did the problem start happening**:
Today, 19/07/2019. Apparently Slith is also having the same issues.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Seems this also happens on local hosted server of para.

**Comment by Ty-Omaha** [comment]
is it possible sometimes you are click dragging?

**Comment by datlo** [comment]
Doesnt happen anymore for me. Weird as fuck. Closing unless this happens again or others report it I guess
