### ISSUE TITLE
Flamethrower not liting

### ISSUE THREAD

**Issue by Magentaformula0** [ParadiseSS13/Paradise#11898]
**Problem Description**:
What is the problem?
So the flamethrower might have a bug. Right now when I press the unlit to light it it just goes from blue to purple instead of changing to lit. I have verified that the tank has plasma in it.

**What did you expect to happen**: 
Why do you think this is an issue?
I expected it to lite like it has before under the same conditions.

**What happened instead**:
How is what happened different from what you expected?
It didn't.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
When I make a flamethrower to fight the blob and it doesn't work the way it should it is frustrating and could have gotten me killed if I hadn't tested it.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Get a plasma tank from science. Build a flamethrower. Place the plasma tank in. click unlit. If it turns from blue to purple then it has been reproduced. 

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
It has happened to me twice now with no foreseeable reason. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: I mean there was a blob and I dont know what else yet.

Anything else you can tell us.
If I have fireproof everything and a message says I have no exposed skin or too thick of clothing on I think you should be completely fireproof. Unrelated.

**Comment by SteelSlayer** [comment]
You actually need an igniter for a flamethrower to light. Try this: get an igniter, screwdriver it so it can be attached, then put it on the flamethrower. Then screwdriver the flamethrower to secure it, put the plasma tank in, then try to light it.

**Comment by Magentaformula0** [comment]
> You actually need an igniter for a flamethrower to light. Try this: get an igniter, screwdriver it so it can be attached, then put it on the flamethrower. Then screwdriver the flamethrower to secure it, put the plasma tank in, then try to light it.

I did everything the same as before without doing what you said and it worked fine this time.

**Comment by Shadow-Quill** [comment]
@Anasari I think this can be closed now
