### ISSUE TITLE
Wiring a crate breaks borg cable coils

### ISSUE THREAD

**Issue by enderman51505** [ParadiseSS13/Paradise#11890]
**Problem Description**:
apon rigging a crate with cable coils and having none left causes it not to regenerate when charging

**Why is this bad/What are the consequences:**
it takes a rather large part of a engiborgs kit away

**Steps to reproduce the problem**:
1: have less then or equal too the amount of wires to rig a crate
2: rig the crate
3: cable coil dissapears and doesnt come back

**Comment by SteelSlayer** [comment]
I was able to recreate this bug
