### ISSUE TITLE
Ash walker nest is invincible

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11902]
**Problem Description**:
The ash walker tendril cannot be destroyed by melee or guns that miners have.  Additionally KA's do not work in the room since it is pressurized for some reason unlike the rest of lavaland surface.

**What did you expect to happen**: 
To destroy the ash walker tendril by KA or knife.

**What happened instead**:
It cannot be killed.

**Why is this bad/What are the consequences:**
You cannot destroy the tendril nest as a miner which leads to constant ash walkers spawning as long as some are alive.

**Steps to reproduce the problem**:
Attack the ash walker tendril.  You cannot destroy it.

**When did the problem start happening**:
For a while, just the people I asked to report it before never reported it.

**Comment by Markolie** [comment]
This will be fixed by the universal damage PR, which is why I haven't touched this yet. Hopefully that will still go through.
