### ISSUE TITLE
Necropolis Tendrils / Lavaland spawners can be moved with a baseball bat. Can also buckle them to office chairs and move them about. Can ALSO place them in lockers that make them spawn mobs inside lockers and can move them about.

### ISSUE THREAD

**Issue by Abydos2** [ParadiseSS13/Paradise#11907]
**Problem Description**:

Any of the Tendrils on Lavaland can be moved from their positions with a baseball bat. You just hit them with it and it sends them 2 tiles forward, repeat the process and get it to a safe spot where you can safely kill it and it cannot spawn anymore mobs.

**What did you expect to happen**: 

I expected the Tendril to not be moved.

**What happened instead**:

The Tendril is moved.

**Why is this bad/What are the consequences:**

It's bad because someone could purely wait for the Tendril to make it's max amount of mobs (3-4) and then just start moving it away with a baseball bat to an area where it can safely be killed for free loot.

**Steps to reproduce the problem**:

1) Get a baseball bat

2) Find a lavaland Tendril

3) Hit it, watch it move.

Added:

4) Hit the Tendril to where a office chair is

5) Buckle it to the office chair

6) You can now move it around without having to hit it.

Added-added:

7) Move the Tendril to a locker

8) Close the locker, Tendril is now in the locker

9) Kill any mobs it spawned.

10) It will spawn new mobs inside the locker.

**When did the problem start happening**:

I reckon it started happening whenever Lavaland was introduced but no one had tried it before.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

Nothing else to report

**Comment by Markolie** [comment]
Tendrils are mobs right now, as it uses /tg/ old system. If/when universal object damage is merged they can be turned into structures like ash walker tendrils. Until then we'll have to live with this, as working around it is a hassle.

**Comment by Emanthealmighty** [comment]
If you turn "anchored" to true wouldn't it prevent it from moving completely?

**Comment by Markolie** [comment]
Mobs should not be anchored, it causes warnings in the movement pushing system.

**Comment by Abydos2** [comment]
> If you turn "anchored" to true wouldn't it prevent it from moving completely?

I tried that, anchored the spawner, didn't work, they could still be moved.

**Comment by Ty-Omaha** [comment]
>Until then we'll have to live with this, as working around it is a hassle.

we can just add an if check to the baseball bat throw function to make sure its not a tendril mob

**Comment by Markolie** [comment]
That is much too snowflaky and does not resolve the other movement issues.
