### ISSUE TITLE
Freezing players shows the admin's ckey as well as character name.

### ISSUE THREAD

**Issue by Shockpoint** [ParadiseSS13/Paradise#11915]
**Problem Description**:
See title.

**What did you expect to happen**: 
To not have my character name displayed to problem players.

**What happened instead**:
My character name was displayed to the frozen player.

**Why is this bad/What are the consequences:**
This allows for metagaming. Simply put, a salty new player can find the admin's character ingame and attack them with this information.

**Steps to reproduce the problem**:
Get a test subject.
Freeze them.
Have them show you the text.

**When did the problem start happening**:
I guess this has been a thing for as long as the freeze command has been in our code. No idea.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
This happened to me before. I didn't think much about it until a recent ban appeal appeared with a screenshot showing the name of an admin's character when they froze the player.

**Comment by Spacemanspark** [comment]
Clearly intentional

Get gud nerd

**Comment by florkeger** [comment]
How do you think of it to be? What should it show instead?

**Comment by florkeger** [comment]
https://github.com/ParadiseSS13/Paradise/pull/11919

Pretty much done here.
