### ISSUE TITLE
Can't order station goal during special rounds

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#11939]
**Problem Description**:
You can't order station goal parts from cargo during nukie or wizard rounds
**What did you expect to happen**: to be able to order BSA or meteor shields
**Why do you think this is an issue?**: this can be used to meta the gamemode
**What happened instead**:Was unable to order the station goal parts

**Why is this bad/What are the consequences**:this can be used to meta the gamemode
this is important because people can begin to notice a pattern
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. have nukies or wizard
2. go to cargo and check console
3. notice the station goal parts aren't there

**When did the problem start happening**: might've always been the case

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: only seems to happen during nukies and wizard, it may happen during blob as well

**Comment by Contrabang** [comment]
Don't think this happens anymore, must have been fixed in one of the many cargo updates
