### ISSUE TITLE
Ghost interactions with tables

### ISSUE THREAD

**Issue by DapperScallywag** [ParadiseSS13/Paradise#11945]
**Problem Description**:
A ghost that hovers over a table will be knocked off when the table flips, possibly damaging grilles/windows/etc.

**What did you expect to happen**: 
I expected the table to have no effect on my ghost, upright, flipped, or flipping

**What happened instead**:
My ghost was knocked off of the table, causing minor damage to a nearby grille that nothing else could reach

**Why is this bad/What are the consequences:**
This has a potential to break windows and thus cause breaches because a ghost was on a table when it was flipped

**Steps to reproduce the problem**:
Move your ghost onto the table
Someone flips the table
Ghost gets knocked off, possibly impacting a nearby grille/window/etc

**When did the problem start happening**:
N/A

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
There seemed to be several tables on the same tile that my ghost was occupying at the time

**Comment by Citinited** [comment]
damn poltergeists!

**Comment by matttheficus** [comment]
Throwing ghosts with buildmode does something similar, though unsure if its the same issue.
