### ISSUE TITLE
Hierophant abilities prevent clicking on yourself

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11947]
**Problem Description**:
The particle effects of the hierophant abilities have a higher overlay priority than that of a player.

**What did you expect to happen**: 
For the hierphant abilities to be a layer below the player so you can click on yourself with legion souls/healing patches.

**What happened instead**:
You cannot click on yourself if the hierphants abilities are currently on your same tile and you instead have to alt click your tile and then click on your player in the floor tab menu.

**Why is this bad/What are the consequences:**
Its a speed intensive fight where you have to keep moving to avoid being hit.  Being unable to heal yourself on the fly means you have to stand still and are a sitting duck.

**Steps to reproduce the problem**:
Fight the hierophant and try to click on yourself with a legion core/healing patch while its abilities are proccing on your tile.

**When did the problem start happening**:
Most likely was a problem that came along with the megafauna but was never noticed.

**Comment by Deelite34** [comment]
Similiar thing happens with big megafauna, I'm 80% sure, that when legion is next to you and covers your character, you are not able to alt click your tile, and for example heal yourself with legion core.

**Comment by florkeger** [comment]
I think the issue here is simply the way the current mobs are handling their layers. The Hierophants blast attack defaulted to to temp_visual which is 4.1 aka above mob layer, so it goes over a lot of things.

Already on something. I was at first making sure it'd only be a fix for the Hierophant, but if it occurs with different megafauna too, I'll look a little more into this.

**Comment by florkeger** [comment]
> Similiar thing happens with big megafauna, I'm 80% sure, that when legion is next to you and covers your character, you are not able to alt click your tile, and for example heal yourself with legion core.

Turns out that all megafauna are set to above mob layers by default, which will pretty much burry everything under them.
