### ISSUE TITLE
Resting is spammable again

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#11952]
**Problem Description**:
The 'rest' command seems to have been fucked up somehow. It's once again spammable--the 'cooldown' is only applied once you stop spamming... and it only prevents you from moving in any of the eight directions for a mere second or so, you can even start spamming rest again.
https://i.imgur.com/whvd40r.gifv

**What did you expect to happen**: 
I expect a small cooldown once I've used the rest command, disabling me from standing again for a second or so.

**Why is this bad/What are the consequences:**
We initially imposed the rest cooldown to prevent players from spamming the command to dodge things such as taser shots easily.

**Steps to reproduce the problem**:
Spam rest. Congratulations, you can do push ups faster than the fastest person alive can run.

**When did the problem start happening**:
Unknown, I've only found this out today.

**Comment by Couls** [comment]
Can't restore the old functionality but I can stick in a do_after to add a progress bar for getting up after resting. Would you prefer I do that?

**Comment by Spacemanspark** [comment]
Should I close this? Not sure if this is a bug per se.

**Comment by Spacemanspark** [comment]
@affectedarc07

**Comment by Spacemanspark** [comment]
I'm fairly sure this isn't a bug.
