### ISSUE TITLE
Plasmaman Wizard Robes Not Armored

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11958]
**Problem Description**:
Plasmaman wizard robes have no armor values unlike normal wizard robes which has :
melee = 30 
bullet = 20 
laser = 20 
energy = 20 
bomb = 20 
bio = 20 
rad = 20
And wizard hat which has : 
melee = 30 
bullet = 20 
laser = 20 
energy = 20 
bomb = 20 
bio = 20 
rad = 20

**What did you expect to happen**: 
For the plasmaman wizard suit and hat to have armor values.

**What happened instead**:
The suit and hat has no armor currently.

**Why is this bad/What are the consequences:**
It makes a plasmaman wizard very suspectable to any weapon the crew has on hand and they are unable to armor themselves from the crew?

**Steps to reproduce the problem**:
Just check the armor values attached for the plasmaman wizard suit and hat.

**When did the problem start happening**:
Most likely since the wizard plasmaman gear was added.

**Comment by Muhdi345** [comment]
I really REALLY don't recommend you make the plasmaman wizard robes armored. Our main weapon is being spaceproof. Do you wish to see me shrug off a bit of damage while I just run to space?

**Comment by datlo** [comment]
this seems like a balance request to me, plasmaman wizards already start with a free suit with no movement penalty, the lack of armor is fine imo
