### ISSUE TITLE
Unable to interact with anything from time to time, while at the same time everyone else seems to be unaffected.

### ISSUE THREAD

**Issue by Novacti** [ParadiseSS13/Paradise#11967]
**Problem Description**:
From time to time, I would just be unable to do anything, while people are still walking, chatting and fighting while I am unable to do anything, not even talk. Only completely closing dream seeker and re-opening it seems to solve the problem.

**Steps to reproduce the problem**:
Play the game for a little bit, then you will suddenly freeze, or if you are moving when the problem occurs, you will continue in the same direction until you hit a wall and stop. 

**When did the problem start happening**:
I think the problem started occurring sometime between the last two BYOND updates, I am not too certain at what precise time.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
This happens to me on all servers, at seemingly random intervals in: paradise, TG, CM. But recently, I've been noticing other people also having the same problem as me, with the problem occurring to us at approximately the same time (do not take my word for this, I cannot be completely sure that they are having the exact same problem as I, but through OOC chat, it has been assumed that we have the same problem happening). 

**Additional remarks**:
I've tried to change all the settings in BYOND and in-game,  clear BYOND cache, completely re-install BYOND and do a full reset on my computer, nothing seems to work.

**Comment by Spaghetti-bit** [comment]
Fixed as of 514
