### ISSUE TITLE
Using thermite creates an abyss into the nether realms

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#11960]
**Problem Description**:
Splashing thermite on walls makes them turn into a black void that cannot be interacted with

**What did you expect to happen**: 
To be able to put thermite on a wall and melt it

**What happened instead**:
The wall became an abyss that I couldn't interact with

**Why is this bad/What are the consequences:**
Severely limits the use of thermite because walls now become inaccessible when doused 

**Steps to reproduce the problem**:
Take thermite, splash it on a wall, watch as it becomes a black box that you can't even alt click on

**When did the problem start happening**:
Not sure, only just encountered it today

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
When other nearby walls were removed it seemed to restore a bit of the wall, perhaps this happened due to the way wall textures join together
![Screenshot (25)](https://user-images.githubusercontent.com/52841396/62412770-dc95a680-b5d4-11e9-94ed-7ad5765dec4b.png)

**Comment by KasparoVy** [comment]
Thermite so strong it melted through reality

**Comment by taukausanake** [comment]
> Thermite so strong it melted through reality

I actually want bluespace thermite now. It doesn't melt through walls. It makes walls traversable/able to be walked through

**Comment by JohnBigless** [comment]
> I actually want bluespace thermite now. It doesn't melt through walls. It makes walls traversable/able to be walked through
Add redspace thermite, wich would temporairly break a tile, making it so that it teleports you randomly the same way a bluespace crystal would when stepped on.

**Comment by taukausanake** [comment]
> redspace thermite

Redspace is still only a theory concerning lore and I feel it should stay that way. Like a crazy scientist's theory
