### ISSUE TITLE
Monkey Bugs

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1196]
- Going from human to monkey and monkey to human still drops all internal organs
- Activating and deactivating the monkey gene is incredibly inconsistent and finicky
 - previously, monkeys would have their monkey gene (block 55/last block) at something like DAC; if it dropped below that, they would humainze; likewise, if you injected someone with an injector that had the last block below a certain value, it would humanize them every time--above a certain value? It would monkeyize them all the time...now? It's incredibly inconsistent.

**Comment by ZomgPonies** [comment]
The monkey block is anything above 800 on the last block, always has been. This is working correctly. Monkeys start with the block > 800. Drop it below that, they humanize. Raise it above that, they monkey again.
