### ISSUE TITLE
The 'Office Door' button in the RD Office cannot be accessed by the Research Director

### ISSUE THREAD

**Issue by JohnBigless** [ParadiseSS13/Paradise#11963]
**Problem Description**:
What is the problem?
A button labelled 'Office Door', whose purpose is to open the RD Office door cannot be used by the Research Director themselves.

**What did you expect to happen**: 
Have access to the button and be able to remotely open and close the RD Office door.

**What happened instead**:
Access Denied.

**Why is this bad/What are the consequences:**
The button is completely obsolete due to it being unusable.

**Steps to reproduce the problem**:
Step 1. Be RD.
Step 2. Go into the Research Director's Office
Step 3. Press button.
Step 4. Access Denied.

**When did the problem start happening**:
No clue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
No other info i find usefull.
A simple var edit in the map editor may solve this problem.

**Comment by florkeger** [comment]
Looks like a simple permission issue with the button. I'll look at it in DM.
