### ISSUE TITLE
beepsky tries to arrest slimes and spam sec chat

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11977]
**Problem Description**:
Beepsky tried to arrest slimes. Ends up spamming sec comms.
![image](https://user-images.githubusercontent.com/22121511/62819605-b41f2680-bb57-11e9-82fe-16d78c4f94f7.png)

**What did you expect to happen**: 
Not to have my CHAT EXPERIENCE RUINED

**What happened instead**:
IT WAS SKREE

**Why is this bad/What are the consequences:**
Annoying and it locks beepsky from catching actual criminals

**Steps to reproduce the problem**:
Have slimes in hallways, beepsky tries to arrest them

**When did the problem start happening**:
No clue

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Happened today 10/08/2019 on live server

**Comment by Shadow-Quill** [comment]
May occur when ID check is on.

**Comment by datlo** [comment]
ID check was not on when I checked the bot settings, only warrant check

**Comment by taukausanake** [comment]
_Beepsky is racist against non-sentient slimes, more at 11_

**Comment by SomeSortaSquid** [comment]
It's a feature that helps you realize it's time to arrest the xenobiologists.

**Comment by Lunaimon** [comment]
I haven't seen Beepsky go crazy against any other simple mobs, is it just slimes?

**Comment by datlo** [comment]
Slimes arent simple mobs, they are actually carbon mobs.
