### ISSUE TITLE
Clowns/mimes cloned loses their clown name

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#11979]
**Problem Description**:
After being cloned I sounded like my character's name instead of being my clown name

**What did you expect to happen**: 
Be cloned all is good

**What happened instead**:

![image](https://user-images.githubusercontent.com/22121511/62822954-54427300-bb8b-11e9-9dcb-2d0f1a7dde89.png)

**Why is this bad/What are the consequences:**
Make me look like a changeling

**Steps to reproduce the problem**:
Clone clown (maybe with brain scan instead of body?)

**When did the problem start happening**:
Dunno

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Happened today 10/08/2019 on live

**Comment by Breenland** [comment]
I’m quite sure this also applies to mimes, and likely any other similar situations.

**Comment by Contrabang** [comment]
Doesn't seem to happen anymore when clowns/mimes are cloned. I can't find the exact PR that fixed it, but it seems to work as intended now
