### ISSUE TITLE
Duplication via false walls

### ISSUE THREAD

**Issue by Cynthum** [ParadiseSS13/Paradise#11972]
**Problem Description**:
Dislodged Girder duplication via False wall dismantling.
**What did you expect to happen**: 
False wall dismantled by welder, returning the titanium and leaving behind a dislodged girder.

**What happened instead**:
After using the welder on the falls wall to dismantle it, the false wall did not dismantle and did not return the titanium. Instead, it stayed fully assemble and created a dislodged girder. Repeating to use the welder on the false wall, will continue to create another dislodged girder per click.

**Why is this bad/What are the consequences:**
Primary issue is that the duplicated girders can still be disassembles down into metal. One can farm metal with this duplication bug. It also brings the issue of unable to remove the false wall, making permenant entry ways that could cause trouble gameplay wise.

**Steps to reproduce the problem**:
Attempt to use a welder on a false wall made from Titanium.

**When did the problem start happening**:
I encountered this problem when trying to build a normal wall, but forgot to wrench the girder into place first. I discovered it when I was trying to correct my mistake.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Gamemode is N/A. Was trying to redesign the interior of the free golem ship at the time. I was a golem at the time. Nothing else out of the ordinary happened. We were parked at the abandoned destroyed ring station.

**Comment by Markolie** [comment]
https://github.com/ParadiseSS13/Paradise/pull/11695 should fix that, as it fully refactors falsewall code.

**Comment by AffectedArc07** [comment]
Has been fixed
