### ISSUE TITLE
Maintenance Drone Wood Planks Don't Regen

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#11974]
**Problem Description**:

Title.

**What did you expect to happen**: 

To regenerate planks as with rods/metal/glass etc.

**What happened instead**:

They were gone until I became a new drone.

**Why is this bad/What are the consequences:**

You have to keep a careful eye on how much wood you have.

**Steps to reproduce the problem**:

1) Be a drone.
2) Use up all your wood planks.
3) Recharge.

**When did the problem start happening**:

N/A

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:

N/A

**Comment by SteelSlayer** [comment]
When I went to test this out, my planks regenerated fine. https://streamable.com/ft4gi

**Comment by moxian** [comment]
Also mentioned in #10601
