### ISSUE TITLE
Mega vox only can wear regular mask instead of vox mask

### ISSUE THREAD

**Issue by hunakos57** [ParadiseSS13/Paradise#11975]
**Problem Description**:
What is the problem?
Mega Vox can't use the vox mask only the regular mask to get N2.

**What did you expect to happen**: 
Why do you think this is an issue?
Only the height change not the shape of face.... There is still a beak.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Breaking the merge of the game.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I was a friendly IPC with some voxxies. One of them was an admeme, I was changed to vox later on to a mega vox.

**Comment by FreeStylaLT** [comment]
mega vox

**Comment by KasparoVy** [comment]
LMAO that's the first time I've ever heard them called mega Vox and I fucking love it hahaha

Vox Armalis but still, mega vox is bomb.

**Comment by KasparoVy** [comment]
Working on some sprites for Armalis breath mask, backpack & belt nitrogen.
