### ISSUE TITLE
Starting as Borg = No Brain

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#1198]
Title sums it up-- As I discovered during one shift in which I tried to transplant a borg's MMI'd brain into a DURAND, I found out that, while being a fully operational borg, he had 'no brain' according to the game as a result of his spawning in as a borg

IDK if this is intentional or not but-- shouldn't it be the case that, no matter what, borgs have some sort of brain (MMI or posibrain)?

I figured that, if spawnborgs (not transhumans or whatever) had a posibrain with a default name (like OSI-666 or the name of the borg or whatever) like posibrains are normally named, it'd make sense-- OR they could spawn with an MMI brain in them with the name of the borg assigned to it (for example, if I extracted the MMI from a borg named 'F.R.I.G.' the MMI would identify as 'F.R.I.G.' as well

**Comment by Zuhayr** [comment]
Bay uses alt titles to determine which brain is spawned.

**Comment by Krausus** [comment]
As Zuhayr said, whether the cyborg is using an alt title matters - a plain Cyborg gets an MMI, an Android gets a posibrain, and a Robot lacks any removable brain.

This is working as intended, though I wouldn't be surprised if most players are unaware of the consequences of picking a cyborg alt title.

**Comment by Plotron** [comment]
Could probably add this info to the Wiki.

**Comment by KasparoVy** [comment]
Alright thanks loads, had no idea this was even a thing
