### ISSUE TITLE
Cyborgs can't choose their names anymore.

### ISSUE THREAD

**Issue by DravenBlackpaw** [ParadiseSS13/Paradise#11983]
**Problem Description**:
When made into a borg you can't choose your name.

**What did you expect to happen**: 
Most like to choose their names when they get borged.

**What happened instead**:
Even when a rename upgrade was used, no use.

**Why is this bad/What are the consequences:**
Too many borgs running around named 'generic borg (number)

**Steps to reproduce the problem**:
have your brain polaced into a borg.

**When did the problem start happening**:
9/11/19
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Not sure what else to say

**Comment by Kyep** [comment]
There's a "Namepick" verb under the "Robot Commands" tab.
However, it doesn't work. It does absolutely nothing when clicked - no error, no runtime.
The verb is probably being called when you turn into a borg, just not working.

More generally all popups that generate a "choose your name" selection right now may be broken. https://github.com/ParadiseSS13/Paradise/pull/11207 should fix this.
