### ISSUE TITLE
Wire-node placed wires don't show up correctly

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#12008]
**Problem Description**:
When clicking on a plating with a wire node on it, while on the tile the node was placed from, the resulting node always shows as a north-placed node.
![image](https://user-images.githubusercontent.com/44811257/63068997-e2e02880-beda-11e9-926b-241032072910.png)
(Blue rectangles are for seperation)
Actual node direction is correct, the icon is just not facing the right way.

**What did you expect to happen**: 
The resulting node being shown correctly.

**What happened instead**:
It didn't.

**Why is this bad/What are the consequences:**
Confuses people when they're expecting the node to be shown one way, when it's always being shown as north-placed.

**Steps to reproduce the problem**:
1) Place wire node.
2) Click again on node/plating to place a node under you.
2a) The correct icon is shown if you follow the steps above, starting with a node placed north of you.

**When did the problem start happening**:
Unknown.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
N/A.

**Comment by Contrabang** [comment]
Like fixed with the powernet refactor. Not able to reproduce.
