### ISSUE TITLE
Tightening bolts in a fake wall destroys it.

### ISSUE THREAD

**Issue by Emanthealmighty** [ParadiseSS13/Paradise#12001]
**Problem Description**:
Tightening bolts in a fake wall destroys it.

**What did you expect to happen**: 
To tighten the bolts and turn it into a real wall.

**What happened instead**:
It disappeared.

**When did the problem start happening**:
Not sure.

**Comment by Ty-Omaha** [comment]
you tightened it too much and the cheapo metal buckled
