### ISSUE TITLE
Hotkeys problem on AZERTY

### ISSUE THREAD

**Issue by PrototypeNitro** [ParadiseSS13/Paradise#12019]
**Problem Description**:
Most of my hotkey doesn't work anymore

**What did you expect to happen**: 
I can't play properly

**What happened instead**:
I Can't use hotkey 1 2 3 4 to get help disarm grb and harm intent

**Why is this bad/What are the consequences:**
It's occur my gameplay

**Steps to reproduce the problem**:
- N/A

**When did the problem start happening**:
When the update to change the keyboard mode QWERTY/AZERTY

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It also occur on borg gameplay when I press Q I should go let but it also drop what I have in my hand

**Comment by dovydas12345** [comment]
I heard that some others who play on AZERTY have problems as well. You are not the only one.

**Comment by Couls** [comment]
Are you using numpad keys or the numbers at the top? You may need to put your keyboard into English mode through windows while using AZERTY mode

**Comment by Sirryan2002** [comment]
likely fixed in the new key binding rework
