### ISSUE TITLE
Abandonned Teleporter Error

### ISSUE THREAD

**Issue by PrototypeNitro** [ParadiseSS13/Paradise#12018]
**Problem Description**:
One the teleporter online and powered on the abandonned telporter Z-level - Teleporter is stuck on Initiliazing and a windows come with an error  has occurred - Can't find property "POWERSTATION"

**What did you expect to happen**: 
We can't use the telporter on Abandonned teleporter?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
If you go on abandonned telporter - expect with hand tle you are trapped

**Steps to reproduce the problem**:
Go on abandonned telporter - Re-build the teleporter and use the computer

**When did the problem start happening**:
immiediatly and for other players as well

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by datlo** [comment]
This is not an issue, you did not setup the teleporter properly. IIRC you missed connecting the powerstation with the teleporter using wirecutters.

**Comment by Shadow-Quill** [comment]
Not a bug/Could not reproduce.

**Comment by Shadow-Quill** [comment]
@Anasari
