### ISSUE TITLE
Ash Drakes Can Jump to Hyperspace

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#12027]
It would appear that under some conditions, Ash Drakes can jump to hyperspace when a shuttle is moving, even if they were previously on Lavaland/the Station.

This is well, problematic for obvious reasons; it should really only be able to jump from its own z-level to it's own z-level, not jump from one to another.

**Comment by MrMagolor** [comment]
How does this happen? An ash drake following a player starts the leap, then the shuttle leaves?
