### ISSUE TITLE
Hierophant staff appears on back even when its in hands

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#12022]
**Problem Description**:
Hierophant's in hands staff appears on the back despite being in hand

**What did you expect to happen**: 
Have it in hands

**What happened instead**:
Have it on back

**Why is this bad/What are the consequences:**
Is wrong. can be confusing when fighting someone with hiero

**Steps to reproduce the problem**:
1. have hierophant staff in your hand

**When did the problem start happening**:
lavaland PR

**Comment by MrMagolor** [comment]
I believe this only happens when holding it in one of the hands, I believe the left?

**Comment by Kyep** [comment]
@AffectedArc07 This is fixed (tested on live) and can be closed.
