### ISSUE TITLE
solar tracker electronics can't be applied to a solar assembly as a cyborg.

### ISSUE THREAD

**Issue by Sheppysneik** [ParadiseSS13/Paradise#12026]
**Problem Description**:
What is the problem?
by trying to add a solar tracker electronics to a solar assembly through the magnetic gripper nothing happens.

**What did you expect to happen**: 
Why do you think this is an issue?
the solar tracker electronics is added successfully when clicking on the assembly with it as an human race with hands, The engineering cyborgs with their magnetic gripper are unable to add the part to the assembly.

**What happened instead**:
How is what happened different from what you expected?
the solar tracker electronics should have been applied to the assembly instead of "disappear"

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
you can't complete a solar tracker as a cyborg, and this is pretty important when you get created in delta station and the human crew orders the cyborg to set up solars.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
>acquire solar assembly;
>wrench assembly;
>pick up the solar tracker electronics with the magnetic gripper as a cyborg engineer;
>click on the assembly with the gripper containing the solar tracker electronics;
>the solar tracker electronics suddenly disappears.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
You can drop the electronics without any problem after picking it up with the gripper, but this possibility disappears when you click with the gripper on the assembly. starting from now the solar tracking electronics seems lost.

**Comment by Shadow-Quill** [comment]
Couldn't reproduce the circuit board disappearing (board could be dropped with the "Dropped Gripped Item" verb in the Drone tab), but can confirm that borgs can't circuit solar trackers.
