### ISSUE TITLE
Cant pull objects / Climb onto surfaces after SR as Ian

### ISSUE THREAD

**Issue by Deriol-BestIan** [ParadiseSS13/Paradise#12032]
**Problem Description**:
After SR'd as Ian I realized I could no longer pull objects or climb onto surfaces anymore as Ian.  John Clarke asked me to post this. :)

**What did you expect to happen**: 
Being able to pull things and climbing onto things, Usual Ian good-boy stuffs.

**What happened instead**:
Nothing happened at all.  No pull icon appeared.  Tried Control + Clicking and Right Click + Pull.

**Why is this bad/What are the consequences:**
Ian cant be the bestest of boys if not able to play fetch! Or Scamp around on tables

**Steps to reproduce the problem**:
Die horrificly to the dismay of others as Ian.  Wait for someone to SR you.

**When did the problem start happening**:
After I was SR'd.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Ian was being a good boy and was SR'd, went immediately running to HoP!  Tried to grab HoP a snack from kitchen counter on way back and realized I couldnt pull.  Then tried to jump onto the HoP counter, cutting in line, to jump into owners arms,  Realized could no longer climb surfaces.

**Comment by Shadow-Quill** [comment]
Related to #11561
