### ISSUE TITLE
Players characters poofing and reappearing

### ISSUE THREAD

**Issue by SquidNeko** [ParadiseSS13/Paradise#12049]
**Problem Description**:
Sometimes when people switch clothing part of their body just poof until they move, alot of time time turning them nearly completely invisible.

It also just happens randomly when people move around. An movement can cause their character to just poof and next step or movement they are back.
But some players just keeps bieng invisible if they dont move for some time.

**What did you expect to happen**: 
Always see players?????

**What happened instead**:
Poofing?????

**Why is this bad/What are the consequences:**
Can be a problem if it happens when someone died and you didnt see them when trying to rescue. Leaving  them to die on accident.
Or if you are trying to find a target and this bug happens as they might be standing still. Not seeing them.
Among other occasions. Players poofing from view can have many problems depending on the situation and things happening.

**Steps to reproduce the problem**:
Dont know how to reproduce. But it keeps happening all the time in every single game alot.
Just play and you should see it if you pay attention. Playing as PAI and staying on your owner might very likely make you see it.

**When did the problem start happening**:
Been going on for a month? Maybe longer? Im not sure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Any gamemode. Random since i dont know the cause.

**Comment by Couls** [comment]
BYOND issue and copy of #11636 #11538
