### ISSUE TITLE
Take control of pet yes/no dialog mixed up

### ISSUE THREAD

**Issue by nicklanng** [ParadiseSS13/Paradise#12050]
**Problem Description**:
The yes and no buttons on the dialog that lets you take control of a pet were mixed up, No gave me control of the pet. Later Yes skipped it and a later No took control of a pet.

**What did you expect to happen**: 
Yes should give you control of the pet no should not.

**What happened instead**:
Yes skipped the pet, no took control.

**Why is this bad/What are the consequences:**
I was standing around as a mi-go confusing my master before I knew what was going on.

**Steps to reproduce the problem**:
I originally killed my self by opening a window to space. I followed a few people as a ghost. Then I got a popup to take control of a mi-go. I hit no and was given control. That mi-go eventually died in an ash fire on lavaland. Later on the xenobiologist activated another pet. I hit yes and nothing happened. Later, I hit no on a tree and took control of it. 
My 'Be Sentient Animal' toggle was always set to Yes.

**When did the problem start happening**:
I'm afraid this is the first time I've ever seen the pet dialog.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
If you have logs, the round occurred on 22/08/2019 at 2:37 PM. MY account is SoupStoreGames.

**Comment by Kyep** [comment]
@nicklanng To confirm:

- You ended up as a "mining golem" despite hitting no to the prompt?
- The mining golem was spawned in on a golem shell?

**Comment by nicklanng** [comment]
I spawned in as a mi-go, the lovecraftian monster. The xenobioligist was
granting sentience to the pets in her pen.

**Comment by Sirryan2002** [comment]
Old issue, the menu in question has been changed to candidate poll or no longer exists
