### ISSUE TITLE
Airlocks don't close themselves anymore

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12054]
**Problem Description**:
Airlocks don't close themselves anymore and changing the timing won't do anything

**What did you expect to happen**: 
For them to close per usual

**What happened instead**:
Bridge and brig wide open because somebody didn't close it behind their back

**Why is this bad/What are the consequences:**
It's broken AF

**Steps to reproduce the problem**:
(might have to set the timers first, aka shortcut them)
Open a door

**When did the problem start happening**:
I've noticed it starting since of today (22-8-2019)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Game was chugging pretty badly as well

**Comment by TDSSS** [comment]
Probably caused by #12047

**Comment by Shadow-Quill** [comment]
Can confirm, only happens with overridden timed doors

**Comment by TDSSS** [comment]
Can reproduce it locally with overriden timing, yeah.

**Comment by Fox-McCloud** [comment]
Not entirely correct; this only applies to overriden ones, as @Shadow-Quill technically pointed out.
