### ISSUE TITLE
On the Nature of the Survivor and the Wastes (A tale of howling wind or lack there of)

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#12052]
**Problem Description**:
When the wind starts kicking up and you place a new shelter, inside, you don't hear anything; it's completely silent--same for once the storm actually starts; when the storm ends and the next storm starts, then you will properly hear the wind.

**What did you expect to happen**: 
I expected to hear the wind howl, the ash to churn, the clouds to dark. I expected twitch my ears and turn them towards the sky---my face set against the world, for I am a survivor. The howling gales and the blustering gusts do not avail me, for I have slain countless many of the beast that linger in these wastes, I have fashioned for myself armor of their dismal hides. The lava has become my bedside, the ash my hallowed den. I shake my fist at the dead gods that once inhabited this realm for their failed attempts on my life. I gaze upon the wastes with the wind tearing at my back---but I shall not fall, for I am a survivor.

**What happened instead**:
<silence>

**Why is this bad/What are the consequences:**
I am unable to be the captain of my own destiny, with the fate of the howling winds licking at my ash charred fur.

**Comment by Shadow-Quill** [comment]
*An eerie silence falls.*
