### ISSUE TITLE
Shuttle can crush singulo

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#12068]
**Issue Description**:
The shuttle can crush the singulo, deleting it.
**What did you expect to happen**: 
Poor miner get instantly nom'd the moment he arrives
**What happened instead**:
Singulo get deleted by the mining shuttle
**Why is this bad/What are the consequences**:
Bruh
**Steps to reproduce the problem**:
1. Have the singulo at a shuttle landing dock
2. Send shuttle on top of singulo crushing it

**When did the problem start happening**:
Happened today 24/08/2019 on live.
**Extra information**:
Was a supermatter charged singulo. The shuttle was a mining shuttle.

**Comment by AffectedArc07** [comment]
**Why is this bad/What are the consequences:**
Bruh

[I 100% agree with this notation](https://www.youtube.com/watch?v=2ZIpFytCSVc)

**Comment by JohnBigless** [comment]
> Why is this bad/What are the consequences:
Bruh

Bruh moment.

**Comment by Citinited** [comment]
New singularity containment method confirmed
