### ISSUE TITLE
People become immune to stuns

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12067]
**Problem Description**:
A vampire became immune to stuns

**What did you expect to happen**: 
To fall down after getting stunned

**What happened instead**:
10 stuns, 5 tasers and 20 disabler shots and he was still walking

**Why is this bad/What are the consequences:**
Game breaking

**Steps to reproduce the problem**:
I'm not quite sure but from the info I gathered it might have come due to the pancuronium inside the vampire.
So step 1 inject him with that. step 2 stun

**When did the problem start happening**:
Since #12063

**Comment by TheSardele** [comment]
Managed to reproduce it with pancuronium, they are in fact immune to stuns.

**Comment by Fox-McCloud** [comment]
This isn't caused by https://github.com/ParadiseSS13/Paradise/pull/12063

You can remove the offending code and it persists.

Somehow, something broke with reagents not properly calling `update_canmove`; something funky is going on and I'm not really sure what...
