### ISSUE TITLE
Can't insert new magazines into the L6 saw

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#12069]
**Issue Description**:
You can't insert new L6 mags into the L6 SAW (Box magazine 5.56x45mm)

**Why is this bad/What are the consequences**:
Renders the L6 unusable outside of its initial 50 rounds

**Steps to reproduce the problem**:
Get L6 SAW
Remove mag
Try to insert new one, fail

**Comment by Shadow-Quill** [comment]
Couldn't reproduce via steps. You probably weren't actually clicking on the gun's sprite.

**Comment by Couls** [comment]
Can reproduce via steps, clicking the L6 Saw with its own magazine(admin spawned) does nothing but doing so with the cover closed does give the message to open the cover first
