### ISSUE TITLE
IPCs cant deploy charging cable more than once

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#12077]
**Issue Description**:

Says it activates, and switches hands if needed, but doesn't give you a cable. Eventually it tells you it's broken.

**What did you expect to happen**: 

To get a charging cable.

**What happened instead**:

We re-enacted Detroit: Become Human

**Why is this bad/What are the consequences**:

Didn't.

**Steps to reproduce the problem**:

1. Be IPC
2. Try and show your charging cord.
3. Fail.

**When did the problem start happening**:

PR #11936, according to Fox.

**Extra information**:

You can deploy your cable exactly once (1ce)

**Comment by Shadow-Quill** [comment]
When @Necaladun VVed me, it showed me as a `/mob/living/carbon/human`, which I haven't been able to reproduce locally yet.

**Comment by Fox-McCloud** [comment]
@farie82 Ya broke it
