### ISSUE TITLE
Lavaland Atmos Issue

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12096]
**Issue Description**:
Destroying rocks too fast while mining results in null pressure zones/void pressure areas.  This can be caused by using a adv plasma cutter while mining or AoE mining mod with cooldown mods.
**What did you expect to happen**: 
For atmo to refill in the areas so pressure damage does not occur.
**What happened instead**:
Miners mining too fast can create areas of zero atmo.
**Why is this bad/What are the consequences**:
Combined with fastmos this can cause miners to quickly take a large amount of damage when running into this void pressure zones they made as atmo on the planet tries to refill it.
**Steps to reproduce the problem**:
Be a miner, use the adv plasma cutter, constantly run along as you mine out with the cutter.
**When did the problem start happening**:
Noticeable since lavaland was merged but could have been an issue for longer since the old asteroid had no pressure in the first place to try and refill with.

**Comment by datlo** [comment]
Couldnt you set the default atmos on these tiles to the lavaland default when they are changed to? Or is that already the case and it just happens 2fast4atmos
