### ISSUE TITLE
No non-human sprites for the durathread bandana

### ISSUE THREAD

**Issue by DoctorDrugs** [ParadiseSS13/Paradise#12113]
**Issue Description**:
as the title says there's no non-human sprites for the durathread bandanna, neither the on head nor mask slots
**What did you expect to happen**: 
have a sprite for them to appear on my character
**What happened instead**:
no sprites were shown
**Why is this bad/What are the consequences**:
lack of sprite, not game breaking in anyway but muh fashion
**Steps to reproduce the problem**:
get durathread and craft a bandanna
**When did the problem start happening**:
as soon as tailoring pr was merged as the pr doesn't actually have any non-human sprites from the get go for the bandanna
**Extra information**:
N/A

**Comment by TheSardele** [comment]
Having the same issue with the jumpsuit as Grey, so this doesn't just affect the bandana

**Comment by KasparoVy** [comment]
Resolved by #12124
