### ISSUE TITLE
Something Medborgs don't regen patches something

### ISSUE THREAD

**Issue by Flip-Sandwich** [ParadiseSS13/Paradise#1212]
Being a medborg and going to recharge doesn't regenerate your patches? I'm not sure, all I know is that I was asked by Qinetix to post this bug report here.

**Comment by TheDZD** [comment]
This bug has come up, been fixed, come up again, been fixed again, and now it's back *again*.

**Comment by Keilden** [comment]
better patch it then eh eh eh?
