### ISSUE TITLE
R&D can discover/sync Golem ship research

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#12125]
(I don't exactly understand the problem. It was reported in #post_round_talk, so I'm just forwarding it here for tracking)
**Issue Description**:
1) Golem ship is displayed on R&D console
2) R&D can sync research levels to Golem ship
3) R&D cannot sync research levels to NSS without *also* syncing it to Golem ship
4) R&D syncing research to Golem ship brings its research levels *down* hindering progress.

**What did you expect to happen**: 
Golem ship research is separate from NSS
**What happened instead**:
See above
**Why is this bad/What are the consequences**:
Info leak
Minor break of immersion
Making golem lives needlessly harder
**Steps to reproduce the problem**:
Unsure
**When did the problem start happening**:
Unsure
**Extra information**:
I'm unsure if z-levels are at play here, from the chat log it _might_ be that golem ship was at the same z-level when the bug manifested, or if it was like that from the start.

Post-game discussion excperts of the round where it happened (starting around https://discordapp.com/channels/145533722026967040/565872046312259594/616469864697036830):

> Golem: Through really complex situations golem ship ended up dropping 2 Durands onto station
> RD: WAIT
> RD: there WAS a golem ship?
> RD: I asked engineering to FIND it because the golem ship was also getting engineerings protolathe server access
> Golem: I SOMEHOW GOT THE CYBERIAD'S TECH LEVELS THAT WERE LOWER THAN OURS
> RD: engineering said "no ship"
> RD: we had golems in science
> RD: Wait
> RD: were you golem ship?
> Golem: YES
> Golem: I was the humanized golem
> RD: HAHAHAHA im so sorry
> RD: I detected you on the servers
> Golem: How the fuck did cyberiad's research link to us
> RD: you got in range of them
> RD: and it said "access?"
> RD: and I couldnt give engineering access
> RD: without giving it to you
> Golem: I went to sinchronize the servers
> RD: so I gave it to engineering and told them to FIND you
> Golem: And it just lowered research
> Golem: A fuckton
> RD: and they didnt find you

> Golem: I dunno, it just seems like an oversight or a bug to me
> RD: @ Golem its a bug
> Golem: Being able to link golem ship with no problem
> RD: @SteelSlayer  When I give engineering a protolathe and corisponding console and server, I gotta give them access to the core server right?
> RD: Free Golem Ship will then magically also appear in the server access list - and if I give access to engineering's new toys free golems also get it
> RD: Apparently this screwed the golems early when tech was low
> RD: They synced xD @_@
> Golem: We somehow downloaded cyberiad's research
> Golem: And wiped ours

**Comment by Denthamos** [comment]
Should probably change their R&D setup to a public console setup.

**Comment by Fordoxia** [comment]
Fixed by #24415 I believe.

**Comment by BiancaWilkson** [comment]
See above
