### ISSUE TITLE
Swarmers unable to eat inactive shells

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#12127]
**Issue Description**:
Swarmers are unable to eat inactive shells.

**What did you expect to happen**: 
I expected to click on an inactive shell to recover resources in a pinch and prevent it from being taken by stupid organics.

**What happened instead**:
I longingly stared at the lost resources but nothing happened.

**Why is this bad/What are the consequences**:
This prevents swarmers from recovering resources for defenses or to prevent the shells from being destroyed by hostiles.

**Steps to reproduce the problem**:
1. Be swarmer
2. Print out a baby
3. You can't eat the baby anymore, oh no

**When did the problem start happening**:
I noticed it some time before this report, as it was the first time I'd attempted to eat a shell to recover resources.

**Extra information**:
I think it may have to do with either the swarmer intent locking, or an unintended change with the lavaland swarmers somehow affecting stationside ones.

**Comment by KasparoVy** [comment]
Goes directly against the prime directive of the swarmers as they are destined to expand and eating your own babies for the most part is a bad idea

Could get a salty guy playing a swarmer hunting down other swarmer babies, but that' probably undue paranoia

**Comment by Breenland** [comment]
> Goes directly against the prime directive of the swarmers as they are destined to expand and eating your own babies for the most part is a bad idea
> 
> While it is a significant resource sink it can be rationalized as a balancing factor that helps very slightly temper how ruthless these things are if played even somewhat thoughtfully
> 
> Could get a salty guy playing a swarmer hunting down swarmer babies stealing your hard earned resources, but that' probably undue paranoia
> 
> I feel it comes down to where we want to head in terms of design direction

It was something you were always able to do until recently, and swarmers only have a limit of 200 resources. Each shell costs 50 resources to make. I've never seen your situation happen before, or at least be reported, but I can understand it. However, if this was a change that was supposed to happen, it wasn't documented anywhere, and thus I believe it's an unintended change.
