### ISSUE TITLE
"Your the welding tool is already full!" but "You need more welding fuel to complete this task."

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#12126]
**Issue Description**:
I somehow got into a situation where my welder was full, yet i couldn't weld vents since "You need more welding fuel to complete this task."

In more details:
- Spawned mid-round as nurse
- Did pretty much nothing of use
- We got crawlers on the station, AI asked to weld vents
- Went to cargo for welding gear. Got the helmet and the welder
- Tried welding (have welder in active hand, click on the vent/scrubber). Since "You need more welding fuel to complete this task.".
- Went to the welder tank. Tried refueling the welder. Failed since "Your the welding tool is already full!".
- Examined the welder. "It contains 20 units of fuel out of 20."
- Tried welding again, with no luck.
- Went to robotics to print me an experimental welding tool.
- Tool spawned with 40/40 fuel.
- Same effect. Can't weld since need more fuel, cant' refuel since it's already full.
- Wielding a bucket full of fuel in a spare hand does not help
- No, i didn't accidentally use a screwdriver on the welders (i wasn't in a posession of a screwdriver any time during the round).

**What did you expect to happen**: 
Using welder welds the vent.
**What happened instead**:
See above.
**Why is this bad/What are the consequences**:
N/A
**Steps to reproduce the problem**:
See above/unsure. Other people were successful at the task. I did have my med HUD on, empty medical belt, and advanced health scanner in the pocket. Don't think that matters.
**Extra information**:
![dreamseeker_2019-08-29_05-13-10](https://user-images.githubusercontent.com/7831163/63912842-b7525780-ca1d-11e9-8be2-b61be7f36c1c.png)

**Comment by Shadow-Quill** [comment]
You didn't turn on the welder.
(Hard to weld stuff when you don't have it on!)

Just use it in-hand to toggle it. :P

**Comment by moxian** [comment]
That's super unobvious... I didn't realize you can turn it on..
Can the error message be improved then, to mention that it's turned off instead of (or at least, in addition to) the "it doesn't have enough fuel" one?

**Comment by Citinited** [comment]
Fixed in #11700 but I mean, it's a welder, it should be fairly obvious that it can be turned on :P
