### ISSUE TITLE
Blind Spell Permanently Blinds Slime People

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#12137]
**Issue Description**:
Blind spell makes slime people blind forever
**What did you expect to happen**: 
To not be blind after the intended duration expired
**What happened instead**:
I was blind until the server reset
**Why is this bad/What are the consequences**:
Being blind forever is bad and not fun
**Steps to reproduce the problem**:
Be Slime Person, get hit with blind, be blind for the rest of the game
**When did the problem start happening**:
Not sure only just found it out as blind is a fairly uncommon spell to see
**Extra information**:
I think it's connected to the innate lack of the eye organ in slime person to have the blind status applied to and removed from

**Comment by silverplatedelta** [comment]
Still occurs as of round 38444 / 12/15/23

**Comment by DGamerL** [comment]
This is currently intended, due to the code not removing the effect if the duration is longer than the spell cooldown
```
        if(duration < base_cooldown)
            addtimer(CALLBACK(src, PROC_REF(remove), target), duration, TIMER_OVERRIDE|TIMER_UNIQUE)
```
