### ISSUE TITLE
Lavaland Tendrils Can be pushed/pulled

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12132]
**Issue Description**:
Lavaland tendrils can be pushed with baseball bats/bone spears and pulled using the meat hooks.

**What did you expect to happen**: 
They should be anchored and unmovable.

**What happened instead**:
You can shove those tendrils around like they are little whimps.

**Why is this bad/What are the consequences**:
Allows miners to easily isolate tendrils away from the creatures which should be guarding them.

**Steps to reproduce the problem**:
Spawn tendril, get a baseball bat/spear/hook.  Go to town.

**When did the problem start happening**:

**Extra information**:

**Comment by variableundefined** [comment]
Make a PR that set their move resist to infinity. Mars had one but I closed it since it was unlikely to be followed up on.

Should be a very simple PR.
