### ISSUE TITLE
Lavaland flight potion Broken

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12133]
**Issue Description**:
The flight potion does not give you wings or the angelic race.

**What did you expect to happen**: 
To get wings and become a angel.

**What happened instead**:
Nothing happened.

**Why is this bad/What are the consequences**:
A core item missing from lavaland loot since the potion lets you grow wings that lets you fly over chasms.

**Steps to reproduce the problem**:
Spawn potion, drink potion, be sad.

**When did the problem start happening**:

**Extra information**:

**Comment by Fox-McCloud** [comment]
It quite clearly is a rudimentary implementation of it that's not meant to do anything other than be a holder, even the reagent makes this *explicitly* clear. Please pay attention to the message you get when you actually use it.

```
/datum/reagent/flightpotion/reaction_mob(mob/living/M, method = TOUCH, reac_volume, show_message = 1)
	to_chat(M, "<span class='warning'>This item is currently non-functional.</span>")
```

Also, this isn't available to players, so it has even less relevance. This issue report makes it sound like you can get it---you can't.
