### ISSUE TITLE
Playtime-locked jobs in Occupation Preferences are very hard to read

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#12148]
**Issue Description**:
The jobs that don't have playtime requirements met are shown in white font on light background.
![2019-08-30_11-27-33](https://user-images.githubusercontent.com/7831163/64017542-5740db80-cb19-11e9-961d-49e8f04f6785.png)

**What did you expect to happen**: 
Text having decent contrast
**What happened instead**:
Text is unreadable
**Why is this bad/What are the consequences**:
Gives bad impression of the game to new players.
Hard on the eyes, especially for people with poor eyesight.
**Steps to reproduce the problem**:
1) (optional) Create a new account if your has all jobs unlocked already
2) go to setup character -> Occupation preferences
3) be unable to read text

**When did the problem start happening**:
Probably since forever.
**Extra information**:
Karma-locked jobs are displayed in nice bold readable blood-red. Adapting it for the playtime-locked jobs is one of the solutions i'd be happy with (devising a separate contrrasting colors is another one, but probably more difficult?)

**Comment by Kyep** [comment]
I have no objection to you doing a PR that changes the white text to a more readable color. I only did it that way originally because the previous method did too. In retrospect I should have changed the text colors while I was at it.

**Comment by moxian** [comment]
I'd gladly do a PR, but unfortunately I cannot [easily] do so for legal reasons.
So I'll choose to interpret "you" in the comment above as collective "you, the people who might be reading this message".
