### ISSUE TITLE
Blood Drunk Eye causes you to randomly drop dead

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#12141]
**Issue Description**:

Using the Eye of A Blood Drunk Miner in active combat will cause you to randomly die despite being high above the HP threshold.
**What did you expect to happen**: 

To not instantly die at *yellow* HP.
**What happened instead**:

YOU DIED
**Why is this bad/What are the consequences**:

It makes the blood drunk eye not act like its description would indicate.
**Steps to reproduce the problem**:

1. Get miner eye
2. Walk up to ash drake
3. Start whamming it
4. Randomly die 
**When did the problem start happening**:

Presumably when crusher trophies were merged.
**Extra information**:

It might have to do with some sort of brute loss stacking eventually going over the limit?

Furthermore, I've had this happen with both a drake, and Hierophant.

**Comment by Fox-McCloud** [comment]
I was afraid something like that would happen.

**Comment by MrMagolor** [comment]
This could also have something to do with how newcrit handles instant death with calculating the total damage.
