### ISSUE TITLE
Itallics on papers breaks enters

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#12158]
**Issue Description**:

When using itallics [i]&[/i] (or [sign], it puts a br or something on either side.

**What did you expect to happen**: 

When typing `1[i]2[/i]3` to show `1_2_3`

**What happened instead**:

When typing `1[i]2[/i]3` it showed
```
1

2

3
```

**Why is this bad/What are the consequences**:

muh paperwork

**Steps to reproduce the problem**:

1) Get paper & pen.
2) Write `1[i]2[/i]3` or `1[sign]1`

**When did the problem start happening**:

Broke at this commit: https://github.com/ParadiseSS13/Paradise/pull/11806/commits/9d9bf046e3d54f6e18cefd9c6c2f7097bf21ed38

**Extra information**:

no

**Comment by Shadow-Quill** [comment]
@Tayyyyyyy

**Comment by Tayyyyyyy** [comment]
Small also breaks it. As a workaround, you can use asterisks for italics, I think.
