### ISSUE TITLE
Greys become immune to water too easily

### ISSUE THREAD

**Issue by TheSardele** [ParadiseSS13/Paradise#12164]
**Issue Description**:
Greys become immune to water while wearing a mask or hat.

**What did you expect to happen**: 
For my face to melt off because I touched water.

**What happened instead**:
I can go deep sea diving by wearing a cigarette without melting.

**Why is this bad/What are the consequences**:
I want to tense up again every time a baldie with an extinguisher walks past.
Also, being able to go diving because you're wearing a cigarette on your face is very counter intuitive when your skin is supposed to be dissolved by water.

**Steps to reproduce the problem**:
1. Wear a cigarette in your mask slot as Grey.
2. Take a shower.
3. "Your the cigarette protects you from the acid!"

**When did the problem start happening**:
Probably #11994

**Extra information**:

**Comment by Ty-Omaha** [comment]
>"Your the cigarette protects you from the acid!"

that's hilarious

**Comment by Markolie** [comment]
Their previous interaction with water wasn't quite intentional and was caused by some faulty logic. It's very easy to adjust Grey's to take full water damage with the new water_act support though, so anyone's welcome to put up a pull request to adjust it.

**Comment by JohnBigless** [comment]
> "Your the cigarette protects you from the acid!"
Gotta stay noir somehow.

**Comment by MrMagolor** [comment]
Nanotrasen man immersed in acid, tells death to wait until he's done smoking

**Comment by matttheficus** [comment]
Fairly sure this is due to cigs counting as masks. Would need a logic change to fix I suppose.

**Comment by Burzah** [comment]
This has been fixed at some point along the way. A cigarette and or a hat are no longer enough to protect you from water. Thank you for making the report!

**Comment by Henri215** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/18501
