### ISSUE TITLE
Mime ATM account name is miss-matched.

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12161]
**Issue Description**:
The name on the Mime's ATM account is inaccurate to the picked name.

**What did you expect to happen**: 
For the ATM to display my Name-Picked name.

**What happened instead**:
It was assigned to a default Mime name.

**Why is this bad/What are the consequences**:
Muh immersion. Also be a sign of other miss-matched data with name-pick roles.

**Steps to reproduce the problem**:
Play Mime. Pick a new name. Check ATM account. (also worth mentioning is I consumed a legion soul, which caused Issue #12160 and may be relevant here too.)

**When did the problem start happening**:
No idea.

**Extra information**:
Here's a screen capture.
![mime_account_name_bug](https://user-images.githubusercontent.com/47765135/64060006-bb54b580-cb94-11e9-9549-5987e4ba80bc.png)

**Comment by DGamerL** [comment]
Happens due to names being picked after the round starts, and bank accounts get set up right during it.
