### ISSUE TITLE
Blood lags the game out hard

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12163]
**Issue Description**:
Blood stacks on top of each other. Creating lag piles as a cultist

**What did you expect to happen**: 
Blood not to make your PC crawl to a halt.

**What happened instead**:
In a fight one of the crewmembers reached a whopping 2 FPS (probably a bit more but it was horrid)

**Why is this bad/What are the consequences**:
SS13 should be playable for everybody not just the elite with their 5Ghz CPUs

**Steps to reproduce the problem**:
Blood. Blood blood!!!!!!!!!
No but really just stack multiple blood paths on top of each other. We had like 50+ blood effects on one tile. In the drug base and it was completely full with those tiles

**When did the problem start happening**:
I think since #11797

**Comment by Couls** [comment]
Can't reproduce this on my test server, how did you manage this?

**Comment by farie82** [comment]
might have to do with cult spawned blood. It was in a base which was tightly packed. Lots of fresh runes and teleporting (which damages you since you can bleed from it)

**Comment by farie82** [comment]
Still an issue that breaks the game
