### ISSUE TITLE
Aurora Caelus event broken

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12162]
**Issue Description**:

The Aurora Caelus event no longer plays the music/lights.

**What did you expect to happen**: 

Because it makes the minor event which was a neat little one broken.

**What happened instead**:

Event ticks with the announcement but with no sound/lights.

**Why is this bad/What are the consequences**:

Not a high priority, but a broken event is not nice.

**Steps to reproduce the problem**:

Guessing just que up the Aurora Caelus event .

**When did the problem start happening**:

Since this week.

**Extra information**:

**Comment by iantine** [comment]
As far as I've noticed, it's been since the merging of parallax. Correct me if this is wrong!

**Comment by Ty-Omaha** [comment]
I think it started before that and there is only like one spot where the lights are which is in the top of escape if you turn off the lights

**Comment by Citinited** [comment]
Aurora Caelis triggered last night and it did play the music, but yeah I do remember wondering where the lights were.

**Comment by Drakeven** [comment]
There's lights? I've never noticed them

**Comment by Shadow-Quill** [comment]
better noticed in darkness, it's supposed to be blue/green light shining from each window into space

**Comment by AffectedArc07** [comment]
Event got purged. Closing issue.
