### ISSUE TITLE
ATM Withdrawing Error

### ISSUE THREAD

**Issue by Sihsse** [ParadiseSS13/Paradise#12172]
**Issue Description**:
Withdrawing credits from your account above the limited amount of 10k will cause it to subtract more funds than 10k.

**What did you expect to happen**:
A 10k deduction from the account and a distribution of 10k. 

**What happened instead**:
A deduction from the account greater than 10k though not the initially requested amount either.

**Why is this bad/What are the consequences**:
A break in roleplay immersion though no real last consequences or negative impacts.

**Steps to reproduce the problem**:
Input cash greater than 10k into the ATM. Attempt to withdraw over the max limit of 10k and see that a greater deduction was made instead.

**When did the problem start happening**:
First noticed at the time of this report.

**Extra information**:

**Comment by Mocha-Not-Latte** [comment]
feature though

**Comment by Shadow-Quill** [comment]
Can't quite tell why this happens. I'll do some testing.
```
if(amount > 10000) // prevent crashes
    to_chat(usr, "<span class='notice'>The ATM's screen flashes, 'Maximum single withdrawl limit reached, defaulting to 10,000.'</span>")
    amount = 10000
authenticated_account.money -= amount
withdraw_arbitrary_sum(amount)
```
