### ISSUE TITLE
Combat gloves no longer have armor

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12182]
**Issue Description**:

Nuclear ops/syndicate combat gloves no longer have armor values.

**What did you expect to happen**: 

Nuclear ops and syndicate combat gloves should have armor due to the role they fill.  I assume this was an undocumented change not not put in as a balance PR.

**What happened instead**:

Their gloves are no long armored at all.

**Why is this bad/What are the consequences**:

Makes it really easy to break operatives/traitors hands.  Additionally effects some ERT and CC officers.

**Steps to reproduce the problem**:

Just VV check the combat gloves.  Nothing.

**When did the problem start happening**:

I remember they had armor at the start of this year, but only checked it recently when I noticed hands being broken a lot easier than normal for nuclear teams and agents.

**Extra information**:

**Comment by Fox-McCloud** [comment]
They never have. This is a feature request.
