### ISSUE TITLE
Jackboots and variants no longer have armor

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12181]
**Issue Description**:

Jackboots and the other variant security has no longer has its melee armor value like it used to.

**What did you expect to happen**: 

The jackboots should still have their melee resistance armor value as its removal was not documented in any change as a PR balance update.

**What happened instead**:

See above.  Boots no longer have armor.

**Why is this bad/What are the consequences**:

Makes it super easy to break securities feet.

**Steps to reproduce the problem**:

Just open the VV on the boots and check the armor value.  Nothing.

**When did the problem start happening**:

They used to have armor last I checked at the start of this year.  Only bothered checking again recently when I noticed officers feet were being broken really easily.

**Extra information**:

**Comment by Fox-McCloud** [comment]
They never have. This is a feature request.
