### ISSUE TITLE
Washing a hooded suit does not clean the hood

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#12192]
**Issue Description**:

Washing a hooded suit (i.e. explorer suit) after removing it does not make the hood clean.

**What did you expect to happen**: 

If you're dumping the full suit in water, shouldn't it clean all of it?

**What happened instead**:

Apparently hoods are kept in bluespace.

**Why is this bad/What are the consequences**:

Muh immersion, basically.

**Steps to reproduce the problem**:

Step 1. Get a hood on a suit dirty/bloody/etc.
Step 2. Try to wash it, i.e. with a washing machine
Step 3. Put suit back on, and put on hood
Step 4. Notice that the dirt/blood/etc. still exists.

**When did the problem start happening**:

As far as I can tell it's always been this way.

**Extra information**:

I only noticed this with explorer suit, but I presume all hooded suits act the same.

You can workaround this with anything that cleans the whole body at once (i.e. showers).

**Comment by Henri215** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/ea3026b9-6055-4dfb-a55e-6a34785dcfa2)

Could replicate.
