### ISSUE TITLE
uplink-bought syndie hardsuits don't have the helmets integrated

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#12196]
**Issue Description**:
Syndicate hardsuits you buy from the uplink do not come with integrated helmets. this is inconsistent with #12073 

**What did you expect to happen**: 
For all helmets to now be integrated

**What happened instead**:
The helmet was separate and had to be added manually

**Why is this bad/What are the consequences**:
Inconsistency

**Steps to reproduce the problem**:
be syndie, buy hardsuit

**When did the problem start happening**:
Since forever but it was made inconsistent with other hardsuits with #12073

**Extra information**:

**Comment by Fox-McCloud** [comment]
I can't reproduce this at all.

I purchased, from the uplink, the regular hardsuit, the elite hardsuit, and the shielded hardsuit.

I was able to toggle my helmet for each of them---and was able to toggle the mode for the regular hardsuit and elite hardsuit.

Everything is functioning as intended.

**Comment by TDSSS** [comment]
Huh, weird. Sorry in that case.
