### ISSUE TITLE
Jetpacks not working

### ISSUE THREAD

**Issue by Magentaformula0** [ParadiseSS13/Paradise#12202]
**Issue Description**:

The jetpacks wont work

**What did you expect to happen**: 

Cause you cant use them

**What happened instead**:

It wouldnt let you move in space freely like it should,

**Why is this bad/What are the consequences**:

You cant move in space when you should. And floating away from the station while deciding which thing you can throw to get back. 

**Steps to reproduce the problem**:

Just put on the jetpack (the ones from eva have been my problem but it might be all normal jetpacks)

**When did the problem start happening**:

Like last week I think. 

**Extra information**:

**Comment by SteelSlayer** [comment]
They're working fine for me right now. Gotta ask the basic questions: Is it on your back? Does it have fuel? Did you toggle it on?

**Comment by Fox-McCloud** [comment]
We should really probably repath tanks so you can only put internals in the suit storage slot

`/obj/item/tank/internals` would fit, but `/obj/item/tank` would not.

**Comment by Magentaformula0** [comment]
> They're working fine for me right now. Gotta ask the basic questions: Is it on your back? Does it have fuel? Did you toggle it on?

I had it in my suit storage on an eva suit. Do you mean it was on your back is your back pack slot? And yes I verified it was toggled on and verified multiple times that it was full.

**Comment by SteelSlayer** [comment]
Ah yeah, you can put jetpacks in your suit storage slot but they don't work, they need to go on your backpack slot. As Fox pointed out above it would be better to make them impossible to put in the suit storage slot so people don't get confused

**Comment by Magentaformula0** [comment]
Oh so that is a change. Are you able to store your bag in your suit storage at least to balance that change out. Otherwise it kind of ruins space exploration of the mechanic job. Making it difficult to collect anything in space.

**Comment by Fox-McCloud** [comment]
We're not re-adding jetjpack easy mode.

Inventory creep is horrific on TG and Paradise--jetpacks were a step to far.

If you want to get the ease of not having fiddly inventory with a jetpack, you're going to have to acqurie a hardsuit and a mining jetpack upgrade.
