### ISSUE TITLE
Welding fully repaired, exposed plating damages the eyes.

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12205]
**Issue Description**:
When using a welding tool on plating, even fully repaired plating, you'll start to go blind and take eye damage if you lack protection.

**What did you expect to happen**: 
I expected to not blind myself, without properly deciding to repair the tile. especially considering with #12002 added an extra step as to not be able to blind yourself this way. #12055 Obviously changed the behavior again, re-introducing the problem.

**What happened instead**:
I blinded myself on accident.

**Why is this bad/What are the consequences**:
It's the same problem #12002 fixed, which is that it makes blobs extremely difficult to fight with welders, as you're spam clicking frequently and will accidentally weld plating.

**Steps to reproduce the problem**:
Take welder. Weld exposed plating. See no fuel consumed. See white screen and take eye damage.

**When did the problem start happening**:
It might have something to do with #12055 , as this reintroduced functionality of welding to repair tiles without needing the extra step. However the whole issue has been around since #11658 and was thought to be fixed by #12002 but I'm unable to confirm that this indeed fixed the issue. So it was either never fixed by #12002, or #12055 reintroduced it.

**Extra information**:
_Your eyes sting a little._

**Comment by JKnutson101** [comment]
Writing at midnight caused me to leave out the fact that I was mentioning welding plating in the title 😄
