### ISSUE TITLE
Plasmaman Chaplain doesn't spawn with Null Rod

### ISSUE THREAD

**Issue by Spyder904** [ParadiseSS13/Paradise#12210]
**Issue Description**:

When spawning as a plasma man Chaplain, all it gives you is your suit, and your plasma tank. Plus your Bible, but that's below you when you make it.

**What did you expect to happen**: 

Well... I expected the Null Rod. If the Chap loses their null rod, they're losing one of their key components.

**What happened instead**:

Well, simple. It doesn't spawn. Anywhere.

**Why is this bad/What are the consequences**:

Without the Null Rod, Chap loses his main form of defense, and a possibly fun weapon.

**Steps to reproduce the problem**:

Select Plasmaman race, Turn Chap to High. Become Chap. No Rod

**When did the problem start happening**:

My first round as plasmaman Chaplain.

**Extra information**:

This is likely caused by too many things in a plasma man's hands- a tank and a suit. Either rid the suit completely, or have plasmamen spawn with their tanks in their pockets/belt

**Comment by Shadow-Quill** [comment]
Fixed in #12357.
