### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by realtaac** [ParadiseSS13/Paradise#12214]
**Issue Description**:
Under mining there is a item called "name" for 0 mats

**What did you expect to happen**: 
make mining things

**What happened instead**:
see something named "name

**Why is this bad/What are the consequences**:
It shouldn't be there

**Steps to reproduce the problem**:
look in mining under RnD

**When did the problem start happening**:
this week i think

**Extra information**:
![name](https://user-images.githubusercontent.com/44135166/64406907-3e1bbb80-d040-11e9-9e78-367ccadf8d61.png)

**Comment by SomeSortaSquid** [comment]
It's the base design datum from designs.dm, which somehow gets added to mining category. It also can be found in exosuit fabricators, in cyborg upgrades modules category.
Doesn't seem to appear in any category in autolathe or circuit imprinter.

**Comment by Spacemanspark** [comment]
Name
