### ISSUE TITLE
Emotes over radio are capitalized

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#12222]
**Issue Description**:

The first word when doing a radio emote (`;!`, `.h!`, etc.) is capitalized.

**What did you expect to happen**: 

`[Common] John Doe laughs!`

**What happened instead**:

`[Common] John Doe Laughs!`

**Why is this bad/What are the consequences**:

😠 

**Steps to reproduce the problem**:

1) Emote over radio.

**When did the problem start happening**:

Within the past week.

**Extra information**:

louder command setting: ✔️ 
was command: ✔️

**Comment by Christasmurf** [comment]
For the "Why is this bad" could have put something about immersion or like, "it just ruins the flow of the message" but an angry face pretty much sums up both of those anyway

**Comment by SteelSlayer** [comment]
This is my fault and I know exactly what's causing it. I made command messages get capitalized when louder command was on. Obviously I didn't do a very good job because it works on emotes. Damn telecomms code

**Comment by JohnBigless** [comment]
Sweet inconsistence.

**Comment by SomeSortaSquid** [comment]
Just remove telecommunication.
All problems solved at once.
