### ISSUE TITLE
"Hotkeys" menu option does nothing

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#12234]
**Issue Description**:
"Help" -> "Hotkeys" BYOND button does nothing

**What did you expect to happen**: 
Show hotkeys

**What happened instead**:
Nothing

**Why is this bad/What are the consequences**:
Can't look up hotkeys

**Steps to reproduce the problem**:
Click Help -> Hotkeys

**When did the problem start happening**:
Either it worked ~a month ago, or I tried that on Beestation that one time i did.

**Extra information**:
no

**Comment by realtaac** [comment]
hotkeys are shown under OOC > Hotkey help

**Comment by moxian** [comment]
That's true!

I've just checked Beestataion, they, too have OOC > hotkey-help button, and it does the exact same thing as their Help > Hotkeys.

I'd argue moving/duplicating this functionality to main window menu is a good thing.
