### ISSUE TITLE
Can no longer draw multiple fake runes on a single tile.

### ISSUE THREAD

**Issue by JKnutson101** [ParadiseSS13/Paradise#12244]
**Issue Description**:
One used to be able to draw multiple fake rune on a tile in crayon, now can only draw one fake rune per tile. I believe this feature was removed unintentionally, because you can still attempt to draw multiple runes, and a timer will pop up while drawing, but nothing appears once the drawing is finished.

**What did you expect to happen**: 
I expected to be able to draw multiple runes per tile. Alternatively, to just reject the attempt to draw a second rune and not start a needless timer.

**What happened instead**:
I got a timer AND no extra fake rune! It took a whole 3 SECONDS from my life!

**Why is this bad/What are the consequences**:
The high levels of roleplay achievable by drawing multiple fake runes are no longer possible in the game's current state, and it's clear that everyone is suffering terribly from their loss. Alternatively, if the performance increase of removing the ability to add multiple fake runes has more value, then spawning timers that inevitably fail with no feedback to the player is minor, but still an issue.

**Steps to reproduce the problem**:
Find crayon. Draw fake rune. Switch fake rune number you wish to draw. Try drawing on the same tile. See the deception of the progress bar and lament as your newly founded cult is stunted by artistic limitations.

**When did the problem start happening**:
Pretty sure it was #12167 . It's a side effect of a MUCH NEEDED fix to the blood stacking issue.

**Extra information**:
I understand this is a real non-issue to 99.99% of the playerbase, but I've had a lot of fun scribbling a bunch of fake runes on a single tile, and making silly summoning circles. Enough fun that I felt the need to write an entire issue report about it. Will close if maintainers deem far too trivial an issue.

**Comment by Pixelzilla** [comment]
I hope this gets fixed. This impacts the graffiti that are meant to overlay ontop of one another to make cool multi-colored designs. You cant have more than one graffiti on a tile and thats just...sad! :(
