### ISSUE TITLE
Placing wooden chairs instead places down a normal metal chair

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#12252]
**Issue Description**:
Placing wooden chairs instead places down a normal metal chair

**Steps to reproduce the problem**:
1. Pick up a wooden chair
2. Press Z with it in your active hand

**When did the problem start happening**:
Unknown, reported on 9/9/2019 by Ansari

**Comment by variableundefined** [comment]
Confirmed. However it is the icon_state that is wrong, while the chair itself has the right typepath
