### ISSUE TITLE
Some items cure roundstart disabilities when they shouldn't

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#12254]
**Issue Description**:

The following removes roundstart disabilities: Legion core, mutadone, etc

**What did you expect to happen**: 

Not to be able to talk after using one of the above.

**What happened instead**:

I could talk!

**Why is this bad/What are the consequences**:

I can't be mute when I talk, now can I?

**Steps to reproduce the problem**:

1) Roundstart disability.
2) Use item above.

**When did the problem start happening**:

With legion cores, probably.

**Extra information**:

no

**Comment by KasparoVy** [comment]
Roundstart disabilities can be removed with mutadone and such too
