### ISSUE TITLE
necropolis tendrils spawning inside ruins

### ISSUE THREAD

**Issue by DoctorDrugs** [ParadiseSS13/Paradise#12257]
**Issue Description**:
necropolis tendrils spawning inside ruins

**What did you expect to happen**: 
to not have necropolis tendrils spawn inside ruins like the golem ship or similar type ruin

**What happened instead**:
see tendrils and mobs inside a golem ship/ruin

**Why is this bad/What are the consequences**:
this can prevent access to a ruin or cause a quick death if a door is opened and the a person walks face first into three goliaths or watchers and gets blasted thinking the ruin was safe to enter

**Steps to reproduce the problem**:
check out the ruins on lavaland, seems to be a rare situation might take multiple attempts to locate a similar issue

**When did the problem start happening**:
not sure exactly, just saw the necropolis tendril in the golem shuttle very recently

**Extra information**:
currently only observed necropolis tendrils to spawn in the golem ship and in the outer walls of hiero's arena

![tendril](https://user-images.githubusercontent.com/10556843/64604596-6c76ff00-d390-11e9-9378-3d54a9a96d02.png)
![tendril in shuttle](https://user-images.githubusercontent.com/10556843/64604607-70a31c80-d390-11e9-81c8-e834b951e98c.png)

**Comment by MrMagolor** [comment]
I've also seen one spawn in the syndicate base, clown biodome, etc.
