### ISSUE TITLE
Staff of storms infinite ash storm noise

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12275]
**Issue Description**:

Using the staff of storms on the station seems to cause the entire server to hear the ash storm precursor storm track nonstop no matter where you are.

**What did you expect to happen**: 

The ash storm sound clip should only play when you are in the area defines it is used in.

**What happened instead**:

The entire server was hearing the ash storms across the entire station and locations in space for the duration of the entire round.

**Why is this bad/What are the consequences**:

Obviously, because nonstop ash storm noises till the round ends is bad.

**Steps to reproduce the problem**:

Player used the staff of storms in mining on the station and in viro.

**When did the problem start happening**:

Unsure exactly on this, I do not remember a specific instance of this occurring prior to two weeks ago, but it could be because no one used the staff on station to make an ash storm.

**Extra information**:

**Comment by Dave-TH** [comment]
The entire z-level hearing the ash storm sounds is as intended.
Cannot reproduce the infinite sound loop locally, do you have any additional information that might help? (Did admins try to stop the storm early, was the staff being spammed excessively, etc?)
Thanks!

**Comment by Denthamos** [comment]
Have not seen this happen in a long while, so assuming that whatever caused this bug has not arisen again.  If spotted again ill re-open this bug report with more info.
