### ISSUE TITLE
Space pods can hold infinite items

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12279]
**Issue Description**:

Space pods can hold an infinite amount of items by using the rest command while holding items inside a pod.  Then you can over time retrieve all these items over time using the verb to check under the space pods seats.

**What did you expect to happen**: 

For the space pod to have limited interior storage.

**What happened instead**:

Freaking bluespace storage pods.

**Why is this bad/What are the consequences**:

Infinite storage of items is bad in a limited storage game, especially with a mobile storage.

**Steps to reproduce the problem**:

Get space pod, drop items in pod, profit.

**When did the problem start happening**:

Probably has existed since pods have been in the code.

**Extra information**:

**Comment by Tayyyyyyy** [comment]
The more items you store, the harder it is to get the item you want, though, so it's kinda balanced.

**Comment by BakKeener** [comment]
There is also the fact you are able to get items from under the seat, that verb would become redundant if you couldn't rest. It also isn't abused either and I doubt anyone is putting a obscene amount of items in a pod which means people aren't breaking a "space" boundary in terms in storage. Perhaps instead adding a inventory system to the pod would be better.

**Comment by lewcc** [comment]
Space pods aren't in the code anymore, so this should probably be closed.

**Comment by matttheficus** [comment]
Begone, pods.
