### ISSUE TITLE
Xenobiology Gold Slime 'Spawn friendly critter' can create invisible dog

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#12283]
**Issue Description**:
A xenobiologist using a gold slime injected with water to create a friendly critter can make an invisible mob called 'dog'.

**What did you expect to happen**: 
It seems to not have a sprite assigned. I expected to receive any of the sprite-assigned friendly mobs, and at first, thought I'd done something wrong- only on right-clicking around did I find the invisible 'dog'.

**What happened instead**:
Upon injecting the gold slime with water, I was presented with a spriteless dog.

**Why is this bad/What are the consequences**:
Confusing, and also, the spriteless dog was able to accept a sentience potion and become a spriteless sentient mob.

**Steps to reproduce the problem**:
Inject water into a gold slime core, producing a friendly mob. This happened for me on the first try, but due to the random nature of the mob spawn, could take many tries. The second time I did it, a regular pug spawned.

**When did the problem start happening**:
13/09/2019

**Extra information**:
Mob could be dragged, interacted with etc. as normal. Just missing the sprite.
![dog](https://user-images.githubusercontent.com/26665535/64860756-683d3100-d671-11e9-803e-ed2749a879f6.png)

**Comment by Ty-Omaha** [comment]
![](https://i.imgur.com/igpvtok.png)
