### ISSUE TITLE
Janitor job allows latejoins when it shouldn't

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#12297]
**Issue Description**:

People can latejoin as janitor, even when there's a roundstart one.

**What did you expect to happen**: 

Nobody to take my precious supplies.

**What happened instead**:

They could.

**Why is this bad/What are the consequences**:

Job slots are a lie.

**Steps to reproduce the problem**:

1) Be Janitor role (unsure if you need Custodial Technician title)
2) Watch as someone can latejoin as a Janitor. (Maybe no alt title?)

**When did the problem start happening**:

unsure

**Extra information**:

I had the alt title of `Custodial Technician`, they were just a ~~plebeian~~ `Janitor`.

**Comment by TDSSS** [comment]
Not a bug, see #8995
The game automatically opens a second job slot.

**Comment by Shadow-Quill** [comment]
doesn't really make sense, considering there's only ever one janicart, but whatever
