### ISSUE TITLE
The Atmos hardsuit sprite does not show up when you hold it in your hand

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#12299]
**Issue Description**:
The Atmos hardsuit sprite does not show up on your character when you hold it in your hand

**Why is this bad/What are the consequences**:
It's a bug :angry: 

**Steps to reproduce the problem**:
1. Pick up an atmospherics hardsuit in your hand
2. Observe that there is no atmos hardsuit sprite on your character

**When did the problem start happening**:
Fairly recent, the past week maybe?

**Extra information**:
This may be affected other hardsuits as well, not sure, I've not tested them yet

**Comment by Dave-TH** [comment]
Issue is resolved with #12313 and should probably be closed.
