### ISSUE TITLE
Light replacers are not working properly.

### ISSUE THREAD

**Issue by Sheppysneik** [ParadiseSS13/Paradise#12305]
**Issue Description**:
Replacing the lights or placing lights on new light fixtures will result in the light being placed, and then hit from the light replacer right after. 

**What did you expect to happen**: 
The light should be replaced, and then NOT hit right after, causing sometimes his destruction

**What happened instead**:
The light has been hit right after the placement, causing sometimes his destruction.

**Why is this bad/What are the consequences**:
Janitors can no longer rely on the light replacer, as the destruction of the light will sometimes have the janitor shocked if not wearing insulating gloves. also it's annoying.

**Steps to reproduce the problem**:
Locate a certain number of light fixture with broken light or with no light, apply light replacer, see as the light smashes right after the placement on most light fixtures. 

**When did the problem start happening**:
About one or two weeks ago?

**Extra information**:
This applies to the drone's light replacer, and maybe the janitor borg module one too.

**Comment by SteelSlayer** [comment]
I've heard about this a couple of times, can't confirm myself but it may have something to do with the light replacer changers in this PR: https://github.com/ParadiseSS13/Paradise/pull/12255. As an alternate method of replacing lights though, you can stand next to the light fixture and press Z while you have the replacer in your hand. It will automatically place lights into fixtures adjacent to you
