### ISSUE TITLE
Lethal Injections Syringes aren't lethal

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#12306]
**Issue Description**:
Lethal injection syringes don't kill

**What did you expect to happen**: 
For someone to die when injected with a lethal injection syringe
They didnt

**When did the problem start happening**:
Probably newcrit

**Comment by TheSardele** [comment]
Having tested this locally, a single syringe is just about enough to kill someone, though not very humanely. Judging from the discord, the reason that someone survived it was that they had a healing virus. Either way, they should probably be made more lethal.

**Comment by BakKeener** [comment]
Yeah the reason they survived was purely due to healing virus which was overly stated that round. Also Cyanide is  still a poor chem for murder.
