### ISSUE TITLE
Lights can be hit at well.. the speed of light

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#12317]
**Issue Description**:

Lights can be hit really fast

**What did you expect to happen**: 

Lights to have a cooldown on being hit 

**What happened instead**:

Slings got buffed

**Why is this bad/What are the consequences**:

Slings don’t need buffs

**Steps to reproduce the problem**:

Pick up item
Find light fixture
Spam click light fixture

**When did the problem start happening**:

#12307

**Comment by Tarhalindur** [comment]
Replicated.
