### ISSUE TITLE
Unflipped table sprites are fucked

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#12312]
**Issue Description**:

When you unflip a table, the sprites are completely broken.

**What did you expect to happen**: 

The sprites to look normal.

**What happened instead**:

They came from the upside down.

**Why is this bad/What are the consequences**:

*scream

**Steps to reproduce the problem**:

1) Flip table.
2) Unflip table.
3) Cry in despair.

**When did the problem start happening**:

???

**Extra information**:

This was on tables with more then one table.

**Comment by matttheficus** [comment]
Fairly sure this is still an issue.
