### ISSUE TITLE
Holodeck can make stools

### ISSUE THREAD

**Issue by Tarhalindur** [ParadiseSS13/Paradise#12329]
**Issue Description**:
Stools thrown out of the holodeck don't disappear

**What did you expect to happen**: 
The stools would disappear.

**What happened instead**:
They didn't.

**Why is this bad/What are the consequences**:
You can now essentially get infinite stools.

**Steps to reproduce the problem**:
1. Put the holodeck in meeting room
2. Pick up stool
3. Throw stool out

**When did the problem start happening**:
As soon as I tried (so at least today as of filing).

**Extra information**:
May be related to mats not disappearing. My guess is that items need a specific flag in order to disappear, which stools don't have. Could be fixed by introducing a special variant of the stool.

**Comment by taukausanake** [comment]
I think because they are normal stools, not holostools. I tried fixing it but I forget what happened

**Comment by Mitchs98** [comment]
This is still a thing unless they were mapped in to be fixed or otherwise fixed through find/replace. Holodeck stools are still normal stools.

**Comment by AffectedArc07** [comment]
I meant to close another issue, my bad
