### ISSUE TITLE
Blood Drunk spawn does not occur every round

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#12324]
**Issue Description**:

The Blood-Drunk Miner's arena does not always spawn.

**What did you expect to happen**: 

Since he is a unique megafauna, like Hierophant, I would think that his arena would always spawn.

**What happened instead**:

Having to either A. use KA like a coward, or B. trying to fight megafauna in melee with ordinary damage resistances.

**Why is this bad/What are the consequences**:

Without the Eye of a Blood-Drunk Miner, using crusher is even MORE impossible.

**Steps to reproduce the problem**:

Step 1. Play miner
Step 2. Check GPS on lavaland
Step 3. Notice that there isn't always a resonant signal at roundstart

**When did the problem start happening**:

One of the lavaland updates, of course. At least, that's what I think.

**Extra information**:

I reported this as an issue, since Fox said on the discord that without the miner eye using crusher against megafauna is more or less impossible (and I agree).

**Comment by Fox-McCloud** [comment]
This is a feature request--the blood drunk is *not* supposed to be a guaranteed spawn; only the Hierophant is.
