### ISSUE TITLE
Bluespace translocation event teleports observers to the void

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#12331]
**Issue Description**:

If you happen to be a observer and inside of the area, where the bluespace anomaly triggers the bluespace translocation event, it just puts you into the void where your screen is black and you can't do anything without admin's intervention.

**What did you expect to happen**: 

To not be put into the void by the bluespace translocation event as a observer.

**What happened instead**:

A observer was put into the void where they can't do anything without admin intervention.

**Why is this bad/What are the consequences**:

You cannot fly around as a ghost while in the void.

**Steps to reproduce the problem**:

1. Spawn in a bluespace anomaly
2. Be in the area of the bluespace anomaly as a observer
3. Wait for it to go off

**When did the problem start happening**:

Not certain, probably for a long time, but today (2019-17-09) was the first time I seen it happen.

**Extra information**:

Teleporting the player fixed the issue.

**Comment by PidgeyThePirate** [comment]
I attempted to replicate this on my personal test server and couldn't do it. The anomaly does however teleport ghosts, which shouldn't happen, and fixing that should fix the issue.

**Comment by dovydas12345** [comment]
I suppose something broke with teleporting then. So yeah fixing it teleporting ghosts should fix the issue.

**Comment by JKnutson101** [comment]
@variableundefined sorry for the ping, just going through the issues and found one to close cause #12433 fixed it.
