### ISSUE TITLE
Brig Timers Are Psychic

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#12349]
**Issue Description**:
Stopping a brig timer as an admin using aghost and admin interaction results in the timer broadcasting it was 'stopped by YOURCHARNAME' on sec radio. This is despite you being a ghost.

**What did you expect to happen**: 
It shouldn't say anything on the radio.

**What happened instead**:
It did say it.

**Why is this bad/What are the consequences**:
Sec radio: "why is (character who is not in the round, let alone playing as sec) stopping brig timers?"

**Steps to reproduce the problem**:
1. Be an aghost
2. Click a brig timer
3. Select the option to stop the timer
4. Listen to radio

**Comment by Ty-Omaha** [comment]
https://github.com/ParadiseSS13/Paradise/blob/5e8517d9a91a79107ad0ef0e60e626e0047dbe66/code/game/machinery/doors/brigdoors.dm#L378

https://github.com/ParadiseSS13/Paradise/blob/7918692dd048890ddaebf932987aeb554a30d9e3/code/game/objects/items/devices/radio/radio.dm#L236
