### ISSUE TITLE
Chaplain plasmamen doesn't get nullrod when spawned

### ISSUE THREAD

**Issue by Tourte-Yaya** [ParadiseSS13/Paradise#12354]
**Issue Description**: Chaplain plasmaman doesn't get a nullrod once they spawn.

**What did you expect to happen**: Nullrod in chaplain possesion once they spawn.

**What happened instead**:Plasmaman chaplain get his plasma tank instead of his nullrod in active hand.

**Why is this bad/What are the consequences**: Chaplain can't get a nullrod until he ahelp.

**Steps to reproduce the problem**:
1. Select plasmaman
2. Spawn as chaplain with a plasma tanks in the active hands instead of nullrod.

**When did the problem start happening**:Plasmaman chaplain spawned with a nullrod before their rework.

**Extra information**: Plasma tank/nullrod should be in pocket once spawned for prevent this.

**Comment by taukausanake** [comment]
Duplicate of #12210
