### ISSUE TITLE
Antag picker bug

### ISSUE THREAD

**Issue by Svej** [ParadiseSS13/Paradise#1235]
When you get chosen for ling, but returned to lobby, you miss the changeling tab, and an admin has to fix it for you.

Also, you can get any antag status, and join in as whatever you want, without it removing it. traitor captain for example.

**Comment by veganzombeh** [comment]
This is pretty much #1147, which wasn't considered a bug at the time.

**Comment by theColdflame** [comment]
As a returntolobby preference user I've experienced this on several occasions. One fix I can think of is forcing the player into civ if the system fails, which is preferable to them being able to choose a job that best fits their objectives
