### ISSUE TITLE
Changelog doesn't auto update in game

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#12361]
**Issue Description**:
CL doesn't auto update in game

**What did you expect to happen**: 
For CL to auto update in game

**What happened instead**:
It doesn't but makes commits?
https://github.com/ParadiseSS13/Paradise/commit/6378e6e2e63038d29247d3c20aa98aacd0c61e24

**When did the problem start happening**:
After the host switch

**Extra information**:
Is it this? https://github.com/ParadiseSS13/Paradise/blob/6fe83a698757f023d26171355fff906d95ee764b/tools/makeChangelog.bat
?
https://github.com/ParadiseSS13/Paradise/blob/c4df6e5b135a2b10c314b0361aae79c59775ee93/tools/ss13_genchangelog.py

**Comment by AffectedArc07** [comment]
There are 2 changelog generators. The webhook which makes `Automtic changelog generation` after each PR is merged, and the python bot which makes `Automatic changelog compile`, which turns all the PR CLs into the main file. The webhook is executed on PR merge, the python script executed on cron timer (every hour or so). 

There is a reason the changelog compiler hasnt been set up yet but I am not going into details.

**Comment by farie82** [comment]
Fixed
