### ISSUE TITLE
Devil keeps lizard face when de-leveling

### ISSUE THREAD

**Issue by Darkmight9** [ParadiseSS13/Paradise#12366]
**Issue Description**:
When depowering from dark lizard form to your original species you keep the lizard face and don't regain your original face

**What did you expect to happen**: 
When I depowered that my face would go back to normal

**What happened instead**:
I became a Skrell with a dark lizard face.

**Why is this bad/What are the consequences**:
It's both a visual bug and a give away that the person is a devil.

**Steps to reproduce the problem**:
Obtain 3 souls and become dark lizard form. Lose a soul and go back to original form.

**When did the problem start happening**:
Don't know

**Extra information**:
I was a Skrell.

**Comment by Ty-Omaha** [comment]
Also they dont have unathi language and galactic common so they cant understand anyone

**Comment by SabreML** [comment]
Devils got nuked by #15672, so no longer an issue.
