### ISSUE TITLE
Devil loses Gal common language when de-leveling from lizard form

### ISSUE THREAD

**Issue by Darkmight9** [ParadiseSS13/Paradise#12365]
**Issue Description**:
When you lose a soul level and go back to original form(from lizard to whatever you were before you got 3 souls) you loose the ability to speak gal common 

**What did you expect to happen**: 
When I depowered I would still be able to speak Gal common

**What happened instead**:
I lost gal common but kept Skrellian and Neo-Russkva

**Why is this bad/What are the consequences**:
Devils NEED to be able to talk regularly. If they loose the common language then they can't make deals.

**Steps to reproduce the problem**:
Obtain 3 souls as devil and power up to lizard form. Lose a soul and de power to original form. Try to speak Gal common.

**When did the problem start happening**:
Don't know

**Extra information**:
My character was a Skrell if that means anything

**Comment by Ty-Omaha** [comment]
i noticed sometimes giving gal. common worked, while other times they as a unathi did not have the unathi language. giving them the unathi language fixed it in that case.

**Comment by Ty-Omaha** [comment]
#12366 related

**Comment by SabreML** [comment]
Devils got nuked by #15672, so no longer an issue.
