### ISSUE TITLE
Able to inject into robotic limbs.

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12367]
**Issue Description**:
I was able to use an emergency auto-injector on myself as an IPC.

**What did you expect to happen**: 
I expected this to not work, and give me feedback saying 'this limb is robotic'

**What happened instead**:
Instead I consumed the auto-injector, and likely gave myself the chemicals, though I had no way of checking.

**Why is this bad/What are the consequences**:
Robotic limbs should not be able to be injected into.

**Steps to reproduce the problem**:
Be IPC. Open oxygen box and inject yourself with emergency auto-injector.

**When did the problem start happening**:
#12343 would be my honest guess, considering they have hybrid synth-organic limbs now.

**Comment by Spaghetti-bit** [comment]
Unable to find the Pr but this issue has been fixed for a while, trying to inject a robotic limb says, “this limb is robotic!”
