### ISSUE TITLE
Using Etheral Jaunt while stunned lets you crawl and become unstunnable for a period of time.

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#12385]
**Issue Description**:

As Stated in the title.

**What did you expect to happen**: 

I expected them to be stunned and not move at all.

**What happened instead**:

They were crawling around and I couldn't stun them so they just kept crawling around being annoying

**Why is this bad/What are the consequences**:

Wizards shouldn't be able to move while downed and they may in fact be able to do other things that I'm unaware of such as possibly wield a item while on the ground.

**Steps to reproduce the problem**:

Stun Wizard, Wizard does Jaunt, Wizard returns from jaunt, Wizard can crawl around and not be stunned.

**When did the problem start happening**:

I have no Idea when the bug appeared but I discovered it a bit before 3 AM on 9/22/2019

**Comment by Spacemanspark** [comment]
Magic

**Comment by matttheficus** [comment]
Likely fixed with Spellcode Refactor, will need testing.

**Comment by chuga-git** [comment]
This issue no longer exists after the introduction of actual crawling.
