### ISSUE TITLE
Chemicals stack with each other, example: Meth + Nuka Cola

### ISSUE THREAD

**Issue by Abydos2** [ParadiseSS13/Paradise#12390]
**Issue Description**:
Chemicals such as Nuka Cola, Meth, Ultra Lube are stacking upon each other.

**What did you expect to happen**: 
That only one of the chemicals would react.

**What happened instead**:
All three of them were stacking.. giving mobs such as Vox, very fast movement speed around the station. Also giving them a stack effect of stun resistance, like having an anti-stun implant within you.

**Why is this bad/What are the consequences**:
It's mainly bad because any player, be them antag or not, can effectively get from one point of the station to the other within a very short amount of time, as well as being highly resistance to stuns. Only stunned for a small time of 2-4 seconds.

**Steps to reproduce the problem**:
Spawn in a mob, such as a human.
Give them Nuka-Cola + Meth
Move around, watch how fast you go.
Give yourself a stun baton and stun yourself, watch how low you are down for.

For a mob, such as Vox:
Same as above, but give yourself Ultra lube as well.

**When did the problem start happening**:
Not entirely too sure but it's been happening around the station for a while now.

**Extra information**:
None that I can think of.

**Comment by Kyep** [comment]
Meth and ultra-lube both use GOTTAGOFAST_METH:
https://github.com/ParadiseSS13/Paradise/blob/7f31e4f7a364ad484c2c00b38a3a319326d6624f/code/modules/reagents/chemistry/reagents/drugs.dm#L319
https://github.com/ParadiseSS13/Paradise/blob/7f31e4f7a364ad484c2c00b38a3a319326d6624f/code/modules/reagents/chemistry/reagents/drugs.dm#L650
So, they should not stack together.

Nukka cola uses GOTTAGOFAST, which probably does(?) stack with the others. Not sure if it should, though.

**Comment by Fox-McCloud** [comment]
Working as intended.
