### ISSUE TITLE
Mindslave status not removed properly

### ISSUE THREAD

**Issue by TheSardele** [ParadiseSS13/Paradise#12393]
**Issue Description**:
A mindslave was gibbed, their brain was put in a humanised monkey, they didn't lose their objective or antag status.

**What did you expect to happen**: 
For the mindslave to lose those things.

**What happened instead**:
They didn't.

**Why is this bad/What are the consequences**:
Mindslaves can have no mindslave implant, making it impossible to prove they are a mindslave, and impossible to de-mindslave them.

**Steps to reproduce the problem**:
Mindslave someone, transfer their brain. In the instance I saw it, the mindslave was gibbed by a drake, transfered into an MMI, and taken back out and placed in a humanised monkey. Never lost the mindslave status as far as I could tell.

**Comment by Markolie** [comment]
Did this take place during the datumized traitor testmerge?

**Comment by JKnutson101** [comment]
I'm fairly certain that if a mindslave is cloned, they're still a mindslave until the implant is removed from their former corpse.

Pretty sure this is related, though I haven't tested it or anything.

**Comment by SteelSlayer** [comment]
Yeah I think what JKnutson101 said is correct, the only way to de-mindslave someone is to remove the implant from the body. But I'm also curious to know if it was during the traitor datum test merge round.

**Comment by TheSardele** [comment]
Pretty sure it wasn't, I posted this immediately after the round it happened in, can't see any testmerges on the discord new round alert around that time.

**Comment by TheSardele** [comment]
Also, I have just seen the Missionary Starter Kit used. Their "Protect X and follow their orders" objective was never removed, even when the timer elapsed, they still showed up as mindslaves at round end. The text telling them that their mindslaving wore off still shows up at least.

**Comment by Aurorablade** [comment]
Still an issue as of 5/21/20210
