### ISSUE TITLE
Possessed Sword takes damage from ash storms

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12395]
**Issue Description**:

The possessed sword takes damage from ash storms and from what I am guessing then other damage sources.

**What did you expect to happen**: 

For the sword to not get damaged and die from an ash storm.

**What happened instead**:

The sword died and the ghost inside the sword was ejected.

**Why is this bad/What are the consequences**:

This makes the weapon as lavaland loot a bit useless as such since a single ash storm will kill your sword.  Especially if you yourself are immune to ash storms from certain armors but your sword on your person will still take damage.

**Steps to reproduce the problem**:

Get an possessed sword and have a ghost in control of it, have out in a ash storm, the ghost inside the door will die in the storm and get ejected from the sword.

**When did the problem start happening**:

Probably has been in for a while but really only noticed now with lavaland

**Extra information**:

From what I hear its people saying the sword works off of PAI mob code.

**Comment by Spacemanspark** [comment]
I think the only thing the ghost sword and pAI share in common is the same role slot, actual code is different
