### ISSUE TITLE
Monkey with non-monkey items equipped cannot have non-monkey items removed

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#1239]
![image](https://cloud.githubusercontent.com/assets/11774300/7913032/5dd71f80-0864-11e5-8171-56140b7bf4ef.png)
As in the image. I was monkeyed by a ling after he killed me, then cloned and dnad back into a human. I couldn't take my gear off my original body, as my monkified body don't actually have the slots for the items.

This is pretty minor and very situation-specific but is a bug all the same.

**Comment by ZomgPonies** [comment]
Hmm monkeyfying should drop all your gear, period. The solution might be to stop ling from being able to monkeyfy dead people?

**Comment by theColdflame** [comment]
Yeah, that might be a good fix and make more sense (altering the genetic code of a dead body so that it somehow grows into a different form?)

**Comment by ZomgPonies** [comment]
Fixed.
