### ISSUE TITLE
Database / MySQL: Aborted connection every round

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#12406]
**Issue Description**:
At the end of every round, game server fails to properly close the connection to the database before restart, resulting in this error in both windows event log and mysql error log:
[Warning] Aborted connection XXXXX to db: 'XXXXX' user: 'XXXXX' host: 'XXXXX' (Got an error reading communication packets)

**What did you expect to happen**: 
Code should close connection to database before shutting down.

**What happened instead**:
It doesn't, resulting in database logging an error at the end of the round as the game process dies without closing its db connection properly beforehand.

**Why is this bad/What are the consequences**:
It fills up the error logs over time with pointless errors.

**Steps to reproduce the problem**:
1) Run the game with mysql active
2) End the round.
3) Check the database / mysql error log

**Comment by AffectedArc07** [comment]
Side note on this, if you add a `sleep(0)` to the end of `world/Reboot()`, it will wait for all running procs to finish executing, including DB writes and closure. Don't ask why it works, it just does.
