### ISSUE TITLE
Borg proto-kinetic accelerator fires at an ungodly speed.

### ISSUE THREAD

**Issue by Drobe50** [ParadiseSS13/Paradise#12407]
**Issue Description**:
 The default mining borg KA fires at an ungodly speed.

**What did you expect to happen**: 
The KA to be normal like every other one.

**What happened instead**:
You fire at the speed or faster than a fully upgraded KA with cooldown modules.

**Why is this bad/What are the consequences**:
You can fire the same speed no matter the pressure, your power is drained absurdly fast as well. Can be used to cheese mobs such as Terrors. 

**Steps to reproduce the problem**:
Be borg, choose mining module, fire KA.

**When did the problem start happening**:
Probably sometime during the lavaland updates, I don't know.

**Extra information**:
Not sure if it's intended or not. But i'm leaning towards unintended.

**Comment by MrMagolor** [comment]
I would say that this cheeses blobs moreso than terrors, but yeah. Still an issue.
