### ISSUE TITLE
Instruments won't play in tandem

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#12440]
**Issue Description**:

Instruments won't play together properly

**What did you expect to happen**: 

Just today I wanted to see if I can play a duet of the same song with someone and the music wouldn't play properly and instead sounded garbled due to the notes not playing or even for that matter have the sounds overlap which is what is supposed to help.

**What happened instead**:

sounded garbled and didn't play most of the notes.

**Why is this bad/What are the consequences**:

It isn't really important compared to all the bugs but this is really more for RP purposes and quality of life. You can't have a band play music together because the instruments refuse to play properly together.

**Steps to reproduce the problem**:

just have two people try to play music at the same time, I don't think song matters.

**When did the problem start happening**:

Probably been a thing for a long time but heavily ignored since no one does bands or duets for that matter and it's just one player walking around the station playing music.

**Comment by Mitchs98** [comment]
Not true for the most part. Some songs do sound garbled. Overall its a timing thing and instrument pairing thing combined with whatever song you're playing. No one touched instrument code in recent months as far as I'm aware. However Squishy and I played duet really often and it sounded just fine usually.

**Comment by Ty-Omaha** [comment]
It's BYOND #10262
