### ISSUE TITLE
The proc cmd_admin_pm needs a Refactor

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#12454]
**Issue Description**:
The proc `cmd_admin_pm` is all over the place

**What did you expect to happen**: 
For legible code, allowing the ability to easily modify it.

**What happened instead**:
It's too confusing

**Why is this bad/What are the consequences**:
Because it hinders progress

**Extra information**:
https://github.com/ParadiseSS13/Paradise/blob/d2e2c91eca9261091984cd372e849fed7710c1b7/code/modules/admin/verbs/adminpm.dm#L61

**Comment by AffectedArc07** [comment]
Requesting a refactor is not a valid issue.
