### ISSUE TITLE
Mindslave status not assigned properly

### ISSUE THREAD

**Issue by TheSardele** [ParadiseSS13/Paradise#12489]
**Issue Description**:
When people get mindslaved, they don't get the objective to follow their master in their notes, and they don't show the red (A) in the logs to make it easy to tell they are an antag at a glance.
They do show up as mindslave in the check antag window and in the traitor panel.

**What did you expect to happen**: 
For them to show up as antag in the attack logs and for them to have an objective to help their master in their notes.

**Why is this bad/What are the consequences**:
Admins can't tell at a glance if a mindslave is one, and who their master is.

**Steps to reproduce the problem**:
Mindslave someone.
Have the mindslave attack someone, they probably don't show up as antag in the attack logs.
Their notes probably don't show the mindslave objective either.

**When did the problem start happening**:
Uncertain, but not long ago, #12378  would be my guess.

**Extra information**:
I originally observed these issues during an event round where people were made traitors via admin powers and figured that may be the cause of the issue, but I've now also seen it happen during normal traitor rounds.

**Comment by SteelSlayer** [comment]
I know what's causing this, and I will fix it.
