### ISSUE TITLE
Main repo comes with compilation errors by default

### ISSUE THREAD

**Issue by DanielProcopio** [ParadiseSS13/Paradise#12497]
**Issue Description**:

When compiling paradise.dme it comes with 3 errors by default? 

https://prnt.sc/pepi8g

I've updated byond and redownloaded it but continue to have the same issue. 

**What did you expect to happen**: 

Expected 0 errors and for the dme to compile

**What happened instead**:

3 errors and dmb is not created

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

Pull latest release, extract, open dme and compile, get 3 errors shown here: https://prnt.sc/pepi8g

**When did the problem start happening**:

10/3/19

**Extra information**:

**Comment by Shadow-Quill** [comment]
Couldn't reproduce on latest master.

**Comment by Aurorablade** [comment]
if this were true the server would not be running at all right now. Are you running the latest version of byond? if not that may be your issue.

**Comment by DanielProcopio** [comment]
Did fresh install and it's compiling properly now, thnx for timely response.
