### ISSUE TITLE
Corner case spawns absurd amount of swarmers/terrors

### ISSUE THREAD

**Issue by SpessX** [ParadiseSS13/Paradise#12502]
**Issue Description**:
Some unknown case/trigger causes a reproduction event (swarmer creates a shell or terror spiderling grows up) to create many copies of that spawn.

**What did you expect to happen**: 
To not have my face eaten by 8342834 red spiders while 298342834 swarmers tear my beautiful station apart. Only one critter should have spawned on that reproduction instance.

**What happened instead**:
Single reproduction created many shells/spiders on that one spot.

**Why is this bad/What are the consequences**:
Station resources can't sustain that kind of hyperbolic population growth and we only have one station, think of the children.
Also causes people to think admins are messing with the round with manual spawns. This is confirmed to not be the case.

**Steps to reproduce the problem**:
Unknown. On one case, a terror queen had taken refuge inside the terror gateway, then came back and red eggs were laid in the gateway access. On the most recent case, an early swarmer made a shell inside engineering. In both cases about 20 copies of each popped up for grabs. Reproduction events before and after went as normal but a specific one went wrong.

**When did the problem start happening**:
Assuming both cases are related -- terrors glitch was about a month or so ago, swarmer glitch was today.

**Comment by Aurorablade** [comment]
So from the logs we were seeing it at diffrent places at diffrent times and not all in the same spot. For swarmers. Swarmers I n.v the hand of someone who knows what they are doing can snowball quick. It's not a bug. Unless you are physically seeing 5+ swarmers off one shell.  And terrors spawn multiple spiderlings per clutch by defualt

**Comment by Fox-McCloud** [comment]
This sounds like hyperbole, to be honest, and is a case of "not having all the information and making assumptions". 

If this is more proveable, in the future, this can be opened, but this just sounds like hyperbole for now.
