### ISSUE TITLE
AI Camera View Teleports When On Activated Cult Teleport Rune

### ISSUE THREAD

**Issue by AdvnetureDrake** [ParadiseSS13/Paradise#12507]
**Issue Description**:
When the AI camera view is on top of a cult teleport rune when it is activated, the AI's camera view will be teleported to the selected destination, even if it is out of camera view or off station.

**What did you expect to happen**: 
The AI's camera should not be teleported when it is on top of a cult teleport rune when it is activated.

**What happened instead**:
My camera view was teleported to the cultist's chosen destination.

**Why is this bad/What are the consequences**:
This could potentially reveal a cultist's base, or at least show where the other end of the teleport rune is.

**Steps to reproduce the problem**:
Create a cult teleport rune with an end destination off station. Have the AI position their camera view directly over the station side rune. Activate the teleport rune. The AI's camera view will be sent to the other rune.

**When did the problem start happening**:
Discovered this issue today.

**Extra information**:

**Comment by Citinited** [comment]
Cult magic is so strong that it can even transport AI consciousness

I bet this also affects normal console eyes

**Comment by AdvnetureDrake** [comment]
Imagine my surprise when I had my camera on someone, and then suddenly my view was teleported to the listening outpost which was full of cult stuff.
