### ISSUE TITLE
As the xenomorph queen you are able to stack resin walls on top of each other on the same tile

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#12517]
**Issue Description**:
You can stack a lot resin walls on the same tile.

**What did you expect to happen**: 

To not be able to build more than one wall on the same tile

**What happened instead**:

You can stack multiple resin walls on the same tile.

**Why is this bad/What are the consequences**:

This doesn't look like intended behaviour.

**Steps to reproduce the problem**:

1. Become a xenomorph queen
2. Build as many resin walls as you want on the same tile.

**When did the problem start happening**:

Unsure. Probably for a long time. First observed today (2019-07-10)

**Extra information**:

![image](https://user-images.githubusercontent.com/37041561/66317558-6722bb00-e922-11e9-88c8-8f72d9d12bd4.png)

**Comment by Ty-Omaha** [comment]
same thing happens with foamed metal grenades
