### ISSUE TITLE
Can open lockboxes using facid

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12528]
**Issue Description**:
As the title says. Lockboxes are easily opened by facid

**What did you expect to happen**: 
Science not to have 10 AEG's in their bluespace backpack

**What happened instead**:
Every scientist and his RD now have guns and are even more armed than cargonia in an identity crisis

**Why is this bad/What are the consequences**:
Don't have to explain this I hope

**Steps to reproduce the problem**:
1. Get lockbox
2. Throw facid over it. Or use grenade

**When did the problem start happening**:
Since the universal damage PR

**Comment by Spacemanspark** [comment]
Oh God, the floodgates have been opened once again
