### ISSUE TITLE
CQC grab combo won't check if you have a grab

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12524]
**Issue Description**:
Grabbing somebody with CQC, failing said grab. Then grabbing somebody else will instantly stun them

**What did you expect to happen**: 
To need to use the combo as it's intended

**What happened instead**:
You can prime a stun.

**Why is this bad/What are the consequences**:
Not how it's designed

**Steps to reproduce the problem**:
0. Get CQC
1. Fails a grab on somebody
2. Grab some else. STUN

**Extra information**:
Combos at a whole just work wonky. Especially if you combine them

**Comment by Fox-McCloud** [comment]
Martial arts are buggy in general; you can do similar things with plasma fist.
