### ISSUE TITLE
Vox incompatible Spacesuits

### ISSUE THREAD

**Issue by Carthusia** [ParadiseSS13/Paradise#12527]
**Issue Description**:

Most unique spacesuits are unwearable by the vox

**What did you expect to happen**: 
I expected to be able to wear the clown EVA suit as a vox

After the space immunity update vox now require spacesuits, but their options for what they can wear are significantly lower than all other races.

Spacesuits i've found that vox cannot wear:

All off color variants: Black/red, green, blue, etc

Cult hardsuit: This was especially annoying to find out, as our cult was pumping these things out like a factory, and i suddenly realized I wasn't able to take the added armor/space proofness from it.

Clown spacesuit

Mime spacesuit

All cosmonaut spacesuits: Captain, security etc

Many more that i probably do not know about.

Spacesuits i've found that Vox can wear:

Normal EVA

Syndicate Blood red hardsuit: Learned this by freak chance.

Captains spacesuit

Engineering Hardsuit

Medical Spacesuit

Paramedic Spacesuit

**What happened instead**:
It would not let me wear any of the listed suits above.

I expected to be able to wear the suits.

**Why is this bad/What are the consequences**:
While spacesuits are available in EVA, the more unique ones players can find an enjoy, cannot be enjoyed by the Vox and in situations where a suit is required and the only one you can find is a unique suit, your kind of hosed.

See Above

**Steps to reproduce the problem**:

Be a vox, attempt to wear any of the listed spacesuits. There are potentially far more suits than im aware exist, and there is a very good chance they are not wearable by the vox as before the recent update, they had no need to be able to wear the suits.

**When did the problem start happening**:

This has probably been the case for a very long time, it's only the more recent race changes that has made it much more obvious and created a negative effect on vox players.

**Extra information**:

**Comment by JKnutson101** [comment]
I wonder if the missing suits even have sprites for Vox wearing them. If not this issue might also need a spriter to solve.

**Comment by Carthusia** [comment]
My guess is they wouldn't have sprites, as for years they never really needed them.

**Comment by Fox-McCloud** [comment]
This is a feature request, so it's going to be closed.

I have zero problems with Vox being able to wear a lot of space suit subtypes, but they lack sprites for most of them, which is why this wasn't changed in the PR;  they can wear *most* hardsuits though.

If someone wants to make Vox sprites for space suits, be my guest; I'd be happy to accept them in a PR.

But this is still a feature request.
