### ISSUE TITLE
Tile bug 

### ISSUE THREAD

**Issue by KromeAngel** [ParadiseSS13/Paradise#12525]
**Issue Description**:
Weird bug where plating doesnt get covered when you place a floor tile on it. Anything thats under it dissapears (Power cables, smugglers satchels, piping...) but the floor tile looks like plating no matter what. 

**What did you expect to happen**: 
I expect a floor tile to appear where the plating was. 

**What happened instead**:
Removed the "floor tile" which resembled plating, put it back and nothing changed. Tried with another floor tile, still the same.

**Why is this bad/What are the consequences**:
Its a bug I suppose.

**Steps to reproduce the problem**:
I've never seen it happen on its own but I know theres a gateway map (Xenomorph nest gateway) that has that same bug on a few tiles infront of the teleporter building. 

**When did the problem start happening**:
/

**Extra information**:
/

![Tilebug](https://user-images.githubusercontent.com/56308151/66402485-36f02080-e9e5-11e9-9b06-91271fcc5343.png)

**Comment by DGamerL** [comment]
Most likely has been fixed by the previous PR, and if it was still a bug it probably would've been noticed more. Thank you for making this report!
