### ISSUE TITLE
Cannot hack APC's anymore

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12537]
**Issue Description**:

You cannot hack APC's anymore with wirecutters or multitools.

**What did you expect to happen**: 

To expose the wires and be able to hack an APC.

**What happened instead**:

You just hit the APC with your multitool or wirecutters.

**Why is this bad/What are the consequences**:

You cannot hack or work with APC's anymore.

**Steps to reproduce the problem**:

Go to APC, expose the wires, try to use a multitool on it.

**When did the problem start happening**:

Only noticed this start this past sunday.

**Extra information**:

**Comment by Couls** [comment]
Likely related to #12245

**Comment by KasparoVy** [comment]
I noticed for certain things I'd have to change my intent to harm. I'll edit my comment when I can remember exactly what I had to do that for... 🤣

**Comment by Crazylemon64** [comment]
OK, specific symptoms: You can expose the wires, but clicking on the APC afterwards still brings up the normal interface.
