### ISSUE TITLE
Borers inside a hosts head get hurt by ash storms

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12533]
**Issue Description**:

Borers inside a hosts head get affected by an ash storm, and killed from it

**What did you expect to happen**: 

Expected my host to take damage from the storm, and for me to be safe unless I crawled out.

**What happened instead**:

Died inside my host silently, without even my host noticing

**Why is this bad/What are the consequences**:

If someone is in a pod, they are safe from a storm, following the same rules, a borer in someones skull should to.

**Steps to reproduce the problem**:

Infest a miner. 
Watch as they are in an ash storm for more then 6 seconds.
Die

**When did the problem start happening**:

Probably since lavaland was added.

**Extra information**:

**Comment by Kyep** [comment]
Does https://github.com/ParadiseSS13/Paradise/pull/14067 fix this?
If not, maybe request that that PR also fixes this.
