### ISSUE TITLE
Reconnecting as NPC

### ISSUE THREAD

**Issue by Sligneris** [ParadiseSS13/Paradise#1253]
Whenever someone goes SSD as NPC (Ian, Slime, etc.),, when they reconnect, the game chat still treats them as unconscious - everything is still replaced as "You can almost hear someone talking...".

**Comment by KasparoVy** [comment]
This one's been around for some time I think. First noticed it weeks ago but thought it was just  a one time thing

No idea why this happens

**Comment by Plotron** [comment]
I read somewhere that it's caused by simple mobs not being able to wake up from sleep, so somehow the deafness never gets removed.
