### ISSUE TITLE
The Syndicate Depot doesn't get fully destroyed.

### ISSUE THREAD

**Issue by JKnutson101** [ParadiseSS13/Paradise#12535]
**Issue Description**:
When Code Delta is declared at the Syndicate Depot, it doesn't fully wipe out the area like it used to, and leaves behind a lot of loot and debris that shouldn't have remained.

**What did you expect to happen**: 
For the suspicious asteroid to be almost completely destroyed

**What happened instead**:
A lot of chunks of depot remained, and several bits of unclaimed loot as well.

**Why is this bad/What are the consequences**:
Free loot for 'failing' the depot is bad.

**Steps to reproduce the problem**:
Trigger enough alarms to set the depot to delta. Scavenge free loot post explosion.

**When did the problem start happening**:
Probably related to the changes with Universal Object Damage.

**Comment by Kyep** [comment]
Having just tested this, the main things left behind appear to be:

- airlocks (which break, and drop circuits)
- metal (stacks of it everywhere)
- atmos pipes and vents (which appear displaced, not destroyed)
- stuff inside boxes inside lockers (e.g pills from pill bottles)
- gibs and blood
- broken lights

Most of this stuff is semi-useless debris.
Of the actual loot, it appears to be mostly stuff inside boxes inside lockers.

Really though I should probably just recode the explosion to:
- change all turfs in the area to /turf/space
- qdel everything else

Explosions don't actually destroy stuff reliably - even dropping a bomb directly on top of a box only destroys the box - everything inside the box is unaffected.

If all containers work like this, it means you can protect an object from a reactor meltdown explosion by wrapping it in paper.

**Comment by Couls** [comment]
I thought TG explicitly made a proc to manually delete things in containers when they explode, its called something like contents_explosion, perhaps we can port that?

**Comment by KasparoVy** [comment]
I remember when you could survive massive fucking bombs by stowing yourself in a locker, bodybag etc. back in the day
Did that come back with a vengeance?

**Comment by Fox-McCloud** [comment]
@KasparoVy I mean, you can try: https://github.com/ParadiseSS13/Paradise/blob/5936bb98fea2bc46769df7ee6bdf57a5f3f3db37/code/game/objects/structures/crates_lockers/closets.dm#L402

**Comment by Kyep** [comment]
"contents_explosion" doesn't exist in our codebase.
I'm not sure trying to port that whole system from TG is a good idea.
Its certainly way beyond the scope of just fixing this bug.
