### ISSUE TITLE
Engi borg gripper cannot install power cell into APC

### ISSUE THREAD

**Issue by VEN0M5** [ParadiseSS13/Paradise#12541]
**Issue Description**:
When an engi borg tries to install a power cell into a APC, the power cell will magically disappear from the gripper. Picking up and dropping power cells is fine.

**What did you expect to happen**: 
To be able to install power cell and finish the APC

**What happened instead**:
Power cell stolen by redspace

**Why is this bad/What are the consequences**:
Engiborg is unable to do one of their jobs.

**Steps to reproduce the problem**:
1. Build up an APC until you wire it.
2. Grab power cell with gripper.
3. Use gripper on APC.
4. Summon Power-sie with the 10 bluespace power cell sacrificed.

**When did the problem start happening**:
Should be still working a week ago

**Extra information**:
A mining jetpack I tried to put into the destructive analyser is disappeared too. Installing a shield satellite board into a computer frame works fine.

**Comment by SpessX** [comment]
This happens to drones too.
