### ISSUE TITLE
Wrenching cargo telepads damages the telepad

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12550]
**Issue Description**:

Using a wrench on a cargo telepad causes you to hit and damage the telepad while wrenching it up/down.

**What did you expect to happen**: 

To wrench and unwrench the object without bashing it.

**What happened instead**:

Now you bash it and wrench it at the same time.

**Why is this bad/What are the consequences**:

Unintentionally damaged a machinery on help intent when trying to move it.

**Steps to reproduce the problem**:

Get cargo telepad, use a wrench on it an any intent.

**When did the problem start happening**:

With the recent changes with universal damage.

**Extra information**:

In light of this going to start testing other machinery and objects to see what else may be acting funnily given this and APC's both got messed up in that PR.

**Comment by Citinited** [comment]
This is probably fixed by #11700, once I do tool behaviours for wrenches
