### ISSUE TITLE
Toolbelt is gone from the biogenerator

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12553]
**Issue Description**:
As the title says

![image](https://user-images.githubusercontent.com/15887760/66592424-48782a80-eb95-11e9-9109-5a094ff245e2.png)

**Comment by moxian** [comment]
Seems to be intentional change introduced in #12514

Though I'm slightly surprised that job specific belts are not made from leather now

**Comment by Fox-McCloud** [comment]
Reading changelogs is important.
