### ISSUE TITLE
RPED doesnt show the parts of a machine anymore

### ISSUE THREAD

**Issue by reschreiter1311** [ParadiseSS13/Paradise#12554]
**Problem Description**:
the rped doesnt show the parts of a machine anymore

**What did you expect to happen**: 
To see which parts a machine has

**What happened instead**:
i didnt know which parts the machine has

**Why is this bad/What are the consequences:**
You dont know which parts are at which tier

**Steps to reproduce the problem**:
grab an rped and click a machine

**When did the problem start happening**:
it started happening about a week ago

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
nothing really

**Comment by Kyep** [comment]
Yeah, I've seen this too. It is annoying.
