### ISSUE TITLE
You can use body scanners and print scans from inside the body scanner

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#12565]
**Issue Description**:
You can use the body scanner without the help of others now

**What did you expect to happen**: 
To need a doctor to check on me

**What happened instead**:
I could check on myself

**Why is this bad/What are the consequences**:
Seems like an unintended balance change, but I don't care either way

**Steps to reproduce the problem**:
Get in body scanner, click body scanner

**When did the problem start happening**:
#12377 

**Extra information**:
The CL for 12377 says that body scanners are similar to sleepers, but sleepers can't be used to inject yourself with chems from inside

**Comment by moxian** [comment]
> The CL for 12377 says that body scanners are similar to sleepers, but sleepers can't be used to inject yourself with chems from inside

You currently can inject yourself with chems while you are inside the sleeper so the CL is technically correct.

**Comment by Couls** [comment]
No you can't I just tested it, clicking the buttons to inject does nothing

**Comment by moxian** [comment]
But I just did that myself in live game two rounds ago...
