### ISSUE TITLE
Ratvarian spear doesn't do extra burn damage

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#12570]
**Issue Description**:

The ratvarian spear doesn't do 5 extra burn damage like it says it does

**What did you expect to happen**: 
for it to do the extra burn damage it should

**What happened instead**:
It doesn't do extra burn damage

**Why is this bad/What are the consequences**:
It makes the loot less valuable

**Steps to reproduce the problem**:
attack with spear, check target that's been hit. notice there is no burn damage

**When did the problem start happening**:
Probably since lavaland was ported?

**Extra information**:
the comment in the code says
``	force = 15 //Extra damage is dealt to targets in attack()``
but there is no code for the spears attack proc here

**Comment by Fox-McCloud** [comment]
Going to close this---Clockcult is the only reason this exists and it was removed on TG---and we're not likely to ever get it, either.

It just being normal, as on TG, is fine.
