### ISSUE TITLE
Canisters not filling tanks or opening

### ISSUE THREAD

**Issue by Alaysian** [ParadiseSS13/Paradise#12574]
**Issue Description**:
I could not fill an air tank on an 02 canister, even when the pressure was set to 1013 and the valve was open.  Upon discovering this, i closed the valve, removed the tank, and turned down the pressure to minimum.  I then open the valve and slowly raised the release pressure.  It never vented into the room.

**What did you expect to happen**: 
When the pressure is set to 1013, it should equalize between it and a tank if it has one, or the room if it doesn't.

**What happened instead**:
Nothing.

**Why is this bad/What are the consequences**:
Unable to use toxins.  Unable to refill used/empty air tanks.

**Steps to reproduce the problem**:
Insert a tank into a canister and set the pressure to 1013, and click open.

**When did the problem start happening**:
10/13/19 at 1 am.

**Extra information**:
I tested it on O2 canisters and then N20 when that didn't work.

**Comment by Citinited** [comment]
Possibly related to #12575

**Comment by Fox-McCloud** [comment]
it was determined the entire air controller halted because of the other PR---for...unknown reasons.
