### ISSUE TITLE
You can't punch xenomorphs

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#12579]
**Issue Description**:
You can't punch xenomorphs

**What did you expect to happen**: 
To be able to punch xenomorphs

**What happened instead**:
The attack animation played but no damage or sound was present

**Steps to reproduce the problem**:
Punch a full xenomorph not a simple mob one

**Comment by matttheficus** [comment]
#12578 is closed, will need to double check if this is clear.

**Comment by Henri215** [comment]
Tested, this is still an issue

**Comment by DGamerL** [comment]
Attacking a xenomorph has about a 10% chance to actually work, instead stunning the xeno. Fully intended
