### ISSUE TITLE
Eating a second slaugheter demon heart does not give you blood eat

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12589]
**Issue Description**:

According to the code, eating a second slaughter demon heart is supposed to allow you to eat people like a slaughter demon, upon consuming a demon heart with blood crawl already.
However, eating a heart displays the message "An unnatural hunger consumes you. You raise the demon heart to your mouth and devour it!", but does not display or have the effects of giving you the blood eat ability, or the you don't feel any different method.

**What did you expect to happen**: 

Killing a second demon allowing you to gain all of its power, as a wizard, cult survivor, or grey tide with a wand of death.

**What happened instead**:

You eat the second heart, gain no bonus unintended, and the other heart is gone forever.

**Why is this bad/What are the consequences**:

Hearts go to waste, and we don't get to see the awesome power of a wizard with blood eat, hulk, and time stop wrecking the crew

**Steps to reproduce the problem**:

Spawn and kill a demon, or just spawn the heart.
Eat the heart.
Gain blood crawl.
Kill and eat another heart.
Notice no faliure message is displayed, and you can not eat people through the blood.

**When did the problem start happening**:

Probably forever.

**Extra information**:

**Comment by Ziiro** [comment]
https://github.com/ParadiseSS13/Paradise/blob/d2e2c91eca9261091984cd372e849fed7710c1b7/code/game/gamemodes/miniantags/slaughter/slaughter.dm#L259-L261 On a lark I took a look at the code, and I understand what it's trying to do, but what a weird ass way to do it.
