### ISSUE TITLE
Certain mountable frames aren't getting applied to walls with the proper orientation and location

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#12598]
**Issue Description**:

Currently the fire alarm frame, intercom frame, and fire extinguisher cabinet frame are broken in terms of placing them on walls. Trying to place any one of these doesn't work properly no matter which side of a wall you apply it to.

Video of the problem:
https://streamable.com/oqmpd

I *think* the problem code lies somewhere in one of these files here:
https://github.com/ParadiseSS13/Paradise/tree/master/code/game/objects/items/mountable_frames

And specifically this proc, which is also present on the other frames.
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/mountable_frames/fire_alarm.dm#L8-L10

However, what I don't understand is that all of this code hasn't been touched in months or years, save for the APC code touched in universal object damage. But that's irrelevant, because placing APC is working properly right now.

I've already tried fiddling around with it to no avail, hoping someone else has any ideas as to what the problem could be.

**Steps to reproduce the problem**:

Take either a fire alarm frame, intercom frame, and fire extinguisher cabinet frame and attempt to place it like I've shown in the video.

**When did the problem start happening**:

Can't have been more than a week or so ago.

**Comment by Citinited** [comment]
This has been going on for a while (at least with intercom frames, which are broken right now)
