### ISSUE TITLE
Swarmer in Lobby

### ISSUE THREAD

**Issue by lalchimi** [ParadiseSS13/Paradise#12593]
**Issue Description**:
Swarmer communication can be heard from the lobby

**What did you expect to happen**: 
Not be able to read swarmer communication from the lobby screen

**What happened instead**:
Swarmer communication readable from Lobby screen

**Why is this bad/What are the consequences**:
People could use it for metagaming before playing their character i mid-round.
It also kind of pollute lobby i guess ?

**Steps to reproduce the problem**:
Stay on lobby

**When did the problem start happening**:
15 october. First time seeing this

**Comment by moxian** [comment]
Cannot reproduce locally.
I don't see a way to trigger the bug from the code, but I also don't see any changes that would have fixed it..
