### ISSUE TITLE
List SSDs and AFKs panel doesn't display special roles correctly

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#12599]
**Issue Description**:

The panel sometimes shows every single person on it as Obj Target. I double checked if they actually were targets, but they weren't. 
 
**What did you expect to happen**: 

I expected it to show up correctly.

**What happened instead**:

Every single person was a Obj Target (including comms agents) even when they actually weren't one.

**Why is this bad/What are the consequences**:

The panel gives false information.

**Steps to reproduce the problem**:

Unsure.

**When did the problem start happening**:

I first noticed it when List SSDs and AFKs panels were merged together (At least around that time). Observed the same 
issue today again.

**Extra information**:

None of the people on the panel were targets.
![SSD panel censored](https://user-images.githubusercontent.com/37041561/66944111-3b57b180-f055-11e9-9bc2-0b06a147061c.PNG)

**Comment by SteelSlayer** [comment]
What were the antags of this round? And just so I understand, a person's role should be "Obj Target" when said person is a target of assasination right?

**Comment by dovydas12345** [comment]
It was changelings and yes Obj Target means they are part of the assasination objective.
