### ISSUE TITLE
Karma Problem While in Pods

### ISSUE THREAD

**Issue by Arvenius169** [ParadiseSS13/Paradise#12609]
Norwest told me to report this for him, so I am. I noticed that while in a pod, you are able to gift yourself karma. That's the extent of my ability to really report this bug.

**Comment by Citinited** [comment]
pod code is utter trash

😄

**Comment by KasparoVy** [comment]
What the actual fuck

**Comment by Spacemanspark** [comment]
Wait hold up what

**Comment by taukausanake** [comment]
Are there logs to show someone giving themselves karma? I'd imagine there are karma logs

**Comment by Arvenius169** [comment]
I actually didn't select to give myself karma, so perhaps it wouldn't really have worked, but I hit "Award Karma to Player" and my character was the only name that came up.

**Comment by Citinited** [comment]
What happened when you selected yourself?
