### ISSUE TITLE
Zombies can hurt each other

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#12613]
**Issue Description**:

Zombies can slap each other with zombie claws.

**What did you expect to happen**: 

Since zombies arent allowed to hurt other zombies, its silly you are able to do so codewise

**What happened instead**:

They can in fact slap each other silly

**Why is this bad/What are the consequences**:

zombies are friends dont hurt fellow zombies

**Steps to reproduce the problem**:

1. slap other zombie

**When did the problem start happening**:

zombie PR

**Comment by Couls** [comment]
zombies can attack each other on TG as well and this was ported from TG, this is more a feature request than an issue but it would be easy to code in, just check for the zombie race in the claw attack proc

**Comment by Fox-McCloud** [comment]
This isn't a bug; this is a feature request.
