### ISSUE TITLE
Alien nest drops metal when destroyed

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#12617]
**Issue Description**:

You can get metal from alien nests

**What did you expect to happen**: 

to get nothing

**What happened instead**:

I got metal

**Why is this bad/What are the consequences**:

It's weird and breaks the immersion

**Steps to reproduce the problem**:

1. have alien make a nest
2. destroy the nest by any means

**When did the problem start happening**:

Probably universal object damage

**Comment by Cazdon** [comment]
Turns out, you can also deconstruct them with a wrench 😄
