### ISSUE TITLE
Universal damage issue - Racks

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12623]
**Issue Description**:

Racks can no longer be dissembled using wrenches.

**What did you expect to happen**: 

To be able to dissemble a rack using a wrench.

**What happened instead**:

You have to bash it apart.

**Why is this bad/What are the consequences**:

Not a huge issue, just game inconsistency.

**Steps to reproduce the problem**:

Get a rack, try to take it apart with a wrench.

**When did the problem start happening**:

When universal damage was ported in.

**Extra information**:

**Comment by SteelSlayer** [comment]
I thought this was a bug at first, but turns out you need to use harm intent

**Comment by Denthamos** [comment]
So...help intent for tables or machines, yet harm intent for racks.  That's....a bit inconsistent.

**Comment by Citinited** [comment]
Ficksed in #11700

IMO it shouldn't care about your intent
