### ISSUE TITLE
600u Sorium Causes effected players to be unable to move

### ISSUE THREAD

**Issue by Alaysian** [ParadiseSS13/Paradise#12629]
**Issue Description**:
As per the title, I made a 600u sorium mine.  When it went off in the hallway, effected players within 2-4 tiles were unable to move.  That was seemingly the only effect noticed.

**What did you expect to happen**: 
Everything around the mine to fly far away

**What happened instead**:
The closest players became unable to move.

**Why is this bad/What are the consequences**:
It leaves players unable to defend themselves or take meaningful part in the round unless they relog.

**Steps to reproduce the problem**:
Make a proximity mine casing.  Fill one bluespace beaker with 150u Mercury, 150u Oxygen. Fill another with 150u Nitrogen, 150u Carbon.  Load both beakers into the casing and secure the casing.  Active the mine near people.

**When did the problem start happening**:
1pm 10/22/2019 is when the event happened.

**Extra information**:
Relogging allows effected players to move again.

**Comment by MrMagolor** [comment]
maybe it's some sort of variable overflow?
