### ISSUE TITLE
Necropolis stone tile overlay bug

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12622]
**Issue Description**:

The overlay graphic/icon for the stone tiles and cracked stone tiles from the ash walker nest and necropolis area cannot be admin deleted, removed, or destroyed in any fashion or form.  Once they are down in a round they cannot be removed.  Same applies for the necropolis stone gates as well for the ash walker nest and legion area.

**What did you expect to happen**: 

For admins to be able to edit areas for events and more by placing down and removing tiles/effects.

**What happened instead**:

The stone tiles when placed cannot be removed at all.

**Why is this bad/What are the consequences**:

Prevents admins from cleaning up areas or editing areas for events.

**Steps to reproduce the problem**:

Go to lavaland, go to the ash walker nest or legion area.  Try to remove/delete the tiles there.

**When did the problem start happening**:

Existed since lavaland was merged in.

**Extra information**:

**Comment by FunnyMan3595** [comment]
Not sure when, but this did get fixed at some point.
