### ISSUE TITLE
Cherry bombs don't put you in throw intent when primed

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#12633]
**Issue Description**:

Cherry bombs don't go throw intent when primed

**What did you expect to happen**: 

To be able to click and throw the bomb after priming

**Why is this bad/What are the consequences**:

You can blow yourself up because you didn't press r fast enough
This is not consistent with the other grenades

**Steps to reproduce the problem**:

get cherry bomb
prime it
click
blow yourself up

**Comment by Ty-Omaha** [comment]
well cherries are meant to be eaten so idk why you would throw it
