### ISSUE TITLE
You can Flacid Nukie hardsuit helmets 

### ISSUE THREAD

**Issue by Matt1311** [ParadiseSS13/Paradise#12648]
**Issue Description**:
You can melt away nukie hardsuit helmets and make their hardsuit completely unusable

**What did you expect to happen**: 
i expected nukies to keep their hardsuit helmet and not to get it melted away

**What happened instead**:
the nukie hardsuit helmet just melted away and the hardsuit was completely broken it couldnt extend its helmet anymore and thus making it not spaceproof anymore

**Why is this bad/What are the consequences**:
nukies arent spaceproof anymore if you use this

**Steps to reproduce the problem**:
get a flacid spray, spray a nukie when the spray is on the 10u option,PROFIT

**When did the problem start happening**:
im guessing this is because of universal object dmg

**Extra information**:
heres a video of it in action https://www.youtube.com/watch?v=f6pCQdbPt3U&feature=youtu.be

**Comment by DGamerL** [comment]
With MODsuits the unusability has been fixed, making them able to be extended again! Thank you for making this report!

**Comment by DGamerL** [comment]
I forgor we don't have all modsuits yet

**Comment by BiancaWilkson** [comment]
We have all modsuits now!
