### ISSUE TITLE
Hijack bugged

### ISSUE THREAD

**Issue by Magentaformula0** [ParadiseSS13/Paradise#12641]
**Issue Description**: Hijack seems to be bugged with its parameters. 

So it doesn't seem to correctly make checks on the shuttle and whether it was hijacked or not. I had seen one round where only one person on the shuttle wasnt a syndicate and they were ziptied (note: they were standing in case that needs to be apart of it). That incident was 2 days ago. And just yesterday I had hijacked the shuttle and i made sure that no one else was on the shuttle and every ghost agreed I was the only one present. I will say though both times I am reffering to the hijacker had a holo parasite. Im wondering if the holo parasite is bugged so that he isnt counted as syndicate and instead is counted as crew. 

**What did you expect to happen**: 

Greentext.

**What happened instead**:

red text

**Why is this bad/What are the consequences**:

Because it makes it so that your objective was uncompletable. and it makes people think that you didnt hijack. 

**Steps to reproduce the problem**:

try hijacking the shuttle with a holo parasite present and out and see if it counts as a proper hijack. 

**When did the problem start happening**:

I dont know. Maybe this is a bug thats existed for a long time. maybe its only been since the last merge. 

**Extra information**:

**Comment by garrulousTeamotei** [comment]
The same problem potentially occurred with me. The apparent only ones on the shuttle were me and another syndicate agent. I do not know if the other agent had a holoparasite. Both of us received redtext.
