### ISSUE TITLE
Chat styling gets broken when any text highlightning is specified (in non-regex mode)

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#12653]
**Issue Description**:
Chat styling is gone if you set up highlighting.
Screenshot of chat: https://cdn.discordapp.com/attachments/236096824463720448/637883043285303298/c1cd26d17ac9810302d7cdfe811f2343.png
Screenshot of settings: https://i.gyazo.com/thumb/1200/059b184f3f3f65adb928f1bc1bce8054-png.jpg

**What did you expect to happen**: 
Highlighting to work, or at least the rest of the styling to not fall off.

**What happened instead**:
Chat was black on white

**Why is this bad/What are the consequences**:
Harder to read the chat when styling is gone. Also feels less pretty

**Steps to reproduce the problem**:
Set up highligting, enter "dayana" into the field, do not tick the regex box. When chat gets new lines they would be black on white.

**When did the problem start happening**:
After #12474 got merged

**Extra information**:
Ticking regex makes styling come back.
However as I've mentioned in https://github.com/ParadiseSS13/Paradise/pull/12474#pullrequestreview-297822432 that would break other stuffs if used as a workaround.

Regex also does not work for the use case of putting multiple names in one field, when the user wants to highlight any of them (see the second screenshot)

**Comment by Ty-Omaha** [comment]
Havent looked at the code but looks like it could be an unclosed span class

**Comment by craftxbox** [comment]
I'll get to figuring this out, I have no clue why it does this NOW when it didn't in testing.
as for 2: that's what the whole point of the multiple entry fields at for
~~i did ask of could be tm'd instead of full merge~~
