### ISSUE TITLE
head crabs can jump through closed windows/windoors

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12662]
**Issue Description**:
A headcrab jumped through a closed windoor or window. Unsure which

**What did you expect to happen**: 
Them not to be magical

**What happened instead**:
They jumped in and got stuck after they did their magic trick

**Why is this bad/What are the consequences**:
It's a bug

**Steps to reproduce the problem**:
Have one chase you near engineering. Have them jump at you near the spot in the picture

![image](https://user-images.githubusercontent.com/15887760/67679000-5ea12b80-f988-11e9-8c80-9e8bc4fa4ea1.png)

**Comment by SabreML** [comment]
#16405
