### ISSUE TITLE
Blueshield's newscaster begins in an inaccessible location without moving room objects

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#1266]
![image](https://cloud.githubusercontent.com/assets/11774300/8021669/9616a448-0ca0-11e5-9415-3298cf0a857e.png)

As title. 

Sidenote: it's also on the opposite side of the room to everything else. Perhaps a better location would be next to the chair/desk where there's empty wall space.

**Comment by Allfd** [comment]
The NT reps office has the same newscaster issue.
