### ISSUE TITLE
Syndicate Depot Delta still leaves treasure behind.

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12677]
**Issue Description**:
Some loot still remains after the depot explodes, and the explosion leaves a lot of debris.

**What did you expect to happen**: 
The depot to be completely gone.

**What happened instead**:
A lot of the depot remained with some very strong loot inside as well.
![depot_explosion_live](https://user-images.githubusercontent.com/47765135/67913333-168a3080-fb63-11e9-97ae-28cbed338ba1.png)

**Why is this bad/What are the consequences**:
Free loot bad.

**Steps to reproduce the problem**:
Trigger Delta alert on Syndie Depot. Check remains.

**When did the problem start happening**:
Well #12245 most likely again.

**Extra information**:
#12535 is basically the same issue, which was supposed to be fixed by  #12539. No idea what the issue could be caused from.

Picture was taken on live server.

**Comment by Kyep** [comment]
Bedsheets, coin and toolbox are okay to survive, I think.
The pinpointer and rifle, though, I will be modifying the code to prevent them from being left behind by explosions.
