### ISSUE TITLE
Highlight strings broken

### ISSUE THREAD

**Issue by xProlithium** [ParadiseSS13/Paradise#12676]
**Issue Description**: After looking through past PRs, I see a couple were pushed pertaining to highlight strings. Seems nobody tested it because _**THEY DON'T WORK ANYMORE**_.

**What did you expect to happen**: The Highlight strings to either work better, or work period.

**What happened instead**: They don't work _at all_.

**Why is this bad/What are the consequences**: As a player, highlight strings can be useful, as an admin, they're invaluable.

**Steps to reproduce the problem**:N/A

**When did the problem start happening**: #https://github.com/ParadiseSS13/Paradise/pull/12474

**Comment by craftxbox** [comment]
i- what? they do work, unless another or manages to fuck them, I've literally tested it a million times what the fuck

**Comment by craftxbox** [comment]
Cannot reproduce, at all. please provide more steps to your issue, such as the terms you are using and wether the 'regex enabled' box is checked.

**Comment by xProlithium** [comment]
After talking 1 on 1 with craftbox, it requires certain syntax to work.
`(?![^<]*>)(str1|str2|str3|str4|str5)` - Per each line.
Apologies for the late close.

Thanks again craft for the help.
