### ISSUE TITLE
Be able to choose your job as an antag

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#1267]
@ZomgPonies @Fox-McCloud @TheDZD 
Details are here so no one can actually see and abuse this until it gets fixed:
http://nanotrasen.se/phpBB3/viewtopic.php?f=24&t=4907&view=unread#unread

**Comment by Fox-McCloud** [comment]
This is a result of a system that Tiger implemented.

@tigercat2000

**Comment by tigercat2000** [comment]
Yes I know, working it out now.
