### ISSUE TITLE
Ion Cloud Event Hardly Visible

### ISSUE THREAD

**Issue by VeteranKyl** [ParadiseSS13/Paradise#12689]
**Issue Description**:
The Harmless Ion Cloud event is giving off such dim light that it's not visible under normal circumstances.

**What did you expect to happen**: 
The Ion Cloud event used to give off light that was bright enough to be visible in even brightly lit rooms.

**What happened instead**:
The light given off by the event is so dim that it's nearly impossible to see if you're not in a pitch black room

**Why is this bad/What are the consequences**:
The lighting issue defeats the purpose of the event, which is to create a minor light event to serve as a break from the normally chaotic nature of the station. Not having this work properly essentially makes the event pointless.

**Steps to reproduce the problem**:
Trigger the Harmless Ion Cloud event while near a window in a well lit area. You won't be able to see any color change.

**When did the problem start happening**:
I believe this started with the lighting rework a few months back.

**Extra information**:
This is likely all related to the way lighting is now handled by the code.

**Comment by moxian** [comment]
See also: #12162

**Comment by moxian** [comment]
Event was removed in #14575
