### ISSUE TITLE
tube pod and station tube station don´t drop dead bodies

### ISSUE THREAD

**Issue by CebollaMan** [ParadiseSS13/Paradise#12686]
Objects or Mechanics Involved: Dead Bodies and transit tube.
Brief Description (include as much detail as possible): A Dead Bodie was found in the IA Satelite, and when loaded into the tube pod, it can´t be ejected
What did you expect to happen?: To find any command in Object tab to eject whatever was inside the pod, or the pod automatically ejecting its cargo at the end of the line.

**Comment by Citinited** [comment]
These things are in desperate need of a rework TBH

**Comment by DGamerL** [comment]
Fixed by #22452 !
