### ISSUE TITLE
Oddyseus Syringe Gun Syringes Usually Don't Work Properly

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#12685]
**Issue Description**:

The syringes fired from an Oddyseus' exosuit syringe gun usually do not work, resulting in a vertical syringe laying on the ground still filled with reagents.

**What did you expect to happen**: 

Syringes fired from an oddyseus should have the same effect as the ones from any other syringe gun.

**What happened instead**:

That for whatever reason the projectiles don't inject and use a weird icon.

**Why is this bad/What are the consequences**:

It really makes a lot of interesting things that could be possible with the Oddyseus much less feasible.

**Steps to reproduce the problem**:

Step 1. Get oddyseus
Step 2. Get some reagents analyzed, and syringes loaded
Step 3. Process reagents, and fire a syringe at something
Step 4. Notice how the syringe is vertical and filled with reagents still, and the person you hit with it has none of the reagents from it in them.

**When did the problem start happening**:

I'm not sure - whenever I've tried using an oddy, this has happened.

**Extra information**:

Sometimes the syringes work properly - they leave an empty normal syringe on the ground. The broken syringes still have a small line indicating that they have chems in them.

**Comment by moxian** [comment]
Related/duplicate: #7132 (yours is more descriptive though)

**Comment by Imotepchief** [comment]
This happens if the clothing the person is wearing has stopped the syringe injecting its contents.
The only way to use the syringe again is to reload it back into the ody and fire it again.
