### ISSUE TITLE
Space Pod Laser is spawning wrong

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#1269]
When you fire the Spacepod laser, it spawns 2 tiles away, making it impossible to hit anything directly infront of you. I don't know if it works with the taser system, however.

**Comment by Spacemanspark** [comment]
I think this was done intentionally to prevent pod pilots from hitting themselves with their own lasers if moving and firing.
@TheDZD

**Comment by Fox-McCloud** [comment]
@Spacemanspark  is correct; pods are STUPIDLY fast right now, and until that's corrected, this is one of the few ways of safely handling it.

**Comment by TheDZD** [comment]
@Spacemanspark Yep, that's correct, when I was fixing pod projectile firing, making them spawn 2 tiles ahead of the pod was the only way to prevent them hitting the pod if it was travelling while firing.

**Comment by TheDZD** [comment]
Whoops, wrong button. This is still technically a problem.

**Comment by Earthdivine** [comment]
This is a very stupid way of handling it, in my honest opinion. There's nothing that moves faster then a pod so there's literally no reason to be firing while going that fast, not to mention I can SHOOT THROUGH WALLS with this. I could have killed a blob through it's blob walls if I felt like it earlier today.

**Comment by monkeysfist101** [comment]
Why not put a check in there to see if the pod is stationary? I was ganked by spiders the other day because I couldn't hit them inside of my own pod bay.
