### ISSUE TITLE
All snipers let you zoom while not holding them

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12693]
**Issue Description**:

All sniper rifles with the zoom function currently let you zoom and see further while not holding them, letting you use other weapons that are functionally better at a distance of which you should not see normally.

**What did you expect to happen**: 

You should have to hold the sniper and have it in your active hand to zoom in.

**What happened instead**:

You can zoom in with it in your inactive hand or on your armor slot and use other guns while zoomed.

**Why is this bad/What are the consequences**:

It lets you use guns like the cr20 or other high impact/stunning based weapons on other players in which you can see but they cannot see you beyond blind firing.

**Steps to reproduce the problem**:

Get a AWP or syndie sniper, place it on your armor exosuit slot, press the zoom button.  Profit.

**When did the problem start happening**:

Unknown, just noticed it today while I was testing some functions with them.

**Extra information**:

**Comment by SteelSlayer** [comment]
I didn't see this issue when I made #13753, but that PR fixes this bug.

**Comment by matttheficus** [comment]
Fixed by #13753
