### ISSUE TITLE
Rod of Asclepius / Pacifists can use Hierophant Club to harm others.

### ISSUE THREAD

**Issue by Abydos2** [ParadiseSS13/Paradise#12699]
**Issue Description**:

People who gain the pacifist trait from the Rod of Asclepius are able to use and damage others with the Hierophant Club.

**What did you expect to happen**: 

I expected to not beable to hit other people with the Hierophant Club.

**What happened instead**:

Whenever I go to hit someone with the Hierophant Club, it gives you the pacifists message 
"You don't want to harm other living beings!"
But then does the Hierophant's AoE ability, with friendly fire on, causes you to damage other people.

**Why is this bad/What are the consequences**:

I believe it's bad for the sake of it not being pacifist. Any miner could get the Hierophant club first, then use the Rod to give themselves endless healing while still being able to damage anyone and anything within their way.

**Steps to reproduce the problem**:

1) Get Rod of Asclepius and use it, go through the whole oath.

2) Get the Hierophant Club

3) Toggle Friendly Fire on it

4) Either at melee or range, use it on a person

5) Watch as you damage people despite having Pacifist.

6) Use it against others such as nukies, blob and such with no fear of damage (Due to your healing), your ranged attacks and being behind cover where you are an endless source of healing to your team-mates and endless damage from range.

**When did the problem start happening**:

Whenever Rod got introduced with the trait rework

**Extra information**:

![unknown](https://user-images.githubusercontent.com/15679133/68241364-6c992100-0006-11ea-87c3-ba53d8f4af16.png)
![unknown (1)](https://user-images.githubusercontent.com/15679133/68241673-fcd76600-0006-11ea-9e79-9754e435f15b.png)

**Comment by silverplatedelta** [comment]
Fixed as stated above.
