### ISSUE TITLE
Genetics bug where some powers randomly activate then are unable to be reactivated when injecting same block that Deactivates them...

### ISSUE THREAD

**Issue by SpookyBooggie** [ParadiseSS13/Paradise#12715]
So as the title states, Genetics on paradise seems to be slightly bugged sometimes. Here is an example. Today I had HULK activate when I injected block 52 it also activated yelling at the same time. I then did a clean SE later and tried to reactivate it. This time nothing happened when I injected block 52 at DAC. So I thought maybe when I injected the empty block 52 it changed one of my other personal SE blocks randomly. So I scanned myself and no other blocks had activated.... weird right? so I moved on but kept 52 above DAC. later when injecting a random block it reactivated along with another random power. (two with one block injection) so I then printed a clean block 52 and used that to get rid of hulk proving that it was, in fact, block 52. Then AGAIN I tried to inject 52 above DAC and nothing happened... I have no idea what causes this

**Comment by farie82** [comment]
This is due to how genetics works Im afraid.
Blocks will get set by the injection but. Wont always activate upon injection. However if you try another block every other set block will try to activate once more.

**Comment by SpookyBooggie** [comment]
Ah okay, that helps clear things up a bunch, thank you!
