### ISSUE TITLE
DNA samplers can get samples from IPCs

### ISSUE THREAD

**Issue by insertnamehere123** [ParadiseSS13/Paradise#12737]
**Issue Description**:

Using a DNA sampler on an IPC gives you a humanoid datapoint

**What did you expect to happen**: 

I expected a humourous error message or something to allude to the character not having DNA to sample

**What happened instead**:

IPCs are machine people and thus don't have DNA, so I exepcted the attempt to fail, instead it worked the same way it would on an organic character

**Why is this bad/What are the consequences**:

It isn't, it's funny, but it might be a bug.

**Steps to reproduce the problem**:

Just get a DNA sampler from the DNA vault station goal and take a sample from an IPC

**When did the problem start happening**:

Not sure

**Extra information**:

It might be working as intended, but it's hard to tell.

**Comment by JKnutson101** [comment]
Yeah old DNA vault used to give powers to IPCs as well. New DNA vault cannot, *and it makes me cri*

**Comment by Spacemanspark** [comment]
It's more so an oversight. When it was ported from /tg/, IPCs weren't taken into consideration

**Comment by insertnamehere123** [comment]
Should I try to fix this? If so, how do I test it?

**Comment by Mitchs98** [comment]
This has been fixed and can be closed.
