### ISSUE TITLE
Syndicate Deport will not register visiting agents

### ISSUE THREAD

**Issue by Drakeven** [ParadiseSS13/Paradise#12739]
**Issue Description**:

When an Agent ID is used to try and log into the Syndicate Deport, it will not register it, and rather treat it like a regular crew ID despite it having access to doors and turrets. 

**What did you expect to happen**: 

Being able to sign into the Syndicate Deport, making mobs non-hostile. 

**What happened instead**:

I was not able to sign in at all.

**Why is this bad/What are the consequences**:

This makes the ability to sign in as a syndicate agent useless other than the ability to send a one time message to the Syndicate. 

**Steps to reproduce the problem**:

Use an Agent ID, get into the Deport, and try to sign in. 

**When did the problem start happening**:

It first happened to me at 17/11/2019 (Australian Dating) 

**Extra information**:

Here are pictures of two different examples of it happening to me, including my objectives, my agent ID, and the red text forbidding me from signing in (Slightly obscured in one of the pictures) 
https://gyazo.com/1df219807ebeafdb317e3629c8839d14
 https://gyazo.com/59bb24d0ae9522fb0518168b61c700c3

**Comment by JKnutson101** [comment]
Did some digging. In /code/game/machinery/computer/depot.dm at line 323, the code checks for  user.mind.special_role == SPECIAL_ROLE_TRAITOR and ever since #12378 traitors are no longer handled in the mind, but in datums, so depot code needs to be updated to check antag datums instead. @Kyep

**Comment by JKnutson101** [comment]
If what I said above is correct this might also prevent things like hijack from taking place. I'll test these two out when I get the chance. I've yet to find a special_role ==ROLE_TRAITOR check but I've found a few special_role == SPECIAL_ROLE_TRAITOR
