### ISSUE TITLE
Maintenance Drone's Magnetic Gripper deletes power cell items.

### ISSUE THREAD

**Issue by darth-tyrael** [ParadiseSS13/Paradise#12730]
**Issue Description**:

Whenever a maintenance drone picks up a power cell item it gets removed from the gripper.

**What did you expect to happen**: 

Maintenance drones should be able to build, fix and maintain APCs, and as such, I expected the magnetic gripper to hold power cells.

**What happened instead**:

When I proceeded to try to place the power cell inside the APC, I slapped it with the APC. Drop gripped item resulted in no items being dropped, and I could pick something else up.

**Why is this bad/What are the consequences**:

Maintenance drones should be able to build, fix and maintain APCs.

**Steps to reproduce the problem**:

- Pick up high capacity power cell + from engineering storage with gripper.
- Get a power control module from engineering's vending machine and drag it.
- Head to abandoned construction area west of engineering.
- Attempt to build the APC there from the frame on the floor.
- Attempt to place the power cell.
- Fail miserably.
- Get another cell from vending machine, pick it up.
- Head to construction and try to place it.
- Cry.

**When did the problem start happening**:

Noticed today (14th November 2019)

**Extra information**:

Drones = bae

**Comment by SteelSlayer** [comment]
This is a known bug and we have a few other duplicate reports. I am fixing this in #12592

**Comment by darth-tyrael** [comment]
Aight thanks for the clarification. Posted on admin's recommendation.
