### ISSUE TITLE
Syndicate chainsaw stun bypasses shielded hardsuit.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12736]
**Issue Description**:

Syndicate chainsaw stun bypasses shielded hard suit

**What did you expect to happen**: 

For the shield to block the damage and the stun

**What happened instead**:

Damage is blocked, stun passes through

**Why is this bad/What are the consequences**:

It doesn't make sense at all

**Steps to reproduce the problem**:

Get a chainsaw
Use it on a shielded hard suit user
Watch as they are stunned

**When did the problem start happening**:

Today

**Extra information**:

**Comment by JKnutson101** [comment]
Shielded Hardsuits have a lot of weird things go through them. Surprise surprise, wizard fireballs completely ignore them, though that might be intentional cause explosions in general seem to go right through.

**Comment by chuga-git** [comment]
The shielded component and energy shield modsuit module have fixed these inconsistencies.
