### ISSUE TITLE
Potted Plants Can Be Used To Conceal Your Character Without Double-Wielding

### ISSUE THREAD

**Issue by Reyblood** [ParadiseSS13/Paradise#12732]
**Issue Description**:

You can conceal your character sprite by wrapping a potted plant with package wrappers, and opening the package with an empty hand.

**What did you expect to happen**: 

To not be 100% sprite-wise hidden while also be able to use the other hand.

**What happened instead**:

Got 100% sprite-wise hidden while also being able to use anything in the other hand.

**Why is this bad/What are the consequences**:

Syndicate Agents using pickpocket gloves can steal anything with their sprite not showing they're holding something in their second hand, able to use other hand with sprite hidden.

**Steps to reproduce the problem**:

1. Find a suitable potted plant
2. Wrap it with Package Wrapper
3. Have two hands empty, pick the wrapped potted plant in one hand
4. Activate the potted plant in active hand
5. Watch the potted plant go to the OTHER (empty) hand while your previously occupied hand is free to use, and your sprite, hidden.
**When did the problem start happening**:

Probably forever.

**Extra information**:

Not have been fiddling enough with that bug, but having your sprite hidden, being able to move at full speed while also having your other hand free gives a lot of good buggy ideas.

**Comment by JKnutson101** [comment]
Whoa, that's pretty wacky. Now Diona's can layer up.

**Comment by Citinited** [comment]
This has already been reported,two handed items be wack yo
