### ISSUE TITLE
Admin characters are showing up on the manifest.

### ISSUE THREAD

**Issue by Shockpoint** [ParadiseSS13/Paradise#12746]
**Issue Description**:

When joining the round via the Join Game button, and clicking an admin-only role, my character's name was put on the Crew Manifest.

**What did you expect to happen**: 

I shouldn't show up on the manifest.

**What happened instead**:

I did.

**Why is this bad/What are the consequences**:

The crew shouldn't know the characters are around. Players could use this to assume there are Syndicate if they see a Syndicate Officer on the manifest.

**Steps to reproduce the problem**:

Start in the lobby.
Click "Join Game".
Choose NTNO/SOO/SO.
Check the Crew Manifest.

**When did the problem start happening**:

I honestly forget. I mainly forgot to report this.

**Extra information**:

**Comment by JKnutson101** [comment]
I think I found the issue, and I'll PR a fix for it once I'm off work tonight.
