### ISSUE TITLE
Toggling 64x64 in Icons Tab Does Not Scale UI

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#1274]
Much like the title aptly states-- As soon as the dynamic hud pull request went live, I tried testing it by setting icons to 64x64-- which produces 15 tile view-distance-- however the UI did not scale.
IDK if this is a bug or nah-- but I felt it'd be better to post this and learn it be the latter than let it slide.

If it's not actually a bug, how do you downgrade your own view distance? Change-View-Range 15 doesn't do jack

**Comment by ZomgPonies** [comment]
Dynamic HUD doesn't give you the ability to change your own view distance. Only certain items (sniper rifles, certain mech abilities, etc) can do that.

**Comment by KasparoVy** [comment]
Thanks for the response
