### ISSUE TITLE
Legion Cores do not heal IPCs

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12759]
IPCs used to be able to be healed by legion cores,  now they are not. The change was unlisted.

**What did you expect to happen**: 
Either have cores heal IPCs or the change properly discussed as a balance decision before being implemented, and then perhaps disallowing IPCs to consume cores for zero benefit.

**What happened instead**:
Applied legion core, consumed, got message, nothing happened.

**Why is this bad/What are the consequences**:
Well pretty nasty nerf to IPC Miner that was unlisted.

**Steps to reproduce the problem**:
Apply Legion Core to damaged IPC.

**When did the problem start happening**:
#12587 here I would have to guess, as it was the last change involving Legion cores.

**Comment by craftxbox** [comment]
working as intended:tm:

**Comment by Kyep** [comment]
I don't think legion cores should heal IPCs. 
Reasons:
- I'd rather miners get patches from medical, rather than relying on legion cores.
- Legion cores are organic. Why should they heal synths?

**Comment by Cazdon** [comment]
> 
> 
> I don't think legion cores should heal IPCs.
> Reasons:
> 
>     * I'd rather miners get patches from medical, rather than relying on legion cores.
> 
>     * Legion cores are organic. Why should they heal synths?
@Kyep 

I honestly agree with the miners relying on medical as opposed to having legion cores. When we ported lavaland from TG, it was fairly 1 to 1. There isn't anywhere near the level of inter-departmental interaction on TG as there is here, and there Legion Cores for healing makes sense. But Paradise is medium RP so forcing the departments to co-operate would be a great idea.

But to answer why they should heal synths, we already have a precedent of including IPCs in DNA mechanics despite having DNA, like IPCs being able to DNA Lock Mechs for instance. We've already ditched "they are synthetic" line of thinking in favor of balanced mechanics, otherwise it wouldn't make sense that maintenance drones and PAIs can go into space unharmed and IPCs cannot. You could even ask why do IPCs become Legions when they are killed by them. Why can Terror Spiders extract 'juice' from the for lack of a better word? There's a lot of things like this.

My biggest gripe is that it's an unlisted change, stealth nerfing IPCs which many people see as the weakest race. IPC's strength of easy to fix virtually never comes into play in lavaland, where perma-kills are common, and mobs hit hard enough to de limb IPCs in one strike (Even the tiny legion skulls will remove your foot or hand in one attack) which can easily immediately end your round, and if they don't it still requires the intervention of another player to get yourself fixed.

But again, I'd prefer to also ditch legion cores in favor of having miners actually interact with more than R&D 20 minutes into the round. They're a bit too self-sufficient and can even buy entire brute med-kits for just a few mining points.

**Comment by DGamerL** [comment]
Not a bug, as of today the design team decided that IPCs should not be able to use legion cores

One has noted that they would like this if it was not for augmented miners being able to benefit from a brute damage modifier and also being able to heal a lot.
