### ISSUE TITLE
Secure Storage is easily destroyed in meteor rounds.

### ISSUE THREAD

**Issue by fj45** [ParadiseSS13/Paradise#1275]
Twice now I have observed that shortly into meteor rounds, secure storage is completely destroyed making it impossible to setup any kind of shield system. The hardsuits and building supplies are also destroyed.

Secure should probably have three or four R-walls where it is exposed to space so it has some chance of shrugging off meteor hits.

**Comment by veganzombeh** [comment]
Three or four reinforced walls seems like overkill. Maybe we could instead add a maintenance tunnel to the exterior or a bit more protection.

**Comment by fj45** [comment]
A maint tunnel would only offer a single wall, plus one around there really isn't needed. I agree that it isn't the norm, but from watching meteor rounds, even two R-walls don't last long.

**Comment by Plotron** [comment]
Let's add some kind of grilles or other soft absorby-stuff like the one between armory and perma or the AI sat glass ring.

Double reinforced walls look... well, kinda silly. You can tell that it's an 'easy fix'.

I agree that secure storage looks kinda exposed.

**Comment by Robertha89** [comment]
technically there are supposed to be grills protecting all windows to offices, thats it mostly.

**Comment by fj45** [comment]
Yeah double stacking walls isn't great, but very few people will ever see it. I guess a mix of grilles and R-walls would be ok, but from seeing the AI sat, grilles alone wouldn't be enough. Most get destroyed just from blast damage.
