### ISSUE TITLE
Security Camera Duplicate Upgrade Drops Items

### ISSUE THREAD

**Issue by blinkdog** [ParadiseSS13/Paradise#12758]
**Issue Description**:
When duplicating a Security Camera upgrade with an item like an Analyzer, the correct message is displayed, but the Analyzer winds up on the floor.

**What did you expect to happen**: 
When the game sends the message `The camera already has that upgrade!`, I expect the Analyzer that I was trying to put into the camera remains in my hand.

**What happened instead**:
When the game sends the message `The camera already has that upgrade!`, the Analyzer that I was trying to put into the camera winds up on the floor on my tile.

**Why is this bad/What are the consequences**:
It's not game-breaking, but it's kind of annoying that I have to pick up the upgrade item. If it doesn't work, it'd be nice if the item just stayed in my hand so I can take it to another camera.

**Steps to reproduce the problem**:
1. Get a Screwdriver
2. Get two (2) Analyzers
3. Approach any Security Camera mounted on any wall.
4. Apply Screwdriver to Security Camera.
5. Apply Analyzer to Security Camera; see message about adding the Analyzer to the camera.
6. Apply second Analyzer to Security Camera; see message about camera already having that upgrade, and find that the Analyzer is now on the floor.

**When did the problem start happening**:
I'm not sure. This is the first time I've gone around mass-upgrading cameras around the station.

**Extra information**:
Nothing special. I might even comb over the code to see if I can fix this one myself. :smile:

**Comment by Citinited** [comment]
Should be an easy enough fix by rewriting the logic around this line https://github.com/ParadiseSS13/Paradise/blob/5936bb98fea2bc46769df7ee6bdf57a5f3f3db37/code/game/machinery/camera/camera.dm#L151

**Comment by KalevTait** [comment]
Ability to use analyzer to upgrade security camera was removed 18 months ago by [this PR](https://github.com/ParadiseSS13/Paradise/commit/28573946d77418d4a86a99c5555b85d04d677057).

**Comment by Contrabang** [comment]
^like said above, fixed by removal
