### ISSUE TITLE
Engineering cyborg unable to place power cells in APCs

### ISSUE THREAD

**Issue by Aslan4468** [ParadiseSS13/Paradise#12754]
**Issue Description**:
When you try to place a power cell into an APC using the engineering cyborg's magnetic gripper, the power cell vanishes from existence and the APC remains without a power cell.

**What did you expect to happen**: 
I expected the power cell to be placed in the APC.

**What happened instead**:
The power cell disappeared rather than being placed in the APC.

**Why is this bad/What are the consequences**:
Engineering cyborgs should be able to place power cells into APCs

**Steps to reproduce the problem**:
1. Become an engineering cyborg
2. Go to an APC or Obtain a power cell for an APC without one.
3. Open the APC and remove the power cell using your magnetic gripper (If it has a power cell)
4. Attempt to place the power cell into the APC
5. The power cell should now have disappeared, with nothing dropping from your magnetic gripper if you select the drop items option.

**When did the problem start happening**:
When I played an engineering cyborg around a week or two ago.

**Extra information**:
No additional information.

**Comment by SteelSlayer** [comment]
Duplicate of #12541
And got a fix coming in #12592

**Comment by Aslan4468** [comment]
Ah. Didn't see that post. My mistake.
