### ISSUE TITLE
Engineering cyborg cant put cells in APC

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#12769]
**Issue Description**:

If you try to put a powercell in an APC using your gripper, the cell just straight up dissapear.

**What did you expect to happen**: 

Put in cell, happy power.

**What happened instead**:

Cell poofed, sad no power.

**Why is this bad/What are the consequences**:

Items shouldnt dissapear, fucks over engiborgs

**Steps to reproduce the problem**:

1. unlock APC and crowbar open the cover
2. remove the cell with your gripper
3. drop the cell to the ground
4. pick up another cell, put that cell in
5. new cell dissapears

**When did the problem start happening**:

No clue

**Extra information**:

Happened today on live 02/12/2019

**Comment by TheSardele** [comment]
#12627 
#12541 
#12592

**Comment by datlo** [comment]
Big oof
