### ISSUE TITLE
Sleeping as a pet is broken

### ISSUE THREAD

**Issue by steve8233** [ParadiseSS13/Paradise#12762]
**Problem Description**:
I clicked sleep in the IC menu while playing as Renault and the sleeping box popped up and I couldnt hear anything but I could still see and move like I was awake. 

**What did you expect to happen**: 
I expected to not be able to see or move like anything else sleeping

**What happened instead**:
I could not hear like I was asleep but I could hear and move like I was awake

**Why is this bad/What are the consequences:**
Its nothing major but just a small bug. It prevents pets from sleeping which only might cause RP issues.

**Steps to reproduce the problem**:
Play as Renault (unknown about other pets) and then try to sleep

**When did the problem start happening**:
Unknown
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It was a normal game.

**Comment by Henri215** [comment]
Tested it last month and it did work just fine.

**Comment by warriorstar-orion** [comment]
no point in keeping a minor 4 year old bug about simplemobs around if it hasn't been reproduced recently. if someone sees it again they can reopen the bug or file a new one.
