### ISSUE TITLE
On station rolls are getting flagged as off station roles.

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12764]
Crewmembers are randomly having their Offstation_Role flag set to TRUE, when they've been crew from roundstart.

**What did you expect to happen**: 
To never have the Offstation_Role flag set to TRUE unless they are truly offstation.

**What happened instead**:
Some Civillian had their Offstation_Role set to TRUE. Some Borg had his Offstation role set to TRUE. I can't re-create this but these were confirmed by @Drakeven and @TDSSS that this happened on live.

**Why is this bad/What are the consequences**:
As of #12577 Off Station roles could no longer be converted, and with #12571 non-convertibles would get sacrificed, meaning perfectly convertible people were wound up sacrificed, to the fault of neither PR mind you.

**Steps to reproduce the problem**:
Not sure. We can rule out this. The civilian in question had Scientist roll set to high, but didn't get their job, and had 'become civilian instead' enabled. Recreating this scenario showed no issues, and nothing else was out of the ordinary about the civilian. 

**When did the problem start happening**:
No idea, this might have been a bug for the games whole lifespan, but only became a problem with the two above mentioned PRs.

**Extra information**:
Big thanks to @TDSSS , @Drakeven , and @TheSardele for answering my questions and helping me find this issue.

**Comment by datlo** [comment]
Offstation role is a fairly recent variable I added myself. I have no idea what could cause it to get flipped on outside of actually spawning in as a spawner or other special role.

**Comment by Kyep** [comment]
Needs to be investigated/fixed, so the off-station role check can be re-added.
