### ISSUE TITLE
Holodeck Sunglasses Are Funky

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#12776]
**Issue Description**:
You can make the sunglasses from the beach holodeck into real HUDglasses which remain when worn and brought outside of the holodeck

**What did you expect to happen**: 
For the glasses to not be usable in crafting HUDglasses or for them to vanish when leaving the holodeck.

**What happened instead**:
The glasses became real and were able to be worn outside the holodeck

**Why is this bad/What are the consequences**:
Infinite duplication of eye protection is bad

**Steps to reproduce the problem**:
Set the holodeck to the beach sim
Gather the supplies to make one of the 3 HUDglasses
Craft the HUDglasses
Leave the holodeck with your brand new pair of sunglasses

**When did the problem start happening**:
Probably when the ability to craft HUDglasses was merged

**Extra information**:
N/A

**Comment by Citinited** [comment]
Related to #12329
