### ISSUE TITLE
Cloning Bug

### ISSUE THREAD

**Issue by snurfe** [ParadiseSS13/Paradise#12770]
**Issue Description**: Cloning copys genetic from race selected via character creator

Golems receiving genetics from character creator

**What did you expect to happen**: To only receive current body abilities.

**What happened instead**: Got abilities that I wasnt supposed to gain.

**Why is this bad/What are the consequences**: You are cloned with genetics you arent supposed to get.

Its not that important, in my opinion, it just breaks immersion.

**Steps to reproduce the problem**:
Pre-scan as a golem.
Die.
Get cloned.

I found this while being a golem, basically I only had vocal cords as a ability, but I had grey as character in creator. What happened is, that when I was cloned, it basically gave me grey's abilitys.
It happened when I pre-cloned myself, and died to drake, then I was cloned with grey abilities, which is my main character race.

**When did the problem start happening**: Not sure.

**Extra information**:
![proof](https://user-images.githubusercontent.com/37090200/69980078-459f1380-150e-11ea-83e9-9b954703ae47.png)

**Comment by farie82** [comment]
When cloned in a fully upgraded cloner you have a chance to get beneficial gene mutations

**Comment by snurfe** [comment]
I see, this means its not a bug, sorry.
