### ISSUE TITLE
Firing guns point blank at another player while standing on the same tile as said player also damages you.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1277]
What the title says. Not a huge issue, but could do with some looking into.

**Comment by KasparoVy** [comment]
This has been around for aaages. Saw the exact same thing in some ss13 videos from 09 and 2013

Does this include bullet-firing weapons and laser/energy-related weapons, or just one of the two groups?

**Comment by Spacemanspark** [comment]
In my case when I found this out, it was a laser weapon.
Dunno about bullet weapons.

**Comment by veganzombeh** [comment]
Tested both laser and bullet weapons, they actually seem to be damaging *only* the firer, not other people on the turf.

**Comment by Spacemanspark** [comment]
A shame we had to remove point blank damage doing extra damage.
