### ISSUE TITLE
Borg & Drones have modules whose tools are lost when fully used

### ISSUE THREAD

**Issue by KheaHyena** [ParadiseSS13/Paradise#12784]
**Issue Description**:
Whenever a Borg or Drone fully use their stack of equipment, they disappear entirely from their module until recharged at a station.

**What did you expect to happen**: 
That the stack didn't disappear and remained in the module, at 0 stacks, unable to be used but still able to interact and restock from equal products on the floor as per usual. With the addition that the Engineering Module should be able to restock to 50 Cable Coil, instead of only 30 (can only restock to 50 at a Recharger), but that's just a small QoL improvement. As far the Mediborg Cyborg Hypospray goes, it should actually be restocked on it's own with Battery Power, albeit slightly slower than when in a Recharger.

**What happened instead**:
You lose your stack entirely and the ability to use and restock until recharged. This is incredibly annoying when you're an Engineering Module that could restock from leftover materials after a bombing. And in fact, you still can IF you don't completely use your stack.

**Why is this bad/What are the consequences**:
It is a big nuisance that forces you to backtrack to a Recharger even if you are able to either manufacture more on the spot (Tiles) or bring them with you (Cable Coil). If a Feature, it feels useless since you can just not use your stack entirely, but a player shouldn't have to worry about using it's stack until that 1 mark. In a special note, this has resulted before in a permanent loss of a stack, namely some Cyborg Hypospray products from the Mediborg, that refused to return even after a rather lengthy charging. This obviously resulted in a Mediborg with highly reduced efficiency whose Hypospray is already incredibly slow to fill up.

**Steps to reproduce the problem**:
Using materials to it's fullest until they are spent\reach 0. They will disappear and force you to recharge to be able to use or manually restock again. I have not tried to replicate the Cyborg Hypospray issue (I consciously prevent it now), although it is incredibly slow at recharging it's chemicals. I am unsure if this slowness is related but the fully use of materials seems to be.

**When did the problem start happening**:
From my own experience, ever since I played Borg.

**Extra information**:
It could be stated as a Feature, but I consider it a Bug due to being a nuisance, inefficient and irrational. And it's not the first time where I lose certain tools, namely some Cyborg Hypospray products with a Medical Borg (as previously stated), due to using them fully (which is most certainly a Bug). This made the Borg rather underwhelming where it was most needed, since two of the most important and most used products were forever lost. These issues make playing Borg more of an hassle than fun, as nobody wants to keep going to a Recharger solely because of a misstep of using their stack in it's entirety. And as Mediborg it's all about measuring chemicals with unnecessary precision and using them very sparingly (in it's obligatory 5u from a total max of 30u), with products that should really be used freely (with the obvious exception of Epinephrine, unless you are rogue).

**Comment by Citinited** [comment]
I'll see about including a fix for this in #11700 - should be simple enough to do

**Comment by KheaHyena** [comment]
> I'll see about including a fix for this in #11700, as I'm already touching stack code a bit in that PR - should be simple enough to fix (famous last words)

Eheh, thanks!

**Comment by Citinited** [comment]
I had a look but I think fixing this requires some reworking of stack code, which I am unwilling to do. Sorry!

**Comment by Spacemanspark** [comment]
Just for reference, this isn't a bug and should have instead been placed onto the forums in the suggestions catagory.

**Comment by KheaHyena** [comment]
> I had a look but I think fixing this requires some reworking of stack code, which I am unwilling to do. Sorry!

Aaaw dang! Thanks for looking at it though.
I wish I could help, but my skills here are next to dull.

> Just for reference, this isn't a bug and should have instead been placed onto the forums in the suggestions catagory.

I see.
So, is it just a wrong nomenclature I used or is this an intended feature?
Hope not, cause it's an unneeded hassle.
And despite being a slightly different problem, I tested the Cyborg hypospray: it only recharges when the chemical is itself selected. It should just recharge them all in general, the need for this type micromanagement is dreadful.

That said, thank you for replying! 
Do you still recommend I apply this feature\suggestion\request on the forums?
