### ISSUE TITLE
Blobs cannot reflect space pod lasers - again

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12780]
**Issue Description**:

Reflective tendrils for blobs can no longer reflect pod lasers again.  Allows pods to cheese the blob by just sitting out of sight range and being a stationary laser target with no fear of lasers reflecting back.

**What did you expect to happen**: 

For the pods lasers to be reflected back on a reflective tendril.

**What happened instead**:

The lasers from the pod slowed down upon hitting the reflective tendril before proccing their damage on it instead of reflecting.

**Why is this bad/What are the consequences**:

Allows pod cheese against blobs with zero way to fight back.

**Steps to reproduce the problem**:

Get reflective tendrils up, try shooting them with pods lethal lasers.

**When did the problem start happening**:

Around when universal damage was merged from what I hear from talking to other players.  Something might have changed with how the tendrils handle the pods lasers.

**Extra information**:

**Comment by Denthamos** [comment]
Did some testing, as it turns out the reflective tendrils do not reflect any space pod weaponry or temperature guns from the north side.  All other directions reflect properly.

**Comment by farie82** [comment]
Fixed by #12808

**Comment by Denthamos** [comment]
Closing this out due to the merged fix.
