### ISSUE TITLE
Revenant does not revive on death like intended.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12787]
**Issue Description**:

Revenants, if there ectoplasm is not disturbed for a minute after death, are supposed to revive from the dust. However, due to how the dust is spawned, it does not work or happen.

**What did you expect to happen**: 

To rise from the dust of your grave again

**What happened instead**:

The dust just becomes inert

**Why is this bad/What are the consequences**:

Crew should have to remove / clean up the dust to keep it from spawning

**Steps to reproduce the problem**:

Be a revenant
Die from anything
Notice after a minute the dust becomes inert.

**When did the problem start happening**:

Forever, probably

**Extra information**:

The variable reforming is what is checked to revive the ghost. For some reason, it is coded that the dust spawns set to zero... preventing the dropped dust from ever coming back to life, and instead always going inert.

**Comment by Breenland** [comment]
Tested in round recently, confirmed that setting the proper variable results in the revenant coming back to life right away.

**Comment by S-CR** [comment]
IIRC this was intentional when revenants were ported originally because they're already very slippery and difficult to kill without being able to revive. Might talk to the maintainers to confirm what the design intent is here.

**Comment by DGamerL** [comment]
Design and Balance recently agreed on not implementing this feature. Code still has to be cleaned up to remove mentions of this however
