### ISSUE TITLE
Monkey cubes sometimes break with a runtime and spawn humanized monkeys without getting used up.

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#12781]
**Issue Description**:

For some unknown reason something happens with a monkey cube and it breaks forever. When it gets touched by water it expands into a humanized monkey and it doesn't get deleted, just stays on the ground.

**What did you expect to happen**: 

I expected the monkey cube to function normally.

**What happened instead**:

It became a infinite source of humanized monkeys.

**Why is this bad/What are the consequences**:

It runtimes and breaks. That explains why it would be bad for the game.

**Steps to reproduce the problem**:

Not certain what causes it, but it was happening when a medical borg takes a monkey's blood and injects a grey extract with it. The borg pulls away one of the monkey cubes that the extract spawned and uses its pocket extinguisher on it. The monkey cube will either runtime and spawn a humanized monkey and not get deleted, which allows it to get used unlimited amount of times, and stay broken for the rest of the round or it will function normally and create a normal monkey and get deleted.

**When did the problem start happening**:

It started happening today on 2019-07-12 around 1 PM GMT +2

**Extra information**:

The runtime:
![sssssssss](https://user-images.githubusercontent.com/37041561/70373711-5aefb580-18f3-11ea-80d7-756ac8d2ad44.PNG)

**Comment by SteelSlayer** [comment]
Replicated using the steps provided. Runtime occurs when you spray the cube with a fire extinguisher. What an odd bug...
