### ISSUE TITLE
Wooden barricades cannot be deconstructed.

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12790]
Relatively old issue, but not reported. Basically you used to be able to deconstruct wooden barricades with a crowbar, now you cannot, forcing you to smash into it several times to finally break it.

**What did you expect to happen**: 
Use a crowbar on a wooden barricade and have it take a long time to deconstruct.

**What happened instead**:
Just smashed the barricade like with every other tool.

**Why is this bad/What are the consequences**:
There's a lot of wooden barricades on station at the start of the round, removing them via attacking is really obnoxious for players and likely obnoxious for admin attack logs.

**Steps to reproduce the problem**:
Crowbar a wooden barricade. Wack. It pry the planks anymore.

**When did the problem start happening**:
#12093 is when the line of code allowing deconstruction was removed, however it was removed to prevent deconstruction of security barricades. The change also effecting wooden barricades seems unintentional after reading through the PR description.

**Extra information**:
@Fox-McCloud can you tell us if it was intentional? If unintentional, the fix would involve tool changes, which I would like included by @Citinited in the tool refactor #11700 if that's not too inconvenient. Including it alongside the tool refactor or after it seems best.

The lines in question removed in the barricade's attackby proc was...
```
	else if(istype(W, /obj/item/crowbar))
		user.changeNext_move(CLICK_CD_MELEE)
		user.visible_message("<span class='notice'>[user] is prying apart \the [src].</span>", "<span class='notice'>You begin to pry apart \the [src].</span>")
		playsound(src, W.usesound, 200, 1)

		if(do_after(user, 300 * W.toolspeed, target = src) && !QDELETED(src))
			user.visible_message("<span class='notice'>[user] pries apart \the [src].</span>", "<span class='notice'>You pry apart \the [src].</span>")
			dismantle()
```

I'm not entirely sure how the refactor goes, but I would imagine putting something like that under 
`/obj/structure/barricade/wooden/crowbar_act(mob/user, obj/item/I)`
would be where it goes? Sorry to bother you for more work, but I'm not familiar enough with the tool refactor to understand how to make a new deconstruction under it.

**Comment by TheSardele** [comment]
I asked fox this before, it's intended, you're supposed to smash them.

**Comment by TDSSS** [comment]
Yeah I think this was brought up in that PR as intended.

**Comment by Cazdon** [comment]
I see. Well can we reconsider that? Currently if you add more wooden planks to the barricade it becomes a wall, which can then be deconstructed. The deconstruction time was orginally really high, so it's not like the barricades combatants setup could get removed easily.

**Comment by Kyep** [comment]
Yeah, this is annoying.
There are places, like the hidden room next to medical maint, where smashing the barricade to get in will draw attention, in a way that deconstructing it with the proper tool would not.
