### ISSUE TITLE
Golem Shell Construction on Any Autolathe

### ISSUE THREAD

**Issue by Ionward** [ParadiseSS13/Paradise#12797]
**Issue Description**:

Basically, you can upload the Golem Shell Construction to a Component Disk from R&D, right at the start of the round, and load it onto an autolathe, and you can now print Free Golem shells before Mining has even gotten to work.

**What did you expect to happen**: 

I was not expecting to be able to upload a design from the Free Golems autolathe to the station's and be able to make what should normally be a random ghost role.

**What happened instead**:

I was searching for the technological shotshells doing some private testing and found the golem shell in the disk menu.

**Why is this bad/What are the consequences**:

Massive balance issues, anyone with an autolathe and this component disk can just churn out free bodies with enough materials, and with an upgraded autolathe you can make an ABSURD amount of them for very little metal. HUGE issue for conversion antag rounds, as you could imagine.

**Steps to reproduce the problem**:

Take starting component disk, add to R&D console, CTRL+F for golem shell, upload that disk onto an autolathe and voila.

**When did the problem start happening**:

It's probably been a thing since free golems were added, but as no one uses the component disks, it went undiscovered.

**Extra information**:

![f4c5f462c91fdbaf428556adebfc6331](https://user-images.githubusercontent.com/25335231/70690968-c4aded80-1c6c-11ea-893e-7b8eb9d140bd.png)

**Comment by SpessX** [comment]
You don't have to go via R&D, golem disk works directly on any autolathe. Personally I'd let it be, it's worked that way on every server ever.

**Comment by DGamerL** [comment]
Intended. Feel free to make a feature request/discussion on the forums or in the discord!
