### ISSUE TITLE
Security Beret Has Better Melee Resist Than Helmet

### ISSUE THREAD

**Issue by TinnCatt** [ParadiseSS13/Paradise#12807]
Originally brought up by the player Gaty on the discord. 

Issue Description:
Currently our security berets have 5 more points of melee resist than the armored security helmets do, with the downside of marginally less fire resist on the beret (B-20 fire resist/H-50 fire resist). Those who brought this up wonder why this strange oversight or obvious beret bias has to be. 

What did you expect to happen:
For the values to be equal, or well, for the armored helmet's to be more.

What happened instead:
As stated above, the security berets have a better melee resist value than the security helmet. 

Why is this bad/What are the consequences:
Well, it means during normal rounds, it's slightly better for officers to ditch their stylish and iconic helmets in favor of the berets for a combat advantage. 

Steps to reproduce the problem:
None, just check the armor values for both.

When did the problem start happening:
Unsure. Not exactly a coder, so, I assume it's been like this for awhile and has been unnoticed. 

Extra information:
Here's two screenshots of the armor values after examining each with View Variables in-game, and a screenshot Gaty showed me. 

![Sec Helmet](https://user-images.githubusercontent.com/35948390/70857708-d50ad600-1ec1-11ea-9c2e-0335827799cf.PNG)

![Sec beret](https://user-images.githubusercontent.com/35948390/70857715-e94ed300-1ec1-11ea-96f5-43617c63fd5b.PNG)

![Values](https://user-images.githubusercontent.com/35948390/70857730-261aca00-1ec2-11ea-92f7-a281e8aa611d.png)

My suggestion, either make the stats equal, with the beret just being a fancier-looking sec helmet, or decrease the beret's melee resist by 5 so it's not slightly better than the helmet itself. 

Sorry this isn't mega helpful in finding the code for these, my knowledge of coding is extremely limited.

**Comment by Shockpoint** [comment]
I only even took the beret because fashion...

I had no idea the beret was stronger LMAO

**Comment by farie82** [comment]
Helmets have the advantage of blocking your ears when being stripped.

**Comment by Ty-Omaha** [comment]
@TinnCatt When posting code don't post a screenshot of it. Click the line number and then copy the URL at the top.
