### ISSUE TITLE
Toxins bomb sprite glitch.

### ISSUE THREAD

**Issue by SpookSpooky** [ParadiseSS13/Paradise#12802]
**Problem Description**: A of a toxins bomb had doubled a valve and appeared broken.

**What did you expect to happen**: For a different sprite appear to accommodate the new tank

**What happened instead**: A sprite glitched.

**Why is this bad/What are the consequences:** Bombs could still be the same size and be unrecognizable, ruins immersion.

**Steps to reproduce the problem**: Take a "tank transfer valve" add a "emergency plasma tank" and then add a "extended capacity emergency oxygen tank" (the plasma tank is the one that seems to be the cause of this)

**When did the problem start happening**: Unknown, found at time of post.

**Possibly related stuff**: Nothing was related and this seems to work without any interference with gamemodes and such, a detonation device can be put on and can detonate with decent power.
![OddToxinBomb](https://user-images.githubusercontent.com/58868568/70841355-808f2a00-1ddf-11ea-90e9-f563aaf50444.PNG)
![OddToxinBomb2](https://user-images.githubusercontent.com/58868568/70841359-8553de00-1ddf-11ea-8073-4a6b59658a53.PNG)

**Comment by Henri215** [comment]
Tested and the problem really is the missing sprite for the emergency plasma tank.
