### ISSUE TITLE
Canvases are invisible to people who didn't see them get created.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#1282]
What the title says. How can I be a magnificent artist if my lame pixel art is only visible to me?

**Comment by Spacemanspark** [comment]
If it's put into a disposal bin and ejected everyone can see it.

**Comment by TullyBurnalot** [comment]
@Fox-McCloud Tested, no longer happens, can be closed.

**Comment by Fox-McCloud** [comment]
This is absolutely still a problem---anyone who uses canvases is well aware of it.

**Comment by tigercat2000** [comment]
did /tg/ ever fix this
