### ISSUE TITLE
Yann makes the game lag to pieces when he's on screen

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12826]
**Issue Description**:
Having Yann (EN with a beret on) be on the screen lags the game out hard. From a smooth 30 FPS to 5 FPS

**What did you expect to happen**: 
The dog not to use meta warfare

**What happened instead**:
H-E-L-Connection lost

**Why is this bad/What are the consequences**:
Shouldn't happen

**Steps to reproduce the problem**:
Unsure if this happens always but have Yann on screen equiped with this:
![image](https://user-images.githubusercontent.com/15887760/71295478-43e1a680-237c-11ea-9ac4-9b062fe76bee.png)

**When did the problem start happening**:
Unknown

**Extra information**:
It was Yann. I've tested to get all others off screen and only when Yann was on it it would lag to pieces

**Comment by AffectedArc07** [comment]
If this doesnt get the `WTF` label then I dont know what the universe is anymore

**Comment by TheSardele** [comment]
I've seen this happen once or twice before, last time it was Ian, not sure if he was wearing a beret. My guess is that this is related to the dog fashion PR. Was unable to replicate it myself though, so it seems to happen rather rarely.

**Comment by Leanfrog** [comment]
It's worth noting, pictured above I was actually right next to Yann and I wasn't experiencing any lag or framerate issues, it's also important to note I was alive and not spectating so that may have something to do with it as well.
