### ISSUE TITLE
If you get EMPed with antidrop active it will not lose it's no_drop flag when thrown

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12835]
**Issue Description**:
When EMPed you throw away the item. It doesn't call dropped or something I think

**What did you expect to happen**: 
The no_drop to go away

**What happened instead**:
It got stuck in my hand forever

**Why is this bad/What are the consequences**:
Either extremely bad or extremely good for the victim depending on the item

**Steps to reproduce the problem**:
1. Get antidrop
2. Activate it with an item in hand
3. EMP one selves
4. Pick it up again

**When did the problem start happening**:
Since forever

**Extra information**:
Making it call dropped will prob fix it

**Comment by SteelSlayer** [comment]
This is the same issue as mine isn't it?  #11526

**Comment by farie82** [comment]
> This is the same issue as mine isn't it? #11526

Yep same issue. Couldt find it easily
