### ISSUE TITLE
Lavaland Mining outpost Cameras don't show up

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#12852]
The lavaland security cameras that allow the AI to see the outpost don't show up on the camera list so the AI can easily jump over to them to look.  You have to get lucky and find someone who you can track to there or send a borg or whatever.  All the cameras SHOULD show up in the "Show Camera List" button on the AI HUD likely either under "Lavaland" or "Mining Outpost" but aren't on the list at all.

https://gyazo.com/d7dad01b4a89548423521aedcefe7e19

https://gyazo.com/1360fd92879f9b847acd82a34473fb53

**Comment by TDSSS** [comment]
>You have to get lucky and find someone who you can track to there or send a borg or whatever. 

Can't you just use jump to network to jump to it and then pan your view over, though? Not that it's not a bug.

**Comment by Sollessa** [comment]
Hmmm, yeah I guess the jump to network button works but it's not terribly convenient.

**Comment by Sollessa** [comment]
I guess it's not really an issue since that seems to be what the network thing is for.

**Comment by procdrone** [comment]
For some reason, lavaland camera/rooms aren't standarised.

For example departments rooms are like this:

Medical Proceesing room
Medical Storage area
Medical Toilet.

While mining outpost rooms cameras are callously called

Lounge
Telecomms area
Ore processing

ETC. they dont have the department monicker added to them, which makes jumping there from camera list a nightmare.
