### ISSUE TITLE
Syringes' "Set Transfer Amount" popup window doesn't appear.

### ISSUE THREAD

**Issue by SpekkioKilwala** [ParadiseSS13/Paradise#12888]
**Problem Description**:
Syringes have got a rightclick menu item for changing the transfer amount. When you click on it, nothing happens.

**What did you expect to happen**: 
I expect a popup window to appear where I can select some specific amount of chemical that I want to transfer each time - you can do this with a Dropper and set the amount from 1-5, for example.

**What happened instead**:
Nothing. I clicked on the item, the rightclick menu disappeared, and the game didn't give me any new prompt.

**Why is this bad/What are the consequences:**
Lack of control when mixing precise amounts of chemicals. For myself I know it is quite inefficient for xenobio where chemicals must be injected into slime cores to produce a particular reaction; only one unit is required and it would be nice to only actually inject that much. Bizarre medical experiments probably want this even more badly because at least I have plasma on-tap.

**Steps to reproduce the problem**:
Pick up a syringe. Rightclick it in your hand. Click the "set transfer amount" menu item.

**When did the problem start happening**:
I didn't know about the intended functionality until today, so I don't know when it last worked. A mentor telling me how to do xenobio was unaware his instructions would not work.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
It was a pretty calm round. I was a regular scientist in xenobiology (and a touch of RnD and repairing some station damage), there were changelings. I tested again on the subsequent round (syndicate war declaration) with the same behaviour.

**Comment by farie82** [comment]
Syringes can only transfer 5u each time. The option is there die to the inheritance (syringe is a child of container just like a dropper)
There should however be a message to give feedback

**Comment by SpekkioKilwala** [comment]
Syringes are a pretty precise tool in real life. Why are they limited in SS13?

**Comment by Mitchs98** [comment]
Balance concerns, really. Being able to inject a full 15u at a time would be problematic in quite a few cases.

**Comment by taukausanake** [comment]
> inject a full 15u at a time

Can't you just do that by jamming into the person with harm intent? You break the syringe sure but you get the job done too

**Comment by farie82** [comment]
Thats on TG

**Comment by SpekkioKilwala** [comment]
Droppers are limited to do amounts from 1-5, all I want is the same range for syringes.
