### ISSUE TITLE
Eat groin without consequences

### ISSUE THREAD

**Issue by LegendWookie** [ParadiseSS13/Paradise#12884]
**Issue Description**:
You can eat a person's groin with matter eater without it affecting them.
They still lose their organs but they don't take any damage from the being eaten part.

**What did you expect to happen**: 
I ate my own groin and expected to die.

**What happened instead**:
I didn't die but just lost my organs which did not really impact me either.

**Why is this bad/What are the consequences**:
I guess no more killing people by eating their groins.

**Steps to reproduce the problem**:
1. get matter eater
2. aim at groin
3. chomp

**When did the problem start happening**:
I think a month ago, I don't recall.

**Extra information**:
Vox can't love.

**Comment by Cazdon** [comment]
Eating groin will contain admin consequence, however. 🔨 


Also a WTF tag please. 🙂
