### ISSUE TITLE
Vampire diseased touch works while cuffed.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12883]
**Issue Description**:

Vampires diseased touch works while the vampire is cuffed.

**What did you expect to happen**: 

The vampire to be unable to touch someone and infect them, as since you cant hug, disarm, or punch people while cuffed, you wouldn't be able to touch them and infect cuffed, especialy when the message given is the person hugs the target.

**What happened instead**:

You can use it cuffed, and infect sec in processing while they wait to get holy water for you.

**Why is this bad/What are the consequences**:

Logically you would be unable to do this , especially when buckle cuffed to a chair.

**Steps to reproduce the problem**:

Get 150 blood as a vampire.
Cuff yourself.
Stand beside target cuffed.
Infect them.

**When did the problem start happening**:

Presumably forever.

**Comment by taukausanake** [comment]
I'm going to say this is working as intended. You can't do those other things because you need arm movement to do them. A touch action though? You don't need to move your arms that much to move your hand over and give them a light pat or poke
