### ISSUE TITLE
Teleporter gun settings change wont change the loaded projectile

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12894]
Adjusting the settings of the teleported gun wont adjust the next shot you shoot, only affecting ones after that.

**What did you expect to happen**: 

I expect the next shot I shoot will set the person to the correct target.

**What happened instead**:

It will randomly teleport someone 15 tiles the first time, then go to correct setting, or teleport someone to the old beacon choice till one shot is fired.

**Why is this bad/What are the consequences**:

Annoying to use, wastes 25% of the ammo to change settings, makes people think its broken period and never used

**Steps to reproduce the problem**:

Spawn gun and target
Set gun to target destination
Shoot once, notice the person is randomly teleported in a 15 tile radius
Shoot again and notice person is sent to target

**When did the problem start happening**:

Most likely forever.

**Comment by Cazdon** [comment]
Ahhh, that makes sense as to why that happened to me one time. I thought it was just the teleporter gun having a chance to send randomly and not to the destination.

**Comment by SteelSlayer** [comment]
I believe this was fixed by #16990
