### ISSUE TITLE
Shuttle Manipulator runtimes

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#12903]
[2020-01-12T06:26:49] Runtime in shuttle_manipulator.dm,117: Cannot read null.name

So apprently when used the mainpulator likes to put the hospital shuttle as the EMERGENCY SHUTTLE DOCK rather then the ADMIN SHUTTLE DOCK. And the emergency shuttle tab is no longer clickable to reset it.
Its makeing me think the docking port ids got crossed somewhere.

**Comment by Sirryan2002** [comment]
confirmed to still be an issue

**Comment by Sirryan2002** [comment]
```[2022-07-11T09:56:57] Runtime in shuttle_manipulator.dm,109: Cannot read null.name
   proc name: ui data (/obj/machinery/shuttle_manipulator/ui_data)
   usr: Arabella Turner (sirryan2002) (/mob/dead/observer)
   usr.loc: The floor (77,108,1) (/turf/simulated/floor/plasteel/dark)```
