### ISSUE TITLE
Alien corrosive acid one shots borgs, most simple mobs... and people.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12901]
**Issue Description**:

Alien corrosive acid one shots most simple mobs, borgs, and even people, dealing 200 damage to simple mobs, or 140 brute and 280 burn to humanoids instantly

**What did you expect to happen**: 

It to start slowly burning the target, needing a shower or fast repairs to keep them alive, but not too much of an issue at the exact moment.

**What happened instead**:

It instantly kills anything short of megafauna, by dealing 200 burn, or 140 brute and 280 burn to humanoids.

**Why is this bad/What are the consequences**:

Xenos already have enough balance issues, instantly killing anything buy standing beside them is a bit much 

**Steps to reproduce the problem**:

Be a xeno sentinel / queen / xeno organ user.
Right click on target
Press corrosive acid
Watch as the person instantly goes hard crit from the damage, and dies seconds later.

**When did the problem start happening**:

Object damage rework changed the way the acid worked, and would have changed this.

**Extra information**:

https://imgur.com/a/FxnZrP5

**Comment by moxian** [comment]
Just some code links.

Alien corrosive acid utilizes 100 "units" of 200-power acid:
https://github.com/ParadiseSS13/Paradise/blob/076ef673cda2630eed893db11eb27154a78d56ee/code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm#L80

Simplemob and borg response to that is to take `200 * min(1, 10) = 200` damage:
https://github.com/ParadiseSS13/Paradise/blob/076ef673cda2630eed893db11eb27154a78d56ee/code/modules/mob/living/living.dm#L269-272

Humanoids response has several more steps involved, but the end result is the same. Specifically, the "acidity" is determined to be `200 * min(100 * 0.005, 1) = 100`
https://github.com/ParadiseSS13/Paradise/blob/076ef673cda2630eed893db11eb27154a78d56ee/code/modules/mob/living/carbon/human/human_defense.dm#L158-L161
and then all affected organs (which is "all organs" in this case) receive `acidity` brute and `2*acidity` burn damage, with some bonus damage to the head
https://github.com/ParadiseSS13/Paradise/blob/076ef673cda2630eed893db11eb27154a78d56ee/code/modules/mob/living/carbon/human/human_defense.dm#L272-L278

I'm honestly unsure why in your tests you are "only" receiving 140 brute total and not 1100, but /shrug.

Guess the fix here would be to either decrease the power or the volume of alien acid power, and leave the damage handling as is.

**Comment by Citinited** [comment]
> I'm honestly unsure why in your tests you are "only" receiving 140 brute total and not 1100, but /shrug.

Might be to do with brute damage being rounded after a certain threshold has been reached. For example, no matter how much you hit a body, it will only go up to around 600 brute damage or so.
