### ISSUE TITLE
You can win two Holoparasite rolls!

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#12905]
**What did you expect to happen**: 
If a player wins one antag roll, to not be in the running for any others they may have applied for.

**What happened instead**:
A player managed to win two holoparasite rolls. Was made one, and then suddenly ripped out and made the other.

**Why is this bad/What are the consequences**:
First traitor's holoparasite got lost to time-space, no replacement was had.

**Steps to reproduce the problem**:
Get two players holoparasite injectors, get an observer. Have both injectors poll at similar times. Have the observer win both rolls. He should get sucked from one to the other, and the first one will have no active CKey.

**When did the problem start happening**:
Maybe forever. Just saw it today.

**Comment by Birdtalon** [comment]
https://github.com/ParadiseSS13/Paradise/blob/076ef673cda2630eed893db11eb27154a78d56ee/code/game/gamemodes/miniantags/guardian/guardian.dm#L300-L309

Suggest adding a check here to make sure they're still an observer.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/13710 might fix this

**Comment by silverplatedelta** [comment]
99.9% sure this is fixed with the PR Kyet mentioned above. Thanks for the report!
