### ISSUE TITLE
Surgical Toolset/regular Toolset Implant buggued

### ISSUE THREAD

**Issue by Traitre** [ParadiseSS13/Paradise#12908]
**Issue Description**:

it seem that surgicaltool/toolset implants both have a weird glitch/bug about their settings. The person retrieving them could see them rightly set up while a surgeon that is asked to install them may NOT see them set up for different arms and instead see them as for the same arm, forcing them to re-set them or fail surgery multiple time not understanding the problem.

**What did you expect to happen**: 

I expected for both implants that had been set correctly by R&D to be able to be implanted without issue (one for right arm, one for left, both were correctly set up on my end)

**What happened instead**:

The surgeon would say that there was no room when the implants were set for the arms that weren't being used (left and right, never the same). We found after a bit of trial and error that for some reason the surgeon may not see the same setting as the patient bringing the items in when they arrive in surgery.

**Why is this bad/What are the consequences**:

this simple problem can cause issues during implantation, i spent a good 15 minutes on an OR table with a surgeon trying to figure out why the damn implants refused to fit in, let's just say i was a lot less full of blood after that.

**Steps to reproduce the problem**:

Get yourself both toolset implants (i also asked for medhud and welderprotection implants) and have them correctly set up by R&D for each arm, and have another surgeon try to install them for you (it may only not work if they connect after the implants have been set). If you see the implants with the correct setup but your surgeon isn't seeing the same and both are for the same arm on their hand, you have reproduced it.

**When did the problem start happening**:

when i first tried to get BOTH arm implants due to the need to be able to handle robotics as a surgeon if need be.

**Extra information**:

**Comment by Cazdon** [comment]
Err did you forget to screwdriver them to switch which arm they went into? By default they only work on the right arm and you have to screwdriver the implant to make it fit in the left arm.

**Comment by Traitre** [comment]
After some more messing about, it seems this bug only applies (at least to me) whenever BOTH the surgeon and me were NOT in LoS of the implants as they were getting changed to the arm they needed to be set to (right or left, whenver the case). it also applied if Either of us was seeing it, but not both.
If the surgeon did the set, it would show for them but not for me, wich would prevent them from putting the implant in, same result in the opposite case.
