### ISSUE TITLE
The greytide virus triggers a bunch of times at once

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12914]
The greytide virus (Brig hack virus) triggers a bunch of times one after another from time to time.

**What did you expect to happen**: 
The virus to hit once and to be announced once

**What happened instead**:
ALERT ALERT ALERT ALERT ...
The poor brig never got hit as hard as it did last round.

**Why is this bad/What are the consequences**:
It's mostly spammy and annoying. The brig will either be unpowered by the AI and thus not affected. Or will be open anyway.

**Steps to reproduce the problem**:
No clue. Might be something to do with the event system.

**When did the problem start happening**:
Unknown

**Extra information**:
There were a bunch of double events that round. Some maybe admin spawned.
Two times spiders. Two times meteors

**Comment by Spacemanspark** [comment]
Yeah, the event manager has been acting weird lately.
