### ISSUE TITLE
NT Rep issue.

### ISSUE THREAD

**Issue by GarryGrizzly555** [ParadiseSS13/Paradise#12915]
**Issue Description**:

As an NT Rep, I have been trying to log into the employment records terminal located in my office, and the login button just doesn't work. Seems like I have no access for some reason. I tried that for two days with the same results.

**What did you expect to happen**: 

I expected to log into the computer, because it's in my office for a reason, right?

**What happened instead**:

I can't log in.

**Why is this bad/What are the consequences**:

I have no idea, but it's pointless to have a terminal I can't log in to on my desk.

**Steps to reproduce the problem**:

Go NT Rep, then try to log into the computer.

**When did the problem start happening**:

I got NT Rep two days ago from making this report, and it didn't work already.

**Extra information**:

I have no idea if someone reported that already, because I'm doing this in a hurry.

**Comment by TDSSS** [comment]
just to make sure, you also inserted your ID in the console, you didn't just mash the login button without putting an ID in, right?

**Comment by AffectedArc07** [comment]
In the console theres a slot the looks like `[--------------------]`. Click that with your ID in hand and press `Login`

**Comment by GarryGrizzly555** [comment]
I did that. I'm not that stupid. I tried multiple times with and without the ID inserted. Slapped the console with my ID, inserted it in. Nothing works.

**Comment by GarryGrizzly555** [comment]
I also reconnected because it usually fixes the issue with any extra windows not working correctly in the game. Nada. It just doesn't work.

**Comment by GarryGrizzly555** [comment]
Alright, I know the solution to that issue.
It couldn't have been simplier than that, but it still annoys me that I have to bother the HoP every shift just to get that access.
Apparently the NT Rep ID doesn't have the access to the employment records terminal by default for some reason.

**Comment by Ty-Omaha** [comment]
try to be more specific in titles "NT rep issue" could mean a million different things

**Comment by Ty-Omaha** [comment]
and you should update the main post with this new information you discovered

**Comment by GarryGrizzly555** [comment]
I should close the post. I discovered that the access required for that console is HoP.
I do realise why I don't have it, but I have no idea why they gave me that terminal then.

**Comment by TDSSS** [comment]
NT Rep used to have HoP access in the past for some reason.

**Comment by GarryGrizzly555** [comment]
That might have been the issue.
The terminal is a relic of the past.
No need to remove it though. Even if it's not intended I can just ask HoP for the access then.
