### ISSUE TITLE
Wizard Spell Upgrading

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1291]
This may have been fixed, but I noticed it was an issue about a week ago:

Purchasing a spell a second time is meant to upgrade the spell and lower it's cooldown...only....that's...not happening..

What is happening: You get a whole new instance of the same spell.

Ei 'Nath! Ei 'Nath! Ei 'Nath! Ei 'Nath!

GIbbing entire swarms of people after a single magic missile never felt so gooddddd.

**Comment by tigercat2000** [comment]
Going to guess this is related to the whole mess of mind & mob spell lists both being used.
