### ISSUE TITLE
Having an issue with seeing chat

### ISSUE THREAD

**Issue by Sheep-Person** [ParadiseSS13/Paradise#12925]
**Problem Description**:
Every single time currently, when i log onto the server it gives me a red chat error that im having a connection issue, but its not on my end.

**What did you expect to happen**: 
Why do you think this is an issue?
I expected chat to move as normal and work, i expected to be able to hear sound. I expected to be able to interact with in game UI's

**What happened instead**:
How is what happened different from what you expected?
Nothing worked except basic gameplay such as opening doors and using items and such.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
I cant play the game and i was told this isn't a single person issue. But the reason its bad is because anyone who has this issue cannot see what another person or admin is saying in chat as that no longer moves or works when the issue presents its self.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Log in.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Two or three months ago it worked, took a break and came back. not working.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Its any game mode thus far. - Chat, Sound, UI. Broken.
![lost](https://user-images.githubusercontent.com/60285114/73118223-f7f3c580-3f16-11ea-9bc2-65d30b70e5bc.png)

**Comment by FreeStylaLT** [comment]
Do you have the Beta version or the Stable version of Byond?

**Comment by Sheep-Person** [comment]
> Do you use the Beta version or the Stable version of Byond for Paradise?

Tried both, neither worked. Tried reinstalling. Didn't work. Tried everything thus far.

**Comment by Ty-Omaha** [comment]
clear your cache

**Comment by DGamerL** [comment]
We don't use the native Byond chat anymore, but instead we moved over to TGChat!
