### ISSUE TITLE
Restarting MC does not re-enable logging

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#12936]
When the MC crashes, and is restarted, nothing is logged to game.log or runtime.log for the rest of the round.

**What did you expect to happen**: 
Logs to work again.

**What happened instead**:
They did not work.

**Why is this bad/What are the consequences**:
Makes figuring out what happened, or even looking up anything from that round, impossible.

**Steps to reproduce the problem**:
1) Crash/restart the MC somehow
2) Do something ingame.
3) Observe that nothing is logged.

**Comment by AffectedArc07** [comment]
This has been fixed. Bug that caused this was the MC making all logs go to `config_error.log` on `/New()`, which would then be overwritten by `SetupLogs()` in `world/New()`. This is also why OOC would re-enable itself.
