### ISSUE TITLE
Block of Static listed as Pipe

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#12937]
![SS13](https://user-images.githubusercontent.com/9967634/73393201-e442b900-42a0-11ea-8c4e-1ccb5698bdc5.png)

**Issue Description**: A pipe looks like a giant block of static. Or a giant block of static is labeled as a pipe. Not sure which.

**What did you expect to happen**: It would look like a pipe.

**What happened instead**: It's a giant block of static.

**Why is this bad/What are the consequences**: A giant block of static is a weird-looking pipe.

**Steps to reproduce the problem**: Unknown. Just found it while looking over some breach damage.

**When did the problem start happening**:

**Extra information**: It occured at 3:10 PM EST 1/29/20.

**Comment by Spaghetti-bit** [comment]
Fixed around 2023, unable to find the PR
