### ISSUE TITLE
Advanced pinpointer pointing to borgs when searching for the blueprints

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12942]
As the title says

**What did you expect to happen**: 
It to point to the blueprints

**What happened instead**:
Find a borg instead

**Why is this bad/What are the consequences**:
It's a bug

**Steps to reproduce the problem**:
Have an engi borg and pinpoint to the blueprints

Edit:
Slime blueprints might also fuck it up. Same path

**Comment by Citinited** [comment]
Should be easy enough to fix by making it look for a subtype of blueprints, then replacing the blueprints in the CE's locker with the new subtype

**Comment by farie82** [comment]
> Should be easy enough to fix by making it look for a subtype of blueprints, then replacing the blueprints in the CE's locker with the new subtype

Exactly the same idea we had in coding chat :P

**Comment by Citinited** [comment]
Ahh I'm not on discord :P excellent

**Comment by SteelSlayer** [comment]
I think you can close this now since #12950 was merged
