### ISSUE TITLE
Some airlocks and windows are invisible in map editor

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#12955]
**Issue Description**:
External airlocks and the windows of the escape shuttle are invisible in the map editor, because they have an incorrect icon_state.

**What did you expect to happen**: 
For them to be visible

**What happened instead**:
they aren't

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:
load up the current map in a map editor, look at the escape shuttle or the AIsat's airlocks

**When did the problem start happening**:

**Extra information**:
Thanks to monster 860 for noticing it in discord when testing his map tool.

Should be fixed by a simple map edit

**Comment by DGamerL** [comment]
As far as we all can see, every case of invisible mapped objects is gone! Thanks for making this report!
