### ISSUE TITLE
Item Dupe Bug

### ISSUE THREAD

**Issue by xProlithium** [ParadiseSS13/Paradise#12958]
**Issue Description**: Recall spell and anti drop causes an item dupe.

**What did you expect to happen**: Item being taken out of the anti-drop active hand, or fail to recall.

**What happened instead**: The recall spell puts the item back in the original owners hand, but a copy remains in the active anti-drop hand.

**Why is this bad/What are the consequences**: It's an item dupe.

**Steps to reproduce the problem**: Two players. Player A has recall active. Player B has anti-drop. Player B picks up item and activates anti-drop. Player A recalls the item. Player A gets the item back, but Player B still has the item in their hand.

**When did the problem start happening**: 2/6/2020 - found out on accident, confirmed to be duplicate a few rounds later in the admin test area.

**Extra information**: The items can't be dropped even if you disable anti-drop. You're then stuck with the item in your hand similar to the Rod of whatever-you-call-it.

**Comment by Ty-Omaha** [comment]
#12051
