### ISSUE TITLE
Flipped Tables are infinitely stackable

### ISSUE THREAD

**Issue by Matt1311** [ParadiseSS13/Paradise#12957]
**Issue Description**:

An infinite amount of Tables can be flipped on one tile to basically make you invincible to bullets

**What did you expect to happen**: 

It could mess up game balance

**What happened instead**:

Only one flipped table per tile should be possible

**Why is this bad/What are the consequences**:

You could cheese nukies super hard by basically nullifying their ranged weapons

**Steps to reproduce the problem**:

1.Build a table
2.Flip it
3.Repeat until satisfied

**When did the problem start happening**:

I think it has been like this forever

**Extra information**:

Thats all information i have

**Comment by datlo** [comment]
![image](https://user-images.githubusercontent.com/22121511/73871589-678a7e80-484e-11ea-9641-5f674e7fc2ad.png)

**Comment by lolzyking** [comment]
It isn't actually that resilient to bullets, also please dont take away the four table fort of kidnapping
