### ISSUE TITLE
Inserting Binary Translator Key into Worn Headpiece makes Key disappear

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#12953]
**Issue Description**:

I inserted a Binary Translator Key into the headpiece I was wearing and it disappeared and didn't work.

**What did you expect to happen**: 

I expected to hear the Robot channel.

**What happened instead**:

I heard no channel and when I took a screwdriver to my headpiece, it only had the standard key.

**Why is this bad/What are the consequences**:

It was a waste of 5 TP.

**Steps to reproduce the problem**:

1. Buy Binary Translator Key.
2. Insert it into worn headpiece.

**When did the problem start happening**:

**Extra information**:

**Comment by SteelSlayer** [comment]
I tried to replicate this, but it works fine for me. I can hear and speak on the binary channel, as well as take out the encryption key. Any other relevant info you can think of? Maybe the type of headset you were using.

**Comment by Mitchs98** [comment]
Unable to replicate with any headset, even non standard headsets the crew has no access too/we don't use, given the provided information.

**Comment by AffectedArc07** [comment]
Cannot be reproduced. Feel free to re-open this at a later date if you can reliably reproduce this issue
