### ISSUE TITLE
Slime Superspeed

### ISSUE THREAD

**Issue by Marcolinoj** [ParadiseSS13/Paradise#12979]
**Issue Description**:

When getting out of air scrubbers as a purple slime (havent tried with other types of slimes) you can get a lot of speed.

**What did you expect to happen**: 
I expected to just get out of the scrubber and have normal speed.

**What happened instead**:
I got out of the scrubber and began being really fast, way too fast.

**Why is this bad/What are the consequences**:
A slime player could go around and abuse the speed while fighting people.

**Steps to reproduce the problem**:
1- (As a slime) Get into an air scrubber.
2- Move around the vents for a while.
3- Get out of any scrubber, then you should get a lot of speed for 10 seconds.

**When did the problem start happening**:
Probably always broken, but I dont know.

**Extra information**:
None, other than I did it while being a sentient purple slime, it might not work with another slime.

**Comment by lolzyking** [comment]
Slime speed is based on body temp
Scrubbers are usually HOT

**Comment by Mitchs98** [comment]
As Lolzy said, after very brief testing, not a bug. Only happens when the scrubbers are hot, slimes are meant to go sonic speed at high body temperatures. Spawned in a test slime, crawled around in scrubbers, no change. Set body temp to 400 and I went faster than meth.

Issue can be closed.
