### ISSUE TITLE
Service Borg Drink Mixer (Endless Drinks, weather you want them or not)

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#12975]
**Issue Description**:

While I haven't played a service borg recently I do recall not too long ago a month at most that when mixing drinks in the service borgs mixing shaker, like say a milk shake before you serve the crew, after a short amount of time the shaker would start to refill with the drink again even if you completely emptied it, which became quite a problem if you wanted to ever mix anything else because there was no way to stop or cancel the mixing though it did seem to be free for no energy cost.

**What did you expect to happen**: 

To empty the shaker and it to remain empty until I filled it up again.

**What happened instead**:

It refilled like the service borgs other containers but with the last drink inside of it instead.

**Why is this bad/What are the consequences**:

Because maybe you want to serve a different drink or maybe it should have a toggle or something because its kind of annoying.

**Steps to reproduce the problem**:

Mix drink in shaker, pour drink to thirsty crew. Wait? 

**When did the problem start happening**:

No idea! It was a thing the first time I played service borg so I assume for quite awhile.

**Extra information**:

I have no idea if this was fixed or not but as of the last time I played a service borg it wasn't and it wasn't that long ago.

**Comment by datlo** [comment]
As a workaround I believe that using your industrial dropper to empty the mixer will prevent it from refilling.
