### ISSUE TITLE
Picket signs have no character limit

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#12973]
**Issue Description**:

What the title says.

**What did you expect to happen**: 

To not be able to copypaste the entire Bee Movie script into a sign.

**What happened instead**:

I was in fact able to copypaste the entire* Bee Movie script into a sign.

*disclaimer: I didn't actually paste the whole thing, just the first 10000 characters. Seemed like an arbitrarily long string but luckily didn't result in a broken chat.

**Why is this bad/What are the consequences**:

If 10000 chars fit in I imagine there's no limit to it. So you could in theory paste millions of chars, breaking the chat or at the very least being extremely annoying. Or potentially worse. Also you might get bwoinked for copypasting the entire Bee Movie script into a sign.

**Steps to reproduce the problem**:

1. Get a picket sign (I actually don't know how to craft one ingame. Maybe with wood and cardboard?)
2. Paste / write a really long string in it using a pen.
3. Annoy the hell out of everyone by filling the entire chat window with a button press, or even when someone simply examines you.

**When did the problem start happening**:

I imagine since they were first introduced. This is why you stress test things.

**Extra information**:

According to all known laws of aviation, there is no way a bee should be able to fly. Its wings are too small to get its fat little body off the ground. The bee, of course, flies anyway because bees don't care what humans think is impossible.

**Comment by taukausanake** [comment]
>Not posting WGW or the Navy Seal copypasta instead

but I guess those are quite a bit shorter than the Bee Movie

**Comment by Sikroth** [comment]
My first idea was WGW (just hinted at doing it IC, didn't really plan on doing it) but then a helpful Poly suggested the bee movie script which was both funny and a great way to test huge text lenghts. So that's what I did :D
