### ISSUE TITLE
IPCs are blinding themselves during self-repair

### ISSUE THREAD

**Issue by hunakos57** [ParadiseSS13/Paradise#12987]
**Issue Description**:

IPCs are blinding themselves during self-repair with the welders.

**What did you expect to happen**: 

It is annoying, and it wasn't like this about 2 days ago.

**What happened instead**:

Got flashed each and every time I fixed a dent.

**Why is this bad/What are the consequences**:

Making it annoying to play.

**Steps to reproduce the problem**:

Get denting damage, use welder on the targeted area, get flashed by it.

**When did the problem start happening**:

2 days ago it was fine, or even just a few hours ago.

**Extra information**:

Not much to add.

**Comment by craftxbox** [comment]
This sounds like its working as intended. Humans get blinded from repairing their prosthetics aswell, why shouldnt ipc?

**Comment by hunakos57** [comment]
Then why was this only fixed today? Since as I see, you have to write a code to make an exception for IPCs to not blind themselves during self-maintenance, but now they do.

**Comment by SteelSlayer** [comment]
I double checked and for the record, humans do not blind themselves while repairing their robo-limbs, and neither do IPC's. This change was unintentional/an oversight.
