### ISSUE TITLE
Screwdriver not working for IRC Surgery

### ISSUE THREAD

**Issue by JimKil3** [ParadiseSS13/Paradise#12981]
**Issue Description**:

I cannot perform internal component manipulation because a screwdriver cancels the surgery instead of unscrewing a panel.

**What did you expect to happen**: 

The surgery to progress normally

**What happened instead**:

The surgery was canceled

**Why is this bad/What are the consequences**:

Cannot perform internal cybernetic manipulation on an irc.

**Steps to reproduce the problem**:

Start internal component manipulation on an irc.
Attempt first step.
**When did the problem start happening**:

I remember it working about 2 days ago.

**Extra information**:

**Comment by Citinited** [comment]
Currently working to fix this one, current workaround is to use a kitchen knife or a coin
