### ISSUE TITLE
Thermite can no longer be triggered by a welder.

### ISSUE THREAD

**Issue by GreeyKorala** [ParadiseSS13/Paradise#12997]
**Issue Description**:

When trying to use thermite on a reinforced wall it no longer is triggerable by a welder.

**What did you expect to happen**: 

The current patch of the game has made this a problem, I'm not sure as I don't know anything about coding why the issue is going on. Perhaps it's literally just the way the game thinks you are trying to use the tool on the wall and cancels the action?
 I genuinely don't know, I'm guessing.
**What happened instead**:

It just doesn't work when it used to.

**Why is this bad/What are the consequences**:

Thermite is important to remove walls quickly.

**Steps to reproduce the problem**:

Use thermite on an reinforced wall then try to heat it using a welder.

**When did the problem start happening**:

This release. About three days ago.

**Extra information**:

Nothing more to say.

**Comment by Citinited** [comment]
Ahh I need to get a fix for this, I'll get that done this weekend
