### ISSUE TITLE
Screwdrivers fully dismantle tables instead of leaving frames.

### ISSUE THREAD

**Issue by Aquilar** [ParadiseSS13/Paradise#12990]
**Issue Description**:

Screwdrivers fully dismantle tables instead of just removing the top

**What did you expect to happen**: 

a table frame and sheet of metal appear

**What happened instead**:

two rods and a metal sheet.

**Why is this bad/What are the consequences**:

sometimes you just want to remove the tops of tables instead of dismantling them entirely so you can replace the top with something else.

**Steps to reproduce the problem**:

use a screwdriver on any table, plasteel tables still need welding but they are affected as well

**When did the problem start happening**:

while testing out a reworked drill on my test server, I proceeded back out and test on a clean server and found the screwdriver was dismantling tables entirely like the wrench instead of leaving the table frame.

**Comment by Citinited** [comment]
Got a fix for this one
