### ISSUE TITLE
Cult Sac Objectives Can Target Offstation Roles

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#12998]
**Issue Description**:
CC officer on z2 was selected as cult sac target when one cryoed, despite having mind.offstation_role = 1.

**What did you expect to happen**: 
A crew member to be picked as the sac objective target.

**What happened instead**:
A mob with mind.offstation_role==1 was picked instead.

**Why is this bad/What are the consequences**:
Cult can get sac objectives which target mobs they cannot possibly get to.
Such mobs may have vox/etc names which don't make it obvious they're offstation roles.
So cult can spend entire round searching for mysterious voxxies who cannot be found anywhere.

**Steps to reproduce the problem**:
Cryo the cult sac target.
Have a offstation role character exist and be the only human.
Cult obj should target the offstation role.

**Comment by Cazdon** [comment]
`/datum/game_mode/cult/proc/get_possible_sac_targets()
	var/list/possible_sac_targets = list()
	for(var/mob/living/carbon/human/player in GLOB.player_list)
		if(player.mind && !is_convertable_to_cult(player.mind) && (player.stat != DEAD))
			possible_sac_targets += player.mind
	if(!possible_sac_targets.len)
	//There are no living Unconvertables on the station. Looking for a Sacrifice Target among the ordinary crewmembers
		for(var/mob/living/carbon/human/player in GLOB.player_list)
			if(is_secure_level(player.z)) //We can't sacrifice people that are on the centcom z-level
				continue
			if(player.mind && !(player.mind in cult) && (player.stat != DEAD))//make DAMN sure they are not dead
				possible_sac_targets += player.mind
	return possible_sac_targets`


looks like it only checks if 'is_secure_level' if they're already going through the list of convertables, and considering the mindshield puts them in the list of non-convertables, it searches for them too. Should be a simple fix.
