### ISSUE TITLE
Teleporter Beacons: Unable to Teleport To

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1299]
Fairly obscure bug, but a bug none the less.

If you lock onto a teleporter beacon then place that beacon in your pocket/in a crate/in a locker then attempt to teleporter to it, it won't take you to the location of that beacon.

I suspect this occurs because it sees the location as "null" or "0,0,0" as opposed to its get_turf location.

Either case, this used to work in the past and its' certainly how it works on TG--dunno how/when it broke.

**Comment by Plotron** [comment]
Thanks for telling me... Now I see how I have managed to space so many blueshields.

This is a terrible bug. This mechanic used to work just fine, as I had at least one nuke op team teleport ontop of me thanks to the tracker in my pocket.

Is there a workaround? Does it work if you 'recalibrate' the teleporter once the tracker is in your pocket?

Could it be possible that this is why hand tele portals sometimes do not let thrown items through if the portal is set to the pocketed beacon?

**Comment by Fox-McCloud** [comment]
What happens is: you'll try to enter the portal and it won't let you through---but if you keep trying, the times that it WILL teleport you are the times where it absolutely will space you.
