### ISSUE TITLE
Nukie shuttle consoles are destructible despite INDESTRUCTIBLE tag

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#12991]
**Issue Description**:

You can destroy nukie shuttle consoles when they have the INDESTRUCTIBLE tag.

**What did you expect to happen**: 

You shouldnt be able to.

**What happened instead**:

Sad nukies.

**Why is this bad/What are the consequences**:

Bug.

**Steps to reproduce the problem**:

I am not certain but likely not difficult to reproduce since it's happened on live more than once

**When did the problem start happening**:

Likely universal damage

**Extra information**:

Happened today on live 16/02/2020

**Comment by Ty-Omaha** [comment]
the INDESTRUCTIBLE flag is for damage only and not deconstruction which is why it still could be deconstructed

NODECONSTRUCT is for deconstruction with tools which is what I assume this is about
