### ISSUE TITLE
[RUNTIME] Terror spiders fail to spawn with a runtime

### ISSUE THREAD

**Issue by dovydas12345** [ParadiseSS13/Paradise#13005]
**Issue Description**:

Terror spiders do not spawn when the event fires.

**What did you expect to happen**: 

For the spiders to spawn properly.

**What happened instead**:

Terror spiders didn't happen due to a runtime.

**Why is this bad/What are the consequences**:

Pretty obvious why. 

**Steps to reproduce the problem**:

Seems to happen when the terror spider event fires.

**When did the problem start happening**:

Today (2020-02-18) is the first time I seen it happen.

**Extra information**:

Runtime:
![image](https://user-images.githubusercontent.com/37041561/74777899-227d3800-52a3-11ea-88be-f8040d4971d4.png)

**Comment by farie82** [comment]
Breaks due to this:
![image](https://user-images.githubusercontent.com/15887760/74778870-be577580-529c-11ea-87bb-b6f56f2af9a5.png)
A vent has no parent while it should have one(?)

**Comment by Kyep** [comment]
Should be fixable by just adding "&& temp_vent.parent" into the if statement, to handle the case where there is a vent with no parent, by skipping such vents.
