### ISSUE TITLE
Hunger and talking glitch when transplanting a human head onto a monkey

### ISSUE THREAD

**Issue by Purotozilla** [ParadiseSS13/Paradise#13001]
**Issue Description**:

I had my head transplanted onto a monkey's body and I couldn't satisfy my hunger or talk. Which caused me to starve. I also could only talk to animals, even though I had my human brain and memories. No matter how much I ate, my hunger would not go down and I continued to starve. 

**What did you expect to happen**: 

I expected to have my head transplanted on a monkey's body so I could entertain people around the station and frankly, because I didn't know if it would work. But I expected to talk to people and satiate my hunger but I wasn't able to. I was able to talk to other animals, but I guess I didn't count as sentient.

**What happened instead**:

Whenever I ate, my hunger would not go down. I continued to starve and I could eat unlimited amounts of food. I also could not understand anyone or communicate with anyone to tell them this. I could talk to other animals. 

**Why is this bad/What are the consequences**:

Having your head transplanted onto a monkey is really fun and entertaining. It adds pizzazz to the round and people seemed to enjoy it. But it doesn't make sense either, my head has all my memories and experiences, and yet I couldn't understand anyone. Also, I was eating and giving my body food but I was still hungry. 

**Steps to reproduce the problem**:

1. Have human head surgically removed first to reduce the amount of time the monkey's body is dead so the tissue doesn't get damaged
2. Put monkey under sedation and remove head as quickly as possible
3. Sew the human head onto the monkey's body and resuscitate
4. Stabilize the patient and make sure they are alive
5. As the monkey with a human head, attempt to talk to or understand the staff on the ship
6.Also as the monkey with a human head, attempt to eat food and fill yourself
**When did the problem start happening**:

I tried this about a month ago.

**Extra information**:

Not really, to get the head on successfully is a little challenging but I thought it was really fun. But I wanted to talk to people and not starve.

**Comment by SteelSlayer** [comment]
I found some very old related issues while searching this topic. These can also be closed if someone decides to fix this bug, just thought I'd post them here: #4345, #6228

**Comment by Purotozilla** [comment]
Thanks for linking those. Can't believe it's been an issue this long.

**Comment by Sirryan2002** [comment]
I believe this is fixed? New issue report should be opened if this issue persists.
