### ISSUE TITLE
Unable to pilot mecha

### ISSUE THREAD

**Issue by Xlaits** [ParadiseSS13/Paradise#13024]
**Issue Description**:

Mecha are unpilotable. No amount of right clicking or left clicking will let me in.

**What did you expect to happen**: 

Ability to pilot any mech.

**What happened instead**:

Inability to pilot mech.

**Why is this bad/What are the consequences**:

No one on my server would be able to run any mechs.

**Steps to reproduce the problem**:

create mech (spawned or legit), set up opcodes, right-click (as per wiki).

**Comment by farie82** [comment]
Wiki is incorrect here. You have to drag your sprite onto the mecha

**Comment by BakKeener** [comment]
another wiki update is needed it seems :/

**Comment by Xlaits** [comment]
Thanks all.

**Comment by AffectedArc07** [comment]
How old is that wiki article? It’s been click drag for the past like 2 years?
