### ISSUE TITLE
Disposals Delivery Chute can't be dissasembled

### ISSUE THREAD

**Issue by LegendWookie** [ParadiseSS13/Paradise#13035]
**Issue Description**:
Usually to dissasemble a delivery chute you use a screwdriver and then welder, but for some reason you can't use a welder on it anymore.

**What did you expect to happen**: 
Try to dissasemble one.

**What happened instead**:
Nothing

**Why is this bad/What are the consequences**:
not being able to do something that you should be able to is bad

**Steps to reproduce the problem**:
Try to dissasemble a Delivery Chute and fail doing so.

**When did the problem start**:
27.02.2020

**Comment by Citinited** [comment]
Probably introduced in the tool refactor, I will get a fix for this tonight (Related to #13023?)
