### ISSUE TITLE
Mini-enery crossbow is broken.

### ISSUE THREAD

**Issue by Sotrennel** [ParadiseSS13/Paradise#1304]
The mini-energy crossbow seems to not reload on itself, and if it does, it takes more than 15 minutes, which I think is a bug. (And it pissed me off)

**Comment by Fox-McCloud** [comment]
It doesn't automatically reload itself; you have to manually click on it to reload.

**Comment by Fox-McCloud** [comment]
For clarity, the days of the spammable click-click-click ranged instant stun energy crossbow are gone.
