### ISSUE TITLE
Some ERT borg module pick runtimes

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#13055]
**Issue Description**:

An ERT borg choosing either the engineering or medical module gets the following runtimes:
![image](https://user-images.githubusercontent.com/42044220/75601531-a0022e80-5a81-11ea-910c-592407eb72b5.png)

**Why is this bad/What are the consequences**:
Module picking runtimes halfway through the module picking code which means the ERT borgs never get their deparment sprite and will instead will be the standard grey borg. Also some important code never executes like the engineering borg getting its "magboot" setting, for example.

**Steps to reproduce the problem**:
1. Put yourself into a `mob/living/silicon/robot/ert` borg
2. Try to choose either the medical or engineering module

**Comment by Kyep** [comment]
I have this fixed as part of a borg PR I am working on.
PR should go up in a day or two.
