### ISSUE TITLE
Advanced Kingstons keeps flipping between tajaran and the intended species

### ISSUE THREAD

**Issue by TheSardele** [ParadiseSS13/Paradise#13058]
**Issue Description**:
The advanced kingstons virus turns people into tajarans and the actual target species at random, switching back and forth.

**What did you expect to happen**: 
For them to only turn into the target species.

**What happened instead**:
They kept flipping between tajarans and the target species.

**Why is this bad/What are the consequences**:
Virus doesn't work as intended. Also, because of the way we handle species changes, they constantly get a full heal as their species changes.

**Steps to reproduce the problem**:
Give someone advanced kingstons (make sure that the target species isn't tajarans), wait for the disease to get bad enough. watch them keep flipping back and forth.

**Extra information**:
This is probably due to advanced kingstons inheriting from normal kingstons (which only turns you into tajarans, no other species), and calling ..() as the very first line in their stage_act.

**Comment by Ty-Omaha** [comment]
@TheSardele when talking about specific lines of code you can click the number on the left then copy the URL and paste it in like this
https://github.com/ParadiseSS13/Paradise/blob/4a3e5e00aa30e3eeeb5b5d96da916703fdfc49d3/code/datums/diseases/kingstons.dm#L72
