### ISSUE TITLE
Mining Jump Boots bug

### ISSUE THREAD

**Issue by Da-Dman234** [ParadiseSS13/Paradise#13065]
**Issue Description**:
When wearing the Mining Jump Boots [clothing/bhop] you can jump while in the vacuum of space while touching nothing, resulting in you being able to navigate space at extreme speeds.

**What did you expect to happen**: 
To not be able to jump off nothing at sanic level speeds

**What happened instead**:
I became literally sonic in space

**Why is this bad/What are the consequences**:
You can move through space at broken speeds

**Steps to reproduce the problem**:
Buy the mining jump boots, spam the jump button, go fast

**When did the problem start happening**:
I was told of it on March 2nd

**Extra information**:
Gotta go fast

**Comment by LegendWookie** [comment]
I think that's intended

**Comment by Burzah** [comment]
This is an intended feature. WE will not be changing this at this time. Thank you for making a report!
