### ISSUE TITLE
Locking Suit Storage Units Appears to do Nothing.

### ISSUE THREAD

**Issue by VeteranKyl** [ParadiseSS13/Paradise#13081]
**Issue Description**:
Space suit storage units, although can be locked, do not require any kind of ID access to unlock. Essentially, locking a suit storage unit just means you have to unlock it before you can open it, with no access being needed to do the unlocking.

**What did you expect to happen**: 
Suit storage units should have access requirements to them to prevent theft. 

**What happened instead**:
You just open the storage unit and make off with your prize.

**Why is this bad/What are the consequences**:
The suit storage unit, despite being lockable, is NOT a secure place to store anything. The storage unit should be lockable, which would mean that traitors would have to have a method of accessing the storage unit, such as stealing an ID, emmaging, or maybe hacking. Otherwise, you're better 

**Steps to reproduce the problem**:

1. Lock a suit storage unit.
2. Get rid of your ID.
3. Unlock the storage unit.

**Extra information**:
I'm not sure what the intended hacking method is for the storage units, but it should probably be addressed along with the locking issue.

**Comment by TDSSS** [comment]
There is a wire you can pulse to toggle an SSU from secure to not secure and back. Only secure SSUs need access.

Maints/heads did not want SSUs to start off secure as it would make it harder to get things for antags, so all SSUs were made unsecure by default, so this is intended, not a bug.

**Comment by VeteranKyl** [comment]
That's kind of strange, as I'd expect that given the value of the items being stored (especially the CE and captain's suit) they'd want the lockers to be secure by default.

**Comment by AffectedArc07** [comment]
Can confirm this is fixed, as I couldnt use the captains suit storage unit a few weeks ago without access.
