### ISSUE TITLE
Blood Drunk Miner Sprite is too big

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13087]
**Issue Description**:

The Blood Drunk Miner "hitbox" is way too large for it's size and is being treated as a 48x64 mob when its current sprite is 64x64 and shouldn't be that large anyway. Right above the miner is a empty 48x32 area you can click onto that will target the miner despite the miner sprite not being there or even slightly clipping into it. I also noticed the blood drunk miner icon location is for some reason in alienqueen.dmi and I am unsure as to why that is and feel it shouldn't be there at all.

**What did you expect to happen**: 

While this might sound like a minor issue, you can't fight him from above as you will be unable to use any healing items that require you to click yourself as his "hitbox" will layer over yours and prevent you from doing so. The same applies from fighting from his sides as half of his hitbox will layer over yours.

**Why is this bad/What are the consequences**:

Just the fact that the sprite overlays one extra tile that it doesn't need to is pretty bad as it doesn't occupy that tile nor is any of it pixels in it, plus it forces you to fight it directly from below just so you can fight the miner properly.

**Steps to reproduce the problem**:

As far as I know  there's no steps here, only tall and wide miners.

**When did the problem start happening**:

Not sure, found out about it today on 3/6/2020, I would like to assume it been a issue for awhile and no one mentioned it until now.

**Extra information**:

Why is the icon in alienqueen.dmi and not in it's own dmi in the lavaland folder.

**Comment by MrMagolor** [comment]
Can confirm, although this is more of an issue when you get admemed into being a sentient one and can hardly attack without hitting yourself.
