### ISSUE TITLE
Gygax's do not take damage while sprinting.

### ISSUE THREAD

**Issue by Cazdon** [ParadiseSS13/Paradise#13089]
**Issue Description**:
Title.

**What did you expect to happen**: 
For Gygax's to take damage while sprinting as they used to.

**What happened instead**:
They take no damage but still drain battery.

**Why is this bad/What are the consequences**:
Gygax's roaming around at the speed of sound, with places to go, gotta follow their rainbow. With no consequences.

**Steps to reproduce the problem**:
Sprint as Gygax.

**When did the problem start happening**:
A few people said they noticed it changed around the time Universal Object Damage was merged, but I don't know for sure. I've seen it for awhile, forgot to report it, everytime and I'm assuming this isn't intended.

**Comment by farie82** [comment]
https://github.com/ParadiseSS13/Paradise/commit/20c4cf0a088d43f4cd4b8c0a809d9bb53308ef34#diff-a816e5300ca25b3f653f50405875bfa9L331
Removed the take_damage proc
![image](https://user-images.githubusercontent.com/15887760/76166214-33f88800-615d-11ea-971d-768182e2ab9c.png)

Prob on accident

**Comment by matttheficus** [comment]
Fixed by #14195
