### ISSUE TITLE
Revolutionaries game mode instantly ends

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#13095]
It instantly ends when starting
![image](https://user-images.githubusercontent.com/20497797/76172148-16312000-6169-11ea-83c4-62ac8862c144.png)

**Comment by farie82** [comment]
Seems like the revs were dead at the lobby screen. From what I heard in the post round chat

**Comment by Spacemanspark** [comment]
This is the server giving mercy to the playerbase

**Comment by Ty-Omaha** [comment]
I think this happened a long time ago too but a fix was put in?

**Comment by Kyep** [comment]
Not even the server wants to play Rev.

**Comment by Burzah** [comment]
As revolution has been updated recently and there have been no additional reports about this type of behavior occurring, I am going to close this issue. If any other issues occur like this, please feel free to make another report. Thank you for reporting this issue!
