### ISSUE TITLE
Can't ignite plasma sheets with lighter anymore

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#13092]
**Issue Description**:
You can't ignite plasma sheets with lighters, matches, lit cigarettes or candles anymore. Only welders work.

**What did you expect to happen**: 
fiery death

**What happened instead**:
nothing

**Why is this bad/What are the consequences**:
unintuitive how you can't ignite the plasma sheet that way, but can ignite other plasma like the statue for example

**Steps to reproduce the problem**:
use lit lighter on plasma sheets

**When did the problem start happening**:
After the merge of the tools refactor #11700

**Extra information**:
The issue is that the attackby proc of plasma sheets was completely replaced with a welder_attack proc, which means only welders can ignite it anymore.

**Comment by TDSSS** [comment]
@Citinited

**Comment by Citinited** [comment]
I'll include a fix for this in #13092 - should be a simple enough one to do
