### ISSUE TITLE
Spacepods go through teleporters

### ISSUE THREAD

**Issue by Inflectrum** [ParadiseSS13/Paradise#13101]
**Issue Description**:

Spacepods can fit through teleporters. If you drive a spacepod in to a teleporter, the spacepod teleports.

**What did you expect to happen**: 

The spacepod is a large object, two by two tiles, so it feels safe to assume that the pod would not fit through the teleporter. The teleporter is quite small and appears to only be designed to fit human sized objects/people and smaller.

**What happened instead**:

The spacepod went through the teleporter, and ended up inside the station.

**Why is this bad/What are the consequences**:

It can lead to awkward IC scenarios of trying to get a pod out of the station, which can lead to unnecessary confrontation with sec as they try to arrest you in the teleporter room you accidentally got yourself teleported in to.

**Steps to reproduce the problem**:

Have a teleporter set up and ready to go.

Drive a spacepod through it.

**When did the problem start happening**:

Never knew it was possible. This problem occurred only about an hour before I posted this

**Extra information**:

PM me in discord if you need any more information, I have no screenshots unfortunately.

**Comment by Citinited** [comment]
Spacepods can go through all kinds of stuff, disposals chutes is another example of a thing they can use fine. Makes sense if you know how the code works, but counter-intuitive

**Comment by Denthamos** [comment]
My guess is this is due to how space pods work in terms of which tile for the space pod it counts as the pod itself.  Might be related to #12778
