### ISSUE TITLE
You cannot place conveyor belts and their switches

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#13119]
**Issue Description**:

It currently is impossible to place conveyor belts and the switch. Even if your try with a conveyor belt placer. It will shout at you if you don't have any belts in it, but when you have one in it just doesn't work.

**What did you expect to happen**: 

For the conveyor belts and conveyor belt switches to place down on the floor correctly.

**What happened instead**:

It was broken and nothing happened.

**Why is this bad/What are the consequences**:

There are places that use conveyor belts and if those get broken it is currently impossible to replace

**Steps to reproduce the problem**:

1. Get conveyor belts and/or conveyor belt switches.
2. Get a conveyor belt placer.
3. Put your belts in it.
4. Try to put one down.
5. Go cry in a corner when it doesn't work.

**When did the problem start happening**:

Unknown. First time seen it today 2020-03-14
Best guess is since tool behaviour rework.

**Comment by datlo** [comment]
You can currently place belt and switches by hand and they work properly so this is an issue with the conveyor belt placer exclusively. just do by hand as a workaround

**Comment by dovydas12345** [comment]
Oh, I must have been placing them wrong by hand then. Good to know.

**Comment by Citinited** [comment]
I'll take a look later

**Comment by AffectedArc07** [comment]
Cannot reproduce. Feel free to reopen if you find a reliable way to reproduce.
