### ISSUE TITLE
Turn all Humans into monkeys gibs people

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#13137]
The button _Turn all Humans into Monkeys_ gibs people
In the admin secrets verb then OOC Events

It shouldnt gib people because it should turn them into a monkey instead.

**Comment by Shockpoint** [comment]
I was under the impression this only reduced races to their lesser forms, and gibbed those without one.

**Comment by Ridgyaxe** [comment]
It for SURE gibs Vox and golems.

I think it will only gib races that don't have a monkey or related counterpart.

**Comment by Spacemanspark** [comment]
This is intended

**Comment by Sirryan2002** [comment]
not a bug
