### ISSUE TITLE
Runtimes with roburger cyborgification

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#13133]
**Issue Description**:
Found this while testing out #4191. Getting borged with a roburger, inside or outside of a scanner, produces 5 separate runtimes.

**What did you expect to happen**: 
Probably for it not to runtime.

**What happened instead**:
It runtimed.

![dHpnLFItiU](https://user-images.githubusercontent.com/12178527/76894517-4a3ccd00-685c-11ea-8e84-cc79c09a4e58.png)
![eanWGY7a9R](https://user-images.githubusercontent.com/12178527/76894524-4e68ea80-685c-11ea-8ba5-08b20e4a8a08.png)
![njHZJMFEuT](https://user-images.githubusercontent.com/12178527/76894529-5032ae00-685c-11ea-8e81-888cffabce41.png)
![qxshubK0LM](https://user-images.githubusercontent.com/12178527/76894531-5163db00-685c-11ea-8eee-755af691f278.png)
![u4PnDf1kaL](https://user-images.githubusercontent.com/12178527/76894533-532d9e80-685c-11ea-9a72-70f7819e2fe9.png)

**Why is this bad/What are the consequences**:
The borging process itself went flawlessly, everything worked normally. Runtimes probably shouldn't exist though.

**Steps to reproduce the problem**:
1. Consume roburger.
2. Wait.
3. View runtimes when borged.

**When did the problem start happening**:
Unsure

**Extra information**:
Nope.

**Comment by Kyep** [comment]
Can't reproduce this.

**Comment by Mitchs98** [comment]
No longer able to produce runtimes for cyborgification/xenoification inside or outside of machinery. Not sure what fixed the runtimes, but hey less runtimes are good yes? Closing this, as I couldn't reproduce it again after several tests. Though note: Transforming in a body scanner still breaks it, so #13896 will still fix #13132
