### ISSUE TITLE
Graphics issue with pipes

### ISSUE THREAD

**Issue by procdrone** [ParadiseSS13/Paradise#13147]
**Issue Description**:
Pipe sprites behave incorrectly, connections to other pipe lines on T, L and X (and others) connections are not displayed correctly.

![f3d54efe0ae096a442779ba74805dc47](https://user-images.githubusercontent.com/46283583/77039150-a404da80-69b5-11ea-91a2-5392ca13f963.png)

**Why is this bad/What are the consequences**:
Confusion regarding the actual state of pipes

**Steps to reproduce the problem**:
Unknown for now. Happens frequently.

**When did the problem start happening**:
Longer time now. More than a few months.

**Comment by AffectedArc07** [comment]
Fixed this
