### ISSUE TITLE
"Crew Traitor" smite doesn't work correctly

### ISSUE THREAD

**Issue by TheSardele** [ParadiseSS13/Paradise#13149]
**Issue Description**:
The "Crew Traitor" smite causes the person you use it on to get the objective to assassinate themselves, while also creating a random objectiveless traitor.

**What did you expect to happen**: 
For the new traitor to get the objective to assassinate the smited person.

**What happened instead**:
They didn't, and the smited person gained the objective to assassinate themselves.

**Why is this bad/What are the consequences**:
Can't really use the crew traitor smite right now, it's less broken to just manually give someone the assassinate objective.

**Steps to reproduce the problem**:
Smite someone with the "crew traitor" smite.

**When did the problem start happening**:
No idea.

**Extra information**:
Seen it happen twice now, the second time was a traitor round, not sure about the first one.

**Comment by Ty-Omaha** [comment]
https://github.com/ParadiseSS13/Paradise/blob/04ba5c1cc902bf2eada751de7b1b72ebc64ecd86/code/modules/admin/topic.dm#L1975

**Comment by Kyep** [comment]
Having tested this:
- It does create a new traitor
- The new traitor does get traitor status, shows in CA, gets TC, etc
- However, the objective gets given to the victim, not the target.
- Unsure if victim or target get their objectives announced
