### ISSUE TITLE
Carded AIs Can Sometimes Be Limitlessly Tracked On Security Cameras

### ISSUE THREAD

**Issue by Furbnus** [ParadiseSS13/Paradise#13141]
**Issue Description**:
Carded AIs can be sometimes be tracked by security camera consoles as if they were Cyborgs or an AI core and can be followed to any Z-Level, provided they began on Z-Level 1.

**What did you expect to happen**: 
I expected to be unable to see a camera icon from the map screen in the middle of space originating from a carded AI.

**What happened instead**:
I could follow the Intellicard anywhere, including other Z-Levels.

**Why is this bad/What are the consequences**:
This allows security or anyone else with security camera console access to track a carded anywhere on the map without restriction.

**Steps to reproduce the problem**:
AI is carded.
Someone uses camera console.
Enter Map Screen.
Click on camera icon coming from Carded AI.
Follow Carded AI anywhere it goes forever.

**When did the problem start happening**:
First noticed on March 18, 2020.

**Extra information**:
N/A.

**Comment by silverplatedelta** [comment]
with #21443, this has become intended behavior with counter-play (tape the card). Thanks for the report!
