### ISSUE TITLE
Secure Safe doesn't allow you to retrieve any items you put in it.

### ISSUE THREAD

**Issue by Muhdi345** [ParadiseSS13/Paradise#13144]
**Issue Description**:

The Secure Safe (wall safe in captains office) can be interacted with to unlock and lock it. And you can place items into it as normal but retrieving items is impossible by either dragging the safe to your sprite or by clicking the safe with any intent.

**What did you expect to happen**: 

It's an underused item because nobody expects it to be used. But I didn't think it would be THIS secure! You can probably only get the items back by blowing up the safe.

**What happened instead**:

Trying to drag the safe to your sprite result in nothing, but what I did see happen is that my bag or any opened container started acting pretty weird unless I closed and opened it again. Unsure how to explain.

**Why is this bad/What are the consequences**:

Just put all of the captains items into the wall safe, 100% secure unless it's blown up.

**Steps to reproduce the problem**:

Unlock the safe, try to open the safe container.

**When did the problem start happening**:

Unsure

**Extra information**:

**Comment by SteelSlayer** [comment]
This was my fault, but I can fix this easily. Any other information you give on the "bag acting weird" part though?

**Comment by Muhdi345** [comment]
Just that it stacked a new container on top of the one I already had opened. I didn't check how much of it I could manipulate though.

**Comment by BakKeener** [comment]
oh yeah that isn't completely related to the safe, It occurs with other stuff too and it's kinda weird.

**Comment by SteelSlayer** [comment]
Ok good its not my fault :sweat_smile:
