### ISSUE TITLE
Hand Labelers can appear to break janitorial carts

### ISSUE THREAD

**Issue by McGamerson** [ParadiseSS13/Paradise#13148]
**Issue Description**:

https://gyazo.com/0d4815fbb923830e42c2ae18abe570a0

Minor UI Issue but bringing it up anyways as relabeling the janitorial cart makes certain items obstructed. There is both a mop and signs on this cart.

**Why is this bad/What are the consequences**:

Fooled another player into thinking he was locked out of the janicart because I had 'claimed it.' Makes using a labelled cart awkward if you do not know how to fix.

**Steps to reproduce the problem**:

Use a hand labeler with a semi-long label on a janitorial cart (The big yellow lo-tech one).

**Extra information**:

Found out minutes later that this can be fixed manually by rescaling the window horizontally although was fairly confusing for me and the janitor.

**Comment by Henri215** [comment]
Janicarts now use radial menus because of https://github.com/ParadiseSS13/Paradise/pull/22688, making this issue no longer a thing, thank you for reporting.
