### ISSUE TITLE
Runtimes/General fuckery with positronic brains

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#13172]
**Issue Description**:

Runtimes and general fuckery occur with positronic brains if players are requested while you are dead ghosted, and you re-enter your brain.

**What did you expect to happen**: 

To not have people able to take my brain over, as IPC.

**What happened instead**:

People can take over positronic brains (in roles such as Magistrate), if a call for players is sent out.

**Why is this bad/What are the consequences**:

Players accessing karma-locked/high importance jobs whilst looking as if they should be there.
Also causes a client crash.

**Steps to reproduce the problem**:

1) Die as IPC, but do not get gibbed.
2) Vacate your body, as most ghosts do.
3) Remove the positronic brain from the body.
4) Start searching for players by using it in-have.
5) Re-enter brain and wait for player call to complete.

**When did the problem start happening**:

Yesterday is when it occurred to me.

**Extra information**:

There were several runtimes relating to login stuff (For me), but I didn't save any particular ones.

**Comment by Shadow-Quill** [comment]
Note that the repo steps aren't tested.

**Comment by silverplatedelta** [comment]
fixed with #26950. Thanks for the report!
