### ISSUE TITLE
IPCs/robotic limbs can't be self repaired from brute damage with welders

### ISSUE THREAD

**Issue by Sheppysneik** [ParadiseSS13/Paradise#13179]
**Issue Description**:
IPCs and people with robotic limbs can no longer repair minor denting damage on themselves with welders.

**What did you expect to happen**: 
for the brute damage to be gone after welding

**What happened instead**:
the repair sound get played, you get flashed and nothing is repaired

**Why is this bad/What are the consequences**:
ipcs and other people need to ask someone else for minor self repairs

**Steps to reproduce the problem**:
1: receive brute damage on something
2: weld it

**When did the problem start happening**:
today it seems?

**Extra information**:
burn damage can be fixed with cables without problems

**Comment by SteelSlayer** [comment]
I can confirm this is a problem with all progress bar type actions (`do_mob`) performed on a mob which so far includes:
- repairing your own robo limbs
- crowbarring out a robobrain from a borg.

I will look into fixing this.
