### ISSUE TITLE
Possible Shadowling movement bug while using the shadow walk spell

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#13176]
**Issue Description**:

When casting shadow walk you might suddenly lose control of your character and end the spell in a fully-lit place where there may or may not be crew members who will murder you.

**What did you expect to happen**: 

I expected to be able to move around as normal.  I was tased and injured but as far as I'm aware that doesn't affect movement ability during the spell.

**What happened instead**:

Instead I ended up rocketing north from med-maint into the heart of the station and ended up in the dorms/pool area, which was fully lit and had multiple non-thrall crew members.  Hitting "S" or the down arrow key only caused me to stop in place.

**Why is this bad/What are the consequences**:

A shadowling could easily have their round ended - like mine was - by a bug.

**Steps to reproduce the problem**:

Try to shadow walk, possibly while holding one of the movement keys on your keyboard.  Try it while stunned by a taser and having taken some damage.

**When did the problem start happening**:

It worked fine multiple times up to that point in the round.

**Extra information**:

One other shadowling had a similar bug during the same round.

**Comment by farie82** [comment]
Closing since this bug was directly related to shadowlings, which got removed. If this issue occurs with similar spells then please do make a new issue
