### ISSUE TITLE
Unscrewing lava

### ISSUE THREAD

**Issue by VEN0M5** [ParadiseSS13/Paradise#13186]
**Issue Description**:
I can unscrew lava

**What did you expect to happen**: 
Nothing happened

**What happened instead**:
Lava is unscrewed

**Why is this bad/What are the consequences**:
Muh immersion

**Steps to reproduce the problem**:
1. Grab screwdriver
2. Unscrew lava

**When did the problem start happening**:
Just found out about it today

**Extra information**:
![image](https://user-images.githubusercontent.com/15703585/77425899-69b09880-6e0e-11ea-895d-a81e57df9df8.png)

**Comment by Citinited** [comment]
Working as intended™️

**Comment by Ty-Omaha** [comment]
This is how scientists are able to collect data on lava IRL
