### ISSUE TITLE
Plasma cutter displays progressbar when cutting through reinforced walls but does not change the wall

### ISSUE THREAD

**Issue by nok-ko** [ParadiseSS13/Paradise#13197]
**Issue Description**:

The plasma cutter and advanced plasma cutter, when clicking on a reinforced wall, display a progress bar and message saying that some cutting is happening, but at the end of this progress bar, nothing occurs.

**What did you expect to happen**: 

A deconstruction step to happen to the wall.

**What happened instead**:

Nothing happens: you can even perform the same action again and the same progress bar will be displayed, with no consequence.

**Why is this bad/What are the consequences**:

This behaviour is clearly broken, the game shouldn't have bugs 😅 

**Steps to reproduce the problem**:

Equip plasma cutter in any hand. Stand next to reinforced wall. Click on reinforced wall, with any intent. Watch an anticlimactic progress bar.

**When did the problem start happening**:

Ever since plasma cutter wall deconstruction was implemented, PR #11700.

**Extra information**:

I don't think @Citinited actually mentioned this new feature in his original PR. 😠

**Comment by Citinited** [comment]
Haha nah plasma cutters were meant to preserve their old behaviour in tool refactor PR, clearly something went awry though!

I'll fix this in my WIP PR
