### ISSUE TITLE
Wrapping Paper Issue

### ISSUE THREAD

**Issue by EnochArden** [ParadiseSS13/Paradise#13192]
**Issue Description**:

Wrapping paper isn't working on crates

**What did you expect to happen**: 

the crate to be wrapped, so we could send it from cargo.

**What happened instead**:

It only said there wasn't enough paper even though it was a full stack.
**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

use wrapping paper on a crate

**When did the problem start happening**:

**Extra information**:

**Comment by SteelSlayer** [comment]
Confirmed this a bug. I have a PR to fix this in #13189.
