### ISSUE TITLE
Engineering shuttle recall mid flight

### ISSUE THREAD

**Issue by Daylight2** [ParadiseSS13/Paradise#13195]
**Issue Description**:
You can change the destination of the engineering shuttle using the console whilst it's still flying.This restarts the shuttle trip duration. So if, for example, a group of angry sec officers are on the engineering outpost, but you manage to sneak past and launch the shuttle towards the station, you can just be recalled back before arriving. You can also use your own shuttle console to point the shuttle back towards the station, but the angry group of security can call you back again. Repeat ad nauseum. 

**What did you expect to happen**: 
For the shuttle to fly to the station and dock before it can be recalled

**What happened instead**:
Stuck between an endless unsurvivable void and a group of angry sec officers, with only a shuttle console to keep them at bay.

**Why is this bad/What are the consequences**:
Makes it quite hard to escape from the engineering outpost (Or to the engineering outpost, I suppose) whilst someone is chasing you

**Steps to reproduce the problem**:

- go to engineering shuttle

- use console to send shuttle away

- use console to send shuttle back right away

**When did the problem start happening**:
Issue happened on march 25 2020

**Extra information**:
Vampires can shadowstep into the shuttle engines and hitch a free ride, which is nice. Also quite lethal if you're a slime without a spacesuit.

**Comment by BakKeener** [comment]
yeah I was there watching that annoyance and it shouldn't be a thing at all, there should be a cooldown for using the shuttle as well. I also think this can occur with any shuttle console but not tested yet.

**Comment by datlo** [comment]
This is working as intended but I agree that it should be changed.

**Comment by Daylight2** [comment]
Engi shuttle gone, thus not an issue anymore
