### ISSUE TITLE
there's no way to retrieve MMIs from cyborgs.

### ISSUE THREAD

**Issue by Aquilar** [ParadiseSS13/Paradise#13211]
**Issue Description**:

there's no way to retrieve MMIs from cyborgs without blowing them up.

**What did you expect to happen**: 

crowbarring a cyborg to retrieve the MMI

**What happened instead**:

the cyborg was deconstructed and the MMI ceased to exist

**Why is this bad/What are the consequences**:

you need to blow up cyborgs to retrieve MMIs

**Steps to reproduce the problem**:

the expected steps to retrieve an MMI from a cyborg, open them up, expose wires, cut wires, crow bar.

**When did the problem start happening**:

have no idea.

**Extra information**:

a quick look at the code, other than destroy, deconstruct or crowbar act for robots has no coding for moving the MMI out of the mob.

**Comment by VynalDerp** [comment]
Strange. Just yesterday I saw someone take an MMI out of a borg by deconstructing it, and then went on to make that MMI the station's AI to replace the previous one. When did this bug occur? Was there an update or test of an upcoming build or something?
