### ISSUE TITLE
Wingdings broken. (MORE SECRET GREY NERFS)

### ISSUE THREAD

**Issue by LegendWookie** [ParadiseSS13/Paradise#13221]
**Issue Description**:
I can't use wingdings anymore when having it enabled and the speech translator disabled.

**What did you expect to happen**: 
I expected to speak in wingdings.

**What happened instead**:
Graynt says, ""

**Why is this bad/What are the consequences**:
Species feature not working is bad mkay.

**Steps to reproduce the problem**:
I choose wingdings as disability, join, turn off speech translator and talk.

**When did the problem start happening**:
I noticed it today (29.03.2020)

**Extra information**:
My grey setup:
https://i.gyazo.com/5c0db7297eb950bb35b7eb99b7db6479.png

https://i.gyazo.com/ea373ed911eb467db02e2c16b167dd12.png

**Comment by Spacemanspark** [comment]
Banned

**Comment by datlo** [comment]
Cannot reproduce 
![image](https://user-images.githubusercontent.com/22121511/77849076-43ea1180-71c9-11ea-8945-53467fcfc460.png)

Usually when your messages look like that it's because you've been muted by a disability or a chem

**Comment by LegendWookie** [comment]
> Cannot reproduce
> ![image](https://user-images.githubusercontent.com/22121511/77849076-43ea1180-71c9-11ea-8945-53467fcfc460.png)
> 
> Usually when your messages look like that it's because you've been muted by a disability or a chem

Faerie has also already tried this on a test server. This seems to only happen on live. I've tested this with another grey player in the admin test area and we both had the same issue.
