### ISSUE TITLE
mecha voice modification kits can't be applied to mechs

### ISSUE THREAD

**Issue by Sheppysneik** [ParadiseSS13/Paradise#13232]
**Issue Description**:
Mecha voice modification kits won't be installed to mechs

**What did you expect to happen**: 
for the mecha voice modification kits to be installed

**What happened instead**:
by clicking it just displays
![immagine](https://user-images.githubusercontent.com/52687739/78002849-15d70f80-7338-11ea-8a79-afe89c1fa156.png) and nothing is installed

**Why is this bad/What are the consequences**:
muh voices

**Steps to reproduce the problem**:
M.V.M.K. in hand, click on mech

**When did the problem start happening**:
no idea, may be related to the tool refactor?

**Extra information**:
tested on a durand and a gygax

**Comment by datlo** [comment]
Fixed by #13189 (Most likely)
Testing right now
