### ISSUE TITLE
Magical borg equipment search

### ISSUE THREAD

**Issue by procdrone** [ParadiseSS13/Paradise#13239]
**Issue Description**:

After the newest introduction of the ALT+Click to open various boxes and inventories, borgs received the same blessing and can check out inventories using the same shortcut

**What did you expect to happen**: 

For inventory to not open.

**What happened instead**:

Inventory is displayed to the borg.

**Why is this bad/What are the consequences**:

Balance, and consistency,

**Steps to reproduce the problem**:

1.Be a cyborg.
2. Find any bag or box, or any type of container.
3. Alt click it

**When did the problem start happening**:

Noticed it today (02/04/2020), however I am sure it exists since the alt click update.

**Comment by nok-ko** [comment]
Can borgs detonate mousetrap bombs with this?

**Comment by Spacemanspark** [comment]
...Im fairly sure this is intentional?
