### ISSUE TITLE
Devils cant respawn after being cremated

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#13236]
**Issue Description**:
Devils can be cremated

**What did you expect to happen**: 
The only way to kill a devil should be to use the librarian codex and find their weakness instead of just cremating them

**What happened instead**:
They were just cremated

**Why is this bad/What are the consequences**:
It defeats the purpose of having the codex and the game mode

**Comment by SabreML** [comment]
Devils got nuked by #15672, so no longer an issue.
