### ISSUE TITLE
Colorful Crashing Blood

### ISSUE THREAD

**Issue by LegendWookie** [ParadiseSS13/Paradise#13242]
**Issue Description**:
Drinking colorful reagent will recolor your blood but when you then examine said blood while it's on the ground it lags your games and sometimes almost crashes it.

**What did you expect to happen**: 
Regular blood but with colors.

**What happened instead**:
Regular blood with colors and crashes.

**Why is this bad/What are the consequences**:
Crashes bad m'kay?

**Steps to reproduce the problem**:
1. drink colorful reagent 
2. bleed

**When did the problem start happening**:
02.04.2020

**Extra information**:
Vox can't love

**Comment by Citinited** [comment]
Probably related to #13000
