### ISSUE TITLE
Use disposals to go through shutters

### ISSUE THREAD

**Issue by LegendWookie** [ParadiseSS13/Paradise#13249]
**Issue Description**:
If you place a disposals trunk infront of shutters and disposals anything in it, it will go through the shutters.

**What did you expect to happen**: 
I expected to bump against the shutters.

**What happened instead**:
I phased through the shutters instead of bashing against it.

**Why is this bad/What are the consequences**:
Skipping sections in T-Spiders Gateway.
Phasing into the HoP office through the shutters.

**Steps to reproduce the problem**:
1. Place a disposals trunk aiming at the shutters directly infront of it.
2. Place a disposals chute or something similar to that on top of it or leading to it via pipes.
3. Disposals yourself.

**When did the problem start happening**:
I've noticed it a few months ago but apparently forgot to write a bug report.

**Extra information**:
Vox can't love.

**Comment by farie82** [comment]
Can also do this with airlocks. Just not with walls
