### ISSUE TITLE
Being able to repair wooden barricades with a welder

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13259]
**Issue Description**:

As stated in the title, You shouldn't be able to fix something made of wood with a welder.

**What did you expect to happen**: 

I expected to be able to damage it on help intent.

**What happened instead**:

I was on help intent trying to break it since we can't deconstruct them at the moment as stated in Issue #12790 and instead I got the message for attempting to repair it as well as being blinded.

**Why is this bad/What are the consequences**:

You shouldn't be able to repair a object made of wood with a welder.

**Steps to reproduce the problem**:

Step 1. Have Lit welder on help intent.
Step 2. Use said welder on wooden barricade.
Step 3. Attempting to Repair wooden barricade.
Step 4. Get blinded for not having welding protection.

**When did the problem start happening**:

I found out about it a week ago I think, not sure when this became a issue however.

**Comment by Spacemanspark** [comment]
bluespace
