### ISSUE TITLE
Taking apart a chem dispenser doesn't drop a powercell

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#13254]
**Issue Description**:
When you disassemble a chem dispenser, it drops all stock parts, except the power cell

**What did you expect to happen**: 
The cell to drop with everything else

**What happened instead**:
No cell was dropped

**Why is this bad/What are the consequences**:
Every time you take a chem dispenser apart you lose a cell

**Steps to reproduce the problem**:
Take apart a chem dispenser

**When did the problem start happening**:
Probably when chem dispensers and portable chem dispensers were merged

**Extra information**:
N/A

**Comment by BryanPara** [comment]
I was attempting to recreate this on an earlier build, not sure how far behind the current, and it dropped the cell, so the issue is occurring at least within the last month or so of merging something that touched chem dispensers.
