### ISSUE TITLE
Unable to apply wrench to filing cabinet

### ISSUE THREAD

**Issue by blinkdog** [ParadiseSS13/Paradise#13251]
**Issue Description**:
While in the IAA office, wanted to apply a wrench to the filing cabinet, either to make it movable or deconstruct it to remove it as an obstacle. This didn't work.

**What did you expect to happen**: 
I thought I would apply the wrench and the cabinet would either be movable or deconstructed.

**What happened instead**:
The message "You begin to wrench the filing cabinet." appeared, but no progress bar appeared and nothing happened. I also handed the wrench to another player, who experienced the same bug.

**Why is this bad/What are the consequences**:
Filing cabinets are neither movable nor deconstructable, at least in the standard expected way.

**Steps to reproduce the problem**:
* Attempt to apply wrench to filing cabinet
* See message
* Do not see progress bar or any change in the game

**When did the problem start happening**:
This is the first time I've attempted to wrench a filing cabinet.

**Extra information**:
I think the filing cabinet in the IAA office has a bunch of crew contracts in it; could that be why movement/deconstruction did not work?

**Comment by Citinited** [comment]
It's not anything I've touched but I'll include a fix in my WIP tools PR.

I think this has been an issue forever

**Comment by SabreML** [comment]
Fixed by #14616.
Forgot to add it in the PR, whoops!
