### ISSUE TITLE
Disassembling a live positronic brain will break their client

### ISSUE THREAD

**Issue by Tinnydave23** [ParadiseSS13/Paradise#13263]
**Issue Description**:
When an IPCs positronic brain is disassembled in R&D the IPC will experience a permanent black screen, even as a ghost.

**What did you expect to happen**: 
I expected being dissembled to be similar to cremated in the sense that without a body I would just become a regular ghost.

**What happened instead**:
My client screen went completely black, chat could still be read showing that I was a ghost but for the rest of the round I had just a black screen to look at.

**Why is this bad/What are the consequences**:
In my opinion its game breaking for the person who has had this happen to them and it really kills the motivation to keep playing the round when you literally can't see anything.

**Steps to reproduce the problem**:
Get a conscious IPC positronic brain and disassemble it in R&D. 

**When did the problem start happening**:
Happened during a raging wizard round, I was a wizard and after being destroyed instead of being borged security took my positronic brain to R&D and had the AI destroy it.

**Extra information**:

**Comment by farie82** [comment]
Good first issue.
The player is not made into a ghost when the brain is destroyed.

**Comment by Shockpoint** [comment]
This is a result of the player being sent to nullspace, actually. Any admin can teleport you out of nullspace if you ask.
Although, why it sends you there, I'll never know. This did happen before when russian revolvers would fire hard enough to send IPC brains to nullspace as well, so it may have something to do with how the posibrain is handled.

**Comment by taukausanake** [comment]
> russian revolvers would fire hard enough

I really wish that was a feature, or turned into one. Fire hard enough to send your soul someplace else

**Comment by SteelSlayer** [comment]
I'm unable to reproduce this. When a robobrain, posibrain or MMI get deleted, it makes a call to destroy the brainmob inside of the item, which calls `ghostize()`. I tested this with deconstructing a possessed brain in the destructive analyzer, and also just admin deleting the brain. Both made me a brain ghost.

**Comment by Tinnydave23** [comment]
Odd, it's possible it was just a one time glitch that happened or happens very rarely.
