### ISSUE TITLE
Aghost makes your inventory invisible

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#13269]
**Issue Description**:
Aghosting out of your body, then returning, makes your inventory icons disappear.

**What did you expect to happen**: 
Inventory shows up as normal.

**What happened instead**:
Upon re-entering my body after aghosting, everything I was wearing (gloves, headset, shoes, uniform, etc) was invisible in my inventory pane. It was still there. I could still remove and re-add it. But it was invisible.

**Why is this bad/What are the consequences**:
Makes it a nightmare for admins to manage what they are wearing because after every aghost+reentry into their body, they have to remove everything they're wearing and re-wear it, just so it shows up.

**Steps to reproduce the problem**:
1. Be an admin.
2. Use 'aghost' under admin verbs
3. Do some stuff
4. Use 'aghost' again to re-enter your body
5. Observe that your inventory is now invisible

**When did the problem start happening**:
Within the last year, not sure when. Very annoying.

**Extra information**:
Unsure the exact trigger, but it happens a LOT. (to me at least)

**Comment by datlo** [comment]
I believe that closing and reopening the inventory panel with the button in bottom left fixes this bug, if its the one I get sometimes. Still annoying and should be fixed, obviously.

**Comment by farie82** [comment]
Happens to normal players as well at random it seems. Good to have a repro though.

**Comment by Kyep** [comment]
Rejuv fixes it.
So does "update mob sprites".
Be good if it just never happened in the first place, though.

**Comment by farie82** [comment]
Prob related to #11538
