### ISSUE TITLE
Can't debug subsystems by clicking them in the MC tab

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#13260]
**Issue Description**:

@AffectedArc07 
After #13182 was merged, you can't debug subsystems by clicking them in the MC tab. 
Reverting line 184 in `subsystems.dm` to what it previously was, fixes this issue.

**What did you expect to happen**: 
To debug a subsystem.

**What happened instead**:
They became un-clickable.

**Steps to reproduce the problem**:
Go to the MC tab, try to debug a subsystem by clicking on it.

**Comment by AffectedArc07** [comment]
Ah shit
