### ISSUE TITLE
Return to lobby antag bug

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#1327]
Apparently #1268 didn't totally fix #1235. I rolled cultist and was returned to the lobby. I didn't have a high preference job selected, and had very few on low/medium, so that may have caused it.

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
:rage:
No clue how that's happening, it should just toss people into a random roll.

**Comment by veganzombeh** [comment]
Cultists aren't given a special_role that I can see until post_setup, by which point I think job assignment has already been handled.

**Comment by tigercat2000** [comment]
@veganzombeh ... that's great

**Comment by veganzombeh** [comment]
Just checked, looks like this affects cultists, changelings and vampires.
