### ISSUE TITLE
Donk pockets with ants on them can't be reheated.

### ISSUE THREAD

**Issue by ungauss** [ParadiseSS13/Paradise#13272]
When a donk pocket gets ants on it, it cannot be reheated in a microwave since it contains "components unsuitable for cooking".

**What did you expect to happen**: 
The donk pocket is reheated and either the ants remain, disappear or become "burned" ants.

**What happened instead**:
Doesn't work.

**Why is this bad/What are the consequences**:
Donk pockets are unusable until ants are removed. Doesn't make sense why you can't reheat a donk pocket with ants on it.

**Steps to reproduce the problem**:
Try to microwave a donk pocket with ants.

**When did the problem start happening**:
Since the ants PR.

**Comment by taukausanake** [comment]
Maybe need a way to remove the ants from food? That might be a good solution. That or just don't let ants get to your food. Normally that's a deal breaker for food in real life

**Comment by matttheficus** [comment]
Would likely need to re-code the cooking tools to fix this as it cooks based on reagent amounts and ants are actually a reagent.

**Comment by Henri215** [comment]
I could reheat infested donk pockets, destroying ants in the process.

**Comment by DGamerL** [comment]
I also tested it, and I could reheat cold donk pockets with ants just fine. This was most likely fixed via #20453. If it happens again, feel free to open a new issue report!
