### ISSUE TITLE
Nicotine withdrawls occur while smoking.

### ISSUE THREAD

**Issue by ungauss** [ParadiseSS13/Paradise#13273]
A player addicted to nicotine can receive withdrawl messages and negative effects while they are smoking.

**What did you expect to happen**: 
Nicotine cravings wouldn't occur while I'm smoking - since I'm currently receiving nicotine. Slowness and headache messages wouldn't happen with a cigar in mouth.

**What happened instead**:
An addicted player goes into withdrawl while smoking. It seems the cigarrettes don't deliver enough nicotine or dose fast enough to keep withdrawl away.

**Why is this bad/What are the consequences**:
This doesn't make sense, real-life smokers don't crave a cigarette while smoking a cigarette. In gameplay terms, it also makes it impossible to stop withdrawl effects by smoking (forcing you to cure the addiction).

**Steps to reproduce the problem**:
Become addicted to nicotine. Smoke. Observe withdrawl occurs while constantly smoking.

**When did the problem start happening**:
This is likely related to the addiction rework. This didn't use to happen last time I tried smoking in-game (~6 months ago).

**Comment by farie82** [comment]
Fixed in #13181

**Comment by AffectedArc07** [comment]
Fixed
