### ISSUE TITLE
You can't remove wooden barricades using a crowbar

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#13288]
**Issue Description**:

You no longer can remove wooden barricades using a crowbar.

**What did you expect to happen**: 

To be able to remove the barricade without having to hit it until it breaks.

**What happened instead**:

You can't remove barricades without bashing them down.

**Why is this bad/What are the consequences**:

You used to be able to remove barricades using a crowbar, which is why I believe this is not intended behaviour.

**Steps to reproduce the problem**:

1. Spawn in a wooden barricade and a crowbar.
2. Try to remove it using help intent with the crowbar.
3. Cry when it hits the barricade.

**When did the problem start happening**:

My best guess it started happening when tool refactor PR was merged.

**Comment by Sheppysneik** [comment]
Seems like a duplicate of #12790

**Comment by taukausanake** [comment]
I thought you had to screwdriver the barricade first and then you could crowbar it? Was that changed?
