### ISSUE TITLE
Carbon animals (Monkey, Stok, etc) can't gain nutrition

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#13296]
**Issue Description**:

Feeding monkeys or other unevolved carbon animals doesn't make their nutrition levels go up.

**What did you expect to happen**: 

Feed animals should gain nutrition.

**What happened instead**:

They remain malnourished and eventually suffer from hypolgycemia.

**Why is this bad/What are the consequences**:

PunPun dead bad.

**Steps to reproduce the problem**:

- Simply stay in the round for long enough to have animals' nutrition levels drop under 100.
- Alternatively, varedit said nutrition.
- Feed monkey and watch nutrition not go up

**When did the problem start happening**:

I actually remember this happening for as long as I've been playing (so, years?), but it has never really been much of an issue until the hypoglycemia PR was added, as now low nutrition can kill.

It is probably a concern for borers using monkeys as hosts, but I don't know if borer-controlled monkeys are also unable to gain nutrition.

**Extra information**:

**Comment by SteelSlayer** [comment]
Related to #13001 and technically a duplicate of #4345, very old issue.
