### ISSUE TITLE
Wizard hardsuit not coldproof

### ISSUE THREAD

**Issue by Daylight2** [ParadiseSS13/Paradise#13299]
**Issue Description**:
The wizard hardsuit (aka Battlemage Armor), although being pressure proof, still exposes the user to the freezing cold of space.

**What did you expect to happen**: 
Not to freeze to death whilst wearing a hardsuit

**What happened instead**:
Slowly froze to death

**Why is this bad/What are the consequences**:
Misleads players, and reduces the viabilaty of the hardsuit

**Steps to reproduce the problem**:

- Buy battlemage armor

- Go to spess

- Freeze, criminal scum!

**Comment by datlo** [comment]
This is working as intended. Not a bug.

**Comment by daylight2** [comment]
Huh. Why is it spaceproof then?

**Comment by TDSSS** [comment]
see #13099 and #13100

**Comment by daylight2** [comment]
> see #13099 and #13100

Neither of those explain *why* the armor is pressure proof but not coldproof, just clarify that it's intended.

**Comment by nok-ko** [comment]
^^ yeah, what the heck?

**Comment by TDSSS** [comment]
Check the PR where it was added, then. If I recall correctly it was to encourage wizards to stay on station rather than hiding in space.
