### ISSUE TITLE
/nodecon variant of plasteel/titanium walls are deconstructable

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#13304]
**Issue Description**:
You are able to deconstruct variants of walls that are not supposed to be able to be deconstructable.  Example of this being the derelict walls.

**What did you expect to happen**: 
It allows player to bypass hard restrictions put into place in such space ruins and hampers the ability to modify shuttles without them being able to be nodecon.

**What happened instead**:
Players deconned the derelict walls with a welder.

**Why is this bad/What are the consequences**:
It is not the intentional purpose of the walls allows players to skip challenges required to get loot.

**Steps to reproduce the problem**:
Place down the /nodecon walls and you can deconstruct them/go to the derelict.

**When did the problem start happening**:
I noticed recently, may has been a thing for a few months now because the players that were doing this without reporting it knew exactly what to do and where to go in order to bypass everything.

**Comment by datlo** [comment]
This is most likely caused by tool refactor.
