### ISSUE TITLE
Speed stacking from meth/nuka cola and such sources.

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#13314]
**Issue Description**:
Chemicals such as Nuka Cola, Meth, Ultra Lube are stacking upon each other to reach old meth levels of speed.

**What did you expect to happen**: 
For only one speed buff to apply to the character.

**What happened instead**:
The chems involved were stacking giving players old meth levels of speed.

**Why is this bad/What are the consequences**:
The combo gives the player using it a near un-counterable advantage due to how fast they are able to move like old meth speeds, plus the stun resistance.  This speed bonus was nerfed in pr #9259 and it feels like this was an oversight since the speed bonus was nerfed for a good reason.

**Steps to reproduce the problem**:
Combine nuka cola and meth together in an organic mob, old levels of meth speed combined with the stun resistance.

**When did the problem start happening**:
After #9259

**Comment by Kyep** [comment]
@AffectedArc07 
This issue can be closed. Meth, Nuka Cola, Stims and Ultra Lube no longer stack, as they all use the same GOTTAGOFAST flag.
