### ISSUE TITLE
Mechs can be spam repaired.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#13316]
**Issue Description**:
Mechs can be spam repaired by queuing up repair actions infinitely.

**What did you expect to happen**: 
As of https://github.com/ParadiseSS13/Paradise/pull/10051 mechs were no longer supposed to be able to be repaired this fast and have a 1.5 second timer in-between repairs.

**What happened instead**:
You could repair mechs way too fast.

**Why is this bad/What are the consequences**:
The balance for mechs that was much needed is currently broken, making mechs more overpowered than they need be.

**Steps to reproduce the problem**:
1. Pew mech.
2. Try to repair mech multiple times at once.
3. It just works.

**When did the problem start happening**:
Unsure. Likely either the tool refactor or Steel's refactor that broke some things to do with tools.

**Extra information**:
Boopeth.

**Comment by SteelSlayer** [comment]
After a bit of research I *think* this is related to the tool refactor. All tool usage goes through the `/obj/item/proc/use_tool` proc. But, inside this proc, there's no support for doing `do_after_once()`, and in #10051, `do_after_once()` was used to limit repair spam.

**Comment by SteelSlayer** [comment]
This can probably be closed now that #13633 is merged.

**Comment by AffectedArc07** [comment]
Fixed
