### ISSUE TITLE
Blast Doors Can Now Be Destroyed

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#13319]
**Issue Description**:
Blast doors are meant to be indestructible but are now vulnerable to destruction from numerous sources of damage

**What did you expect to happen**: 
For blast doors to not be breakable by things

**What happened instead**:
Blast doors have been broken on numerous occasions when they're not intended to be

**Why is this bad/What are the consequences**:
This was likely an unintended change when object damage was merged, this means that crew who somehow get to say CC can get into locations if they happen to have powerful enough explosives

**Steps to reproduce the problem**:
Get a high damage weapon like the mining laser for space pods or powerful explosives like syndie bombs then use them on the blast door

**When did the problem start happening**:
Probably when object damage was merged because as far as I know, blast doors were indestructible prior to the PR

**Extra information**:

**Comment by nok-ko** [comment]
This is, to my knowledge, intended behaviour.

**Comment by Leanfrog** [comment]
Seems like this is in fact intended except for the pod mining laser which has now been marked in a separate report
