### ISSUE TITLE
Unable to link separate Telecommunication machines.

### ISSUE THREAD

**Issue by garrulousTeamotei** [ParadiseSS13/Paradise#13312]
**Issue Description**:

Unable to link any two separate telecommunication machines. Machines tested were Receiver, bus, processor, server, and relay. Hub was not tested. Test occurred on Delta Station via Ghost role. Error may be tied to specific z level.

**What did you expect to happen**: 

Telecommunication machines would link, allowing a functional 1 z level telecomms.

**What happened instead**:

Machines did not link. No connections were shown under 'Linked Network Entities:'

**Why is this bad/What are the consequences**:

Prevents a method of communication from being set up on Delta. If this effects machines outside the Delta Station Z level, sabotage or damage to machines may result in permanent cessation of communications.

**Steps to reproduce the problem**:

Spawn as Old Cryogenics Ghost Role. Create one Receiver, bus, processor, server, hub. Attempt connection via multitool

**When did the problem start happening**:

Seen on 4/17/2020

**Extra information**:

**Comment by AffectedArc07** [comment]
I think this broke during dreamchecker, ill take a look now
