### ISSUE TITLE
cryosleep kills people

### ISSUE THREAD

**Issue by realtaac** [ParadiseSS13/Paradise#13327]
**Issue Description**:

when people go into cryo to log off or ghost there is a chance they pop out of cryo as a corpse

**What did you expect to happen**: 
Cryo and ghost and have your body moved to storage

**What happened instead**:
body spawns on top of cryopod as a corpse with the SSD logo above their head but if you examine them they are dead

**Why is this bad/What are the consequences**:
it causes more corpses to be around than normal

**Steps to reproduce the problem**:
When people go to cryo after a while they have a chance of being a corpse, unknown of the situation before they cryo

**Comment by Mitchs98** [comment]
Are you positive they weren't dying/had internals on/any other situation that would normally cause someone to die before entering cryo? Any other information?

**Comment by realtaac** [comment]
I'm pretty sure they did not have internals on, no clue if they were dying but they had 0 brute and burn damage and 100% blood so..

**Comment by realtaac** [comment]
thinking about it they may have starved to death, still they should be moved to cryo storage before starving, closing issue

**Comment by TDSSS** [comment]
but...you can't actually starve to death, you'll just be annoyingly slow.

**Comment by Mitchs98** [comment]
You can starve to death, actually. Hypoglycemia can put you into crit shock which can cascade into further crit stages. #13098
