### ISSUE TITLE
Pod Mining Lasers Can Damage Blast Doors

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#13320]
**Issue Description**:
Pod mining lasers can damage and destroy blast doors despite doing roughly 50 damage when blast doors have a damage deflection of 70

**What did you expect to happen**: 
For blast doors to not be breakable so easily

**What happened instead**:
The blast door was easily destroyed by a pod mining laser

**Why is this bad/What are the consequences**:
The mining laser is ignoring the damage deflection meant to prevent simple things from breaking them

**Steps to reproduce the problem**:
Apply a mining laser to a space pod, shoot blast door with mining laser, watch it break after several shots

**When did the problem start happening**:
No clue, probably thanks to the mess of code that are space pods

**Extra information**:

**Comment by nok-ko** [comment]
Wait, space pods can have mining lasers?!

**Comment by Leanfrog** [comment]
It's techincally a KA but internally and the weapon itself is marked as a mining laser

**Comment by Leanfrog** [comment]
Okay, turns out that damage deflection only affects melee weapons closing for that reason
