### ISSUE TITLE
Morgue trays float away while in no gravity

### ISSUE THREAD

**Issue by PidgeyThePirate** [ParadiseSS13/Paradise#13337]
**Issue Description**:
In no gravity, opening a morgue tray causes the tray to float off into the wild blue yonder. It teleports back inside the tray holder when you click on it again.

**What did you expect to happen**: 
The tray stays put under any gravity when opened.

**What happened instead**:
It floated away.

**Why is this bad/What are the consequences**:
Can make using morgue trays annoying in low gravity as they float away from the bodies.

**Steps to reproduce the problem**:
- gravgen off
- open tray

**When did the problem start happening**:
Not recently I'd imagine.

**Comment by taukausanake** [comment]
Duplicate of #2540. Not a bug, working as intended. Might be worth another look at though

**Comment by PidgeyThePirate** [comment]
Huh. Well there you go.
