### ISSUE TITLE
Initropidril does not properly apply when applied with liquid contents in botany

### ISSUE THREAD

**Issue by Alantodne** [ParadiseSS13/Paradise#13333]
**Issue Description**:
Initropidril does not properly apply when applied with liquid contents in botany

**What did you expect to happen**: 
In botany, When using omega weed as the base, adding nicotine and morphine to it, along with liquid contents and also separated chems, along with having 100 potency. I thought throwing this would apply Initropidril along with any not 'mixed' chemicals. However it doesnt. When you place the same plant into a grinder and grind it up, it produces Initropidril.

**What happened instead**:
It is applying all non mixed chems. and doesnt apply Initropidril. It does apply mercury, hairgrowium, itching powder, and histamine properly. It also seems to not have ANY Initropidril related ingredients too. 

**Why is this bad/What are the consequences**:
It reduces the power that tator botanists could have as they can not produce Initropidril and distribute it via their plants.

**Steps to reproduce the problem**:
get omega weed, get reishi, get space tobaco. Extract morphine and nicotine. apply both to the omaga weed. Also apply liquid contents(Trait from tomatoes) and separated chems(Trait from glowberries). Apply saltpeter to the plant to make it potency 100. and then throw said plant at victim. I used a upgraded health analyzer to see which chems were in the monkey system.  

**When did the problem start happening**:
Not sure, only tested it recently as I only had the chance recently.

**Extra information**:

**Comment by nok-ko** [comment]
**Separated Chemicals** makes the chemicals in the plant not react until the plant is squashed. This is working as intended.

**Comment by Fox-McCloud** [comment]
separated chemicals, as pointed out, prevents mixing; that said, even if you didn't have it, this wouldn't be enough; splashing only applies `TOUCH` based reactions.
