### ISSUE TITLE
Sentience event harm intent malfunctions

### ISSUE THREAD

**Issue by lolzyking** [ParadiseSS13/Paradise#13345]
Certain simple mobs when granted sentience from the Sentience random event cannot properly use harm intent and make use of their increased damage for self defense, Such as mice,

**What did you expect to happen**: To be able to nibble them

Because other simple mobs such as parrots, lizards, corgis, cats, foxes, all gain the ability to properly use harm intent

**What happened instead**:

I nuzzled them, harmlessly, also wasn't able to harm objects either.

**Why is this bad/What are the consequences**:

Because I would not be able to defend myself

**Steps to reproduce the problem**:

accept a sentience event, awaken as a mouse.

**When did the problem start happening**:
 always I believe.

**Extra information**:

I think it has something to do with some simple mobs have specific verbage for their interactions, Like nuzzle on mice, not the same bug but I think it might be a similar bug in the attack verbage that baby slimes have when sentient as they cannot attack objects either.

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/13020

It's working as intended. IT no longer boosts the damage of simple mobs.
