### ISSUE TITLE
Bubblegums charge deals twice as much damage as intended.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13349]
**Issue Description**:

Bubblegum's charge is supposed to deal 30 armor piercing brute each time it hits a player.
However, without fail, any mob hit by Bubblegum's charge is hit twice, causing them to take 60 damage, twice as much as expected.

**What did you expect to happen**: 

For getting hit by a charge doing only 30 damage .

**What happened instead**:

you always get hit twice, taking 60 damage. 

**Why is this bad/What are the consequences**:

The charge attack, which is already nigh impossible to avoid without speed chemicals, twice as deadly as intended.

**Steps to reproduce the problem**:

Take control of bubblegum, or throw a humanized monkey at it.
Note that each time the charge hits a person, the attack log is generated twice, and they take 60 damage instead of 30.

**Comment by Henri215** [comment]
fixed by https://github.com/ParadiseSS13/Paradise/pull/18837

**Comment by Henri215** [comment]
Like Henri from the past said, it was fixed by PR #18837.
