### ISSUE TITLE
Automatic Crew Transfer has higher priority over Shuttle Delay abilities/items

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13352]
**Issue Description**:

As stated in the title, If the automatic crew transfer vote goes through while cult/shadowlings delays the shuttle call above 5 minutes, it'll go over it and speed up the shuttle.

**What did you expect to happen**: 

It's a very rare issue that may not happen for months at a time or maybe even years, but I feel this is just a oversight in the code that didn't take into account for something like this happening. It is however something that can happen and could screw a cult over who needed just a bit more time.

**What happened instead**:

I expected the crew transfer vote to not do anything as I seen shuttle calls made before it and it wouldn't do anything if it was below 5 minutes.

**Why is this bad/What are the consequences**:

This will mostly affect cultists as they might need those few extra minutes to finish a summon. I seen them try to create the 3x3 rune while shuttle is in transit and because they didn't have enough time just flat out lose.

**Steps to reproduce the problem**:

1. Delay shuttle call with cursed orb/shadowling ability.
2. Allow automatic crew transfer to happen.
3. Shuttle timer is reset to 5 minutes ETA.
**When did the problem start happening**:

Most likely a oversight and been in the code since the beginning.

**Comment by Kyep** [comment]
I'd rather crew vote shuttle calls (which are the result of an OOC player vote) take priority over IC stuff like cursed orb/etc.

**Comment by farie82** [comment]
The described behaviour still holds for the cult shuttle delay item. The sling shuttle delay ability has been removed.

**Comment by silverplatedelta** [comment]
After consulting the heads, this has been ruled intended behavior. The sound should end promptly when voted for by the players. Thanks for the report!
