### ISSUE TITLE
Highlight words bugs out when examining thing with said word in the Name

### ISSUE THREAD

**Issue by Blonkz** [ParadiseSS13/Paradise#13365]
**Issue Description**: Highlight words bugs out when examining thing with said word in the Name

I have hightlighted the word "atmos" (without " "). Everytime I examine someone wearing an atmospherics jumpsuit I get a long string of letters starting with src="data:image..."

**What did you expect to happen**:  I examined a person wearing an atmos jumpsuit

I expected to see the symbol of the atmospheric thechicians jumpsuit and not some weird long line of text.

**What happened instead**:

Example of examining an assistant wearing a atmospheric technicians jumpsuit:

This is Orchid Of The Stars, a diona!
He is wearing atmos" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAPFBMVEXAwMCWcgDGlgCrq6vMmwDZ2dn/2wIAbZEAlMEAqf+MjIxUVFRra2vDlQADTmY8PDyBgYHAwMCnfwB8XQBGIXzjAAAAAXRSTlMAQObYZgAAAGR6VFh0RGVzY3JpcHRpb24AAHicU1ZwcnX39FNw8fXkKkstKs7Mz1OwVTDRM+DiLM9MKckAcoyNuDgzUjPTM0ognOKSxJJUIFNJiYszJbOoGMg05OJMK0rMTYWwlRVc/VzAJgIAmrcYC32rgUMAAACESURBVDiN7dDLDsQgCAVQwApSH+3o///rQJcTWc22NyEu7gkmALz5DRKllIgw6o8Dc8r+BICZMCMx74EUdmE9F9kCdXGyatEAiIFqQPYAxEGzkX3vO1SbTdSD9GcDhQukdwNE0Rfjqu3+3K1eIwAy5yQbCYHdEO2eEYCxFk5cK+rf/JUvKBYEicXF9J4AAAAASUVORK5CYII="> a blood-stained atmospheric technician's jumpsuit!
He is wearing  a blood-stained hair flower pin on his head!
He has  a leather satchel on his back.
He has blood-stained hands!
He has  a tool-belt about his waist.
He is wearing  some blood-stained work boots on his feet!
He has  an engineering radio headset on his left ear.
He is wearing  Orchid Of The Stars's ID Card (Civilian).
He is limp and unresponsive; there are no signs of life...
He has severe bruising!
He has severe burns!
He is bleeding!

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

Set hightlight string to "atmos" without (" ")
I have set regex to: on

**When did the problem start happening**:
Constantly, always

**Extra information**:

**Comment by tinfoiltophat** [comment]
Can confirm. I was wondering what was causing this, didn't realize that it was because of the highlighting until you mentioned it.

**Comment by Shendow** [comment]
I doubt this is fixable because the regex is applied on the HTML code (as opposed to the text you see), so it ends up replacing text that was there for the HTML formatting, breaking it. I'll try thinking of a solution for this.
