### ISSUE TITLE
While being in a vehicle you can be hit twice by the same projectile.

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13377]
**Issue Description**:

As stated in the title you can be hit twice by the same projectile in a vehicle.

**What did you expect to happen**: 

Only be hit once.

**What happened instead**:

I got hit twice by the same projectile.

**Why is this bad/What are the consequences**:

If you are riding a vehicle, you shouldn't be forced to take two hits from a single projectile. I discovered this when being shot by disablers and it would be much worse if I were to be hit by buckshot, slugs or even 357., which would drop me very quickly if not instantly.

**Steps to reproduce the problem**:

Step 1. Step into a vehicle.
Step 2. Get shot while moving towards or standing still in said vehicle.
Step 3. Receive two attack procs from a single projectile.
Step 4. Cry because you received double the damage.

**When did the problem start happening**:

No idea once again since I bet it been around for a long time and noone noticed it due to the only people using vehicles if the janitor and paramedic.

**Extra information**:

I think it procs from moving forward towards a projectile while in a vehicle.

**Comment by Sirryan2002** [comment]
no longer an issue, believe it was fixed in a refactor
