### ISSUE TITLE
Grenades not mixing Fluorosurfactant and Water. Causing damage instead

### ISSUE THREAD

**Issue by aviseu** [ParadiseSS13/Paradise#13372]
**Issue Description**:
Cleaning grenades are bugged. They explode.

**What did you expect to happen**: 
Cleaning grenades to release the foam and clean the tiles it touches.

**What happened instead**:
1. Fluorosurfactant mixed with water works when mixed in a beaker.
2. Grenades do not seem to mix Fluorosurfactant with Water.
3. Grenade will explode, dealing damage mostly on head and upper body. Water will be spread on the floor causing people to slip.

**Why is this bad/What are the consequences**:
Cleaning grenades are now able to damage crew and do not do their function.

**Steps to reproduce the problem**:
1. Make grenade casing
2. Wire it
3. Add beaker with 40 Fluorosurfactant and 10 Space Cleaner
4. Add beaker with 40 Water and 10 Space Cleaner
5. Finish grenade
6. Activate and throw grenade.

Alternative: ask janitor to use one of their grenades

**When did the problem start happening**:
I noticed it first today. May 3rd 2020

**Extra information**:
-

**Comment by nok-ko** [comment]
I'm pretty the damage is because grenade casings heat up the contents of the beakers enough to cause damage. Not sure exactly why cleaner doesn't work... I will point out that smoke grenades with space cleaner are better than fluorosurfactant grenades.
