### ISSUE TITLE
Swarmers show up twice on the orbit menu

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13376]
**Issue Description**:

Each swarmer shows up twice on the orbit menu for some reason

**What did you expect to happen**: 

Each swarmer to show up once on the menu

**What happened instead**:

Each one shows up twice, searching for a swarmer by name brings up a bigger list

**Why is this bad/What are the consequences**:

Not the most major issue, but confusing and weird

**Steps to reproduce the problem**:

Spawn a swarmer shell
Enter swarmer shell
Use another account to open the orbit panel
Notice how the swarmer shows up twice

**When did the problem start happening**:

Unknown

**Extra information**:

**Comment by jonathan123700** [comment]
Also: in the swarmer chat a message is shown twice (with the red X2 thingy). its probably related.

**Comment by AffectedArc07** [comment]
Likely related to the fact they `Initialize()` twice due to them being awfully coded.
