### ISSUE TITLE
Colorblindness cured by the red screen effect from the Gates of Necropolis

### ISSUE THREAD

**Issue by Elementium-OrTa** [ParadiseSS13/Paradise#13371]
**Issue Description**:
The red screen coloring given from the Gates of Necropolis removes the colorblindness color filter.

**What did you expect to happen**: 
To still be colorblind after the red overlay went away.

**What happened instead**:
Was somehow cured of colorblindness when the red screen effect faded away.

**Why is this bad/What are the consequences**:
Provides an unconventional cure for colorblindness when there's no reason for it to cure it.

**Steps to reproduce the problem**:
Be a colorblind miner
Go to the Gates of Necropolis
Tentatively knock on the gate.
Wait around for your screen to go red.
Marvel at how your colorblindness has been cured while you run for your life.

**When did the problem start happening**:
N/A

**Extra information**:

**Comment by Inadvizable** [comment]
This issue has been fixed in #16698
