### ISSUE TITLE
Vendor Account gains double/triple what you pay at a vendor

### ISSUE THREAD

**Issue by Elementium-OrTa** [ParadiseSS13/Paradise#13389]
**Issue Description**:
Comparing account balances before and after purchase at a an Account Uplink Terminal (there's one between the HoP office and conference room), the Vendor account gain more cash from vendor transactions than it should.

**What did you expect to happen**: 
For the vendor account to get the amount of cash that was paid, and not more.

**What happened instead**:
If you pay with your ID, it gets triple the cash.
If you pay with hard cash, it gets double.

**Why is this bad/What are the consequences**:
Makes no sense and allows unintended illegitimate money duplication (even though the method sucks).

**Steps to reproduce the problem**:
Note the cash balance of the Vendor account (starts at 5000).
Go purchase something from a vendor at price X.
Check the balance of the Vendor account once more, and note that it increased by an amount greater than X.

**When did the problem start happening**:
N/A

**Extra information**:
Checking the transactions log for the Vendor account reveals that ID purchases have two transaction logs instead of one. Cash purchases produce only one log. I assume there's one more hidden transaction happening. Checking the transaction account for your ID shows one log for payment.

**Comment by tinfoiltophat** [comment]
Wanted to mention that I was able to replicate this. It will only debit the buyer's account once, generates two transaction logs for the vendor, and credits 3x the amount. Currently working on a fix.
