### ISSUE TITLE
when walking diagonally it's possible to lose grip on rolling beds.

### ISSUE THREAD

**Issue by Sheppysneik** [ParadiseSS13/Paradise#13385]
**When an occupied rolling bed and potentially other objects are next to a solid object like a wall or a window, moving diagonally will cause you to lose the grip**

**What did you expect to happen**: 
to start pulling the object diagonally without losing the grip.

**What happened instead**:
i lost the grip on the object.

**Why is this bad/What are the consequences**:
it's annoying.you'll have to pull the object without moving diagonally, and potentially lose time catching it again after you lose it. 

**Steps to reproduce the problem**:
>put roller bed next to a solid object 
![immagine](https://user-images.githubusercontent.com/52687739/81146826-52220f00-8f79-11ea-93b2-0819e5a57493.png)
>pull it and don't stop moving diagonally south-side, in this case.
![immagine](https://user-images.githubusercontent.com/52687739/81147169-07ed5d80-8f7a-11ea-8a15-004f6e29e6b0.png)

**When did the problem start happening**:
since #11358 maybe? wanted to report it from a long time but i forgot to.

**Extra information**:
i tested this on the last build on an occupied rolling bed and the problem happens. it seems that the wheelchair seems to suffer this same problem but more rarely?

**Comment by Fox-McCloud** [comment]
This isn't really fixable; it's not a result of the smooth gliding either.

See, diagonal movement is a hack; you're not actually moving diagonally; you're moving (in the case of moving south-east) down and to the right. 

When you pull things at an angle in some of these situations, you're trying to make it move in a way it can't that's attempting to follow you---in other words you're shoving it into a wall and breaking the pull in the process of things.

**Comment by Spaghetti-bit** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/25592
