### ISSUE TITLE
Borgs can remotly use wall defibrillators

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13383]
**Issue Description**:

Borgs can use wall defibrillators remotely, making the defib paddles appear under them magically

**What did you expect to happen**: 

Nothing to happen when I click on the wall mount from the middle of medical

**What happened instead**:

magically appearing paddles under me 

**Why is this bad/What are the consequences**:

Borgs shouldn't be able to remove the paddles.

**Steps to reproduce the problem**:

Head to medical as a borg
Click on the wall defib from everywhere, not even beside it
magic paddles below you

**When did the problem start happening**:

Unknown
![image](https://user-images.githubusercontent.com/52090703/81127113-34b65c00-8f0b-11ea-9692-3fa835263b0c.png)

**Comment by Spacemanspark** [comment]
I just imagine a secborg in the middle of combat using magnets to pull the handles towards them, the attached wiring tripping a group of flukies
