### ISSUE TITLE
Alt-Click tabs on tiles aren't closed when you climb Jacob's Ladder

### ISSUE THREAD

**Issue by Elementium-OrTa** [ParadiseSS13/Paradise#13391]
**Issue Description**:
Climbing or descending Jacob's Ladder doesn't close Alt-Click tabs, allowing you to interact with objects or mobs at the bottom of the ladder while you're at the top of the ladder.

**What did you expect to happen**: 
The Alt-Click window to move with my character to the different z-level or close.

**What happened instead**:
It doesn't close or move, allowing you to interact with anything on the tile except for the turf.

**Why is this bad/What are the consequences**:
You can teleport from the top of the ladder to the bottom by Alt-Clicking the tile the ladder is on, or attack or interact with things at the bottom while at the top.

**Steps to reproduce the problem**:
Obtain or spawn in the Jacob's Ladder item.
Use it.
Ensure you have Spess protection.
Alt-Click a tile with a mob or item on it before climbing to the top of the ladder.
Interact with that mob or item.

**When did the problem start happening**:
N/A

**Extra information**:
Haven't tried this with regular ladders. Does Paracode have regular ladders?

**Comment by Kyep** [comment]
We really should just remove Jacob's Ladder completely. It is a very dumb item.

**Comment by Sirryan2002** [comment]
Still an issue 👍
