### ISSUE TITLE
Instant Summons spell takes containers if the Marked item is in one

### ISSUE THREAD

**Issue by Elementium-OrTa** [ParadiseSS13/Paradise#13390]
**Issue Description**:
Happened to get a Pulse Carbine and a Spellbook of Instant Summons during a wizard round.
After marking the gun, I found that if someone took it and put it in their bag, I get their bag with the gun after recalling the item.

**What did you expect to happen**: 
To only get the Marked item.

**What happened instead**:
I got the entire bag the Marked item was in.

**Why is this bad/What are the consequences**:
I hadn't marked the bag for recall, and it allows for an interesting although unintended method of theft.

**Steps to reproduce the problem**:
Somehow obtain a Spellbook of Instant Summons (or spawn one in).
Use it and then mark a pen or gun or whatever.
Place the Marked Item into a box or bag, then put it on a monkey or the ground.
Recall the Marked Item.
Theft of container containing Marked Item successful.

**When did the problem start happening**:
N/A

**Extra information**:

**Comment by datlo** [comment]
This is working as intended. Not an issue.

**Comment by TheSardele** [comment]
https://github.com/ParadiseSS13/Paradise/blob/928a8f0e04b932cc8b6bee49caf6dde0b6b1acfa/code/datums/spells/summonitem.dm#L58
Here is the line of code, showing that it is intended.

**Comment by nok-ko** [comment]
May be wise to add player-facing text explaining that particular feature, as well.

**Comment by trololiver112** [comment]
changing the description from "This spell can be used to recall a previously marked item to your hand from anywhere in the universe." to "This spell can be used to recall a previously marked item or the container containing it to your hand from anywhere in the universe." ?
Easy fix that could make it easier to see that this is indeed intended i guess?
