### ISSUE TITLE
vulpkanin bugs

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#1339]
the spots on the face clip through eye wear, and some clothing items clip through the tail.

![vug ss13](https://cloud.githubusercontent.com/assets/12041669/8222511/8224fe10-153a-11e5-86db-03c4b17939a0.PNG)
boots clip tail
![ss13 bugs 2](https://cloud.githubusercontent.com/assets/12041669/8222522/a63d3dbc-153a-11e5-9c06-65dfb01f644a.PNG)
wearing sec HUD

**Comment by KasparoVy** [comment]
Not sure if this is an issue for Tajarans and Unathi (other tailwagging species) as well, will have to look into that too

**Comment by veganzombeh** [comment]
I think the spots are drawn on the same layer as hair, so it will draw the spots on top of anything that doesn't hide hair.
