### ISSUE TITLE
The cryo-log in the permabrig is not working

### ISSUE THREAD

**Issue by Nepoox** [ParadiseSS13/Paradise#13425]
**Issue Description**:

The cryo log in the perma brig does not work as intended. It does not show when a prisoner cryos. The normal cryo log does.

**What did you expect to happen**: 

To show when a prisoner cryos.

**What happened instead**:

It was just blank and empty. The normal cryo log did show his name.

**Why is this bad/What are the consequences**:

The Warden thinks he escaped.

**Steps to reproduce the problem**:

Put a mob in perma with prisoner-ID and cryo them.

**When did the problem start happening**:

Today, but it probably was an issue before already.

**Extra information**:

**Comment by DGamerL** [comment]
Unsure when this was fixed, but on the current master it works correctly.
If this happens again, feel free to open a new issue report!

![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/9fa8e054-73ba-4658-96b9-aa617671e9b1)
