### ISSUE TITLE
Re-entering killed blob-zombie corpse crashes the game

### ISSUE THREAD

**Issue by Ninjatrollol** [ParadiseSS13/Paradise#1342]
Hi guys. Not a incredible game-ruining bug but still, perhaps it's worth mentioning.

Was a clown and got killed by the blob while fightning it in the name of the immaculate Honkmother. My dead honkbody turned into a blobhonkzombie and got robustidly killed by the captain and others. I ghosted to spectate after I was killed by the blob but before the body was turned into a blobzombie. 
After the blobhonkzombie was killed, the body was taken to medbay so I re-entered as I guessed it was going to be cloned. When I clicked the Re-enter Corpse command in the menu, the game crashed with the standard windows "program stopped working" message. I don't know the exact details of the error message as I closed the window pretty much immediatly and restarted SS13. When I got back into the game I had re-entered my corpse. No big deal in the end but got advised by a mentor to post it here so here it is.

Honk.

**Comment by FalseIncarnate** [comment]
This is likely a similar (if not the same) issue as crashes during jumping, teleporting, and so forth that cropped up after the lighting overhaul.

It is a BYOND issue simply on the merit of being a full application crash.

**Comment by TheDZD** [comment]
Try updating to the latest BYOND version, this crash should be fixed in 508.1289 according to Lummox JR.
