### ISSUE TITLE
Casting the shadowstep vampire power generates a ridiculous amount of attack logs

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#13434]
**Issue Description**:
Casting the shadowstep vampire power generates a ridiculous amount of attack logs.

![LS4s6F1QY9](https://user-images.githubusercontent.com/42044220/81966627-63a19180-95df-11ea-94b4-7f6c23acbb51.gif)

**What did you expect to happen**: 
For it to generate only one log.

**What happened instead**:
It generated a 100 logs.

**Why is this bad/What are the consequences**:
It spams admins with tons of logs for no reason and lags the chat.

**Steps to reproduce the problem**:
Become a vampire, get the spell "shadowstep" and cast it. Observe the admin log spam.

**When did the problem start happening**:
I have no idea.

**Extra information**:
It seems to generate more logs if every tile around you is darkness. But for example if you are in a lit hallway with just a few dark tiles nearby it only generates maybe a handfull of logs.

Also there were no runtimes.

**Comment by farie82** [comment]
it is because of:
https://github.com/ParadiseSS13/Paradise/blob/d7e8757c492d39ec745fc1947775271bf0a503ba/code/__HELPERS/mobs.dm#L277-L282
target here is a list of all possible turfs. Which is a ton. So an attack log is generated for each turf. Each log should have been put on `ATKLOG_ALL` though
