### ISSUE TITLE
Cursed Clown/Mime Mask (Not to be confused with cluwne) is not functional internals

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13458]
**Issue Description**:

The masks don't work as internals like the original ones do which causes issues for races that get turned into clowns or mimes via magic who can't take off their masks, becoming unable to breathe. Mainly Vox have this issue since they are the majority that get hit by this.

**What did you expect to happen**: 

I expected the masks to work normally and not make them suffocate to death.

**What happened instead**:

They suffocated on the O2 in the air giving them Toxin and O2 Damage which probably took them out of the round.

**Why is this bad/What are the consequences**:

Mimeify and Clownify Wizard spell kills certain races who can't easily get acid that can melt masks off.
I don't think this was intended and was ment to be harmless for the most part.

**Steps to reproduce the problem**:

1. Use the mimeify/clownify spell on a vox or plasmaman
2. Watch them slowly die on the O2 in the air.

**When did the problem start happening**:

Not sure when these spells were added. Might of started before vox and plasmaman were added? No idea when they got added though and I'm not certain when the issue started.

**Extra information**:

I think the spell might also remove plasmaman enviromental protective suits too.

**Comment by datlo** [comment]
That's very strange as I added these spells. The masks are the exact same as regular clown and mime mask, they just have nodrop added.

The spell was made before the plasmaman rework so I'll have to test for that and see about changing it for the envirosuit yeah. 

I'll test internals with the masks but I see no reason you cant use internals with them. The spell WILL cause you to drop your tank if its in your pocket due to changing your uniform but you can pick it back up.

**Comment by iantine** [comment]
Can confirm this. With a tank in pocket/belt/wherever, attempting to turn on said tank you receive a message similar to "You are not wearing a suitable mask".

**Comment by tinfoiltophat** [comment]
> That's very strange as I added these spells. The masks are the exact same as regular clown and mime mask, they just have nodrop added.
> 
> The spell was made before the plasmaman rework so I'll have to test for that and see about changing it for the envirosuit yeah.
> 
> I'll test internals with the masks but I see no reason you cant use internals with them. The spell WILL cause you to drop your tank if its in your pocket due to changing your uniform but you can pick it back up.

It turns out that the nodrop flag was overriding the standard airtight flag that makes masks viable for internals. Will push a fix once i can get the spell to work for envirosuits.

**Comment by datlo** [comment]
Ah.. Didnt realise the flag for mask was part of that var. Oops. good catch
