### ISSUE TITLE
Lighting is not updating properly

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#13472]
**Issue Description**:
Lighting does not update till you enter the area. Sometimes that also does not fully work

**What did you expect to happen**: 
It to update like before

**What happened instead**:
It does not update

**Why is this bad/What are the consequences**:
It's a bug

**Steps to reproduce the problem**:
Open the door shown on the picture

**When did the problem start happening**:
Since the lighting refactor #13436 

**Extra information**:
![image](https://user-images.githubusercontent.com/15887760/82600410-2ffdd300-9bae-11ea-8bbb-11ab245b7d5f.png)

**Comment by Fox-McCloud** [comment]
Already known--curious as to *why* it's happening. Informed TG about it. Hopefully i'tll be fixed soon.

can't tell what's obviously wrong, at a glance.
