### ISSUE TITLE
Cloning pod has no off sprite

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#13484]
**Issue Description**:
Cloning pods lose their sprite if you disable equipment on the area APC, the cloner will lose its sprite

**What did you expect to happen**: 
The cloner to keep its sprite or have a dedicated off sprite

**What happened instead**:
Its sprite dissapeared

**Why is this bad/What are the consequences**:
You cant access or even see the cloner unless you rightclick or alt click the cloner

**Steps to reproduce the problem**:
Disable the equipment channel on the APC for the area the cloner is is 

**When did the problem start happening**:
N/A

**Extra information**:
N/A

**Comment by datlo** [comment]
Related issue : https://github.com/ParadiseSS13/Paradise/issues/13410
