### ISSUE TITLE
Communication key not showing

### ISSUE THREAD

**Issue by Kepplerx** [ParadiseSS13/Paradise#13492]
Multiple times as I have been the RD, the Communications console (I think thats the name, the one for PDAs anyway) has been missing. Not in physically missing, but a white paper without a code. In one instance I asked another crewmember to read it (if the problem was on my end) but it was blank for them too. I did play some days ago (a week, or more?), and back then this was not a problem. As you can certainly understand, Access to this server is very useful as RD, if it has been removed or left blank for other reasons, then I stand corrected. To note I did ask both admins and mentors at the time (and Nanotrasen CC) for the code, but was not provided it, I dont quite remember the reason, either it was because it wasnt there or something. Hope this report helps, that is the intention at least.

**Comment by Kyep** [comment]
Paper is printed.
Key is saved to the vars on the paper.
Paper just displays blank when read. HTML won't render for some reason.
Has been happening in a fair few rounds now.
