### ISSUE TITLE
SBRs/Intercomms don't function if TComms is dead

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#13496]
**Issue Description**:

SBRs/Intercomms do not function if Telecommunications is disabled/destroyed.

**What did you expect to happen**: 

Radio comms to go through when T-Comms was disabled.

**What happened instead**:

Radio comms did not go through as expected.

**Why is this bad/What are the consequences**:

They are supposed to be semi-separate from the telecomms network, and should work even if telecomms itself is non-functional.

**Steps to reproduce the problem**:

1. Obtain SBR or use an intercom.
2. Disable/destroy telecomms.
3. Speak.
4. Listen to [the sound of silence](https://youtu.be/u9Dg-g7t2l4?t=12).

**When did the problem start happening**:

After @AffectedArc07's PR: #13446.

**Extra information**:

N/A.

**Comment by Fox-McCloud** [comment]
Fixed: https://github.com/ParadiseSS13/Paradise/pull/13497
