### ISSUE TITLE
Bluespace anomaly still continues after it is defused

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#13508]
**Issue Description**:
As the title says. The anomaly still fires and translocates stuff while the anomaly is defused and a core is gained

**What did you expect to happen**: 
It not to trigger

**What happened instead**:
It bluespaced medbay into space while the core was defused

**Why is this bad/What are the consequences**:
It's a bug

**Steps to reproduce the problem**:
have it trigger I guess and defuse it. It took a while to get defused but atleast 30 seconds before the teleport trigger happened

**When did the problem start happening**:
Not sure. Might be related to the anomaly event change in a PR recently

**Comment by Fox-McCloud** [comment]
Pfffttt.

I'll look into this when I finally update the SM PR, as it touches on anomalies.

This doesn't happen every time---so if I were to guess, this is probably some kind of weird runtime or de-referencing issue.

**Comment by farie82** [comment]
I checked for related runtimes in the round but didn't see any on first glance

**Comment by moxian** [comment]
duplicate: #10780

**Comment by farie82** [comment]
Dupe so closing time
