### ISSUE TITLE
You can wear krav maga gloves to turn off sleeping carp and shoot guns

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13501]
**Issue Description**:

By putting on krav maga gloves, you overide sleeping carp, allowing you to shoot guns

**What did you expect to happen**: 

Gaining the power of sleeping carp and krav maga

**What happened instead**:

Sleeping carp is turned  off, you can be shot, BUT you can also shoot guns as well

**Why is this bad/What are the consequences**:

Sleeping carp is not something you should be able to turn on and off at will to shoot guns.

**Steps to reproduce the problem**:

Spawn and use a sleeping carp scroll
Try and fail to shoot a gun
Put on krav maga gloves
Notice you are now able to shoot guns, and to be shot with ranged weapons

**When did the problem start happening**:

Probably the martial art rework

**Comment by SteelSlayer** [comment]
The martial arts rework has not been merged yet, but it may fix this, not sure.

**Comment by BakKeener** [comment]
I doubt it's going to fix it. Probably more of an issue of you can't having more then one martial arts at a time if that's a thing. From the sounds of it, Krav Maga overrides Carp and the moment it's removed the override is gone and carp is back.
