### ISSUE TITLE
Minor spelling mistake.

### ISSUE THREAD

**Issue by monkeysfist101** [ParadiseSS13/Paradise#1350]
Just an extra character for the Robust Packets.
http://puu.sh/iv3eI/977a27dd1f.png

**Comment by tylerh95** [comment]
Can anyone confirm if this is fixed?

**Comment by CrAzYPiLoT-SS13** [comment]
Yeah, I saw a PR dealing with this. You should check just in case.

**Comment by PJB3005** [comment]
if it isn't, sanitize() in the code that sends the currently selected item to the nanoUI
