### ISSUE TITLE
Registered z level mismatch

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#13522]
**Issue Description**:
After Fox made it clear we're still interested in messages like these:
ADMIN LOG: [name goes here] has somehow ended up in Z-level 12 despite being registered in Z-level 9. If you could ask them how that happened and notify the coders, it would be appreciated.

Reporting that happening today, it happened after the player was thrown off the escape shuttle while it was in transit. No idea why it says z level 9 and 12 if he was thrown from the escape shuttle, though.

Related attack log:
Thrown from tile at 13, 246, 2 in area the Emergency Shuttle with the target tile at 7, 246, 2 in area Space"

**What did you expect to happen**: 
No such messages

**What happened instead**:
got such a message

**Why is this bad/What are the consequences**:
Fox told me we're still interested in getting those reported in #13480

**Steps to reproduce the problem**:

**When did the problem start happening**:

**Extra information**:
I hope this is specific enough.

**Comment by matttheficus** [comment]
Not an issue directly it seems, debug info.
