### ISSUE TITLE
Lavaland snow biome console issues 'toFixed' error

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#13530]
Lavaland snow biome Power Monitoring Console issues ERROR: An error occurred while rendering the UI: Unable to get property 'toFixed' of undefined or null reference

**What did you expect to happen**: 
The console to load properly

**What happened instead**:
The console would not initialise, and displayed the same error repeatedly

**Why is this bad/What are the consequences**:
It renders the console unviewable

**Steps to reproduce the problem**:
1. Visit the Lavaland snow biome
2. Click on the Power Monitoring Console
3. View error

**When did the problem start happening**:
Noted by a player today, and double checked it as an observer. Uncertain when problem started happening.

**Extra information**:
Visual:
![tofixed](https://user-images.githubusercontent.com/26665535/83543027-1dd14c80-a53f-11ea-9134-85fb5e18a1ec.png)

**Comment by AffectedArc07** [comment]
Something todo with this. This error occurs when trying to use `smoothRound()` on text. Something probably fucked with the powernet here.

**Comment by AffectedArc07** [comment]
After doing some investigation, there is no powernet even connected to this console, which is also the reason for error. This console is fully redundant, and has no cables, nor reason to exist.
