### ISSUE TITLE
Actively tracking vitals off z-levels or suit sensors using a cloning console.

### ISSUE THREAD

**Issue by Aidenzack1** [ParadiseSS13/Paradise#13533]
**Issue Description**:

You are able to track vitals off z-level and presumably without suit sensors even being on in the first place, just by getting them pre-scanned at medical and clicking refresh to track their vitals in near real time.

**What did you expect to happen**: 

To only see vitals that they had before scanning.

**What happened instead**:

Vitals change as pre-scanned individual takes damage.

**Why is this bad/What are the consequences**:

People can use this to actively track people's vitals, despite if someone took them off z-level or disabled sensors outright. This is bad due to how someone can track if someone is being harmed, despite if someone took all the necessary precautions to make sure people cant check vitals. 

**Steps to reproduce the problem**:

Pre-scan someone, click refresh, damage should update as they take damage.

**When did the problem start happening**:

 6-2-2020 M/D/Y

**Extra information**:

**Comment by Fox-McCloud** [comment]
Not a bug. This is functioning exactly as intended.
