### ISSUE TITLE
Ai doesnt track radio messages in say logs

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13531]
**Issue Description**:

For all messages the AI says to show in the in game logging system, but only holopad and binary shows

**What did you expect to happen**: 

Everything the AI says to be logged

**What happened instead**:

Only holopad and binary is logged

**Why is this bad/What are the consequences**:

Can not track what the AI has said over comns in logging view in game.

**Steps to reproduce the problem**:

Have the AI say anything over comns
Open logger and put the AI in
Note that the radio message is not logged

**Comment by farie82** [comment]
![image](https://user-images.githubusercontent.com/15887760/83563854-059c0600-a51c-11ea-9d47-ae64ff12cd00.png)
Test done on an old branch that didn't have the tcomms PR. Works here
#13446 most likely forgot to add something or such. Shouldn't be hard to fix
