### ISSUE TITLE
Cannot detach Repair Droid from Mechs

### ISSUE THREAD

**Issue by Blackmage198** [ParadiseSS13/Paradise#13548]
**Issue Description**:
You cannot detach the Repair Droid from mechs

**What did you expect to happen**: 
To be able to detach the droid from the equipment section of the mech screen

**What happened instead**:
I wasn't.

**Why is this bad/What are the consequences**:
If you accidentally place a droid on a mech or want to remove it, you're boned.

**Steps to reproduce the problem**:
1. Attach a droid
2. Try to remove
3. Cry at the wasted slot

**When did the problem start happening**:
Unknown, only witnessed today.

**Comment by AffectedArc07** [comment]
I have had this about a month ago, and it also introduces fucky behaviour where pressing “Detach” on the repair droid just drops the first index in the list of equipment, and you can put multiple repair droids on.


The even weirder part is removing a droid will remove the sprite, but keep the item on, but the sprite will come back if you toggle it on or off.
