### ISSUE TITLE
Pirate energy cutlass wrong sprite

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#13540]
**Issue Description**:
The pirates energy cutlass sprite is now using the regular energy sword sprite when it has its own sprite.

**What did you expect to happen**: 
For the energy cutlass to look like the energy cutlass.

**What happened instead**:
It now looks like the syndicate energy sword.

**Why is this bad/What are the consequences**:
Causes a bit of confusion as in hand it looks like a cutlass someone is wielding, but on the ground it looks like an energy sword.

**Steps to reproduce the problem**:
Spawn the melee/energy/sword/pirate and see its using the wrong sprite.

**When did the problem start happening**:
Just this week of 6/4/2020.  Last week it was fine.

**Extra information**:

**Comment by dearmochi** [comment]
Fixed in dearmochi/Paradise@7a64b1874cf859082cdc88c4eced90c6e93498d3 that I'll bundle in a PR along with other fixes
