### ISSUE TITLE
Magic spells / items / summons forbiden to mages on raging mages can be bought

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13541]
**Issue Description**:

Wizards can by anything in the spellbook on raging mages

**What did you expect to happen**: 

Apprenteces, lich, and the like to be RIGHT OUT

**What happened instead**:

Raging mages have apprentices and lich and everything is on fire

**Why is this bad/What are the consequences**:

Raging mages have restrictions to keep wizards living forever / making more apprentences, this breaks that

**Steps to reproduce the problem**:

Force the round as raging
Watch as as everything goes to hell as there is apprenteces and liches

**When did the problem start happening**:

06/04 first reported case

**Comment by Shockpoint** [comment]
This is why I never force ragin'.

**Comment by SteelSlayer** [comment]
I don't know if there was ever code to restrict buying these two things during ragin. Do you recall them being unable to buy in the past at any point?
