### ISSUE TITLE
Sec borg makes cursed stun batons

### ISSUE THREAD

**Issue by Niteark** [ParadiseSS13/Paradise#13553]
**Issue Description**:
Sec borg can create undroppable stun batons with no limits.

**What did you expect to happen**: 
Borg should not be able to place it's modules

**What happened instead**:
Borg is able to place a stun baton inside a personal locker that can be picked up by crew but cannot be dropped.

**Why is this bad/What are the consequences**:
Borg can arm entire station with cursed stun batons creating chaos

**Steps to reproduce the problem**:
Go to arrivals locker room, open a personal locker, click the locker with an active stun baton module as a sec borg, it will be placed inside and can be picked up by crew.

**When did the problem start happening**:
I first noticed this today.

**Extra information**:
I only tested a few different lockers, it worked in two separate personal lockers but not others.

**Comment by AffectedArc07** [comment]
It appears you forgot to fill out your issue details. To edit your issue, press the 3 dots in the top right and edit.
![image](https://user-images.githubusercontent.com/25063394/83942189-35cbf900-a7e9-11ea-8291-f306d8f0f643.png)

If you need any help with GitHub, dont be afraid to ask
