### ISSUE TITLE
Cleanbots do not appear on Custodial Pro cartirdge

### ISSUE THREAD

**Issue by Oyu-De** [ParadiseSS13/Paradise#13565]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/66401072/83973178-53828680-a8ed-11ea-8623-d6d8ced22a9e.gif)

**Issue Description**: Cleanbots do not appear on custodial pro cartidge

**What did you expect to happen**: Custodial pro cartrdigde to be able to see/locate/control/summon cleanbots

**What happened instead**: “No cleanbots detected” on the PDA even though they are visible and connected

**Why is this bad/What are the consequences**: Janitors lack the controll to locate/summon cleanbots and can be utilised to some extent but now they just wander around (when janitor can summon them to help cleaning).

**Steps to reproduce the problem**:
1– Start as a janitor or get custodial pro cartridge from cargo
2– Open PDA —> Custodial locator
3– “No cleanbots located/connected
4– Find a cleanbot and check that it is connected and question why

**When did the problem start happening**: Unable to give a specific date as I started playing janitor recently. Atleast 4 days.

**Extra information**: (just a note) Will update and add a small video clip if possible to better illustrate

**Comment by dearmochi** [comment]
I've fixed this issue that I'll bundle with other fixes in an upcoming PR

Technically speaking, the problem stemmed from the fact that the PDA was looping through `GLOB.simple_animals` which no longer is a list of simple animals, but is now a list of lists of simple animals depending on their AI state. Judging by that modification was made, that issue was around for at least a year

**Comment by Oyu-De** [comment]
> I've fixed this issue that I'll bundle with other fixes in an upcoming PR. I'll also touch up the template a bit so the custodial locator UI looks a bit neater
> 
> Technically speaking, the problem stemmed from the fact that the PDA was looping through `GLOB.simple_animals` which no longer is a list of simple animals, but is now a list of lists of simple animals depending on their AI state. Judging by that modification was made, that issue was around for at least a year
> 
> Commit: [dearmochi/Paradise@1b17002](https://github.com/dearmochi/Paradise/commit/1b1700271e0a4bf74b56bcfeed9f671437168b29)


Oh, glad to hear that it is actually someahat known and getting fixed. Was asking on discord for the last 2 days and no one apparently knew/cared. Still, really glad to hear that it is in a PR
