### ISSUE TITLE
Telekinesis can cheese blobs

### ISSUE THREAD

**Issue by Marginalorb-zz** [ParadiseSS13/Paradise#13566]
**Issue Description**:
I watched a grey use telekinesis to fling a welding tool repeatedly underneath blob tiles until they managed to destroy the blob core despite the blob growing back before they could get the welding tool to a non blob covered tile.

**What did you expect to happen**: 
I expected the blob to eat the welding tool, as it was growing back as it was being damaged.

**What happened instead**:
Blob speedrun TK%

**Why is this bad/What are the consequences**:
It's unfair for the blob players to be downed by something they basically can't see coming or, from what I saw, stop.

**Steps to reproduce the problem**:
Put a lit welder on the floor near a blob, use Telekinesis to fling it into blob until you get it to the blob core, then win after you smacked the blob core until it died.

**When did the problem start happening**:
Who knows how long this has been broken, but I just noticed it as of June 7th

**Extra information**:
None.

**Comment by DGamerL** [comment]
As of currently, this issue has been fixed in two ways:
1. Blobs now properly eat TK'ed objects
2. (Welder only) Welders now take 0.5 fuel per hit, making it harder to abuse them against blobs and such
If this somehow happens again, feel free to make another issue report!
