### ISSUE TITLE
Fixing cameras does not allow AI to see through the area the camera is fixed.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13575]
**Issue Description**:

When a broken camera is fixed, the AI can not see the area.

**What did you expect to happen**: 

The AI should be able to see through a camera when it is fixed

**What happened instead**:

Ai reports that it can still not see through it.

**Why is this bad/What are the consequences**:

AI becomes blind and unable to fix issues as cameras break.

**Steps to reproduce the problem**:

Be the AI.
Have someone fix a broken camera
Notice you still can not see through it

**When did the problem start happening**:

First reported 08/06/2020

**Extra information**:

Deleting a camera updated ai's view properly

**Comment by dearmochi** [comment]
I can't seem to reproduce this by cutting the blue wire and mending it back, what do you mean by broken? Completely destroyed?

**Comment by Qwertytoforty** [comment]
Strange, I was reported that the AI couldn't see through the blue shields office camera, which was broken round start, after the wires were mended.
