### ISSUE TITLE
DIY bluespace lockers

### ISSUE THREAD

**Issue by SpookSpooky** [ParadiseSS13/Paradise#13585]
Allows you to create a DIY bluespace locker with a regular lockable locker

**What did you expect to happen**: 
A locker become a physics object and not have the ability to be walked through.
**What happened instead**:
The locker began to act like a bluespace locker while losing the ability to hold items.

**Why is this bad/What are the consequences**:
Allows anyone to have a better locker. (cant hold items oddly)
Bugs bad, pest spray doesn't work.

**Steps to reproduce the problem**:
Requires an ID and locker.
ID unlock the locker, open it completely, stand in the locker and then click your ID on the locker itself. 
It will close and now be able to be walked through.

**When did the problem start happening**:
Probably since forever, noticed June 8 2020

**Extra information**:
Images of the glitch (ignore Im upside down)
![ghnfbdvsd](https://user-images.githubusercontent.com/58868568/84102299-5359b800-a9cd-11ea-9976-c5e67e7a434c.PNG)
![hgjnbfvd](https://user-images.githubusercontent.com/58868568/84102300-55bc1200-a9cd-11ea-9604-835c2c2c2c05.PNG)

**Comment by Fox-McCloud** [comment]
@farie82 

This looks like it's happening specifically with personal lockers.

**Comment by SteelSlayer** [comment]
This is my fault.. somehow. I'll see about fixing it
