### ISSUE TITLE
Malf AI

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#1359]
Malf AI can't start properly, even if all conditions required are met.
It can't even be force-started.

**Comment by Fox-McCloud** [comment]
Suspect this is the case for revolution, as well.

@tigercat2000

**Comment by Spacemanspark** [comment]
This would explain the dozens of AI rounds I've played and never gotten MALF.

**Comment by Davdichan** [comment]
I'm okay with no Revolutions, no MALFs how ever makes me a sad little cyborg.
