### ISSUE TITLE
Blob/Blobbernauts can't damage Full Tile Reinforced Glass

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13609]
**Issue Description**:

For whatever reason the Blob and blobbernauts can't damage full tile reinforced glass when they can destroy regular reinforced glass with ease and the blob itself can shatter walls with 2 hits.

**What did you expect to happen**: 

I expected to be able to destroy the glass so I can expand into those tiles.

**What happened instead**:

I couldn't do anything to the glass, the blobbernauts couldn't damage it for us so it just stood there.

**Why is this bad/What are the consequences**:

It just became an hinderence and actually helped get the first overmind killed because he couldn't put reflective blobs on it since his core was next to it and he just was blasted with lasers unable to do anything.

**Steps to reproduce the problem**:

1. Place a full tile reinforced window.
2. Have either a Blob Overmind try to expand into it or blobbernaut try to smash it
3. See that they can't expand or remotely damaage the thing.

**When did the problem start happening**:

Probably been there for awhile? Maybe when universal object damage became a thing?

**Extra information**:

I do recall being able to get rid of them and I'm not sure what's different now, it even inhibits blob nodes from expanding through them.

**Comment by trololiver112** [comment]
unable to recreate this. I seem to be able to destroy reinforced full tile glass both as a blobber as well as a overmind

**Comment by BakKeener** [comment]
Weird, We weren't able to that round, Maybe something wasn't running properly that round and broke it.

**Comment by BakKeener** [comment]
@trololiver112 I just remembered something, I do believe the Reinforced Full Glass Tiles were unscrewed and crowbarred into loose entities, perhaps that was the cause of me not being able to break them?

**Comment by Sirryan2002** [comment]
Given this was made before map rotation and that most blobs on box station like to pop in turbine, I'm going to take a wild guess that this is definitely a consequence of the var edited windows in the southern abandoned bar. They were var edited to have 7 million integrity each. Furthermore, I could not reproduce this issue on production on any fulltile window.
