### ISSUE TITLE
Blob eating the nuke doesnt actually blow the station

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#13600]
**Issue Description**:
The blob eating the nuke ends the round but doesnt actually explode the station

**What did you expect to happen**: 
"Station destroyed by nuclear device"

**What happened instead**:
"A nuclear device exploded but it was not on station"

**Why is this bad/What are the consequences**:
Blobs technically win and it causes a blank animation at roundend

**Steps to reproduce the problem**:
Eat the nuke as a blob

**When did the problem start happening**:
Since the blob nuke PR was merged

**Extra information**:
The nuke was primed

**Comment by TDSSS** [comment]
Where exactly was the nuke set? It might just have been too far out from the center of the station to count.

The blob attack literally just causes the nuke to go off, it doesn't even delete it so I have a hard time believing it is the underlying issue.

**Comment by TDSSS** [comment]
Also, what _exactly_ was the message shown? Was it
"A nuclear device was set off, but the device was not on the station!"?

The game shouldn't even end in that case.

**Comment by TDSSS** [comment]
![Untitled](https://user-images.githubusercontent.com/32099540/84401596-bd5ba280-ac03-11ea-8db2-4635ecc01e98.png)
Can't reproduce, seems to work just fine in the base case.

**Comment by AffectedArc07** [comment]
Cannot repro
