### ISSUE TITLE
Treadmills in brig are the wrong away

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#13603]
**Issue Description**:

Treadmills in brig are the wrong away

**What did you expect to happen**: 
For the treadmills to be the right way, allowing me to run for tickets and be launched of if i stop

**What happened instead**:

Nothing

**Why is this bad/What are the consequences**:

No easy weightloss, and no tickets for the filthy criminals

**Steps to reproduce the problem**:

Step on treadmill and run, if you run off, you run off, if you run towards a solid surface, nothing happens

**When did the problem start happening**:

Been around for maybe 2 years?

**Extra information**:

**Comment by PacifistDalek** [comment]
This still isn't fixed, this makes brig clown sad :c
