### ISSUE TITLE
Lesser Ash Drake Reversion Seems To Cause Increasing Lag

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#13610]
**Issue Description**:
Every time I reverted to my humanoid form as a lesser ash drake I appeared to get increasing amounts of lag each time I did it, it may have also affected people in the near vicinity

**What did you expect to happen**: 
To revert back to normal without any lag

**What happened instead**:
Each time I reverted it appeared to get more and more laggy as well as potentially impacting others

**Why is this bad/What are the consequences**:
Lag is bad and being able to intentionally lag others is bad

**Steps to reproduce the problem**:
1, Get lesser drake transformation
2. Transform back and forth a number of times
3. Experience progressively worse lag

**When did the problem start happening**:
No clue, but it happened to me during the round starting at 8:46 PM EST on the 13th of June

**Extra information**:

**Comment by farie82** [comment]
Could not reproduce it locally. When did the lag start? Did it end at some point?
