### ISSUE TITLE
Mesons still borked

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#1362]
Contrary to 
"Meson fix in action:
https://dl.dropboxusercontent.com/u/107028026/ShareX/2015/06/2015-06-19_15-58-10.webm"

in #1347 Lighting optimizations, mesons are still bork bork borked as they were before

See if you can spot the Unathi wearing mesons: http://i60.tinypic.com/23j07cw.png

I'm 100% sure that .webm showed mesons as they used to be with items out of darksight range just not being rendered, but that's clearly not the case r.n.

**Comment by Fox-McCloud** [comment]
@KasparoVy 

The server hasn't been patched yet; there's often a delay on what is run on the live server vs what's in the codebase. I tested out mesons locally and they work as demonstrated in that little video clip.

**Comment by KasparoVy** [comment]
My bad, I thought it was patched on main. I'll close this then
