### ISSUE TITLE
Paper Formatting Error

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#13653]
**Issue Description**:
Minor error in pencode formatting, unsure if this has been reported or not...frankly not going to look through 760 issues to be sure right now. At either rate, when using [center] before [large] it ignores the center tag entirely, and only makes large text. However, using [large][center] works as you would expect it to.

**What did you expect to happen**: 
I expected pencode to not care which format tag is used first, as it makes no real sense for it to do so.

**What happened instead**:
Pencode is apparently picky as hell, and did in-fact care what tag is used first.

**Why is this bad/What are the consequences**:
It will easily lead to incorrect formatting in papers and people assuming that formatting on a whole is currently broken, when in-fact it just has to be done unexpectedly specificially.

**Steps to reproduce the problem**:
1. Grab paper.
2. Write [center][large]
3. Watch as you get large text but it's not centered.
4. Put [large][center].
5. Wonder why exactly it matters which goes first.

**When did the problem start happening**:
Unsure

**Extra information**:
Credit goes to Squishy for finding out this issue.

**Comment by dearmochi** [comment]
The issue is with `marked-paradise.js` not eliminating `<p>` tags generated by `marked.js` properly. I'll push a fix shortly once I made sure it didn't break anything

**Comment by Mitchs98** [comment]
Awesome. Hopefully it fixes formatting in general for a lot of things!
