### ISSUE TITLE
Ghetto Surgery: Screwdriver (bone glue) does not work.

### ISSUE THREAD

**Issue by Davdichan** [ParadiseSS13/Paradise#1367]
Pretty simple, using a screwdriver on someone when you should be applying bone glue always stabs them instead of attempting repair the limb, even when on surgery tables. Need someone to look at the code for alternate surgery items and make sure everything is flagged correctly.

**Comment by veganzombeh** [comment]
It looks like screwdrivers can only be used for robotic organs. Do you know if it was robotic?

**Comment by Fox-McCloud** [comment]
I've definitely done multiple surgeries since this point and effectively used screwdrivers at bone gel. Was this a specific surgery or?

**Comment by Davdichan** [comment]
This Bug was submitted months ago, I believe it was on head surgery, I was trying to ghetto surgery a janitor after a he was critically wounded with a broken skull. Attempting to 'glue' his skull would stab him in the eyes while targeting his head on help intent. 

The wiki has since been updated to state that head surgeries are not possible anymore with ghetto tools. it's unclear if this is intentional or an oversight, as fractured skulls are life threatening and should be treated before the patient walks around too far causing more brute, brain and eye damage to themselves.

**Comment by Crazylemon64** [comment]
I've just performed a head bone-repair surgery with a wrench and screwdriver on both a normal table an an operating table, this can probably be closed.
