### ISSUE TITLE
Melee Attacks in Space drift your Sprite Off-screen

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#13686]
**Issue Description**:

Doing multiple melee attacks from space will slowly drift your sprite up, until it goes off the edge of the screen.

**What did you expect to happen**: 

My sprite would stay in the same place.

**What happened instead**:

Instead it slowly drifted upward until it looked like it was on a different tile, and kept drifting further upward with each attack until it drifted off the top of the screen.

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

1. Get Paramedic hardsuit and Dsword.
2. Go into space.
3. Repeatedly attack windows from space over and over again.

**When did the problem start happening**:

**Extra information**:

Getting shocked or lying down resets the position of your sprite to where it's supposed to be.

This is a screenshot of me appearing to be 2 tiles above where I actually am.
![image](https://user-images.githubusercontent.com/9967634/85664673-1f92b980-b680-11ea-8d39-2260d673bfda.png)

**Comment by DaveKorhal** [comment]
Did some more testing:
-It also resets your position if you re-enter the station.
-Other crew can also see the drift. (One commented I looked like I was in the Cargo Bay when I was just outside.)

**Comment by farie82** [comment]
Probably the same issue as #9119
