### ISSUE TITLE
Engineering shuttle console still exists on bridge after engineering shuttle removal

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13707]
**Issue Description**:

There is an engineering shuttle console on bridge after construction site was removed, leaving a pointless broken console

**What did you expect to happen**: 

For the console to be removed / replaced with something else

**What happened instead**:

console is still their, just showing up with a missing shuttle if clicked on

**Why is this bad/What are the consequences**:

Broken shuttle consoles should not be there / be removed

**Steps to reproduce the problem**:

Go to bridge
Notice the console by the door
Notice how its the engineering shuttle console, and how it is missing the shuttle when it is clicked on

**When did the problem start happening**:

Yesterday, before construction site was removed.

**Extra information**:

**Comment by Kyep** [comment]
This is technically fixed.

But now, we have 2 mining shuttle consoles on the bridge.
