### ISSUE TITLE
[Engineering] SMES cells discharged, dissassembled, reassembled 20% charge

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1372]
When a fully discharged SMES cell is dissassembled and reassembled it gains 20% charge from no where. Essentially meaning engineering would never need to setup power as they could dissemble the SMES cells all day for power.

Assembled SMES cells (regardless if new or old) should start with 0% charge. A PACMAN generator should be used instead to power/charge them.

**Comment by Robertha89** [comment]
Not a bug persay, it's intended kinda, depending on cell type, 5 basic cells give 25000 charge, 5 hyper cells give 150000, now the thing is, the charge level of the smes and charge level of the cells never interact, actually im not sure if even you you put in 5 drainged cells it will start empty, even then, you can just use a battery charger and charge a cell for less then it cost to power the area.

**Comment by Taaketa** [comment]
Point still stands that an engineer never has to setup sing or solars. Just dissassemble and reassemble several SMES all round for free power.

**Comment by PJB3005** [comment]
I think this didn't autoclose because @Fox-McCloud used a colon between "fixes" and the PR ID
