### ISSUE TITLE
Cloner won't clone brainless body after body scan upgrade

### ISSUE THREAD

**Issue by MisterOkapi** [ParadiseSS13/Paradise#13726]
**Problem Description**:
Cloner gives an error saying subject has no brain when it's set to scan the body to clone them.

**What did you expect to happen**: 
I thought that the cloner would clone the character based upon the DNA of the body

**What happened instead**:
It gave an error saying the subject had no brain.

**Why is this bad/What are the consequences:**
Seems like it should work on a brainless body or give an error message if something happened to prevent the cloning from happening.

**Steps to reproduce the problem**:
Found decapitated head. Put head on corpse. Attempted to clone but no brain detected. Put body in morgue. Cloner got upgraded. Took body out of morgue and put in cloner. Cloner failed to work.

**When did the problem start happening**:
today?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Cloner had 150 meats still inside.

**Comment by Fox-McCloud** [comment]
That's intended. You can never clone without the brain.

The feature to scan brain or body is what DNA to utilize.

Normally the scanner goes off of the body's DNA--upgrading it allows for it to go off of the brain's DNA---which allows for you to do a quickie brain transplant into a donor body of your choosing then shove it in the cloner, but still get the original person's appearance, as opposed to their new body's appearance.
