### ISSUE TITLE
Generalist Cyborg cannot use built-in zipties

### ISSUE THREAD

**Issue by Zynnq** [ParadiseSS13/Paradise#13734]
**Problem Description**:
Generalist Cyborg cannot use built-in zipties.

**What did you expect to happen**: 
Being able to cuff other people.

**What happened instead**:
Error message "The zipties is stuck to your hand!" appears instead of any other interaction with the zipties on people.

**Why is this bad/What are the consequences:**
A module not functioning at all is confusing.

**Steps to reproduce the problem**:
1) Pick generalist cyborg
2) Attempt to cuff crew or monkeys
3) Get message "The zipties is stuck to your hand!"

**When did the problem start happening**:
Zipties were never observed to have actually worked, so it might've sneaked in with PR #13056 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The bug was observed only after having been hit by an EMP previously - perhaps this just permanently destroyed the module, no testing on this was done prior to the EMP

**Comment by MarsM0nd** [comment]
Did check the thing with VV, the generalist has /obj/item/restraints/handcuffs/zipties, while security borgs have /obj/item/restraints/handcuffs/zipties/cyborg, that'll likely be the problem.
