### ISSUE TITLE
We are out of bitflags

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#13733]
**Issue Description**:
Our toggles preference has used the maximum amount of bitflags that BYOND supports (24). As such, we cannot add any more toggleable preferences without a stupid workaround, or a preference refactor (maybe ill do it in the future)

**What did you expect to happen**: 
Preferences to save above that number

**What happened instead**:
It didnt even toggle properly

**Why is this bad/What are the consequences**:
We are unable to save any more preferences

**Steps to reproduce the problem**:
```dm
#define AATESTING 16777216

/client/verb/aatesting()
	set name = "AA Testing"
	set category = "Special Verbs"
	prefs.toggles ^= AATESTING
	to_chat(src, "Test toggle [(prefs.toggles & AATESTING) ? "on" : "off"]")
```
![image](https://user-images.githubusercontent.com/25063394/86139409-99df9580-bae7-11ea-8ca7-b41339a3e178.png)

**When did the problem start happening**:
When numpad targetting became a toggle

**Extra information**:
JSON preferences or savefiles are the way to fix this.

**Comment by FreeStylaLT** [comment]
you could say the flags ran out.. bit by bit.

**Comment by Spacemanspark** [comment]
This is a Bit of a problem, I do say

**Comment by KasparoVy** [comment]
Son of a bit-ch! Json ftw
