### ISSUE TITLE
Carded AI with transceiver off can still use binary chat

### ISSUE THREAD

**Issue by warior4356** [ParadiseSS13/Paradise#13776]
Unsure if this is working as intended. 

If so, possibly reevaluate this as it makes stealing the AI near impossible for a non-traitor as they can't subvert the AI and under most lawsets a freeform law would be unable to override self-preservation laws, so making an upload won't actually work.

**Comment by Shockpoint** [comment]
I believe this is intended.

Part of the risk of stealing the AI is that you give away your position by doing so, or so I remember players being told.

**Comment by enderman51505** [comment]
They can also use PDA iirc

**Comment by matttheficus** [comment]
Intended behavior.
