### ISSUE TITLE
Automenders Reporting No exposed flesh or thin material even when there si

### ISSUE THREAD

**Issue by Samman166** [ParadiseSS13/Paradise#13778]
**Issue Description**: Automenders were not working on people saying that there was no exposed flesh or thin material even though they were stripped completely this seemed to have a correlation with people who got powers from DNA vaults

Could not heal people with automenders saying there was no exposed flesh or thin material even though they were stripped seemed to be an issue with gauze too. Seemed to only be an issue on people who got powers from DNA vaults

**What did you expect to happen**: 

Be able to heal people quickly with the menders once stripped of any heavy clothing like exosuits

**What happened instead**:

We were not able to heal people more importantly corpses quickly enough so we had to rely on cloning making people wait longer to be revived and taking the fun out of stabilizing critical patients patches were in short supply and other healing items like gauze didnt work either 

**Why is this bad/What are the consequences**:

Players had to wait longer to be revived and it was making medical less fun because we could not try and save dead people with defibs and try to stabilize them and instead had to rely on cloning entirely and mass produce patches which were acting too slow for the amount of corpses

**Steps to reproduce the problem**:

Get all the DNA vault powers 
Take damage
Take off any clothing that would interfere normally
Use automenders or other medical items requiring exposed flesh 

**When did the problem start happening**:

After using a load of DNA vaults too get powers think i got all of them so might be just one specific one or all of them

**Extra information**:

Not sure if there was a problem with gauze just heard it from others and im pretty sure the issue was related to vault powers

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/blob/210f8badf474adbd9f710a5f22fc19bccf4516e7/code/modules/station_goals/dna_vault.dm#L311

The vault will give the pierce immune trait if you go for armor, which will, in fact, make them impervious to certain healing methods.
