### ISSUE TITLE
Transforming level 7 virus

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#13787]
**Issue Description**:

There was a random virus, which did have a name and cure of saline and spreading by blood. For some reason, it did transform into an unknown virus that spread by contact and had a different listed cure, acording to VV.

**What did you expect to happen**: 

The virus to stay the same and let itself be cured.

**What happened instead**:

The virus seems to have needed one cure, but another was shown.

**Why is this bad/What are the consequences**:

Medbay would need to test every potential cure to heal a virus if it changes like that, as no reading can be trusted.

**Steps to reproduce the problem**:

It should be reproducable by a virus that has theese symptoms, but may be spawned by the event: /datum/symptom/itching /datum/symptom/sneeze  /datum/symptom/cough /datum/symptom/shivering /datum/symptom/headache
Name it, and in the first stage, it'll have that name. Later, it'll have the same ID, but different cure and unknown name.

**When did the problem start happening**:

Unknown.

**Extra information**:

Was checked on with VV and SDQL to get all /disease/advance, SDQL found only one of the named virus remaining, which was on the carrier of the event, staying at stage 1, many instances of the unknown version with the same symptoms, but other cure and spread. Did VV one infected early, they had the named version, but later, it switched to unknown with the different cure and spread, which i belive was caused by the raised stage.

**Comment by farie82** [comment]
Because of line https://github.com/ParadiseSS13/Paradise/blob/2a055969ee7fdf9b5fd8f5cb6559f2458393e448/code/modules/events/disease_outbreak.dm#L14
The properties are randomly set the first time the virus is made. Then once it spreads the actual values get calculated making it a different virus

**Comment by farie82** [comment]
There is way more wrong in the code. I'll put a PR up in a bit. Thanks for the report!
