### ISSUE TITLE
Using a Syringe Gun or at least a Rapid Syringe Gun with Hulk will delete syringes inside.

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13780]
**Issue Description**:

If you have hulk or the trait that prevents you from using guns it will delete the syringes inside as if they have been fired and injected into someone.

**What did you expect to happen**: 

I expected to not be able to fire it and still have the syringes inside.

**What happened instead**:

It ate my syringes, sent them to the shadow realm and won't return them to me.

**Why is this bad/What are the consequences**:

Making expensive and time consuming chemicals to only forget you have hulk on you or a no gun trait will cause you to lose them and I believe this was a oversight.

**Steps to reproduce the problem**:

Step 1. Get Hulk or the trait to be unable to use guns.
Step 2. Load Syringe Gun with Syringe
Step 3. Try to shoot it to find you can't.
Step 4. Try to unload it to find out there is no syringe inside.
Step 5. Cry that you somehow removed matter from reality despite it being impossible to do so.

**When did the problem start happening**:

No idea when but I found it out today. Might've been in the game for a long time for all I know.

**Comment by dearmochi** [comment]
Technically the syringe is still loaded but considered as chambered (internally), meaning you can't unload it. I'll push a PR shortly to fix that weirdness
