### ISSUE TITLE
Dark Space

### ISSUE THREAD

**Issue by FireFlashie** [ParadiseSS13/Paradise#1379]
![image](https://cloud.githubusercontent.com/assets/10612280/8327767/a88d1072-1a73-11e5-9d45-0b802f202fd8.png)

**Comment by FalseIncarnate** [comment]
Should be fixed by #1365

Server simply isn't patched yet to my knowledge.

**Comment by FireFlashie** [comment]
This is latest Paradise code.

**Comment by TheDZD** [comment]
@PJB3005

**Comment by Fox-McCloud** [comment]
![bright](http://i72.photobucket.com/albums/i169/Fox_P_McCloud/brigt_zpsrijf4tsy.png)

I'm unable to reproduce this.

**Comment by Spacemanspark** [comment]
Glance at the live server.
Also, it does look like it's the same deal on your end, look to the left.

**Comment by Fox-McCloud** [comment]
I'm guessing this is a server configuration issue revolving around starlight and not necessarily a coding issue--PJB will have to look into it further.

Also, that's occurring because SS13 was designed for 15x15 and we have 17x17 so...yeah.

**Comment by PJB3005** [comment]
Alright i'll see what's causing this
