### ISSUE TITLE
Bug with Using Wall-Mounted and Standard Defibrillator on Vox and Slimepeople (perhaps other races too)

### ISSUE THREAD

**Issue by Elasmobranchii** [ParadiseSS13/Paradise#13790]
**Issue Description**:

When attempting to use the wall-mounted or standard defibrillator to revive a Vox or Slimeperson, they are unable to be targeted.

**What did you expect to happen**: 

Well, normally the defibrillator will go through the animation, and either revive the body or give you a message indicating what needs to happen before they can be revived.

**What happened instead**:

Nothing. I was unable to interact with Vox or Slime people using the defibs.

**Why is this bad/What are the consequences**:

Vox/Slimeperson unable to be revived short of using SR.

**Steps to reproduce the problem**:

Should be reproducible on a dead Slimeperson/Vox. Numerous doctors were having this issue.

**When did the problem start happening**:

For me, the round starting at 1:36 AM PDT on 7/9/2020.

**Extra information**:

Not that I can think of.

**Comment by dearmochi** [comment]
What do you mean by "unable to be targeted"? I am unable to reproduce this issue - I am able to defibrillate both Slime people and Vox normally

**Comment by Elasmobranchii** [comment]
What I mean by unable to target is when holding the defib panels, targeting the chest, and clicking the mob sprite nothing happens. I was able to reproduce the issue on slime people by closely replicating the scenario:

- I Killed the slime person via brute damage to the chest, and removed the heart. Attempted to use both the standard and wall-mounted defib. Expected that it would beep and spit out a failure message about a missing heart. Nothing happened.

-Transplanted heart back into slime person, tried both defibs again. Expected that it would beep and spit out a message about tissue damage. Nothing happened.

- Brought brute damage down to revivable threshold, tried defibs again. Expected that it would zap and resuscitate. Nothing happened.

I was able to replicate this process on vox, humans, and vulpkanin too. Oddly enough, the CMO's compact defibrillator does not seem to be having this issue (though it did spit out a message about cardiac arrythmia after the transplant. I dont know how a dead person can be going through a heart attack.) Substituting a cybernetic heart for the original heart still had the same issues. I also noticed that the standard defib was having the same bug on humans (beep doesnt happen/no failure message) when the heart is necrotic.

**Comment by moxian** [comment]
I tried to reproduce this on a local test server:
- start surgery
- remove heart
- immediately defib

and ran into runtime at https://github.com/ParadiseSS13/Paradise/blob/914e1493cd3c9827644985ac8876b921ad897560/code/game/objects/items/weapons/defib.dm#L395 `Exception has occurred: Cannot read null.status`

I'm not sure this is the root cause, but it's at least something that we should fix.

**Comment by DGamerL** [comment]
All instances of this have been properly nullchecked! Thanks for making the report!
