### ISSUE TITLE
Mining: Production Machine Console eats ID cards

### ISSUE THREAD

**Issue by thatdanguy23** [ParadiseSS13/Paradise#13813]
**Issue Description**:
The "production machine console" that sits in the Processing Area of the Lavaland mining base will take an ID card, and because it has no slot, cannot return it.

**What did you expect to happen**: 
The console to act like a regular ORM.

**What happened instead**:
It eats ID cards and has no point system or card slot.

**Why is this bad/What are the consequences**:
A miner attempted to use it and fed it their ID card, only to have it permanently removed from their person.

**Steps to reproduce the problem**:
Put an ID card in the machine, either before, during or after smelting.

**When did the problem start happening**:
Unknown, but the first report was today.

**Extra information**:
Norwest can verify.

**Comment by SteelSlayer** [comment]
I'm unable to reproduce. When I click the machine with my ID, it just hits the machine with it. And the machine doesn't have `attackby` code that has anything to do with IDs

This is the console you're talking about correct?
![image](https://user-images.githubusercontent.com/42044220/89129362-7337c480-d4c2-11ea-85fc-5c69de96f4ef.png)

**Comment by thatdanguy23** [comment]
odd. it was that console, yes. did you try in all different intents? not sure if it has anything to do with it.

**Comment by SteelSlayer** [comment]
Yeah I did, it worked the same on all intents.
