### ISSUE TITLE
Prison break moderate event does not stop proccing

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#13815]
**Issue Description**:
The moderate prison break event when it procs constantly recycles and repeats.

**What did you expect to happen**: 
For the event to proc once and then go on cooldown to the bottom of the event list with low priority.

**What happened instead**:
The virus continually procced nonstop until it was manually disabled.

**Why is this bad/What are the consequences**:
Security alert, security alert, security alert, security alert, security alert, security alert.

**Steps to reproduce the problem**:
Que up the prison break moderate event, let it tick and spam messages nonstop.

**When did the problem start happening**:
First time I noticed it was on 7/11/2020.  No earlier reports on it as far as I know.

**Extra information**:

![ZVwKhJH](https://user-images.githubusercontent.com/24213815/87252668-8c58d280-c43a-11ea-8f3a-f7c7a3b69197.png)

Each time it procs it clones the event in the event listing, after I disabled it.

![breakevent](https://user-images.githubusercontent.com/24213815/87252732-05582a00-c43b-11ea-85fa-953aba315ed6.png)

**Comment by Kyep** [comment]
@Denthamos Can't replicate this. Can you? If not, close?

**Comment by SabreML** [comment]
Probably fixed by #15203
