### ISSUE TITLE
Invisible, unremovable ghost facehuggers

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#13810]
**Issue Description**:
A player had a dead facehugger shown in his mask slot, but could not remove it after getting face hugged. other players didn't see the facehugger. He was also blind and other people didn't see the facehugger on his face.

**What did you expect to happen**: 
The facehugger can be removed

**What happened instead**:
It stayed until the person was admin revived

**Why is this bad/What are the consequences**:
You're forever blind and have a mask slot filled

**Steps to reproduce the problem**:
No idea, sorry.

**When did the problem start happening**:
Sometimes after xenos were removed from rotation

**Extra information**:

**Comment by Fox-McCloud** [comment]
This sounds like a runtime error or qdeletion bug of some variety. Shame I wasn't there for it; that would have been interesting to diagnose.

**Comment by TDSSS** [comment]
Yeah, sorry. Due to the xeno larva bug we decided to end the round early with a shuttle call.

**Comment by Contrabang** [comment]
possibly related to #19541

**Comment by Spaghetti-bit** [comment]
This was fixed with a BYOND update…. 513? I think?
