### ISSUE TITLE
Pipe bursting procs and related vars are never used/reached

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#13826]
**Issue Description**:
the maximum_Pressure, fatigue_pressure and alert_pressure vars on atoms machines are completely useless and never used. The check_pressure proc which is supposed to access them has no way of getting called.

This means pipes, which are supposed to burst at certain pressures...simply don't

**What did you expect to happen**: 
For pipes to burst if over their maximum pressure

**What happened instead**:
Nothing happens

**Why is this bad/What are the consequences**:
Never used or accessed procs or vars are bad, pipes taking infinite pressure when they're supposed to burst at certain points are bad, too.

**Steps to reproduce the problem**:
Fill a pipe with more than the 70 atmospheres worth of pressure it's supposed to take and notice it doesn't burst.
Alternatively, do a code search for check_pressure and notice how it's never called (the only mention being a proc with the same name in KA code that does something completely differently)

**When did the problem start happening**:
Well, this code is like 5 years old, and I don't recall anyone ever mentioning pipe bursting.

**Extra information**:
Probably easier to just...remove pipe bursting since everyone is so used to this?

**Comment by Spaghetti-bit** [comment]
Fixed by MILLA
