### ISSUE TITLE
Runtime the cat kills blobs by itself in seconds

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#13823]
**Issue Description**:
Runtime can Splat() blob-infected mice, which sets them to stat = DEAD without calling death(), and thus without triggering the blob mouse's transformation into a blob.

**What did you expect to happen**: 
Runtime (or anything else!) kills the infected mouse.
Mouse instantly becomes blob on death.

**What happened instead**:
Runtime Splat()ed mouse. Mouse died. No blob was created.

**Why is this bad/What are the consequences**:
Runtime can single handedly kill a blob before it even bursts.

**Steps to reproduce the problem**:
1) Spawn /mob/living/simple_animal/mouse/blobinfected and put yourself in control of it
2) Spawn /mob/living/simple_animal/pet/cat/Runtime
3) Wait a few seconds
4) You are now Splatted by runtime, annihilator of blobs, and never got a chance to live up to your blobby potential

**Extra information**:
Does https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/friendly/mouse.dm#L83 even need to exist? Why not just call .death()? That Splat() proc is terrible quality code littered with "src.". I doubt we'd accept it nowadays.

**Comment by Spacemanspark** [comment]
Runtime is legend, and removing this feature would bring great dishonor to their name.

**Comment by Gatchapod** [comment]
Do you ever wonder how many blobs died this way, while players thought there was no midround antag?

**Comment by Spacemanspark** [comment]
Likely not many tbh

**Comment by BakKeener** [comment]
I spawned in that room during a green terror event I believe? I died so quickly and finding out I didn't just burst right there and then was very confusing until I re-entered my corpse and saw the timer was still ticking. Then I swiftly smited cloning for their sins of having runtime have that code still.
