### ISSUE TITLE
Vamps igniting under a shower dont extinguish

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#13820]
**Issue Description**:
A vampire that is fed holy water will ignite and all that when fed holy water, but if he ignites while already under a shower, he wont extinguish unless the shower is cycled off and on

**What did you expect to happen**: 
the vamp to briefly ignite and extinguish right away at the next cycle

**What happened instead**:
vamp stays on fire if nothing is done

**Why is this bad/What are the consequences**:
seems unintended if you ask me

**Steps to reproduce the problem**:
place a vamp under a shower and feed holy water until it ignites. when on fire, turn on shower. wait until it procs to ignite again, shower wont extinguish him again

**When did the problem start happening**:
iunno noticed it yesterday

**Extra information**:
cycling the shower off and on still extinguishes

**Comment by Gatchapod** [comment]
Unable to reproduce.
Vampire ignites and gets immediately extinguished repeatedly, until they die from flat burn damage caused by the holy water.

Could you try to recall the steps more precisely? Which shower or what was its setup?

**Comment by pinatacolada** [comment]
it was an extra shower built in brig, or maybe it was stolen from somewhere else, but it was not mapped in thats for sure
the guy was buckled to a chair but i dont think that matters
feed a craptone of water to a vamp buckled to a chair, wait until it ignites, turn shower on (it extinguishes him now), leave shower on, wait until it reignites, when it does it wont extinguish despite being under the shower

**Comment by Gatchapod** [comment]
Alright. After building a shower in the processing, it behaves as described.

**Comment by matttheficus** [comment]
Cannot reproduce on testserver, also older than newvamp.
