### ISSUE TITLE
AI tickets.

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#13837]
**Issue Description**:

The AI can take a ticket for the HoPs line, which'll appear on the AI cores.

**What did you expect to happen**: 

The AI to either be unable to get a ticket, or the ticket machine to drop the ticket infront of it.

**What happened instead**:

A ticket was teleported to the AI core.

**Why is this bad/What are the consequences**:

Tickets shouldn't be able to teleport

**Steps to reproduce the problem**:

Be AI, camera over the HoPs office, get a ticket.

**When did the problem start happening**:

Likely since the ticket machine was added

**Extra information**:

Anything that does it remotely may be able to do it, at least borgs can do it.

**Comment by Spacemanspark** [comment]
Time to reserve my spot in line for all access requesting as the AI

**Comment by Nazsgull** [comment]
Will try to fix this tomorrow. It's gonna be my first PR so please bear with me. Not sure on whether to let AI extract a ticket so it falls in front of the machine or to not even be able to interact with it.
