### ISSUE TITLE
Space ruin relays are all unlinked

### ISSUE THREAD

**Issue by Balthusdire** [ParadiseSS13/Paradise#13836]
**Issue Description**:
All space space ruin relays start unlinked.

**What did you expect to happen**: 
I expected that relays at places like the DJ station or the prepper base base would start linked.

**What happened instead**:
The relays are all unlinked right from the start.

**Why is this bad/What are the consequences**:
Most people who will come across these relays will not have the linking password and so they relays become unusable.

**Steps to reproduce the problem**:
On round start go to any space based relay in any space ruin.

**When did the problem start happening**:
Post space ruin rework.

**Extra information**:

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/87441668-43944b80-c5eb-11ea-9a57-0395f8214cd1.png)
Tested in singleplayer, cannot reproduce

**Comment by Balthusdire** [comment]
Alright I'll have to take a look.

**Comment by Balthusdire** [comment]
Closing, looks like maybe I got really unlucky and one round someone unlinked them all before me.
