### ISSUE TITLE
Double space ruins

### ISSUE THREAD

**Issue by lolzyking** [ParadiseSS13/Paradise#13845]
**Issue Description**: Two copies of the survivor station space ruin spawned in space

**What did you expect to happen**: only one to be able to spawn

**What happened instead**: two spawned

**Why is this bad/What are the consequences**: confusion, lots of confusion

**Steps to reproduce the problem**: pray to rngesus

**When did the problem start happening**: unknown 

**Extra information**:

**Comment by Kyep** [comment]
I believe this refers to the theta station ruin.

**Comment by AffectedArc07** [comment]
I never touched this ruin during the ruin rework so I believe this to have always been an issue

**Comment by lolzyking** [comment]
correct theta station, two copies spawned, survivors joining as them from the mob spawners tab cascaded, Engineer joins theta 1, engineer joins theta 2, ect.
