### ISSUE TITLE
Smokescreen IPC

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#1384]
When a smokescreen dissipates IPC's still see everything darker
![capture](https://cloud.githubusercontent.com/assets/12041669/8338975/541a4f78-1a82-11e5-82e3-1c03f92e399c.PNG)

**Comment by FalseIncarnate** [comment]
That appears to be a damage overlay. When damaged, you will typically begin to get a "tunnel-vision" effect on your screen that gets worse with more damage.

Smoke has been known to (in some cases) cause some OXY damage to IPCs which is unable to be repaired. Based on the age of this report, the chance of toxins damage is also a possible cause.
Please report this in-game if it occurs again so an admin can check your vars to see if it is possibly related to damages, and I will attempt to reproduce this locally when I get the chance to confirm/deny my theory.
