### ISSUE TITLE
Lavaland weather noise ignores ambience preference

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#13843]
**Issue Description**:
After you turn off "hear/silence ambience" under Preferences, you still hear the howling wind of lavaland.

**What did you expect to happen**: 
Turning off this preference should silence the annoying wind.

**What happened instead**:
It doesn't. I still hear the wind.

**Why is this bad/What are the consequences**:
The wind is long, loud, and annoying. It should be possible to turn it off.

**Steps to reproduce the problem**:
See description.

**Extra information**:
Some may argue that the wind noise is necessary to tell miners when to seek shelter.
This is wrong, for two reasons:
- The player can be notified about ash storms in other ways, such as a message in chat, or a pop-up notification in the top right of the screen.
- These other notification methods are in fact better if you want a reliable notification, as they won't be missed by players who also have loud music going, are in a busy room, or are simply deaf or have sound muted.

**Comment by Fox-McCloud** [comment]
This isn't a bug and is fully intended.

This isn't an aesthetic choice, nor should it be; this isn't like ship ambience where it's just fluff and just there for flavor. It has an important gameplay aspects that goes along with it; players need to have this information telegraphed to them, and it's it's not just for funsies. Sounds that have gameplay implications and impacts are not toggled for a reason. You can't toggle the sound guns make or the sound mobs make when you break their bones--these are all gameplay aspects.

It's the same for lavaland.

It also shoehorns people into having to have ambience on just to hear a very important gameplay sound--when some people don't want to hear just fluff sounds.
