### ISSUE TITLE
Diagonal walking can increase speed

### ISSUE THREAD

**Issue by Tarhalindur** [ParadiseSS13/Paradise#13840]
**Problem Description**:
If you're adjacent to a wall and diagonally walk up against it (for instance, stand a tile up from a wall and walk right and down), your speed will increase noticeably.

**What did you expect to happen**: 
I would walk at normal speed.

**What happened instead**:
I walked at a significantly higher speed than is normal for both normal and diagonal walking.

**Why is this bad/What are the consequences:**
You should not be able to run faster by using a secret trick.

**Steps to reproduce the problem**:
1. Be next to a wall
2. Walk normally next to the wall and observe speed
3. Walk diagonally next to and into the wall and observe speed

**When did the problem start happening**:
Not sure. Doesn't seem to be really recent, though.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I don't think this is related to anything else.

**Comment by Fox-McCloud** [comment]
This is an illusion; what you're noticing is an initial acceleration difference; you're basically cancelling out the smooth, so your sprite initially juts forward faster than you're actually moving, but then you pause for a little.

I've tested this numerous ways, numerous times, and holding up and to the right/left against a wall means you arrive at your destination at exactly the same amount of time as regular walking. Even if you hold up and over and left go and re-press up again, it also gives a similar "feel", but you're still moving at the same *actual* speed.

It's like if a car moves at 60 mph then stops suddenly only to restart a bit later---vs a car that is traveling at 30 mph consistently.

They both arrive at their destination at the same time,but one "looks" initially like its moving faster.

**Comment by Shockpoint** [comment]
And here I thought SS13 had evolved into DOOM/Quake.

**Comment by Spacemanspark** [comment]
HOPHOPHOPHOPHOP
