### ISSUE TITLE
Vox organs die

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#13858]
**Issue Description**:

Vox organs decay to death after death

**What did you expect to happen**: 

For vox organs not to decay to death

**What happened instead**:

Vox organs decayed to death

**Why is this bad/What are the consequences**:

When you eventually revive the vox with every organ dead, they walk really slow.

**Steps to reproduce the problem**:

Step 1. Be vox Step 2. Die Step 3. Wait 45 minutes Step 4. Fix vox and revive with sr. Step 5. Confirm in advanced body scanner

**When did the problem start happening**:

I first learned about it about a week ago, when an errant bomb turned me into a vox nugget, when i was revived after being 'cloned' twice, I had a huge speed penalty that seemed to originate in dead organs.

**Extra information**:

Vox organs were not supposed to decay, afik this is yet to be changed.

**Comment by TheSardele** [comment]
Fairly certain that is intended. SR overrides the decay immunity.

**Comment by KasparoVy** [comment]
"Man we got fleeced so hard." lol... Yeah, I still feel it.

**Comment by ppi13** [comment]
Well, that is silly, might as well remove the decay immunity and just use stable reagent + brain transplant instead =\
