### ISSUE TITLE
Bug: Minebots take Stamina damage.

### ISSUE THREAD

**Issue by Dannboi** [ParadiseSS13/Paradise#13859]
**Issue Description**:
Minebots, which are considered to be small robots, take stamina damage and can be stunned, despite functioning similiarly to borgs and drones. They are subject to stuns from both collapsible batons and rubber bullets, which causes them to oddly (but humorously) freeze up for a couple of seconds in place, showing no actual response to the effect other than a loss of control from the player.

**What did you expect to happen**: 
I expected minebots to behave similiarly to other simple mobs, but instead was forced to sit idle during otherwise odd stuns.

**What happened instead**:
Every time minebot was stuck with rubber bullet or collapsible baton, lost control of mob for several seconds, as though being a humanoid stunned in that manner.

**Why is this bad/What are the consequences**:
This is an odd exception that does not seem to have a reason to exist.

**Steps to reproduce the problem**:
As a player controlled Nanotrasen minebot, be struck by a collapsible baton or a rubber bullet.

**When did the problem start happening**:
Current, as far as I am aware.

**Extra information**:
Perhaps there has been a change to simple mobs that I did not know about? If so, I apologize! It still seems odd to happen to a "robotic" mob, however.

**Comment by Fox-McCloud** [comment]
Just tested this; they don't take any stamina damage; neither do any other simple mobs--their stamina damage coefficients are all zero.

*most* simple mobs can't be stunned/weakened, but there *are* exceptions; mining bot is one of those intentional exceptions.

Not a bug and working as intended.
