### ISSUE TITLE
[Sprite missing] Wrapping Paper Missing

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1385]
When you wrap something in packaging it appears as a package. But if you use wrapping paper on it. The item disappears. If you Alt-Click on the square you are standing on. It will appears a "Object" or something similar. Putting the item in your backpack means you lose an item slot as it's impossible to remove.

**Comment by KasparoVy** [comment]
I forgot who told me this, but the exact same thing happened to me while mining. I mined a strange rock and got a spriteless object-- that I proceeded to pick up with right click and stow in my pack. What you have to do is take the pack in your hands, right click, and empty on the floor (I think that's how you do it. Either way, there is a method for emptying your whole pack at once). Once done, just don't pick up the spriteless 'object'
