### ISSUE TITLE
New shuttle is so fat you can see beyond the horizon that you are suppossed to see:

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#13856]
**Issue Description**:

![image](https://user-images.githubusercontent.com/35972878/87701896-ea6a1a80-c798-11ea-8b52-fd966f9ed77c.png)

**What did you expect to happen**: 

to see the moving trough space animated tiles, and not normal space tiles out of window, while traversing trough space inside shuttle 

**What happened instead**:

I can see static space next to moving space

**When did the problem start happening**:

Since merging #13727

**Extra information**:

It's visible as ghost, didn't confirmif I can see the same as crew member.

**Comment by AffectedArc07** [comment]
Damn, I didnt spot this because of parallax

**Comment by KasparoVy** [comment]
When dat ass so thicc it causes bluespace distortion

**Comment by BakKeener** [comment]
the freaking parallax, not only does it break while orbiting people but it also prevents our coders from noticing this.

**Comment by Henri215** [comment]
Tested and looks like the issue has been fixed by https://github.com/ParadiseSS13/Paradise/pull/21260.
Thank you for reporting.
