### ISSUE TITLE
Bug Report: Meat hook interaction with Holopara

### ISSUE THREAD

**Issue by Dannboi** [ParadiseSS13/Paradise#13866]
**Issue Description**:
Throwing a meathook at a holoparasite will cause an odd interaction that (essentially) instakills both holopara and host. It appears to cause damage every tick and kills the host almost instantly.

**What did you expect to happen**: 
Hook hits holopara, does single pull damage, perhaps dislocates holopara?

**What happened instead**:
Hook remained attached to holopara and filled the screen with bugs and damage counters. User died instantly, as did holopara, and chain remained floating in air.

**Why is this bad/What are the consequences**:
Serious balance issues as well as lagging the game for a few moments.

**Steps to reproduce the problem**:
Summon Holopara (This instance, it was ranged, which might have an effect) and have another person throw the meat hook at them. 

**When did the problem start happening**:
Current. I witnessed it literally fifteen seconds ago.

**Extra information**:
Ranged Holoparasite, Moi the security officer. The attacker was a vampire miner wielding a meat hook, who had previously pulled Moi twice before the holoparasite summoned to react. Moi died nearly instantly, and the damage done was insane. Chain remained in the air for about fifteen seconds afterwards, as well, suspended where the holoparasite had died.

**Comment by farie82** [comment]
First one I could actually repro.
![image](https://user-images.githubusercontent.com/15887760/87820065-a72dab80-c86d-11ea-95a3-aa6639aa9364.png)
I'll investigate

**Comment by farie82** [comment]
Also be sure to not include current round information in issues. The same rules apply as in the discord
