### ISSUE TITLE
PM link in admin ticket does not work

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#13876]
**Issue Description**:
A player opened a ticket, when I click on his name to reply I get 
Error: Private-Message: Client not found.

However, the player is still connected and even playing as the same mob as when he sent the ahelp. I can PM him just fine via the player panel or similar

**What did you expect to happen**: 
To be able to PM him from the ticket window

**What happened instead**:

I couldn't and had to search for him via player panel

**Why is this bad/What are the consequences**:
Inconvenient

**Steps to reproduce the problem**:
No idea, sorry

**When did the problem start happening**:

**Extra information**:

**Comment by TheSardele** [comment]
I think this happens when the player dis- and reconnects. After they reconnect, previous PM links don't work anymore.
