### ISSUE TITLE
Tesla arcs do not destroy APCS

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13873]
**Issue Description**:

Tesla arcs do not destroy apcs, causing them to explode each time they are shocked, but not break and disappear.

**What did you expect to happen**: 

For the APC to blow up and be destroyed / deleted

**What happened instead**:

It explodes, but is not destroyed

**Why is this bad/What are the consequences**:

An apc that constantly explodes when shocked but does not disappear doesn't make sense, and is shockingly dangerous 

**Steps to reproduce the problem**:

Loose the tesla
Wait for it to get near an APC
Watch as the apc never breaks and constantly explodes

**Comment by Spacemanspark** [comment]
APCs are literal deities

**Comment by Alex1222003** [comment]
The red screen represents the anger.
