### ISSUE TITLE
The Singularity improperly "tears" reinforced floors, generating infinite rods

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#13877]
The Singularity appears to affect reinforced floors in a very buggy way, as 1 metal rod is generated from the tiles each pull tick, but the floors are never actually ripped off or destroyed.

**What did you expect to happen**: 

Reinforced flooring probably shouldn't be "ripped" by the singularity's pull. Currently there seems to be some sort of buggy behaviour where the singularity does in fact attempt to remove that flooring, which is made with rods, but the floor is never actually removed.

**What happened instead**:

Infinite metal rods were spawning from each reinforced floor tile, without the tiles being actually destroyed.

**Why is this bad/What are the consequences**:

a) It's buggy behaviour
b) Infinite materials!
c) ... that can promptly fly into the Singularity, feeding it and causing it to grow

**Steps to reproduce the problem**:

- Place reinforced floors somewhere near the Singularity's containment field.
- Set up Singularity engine.
- Watch as an endless stream of rods fly into the Singulo.

**When did the problem start happening**:

I've no idea, people don't often build reinforced floors around the singulo for no reason

**Extra information**:

Screenshot of rods flying into the singulo.

Unrelated to this issue, but I left the PA at 2 while testing this for about 30 minutes and the Singulo's energy level was barely above 700 even with the rods flying into it. I feel like something might be wrong with that (IIRC the stage3 (5x5) is around ~500, and stage4 (7x7) is around 1000).

![image](https://user-images.githubusercontent.com/7857084/87881528-19cb9200-c9fa-11ea-8a69-5a7c637c276b.png)

**Comment by SteelSlayer** [comment]
Investigated this a bit, not really sure what's going on and don't have the know how to figure it out. But I did find out the cause... sort of. Here is a ghetto call stack:

First this is called:
```js
/turf/simulated/floor/singularity_pull(S, current_size)
	..()
	if(current_size == STAGE_THREE)
		if(prob(30))
			if(floor_tile)
				new floor_tile(src)
				make_plating()
```
Game calls `make_plating()`. Which calls: 
```js
/turf/simulated/floor/proc/make_plating()
	return ChangeTurf(/turf/simulated/floor/plating)
```
Which calls `ChangeTurf`:
```js
/turf/simulated/floor/ChangeTurf(turf/simulated/floor/T, defer_change = FALSE, keep_icon = TRUE, ignore_air = FALSE)
	if(!istype(src, /turf/simulated/floor))
		return ..() //fucking turfs switch the fucking src of the fucking running procs
	if(!ispath(T, /turf/simulated/floor))
		return ..()
```

The issue is that it fails the second if check here. What I don't understand is that
`if(!ispath(/turf/simulated/floor/plating, /turf/simulated/floor)` shouldn't succeed because plating IS a subtype of floor, but it succeeds and thus calls `return ..()` preventing the floor from reverting to a plating.
