### ISSUE TITLE
Bad Roundstart Tips

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#13892]
Not exactly a bug per se, but a **lot** of the tips are plain wrong, outdated or inaccurate. I've gone over the list and while I can't claim to know everything about the game I've identified and tested a bunch of glaring ones.

Posting this an issue report in case people want to add to the list before someone PRs a correction. The number is the line where the tip is in the tips.txt file

----------

_1. Where the space map levels connect is randomized every round, but are otherwise kept consistent within rounds._
Weirdly worded. Probably wrong considered space has randomized ruins now too.

_12. You can grab someone by clicking on them with the grab intent, then upgrade the grab by clicking on them once more. An aggressive grab will momentarily stun someone, allow you to place them on a table by clicking on it, or throw them by toggling on throwing._
Nope. We upgrade grabs by "using" the grab itself (aka clicking on the REINF icon in your hand or pressing Z in hotkey mode). I also don't think our aggressive grab stuns.

_24. A thrown glass of water can make a slippery tile, allowing you to slow down your pursuers in a pinch._
We do not have shattering reagent containers on throw.

_39. As a Medical Doctor, you must target the correct limb and be on help intent when trying to perform surgery on someone. Using disarm intent will intentionally fail the surgery step._
I do not think this works, as far as my tests went at least. You just hit them with the surgical tool.

_40. As a Medical Doctor, corpses with the "...and their soul has departed" description no longer have a ghost attached to them and aren't revivable or clonable._
Not necessarily "wrong" but I'd change it to they "likely" aren't revivable. Sometimes ghosts can come back.

_53. As a Scientist, you can disable anomalies by scanning them with an analyzer, then send a signal on the frequency it gives you with a remote signaling device, or if researched, hit the anomaly with an anomaly analyzer. This will leave behind an anomaly core, which can be used to construct a Phazon mech or reactive armors!_
We unfortunately don't have Anomaly Analyzers. Reactive Armors are also not craftable.

_66. As an Engineering Cyborg, you can attach air alarm/fire alarm/APC frames to walls by placing them on the floor and using a screwdriver on them._
Incorrect. Paracode engiborgs use their Magnetic Gripper to hold and place objects like those.

_67. As a Medical Cyborg, you can fully perform surgery and even augment people._
Sadly false. Medical borgs can't hold organs, implants and other bits and pieces, limiting their ability to perform surgery.

_76. As an Engineer, you can repair windows by using a welding tool on them while on any intent other than harm._
Actually you have to specifically be in help intent to repair windows.

_79. As an Engineer, you can pry open secure storage blast doors by disabling the engine room APC's main breaker. This is obviously a bad idea if the engine is running._
Technically the storage blast doors in the Cyberiad are in the Secure Storage area, not the Engine room. You'd need to turn off the power to the APC inside storage to be able to crowbar them open. Aditionally, you only need to turn off the Enviroment power channel Off, not the whole APC.

_91. As a Security Officer, your sechuds or HUDsunglasses can not only see crewmates' job assignments and criminal status, but also if they are mindshield implanted. You can tell by the flashing blue outline around their job icon._
The flashing outline is green, not blue.

_114. As a Botanist, you can combine production trait chemicals just like a Chemist. Chlorine (blumpkin) + radium and phosphorus (glowshrooms) equals unstable mutagen!_
This is TG's unstable mutagen recipe. We use Chlorine and Plasma (blumpkin) + Radium (glowshroom).

_116. As the Chef, you can rename your custom made food with a pen._
I do not think this is working at the moment, though the prompt to rename foods shows up so it's mostly a bug and this hint is fine.

_123. As a Cargo Technician, you can order contraband items from the supply shuttle console by de-constructing it and using a multitool on the circuit board, the re-assembling it._
The functionality to multitool the board exists but I *think* it currently does nothing. The hidden cargo supply packs are unlocked by emagging the console.

_124. As a Cargo Technician, you can earn more cargo points by shipping back crates from maintenance, liquid containers, plasma sheets, rare seeds from hydroponics, and more!_
Liquid containers (water/fuel tanks) don't give points.

_125. As a Shaft Miner, the western side of the Asteroid has a lot more rare minerals than on the east, but is a lot more dangerous._
What Asteroid?

_133. As a Traitor, plasma can be injected into many things to sabotage them. Power cells, light bulbs, welding tools, cigars and e-cigs will all explode when used._
Welding tools can't be filled directly. Cigars might need to be revised, code wise (explosion seems very weak and some cigs have no space to inject plasma), but the tip should be correct in that regard.

_162. The Chaplain can bless any container with water by hitting it with their bible. Holy water has a myriad of uses against both cults and large amounts of it are a great contributor to success against them._
"Both cults". No clock cults here.

_173. As a Revenant, your Defile ability removes holy water from tiles in a small radius, along with salt, allowing you to reclaim the station from the chaplain if they've been covering the station in holy water. It can also be used to open morgue trays!_
I don't think we can have tiles of salt here? I tried to spray salt from a spray bottle and it didn't seem to block revenants.

_177. As a Revenant, fastmos is your friend. Breaking windows to space can cause massive damage and mayhem._
While breaches into space are still good for a Revenant I don't think it should be worded as "Fastmos".

_199. Space ruins can contain all kinds of interesting goodies, even a wand that can raise the dead!_
Unsure if this one's true, or if it's new/old. Bringing it up for review.

**Comment by VEN0M5** [comment]
About tip 123, multitooling the board should unlock the foam dart pistols crate and the contraband crate... Unless that was removed since I last played but I doubt it. The contraband crate contains posters and floor pills.
