### ISSUE TITLE
IPC sprite bug 

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#1389]
Security beret has a sprite bug when worn on IPCs 
![capture](https://cloud.githubusercontent.com/assets/12041669/8365688/b9c641ee-1b5c-11e5-8a28-91f64b5f4b41.PNG)
only when looking north The beret has weird orange lines on the top

**Comment by Spacemanspark** [comment]
Actually that's with ALL mobs.
Happens with my human security character as well.
Probably happens with Kei, too, but he's orange so it doesn't matter.
