### ISSUE TITLE
Accordion wrong sprites

### ISSUE THREAD

**Issue by Asmerath** [ParadiseSS13/Paradise#13898]
**Issue Description**:

Accordion is blue in one hand and red in another

**What did you expect to happen**: 

the regular accordion to be red in both hands 

**What happened instead**:

the accordion is blue if it is in your right hand

**Why is this bad/What are the consequences**:

Its inconsistent and it takes the sprite of a donor item.

**Steps to reproduce the problem**:

Hold an Accordion in your right hand

**When did the problem start happening**:

Not too sure but I'm sure it started when I sprited the donator accordion. I am new to code and such and probably fucked it up only noticing today because no one ever uses an accordion.

**Extra information**:

Hold an accordion in your right hand it is blue (using the sprite of Rara's Somber Accordion) where as if its held in your left hand its the normal red accordion with back straps.

**Comment by dearmochi** [comment]
Can confirm the accordion sprite was wrong for the right hand, fixed in https://github.com/ParadiseSS13/Paradise/pull/13865
