### ISSUE TITLE
Spaced to lavaland

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#13893]
**Issue Description**:

If you get spaced during transit of a shuttle, you can land on lavaland.

**What did you expect to happen**: 

To land somewhere in space.

**What happened instead**:

Somehow survived an orbital drop onto the planet without a scratch.

**Why is this bad/What are the consequences**:

Would expect spaced people to land in space.

**Steps to reproduce the problem**:

Be on a shuttle/pod that's currently traveling, take a step outside and be (un)lucky.

**When did the problem start happening**:

Unknown

**Extra information**:

The case i've experienced did place the spaced character in the necropolis wall at the top of lavaland, which are as far as i'm aware unbreachable. So even if we are fine with people getting dropped onto the planet, it should check that they are able to move/get recovered, even if the chances may be slim.

**Comment by Spacemanspark** [comment]
Orbital Drop Lava Troopers
