### ISSUE TITLE
Survival pods magically delete lava

### ISSUE THREAD

**Issue by Balthusdire** [ParadiseSS13/Paradise#13918]
**Issue Description**: 
A survival pod can be activated and throw onto lava and it will open and delete all the lava.

**What did you expect to happen**: 
Pod would fail to deploy or would be burned by the lava.

**What happened instead**:
The survival pod deployed and deleted the lava.

**Why is this bad/What are the consequences**:
Lava is supposed to be a significant barrier that takes time and effort to overcome. This allows people to bypass lava very simply with round start equipment. This allows painfully easy access to the syndie base, to the labour camp, to anywhere over lava.

**Steps to reproduce the problem**:
Activate a survival pod capsule over lava and it will open and remove all the under it.

**When did the problem start happening**:
First noticed 2 days ago.

**Extra information**:
![broken](https://user-images.githubusercontent.com/29210343/88443356-fc296e80-cde5-11ea-9161-36acbd6cb1ad.PNG)

**Comment by TheMaveran** [comment]
Pretty sure this is intentional, and I’m not sure if this is really an “issue” per say. And by time and effort, do you mean taking 2 minutes to kill like two goliaths for the boat mats?

**Comment by Kyep** [comment]
I'm not sure this is an issue.
There are plenty of ways to bypass lava.
E.g. RCDs, lavaproof upgrade, etc.
I don't think lava is meant to be completely impassable.

**Comment by Balthusdire** [comment]
Okay so here's my reasoning on why it is broken. Lava should be something that can be bypassed but it should be something that takes some effort to do so, which is why lava does so much damage so fast to prevent people from crossing one tile gaps and just eating the burn damage. RCD, lavaproof, even the goliath boat all take some time and effort to do. Not a ton which is good, but still you need to at least find 3 goliaths and kill them or get some RND equipment. Once you have done that you are able to cross lava but for methods like boat or rcd there is an element of risk since crossing takes time and some care to make sure you dont get burned or attacked since you are vulnerable. The pod I think is broken because of a few reasons that these other methods dont have a problem with.

1. The pod is round start equipment and incredibly fast and simple to use. A miner at round start can simply check for the syndie base's coordinates and head right there, throw down the pod, and loot it. Possibly before the syndie base personnel wake up. The other methods take some time to gather everything up and some methods require coordination with departments outside cargo.

2. The pod is an extremely powerful way to cross lava. You activate it and throw it into the lava and it will clear 25 tiles and make those tiles ash storm proof. You also have walls and machines that are a natural defense against any of the syndicate weapons if they do notice you trying to approach the base.  The walls can also reflect projectiles back at the firer, though this chance is fairly low for the weapons the syndicate scientists carry. If you are crossing in a mech or in a boat you are exposed to a greater or lesser degree. While crossing in a boat for example you have a hard time handling anything but the boat and its oars since other items have a tendency to burn.

3. The pod eliminates lava. Most other methods allow you to pass lava but do not remove it as a barrier, meaning anyone who wants to follow you must also have a way to bypass it. The obvious exception to this is the RCD which also removes lava, but the RCD requires a lot of resources at round start or requires enough RnD to make it cheap enough and also requires you to slowly advance one tile at a time into the lava which is a reasonable requirement for something that permanently removes the lava.

While this method isn't super wide spread yet even in the past week I've been seeing more and more players pick it up so they can try to loot the syndie base and if there is one thing miners don't need its more powerful loot. This is a method that seems to continue to become more wide spread as people realize that it is possible.

I do understand though that this is definitely not a clear cut case of something being broken and if you guys decide that it is okay I will happily close this issue, I just wanted to lay out the case as I see it first.
