### ISSUE TITLE
Roll of gauze doesn't heal minor bruises?

### ISSUE THREAD

**Issue by ClaytonKelly** [ParadiseSS13/Paradise#1391]
Is this intended? Minor bruises you can place it on them and it gives you that medical message but it doesn't actually do anything. So is it strictly only to be used for bleeding?

**Comment by Robertha89** [comment]
This is a bug. As it is supposed to go away when  healed

**Comment by Fox-McCloud** [comment]
gauze is used to stop bleeding; nothing more, nothing less--this is most definitely *not* a bug.

**Comment by Robertha89** [comment]
while it might not be with this specific item, there is no way to remove bruises from your examine text.
