### ISSUE TITLE
Ash Storm causes MMI failure

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#13926]
As a miner borg you are now immune to ash storms, but apparently the MMI inside of you is not.

The borgs MMI will die if you stand out in the storm, and while this does not disable your borg, if your brain is removed from your borg you will die because your brain is pre-dead.

**What did you expect to happen**: 
The MMI to not die because it is inside of a borg that is immune to ash storms

**What happened instead**:
MMI is dead, I grabbed a screenshot: https://cdn.discordapp.com/attachments/572946419028066317/736804814129725530/Ash_Storm.png

**Why is this bad/What are the consequences**:
Just seems like a strange bug, also some roboticists tend to take borgs apart to repair them and pulling a dead MMI out of a borg that might be repairable is kind of a problem, especially when mmis cannot be repaired.

**Steps to reproduce the problem**:
Be borg, stand in ash storm, wait.

**When did the problem start happening**:
Probably after borgs were given the ability to be immune to ash storms?

**Extra information**:
I was told to add that I was a round start cyborg, and my job preference is set to Robot.

**Comment by Spacemanspark** [comment]
How does this react with posi/ robotic brains? The same?
