### ISSUE TITLE
Drask get killed by Cleaning Grenades

### ISSUE THREAD

**Issue by shawnhind** [ParadiseSS13/Paradise#13938]
**Issue Description**:
If a drask stands in a cleaning grenade area of effect they seem to sometimes die.

**What did you expect to happen**: 
Not to die.

**What happened instead**:
As the cleaning grenade started to dissipate I was instantly put into crit.  Have had it happen multiple times and I initially assumed it was intentional.

**Why is this bad/What are the consequences**:
Dying if you shouldn't die is not good.

**Steps to reproduce the problem**:
1. Throw a cleaning grenade
2. Be Drask
3. Die

**When did the problem start happening**:
I just recently unlocked Drask in the last couple of days and it's happened since I unlocked it.  So July 2020 is when I started noticing it.

**Extra information**:
I hadn't been sure if this was a bug or if it was intended but I ahelped and @Qwertyotoforty told me it was a bug so that made me think it was already known.  But when searching I didn't find anything referring to drask dying from this.

**Comment by shawnhind** [comment]
Additional notes:

Tested this locally and it happened three times in a row with drask + cleaning grenade.  It specifically says "You are scalded by the hot chemicals! x8" when the foam goes away.

https://i.imgur.com/AHTMo4O.png

**Comment by taukausanake** [comment]
Drask are colder creatures than normal mobs, so maybe luke-warm temperatures hurt them more. Is pretty weird a cleaning grenade would generate any amount of heat but that's Chemistry for you

**Comment by shawnhind** [comment]
@taukausanake so are you saying you think this is intended behavior and not a bug?  I had opened this because I ahelped this and Qwertyotoforty had thought it was a bug when I asked if it was supposed to have happened.  Maybe need to get some input from others to see if this is intended or not

**Comment by taukausanake** [comment]
I don't know anything, I'm just throwing out ideas on what the issue could be. It's possible that it's intended but someone smarter than me would have to verify it

**Comment by SteelSlayer** [comment]
Looked into this a bit. Naturally spawning cleaner grenades' reagents start out at 293.15K, but grenades add 10K to them when the grenade goes off so that puts them at 303.15K. Drask's `heat_level_1` is 300, which makes the greande deal damage to them.

However, if we look at this:
```js
var/mult = dna.species.heatmod
if(bodytemperature >= dna.species.heat_level_1 && bodytemperature <= dna.species.heat_level_2)
   throw_alert("temp", /obj/screen/alert/hot, 1)
   take_overall_damage(burn=mult*HEAT_DAMAGE_LEVEL_1, updating_health = TRUE, used_weapon = "High Body Temperature")
```
They should only take `mult * HEAT_DAMAGE_LEVEL_1` damage, which is normal terms is `2 * 2`, or 4 damage. They will take 4 burn damage over their entire body, every Life cycle (2 seconds). Which is obviously nowhere near enough to kill them.

So my question would be, was this a naturally spawning cleaning grenade or a custom one made in science that was really hot or something?

**Comment by Fox-McCloud** [comment]
Foam is meant to apply in an AoE each time it pops; it's how it "splashes" things around to clean/impact them.

So if it goes off when you're in the middle of it, you're going to get splashed multiple times as there's multiple "foams" that are in range of you.

Adjusting the entirety of chemical temperatures just to make things bubblewrapped for Drask is really not appropriate here---this is either going to have to be decided on something like "Drask just have to put up with this as a quirk" or their temperature resistance increased slightly.

**Comment by shawnhind** [comment]
In my opinion, having cleaning grenades, something that everyone assumes to be non-lethal to be able to kill crew by accident is a really bad idea unless it gets made common knowledge that janitors need to be careful otherwise they could be charged with Manslaughter without even understanding why.

It's not so much a matter of it being inconvenient to drask but I've been accidentally murdered 3 times since unlocking drask a month ago.  Cleaning grenades get thrown in hallways all the time with no thought put into that they could kill some people.  I think either the fact that cleaning grenades can be dangerous to some races needs to be documented or the heat threshold should be adjusted slightly to prevent this.  I'm not sure how much balance impact a few degrees adjustment would have to drask?  WOuld setting the threshold just above the cleaning grenade temp have an impact on anything else?
