### ISSUE TITLE
Pentetic Acid damages robo limbs

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#13939]
**Issue Description**:
So apparently, pentetic acid can damage robotic limbs now.

**What did you expect to happen**: 
I gave someone that had robotic limbs pentetic acid. I expected the robotic limbs to be entirely unaffected.

**What happened instead**:
The robotic limbs magically gained brute and burn damage.

**Why is this bad/What are the consequences**:
Robotic limbs are getting damaged when they should not be, leading to damage that medbay cannot heal and that the person will have to heal themselves or get robotics to heal.

**Steps to reproduce the problem**:
1. Eat pentetic acid while having robo limbs.
2. Wait for RNG damage rolls.
3. Scan yourself.
4. Marvel at your robo limbs becoming damaged.

**When did the problem start happening**:
No clue.

**Comment by SteelSlayer** [comment]
Pretty sure this has always been the case. It's probably like this so that you can't get fully augmented, eat pills and ignore all the damage incurring downsides.

**Comment by moxian** [comment]
This is working as intended. Pentetic Acid damages *any* limbs, although it might be less noticeable on organics, as they get healed with other meds.

https://github.com/ParadiseSS13/Paradise/blob/914e1493cd3c9827644985ac8876b921ad897560/code/modules/reagents/chemistry/reagents/medicine.dm#L434-L436

Been this way for a while.

**Comment by AffectedArc07** [comment]
Working as intended
