### ISSUE TITLE
IPC's dont process chemicals when dead

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#1393]
IPC's dont process degreaser or Liquid solder while dead which means that if IPC died of brain damage or residue(toxins) they cannot be fixed

**Comment by Spacemanspark** [comment]
FalseIncarnate and me found this out yesterday.

**Comment by Fox-McCloud** [comment]
No one processes reagents while dead--they're..dead.

**Comment by FalseIncarnate** [comment]
This was partially an oversight and partially intended functionality.

In addition to a couple other minor things I thought of today, I'll be trying to code a way to repair brain damage and residue from a deceased IPC so they can properly be revived.

In the meantime... Try not to OD?

**Comment by Robertha89** [comment]
well, injecting the reagent should be enough to prevent em from autogibbing when you weld em up

**Comment by Fox-McCloud** [comment]
The same thing happens with humans; often times they require multiple defibs just to bring them back.

IPCs blowing appart is really the only thing that's making this inherently more difficult than otherwise would be.

**Comment by BiberDark** [comment]
Only Acid and Alkalisshould work on IPC´s  for example: ( NH3 / NaHCO3 / NAHO) or HNO3+3 HCl (aqua regis). Nothing else.
