### ISSUE TITLE
I get an error message as drone when I try to access the Power Alarm window.

### ISSUE THREAD

**Issue by justaguyulove** [ParadiseSS13/Paradise#13953]
**Issue Description**:
I get an error message as drone when I try to access the Power Alarm window.

**What did you expect to happen**: 
For the window to simply open up and show me the power alarm statuses.

**What happened instead**:
I got an error message.

**Why is this bad/What are the consequences**:
I cannot clear or fix the alarms.

**Steps to reproduce the problem**:
Go drone, upon up the power alarm monitor under Subsystems. I also had another issue that I will report in a different report.

**When did the problem start happening**:
About 30 minutes before this report was made.

**Extra information**:
Picture:
https://imgur.com/a/RSJyvX3

**Comment by RedWolfie** [comment]
This will likely get fixed with #13751
