### ISSUE TITLE
"You somehow ended up in nullspace AKA Z sector 0. No clue what happened. I'll send you to arrivals."

### ISSUE THREAD

**Issue by justaguyulove** [ParadiseSS13/Paradise#13954]
**Issue Description**:
Dovydas12345: "You somehow ended up in nullspace AKA Z sector 0. No clue what happened. I'll send you to arrivals."

I was ventcrawling as a drone, when I tried to open up the Power Alarm subsystem (see other bug report), which resulted in an error message. I tried to fix it by restarting the game. When I came back, I was able to move, hear things around me and read chat/radio, but was unable to see anything. All I saw was black rectangles. That is when I talked to Dovy, who told me what happened (read above).

**What did you expect to happen**: 
To be able to play as a drone without issues.

**What happened instead**:
I got yeeted into the 4th dimension.

**Why is this bad/What are the consequences**:
It made me unable to play.

**Steps to reproduce the problem**:
Ventcrawl, open up Power Alarms under Subsystems, get ERROR message (see other bug report), restart.

**When did the problem start happening**:
30 minutes before this post.

**Extra information**:

**Comment by Groudonmaster** [comment]
Fixed by PR #14415

**Comment by Henri215** [comment]
Tested, it was fixed by PR https://github.com/ParadiseSS13/Paradise/pull/14415 like Groudonmaster said.
