### ISSUE TITLE
Invisible Syndi-bees are only a pet shop away!

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#13957]
**Issue Description**:
Giving a pet collar to a sentient Syndi-bee makes it invisible

**What did you expect to happen**: 
That it would have a cool new name, with no other side effects

**What happened instead**:
It got a cool new name and its sprite disappeared. It was still in the world, and interactable, as a sentient syndi-bee normally is, but was invisible

**Why is this bad/What are the consequences**:
INVISIBLE SYNDI-BEES MAKING SARCASTIC COMMENTS OUT OF NOWHERE

**Steps to reproduce the problem**:
Use gold slime extract + blood to create random creature
Get a syndi-bee
Feed it a sentience potion
Once sentient, put a pet collar on it with a new name
Boom, invisible bee

**When did the problem start happening**:
Dunno!

**Extra information**:
I'd be curious to see what other sentience potion animals this affects

**Comment by PacifistDalek** [comment]
![image](https://user-images.githubusercontent.com/32213277/88887645-cbdd3800-d20a-11ea-97fb-489d34bdd235.png)

**Comment by Balthusdire** [comment]
I for one welcome our new invisibee overlords.
