### ISSUE TITLE
MetaStation issues megathread

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#13950]
# Last Updated: 2020-10-14

This is an issue for keeping track of all the MetaStation issues, combining the others, and serving as an easy point for people to post things they find. I plan to fix all the ones posted on here after map standardisation has gone through. Here are existing ones in no particular order

# Please include co-ordinates of all issue reports

Turbine needs a pipe cleanup as well as an atmospherics inlet
![image](https://user-images.githubusercontent.com/25063394/88809195-bedd2c00-d1ab-11ea-866d-94682c470afb.png)

Prisoner processing needs a major remake
![image](https://user-images.githubusercontent.com/25063394/88809986-aa4d6380-d1ac-11ea-8370-40a1a207c6fe.png)

The hell is this wiring in the teleporter
![image](https://user-images.githubusercontent.com/25063394/89102154-4de18280-d3fe-11ea-901d-96726da48400.png)

**Comment by TDSSS** [comment]
> Atmos needs an extra hardsuit and a cleanup of what is where

Probably need to be in suit storage units, too.

**Comment by AffectedArc07** [comment]
> > Atmos needs an extra hardsuit and a cleanup of what is where
> 
> Probably need to be in suit storage units, too.

This is part of what I meant in `cleanup of what is where`

**Comment by AffectedArc07** [comment]
This needs to be removed
![image](https://user-images.githubusercontent.com/25063394/88905231-fa303700-d24d-11ea-95dd-681702915728.png)

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/89101882-0d810500-d3fc-11ea-999c-6b90f3ebc565.png)
Morgue has random pipes and no attached scrubber

**Comment by SabreML** [comment]
Some vents at roundstart are set to siphon, specifically I noticed the one at the IAA spawnpoint but I've been told there's more.

**Comment by Cocacolagua** [comment]
the arcade doesn't have a tech vendor.

**Comment by AzuleUtama** [comment]
In mining - the doors leading out to the shuttle started off bolted and all miners spawned on the same spot at roundstart.

**Comment by hal9000PR** [comment]
the mime and clown office aren't ID restricted to mime/clown

**Comment by AknightSS13** [comment]
The NTR is starting with a CC stamp , i don't think it's normal

**Comment by tolliamlew** [comment]
in the CMO office, the buttons placed on full tile windows are inaccessible because they are under the window panes.

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/125695150-45814335-c1a4-461d-adcc-ed652edf9223.png)
AI upload starts with turrets off and is unbolted

**Comment by Nerfection** [comment]
The Camera Console in the warden's office does not have any cameras connected to it :)

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/125695692-7e8e4d16-d5fd-43b7-bced-b1753f4df959.png)
these doors in paramedics room have no assigned access

**Comment by Cocacolagua** [comment]
> The Camera Console in the warden's office does not have any cameras connected to it :)

to add onto this, all security camera consoles do not work

**Comment by S34NW** [comment]
NTR starts with a CC stamp, not the correct NTR one.

**Comment by S34NW** [comment]
All solars start wired

**Comment by Bormac** [comment]
Paramedics doors have no access set so you can walk into medical storage through their office as a civi

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/125696485-068a7733-8b76-4409-b41c-13066d4145a3.png)
this random plating exists north of xenobio

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/125696936-1734e574-a44e-4f28-9800-8faef0f6b58c.png)
mime and clown offices lack correct access

**Comment by E-MonaRhg** [comment]
Cargo lacks the status displays that display when the shuttle arrives and only the lower one of these buttons works and operates both blast doors
![image](https://user-images.githubusercontent.com/71735193/125697693-81917a6a-3102-4c3b-b264-59634eeff9a1.png)

**Comment by KrossarnTom** [comment]
Pipes dont connect
Pump is off
Room is called "Incinerator" But it is the Turbine
![Skärmbild 2021-07-14 235353](https://user-images.githubusercontent.com/72948218/125697793-c4877319-2307-4fdc-9a5f-dbc8b7d41571.png)

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/125699422-dc853631-366a-47b9-8020-3b3b41f207a2.png)
coffee machine costs money... that prisoners cant pay for...

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/125699976-8d2141f4-442c-47b1-b280-637bccf95668.png)
white ship docks IN perma

**Comment by KrossarnTom** [comment]
(Red) N2 pumps starts at 101kPa
(Blue) O2 pump starts at 101kPa
(Purpule) Mixer starts at 4500kPa
(White) Air tank fills at a VERY slow rate
![Skärmbild 2021-07-15 001652](https://user-images.githubusercontent.com/72948218/125699797-40374fc4-b292-47d5-a4cd-ecc8b7320316.png)

**Comment by yeetethdeleteth** [comment]
OK OK OK OK OK

White ship is super broken. There's two options for places to land station side as opposed to the Cyberiad's one.
![wtf](https://user-images.githubusercontent.com/68583331/125700359-f136a6ef-83b2-4ff4-a346-13dbfe97c4b6.JPG)

The top one lands in perma.
![ijurjuss](https://user-images.githubusercontent.com/68583331/125700415-05bf007e-167e-4aa9-91a5-d62379a4685d.JPG)

Too afraid to try the second one, will try it later.

**Comment by cmcarey** [comment]
Not sure if a bug, but I've noticed some radios that I think should be on AI private (like in the AI core chambers) are on 144.7, which the wiki references as AI private, but clicking the AI private preset changes it to 134.3.

**Comment by Forenzek** [comment]
[https://i.imgur.com/fNE4uWp.png](url)

This door doesn't have access set so anyone can walk in.

**Comment by E-MonaRhg** [comment]
Wrong pipe in engineering sends trash from security to just above the SM:
![image](https://user-images.githubusercontent.com/71735193/125701347-0bf90728-75e2-412d-96cd-9e2e6ca07a2b.png)

**Comment by KrossarnTom** [comment]
External Airlocks to the different shuttles in arrivals are unlocked.
Also the Airlock west of medical lacks "buttons" and air cycle.
![Skärmbild 2021-07-15 010227](https://user-images.githubusercontent.com/72948218/125703470-3e8cd547-6441-40f7-afac-edd839ddcc79.png)
![Skärmbild 2021-07-15 010427](https://user-images.githubusercontent.com/72948218/125703474-47d2e7d9-befa-4e17-b757-3c33013adcf8.png)
![Skärmbild 2021-07-15 005855](https://user-images.githubusercontent.com/72948218/125703487-cd056973-8580-4946-842c-bd464f979aa3.png)

**Comment by KrossarnTom** [comment]
External Airlocks west of medical are unlocked, lack air cycling and buttons to do so. 
![Skärmbild 2021-07-15 005855](https://user-images.githubusercontent.com/72948218/125707601-fff764ad-3435-4f20-8908-8dcdfaedfe64.png)

**Comment by Bormac** [comment]
escape airlocks are unbolted
also clown and mime offices have no accesses set to them so public.

**Comment by chafla** [comment]
Medbay treatment room shutters are just strange

There's a sideways shutter over the left room's airlock, but none over the right one?

![image](https://i.imgur.com/HGRLwod.png)

**Comment by terectec** [comment]
Here's some notes ive taken about the new upper medbay area:
![dreamseeker_wZPD6DELa4](https://user-images.githubusercontent.com/53158786/125709180-0f854d83-f316-4ee4-87ed-0b84c0c90ad7.png)

- Firstly, there's the notable lack of Defibrilator mounts in the upper treatment area - There must be at least one, though since this design is split, it would be preferable to have one on each.
- Then, there's the weird case of the personal lockers. I may be wrong, but I've put 60+ hours in medbay and I have never had a patients belongings get stolen. 
- Furthermore, I'm left wondering why the upper treatment area is split in the first place. There's literally no benefit in having two small treatment closets. Then, I must ask why there are shutters around the area. It's just a potential point of failure that, at best, might stave off a threat or a few seconds. At worse, will stop movement around medbay and negate treatments for patients outside it. 
-  In my opinion, the Shutters must be removed and the rooms joined into one. There should also be at least one defibrillator mount. If a vendor was added to the west wall, it would effectively negate the need for so many Emergency NanoMeds around the treatment area.

**Comment by Hostail** [comment]
Rapid Crate Senders can't seem to choose a telepad to teleport to, so you can't use it at all.
Also you can't send a wrapped crate to Engineering through disposals, it just keeps looping, maybe has something to do with the formerly mentioned wrong pipe in engineering.

**Comment by AffectedArc07** [comment]
> (Red) N2 pumps starts at 101kPa
> (Blue) O2 pump starts at 101kPa
> (Purpule) Mixer starts at 4500kPa
> (White) Air tank fills at a VERY slow rate
> ![Skärmbild 2021-07-15 001652](https://user-images.githubusercontent.com/72948218/125699797-40374fc4-b292-47d5-a4cd-ecc8b7320316.png)

![image](https://user-images.githubusercontent.com/25063394/125777345-74690e77-60fa-4592-9955-9f450f5b2d57.png)
![image](https://user-images.githubusercontent.com/25063394/125777355-760460c6-a071-4b08-91db-c66f6c1417fa.png)
Box both have these set at 4000 each

**Comment by farie82** [comment]
5978 runtimes on initialize of meta station. All runtimes were of this type:
```
Runtime in code/modules/atmospherics/machinery/datum_pipeline.dm,60: 
/obj/machinery/atmospherics/pipe/simple/hidden/scrubbers [[0x20041fd]] added to a pipenet while still having one 
(/datum/pipeline) (pipes leading to the same spot stacking in one turf). Nearby: 88, 197, 2.
```

**Comment by LightFire53** [comment]
https://www.paradisestation.org/forum/topic/21135-nss-cerberon-metastation-mapping-repair-list/

**Comment by Adrer** [comment]
![image](https://user-images.githubusercontent.com/19361017/128898483-edf55242-8ed9-4c3f-9ce7-7a2501b7d826.png)

Custodial closet has no custodial closet.

**Comment by hal9000PR** [comment]
![image](https://user-images.githubusercontent.com/69320440/128899661-21362465-17c9-4407-9ff1-5b39d7b8b942.png)
atmos techs cannot reach the guest pass terminal.

**Comment by hal9000PR** [comment]
![image](https://user-images.githubusercontent.com/69320440/128900349-6c48eb96-79fb-41ae-90f6-2293b634ec63.png)
minisat access is accessable by engineers/atmostechs

**Comment by AffectedArc07** [comment]
If your comment got deleted it means the thing was fixed.

**Comment by S34NW** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/69320440/128900349-6c48eb96-79fb-41ae-90f6-2293b634ec63.png)
> minisat access is accessable by engineers/atmostechs

This is not an issue. Engineers do not have access to the sat interior.

**Comment by S34NW** [comment]
> 
> 
> Here's some notes ive taken about the new upper medbay area:
> ![dreamseeker_wZPD6DELa4](https://user-images.githubusercontent.com/53158786/125709180-0f854d83-f316-4ee4-87ed-0b84c0c90ad7.png)
> 
>     * Firstly, there's the notable lack of Defibrilator mounts in the upper treatment area - There must be at least one, though since this design is split, it would be preferable to have one on each.
> 
>     * Then, there's the weird case of the personal lockers. I may be wrong, but I've put 60+ hours in medbay and I have never had a patients belongings get stolen.
> 
>     * Furthermore, I'm left wondering why the upper treatment area is split in the first place. There's literally no benefit in having two small treatment closets. Then, I must ask why there are shutters around the area. It's just a potential point of failure that, at best, might stave off a threat or a few seconds. At worse, it will stop movement around medbay and negate treatments for patients outside it.
> 
>     * In my opinion, the Shutters must be removed and the rooms joined into one. There should also be at least one defibrillator mount. If a vendor was added to the west wall, it would effectively negate the need for so many Emergency NanoMeds around the treatment area.

Fixed

**Comment by S34NW** [comment]
> 
> 
>     * Medbay treatment room shutters are just strange
> 
> 
> There's a sideways shutter over the left room's airlock, but none over the right one?
> 
> ![image](https://camo.githubusercontent.com/5bd76b6e9bfc0e1eb74097b256ffc147c73b4896c9cd6f203e2e515e854fa3e3/68747470733a2f2f692e696d6775722e636f6d2f4847524c776f642e706e67)
> 
>     * The medbay maint door into the psych office has the wrong access (seems like it just has general medical doctor access)

Fixed

**Comment by S34NW** [comment]
> 
> 
> Some vents at roundstart are set to siphon, specifically I noticed the one at the IAA spawnpoint but I've been told there's more.



> 
> 
> the arcade doesn't have a tech vendor.



> 
> 
> In mining - the doors leading out to the shuttle started off bolted and all miners spawned on the same spot at roundstart.



> 
> 
> The NTR is starting with a CC stamp , i don't think it's normal



> 
> 
> the mime and clown office aren't ID restricted to mime/clown



> 
> 
> in the CMO office, the buttons placed on full tile windows are inaccessible because they are under the window panes.



> 
> 
> ![image](https://user-images.githubusercontent.com/12197162/125695150-45814335-c1a4-461d-adcc-ed652edf9223.png)
> AI upload starts with turrets off and is unbolted



> 
> 
> ![image](https://user-images.githubusercontent.com/12197162/125695692-7e8e4d16-d5fd-43b7-bced-b1753f4df959.png)
> these doors in paramedics room have no assigned access



> 
> 
> ![image](https://user-images.githubusercontent.com/12197162/125696936-1734e574-a44e-4f28-9800-8faef0f6b58c.png)
> mime and clown offices lack correct access

fixed all of these

**Comment by meow20** [comment]
![image](https://user-images.githubusercontent.com/62257265/133887990-2facd4b1-f7ec-4b80-b584-8ba121c83428.png)
this biohazard sign seems missplaced?

![image](https://user-images.githubusercontent.com/62257265/133888077-eb136c08-f7ce-44f2-9e1c-7ac6716eadf3.png)
the ticket machine should be at the start of the line, not the end

the nt rep starts with CC stamp, not NTR stamp on his desk

![image](https://user-images.githubusercontent.com/62257265/133888647-49fed312-36e8-4372-b3de-309e8437eead.png)
this place under incinerator airlock has two pipes of the same type on the same tile making runetimes

![image](https://user-images.githubusercontent.com/62257265/133891004-e444d009-708c-40e3-bc0d-8ace92e39304.png)
medbay storage scrubber and vent aren't connected to anything

**Comment by TopTheWorst** [comment]
![image](https://user-images.githubusercontent.com/90973675/133892449-45498e30-e9c7-4c54-b335-e9f6c32a2936.png)
Surgery Observation is not connected to grid

**Comment by CrispyChipFox** [comment]
Exosuit Fabricators give blue screen errors and protolathe jams.

**Comment by LightFire53** [comment]
> Exosuit Fabricators give blue screen errors and protolathe jams.

Uh, not sure if that's MetaStation unique? May have to make a different bug report

**Comment by Henr988** [comment]
![image](https://user-images.githubusercontent.com/90366770/134097004-a9b41b26-881a-4e85-a369-2de525867f54.png)

personal issue, atmosia has no outlet valves, just a pump

**Comment by LightFire53** [comment]
My to do: Add pepperspray refill to security somewhere, replace the bed and electropack with an actual electric chair, and add a recharger to RnD

**Comment by VynalDerp** [comment]
Robotics has the same issue that Delta used to have - it has no Space Cleaner, meaning infections are very common (and deadly).

While the Anesthetic cabinet is a great idea, and very useful, nobody in Science has access to it. Not sure if you can change access to it, or if it would be best to change it with a locked robotics locker.

Robotics also lacks diagnostic HUDs on roundstart (or at least I could not find them), and ended up needing to build a Protolathe to make some.

**Comment by TORE01** [comment]
There is no gas mixing station in the toxins lab. if you want to do toxins you gotta remove the filter from the 3 connector ports to the right and replace it with a gas mixer. It's rather inconvenient.

**Comment by LightFire53** [comment]
> Robotics has the same issue that Delta used to have - it has no Space Cleaner, meaning infections are very common (and deadly).
![image](https://user-images.githubusercontent.com/16112919/134449287-ade47dc3-19cf-4afc-93d2-91adc339d4de.png)

Sorry papi, it's already there. Just means someone looted it early.
 
Otherwise, #16777 addresses fixes from Sept 20-21

**Comment by Freakycrafter** [comment]
This switch in robotics is in the wrong place:
![image](https://user-images.githubusercontent.com/57047909/134672191-90a0f907-7a7d-4024-9654-102228a1ef2a.png)
It looks like its on the table, but its actually "on" this tile:
![image](https://user-images.githubusercontent.com/57047909/134672273-bff319c7-0f0c-41d0-b425-4925fe236f67.png)
Like this you cant reach it from standing next to the table.

**Comment by VynalDerp** [comment]
Not exactly an issue persay, but a design issue with the map (at least in my opinion and some people I have asked.) There are quite a few one tile long maintenance hallways, which can extend a fair distance. This often results in disabler or taser shots taking down an officer or antag quite easily, since there is next to no chance to dodge. It makes combat rather unfun on either end. 
Even in some areas with two tile hallways, there are girders, grilles, or water tanks tightening the hallways back to be one tile. This is the main thing holding it back from being voted commonly  at the moment, at least in my opinion.

Wasn't sure where else to leave this, so just dropping it here for now.

**Comment by PacifistDalek** [comment]
I think botany is missing some gear in the back room too, though i might just be confused by the layout. Some stuff is duplicated, some is not, it's quite odd.

**Comment by AllStickyGithub** [comment]
No guest pass terminals on this map

**Comment by Dafrek** [comment]
![image](https://user-images.githubusercontent.com/68184787/169324860-25411ff3-44e6-4dcb-b672-4f62376b0c3a.png)

The injector that vents waste gas from the SM into space seems to start off at round start. I was told that it is coded to be on, but for some reason still seems to be off or turns off.

**Comment by AffectedArc07** [comment]
I think this can be retired now, now that @Bm0n finished the remap
