### ISSUE TITLE
Revenant Role Canidacy issues

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#1395]
Option for it does not appear in Game  Pref ui in lobby.
Using the verb for it in the panel it does not save between rounds.

i did clear my game cache.

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Aurorablade** [comment]
Also i think thier see in dark stuff might be borked...

**Comment by Robertha89** [comment]
see in dark appears to be borked yes.
