### ISSUE TITLE
Sentence verbs over comns do not work right anymore

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#13968]
**Issue Description**:

Sentence prefixes, like asks, yells, queries, states, ect, doesn't work over telecomns anymore

**What did you expect to happen**: 

For if you are to speak in a way that affects how your verb comes out, for this to be reflected on radio

**What happened instead**:

everyone has says over radio no matter what

**Why is this bad/What are the consequences**:

AI no longer states over radio, and its weird having yourself ask or state locally, and it comes out as says over radio.

**Steps to reproduce the problem**:

say ; Does this work?
![image](https://user-images.githubusercontent.com/52090703/89038028-8ead9e80-d30d-11ea-8bc4-1f2806cae289.png)
See as it says ass locally and says over telecomns

**When did the problem start happening**:

Telecomns rework

**Comment by AffectedArc07** [comment]
Will be fixed when https://github.com/ParadiseSS13/Paradise/pull/13943 is merged
