### ISSUE TITLE
Cyborgs can't access the Chemistry Fridge.

### ISSUE THREAD

**Issue by SabreML** [ParadiseSS13/Paradise#13964]
**Issue Description**:

As a Mediborg, I can't access the chemistry fridge when I click on it.

**What did you expect to happen**: 

I expected that the UI would popup, and I could vend pills and so on.

**What happened instead**:

No UI.

**Why is this bad/What are the consequences**:

Medical borgs can't vend important stuff like SR pills.

**Steps to reproduce the problem**:

Play as Cyborg
Click on Smartfridge

**When did the problem start happening**:

Can't really remember if it ever worked, but it's been an issue for at least a month.

**Extra information**:

Also an issue for the AI and Maintenance Drones, so presumably it's something to do with silicons.

**Comment by SteelSlayer** [comment]
I think this is a balance limitation.

**Comment by SabreML** [comment]
> I think this is a balance limitation.

It could be, I just think it’s odd that there’s no feedback whatsoever when you click on it.
Maybe there should be a message or something?

**Comment by SabreML** [comment]
Still think this is an issue, but I'm closing it since it's not exactly a big one.
