### ISSUE TITLE
AI hologram cannot switch to crewmember type

### ISSUE THREAD

**Issue by Skepticalpath** [ParadiseSS13/Paradise#13967]
**Issue Description**: 
As AI, switching what the hologram looks like to a certain crewmember never works. It will remain on your current hologram. 

**What did you expect to happen**: 
I expected the hologram's appearance to switch to the crewmember selected

**What happened instead**:
The hologram does not change to the crewmember. 

**Why is this bad/What are the consequences**:
Less customization for AI and a clear option for AI is not available at all. 

**Steps to reproduce the problem**:
Play as an AI.

Click the change hologram option and choose crewmember.

Click on any crewmember from the menu.

**When did the problem start happening**:
Noticed it a few months ago and tried it today to see if it was fixed. The problem remained. 

**Extra information**:
No matter the crewmember you select the hologram will not change and will remain on what is applicable before. Unique and animal holograms work just fine.

**Comment by farie82** [comment]
![image](https://user-images.githubusercontent.com/15887760/89915979-4f2d5f00-dbf7-11ea-92f4-1dfd7d781f65.png)
The overlays of the crew are not added yet. Thus in `getFlatIcon` nothing will be generated and saved to the "image" field.
Then the AI tries to use the "image" field which is null.
