### ISSUE TITLE
Lipsticks are visible trough masks. 

### ISSUE THREAD

**Issue by DrHornet** [ParadiseSS13/Paradise#13986]
**Issue Description**:
When lipstick is applied, it's sprite appears to be located over the mask layer which should not be.

**What did you expect to happen**: 
The lipstick should be hidden below mask and not being visible trough it.

**What happened instead**:
The applied lipstick was visible through mask like if there was nothing in front of it.

**Why is this bad/What are the consequences**:
It makes characters look rather silly while wearing for example sterile masks or breathing masks along with lipstick.

**Steps to reproduce the problem**:
Apply the lipstick. 

**When did the problem start happening**:
I have no idea how long this issue is around as I have started using lipsticks just recently. 

**Extra information**:
Nothing much to say about it.

**Comment by AffectedArc07** [comment]
Probably broke after https://github.com/ParadiseSS13/Paradise/pull/13911 was merged

@dearmochi
