### ISSUE TITLE
Wingdings failing to load in chat

### ISSUE THREAD

**Issue by BryanPara** [ParadiseSS13/Paradise#14008]
**Issue Description**:
Individuals with the Wingdings genetic mutation when speaking the wingding symbols fail to load and it appears as if they said nothing.

**What did you expect to happen**: 
Grey gibberish when talking with wingdings

**What happened instead**:
A very VERY good imitation of being a mime.

**Why is this bad/What are the consequences**:
 I really don't want knock-off mimes running around the station. In all seriousness not too terrible but still an issue.

**Steps to reproduce the problem**:
Spawn in with wingdings or reincarnate and toggle wingdings, speak, congratulations on graduating mime school.

**When did the problem start happening**:
August 4th 2020, 4:54 EST Server time 8:54

**Extra information**:
Hopefully this is a minor issue that can be resolved quickly, mimes creep me out.

**Comment by RedWolfie** [comment]
Fixed in #14221

**Comment by matttheficus** [comment]
Fixed
