### ISSUE TITLE
Carpets blocking sight

### ISSUE THREAD

**Issue by Rats808** [ParadiseSS13/Paradise#1401]
![image](https://cloud.githubusercontent.com/assets/13080757/8393805/e147c430-1cd4-11e5-9ca0-74512888d8c2.png)
Not sure if this affects all carpets or just carpets made by chemistry. Probably just chemistry, since I haven't seen anybody complaining about the library.

**Comment by Rats808** [comment]
Turning the lights off and back on fixes it.

**Comment by PJB3005** [comment]
gah I know what caused this, gonna fix it
