### ISSUE TITLE
Atmospheric Controls

### ISSUE THREAD

**Issue by BiberDark** [ParadiseSS13/Paradise#1402]
- If you set Air alarms to exact 0 or 40 the room temprature will not change, below or above it works.
- If i set a room to server room i can´t change temprature , i cannot set negativ values. ( so no minus 130 ° rooms )
- Sometimes cooling will not work at all, or the room will not change pressure .

**Comment by TheDZD** [comment]
Were you using the console that is in atmospherics? You can only modify air alarms from there if there is an active alert in the area said alarm controls.

**Comment by BiberDark** [comment]
No the Air Alarms in the rooms. As an AI-Player.

**Comment by PsiOmegaDelta** [comment]
If your air alarms still work as on Bay you first need to change the temperature alarm range in the sensor settings panel. It's the alarm range that caps the temperature you are allowed to set.
Being unable to set the temperature to 0 is likely due to a bad input check that quits early. Basically goes like:
```
var/temp = input("Select temperature") as null|anything
if(!temp) // Matches both cancel/null and 0
    return
```
Should instead be:
```
var/temp = input("Select temperature") as null|anything
if(isnull(temp)) // Only quit if the user selected cancel.
    return
```

**Comment by BiberDark** [comment]
The alarm range influence the  possible temperature? I thought this is regulated by the room setting. LIke Vox / Human / Coldroom.  I think the temp should only be regulated over the thermostat and the room setting only influences the gascomposition in the room.

**Comment by PsiOmegaDelta** [comment]
It kind of makes sense for the temperature range to be limited by the alarm settings, unless you want to annoy the engineering department with a permanent atmosphere alarm.

**Comment by BiberDark** [comment]
For something like this there is an atmospheric division, or not ? Or the Ai.

**Comment by Markolie** [comment]
Not sure how to fix the temperature thing to be honest - it'd require a pretty hefty if check due to the negative numbers. There's probably a better way I don't know of.

**Comment by FalseIncarnate** [comment]
Simplest way would be to use Kelvin instead of Celius for the temperature settings, as they will always work with min/max ranges

Converting will just be a pain
