### ISSUE TITLE
Crab provide infinite nutrition to slime

### ISSUE THREAD

**Issue by Gc1mak** [ParadiseSS13/Paradise#1403]
I was turned into a slime in a tragic workplace accident and went to the gateway beach. I attacked and fed on a crab. I got all the way from 800 something nutrition to 2200 until I logged out because I had to go for dinner. I think crab provide infinite nutrition to slime. I am not sure about other pets.
- Ansari

**Comment by Smudgyglasses** [comment]
not sure if this was ever fixed but this also applies to mice, even though the mice sprite suggests the mob is dead it provides infinite nutrition
