### ISSUE TITLE
LWAP sniper fits in holsters

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14048]
**Issue Description**:

Lwap sniper, a bulky laser sniper 2 hands are needed to use, fits in a normal sized shoulder holster.

**What did you expect to happen**: 

For it too be too big to fix

**What happened instead**:

It fits inside your holster, allowing you to hold one without using a backpack or armor slot

**Why is this bad/What are the consequences**:

A giant bulky laser sniper should not fit in an item smaller then it, when the holster is ment to hold normal or smaller sized guns

**Steps to reproduce the problem**:

Get a holster on.
Get a LWAP
Press H to holster it

**Extra information**:

Adding:

> /obj/item/gun/energy/ionrifle/isHandgun()
	return 0

Fixes the issue

**Comment by mokulus** [comment]
@AffectedArc07 please close this, fix was merged
