### ISSUE TITLE
You can get a deathsquad action figure from the arcade

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#14055]
**Issue Description**:
You can get deathsquad action figures from the arcade. Also deathsquad ripleys (We dont use them but its still weird)

**What did you expect to happen**: 
This figure to be unavailable from the prize pool

**What happened instead**:
They can spawn

**Why is this bad/What are the consequences**:
Deathsquads dont exist. They never have, and never will. Epsilon is a myth and anyone talking about it should be sent for a psych eval

**Steps to reproduce the problem**:
Grind the arcade for a bit until you get the figure

**When did the problem start happening**:
Probably when the figures got added

**Extra information**:
N/A

**Comment by PidgeyThePirate** [comment]
You mean the action figure from DeathSquad™, the popular holovid show about loose cannon ERT officers who don't play by the rules? What's wrong with them?

**Comment by AffectedArc07** [comment]
```dm
/obj/item/toy/figure/dsquad
	name = "Death Squad Officer action figure"
	icon_state = "dsquad"
	toysay = "Eliminate all threats!"
```
If you want to modify it, feel free

**Comment by PacifistDalek** [comment]
This should be like the only prize you get if you emag the arcade machine
