### ISSUE TITLE
The abstract monster meat is spawnable using silver slime extracts

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#14063]
**Issue Description**:
The monster meat item is spawnable when using a silver slime extract.

**What did you expect to happen**: 
Abstract items to not spawn

**What happened instead**:
You got an item saying to alert a coder

**Why is this bad/What are the consequences**:
It's a bug

**Steps to reproduce the problem**:
Pray to RNG to get it from the silver slime extract

**When did the problem start happening**:
Since the `/obj/item/reagent_containers/food/snacks/monstermeat` type is brought to life

**Extra information**:
Silver slime extracts already have a blacklist. The type is just not put in there

**Comment by alex-gh** [comment]
This probably should be closed, since the fix was merged.
