### ISSUE TITLE
Saving character without DB

### ISSUE THREAD

**Issue by Fr4Ckt3r** [ParadiseSS13/Paradise#14060]
Yeah, yeah i know that i should write that on forum, but i dont have time to run BYOND then connect to server and etc

Any chance on saving character without DB? I dont want to setup that, i wanna save character like in Baystation w/o db

**Comment by AffectedArc07** [comment]
We do not use savefiles, everything is stored in the database. We have no plans to refactor everything to have split saves between a database and a BYOND savefile (which is unreadable by anything else)
