### ISSUE TITLE
Magical mime mask doesnt hide your face

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14076]
**Issue Description**:

The magical mime mask doesn't hide your face like a mask should, so you can see who it really is under it, dispite having your face covered sprite wise and logicaly

**What did you expect to happen**: 

For the mime  mask to cover your face and make you look unknown

**What happened instead**:

Mask doesn't stop your identity from showing.

**Why is this bad/What are the consequences**:

Allows for easy tracking to happen, inconsistent from other masks

**Steps to reproduce the problem**:

Be a wizard.
Get a magical mime mask.
Put it on.

![image](https://user-images.githubusercontent.com/52090703/90156425-6c2e7300-dd5a-11ea-90e7-8297fcd3d516.png)

**Comment by datlo** [comment]
This is not a bug. Wizards do not have IDs and the only reason to wear the magical clown and mime masks is for the sake of a gimmick, which the wizard's name is a part of. Hence why they do not hide your identity.
