### ISSUE TITLE
Mass drivers fling ghosts

### ISSUE THREAD

**Issue by Alantodne** [ParadiseSS13/Paradise#14081]
**Issue Description**:
Mass Drivers will fling ghosts

**What did you expect to happen**: 

The mass driver to trigger and for ghosts to not go flying

**What happened instead**:
The mass driver will fling the ghost at that speed, sometimes causing collision with other ghosts in the mass driver. It also sometimes produces sounds. not sure if they are hearable for in round people that arent ghosts.

**Why is this bad/What are the consequences**:
There MIGHT be a interaction with a ghost flying into a person, however I didnt see that yet.

**Steps to reproduce the problem**:
Set up mass driver(Not sure how to do this I watched Rolix). Position a ghost on the flingy part. Trigger the driver. Ghost should go flying. 

**When did the problem start happening**:
I noticed it during a round today.

**Extra information**:
Also Ghosts that are following someone that gets on a mass driver will stop following that person. Probably related to this.

**Comment by taukausanake** [comment]
S p o o k y. Especially with the sounds. Working as intended if you ask me but might want to look into the ghosts stop following when someone is shot out

**Comment by farie82** [comment]
Easy first issue. There are two ways to check if something is immovable. First one (the oldest method) is the `anchored` variable on atoms. The newer one is the `move_resist` variable on atoms. If the latter is `INFINITY` then it is immovable
