### ISSUE TITLE
Paperwork Centering

### ISSUE THREAD

**Issue by DevL-Whats-a-jpg** [ParadiseSS13/Paradise#14083]
**Issue Description**:
Using [center[ [/center] on the first line does not center the text (or image).

**What did you expect to happen**: 
I expected to find my text nice and centered.

**What happened instead**:
It acts as if the center is not there, however it does not render the center's.

**Why is this bad/What are the consequences**:
Its not important, unless you love making the chemist fill out 6 sheets of paperwork for each of his buckets.

**Steps to reproduce the problem**:
Just try something like [center] Header [/center] on the first line.

**When did the problem start happening**:
Around 2 weeks ago, its definitely a more recent issue.

**Extra information**:
Ganglewaefre found it works on the second (and likely all below) lines, and you can just place a horizontal rule at the top.

**Comment by RedWolfie** [comment]
I failed to reproduce this

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/96363070-d7fdd500-1129-11eb-9610-673fed083ff8.png)
