### ISSUE TITLE
Sea carp are invisible

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14095]
**Issue Description**:

See carp are invisible, and only show on right click or health huds

**What did you expect to happen**: 

For sea carp to be visable

**What happened instead**:

They are not

**Why is this bad/What are the consequences**:

Mobs being invisible is bad, as you can not fight them

**Steps to reproduce the problem**:

Have a beach gateway.
Ghost, and turn on huds
See all the carp that most can not see.

**Comment by Spacemanspark** [comment]
Did you try using the silph scope
