### ISSUE TITLE
Hotkey toggle makes the game crash

### ISSUE THREAD

**Issue by lalchimi** [ParadiseSS13/Paradise#14098]
**Issue Description**: 
When switching the hotkeys on with TAB, the game completly crash. Forcing me to quit.
I don't  know why it happens. It seems to work for other but not me.
I have clean the cache. Reinstal BYOND. Restart my computer.
I tried hotkeys on other servers and it doesn't make the game crash on the other servers.

**What did you expect to happen**: 

Make the switch to hotkey without crashing the game.

**What happened instead**:
Crash the game

**Why is this bad/What are the consequences**:
Can't play with hotkeys

**Steps to reproduce the problem**:
Hit TAB

**When did the problem start happening**:
No idea of the reason. It started on the 08/17/2020

**Extra information**:
It also makes tabs dissapear, only showing three tab.
![image](https://user-images.githubusercontent.com/56610386/90348044-480db300-e034-11ea-807f-e5251c62fead.png)

**Comment by Contrabang** [comment]
An issue with windows, and no other reports in nearly 3 years
