### ISSUE TITLE
no machine boards for lysis/ballistic and broken apples

### ISSUE THREAD

**Issue by Midaychi** [ParadiseSS13/Paradise#1409]
Both these issues exist on bay as well as far as I know.

You can't reconstruct or construct the lysis centrifuge or the ballistic thingymabab because there's no board for them or definitions for machine components. If these could be added to the circuit imprinter/machine definitions that'd be pretty neat. 
No need for upgrade code or anything, but if you do you could make better parts destroy the genome slower in the lysis machine/allow for more mutations in the bioballistic before they become unviable.

 As for apples, their icon or something is broken. They come out of the vendor as question marks, and attempting to use them in the lysis/bioballistic will freeze those machines up permanently, which is a problem because they can't just be torn apart and put back together RE: previous issue.

Also side thing that I'm not sure is actually an issue, as it might be intentional? Poppys don't have any reagents at all.

**Comment by FalseIncarnate** [comment]
I'll look into this (given my familiarity with botany stuff)

When you say that apples come out as question marks, is it the dark circle with a question mark seed icon (I think tea and tobacco have the sprite I'm referring to), or JUST a question mark (typically purple)?

Poppies might have been a mistake in updating the reagents to goonchem, so I'll look into fixing that.

Build able xenobotany stuff will get run past the others before I do anything with that, but I don't foresee much opposition to that. Hell, if anything, it's another reason to raise the bio research!

**Comment by Midaychi** [comment]
It's got a dark disk behind the questionmark

**Comment by Midaychi** [comment]
There *might* be opposition to making the boards R&D able because if you do, then that makes the only thing a scientist would need to build a botany batcave on the research outpost be the box of botany disks. I think you can order those from cargo?

**Comment by FalseIncarnate** [comment]
The dark disc question mark is actually a seed sprite, despite looking like a mistake.

I'd like to expand on the icon selection for new botany, since visually it is VERY inferior to the old system. Getting the appropriately configured sprites is just off-putting.

**Comment by Midaychi** [comment]
https://github.com/Baystation12/Baystation12/pull/9964
