### ISSUE TITLE
AI PDA ringer makes heavy lag for any ghosts that see the message, maybe mobs too

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14096]
**Issue Description**:

whenever AI has the PDA ringer go off, like in the image below, all ghosts that have the AI on the screen are froze for a second.
![image](https://user-images.githubusercontent.com/52090703/90341431-ae131f80-dfcd-11ea-9ba4-3cfccaf537e0.png)

**What did you expect to happen**: 

For the ringtone on the AI to work normally

**What happened instead**:

Lag consumes me

**Why is this bad/What are the consequences**:

AIS PDA should not lag people

**Steps to reproduce the problem**:

Ghost near the AI, seeing it
Wait for someone to PDA IT 
Enjoy the free lag.

**Comment by AffectedArc07** [comment]
Never been an issue for me. Is this a confirmed issue between multiple people or just your end?

**Comment by Qwertytoforty** [comment]
No one else has the issue, it seems, just me, no idea why, joy.

**Comment by Spacemanspark** [comment]
Haha
