### ISSUE TITLE
Synthetics can't flush disposals

### ISSUE THREAD

**Issue by ExusA** [ParadiseSS13/Paradise#14125]
**Issue Description**:
When anything other than a humanoid attempts to flush a disposal, nothing happens.

**What did you expect to happen**: 
Synthetics (robots, AIs and drones) to be able to flush disposals like usual.

**What happened instead**:
No feedback, the button just does nothing.

**Why is this bad/What are the consequences**:
Maint drones have the ability to set their own mail tag and travel via disposals, but they can't flush themselves and can't use the ability properly. There's also a whole slew of other situations where a silicon might need to flush a disposal.

**Steps to reproduce the problem**:
Join as a cyborg or drone, attempt to flush a disposal.

**When did the problem start happening**:
Most likely since #13310 was merged.
 

**Extra information**:

**Comment by Ionward** [comment]
Maintenance drones can not use the disposals UI to send themselves, you have to climb in and THEN set your mail tag, and it will send you to the tag destination. Everything else about this sounds unintended, however.

**Comment by Kyep** [comment]
@AffectedArc07

**Comment by AffectedArc07** [comment]
Silicons are unable to flush disposals because the handle is a physical thing, not a digital control (Hence why you can still toggle pump power). I might change this so that borgs themselves can do it, but the AI certainly should not be able to toggle disposal handles because again, its a physical control

**Comment by AffectedArc07** [comment]
Not a bug
