### ISSUE TITLE
Transformations into other races will remove any implants you have

### ISSUE THREAD

**Issue by TheMaveran** [ParadiseSS13/Paradise#14127]
**Issue Description**:
Transforming into another race will yeet your implants into oblivion, chemical and robotic included.

**What did you expect to happen**: 
For you to keep them.

**What happened instead**:
you lose your implants

**Why is this bad/What are the consequences**:
Doesn't make much sense and its pretty damn annoying.

**Steps to reproduce the problem**:
Acquire implant of any type, Transform yourself as Shadowling, Changeling, Using drake potion(skeleton), Colossus crystal(clown), or Slime mutation toxins; then cry as your implants are gone. There are probably more methods of transformation that do the same thing.

**When did the problem start happening**:
For as long as I can remember

**Extra information**:
naw. However many of the transforms seem to also remove mutations when you should keep them, but in some cases they are kept. More inconsistent stuff.

**Comment by matttheficus** [comment]
seems fixed as per above?
