### ISSUE TITLE
Prayer beads nullification stacks to insane values.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14136]
**Issue Description**:

Prayer beads nullification to vampires can be stacked multiple times in a row, preventing a vampire from using powers at all, effectively. 

**What did you expect to happen**: 

Prayers beads to apply their effect, and if applied again, refill the nulification to the beads amount, but not go higher.

**What happened instead**:

You can stack the nullification, leading to vampires being nullified to 20 minutes or more.

**Why is this bad/What are the consequences**:

You should not be able to make a vampire unable to use any abilities for 20+ minutes by using a null rod a few times, it should only nullify them for 4 minutes and have to be refreshed.

**Steps to reproduce the problem**:

Get a vampire and chaplain.
Nullify with the beads, look at the nullify value.
Use the beads again, see how the value is added.

**Comment by Sinestia** [comment]
Seems to be working as intended, I assume it's like this so that there's interaction between the multiple sources of nullification.

 Even first application doesn't _really_ last for 120 seconds, because being in the presence of it will add on like 10 seconds.


Diminishing returns or a cap could still be a good idea on their own of course

**Comment by farie82** [comment]
Easy first issue. The logic here is incorrect yet is easy to fix

**Comment by farie82** [comment]
Just checked the other instances where `nullified` gets modified and the prayer beads ain't the only one having this issue

**Comment by mokulus** [comment]
What should the logic be for this? `nullify` means the time that vampire is disabled, but how should this be calculated?

**Comment by farie82** [comment]
Ill give my quick thought on what I think the designer originally wanted.
He wanted to make the nullify be a max of 120. So he used max... which is the incorrect method for this.
