### ISSUE TITLE
Chameleon Flags rigged with Minibombs cannot be lit on fire normally

### ISSUE THREAD

**Issue by Marginalorb** [ParadiseSS13/Paradise#14138]
**Issue Description**:
If you rig a Chameleon flag with a syndie minibomb you can't set it on fire unless you have a fire in the same space, say by burning it with a flamethrower for example

**What did you expect to happen**: 
I expected to be able to light the flag on fire with a lighter or welding tool.

**What happened instead**:
The flag became unburnable once given a bomb, confounding myself and abydos

**Why is this bad/What are the consequences**:
It basically makes the chameleon flag useless outside of being something syndies can buy for giggles.

**Steps to reproduce the problem**:
Get a chameleon flag, set it to any flag type, add a minibomb, cry because you just wasted 7 TC on a flag and bomb.

**When did the problem start happening**:
No clue when it could've started, but issue was noticed and tested by myself and abydos on Aug 23rd 2020

**Extra information**:
N/A

**Comment by RedWolfie** [comment]
I'm looking into this
