### ISSUE TITLE
You can flash paper messages on deactivated cameras

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14154]
**Issue Description**:

You can click on a camera with paper to display a message to the AI, even if the camera wires are cut / camera is broken

**What did you expect to happen**: 

Nothing to happen

**What happened instead**:

Ai receives messages despite not being able to see out of said camera, it does not make sense

**Why is this bad/What are the consequences**:

If a solitary prisoner is being a shit and spamming the AI camera, you should be able to cut the camera to keep the shitter from spamming the AI with paper. Due to this bug, you cant, and have to remove the camera from the wall.

(frankly papers to AI should be logged / ai should be able to mute them without admins / other people getting involved)

**Steps to reproduce the problem**:

Cut a cameras wires / find a disabled camera
Click on it 50 times in a row with a paper
Watch as the AI wants to murder you, despite the camera not working

**Comment by farie82** [comment]
Easy first issue. Need to check if the camera is activated before doing all the paper showing logic
