### ISSUE TITLE
Reinforced Floors Blocking Sight

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#1415]
The exact same problem as #1401 but with reinforced floors (done by applying rods to bare tile-less floors).

Could probably be sorted by turning the lights off and on again, too, but haven't tested that.

**Comment by TheDZD** [comment]
I think the issue may be due to the fact that several fixes to lighting haven't  yet been patched in on the live server. It remains to be seen whether or not this will persist once that has happened.

**Comment by KasparoVy** [comment]
If this is fixed once those patches go live I'll close it np
