### ISSUE TITLE
being able to hold plants in one hand.

### ISSUE THREAD

**Issue by DeusExVita** [ParadiseSS13/Paradise#14160]
**Issue Description**:

if you wrap a plant, when you unwrapp it you will hold it in one hand, not both

**What did you expect to happen**: 

to hold the plant in both hands.

**What happened instead**:

plant one handed

**Why is this bad/What are the consequences**:

i can do surgery while holding a plant

**Steps to reproduce the problem**:

wrap a plant, pick up the wrapping papered plant, unwrap it

**When did the problem start happening**:

its actually been a long time, you could do this for a while now

**Extra information**:

im sad i cant be a plant doctor anymore

**Comment by SabreML** [comment]
Almost a four year old issue! #5997, #12732
Someone should probably fix that at some point.
