### ISSUE TITLE
ID consoles downloaded Laptops/Tablets are missing the 'Demotion' button.

### ISSUE THREAD

**Issue by Sky-Ping** [ParadiseSS13/Paradise#14167]
**Issue Description**:
When you download the ID console app onto a Laptop or Tablet and install the relevant ID Card attachment from RnD, the console is missing the red 'Demotion' button which is present on the main HoP console counterpart.

**What did you expect to happen**: 
Underneath the Name and Account Number section, there should be two long red buttons, one for demotion and one for termination.

**What happened instead**:
Underneath the Name and Account Number section, there is only one long red button, for termination.

**Why is this bad/What are the consequences**:
One of the biggest advantages to having an ID console in your pocket is so that you can change ID and demote people on the spot without having to walk to the bridge to demote it there.  A big reason why demotions may be discouraged is because of the time having to move to the HoP office and back, while demotions via laptop/tablet are much more efficient and time saving. Demotions with the laptop/tablet right now can only be done by setting jobs to 'Civilian', which while effective isn't Standard Operating Procedure.  ID consoles on the ground and ID consoles installed onto Laptops/Tablets should have the exact same interface for standardization.

**Steps to reproduce the problem**:
1. Assemble a Laptop or Tablet at Primary Tool storage with all available parts.
2. Install an ID card slot reader, available from RnD at a certain tech level.
3. Download the ID console software, the first option on the screen (this may require you to have HoP or Captain level ID access to be available)
4. Compare the laptop/tablet ID Console to the HoP office/Bridge ID Console.

**When did the problem start happening**:
This problem was made aware to me a couple hours ago, I am not sure for how long this problem has existed.

**Extra information**:
Just think about how badass you'll be when you walk into the chemists office, watch them making meth, and then take their ID and demote them on the spot.  Now imagine actually clicking the demote button on the ID instead of clicking civilian.

**Comment by Kyep** [comment]
When I do TGUI ID computers, I am likely to just totally axe the modular ID card program.

**Comment by Kyep** [comment]
@AffectedArc07 This issue can be closed.
