### ISSUE TITLE
Round start security borg could not take the security module while there was only one other security borg

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#14173]
**Issue Description**:
As AI one of my borgs could not pick the security module while there only was one other security borg active

**What did you expect to happen**: 
Two security borgs to be the max.

**What happened instead**:
The borg got a message saying there were already two which is the max

**Why is this bad/What are the consequences**:
It's a bug

**Steps to reproduce the problem**:
Have two borgs
Have one go sec
Have the other go sec

**When did the problem start happening**:
Noticed first the 28th of august. Probably an issue since the borg rework

**Extra information**:
The borg did have the security module according to the AIs status panel. Both modules of the borgs were security. Yet the second borg still had no module selected.
No runtimes were spotted that round

**Comment by Kyep** [comment]
@AffectedArc07
At shift start, the alert level is green.
While 2 secborgs are permitted on red/blue alert, on green only one secborg is permitted.
So the fact the other borg chose secborg module first, means you cannot choose it as well.
This behavior is intended. No bug.
