### ISSUE TITLE
Putting omnizine in as the last ingredient for strange reagent does not make SR

### ISSUE THREAD

**Issue by cptcoffee50** [ParadiseSS13/Paradise#14193]
**Issue Description**:
When making Strange Reagent, if you put the 10u of omnizine last, it won't create SR. Instead it splits and adds the omnizine to the holy water and unstable mutagen. 

**What did you expect to happen**: 
It should have made 30u of strange reagent.

**What happened instead**:
Instead it added the omnizine to both the holy water and the unstable mutagen. The omnizine was unrecoverable from the chem dispenser

**Why is this bad/What are the consequences**:
Omnizine can be hard to come by and messing up what little you are given by the CMO can make it very hard to be able to produce strange regeant

**Steps to reproduce the problem**:
In a bucket mix: 10u of wine,mercury,water. Then add 10u of radium,chlorine,plasma. Finally add 10u of omnizine. It should be evenly split into both unstable mutagen and holy water, but the omnizine will have disappeared and the SR hasn't been created.

**When did the problem start happening**:
I encountered it during a game on 8/29/20

**Extra information**:
![sr](https://user-images.githubusercontent.com/70458330/91649929-e420bc80-ea2d-11ea-807b-4434eead9a77.png)

**Comment by Pennwick** [comment]
Going by the numbers here. Are you certain the syringe wasn't on draw?

10u of omni in the syringe, draws up 2.5 and 2.5 of Hwater and mutagen. Then the reaction would happen inside the syringe and it would look like it vanished.

I don't currently have the code set up on my computer but if anyone is having trouble replicating this it might be the issue.

**Comment by SteelSlayer** [comment]
Unable to reproduce with the given steps. I was able to make SR by adding the 10u of omnizine to 30u holy water and 30u unstable mutagen as the final step.

**Comment by AffectedArc07** [comment]
Cannot be reproduced. Feel free to re-open this at a later date if you can reliably reproduce this issue
