### ISSUE TITLE
Removed internal organs don't process

### ISSUE THREAD

**Issue by ExusA** [ParadiseSS13/Paradise#14203]
**What did you expect to happen**: 
Internal organs don't rot when left on the floor.

**What happened instead**:
Internal organs are supposed to accumulate germs and eventually rot if you leave them outside a body or a freezer for too long, but instead they stay fresh forever. This only seems to happen when the organs are removed via gibbing, extracting them through surgery starts them processing just fine.

**Why is this bad/What are the consequences**:
I think it's not the intended behavior.

**Steps to reproduce the problem**:
Gib a carbon mob, watch the germ_level not rise on its internal organs, and properly rise on external organs.
Surgically remove an internal organ and watch its germ level rise properly.

**Comment by RedWolfie** [comment]
looking into this
