### ISSUE TITLE
Orange Wires

### ISSUE THREAD

**Issue by DevL-Whats-a-jpg** [ParadiseSS13/Paradise#14204]
**Issue Description**:
Cannot color wires orange with crayons.

**What did you expect to happen**: 
Get a orange wire

**What happened instead**:
Wire turned white

**Why is this bad/What are the consequences**:
Its not important but i would like to be able to make orange wire.

**Steps to reproduce the problem**:
Just use a orange crayon on any color of wire, haven't tested it on already orange wire however.

**When did the problem start happening**:
Not sure exactly, just noticed it.

**Extra information**:
Probably happening because when you use a crayon on say wire_red it tries to make wire_orange but wire_orange does not exist so it makes it white, i dunno.

**Comment by DevL-Whats-a-jpg** [comment]
When you place it it reverts to red, however the model that you hold is white.

**Comment by RedWolfie** [comment]
I'm looking into this
