### ISSUE TITLE
DNA Vault Component Issue

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#14223]
**Issue Description**:
When building the DNA Vault, it calls for 5 pico manipulators and 5 super capacitors. It turns out that it can ONLY be pico manipulators, not higher level femto manipulators, despite to my best memory you being able to use higher level components in most machines than are what is called for upon construction? Dunno if this affects the capacitors too

**What did you expect to happen**: 
Expected that pico or higher would count for building the DNA Vault

**What happened instead**:
Femto manipulators are TOO GOOD for the DNA Vault

**Why is this bad/What are the consequences**:
Illogical in a world where we do upgrades to every machine, and a pain when you've already got a pile of femtos from said upgrades.

**Steps to reproduce the problem**:
Build DNA Vault machine. Try to add femto manipulators.

**When did the problem start happening**:
Probably forever?

**Extra information**:

**Comment by AffectedArc07** [comment]
This is intentional, hence the specification for super capacitors, not just "capacitor". The same applies with the BSA.
