### ISSUE TITLE
Cultist Fale]se

### ISSUE THREAD

**Issue by Propa9** [ParadiseSS13/Paradise#14230]
COMMUNICATION ISSUE

So, there's an issue where Cultist spawn. When the cultist spawn two will spawn but the third will only show as a cultist to the two others but won't be told they're a cultist.

**Comment by farie82** [comment]
Best to keep to the issue template. When did this happen? How was he not told he's a cultist? No icon? No roundstart text? Was his antag status set? And what not. That information will help other contributers solve the issue

**Comment by Propa9** [comment]
Sorry about that. The round was around 12 PM Pacific Time. There was a bubblegum on the shuttle.

Second, he just wasn't a cultist

**Comment by Kiyahitayika** [comment]
Sounds like someone may have AHELPed to not be a Cultist and then Bubblegum distracted Admins.

**Comment by lewcc** [comment]
Not enough info to reproduce and doesn't follow the issue template, closing.
