### ISSUE TITLE
Diona Vampire bug

### ISSUE THREAD

**Issue by DeusExVita** [ParadiseSS13/Paradise#14252]
**Issue Description**:

As a vampire dionas dosnt loose blood.

**What did you expect to happen**: 

like all other races, loose blood as a food source

**What happened instead**:

didnt loose blood

**Why is this bad/What are the consequences**:

diona dont need to feed as vampires

**Steps to reproduce the problem**:

become a diona, be a vampire

**When did the problem start happening**:

as long as i remember.

**Extra information**:

*creaks

**Comment by TheYeetster1** [comment]
*creaks
