### ISSUE TITLE
Diona Slings

### ISSUE THREAD

**Issue by DeusExVita** [ParadiseSS13/Paradise#14253]
**Issue Description**:

Diona slings who hatch have a light and dark meter.

**What did you expect to happen**: 

once you hatch as a sling to have only a darkness meter

**What happened instead**:

both light and dark meter

**Why is this bad/What are the consequences**:

if its still the same, last time i had minor healing in the light

**Steps to reproduce the problem**:

be diona, become sling.

**When did the problem start happening**:

as long as i can remember.

**Extra information**:

*creaks.

**Comment by PacifistDalek** [comment]
*creaks
