### ISSUE TITLE
Refresher Crystal Xenos Outbreak?

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#14266]
**Issue Description**:

You can create a xenomorph outbreak with no admin intervention with what is already on station.
Llamar, the RD's pet is harmless by default but apparently if you kill them then and then use SR on the dead body, it comes back to life as a normal facehugger and will hug whomever they can and implant a xenomorph. At least from what I witnessed that is what happened. 
***EDIT*** Looks like it was a miner using a refresher crystal on gateway facehuggers. As I said I didn't witness this first hand so I wasn't sure what happened. But yeah. Still something to note as space ruins and gateways both can have dead face huggers.

**What did you expect to happen**: 

I'm not sure if it is intentional or not but it seems like an oversight that has never really been looked at before, most shifts llamar just stays in their display case and never comes out so its not surprising people never really checked.
I would expect llamar to come back as a harmless facehugger and not grow their .. uh, whatever it is that they use to implant a xeno egg back.

**What happened instead**:

They grew it back and became a threat!

**Why is this bad/What are the consequences**:

Now that this is known people are going to be using it a lot I tihnk. >..> it might become a new "thing" unless it gets handled. Xenos are out of rotation for being broken but being able to just make them on a whim kind of defeats the purpose. though they would have to start with just a single drone so maybe not entirely dangerous

**Steps to reproduce the problem**:

Kill llamar, apply SR, get face hugged, burst?

**When did the problem start happening**:

I have zero idea, probably forever. Llamar is one of the overlooked pets like renault, nobody pays attention to them because they never leave their owners office

**Extra information**:

This is just from observation, I do not have a test server or anything to test it myself, may need some more testing by someone that does.

**Comment by TheMaveran** [comment]
Is it really an issue though? You’d have to try very hard and have quite a bit of luck to get this. Personally I want to see the hijack miner who actually manages it.
