### ISSUE TITLE
Machine people can drink from condiment bottles

### ISSUE THREAD

**Issue by FunnyMan3595** [ParadiseSS13/Paradise#14270]
**Issue Description**:
Machine people can drink from condiment bottles

**What did you expect to happen**: 
As when eating food, a message that you have no mouth.

**What happened instead**:
You drink the condiment.

**Why is this bad/What are the consequences**:
Machine people aren't supposed to be able to eat.

**Steps to reproduce the problem**:
Create or find a condiment bottle.  Use it on yourself.

**When did the problem start happening**:
Unknown.

**Extra information**:

**Comment by PidgeyThePirate** [comment]
I don't think this is really a bug. Machines can drink, they have a fluid intake port. Granted they shouldn't drink hot sauce, but that's more of a feature request.
