### ISSUE TITLE
Security jacket is invisible for greys.

### ISSUE THREAD

**Issue by Marcolinoj** [ParadiseSS13/Paradise#14276]
**Issue Description**:
Grey's security jacket sprite is now invisible.

**What did you expect to happen**: 
To see the security jacket on my character when I put it on.

**What happened instead**:
When I put on the security jacket, the sprite doesnt appear on my character

**Why is this bad/What are the consequences**:
Makes greys unable to use the alternative to the armor, the security jacket.

**Steps to reproduce the problem**:
Be a grey. and then put on a security jacket

**When did the problem start happening**:
After the grey sprite update, where the armor and hailer were fixed, probably something there broke it.

**Extra information**:
Screenshots of the jacket not showing
![image](https://user-images.githubusercontent.com/61087399/92781440-8455da00-f37a-11ea-94c5-a08b52c9a715.png)
![image](https://user-images.githubusercontent.com/61087399/92781461-891a8e00-f37a-11ea-8c86-2815ec47f9e8.png)

**Comment by SabreML** [comment]
Unable to reproduce, so presumably this was fixed at some point.
