### ISSUE TITLE
Service borg can pick up the nuclear disk, breaking precedent for the NAD

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14281]
**Issue Description**:

The service borg can use its tray to pick up the NAD, leading to a break in precedence around it.

**What did you expect to happen**: 

For the tray to not pick up the NAD

**What happened instead**:

It picks up the NAD and puts it inside the borg

**Why is this bad/What are the consequences**:

Currently, we prevent the crew from putting the disk inside a person, in a way that requires either specialized tools, or gibbing of the person, to take the NAD out. This is why storage implants, and cavity surgery, refuse the NAD from being put inside them in those situation. However, when a service borg does this, this precedent is broken. The borg now has the NAD inside them, killing the borg does not have it drop the item, the borg needs specialized tools, the borg console, a bomb, or an emag and crowbar, to get the NAD out. Worse, when the NAD is "removed", its actually the borg destroying the contents, which means the NAD is teleported to a random part of the station.

**Steps to reproduce the problem**:

Pick service borg
Go to the captains office.
Click on NAD with tray

**When did the problem start happening**:

Probably forever, I heard about it being abused earlier today.

**Comment by taukausanake** [comment]
I kind of want the NAD to be inserted into someone. "You can get dat disk from my cold, dead body." Shame it's not allowed.

This kind of wants me to have a nuke borg just for the lulz. A reskinned borg with nothing special about it but it can deploy as a nuke and be set like the normal one. Then it just stays where it is stationary until it blows. Its sole purpose
