### ISSUE TITLE
Protolathe: recyclicling nanopaste gives more material than crafting it

### ISSUE THREAD

**Issue by SilentPony** [ParadiseSS13/Paradise#14286]
**Issue Description**:
Recycling a nanopaste stack created in protolathe gives more material than was used in crafting it.

A stack of nanopaste requires 7000 metal and glass to create in a protolathe->medical tab. The stack has 6 units (swarms) of nanites. The nanopaste can be inserted back into the protolathe to recycle some of the materials back. Each invidivual unit (nanite swarm) of the nanopaste counts as a full item when recycling in the protolathe and refunds 7000 units of metal and glass. Thus, creating and recycling a nanopaste item gives 6 times the glass and metal that was used back.

**What did you expect to happen**: 
A stack of nanopaste (6 units) should refund 7000 metal and glass when inserted into a protolathe or each unit should refund
1166 metal and glass.

**What happened instead**:
Each individual unit (nanite swarm) of the nanopaste refunded 7000 metal and glass in the protolathe.

**Why is this bad/What are the consequences**:
Protolathe can be used with 7000 metal and glass (and tech to create nanopaste) to create unlimited amount of metal and glass.

**Steps to reproduce the problem**:
Get 3 materials and 2 engineering research level, insert 7000 metal and glass into the protolathe in the R&D department, click on nanopaste in core R&D console->Protolathe Menu->Medical->Nanopaste to create 1 stack of nanopaste, insert back the nanopaste (inserting 1 unit will replenish the materials, inserting the rest will give much more metal and glass in the protolathe), check material storage in the protolathe to make sure the there is indeed a surplus of metal and glass.

**When did the problem start happening**:
Do not know when it started, but I tested on commit fc72297103dc9999e57270252dfdbe995a88ed79 dated Sep 9.

**Extra information**:
Was testing on a locally compiled server after downloading the code.

**Comment by Contrabang** [comment]
Tested this, not able to reproduce. Attempting to use the nanopaste on the protolathe and autolathe gives "Protolathe is fully intact." and "Autolathe is fully intact."

**Comment by Contrabang** [comment]
Tested this with the recycler and destructive analyzer too, currently neither of these actually give back materials of destroyed objects so this isn't a problem there either.
