### ISSUE TITLE
Telecommunication Server Monitor

### ISSUE THREAD

**Issue by BiberDark** [ParadiseSS13/Paradise#1429]
I dont know if this is only a problem for me ?

I configured the Telecomunication Server Monitor 
Network: tcommsat then scanned it .  Worked normally but after that maybe 1 minute later i clicked the console again and then the game freezed for me,

The code was so slow that it took 5 minutes to load 365 Messages
![image](https://cloud.githubusercontent.com/assets/10325479/8451638/faa8cc04-1fe4-11e5-9073-4962b43b828d.png)

Maybe there is something wrong with this. At other server there was no such an complete freeze,

PS: I played as drone

**Comment by PsiOmegaDelta** [comment]
You're most likely running older telecoms code where one mob is created for each message to get some minor data and is then hard deleted.
Other servers store this data in the message to begin with, instead of this mob type.

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, the chat shows that at that moment, the world was restarting?

**Comment by BiberDark** [comment]
The Shutdown was a bit later,it  took me a moment  to produce this screenshot.

**Comment by BiberDark** [comment]
Just want to add the problem still exists. In the last game as human i opened the tcomms console and set it up, everyone who opened it cause a lag fo everybody on the server.

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/telecomms/logbrowser.dm#L64-L135

Here's yer problem

**Comment by PsiOmegaDelta** [comment]
Line https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/telecomms/logbrowser.dm#L78 in particular, with a mob being created (and later deleted) for every message on every refresh. 
This is what most other serves have done away with.

**Comment by Crazylemon64** [comment]
```var/mob/M = new mobtype```

http://i.imgur.com/0Xk0F5W.png

**Comment by Anticept** [comment]
https://github.com/ParadiseSS13/Paradise/pull/6515
