### ISSUE TITLE
Lose sleeping carp when hulked.

### ISSUE THREAD

**Issue by Noobeld** [ParadiseSS13/Paradise#14292]
**Issue Description**:
When you hulk, you lose your Martial Arts Scroll ability, but the sleeping carp tab is still visible.

**What did you expect to happen**: 
Last time I did this they both worked together, it may have been changed though.

**What happened instead**:
You lose all abilities of sleeping carp.

**Why is this bad/What are the consequences**:
There isn't anything to tell you that you've lost the ability, if it's intended that would at least be useful.

**Steps to reproduce the problem**:
Apply scroll, apply Hulk

**Comment by Mitchs98** [comment]
As far as I'm aware this is intentional for balance purposes. You regain sleeping carp and its deflection when you're no longer hulked. You can't deflect with a desword while hulked either as far as I'm aware, also for balance purposes.

**Comment by hal9000PR** [comment]
This is not a bug, this is intended
