### ISSUE TITLE
You cannot eject passengers from a space pod.

### ISSUE THREAD

**Issue by TheYeetster1** [ParadiseSS13/Paradise#14294]
**Issue Description**:

When the passenger in a space pod is dead, or otherwise incapacitated there is no way to remove them from the pod.

**What did you expect to happen**: 

There to be an eject passenger verb when you have a passenger seat in your escape pod. Or at least have the Unload cargo verb eject the passenger.

**What happened instead**:

There is no way to eject a passenger

**Why is this bad/What are the consequences**:

 Having no way to remove a dead passenger makes using the space pod useless to a paramedic.

**Steps to reproduce the problem**:

Get in a space pod with a passenger seat
Put someone inside
be unable to eject them

**When did the problem start happening**:

probably since space pods were implemented

**Extra information**:

I was playing paramedic and got the mechanic to build me a space pod, it was painted blue, and had a passenger seat.

**Comment by TDSSS** [comment]
IIRC, you can simply remove passengers from space pods by clicking them with an empty hand on grab intent.

**Comment by TheYeetster1** [comment]
I am stupid can I delete a bug report?

**Comment by TheYeetster1** [comment]
I am dumb dumb.
