### ISSUE TITLE
TGUI dropdown component text overflow

### ISSUE THREAD

**Issue by RedWolfie** [ParadiseSS13/Paradise#14298]
**Issue Description**:
![dropdown-text](https://user-images.githubusercontent.com/13683223/93105595-8e941300-f6af-11ea-966e-4acdbb9ab69f.png)

**What did you expect to happen**: 
Text not to overflow outside dropdown

**What happened instead**:
Text overflowed outside dropdown

**Why is this bad/What are the consequences**:
UI can look like crap when a long option is selected

**Steps to reproduce the problem**:
Create a TGUI window with a Dropdown component, put in a long text in the selected prop

**Comment by Kyep** [comment]
You have to set the width.

**Comment by Sirryan2002** [comment]
This is a mistake with someone's React/TGUI implementation and not an actual issue with one of our in-game menus
