### ISSUE TITLE
Picking stuff up as a spider bot

### ISSUE THREAD

**Issue by trollateder** [ParadiseSS13/Paradise#1430]
Not sure if it is a bug or intentional but when I pick certain things up as a spider bot(ie. space beer) I blow up and am left as a MMI.

**Comment by TheDZD** [comment]
That's quite odd, spider bots are supposed to be able to pick up small items.

**Comment by KasparoVy** [comment]
give dat spider bot a nuke disk

you know how dem spider bots like the nuke disks

**Comment by Spacemanspark** [comment]
Doesn't happen to me, and I usually get put into spider bots to grab the AI core board for the roboticist.

**Comment by Crazylemon64** [comment]
Can this be reproduced?
