### ISSUE TITLE
Orion trail Ghost Suicide

### ISSUE THREAD

**Issue by Cocacolagua** [ParadiseSS13/Paradise#14303]
**Issue Description**:
If you spam the "Kill a crewmember" button in the arcade game "orion trail", you recieve a bugged message.

**What did you expect to happen**: 
For a videogame ghost to not kill themselves.

**What happened instead**:
![image](https://user-images.githubusercontent.com/48032385/93134897-d31fae80-f6af-11ea-8d52-c1b29e08dd30.png)

**Why is this bad/What are the consequences**:
immersion breaking, a scary creepypasta, do not play orion trail at 3 AM.

**Steps to reproduce the problem**:
1- Start an Orion Trail game.
2- Spam the "Kill a crewmember button"
3- Realize you are playing a haunted copy of Orion Trail.

**When did the problem start happening**:
I don't remember this happening a year ago, but it might have been happening since it was added.

**Comment by farie82** [comment]
Easy first issue. The Topic does not check if you can still kill a crewmember

**Comment by further-reading** [comment]
I believe I have fixed this in https://github.com/ParadiseSS13/Paradise/pull/14503 However I was not able to click fast enough to make the bug happen before changing it so I can't be sure.
