### ISSUE TITLE
Drone Headlamp lights Stay still in pipes

### ISSUE THREAD

**Issue by rapaskoti** [ParadiseSS13/Paradise#14300]
**Issue Description**:

The light stays in one place instead of moving when you're in pipes

**What did you expect to happen**: 

well it to not work or..well move along with the drone

**What happened instead**:

look in the desc

**Why is this bad/What are the consequences**:

it really shouldn't just be doing this 

**Steps to reproduce the problem**:

Go in a vent enter a dark place that has pipes (like maints) then turn your headlamp on and move around

**When did the problem start happening**:
 probably been a problem for..a long time

**Extra information**:

![image](https://user-images.githubusercontent.com/44611123/93121082-f9a01280-f6cc-11ea-9b26-a61453791a3a.png)

The drone is right next to the light on this picture

**Comment by SteelSlayer** [comment]
Duplicate of #13004

**Comment by rapaskoti** [comment]
ah...well i will just close this one then after not going to bed and reading github stuff like a normal person
