### ISSUE TITLE
Wrong access on syndie depot turret control

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#14302]
**Issue Description**:
A player with a 'syndicate operative' ID card was unable to use the external turret controller on the Syndie depot

**What did you expect to happen**: 
for the ID to let you unlock the controller

**What happened instead**:
It didn't

**Why is this bad/What are the consequences**:
You can't do the smart thing

**Steps to reproduce the problem**:
Spawn in a 'syndicate operative' ID card and try to unlock the turret controller on the right of the depot, outside.

**When did the problem start happening**:

**Extra information**:
![Capture](https://user-images.githubusercontent.com/32099540/93130014-2b67a800-f6d2-11ea-81a7-01ecd1b28581.PNG)
I used VV to take a look. On the right you see the turret controller that doesn't work. On the left, you see an internal turret controller as comparison. In the middle, you see the Operative ID card, which has the access it would need.

I assume the cause is incorrectly var-editing the turret controller in question.

**Comment by Kyep** [comment]
It is intended that the external turrets (east side) can be turned on/off with a normal agent ID, but the internal turrets (controlled from panel inside the armory) require an admin ID (syndie commander access).

**Comment by TDSSS** [comment]
@Kyep The issue is that the external turrets (east side) **cannot** be turned on/off with a normal agent ID, or ANY ID in fact. They simply cannot be accessed because their access is borked. Not even a Syndicate officer can unlock the controller.

**Comment by Kyep** [comment]
Yeah, verified. Looks like setting it in the template doesn't work currently.
