### ISSUE TITLE
Vendors won't load their UI without me reloading the game.

### ISSUE THREAD

**Issue by Kobic** [ParadiseSS13/Paradise#14305]
**Issue Description**:
Everytime I buy something from vendors I have to reload the game to get the vendor UI to not appear as a white box

**What did you expect to happen**: 
I expected a vendor UI or a UI for the station APC to come up but instead all I get is white UI boxes.

**What happened instead**:
I can't use vendors without reloading the game. And even after reloading the game I can only use them ONCE before they become white UI boxes again. Strangely I can still use consoles just fine.

**Why is this bad/What are the consequences**:
I can't play as doctor effectively. Imagine having to reload your game everytime you need something from the Nanomed...it just isn't going to work as a doctor...

**Steps to reproduce the problem**:
All I have to do is open a vendor of any kind and I get a white UI box. Reloading the resources doesn't help in any way other than closing the box. Trying to open it without reloading the game itself will lead to the same white UI box.

**When did the problem start happening**:
Only a couple days ago. I think a more recent merge is the issue.

**Extra information**:
I've had multiple other people have issues with vendors for the exact same reason lately so it's not JUST me.

**Comment by hal9000PR** [comment]
This has been a problem with nanoUI for ages. The switch to TGUI should fix this

**Comment by Kyep** [comment]
@Kobic can you please message me on Discord if this is still happening to you? I'd like to track down the source.

**Comment by AffectedArc07** [comment]
This was fixed by changing topic limiting and happened if you opened a machine with 2 TGUI windows (IE: Wires and the vending machine). Feel free to comment if this still happens, but it should be fixed.
