### ISSUE TITLE
Problem with newscasters

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#14304]
**Issue Description**:
Got an error message when attempting to access the NEWSCASTER (not comms console) to the right of the bridge. Eventually caused my game to crash. Problem was initially reported by a player thru ahelp who experienced the same issue. I tested it on myself and replicated it repeatedly.

**What did you expect to happen**: 
For the console to be usable and not cause the game to crash.

**What happened instead**:
Console wasnt usable...game crashed...

**Why is this bad/What are the consequences**:
Error message. Game crashed.

**Steps to reproduce the problem**:
Click the console.

**When did the problem start happening**:
Unknown

**Extra information**:
![image](https://user-images.githubusercontent.com/26615673/93139169-3b6d9080-f6ae-11ea-8234-6899f98707ee.png)

**Comment by AffectedArc07** [comment]
Appears to have been isolated to that round
![image](https://user-images.githubusercontent.com/25063394/93139264-535a0a00-f6d8-11ea-9154-8c29c8417a08.png)

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/93140809-f90e7880-f6da-11ea-8f79-3d424dec253e.png)
Rename approved

**Comment by Kyep** [comment]
@dearmochi maybe flag your TGUI newscaster PR as fixing this (I assume it will)
