### ISSUE TITLE
Possessed Blade pAI Alert Mismatch

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#14312]
**Problem Description**:
When the Chaplain calls for someone to possess their possessed blade, it throws up a pAI available alert in the chat. The icon in the screen itself shows the blade, however.

**What did you expect to happen**: 
When the Chaplain does that, it should say they are looking for a spirit for their blade in the chat.

**What happened instead**:
The prompt states pAI, but when you hit teleport it'll bring you to the chaplain and his blade.

**Why is this bad/What are the consequences:**
Someone unthinkingly could take position in the blade, which is not what they clicked on. 

**Steps to reproduce the problem**:
1. Have the Chaplain take the possessed blade.
2. Call for ghosts.
3. Chat shows a wrong prompt.

**When did the problem start happening**:
Just today, though I'm unsure how long it has been happening.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
This was during a testmerge, so I can't say for sure if this happens every round. However I doubt the TM affected this specific scenario.

**Comment by Kyep** [comment]
@dearmochi
