### ISSUE TITLE
The item 'Spooky Lantern' does not allow the user to have thermal vision when resummoning the wisp.

### ISSUE THREAD

**Issue by HarrisonW1** [ParadiseSS13/Paradise#14313]
**Problem Description**:
The item 'Spooky Lantern' does not allow the user to have thermal vision again when re-summoning the wisp.

**What did you expect to happen**: 
The item 'Spooky Lantern' should enable the user to have thermal vision as long as the wisp is released from the lantern, regardless of the amount of time it gets summoned.

**What happened instead**:
The user is able to gain thermal vision the first time they released the wisp. The problem begins when the user returns the wisp back to the lantern, and then releases the wisp again, where thermal vision is not gained back for the user. The 'Spooky Lantern' also does not provide any additional increase in light.

**Why is this bad/What are the consequences:**
The 'Spooky Lantern' item is not consistent with its mechanic or at least does not indicate to the user that the lantern is only a one-time use. This will disrupt the user experience or immersion during gameplay.  

**Steps to reproduce the problem**:
1. Use Byond client version 1528.
2. Proceed to find 'Spooky Lantern' in Lavaland.
3. Go to a populated area and hide behind a wall from the population.
4. Release the wisp and observe that the mechanic is working as intended.
5. Return the wisp, and re-release the wisp.
6. Observe that the 'Spooky Lantern' mechanic does not work as intended, and cannot be resolved.

Addendum:
1. This issue can be resolve if the user reconnects the game whilst the 'Spooky Lantern' is in use. However, the problem still persist if the user performs Step 5 again.
2. This issue is not resolved if the user reconnects the game whilst the 'Spooky Lantern' is not in use. Releasing the wisp afterwards does not work.

**When did the problem start happening**:
This issue was discovered during a round where "Medical TGUI is being testmerged." I have not played the game in a while so I do not know when this problem exactly started.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
This issue occured in a round where "Medical TGUI is being testmerged.".
![scrnshot1](https://user-images.githubusercontent.com/39963470/93215360-336d2980-f75e-11ea-87c4-5eae73d0e67a.png)
An image showing a populated area in the bar whilst the 'Spooky Lantern' is not turned on.

![scrnshot12](https://user-images.githubusercontent.com/39963470/93215369-3700b080-f75e-11ea-96ca-bffb547bd344.png)
An image showing the 'Spooky Lantern' does not provide thermal vision for the user to observe the fight inside the bar.

**Comment by Breenland** [comment]
I tested it a bit during the round as well and can confirm it wasn't giving any benefits.
