### ISSUE TITLE
Mulebot's dont work

### ISSUE THREAD

**Issue by meow20** [ParadiseSS13/Paradise#14324]
**Issue Description**:
Mulebot's dont react to the "Proceed" command 

**What did you expect to happen**: 
For the mulebot to move to his destination.

**What happened instead**:
Nothing.

**Why is this bad/What are the consequences**:
Mulebots are useless.

**Steps to reproduce the problem**:
Select destination 
Press "Proceed"

**When did the problem start happening**:
I was told about it 14.09.2020

**Extra information**:
"Set destination" and "unload crate" options are working though.

**Comment by Kiyahitayika** [comment]
**Mulebots are useless.**
Agree. :D

Honestly, I don't understand MULEbots x3 I think Kyet was floating the idea of replacing them.

**Comment by Kyep** [comment]
There's really no reason for mulebots to still exist.
Mailing things via wrapper+label+disposals is faster and more efficient.

**Comment by datlo** [comment]
Sometimes disposals get blown up and is unusable. I think mulebot could use a buff to their movespeed, though, it's ridiculously slow even when hacked to go faster.

**Comment by AffectedArc07** [comment]
Believe this has been fixed.
