### ISSUE TITLE
Crew Monitor duplicating crew entries

### ISSUE THREAD

**Issue by procdrone** [ParadiseSS13/Paradise#14322]
**Issue Description**:
Related to #13766

If you leave the crew monitor UI open for extended amount of time, it will generate/copy additional crew entries. It most often happens with Unknowns that dont have their sensors maxed.

**What did you expect to happen**: 
For crew monitor to not generate additional crew entries.

**What happened instead**:
Additional unknowns are shown on the crew list

**Why is this bad/What are the consequences**:
Clutters up the UI.

**Steps to reproduce the problem**:
Be AI, open crew monitor, leave it open for extended time as round goes on. Notice additional Unknowns being on list.
Close the UI and reopen it and they are gone.

**When did the problem start happening**:
Ever since Crew monitor TGUI was merged.

**Comment by procdrone** [comment]
Bugged
![a1](https://user-images.githubusercontent.com/46283583/97068574-0582cc80-15c9-11eb-8425-73d9c498d30e.png)
1 second later, after closing and reopening
![a2](https://user-images.githubusercontent.com/46283583/97068576-074c9000-15c9-11eb-8341-e821e500dcca.png)

**Comment by Oyu-De** [comment]
Aight, time to stop playing paramedic for the time being

**Comment by Drsmail** [comment]
So i found how ro reproduce the bag. 
You spawn 2 pun-puns with Game-panel -> Mobs -> pun
You Turn on yours sensors.
Go to the Crew Monitor interface, click highlight on Unknown.
Enjoy duping)

Also i tryed my best to cheek for sanding duped crew data, but all i found was good. I suspect the problem somewhere with java code, which i am bad with)

![Image](https://github.com/user-attachments/assets/b9abfcf7-3f8e-404e-8956-f5cbc0ed3561)
![Image](https://github.com/user-attachments/assets/cb3e0d32-5ad1-49f7-ad57-b25c081108e2)
