### ISSUE TITLE
Pipes don't always visually connect right at round start.

### ISSUE THREAD

**Issue by DevL-Whats-a-jpg** [ParadiseSS13/Paradise#14323]
**Issue Description**:
Pipes sometimes dont visually connect properly at round start.

**What did you expect to happen**: 
The pipes in atmos to not be little blocks

**What happened instead**:
The pipes to be... pipes.

**Why is this bad/What are the consequences**:
It makes learning atmos a huge pain, as well as just a general eye sore.

**Steps to reproduce the problem**:
It seems to be random, ive seen it a few times with the pipes in the bottom right corner of sci chem but never in atmos, until now.

**When did the problem start happening**:
Maybe a few weeks? haven't exactly kept track, could easily be longer.

**Extra information**:
I did confirm that when they do glitch its not just client side, also here's a screen shot of what i mean. Also only happens to pipes that spawn by default and the pipes work like normal, its just visual. Un-Wrenching the wrenching again does not fix it either.
![piped](https://user-images.githubusercontent.com/53537549/93296702-bf626e00-f7bd-11ea-93a3-5264eaddeaf2.PNG)

**Comment by SteelSlayer** [comment]
Same as #13147
