### ISSUE TITLE
You can pull Blobernauts.

### ISSUE THREAD

**Issue by enderman51505** [ParadiseSS13/Paradise#14343]
**Issue Description**:

You can pull blobernauts using CTRL-click/rightclick -> pull

**What did you expect to happen**: 

for them not to be movable after #14144 

**What happened instead**:

You can pull them

**Why is this bad/What are the consequences**:

You can pull blobernauts away from blob tiles faster than they can go towards it, preventing them from healing

**Steps to reproduce the problem**:

right click ->pull or CTRL click a blobernaut

**When did the problem start happening**:

Probably forever

**Extra information**:

https://cdn.discordapp.com/attachments/755992294624198760/755992320008126521/unknown.png

**Comment by Kiyahitayika** [comment]
That PR was for throwing Blob Spores which is for spawning Blobbernaughts. That PR was, in fact, to prevent Blobbernaughts from _pulling_ the Spores as well so they couldn't powergame in that way.

If Blobbernaughts can pull people and other things, they _definitely_ should be able to get pulled as well.

**Comment by Kiyahitayika** [comment]
Maybe setting blobbernaughts with something like 
`.move_resist == MOVE_FORCE_VERY_STRONG`
or something?
