### ISSUE TITLE
Emitters sometimes fail emitting

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#14346]
**Issue Description**:

Emitters fails emitting

**What did you expect to happen**: 

Emitters with power that are one should emit

**What happened instead**:

The powered emitters did not emit

**Why is this bad/What are the consequences**:

Singularity/Tesla gets free, and everyone breaks immersion by shouting for goat, and admins goats it ruining IMMERSION

**Steps to reproduce the problem**:

I do not know how to reproduce due it just being a bug, however deconstructing and rebuilding it fixes it

**When did the problem start happening**:

**Extra information**:

**Comment by SteelSlayer** [comment]
Was this during engine/containment startup?

**Comment by Spacemanspark** [comment]
From what I've been told and been able to reproduce is that this happens when you set charging on SMES to 'auto' _before_ containment goes up. There's a work around for this that involves deconstructing and reconstructing the emitters, which fixes this problem.

**Comment by SteelSlayer** [comment]
This is working as intended according to, I believe, Fox. You need to set all engineering SMES' charge setting to "off", so they don't pull any power from the western SMES supplying the initial power for the emitters.

**Comment by Kiyahitayika** [comment]
> This is working as intended according to, I believe, Fox. You need to set all engineering SMES' charge setting to "off", so they don't pull any power from the western SMES supplying the initial power for the emitters.

This is how I was taught to set up the engine, so I expect it's working as intended.

**Comment by matttheficus** [comment]
Working as intended.
