### ISSUE TITLE
Silicon feedback for shocking/bolting/emergency access'ing doors doesn't show when using hotkeys.

### ISSUE THREAD

**Issue by enderman51505** [ParadiseSS13/Paradise#14361]
**Issue Description**:

Silicon's no longer get chat feedback from using hotkeys (Alt/Shift/ctrl) on doors, works fine when using the normal door interface.

**What did you expect to happen**: 

for a message to pop up in chat when I electrify a door

**What happened instead**:

No message

**Why is this bad/What are the consequences**:

If you are in a hurry, you can accidently leave 50 damage doors shocked

**Steps to reproduce the problem**:

1.  use a Silicon hotkey on a door
2.  look at chat

**When did the problem start happening**:

Since the TGUI airlock PR

**Extra information**:

Works fine when using the standard door interface.

**Comment by RedWolfie** [comment]
#14359
