### ISSUE TITLE
Lil bots pushing carts

### ISSUE THREAD

**Issue by Cocacolagua** [ParadiseSS13/Paradise#14368]
**Issue Description**:
Janibots, Medibots, Floorbots, Securitrons and all of those little buggers can push jani-carts and paramedic carts the same way someone in harm intent would, which is quite odd behaviour since they go under everything else

**What did you expect to happen**: 
For the bots to go below the cart

**What happened instead**:
Bots used their new-found strenght to push the cart as they go

**Why is this bad/What are the consequences**:
Super annoying in rounds where robotics spam-produces janibots, inconsistent behaviour with everything else

**Steps to reproduce the problem**:
1. Mount a jani-cart / paramedic-cart
2. Try to run over a janibot
3. Janibot starts pushing you instead

**When did the problem start happening**:
No idea, since a long time ago probably.

**Comment by Spacemanspark** [comment]
Nothing bypasses beepsky and his well meaning sidekicks from stopping law breakers
