### ISSUE TITLE
Chef is unable to interact with people outside the kitchen/bar

### ISSUE THREAD

**Issue by Balthusdire** [ParadiseSS13/Paradise#14376]
**Issue Description**:
When heading outside the bar or kitchen, any area the chef has CQC, the chef can not hug, disarm, grab, or hit others.

**What did you expect to happen**: 
To be able to interact normally with people outside the kitchen such as hugging them.

**What happened instead**:
Nothing. No message, no interaction, its like you didnt even click on them.

**Why is this bad/What are the consequences**:
Chef is powerless outside the kitchen. Also can't hug people.

**Steps to reproduce the problem**:
Be chef, head to anywhere your CQC does not normally apply and click on someone on any intent. Nothing happens.

**When did the problem start happening**:
Today, after the martial arts pr was merged.

**Extra information**:
While I don't know if it is related to the martial arts changes, it seems like it might be since CQC still works and I can still hug people and interact normally in CQC areas, but only in CQC areas.

**Comment by KasparoVy** [comment]
LMFAO holy fuck that's hysterical.
