### ISSUE TITLE
Heat Exchangers wrenched to the fabric of space

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#14389]
**Issue Description**:

You can wrench heat exchangers to space, with nothing under them.  You can do this while space walking to space walk infinietely since RPD's do not have ammo. But the weirder thing is you can just wrench them down to nothing on space

**What did you expect to happen**: 

Well.. unless the heat exchanger is tapping into the fabric of reality I dont think you should be able to fasten them down like that.

**What happened instead**:

You can wrench them down in space, probably any where you want.

**Why is this bad/What are the consequences**:

Its just weird? And I guess you can space walk infinetely with an RPD and a wrench. They also make good barricades. but yeah.

**Steps to reproduce the problem**:

RPD a heat exchanger onto space, and wrench it down. Become perplexed.

**When did the problem start happening**:

probably forever ago? This might be the umpteenth time this has been reported.

**Extra information**:

**Comment by datlo** [comment]
afaik all pipes can be wrenched on space tiles and it's intended behaviour to make space loops and such? you're meant to wrench them to other, nearby pipes I guess, which could be added as a requirement for pipes on space tiles.
