### ISSUE TITLE
IPC using wormhole jaunter vomits upon landing

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#14381]
**Issue Description**:

An IPC using the wormhole jaunter, intentionally or falling into a chasm, throws up upon landing wherever it takes them.

**What did you expect to happen**: 

Expected there to be a check to not vomit as IPC. Perhaps something else to make the stun last as long.

**What happened instead**:

IPC vomited upon landing.

**Why is this bad/What are the consequences**:

Immersion breaking. IPC generally don't have the fleshy internals to vomit from.

**Steps to reproduce the problem**:

1: Be IPC.
2: Acquire wormhole jaunter.
3: Use it and walk into the wormhole, or fall into a chasm while it is equipped on your belt slot.

**When did the problem start happening**:

Noticed 19/Sept/2020.

**Extra information**:

Boxstation

**Comment by Kiyahitayika** [comment]
👏 Nice. @iantine  Any idea if IPCs vomit under other circumstances?
