### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by pronyacat** [ParadiseSS13/Paradise#1440]
code\modules\garbage collection\garbage_collector.dm:108:error: proc definition not allowed inside another proc

code\modules\garbage collection\garbage_collector.dm:144:error: unbalanced }
paradise.dmb - 2 errors, 0 warnings
How fix it?

**Comment by Fox-McCloud** [comment]
Try updating to the latest beta version of BYOND; a number of other had this until they did so.

**Comment by pronyacat** [comment]
Thx
