### ISSUE TITLE
AI players view stays at the AI repair console when it's repaired and gets carded again

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#14408]
**Issue Description**:
As AI my view got stuck to the AI repair console in the RD office when I got repaired and carded again

**What did you expect to happen**: 
To follow my body

**What happened instead**:
An outer AI card experience

**Why is this bad/What are the consequences**:
It's a bug

**Steps to reproduce the problem**:
Die as AI. Get put in the console to be repaired. Get put in a card

**When did the problem start happening**:
Unsure

**Extra information**:
I was malf
Reconnecting helped fix the view

**Comment by procdrone** [comment]
It also happens to non malf-AIs, as i've experienced it as well.

The view is fixed if you're put into a core or reconnect(unsure on this one, i think it does), but its an issue nonetheless.

**Comment by farie82** [comment]
Forgot to mention that yeah. Reconnecting fixed the view
