### ISSUE TITLE
Interacting with objects

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#1441]
When you interact with some objects that open a new window the game completely lags out you cant move and when you close the window another one opens until you get away from the object.

**Comment by TheDZD** [comment]
Going to need some specifics as far as what causes intense lag.

**Comment by orelbon** [comment]
what do you mean?

**Comment by orelbon** [comment]
is there a way i can make a video showing this?

**Comment by PJB3005** [comment]
@orelbon @TheDZD probably wants to know WHICH UIs have the issue.

Also, to make a video I recommend using [ShareX](https://getsharex.com/)

**Comment by orelbon** [comment]
https://www.youtube.com/watch?v=CF2BvVGFqvI

**Comment by Markolie** [comment]
Part of https://github.com/ParadiseSS13/Paradise/issues/1623 (I guess?).
