### ISSUE TITLE
TGUI Cam Console (Network?) Issues (New, Rebuilt and Emagged consoles have no cam access. Borg, Video camera and ERT helmet cam feeds are black) 

### ISSUE THREAD

**Issue by Vulkoras** [ParadiseSS13/Paradise#14417]
**Issue Description**:
(Tested primarily on a private server and very tentatively on the live server (screwed/unscrewed then rebuilt the test chamber telescreen and yielded the same results).

(I have little to no understanding of the code/internal workings involved and am only reporting what i've been able to notice in game).

Newly constructed consoles (tried boards from tech storage and protolathe while using various IDs including captain and admin) have no camera access or methods i'm able to find to add access.  

Rebuilt consoles (either fully deconstructed or reset by disconnecting/reconnecting the console with screwdriver) lose their old cam access (tested on bridge, security checkpoint, centcom, RD office and test chamber monitors/telescreens). Issue did not manifest on the detectives wooden tv monitor which retained access/seemed to function as normal (was able to access borg feeds but still black). Rebuilt consoles were not able to monitor borg or ert cameras, however rebuilt entertainment monitors were able to select the video cam feed (black).

Emagging consoles seems to yield no effect.

Borg, video camera and ERT cam feeds can be selected (on appropriate non reconstructed) monitors but only provide a black feed.

**What did you expect to happen**: 
Not certain how to add access to boards/consoles via new system (there may be a method i'm missing in which case I'll be extremely embarrassed/sorry for the foreseeable future) but had expected them to either start with access or some method to gain it given the board in tech storage/new boards via the protolathe.

Expected rebuilt consoles to retain old access based on the behaviour of the detectives monitor and a comment made by AffectedArc07 on the original pull request: 
"All of this has been removed, and networks are now decided by the boards of the subtypes, since having a selection box for networks in this UI size would not work well, and we have a search anyway.

_Originally posted by @AffectedArc07 in https://github.com/ParadiseSS13/Paradise/pull/13750#discussion_r448552223_" 

Expected emagging consoles, telescreens, entertainment monitors, etc to provide full access to cameras normally visible to a full access station console.

Borg/videocamera/ERT feeds providing a mobile camera view of the target.

**What happened instead**:
Inability to access/add cam feeds.

Loss of cam feeds.

No visible effect.

Black feeds.

**Why is this bad/What are the consequences**:
Inability to create usable new cam consoles.

Inability to retain cam access when moving, rebuilding or resetting existing standard cam consoles. 

Loss (possibly intentional?) of an emag feature.

Lack of vision from borg cameras, the telemonitor/librarians video camera not being usable and ERT helmet cams not providing their function (squad oversight?). 

**Steps to reproduce the problem**:
Create a new cam console using either protolathe or tech storage.

Unscrew/Re screw an existing cam monitor/telescreen or fully deconstruct/reconstruct one.  

Use an emag on any cam console, telescreen, etc.

Look at a borg cam feed through a console, the video camera via an entertainment monitor and an ERT helmet cam through the centcom console.

**When did the problem start happening**:
TGUI Cam Console update

**Extra information**:
Uncertain if intentional but you are able to examine via shift clicking through new consoles (Only AI seemed to be able to in previous implementation).

(Apologies for any mistakes/things I missed and my awful verboseness. I've spent most of the year experimenting with/testing in the game/codebase but all the out of game social/contributing stuff is still somewhat beyond me and intimidating (by no fault of the community etc, I'm just not great to say the least with these things). With this being the first time I've written anything of this nature. None of this is intended to be critical/negative in any way, the oddities aside I adore the new consoles and they're fantastic from a usability standpoint (in general the recent flurry of updates/improvements has been phenomenal). I'd just been experimenting to see if the brped works through the new consoles (it does) and came across this while attempting to build a new cam console. I ended up just digging deeper from there but couldn't find any reference to the issues asides from the black borg feeds and figured I should probably try to bring things up in some manner. Sorry again if this isn't the right way to go about it/is otherwise incorrect, i'll happily edit or delete as requested).

**Comment by Kyep** [comment]
@AffectedArc07

**Comment by AffectedArc07** [comment]
I will take a look at this when I can. The network issues and emag issues should be relatively easy to do. Not so sure about the black feeds from video cameras and AI cameras.

**Comment by Spaghetti-bit** [comment]
This has been stale for.... almost a year, I can't seem to reproduce any of the following issues mentioned.
