### ISSUE TITLE
Emagged meteor sats do not increase meteor event weight

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#14413]
**Issue Description**:
Emagged meteor sats do not increase the weight of meteor events, which they should.

**What did you expect to happen**: 
They should make meteor events more common

**What happened instead**:
The base weight of the meteor event gets multiplied by 2...but the base weight is 0, since the event relies entirely on role weight, meaning the emagged sat does nothing.

**Why is this bad/What are the consequences**:
Things don't work as intended

**Steps to reproduce the problem**:
Look at the code for meteor shield sats and see they do
M.weight *= 2
Then look at event_container.dm and notice the weight of meteor events is 0, meaning this does nothing.

**When did the problem start happening**:

**Extra information**:
The meteor event relies entirely on job weighting to fire, which is unaffected by this. It probably should be multiplied by the modifier as well.

**Comment by PacifistDalek** [comment]
This getting fixed would mean that as a hijack cargo traitor you could just keep ordering meteor shields and keep emagging them until you have constant meteor strikes, right?

**Comment by TDSSS** [comment]
It increases the weight of the event, not the frequency of events firing in general. That means you could probably guarantee that moderate event is meteors, but you wouldn't get constant meteor showers.
