### ISSUE TITLE
The 'Start Singularity' debug verb doesn't work

### ISSUE THREAD

**Issue by SabreML** [ParadiseSS13/Paradise#14420]
**Issue Description**:

The `Start Singularity` debug verb doesn't actually start the singularity. Although it does seem to set up everything else.

**What did you expect to happen**: 

Containment goes up, emitters start firing, singularity gets generated.

**What happened instead**:

Containment went up, collectors got filled and activated, emitters activate and.... no singularity.

**Why is this bad/What are the consequences**:

No actual gameplay consequences, since it's a only a debug thing, but it'd still be pretty useful to have.

**Steps to reproduce the problem**:

Start game as an admin, go to the `Debug` tab, click `Debug verbs` to show all of them, click `Start Singularity`.

**When did the problem start happening**:

Presumably right after #11957 was merged, since it replaced the [`/the_singularitygen`](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/power/singularity/generator.dm) in containment with [`/radio/beacon/engine`](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/devices/radio/beacon.dm#L88).

**Extra information**:

The problem code is this here, in [`debug.dm`](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/admin/verbs/debug.dm#L733):
```cs
spawn(30)
    for(var/obj/machinery/the_singularitygen/G in GLOB.machines)
        if(G.anchored)
            var/obj/singularity/S = new /obj/singularity(get_turf(G))
            S.energy = 800
            break
```
I'd fix it myself but I'm pretty tired right now and I'll have forgot by tomorrow, so someone else can do it.

**Comment by Kyep** [comment]
Unsure if its worth fixing this right now, since the entire engine will be re-worked with https://github.com/ParadiseSS13/Paradise/pull/11311 -- at which point this entire proc is gonna need to be re-written anyway.

**Comment by SabreML** [comment]
Fair point, It'll certainly be interesting to see an automated SM setup!

Closing the issue since it'll be invalidated soon:tm:.
