### ISSUE TITLE
Inconsistent Agent ID

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#14468]
**Issue Description**:

Agent IDs are set to be only usable by anyone with a special role, at least for the access copying. It can still be used to fake the ID, if a normal crewmember gets their hands on an unused agent ID.

**What did you expect to happen**: 

Either be able to fully use the agent ID, or not be able to use it at all

**What happened instead**:

Was able to modify the ID to set name, occupation, look, etc., but nothing happened when applied to another ID.

**Why is this bad/What are the consequences**:

Inconsistency, makes it seem a bit broken.

**Steps to reproduce the problem**:

Get a normal crewmember, spawn in an agent ID, let the crewmember use it

**When did the problem start happening**:

Unknown.

**Extra information**:

Can happen if cargo gets emagged and a null crate ordered, many sets do have an agent ID included.
To make it usable, would probably need to change https://github.com/ParadiseSS13/Paradise/blob/c5597b937259aaec789f1ee317af4fce1d1f8f93/code/game/objects/items/weapons/cards_ids.dm#L359, to stop normal crew from total usage, do a similar check in the attack_self part.

**Comment by matttheficus** [comment]
Not an issue, should be useable by first-to-use.

**Comment by matttheficus** [comment]
To add to this, preventing access-stealing while still being able to use the ID allows Syndie Researchers/event characters/etc to still change ID info without the “antag ability” to steal access.
