### ISSUE TITLE
Phazon Punches

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#1448]
These leave attack logs normally, but the quick-jump sends you to 0,0,0 for some reason. I witnessed two phazons smashing an antagonist to death in a prior round, and when trying to jump to them, it just sent me to a black screen 'till I jumped directly to a key.

**Comment by Spoopy11** [comment]
Sounds like it's sending you to the mob, who whilst inside of something like a closet or a mech, is typically located at 0,0,0
