### ISSUE TITLE
Giving a traitor assassinate with a random target through traitor panel can select off station roles 

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14483]
**Issue Description**:

Giving a traitor assassinate with a random target through traitor panel can select off station roles 

**What did you expect to happen**: 

For it to exclude off station roles in its random generation

**What happened instead**:

It selected an off station role, a theta station member

**Why is this bad/What are the consequences**:

Ghost roles, ERT, and admin stuff off the station should not be random targets

**Steps to reproduce the problem**:

Spawn a traitor.
Spawn a ghost role.
Give a traitor a random assassinate target through traitor panel.
Watch as it can the ghost role.

**Comment by farie82** [comment]
This is due to the random picker picking from the same selection of humanoids that admins can select from. Which means every humanoid in the game. Should be an easy issue to fix. Would require some thinking to keep the existing manual selection in place
