### ISSUE TITLE
medical borgs have no reason to use anasthetic 

### ISSUE THREAD

**Issue by kenken244** [ParadiseSS13/Paradise#14492]
**Issue Description**:

medical borgs always ignore surgery fail chance completely, which means that they don't need to use anasthetic or even a proper surgery room, they can literally do surgery in a hallway with their fold out bed

**What did you expect to happen**: 

borgs not using anasthetic is a very big RP/ immersion issue, NOBODY should ever consent to having surgery done on them without anasthetic, and they have no game mechanics that require anasthetic like organic doctors. you could argue that this should be covered by laws, but there's also the arguement that under corporate laws, using anasthetic is a waste of time and resources and therefore causes expenses

**What happened instead**:

**Why is this bad/What are the consequences**:

this really seems like an oversight, while med borgs probably do need to ignore certain causes of failure chance, ignoring all sources completely makes them incredibly strong at surgery, since they can do it anywhere at any time with no chance of failure. in addition, borgs almost never use anasthetic because it is not required, which is very metagamey

**Steps to reproduce the problem**:

be a med borg, pull out a fold out bed in the bar or something and start doing surgery just as well as the best doctor can in a dedicated operating room

**When did the problem start happening**:

probably always

**Extra information**:

**Comment by Spacemanspark** [comment]
This isn't a bug, but a feature/ tweak request, which belongs on the forums.

**Comment by Asmerath** [comment]
they have pain killers though do they not? I'm positive as I was playing mediborg just yesterday.

**Comment by procdrone** [comment]
Yes, mediborgs have Hydrocone, a painkiller.

The OP is pointing out that using it is OPTIONAL given the fact borg has no chance to fail a surgery step, therefore, no reason to use said painkiller.

Borgs have no means to apply Anasthetic, to be fair. they can't put items on people.

**Comment by taukausanake** [comment]
Just going to put #8716 here for reference

**Comment by matttheficus** [comment]
Feature as per #8814
