### ISSUE TITLE
AI/Borg internal cameras are always off

### ISSUE THREAD

**Issue by Muhdi345** [ParadiseSS13/Paradise#14523]
**Issue Description**:

Checking the internal AI camera and borg cameras from a Security camera console will always return a black screen.

**What did you expect to happen**: 

You can never keep an eye on if the AI has been moved or whatnot. And if/since the disable internal cameras power has been added to the Malf AIs you'll also always suspect them of being so.

**What happened instead**:

You only get a black screen, and not even the cut camera screen you otherwise should get.

**Why is this bad/What are the consequences**:

You'd never be able to find a malf AI if he's trying to stealth move itself. Nor would you be able to get a clue for a carded AI's location.

**Steps to reproduce the problem**:

Any camera console will return a black screen on checking a borg/AI internal camera.

**When did the problem start happening**:

Probably from the TGUI update.

**Extra information**:

Never tried asking if other players have the same issue. But everything else works fine for me.

**Comment by Rurik123** [comment]
Also have this issue. Unfortunately I also noticed that the camera map button, where you can look at the map of the station instead of the camera list, is gone. Unsure if this is intentional or not, but it greatly impedes the usefulness of sec cameras for security.

**Comment by Muhdi345** [comment]
https://github.com/ParadiseSS13/Paradise/pull/14602 Should have fixed this. Lets find out!
