### ISSUE TITLE
Vault codes are not working

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14534]
**Issue Description**:

Vault codes in the captains office now show up only with the NT logo and the words Vault codes, centered in the paper.

**What did you expect to happen**: 

For the vault codes to show up.

**What happened instead**:

You get nothing Charley, NOTHING. You loose. Just the logo and the words Vault code.

**Why is this bad/What are the consequences**:

Crew needs to ahelp / ask CC for codes

**Steps to reproduce the problem**:

Start a round.
Look at the vault codes paper. 
See the above mentions.

**Comment by S-CR** [comment]
Can't reproduce this, any additional information?
