### ISSUE TITLE
NT BSOD / Power alarm bluescreen bug

### ISSUE THREAD

**Issue by CrafticalDecoy** [ParadiseSS13/Paradise#14537]
**Issue Description**:

I get this picture basically whenever I wirelessly try to check the power grid either through the power alarm from the CE's PDA or as an engiborg. It's not consistent that sometimes works but when it stops and gives me this screen, it straight up doesn't work anymore.

**What did you expect to happen**: 

Wireless vision of the powergrid.

**What happened instead**:

NT BSOD!

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

Open the PDA, power alert, choose grid power monitor.

**When did the problem start happening**:

**Extra information**:

![unknown](https://user-images.githubusercontent.com/33381354/95053028-205fd080-06f0-11eb-8146-e27cd7273557.png)

**Comment by AffectedArc07** [comment]
I assume this happened when a console you were monitoring got deleted from the world, which caused a null entry. I'll fix this later.

**Comment by CrafticalDecoy** [comment]
That makes sense. Thanks in advance.
