### ISSUE TITLE
Disposal pipes

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#1455]
When welding disposal pipes that make a turn they finish looking straight instead of turned.
![before welding](https://cloud.githubusercontent.com/assets/12041669/8512608/c51e0b76-2318-11e5-8035-c3b321940d18.PNG)
![after welding](https://cloud.githubusercontent.com/assets/12041669/8512609/cad8ef86-2318-11e5-85a7-f39e3abd1144.PNG)

**Comment by Taaketa** [comment]
If someone fixes this. Could you add in the disposal pipes that allow multi directions on it? They are on the map by default. On phone at work so can't grab screens. But will do once I'm home.

**Comment by CrAzYPiLoT-SS13** [comment]
The screenies? Also, the code for pipes looks good. I don't know why it does that. Tried some things, none worked.

**Comment by Taaketa** [comment]
Doh. Forgot. I will do tonight for sure.

**Comment by Taaketa** [comment]
http://imgur.com/Wr1G1Wy

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, I am pretty sure you can make those.

2015-07-21 18:59 GMT+02:00 Taaketa <notifications@github.com>:

**Comment by Taaketa** [comment]
You can pipes that force disposal pipes in one direction. As far as I know these allow disposal pipe traffic to either go straight ahead or turn. Mainly affects those pipes that are also used for delivery.

**Comment by PJB3005** [comment]
You can't build sorting pipes.

**Comment by Taaketa** [comment]
Is there a reason you can't?

**Comment by tigercat2000** [comment]
@Taaketa Yeah, sorting system is generated pre-round. The sorting pipes aren't just magical, they are all tagged and have some overhead to handle getting stuff to it's destination

**Comment by PJB3005** [comment]
@tigercat2000 if you're up for it though, I made them buildable in [this PR on /vg/](https://github.com/d3athrow/vgstation13/pull/4285).
