### ISSUE TITLE
Unbranded Augment appearance changes

### ISSUE THREAD

**Issue by SneakyDamus** [ParadiseSS13/Paradise#14579]
**Issue Description**:
Unbranded augments change your sprite when they never used to before and also look horrible on some races. One of the reasons I believe this is unintentional is that all the branded augments default to an actual head while unbranded is a monitor.

**What did you expect to happen**: 
To be able to to keep my unmodified appearance when getting augmented.

**What happened instead**:
The unbranded augments actually changed my appearance, specifically the head to a monitor.

**Why is this bad/What are the consequences**:
It causes noticeable bugs on some races sprites and discourages augmentation, it's already somewhat niche without turning you into a toaster. 

**Steps to reproduce the problem**:
Augment a body with unbranded augments, can be done on an SM clone or yourself since the result is the same.

**When did the problem start happening**:
I remember it working at least at the start of 2020, I took a long break so I can't narrow down exactly when this started happening.

**Extra information**:
While this isn't essential, I'll love you forever if you can find and revert this change or spare some time to work on a way to have stealthy augments so to speak. I also tried several methods to work around the issue and none worked, if you find any that do work and you can reasonably use IC then I'd also appreciate it.

**Comment by matttheficus** [comment]
Likely not a bug, sprites are just potato-style.
