### ISSUE TITLE
Airlock painter is not functioning as it is meant to be.

### ISSUE THREAD

**Issue by GreeyKorala** [ParadiseSS13/Paradise#14583]
**Issue Description**:

There is an issue with the airlock painter where it is possible to remove windows from an airlock that has windows just by using the "External Maintenance Airlock" option as a paint.

**What did you expect to happen**: 

I expected it to not remove the windows from an airlock and to instead display a requirement message that it normally does when you try to paint a windowless paint onto a windowed airlock. I think this is an issue because it can be used to grief departments where the glass airlock is their only way of seeing outside. Such as the bridge's inner airlocks to enter being changed to windowless making you unable to see outside the bridge from the sides.

**What happened instead**:

What happened instead is the painter removes the windows from an airlock when it is not meant to.

**Steps to reproduce the problem**:

Use the "External Maintenance Airlock" paint on any airlock with windows on it, it will remove them. 

**When did the problem start happening**:

I'm unsure, the assumption is that it has always been this way and no one has noticed. 

**Extra information**:

N/A.

**Comment by GreeyKorala** [comment]
I forgot to remove my super intelligent title that I used before.

**Comment by SteelSlayer** [comment]
I can't reproduce this. It work's just fine by keeping the windows intact.

![cO3GX7E](https://user-images.githubusercontent.com/42044220/95771786-44d42380-0c81-11eb-8963-bf6bc0e685e9.gif)

**Comment by AffectedArc07** [comment]
Cannot be reproduced. Feel free to re-open if you find a reliable way to reproduce the issue
