### ISSUE TITLE
Incorrect chat messages when blind

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#14594]
**Issue Description**:

When player is blind(ed) and other players perform actions in the same screen, the blind player will see those actions in the chatbox with the descriptor "You" as if they are performing those actions. For example: "You hit [airlock/air alarm/etc name]!" There is also a strange message of "You hear !" which I could not decipher the action of.

**What did you expect to happen**: 

Expected to not see "You hear !" or to be told I was hitting things whilst not hitting anything.

**What happened instead**:

The "You hear !" message appears to be an error, and the "You hit [etc]!" appears to need the descriptor corrected.

**Why is this bad/What are the consequences**:

Confusing/misleading chat messages.

**Steps to reproduce the problem**:

1. Be blind. Unsure if it being roundstart/genetic or eye damage makes a difference. In this case, it was from eye damage.
2. Have players around you hit an airlock/air alarm/etc (uncertain what exactly was hit) or perform various actions (not sure what produced the "You hear !" message).

**When did the problem start happening**:
Noticed 12/October/2020.

**Extra information**:

Images:
![1](https://user-images.githubusercontent.com/26665535/95719351-681bc480-0cbb-11eb-9458-10402ef7869a.png)
![2](https://user-images.githubusercontent.com/26665535/95719352-694cf180-0cbb-11eb-81b4-c892d65e2efc.png)
Can confirm I, completely blinded, did not hit anything or do anything other than be pulled around at this time.

**Comment by silverplatedelta** [comment]
Having played a blind character (and a moth) recently, I've not experienced these messages. If this occurs/has occurred recently, please re-open this report. Thanks!
