### ISSUE TITLE
Fiber-Wire Garrote choke is escapable

### ISSUE THREAD

**Issue by Funkmaster-Rick** [ParadiseSS13/Paradise#14590]
**Issue Description**:
Fiber-write garrote kill-choke is escapable. Not sure how. The wiki says the target is supposed to be helpless.

**What did you expect to happen**: 
I expected my target to be completely helpless once choked.

**What happened instead**:
Target was helpless for a while but then escaped the choke and I don't know how.

**Why is this bad/What are the consequences**:
I was syndicate traitor with killing this target as one of my goals. I set up the situation to fully rely on the garrote, so when the garrote didn't function properly my plan was dead and I had no effective way to continue my goals due to being outed as a traitor. It ruined my antag round.

**Steps to reproduce the problem**:
Put garrote in hands, press Z to activate into both hands, left-click target from behind. How they actually escape I have no idea.

**When did the problem start happening**:
Just noticed it 11th October 2020.

**Extra information**:

**Comment by farie82** [comment]
Intended behaviour. The fiber-wire garrote will give you a red grab. Which is breakable if you're very very lucky (or in your case unlucky). Spamming movement buttons or resist will try to free you from the grab. If they win a 5% chance roll they will break free.
To avoid this you need to use the grab once more to get into the kill grab which will render them fully helpless
