### ISSUE TITLE
Vending Machines Can't Read PDA ID's.

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#14591]
See title. This also applies to PDA's held in your hand.

Wearing a PDA with an ID in it, in your PDA slot no longer allows you to purchase things; you have to move it. This is functionality loss.

**Comment by Kyep** [comment]
Having looked into this, this might be a functionality loss, but:
- It is more consistent with how most things work now. Many things that get your ID card use proc/get_idcard() or procs that call it, and this considers IDs in PDAs only if the PDA is worn on your ID slot. Not if it is worn on your PDA slot. Changing get_idcard() would affect other things, and making it use another proc would make it more inconsistent with other objects. Neither seems desirable.
- It is also more consistent with how character identity visibility works (specifically, an ID inside a PDA inside your PDA slot will still result in a masked person reading as unknown, where an ID inside a PDA inside your ID slot will display your name). It would be weird/inconsistent for the player experience if IDs in PDAs on your PDA slot revealed your identity some, but not all, of the time, depending on the person/object looking at you.

It isn't a big deal, but I do think we should aim for consistency.
