### ISSUE TITLE
Glass tables are invisible

### ISSUE THREAD

**Issue by Asmerath** [ParadiseSS13/Paradise#14601]
**Issue Description**:

Glass tables are invisible

**What did you expect to happen**: 

Glass tables to be visable

**What happened instead**:

I make glass table but its invisible

**Why is this bad/What are the consequences**:

can make invisible, impassible terrain that you can't climb without alt clicking the tile

**Steps to reproduce the problem**:

create a table frame out of metal rods, apply glass.

**When did the problem start happening**:

around the time the server was chain crashing, I made a glass table and noticed it was invisible but thought it woulda gotten fixed by now.

**Extra information**:

thats about it!

**Comment by SteelSlayer** [comment]
Unable to reproduce locally. Round-start tables appear fine, as well as crafted ones.

![EAKEy5j](https://user-images.githubusercontent.com/42044220/95802771-014ed900-0cc4-11eb-9841-8b4b901f2881.gif)

**Comment by Asmerath** [comment]
when the whole invincible eevee round happened I was stuck in secure storage with the AI. I tried to build a glass table and it was invisible. Then a couple rounds ago I was on the asteroid bunker and tried to make it pretty with glass tables, those tables were invisible.

**Comment by Asmerath** [comment]
so strange, I just tested it on live servers and its working...

**Comment by SteelSlayer** [comment]
Very weird. Its possible it could have happened in that specific round due to some runtime errors or something.

**Comment by AffectedArc07** [comment]
Very possible that its an isolated bug due to the chain-crashing round and players getting half-self corrupted RSC packages.

**Comment by Kiyahitayika** [comment]
Important to know nonetheless
