### ISSUE TITLE
Not roundstart Security camera console don't list any cameras

### ISSUE THREAD

**Issue by hunakos57** [ParadiseSS13/Paradise#14625]
**Issue Description**:

Newly built Security camera console don't see any cameras.

**What did you expect to happen**: 

See the cameras.

**What happened instead**:

Didn't see any camera listed

**Why is this bad/What are the consequences**:

Renders the console useless.

**Steps to reproduce the problem**:

Build a security camera console OR just screwdrive one off and on.

**When did the problem start happening**:

Can't tell, I would say it come with the new GUI.

**Extra information**:

Keep this information away from antags.  <.<

**Comment by KrossarnTom** [comment]
Don't you need to swipe an ID card, preferable a heads ID card, for it to show specific cameras?

**Comment by meow20** [comment]
I think You have to access the console with high-level ID like hos or captain and enable SS13 network, then after leaving console others should be able to access but the whole system is bit confusing and there is tons of tickets about it so im not even sure of that.
