### ISSUE TITLE
Droid subsystem power monitor NTOS error

### ISSUE THREAD

**Issue by hunakos57** [ParadiseSS13/Paradise#14624]
**Issue Description**:

https://cdn.discordapp.com/attachments/145700319819464704/766591540487258142/unknown.png

**What did you expect to happen**: 

Expected to see a power console.

**What happened instead**:

Blue mean screen

**Steps to reproduce the problem**:

Join as a droid -> select the last tab of the tabs (I think subsystems it was called) -> Click on Power Monitor option -> click on any of the listed consoles -> blue screen

**When did the problem start happening**:

I think it worked before the GUI update, I haven't played as a droid in a long time. 

**Extra information**:

It doesn't even let me go back to the selection menu.

**Comment by AffectedArc07** [comment]
Should be fixed. Feel free to re-open if not.
