### ISSUE TITLE
IPCs sometimes turn bald on death. 

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#14647]
Uh fuck mobile doesn't get the automatic format so here we go with memory

_Hi yes welcome to chili's what is the problem you are having sir:_
IPCs with hair sometimes turn bald on death. I'm not sure if this is consistent in some way, because it doesn't always seem to happen... but it's pretty frequent.

_That's great but why is that ba-:_
Muh hair.

_Uh OK how do we recreate this issue:_
Die as an IPC with hair.

_OK sir would you like to add anything else:_
Three large cheese fries

**Comment by Kiyahitayika** [comment]
_We are very sorry for the inconvenience you have experienced in the rendition of our service, sir. We take all concerns and complaints very seriously. As such, we will be reaching out to Corporate with your request that they no longer shave down IPC heads to give them a fresh-off-the-assembly-line glow when they come out of Robotics. We sincerely apologize for the non-consensual polishing._

**Comment by Spacemanspark** [comment]
I'm going to hack the shoal and banish vox hair

**Comment by Kiyahitayika** [comment]
> I'm going to hack the shoal and banish vox hair

Voxxy has no hair, only quills.

**Comment by Spacemanspark** [comment]
I'm kicking you out of chilis
