### ISSUE TITLE
Central atmospherics computers do not unlock air alarms, and can't use the map to select them with TGUI

### ISSUE THREAD

**Issue by Dashsora** [ParadiseSS13/Paradise#14659]
**Issue Description**:

Central atmospherics computers do not unlock the air alarms, making them unusable to remotely control air alarms.

It is also impossible to pick an air alarm from the map, clicking their icons do nothing, you have to select them from the list.

**What did you expect to happen**: 
To be able to easily and remotely access air alarms.

**What happened instead**:
Couldn't easily and remotely access air alarms.

**Why is this bad/What are the consequences**:

Renders the central computer absolutely useless.

**Steps to reproduce the problem**:

Use a CAC, select an air alarm, be unable to unlock it and unable to do anything with it. Try to click any of the icons on the map.

**When did the problem start happening**:
Ever seen TGUI merge

**Extra information**:

There was also a bunch of additional air alarms labelled something like "All access air alarms" that I couldn't access by any means whatsoever. Sorry I didn't take a screenshot for that.

**Comment by AffectedArc07** [comment]
Could you elaborate on what happens when you try to remotely access them and what access you had at the time? It worked for me during testing just fine.

**Comment by Dashsora** [comment]
https://gyazo.com/e761615f0c02735cce85133be0d07359

As an atmospherics technician. 

The all access air alarms are back in this gif (they weren't in a previous round), as you can see I'm trying to access them, to no avail, and then accessed the armory one, popped up fine, but it was locked. No matter what remote control setting I set it to it wouldn't do nothing either. impossible to access any other functions.

**Comment by AffectedArc07** [comment]
The all access ones appear to appear from `oldstation.dmm` even though ruin levels shouldnt have station contact. 
![image](https://user-images.githubusercontent.com/25063394/96475865-6e1a2400-122c-11eb-9739-b2acee1d8dbf.png)
Other issue will be fixed shortly.
