### ISSUE TITLE
Unknown on crew monitor clones itself and never disappears

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#14666]
**Issue Description**:

Sometime you get multiple unknowns on the crew monitor, 3-4 that had identical amount of damage

**What did you expect to happen**: 

For them not to clone themselves, and for the unknowns to disappear when not unknown

**What happened instead**:

Unknowns a plenty

**Why is this bad/What are the consequences**:

This seems to be a minor oversight that caused this bug, and bugs are bad

**Steps to reproduce the problem**:

Honestly, I do not know how to reproduce 

**When did the problem start happening**:

After the crew monitor got tgui

**Extra information**:

**Comment by SteelSlayer** [comment]
Probably related to #14322

**Comment by procdrone** [comment]
i have updated #14322 with screenshots of the issue if that helps

**Comment by matttheficus** [comment]
Duplicate + more info on #14322
