### ISSUE TITLE
Screen view going black if you reconnect in while in a pipe/vent (Maintenance Drone)

### ISSUE THREAD

**Issue by Badoniondev** [ParadiseSS13/Paradise#14664]
**Problem Description**:
If you exit and rejoin the server while you are in a vent/pipe, the screen view will go black. This occurs in both Scrubbers and Vent(Haven't tested with generic or atmos pipes). Chat and UI keeps working fine, everything else is black. I've only tested this with Maintenance Drones, but it might happen with anything that can ventcrawl. This can be fixed by exiting the vent, however you will not see the pipes, so you have to guess where the exit is.

**What did you expect to happen**: 
To reconnect and for the screen to work properly

**What happened instead**:
The screen went pitch black.

**Why is this bad/What are the consequences:**
Some might not be able to exit vents, ending the round for them unless someone dismantles the pipe or an admin teleports them out of it.

**Steps to reproduce the problem**:
Go into a vent, exit, rejoin, see black screen, hope to find the exit in the pitch black maze.

**When did the problem start happening**:
Noticed it today, i don't remember it happening last year or so however.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I think it always occurs regardless of gamemode. Nothing out of the ordinary in the rounds.

**Comment by Groudonmaster** [comment]
Old Issue but it may have been fixed already. Recent instances of doing this for me results in a different bug of not being able to see pipes until I exit the pipes and re enter

**Comment by Groudonmaster** [comment]
Fixed by #19444

**Comment by Badoniondev** [comment]
I also noticed it was fixed but i forgot i opened the issue about it. Apologies!
