### ISSUE TITLE
Safe NanoUI dial missing

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#14675]
**Issue Description**:
The dial on the safe UI is missing. This is the manual safe seen in the vault, captain's office and so forth.

**What did you expect to happen**: 
An image of a safe dial to appear and turn when you spin it.

**What happened instead**:
There is an error image with a black X, which turns when you spin the dial.

**Why is this bad/What are the consequences**:
We are changing to a new UI and fixing a bugged older UI would be good.

**Steps to reproduce the problem**:
Use any safe on the current build of the game.

**Comment by AffectedArc07** [comment]
All NanoUI images are currently broken. Given that NanoUI is on life support and has 9 UIs remaining to be converted, this wont be fixed.
