### ISSUE TITLE
IPC attempting suicide with salt shaker merely swaps names with it

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#14682]
**Issue Description**:

An IPC who attempts the unique suicide with the salt shaker merely gains the name 'salt shaker (as [IPC name]), whilst the salt shaker gains the IPC's name.

**What did you expect to happen**: 

I expected, as the IPC in question, to die, not to remain in full health with a salt shaker named after me. I've tried this in other species so I'm pretty sure the suicide isn't supposed to leave you alive.

**What happened instead**:

Remained at 100% health with a changed name and a salt shaker named after me.

**Why is this bad/What are the consequences**:

Suicide should not leave the suicidee alive.

**Steps to reproduce the problem**:

1. Be an IPC.
2. Hold a salt shaker.
3. Write 'suicide' in your text bar; click enter and agree to the prompt.

**When did the problem start happening**:

First noticed earlier this year. Confirmed today, 21/Oct/2020.

**Extra information**:

Image:
![sdcdsds](https://user-images.githubusercontent.com/26665535/96697700-ef61ea00-13d7-11eb-9f96-e351442d9af7.png)

**Comment by variableundefined** [comment]
A result of salt shaker returning toxin loss which IPC are immune to
