### ISSUE TITLE
AI "announcement" verb shuffles words

### ISSUE THREAD

**Issue by procdrone** [ParadiseSS13/Paradise#14706]
**Issue Description**:
When trying to speak, game shuffles the order of words seemingly at random

**What did you expect to happen**: 
for everything i put in to be read in order

**What happened instead**:
Words are voiced randomly, shuffled.

**Why is this bad/What are the consequences**:
can't communicate reliably

**Steps to reproduce the problem**:
Be ai, make a lenghtier sentence (few words) using "announcement" verb. hear words but in random order.

**When did the problem start happening**:
as of a week ago

**Extra information**:
yes but no

**Comment by PacifistDalek** [comment]
Maybe related to https://github.com/ParadiseSS13/Paradise/issues/14126 ?

**Comment by procdrone** [comment]
my issue happens even without hologram

**Comment by SabreML** [comment]
Did anyone else hear the words all shuffled or was it just you?

**Comment by meow20** [comment]
I had this happen to me last year multiple times, I thought it was intentional lol

**Comment by procdrone** [comment]
> Do you know if anyone else heard the words all shuffled or if it was just you?

I havent tested it that far, but i **suspect** the shuffling could've been only me, since noone asked me WTF am i speaking & people seemed to understand these messages.

But again, this is only my **suspicion** as I have not tested it.

**Comment by TheYeetster1** [comment]
I have had the same problem, only on a personal test server. Didn't have my config setup too, Maybe related to config?

**Comment by matttheficus** [comment]
Cannot repro.

**Comment by matttheficus** [comment]
Seems it actually DOES still occur, reopening.

**Comment by lewcc** [comment]
This definitely still happens. Still pending a repro.
