### ISSUE TITLE
Light flickering cycles through lights one by one when your boo! ability affects multiple lights

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#14727]
**Issue Description**:

When using your boo! ability as a ghost if your boo! affected multiple light, the lights flicker one by one instead of all of them at once. 

**What did you expect to happen**: 

I expected all of the lights affected by the boo! to flicker at the same time.

**What happened instead**:

One light flickered and the other, which was also affected by the boo waited for the previous light to finish before starting to flicker.

**Why is this bad/What are the consequences**:

Fairly sure this is not intended behavior and it reduces the spookiness levels of light flickering if they flicker one by one instead of all of them at the same time.

**Steps to reproduce the problem**:

1. Be a ghost.
2. Either change the range of your boo ability or find a room, where multiple lights are nearby each other.
3. Use your Boo! ability so that it affects multiple lights at the same time.

**When did the problem start happening**:

Pretty sure it began happening, when this PR was merged: #14396 

**Extra information**:

A gif of the issue in effect. You can see the left one start flickering first and once it finished the right one starts
![1lightatatime](https://user-images.githubusercontent.com/37041561/97109763-c003f380-16dd-11eb-9e80-04374ca9c8a9.gif)

**Comment by SabreML** [comment]
I've done a bit of testing and I'm pretty sure that it wasn't me who broke it. 🤞
Everything in the lighting code works fine still but it's only getting called once the previous spook has finished.

My guess is that it's *maybe* something to do with #13200, but I can't be sure.
