### ISSUE TITLE
Hallucination block does nothing

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#14721]
**Issue Description**:

Genetics Hallucination block ("Your mind says 'Hello'.") does nothing when triggered, either by genetics, rad storm, badmin brew, player panel, etc. Whatever it's supposed to do simply doesn't happen. I've had it ingame, incurred it manually on a test server and waited for effects to take hold, and it's simply a useless block.

**What did you expect to happen**: 

Some sort of action to the block - experiencing hallucinations or something of the sort.

**What happened instead**:

'Your mind says hello', then nothing.

**Why is this bad/What are the consequences**:

It seems the block is working incorrectly.

**Steps to reproduce the problem**:

1. Be a humanoid mob.
2. Have the Hallucination block applied to you through genetics, radiation, player panel, etc (it's applied correctly when you see the message "Your mind says 'Hello'.")
3. It will not affect your round in any way.

**When did the problem start happening**:

Noticed gradually over the last few months.

**Comment by mokulus** [comment]
It seems that mutation [sets hallucination to 20](https://github.com/ParadiseSS13/Paradise/blob/8d687bfd7f8f9ca8e374a45b50fca61833aeadc8/code/game/dna/genes/disabilities.dm#L53), but hallucinations work only when there is [more than 20 units](https://github.com/ParadiseSS13/Paradise/blob/2b9b04acb1ca56b5493b46f6f471a98e481d2108/code/modules/flufftext/Hallucination.dm#L38). Also the probability is only 1%.

Either probability or value of hallucination needs to be increased.
