### ISSUE TITLE
Being a cling disables Alt-clicking to examine a tile or to open a container

### ISSUE THREAD

**Issue by 123Neok321** [ParadiseSS13/Paradise#14753]
**Issue Description**:

Being a cling disabled my ability to alt-click a tile to examine it, or alt-click a container to open it. Upon removal of cling status, I was able to alt-click tiles/containters again.

**What did you expect to happen**: 

Alt-clicking a tile to examine it, or a container to open it.

**What happened instead**:

Nothing, alt-clicking did not open a container nor examine a tile.

**Why is this bad/What are the consequences**:

Being unable to use the hotkeys is pretty annoying.

**Steps to reproduce the problem**:

Started the round with cling enabled, became a cling, was unable to alt-click until I requested an admin remove my status as cling.

**When did the problem start happening**:

Had this problem playing a round on 27/10/20 at GMT 16:20

**Extra information**:

**Comment by SabreML** [comment]
Just to check, did you have any stings selected? That overrides alt-clicking and middle clicking.

**Comment by SteelSlayer** [comment]
Do you know if you had activated or used one of your targeted stings (DNA sting) *before* this issue happened, or was it right at the start of the round?
