### ISSUE TITLE
Janitor [Cricket Model] Borgs who have their battery removed and put back in do not turn back on.

### ISSUE THREAD

**Issue by TheYeetster1** [ParadiseSS13/Paradise#14756]
**Issue Description**:

When playing as a janitor borg, if you have your Battery removed for upgrades or a new battery, you will not turn back on once the battery is re-inserted. Your power will be at full but your system status will read: Non-functional 

This has happened to me twice (2x) don't know if other people experience the same problem.

Also occurred when playing as a janitor borg, Accidently hit myself with a light replacer and was permanently disabled. Even a admin revive did not fix the issue. Admin teleported me to robotics, they could not fix me and had to remove my brain.

**What did you expect to happen**: 

For you to turn back on 

**What happened instead**:

You remain turned off, and the robotocist has to completely remove your brain and put you in a new body to turn back on.

**Why is this bad/What are the consequences**:

You Shouldn't have to have a new body created just because your battery was turned off.

**Steps to reproduce the problem**:

-Round Start Borg
-Pick Janitor Module
-Pick Cricket sprite (Haven't Tested other sprites)
-Have roboticist remove your battery
-be unable to be turned back on

**Alternatively** 
-Round Start Borg
-Pick Janitor Module
-Pick Cricket sprite (Haven't Tested other sprites)
-Get stunned by hitting yourself with a light replacer
-be unable to be turned back on

**When did the problem start happening**:

About 2 weeks ago, when I started playing Janitor Borg

**Extra information**:

Might be related to issue #14161 
I will try to do some more research, picking other sprites and things.

**Comment by Spacemanspark** [comment]
You can get around this if the roboticist gives you a good whack with a wrench or whatever after putting the cell back in

**Comment by Kiyahitayika** [comment]
>Get stunned by hitting yourself with a light replacer
👀 wut. don't do that D:
> You can get around this if the roboticist gives you a good whack with a wrench or whatever after putting the cell back in
Huh, sounds like some code runs on when the borg is attacked, but not when a battery is put in?

**Comment by Fordoxia** [comment]
I cannot reproduce either of these issues.

**Comment by DGamerL** [comment]
Cannot reproduce - and would doubt that the only mention of this issue would be from 4 years ago - thanks for making the report! Has been fixed somewhere down the line!
