### ISSUE TITLE
Singulo Can Phase Through Containment

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#14766]
**Issue Description**:
The singulo was able to phase through containment despite only being at stage 2

**What did you expect to happen**: 
For the singulo to not get loose

**What happened instead**:
The singulo just up and left containment making the station RIP in peace 

**Why is this bad/What are the consequences**:
Singulo shouldn't be able to phase through containment at stage 2

**Steps to reproduce the problem**:
No clue, what lead up to it happening was it got stranded  in containment at stage one, so it was fed like 5 items to give it a boost so it would move into the PA's line of fire, then once it hit stage 2 it just kind of phased through the containment walls

**When did the problem start happening**:
Wish I knew, but with what little info I have I can't make a guess

**Extra information**:

**Comment by AffectedArc07** [comment]
Was it directly adjacent to containment walls when it went loose? Chances are it expanded and ate its own containment.

**Comment by Leanfrog** [comment]
Containment was left untouched, it physically just left containment while being inside

**Comment by Kepplerx** [comment]
Containment was even standing after it left, and continued to do so, until minutes afterwards
