### ISSUE TITLE
RCD'ing on station lava tiles brings out the VOID

### ISSUE THREAD

**Issue by Peakwastaken** [ParadiseSS13/Paradise#14797]
**Issue Description**:
If you make a lava tile using a lava staff - and then construct-deconstruct a window over it with an RCD, only a black void is left behind.

**What did you expect to happen**: 
Expected there to be either plating, obsdian floor (removed lava), or lava.

**What happened instead**:
The floor was a pitch black void.

**Why is this bad/What are the consequences**:
Muh immersion

**Steps to reproduce the problem**:
Make a lava tile using a lava wand - RCD a window on the same tile, then deconstruct said window.

**When did the problem start happening**:
Noticed it today 31/10/20

**Extra information**:
Probably stems from the fact RCD'ing windows destroys whatever floor tile is below. The void still was effectively plating - you could add and remove floor tiles without problem - but the void wouldn't go away.
![99fe3049304ee481387bfdc90dce81e3](https://user-images.githubusercontent.com/45887317/97778834-54dc7600-1b50-11eb-9bff-aadf45927844.png)

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/13971 should fix this.
