### ISSUE TITLE
AI detector bug

### ISSUE THREAD

**Issue by Quarktal** [ParadiseSS13/Paradise#14830]
**Issue Description**:
So, AI detector detects cryo'd AI, there was new AI, that was 99% not in the area (xeno lab), but the storaged AI was there before cryoing and my AI detector was on red 5 minutes while i waited. I even said provocative false message to make current AI look away, and judjung by chat it did.

**What did you expect to happen**: 
AI detector would'nt detect last position of cryo'd AI

**What happened instead**:
AI detector did detect last position of cryo'd AI

**Why is this bad/What are the consequences**:
I was confused, scared and wasted 5 minutes waiting in a locker for ai to go away

**Steps to reproduce the problem**:
Just walked around with uplink multitool i guess.

**When did the problem start happening**:
Everytime i was near xeno lab

**Extra information**:
round ended at 23:45 GMT+3 time (for logz)

**Comment by farie82** [comment]
I believe the xenobio console "eyes" also make the AI detector go off. Can be wrong though but I've seen them go off around xenobio a lot
