### ISSUE TITLE
Runtime in getpois. Ghost orbit menu

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#14841]
**Issue Description**:
```
Runtime in unsorted.dm,1986: getpois returned something under a non-string name - 
   proc name: stack trace (/datum/proc/stack_trace)
   usr: NAME (CKEY) (/mob/dead/observer)
   usr.loc: The floor (41,145,1) (/turf/simulated/shuttle/floor)
   src: /datum/orbit_menu (/datum/orbit_menu)
   call stack:
   /datum/orbit_menu (/datum/orbit_menu): stack trace("getpois returned something und...")
   /datum/orbit_menu (/datum/orbit_menu): tgui static data(NAME (/mob/dead/observer))
   /datum/tgui (/datum/tgui): open()
   /datum/orbit_menu (/datum/orbit_menu): tgui interact(NAME (/mob/dead/observer), "main", /datum/tgui (/datum/tgui), 0, null, /datum/tgui_state/observer_sta... (/datum/tgui_state/observer_state))
   NAME (/mob/dead/observer): Orbit()
   Orbit (/obj/screen/ghost/orbit): Click(null, "mapwindow.map", "icon-x=17;icon-y=19;left=1;scr...")
```

**What did you expect to happen**: 
It not to runtime

**What happened instead**:
It runtimes. Unsure what the effects are functionally

**Why is this bad/What are the consequences**:
Runtimes are bad

**Steps to reproduce the problem**:
- Have a roundstart borg with "robot" job title.
- Have a ghost open orbit menu

**When did the problem start happening**:
TGUI version of the orbit menu. Runtime observed around 14:00 7/11/2020

**Comment by moxian** [comment]
Steps to reproduce:
- Have a roundstart borg with "Robot" job title.
- Have a ghost open orbit menu

**Comment by Kyep** [comment]
Fixed in https://github.com/ParadiseSS13/Paradise/pull/15011

**Comment by Kyep** [comment]
Not actually fully fixed. See my comment on https://github.com/ParadiseSS13/Paradise/pull/14991
