### ISSUE TITLE
Singulo can (still) noclip through containment.

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#14848]
**Issue Description**:
![dreamseeker-20201105-114931](https://user-images.githubusercontent.com/7831163/98464602-f81a3480-21bb-11eb-9b75-5d3f12e0c049.png)

Sequence of events:
- singularity started
- containment goes offline
- pa disabled
- singulo is stage 1 chilling where my ghost sprite is, not moving (I have no idea how it got there.. Got to stage 2 and then dissipated? does it work like this?)
- containemnt reenabled
- since, as you can see, this is a bit off-center, the PA  was moved to the left so that it can hit the singulo again
- pa is moved, restarted
- after several bursts:
- singulo grows to stage 2 (to the right, properly, doesn't breach containment here)
- and goes straight down, and noclips through south(!) containment

**What did you expect to happen**: 
Singulo stays in containment.

**What happened instead**:
Singuloose.

**Why is this bad/What are the consequences**:
yeah, i dunno...

**Steps to reproduce the problem**:

**When did the problem start happening**:
This particular incident happened on 2020-11-05 11:50 UTC (time approximate).
Notably, this was after #14787 got merged

**Comment by matttheficus** [comment]
Seems #14787 did not fix this.

**Comment by Talik6969** [comment]
Is it not been fixed?
