### ISSUE TITLE
[Borg] Traitor AI cannot hack Borg

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1484]
Could be in connection to to issue #1483. But Traitor AI CAN hack the borg. But the borg recieves no hacked modules and no zero law.

**Comment by Taaketa** [comment]
I haven't been able to test. Did this get fixed in the above commit?

**Comment by Markolie** [comment]
This wasn't fixed by that, but when I redid the robot control console. Mind you that AI's that didn't start the round as AI's can't actually hack borgs.
