### ISSUE TITLE
AI Cannot See Cult Runes

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#14862]
**Issue Description**:
The AI is unable to see cult runes, either at all or just through cams though I'm unsure of which.

**What did you expect to happen**: 
To see the runes that all of sec including my borgs saw

**What happened instead**:
I couldn't see any runes and was slightly confused

**Why is this bad/What are the consequences**:
The runes weren't hidden using a conceal spell yet I couldn't see them as the AI,

**Steps to reproduce the problem**:
1. Be AI
2. Have a cult rune be somewhere
3. Look at where the rune should be, but realize that it isn't visible

**When did the problem start happening**:
Since bloodcult got merged it seems

**Extra information**:

**Comment by hal9000PR** [comment]
this is intended
