### ISSUE TITLE
The internal and external buttons for vents in air alarms are inverted.

### ISSUE THREAD

**Issue by Dashsora** [ParadiseSS13/Paradise#14861]
**Issue Description**:

While using an air alarm to control unary vents, their internal and external settings are inverted since the TGUI merge. They function as they did before, and as they should (external by default, on the left, internal on the right), but are mislabeled : Instead, the internal button is on the left, and the external button is on the right.

**What did you expect to happen**: 
The external mode to check for room pressure, and the internal mode to check for pipe pressure

**What happened instead**:
The complete opposite

**Why is this bad/What are the consequences**:

mislabelled settings could lead to catastrophic atmospherics failures - as well as misunderstanding and confusion

**Steps to reproduce the problem**:
Open an air alarm, check vent settings - notice all default unary vents are on internal by default. Compare tgui with nanoui and realise the settings' LABELS are switched around.

**When did the problem start happening**:

Ever since TGUI merge

**Extra information**:

Once again : everything works fine - it's just the labels that are switched around.

**Comment by Muhdi345** [comment]
I was planning to do this bug report, but I just forgot. I had a heart attack the first time I saw a air alarm with these too.
