### ISSUE TITLE
Pride lavaland mirror change body no longer yeets you to space.

### ISSUE THREAD

**Issue by TheMaveran** [ParadiseSS13/Paradise#14885]
**Issue Description**:
changing body with pride mirror wont yeet you to space.

**What did you expect to happen**: 
You should get yeeted but dont.

**What happened instead**:
can change appearance and race freely

**Why is this bad/What are the consequences**:
can change appearance and race freely

**Steps to reproduce the problem**:
use lavaland pride mirror

**When did the problem start happening**:
probably since mirror TGUI

**Extra information**:
no

**Comment by Kyep** [comment]
It shouldn't yeet you into space, period.
There were shit-tons of times when it yeeted you, that you'd end up inside of a wall on lavaland.
Without fail, people would ahelp this, and it would waste admin time.
It should move you to a FLOOR (not wall!) tile on lavaland.
It should not be able to move you to any other zlevel, or to any tile which is dense (either from a wall, or structure).

**Comment by TheMaveran** [comment]
y e e t

But hey it don't yeet anywhere now.
