### ISSUE TITLE
Bar Sign is invisible once removed

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#14884]
**Issue Description**:
The bar sign turns invisible when you remove it from the wall with a screwdriver

**What did you expect to happen**: 
To have a sign that was able to be moved elsewhere, or one that can't move.

**What happened instead**:
Sign turned invisible, was still interactable via ALT-clicking the tile where it was, and interacting with it via the "floor" tab. When attempting to place it back on a wall, it remained invisible.

**Why is this bad/What are the consequences**:
Invisible items are bad, plus it would be nice to be able to move the bar sign around for bar rearranging.

**Steps to reproduce the problem**:
Unscrew sign with screwdriver.

**Comment by Tuulipommi** [comment]
I think that the problem is that the Bar sign doesn't seem to have a sprite for a open maintenance panel.

**Comment by MarsM0nd** [comment]
Seems to be due to the bar sign being a subtype of decals, and the icon sprite sheet reverts upon deconstruction, so it's trying to find the bar sign in the decals.dmi.
