### ISSUE TITLE
Resting breaks antidrop implant if it is enabled

### ISSUE THREAD

**Issue by VEN0M5** [ParadiseSS13/Paradise#14906]
**Issue Description**:
If you rest & unrest while gripping something with the antidrop implant, you will be unable to ungrip the item and it ends up stuck in your hand. Pressing the antidrop icon will just show you the 'your hands relax' message while it does nothing.

**What did you expect to happen**: 
To be able to lie down with food on a sofa to RP as a lazy bum.

**What happened instead**:
I am now a lazy bum with pizza for hands.

**Why is this bad/What are the consequences**:
You lose a hand slot to use.

**Steps to reproduce the problem**:
1. Convince sci to give you antidrop
2. Convince medbay to implant you
3. Hold an item
4. Enable antidrop
5. Rest and unrest
6. Spam the antidrop button
7. Congratulations, your hands is now said item.

**When did the problem start happening**:
First noticed it during the Griffon event that Norwest did. I was a minion and got the toolbox stuck to my hand.

**Extra information**:

**Comment by moxian** [comment]
Cannot reproduce with the steps provided:

![20201116-054305-3LPB4QuuAe](https://user-images.githubusercontent.com/7831163/99216902-b8aca300-27ce-11eb-9c07-79d6d20f706d.gif)
