### ISSUE TITLE
Atmos mag boots

### ISSUE THREAD

**Issue by DeveloperLoser** [ParadiseSS13/Paradise#14904]
**Issue Description**:
Atmos mag boots seem to randomly turn off, aswell as become stuck on, needing another person to pull them off. This happened to me and the person i was working with (not sure what their username is), their hud element can also dissapear or become glitched, causing them to be stuck on or off.

**What did you expect to happen**: 
Not be eternally bound to my magboots

**What happened instead**:
I needed my co-worker to pull off my boots

**Why is this bad/What are the consequences**:
My immersion! and i don't like being stuck to the floor against my will

**Steps to reproduce the problem**:
Not sure, a-helped it along with some other atmos issues, but it wasn't just me, as i said it happened to my co-worker to

**When did the problem start happening**:
Just today, but i haven't played atmos in a bit

**Extra information**:
Left clicking and right clicking to try and get them off (shows that they exist in bottom left but you cant see that)
[https://gyazo.com/e9032ca54ba213da60bd3bccc067c5c8](url)

My hud with them stuck in the off mode
[https://gyazo.com/4f439cf2a2489bd917e03af95e851592](url)

**Comment by KrossarnTom** [comment]
Weird. I play atmos tech alot and never had this happen to me..
