### ISSUE TITLE
Ventcrawlers can get perma-stuck in server room

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#14910]
**Issue Description**:
Ventcrawling entities who enter server room air scrubber are doomed to forever stay in pipes.

**What did you expect to happen**: 
Be able to exit.

**What happened instead**:
Can't.

**Why is this bad/What are the consequences**:
The round is RUUUUINEEDD

**Steps to reproduce the problem**:
1) Be a ventcrawler (i.e. a drone)
2) climb into Server Room Air Scrubber #1
3) try to exit
4) be sad

**When did the problem start happening**:
Probably since forever.

**Extra information**:
How it looks with floor tiles removed:
![20201116-094927-eJMoEcWLsg](https://user-images.githubusercontent.com/7831163/99237935-076b3480-27f1-11eb-9f9c-11d1c50269e1.gif)

Please note that the scrubber visually connects to the white pipe, not red (even though the piping is shown as red):
![dreamseeker-20201116-094040](https://user-images.githubusercontent.com/7831163/99238018-1d78f500-27f1-11eb-837f-87256800a6f9.png)

This might be fixed by #14432 , but i haven't checked, and honestly it's out of scope.

**Comment by lewcc** [comment]
The new layout of the server room should have fixed this.
