### ISSUE TITLE
Game crashes whenever logging into an ATM with an ID that has had many transactions.

### ISSUE THREAD

**Issue by henriquekill9576** [ParadiseSS13/Paradise#14913]
**Issue Description**:
Opening the ATM with an ID that has had alot of transactions (more than 2k in my test) will freeze the game.

**What did you expect to happen**: 
The game not die and me be able to withdraw my credits.

**What happened instead**:
Game froze, never unfroze again, had to restart.

**Why is this bad/What are the consequences**:
You spend an hour or more trying to get alot of credits and then you are unable to use them properly.

**Steps to reproduce the problem**:
Do alot of transactions, usually from a slot machine.
Put your ID on a ATM
Log in
Watch as the game freezes

**When did the problem start happening**:
Happened last round, never did this many transactions so I don't know if it's been here before.

**Extra information**:
@variableundefined

**Comment by AffectedArc07** [comment]
Likely not related to the amount of credits. If you were spamming slot machines its likely lag due to the sheer amount of transactions being sent forwards and backwards.

**Comment by henriquekill9576** [comment]
Ah yeah that was probably it, I did 2500+ slots that shift

**Comment by AffectedArc07** [comment]
@henriquekill9576 please edit your title to make the issue easier to tell at a glance

**Comment by White-Diavol** [comment]
This will be obsolete of this one gets merged. https://github.com/ParadiseSS13/Paradise/pull/15555

**Comment by matttheficus** [comment]
With the gambling being toned down via #14953 this likely isnt an issue any longer.
