### ISSUE TITLE
[Borg] Spam "SYSTEM ALERT: ENERGY DRAIN DETECTED"

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1491]
Please... can we do something about the SPAM assoicated with this? I don't even know how to get rid of the damn effect. But it's annoying as hell not being able to read fecking chat because of it.

It's not fun and it really intrudes on borgs being able to do their damn job.

For reference see my chat window:

http://i.imgur.com/NzeLpHz.png

**Comment by CrAzYPiLoT-SS13** [comment]
Uhm, the file associated with it has to-do comment in front of the code, but is still included in the dme?
@tigercat2000

**Comment by tigercat2000** [comment]
It's a xenoarch effect, if i recall correctly. Which will probably be covered by the -tg- mining PR.

**Comment by Taaketa** [comment]
I guess this can be closed because of #1476. Seems xenoarch will need a rebuild anyway.
