### ISSUE TITLE
Speed Bike Particle Trail Doesn't Go Away

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#14914]
**Issue Description**:
The speed bike vehicle's trail doesn't fade after a little while like it should

**What did you expect to happen**: 
To see the trail fade away

**What happened instead**:
It remained covering massive swathes of area with the effect

**Why is this bad/What are the consequences**:
It's immense visual noise and can make interacting with things difficult

**Steps to reproduce the problem**:
1. Mount speed bike
2. Drive speed bike
3. Notice that the particles coming from the bike don't go away

**When did the problem start happening**:
Unknown

**Extra information**:

![Screenshot (284)](https://user-images.githubusercontent.com/52841396/99296538-eddbe400-2814-11eb-9e9a-56ccfea2075f.png)

**Comment by SteelSlayer** [comment]
Cannot reproduce locally. Must have been something weird going on with the server, errors or runtimes etc.

![42PmSNl](https://user-images.githubusercontent.com/42044220/99552534-ba1ecc80-2982-11eb-8710-4e3f718557b9.gif)

**Comment by Sirryan2002** [comment]
It appears that pointing effects are also not going away in the provided image. My guess would be is this is a subsystem breaking on the server. Since I could not reproduce it either this will be closed.
