### ISSUE TITLE
Wiki, Forum, Rules, and GitHub links broken

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#14947]
**Issue Description**:
Clicking the links to the Wiki, Forum, Rules, and GitHub in game brings you to broken URLS. Other links in game to webpages are busted too.

**What did you expect to happen**: 
To go the websites correctly

**What happened instead**:
http://%22https//github.com/ParadiseSS13/Paradise%22
![image](https://user-images.githubusercontent.com/32213277/99762072-9e700f00-2ac5-11eb-9fc1-5ae523f17247.png)
(I'm not sure why the copy-pasted URL is different from the one in the screenshot, but perhaps that's related to the bug?)

**Why is this bad/What are the consequences**:
Makes it harder for newbies to get their questions answered, and to read the rules!

**Steps to reproduce the problem**:
Just try to click on the links. I'm using Chrome on Windows 7 if that makes a difference.

**When did the problem start happening**:
_Possibly_ related to https://github.com/ParadiseSS13/Paradise/pull/14613 but maybe related to BYOND itself changing some of this stuff? (i.e. related to the change that required the 14613 pull instead of the pull itself.

**Comment by Kyep** [comment]
This isn't a bug with our code.
It just means you need to update your BYOND version.

**Comment by AffectedArc07** [comment]
Update BYOND. Windows changed how links are handled which broke them in BYOND, but an update is out which fixes it. This is not a server-side bug.
