### ISSUE TITLE
You can make multiple DNA Vaults.

### ISSUE THREAD

**Issue by Shockpoint** [ParadiseSS13/Paradise#14955]
**Issue Description**:
You can make multiple DNA vaults.

**What did you expect to happen**: 
To only have one vault.

**What happened instead**:
There are FOUR.

**Why is this bad/What are the consequences**:
Multiple DNA vaults means multiple free genes without instabilities.

**Steps to reproduce the problem**:
Have the DNA Vault as a station goal, order multiple crates.

**When did the problem start happening**:
I have no idea.

**Extra information**:

**Comment by S34NW** [comment]
I Think this is intended, it gives people something to do on a slow shift!

**Comment by Muhdi345** [comment]
It's not so intended when you can use the same samplers you used for the first DNA vault to instantly be able to choose the next 2 free powers though.

**Comment by S34NW** [comment]
Ah if you can instantly reuse samplers then yeah
