### ISSUE TITLE
Bolas preventing interaction for 10 seconds on resist

### ISSUE THREAD

**Issue by Daman580** [ParadiseSS13/Paradise#14954]
**Issue Description**: When you get ebolaed, and attempt to resist it, you are unable to click on anything, attack, disarm, check your backpack, nothing of that kind. This even occurs when you resist OUT of the bola. This happens for around 10 seconds and then the effect goes away and interactions are normal.

Unable to interact with any items or sprite for 10 seconds after being ebolaed.

**What did you expect to happen**: 

When you get ebolaed, you resist, and it attempts to remove the bola. If you succeed the resist it comes off and you can recheck your run. If you fail it stays on and you are stuck walking.

**What happened instead**:

When you get ebolaed, you resist, and it attempts to remove the bola. If you succeed the resist it comes off but you are unable to interact with any items or mobs for 10 seconds. If you fail it stays on and you are suck walking as well as being unable to interact with any items or mobs for 10 seconds.

**Why is this bad/What are the consequences**:

Security can just ebola you, you resist out of it, and then not be able to fight back for 10 seconds due to stunbatons not being able to click on people as well as harming or disarming any persons.

**Steps to reproduce the problem**:

1. Be humanoid mob
2. Have ebola (not sure about normal bola) thrown and hit you
3. Resist the bola
4. Try to interact with anything for 10 seconds.
5. Be confused.

**When did the problem start happening**:

Happened today, but I believe its been happening for more than a year. Surprised no one has put this issue up yet

**Extra information**:

This is Carl Trent on Byond, message me on discord if you have questions

**Comment by moxian** [comment]
https://github.com/ParadiseSS13/Paradise/blob/50206162686f63cd0848b6dcb2f6d7990bf0f697/code/modules/mob/living/carbon/carbon.dm#L790

No idea why the timing is done via `changeNext_move` (preventing pretty much any other interactions for the duration) and why is `do_after` not sufficient...

**Comment by Qwertytoforty** [comment]
This also seems to effect cuffed people
