### ISSUE TITLE
List of Browser UIs able to be converted to TGUI

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#14968]
The following is a list of non-TGUIs to be converted. This is non time critical and just used as a simple project if someone wants one.

This list intentionally **DOES NOT INCLUDE OOC UIS**. Do not convert purely OOC UIs to TGUI. Your PR will be objected to.

### Pure HTML browser UIs (Black on White) 
- [ ] Magnet control (Firing range) | code\game\machinery\magnet.dm (Will do as part of larger refactor)
- [ ] Space heaters (Same template as ACs likely) | code\game\machinery\spaceheater.dm
- [ ] Message monitoring console | code\game\machinery\computer\message.dm
- [ ] Mass driver and pod doors control | code\game\machinery\computer\pod.dm
- [ ] Mech interface (Includes all sub-equipment like sleepers) | code\game\mecha\mecha_topic.dm
- [ ] All multitool link menus | code\game\objects\objs.dm (This is being killed in another refactor)
- [ ] Human pAI interface | code\game\objects\items\devices\paicard.dm
- [ ] Tracking implant locator | code\game\objects\items\weapons\teleportation.dm
- [ ] Secure storage | code\game\objects\items\weapons\storage\secure.dm
- [ ] Noticeboard | code\game\objects\structures\noticeboard.dm
- [ ] Claw game | code\modules\arcade\claw_game.dm
- [ ] Prize counter machine | code\modules\arcade\prize_counter.dm
- [ ] Stacking machine console | code\modules\mining\machine_stacking.dm
- [ ] Coin mint | code\modules\mining\mint.dm
- [ ] AI alarm alerts | code\modules\mob\living\silicon\ai\ai.dm
- [ ] pAI recruiting | code\modules\mob\living\silicon\pai\recruit.dm
- [ ] Drone installed modules list | code\modules\mob\living\silicon\robot\drone\drone_items.dm
- [ ] Newspapers (Be careful with sanitization) | code\modules\newscaster\obj\newspaper.dm
- [ ] Ninja SpiderOS | code\modules\ninja\suit\SpiderOS.dm
- [ ] Folders | code\modules\paperwork\folders.dm
- [ ] Photos | code\modules\paperwork\photography.dm
- [ ] AI PDA message log | code\modules\pda\ai.dm
- [ ] Dart gun | code\modules\projectiles\guns\dartgun.dm
- [ ] R&D server control | code\modules\research\server.dm 

### /datum/browser popups (White on black)
- [ ] Malf module menu | code\game\gamemodes\malfunction\Malf_Modules.dm
- [ ] Abductor console | code\game\gamemodes\miniantags\abduction\machinery\console.dm
- [ ] Abductor gland dispenser | code\game\gamemodes\miniantags\abduction\machinery\dispenser.dm
- [ ] Abductor experiment machine | code\game\gamemodes\miniantags\abduction\machinery\experiment.dm
- [ ] Atmos tank control | code\game\machinery\atmo_control.dm
- [ ] Disco machine | code\game\machinery\dance_machine.dm
- [ ] Chess boards | code\game\machinery\gameboard.dm
- [ ] Holopads | code\game\machinery\hologram.dm
- [ ] Bot navigation beacons | code\game\machinery\navbeacon.dm
- [ ] Suit storage unit | code\game\machinery\suit_storage_unit.dm
- [ ] Area atmos control (scrubbers console) | code\game\machinery\atmoalter\area_atmos_computer.dm
- [ ] Arcade battle | code\game\machinery\computer\arcade.dm
- [ ] Orion trail | code\game\machinery\computer\arcade.dm
- [ ] Holodeck control | code\game\machinery\computer\HolodeckControl.dm
- [ ] Blueprints | code\game\objects\items\blueprints.dm
- [ ] Crayon + spraycan menu | code\game\objects\items\crayons.dm
- [ ] Mixing bowl | code\game\objects\items\mixing_bowl.dm
- [ ] Deck of cards | code\game\objects\items\toys.dm
- [ ] Robot endoskeleton boot debug (?????) | code\game\objects\items\robot\robot_parts.dm
- [ ] Stack crafting | code\game\objects\items\stacks\stack.dm
- [ ] ID cards | code\game\objects\items\weapons\cards_ids.dm
- [ ] Engineering cart (These 3 can use the same template) | code\game\objects\structures\engicart.dm
- [ ] Food cart (These 3 can use the same template) | code\game\objects\structures\foodcart.dm
- [ ] Janicart (These 3 can use the same template) | code\game\objects\structures\janicart.dm
- [ ] Nanomob battle terminal | code\modules\arcade\mob_hunt\battle_computer.dm
- [ ] IR sensor assembly | code\modules\assembly\infrared.dm
- [ ] Proximity sensor assembly | code\modules\assembly\proximity.dm
- [ ] Timer assembly | code\modules\assembly\timer.dm
- [ ] Bottler | code\modules\food_and_drinks\drinks\bottler\bottler.dm
- [ ] Icecream vat | code\modules\food_and_drinks\kitchen_machinery\icecream_vat.dm
- [ ] Base kitchen machine | code\modules\food_and_drinks\kitchen_machinery\kitchen_machine.dm
- [ ] Gene modder | code\modules\hydroponics\gene_modder.dm
- [ ] Seed extractor | code\modules\hydroponics\seed_extractor.dm
- [ ] Smelting console | code\modules\mining\machine_processing.dm
- [ ] Ore box | code\modules\mining\satchel_ore_boxdm.dm
- [ ] Mob strip menus | code\everywhere.dm
- [ ] AI announcement help | code\modules\mob\living\silicon\ai\say.dm
- [ ] Borg station alarms view | code\modules\mob\living\silicon\robot\robot.dm
- [ ] Borg module lisitng | code\modules\mob\living\silicon\robot\robot.dm
- [ ] Bot controls | code\modules\mob\living\simple_animal\bot\bot.dm
- [ ] Filing cabinet | code\modules\paperwork\filingcabinet.dm
- [ ] Photocopier | code\modules\paperwork\photocopier.dm
- [ ] Turbine & Turbine control | code\modules\power\turbine.dm
- [ ] Particle accelerator control | code\modules\power\singularity\particle_accelerator\particle_control.dm
- [ ] Pandemic | code\modules\reagents\chemistry\machinery\pandemic.dm
- [ ] Reagent grinder | code\modules\reagents\chemistry\machinery\reagentgrinder.dm
- [ ] Experimentor | code\modules\research\experimentor.dm
- [ ] TSci Console | code\modules\telesci\telesci_computer.dm

### Don't Do It 
These UIs have issues, let a maint handle them.
- [ ] ~~Paper~~ (TGUI paper has glaring sanitization issues) | code\modules\paperwork\paper.dm
- [ ] ~~Clipboards~~ Same reasons as TGUI paper | code\modules\paperwork\clipboard.dm
- [ ] ~~Paper bundles~~ (TGUI paper has glaring sanitization issues) | code\modules\paperwork\paper_bundle.dm
- [ ] ~~Library books~~ Dont do this. Same applies for this as TGUI paper | code\modules\library\lib_items.dm
- [ ] ~~Paper holding to cameras~~ Dont do this. TGUI paper has sanitization issues | code\game\machinery\camera\camera.dm

**Comment by Kiyahitayika** [comment]
dear lord

**Comment by KalevTait** [comment]
This seems to be a list of player facing UIs. I'm wondering if it would make sense to do this for Admin facing UIs as well?

**Comment by Sinestia** [comment]
https://github.com/ParadiseSS13/Paradise/pull/16265 

ai_slipper was handled, but is not updated in your list

**Comment by Miraviel** [comment]
@AffectedArc07 
this was done in #18505 

`Labor camp points manager | code\game\machinery\computer\prisoner.dm`

**Comment by Contrabang** [comment]
Thought I'd post a small update so that AA can have an easier time updating this next time he visits here:

### Mentioned
Implant pad - #18556
Guest Pass Terminal - #15414
Destination Tagger - #18155

### Not mentioned, but still TGUI'd
Labor Camp Points Manager - #18505
Biogenerator - #18263

### Removed
Pipe dispensers - REMOVED #18763
Radiation laser - REMOVED #18469
Juicer - REMOVED #18764

### WIP
Health sensor assembly - WIP #19111

**Comment by Burzah** [comment]
I forgot to link to this, but turbine is done with https://github.com/ParadiseSS13/Paradise/pull/21226

**Comment by S34NW** [comment]
Now managed by https://github.com/orgs/ParadiseSS13/projects/4
