### ISSUE TITLE
Brains in MMIs do not speak through runechat

### ISSUE THREAD

**Issue by thaulos-bolsens** [ParadiseSS13/Paradise#14994]
**Issue Description**:
Brains in MMIs do not speak through runechat.

**What did you expect to happen**: 
Brains in MMIs should be able to speak through runechat.

**What happened instead**:
Brains in MMIs do not speak through runechat.

**Why is this bad/What are the consequences**:
People will miss out on what MMIs are saying if they aren't checking the right side chat box.

This is specially bad for brains in MMIs considering they aren't able to do anything else other than talk.

**Steps to reproduce the problem**:
1. Be a brain in MMI.
2. Speak

**When did the problem start happening**:
Runechat probably never added to brains in MMIs.

**Comment by MrTeco** [comment]
they also see ghosts

**Comment by S34NW** [comment]
#15050 fixed the ghost thing
