### ISSUE TITLE
Vending machine bug

### ISSUE THREAD

**Issue by MrTeco** [ParadiseSS13/Paradise#15006]
**Issue Description**:
Vending machines deleting coins

**What did you expect to happen**: 
I inserted 2 coins into an AutoDrobe, I expected being able to return them both or buy 2 items that cost coins

**What happened instead**:
When I inserted a second coin into the vendor, it dissapeared

**Why is this bad/What are the consequences**:
This is bad if you want to buy multiple items from a vendor that cost coins, consequence is you losing coins if you try this

**Steps to reproduce the problem**:
Put 2 coins into a vending machine

**When did the problem start happening**:

**Extra information**:

**Comment by Kyep** [comment]
Can't reproduce this.
When I tried, I inserted the first coin (which worked) then when I tried to insert the second one, it said: "There is already a coin in this machine!" and would not let me insert the second one until the first one was used.
