### ISSUE TITLE
Mining Satchels destroying hydrogen.

### ISSUE THREAD

**Issue by Davdichan** [ParadiseSS13/Paradise#1502]
Raw Hydrogen can be mined normally, resulting in 5 hydrogen ore.

Picking this ore up with your satchel deletes all the ore and leaves one hydrogen in your satchel till you empty it. I.E., mine 4 Hydrogen veins, only yield 1 raw hydrogen ore.

Using a bluespace satchel has the same problem, satchel will collect the ore but only show 1 ore in your satchel no matter how much you hold. Have yet to test this with orebox's and ripleys, but I think those operate normally.

Makes it impossible to get respectable quantities of Metallic Hydrogen for research or Tritium for export and use as MRS Pacman fuel.

**Comment by Fox-McCloud** [comment]
Definitely as bug, but marked as "won't fix" because hydrogen won't be a "thing" post TG mining update. Likewise, the system will be so dramatically changed this will probably not be an issue  (or new issues will crop up) once TG mining goes live.

**Comment by KasparoVy** [comment]
Oreboxes and RIPLEYs with oreboxes work normally.
