### ISSUE TITLE
Issues opening windows with TGUI

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#15028]
**Issue Description**:
TGUI windows currently sometimes bug out. I meant to post this during the test merge, and meant to post this yesterday. But I've been sick(still am) and haven't felt like doing much. Anywho. Essentially some TGUI windows won't open without reloading UI resources(in the case of terminals/consoles/anything you can't stick in inventory or drop) or (in the case of items that can go in inventory) drop/repeatedly put in and out of backpack and click it repeatedly. It won't produce an error(outside of perhaps a runtime on server log), it just simply won't load at all.

**What did you expect to happen**: 
I expected to be able to use the items and consoles like normal. 

**What happened instead**:
Consoles and items could sometimes(frequently) fail to load and be usable at all.

**Why is this bad/What are the consequences**:
UI should work without having to reload it constantly.

**Steps to reproduce the problem**:
1. Click a console or pick up an item with a UI.
2. Use it a few times, being sure to close the window in-between uses.
3. Eventually, it just won't work.
4. Reload UI resources or drop/put in bag repeatedly to get it to work again.
5. Repeat.

**When did the problem start happening**:
Ever since #14957 , I'm assuming. The issue just wasn't reported on the PR itself. It may not be that, but that's when I noticed it was during that test merge.

**Extra information**:
N/A

**Comment by procdrone** [comment]
i have the same issue, for me it was all UI would open normally... but just once. after i closed the window I could not reopen the same TGUI again without reloading. absolute horror.
