### ISSUE TITLE
Telecomms bug: Another core is already active in this sector. Power-up cancelled due to radio interference.

### ISSUE THREAD

**Issue by Cergosum** [ParadiseSS13/Paradise#15046]
**Issue Description**:

Telecommunication core gives the message:
"Error: Another core is already active in this sector. Power-up cancelled due to radio interference." Even after it was rebuilt and refused to turn on.

**What did you expect to happen**: 

The core to turn on, and function normally, or, at least, repeat messages like the Wiki said(if there is two).

**What happened instead**:

Instead I got a message:
Error: Another core is already active in this sector. Power-up cancelled due to radio interference.

**Why is this bad/What are the consequences**:

We never really did get telecomms back up.

**Steps to reproduce the problem**:

Well a believe a terror spider ransacked the AI sat and tore apart the telecommunications core
 and APC's there. A borg(me), a drone, and a sec officer tried to fix it, and we were able to get power back and rebuild the core, We could interact with the machine and change the ID or other configurations. However, it would not turn back on. I even disassembled and reassembled it on another tile. 

**When did the problem start happening**:

I'm not as familiar with the new telecomms.

**Extra information**:

I asked mentors and people in chat, and read and re-read the wiki-page,

**Comment by AffectedArc07** [comment]
Intentional behaviour. Being able to make 2 cores for redundancy and never have comms drop out is boring and powergamey as all hell.

**Comment by Cergosum** [comment]
Makes sense to me. Do you want me to edit the wiki to reflect that?

**Comment by AffectedArc07** [comment]
Please do
