### ISSUE TITLE
Changlings transforming from a wanted person keep their wanted status, till an ID card is removed or face blocking happens

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#15059]
**Issue Description**:

When a changeling transforms from a wanted person, they visually keep the wanted symbol above their head, although examining will say their sec record is clean

**What did you expect to happen**: 

For when you transform to not keep the wanted symbol beside your head.

**What happened instead**:

Cling transforms to a new non wanted form, keeps the wanted symbol beside their head, gets arrested and lynched.

**Why is this bad/What are the consequences**:

It uh, should not have a wanted symbol beside your head if you are not wanted when you transform into someone non wanted with a non wanted ID.

**Steps to reproduce the problem**:

Transform into wanted person as cling.
Transform out.
Note that you are still wanted.

**Comment by farie82** [comment]
Same occurs when using smutagen
