### ISSUE TITLE
Using a hatchet on tower caps in a portable extractor creates 1 plank and deletes all other logs.

### ISSUE THREAD

**Issue by DeveloperLoser** [ParadiseSS13/Paradise#15056]
**Issue Description**:
Placing say, 25, tower cap logs in a portable extractor, then clicking them with a hatchet, yields 1 plank and deletes all 25 logs.

**What did you expect to happen**: 
I expected it to turn 1 log into however many planks its potency decided

**What happened instead**:
i got 1 plank and it deleted all the others

**Why is this bad/What are the consequences**:
Can potentialy ruin a ash walkers way of getting wood, violating laws of physics also isn't good

**Steps to reproduce the problem**:
place however many tower cap logs in a portable extractor, open it in hand, click on the logs with a hatchet

**When did the problem start happening**:
no idea, discovered it 5 minutes ago

**Extra information**:

**Comment by DevL-Whats-a-jpg** [comment]
Turns out its just a graphical error, still not a good thing however
