### ISSUE TITLE
Contractor space helmet does not have grey sprite

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#15094]
**Issue Description**:

Contractor space helmets dont have grey sprite, so big head clips through. Might affect other species that needs a sprite, check syndi softsuits and compare.

**What did you expect to happen**: 

Proper sprite like other syndi softsuits.

**What happened instead**:

Oof my head

**Why is this bad/What are the consequences**:

Lets you see face behind suit. Doesnt look good.

**Steps to reproduce the problem**:

1. Be grey
2. Equip contractor spacesuit helmet

**When did the problem start happening**:

Contractor PR

**Comment by 1080pCat** [comment]
No longer an issue, cant find when this was fixed, but greys have the sprites now.

**Comment by Henri215** [comment]
Tested again and looks like it has been fixed at some point in the past, thank you for reporting.
