### ISSUE TITLE
Money Bags can hold an extreme amount of coins.

### ISSUE THREAD

**Issue by Hematoma** [ParadiseSS13/Paradise#15092]
Issue Description:
Money Bags can hold an extreme amount of coins, and have all of them be dumped out at once.

What did you expect to happen:
I expected to not be able to store so many coins in one bag or to not be able to dump them all at once.

What happened instead:
all the coins got put into one bag.

Why is this bad/What are the consequences:
The server freezes for 5-10 seconds.

Steps to reproduce the problem:
step 1-Input material into a coin making machine.

step 2-Make coins until you have a few thousand.

step 3-Dump them all out.

**Comment by farie82** [comment]
Unable to reproduce. The bag can hold up to 40 coins and has a `CHECK_TICK` call when dumping the inventory. 40 is not that much and the check_tick call will prevent the server from hanging

**Comment by Hematoma** [comment]
did you have the coin press outputting the coins into the bag?
