### ISSUE TITLE
Picking up Playing Cards Deletes the Main Deck

### ISSUE THREAD

**Issue by matttheficus** [ParadiseSS13/Paradise#15115]
**Issue Description**:

If you hold a single card in your hand, then pick up a deck from the ground/table/etc it will just consume the full deck and only leave you with a single card. Its a neat magic trick but making things go poof randomly is bad.

**What did you expect to happen**: 

The deck does not just delete itself

**What happened instead**:

The deck disappears from existence.

**Why is this bad/What are the consequences**:

Things magically disappearing is bad.

**Steps to reproduce the problem**:

1. Draw a card from the deck
2. Pick up the deck of cards
3. Deck disappears and youre left with a single card.

**When did the problem start happening**:

Unsure, noticed it over 3 separate rounds.

**Comment by Oyu-De** [comment]
and they blame me for pulling multiple cards. Outrageous with no evidence. This bug sounds hilarious if mime or clown does it tbh but yeah not much fun when actually trying to play I guess

**Comment by farie82** [comment]
Unable to reproduce. I managed to just grab the deck just fine while I had one card in my hand. Tried both my inactive hand and active hand to be filled with the single card. Also tried to fill both my hands with stuff. Nothing deleted the deck

**Comment by lectronyx** [comment]
I've had this happen to me multiple times, with Dumbdumn1 witnessing it once iirc
