### ISSUE TITLE
Ventcrawling is broken for vents.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#15138]
**Issue Description**:

You can no longer alt click on vents to vent crawl in them

**What did you expect to happen**: 

To alt click on a vent and start climbing into it

**What happened instead**:

shits fucked, vents don't work, only scrubbers

**Why is this bad/What are the consequences**:

stops 50% of pipe entrances break for midrounds, which is bad.

**Steps to reproduce the problem**:

spawn mouse
alt click on vent
nothing happens
alt click on scrubbers
vent crawl.

**Comment by Kyep** [comment]
Cannot reproduce.

**Comment by S34NW** [comment]
Bug happens due to null pipenets, not an actual issue with vents themselves.
