### ISSUE TITLE
Malf AI is not working

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#1513]
I've brought this up in staff chat, but fuck it.

This is an entire gamemode that is being left in the dark, it needs fixing.

Server setup fails when trying to launch the gamemode, and reverts back to lobby

**Comment by Fox-McCloud** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
@Fox-McCloud Have I not said that I have no clue how to fix this multiple times in the past?

**Comment by Regen1** [comment]
@tigercat2000 
@Fox-McCloud 
@TheDZD 

This needs to be fixed, I don't think tiger is the only one capable of looking on that particular part of code, and I certainly hope this won't be a case of "I tried for 5 minutes, lets just leave it broken"

**Comment by CrAzYPiLoT-SS13** [comment]
I have a feeling that this will be one of my famous "abandoned or rejected
for snowflakeyness" projects, but I will give it a shot.
