### ISSUE TITLE
Lighting engine visible, blocks sight of most simulated tiles.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#1515]
This doesn't happen to everyone, but I am experiencing it lately. I've determined that what I am seeing is a visual of the lighting engine, as it goes away when I toggle darkness while ghosted. I can't give much information as to why I am seeing it, but here are answers to most people's instantly-asked questions:

-I have toggled graphics hardware usage on/off in both the in-game menu and BYOND preferences.
-I am updated to the most recent beta version
-I have cleared my BYOND cache
-I have restarted BYOND.

EDIT: After doing all of the above, and restarting my computer, my own issue seems to be fixed. If we could find a way to stop this happening at all, it would be good, though.

**Comment by PJB3005** [comment]
Does it look like ![](https://i.imgur.com/x1w0F0R.jpg)?

If it does, no way to fix it, BYOND issue in correlation to how lighting works

**Comment by Fox-McCloud** [comment]
closing due to lack of response.
