### ISSUE TITLE
Revenant getting stuck in morgue trays

### ISSUE THREAD

**Issue by Draconic-saint** [ParadiseSS13/Paradise#1516]
If a revenant get's stuck inside a morgue tray, for instance when it's closed when he's absorbing the corpse they're  on top off, the screen will stay fixated on that point.

The morgue tray will stay at the center of the screen, but the revenant can still move around freely when he leaves the tray.

I've not yet tried to recreate this.

**Comment by Spacemanspark** [comment]
You can type in 'cancel-camera-view' to fix this in game.

**Comment by CrAzYPiLoT-SS13** [comment]
Is this supposed to be closed, as there is a fix, or we need to fix it in the code?

**Comment by tigercat2000** [comment]
@CrAzYPiLoT-SS13 It's still an issue. For once, a Life() call -should- be calling reset_view(), since revenants don't need things like mechs to work.

**Comment by tigercat2000** [comment]
@Draconic-saint Is this still a thing, after -tg- Life?

**Comment by Crazylemon64** [comment]
Revenants can no longer be dragged into morgue trays, thus this bug exists no longer.
