### ISSUE TITLE
Headcrabs can dupe zombies

### ISSUE THREAD

**Issue by TheSardele** [ParadiseSS13/Paradise#15218]
**Issue Description**:
Headcrabs sometimes create 2 zombies from the same corpse.

**What did you expect to happen**: 
For every corpse to only spawn 1 zombie.

**What happened instead**:
2 identical looking zombies spawned from the same body. Only one of them drops the original corpse.

**Why is this bad/What are the consequences**:
This behaviour is really illogical and makes headcrabs more powerful than they should be.

**Steps to reproduce the problem**:
Spawn a ton of headcrabs, spawn in a corpse, should probably cause the issue as described above.

**When did the problem start happening**:
Probably for as long as headcrabs have been in the game.

**Extra information**:
According to @DoctorDrugs , this also happens with blob spores, but they couldn't reproduce it.

**Comment by SabreML** [comment]
#16405
