### ISSUE TITLE
Golem ID and Mech

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#15210]
I was messing around as a free golem, and finished research and decided to make a mech, shortly after that I lost my ID and couldn't find it, until I looked under the mech...

As a free golem your ID falls off when you exit mechs, from where it should be on your belt to the ground

**What did you expect to happen**: 
The ID to not fall off and remain equipped

Its minor but obnoxious

**What happened instead**:
ID hit ground and annoy me!

It should stay equipped

**Why is this bad/What are the consequences**:

You could lose your ID that way, and if a science traitor was using golems/mechs it could be come a more significant problem.

**Steps to reproduce the problem**:

Be golem, have ID  (Or at least free golem ID) and enter/exit a mech (or at least a durand but ripley as well I think)

**When did the problem start happening**:

Absolutely no Id, just saw it today.

**Extra information**:

**Comment by Aracino** [comment]
This also applies to your belt and pocket items, as I found out.
