### ISSUE TITLE
Duped an IMS while taking it out of a bag.

### ISSUE THREAD

**Issue by gummybaer** [ParadiseSS13/Paradise#15214]
**Problem Description**:
Took an IMS out of a bag, to find a copy remained.

**What did you expect to happen**: 
For there not to be one in the bag, after taking one out and giving it away.

**What happened instead**:
There was an extra IMS in the bag.

**Why is this bad/What are the consequences:**
Depending on the nature of the issue, could possibly enable duplicating items at will.

**Steps to reproduce the problem**:
I printed an IMS along with some implants at R&D, then went to robotics to get them installed. Set the *ONE* IMS i printed on the table. Woke up with implants except for one, nutriment pump, so took that and the IMS and headed to medbay. In medbay took the IMS out of the bag to give it to the CMO. Threw it at the CMO. I find an extra IMS in the bag after the fact. Duplicated. Alternatively i made two and was an idiot. Possible, but unlikely.

**When did the problem start happening**:
Round ID 25230, never experienced this before, happened around 1:30 into the round, character is Hikikaki.

**Comment by matttheficus** [comment]
Stale, cant seem to duplicate.
