### ISSUE TITLE
Pointing No Longer Follows Atoms

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#15220]
Points no longer follows atoms, but instead, is bound to the turf.

This is bad, because it means it's harder to get people's attention when they run off screen and also looks really strange when an atom moves off the tile it's on.

This started occurring ever since: https://github.com/ParadiseSS13/Paradise/pull/14979

@dearmochi

**Comment by dearmochi** [comment]
Except arrows were *always* bound to the turf. All the PR you linked did was to modify the offset through `animate()`.

**Comment by dearmochi** [comment]
Case in point in my `fish-qol` branch (#14749), made a month before the PR in question:
![ctjIC2WBMj](https://user-images.githubusercontent.com/1496804/103438776-04a88f80-4c37-11eb-96db-3afceebb5a51.gif)

**Comment by Spacemanspark** [comment]
This has always been the case

**Comment by Mitchs98** [comment]
Has always happened for me too, never seen it actually follow me after the initial point reaches my sprite/turf I was on when they did it.

**Comment by Kiyahitayika** [comment]
PR https://github.com/ParadiseSS13/Paradise/pull/14979 continued the work done with the pixel-offset of PR https://github.com/ParadiseSS13/Paradise/pull/14084. The pixel offset was done to point to the location of the object, but never appears to have been tied to the atom itself.

Could it be possible to `qdel` the pointer object and create a new one with the remaining time at the new location when an object is moved?

**Comment by dearmochi** [comment]
> 
> 
> PR #14979 continued the work done with the pixel-offset of PR #14084. The pixel offset was done to point to the location of the object, but never appears to have been tied to the atom itself.
> 
> Could it be possible to `qdel` the pointer icon and create a new one with the remaining time at the new location when an object is moved?

That could be a way to solve the issue. I'm just concerned about the clunkiness of the pointer icon teleporting every time an atom moves as well as the performance implications.

**Comment by Fox-McCloud** [comment]
@dearmochi 

Yeah, I'm just misremembering this because I'm dumb, ignore me.

I'll close this.
