### ISSUE TITLE
Golem Rebellion

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#15230]
**Issue Description**:

A servant golem can easily make himself not loyal to his creator through body swapping

**What did you expect to happen**: 

the golem should remain loyal to their original creator even if they swap bodies to a new shell they created

**What happened instead**:

The golem lost his loyalty objective and was instead told to be loyal to himself.

**Why is this bad/What are the consequences**:

If a golem wants to just fuck off and not listen to their master they can easily do so, problematic when they may be used in antag objectives.

**Steps to reproduce the problem**:

Be servant golem loyal to xenobiolgist. Get inert golem shell. Complete it yourself then swap to it. Now you are loyal to yourself.

**When did the problem start happening**:

probably forever ago

**Extra information**:

https://cdn.discordapp.com/attachments/134493088218349578/795012868478861353/Hmm_Yes.png

**Comment by nok-ko** [comment]
[Relevant code](https://github.com/ParadiseSS13/Paradise/blob/e8272302045f219de6953fa5a5092413de894142/code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm#L81-L86) (in `golems.dm`):

```dm
	if(has_owner && creator)
		important_info = "Serve your creator, even if they are an antag."
		flavour_text = "You are a golem created to serve your creator."
		description = "You are a Golem. You move slowly, but are highly resistant to heat and cold as well as blunt trauma. You are unable to wear clothes, but can still use most tools. \
		Serve [creator], and assist [creator.p_them()] in completing [creator.p_their()] goals at any cost."
		owner = creator
```
