### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#1524]
I was just about to fix the holopad issue and I opened the map. Compilation errors present. Recompiled and got these two errors:
code\modules\garbage collection\garbage_collector.dm:108:error: proc definition not allowed inside another proc
code\modules\garbage collection\garbage_collector.dm:144:error: unbalanced }
My code is up to date, I updated it 5 minutes ago.

**Comment by CrAzYPiLoT-SS13** [comment]
I would try to fix them, but I am really confused by LINDA, garbage collector and all that stuff as I am still unexperienced in DM.

**Comment by CrAzYPiLoT-SS13** [comment]
Also, 76 issues... My main priority will be fixing issues until we have 0.

**Comment by tigercat2000** [comment]
You have to use BYOND Beta to compile the code.

**Comment by CrAzYPiLoT-SS13** [comment]
Ah, the dumbass myself. Closing this.
