### ISSUE TITLE
Chameleon projector lets you lock your view on a cardboard box

### ISSUE THREAD

**Issue by Peakwastaken** [ParadiseSS13/Paradise#15251]
**Issue Description**:
Using a chameleon projector inside of a cardboard box, the big ones you can get into, and then move - it'll open the box and give you freedom of movement while your camera remains on the box, until the projector is deactivated.

**What did you expect to happen**: 
My viewpoint following my character.

**What happened instead**:
My viewpoint stayed centered on the box.

**Why is this bad/What are the consequences**:
It can either be a massive inconvenience, preventing you from seeing around your character, or it could be abused to remotely spy on people.

**Steps to reproduce the problem**:
- Get in a box
- Use a chameleon projector
- Move out of the box
- Move around and notice your camera not following yourself

**When did the problem start happening**:
Discovered yesterday, the fifth of january 2021

**Extra information**:
Gif attached for reference

https://user-images.githubusercontent.com/45887317/103805361-76128480-5021-11eb-9db7-e9efddbabb93.mp4

**Comment by Contrabang** [comment]
Fixed by #17719
