### ISSUE TITLE
If you spawn obese, you dont get anything.

### ISSUE THREAD

**Issue by nachomeep** [ParadiseSS13/Paradise#1525]
No PDA, ID, or clothing.

**Comment by CrAzYPiLoT-SS13** [comment]
Have you tried reconnecting?

**Comment by tigercat2000** [comment]
Correction, if you spawn obese as a job that doesn't have an obese version of the jumpsuit, the jumpsuit will burst and delete all your stuff.

**Comment by TheDZD** [comment]
Which job in particular caused this to happen?

**Comment by nachomeep** [comment]
A civilian with a non-gray jumpsuit and roboticist did it for me.

**Comment by RudiPardieck** [comment]
Seems to have been fixed
