### ISSUE TITLE
guest pass

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#1527]
When the guest pass runs out of power it turns into a computer

![guest pass](https://cloud.githubusercontent.com/assets/12041669/8711036/5ed5ca50-2b1c-11e5-9062-0ee9721c4a30.PNG)

**Comment by FalseIncarnate** [comment]
That is likely the result of the guest pass terminals lacking an off-sprite, so they default to their base type's off-sprite.

I'll look into this later, shouldn't be terribly difficult to edit their sprite to create an off-state version

**Comment by PsiOmegaDelta** [comment]
Might want to check laptops (the stationary, nor portable, kind) as well, if you're using those.

**Comment by CrAzYPiLoT-SS13** [comment]
Uhm, in the file of the guest pass, there is no mentioning of an off-state for a guest pass. Furthermore, I don't understand how the system works. There is one file with both the terminal and the pass in it and it's really freaky coded.
@Fox-McCloud
