### ISSUE TITLE
Computers

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#1528]
Plasma and presumably other gases are under the screen 
![plasma computer](https://cloud.githubusercontent.com/assets/12041669/8715140/6ebb85b6-2b4b-11e5-9789-b098ac58d01b.PNG)

**Comment by Spacemanspark** [comment]
So are papers.

**Comment by Nienhaus** [comment]
Well clearly the screens are shining though the plasma and paper.

**Comment by FalseIncarnate** [comment]
Same issue as #1519, it's an issue with the layers of the overlay and other sprites

**Comment by PJB3005** [comment]
Fixable? yes

Would it be fucking conveluted to try and hack this into BYOND's layer system? yes.

Would it lag? probably

**Comment by TheDZD** [comment]
Same issue as #1519.
