### ISSUE TITLE
Mentor ghosts can unlock/lock kitchen lockers

### ISSUE THREAD

**Issue by shmabuu** [ParadiseSS13/Paradise#15296]
**Issue Description**:
You're able to unlock and lock kitchen access lockers as an observer mentor

**What did you expect to happen**: 
Not be able to lock/unlock any locker on the station as a ghost

**What happened instead**:
I was able to lock and unlock the lockers in the kitchen 

**Why is this bad/What are the consequences**:
Ghosts interacting with the game that aren't admins is not intended

**Steps to reproduce the problem**:
- Be a mentor ghost
-alt-click kitchen locked/unlocked lockers

**When did the problem start happening**:
When I became a mentor, no idea how long it's been around for

**Comment by TheYeetster1** [comment]
mentors are pretty spooky

**Comment by iantine** [comment]
Fairly certain it's not a mentor issue, as there are no perms there which would allow for this - and having deadminned to check, can confirm that it's a ghost problem in general.

**Comment by SabreML** [comment]
Seems to have been fixed recently since I can't reproduce it anymore. Presumably by #15552.

**Comment by shmabuu** [comment]
Fixed this is epic
