### ISSUE TITLE
Shadowling ability, "Shadow Walk" caused freezing by mass interaction and "semi-random" teleporting after unfreezing

### ISSUE THREAD

**Issue by Momoberry** [ParadiseSS13/Paradise#15309]
**Issue Description**: After attempting to use Shadow Walk as a sling, it froze my game by making many interactions that flooded my chat, after unfreezing I would be in a random location in the direction I was facing. 
Sling ability is not working as intended and causes client freezing and "teleporting", often putting the user in dangerous situations. Ie. "space, locked in a room, teleporting into the brig reception and being shot by every security officer in the vicinity..."

**What did you expect to happen**:  To be put in an ethereal form that let me walk through objects and be invisible but at the cost of not being able to interact with the physical world while using it.

**What happened instead**: As soon as the ability is activated, it would flood the chat with "You cannot use abilities affecting others while you are traversing between worlds." and proceed to freeze my game for a rough 3-5 seconds. After unfreezing, I would be in a location in the direction I was originally facing several hundred steps away. An example of this would be me teleporting from the Engineering CPU storage and ending up in the brig reception office in one instance.

**Why is this bad/What are the consequences**: Aside from the death of the player through being teleported into deadly situations and ruining their uncommon antagonist rounds, it also deprives the actual crew of a proper antagonist. It dampens the mood in general.

**Steps to reproduce the problem**: Not particularly complex, as it happened three separate times and those were the only three times I used the ability. I was just walking and I believe against a wall to shorten the distance. Even after dying and being resurrected by qwerty, it continued.

**When did the problem start happening**: It was when I had revealed my form and tried playing as a proper sling for the first time in my ss13 career. It didn't really have a specific circumstance to trigger it AFAIK, just using the ability while facing a direction. Perhaps there were interactions in my path when I attempted to use it, but I can't confirm. 

**Extra information**: [https://i.gyazo.com/9fea0c8af63ac6b4a7ffcd3aafbeca23.png](url) [https://i.gyazo.com/d83815245cebb023d61951332fb77d99.png](url) These aren't terribly good screencaps, but the one focused on the text shows just how much it spammed my chat with the location of the scroll bar from the bottom of the chat. The other is of me dying in space from my first attempt and teleporting outside into space with nothing in sight.

**Comment by Momoberry** [comment]
The admin who handled the ticket was qwertytoforty, they can vouch for the issue happening. The two others who saw me randomly appear in the brig reception were King Arthur as Llinos and Kingminoas as lucas eternity as they were the ones to start killing me. Totally justified, I don't really blame them I would too if some random ass sling suddenly appeared in the reception of my division.

**Comment by S34NW** [comment]
Llinos here, yeah, they just randomly appeared in the brig. Weird bug.
