### ISSUE TITLE
Custom shuttle dockers (mainly SIT computer) use fixed zvlvs / do not work with lavaland

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#15312]
**Issue Description**:

Custom docking computers use fixed zlvls, thinking telecomns z3, thinking mining is z5, etc. Even if lavaland is selected (via the z3) it will not move the camera to lavaland, and probably would not mark the area as clear, or even let you see it.

**What did you expect to happen**: 

For it to not use fixed zlvls, and for if mining was an option, to allow you to go there

**What happened instead**:

Lets you go to the station, and a random zlvl. Lavaland option does not work

**Why is this bad/What are the consequences**:

Shouldnt be using fixed zlvl stuff when we removed most of it from the code, should work with all zlvls it is assigned to.

**Steps to reproduce the problem**:

Use the SIT computer
Select lavaland.
Watch as nothing happens.

**Comment by Kyep** [comment]
SITs are not intended to travel to lavaland.
Unsure why they even have that option in their console.

**Comment by AffectedArc07** [comment]
Fixed since I made these use zlevel names not numbers
