### ISSUE TITLE
Blood Rites loses all charges when flashbanged

### ISSUE THREAD

**Issue by cluwneythescourge** [ParadiseSS13/Paradise#15310]
**Issue Description**:

When having Blood Barrage (the 300 unit spell) prepared to cast in hand, if you get flashbanged, you "drop" the spell. When this happens, all charges are lost as if the spell is used (or at least this happened to me when  I tried it, obviously not many chances to replicate.)

**What did you expect to happen**: 

You shouldnt lose all your charges

**What happened instead**:

you shouldnt lose all your charges

**Why is this bad/What are the consequences**:

you shouldnt lose all your charges

**Steps to reproduce the problem**:

1.  gather 300 units of blood rites
2. prepare the 300 unit spell, blood barrage iirc
3. get flashbanged

**When did the problem start happening**:

not sure

**Extra information**:

**Comment by datlo** [comment]
This is working as designed, any stuns will cause the spell to fizzle, not a bug.
