### ISSUE TITLE
Tool list stays open when you get reset as a borg

### ISSUE THREAD

**Issue by thaulos-bolsens** [ParadiseSS13/Paradise#15341]
**Issue Description**:
Tool list stays open when you get reset as a borg.

**What did you expect to happen**: 
Tool list should disappear.

**What happened instead**:
Tool list gets emptied but in the way cluttering the UI.

**Why is this bad/What are the consequences**:
The button to toggle the visibility of the tool list is the same as the one to pick a module. Making it impossible to close the tool list without picking a module first.

**Steps to reproduce the problem**:
1. Be a borg
2. Pick a module
3. Open tool list
4. Be reset

**When did the problem start happening**:
Unknown

**Extra information**:
Here is a screenshot:
![bug3](https://user-images.githubusercontent.com/49027389/105631285-ab9ed680-5e45-11eb-8e25-f7a84fb3b4e6.png)

**Comment by CkeyLurapa** [comment]
Made a bit of a mess, trying to figure out to have two PRs open at once.

I fixed it over on [Here](https://github.com/ParadiseSS13/Paradise/pull/15534)
![a2SrQE9MFh](https://user-images.githubusercontent.com/78467505/107964769-98b29880-6fe4-11eb-9f15-71a21827dab8.gif)
