### ISSUE TITLE
Syndicate Teleporter Console in Syndicate Forward Base shows BSOD with correct access ID or advanced admin interaction

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#15350]
**Issue Description**:

The Syndicate Teleporter Console in the Syndicate Forward Base shows a NTOS BSOD when the user has A) a correct Syndicate ID allowing access to enabling the Teleport Beacon/Portal or B) Advanced Admin Interaction enabled whilst observing. The Syndicate Teleporter Console in the Suspicious Supply Depot, however, works correctly. This has been observed by an admin on live, then tested on private.

**What did you expect to happen**: 

Not to encounter BSOD. If the  Syndicate Teleporter Console in the Syndicate Forward Base is not to be interfaced with, it should have a screen for this rather than a BSOD.

**What happened instead**:

Correct access ID or advanced admin interaction causes a consistent BSOD on the Syndicate Teleporter Console in the Syndicate Forward Base.

**Why is this bad/What are the consequences**:

We shouldn't have BSOD, even if the player won't generally encounter them; it may be inconvenient for administration.

**Steps to reproduce the problem**:

Either:
1. be a humanoid mob with correct syndicate access ID at the Syndicate Teleporter Console in the Syndicate Forward Base, and access the console,
or:
2. observe the Syndicate Teleporter Console in the Syndicate Forward Base with proper administrative rights and enable advanced admin interaction, then access the console.

**When did the problem start happening**:

Noticed 25/Jan/2021

**Extra information**:

Accessing console with advanced admin interaction (console appears like this with proper access also):
![VG4Rpuw](https://user-images.githubusercontent.com/26665535/105686146-079f5300-5f4b-11eb-9f73-4413562f82df.png)
Accessing console without proper access:
![8oH9Jdx](https://user-images.githubusercontent.com/26665535/105686229-1c7be680-5f4b-11eb-8a3d-fa594882e49a.png)

**Comment by iantine** [comment]
Was advised to ping @Kyep due to potential relation to #15219

**Comment by Kyep** [comment]
@iantine My existing open PR (linked in previous message) already fixes the runtime that causes that error.
