### ISSUE TITLE
Mindslave implants are not working on nukie rounds

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#15361]
**Issue Description**:

Mindslave implants are not working on nukie rounds.

**What did you expect to happen**: 

For after implantation, the person to become a mindslave, have the hud, show on check antags, ect, ect

**What happened instead**:

Instantly gets de-mindslaved, according to ahelps

**Why is this bad/What are the consequences**:

Mindslaves should work, no matter the gamemode.

**Steps to reproduce the problem**:

Have a nukie round
Mindslave them
Watch as nothing happens

**Extra information**:

![image](https://user-images.githubusercontent.com/52090703/105900161-aa0e1380-5fe9-11eb-9c70-2efa401b5fe3.png)

**Comment by SteelSlayer** [comment]
The issue is that nukies don't have their `som` mind variable set up, so it makes a runtime here:
```
Runtime in implant_traitor.dm,70: Cannot read null.serv
```

I've actually already fixed this in my PR: #15084.
