### ISSUE TITLE
SM Monitor keeps flashing skull after SM explodes

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#15387]
**Issue Description**:
The Supermatter Monitoring console keeps flashing the red skull that shows imminent delamination even after the SM explodes and there's no more danger.

**What did you expect to happen**: 
For it to stop flashing

**What happened instead**:
It kept acting as if the Sm was about to explode.

**Why is this bad/What are the consequences**:
Makes people think there's still a delamming SM when there's none anymore.

**Steps to reproduce the problem**:
Delam SM
Look at Monitoring Console.

**When did the problem start happening**:

**Extra information**:

**Comment by Kepplerx** [comment]
Had a discussion with Affected on this, and its not considered an issue. If the SM delammed the flashing EVAC message makes more sense than the calm green Offline sprite.
