### ISSUE TITLE
[Engineering] Powergrid not synced correctly

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1539]
So the background to this is the station got devasted by meteors at round start. The power grid had to be repaired because engineering took the brunt of the damage.

However, after the sing got setup again and trying to reconnect the grid directly to it. The grid doesn't want to take the full power from the sing engine. See the screenshot below:

http://i.imgur.com/nhEkvpd.png

The wire in the door way in the screenshot is powered at the 1.6 KW range but the cable just above the door way. That it's connected to is only transmitting 516000w. If I cut the cable it resynced with the the rest of the existing network.

Something similar can happen with the solar arrays as well. If I direct wire them and let them cycle to full power once in full range of the sun. I can disconnect the wires and then reconnect them and the solar will forever power the grid at 90000watts.

**Comment by TheDZD** [comment]
This might have something to do with the fact that we use ancient powernet code that hasn't been maintained at all.
