### ISSUE TITLE
Patch Pack is Dropped Whenever it's Used on a Person Directly

### ISSUE THREAD

**Issue by AmericanToxic** [ParadiseSS13/Paradise#15407]
**Issue Description**:
 Whenever I attempt to apply patches via "hitting" the patient with the patch pack on help intent, it will apply the medication patch, but the patch pack itself will leave the hand it's in and be on the floor.

**What did you expect to happen**: 
I expected to directly apply a patch to a patient via the patch pack and that would be the end of it

**What happened instead**:
The medication would apply, but the patch pack would leave my hand and be on the floor wherever I was standing when applying the patch.

**Why is this bad/What are the consequences**:
Significant potential of losing medications, especially when trying to treat multiple patients

**Steps to reproduce the problem**:
Use the patch pack directly on a sprite

**When did the problem start happening**:
Unknown, only recently attempted to use a patch pack again. Non-issue a few months ago

**Extra information**:
N/A

**Comment by ToucanBeak** [comment]
I've been looking at the implementation of this and it's super nasty. According to coding chat on Discord, it seems that patches dispensed directly this way don't even have their references cleaned up.
The best be may be to just disable this direct dispense feature, but I'll wait until someone above me give me the go-ahead before I do a PR.
