### ISSUE TITLE
Radiation Stacks weirdly, and leaves the SM with a lot less power than makes sense

### ISSUE THREAD

**Issue by Kepplerx** [ParadiseSS13/Paradise#15402]
**Issue Description**:
The way radiation stacks, and is collected by the Radiation Collectors, makes little sense. It appears that as each item or entity has its own max rads, having more of either makes more rads in total, as such making more power. This seems to be due to how the SM makes things radioactive, while not itself being radioactive. In theory a SM with no things that could be radioactive around it, wouldnt make power at all.

**What did you expect to happen**: 
The SM itself was radioactive, or the Collectors or similar items had a high rad limit, meaning more power production. Adding a monkey with items, or standing by the SM in the chamber, would not make more power at all, perhaps even lower it.

**What happened instead**:
The SM itself makes no rads, and the collectors then just scrape off what few rads there is on the windows or the collectors themselves, a very small amount. Adding a monkey with items, would increase power manyfold, just due to the items.

**Why is this bad/What are the consequences**:
Makes the monkey SM if not necessary, a sensible improvement even as it seems stupid. The SM power generation is very low, meaning a Tesla or Singulo makes a lot more a lot easier, especially for projects. Encourages a lot more risky ways overall to make more power, for example placing monkies in the engine itself, but also experimentation with gases  (Though not bad in itself those). The system as is does not make sense, as one would assume the rads being collected come from the SM itself, the system seems setup that way even. The no buckling by SM is a meaningless fix as such, because one can place a monkey on the outside of the glass for a similar effect.

**Steps to reproduce the problem**:
See how even a CE with items improves power production by a very high amount at little effort. Stand in the chamber to the left or right side, and examine the high disparity between them, as well as the SM itself not being radioactive under a scan.

**When did the problem start happening**:
Ever since the Radioactivity change

**Extra information**:
I would assume changing the max radioactivity on some items may be a way to fix it, perhaps not all pieces of paper can be as radioactive as a monkey, or perhaps plasmaglass can be more radioactive. Another solution would be to make the Collector pick whichever source is the strongest one, and just use power based on that one. Making the SM itself radioactive would also help in this.

**Comment by Fox-McCloud** [comment]
This...isn't how the SM works at all, nor should it work.

Rads stacking in an exponential way is not ideal, in the slightest, and needs to be eventually addressed, but this isn't how rads work nor *should* they work. 

As for power production of the SM--it's also fine; it provides enough power to the station far in excess of what the station drains in terms of power---if you want more power, you're going to have to experiment and try different things---day to day, power generation is fine.

**Comment by Kepplerx** [comment]
@Fox-McCloud My point was rather that as of now, the SM seems to have a lot of capacity to make rads that seem to go nowhere, as such the monkey thing. Adding more stuff there solves that issue, that can be accomplished by other things that monkeys, or make the amount of rads a window can recieve higher. 

The SMs power output is not something that needs to be so high, but such simple steps, increases its output by quite a lot, whcih shouldnt really be the case, one could always refactor Collector power down while making rads spread more

**Comment by matttheficus** [comment]
Not an issue as per Fox's note.
