### ISSUE TITLE
Disabling Antag does not remove chance of spawning slaved to Malf AI

### ISSUE THREAD

**Issue by Cassient** [ParadiseSS13/Paradise#15406]
**Issue Description**:

Disabling Antag on Round-Start doesn't remove possibility of spawning as Borg slaved to a Malf AI

**What did you expect to happen**: 

Disabling Antag to remove possibility of spawning as any form of Antag

**What happened instead**:

Spawned as a Borg slaved to a Malf AI, including Law Zero

**Why is this bad/What are the consequences**:

Players who wish to play without having to be an antagonist may roll as a Malf Borg and have to play as an antag, or enter Cryo at round-start, removing any respawn possibilities

**Steps to reproduce the problem**:

Ready up for a round with Cyborg enabled and Antag disabled on a round where the AI is Malf

**When did the problem start happening**:

Unknown, possibly as long as the Antag disabling feature

**Extra information**:

**Comment by Fox-McCloud** [comment]
This is part of the nature of being a borg---much like the AI, you're subservient to the entire station--it's baked into what you sign up for when you pick the job--this is something that really shouldn't be protected for, nor will it be.
