### ISSUE TITLE
Medical Borgs do not have a geiger counter

### ISSUE THREAD

**Issue by thaulos-bolsens** [ParadiseSS13/Paradise#15413]
**Issue Description**:
With the introduction of the new engine, radiation has become a more common issue that medical needs to solve/cure. This often involves measuring the radiation level and whether or not the patient has radioactive contaminants.

The tool used to diagnose those two metrics is the geiger counter.

**What did you expect to happen**: 
Medical borgs should have the ability to check for radioactivity levels and radioactive contaminants.

**What happened instead**:
Medical borgs have no access to a geiger counter.

**Why is this bad/What are the consequences**:
Medical borgs should be able to treat or at the very least triage patients with radioactive related issues.

**Steps to reproduce the problem**:
Be a medical borg.

**When did the problem start happening**:
Started being a problem when the new engine was introduced.

**Extra information**:
N/A

**Comment by hal9000PR** [comment]
If I'm not mistaken, don't body scanners also show radiation?

**Comment by Fox-McCloud** [comment]
This is a feature request, and not appropriate for the git.
