### ISSUE TITLE
Borgs being permamently deleted within seconds by blob.

### ISSUE THREAD

**Issue by procdrone** [ParadiseSS13/Paradise#15423]
**Issue Description**:

a Cyborg can be permanently deleted (with brain included) as fast as one, two seconds.

**What did you expect to happen**: 

for it to take a little longer (some sort of cooldown or knockback) or at least not delete brains

**What happened instead**:

borg, brain, and hope deleted sooner than i could sneeze

**Why is this bad/What are the consequences**:

player permanently removed from round

**Steps to reproduce the problem**:

1. Be blob
2. Click spam on borg player
3. Hes dead within seconds, brain gets deleted after blob tile is spawned on it
4. Hes gone

**When did the problem start happening**:

Ever since the dawn of man.

**Extra information**:

**Comment by AffectedArc07** [comment]
Relaying this.
![image](https://user-images.githubusercontent.com/25063394/106666693-d7396380-659f-11eb-9ce4-1c3172973d50.png)

Being hyperbolic in issue titles will not only make this harder to reproduce, but also comes off as really naggy.

**Comment by Fox-McCloud** [comment]
Balance changes and feature requests are not typically for the git.

Closing.
