### ISSUE TITLE
IPC's have internal organs

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#1543]
This causes them to gasps and coughing  up blood.
Among other things

**Comment by Spacemanspark** [comment]
Yep, it's pretty funny to kill an IPC, revive them, and kill them again just to see the endless amount of organs you can create.
(Oh dear God please don't do this you monsters.)

**Comment by TheDZD** [comment]
Yeah, the changes to organs made IPCs buggier than they already were prior.

**Comment by tigercat2000** [comment]
@TheDZD I wouldn't call this a bug per-say; They are perfectly intended to have internal organs which are robotic. They probably shouldn't, but they have specific code just for that.

**Comment by Keilden** [comment]
So why not just make custom organs like Dionas?

**Comment by Zuhayr** [comment]
Actual IPC organs are on Baydev if you want to snaffle them. It allows you to reboot an IPC by taking out their brain, blowing in the socket, and putting it back in.

**Comment by Robertha89** [comment]
Like a NES game. Real old school.
