### ISSUE TITLE
Vulps loose darksight upon being defibed

### ISSUE THREAD

**Issue by Herder05** [ParadiseSS13/Paradise#15448]
**Issue Description**:

When med defibs you you loose the darksight ability that vulps have
other things that can happen are when you get defined with mesons you get meson view with Fullbright 

**What did you expect to happen**: 

to keep my darksight

**What happened instead**:

lost my darksight

**Why is this bad/What are the consequences**:

vulps loose one of the few things special about them

**Steps to reproduce the problem**:

be vulp then die get defibed
for the meson version just do it while wearing meson
**When did the problem start happening**:

always been like this just never bothered to make a bug report of it

**Comment by hal9000PR** [comment]
https://github.com/ParadiseSS13/Paradise/pull/15192 fixes this

**Comment by Herder05** [comment]
ah its already been reported *snap
