### ISSUE TITLE
More full tile window bugzz

### ISSUE THREAD

**Issue by TheYeetster1** [ParadiseSS13/Paradise#15466]
**Issue Description**:

If you replace a wall with a window the fire alarms, intercoms, atmos air alarms, APCs and other interactables become unusable, 

**What did you expect to happen**: 

for me to still be able to use wall equipment even if replaced with glass

**What happened instead**:

I am unable to interact and just knock on the glass

**Why is this bad/What are the consequences**:

You cant access APCs and other things without deconstructing the window.

**Steps to reproduce the problem**:

RCD deconstruct a wall, or normal deconstruction, replace with full tile glass window, try to use a wall intercom or APC, etc.

**When did the problem start happening**:

Since PR #15385 got implemented 

**Extra information**:

**Comment by TheYeetster1** [comment]
Also some of the intercoms in the brig are also unusable.

**Comment by Fox-McCloud** [comment]
This isn't really a bug---this is just how full-tile windows function. You'll have to move said items, in question.

>Also some of the intercoms in the brig are also unusable.

they weren't before; I specifically checked for this; they're a lot easier to notice though, because fulltiles really draw attention to what's inside them, aesthetically.
