### ISSUE TITLE
Engineering airlock missing external button

### ISSUE THREAD

**Issue by DinBlade** [ParadiseSS13/Paradise#15479]
**Issue Description**:
New SM mapping changed the left airlock under the engineering's hardsuits to go to space and not into the old engine chamber, but there is not button to cycle to exterior on the space side of the airlock.

**What did you expect to happen**: 
To be able to get back in after doing the Sats goal, but was closed due to someone hitting the button on the inside/going back inside. Had to go around the engine to atmos maint.

**What happened instead**:
No way in. Had to go around the engine to atmos maint. Could not access the Engineer airlock.

**Why is this bad/What are the consequences**:
Minor issue, but when vamp/clings/slings are about going thru the engi maint solar airlock is not a good idea. Or going around the engine to atmo maint is just odd/annoying.

**Steps to reproduce the problem**:
Two people go out the airlock, one goes back in, second person has to ask or go around.

**When did the problem start happening**:
SM mapping reworked Engineering proper.

**Extra information**:

**Comment by matttheficus** [comment]
Fixed.
