### ISSUE TITLE
Engineering Control Room engine monitor set to old Singulo engine cameras

### ISSUE THREAD

**Issue by DinBlade** [ParadiseSS13/Paradise#15480]
**Issue Description**:
Engineering Control Room has a 'engine monitor' in the top right called the 'Singularity Engine Telescreen', it should see the engine like the one under the CE's office called the 'Engine Monitor' but it is blank, no cameras are on it/connected to it

**What did you expect to happen**: 
To see the five engine cameras.

**What happened instead**:
It had an empty list.

**Why is this bad/What are the consequences**:
Minor issue, but having to go down into the high rad area to check issues in person vs getting a glance before running in might be nice.

**Steps to reproduce the problem**:
Click on the Singularity Engine Telescreen in the Engineering Control Room.

**When did the problem start happening**:
After the SM remap

**Extra information**:

**Comment by Sirryan2002** [comment]
My fault, I looked at the wrong monitor when determining whether this was still an issue. Feel free to reopen this.
