### ISSUE TITLE
Pentetic acid does not lower radiation when used in a cryomix

### ISSUE THREAD

**Issue by TORE01** [ParadiseSS13/Paradise#15484]
**Problem Description**:
What is the problem?
When chemicals are used in a cryomix their effects get enhanced by 10 times (last time I checked). Due to the new nature of radiation, using pentetic acid in a cryomix to cure radiation would be a huge help when the SM delaminates. But it doesn't seem to work.

**What did you expect to happen**: 
Why do you think this is an issue?
Pentetic acid lowers radiation way better than Potassium ionide and is procuded both for this usage and for purging harmful chemicals or poison from a patients body. When put in a cryomix along with cryoxadone, I expected the cryoxadone to heal brute and burn damage while the pentetic acid would lower radiation at a higher rate than when injected. This is false, as it doesn't seem to heal radiation at all.

**What happened instead**:
How is what happened different from what you expected?
Instead of healing radiation damage while used in a cryotube, the pentetic acid instead just does what it does besides healing radiation. It heals toxin damage while purging other chemicals in the body at a higher rate.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
While it's not the end of the world, it just feels inaccurate (my disappointment is immeasurable, and my day is ruined).

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Go to the SM crystal, get irradiated (do NOT get dusted). Then afterwards, have a doctor waste his pentetic acid by putting it into a cryomix. And voila, you are still irradiated and probably going bald at this point.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
It just never worked I guess, which is understandable since the radiation rework is very recent.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Have a nice day

**Comment by Fox-McCloud** [comment]
You can't shove tons of chemicals into a cryo mix at once--it's only going to process so many, to prevent abuse of chem multiplying for situations just like this; you're going to have to experiment and find the right ratio or cut out the number of ingredients to have it actually work, but it will work; alternatively, they were still irradiated and were accumulating rads because of that---the radiation purging isn't just going to stop because it's in a cryo mix.
