### ISSUE TITLE
You Can Weld Body Bags Shut

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#15495]
**Issue Description**:
You can use a welder to seal body bags shut

**What did you expect to happen**: 
To not be able to weld body bags like a locker

**What happened instead**:
The body bag was welded shut and unable to be opened

**Why is this bad/What are the consequences**:
Doesn't really make sense, also seems unintended

**Steps to reproduce the problem**:
1. Get welder
2. Get body bag
3. Weld body bag
4. Find that the bag is welded shut

**When did the problem start happening**:
N/A

**Extra information**:

**Comment by AffectedArc07** [comment]
Kinda makes sense because it has a zipper, and you can weld zippers.

**Comment by S34NW** [comment]
If you got a zipper hot enough to weld it, surely the bodybag would melt?
