### ISSUE TITLE
Cannot Tape Paper To Full Tile Windows

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#15490]
**Issue Description**:
You cannot tape paper to full tile windows like you could with directionals

**What did you expect to happen**: 
To tape the paper to the window

**What happened instead**:
I just hit the window with my paper

**Why is this bad/What are the consequences**:
Prevents leaving notes on windows

**Steps to reproduce the problem**:
1. Tape paper
2. Try to put paper on window
3. Realize you can't and be sad

**When did the problem start happening**:
Unsure, only an issue now that we've transitioned to full tile windows

**Extra information**:

**Comment by SabreML** [comment]
I don't seem to be able to tape paper to windows, even on a branch from before the window merge. Are you sure it was possible then?

![7ApzwUgrq2](https://user-images.githubusercontent.com/57483089/107559522-1be28180-6bd4-11eb-9357-34f48d86b666.gif)

**Comment by Kiyahitayika** [comment]
@SabreML It was not. This can also be tested in-game by making directional windows.

**Comment by Leanfrog** [comment]
Guess I just remembered wrong then, closing
