### ISSUE TITLE
You try to shake a dead person who has (near) no damage awake

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#15504]
**Issue Description**:
You shake a dead non wounded person instead of it saying that they are dead like with all other wounded dead persons.
![image](https://user-images.githubusercontent.com/15887760/107702596-c46b1100-6cba-11eb-8e47-b566424b733a.png)

**What did you expect to happen**: 
It to tell me they are dead. So it will try to do CPR on the person and fail since they are dead

**What happened instead**:
My char tried to help them up on their feet again.

**Why is this bad/What are the consequences**:
Mostly inconsistency with the current working.

**Steps to reproduce the problem**:
1. advanced proc call "death" on a mob. No arguments
2. Click on them on help mode

**When did the problem start happening**:
Prob since new crit

**Extra information**:
Easy first issue

**Comment by SabreML** [comment]
Fixed by the above PR.
