### ISSUE TITLE
Bridge request console bluescreen.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#15523]
![image](https://user-images.githubusercontent.com/52090703/107862338-3efe7280-6e1a-11eb-8d82-8149c296fda0.png)

**Comment by moxian** [comment]
BSOD in one of these two `.map()`s, i can't be sure which one exactly
https://github.com/ParadiseSS13/Paradise/blob/c445b4d396985bd70d3291fd10a2b6153415c76f/tgui/packages/tgui/interfaces/RequestConsole.js#L235-L241
