### ISSUE TITLE
Changeling reviving with suicide command

### ISSUE THREAD

**Issue by Sneedstar** [ParadiseSS13/Paradise#15560]
**Issue Description**:

Possible unintended issue, undetermined until a coder reviews.

**What did you expect to happen**: 

This stops you from being cloned even though you are currently living. Reviving from the suicide state which is supposed to be a DNR state and completely fools those around you if you are a changeling.

**What happened instead**:

Suicide was said to be a DNR state but that isn't true for changelings. Changelings are able to revive from the suicide command as stated.

**Why is this bad/What are the consequences**:

The changeling can no longer use the cloner machine even if they are alive.
This could be a bug abuse/unintended or maybe even power gaming. Coder review is required.

**Steps to reproduce the problem**:

I suicide, revive using changeling powers and so on. I made a video showcasing the steps reproduced. https://www.youtube.com/watch?v=M7ipgXd81mY&feature=youtu.be&ab_channel=Sneed

**When did the problem start happening**:

**Extra information**:

I've used this only twice and both times have been a clean get away as changeling whether this is intended or not I am unsure.  I am unsure if it's bug abuse because changelings are suppose to revive and yet the suicide state is not suppose allow for revival and yet here we are at a state where they both counteract each other in someway. You surely get your free get away as changeling from security but cannot use the cloner. It is a lose and win situation.

**Comment by hal9000PR** [comment]
Clings are supposed to be able to revive out of suicide.

**Comment by Spacemanspark** [comment]
Personally I'd be cool with gutting the suicide function out of the game entirely.

**Comment by Sneedstar** [comment]
> Personally I'd be cool with gutting the suicide function out of the game entirely.

I see no issue with this, I see the suicide function only used as antags being caught or a really stupid security officer ending their life. I'd like to request a normal DNR function in place that would block SR revivals because the only possible good functionality of suicide is the DNR. Not everyone may want to be revived back into a potential burning heap a mess of a station by some revival serum.

**Comment by Sneedstar** [comment]
POG
Issue resolved. Day is made, game is NOT ruined!
