### ISSUE TITLE
Slime-person organ icon updates failing

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#1556]
Issue; When a slime person's limbs are removed, their icon does not update. Appears to be a similar issue to the "beheading doesn't actually update the icon" issue back at the start of the new organ system.

![screenshot](http://puu.sh/j9T1b/a147fd680f.jpg)

Issue appears to be reproducible on any slime-person external organ at all times. 

Bug appears to only affect slime people.
![scxeeen](http://puu.sh/j9TeZ/6b73f4a465.jpg)

**Comment by Dumbdumn5** [comment]
Would it possibly be due to the icon being an overlay? Or is that a part specific overlay.
