### ISSUE TITLE
Picking up and dropping items quickly makes them slide

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#15576]
**Issue Description**:
When you pick items up and drop them very quickly, they don't disappear from the old turf and reappear on the turf you are stood on, they slide between said turfs.

**What did you expect to happen**: 
The item should disappear from the old turf, appear in your hand, then at your feet.

**What happened instead**:
Item slid between turfs.

**Steps to reproduce the problem**:
Pick up and drop items really fast. Not consistently achievable, you may need to try a fair few times to see it happen.

**Comment by Gatchapod** [comment]
I always assumed that's a feature.
Isn't it?

**Comment by SabreML** [comment]
I'm 99% sure that this is just a side effect of the movement animation system, so...
**Working as intended:tm:**

**Comment by SteelSlayer** [comment]
Yeah I don't know if this can be fixed.
