### ISSUE TITLE
SSU Storage Slot Borg Interaction Oddity

### ISSUE THREAD

**Issue by Vulkoras** [ParadiseSS13/Paradise#15596]
**Issue Description**:
While attempting to destroy an open SSU (explorer suit variant in the mining outpost) as an engineering borg with an integrated welder a copy of it was placed inside the ssu's storage slot which I was then able to eject (https://cdn.discordapp.com/attachments/811073644771016705/813779568124887040/ssustorageoddness.png). The copied welder mimicked the state of the original and disappeared when the original was stowed (original was able to be used throughout the rest of the shift without issue).

**What did you expect to happen**: 
The ssu to take damage from the welder or to receive a variant of the "X is attached to you and you cannot place it in Y" message.

**What happened instead**:
An odd pseudo duplicate of the welder was placed within the SSU.

**Why is this bad/What are the consequences**:
Assumedly unintentional behaviour/possible item duplication.

**Steps to reproduce the problem**:
As a borg use a welder (or possibly any other item) on an open ssu with an empty storage slot.

**When did the problem start happening**:
I'd assume it's an unintended side effect of https://github.com/ParadiseSS13/Paradise/pull/15540 which allowed any small items to be placed in an ssu's storage slot but I'm not certain (I'm very much a fan of improvements from the pr and hope the issue can be addressed without any loss of functionality). 

**Extra information**:
N/A (I am however extremely tired while typing this (but figured I shouldn't delay reporting it) so I apologise for any mistakes, general poor grammar, poor choice of title or anything I've missed (as a semi related aside, a few months ago as a humanoid I picked up a borg variant wrench out of a linen basket which disappeared briefly after. At the time I wasn't sure what had happened but looking back I guess it might have been another variant of this issue)).

**Comment by TDSSS** [comment]
I wonder now if SSU's respect no-drop, or if the same issue would occur when trying to put something in an SSU with nodrop active.
