### ISSUE TITLE
Malf AI lags the server for 10 minutes

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#1560]
If certain malf AI abilities are used / spammed the server locks up for 10+ minutes while it tries to handle everything
Things include: 
Hostile Lockdown
Blackout

When hostile lockdown is used you can actually see the wave of "lag" that spreads, doors slowly closing, bolting and getting electrified

**Comment by Fox-McCloud** [comment]
I can't help but suspect the reason for the door lag is because of a lack of a spawn() in particular part of doors....which is handled/fixed in Krausus' PR. Not 100% sure if that's the case though.
