### ISSUE TITLE
area creation log location is wrong.

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#15609]
**Issue Description**:
The creation of new rooms/areas is logged. However, the coordinates attached to the message admins get about that is always 0,0,0, which is wrong.

**What did you expect to happen**: 
Actual coordinates

**What happened instead**:
You get a message like
ADMIN LOG: A new room was made by [Some CKEY]/(IC NAME(?) (FLW)(?) (FLW) at Shitty DNA Vault (0,0,0) (JMP) with the name Shitty DNA Vault

(also the ? and FLW links are both duplicated)

**Why is this bad/What are the consequences**:
coordinates should be correct

**Steps to reproduce the problem**:
make new area, be admin, look at message

**When did the problem start happening**:
once the logging feature was put in, in #15525

**Extra information**:

**Comment by SabreML** [comment]
Fixed by the above PR
