### ISSUE TITLE
Spears cannot damage goliaths or watchers

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#15607]
**Issue Description**:
As it is right now, ash walkers cannot fight goliaths or watchers with the spears they start with as the spears do no damage to the lavaland wildlife of goliaths and watchers.

**What did you expect to happen**: 
For the spear to actually damage the thing ash walkers are supposed to hunt

**What happened instead**:
Spear bounces harmlessly off of the goliath or watcher.

**Why is this bad/What are the consequences**:
Prevents ash walkers from having progression as they have nothing they can hunt for bones, sinew, or leather.

**Steps to reproduce the problem**:
Spawn as ash walker, grab spear. Try to attack a goliath or watcher.

**When did the problem start happening**:
Unknown, issue was first noticed since june of 2020 when I initially reported it

**Extra information**:

![spears](https://user-images.githubusercontent.com/24213815/109105078-d43f1800-76f2-11eb-8dfa-d964c62d35b8.PNG)
![spears 2](https://user-images.githubusercontent.com/24213815/109105080-d4d7ae80-76f2-11eb-9513-4ab2748f7eb7.PNG)
![spears3](https://user-images.githubusercontent.com/24213815/109105085-d608db80-76f2-11eb-93c6-a6f280b97038.PNG)

**Comment by hal9000PR** [comment]
I'm pretty sure this is intended. Iirc the ash walker wiki mentions this as being a feature. You are intended to melee your prey to death rather than kill them from a range.

**Comment by datlo** [comment]
I think the issue reported is that melee damage does not work either. Goliaths have always been immune to thrown spears.

**Comment by Denthamos** [comment]
As datlo has said is what is meant.  I was simply showcasing all three attacks being done against a golaith and watcher.  One hand, wielded, and thrown.  None of the three work against either of them.  Apparently this also applies to legions but I did not test that one.

Kind of an issue when the weapons you spawn with to hunt the wildlife, cannot even hurt the wildlife to kill them.

**Comment by Denthamos** [comment]
Further testing - Today the spears are working properly against the lavaland wildlife, so I am not sure what happened yesterday during that round in specific to cause the spear picked up off the table in the ash walker nest to not be doing any damage.

**Comment by Denthamos** [comment]
Issue has not been seen or reported in a while.  Closing this due to inconsistency of the issue since then.

**Comment by Vi3trice** [comment]
Throw force needs to be higher than 20 in order to damage lavaland mobs specifically. Standard glass spears are 20, plasma-tipped ones are 21.
