### ISSUE TITLE
Changeling monke can't use vents

### ISSUE THREAD

**Issue by Aracino** [ParadiseSS13/Paradise#15601]
**Issue Description**: Changelings in lesser forms can't use ventcrawl

Attempted to vent crawl as monkey, took all items off, wasn't able to crawl through vents.

**What did you expect to happen**: 

Be a vent monke

**What happened instead**:

Be a sad monke who couldn't vent crawl.

**Why is this bad/What are the consequences**:

Can't do vent crawls into high profile areas like captains room to steal laser gun.

**Steps to reproduce the problem**:

Be changeling (optional?)
Be lesser form/monke
Try to crawl in vents
Fail

**When did the problem start happening**:
As I'm rarely using lesser form/playing as a monkey, assumedly after Fox's gene refractor.

**Extra information**:

**Comment by warior4356** [comment]
I tested this, talking to them in discord. I am unable to replicate this issue.

**Comment by Fox-McCloud** [comment]
Ventcrawling wasn't touched nor turned into a trait in that PR, so it's a bit unlikely that traitifying was the source of this issue.

Are you absolutely *sure* you didn't have something equipped.

**Comment by meow20** [comment]
I had 2 different people mhelp about this (before gene refactor) and I couldn't replicate it myself either back then.

**Comment by Fox-McCloud** [comment]
sounds like something is getting put in the mob's `contents` when it *shouldn't* be.

**Comment by Aracino** [comment]
Yeah I was told it could be related to the gene thing, but I'm not sure after Meow's comment. I made sure I had nothing on me, not even implants or anything. It's possible it could be client side but I tried a few methods, reconnecting, close out byond, transforming into a farwa, all didn't work.

**Comment by Aracino** [comment]
It's possible this issue is caused by having a changeling sting active, as that would supersede alt clicking on vents like it does with pointing and middle mouse button.

**Comment by DeveloperLoser** [comment]
Yea, happened to me and a persons who brain a stuck in a monkey, they couldn't vent crawl even with all items stripped. Something funky is definitely going on with player monkeys.

**Comment by SteelSlayer** [comment]
Yeah most likely you had a sting prepared which overrides alt-click. Can't reproduce this with just the given steps, lesser form works fine.

**Comment by SteelSlayer** [comment]
Issue was likely due to an overridden middle/alt click as stated above. Though if this issue appears again, feel free to reopen the report.
