### ISSUE TITLE
Security Borg Baton

### ISSUE THREAD

**Issue by scoutskywalker** [ParadiseSS13/Paradise#15617]
**Issue Description**:

The security borg baton can have it's power source uninstalled. This renders the baton useless. 

**What did you expect to happen**: 

The security borg should be attacked with a screwdriver instead.

**What happened instead**:

I suspect that with the baton out, using a screwdriver on the borg takes out the baton's battery. 

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

1. Be security borg
2. Have baton out
3. Use screwdriver (suspected, not confirmed.)
4. Lose ability to use baton

**When did the problem start happening**:

2/25/2021

**Extra information**:

**Comment by Spacemanspark** [comment]
Uhh, I don't think this can happen--have you actually confirmed this in game? A borg pulls power for the baton from its own power supply.

**Comment by Tourte-Yaya** [comment]
Spawned cyborgs with pre-loaded module like destroyer don't have a cell in their stunbaton either.

**Comment by scoutskywalker** [comment]
> Uhh, I don't think this can happen--have you actually confirmed this in game? A borg pulls power for the baton from its own power supply.

Yes, had this happen yesterday. Baton sprite had the battery out and everything, as well as inputting the message "not enough reserve power" at 15 kW stored power.

**Comment by SteelSlayer** [comment]
Can't reproduce locally with given steps.

**Comment by White-Diavol** [comment]
I had this happen to me but I am not sure on the steps that led up to it.
Does it make sense that secborgs have infinite power batons that only use their normal borg power reserves?

**Comment by matttheficus** [comment]
Sec Borgs are gonezo, stale, and unrepro.
