### ISSUE TITLE
Robotics built AI's have weird buggy issues with revs.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1563]
Started out as headrev, get cut down.
Regardless, I see a posibrain popup come, and I click the sign up button.
Upon being posi'd, I see that the roboticist is a rev, via the RevHUD.
Roboticist makes me an AI and I see I'm still a damn headrev, and I can see other revs.
However, the round ends shortly after, due to all rev heads dying.
Not EXTREMELY serious, since I was obviously bound to laws, but... something worth checking.

**Comment by veganzombeh** [comment]
Did you enable antagHUD, or could you still see revs from when you were alive?

**Comment by Spacemanspark** [comment]
I did not enable antag HUD.

**Comment by TheDZD** [comment]
Probably something to do with the fact that you don't get your antag status reset upon being borged, which may or may not be intentional. That said, you should definitely have your antag status reset upon taking control of a posibrain.

**Comment by Crazylemon64** [comment]
My posibrain mind fix has fixed this.
