### ISSUE TITLE
Binded to looking forward, everytime I turn it makes me look up again. Moving very slowly.

### ISSUE THREAD

**Issue by MustacheMan45** [ParadiseSS13/Paradise#15634]
**I can't stay/keep looking to the left, bottom, or right of my screen. My character always defaults to facing the top, and I can't figure out why. It's slowing me down, and the current job I'm playing is extremely important.**:

**I'm not sure why the problem exists. One moment I go AFK in the evidence room facing the right way, and the next when I come back, I'm stuck facing forwards and walking like a crab.**: 

**Well, I expected I'd just come back to not much else, and that I could get on with the cremation of a dead EoC. But all of a sudden this bug, of which I believe is disrupting my work.**:

**This is bad because I am much slower than usual, and this can afflict my operation when I am needed to arrest a criminal, or kill one for that fact.**:

**Be either the HoS, or a security officer, and walk into the evidence room. Stand on the tile right below the two northwest lockers. Then, wait 2-3 minutes, come back and this is how my problem happened.**:

**Just today. I don't really think this is an old feature, but it possibly good be.**:

**I would really appreciate it if anyone could figure out what's causing the problem, or if this has happened to them before.**:

**Comment by SabreML** [comment]
I'm not sure what could cause this to happen while you're AFK, but the 'Locked facing in one direction and crabwalking' thing isn't a bug.
There's a feature to lock your character into facing a certain direction by shift+middleclicking somewhere, and you can unlock yourself by shift+middleclicking again.

**Comment by MustacheMan45** [comment]
Thank you for the feedback! Sadly the round has already ended, but thank you so much! I'll use this information for when I later encounter this again.

**Comment by MustacheMan45** [comment]
Thank you for the feedback! Sadly the round has already ended, but thank you so much! I'll use this information for when I later encounter this again.

**Comment by MustacheMan45** [comment]
Thank you for the feedback! Sadly the round has already ended, but thank you so much! I'll use this information for when I later encounter this again.

**Comment by LightFire53** [comment]
@MustacheMan45 if you run into what seems to be a bug, you can ahelp in game to get some more immediate assistance. If we can't help you there, then a bug report may be needed. We don't see bug reports on GitHub in game, and it may be something that is a quick fix!
