### ISSUE TITLE
You cannot augment hands, feet and lower bodies

### ISSUE THREAD

**Issue by hal9000PR** [ParadiseSS13/Paradise#15641]
**Issue Description**:

you cannot start the surgery to augment hands, feet and lower bodies

**What did you expect to happen**: 

to be able to augment those limbs

**What happened instead**:

no augmentation surgery could be selected 

**Why is this bad/What are the consequences**:

you cannot augment people.

**Steps to reproduce the problem**:

1) lay human on surgery table
2) aim for lower body/hands/feet
3) try and select augmentation surgery

**When did the problem start happening**:

maybe since #14813 ? but I am unsure.

**Extra information**:

**Comment by Adrer** [comment]
Note: Tested this, appears to only to happen with slimepeople.
