### ISSUE TITLE
Putting a Wizard hat on a Corgi grants them the title 'Grand Wizard'

### ISSUE THREAD

**Issue by Sky-Ping** [ParadiseSS13/Paradise#15648]
**Issue Description**:

Putting a Wizard hat on a Corgi grants them the title 'Grand Wizard'

**What did you expect to happen**: 
When I put a cute wizard hat on the dog, I didn't expect him to become a white supremist.

**What happened instead**:
Ian became the leader of the KKK.

**Why is this bad/What are the consequences**:
In all honesty, this is the type of thing that will fly over a lot of peoples head, but I'd assume we don't want this stuff hard coded into the game.

**Steps to reproduce the problem**:
1. Place a wizard hat (collectable included) on a corgi.

**When did the problem start happening**:
It's possible that this has flown under the radar for a decade and we just never knew.

**Extra information**:

**Comment by Dumbdumn5** [comment]
I can't really respect the reasoning in this issue report, as per my comment in #15653 

Though I could barely see it in name recognition alone, that should _reasonably_ be wiped out by the inclusion of a neon orange dog in a wizard hat.

**Comment by MrFagetti** [comment]
Grand Wizard =/= KKK

Honestly, I think you're looking too deep into it or being hyper-vigilant over anything that mildly could be seen as relating to the weird bedsheet ghosts.

**Comment by Kraingore** [comment]
You're looking far too deep into it. Maybe you just want something to mad at?
