### ISSUE TITLE
Barbers do not have an icon on the SECHUD

### ISSUE THREAD

**Issue by Markolie** [ParadiseSS13/Paradise#1565]
Barbers lack an icon (on the top left) on the SECHUD, as we have no custom icon for them. A spriter will have to create one, most likely, after which it can be easily added.

**Comment by KasparoVy** [comment]
Just do, like, some diagonal scissors or a buzzer/shaver, whomever sees this ;P. Easy fix

**Comment by Markolie** [comment]
@Nienhaus: If you're available and willing, we could really use a HUD icon for barbers.
