### ISSUE TITLE
bots pathfinding seems to be broken

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#15667]
**Issue Description**:

There seems to be some issue with bots such as medibots, cleanbots and such being unable to navigate around walls/doors anymore, they seem to just try to go in a straight line to their next checkpoint. This is also an issue with Mulebots.

Not sure if it is related but bots will also sometimes teleport several tiles when moving (like if you put beepsky in a locker as he stops in a checkpoint for a few seconds and drag him, he'll then open the locker and immediately snap back in place).

**What did you expect to happen**: 

Bots pathfind, going around walls and through doors.

**What happened instead**:

Bots stuck in corners, mulebots stuck running into the cargo desk instead of through the doors, etc.

**Why is this bad/What are the consequences**:

Makes bots bad/useless.

**Steps to reproduce the problem**:

build cleanbots or similar in robotics and tell them to patrol
watch them get stuck in a corner

or

send mulebot to other department
watch it run into the cargo desk and get stuck

**When did the problem start happening**:

I noticed it some weeks ago? Maybe earlier, but I had been taking a hiatus until recently, so it's hard to tell. It can't be too old though.

**Extra information**:

**Comment by S34NW** [comment]
armsky has been broken like this for a week or two now, he just sits in the top left corner where he spawns (unless he sees something to beat up)

**Comment by White-Diavol** [comment]
Noticed that clean-bots consistently get stuck if for example there is blood under the sleeper, table or  similar.

**Comment by White-Diavol** [comment]
Looks like the auto-patrol method and the calc_path it calls for the smaller bots is broken here - it calculates a target regardless of obstacles and simply pushes the bot toward without any attempts for a different path or acknowledging they are trapped.

In the image both are stuck and partly non-functionaly and are both attempting to reach targets that are off-screen on the other end of the table (from their POV).
![image](https://user-images.githubusercontent.com/53142276/110205830-91134080-7e7a-11eb-89ff-1347a138a850.png)

**Comment by White-Diavol** [comment]
Also I managed to reproduce them getting stuck on corners.

**Comment by datlo** [comment]
This also affects the syndicate bot on the depot. Get stuck on the closed blast doors when hes supposed to patrol around the depot.
![image](https://user-images.githubusercontent.com/22121511/119669636-7e385880-be38-11eb-8dee-58d4db54f93c.png)
