### ISSUE TITLE
Double text both in chat and in runechat for Holoparasites

### ISSUE THREAD

**Issue by Kepplerx** [ParadiseSS13/Paradise#15685]
**Issue Description**:

As a Holopara, the owner displayed double texting for everything they said, both in chat and in the runechat.

**What did you expect to happen**: 

That there was no double text.

**What happened instead**:

The text doubled, but only for the owner of the parasite, not for others.

**Why is this bad/What are the consequences**:

Annoying, and likely does not help if the messages are sent double as the strain will be higher, and the runechat becomes a lot more annoying.

**Steps to reproduce the problem**:

Be a (if it matters, standard holopara traitor kind) and have the owner talk, there should then appear double text as in the pictures.

**When did the problem start happening**:

Unsure, but likely not an issue just with runechat, but also the normal chat

**Extra information**:

![Bug](https://user-images.githubusercontent.com/65926304/110238905-668dba00-7f44-11eb-814f-5f2aef24bc1b.PNG)
The picture above shows the double runechat texting
![image](https://user-images.githubusercontent.com/65926304/110238909-6e4d5e80-7f44-11eb-9d3e-13b35ad026e1.png)
The picture above shows normal chat texting, but was taken with a long time between the first one, and as such show it was not a isolated incident. The (x2) minimize the issue here, but show that its still there.

**Comment by SteelSlayer** [comment]
Can't reproduce this. Any other information you can give? Did this happen from the moment you became a holoparasite?

**Comment by Kepplerx** [comment]
> Can't reproduce this. Any other information you can give? Did this happen from the moment you became a holoparasite?

Yeah, from the moment I became one, as to other factors I added all I am aware of

**Comment by matttheficus** [comment]
Cannot reproduce + Stale
