### ISSUE TITLE
Having internals on in the 'Status' tab causes a framerate drop

### ISSUE THREAD

**Issue by SabreML** [ParadiseSS13/Paradise#15684]
**Issue Description**:
Having the 'Status' tab open with internals turned on reduces the game's frame rate by a considerable amount.
Apparently GPS coordinates showing can also cause this, but I haven't tested that myself.

**What did you expect to happen**: 
The game performance would stay stable, maybe with a *slight* decrease due to all of the values on the Status tab.

**What happened instead**:
Noticable framerate drop from 60 to maybe around 30. I haven't tried getting exact numbers yet.

*Video Demonstration with Internals, GPS, and Spacepod stats on a test server: (Not sure if the GPS and Spacepod actually make a difference here)*

https://user-images.githubusercontent.com/57483089/110226669-2f3def80-7ee9-11eb-9530-f5b6a277be1c.mp4

*Far more obvious example recorded on the live server:*

https://user-images.githubusercontent.com/57483089/120053296-4f310b00-c021-11eb-8560-ff87ed2b3136.mp4

**Why is this bad/What are the consequences**:
It forces me to have a different tab open if I actually want to have any chance in combat, or even just walking around if it gets bad enough, which means I can't see things like the escape shuttle timer or internals pressure.

**Steps to reproduce the problem**:
Activate internals and switch between 'Status' and any other tab. There should be an obvious difference.
The longer the round goes on for, the worse it gets.

**When did the problem start happening**:
I only noticed this problem when I started playing Vox since they have constant internals, so anywhere from about two weeks ago.

**Extra information**:
It *looks* like it's just a hardware/CPU problem on my end, but the majority of people I've spoken to about this have also experienced it.

**Comment by AffectedArc07** [comment]
Not something we control, nor a big enough problem for us to worry about, since I haven't heard of many people suffering from this at all.

**Comment by S34NW** [comment]
doesnt the status tab cause slowdown anyway over time?

**Comment by Spacemanspark** [comment]
I also suffer from this. Thank Jesus for the examine tab, because it's actually crippling. 

There's also a bit of a slowdown with the borg status tab too, but it's not nearly as bad.

**Comment by SabreML** [comment]
> Not something we control, nor a big enough problem for us to worry about, since I haven't heard of many people suffering from this at all.

So far I've heard from 4 people who aren't affected by it, and 6 who are. Assuming that holds up in the overall population then I would say it's definitely worth fixing if possible. Having over a third of the playerbase practically unable to use one of the most important information tabs is definitely an issue.

**Comment by Rurik123** [comment]
So this is what I was experiencing. Yea, got hella lag at, what I thought, was randomly. Pretty grievous too, especially for sec/antag.

**Comment by Sikroth** [comment]
just to keep better track of the number of affected people, it is also something I've noticed a lot recently

**Comment by DeveloperLoser** [comment]
Suffer from this to, didnt notice it was internals however, so good catch. I drop to a solid 10FPS, btw.

**Comment by ArdentSpark** [comment]
I also suffer from this, and had no idea until it was pointed out and double checked for myself

**Comment by SabreML** [comment]
### Update:
Finally managed to get a FPS monitor working, apparently fraps works in SS13.
Behold, the Vox/Plasmaman internals experience!

https://user-images.githubusercontent.com/57483089/120053179-b39f9a80-c020-11eb-9b21-5e574734bef9.mp4

(Recorded on live just before the shuttle arrived, Round ID 27410.)
