### ISSUE TITLE
Floral Somatoray does not mutate plants

### ISSUE THREAD

**Issue by KommodoreKomrk** [ParadiseSS13/Paradise#15719]
**Issue Description**:
The Floral Somatoray does not mutate plants (when set to mutate) in soil or in trays. It does still change the yield (even when set to mutate), however.

**What did you expect to happen**: 
For the plant to show any signs of mutation

**What happened instead**:
The plant grew sick and unhealthy, even with full Gaia applied

**Why is this bad/What are the consequences**:
Effectively makes the Floral ray useless

**Steps to reproduce the problem**:
Stand 1+ tiles away from plant
Set Floral ray to mutation
Fire it for 39 minutes until something happens
Nothing happens

**When did the problem start happening**:
Current build, at least, unknown when this started

**Extra information**:

**Comment by S34NW** [comment]
The floral somatoray might need to be modified to change its description to avoid this confusion, but the "mutate" option actually mutates the plant's stats, not the plant type itself. So this is intended behaviour.

**Comment by dearmochi** [comment]
The "mutate" projectile calls `mutate` on the tray's seed when hit:
https://github.com/ParadiseSS13/Paradise/blob/dfad6545e9a6ad1be15a4534124f11548cb18814/code/modules/hydroponics/hydroponics.dm#L410-L413

So it's indeed intended behaviour

**Comment by Fox-McCloud** [comment]
It mutates *stats*, not species. 

Not a bug.
