### ISSUE TITLE
Can't interact with PDAs while lying down

### ISSUE THREAD

**Issue by SabreML** [ParadiseSS13/Paradise#15724]
**Issue Description**:
You're not able to interact with your PDA while lying down.

**What did you expect to happen**: 
> tweak: can utilize your PDA when lying down

#15233

**What happened instead**:
You can open the UI, but everything is disabled.

**Why is this bad/What are the consequences**:
Kinda defeats the point of #15233, especially since it was approved and merged.

**Steps to reproduce the problem**:
1. Open PDA.
2. Lie down.
3. Eye icon goes orange.

**Extra information**:
The problem is line 64 here:
https://github.com/ParadiseSS13/Paradise/blob/8943c60057c1990ac4970fd92469769c0f3324e7/code/modules/tgui/states.dm#L59-L66
The PR edited the `can_use()` proc, but the TGUI side of it is untouched.

**Comment by Sirryan2002** [comment]
Will be fixed in #17899
