### ISSUE TITLE
Super PACMAN and regular PACMAN not working properly

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#15723]
**Issue Description**:
On power setting 2 for Super PAcmans and regular Pacmans constantly raise heat higher and higher till they explode / their temp scale to power setting is too high.

**What did you expect to happen**: 
For them to remain stable in the green at power setting 1/2, not reach into the orange until setting 3 and explode in 4/5.

**What happened instead**:
The pacmans exploded on power setting 2.

**Why is this bad/What are the consequences**:
Prevents engineering from properly using them in a situation where the SM explodes and they need to generate backup power for the station.

**Steps to reproduce the problem**:
Build a pacman or super pac.  Monitor the temperatures at stage 1/2.  One goes into the orange slightly at halfway and two explodes it.

**When did the problem start happening**:
Unknown, been a while since I have used them or even seen them properly used.

**Extra information**:

Mrs pacmans appear to be working properly at settings 1-5 with 1-2 being stable, 3 being orange, and 4-5 getting dangerous.

Attached is a picture showing the stable working temps of each at stage 1.
![pacs](https://user-images.githubusercontent.com/24213815/111303975-281e8c00-8623-11eb-870c-bce0deebb6f2.PNG)

**Comment by dearmochi** [comment]
At ambient temperature, PACMAN (except MRS) temperatures are clamped between `56 + power_output * 50` and `76 + power_output * 50` -- at level two, this means the temperature should never leave the range of 156 K to 176 K. The safe temperature for these generators is up to 300 K.

**After testing with both generators on level two then four, I found that the 300 K limit is never reached and that the generators never exploded.**

![image](https://user-images.githubusercontent.com/1496804/111315836-0c3ada80-8663-11eb-8b27-7abb3e7c1ba5.png)

That being said, the generator's temperature output is affected by the turf's air temperature -- a PACMAN in a cold room will cool more easily, but in a hot room, it will get warmer more easily as well, potentially overheating.
A generator can also only explode if it's EMP'd, emagged (25% chance) or stays at >300 K for too long.

**Comment by matt81093** [comment]
Do you know what temperature the turf the PACMAN you tested were on?

**Comment by Denthamos** [comment]
Attached is a picture showing how it was setup in electrical maint.  The room temperature was the usual ambient temp for the room as it was never touched the entire shift.
Green - Superpac/ Purple - Regular Pac
The right side was set on setting 2 and left side were at setting 1.  The right side superpac exploded on setting 2.

![elec](https://user-images.githubusercontent.com/24213815/111387096-326c7480-867b-11eb-8015-fed7be049da4.PNG)

**Comment by matttheficus** [comment]
Stale and seems to be working within parameters.
