### ISSUE TITLE
Nukies choke to death because they dropped their tank and didn't turn off internals.

### ISSUE THREAD

**Issue by PidgeyThePirate** [ParadiseSS13/Paradise#15733]
**Issue Description**:
I'm not sure if it's an issue entirely confined to suspicious emergency oxygen tanks, but when you breach into the station and throw away the tank, you seem to remain connected to the internals indefinitely even as the tank sits on the floor.

**What did you expect to happen**: 
Taking off the tank and tossing it aside should really mean you aren't breathing from it anymore.

**What happened instead**:
I choked to death and lost a nukie round for no apparent reason. I confirmed the bug in a later round.

**Why is this bad/What are the consequences**:
People choking to death for no apparent reason is pretty bad. I ded pls nerf

**Steps to reproduce the problem**:
1. Wear mask.
2. Wear suspicious emergency oxygen tank.
3. Activate internals.
4. Throw aside the tank.
5. Pick it back up.
6. Internals are still on.

-alternatively-

5. Choke to death about 15 minutes later.

**Comment by wikimody** [comment]
Alternatively leave a tank in air carnister loiding and hawe infinite oxygen using no slots for air tanks

**Comment by PidgeyThePirate** [comment]
After some more testing, I could not replicate this. I don't know what caused me to choke to death, but I have to close this for now.
