### ISSUE TITLE
Slime Soup showing up as invisible

### ISSUE THREAD

**Issue by Sky-Ping** [ParadiseSS13/Paradise#15741]
**Issue Description**:
The item Slime Soup has no sprite attributed to it and shows up as invisible.  The item is still edible and can be picked up with right click.

**What did you expect to happen**: 
Visible Slime Soup

**What happened instead**:
Oh no where did my slime soup go

**Why is this bad/What are the consequences**:
Attracts ants, can take up a hand slot preventing other items from being picked up.

**Steps to reproduce the problem**:
Item is /obj/item/reagent_containers/food/snacks/slimesoup

**When did the problem start happening**:
N/A

**Extra information**:

**Comment by SabreML** [comment]
There actually doesn't seem to be a sprite for this at all in the `.dmi` file, and there doesn't seem to have *ever* been one unless it was stealthily removed by accident somewhere.

**Comment by LightFire53** [comment]
> There actually doesn't seem to be a sprite for this at all in the `.dmi` file, and there doesn't seem to have _ever_ been one unless it was stealthily removed by accident somewhere.

I actually found an old sprite on the wiki of all places... and yeah, it's dated.

![image](https://user-images.githubusercontent.com/16112919/111890886-0880be00-89ab-11eb-9733-bea265d64153.png)

That said, I'm currently just spriting the old one in to fix the immediate problem, and can PR a new one in later.
