### ISSUE TITLE
Full tile plasma windows will not hold gases.

### ISSUE THREAD

**Issue by TheYeetster1** [ParadiseSS13/Paradise#15768]
**Issue Description**:

When making a gas chamber, full tile windows will not hold N20, Plasma or other gasses.

**What did you expect to happen**: 

For secured reinforced  plasma, full tile windows to prevent gas escaping

**What happened instead**:

![bugatmos1](https://user-images.githubusercontent.com/70362590/112922908-4d0f0680-90db-11eb-9bdc-c46da7222e05.png)

**Why is this bad/What are the consequences**:

The description says that they are fireproof, while true one would expect that a secured window would also contain the fire and other dangerous gasses.

**Steps to reproduce the problem**:

- Build a gas chamber
I have tested many variations and It does not matter if you have:
A)no floor tile underneath the glass
B)regular floor tile underneath the glass
C)reinforced floor tile underneath the glass
D)If it is in atmospherics or not.
E) If there is grill underneath or not.
F) If you release plasma or N20

Video of what i did: https://youtu.be/G18UP3OApwo

**When did the problem start happening**:

Unknown, I am fairly certain that I have come across this problem when dealing with regular non-plasma full tile windows, when trying to fix breaches. But I have no idea why full tile windows leading to space don't just leak air.

**Extra information**:

I'm unsure if this is intended behavior or not, please let me know if this is intended.

**Comment by hal9000PR** [comment]
https://www.paradisestation.org/forum/topic/18876-atmos-how-airtight-are-your-windows/?tab=comments#comment-145300

take a look at this

**Comment by TheYeetster1** [comment]
@hal9000PR Thank you, this is useful to me.

**Comment by TheYeetster1** [comment]
This seems to be a long standing issue, so old infact it is the 3rd oldest, open bug report from 2015.

Issue: #2913

**Comment by 1080pCat** [comment]
Unable to repo, given the time past, change of atmos systems and [this post](https://www.paradisestation.org/forum/topic/18876-atmos-how-airtight-are-your-windows/?do=findComment&comment=160257) im going to safely assume this has been been fixed.
