### ISSUE TITLE
species without eyes cannot use cling augmented eyesight

### ISSUE THREAD

**Issue by hal9000PR** [ParadiseSS13/Paradise#15765]
**Issue Description**:

species without eyes cannot use cling augmented eyesight

**What did you expect to happen**: 
to be able to use the ability

**What happened instead**:
couldn't use the ability

**Why is this bad/What are the consequences**:
slime people cannot use the ability and they must transform in order to use this ability 

**Steps to reproduce the problem**:
1, be slime person
2, be a cling
3, buy augmented eyes
4, press the button

**When did the problem start happening**:
when eye implants became cyber eyes

**Extra information**:
![image](https://user-images.githubusercontent.com/69320440/112882741-407fb380-90c5-11eb-8f34-f101c0da65c2.png)
this check always fails. I dunno how to fix it without adding an eye organ to slimes when they use the ability.

**Comment by DogsParadise** [comment]
This makes sense tho?

**Comment by AffectedArc07** [comment]
Closing for a test

**Comment by hal9000PR** [comment]
sorta makes sense now that I think about it
