### ISSUE TITLE
I don't really have a title for this...

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1581]
I know the code for character previews is shit, but this is still amusing. Not a big issue, and probably a Byond bug itself, but may as well stick it here.
I played some CM last night, and then when I came to Paradise this morning and opened up my character setup, I got this.
![Whatisthis](http://i.imgur.com/7OxIZbf.png)

**Comment by tigercat2000** [comment]
That's hilarious. 

Going to guess the rsc got fucked up and byond assumed "eh the image is kinda the same name or something"

**Comment by Iamgoofball** [comment]
Ahahahahahah

**Comment by Spacemanspark** [comment]
@apophis775

**Comment by Robertha89** [comment]
I want those clothes.

**Comment by SamCroswell** [comment]
@tigercat2000 
Likely because it was cached under the same character name, if I had to guess.

**Comment by veganzombeh** [comment]
I'll stick this here, because I suspect it's also an rsc bug and doesn't warrant it's own issue, but this happened. http://i.imgur.com/4tmYi3y.png (In the status panel)

**Comment by Spacemanspark** [comment]
![](http://i.imgur.com/OUjERi4.png) I don't know if this needs an explanation.

**Comment by tigercat2000** [comment]
that's terrifying

**Comment by M3hillus** [comment]
On my phone....is that a metroid latched on your head?

**Comment by Spacemanspark** [comment]
Yes.
We used to have Metroids in SS13.

**Comment by Robertha89** [comment]
we still have, slimes are re-sprited and renamed metroids

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

The metroid on the head is not a bug---just something extremely rare: https://github.com/ParadiseSS13/Paradise/blob/103372e92b0c1cef97b8e3fee3079832e17993f3/code/modules/mob/new_player/preferences_setup.dm#L494

**Comment by Spacemanspark** [comment]
That's intentional on the character setup screen only? What even.

**Comment by Robertha89** [comment]
actually it's intentional to character setup screen only

**Comment by Spacemanspark** [comment]
That's what I said.

**Comment by Robertha89** [comment]
some of the sprites, i have no clue where they come from, but basically, there is a small easter egg, say you want to be a cyborg or ai, then your character will be nude, but they can also wear the cardboard box suit and hat, or be muzzled, blinding and straightjacketed. It's random

**Comment by Spacemanspark** [comment]
How dare ye close my grand issue report.
