### ISSUE TITLE
Radiation is extremely slow.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#15819]
**Issue Description**:
Do note. I'm not exactly sure if this is a bug or not, it _seems_ to me that it is, but it might not be. Bare in mind this is NOT taking into mind contaminated objects, I did not test this, just straight radiation.

Essentially, damage from radiation is basically nonexistent until you reach 500 rads. Even at that point it's so extremely minor that it's a mere inconvenience, by this I mean like. 1-2 toxins here and there and nothing more. It took me roughly 18 minutes for hair to fall out, 816 rads, and toxins to reach 56 damage, bare in mind at this point it was more the toxins from the liver damage that was damaging me more than the radiation. It took 23 minutes, 1.1k toxins, and around 30 liver damage to finally enter crit. 26 minutes to kill, and that death was mostly because RNG deemed it so.

**What did you expect to happen**: 
I expected radiation to be a tad more lethal, rather than something you can not care about. This test was done standing next to uranium golem, naturally radiation will scale higher with more radiation producers. The golem also did not irradiate any objects at all, other than the test mob.

**What happened instead**:
It took roughly 1/4th of the round to actually die from radiation exposure, and most of the death wasn't radiation related.

**Why is this bad/What are the consequences**:
If this is a bug, it makes essentially any form of radiation barring massive doses I.E the SM trivial.

**Steps to reproduce the problem**:
1. Get radiated.
2. Wait

**When did the problem start happening**:
Presumably since the radiation refactor.

**Extra information**:
If this ISN'T a bug, then that's my bad. Do note this isn't intended, in any capacity, to be a feature request. From my point of view, this seems like a bug.

**Comment by ppi13** [comment]
Uranium Golems pulse for 20 radiation, nor does it contaminate which is a huge deal, you don't contamine before you get hit by 350 rads, and contaminated items rad other things at 25% of the power of the original thing, anything from 0-500 is safe, hairloss starts at 800, mutation 1250, vomit and knockdown at 2000, from the code this seems to be correct.
Looking over it, it seems to be balanced around the SM that is the primary source of radiation, so it's not a bug, at best it might be an oversight in buffing the rads of uranium golems.

**Comment by S34NW** [comment]
uranium in general was forgotten about since the rad refactor and SM
