### ISSUE TITLE
"Kill" grab intent movement speed bug

### ISSUE THREAD

**Issue by MrTeco** [ParadiseSS13/Paradise#15860]
**Problem Description**:
When grabbing 2 characters with different hands, on kill intent, you walk twice as fast, skipping a tile every time you step.

**What did you expect to happen**: 
What I expected, is walking while grabbing 2 characters on kill intent being as fast as walking while grabbing a single character on kill intent.

**What happened instead**:
Instead, when I grabbed 2 characters on kill intent, I started moving 2 tiles every step, like teleporting ahead 2 tiles.

**Why is this bad/What are the consequences:**
Because, someone could abduct someone, or even 2 people at once, and run away faster because of this bug.

**Steps to reproduce the problem**:
Press 3, click human, upgrade to kill. switch hands, click other human, upgrade to kill. You walk faster now.

**When did the problem start happening**:

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Defenitely works on monkeys atleast

**Comment by matttheficus** [comment]
Should be fixed by #17895
