### ISSUE TITLE
Grammar Mistake in description of Coroner's Cap 

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#15895]
**Issue Description**:

/obj/item/clothing/head/surgery/black
"A cap coroners wear during autopsies. Keeps their hair from falling into the cadavers.  **It is as dark than** the coroner's humor."

Should be corrected to "It is as dark as" or just be rewritten.

This is a minor issue but it should probably be lumped in with a larger bugfix PR at some point or would be good for someone wanting to learn how to make PRs.

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/115067350-b0c16e00-9ee8-11eb-82d9-a1a75960051d.png)
