### ISSUE TITLE
Slime person changeling HUD buttons

### ISSUE THREAD

**Issue by DeveloperLoser** [ParadiseSS13/Paradise#15913]
**Issue Description**:
Doing transformation stuff as a slimeperson changeling (inside a locker I believe) will duplicate the slime person hud buttons.

**What did you expect to happen**: 
Not have 4 different hud buttons for SP.

**What happened instead**:
Had 4 hud buttons for SP

**Why is this bad/What are the consequences**:
Gets annoying after a bit

**Steps to reproduce the problem**:
Be a slime person changeling, transform into someone else (vulp in my case) go into a closed locker. Change back to slime person.

**When did the problem start happening**:
Not sure.

**Extra information**:
Didnt try to reproduce in same round, but buttons stuck around and weren't present when i normally transformed before.

**Comment by hal9000PR** [comment]
This happens when you transform out of a slime person. Sometimes it doesn't properly remove the action buttons.

**Comment by Sirryan2002** [comment]
Code issue identified, slimes/unathi skip `action.remove` for some reason upon the second calling of `on_species_lost` proc in their dm file

**Comment by Sirryan2002** [comment]
found a solution, PR should be out sooner or later
