### ISSUE TITLE
Noise Analyzer Only Hears Screams

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#15918]
**Issue Description**:
The Noise analyzer is supposed to pickup most types of noises, however it can only hear when something screams.

**What did you expect to happen**: 
For the analyzer to be able to hear:
- Me smashing a toolbox against a girder
- Me saying something
- An Airlock Bolting/Unbolting/Opening/Closing

**What happened instead**:
Noise Analyzer only activated upon me screaming.

**Why is this bad/What are the consequences**:
while it's fun that the only current purpose of this item is to detect the suffering of others, its loses it's intended functionality and usefullness by only being able to detect audible pain instead of other important noises.

**Comment by FlattestGuitar** [comment]
This is a feature request, not an issue.

**Comment by Sirryan2002** [comment]
eh, I guess you're right. It's kindof limbo between bug and request since it seems like someone didnt actually implement proper functionality to this when it was added.
