### ISSUE TITLE
Slime person changeling transformation shock/cardiac arrest

### ISSUE THREAD

**Issue by DeveloperLoser** [ParadiseSS13/Paradise#15912]
**Issue Description**:

As a changeling, Transforming from slime person, to vulp, and back to slime person, puts you into shock, and then cardiac arrest.

**What did you expect to happen**: 
Not go into shock and cardiac arrest,

**What happened instead**:
...

**Why is this bad/What are the consequences**:
Death if not noticed. Also puts a nice indicator on med huds that can easily be meta'ed, as you are otherwise entirely fine.

**Steps to reproduce the problem**:
Be a slime person cahngeling, transform into a vulp, transform back to slime person.

**When did the problem start happening**:
Not sure.

**Extra information**:

**Comment by Sirryan2002** [comment]
I cannot reproduce this. Is this something that has happened more than once? Additionally, were you already injured before you transformed?

**Comment by DeveloperLoser** [comment]
Yea it happened twice, also no I was not injured before. Had multiple doctors as well as the BP come up to me several times. Also Ahelped just to confirm. The player I was transforming into was Dahk Grel so maybe they have something like a cybernetic heart that could cause it.

**Comment by matttheficus** [comment]
Likely an issue regarding updating of the MedHUD

**Comment by Contrabang** [comment]
Not able to duplicate, and a more exact issue for the medhud thing has been opened
