### ISSUE TITLE
Twrp

### ISSUE THREAD

**Issue by golfviva** [ParadiseSS13/Paradise#15950]
**Issue Description**:

**What did you expect to happen**: 

**What happened instead**:

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

**When did the problem start happening**:

*github: main

**Comment by Sirryan2002** [comment]
Please fill out this issue report or close it :)

**Comment by AffectedArc07** [comment]
Closing. Fill it out properly or not at all.
