### ISSUE TITLE
Rogue pixel on doppler array

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#15967]
**Issue Description**:
![EghWSDwczt](https://user-images.githubusercontent.com/25063394/116780828-d74de000-aa76-11eb-8d81-0e457a74fee4.gif)

**What did you expect to happen**: 
That pixel in the bottom right to not be there

**What happened instead**:
See image

**Why is this bad/What are the consequences**:
Looks bad

**Steps to reproduce the problem**:
Open eyes

**When did the problem start happening**:
Since the sprite change

**Extra information**:
I have been coffee free for over 7 days

**Comment by hal9000PR** [comment]
we are all proud of you AA

**Comment by DogsParadise** [comment]
I'll fix this

give me like 30 minutes

**Comment by ManiacalSymphony** [comment]
That's the bottom left, but sure

**Comment by AffectedArc07** [comment]
> That's the bottom left, but sure

What are directions anyway
