### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by NancokPS2** [ParadiseSS13/Paradise#15972]
**Issue Description**:

Whenever i try to connect, BYOND goes Connecting for around 10 seconds before returning "Connection Failed"

**What did you expect to happen**: 

To play the game

**What happened instead**:

I get an error

**Why is this bad/What are the consequences**:

Can't play

**Steps to reproduce the problem**:

Press Join, wait until error pops up

**When did the problem start happening**:

N/A, never worked

**Extra information**:

I tried clearing cache of both IE and BYOND to no avail, other servers do work, Paradise is the only one giving me issues

**Comment by AffectedArc07** [comment]
Not a code issue. Please try running `ping byond.paradisestation.org` in your command prompt to see if you can reach the server.
