### ISSUE TITLE
`jquery.mark.min.js` doesnt exist, and is a goonchat asset

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#15994]
**Issue Description**:
`BUG: File error 2 (No such file or directory): /home/aa07/Paradise/goon/browserassets/js/jquery.mark.min.js (current directory is /home/aa07/Paradise)`

**What did you expect to happen**: 
The asset to load and my console to not be spammed

**What happened instead**:
![image](https://user-images.githubusercontent.com/25063394/117337728-a2d28d80-ae95-11eb-962a-645d45792fcc.png)

**Why is this bad/What are the consequences**:
Clients should be getting assets, but they arent

**Steps to reproduce the problem**:
Launch the server. Note that this error occurs on both windows and linux, but only reports on windows.

**When did the problem start happening**:
Unsure

**Extra information**:
N/A

**Comment by Sirryan2002** [comment]
Did this start happening b/c of the server transfer or is has this been a continuous issue with goonchat?

**Comment by AffectedArc07** [comment]
> Did this start happening b/c of the server transfer or is has this been a continuous issue with goonchat?

Continuous issue, just never reported since windows doesn't flag these up.
