### ISSUE TITLE
Cursed Heart

### ISSUE THREAD

**Issue by Zulaara** [ParadiseSS13/Paradise#15993]
**Issue Description**:

Cursed Heart unexpectedly killed me instantly from full health, even though I had been pumping it. Upon attempted defib revivals, I died instantly again. Only after filling me with a lot of blood were they able to revive me for a few seconds before the cursed heart killed me again. 

**What did you expect to happen**: 
I did not expect to randomly die

I believe the cursed heart may increase the amount of blood it consumes over time when not pumped, but I do not know if this is true or intended. 

**What happened instead**:
I was at full health (as far as I could tell) and dropped fully dead instantly

this is pretty clear. Alive = expected. Dead = unexpected

**Why is this bad/What are the consequences**:
I thought the cursed heart gave amazing regeneration in exchange for constant attention, but this means it effectively puts a timer on how long you will live at a maximum.

Miners and lavaland players should be able to benefit from the cursed heart for a long time as they mine and do other things, rather than just a die in a silent blaze of glory. 

**Steps to reproduce the problem**:

I was a diona beachbum from lavaland with a champions hardsuit and the cursed heart and the eye of god. I don't believe those should affect anything though. We were fighting a blob late in the round and i was pumping and shooting a kinetic accelerator. Suddenly, I dropped dead. 

**When did the problem start happening**:

**Extra information**:

**Comment by BakKeener** [comment]
I believe the timer is around 7 seconds, before it STARTS killing you I think, but if you are pumping it on a regular basis and you die before the timer for you to die occurs then something is clearly wrong. Also if I recall cursed heart isn't supposed to be a instant death?

**Comment by matttheficus** [comment]
Stale and no method of reproduction.
