### ISSUE TITLE
Solar Consoles and Processing

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1599]
Simply put, when the round starts solar trackers/computers are not properly being added to the sun controller. I've tried a number of things to get them to be added to the solars processing list, but it just isn't happening--players have to manually unscrew and re-screw the console screen to get them to be properly added to the sun controller.

**Comment by Taaketa** [comment]
Out of curiosity what should unscrewing and rescrewing do?

**Comment by Markolie** [comment]
It calls the New() proc again, and this time the sun has initialized properly so the consoles can now be added to the list.
