### ISSUE TITLE
Buggy arcade floors

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#15995]
**Issue Description**:

After a welderbombing, people attempted to replace the floor tiles of the arcade. However, the floor tiles looked like plating, and shift clicking on it lagged / crashed the game.

**What did you expect to happen**: 

Not issues

**What happened instead**:

The icon_state for the arcade floor is "arcade". The icon path is icons/goonstation/turf/floor.dmi
However, on the tiles where the welderbombing happened, after the floor tiles were removed and replaced, the icon_state was "arcade", but the icon path is **icons/turf/floors.dmi** 
Since that path does not have the arcade dmi, it bugs out and makes tiles you can not examine without issues.

**Why is this bad/What are the consequences**:

Bugs like this are bad

**Steps to reproduce the problem**:

Welderbomb arcade.
Crowbar and replace tiles.
Examine buggy tiles

**Comment by Sirryan2002** [comment]
Can confirm that this happened on a separate round
