### ISSUE TITLE
Debug number in chat when scanning/cloning players

### ISSUE THREAD

**Issue by stejul** [ParadiseSS13/Paradise#1601]
As soon as I died, [**this**](http://gyazo.com/99217633a4a9c6978085d6751addb1ec) popped in chat. Nothing has really affected my characte maybe, because I was dead, but not sure about that.

**Comment by FalseIncarnate** [comment]
I believe that is a debugging message that was accidentally left in somewhere. It has been spotted before, but we haven't tracked down where it comes from yet.

I have personally seen that before while alive, so I believe everyone sees it, or at least is not directly related to death.

**Comment by TheDZD** [comment]
Somebody likely left a `world << ` line somewhere.
