### ISSUE TITLE
Infinite Kisses Bug

### ISSUE THREAD

**Issue by Ginji23** [ParadiseSS13/Paradise#16019]
Doing the kiss emote puts a kiss in your hand. By clicking on the sprite with your free hand, it is switched to your other hand, but makes it into an invisible kiss "item." You can hit people harmlessly with this kiss "item," drop it like a normal item to remove it, or click the air in front of your player to infinitely shoot kisses. This can easily spam the chat log.

**Comment by SabreML** [comment]
Can confim, easily reproducable issue.

https://user-images.githubusercontent.com/57483089/118121585-9b593a00-b3e9-11eb-8453-544cab3da39b.mp4

Not sure what's acutally causing it, but I assume it's just not `DROPDEL`ing properly. May also be a problem on other items with the flag.
https://github.com/ParadiseSS13/Paradise/blob/9422c7828a44be1a02194394a03130ede903b9df/code/game/objects/items/hand_item.dm#L54
