### ISSUE TITLE
Holy SHIT CLONING BROKEDEDED

### ISSUE THREAD

**Issue by Jaywings** [ParadiseSS13/Paradise#16018]
**Issue Description**:

Cloning is not ejecting both incomplete and failed clones on ID ejection or power disruption.

**What did you expect to happen**: 

The clone to pop out as incomplete and severely damaged, or gibs. 

**What happened instead**:

The cloner proceeds to get stuck in a permament stuck state until dissembled if the clone is destroyed. Uncertain of what happens to an incomplete, but safe clone.

**Why is this bad/What are the consequences**:

Cloning should be working properly as an important part of medical bay. Having the cloner get permanently stuck until dissembled is very painful to med-bay, as dissembling it removes all biomass from the specific cloner.

**Steps to reproduce the problem**:

1. Kill someone.
2. Throw them in DNA modifier
3. Scan and proceed to clone
4. Proceed to either EMP or EMAG the cloning pod
5. Cry because you are unable to remove the clone by either ID ejection or power malfunction.
6. Cry harder because you have to disassemble the pod in order to clear it, resulting in loss biomass.

**When did the problem start happening**:
 I suspect it happened after tool refactors, but my knowledge is fragmented due to multiple breaks. The cases of this happening are rare due to lack of EMP or EMAG use on cloners, but I'd rather not see medbay get stuck with it again.

**Extra information**:

Nothing other then thanks to Fethas for testing it ingame with me, and player Virikats in informing me of this.

**Comment by farie82** [comment]
Most likely caused by this runtime I found in the logs of today
```
Runtime in cloning.dm,473: Cannot execute null.Cut().
  proc name: go out (/obj/machinery/clonepod/proc/go_out)
  usr: NAME (CKEY) (/mob/living/carbon/human)
  usr.loc: The floor (158,115,2) (/turf/simulated/floor/plasteel)
  src: the cloning pod #1 (/obj/machinery/clonepod/biomass)
  src.loc: the floor (158,114,2) (/turf/simulated/floor/plasteel)
  call stack:
  the cloning pod #1 (/obj/machinery/clonepod/biomass): go out()
  the cloning pod #1 (/obj/machinery/clonepod/biomass): attackby(NAME\'s ID Card (... (/obj/item/card/id/medical), NAME (/mob/living/carbon/human), "icon-x=14;icon-y=25;left=1;scr...")
  NAME\'s ID Card (... (/obj/item/card/id/medical): melee attack chain(NAME (/mob/living/carbon/human), the cloning pod #1 (/obj/machinery/clonepod/biomass), "icon-x=14;icon-y=25;left=1;scr...")
  NAME (/mob/living/carbon/human): ClickOn(the cloning pod #1 (/obj/machinery/clonepod/biomass), "icon-x=14;icon-y=25;left=1;scr...")
  the cloning pod #1 (/obj/machinery/clonepod/biomass): Click(the floor (158,114,2) (/turf/simulated/floor/plasteel), "mapwindow.map", "icon-x=14;icon-y=25;left=1;scr...")
```
