### ISSUE TITLE
Admin-spawned Inquisitor ERT couldn't use null rod.

### ISSUE THREAD

**Issue by PopeDaveThe3th** [ParadiseSS13/Paradise#16017]
**Issue Description**:

I, as an admin spawned Inquisitor ERT, couldn't use my null rod, with it smacking me in the face instead.

**What did you expect to happen**: 

For me to be able to hold my null rod.

**What happened instead**:

The null rod slipped from my holy fingers and bonked me on the head.

**Why is this bad/What are the consequences**:

An inquisitor with no null rod is severely hampered in actually dealing with unholy threats.

**Steps to reproduce the problem**:

1. Get spawned in as an Inquisitor ERT by an admin.
2.  Attempt to equip your null rod.

**When did the problem start happening**:

Round 26939

**Extra information**:

An admin informed me that an admin-spawned Inquisitor has an IsHoly var of 0, rather than 1.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/13339

**Comment by matttheficus** [comment]
As per #13339 the issue would cause weird mind problems. The solution is you have to manually VV the mind to make it holy. If youre going to spawn something in manually, youll need to fix said issues manually too.
