### ISSUE TITLE
Malfunctioning AI can roll vampire on traior vampire rounds (presumably cling traitor has same issue)

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#16067]
**Issue Description**:

Malfunctioning AIS can also sorta roll vampire, reducing the vampires in the round by one.

Presumably also happens on traitor changling.

**What did you expect to happen**: 

For the code that excludes vampires from being AI to work.

**What happened instead**:

Last round, the AI got this message on a traitor vampire round. The AI was malfunctioning after, which is most likely part of the events leading to this.
![image](https://user-images.githubusercontent.com/52090703/119279707-750e7800-bbfb-11eb-8471-d52d32a84be1.png)
This is the message displayed to vampires when they are turned into a borg / AI.
When checked afterwords, only 2 vampires spawned in the round, despite the gamemode requiring 3 to be generated. This means this malfunctioning AI rolled vampire, and it was overridden by them becoming a malf AI.

**Why is this bad/What are the consequences**:

Vampires / changings being reduced due to bugs like this is bad.

**Steps to reproduce the problem**:

I suspect this is caused by the fact that traitors are generated after vampires and changelings, and they have a different list of restricted roles.
For example, when someone gets vampire, their restricted roles are added to the mind, which is a combination of the usual restricted roles, and AI

vampire.restricted_roles = (restricted_jobs + secondary_restricted_jobs)

However, after vampires are rolled, traitors are rolled.
If a person was to roll traitor, this happens:

traitor.restricted_roles = restricted_jobs

This will override the restricted_roles, if they already have any. Normally they don't, but _vampires_ do. Since the restricted roles is overridden, AI is now an option this vampire traitor could theoretically roll.

**When did the problem start happening**:

https://github.com/ParadiseSS13/Paradise/pull/15452

**Extra information**:

The way for this to be fixed is to not remove any restricted roles the person already has.

**Comment by Contrabang** [comment]
Haven't seen this in forever, fixed by https://github.com/ParadiseSS13/Paradise/pull/20106
