### ISSUE TITLE
Boxstation AI upload turret controls cant be swiped

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#16090]
**Issue Description**:

Turret control on bridge for the AI upload cant be swiped by the captain to unlock the controls and turn the turrets off.

Turret controls on AI sat are fine. I havent tested delta/meta station.

**What did you expect to happen**: 

Swipe controls, unlock them

**What happened instead**:

Swipe controls, nothing happens. AI/borgs can still control the panel, crew can open the panel but it's locked.

**Why is this bad/What are the consequences**:

Feature isnt working.

**Steps to reproduce the problem**:

Spawn as captain, swipe ID on AI upload turret controls.

**When did the problem start happening**:

Recently. Was reported today (26/05/2021) on discord and reproduced on updated local server.

**Comment by farie82** [comment]
Not related to #16091. The access requirements are loaded in incorrectly. They are loaded in as strings instead of numbers. This means that the IDs access(which use numbers for access) don't match
