### ISSUE TITLE
[TG Mining] Drones

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1610]
Purchasing a drone with points. (not with the starter card) gives no upgraded welding tool. Is that intended?

**Comment by TheDZD** [comment]
I'm not certain how much of it is intentional, and how much of it is because the equipment vendor is only capable of dispensing one item per purchase (mining vouchers use a different system).

**Comment by Taaketa** [comment]
Could it be possible to add an upgraded welding to the vendor for say 200 points?

**Comment by Taaketa** [comment]
Since this related. Could a machine frame and board be created for the Ore Redemption machine? A large went off yesterday on the server screwing over the miners for the rest of shift. As the machine was destroyed. Maybe add a board to tech stoarge?

**Comment by TheDZD** [comment]
One [already](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/constructable_frame.dm#L662) [exists](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/research/designs/machine_designs.dm#L335), you just have to bug RnD or robotics for a board, which they should fairly happily give you considering they need processed ores to build their toys.

**Comment by Taaketa** [comment]
Ooo. Guess the scientist didn't know about it then.

Thanks.

I'll add to wishlist for a spare board in tech storage though. :)

**Comment by Markolie** [comment]
Closing older feature requests - post it on the forums please.
