### ISSUE TITLE
Another Rod of Asclepius issue

### ISSUE THREAD

**Issue by KozackWolf** [ParadiseSS13/Paradise#16139]
**Issue Description**:

As is known, when you use the rod of asclepius you can no longer cause harm in any manner. However, it interacts oddly with CQC if you use that first. Apparently you can still use CQC moves while holding the active rod.

**What did you expect to happen**: 

The rod is supposed to turn you completely harmless, with this, you are not harmless.

**What happened instead**:

I expected to not actually do anything when I accidentally used a strike with my free hand, while holding the rod.

**Why is this bad/What are the consequences**:

I figure it's a nasty way to bypass the rods downside.

**Steps to reproduce the problem**:

**When did the problem start happening**:

Tried it a few days ago. I used a CQC manual, then later a miner handed over a rod and I activated it, apparently I could still CQC people. I only tested it with disarm strikes though.

**Extra information**:

**Comment by lewcc** [comment]
Fixed in #16988
