### ISSUE TITLE
Ranged holoparasites in scout mode can go from CC z-level to cyberiad

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16135]
**Issue Description**:
Ranged holoparasites in scout mode are able to go to cyberiad by entering a shuttle transition zone near the west of the z-level. (or perhaps it was just z-level boundary, I did not have the time to recreate)

**What did you expect to happen**: 
You stay on CC z-level

**What happened instead**:
Popped up at cyberiad north of departures.

**Why is this bad/What are the consequences**:
Any admin spawned CC antagonists with holoparasites can scout every inch of the station immediately.

**Comment by ppi13** [comment]
Technically not a bug, if you enter the shuttle transition zone you go to the station z-level.
Working As Intended™
