### ISSUE TITLE
The Tesla tend to get stuck in certain areas

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#16142]
**Issue Description**:

The Tesla tend to get stuck in certain areas when released, causing it to loop around the same area

**What did you expect to happen**: 

For the tesla to randomly hunt down and murder everyone on the station

**What happened instead**:

It was as if the tesla was not released at all, just had an area walled off and called it a day

**Why is this bad/What are the consequences**:

It makes a tesla release a fucking joke

**Steps to reproduce the problem**:

Release multiple teslas around the station, and in areas such as between mechanic and engineering, solars, arrival the tesla will loop

**When did the problem start happening**:

Dunno

**Extra information**:

The reason this happens is that the method of movement for the energy_call is that it checks it's shocked list for what to move to next, and it generally shocks the same half a dozen to a dozen objects over and over again, which means it will move to those objects again.

**Comment by hal9000PR** [comment]
Perhapse we could make Tesla shocks break those items in the area so it is forced to keep moving?
