### ISSUE TITLE
Krav maga can steal peoples grabs.

### ISSUE THREAD

**Issue by SpookSpooky** [ParadiseSS13/Paradise#16144]
**Issue Description**:
Krav Maga gloves can steal grabs

**What did you expect to happen**: 
To be able to disarm someone whos grabbed me and not steal their grab

**What happened instead**:
I disarmed someone who grabbed me and their grab was stolen.

**Why is this bad/What are the consequences**:
Anyone who uses Krav and disarms someone whos grabbed them can steal their own grab, confuse the krav user and generally shouldn't work.

**Steps to reproduce the problem**:
Requirements: Krav gloves, 2 people, a bit of luck (worked 2/3 times I tested actively ingame)
1. Krav user gets grabbed by the second person passively (might require reinforced grab)
2. Krav user disarms the person and walks away
3. Krav user now has an invisible grab and is slow. Congratulations you've commited dark magic with Krav Maga.

**When did the problem start happening**:
Semi recently, or it was always a thing I never found when I used to play warden.

**Extra information**:
You can steal alot more things. This was just another that was found. Others include kisses, slaps, wizard magic and a few others.

This was edited to be less confusing after the issue was fully figured out.

**Comment by Coolrune206** [comment]
Could be because disarming with Krav tries to take the item from the hand of the aggressor and place it into your hand - in this case, it would apparently be trying to "disarm" the grab, putting the grab into your hand and giving you the associated slowdown.

**Comment by S34NW** [comment]
This will get fixed with #15722
