### ISSUE TITLE
Pinpointer not pointing to AI during Doomsday

### ISSUE THREAD

**Issue by ItsMarmite** [ParadiseSS13/Paradise#16150]
**Issue Description**:

During a Malfunctioning AI using Doomsday, the Nuclear Pinpointer did not have an option to point to the doomsdaying AI's core after it had been moved.

**What did you expect to happen**: 

The Nuclear Pinpointer, when switched on, would have an option to point towards the AI's core, allowing its location to be known for the race to destroy it before total station Armageddon.
This is not an intended feature. The Pinpointer is supposed to be the bane of a malfunctioning AI that wants to hide its core. 

**What happened instead**:

The Pinpointer only had options available to point towards the Nuke, which was contained in the vault, and the Nuke Disk, which was held by the CMO in the library; as if the Pinpointer had not recognised that the AI was doomsdaying.

**Why is this bad/What are the consequences**:

The crew is unable to locate the general direction of the AI, thus allowing an AI to hide in the top right corner of the Z Level and vibe until Doomsday has counted down.

**Steps to reproduce the problem**:

Have Malfunctioning AI Doomsday the station. Pick up pinpointer. Turn on pinpointer. Panic.

**When did the problem start happening**:

Occurred in a round earlier today when I, as the Acting HOS, picked up the pinpointer. AI was found by two Security Officers without the pinpointer, AI destroyed with one second left on the clock.

**Extra information**:

I don't know what could've caused this other than the code for the pinpointer not realising the AI had doomsday'd.

**Comment by dearmochi** [comment]
The pinpointer is made to point the disk when Doomsday is initiated, but it otherwise doesn't turn it on.

https://github.com/ParadiseSS13/Paradise/blob/01c0c86d01f7aaa418a077addda948973c4e518f/code/game/gamemodes/malfunction/Malf_Modules.dm#L257-L260

Pretty terrible way of doing things.

**Comment by matttheficus** [comment]
reopenned, pinpointer should point to the AI core not the nuke inside of it.

**Comment by Shadow-Quill** [comment]
> reopenned, pinpointer should point to the AI core not the nuke inside of it.

The pinpointer does point at the AI core.

**Comment by Spaghetti-bit** [comment]
The pin pointer now actively tracks the AI during delta. No idea when this was fixed exactly but it’s no longer issue or reproducible
