### ISSUE TITLE
Getting Stuck in Piping and Rapidly Dying as Slime

### ISSUE THREAD

**Issue by WesleySmites** [ParadiseSS13/Paradise#16153]
**Issue Description**:

As a slime, while ventcrawling, I become unable to move and quickly die. This happened in both scrubber and air supply pipes. This tended to happen when I was changing direction.

**What did you expect to happen**: 

To not be immobilized and die.

**What happened instead**:

I became immobilized and died.

**Why is this bad/What are the consequences**:

Ventcrawling characters need to be able to ventcrawl.

**Steps to reproduce the problem**:

I spawned in three times as a pyroclastic anomaly slime. I left the SM where I was spawned and ventcrawled. In the first instance, I ventcrawled to the toxins test room and became immobilized and died within 5 seconds 1 tile north of the "Toxins Mixing Room Vent Pump #1" (at least, I think so. I ahelped and this is where my corpse popped out). The second time I became immobilized and died within a tile of "Prison Cell Block A Air Scrubber #6." The third time I died within a tile of "Virology Vent Pump #1." All of these deaths occurred within about 

**When did the problem start happening**:

**Extra information**:

One person in deadchat said that they only had this issue while in scrubbers.

**Comment by S34NW** [comment]
Pyro anom slimes randomly slow down and die in the open too, usually when there is low pressure/temp

**Comment by DeveloperLoser** [comment]
Haven't had this issue in those locations, however it should be noted that due to buggy code you can switch pipe nets, such as scrubbers to supply in disposals, and supply to the R&D server cooling loop (in-escapable death). This is potentially related to that but is more likely just atmos techs being lazy and draining all air out of supply, killing/freezing anything in the pipes.

**Comment by Contrabang** [comment]
I haven't seen this anytime recently, closest I can think of is slimes dying in pipes that are in space, which is intended.

**Comment by DGamerL** [comment]
I've tried to ventcrawl myself on the latest master branch, haven't experienced anything else or heard others with this same experience, which means that it almost certainly has been fixed in the past few years! Thanks for making the report, and if it happens again, feel free to open a new one!
