### ISSUE TITLE
Dark blessing nullrod from lavaland can not be picked up

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#16157]
**Issue Description**:

Dark blessing nullrod from tendril chests can not be picked up

**What did you expect to happen**: 

For people to pick it up, get it stuck to their arms, and be able to stab things with it

**What happened instead**:

Players report being unable to pick it up.

**Why is this bad/What are the consequences**:

Makes the loot useless, and leaves an armblade on the ground no one can pick up

**Steps to reproduce the problem**:

Open chest with dark blessing.
Attempt to pick it up.

**Comment by hal9000PR** [comment]
Didn't you fix this yourself?

**Comment by Qwertytoforty** [comment]
maybe
