### ISSUE TITLE
Proto kinetic accelerator cooldown increased when another pKA is in backpack

### ISSUE THREAD

**Issue by nrobisch** [ParadiseSS13/Paradise#16161]
**Issue Description**:
When you are dual-wielding proto kinetic-accelerators, they have increased cooldown between shots. However this increased cooldown also seems to apply when the second pKA is in your backpack as well, despite not being wielded.

**What did you expect to happen**: 
pKA having the normal cooldown.

**What happened instead**:
pKA had an increased cooldown.

**Why is this bad/What are the consequences**:
I gotta go fast, and this stops me from doing so. Also disincentivizes miners from picking up dead miner's pKAs

**Steps to reproduce the problem**:
Wield a pKA, then put another one in your explorer's satchel.

**When did the problem start happening**:
A couple days ago when I picked up a dead miner's pKA and put it in my backpack, I noticed I suddenly fired my main one much slower. It very well could have been an issue before however.

**Extra information**:
I have only tested this with explorer's satchels, but it very well could work with other backpack/containers.

**Comment by hal9000PR** [comment]
This is intended.

**Comment by shmabuu** [comment]
Yeah not an issue, it's 100% intended
