### ISSUE TITLE
Robotic Brains don't get runechat.

### ISSUE THREAD

**Issue by SabreML** [ParadiseSS13/Paradise#16175]
**Issue Description**:
Robotic/Positronic brains (and possibly others) don't get runechat.

**What did you expect to happen**:
When speaking, robobrains would have their messages appear above them as runechat.

**What happened instead**:
They didn't.

**Why is this bad/What are the consequences**:
Could (and probably has) lead to robobrains being forgotten on a table somewhere until they pray for an admin or something.
Since a lot of people seem to rely entirely on the chat box for messages now.

**Steps to reproduce the problem**:
1. Become robobrain.
2. Talk.

**When did the problem start happening**:
Unsure. It *should* have been added in #15604, so presumably a PR after that removed it by accident.

**Extra information**:
The issue seems to be that `update_runechat_msg_location()` is being called before the brain mob is moved into the robobrain item, so it doesn't pass the `if(container)` check.
https://github.com/ParadiseSS13/Paradise/blob/91c3d1750dc55334cfb4531754cd0da8869114da/code/modules/mob/living/carbon/brain/brain.dm#L112-L118
https://github.com/ParadiseSS13/Paradise/blob/91c3d1750dc55334cfb4531754cd0da8869114da/code/modules/mob/living/carbon/brain/robotic_brain.dm#L203-L216

**Comment by Wojz** [comment]
> Could (and probably has) lead to robobrains being forgotten on a table somewhere until they pray for an admin or something.

All the time.

**Comment by SteelSlayer** [comment]
When a ghost signs up, robobrain runechat is working fine for me . However when I deconstruct a borg and their robobrain appears on the floor, their runechat is broken.

**Comment by SabreML** [comment]
Wasn't able to see it when I joined as a robobrain last round, but it all seems to be on `New()` so maybe it's just inconsistent.
