### ISSUE TITLE
Cannot Create Paper Hearts - Receive Message Indicating Tool is Missing

### ISSUE THREAD

**Issue by WesleySmites** [ParadiseSS13/Paradise#16170]
**Issue Description**:

When attempting to craft a paper heart, I receive a message that indicates that I do no have the required tools.

**What did you expect to happen**: 

I expected to craft a paper heart.

**What happened instead**:

I received a message indicating I could not.

**Why is this bad/What are the consequences**:

One cannot create paper hearts.

**Steps to reproduce the problem**:

Attempt to create a yellow paper heart with a multicolor crayon or yellow crayon.

**When did the problem start happening**:
 6/12

**Extra information**:

Another person tried but was unable to craft a paper heart; they said that they received a similar message concerning a lack of tools.

**Comment by SpookSpooky** [comment]
Not a bug, paper hearts require a red crayon because hearts are red I guess. Pretty sure the tool required says just "crayon" and that might need to be changed but crafting a heart is working properly.

**Comment by WesleySmites** [comment]
> Not a bug, paper hearts require a red crayon because hearts are red I guess. Pretty sure the tool required says just "crayon" and that might need to be changed but crafting a heart is working properly.

Gotcha, good to know. New to Github; would you recommend opening a new issue requesting this change?

**Comment by WesleySmites** [comment]
Making it a new issue.
