### ISSUE TITLE
Security Cybrog Stun Baton module randomly breaks

### ISSUE THREAD

**Issue by DaydreamIQ** [ParadiseSS13/Paradise#16179]
**Issue Description**:

The Cyborg's stun baton module will sometimes depower without any clear fix aside from complete module reset. Any attempts to power it again will result in "The stun baton has no power to draw from" message despite the contrary. 
**What did you expect to happen**:  It to power up

**What happened instead**:

The module states there's no power despite there being plenty. Examining the baton results in it saying it has 5% charge. The only means by which to fix it is to completely reset most of the time

**Why is this bad/What are the consequences**:

Because having a module randomly break leaves the borg with only a disabler and handcuffs. Which can make it impossible for them to apprehend certain criminals such as Carp users.

**Steps to reproduce the problem**:

Unknown. Cause seems to be random, though latest case seemed to happen on excessive use of stunbaton while powered down

**When did the problem start happening**:

At the very least the past two weeks

**Extra information**:

**Comment by SteelSlayer** [comment]
I've tried to replicate this, but no luck. It's obviously an issue though, because I've seen multiple people talk about it. If anyone has any more info on how to reproduce this, let me know.
