### ISSUE TITLE
Clown Shoes not Wobbling

### ISSUE THREAD

**Issue by WesleySmites** [ParadiseSS13/Paradise#16171]
**Issue Description**:

As a clown, my character does not wobble or bounce when wearing clown shoes..

**What did you expect to happen**: 

I expected that, while walking, my clown shoes would result in my sprite bouncing or wobbling.

**What happened instead**:

My character moonwalked without vertical movement.

**Why is this bad/What are the consequences**:

Clown shoes should wobble.

**Steps to reproduce the problem**:

Spawn as a clown with a loadout including jackboots before equipping clown shoes.

**When did the problem start happening**:
 6/12

**Extra information**:

Equipping the clown shoes in my locker or in my backpack did not fix the issue. Equipping the clown exosuit, unequipping it, and equipping it again fixed the issue.

**Comment by SteelSlayer** [comment]
Can't reproduce this. Did you make sure you didn't accidentally toggle on the "waddle dampeners" for the shoes by control clicking them? If it's on, you won't get the waddle when you equip them.

**Comment by WesleySmites** [comment]
> Can't reproduce this. Did you make sure you didn't accidentally toggle on the "waddle dampeners" for the shoes by control clicking them? If it's on, you won't get the waddle when you equip them.

Ah, forget to mention I tried toggling that on and off with no success.
