### ISSUE TITLE
Player slimes (created via black extract) are unable to ventcrawl.

### ISSUE THREAD

**Issue by LufgtHuron** [ParadiseSS13/Paradise#1620]
This has been an issue for a while now, since the monkey ventcrawl update I think. It is impossible to ventcrawl - whether it a combination of key + click or the long gone menu button.

**Comment by TheDZD** [comment]
@tigercat2000 slimes are supposed to be able to ventcrawl with the current system, correct?

**Comment by tigercat2000** [comment]
@TheDZD Yeah, their verb was removed with all the others, but never set their ventcrawler variable to 1/2 to keep ventcrawl.
