### ISSUE TITLE
Proximity sensor - igniter assembly doesn't work when in pockets or held in hands

### ISSUE THREAD

**Issue by RobertRoberts2020** [ParadiseSS13/Paradise#16219]
**Issue Description**:

Proximity sensor - igniter assembly doesn't work when in pockets or held in hands

**What did you expect to happen**: 

I expected the assembly to cause sparks indepantly of it's storage slot location

**What happened instead**:

The red light flickers but sparks don't come out.

**Why is this bad/What are the consequences**:

Because I want to moonwalk while sparking all around very fabously down the hallways while wearing these contraptions because they'r very very cool and awesome, also it has other uses which are not really important right now

**Steps to reproduce the problem**:

put together two of these and fit them in your pockets, they won't work, maybe the first time, but they used to work while I walked around the place, so someone probbly broke it on purpose buecase they hate fun

**When did the problem start happening**:

sometime

**Extra information**:

Fix this k bye

**Comment by SteelSlayer** [comment]
Unintentionally broken by me a while back, this will be fixed in #15836.
