### ISSUE TITLE
Cannot open pod doors that are in darkness

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#1621]
if a large pod door is in darkness trying to open it via the spacepod menu will not work stating that there are no nearby pod doors

https://goo.gl/QZ8Fjj

**Comment by TheDZD** [comment]
[This](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/vehicles/spacepods/spacepod.dm#L641) line needs to be changed to use orange instead of oview.
