### ISSUE TITLE
Burning a paperstack can make an invulnerable item

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16218]
**Issue Description**:
Burning a paper stack with the bottom sheet having a photo attached creates an un-interactable, un-burnable sheet that cant be read or edited.

**What did you expect to happen**: 
There not to be a piece of paper that can't be destroyed

**Comment by S34NW** [comment]
```
[2021-10-30T22:18:46] Runtime in paper_bundle.dm,69: list index out of bounds
   proc name: attackby (/obj/item/paper_bundle/attackby)
   usr: The unidentified entity (s34nw) (/mob/living/carbon/human)
   usr.loc: The floor (223,13,1) (/turf/simulated/floor/plasteel)
   src: Judgement (/obj/item/paper_bundle)
   src.loc: the unidentified entity (/mob/living/carbon/human)
   call stack:
   Judgement (/obj/item/paper_bundle): attackby(the welding tool (/obj/item/weldingtool), the unidentified entity (/mob/living/carbon/human), "icon-x=15;icon-y=13;left=1;scr...")
   the welding tool (/obj/item/weldingtool): melee attack chain(the unidentified entity (/mob/living/carbon/human), Judgement (/obj/item/paper_bundle), "icon-x=15;icon-y=13;left=1;scr...")
   the unidentified entity (/mob/living/carbon/human): ClickOn(Judgement (/obj/item/paper_bundle), "icon-x=15;icon-y=13;left=1;scr...")
   Judgement (/obj/item/paper_bundle): Click(null, "mapwindow.map", "icon-x=15;icon-y=13;left=1;scr...")
   (This error will now be silenced for 10 minutes)
```

**Comment by S34NW** [comment]
Steps to reproduce:


- Get a paper
- Attach a photo to it
- Add another paper onto that
- Light it with a welder or other tool
- It will burn a blank paper and leave a stack that cant be interacted with or burnt
  - The only way to remove the stack is by right-clicking and pressing "loose bundle"

**Comment by S34NW** [comment]
The order of paper operations is important, click on a photo-attached-paper with a non attached paper, else it will burn like normal.

**Comment by Sirryan2002** [comment]
paperstacks need to be refactored honestly, old code and it's really starting to show its age
