### ISSUE TITLE
NanoUI Issues

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#1623]
- NanoUI is ridiculously resource-intensive ~~on the server~~ (apparently it's on clients in specific, whoops) for just being a simple UI.
- Certain NanoUI interfaces have a tendency to repeatedly crash people on certain screens. Recently, the traitor uplink has been doing this very often.

In my opinion, NanoUI isn't worth these two major issues for a nice UI. Using stylesheets, the same can be accomplished without using NanoUI, alternatively, we may want to port the HTML interface written by @nullquery and try to replace NanoUI interfaces with it.

@Markolie @Fox-McCloud @ZomgPonies

**Comment by tigercat2000** [comment]
@TheDZD We don't even really need his system, just using the browser datum can closely mirror NanoUI.

**Comment by TheDZD** [comment]
@tigercat2000 Hence me labeling it as an alternative.

**Comment by Markolie** [comment]
Porting that interface is a bad idea. It'd take a huge amount of effort to convert everything, and despite nullquery stating he'd do it himself, none of that has happened: https://github.com/tgstation/-tg-station/pulls?q=is%3Apr+author%3Anullquery+is%3Aclosed.

With regards to nanoUI being resource-intensive: I'm not sure about that. I'm sure that compared to other processes running on the server, it can't be all that bad. If it's truly a primary cause of lag for the server then sure, I think that's a good reason for replacing it. If it's less efficient than regular interfaces but the difference is not gigantic, then I think it's a good reason to replace it. Mind you that a lot of the NanoUI performance "issues" come from many interfaces automatically updating every tick, which regular interfaces don't. If we disable this functionality (and I don't think we should), we'd probably see a very large performance boosts.

I'm not aware of the crashing issue and I don't experience it myself. I can look into fixing it if anyone can provide me with debug data (when it happened, what screen, what they clicked, etc.). So far I have not seen this reported in the issue tracker.

**Comment by TheDZD** [comment]
@Markolie Haven't been experiencing NanoUI crashes myself either, but recently people have been ahelping fairly often about their PDA crashing them when opening the traitor uplink. Trying to open the  PDA again at that point crashes them, and even when given a new PDA and uplink it would crash.

**Comment by Markolie** [comment]
Does their game crash, or does the PDA itself stop functioning?

**Comment by TheDZD** [comment]
Game crashes entirely.

**Comment by tigercat2000** [comment]
@Markolie From what I understand, It has a very significant performance load on client connections.

The 10-20 second delay that happens when you connect to the server and can't open any UI windows is most likely due to NanoUI- it sends every UI's resources to the client on Login(). 

As for the crashes, I have experienced them myself, though they are rare. I know that runtimes can easily cause the blank-screen issues, and there isn't actually a way to fix the client other than hoping that relogging will fix it.

Baystation12 has a button that forces a full redownload of NanoUI resources, to fix most of those issues.

As for @TheDZD mentioning actual __crashes__, that would be new to me.

**Comment by Markolie** [comment]
The PDA blanking is a very old issue, and Bay added a "Reset PDA" button to fix that whenever it happens (which I ported a week back). I must say that the issue with every UI blanking hasn't happened to me in a long time.

As for NanoUI sending the data to the client on login - it's indeed possible that that prevents users from accessing UI's the first 10-20 seconds, although I wonder if it's just NanoUI that causes it (we'd have to disable this functionality to check). 

Either way - NanoUI looks great, and is extremely powerful in what it can do. It's also very easy to modify (once you know the template system) and use, and as such I'm very strongly opposed to using a different system. It's better if we look for a way to resolve these performance issues, rather than moving to a different system.

**Comment by TheDZD** [comment]
If we can pin down the causes of the issues, that would definitely be preferable to completely redoing the system. My main issue with it is really the client crashing.

**Comment by tigercat2000** [comment]
@Markolie It would be a pain to get rid of, and fixing things is almost always better than abandoning them and moving to another system.

However, I would like to point out that it's template system is considerably more complicated than plain HTML code, which can be used to emulate it's visuals easily without the delay issues or general slowdown of it. For that matter, it would be difficult to irreversibly break html for a round.

**Comment by Markolie** [comment]
@Krausus found an issue causing PDA's to blank - the message sent to PDA's when science completes all objectives is a string instead of a proper associative list, thus breaking the PDA when it's received.

@Krausus will you take care of fixing that, or should?

**Comment by Krausus** [comment]
I'm looking into it. Seems there's a few things that can add bad messages, though job objective completion is obviously the biggest offender.

**Comment by Markolie** [comment]
Relevant to not being able to open UI's when you join: http://www.byond.com/forum/?post=1908255

**Comment by PJB3005** [comment]
Just saying, but yes, nanoUI IS EXTREMELY resource intensive for things like the advanced camera console, crew monitor, and central atmospherics computer.

And yes, the HTML interface module IS worth it by a LONG shot, @tigercat2000.

**Comment by Markolie** [comment]
We've recently added caching to all three - it makes them much less resource intensive.

**Comment by PJB3005** [comment]
Well that's nice then.

I still heavily recommend the HTML interface module, [it even has a subtype that imitates nanoUI.](http://i.imgur.com/hGXxmMl.png)

**Comment by Markolie** [comment]
Unless someone's willing to go through all our current interfaces and convert them, I think NanoUI is a better solution for the time being. Especially if BYOND fixes the issue I mentioned above.

**Comment by PsiOmegaDelta** [comment]
If someone successfully converts the code/nano/modules/human_appearance.dm interface and all its use cases to the HTML interface then I would consider it myself, as that NanoUI interface uses each of the extra features that Bay has added to NanoUI over time.

**Comment by PJB3005** [comment]
![](http://i.imgur.com/CVao1HW.png)

Yes that chart updates in real time.

No way to do that in nanoUI.

**Comment by PJB3005** [comment]
*cough
![](https://camo.githubusercontent.com/5ee9a02f62a1dec4915c5f5a4ba0789bac82271b/687474703a2f2f692e696d6775722e636f6d2f7939417266326d2e706e67)

**Comment by nullquery** [comment]
...?

**Comment by PJB3005** [comment]
That was nanoUI lagging

**Comment by Markolie** [comment]
If that's on /vg/, consider porting Bay's NanoUI changes. I'm looking at the profiler of our server right now with a population of 80+, and there's a distinct lack of NanoUI.

**Comment by PJB3005** [comment]
No, that's on paradise, I did forget to pull so it's outdated, but either way that's unacceptable.

**Comment by Markolie** [comment]
Not sure where you're getting that data, but we don't get that level of lag on our live server from NanoUI.

**Comment by Markolie** [comment]
Oh, I see. You're using the security montior. Yes, that used to be a laggy piece of shit after we converted it to NanoUI. If you pull you'll see that lag will completely disappear though, as we added caching to that (and any other NanoUI computers that use loop through a lot of machines, such as power monitors and crew monitors). It's made the "lag" NanoUI causes negligible. If we'd rip NanoUI out right now, the performance boost would not be noticeable.

**Comment by PJB3005** [comment]
Turns out it was

**Comment by Vivalas** [comment]
I've been getting crashes on the security records console when opening it, AFAIK that's straight HTML, not sure if that's related.

**Comment by orelbon** [comment]
@PJB3005 oh my god that graphs is beautiful pls merge

**Comment by Ar3nn** [comment]
Okay, I'm going to assume this is a general NanoUI report thread? If not, feel free to delete/ignore this comment, buuuut here goes. The Pathogen Isolator in Virology can break if you leave a syringe in the machine too long, blanking out the interface until reset.

**Comment by tigercat2000** [comment]
it's really not a general nano report thread, please make a new issue @Ar3nn

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, is this resolved?

**Comment by Tastyfish** [comment]
yeah probably, since the only useful thing in here (I think) is the security records issue, which has its own ticket.
