### ISSUE TITLE
guest pass terminal unlimited sets

### ISSUE THREAD

**Issue by DeusExVita** [ParadiseSS13/Paradise#16242]
**Issue Description**:

guest pass can be set to the same name as active crew members of a different job and be used to set/unset people from arrest, or used as job title over radio

**What did you expect to happen**: 

i can set people to arrest as a sec officer/ unset people

**What happened instead**:

using your char name.

**Why is this bad/What are the consequences**:

because anyone can unset themselves under the cappies/magies  name.

**Steps to reproduce the problem**:

honestly i have no clue, remove guest pass? change it to only use char name?

**When did the problem start happening**:

year, two years if not more ago?

**Extra information**:

**Comment by tomasalves8** [comment]
Hi @DeusExVita,

Can you explain a bit more of how you can encounter this issue?

Thanks

**Comment by matttheficus** [comment]
Given guest passes can be used to do anything that a normal ID can do, albeit on a timer, this is likely intended.
