### ISSUE TITLE
Reticence and HONK Mech being incompletable  

### ISSUE THREAD

**Issue by shmabuu** [ParadiseSS13/Paradise#16267]
Mime mech and clown mech, Reticence and HONK Mech aren't able to complete the final step 

**What did you expect to happen**: 
The mech to be complete after doing the final honk or emote at the mech

**What happened instead**:
Nothing happens when the final honk is honked after adding the clown shoes and nothing happens when emoting at the mech after adding the suspenders on it

**Why is this bad/What are the consequences**:
These mechs may not be liked by all, but they're good fun to use. Plus, this has been a bug for quite a while.

**Steps to reproduce the problem**:
Try to build a HONK mech or a reticence. You can get to the final step but it won't complete.

**When did the problem start happening**:
Not sure but it's been a good few months now, I thought someone made an issue report on it but I couldn't find it

**Comment by shmabuu** [comment]
Ok so apparently this is intended to prevent the grief that these mechs can cause (understandable.) Even though I can't find a PR that made this happen they are apparently able to be completed with some admin tools.

**Comment by shmabuu** [comment]
Ok so apparently this is intended to prevent the grief that these mechs can cause (understandable.) Even though I can't find a PR that made this happen they are apparently able to be completed with some admin tools.

**Comment by AffectedArc07** [comment]
> Ok so apparently this is intended to prevent the grief that these mechs can cause (understandable.) Even though I can't find a PR that made this happen they are apparently able to be completed with some admin tools. 

.....Who's saying this? I don't remember any pull to do this and the code is still there to make it work. This is a bug.
