### ISSUE TITLE
RCD can be used with telekinesis 

### ISSUE THREAD

**Issue by Herder05** [ParadiseSS13/Paradise#16289]
**Issue Description**:

You can use tk on a rcd to decon things at long range and even better you can move the rcd while deconning allowing you to decon more then 9 things at a time! (this works with all rcd modes)

**What did you expect to happen**: 

rcd to be like tools and not work with tk

**What happened instead**:

rcd worked with tk

**Why is this bad/What are the consequences**:

can be used to decon rooms your not in and just make rcds even more cheesed

**Steps to reproduce the problem**:

get tk
get rcd
use rcd at long distance
move the rcd while its doing things
decon more

**When did the problem start happening**:

probably been there for ever

**Extra information**:

**Comment by Spacemanspark** [comment]
Technically not a bug, unfortunately.
