### ISSUE TITLE
Certain ghost spawns are no longer in rotation

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16282]
**Issue Description**:
Free golem and Theta station ghost spawns seem to have been removed from rotation.

**What did you expect to happen**: 
I don't recall a PR explicitly doing this, so unless there was a silent config change, this is a bug.

**Why is this bad/What are the consequences**:
Less ghost spawner variety.

**When did the problem start happening**:
Seems like a few weeks or so according to some, I can't remember a specific time when I noticed it stopping.

**Comment by Aurorablade** [comment]
that if i recall is RNG and can be fickle. such as the times admins watch in horror as RNG makes the rounds cult...5 times..in a row back to back...

**Comment by S34NW** [comment]
Bug is introduced in #15980, currently TMd

**Comment by AffectedArc07** [comment]
Fixed
