### ISSUE TITLE
Test Projectile Can Crash the Server

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1629]
Right so, this hasn't happened before until turrets were updated, but this occurred tonight:;

![ohshit](http://i.gyazo.com/d186838b97967680576669bb65d83c62.png)

It ended up calling millions of get_turf() calls and kept on processing indefinitely; this makes since, especially in the context that this was recently changed to use get_turf()

The situation that caused this was unclear; I suspect it had something to do with the Captain entering the AI chamber with a Phazon; perhaps it got stuck on something or couldn't target it well, due to it's nature, or something.

**Comment by Markolie** [comment]
Port over this change and add a check for spacepods in there as well (Bump() on the test projectile): https://github.com/Baystation12/Baystation12/pull/10087/files#diff-ef552f9576d3c5ed6eac40e5bd80cb35R388

I think that'll fix it. I don't have access to my desktop this week, so someone else will have to do it.

**Comment by Markolie** [comment]
Installed Git on my laptop - fix is PR'ed.

**Comment by TheDZD** [comment]
It's *baaaaaaaaaaaaaack*.
