### ISSUE TITLE
KA upgrades don't apply for mining borgs

### ISSUE THREAD

**Issue by Forenzek** [ParadiseSS13/Paradise#16301]
**Issue Description**:
When roboticists try to apply KA upgrades to mining borgs that just fall to the floor instead of applying.

**What did you expect to happen**: 
Expected upgrades to apply as all other do.

**What happened instead**:
Upgrades did nothing other than fall to the floor.

**Why is this bad/What are the consequences**:
Can no longer upgrade mining borg KAs

**Steps to reproduce the problem**:
Try to upgrade a mining borg KA

**When did the problem start happening**:
7/4/21

**Extra information**:

**Comment by SteelSlayer** [comment]
Likely my fault, I will look into fixing this.
