### ISSUE TITLE
AI can see syndie base test chamber cameras

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16310]
**Issue Description**:
The station AI can see the cameras in the ghost spawner research test chamber.

**Why is this bad/What are the consequences**:
The AI should not be able to see this area or be aware of its existence. 

**When did the problem start happening**:
Since they were added.

**Comment by SabreML** [comment]
Don't seem to be able to reproduce this. Could you elaborate on the steps?

**Comment by theo-3** [comment]
You can see it if you use the Jump to Network verb

**Comment by theo-3** [comment]
No idea how to fix this. Can you make a camera network hidden? (I added the cameras)

**Comment by SabreML** [comment]
> You can see it if you use the Jump to Network verb

Ahh, okay I see it now. You can fix it by adding the `"SyndicateTestLab"` network to the `restricted_camera_networks` list here:
https://github.com/ParadiseSS13/Paradise/blob/3f6eac48d17fcf336b1e2e21a12f56ee92b5abf5/code/_globalvars/lists/misc.dm#L25-L34
