### ISSUE TITLE
Jump boots don't have to be worn to be used

### ISSUE THREAD

**Issue by Wojz** [ParadiseSS13/Paradise#16334]
**Issue Description**:

You can hold jump boots in your hand and still get the HUD buttons to use them, and they work.

**What did you expect to happen**: 

To have to wear jump boots to use their jump boost.

**What happened instead**:

I can hold the jump boots and just use their jump boost thing like that.

**Why is this bad/What are the consequences**:

You can have many pairs of boots on you and switch between them to become Sonic the Hedgehog or such. Also it's kind of dumb ICly that it works.

**Steps to reproduce the problem**:

1. Acquire jump boots.
2. Hold the jump boots.
3. Press the HUD button.

**When did the problem start happening**:

No idea. Probably always?

**Extra information**:

Miner moment

**Comment by Coolrune206** [comment]
It's possible this may actually also work out of pocket slots.
