### ISSUE TITLE
Gateway terror spiders never GC

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#16358]
**Issue Description**:
Terror spiders in the gateway never garbage collect.

Taken from multiple rounds
![image](https://user-images.githubusercontent.com/25063394/125522703-d66ff5b2-ecc5-4aac-8399-d04d7a7281b8.png)
![image](https://user-images.githubusercontent.com/25063394/125522707-359bcbff-04fc-43bf-bea7-828c403eb61c.png)
![image](https://user-images.githubusercontent.com/25063394/125522718-640ed40f-459f-4d0f-a718-3ea10dc0ed0e.png)
![image](https://user-images.githubusercontent.com/25063394/125522803-3090214a-3eeb-4e90-9aad-1cc1ea41c65b.png)

**What did you expect to happen**: 
Them to GC properly atleast some of the time

**What happened instead**:
Every gateway terror spider has a 100% GC fail rate. This makes the GC cry bloody murder and use a lot of excess CPU (see timings)

**Why is this bad/What are the consequences**:
See above.

**Steps to reproduce the problem**:
1. Load gateway terror spider mission
2. Kill some of them
3. `Debug` > `Display del() log`

**When did the problem start happening**:
Unsure

**Extra information**:
Unsure

**Comment by Fox-McCloud** [comment]
Over 150 ms to hard delete 1 mob *ONCE*. 

Patently ridiculous.
