### ISSUE TITLE
Rapid Pipe Dispensers not updating pipe choice

### ISSUE THREAD

**Issue by ItsMarmite** [ParadiseSS13/Paradise#16356]
**Issue Description**: Rapid Pipe Dispenser not updating pipe placement choice.

**What did you expect to happen**:  A four way manifold pipe being placed instead of a straight pipe.

**What happened instead**: The RPD continued to place straight pipes.

**Why is this bad/What are the consequences**: This can be VERY bad in situations such as what actually occurred or very tedious in situations where you want to repipe atmospherics.

**Steps to reproduce the problem**: Take an RPD. Choose straight pipe. Place pipes a few times. Change to four way manifold. Place pipe.

**When did the problem start happening**: Today.

**Extra information**: I have never seen this happen before and I'm wondering if its replicable.

**Comment by DeveloperLoser** [comment]
Similar event here, except uh, for a good while straight pipes would just... appear. Initially thought it was admemery due to previous round but it seemed to happen every 2 seconds exactly. Could be related, but never seen before or since. Also stowing my RPD, switching settings, and throwing it across the room did nothing to stop it.

**Comment by Sirryan2002** [comment]
I think this may have been fixed but I'm not 100% sure. I was not able to reproduce it personally, but I would like other people to test this aswell.

**Comment by Henri215** [comment]
Could not replicate, @ItsMarmite have you seen it happening more than once?

**Comment by DGamerL** [comment]
Has not been able to be replicated by multiple people, and no extra context has been given or more detailed steps on how to reproduce it. If this bug appears again, feel free to make a new issue report!
