### ISSUE TITLE
Mining doors bolted and do not unbolt

### ISSUE THREAD

**Issue by Zergspower** [ParadiseSS13/Paradise#16368]
**Issue Description**:
Mining dock doors don't unbolt when the ship docks, potentially due to the ship not being there at the start.

**What did you expect to happen**: 
Unbolt/bolt as the ship come and goes

**What happened instead**:
called the ship at round start and the doors bolted, had to get AI to unbolt

**Why is this bad/What are the consequences**:
Cant mine

**Steps to reproduce the problem**:
Start
Call mining ship to station
see results

**When did the problem start happening**:
round start

**Extra information**:

**Comment by AffectedArc07** [comment]
https://github.com/ParadiseSS13/Paradise/issues/13950
