### ISSUE TITLE
Sometimes you can see what a person is doing with a tool

### ISSUE THREAD

**Issue by michaelyesok** [ParadiseSS13/Paradise#16366]
**Issue Description**:

After i had given a multitool to someone, the multitool, The multitool did not disspear and moved when that person moved it from there hands to there bag, ect.

**What did you expect to happen**: 

For the multitool to not show up and show what the person is doing with it.

**What happened instead**:

The multitool showed me what the other person was doing and keept showing up in my screen

**Why is this bad/What are the consequences**:

It allows you to see what the person is doing with a item even though you cant see the person.

**Steps to reproduce the problem**:

Print multitool and toolbox
Put toolbox on table with the interface open.
Wait for someone to pick it up
You now see what the person is doing

**When did the problem start happening**:

No idea.

**Extra information**:

![image](https://user-images.githubusercontent.com/84622738/125693284-eda96ebb-b498-4494-92f6-a91ab9d875e5.png)

**Comment by SabreML** [comment]
I've had this happen with a lot of other items myself, so it's not just limited to tools. Seems to be related in some way to having the inventory UI open when someone else picks it up.
