### ISSUE TITLE
morgue is all access

### ISSUE THREAD

**Issue by Greenbean73** [ParadiseSS13/Paradise#16369]
**Issue Description**:
the morgue is set to all access, meaning you can get into the medbay via the morgue hallway door

**What did you expect to happen**: 
the medbay main entrance is locked to med-only, meaning that other hallway access doors should also be med-only

**What happened instead**:
the morgue hallway door and medbay door are both all access, meaning that non-med people can get in

**Why is this bad/What are the consequences**:
anyone can get into medbay

**Steps to reproduce the problem**:
step 1: try going through the medbay main entrance
step 2: realize that the medbay main entrance is locked, and only medical personnel can open it
step 3: try going through the morgue hallway door
step 4: just walk right on in, because the door opened (when it shouldnt)

**When did the problem start happening**:
i only noticed it when someone mentioned it was all access. mustve been that way since the map was added

**Extra information**:
should probably check for similar issues in other departments

**Comment by SabreML** [comment]
#13950

**Comment by S34NW** [comment]
fixed

**Comment by tomasalves8** [comment]
Can this be closed? @dearmochi

**Comment by Greenbean73** [comment]
pretty sure it can be
