### ISSUE TITLE
Emagging a display case does not open it

### ISSUE THREAD

**Issue by Wojz** [ParadiseSS13/Paradise#16377]
**Issue Description**:

When you use your emag on the display case, it does not open it. Instead, it seems that another ID has to be used subsequently.

**What did you expect to happen**: 

For the display case to behave like every other emaggable lock in the game and open upon emagging.

**What happened instead**:

It does not open, but still triggers the alarm in captain's office.

**Why is this bad/What are the consequences**:

Inconsistent behavior is bad, because it can easily trip up a player who does not expect it.

**Steps to reproduce the problem**:

1. Get an emag
2. Click captain's display case with it

**When did the problem start happening**:

When #16096 made them emaggable to begin with.

**Extra information**:

**Comment by hal9000PR** [comment]
I'm pretty sure emagging it removes the access restrictions on it. So anyone can just open it.

**Comment by Wojz** [comment]
> I'm pretty sure emagging it removes the access restrictions on it. So anyone can just open it.

With an ID, not an empty hand or anything. Which is inconsistent with what the emag does to literally anything else.
