### ISSUE TITLE
Headcrab Zombies become Invisible when a collar is put on them.

### ISSUE THREAD

**Issue by Raydon1206** [ParadiseSS13/Paradise#16384]
**Issue Description**:
Headcrab zombies made sentient via rainbow extract turn invisible when a collar is put on them.

**What did you expect to happen**: 
Headcrab zombie stays visible.

**What happened instead**:
They turned invisible, sprite missing.

**Why is this bad/What are the consequences**:
Being unable to click on a zombie sounds like it might be really annoying.

**Steps to reproduce the problem**:
1.) Find a rainbow extract potion
2.) Find a headcrab
3.) Become headcrab
4.) Zombify your old body.
5.) Have someone put a collar on your zombie corpse.
6.) Achieve invisibility.

**When did the problem start happening**:
7/17/2021 at around 1:00 PM

**Extra information**:
Probably don't need to do the exact same steps I did but, they are there for posterity sake.

**Comment by SabreML** [comment]
#16405
