### ISSUE TITLE
New change mob Appearance is cluttering admin tab, did not replace the old one

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#1640]
![image1](http://puu.sh/jpyYZ/4f872b8f5b.png)
![image2](http://puu.sh/jpznQ/ec5f2f0f8d.png)

As you can see, there is no need to have it two places, as well as it did not remove the original "Change appearance" button

**Comment by TheDZD** [comment]
@Markolie

**Comment by Markolie** [comment]
Should be an easy fix, but someone else will have to do it as I'm at Gamescom.

**Comment by Regen1** [comment]
@TheDZD Pls
The fact that it moved the entire adminpanel to verbs to the right makes it impossible to do anything without searching for ages
