### ISSUE TITLE
aghosting as a golem and then reentering body forces golem to drop everything in pockets.

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#16415]
Upon aghosting and then reentering my body as a golem, I dropped my ID, PDA, and everything in my pockets. This happened multiple times. This happens only upon reentering my body.

**Comment by farie82** [comment]
Could not reproduce locally. Tried using the `Re-enter corpse` button and verb, double clicking my character and directly possessing the golem by drag + dropping my ghost sprite.
None of the cases caused my character to drop their items. Tried it with 3 different golem spawns as well. Servant using the item, adamantine using the spawner. And by manually spawning a golem

**Comment by Sirryan2002** [comment]
Have not had this issue since, gonna close it for now since it could not be reproduced
