### ISSUE TITLE
Borg detonation's much larger than before.

### ISSUE THREAD

**Issue by Forenzek** [ParadiseSS13/Paradise#16410]
**Issue Description**:
Borg detonations seem to have grown significantly. Today when detonated it destroyed a 2x3 area all the way down to lattice/space and completely destroyed my brain/MMI. 

**What did you expect to happen**: 
Typically when detonated it damages the area but doesn't destroy floor tiles or the brain/MMI

**What happened instead**:
https://i.imgur.com/ch7Oevy.png
this is what happened

**Why is this bad/What are the consequences**:
Borgs are completely out of the round when detonated and can no longer have their brains/MMI recovered. You can also now use suicide borgs as a significant weapon to completely destroy equipment if you wanted as the detonation is significantly more powerful than before.

**Steps to reproduce the problem**:
1. Get a borg
2. Detonate said borg

**When did the problem start happening**:
Today 7/22/21

**Extra information**:
This happened to two borgs at the same time so its not just a one off and the borgs were not next to each other when it happened so it wasn't just a cumulative effect from two explosions at the same time.

**Comment by hal9000PR** [comment]
Where you emagged or hacked by a malf AI? That makes your explosion size larger.

**Comment by Forenzek** [comment]
I'm an idiot, ignore this. Completely forgot that the AI hacked us right before we were detonated. Closed the issue. Sorry for this.

**Comment by Spacemanspark** [comment]
Bant 4 lif, how d a r e
