### ISSUE TITLE
Swarmers Can Delete Hardsuits Via Eating SSUs

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#16413]
**Issue Description**:
Swarmers can delete hardsuits from existence by the SSU the suit is stored in.

**What did you expect to happen**: 
For the spacesuit to be dropped on the floor or ejected in some manner

**What happened instead**:
The hardsuit was completely deleted

**Why is this bad/What are the consequences**:
Bugs are bad and also hardsuits and EVA suits are a very limited resource on station that generally shouldn't be destroyed

**Steps to reproduce the problem**:
1. Get a swarmer
2. Have a SSU with a hardsuit or EVA suit in
3. Have swarmer eat the SSU
4. Suit is now delet :.(

**Extra information**:
Might extend to when SSUs are destroyed in general, only saw it happen with a swarmer though

**Comment by Mitchs98** [comment]
`/obj/machinery/suit_storage_unit/Destroy()
	SStgui.close_uis(wires)
	QDEL_NULL(suit)
	QDEL_NULL(helmet)
	QDEL_NULL(mask)
	QDEL_NULL(boots)
	QDEL_NULL(storage)
	QDEL_NULL(wires)
	return ..()`

I could be wrong but based on 276 in suit_storage_unit.dm, it's intended behavior for whatever is inside to get destroyed on destruction. Not really a bug, but perhaps it should drop the contents on destruction whatever than banishing them to the shadow realm.
