### ISSUE TITLE
Revenants aren't listed under antags in the orbit menu with AHUD on

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#16412]
**Issue Description**:
Revs aren't in the list

**What did you expect to happen**: 
Revs to be in the list

**What happened instead**:
Rev wasn't in the list

**Why is this bad/What are the consequences**:
Bugs = bad

**Steps to reproduce the problem**:
1. Have a revenant
2. Enable AHUD
3. Open orbit menu and see that revenant isn't on the list

**When did the problem start happening**:

**Extra information**:
![Screenshot (456)](https://user-images.githubusercontent.com/52841396/126821890-5d20b37d-cd8a-4822-98bd-c1e4f21daf71.png)

**Comment by TheYeetster1** [comment]
was just about to make the same bug report.
