### ISSUE TITLE
Borgs cannot open morgue trays

### ISSUE THREAD

**Issue by chafla** [ParadiseSS13/Paradise#16425]
**Issue Description**:
Borgs can't open morgue trays

**What did you expect to happen**: 

As a medborg, I figured I could open/close morgue trays and put bodies away.

**What happened instead**:
Couldn't interact with morgue trays at all. This made it pretty difficult to deal with nearly a whole morgue full of bodies.

**Why is this bad/What are the consequences**:
On the mechanical side, it means that medborgs can't really handle putting bodies away or fetching them without help. Best they can do is drop corpses in the morgue and hope someone comes along to put them away. 

**Steps to reproduce the problem**:

**When did the problem start happening**:

I noticed this myself a few days ago, no idea how long it's been a thing.

**Extra information**:

**Comment by lewcc** [comment]
Not a bug, morgue trays aren't electronic so this is intended
