### ISSUE TITLE
Last resort headslug returning from monke and morphing into an alien broke the changling hivemind and abilites

### ISSUE THREAD

**Issue by shadowcrimes** [ParadiseSS13/Paradise#16437]
**Problem Description**:
Changing from last resort to humanisation to alien completely removed the hivemind chatter, as well as my ability menu.

**What did you expect to happen**: 
Nothing out of the ordinary, become an abductor, while still being a ling

**What happened instead**:
Everything changling related, outside of objectives completely shutdown and ceased to exist. Including the hivemind chat and the abilities bar.

**Why is this bad/What are the consequences:**
Requires admin intervention to fix, which changes changling hivemind naming, resets DNA, this can outright break their objectives, plus... why would you be a changling if you can't even... absorb, let alone lacking all superhuman abilties that even give the edge over just a tider with objectives.

**Steps to reproduce the problem**:
1: headslug
2: return to monke
3: humanise
4: become ayy
5: AAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**When did the problem start happening**:
As a ling in mining, on lavaland, was headslugging to bypass my tracker implant which security gave me because they didn't have first hand mindshielded evidence to warrent execution. then everything borked when I became an abductor, till I had my changling status taken and readded to fix the issue.

**Comment by SteelSlayer** [comment]
Fixed this in #17774, but I forgot to write it.
