### ISSUE TITLE
Armored Trenchcoat spelling mistake.

### ISSUE THREAD

**Issue by BurningFreeze** [ParadiseSS13/Paradise#16446]
**Issue Description**:
The armored trenchcoat's name is spelled Armored Trenchoat

**What did you expect to happen**: 
I expected to read the word coat.

**What happened instead**:
I read the word oat.

**Why is this bad/What are the consequences**:
There's a C missing, this could result in someone getting confused on the spelling of trenchcoat.

**Steps to reproduce the problem**:
Examine the armored trenchoat item.

**When did the problem start happening**:
Probably when the Armored Trenchoat was added.

![Trenchoat](https://user-images.githubusercontent.com/79219602/127285936-ba933073-df6b-4bd3-97f6-3264c69547c6.PNG)

**Comment by Wojz** [comment]
And you thought durathread was sick. Introducing armored trenchoat.
