### ISSUE TITLE
Messaging Monitor and Camera Monitor Computer Bugs

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#1644]
- When built mid-round, camera monitors and messaging monitors remain black-screened unless power to the room they are in is disabled and re-enabled.
- Camera monitors built mid-round do not have access to any cameras, no matter the access on the ID of the person trying to use said monitor.

@Markolie any ideas?

**Comment by Spacemanspark** [comment]
Same thing occurs with vending machines.
