### ISSUE TITLE
Offstation bridge area naming creates teleport issues

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#16456]
**Issue Description**:
Off-station /area/ruin/onehalf/bridge area (and possibly others) use the exact same name as on-station area, namely "Bridge".

**What did you expect to happen**: 
Areas should have unique names.

**What happened instead**:
/area/ruin/onehalf/bridge and possibly others use the same name as on-station area.

**Why is this bad/What are the consequences**:
As an admin, when I use "jump to", "area" and "bridge", I expect to land on the Cyberiad bridge, not an abandoned bridge in a space ruin in the middle of nowhere.

**Steps to reproduce the problem**:
Load a ruin with /area/ruin/onehalf/bridge or another off-station area with the same name as an on-station area.
As an admin (and possibly observer, etc) try to jump to the named on-station area.
Find yourself off-station and annoyed.

**Comment by lewcc** [comment]
This was fixed in #17326.
