### ISSUE TITLE
Pink hawaiian shirt has no drask sprite

### ISSUE THREAD

**Issue by Wojz** [ParadiseSS13/Paradise#16466]
**Issue Description**:

When wearing a pink hawaiian shirt as a drask, the sprite is missing. This is not a problem for the other shirts.

**What did you expect to happen**: 

To have a drippin pink shirt on.

**What happened instead**:

Dripless. There is no sprite. Just some red text above my head.

**Why is this bad/What are the consequences**:

I cannot have pink hawaiian shirt drip. And missing sprites are just bad.

**Steps to reproduce the problem**:

1. Be drask
2. Put on a pink hawaiian shirt
3. Cry

**When did the problem start happening**:

No idea, might have never worked.

**Extra information**:

simply gamebreaking bug

**Comment by PacifistDalek** [comment]
Note, species/drask/uniform.dmi does contain a pink hawaiian shirt sprite for the drask, so this seems to be more of a code issue than a spriting issue, in case anyone wants to take a crack at fixing it.
