### ISSUE TITLE
Disposal chutes UI becomes unresponsive, unable to retrieve items, flush, or deconstruct

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1649]
I wish I knew more about the cause, but it happened in a round earlier, if something gets stuck in the unit, deleting it appears to dump all the items on the ground, however.

**Comment by Alex6511** [comment]
@Markolie

**Comment by Markolie** [comment]
Can't fix it without more information.

**Comment by Alex6511** [comment]
So far I've only seen it happen when items are placed in the units, not before.

**Comment by Alex6511** [comment]
It could be caused by the disposal unit losing power.

**Comment by CrAzYPiLoT-SS13** [comment]
Naw, consulted with Neca, he asked melandor, they are runtiming.

**Comment by Markolie** [comment]
Post the runtime please. 

Sent from my iPhone.

**Comment by CrAzYPiLoT-SS13** [comment]
Unknown to me.
@melandor0 
@Necaladun

**Comment by Fox-McCloud** [comment]
here you go, Mark: http://hastebin.com/edogolabis.coffee

**Comment by Necaladun** [comment]
Here ya go:

runtime error: Cannot read null.density
proc name: expel (/obj/structure/disposalpipe/proc/expel)
  source file: disposal.dm,756
  usr: null
  src: the disposal pipe (/obj/structure/disposalpipe/trunk)
  call stack:
the disposal pipe (/obj/structure/disposalpipe/trunk): expel(the disposalholder (/obj/structure/disposalholder), null, 1)
the disposalholder (/obj/structure/disposalholder): move()
the disposalholder (/obj/structure/disposalholder): start(the disposal unit (/obj/machinery/disposal))

**Comment by Necaladun** [comment]
In game testing revealed it works first time just fine, (Insert monkey, pull handle).
After that, UI doesn't even open. This was tested for all the xenobio disposals.
