### ISSUE TITLE
Hidden interior button for the external access in sec maints

### ISSUE THREAD

**Issue by KrossarnTom** [ParadiseSS13/Paradise#16492]
**Issue Description**:
Hidden interior access button for the external access in sec maints.
![Skärmbild 2021-08-06 184342](https://user-images.githubusercontent.com/72948218/128544729-1313d711-8779-4596-b389-2e86986229d1.png)
![Skärmbild 2021-08-06 184604](https://user-images.githubusercontent.com/72948218/128544769-449d0ac0-c2d5-429b-8563-a9fc2474fb82.png)

**What did you expect to happen**: 
For the interior button to be visable.

**What happened instead**:
The interior button is shrouded/FoW/unseen. Although, it can be used if the player knows the exact location of the button.

**Why is this bad/What are the consequences**:
Players might have a hard time using this external access.

**Steps to reproduce the problem**:
Start game.

**When did the problem start happening**:
Been like this for as long as i can remember.

**Extra information**:
Maybe it can be moved to the Reinforced wall left of its current location.

**Comment by S34NW** [comment]
fixed
