### ISSUE TITLE
The camera console in arrivals on metastaion doesn't display any cameras

### ISSUE THREAD

**Issue by GuyWithoutPie** [ParadiseSS13/Paradise#16512]
**Issue Description**:

**What did you expect to happen**: 

**What happened instead**:

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

**When did the problem start happening**:

**Extra information**:

**Comment by E-MonaRhg** [comment]
There's a megathread for issues related to metastation: https://github.com/ParadiseSS13/Paradise/issues/13950

**Comment by LightFire53** [comment]
This will be addressed in #16394

**Comment by matttheficus** [comment]
No information
