### ISSUE TITLE
Delta issues megathread 2021-08-10

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#16515]
Post comments of delta issues

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/128944380-b2f7aee1-07f7-4bab-9dd8-e35be092b2b4.png)
Still relevant

**Comment by S34NW** [comment]
> Additionally, the atmospherics supermatter still needs a monitoring console.
> 
> And, as stated in the last delta thread, the radiaton collectors need to be a tile closer to the supermatter crystal on either side.

These were fixed in yesterdays issue fix sweep

**Comment by AknightSS13** [comment]
I don't know if it was told before and sorry if it was but the pipes leading to sec are wrongly placed
![pipes](https://user-images.githubusercontent.com/87449601/129103382-76c3d9a3-9314-4a5e-ab7d-108a3b7c7b9f.PNG)

**Comment by AffectedArc07** [comment]
Cargo has no roundstart materials

**Comment by Sikroth** [comment]
The Psych Office Maintenance door is public access (could enter psych office as assistant from maint).

**Comment by AknightSS13** [comment]
tried as a drone to mail tag and in engineering and library and medbay  and i end up everytime in magistrate office 

As for kitchen and bar and science  i end up in cargo each time

And security leads to security when mail tagged

**Comment by jColbor** [comment]
There's no chemistry heater in SciChem by default

**Comment by AffectedArc07** [comment]
Floors in library are reskinned plasteel
![image](https://user-images.githubusercontent.com/25063394/129106041-23c406e7-781a-49bb-8bbe-ae11be475407.png)

**Comment by AknightSS13** [comment]
as a maint drone i couldn't go under the wooden tables in the captain room and teleporter

**Comment by Sirryan2002** [comment]
barkeep's backroom is missing the bottler unit

![Capture](https://user-images.githubusercontent.com/80364400/129407945-9d2c681e-a4d2-4690-a7f0-b7756ed91c3f.PNG)

**Comment by CrispyChipFox** [comment]
Hey I have a problem as Surgeon to open medbay chemist windor to get to fridge. It appears Medical doctors have the same issue. CMO and cyborgs don't have this problem.

**Comment by TORE01** [comment]
Psych office APC is wired but not connected to the powernet. Wire ends after the airlock

**Comment by Leanfrog** [comment]
The external airlock on the AI sat is not connected to a power grid and the sat also lacks a camera on the southern side

**Comment by matttheficus** [comment]
![image](https://user-images.githubusercontent.com/57759731/129623461-4763e15d-85c3-48cc-9049-606c55ab1188.png)
![image](https://user-images.githubusercontent.com/57759731/129623545-d9535b9b-ced4-441e-82d6-449ee0ffdb30.png)

The fax machine in the IAA's Office is noted as the Magistrate's Office in the Fax Panel instead of the IAA's Office

**Comment by warriorstar-orion** [comment]
The camera labelled "Research Toxins Secure Room" doesn't appear to be showing the right part of the station.
![-16_05_46](https://user-images.githubusercontent.com/59303604/129624144-50a1fd8f-6072-42f3-a486-39632bc58895.png)

**Comment by warriorstar-orion** [comment]
I believe this is tool storage but the airlocks are not labelled as such.

![Greenshot-15_31_46](https://user-images.githubusercontent.com/59303604/129624241-d4ebe2cb-619f-4824-8e07-7a70dd12b287.png)

**Comment by AknightSS13** [comment]
this apc was not connected to the grid
![Capture](https://user-images.githubusercontent.com/87449601/129624421-3500e790-d7f8-4814-b151-50b304e3325b.PNG)

**Comment by warriorstar-orion** [comment]
The windoor to this small area isn't labelled, so I don't know what it's called, but the NTR, and possibly other command, don't have access, despite having the ability and need to swipe the keycard auth device inside it.
![Greenshot-16_00_52](https://user-images.githubusercontent.com/59303604/129624621-15d5c9cb-3eb7-4b60-9bcc-e9564aa20140.png)

**Comment by warriorstar-orion** [comment]
This door leading to the courtroom is labelled as the Magistrate's office, despite their office being, I assume, just the lower portion of the courtroom behind the desk.
![Greenshot-15_34_31](https://user-images.githubusercontent.com/59303604/129625256-8f0791b9-424d-4b21-a321-9d6fcc63ef55.png)

**Comment by warriorstar-orion** [comment]
One minor design note, there are very few APCs in the primary hallway and no chargers in the bathrooms. I don't know if this was an intentional choice but it makes it difficult for IPCs to recharge. If the idea is that organics can only eat at the kitchen, so IPCs should have less places to do so as well, that's fine. I just though I'd point it out.

**Comment by AknightSS13** [comment]
Gateway scrubber pipe intersection is just 2 straight scrubbers pipe when it could be replaced with a 4 way scrubber manifold
![pipes](https://user-images.githubusercontent.com/87449601/129625966-5e80eb7a-7b9a-4b11-8099-e322b2aba784.PNG)

**Comment by KrossarnTom** [comment]
Normal officers don't have access to the lower windoor to the armory. 
![Skärmbild 2021-08-13 214335](https://user-images.githubusercontent.com/72948218/129644022-9c59fecd-06ba-46c0-b7d6-698015154093.png)

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/132546090-1c44657a-7e43-4eb6-9193-0535b14e98ce.png)
This button does nothing

**Comment by meow20** [comment]
![disposalsskrek](https://user-images.githubusercontent.com/62257265/132555542-9330f78f-4a5b-425f-a19d-61b47227f694.png)
turns out all or most disposals lead to bartenders backroom.

and

![skrekconveyors](https://user-images.githubusercontent.com/62257265/132555595-a8421a7e-8107-45bb-afd0-534508a8cee1.png)

the last two conveyors face wrong direction

**Comment by Denthamos** [comment]
Pun pun the barkeeps pet spawns in the kitchen and not in the bartenders area where they belong.

**Comment by Henr988** [comment]
> Post comments of delta issues

Toxins mass driver works, but the shutter doesn't open.
![image](https://user-images.githubusercontent.com/90366770/132613847-c26b5a3a-79bb-4d10-aaae-2699f44b3bc4.png)

Toxins burn chamber's space vent doesn't open.
![image](https://user-images.githubusercontent.com/90366770/132613890-c3786d74-7241-4c04-9b9c-b607d507139a.png)

**Comment by Herder05** [comment]
the top middle field gen in containment is a broke didn't get a screenshot but it wont turn on

**Comment by Onyxarias** [comment]
The two buttons meant for the Security podbay doors instead control the main podbay doors.

![image](https://user-images.githubusercontent.com/70349271/132616148-98b2f176-f3f1-4b80-9f86-754a404b5c82.png)

**Comment by BearTrap2135** [comment]
Found another piping funny in Dorms. not super important in terms of issues but its there. 
![piping funny](https://user-images.githubusercontent.com/86756575/132616678-e0a1232c-0533-4405-94bc-b1505733a853.png)

**Comment by VynalDerp** [comment]
Not a bug but IDK where else to leave this.

Medbay really needs space cleaner and/or soap. Surgery rooms have none and it is basically playing a game of Infection Roulette, where if you get bad RNG the patient dies. Only one cleaner for the entirety of the Medbay, which is leagues larger than Box station's.
The airlock leading to Virology is labeled as a Maintenance airlock, so some people got confused looking for Viro.
And finally, there is no direct connection between the Medbay area and the Morgue, the only way is through a small maintenance room. While cool, walking through maints to deliver a body to coroner from Cloning is a bit dangerous. Genetics has a connection, but general Doctors do not have access.

**Comment by RobertRoberts2020** [comment]
A missing tile at the magistrate office airlock
![image](https://user-images.githubusercontent.com/38957322/132972857-e0cb3036-974f-46ef-b164-30471e82ceec.png)

**Comment by VynalDerp** [comment]
Pods attempting to enter the escape shuttle via the airlock are blocked by a portion of Virology. These four tiles are the culprit.
![viro](https://user-images.githubusercontent.com/49999671/132978052-8980bbca-1145-432e-9159-206bad2eaa50.png)

**Comment by KrossarnTom** [comment]
![deltaissue](https://user-images.githubusercontent.com/72948218/133909708-102d9d2e-3a88-4b39-bdbe-36f93b16e85b.png)
Two atmospheric alert computers on top of eachother on the bridge.

**Comment by KrossarnTom** [comment]
![Delta issue](https://user-images.githubusercontent.com/72948218/133909802-cfb02dd1-e41c-4e74-886f-f074e2d01076.png)
HoS got a Long range fax machine.

**Comment by PacifistDalek** [comment]
Solars eat up more wire than they do on box to build, and have less wire coils stashed out on the solars themselves, so more wires should be added.

Also, airlocks to the solars have floor tiles (just inside the airlock section!) which makes it a touch annoying to wire the solars through the airlock

**Comment by LightFire53** [comment]
Fresh batch of fixes addressing stuff from september 8th - 19th: #16740

**Comment by Bormac** [comment]
I found two issues on Kerebros last time I played.
Medchems public facing fridge is not actually public, its medical locked so it defeats the purpose of it being public facing.

The other is the security checkpoint at security's desk is cursed. has double windoors on the same side, you can throw stuff on the desk from the public side but you cant take it off.  [https://cdn.discordapp.com/attachments/134493088218349578/889591920110759986/Cursed_Desk_Kerebros.jpg](url)

**Comment by thanatossage** [comment]
medbay has no wall mounted charger for the defibs.

**Comment by LightFire53** [comment]
To do: Bridge and engineering need slightly bigger power cells round start
Janitor needs space cleaner refill
HoP clothing closet

**Comment by Contrabang** [comment]
Majority of the station lacks newscasters.
 Newscasters in the bridge and AI should be able to set people to wanted and censor news.
 Command personnel offices lack clothes; jumpsuits, alternate uniforms, jumpskirts, etc.

**Comment by lordmavis** [comment]
No American Flag bedsheet for Americium.
I even sent a fax to CC about this and got rejected... America is sol gov... not syndicate....

**Comment by Contrabang** [comment]
Also, why is this called "Captains seat (sic)" when all of command has access? Perhaps there's a more fitting title like "Bridge Communications"?

![image](https://user-images.githubusercontent.com/91113370/134121870-6e067beb-f930-46cf-b1c2-5c51d681daf1.png)

**Comment by Contrabang** [comment]
Whole station is also missing holopads, only a few on the bridge and that's about it.

**Comment by thanatossage** [comment]
no spare voxygen or plasma tanks in medical

**Comment by AffectedArc07** [comment]
@Contrabang captain is the only person who can use most of the functions on the console, and its also the person who sits the 99.9% of the time, so I would say the naming for that is fine.

**Comment by SweetBlueSylveon** [comment]
The only gas pipe that comes to the SM engine is a nitrogen pipe as opposed to the "loop to engine" pipe. The SM also only has 3 filters as opposed to four.

**Comment by Henr988** [comment]
https://media.discordapp.net/attachments/890057325304496189/890067023361626163/unknown.png?width=632&height=494

full plasma tile windows doesn't protect from toxins mixing atmos

**Comment by LightFire53** [comment]
> medbay has no wall mounted charger for the defibs.

Medbay has 2
![image](https://user-images.githubusercontent.com/16112919/134446844-81554468-7699-4879-a5e0-e1b3a689c69a.png)


> Majority of the station lacks newscasters.
> Command personnel offices lack clothes; jumpsuits, alternate uniforms, jumpskirts, etc.

Lots of newscasters already, though tossing a few more in. Jumpsuit lockers are already the exact same as cyberiad, could be a result of clothing vendors being a thing

> Whole station is also missing holopads, only a few on the bridge and that's about it.

Patently untrue, there are lots around the station, though I have added more around to public areas.

> Medchems public facing fridge is not actually public, its medical locked so it defeats the purpose of it being public facing.

This is already the exact same fridge as what is on cyberiad

> https://media.discordapp.net/attachments/890057325304496189/890067023361626163/unknown.png?width=632&height=494
> 
> full plasma tile windows doesn't protect from toxins mixing atmos

Pretty sure it was stated somewhere this is a code issue, not a map issue? Think @S34NW determined that

Otherwise, all non-SM/Engine related fixes posted here since my last comment with fixes mentioned are repaired in #16776

**Comment by CenkTheRaptor** [comment]
cryodorms has no vents, causing people to die from o2 loss

**Comment by Sikroth** [comment]
From playing a doctor round recently:

Medbay could *really* use having more equipment, to the level the main Box/Cyberiad map has. I am talking sterile masks, space cleaner bottles, medical huds, defibs. I can't really list everything off the top of my head, but it feels like despite being a large map it is severely lacking in those. I'd just take a look at the Cyberiad map and try to match the amounts.

For instance:

For space cleaners in Cyberiad, there's 1 in the reception desk, 1 in chemistry, 1 in each operating backroom, 1 in the cryotubes room, in cloning, in the virology hallway and inside virology itself, and 1 in genetics. And I probably forgot some. 9.

In contrast, Delta has 1 in chemistry, 1 in the sleeepers room, 1 in equipment room, 1 in the surgery hallway, and I think that might be it. Total of 4, less than half for a considerably larger (and more prone to blood trails) medbay.


There is also literally one box of sterile masks, and as far as I know also 1 box of gloves (not counting the ones in lockers). For comparison, Cyberiad has both gloves and masks in both OR backrooms, in storage room and in the reception desk.

**Comment by KrossarnTom** [comment]
![Skärmbild 2021-09-24 231624](https://user-images.githubusercontent.com/72948218/134740410-3c4317e9-ee26-4c5b-a913-7c586b538c8d.png)
Random Computer Board, that wont build anything, in this maints room west of arrivals.

**Comment by KrossarnTom** [comment]
![Skärmbild 2021-09-24 233422](https://user-images.githubusercontent.com/72948218/134741620-413a4aa7-3795-4c65-bda1-ae20de25db90.png)
Civilians got access, from maints, to Clown and Mimes room.

**Comment by LightFire53** [comment]
> ![Skärmbild 2021-09-24 231624](https://user-images.githubusercontent.com/72948218/134740410-3c4317e9-ee26-4c5b-a913-7c586b538c8d.png)
> Random Computer Board, that wont build anything, in this maints room west of arrivals.

Pretty sure you can use a screwdriver on this to create different types of computers

**Comment by nukularpower** [comment]
Just a note that per other implementations, the walls for the perma cells on both Meta and Delta should be shocked windows, not actual walls

**Comment by KrossarnTom** [comment]
> > ![Skärmbild 2021-09-24 231624](https://user-images.githubusercontent.com/72948218/134740410-3c4317e9-ee26-4c5b-a913-7c586b538c8d.png)
> > Random Computer Board, that wont build anything, in this maints room west of arrivals.
> 
> Pretty sure you can use a screwdriver on this to create different types of computers

Tried it now. (also multitool) Did nothing. I guess it is for an old computer that got removed? Maybe?

**Comment by LightFire53** [comment]
> Just a note that per other implementations, the walls for the perma cells on both Meta and Delta should be shocked windows, not actual walls

Not quite sure what we are talking about here. You mean the little rooms with beds?
![image](https://user-images.githubusercontent.com/16112919/134751446-a2a6bc5e-25cf-475d-b91c-892501c19ce0.png)
Because this is what Box has: 
![image](https://user-images.githubusercontent.com/16112919/134751464-1766378a-e200-433d-a8cc-352e88e0bef6.png)

**Comment by nukularpower** [comment]
> > Just a note that per other implementations, the walls for the perma cells on both Meta and Delta should be shocked windows, not actual walls
> 
> Not quite sure what we are talking about here. You mean the little rooms with beds?

Yes, in your image if you go to the left, the actual perma windows are glass.  On box it doesnt matter because of the layout but on the new maps the cells *are* the perma walls and should also be glass (imo) - to give people a chance to escape, at the end of the day.

If it counts for anything, thats how it is on the RU para server, though I doubt it would matter.  Just pointing it out, anyways

**Comment by VynalDerp** [comment]
Not sure if this has been posted here already, but the EVA suit storage unit in the RD's office has a normal EVA suit instead of the RD's unique hardsuit. Not sure if intended or an oversight.

**Comment by Christasmurf** [comment]
Looks like I found two mislabelled cameras on delta

![](https://cdn.discordapp.com/attachments/410782260887945226/891620558918275112/unknown.png)

![](https://cdn.discordapp.com/attachments/410782260887945226/891620966910812160/unknown.png)

**Comment by Christasmurf** [comment]
Oh also another note while I'm here: The HoP office fax machine is only a normal one, not long range. If this is intentional, then there's an issue with box station.

**Comment by LightFire53** [comment]
> > > Just a note that per other implementations, the walls for the perma cells on both Meta and Delta should be shocked windows, not actual walls
> > 
> > 
> > Not quite sure what we are talking about here. You mean the little rooms with beds?
> 
> Yes, in your Box image if you go to the left, the actual perma windows are glass. On Cyberiad it doesnt matter because of the layout but on the new maps the cells _are_ the sec-facing perma walls and should also be glass (imo) - to give people a chance to escape, at the end of the day.
> 
> If it counts for anything, thats how it is on the RU para server, though I doubt it would matter. Just pointing it out, anyways

![image](https://user-images.githubusercontent.com/16112919/134816756-76d015be-f06b-4855-b16f-d016904a8d59.png)

Does this not count as an opportunity to escape?

**Comment by KrossarnTom** [comment]
<img width="375" alt="CF3C3E6B-C7DF-4629-AB0C-457FDBD6CADC" src="https://user-images.githubusercontent.com/72948218/134886283-5c9a518f-a859-47d4-aa3a-6669b6862330.png">
Mechanics. Nice plus sign :)

**Comment by TopTheWorst** [comment]
There is a lack of megaphones for command

Also, these bridge blastdoor buttons are all over the place
![image](https://user-images.githubusercontent.com/90973675/134963689-89646dec-73b9-4071-873e-c422a97a88bd.png)

**Comment by Sikroth** [comment]
A holopad on top of a scrubber, in front of bridge. Looks ugly and blocks the scrubber visually to see welding.
![image](https://user-images.githubusercontent.com/7857084/135662174-d0ea4a09-7e3e-4fc2-b9fd-89179dbe0e32.png)

I feel like there's more of these overlaps around the map but I haven't checked.

**Comment by warriorstar-orion** [comment]
There appears to be no Crittercare on Delta.

There also appears to be no guest pass terminal in Cargo, but I may have missed it.

**Comment by Christasmurf** [comment]
Normal paperbin in the NT Rep office, not the one with the headers. 0/10 literally unplayable map

**Comment by AffectedArc07** [comment]
Botany has no disk compartmentalized

**Comment by AllStickyGithub** [comment]
These airlocks are mislabeled.
![Screenshot 2021-10-12 123918](https://user-images.githubusercontent.com/62549552/136941632-6892d2e2-0f97-4102-b8aa-435b6cf6ef68.png)

These airlock controls are not linked to the vents or the airlocks.
![Screenshot 2021-10-12 124348](https://user-images.githubusercontent.com/62549552/136941682-6626682b-13ef-4e9f-888d-2dd9892b2c89.png)

**Comment by Polluted-Heart-Maker** [comment]
Got a glitch for ya. The Engineering SMES APC is never able to receive external power even though the wiring is correctly set up. Checked multiple times as a drone on Delta but it seems every shift it's the same, so I am betting it's a bug and not something someone did.
![Screenshot_126](https://user-images.githubusercontent.com/84251057/139952018-b0edf7b1-eb9d-44d6-b6cc-b0be86ab569f.png)
![Screenshot_127](https://user-images.githubusercontent.com/84251057/139952036-cfc9a97a-a8d9-4d63-98c0-b19c1cadb0df.png)

**Comment by LightFire53** [comment]
> Got a glitch for ya. The Engineering SMES APC is never able to receive external power even though the wiring is correctly set up. Checked multiple times as a drone on Delta but it seems every shift it's the same, so I am betting it's a bug and not something someone did. ![Screenshot_126](https://user-images.githubusercontent.com/84251057/139952018-b0edf7b1-eb9d-44d6-b6cc-b0be86ab569f.png) ![Screenshot_127](https://user-images.githubusercontent.com/84251057/139952036-cfc9a97a-a8d9-4d63-98c0-b19c1cadb0df.png)

![image](https://user-images.githubusercontent.com/16112919/140010349-acc422f5-90f2-4ea9-b8d7-aaa5173b0e02.png)

Yeah, on paper it all seems to be attached to the grid. Not only that, the APC is just a standard APC which we use in many other places, so I have no idea? May have something to do with the area itself?

**Comment by TORE01** [comment]
This is a nitpick, which means we are fairly close to perfection. The departures/escape external airlocks are both called "Arrivals external airlock".

**Comment by TORE01** [comment]
Hello. Putting this here since its not a problem on cyberiad. I played contractor today and I could not call extraction on my kidnapping objective in Research & Development. The circle indicated that I was where I was supposed to be, but I could not press the extraction button. I did not get a screenshot because I was hunted by the time I prayed for help.

**Comment by meow20** [comment]
![image](https://user-images.githubusercontent.com/62257265/146542623-d69377a2-28ce-4395-96f7-ef2c84e9538d.png)
this airlock near grav gen doesn't react to the button below it or to the airlock controller nearby if you were to try to force it open.

**Comment by Christasmurf** [comment]
![image](https://user-images.githubusercontent.com/25437893/151270227-6b1aa6bb-9dcf-495f-bf4a-00b486d132c9.png)
Detective's office RC machine is called "unknown requests console"

**Comment by Christasmurf** [comment]
![image](https://user-images.githubusercontent.com/25437893/151272052-9da80052-d1ef-470e-a375-81c7709a0775.png)
Not sure why the telecomms chamber is called AI upload

**Comment by AllStickyGithub** [comment]
As far as I can tell there are no guest pass terminals anywhere.

**Comment by moxian** [comment]
![20220511-085617-StrongDMM](https://user-images.githubusercontent.com/7831163/167811279-febbab7b-9301-40b3-8761-56042b0d2286.png)
These two maint areas are the same areas, and powered by a single APC. Which is nigh-impossible to deduce without looking at the map source.

**Comment by Vulkoras** [comment]
Just a very minor thing which I'm not even certain is an issue or if is just map specific, but currently Delta (along with Box) doesn't have the Janitor's pet lizard Wags-His-Tail, which is present in the custodial closet on both current versions of Meta (I'm not sure if they were ported with meta, or were present on the others then lost at some point though (Not mentioned with the other pets on the wiki, and their name is carried over from TG/based on their verbs-the-noun lizardperson naming scheme as far as I can tell)).

**Comment by LightFire53** [comment]
> Just a very minor thing which I'm not even certain is an issue or if is just map specific, but currently Delta (along with Box) doesn't have the Janitor's pet lizard Wags-His-Tail, which is present in the custodial closet on both current versions of Meta (I'm not sure if they were ported with meta, or were present on the others then lost at some point though (Not mentioned with the other pets on the wiki, and their name is carried over from TG/based on their verbs-the-noun lizardperson naming scheme as far as I can tell)).

Probably just part of the meta port, since they weren't in there before either iirc

**Comment by SteelSlayer** [comment]
There are two misplaced areas labeled "sleep room" in a hallway outside the teleporter:

![image](https://user-images.githubusercontent.com/42044220/175238506-6146c715-edd4-41ff-811e-cc87fcf2ccc4.png)

**Comment by AffectedArc07** [comment]
I think we can sunset this now and just have it pile into regular issues
