### ISSUE TITLE
New *spin command breaks mobs with existing spin behavior

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#16513]
**Issue Description**:
The `spin` command introduced in #15917 changed the behavior of the existing `/mob/living/simple_animal/pet/dog/chasetail` command, causing it to graphically glitch out.

**What did you expect to happen**: 
The mob should begin and end each spin animation in sequence.

**What happened instead**:
It appears that the spin animation is restarted on every command, and animation frames are interleaved every time the command is invoked. This causes the spin to be choppy and not look appropriate.

**Why is this bad/What are the consequences**:
This is a graphical anomaly that is distracting because it has the ability to animate faster than, I think, anything else in the game, which draws attention to it.

**Steps to reproduce the problem**:
1. Become dog
2. Speen

**When did the problem start happening**:
I believe this is a knock-on effect from #15917 but this is a guess.

**Extra information**:

https://user-images.githubusercontent.com/59303604/128937584-4883b5f0-571f-4bdf-a32b-6e9d991bbfec.mp4

**Comment by PacifistDalek** [comment]
Olympic Speed Spinner Ian

**Comment by warriorstar-orion** [comment]
Does closed here mean fixed, code freeze, or too low priority?
