### ISSUE TITLE
Cargo shuttle console TGUI runtime

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#16535]
**Issue Description**:

The console bluescreened when I tried to look at it as a ghost, but once I tried again it seemed fine.
![Screenshot 2021-08-13 124108](https://user-images.githubusercontent.com/37041561/129342293-817781dc-80f0-4403-9209-fed19dde3812.jpg)
I am not quite sure what the cause to it was, but the console was emagged.

**What did you expect to happen**: 

For it to work without showing that screen.

**What happened instead**:

I was met with the bluescreen of death.

**Why is this bad/What are the consequences**:

bluescreen of death = bad

**Steps to reproduce the problem**:

I am not quite sure what the cause to it was so I can't quite tell you exact steps.
1. Find a cargo console.
2. Emag it (Not certain if necessary to replicate)
3. Become a ghost
4. Look at the console.

**When did the problem start happening**:

Only happened to me today (2021-08-13)

**Extra information**:

**Comment by moxian** [comment]
Judging by the stacktrace, it's probably the outer (I'm 87% sure) filter in 
https://github.com/ParadiseSS13/Paradise/blob/c445b4d396985bd70d3291fd10a2b6153415c76f/tgui/packages/tgui/interfaces/CargoConsole.js#L155-L160

The dm side looks sane, everything seems to be well defined...
https://github.com/ParadiseSS13/Paradise/blob/c445b4d396985bd70d3291fd10a2b6153415c76f/code/modules/shuttle/supply.dm#L459-L466

**Comment by Sirryan2002** [comment]
Would like to see someone heavily test the cargo console and attempt to break the TGUI in order to confirm that this is still an issue
