### ISSUE TITLE
All one-way access airlocks now start without the one-way access

### ISSUE THREAD

**Issue by Peakwastaken** [ParadiseSS13/Paradise#16537]
**Issue Description**:

All the one-way access airlocks (medbay entrances, cloning, brig cells entrance) aren't properly set at shift start, and can't be opened from the inside as they should.

**What did you expect to happen**: 

Bump into door, door open

**What happened instead**:

wub wub wub *blinks red

**Why is this bad/What are the consequences**:
Seems to be a bug brought by a recent PR, an unintentional change.

**Steps to reproduce the problem**:
Bump into door without medbay/sec access from inside, be sad.

**When did the problem start happening**:

First noticed on the 12/08/2021

**Extra information**:
 the airlock boards simply weren't set-up right, they were otherwise fully functional.

**Comment by SabreML** [comment]
My fault, from #16501. Fixing now.
