### ISSUE TITLE
Hybrid Turret fits in Shoulder Holster

### ISSUE THREAD

**Issue by yeetethdeleteth** [ParadiseSS13/Paradise#16542]
**Issue Description**:

Hybrid Turret Guns are big, bulky, and require two hands to fire, yet you can put them in a shoulder holster.

**What did you expect to happen**: 

The super big gun should not fit in a shoulder holster,

**What happened instead**:

They go into the shoulder holster.

**Why is this bad/What are the consequences**:

It feels wrong that a silenced stechkin or security autorifle do not fit but the super big, two-handed gun can.

**Steps to reproduce the problem**:

Get a hybrid turret gun, get a shoulder holster from botany, holster the gun.

**When did the problem start happening**:

I found out about a month ago but it's probably been this way for awhile.

**Comment by chafla** [comment]
Already on it, #16529 fixes this.
