### ISSUE TITLE
Boo button/arrow button overlap build mode

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#16544]
**Issue Description**:
The boo button and arrow to hide buttons in the top left of the visual screen overlap on top of admin build mode preventing you from pressing them.

**What did you expect to happen**: 
Build mode should overlap on top of boo and not the other way around.

**What happened instead**:
Cannot change build mode functions due to boo.

**Why is this bad/What are the consequences**:
Harder to use admin build mode.

**Steps to reproduce the problem**:
Have admin rank and be a ghost, enable build mode.  Cannot press the build mode function and ? button due to boo buttons.

**When did the problem start happening**:
When the boo and arrow button were added to ghosts.

**Extra information**:

**Comment by LightFire53** [comment]
This is not always the case, but I do find it occurs about 50% of the time, or if you enter and leave build mode multiple times
