### ISSUE TITLE
Cyborg laser gun does not re-enable itself when cyborg is powered with charged slime core

### ISSUE THREAD

**Issue by thaulos-bolsens** [ParadiseSS13/Paradise#16559]
**Issue Description**:
Disabled cyborg laser gun does not re-enables when cyborg is powered by a charged slime core.

**What did you expect to happen**: 
The cyborg laser gun gets disabled because there is no power. It should re-enable itself if there is power again.

**What happened instead**:
Cyborg laser gun stays disabled until docking into a cyborg charging station.

**Why is this bad/What are the consequences**:
The whole point of charged slime cores is that it allows you autonomy in exchange for a smaller cell capacity. Having to go to recharge every time you use 10kw defeats the purpose.

**Steps to reproduce the problem**:
Be a security cyborg, with charged slime core and with safety override. Fire until cell charge reaches zero.

**When did the problem start happening**:
This has always happened as far as I know.

A previous fix made it so that cyborg charging stations re-enable the laser gun: https://github.com/ParadiseSS13/Paradise/issues/16398

**Extra information**:
That's pretty much it.

**Comment by SteelSlayer** [comment]
I just want to mention that this was not a result of #13527. As far as I can tell slime cores never had this feature, so technically this is a feature request. However it does make sense to have this change.

**Comment by matttheficus** [comment]
Stale feature request.
