### ISSUE TITLE
No traitors appear at end round

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#1655]
I think we have all seen this, but alot lately no traitors (save for revenents) will show up on the end round score screens. Seems to be for traitors, I think vampires are working right. Also the vox hiest bug is still there..Again, blame bluespace

**Comment by Alex6511** [comment]
I believe this also occurs for the changeling gamemode

**Comment by TheDZD** [comment]
I've seen this happen on AutoTraitor rounds fairly often.

**Comment by Robertha89** [comment]
A year back adding a traitor via game panel fixed this for auto-traitor.

**Comment by Alex6511** [comment]
To clarify, this affects all game modes involving traitors, as they do not appear in Changeling+Traitor either.
