### ISSUE TITLE
The Security camera consoles network issue

### ISSUE THREAD

**Issue by KrossarnTom** [ParadiseSS13/Paradise#16568]
**Issue Description**:
The security camera console, when rebuild, wont show any cameras. This is probably due to that every single security camera console on the map have had their network list value edited to show these networks.
![Skärmbild 2021-08-19 092143](https://user-images.githubusercontent.com/72948218/130025423-5dfe20ac-d8f4-4fac-937e-0f3986b635a4.png)

 And so when rebuilding a console it use the default dm that have the network list value empty.
![Skärmbild 2021-08-19 092757](https://user-images.githubusercontent.com/72948218/130025750-68474dc1-0956-43ab-a099-29fb3fcfe449.png)

Adding "SS13","Research Outpost","Mining Outpost" to the list the console have connection to the networks when they're rebuild.

**What did you expect to happen**: 
To be able to move the consoles.

**What happened instead**:
The console will be useless after reconstruction.

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

**When did the problem start happening**:

**Extra information**:

**Comment by KrossarnTom** [comment]
Im not sure if this is intentional, that their values are edited on the map and the default dm is blank.
But i will ping @S34NW once more as they're fixing the rest of the map.

**Comment by S34NW** [comment]
It's odd the SS13 network is not added by default in the code, as that's the default cam network we assign to all station cameras.
Seems like something to be fixed by adding ss13 to the network list variable for the cam console computer object

**Comment by KrossarnTom** [comment]
Same issue were applied almost a year ago. #14625
