### ISSUE TITLE
If you spawn with an amputated left arm, you can still hold things in your left hand

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1656]
Did not test other arms, have also had this occur with limbs amputated in explosions.

**Comment by Robertha89** [comment]
You can still use your pda, check your backpack and a use your bikehorn when spawning without arms as clown.

**Comment by Spacemanspark** [comment]
This is because you still have your hand.
This also occurs if your arm is cut off.

**Comment by Alex6511** [comment]
@Robertha89 I have no idea what you're talking about, I know you can still use your PDA.
@Spacemanspark https://gyazo.com/83518a207c566c8ed2b854d8e3501478 it says my hand is missing, too. Regardless, its a bug, you shouldn't have a hand if your arm is missing.

**Comment by KasparoVy** [comment]
@Alex6511 Unless you're Rayman.

**Comment by Dinarzad** [comment]
Can back this up. I lost my left arm and hand in a gibtonite explosion an was able to pick up my pickaxe with my new telekinetic powers emitting from my stump of a left arm.

Wentthe rest of the match without issue actually...

**Comment by KasparoVy** [comment]
That's hardcore

Make a character named no-arms Ned and just go about honking people with your telekinetically controlled bike-horn
