### ISSUE TITLE
Lavaland Anomalous Crystal Clown ability is super buggy.

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#16572]
**Issue Description**:
The Anomalous Crystal on Lavaland has the ability to turn everyone around it into clowns. This entails that person getting the roundstart clown loadout including the Comic/Clumsy gene and the sad trombone implant.

This also spawns in that players custom roundstart loadout, so if they had any clothes/glasses/fluff items picked out they spawn with those as well. It will delete any mindshield as well as adrenal implants that player had. I have not tested it but one can assume it would also delete other ones such as death implant, tracker, storage, and other implants.

In addition, since there does not seem to be a limit of the crystal, it has massive grief potential with it being used on a previous round to turn most of command and the ERT into clowns.

**Comment by chafla** [comment]
As a Med ERT who got clowned, it did delete my death tracker, but curiously left my surgical toolset implant intact.

**Comment by Sirryan2002** [comment]
Fixed in PR, this was removed
