### ISSUE TITLE
Contractors Occasionally Lose the Ability to Call Extraction

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#16585]
**What is the problem?**
As a contractor, despite cuffing and dragging your target to the correct room, your call extraction button may stay grey'd out permanently, preventing you from contracting anyone in the future, even if you abort and take a new contract.

**What did you expect to happen**: 
When you are in the correctly chosen room next to your target, for the Call Extraction button to turn green and call the flare when pressed.

**What happened instead**:
The button stays grey'd out. This continues for all future contracts, despite the location and targets being correct and adjacent.

**Why is this bad/What are the consequences**:
Completely ends the contractors ability to do their job, also wasting their TC if it happens early.

**Steps to reproduce the problem**:
I do not know what caused it. Round details listed in Extra Information.

**When did the problem start happening**:
About 90 minutes into the round, after two successful contractings, the third one starting the issue.

**Extra information**:
I contracted two people 60 minutes into the round via cuffing, taping, and welding them into a normal locker, then opening the locker on top of the portal. Everything is normal up to this point. Both people were contracted within 5 minutes of each other. (IAA contracted in engineer storage. My next contract happened to be in the same room and was contracted in medbay.)

90 Minutes in, one of my contracts Cryo'd in perma, giving me a new contract, the Brig Phys, to take to the Construction Area.
With an emagged borg, we rushed the brig, and I took the brig phys into cargo, stuck them into an ID-locked cargo locker, and brought them into the area designated by the contractor PDA arrow.
Also I think in the chase I accidentally stuck some duct tape to the contractor PDA. I doubt it'd break just a single button but i'll mention it anyways.
Unfortunately standing next to the locker, with the Brig Phys both inside and outside of it, the Call Extraction button never turned green. After a bit of talking I let them go and abandoned the contract.

I went for a different contract ~15 minutes later, a cargo tech now promoted to QM, to be taken into Medical Treatment. Cuffed em, ID-locked them in a miner locker, brought them to medical treatment, couldnt extract.
Tried demoting them to cargo-tech so that their ID matched the contract, still couldnt extract in or outside the locker.
At that point I gave up.

**Comment by SabreML** [comment]
Should probably mention since it wasn't linked, this is getting looked into with #16586. As far as I'm aware nobody's figured out what exactly is causing it, but hopefully that PR will fix the issue.

**Comment by AffectedArc07** [comment]
Fixed in the PR linked above
