### ISSUE TITLE
invisible wand of slipping

### ISSUE THREAD

**Issue by Greenbean73** [ParadiseSS13/Paradise#16599]
**Issue Description**:

The wand of slipping becomes invisible if it runs out of charges

**What did you expect to happen**: 
The wand not becoming invisible

The wand isn't supposed to be invisible

**What happened instead**:
The wand becomes invisible

Was expecting the wand to stay normal, but it disappeared instead

**Why is this bad/What are the consequences**:
Makes it hard to know where the wand is, and it can still take up inventory spaces

It's possible to clog inventory spaces with invisible wands

**Steps to reproduce the problem**:

Step 1: Get a wand of slipping

Step 2: Fire the wand until it's out of banana peels

Step 3: Wand disappears

**When did the problem start happening**:
8/25/21

Not sure if it worked properly before, but it might have

**Extra information**:

**Comment by SteelSlayer** [comment]
Confirmed it does turn invisible. But also, where did you actually get a wand of slipping from?

**Comment by Greenbean73** [comment]
There's a wand of slipping in the clown sanctuary place on Lavaland. When I
found the bug, someone gave it to me. I found the place you actually get it
from during a later round (last night, in fact)
