### ISSUE TITLE
Saving Chat Logs Not Working

### ISSUE THREAD

**Issue by punkalope** [ParadiseSS13/Paradise#16590]
**Issue Description**:

The HTML chat log window doesn't open when I try to save one.

**What did you expect to happen**: 

I click "save chat log" and it opens Microsoft Edge.

**What happened instead**:

I click "save chat log" and nothing happens.

**Why is this bad/What are the consequences**:

Can't save chat logs.

**Steps to reproduce the problem**:

Open Paradise > Gear Icon > Save Chat Log.

**When did the problem start happening**:

18/08/2021

**Extra information**:

:[

**Comment by AffectedArc07** [comment]
The Microsoft edge window that opens has the chat log in does it not?

You then save from that window to disk, BYOND itself can't do direct file writes from your client iirc.

**Comment by Wojz** [comment]
> The Microsoft edge window that opens

The issue description is that the window doesn't open.

**Comment by punkalope** [comment]
> The issue description is that the window doesn't open.

Yeah yeah, exactly that. Super sorry if I wasn't clear enough.
Before the 18th it would open the Edge window like normal. After that, though, it just kind of...stopped?
I should have done this before, but here's a gif of it too. The other things in the dropdown work perfectly fine and open windows then they should, but the "saving chat log" button doesn't.
![07PzryQzjO](https://user-images.githubusercontent.com/88009266/130503892-56f5f75b-9798-4c1b-b1dd-901499855f11.gif)

**Comment by SabreML** [comment]
> Yeah yeah, exactly that. Super sorry if I wasn't clear enough.
> Before the 18th it would open the Edge window like normal. After that, though, it just kind of...stopped?
> I should have done this before, but here's a gif of it too. The other things in the dropdown work perfectly fine and open windows then they should, but the "saving chat log" button doesn't.

I had exactly the same issue personally as in this gif on the 15th, although I've not tried it since then. I had to manually select and copy everything in the chat window in order to save it.

**Comment by Contrabang** [comment]
This is an issue with BYOND failing to open IE. I think this could be worked around though using the ftp proc carefully

**Comment by AffectedArc07** [comment]
> This is an issue with BYOND failing to open IE. I think this could be worked around though using the ftp proc carefully

Don't believe so. The chat data is entirely client side so having the server invoke something probably won't change much.

**Comment by Contrabang** [comment]
Alright, my bad

**Comment by S34NW** [comment]
TGUIv4 should have maybe fixed this
