### ISSUE TITLE
wheelchair users cannot enter the gateway

### ISSUE THREAD

**Issue by 7erracotta** [ParadiseSS13/Paradise#16611]
I was playing as a character who uses a wheelchair and i wanted to be an explorer, but i ran into a huge issue. the gateway wouldnt let me through

**Comment by LightFire53** [comment]
1. Please make sure you use the issue template, as it helps provide more information
2. Gateway is ableist confirmed

**Comment by TORE01** [comment]
Maybe we need to add a ramp?

**Comment by Zephroze** [comment]
YEET
