### ISSUE TITLE
Pickpocket Gloves Code Duplicate

### ISSUE THREAD

**Issue by TheLinuxOS** [ParadiseSS13/Paradise#16633]
**Issue Description**:

**What did you expect to happen**: 
There to be only one set of the code

**What happened instead**:
There were 2 identical sets of the same code for pickpocket = 1

**Why is this bad/What are the consequences**:
Adds clutter to the code that doesnt need to be there

**Steps to reproduce the problem**:
Go to around line 400 of Paradise/code/modules/mob/living/carbon/human/inventory.dm, you will see that the code for pickpocket is listed twice

**When did the problem start happening**:
IDK I came to check yalls code so I could port the gloves and I saw the duplicate code

**Extra information**:
This doesnt really fit yalls normal bug format and im not sure if its intended but if you check line 400 of the code in the section I listed above you will see that the exact same block of code shows up twice which I find rather weird, it even has the exact same comments on the code. Potentially a mistake? Just figured yall would like to know
![Screenshot_117](https://user-images.githubusercontent.com/67720649/132079638-d57b4b9a-3b63-43cb-99e0-199bdd2dd832.png)

**Comment by SteelSlayer** [comment]
One proc is `stripPanelEquip`, on is `stripPanelUnequip`. These are different procs, both of which are needed. Unless you meant that the code inside each of the procs is the same and should be extracted as to not have duplicate code, then yeah you're right.

**Comment by TheLinuxOS** [comment]
Ah wait no you’re right I did miss that nevermind then
