### ISSUE TITLE
Engineering camera monitor consoles have misaligned screens

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16641]
**Issue Description**:
The screens for engi camera monitors are a pixel or two out of alignment.

**Why is this bad/What are the consequences**:
They look quite goofy.

**When did the problem start happening**:
https://github.com/ParadiseSS13/Paradise/pull/16564

**Extra information**:
![image](https://user-images.githubusercontent.com/12197162/132190124-802022f5-cfcd-4918-ba00-8d5a66b3dfe6.png)

**Comment by LightFire53** [comment]
@S34NW close issue pls
