### ISSUE TITLE
E.X.P.E.R.I-MENTOR and Console won't link

### ISSUE THREAD

**Issue by Kirbyroth** [ParadiseSS13/Paradise#16665]
**Issue Description**: E.X.P.E.R.I-MENTOR won't link to R&D Console and is unusable as a result

Console is to far or the walls block it from linking. 

**What did you expect to happen**: 

Round start should have linked with no issue

**What happened instead**:

Was unable to link E.X.P.E.R.I-MENTOR to R&D console

**Why is this bad/What are the consequences**:

E.X.P.E.R.I-MENTOR won't work without linking to console first 

**Steps to reproduce the problem**:

Round start go to E.X.P.E.R.I-MENTOR attempt to link and it wont link

**When did the problem start happening**:

Today during Delta test 9/8/2021

**Extra information**:

Fixed in game by moving the console in front of the E.X.P.E.R.I-MENTOR

**Comment by LightFire53** [comment]
I tried to see if this would be a minor map fix, however:
![Delta Exp](https://user-images.githubusercontent.com/16112919/132622521-3e810532-8656-442d-afc3-55c564f22cd2.png)

It worked in the green circle, but not in the red X's. As a result, this may be more code based than map based. However, I don't know the black magicks, so I can't obviously see if there is a "range" to the experimentor.

**Comment by Kirbyroth** [comment]
yea the green circle where it move it to as well.  Thinking it likely range issue wonder if other machines have range limit on them as why there always near the consoles🤔

**Comment by Dovixx** [comment]
Looking at the code of the experimentor. It seems that there is a range limit to how far the console can be and the max distance is 3 if I understoodbit correctly.

**Comment by lewcc** [comment]
This is no longer a bug on delta, though the range concern is still present in code. That being said, the main issue here was the mapping.
