### ISSUE TITLE
Diona Nymphies get stuck in Mean Borgo Jail when a Cyborg attempts to hug them.

### ISSUE THREAD

**Issue by Raydon1206** [ParadiseSS13/Paradise#16752]
**Issue Description**:
Nymphies getting stuck inside cyborgs.

**What did you expect to happen**: 
Cyborg to hug/pet the nymph.

**What happened instead**:
Cyborg picked up nymph, and had no way to drop them.

**Why is this bad/What are the consequences**:
Nymph gets sent to the shadowrealm, decontructing the cyborg does not help. Have not tried having the nymph resist yet.

**Steps to reproduce the problem**:
Aquire Diona Nymph
Have any cyborg with a hug module hug it
Inhale Plant

**When did the problem start happening**:
9/20/2021

**Extra information**:
As far as I know, the Diona is just.. deleted.

**Comment by Spacemanspark** [comment]
OK I'm not going to lie

I cackled reading this
