### ISSUE TITLE
Treadmill being ran on push ghosts away

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#16757]
**Issue Description**:

When a brigee is running on the treadmill, if a ghost stands on it, they're launched away like they were a physical mob

**What did you expect to happen**: 

Nothing

**What happened instead**:

I was launched like a corporeal being

**Why is this bad/What are the consequences**:

Physical world shouldnt interact with ghosts

**Steps to reproduce the problem**:

1. Have someone running on treadmill
2. Ghost stands on top of them

**When did the problem start happening**:

Not sure

**Extra information**:

Happened to me today, 21/09/2021, on the live server, on boxstation cell 3

**Comment by Spacemanspark** [comment]
Finally, a worthy tool against the evil ghosts of deadchat
