### ISSUE TITLE
Fliponium never stops flipping

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16767]
**Issue Description**:
Fliponium no longer wears off, you spin until you slip or lie down.

**What did you expect to happen**: 
For the spin to run out eventually when the chem runs out.

**What happened instead**:
Infinite spinny boys.

**Why is this bad/What are the consequences**:
It is _extremely_ LRP to see everyone running around spinning

**When did the problem start happening**:
Probably with 514 and the other animation bugs we have.

**Comment by Fox-McCloud** [comment]
This has always been the case.

You spin faster and faster the longer its in you, then, once it wears off, you still continue spinning, but at a much slower pace--it's literally how it's been designed.
