### ISSUE TITLE
If you are assigned antag and have no roles capable of antaging selected, as well as return to lobby if no roles are found, you can be assigned antag without spawning, which causes numerous bugs.

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1681]

**Comment by Taaketa** [comment]
This issue maybe more helpful with a shorter title and a better description. Best I can understand here is that...

If your job role isn't available and you don't have 'be assistant' enabled. You'll be sent back to lobby with antag objectives.

**Comment by TheDZD** [comment]
Sounds like the same issue as #1327.

**Comment by KasparoVy** [comment]
RIP lobby

tfw you got escape alone

**Comment by Alex6511** [comment]
Yeah it is, closed
