### ISSUE TITLE
IPCs come back to life after being rev drained while sleeping

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16813]
**Issue Description**:
Sometimes, IPCs will randomly stop being dead a few minutes after a rev has drained their soul.

**What did you expect to happen**: 
For them to stay dead unless revived

**What happened instead**:
They just got up and scared everyone who saw they were dead.

**Why is this bad/What are the consequences**:
People get labelled as clings when in reality it's just a strange bug.

**Comment by farie82** [comment]
Did they get hit by something or cause any other health update?
The rev just says `death()`. So IPCs will just revive once they get any sort of health update
