### ISSUE TITLE
Ash Drakes can do their "Lava Swoop" attack on a separate Z-level if they have not dropped aggro.

### ISSUE THREAD

**Issue by SweaterKittens** [ParadiseSS13/Paradise#16827]
**Issue Description**:
If an Ash Drake is aggro'd on you, it will perform the lava portion of it's Lava Swoop attack, even if you are on another Z-level.

**What did you expect to happen**: 
Jaunting to a separate Z-level would not allow an Ash Drake to perform attacks on you across Z-levels.

**What happened instead**:
If the Ash Drake rolls its Lava Swoop attack, it will perform the entirety of it sans the final landing, conjuring pools of lava beneath you on the station.

**Why is this bad/What are the consequences**:
If you have jaunted to the station, you will be stunned, meaning this attack will guaranteed kill you along with burning all of your equipment, meaning your round is over as a miner. You pay 750 points for a jaunter to get you out of trouble, and due to the random placement, is already dangerous on its own. It also does not make sense that a Drake hundreds of miles from the station can perform a swoop attack on you. Additionally, due to summoning a 3x3 pool of lava on any of the jaunt locations, this can do fairly substantial station damage, depending on positioning.

**Steps to reproduce the problem**:
While you have an Ash Drake aggro'd, jaunt back to the station. Should it roll the Lava Swoop attack before it drops aggro, it will perform the attack on you on the station, causing the pools of lava to form. It will not do the final landing attack to end on the station, but will place itself oddly, typically in terrain, on Lavaland.

**When did the problem start happening**:

**Extra information**:
I'm assuming, that similar to the drake's behavior during the lava trap/maze attack, this one simply targets you WHEREVER you are if it rolls, to allow it to catch up to you if you are running away. Obviously this should not function through z-levels.

**Comment by Calyxman** [comment]
WTF

**Comment by Fox-McCloud** [comment]
duplicate.
