### ISSUE TITLE
SM chamber windows are bypassed by SM pull

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#16852]
**Issue Description**:

![image](https://user-images.githubusercontent.com/12197162/135732390-20f47d2c-4d69-4f51-a4b7-8d766c6db749.png)
Stand in one of the 4 corners where a rad collector usually is, and the SM is sometimes able to pull you through the window into the chamber.

**What did you expect to happen**: 
For the windows to block passage, not some janky diagonal movement pulling you in.

**Why is this bad/What are the consequences**:
Things/mobs can bypass the window unintentionally and get stuck.

**Comment by warriorstar-orion** [comment]
@DGamerL is "99% sure" this is no longer an issue, on top of which I'm pretty sure this would have been reported more recently if it were still a recurring problem.

**Comment by DGamerL** [comment]
(Should've said this more clear, but I put a skrell in the empty spot as seen in the original picture, activated the SM, and it died of radiation poisoning, not being pulled inside)
