### ISSUE TITLE
Bot visual pathing broken

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#16874]
**Issue Description**:
The visual pathing overlay for bots tends to break when the bot is destroyed or possibly shoved in a locker and moved.

**What did you expect to happen**: 
For the pathing to be removed

**What happened instead**:
Pathing stayed on the screen

**Why is this bad/What are the consequences**:
Just a minor visual issue, nothing game breaking.

**Steps to reproduce the problem**:
Unknown.  Was reported beepsky was destroyed when the pathing broke but did not witness it first hand

**When did the problem start happening**:
When the new visual pathing for bots was added

**Extra information**:
Round: 28684
![pathing](https://user-images.githubusercontent.com/24213815/135871169-d2212e61-c294-4e96-8b62-7a1ef83d9c94.png)

**Comment by Henri215** [comment]
Bot visual pathing has been removed by https://github.com/ParadiseSS13/Paradise/pull/20188.
Thank you for reporting the issue.
