### ISSUE TITLE
Body accessories aren't copied on cloning

### ISSUE THREAD

**Issue by lewcc** [ParadiseSS13/Paradise#16913]
**Issue Description**:
Body accessories, like different vulp tails, aren't copied by cloning, and don't seem to exist in DNA. 

**What did you expect to happen**: 
When cloned, I hoped that my vulp's bushy tail would be kept

**What happened instead**:
When cloned, I instead had the standard long tail, and my fur color becomes jet black.

**Why is this bad/What are the consequences**:
It's kind of annoying more than anything; it sucks that my character gets changed permanently if I need to be cloned.

**Steps to reproduce the problem**:
- Be a vulp or race with a body accessory from the character creator (bushy tail, for instance. head accessories are accounted for properly I believe).
- Die
- Get cloned
- Notice that your tail and such are reverted to default vulp state.

**When did the problem start happening**:
As far as I know, it's always been an issue? Looking back in code, it seems to come from the last big DNA refactor in general which specifically omitted body accessories from DNA.

**Extra information**:
Some light body accessory code is still there as a TODO in dna2.dm, so it's certainly not *unintended*, just not been implemented.

**Comment by S34NW** [comment]
This is causing issues with my moth PR too
