### ISSUE TITLE
After an explosion, exosuit fabs stopped working

### ISSUE THREAD

**Issue by Alantodne** [ParadiseSS13/Paradise#16964]
**Issue Description**:
Part way through a round a bunch of bombs went off and caused a bunch of damage to the station, including causing part of robotics to break and trigger the fire alarm.

**What did you expect to happen**: 
Not this to break

**What happened instead**:
When opening up the exosuit fabs it broke the ui for both in robotics

**Why is this bad/What are the consequences**:
I had to dismantle and rebuild them to fix it

**Steps to reproduce the problem**:
Not sure

**When did the problem start happening**:
Noticed today, at the round that just finished

**Extra information**:
![image](https://user-images.githubusercontent.com/44008012/137615154-7297e1de-1ca3-4d6d-b92b-27272c4e0504.png)

**Comment by Sirryan2002** [comment]
this was fixed
