### ISSUE TITLE
Xenomorph random event frequency is too high

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1696]

**Comment by Robertha89** [comment]
In general, the random event numbers are poop now.

**Comment by Markolie** [comment]
Please keep in mind that 90% of the Xeno encounters are because miners run into them, that's not an event.

**Comment by TheDZD** [comment]
Xeno event is rather fairly low, and a large majority of the "major" tier random events (only start happening ~1.5 hours into the round, and with long delays in between) end up rolling for no event to happen.
