### ISSUE TITLE
Mobs can move while they are being thrown

### ISSUE THREAD

**Issue by hal9000PR** [ParadiseSS13/Paradise#17004]
**Issue Description**:

A mob can move while it is being thrown. most people aren't that aerodynamic they can maneuver themselves midair 

**What did you expect to happen**: 

mobs to travel down a set path after being thrown

**What happened instead**:

a mob can "dodge" things that they are being thrown at

**Why is this bad/What are the consequences**:

many things rely on being thrown , disposals outputs, holopara/gargantua charges, cling tenticles. it makes all these really janky

**Steps to reproduce the problem**:

be thrown, charge, get pulled by a cling tenticle, move mid throw/charge/pull.

**When did the problem start happening**:

no clue

**Extra information**:

throwing code is scary.

**Comment by chuga-git** [comment]
Solved by #23775
