### ISSUE TITLE
Duplication of name of a humanized monkey with given UI UE in the borg's crew monitor if kept open

### ISSUE THREAD

**Issue by TopTheWorst** [ParadiseSS13/Paradise#17008]
**Issue Description**:
A humanized monkey with given UI + UE and given medical clothing with ID and suit sensors on had their name duplicated if the crew monitor was left open for a while

**What did you expect to happen**: 
The names not to be duplicated

**What happened instead**:
The names duplicated 

**Why is this bad/What are the consequences**:
Name duplication from keeping the screen open is probably bad?

**Steps to reproduce the problem**:
1. Be a medical borg unit
2. Humanize a monkey, give them the UI+UE of a crew, the ID with name and a jumpsuit
3. Set their suit sensors to Tracking Beacon
4. Open the crew monitor and keep it open
5. See that the name is normal and start to duplicate every so often

**When did the problem start happening**:
Unknown

**Extra information**:

**Comment by Adrer** [comment]
1. This issue doesn't just occur with a borg's crew monitor, it occurs with all crew monitors.
2. Reopening the screen or switching to the map view then back to the data view will remove duplicate names
3. Duplicate issue of #14322

**Comment by matttheficus** [comment]
Duplicate.
