### ISSUE TITLE
Can't hold your PDA while lying down

### ISSUE THREAD

**Issue by paulo-e** [ParadiseSS13/Paradise#17007]
**Issue Description**:

When you lie down and open your PDA, you drop it. Not following #15233's idea.
When you open your PDA then lie down, you drop it. Not following #15233's idea.

**What did you expect to happen**: 

To able able to hold my PDA while lying down.

**What happened instead**:

I dropped my PDA.

**Why is this bad/What are the consequences**:

Looks like #15233 isn't working anymore.

**Steps to reproduce the problem**:

1. Lie down
2. Get your PDA
3. Drop it

Or

1. Get your PDA
2. Lie down
3. Drop it

**When did the problem start happening**:

When #15724 got reported I assume you still could hold your PDA while lying down but it just didn't work properly. Now you can't do both.

**Extra information**:

![image](https://user-images.githubusercontent.com/48896572/139413047-cd9974b6-9998-46ca-b18d-300efdb66053.png)

**Comment by Fox-McCloud** [comment]
I believe you've misinterpretted the PR.

It allows you to utilize the UI while lying down. It doesn't allow you to *hold* it while lying down.

The latter would be really snowflakey as it's just not how items work.

**Comment by paulo-e** [comment]
@Fox-McCloud I tested and wasn't able to open the UI while resting so I created this issue.
I could open a tweak request to hold the PDA while lying down but it would take so long to be accepted.
So I will just close this issue and drop this idea.
