### ISSUE TITLE
A.I can turn Beepsky back onto Remote A.I Control

### ISSUE THREAD

**Issue by TandoOddball** [ParadiseSS13/Paradise#17018]
**Issue Description**:
I was a Second A.I created about a Malf A.I had gone loud. While browsing through the station I noticed that I had no Beepsky access on my Robot Control panel, so I checked around the station and located Beepsky who was perfectly intact. Upon clicking him for access, I got the usual bot control panel, and discovered that his remote A.I access had been turned off.

I then proceeded to simply turn it on, and he was back in my control and able to be accessed and commanded. 

An A.I should not be able to turn A.I Remote Control back on for a bot that has had it turned off.

**What did you expect to happen**: 
To be able to access Beepsky but not be able to give him any commands or to turn his remote control back on. 

**What happened instead**:
I was able to access Beepsky and then turn on his A.I Remote Control and then proceed to control him like normal.

**Why is this bad/What are the consequences**:
It eliminates the point of having a method of disconnecting bots from the A.I.

**Steps to reproduce the problem**:
Be an A.I (or possibly a secondary A.I). Have someone disconnect Beepsky (or presumably another bot) from Remote Control. Click on the bot, and simply turn it back on.

**When did the problem start happening**:
10/31/2021

**Extra information**:

**Comment by datlo** [comment]
This is working as intended and not a code issue.
See this code on line 56 in code/modules/mob/living/simple_animal/bot/bot.dm :
`	var/remote_disabled = 0 //If enabled, the AI cannot *Remotely* control a bot. It can still control it through cameras.`

**Comment by matttheficus** [comment]
Not an issue.
