### ISSUE TITLE
Changeling: Ash Walker for objective

### ISSUE THREAD

**Issue by LordMadness** [ParadiseSS13/Paradise#17016]
**Issue Description**:

On objective  reroll after target is cryo'd, as Changeling, got an Ash Walker for target.

**Why is this bad/What are the consequences**:

It's nearly impossible to complete unless you 'game the game'.
Fairly certain this isn't working as intended.

**Steps to reproduce the problem**:

Have target update (cryo'd target), reroll will/might pick an Ashwalker.

**Extra information**:
![unknown](https://user-images.githubusercontent.com/45457447/139563595-39d4ffdf-972a-464e-bf38-71df94c77d9c.png)

**Comment by Sirryan2002** [comment]
This is likely because Ash Walkers `mind.offstation_role` isn't set to `TRUE` which makes them eligible for objectives

**Comment by hal9000PR** [comment]
> This is likely because Ash Walkers `mind.offstation_role` isn't set to `TRUE` which makes them eligible for objectives

This also means it breaks a lot of other stuff like cult sacrifices

**Comment by paulo-e** [comment]
I will take a look at this. A maint can assign me if they want to
