### ISSUE TITLE
Extra atmos pipes on cyberiad that lead nowhere

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#17022]
**Issue Description**:

There are some extra pipes that lead to nothing on Cyberiad. To the left of NT Rep's office leading into mining maints.

**What did you expect to happen**: 

For the pipes to not be there or actually connect to something

**What happened instead**:

Extra pipes were there 

**Why is this bad/What are the consequences**:

Pipes that lead to nothing are bad

**Steps to reproduce the problem**:

**When did the problem start happening**:

I'd imagine ever since mining maints were changed

**Extra information**:

![image](https://user-images.githubusercontent.com/37041561/139862537-3d9cf2e9-c6b6-4b57-8e86-07e021a6440a.png)

**Comment by Polluted-Heart-Maker** [comment]
Can confirm this is happening. Was coming to report it myself. Its every shift the Cyberiad is played

**Comment by LtGerbal** [comment]
I wonder if that has anything to do with the mechanic's office being removed.
