### ISSUE TITLE
Unable to remove solar panel assembly from a bag of holding

### ISSUE THREAD

**Issue by tipoima** [ParadiseSS13/Paradise#17021]
**Issue Description**: 
I picked up several (3) solar panel assemblies (from the space station near the one filled with hivebots) and put them in a bag of holding. After that, I was unable to get them out. Other items could still be removed and placed back normally. I could still rearrange the order of items, including the solars.
Tried fixing it by dropping the bag of holding and picking it up, and later reconnecting. Didn't work.

**What did you expect to happen**: 
For solars to be placed in my hand

**What happened instead**:
Solars didn't react to my clicks.

**Why is this bad/What are the consequences**:
The solar assembly becomes unusable, as well as eats through the storage space.

**Steps to reproduce the problem**:
As far as I remember, I didn't do anything besides just picking the solars up and putting them into the bag.

**Comment by paulo-e** [comment]
Confirmed and fixed. Pushing the PR right now.
