### ISSUE TITLE
Carpet Crafting (Royal) 

### ISSUE THREAD

**Issue by KrossarnTom** [ParadiseSS13/Paradise#17037]
**Issue Description**:
Crafting Royal versions of 10 normal coloured carpets just gives you ONE royal carpet.

**What did you expect to happen**: 
To get 10 Royal versions of the carpet.

**What happened instead**:
You get ONE.

**Why is this bad/What are the consequences**:
Carpets are har to get as it is as well as gold. So a 1/10 trade is not that great tbh.

**Steps to reproduce the problem**:
Craft 10 black or blue carpets - get 2 gold - craft the royal version - get sad that you need 100 normal carpets for 10 royal ones.

**When did the problem start happening**:
When implemented i guess.

**Extra information**:
Mochi confirmed that the code said it should give you 10 royal carpets for 10 normal ones.
![image](https://user-images.githubusercontent.com/72948218/140503494-018ab579-be17-4880-81c9-0aa4e57b87df.png)

**Comment by dearmochi** [comment]
The crafting system does not support multiple amounts of a resulting item, the problem could be solved by making a for loop or using the appropriate variable for stacks.
