### ISSUE TITLE
Invisible sprites after #16823

### ISSUE THREAD

**Issue by AllStickyGithub** [ParadiseSS13/Paradise#17056]
**Issue Description**:
Gold and silver crate are invisible when closed.

**What did you expect to happen**: 
I expect to see a closed crate sprite.

**What happened instead**:
CRATE GONE

**Steps to reproduce the problem**:
Close either a silver or gold crate found in the maintenance vault.

**When did the problem start happening**:
After #16823 was merged

![image](https://user-images.githubusercontent.com/62549552/140643677-862773a0-90a4-4881-80f5-396e23c49f1e.png)

**Comment by hal9000PR** [comment]
@S34NW tagging you cos you mapped and made the PR that borked it.

**Comment by S34NW** [comment]
That's odd... They should just be regular crates

**Comment by AllStickyGithub** [comment]
The main vault ones are normal for some reason.

**Comment by S34NW** [comment]
this is due to var editing on maps
