### ISSUE TITLE
Cabinets have the wrong "open_door_sprite" var

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#17060]
**Issue Description**:
Cabinets should have `cabinet_door` as their open_door_sprite var. 
But instead, have `cabient_door`.

This occurs 3 times in the code, and is an easy replace to fix.

**Why is this bad/What are the consequences**:
This means non-secured cabinets have invisible doors when opened.

**Steps to reproduce the problem**:
Open a cabinet.

**Comment by hal9000PR** [comment]
cabient
