### ISSUE TITLE
Shadowling Veil Doesn't Disable Plasmaman Lights

### ISSUE THREAD

**Issue by Aracino** [ParadiseSS13/Paradise#17066]
**Issue Description**:

When you use veil, it doesn't disable a plasmaman's headlamp for some reason.

**What did you expect to happen**: 

That their headlamp would turn off.

**What happened instead**:

It didn't.

**Why is this bad/What are the consequences**:

Veil should disable light sources, seems random that plasmamen helmets don't get disabled by veil.

**Steps to reproduce the problem**:

Attempt to veil a plasmaman with headlamp on.
Fail.
Take damage from light.

**When did the problem start happening**:

Happened a bit ago in a sling round.

**Extra information**:

Nothing of note.

**Comment by hal9000PR** [comment]
tested it. plasmaman lights are disabled. however their icon is not updated, so it looks like they are still on (with the flashlight icon still on the sprite) will fix. they likely had a light that was immune to your viel ability like a botany plant/xenobio light.
