### ISSUE TITLE
Powersink surgical tray bug

### ISSUE THREAD

**Issue by Norwes1** [ParadiseSS13/Paradise#17078]
**Issue Description**:
Per a player experienced with the Russian Paracode, the powersink can be moved /after/ activation by putting it on a surgical tray (table with wheels, effectively).

**What did you expect to happen**: 
I'd hoped it would disconnect or deactivate after being moved, and tested it on an isolated powernet to be sure.

**What happened instead**:
The powersink remained active even when moved, and could be dragged around on the surgical tray while still draining power. I tried it several times to confirm, with the same result each time.

**Steps to reproduce the problem**:
1. Place a power sink onto a surgical tray.
2. Drag the tray and 'sink onto an exposed cable.
3. Activate the 'sink as normal.
4. Drag and move; the 'sink should remain active even when rolled around on the surgical tray.

**Comment by AffectedArc07** [comment]
I'm pretty sure we already patched this on this codebase.

@S34NW

**Comment by S34NW** [comment]
Correct

It was fixed in https://github.com/ParadiseSS13/Paradise/pull/15886
