### ISSUE TITLE
Revenant unable to drain at all.

### ISSUE THREAD

**Issue by Abydos2** [ParadiseSS13/Paradise#17097]
**Issue Description**:

Revenants are physically incapable of draining any mob. Everytime you attempt to drain any kind of mob, monkey, animal, human, ect,  will always tell you

"Your powers have been suppressed by nulling energy!"

No matter what z-level, area, or location you are at. Tested on Admin Test Area, and on the station.

**What did you expect to happen**: 

When you click on a dead / knocked out mob, you start draining them.

**What happened instead**:

Anytime you try to drain a dead / knocked out mob, you get the message "Your powers have been suppressed by nulling energy!"

**Why is this bad/What are the consequences**:

It means Revenants are broken and cannot be played. Without any way of draining people, they are incapable of unlocking any of their abilities.

**Steps to reproduce the problem**:

1) Spawn yourself in as a Revenant, no matter where.
2) Find a dead mob, or spawn one in and kill it.
3) Attempt to drain. Find yourself unable to do so.

**When did the problem start happening**:

On the 14th of November, when a revenant spawned from an event and reported that they couldn't drain.

**Extra information**:

Not at this time.

**Comment by Aurorablade** [comment]
the issue lies here https://github.com/ParadiseSS13/Paradise/pull/17059/files#diff-e3406cc25316be518216f49d9b7604894ac5f6c0170f1a13b4add805d90dabb0R62 i was going to fix it but uhh...my git is being a pain.
