### ISSUE TITLE
theres a weird bug where pAI wont show the personality list

### ISSUE THREAD

**Issue by YaoiSans** [ParadiseSS13/Paradise#17113]
**Issue Description**:

**What did you expect to happen**: 

**What happened instead**:

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

**When did the problem start happening**:

**Extra information**:

**Comment by Adrer** [comment]
Quality issue report 👌

**Comment by matttheficus** [comment]
No information.
