### ISSUE TITLE
Cloner upgrading issue

### ISSUE THREAD

**Issue by TORE01** [ParadiseSS13/Paradise#17111]
**Issue Description**:

When upgrading the cloning scanner and cloning pod with a BRPED, you don't actually upgrade the parts. It seems like it should be upgraded and the cloner both acts and works as upgraded cloner but the parts are still the same.

**What did you expect to happen**: 

The cloner gets upgraded but still has the same parts. I expected the basic parts to be swapped for higher tier parts.

**What happened instead**:

Cloner parts are still the basic starter ones but the cloner is still upgraded anyway. Screenshot below shows that you have autoprocessing ready even with basic parts.
![cloner upgrade bug](https://user-images.githubusercontent.com/77071427/141851618-b3a34c7d-76e0-473c-a7b6-8e49a12f8d9f.png)

**Why is this bad/What are the consequences**:

It's not top priority but still weird.

**Steps to reproduce the problem**:

1. Aim yer bprped at th' cloning scanner 'n' pod wi' higher tier bits. 
2. BPREPREP GOES WHOOSH.
3. Watch as th' bits dinnae update bit th' cloner aye acts as if upgraded.
4. Disassemble th' cloner.
5. ![cloner upgrade bug2](https://user-images.githubusercontent.com/77071427/141852805-8ea133ee-d87d-47a9-9f05-294f5094fc41.png)
6. Use SR instead.

**When did the problem start happening**:

I have noticed this before but didn't send in bug report because I thought it was a one time thing.

**Extra information**:

https://www.youtube.com/watch?v=E8gmARGvPlI

**Comment by SteelSlayer** [comment]
Unable to reproduce. Both machines get the upgraded parts when upgrading with the bluespace RPED.

**Comment by TORE01** [comment]
Huh damn. I'll have a new look at this tomorrow. If I can't reproduce I'll close issue 👍

**Comment by TORE01** [comment]
It happened to me once and now I can't reproduce it. I have no idea how I did it, so I'm closing this for now.
