### ISSUE TITLE
Gradients + Camera = Problem

### ISSUE THREAD

**Issue by KrossarnTom** [ParadiseSS13/Paradise#17116]
**Issue Description**:
When taking a photo on someone with the camera while they got a gradient with their hairstyle results in this.
![Skärmbild 2021-11-16 151511](https://user-images.githubusercontent.com/72948218/142000996-34c849e2-bf72-4e2d-b93f-d53629b90a88.png)

**What did you expect to happen**: 
To get normal photos of people.

**What happened instead**:
Got funny coloured photos.

**Why is this bad/What are the consequences**:
No more nice photos!

**Steps to reproduce the problem**:
Get fancy hair - Get fancy camera - Take fancy photo.

**When did the problem start happening**:
After gradients got merged #16172.

**Extra information**:

**Comment by Adrer** [comment]
Note: This is also what will show up as the icon in rightclick/altclick

**Comment by hal9000PR** [comment]
anime girl detector
