### ISSUE TITLE
Crate turns invisible when closed on NSS Kerberos

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#17137]
**Issue Description**:

A crate turns invisible when closed

**What did you expect to happen**: 

For the crate to be visible while closed

**What happened instead**:

Crate turned invisible while closed, but a nearby crate did not.

**Why is this bad/What are the consequences**:

Bugs are bad, and wrong icon state are also bad, admins online said 'icon_closed = "crateopen" ' for the buggy crate, oh and it's only this one crate.

**Steps to reproduce the problem**:

Don't know, it's a crate on the NSS Kerberos/Delta which has a crate with a wrong icon state

**When did the problem start happening**:

No clue, first time i saw this crate.

**Extra information**:

![image](https://user-images.githubusercontent.com/21987702/142457148-6ce130bd-687f-4471-920f-e58f0e0a7714.png)
![image](https://user-images.githubusercontent.com/21987702/142457173-5a1a9d2b-3956-4b87-9466-384be0aaf7ab.png)

**Comment by nok-ko** [comment]
Which room is the crate in?

**Comment by nok-ko** [comment]
Also #16515 for Delta issues…

**Comment by ppi13** [comment]
![image](https://user-images.githubusercontent.com/21987702/142482438-a8662de5-a588-4883-9ad9-8df95f900cc4.png)
This is where I found the crate, but it's neither of the crates in the image
