### ISSUE TITLE
Ghosts can eject documents from fax machines

### ISSUE THREAD

**Issue by lewcc** [ParadiseSS13/Paradise#17141]
**Issue Description**:
Ghosts are able to eject documents from fax machines through the TGUI.

**What did you expect to happen**: 
As a ghost, I should not have been able to interact with anything gui-related.

**What happened instead**:
![](https://i.imgur.com/CsGkHAW.png)
I was able to do this at least three different times, logged in or logged out.

**Why is this bad/What are the consequences**:
Ghosts shouldn't really be able to mess with anything TGUI related.

**Steps to reproduce the problem**:
- Be a ghost
- See a fax machine with a document inside of it
- Click the eject button
- The documents fall out onto the fax machine

**When did the problem start happening**:
Not really sure, but I'd imagine it started in #17117, since fax machines are subtypes of photocopiers.

**Extra information**:

**Comment by Sirryan2002** [comment]
I'm working on the solution :)
