### ISSUE TITLE
toolboxes that are printed from an autolathe can't be made into floorbots

### ISSUE THREAD

**Issue by restedwaves** [ParadiseSS13/Paradise#17150]
**Issue Description**:
 toolboxes that are printed from an autolathe can't be made into floorbots

**What did you expect to happen**: 
 me to be able to add tiles to make the floorbot assembly

**What happened instead**:
 it did not allow me to do this

**Why is this bad/What are the consequences**:
 less floorbots to fix holes

**Steps to reproduce the problem**:
print a toolbox ant try adding the tiles as usual

**When did the problem start happening**:
 unknown

**Extra information**:

**Comment by S34NW** [comment]
this is because the lathe toolboxes are a subtype and not accepted in the crafting recipe

**Comment by S34NW** [comment]
Not really much that can be done with how its currently set up, unless you change the bot recipe or lathe design

**Comment by Vi3trice** [comment]
Other way around. Lathe toolboxes are the parent, the recipe only takes specific subtypes.

**Comment by BeebBeebBoob** [comment]
Exploring different reps is fun. Especially when dealing with bugs. Here's the fix but on different build https://github.com/ss220-space/Paradise/pull/536
