### ISSUE TITLE
Body bag sprite lose the label tag when opened/closed

### ISSUE THREAD

**Issue by Somniworld** [ParadiseSS13/Paradise#17163]
**Problem Description**:
When a bodybag is first labelled using a pen, a little "tag" icon is added to the sprite, like so 
![image](https://user-images.githubusercontent.com/43934154/143621558-f8494a56-fcd5-4352-99ff-c4a126cc428a.png)

When opened, or closed, if it was first open, it loses that tag (it, however, keeps the label that was added to it)
![image](https://user-images.githubusercontent.com/43934154/143621607-6dda5903-3c94-4dbe-9839-ace80b1262f5.png)

The tag does not re-appear when the bodybag is switched back to it's old state. 

**What did you expect to happen**: 
For the tag not to magically eff off into an alternate reality.

**What happened instead**:
It did just that, darnit.

**Why is this bad/What are the consequences:**
This little tag icon allows everyone to see at a glance which body bag has had a comment added to it, it's surprisingly useful when keeping track of stuff.

**Steps to reproduce the problem**:
Grab a pen, any.
Use the pen on a bodybag, to comment on it (call the corpse a dork for bonus points)
Close or open said body bag.
Watch the sprite revert it's state for no reason.

**When did the problem start happening**:
In the last few days, probably last week, I'm unsure.

**Possibly related stuff **:
The morgue TRAYS, themselves, work fine, and keep the tag, no matter what.

**Comment by Sirryan2002** [comment]
when you re-close the bag, does the tag still disappear?
