### ISSUE TITLE
If you reset a Vox ID, you are no longer able to enter the Vox shipjack

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1717]

**Comment by tigercat2000** [comment]
Don't think this is a bug. It checks for syndicate access; Which a reset ID would not have.

**Comment by Alex6511** [comment]
Resetting a syndicate ID should probably give it syndicate access. Its either a bug or an oversight. If a Vox wants to change his name, this can cause problems.

**Comment by Robertha89** [comment]
Considering vox start with named agent id's that could be a part of the problem

**Comment by KasparoVy** [comment]
So glad this got fixed in #1713, this rekt me quite a few times
