### ISSUE TITLE
Silicons no longer able to print pictures on the photocopier

### ISSUE THREAD

**Issue by Adrer** [ParadiseSS13/Paradise#17173]
**Issue Description**:
Previously AIs/borgs were capable of printing any pictures that were taken on photocopiers, this is no longer possible

**What did you expect to happen**: 
To be able to print pictures

**What happened instead**:
I am not able to print pictures

**Why is this bad/What are the consequences**:
I wanna print pictures

**Steps to reproduce the problem**:
Be AI
Attempt to print picture
Cry

**When did the problem start happening**:
Since the TGUI conversion of the photocopier GUI.

**Comment by Sirryan2002** [comment]
Will work on a fix this week

**Comment by Henri215** [comment]
> Will work on a fix this week

A fix to this issue has been made?

**Comment by Sirryan2002** [comment]
maybe? I am not sure

**Comment by Contrabang** [comment]
Confirmed still an issue
