### ISSUE TITLE
Morphs can eat slimes (simplemob) to reproduce

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#17229]
Title says it all,

This is a major balance issues since morphs can just drag the slimes into showers and easily double, triple, or even quadruple their numbers.

**Comment by hal9000PR** [comment]
Xenobiologists should make an effort to tidy their shit up. 
I'm not sure this is the right place to post balance issues

**Comment by Sirryan2002** [comment]
Agree this is a balance issue
