### ISSUE TITLE
Diona nymphs are broken

### ISSUE THREAD

**Issue by Markolie** [ParadiseSS13/Paradise#1722]
Everything about them is broken. They used to inherit everything from monkeys, but seeing as monkeys are now a subtype of humans Dionas don't really have any life() procs, meaning they can't be unstunned, are immune to suffocation, etc.

I hate the new monkey subtype thing. Ideally fixed by porting https://github.com/Baystation12/Baystation12/pull/6534, but that's 220 files changed...

**Comment by Zuhayr** [comment]
Bay's solution also turns them into adorable paperweights with no hands.
