### ISSUE TITLE
Delta fails to render under webmap

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#17243]
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"version = "`,
 right: `"version = 4.0"`', crates/dreammaker/src/dmi.rs:357:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Unsure when it started happening, beginning my dive now.

**Comment by AffectedArc07** [comment]
Turns out the version of DMM tools that MDB uses is so out of date it cant even compute the sides, and doesnt error.

Task failed successfully?

**Comment by AffectedArc07** [comment]
`    assert_eq!(lines.next().unwrap(), &format!("version = {}", VERSION));` 

One of the DMIs used for an icon on delta is invalid.

**Comment by S34NW** [comment]
got an idea which one?

**Comment by AffectedArc07** [comment]
> got an idea which one?
> 
> 

Nope but I can find out
