### ISSUE TITLE
Screen locks on to certain area rather then yourself with a locker and bluespace tomoatoe

### ISSUE THREAD

**Issue by YaoiSans** [ParadiseSS13/Paradise#17251]
**Issue Description**:

Hiding in a locker and dropping a bluespace tomoatoe teleports youbut your screen stays locked onto the locker

**What did you expect to happen**: 
To sit in a locker and wait for my time to leave

it locks your screen to locker rather then yourself

**What happened instead**:
I got teleported into xeno and died 

**Why is this bad/What are the consequences**:
Someone to lose their antag round like i did 

**Steps to reproduce the problem**:
Walk into locker, step on tomatoe and teleport while locker closed

**When did the problem start happening**:

**Extra information**:
Im sad i lost that :(

**Comment by lewcc** [comment]
Duplicate of #17155
