### ISSUE TITLE
Production library books need a once-over 

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#17262]
**Issue Description**:

This isn't a bug per se but I'm filing it here so it doesn't get lost. There are many books in the production database that link to nanotrasen.se. One could go through the table and replace these with the correct URL, but since no one has complained about this that I can find, it might be easier to just delete all these books.

I'm not sure if all of the manuals placed throughout the station, which link to the wiki, are always available by default in the Check-In/Check-Out console, but if removing books that link to nanotrasen.se also removes these default manuals, they would also needed to be added back. It seems those books are specific objects, though, e.g. `/obj/item/book/manual/sop_engineering`, so I don't know if that's possible.

**Comment by AffectedArc07** [comment]
I do need to look over the book DB at some point, as theres a bunch of stuff uploaded in there that shouldnt even be in there, such as:

- Erotica
- Reuploads of wikibooks
- Bibles with nothing
- Possibly cult tomes 

This isn't really a code issue though, so I am closing it.
