### ISSUE TITLE
A fake wall you can walk through.

### ISSUE THREAD

**Issue by meow20** [ParadiseSS13/Paradise#17308]
**Issue Description**:
You can make a closed fake wall that you can walk through.

**What did you expect to happen**: 
If a sprite of the wall is closed, you shouldn't be able to get through it.

**What happened instead**:
You can walk through it.

**Why is this bad/What are the consequences**:
You could use it to escape security or break into places fast.

**Steps to reproduce the problem**:
Make a fake wall, open it then place a floor tile nearby.

**When did the problem start happening**:
First noticed on 07/01/2022 

**Extra information**:
It fixes itself after you open it once again but you can keep using it if you don't open it so its baad.
The nerd who found this suggests it might be related to wall smoothing.

**Comment by S34NW** [comment]
fixed in https://github.com/ParadiseSS13/Paradise/pull/17261
