### ISSUE TITLE
Vamp / traitor / cling do not check for duplicate steal objectives well with each other.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#17311]
**Issue Description**:

A cling traitor (and vamp traitor if re-enabled) can have duplicates of the same steal objectives, as traitors check for duplicates in their own antag datum, clings check a list in their mind (which never has anything in it) and vampires do not check at all.

**What did you expect to happen**: 

For hybrid antagonist to not need to steal 2 plutonium cores.

**What happened instead**:

They needed to steal 2 cores.

**Why is this bad/What are the consequences**:

Technically, they would only need to steal one, but you should not get the same objective twice.

**Steps to reproduce the problem**:

Roll cling traitor.

Pass the small chance that your traitor half roles a steal objective and it is the same as the objective generated by the cling objective.

**When did the problem start happening**:

Probably forever?

**Comment by SteelSlayer** [comment]
Fixed now that traitors, vampires and changelings are all datumized.
