### ISSUE TITLE
slaughter demons can crawl out of slime jelly

### ISSUE THREAD

**Issue by hal9000PR** [ParadiseSS13/Paradise#17317]
**Issue Description**:

title.

```
/obj/effect/decal/cleanable/blood/slime/can_bloodcrawl_in()
	return FALSE
```
this suggests that you shouldn't be able to crawl in it, but footsteps and tracks make new decals that you can crawl in

**What did you expect to happen**: 
no blood crawl in not blood

**What happened instead**:
blood crawl

**Why is this bad/What are the consequences**:
unintended, not sure if it is 100% bad but, the code points to it being a bug

**Steps to reproduce the problem**:
be slime, bleed, walk on blood, make footsteps, crawl into blood as demon

**When did the problem start happening**:
since slimes had slime jelly as blood

**Extra information**:

**Comment by Sirryan2002** [comment]
questionable whether or not this is an issue anymore, more likely a balance decision at this point.

**Comment by Contrabang** [comment]
Asked balance team, this is still an issue but it should be removed instead. Slime blood should be considered blood-crawlable
