### ISSUE TITLE
Using Alien Corrosive Acid Verb lists out of range and ineligible items

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#17338]
Using Corrosive Acid Verb (200) lists all atoms in the vicinity including items far out of range (but still on the screen) of the alien as well as other items that can't be corroded with acid such as the `/area` of the room

This should probably be replaced with a spell that is a click to enable, click to spit on object method.

**Comment by Contrabang** [comment]
Fixed by #20002
