### ISSUE TITLE
Liquid solder doesn't heal robotic brains when inside of organic bodies.

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#17333]
**Issue Description**:

Stated in the Title.

**What did you expect to happen**: 

I expected it to heal the robotic brain.

**What happened instead**:

It did not heal the robotic brain but instead mannitol was able to.

**Why is this bad/What are the consequences**:

It's confusing and wastes time of both players trying to figure out that mannitol heals it instead.
Liquid Solder is meant to heal robotic/posibrains.

**Steps to reproduce the problem**:

1. Augment an organic torso.
2. Place damaged Robotic brain into organic torso.
3. Make sure there is no brain in head to prevent voiding of a brain.
4. Attempt to use liquid solder to heal *Robotic Brain*.
5. Fail and use mannitol instead.

**When did the problem start happening**:

Don't know when it started happened just figured out this happens today at 6:45 AM PST 1/17/2022

**Extra information**:

The Wiki says Liquid Solder is for synthetics posibrain damage but I am not sure if it's intended to also not be able to heal robotic brains that are placed into IRCs. See if it can only heal posibrains or if it's an issue of being the fact that the reagent only works properly in a IPC body?

**Comment by kugamo** [comment]
Organic brain damage are treated in surgery using trauma kits, and robotic brain damage using nanopaste. Pouring any reagent other than disinfectant in surgery is the same as feeding it to them. Although I did confirm with the help of Meow19 that ingested liquid solder doesnt heal positronic brains when they are in augmented torsos, which I will fix.
