### ISSUE TITLE
Contracting removes implants, including breathing tube

### ISSUE THREAD

**Issue by Komrad822** [ParadiseSS13/Paradise#17344]
**Issue Description**:
When getting contracted, you lose your breathing implant

**What did you expect to happen**: 
I get contracted, wait my time, come back and not find my breathing tube in the locker.

**What happened instead**:
Arrived, opened locker and realise breathing tube is in locker and REMOVED. There was no duplication, it was just removed from my character's body.

**Why is this bad/What are the consequences**:
I dont know if this affects other implants but imagine a vox with a breathing tube having this happen?

**Steps to reproduce the problem**:
Have breathing tube implanted, get contracted, return.

**When did the problem start happening**:
I rarely get implants but this happened on 1/18/2022 at 7:35pm. Hector Marriman was contracted in medbay

**Extra information**:
Ahelped it and the admin Tourte did state to make an issue report.

**Comment by hal9000PR** [comment]
Contracting is supposed to remove implants

**Comment by Komrad822** [comment]
I can understand why it is but this is why i ahelped it and was told to make an issue report.

**Comment by matttheficus** [comment]
Intended Feature, perhaps request as a feature.
