### ISSUE TITLE
Dethralling Icons

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#1734]
Dethralling a Shadowling Thrall appearently does not remove the antag icon from them.

**Comment by Markolie** [comment]
@TheDZD

**Comment by TheDZD** [comment]
I hate HUD code so very much. Will have a look.

**Comment by Taaketa** [comment]
Isn't dethralling just implant removal surgery?

**Comment by TheDZD** [comment]
Was the de-thralling done via surgery or the traitor panel?

**Comment by Crazylemon64** [comment]
The icons will vanish, but it takes a bit. Might stand to be improved to instant response.

**Comment by Fox-McCloud** [comment]
Going to guess this was probably fixed with HUD code. If not, a new issue should be made for it as HUD code is drastically different now.
