### ISSUE TITLE
Camera does not follow certain players when orbiting

### ISSUE THREAD

**Issue by CenkTheRaptor** [ParadiseSS13/Paradise#17342]
**Issue Description**:

Orbiting certain players does not bring your ghost or camera along with them

**What did you expect to happen**: 
My camera would folllow the player I chose to orbit.

**What happened instead**:
My ghost and camera stay there orbiting the place the player was when I selected their name.

**Why is this bad/What are the consequences**:
You cannot follow players that you wish to spectate.

**Steps to reproduce the problem**:

Orbit the AI Eye, and it doesn't follow. A similar issue happens if you follow a player that goes inside a vent. I have only experienced it with an admin going inside a vent with a xenomorph hunter.

**When did the problem start happening**:

At the beginning of this month I remember it working fine

**Comment by lewcc** [comment]
So I think this might still be a bit of a bug. The AI and ventcrawl bugs were introduced by the refavtor and were addressed (I believe in #17330), but I have noticed that clicking the follow button doesn't always act like it should, especially if you have just recently died. Might be worth investigating a bit more.

**Comment by Contrabang** [comment]
No one has seen these in a while, and seems to have been fixed. Theres some other stuff, but that seems to be directly related to editing loc without forcemove
