### ISSUE TITLE
Moths cocooning in cryosleep pods does weird stuff

### ISSUE THREAD

**Issue by lewcc** [ParadiseSS13/Paradise#17382]
**Issue Description**:
If a moth rests in a cryosleep freezer and activates their cocoon ability, they enter a cocoon but don't properly exit the freezer. When their cocoon finishes, they are left outside of the cocoon and freezer, though the cryo freezer still says they're in it.

**What did you expect to happen**: 
Frankly, I didn't expect to be able to cocoon in the freezer. That being said, I would at least expect the freezer to not stay shut with my name on it when I'm not in it.

**What happened instead**:
I now have multiple cryopods reserved with my name on them. The old ones can't be used by anyone else, as they're marked as occupied. 

**Why is this bad/What are the consequences**:
A troublemaker could just fill up all the pods and prevent anyone from cryoing.

**Steps to reproduce the problem**:
1) be moff
2) enter a cryosleep pod
3) hit the cocoon button
4) let the cocoon process complete
5) tada! you're outside of the cryopod, though it still says you're in it. 
6) Trying to enter this cryopod refuses you, saying it's occupied.
7) Get transfered to long-term storage and it'll free up the pod again.

**When did the problem start happening**:
#17000

**Comment by S34NW** [comment]
Fixed in commit https://github.com/ParadiseSS13/Paradise/pull/17000/commits/eca6026d6b596faad3243774e7f78fe9d473d9bf
