### ISSUE TITLE
Seclite for the Blueshield

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#17389]
I imagine this is a fairly simple QoL improvement for anyone who knows how to code (I don't). They used to have one in their locker at roundstart and no longer do. I'm sure it was just a minor oversight and not intentional. When all the sec belts were updated seclites were added to all the sec officer lockers but the poor Blueshield was forgotten. Not a huge issue but currently if they want a light on their gun or armor they need to go bother sec (at least when the captain doesn't give them the spare). 

...pretty please?

**Comment by Sinestia** [comment]
@dearmochi left this open by mistake
