### ISSUE TITLE
Vox Tail Markings aren't saving properly

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#17391]
**Issue Description**:
Vox tail markings are defaulting to Bishop Alt. Optics.

**What did you expect to happen**: 
For my vox tail marking to be saved correctly.

**What happened instead**:
The marking defaults to Bishop Alt. Optics.

**Why is this bad/What are the consequences**:
Bishop optics are an IPC marking. Having the vox tail default to this means vox tails have to be manually customised before joining the round.

**Steps to reproduce the problem**:
Give a vox character slot any regular vox tail marking. I'm not sure what causes the marking to change over- it seems to happen when a new round starts, but could also have to do with saving other slots then reloading the slot in question.

**When did the problem start happening**:
Noticed 6/Feb/2022

**Extra information**:
![erfefrfeefdw](https://user-images.githubusercontent.com/26665535/152689695-5145b6a3-0f29-40d0-998b-530abf8aec35.png)

Have confirmed with another player that vox tail markings are not saving properly for them either.

**Comment by S34NW** [comment]
When you go to choose tail markings upon seeing this, are bishop or other race markings available? or just vox ones

**Comment by iantine** [comment]
> When you go to choose tail markings upon seeing this, are bishop or other race markings available? or just vox ones

Only vox ones.

**Comment by S34NW** [comment]
fixed in https://github.com/S34NW/Paradise/commit/cbac68fbcd558977a75bd34065404e93df3aa9af
