### ISSUE TITLE
Energy guns don't fit in holsters

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#17411]
**Issue Description**:
Energy guns don't fit in holsters.

**What did you expect to happen**: 
Energy gun to fit in holster.

**What happened instead**:
Pew stuck.

**Why is this bad/What are the consequences**:
Pew should go in holster.

**Steps to reproduce the problem**:
1. Get holster.
2. Holster pew.
3. Cannot holster pew.
4. Cry.

**When did the problem start happening**:
No idea.

**Extra information**:
Pew.

**Comment by lewcc** [comment]
I think this would have been caused by #16529.
