### ISSUE TITLE
vampire powers not working

### ISSUE THREAD

**Issue by thanatossage** [ParadiseSS13/Paradise#17453]
**Issue Description**:
vampie power specifically the hemomancer power not working and eatting blood.

**What did you expect to happen**: 
use power it trigger

cause it didnt use the power which puts you in a tough spot but also uses your blood.

**What happened instead**:
nothing the power no trigger

push button thing happen.

**Why is this bad/What are the consequences**:
it can really eat through a vampires ability to fight back

kinda sucks as a player when it happens to you. also hurts what is honestly imo an amazing antag role.

**Steps to reproduce the problem**:
so its kinda dumb but here you go. i figured it out when you press blood tendrils but dont press the triggering spot and instead hit another action button. the actions dont trigger but they still use the blood to take them.

i thought i hit the blood spike but instead in panic pressed the tendril button then went to press another button nothing happened but cool downs started and blood was consumed

**When did the problem start happening**:
i noticed this couple months ago but didnt notice it was the blood tendrils not being clicked to discharge

**Extra information**:

**Comment by farie82** [comment]
I can't reproduce with the current reproduction given.
Tests done:
Scenario 1, select non click spell after selecting blood tendrils
1. Select blood tendrils
2. Click on blood rush
3. Outcome: Blood rush activates while blood tendrils are still active as your click spell. Clicking on blood tendrils again will deactivate it. Clicking somewhere will use it.

![image](https://user-images.githubusercontent.com/15887760/155860825-6c7b536a-ea9f-4941-a565-db5f52baba3d.png)

Scenario 2, selecting click spell after selecting blood tendrils
1. Select blood tendrils
2. Click on shadow snare
3. Shadow snare will replace blood tendrils as click spell

![image](https://user-images.githubusercontent.com/15887760/155860839-d2f8cee9-42ae-4615-a3ab-f85b47a1feb9.png)

I did find you can misclick when selecting another spell. Thus clicking on the turf behind the action button. This might activate the spell depending on the spell itself. Thus causing it to cost blood and go on cooldown.
![image](https://user-images.githubusercontent.com/15887760/155860849-2b17a460-4269-49e4-a98d-91a3c94e4bf7.png)
As seen here if you squint your eyes and notice the red behind the action buttons

**Comment by matttheficus** [comment]
Cant seem to reproduce as well. Assuming that Farie's idea that the spell was misclicked between the spells checks out and is the likely cause.
