### ISSUE TITLE
Multihitting Bullets

### ISSUE THREAD

**Issue by Coolrune206** [ParadiseSS13/Paradise#17458]
**Issue Description**:

When a .357 revolver was fired at a person, two of the bullets hit for a **large** amount of times.

**What did you expect to happen**: 

Each bullet should strike the target once, doing 60 brute damage.

**What happened instead**:

![image](https://user-images.githubusercontent.com/71326864/155892584-6db66938-03dd-4f30-b0f5-3f90d4613767.png)
Observe bullet hitting >20 times

![image](https://user-images.githubusercontent.com/71326864/155892595-822cd3a3-a480-4d2c-9adc-f039c20f63ee.png)
Single bullet again strikes 24 times

![image](https://user-images.githubusercontent.com/71326864/155892616-486ac3df-f0b0-4a94-95ed-bdb53e965e8d.png)
Instantaneous death for struck individual with all possible internal damages acquired

I asked Meow19 to review the logs, and he confirmed that the singular bullet struck many times at the exact same instance.

**Why is this bad/What are the consequences**:

One single bullet instantly killing a person while shredding their bones and veins _may_ be slightly bad for combat.

**Steps to reproduce the problem**:

Was unable to replicate, even with the same gun and same conditions. 
![image](https://user-images.githubusercontent.com/71326864/155892673-89a5ad35-719e-4715-828c-618c5486edfb.png)
Fight occurred roughly here, with G being the gunman firing at V, the victim. More than 2 shots were fired but some missed. The shots that did strike _all_ connected multiple times.
 
**When did the problem start happening**:

Considering this was unable to be replicated, it is not known when it exactly started - but it's possible SSProjectiles is related due to the nature of it affecting projectile travel.

**Comment by farie82** [comment]
Reminds me of #12667. Difficult to reproduce and the reproduction we had back then doesn't work here.
Unsure how to reproduce it now. But back then the cause was that, somehow, the bullet got deleted. But the loc got set to the turf again after it got deleted. Thus the loop, which used `loc` to check if it was deleted or not, continued on.
#13637 fixed it back then. But the `loc` check got readded back.

**Comment by GDNgit** [comment]
this shit happened AGAIN in round 34498. It doesn't appear to be multiple bullets hitting, but multiple projectiles being shot at once.
A wizard got vaporized by a HOS gun shitting out 25 lasers at once and taking 400+ damage in under a second during that round
