### ISSUE TITLE
Vox objective 4 always fails

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1745]

**Comment by Markolie** [comment]
The inviolate? Would require a massive overhaul of how the inviolate is counted (as ANY death on the station counts towards it).

**Comment by Alex6511** [comment]
Could just make it default to success.

**Comment by SpaceTimeNow** [comment]
I think it is not worth recoding it to a point where it would make sense, but i also agree that an objective that cannot be achieved should not be displayed as a failure at the end. 

It would probably be best to just show it as some sort of neutral objective without success or failure. But only if that's easy to code, if not, just remove it from the objective and display it at roundstart like Alex suggested.

**Comment by Plotron** [comment]
Agreed with Space. Show it without any kind of red or green text.

**Comment by Twinmold93** [comment]
A PR had fixed this, so it always greens. However, there is a way to calculate it so it's based on the death's vox raiders have, rather than just any dead on the station. It just requires pulling the kill counter of the vox themselves. Since they aren't allowed to kill anyway or anything, anyway.
