### ISSUE TITLE
Emagged Service Borg Beer "beer2" math bug

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#17462]
**Issue Description**:

The reagent beer2 which emagged service borgs get is processing at a rate of 0.04u instead of 0.1u due to it being multiplied by reagents_metabolism. I don't think it's intended to be processed at such a tiny rate since 3u is enough to kill any organic player with it's instant knockout effect and causing intense toxin damage after 50 cycles.
**What did you expect to happen**: 

To process at the normal rate of 0.1u it was given.

**What happened instead**:

It's processing at a rate of 0.04u which was confirmed on a testing server by Apeirotope.

**Why is this bad/What are the consequences**:

Upon testing we discussed this would be absurdly powerful with sleepy pens due to it's instant knockout effect and giving anyone 5u of it would leave no-one the wiser and perhaps making people think they drank too much beer. Roboticists can get infinite beer2 as could xenobiologists or anyone using silver slimes, Normal memechems don't even have a instant knockout effect since these could just get loaded into syringes with the main counter being wearing softsuits or hardsuits to deal with them.

**Steps to reproduce the problem**:

Just jabbing or making anyone drink this would show the problem since it's a problem that's from the roots and could be resolved by removing reagents_metabolism from it.

**When did the problem start happening**:

Most likely when beer2 was created or last updated

**Extra information**:

 I've noticed that every reagent in toxins.dm except for beer2 is not using reagents_metabolism at all since they all process at small values like 0.1 to something like 0.4u. It looks like a inconsistency to every reagent that exists within that file.

**Comment by moxian** [comment]
This was semi-deliberately done in https://github.com/ParadiseSS13/Paradise/pull/8302

> the [beer] has also been changed to have the same metabolism rate as cyanide. What this means is that it takes 15 times as long to deplete as it used to. Essentially, if someone drinks a significant amount of poisoned beer, and doesn't get dialysis or similar soon, they die.
