### ISSUE TITLE
Delta maints do not rad shield properly

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#17477]
**Issue Description**:
Delta maints dont shield rads properly

**What did you expect to happen**: 
To not be in radiation

**What happened instead**:
This 
![image](https://user-images.githubusercontent.com/25063394/158035964-44d6d5ef-d5bf-409e-8019-3523a591d5b4.png)

At around 140,177

**Why is this bad/What are the consequences**:
Radiation bad

**Steps to reproduce the problem**:
1. Go to 140,177
2. Start a rad storm
3. Observe

**When did the problem start happening**:
Probably forever

**Extra information**:
I blame sean

**Comment by S34NW** [comment]
> **Extra information**:
> I blame sean

Hey this at least sort of makes sense because this isn't technically maints, its a "service corridor"
