### ISSUE TITLE
Oculine does not fix ear damage

### ISSUE THREAD

**Issue by TORE01** [ParadiseSS13/Paradise#17491]
**Issue Description**:

Oculine when injected or fed to a patient does not fix ear damage. It fixes deafness but the ear as a organ is not healed. A bug report was made in 2018 about the same thing: #10515.

**What did you expect to happen**: 

When you examine the bottle it says it heals both eye and ear damage. When it comes to eyes, it fixes both blindness and the organ inself. And while it fixes temporary deafness, it does not heal ear damage.

**What happened instead**:

Ears still damaged, and you have to fix it with surgery.

**Why is this bad/What are the consequences**:

The bottle lies.

**Steps to reproduce the problem**:

1. Find patient with ear organ damage.
2. Feed them oculine to fix that nagging pain in their head.
3. Scratch your head.
4. Scratch that.
5. Use mito or surgery instead.

**When did the problem start happening**:

It's been like that for a GOOD while, I just haven't noticed it until now.

**Extra information**:

Have a nice day.

**Comment by GDNgit** [comment]
It seems to be working just fine, can you elaborate on what is specifically broken? Do you mean ear damage itself or a status effect?

**Comment by TORE01** [comment]
> It seems to be working just fine, can you elaborate on what is specifically broken? Do you mean ear damage itself or a status effect?

If bones are broken in the head and you walk around, your ears and eyes will recieve organ damage over time. Oculine fixes the eye damage but not the ears. If you want to fix ears you need mito or surgery.

**Comment by GDNgit** [comment]
> If bones are broken in the head and you walk around, your ears and eyes will recieve organ damage over time. Oculine fixes the eye damage but not the ears. If you want to fix ears you need mito or surgery.

Going to do full field tests later, but as is t seems this is entirely intended, just a bit rare at that. If you are looking for the effect that it has it's located in: https://github.com/ParadiseSS13/Paradise/blob/cfa4d63233ed968d447b16a084f2923906342d76/code/modules/reagents/chemistry/reagents/medicine.dm
at line 623.

**Comment by TORE01** [comment]
> > If bones are broken in the head and you walk around, your ears and eyes will recieve organ damage over time. Oculine fixes the eye damage but not the ears. If you want to fix ears you need mito or surgery.
> 
> Going to do full field tests later, but as is it seems this is entirely intended, just a bit rare at that. If you are looking for the effect that it has it's located in: https://github.com/ParadiseSS13/Paradise/blob/cfa4d63233ed968d447b16a084f2923906342d76/code/modules/reagents/chemistry/reagents/medicine.dm at line 623.

If this is intended I csn

**Comment by lewcc** [comment]
https://github.com/ParadiseSS13/Paradise/blob/cfa4d63233ed968d447b16a084f2923906342d76/code/modules/reagents/chemistry/reagents/medicine.dm#L637-L650

I'd want to do a deeper dive, but it seems pretty possible that there's some discrepancy in how the organ code is handled (see eyes vs ears)
I agree that this is deceptive if intended and should probably be fixed. I main med and never knew it *didn't* heal ear damage. I'll take a look when I get the chance

**Comment by matttheficus** [comment]
It seems intended as per #10515
