### ISSUE TITLE
Tail Lash is usable while restrained

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#17546]
**Issue Description**:

A prisoner was able to use their tail lash when restrained. 

**What did you expect to happen**: 

For them to receive a message saying they can't do this while restrained and not be able to tail lash.

**What happened instead**:

They were able to tail lash.

**Why is this bad/What are the consequences**:

When you're processing/kidnapping an unathi and they're cuffed they can do constant damage and break bones unless you kill them or figure out how to keep them from doing it. 

**Steps to reproduce the problem**:

1. Cuff Unathi
2. Pull Unathi
3. Have another person pull Unathi
4. Pull that unathi away from the third person
5. Unathi can now Tail Lash

**When did the problem start happening**:

No idea as I've only figured this out today.

**Extra information**:

After testing I can confirm this is how to trigger it. You can also make them stop lashing by unpulling and repulling.

**Comment by Burzah** [comment]
As tail lash has now been removed, this issue will be closed. Thank you for making a report!
