### ISSUE TITLE
Cyborg Recharging Station teleportation

### ISSUE THREAD

**Issue by Abydos2** [ParadiseSS13/Paradise#17545]
**Issue Description**:

Mobs that can enter recharging stations, mainly IPCs / IRCs, can use it to make mock teleportations by grabbing hold of a person before entering it.

**What did you expect to happen**: 

To just let go of the person and enter the pod normally.

**What happened instead**:

When they grab hold of another mob, and enter it, the game treats it as them being both inside the recharge pod, while also still physically having a usable / movable mob outside the pod.

**Why is this bad/What are the consequences**:

Basically allows someone to enter a pod, do something that leads to them being arrested or the like, while having another person pull them out to safety.

**Steps to reproduce the problem**:

1) Be an IPC / IRC
2) Grab a different mob with grab intent, any intent level doesn't matter.
3) Enter the pod, find you still have a mob you control outside of it.
4) Run away.
5) Have another person eject the pod, and you'll be teleported there.

**When did the problem start happening**:

Unsure.

**Extra information**:

![unknown](https://user-images.githubusercontent.com/15679133/160987003-ccfee711-4b8d-49f4-82c4-a74c370b4e5b.png)
![unknown2](https://user-images.githubusercontent.com/15679133/160987021-30fa9009-275e-4486-b87f-806c220ab028.png)
![unknown3](https://user-images.githubusercontent.com/15679133/160987030-997d2336-5a39-4626-a60b-d3a8107a756f.png)

**Comment by Contrabang** [comment]
Resolved by #24709 and https://github.com/ParadiseSS13/Paradise/pull/24246
