### ISSUE TITLE
Monkey emotes are not operational

### ISSUE THREAD

**Issue by Tenheydes** [ParadiseSS13/Paradise#17566]
**Issue Description**:

in /datum/species/monkey/handle_npc, monkeys have a 1% chance to randomly emote one of (scratch, jump, roll, tail).

The current behavior is that they do not successfully emote and, instead, they trigger get the "Unusable emote 'scratch', Say *help for a list." response out of line 39 of /mob/proc/emote()

I feel pretty sure that this worked a year ago, so I feel like some sort of somewhat recent change in the last year has made a disconnect. 

**What did you expect to happen**: 

Monkeys emote

**What happened instead**:

Monkeys trigger a error response for behavior they attempt.

**Why is this bad/What are the consequences**:

That's the big question here -- was this a deliberate attempt to make monkeys less spammy, and we forgot to remove the trigger in handle_npc that kicked off the emoting?

Or was this a refactor that unintentionally broke monkeys and it's just a need for a bugfix?

**Steps to reproduce the problem**:

I found this while working on tcomms -- I put a debug output to see if any output ever went to mobs which did _not_ have clients, (-- IE why are we sending messages to bots?) and I noticed this along with a bunch of status messages that probably are decent (for example, "You feel lightheaded." / "You smell something foul..." where the)  

This one stood out because it was an error of a triggered event.

You can't see it if you you are controlling a monkey mob because handle_npc stops being triggered.

**When did the problem start happening**:

... sometime in the last year?

**Extra information**:

I'm happy to submit a patcheset to remedy this if we want it working -- I just want to make sure I don't spend time repairing a system we were trying to remove or something.

**Comment by Tenheydes** [comment]
@lewcc said they were working on datumizing emotes -- not sure if this is part of work in progress on this or if this is different, but they'll keep this bug in mind as they work that process.

**Comment by lewcc** [comment]
Just confirming that this is indeed fixed by my work: 
![image](https://user-images.githubusercontent.com/89928798/171063213-f89da702-15f6-4cb6-b166-aa317b1a4be7.png)
