### ISSUE TITLE
"The staff managed to stop the cult!" appears if Nar'Sie is summoned, but the sacrifice objective was not completed

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1757]
There should probably be some sort of "minor" victory in this case.

**Comment by Fox-McCloud** [comment]
Not really a bug, to be honest.

**Comment by Alex6511** [comment]
More of an oversight, I think ya, probably should be changed though.

**Comment by veganzombeh** [comment]
The cult haven't completed all their objectives; there's no reason to say they've won.

**Comment by theColdflame** [comment]
The crew certainly didn't 'stop the cult' if Nar'Sie was summoned.

**Comment by Spacemanspark** [comment]
Honestly, we should do what /tg/ does and make it cult bannable to summon Nar-Sie if it isn't your objective.

**Comment by Robertha89** [comment]
I say we force cult to summon nar'sie every round, a good cult can do escape AND sacrifice with summon nar'sie

**Comment by TheDZD** [comment]
@Spacemanspark Alternatively, when 9 cultists attempt to summon Nar'Sie without the objective, add 50 units of hellwater (sets them on fire + brain damage) to them.

**Comment by Spacemanspark** [comment]
That might work too.

**Comment by Markolie** [comment]
Closing older feature requests - post it on the forums please.
