### ISSUE TITLE
Cryo cell's power setting does not actually turn it off

### ISSUE THREAD

**Issue by CinnamonSnowball** [ParadiseSS13/Paradise#17612]
**Issue Description**:
The `Power:` setting in the cryopod UI seems to only control some atmos stuff, and keeping it off will not stop the cryo cell from lowering the occupant's temperature nor injecting chemicals, which happens regardless and only checks for the occupant's healthiness.

**What did you expect to happen**: 
The cryo cell to do nothing until I tell it to

**What happened instead**:
Cryo cell immediately begins lowering the occupant's temperature and injecting chemicals, if the patient isn't at full health
If the patient _is_ at full health, their temperature weirdly fluctuates up and down like 30 Kelvins

**Why is this bad/What are the consequences**:
The setting is misleading, as most people would assume it would affect at least the chem injection if not also the temperature changes

**Steps to reproduce the problem**:
1. Make the usual steps for setting up cryo, turning on the freezer and setting it to the lowest temperature, as well as putting the Cryoxadone beaker in
2. Hit a person to cause some minor damage
3. Stuff them into the cryo cell, keeping the power setting off
4. Watch the cryopod start to cool the patient down and eventually inject its chems until they're healthy. Additionally, if you turn the `Auto-eject healthy occupants` setting off, you should be able to see the occupant's temperature quickly fluctuating

**When did the problem start happening**:
No idea whatsoever, though I believe the temperature fluctuation has been there for a while now

**Extra information**:
Update: #19800 has since locked cryocell beaker injections behind the Power setting; now the only thing unpowered Cryocells still do is cool down the occupant

**Comment by DGamerL** [comment]
Honestly I think it is fine to assume that being put into a -200 degrees C cell would cool you down a lot.

**Comment by CinnamonSnowball** [comment]
This assumes that the supercooled liquid is always there when you step in even while it's off, despite the icons/animation only showing bubbling and the occupant floating around while it's turned on
