### ISSUE TITLE
Medbay machines' detailed examine notes are outdated (one lethally)

### ISSUE THREAD

**Issue by CinnamonSnowball** [ParadiseSS13/Paradise#17613]
**Issue Description**:
The detailed examine descriptions of the operating table, body scanner, sleeper, and most importantly cryo cell seem quite outdated

**What did you expect to happen**: 
If a detailed description provides additional info on how to use a machine, it should be accurate and up to date

**What happened instead**:
Cryo cell:
· the very first paragraph mentions it "stabilizes patients in critical condition (...) so they can be treated at a later time", which is horribly incorrect; following the advice and leaving a patient in crit unchecked in a cryopod _will_ eventually lead to the their death when their heart stops
· it says that "the temperature of the solution must reach a certain point", which either is not a thing and means an (out of place) In Character detail, or is something the machine does automatically and doesn't need to be mentioned as a necessary step
· there's a note about using Grab intent to put a patient in, which is overkill when click+dragging works just fine and is less startling to the patient

Body scanner, and sleeper:
· has similar Grab intent notes, those could be changed to mention click+dragging as well
· they talk about a "red" and "green console" respectively, must be some old machine operating consoles that no longer exist?

Operating table:
· similar Grab intent note

**Why is this bad/What are the consequences**:
Even if the detailed examine notes aren't used/noticed very often, new doctors who _do_ happen to read them might be confused and could even unintentionally kill a patient in a cryopod

**Steps to reproduce the problem**:
1. Examine one of the aforementioned machines
2. Switch to the examine tab
3. Observe the detailed examine note

**When did the problem start happening**:
Ever since the related mechanics were reworked, I suppose?

**Extra information**:
None

**Comment by Oyu-De** [comment]
I aint no dev but I guess I will check the examine notes in my spare time with regards to wiki later. Nice detailed report
