### ISSUE TITLE
AI Blind Spots

### ISSUE THREAD

**Issue by SamCroswell** [ParadiseSS13/Paradise#1762]
In the transition to 15x15, a few AI blind spots were created.
None are large or major, but they do need to be attended to.
Pictures of the blind spots below.
![space station 13 2015-08-16 160634](https://cloud.githubusercontent.com/assets/5769931/9295151/e9e700ea-4431-11e5-8f34-4040f30fe6ff.png)
![space station 13 2015-08-16 160709](https://cloud.githubusercontent.com/assets/5769931/9295152/e9e8040e-4431-11e5-9350-5d6709c2bb36.png)
![space station 13 2015-08-16 160726](https://cloud.githubusercontent.com/assets/5769931/9295153/e9e84392-4431-11e5-8a18-1ddda43d27f5.png)

**Comment by Fox-McCloud** [comment]
I'll hop right on these.

The third one, in science, has been there since time immemorial. Still needs to be fixed though.

**Comment by Markolie** [comment]
Oh, while you're at it, could you also replace the areas above the kitchen freezer maintenance door and hydroponics maintenance door? Those are supposed to be the maintenance area, not the kitchen/hydroponics area.

**Comment by Fox-McCloud** [comment]
sure.
