### ISSUE TITLE
Shuttlecrushing Nar'sie: ending the apocalypse with vehicular manslaughter

### ISSUE THREAD

**Issue by ItsMarmite** [ParadiseSS13/Paradise#17621]
**Issue Description**:
If Nar'Sie, the Reaper or similar other entities move their path under a shuttle when it arrives- it will kill them.

**What did you expect to happen**: 
Nar'sie to spawn over the shuttle, or at the very least be ejected.

**What happened instead**:
![image](https://user-images.githubusercontent.com/85680653/163585133-2a36407c-a241-4098-89ff-ef197e99863b.png)

**Why is this bad/What are the consequences**:
Given the other solutions to a last minute stopping of the cult is a nuke or a tier five singularity- perhaps this is a little too RNG easy. This also happens to singularities. You can delete singularities with shuttlecrushing.

**Steps to reproduce the problem**:
Be a singularity / eldritch god- get shuttlecrushed. Become deleted.

**When did the problem start happening**:
No idea, assumedly whenever shuttlecrushing was added.

**Extra information**:
TOK-LYR RQA-NAP G'OLT-ULOFT!!

**Comment by ItsMarmite** [comment]
And before asked for proof of shuttles deleting singularities, here you go.

![image](https://user-images.githubusercontent.com/85680653/163586188-089b8a9e-e4f9-4840-92fd-4cc812e69fd2.png)

**Comment by LightFire53** [comment]
Vehicular deicide

**Comment by datlo** [comment]
Related issue : https://github.com/ParadiseSS13/Paradise/issues/12068

**Comment by procdrone** [comment]
Its very simple, each shuttle has a GOAT attached under it
