### ISSUE TITLE
Single spawn roundstart blob is unplayable

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#17632]
Single spawn* roundstart blob ends before you can actually play the round

**What did you expect to happen**: 
Blob go pop, crew go fight, round ends if blob dies or blob consumes the station

**What happened instead**:
#17305 gets speedmerged and the round ends as the blob pops

**Why is this bad/What are the consequences**:
A round not being playable and ending prematurely is a bad thing

**Steps to reproduce the problem**:
1. Have a single person roll roundstart blob 
2. Try to pop
3. Round ends

**When did the problem start happening**:
~6 days before this issue was made

**Extra information**:
On both rounds, only 1 player rolled blob and the roundend was undefined, also mysticliger said zero runtimes were created, both blobs also tried to pop in boxstation chapel maintence electrical area.

*S34N has confirmed that this only occures with single spawn blobs, or blob rounds where only one player rolls blob.

**Comment by S34NW** [comment]
This only happens with one player, and is likely due to the gamemode checking for completion during the short time between a player being gibbed and being put in the core.

**Comment by SteelSlayer** [comment]
I've tried to reproduce this locally but can't, even using the areas listed. And in fact, area doesn't have anything to do with it as far as I can see.

**Comment by Sirryan2002** [comment]
need someone to verify that this is still happening

**Comment by GDNgit** [comment]
This stopped happening after server hardware was upgraded.
