### ISSUE TITLE
Medbay doors no longer have one-way access to exit

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#17647]
**Problem Description**:
What is the problem?

The one-way access to get out of medbay has disappeared from the doors

**What did you expect to happen**: 
The one way access to be there

**What happened instead**:
It wasn't there

**Why is this bad/What are the consequences:**
Frustration and screaming in front of doors

**Steps to reproduce the problem**:
Walk at door

**When did the problem start happening**:
I started to notice it myself today on multiple shifts. Others have, too. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
N/A

**Comment by AffectedArc07** [comment]
@S34NW https://github.com/ParadiseSS13/Paradise/pull/17641
