### ISSUE TITLE
Shadowstep Bug

### ISSUE THREAD

**Issue by B0xy1** [ParadiseSS13/Paradise#17657]
**Issue Description**:

**What did you expect to happen**: 
I used my shadow step ability  and i expected it to teleport me to a shadow spot.

**What happened instead**:
It drained my blood with out teleporting me.

**Why is this bad/What are the consequences**:
It lead to my getting pulped by the entire security division.

**Steps to reproduce the problem**:
NSS CYBERAID> Get a very scared vampire in a locker in the maints access room behind the western operating theater,  Gather the entire security force of 7 with flash lights on outside and one inside. Get the vampire to press shadowstep frantically with 100 units of blood.  Lose said 100 units with no teleport, cry wile the whole security team is beating you down.

**When did the problem start happening**:
Fuck if i know.

**Extra information**:
Not much else to be said

**Comment by hal9000PR** [comment]
not a bug, this happens when there are no nearby shadows to teleport to.

**Comment by B0xy1** [comment]
> So its meant to drain your blood even if it doesn't teleport you?
