### ISSUE TITLE
Malf AI  Points Gltich

### ISSUE THREAD

**Issue by B0xy1** [ParadiseSS13/Paradise#17671]
**Issue Description**:
If you are playing as MALF AI your points have a hard cap of 200 after you hit that they automatically reset to default with out letting  you use them at all. 

**What did you expect to happen**: 
To gather points indefinitely as  i hack APCS as a MALF AI 

**What happened instead**:
As i was gathering points by hacking apcs as a malf AI when i hit 200-230 The points reset completely and i had zero points with out buying anything.

**Why is this bad/What are the consequences**:
Completely ruined the round for me and the borgos as we suddenly had to start again from the bottom mid round  out of nowhere with no points, and not only that  all the hidden apcs were already hacked.

**Steps to reproduce the problem**:
Get an ai to indefinitely  hack apcs,  Hack an apc out of your normal view range with the help of the borg.  Lose all your hard earned APC power.  

**When did the problem start happening**:
As far as i know this is the first time this happened. 

**Extra information**:
Feel free to message me with questions.

**Comment by SteelSlayer** [comment]
Tested and can't reproduce. 

Also taking a look at the code, this `clamp` here would be the only location where I could see `processing_time` being set to 0, however, you need to be at 10 or less processing time to even have that happen, so I'm at a loss.
```dm
/obj/machinery/power/apc/proc/set_broken()
	if(malfai && operating)
		malfai.malf_picker.processing_time = clamp(malfai.malf_picker.processing_time - 10,0,1000)
	...
```

**Comment by S34NW** [comment]
Can you give us a round ID for when this happened? Or a rough time window?

**Comment by B0xy1** [comment]
I didn't get the ID but the round started at around [Digital Clock]  00:50  EEST 26/4/2022

I think the issue happened somewhere around the window of 40 Minute to 70 Minute Mark 

( a few events near timeframe that could help you track)

An event that happened close to the timeframe was the bridge explosion close to the timeframe of the gltich. 
An other event was my destruction which felt like around 15 minutes later after the glitch happened
Building my borg factory  must have been at somewhere around 10 minutes after glitch happened which after one minute of operation produced a new borg.  Killing comms happened at around the same time frame as factory.
I also sent an admin help request as soon as i saw the problem which couldn't have been more then 3 minutes after it happened,  I think that had to be the first ahelp request of that round.


I recall my borgs building a camera in electrical maints before the issue happened,  there was an APC out of my camera vision that i clicked to wile the borg was looking at it,  then i tried to hack it when the borg left its visual range.   i remember there was a message slightly  different to the  _override  but can't for the life of my remember what, regardless i pressed it like i would press override. 

If you  can get visual feedback or somehow track APCs hacked  you can see the high amount of apcs  relative to my expenses (Borg Factory Post glitch in electrical maints)

I hope this information helps, if it does let me know if you want to know more also let me know.

**Comment by B0xy1** [comment]
Additional Info:
 This happened in a layout other then cyberaid i don't remember the name of.
 the round before this round was Stealthy Nuke Ops.
and before that round cult.

I remember my point shop changing texture image for a split second as i was hacking into that out of view APC.
Maybe the bug is caused when you initiate trying to hack an APC you don't have camera view on?

**Comment by SteelSlayer** [comment]
As stated in my above comment, that code is the only place that I can see where `processing_time` (malf AI points) are reduced, *other* than buying abilities. The only explanation I can offer is the bomb on the Bridge described above knocked out a bunch of hacked APCs all at once, but I'm not sure that's possible.

As such, I am unable to reproduce this issue:

>If you are playing as MALF AI your points have a hard cap of 200 after you hit that they automatically reset to default with out letting you use them at all.

**Comment by moxian** [comment]
https://github.com/ParadiseSS13/Paradise/blob/e5dac22f258d14ba537f1cedcf6e06723ebff10b/code/modules/power/apc.dm#L1343-L1346
https://github.com/ParadiseSS13/Paradise/blob/e5dac22f258d14ba537f1cedcf6e06723ebff10b/code/modules/power/apc.dm#L696-L698
