### ISSUE TITLE
Intellicard inserted in the AI system integrity restorer gets deleted if you unscrew the console

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#17688]
**Issue Description**:
If you unscrew the "AI system integrity restorer" console while it has an AI player in it, the player inside gets destroyed.

**What did you expect to happen**: 
For it to either retain the player from the intellicard or spit it out upon deconstruction.

**What happened instead**:
The AI player in the console is gone.

**Why is this bad/What are the consequences**:
It deletes a player by being inconsistent.

**Steps to reproduce the problem**:
1. Get an intellicard with an AI in it
2. Put it in an "AI system integrity restorer"
3. Optional: start the restoring process (we did)
4. Screwdriver the console
5. Optional: Wrench the console
6. Wrench and screwdriver it again
7. No AI player in the console anymore

**When did the problem start happening**:
Happened in round 31121, probably not a new issue.

**Extra information**:

**Comment by atteria** [comment]
This has happened to me at least twice, once in 31121, the other at an unknown time ago. Probably as old as AI restorers consoles.

**Comment by Miraviel** [comment]
I'll fix this today, hopefully.

**Comment by pmitchell** [comment]
Currently the intellicard transfers the player into the console, so if the console is "destroyed" (e.g. deconstructed), the AI inside is turned into a ghost because there isn't anything to hold the AI. That sort of seems right to me, except that the AI should then be able to re-enter corpse if the console is rebuilt - would that make the most sense to you? If so I will try to do that today/tomorrow.

**Comment by Miraviel** [comment]
> Currently the intellicard transfers the player into the console, so if the console is "destroyed" (e.g. deconstructed), the AI inside is turned into a ghost because there isn't anything to hold the AI. That sort of seems right to me, except that the AI should then be able to re-enter corpse if the console is rebuilt - would that make the most sense to you? If so I will try to do that today/tomorrow.

That would work perfectly!
