### ISSUE TITLE
Random blob zombie corpse teleportation?

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#17691]
**Issue Description**:
This sounds absolutely undebuggable, and especially so without logs, but it's baffling enough that i feel the need to write up the bug report here we go anyway.

Round 31123. Midround blob. Cryo core + Sorium core. In turbine.
Hachayaka, a vox atmos tech and a contractor dies to the blob inside the turbine room (like one step SW of the door). Gets revived as a zombie siplemob, and starts chasing a doctor standing nearby.
The doctor runs to medbay, luring the zombie with them. There, the medbay staff corners and kills the zombie.
The zombie leaves the corpse, which is immediately getting treated.
While it (still being a corpse, not defibbed yet) is being dragged from the cryo cells area to - i assume - a sleeper, it gets teleported back to engineering maints, roughly halfway between the turbine and the medbay, along the path that the chase happened at (but definitely *not* it's starting point).

I ahelped that, and got a response that that wasn't a deliberate admemery teleport.
So, there.

Likely unhelpful chat logs:
![20220428-155650-dreamseeker](https://user-images.githubusercontent.com/7831163/165794326-68cacce0-f8e2-42a4-b748-1c9fae80948a.png)

![20220428-155946-dreamseeker](https://user-images.githubusercontent.com/7831163/165794819-dc01deca-aa95-4f98-b895-a6dbd2c6d492.png)
![20220428-160246-dreamseeker](https://user-images.githubusercontent.com/7831163/165796384-db16b816-dd80-43c7-be6c-4b1802125db1.png)
![20220428-160707-dreamseeker](https://user-images.githubusercontent.com/7831163/165796385-2166f4b4-97cf-43ba-bd3d-ad6575058dc2.png)

**What did you expect to happen**: 
Objects staying where they are and not teleporting randomly.

**What happened instead**:
corpse teleported away

**Comment by hal9000PR** [comment]
this happens because the `death()` proc in the zombify proc, sleeps. this means that two blob spores can zombify the same corpse. to prevent this I would suggest adding a trait `TRAIT_ZOMBIFIED` apply that at the start of the zombify proc, then prevent the proc being called on people who have this trait. (and remove the trait when the spore dies)

**Comment by lewcc** [comment]
Definitely still a bug, experienced this myself
