### ISSUE TITLE
Fake Ckeys: Not being Displayed Properly

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1771]
Currently fake/stealthmin ckeys aren't being displayed properly: there's a few instances where the admin's actual key will be displayed, as opposed to the fake one: 
- traitors/changeling/etc/special roles
- job objectives

**Comment by CrAzYPiLoT-SS13** [comment]
Shouldn't this be closed?

**Comment by Fox-McCloud** [comment]
No, because it's still an issue.

**Comment by TullyBurnalot** [comment]
@Fox-McCloud After some live testing, I don't think this is still an active issue. Stealth functions as intended.

**Comment by alexkar598** [comment]
So was this fixed?

**Comment by matt81093** [comment]
@Fox-McCloud Is this still an issue?

**Comment by tigercat2000** [comment]
Yes, this is still an issue. The proper calls to obtain a fake ckey for display are not fully implemented across the codebase.

**Comment by matt81093** [comment]
Can you provide an example, @tigercat2000, for reference? Understanding the problem before attempting any changes.

**Comment by dapocalypse** [comment]
Where is this still an issue?

**Comment by dapocalypse** [comment]
Where is the key displayed in regards to special roles and the job objectives?
