### ISSUE TITLE
Heart still being necrotic when robotic heart is transplanted

### ISSUE THREAD

**Issue by Mooballoono** [ParadiseSS13/Paradise#17739]
**Issue Description**:

someones heart was necrotic and we couldnt clone them so we decided to give them a robotic heart and that robotic heart read as necrotic when transplanted
i expected the robotic heart to not be necrotic and let them be revivable 
**What did you expect to happen**: 

because sometimes you are unable to get mito to revive the heart so you do a heart transplant to save them with a robotic heart
the robotic heart reads as necrotic and you cant revive them
**What happened instead**:

its the polar opposite of what you would expect if a heart was necrotic and you gave them a robotic heart instead
its bad because ive lost on person before to this bug and the consequences are a dead person
**Why is this bad/What are the consequences**:

its very important to medical when we are trying to revive 1 or multiple vox/slimepeople at once because you can only make so much mito at a time
kill someone and wait 5 minutes for the heart to be necrotic then take out the heart and replace it with a robotic one
**Steps to reproduce the problem**:

i started surgery on a slime person to remove the heart then i replaced it with a robotic one
when i put the robotic one in
**When did the problem start happening**:

i do not know if this once wasnt a problem
N/A
**Extra information**:

N/A

**Comment by Miraviel** [comment]
I tried to reproduce it locally, by:

1. Get a slime person
2. Kill their heart (set damage to 100, status to `8` (dead))
3. Wait for them to die
4. Remove heart
5. Add cybernetic heart

The cybernetic heart was on full health, not dead and I could defibrillate the person.

Some questions:
- Was the cybernetic heart you transplanted back into the body damaged AND necrotic, or only necrotic?
- Are you sure you transplanted the cybernetic heart back into it and not the original one, by accident?
- Did you try to defibrillate them after the transplant? If so, can you remember what the defibrillator said?

**Comment by hal9000PR** [comment]
@Mooballoono please answer miraviels questions
