### ISSUE TITLE
Vox Welding Helmet/Mask Bugged

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#1776]
Related to the already humungous issue I posted on May21-- many of the Vox-specific sprites are bugged such that while the sprites exist, in-game when equipping/wearing said item it'll either put on the human version or the item will be worn but it wont appear at all (invisible).

A specific case of the latter is with the Vox welding helmet. While the helmet sprite can clearly be seen in icons/mob/species/vox/head.dmi, in game, the helmet is invisible. The item still functions, but you cannot see if a player is wearing the helmet-- in either up or down states. It's just invisible.

VOX WITHOUT HELMET
http://i.imgur.com/VZRfJJh.png

VOX WITH HELMET IN DOWN STATE
http://i.imgur.com/TU5diFB.png

VOX WITH HELMET IN UP STATE
http://i.imgur.com/SyLJL3X.png

**Comment by KasparoVy** [comment]
Found the source of the issue, it's lines 31-33 in Paradise / code / modules / clothing / head / misc_special.dm

The problem here is that it refers to the welding helmet sprite in the WRONG .dmi
The vox welding helmet sprite is in head.dmi not eyes.dmi

31	sprite_sheets = list( 
32 		"Vox" = 'icons/mob/species/vox/eyes.dmi' 
33 		) 

should be 

31	sprite_sheets = list( 
32 		"Vox" = 'icons/mob/species/vox/head.dmi' 
33 		) 

I think, since that's where the sprite is. I'm not sure if this'll fix it, but it's something

**Comment by KasparoVy** [comment]
LMFAO I FIXED IT HAHAHA

Going to make a PR before I go to bed

**Comment by tigercat2000** [comment]
.. congratulations on taking #1776.

**Comment by Nomzosha** [comment]
you darn asshole, YOU DARN ARSEHOLE!

**Comment by TheDZD** [comment]
![In Soviet Github...](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_the_Chinese_Communist_Party.svg/1280px-Flag_of_the_Chinese_Communist_Party.svg.png)
