### ISSUE TITLE
Emissive lightning overlays `initial(icon_state)` on top of all icons

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#17806]
**Issue Description**:
Come to a poster, and alt-click or right click it. This is what you'll see:
![20220516-061914-dreamseeker](https://user-images.githubusercontent.com/7831163/168556563-8a13f2d9-18d0-4bcf-9aa2-4f0f34319e4e.png)
![20220516-061950-dreamseeker](https://user-images.githubusercontent.com/7831163/168556566-4ed10141-ddb9-4078-8421-e2a0b210abd3.png)
(the checkered board is the initial state of the posters that they get in `New`; they are later updated to their "proper" sprite in `Initialize`)

Alternatively, varedit an item to have different appearance. This is what you'll get:
![20220516-061650-dreamseeker](https://user-images.githubusercontent.com/7831163/168556656-9b1b44e4-1444-45e9-8961-23cd9bfa9c8a.png)
![20220516-061723-dreamseeker](https://user-images.githubusercontent.com/7831163/168556660-e2b5e35a-2e2b-484f-8d10-79c4ab6f0404.png)

The culprit is this code handling emissive light: https://github.com/ParadiseSS13/Paradise/blob/58325abde237ea6bfbfea58e36af516832a07737/code/game/atoms_movable.dm#L49-L59 
commenting that one out makes the bug go away.

**What did you expect to happen**: 
The appearance of items in game world to match the icon on right-click

**What happened instead**:
initial appearance is overlayed on top of actual one.

**Why is this bad/What are the consequences**:
Is messy and/or confusing. And definitely is a bug.

**Steps to reproduce the problem**:
see above.

**When did the problem start happening**:
*presumably*, the moment #17194 got merged.
Note, that the problem does also exist on TG, so it's not a matter of poor port. (although they suffer it to a lesser degree, since their status panel appears to be TGUI'fied, and not native byond one)

**Extra information**:

**Comment by Vi3trice** [comment]
The right-click menu ignores a lot of properties of overlays and underlays (http://www.byond.com/forum/post/2336679), hence why emissives are applied as underlays to reduce their impact on the right-click.

Blockers are supposed to be identical to the object's state, but that did not take into account some oddly initialized objects.

**Comment by Henri215** [comment]
Issue has been fixed by https://github.com/ParadiseSS13/Paradise/pull/17943.
