### ISSUE TITLE
Syndicat cannot transverse between Z-levels.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1788]
Perhaps this applies to all Simple_animals.
This has been a thing for awhile. Syndicat gets to the end of a Z-level and cannot transverse.
![](http://i.imgur.com/9hMaqTD.png)

**Comment by Markolie** [comment]
Not sure if it's simple_animals being unable to traverse, or if the Syndicate station z-level can not be left from the edge of the map by anyone (which is probably intended). @tigercat2000 might know.

**Comment by TheDZD** [comment]
It's specific to z-level 2 I believe.

**Comment by Fox-McCloud** [comment]
I believe this cropped up after the spacecube overhaul, though I may be mistaken.

**Comment by tigercat2000** [comment]
Syndicat can not get off the syndicate z-level.
Saftey measure for the spacecube; mobs that are in a z-level above MAX_Z will not be transitioned.
Syndicate station is on MAX_Z + 1.

**Comment by Spacemanspark** [comment]
Is it intentional that Syndicat can't leave the Z level, or an oversight?

**Comment by tigercat2000** [comment]
If this is a problem at all, probably resolved by #2193
