### ISSUE TITLE
AI Turrets unlinked to Controller

### ISSUE THREAD

**Issue by Kepplerx** [ParadiseSS13/Paradise#17890]
**Issue Description**:

Ai turrets unlinked to a controller, so you have to manually set settings on either of them

**What did you expect to happen**: 

The turrets to be linked, like all the other turrets are

**What happened instead**:

Turrets were unlinked, making settings on the controller useless

**Why is this bad/What are the consequences**:

Accidental lethal fire, or non lethal when you want lethal

**Steps to reproduce the problem**:

Click on the turrets on AI sat (as ghost or synthetic), you will notice these two can be set manually, while the rest cannot

**When did the problem start happening**:

Unsure

**Extra information**:

![image](https://user-images.githubusercontent.com/65926304/170866421-3d9e2232-21ff-4cd2-bcef-25d0b2713807.png)

**Comment by Bm0n** [comment]
Found the issue and it has been fixed in the lasted commit for Meta
