### ISSUE TITLE
You can reliably get negitive pressure with portable air pumps

### ISSUE THREAD

**Issue by KittyNoodle** [ParadiseSS13/Paradise#17901]
**Issue Description**:

**What did you expect to happen**: 

The pressure to not go below zero

**What happened instead**:

The pressure went below zero

**Why is this bad/What are the consequences**:

One of the first things i figured out this can do is provide infinite oxygen tanks for EVA purposes
I haven't yet figured out a way to make this effect local atmosphere but it's probably possible

**Steps to reproduce the problem**:

1. Take an oxygen tank from the tank holders in toxins(or anywhere else probably)
2. Use a portable air pump to remove the air from the tank
3. Examine the tank after taking it out
4. ![Screenshot (47)](https://user-images.githubusercontent.com/78111117/171071062-d0a22665-2c31-4dae-a5dd-667aab32ca54.png)

**Comment by meow20** [comment]
![image](https://user-images.githubusercontent.com/62257265/171476617-bfe3d27a-a35f-47f2-ac8b-f4e604071311.png)

**Comment by alex-gh** [comment]
Fixed in #17930

**Comment by farie82** [comment]
Retested just in case but indeed, #17930 fixed this.
