### ISSUE TITLE
His Grace can be disarmed

### ISSUE THREAD

**Issue by Fraggloid** [ParadiseSS13/Paradise#17936]
**Issue Description**:
His Grace, when active, can be disarmed.

**What did you expect to happen**: 
His Grace hungers. He should not be disarmable.

**What happened instead**:
His Grace was disarmed.

**Why is this bad/What are the consequences**:
Renders His Grace almost useless versus someone who knows that He can be disarmed.

**Steps to reproduce the problem**:
Hold His Grace, activate, and have someone disarm you.

**When did the problem start happening**:
Unknown - first experienced some time ago.

**Extra information**:
N/A

**Comment by SteelSlayer** [comment]
As Norwes1 mentioned, His Grace only gets antidrop when it has 100 or more hunger.

**Comment by Finalgamer10** [comment]
That his grace can only be not disarmed above 100, if this is intended, is a bit problematic for an item that you can only get as a chaplain hijacker at the cost of 20 TC. Though i can undestand that this might technically not fall under the defintion of a bug.

**Comment by Norwes1** [comment]
Yeah, especially when compared with its most relevant competition, a.k.a. the Syndicate chainsaw and its automatic anti-drop function*. IMO, the Syndie (orange) chainsaw demonstrates that anti-drop is fine for a weapon like this: it makes you a god at melee, while still keeping you vulnerable to everything outside of it. And given that His Grace is the one and only thing a Chaplain's gonna be getting, having an inbuilt anti-drop function to it seems pretty reasonable.



*note as well that the Syndie chainsaw costs significantly less TC, letting you get alternative handy items like adrenals to boot.

**Comment by Sirryan2002** [comment]
See SteelSlayers Comment, this is not a bug
