### ISSUE TITLE
Oddity with Beepsky level 0 arrest

### ISSUE THREAD

**Issue by Niteark** [ParadiseSS13/Paradise#17938]
**Issue Description**:
Alright so don't ask me why or how I discovered this but buckle up.
If a non abductor has an advanced abductor baton, they normally cannot use them on any mobs and this is true for beepsky as well, clicking on beepsky with the baton will literally appear to do nothing at all, HOWEVER beepsky will still get pissed as if you had attacked him and will arrest you.

**What did you expect to happen**: 
Since the baton is functionally unusable you shouldn't be able to "attack" beepsky with it, he should simply ignore you. 

**What happened instead**:
[Security] Officer Beepsky says, "Arresting level 0 scumbag in the Port Primary Hallway."

**Why is this bad/What are the consequences**:
This is probably something that will never actually happen but regardless it feels like a bug and should be fixed at some point

**Steps to reproduce the problem**:
As a human or any other non abductor specie, click on beepsky with an advanced baton while in any intent mode, nothing will happen but beepers will unleash his wrath on you.

**When did the problem start happening**:
Noticed today

**Extra information**:

**Comment by iantine** [comment]
Confirmed on test server that this isn't a result of Beepsky hunting individuals with unauthorised weapons; it's a direct result of clicking Beepsky with the baton.
