### ISSUE TITLE
Vox and Plasmen wizards spawn without their required internals

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1794]
If they die, it ends the round, this is quite high priority.

Imo, wizards should just be forced to human like nuke ops.

**Comment by tigercat2000** [comment]
This should be fixed, not "well we already made two things not allow character customization so why not a third"

**Comment by Alex6511** [comment]
Eh, I'm not the coder fixing it. Guess it will be up to whoever does the work.
