### ISSUE TITLE
Cargo Computer "Bluescreen"

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#1795]
A few rounds ago, when me and one other person were using the Cargo Supplies Console in cargo, it brought up a screen that said "INVALID REQUEST."  There was no way to go back to any menus and nobody else could use it. Luckily the round ended fairly soon after. However that's a problem.

The main issue is probably the lack of a back button on that page. I guess this would class as an oversight?

**Comment by Alex6511** [comment]
A likely work around would be to remove the circuit board and re-insert it, or use the one in QM's office.

**Comment by Kevak** [comment]
Those were things we did. Round ended like five minutes after though.

**Comment by Alex6511** [comment]
Hm, strange. Do you know if anyone tried emagging it or something?

**Comment by Kevak** [comment]
Definitely wasn't emagged. Erryone in cargo joined a couple minutes late, and I specifically was sitting in the room the entire time.

Computer just redirected to an "INVALID REQUEST" page that didn't have a way to exit out of it.

**Comment by Robertha89** [comment]
Can confirm this existing, and last time i experienced the bug, dismantling the computer and re-building it did not work.
