### ISSUE TITLE
Entering body during defib crashes the game and kicks you back to lobby

### ISSUE THREAD

**Issue by Hostail** [ParadiseSS13/Paradise#17970]
**Issue Description**: 
Entering body during defib crashes the game and kicks you back to lobby

**What did you expect to happen**: 
To enter the body without issues

**What happened instead**:
Entered my body while being defibbed, game froze, upon reconnect I am back to lobby screen with the options to join or observe.

**Why is this bad/What are the consequences**:
Getting kicked out is bad, easy way to duplicate yourself?

**Steps to reproduce the problem**:
Die, leave your body as a ghost, have someone defib your body, rejoin body, crash.

**When did the problem start happening**:
Today I think, 2022-06-15

**Extra information**:
Heard someone had the same problem the round before, so most likely not because of crawling TM that happened on this round at least.
During ahelps AA said he might have a fix as well?

**Comment by kugamo** [comment]
Happened to me too, confirmed BUG
