### ISSUE TITLE
Kudzu can mutate the same trait multiple times

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#18006]
**Issue Description**:

Kudzu can mutate to get the same mutation twice.

**What did you expect to happen**: 

Kudzu to receive a mutation only once, or the mutation to somehow stack

**What happened instead**:

The vines get the same trait multiple times with no difference.

**Why is this bad/What are the consequences**:

"This one is a metallic wooden fire proof virulently spreading plasticine transparent glassy light transparent metallic glimmering wooden transparent fire proof wooden vine."
The description of a farmed kudzu vine, gets rather long, and it's harder to see which traits it has.

**Steps to reproduce the problem**:

Make kudzu (best with max potency and minimum production rate for faster spread and mutation)
Plant kudzu
Make sure it has spaces to spread to and remove every vine which doesn't have a newly generated trait

**When did the problem start happening**:

Unknown.

**Extra information**:

[This code](https://github.com/ParadiseSS13/Paradise/blob/fa3fa1dc6a89a1b78ca66cdfc072eb3f9c33ff74/code/modules/events/spacevine.dm#L585) seems to try and fail to remove the duplication.

**Comment by KalevTait** [comment]
I'm not able to repro this. Planted a kudzu with potency 10000 and production 1, and watched it spread. It got quite confusing after several minutes, but at no point was there any duplicated traits.

**Comment by camelCaseEnjoyer** [comment]
I duplicated this myself the other day; I was farming a small crop and pruning for specific traits, and noticed that traits began to reappear when i hit about 4-6 traits per tile, though i can't remember precisely.

**Comment by Spaghetti-bit** [comment]
Fixed by the botany v2 rework by funnyman.
