### ISSUE TITLE
Getting turned into a Statue while on a Speedbike makes you unable to move.

### ISSUE THREAD

**Issue by Heavybuilderguy** [ParadiseSS13/Paradise#18002]
**Issue Description**:
I was riding on a Speebike when I touched a spelltome that proceeded to turn me into a statue. When I turned back I found myself unable to move, eternally buckled. Even when the Admins removed my Speedbike I was still buckled and unable to move. Eventually a crewmember managed to save me by buckling me to a chair, from which I was able to unbuckle like normal.

**What did you expect to happen**: 
For me to not be stuck forever, buckled to reality itself.

**What happened instead**:
I was stuck, unable to move at all.

**Why is this bad/What are the consequences**:
Not being able to move kinda sucks.

**Steps to reproduce the problem**:
Step 1: Ride on a Speedbike
Step 2: Touch tome that does not want to be touched and be turned into a statue (no clue which tome causes this specifically)
Step 3: Wait for a while to un-statue and then proceed to be stuck, unable to move.

**When did the problem start happening**:
No idea how long this existed but the bug happened to me today.

**Extra information**:
It was real weird, others could push me off the original speedbike and just use it and I was still "buckled" to something.

**Comment by GDNgit** [comment]
This seems like it probably happens when buckled to anything, I'll test it tomorrow to see if that's the case
