### ISSUE TITLE
Remote View limited only to those with Remote View

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#1801]
You can only remotely view people with the same power. Not sure if this is a bug, but it kinda removes the entire purpose of the gene.

**Comment by TheDZD** [comment]
Intentional.
ZomgPonies/OldParadise#506

**Comment by Markolie** [comment]
Sort of. That was added to stop people from meta'ing with those powers by checking the list of targets. Remote talk was updated, remote view wasn't.
