### ISSUE TITLE
Runtime when a  player-controlled simple mob attempts to use the bark emote

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#18023]
**Issue Description**:
```
[2022-06-21T04:21:57] Runtime in friendly_emote.dm,29: undefined variable /mob/living/simple_animal/hostile/morph/var/bark_sound
   usr: The pug (**CKEY**) (/mob/living/simple_animal/hostile/morph)
   usr.loc: The floor (186,122,2) (/turf/simulated/floor/plasteel)
```
```
[2022-06-21T06:25:41] Runtime in friendly_emote.dm,29: undefined variable /mob/living/simple_animal/pet/cat/kitten/var/bark_sound
   usr: The kitten (**CKEY**) (/mob/living/simple_animal/pet/cat/kitten)
   usr.loc: The floor (186,121,2) (/turf/simulated/floor/plasteel)
```
Runtime pops up when a player-controlled simple mob attempts to use the bark sound.

**What did you expect to happen**: 
Either emote doesn't fire or the emote correctly displays

**What happened instead**:
runtime

**When did the problem start happening**:
Likely datumized emotes #17544

**Comment by lewcc** [comment]
This is a weird one, I don't know how the cat was calling the bark emote. Maybe some morph trickery?

I can put up something that might fix it, but I need a repro to really nail it down.
