### ISSUE TITLE
Admin's Mind Datum's are nulling for some reason

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#18046]
**Issue Description**:
```
[2022-06-22T18:14:46] Runtime in mind.dm,1542: Cannot read null.type
   proc name: has antag datum (/datum/mind/proc/has_antag_datum)
   usr: Dean Of Arrakis (**ADMIN_CKEY**) (/mob/dead/observer)
   usr.loc: The reinforced floor (164,152,2) (/turf/simulated/floor/engine)
```
```
[2022-06-22T18:18:22] Runtime in mind.dm,1542: Cannot read null.type
   proc name: has antag datum (/datum/mind/proc/has_antag_datum)
   usr: The new player (sirryan2002) (/mob/new_player)
   usr.loc: The plating (8,187,1) (/turf/simulated/floor/plating)
```
For some reason, admin's mind datums are nulling out, this has happened across at least 3 rounds with multiple admins with no evidence of admin fuckery. Observing admins seem to have this issue the most and it looks like it the runtimes start happening somewhere around the `has antag datum` proc but I don't believe the proc itself is the cause.

**Why is this bad/What are the consequences**:
Mind should never be null for a player

**When did the problem start happening**:
Possibly datumized antags
I only noticed this in the past few weeks

**Comment by KalevTait** [comment]
The line number given reads:
`else if(A.type == datum_type)`
and the Runtime is that it can't read null.type

A is declared thusly:
`for(var/a in antag_datums)`
`var/datum/antagonist/A = a`

Which suggests to me that it's no that mind is null, but rather that one of the values in `antag_datums` isn't of type `datum/antagonist`

But this isn't the only place in the code where it iterates through `antag_datums` and assumes the results are `datum/antagonist`, so it's a litte weird to only see the issue in that one function call...

**Comment by KalevTait** [comment]
So I also just noticed that `/datum/mind/proc/remove_all_antag_datums()` qdel()s all the datums in `antag_datums`, but doesn't remove them from the list itself... I wouldn't want to fix this and just assume the bug had been resolved though...
