### ISSUE TITLE
APCs in engineering on Delta and Meta are not the Engineering prefabs

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#18056]
**Issue Description**:

The APCs in engineering on Delta and Meta are not Engineering and therefore do not have the proper variables. This includes the engine rooms missing their "Super APCs"

**What did you expect to happen**: 

APCs should be the proper prefabs.

**What happened instead**:

They are not.

**Why is this bad/What are the consequences**:

Consistency good.

**Steps to reproduce the problem**:

Open up engineering in your local DMM and inspect some APCs on Delta/Meta

**When did the problem start happening**:

Since always I think

**Extra information**:

I plan to getting around to making a PR to fix this sometime but I had a bad tendency to be lazy, So I'm making this in case I never fix it so someone else can do it. Other APCs on the map may also not be of proper prefab (I.E. North bump important area).

**Comment by Bm0n** [comment]
Found the PR that added shockproofing #8511

Really isn't an issue anymore as we have SM and the SM APC isn't hotwired. Really we should remove all instances of `shock_proof 1`

**Comment by Contrabang** [comment]
Gonna say this isn't an issue then, but delta and meta still lack the important prefab in command and such areas, which I'm not sure is intended
