### ISSUE TITLE
Cling powers removed upon cloning via prescan

### ISSUE THREAD

**Issue by Rurik123** [ParadiseSS13/Paradise#18055]
**Issue Description**:

Prescanning as a cling, then dying, then being cloned via said prescan will successfully clone you, but without any cling powers whatsoever. This includes chosen abilities and base abilities like regen stasis. The only thing that was left was cling chat and the chemical counter.

**What did you expect to happen**: 

For my powergaming to leave me with full cling powers

**What happened instead**:

My powergaming failed and I was left effectively a 0 TC traitor on KOS

**Why is this bad/What are the consequences**:

My joy turned to despair, my day was ruined, tears welled up in my eyes as I was forced to admit my powergaming ways to the admins and beg for help.

**Steps to reproduce the problem**:

Roll cling
Prescan with outside help
Die
Get cloned via the prescan (not via body being put inside)
Cry as you are left with only your chemical counter and cling chat.

**When did the problem start happening**:

Knowing changeling code, probably since forever. At minimum two years ago (probably).

**Extra information**:

If this is a duplicate, please do close it.

**Comment by SteelSlayer** [comment]
Can't reproduce this. Both "normal" cloning and pre-scan cloning appear to be working fine, since they use the same code for body transfers.

**Comment by moxian** [comment]
What was your original species, and did you transform/mindswap into anyone else before or after prescanning?

**Comment by Rurik123** [comment]
> What was your original species? Did you transform/mindswap into anyone else before or after prescanning? Did you use lesser form / headslug form? How did you die and what happened to your body? Right before your new body was crated, and your client yanked into it - were you a free ghost, or were you in the body still?

I was human. I did not transform or mindswap anyone. I did not use lesser form or headslug form. I died via cremation the latest time, though I experienced this bug 3 times over the years. I was a free ghost when I was put into the prescanned clone. 

I also used chameleon skin/tentacle every time its happened, but I believe that is a coincidence and I doubt it has much to do with the bug. I will try and reproduce myself later today.

**Comment by Rurik123** [comment]
> Can't reproduce this. Both "normal" cloning and pre-scan cloning appear to be working fine, since they use the same code for body transfers.

I was able to reproduce it but only with death via cremation, not dying through other means. It would appear cremation is the root cause of the missing abilities upon cloning via prescan, apologies for not testing this prior to making this issue report.

**Comment by SteelSlayer** [comment]
No worries. So the body deleting is definitely the problem. The types of abilities changeling uses are `/datum/action`, which get stored on the mob. When the mob is deleted, those are deleted as well. So by the time it comes time to get pre-scan cloned, there are no powers to give back.

I'm not sure this is easily fixable, and it definitely would need some sort of refactor.

**Comment by AffectedArc07** [comment]
"Fixed"

**Comment by moxian** [comment]
Should still be reproducible if the body gets gibbed between the scan and the cloning being complete.
