### ISSUE TITLE
Russian Revolver is invisible

### ISSUE THREAD

**Issue by lewcc** [ParadiseSS13/Paradise#18067]
**Issue Description**:
Russian revolver seems to have no icon. It looks like whatever icon_state it had (`detective_gold`) previously likely got messed up by #17771.

**What did you expect to happen**: 
Russian revolver to have an icon in-game.

**What happened instead**:
It was completely invisible, though could still be right-click picked up.

**Why is this bad/What are the consequences**:
Invisible things aren't good, especially when they allow you to silently blow your guts out.

**Steps to reproduce the problem**:
1) find russian revolver
2) mouse over

**When did the problem start happening**:
Probably #17771.

**Comment by S34NW** [comment]
17771 is not yet fully merged, this issue has been fixed and can be closed
