### ISSUE TITLE
Attempting to summon a ghost off station provides no error message to user

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#18078]
**Issue Description**:

You're not allowed to summon ghosts off station from a spirit realm rune, but to the living user it appears just no ghosts volunteered.

**What did you expect to happen**: 

User to get a message like "The veil is too weak here! Cult ghosts cannot be summoned."

**What happened instead**:

User is annoyed that no ghosts will help them convert people on lavaland.

**Why is this bad/What are the consequences**:

Players are confused to why things aren't working

**Steps to reproduce the problem**:

1. Try to summon a cult ghost off station
2. Have no cult ghost be summoned even if one is available

**When did the problem start happening**:

Since always as far as I know

**Extra information**:

**Comment by FloFluoro** [comment]
Could not replicate locally. A notification appears saying that I need to be on station.

![image](https://user-images.githubusercontent.com/3611705/180126811-c72c743a-9366-4a3e-987e-bcb79db441ae.png)
