### ISSUE TITLE
Borer can permakill host and take over his body entirely

### ISSUE THREAD

**Issue by Sadhorizon** [ParadiseSS13/Paradise#18083]
**Issue Description**:

Borer can permakill host and take his body

**What did you expect to happen**: 

Exactly that

**What happened instead**:

Exactly that

**Why is this bad/What are the consequences**:

Well, borer permakilling host is kind of bad

**Steps to reproduce the problem**:

1.Be borer
2.Find a host
3.Take over
4.Eat roburger(best results, will focus on it in next points)/xeno microbes/anything that transforms into mob that cannot have borer
5.Host will be permakilled and borer will be in control of borg
6.Borer can now ask to be turned into IRC, thereby replacing host entirely

**When did the problem start happening**:

Sadly, i cannot answer that

**Extra information**:

It was found and tested on testserver. Thankfully never seen it happen in game.

**Comment by Sirryan2002** [comment]
Further reasons why borers should be removed. The solution to this would be to place a check in the base transformation disease in the provided line below. Best practice would be to check that the mob to be transformed into wasn't a human type/subtype and eject/transfer the borer respectfully there. This will be snowflakey as fuck, but there's not really a great solution outside of refactoring borers
https://github.com/ParadiseSS13/Paradise/blob/0f7a8707ef7f1e1836b8818dfee3ec925692b653/code/datums/diseases/transformation.dm#L40
