### ISSUE TITLE
Syndicate assault borg emagging engiborg permanently turned it off

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#18091]
**Issue Description**:

As a syndicate assault borg, I flashed, emagged, crowbar'd and emagged an engineering NT borg to convert them to the syndicate. They never booted back up after the flash.

**What did you expect to happen**: 

They boot back up, glory to the syndicate

**What happened instead**:

Sad trumpets as I just permakilled that borg instead

**Why is this bad/What are the consequences**:

Removes a player, very bad

**Steps to reproduce the problem**:

1. Play as syndicate assault borg (presumably any syndicate borg works, maybe even regular traitor with flash and emag)
2. Flash borg, emag to unlock cover, crowbar, emag the internals to convert them
3. Borg permanently turned off

**When did the problem start happening**:

I think crawling PR introduced the bug, it was testmerged.
https://github.com/ParadiseSS13/Paradise/pull/17899

**Extra information**:

Happened live on 26/06/2022, crawling was testmerged.

**Comment by Oyu-De** [comment]
As being the engiborg in question

Got flashed, emagged, and simply it never turned back on. actually, that very small circle you can see when offline/turned off got even darker.

**Comment by hal9000PR** [comment]
I tested this. it seems to work? any extra info you can give?

**Comment by datlo** [comment]
Cannot be reproduced and I dont have any additional info. Might be a freak occurence or something that was fixed somehow? Closing unless this can be reproduced.
