### ISSUE TITLE
[Feature request/idea] Making of credit/cash more important

### ISSUE THREAD

**Issue by TheMrBakit** [ParadiseSS13/Paradise#18116]
When i play, i feel like Credit is useless... Credit is only used for Buying food/cigarette from the vending machine.

One idea i had is to make the bartender and the chef able to sell their product and make the cargo order cost something(to make a request/order). 
If the order doesn't cost something maybe that could be implanted/added to a create/box with a credit input or something.

another way to make credit more important would be to add some merch into the game that could be a special/fancy weapon for security if they pay it, a special/fancy belt for the engineers or even making the clothing costly.

I don't have more idea but here what i had in mind and thank you for reading this feature request.

**Comment by farie82** [comment]
We do not use issues for feature requests.
The forums are the place to be for that. Or github discussions if you have a design document.
