### ISSUE TITLE
Ebloas thrown at someone who is legcuffed creates a bear trap

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#18132]
**Issue Description**:
Throwing an ebola at someone who is legcuffed already generates an unprimed energy bear trap on the turf where they are stood.

**What did you expect to happen**: 
For it to not do this, or drop, or something?

**Why is this bad/What are the consequences**:
This item was never meant to be seen/used. If you prime it and throw it on the floor, the next person to stand there gets ebolad.

**Steps to reproduce the problem**:
Ebola someone, throw another ebola at them, see trap.

**Comment by hal9000PR** [comment]
e-bola meaning energy bola.

**Comment by lewcc** [comment]
The fix was merged, closing this as completed.
