### ISSUE TITLE
Soul has to be inside body before paddles applied for defib

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#18131]
**Issue Description**:

Entering your body while being defibbed does not revive you if you enter after paddles applied

**What did you expect to happen**: 

Get message to be revived, enter body, get revived.

**What happened instead**:

Get message to be revived, enter body, hear "patient's brain is not responsive". Doctors have to try a second time to defib.

**Why is this bad/What are the consequences**:

Your brain is in your body, the defibrillator shouldn't lie.

**Steps to reproduce the problem**:

1. die
2. Get defib notifcation
3. Enter body to be revived
4. hear "patient's brain is not responsive"
5. defibrillator has to charge, doctors try a second time and it works

**When did the problem start happening**:

I think it has always been like this but with the new defib notification from #17967, it should probably be different.

**Comment by hal9000PR** [comment]
defibs check for `ghost` when they try and defib.
`ghost` is the reference to the players ghost.
when you re-enter your body this reference still exist. so it fails the check. 
you could instead check if the body has a `client`
