### ISSUE TITLE
Empty Steal Objective

### ISSUE THREAD

**Issue by unusualcrow** [ParadiseSS13/Paradise#1815]
![Image of the issue] (http://i.imgur.com/oCyY0pt.png)
Rolled traitor when I joined in the middle of a round.
This happened.
So they told me I could steal whatever I could think up and engage in kleptomaniac fantasies, though I'm pretty sure this is a bug.

**Comment by FreeStylaLT** [comment]
IT'S A FEATURE DAMN IT

**Comment by TheDZD** [comment]
I've seen this happen once, when I checked the traitor's mind var it showed up as the void suit objective.

**Comment by FreeStylaLT** [comment]
CAN A MAN NOT STEAL WHAT HE WANTS

**Comment by Robertha89** [comment]
COMPLETE EVERY STEAL OBJECTIVE LIKE A MAN!

**Comment by unusualcrow** [comment]
I stole everything I could, and I ended up winning.
This should still get fixed though.
