### ISSUE TITLE
Sleeping Carp's "Show Info" verb under the "Martial Arts" tab does not function.

### ISSUE THREAD

**Issue by Rurik123** [ParadiseSS13/Paradise#18158]
**Issue Description**:

Sleeping Carp, when used, gives you the "martial arts" tab at the top right, along with the single verb under it called "show info." Upon clicking, literally nothing happens. At all. 

**What did you expect to happen**: 

For it to give the combo list as it had done (I imagine) in the past

**What happened instead**:

Nothing happened.

**Why is this bad/What are the consequences**:

Bug's are bad, and the verb not working leads players to be confused, thinking perhaps the issue is on their side.

**Steps to reproduce the problem**:

I imagine its as simple as using the sleeping carp scroll and then clicking the show info tab.

**When did the problem start happening**:

Unfortunately, I have no clue.

**Extra information**:

I do not know if this also effects other martial arts.

**Comment by KalevTait** [comment]
Unable to repro. Clicking 'show info' displays the combo list in chat.

**Comment by Rurik123** [comment]
Also unable to reproduce locally. Asked admin to try it live, in case it was one of the testmerges causing it, and it worked for them. No idea what caused this issue for me one round, but closing.
