### ISSUE TITLE
Dodgeball in-hand sprite shows a basketball

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#18154]
**Issue Description**:
Pick up a dodgeball and you'll start bouncing it on the floor, but it'll magically turn into a basketball! (just visually, i'm guessing there is no in-hand sprite for dodgeballs. Probably a good first issue for an aspiring spriter!)
![image](https://user-images.githubusercontent.com/32213277/176538125-5da2b0a3-d366-4e37-a0d7-55ce76a92645.png)
![image](https://user-images.githubusercontent.com/32213277/176538089-9980c01a-6b77-4225-acce-7fc525d42b0b.png)

**When did the problem start happening**:
June 29, 2022 during the Shepard Station test, but it's probably existed as long as dodgeballs have.

**Comment by Sirryan2002** [comment]
this is because dodgeballs inherit the item_state from their base type, simple fix would be to either null the item_state or make one for dodgeballs
