### ISSUE TITLE
Erika Surprise is called glass of ...what?

### ISSUE THREAD

**Issue by DanteR03** [ParadiseSS13/Paradise#18157]
**Issue Description**:

 That's Glass of ..what?. It is a tiny item.
The surprise is, it's green!
It contains:
40 units of Erika Surprise
It will transfer 10 units at a time.
 Glass of ..what? is almost full!

The description is clearly from Erika Surprise, but the title is still "Glass of What?"

**What did you expect to happen**: 

Expected the glass to be labeled as "Erika Surprise"

**Why is this bad/What are the consequences**:

It just doesn't look nice.

**Steps to reproduce the problem**:

Go to the bar
Mix 50 units of Erika Surprise
Pour in a glass

**Comment by PacifistDalek** [comment]
The issue is in:

> name = "Erika Surprise"
	id = "erikasurprise"
	description = "The surprise is, it's green!"
	reagent_state = LIQUID
	color = "#2E6671" // rgb: 46, 102, 113
	alcohol_perc = 0.2
	drink_icon = "erikasurprise"
	name = "Erika Surprise"

that second name should be drink_name
