### ISSUE TITLE
Trapped on Cargo Tug when handcuffed

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#1818]
I was messing around with a cargo train and Beepsky stunned me for some reason. I couldn't get off the tug so I resisted and it said, "You attempt to unbuckle yourself" so I was trapped in the seat. When I successfully unbuckled myself however I still could not get off the tug and resisting again repeated me needing to unbuckle myself. I'm stuck on the tug and can't open any doors either.

**Comment by tigercat2000** [comment]
This is almost certainly fixed by #2160
