### ISSUE TITLE
RCS doesnt work on delta, according to ahelps

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#18206]
**Issue Description**:
Map is delta, and apparently the RCS doesnt work

**What did you expect to happen**: 
The RCS to work

**What happened instead**:
It doesnt

**Why is this bad/What are the consequences**:
Cargo should be able to use their thing

**Steps to reproduce the problem**:
Try use RCS on delta

**When did the problem start happening**:
Unsure

**Extra information**:
N/A

**Comment by AffectedArc07** [comment]
> Title incorrect, RCS not RCD <3

In my defence:
- Next to eachother on the keyboard
- Fat fingers
- Both are ingame items

**Comment by Bm0n** [comment]
I just tested the RCS on a local server and it works just fine. What's broken about it?

**Comment by Sirryan2002** [comment]
confirmed as no longer an issue by multiple players
