### ISSUE TITLE
Prototype gun from Theta is a taser

### ISSUE THREAD

**Issue by TORE01** [ParadiseSS13/Paradise#18215]
**Issue Description**:

The prototype stun gun from Theta is firing taser shots. 

**What did you expect to happen**: 

We're moving away from insta stun so finding a taser on Theta is weird. 

**What happened instead**:

Frank got himself a taser. 

**Why is this bad/What are the consequences**:

Ranged insta stun can be found in space. 

**Steps to reproduce the problem**:

Go to Theta and grab the prototype stun gun. 

**When did the problem start happening**:

Its not really a bug. 

**Extra information**:

I wasnt sure where to inform of this so I made a bug report. 
Have a nice day.

**Comment by GDNgit** [comment]
Working as intended :tm:

Basically, one of the last tasers in the game, purposefully kept in

**Comment by Sirryan2002** [comment]
apparently this is intended

**Comment by TORE01** [comment]
Oh shit. I'm sorry
