### ISSUE TITLE
Revenant New Account Timer

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#1823]
Revenants do not have a new account timer, meaning 0 day old accounts can roll as a revenant. Not certain if this intentional. I was also told that the account timer (should be 14 days) for Shadowlings doesn't seem to be working, but have been unable to test it thus far.

@Fox-McCloud

**Comment by Robertha89** [comment]
From what I can see shadowling age counter works proper, but the revenant does not,

Tested by setting limits for shadowlings to a single player with an account age of 0, would not start.
Revenant tested both as admin and de-admined, got turned both times.
