### ISSUE TITLE
Small visual bug with the captains sword

### ISSUE THREAD

**Issue by Maturis** [ParadiseSS13/Paradise#18257]
**Issue Description**:
Can't see capitans sheathed sword when looking left.

**What did you expect to happen**: 
That I can see the sword just like when I look right.

**What happened instead**:
Instead of seeing it like when looking on the right you cannot see it when looking to the left

**Why is this bad/What are the consequences**:
Nothing major but it triggers my OCPD

**Steps to reproduce the problem**:
look to the left when the sword is sheathed

**When did the problem start happening**:
From the start

**Extra information**:

**Comment by Burzah** [comment]
I took a look at this today. Judging from the view on each side, the handle should probably be visible on the left somewhere at chest level as it extends extends past the chest on the right view. 

View Right
![dreamseeker_4Wp2BlmdRV](https://github.com/ParadiseSS13/Paradise/assets/116982774/adefda4d-d1b2-4506-afc6-f8f99dd17753)

View Left
![dreamseeker_rWZBmZGDaG](https://github.com/ParadiseSS13/Paradise/assets/116982774/a074ad2f-9b3b-46be-9a7e-f0e21f7cff23)

**Comment by Henri215** [comment]
Looks like other servers did fix this issue, one could grab the sprite from them.
https://github.com/ss220-space/Paradise/pull/3205

**Comment by Stealthii** [comment]
Nice find @Henri215 - I've raised #22155 to include this.
