### ISSUE TITLE
Incapacitated chair rotation attempt can be done at any range

### ISSUE THREAD

**Issue by kugamo** [ParadiseSS13/Paradise#18256]
**Issue Description**:

When incapacitated you can attempt to rotate any chair at any range and you get a message like it was a valid thing to do

**What did you expect to happen**: 

Check for adjacency before checking for incapacitation.

**What happened instead**:

You get messages to your chat like it was a valid thing to do.

**Why is this bad/What are the consequences**:

Its janky.

**Steps to reproduce the problem**:

Be incapacitated somehow, alt click any chair location

**When did the problem start happening**:

long time.

**Extra information**:

https://user-images.githubusercontent.com/16618648/177863477-2b1b0971-8d8d-4560-82e2-4fe02d175d16.mp4

**Comment by Peterrrrrrrr** [comment]
Hi there,

So, from what I can see, (I think I have misunderstood) it says 'You can't do that now' is this what you are referencing?

I have watched the video a lot and I cannot see what you are referring to here, please could you provide more detail?

Thanks
