### ISSUE TITLE
MetaStation's RND is isolated, it is very difficult to interact with science on this map

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#18267]
**Issue Description**:
I have been told before that it is a design choice to make science less isolated from the rest of the station, to avoid "the science bubble". The current (new?) RND design, on the other hand, reinforces isolation: if you, as a customer stand at the desk, it is impossible to see the RND scientist, and they probably can't see you either if they have skills on the top-left corner of their screen (I haven't tested the latter).

On this picture, there was a scientist at the Protolathe.

![image](https://user-images.githubusercontent.com/33333517/177966648-4a1ba8bf-aefe-4754-8b4f-e6eae14ba476.png)

**What did you expect to happen**: 
The RND scientist should be a few tiles from the desk to be able to properly communicate with people who order stuff from them.

**What happened instead**:
They never noticed anyone at the desk.

**Why is this bad/What are the consequences**:
RND, which is science's only point with the "outer world" is cut off, making science a 100% isolated on MetaStation.

**Steps to reproduce the problem**:
Check the map.

**When did the problem start happening**:
With the latest science remap on MetaStation.

**Extra information**:

**Comment by lewcc** [comment]
It'd be awfully nice to have a little reception bell or something there for people to ring

**Comment by Contrabang** [comment]
Metastation RND has been remapped
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/1254e1c9-b8d5-4ff8-933b-0409b6b62fc0)
