### ISSUE TITLE
Wallets don't show your ID

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#1827]
If you put your ID in a wallet and stick that in your id slot then you come out as Unknown. Not sure if this has any issues security-wise or if this is intended. Personally I'd like it to show who I am still. I think PDAs used to do that when you stuck your ID in them.

**Comment by Fox-McCloud** [comment]
I recall Mark looking into this, and it's an intended feature.

**Comment by Markolie** [comment]
I can't quite remember. We'll have to re-investigate.

**Comment by Plotron** [comment]
It was an intended feature of a wallet.

You cannot see an ID if it's hidden in something. Use damned logic.

In much the same way people can't see your money unless you show them the open wallet.

You swipe the wallet with the ID in it, not just the ID. Think metro.

**Comment by Robertha89** [comment]
Originally you where able to use it to show of an ID, while at the same time you could use it to hide extra id's for better door access. But thats like 3 years ago since that worked.

**Comment by taukausanake** [comment]
@Robertha89 I think I'd go for that, using it for multiple IDs. It's not an easy to come by item because you only get them from Hydro. I guess so long as the Show-ID verb still shows it, maybe shows (says) it inside a wallet but I don't make them anymore so I don't remember.
@Plotron Yeah, so long as you can still use the wallet containing the ID as an ID then I'm happy. Make sure the first ID in its inventory is the one used for verification just in case you have multiple because you're an assistant or Changeling

**Comment by Plotron** [comment]
@taukausanake You can make the wallet yourself. We've got the public garden.

**Comment by taukausanake** [comment]
@Plotron I forgot, it also has a biogenerator. I don't expect anyone in the garden to use it though and eventually watch all their plants die from lack of nutrients

**Comment by Robertha89** [comment]
From what I can see, this is intended, it still works as an id, but it hides it.

**Comment by taukausanake** [comment]
It looks like everything is working as intended. I took a peak at the code so maybe this is fine

**Comment by tigercat2000** [comment]
If this is a feature request, it should probably go onto the suggestions forum and be closed here.
