### ISSUE TITLE
Shuttle calls on red alert send the shuttle after 10 minutes rather than 5

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#18284]
**Issue Description**:
When the emergency shuttle is called during red alert, the shuttle shows up in 10 minutes rather than 5

**What did you expect to happen**: 
Shuttle shows up in 5 minutes

**What happened instead**:
Shuttles shows up in 10 minutes

**Why is this bad/What are the consequences**:
Shuttles should be showing up at the correct time

**Steps to reproduce the problem**:
1. Call shuttle on red alert
2. Wish you just called it on green

**When did the problem start happening**:
This started happening like a week ago, so it may be related to a currently TMed PR but I have no idea which one

**Comment by DeejayNite** [comment]
So yeah there is no proof of this, every shuttle call on red comes in 5 minutes.
What you're describing is likely the (I think intended) feature of calling red alert and then calling shuttle right after, if the station has been on red alert for a few minutes it becomes the 5 minute shuttle

**Comment by Sirryan2002** [comment]
I need somebody to test this a few times on a test server normally and then with a couple edge cases like jumping through alerts quickly and then calling.

**Comment by GDNgit** [comment]
Couple of things that could help replicate this issue:

1. All shuttle calls were made at least 25 minutes after Red was gotten
2. No adminshuttles were called, all were done through ic means (Done through AI, captain office console, and a built console), replacement id's were used for the latter 
3. Shuttle was not previously called in the round
4. We did actually have a shuttle call work once, but it was done right after Red, so something broke because of the timer @DeejayNite mentioned 

Mostly putting this down because I need to test it more later, just haven't had time (or the motivation to) yet

**Comment by GDNgit** [comment]
Appears to have been fixed
