### ISSUE TITLE
Blob Gases

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1829]
Some Blob gases affect people's ability to operate internally. Yet wearing a full hardsuit provides zero protection from that. I can understand things like flesh rending and fire blobs. But the there other ones were my character just collapsed and lungs were damaged. I don't get it if I choose to fight the blob in a super slow hardsuit and gas mask. Why should I not be offered some protection from those gases?

**Comment by Markolie** [comment]
@Fox-McCloud This really needs tweaking. Lung Destroyer blobs are so ridiculously overpowered: you get hit once, you're as good as dead because you'll collapse in a matter of seconds.

**Comment by Robertha89** [comment]
This is why you do not play races with lungs, superior slime people. also, the chems are applied on touch, not as gas, and personally i see this being balanced, as jumping in a puddle of biohazard is a bad idea. this is why guns are stronk.

**Comment by TheDZD** [comment]
Blob chems being able to penetrate gas masks, internals and hard suits is probably a **bit** much.

**Comment by Iamgoofball** [comment]
Gas mask and biosuit penetration on gas is a bug.

**Comment by Robertha89** [comment]
bio pen is a bug, at least for that chem.

**Comment by KasparoVy** [comment]
Sucks when you go through all the trouble of suiting up and putting on dat mask only to get skrekked by gas that would, ordinarily, be ineffective against you if someone dispersed it in grenade form
