### ISSUE TITLE
Connection drops a few seconds after joining the server

### ISSUE THREAD

**Issue by Beezbrax** [ParadiseSS13/Paradise#18305]
**Issue Description**: After joining the server I have a few seconds where I am able to interact with the game as normal before being given the message "You are either AFK, experiencing lag or the connection has closed."

**When did the problem start happening**: I had last played on the server a few years back and didn't have this issue, I've just started playing again this week and every attempt to connect to Paradise has resulted in this 

**Extra information**: Paradise is the only server I've joined that has had this problem so far. I've downgraded to the version of byond recommended in the chat but it didn't fix it. I've also made sure byond was allowed in my firewall and attempted running it in administrator mode with no difference.

**Comment by GDNgit** [comment]
Clear cache and then internet explorer cache
Join the discord if you can

**Comment by Beezbrax** [comment]
Yep it's working now, seems like clearing the byond cache was what did it.
