### ISSUE TITLE
statue animation bugged as hell

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#18331]
**Issue Description**:

Statue from animation does not wear off. It also currently is bugged, making 2 statues, one with no ckey, which if deleted pops out the original victims body catatonic

**What did you expect to happen**: 

none of the above, statueification wearing  off after being animated

**What happened instead**:

all of the above

**Why is this bad/What are the consequences**:

all of the above

**Steps to reproduce the problem**:

petrify with flesh to stone, animate, delete ckeyless statue.

**When did the problem start happening**:

Unknown

**Comment by DGamerL** [comment]
#23881 Fixed this, closing!
