### ISSUE TITLE
Runtime when Nar'sie goes off the station Z-level

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#18341]
**Issue Description**:
```dm
[2022-07-11T15:53:08] Runtime in narsie.dm,125: Cannot read null.z
   proc name: pickcultist (/obj/singularity/narsie/proc/pickcultist)
   src: Nar\'Sie (/obj/singularity/narsie/large)
   src.loc: space (23,139,8) (/turf/space)
   call stack:
   Nar\'Sie (/obj/singularity/narsie/large): pickcultist()
   Nar\'Sie (/obj/singularity/narsie/large): process(20)
   Objects (/datum/controller/subsystem/processing/obj): fire(1)
   Objects (/datum/controller/subsystem/processing/obj): ignite(1)
   Master (/datum/controller/master): RunQueue()
   Master (/datum/controller/master): Loop()
   Master (/datum/controller/master): StartProcessing(0)
```
Nar'sie floated off the z-level and then this runtime kept happening quite frequently, this was during a cultist round when nar'sie was summoned on the station z-level.

**Comment by Contrabang** [comment]
Looking at this, it seems this runtime was happening because some carbon in the GLOB.alive_mob_list wasnt on a turf, so in nullspace. Not sure how that happens, or it was that Narsie wasnt on a Z-level, which could happen I guess if theres something weird about moving between Z-levels.

**Comment by Sirryan2002** [comment]
nar-sie was on a z-level, just not z2
