### ISSUE TITLE
Crawling people show up all weird on photos

### ISSUE THREAD

**Issue by Inadvizable** [ParadiseSS13/Paradise#18368]
**Issue Description**:

Taking photos of crawling people makes them look like they have half-sunk into the floor.

**What did you expect to happen**: 

A picture of someone crawling on the floor after they got owned.

**What happened instead**:

![dreamseeker_sjEjDzSDxI](https://user-images.githubusercontent.com/107632879/178815363-054cc75f-cca0-46f8-948d-baf84ffe243a.png)

**Why is this bad/What are the consequences**:

Looks bad.

**Steps to reproduce the problem**:

1. Get camera
2. Get horizontal person
3. Click them

**When did the problem start happening**:

Probably crawling rework

**Extra information**:

I had burger today

**Comment by Contrabang** [comment]
Fixed
