### ISSUE TITLE
Book descriptions are messed up

### ISSUE THREAD

**Issue by Inadvizable** [ParadiseSS13/Paradise#18378]
**Issue Description**:

Some books (at the very least the corporate manuals) have error messages in their descriptions.

**What did you expect to happen**: 

Proper descriptions.

**What happened instead**:

![dreamseeker_AW44MYpHQg](https://user-images.githubusercontent.com/107632879/179006128-8cf96467-11e7-455b-aa68-6bb8e1fd6881.png)

**Why is this bad/What are the consequences**:

This is not an IC message where it should be.

**Steps to reproduce the problem**:

1. Click library computer
2. Go to the corporate section where you print pre-made manuals such as the SOP books
3. Print some
4. Examine them

**When did the problem start happening**:

Probably library rework?

**Extra information**:

the description told me to make this report and I am powerless to resist it

**Comment by Sirryan2002** [comment]
Yeah that's my fault, I forgot to ovveride the inherited descriptions on book since this was meant for base type books that players aren't actually supposed to get.
