### ISSUE TITLE
Bedsheets no longer show as 'cloaks' when worn in the backpack slot

### ISSUE THREAD

**Issue by Fraggloid** [ParadiseSS13/Paradise#18370]
**Issue Description**:
Bedsheets no longer show as 'cloaks' when worn in the backpack slot

**What did you expect to happen**: 
Player sprite updated to show the worn bedsheet

**What happened instead**:
Player sprite did not update to show the worn bedsheet

**Why is this bad/What are the consequences**:
My drip is lower than expected

**Steps to reproduce the problem**:
Wear bedsheet on backpack slot

**When did the problem start happening**:
First noticed roughly at time of this post

**Extra information**:

**Comment by Henri215** [comment]
Just tested and seems to be fixed.

![image](https://user-images.githubusercontent.com/77684085/191967684-36330149-83e0-40d9-a18f-2740575ea016.png)

**Comment by Fraggloid** [comment]
Some sheets still show incorrect sprites - showing as a plain white sheet rather than the coloured variant.
The mime sheet is one example of this.

**Comment by Henri215** [comment]
> 

![mimebed](https://user-images.githubusercontent.com/77684085/192029344-b8210d70-e1a3-43af-8371-83eba96405fd.png)
![red](https://user-images.githubusercontent.com/77684085/192029351-e854b963-8bc9-4390-bcdf-ccffbe88ef62.png)
![brown](https://user-images.githubusercontent.com/77684085/192029352-306b2ece-3c3e-4bb8-a548-51b6f18e9286.png)

Just tested all bedsheets and they got correct sprites (including mime one). One thing that could be improved is red and brown bedsheet (color tone looks way different from the icon)

**Comment by Fraggloid** [comment]
![image](https://user-images.githubusercontent.com/23267045/193427687-8afd9895-8492-4d46-a94a-504dba7bd6d1.png)
odd, still shows as white for me with mime sheet.
This sheet was dyed using a crayon, could that be the issue?
