### ISSUE TITLE
Hydroponics Trays Stop Flashing Their Status Lights

### ISSUE THREAD

**Issue by aaqe** [ParadiseSS13/Paradise#18394]
**Issue Description**:

Hydroponics trays randomly(?) stop showing status lights.

**What did you expect to happen**: 

To see whether a plant needs anything done.

**What happened instead**:

All lights were off.

**Why is this bad/What are the consequences**:

Nearly impossible to manage plants without golden trays.

**Steps to reproduce the problem**:

Do botany for 20min.

**When did the problem start happening**:

About the time of the death nettle balance.

**Extra information**:

**Comment by Vi3trice** [comment]
Caused by #17943. I wasn't returning a list of overlays, just a concatenated string so cases where multiple lights would show will simply have no lights.
