### ISSUE TITLE
honkbot has a runtime issue on creation/spawn

### ISSUE THREAD

**Issue by restedwaves** [ParadiseSS13/Paradise#18421]
**Issue Description**:

runtime upon creation or spawning of a honkbot

**What did you expect to happen**: 

honkbot gets made

**What happened instead**:

honkbot breakpointed the server i was testing on

**Why is this bad/What are the consequences**:

runtime

**Steps to reproduce the problem**:

spawn/create a honkbot

**When did the problem start happening**:

unknown

**Extra information**:

was using the main branch which i updated to yesterday

**Comment by Sirryan2002** [comment]
Honkbots need a refactor, their code is causing up to 3 different runtimes on production everytime they're in use.
