### ISSUE TITLE
Labor Camp space airlocks in cyberiad brig bolt open during graytide event

### ISSUE THREAD

**Issue by lewcc** [ParadiseSS13/Paradise#18423]
**Issue Description**:
The space airlocks to the labor shuttle get bolted open during the Graytide Virus event.

**What did you expect to happen**: 

They shouldn't be bolted open, it spaces the whole brig.

**What happened instead**:
The doors were bolted open, and the labor shuttle had to be called to fix them without AI intervention.

**Why is this bad/What are the consequences**:
Brig shouldn't necessarily be spaced from an event like this, and I don't think it used to be like this.

**Steps to reproduce the problem**:
- fire off the Graytide Virus Event on boxstation

**When did the problem start happening**:
Probably when Perma was remapped and things got reorganized. This might have still happened in the old brig but been prevented from spacing the brig by the dual airlocks. 

**Extra information**:

**Comment by S34NW** [comment]
However, this is caused by the area for this room being changed from `/area/security/prisonershuttle` to just being part of the brig.
