### ISSUE TITLE
Emitters beams deviate from a straight line over a long distance when pointing west

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1842]
While hilarious, I don't think this really fits in 2d spessmen

**Comment by TheDZD** [comment]
Title is not particularly descriptive. Emitters are inaccurate over a long range, as the particles seem to be deviating from a straight line.

**Comment by Alex6511** [comment]
Adjusted title

**Comment by TheDZD** [comment]
Can't seem to replicate this.

**Comment by Fox-McCloud** [comment]
this is a problem with ALL projectiles, not just emitters.
