### ISSUE TITLE
When Joining sever "Use Graphics hardware for displaying maps" turns on making game unplayable. 

### ISSUE THREAD

**Issue by Countderpula** [ParadiseSS13/Paradise#1843]
I am having an Issue when I join a game on this server. Whenever I join the Byond Setting "Use Graphics hardware for displaying maps" turns on (I always have it off) making SS13 unplayable. Does anyone know how to fix this?

**Comment by tigercat2000** [comment]
If the graphics hardware option is disabled, the lighting system breaks.

**Comment by TheDZD** [comment]
The lighting system does not worth without graphics hardware acceleration. I am assuming that for whatever reason the hardware acceleration does not work on your machine, which may well be a hardware issue.

**Comment by Taaketa** [comment]
Was there not a pull request recently put through that forces graphics hardware on, on join to the server?

**Comment by Spacemanspark** [comment]
Not all graphics cards can support that, @Taaketa.

**Comment by tigercat2000** [comment]
@Taaketa @Spacemanspark Yes, there was a PR, that's how it works. Issue here is, I am pretty sure @Countderpula is one with that type of card.
