### ISSUE TITLE
Cluwne mask becomes invisible after decapitation

### ISSUE THREAD

**Issue by FloFluoro** [ParadiseSS13/Paradise#18430]
**Issue Description**:
A cluwne's cursed clown mask becomes invisible if the cluwne is surgically decapitated and has their head reattached. They're still "wearing" the mask (which can be seen upon inspection), but it doesn't physically appear on their face.
![image](https://user-images.githubusercontent.com/3611705/179442966-c7b98b16-11f1-40ac-bd6e-7d9ec00108da.png)

**What did you expect to happen**: 
For the cluwne mask to reappear once the cluwne is revived, since his torment is inescapable

**What happened instead**:
The cluwne mask did not reappear

**Why is this bad/What are the consequences**:
Cluwning is meant to be irreversible and unconcealable 

**Steps to reproduce the problem**:
1. Cluwne someone
2. Surgically decapitate them
3. Reattach their head
4. Revive them
5. No mask!

**When did the problem start happening**:
N/A

**Extra information**:
honk

**Comment by lewcc** [comment]
Somehow this is even more cursed than the cluwne itself
