### ISSUE TITLE
Space Carps can smell sentience

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#18441]
**Issue Description**:
When you transfer consciousness to a space carp, other spacecarp suddenly start attacking you. 

**What did you expect to happen**: 
For them to ignore me the same as they ignore any other space carp they come across.

**What happened instead**:
I ded plz nerf

**Why is this bad/What are the consequences**:
Makes it much harder to become a space carp and fly around in space, plus it's very inconsistent.

**Steps to reproduce the problem**:
1. Get a sentience transfer potion from xenobio
2. Fling yourself into space
3. Slam into a pack of space carp
4. Transfer your conciousness to a space carp
5. Get nommed by not only the carps who were next to you already, but all carp you meet.

**Comment by PacifistDalek** [comment]
oops

**Comment by hal9000PR** [comment]
`to_chat(SM, "<span class='warning'>You are now [SM]. Your allegiances, alliances, and roles are still the same as they were prior to consciousness transfer!</span>")`

This is intended behaviour
