### ISSUE TITLE
UI oddity from too many chems in the Chem Dispenser 5000

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18532]
**Issue Description**:

Too many chemicals in the same container causes UI oddity.

**What did you expect to happen**: 

Text leaving the container looks bad.
Also maybe the beaker contents should be scrollable, rather than the dispensing options, seeing as one (almost) never changes in size while the other does?

**What happened instead**:

See image (looks off).

**Why is this bad/What are the consequences**:

Broken UI is "not nice", also it makes dispensing chemicals slightly annoying with the default size.

**Steps to reproduce the problem**:

1. Fill beaker with many different non reacting chemicals (my test has 19 chemicals, all from the "???" pill bottle)
2. Put beaker in the Chem Dispenser 5000.

**When did the problem start happening**:

I noticed it on the 24th of July 2022.

**Extra information**:

![image](https://user-images.githubusercontent.com/25958019/180633607-70e4fc70-2c84-42a3-b784-fc06d8660332.png)

**Comment by Sirryan2002** [comment]
this is going to be a rough fix, due to the nature of using flex displays, the chemical buttons section will not maintain a minimum height
