### ISSUE TITLE
Radiation Event Doesnt Affect Space

### ISSUE THREAD

**Issue by kugamo** [ParadiseSS13/Paradise#18539]
**Issue Description**:

The event in which a rad storm passes by the station, space tiles arent affected(at least visually)

**What did you expect to happen**: 

If its a rad storm only maint should be safe, not space too (isnt that where it comes from??)

**What happened instead**:

Space wasnt affected.

**Why is this bad/What are the consequences**:

You can completely avoid the storm with EVA gear

**Steps to reproduce the problem**:

cause the rad storm event to occur

**When did the problem start happening**:

unknown

**Extra information**:

![image](https://user-images.githubusercontent.com/16618648/180653821-6b8afd41-f565-41b8-a30a-03181c3b8b57.png)

I realize this might be balance, so all the explorers in space arent immediately irradiated. But I think at least the space on z level 2 should be affected. Doesnt make any sense otherwise, and plays better with it affecting space imho

**Comment by Sirryan2002** [comment]
this apparently used to work, so its a bug
