### ISSUE TITLE
Admin Freezes do not properly freeze Maintenance Drones & Simple Mobs

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#18553]
**Issue Description**:
When Admin freezing a Maintenance Drone or Simple Mobs, the player does not have their movement locked and vision blurred, they are still able to interact with the world and move freely.

**Why is this bad/What are the consequences**:
Admin anti-grief tools need to work

**Comment by Contrabang** [comment]
Turns out this literally applied to EVERYTHING but humans, neat.

**Comment by Groudonmaster** [comment]
This has been fixed a couple months ago?
