### ISSUE TITLE
Putting in blood into the pandemic with harm intent makes it runtime

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#18562]
**Issue Description**:

When putting in a beaker with blood into the pandemic it puts the beaker in and splashes the beaker's contents at the same time making it runtime.

**What did you expect to happen**: 

For it to either put in the beaker or just splash. Not both at the same time.

**What happened instead**:

beaker's contents were splashed and beaker was put into the machine at the same time

**Why is this bad/What are the consequences**:

Runtimes are scary :(

**Steps to reproduce the problem**:

1. Get a pandemic and a beaker
2. Put some blood into the beaker
3. turn on harm intent
4. Put the beaker into the pandemic

**When did the problem start happening**:

Noticed today 2022-07-25

**Extra information**:

Runtime:
`[2022-07-25T09:04:28] Runtime in pandemic.dm,110: Cannot execute null.GetDiseaseID().
   proc name: Topic (/obj/machinery/computer/pandemic/Topic)
   usr: [snip] (/mob/living/carbon/human)
   usr.loc: The floor (141,98,2) (/turf/simulated/floor/plasteel)`

**Comment by hal9000PR** [comment]
angrily SLAM the beaker into the machine that hard it runtimes

**Comment by Contrabang** [comment]
Fixed by #20504
