### ISSUE TITLE
If you ghost out from an exosuit that has a gun, you keep the targeting cursor

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#18596]
**Issue Description**:

Get into an exosuit with a gun, ghost out, now you are stuck with a targeting cursor.

https://user-images.githubusercontent.com/33333517/181215936-cb5b89d8-a1c0-459a-84ee-1f4012af7bc7.mp4

**What did you expect to happen**: 

The cursor to disappear.

**What happened instead**:

The cursor stayed.

**Why is this bad/What are the consequences**:

I no longer have a gun, I should not have a targeting cursor.

**Steps to reproduce the problem**:

1. Get into an exosuit with a gun
2. Switch to gun
3. Ghost out

**When did the problem start happening**:

Dunno.

**Extra information**:

Happened in round 32213.

**Comment by Sirryan2002** [comment]
duplicate of #17487
