### ISSUE TITLE
MULEs do not update their sprite once they drop off the crate on them

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#18603]
**Issue Description**:

Once they drop off their crate at the destination their sprite does not update. It looks as if the MULE still has a crate on it.

**What did you expect to happen**: 

Sprite to properly update

**What happened instead**:

It remained the same

**Why is this bad/What are the consequences**:

Its confusing when it looks like the MULE has a crate on it but actually doesn't

**Steps to reproduce the problem**:

1. Put crate on MULE.
2. Send it off somewhere
3. It comes back looking like it still has the crate.

**When did the problem start happening**:

Noticed today (2022-07-27)

**Extra information**:

**Comment by Sirryan2002** [comment]
caused by appearances pr
