### ISSUE TITLE
chainsaw not knocking down when it should

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#18614]
**Issue Description**:

chainsaw only rng knocks down, instead of always

**What did you expect to happen**: 

for the block checking code to make sure it only works when not blocked

**What happened instead**:

it never worked

**Why is this bad/What are the consequences**:

The knockdown should always happen

**Steps to reproduce the problem**:

chainsaw someone with good melee armor.
Not that they are not always knocked down

**When did the problem start happening**:

when I reworked it

**Extra information**:

line 630 in twohanded is the issue. It should return true if not blocked... but it is not doing that?

Hal and I could not find the issue

**Comment by Sirryan2002** [comment]
The chainsaw checks if it should weaken based on the return value from the chainsaw's attack() parent proc.
```dm
if(..())
    //weaken code
```
In the `obj/item/attack()` proc, the return value for it is decided in this line here where it calls attacked_by on the mob target.
```dm
. = M.attacked_by(src, user, def_zone)
```
herein lies the issue, when attacking carbon mobs this proc will be called
```dm
/mob/living/carbon/human/attacked_by
```
although the comment on that proc says it return true if the hit was succesful, it never actually has a `return 1` or `return TRUE` when there is a succesful/non-blocked hit, which means that in the case where we call the original parent proc it will NEVER return TRUE if there is a succesful hit which means it will never weaken.
