### ISSUE TITLE
Medical channel colour too close to common

### ISSUE THREAD

**Issue by Yukiona** [ParadiseSS13/Paradise#1861]
I find its hard to read the medical channel or notice it when new messages appear, its a kinda light blue colour which is hard to read against a light background anyway.

I guess its that colour because medbay is white/light blue but I think medbay would benefit from a the colour being a deep dark blue or a light red.

**Comment by BiberDark** [comment]
http://www.farbtabelle.at/farbtabelle/cyan/  -->  00cece or 00a5a5 could be good.
