### ISSUE TITLE
Completing the Vox sprite issues

### ISSUE THREAD

**Issue by SpaceTimeNow** [ParadiseSS13/Paradise#1862]
Since i have seen the work on the ill fitting jumpsuits for vox and since i almost exclusively play vox. I would like to list other sprite related issues I encountered while playing vox:

1. ~~Gloves:
We already did some work on vox gloves, most of them now display, but the latex gloves and the other new medical gloves (can't lookup the name right now) are still invisible. And if they are dyed then the dyed gloves are also not visible. Insulated gloves and black gloves work fine in the vanilla or dyed version.~~

2. Hats:
All the hats are ill fitting on vox. Probably because the Vox head is bigger and off center. Not sure if you can make the hats on vox appear slightly off center as well, but it would be nice. 

3. ~~Helmets:
The vox head sticks out of helmets that have a face cover. I would rather have the vox face cut off unrealisticly short to fit in the helmet, instead of half the head sticking through a riot helmet for exsample. Interesstingly enough the head only goes through the helmet if the vox looks to the West or East, if it looks directly at you then the face is already cut off to fit inside the helmet.~~

4. Security gas mask:
Not 100% positive on this one, but i believe the security gas mask are still invisible on vox. Maybe that changed, but it's unlikely.

5. ~~CE Hardsuit:
The CE hardsuit can be modified via a hardsuit modification kit to fit a vox, but there is no new sprite applied. The vox just get the vanilla sprite and the head and tail sticks out of the hardsuit. The atmos and engineering hardsuit can properly be modified an get a new sprite, just not the CEs Hardsuit.~~

6. Welding mask:
Welding mask is invisible. 
Note: Welding MASK, not helmet

**Comment by SpaceTimeNow** [comment]
6. Welding mask is invisible. Note: Welding MASK, not helmet

**Comment by KasparoVy** [comment]
5 was fixed

**Comment by KasparoVy** [comment]
If 3 refers to security/swat helmets, that was fixed as well

Does 6 refer to the new welding gas mask?

**Comment by SpaceTimeNow** [comment]
Yes 6 does refere to the new welding mask that goes into your mask slot.

**Comment by KasparoVy** [comment]
Got 1, I'll work on the masks next

**Comment by SpaceTimeNow** [comment]
Appreciate the effort, thanks a lot! No rush.

**Comment by Fox-McCloud** [comment]
mmmost of these have been addressed, I believe.
