### ISSUE TITLE
Secbelt sprite gets messed up when an ebola is put in

### ISSUE THREAD

**Issue by Inadvizable** [ParadiseSS13/Paradise#18638]
**Issue Description**:

Putting an energy bola on a belt hides some other stuff on it.

**What did you expect to happen**: 

For the sprite to display properly.

**What happened instead**:

![dreamseeker_hmrWSnYUPr](https://user-images.githubusercontent.com/107632879/181793945-e422c8f7-6429-4f2a-bae8-a0d58cd67dcc.gif)

**Why is this bad/What are the consequences**:

Looks bad.

**Steps to reproduce the problem**:

1. Get a belt with some stuff on it.
2. Put an energy bola on it.
3. Observe

**When did the problem start happening**:

Maybe #17943?

**Extra information**:

Did you know that even with seat belts people die all the time in car crashes? I thought that was interesting

**Comment by Inadvizable** [comment]
Testing a bit more. Stuff that is put in the belt AFTER the bola shows up properly.

**Comment by YoureNotTheSharpest** [comment]
this is the same for toolbelts and pocket fire extinguishers i think.
