### ISSUE TITLE
Some silver slime food turn invisible, and can be infinitely fed (but does nothing)

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18634]
**Issue Description**:

Some silver slime food turn invisible when you try to eat it, or force someone to eat it.
Canceling the force feeding gives you an invisible item that can be force fed unlimited times, but does nothing.

**What did you expect to happen**: 

Invisible items shouldn't exist.

**What happened instead**:

Item couldn't be eaten, and turned invisible.

**Why is this bad/What are the consequences**:

Its weird having invisible items that does nothing.

**Steps to reproduce the problem**:

1. Get a silver slime core.
2. Inject with plasma dust.
3. Some of the items spawned cant be eaten, try force feeding a monkey until one turns invisible without doing anything.
4. Cancel force feeding.
5. You now should have an item that can be feed as many times as you want, but does nothing.

**When did the problem start happening**:

The food that cant be eaten has been around forever, I thought it was a "funny" prank. I first found the other oddity today 29.07.2022.

**Extra information**:

**Comment by Sirryan2002** [comment]
it appears you're able to spawn in the base snack type
