### ISSUE TITLE
Mutations as an IPC

### ISSUE THREAD

**Issue by Kuzo1971** [ParadiseSS13/Paradise#18632]
**Issue Description**:

As an IPC, when the station-wide radiation hit, I mutated so I couldn't hear. I'm not actually sure if it was a mutation, but I lost hearing during it and Admins had to intervene to fix it, hence this report.

**What did you expect to happen**: 

I expected to not experience a difference from the radiation.

**What happened instead**:

I lost hearing which was only resolved by Admin influence.
**Why is this bad/What are the consequences**:

It's an important issue because it can't fixed without admins.

**Steps to reproduce the problem**:

The round event with the radiation started, I walked through the radiation and ended up losing hearing. It gave me a message when I did, I don't recall but I think it's the same one for the deaf mutation.

**When did the problem start happening**:

After the IPC changes, but I also never tried myself, someone said this was a new thing. 

**Extra information**:

**Comment by hal9000PR** [comment]
was fixed in commit hash 84693c2962e4ed15b424590b323ba195c8b1f4db
