### ISSUE TITLE
Rad Suit Prevents Genetics Injector Radiation

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#1865]
Exactly what it says on the can, used a lot by Cheaty McCheatersons.

**Comment by Robertha89** [comment]
really? that is fucking hillarious, and makes no logical sense.

**Comment by tigercat2000** [comment]
#1882 doesn't fix this. It fixes it for DNA modifiers, but this was about DNA injectors.

**Comment by Markolie** [comment]
Will investigate.
