### ISSUE TITLE
cham under shirt doesn't work

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#18675]
**Issue Description**:

cham under shirt doesn't work, no action to change it.

**What did you expect to happen**: 

To be able to change the look at it.

**What happened instead**:

Can't make it. Shirts stuck. SHIRTS STUCK, PLEASE!..

**Why is this bad/What are the consequences**:

People pay for the shirt, they should be able to use it

**Steps to reproduce the problem**:

Buy / spawn /obj/item/clothing/under/chameleon 

Note it does not work.

**When did the problem start happening**:

First seen now, tms are:
[#18460](https://github.com/ParadiseSS13/Paradise/pull/18460) - Atmospherics refactor @ a46020
[#18547](https://github.com/ParadiseSS13/Paradise/pull/18547) - Armour Refactor @ 653630

**Comment by Contrabang** [comment]
This happened 1-2 days ago too iirc, I completely forgot to report it

**Comment by Vi3trice** [comment]
It's occurring on master, has it ever worked? The action datum is actually in the object, but doesn't seem to get granted to the mob like other chameleon objects.
