### ISSUE TITLE
Patrol robots' engineering checkpoint in the Cyberiad is unreachable

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#18673]
**Issue Description**:

The patrol robots (beepsky, medibot) follow a series of checkpoints to move about the station. There's a checkpoint in front of the engineering foyer that is unreachable (due to the fenced garden, I suspect) that causes them to skip going down that hallway in their patrol route

**What did you expect to happen**: 

Robots patrol down the engineering (aft) hallway.

**What happened instead**:

They skip that hallway and recalculate the route when they hit their previous checkpoint.

![image](https://user-images.githubusercontent.com/7857084/182220954-77a5dcf3-bf6b-42dd-bd85-883bfcf51c06.png)

**Why is this bad/What are the consequences**:

Incomplete robot coverage. Not a huge deal but it'd be a simple fix.

**Steps to reproduce the problem**:

Watch robots patrolling.

**When did the problem start happening**:

Whenever the engi hallway/assembly line area was reworked to have that fenced in garden, I think.

**Extra information**:

**Comment by S34NW** [comment]
This is due to the railing being on the same turf as the beacon, moving it one tile to the East on prod makes bots work again.

**Comment by Sikroth** [comment]
If someone wants to try and figure out why a railing that's not blocking the way kills the pathfind, I was looking at code and found this bit in the pathfinding algorithm. Probably a behavior similar to directional windows could be added to railings? I haven't really tried so I dunno how doable or easy/complex it'd be, or if it'd solve this particular issue, but 🤷 :

https://github.com/ParadiseSS13/Paradise/blob/f0841b36294baccc2c5ac18678bd898defb8583d/code/defines/procs/AStar.dm#L168-L188
