### ISSUE TITLE
Traitor item - "Voice Changer" is currently broken

### ISSUE THREAD

**Issue by LufgtHuron** [ParadiseSS13/Paradise#1868]
No matter what setting are used on it, it always just stays as "the voice changer(as YourName)"

Tried it on, off, name without spaces or with, different ID's - nada. It never works. Kinda got my round ruined by it just now so here I am. 

Can be confirmed by @Elysian_Price.

**Comment by PsiOmegaDelta** [comment]
Paradise appears to have a similar voice changer as Bay now.
This means that it no longer cares about the carried id, but instead has two verbs for toggling on/off and for setting the voice to impersonate.

**Comment by LufgtHuron** [comment]
Yeah, I was trying that. And as I've said, tried it with all settings. Off or on, that name or the other. Even tried "Voice" as a name. 

It doesn't work.

**Comment by Markolie** [comment]
Ah, this is my fault. I'm returning the voice changer object instead of the name inserted into the voice changer. Will fix.

Thanks for the report.
