### ISSUE TITLE
Railings block pathfinding AI

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#18681]
**Issue Description**:

The pathfinding algorythm is unable to navigate through tiles with a railing, even if said railing is not blocking the way.

**What did you expect to happen**: 

Similar to directional windows, railings shouldn't stop bots or any pathfinding entity to move through the tile they're in.

**What happened instead**:

Dumb pathfinding behavior:

![image](https://user-images.githubusercontent.com/7857084/182409822-b4757113-b17a-4389-8649-b02fd05f525c.png)
![image](https://user-images.githubusercontent.com/7857084/182410824-3a38d90c-821a-4761-aa90-e6a5dfaa3a47.png)

**Why is this bad/What are the consequences**:

Makes medibots and other patrol bots dumb. Not sure if it has any effect on hostile mobs.

**Steps to reproduce the problem**:

Place railings and try to make a robot path/patrol through them.

**When did the problem start happening**:

Probably when railings were introduced in #16674

**Extra information**:

It's likely the reason behind #18673 too. I added a comment in that issue with a bit of code that seems related to the pathfinding and directional windows that might be a good place to start looking.

**Comment by S34NW** [comment]
Yeah, railings need an override similar to directional windows to fix this

**Comment by Sirryan2002** [comment]
A* moment
