### ISSUE TITLE
all spellblade enchantments are broken, bar bluespace

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#18686]
**Issue Description**:

all spellblade enchantments are broken, bar bluespace

**What did you expect to happen**: 

worky

**What happened instead**:

no worky

**Why is this bad/What are the consequences**:

should worky

**Steps to reproduce the problem**:

pick any enchantment but bluespace
wack
nothing but melee happens.

**When did the problem start happening**:

99% sure #18618 broke it

**Comment by hal9000PR** [comment]
ok this is a pretty bad bug, it means any melee weapon that relies on an `afterattack` override wont work unless its a ranged weapon. 

ideally, to make this work we would want every attack/afterattack to return two separate values. 0 if the attack fails, 1 if it is successful but shouldn't after attack, and 2 if it should after attack. or something similar.

rn it only afterattacks if it returns FALSE (or null) which it did before 18618.

a quick and dirty fix to this would be to make living and human attackbys return 2, then make 
```
		var/resolved = target.attackby(src, user, params)
		if(!resolved && target && !QDELETED(src))
			afterattack(target, user, 1, params) // 1: clicking something Adjacent
```
check if for (!resolved || resolved == 2) preferably as defines.
