### ISSUE TITLE
AI cannot access the holopads in sight/in its sat

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#18718]
**Issue Description**:

When the AI gets a call on a holopad to their chamber, they cannot answer it.

**What did you expect to happen**: 

For the AI to be able to answer the call so people can talk to them in their sat, or someway to deny the call.

**What happened instead**:

You cannot interact with the holopad, you will instead try to activate your own hologram on it.

**Why is this bad/What are the consequences**:

It goes beep beep and it annoys you until they stop trying to call you because they dont understand you can't pick up.

**Steps to reproduce the problem**:

\> Be AI
\> Get a call on a holopad in front of you 
![image](https://user-images.githubusercontent.com/91113370/183126532-09e0900c-85a6-48a0-bd30-58fbf2336756.png)

\> Suffer.

**When did the problem start happening**:

Always I believe? May just be an oversight

**Extra information**:

i hate holopads (next issue i make will be this)
![image](https://user-images.githubusercontent.com/91113370/183126112-04af6950-e2d6-45c5-8106-e076d7919923.png)

**Comment by Sirryan2002** [comment]
This is intended behavior
