### ISSUE TITLE
Holopads don't know when to stop talking when they call is not answered.

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#18719]
**Issue Description**:

Holopads don't know when to shut up when their call isn't answered, instead repeating the same line over and over.

**What did you expect to happen**: 

For them to say "No answer received." once.

**What happened instead**:

![image](https://user-images.githubusercontent.com/91113370/183127030-4c7dc654-adda-4681-9e37-b1995673650c.png)

**Why is this bad/What are the consequences**:

99% sure its a bug

**Steps to reproduce the problem**:

1. Call any holopad
2. Stand on the holopad while the call isnt recieved
3. Get spammed with text, about 1-2 second.

**When did the problem start happening**:

Unknown, wasnt doing this until sometime in the last few months I think

**Extra information**:

![image](https://user-images.githubusercontent.com/91113370/183126751-056d7dd9-9c5a-49ad-8dcf-985e74f4b349.png) User end
![image](https://user-images.githubusercontent.com/91113370/183126809-30cb62e0-7b96-4553-bf70-9a6452aca228.png) Area being called to end

**Comment by lewcc** [comment]
> 99% sure its a bug 

I think you can add an extra 1% to that, I don't think holopads should blast your ear out if you don't get through to someone :U
