### ISSUE TITLE
Kidan can't eat nymphs

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1872]

**Comment by Keilden** [comment]
Label this as top priority!

**Comment by Alex6511** [comment]
Yep

**Comment by FalseIncarnate** [comment]
Kidan code likely was not updated to use the new pathing (again)

I'll fix this (with a couple other things I need to fix) tonight

**Comment by FalseIncarnate** [comment]
Whoops, ignore that reference, accidentally typed the wrong issue number.

But if a maintainer sees this, please include the Cannot Reproduce tag unless someone else manages to reproduce and record this issue.
