### ISSUE TITLE
Grabs still longer than 3 seconds.

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#18730]
**Issue Description**:

Grabs are still longer than 3 seconds.

**What did you expect to happen**: 

The PR https://github.com/ParadiseSS13/Paradise/pull/18432 was supposed to reduce it to 3 seconds in order to make it so people aren't stuck standing still for an absurdly long period of time.

**What happened instead**:

Still stunned for a period longer than 3 seconds.

**When did the problem start happening**:

Noticed it during a vampire/tot round where I got neck grabbed by a vampire and an sec officer in two different scenarios earlier today on 8/6/22

**Comment by Sinestia** [comment]
think I know why, I'll try an PR this
