### ISSUE TITLE
New Medical/Science Maint Lacks Crates

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#18735]
**New Med/Sci maint lacks Crates**:

Despite a massive overhaul of Sci/Med Maint there are no crates at all.

**What did you expect to happen**: 

Cargo likes to nom nom crates.

**What happened instead**:

Some crates to exist in maint areas.

**Why is this bad/What are the consequences**:

Cargo likes to nom crates for points.

**Steps to reproduce the problem**:

Go to new Sci/med Maint on Cyberaid and find no crates.

**When did the problem start happening**:

New Sci/Med Maint.

**Extra information**:

Stick a few crates in, not a massive amount. Old Sci/med maint had 3 from memory.

**Comment by AffectedArc07** [comment]
Please file this on the PR itself https://github.com/ParadiseSS13/Paradise/pull/18468
