### ISSUE TITLE
Schrodinger's Gibber Corpse

### ISSUE THREAD

**Issue by KM-Catman** [ParadiseSS13/Paradise#18736]
**Problem Description**:
If you drag a body away from the gibber fast enough after putting it in, the body will not be in the gibber, but activating the gibber will still produce the person's meat.

**What did you expect to happen**: 
I was gibbing a person who wanted to be gibbed before leaving, I expected the body to disappear and for me to be able to gib it normally.

**What happened instead**:
The person I was going to gib was both in and out of the gibber, and after they Cryoed, I activated the gibber and got their meat despite them not technically being in the gibber.

**Why is this bad/What are the consequences:**
Theoretically could be used to make infinite meat, or potentially duplicate butcher items. 

**Steps to reproduce the problem**:
Grab a person who can be gibbered, Grab them and do the process of putting them in the gibber. As soon as you see them appear in the gibber animation, pull them away from it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
The person was SSD and asked for me to gib them personally before they left. I was a traitor on the standard gamemode. Nothing out of the ordinary was occurring.

**Comment by Sirryan2002** [comment]
gibber is peak shitcode
