### ISSUE TITLE
Using the instant summons spell with the immortality talisman active causes it to runtime

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#18755]
**Issue Description**:

Using the instant summons spell with the immortality talisman active causes it to runtime

**What did you expect to happen**: 

For it to not break and cause runtimes

**What happened instead**:

Game cried

**Why is this bad/What are the consequences**:

Runtime = bad

**Steps to reproduce the problem**:

Not exactly certain on the steps as it was discovered by someone else, but my guess is:
1. Give yourself talisman and spell
2. Select an item for summoning and mark it
3. Throw it
4. Activate talisman
5. Try to summon item

**When did the problem start happening**:

Noticed today (2022-09-08

**Extra information**:

Runtime:

> [2022-08-09T13:35:22] Runtime in summonitem.dm,98: Cannot read null.loc
   proc name: cast (/obj/effect/proc_holder/spell/summonitem/cast)
   usr: [snip] (/mob/living/carbon/human)
   usr.loc: The floor (129,137,2) (/turf/simulated/floor/plasteel)
   src: Recall the decayed regenerativ... (/obj/effect/proc_holder/spell/summonitem)
   src.loc: null
   call stack:
   Recall the decayed regenerativ... (/obj/effect/proc_holder/spell/summonitem): cast(/list (/list), [snip] (/mob/living/carbon/human))
   Recall the decayed regenerativ... (/obj/effect/proc_holder/spell/summonitem): perform(/list (/list), 1, [snip]  (/mob/living/carbon/human))
   Recall the decayed regenerativ... (/obj/effect/proc_holder/spell/summonitem): try perform(/list (/list), [snip] (/mob/living/carbon/human))
   Recall the decayed regenerativ... (/obj/effect/proc_holder/spell/summonitem): choose targets([snip] (/mob/living/carbon/human))
   Recall the decayed regenerativ... (/obj/effect/proc_holder/spell/summonitem): Click()
   Instant Summons (/datum/action/spell_action): Trigger()
   Instant Summons (/obj/screen/movable/action

**Comment by Sinestia** [comment]
>Give yourself talisman and spell
Select an item for summoning and mark it
Throw it
Activate talisman
Try to summon item


I followed these steps and did not receive an error

**Comment by Sinestia** [comment]
Likely fixed now that the spell will refuse to cast if it isn't provided a valid loc

**Comment by Dovixx** [comment]
Will be closing it as it should be fixed by the PR
