### ISSUE TITLE
Experimentor  summoning buckled pets anchors them in place

### ISSUE THREAD

**Issue by Amphigyies** [ParadiseSS13/Paradise#18778]
**Issue Description**:

An experimentor interaction with a strange objects that summons station pets does so even when the pet in question is buckled into a seat, freezing it in place at the experimentor.

**What did you expect to happen**: 

We expected the animal to be able to move about freely.

**What happened instead**:

The animal was rooted in place.

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

Have all the pets on station buckled down to a seat, and use the experimentor until one is teleported.

**When did the problem start happening**:

This occurred today, not sure of any other instances.

**Extra information**:

**Comment by streather** [comment]
I noticed this a few weeks ago, forgot to create a bug report.

It's worth noting they are anchored to the spot, you can't drag them, grab them and throw them and even if you dismantle the experimentor they're still stuck there.
