### ISSUE TITLE
Shadowling: Parity

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1877]
Just a few things that we're not at parity yet with Shadowlings, from TG:

- Light damage+lumcount to trigger said damage (though this may be different with our lighting system): https://github.com/tgstation/-tg-station/blob/4b7c6ee140fe7ccc71072bb01ef3e2a87d7e8de3/code/game/gamemodes/shadowling/shadowling.dm#L238
- reduced burn damage modifier: https://github.com/tgstation/-tg-station/commit/c619e290485f1c623c63aedfb330d25080e8b80f
- lack of Weakeyes var: https://github.com/tgstation/-tg-station/pull/8291
- SpaceSuit/helmet aren't space proof: https://github.com/tgstation/-tg-station/pull/11186
- Shadowlings aren't properly radiation immune (giving them RAD_ABSORB would be bad though)
- Shadowlings dust upon death and have NO_SCAN for some reason.
- Shadowlings slowly become hungry.

**Comment by tigercat2000** [comment]
Um, I'm pretty sure they do take light damage, using the appropriate stuff for our lighting.

**Comment by Fox-McCloud** [comment]
This isn't a bug report; of course they take light damage; this is a "lack of parity" report. It was requested this be posted here instead of on Skype.

**Comment by tigercat2000** [comment]
That doesn't make.. much sense to me to include, but okay then.
