### ISSUE TITLE
Languages are stored in the torso, not the brain/mind.

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18785]
**Issue Description**:

Putting your head on a monkey's body makes you forget all languages except chimpanzee.

**What did you expect to happen**: 

To remember the languages you've "learnt" during your life.

**What happened instead**:

All languages forgotten, chimpanzee learnt.

**Why is this bad/What are the consequences**:

When transferring your brain, you should keep all knowledge you had. The torso has no organs capable of storing knowledge.

**Steps to reproduce the problem**:

1. Amputate a monkeys head.
2. Amputate your head.
3. Place your head on the monkeys body.
4. Revive.

**When did the problem start happening**:

Noticed it today 12.08.2022.

**Extra information**:

Chimpanzee is its own language, rather than a way of speaking (like Swedish/chav), which means that both you and someone you don't share a language with (ashwalker?) can turn into monkeys and suddenly understand each other perfectly fine, while you cant understand people you've worked with. 

Baking this speech pattern into the 55 gene that differentiates between human and monkey might be a fix, not sure how that would affect AIs or talking to holoparasites occupying your body though. Or keeping all languages when doing this transfer.

**Comment by Sirryan2002** [comment]
duplicate issue of #6228
