### ISSUE TITLE
Can't make Scanner or Sleeper face up or down

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#18797]
Wrenching a Body Scanner or Sleeper cycles it between facing right and left, but not up and down.

**What did you expect to happen**: 
It'd rotate

**What happened instead**:
Wiggle Left and Right, no Up and Down

**Why is this bad/What are the consequences**:
Makes me sad when I try to renovate medbay

**Steps to reproduce the problem**:
Wrench one of the above. Maybe Cryo sleepers too, I didn't check.

**When did the problem start happening**:
2022-08-12 was when I fist noticed it.

**Comment by Sirryan2002** [comment]
I blame sleeper shitcode for this
