### ISSUE TITLE
Mentors can see admin (R)LOOC

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1879]

**Comment by Spacemanspark** [comment]
Perhaps intentional.

**Comment by Robertha89** [comment]
#1866

**Comment by Alex6511** [comment]
I don't think you get it, they can see ONLY admins talking in LOOC globally, that's not intentional.

**Comment by Markolie** [comment]
That fix is not live yet.

**Comment by Spacemanspark** [comment]
I thought they could see all LOOC, Johannhawk has told me as much.

**Comment by Alex6511** [comment]
@Markolie Are you sure? The fix implies admins can't see (R)LOOC, I was told by admins prior to reporting this that (R)LOOC is working.
