### ISSUE TITLE
Misleading structural enzymes sprite when it comes to dart pistols

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18844]
**Issue Description**:

The structural enzyme (SE) sprite looks like a syringe, and on use turns into one, making you think it can be placed in the dart pistol. Not being able to place the SE "syringe" in a dart pistol is intentional.

**What did you expect to happen**: 

To see a different sprite.

**What happened instead**:

Nothing, not even an error message.

**Why is this bad/What are the consequences**:

Its confusing that the SE uses a syringe sprite and acts like one, but cant be placed in something that shoots syringes.

**Steps to reproduce the problem**:

1. Get a SE syringe from genetics.
2. Try to load it into a dart pistol.

**When did the problem start happening**:

Tested first today, 17.08.2022, but heard about it a few days ago.

**Extra information**:

Firing SE syringes out of a dart pistol is way too strong, so it is intentional that this cant be done. However, the sprite should reflect this.

**Comment by Sirryan2002** [comment]
this is really a feature request/suggestion
