### ISSUE TITLE
Monkeys cant inject themselves with structural enzymes.

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18843]
**Issue Description**:

If you are a monkey you can't inject yourself with a structural enzyme syringe (SE), despite being able to hold it, and being able to inject yourself with normal syringes. You dont get any error messages either.

**What did you expect to happen**: 

Either to be able to inject yourself with the SE, or an error message.

**What happened instead**:

Nothing, not even an error.

**Why is this bad/What are the consequences**:

The SE injector looks like a syringe, so it is confusing being able to inject yourself with one but not the other. Also as a monkey it is not possible to turn back to human with an SE or continue experimenting on yourself/give yourself powers.

**Steps to reproduce the problem**:

1. Get a SE syringe from genetics that will turn you into monkey. (block 55 set above or at 802)
2. Get one that will turn you back to a human. (block 55 set to below 802)
3. Inject yourself with the first syringe to become a monkey.
4. Try to inject yourself with the syringe that makes you a human.

**When did the problem start happening**:

Noticed it a few days ago.

**Extra information**:

Opening another issue relating to the SE syringes, a sprite change and an error message might fix both, if intentional.

**Comment by Burzah** [comment]
After looking over the issue and speaking to some members of the design team, this seems to be working as intended. Currently only advanced tool users can use DNA Injectors. Thank you for opening the report.
