### ISSUE TITLE
dna.species.armor doesnt work

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#18853]
**Issue Description**:

Armor on dna.species doesnt work.

**What did you expect to happen**: 

Golems / people who took dna vault / anything else that adds armor to a species would take less damge (note this has not been converted to the new armor system, and needs to, golems values need to be increased.

**What happened instead**:

Golems / dna vault people take full damage.

**Why is this bad/What are the consequences**:

Golems really should not be taking full damage. A dna vault modifier being useless is bad.

**Steps to reproduce the problem**:

spawn golem.
shoot golem. 
Wow, 20 damage!

**When did the problem start happening**:

probably  #18547

**Comment by Sirryan2002** [comment]
@Edan52 
Could you look into this?
