### ISSUE TITLE
Objects that need qdel'ing

### ISSUE THREAD

**Issue by Markolie** [ParadiseSS13/Paradise#1886]
Just to keep track of it:

/mob/new_player
/obj/screen/storage
/obj/screen/close
/obj/item/device/sensor_device
/obj/item/device/assembly/signaler
/obj/item/weapon/storage/internal
/obj/item/device/radio/headset
/obj/item/organ/external/chest
/obj/item/organ/external/groin
/obj/item/organ/external/arm
/obj/item/organ/external/arm/right
/obj/item/organ/external/leg
/obj/item/organ/external/leg/right
/obj/item/weapon/reagent_containers/food/snacks/monkeycube/wrapped
/obj/screen/grab
/obj/effect/equip_e/human
/obj/item/clothing/accessory/petcollar
/obj/item/weapon/reagent_containers/food/snacks/monkeycube/wrapped/farwacube
/obj/item/mecha_parts/mecha_equipment/tool/syringe_gun
/obj/effect/decal/cleanable/blood/drip
/obj/effect/proc_holder/spell/aoe_turf/boo
/mob/dead/observer
/obj/item/device/encryptionkey/heads/ai_integrated
/obj/item/device/radio/headset/heads/ai_integrated
/obj/structure/spacepod_frame
/obj/item/device/radio
/obj/item/clothing/head/surgery/blue
/obj/item/clothing/suit/storage/labcoat
/obj/item/clothing/suit/storage/labcoat/chemist
/obj/item/weapon/book/manual/barman_recipes
/obj/effect/decal/cleanable/blood/tracks/footprints
/obj/effect/decal/cleanable/blood/splatter
/obj/item/mecha_parts/chassis/ripley
/atom/movable/lighting_overlay
/mob/aiEye
/obj/item/device/radio/beacon
/obj/item/clothing/suit/chickensuit
/obj/item/weapon/stock_parts/micro_laser
/obj/item/weapon/stock_parts/matter_bin
/obj/item/weapon/stock_parts/manipulator
/obj/item/weapon/storage/part_replacer
/obj/item/weapon/bananapeel
/obj/item/clothing/mask/breath
/obj/item/device/radio/headset/headset_med
/obj/item/device/radio/headset/headset_sci
/obj/item/device/flashlight
/obj/item/device/pda/warden
/obj/item/weapon/ore/iron
/obj/item/organ/external/hand
/obj/item/organ/external/foot/right
/obj/item/asteroid/hivelord_core
/obj/item/device/radio/headset/headset_sec/alt
/obj/item/mecha_parts/chassis/phazon
/obj/machinery/door/airlock/glass_engineering
/obj/effect/overlay/holograph
/obj/item/weapon/reagent_containers/glass/beaker/noreact
/obj/item/weapon/reagent_containers/food/drinks/weightloss
/obj/item/weapon/reagent_containers/food/snacks/sliceable/pizza/margherita
/obj/item/weapon/reagent_containers/glass/fertilizer/rh
/obj/item/weapon/reagent_containers/glass/fertilizer/l4z
/obj/item/weapon/reagent_containers/food/snacks/hotdog
/obj/singularity
/obj/item/weapon/reagent_containers/food/drinks/chicken_soup
/obj/item/weapon/reagent_containers/pill/patch/styptic
/obj/item/weapon/reagent_containers/hypospray/autoinjector
/obj/item/weapon/reagent_containers/food/condiment/pack/ketchup
/obj/item/weapon/reagent_containers/food/snacks/grown
/obj/item/weapon/reagent_containers/food/snacks/cheesewedge
/obj/item/weapon/reagent_containers/pill
/obj/item/weapon/reagent_containers/spray/cleaner
/obj/item/weapon/reagent_containers/food/drinks/cans/cola
/obj/item/weapon/reagent_containers/food/drinks/cans/thirteenloko
/obj/item/organ/brain
/obj/item/weapon/reagent_containers/pill/patch
/obj/item/clothing/mask/cigarette
/obj/effect/bmode/builddir
/obj/effect/bmode/buildhelp
/obj/effect/bmode/buildmode
/obj/effect/bmode/buildquit
/obj/item/stack/sheet/metal
/obj/item/weapon/reagent_containers/food/snacks/egg
/obj/item/organ/external/hand/right
/obj/item/organ/external/foot
/obj/item/device/flashlight/pen
/obj/item/weapon/reagent_containers/food/snacks/donkpocket
/obj/item/weapon/reagent_containers/glass/bottle/ether
/obj/item/weapon/reagent_containers/food/drinks/cans/space_up
/obj/item/weapon/reagent_containers/glass/bottle/charcoal
/obj/item/weapon/reagent_containers/food/snacks/flour
/obj/item/weapon/reagent_containers/pill/patch/silver_sulf
/obj/item/weapon/reagent_containers/food/snacks/margheritaslice
/obj/item/weapon/reagent_containers/pill/charcoal
/obj/item/weapon/tank/emergency_oxygen
/obj/item/weapon/reagent_containers/food/snacks/meat/monkey
/obj/item/weapon/reagent_containers/syringe
/obj/item/weapon/reagent_containers/food/snacks/spagetti
/obj/item/device/radio/headset/headset_eng
/obj/item/weapon/tank/emergency_oxygen/engi
/obj/item/weapon/reagent_containers/food/snacks/pastatomato
/obj/item/mecha_parts/chassis/odysseus
/obj/item/weapon/reagent_containers/food/snacks/syndicake
/obj/effect/mist
/obj/machinery/atmospherics/unary/vent_pump
/obj/item/mecha_parts/chassis/durand
/obj/machinery/alarm
/obj/machinery/atmospherics/pipe/simple/hidden/supply
/obj/machinery/door/airlock/maintenance
/obj/item/weapon/reagent_containers/food/snacks/donut/normal
/obj/machinery/atmospherics/unary/vent_scrubber
/obj/machinery/status_display
/obj/machinery/atmospherics/pipe/simple/hidden/scrubbers
/obj/item/weapon/grab
/obj/machinery/autolathe
/obj/machinery/atmospherics/pipe/manifold/hidden/scrubbers
/obj/item/device/radio/borg
/obj/machinery/camera
/obj/item/weapon/reagent_containers/borghypo
/obj/machinery/atmospherics/pipe/manifold/hidden/supply
/obj/item/organ/external/chest/ipc
/obj/item/organ/external/groin/ipc
/obj/item/organ/external/arm/ipc
/obj/item/organ/external/arm/right/ipc
/obj/item/organ/external/leg/ipc
/obj/item/organ/external/leg/right/ipc
/obj/effect/proc_holder/spell/targeted/shadowling_hatch
/obj/machinery/optable
/obj/item/weapon/reagent_containers/food/drinks/drinkingglass
/obj/item/weapon/reagent_containers/pill/salicylic
/obj/effect/blob/core
/obj/item/weapon/reagent_containers/food/snacks/taco
/obj/item/device/radio/headset/headset_service
/obj/item/weapon/tank/emergency_oxygen/vox
/obj/item/weapon/reagent_containers/glass/beaker
/obj/item/weapon/reagent_containers/glass/beaker/large
/obj/machinery/chem_dispenser/constructable
/obj/item/device/t_scanner
/obj/item/mecha_parts/chassis/gygax
/obj/item/device/flash/cyborg
/obj/item/clothing/mask/gas/sechailer/cyborg
/obj/item/weapon/restraints/handcuffs/cable/zipties/cyborg
/obj/item/taperoll/police
/obj/item/weapon/stock_parts/cell
/obj/item/weapon/gun/energy/disabler/cyborg
/obj/item/weapon/stock_parts/cell/high
/obj/item/weapon/melee/baton/loaded/robot
/obj/item/weapon/reagent_containers/pill/salbutamol
/obj/item/device/encryptionkey/headset_service
/obj/item/radio/integrated/signal
/obj/item/weapon/reagent_containers/food/drinks/bottle/bottleofnothing
/obj/item/organ/external/head

**Comment by Spacemanspark** [comment]
That's a lot of items.

**Comment by Fox-McCloud** [comment]
which list are these in?

**Comment by Markolie** [comment]
It's the (GC) Hard Del List verb under debug (or Show Del Info, which has a tabled list).

**Comment by Fox-McCloud** [comment]
Ahh...so items that are being qdel'd but are failing to be GC'd properly (because of dangling references).

yuckkkk

**Comment by tigercat2000** [comment]
Mobs aren't a worry, they should be intentionally hard-delling.

**Comment by Fox-McCloud** [comment]
We should probably log this to the runtime log like TG does, so it's easier to get a grasp over which things crop up the most and what they are.
