### ISSUE TITLE
Genetics lab APC is invisible on Boxstation

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#18861]
**Issue Description**:

The APC is invisible there due to the layer of the wall it is on is 3 instead of a regular wall layer, which is 2.

**What did you expect to happen**: 

For it to be visible

**What happened instead**:

It wasn't there

**Why is this bad/What are the consequences**:

Stuff you can't see is bad

**Steps to reproduce the problem**:

1. Boot up a server and make sure box is loaded
2. Head to genetics lab and see the APC is invisible
3. Realize the APC layer is 2.9 and the wall its on is 3 for whatever reason

**When did the problem start happening**:

Ever since the med/sci remap PR #18468 if I had to guess

**Extra information**:

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/185611105-a8615114-28be-4906-b217-b8abc85e916c.png)
![image](https://user-images.githubusercontent.com/12197162/185611121-865c8263-be09-443a-876c-10776de0290e.png)

Wall and APC are not varedited, this is not a mapping issue.

**Comment by S34NW** [comment]
![image](https://user-images.githubusercontent.com/12197162/185611642-649aaa35-a535-480f-bd5e-d2873e60b871.png)
APC is visible in-game

**Comment by Dovixx** [comment]
the APC is fine, I am just dumb
