### ISSUE TITLE
Emagged deep fryer gets locked up from  frying primed grenades

### ISSUE THREAD

**Issue by Niteark** [ParadiseSS13/Paradise#18871]
**Issue Description**:
Priming a grenade and then deep frying it with an emagged deep fryer will allow the grenade to detonate normally, but the fryer will become stuck in the process of deep frying until deconstructed.

**What did you expect to happen**: 
The grenade either should cease to function normally or the trigger of it being detonated should cause the deep frying to end prematurely 

**What happened instead**:
Deep Fryer softlock dumbness

**Why is this bad/What are the consequences**:
Is bug and weird, also it requires you to decon the fryer which unemaggs it, which can be annoying if you lose the emag or if it was someone else who emagged it

**Steps to reproduce the problem**:
Emag deep fryer, get grenade and prime it in hand, place grenade into deep fryer

**When did the problem start happening**:
Prolly when the deep fry emag PR happened

**Extra information**:
The specific grenade used was a banana grenade

**Comment by FloFluoro** [comment]
Thanks for the report, will be fixing this shortly.
