### ISSUE TITLE
Photocopy machines are really really funny and let you cheese simple mobs

### ISSUE THREAD

**Issue by Niteark** [ParadiseSS13/Paradise#18875]
**Issue Description**:
You can click and drag ANY mob onto a photocopy machine, including mobs not intended to be moveable (Terror spiders, Megafauna Overwhelming force vampires ect.) You can also use an emagged copy machine to scan the ass of simple mobs and this does NOT consume toner letting you spam it rapidly, allowing you in theory to be able to kill mobs like prince of terror or BDM in roughly 2 seconds.

**What did you expect to happen**: 
You can not normally lift up an entire ash drake, but if you have a nearby copy machine you sure as hell can, which considering you can unwrench and drag them around wherever you want makes this abuseable. (Pulling terrors off vents for example)

**What happened instead**:
Mobs that are intended to be unmovable should not be able to be thrown onto a copy machine

**Why is this bad/What are the consequences**:
Powergaming vs terrors, cheesing simple mobs with hundreds of free damage per second.

**Steps to reproduce the problem**:
Just click and drag any mob onto a copy machine, they will be moved regardless.
![Screenshot_78](https://user-images.githubusercontent.com/66515703/185798371-eed55d9a-083f-4000-99f9-2260835ff2ab.png)
![Screenshot_77](https://user-images.githubusercontent.com/66515703/185798373-07040411-afa8-4b88-a6bf-127d5aa6472c.png)

**When did the problem start happening**:
Who knows

**Extra information**:

**Comment by alex-gh** [comment]
>  Powergaming vs terrors, cheesing simple mobs with hundreds of free damage per second.

Can't reproduce this one. Sure I can drag and drop them onto the copier, but no damage.

**Comment by Niteark** [comment]
To do damage it has to be emagged and you have to "copy" their ass while the mob is on it

**Comment by alex-gh** [comment]
Yep, reproduced it. Had to spam it a little for the spider to actually die.
Committing a fix right now.
