### ISSUE TITLE
Hunger Bar Disappears

### ISSUE THREAD

**Issue by matttheficus** [ParadiseSS13/Paradise#18886]
**Issue Description**:

The hunger bar does not show at all.

**What did you expect to happen**: 

The hunger bar to show.

**What happened instead**:

There was no hunger bar, didnt notice my hunger being low until I slowed down due to it.

**Why is this bad/What are the consequences**:

Going hungry randomly is bad.

**Steps to reproduce the problem**:

There doesnt appear to be a way to force it, asked via OOC and some people said it appears and some say it doesnt.

**When did the problem start happening**:

Recently, only noticed it today. Perhaps came due to #18646 due to it being a HUD change? Unsure.

**Extra information**:

Round: 32557

**Comment by SteelSlayer** [comment]
When I spawn in with a character I get the hunger icon, and messing around with giving doesn't cause any problems. Going to need more information here on when the hunger icon disappeared, and what you were doing at the time.

**Comment by ItsMarmite** [comment]
I had this issue last night, so did another player. Definitely not an isolated issue.

**Comment by SteelSlayer** [comment]
Yep, confirmed that this is an issue, and I've got the above PR fixing it. Thanks for the report.

**Comment by 1080pCat** [comment]
Still an issue.

**Comment by SteelSlayer** [comment]
Does the hunger icon disappear after you've given or received a given item? Or is just missing at round start?

**Comment by KittyNoodle** [comment]
had it happen to me recently, it broke ALL alerts, not just hunger
