### ISSUE TITLE
Cargo has no power? Is it mice? No, someone forgot a wire.

### ISSUE THREAD

**Issue by Komrad822** [ParadiseSS13/Paradise#18893]
**Issue Description**:

Each shift cargo loses power on box map.

**What did you expect to happen**: 

Cargo not losing power each shift after I kill every mouse.

**What happened instead**:

Its not mice actually, its a missing wire!

**Why is this bad/What are the consequences**:

Cargo losing power during a NUKIES round... or round start BLOB or just in general due to a missing wire is not fun.

**Steps to reproduce the problem**:

1. Spawn on cyberiad
2. Stare at the missing wire in maints outside mining dock
3. Contemplate why you play this game.

**When did the problem start happening**:

Likely the mining maints rework

**Extra information**:

![issues 2](https://user-images.githubusercontent.com/94168850/186798157-5ad68ad7-babd-46cd-a18e-a7fc38b98de5.png)
![10e5a97678942b97126122ae57eca5ef](https://user-images.githubusercontent.com/94168850/186798166-c6ad285a-8a43-4659-9e49-837a1dd3aa1b.png)

**Comment by LightFire53** [comment]
Gets fixed in #18889
