### ISSUE TITLE
Surgery starting in the wrong situations

### ISSUE THREAD

**Issue by Mooballoono** [ParadiseSS13/Paradise#18900]
**Issue Description**: 
Surgery starting when fighting with any tool listed for ghetto surgery while not on a table

**What did you expect to happen**: 
to just hit people with the weapon

**What happened instead**:
i hit them on harm intent then it reverted to help intent and constantly started surgery with every click 

**Why is this bad/What are the consequences**:
it causes big issues with cult because their knife starts surgery too and its also just a big problem for antag as a whole including cling

**Steps to reproduce the problem**:
attack someone with a cult knife/fireaxe/any bladed weapon on help intent

**When did the problem start happening**:
after the surgery refactors PR was merged

**Extra information**:
nope

**Comment by AffectedArc07** [comment]
Please file this on the PR https://github.com/ParadiseSS13/Paradise/pull/18325
