### ISSUE TITLE
You can feed simple mobs with condiment bottles

### ISSUE THREAD

**Issue by Niteark** [ParadiseSS13/Paradise#18915]
**Issue Description**:
Using condiment bottles you can force feed simple mobs, this is something you normally cannot do with other containers and the reagent is in fact not consumed despite the feeding message and sound effect.

**What did you expect to happen**: 
Things should be consistent

**What happened instead**:
![Screenshot_93](https://user-images.githubusercontent.com/66515703/187081433-59c68931-bee9-4cd0-a7da-a564ea236fd0.png)

**Why is this bad/What are the consequences**:
It is just weird

**Steps to reproduce the problem**:
Fill condiment bottle with whatever, I used whiskey and click on simple mob to feed it

**When did the problem start happening**:
Noticed today

**Extra information**:

**Comment by PacifistDalek** [comment]
![image](https://user-images.githubusercontent.com/32213277/187281686-c711c62f-37fe-4a9a-8805-40ebf98477dd.jpeg)
