### ISSUE TITLE
Soda can alt click shakes can and opens transfer amount window

### ISSUE THREAD

**Issue by Freakycrafter** [ParadiseSS13/Paradise#18918]
**Issue Description**: When alt clicking a soda can you shake it up and then, after shaking or after another alt click while still shaking the transfer amount window opens.

**What did you expect to happen**: That i would simply shake the can.

**What happened instead**: I shook the can and then the window for the transfer amount opened.

**Why is this bad/What are the consequences**: It seems like unintended behaviour.

**Steps to reproduce the problem**: Take a soda can, shake it up by alt clicking it.

**When did the problem start happening**: Shortly before i wrote this ticket (though i havent exactly shaken up a lot of soda cans before that)

**Extra information**: Is most likely related to #18431, as it's added the alt clicking behaviour for reagent containers.

**Comment by Sirryan2002** [comment]
@CinnamonSnowball
