### ISSUE TITLE
Standard Atmos filter setting are fucked

### ISSUE THREAD

**Issue by SpaceTimeNow** [ParadiseSS13/Paradise#1893]
When you hit Filtering mode on a atmos alarm then the scrubber setting get all fucked up.
![qpq6v2j](https://cloud.githubusercontent.com/assets/10059163/9563677/70d4338e-4e8c-11e5-8ed6-0bfdde7f9615.png)

Ultimate dust station mode.

**Comment by Markolie** [comment]
Which ones is it supposed to filter?

**Comment by SpaceTimeNow** [comment]
The changes seem fine to me!

The only issue that is left seems to be a balance one:
"tox_scrub" and "n2o_scrub" are now allways forced to 0 when hit normal filter mode even if they were manually set to 1 before.

I think that's the case, because the super scrub mode sets all bad gases to 1 and returning from super scrub mode to normal makes the scrubbers less efficient and only scrub CO2.

The best method in my opinon would be to save "tox_scrub", "n2o_scrub" settings when leaving filtering and reapply the following when re-entering filtering mode:

"o2_scrub" = 0 if normal room, 1 if vox room
"n2_scrub" = 0
"co2_scrub" = 1
"tox_scrub" = saved "tox_scrub" value
"n2o_scrub" = saved "n2o_scrub" value

**Comment by Markolie** [comment]
It shall be done.
