### ISSUE TITLE
Traitor Pannel Contractor Contract adding doesn't add TC to locations

### ISSUE THREAD

**Issue by Eric6426-Blossom** [ParadiseSS13/Paradise#18940]
**Issue Description**:

Via the Traitor Pannel, if you add a contract to a Contractor, after choosing a person, it'll add the contract but all the locations it randomly chooses will default to 0 TC, and will need to be manually tweaked and given TC.

**What did you expect to happen**: 

For the default contract TC calculation for contract and location difficulty to be used instead of forcing the admin to manually set the values.

**What happened instead**:

Had to set the values myself after giving a contractor a contract, due to them all being 0 TC.

**Why is this bad/What are the consequences**:

Contractors sometimes need their contracts removed or more added due to issues in-round about their contract or for admin-related purposes.

**Steps to reproduce the problem**:

(Unsure if impactful, not fully tested, just did it when this happened) Delete one of the contracts of a contractor
Add a new contract and pick anyone for the contract
Check the contract's locations, see the 3 options randomly chosen, but all set to 0 TC

**When did the problem start happening**:

29/08/2022 is the date in which I found it.

**Extra information**:

**Comment by Komrad822** [comment]
I've actually had this happen before when i first started contracting so it goes back to at least december of 2021.
