### ISSUE TITLE
Clown runtimes if you put on cursed clown mask

### ISSUE THREAD

**Issue by FloFluoro** [ParadiseSS13/Paradise#18946]
**Issue Description**:

Putting on a cursed clown mask as a roundstart clown causes a runtime

**What did you expect to happen**: 

No runtime

**What happened instead**:

Runtime

**Why is this bad/What are the consequences**:

Runtimes bad

**Steps to reproduce the problem**:

1. Be a roundstart clown
2. Spawn /obj/item/clothing/mask/cursedclown
3. Put on the mask, enjoy your runtime

**Extra information**:

Cursed clown masks are in the floor cluwne's drop table, so this could happen in live, however unlikely it may be.

**Comment by Sirryan2002** [comment]
this is probably my fault?
