### ISSUE TITLE
Sprite on Character Setup in lobby does not update

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#1899]
This applys to underwear/shirt (and soon SOCKS) choices.

**Comment by Markolie** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
It never has, AFAIK.

**Comment by TheDZD** [comment]
I specifically remember this updating fine at one point.

**Comment by Aurorablade** [comment]
yeah it did.

**Comment by Spacemanspark** [comment]
It did.

**Comment by tigercat2000** [comment]
My mistake then. Character Preview is notoriously fucky, I'll look into it later.

**Comment by Spacemanspark** [comment]
https://github.com/ParadiseSS13/Paradise/issues/1581 Anyone remember this?

**Comment by Markolie** [comment]
Fairly certain that's a different issue.

**Comment by Spacemanspark** [comment]
Ya, it is, just poking fun at how bad the character setup lobby code is.

**Comment by Markolie** [comment]
Ahh, never mind then :P.

**Comment by Fox-McCloud** [comment]
Should be fixed, now.
