### ISSUE TITLE
Dresser Structure does not respect gender/race restrictions

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#1900]
It will list all options and not check for race/gender...

Ever seen a bald greytide male in kinky ladies underwear? Never want to...It cannot be unseen *cries*

**Comment by Zuhayr** [comment]
Why is this a problem?

**Comment by Dumbdumn5** [comment]
I agree with @Zuhayr

**Comment by tigercat2000** [comment]
not a bug
