### ISSUE TITLE
Death alarm implants have random activate button

### ISSUE THREAD

**Issue by Christasmurf** [ParadiseSS13/Paradise#19012]
**Issue Description**:
Death alarm implants have a random activate button on your HUD, pressing activate on it does nothing
![image](https://user-images.githubusercontent.com/25437893/189485797-8fff1058-bcf0-4651-93b8-87ac0dd5bfe3.png)

**What did you expect to happen**: 
No button like before

**What happened instead**:
Useless button

**Why is this bad/What are the consequences**:
Useless crap on my screen ree how i click spessmans under it now

**Steps to reproduce the problem**:
Get implanted with a death alarm

**When did the problem start happening**:
I noticed it start two shifts ago but probably last time implants were messed with

**Extra information**:
I am very sad at this issue please fix quickly so I can be not sad

**Comment by Sirryan2002** [comment]
Technically my implant refactor caused this, but this is because I added a base sprite for the dmi that implant action icons use and the code that caused this is problematic 💀

**Comment by hal9000PR** [comment]
Apparently fixed
