### ISSUE TITLE
Playing a sound file locally does not respect the 'hear admin .midi's' preference setting.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1902]
Elysian played a sound file locally, and I had the setting turned off.
Not a large issue.

**Comment by tigercat2000** [comment]
It's intentional.

**Comment by Spacemanspark** [comment]
It shouldn't be.

**Comment by tigercat2000** [comment]
Still not a bug.

**Comment by TheDZD** [comment]
Admins often use local sounds for events/haunting people. It makes sense that the setting applies to global sounds because those are not uncommonly used to play music.

**Comment by Spacemanspark** [comment]
If an admin plays an MP3 or what have you file to someone with a bad internet connection, it REALLY lags for the next thirty or so seconds.

**Comment by tigercat2000** [comment]
This still isn't a bug, it's a feature request, as this is how local sounds are fully intended to work.

**Comment by CrAzYPiLoT-SS13** [comment]
Closure when?
