### ISSUE TITLE
Implanters in box not implating and new implanters coming full and not implanting as well.

### ISSUE THREAD

**Issue by DogeDogIs** [ParadiseSS13/Paradise#19037]
**Issue Description**:

The implanters in the boxs and in the protolathe, are both with problem, in the box they don't implant and don't waste and in the protho, they come full and do not waste as well.

**What did you expect to happen**: 

Well, its impossible to implant someone with this, we need to luck to have a implanter that work. No ideia what this bug can be.

**What happened instead**:

I expected the implant working and they having tracking or death implants, but didn't worked.

**Why is this bad/What are the consequences**:

Sometimes perma prisioners can't have the tracking implants, and if you go to make a new implant in science the implnter comes full and you can't use it too. Need to pray to any implanter works to make this. This can cause so many problems.

**Steps to reproduce the problem**:

Get a implant box and use it on someone. 

Go to protolathe, make a new imaplanter and use it in someone too. (And the implanter needed to be empty not full when frabricated in the proto)

**When did the problem start happening**:

When the implanter had the new sprite. 

**Extra information**:

https://user-images.githubusercontent.com/62888630/189773292-3461d088-2de7-4619-82c6-01249d25b2ab.mp4

https://user-images.githubusercontent.com/62888630/189773414-d30fed8f-0fa7-40a1-9474-1f3204508f2b.mp4

**Comment by Contrabang** [comment]
likely related to #18982 and/or #18556
Looking into this
