### ISSUE TITLE
Tendril loot giving items with no use on lavaland

### ISSUE THREAD

**Issue by SpinningSalami** [ParadiseSS13/Paradise#19031]
**Issue Description**:
When the Inquisitor suit was removed from tendril loot #18698 the bottle of hell water was left taking up the slot and giving something that is not useful on lavaland.

**What did you expect to happen**: 
To get something that can actually be used on lavaland.

**What happened instead**:
Got some weak poison.

**Why is this bad/What are the consequences**:
Dilutes the loot pool of tendril chests and also gives you something not useful on lavaland at all.

**Steps to reproduce the problem**:
Kill tendril until you get a bottle of poison holy water and nothing else.

**When did the problem start happening**:
Remove the holy water from the loot pool.

**Comment by hal9000PR** [comment]
This isn't a bug
