### ISSUE TITLE
ID in PDA prevents vending machine usage.

### ISSUE THREAD

**Issue by Iwanabeu** [ParadiseSS13/Paradise#19049]
**Issue Description**:

Having an invalid ID in your PDA, like an agent ID with no linked bank account, causes vending machines to forbid usage. "Unlinked ID detected. Present cash to pay."

**What did you expect to happen**: 

The vending machine should look at my valid, money holding ID card in my ID slot, and allow me to buy stuff.

**What happened instead**:

The vending machine ignored my valid ID in my ID slot, saw that I had an unlinked ID in my PDA, and denied me.

**Why is this bad/What are the consequences**:

To buy stuff from a vending machine, you have to put the agent ID, which is S class contraband, into your backpack. Having to juggle your ID for no reason is not good.

**Steps to reproduce the problem**:

Buy agent ID, do not link agent ID to bank account, put ID in PDA. Keep regular ID in ID slot. Try to buy something.

**When did the problem start happening**:

Since #18992 was merged I guess.

**Extra information**:

It only works one way, the ID in the PDA overrides the ID in the ID slot. If you have a valid ID in PDA but an agent ID with no bank in the ID slot, you can use the vending machine as normal.

**Comment by FloFluoro** [comment]
Will be addressing this in a PR shortly.
