### ISSUE TITLE
Upgraded freezers cool below absolute zero

### ISSUE THREAD

**Issue by SpaceTimeNow** [ParadiseSS13/Paradise#1907]
Upgraded freezer cool below 0 Kelvin, which should not be possible. I noticed it when cryo got upgraded.

![5](https://cloud.githubusercontent.com/assets/10059163/9567747/c81204c8-4f36-11e5-9ac9-af9679384ddc.JPG)

If you cool gas below 0 kelvin it becomes negative pressure, that fuckes with cryo because you need pressure for it to work. When you set the cooler to like 50 Kelvin then you will have pressure again, so if you know what you do you could prevent this. 

But you could obviously abuse that and fill canisters with infinite amount of gas, because at 0 or less kevlin pressure won't built up.

**Comment by Markolie** [comment]
Ah, it's caused by the tier 4 upgrades.

**Comment by Alex6511** [comment]
Ss13 breaking the laws of thermal dynamics again.

**Comment by Iamgoofball** [comment]
We fixed this ages ago at tg

**Comment by Markolie** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/ATMOSPHERICS/components/unary_devices/Freezer.dm#L34

Based on that, the min temperature on freezers can still be set to -17K.
