### ISSUE TITLE
Communicating with animals, has science come too far?

### ISSUE THREAD

**Issue by dagilbert** [ParadiseSS13/Paradise#1908]
Currently without a borg you cant talk to the animals, from what I remember pAI's used to be able to translate but that doesn't work anymore.

I was thinking it would be cool if vulps could talk to animals, or just renault/foxes and maybe tajarans can understand runtime or something.

or just allowed the :7 or whatever language to work for animals of that type.

I think Ian's trying to tell me the captain has fallen down the well, but I can't understand :'(

**Comment by tigercat2000** [comment]
The issue tracker is really not the place for feature requests, they would be better received on our suggestion forums, located [here](http://nanotrasen.se/forum/viewforum.php?f=12)

**Comment by dagilbert** [comment]
oh sorry, thanks.

**Comment by Markolie** [comment]
Closing feature requests - post it on the forums please.
