### ISSUE TITLE
ERT Leader no longer gets an officer name

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1909]
Ever since the change to the new ERT system where the command isn't just the first person who hits the button, I've noticed that the leader is being assigned a random NCO name instead of an officer name. I think this is because the character is spawned before selecting your role, and then your name is not changed to reflect your role as leader.

**Comment by Spacemanspark** [comment]
Yep, so you get Corporal Billy Jones in charge of Major Honks and Lieutenant Bob joe.
