### ISSUE TITLE
Vampire Claws Permanently attached.

### ISSUE THREAD

**Issue by RMLMT** [ParadiseSS13/Paradise#19109]
**Issue Description**:
While playing as a vampire, I was unable to put away my claws after rapidly activating the claws and then rejuvenating.

**What did you expect to happen**: 
I expected to be able to deactivate my claws and pick up items.

**What happened instead**:
I was permanently unable to unequip the vampire claws, and an admin had to remove them. This is clearly not intended behavior.

**Why is this bad/What are the consequences**:
Being unable to pick up items as a vampire severely inhibits your ability to function.

**Steps to reproduce the problem**:
Unsure exactly, but I know it involves activating the claws and then rapidly rejuvenating. Denthamos has submitted a report which should include some sort of reproduction of this.

**When did the problem start happening**:
During combat, after the claw->rejuv combo mentioned.

**Extra information**:
It's possible stuns might have factored in somehow, or disablers. The issue did not occur while stunned though.

**Comment by hal9000PR** [comment]
When you say "rapidly activating them" do you mean using them in hand?

**Comment by hal9000PR** [comment]
just tested this, you have to "use them in hand" eg. press z by default. in order to dispell them.
