### ISSUE TITLE
Issues when Changeling get First time Cyborged

### ISSUE THREAD

**Issue by Venuska1117** [ParadiseSS13/Paradise#19143]
**Problem Description**:
When Changeling get cyborged first time, you are not integrated with cyborg, you have AI laws but can't communicate, when i died from "Drunken Blood Miner" my cyborg got destroyed and my brain fell out, second time cyborged fixed issues.

**What did you expect to happen**: 
Just to get normally cyborged

**What happened instead**:
Got Cyborged as Changeling, dont have access to communications channels (ANY)

**Why is this bad/What are the consequences:**
I dont know if its intentional as "second" chance or its bug

**Steps to reproduce the problem**:
Be Changeling, Get beaten by security because u commit yourself to be one, get brain rip off from head and put in MMI, fight 12minutes to get cyborged, get cyborged to see issue with using communications channels, die from blood drunk miner and your brain fell out and body is gone, and get in cyborg shell again to be "fully" cyborged (second time it work normally)

**When did the problem start happening**:
When i just casually played

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
I think there is possibility for changeling to be human, because when you are fist cyborged you lost all abilities, and probably can be cloned to be "human" but i got cyborged so idk if my "theory" is right.

**Comment by SteelSlayer** [comment]
Can you elaborate on the communications channel issue? Do you mean that you could not use the cargo channel, or binary channel for example? Was there *any* other radio chatter going on at this time?

As for the other thing you mentioned: someone can correct me if I'm wrong but the brain falling out part is normal. Sounds like the blood drunk miner gibbed you, and that means as a cyborg, all that's left is your brain.

**Comment by Venuska1117** [comment]
i mean, "known languages" tab, when you first time cyborged you dont have access to any language, the page is mostly blank (you only know how to talk default language)

**Comment by silverplatedelta** [comment]
Due to how clings now behave, this is no longer an issue. De-braining a cling will not kill it.
