### ISSUE TITLE
Reinforcement caller invisible (Saboborg one)

### ISSUE THREAD

**Issue by Komrad822** [ParadiseSS13/Paradise#19156]
**Issue Description**:

Sabo-borg calling device was invisible in hand, in bag and on floor for myself.

**What did you expect to happen**: 

The item be visible on purchase.

**What happened instead**:

I had to wonder if I had actually bought it, since both hands were full at the time i wondered why it was invisible at my feet.

**Why is this bad/What are the consequences**:

Inexperienced players may panic, may forget it, itll cause more ahelps than it should.

**Steps to reproduce the problem**:

1.Have hands full
2.But sabo-borg reinforcement thing
3. Observe as it is invisible but still shows up if you right click the time.

**When did the problem start happening**:

IDK.

**Extra information**:

I recorded my nukie round and if someone wants to see exactly what Im talking about, let me know and ill make a video on that section of the round.
In the image below, in the selected hand has the spawner remote.
![image](https://user-images.githubusercontent.com/94168850/192083258-62202eab-797f-45ab-a5b0-b8a4d6aac773.png)

**Comment by Samman166** [comment]
Do you know the round ID of the round this happened?
