### ISSUE TITLE
the science break room is not accessable to robotics. [Kerberos]

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#19154]
**Issue Description**:

For robotics to be able to chill in the break room with science, and eat from the 2 vendors in the department

**What did you expect to happen**: 

To have a drink with THE SCIENCE TEAM, not by themselfs

**What happened instead**:

No access, it is built off scichem, for some reason

**Why is this bad/What are the consequences**:

muh drinks and break

**Steps to reproduce the problem**:

Be roboticst
Try to reach it.
Fail

**Comment by Miraviel** [comment]
They can access the break room via maintenance. They cannot access it from scichem because they should not have access from scichem.

Kerberos' science access is all over the place, but I am fixing those now.

**Comment by Miraviel** [comment]
Kerberos was remapped so this is no longer an issue
