### ISSUE TITLE
Facehuggers can't facehug corgis

### ISSUE THREAD

**Issue by FloFluoro** [ParadiseSS13/Paradise#19157]
**Issue Description**:

Facehuggers can't facehug corgis, despite having checks in code to do so. #7735 indicates that this worked at some point.

**What did you expect to happen**: 

The facehugger to attach to the corgi. Facehuggers lunge at corgis specifically because they're whitelisted in the code, but they don't attach for some reason.

**What happened instead**:

The facehugger does not attach, and flops onto the floor in its dormant state.

**Why is this bad/What are the consequences**:

You can throw corgis at facehuggers to make them sleep. You can send a corgi into a xenomorph nest to neutralize all the facehuggers inside of it, because they'll _all_ go dormant without attaching to the corgi. This seems bad since Xenos are now back on rotation?

**Steps to reproduce the problem**:

* Be a corg
* Walk into facehugger
* Facehugger will lunge, fail to attach, then go dormant

**When did the problem start happening**:

Probably after #12206, which ripped out a bunch of corgi-related code in `facehugger.dm` for some reason.

**Extra information**:

bark

**Comment by Scribble-Sheep** [comment]
Should corgis even be facehuggable in the first place, design wise? Seems kind of odd since from what I can tell of the code, other simple mobs just..don't have those checks.

**Comment by FloFluoro** [comment]
> Should corgis even be facehuggable in the first place, design wise? Seems kind of odd since from what I can tell of the code, other simple mobs just..don't have those checks.

Whether someone wants to resolve it by fixing corgi facehug attachment or removing the quirk entirely, that's up to whoever tackles the issue.
