### ISSUE TITLE
Ian refuses to GC

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#19152]
**Issue Description**:
Ian fails to GC under pretty much every situation

**What did you expect to happen**: 
No GC fail

**What happened instead**:
![Screenshot 2022-09-23 170912](https://user-images.githubusercontent.com/96800819/192063218-d25295f8-d054-42a5-9622-ff5a3552503d.png)

Due to the fucking experimenter holding a ref
**Why is this bad/What are the consequences**:
GCing good, GC failing bad

**Steps to reproduce the problem**:
Start a server
Try to GC Ian (This can be done by having Ian replaced with smol Ian)
No GC

**Comment by Miraviel** [comment]
Fixed in #19430
