### ISSUE TITLE
Respawn command is missing.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1915]
An admin can toggle on respawning, but nobody can use it. This was discovered in a highlander round yesterday in which it was toggled on, but nobody could, well, respawn. The command can't be typed in, nor can it be seen in the ghost/ OOC tab.

**Comment by tigercat2000** [comment]
I do believe the respawn system was half-way ripped out a while ago, and no one bothered to take away the overhead.
