### ISSUE TITLE
Invisible snake pais

### ISSUE THREAD

**Issue by mattrim5989** [ParadiseSS13/Paradise#19163]
**Issue Description**: Snake pai(s) become invisible in hand, on head, and any other storage while in snake form

**What did you expect to happen**: I expected a model image in hand and on head inventory along with a model on the charcter like other pai chassis

**What happened instead**: No model in inventory or on charcter

**Why is this bad/What are the consequences**: pais can be lost in inventory or you can forget where they are and make mistakes in game because of it like trying and failing to put a eva helmet on

**Steps to reproduce the problem**: Get pai, have pai unfold chassis and choose snake form, pick up pai, (for head inventory glitch put on empty head slot)

**When did the problem start happening**: Unknown but I noticed this month

**Extra information**: While I haven't looked this might be missing images in files or some kind of failure when requesting the images

**Comment by Burzah** [comment]
This is apart of an older issue has been ongoing. You can find it here https://github.com/ParadiseSS13/Paradise/issues/9328.
Right now there are a few pAI sprites that need to be fixed and updated so they display correctly in game. I am going to close this issue as this behavior has already been documented. Thank you for making the report!
