### ISSUE TITLE
Getting knocked out then having your hardsuit stolen makes a ghost item

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#19169]
**Issue Description**:

I was knocked out and had my equipped hardsuit stolen, that placed a ghost item in my hand that could have another item on top of it.

**What did you expect to happen**: 

No ghost items.

**What happened instead**:

I got a ghost item that could have items on top of it, but when equipped, I couldn't unequip it or equip other gear. The ghost item followed the actions of the new owner.

**Why is this bad/What are the consequences**:

Ghost items are bad.

**Steps to reproduce the problem**:

1. Equip hardsuit and its helmet.
2. Get knocked out.
3. Have the hardsuit stolen while knocked out.
4. Look at your hand and/or open the equipment screen a few times.

**When did the problem start happening**:

Noticed today 25.09.2022.

**Extra information**:

I wasnt able to capture the first image since my character fainted a few times, but just imagine a hardsuit in my right hand, with a large O2 tank stacked \*on top\* of the sprite.

After fainting and opening the equip screen the hardsuit moved from my hand to this invisible slot + it was still equipped in my torso slot.
![image](https://user-images.githubusercontent.com/25958019/192122829-ddb3bcca-3977-4205-945d-53e0d43690ea.png)

Also I was contracted, and at the very end the hardsuit came back. Still a ghost though. This is probably due to it following actions of the new owner.
![image](https://user-images.githubusercontent.com/25958019/192122966-5c532235-b5d7-4f17-bfbd-a8f2e4d60f44.png)

Bonus pic to show the hardsuit is actually the same one someone else has (collecting radiation):
![image](https://user-images.githubusercontent.com/25958019/192123039-39e5b2e6-0dfe-4196-ab76-07f67377a984.png)

**Comment by Christer2222** [comment]
slight correction; I wasnt able to test if I could equip something over the suit as I tried placing a jumpsuit there. However it could NOT be unequipped.

**Comment by Spaghetti-bit** [comment]
We don’t have hard suits anymore and mod suits do not have this problem

**Comment by Fordoxia** [comment]
> We don’t have hard suits anymore and mod suits do not have this problem

We do actually still have hardsuits for the SST.
