### ISSUE TITLE
Lagspike causes controls to be locked

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#19195]
**Issue Description**:

I want to begin this issue by saying that I am not 100% sure if this is consistent, but I experience this several times every round.
Holding a directional button (tested with WASD) and having a lagspike causes that button to be stuck pressed until you press it again.

**What did you expect to happen**: 

To have the game register when a key is lifted, even if there was a lagspike between the press and the lift. Preferably it would register the button lift even during the lagspike (key no longer pressed when spike is over)

**What happened instead**:

Press key, lag happens, game resumes, lift key, game still registers the key as being down.

**Why is this bad/What are the consequences**:

Its very annoying trying to move somewhere and then having your character move past the point, especially in space.

**Steps to reproduce the problem**:

1. Move in a direction by holding down the movement buttons (tested with WASD, not arrows)
2. Have a lag spike happen.
3. Wait for the game to resume (lifting your key seems optional, though I usually hold it).
4. Watch as your character moves on its own.

**When did the problem start happening**:

While not sure it might have started around the time the wall sprites changed. I haven't reported it before now because I wasn't sure how to word it, or if it was something else that the lag itself. Seems hard to reproduce.

**Extra information**:

I should make clear that this happens in places with gravity, aka inside the station, not only in space. Though outside and inside do feel similar due to this issue. Also interacting with machinery seems to increase the odds of this happening.

**Comment by Scribble-Sheep** [comment]
Do you have a tgui window open before this happens? I've had issues where holding a key down while the window is open, then closing it, will cause the key to be held until I reconnect.

**Comment by Christer2222** [comment]
It happens more frequently when you have/had a tgui window open, but it can also happen with no window open at all.
