### ISSUE TITLE
Arrival shuttle not shielded to Solar flares

### ISSUE THREAD

**Issue by Mythrava** [ParadiseSS13/Paradise#19206]
**Issue Description**:

Arrival shuttle not shielded to Solar flares

**What did you expect to happen**: 

Spawn in and not die

**What happened instead**:

Spawn in get blinded before even know what happened, died 50 secs after that to over heating 

**Why is this bad/What are the consequences**:

Being blinded and in crit before getting off the arrival shuttle is dumb

**Steps to reproduce the problem**:

**Extra information**:

Was a Tajaran so Lower heat threshold i went into crit, pretty sure a drask wound of been husked if that happen to them

**Comment by SteelSlayer** [comment]
Which map is this? Or is it all maps?

**Comment by Mythrava** [comment]
MetaStation

**Comment by S34NW** [comment]
> Which map is this? Or is it happening on all maps?

This is likely happening on all maps, looking at the code

**Comment by Jaredw224** [comment]
Happening to all station's, it's a death sentence being on the arrival shuttle, during a solar flare
