### ISSUE TITLE
Shadowling thralling is not disabling the loyalty implant

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1920]
I'm pretty sure it's supposed to disable the implant, not go straight through it.

**Comment by Fox-McCloud** [comment]
It goes straight through the implant and destroys the implant in the process--unless this super recently bugged out, this was working, last I checked.

People with loyalties take longer to thrall.

**Comment by Alex6511** [comment]
Yeah, I don't think its correctly destroying the implant, just going through it (still takes longer) but I can't test it.

**Comment by Alex6511** [comment]
It appears to only happen when an asended shadowling instantly thralls someone.

**Comment by Fox-McCloud** [comment]
This only happens with ascendants, given their power levels and the fact this is only during the last few minutes of the round...I don't really count this as a bug.
