### ISSUE TITLE
Not being able to close an incision after failing last step

### ISSUE THREAD

**Issue by Juberan64** [ParadiseSS13/Paradise#19243]
**Issue Description**:
When performing surgery (any I think) on a living mob, if you fail the last step (cautery to close the incision), there is a bug where you won't be able to close it after failing, leaving it open and the patient bleeding out. Cannot be closed with scalpel + cautery neither.

**What did you expect to happen**: 
I expected to close the incision with the cautery.

**What happened instead**:
I couldn't close the incision and had to ask an admin to close it (two times)

**Why is this bad/What are the consequences**:
Having to ask an admin to close an incision each time I fail isn't nice, and waiting for the admin to close it while the patient bleeds out isn't nice either.

**Steps to reproduce the problem**:
Put someone in a table/roller bed and don't give any type of anesthetic (so failing chances are higher and you can see it happening), start a surgery (Organ manipulation for example), do all the steps and try to close the incision. Repeat until you fail the last step of the  surgery.

**When did the problem start happening**:
I have been seen this for a week, I believe it could be the surgery tweak we got a few weeks ago where you could do more than one fix in the same surgery, but no idea at all.

**Extra information**:
It makes me so mad having someone bleeding when I did all right. Anyone could think "You could just use a surgery table and anesthetic", I use morphine for quick surgeries, so mistakes on sugery can happen and Im not stopping using morphine for a bug :).
Another thing I would like to add is that sometimes, starting a new surgery in the same place while the other one is bugged, lets you close the second incision, fixing the bug, but Im not really sure if this happens always.

**Comment by lewcc** [comment]
https://github.com/ParadiseSS13/Paradise/pull/19237 should fix this

**Comment by Juberan64** [comment]
Well, thank you so much for fixing it, hope it gets implemented in the game soon.
