### ISSUE TITLE
Malfunctioning AI lockdown has been disabled

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1925]
After #1924 I think it's a good idea to create an issue report so we as a group remember that it needs to be re-added at some point. I would prefer it be high priority but I imagine not everyone considers one ability to be so important.

**Comment by TullyBurnalot** [comment]
@Fox-McCloud Not even sure if it's relevant anymore, either close or please specify.

**Comment by Davdichan** [comment]
"Lets give the AI the ability to shut, bolt and shock every door on the station"
Pass

I'm fairly certain it didn't even check if the door was visible on cameras. That or it just bugged out every time I saw it used.
