### ISSUE TITLE
Some Xenoborg stuff is broke

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [ParadiseSS13/Paradise#19290]
**Issue Description**:

Two of the Xenoborg's modules, namely the eye-flash and the paralytic toxin synthesizer spray have issues in regards to them in the following ways. 

One, the eye-flash module, once it burns out, the sprite disappears from the modules selection but is still able to be selected, the sprite is just gone.

Two, the paralytic toxin synthesizer spray has zero actual effect. I've tested it both on humanized monkeys and regular monkeys, and nothing actually happens. I've also tested it on a crewmember who requested it and still, nothing happened.

**What did you expect to happen**: 

The eye-flash shouldn't have just vanished, and the paralytic toxin should've... maybe done stamina damage? Or weaken? Literally anything.

**What happened instead**:

The eye-flash disappeared but was still usable after a quick trip to the cyborg charger as normal. I would presume it's because there's no actual sprite for a burned out xenoborg eye-flash. The paralytic toxin did... literally nothing ever.

**Why is this bad/What are the consequences**:

Well, at the barest minimum, things not properly working in the codebase is just... bloat, isn't it? Useless? But I mean, failing that, obviously people like the idea of the Xenoborg since it exists in the first place, so making things not broken for it is probably a reasonable idea, though at the same time the actual purpose of the Xenoborg is questionable at best.

**Steps to reproduce the problem**:

Use the flash until it burns out, you'll see the sprite vanish. Spray anything with the paralytic toxin, nothing will happen.

**When did the problem start happening**:

The paralytic toxin has not once worked as far as I can tell.

**Extra information**:

See the attached images below. The first image is a picture of the eye-flash selected as an active module without a sprite, the second picture is the spriteless module sitting in it's place in the modules list next to the paralytic spray.

![Bugged Eye-Flash 1](https://user-images.githubusercontent.com/71111573/193975421-7887def0-306b-4c10-88eb-68512a811ac9.png)

![Bugged Eye-Flash 2](https://user-images.githubusercontent.com/71111573/193975431-e7443ae8-48a8-4ae3-badd-aa5028a5d953.png)

**Comment by GDNgit** [comment]
these are so fucking funny let me explain
1. "Viagra spray" applies ether topically...  a chemical which REQUIRES injection, so it does nothing at all
2. the flash has no disabled sprite I believe, so it just goes invis
These things need some tweaks, but it's damn funny
