### ISSUE TITLE
Headpocket for skrell doesn't work

### ISSUE THREAD

**Issue by Tourte-Yaya** [ParadiseSS13/Paradise#19312]
**Issue Description**:

Headpocket doesn't work.

**What did you expect to happen**: 

I expected to be able to store items in the headpocket

**What happened instead**:

The button for opening the headpocket slots doesn't work.

**Why is this bad/What are the consequences**:

Button should work.

**Steps to reproduce the problem**:

Spawn a skrell, possess it and click on the headpocket button.

**When did the problem start happening**:

No clue.

**Extra information**:

**Comment by Vi3trice** [comment]
Did you try while having an item in your active hand?

**Comment by Tourte-Yaya** [comment]
Nope, just tried now with an item in active hand and it worked, we probably should have a message telling the user we need an item in the active hand to prevent confusion instead of 0 message.
