### ISSUE TITLE
It is impossible to see reagents and addictions inside IPCs

### ISSUE THREAD

**Issue by KittyNoodle** [ParadiseSS13/Paradise#19313]
**Issue Description**:

The cyborg analyzer is incapable of scanning chemicals or addictions in ipcs. 

**What did you expect to happen**: 

It to report the chemicals and addictions in ipcs.

**What happened instead**:

it does not

**Why is this bad/What are the consequences**:

makes it near impossible to figure out the chemicals inside an ipc.

**Steps to reproduce the problem**:

1.Drink super lube as an ipc
2. scan yourself
3.no chemical or addiction readout
**When did the problem start happening**:

**Extra information**:

**Comment by YoureNotTheSharpest** [comment]
> super lube
hehehe

**Comment by DGamerL** [comment]
Fixed by #23523
