### ISSUE TITLE
Slimes can understand drones

### ISSUE THREAD

**Issue by Groudonmaster** [ParadiseSS13/Paradise#19314]
**Issue Description**: Play drone, talk to yourself because the captain is stupid about electrical powernets, sentient slime understands you, profit????

**What did you expect to happen**: Slimes to not be able to understand me bitching about the captain being stupid about electrical powernets

**What happened instead**:Slimes understood me bitching about the captain being stupid about electrical powernets

**Why is this bad/What are the consequences**: Unintentionally break drone laws just by speaking out loud next to a slime

**Steps to reproduce the problem**: Be drone/slime near the other and have the drone talk. Slime understands.

**When did the problem start happening**:n/a

**Extra information**:n/a

**Comment by matttheficus** [comment]
If I recall, slimes have `universal_understand`, would need to double check.

**Comment by Coolrune206** [comment]
> If I recall, slimes have `universal_understand`, would need to double check.

It seems _all_ simple mobs have universal_understand, just not universal_speak, so this issue is not unique to slimes.
