### ISSUE TITLE
MULE paths always appearing 

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#19322]
**Issue Description**:

The MULE path, which you can see with the diagnostic HUD is always shown despite it not moving.

**What did you expect to happen**: 

For it to not stick around

**What happened instead**:

It was still there despite the mule having traveled that path

**Why is this bad/What are the consequences**:

Paths that aren't being currently traveled cause confusion

**Steps to reproduce the problem**:

1. Get a diagnostic HUD or be a ghost with diagnostic HUD enabled
2. Go to a mule
3. Set a destination (in this case it was noticed when the MULEs were set to brig I am guessing any destination would work)
4. See the path be drawn even if the bot isn't moving.

**When did the problem start happening**:

Unsure noticed today (2022-10-08)

**Extra information**:

**Comment by S34NW** [comment]
This is fixed in https://github.com/ParadiseSS13/Paradise/pull/18984
