### ISSUE TITLE
A cutlist body that was offered up for a ghost to take over can be taken over again by the original player

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#19323]
**Issue Description**:

The original player of a cultist body that can go back into the body if the new player is currently in spirit realm.

**What did you expect to happen**: 

For it to not allow them to take over the body again

**What happened instead**:

They were put in the body and the new player being booted from the body

**Why is this bad/What are the consequences**:

If a player requests to be replaced or someone who is currently banned from cultist is replaced, they can simply go back into their body if the player that is now controlling their body goes into the spirit realm.

**Steps to reproduce the problem**:

1. Have someone control a cultist body.
2. Offer it up for ghosts
3. Have someone take over
4. Have that new player go into spirit realm using the rune.
5. The original player of the body will be able to take over again by re-entering their body by double clicking on the body. (I am not sure if the re-enter body verb would work) 

**When did the problem start happening**:

Unsure, but likely when blood cult was originally added
Noticed for the first time today 2022-10-08

**Extra information**:

**Comment by matttheficus** [comment]
This is likely due to mind fuckery, the same issue can occur when offering an admin-created body that was previously hosting its creator.
