### ISSUE TITLE
Sec borgs can spam *halt over and over.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#1933]
I found I could do this whilst playing. (Jesus fuck it's annoying as hell).
recorded it too, will upload video later.
Imagine a sea of "HALT! SECURITY!" and the gravel in the background, because why not.
you have created a living hell.
@Markolie

**Comment by Markolie** [comment]
Halt! Security!

**Comment by Spacemanspark** [comment]
Lmao more like
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!
HALT! SECURITY!

**Comment by Alex6511** [comment]
Do you mean *halt in the title?

**Comment by Spacemanspark** [comment]
Whoops, good catch.

**Comment by Spacemanspark** [comment]
...Apparently, this is INTENTIONAL.
![OHGODWHY](http://i.imgur.com/43V3WqD.png)

**Comment by Alex6511** [comment]
#blameMarkvA

**Comment by Spacemanspark** [comment]
http://youtu.be/syIHMlps_Rg
