### ISSUE TITLE
MULEbots cannot be unscrewed to access service panel

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#19346]
**Issue Description**:
You can no longer unscrew a depowered/powered MULEbot to access it's wires/service panel.

**What did you expect to happen**: 
For this to happen as it always has.

**What happened instead**:
Literally nothing, no feedback is given on attemping to screwdriver it.

**Extra information**:
![image](https://user-images.githubusercontent.com/12197162/194915333-992441f2-8065-4d71-ad50-c09175a79f85.png)

**Comment by Sirryan2002** [comment]
#19024 @Contrabang
