### ISSUE TITLE
Radium and other irradiating chems don't irradiate ipcs.

### ISSUE THREAD

**Issue by KittyNoodle** [ParadiseSS13/Paradise#19368]
**Issue Description**:

IPCs do not take irradiating damage from radium.

**What did you expect to happen**: 

Radiation brain damage.

**What happened instead**:

Nothing

**Why is this bad/What are the consequences**:

A chem which you would expect to harm ipcs doesn't

**Steps to reproduce the problem**:

1. Drink radium as ipc
2. No rad damage

**When did the problem start happening**:

When ipc radiation damage was added

**Comment by matttheficus** [comment]
This is likely due to it not being processed by IPCs, much like many other chems.
