### ISSUE TITLE
Remove blood from the Recycling Grinder with this one weird trick! Janitors hate him!

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#19393]
**Issue Description**:
Screwdriving the panel open on the recycling grinder makes blood magically disappear sprite-wise (examine text still says its blood stained)

**What did you expect to happen**: 
To be able to open and close the panel on a grinder without it deleting blood

**What happened instead**:
THIS NEW SCREWDRIVER CLEANS IN SECONDS

**Why is this bad/What are the consequences**:
Visual inconsistency

**Steps to reproduce the problem**:
Bloody the recycler (emag it, then throw a body into it). Now use a screwdriver on it to open the panel.

**When did the problem start happening**:
Probably forever because it appears there is no sprite state for a bloodied, open grinder. It probably needs a refactor to not need a crazy amount of sprites.

**Comment by SteelSlayer** [comment]
This should be fixed by extracting the open panel portion of the recycler sprite and moving to it's own icon so it can be applied as an overlay on top of the recycler when it is screwed open.

Requires a (small) refactor.
