### ISSUE TITLE
The nuclear explosion does not dust corpses

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#19408]
**Issue Description**:

When the nuke goes off, every living mob gets dusted in its vicinity/z-level/however the `offstation` var of it works.

**What did you expect to happen**: 

When the nuke goes off, every mob, living or dead, should get dusted.

**What happened instead**:

Corpses stay intact.

![image](https://user-images.githubusercontent.com/33333517/196030428-477302c6-ee73-4a3d-b0cd-cb95134411fb.png)

**Why is this bad/What are the consequences**:

Inconsistent, and I want everyone to dust equally.

**Steps to reproduce the problem**:

1. Have a living and a dead mob
2. Set off nuke
3. Observe as the living one dusts but the corpse stays intact

**When did the problem start happening**:

Probably forever.

**Extra information**:

...

**Comment by Sirryan2002** [comment]
closing as this isn't an issue, moreso a suggestion for more functionality
