### ISSUE TITLE
"an unknown language" appearing in the character setup.

### ISSUE THREAD

**Issue by RomanaTColgate** [ParadiseSS13/Paradise#1940]
Under language.dm we have a giant, what looks to be, example language.
/datum/language
	var/name = "an unknown language" // Fluff name of language if any.
	var/desc = "A language."         // Short description for 'Check Languages'.
	var/speech_verb = "says"         // 'says', 'hisses', 'farts'.
	var/ask_verb = "asks"            // Used when sentence ends in a ?
	var/exclaim_verb = "exclaims"    // Used when sentence ends in a !

And so on, this is actually appearing in the character setup as it's listen in the code, and it's weird.  I imagine this is supposed to be commented out?

**Comment by veganzombeh** [comment]
It's the parent type of all other languages, those names are just placeholders. Is this actually appearing in-game? Character setup uses the `all_languages` list, which should contain only subtypes of /datum/language.

**Comment by RomanaTColgate** [comment]
Yes, it is, in the character set-up screen people can actually select and use it.

**Comment by TheDZD** [comment]
@Markolie You're more familiar with language code than I am, any ideas why this is occurring?

**Comment by FalseIncarnate** [comment]
Probably assembles the list and forgets to leave out the original parent datum.

I'll look into fixing this later, but any saved characters with it selected will retain it unless we force them to change via SQL edits (undesirable).
