### ISSUE TITLE
Vetus Speculator aggro from 18 tiles out

### ISSUE THREAD

**Issue by pismorizzo** [ParadiseSS13/Paradise#19428]
**Issue Description**:

I was a tot miner early in the shift, just half an hour in, walked back into the base to eat some donk pockets. Walked back out towards the Vetus but I was keeping a healthly 2 screens from it, 17-18 tiles, the entire time when it shot outta nowhere aggroing to me resulting in my dusting. After I died I saw that someone else had agro'd it at some point and been dusted but why it would then auto aggro to me from 2 screens away is clearly not intended. 

**What did you expect to happen**: 

Megafauna are not supposed to aggro without being on screen usually its about 5 tiles but I am not sure the exact agro range but I know it aint 18 tiles. 

**What happened instead**:

It aggro'd to me from 2 full screens out, I have it all clipped and it will be posted in steps to reproduce.

**Why is this bad/What are the consequences**:

Mega fauna aggro'ing from way outside visual range should not happen.

**Steps to reproduce the problem**:

Earlier in the round I was nearly killed by an ashdrake that was around the corner I was running (there were 6-7 ash drake signals) after bolting from it into hiero arena it de-aggo'd once I got enough space between us in the arena. Returning to base I  just barely caught sight of the Vetus and it shot me instantly (odd but I didn't think much of it) it quickly de-aggro'd as I bolted away. About 8-9 minutes later one of my targets looks like they are selecting a song for their piano and so I dragged em over to a nearby goliath (I think this guy came back and ran into the vetus and got dusted before I returned.) in a lazy way to get em killed with full deniability. I went back to the mining station ate some food and donk pockets, headed back out passed 18 tiles from the Vetus saw an ore box and went to steal its ores and BAM its WARNING messaged appear'd, it was charging me from 18 tiles out. I was unable to get away and was dusted. I have the last 3 minutes clipped and cut down to the parts from I exit the mining base to just after being dusted. 

Clip: 

https://user-images.githubusercontent.com/81654328/196318356-54682611-2dc3-47fa-a146-6ae40bec7bba.mp4

**When did the problem start happening**:

Never seen it happen before so today, 10/17/2022
Never had any other Megafuana do this to me even while someone else was ACTIVELY fighting them so I assume it to be an issue with the Vetus. 

**Extra information**:

During the video pay attention to my gps which has the malf signal pulled up and shows how far it was when it charged. 

If me having aggro'd it earlier by accident was what caused it to 15 minutes later re-pick up that aggro from 18 tiles out this is still a bug. No other mega fauna will keep re-aggro'ing way later from 18 tiles out after you de-aggro. 

P.S. Don't say a damn thing about me activating windows.

**Comment by GDNgit** [comment]
I don't see anything wrong with this.
The megafauna was currently attacking someone, killed them, you walked into it's aggro range, it targeted on to you, then aggroed to you.

**Comment by pismorizzo** [comment]
Damnit just awful timing at the max possible range aye, Ill close this then.
