### ISSUE TITLE
When assassination targets cryos, you can roll them as the new target

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#19433]
**Issue Description**:

My target cryod and I got them again, and I had to ahelp to get a new target.

**What did you expect to happen**: 

Getting a valid target.

**What happened instead**:

I got a non valid target.

**Why is this bad/What are the consequences**:

You should get proper targets.

**Steps to reproduce the problem**:

1.  Be traitor.
2. Have an assassination target.
3. Have target cryo.
4. Repeat from step 2 until random chance makes this happen.

**When did the problem start happening**:

Noticed today 18.10.2022.

**Extra information**:

"Miriza Ksa" was my original target, then I saw this appear in chat.
![image](https://user-images.githubusercontent.com/25958019/196373460-df6d4651-9aee-4a20-b2f3-80389038fd15.png)
After this I had to ahelp.

**Comment by Contrabang** [comment]
https://github.com/Contrabang/Paradise/blob/cedc12f64c67ea50b1b537eca91e7e13f5a3a58d/code/game/gamemodes/objective.dm#L81-L90
this is **supposed** to be one tick after your target cryod
