### ISSUE TITLE
Dark Shard can be eaten.

### ISSUE THREAD

**Issue by tipoima** [ParadiseSS13/Paradise#19449]
**Issue Description**:

Dark shard can be eaten like a food.

**What did you expect to happen**: 

To recieve the katana implant thing.

**What happened instead**:

Shard had a bite taken out of it. I wasn't able to turn it into a katana.

**Why is this bad/What are the consequences**:

Tendril loot should not be so easily destroyed simply by not knowing how to activate it.

**Steps to reproduce the problem**:

Put dark shard in a hand. Apply to your sprite. Nomnomnom.

**Comment by matttheficus** [comment]
#18757

**Comment by GDNgit** [comment]
Pretty sure this is due to organs also being able to be eaten for some reason.
