### ISSUE TITLE
Holobadge Icon Duplication

### ISSUE THREAD

**Issue by ItsMarmite** [ParadiseSS13/Paradise#19452]
**Issue Description**:
The 'remove holobadge' icon duplicates each time you remove it and does not go away when the armour is taken off.

**What did you expect to happen**: 
The icons to go away.

**What happened instead**:
![image](https://user-images.githubusercontent.com/85680653/196968350-8213cb8e-32cb-4b35-b4bd-043f93048325.png)

**Why is this bad/What are the consequences**:
Oops, all icons.

**Steps to reproduce the problem**:
Put holobadge on armour, take holobadge off of armour. Repeat for however many icons you want. Take armour off with holobadge still on, put armour back on. AAAAAAAAAAA.

**When did the problem start happening**:
Assumedly whenever holobadges on armour was added.

**Extra information**:
N/A

**Comment by GDNgit** [comment]
Pretty easy to fix, it just needs to have the action removed on destroy

**Comment by Peterrrrrrrr** [comment]
Hi, I cannot replicate this succesfully. I seem to be able to remove it from the security armour successfully.

is there a specific armour type that you have tried this on?
