### ISSUE TITLE
Old Library in maintenance on Delta gets affected by Radiation Storm event

### ISSUE THREAD

**Issue by ArcZelf** [ParadiseSS13/Paradise#19489]
**Issue Description**:

The Old Library area in Delta maints does not get shielded from the radiation storm.

**What did you expect to happen**: 

I expected to be safe from the radiation storm in the old library found in maints.

**What happened instead**:

It turned fucking green

**Why is this bad/What are the consequences**:

People should be guaranteed safety from the radiation storm in maints. "Maintenance is best shielded from radiation"

**Steps to reproduce the problem**:

>Open server and load Delta
>Trigger Radiation event
>Head to the Old Library area in maints
>Engulfed in green

https://user-images.githubusercontent.com/108688684/197396600-c4e78e99-b09a-479d-8e71-1f97b29b21e1.mp4

![oldlibrary](https://user-images.githubusercontent.com/108688684/197396697-2528b009-e985-4bb2-bb0d-a76027abf52d.png)

**When did the problem start happening**:

I noticed this yesterday when a radiation storm hit and people in old library were getting hit by radiation where they should have been safe.

**Extra information**:

noe

**Comment by warriorstar-orion** [comment]
This seems like a bug. I can't think of why you'd want to exclude that room specifically from radstorm protection.

**Comment by S34NW** [comment]
100% an oversight using the wrong area
