### ISSUE TITLE
Item plurals in kitchen machine TGUI are presented incorrectly

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#19486]
**Issue Description**:

The more of one kind of item you add, the more 's'es get added to the end of the ingredient description.

**What did you expect to happen**: 

The plural to remain the same past two items.

![Paradise Station 13-22_39_41](https://user-images.githubusercontent.com/59303604/197374333-63af440b-dcce-47fe-86ea-627a283a50f2.png)

**What happened instead**:

Every item adds a new 's'.

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

**When did the problem start happening**:

**Extra information**:

**Comment by Sirryan2002** [comment]
@Contrabang I think this is you right?

**Comment by Contrabang** [comment]
> @Contrabang I think this is you right?

swear i fixed this but yeah. Very busy with college right now but I'll try to get around to it when I have time
