### ISSUE TITLE
Lighting is a little wonky after rebuilding floor.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#1950]
Far as I can tell, there was an explosion. Went in, re-tiled the floors, lighting shenanigans ensued. Portable lights like the seclite and PDA light didn't update the light on the tiles, but a drone building new lights did the trick.

Mesons
![image](https://cloud.githubusercontent.com/assets/6721066/9671826/a8a4d19e-5263-11e5-9919-879561063016.png)

No mesons.
![image](https://cloud.githubusercontent.com/assets/6721066/9671829/b25401c4-5263-11e5-9d5f-659ce0b98eeb.png)

Standing in the infinite darkness with PA light on. (drone built one light to the east.)
![image](https://cloud.githubusercontent.com/assets/6721066/9671945/9c16440c-5264-11e5-906d-ea50fe652632.png)

**Comment by RomanaTColgate** [comment]
I see this all the damn time.  It's awful, infinite darkness.

**Comment by NTSAM** [comment]
I get a bit of a chuckle out of it when people start dumping lamps and flashlights into the square hastily

**Comment by SpaceTimeNow** [comment]
Yes please, this is very annoying
