### ISSUE TITLE
Revenents do not get the SSD warning when attempting to drain SSD individuals.

### ISSUE THREAD

**Issue by Alantodne** [ParadiseSS13/Paradise#19520]
**Issue Description**:
As a Revenant, you can drain the souls of SSD individuals without getting the warning.

**What did you expect to happen**: 
Clicking on a SSD individual to get the "the person is SSD warning"

**What happened instead**:
No warning was recieved.

**Why is this bad/What are the consequences**:
You arent warned that you are about to commit a SSD felony when you are about to. 

**Steps to reproduce the problem**:
As a revenant, click on a individual to drain their soul. Recieve no SSD warning.

**When did the problem start happening**:
Probably since revenant birth. 

**Extra information**:

**Comment by warriorstar-orion** [comment]
Can confirm that the codepath for SSD warnings is skipped during a revenant Harvest call.
