### ISSUE TITLE
Warning when hosting a server without having ruins enabled

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#19524]
`## WARNING: couldn't find shuttle with id: whiteship in code/controllers/subsystem/shuttles.dm at line 90 src: Shuttle usr: .`

**Steps to reproduce the problem**:
Run a server while ruins are disabled

**When did the problem start happening**:
Awhile
**Extra information**:
Shows up on unit tests

**Comment by Sirryan2002** [comment]
Not an issue, this is just server runtime warning that's purely for debug. It won't ever occur in production unless the host fucks up the config.

```toml
# The following is the white ship ruin. Its force-spawned and is required to stop SSshuttle runtiming on startup
# Its also important incase a white-ship console is ever built midround
# DO NOT DISABLE THIS UNLESS YOU HAVE A GOOD REASON
"_maps/map_files/RandomRuins/SpaceRuins/whiteship.dmm",
```
