### ISSUE TITLE
Transforming into a different species while wearing hard suit might stop you from using auto mender forever

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#19541]
**Issue Description**:

A bit hard for me to test, and also I had this happen on a different occasion, but I dont think I changed species back then, so might be unrelated.
You get the error message for not having any skin exposed when you were wearing a hard suit, changed species, took off the hard suit, and then try to use an auto mender.

**What did you expect to happen**: 

To be able to use auto menders even after changing species.

**What happened instead**:

Got error saying I didnt have any exposed skin.

**Why is this bad/What are the consequences**:

Not wearing hard suits should be recognized.

**Steps to reproduce the problem**:

1. Wear hard suit.
2. Change species. (I used Envy's knife to turn into a skeleton, but that other time there might have been an unathi virus going around during a blob round?)
3. Take off hard suit (I took off everything).
4. Try to use an auto mender.
5. Look at chat.

**When did the problem start happening**:

Noticed a few days ago.

**Extra information**:

**Comment by Christer2222** [comment]
You're probably right about the skeleton case, the same thing happened when I turned into a lich playing as a wizard. Though the unathi virus situation still stands (if that was a thing). Might actually not have anything to do with hardsuits at all, or maybe its even related to #19169. All I remember from that other time was that I was wearing a hardsuit and got knocked out by some blob chemical, then couldn't be automended despite stripping fully.

**Comment by Christer2222** [comment]
Another possibility to make this not a bug; there might have been a DNA vault on the station and I might have picked hardened skin. I don't remember, but if that was the case, I might have just gotten confused.

**Comment by silverplatedelta** [comment]
Code appears to be functioning as intended. Thank you for filing the report.
