### ISSUE TITLE
Dead Xeno Queens Cannot Be Dragged

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#19547]
**Issue Description**:
Dead xenomorph queens are unable to be dragged around

**What did you expect to happen**: 
To be able to drag the dead queen around

**What happened instead**:
I got the "xenomorph queen is too heavy!" message when i tried to pull it

**Why is this bad/What are the consequences**:
You can't move the corpse around for recovery or dissection

**Steps to reproduce the problem**:
1. Get a xenomorph queen
2. See that it can't be dragged normally
3. Kill the queen
4. See that the queen still can't be dragged despite being dead

**When did the problem start happening**:
Almost certainly after the xenomorph queen buff PR #19106 which made the queens unable to be pushed/pulled

**Extra information**:

**Comment by GDNgit** [comment]
Intended

**Comment by Leanfrog** [comment]
Intended as said above
