### ISSUE TITLE
Terror Spiders lack spawn instructions

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#19546]
**Issue Description**:

After way too many rounds of watching brown terrors not do their one job, I realized that terrors don't get useful instructions similar to other antags.

Compare:

### Blob
![Paradise Station 13-13_26_25](https://user-images.githubusercontent.com/59303604/198845629-60a27c78-65e4-434d-a4e3-8703525a2b7a.png)

### Morph
![Paradise Station 13-13_33_13](https://user-images.githubusercontent.com/59303604/198845630-6fe462dd-389e-4aa6-8353-fdd712b8e7dd.png)

### Slaughter Demon
![Paradise Station 13-13_34_18](https://user-images.githubusercontent.com/59303604/198845631-2a55fd84-22cd-42c5-b812-46042621abdc.png)

### Terror Princess
![Paradise Station 13-13_35_27](https://user-images.githubusercontent.com/59303604/198845632-93e679c1-aa68-4fe6-939c-c3cb0ab6396d.png)

**What did you expect to happen**: 

Players spawning into terrors should get a brief description of their purpose, objectives, class, and abilities.

**What happened instead**:

Players spawning into terrors are only given a wiki link to peruse before engaging in the game mechanics.

**Why is this bad/What are the consequences**:

Terrors should spawn in and have an immediate understanding of the role their specific spider plays in the game mode.

**Steps to reproduce the problem**:

Just enable all your preferences and fiddle with the event manager and force a bunch of stuff and spawn into a bunch of stuff and look at the words

**When did the problem start happening**:

I don't think any spawn instructions were ever here

**Extra information**:

**Comment by Sirryan2002** [comment]
This is a "feature request" as in something that's the author of the report is asking to be added, but that doesn't take away from the fact that this is still an issue.

**Comment by warriorstar-orion** [comment]
Fixed by #19564 .
