### ISSUE TITLE
Handheld crew monitor long names overlaying

### ISSUE THREAD

**Issue by Venuska1117** [ParadiseSS13/Paradise#19555]
**Issue Description**:
unable to tell name of person, because of overlaying long names

**What did you expect to happen**: 
because i can't check job and name of person

**What happened instead**:
Names overlaying

**Why is this bad/What are the consequences**:
its sometimes hard to tell what name it is

**Steps to reproduce the problem**:
1. use map in handheld monitor
2. look at too long name
3. try quess what its written

**When did the problem start happening**:
When playing as medic

**Extra information**:
Photo given.
![image](https://user-images.githubusercontent.com/89580971/198877774-332f04a3-1346-4edb-a0f1-99cbf099c779.png)

**Comment by Sirryan2002** [comment]
I don't even know how I would begin to approach fixing this tbh

**Comment by Venuska1117** [comment]
i have 3 ideas, but i am not codder so i will just give you ideas:

1. You can increase capacity of text in one line (just making it longer)
2. You can make names decrease in size (the font) depending how long name is.
3. You can add second line, so when name is too long, it will be dropped line below, Example:

- (captain) Kuubo Limo
   Se Liou Dingo

**Comment by Christer2222** [comment]
This probably happens with all monitors. Here is an image from the atmospherics computer.
![image](https://user-images.githubusercontent.com/25958019/205391408-8e45ac7a-dbe2-4574-a3c2-3217469f44bc.png)
