### ISSUE TITLE
Jestosterone leaving the system disables your clown shoes

### ISSUE THREAD

**Issue by FloFluoro** [ParadiseSS13/Paradise#19583]
**Issue Description**:

As a Clown wearing clown shoes, you will stop waddling if Jestosterone leaves your system, even if you're wearing clown shoes with waddle toggled on. You need to take off your shoes and turn off waddle dampeners to reenable the waddle.

**What did you expect to happen**: 

For me to continue waddling as normal, despite Jestosterone leaving my system.

**What happened instead**:

I stopped waddling, a serious crime in Clown culture

**Why is this bad/What are the consequences**:

I have become a pariah among clownkind because I stopped waddling

**Steps to reproduce the problem**:

1. Be Clown
2. Imbibe Jestosterone
3. Let Jestosterone leave your system
4. You will stop waddling

**When did the problem start happening**:

N/A

**Extra information**:

Honk

**Comment by warriorstar-orion** [comment]
Can reproduce, used a jest patch and lost my waddle
