### ISSUE TITLE
Progress Bars Issues

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1959]
Just a report for any issues with progress bars; for the most part, these seem to function exactly as intended...that said, there are a few known things that lack progress bars, which is the main point of this issue report.

Current things missing:

- Construction of objects

**Comment by tigercat2000** [comment]
I'm not quite sure what you mean by 'construction of objects'; Machine construction, tablecrafting?

**Comment by Fox-McCloud** [comment]
Things made with metal sheets such as machine frames, computer frames, etc---that sort of thing.

**Comment by FalseIncarnate** [comment]
Disassembling wooden tables (wrench on built table structure, not on parts) does not have a bar. Metal tables did seem to have a bar however.

**Comment by Tastyfish** [comment]
Disassembling wooden tables will now have a progress bar due to #4150

**Comment by Crazylemon64** [comment]
@Fox-McCloud The progress bar in the inventory when constructing girders and machine frames is kind of hard to see, but displayed above the metal sheets themselves. It might be better to put that progress meter above the person, instead.

**Comment by Tastyfish** [comment]
I believe that's what do_mob() does

**Comment by CrAzYPiLoT-SS13** [comment]
Close?
