### ISSUE TITLE
His Grace continues to eat its user upon satiation.

### ISSUE THREAD

**Issue by ItsMarmite** [ParadiseSS13/Paradise#19605]
**Issue Description**:
His Grace continues to tally blood lust for each person to kill once sated.

**What did you expect to happen**: 
Blood lust to pause upon somehow killing 25 people.

**What happened instead**:
I got eated.

**Why is this bad/What are the consequences**:
I should be able to kill 150 people without my green god trying to murder me.

**Steps to reproduce the problem**:
Spawn in his grace. Kill 25 skrells. Kill 150 more.

**When did the problem start happening**:
Probably when New His Grace was merged.

**Extra information**:
:(

**Comment by warriorstar-orion** [comment]
Was this related to the conversation about how His Grace works when mobs don't have clients? It sounded like this was intentional if the skrell didn't have players attached.

**Comment by warriorstar-orion** [comment]
@ItsMarmite ping
