### ISSUE TITLE
Glitched Character Occurance

### ISSUE THREAD

**Issue by Trinityofhell** [ParadiseSS13/Paradise#19601]
**Issue Description**:

My uniform had glitched out and I had a invisible blueshield uniform despite me not actually wearing the jumpsuit

**What did you expect to happen**: 

I put on my gear and i thought it wouldnt bug out?

**What happened instead**:

My gear glitched out and I couldnt put anything in my pockets nor did I have a uniform slot filled being unable to wear the uniform despite my character having the uniform visually on

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

All I know is that I put my gear on too fast after being given my uniform by another person

**When did the problem start happening**:

11/4/2022 at around 7PM 

**Extra information**:

Try being sick with toxins and stunned from throwing up while trying to grab the uniform from another person's give action

**Comment by warriorstar-orion** [comment]
Which uniform was it specifically?

**Comment by Trinityofhell** [comment]
> Which uniform was it specifically?

It was the Blueshield uniform I had on and I dont really have much other info than what I stated

**Comment by silverplatedelta** [comment]
Likely fixed with the give refactor. Thank you for the report!
