### ISSUE TITLE
Stealthmin account name is revealed when they talk in dsay

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1961]
To be clear, their stealth name is revealed.

**Comment by tigercat2000** [comment]
Intentional, kinda, probably should just use no name.

**Comment by Regen1** [comment]
perhaps just "Administrator" like it does in the adminhelp replies

**Comment by Alex6511** [comment]
@Regen1 Actually if you click on "Administrator" in the ahelp in the top of the box it says the admins real name there too.

**Comment by Spacemanspark** [comment]
It does.

**Comment by Fox-McCloud** [comment]
Yeah...stealthmin needs a LOT of work.

**Comment by TheDZD** [comment]
I believe that tgstation/-tg-station#9572 fixes the PM issue.

**Comment by Markolie** [comment]
I'll make it so using dsay shows "Administrator" when stealthed. If you talk as a stealthmin regularly in dsay the fake ckey will still show up though, as that's intended behaviour.
