### ISSUE TITLE
Closets are now nuclear proof

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#1962]
Not sure if this is a feature, but I hope it is.

In case of Nuclear Detonation, hide in a closet.

All Nanotrasen Closets are supplied by Vault Tec, Revolutionizing safety for an uncertain future.

No longer you need any of our old fashion vaults, just get your Vault Tec brand closet in every room and survive an barage of nuclear bombs.

**Comment by taukausanake** [comment]
If this isn't a feature it better be made into one. I want to be Indiana Jones one day even if no one liked that movie

**Comment by Markolie** [comment]
The code that handles killing mobs after the explosion is very simple and simply doesn't check for people in containers. As such, more of a feature request.

**Comment by Spacemanspark** [comment]
Let's keep this, I like muh indiana jones references.
...Maybe just limit it to actual refrigerators though.

**Comment by tigercat2000** [comment]
I swear the nuke used to search closets specifically.

**Comment by Markolie** [comment]
Mhm, actually, looks like it does. Never mind.

**Comment by SpaceTimeNow** [comment]
That lockers will protect from a nukes is ridiculous, you need a lead fridge, obviously.

**Comment by taukausanake** [comment]
Make upgraded lockers then or something. The secure lockers if anything else. Just make sure you can lock/unlock from the inside. Shouldn't be hard if you can use a multitool inside it but that's another topic

**Comment by KasparoVy** [comment]
Lmfao, add a recipe for making 'reinforced lockers' out of plasteel or something
That'd be hilarious.

**Comment by SpaceTimeNow** [comment]
:+1: for reinforced reinforced Vault-Tec lockers

**Comment by Crazylemon64** [comment]
This is fixed.
