### ISSUE TITLE
Slime People Medical Records

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#1963]
I have recently found out that accessing Slime People medical files will cause you to crash. Clicking on one will cause the page to load, but the crew image doesn't, then Dream Seeker will crash. When you re-enter and look at the monitor it will successfully load the page without a crash, however.

**Comment by Crazylemon64** [comment]
This is a general bug with most records - probably some busted thing in BYOND's image rendering

**Comment by Tastyfish** [comment]
It would be good to know if it still does or not; 510 in particular has made several changes to image rendering and network propagation.

**Comment by Fox-McCloud** [comment]
I still crash all the time with sec records---so do a lot of players; ones that are running 510 or not.
