### ISSUE TITLE
Vulpkanin points don't cover hands.

### ISSUE THREAD

**Issue by CodeDingus21** [ParadiseSS13/Paradise#19630]
**Problem Description**:
Vulpkanin points don't seem to work with the hands.

**What did you expect to happen**: 
Hands to be brown along with the feet.

**What happened instead**:
How is what happened different from what you expected?
Hands are not brown.

**Why is this bad/What are the consequences:**
It looks really weird.

**Steps to reproduce the problem**:
Make vulpkanin character with vulpkanin points, or any variation of it.

**When did the problem start happening**:
About a month or so ago?

![oops](https://user-images.githubusercontent.com/18562609/200218651-6ec5cbc7-6670-4bc8-ba04-c83382aa292d.png)

**Comment by GDNgit** [comment]
If this is only the case in the character creator, it's just a layering issue

**Comment by Contrabang** [comment]
being fixed by #19614

**Comment by Contrabang** [comment]
Fixed by #19724
