### ISSUE TITLE
Security Belts Change Color with Cable Cuffs in it.

### ISSUE THREAD

**Issue by QuadDevil** [ParadiseSS13/Paradise#19645]
**Issue Description**: Security belts change color to the color of cable cuffs put in them.

**What did you expect to happen**: My cable cuffs to be stored in the belt

**What happened instead**: The cuffs were stored, but my belt turned a solid BLUE

**Why is this bad/What are the consequences**: My belt became solid blue/yellow/GREEN

**Steps to reproduce the problem**:
1. Get a Security Belt
2. Make a colorful arrangement of cable cuffs
3. Choose a color and place that in it.
4. Change your security belts colors to represent your mood by putting them in the belt.
5. Removal of cuffs returns it to how it originally was

**When did the problem start happening**: Within the last few weeks I believe

**Extra information**: You can't make your security belt a rainbow, it only takes the first color inputted(If only though). And yes, it goes back to normal when the cable cuffs are removed from the belt

**Comment by Coolrune206** [comment]
Able to replicate. White cable cuffs do not alter the color of the belt. Might be related to the fact that the cable restraints do not have a model on the security belt to color so they default to coloring the belt itself?
