### ISSUE TITLE
Throwing a Proto-Kinetic Accelerator with bayonet and flashlight adds some weird rotation to the sprite

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#19651]
**Issue Description**:

When you throw a Proto-Kinetic Accelerator (KA) with a flashlight and a bayonet, the bayonet and the flashlight detaches during the throw animation.

**What did you expect to happen**: 

For the sprites to have the same orbit/rotation.

**What happened instead**:

Sprites rotating at different speeds/orbits.

**Why is this bad/What are the consequences**:

It looks bad.

**Steps to reproduce the problem**:

1. Put a bayonet and a flashlight on a KA.
2. Throw it.

**When did the problem start happening**:

Noticed today 10.11.2022.

**Extra information**:

The sprites have rotated all the way into the wall. They do fix themselves when the animation is done.
![image](https://user-images.githubusercontent.com/25958019/200962604-70fa985a-751b-4a97-8f53-473176e82304.png)

**Comment by warriorstar-orion** [comment]
Can reproduce. 

https://user-images.githubusercontent.com/59303604/201561837-964bf032-c85d-4433-ad56-b22f283b274a.mp4

Don't have the slightest clue where to begin diagonising this.
