### ISSUE TITLE
field generators can bug out and be stuck at 50% capacity

### ISSUE THREAD

**Issue by restedwaves** [ParadiseSS13/Paradise#19657]
**Issue Description**:

field generators can bug out and be stuck at 50% capacity stopping them from turning on or being removed

**What did you expect to happen**: 

them to either charge to full and link to the others of not charge at all

**What happened instead**:

it was stuck at 50 percent and refusing to link

**Why is this bad/What are the consequences**:

tesla and singulo containment failures or being completely unable to start containment

**Steps to reproduce the problem**:

honestly i have no idea how this happened or what could cause it

**When did the problem start happening**:

dont remember even the rough date of the last time i did tesla

**Extra information**:

bad screen shot i know but the round ended before i could get a better one, the lower generator is completely discharged too
![image](https://user-images.githubusercontent.com/90993960/201119898-520fa5d8-ed74-4939-87a6-2d1aae2765ad.png)

**Comment by warriorstar-orion** [comment]
Without reproduction instructions it will be challenging to pin down exactly what happened here. Could you recall anything about the setup of the engine, or any other strange behavior you saw?

**Comment by restedwaves** [comment]
unfortunately no, it was like that by the time i arrived, the other engineer denied even setting up the engine but all the emmiters were on albeit uncharged and the tesla was wrenched, as far as i can tell the issue was the reason whoever was setting it up stopped, im surprised they didnt submit a report themselves honestly.

i doubt this would have any bearing on it but i replaced the tesla generator with a singulo one before beginning to seriously look at the field.

perhaps power up the field and let it discharge and that would replicate it?
