### ISSUE TITLE
IPC cavity surgery gets stuck if the patient loses the limb in the process

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#19661]
**Issue Description**:

If an IPC loses their limb during cavity surgery (and maybe, all surgery? Did not test it), the limb cannot be re-attached, as the previous surgery does not get cancelled.

**What did you expect to happen**: 

When a limb is lost, that surgery should stop.

**What happened instead**:

The IPC's head could not be re-attached, as it still had a cavity implant going on.

**Why is this bad/What are the consequences**:

That limb section was forever lost.

**Steps to reproduce the problem**:

1. Put IPC on table (normal table)
2. On the mending step (cautery/welding tool), fail repeatedly
3. Wait until person gets decapped
4. Notice you cannot put their head back on as the operating console still says you have a cavity procedure ongoing in the head zone

**When did the problem start happening**:

Noticed it in round 33466

**Extra information**:

None

**Comment by warriorstar-orion** [comment]
Is there a guaranteed way to fail steps? I don't know robotics/surgery that well.
