### ISSUE TITLE
Bugged Job Titles due to Lack of Retroactive Fix

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#1968]
Occasionally, you might see a player join the game with a job such as `Chemist=Pharmacologist&Medical+Doctor=Nurse`. There was a fix to this issue made a while ago, but it didn't apply to characters with alt titles that were already broken and do not get changed.The issue likely requires either clearing the SQL column or running a script to fix the broken titles.

**Comment by Crazylemon64** [comment]
Has this been fully expunged?

**Comment by TheDZD** [comment]
Yes.

**Comment by FlattestGuitar** [comment]
A bit of an icky ocky, so I blurred it out, but it seems this is still happening.

![](https://i.gyazo.com/3eea2d63263c53c309d8ab86e6822fa3.png)

**Comment by Spacemanspark** [comment]
Ya, I still see this from time to time.

**Comment by TheDZD** [comment]
Huh, could've sworn I had fully expunged all of those from the database a few weeks ago.
