### ISSUE TITLE
new gas mixers and digital valves dont seem to work

### ISSUE THREAD

**Issue by restedwaves** [ParadiseSS13/Paradise#19681]
**Issue Description**:

new gas mixers and digital valves dont seem to work

**What did you expect to happen**: 

if one breaks and is replaced it wont move gas, new limiters dont unlock

**What happened instead**:

it should mix gas for use elsewhere

**Why is this bad/What are the consequences**:

possible completely disabling atmos, making toxins even more impossible

**Steps to reproduce the problem**:

place any of these on the network, choke to death because the new air mixer does not output the air mix

**When did the problem start happening**:

**Extra information**:

**Comment by AffectedArc07** [comment]
Did you make these in escape by any chance?

**Comment by restedwaves** [comment]
no i was trying to get the turbine online
