### ISSUE TITLE
Extreme amounts of lag while using the Mhelp respond function

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#19694]
**Issue Description**:
Title, slows your game to a crawl

**What did you expect to happen**: 
Not my game screaming in pain

**What happened instead**:
My game screaming in pain before crashing

**Why is this bad/What are the consequences**:
my poor game

**Steps to reproduce the problem**:
1. Get an mhelp sent in
2. Use the respond function by clicking on their name
3. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**When did the problem start happening**:
Pretty recent, not longer than a week ago

**Comment by warriorstar-orion** [comment]
I don't suppose you can pin down the round ID so we can check the profiling stats?

**Comment by GDNgit** [comment]
> I don't suppose you can pin down the round ID so we can check the profiling stats?

Think I made this issue after round 33492

**Comment by warriorstar-orion** [comment]
No similar instances in two weeks, closing for now.
