### ISSUE TITLE
Botany issue - Potato plant sprite goes invisible at certain growth stages

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#1970]
![asdasdasdasdadsa](https://cloud.githubusercontent.com/assets/13933611/9706366/dd6b780a-54da-11e5-84df-c77b52450d34.png)

Just a quick image of the issue, it is visible at other stages (as you plant it and a few other bits) but it just goes invisible at times.

**Comment by TheDZD** [comment]
@FalseIncarnate

**Comment by FalseIncarnate** [comment]
Likely a mixup with a plant state icon being misnamed or missing, will investigate with some upcoming tweaks to botany

**Comment by taukausanake** [comment]
There are a few plant icons like this I believe. I don't remember which ones but I'm pretty sure potatoes aren't the only one

**Comment by RomanaTColgate** [comment]
I've seen this with potatoes and a few other plants, yes.
