### ISSUE TITLE
Hosting in Ubuntu (runtime errors)

### ISSUE THREAD

**Issue by Denveous** [ParadiseSS13/Paradise#19736]
**Issue Description**:

Not sure how else to address this I had been hosting Paradise for a month and had to wipe the slab I host on clean, in the process of coming back I installed Byond and did everything as I did before and I'm getting an error everytime I start Paradise through DreamDaemon which seems to related to multiple files within paradise code. I am all out of ideas and google is 10000000% useless when googling this error, besides people telling me to use the trusted parameter (which I already have tried using EVERYthing it seems like including that). 

**What did you expect to happen**: 

The server to start.

**What happened instead**:

_Multiple runtime errors occur:_

runtime error: /usr/local/lib/libbyond.so: undefined symbol: log_write
Runtime in rust_g.dm,187: /usr/local/lib/libbyond.so: undefined symbol: shutdown_http_client
Runtime in rust_g.dm,248: /usr/local/lib/libbyond.so: undefined symbol: redis_disconnect

**Why is this bad/What are the consequences**:

The server literally won't run, this could potentially affect most people using the code.

**Steps to reproduce the problem**:

Download ANY byond linux zip, extract and install.
Clone the paradise git, compile with DreamMaker and then run the dmb. 

**When did the problem start happening**:

Immediately after a FRESH install of Ubuntu. (and yes I've added the i386 prerequisites and everything, and yes it worked prior to the reinstall)

**Extra information**:

OS: Ubuntu 22.04.1 LTS
Full log of the crash: https://pastebin.com/rWFCKwmT
_inb4 troll comments like ("use CentOS" or "why are you using ubuntu?"), this is NOT up for discussion._

**Comment by AffectedArc07** [comment]
We dont support linux really, but in this case ill try assist.

Can you give me the output of `ldd librust_g.so`?

**Comment by Denveous** [comment]
> 

# ldd librust_g.so
        linux-gate.so.1 (0xf7f53000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libz.so.1 => not found
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7751000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf774c000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7644000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf763f000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf740a000)
        /lib/ld-linux.so.2 (0xf7f55000)

**Comment by AffectedArc07** [comment]
Try installing the following deps:

`apt-get install libssl-dev:i386 pkg-config:i386 zlib1g-dev:i386`

**Comment by Denveous** [comment]
Resolved by abandoning Paradise for another code base. Thanks for trying to help anyways though, was good while it lasted :)
