### ISSUE TITLE
Can't Sell Plasma

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1974]
Simply put, any plasma you put on the shuttle is not sold, at all; doing so just deletes the plasma without any benefit.

This is quite detrimental to the relationship between cargo and mining as mining literally can't help cargo get more supply points when it's absolutely needed.

No idea when this cropped up.

@Markolie

**Comment by Taaketa** [comment]
Really? It was about 2 days ago I put plasma on the shutrle boosted points to 900. Did you put the plasma in a closed crate? That worked for me.

**Comment by Fox-McCloud** [comment]
Will definitely double check, but I didn't appear to be getting any points for crates, either.

**Comment by Fox-McCloud** [comment]
Alright, it has to be IN crates. Derp fox is derp.

**Comment by tigercat2000** [comment]
This is still relevant, it should probably check for non-crated-plasma too.
