### ISSUE TITLE
Chatbox breaks when closing extra windows

### ISSUE THREAD

**Issue by Groudonmaster** [ParadiseSS13/Paradise#19767]
**Issue Description**: When playing as a drone having additional windows such as power monitor or alerts monitor open and then closing them by pressing the x button on the window will immediately white out the text box. Only solution is to restart the game I've found.

**What did you expect to happen**: The alerts window to close without any additional changes

**What happened instead**: Chat becomes useless until restart.

**Why is this bad/What are the consequences**: Rather self explanatory. Chat becomes useless or you don't use robot commands.

**Steps to reproduce the problem**: 
1. (UNKNOWN IF OPTIONAL) Join as drone
2. Use show alerts command
3. Close Alerts window
4. Become unable to use chat until restarting

**When did the problem start happening**: First observed 23/11/2022

**Extra information**: I don't remember this happening on cyborg and this is potentially a hardware issue.

Specs:
AMD Ryzen 5 3600 CPU
MSI RTX 2070 Super GPU
MSI B450 Tomahawk Mobo 
Running Windows 11 OS Version 21H2

**Comment by Groudonmaster** [comment]
![Screenshot_20221123_102035](https://user-images.githubusercontent.com/16804362/203693689-8354aaab-c1e8-4d5d-9035-27e486e92832.png)
![Screenshot_20221123_102114](https://user-images.githubusercontent.com/16804362/203693695-ebac0681-27b3-401f-a281-56f0fd19881b.png)
![Screenshot_20221123_102159](https://user-images.githubusercontent.com/16804362/203693698-d90e34c8-e484-41c7-adc4-0b621de4230b.png)

**Comment by GDNgit** [comment]
Cannot reproduce, clear your byond cache to see if that helps.

**Comment by Groudonmaster** [comment]
Attempted troubleshooting already includes:

Clearing byond cache
Updating byond
Reinstalling byond
Restarting computer
Restarting network device

**Comment by GDNgit** [comment]
> Attempted troubleshooting already includes:
> 
> Clearing byond cache Updating byond Reinstalling byond Restarting computer Restarting network device

Clear IE cache if you haven't done so already, if not this is probably hardware specific and might just go away with time

**Comment by Groudonmaster** [comment]
Reinstalling BYOND a second time resolved the issue. Unknown cause and unable to replicate further. Assuming it was user error at this point somehow.
