### ISSUE TITLE
Blowing up chasms on lavaland might reveal lattice.

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#19760]
**Issue Description**:

When blowing up chasms on lavaland lattice might get revealed.

**What did you expect to happen**: 

Explosions shouldn't affect chasms at all, as they are holes.

**What happened instead**:

I could see lattice and lava (baseturf).

**Why is this bad/What are the consequences**:

Breaks immersion. Doesn't seem to drain atmos though.

**Steps to reproduce the problem**:

1. Get a chasm on lavaland.
2. Blow up gibtonite nearby. (think I tested with 2 or 3 squares)
3. Hope lattice gets revealed.

**When did the problem start happening**:

Noticed today 23.11.2022.

**Extra information**:

Might be related to #17829
![image](https://user-images.githubusercontent.com/25958019/203458866-6818dd12-c205-414f-b95c-5006ab3c2ef0.png)

**Comment by Sirryan2002** [comment]
```
/turf/simulated/floor/ex_act(severity)
	if(is_shielded())
		return
	switch(severity)
		if(1.0)
			ChangeTurf(baseturf)
		if(2.0)
			switch(pick(1,2;75,3))
				if(1)
					spawn(0)
						ReplaceWithLattice()
						if(prob(33)) new /obj/item/stack/sheet/metal(src)
				if(2)
					ChangeTurf(baseturf)
				if(3)
					if(prob(80))
						break_tile_to_plating()
					else
						break_tile()
					hotspot_expose(1000,CELL_VOLUME)
					if(prob(33)) new /obj/item/stack/sheet/metal(src)
		if(3.0)
			if(prob(50))
				break_tile()
				hotspot_expose(1000,CELL_VOLUME)
	return
```
this is why, Chasm doesn't have its `ex_act()` overridden
