### ISSUE TITLE
Bluespace Technology Disks?

### ISSUE THREAD

**Issue by YoureNotTheSharpest** [ParadiseSS13/Paradise#19768]
**Issue Description**:
Research disks provide levels of the RND console (to central) after they have been saved.

**What did you expect to happen**: 
for when I send a level 1 disk of toxins to get paid 0 credits

**What happened instead**:
I sent a level 1 toxins disk and was paid 270 credits of level 7 credits

**Why is this bad/What are the consequences**:
RnD can send over level 1 disks and announce when they have 5s for cargo to send the level 1s for the 5s credits. This can also lead to cases where cargo hoards the first waves of disks untill RND sends a new pair like 7s to be sent, and then send the 5s for the 7s credits, leaving cargo with a 'backup' of RNDs levels.

**Steps to reproduce the problem**:
>save level 1 toxins tech to disk
>do toxins successfully
>save to a differing disk toxins 7
>Ship off the "Level 1" toxin disk
>watch the Central Command message Log report you getting 270 credits?

**When did the problem start happening**:
Unknown

**Extra information**:

**Comment by Sirryan2002** [comment]
You are positive that a disk with toxins 1 was delivered and there was not any other disk on the shuttle with toxins 7 loaded on it?

**Comment by YoureNotTheSharpest** [comment]
I had, on the test server, while recording values of credits per research level had saved 7 toxins level disks, from 1 to 7.

I can be certain that when I shipped the level 2 toxins disk it was alone in the single crate i had shipped.

**Comment by YoureNotTheSharpest** [comment]
I had not shipped a level 1 forsay but i am in doubt that it would be any different between a level 1 and 2, least looking at it from this being independent of level of the disk itself.

**Comment by YoureNotTheSharpest** [comment]
But I am certain the credits stolen by the level 2 was of atleast level 7 as i had next cycle shipped a level 7 disk and it returned 0 additional credits.

**Comment by YoureNotTheSharpest** [comment]
I wonder if this works in reverse

**Comment by DGamerL** [comment]
This can happen because the disks have the same research datum as the Protolathe

**Comment by warriorstar-orion** [comment]
Fixed by #25653.
