### ISSUE TITLE
Cargo Console not recognizing non-standard job names

### ISSUE THREAD

**Issue by tipoima** [ParadiseSS13/Paradise#19779]
**Issue Description**:

Having a job name that isn't a default one prevents you from paying with your department's account.

**What did you expect to happen**: 

To still have access to accounts my job can pay with.

**What happened instead**:

You only get your personal and supply's accounts.

**Why is this bad/What are the consequences**:

HoPs often edit job titles for Acting Heads, leading to a situation where, for example, Acting RD has to either beg a scientist to come to Cargo and order prototypes, or beg QM to let him use Supply's money.

**Steps to reproduce the problem**:

Have a job. Have job title changed. Realise that you lost department account access.

**Comment by Sirryan2002** [comment]
Job code will need a refactor for a viable solution to be available for this
