### ISSUE TITLE
Nuclear operative tool vendor requires money

### ISSUE THREAD

**Issue by Daylight2** [ParadiseSS13/Paradise#19776]
**Issue Description**:
Nukie tool vendor requires money

**What did you expect to happen**: 
To be able to get tools from the syndicate base tool vendor as a nukie

**What happened instead**:
Was asked for money to buy tools - nukies are communists who have no money. 

**Why is this bad/What are the consequences**:
Kind of pointless to have a tool vendor that you can't get tools from

**Steps to reproduce the problem**:
Go to nukie base, open tool vendor

**When did the problem start happening**:
Probably since the economy rework

**Extra information**:

**Comment by ItsMarmite** [comment]
POOR!
