### ISSUE TITLE
Vampires get picky about drinking blood from beakers

### ISSUE THREAD

**Issue by Scribble-Sheep** [ParadiseSS13/Paradise#19798]
**Issue Description**:
Vampires, when drinking blood from a beaker or injecting via bloodbags, suffer from bloodtype incompatibilies. (ie, a- will begin taking toxin damage after drinking a cup of a+)

**What did you expect to happen**: 
Vampires to be able to drink any blood, since they can do it just fine outta someone's neck?

**What happened instead**:
Took toxin damage and needed to dialysis the incompatible blood out of my system and pop a charcoal tab to avoid dying.

**Why is this bad/What are the consequences**:
It makes no sense. the same blood, from a monkey is fine, but out of a beaker will kill you.
It's not like it's impossible get around this, but it feels weird to have to do so

**Steps to reproduce the problem**:
Pick a vampire with a blood type that is not AB+, pour yourself a beaker of blood that isn't compatible with your own, and use a medical scanner to note your toxins level skyrocketing.

**When did the problem start happening**:
It seems like an oversight, so idk if it's new, but I caught this a few days ago while trying to test if bloodbags sated vamp hunger.

**Extra information**:
I can kind of guess why this might be? If blood bags are a type of ingestion code wise, then it could end up being a meta tell if you accidentally pumped the wrong blood into someone and they were fine, but like...idk.

**Comment by DGamerL** [comment]
This also happens for normal blood bags, not just for drinking out of beakers. I'll see if I can whip up a fix for this next week when I have more time
