### ISSUE TITLE
Runtime about job.dm when an ERT is spawned

### ISSUE THREAD

**Issue by Tourte-Yaya** [ParadiseSS13/Paradise#19801]
**Issue Description**:

Runtime in job.dm when an ERT is spawned.

**What did you expect to happen**: 

No runtime to happen

**What happened instead**:

Runtime with job.dm about an ERT and account.

**Why is this bad/What are the consequences**:

runtime bad
**Steps to reproduce the problem**:

Spawn ERT through the ERT dispatch verb. Amber was spawned on live during the runtime.

**When did the problem start happening**:

Probably due to the economy rework, unsure.
https://github.com/ParadiseSS13/Paradise/pull/19209
**Extra information**:

![image](https://user-images.githubusercontent.com/50141998/204612093-ed4a767a-ae94-43b2-b51a-053718f31abd.png)

**Comment by Eric6426-Blossom** [comment]
To add a bit more context;

ERT of Amber was called, changed their kits to one Gamma(Engi) one Red(Commander) from their repective Amber counterparts.

Here's another odd thing; Master Sergeant Schmidt is not the name of either of them, which are named differently, and no other ERT member spawned/was joined by any ghost outside of those 2 who were the only to sign up.
