### ISSUE TITLE
Husked corpses have normal hands

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#19825]
**Issue Description**:
Husked corpses have normal-coloured hands

**What did you expect to happen**: 
For a husked corpse to be uniform in it's huskness

**What happened instead**:
![image](https://user-images.githubusercontent.com/12197162/205269561-2374eb35-79c0-402f-a8cd-0d07e9752fdd.png)

**When did the problem start happening**:
Probably in https://github.com/ParadiseSS13/Paradise/pull/19490

**Comment by Sirryan2002** [comment]
when you're horrifically mutilated by laser fire but your hand care routine is on point
