### ISSUE TITLE
Ghost pepper missing New()

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#1987]
In seed_datums.dm it looks like someone tried adding in ghost peppers but forgot to give it a proper New() proc. Currently there is a second New() for ice chilies right under it so maybe they just forgot to edit it correctly. Not a bit issue, just someone throw it in a PR if they want.

**Comment by FalseIncarnate** [comment]
this was probably me derping on a copy-paste. will fix with some other botany tweaks/fixes soon.
