### ISSUE TITLE
Exosuit Fabricator can put items in inaccesible locations

### ISSUE THREAD

**Issue by PacifistDalek** [ParadiseSS13/Paradise#19899]
**Issue Description**:
Exosuit Fabricator always drops its items on the tile below it, so when it's up against a wall on its south side, it dumps those items on the same tile as the wall.

**What did you expect to happen**: 
The item to be spawned to the north, east, or west of the fabricator

**What happened instead**:
South, inside wall.

**Why is this bad/What are the consequences**:
Pain in the ass if you want to rearrange things to have the fabricator up against a south wall.

**Steps to reproduce the problem**:
Put fabricator with a wall to the south of it, use it, see item get placed on wall tile.

**Comment by Miraviel** [comment]
Obviously not a good behaviour, but for those interested in temporary fixing it - screwdriving and multitooling it rotates its output by 90°.

**Comment by matttheficus** [comment]
As Mira said, you CAN rotate it to avoid this. Im not sure if there's a nice/work-worth way to fix this when you can just change the output tile.

**Comment by silverplatedelta** [comment]
This is the default output, the direction can be easily changed with a multitool. This also occurs with the ORM and I think the coin press. Closing this issue as not planned as this has become standard behavior for some machines.
