### ISSUE TITLE
Holster hotkey invokes .holster instead of just "holster"

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1990]
Makes holsters less useful, as I believe their purpose to be the ability to quickdraw your weapon.

**Comment by Spacemanspark** [comment]
I meant to make an issue report on this long ago, but forgot.
Oops.

**Comment by TheDZD** [comment]
I believe this was done as a part of object verbs being nuked a while ago in favor of action buttons, but I have no idea why this hotkey was broken instead of just outright removed.

**Comment by Alex6511** [comment]
In this case I think it would be really nice if we could get both. At the moment the shoulder holster is nothing more than a pocket for your gun (one that can be hard to click since it's in a different spot, no less). Having a hotkey to draw your gun really quickly would be an interesting mechanic, after all the whole point of a shoulder holster in real life is the quickness at which you can draw and fire.
