### ISSUE TITLE
Cthulhu still appearing by my sprite after deconversion - Cult Icon problem

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#1991]
![cult](https://cloud.githubusercontent.com/assets/13933611/9767496/6ce2e6fc-5716-11e5-902f-393eeb337dd5.png)

I was deconverted a few seconds before that, but keep in it's just the icon, I can't reach out, pray etc.

Athena was still a Cultist for reference that I wasn't a Cultist anymore.

Just a small issue.

**Comment by Alex6511** [comment]
Did it go away after a few minutes? I think it can take a little while to update sometimes.

**Comment by DavidRossii** [comment]
It persisted till the end of the round.

**Comment by Alex6511** [comment]
Alright then. This could be related to my bug about reconverted cultist seeing AOOC.
