### ISSUE TITLE
Handcuffing one-handed people just works

### ISSUE THREAD

**Issue by cool20141** [ParadiseSS13/Paradise#19919]
**Issue Description**:

You can handcuff one-handed(Maybe even handless, didn't check) people

**What did you expect to happen**: 

Handcuffs can't be used on people with only 1 hand, because, you know, that's how handcuffs work

**What happened instead**:

Got cuffed

**Why is this bad/What are the consequences**:

Cut my arm off for nothing

**Steps to reproduce the problem**:

1. Cut your arm off
2. Try putting handcuffs on you
3. It just works

**When did the problem start happening**:

-

**Extra information**:

Don't think it's feature, because you can't even put gloves on your 1 hand(Which is strange), but handcuffs you can(Which is strange too)

**Comment by Daylight2** [comment]
Intentionally implemented in this PR: https://github.com/ParadiseSS13/Paradise/pull/11131
Being able to wear gloves on one hand might be worth having a look at though.
