### ISSUE TITLE
Its possible for a latejoining AI to spawn in a destroyed AI satalite or in a spot already occupied

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1992]
So basically, two things can happen right now. If the crew builds an AI when they don't have one at round start, and puts it in the AI core, if another AI joins they will spawn directly on top of the other AI. The second problem is the late joining process makes no check of the current status of the AI satellite. For instance, if the satellite is destroyed but the AI is recovered via a intellicard, if the old AI module is not removed, another AI can join in its place. This can occur after the AI satellite is bombed and its power is eliminated, so basically the joining AI will instantly lose power and slowly die, unable to call for help.

**Comment by Markolie** [comment]
AI's spawning on a destroyed satellite is the same as players spawning in arrivals after it's been bombed - bad luck.

**Comment by Alex6511** [comment]
The problem isn't so much the spawning on the destroyed satellite, it's that removing the AI who was previously there opens the slot for another AI to join. What happens is basically the AI dies, crew recovers it, revives it and puts it somewhere else, new AI joins, crew has to go save it, which frees the slot again so another joins... etc.

**Comment by Robertha89** [comment]
So what you are saying if someone moves the ai, we can have ai's spawn infinity in? Even during a malf round? GOD THAT WOULD BE HILLARIOUS!

**Comment by taukausanake** [comment]
AI FARM! MAKE IT SO!

**Comment by Robertha89** [comment]
Imagine this if you would, malf ai gets moved into one of the superhidden spots, and takes over every apc, a new ai joins as the crew joins together to kill the ai, the ai dies, nothing changes. 5 seconds later the nuke goes boom
