### ISSUE TITLE
AIs can become traitor-changelings

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#19940]
**Issue Description**:
In `/datum/game_mode/traitor/changeling/pre_setup()`, their restricted roles are set properly:

![image](https://user-images.githubusercontent.com/42044220/208024400-378eb788-d7c7-46e4-a72c-4a5c6d8e6631.png)

But shortly after, the parent `/datum/game_mode/traitor/pre_setup()` is called:

![image](https://user-images.githubusercontent.com/42044220/208024430-99b9fe39-df49-4295-89ac-ee219848d7a5.png)
Which removes `"AI"` from their `restricted_roles`, since the traitor gamemode does not have `"AI"` in it's `restricted_jobs`.

**Steps to reproduce the problem**:
1. Set the mode to traitor+changeling
2. Set your occupation to AI
3. Have traitor and changeling antag preferences turned on
3. Ready up, start the round

**Comment by Daylight2** [comment]
Obligatory ;HALP AI ABSORBING ME IN MORGUE

**Comment by Contrabang** [comment]
This is similar to #16067, but they technically touch on 2 different topics. However, this may have been fixed by #20106? I am not sure.

**Comment by Contrabang** [comment]
Haven't seen this in forever, fixed by #20106
