### ISSUE TITLE
Space cleaner resets the LIGHT's color to null

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1995]
This causes them to become pitch black, walking into the area with a flashlight fixes it.

**Comment by Fox-McCloud** [comment]
I don't even see why this is remotely mentioned here.

What does color have to do with lighting or space cleaner for that matter?

**Comment by Fox-McCloud** [comment]
Ok, after testing what this issue actually is:

- Space cleaner resets the LIGHT's color to null...which makes it look black.

**Comment by Alex6511** [comment]
Yeah I really had no idea what was going on, other than that after using it the tiles became black because of lighting.
