### ISSUE TITLE
Changelings can revive inside slaughter demons and attack them

### ISSUE THREAD

**Issue by Daylight2** [ParadiseSS13/Paradise#19971]
**Issue Description**:
Changelings can revive inside slaughter demons and attack them

**What did you expect to happen**: 
Changelings not being able to attack slaughter demons from the inside

**What happened instead**:
Got hit by an unavoidable armblade whenever I manifested

**Why is this bad/What are the consequences**:
There is no way to avoid the changeling hitting you after you eat them, meaning you cannot manifest without dying.

**Steps to reproduce the problem**:
Eat cling
Have cling revive
Hit manifested demon as a cling

**Comment by matttheficus** [comment]
On one hand, its kinda funny.

On the other hand, it kinda nukes a midround unless theyre careful who they attack, which MIGHT be decent for a usually murderbone-y antag.

**Comment by Daylight2** [comment]
> On one hand, its kinda funny.
> 
> On the other hand, it kinda nukes a midround unless theyre careful who they attack, which MIGHT be decent for a usually murderbone-y antag.

Demons have no way to tell if they're attacking a disguised changeling or not, and if they did, this would make them more murderboney, not less, as the usual reaction would be to team up with the cling. And anyways, I feel like it really goes against the theme of a slaughter demon to have to be picky about who you kill.

Also, on the round this happened, the cling admitted to purposefully getting killed to abuse this bug, which really doesn't give the demon any counterplay.

**Comment by Daylight2** [comment]
Why does the close issue button have a drop down symbol next to it on mobile when it closes the issue in one tap

**Comment by GoldenMustachio** [comment]
I've seen changelings readapt to use screech to stun players while inside the demon's stomach allowing them to constantly stun players while being immune to all forms of attacks, especially if the demon just remains in blood crawl.
