### ISSUE TITLE
Cere station (NSS Farragus) map incorrect

### ISSUE THREAD

**Issue by Groudonmaster** [ParadiseSS13/Paradise#19979]
**Issue Description**: Gravity generator supposed to be by engineering according to the map. It is actually slightly above arrivals

**What did you expect to happen**: 

Map to be accurate

**What happened instead**:

Map so wrong I rage ghosted just to find the room using teleport.

**Why is this bad/What are the consequences**:

Incorrect information bad please fix.

**Steps to reproduce the problem**:

View map. Attempt to locate gravity generator. Fail to locate it in game

**When did the problem start happening**:

21/12/2022

**Extra information**:

**Comment by lewcc** [comment]
This seems to be about the webmap itself being out of date, which will continue to happen until the map gets officially merged.
Since the map is only test-merged for now, please leave your feedback about it on the PR itself: https://github.com/ParadiseSS13/Paradise/pull/19951
Thanks!
