### ISSUE TITLE
Atmos deletes itself on turfs with a tiny fan after replacing the floor tile.

### ISSUE THREAD

**Issue by silverplatedelta** [ParadiseSS13/Paradise#19975]
**Issue Description**:
If the floor tile is removed on a turf with a tiny fan (admin atmos fan) the atmos on that turf is removed and becomes a vaccum.

**What did you expect to happen**: 
Atmos to remain unchanged.

**What happened instead**:
A serious violation of the first law of thermodynamics. 

**Why is this bad/What are the consequences**:
Being able to delete gas is a problem, you could delete ALOT of gas with this method.

**Steps to reproduce the problem**:
1) Walk up to turf with tiny fan. 
2) Replace floor tile. 
3) Suffocate.

**When did the problem start happening**:
Likely a very long time ago. I just noticed it this past round #33955

**Extra information**:
Issue only tested on Cere station. Unknown if its localized to this map.

**Comment by Spaghetti-bit** [comment]
Fixed with https://github.com/ParadiseSS13/Paradise/pull/25328
