### ISSUE TITLE
[Maint Drones] People re-activing maint drones can spam observers / dead people

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1998]
When maint drones are reactivated from a player leaving and them remaining entact.  A player in the station can spam the re-activation so that dead chat/observers have 5 or 6 popup messages asking them if they want to be a maint drone. Clicking "never for this round" does not remove the remain messages.

**Comment by Fox-McCloud** [comment]
Pretty sure this is the case for PAI's as well.
