### ISSUE TITLE
Catwalk/Lattice placing is broken

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#20003]
This was in round #33998

**Issue Description**:

Placing down new lattice/catwalks in game does not properly place them.

**What did you expect to happen**: 

For lattices/catwalks to auto-smooth out into their line shapes and auto-connect to map-pre gen catwalks and lattices.

**What happened instead**:

When I placed down the new lattices it did not auto-connect to the map pre-gen ones nor did they smooth out into those line ladder shape ones.  It did connect when I made a catwalk nearby but did it in a very janky way.

**Why is this bad/What are the consequences**:

Very unimmersive.

**Steps to reproduce the problem**:

Place down lattice/catwalks in space in game in the open or nearby pre-generated lattice/catwalks.

**When did the problem start happening**:

Could not say as its not something I have noticed until today.

**Extra information**:

In the first photo the red is the map pre-gen stuff and the green area is the stuff I placed.
![image](https://user-images.githubusercontent.com/24213815/209455589-7a3e1e9e-2d2b-475a-a1a8-f989dc37e43e.png)
How it looked originally, taken from the webmap.
![image](https://user-images.githubusercontent.com/24213815/209455596-397f5dc0-9c30-4c8e-af50-b7a6edd6688c.png)

**Comment by warriorstar-orion** [comment]
Is this specific to one map or all of them?

**Comment by Denthamos** [comment]
> Is this specific to one map or all of them?

It appears it was round specific and not map specific.  Guessing something broke runtime wise that round - blob round.

**Comment by DGamerL** [comment]
Heya, thanks for making the report! This has most likely been solved along the way, as it seems to have never happened again. If it does, feel free to make a new issue!
