### ISSUE TITLE
Fulton'd to nullspace

### ISSUE THREAD

**Issue by Kholdstare2** [ParadiseSS13/Paradise#20020]
**Issue Description**:

I was extracted from lavaland with a fullton but it didn't "go" anywhere and an admin had to rescue me from nullspace.

**What did you expect to happen**: 

To pop up wherever the fulton beacon was.

**What happened instead**:

Oops, all nullspace.

**Why is this bad/What are the consequences**:

Going to nulspace effectively removes you from the round without admin intervention, this is probably bad.

**Steps to reproduce the problem**:

1. Get fulton'd
2. ????

**When did the problem start happening**:

Round 34032 shortly after it started.

**Extra information**:

I wish I had more details, but I don't.

**Comment by GDNgit** [comment]
Were you given an option for location or did you just get sent to hell?

**Comment by Kholdstare2** [comment]
I was not given an option/dialog. I had a fulton attached to me, watched the animation, then nothing. Just sat there in the spot on lavaland where my body was.
