### ISSUE TITLE
Sniper rifle projectiles are not oriented to trajectory

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#20067]
**Issue Description**:

When firing a sniper round (such as the nukie-loadout one or the weapon used by the Syndie simplemobs in the depot), the projectile may not face the direction it was shot at, instead passing through space "vertically".

**What did you expect to happen**: 
Projectiles should be angled properly.

**What happened instead**:
Projectiles may be oriented towards North-South, not changing as it follows its path.

**Why is this bad/What are the consequences**:
Gross graphical glitch.

**Steps to reproduce the problem**:

Ensure the depot ruin spawns and spawn a corgi near the Syndie QM. The QM only has a 50% chance of spawning with the sniper so a few restarts may be necessary.

https://user-images.githubusercontent.com/59303604/210176627-330adcfd-b877-422b-a520-0a7726f0230f.mp4

**When did the problem start happening**:
No idea.

**Extra information**:

**Comment by Henri215** [comment]
Happens with the penetrator ammo only, no need to test with the depot ruin.
Couldnt find the source of this problem yet.

**Comment by 1080pCat** [comment]
#25636 has fixed this issue
