### ISSUE TITLE
Biogenerator "Amount to vend" can be sent to NaN

### ISSUE THREAD

**Issue by Herder05** [ParadiseSS13/Paradise#20061]
**Issue Description**:

The biogenerator can have the amount to vend field go to NaN then the field becomes flat and very hard to click

**What did you expect to happen**: 

It to go to 1

**What happened instead**:

It went to NaN then became a small line

**Why is this bad/What are the consequences**:

Random little bugs bad

**Steps to reproduce the problem**:

set biogenerator to any number from 2-9 (i have found it works best when set to 7)
hold to drag it then pull down really fast
repeat until it says NaN
let go and watch the field become line

**When did the problem start happening**:

Probably when it got tgui

**Extra information**:

**Comment by S34NW** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/23299
