### ISSUE TITLE
Voice changer displays your name over the radio

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#2009]
Apparently when speaking over the radio with a Voice changer, you appear to be talking as normal, but to everyone else they see your real name.

Tristan1333 (Max BioTek Operative 2) (follow|body) moans, " [Common] Sarea Elderway exclaims, "PIZZA STRAIGHT TO YOUR DOOR!""

Cryzone (Hari Seldon) (follow|body) complains, "[Common] Max BioTek Operative 2 (Sarea Elderway) (follow) exclaims, "PIZZA STRAIGHT TO YOUR DOOR!""

**Comment by Markolie** [comment]
Were they wearing an Agent ID, or their own ID card?

**Comment by Earthdivine** [comment]
Agent ID I believe

**Comment by Markolie** [comment]
And did they change the name on their ID?

**Comment by Markolie** [comment]
Ahh, I see. It works perfectly fine - voice changers have an exception for ghosts, so ghosts know who's using the voice changers. Actual crew will only see the voice changer name.
