### ISSUE TITLE
Beepsky can't open doors.

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2012]
Beepsky can no longer open doors to wanted people, making security oh so much harder.

**Comment by Markolie** [comment]
You sure? Beepsky can only open doors it has access to (Detective access) unless the AI specifically calls it.

**Comment by Robertha89** [comment]
Beepsky used to have all access, infact if you where stuck you could call beepsky to open doors for you, reminds me, security officers can no longer call beepsky, no security bot button in the pda strangely enough.

**Comment by tigercat2000** [comment]
Um, beepsky has never had all access.

**Comment by Robertha89** [comment]
Huh, in that case then.
