### ISSUE TITLE
Small issues with deltastation

### ISSUE THREAD

**Issue by Christasmurf** [ParadiseSS13/Paradise#20131]
**Issue Description**:
A series of small mapping issues with delta station.
1. Engineering and Research lack a recharger. On every other map, every core department (not including service as that is spread out) contains at least one recharger, either for staff to charge their own equipment/weapons or for security's use when defending such an area from a biohazard.
2. The kitchen lacks shutters over the counters. As both other main maps we use have shutters in the kitchen, this seems like an oversight.
3. The table located INSIDE the kitchen is reinforced, when it should not be. The counters are meant to, as this is consistent across all maps, but the internal tables are just meant to be normal metal ones.
4. Miners have access to the cargo bay, an area they do not normally have access to on the other stations. They are meant to be able to access the cargo office (and I'm assuming the break room area, all circled in red) however they can use the door circled in blue but none of the areas in the area they should be able to get to.
![image](https://user-images.githubusercontent.com/25437893/211209884-1559f4af-d1bb-4a26-b07a-2b749eb58c76.png)

**What did you expect to happen**: 
No issues with maps reeeeee bad game 0/10

**Extra information**:
Just small stuff either for QOL or consistency, nothing overly game breaking or urgent

**Comment by Venuska1117** [comment]
i believe farragus have same thing if i remember correct?
