### ISSUE TITLE
Traitors that are de-traitored by admins don't lose their uplink.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2013]
Same as on the tin, it even still gives you the passcode in your notes.

**Comment by TheDZD** [comment]
Admins *can* remove their uplink and passcode, but it seems that sometimes they forget to do so. That said, it should probably be a default thing when de-traitoring people.

**Comment by KasparoVy** [comment]
In that case it'd do us well to remember to give them a replacement PDA appropriate to their jobs or whatever

**Comment by TheDZD** [comment]
Not even necessary, it's possible to disable the traitor uplink without having to give them a new PDA button, there are "Give Uplink" and "Remove Uplink" buttons in the traitor panel for traitors.

**Comment by Markolie** [comment]
That's a fair point and intended then - admins should just remember to take away the uplink, just like how they have to remember to give one.
