### ISSUE TITLE
Bee hitboxes are to large

### ISSUE THREAD

**Issue by Carthusia** [ParadiseSS13/Paradise#20152]
**Issue Description**:

Bee hitboxes are currently the size of an entire tile, consuming it and preventing you from clicking anything on said tile but the bee, even if the bee is nowhere near it, it will always hit the bee

**What did you expect to happen**: 

The hitbox is just way to big

**What happened instead**:

I expected to pickup a tool, or hit the guy im clicking on, not the bee

**Why is this bad/What are the consequences**:

Melee combat in any scenario where bees are, the bees will always be hit first, even if two people are clicking on eachother, they will always hit the bee's first

**Steps to reproduce the problem**:
Spawn bees, stand on same tile as bee, try to hit self or pickup a tool on said tile, you will hit the bee

**When did the problem start happening**:
Not sure how long its been like this, but i just noticed it today

**Extra information**:

Bees aint that  big

**Comment by hal9000PR** [comment]
```
/mob/living/simple_animal/hostile/poison/bees/proc/make_opaque()
    // If a bee attacks someone, make it very easy to hit for a while
    last_attack = world.time
    mouse_opacity = MOUSE_OPACITY_OPAQUE

/mob/living/simple_animal/hostile/poison/bees/Life(seconds, times_fired)
    . = ..()
    if(mind || (mouse_opacity == initial(mouse_opacity)))
        return
    var/diff = world.time - last_attack
    if(diff >= opacity_time)
        mouse_opacity = initial(mouse_opacity)
 ```
 
 this is intended
