### ISSUE TITLE
Radiation suit does not protect from radiation

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2016]
Supposed to have rad protection, does not, got rads from the rad event.

**Comment by Markolie** [comment]
Did you take radiation damage, or did you get random mutations, or both?

**Comment by tigercat2000** [comment]
If I recall correctly, the rad storm event just doesn't actually check for radiation protection. I think it even kills RADIMMUNE races.

**Comment by Robertha89** [comment]
Only radiation

**Comment by Keilden** [comment]
IPCs does not take any rad damage from rad storms atleast.
