### ISSUE TITLE
Can't walk along edges in space

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2017]
As in if you are outside a window on a space tile next to a wall or anything ya can't move.

**Comment by Robertha89** [comment]
Even with activated magboots

**Comment by Markolie** [comment]
Going to need a bit more information than this, because I happen to know spacewalking works just fine. Post a screenshot or something.

On that note, the quality of bug reports has been somewhat abysmal lately - we'll have to set up some guidelines for those.

**Comment by Robertha89** [comment]
It happens at really random, and I can't re-create the bug, as i do not know what causes it, but in areas you are supposed to be able to walk in space, in fact when I had the bug before.

Imagine you are standing in space, just space nothing else, you throw an item, and you move a single tile.

**Comment by Spacemanspark** [comment]
I think it has something to do with space pods.

**Comment by KasparoVy** [comment]
Happened to me as well one round. I couldn't move in space at all unless I was on a floor or threw craploads of rods. I didn't drift, either, every time I threw something I just went one square.

**Comment by TheDZD** [comment]
Did the gravity generator happen to have been offline when this was happening? I know there have previously been issues with that and space movement before.

**Comment by Robertha89** [comment]
Nope, other people could walk without any issues.

**Comment by Markolie** [comment]
Probably fixed by https://github.com/ParadiseSS13/Paradise/pull/2171. Re-open if it hasn't been.
