### ISSUE TITLE
Changelings that use Swap Form lose the changeling hivemind.

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#2018]
I swapped forms, and noticed I didn't have hivemind language. It was also gone from Check-Known-Languages. Resulted in [this](https://cloud.githubusercontent.com/assets/8311190/9833142/e2e109b8-5984-11e5-90ad-7ee09b2dc6e2.png).

**Comment by SamCroswell** [comment]
More pertinently, the old body keeps the language.

**Comment by TheDZD** [comment]
@Fox-McCloud
