### ISSUE TITLE
admins that de-admin and re admin must re log in to use f5 asay if they die deadmined

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#20208]
**Issue Description**:

admins that de-admin and re admin must re log in to use f5 asay if they die

**What did you expect to happen**: 

to not have to have to

**What happened instead**:

I have to

**Why is this bad/What are the consequences**:

pain

**Steps to reproduce the problem**:

Play as whatever.
De-admin.
Die
Re-admin
Try to press f5

**When did the problem start happening**:

unknown

**Extra information**:

I blame s34n

**Comment by Contrabang** [comment]
Seems to be fixed
