### ISSUE TITLE
Instruments are silenced for new players

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#20211]
**Issue Description**:

New players cannot hear instruments by default as it is toggled off. They manually have to toggle it with `toggle_instruments()`.

Reporting this as a bug because it is apparently supposed to be turned on:

**client/preference/preferences.dm**
```
/datum/preferences
	(...)
	var/sound = SOUND_DEFAULT
```

**__DEFINES/preferences.dm**
```
#define SOUND_DEFAULT (SOUND_ADMINHELP|SOUND_MIDI|SOUND_AMBIENCE|SOUND_LOBBY|SOUND_HEARTBEAT|SOUND_BUZZ|SOUND_INSTRUMENTS|SOUND_MENTORHELP|SOUND_DISCO|SOUND_AI_VOICE|SOUND_PRAYERNOTIFY)
```

**What did you expect to happen**: 

When creating a new ckey, to hear instruments instantly.

**What happened instead**:

Logged into Para with a new ckey, clicked toggle instruments, _then_ they were turned on.

**Why is this bad/What are the consequences**:

Code no work plus instruments are fun to listen to. Sometimes.

**Steps to reproduce the problem**:

1. Make a new ckey
2. Join server
3. Click Hear/Silence Instruments

**When did the problem start happening**:

Probably forever

**Extra information**:

no

**Comment by Contrabang** [comment]
Not able to reproduce on a local server with default client prefs, Im able to play instruments without a problem. 

My client prefs by default was 4079, which is what SOUND_DEFAULT calculates to (aka 1|2|4|8|32|64|128|256|512|1024|2048)
![image](https://user-images.githubusercontent.com/91113370/212814081-a147f987-1236-4e08-b117-40c441ccee6e.png)
However, converting 4079 to binary, you come up with this. Meaning one bit somewhere is indeed missing
![image](https://user-images.githubusercontent.com/91113370/212814142-8d7c6069-6be5-403b-85ab-56365efd1db3.png)

Im thinking this might be something with the server database?

**Comment by Miraviel** [comment]
Definitely a server issue, joined Paradise with a fresh ckey, I could not hear instruments until I toggled it
