### ISSUE TITLE
You can put spray paint cans behind your ears.

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#20221]
**Issue Description**:

You can put spray paint cans behind your ear (At least the one from the adaptive cardboard cutout TC purchase).

**What did you expect to happen**: 

For it not to go behind my ear. Or for it to prioritize the container I have open. Or both.

**What happened instead**:

Behind my ear it went.

**Why is this bad/What are the consequences**:

I didn't expect something that big to go behind my ear, so I lost track of where it was until I guessed that is was a type of pen and figured out where to look for it. There are a few items that are like this, where they have properties they shouldn't have because they are a type of object, this is apparently one of them.

**Steps to reproduce the problem**:

1. Buy an adaptive cardboard set (Fortified Artistic Box as the examine text says).
2. Take out the spray paint.
3. Press E to put it back.
4. Notice it is now behind your ear.

**When did the problem start happening**:

Noticed today 17.01.2023

**Extra information**:

![image](https://user-images.githubusercontent.com/25958019/212902368-39eef4d2-c0cf-412a-8893-8b76cbe72246.png)

**Comment by AffectedArc07** [comment]
I'm pretty sure this specific can is a subtype of a pen

Does it work on paper?

**Comment by Christer2222** [comment]
I did not test it on paper. I did try to activate it in my hand though, and I had the options "Toggle Cap", "Change Color" and "Change drawing". The change drawing option allowed me to select runes, letters etc.
