### ISSUE TITLE
bugged floor tiles

### ISSUE THREAD

**Issue by banba2000** [ParadiseSS13/Paradise#20252]
**Problem Description**:
on the Cerberon map if you go south of the robotics labs there is an abandoned genetics lab. some floors are damaged or made of grass. In some of my shifts i expanded the robotics labs southworth and remove the floor in the abandoned genetics lab. But when i replace the floor where the 'grass' tiles used to be with just metal tiles. The metal tiles become invisible (note i have not tested this for other tile type options so it could only be for metal tiles) the only way the floor will become 'normal' is to give it a color(with the paintgun(cant say the exact name of the thing)) and then the tile will become visible

**What did you expect to happen**: 
Why do you think this is an issue?
for rebuilding the room it can be frustrating and disorientating.

**What happened instead**:
How is what happened different from what you expected?
i expected the standerd metal floor tile to show up.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
it can be game breaking when you expect a metal tile and none is showing up.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. hold crowbar in hand.
2. use crowbar on floor
3. hold metal tiles in hand
4. use metal tiles on floor
thats it

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
-

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
-

**Comment by SteelSlayer** [comment]
Could you please fill out the rest of the issue report with details about the bugged tiles?

**Comment by banba2000** [comment]
sorry, i accidentally clicked on the comment button.

**Comment by silverplatedelta** [comment]
This area was mapped out a few months ago, thus solving this issue. Thanks for the report!
