### ISSUE TITLE
Putting cash in a vendor doesnt let you remove it

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#20268]
**Issue Description**:

Put cash in a vendor, buy something, not able to get it out. (ID not having a linked account)

**What did you expect to happen**: 

To be able to remove the cash

**What happened instead**:

cash stuck, scammed

**Why is this bad/What are the consequences**:

scammed

**Steps to reproduce the problem**:

1. wear ID with no connected account (not sure if relevant)
2. put money in vendor
3. not be able to remove money

**When did the problem start happening**:

Not sure

**Extra information**:

Deconstructing the vendor also DESTROYS your money

**Comment by Henri215** [comment]
Tested and yes, it happens if you have no ID or one with no connected account
