### ISSUE TITLE
Changeling swap forms (again)

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#2027]
Apparently the issue goes beyond what was outlined in #2018. I've gotten reports it also includes leaving all of the changelings abilities in the old body. I looked over the fix in #2026 and I don't think this was fixed along with the languages.

**Comment by Robertha89** [comment]
swap form seems kinda silly for a changeling, considering it's because of their body they are changelings, not their mind. I mean, are they wizards now?

**Comment by TheDZD** [comment]
@Fox-McCloud the proc to swap minds probably doesn't have explicit proc_holder handling.
