### ISSUE TITLE
Planted grass can fail to ever mature

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#20293]
**Issue Description**:

Grass planted in botany somethimes randomly decides to never fully mature and become harvestable, or takes exceedingly long to do so.

**What did you expect to happen**: 

Plant grass, harvest grass.

**What happened instead**:

Sad botany noises.

**Why is this bad/What are the consequences**:

Grass is a nice decorative floor tile so being unable to grow it is bad.

**Steps to reproduce the problem**:

Plant grass, pray to the botany gods that it grows/doesn't grow

**When did the problem start happening**:

About a millennia ago. It was *supposedly* fixed in #14526 but I swear it is still a thing.

**Extra information**:

**Comment by Vi3trice** [comment]
I don't see anything wrong in grass specifically. However, RNG can really screw you over if you wind up with grass that is stuck at 0 yield.

**Comment by Sikroth** [comment]
I had it happen earlier today but it's hard to reliably reproduce. Issue is not that the plant has 0 yield (i farm everything with robust harvest so the stats dont change), but instead the plant itself never becomes harvestable to begin with.

You can have a grass plant with age 30+ that never was mature, which should just not happen. Grass has a base maturation of 2 and production of 6 iirc, so without any modifications to the stats it should be mature by age 8 and then every 6 cycles.

The super obvious culprit is probably maturation 2, as grass is, if i remember correctly, the only plant that has less than 3. Why that causes it to bug and never mature is unknown to me.

**Comment by Vi3trice** [comment]
An admin will have to get involved when it happens, because I can't figure out why maturation being 2 would have an effect.
At 224 trays per boots, I still cannot get the grass to not mature.

![GRASS](https://user-images.githubusercontent.com/80771500/214576091-08887132-30c2-487d-b842-ac1de86ab507.png)

**Comment by Sikroth** [comment]
Hopefulle me or someone else will ping an admin ingame if/when it happens again. I tried to duplicate it earlier but they grew fine this time.

**Comment by Sikroth** [comment]
It happened today with one of two identical seeds I planted. We looked a bit into it while the seed wasnt harvestable (it ended up becoming harvestable later on) but apparently there wasn't any var differences. At least now I can say for sure it's still an issue, just hard to reproduce.

![image](https://user-images.githubusercontent.com/7857084/214894272-efa3a473-5f80-4417-80e9-626910e4f65d.png)

**Comment by Spaghetti-bit** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/24342
