### ISSUE TITLE
Runtime /mob/new_player/can_track()

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#20315]
**Issue Description**:

Got this runtime on the server by an AI:

```[2023-01-29T15:50:09] Runtime in ai.dm,708: undefined proc or verb /mob/new_player/can track(). 
   proc name: Topic (/mob/living/silicon/ai/Topic)
   usr: AINAME(CKEY) (/mob/living/silicon/ai)
   usr.loc: The floor (143,23,2) (/turf/simulated/floor/bluegrid)
   src: AINAME(CKEY) (/mob/living/silicon/ai)
   src.loc: the floor (143,23,2) (/turf/simulated/floor/bluegrid)
   call stack:
   AINAME(CKEY) (/mob/living/silicon/ai): Topic("src=\[0x300007f]_1785;track=\[...", /list (/list))
   AINAME(CKEY) (/client): Topic(AINAME(CKEY) (/mob/living/silicon/ai), "src=\[0x300007f]_1785;track=\[...", /list (/list))
   /datum/callback/verb_callback (/datum/callback/verb_callback): Invoke()
   world: invoke callback with usr(AINAME(CKEY) (/mob/living/silicon/ai), /datum/callback/verb_callback (/datum/callback/verb_callback))
   /datum/callback/verb_callback (/datum/callback/verb_callback): InvokeAsync()
   Verb Queue Manager (/datum/controller/subsystem/verb_manager): run verb queue()
   Verb Queue Manager (/datum/controller/subsystem/verb_manager): fire(0)
   Verb Queue Manager (/datum/controller/subsystem/verb_manager): ignite(0)
   Master (/datum/controller/master): RunQueue()
   Master (/datum/controller/master): Loop()
   Master (/datum/controller/master): StartProcessing(0)
```

**What did you expect to happen**: 

The `can_track()` verb is defined on `/mob/living/`, new_player should not call this

**What happened instead**:

The AI somehow ended up trying to track a new player?

**Why is this bad/What are the consequences**:

This is definitely unintended.

**Steps to reproduce the problem**:

Unsure, the AI in question said they tried to track random people, it took a lot of time, and then it succeeded. It is possible that they were trying to track someone who was still spawning in?

**When did the problem start happening**:

Round 34420

**Extra information**:

...

**Comment by Miraviel** [comment]
farie mentioned they might have clicked an old ref link in the chat to follow them, like a deleted mob's

**Comment by GDNgit** [comment]
> farie mentioned they might have clicked an old ref link in the chat to follow them, like a deleted mob's

Yeah, that's the cause (found out while debugging mind GC stuff)
Arrivals annoucer strikes again, it gets deleted right after it gets created which is why if you try to observe an annoucer it will often send you to a random mob if nowhere at all, same logic applies to the AI
