### ISSUE TITLE
Wearing a facehugger makes you blind

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2031]
Now you can't use the best internals in the game anymore, also, it does this for the toy too, which seems logical, but in reality is stupid.

**Comment by Spacemanspark** [comment]
The toy should blind, but only for one or two seconds, in my opinion.

**Comment by Fox-McCloud** [comment]
This is intentional.

**Comment by tigercat2000** [comment]
I.. don't see how this is intentional at all?

**Comment by tigercat2000** [comment]
Wouldn't this mean that Lamarr would also blind people? And the toy doing it doesn't seem like it should either. Or, infact, even the normal facehuggers. This doesn't make any sense.

**Comment by Spacemanspark** [comment]
It covers your entire face.

**Comment by Fox-McCloud** [comment]
That and it's there to mimic the effect real huggers have of knocking you out and making you black out.

It specifically states, in the code that the toys make you blind to make it "more authentic".

**Comment by taukausanake** [comment]
Can we add in the feature to move it out of the way so you can see, but not to the point that it's removed?
