### ISSUE TITLE
EFTPOS won't work in pocket.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#20342]
**Issue Description**:
EFTPOS when pocketed will not properly process a transaction when placed in your pocket despite it telling you that you swipe the card.

**What did you expect to happen**: 
I expected the transaction to process properly an charge the account of the card swiped.

**What happened instead**:
I did not get any money 😔 

**Why is this bad/What are the consequences**:
You rip yourself off by right of buggy technology.

**Steps to reproduce the problem**:
1. Pocket EFTPOS.
2. Swipe card.
3. Observe as no money happens.

**When did the problem start happening**:
Not sure.

**Extra information**:
No money bad, bartender poor and homeless.

**Comment by FridgeBurns** [comment]
I can't replicate this. I think it was fixed by #20095 or #20456.

**Comment by Mitchs98** [comment]
May have been then and this just didn't get mentioned when the PRs went live. I'll close it, it can be re-opened if the issue presents itself again.
