### ISSUE TITLE
Package sending on Farragus is broken.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#20352]
**Issue Description**:
A few items were sent down Farragus disposals VIA the labeled package system. None made it to their destinations and instead were chucked out into space VIA main disposals. Two different destinations; The bar and Chemistry.

**What did you expect to happen**: 
I expected things to be sent to their destinations.

**What happened instead**:
They were not.

**Why is this bad/What are the consequences**:
Things do not get sent to where they need to go, and therefore get lost.

**Steps to reproduce the problem**:
1. Print Label.
2. Put stuff in label.
3. Chuck into disposals.
4. It gets spaced.

**When did the problem start happening**:
Since the map existed, probably?

**Extra information**:

**Comment by S34NW** [comment]
Needs further testing, disposals for these exists
