### ISSUE TITLE
NSS Farragus quantum pad apc bug

### ISSUE THREAD

**Issue by ReedOni** [ParadiseSS13/Paradise#20350]
**Issue Description**:

I can't build an APC at the quantum pads room near brig after the previous one was destroyed during a spider emergency. 

**What did you expect to happen**: 

To be able to build the APC.

**What happened instead**:

I get a message saying that this area already has an APC.

**Why is this bad/What are the consequences**:

Power can't be restored to the quantum pads.

**Steps to reproduce the problem**:

Try placing an APC at one of the quantum pads room after deconstructing an old one.

**When did the problem start happening**:

I only noticed it today for the first time so I don't know exactly.

**Extra information**:

I ahelped the issue and Norwest asked me to make a bug report, sadly the picture I took doesn't show the "this area already has an apc" message, I hoped it would.

![Paradise Station NSS Farragus 2023-02-03 011200](https://user-images.githubusercontent.com/124325803/216497237-19192c7a-f5b8-4e40-a719-98370d660874.png)

**Comment by S34NW** [comment]
Security telepad is incorrectly aread as science telepad. Fix incoming
