### ISSUE TITLE
Wingdings are cured by Mutadone

### ISSUE THREAD

**Issue by SeizingSponge** [ParadiseSS13/Paradise#20372]
**Issue Description**:

Roundstart wingdings can be cured by Mutadone and apparently roundstart disabilities are not supposed to be affected by mutadone.

**What did you expect to happen**: 

I didn't know it was an issue until I explained it on discord and people told me to report it :)

**What happened instead**:

I could speak common as a _cool_ grey! Very unsettling!

**Why is this bad/What are the consequences**:

Wingding is cool disability! If this is a bug, it would certainly be nice not to be accidentally 'cured' of it.

**Steps to reproduce the problem**:

Be grey with wingding
Eat mutadone
Lie

**When did the problem start happening**:

Noticed it a few months back I think. Thought it was a feature.

**Extra information**:

I love you

**Comment by SeizingSponge** [comment]
also its been a while since the situation has arose but I believe mutadone takes away grey's telepathy too

**Comment by Gatchapod** [comment]
I did some testing.
Mutadone by default does not affect grey wingdings or telepathy. Likely, it does not affect any roundstart disabilities or genetic powers.
However, once you're cloned, mutadone can cure your roundstart disabilities.

I assume this is a dna2 moment.

**Comment by Komrad822** [comment]
>However, once you're cloned, mutadone can cure your roundstart disabilities.

This includes clean SE too.

Can second this, have used it to cure said issues on cloned greys to bypass the need to extract their implants (you gain the ability to communicate again but lose the niche of your species).
