### ISSUE TITLE
Some patches may be significantly more effective than intended

### ISSUE THREAD

**Issue by Coolrune206** [ParadiseSS13/Paradise#20381]
**Issue Description**:

https://github.com/ParadiseSS13/Paradise/pull/13062 changed patches with the intent of having them apply their reagents over time slowly as a touch effect. However, because the most common chems used in patches have a metabolism effect, they are **significantly** more effective this way than if they were directly applied.

**What did you expect to happen**: 

Here's Bill, who just ran into a wall of lasers. Bill is injured, and needs help.
![image](https://user-images.githubusercontent.com/71326864/217318247-035cf3c8-b6e6-4d4e-86cc-9ad334181c0e.png)
Directly applying 30u of Silver Sulfa will mildly help Bill, by removing 30 burn damage as you might expect because Silver Sulfa heals 1 to 1 with touch application.
![image](https://user-images.githubusercontent.com/71326864/217318601-9bed26f8-7eab-4ef9-905e-21f65cf9b174.png)
Anyways, Bill's still going to die, but that's intended. Let's move on to Greg.

**What happened instead**:

Greg just ran through a plasmafire, and needs help.
![image](https://user-images.githubusercontent.com/71326864/217319082-52aa6373-b441-4ee2-8761-66228ce91e6b.png)
We slap a standard-fare Silver Sulfa patch on Greg, which contains 30u of Silver Sulfadiazine (which above healed 30 burn damage). Let's step away from Greg for a minute and check on him once the patch is done.
![image](https://user-images.githubusercontent.com/71326864/217319884-17ed3556-394f-419e-8a54-1008bac3441c.png)
Greg's still going to die, oh well, but he's managed to heal **over 200 burn damage from this 30u patch.**

**Why is this bad/What are the consequences**:

Patches, as far as I can tell from the intent of the PR, were meant to stay at around the same effectiveness while applying over time. They were directly noted as being applied via a touch reaction. However, due to the metabolism effect of Sulfa and Styptic, they heal significantly more than they would just via the touch reaction. You can look at a similar chemical, synthflesh, to see what I believe the PR intended. 10u of Synthflesh heals 15 damage via direct application, and if you slap on a synthflesh patch it heals 15.225 damage (due to rounding) over a period of time. 
Right now, those little patches sitting around the station *can* heal over 200u of damage each (even if it's over a period), which is a lot more than they probably should heal. The overwhelming amount of healing these things give is probably part of the reason Mining has so little trouble against megafauna, because they have a large heal effect throughout the fight not counting cores. 

**Steps to reproduce the problem**:

Just apply any sulfa/styp patches.

**When did the problem start happening**:

Since the aforementioned PR.

**Extra information**:

Now, this has been the state of affairs for around 3 years, and I think most of us have just assumed that patches should be healing this much - but because I genuinely cannot tell if 30u patches were supposed to go from healing 30 damage to healing 200 damage over time, I figured it would be worth at least making an issue report so I can discern if this was an intended massive buff or not.

**Comment by CinnamonSnowball** [comment]
It's probably worth noting that the >200 burn damage healed on Greg happened over the course of nearly 3 entire minutes, during which Greg would unfortunately likely have died anyway

Styptic Powder/Silver Sulfadiazine patches, while indeed amazing at keeping up pretty good healing for a longer while, are not at all meant for situations where you suffer large bursts of damage - even though they theoretically *can* heal insane amounts of damage, if you're already deeply injured, you're likely to get mauled by whatever it is that hurt you due to being in pain slowdown before the patch can save your life

**Comment by SpringSkipper** [comment]
> We could slightly tune down the chemicals in the base patches, to provide closer to say, 150 or 100 heal over time. I would rather not slow the rate of healing of patches. In any case, more balance than a bug.

For reference, a 10u patch like you find in a white medkit heals 68.15 damage over a few seconds less than a full minute. 30u is a very high dosage for a patch.
