### ISSUE TITLE
Having 0 magic loses you a game of "Space Villian 2000"

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#20407]
**Issue Description**:

If you use all your magic, you lose the game.

**What did you expect to happen**: 

To not lose after getting 0 magic, and not be able to use the heal ability.

**What happened instead**:

You lose the game.

**Why is this bad/What are the consequences**:

Its confusing.

**Steps to reproduce the problem**:

1. Play "Space Villian 2000" the arcade game.
2. Spam Heal until you game over.

**When did the problem start happening**:

Noticed today 12.02.2023

**Extra information**:

Also don't know if the name is a pun on Ian or a spelling mistake, but I am guessing the later.
![image](https://user-images.githubusercontent.com/25958019/218290611-ceb68a27-36d8-40c5-8394-5ee45b497b46.png)

**Comment by GDNgit** [comment]
```	
if((player_mp <= 0) || (player_hp <= 0))
	gameover = 1
	temp = "You have been crushed! GAME OVER"
```
working as intended but... bwuh

**Comment by Christer2222** [comment]
Intended nonsense, good lol Well, I posted the issue, I feel it should tell you about this... if it is intended and good for the game; tag this as whatever fits.

**Comment by SpringSkipper** [comment]
it always struck me as weird too
honestly though I don't think it matters much either way. This 'game' involves just alternatingly spam-clicking the buttons until you win, with no real skill elements.

**Comment by Christer2222** [comment]
I wont argue that this is a low impact issue (yet these stand out when it comes to polish), but not the point as documentation is important. I certainly wont lose any sleep over whether or not this is fixed, labeled as intentional or something else. But it could serve as a way to introduce new contributors (such as myself) to the project.

**Comment by Henri215** [comment]
I confirmed that "Villian" is a spelling mistake.
About it going game over when it hits zero, i think it adds, not much, a bit of caution when using your magic points since you dont know how many points will be used the next time its used, which could lead you to failure.

**Comment by warriorstar-orion** [comment]
The code seems pretty emphatic about the behavior here so I'm going to mark it as intended. If you'd like to make a change to it that may be a good small PR to work on.
