### ISSUE TITLE
Claw game has the incorrect text when inserting credits.

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#20408]
**Issue Description**:

When you insert credits into the claw game, it says you insert the amount of credits in your stack, rather than 5.

**What did you expect to happen**: 

For it to either say I insert 5 credits, or for it to tell me how many credits my current stack holds, or both!

**What happened instead**:

"You insert 100 credits"
"You insert 95 credits"

**Why is this bad/What are the consequences**:

Incorrect text is confusing.

**Steps to reproduce the problem**:

1. Get a stack of credits (I got 100).
2. Insert them into the claw game.

**When did the problem start happening**:

Noticed today 12.02.2023.

**Extra information**:

![image](https://user-images.githubusercontent.com/25958019/218291087-46ad6465-883b-4f0c-867b-efcacc372bdb.png)

**Comment by Henri215** [comment]
![image](https://user-images.githubusercontent.com/77684085/218311146-e619f8b5-6d35-4903-b85b-f76a10fd269b.png)
Its using the base economy_machinery insert_cash proc visible message, which makes sense for vendors but not arcade machines.
