### ISSUE TITLE
Dyed Durathread Clothing Missing Sprites

### ISSUE THREAD

**Issue by SchrodingersWolf** [ParadiseSS13/Paradise#20411]
**Problem Description**:
![Screenshot (423)](https://user-images.githubusercontent.com/108938550/218307071-174bea60-c3e9-445b-98e5-48b2252c1a5a.png)

![Screenshot (425)](https://user-images.githubusercontent.com/108938550/218307087-131f003b-f2fc-4e78-92be-c10e8a4f1c50.png)

Missing sprite for dyed Durathread clothing

**What did you expect to happen**: 
My Durathread clothes to be dyed and look cool

**What happened instead**:
Got invisible Honk-brand clothing instead

**Why is this bad/What are the consequences:**
Missing sprites are bad (And I don't want to be accused of Public Indecency when I'm wearing clothes)

**Steps to reproduce the problem**:
1. Make Durathread jumpsuit from woven Durathread
2. Put jumpsuit in washing machine
3. Insert crayon in washing machine (I used a black one)
4. Wait for it to finish washing
5. Clothes came out missing sprites

**When did the problem start happening**:
Not sure when it is a thing, but discovered on 2/12/2022 (Round ID 34590)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
N/A

**Comment by Contrabang** [comment]
Able to reproduce with other colors. Likely caused by #19092. Bandanas seem to work fine. The beret and beanie dont get colored.
