### ISSUE TITLE
Bug with changeling swapping into lesser form.

### ISSUE THREAD

**Issue by Sotrennel** [ParadiseSS13/Paradise#2051]
When a changeling transforms into his lesser form, there seems to be a transition bug.
The changeling dissapears, and an invisible monkey appears with only his hair visible.
After 3-4 seconds, this monkey gets visible and can use vents etc.

I think this is a pretty frustrating bug, since changelings use the lesser form for a quick escape.
If the transition takes more than 5 seconds, it isn't really an escape, since everybody has noticed it before you can use actions.

**Comment by Markolie** [comment]
Thanks for the report. Will investigate.
