### ISSUE TITLE
White Gloves don't show on Greys after Dignitary Drip roll out.

### ISSUE THREAD

**Issue by ReedOni** [ParadiseSS13/Paradise#20540]
**Issue Description**:

I rolled NT Rep as grey right after the new sprites were implemented, I wore the white gloves but they are not showing on my sprite.

**What did you expect to happen**: 

I can't see the gloves which should be visible.

**What happened instead**:

The gloves didn't show on my hands.

**Why is this bad/What are the consequences**:

New drip not working is not good.

**Steps to reproduce the problem**:

Be Grey and wear white gloves.

**When did the problem start happening**:

As soon as I was able to test the new NT Rep sprites 15 minutes ago.

**Extra information**:

I've tested on a skrell during the shift I'm in and the gloves appear on their sprite, this might be an issue with Greycism. I will test this on vox and drask too. I would link the dignitary drip PR but I don't know where to find it once it's merged.

![Paradise Station NSS Cyberiad 2023-03-04 133845](https://user-images.githubusercontent.com/124325803/222902528-f0a10041-5f6f-4114-a86b-3532ea2f7198.png)
![Paradise Station NSS Cyberiad 2023-03-04 133843](https://user-images.githubusercontent.com/124325803/222902535-00c888d4-7a8b-4597-b2f3-21c324f22c7e.png)

**Comment by Contrabang** [comment]
![image](https://user-images.githubusercontent.com/91113370/222903474-9fa47fe1-ab6c-4ee3-a783-a72313b30d0d.png)
![image](https://user-images.githubusercontent.com/91113370/222903482-95890dda-3f74-4445-9356-cb5fa6a1d442.png)
Yep, the dmi is missing grey gloves. Vox, drasks, and kidans have their respective gloves in their dmi though.
