### ISSUE TITLE
R&D Machinery not Synced

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2056]
Alright, pretty sure this is a bug, but in case it's not, thus the feature request tag.

So on TG, the R&D machinery starts off automatically linked to their respective RD consoles--this most certainly doesn't happen here and the console has to be manually synced every shift.

I believe all machinery is supposed to sync with nearby consoles---not sure if this is caused by improper ID's set on the RD console or something else.

**Comment by taukausanake** [comment]
I personally don't want the machines to be auto-linked. Makes sure that R&D is doing their job for starters
