### ISSUE TITLE
IPC Surgery needs a Fixing

### ISSUE THREAD

**Issue by YoureNotTheSharpest** [ParadiseSS13/Paradise#20578]
**Issue Description**: IPCs are special snowflakes and this is well known. They are so special that they have their own surgeries. There are issues however that I had not reported for like several months with surgeries such as the biochip removal and cavity implants.

**What did you expect to happen**: The surgeries to utilize tools within a toolbelt.

**What happened instead**: The surgeries Cavity Implant/Removal and Biochip Removal require surgical tools Cauterizer and Retractors respectively.

**Why is this bad/What are the consequences**: Robotics doesn't need to be confused when trying to do a biochip search on antag IPCs and not know how to close an IPC.

**Steps to reproduce the problem**: Get IPC on surgical bed, do any of the surgeries listed, get to the final steps, attempt to use a crowbar to close the IPC, be confused, look at wiki, use a cautery tool/retractors to close cavitys/the hatch of IPCs.

**When did the problem start happening**: Surgery Refractor I believe caused this back in november.

**Extra information**: Can we get a use for wirecutters/wrench in IPC surgery?

**Comment by YoureNotTheSharpest** [comment]
OH also before I forget,

IPCs require a surgery to fix their disfigurement as identity reconfiguration does not fix disfigurement.

**Comment by lewcc** [comment]
Just for context, fixing disfigurement happens within Cybernetic Repair.
