### ISSUE TITLE
IPC's head explodes into gibs

### ISSUE THREAD

**Issue by YoureNotTheSharpest** [ParadiseSS13/Paradise#20571]
**Issue Description**: When assaulting a vending machine with an item it will fall over and result in a mess of gibs. This also applies to IPCs creating a bloody mess from something without blood.

**What did you expect to happen**: Originally I didnt expect to just fucking die to a vending machine, but more so I would have expected it to just lego me

**What happened instead**:

**Why is this bad/What are the consequences**: IPCs are not organics and shouldnt make gibs

**Steps to reproduce the problem**: be IPC, Attack vending machine with tool, ???, Have your head explode and gibs fly everywhere

**When did the problem start happening**: Vending machine retaliation PR.

**Extra information**:
![image](https://user-images.githubusercontent.com/107788621/223003024-beb9046e-6d72-4bfb-8519-bebc9f477763.png)

**Comment by YoureNotTheSharpest** [comment]
I realized I have left the "What happened instead:" field blank but uh.... that is redundant somewhat...

**Comment by Miraviel** [comment]
This is a good first issue, the vendor needs to check whether its user is an IPC, and if so, it should use the robot gibspawner.
