### ISSUE TITLE
PDA sprite updating issue

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#20590]
**Issue Description**:

If you 'hotswap' a id in a pda, then remove the id from the PDA, it will still look like the pda has a id in it.

**What did you expect to happen**: 

I expected the sprite to correctly update, to have a empty ID slot. 

**What happened instead**:

The PDA still looked like it had a ID in it, causing minor confusions while looting people for access.

**Why is this bad/What are the consequences**:

As a relatively minor sprite issue, aside from being confusing for a second, its not 'bad' aside from bugs being bad. 

**Steps to reproduce the problem**:

1. Take a PDA with no id in it
2. Take a ID card, and insert it into the PDA
3. Take a second ID card, and hot swap the IDs around (click on the full PDA with the second id card)
4. Remove the freshly swapped ID, and watch as the sprite for the PDA does not change/update to reflect the state of the PDA

**When did the problem start happening**:

I think i first noticed it happening when the new ID sprites were ported? However it is very unlikely a sprite change buggered it.

**Comment by Contrabang** [comment]
I think this has been around forever, but it is definitely more noticeable with the new ID sprites in PDAs
