### ISSUE TITLE
CI `check_file_names.py` doesnt work properly

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#20627]
**Issue Description**:
The `check_file_names.py` is meant to prevent files with duplicate names in the codebase. However:
![image](https://user-images.githubusercontent.com/25063394/224534249-1644ea03-869c-4043-856d-8ad992fa323c.png)

This aint it chief

**What did you expect to happen**: 
The check to work

**What happened instead**:
It didnt

**Why is this bad/What are the consequences**:
Faulty checks bad

**Steps to reproduce the problem**:
Run the script

**When did the problem start happening**:
Since I added it

**Extra information**:
What is it with this one file that causes issues

**Comment by warriorstar-orion** [comment]
so it doesn't get lost in discord noise:
```diff
 def main():
     alert_sent = False
     for filename, fullpaths in file_name_map.items():
-        if len(fullpaths) > 2:
+        if len(fullpaths) > 1:
             if not alert_sent:
                 print("The following files have the same name in multiple places in the codebase. Please fix!")
                 alert_sent = True
```


fix will require a bunch of false negatives to be fixed: https://gist.github.com/warriorstar-orion/2e39bae505c382777f7d4ce1bb0450a7
