### ISSUE TITLE
The medical wrench duplicates itself when used to commit suicide

### ISSUE THREAD

**Issue by JimKil3** [ParadiseSS13/Paradise#20646]
**Issue Description**:

Committing suicide with the medical wrench duplicates it.

**What did you expect to happen**: 

I expected it to not be duplicated

**What happened instead**:

It was duplicated

**Why is this bad/What are the consequences**:

Duplication is bad, even if you have to dust yourself to do it

**Steps to reproduce the problem**:

1. Hold a medical wrench
2. Suicide verb
3. ???
4. Profit(?)

**When did the problem start happening**:

Probably for as long as it's been in the game, but I'm not sure how this would have gone unreported, so it may have been a recent change.

**Additional Information**:
![image](https://user-images.githubusercontent.com/47290811/225303156-89dde44b-35ed-4588-a3ff-dd412b6a5159.png)
Only one of the wrenches has the "For some reason, it reminds you of [name]." text.

**Comment by Contrabang** [comment]
Actually it seems like the medical wrench turns the user into a medical wrench also, so this is an intended duplication I think?

**Comment by Contrabang** [comment]
This will be "fixed" by #20607 because it clarifies that the user turns into the wrench.

**Comment by Henri215** [comment]
"fixed" by https://github.com/ParadiseSS13/Paradise/pull/20607.
