### ISSUE TITLE
Abductor Console not able to disguise the agent

### ISSUE THREAD

**Issue by SpecialX989** [ParadiseSS13/Paradise#20651]
**Issue Description**:

The abductor console was not able to disguise my agent thus forcing us to complete our objective strong-arm style.

**What did you expect to happen**: 

I expected to push a fancy button and my agent to not look like an agent

**What happened instead**:

I pushed a fancy button and my agent still looked like an agent

**Why is this bad/What are the consequences**:

My agent cannot stealthily abduct people and thus forcing us to be more robust than usual.

**Steps to reproduce the problem**:

Spawn in as an abductor
Push a fancy button
Still be an abductor

**When did the problem start happening**:

Last I checked it was always working, I only noticed it now as it was my first time being an abductor.

**Extra information**:

Always salt your pasta while boiling it.

**Comment by Contrabang** [comment]
The scientist needs to scan people from the console, then select a disguise, before the abductor agent can activate it. I'm not sure what you mean by the fancy button and I cannot reproduce this. 
Although, clarification in game on how this process works might be helpful for new abductors.

**Comment by Contrabang** [comment]
It seems like it was an problem with the agent not activating their disguise once selected. I think theres a design issue with these disguises being complicated but theres no easy solution to that design issue
