### ISSUE TITLE
Desiccated Slimes have BONES!

### ISSUE THREAD

**Issue by matttheficus** [ParadiseSS13/Paradise#20652]
**Issue Description**:

When slimes desiccate, they leave behind **BONES**. Slime people dont **HAVE** bones!
`X is mostly desiccated now, with only bones remaining of what used to be a person.`

**What did you expect to happen**: 

Slime people do not have bones. They should not rot down to bones!

**What happened instead**:

Slime people have **BONES**!

**Why is this bad/What are the consequences**:

Muh continuity.

**Steps to reproduce the problem**:

1. Kill a slime person.
2. Let the rot consume them.
3. **BONES**!

**When did the problem start happening**:

Likely since forever.

**Comment by Contrabang** [comment]
Technically slimes do have bones in the lore, but they're unbreakable
