### ISSUE TITLE
Missing in-hands sprites Megathread

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2066]
Report any and all missing in-hands here

Found thus far:

- ~~welder~~
- ~~wrench~~
- ~~all toolboxes~~
- ~~backpacks~~
- ~~dufflebags~~
- ~~boxes~~
- ~~cigs~~

**Comment by Spacemanspark** [comment]
Syringe gun.
Right
Right hand shows a frame of a burning flag, left hand is invisible.

**Comment by Fox-McCloud** [comment]
- There are two instances of "flashbang", causing grenades to improperly appear
- Zippo Lighter
- resonator
- pepperspray
- golden cup (may require code changes)
- Mining jetpack
- tile (for floors)
- flares

**Comment by Markolie** [comment]
Also added syringe and suppressor in-hands.

**Comment by Alex6511** [comment]
Wand of Ressurrection is missing.

**Comment by SamCroswell** [comment]
Syringe guns left hand appears as a flag.

**Comment by veganzombeh** [comment]
Not sure if I should make a new issue, or use this one.

Video camera.
