### ISSUE TITLE
Summon Cult Ghosts rune can summon cultists that are in Spirit Realm

### ISSUE THREAD

**Issue by GoldenMustachio** [ParadiseSS13/Paradise#20671]
**Issue Description**:

While in the Spirit Realm as a cultist and your ghost sprite is above a Rune that is attempting to summon cult ghosts it can force the player out of their previous body and into a cult ghost, leaving their previous character an unplayable cultist as it still thinks the player just hasn't returned to the body yet, however there is no way to return to the body.

**What did you expect to happen**: 

I expected to not turn into a cult ghost and to be able to return to my physical form.

**What happened instead**:

Instead of being able to return to my previous character I received the message "You have no body."

**Why is this bad/What are the consequences**:

This issue can strip cultists of gameplay and completely take them out of the round, if this were to happen round start cult this could compromise a cult pretty quickly.

**Steps to reproduce the problem**:

1. Enter Sprit Realm as cultist
2. Hover over a Summon Cult Ghost rune
3. Activate Summon Cult Ghost rune
4. You are now (hopefully) a cult ghost.
5. Attempt to return to your previous body.

**When did the problem start happening**:

This occurred on round 35033 on 3/19/23 around 8:30 PM EST

**Extra information**:

N/A

**Comment by Contrabang** [comment]
Fixed by #22540
