### ISSUE TITLE
In-Hand Layer seems to be wrong

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2067]
The layer that in-hands appear on is different than it once was and appears to be incorrect.

For example, holding a clipboard, it will appear BEHIND your clothing/tail, when it appeared in front of them, before.

How it currently appears:

![wrong1](https://i.gyazo.com/0a402a15084a90e31659bf2453b7da83.png)
![wrong2](https://i.gyazo.com/3663cf2368cec619136c562b881ebb16.png)

How it is *meant* to appear:

![right1](https://i.gyazo.com/0397012161bd0e3796ffcc68ff01134c.png)
![right2](https://i.gyazo.com/43975f2f431d76ad3bc971be09888c1b.png)

Tails, suits, clothes, belts, etc aren't meant to block in-hands.

**Comment by Spacemanspark** [comment]
Also, Syringe guns appear to be a frame of a burning flag in the right hand (left hand shows no sprite at all.)

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Report that in the other issue report please; that one is for missing/messed up sprites; this is a separate issue, completely.
