### ISSUE TITLE
N20 is colored blue on some tiles instead of its usual white.

### ISSUE THREAD

**Issue by Accinator50** [ParadiseSS13/Paradise#20688]
**Issue Description**:

During a xenomorph round N20 was released into maintenance. Instead of its usual color the N20 was colored blue on some tiles. After mhelping, I was told that the problem probably is that the tiles were painted blue previously which is why the N20 adapted the color.

**What did you expect to happen**: 
N20 is not supposed to be blue. It should be white.

**What happened instead**:
It was blue on some tiles.
Blue tiles:
![grafik](https://user-images.githubusercontent.com/44909173/226699464-cf1dae0a-3ff1-43a7-8d6a-40ce82b626dd.png)
White tiles next to blue tiles:
![grafik](https://user-images.githubusercontent.com/44909173/226699343-759b34e2-1b47-4850-8fbb-80ee55ce17a1.png)

**Why is this bad/What are the consequences**:
It's not a major problem but it can ruin immersion.

**Steps to reproduce the problem**:
I'm not sure if there is a way to consistently reproduce this bug, as I was only a bystander when it happened. But my guess would be:
- Paint the tiles blue (probably via the xenobio floor tile feature).
- Release N20 gas.

**When did the problem start happening**:
Unknown. First encounted during round 35017.

**Comment by ppi13** [comment]
I believe this was caused by maintenance being painted blue.  
The way it works is that there are two vars, one for plasma, and one for n2o, if they are enabled, then the gas will be visible, since the visible gas is part of the tile, it also has the same color as the tile.
So not a bug, just an unintended interaction.
