### ISSUE TITLE
Aliens can show up as infected on health scanner huds.

### ISSUE THREAD

**Issue by Accinator50** [ParadiseSS13/Paradise#20689]
**Issue Description**:
Aliens can show up as infected on health scanner huds. It happened to both larva and grown xenos. 

Larva:
![grafik](https://user-images.githubusercontent.com/44909173/226701506-b10e9da7-3322-40b6-b816-113ce4ccaedd.png)
Hunter:
![grafik](https://user-images.githubusercontent.com/44909173/226702028-81c48aec-8649-477e-a317-00a51a99e8ed.png)

Xenos can't be infected with viruses so they shouldn't show up as infected.

**What did you expect to happen**: 
They shouldn't show up as infected

**What happened instead**:
They showed up as infected.

**Why is this bad/What are the consequences**:
It's a bug. Bugs are bad.

**Steps to reproduce the problem**:
I suspect that as a xeno you have to be infected with a virus for this bug to occur.

**When did the problem start happening**:
Unknown.

**Comment by matttheficus** [comment]
Xenos can be infected with viruses as theyre carbon mobs. This is intended.
