### ISSUE TITLE
Some machines don't lose APC connection when unwrenched and wrenched down somewhere else

### ISSUE THREAD

**Issue by CinnamonSnowball** [ParadiseSS13/Paradise#20691]
**Issue Description**:
Some machines (vending machines, kitchen appliances, Cyberiad bar's chess game were tested) stay connected to whichever area's APC they were constructed in even when moved somewhere else.

**What did you expect to happen**: 
Machinery should probably not maintain its power connection when unwrenched, but more importantly it should connect to the new area's APC when moved and wrenched down somewhere else.

**What happened instead**:
Some machines never lose their connection to their original APC unless de-and-reconstructed.

**Why is this bad/What are the consequences**:
Vendors and such from areas that lost power cannot be accessed after simply moving them into powered rooms, since the connection to the original area persists.
Machines could be constructed in a specific area on the station, then moved somewhere else to stealthily drain a given area's power.

**Steps to reproduce the problem**:
- Grab a wrench
- Unanchor some random vending machine, move it to a different area, wrench it down there
- Return to the vendor's original area, unlock the APC and turn equipment off
- Note that the vendor has turned off despite no longer being in the same area

**When did the problem start happening**:
Commit `7c3cd86f14` aka #19991 (note: due to a different bug introduced in that PR, vending machines have to be interacted with to make sure they're actually [de]powered and their UI is [in]accessible, as their icons do not update properly; this has since been fixed in #20668)

**Extra information**:
Notably does not happen with consoles (e.g. bridge ones), though this might be due to the extra screwdriver step counting as de-and-reconstructing the console, forcing a reconnection.

**Comment by Sirryan2002** [comment]
Fixed in #23188
