### ISSUE TITLE
Slime people can get broken bones.

### ISSUE THREAD

**Issue by Accinator50** [ParadiseSS13/Paradise#20700]
**Issue Description**:
Slime people can get broken bones after returning from the contractor's prison.

**What did you expect to happen**: 
Slimes don't have bones.

**What happened instead**:
A species that has no bones got broken bones.

**Why is this bad/What are the consequences**:
Bugs.

**Steps to reproduce the problem**:
- Be slime
- Be contracted
- Get (un)lucky and get broken bones after being send back

**When did the problem start happening**:
Likely after PR #19116 was merged.

**Comment by matttheficus** [comment]
Havent heard of this happening again, so this could be a one-off? Going to close for now.
