### ISSUE TITLE
Farragus Booze Vendor spawns in a wall

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [ParadiseSS13/Paradise#20716]
**Issue Description**: The Booze-O-Mat vending machine, (the one you get glasses out of), spawns in a bloody wall.

**What did you expect to happen**: I certainly did not expect the vending machine to have noclip enabled.

**What happened instead**: Noclip was indeed enabled.

**Why is this bad/What are the consequences**: Things spawning in walls seems like an oversight that needs correcting.

**Steps to reproduce the problem**: Look at Farragus, look past Farragus being kinda subpar in general, and spot this little particular mistake.

**When did the problem start happening**: I have genuinely no idea, I've never lingered in the service asteroid, but I must imagine it happened during the remap.

**Extra information**: See attached image.
![Jank Bar](https://user-images.githubusercontent.com/71111573/227748260-164f6156-00b9-4b7a-b3e4-b887e356040f.png)

**Comment by S34NW** [comment]
This is actually intended so it's accessible from both sides
