### ISSUE TITLE
Invisible dead angry corgi at space syndicate cake factory

### ISSUE THREAD

**Issue by Kristian-T** [ParadiseSS13/Paradise#20746]
**Issue Description**:
When you kill the angry corgi at the syndicate cake factory in space it's corpse becomes invisible (It's a reskinned alien). 

**What did you expect to happen**: 
The angry corgi being visible when dead.

**What happened instead**:
The angry corgi became invisible.

**Why is this bad/What are the consequences**:
It becomes difficult to interact with the corpse when it is invisible and breaks immersion.
Also if you revive the corgi with a Lazarus injector, the corgi stays invisible, which could become a problem if the person reviving it is an antag, and uses a sentience potion on it.

**Steps to reproduce the problem**:
Step 1.
Kill angry corgi.

Step 2.
Revive angry corgi with Lazarus injector.

**When did the problem start happening**:
Tested it the day of this report 30/03/2023

**Extra information**:
Honestly it is kind of a hilarious bug, but please fix it anyways.

**Comment by Henri215** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/21611
