### ISSUE TITLE
Toy Disintegrate Runtimes

### ISSUE THREAD

**Issue by Banderblitz** [ParadiseSS13/Paradise#20740]
**Issue Description**:
Toy Disintegrate from the arcade appears to runtime and ping admins when used from the spell menu to equip and put away.

**What did you expect to happen**: 
I expected my funny toy hand to simply mess with security when I used it around them, and not mess with admin logs and the server.

**What happened instead**:
An admin notified me that my spell usage was causing runtimes every time it was being used.

**Why is this bad/What are the consequences**:
Runtimes notable by admins that can be commonly spammed bad. Otherwise, not likely significant.

**Steps to reproduce the problem**:
Buy toy disintegrate from the arcade, use from spell menu on the side to equip and unequip repeatedly. Preferably in front of an officer to give them shakes.

**When did the problem start happening**:
As of 3/29/2023 it was noted.

**Comment by silverplatedelta** [comment]
Runtimes from this item are not being spammed within the past year, with 11 being thrown since January. None of these 11 occur from the usage of the "spell" itself. Thanks for the report!
