### ISSUE TITLE
Captain's Jacket Blocks Uniform and ID slot

### ISSUE THREAD

**Issue by pismorizzo** [ParadiseSS13/Paradise#20759]
**Issue Description**:
The Captains Jacket blocks the uniform, belt, sensors and ID slots preventing someone from removing their ID without taking the jacket off first. None of the captains other exosuit slot items such as the captains formal coat do this.

**What did you expect to happen**: 
To be able to remove the ID just like all the other armor slot items

**What happened instead**:

The ID and uniform slots are unreachable unlike every other armor slot item besides spacesuits. 

**Why is this bad/What are the consequences**:

It gives one of the items a direct and I can only assume unintended benefit that wouldn't be clear to anyone at a glance and could lead to horribly confusing situations or death for a would be attacker. Captain is a prime target for AA, catching them off guard and stunning them only to find you CANT remove their ID unlike every other coat item would be bad design if this is for some weird reason intended.

**Steps to reproduce the problem**:

Apply Captains Jacket item to player, boom uniform and ID slots are blocked from being interacted with by another player. 

**When did the problem start happening**:

No idea, probably since the jacket existed. 

**Extra information**:
![Screenshot (668)](https://user-images.githubusercontent.com/81654328/229044008-c58dea5e-3cbf-46f7-87eb-391c36d34438.png)
![Screenshot (669)](https://user-images.githubusercontent.com/81654328/229044035-20b73e2e-ea07-43c8-b4c1-400e8872de38.png)

**Comment by Contrabang** [comment]
I think this is intended, all of the captain's jackets seem to have this. The jacket, tunic, formal coat, and long white cloak all hide this stuff. The jackets have less armor compared to the carapace, but cover more area.

**Comment by pismorizzo** [comment]
> I think this is intended, all of the captain's jackets seem to have this. The jacket, tunic, formal coat, and long white cloak all hide this stuff. The jackets have less armor compared to the carapace, but cover more area.

At least on the test server none of the pieces of equipment you listed do this, it is only the jacket in the garment bag that does this. So unless there was some wordless change somewhere that did this recently before the test server was sync'd there is no way this is intended. 
![Screenshot (671)](https://user-images.githubusercontent.com/81654328/229187129-0af87cb2-67eb-4ee1-b4b1-935814de5ef2.png)
Screencap showing that the formal coat does not do this also like you said it does, at least on the test server.

**Comment by Henri215** [comment]
> Right, I thought the coats were also open jackets, misread the type. I asked about this to the balance team and theyre currently discussing it

We got a final decision on it?

**Comment by Contrabang** [comment]
I don't remember, I think It was intended?
