### ISSUE TITLE
Apostrophes (') in flavour texts turn to #39 (or something like that).

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#2076]

**Comment by Markolie** [comment]
Thought I fixed this.

**Comment by tigercat2000** [comment]
It was fixed for a while, no idea what broke it again.

**Comment by Markolie** [comment]
Justed tested it in-game, it's working fine. My guess is that you're viewing a flavor text that someone hasn't updated since the fix, and as such the apostrophe is still unescaped. If you edit it and replace the #39 with an apostrophe it should stick.
