### ISSUE TITLE
Pipes are missing, preventing air distribution

### ISSUE THREAD

**Issue by Artorp** [ParadiseSS13/Paradise#208]
Seems like several supply pipes are missing, hindering air from supplying the station. Their coordinates:

134, 88 (manifold, outside atmos)
144, 93 (manifold, surgery)
88, 110 (manifold, cargo)
116, 138 (pipe, bridge)

----

The atmos air distro is unconnected from the rest of the station, only providing air to engineering, medical, science, and part of the bridge. Changing the supply pipes at

(118, 124)

from two crossing pipes into a single 4-way manifold seems to fix this.

----

There are also other pipes missing on other z-levels. On z-level 4 there's a straight pipe instead of the bent pipe at the engineering docking airlock:

(49, 139, 4)

The Labor Camp and the science station are also plagued by pipe issues:

(56, 156, 5) (bent pipe)
(153, 189, 5) (manifold)

**Comment by FalseIncarnate** [comment]
Thank you for providing not only information on missing pipes, but also the coordinates! This should greatly help with mapping to ensure these issues get resolved.

I would like to also add that surrounding the Gravity Generator area are a number of un-insulated pipes directly exposed to space. This pretty much freezes the pipe, preventing airflow from passing through them. Sealing these areas with floors, using insulated piping, or rerouting the pipes to not pass through space should fix the issue.

There is also a missing under the door between atmos control and engineering, where the cyan pipe connects to a distro line. Oddly this may or may not affect air transfer; further observation is needed to be sure though.

I am aware Mark has a PR up for some mapfixes for atmos, which has been merged in. I believe we are simply waiting on that to get patched into the live code to see what is left to fix.

**Comment by Artorp** [comment]
Sure thing, glad to help!

Should me noted insulated pipes doesn't actually seem to *do* anything. They're eye-candy, and identical to regular ones as far as I am aware.

The cyan pipe is connected through an Universal Pipe Adapter. However the graphic for it can be misleading, it doesn't actually change from being connected or not, instead showing the same sprite as a disconnected one. Maybe raise it above the floor?

I checked in singleplayer with the latest build from github, just to be sure these weren't fixed in the latest PRs.

**Comment by Markolie** [comment]
I very much appreciate you tracking down these missing pipes. Unfortunately enough I won't be able to fix this issue for another six days (or make any other PR's, for that matter). Perhaps someone else can quickly fix these? Shouldn't take more than a few minutes (Fox, DZD, Dave)?

**Comment by Fox-McCloud** [comment]
@Artorp 

I corrected all the issues you listed here and moved the universal adapters into maintenance to avoid the visual issues you just mentioned. Lemme know if you find anything further.

**Comment by Artorp** [comment]
Thanks, that did it.
