### ISSUE TITLE
Plasmaman Envirosuit Helmet Doesn't Stop Facehuggers

### ISSUE THREAD

**Issue by anthaily** [ParadiseSS13/Paradise#20807]
**Issue Description**:
Facehuggers can tear the mask off of plasmamen and put larvae in their body through the envirosuit helmet.
The envirosuit helmet is not removed.

**What did you expect to happen**: 
I expected facehuggers to die on impact with the helmet as they do with space suit helmets, biohoods and riot helmets.

**What happened instead**:
The facehugger is able to remove the mask from the plasmaman and impregnate them with larva.

**Why is this bad/What are the consequences**:
The wiki lists envirosuit helmets as one of the clothing options that blocks facehuggers. Plasmamen without access to space suit helmets or hardsuits would be permanently vulnerable to facehuggers.

**Steps to reproduce the problem**:
1.) Be a plasmaman wearing a breathmask, plasma tank, envirosuit and helmet.
2.) Walk next to a facehugger or have one thrown at you.
3.) The facehugger tears off your mask as if you weren't wearing a protective helmet.

**When did the problem start happening**:
I had never played a plasmaman until this year so I'm not sure.

**Extra information**:
Lamarr and the alien toy from mining don't attempt to jump at character wearing protective helmets who walk by them, but they do successfully take the mask off of plasmamen wearing envirosuit helmets.
Plasmamen wearing EVA helmets are treated the same as other crew wearing EVA helmets; it's an issue with the envirosuit helmet specifically.

**Comment by GDNgit** [comment]
Unless you toggle your welding mask on your envirosuit, you're vulnerable to facehuggers. This is intended, not having the welding mode enabled removes cover_flags

**Comment by Contrabang** [comment]
This is intended behavior, as GDNgit has said
