### ISSUE TITLE
Missing west facing sprite on Judge helmet on Vox

### ISSUE THREAD

**Issue by sirjatu** [ParadiseSS13/Paradise#20816]
Missing west facing sprite on the Judge helmet for voxes
The west facing sprite for the Judge helmet is missing for voxes

I expected all the sprites to exist.
Bugs are bad

West facing sprite was not there.
I expected all the sprites to show, on all sides.

Bugs are bad
Bugs are bad

Be a Vox, equip Judge helmet from SecDrobe vendor, face character to West.

Noticed the bug now, when playing Vox

**Comment by Sirryan2002** [comment]
#20623 @GDNgit

**Comment by ATP-Engineer** [comment]
FUCK. Consider it fixed once my PR is merged.
