### ISSUE TITLE
The Lightning Guardian's Lightning Chains Deal No Damage

### ISSUE THREAD

**Issue by anthaily** [ParadiseSS13/Paradise#20813]
**Issue Description**: The lightning chains created when a lightning guardian attacks a mob do not damage the mobs standing on the chain.

**What did you expect to happen**: 
I expected that mobs standing on the lightning chains would take constant burn damage.

**What happened instead**:
Mobs standing on the lightning chain are unaffected.

**Why is this bad/What are the consequences**:
The lightning guardian is completely pointless as a result of this, when compared with the other guardian options.

**Steps to reproduce the problem**:
Summon multiple humanoid mobs or i.e Skrell and Monkeys
Summon a lightning guardian (Beam Guardian) and assume direct control of it.
Arrange the mobs so that they're standing in a line. Hit mob 1, then move so that mob 2 is standing directly between mob 1 and the lightning guardian.
Examine mob 2 or perform a health scan to see how much damage it's taking.

**When did the problem start happening**:
I do not know.

**Extra information**:
I'm unable to test if the lightning chain between a host and a lightning guardian deals damage, but I imagine it doesn't.

**Comment by Contrabang** [comment]
I can reproduce this, but guardians tend to break when they have no master. When testing with two clients, one guardian and one master, it works properly.
