### ISSUE TITLE
I broke cult revive runes

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#20832]
**Issue Description**:
I broke cult revive runes and I'm not at home to fix it

**What did you expect to happen**: 
Revive runes won't yeet people

**What happened instead**:
They do because I put a || operator instead of a && operator 

**Why is this bad/What are the consequences**:
It should be rather obvious

**Steps to reproduce the problem**:

**When did the problem start happening**:

https://github.com/ParadiseSS13/Paradise/pull/20672

**Extra information**:
Change that || to an && and you're golden

**Comment by Sirryan2002** [comment]
Please use a proper title and actually fill out this bug report, if you don't actually get around to fixing this yourself it's pretty much useless to someone who tries to approach fixing this in the future.

**Comment by Contrabang** [comment]
This was broken by the line `if(!mob_to_revive.get_ghost() || mob_to_revive.client && mob_to_revive.client.is_afk())` reportedly, the || here is supposed to be a &&
