### ISSUE TITLE
Syndicate Sentry Bot visible on sec PDA

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#20865]
**Issue Description**:

You can see the Syndicate Sentry Bot on a PDA with a security bot cartridge

**What did you expect to happen**: 

I shouldn't need to know that the Bot is patrolling the depot

**What happened instead**:

Not seeing the Syndicate Sentry bot on my PDA

**Why is this bad/What are the consequences**:

Kind of weird seeing Syndicate bots as HOS

**Steps to reproduce the problem**:

I have no idea what happened differently this round, someone just noticed it

**When did the problem start happening**:

No idea

**Extra information**:

**Comment by Contrabang** [comment]
Same type of problem as #20701, but I'm leaving it open as its technically different
