### ISSUE TITLE
Cryo cells with non-existent occupants

### ISSUE THREAD

**Issue by Greenbean73** [ParadiseSS13/Paradise#20875]
**Issue Description**:

The cryo pods are showing a person inside them, despite there not being a person actually there. Getting in and out of the cryo tubes do not remove the fake person

**What did you expect to happen**: 

The cryo tubes should not have an avatar inside when there is no occupant

**What happened instead**:

The cryo pods keep showing an avatar inside even after the actual person has left

**Why is this bad/What are the consequences**:

It is confusing, and might mislead people into thinking the cryo tubes are still occupied

**Steps to reproduce the problem**:

I unfortunately do not know how it happened, but I did see the actual person leaving one of the glitched tubes

**When did the problem start happening**:

Today is the first time I saw this happening, during round #35359

**Extra information**:

![image psd](https://user-images.githubusercontent.com/87451197/232163533-e40c7932-db97-45ba-868e-65a64fb4df38.png)

**Comment by SynthTwo** [comment]
that's creepy

**Comment by Henri215** [comment]
Priority issue, this is CREEPY!
