### ISSUE TITLE
Examine tab doesn't display full flavor text.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2087]
![](http://i.imgur.com/cRhMvbb.png)
Should display the full flavor text as well as the mob icon (It does display icons for other items, just not mobs, apparently.).
I suspect this is because we don't have Bay's updated flavor text code.
@tigercat2000 @zuhayr

**Comment by tigercat2000** [comment]
;_; :crying_cat_face: :sob: :cry:

**Comment by Spacemanspark** [comment]
Brb writing javascript code making fun of Tigercat.

**Comment by Spacemanspark** [comment]
Be kind of neat to have Bay's flavor text, though.

**Comment by KasparoVy** [comment]
:smirk_cat: 
Holy crap I didn't even know these emoticons existed

Yeah I'm pretty sure you're dead on in your guess there

**Comment by Spacemanspark** [comment]
This still isn't completely fixed, it should also be showing the icon.

**Comment by Markolie** [comment]
That's a BYOND overlay bug which can't be fixed.

**Comment by tigercat2000** [comment]
Not a bug really, just \icon only working for icons

**Comment by Spacemanspark** [comment]
Ah, alright.
Just going off of what I know from Bay's examine tab code.

**Comment by tigercat2000** [comment]
Wait, uh, does bay's work? because if it does I missed something

**Comment by Spacemanspark** [comment]
It does, last I checked.
