### ISSUE TITLE
Dragging tarot card deck from bag into pocket slot causes them to disappear from existence

### ISSUE THREAD

**Issue by SeizingSponge** [ParadiseSS13/Paradise#20900]
**Issue Description**:
Dragging tarot cards from bag into pocket slot causes them to disappear from existence

**What did you expect to happen**: 
I expected that my tarot cards would move from my bag slot to my pocket slot.

**What happened instead**:
 Instead they disappeared into the mist leaving me cardless and humiliated.

**Why is this bad/What are the consequences**:
Losing item because of glitch feels bad even if it could be funny for magic shows

**Steps to reproduce the problem**:
Have leather satchel with loadout tarot cards(I'm guessing this happens with all bags and all cards though}
Drag card deck with mouse from bag slot to pocket slot
Frown as the cards vanish before your eyes

**When did the problem start happening**:
Just noticed this today on April 19, 2023

**Extra information**:
Thank you for reading this bug report I love you

**Comment by Contrabang** [comment]
Hi! Thank you for opening this issue, however this issue has already been reported. I'm going to be closing this as a duplicate as it has already been reported in #17401, #12774, and #12193. We appreciate the bug report though, it helps the developers learn of unknown bugs. I hope this doesn't discourage any future bug reports from you. Thank you!
