### ISSUE TITLE
Escape pod walls stick to walls and windows

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#20948]
**Issue Description**:

The walls on the escape pods are smoothed to the walls and windows (at least on meta).

**What did you expect to happen**: 

For them to be separate.

**What happened instead**:

Sticky pods.

**Why is this bad/What are the consequences**:

It looks bad, the escape pods wouldn't even be able to escape if they were welded to the station!

**Steps to reproduce the problem**:

1. Boot up the game and find an escape pod. (I was on meta)

**When did the problem start happening**:

I noticed it today 26.04.2023, but probably happened last time walls were updated.

**Extra information**:

![image](https://user-images.githubusercontent.com/25958019/234428005-60820477-7f58-4c5e-b81d-bc6316bfbf29.png)
![image](https://user-images.githubusercontent.com/25958019/234428365-bb8107a6-ca26-4653-8b3d-f5e04f251e85.png)

**Comment by 1080pCat** [comment]
_Likely_ broken by [20795](https://github.com/ParadiseSS13/Paradise/pull/20795) not 100% sure though

**Comment by QuacksQ** [comment]
oops

**Comment by QuacksQ** [comment]
I'll look into it lol
