### ISSUE TITLE
Cutting Cutlets In-Hand does NOT Give Bacon

### ISSUE THREAD

**Issue by matttheficus** [ParadiseSS13/Paradise#20959]
**Issue Description**:

Bacon DISAPPEARS!

**What did you expect to happen**: 

I expect to be given bacon.

**What happened instead**:

Poof, meat is gone.

**Why is this bad/What are the consequences**:

Bacon should not just disappear.

**Steps to reproduce the problem**:

1. Hold cutlet in hand.
2. Use knife on it.
3. Get `You cut the raw cutlet with the kitchen knife!`
4. Bacon does not appear.

**When did the problem start happening**:

Unknown.

**Comment by Contrabang** [comment]
![image](https://user-images.githubusercontent.com/91113370/234938082-02b0358e-b32e-4fba-bbff-9e8848c5247d.png)
`new ... (loc)` needs to be something like `src` or `get_turf(src)` here
