### ISSUE TITLE
APC Negative Draw

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [ParadiseSS13/Paradise#20980]
**Issue Description**:

HoP APC was drawing negative on lighting with lights off for some reason.

**What did you expect to happen**: 

I didn't expect weird backwards magic batteries.

**What happened instead**:

Weird backwards magic batteries.

**Why is this bad/What are the consequences**:

I don't know how problematic this is, but I know there's a bunch of PR's underway to rework the power grid so calling attention to this feels prudent.

**Steps to reproduce the problem**:

Look at APC with lights off. Negative power draw. Be confused.

**When did the problem start happening**:

I'm not sure if the SM blowing up played a part in it but that also did happen on the shift from the screenshot below.

**Extra information**:

![image](https://user-images.githubusercontent.com/71111573/235074058-6a53d2e2-20b7-4af7-a54b-de546efe3345.png)

**Comment by Samman166** [comment]
Probably related to power refactor, will try and narrow down the cause when I see it in game, ahelp it if you see it again so if a staff member who feels capable of it can investigate it a bit.

**Comment by Peakwastaken** [comment]
being there at the time there didn't seem to be runtimes regarding powers or APCs/machinery, and I checked many other APCs and none had a similar issue

**Comment by Sirryan2002** [comment]
Have reproduced this several times and am cooking up a fix
