### ISSUE TITLE
Virology pandemic machine doesn't properly recognize slime jelly for blood interaction with viruses.

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [ParadiseSS13/Paradise#20991]
**Issue Description**:

So, when a blood sample of slime jelly is inserted into the pandemic machine, it just says there's no valid blood sample inside.

**What did you expect to happen**: 

I expected it to recognize it as such, so that Virologists can potentially cure slimes and get antibodies from them.

**What happened instead**:

The pandemic machine said get bent.

**Why is this bad/What are the consequences**:

I feel like this is an oversight, making Virology have this weird gap for slime people.

**Steps to reproduce the problem**:

Take a blood sample from a slime person, put it in the pandemic machine.

**When did the problem start happening**:

**Extra information**:

For prudence I also tested a Vox blood sample, as it's also a nonstandard humanoid blood, but it works fine.

![image](https://user-images.githubusercontent.com/71111573/235337321-c4def935-643e-4e77-a0e9-3826fd6086c1.png)

Here you can see me next to my own blood sample as a slime person, to show there is jelly in the syringe.
![image](https://user-images.githubusercontent.com/71111573/235337356-462c75be-6411-4b03-8da0-fafb53e250b9.png)
And here you see the pandemic machine says no.
![image](https://user-images.githubusercontent.com/71111573/235337421-03645fd6-3cd1-4fac-8847-ee2b85973344.png)

**Comment by hal9000PR** [comment]
This was actually intended
