### ISSUE TITLE
broken gas mixer 

### ISSUE THREAD

**Issue by Matesw23** [ParadiseSS13/Paradise#21018]
**Issue Description**:
I placed with RPD a gas mixer in atmo and connected inputs to (87%) plasma and (13%)oxygen. The input pipes when analyzed through analyzer clearly had pressure and correct gasses. The output however was always 100% oxygen no matter the set proportions.
I made gas mixer setup just as described in wiki tutorial https://paradisestation.org/wiki/index.php?title=Gas_Turbine

**What did you expect to happen**: 
I get mixed gas

**What happened instead**:
I got 100% oxygen no matter what

**Why is this bad/What are the consequences**:
It doesn't work

**Steps to reproduce the problem**:
https://paradisestation.org/wiki/index.php?title=Gas_Turbine
Follow this guide and place gas mixer (just as on image) which is supposed to mix plasma and oxygen

**When did the problem start happening**:
We (me and even CE) replaced pipes and mixer several times and output was always 100% oxygen

**Extra information**:

**Comment by DGamerL** [comment]
Sadly this is a result of atmos code being really bad, so it'll stick around and appear sometimes whenever it feels like it, and until someone will refactor atmos code.

Best solution is to just unwrench everything and wrench it back, and give a quick prayer in the meantime.

**Comment by Spaghetti-bit** [comment]
Fixed with https://github.com/ParadiseSS13/Paradise/pull/25328
