### ISSUE TITLE
Slimes go blind from flashlight eyes, despite not having eyes

### ISSUE THREAD

**Issue by jonahmastro** [ParadiseSS13/Paradise#21020]
**Issue Description**:

Slimes go blind from having flashlight eyes installed, but they do not have eyes

**What did you expect to happen**: 

having flashlight eyes would not cause a creature that didn't have eyes in the first place to go blind

**What happened instead**:

Instead, the flashlight eyes DID blind the slime person despite logically it wouldn't happen

**Why is this bad/What are the consequences**:

It causes unneccesary blindness in slime people when it shouldn't happen

**Steps to reproduce the problem**:

Surgically implant crafted flashlight eyes into a slime person

**When did the problem start happening**:

This worked at 1:31 PM, 5/3/23

**Extra information**:

**Comment by Contrabang** [comment]
Currently, it is intended for eyes implanted in slimes to give them new vision (for example, thermal eyes), flash light eyes gives people blindness so, I believe this is intended. Some people are discussing if this should be how eyes work in slimes, so I'll leave this issue open

**Comment by silverplatedelta** [comment]
It has been over a year since this has opened, general consensus is that for both balance and flavor reasons this is working as intended.
