### ISSUE TITLE
Holoparasites can rest, stopping them from moving

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#21086]
**Issue Description**:

Holoparasites can rest, stopping them from moving and confusing the guardian's player

**What did you expect to happen**: 

For the holopara to be able to move, or rather them not able to rest

**What happened instead**:

they couldnt move

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

rest as holopara

**When did the problem start happening**:

always, but more important because of crawling

**Extra information**:

**Comment by Henri215** [comment]
This is probably whats causing https://github.com/ParadiseSS13/Paradise/issues/9794.
