### ISSUE TITLE
Aggresive grab bug.

### ISSUE THREAD

**Issue by Sotrennel** [ParadiseSS13/Paradise#2109]
When you aggresive grab someone, and then switch hands, there is no way to change back to the aggressive grab or to stop the aggresive grab, besides resting on the ground to "break" it.

I think this is a frustrating bug.

**Comment by taukausanake** [comment]
I don't know what you mean, I can switch back to the grab hand and drop said grab fine

**Comment by Sotrennel** [comment]
Strange, at the moment I seemed unable to swap hands.
I had a stunprod in my left and a red grab in my right hand.

**Comment by veganzombeh** [comment]
When you say you can't change hands, do you just mean you can't click on the hand to change it? If so, you can just click the 'Swap' bar just above the hands.
