### ISSUE TITLE
Auto-hiss does not apply to whispering.

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#2110]
Not *really* a bug, but it's definitely inconsistent and seems like an oversight.

**Comment by Fox-McCloud** [comment]
He rrrecommends that that they contact Tigerrrr forrr this parrrticularrr issue.

@tigercat2000

**Comment by tigercat2000** [comment]
Not really a bug, but I'll see what I can do.
(*cries because more saycode*)

**Comment by Spacemanspark** [comment]
Ssssssshit dude.

**Comment by KasparoVy** [comment]
Lmfao, grrreat stuff bud. Good luck sorrrrting this one out

**Comment by NTSAM** [comment]
Noicccccccccccccccccccccccccccccce.
