### ISSUE TITLE
Handcuffs falling off when transforming as a Changeling

### ISSUE THREAD

**Issue by PopGamer45** [ParadiseSS13/Paradise#21133]
**Issue Description**:
Handcuffs fall of from your hands when transforming as a changeling

**What did you expect to happen**: 
The handcuffs should have stayed on when transforming

**What happened instead**:
Handcuffs fell of

**Why is this bad/What are the consequences**:
This bug makes the ability to destroy cuffs with acid useless

**Steps to reproduce the problem**:
1. Be a changeling
2. Put on handcuffs
3. Transform

**Comment by datlo** [comment]
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/14122

**Comment by Henri215** [comment]
As datlo has said its a duplicate of https://github.com/ParadiseSS13/Paradise/issues/14122. Thank you for filling this one anyway.
