### ISSUE TITLE
Nanite Auto Injector not fixing IB IAW PR #12875

### ISSUE THREAD

**Issue by Komrad822** [ParadiseSS13/Paradise#21143]
**Issue Description**:

 Prototype nanite autoinjector isnt fixing IB.

**What did you expect to happen**:

I inject and after a moment my IB  will be gone.

**What happened instead**:

My IB was not gone after said moments.

**Why is this bad/What are the consequences**:

PR #12875 made it so nanites fix IB. 

**Steps to reproduce the problem**:

1. Have IB.
2. inject the prototype nanite auto injector
3. wait.
4. Act like Travolta as you wonder why your IB still isnt fixed. 

**When did the problem start happening**:

No idea

**Extra information**:

**Comment by Contrabang** [comment]
Qwerty confirmed that this is an oversight with the design and needs a fix
