### ISSUE TITLE
Issue with 2FA

### ISSUE THREAD

**Issue by dojoman500** [ParadiseSS13/Paradise#21142]
**Issue Description**:
2FA Prompt did not show, got banned for not authenticating properly

**What did you expect to happen**: 
Expected to be able to enter, get the 2fa prompt, enter my code, and join

**What happened instead**:
![image](https://github.com/ParadiseSS13/Paradise/assets/60892219/24ad43b5-4b10-4fe3-bcd5-396e4b83dcd2)

**Why is this bad/What are the consequences**:
Falsely banned for failing 2FA despite never getting the dialog to enter the code

**Steps to reproduce the problem**:
Was creating a new Tajaran character when the server closed for the new round. BYOND failed to reconnect me for some reason and effectively crashed. Upon closing the crashed window and trying to reconnect, I got the banned for 2FA screen, while never getting a chance to verify it

**Extra information**:
Also lost all progress on my tajaran character most likely due to the server restarting, but that's irrelevant

**Comment by AffectedArc07** [comment]
Hello

Are you playing on a IP shared with someone else?

**Comment by dojoman500** [comment]
> Hello
> 
> Are you playing on a IP shared with someone else?

No, I'm the only one who even has BYOND at my house

**Comment by AffectedArc07** [comment]
Few things worth of note:
1. 2FA set to `Always` is somewhat buggy with round restarts and the way its handled behind the scenes as its based on internalised routing on IP not ckey, and it isn't perfect
2. Could you try connecting again please?
3. Failing that, could you try going to https://paradise13.org/fixtos then try reconnecting a second time?

**Comment by dojoman500** [comment]
> Few things worth of note:
> 
> 1. 2FA set to `Always` is somewhat buggy with round restarts and the way its handled behind the scenes as its based on internalised routing on IP not ckey, and it isn't perfect
> 2. Could you try connecting again please?
> 3. Failing that, could you try going to https://paradise13.org/fixtos then try reconnecting a second time?

Someone ahelped on my behalf to let me back in, I was able to get back in. I have it currently on IP change now since I'd rather not get false banned again

**Comment by AffectedArc07** [comment]
Closing as solved
