### ISSUE TITLE
AI cloning record management

### ISSUE THREAD

**Issue by RobloxPlayer16** [ParadiseSS13/Paradise#21157]
**Issue Description**:

AI cannot delete cloning records because it "does not have an ID in hand"

**What did you expect to happen**: 

The record to be deleted

**What happened instead**:

The record could not be deleted

**Why is this bad/What are the consequences**:

Could mess up taitor AI objectives. in my case it was an issue of an ashen skeleton being in the records, when it should not. I could not delete it to clear the cloner list. 

**Steps to reproduce the problem**:

Have a record in the cloning records
as AI try to delete it.

**When did the problem start happening**:

Not sure. Don't think I've ever tried to delete a cloning record as AI before. did not work today 5/22/23

**Extra information**:

**Comment by FridgeBurns** [comment]
this is fixed by #21495

**Comment by Henri215** [comment]
Like FridgeBurns said, fixed by https://github.com/ParadiseSS13/Paradise/pull/21495
