### ISSUE TITLE
Communications Console -- Unable to raise Alert

### ISSUE THREAD

**Issue by Spaghetti-bit** [ParadiseSS13/Paradise#21165]
**Issue Description**: Captain and command are unable to raise the alert level via communications console.

**What did you expect to happen**: For the alert level to raise.

**What happened instead**: "You are not authorized to do this" with captain access.

**Why is this bad/What are the consequences**: Being unable to up the code level without staff intervention is very bad. I don't want to go into the consequences. 

**Steps to reproduce the problem**: Click on dah console. Log in. Cry.

**When did the problem start happening**: Round 35827

**Extra information**: N/A

**Comment by farie82** [comment]
Fixed in https://github.com/ParadiseSS13/Paradise/pull/21166

**Comment by Contrabang** [comment]
oops.
