### ISSUE TITLE
Ghosts keep the antaghud HUD even if they unclick the option

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#21178]
**Issue Description**:
I turned off ahud to make some dchat screenshots, but it kept the vampire/antag icon showing. The orbit menu was still correct, however.

**What did you expect to happen**: 
Get some nice, HUDless screenshots

**What happened instead**:
Got HUD in my screenshot

**Images**:
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/c7f9bd99-ac99-4ae4-821c-f61e8bccc092)
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/94274b8b-db4a-48a6-afe5-fbfb76acd9b5)

**Why is this bad/What are the consequences**:
Most likely not something that is supposed to happen.

**Steps to reproduce the problem**:
Die
Turn on ahud
Turn off ahud
Still see ahud

**When did the problem start happening**:
Unsure, might be since the "holding a plant removes the HUD"

**Extra information**:
I did leave and come back halfway, but that might not affect it at all.

**Comment by Henri215** [comment]
Could replicate on an older version, not related to that PR it seems.
