### ISSUE TITLE
Destructive analyzer destroys entire stacks of bluespace crystals at once

### ISSUE THREAD

**Issue by ColKev1** [ParadiseSS13/Paradise#21181]
**Issue Description**:

Currently the destructive analyzer will consume every single item in a stack of bluespace crystals at once.

**What did you expect to happen**: 

Destructive should only consume a single item from the stack like it does other materials

**What happened instead**:

It eats the entire stack

**Why is this bad/What are the consequences**:

Losing crystals to bugs feels bad given the rarity of bluespace crystals

**Steps to reproduce the problem**:

Insert >=2 Bluespace crystals into a destructive analyzer and hit the deconstruct button, lose all crystals in the destructive analyzer

**When did the problem start happening**:

I've only had it happen to crystals made by Xenobio in the past, but the new PR to standardize crystals https://github.com/ParadiseSS13/Paradise/pull/21028 makes it happen to ORM output crystals 

**Extra information**:

**Comment by Henri215** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/cabf4826-99fd-49d9-9b33-0af621f21846)
Probably related to that, since the crystal sheet_type is an ore and not a proper sheet.
