### ISSUE TITLE
money infinite bug

### ISSUE THREAD

**Issue by Javi1990** [ParadiseSS13/Paradise#2120]
because in an empty game I went to create a new bank account, I put a number too high 999999, my account became causing infinite money, Account balance: $1.19102e+006 
and that money can buy things and can cause an imbalance, to put such a high number should mean it is not possible for lack of funds

Thanks for your time

**Comment by Markolie** [comment]
Did you create a new account using the accounts database?

**Comment by Javi1990** [comment]
yes, Using Computer hop, it is assumed that when I create an account money is removed from the account of the station

**Comment by Markolie** [comment]
Right, thanks. Will investigate.
