### ISSUE TITLE
[ATMOS] Various undocumented changes

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2121]
Volume pumps and gas pumps. Now have an error message saying "Remove flooring before wrenching". They will wrench up after removing flooring. (yes they are turned off)

The digital switching valve for redirecting flow to the freezers is now replaced by a manual T-Valve. The T-valve isn't setup in the right direction.

The digitial switching valves for O2, N2 and Air tanks all start as turned off. Although this may have been a traitor AI but it was like this 10 minutes into the round.

Arrivals atmospherics may start empty? (Could've been a traitor though)

**Comment by Markolie** [comment]
Investigating, thanks for the report. None of these are intentional, by the way.

**Comment by Taaketa** [comment]
I guess so. But I also keep a close eye on the Pull requests and didn't see any planned changes to atmos. Hence why I am confident in saying "undocumented" :)
