### ISSUE TITLE
You can't remove case from Implantpad

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2122]
Title, i forgot about this bug due to NEVER being blueshield, but this allows things like naming implants and setting them more accuratly and what not, but you can't due to the pad being unable to eject.

Second bug, locator implants are registered on 145.9 which is fine, if it was not for the fact that the implants are also on the frequency and checking them out does not work unless you change it, even then it does not give accurate location.

Here is what i get from 6 implanted heads.
electronic-southeast-very weak
electronic-southeast-very weak
electronic-southeast-very weak
electronic-southeast-very weak
electronic-southeast-very weak
electronic-southwest-very weak
which would be fine if refreshing it was convinient and you did not have to change frequency refresh and then change it to see it.

**Comment by Fox-McCloud** [comment]
Ugh. Not surprised. Our implant code is AWFUL.
