### ISSUE TITLE
Door open if you are in them when they close

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2123]
not sure if this is a feature or a bug, either way it needs to be removed.

Lets just... remove the door safeties over every door, and make em close fast, and kill anyone who is alone. This needs to be changed, like making it a closed door when it begins closing, instead of after.

**Comment by Markolie** [comment]
Feature requests go on the forums.

**Comment by tigercat2000** [comment]
actually, this is a bug, i think there is already an issue report open; doors without safties that close are not supposed to auto open again

**Comment by Robertha89** [comment]
This is not a feature request, this is a bug where doors autocrushes you if safeties are disabled, and thats kinda broken. Especially since it looks like the AI is doing it.

**Comment by Fox-McCloud** [comment]
Yeah, it's definitely a bug; the door is supposed to crush the person once and that's it; killing someone with door crushing is supposed to require someone actively triggering it.
