### ISSUE TITLE
Zippos don't have an in-hand sprite when turned on

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#21257]
**Issue Description**:
Zippos don't have an in-hand sprite when they are turned on.

**What did you expect to happen**: 
To at least keep the display of the zippo, instead of it just simply vanishing.

**What happened instead**:
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/12ee6394-a39d-403e-85b3-2857b062ad45)
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/62048f4c-37ec-49ed-8ca2-d1e1a382960e)

**Why is this bad/What are the consequences**:
Just a small sprite bug.

**Steps to reproduce the problem**:
1. Get zippo
2. Turn it on
3. Magic zippo disappears

**When did the problem start happening**:
Unsure

**Comment by Stealthii** [comment]
There's a few contributing factors to this bug, in fact it completely disappears for any special zippo lighter after first ignition.

The main one is logic in `/obj/item/lighter/proc/turn_{on|off}_lighter`, which sets both the `icon_state` **and** `item_state` to either 'icon_on' or 'icon_off'. There are held item sprites for "zippo", but none of the other custom zippos nor the base lighter item.

I've fixed this bug in #22150, as well as update the logic around icon updates to be more consistent with upstream, and enable a path forward for updated held graphics as well!
