### ISSUE TITLE
IPC brains have no name

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2126]
Alright, not exactly sure how far this goes, don't have the time to test this; but basically, IPC brains do not have a real_name.

Test case:
 - Be IPC
 - VV mmi_holder organ
 - Call proc, removed, 0 arguments
 - Posibrain pops out, VV posibrain
 - Notice posibrain is named `positronic brain ()`
 - VV brainmob, notice name and real_name are both null
 - Panic, `[blank space] says, "KILL ME."`

**Comment by Markolie** [comment]
They only don't have a name when they're in the mob and they're admin'ed out of there without the mob actually being moved with it. When they're properly dropped (i.e. on gib) the mind of the IPC will be transferred to the brain, thus also transferring the name.

**Comment by tigercat2000** [comment]
@Markolie Ahah, had a feeling that was the case. Thanks, mark.

**Comment by Markolie** [comment]
Is actually a bug, it seems. Will fix.
