### ISSUE TITLE
Hydro trays not setting lighting

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#2131]
I just noticed today but when I try to set a hydro tray's light to a different value it doesn't change. Currently they are all set to 10 lumens and won't go lower. Don't know if this affects plants growing but it would be nice to look into it

**Comment by taukausanake** [comment]
That was fast labeling ._.

**Comment by FalseIncarnate** [comment]
Hydro tray lights only work when the lid is up, otherwise they pull the light from their tile

If the lid being up doesn't change this, that would be a bug, otherwise working as intended.

**Comment by taukausanake** [comment]
Huh. I didn't think that mattered. Okay, not a bug. Derp me
