### ISSUE TITLE
Upon disassembling roundstart freezers giving 30 cables instead of 1

### ISSUE THREAD

**Issue by kano-dot** [ParadiseSS13/Paradise#21328]
**Issue Description**:
title

**What did you expect to happen**: 
obtaining one cable instead of whole stack, as per construct requirement

**What happened instead**:
i got 29 more cables than i should've

**Why is this bad/What are the consequences**:
bugs are bad

**Steps to reproduce the problem**:
spawned in any type of map and dismantled a roundstart freezer

**Comment by warriorstar-orion** [comment]
Can reproduce.
