### ISSUE TITLE
dark blessing bug

### ISSUE THREAD

**Issue by Swissik** [ParadiseSS13/Paradise#21332]
so i was playing shaft miner and i found a dark blade and used it then i ended dying in lava so my brain was moved to a new body and when i tried to get the dark blade back i was unable to equip it and no one else could either

**Comment by Contrabang** [comment]
How did you get the dark blessing off the body?

**Comment by Contrabang** [comment]
Seems to be an issue with abstract being added on pickup, but not removed on dropped
