### ISSUE TITLE
Infinite metal with the Holodeck.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2133]
-Enter holodeck.
-Set holodeck mode to 'theater'
-Destroy racks via wrench or kicking them down
-Convert racks assemblies to metal
-Refresh the theater holodeck.
-Rinse and repeat to make infinite metal
How has this not been discovered before now?

**Comment by tigercat2000** [comment]
>How has this not been discovered before now?

Have you considered that many people have known about it for a while and no one made a bug report because they didn't want it fixed?

**Comment by Spacemanspark** [comment]
Yes.

**Comment by Markolie** [comment]
Spaceman's doing God's work.
