### ISSUE TITLE
Getting out of a mech on a connector port makes this alert not disappear

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#21344]
**Issue Description**:

Getting out of a mech on a connector port makes this alert not disappear

**What did you expect to happen**: 

Alert to not show up

**What happened instead**:

![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/b5a50d06-9545-4044-8e9b-221bb40e8c77)

**Why is this bad/What are the consequences**:

bug bad

**Steps to reproduce the problem**:

1. be in firefighter (or maybe a ripley, not sure)
2. go on top of connector port
3. get out of mech
4. alert there for the rest of the round

**When did the problem start happening**:

always? not sure

**Extra information**:

**Comment by 1080pCat** [comment]
I've noticed this a few times where just walking over one will pop it up, then just not make it go away, so im not sure if leaving the mech is the cause of it?
