### ISSUE TITLE
pod people ship on lavaland spawning with cold air.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#21361]
**Issue Description**:

The pod people ship on lavaland seems to be spawning with lethally cold air

**What did you expect to happen**: 

20C

**What happened instead**:

-18.1C air

**Why is this bad/What are the consequences**:

Ruins like this should not kill its inhabitents.

**When did the problem start happening**:

Only seen it past few days personally.

**Comment by warriorstar-orion** [comment]
This is referring to `lavaland_surface_seed_vault.dmm`, but I was not able to reproduce the issue on 33a97a4c95c4ecaaa2912ca0e1d11f5f23d0ebd6. These are the TMs that were running at the time.
![2023_06_16__22_40_56__#coding_chat _ Paradise Station - Discord](https://github.com/ParadiseSS13/Paradise/assets/59303604/6cf85b92-0218-4b6c-8f66-843f4ec5738c)

**Comment by kugamo** [comment]
If their rooms are mapped with `/turf/simulated/floor/plasteel/freezer` then its due to Shepard TM, I altered this in the Shepard PR so that kitchen freezers would start cold.

**Comment by kugamo** [comment]
Fixed since [e88a035](https://github.com/ParadiseSS13/Paradise/pull/21083/commits/e88a035c62380b0814a7b2079ef843052abe6200) .... I made the cold tiles a subtype.

**Comment by warriorstar-orion** [comment]
As above, this was caused by a TM, not code already submitted.
