### ISSUE TITLE
Unsatisfactory Table Behavior

### ISSUE THREAD

**Issue by Rosebrandon0** [ParadiseSS13/Paradise#21362]
**Issue Description**:

When a multi-tile table is flipped and then put back, the result is a multi-cell table.

**What did you expect to happen**: 

The table(s) should return to their merged state.

**What happened instead**:

The table formed a multi-cell table when put back.

**Why is this bad/What are the consequences**:

This breaks the continuity of the table's expected behavior in an unrealistic manner.

**Steps to reproduce the problem**:

Flip any table that is merged and then put it back.

**When did the problem start happening**:

Just now.

**Extra information**:

![image](https://github.com/ParadiseSS13/Paradise/assets/58378041/ba216f20-08ba-4c0e-8ef4-66b9e9fa75b6)

**Comment by Contrabang** [comment]
Table smoothing my behated
