### ISSUE TITLE
Throw Mode Icon stays on after death

### ISSUE THREAD

**Issue by Cocacolagua** [ParadiseSS13/Paradise#21418]
**Issue Description**:
If you have throw-mode active and then die, your mouse icon will stay as the throw-mode icon, even though you can't actually throw shit as a ghost.

**What did you expect to happen**: 
For the mouse icon to go back to normal.

**What happened instead**:
It stayed like that.

**Why is this bad/What are the consequences**:
UGLY!!!! EWWWW!!!! very icky. not good.

**Steps to reproduce the problem**:
1. try to throw
2. die
3. ughhhhhh

**When did the problem start happening**:
#21219

**Comment by kugamo** [comment]
It also stays on if you drop the item :o)

**Comment by HMBGERDO** [comment]
> It also stays on if you drop the item :o)

You don't need item to have throwmode on
