### ISSUE TITLE
Storage implant doesn't store anything.

### ISSUE THREAD

**Issue by GreatGatherer** [ParadiseSS13/Paradise#21453]
**Issue Description**:
Storage implant doesn't store items, its one and only benefit.
Instead, it is merely an implant, without the storage.
Tested items of all various item sizes, from tiny to normal, the usual cutoff. Nothing.

**What did you expect to happen**: 
I expected to be able to store my contraband and/or theft objectives in the implant.

**What happened instead**:
Implant pops up the UI, however, items simply do not enter the slots.

**Why is this bad/What are the consequences**:
I spent my telecrystals on the storage implant, I expect it to do something, instead of just give me a cool looking button.

**Steps to reproduce the problem**:
1: Buy storage implant
2: Inject self with storage implant
3: Open implant
4: ???
5: Shit's fucked.

**When did the problem start happening**:
Can't remember the last time I used a storage implant, got one out of a surplus when I discovered this. Last I recall was in March.

**Extra information**:
Implant gotten out of a surplus. Possible issue with surplus crates providing non-functional storage implants.

**Comment by warriorstar-orion** [comment]
I wasn't able to reproduce this on b759ced58bbd8376318131c513ee04d336736b4b.

![2023_06_25__13_30_51__](https://github.com/ParadiseSS13/Paradise/assets/59303604/64989f92-0f5f-4bea-83d2-da975cd16947)

Did you have any other implants or abilities?

**Comment by Burzah** [comment]
Tested again by acquiring the implant through a surplus crate. I was unable to reproduce the issue.

**Comment by warriorstar-orion** [comment]
With two failures to recreate the issue and no response after over a month, closing. Please feel free to re-open if you encounter the issue again.
