### ISSUE TITLE
Cmagged Gravity Generator Effect not Reverting After Cleaning

### ISSUE THREAD

**Issue by Bjamcham** [ParadiseSS13/Paradise#21450]
**Issue Description**:
Cleaning a cmagged gravity generator with soap does not revert the waddling effect although the oozing slime indicator message no longer appears on examine. 

**What did you expect to happen**: 
To no longer be waddling

**What happened instead**:
The entire crew continued to waddle

**Why is this bad/What are the consequences**:
Unreversible constant waddling is a tad over the top

**Steps to reproduce the problem**:
1. cmag the gravity generator
2. clean it with soap(several times)
3. disable and then enable gravity just to be sure
4. Continue to waddle

**When did the problem start happening**:
#20944

**Comment by lewcc** [comment]
I've been trying really hard to find a repro, but paradoxically it seems to always work in solo testing. There might be an element of requiring multiple mobs/clients?

**Comment by Henri215** [comment]
Closing since the feature has been reverted by https://github.com/ParadiseSS13/Paradise/pull/21493, it may be reopened later if it ever comes back with the same problem.
