### ISSUE TITLE
When building airlocks, airlocks spawn itself 2 times

### ISSUE THREAD

**Issue by PopGamer45** [ParadiseSS13/Paradise#21452]
**Issue Description**:
When you complete construction of a airlock the airlock spawns 2 times

**What did you expect to happen**: 
When building a airlock only 1 airlock should be spawned

**What happened instead**:
2 airlocks spawned

**Why is this bad/What are the consequences**:
Players could duplicate materials

**Steps to reproduce the problem**:
> Build a airlock
> 2 airlocks spawn

**When did the problem start happening**:
Not sure

**Comment by Sirryan2002** [comment]
could you please explain this in some more detail.

1. What kind of airlock were you constructing?
2. How were you building it? By using materials in hand or and RCD?
3. At what point did the airlock duplicate? When you made the frame of the airlock or during a step in the construction process?

**Comment by PopGamer45** [comment]
1. A double airlock and a public airlock, so it seems its on all types of airlocks
2. Using materials in hand
3. It duplicated at the last step of the construction, so when you use a screwdriver on it
Sorry for missing out on details

**Comment by Sirryan2002** [comment]
thank you, it helped us narrow down where the issue was!
