### ISSUE TITLE
Cmagged grav gen not affecting borgs in rechargers.

### ISSUE THREAD

**Issue by Alantodne** [ParadiseSS13/Paradise#21451]
**Issue Description**:
When a Cyborgs in rechargers arent affected by clown gravity if they are in the recharger when it goes off.

**What did you expect to happen**: 
Cyborg in the recharger to be affected by clown gravity when it leaves the recharger. 

**What happened instead**:
When the cyborg exited the recharger everyone else was walking like clowns except the cyborg that was in the recharger when the gravity went clown.

**Why is this bad/What are the consequences**:
Cyborg not having his clown gravity when gravity goes clown.

**Steps to reproduce the problem**:
Cyborg enters recharger. 
Gravity goes clown.
Cyborg exits recharger.
Observes others walking in clown grav, but not themselves.

**When did the problem start happening**:
Recently, probably around the time the clown gravity got introduced.

**Extra information**:
Clown gravity stunning borgs EVERY SINGLE TIME you enter and exit a gravity fields sucks especially as a cyborg. if you enter space from engie maints between SM and atmos, going to AI sat. you get stunned like 4-5 times.

**Comment by Henri215** [comment]
Closing since the feature has been reverted by https://github.com/ParadiseSS13/Paradise/pull/21493, it may be reopened later if it ever comes back with the same problem.
