### ISSUE TITLE
Polarized glass doors are extremely buggy

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#21479]
**Issue Description**:

Polarizing a glass door, will make the glass disappear and appear randomly. Repainting the door will make it even worse, switching between its original icon and the repainted icon randomly.
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/a9a79a78-9fbf-41b6-8784-998579a34c11)
(Theres glass in these doors!)
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/e7b88b26-be92-4ff1-b0e4-d6973eae24cd)
(Repainted command colors, randomly showing the white doors when you open and close them)

**What did you expect to happen**: 

The doors to look normal

**What happened instead**:

They were not normal

**Why is this bad/What are the consequences**:

it BREAKs them

**Steps to reproduce the problem**:

1. Polarize the doors (for me, in chapel)
2. be confused, where did the glass go?
3. put down a polarization switch, it does nothing. You can just never see through the doors
4. Paint them another color
5. Open the door, be confused when the animation is showing the white door

**When did the problem start happening**:

Uhhh, that change to doors to let them use reinforced glass, probably

**Extra information**:

**Comment by DGamerL** [comment]
... What the fuck. I'll see about getting a fix up today.

**Comment by SteelSlayer** [comment]
Potentially related to #21440.
