### ISSUE TITLE
Three out of four suit storages in expedition room are CLOWN EVA storage units on NSS Arrhodes map

### ISSUE THREAD

**Issue by ATP-Engineer** [ParadiseSS13/Paradise#21480]
**Issue Description**:

3/4 EVA suits are clown EVA suits for expedition room on the NSS Arrhodes map. Mapping error.

**What did you expect to happen**: 

For Explorers not to be supplied with clown costumes

**What happened instead**:

HONK
![image](https://github.com/ParadiseSS13/Paradise/assets/120416457/aa333161-a782-4114-8415-74da8185d499)

**Why is this bad/What are the consequences**:

3/4 explorers need to take from EVA storage if they dont want to look stupid in space.

**Steps to reproduce the problem**:

Explorer  -> * High, Vote NSS Arrhodes, Go to top right of room, open 3 suit storages.

**When did the problem start happening**:

Likely since NSS Arrhodes TM'd, just not reported.

**Extra information**:

N/A

**Comment by kugamo** [comment]
This has been fixed in `[65ff39c](https://github.com/ParadiseSS13/Paradise/pull/21083/commits/65ff39c7ae1ced19853c6a507da20baa61ed633f)` So shouldnt be an issue anymore on the map, at least as soon as the TM is updated.
