### ISSUE TITLE
Persistent and Duplicate Station Alerts. Map Bug(?)

### ISSUE THREAD

**Issue by Rosebrandon0** [ParadiseSS13/Paradise#21482]
**Issue Description**:

Station alerts will sometimes remain on the alerts console even when the system state should display as nominal.

**What did you expect to happen**: 

The Auxiiary tool storage should not be showing a power alrt in this state.

**What happened instead**:

The below screenshot shows the state of one of the affected APCs, which should not be generating an alert.

![image](https://github.com/ParadiseSS13/Paradise/assets/58378041/f55a632d-f6ba-44ed-9b9b-a8af31c63f5c)

The below screenshot shows the state of another APC of the affected area, which should not be showing an alert.

![image](https://github.com/ParadiseSS13/Paradise/assets/58378041/71274487-35c1-4ec5-9e9a-8cc39f20e87e)

I also attempted to deconstruct and reconstruct both of the target APCs, and the result was two power alerts for the same area that are now stuck.

![image](https://github.com/ParadiseSS13/Paradise/assets/58378041/97366a0c-1af2-4e20-b502-5d3187666d19)

**Why is this bad/What are the consequences**:

Erroneous alerts add clutter to the station alerts UI.

**Steps to reproduce the problem**:

Unsure what causes alerts to remain stuck like this. This behavior might be unique to areas like this Aux Tool Storage on Shepherd, since places are normally not supposed to have more than one APC associated with them.

**When did the problem start happening**:

Now.

**Extra information**:

I've made sure to open and close the alerts UI to account for the alerts UI not refreshing on it's own. 

I confirmed that both the APCs I've mentioned are blueprinted as one contiguous room, by accident, when I attempted to deconstruct and reconstruct the first APC and recieved the message that the room already has an APC.

Auxillary Tool Storage APC shown in this image was on Sherpherd Station. The Auxillary Tool Storage has more than one APC associated with it. The presence of more than one APC per area is a continuity break from other station designs, and a state not achivable under normal conditions. This might be related to this strange alert behavior.

**Comment by kugamo** [comment]
The two apcs were erroneous, and I meant for them to be in seperate areas. Not sure to what degree it is the cause, but I've updated the map regardless. I think the game stops people from making another APC in an area with one already, the state of the game that caused it shouldn't be normally possible.

![StrongDMM_L64hc1pGTW](https://github.com/ParadiseSS13/Paradise/assets/16618648/cd65b85f-524c-4ba9-8e7b-a3e16a40a0dc)
