### ISSUE TITLE
Atmos Alarm Visual Bug

### ISSUE THREAD

**Issue by Rosebrandon0** [ParadiseSS13/Paradise#21492]
**Issue Description**:

Air Alarms will sometimes display as finished and functional when placed.

**What did you expect to happen**: 

The Air Alarm should be represented in it's unfinished state.

**What happened instead**:

![image](https://github.com/ParadiseSS13/Paradise/assets/58378041/a190e947-5c89-441a-b56e-21bff93ef49f)

**Why is this bad/What are the consequences**:

This is an obvious visual bug.

**Steps to reproduce the problem**:

Begin construction of an Air Alarm. Sometimes.

**When did the problem start happening**:

Now.

**Extra information**:

I'm not sure how to reliably reproduce this visual bug.

**Comment by Contrabang** [comment]
The frame just needs better update_icon_state code, I remember looking at this before
