### ISSUE TITLE
Not all Maintenance in Arrhodes/Sheperd protects you from Radiation

### ISSUE THREAD

**Issue by BasilTamaya** [ParadiseSS13/Paradise#21517]
**Issue Description**:

Not sure about most maints since this was only tested in the Bar Maintenance of Arrhodes, but that maints specifically did not protect people from radiation

**What did you expect to happen**: 

Bar Maints, as titled as maints, should've protected me from rads.

**What happened instead**:

Every other person that sat in it with me suffered from radiation poisoning, and I turned into a gorilla

**Why is this bad/What are the consequences**:

It's called bar maints so as part of maints it should protect you from rads

**Steps to reproduce the problem**:

Sit in it during rads.

**When did the problem start happening**:

Probably has been an issue ever since it got merged. Unsure.

**Extra information**:

Round ID: 36347
Date: 2023-06-29

![image](https://github.com/ParadiseSS13/Paradise/assets/138180883/c22ef5cc-4942-4afe-a68a-2e8a8ee4d3ac)

**Comment by kugamo** [comment]
should be fixed in latest commit [dabb524](https://github.com/ParadiseSS13/Paradise/pull/21083/commits/dabb5249b9c7a2173cd2ce76f28cd2b68dc12185)

**Comment by Contrabang** [comment]
Fixed by Shepard author
