### ISSUE TITLE
Ebows (And likely the mini ebow as well) cause IPC's to move slower permanently when hit.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2151]
Following Dave shooting me with a toxins dart from a large Ebow, my IPC's walkspeed was slowed down by at least half for the rest of the round.

**Comment by Markolie** [comment]
It's because it causes Tox damage, and IPC's weren't meant to take those. As it's been a few weeks since the IPC overhaul PR and that mechanic still hasn't been touched, I'm removing toxin damage from IPC's completely now.

**Comment by Spacemanspark** [comment]
I figured it was something to do with toxins damage.

**Comment by Markolie** [comment]
Okay, @FalseIncarnate is working on reworking the synth chems not to use toxin damage - once that's done we can give IPC's NO_POISON back.
