### ISSUE TITLE
Clown Gene and Stammer creates an unusual effect

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#2155]
Unsure if this has already been seen and or notified about but here's some of it in action.

When you're in a critical state/tazed etc. the stammer effect along with the Clown's comic sans creates an unusual effect.

![clown](https://cloud.githubusercontent.com/assets/13933611/10073549/ae326716-62c1-11e5-92ab-d38b85d557a1.png)
(edit, spelling mistake on creates)

**Comment by Markolie** [comment]
Already fixed.

**Comment by Markolie** [comment]
Remember when I said this was fixed? I LIED.

https://github.com/ParadiseSS13/Paradise/pull/5807
