### ISSUE TITLE
Heat Exchager Visual Bug

### ISSUE THREAD

**Issue by Rosebrandon0** [ParadiseSS13/Paradise#21586]
**Issue Description**:

Heat Exchangers place over space are invisible.

**What did you expect to happen**: 

The heat exchanger should be displayed.

**What happened instead**:

![image](https://github.com/ParadiseSS13/Paradise/assets/58378041/f0fe7a58-d83c-4ab7-be2d-f36a6f3b946a)

**Why is this bad/What are the consequences**:

This is an obvious visual bug.

**Steps to reproduce the problem**:

Place a heat exchanger over a tile then expose that tile to space.

**When did the problem start happening**:

now

**Extra information**:

The object only turns invisible when wrenched into place. The freemoving pipe sprite is unaffected.

**Comment by meow20** [comment]
These become visible when at least one other HE pipe is connected to them IIRC

**Comment by EmeraldCandy** [comment]
this is an issue with ALL atmos pipes if I remember correctly. In my experience wrenching down only one pipe does indeed make it invisible until you connect another to it

**Comment by lewcc** [comment]
I've done a bit of investigation, and it looks like some of these pipes (heat exchangers in particular) are just missing their `exposed00` icon states. This looks like not too hard of a fix, but just requires someone with spriting knowledge.
