### ISSUE TITLE
Missing Blueshield office pipe

### ISSUE THREAD

**Issue by ArcticValor** [ParadiseSS13/Paradise#21627]
one singular air scrubber pipe is missing from the Blueshield office right under the door (seen below) not sure if this was intentional or an oversight.
![image](https://github.com/ParadiseSS13/Paradise/assets/132216854/47ccc26a-72f0-4ff7-9501-bb2b997d3765)

**Comment by AffectedArc07** [comment]
Map name?

**Comment by warriorstar-orion** [comment]
That'll be Box, I can see the pipe missing in SDMM too.

**Comment by Stealthii** [comment]
This was fixed by @Venuska1117 in #21425.

**Comment by ArcticValor** [comment]
forgot to close woops
