### ISSUE TITLE
Vox Mimes no Longer Spawn w/ Mime Mask in Backpack

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#2163]
The title says it. Before a recent patch, Vox Mimes got a breath mask on the face and a Mime mask in the pack. Now it's just a Vox breath mask and no Mime mask to be seen at all. IDK about Clown, but I speculate this may be the case for them too (haven't had the chance to test)

**Comment by KasparoVy** [comment]
Thanks a ton! I'll go ahead and close this once 2162's in

**Comment by Markolie** [comment]
No problem! Closing it won't be necessary - it'll do so automatically when the PR is merged: https://help.github.com/articles/closing-issues-via-commit-messages/.
