### ISSUE TITLE
Flaptonium spawns parrot with engineering headset

### ISSUE THREAD

**Issue by PopGamer45** [ParadiseSS13/Paradise#21632]
**Issue Description**:
When a parrot spawns from flaptonium it comes with a engineering headset

**What did you expect to happen**: 
Flaptonium should spawn only the parrot not the headset too

**What happened instead**:
Parrot spawned with engineering headset

**Why is this bad/What are the consequences**:
Gives a unintended way of acquiring a departmental headset to players

**Steps to reproduce the problem**:
1. Make flaptonium
2. Parrot spawns
3. Parrot has engineering headset

**Comment by warriorstar-orion** [comment]
Oh my god, apparently all parrots start with a random department headset.

https://github.com/ParadiseSS13/Paradise/blob/c85e015c262464be60933600c6c9ccbff913891b/code/modules/mob/living/simple_animal/parrot.dm#L90-L102
