### ISSUE TITLE
There is no APC in Cyberiad science maint

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#21633]
**Issue Description**:

There is no APC in Cyberiad science maint
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/027349b6-d2d8-409f-a8bb-da0e29f6a16c)

**What did you expect to happen**: 

There to be an APC

**What happened instead**:

Infinite power glitch /s

**Why is this bad/What are the consequences**:

Antagonists cannot sabotage the power in sci maint

**Steps to reproduce the problem**:

open cyberaid

**When did the problem start happening**:

Sci maint rework probably

**Extra information**:

Couldnt find an issue on it, so I opened this one

**Comment by Coolrune206** [comment]
Isn't it in engi checkpoint?

**Comment by Contrabang** [comment]
> Isn't it in engi checkpoint?

Thats in asmaint2, this scimaint is just asmaint
