### ISSUE TITLE
pAI Availability list

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#2165]
There is now a minute cooldown on reflesh available personalities which has the side effect of there being a minute in which you cannot download any new personalities that have added themselfes to the list

**Comment by Markolie** [comment]
Intentional to stop ghost spam.

**Comment by joonasm** [comment]
its still annonying having to wait a minute before you can download any pAI's if none have been requested before you got the device

**Comment by Markolie** [comment]
I realise that, but unfortunately enough it's a necessary evil as some players just love to spam too much.
