### ISSUE TITLE
Cryodorms stores IPC positronic brains when they enter cryosleep

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#2168]
being transfered to cryostorage seems to leave your positronic brain into the object storage
![2015-09-25_20-18-47](https://cloud.githubusercontent.com/assets/589709/10107330/fc03fb74-63c2-11e5-9e78-d76a5948bc66.png)

**Comment by Spacemanspark** [comment]
You can shut off the posibrain and ask for a new personality, though. I wouldn't really count this as a bug.

**Comment by Spacemanspark** [comment]
This is still a thing.
