### ISSUE TITLE
Binary Encryption Key and Xeno Hivemind

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#217]
The binary encryption key seems to allow one to speak and hear the xenomorph hivemind for whatever reason, I assume this isn't intentional.

**Comment by Fox-McCloud** [comment]
@TheDZD 

I suspect this is all tied in with the Xeno game mode and Xeno AI so that the AI can understand the Xenos and still utilize binary and the hivemind at the same time.

**Comment by Markolie** [comment]
Can be closed.
