### ISSUE TITLE
Malf AI law is not stated at roundstart with the rest of the laws for borgs. 

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#2170]
Before, it would be like
0: you is malf bro
1. Don't harm people, etc

It doesn't list the law 0 anymore, you have to manually check laws to see it.

**Comment by Markolie** [comment]
Not a bug - mechanic that changes the AI laws and announces it to them has not changed in over a year. The borgs never got a separate notification.
