### ISSUE TITLE
Tesla zaps through walls

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#21709]
**Issue Description**:

Tesla zapps through walls

**What did you expect to happen**: 

For walls to block the tesla zap

**What happened instead**:

You got zapped and you die

**Why is this bad/What are the consequences**:

Yeah, tesla not respecting walls in regards to tesla zaps is just bad news all around

**Steps to reproduce the problem**:

Stand behind a wall with a tesla on the other side

**When did the problem start happening**:

Round ID 36555 was the first round to experience it

**Extra information**:

https://github.com/ParadiseSS13/Paradise/assets/21987702/72c89d4f-eea3-4cee-b3da-c611daf9241d

**Comment by AffectedArc07** [comment]
Quoting from discord.

"Walls are made of metal."

**Comment by AffectedArc07** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/25063394/8c7820ff-5785-4dcb-af2d-8a7760b54722)

Non issue, intentional PR design
