### ISSUE TITLE
Eyeblurry is causing client stuttering

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#21719]
**Issue Description**:
The eyeblur status effect is causing client stuttering

**What did you expect to happen**: 
To get the eyeblurry effect as normal

**What happened instead**:
Get the eyeblurry effect followed by 1-2 seconds of a freeze, which can get you killed easily

**Why is this bad/What are the consequences**:
every single laser applies a 2 second stun

**Steps to reproduce the problem**:
1. Get shot at by something
2. Get the eyeblurry effect
3. Get froze

**When did the problem start happening**:
Very recent

**Extra information**:
Happening with a couple people, thought it was just me but nope

**Comment by EmeraldCandy** [comment]
I did not know it was from eyeblurry, but I can confirm i've had this exact issue where when I get hit usually my whole game freezes and it makes combat very, very difficult.
