### ISSUE TITLE
Die a Glorious Death is still an option to give to Antagonists in the Traitor Panel

### ISSUE THREAD

**Issue by MarginalOrb** [ParadiseSS13/Paradise#21723]
**Issue Description**:
When giving an antagonist objectives manually the Die option to give them Die a glorious death is still there.

**What did you expect to happen**: 
It to not be there since PR 21323 was merged.

**What happened instead**:
Twas there!

**Why is this bad/What are the consequences**:
I mean, it's not supposed to be there. But it is.

**Steps to reproduce the problem**:
Open TP on a player, add objective, "Die" is still there.

**When did the problem start happening**:
After 21323 was merged

**Extra information**:
I found this out while admin abusing someone, enjoy!

**Comment by Contrabang** [comment]
Yep, it didn't get removed from this list
https://github.com/ParadiseSS13/Paradise/blob/d68aafca0780abafba8e58571a54cae83e526e72/code/datums/mind.dm#L594-L596

**Comment by Baredolf** [comment]
Pull request #21786
