### ISSUE TITLE
Clings transforming into slimepeople / admin spawned slimes have the crit hud

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#21732]
**Issue Description**:

Clings transforming into slimepeople / admin spawned slimes have the crit hud, like the person is in crit

**What did you expect to happen**: 

normal hud

**What happened instead**:

The game fails to find a heart in them when they spawn, and as such deems they are having a heart attack from no heart, and must be in crit

**Why is this bad/What are the consequences**:

outs clings a bit / looks bad

**Steps to reproduce the problem**:

transform into a slime / spawn a slime

**When did the problem start happening**:

probably slime crit rework, I am unsure why no other species has this issue.

**Extra information**:

**Comment by Henri215** [comment]
Issue has been fixed by yourself with https://github.com/ParadiseSS13/Paradise/pull/21733.
Thanks for..reporting/fixing it :)
