### ISSUE TITLE
vampire bug

### ISSUE THREAD

**Issue by VACAXD** [ParadiseSS13/Paradise#2173]
It seems that suck blood does not work
in wiki:
How to suck blood

    Target head
    Attack with empty hand (harm intent) <------ BUG

the only thing it does is hit death, not suck blood..

**Comment by TheDZD** [comment]
Was either person wearing a mask or a helmet that obscures their face?

**Comment by VACAXD** [comment]
No

**Comment by Fox-McCloud** [comment]
I've received no further reports of this and there's been a fairrrr share of Vamp rounds.
