### ISSUE TITLE
Tape Recorder no longer able to be unscrewed.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2174]
This makes me a sad boy.

I can no longer make these recorders play an infinite chorus of honks, set to a timer that repeats.

**Comment by tigercat2000** [comment]
Not a bug, tape recorder wires were removed because of a BSOD issue.

**Comment by Fox-McCloud** [comment]
Yup; there was a specific instances where you could crash the server using several of these and stringining them together properly with them hearing+recording+playing back each other all at the same time.

**Comment by fludd12** [comment]
But... How else will I make a health assembly that activates an automated tape recorder on repeat playing a message when I am dead?

**Comment by Markolie** [comment]
Through the power of love and friendship!

**Comment by tigercat2000** [comment]
okay to be fair nuking the wires was a pretty
nuclear option
...
pun not intended
This could probably be fixed with making sure hear_say doesn't take input from other recorders
