### ISSUE TITLE
Umbrae Shadow Anchor can lead to negative blood.

### ISSUE THREAD

**Issue by DahkGrel** [ParadiseSS13/Paradise#21747]
**Issue Description**: 
Using shadow anchor as an umbrae, and then having less blood than the cost of the spell, will lead to negative blood. This disables all vampire abilities, even the free zero cost ones like glare and blood flush. 

**What did you expect to happen**: 
I expected blood to reach zero then stop, allowing me to use free vamp abilities like glare and blood flush.

**What happened instead**:
Blood reached a negative number, disabling all vampire abilities. Including the free ones.

**Why is this bad/What are the consequences**:
This prevents the vampire from doing their most basic abilities, effectively making them some dork with fangs and nothing else.

**Steps to reproduce the problem**:
Place shadow anchor. Use abilities that reduce blood to a lower value or be fed holy water. When the shadow anchor time is up, it will teleport and force the vampire to spend the shadow anchor cost again, going into a negative number if it can't be afforded and disabling all vampire abilities. 

**When did the problem start happening**:
July 7, 2023. I believe there is a testmerge for umbrae at this time, but I can't find the PR.

**Extra information**:

**Comment by matttheficus** [comment]
PR is: #21578
