### ISSUE TITLE
Fulton packs are not returned to modsuits when used.

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#21745]
**Issue Description**:
When fultons are used, they drop the item in the user's hand, except for the fulton pack itself, if there are any left, which it puts in the available back storage space. When the mining modsuit is used, the rest of the fulton pack isn't returned to the modsuit's storage, resulting in the rest of the fulton pack stranded at its user's original location.

**What did you expect to happen**: 
Fulton pack should be put in the user's back storage when available.

**What happened instead**:
Fulton is left stranded at its user's original location.

**Why is this bad/What are the consequences**:
Players should be able to use the fulton pack in its entirety without having to scramble back to the planet to retrieve them.

**Steps to reproduce the problem**:
1. Spawn mining modsuit, deploy and activate.
2. Place a fulton beacon on-station.
3. Jump to Lavaland, spawn a fulton pack, and set its destination to the beacon.
4. Remove any other item from your hands and activate the

**When did the problem start happening**:
Most likely an issue with the initial modsuit implementation.

**Comment by Contrabang** [comment]
Fixed in modsuit TM
