### ISSUE TITLE
Contractor portal return breaks modsuits

### ISSUE THREAD

**Issue by EmeraldCandy** [ParadiseSS13/Paradise#21740]
**Issue Description**:
when being returned by a contractor portal, it will rip apart the modsuit parts and drop them onto the ground. When picks up and "dropped" it returns them to the suit it seems. It also appeared to put all of my items into a bag called "modsuit storage" that was its own independent item. As CE I threw the bag down the hall, and accessed the normal modsuit control pack. This caused the bag to disappear and opened the backpack as normal

**What did you expect to happen**: 
for modsuits not to be ripped apart

**What happened instead**:
a very broken modsuit, a pile of implants, and broken legs

**Why is this bad/What are the consequences**:
broken modsuits are very bad

**Steps to reproduce the problem**:

- have an active modsuit
- be thrown into a contractor portal
- wait timer out and return to the station

**When did the problem start happening**:
unknown, noticed on round 36587

**Comment by Contrabang** [comment]
Fixed in modsuit TM
