### ISSUE TITLE
Only one pimpin' ride spawns at cyberiad in the new janitorial office instead of the 2 like supposed to

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#21768]
**Issue Description**:

Only one pimpin' ride spawns at cyberiad in the new janitorial office instead of the 2 like supposed to

**What did you expect to happen**: 

There should be 2 pimpin' rides. There even are two keys that spawn now since the new jani office. 

**What happened instead**:

Only 1 pussywagon spawned

**Why is this bad/What are the consequences**:

One janitor still is condemned to walking all of the place. 

**Steps to reproduce the problem**:

Be roundstart janitor, look around in janitorial closet

**When did the problem start happening**:

Since we moved to the new location

**Extra information**:

**Comment by Contrabang** [comment]
From what I know, the second cart was removed on purpose, but it seems like the second key was still left behind

**Comment by Landerlow** [comment]
Why was it removed? I know the station is small but honestly if you have two janitor slots, at least give 'em both a pussywagon. It has always been a bit of a gripe for me that one of the janitors always has to be a celibate.
