### ISSUE TITLE
Drones health goes negative

### ISSUE THREAD

**Issue by Baredolf** [ParadiseSS13/Paradise#21796]
**Issue Description**:

Maintenance drones and possibly other synthetic life have effectively 200% health

**What did you expect to happen**: 
To die upon reaching 0% health

**What happened instead**:
my health continued to go negative, untill it hit -100%

**Why is this bad/What are the consequences**:
If someone was attempting to kill the drone, it would be twice as hard.

**Steps to reproduce the problem**:
take damage resulting in less of health, at low health hit yourself with a welder, boom -20 health

**When did the problem start happening**:
As far as I am aware, its a recent issue

**Extra information**:
Was burned by a pyro anomaly down to 20% health, accidentally hit myself with welder and went down to -20% repeatedly hit myself for testing purposes and made it down to -100% before i turned into robotic remains
![hmmmmm immortal drone](https://github.com/ParadiseSS13/Paradise/assets/12814132/b921617f-bff2-4298-a660-d8699814a47d)

**Comment by Baredolf** [comment]
can confirm, applies to borgo aswell

**Comment by Contrabang** [comment]
Before our current crit system, people would go unconscious at 0 health, and then die when at -100 health. The unconscious part doesn't apply to silicons, but its still intended for them to die at -100 health. Thanks for this report!
