### ISSUE TITLE
A ghost hardsuit stays behind if it gets stripped while unconscious

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#21823]
**Issue Description**:
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/eb357bdb-b1dd-4386-904e-ce686d1370a9)
If someone strips your hardsuit while you're unconscious/dead, it lookss like there is something in your exosuit slot.

**What did you expect to happen**: 
To not have a phantom hardsuit equipped

**What happened instead**:
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/a24babc1-beac-47f2-bd09-e98c6df4d7a7)

**Why is this bad/What are the consequences**:
Bug bad

**Steps to reproduce the problem**:
Wear a full paranormal RED ERT suit, die, get stripped and get revived.

**When did the problem start happening**:
Don't know, might be MODsuits TM?

**Comment by Henri215** [comment]
Related to this maybe https://github.com/ParadiseSS13/Paradise/issues/19169?

**Comment by DGamerL** [comment]
Oh yeah that seems like the same bug, want me to close this issue?

**Comment by Henri215** [comment]
> Oh yeah that seems like the same bug, want me to close this issue?

If you are sure this is a duplicate..yeah
