### ISSUE TITLE
ghosting when xeno nested removes respawnability

### ISSUE THREAD

**Issue by EmeraldCandy** [ParadiseSS13/Paradise#21826]
**Issue Description**:

When nested during a xeno infestation, a chat message comes up that you may ghost and you will keep your revivability if you do so. However, upon using the ghost VERB in the chat, I no longer had a body, an my revivability was set to "no".

**What did you expect to happen**: 

TO still be able to enter my body and respawn

**What happened instead**:

Respawnability set to "no" and could not re-enter body

**Why is this bad/What are the consequences**:

No funny antag rolls after I give up on life :(

**Steps to reproduce the problem**:

- Be grabbed by xeno and nested
- wait for message to come up saying I may ghost
- ghost
- game punishes for ghosting

**When did the problem start happening**:

with the addition of #21717, noticed on round 36679

**Extra information**:

**Comment by GDNgit** [comment]
use the alert it gives you, i specifically didn't do this to make metagaming significantly harder

**Comment by EmeraldCandy** [comment]
> use the alert it gives you, i specifically didn't do this to make metagaming significantly harder

okay, i talked with coolrune mid-round about it when I used the verb, he stated he didnt believe that was intentional and to open an issue under it, but if it isnt then thats good to know thank you
