### ISSUE TITLE
Diona can have broken bones from enchanced action rifle.

### ISSUE THREAD

**Issue by Venuska1117** [ParadiseSS13/Paradise#21851]
**Issue Description**:
During Wizard round i got shot 7 times with enchanted action rifle and got "broken ribs"

**What did you expect to happen**: 
Have only IB not broken bones

**What happened instead**:
got IB and Broken bones

**Why is this bad/What are the consequences**:
dionas dont have bones

**Steps to reproduce the problem**:
1. Be diona
2. Get shot several times in chest by wizard action rifle
3.  Get Broken Ribs... somehow...

**When did the problem start happening**:
it probably exist for long time, but i discovered it yesterday during play.

**Extra information**:
Probably other spiecies without bones can have it (didn't test it)

**Comment by Ionward** [comment]
as of #11989 diona have bones that can break

**Comment by Venuska1117** [comment]
oh i didn't know they have bones, normally i never ger broken bones (only in special cases), and surgery dont require saw to open, so i logically tought they dont have ribs.
