### ISSUE TITLE
AI Can Lose The Ability To Hear Radio Channels

### ISSUE THREAD

**Issue by Daylight2** [ParadiseSS13/Paradise#21902]
**Issue Description**:

After getting EMP-d, carded, put back in my core, and relocated, I lost the ability to hear any radio channels except binary. Hearing radio channels trough intercoms worked fine, but I could not see my own messages (and am unsure if messages I sent went trough, although security did seem to respond to some of my calls).

**What did you expect to happen**: 

To be able to use the radio to receive and send messages.

**What happened instead**:

Could not see (and possibly send) any radio messages.

**Why is this bad/What are the consequences**:

Not being able to use the radio made me almost useless as an AI.

**Steps to reproduce the problem**:

I imagine this may be difficult to reproduce, but I will try to list everything that happened:
-Got hit by an EMP grenade whilst my core was being broken into
-Got carded whilst under the effects of EMP, and presumably had all my privileges disabled whilst carded
-Got put back into my core
-Got dragged trough space to a new location
-Discovered my radio no longer works

**Extra information**:

An admin tried to fix the issue with the AI integrity restorer, as well as by rejuvenating me, but had little success. I regained the ability to see my own messages trough intercoms, but could still not see channels without the use of intercoms. This happened on round ID 36777.

**Comment by AffectedArc07** [comment]
Closing as not an issue
