### ISSUE TITLE
Holy melons not meloning (NVM please close)

### ISSUE THREAD

**Issue by TaM-tHe-JaM** [ParadiseSS13/Paradise#21906]
**Issue Description**:

**What did you expect to happen**:  Holy melon to exist
 wasnt really just disappointing

**What happened instead**: holy melon wasnt meloning
 holy melon. instead i got melon.

**Why is this bad/What are the consequences**: my disappointment was immeasurable. and the ESTEEMED_CAPTAIN had to wait an extra hour for a HEARTY and NUTRITIOUS meal.

**Steps to reproduce the problem**: go to botany with mutagen and do holy melon making things

**When did the problem start happening**: 8/3/23 2:00PM ETZ

**Extra information**: literally unplayable

**Comment by GDNgit** [comment]
they exist it's just rng to get them

**Comment by TaM-tHe-JaM** [comment]
> they exist it's just rng to get them

oh ok nevermind then sorry
