### ISSUE TITLE
[Atmos] Odd pipe behaviour

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2192]
Bent pipes when unwrenched become straight pipes. When wrenched again they remain straight pipes.

The turbine plasma gas tank has no plasma in it (or at least only 2000kpa).

Edit:

Gas filters latch onto supply pipes that are underneth floorboards instead of normal grey pipes that are laid.

Gas Turbine is unclear as to when it is turned and when it is off.

Gas Turbine plasma tank cannot be measured by atmos tech PDA.

**Comment by Markolie** [comment]
Investigating.

**Comment by Taaketa** [comment]
Update to the original.

**Comment by Markolie** [comment]
The gas turbine sprite being unclear's a feature request.

**Comment by Markolie** [comment]
Turbine plasma gas tank has 10000 kPA, so that's not an issue either. @Fox-McCloud might have to increase it though.

**Comment by Taaketa** [comment]
Strange because when I hooked it up directly the gas meter only reported 2000kpa of pressure coming from the tank.

**Comment by Markolie** [comment]
I'm not sure if it's actually 10000kPA, but it's 10000 in terms of whatever volume the code uses (which is the default for tanks).

**Comment by Markolie** [comment]
The supply pipe connecting thing really isn't a bug either - it connects to the pipe based on what was on the tile first, and in this case that's the supply pipe. Changing that would require snowflaking out pipe priorities which I'd rather not do.

The bent pipe thing is definitely a bug though.

**Comment by Markolie** [comment]
Not being able to measure toxin tanks is a bug, too.

**Comment by Fox-McCloud** [comment]
Not really sure how it's unclear if it's on or off; the console has an on and off button directly on it. If it's on, then it'll generate power--if it's off, it won't.

As for the plasma tank; it has enough to keep you going for a bit---you're going to have to learn how to operate it though; this isn't just braindead toxins where you dump as much plasma as humanly possible into the burn chamber straight away and ignite it; you're going to have to meter the gas at a rate where it burns effectively, but doesn't burn out/consume all the gas in a short order.

Also, there's a pipe that leads from atmospherics mix tank to the gas turbine for a a reason; you have near unlimited levels of plasma in that tank to toy with with the turbine if you so desire.

2000 kPa of plasma in a tank that has a volume of of 10,000 is...a LOT of plasma.
