### ISSUE TITLE
Resist does not work against stripping anymore

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#2196]
Unless it's intended. But even if it is intended, you should AT LEAST remove the "XXX resists!" message that clutters the chat and does nothing.

1. Try to take someone's item off the body.
2. Resist as the other person.
3. Have resist do nothing against stripping.

In the very least you could make it so that stripping would take more time when you resist. Now you ALWAYS have to move away to cancel the stripping.

**Comment by Fox-McCloud** [comment]
Resist really isn't supposed to prevent someone from taking objects/clothing off or putting something on--that said, the message shouldn't be displaying either.

**Comment by tigercat2000** [comment]
Actually this is definately not intended, unless someone touched the resist system while I wasn't paying attention.

**Comment by Markolie** [comment]
Not sure if this is really worth fixing. Our inventory stripping system is one of the worst pieces of oldcode currently in existence, so this is probably best handled in an overhaul.

**Comment by Davdichan** [comment]
Oh hey, tg has a functional inventory stripping system that even organizes items according to what would effect them (belts, pockets and ID slot items are under jumpsuits and offset slighty, showing that removing the jumpsuit will remove all of these items too)

It also properly hides and prevents a person from stripping you through impermiable items like biosuits and hardsuits (no more ripping a guy's jumpsuit off through his hardsuit, or removing a sechud from a dead officer without taking off his riot helmet first.)

**Comment by Plotron** [comment]
So, in summary:
1. According to tigercat2000, it's not intended. (check one of my earlier threads: http://nanotrasen.se/forum/viewtopic.php?f=48&t=4750 )
2. This code needs replacement and not fixing.
3. TG has a working system.
4. Usually we port things from TG.
Therefore:
5. The next logical step would be to port the TG system one day.

**Comment by KasparoVy** [comment]
@Davdichan
Sounds almost too good to be true o_O

**Comment by Alex6511** [comment]
@Plotron Just get that PR up for step 5 and we'll merge is ASAP bud.
