### ISSUE TITLE
Loosing one hand with anti-drops will drop stuff in both hands.

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#21975]
**Issue Description**:

Loosing a single hand while holding something with the NODROP flag, will drop what you're holding in both hands.

**What did you expect to happen**: 

To not drop what im holding in my right hand after my left hand gets cut off. 

**What happened instead**:

Dropped what i was holding in my right hand after loosing my right.

**Why is this bad/What are the consequences**:

Dropping stuff while the NODROP flag is active and you did not loose the hand you're holding it in, is not intended. 

**Steps to reproduce the problem**:

1. grab a item that has the NODROP flag
2. cut your off empty hand off, from another body
3. watch as the nodrop flagged item, intact, drops.

**When did the problem start happening**:

Unsure, i do remember it working at some point, just not sure how long ago.

**Extra information**:

heres a funny little gif to show whats happening
![dreamseeker_z59kp82fhd](https://github.com/ParadiseSS13/Paradise/assets/96908085/c56f6504-32c1-4b98-a9d8-4474186db857)

**Comment by Burzah** [comment]
Okay. I tested this today and can confirm that items with the NODROP flag do drop from the opposite hand when the other is removed during surgery. Testing this further the behavior also occurs with regular items held in a hand while the opposite hand was removed.
