### ISSUE TITLE
Some station pets bleeding wrong-color blood

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#21976]
**Issue Description**:
Witnessed with both Ian and Paperwork, pets that are killed bloodily leave uncolored blood stains when dragged.

**What did you expect to happen**: 
Correct blood colors. Also they don't appear to be the same icon state either.

**What happened instead**:
White/uncolored blood from mammals.

**Why is this bad/What are the consequences**:
Some kind of regression, visually annoying.

**Steps to reproduce the problem**:
Unsure. Happened once when a sentient forklift killed Ian and dragged them about, and once when a cryo anomaly killed Paperwork.

**When did the problem start happening**:
Dunno, first noticed it 36913 or 36914, and again in 36915.

**Extra information**:
![2023_08_13__00_58_06__Paradise Station 13](https://github.com/ParadiseSS13/Paradise/assets/59303604/4a64a4db-a86c-41ca-b9b3-ec65dbda959b)
![2023_08_12__19_32_47__Paradise Station 13](https://github.com/ParadiseSS13/Paradise/assets/59303604/f524d7da-c2e2-4634-84bb-b67b22f7ec32)

**Comment by Henri215** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/21984.
