### ISSUE TITLE
Gibonite Delimbing bypass

### ISSUE THREAD

**Issue by YoureNotTheSharpest** [ParadiseSS13/Paradise#21986]
**Issue Description**:
Gibonite delimbs IPCs while inside of ripleys

**What did you expect to happen**: 
The riply to tank the gibonite explosion like a man

**What happened instead**:
I had my arm delimbed without taking ANY damage.

**Why is this bad/What are the consequences**:
I do not see how gibonite would even delimb without dealing any damage, nor was it expected to delimb.

**Steps to reproduce the problem**:
>be IPC (I doubt it works on other races but have not tried it)
>get a Firefighter (probably could be any mech?)
>mine into gibonite with Firefighter
>sit about 3-5 tiles away
>get boomed

**When did the problem start happening**:
N/A

**Extra information**:

**Comment by 1080pCat** [comment]
Similar issue with welding fuel tanks going off, was very funny to find my arm had been ripped off with no damage being done to me or the exo suit. 
It's not just IPCs though.

**Comment by Henri215** [comment]
As @Qwertytoforty has said over discord this is working as intended, mechs shouldnt 100% protect you from explosions, thus leading to delimbing.

If you disagree with this behaviour please feel free to make a suggestion over the forums or discord.
