### ISSUE TITLE
Passive Vents dissappear upon wrencing.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#2198]
When you wrench a Passive Vent to the floor after taking it out of the pipe dispenser it completely disappears and does not function.

**Comment by Markolie** [comment]
We don't even have passive vents in our codebase, so I'm not sure why these are even listed in the machine. Will remove it.

**Comment by GelatinousGlob** [comment]
WHAT?! NO!!! PASSIVE VENTS WHERE THE MOST IMPORTANT VENTS FOR ATMOS FUCKERY!

Bullshit they don't exist!

**Comment by Markolie** [comment]
Please watch your behaviour, I don't appreciate that kind of tone and it is completely unnecessary.

If you believe that they were in the code, I'll investigate. But as far as I could tell, they weren't there.

**Comment by Markolie** [comment]
Mhm, I see now. For some reason the only place they were referred to as passive vents was in the dispenser, otherwise they were just referred to as "vents". I'll look into re-adding it, but no guarantees.
