### ISSUE TITLE
Homemade toxins bomb assemblies detonate immediately upon activation

### ISSUE THREAD

**Issue by TORE01** [ParadiseSS13/Paradise#21993]
**Issue Description**:

You can make a homemade bomb assembly with 3 plasteel. These work like the syndicate bombs do with timers and all.
In the crafting menu you can also make a homemade toxins payload. This requires a TTV toxins bomb without any attached assembly components. This works as intended until you wrench the bomb in place and set the timer. You write in 120 seconds and it gives you 2.

**What did you expect to happen**: 

If you write in 120 seconds and the bomb explodes immediately you will most likely just bomb yourself.
**What happened instead**:

The bomb explodes immediately.

**Why is this bad/What are the consequences**:

It doesn't work as intended.

**Steps to reproduce the problem**:

This is going to be a little long.
1: Make a maxcap toxins bomb without any remote signallers or anything.
2: Make a bomb assembly with 3 plasteel.
3: In the crafting menu, make a toxins payload casing.
4: Insert the maxcap toxins bomb into the payload casing.
5: Using a wirecutter, mend all the wires on the bomb assembly.
6: Insert the payload casing into the bomb assembly.
7: Screwdriver the bomb and drag it to the place where you want to plant it.
8: Wrench the bomb in place.
9: Set the timer to 140 seconds.
10: THE BOMB HAS BEEN PLANTED.
11: The bomb explodes in 2 seconds instead giving no counter terrorists any time to diffuse.
12: Terrorists wins!

**When did the problem start happening**:

I have never tried this before and I have not seen anyone try this either so I don't know.

**Extra information**:

I just wanted to try this for future antag shenanigans. It's not a big issue because nobody ever makes bomb assemblies when grenades are more effective.

**Comment by Kaomiyo** [comment]
I've tried reproducing this for a few days now, but haven't been successful with every detonation going off at the correct time set. Have you been able to reproduce this? Also opening the floor to anyone else who has run into this issue or has been able to reproduce it.

**Comment by TORE01** [comment]
> I've tried reproducing this for a few days now, but haven't been successful with every detonation going off at the correct time set. Have you been able to reproduce this? Also opening the floor to anyone else who has run into this issue or has been able to reproduce it.

Hey. 
I tried it once and it blew up immediately nearly killing me in the process. On my attempt I accidentally added a remote signaller to my toxins bomb that I had to remove afterwards and I set it to 140 seconds. I will try to reproduce it but I am abroad atm for work and returning on friday.

**Comment by TORE01** [comment]
It's been a long while. I tried to reproduce this back when I reported this but I couldn't. Closing this for now.
