### ISSUE TITLE
Custom Synthetics

### ISSUE THREAD

**Issue by Ultimate-Chimera** [ParadiseSS13/Paradise#220]
Rename The Ultimate Chimera-AlienAI to theultimatechimera-ai and put theultimatechimera:C.O.R.G.I in custom sprites in the config folder. Necaladun did it wrong. It will not allow C.O.R.G.I to switch to other sprites. You also must copy over the crash sprite to custom-synthetics and name it theultimatechimera-is-crash, otherwise the sprite would be invisible when the AI is dead.

**Comment by Markolie** [comment]
I've let Neca know.

**Comment by Ultimate-Chimera** [comment]
Thank you.

**Comment by Markolie** [comment]
Is this still an issue? Also, silly tag issue.

**Comment by Ultimate-Chimera** [comment]
Yes, it's just an easy renaming in the .DMI to be honest, not sure why nobody understands how to do it.

**Comment by Markolie** [comment]
Will have a look tomorrow.

**Comment by Markolie** [comment]
What DMI are you talking about, exactly? I can't find any trace of your icons in the AI file.

**Comment by Ultimate-Chimera** [comment]
custom-synthetics.dmi in the icons/mob folder.

**Comment by Markolie** [comment]
Allright, and where do I find the crash icon state and CORGI files you mentioned?

**Comment by Ultimate-Chimera** [comment]
Default sprite is fine, unless if you want to get it from /tg/ but it doesn't really "fit" and CORGI is just the name you would put in custom sprites in the config folder...

**Comment by Markolie** [comment]
Allright. https://github.com/ParadiseSS13/Paradise/pull/307 fixes the sprite names. I'll ask someone with server access  to change the custom item settings.

**Comment by ZomgPonies** [comment]
Done.
