### ISSUE TITLE
Surgery with species with skip "bone cutting" make you unable to repair bones during organ manipulation.

### ISSUE THREAD

**Issue by Venuska1117** [ParadiseSS13/Paradise#22000]
**Issue Description**:
It happend to me when operated diona, diona got broken bones and IB, i started organ manipulation surgery (with dont require you to cut "bones" to open) when i fixed IB and was going for bones, it said "there is nothing to fix!" so i was forced to stop this surgery and start fresh one for bone repair.

**What did you expect to happen**: 
To fix "bones"

**What happened instead**:
unable to fix bones...

**Why is this bad/What are the consequences**:
make you confused, broken bones cant be repaired, maybe if you do surgery specific for it.

**Steps to reproduce the problem**:
1. Get diona with broken ribs
2. start "organ manipulation on chest
3.  do (scalpel -> hemo -> retractor) 
4. try use bone gel (with start bone repairing part)
5. get feedback "there is nothing to fix!"

**When did the problem start happening**:
When they give diona breakable "bones" - #11989 
And new surgery rework got created, allowing fix IB/bone fix during organ manipulation surgery - #18325

**Extra information**:
there can be that, you cannot fix bones because its part of "organ manipulation" but because diona skip "bones cutting" and "bones  mending", they just left with broken bones.

**Comment by Spaghetti-bit** [comment]
This was fixed around March, can’t find the PR that fixed it but this is no longer an issue.
