### ISSUE TITLE
Missing Embeded Objects

### ISSUE THREAD

**Issue by kincaidrenard** [ParadiseSS13/Paradise#22009]
**Issue Description**:
Embeded objects disappear, but still leave the icon in the top right.

**What did you expect to happen**: 
Expected a embed object to exist

**What happened instead**:
Embed object didn't exist

**Why is this bad/What are the consequences**:
Left a embed icon in the top right that had no reason to be there

**Steps to reproduce the problem**:
Not sure if it can be reproduced, there was a gravitational anomaly, and myself and at least one other had embed objects. We walked to medbay to get them taken out but medics said there was nothing there. Didn't show up in scans and there was no embed removal surgery option.

**When did the problem start happening**:

**Extra information**:
Removing the limb and reattaching the limb made the icon go away.

**Comment by Henri215** [comment]
Could not replicate, anything else you reemmber?

**Comment by kincaidrenard** [comment]
Uhh, my embed object was a broke glass in my left leg. The vox had a rod stuck, idk where though.

**Comment by Armyguy** [comment]
One way to try and test this, is the powered crossbow. As me getting shot by it triggered this bug for me
