### ISSUE TITLE
Virologist no longer has vials. 

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#2201]

**Comment by tigercat2000** [comment]
faaaaaaaaaawkkkkkkssssssssssss @Fox-McCloud

**Comment by Markolie** [comment]
I'll fix this actually, as I modified the grilles in virology anyway.

**Comment by Fox-McCloud** [comment]
Whoops; I forgot the locked vialbox doesn't have vials in it by default...
