### ISSUE TITLE
Not-slimepeople can *pop and *bubble

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#22014]
**Issue Description**:

Non-slimepeople can pop and bubble
**What did you expect to happen**: 

Not to be able to do that as non-slimeperson. 

**What happened instead**:

I made weird noises. 

**Why is this bad/What are the consequences**:

Immersion ruined. 
Then again, I can get behind *pop .. just making a sound like that. But .. not bubble.

**Steps to reproduce the problem**:

Be not-slimeperson.

Use *pop, *bubble

**When did the problem start happening**:

**Extra information**:

**Comment by Henri215** [comment]
The original PR forgot to include either the 
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/3970e7d4-e704-4f1b-ac47-99f6417c4aa0)

Or the
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/d75ee39f-fc8f-4625-ae72-d737e07ae0f5)

For slimes.
