### ISSUE TITLE
Combo counter appears when you're drunk

### ISSUE THREAD

**Issue by kano-dot** [ParadiseSS13/Paradise#22015]
**Issue Description**:

As long as you have drunk status effect, you're able to see the actions you made in combo counter if you don't know any martial arts. This doesn't apply to martial art users.

**What did you expect to happen**: 

To not be able to see my magnificent combos without spending any effort on martial arts.

**What happened instead**:

![mostcombo](https://github.com/ParadiseSS13/Paradise/assets/89972582/62ebbce3-4d64-4576-8c34-693531d4531e)

**Why is this bad/What are the consequences**:

It's an oversight i guess?

**Steps to reproduce the problem**:

drink and wait for drunk status effect to appear, then demonstrate your combo

**Comment by Contrabang** [comment]
Drunken brawling is technically a martial art but... it probably shouldn't show for drunken brawling
