### ISSUE TITLE
Farragus Unshielded Maint tile

### ISSUE THREAD

**Issue by DahkGrel** [ParadiseSS13/Paradise#22025]
**Issue Description**:

Hydroponics Maint tile is unshielded from radiation when it should be shielded

**What did you expect to happen**: 
To be shielded 

**What happened instead**:
Not shielded

**Why is this bad/What are the consequences**:
Radiation bad

**Steps to reproduce the problem**:
Force rad storm event, go to tile

**When did the problem start happening**:

**Extra information**:

![image](https://github.com/ParadiseSS13/Paradise/assets/73263015/d2746f77-b1e7-4492-ad05-d042d1eb37b1)

**Comment by DahkGrel** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/73263015/af573ba7-2ab5-4a61-9680-1371153981de)
Ghost view for ease of reference

**Comment by DGamerL** [comment]
As I've explained on discord, this sadly is an annoying outcome of how APCs in maints work. Could most likely just be labelled not a bug
