### ISSUE TITLE
Bogus runtime in the maploader bricked the statuin

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#22035]
**Issue Description**:
See title

`[2023-08-20T17:30:03] Runtime in code/modules/awaymissions/maploader/reader.dm,263: Oh no, I thought this was an area!`

This occurred on 2023-08-20 during 37017, and I cannot repro it locally, which makes me almost want to blame bit flips.

**What did you expect to happen**: 
The station to load

**What happened instead**:
This
![image](https://github.com/ParadiseSS13/Paradise/assets/25063394/a61ed7bd-bf6a-4ad3-a40f-fab3b3ef2ed1)

**Why is this bad/What are the consequences**:
HALF THE BLOODY MAP AINT HERE

**Steps to reproduce the problem**:
No idea

**When did the problem start happening**:
This one time

**Extra information**:
I play the game for ONE day and this happens.

**Comment by ATP-Engineer** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/120416457/200ecb93-c5bf-45a5-9caa-01d7c043b218)

**Comment by silverplatedelta** [comment]
If my memory was right, AA elected to blame bitflips and move on with life.
