### ISSUE TITLE
Modsuits that start with a 'pinned' module can duplacate the action button

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#22079]
**Issue Description**:

You're able to get more than one action button for turning modules on, on some modsuits if they have the icon pre-pinned

**What did you expect to happen**: 

To not have multiple UI buttons that do the exact same thing. 

**What happened instead**:

Had 6 jetpack icons on my CE modsuit

**Why is this bad/What are the consequences**:

UI clutter is bad. Not to mention the buttons all do the exact same thing

**Steps to reproduce the problem**:

Using the jetpack module as an example as its the most used pre-pinned module
1. Put on the modsuit
2. Unpin the jetpack module, then repin
3. Take off, and drop the modsuit
4. Pick up, and put on the suit. Now you have two jetpack icons.
5. Unpin and repin to temporarily fix the issue, to find out it only makes it worse as you've now made three icons next time you drop the suit. 

**When did the problem start happening**:

when #21147 was merged

**Comment by lewcc** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/24420.
