### ISSUE TITLE
Cyborgs do not have instant bolt/shock during malfunctioning AI

### ISSUE THREAD

**Issue by Fordoxia** [ParadiseSS13/Paradise#22086]
**Issue Description**:
Under normal circumstances, cyborgs and the AI have a 3 second timer applied when attempting to bolt or shock a door. If the AI is malfunctioning, this timer is supposed to be removed. This did not occur.

Cyborg synced to a malfunctioning AI still had 3 second bolt and shock timers.

**What did you expect to happen**: 
I was unaware this was a bug until after the fact, but it is apparently unintended behaviour.

**What happened instead**:
No timer removal happened.

**Why is this bad/What are the consequences**:
This behaviour is not an intentional feature, it creates additional difficulty for the cyborgs.

**Steps to reproduce the problem**:
Being a cyborg during a malfunctioning AI round. I was specifically one of the two round-start cyborgs.

**When did the problem start happening**:
This behaviour was present from the start to the end of the round.

**Extra information**:
Because I was unaware that this was unintentional behaviour, I did not check with any of the other cyborg players or the AI to see if they were also experiencing this issue, or if it was isolated to myself.

**Comment by 1080pCat** [comment]
should be fixed by #22084

**Comment by Contrabang** [comment]
Fixed with #22084

**Comment by matttheficus** [comment]
Note: you are still required to emag a borg via the console to get the timer removed as a Malf AI. You do not have this by default.
