### ISSUE TITLE
Delta has duplicated APCs and mismatched areas

### ISSUE THREAD

**Issue by Git-GoR** [ParadiseSS13/Paradise#22081]
**Issue Description**:
Logging here to fix after mapping freeze.
Central Primary Hallway area has two APCs
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/1173d9fe-d6b7-4c76-8ec9-bc45c1d2e106)

Same with Fore Primary Hallway
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/1b54f75f-38cf-432c-90ff-d2cbd30f3357)

Both Experimentor lab and Scichem use `area/toxins/explab`, each with their own APC. Same thing happens with their test chambers, which use `area/toxins/test_chamber`
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/0fe44932-d680-4034-8c4b-3d35981d01e5)

Extra: these lockers in front of the Vault have no station area defined.
![imagen](https://github.com/ParadiseSS13/Paradise/assets/58085266/0cb8500f-1abc-4587-93f8-dcb0ab26858d)

**What did you expect to happen**:
For each area to have only one APC. The first two can be solved by removing one of the APCs. Second one in particular can be solved by splitting the area into smaller ones, using `area/hallway/primary/central/x` subtypes that share the area name. Why do they share their name? No idea.
Third one would have to be solved by giving the EXPERIMENTOR itself the `area/toxins/explab_chamber` and scichem the `/area/toxins/misc_lab`.

**Extra information**:
#21681 will mess with station areas GREATLY, probably wait until merge. Could be that some issues are resolved by it.

**Comment by DGamerL** [comment]
Who the fuck mapped these areas and why am I horrified
