### ISSUE TITLE
Farragus Kitchen APC randomly becomes nonfunctional

### ISSUE THREAD

**Issue by Fordoxia** [ParadiseSS13/Paradise#22099]
**Issue Description**:
The APC of the Farragus kitchen will seemingly with no reason fail to deliver power to the kitchen. This occurs even if the wire to the APC is powered, and can also occur even when all settings are turned from "AUTO" to "ON".

**What did you expect to happen**: 
The APC to function normally.

**What happened instead**:
The APC didn't work.

**Why is this bad/What are the consequences**:
The kitchen has no power.

**Steps to reproduce the problem**:
Random occurrence on the Farragus map, no specific steps to replicate.

**When did the problem start happening**:
Between 30 and 60 minutes into a round.

**Extra information**:
Two separate issues arose: 

The APC would fail to deliver power unless forced to "ON" even at 100% charge with external power.

All electrical devices in the kitchen became disconnected from the APC, displaying 0W power on Equipment, Lighting, and Environment even at full charge and with external power.

**Comment by Contrabang** [comment]
Thank you for the report! This is technically a duplicate, but it is the superior version of #21253, so the other issue will be closed.
