### ISSUE TITLE
Sliding Puzzle Chest Rewards Empty.

### ISSUE THREAD

**Issue by Banderblitz** [ParadiseSS13/Paradise#22115]
**Issue Description**:
Lavaland sliding puzzles when complete spawn a necropolis chest, however the necropolis chest is empty.

**What did you expect to happen**: 
I expected to receive a lavaland chest with at least 'something' in it relevant to the chest that spawned.

**What happened instead**:
As above, a necropolis chest spawned, however it was empty.

**Why is this bad/What are the consequences**:
While less lavaland loot is not necessarily a 'bad' thing, having a ruin spawn that encourages you to solve a puzzle for the sake of nothing is just bloat, when ever rewarded people will not solve it most of the time.

**Steps to reproduce the problem**:
Go to lavalands, find a sliding puzzle, complete it, be rewarded with a headache and an empty chest.

**When did the problem start happening**:
As of 8/25/2023 it happened, likely began when PR#21930 was merged.

**Comment by Contrabang** [comment]
Posting the link to line it to the original PR #21930, thanks for the report!
