### ISSUE TITLE
Camera bug from syndicate uplink

### ISSUE THREAD

**Issue by Kryoclast** [ParadiseSS13/Paradise#22146]
**Issue Description**:
Camera bug from the syndicate uplink isn't working

**What did you expect to happen**: 
Expected the camera bug to work when 
 - using it in hand
 - or ctrl+click 
 - or alt + click

**What happened instead**:
Nothing happened

**Why is this bad/What are the consequences**:
Feature anomaly, loss of TC.

**Steps to reproduce the problem**:
 Purchase a camera bug from the traitor uplink, attempt to use it

**When did the problem start happening**:
First noticed a week ago

**Extra information**:
I have purchased 2 camera bugs in the same round, the first one was working, the second camera bug wasn't working. It's hard to tell what causes the anomaly

**Comment by Burzah** [comment]
At this time, there is no 'ctrl + click' or 'alt + click' action exists for the camera bug to begin with. I was also not able to reproduce the issue in testing either. Can you provide more information from when this incident occurred?

**Comment by 1080pCat** [comment]
I've had the same issue, was very frustrating.
I couldn't figure out what the issue was with it, even after finding a second one, both didn't work. 
If i remember correctly, me giving it to others and asking if it worked got a all-round *no*  


Perhaps its an issue with multible cambugs (kits) existing? just a thought.

**Comment by Burzah** [comment]
> Perhaps its an issue with multiple cambugs (kits) existing?

I did try testing it like this, but was not able to reproduce the same issue, but since multiple people are now saying that this has happened. I will change the labels to reflect that. Any additional information in rounds where this occurs is appreciated.

**Comment by pismorizzo** [comment]
No idea if this is related but the camera bug that spawns from a space ruin has a weird quirk where is if the APC in the ruin stops giving power to equipment the same thing as described happens to the camera bug and it stops working until power is restored to that specific APC. Again no idea if related but its a lead.
