### ISSUE TITLE
FLAMETHROWER ADD_LOGS IS BACKWARDS

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2214]
I AM DONE
I AM DONE FUCKING FIXING BACKWARDS ADD_LOGS
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/flamethrower.dm#L69

@Markolie WHYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
https://github.com/ParadiseSS13/Paradise/blob/master/code/__HELPERS/mobs.dm#L152

**Comment by Markolie** [comment]
Why the hell is it reverse anyway, having user as the mob makes way more sense.
