### ISSUE TITLE
Pepperspray sprite bug

### ISSUE THREAD

**Issue by kincaidrenard** [ParadiseSS13/Paradise#22157]
**Issue Description**:
When holding pepperspray, it is always 'seen' in the left hand of the character sprite. Even if it's physically in the right hand slot.

**What did you expect to happen**: 
not that

**What happened instead**:
sprite can be seen holding pepperspray and a batong, pretty silly

**Why is this bad/What are the consequences**:
Being able to correctly identify things in peoples hands is pretty important

**Steps to reproduce the problem**:
hold spray in right hand

**When did the problem start happening**:

**Extra information**:
oh yeah this is on the test server, cause normie server is down

**Comment by Burzah** [comment]
Tested this and confirmed that no matter what hand you hold the pepper spray in, the sprite stays in the left hand.
