### ISSUE TITLE
MODSuits missing "ARE YOU SURE?" prompt 

### ISSUE THREAD

**Issue by Screampuff** [ParadiseSS13/Paradise#22161]
**Issue Description**:

MODSuits on /tg/ give a popup on the action bar that state "ARE YOU SURE?" to confirm selection before deploying.  There is no such popup on the action bar here, forcing players to double click and assuming the button just doesn't work properly.  The actual popup exists in code somewhere clearly as forcing an action bar refresh by picking up an O2 tank or another item that has an action bar makes it show up, but then it gets stuck on the icon forever until another action bar refresh.

**What did you expect to happen**: 

"ARE YOU SURE?" should be shown to the player when they initially left click on the deploy or power buttons.
![2023-08-29_11-15-46](https://github.com/ParadiseSS13/Paradise/assets/5251535/9c3f8a84-cc4e-4f97-a93b-b6956c0d3063)

**What happened instead**:

Nothing.

**Why is this bad/What are the consequences**:

No feedback for why MODSuits "aren't working unless you spam/double click" is bad.

**Steps to reproduce the problem**:

Left clicked on deploy/power, nothing happened until I did it again.

**When did the problem start happening**:

Since testmerge.

**Extra information**:

**Comment by Stealthii** [comment]
It seems some `ButtonUpdateIcon()` calls were missed from https://github.com/tgstation/tgstation/pull/63836.

I've raised #22162 to address this.
