### ISSUE TITLE
Grammar issue with the Merchandise Vendor description

### ISSUE THREAD

**Issue by Henri215** [ParadiseSS13/Paradise#22181]
**Issue Description**:

The Nanotrasen Merchandise Vendor (```code/game/machinery/merch_vendor.dm```) has a missing dot at the end of its description and the word ```Swag``` is capitalized.
![image](https://github.com/ParadiseSS13/Paradise/assets/77684085/ae2fb234-37d1-468b-b2ff-afdec2e21fd4)

**What did you expect to happen**: 

For there to be no grammar issues with it.

**What happened instead**:

The world is in chaos

**Why is this bad/What are the consequences**:

Bad grammar is bad

**Steps to reproduce the problem**:

Go to a merchandise vendor and examine it

**When did the problem start happening**:

Since it was added

**Extra information**:

Free GBP

**Comment by aditya-garg-09-01-2002** [comment]
Looks like something easy to do, I just started with open-source contributions.
Can I take it up and how do I correct it, first fork, then update and then send a pull request?

**Comment by aditya-garg-09-01-2002** [comment]
Or do I rectify the issue as told and create a new branch for pull request @Henri215

**Comment by Henri215** [comment]
@aditya-garg-09-01-2002 Go over the coding_chat discord channel, we can help you there

**Comment by aditya-garg-09-01-2002** [comment]
ok thanks @Henri215

**Comment by aditya-garg-09-01-2002** [comment]
I have created pull request, Hope it is as it should be.
Thanks for supporting @Henri215
