### ISSUE TITLE
SM S-Class events dont do much of anything.

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#22192]
**Issue Description**:

The S-class event didn't do much of anything, dead ass maybe a 300 EER spike, but that was _it_

**What did you expect to happen**: 

To have a fun time baby sitting a engine over 6k EER, and all the issues that come around with such a event

**What happened instead**:

Maybe a 300 EER spike, even that im unsure if was just from it lowering, or me trying to poke it to happen with a emitter. 

**Why is this bad/What are the consequences**:

Its not what was intended by Silvers original PR, as noted in the PR. 

**Steps to reproduce the problem**:

Setup the engine, wait for s-class event, or force it? not sure if you're able to.
Sit back and be calm while the engine does nothing.

**When did the problem start happening**:

gonna guess maybe  #22074, but i couldn't tell ya, first i've seen the event happen.. or not happen in this case.

**Comment by Groudonmaster** [comment]
Until the job title changes get pushed I'd prefer it stays this way. There's nobody just detected to the crystal right now and signing up to do fun engineering stuff and getting relegated to crystal babysitting doesn't sound fun

**Comment by 1080pCat** [comment]
> There's nobody just dedicated to the crystal right now and signing up to do fun engineering stuff and getting relegated to crystal babysitting doesn't sound fun

s-class events have a 5 minute warning, i meant babysitting in the context of needing to tend to the crystal during the event.

**Comment by 1080pCat** [comment]
Just had a round that a s-class DID work, so.. im not sure why it didn't this time, i'll be closing this since it seemed to have worked?

strange
