### ISSUE TITLE
Strange things happening with Strange Reagent

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#2222]
So, I'm not entirely sure whats going on, but earlier today two people got really bugged out after medbay attempted to use Strange Reagent on them. It sounds like they had a lot of internal damage but no external damage. I wasn't able to deduce if it "worked" or "failed" but basically the bodies were on all the scanners "unconscious" despite being dead to medUI. They also were not defibable ("patient not in valid state") and could not be cloned.

I really have no fucking idea, maybe their time of death isn't being reset?

**Comment by tigercat2000** [comment]
Alex, alex why. Why. #2222

**Comment by Alex6511** [comment]
Hue.

**Comment by TheDZD** [comment]
Well, there's still #3333.

**Comment by Alex6511** [comment]
This was fully intentional by the way. Its a Alex thing.
