### ISSUE TITLE
/mob/living/simple_animal spawns with no sprite

### ISSUE THREAD

**Issue by Chicken12341** [ParadiseSS13/Paradise#2223]
I'm not sure if it's actually meant to be in the game, but upon examination it has a crystal spider-esque icon when examined, but it's actually invisible

https://i.gyazo.com/9778c9d94e4ea8cda0ae18d6a674e188.png

https://i.gyazo.com/5c13ca93de267ef7f8f8d1dcf85d09a4.png

This was spawned in somehow via Xenobio. I was only briefly in the round, but I know that there weere at least adamantine golems. Also, I noticed some 'animal' runes on the ground. Among the /mob/living/simple_animal spawns were some Faithless, bloated people/things, space bears, and those weird bug things (maybe hive bots). I believe they came from the animal runes or the Experimentor

**Comment by Spacemanspark** [comment]
It has the basilisk icon when examined?
Odd.

**Comment by Markolie** [comment]
The base path of simple_animal should never be spawned in, just like how /obj or /obj/item should never be spawned in.

If a non-admin spawned this in somehow, please update the report with the information on how that happened.

**Comment by Chicken12341** [comment]
A potential fix for this is adding /mob/living/simple_animal to the var/global/list/blocked_mobs, however I'm not sure of the side-effects. I was testing this but got sidetracked

**Comment by Spacemanspark** [comment]
Pssssst.
@Fox-McCloud 
Sentience potions can spawn them.
