### ISSUE TITLE
Toxins Disposal leading to Cargo in Cyberion

### ISSUE THREAD

**Issue by GetProactive** [ParadiseSS13/Paradise#22282]
**Issue Description**:

The disposals from toxins on the cyberion map leads to cargo.

**What did you expect to happen**: 

Those who have no idea or wish to abuse as a traitor and do have knowledge have easy access in destroying the station.

**What happened instead**:

The other maps already have a disposals that leads to the mass driver instead of another department on the station.

**Why is this bad/What are the consequences**:

It will prevent new players who have no idea being ruined because of this mistake, and others having their experience ruined due to a mishap

**Steps to reproduce the problem**:

Make a bomb and send it through the testing disposals.

**When did the problem start happening**:

On the Cyberion Map

**Extra information**:

**Comment by DGamerL** [comment]
For anyone wanting to fix this issue, the station is Deltastation/Kerberos. While there isn't a requirement for disposals to lead into the mass driver, I can understand the confusion and it is most likely preferred to have a disposals bin lead onto the mass driver here.

**Comment by 1080pCat** [comment]
> Deltastation/Kerberos.

Meta/cerebron, not delta/kerberos..
