### ISSUE TITLE
The description of the Nutriment implant in the description of the design has a typo

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#22337]
**Issue Description**:
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/799dc04d-a8c9-4c0b-a3d0-465acf1c30f5)
This implant `with` synthesize

**What did you expect to happen**: 
No typo

**What happened instead**:
Found typo :(

**Comment by Brillcrafter** [comment]
gonna be fixed very soon
