### ISSUE TITLE
Hulk Overlay is Broken

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2235]
No hulk overlay when hulk.

**Comment by Markolie** [comment]
@tigercat2000's Frankenstein update may have broken this?

**Comment by tigercat2000** [comment]
highly doubt it, hulk is handled post-organs

**Comment by Markolie** [comment]
Seems to work fine.

Please provide more accurate steps to reproduce and the conditions under which it recurred, and preferably a screenshot instead of just saying "hulk overlay is broken".
