### ISSUE TITLE
Cyborgs and AIs get assigned a bank account they cannot access

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#22364]
**Issue Description**:
The AI and Cyborgs get assigned a bank account, which they cannot access themselves.
They should probably either get one and be able to access it (My preference) or not get one at all.

**What did you expect to happen**: 
For sillicons to be able to use things like bank accounts that they are given

**What happened instead**:
They can't access it themselves

**Why is this bad/What are the consequences**:
This is an oversight.

**Comment by Fordoxia** [comment]
Note: The bank account is in the name of the base character of the AI/Cyborg (i.e. who they would be if they rolled a non-silicon job).

It should totally be accessible to the silicon in question, great RP synergy with the Corpo lawset.
