### ISSUE TITLE
Ghost Objects In Hands/Pockets

### ISSUE THREAD

**Issue by TrungoBungo** [ParadiseSS13/Paradise#22369]
Ghost Objects In Hands/Pockets

Usually when playing SS13 you are always interchanging items in your hands or pockets. Whether this is to avoid sec finding something on you, or just plain micromanaging.

What has been ending up happening to me on multiple rounds though recently is ghost items in my hands/pockets. This has caused situations for me that I cannot put something in my pocket for the game believes something is there/or I cannot hold something for the game also believes something is there. (You still see the green outline as if you were hovering the item). This ghost item has occurred specifically for the airhorn found at the beachbums lifeguard shack, and another object I cannot remember.

This is bad for it impedes gameplay quite a bit by getting rid of a players way to hide something, or to even hold something/dual wield. Which can result in unfun situations, and annoyance of trying to micromanage what to have in one pocket/one hand.

The problem with this bug, is that it's total RNG. I have no idea how to replicate it, but I must be doing something because it has at least happened thrice to me. (Second time it happened but then fixed itself? While other first and third required admin to strip me of everything.)

This has been happening since about 2~3 days? I have seen no other reports based on this. Might be just bad RNJesus

**Extra information**:
God Speed.

**Comment by DGamerL** [comment]
If it happens again, could you try making a picture of how it looks + how it looks when you right click the pocket with the ghost item?

**Comment by silverplatedelta** [comment]
Ive not seen this issue recently. If this happens again, please re open this report or open a new one with details concerning the events before this bug occur:ed!
