### ISSUE TITLE
MODsuit stamp can be placed into crates and onto tables

### ISSUE THREAD

**Issue by Coolrune206** [ParadiseSS13/Paradise#22383]
**Issue Description**:

Title.

**What did you expect to happen**: 

It should be attached to the modsuit.

**What happened instead**:

You can slap it in a crate or table and walk away. It disappears when the module is disabled.

**Why is this bad/What are the consequences**:

It's not meant to work like this.

**Steps to reproduce the problem**:

Deploy Modsuit. Deploy Stamp Module. Click table or crate. Despair.

**When did the problem start happening**:

Likely as long as Modsuits have been around.

**Extra information**:

**Comment by Henri215** [comment]
Fixed by https://github.com/ParadiseSS13/Paradise/pull/22718.
