### ISSUE TITLE
Issue with Judo belts help/harm intent noticed in round 37925

### ISSUE THREAD

**Issue by anthaily** [ParadiseSS13/Paradise#22392]
**Issue Description**:
Round ID 37295 I noticed problems with Judo which were not present in the previous round.
When using help attempt on someone with an empty hand, a help icon would appear where the combo meter normally is, but nothing would happen.
When using harm intent on someone with an empty hand, a harm icon would appear where the combo meter normally is, and no punch would happen.
I don't know what PR was merged between the previous round and this one but it broke Judo.
I wasn't able to test eye jab, but throw, discombobulate, armbar, and wheelthrow were all working correctly.

**What did you expect to happen**: 
I expected that using help intent would do a normal shake-up from a stun or resting, and that using harm intent would deliver a 10 brute damage punch.

**What happened instead**:
When I used help intent with an empty hand, a help icon appeared on the combo tracker, but nothing else happened.
When I used harm intent with an empty hand, a harm icon appeared on the combo tracker, but nothing else happened.

**Why is this bad/What are the consequences**:
The player wearing the Judo belt is unable to attack lethally or help up stunned players.

**Steps to reproduce the problem**:
I wore a Judo belt and used harm to try and punch another character.
I wore a Judo belt and used help to try and shake up another character.
I have not reproduced this on a test server or in another round because I could not figure out how to view which PRs were merged in round 37925.

**When did the problem start happening**:
This started happening from early on in Round 37925.

**Extra information**:

**Comment by HMBGERDO** [comment]
https://github.com/ParadiseSS13/Paradise/pull/22322 this caused this and ^ is fixing that issue
you cant help with CQC, Judo, cant just harm with Judo and some other issues
before the fix merged, doing some step that is not start of any combo will break you if your martial art has combos
