### ISSUE TITLE
Some grammar issue or something

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2240]
![OH NOES](https://i.gyazo.com/13c8d0941599371445ca62bc85b04334.png)
Had someone send me a message about this, it looks like something related to hardsuits.
Obviously a huge issue and should be rectified three years ago.
EDIT: I'm an idiot and linked a picture of a crab. FIXED. @Alex6511

**Comment by Finalsong** [comment]
ur breddy gud xDDDDD

**Comment by Spacemanspark** [comment]
![I failed](http://i.imgur.com/YKgwKHf.png)
Here's the picture of what I accidentally uploaded for your viewing pleasure.
