### ISSUE TITLE
Jetpacks seem to be broken.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2242]
They turn on, they emit the trails, but they don't actually seem to work (Let you move in space freely). Someone pointed this out to me in an adminhelp.

**Comment by tigercat2000** [comment]
I KNOW I TESTED THIS


i probably didn't
god fucking damnit

**Comment by Markolie** [comment]
Please tell me you didn't have your backpack in your suit storage slot, you scrub.

Can't reproduce - they seem to work fine.

**Comment by Alex6511** [comment]
I can confirm it was on the persons back. This is an issue.

**Comment by Spacemanspark** [comment]
It was on their back. I examined them at the time.

**Comment by Markolie** [comment]
Then they probably had it turned off or it was empty, as I just tested it and nuke ops seem to be able to use theirs just fine.

**Comment by Spacemanspark** [comment]
I don't think turned off/ out of fuel jet packs leave trails, though.

**Comment by Alex6511** [comment]
@Markolie I realize that we can't reproduce this, but I have twice now, seen someone with an activated jetpack, with pressure, that is unable to move while in space. This bug exists. If you want we can try to reproduce it later. I have some ideas.

**Comment by Alex6511** [comment]
After multiple attempts I can't reproduce this. If it happpens again I'll get more detailed information and make another report.
