### ISSUE TITLE
Being cloned with martial arts makes you lose access to combos

### ISSUE THREAD

**Issue by Coolrune206** [ParadiseSS13/Paradise#22429]
**Issue Description**:

As per title. Being cloned while having martial arts (tested with CQC, likely same with carp) makes you lose access to combos and importantly the combo counter.

**What did you expect to happen**: 

Cloning SHOULD keep martial arts properly.

**What happened instead**:

You keep the harm/disarm changes alongside short combos like double harm that aren't reliant on the combo counter, but anything else (and the counter itself) do not exist for you.

**Why is this bad/What are the consequences**:

You lose access to... an inconsistent amount of your martial arts if you die and get cloned.

**Steps to reproduce the problem**:

Spawn
Get CQC
Die
Get cloned
Try to combo shit
Suffer

**When did the problem start happening**:

Probably... after https://github.com/ParadiseSS13/Paradise/pull/21943, which changed the system martial arts combos used to be reliant on the counter. Might not be related though, I really don't know the last time this worked properly!

**Extra information**:

**Comment by Contrabang** [comment]
I think it may be more related to #22322 or #22394
