### ISSUE TITLE
Welding mask sprites are reversed on drask.

### ISSUE THREAD

**Issue by silverplatedelta** [ParadiseSS13/Paradise#22423]
**Issue Description**:
The sprites for the welding mask on drask are reversed, the "disabled" sprite appears when the mask is on, and vice versa.

**What did you expect to happen**: 
The sprites to appear normally

**What happened instead**:
Sprites were reversed

**Why is this bad/What are the consequences**:
Sprite inconstancy is bad.

**Steps to reproduce the problem**:
Play a drask, wear a welding mask (the kind RnD makes), enable and disable it

**When did the problem start happening**:
Unknown.

**Extra information**:

**Comment by PollardTheDragon** [comment]
Are you sure the issue is with the welding gas mask? I am unable to reproduce the issue.
![image](https://github.com/ParadiseSS13/Paradise/assets/144391971/75fca389-7003-4a61-90c8-179bc62e90b2)
![image](https://github.com/ParadiseSS13/Paradise/assets/144391971/b61cda36-c786-435a-bc7a-09ec87fb092a)

**Comment by Taurtura** [comment]
I believe this is actually a problem tied directly to the welding mask, rather than the specie, as this happened to me while playing a human or IPC multiple times. (Yes I use welding protection as an IPC player)

The mask just sometimes break and keeps it's visor state when it shouldn't.

**Comment by silverplatedelta** [comment]
Not had this issue recently. Its either spurious or fixed.
