### ISSUE TITLE
Can not use escape key to cancel cultist Mask popups

### ISSUE THREAD

**Issue by Chicken12341** [ParadiseSS13/Paradise#2243]
This isn't a bug, mainly a QoL because as Nar'Sie's Mask, managing urges and all the pop up text boxes will just set the urge as an empty line of text when you hit "ok" while the pop up is empty.

**Comment by tigercat2000** [comment]
Byond issue at best. Not even really an issue. Nothing we can do.

**Comment by Chicken12341** [comment]
It's just annoying because I accidentally spammed "You feel no supernatural compulsions" like 9 times

**Comment by CrAzYPiLoT-SS13** [comment]
Will be pointless when #4392 gets merged, might as well close it now.

**Comment by Spacemanspark** [comment]
I still wish we kept the mask.
