### ISSUE TITLE
[Disposals] New maint area disposal outlet

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2244]
Seems to be sending paper backwards instead of into space.

http://imgur.com/DDBpBZ0

**Comment by Markolie** [comment]
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
Not a clue on this one; I have a feeling it may be due to the looping nature of spess---I've watched a few things got out that chute and it goes flying off into space properly; whatever is causing it, it's certainly not all the time.

**Comment by Fox-McCloud** [comment]
pretty sure this relates to the spesscube. Haven't seen this in a while.
