### ISSUE TITLE
MODSuit charging does not generate an attack log

### ISSUE THREAD

**Issue by Coolrune206** [ParadiseSS13/Paradise#22456]
**Issue Description**:

As per title. The kick/charge module in the modsuit thingamajig does not generate an attack log to indicate that it actually happened.

**What did you expect to happen**: 

Attack log when someone does something that can cause damage to another player.

**What happened instead**:

No attack log.

**Why is this bad/What are the consequences**:

Knowing when someone is damaging someone through means such as this is quite helpful for obvious reasons.

**Steps to reproduce the problem**:

Put on a Loader Modsuit.
Use whatever module it has to launch yourself at someone.
Marvel at the lack of a log.

**When did the problem start happening**:

Since Modsuits were added.

**Extra information**:

Logging is important!

**Comment by 1080pCat** [comment]
> modsuit thingamajig

mm yes the thingamajig.. ~~(module coolrune, its a module!)~~
