### ISSUE TITLE
Floorbot is using up tiles when "removing" tile (makes no sense)

### ISSUE THREAD

**Issue by Venuska1117** [ParadiseSS13/Paradise#22478]
**Issue Description**:
Floorbot is using up tiles when removing damaged tile (it don't even replace it with plating)

**What did you expect to happen**: 
remove damaged floor and dont consume tiles for it (its just crowbar action)

**What happened instead**:
removed tile, used up tiles

**Why is this bad/What are the consequences**:
it consume tiles on action with should not use up tiles, it makes no sense.

**Steps to reproduce the problem**:
1. Make Floorbot.
2. Give it tiles.
3. Enable "repair damaged tiles and platings"
4. Look Floorbot use up tiles to remove damaged tile.

**When did the problem start happening**:
No idea when

**Extra information**:
It make no sense to use up tiles when it normally when you do it dont require tiles to do so.

**Comment by Oyu-De** [comment]
so, just a note, checked on this. You must have "Add tiles to new hull plating" turned on for it to remove/replace floor tiles. however it seems to fix actual plating.
Absolutely no idea why this broke, but checking on it.
