### ISSUE TITLE
Inability to put an object within ones hands.

### ISSUE THREAD

**Issue by JohnJuann** [ParadiseSS13/Paradise#22476]
<!--

**What is the problem?**
While dealing cards to gamble in bar i somehow triggered a bug that made it impossible to grasp things in my own hands. It was similar to the effect of having no hands without the ic explanation. 

**What did you expect to happen**: 
I was expecting to either deal another hand or shuffle a deck of cards i had been using most of the round

**What happened instead**:
My hands (Physical) were rendered useless as if they were removed.

**Why is this bad/What are the consequences**:
Consequences: inability to utilize anything in inventory, or in hand. Game breaking bug. 

**Steps to reproduce the problem**:
Experiment with the deck of cards and in the event the same thing occurs for another player make sure to rule deck of cards out or find a causation. it could be a complete dead end but might be worth looking into. 

**When did the problem start happening**:
Only my most recent round.  ID:37360

**Extra information**:
Potentially related to the deck of cards. im not a coder nor have i dealt with this issue in the past, so take what i say with a grain of salt. Probably a deeper issue within the code. Strangely enough after enough time passed i gained the function back. Adds another layer of lovely mystery.

**Comment by JohnJuann** [comment]
First time using the site, apologies for it being so bare. But ill give the run down. 

Essentially i was dealing cards in the bar when suddenly i wasnt able to grasp anything, even if it was in my inventory. 
Its never happened to me before but it miight be worth ruling out the deck of cards if you can. 

Significance? 
Game breaking

How to replicate? 
Not sure but it might be worth experimenting with the deck of cards. Its unfortunately the only thing i can think of. 

When did it happen?
Round ID# 37360

Im not a programmer or coder so take my suggestions with a grain of salt. More than likey the answer lies deeper in the code but its worth a couple experiments.

**Comment by JohnJuann** [comment]
To add to the confusion the ability came back after about 20 minutes. Hope that helps!

**Comment by Spaghetti-bit** [comment]
I’ve not been able to reproduce this in any way and will be closing the issue as I’ve not had anyone report such things happening. I played…. A lot of Unun
