### ISSUE TITLE
Engineering outpost solars not working correctly

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#2251]
Not sure why, but they seem to never generate power.

**Comment by Markolie** [comment]
They're producing power just fine. It's just very little, and whenever the sun is SW, SE, or S it won't generate powers due to the outpost being in the way.

**Comment by Alex6511** [comment]
How long does the cycle take? Because we waited close to 10 minutes and they never turned away from south east, generating no power.

**Comment by Markolie** [comment]
The sun's pretty random I believe. It doesn't matter though - there's always enough power to keep the outpost charged.

**Comment by Alex6511** [comment]
Seems the sun rotation actually just takes a lot long than I realized, it's working correctly.
