### ISSUE TITLE
Lavaland "Nest" Ruin make Resin Floor grow over lava/chasm/plasm if destroyed open.

### ISSUE THREAD

**Issue by Venuska1117** [ParadiseSS13/Paradise#22535]
**Issue Description**:
Make chasm/lava/plasma hard to spot if you are new player and don't know exact shape of ruin and "lava" it spawns.

**What did you expect to happen**: 
to not spread

**What happened instead**:
booby traps.
![image](https://github.com/ParadiseSS13/Paradise/assets/89580971/a4827779-cce2-44c9-9fed-15cf9027b3e2)

**Why is this bad/What are the consequences**:
Die to lava, kill new players.

**Steps to reproduce the problem**:
1. Get "Nest" Ruin
2. Destroy walls near "queen" nest
3. see resin floor spread over lava/chasm/plasma

**When did the problem start happening**:
Probably after Lavaland Rework #21838, i didn't see this issue before rework was made.

**Extra information**:
N/A

**Comment by Burzah** [comment]
Closing this issue as it is already listed. Thank you for the report!
https://github.com/ParadiseSS13/Paradise/issues/22535
