### ISSUE TITLE
Holding a plant doesn't properly hide you anymore

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#22551]
**Issue Description**:
When holding a plant, my character sprite suddenly appeared under the plant sprite after a few seconds

**What did you expect to happen**: 
To only show my HUD while I'm holding a plant

**What happened instead**:
![image](https://github.com/ParadiseSS13/Paradise/assets/108773801/3a4c2ea0-41fb-4c8b-820b-6efb95e40e28)

**Why is this bad/What are the consequences**:
I wanna be invisible when holding a plant, unless I'm examined or someone is using a HUD :(

**Steps to reproduce the problem**:
Grab plant
Move around
Character sprite appears

**When did the problem start happening**:
Probably since the PR that tried to fix HUDs with plants

**Comment by Ionward** [comment]
plants worked fine before with the hud changes added, i was noticing some sprites failing to refresh a couple nights ago but thought it was just a weird runtime thing, maybe there’s something fucky there

**Comment by Contrabang** [comment]
Fixed a while back
