### ISSUE TITLE
No one Deathgasps Anymore

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2258]
People are unable to deathgasp anymore; if someone dies, they just fall over without any particular emote.

**Comment by Spacemanspark** [comment]
WHAT.

**Comment by KasparoVy** [comment]
rip

**Comment by Spacemanspark** [comment]
I'll look into this in a few hours.

**Comment by Markolie** [comment]
Did you add the variable to /datum/species or the human subtype? Most races probably don't have one defined.

**Comment by Spacemanspark** [comment]
@Markolie It's in /datum/species.
Testing something really quick to see if it fixes it, hang on.

**Comment by Spacemanspark** [comment]
As an addon: I have a version of the code where this works perfectly, when you die and everything.
I downloaded and tested the current version, and it seems to be fudged, but I can't find differences in comparison...

**Comment by veganzombeh** [comment]
Not sure if it's related to this issue, but @Spacemanspark's changes to [human/emote.dm](https://github.com/ParadiseSS13/Paradise/blob/7586390436b5b20c58e8e0e56ac9856f3ba085e6/code/modules/mob/living/carbon/human/emote.dm#L339) were reverted.

**Comment by Markolie** [comment]
Looks like this is my fault.
