### ISSUE TITLE
Cargo supply orders are frozen. Can't approve nor deny the order. 

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#22590]
**Issue Description**:

Cargo orders not being able to approved nor denied. It's just 'stuck'. 

**What did you expect to happen**: 
To be able to approve or deny an order. 

**What happened instead**:\
Computer said no.

**Why is this bad/What are the consequences**:
Can't handle cargo orders.

**Steps to reproduce the problem**:
Place orders at cargo and hope you run into the issue. I'm not sure if it's a recurring issue yet but I heard from others that they had this problem too, so I assume I'm not the only one. 

**When did the problem start happening**:
Noticed it today. 

**Extra information**:
One of the orders needed approval from a certain department. I asked the HOP to either approve or deny the order if possible. They couldn't either. 

Round ID: 37443

**Comment by 1080pCat** [comment]
I've come across this twice, one of the times being caused by me, it seems like if you put a order in while your ID is in your pda, it breaks it.
That or if you start the order with the id on, then put it into your pda to move funds around, like you'd usually do as a head, that might be a cause.

**Comment by DGamerL** [comment]
Thanks laptop for adding the labels when I boot it back up, instead of when I did it yesterday

**Comment by DGamerL** [comment]
Issue is now take or give 6 months old, and nobody has encountered this issue as far as I know it.
Testing on live and on a testserver both work properly aswell.
