### ISSUE TITLE
Borg tray sticks to carbon hands.

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#2259]
If you put your tray on some unfortunate carbon lifeform's hand as a service borg, this tray is utterly unremovable without admin magic.

**Comment by Markolie** [comment]
How the hell are you giving people your tray? That shouldn't be possible.

**Comment by Rumiluntti** [comment]
The same way you would do it as a carbon. Open the menu where it list their clothes and stuff and stick that cursed thing in their hand.

**Comment by tigercat2000** [comment]
Inventory code, _of course it's inventory code_

**Comment by Spacemanspark** [comment]
Newsflash: "Spark 5.5 has disabled hundreds of working crew!
A civilian on site tells us the details.
News Reporter: 'How did this happen?'
Civilian: 'HELP THE TRAY WON'T COME OFF AHHHHHH.'
And that's all for no- wait, is that...
FUCK HE'S HERE RUN RUN OH GOD I GOT A TRAY IN MY HANDS IT WON'T COME OFF-"
