### ISSUE TITLE
All Sharp Objects Cause Surgical Intent

### ISSUE THREAD

**Issue by Aligotess13** [ParadiseSS13/Paradise#22605]
**Issue Description**:

All sharp objects, when used with help intent on a tabled humanoid, pull up a surgical menu. This includes objects not involved in any ghetto surgery, like broken bottles and spears.

**What did you expect to happen**: 

I expected only designated ghetto tools would show surgical UI.
**What happened instead**:

The UI appears to be a blanket feature of all sharp objects.

**Why is this bad/What are the consequences**:

At some point, some players may be in a scenario where they attack a tabled opponent, and because they're on help intent, they will face a surgical screen in the middle of combat with no fault of their own.

**Steps to reproduce the problem**:

I loaded up a testing server and spawned in a spear. I used the spear on a tabled humanoid.

**When did the problem start happening**:

Ever since I discovered it in 9/22/23

**Extra information**:

I think Wiki action could help somewhat. Adding a warning to not use sharp objects on help intent against tabled opponents. But I believe the code should still stay consistent, broken bottles aren't an improvised surgical tool but still have the feature.

**Comment by SteelSlayer** [comment]
While I don't think this is ideal, it is technically intended because we add the surgery initiator component to any item, based on if it's sharp or not. 

![image](https://github.com/ParadiseSS13/Paradise/assets/42044220/d0bd8876-9e65-4573-bf00-b8cbd32468e4)
