### ISSUE TITLE
Metastation Bridge Hallway controls SPACE

### ISSUE THREAD

**Issue by Cocacolagua** [ParadiseSS13/Paradise#22636]
**Issue Description**:
Metastation's bridge hallway is missing an area
![j1t8QC7JVI](https://github.com/ParadiseSS13/Paradise/assets/48032385/74800592-b318-421d-9ab8-a66d7507334e)

**What did you expect to happen**: 
For it to have an area

**What happened instead**:
![OBeUkGyH28](https://github.com/ParadiseSS13/Paradise/assets/48032385/ddc6ebb6-dfcc-424a-ae39-85a0499742e4)
![LSlQks4sVB](https://github.com/ParadiseSS13/Paradise/assets/48032385/444ed017-3e82-4545-a0fb-c1b9a5e66b88)

**Why is this bad/What are the consequences**:
Areas should have Areas

**Steps to reproduce the problem**:
1. Log on Metastation

**When did the problem start happening**:
No clue

**Comment by meow20** [comment]
Dear lord 💀
