### ISSUE TITLE
You can't put a ID in a PDA on the floor

### ISSUE THREAD

**Issue by GDNgit** [ParadiseSS13/Paradise#22641]
**Issue Description**:
You can't put a ID in a PDA on the floor

**What did you expect to happen**: 
Per a comment in the code and previous behavior, this is what is suppose to happen

**What happened instead**:
Someone fucked up the check so it doesn't happen

**Why is this bad/What are the consequences**:
severe minor annoyance 

**Steps to reproduce the problem**:
try to put it in
can't :(

**When did the problem start happening**:
sometime within the past

**Extra information**:
jimkil do the funny

**Comment by JimKil3** [comment]
the `attackby` proc isn't called when you click an item on the ground with another item, fixing this would be moving the logic for inserting the ID into a PDA on the ground into whichever proc is called
