### ISSUE TITLE
AIs can not use mech equipment

### ISSUE THREAD

**Issue by GreatGatherer** [ParadiseSS13/Paradise#22648]
**Issue Description**:
When deployed to a mech as AI, either through the exosuit beacon or through malf AI mech domination, no equipment is able to work

**What did you expect to happen**: 
I expect to be able to use the mech that was given to me/I rightfully stole using my hard earned points, to be able to help/hinder the crew

**What happened instead**:
I get a fancy shell to run around in, but my equipment does absolutely nothing. Clicking on a person with gear will try and track them with your camera, and there's no way to fire guns in a durand/gygax/ect.

**Why is this bad/What are the consequences**:
I expect that when robotics builds a mech that I'm allowed to use as AI, I can go help the blob fight in a more... direct way.

Significantly more impactful as malf AI where mech domination is entirely useless.

**Steps to reproduce the problem**:
1: Play AI
2: Malf
3: Buy mech domination
4: Steal a mech
5: Oh no.

or
1: Robotics makes you a mech. How kind.
2: Take control.
3: Oh.

**When did the problem start happening**:
This is an issue that has been broken as long as I've been playing on paradise, and as far as I am aware has been unfixed for over a year.

**Extra information**:
N/A

**Comment by GDNgit** [comment]
You're aware AIs use middle click for mechas right?

**Comment by Contrabang** [comment]
Yeah, AIs using mechs need to middle click to use the mech's main weapons. It says it as you gain control of the mech
