### ISSUE TITLE
Anti-Drop implant breaks if you lose your arm.

### ISSUE THREAD

**Issue by pismorizzo** [ParadiseSS13/Paradise#22651]
**Issue Description**:
The anti-drop implant becomes unable to relax your other hand after you lose an active anti drop hand, thus causing you to be stuck with an item glued to your 1 remaining hand until you can get a hand reattached. 

**What did you expect to happen**: 
To be still able to tense and relax my remaining arm since its a brain implant. 

**What happened instead**:
If you tense your remaining hand you become unable to relax it, it will say it is relaxing it but it wont. Thus causing you to have no hands at all until you can get a hand reattached which seemed to fix the issue.

**Why is this bad/What are the consequences**:
- Antag eats bomb
- Bomb takes active arm, 
- Antag repicks up weapon and tenses 
- Realize you can no longer relax and thus must get someone to reattach a hand while you now have no hands at all as your remaining one is stuck on the weapon.

-Die

**Steps to reproduce the problem**:
Install anti drop implant, tense an item in a hand, remove tensed hand, try to tense an item in the remaining hand and then relax it. Item should be stuck and it will not let you relax it despite saying it will.

**When did the problem start happening**:
No idea probably a long time.

**Extra information**:
Screaming at my thralls to get a hand reattached while I am powerless to do anything cause I have a giant staff glued to my hand was not ideal.

**Comment by JimKil3** [comment]
reproduced this on my test server, it might be something with the `l_hand_ignore` and `r_hand_ignore` vars not resetting when a limb is lost, but I'm not entirely certain
