### ISSUE TITLE
Vox Scream has no cooldown

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2265]
You can spam scream the vox scream as vox. Lacks a cooldown.

**Comment by Spacemanspark** [comment]
That must be recent.
How horrific.

**Comment by Markolie** [comment]
There we go, that's the right tag. They do have a cooldown.

Keep in mind that the cooldown is only like two seconds.

**Comment by KasparoVy** [comment]
If there wasnt a cooldown, spamming a scream macro would output overlapping sounds

'd also probably blow out your ears and liquefy brains too
