### ISSUE TITLE
Medical Hardsuit does not provide protection from Contact diseases

### ISSUE THREAD

**Issue by FireTarrasque** [ParadiseSS13/Paradise#22650]
**Issue Description**:

The Medical Hardsuit, whose description states provides "Complete protection from pathogens", does not actually seem to provide ANY protection from contact viruses.

**What did you expect to happen**: 
As hijacker virologist, I acquired a Medical Hardsuit. I was going to use it to vaccinate myself against the diseases in the disease crate, and then spread superinfected monkeys throughout the station as a form of biological warfare. I expected that the 

**What happened instead**:

Instead, I immediately became infected every time I gave a monkey a contact virus, even when the suit was activated and I was using a gas mask with internals on.  This happened three separate times.

**Why is this bad/What are the consequences**:

This caused several accidental outbreaks on-station, and could continue to do so in the future. Also, it gets in the way of Virologist hijacker shenanigans.

**Steps to reproduce the problem**:
It should be pretty simple to make the medical hardsuit protect you from contact viruses, right? The paramedic one might already do it, even.

**Comment by PIerreLouisH** [comment]
Easy to patch, but overdue: 

hardsuits are getting softly depreceted and replace due to modsuits. I suggest we close this issue.

**Comment by Burzah** [comment]
Medical hardsuits have been replaced by modsuits, including in the ruins they were available in. This issue is now closed. If you have any other concerns, please feel free to create a new issue. Thank you for making a report!
