### ISSUE TITLE
Unable to pull out a cult soulstone from a backpack.

### ISSUE THREAD

**Issue by Tourte-Yaya** [ParadiseSS13/Paradise#22666]
**Issue Description**:

You can't click on the soulstone in your backpack.

**What did you expect to happen**: 

To be able to move the soulstone out of the backpack.

**What happened instead**:

You can't pull out the soulshard out of your backpack and the player needs to ahelp it.

**Why is this bad/What are the consequences**:

Sharded player stuck in a backpack is terrible.

**Steps to reproduce the problem**:

No clue, I don't play cultist, though I would guess all you need to do is to place a soulstone in your backpack.

**When did the problem start happening**:

No clue.

**Extra information**:

Too many ahelps about it, forcemoving the shard out for every cultists is painful.

**Comment by Komrad822** [comment]
Just had a cult round, had had the "both hands highlighted" bug. Soul shards were invisible in my hand. thankfully my bag was full. Maybe related, maybe not.

**Comment by Henri215** [comment]
The PR that caused this is being temporarily reverted by https://github.com/ParadiseSS13/Paradise/pull/22709 (with a TM) until the byond issue is fixed.

**Comment by Henri215** [comment]
This is no longer an issue since we updated to newer byond versions, thanks for reporting.
