### ISSUE TITLE
Cloning brains in bodies clones bodies

### ISSUE THREAD

**Issue by YoureNotTheSharpest** [ParadiseSS13/Paradise#22675]
**Issue Description**:
brains are non persistant in cloning

**What did you expect to happen**: 
I expected to not be able to KFV my fellow man

**What happened instead**:
Sticking my man in a vox corpse and cloning him turned him into an actual vox

**Why is this bad/What are the consequences**:
clone people into non cloneable races

**Steps to reproduce the problem**:
grab a dead assistant who has a mind (Trust me they have a very small one)
debrain them or decaputate them
stick head/brain on a vox corpse
stick mr yaya voxxie in cloner
clone them
wait
????
your fellow man can be use to make KFV

**When did the problem start happening**:
I bet since non clonable species existed

**Extra information**:
I believe the 'no cloning' trait is not actually tied to the body itself rather it is tied to the brain which allows for shenangains such as cloning people into being positronic IPCs and all other Bullshit. I understand why it is tied to the brains, mainly because if it was tied to the body then you could stick an IPCs brain into a monkey and then clone them causing the INVERSE of the problem. I only really discovered it last year and never had the time nor enough information on WHY it happens so i left it and forgot about it for a while. I just now had the cloning issue brought back to mind by a discussion over discord. I think I know how it could be solved. If you can find a way to put the cloning trait on bodies then that WOULD solve it, atleast the root cause of it. But I am no c*der so I'll leave the solution crafting to you nerds

**Comment by JimKil3** [comment]
the extra information portion is probably correct, from what I saw looking into it myself
