### ISSUE TITLE
Beakers don't display their actual capacity. It is hardcoded into the description.

### ISSUE THREAD

**Issue by DGamerL** [ParadiseSS13/Paradise#22697]
**Issue Description**:
`glass_containers.dm` , line 122
```
/obj/item/reagent_containers/glass/beaker
	name = "beaker"
	desc = "A beaker. Can hold up to 50 units."
```

As an example, a small beaker will say on examine that it has a volume of 50 units, however this does not account for admins varediting them to hold more.

**What did you expect to happen**:
It to display accordingly when I varedit a beaker to hold more than it's supposed to be 

**What happened instead**:
I spent hours debugging a problem that didn't exist

As I'm marking this as a good first issue, here's a step by step on how to fix it:

- To add a value from a variable into a string, we have to use `[ ]`. So, we can replace the `50` from the example with the `[]`.
- Now, to actually make it display the variable value that we want, we can just add the variable name itself between the brackets!
- If we look at `/atom`, we can see that everything has a `/datum/reagent`, and thus a `maximum_volume` var. This is responsible for how many reagents the beaker/bottle can hold, so we just add it into the brackets!
- As we can't just grab that variable, we have to access it. In this case, we can access it by doing `reagents.maximum_volume`. The `.` means that we are taking a variable from another reference, in this case a reference to the reagents datum.
- Our end result should look like this: `desc = "A beaker. Can hold up to [reagents.maximum_volume] units."`
- Now, rinse and repeat for all beakers and bottles that exist, and we should be good to do!

**Comment by Brillcrafter** [comment]
just about to make the PR
