### ISSUE TITLE
Re-incarnate button doesn't let you respawn in your body regardless of the job/role

### ISSUE THREAD

**Issue by Tourte-Yaya** [ParadiseSS13/Paradise#22706]
**Issue Description**:

Button not working as intended.

**What did you expect to happen**: 

To be respawned inside of my body with the role/job instead of still being a ghost and creating two runtimes.

**What happened instead**:

I was still a ghost.

**Why is this bad/What are the consequences**:

Runtimes bad.

**Steps to reproduce the problem**:

Use re-incarnate button on any role/job.

**When did the problem start happening**:

Today.

**Extra information**:

![image](https://github.com/ParadiseSS13/Paradise/assets/50141998/9648646a-c293-4933-a853-f882932aeaee) 
![image](https://github.com/ParadiseSS13/Paradise/assets/50141998/6270f5e4-e295-4c34-b9a6-e3cbdb568766)
Here's a bunch of runtimes when I tried to respawn as assistant and SOO.

**Comment by Burzah** [comment]
This issue appears to have started after https://github.com/ParadiseSS13/Paradise/pull/22686 was merged.
