### ISSUE TITLE
Sticky beaker

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2270]
there was a beaker that got stuck in peoples hand, and kept duplicating adinfinitum.

![image](https://cloud.githubusercontent.com/assets/7663878/10261323/7b98b008-6992-11e5-86fe-cc5f6d10ae4a.png)

**Comment by Robertha89** [comment]
and nobody could remove em in any way, it was horrible, source might have been the mediborg, not sure.

**Comment by Markolie** [comment]
Effectively a duplicate of https://github.com/ParadiseSS13/Paradise/issues/2259.
