### ISSUE TITLE
Using an empty hand on a MODsuit doesn't allow you to change the inserted cell

### ISSUE THREAD

**Issue by Probablyjay19** [ParadiseSS13/Paradise#22704]
**Issue Description**:
MODsuit advertises in it's item description while it's cover is open that using your empty hand on it will allow you to remove it's cell, this is in fact not true

**What did you expect to happen**: 
For the cell in the MODsuit to pop out into my hand like magic 

**What happened instead**:
The MODsuit swapped from my left hand to my right hand. Needed to use a wrench on it instead, which removes the cell and the MODcore

**Why is this bad/What are the consequences**:
Bugs bad? 

**Steps to reproduce the problem**:
Use a screwdriver on any MODsuit, and as it says, try to use an empty hand to remove it's cell

**When did the problem start happening**:
almost certainly PR#21147

**Extra information**:

https://github.com/ParadiseSS13/Paradise/assets/87214315/cba3b76f-480f-4901-a10a-2dd092a6b2a9

**Comment by Contrabang** [comment]
It says to use a wrench, doesn't it?

**Comment by Henri215** [comment]
Tested and confirmed over discord with Qwerty that it is a bug.

**Comment by Probablyjay19** [comment]
> It says to use a wrench, doesn't it?

It says 

*to remove the cell, use an empty hand* 

Which does not work
