### ISSUE TITLE
recycle bug

### ISSUE THREAD

**Issue by Javi1990** [ParadiseSS13/Paradise#2271]
recycle no release metal and glass....only destroy items

**Comment by Markolie** [comment]
@Fox-McCloud 

Also, please try to provide a bit more information in bug reports. What did you try to recycle, and where?

**Comment by Javi1990** [comment]
http://nanotrasen.se/wiki/index.php/Waste_Disposal

the photo is old, but it is the machine that shreds trash, should become trash in glass and metal, 
its only function

**Comment by Fox-McCloud** [comment]
Pretty sure you're just not feeding it enough materials.

The recycler doesn't work for everything; it will only extra materials from things that actually have materials----you can't get metal from a jumpsuit, for instance.

I just tested this with items that had glass, metal, gold, silver, diamond, and even bananium---they all worked.

**Comment by Javi1990** [comment]
It does not work with broken glass,  should give me a unit of metal or minimum cristial..

**Comment by Fox-McCloud** [comment]
It doesn't work like that. The recycler isn't 100% efficient unless its upgraded.

If you're wanting to recycle glass shards at 100% efficiency, you're going to have to upgrade it or take the time to insert each one into a protolathe.
