### ISSUE TITLE
Powergloves become useless if you use a modsuit. 

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#22716]
**Issue Description**:

title, they become a tc sink and a funny 50 tc paperweight if you have a modsuit active. 

**What did you expect to happen**: 

To have my 50 tc item work just fine with a modsuit

**What happened instead**:

lost 45/50 tc depending how you wanna look at it. 

**Why is this bad/What are the consequences**:

They shouldn't fight over what works/doesn't

**Steps to reproduce the problem**:

Get the powergloves, and a modsuit, put the modsuit on and activate it, and loose functionality of the gloves.

**When did the problem start happening**:

When modsuits got merged.

**Extra information**:

i ded pls fix

**Comment by DGamerL** [comment]
This is sadly how modsuits work. They override your glove slot, causing certain effects like from Krav Magloves or Insulated gloves to be lost. You are free to post a suggestion [here](https://www.paradisestation.org/forum/60-suggestions/) on changing how this currently works!
