### ISSUE TITLE
Flash Bangs do not work

### ISSUE THREAD

**Issue by Komrad822** [ParadiseSS13/Paradise#22742]
**Issue Description**:
Flashbangs are not affecting those around it without flash or hearing protection as they should. Apparently according to PeakPerformance, its inconsistent as they tested at admin testing area in the same round I found the issue.

**What did you expect to happen**: 

I to be blinded and deafened when a flashbang went off near me.

**What happened instead**:

I was perfectly fine both eye and ear wise.

**Why is this bad/What are the consequences**:

Flashbangs are a tool sec AND antags use to contain groups of people or a last ditch effort to stop someone.

**Steps to reproduce the problem**:

1. Prime flashbang.
2. Toss it infront of you
3. Stare at it like you're the guy who stares at the sun all day at Central Park in NYC.
4. Notice how nothing happens except that it pops with the audio file.

**When did the problem start happening**:

Noticed round 37574. First round of the day for me so idk if it was occurring earlier.

**Extra information**:

Peak says that flash powder also did not work but holding the flashbang as it went off DID work in flashing you.

(Had a video but it had an mhelp in it so cant post here sorry)

**Comment by Ionward** [comment]
#22286 was the last PR to affect flashbangs, if this helps sleuth things out any
