### ISSUE TITLE
Hole in Athland Ruins causes a pit in reality, that, or Lavaland is truly hollow.

### ISSUE THREAD

**Issue by Inferno1882** [ParadiseSS13/Paradise#22745]
**Issue Description**:

Found a space tile in the Athland Excavations ruin. 

**What did you expect to happen**: 

The hole to not be there.

**What happened instead**:

There was a hole.

**Why is this bad/What are the consequences**:

Holes leading to the vacuum of space on a planet is not good.

**Steps to reproduce the problem**:

Observed the hole.

**When did the problem start happening**:

**Extra information**:

This, uh, _may_ be from an exploding Crate that blasted onto plating. I unfortunately cant confirm at the moment, but this is likely.

I'm not smart, but checking to see if plating being destroyed on Lavaland should spawn the Lava/Chasm tile or Space might help these very infrequent incidents. That, or making sure the items under the plating is correct. I'm not a mappist.

**Comment by DGamerL** [comment]
Could you next time include a picture of where it happened?

**Comment by DGamerL** [comment]
Fixed by #22850! Thank you for making the report!
