### ISSUE TITLE
Reword Ash Walker briefing

### ISSUE THREAD

**Issue by Norwes1** [ParadiseSS13/Paradise#22752]
The current ash walker prompt reads '**Do not attack the Mining Outpost without provocation.**' Thing is, ash walker _players_ tend towards the sort who view 'stubbing mah toe' as provocation enough to raid the Mining Outpost. Meanwhile, the wording of '**Do not go onto the main station without admin permission**' is actually adhered to in practice.

In just the past couple rounds (37582 and 37583 in particular) I've had to break up ash walker rule-breaking behavior, including raiding the Outpost multiple times and trying to lure megafauna to it when they were told not to go onto the main station. If we aren't gonna remove ash walkers entirely, then let's at least make it clear that they need to cut down on their shenanigans, because this is taking up a ridiculous amount of admin overhead and causing a lot of dchat salt.

Suggestion: Change the wording on the first part to **Remember: you are NOT automatically an antagonist. Do not attack individual Miners unless they attack first, and do not raid the Mining Outpost unless Miners destroy your home tendril. Do not go onto the main station without admin permission. Do not lure megafauna to the Mining Outpost or carry out similar round-disruptive actions at any time. Failure to comply may lead to a ban.**'

The ungas aren't gonna stop unless we spell out exactly what they can't do, so let's draw some more boundaries and make it clear that bans are on the table unless they knock it off. Please.

**Comment by S34NW** [comment]
Ashwalkers are lavaland antagonists, according to headmin ruling.
This is thus a non-issue, approach the headmins to change their stance on ashies before we can make any such designation changes in their briefing.
