### ISSUE TITLE
minor Vampire visual bug with envy knife

### ISSUE THREAD

**Issue by Boojabin** [ParadiseSS13/Paradise#22756]
**Issue Description**:
The food bar texture in the top right of the screen when you are hungry changes from the blood symbol to the burger as far as I know when you use an envy knife on a corpse from a legion.

**What did you expect to happen**: 
I expected the blood texture to still be there.

**What happened instead**:
the hunger bar turned into the regular hunger bar given to crew.

**Why is this bad/What are the consequences**:
there isn't really anything bad but it just being a minor visual bug that probably doesn't cause any issues with anyone else due to how obscure the circumstances are, and how miner it effects the game, as all it did to mean was think that I wasn't a vampire for a brief moment.

**Steps to reproduce the problem**:
1: be a vampire
2: locate envy rune and grab knife
3: get a legion to drop a ash walker corpse
4: use envy knife on the ash walker corpse

**When did the problem start happening**:
i don't know when this problem started or if it just has been a thing since paradise started, because this visual bug is probably overlooked by everyone.

**Extra information**:

**Comment by DGamerL** [comment]
Essentially the same as #22490.
The vampire hunger HUD isn't prepared to stay if your species changes, not only ashwalkers. Thanks for making the report anyways!
