### ISSUE TITLE
Hoodie runtime

### ISSUE THREAD

**Issue by JimKil3** [ParadiseSS13/Paradise#22760]
**Issue Description**:
If a hoodie gets hit by acid, and its hood is deleted, it runtimes every single time you click the action button to toggle hood.

**What did you expect to happen**: 
For there to be a null check

**What happened instead**:
No null check

**Why is this bad/What are the consequences**:
Lots of runtimes if the button is spam-clicked

**Steps to reproduce the problem**:
Presumably, put on a hoodie, delete the hood somehow, then try to toggle it

**When did the problem start happening**:
Unsure

**Extra information**:
![image](https://github.com/ParadiseSS13/Paradise/assets/47290811/41574995-9059-4048-927d-53cc9349e3c6)

**Comment by DGamerL** [comment]
Could you add a piece where you explain it in the code, where you put the nullcheck, what a nullcheck is etc.?

**Comment by JimKil3** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/47290811/d547acfe-6a3a-4779-94c5-3e86530ca25b)
The highlighted line is where the runtime happens. The game tries to check if the hood has the `NODROP` flag, but since there is no hood (because it got deleted by acid or some other method), it ends up trying to read the `flags` var of something that's null, hence the runtime error ("Cannot read null.flags"). To fix this, you can use the `?.` operator or add an addl. check somewhere else to see if the hood is null _before_ checking its flags.

**Comment by Brillcrafter** [comment]
applied the fix and going to make the PR tonight when I have more time.
