### ISSUE TITLE
Even when handcuffed, those dual wielding a chainsaw don't drop the chainsaw.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2276]
Meaning it's literally impossible to stop someone with a chainsaw without killing them. They're under the effects of handcuffs, sure, but that almost means nothing without continuous stunning. They can still attack when standing up, with the chainsaw.

**Comment by TheDZD** [comment]
I need to have a look at how /tg/ handles NODROP and handcuffs, because dropping a NODROP chainsaw will result in somebody accidentally picking it up and being unable to drop it.

**Comment by KasparoVy** [comment]
And then they continue the legacy of a chainsaw massacre

**Comment by TheDZD** [comment]
At the moment, you can no longer attack with the saw while cuffed, but you still can't get the chainsaw off of them.
