### ISSUE TITLE
При емаге АПЦ сбивается dir

### ISSUE THREAD

**Issue by dj-34** [ParadiseSS13/Paradise#22775]
При емаге АПЦ сбивается dir (видимо сбрасывается c нашего кастомного apc/*dir* до обычного apc, либо не берет изначальное положение apc.
Возможно похожая проблема присутствует на других подтипах машинерии
Возможное решение: нужно брать значение оригинального dir при emag_act()

**Comment by dj-34** [comment]
woops, missed issue repository

**Comment by Contrabang** [comment]
Привет!
Это английская кодовая база Paradise. Думаю, вы ищете https://github.com/ss220-space/Paradise/issues. Я не думаю, что созданная вами проблема применима к нашей кодовой базе. Я не носитель языка, но если у вас возникнут вопросы, дайте мне знать )
