### ISSUE TITLE
Cyborgs are unable to click-drag items and objects

### ISSUE THREAD

**Issue by Fordoxia** [ParadiseSS13/Paradise#22808]
**Issue Description**:
Normal crew are able to click on an adjacent tile to make dragged objects move into it. Cyborgs lack this functionality despite having the ability to drag.

**What did you expect to happen**: 
For click-dragging to be functional.

**What happened instead**:
Click-dragging is not functional.

**Why is this bad/What are the consequences**:
Dragging items around requires weird movements to make things move into the correct tile. Cyborgs cannot put dragged items onto tables without deconstructing the table or building a table underneath themselves. It is also possible for a cyborg to become trapped between two objects if there is no room to push them away (in situations where click-dragging would allow normal crew to easily escape).

**Steps to reproduce the problem**:

**When did the problem start happening**:
For as long as I can remember.

**Extra information**:
No further information.

**Comment by DGamerL** [comment]
Not a bug, cyborgs do not have hands and therefore cannot push objects like this, alas.
