### ISSUE TITLE
neurotoxin organ stun shooting

### ISSUE THREAD

**Issue by sirjatu** [ParadiseSS13/Paradise#22803]
**Issue Description**:
neurotoxin spit gotten via xeno organs works while in stamina crit

**What did you expect to happen**: 
I didn't think I would be able to shoot a magic space organ gun while stunned

**What happened instead**:
I was able to shoot people/xenos with neurotoxin while stunned

**Why is this bad/What are the consequences**:
seems like an oversight to allow non-xenomorphs to a high capasity ranged weapon

**Steps to reproduce the problem**:
have a neurotoxin xeno organ implanted into self, get stunned, be still able to shoot neurotoxins at people

**When did the problem start happening**:
When I tried it in a round, and it somehow worked

**Comment by DGamerL** [comment]
As per the original author, this is intended behaviour.
It was also asked to the balance team, they agreed it was fine to leave it as is.
