### ISSUE TITLE
Humanoid Slowdowns Do Not Apply to Wheelchairs

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#2280]
This bug appears to be the source of the recent wheelchair speed demons on the server. If for example, you're wearing a hardsuit, you'll move faster on a wheelchair than you would otherwise.

**Comment by Markolie** [comment]
@tigercat2000

**Comment by TheDZD** [comment]
You could probably add something like:
`var/mob_delay = driver.movement_delay
if(mob_delay > 0)
     move_delay += mob_delay`
under [this](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm#L40) line to fix it, although I'm not 100% certain of that.

**Comment by Robertha89** [comment]
nah, the move_delay could be set too 3, would fix everything, i was messing around with that after alex asked if i could make a fix.

**Comment by tigercat2000** [comment]
that wouldn't fix everything, Robertha, that would just slow the wheelchair down another tick. Doesn't solve the issues with hardsuits.

**Comment by TheDZD** [comment]
Granted, my "fix" would result in wheelchair users being further crippled because they would always move with 2 more slowdown than everyone else.

**Comment by Markolie** [comment]
And it's not possible to just set the movement speed of the wheelchair to a set value right? Or just prevent it from going over the wheelchair max speed by using max(movement_speed, wheelchair_speed)?

**Comment by Robertha89** [comment]
Well, the main reason to use the wheel chair is, missing a foot or two, or pain and maaaybe hunger, so how about wheelchair ignores the slowdown by pain, limbloss, broken limbs, and possible hunger. Well maybe not hunger, i just want it that way, but it would be bad balance.

**Comment by KasparoVy** [comment]
What if they just have STRONK SPESSMEN BICEPZ/arms whatever?
