### ISSUE TITLE
UI shows for exosuit after getting carded from the Exosuit then getting put back in AI core

### ISSUE THREAD

**Issue by Jaredw224** [ParadiseSS13/Paradise#22815]
**Issue Description**: UI shows for exosuit after getting carded from the Exosuit then getting put back in AI core

**What did you expect to happen**: When getting carded out of the exosuit then put in the AI core the UI for the exosuit does not show up

**What happened instead**: So when you get carded out a exosuit as the AI and then put back in the AI core the UI for the exosuit shows, the game is thinking your still in the exosuit, when really you are in the AI core

**Why is this bad/What are the consequences**: None that I can see, but can be abusive if used right

**Steps to reproduce the problem**: Go as the AI, Upload your self to a exosuit with a AI control beacon, then get carded out the exosuit, then someone puts you back in the AI core, the UI for the Exosuit shows up instead

**When did the problem start happening**: Now

**Extra information**:

**Comment by Henri215** [comment]
Duplicate issue of https://github.com/ParadiseSS13/Paradise/issues/19923.
Thank you for reporting anyway.
