### ISSUE TITLE
Service cyborgs can make infinite omnzine. 

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#2281]
Needless to say, this is very overpowered.

**Comment by Markolie** [comment]
Provide the steps to reproduce please, because "X can do Y" isn't very helpful.

**Comment by Alex6511** [comment]
1. Grind up a warm donk pocket to create omnizine and some nutrient. 
2. Bring it to chemistry, have them remove all the nutrient from the mix
3. Pickup said omnzine with your dropper, put it in your shaker
4. Put this back in the beaker, this begins synthing more omnzine
5. Repeat steps 3-4 until you have a full shaker of omnzine.

**Comment by TheDZD** [comment]
You can probably do something similar using the beer can after emptying it out too. Both of these items should probably be restricted to only regenerate reagents that are drinks.

**Comment by Robertha89** [comment]
I would be fine if the mediborg had a synthesizer anno odysseus syringe gun, but service cyborg is supposed to be universally useless, this is unacceptable
