### ISSUE TITLE
When a AI is in a exosuit, AI can't use any of the modules

### ISSUE THREAD

**Issue by Jaredw224** [ParadiseSS13/Paradise#22816]
**Issue Description**: When a AI is in a exosuit, AI can't use any of the modules

**What did you expect to happen**: Being able to push middle mouse and use your installed modules

**What happened instead**: when pushing the middle mouse you were unable to use the modules

**Why is this bad/What are the consequences**: The AI can't help anyone, nor help the station if the crew needs help or needs fixing

**Steps to reproduce the problem**: Get in a exosuit with modules and a AI control beacon Upload yourself as the AI to the Ripley APLU then try to use the RCD, Cable layer, 	Extinguisher, ion jetpack. Try pushing your middle mouse (nothing will happen) only module you can use is the ion jetpack (due to it only be on the UI)

**When did the problem start happening**: Now

**Extra information**:

**Comment by GDNgit** [comment]
Did you select a module?

**Comment by Jaredw224** [comment]
you can't, even pushing middle mouse button, I had a RCD installed and pushing middle mouse nothing shows up, the only thing I saw that worked was the ION, thats becuse that was on the UI on the top of the screen not the RCD though

**Comment by JimKil3** [comment]
I was able to use modules in a mech as an AI on my local server
![dreamseeker_fhY8nqizvP](https://github.com/ParadiseSS13/Paradise/assets/47290811/01fc1865-d5dc-447e-bfe5-8c54789c2625)
