### ISSUE TITLE
Direction locking is broken.

### ISSUE THREAD

**Issue by Scribble-Sheep** [ParadiseSS13/Paradise#22870]
**Issue Description**:
Direction locking (shift + middle clicking) doesn't seem to work anymore.

**What did you expect to happen**: 
Direction locked north, remain facing north no matter what, at the cost of speed

**What happened instead**:
I moved in the direction I was facing, then changed to face north after after I was done moving.

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:
Just try to direction lock and move, observe that it doesn't work.

**When did the problem start happening**:
Round 37664

**Extra information**:

**Comment by Contrabang** [comment]
related to the tm of #21956 i believe. Will need to confirm if its still active

**Comment by DGamerL** [comment]
TM is currently not active anymore.
Direction lock has been restored to working again! Thank you for making this report! If it happens again, feel free to make another one!
