### ISSUE TITLE
Animals unable to move

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2289]
At random times animals are unable to move, I do not know how or why, but it usually happens with corgi's, can't move with arrow keys, you can change direction with mouse button, and that is it.

**Comment by Markolie** [comment]
Again, bug reports like this won't help anything. Please always provide the specific circumstances under which it happened and try to give as many details as possible, even when you're not sure why it happens. Screenshots help too.

People are relying on coders too much to figure out what's wrong.

**Comment by Alex6511** [comment]
Encountered this awhile ago, it's fixed by resting twice.
