### ISSUE TITLE
IPC bug killed by radiation

### ISSUE THREAD

**Issue by Javi1990** [ParadiseSS13/Paradise#2290]
My life started to fall by being near a person, in chat (You are enveloped by a soft green glow emanating from Leonel Bloise.)
after my body had many toxins

in wiki read

     Immune to Oxygen Deprivation.

    Immune to Toxins.

    Immune to Clone Damage. (about 30%)

    Immune to Radiation

    Immune to disease.

**Comment by Markolie** [comment]
How long ago was this? There's a specific check in place for IPC's to take radiation damage in the case you mentioned, and I just tested it and I didn't take any damage. The toxin may have come from something else, but that issue has been fixed as well.

**Comment by Javi1990** [comment]
I think it was by touching a person, Wikipedia says I'm immune...

**Comment by Markolie** [comment]
For now I can't reproduce. Once we've patched and it still happens, re-open this please.
