### ISSUE TITLE
AI unable to use sleepers of Odysseus

### ISSUE THREAD

**Issue by terror131** [ParadiseSS13/Paradise#22951]
**Issue Description**:

when playing as an AI one shift I took control of a Odysseus with a medical sleeper on it to try to move a corpse into medical so medical can revive them but for some reason i was unable to use the sleeper and all i got was saying attempting to track the person when I tried to click on them with the sleeper raised

**What did you expect to happen**: 

to be able to use the sleeper 

**What happened instead**:

all i got was messages saying attempting to track the person i was trying to use the sleeper on

**Why is this bad/What are the consequences**:

AI's unable to use sleepers from exosuits to help save people is kind of bad

**Steps to reproduce the problem**:

connect to an exosuit with an AI beacon
raise/equipped sleeper
click corpse
didn't pick up corpse only got message of attempting to track

**When did the problem start happening**:

unsure
**Extra information**:

the Area I was attempting to do it in had no camera unsure if this had an effect on it

**Comment by DGamerL** [comment]
Heya, could you try using your middle mouse button? AIs should use that instead of the leftclick for any mech interactions!

**Comment by terror131** [comment]
yep turns out it was middle click and i'm just stopid
