### ISSUE TITLE
Lack of handheld mirror options for nonhuman species

### ISSUE THREAD

**Issue by Bjamcham** [ParadiseSS13/Paradise#22966]
**Issue Description**:
Handheld mirror lacks body marking and other mirror options availible on station mirrors for non human species.

**What did you expect to happen**: 
To see the same menu with all of the normally availible customization options as the wall mounted mirror when using the handheld mirror

**What happened instead**:
There were no options in the UI at all for nians and other non human species were missing sections as well.

**Why is this bad/What are the consequences**:
The mirror should be usable for species that aren't just humans.

**Steps to reproduce the problem**:
Spawn as a nian or other species with body markings, get a handheld mirror, try to use it, compare the options with that of a wall mounter mirror.

**When did the problem start happening**:
Since the handheld mirror's addition in https://github.com/ParadiseSS13/Paradise/pull/22042 

**Extra information**:
![image](https://github.com/ParadiseSS13/Paradise/assets/107899953/b0617968-37e6-4665-a21a-c25468bf69c1)

**Comment by Burzah** [comment]
Okay so currently I see this happening with just Nian, but it would have to be looked into further. 

Testing appearance changes and the mirror right now locally has been problematic (and probably needs another issue report made about it). Currently not all species are displaying mirror options properly locally, but seem to be functioning on live servers. Though another issue that happens on both live and local makes species have body accessories that aren't meant for the species in question, which occurs after changing the species via a magic mirror, then using a regular mirror to adjust it further.
