### ISSUE TITLE
RCDs do not work on windows with no grilles.

### ISSUE THREAD

**Issue by Fordoxia** [ParadiseSS13/Paradise#22974]
**Issue Description**:
The Rapid Construction Device (RCD)'s deconstruction setting cannot deconstruct a window unless it has a grille under it.

**What did you expect to happen**: 
For un-grilled windows to also be deconstructable.

**What happened instead**:
Ungrilled windows are immune to the RCD.

**Why is this bad/What are the consequences**:
Windows are supposed to be deconstructable. Lacking a grille probably shouldn't make this impossible.

If a single degrilled window is destroyed, RCD cannot spit out a degrilled window to make it blend with the other windows, nor can it deconstruct the degrilled windows to allow quick and easy conversion to grilled windows.

**Steps to reproduce the problem**:
Equip an RCD. Attempt to deconstruct a window with no grille.

**When did the problem start happening**:
Unknown, but PR #22273 made the problem much more noticeable now degrilled windows are found almost everywhere.

**Extra information**:
No extra information.

**Comment by DGamerL** [comment]
Fastest fix PR in the west.
