### ISSUE TITLE
(gamma?) ERT borgs are unable to use common radio

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#22970]
**Issue Description**:

using `;` results in them speaking over the response team radio channel, rather than common 

**What did you expect to happen**: 

for them to speak over common

**What happened instead**:

couldn't ask the crew important questions

**Why is this bad/What are the consequences**:

being unable to communicate with the general crew is not ideal

**Steps to reproduce the problem**:

1. become a ert borg. MIGHT only be gamma combat borgs, unsure.
2. try to speak over common radio using `;`
3. find that you're speaking over the ert comms 

**When did the problem start happening**:

likely whenever ert comms not needing tcoms being up to work got merged?

**Extra information**:

**Comment by Adrer** [comment]
This is actually deliberate (Do not ask my WHY it was done like this though), ERT borgs have their default frequency set to the ERT comms frequency, and their frequency is locked, this means that ; will default to ERT comms, and there is no way to bypass this.
![image](https://github.com/ParadiseSS13/Paradise/assets/19361017/9e027d36-2cdf-440c-88bb-205d8ba583bf)


Personally I'm fine with this being changed to no longer lock them into ERT comms.

**Comment by DGamerL** [comment]
As Chap said, this is indeed intended. Feel free however to ask the design team to change this! This is quite weird, and would probably not have any pushback to being changed.
