### ISSUE TITLE
Singularity escapes

### ISSUE THREAD

**Issue by Talik6969** [ParadiseSS13/Paradise#22980]
**Issue Description**:

Singularity passes through shields and escapes

**What did you expect to happen**: 

Singularity must not pass through the shields

**What happened instead**:

Singularity escapes from the shields

**Why is this bad/What are the consequences**:

Singularity mechanics is broken. Cannot be used in game

**Steps to reproduce the problem**:

Make shields and teleport singlularity using Praticle Accelerator

**When did the problem start happening**:

I don't know

**Extra information**:

**Comment by Henri215** [comment]
Something like this happened? https://github.com/ParadiseSS13/Paradise/issues/14848

**Comment by Talik6969** [comment]
> Something like this happened? #14848

Use. OMG it's been broken for 3 years?

**Comment by Oyu-De** [comment]
> > Something like this happened? #14848
> 
> Yes. OMG it's been broken for 3 years?

this would happen from time to time, although much more prominently as we did not have SM and instead used singulo/tesla back in the day. Singulo/tesla sometimes would clip through the walls. Ought to be fixed, apparently not.

**Comment by Talik6969** [comment]
> this would happen from time to time, although much more prominently as we did not have SM and instead used singulo/tesla back in the day. Singulo/tesla sometimes would clip through the walls. Ought to be fixed, apparently not.

Why? It's a broken and singulo ALWAYS escapes

**Comment by DGamerL** [comment]
Closing as it is a duplicate, thank you for making the report!
