### ISSUE TITLE
Icons moved back to origional location after IB knockdown

### ISSUE THREAD

**Issue by silverplatedelta** [ParadiseSS13/Paradise#23007]
**Issue Description**:
Custom placed icons move back to the original location after an IB induced knockdown

**What did you expect to happen**: 
Ability icons to remain where I custom placed them.

**What happened instead**:
OH GOD WHERES MY CURSED HEART BUTTON

**Why is this bad/What are the consequences**:
your ability buttons shouldn't be randomly reset.

**Steps to reproduce the problem**:
move abilities, get IB stunned, weep

**When did the problem start happening**:
Probably with a recent change to ability buttons

**Comment by GDNgit** [comment]
Can't reproduce this on local, cursed heart stayed where it was. Sure you didn't shift click to reset it?

**Comment by silverplatedelta** [comment]
Unable to reproduce this on local. This has either been fixed at some point or I suffered a skill issue prior to reporting.
