### ISSUE TITLE
Burn husking appears to no longer work

### ISSUE THREAD

**Issue by SchrodingersWolf** [ParadiseSS13/Paradise#23028]
**Issue Description**: 
As title. You appear to be unable to husk anyone via inflicting burn damage.

Methods tested include laser and pulse weaponry, Immolators, the Burn Death smite, 1000 Kelvin fluorosulphuric/water spray bottles, and finally cooking them in a plasmafire with a 50% O2/50% plasma burnmix. 

Subjects tested include humans, skrells, drasks, and drask umbraes.

**What did you expect to happen**: 
To be a Bond villain and burn someone into a husk via superheated acid, water, plasmafire torture chambers, my veritable arsenal of laser and pulse weaponry and finally my god (admin) powers.

**What happened instead**: 
I managed to get Critical Burns on all of their limbs and 500+ burn damage, but examining them and using a Medical scanner tells me that the person is not husked.

**Why is this bad/What are the consequences**: Sitting in a plasmafire/getting lasered to death should have consequences.

**Steps to reproduce the problem**:
1. Spawn in your test subject of choice
2. Inflict burn damage of your choice
3. After they died, scan them with a Medical Scanner and realise they have 500+ burn damage but aren't husked

**When did the problem start happening**:
No idea, but only discovered on 23/10/2023

**Extra information**:
Some people in #coding-chat told me that /mob/living/carbon/human/adjustFireLoss and /mob/living/carbon/human/getFireLoss in human_damage.dm isn't used anywhere - Maybe that is a place to start?

**Comment by SchrodingersWolf** [comment]
Update: Seems like the Burn Death smite still works in husking someone, but you have to keep smiting them multiple times before they will turn into a husk. The rest of the issue still applies currently.

**Comment by Spaghetti-bit** [comment]
I’ve been unable to reproduce this and body’s are husking. The bonfires have had their meals.

**Comment by silverplatedelta** [comment]
as a drask player, I can confirm that this issue is no longer occurring.
