### ISSUE TITLE
The uplink shopping cart can sometimes consistantly BSOD.

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#23030]
**Issue Description**:

So, the shopping cart TGUI for some reason, is crashing, and whatever is causing it is inconsistent, however if it DOES start to BSOD, you'll be unable to access the shopping cart, and ONLY the shopping cart section of your uplink for the rest of the round. 

**What did you expect to happen**: 

To be able to use the tab.

**What happened instead**:

Cant use the tab.

**Why is this bad/What are the consequences**:

loss of functionality is badd

**Steps to reproduce the problem**:

Not a CLUE. 
The only relation was adrenals being added to the cart the two times it happened. 

**When did the problem start happening**:

when the shopping cart thing was added

**Extra information**:

Its happened to me twice now, as stated above the only two commonalities was adrenals, im pretty sure, and other rounds i've been able to use the uplink shopping cart tab in its fullest.
The error message if its any help, and my byond version is `515.1514`.
My hunch is that it COULD be the recommended items to buy trying to reference a non-existent item, however since its crashing, i flat out have no way of checking whats in it, and TGUI code scares the hell outa me, so. 
![lYFPP0NMV8](https://github.com/ParadiseSS13/Paradise/assets/96908085/e8c1d45f-599c-4156-9f3b-efce349c9164)

**Comment by Scribble-Sheep** [comment]
I had this happen to me the other round, and I wasn't buying adrenals.
Unfortunately I don't remember what it was.

**Comment by Oyu07** [comment]
> I had this happen to me the other round, and I wasn't buying adrenals. Unfortunately I don't remember what it was.

So thats two people saying its adrenals related, something is going on

**Comment by Scribble-Sheep** [comment]
> > I had this happen to me the other round, and I wasn't buying adrenals. Unfortunately I don't remember what it was.
> 
> So thats two people saying its adrenals related, something is going on

No no uh, I wasn't buying adrenals

**Comment by Scribble-Sheep** [comment]
> > My hunch is that it COULD be the recommended items to buy trying to reference a non-existent item
> 
> I am able to reproduce this by refreshing my recommended items over and over. However, I'm unsure if this can also be caused by a bugged item in the store. @Scribble-Sheep I'd like to know if you also ran into this when pressing "See more suggestions" so I can rule out bugged items in the store

If memory serves me right, the first time I got this, I added a few items to my cart, and it bluescreened when I tried to check out, without ever even getting to like, see the cart.
I antagged again after that, got into the cart fine, and refreshed my suggestions a few times, with no problem, though, that's a randomized screen, so that prolly doesn't help much.
