### ISSUE TITLE
Some things pull ghosts with no prompts

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2306]
List of things I know of:
 - Xenomorphs
 - Borers
 - Revenants
 - Wizard Apprentices
 - Blubs

>observing, in the middle of dealing with so-
>LOLXENONOW
>fucking kill me

**Comment by TheDZD** [comment]
This happens far too often when I'm alt-tabbed coding while also keeping an eye on the server.

**Comment by Spacemanspark** [comment]
...I thought borers were in the 'Spawn as NPC' catagory?

**Comment by Markolie** [comment]
Generally speaking, you should turn off your preferences if you don't want to play as one of these roles. An alternative is enabling antag hud (and de-adminning).

**Comment by TheDZD** [comment]
@Spacemanspark Borers spawned by admins/other borers are, yes. Borers spawned directly by the random event, not so much.

**Comment by tigercat2000** [comment]
@Markolie Fuck that, this should prompt regardless of preference. Even for non-admins this shit is abrupt and annoying.

**Comment by TheDZD** [comment]
@Markolie Consistency-wise though, there are other antags that prompt you if you have the preference turned on, such as the nuke ops borg. It wouldn't be a stretch to extend the same thing to these ones.
