### ISSUE TITLE
Nuke won't accept code on blob 7-12

### ISSUE THREAD

**Issue by Axios69** [ParadiseSS13/Paradise#2307]
Nuke code provided with 7-12 directive on blob rounds won't work with the nuke, it just says error. Station's own disk or DS disk don't work either

**Comment by Markolie** [comment]
The admin probably gave the wrong code, or there was a second nuke on the station (admin spawned?).

**Comment by Spacemanspark** [comment]
This was the automatic announcement for blobs when they spread too far. I was the captain of said round.

**Comment by Spacemanspark** [comment]
The nuke was from the vault, I retrieved it myself.

**Comment by Earthdivine** [comment]
This issue is happening more and more from what I've been hearing, can I ask to have this issue looked into more since it makes nuke ops and blob extremely dicey?

@Markolie @DZD @Fox-McCloud

**Comment by Crazylemon64** [comment]
This is fixed, yes?

**Comment by TheDZD** [comment]
Would seem so, haven't had any reports of this recently.
