### ISSUE TITLE
The crew monitor map is broken.

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#23092]
**Issue Description**:

Title, when you move the map the dots for people with tracked dont move

**What did you expect to happen**: 

for them to move

**What happened instead**:

they didn't move

**Why is this bad/What are the consequences**:

useless function if the dots dont move

**Steps to reproduce the problem**:

1. get a crew monitor. (might be cyborg only? i doubt it though)
2. look at the map mode.

**When did the problem start happening**:

dunno

**Extra information**:

![SYS3LrJrxA](https://github.com/ParadiseSS13/Paradise/assets/96908085/cf145e6f-fef6-429d-b8bb-23810e86b18e)
![mgEwMBEONp](https://github.com/ParadiseSS13/Paradise/assets/96908085/a845f826-aa68-40a6-87cd-e57821bdf067)
![QZNDKUaa9F](https://github.com/ParadiseSS13/Paradise/assets/96908085/0a012e2c-e1b5-4fe9-b7ba-e55ce4ccf4a8)

**Comment by Oyu07** [comment]
Just to confirm, does it reset to their proper positions after a second or so?
If that is the case, I believe its been there since start, There is probably a way to fix this though

**Comment by Contrabang** [comment]
> Just to confirm, does it reset to their proper positions after a second or so? If that is the case, I believe its been there since start, There is probably a way to fix this though

it doesn't.

I believe the problem is the drag is on the image, not the main box
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/5a560058-ef75-4387-b1ad-5f2233ee66ff)
