### ISSUE TITLE
If a mule bot is called by the ai once, you're completely unable to call it again, for the rest of the round.

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#23095]
**Issue Description**:

Title, if you use the "call" function as ai on a mule, you'll be able todo it exactly ONCE. after that it'll think its arrived despite not actually moving. 

**What did you expect to happen**: 

To be able to freely call mules around.

**What happened instead**:

Could once, after that, mule bonked.

**Why is this bad/What are the consequences**:

Broken feature. 

**Steps to reproduce the problem**:

1. Be ai
2. use the robot interface menu to call a mulebot to a location
3. have it arrive, and depending on if "return home" function is active or not you'll get two outcomes
If you have autohome on, it'll return home, and become unmovable via the "call" ai ability.
If you have it off, you're still able to move it around freely, until you send it home.

**When did the problem start happening**:

Honestly, probably when mules were added

**Comment by Oyu07** [comment]
> Mulebot
> AI bot interface

![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/c9d5b22f-2b1b-464b-b762-fcdf5b5f8649)
