### ISSUE TITLE
Mr. Changs Sweet and Sour balls not looking too hot.

### ISSUE THREAD

**Issue by ProgrammingGod122** [ParadiseSS13/Paradise#23100]
**Issue Description**: The Mr. Chang's Sweet and Sour Chicken Balls Sprite is broken in the vending Machine

**What did you expect to happen**:  For there to be an actual sprite there. Not all of them

**What happened instead**: I got see every sprite I'm assuming in the Mr. Chang collection.

**Why is this bad/What are the consequences**: Icons should represent what is in them. Not everything.

**Steps to reproduce the problem**: Look at any Mr. Chang's vending machine

Look at a MR. Cheng Vendor

**When did the problem start happening**: When I started the shift.

**Extra information**:

![Broken Sprite](https://github.com/ParadiseSS13/Paradise/assets/40646519/8944a77e-607a-4571-a527-87409207b60d)

**Comment by Mitchs98** [comment]
https://github.com/ParadiseSS13/Paradise/pull/23087

Already have a fix up, thanks for the report though!

**Comment by ProgrammingGod122** [comment]
Are you just waiting for the fix to get merged?

**Comment by ProgrammingGod122** [comment]
> https://github.com/ParadiseSS13/Paradise/pull/23087
> 
> 
> 
> Already have a fix up, thanks for the report though!

Are you just waiting for the fix to get merged?

**Comment by Mitchs98** [comment]
> > #23087
> > Already have a fix up, thanks for the report though!
> 
> Are you just waiting for the fix to get merged?

Mhm! It's already awaiting merge. 'Twas a simple fix.
