### ISSUE TITLE
The radial sliders on tanks do not work. 

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#23114]
**Issue Description**:

Title. they flat do not function 

**What did you expect to happen**: 

Them to function 

**What happened instead**:

They didn't

**Why is this bad/What are the consequences**:

Very bad, can't do tank stuff that isn't default pressure or max

**Steps to reproduce the problem**:

1. get a tank
2. try slider

**When did the problem start happening**:

#23075 most likely

**Comment by ColKev1** [comment]
You can still manually type in a value as a temporary workaround.
