### ISSUE TITLE
Colored lighters become un-colored after usage.

### ISSUE THREAD

**Issue by Sadhorizon** [ParadiseSS13/Paradise#23111]
**Steps to reproduce the problem**:

1. Find the colored lighter
2. Turn it on
3. GREEN
4. Turn it off to double-check
5. STILL GREEN, GIVE ME BACK MY COLOR

**Issue Description**:
After turning a colored lighter on, it looses it's color, becoming green.

**What did you expect to happen**: 
To keep my red lighter.

**What happened instead**:
It's green!

**Why is this bad/What are the consequences**:
Lighter economy is in shambles. (Most definitely unintended behaviour)

**When did the problem start happening**:
not sure

**Comment by Peterrrrrrrr** [comment]
WHy is this open when it has been fixed?

**Comment by Spaghetti-bit** [comment]
Almost certain this is no longer an issue.
