### ISSUE TITLE
Dice bags fit in medical belts

### ISSUE THREAD

**Issue by CinnamonSnowball** [ParadiseSS13/Paradise#23120]
**Issue Description**:
As per title.

**What did you expect to happen**: 
Medical belt to hold medical equipment only, I suppose.

**What happened instead**:
![2023-11-01 18_58_57](https://github.com/ParadiseSS13/Paradise/assets/100448493/aaa40c22-47e3-4b1f-ac08-7e497189eb2c)

**Why is this bad/What are the consequences**:
Muh immursion

**Steps to reproduce the problem**:
Find medical belt, strap an entire bag of tiles into it.

**When did the problem start happening**:
Presumably since they were implemented as a subtype of pill bottles.

**Extra information**:
Thanks, have a Paradise day!

**Comment by Badoniondev** [comment]
As the writer of the "But why is this a pill bottle" i consider this an epic win.
