### ISSUE TITLE
Pet emotes work very haphazardly

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2313]
As a pet:
Nuzzling a human tells you you can't emote "nuzzles [Person]"

Nuzzling yourself produces:
[petname] nuzzles [petname]!
nuzzles [petname]!

I imagine this is a similar issue to what was happening with the broken hands.

**Comment by Spacemanspark** [comment]
Same deal occurs with Posibrains.

**Comment by tigercat2000** [comment]
Yeah, I noticed this, but to be honest, I have no clue why it's happening, nor any idea how to fix it.

**Comment by Crazylemon64** [comment]
Once I've finished the thing I've been working on, I'll take a peek into emote code

**Comment by Crazylemon64** [comment]
The problem: The attack_animal proc of humans calls pet.emote("[pet.friendly] [human]"). This, then will break as the pet doesn't have a [pet.friendly] emote. This means... either going the braindead pet.emote("me", 1, "[pet.friendly] [human]") route, or some other method that doesn't instill more poison in the codebase.

**Comment by Crazylemon64** [comment]
However, I haven't found out why pet's emotes are duplicated. I'll look further into that bit.

**Comment by Crazylemon64** [comment]
Fixed by #2332
