### ISSUE TITLE
Beakers/small beakers sprite problem

### ISSUE THREAD

**Issue by Slrafito** [ParadiseSS13/Paradise#23148]
### Issue Description

When filling beakers with anything and then pouring or transferring its contents, the sprite freezes, showing as if the beaker has something in, but its actually empty. This effect stacks, so if you do it carefully  you could make an empty rainbow beaker... With patience.

### What did you expect to happen

Beakers going back to looking empty after getting rid of its contents

### What happened instead

The phantom of the used chemicals decided to haunt my beakers for eternity (Tourte fixed one, but the rest were doomed).

### Why is this bad/What are the consequences

Confusion from beakers visually. Pain suffering and confusion.

### Steps to reproduce the problem

1. Fill beaker with chemical (anything).
2. Pour it into another container or throw the contents on the floor.
3. Congratulations! Haunted Beaker!

### When did the problem start happening

I noticed at... 3 or 4 hours from this report (Friday 03/11/2023 around 23:30  WET).

### Extra information

Round ID: 37933 (I think)

**Comment by DGamerL** [comment]
Heya! Luckily this is a known bug that will be fixed upcoming monday, as the server will then be upgraded to a newer Byond version that will fix this!

**Comment by DGamerL** [comment]
Fixed with #23186!
