### ISSUE TITLE
You can "chug" a dice bag like a pill bottle, but you don't eat the dice

### ISSUE THREAD

**Issue by Scribble-Sheep** [ParadiseSS13/Paradise#23142]
**Issue Description**:
"chugging" a dice bag will display a message about raising the "pill bottle" to your mouth and swallowing all the pills.
Notably, the dice inside all remain intact and unswallowed.

**What did you expect to happen**: 
Either to not be able to do this at all, or for the dice to vanish so I could do a funny dice swallowing trick.

**What happened instead**:
The dice bag is referred to as a pill bottle, and the game mentions swallowing non-existent "pills"

**Why is this bad/What are the consequences**:
Let me swallow dice, or don't tease me with the silly!

**Steps to reproduce the problem**:
Pick up a dice bag. Drag and drop its sprite onto yours. Check the contents of the dice bag afterwards.

**When did the problem start happening**:
I remember at one point this actually caused the dice to disappear, but sometime between then and when I started playing again recently, it stopped working.

**Extra information**:

**Comment by Sirryan2002** [comment]
fix currently open for this
