### ISSUE TITLE
Running in Space

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#2317]
Today I encountered a very strange glitch.

So strange in fact, that it defies the laws of reality.
Once was a time where if you'd lost footing, you drifted endlessly in space-- unless you were lucky.
Now, we truly do live in the future. A future where your average Vox is just as capable of motion in space as they would be on a floor in the station. Direction changes, loop de loops, no drifting-- no problems.

Well, there is a problem. The fact that you CAN DO THIS. I encountered it twice, both times after running straight out a window into space-- over a catwalk and a lattice with no obstruction. No having been buckled into a chair, having been laid down, having been sick, rejuved-- none of that. Just opened a window in north arrivals maintenance just above the vault and ran out into space to find I could stop on a dime and walk around like it wasn't even a thing. Throwing objects didn't move me so much as an inch, either.

I've tried numerous things to try and fix it. Resting, sleeping, disarming myself, collapsing, running on and back off lattices/catwalks/floors and into space, doing all the aforementioned in the station then going back out into space from a different location to see if it fixed-- nada, no go. I even flashbanged myself.

Spooky!

Also, it seems that running full-speed along walls in space no longer triggers 'slips' like it did before (before you used to slip like 666 times per second, now you don't slip whatsoever).

**Comment by tigercat2000** [comment]
slipping was removed because it was fucking stupid
(and I didn't care enough to reimplement the, like, 20 lines of code)

**Comment by KasparoVy** [comment]
I agree!

**Comment by Spacemanspark** [comment]
Are you sure it's only vox?

**Comment by KasparoVy** [comment]
I only ever muck about in space when I play Vox, and I only ever really use that one race-- I could check, but I've no idea how to reproduce the bug. I'll report back w/ my findings

**Comment by Spacemanspark** [comment]
It's not just vox, saw an IPC that was able to do the same today.

**Comment by KasparoVy** [comment]
Houston we have a problem

**Comment by GelatinousGlob** [comment]
If we don't slip in space what is the purpose of mag boots?

**Comment by tigercat2000** [comment]
Dealing with atmospheric issues, resisting singularity pulls, for two things. Fuck slipping.

**Comment by Crazylemon64** [comment]
This has been unreproducable for a while, should it be closed?
