### ISSUE TITLE
Spoken emotes (say ! emotes) are affected by stutter, auto-accent, slurring, etc.

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#2320]

**Comment by tigercat2000** [comment]
Not a bug.

We don't have a NO_STUTTER flag for languages, like bay does, therefore all languages, including Noise, have stuttering.

**Comment by veganzombeh** [comment]
Surely this isn't intended though. It results in things like "George Melons s-si-g-ghs". It's not speech and doesn't really make sense that it would be slurred/accented/stuttered.

**Comment by tigercat2000** [comment]
Still not a bug, it's an oversight at best. Whatever. I'll fix it. 6 lines of code.
