### ISSUE TITLE
Not serious at all

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#2326]
> You buckle yourself to the chair.
> You need your hands and legs free for this.

I spawned in from ghost as a butterfly. When the shuttle arrived I got on a chair and got that above message. Couldn't unbuckle from it afterwards.

Also when I died I had no ghost name. Kind of sad

**Comment by tigercat2000** [comment]
it's because of the abysmal structure-climbing code, everyone gets it

**Comment by Plotron** [comment]
Yeah, and when I am in a rolling chair (as a human, for instance), I cannot rotate myself just by clcking on a nearby tile (I have to rotate the rolling chair manually, just as with normal chairs and armchairs).

We've lost a special feature here! It's what made rolling chairs stand out!
