### ISSUE TITLE
Set Opacity in Atom/Destroy()

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2329]
@PJB3005 

Since you're most fmailiar with lighting, wanted to ask you about this.

In our Atom/Destroy, we have set_opacity(0): https://github.com/ParadiseSS13/Paradise/blob/master/code/game/atoms.dm#L33

However, correct me if I'm wrong, but this is essentially redundant/pointless when atom/movable/Destroy() essentially does the same thing, correct? https://github.com/ParadiseSS13/Paradise/blob/6f69d256235c95048cc735385fe437908f66baf3/code/modules/lighting/lighting_atom.dm#L43

**Comment by PJB3005** [comment]
Yep, looks like it's redundant to me, probably a relic from DAL.

**Comment by Fox-McCloud** [comment]
@PJB3005 

Thanks so much!
