### ISSUE TITLE
Human skin tone

### ISSUE THREAD

**Issue by BorisLemons** [ParadiseSS13/Paradise#2333]
Human skin tone seems to be borked, regardless of the value set up in character set up, it will appear as default. This is independent of slot used.

**Comment by tigercat2000** [comment]
Hm. This was probably fixed by #2323, try again after server patches.

**Comment by BorisLemons** [comment]
The bug has not been resolved.

**Comment by tigercat2000** [comment]
Can't reproduce locally as of commit c2ffc3196320e

We probably still haven't patched the main server.

**Comment by Fox-McCloud** [comment]
likely fixed; please re-report if this is an issue.
