### ISSUE TITLE
LINDA: Too Many Active Turfs and Excited Groups 

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2336]
Simply put, at round start there's something like 2000-3000+ active turfs and around 30+ excited groups; this shouldn't  be the case as the map starts out in a relatively default state---while there will be some areas this is unavoidable (such as the server room or the plasma+N2O mix tanks), most of the active turfs are NOT in these areas.

This is likely a mapping errors due to custom values that are set when they shouldn't be.

Just a basic exploratory examination by me seems to reveal the vast vast majority of these are occurring because of z-level 5.

Furthermore, this is happening: 

![turfs](https://i.gyazo.com/a800ae2a72b98a52cb3763008e3dec6e.png)

@tigercat2000 

Relevant PRs: 
https://github.com/tgstation/-tg-station/pull/10593
https://github.com/tgstation/-tg-station/pull/10864
https://github.com/tgstation/-tg-station/pull/10669
https://github.com/tgstation/-tg-station/pull/10785

**Comment by CrAzYPiLoT-SS13** [comment]
Should be closed afaik?

**Comment by Fox-McCloud** [comment]
There's still a ton of active turfs on the away missions, technically.

**Comment by FalseIncarnate** [comment]
Is this still an issue? If not, please close.

**Comment by Fox-McCloud** [comment]
It is, because of how awful the away missions were designed.
