### ISSUE TITLE
The random_hair_style function seems to always choose "Bald"

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2344]
To reproduce:
- Make a human with hair
- Apply hairgrownium
- Greytidification process 33% complete

**Comment by veganzombeh** [comment]
I'll need to double check this, but I believe [this line](https://github.com/ParadiseSS13/Paradise/blob/6c1208e18f9ed8c3b6ef2b74e40417dbdbf3ebe9/code/__HELPERS/mobs.dm#L29) to be the problem. It should be checking for species.name.

**Comment by tigercat2000** [comment]
@veganzombeh species is an arbitrary variable in the proc arguments, it's not a datum, it's text

**Comment by veganzombeh** [comment]
Fuck I'm stupid, I assumed this was a mob proc.

**Comment by veganzombeh** [comment]
Okay, in that case [this](https://github.com/ParadiseSS13/Paradise/blob/c7760a20198258503aad585f48dd20e556e3573e/code/modules/reagents/newchem/other.dm#L230) should be using the species name as the argument, rather than the datum.

**Comment by tigercat2000** [comment]
indeed

**Comment by Crazylemon64** [comment]
I'm pretty sure this is fixed
