### ISSUE TITLE
Turning off pull mode with Ctrl+click NOT functional (Initiating pull mode works fine)

### ISSUE THREAD

**Issue by alexpkeaton** [ParadiseSS13/Paradise#2345]
First time posting on the forums, so I apologize if I am not reporting this correctly or if I missed this being mentioned elsewhere. In the last 24 hours, something in the user interface has changed which has caused the deactivation of "pull mode" using Ctrl+click on the object being pulled to stop working. At least one other player has confirmed this occurring in his client as well. Oddly, an object can still be pulled initially by using Ctrl+click, you simply cannot release it. To deactivate pulling an object currently, the GUI pull button must be clicked or other environmental/object factors that naturally deactivate pull mode must occur.

Thanks for looking into this.

**Comment by Fox-McCloud** [comment]
@tigercat2000

**Comment by FalseIncarnate** [comment]
I normally stop pulling by hitting the delete key (not backspace, the one by the insert button on full keyboards).

Try using that one if you can, as it is specifically bound to the "stop pulling" action even without Hotkey mode.

**Comment by tigercat2000** [comment]
broken since before I touched it

**Comment by TheDZD** [comment]
Ctrl+click pull never worked like this, it has always been delete to stop pulling.

**Comment by Aurorablade** [comment]
no actually it did work like that then it suddenly STOPED working like it....i just never made a big deal about it to myself to report and/or fix it...
