### ISSUE TITLE
Z-levels are bugged

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2347]
Z-levels are not designed to be controlled, when it was in a box, it was bugged, when it is in a torus, it is still bug...

So currently, I am at z-level 4, if i go north, i enter z-level 4, if i got south, i enter z-level 4, if i go west, i enter z-level 4, and if i go east, i enter z-level 4, which means another z-level also goes to z-level 4.

it's not the first time a z-level goes to it's own z-level, but it's the first time all directions goes.

**Comment by Fox-McCloud** [comment]
guessing this has been resolved---z-level behavior is pretty consistent now, from what I've noticed.
