### ISSUE TITLE
Blurry eye overlay due to eye damage cannot be removed in some cases.

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#2350]
If your eyes are damaged enough that you get the blurry eye overlay permanently, it cannot be removed via meds or surgery. 

http://nanotrasen.se/forum/viewtopic.php?f=2&t=6050

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by veganzombeh** [comment]
This appears to be the case for the shortsighted and blind sdisabilities, which, as far as I'm aware, there's no way to remove since eye surgery was removed.

**Comment by tigercat2000** [comment]
It's tricky to solve, because as-is, organ repair surgery doesn't support anything like this.

**Comment by Fox-McCloud** [comment]
This problem has been in since I returned to Paradise back in August of 2014--for some reason, eye damage will end up getting set to "null" instead of 0, which means the eye overlay will literally never clear under any circumstances.

**Comment by veganzombeh** [comment]
It may not be the same issue, then, there have definitely been ahelps about [this message](https://github.com/ParadiseSS13/Paradise/blob/660f1d22a2752e8ec20eaffb3b73c8286c270a0d/code/game/machinery/adv_med.dm#L516) recently, with no apparent way of curing it.

**Comment by Alex6511** [comment]
@veganzombeh Same bug
