### ISSUE TITLE
You can equip a hardsuit helmet without modifying it to fit your species.

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#2354]
This is relatively minor, but

1. Get a hardsuit modified to fit your species.
2. Attach a non-modified helmet to that hardsuit.
3. Equip the hardsuit. The helmet *will not* be deployed automatically.
4. Right-click the hardsuit, select "Deploy Helmet".
5. You are now wearing a hardsuit helmet that your species should not be able to wear.

**Comment by KasparoVy** [comment]
Does it use the sprite of the helmet's current state (human as default or for example unathi if it was unmodified) or does it automatically use the sprite appropriate for the species while still being unmodified?

**Comment by veganzombeh** [comment]
The sprite on that character is correct, the sprite of the item is wrong.
