### ISSUE TITLE
Morph with Vox allows Nucleation Hairstyles to be chosen. 

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#2357]
![e0u58rt](https://cloud.githubusercontent.com/assets/13933611/10462062/8335cb3a-71d4-11e5-87e8-e635b898eb2c.png)

As in the picture, brought to attention by Stobacrio. He has Morph and when it gets to the hairstyle selection, he can pick Nucleation hairstyles, they don't show a sprite of course but still the option remains.

Unsure if this happens for all races.

**Comment by veganzombeh** [comment]
IC in github. Ban he.

This isn't specific to just Nucleation, as I see Antennae there, which is Wryn-only. I guess it doesn't doesn't check for species anywhere.

**Comment by KasparoVy** [comment]
@Fox-McCloud This was fixed ages ago but I didn't notice this issue on the Git and forgot to reference it, oops!
