### ISSUE TITLE
Photos can't been seen

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#2358]
As above, I've noticed that since recently photographs are always 'too far away' to view, even on the same tile or in your hands.

**Comment by TheDZD** [comment]
Noticed this problem as well, in one round the HoS tried looking at a photo and experienced this bug. He then placed it on the ground when asked, and still could not see it, however as a ghost I could see it by shift-clicking the photo while I was on the same tile as the HoS.

**Comment by tigercat2000** [comment]
i'm pretty sure this was because of my examine overhaul, headset examine doesn't work either
i'm guessing in_range(user, 0) does not actually return true if it is inside of them

**Comment by Plotron** [comment]
Not sure what person DZD is talking about, but I've experienced this bug once or twice.
It doesn't always happen, though (I think).

**Comment by mikecari** [comment]
Yeah this glitch is still a thing and really common.

**Comment by Tastyfish** [comment]
Probably related to stack examining not showing item count as well.
