### ISSUE TITLE
Syndicat

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#2360]
With the removal of the traitor station came the unexpected removal of Syndicat, can we have her placed at the Nukkie base with syndifox for the players who want to respawn as her?

**Comment by Spacemanspark** [comment]
Yes please.

**Comment by TheDZD** [comment]
You can never have enough cats, until you have a catsplosion, and then your station has a serious problem and the crew is likely going to start a tantrum spiral as soon as one cat dies.

**Comment by Plotron** [comment]
I miss Syndicat.

**Comment by NTSAM** [comment]
Syndicat or riot
:angry:
