### ISSUE TITLE
Cyborgs bumping things moves them 2 tiles

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2361]
To reproduce:
* Be a glorious, synthetic, cyborg
* Push a pushy thing
* Egads! It moved twice as far!

**Comment by Spacemanspark** [comment]
This isn't intentional?

**Comment by TheDZD** [comment]
This has happened for as long as I've been around, I think it's intentional.

**Comment by tigercat2000** [comment]
even if it's not intentional
_movement push code_
**crying intensifies**

**Comment by Crazylemon64** [comment]
It's a piece of copypasta'd code that calls the parent, which also does the bumpy moving thing. It wouldn't be that painful of a fix, but precedent holds precedence.

Looking at the Bump() proc of robot.dm:
In the middle of it, it does a parent call to silicon/Bump(). The function it calls looks like a carbon-copy of itself, down to the comments, making me think this was a not-too-careful copypasta

**Comment by TheDZD** [comment]
Huh, you're right. It seems like it copypasta's the silicon Bump() inside of a spawn(0), then calls the parent proc, which is the silicon Bump().

**Comment by Crazylemon64** [comment]
It wasn't a carbon copy, I made a blunder reading my editor. Nonetheless, it looks like the silicon/Push() also copies a bit with a now_pushing that always sets now_pushing to 0 or null before the end of the function. This might need to be tweaked so that it's more sensical, as I get the idea now_pushing is a guard against doing multiple pushes at once.
