### ISSUE TITLE
Weapon/module seems to be unused except for power module

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2364]
Looking at the code where the power_module is defined, it's got a nice family of other weapon/modules that, as far as I can tell, would do just fine expunged from the codebase. Are they fine just being torn out and the APC electronics being placed in the APC's file?

**Comment by Fox-McCloud** [comment]
Could you clarify what you mean or provide a link, please?

**Comment by Crazylemon64** [comment]
Paradise/code/game/objects/items/weapons/modules.dm

There's a whole bunch of modules defined, but the only references to weapon/module I see in the entire codebase are either in the APC class, in the map, or in the vendor's starting inventory.

**Comment by Fox-McCloud** [comment]
That would be fine.
