### ISSUE TITLE
Clients being moved to heads upon decapitation even after ghosting.

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#2367]
This is slightly vague as I don't have details of the exact circumstances it occurs in, but there appears to be an issue with clients being moved into decapitated heads upon decapitation even if the client had previously ghosted.

**Comment by Fox-McCloud** [comment]
Organ code rewrite strikes again...

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/brain/brain_item.dm
When the head is decapitated, it calls removed() of all its internal organs. In the transfer_identity proc, called by the removed() of the brain, the ghost is forced into the brain without a check, given this problem. WHERE there needs to be a check for a ghost, I'm not sure.

**Comment by veganzombeh** [comment]
It's attempting to transfer the identity of `owner

**Comment by Crazylemon64** [comment]
Is this still a thing?

**Comment by Crazylemon64** [comment]
This is no longer a thing, is it?

**Comment by veganzombeh** [comment]
It looks like it's been fixed. I haven't played in a looong while though so I can't confirm that.

**Comment by Crazylemon64** [comment]
Yell if this ever happens again
