### ISSUE TITLE
Table duping

### ISSUE THREAD

**Issue by holyass** [ParadiseSS13/Paradise#2368]
early morn of 10/14/15 I found a bug that let you copy table over and over, and make you have endless tables, it work so far KNOWN are  wood tables and Reinforced Table  and maybe the other two type too, Glass and just a table. A admin knows about it.

**Comment by Spacemanspark** [comment]
This is pretty vague, and doesn't explain how to do it, so the coders can fix it...

**Comment by holyass** [comment]
ok, here how to do it, One. be a borg, two have two table parts three get your graber, four. grab one table, five. SPAM click the other table part, six ????? seven. endless tables For the table god!

**Comment by Spacemanspark** [comment]
Oh, ya, I think this was already reported.
But ya, details like that help a lot.

**Comment by Crazylemon64** [comment]
Ah, yes, I might(?) have found the source of the issue. Though, I don't really know how qdel behaves. When the gripper does attack_self, it calls the attack_self of the item it holds. With the table parts, once it's done, the table parts call qdel on themself. However, if they're held by the gripper... I'm not sure what happens with that reference. It looks like it might be dependent on the drop_item call actually working, so all the references are gone(?). Anyways, don't take any of this advice as valid, someone more versed in the GC system should probably look into this:
@Fox-McCloud , could you give this a look?
