### ISSUE TITLE
Polly

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#2379]
polly does not drop items it takes when killed, making them disappear.

**Comment by CrAzYPiLoT-SS13** [comment]
Hm, it has the code for that, but it seems to delete the item as soon as it drops it. I can remove the problematic line, but it will make the item linger in the parrot's inventory, which can be bad if it's rejuvenated by admins.
Exact code:
    if(held_item)
	    held_item.loc = src.loc
	    held_item = null
@Fox-McCloud

**Comment by monster860** [comment]
Poly is soooo annoying.

**Comment by Tastyfish** [comment]
This bug was resolved at some point.
