### ISSUE TITLE
PDA power monitor

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#2380]
to use the PDA power monitor you first need to use a computer. the grid power option on the PDA has a copy
![pda power](https://cloud.githubusercontent.com/assets/12041669/10561146/547fc608-74ed-11e5-82e7-30501f67b778.PNG)

**Comment by Markolie** [comment]
There's two monitors with that name on the map, as such you can pick both of them.

**Comment by orelbon** [comment]
@Markolie you forgot that you need to use a computer to vew it on the PDA, and sometimes it wont work at all

**Comment by Markolie** [comment]
Well, "sometimes it won't work" isn't really descriptive enough to fix an issue.

**Comment by orelbon** [comment]
the actual problem is that you need to use a power monitor computer to see it on your PDA, and even that wont work sometimes, i m not a coder i cant tell you what could possibly cause it

**Comment by Markolie** [comment]
That's intentional. A PDA can't magically read the station's power grid when it's not connected to a node.
