### ISSUE TITLE
Atmos pipes disappear when unwrenched.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#2382]
Something like 90% of the pipes I unwrench disappear even when they are taken one by one from the very end. I believe pumps and switches disappeared too. In a few scenarios with a single pipe wrenched and unwrenched it wouldnt disappear.

**Comment by Fox-McCloud** [comment]
@Markolie 

Very peculiar.

**Comment by Markolie** [comment]
Didn't do this before. Perhaps it's caused by the GC'ing?

**Comment by TheDZD** [comment]
It's likely either pipes or #2373.

**Comment by tigercat2000** [comment]
i highly doubt mine broke it, it literally only affects recycling code

**Comment by Fox-McCloud** [comment]
Ahhh, I see.

Deconstruct doesn't properly de-reference pipes, so it puts them on the turf, then immediately deletes them.
