### ISSUE TITLE
Juggernauts cant smash through walls

### ISSUE THREAD

**Issue by mikecari** [ParadiseSS13/Paradise#2389]
Juggernauts can only smash through the outer wall and not the girder. Seems unintentional

**Comment by tigercat2000** [comment]
It's been this way since forever+1, I doubt it's unintentional.

**Comment by mikecari** [comment]
I'm not sure though, on /tg/ and other places the code is based on, they CAN smash through girders.

**Comment by TheDZD** [comment]
They have environment_smash = 2, which should mean that they can break walls but not reinforced walls.

**Comment by tigercat2000** [comment]
was fixed by #3863
