### ISSUE TITLE
Bluespace tomatoes (And any fruit with spatial trait) only work on secure tiles.

### ISSUE THREAD

**Issue by Mijhead** [ParadiseSS13/Paradise#2394]
See title.

How to replicate: Grow bluespace tomato, squish it in hand/throw it at the tile you stand on. It teleports. Repeat but on space tiles. It does not teleport.

**Comment by KasparoVy** [comment]
Don't really think this is an issue. With space tiles, there is nothing solid beneath you to stop the tomato in its flight-- so it makes sense that it wouldn't trigger a teleportation
It'll just keep flying on through nothing

**Comment by Fox-McCloud** [comment]
Probably only works on simulated turfs; if that's the case, then this is probably very very much intentional.

**Comment by Mijhead** [comment]
Squishing it in the hand doesn't involve throwing it, or throwing it at anything, though. Squishing is done by clicking on it with harm intent while it's in your hand, for reference.

**Comment by fludd12** [comment]
Is this still an issue?

**Comment by Anticept** [comment]
This is no longer an issue. Tested with /obj/item/weapon/reagent_containers/food/snacks/grown/tomato/blue/bluespace . This worked fine.

Note that with new botany, this might even be relevant anymore. I have no idea. I just know it worked in space for me.
