### ISSUE TITLE
Manual T-Valves mixing air like manifolds

### ISSUE THREAD

**Issue by bfilia** [ParadiseSS13/Paradise#2400]
The air pressure is being mixed between connecting pipes despite one of the sides being shut off. Is this intentional?

**Comment by Tastyfish** [comment]
Just looked at this: there is literally no code in the tvalve object to make it actually valve anything. lol. It's basically a 3-way manifold with a couple led's glued on currently.

**Comment by Tastyfish** [comment]
Oh, I figured out why they're broken, making fix.
