### ISSUE TITLE
Can't read/inspect ID cards

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#2401]
They're always "Too far away", just like the problem with reading photos that was mentioned here some time ago.
Shift+Click (Examine) is broken for ID cards, it seems.
This means you can no longer see the default photo and blood group.

**Comment by veganzombeh** [comment]
This is probably caused by the same thing as #2358.

**Comment by Plotron** [comment]
The bug is still there. You can read welding fuel and probably other things, but ID still doesn't work.

**Comment by Fox-McCloud** [comment]
I doubt the server has patched yet.

**Comment by Tastyfish** [comment]
Yeah the server just hasn't been updated yet this week.
