### ISSUE TITLE
Traitor pickpocket gloves does not work as intended

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#2402]
Description reads: "A pair of sleek gloves to aid in pickpocketing, while wearing these you can see inside the pockets of any unsuspecting mark,  loot the ID or pockets without them knowing, and pickpocketing puts the item directly into your hand."

But the item spawns on the ground under the target

**Comment by tigercat2000** [comment]
Not feasible to fix from the way -tg-'s stripping works.

**Comment by Regen1** [comment]
Then either the gloves should be removed, reworked or the desc at least changed.

**Comment by tigercat2000** [comment]
As-is they allow you to strip any item with no message, that's all they do.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Do they allow you to put items onto someone without a message, as well?

**Comment by tigercat2000** [comment]
@Fox-McCloud I don't think so, but it could be added rather easily

**Comment by Fox-McCloud** [comment]
I believe old pickpocket gloves had that; it wasn't for any item, just certain slots.

**Comment by KasparoVy** [comment]
when chuck lefuck takes the captain's hat and swaps it for clown wig without him knowing

**Comment by TheDZD** [comment]
They used to allow you to strip or place anything in/from either pocket or the ID slot without generating a message.
