### ISSUE TITLE
Odd cryo bug.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2403]
Multiple people heading into the same cryo pod at the same time, or placing people into cryo pods, or both at the same time, will allow multiple people to enter the same cryopod. If one person exits the pod, it shows the open cryo pod state and allows another person to climb in, or put more people into it.
On the bright side, this means unlimited storage.

**Comment by TheDZD** [comment]
This likely causes bodies in the cryo pod to never get despawned.

**Comment by KasparoVy** [comment]
clown car cryopods ftw

**Comment by veganzombeh** [comment]
It looks like all this needs is a `if(occupant) return` after the `do_after`s. I'd do it myself but I'm away at the moment.
