### ISSUE TITLE
Dead Mobs: Still Screaming

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2406]
Dead mobs can still scream.

**Comment by LufgtHuron** [comment]
Haha wow, this is reported only now? Last time I played (maybe two months ago) I noticed this when I was a chef and could kill a monkey and then keep hitting it for infinite screams.

**Comment by Crazylemon64** [comment]
Should unconscious mobs scream, too? I've got a fix ready that depends on the answer to that question.
