### ISSUE TITLE
AI's in mechs are fairly bad.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2411]
-AI's can't utilize anything besides the repair droid in a mech.
-AI's are instantly deleted if the mech dies.

**Comment by Fox-McCloud** [comment]
The latter is intentional, so AI's can just yolocontrol mechs with impunity when they're rogue.

**Comment by TheDZD** [comment]
Not certain if being unable to use a repair drone is intentional or not, although I would assume it to be non-intentional.

**Comment by Spacemanspark** [comment]
Huh?
No, uh, the only thing they CAN utilize is the repair drone.

**Comment by Markolie** [comment]
@Fox-McCloud This can be closed. When you're an AI in a mech, you need to use middle mouse click to interact with the mech (i.e. fire).
