### ISSUE TITLE
Space Pods Occupant Error

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#2412]
We seem to have a rampant error with Space Pods where if someone gets in them, and then precedes to get out, they get 'stuck' in the pod. They do exit it, and can move about, but the 'occupant' variable gets stuck with them in it. There are two potential causes to this error: 1) when someone exits the pod, it does not change to variable 'occupant = null'; 2) when someone switches to the passenger seat, variable 'occupant2', the variable 'occupant' does not revert to 'occupant = null'.

As a note, included bugs with this do include anyone still registered to variable 'occupant' are still affected by the pod. If the pod were to self-destruct or be destroyed, then whoever is still registered to 'occupant', regardless of where they are, will be teleported back to the pod location (as it ejects them to the pod), and gibbed (as the pod has now exploded). This has happened to someone as they had accidentally left the pod blocking a door against cultists. When they blew it up (as there was no other way to move it), the person who was still registered to 'occupant' received a message saying the pod was critical and had 10 seconds to evacuate. It then proceeded to explode, and teleported him back to it, gibbing him, even though he was on station, and the pod was at telecomms in the medical shuttle.

**Comment by TheDZD** [comment]
Spacepod code is horrifying.
@tigercat2000

**Comment by tigercat2000** [comment]
ugh i'm working on something now
It's very difficult to fix fucking spacepod code, because only players ever manage to replicate bugs I know fucking exist.

**Comment by Plotron** [comment]
Not sure if it's related, but there was a bug where the pilot seat slot got bugged and was inaccessible. Had a co-pilot (I called him "Marine") exit the pod after me. Not sure what exactly happened, but I could only enter as passenger after that. It effectively grounded the security space pod.

Not to mention that I locked the doors from the passenger seat and I couldn't unlock them.
