### ISSUE TITLE
mechanical organ surgery is borked

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#2413]
nanopaste does nothing but show the "you don't know what to do with the nanopaste" message, welder closes the incision, cables do nothing too I think. Had this happen several times with mechanical hearts so far.

**Comment by Crazylemon64** [comment]
Were these mechanically assisted organs, or fully mechanical? If they were merely assisted, the standard organ surgery is the way to go.

**Comment by pinatacolada** [comment]
fully mechanic I think. what's funny is that mitochloide works on them. Anyways, I tried both normal and mechanical surgeries and neither worked, and in fact. trying the normal surgery gives no text dialogue, but shows a progress bar.
