### ISSUE TITLE
Strange seed fruits still contain nutriment as opposed to plant matter

### ISSUE THREAD

**Issue by Mijhead** [ParadiseSS13/Paradise#2416]
See title.
Related; Plant matter doesn't function as nutriment for yield modifier purposes.

**Comment by FalseIncarnate** [comment]
Oversights on my part, will look into fixing them soon.

Might make strange seeds pick from either nutriment, protein, or plant-matter, to make them more "exotic".

**Comment by Keilden** [comment]
Oyeah meat fruit
