### ISSUE TITLE
PDA looks weird in the messaging screen.

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2417]
Probably my fault, whoops.
Applies to normal and retro themes, see:
![heth](https://puu.sh/kWq9X/45ae8112b1.png)
![andheth](https://puu.sh/kWqau/bc8883e990.png)

**Comment by CrAzYPiLoT-SS13** [comment]
This is most likely caused by the string of text for the name and job being too long from the looks of it. Wouldn't know how to fix it tho, as I never messed with those template thingies or whatever.

**Comment by Plotron** [comment]
Yeah, youI broke it, now I'm getting used to it.

Mildly annoying and confusing.
