### ISSUE TITLE
You can buckle multiple people to the same thing.

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2418]
This would be awesome, if it worked properly- buuuut it actually just means whoever the last buckled person is is the only one that can unbuckle.

**Comment by taukausanake** [comment]
Does it? If you aren't restrained can't you just unbuckle yourself? Or resist out of it? I think I've been buckled with someone in the pods before and managed to get out myself

**Comment by veganzombeh** [comment]
You can technically unbuckle yourself @taukausanake, but only if you're the most recently buckled, so you have to re-buckle yourself first.
