### ISSUE TITLE
Jumping to people randomly causes heap corruption

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2424]
Title, it's the reason people crash.

**Comment by tigercat2000** [comment]
What makes you think that, exactly?

**Comment by Robertha89** [comment]
Because it is an Event ID 1000 Application error using the Event Viewer to see this.

**Comment by Spacemanspark** [comment]
I believe this is more of a Byond issue.
I downgraded to 508.1292 and I never crash anymore.

**Comment by Fox-McCloud** [comment]
>I downgraded to 508.1292 and I never crash anymore.

I've generally found this to be the most recent version that's the most stable.

**Comment by Tastyfish** [comment]
This has been probably moot for multiple major versions of BYOND now.
