### ISSUE TITLE
You keep your Change Monitor verb as a Vox Raider

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#2429]
As it says in the title, pretty much.
Here's what went down.

- Have an IPC character with Be Vox enabled.
- Get lucky enough to be chosen for Raider.
- Check your verb tabs.
- You'll still have your Change Monitor verb.

Probably worth noting that instead of screens being listed it lists Voxen haircuts.

**Comment by KasparoVy** [comment]
Professional Vox barbers straight out the shoal

**Comment by Crazylemon64** [comment]
Yaya I is so stylish I is changing hair as I speakses! Is goods!

**Comment by Spacemanspark** [comment]
Ya ya is become rockstars now! *change hair and steal guitar*

**Comment by NTSAM** [comment]
At least we can't have bird-TVs.

**Comment by Tastyfish** [comment]
This also happens for IPC's that get selected as a nuke and switched into a human.

**Comment by Crazylemon64** [comment]
Do I HAVE to fix this bug... I know HOW to, but it's hilarious...

**Comment by Spacemanspark** [comment]
I'd say "We should keep it.", but then I'd be a hypocrite.

**Comment by Robertha89** [comment]
We got a command called C.S.A - User and C.S.A - Admin, that basically allows you to modify your appearance, if you choose species IPC, or Vox Armalis, you get their unique verbs, and you keep em even if you change, so this is something that should be fixed.

**Comment by TheDZD** [comment]
Re-opened as #3143 was reverted.
