### ISSUE TITLE
Miming var does not affect speech.

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#2430]
This has been an issue for a *long* time, I've just realized it has never been reported.

`miming = 1` does not prevent speech. This means the mime can speak without using the 'Speech' verb, and still create invisible walls while speaking.

**Comment by Robertha89** [comment]
Intended, the mime is a master mimer.

**Comment by KasparoVy** [comment]
What's it SUPPOSED to do, anyway?

**Comment by veganzombeh** [comment]
The mime spawns with `miming = 1`. This prevents them from speaking. The mime can use the `Speech

**Comment by Plotron** [comment]
I like talking mimes.

**Comment by tigercat2000** [comment]
should make it replace all text with bright red "I AM A MIME WHO TALKS, SHOOT ME, I AM A LEGIT KILL."

**Comment by Spacemanspark** [comment]
Yes please, @tigercat2000

**Comment by veganzombeh** [comment]
@Plotron Mimes *are* supposed to be able to talk, they normally just have to use the Speech verb first, which sacrifices their ability to make invisible walls.

**Comment by TheDZD** [comment]
Mimes, talking? THEY ARE A DISGRACE TO MIMEKIND AND MUST BE DISPOSED OF!

**Comment by tigercat2000** [comment]
@Fox-McCloud are you sure this is fixed?

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/3736
