### ISSUE TITLE
Being flashed as pAI makes people unable to walk trough you

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#2435]
When flashed in mobile form mobs become unable to pass trough pAI's in mobile form and vice versa.
Folding and unfolding doesnt fix this

**Comment by Crazylemon64** [comment]
This is fixed, right?

**Comment by fludd12** [comment]
No recent news on if it's fixed, and pAI density is being addressed in a recent issue.

**Comment by Crazylemon64** [comment]
I'm not able to flash pAIs with either the area mode or directly hitting them with flashes. Closing, lemme know if this is still a thing.
