### ISSUE TITLE
Flash Powder recipe

### ISSUE THREAD

**Issue by lolzyking** [ParadiseSS13/Paradise#2436]
Flash powder's recipe calls for the reagents Sulphur, Aluminum and Potassium.

Sulphur is however spelled as sulfur in the code, could some code savvy fix this spelling error in the recipe?

**Comment by NTSAM** [comment]
b-but my Spessmerican spelling!

**Comment by veganzombeh** [comment]
It's always called `sulfur` in the code. I can't see any mention of Sulphur, where's the spelling error?

**Comment by lolzyking** [comment]
When I was trying to make flashpowder yesterday, I was unable to with current recipe on the wiki
I assume this is because the recipe for it asked for Sulphur, and not sulfur

could someone check the recipe for flash powder in the code then? to see if thats where a spelling error is, or if the wiki is just wrong

**Comment by veganzombeh** [comment]
The spelling mistake is just on the wiki, not in the code. It also requires chlorine, is that on the wiki?

**Comment by TheDZD** [comment]
Yeah, as @veganzombeh said, all references to the chemical in the code spell it as "sulfur," more likely than not the wiki might just be missing chlorine in the chemical's recipe.

**Comment by lolzyking** [comment]
thanks wiki was just wrong
