### ISSUE TITLE
Slimes cause toxin damage to IPC's

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#2437]
Being "absorbed" by a slime will over time deal toxin damage to IPCs if not wrestled off.

**Comment by Fox-McCloud** [comment]
When @FalseIncarnate resurrects his one PR, this issue will be corrected

**Comment by FalseIncarnate** [comment]
Soon.(tm)

**Comment by Crazylemon64** [comment]
I'm going through the huge buffer of issues we have and seeing if I can knock out ones we've already taken care of.

Fixed by #2578
(if I'm not mistaken)
