### ISSUE TITLE
2 Atmos Related bugs [Station Bounced Radios] [Turbine]

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2442]
Atmos techs cannot set station bounced radios to Engineering channel.

The gas pump outside the Turbine room to the gas injector has no power and cannot be turned on.

**Comment by TheDZD** [comment]
@tigercat2000 Is the first issue intentional or a not.

**Comment by tigercat2000** [comment]
@TheDZD doubt it was caused by my radio changes, I'm guessing engineering radio channel was locked to engineering access, which atmos techs don't have- they just have lobby access.
