### ISSUE TITLE
[Exosuit Fabs] [Robotics] Cyborg right legs disappear from menu

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2444]
Seems after using the "All items" option too many times in a row the exosuit fab just 'forget's it can make cyborg right legs. Both are affected and doesn't seem to matter how much materials are in them. Seems to be after 5 full borg bodies are made it just doesn't want to make right legs anymore. Only way to fix it at the moment is to disassemble and reassemble the exofab.

EDIT: AT the time this was happening the exofab was fully upgraded with bluespace and finto items and the best laser.

**Comment by Davdichan** [comment]
I've seen this happen a lot, and it's been happening and off for a year.

Reassembling the machine is a guaranteed fix. Resyncing the machine has on occasion also worked to bring the legs back. As for what is causing it? I don't know, it some how gets clipped off the list of items, and it's always the right leg, never any other item in any other category.

**Comment by Ar3nn** [comment]
Re-syncing the fabs always works for me as a mechonerd, but I don't normally make as many borg bodies as a typical mechonerd, since I religiously enforce the paperwork, and lots of people dont want to go through the effort. Maybe I've just always been lucky. But I have noticed it, but figured it too minor and irregular to bother with.

**Comment by Crazylemon64** [comment]
It's happened with the durand armor plates, too. Something with the lists not acting right, particularly the final elements

**Comment by Anticept** [comment]
I've never seen this occur, nor heard anyone say it happens in the past 6 months.

**Comment by Ar3nn** [comment]
Yes.

**Comment by Taaketa** [comment]
I don't believe this is an issue anymore.
