### ISSUE TITLE
Pun Pun: No Suit

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2454]
Somewhere along the line Pun Pun lost his suit and is now naked.

**Comment by Spacemanspark** [comment]
Perhaps it was removed to be more in line with /tg/.
Or an accident.
Either way, it'd be nice to re-add it.

**Comment by NTSAM** [comment]
That's why Pun Pun looked a bit off.

**Comment by Plotron** [comment]
I never cared for Pun Pun after he got 'accidentally stripped'.

**Comment by HereticChurch** [comment]
His outfit is still around somewhere. I know I can spawn it and wear it as a human. (Its amusing because its still the same size so it looks ridiculous.)
