### ISSUE TITLE
/Hostile/ Mobs are invincible

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#2463]
@Aurorablade 
I had 4 crew bashing me with everything they could and I wasn't taking any damage. Even had guns fired at me.

**Comment by Spacemanspark** [comment]
I sense a perfect opportunity.

**Comment by NTSAM** [comment]
[Endless deconstruction intensifies]

**Comment by Earthdivine** [comment]
Never mind, its all mobs

**Comment by tigercat2000** [comment]
don't you mean all simple_animals

**Comment by Spacemanspark** [comment]
Oh God.
This is terrifying.

**Comment by Earthdivine** [comment]
No, only tried it with anything with /Hostile/. Lemme change it.

**Comment by Aurorablade** [comment]
@Earthdivine @tigercat2000 I AM SO SORRY I AM SOOO SORRRYYYY
