### ISSUE TITLE
Invincible Goliath and Hivelord

### ISSUE THREAD

**Issue by Afelirick** [ParadiseSS13/Paradise#2464]
Goliath had two miners beating on it with kinetic accelerators, it even exploded a few bits of gibtonite ore that were practically on top of one another.   A few minutes afterward I encountered a hivelord, per standard hivelord procedures I attempted to bash it's little flighty bits while saving my shots for the hivelord itself - the flighty bits.. were invincible.  I retreated before I could discovered if the hivelord itself was or not, but I imagine it is.  If I can update these I'll do so if I encounter the rest of the asteroid enemies.

**Comment by TheDZD** [comment]
That was a problem with the last patch, all simple_animals were immune, already fixed.
