### ISSUE TITLE
Swarmers don't destroy Orion Trail machines when deconstructing them

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2471]
Can be scummed to produce endless amounts of metal.
Seems to also occur on the Mining shuttle console and the Identification computer.

**Comment by Keilden** [comment]
Several consoles have that problem.

**Comment by Crazylemon64** [comment]
I'm almost certain it's related to that runtime that happens when the text2path on the circuit returns null: Looking through the code, the machines that have that problem have the actual path, rather than the path in string format. Looks like it needs to be standardized in order for swarmers to behave consistently with them.

**Comment by Fox-McCloud** [comment]
We really need to just make all circuits use a non text path.
