### ISSUE TITLE
Swarmers can eat Circuits

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#2474]
After disassembling a console you can then eat the ciruit for resources

**Comment by Earthdivine** [comment]
@Aurorablade

**Comment by Fox-McCloud** [comment]
Pretty sure this is intended.

**Comment by Earthdivine** [comment]
>Ctrl Click on a machine to dismantle the machine (Requires 10 seconds). Some machines are >obviously protected against this. The circuit board for the machine will drop on the floor, and >swarmers can't eat them.

This is in both our pull and TG's, and all their other swarmer related pulls don't mention allowing them this.

**Comment by Fox-McCloud** [comment]
https://github.com/tgstation/-tg-station/pull/11487

They were never explicitly blacklisted.

**Comment by Aurorablade** [comment]
testing a fix now. i mean its a simple fix but given my run streak lately.
