### ISSUE TITLE
Energy gun on disabler mode shot a laser.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2482]
Not sure how to exactly replicate this.
Had an energy gun on lethal mode, because swarmers. Turned it to disabler mode to fire at someone that ran up to me and attacked me, and it shot out a laser, with the disabler beam sound effect, inflicting burn damage. Further shots fired proper disabler beams.

**Comment by KasparoVy** [comment]
I guess on click, it doesn't trigger the change in projectile state-- whereas after firing (clearing the loaded shot), on loading the next projectile, it checks for the projectile state (disable, laser)

Sounds spooky

**Comment by Fox-McCloud** [comment]
please re-report this if you ever find it again; I've never heard or seen this happen or received any further reports on it.
