### ISSUE TITLE
Swarmers can understand galactic common

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2491]
From #2325:

> Speak swarmer language, and do not understand human speech

Seems humans and swarmers understand one another just fine. Might need a fix.

**Comment by Plotron** [comment]
I guess...

**Comment by Robertha89** [comment]
They are AI's of a super advanced civilisation that died out long ago, they mastered bluespace tech beyond what humans have, i see no reason why they should not understand every language like any other cyborg or ai.

**Comment by tigercat2000** [comment]
because it's obviously unintended, robertha, therefore a bug
