### ISSUE TITLE
Launcher projectiles won't hit targets

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#2494]
Whenever you use a crossbow, Vox spike launchers, or the pneumatic cannon, their projectiles seem to just stop at your targets feet, whether they're a human mob or a simple mob like a spider. Found this out by testing in the admin rooms with the aforementioned items. The weapon can only really hit the user, as if you stand right next to your target and fire past them, the projectile hits you instead.

**Comment by Plotron** [comment]
So that means it's broken as fuck.
Damn, what a shame!
