### ISSUE TITLE
Odyssesus Syringe Gun Can Clone ANY Reagent

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#2498]
The reason for this being a problem should be fairly self-explanatory.

**Comment by Crazylemon64** [comment]
Could you give an example of a reagent it shouldn't clone? I'm not coming up with any.

**Comment by NTSAM** [comment]
I think some stuff it shouldn't clone is like Ominizine or some stuff.

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

Concentrated Initro.

**Comment by Robertha89** [comment]
Not true, can't clone potasium, and like a few dozen other reagents, there is no reason for it to not clone omnizine, as it is currently the slowest form of omnizine generation in the game.

**Comment by TheDZD** [comment]
@Robertha89 There are [_no_ sanity checks whatsoever](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/mecha/equipment/tools/medical_tools.dm#L615-L629) when it comes to scanning and replicating reagents. This means that reagents such as poison kit chems, and nanites (the adminordrazine subtype that ERTs get in their hyposprays) can be cloned.

**Comment by Crazylemon64** [comment]
Omnizine, at least, can be made in sleepers, so I don't think that particular one is off, but nanites and poison kit stuff seems bad to infinitely replicate, yeah

**Comment by Davdichan** [comment]
Syringe gun synthesisers don't get used that much and when they do its generally for lulz. Why don't we just make mounted sleepers able to inject basic chems into help patients and just have syringe guns need to be loaded manually, you have to drop them on the ground anyways to load them in the first place.
