### ISSUE TITLE
Plasmaman HoS/Blueshield latejoiners do not get items

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#2519]
A trenchcoat/armor and an energy gun/taser spawn on the ground upon round-start join. They do not spawn at all if you latejoin.

You don't get your taser or second energy gun unless you join at round-start.
Hell, I didn't even realize the Blueshield gets a taser until I joined Blueshield at round-start.

**Comment by fludd12** [comment]
Is this still an issue?

**Comment by Anticept** [comment]
Confirmed, still an issue.

**Comment by Aurorablade** [comment]
I do not think this is an issue and more intended due to how the outfit code and palsmamen work. @Crazylemon64

**Comment by Anticept** [comment]
It's an issue because it's inconsistent. Even if the code is by design due to restrictions in the mechanics of the plasmaman, it's goofy that you have to be a roundstart to get these items, yet a latejoin doesn't get them.

**Comment by pinatacolada** [comment]
This goes byond (honk) plasmamen, if you select a hoodie from the fluff inventory thing, you roundstart with the hoodie and a labcoat on the floor, if youre a doctor or a job with labcoats, but if you late join, you dont get a labcoat at all

**Comment by taukausanake** [comment]
Maybe we really should give Plasmamen a containing softsuit instead of a hardsuit. I always thought it a decent enough feature for them but maybe it's too limiting

**Comment by Anticept** [comment]
I know what the issue is now.

When you join the game, your are manifested in the startscreen area, then moved to the arrivals shuttle.

Your stuff is on the floor in the startscreen.
