### ISSUE TITLE
Passive vents don't work.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#2521]
Passive vents do not work at all. They should take the same pressure and gas composition as the room its in and put it inside the pipe like you would expect an open pipe in real life would work.

Been broke a long while, my first issue got it removed from the dispenser list, second issue had it restored but it was never repaired. Its possible it goes back to LIDNA implementation but im like 69% sure it worked after that.

Is VERY useful for advanced atmospherics work and could be the most important item for an effective closed loop turbine and other high-speed atmospherics work instead of building crazy massive stacks of laggy pumps to do the same thing.

**Comment by Tastyfish** [comment]
Just now looked at the code for passive vents and realized they are currently coded to act like volume pumps that output to the turf, which is clearly not their advertised functionality. I'm gonna work on making them act like expected.
