### ISSUE TITLE
Wearing a pAI on you head doesnt show their sprite

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#2524]
if you put a pAI in mobile form on your head it looks as if you didint have anything on your head

**Comment by Plotron** [comment]
Yeah.

**Comment by Spacemanspark** [comment]
The fairy sprite works, nothing else does.

**Comment by TheDZD** [comment]
Does anybody remember a point at which it show the pAI sprite on humanoids' heads other than the fairy sprite?

**Comment by Spacemanspark** [comment]
Yes, when they first came out.

**Comment by Plotron** [comment]
What Spacemanspark said.
I remember the fancy sprites, but I am not sure when it got broken.

**Comment by Aurorablade** [comment]
this https://github.com/ParadiseSS13/Paradise/commit/ca6c7d10baa221e09320939a9d7c487c5033625d broke it the head sprites and the inhand sprites were in the same file.

**Comment by Aurorablade** [comment]
and yes i am fixing it..
