### ISSUE TITLE
Opening a morgue in Zero-G makes the slab float away until it hits something solid.

### ISSUE THREAD

**Issue by Suthek** [ParadiseSS13/Paradise#2540]
How to reproduce: Open one of the morgues in while the gravity generator is busted, I guess.

The morgues can still be closed normally, making the slab vanish from the other side of the room.
I didn't have time to test wether in that case an item that's on the morgue slab tile or in front of the morgue itself is gathered up, so for all intents and purposes, it might just be a graphic bug.

**Comment by tigercat2000** [comment]
That's fucking hilarious.

**Comment by TheDZD** [comment]
It really is.

**Comment by KasparoVy** [comment]
Absolutely hilarious hahaha, "Working as Intended™"

**Comment by Suthek** [comment]
Update: I just managed to test how the slab interacts with items, and it is in fact, anything on the slab space that gets sucked back into the morgue, not what's in front of the morgue. So if you have a corpse at the other end of the room, no need to pull them over. Just break Gravity, open the morgue and close it again, making the corpse teleport away along with the slab.

**Comment by taukausanake** [comment]
Let's not fix this. How often is the morgue going to be used with the gravity out anyways?

**Comment by Davdichan** [comment]
The gravity goes out more often the morgue is used, I can tell you that much for sure.

**Comment by Tastyfish** [comment]
It almost seems like the fix should be that you have to pull the slab back and reattach it, rather than it never flying off, because this is too funny.

**Comment by taukausanake** [comment]
Yeah if anything make a check for the slab still being in front of the morgue but don't get rid of it floating away. That's a feature!

**Comment by Anticept** [comment]
Still a problem. As well as quite amusing.

**Comment by tigercat2000** [comment]
I say we mark this as a non-issue and officially call it a feature 👌 
Probably should make it so that morgue tables can be reattached in some way though.

**Comment by ExitGame** [comment]
It's been 2 years. 2 YEARS.

**Comment by Allfd** [comment]
@ExitGame Well........

**Comment by taukausanake** [comment]
> Working as Intended™

**Comment by Aurorablade** [comment]
@Crazylemon64 @Fox-McCloud i think this was fixed.

**Comment by Anticept** [comment]
@Aurorablade it's not fixed. Just tested.
