### ISSUE TITLE
IPCs register damage on their 100% indicator

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2544]
This might have something to do with Fox's stamina fixes. They're normally supposed to not feel pain at all.

**Comment by Spacemanspark** [comment]
Damage or stamina?
If it's stamina, it's intentional, I believe.
Damage- not so much.

**Comment by Fox-McCloud** [comment]
Stamina registers on the heartbeat monitor; the health doll registers brute and burn.

The only change I made to stamina is making it kick in at the proper level.

**Comment by fludd12** [comment]
As in, when I took damage as an IPC, the 100% heartbeat monitor changed to the green "not quite full" marker. Never tested with lower damage values, but it shows "pain" now.

**Comment by Ar3nn** [comment]
I can confirm that it's pretty much always done that. I've played IPC for a long while and the heartrate pulse icon always changes as I take damage, I thought it was meant to represent overall status. Didn't even know stamina was a thing in-game until I read this thread, so I didn't know it was an issue.

**Comment by Crazylemon64** [comment]
This isn't a bug, right?

**Comment by Tastyfish** [comment]
I'm fairly certain IPC's do have stamina like humans yeah.
