### ISSUE TITLE
Baystation RIG Issue repository

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#2545]
Cause all our new toys always break.

-Using Toggle Hardsuit Verb will say it will begin initializing the suit but will in fact make it invisible, or will completely break the suit and make it unresponsive if used more then once, nor will it actually initialize the suit.

-Using the rig will delete your headpiece and footwear. Doesn't really seem like an issue.

**Comment by tigercat2000** [comment]
>-Using the rig will delete your headpiece and footwear. Doesn't really seem like an issue.

wait what
I definately could have sworn trying to deploy it while wearing things would throw an error message and prevent you from doing it

.. was it using the UI or a verb?

**Comment by Earthdivine** [comment]
Verb, ERT/Security rig specifically.

**Comment by HereticChurch** [comment]
I've noticed activating the magboot functions of any of the rigsuit boots makes them take the sprite of standard magboots.
