### ISSUE TITLE
Gambling table takes full stack of grass tiles

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#2546]
Steps to replicate:
1. Make a full stack of 60 grass tiles
2. Make a wooden table
3. Use grass stack on table to make gambling table
4. Realize all your grass is now gone
5. Wrench the table apart
6. Notice you only got one grass tile out of it

**Comment by Fox-McCloud** [comment]
yeah, there's a lot of inconsistencies with wood, too---take apart a wooden chair and only get 1 piece of wood; try to built a chair and realize it takes like...4 pieces of wood.

**Comment by Crazylemon64** [comment]
Similar thing with girders, closets, table and rack parts - all disassemble to 1 metal each, in spite of their costs
