### ISSUE TITLE
Maint Drone Table Generation

### ISSUE THREAD

**Issue by NTSAM** [ParadiseSS13/Paradise#2547]
As a maintenance drone, it's possible to generate tables out of nowhere.

How to reproduce:
Pick up a table part set with your gripper.
Place table by using the gripper.
Keep using the gripper, you'll generate tables out of nowhere.

**Comment by Spacemanspark** [comment]
I swear this was already reported.

**Comment by Crazylemon64** [comment]
*ping*
#2368

**Comment by TheDZD** [comment]
As @Crazylemon64 pointed out, duplicate of #2368.

**Comment by NTSAM** [comment]
oh
