### ISSUE TITLE
Probably more of a feature request-ish thing?

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2551]
I would just really adore that one air canister in the western mining airlock to be removed. It serves no purpose I am aware of, and if its where the airlock refills from, that could easily be cut to the other canister about thirty feet away in that room with all the maintenance stuff in it that, if memory serves, does exist.

**Comment by Spacemanspark** [comment]
Put this on the forums, it will just get closed here.

**Comment by TheDZD** [comment]
This should just go on the forums.
