### ISSUE TITLE
Taking cold damage while pilot a civilian space pod in space.

### ISSUE THREAD

**Issue by Afelirick** [ParadiseSS13/Paradise#2555]
It seems flying a civilian space pod without a space/hardsuit is now detrimental to ones health!  At least in space.  Internal airtank is enabled as shown in the screenshots.  Freshly constructed space pod, wearing the standard mechanic jumpsuit.  This happened to me the previous shift, but I decided to wait for the next shift to try it again, in case it was some bizarre fluke.  Apparently not.  Not suffocating, no pressure loss, just cold damage.  I play mechanic pretty regularly, this is the first time I've encountered this.

Screenies:

http://i.imgur.com/fVgZwMY.jpg - inside the station

http://i.imgur.com/yzRMgkR.jpg - outside the station, owies.

Thanks!

**Comment by TheDZD** [comment]
Trying to "fix" spacepod code is like playing Whack-a-Mole, you fix one bug and three more pop up.

**Comment by Crazylemon64** [comment]
#2821 Close ALL of the bug reports! Until no bugs are left, and we attain perfection! (haha as if)
