### ISSUE TITLE
Revenant sprite is broken.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2561]
Revenants are currently bugged out, their sprites are naked bald humans with green eyes.

**Comment by Earthdivine** [comment]
The true form of the Revenant is revealed, the PseudoGreytide.

**Comment by Spacemanspark** [comment]
Funny enough, I had a similar issue the other day when coding Pokemon stuff out of boredom.
I fixed it by giving it an icon for when it's supposed to die.

**Comment by TheDZD** [comment]
@Fox-McCloud
