### ISSUE TITLE
pAI's cannot adjust their radio frequencies.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2562]
"SPACEMANSPARK STOP MAKING BUG REPORTS!"
Perhaps related to https://github.com/ParadiseSS13/Paradise/issues/2534
Exactly as it is on the tin.

**Comment by TheDZD** [comment]
@tigercat2000 Did you happen to touch any of the pAI radio code when you were implementing HTML5? Because last time both this and #2534 were happening, it was because of a problem with how radios were handled.

**Comment by tigercat2000** [comment]
not with HTML5
i know i touched their Life() with a few other things though
