### ISSUE TITLE
Dead pAI's that died in chassis form are... interesting.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2564]
Double click on your debris (If you were in chassis form), and you can re-enter your corpse. The bug here, however, is that you can rest and/ or unrest, and your sprite will rest/ stand up, the debris icon disappearing and you look normal. You can't do much else, however.

**Comment by tigercat2000** [comment]
resting has no sanity checks? why am I not suprised

**Comment by Crazylemon64** [comment]
Still a thing 1 sec
