### ISSUE TITLE
AI's sec huds cannot set statuses

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2568]
Dunno why, but people can't use their camera augments anymore (Med/sec HUDS).
@tigercat2000

**Comment by tigercat2000** [comment]
fucking kidding me

**Comment by Spacemanspark** [comment]
An update to this; they can't see the overlays, but can still examine and set arrest status' and whatnot.

**Comment by mikecari** [comment]
Yeah this is still a thing, fucking sucks too.
