### ISSUE TITLE
Central Atmospherics Computer on wrong net

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#2571]
The Central Atmospherics Computer in the station's Atmopherics control room can now only control the mining atmos alarm, and not any of the station's ones. There is no way to change what network it's on that I know of.

**Comment by Tastyfish** [comment]
It actually seems to be working this round, either it's random or it can change partway through the round, because multiple rounds it's been the mining network/layer.

**Comment by Tastyfish** [comment]
Although the alarm icons are all shifted about 100 pixels or more higher than they should be on the map.

**Comment by tigercat2000** [comment]
about the 100 pixels thing- yeah I noticed that with HTML5 and have no idea how to fix it, happens with the crew monitor too

**Comment by IAmBigCoat** [comment]
I'm getting a similar but slightly different problem with the central atmo computer:
First is the aforementioned wrong-network problem. The map wasn't rendering, no icons were visible, and Show Detail List only showed M019's air alarm. Unscrewing the monitor and then screwing it back in fixed the network,
Next, though, is the problem that even when it's on the network, all of the icons and the station map are invisible. At that point, Show Detail List fails to load the list at all.

**Comment by Tastyfish** [comment]
Good to know that reassembling it fixes the network thing.

**Comment by IAmBigCoat** [comment]
Joined a round and the Central Atmo computer was on the MO19 network. Rebuilt the computer, nothing changed.

**Comment by Tastyfish** [comment]
The server probably hasn't been updated yet.
