### ISSUE TITLE
Using a syringe or open beaker on a cake will both use the item AND put it in the cake.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#2583]
The beaker can be solved by putting a lid on it, but syringes are doomed to only ever have 10 units of whatever in them, with the other 5 in the cake.

The reason I include beakers in this is because I thought I'd be able to treat the cake like a bag of flour or other container and pour a ton of rum into it from the beaker. Because rum cake. As it stands, splashing a cake with the contents of a beaker does nothing but put the beaker into the cake, so you have to feed it a syringe for each unit of whatever you want in each slice.

Beaker-to-cake fluid transfer would be ideal.

**Comment by Anticept** [comment]
As an idea to solve this: syringes set to draw will NOT inject anything, and will instead insert nicely into the cake. Those set to inject, as are unlidded beakers, will inject into the cake.

**Comment by taukausanake** [comment]
I still want a bluespace cake that can take a lot of items inside it

**Comment by DesolateG** [comment]
This looks like it was fixed with #8681
