### ISSUE TITLE
Selecting harm intent visually breaks the intent selector

### ISSUE THREAD

**Issue by Joeeigel** [ParadiseSS13/Paradise#2590]
I've had this issue across two different computers so I thought I would report it in case it is a bug. See the gif below for an example of the issue.

http://i.imgur.com/lGi3fjo.gifv

**Comment by Spacemanspark** [comment]
This occurs if you change the UI.

**Comment by Joeeigel** [comment]
Set UI back to midnight and harm intent shows correctly.

**Comment by Spacemanspark** [comment]
Well, custom change the colors, I should elaborate.

**Comment by taukausanake** [comment]
I should have reported this when I got it. I think all I did was mention it in adminhelp

**Comment by Spacemanspark** [comment]
I've dealt with that bug for over a year. Learned to live with it, but it would be nice to have it fixed.
