### ISSUE TITLE
Multiple ERT's Not Working

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#2598]
Trying to send in an ERT after one is already on station puts out the announcement, but it doesn't work if you click the "Join as ERT" button. I assume this is a bug, as we've sent multiple ERTs in the past.

**Comment by Fox-McCloud** [comment]
@DaveTheHeadcrab

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, the keycard authentication device spews out an error if you try to send another ERT in, at least in the code.

**Comment by TheDZD** [comment]
Fox, he's @DaveTheHeadcrab now.
