### ISSUE TITLE
Text Sanitization is Broken (again)

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2601]
Basically, once upon a time, for certain things, if you said something like

"He's a 5'8" red fox", it would appear like: "He#39s a 5#398#42 red fox" (or something close).

This was later fixed and things would appear correctly...that said, something broke this, again, and now things are messed up.

This impacts a lot of stuff, from player descriptions, to using the voodoo doll to make someone say something (making it horrendously obvious when a voodoo doll is on the field).

**Comment by LufgtHuron** [comment]
Oh yeah this makes the whole ERP experience reallt terrible, how am I supposed to do it with all these numbers and shit? 

Also, how do I specify all these really precise things like having a height of 1 m 77 cm and 22.2 mm? Or a weight of like 77 kilos and 22.22345111 grams? Shit!

**Comment by TheDZD** [comment]
@LufgtHuron This isn't the place for passive-aggressive comments directed at certain players or groups of players. This being a bug has nothing to do with ERP or snowflakey characters (and the suggestion is that it does is laughable). If you have nothing constructive or useful to comment about this, then don't comment at all.

**Comment by LufgtHuron** [comment]
@TheDZD

You're right, my bad. I deleted the comment, I will save stuff like that for a more appropriate place & time or just - not comment like that at all. Shouldn't have let such nonsense tick me off, I will avoid github until most of my withdrawal symptops pass, sorry again.

**Comment by CrAzYPiLoT-SS13** [comment]
I'm pretty sure this doesn't appear anymore.
