### ISSUE TITLE
Candy Machine won't accept chocolate bars

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2614]
This is incredibly detrimental to my ability to scrumdiddlyumptiousify up some chocolate candies.

**Comment by Spacemanspark** [comment]
RED ALERT RED ALERT.

**Comment by Tastyfish** [comment]
What a strange oversight.

**Comment by FalseIncarnate** [comment]
Couple quick questions:

Was there a message, and if so what did it say?

Was the candy maker in use, dirty, or screwed open?

Has this occurred on multiple rounds?

**Comment by fludd12** [comment]
1: Yes, "You cannot put the chocolate bar in the candy maker" or something like that. Even the chocolate reagent was considered disallowed.
2: None of the above.
3: Yes, so far every round I've tried it.

**Comment by IAmBigCoat** [comment]
I just tested this and the candy machine accepted chocolate bars and candy bars just fine.

**Comment by Iamgoofball** [comment]
Was it a chocolate bar FROM the machine itself?

**Comment by IAmBigCoat** [comment]
It was. I made a candy bar (Just listed as candy,) from it. The machine also accepted the candy bar. Then I tried a candy bar from one of the vending machines, and it also accepted that.

**Comment by fludd12** [comment]
Ah, that's what I was supposed to use! I was making chocolate by spilling the reagent on the floor. Still, we really ought to make it accept all kinds of chocolate.

**Comment by FalseIncarnate** [comment]
I'm still unsure if this is an issue or not.

The recipes call for the chocolate bar item, which is the result of the reaction in beakers/containers.

You said you were spilling the reagent on the floor to get something? Are you talking about spilling pure chocolate powder onto the ground or what?

**Comment by FalseIncarnate** [comment]
After looking into the code, the bar you are getting from the floor (rather unsanitary to be eating floor chocolate) is a completely different item type: reagentchocolatebar.

This bar is not used by ANYTHING, and actually seems to be kinda stupid in my opinion since it is the same reagents and such as a chocolate bar made through the proper reaction recipe. I'll probably be either completely nuking this bar from the code or turning it into a separate bar (perhaps a dark chocolate bar) with it's own uses.

**Comment by fludd12** [comment]
The hot chocolate from the hot drinks vendors (not Dutch Hot Cocoa) has
pure chocolate reagent in it; Spilling 5u produces a chocolate bar, but
these didn't work.

**Comment by Iamgoofball** [comment]
@FalseIncarnate or making it a child of the normal candybar like a sane person
