### ISSUE TITLE
Doors do not automaticly open for person in wheelchair

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#2620]
doors will not auto open for person when they bump the door/make contact with door
Person in wheelchair cannot ctrl+click or mouse click a floortile to turn without actually moving.

**Comment by Aurorablade** [comment]
I think it has to do with it thinking your hands are not free.

**Comment by tigercat2000** [comment]
it doesn't
door/Bump() code handles opening for mobs
I didn't feel like snowflaking the already shit wheelchairs into it

**Comment by Fox-McCloud** [comment]
This is also the case for vehicles as well--both the janicart and Bay's tugs.

**Comment by Ar3nn** [comment]
but not the shit ambulance.

**Comment by tigercat2000** [comment]
@TheDZD  but this isn't a bug
at best it's an oversight but it's not even that because it's a matter of needing to snowflake it into door code

**Comment by TheDZD** [comment]
This tag probably fits better than either of the two.
