### ISSUE TITLE
Revenants are consumed by the singularity

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2621]
This happens even in ghost form, which shouldn't be affected by anything. Not entirely sure why players are exploring the singularity as the sp00p ghost, but it's worth looking into.

**Comment by TheDZD** [comment]
This is likely intentional, although a bit odd considering that revenants in most other respect act like player ghosts while moving around.

**Comment by Anticept** [comment]
This doesn't seem to occur anymore.

Created a revenant. Moved my mind into it. Created a singularity, and it doesn't seem to destroy the revenant at all, but it IS still affected by the gravity pull.
