### ISSUE TITLE
Fire Axe's sprites don't update properly

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#2632]
The axe initially appears as one-handed when drawn, It remains one-handed when wielded, then when unwielded it appears wielded- this results in the sprite appearing to be in the opposite mode. I'm unsure if this is clientside or not.

**Comment by Plotron** [comment]
I've experienced this bug once a few weeks ago (I think), but it was probably a spear.
Yeah, it's kind of out-of-sync (at least client-side - but aren't most of the things handled server-side?).

Check spears if they have the same problem.

**Comment by tigercat2000** [comment]
Fixed by #2752
