### ISSUE TITLE
[Kind of a suggestion?] Greys cannot cancel telepathy

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2653]
Simply put, there is no way to /not/ talk to someone once you click the button, and pressing enter without a text input sends blank text to the person, while still alerting them to the fact that a voice echoes through their head. We really ought to have a way of... not talking?

Similarly, there's no way to cancel pill creation at the ChemMaster, which can get annoying, though at least making multiple pills gives you the opportunity to have zero pills made.

**Comment by Fox-McCloud** [comment]
There's a lot of things that have this, up to, and including admin helps.

You end up having to send a blank message to an admin if you change your mind.

**Comment by Ar3nn** [comment]
Wait, that actually does send a blank adminhelp? shiiiit, I've done that a few times, then.

**Comment by fludd12** [comment]
The strange thing is that it doesn't with ahelps, unless you have a space
in the blank. With grey text, it still sends, even without putting anything
in.

**Comment by Plotron** [comment]
Yes, a lot of things.
Like harmful genetic powers...

**Comment by Zuhayr** [comment]
var/msg = input("What do you want to say?") as text|null
if(!msg) return
target << "[msg]"

'as text|null' also allows you to cancel.
