### ISSUE TITLE
Can't Cancel Setting C4 Timer

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#2664]
Should one start setting the timer to arm a brick of C4 and suddenly wish to abort, they are unable to unless they find a quiet spot, shut down their client and rejoin.

**Comment by TheDZD** [comment]
I could be wrong here, but I believe that the timer only starts after you plant the C4, setting the timer just determines how long it will take after you place the C4 on something.

**Comment by pinatacolada** [comment]
I think he means that once you set the timer there's no way to set a different time
