### ISSUE TITLE
Giant Spider Civil War

### ISSUE THREAD

**Issue by Keilden** [ParadiseSS13/Paradise#2666]
Seems like all giant spiders hate eachother and will kill other giant spiders on sight. Was observing a round with a random spider event. A nurse spider ate a mouse and laid eggs. Her children grew up and killed her and eachother.

**Comment by TheDZD** [comment]
I'm guessing that this is an issue with spider factions. Possibly caused by #2591.

**Comment by M3hillus** [comment]
Its the ciiiiiiiircle of life!

**Comment by Fox-McCloud** [comment]
I'm pretty sure I know what happened here, but I could be very wrong; I have a feeling that there were both hostile and non-hostile spiders involved in this...as such, the hostile ones would *definitely* attack the non-hostile ones (as they properly should!).

I'll test further, but I'm pretty sure this is what happened.

**Comment by Fox-McCloud** [comment]
Yeah, upon testing this---I spawned in hostile spiders--they killed things and ignored each other; likewise, their offspring also killed things and ignored each other.

Methinks there were neutral and hostile spiders involves in this.

**Comment by Keilden** [comment]
No I am sure that there was no neutral spiders around that round. And I saw the spider lay the eggs and that the offspring grew up and killed the mother.

**Comment by Keilden** [comment]
During a round today two tank/bull spiders or whatever the redeyed ones are called decided to fight to death when they grew up from the same egg sac. This time I know they came from the same egg becuse the spiderlings did not move at all.

**Comment by Aurorablade** [comment]
Cannot reprodue on normal spiders. HOWEVER Terror spiders and giant spiders hate each other. @Kyep intended?

**Comment by taukausanake** [comment]
Pretty sure Terror spiders are supposed to hate everything alive. Giant spiders hate anything that hates them

**Comment by Kyep** [comment]
@Aurorablade Terror Spiders look at normal spiders the same way humans look at chickens. "Yes, they have the same number of legs as we do... but they're still food".

**Comment by Fox-McCloud** [comment]
Pretty sure this was resolved long ago.
