### ISSUE TITLE
Syndiborg Bugs

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2670]
There's a few Syndiborg bugs at the moment:
- Machine gun is missing its sprite
- Syndiborgs cannot utilize the shortcuts on doors and other such things
- Syndiborgs can't unlock/unbolt/etc things at all, even if they manually bring the panel up
- doesn't seem to be able to utilize its own pinpointer

**Comment by theColdflame** [comment]
Wasn't being unable to unbolt doors an intentional nerf?

**Comment by Rumiluntti** [comment]
I think it was intended to not let syndiborgs mess with doors.
Syndiborg pinpointer only shows the location of teh nearest nukeop, is this broken too?

**Comment by Fox-McCloud** [comment]
Its part of a string of Syndiborg bugs that were never really fully fixed--they weren't able to interact with a lot of things---and apparently still aren't. AFAIK, this was never intentionally added.

**Comment by FlattestGuitar** [comment]
I don't believe any of these are still issues.

**Comment by Crazylemon64** [comment]
yo ring ring can this be shut down?
