### ISSUE TITLE
Discrapancies - security records

### ISSUE THREAD

**Issue by Stephanov** [ParadiseSS13/Paradise#2677]
A record appeared unupdated - a warden corrected the issue in his records computer

Variables they tried to change were:
-Wanted -> Incarcerated
-Criminal record -> whatever the changes were

The data however did not update - the sec hud still showed the person as "warranted" and their criminal record showed up neither on the PDA nor on other security devices.

Things we tried:
-Putting in ID to authorize the computer
-Changing the records

Maybe there's a problem with the security record computer in the warden's office?

**Comment by Vivalas** [comment]
Going to add on to this by saying records are acting very wonky. Random entries in the records show up as being wanted or incarcerated (the colors) despite the actual records having no status (clicking on them). Status seems to change semi randomly and changing someone's status from the records doesn't actually update the colors.

Also, secHUDs glitch and prompt the user multiple times when trying to change status from examine, not sure if this is related.

**Comment by Vivalas** [comment]
The error appears to be that multiple records have the same ID, thus fucking up the system when someone tries to change a records.

**Comment by Vivalas** [comment]
![image](https://cloud.githubusercontent.com/assets/6334647/11460758/7cd7ad7c-96b8-11e5-8d16-43818d55580c.png)

**Comment by Vivalas** [comment]
This is definitely the case as trying to change records using the console alters the record of the highest entry with the same ID. For example changing Andy Friese in this example to incarcerated would set Alexander Archibald to Incarcerated as well, and all the other 00FFF7s

**Comment by Stephanov** [comment]
I too have seen people randomly getting set to arrest - coders, if there's any way we can help provide more info let us know. As you might understand, SOP is currently in an even worse shape than usual (records wise anyway)

**Comment by pinatacolada** [comment]
medical records are affected too, and what's even worse, the medical laptop can show the wrong record without you noticing

**Comment by Vivalas** [comment]
I would imagine all records would be affected due to the fact that IDs are what link records together.
