### ISSUE TITLE
Detective Laptop Issue

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#268]
Disregarding the *cough*unwarranted*cough* changes to the Detective's access level, it should be noted that a Detective's laptop currently does not have access to Security Records, only Medical ones.

**Comment by Artorp** [comment]
It's a bug. In this file:

https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/computer3/lapvend.dm#L296

    if(access_security in C.access || access_forensics_lockers in C.access)

Should be replaced by

    if((access_security in C.access) || (access_forensics_lockers in C.access))

While we're on this topic, he really should get access to a recharger. As far as I know he has access to none on his own which discourages the use of a laptop. Meanwhile rest of security has like 6 within hands reach. Maybe move some to the security room above his office?

**Comment by ZomgPonies** [comment]
Err this should have autoclosed, Fox can you close it please?
