### ISSUE TITLE
Corgis Eating Food No Longer Regens Health

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#2680]
Ate a crapload of food as a near-death Ian, it bumped my HP up from 26% to 43% after eating a meat but it IMMEDIATELY went back down to 26%. I was able to reproduce this as many times as I ate a meat.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/living.dm#L44>This</a> and <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/reagent_containers/food/snacks.dm#L248>this</a> is where the problem arises. The health is set directly here, causing it to be immediately reset once the health updates.
