### ISSUE TITLE
[Space] Gangways / Pathways stop H/E pipes working

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2688]
If you lay H/E pipe over a pathway it H/E pipe doesn't lose heat to space. Prime example of this happening is at the flow pipe to the turbine room from Atmos' mixing tank. Replace the pipe there with H/E and it won't cool til the walkway is removed.

**Comment by tigercat2000** [comment]
That'd be because catwalks are currently a type of turf themselves (which is fucking stupid), but don't inherit from /turf/space

**Comment by Tastyfish** [comment]
Why aren't they an object like latices?

**Comment by Crazylemon64** [comment]
I think so that cables can be placed on top

**Comment by Taaketa** [comment]
This will probably not be fixed due to the need to lay cable.
