### ISSUE TITLE
Turning a monkey into a human rquires it's DNA to be altered 3 times instead of just once

### ISSUE THREAD

**Issue by CupcakesNHacksaws** [ParadiseSS13/Paradise#2690]
Normally turning a monkey's 55th SE block to 800 or less would turn it human. Instead, you need to do that, raise it above 800, and then back to 800 or less again.  
It's just generally annoying, and if you want to consume a humanized monkey as a ling/vampire, you need to bring 3 SE injectors with you to do it instead of just one.

**Comment by Crazylemon64** [comment]
Didn't get closed for some reason
