### ISSUE TITLE
In Nations 2.0+, Cargonia Ore Redeemer Is Insta-Stealable

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#2700]
Cucks mining for the whole round unless you bust open the gulag, and even then, not for points.

The writing of this report was prompted by the theft of the ore redeemer before the 'nations' job-termination warning was even sent out within the first fifteen seconds of the round.

Exceptionally vulnerable

**Comment by Spacemanspark** [comment]
Not really a bug, just ahelp that shit.

**Comment by Tastyfish** [comment]
Textbook metagaming rule violation, not really any way to avoid this code-wise, I don't think.
