### ISSUE TITLE
Medical Hud issue

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#2705]
When examining medical records via Medical Hud, you get more than one medical record. For example:

http://puu.sh/lGkLb/851981fbe8.png

That was me scanning one persons medical record.

**Comment by Crazylemon64** [comment]
Link rotted

**Comment by Aurorablade** [comment]
pretty sure this may not be an issue.

**Comment by Fox-McCloud** [comment]
I believe this was related to medical records not GCing; they're hard deleted now.
