### ISSUE TITLE
Cyborg disabler cooling is prohibitively expensive

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2707]
Currently, the cyborg disabler cooling, for security modules only, requires a whopping 40 metal sheets, the same price as the cyborg-generic VTEC upgrade. Compared to other upgrade modules, which take on the order of about 5 sheets, this is a dramatic difference. Are these price ratios as intended?

In addition, the rename module is 17.5 metal sheets, though I assume the price is that high to prevent roboticists from easily covering up a naughty cyborg's trail.

**Comment by Fox-McCloud** [comment]
Definitely feature request/balance suggestion, and not a bug. Pretty sure this is intended as they're both massive upgrades to the borgs.
