### ISSUE TITLE
Mobs with environment_smash turn wood chairs to metal.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2709]
Had a free moment, and decided to goof around with my Pokemon code idea a bit.
Found this while messing around.
![Mewtwoismagic](http://i.imgur.com/ZLYU0Vv.png)
Also, it's a bit inconsistent, it gives you a message when destroying tables and walls, but not chairs.

**Comment by Plotron** [comment]
Magic.
