### ISSUE TITLE
Beaker Shenanigans

### ISSUE THREAD

**Issue by Dinarzad** [ParadiseSS13/Paradise#2717]
This is gonna be mildly long winded, so I apologize for that.

Just had a round as a Medical Cyborg with a lot of weird beaker stuff happening. Round was normal until I clicked on the Cryo-tubes with a beaker in which it said "The beaker is stuck to you!" ((As it should, cuz borg))

However. After THAT things got..... weird. Beakers started getting stuck in people's hands and when removal attempts were made, it said the same thing. The beaker is stuck to them. One guy even hacked off his arms an somehow the beakers were still stuck to him, which prevented him from being cloned.

In addition, when I had my inventory open while a doctor was giving a seperate beaker to a botanist, I noticed it was affecting MY beaker in my inventory. When he put the lid on it, the lid went on mine, when he gave it to the botanist, it poofed out of my own inventory.

Steps to reproduce: I have no fuckin clue.
I guess try to insert a beaker into the cryo tubes, that's all I got.

**Comment by Crazylemon64** [comment]
D'oh! The beaker of the cryotube is set before it checks whether it's NODROP or not!
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/cryo.dm#L287>Here</a>. I'll fix this now.
