### ISSUE TITLE
visible_message is invisible to wrapped mobs

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2725]
- Be in a mecha/mmi/pAI card
- Be ignorant to the spider that's trying to claw your exosuit apart

It seems mech pilots DO notice people stabbing them with an energy katana, however, as that's handled within the mecha code itself.

**Comment by Crazylemon64** [comment]
Is it possible to override the existing "viewers" proc to also check for wrapped mobs, in addition to a parent call to the original "viewers"? Or would that be face-meltingly horrible code?

**Comment by ZomgPonies** [comment]
I thought it already did.

**Comment by tigercat2000** [comment]
visible_message and saycode are two very different beasts
which one has an issue

**Comment by Crazylemon64** [comment]
Well, both use the "viewers" method to determine which mobs hear/see it. The way both work, to

**Comment by tigercat2000** [comment]
There is definately some fucking handling somewhere that makes sure mobs inside mobs/objects hear anything said, but I am having trouble finding it.

**Comment by Crazylemon64** [comment]
Wait, actually, I think wrapped mobs are still able to hear speech. So, the problem lies with visible_message, I think I might have been mixing up my memories.

**Comment by TheDZD** [comment]
Say code definitely checks for players inside of objects (this includes mobs inside of mobs), and players inside of objects inside of objects. The issue is almost certainly with visible message.

**Comment by Crazylemon64** [comment]
Yeah, the problem is definitely with visible_message, I think saycode is innocent this time. Should I switch it to a similar format as the saycode speech detection, and see if that resolves the issue?

**Comment by Crazylemon64** [comment]
Fixed by #5429
