### ISSUE TITLE
[Nations] Nation leader can change nation name after death

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2726]
CE got killed by someone during a nations round. CE renamed the nation to "Below viro, above AI"

**Comment by ZomgPonies** [comment]
What a $%^*%^&*()

**Comment by tigercat2000** [comment]
I do hope you adminhelped this, because it's blatant metagaming.
still an issue of course

**Comment by Taaketa** [comment]
*cough* It may or may not be the current round and I am that person who just cloned the CE.

**Comment by Taaketa** [comment]
I should add the CE never nominated a Nation Heir so that maybe part of the issue.

**Comment by Plotron** [comment]
I haven't even noticed! Wow!

**Comment by Spacemanspark** [comment]
Oh, that would explain why engineering was named weirdly.
Kek.
