### ISSUE TITLE
[Nations] Cyborg death issues

### ISSUE THREAD

**Issue by AndriiYukhymchak** [ParadiseSS13/Paradise#2728]
When cyborg dies in nations, you get messages "...you can almost hear something..." in packs of 100 each minute.

**Comment by ZomgPonies** [comment]
Not sure if this is limited to Nations or is a bug recurring in all gamemodes.

**Comment by AndriiYukhymchak** [comment]
Wait... I think I got it. It is only nations bug because of 2 modules you have (shield and mobility). If they are de-powered (power<2-3k) they start spamming "Module is turned off". Probably these messages are converted to "almost hear something" on "death"
