### ISSUE TITLE
N2O canister sprites are broken

### ISSUE THREAD

**Issue by Markolie** [ParadiseSS13/Paradise#273]
@PJB3005

Looks like the sprites of N2O are broken as a result of the patch. See http://i.imgur.com/BUiNluM.png.

**Comment by Markolie** [comment]
Derp.

**Comment by PJB3005** [comment]
Crap, gonna get this hotfixed real quick, I swear I used this sprite in my tests

**Comment by Markolie** [comment]
Checking if it'll autoclose.
