### ISSUE TITLE
Cannot Resist out of Mech Sleepers

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2734]
you're meant to be able to resist out of these so it's not just a forever stunlock/prison, but this apparently isn't working.

**Comment by Crazylemon64** [comment]
Do you want the resist-to-escape to be on a delay? Do you want it to notify the pilot of the mech when the occupant attempts to escape?

**Comment by Fox-McCloud** [comment]
I believe TG just has it so that if you resist, you're automatically and instantly ejected (I believe it just calls go_out()).
