### ISSUE TITLE
Game mechanic: Lockbox metal

### ISSUE THREAD

**Issue by Stephanov** [ParadiseSS13/Paradise#2738]
A lockbox visibly made of metal, though when you want to recycle an empty one:
"This object does not contain sufficient amounts of metal or glass to be accepted by the autolathe."

I feel it should have a small amount of metal for recycling. That's all. c:

**Comment by Plotron** [comment]
It's bluespace metal. One does not simply *harvest* bluespace.

**Comment by Crazylemon64** [comment]
They don't COST anything extra, either, so I think it's best it stays as-is

**Comment by Fox-McCloud** [comment]
>They don't COST anything extra, either, so I think it's best it stays as-is

This, plus I'd rather players not min-max it and find the cheapest thing that has a lockbox and spam it to get extra metal.
