### ISSUE TITLE
Space weeds can't pull you if you're on a segway

### ISSUE THREAD

**Issue by MaskedJihadi** [ParadiseSS13/Paradise#2739]
Yeah, you heard me.

**Comment by Plotron** [comment]
Do not nerf the segway!

**Comment by TheDZD** [comment]
Probably related to how you're technically buckled to the vehicle. @FalseIncarnate intentional or not?

**Comment by FalseIncarnate** [comment]
Intended. If you are already buckled to something, you can't be entangled since that does stuff like move and buckle you onto the vines. That means patients won't be ripped off roller beds or ambulance tugs should vines pop up near medbay.
