### ISSUE TITLE
pAI fairy onhead sprite doesnt work

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#2743]
Putting a pAI using the fairy mobile form on your head will make them invisible on the human mob

**Comment by Spacemanspark** [comment]
@Aurorablade

**Comment by Aurorablade** [comment]
RAWRGHHHHHHHH

**Comment by Crazylemon64** [comment]
![works](https://cloud.githubusercontent.com/assets/5661700/21787534/9f49c0b4-d67e-11e6-8d8b-2e8736d1b6e0.png)
