### ISSUE TITLE
Cyborgs are VERY STRANGE and VERY GLITCHY

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2747]
Being shot repeatedly as a cyborg got me "Killed" - The health indicator was a bluescreen, and it said I shuddered violently for a moment, before becoming motionless.

However, it repeated that death message twice a second for as long as my battery was still in me, and I could still walk around, despite being able to see through walls.

Not only that, but I could still talk in cyborg chat, except doing so made it repeat my message an exponential number of times. The first time, 5. Then, half the text chat. Then, it filled the whole screen. and more. 

This binary glitch persisted even after being repaired.

Update 1: Side note, the binary glitch may be clientside.

Update 2: Being removed from the cyborg body and placed in a new one fixed the glitch. What the hell.

**Comment by Fox-McCloud** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
insane glitches which are probably clientside are not my domain

I looked through as much cyborg death code as I could, none of this fucking shit should happen, so I'm stumped.

**Comment by Crazylemon64** [comment]
I think I might almost be able to work this out, but... what does something like `. = ..()` mean? I see it a lot in `Life()` code

**Comment by Crazylemon64** [comment]
Well, here's a quick-fix for you: 
robot/life.dm: <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/silicon/robot/life.dm#L63>Line 63</a>, whenever the cyborg calls `use_power()` and there's charge in the cell, stat will be set to `CONSCIOUS`. Then, when status updates roll around, it appears as alive to `death()`, and so `shudders violently for a moment, then becomes motionless, its eyes slowly darkening.` forever and ever so as long power remains in the cell.

As for the binary messaging exploding once the robot dies, I haven't found the cause of that yet.

**Comment by Crazylemon64** [comment]
Actually, I suspect that the cyborg might not be properly removed from the dead_mobs_list when set to `CONSCIOUS` from `use_power`, and so the code in mob/language.dm for binary speech broadcasting then sends each entry of that same mob in the list the message: <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/language.dm#L458>Here</a>. Hopefully this will help the problem.

**Comment by Crazylemon64** [comment]
I think the final part of this issue is ensuring that a cyborg, when repaired, will be properly removed from the `dead_mob_list`, so that it doesn't get any duplicate messages if it dies even once. I'll watch for the corresponding PR when it emerges.

**Comment by tigercat2000** [comment]
@Crazylemon64 
`. = ..()` means, set the default return value to the parent return value

`.`, at least, when used by setting it to something, `. = value`, is the "default return value" - if a proc exits with no 'return' keyword, IE, reaching the bottom, it will return the value of `.`

technically it does more, as `.()` calls the proc, and `..()` calls the proc's parent, but that's almost never used
