### ISSUE TITLE
Engineering duffle bags

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#2748]
Engineering duffle bags dont have a sprite when put on

**Comment by RudiPardieck** [comment]
All duffel icons are missing from the back.dmi file

**Comment by KasparoVy** [comment]
Oh God, where the hell did the duffelbag icons go?

**Comment by Crazylemon64** [comment]
Were they even there in the first place? I've looked a bunch of commits back, and haven't found them.

**Comment by kylejen** [comment]
Yeah, I miss the dufflebag icons. It's strange having your character not seen as wearing any kind of backpack (visually)

**Comment by orelbon** [comment]
@Fox-McCloud @tigercat2000 where are the sprites for the duffle bags, backpacks and satchels?

**Comment by orelbon** [comment]
scratch that where are the satchel icons at i can't find them.

**Comment by Crazylemon64** [comment]
Mob sprites are found in mob/back.dmi, if I'm not mistaken, and the inventory sprites for them are found in obj/storage.dmi
