### ISSUE TITLE
Cyborg reclassification boards break cyborg names

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#2758]
From what i've seen trying to Re-name a cyborg breaks their name. Gets stuck as "Default Name" Until the MMI/Posibrain is taken out and replaced into the chassis, Which is the only way I've found to fix it.

**Comment by Spacemanspark** [comment]
Is the person using a pen on the reclassification board to rename it, or just plain old sticking it in?

**Comment by AceMcLazer** [comment]
@Spacemanspark We were just sticking it in. Maybe that was the issue. I was under the assumption it re-Enabled Namepick Verb. My mistake.
