### ISSUE TITLE
Advanced Mop Breaks walls with fungus on them.

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#2759]
Advanced mop seems to weld walls down when you try to clean walls afflicted by fungus.

**Comment by tigercat2000** [comment]
that's fucking hilarious

**Comment by Spacemanspark** [comment]
Hahaha what.

**Comment by tigercat2000** [comment]
"THE JANITOR IS HERE MOTHERFUCKER"
**smashes down wall with mop of power**
"GET READY TO BE CLEANSEEEDD"

**Comment by Fox-McCloud** [comment]
Fungus or wall rot? Becuase that's totally normal with wall rot.

**Comment by Spacemanspark** [comment]
Whaaaaaaaaaaat.

**Comment by AceMcLazer** [comment]
It was fungus. green stuff

**Comment by Fox-McCloud** [comment]
Alright, that's not fungus. That's wall rot.

Fungus is the brown stuff on the walls you can scrape off to make spaceacillin. Wall Rot is wwhat weakens a wall---just touching it with much of anything, for a regular wall, makes it crumble, YOu use welders to remove wall rot.

This isn't a bug. Working as intended.
