### ISSUE TITLE
Virology machine bug

### ISSUE THREAD

**Issue by SomanBat** [ParadiseSS13/Paradise#2760]
OK, there's a way to break a semi-important viro machine for an entire round. Steps to replicate follow.

Pathogenic Isolator (first machine in line). Insert an infected blood sample, with the virus already in the database.  Hit "database lookup", and close the window before it completes.  If you do this, it renders the machine totally unuseable for the rest of the round.  All you get is a blank window on trying to access it.

This bug may depend on lag some, too.  People are more likely to close the window if the database lookup is taking a little bit, and if they do, it locks the machine for the rest of the round.

**Comment by Plotron** [comment]
I assume that relogging did not help.
