### ISSUE TITLE
Character set up: no details/bald/no facial hair.

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2761]
As of the latest patch, character set up details are incorrect; everyone appears featureless; their colors are correct, but they'll always be bald/have no facial hair.

This has no impact on *in game* sprites--they look normal, but the character setup sprites are lacking details.

**Comment by kylejen** [comment]
I've also noticed that during character setup, your undershirt/underwear won't show up, but that doesn't affect in-game sprites, as well.

**Comment by ZomgPonies** [comment]
@SvartaSvansen
