### ISSUE TITLE
AI Shuttle Call UI button leads to the voice annoucement dialogue

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#2765]
the verb itself from the tab works, it's just that the button is linking to the announcement system

**Comment by Plotron** [comment]
Wtf? Really?!
...

**Comment by Aurorablade** [comment]
Oh god I was hoping I didn't need to swap branches from my HUD work

**Comment by Spacemanspark** [comment]
RIP

**Comment by tigercat2000** [comment]
please don't touch this
it'll be fixed by #2719

**Comment by Aurorablade** [comment]
yay!

**Comment by Spacemanspark** [comment]
Actually, I think cyborgs can't use their set-sensor-thingy button either at the moment.

**Comment by tigercat2000** [comment]
Someone test this, it is probably fixed.

**Comment by pinatacolada** [comment]
still bugged
