### ISSUE TITLE
Custom cannister colors aren't cleared making new design

### ISSUE THREAD

**Issue by Artorp** [ParadiseSS13/Paradise#277]
First of all I'd like to say I love the new labeling system. There's one issue tho, labels and decals aren't cleared when the canister is relabelled. You can change the primary color, but the others+decals sticks with it till the end.

**Comment by PJB3005** [comment]
that's... odd? both the _color and decals var are being cleared every time you relabel, and the overlays are cleared by the update_icon() code, always, I'm gonna have to test this later but I see no logical way this can happen

**Comment by Artorp** [comment]
Good work, all issues seem to have been fixed. :+1:
