### ISSUE TITLE
Telecomms compiler fails to upload for certain scripts

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#2775]
Uploading my script caused the local html to refuse to upload it.
![Here](http://i.imgur.com/imcZ9M1.png)
* Line 58 is the `window.location = ` that pushes the script to the (real game) server. From fiddling with deleting parts of the script, I think it flips out if the script is over a certain length.

Going to naturally assume related to #2433. Can upload the script somewhere if need be for testing.

**Comment by Tastyfish** [comment]
Going to naturally assume related to #2433. Can upload the script somewhere if need be for testing.

**Comment by tigercat2000** [comment]
The script would be appreciated.

**Comment by Tastyfish** [comment]
http://pastebin.com/EmTH4TAf

**Comment by Crazylemon64** [comment]
I think the "encodeURIComponent" call on the text buffer might result in too large of a string for setting "window.location" to handle once there are too many characters in the buffer; removing all newlines and putting the script in one line resulted in the same problem. To fix this, giving BYOND the script in some means other than through the URL would probably be necessary.

**Comment by Crazylemon64** [comment]
Looks like what -tg- had, before NTSL was removed completely, was the winshow() built-in BYOND proc. Unfortunately, I don't think that's going to work here, so... Someone more experienced with web development may be able to help here.

**Comment by tigercat2000** [comment]
@Crazylemon64 Problem is, there isn't any other way to give BYOND the script.
Byond is a piece of fucking shit in every regard, so the only way to actually communicate between browser and code is via a fucking parameter in a byond:// link.

**Comment by Crazylemon64** [comment]
I think we, in a few other points in our codebase, make use of external libraries to get past stuff BYOND can't do. If we were, perhaps, to copy the code over to a cache on the server, then make BYOND read the data in with an external library call, we might be able to get around the "can only give BYOND data through url" problem

**Comment by Tastyfish** [comment]
The code could in theory also be broken up into chunks of a size that we know do work, send the chunks, and then reconstruct it on the server, sorta like TCP.

**Comment by monster860** [comment]
Yeah, how come no one tried changing it like that?

**Comment by Crazylemon64** [comment]
I am not familiar with web development!

**Comment by monster860** [comment]
Well, fun shit there. Anyways, I got that script above to compile after fixing a few errors, but I have trouble figuring out what it's supposed to do.

**Comment by monster860** [comment]
With GET requests, which is what was used before, the data sent to the server is encoded in the URL. With POST, the data is sent after the URL in the HTTP request. The code used before is actually not the right way to make a get request, so I had to put in the proper code so I could set method to POST.

**Comment by Crazylemon64** [comment]
@monster860 I think it's supposed to "markov chain", or use a repository of words to randomly generate messages, based on words it's given. So basically, it makes everyone not whitelisted sound like a chatbot, which says things with words that are often put after one another.

**Comment by Tastyfish** [comment]
@Crazylemon64 I believe monster860 was talking about the compiler's code, although yes, that is what the ntsl script does.

**Comment by monster860** [comment]
Well, it works with my patch.
