### ISSUE TITLE
QM Stamp  - wrong texture

### ISSUE THREAD

**Issue by Stephanov** [ParadiseSS13/Paradise#2781]
The QM's stamp; the one from his office, is using "large_stamp-ok" instead of "large_stamp-qm" when applied to a paper.

It is using the same smaller version on a piece of paper instead of a (presumably) intended reddish circle stamp.

**Comment by Plotron** [comment]
I *knew* there was something wrong with it!

**Comment by Tastyfish** [comment]
This is actually a mapping issue, the stamp in the office is actually the Granted stamp with a different named manually entered in. The real QM stamp isn't in the map at all for whatever reason.
