### ISSUE TITLE
Overeating Icon Never Goes Away

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2782]
If you're mildly hungry or starving and eat, then these icons will eventually correct themselves.

That said, if you overeat and get the overeat icon, no matter what, this icon will never go away.

**Comment by Aurorablade** [comment]
I don't think my screen object code touched that

**Comment by Ar3nn** [comment]
I do overeat as IPC a lot but I never notice the slowdown kick back in. I think it does go away over time as normal, maybe thats just an organic thing.
