### ISSUE TITLE
Footstep sounds

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#2786]
Security boot sounds overlap with the new footstep sounds, so its a weird mix of regular footsteps and security boots. @tigercat2000

**Comment by Tastyfish** [comment]
I would guess then that it's also the case for clown shoes.

**Comment by Fox-McCloud** [comment]
There's also the problem of being able to hold down the arrow key against something dense and the sound triggers, anyway.

AFAIK this doesn't happen with shoes, for some reason.

**Comment by Spacemanspark** [comment]
Incorrect, @Fox-McCloud, I've noticed it occuring with jackboots for awhile now.

**Comment by Fox-McCloud** [comment]
Fair enough. Wonder when that started.

**Comment by tigercat2000** [comment]
Intentional.
Mostly.
Actually, mostly "not worth trying to figure out the logic for since the two systems don't communicate at all"

**Comment by orelbon** [comment]
What about if using sec boots the sounds don't activate

**Comment by Crazylemon64** [comment]
Couldn't you cut out the jackboots sound from their section of the code, and put that handling into your own system?

**Comment by CrAzYPiLoT-SS13** [comment]
Fixed?
