### ISSUE TITLE
Claw Game bugs

### ISSUE THREAD

**Issue by FalseIncarnate** [ParadiseSS13/Paradise#2795]
Mostly reporting this here so we don't get a spam of duplicate reports.

Being disarmed/stunned while playing a claw game will make the window unable to be closed, permanently locking out that machine.

 If someone walks away from the machine, the game doesn't close, and thus cannot be played by others.

**Comment by Spacemanspark** [comment]
Moving the mouse AT ALL after the claw machine picks up a prize will immediately give you a game over.
Sometimes, it'll just game over randomly after picking up a prize, as well. (And by sometimes I mean a 50% chance.).

**Comment by FalseIncarnate** [comment]
That's not a bug. The game is rigged.

**Comment by Robertha89** [comment]
We should be able to hack it to remove the rigging... Also emag act

**Comment by FalseIncarnate** [comment]
Emag_act is planned for the future, might also introduce claw upgrades like I initially wanted if one of my ideas pans out (this part is lower priority)

**Comment by Spacemanspark** [comment]
Ohhhhhh.
