### ISSUE TITLE
Cultist Construct lights showing behind NarSie

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#2799]
Cultist Construct lights will be visible behind Narsie. Completely harmless but a bug nonetheless.

**Comment by TheDZD** [comment]
Could you elaborate on this exactly? From what I understand, this means that the red light emitted by cult constructs affect the tiles that Nar'Sie is on?

**Comment by tigercat2000** [comment]
cult constructs do not emit red light, they emit negative light

Their eyes glow in the dark, via layer hacks
Nar'Sie needs to be at a higher layer. Not really a bug anyways, just an unfortunate sideeffect.

**Comment by Ar3nn** [comment]
I don't really like the glowing lights to begin with. In the complete darkness that harvesters are establishing by default, they glow and nobody else does, so unless they're dumb enough to walk into you with a flashlight, boom, advantage. I want some sort of night vision, thermal vision, movement sensor, something to show me a target when they walk into thirteen of us while we can't see them, and we all end up robusting each other trying to find him.

**Comment by Earthdivine** [comment]
>Could you elaborate on this exactly? From what I understand, this means that the red light emitted by cult constructs affect the tiles that Nar'Sie is on?

This is exactly what happens, what Tiger said is the correct fix.
