### ISSUE TITLE
Atmos Computer and Crew Monitor do not display map.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#2806]
![image](https://cloud.githubusercontent.com/assets/6721066/11731787/0af0d97e-9f6c-11e5-8451-45745296277f.png)
The crew monitor displays the same blank map. I can mouse over the alarms and click to access them just fine, but I can't see their icons.

It's a local issue with my IE's javascript (I'm still on IE9.) I receive the following error every few seconds when attempting to view the maps on a local-hosted server.
![image](https://cloud.githubusercontent.com/assets/6721066/11731760/d1083b30-9f6b-11e5-8f3e-1e29f6c9ffb2.png)

**Comment by TheDZD** [comment]
@tigercat2000 Any ideas about this?

**Comment by tigercat2000** [comment]
probably unsanitized byond special characters in the nano data @TheDZD

**Comment by Tastyfish** [comment]
All of the browser content runs in ie8 mode, so your ie version *shouldn't* matter if >= 8; was this on the real server or running it locally? It seems like weird things can happen with passing data in the complex nanoui screens if running the server locally sometimes.

**Comment by IAmBigCoat** [comment]
The error pops up when I run locally, but the maps are equally nonfunctional no matter where I am.

**Comment by CrAzYPiLoT-SS13** [comment]
Closure when?

**Comment by IAmBigCoat** [comment]
Not to be that guy, but it still doesn't work for me on the live server. The invalid character error must have been unrelated to the map not displaying. The master list of air alarms DOES work for me now, though. So that's nice.
Updating my local repo now and poking at it.

**Comment by IAmBigCoat** [comment]
![image](https://cloud.githubusercontent.com/assets/6721066/12250805/f3c89cf6-b897-11e5-8ccd-9e8addac9983.png)

New/different error when on local hostin'. Now is the time for the rabbit hole.
Nano.js's char 4705 in my cache corresponds to line 29 in [nano_base_callbacks.js](https://github.com/ParadiseSS13/Paradise/blob/master/nano/scripts/nano/nano_base_callbacks.js#L29). Same function calls, all the variable names are single letters. I assume that's just how nano gets packaged and sent to the client.

The only thing that looks strange in the nano.js cache file around that area is the fact that the variable name "t" is used for a number of different things. It corresponds to nano_base_callbacks'  _baseBeforeUpdateCallbacks variable (Line 6,) updateData (Line 10,) and obj (Line 27.)

I have no idea why this only breaks for me.

**Comment by tigercat2000** [comment]
@IAmBigCoat `nano.js` is uglified and minified by a javascript parser, it shortens everything as much as it can get away with, such as `t`

That object should never be null, though, which is weird.

**Comment by Fox-McCloud** [comment]
Try clearing your BYOND cache.

**Comment by IAmBigCoat** [comment]
Did several times.
Everything being t is the only thing I could think of. I'm not tremendously familiar with JS, but usually terrible things happen when you have more than one variable with the same name.
It otherwise looks totally fine.
