### ISSUE TITLE
Being attacked in shuttle wall lockers

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#2808]
I only notice this in the escape/crew transfer shuttle because that's the only time I ever want to hide in lockers. I don't think you're supposed to be able to open those emergency lockers but you can via right-click, as well as close them.
When you are "hiding" in one of these lockers you can still be attacked by pretty much anything. I got wrecked by a goliath once I believe and only recently got shot with a syringe filled with sleepy chems.

Also I notice those same emergency lockers don't take up any space but when you open and close them by the right-click, they act like a normal locker and become solid when closed. Can they be given a look at maybe?

**Comment by Spacemanspark** [comment]
It's somewhat intentional, but buggy.

**Comment by taukausanake** [comment]
Could someone explain it a bit more?

**Comment by Robertha89** [comment]
It's technically a closet. But for objects. While the icon is on the wall. The actual closet is on the floor. When you hide mobs in it the closet suddenly gains density. Which technically is a bug or an oversight.

**Comment by tigercat2000** [comment]
it's technically a feature
as someone did make it possible
but it's really goddamn buggy, and doesn't use the right icons

**Comment by Spacemanspark** [comment]
I'll try fixing it.

**Comment by Spacemanspark** [comment]
I have fixed this, making PR.
