### ISSUE TITLE
Tile frost overlay puts the floor tile above anything else on that tile.

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2809]
Just like it says on the tin, any tile with the frost overlay on it, you have to alt click to get anything done.

**Comment by FalseIncarnate** [comment]
Can confirm, definitely is on top of girders.

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

Yeah, this is problematic as it makes seeing things during breaches very difficult.

**Comment by Spacemanspark** [comment]
Ponies is already aware of this, we told him in OOC yesterday.

**Comment by Ar3nn** [comment]
kek Fox actually thats exactly how I noticed it. Someone bombed the disposals space loop and the vacant office, and I was an engiborg trying to help patch the breach. But yeah, guess I'll close it if Ponies already knows.

**Comment by Fox-McCloud** [comment]
nah, it's not fixed--doesn't matter if he knows or not--these are to be closed when the issue is resolved, not when someone is notified.

**Comment by Ar3nn** [comment]
Oh, alright. Sorry for the mistake.

**Comment by Fox-McCloud** [comment]
no problem
