### ISSUE TITLE
pAIs inside PDAs cannot be heard whispering

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#2810]
if a pAI is in a PDA the holder of the PDA cannot hear the pAI if it whispers

**Comment by TheDZD** [comment]
Saycoooooooooooooooooooooode!

**Comment by taukausanake** [comment]
You can put a pAI inside a PDA? I did not know that. Anything else affected by this? Any alerts that the pAI might make like when searching for one or when it wipes itself? Maybe not say code but would be annoying
