### ISSUE TITLE
Vampire Passive abilities don't work anymore

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#2812]
What it says on the tin really, vampires passive thermal powers and other passives don't actually trigger properly.

**Comment by tigercat2000** [comment]
fuck me sideways

more details please, a list of everything that doesn't work

**Comment by Ar3nn** [comment]
Well, I'm at least pretty sure the immunity to holy still works.

**Comment by theColdflame** [comment]
I was the victim of this, didn't get themals or upgraded rejuv

leading to me dying before getting 500 blood, so not sure if the last one still works

actives were fine

**Comment by Tastyfish** [comment]
This was fixed by #3541.
