### ISSUE TITLE
Voice Analyzers and Emotes

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2815]
Voice analyzers are unable to detect emotes and register them as something said/stated as a potential trigger for them---thereby limiting the scope of their effectiveness.

**Comment by Tastyfish** [comment]
Does it make sense for voice analyzers to trigger from emotes?

**Comment by tigercat2000** [comment]
this isn't even slightly a bug

not only is it a terrible idea, emotes send messages directly to mobs, only exception is implants, which are snowflaked into human/emote

**Comment by Fox-McCloud** [comment]
@Tastyfish 

For some emotes? yeah--particularly audible ones like *gasp, *scream, *fart, *cry, etc---as they would have recognizable and distinctive waveforms----others, like *flip, *blink, *twitch, etc wouldn't, butttt that may be pushing the complexity and snowflake of things.

**Comment by TheDZD** [comment]
Unless emotes are differentiated between audible and visible, this isn't really a bug as much as an oversight.

**Comment by Tastyfish** [comment]
Oh yeah, forgot that the game does differentiate between visible and audible emotes.

**Comment by Tastyfish** [comment]
Making a generalized fix that could be useful to other objects.
