### ISSUE TITLE
Vox can wear tails

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2818]
![image](https://cloud.githubusercontent.com/assets/7663878/11762368/7c516218-a0e4-11e5-918a-448a52964f3e.png)
So eh, Vox can wear tails.

HOW TO REPRODUCE!!!
1. Pick species Dogbeast.
2. Choose accesory
3. Change species to Vox.
4. Choose what tail.
5. Enter game.
6 Say"*wag

Recommended fixes! (pick one)
1. Species blacklist!
no really, tails should only have a species blacklist, i mean certain tails both dogbeast and catbeast can share.
2. Make it available for everyone!

**Comment by tigercat2000** [comment]
they already have a species blacklist, i fucked up with the refreshing and wiping

**Comment by Spacemanspark** [comment]
That's a horrifying monstrosity.

**Comment by orelbon** [comment]
pls fix i saw this earlies today in game. MUH EMMURSIONS

**Comment by fludd12** [comment]
Haven't seen this glitch in a while, is it still possible?

**Comment by Aurorablade** [comment]
@Crazylemon64 @Fox-McCloud pretty sure is no longer an issue

**Comment by taukausanake** [comment]
Turn it into a feature. Tail organs when?
