### ISSUE TITLE
While inside a pod, you can still freeze while in space.

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#2819]
As said on tin, only way to counteract it is to wear a hard suit (w helm) while podding around.

**Comment by tigercat2000** [comment]
There's a setting that switches between internal airtank and external air, are you sure it was set to airtank?

**Comment by TheDZD** [comment]
@tigercat2000 This has definitely been occurring with the internal air tank toggled on.

**Comment by Fox-McCloud** [comment]
think I know the issue:
