### ISSUE TITLE
Can't Drag yourself to cloning/DNA scanner

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2829]
@Crazylemon64 

You cannot mousedrop yourself into a cloning/DNA scanner---someone else can do this to you, but you can't do it to yourself. 

You can mousedrop yourself into body scanners, sleepers, operating tables, and cryo tubes.

**Comment by Crazylemon64** [comment]
eh wha

I'll take a look, probably have something hammered out later this evening sure
