### ISSUE TITLE
Vampires & Closets

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#2833]
According to CodenameGordan, who for whatever unknowable reason doesn't want to report this himself, when a Vampire closes themselves inside a closet or similar object, they lose access to the tab that displays their vampire abilities, meaning they can't hide in a locker to rejuvenate, summon bats from inside, etc.

I haven't tested this myself, because I don't like playing Vampire much. And by much, I mean ever.

**Comment by VampyrBytes** [comment]
Can't reproduce this... my tab doesn't disappear when I go in a closet.
