### ISSUE TITLE
OOC and ahelp verbs

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#2834]
When joining the server after round ends, or just joining in in general, the ooc and ahelp verbs take forever to load they usually appear at 80 seconds left in the round count down. probably caused by #2824

**Comment by tigercat2000** [comment]
Almost certainly not caused by #2824, it deals exclusively with UI's.

**Comment by Spacemanspark** [comment]
I don't even thing we've patched yet.
Though I could be wrong.

**Comment by orelbon** [comment]
@tigercat2000 i dont know it started happening around the time that got patched in.

**Comment by tigercat2000** [comment]
Can you specify "load"?
The verbs do not appear for a while?
The verbs don't work for a while?

**Comment by orelbon** [comment]
it give you this when using f1 or f2 and typing in ooc doesn't do anything either. it stays like this for around a minute and a half.
![bug](https://cloud.githubusercontent.com/assets/12041669/11772625/386da760-a1ec-11e5-858d-461a72a8c750.PNG)

**Comment by tigercat2000** [comment]
Well, that is definately one of the stranger bugs I have seen.
Just tested it, doesn't seem to happen to me, though, which is odd.

**Comment by orelbon** [comment]
should i try and clear my cache?

**Comment by tigercat2000** [comment]
... Huh.
Further testing, it happens to non-admin accounts, but not admin accounts.

**Comment by orelbon** [comment]
something smells funky here.

**Comment by orelbon** [comment]
Clearing the cache does not work.

**Comment by NTSAM** [comment]
This happens to me too.

**Comment by tigercat2000** [comment]
What version of byond are you two running?

**Comment by NTSAM** [comment]
I believe I'm using 509.

**Comment by Tastyfish** [comment]
Using 508, have same problem. I think it's literally all of the client verbs, ie entire preferences tab, etc

**Comment by tigercat2000** [comment]
@Tastyfish It's not all of them, not for me anyways, as some do show up, some do not, notably OOC and Adminhelp

**Comment by Tastyfish** [comment]
Also `.Toggle-hotkey-mode`, `nanoclose`

**Comment by orelbon** [comment]
using 509 as well

**Comment by tigercat2000** [comment]
Found it, missing spawn() in client procs.
well i still need to test it but
