### ISSUE TITLE
Possible White Ship bug

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2840]
I know the entire shuttle system is getting overhauled, but I'd like to point out that right now, the White Ship computer, at least when you point it at the station, takes you to one of the asteroid z-levels instead. Is/Was this intended for some reason?

**Comment by Spacemanspark** [comment]
I'm not even sure how that's possible. Amusing, though.
@tigercat2000

**Comment by tigercat2000** [comment]
ah god who knows
will be fixed by #2719

**Comment by NTSAM** [comment]
yay

**Comment by Ar3nn** [comment]
wat @NTSAM

**Comment by Fox-McCloud** [comment]
Wont' be fixing this one; not worth due to the shuttle overhaul coming.

**Comment by Ar3nn** [comment]
Alright, then.
