### ISSUE TITLE
Alert code gamma does not stop crew transfer shuttle

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#2850]
Like red does

**Comment by tigercat2000** [comment]
as per usual, will be fixed when I get to redoing the voting part of #2719

**Comment by Regen1** [comment]
"as per usual"?
Whatever, good enough

**Comment by tigercat2000** [comment]
"as per usual" meaning "pretty much every bay shuttle issue is going to be fixed by bay shuttles being ripped out entirely"

**Comment by TheDZD** [comment]
Red alert doesn't stop he crew transfer shuttle anymore either, so this isn't exactly a bug.
