### ISSUE TITLE
Thanksgiving is over

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#2851]
@Fox-McCloud

**Comment by tigercat2000** [comment]
I assume this is in relationship to the bar map changes- which can't be fixed until the map freeze is over.

**Comment by Regen1** [comment]
@tigercat2000 The PR can still be made, also it should've been fixed before your PR was even made.

**Comment by tigercat2000** [comment]
@Regen1 There isn't any point to making the PR, as map conflicts go both ways, and the map work would have to be redone after the shuttles are merged (most likely)

**Comment by Regen1** [comment]
Perhaps the maptool thing works different than what I originally though, oh well.
This issue will still be open for when your PR goes through

**Comment by Plotron** [comment]
Does this mean... no christmas this year?!

**Comment by orelbon** [comment]
can't you just revert the pr for christmas when you are ready to merge so it dosent conflict?

**Comment by Fox-McCloud** [comment]
Map freeze means this isn't going to happen.

**Comment by Regen1** [comment]
You forgot a "yet" there
