### ISSUE TITLE
NE part of Central Primary Hallways has 2 APC's

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#2858]
What it says on the tin, there's an APC near the bridge entrance, and one fore of it in `/area/hallway/primary/central/ne`. They conflict and do weird things when one breaks.

**Comment by orelbon** [comment]
this is gonna have to wait until tiger finished the shuttle port

**Comment by Tastyfish** [comment]
Yes, just documenting it because I would have definitely forgotten by then.
