### ISSUE TITLE
Chem Dispensers automatically ejecting Beakers

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#2861]
Short description,
Chemist inserts beaker with 40u of reagents inside it
5 seconds passes
Beaker gets automatically ejected
This happens to both dispensers in chemistry and with different beakers.

**Comment by Crazylemon64** [comment]
Have been unable to reproduce. Is it only with specifically 40?

**Comment by Crazylemon64** [comment]
Unable to reproduce. Can you specify more, @DavidRossii?

**Comment by Fox-McCloud** [comment]
used chems a lot---so have a number of others; haven't seen this.

Sure it wasn't just an admin messing with you? =p
