### ISSUE TITLE
IPCs can be humanized

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#2862]
I unno why nobody reported this, it's been around for awhile and it's even on the forums as a guide.
(http://nanotrasen.se/phpBB3/viewtopic.php?f=15&t=6229)

Copied from the topic, the steps to replicate are as follows:

Stage 1 of surgery, obtain one souless body with head containing a brain
Stage 2 Remove the head from the creature
Stage 3 Remove the IPC's head from frame
Stage 4 place creatures head on IPC
Stage 5 Remove the brain from the head of the creature on the ipc frame, as the consciousness has transferred from the positronic brain to the organic brain.
Stage 6 obtain a humanized creature
Stage 7 peraform brain replacement surgery
Stage 8 Clone the finished product for stable infection free permanency.

when this is all said and done, the IPC will now be a member of whichever species you put them in.

**Comment by Spacemanspark** [comment]
@tigercat2000
This is a great sin to Synthetica.

**Comment by tigercat2000** [comment]
why do you blame me, not my fault that someone decided to make a non-brain brain and didn't account for the consequences

**Comment by Spacemanspark** [comment]
I thought you did the frankenstein stuff.

**Comment by Crazylemon64** [comment]
Working on a fix now

**Comment by Spacemanspark** [comment]
Yee haw

**Comment by NTSAM** [comment]
yay

**Comment by Ar3nn** [comment]
All the IPCs are up in arms. I think someone halfway did this to me one round, then just aborted it and put my head back on.

**Comment by NTSAM** [comment]
Some dude said he forcibly made two permabrigged IPCs into humans just cause perma.

**Comment by Spacemanspark** [comment]
@NTSAM That's pretty shitty.

**Comment by Crazylemon64** [comment]
r00d d00d. Well, I think I've got something working, so THAT nasty reign of terror is at an end. PR in a few minutes

**Comment by Spacemanspark** [comment]
Also, @tigercat2000 
If the brain was in the head, then they would literally die in four to five punches or two laser blasts.
That's pretty much all it takes to knock off an IPC's head.
There's a fine line between 'challenging' and 'thefuckisthisgarbageoutthewindowwiththecontroller'

**Comment by Crazylemon64** [comment]
Hold on, there's slight delays while I adjust surgery organ removal code to not expect a given organ to be the primary organ

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

If you move the positronic brain back into the head, then you'll want to make IPC heads printable and make it so the toreso is *not* printable.

**Comment by Spacemanspark** [comment]
I don't think they're doing that, @Fox-McCloud

**Comment by Crazylemon64** [comment]
@Fox-McCloud I'm not moving it back into the head, don't worry. I'm just making it so that organ surgery can now accommodate for more than one of the same organ class being in the body.

**Comment by Spacemanspark** [comment]
Indeed, @Crazylemon64

**Comment by Stephanov** [comment]
-Attaching synthetic brain to organic nerve ends using modern technology
-Cloning the other race's host body as a substitute for DNA
-Moving the "mind" from the old body to the new

I don't see this being a bug, rather than a feature.

**Comment by Crazylemon64** [comment]
Nah, it's a limitation of our code which expects that you don't insert more than one of the same organ at a time. For instance, it leaves the posibrain stuck in a limbo inside the torso, where you can't interact with it with robotic organ removal surgeries. Anyways, this fix will also let you have more than one of other organs without weird badness happening, so prepare for invader zim-like shenanigans once the not-terrible organ code rolls out, at which point I'll look into having multiple organs take up backup for one another.

**Comment by Deanthelis** [comment]
I, for one, enjoy bizarre surgery shenanigans.
I enjoyed playing with self-surgery when it existed, I enjoy giving Pun-Pun robotic arms, lower body and legs, and I enjoy mounting brainless monkey heads on IPCs who frustrate me when I am a traitor.

This is tangentially related, but replacing an IPC head with a head not containing a brain, but containing eyeballs, does not restore the IPC's eyesight. I don't know if this is on purpose or should stay that way, I'm not commenting on balance here, just reporting that factor.

**Comment by Crazylemon64** [comment]
Yeah, the species have a special "vision organ" variable, which determines which type of organ is used for vision. It's only used with IPCs, however, whose "Optical sensors" are tagged as "optics", while eyes in every other species are tagged as "eyes". I'd like to do something about it, but I'm not touching organ code too much until @Aurorablade gets around to the organ overhaul.
