### ISSUE TITLE
Guardian Talk is Not Properly Logged

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2863]
As it says on the tin: guardian chat/talk is not properly logged.

It just shows up as ":U" in the administrative logs.

**Comment by Spacemanspark** [comment]
Quick, grief everything!
@Aurorablade

**Comment by Ar3nn** [comment]
So you can't tell at all what anyone says in guardian communication? That's a pretty serious issue.
