### ISSUE TITLE
Spaceacilin completely cured a virus 

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2872]
I don't know the details, because I wasn't there for most of it, but I was virologist attempting to cure an rng virus, and while I killed the warden with radium from an accidental miscalculation and slow injection process, the CMO was buying the captain time with spaceacilin, and he eventually just showed no symptoms at all, med hud showed him not infected. I scanned him for antibodies and there were none, yet his blood cured the crew with no issues.

**Comment by TheDZD** [comment]
If memory serves, spaceacillin has a chance to outright cure stage 1 viruses.

**Comment by Ar3nn** [comment]
I tried to get the CMO that shift to comment on the issue, but they didn't so I have no further information on the issue. I'm pretty sure the captain was infected around the same time as the warden and he was stage 3 going into 4 when I killed him with radium.

**Comment by Fox-McCloud** [comment]
Not a bug; deliberate feature.

If it's stage one and passes a probability check, it will cure the virus.

**Comment by Ar3nn** [comment]
As I said, I was pretty sure it wasn't stage one, but not entirely since I wasn't treating him. It could've been delayed enough to work out that way.
