### ISSUE TITLE
Particle Accelerator Failure

### ISSUE THREAD

**Issue by Dragonephobe** [ParadiseSS13/Paradise#2873]
I was trapped between the Particle Accelerator's computer and a Space Heater, I attempted to disassemble the computer in order to get out. In disassembling the computer, rather than my wire cutters removing the cable as they tend to, it opened a GUI, thinking this was just a paradise thing (I'm relatively new and don't disassemble the PA too often) I cut the cables, then when reassembling the computer, I got an error when running the scan, it asked me to check the wire connections. I opened the panel and, lo and behold, when I used my wirecutters they simply removed the wire, I tried using a multitool but still could not reopen the GUI, leaving all of the power to solars. Small bug that caused a sizable problem, either remove the GUI or make it openable.

**Comment by TheDZD** [comment]
The PA control computer isn't an actual computer console, just its sprite, thus it doesn't disassemble like normal computers. The wires GUI it gives is similar to the protolathe, and I can't quite seem to follow what you did to "break" it. Chances are that one of the particle accelerator sections was left unwired. If you could get the exact message that was output when you tried running the scan, that would help.

**Comment by Dragonephobe** [comment]
It was wired correctly.

**Comment by TheDZD** [comment]
Might be an issue with one of the parts not getting a specific variable set, as I've seen something similar happen once, but couldn't get it to happen again, and I can't for the life of me remember what variable it was.

**Comment by Fox-McCloud** [comment]
This happens when you pulse/cut a wire on the *panel* of the accelerator---you would have to cut+mend all the wires and things would be ok.
