### ISSUE TITLE
IPC's can be fat

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#2875]
![ss 2015-12-18 at 12 33 00](https://cloud.githubusercontent.com/assets/13933611/11886145/f92db6d6-a51e-11e5-945a-b3a4240afef3.png)

Too much junk in the recycle-bin I think.

**Comment by Fox-McCloud** [comment]
lol.

**Comment by Spacemanspark** [comment]
Hahahahahaha.
How even?
I've overloaded myself many times, never gotten fat.

**Comment by DavidRossii** [comment]
I think it may be the disability choice of being fat at roundstart.

**Comment by Spacemanspark** [comment]
Ah.

**Comment by Crazylemon64** [comment]
I get the idea you can toggle this for other species that normally can't be fat, either - such as Vulpkanin, Vox, or anything else that's not a Grey, Human, or Taj. Not sure how the bare torso looks with this active, though.

**Comment by KasparoVy** [comment]
Lmao, I was in this round and I thought it was a human for the longest time at a glance.. Holy shit this is hilarious.

**Comment by orelbon** [comment]
Not enough fat ipcs 11/10

**Comment by AceMcLazer** [comment]
Just leave it in. Hes not fat! he just has a big chassis! :frowning:

**Comment by Fox-McCloud** [comment]
I've not seen this in eons, and not sure it can even be reproduced.
