### ISSUE TITLE
Candy Cane Sprite - White part is transparent

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#2876]
![ss 2015-12-18 at 12 34 57](https://cloud.githubusercontent.com/assets/13933611/11886169/44dbbea2-a51f-11e5-8377-8270845bd243.png)
![ss 2015-12-18 at 12 36 33](https://cloud.githubusercontent.com/assets/13933611/11886189/6f441018-a51f-11e5-85d3-d9777b633c28.png)

Should show it well.

**Comment by Spacemanspark** [comment]
There is no Christmas Spirit on the Cyberiad.

**Comment by FalseIncarnate** [comment]
This was a derp on my part. I re-used the existing candy cane sprites which were made for custom-filling versions, and did not realize they had transparency on the stripes because of the while background of dream-maker. simple fix at least.
