### ISSUE TITLE
[Footsteps] Small Blood droplets and Spider Blood

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2878]
Maintenance footstep noises can be heard on metal floor tiles when there is blood droplets or spider blood on the tile.

**Comment by tigercat2000** [comment]
somehow I don't think it's related in any way
someone probably crowbarred the tile up and placed it back down, which doesn't clear the sounds, known issue

**Comment by TheDZD** [comment]
Yeah, probably #2786 in disguise.
