### ISSUE TITLE
Golems glitch syringes

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2879]
I was virologist and actually did my damn job for once, made a beneficial virus and began distribution to the crew. A golem came in at one point wanting some, and when I injected it, it didn't remove the blood from the syringe. So far I only injected one person afterward, but it didn't remove the blood that time either, effectively giving me infinite blood samples of the virus.

If it helps, it says the following upon successful injection:
You inject  units of the solution into Squish Master Z. The syringe now contains 5 units.

Edit: It finally took the blood after the third injection.

**Comment by Fox-McCloud** [comment]
shouldn't be a problem any longer.
