### ISSUE TITLE
Virology patient closets

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2880]
I assume they're an artifact of an earlier time, when the code for lockers and such wasn't clean, but they don't detect an ID unless its in your active hand, making using one as my closet of shame to hide all the bad viruses I'm not going to use more time consuming.

**Comment by Fox-McCloud** [comment]
These are personal lockers, and they're different from other lockers---they bind to that ID *specifically*, and are the only known lockers that do this.

**Comment by Ar3nn** [comment]
So this is an intentional "feature?"

**Comment by Fox-McCloud** [comment]
I believe so.

**Comment by Ar3nn** [comment]
Alright, well...I don't get why viro would have closets designated like that, but if you say so, I'll take your word for it. Thanks for explaining it.

**Comment by Tastyfish** [comment]
They are private closets for patients/guinea pigs that have to live there to put their personal stuff in.

**Comment by Ar3nn** [comment]
Like I said, I use one to stash unfriendly virals >< That's about it.
