### ISSUE TITLE
Braaaainnnnzzzzzzz!

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2881]
Apparently there was a glitch in the gibbing process that created a brain twice when someone was gibbed. Both brains were delivered to medbay intact, I threw them in a freezer and the CMO was actually the one that noticed the name. Despite my utter lack of knowledge on circumstances, I was told to report it, so here it is. Maybe check the admin logs for 4:20 EST?

**Comment by TheDZD** [comment]
No idea how to reliably reproduce this.

**Comment by Ar3nn** [comment]
I know nothing about how it happened, myself, but someone said do, so I did.

**Comment by Fox-McCloud** [comment]
report this again with more details if you see this happening again, please.
