### ISSUE TITLE
Shuttle/Pod Bug Megathread

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2883]
There's bound to be bugs with so many changes, so post them here.

Known
- ~~Pod doors do not automatically bolt when they launch~~
- ~~Cannot use any of the departmental shuttles~~
- ~~CentComm shuttle dock doors cannot be opened~~
- ~~Cargo shuttle becomes frozen~~
- ~~ERT cannot open the doors/access their own shuttle~~
- Shuttle ETA Status is unlabeled

**Comment by ZomgPonies** [comment]
Question: Sniper fairy/(Katyusha Shazbot) (?) (PP) (VV) (SM) (FLW) (CA) (REJT) : update on mining shuttle, it won't let miners in

**Comment by Ar3nn** [comment]
Did you have to revert the ui on the cargo request console or something? Or is that just the UI that /tg/ uses?

**Comment by Tastyfish** [comment]
Haven't tested for accuracy/sense, just relaying:
OOC: Eclipticdawn: All the airlocks for the cargo shuttle are also locked.

**Comment by Fox-McCloud** [comment]
Yeah, so...over in Bayland, ALL shuttle doors have external access/EVA access and access is handled by the controller itself or the shuttle console. That's different, here.

SHould be fixed very soon.

**Comment by tigercat2000** [comment]
>Did you have to revert the ui on the cargo request console or something? Or is that just the UI that /tg/ uses?

yes, unfortunately

**Comment by Taaketa** [comment]
The shuttle at Centcomm at travels to the station on Port Bay 1 can be sent by regular crew. The blast doors cannot be opened by regular crew, however.

**Comment by tigercat2000** [comment]
>The Adminstration shuttle and Ferry Shuttle at Centcomm can be sent by regular crew. The blast doors cannot be opened by regular crew, however.

Intentional.. mostly.
The ferry is intended to be open-access for a one way trip- IE, you can get to the station with it, but an admin has to grant your request to get back.
The admin shuttle, well, I don't know what kind of access requirements should be on admin stuff.

>Another issue is the the cargo shuttle is always exposed to space due to the conveyer cargo doors not existing.

There is a PR up for this, I believe.

**Comment by KasparoVy** [comment]
Cargo shuttle's coming in at space temperature and with no atmosphere

**Comment by Fox-McCloud** [comment]
@KasparoVy 

Fixed in an existing PR, but hasn't been patched in.

Also the problem with the doors not being openable at CentComm, once the shuttle docks? Also fixed.

**Comment by Fox-McCloud** [comment]
damn misclicks.

**Comment by Ar3nn** [comment]
Probably not something that should be asked here, but is there a reason the escape pods have their own end-game landing zone differing from the shuttle?

**Comment by TheDZD** [comment]
Apparently the ERT members don't have access to open the doors of their own shuttle.

**Comment by Tastyfish** [comment]
Shuttle ETA on status tab isn't labelled, it's just the time by itself.

**Comment by Plotron** [comment]
What @Tastyfish said.
