### ISSUE TITLE
RIPLEY mining vision is spotty, toggles on/off repeatedly

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2889]
Get in a RIPLEY, find that your mecha meson sight frequently toggles on and off repeatedly. Not sure if this is the sort of thing that will be addressed by @Aurorablade 's HUD refactor or not.

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Aurorablade** [comment]
as in it actually toggles? it pulses? its supposed to pulse.

**Comment by Fox-McCloud** [comment]
This is just how it works; it pulses SEE_TURFS whenever the scanner actually scans.

Does this happen when you're actually wearing mesons?

**Comment by Crazylemon64** [comment]
Ah, in that case, I guess it's working as intended, though it's not what I expected. Alright, closing this.
