### ISSUE TITLE
Possible limb bug?

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2891]
It's a purely visual/ui effect, but when an IPCs hands/head get taken off and then put back on while they are conscious, it puts a hand/head sprite in the hands slot somewhere.

**Comment by tigercat2000** [comment]
It's part of a long-running bug of random shit ending up in the client.screen when it's not supposed to. No way to resolve it, really.

**Comment by Ar3nn** [comment]
Okay. Sorry.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/silicon/robot/life.dm#L265-L267>Ahahahahaha</a>
Google code, what are you doing?

**Comment by tigercat2000** [comment]
So it turns out, BYOND isn't *that* bad... it's always old code. Goddamnit oldcoders.
