### ISSUE TITLE
Virus causes diona to burn?

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2895]
I couldn't take their blood to check, but I released a virus and it caused all the dionae on the station to start burning despite all symptoms being objectively positive. People keep saying it could've mutated, but I thought all viral mutations got removed from the code.

**Comment by Spacemanspark** [comment]
I think one of the symptoms was causing everyone to heat up. The glowing virus, perhaps?
That will RIP all dionae.

**Comment by Fox-McCloud** [comment]
Virus induce a fever---Diona have very low body temps and very low thresholds to trigger being "too hot" and burning up.

Short end of the story: Virues and Diona never mix, even if it's a "good" virus.

**Comment by Ar3nn** [comment]
All virals cause fever? Well, alright, I learned my lesson. RIP.
