### ISSUE TITLE
Cyborgs Taking Oxyloss Damage

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#2897]
Haven't had the time to confirm this, but apparently cyborgs can take oxyloss damage from blobs with reagents that do so. Posting this here so that it isn't completely forgotten.

**Comment by Crazylemon64** [comment]
It looks like the Lexorin Jelly; As it stands cyborgs have code for special effects when suffocating, but I'm not sure if this is the sort of situation that should trigger it or not.

**Comment by Crazylemon64** [comment]
Pinging @tigercat2000 because they seemed to have opinions on cyborgs having oxyloss factor into health in Life() or not

**Comment by tigercat2000** [comment]
i was just concerned over how bay had two differing calculations for cyborg health, god knows which is correct
