### ISSUE TITLE
Cryopods doesn't seem to work at all

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#2898]
They won't move people into storage, the error "ADMIN LOG: Cryopod in the Dormitories could not find control computer!" keeps spamming Admin logs

**Comment by tigercat2000** [comment]
This is probably pretty high priority

**Comment by TheDZD** [comment]
Welp, `[find_control_computer](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/cryopod.dm#L252-L253)` isn't finding the control computer.
