### ISSUE TITLE
 Antag HUD Megathread

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2899]
Apparently if a changeling is borged he gets permanent antag HUD status

@Aurorablade

**Comment by tigercat2000** [comment]
obviously the issue is that you are somehow BOrging people

**Comment by TheDZD** [comment]
Fix'd.

**Comment by Fox-McCloud** [comment]
alright, so an addendum; sometimes singular traitors, for unknown reasons, will not show up.

For example, in the round I"m spectating, one traitor has his HUD displayed, while another does not.

**Comment by Crazylemon64** [comment]
Uh are you sure that fixed every single HUD problem this sems t be a megathread

**Comment by Fox-McCloud** [comment]
No, I doubt that, but the way issues open/close, this is all automatic.

**Comment by Plotron** [comment]
@Fox-McCloud, @Crazylemon64:
1. MedHUD no longer informs you when it's toggled.
2. It's glitchy - it doesn't work for everyone, the MedHUD sometimes fails to display for certain people (I don't know more, sorry).
3. The SecurityHUD (as a part of AntagHUD) is now below the MedHUD overlay - job icons are obstructed.
4. AntagHUD doesn't let you inspect AI's laws anymore.

**Comment by Aurorablade** [comment]
@Plotron to clerify, you are talking about observers or?

**Comment by Plotron** [comment]
@Aurorablade
Yes, all told from a ghost's perspective.

**Comment by Fox-McCloud** [comment]
closing this for individualized reports.
