### ISSUE TITLE
Bottles cannot be broken over the head of simple mobs

### ISSUE THREAD

**Issue by Zilenan91** [ParadiseSS13/Paradise#2906]
I unfortunately found this out when I was being swarmed by 5 or 6 clowns, leading to my death.

**Comment by Plotron** [comment]
Rubber heads don't break.

**Comment by Fox-McCloud** [comment]
you'd have to do some pretty snowflake checks for this, considering a lot of simple animals don't have heads and a lot of them can't really be weakened, effectively, either.

**Comment by Zilenan91** [comment]
I think /tg/ made it so bottles can be broken on simple mobs, but it doesn't stun them or hit the head in particular.
