### ISSUE TITLE
Solid Plasma + Circuit Imprinter

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#2908]
Circuit imprinters will not allow you to add solid plasma to them, despite there being recipes that require them, like experimental hull shield equipment.

**Comment by Crazylemon64** [comment]
eh wha-?

**Comment by Deanthelis** [comment]
It makes those shield generator/capacitors that are found in secure storage. They're nearly invincible, but yes, that's probably a good idea - or allow plasma to be put in the imprinter, so that future machinery can implement it as a cost.

**Comment by Fox-McCloud** [comment]
I'd just change the requirement from plasma to gold or diamond or something---it's literally the only thing that uses it.
