### ISSUE TITLE
Plasmaman blood vs syringes and blood drinks

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#2911]
Plasmamen appear to have blood, at least on the medical scanner(s).
However I find it impossible to draw blood using the syringe (unable to locate blood), or inject myself with someone else's blood (for instance: viral transfer - it says I'm injecting myself but it does nothing), or hell - I can't even drink blood in a glass - it says I'm drinking, but nothing really happens.

**Comment by Fox-McCloud** [comment]
errr, plasmamen shouldn't have blood; they have the NO_BLOOD flag....are you sure it says they have blood, on a scanner?

**Comment by Anticept** [comment]
Confirmed, handheld medical scanners show blood and 0 pulse. Probably shouldn't show either.
