### ISSUE TITLE
BRPED using RPED sprite when held in hand.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#2915]
Not entirely sure what led up to this point as I wasn't doing anything overly strange with the BRPED but at some point I noticed that it was using the RPED sprite in the hand of my character model despite it clearly being the BRPED in my hand slot when picked up.  It continued to do that for the rest of the round.

On the ground: http://imgur.com/z8EEnxQ
In my hand: http://imgur.com/YZeswMN

**Comment by Ar3nn** [comment]
It's done that for as long as I've known the BRPED was in the game, I didn't know they even had a BRPED hand sprite.

**Comment by Fox-McCloud** [comment]
not a bug. THe BRPED didn't have an in-hand before; it was changed so that it utilizes is parent in-hand, which looks the same as the RPED; a lot of items (clothing, guns, etc) re-use in-hands, particularly when they're so close to looking the same.
