### ISSUE TITLE
New canister painting system

### ISSUE THREAD

**Issue by fj45** [ParadiseSS13/Paradise#292]
Its great, and I really love being able to rename canisters properly, but it really needs a proper UI. (so I can see what I am changing and so I can edit only a single thing if I need to)

You also cannot make the fire fighting canister (CUSTOM) sprite for anything other then the primary colour.

**Comment by PJB3005** [comment]
you can't make the custom (or N2O for that matter) as layers other than primary because the difference in color between using them and using something like air or N2 was minimal enough for me not to bother

also, I might do an UI if I learn NanoUI

**Comment by fj45** [comment]
There is more then enough for a difference to be visible and it makes it impossible to build that type of canister.
