### ISSUE TITLE
Metastation: The Beer Keg is Skinned as a nuke. WTF

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#2923]
^

**Comment by Spacemanspark** [comment]
This is actually intentional.
No, I'm not shitting you, examine the item.

**Comment by tigercat2000** [comment]
It's fully intentional, nukekeg ftw

**Comment by Zolofty** [comment]
Hint- this is an excellent prop for maximum clowning, just beware of the consequences when the crew finally catches you.
