### ISSUE TITLE
Metastation: Barbershop lacks hair dye dispencer

### ISSUE THREAD

**Issue by johannhawk** [ParadiseSS13/Paradise#2924]
i cant fill my hair dye bottle as a barber without them!

as a sidenote, i would like a extra NT. brand hair dye bottle or two added to the barber.

**Comment by tigercat2000** [comment]
We have hair dye dispensers?

**Comment by johannhawk** [comment]
@tigercat2000 yes, but they only function with the hair dye bottle that spawns with the barber, and thats the only one i get besides hairgrownium and quantum hair dye.

forces me to pick one specific color and i need to run back to the dispenser to change it.
