### ISSUE TITLE
MetaStation: Lack of Sec Podbay.

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#2926]

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by FalseIncarnate** [comment]
I didn't touch this one because I have no clue where to slot this in (has to be external hull, but ideally connected to security. Not much room there because of the dorms and perma-brig.

Still an active issue.

**Comment by tigercat2000** [comment]
fixed by #3753 @TheDZD
