### ISSUE TITLE
Metastation: Lots of full windows, instead of rglass panes on the grilles

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2931]

**Comment by AceMcLazer** [comment]
They're Also Offensive to the eyes. The eyes that want to see the four panes and the Grille.

**Comment by Plotron** [comment]
... not this again!

**Comment by tigercat2000** [comment]
Intentional, the window spawners are forced to full-glass, as -tg- uses full glass and @Fox-McCloud requested I keep it as close to -tg- as possible.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

D-did I? I don't recall putting in very much input to Metastation other than repeatedly teasing you about full tile windows.

**Comment by tigercat2000** [comment]
@Fox-McCloud I thought you did, but maybe not. Either way, general thing about meta currently is that it has mostly kept it's -tg- style from the port.
