### ISSUE TITLE
Metastation: There are NO security belts in Brig Equipment Room 

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#2932]

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
Uh, don't these spawn in lockers and the secvend? Pretty sure Cyberiad doesn't have any security belts lying around.

**Comment by Tastyfish** [comment]
Yup, and metastation has 7 officer lockers and a SecTech vender.

**Comment by tigercat2000** [comment]
soo this can probably be closed right

**Comment by Tastyfish** [comment]
I would think so, I see no real difference between one station and the other's security officer equipment, beyond the lack of an EFTPOS scanner (Metastation doesn't have any, this should probably be a separate issue, if we care) and the lack of a megaphone, which nobody ever uses.
