### ISSUE TITLE
Metastation: Cables at certain locations do not stick

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2933]
* N of Maintenance robotics
* NW of medbay lobby
* E of Experimentor chamber
* Directly in front of Aft Port Solars

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
Could you specify what you mean by "do not stick"?

**Comment by Crazylemon64** [comment]
They fall off during gameplay without external prompting, and attempting to replace those cables just results in them popping off again.

**Comment by tigercat2000** [comment]
very strange

**Comment by CrAzYPiLoT-SS13** [comment]
Could it be changing the state, as afaik, we have a special state for
cables and pipes which make them invisible, correct?

**Comment by Crazylemon64** [comment]
I think that's plain-old `invisibility` setting, perhaps there's some map-tile cable conflict, though...

**Comment by FalseIncarnate** [comment]
I was unable to do anything with this report in my metastation fixes because the information provided was just far too vague. Please try to narrow down the problem tiles so we can better diagnose the issue and resolve it from there.

**Comment by tigercat2000** [comment]
This should probably be closed, as there's no way to reliably replicate it.
