### ISSUE TITLE
Metastation: The Turbine room is all access

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2934]
The door into the turbine room is all access or at least set to maintenance access.

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
Turbine room? Do you mean the incinerator room, to the southwest of atmospherics?

**Comment by Tastyfish** [comment]
If they do mean the incinerator, the access is indeed incorrect (maintenance instead of atmospherics).

**Comment by tigercat2000** [comment]
the turbine should be atmos access, and given that Meta is supposed to be much more -tg-ish, incinerator should probably be maintenance

**Comment by Tastyfish** [comment]
Then I think it's as intended then.

**Comment by tigercat2000** [comment]
Confirmed, this is 100% intended. @TheDZD
