### ISSUE TITLE
Metastation: Centcomm windows cannot be damaged or interacted with

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2941]
Tools cannot be used on Centcomm windows. Trappped in space by portal gun and tried to break back in using my tools to take down the windows. Couldn't interact with the windows using the tools.

Also could not smash the window using a fire extinguisher.

**Comment by tigercat2000** [comment]
This... is how it is on cyberiad, too, though? Centcom's windows are fake turfs, not real windows.

**Comment by Ar3nn** [comment]
Why are they on the station, then?

**Comment by tigercat2000** [comment]
@Ar3nn Well I don't know, according to this issue report, "Centcomm windows cannot be damaged or interacted with", which is correct, and one would assume "Centcomm windows" refers to "Windows on Centcomm"

**Comment by Taaketa** [comment]
The windows inside Centcomm on Cyberaid can be tampered with. I've never been trapped in space outside Centcomm before to know if they can or cannot be touched. Didn't know if Metastation was intended this way or not.

**Comment by Ar3nn** [comment]
But why would someone write a report about something so unnecessarily minute as the windows you see for the last 30 seconds of a round? I didn't understand that, and just guessed that the centcomm windows were reused somewhere on metastation. My bad if that was false.

**Comment by Taaketa** [comment]
Well that 'someone' didn't know it was intended those windows aren't meant to be invulnerable.

**Comment by TheDZD** [comment]
Centcomm windows are supposed to be invulnerable to being bashed down, or at least pretty damn near to it.
