### ISSUE TITLE
Metastation: Antag hud Is Borked. Shows Security instead of Antag.

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#2943]
Could Be Just the normal code DUnno

**Comment by Plotron** [comment]
Normal code.
It also shows the S or whatever antag it is to the right, if I'm not mistaken.
You should post these bugs in the AntagHUD megathread.

**Comment by tigercat2000** [comment]
Yyeah this is probably not meta's fault for once

**Comment by TheDZD** [comment]
Not a metastation issue, likely the same issue mentioned in the responses to #2899. Not marking this as a duplicate because issue megathreads are gross for properly keeping track of issues.

**Comment by tigercat2000** [comment]
@Aurorablade is this still a bug

**Comment by Aurorablade** [comment]
noper. i do need to do some hud updates..later..though...
