### ISSUE TITLE
pAI's can change and view medical and security records when examining people

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#2944]
Being in mobile form and examining someone shows medical and security Status and records
![2015-12-22_00-17-52](https://cloud.githubusercontent.com/assets/589709/11942781/8b34af6a-a841-11e5-8843-a9a1d8ead966.png)

**Comment by Plotron** [comment]
They can't change records (add comments) - you may type it in and accept it, but upon further examination, the note doesn't get added.
