### ISSUE TITLE
Metastation: Atmos pipes - connectors scattered in maint aren't connected

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2946]
I don't think TG use supply/scrubber pipes do they? Connectors scattered around maint that are meant to be connected to the supply system are not connected to the supply pipes they are located at:

Aft Starboard Solar Access
Aft Port Solar Access - Storage Room
Storage Room above Vault
Storage Room beside Recreation area
Central Emergency Storage beside Bridge
Medbay Emergency Storage
Aft Emergency Storage above Robotics
Research Emergency Storage
Storage Room beside Atmos
Port Emergency Storage beside Arrivals
Possible connector on AI sat?
Starboard Emergency storage beside Engineering

**Comment by TheDZD** [comment]
@tigercat2000
