### ISSUE TITLE
Metastation: HOS has atmos access

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2950]
I was observing the round HOS, and he was walking around atmospherics and inspecting the pipes like he worked there, no impediment for access.

**Comment by Plotron** [comment]
You sure it wasn't additional access from HoP?

**Comment by Ar3nn** [comment]
No, but I talked with other ghosts, nobody remembered him getting access added.

**Comment by theColdflame** [comment]
If this is referring to the second round of MS, I didn't have any access modifications to my ID as HoS.

**Comment by Ar3nn** [comment]
The last of however many rounds Metastation was out, I only saw the one. It was Luigi.

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by FalseIncarnate** [comment]
Inspecting the doors of atmos (including the windoors inside atmos for the sake of being thorough) showed them as requiring atmos access, which the Head of Security does not get on his ID by default. I heavily suspect this was an IC thing and not an actual code/map error.
