### ISSUE TITLE
Metastation: Telecommunications Server Monitor induces lag

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2953]
Clicking on the Telecommunications Server Monitor induces lag when a ghost or player clicks on it.

It possibly only takes place late into the round as the Message server was loading a lot of PDA messages.

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by FalseIncarnate** [comment]
Not sure if this is a map issue or a code issue. Personally leaning towards the side of it being a code issue, but never can be sure with telecomms.

**Comment by TheDZD** [comment]
Yeah. telecomms can be extremely process-intensive at times.

**Comment by tigercat2000** [comment]
@TheDZD this is definately not a map issue

**Comment by Taaketa** [comment]
#1429

**Comment by Crazylemon64** [comment]
I'm pretty sure this is a += string thing. Fixing now.
