### ISSUE TITLE
Metastation: Syndie Nuke Ops missing pin pointer locker and Nuke

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2955]
As per subject line

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
wait, they are MISSING THE FUCKING NUKE?
Ahahahahahahahahaahaaha *dissolves into crying on the floor*

**Comment by tigercat2000** [comment]
oh
This is fixed by #2997 
Meta has the same *exact* shuttle and nukebase
