### ISSUE TITLE
Literally all of the issues I collected and put in this pastebin

### ISSUE THREAD

**Issue by Zolofty** [ParadiseSS13/Paradise#2957]
http://pastebin.com/qaALzBVN

**Comment by Zolofty** [comment]
I am not good with github, so this is probably done wrong in every way

**Comment by Taaketa** [comment]
Probably better to log these as individual issues and cross check they haven't been reported already. A list like this only wastes a mapper and coder's time.

**Comment by Taaketa** [comment]
Reading it more detailed is needed on some of them for example:

"lots of lights spawning not working, have to take out bulb and put back in"
Where? What type of lights?

This one for example is already reported:

"kitchen lacks the proper machines"

**Comment by Zolofty** [comment]
¯\_(ツ)_/¯  I just asked OOC what all was dicked, and when I took this list to ahelps, I got told "take it to the github".

**Comment by taukausanake** [comment]
Kind of makes me wish this was in a new branch to be honest

**Comment by Taaketa** [comment]
@Zolofty Whatever you want but if you took 2 seconds to look around the issues list you'd see each issue has a seperated log for it. @ZomgPonies would probably prefer it this way for easier tracking and if a new branch does go up like @taukausanake suggests then they can easily cross reference the issues listed. Like I said your list does not make their job any easier.

**Comment by FlippingOut** [comment]
If no one is against it, I'll quickly make them into individual issues.

**Comment by Taaketa** [comment]
Make sure to clearly list them as Metastation issues.

**Comment by FlippingOut** [comment]
Oh yeah, better edit the others to that.

**Comment by Zolofty** [comment]
How do I even close this

**Comment by Zolofty** [comment]
I am not good with git

**Comment by Zolofty** [comment]
help

**Comment by Taaketa** [comment]
There is literally a button that says closed right beside where it says comment on the box you are typing in your damn spam. I'm sorry but I can't help stupid.

**Comment by Zolofty** [comment]
Not my fault it creates a new comment when I press enter instead of a new line. And yeah I apparently am dumb as hell, as I somehow missed that.
