### ISSUE TITLE
Some Changling bugs

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#296]
Heat Vision and Dark vision seem to flicker on and off, two lings confirmed this.

Absorbing at 3 genomes makes it into 4, dunno if its intentional to wait until maxed out or not.

Transforming sting works on Slimes, instantly killing them. Once again, I do not know if this is intentional.

**Comment by Markolie** [comment]
@TheDZD

**Comment by TheDZD** [comment]
Not entirely certain on the meaning of the second one, but I believe that's a part of the intentional limit on only being able to hold 4 non-protected genomes at once, however total genomes absorbed are tracked separately.

**Comment by Earthdivine** [comment]
After conversing in Skype, the second one seemed to be the ling's misunderstanding about how Genomes worked. Thanks for the quick fix.

**Comment by wotan90** [comment]
Hello. It seems i described the second bug not very good. Made an issue here: https://github.com/ParadiseSS13/Paradise/issues/386
