### ISSUE TITLE
Graffiti Transparency Is Dicked

### ISSUE THREAD

**Issue by Zolofty** [ParadiseSS13/Paradise#2960]
Any graffiti that isn't from the "old" (IE: Uboa, revolution, amyjohn, etc) set does not display properly. Only the "shading" displays. Applies to both crayon and spray-can applicated graffiti, but only of the "new" set (IE: syndicate, catbeasts, shitcurity).

**Comment by Tastyfish** [comment]
Yeah, this has been a problem for at least 2 months, I've always forgotten to report it.
