### ISSUE TITLE
Metastation: Lack of Clothesmates etc. in Dorms

### ISSUE THREAD

**Issue by FlippingOut** [ParadiseSS13/Paradise#2963]
Title.

Not sure if it's really needed, but for !!CONSISTENCY!! between maps.

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by orelbon** [comment]
There is a clothes mate.

**Comment by tigercat2000** [comment]
- Clothesmate: Locker room under dorms
 - Autodrobe: Maintenance below the auxiliary bathrooms of arrivals
 - Others: Will do.
