### ISSUE TITLE
Metastation: No cycling airlocks

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2969]
@Fox-McCloud I understand wants it close to TG station. But I'd love to see, where they can be IE. Not shuttles. Added back in.

**Comment by TheDZD** [comment]
@tigercat2000 Intentional or not?

**Comment by tigercat2000** [comment]
Intentional, and I don't plan to change it any time soon, because cycling airlocks are a pain in the ass for such a small benefit, and there's no place to fit airtanks.

**Comment by Fox-McCloud** [comment]
@Taaketa 

This wasn't my decision at all--I've actually had very little to do with Metastation.
