### ISSUE TITLE
Ghosts trigger infrared signaler assembly thingies 

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#2978]
it goes beep beep when a ghost crosses over the infrared, use boo! for maximum spooks on a very confused victim

**Comment by Plotron** [comment]
It's Halloween Special! Become a licensed paranormal investigator on NSS Cyberiad. Use high-tech specialized woo-woo powered technology to detect ghosts, converse with them and exorcise the station.
