### ISSUE TITLE
[Mechs] Removing the battery cell and reinstalling it

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#2982]
The battery has lost no power and can be put into the mech again for full power.

**Comment by Crazylemon64** [comment]
Unable to reproduce. Any special conditions?

**Comment by Taaketa** [comment]
Huh that's weird. Euh...

The mech was fitted with a: 
Plasma Generator
Repar Drone
Diamond Drill
Plasma Cutter

The battery power was at 0% I removed the battery cell, which was a high capacity cell and it was fully charged. Put it back inside the mech and it said it had 100% charge.

**Comment by Taaketa** [comment]
Closing as I can't reproduce.
