### ISSUE TITLE
Launcher projectiles won't hit targets *still*

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#2984]
https://github.com/ParadiseSS13/Paradise/issues/2494
https://github.com/ParadiseSS13/Paradise/pull/2512 didn't actually fix the crossbows and spike launchers, it only added the new properly functioning pneumatic cannon. Crossbow and spike launcher projectiles simply don't hit anything, and instead just stop one tile away from the target harmlessly, effectively making them absolutely useless.

**Comment by Fox-McCloud** [comment]
I meant fixed in the context of the pneumatic cannon; not the others---yes, this is still broken for the crossbow and dart gun.

**Comment by Crazylemon64** [comment]
I imagine this will be a problem for mining's KA, given how the tree is layed out, yes?

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

Uhhh?

**Comment by Crazylemon64** [comment]
Aren't the kinetic accelerators classed as children of the crossbow? Or am I misremembering things...

**Comment by Fox-McCloud** [comment]
the kinetic accelerators are a child of energy crossbows.

The crossbows mentioned here are the ones you make with wood+plastic.

**Comment by Fox-McCloud** [comment]
launchers have been fixed, but there's a semi-related bug with throwing code. Going to go ahead and close this though 'cause the launchers themselves are functional now.
