### ISSUE TITLE
Btime.dll

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#2985]
Not really an issue, but when I try to open my testing server, it loads, and after ~10 seconds, I get an error and the server closes:
PRECISE_TIMER_AVAILABLE is defined in btime.dm, but calling the btime library failed: Unable to load library btime.dll
This is a fatal error. The world will now shut down.
## ERROR: Hook '/hook/startup/proc/checkbtime' failed or runtimed.
The btime.dll file is in the same directory as my .dmb file.

**Comment by Fox-McCloud** [comment]
No idea on this one to be honest; I've never had problems with this; what OS are you using?

**Comment by CrAzYPiLoT-SS13** [comment]
Windows 10

**Comment by Tastyfish** [comment]
Are you using dream daemon with security set to ultrasafe? That mode disables external dll calls.

**Comment by Zuhayr** [comment]
Your BYOND may be out of date.

**Comment by CrAzYPiLoT-SS13** [comment]
I am using it on trusted. BYOND is latest version of stable, can't get beta
as no link for it pops up next to the byond update thingie.

**Comment by CrAzYPiLoT-SS13** [comment]
BTW, I have successfully played with my friends on Windows 10 and with the
process scheduler implemented before. I think it was using beta.

**Comment by Tastyfish** [comment]
And your testing server is just running from a full clone of the git repo, correct?

**Comment by CrAzYPiLoT-SS13** [comment]
Aye.

**Comment by Tastyfish** [comment]
Worst case you can open `code/_DEFINES/btime.dm` and comment out `#define PRECISE_TIMER_AVAILABLE` although I have never tested the fallback mode and have no idea if it even works anymore.

**Comment by CrAzYPiLoT-SS13** [comment]
Already tried that, the compile gives errors as explosions and shit use the
timer.

**Comment by Fox-McCloud** [comment]
btime is essential the operation of the scheduler and a few other things---things wouldn't...go well if you ran without btime anyway.

**Comment by Tastyfish** [comment]
The only other thing I can imagine is that maybe the Paradise folder has weird execution permissions set. Can you run eg the Runtime Condenser in tools or any of the other exe tools without a permission dialog popping up?

**Comment by CrAzYPiLoT-SS13** [comment]
Yes, I can.

**Comment by Crazylemon64** [comment]
Ah, I would like to second that I'm unable to run this in Windows 10 - I'm also having troubles loading bygex.dll, too, so I suspect there might be some overzealous security policies in practice, or something...

**Comment by tigercat2000** [comment]
have either of you tried running dream daemon as administrator

**Comment by Crazylemon64** [comment]
Sure, I'll give that a shot - a moment

**Comment by Crazylemon64** [comment]
Wouldn't you know it - it works when ran as administrator. I find this concerning, but since I trust the codebase and only I use the server, I should be OK.

**Comment by tigercat2000** [comment]
best guess is that windows 10 has stricter UAC policies, and won't allow arbitrary DLL's to be run by non-admin programs

**Comment by CrAzYPiLoT-SS13** [comment]
I ran it as an administrator, nothing.

**Comment by CrAzYPiLoT-SS13** [comment]
Hm, it resolved itself with the newest update. Closing.
