### ISSUE TITLE
[High Priority] Permastun

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2986]
Slip someone, and put them in a killing grip, and they will never stand up, and they can't resist free, this does not kill, but permastuns are broken as fuck.

**Comment by Spacemanspark** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Robertha89** [comment]
oh, and you do need to walk.

**Comment by Ar3nn** [comment]
Its aggressive (neck), if you want the proper term. Also, you can use this for murder if someone's not paying attention enough to resist out, once you hit kill, they get oxycrit immediately for some reason.
