### ISSUE TITLE
Drinks never deplete when drunk

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#2987]
Uh, not much to say, it's weird, it's not like before with the 1+E+number reagent thingy, it's just they never deplete.

**Comment by Plotron** [comment]
There's a point of saturation you can reach. If you drink too much, every consecutive sip will drain a very tiny amount of the liquid, giving the impression that it never drains.

Unless it's an *actual* bug that just popped up. Anyway, I think I'd share this piece of information.

**Comment by TheDZD** [comment]
Chances are that your mob reagent container was full, and you were continuing to try to drink something.

**Comment by Plotron** [comment]
Yes, in other words.
