### ISSUE TITLE
Vital organs aren't needed for revival

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2988]
Chop someone in half, seal the bloody stump, and defib them: Don't worry, they'll be A-OK. Will fix this soon.

**Comment by Fox-McCloud** [comment]
May want to wait until @Aurorablade is done with her PR--it's daunting enough, as is, to work with organ code, let alone when there's tons of conflicts.

**Comment by Crazylemon64** [comment]
Fair enough, I'll leave any further weird organ goofery for later

**Comment by fludd12** [comment]
Is this still relevant since after the organcode rework?

**Comment by Crazylemon64** [comment]
Yeah, you can still survive without lungs/a lower body/similar if defibbed, or additionally without a heart if SR is used

**Comment by Aurorablade** [comment]
its make need a quick fix if anything anything else would invovle an overhual, i plan on doing breathing to lungs at some point but it will need to be balanced out to prevent some racial cheesing

**Comment by jughu** [comment]
DoN'T woRrY iM a dOctOr

**Comment by Fox-McCloud** [comment]
there's hardly any vital organs left; most organs do nasty things when removed; the two exceptions I can think of are the brain and head, and those definitely kill you when you revive them without it.
