### ISSUE TITLE
Re-enter corpse

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#2994]
When using re-enter corpse after getting blown up from the RD console as a cyborg, it says you have given up your right to respawn.

**Comment by Crazylemon64** [comment]
Let's see...
Did you leave your body before your shell was blown?
What kind of MMI did you have installed?
Was your roundstart preferences cyborg role "robot"?

**Comment by CrAzYPiLoT-SS13** [comment]
No.
Don't know.
No. I got borged through borg factory. I thought this was the problem, until I saw other people talking form their MMIs which I know have been borged through the factory too.

**Comment by Crazylemon64** [comment]
What was your race? Were any error messages printed besides "You have given up your right to respawn"?

**Comment by CrAzYPiLoT-SS13** [comment]
Human and no.

**Comment by Crazylemon64** [comment]
And others, DID have MMIs after going through the robotizer?

**Comment by Crazylemon64** [comment]
And you were ghosted at the moment of destruction?

**Comment by CrAzYPiLoT-SS13** [comment]
Yep.

**Comment by Tastyfish** [comment]
If you were ghosted upon destruction, then it sounds like the mmi was destroyed, so there wouldn't be anything to return to anyway.

**Comment by CrAzYPiLoT-SS13** [comment]
Nope, the MMI was still there, and the sprite was living (didn't have the x's)

**Comment by Crazylemon64** [comment]
Open this again if it happens again

**Comment by DesolateG** [comment]
If you leave your MMI or Posibrain you will remove your rights to respawn.
