### ISSUE TITLE
Nuke interface is hilariously broken

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2998]
![hilarity](http://puu.sh/m6pyY/c57a3be689.png)

Thanks, everyone who *completely neglected to mention this to me*

**Comment by Fox-McCloud** [comment]
Um?

**Comment by tigercat2000** [comment]
@Fox-McCloud 
 - `Authorization Disk:` is on the wrong side of the link
 - `Timer:`, `Saftey:`, and `Anchor:` are all on the wrong side of the link
 - There are two timers, one under `Status:` (`Timer:`), and another to the right of `++` (`Time:`)

**Comment by Plotron** [comment]
Hilarious and original!

**Comment by Fox-McCloud** [comment]
Oh, the two times is intentional.

The timer is the countdown--the time is what you want to set it to, I believe.

Thanks for pointing out the others though.

**Comment by tigercat2000** [comment]
oooh. Gotya. Should probably be renamed to clear confusion though

**Comment by Plotron** [comment]
Yeah, rename it to something like Set Time.

**Comment by Plotron** [comment]
Yeah, change it to Set Time and maybe Countdown.
