### ISSUE TITLE
APC interface lock 

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#3000]
The setting to lock and unlock APCs does not work right, you can only use the engage button to disable and enable the interface lock.

**Comment by Iamgoofball** [comment]
#3000

**Comment by Fox-McCloud** [comment]
@orelbon 

Screw you and all you stand for >=(

**Comment by orelbon** [comment]
>:D Mueehehehehe

**Comment by TheDZD** [comment]
Literally the worst person.

**Comment by tigercat2000** [comment]
quickly, someone use the github api!

**Comment by Anticept** [comment]
Confirmed, this is still an issue.

Note, this is a problem with AIs and Cyborgs, interface lock is not something the other mobtypes see.
