### ISSUE TITLE
Sec HUD 

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#3002]
Takes forever to update after changing wanted settings

**Comment by Ar3nn** [comment]
I'm also noticing a slightly longer delay in the switch between infected and normal on medical huds when I cure a virus.

**Comment by TheDZD** [comment]
@Aurorablade

**Comment by Aurorablade** [comment]
@Crazylemon64 @Fox-McCloud i don't think this is an issue still
