### ISSUE TITLE
Morgue bug

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#3009]
You can stick two bodybags, maybe more, into one morgue tray

**Comment by TheDZD** [comment]
Not entirely certain if this is even a bug to be honest.

**Comment by tigercat2000** [comment]
It's not. Just as you can fit something like 20 bodies into one locker.

**Comment by CrAzYPiLoT-SS13** [comment]
Oh, alright.
