### ISSUE TITLE
Beakers...again

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#3010]
So. I make Mitocholide and put it in a large beaker. Go to ChemMaster and make pills. Put pills in bottle. Get beaker out of ChemMaster. It seems like it's full, examine, nothing in it. Splash on floor, get splashing message, but nothing on the floor.

**Comment by CrAzYPiLoT-SS13** [comment]
Also seems, that when making pills from ChemMaster, the beaker never gets emptied, so infinite chems!

**Comment by Crazylemon64** [comment]
Uhh, you did transfer the mitocholide out of the beaker, into the buffer?

With the ChemMaster, there's the beaker, where all the chemicals you work with are stored, and the buffer, where you put all chemicals that you want to make into pills/patches. You HAVE been transferring stuff out of the beaker and into that buffer, right? And the pills were of full functionality? Did consuming them actually add anything scannable to a patient's system, and dropping the pills in a beaker with water in it added volume?

**Comment by CrAzYPiLoT-SS13** [comment]
Yes, it was in the buffer. Yes, they were adding reagents.

**Comment by CrAzYPiLoT-SS13** [comment]
It seems it was 1 round bug...
