### ISSUE TITLE
RIPLEY mesons interfere with worn mesons

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3015]
Wearing mesons and in a RIPLEY, it seems that the meson effect is flickering, which is rather distracting.

**Comment by Fox-McCloud** [comment]
I'm tempted to just remove the meson feature for RIPLEY's--it's annoying as hell anyway.

**Comment by Ar3nn** [comment]
The Ripley/Firefighter meson effect seems to flicker on its own, regardless.

**Comment by Fox-McCloud** [comment]
>The Ripley/Firefighter meson effect seems to flicker on its own, regardless.

That's intentional.

**Comment by Ar3nn** [comment]
Oh, so they weren't meant to give perfect meson vision? Okay, then why at all? I'm just curious how this ever seemed like a good idea?
