### ISSUE TITLE
Non-human mobs don't have autocapitalization

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3023]
As a human, saying things automatically capitalizes the first word of your sentence.
As a simple mob, cyborg, or brainmob, you lack this capitalization.

Intended, ya or na?

**Comment by tigercat2000** [comment]
Somewhat intended. I didn't bother to implement the auto-capitalization at the living/say level because I don't really give a shit about it or like it.

**Comment by CrAzYPiLoT-SS13** [comment]
Damn, my grammar Nazism is hurting me.
