### ISSUE TITLE
Backpack using wrong sprite when dropped in space.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#3024]
Not 100% sure how to reproduce.  I was through the gateway at the syndicate listening post.  I packed what I couldn't fit in my bag into the syndicate agent's bag, and on my way around the asteroid I decided to do some rearranging.  When I dropped the syndicate agent's backpack I noticed the sprite on the 'floor' tab was showing an adult grey slime.

http://imgur.com/8vOLBcW

Fairly minor, I know, but I figured I should report it.

**Comment by Kerroman** [comment]
To clarify: The backpack had the correct sprite in the game window, it's just hidden by my character sprite.  The wrong sprite was only seen in the 'floor' tab on the right where I outlined it in red.

**Comment by tigercat2000** [comment]
Alt-click menu icons are semi-magical, perhaps cache corruption at work.

**Comment by Fox-McCloud** [comment]
recommend clearing your cache and letting us know if this happens again; I've literally never seen this.
