### ISSUE TITLE
AI medHUD randomly doesn't show some people's health

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#3027]
![BLA] (http://puu.sh/m9iCD/cfac89391c.jpg)
and it stays that way for the whole round. So if Greytide A doesn't show his bar, he will never show his bar. All other huds work fine, however.

**Comment by Plotron** [comment]
I had a similar problem with that when I was a ghost, but that was before the last batch of HUD fixes.

**Comment by Aurorablade** [comment]
this is working as intended. the new hud system will ONLY DISPLAY THE MEDHUD WHEN SUIT SENSORS ARE ON it does not need to be on MAX just on.

**Comment by Aurorablade** [comment]
and it might not be...i am double checking now....regardless its a simple fix,...

**Comment by Aurorablade** [comment]
yeah its WAI......I LOVE ABBRIVATIONS

**Comment by Plotron** [comment]
It sure is annoying.

**Comment by Fox-McCloud** [comment]
@Aurorablade 

This applies to sechuds, as well, correct?

**Comment by Aurorablade** [comment]
no it should not be applying to sec huds, sec hud setting was an issue of it be basic and not advanced...nothing to do with suit sensors.

**Comment by Aurorablade** [comment]
to elaborate, it has to do with the thing being a MEDICAL_BASIC instead of MEDICAL_ADVANCED. IT can be changed. but all being on Basic does, is if you do not have it set to at least VITALS TRACKING it will not show the bars. its on the player then if the AI Can't see if they are injuired or not via a camera.

**Comment by Fox-McCloud** [comment]
alright, soooo not a bug. Thanks.
