### ISSUE TITLE
Animated hairstyles lack the delay specified in human_face.dmi

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3029]
Exhibit A:
The Yellow, RGB, Glider, and Console IPC screens.

**Comment by tigercat2000** [comment]
Blatantly a BYOND bug, but what exactly do you mean?

**Comment by Crazylemon64** [comment]
I specified a 10 frame delay on the RGB and Console screens, and I see a delay of 20 on the Yellow screen, but they move at the rate of the Scanline, which has a delay of 1.
