### ISSUE TITLE
Botany Maintenance, space tiles, and radiation events.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#3033]
Building over space tiles in maintenance will not stop them from receiving Space Radiation in the Space Radiation event, but does not put a dangerous flashing overlay over them.

Probably just the Space ~~turf~~ area still being a space ~~turf~~ area.

**Comment by Crazylemon64** [comment]
I suspect it to be more of an areas issue, perhaps with the blueprints this could be avoided, but iunno

**Comment by TheDZD** [comment]
Radiation event is based on areas, you would need the CE blueprints to make the built-over space not be counted as space.

**Comment by IAmBigCoat** [comment]
Yeah, area's what I meant. It just seems a bit silly that blueprints convey magical radiation-proof powers the same way they transfer power from APCs.
