### ISSUE TITLE
Syndicate pets are dead.

### ISSUE THREAD

**Issue by lolzyking** [ParadiseSS13/Paradise#3038]
they spawn in dead every round, there is no PR as to why they are like this ( searched terms syndicat,syndifox and syndicate pets)

these pets bring fun, RP, and usefulness to the syndicate team.

they are space worthy and can pull stuff, often saving poor syndicates from lube induced deaths.

**Comment by Crazylemon64** [comment]
DEATH TO THE SYNDICAT

(not sure why this is happening I'll look into this)

**Comment by CrAzYPiLoT-SS13** [comment]
Not an issue as seen from OOC chat. They were removed because they can often save nukies.

**Comment by tigercat2000** [comment]
oh I actually figured this out while porting -tg- shuttles
nothing that uses the generic breathing code can actually breathe on unsimulated turfs

**Comment by CrAzYPiLoT-SS13** [comment]
Hm, admins concluded that this is intentional on OOC.

**Comment by tigercat2000** [comment]
it's not but I haven't had the time to fix it
