### ISSUE TITLE
Top HUD buttons

### ISSUE THREAD

**Issue by Quantomicus** [ParadiseSS13/Paradise#3039]
Speaks for itself: 
![screenshot_12](https://cloud.githubusercontent.com/assets/9385129/12010730/b8434b04-acb2-11e5-95c4-17a239f0fac3.png)
This happened after closing and then re-expanding the line of buttons.

**Comment by Crazylemon64** [comment]
Sometimes the defib icon shows up in the middle of the screen when unequipping one

**Comment by TheDZD** [comment]
Err, I might be missing something, but what exactly am I looking at?

**Comment by Crazylemon64** [comment]
@TheDZD The list of icons to perform actions with an object on your person, like hardsuit helmet lights or raising and lowering your breath mask

**Comment by CrAzYPiLoT-SS13** [comment]
The arrow to expand the list overlays one of the buttons.

**Comment by Spacemanspark** [comment]
You realize you can click and drag those around the screen, right?

**Comment by CrAzYPiLoT-SS13** [comment]
I do, but it isn't really suitable, if I need to fast toggle something in a
combat situation or something, and I get blocked by that arrow.

**Comment by tigercat2000** [comment]
can't reproduce this locally, minimizing and maximizing with the arrow works fine

**Comment by Crazylemon64** [comment]
I remember fiddling aroud with the paddles, or something, then removing the defib, and the icon moved to the middle of the screen, if that helps anything

**Comment by Tastyfish** [comment]
Does this ever happen to anyone outside of manually fiddling their location?

**Comment by CrAzYPiLoT-SS13** [comment]
It happened to me this time, and never again.

**Comment by DesolateG** [comment]
Has anyone been able to reproduce this? If not this can probably be closed.

**Comment by Fox-McCloud** [comment]
Pretty sure this has been fixed.
