### ISSUE TITLE
As soon as you look at an record inside of the Security Records machine, you crash.

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3046]
Atleast, this is what has happened to me every single time I was trying to access it.

**Comment by pinatacolada** [comment]
It's the side photo that causes the crash, you'll notice it doesn't load when you crash. Same thing happens with medical records and also when examining ID cards. Anything that has the side photo really. Curiously it only crashes once per record.

**Comment by Tastyfish** [comment]
I have no idea what changed here, but I haven't seen this issue in about a week. Is anyone still experiencing this issue?

**Comment by CrAzYPiLoT-SS13** [comment]
I just experienced it. It crashed, I accessed the same record after reconnection and it worked.

**Comment by CrAzYPiLoT-SS13** [comment]
"High priority"

**Comment by Lady-Luck** [comment]
I am told the cause is the photos. Can we just remove the photos?

**Comment by Reker45** [comment]
I thought this was already fixed back in march...welp

**Comment by Ar3nn** [comment]
If nobody is going to look into why the crash occurs and try to fix it, removing the pictures is the next logical fix.

**Comment by PJB3005** [comment]
This is a byond issue, probably among the same nature as the potential crash when using VV on a certain object.

Try to attach a debugger to DS and get debug info to lummox when it happens.
