### ISSUE TITLE
The AI setting people to arrest, does not show up on security HUDS

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#3048]
Their status may be arrest, if set by the AI, but HUDS will not see the red W

**Comment by Fox-McCloud** [comment]
@Aurorablade

**Comment by Aurorablade** [comment]
for AIs this is working as intended unless someone stabs me in the ass with a pitchfork.

**Comment by Plotron** [comment]
What does that mean, @Aurorablade?

**Comment by Kyep** [comment]
I wish this was fixed - it makes no sense for statuses set by AIs to not show up.

**Comment by Plotron** [comment]
@Kyep - there could only one argument - to prevent AIs from supercopping with their bots.
So, if someone breaks into AI Sat, for instance, you'd have to disable safeties on Pingsky in order to make a simple arrest/detainment. That's ridiculous.
