### ISSUE TITLE
Records are still horribly broken

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#3053]
The Constant Crashes makes playing Sec or Updating Medical files Nearly unplayable. It can Ruin high-tension or high action sequences by putting the breaks on suddenlly to restart the client. I nearly died the last time I crashed from changing records do to a antag sneaking up on me. Its not a Bug that makes the game unplayable. but Really puts a damper on it because you have to PLAN on crashing to get anything done as warden, detective a officer with a Laptop on the go, or a doctor updating medical files.

**Comment by Fox-McCloud** [comment]
Which version of BYOND are you using?

**Comment by TheDZD** [comment]
Duplicate of #3046

**Comment by AceMcLazer** [comment]
@Fox-McCloud The most recent version I think. is that have somothing to do with it?
