### ISSUE TITLE
Deconstructing APCs doesn't allow placement of new APC

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#3054]
What is says on the tin.

Couple rounds ago I deconstructed the APC in the maint near the Janitor's office, and I couldn't place down a new APC to replace it. It gave the message "This area already has an APC." and simply didn't work - I asked an admin to delete everything on the tile and it still didn't allow replacement.

**Comment by Robertha89** [comment]
That usually means the area already have an apc. Its easy enough to check.

**Comment by Crazylemon64** [comment]
Destroy()-ing the APC doesn't remove the APC from [apc].area.apcs

**Comment by Fox-McCloud** [comment]
>Destroy()-ing the APC doesn't remove the APC from [apc].area.apcs 

May be why they don't GC either.

**Comment by Tastyfish** [comment]
Technically a separate issue than the area.apc thing (although that probably is why they don't GC), because the apc frame checks the contents of the area for an APC, not that variable. I'm going to check the map to see if there's multiple APC's in medbay maintenance.

**Comment by Tastyfish** [comment]
There are indeed 2 APC's, although it's because both the maintenance aft of medbay and the maintenance fore of genetics are both the same area. Should that little maintenance fore of genetics by a new area type or should one of the APC's be removed? @Fox-McCloud

**Comment by Tastyfish** [comment]
I wrote code to dump areas with multiple APC's, there are 9 areas that have at least 2, lol. Almost all of them are contiguous, so I'll probably just make a PR that has all of them fixed. So far only the OP case and arguably surgery (since I'm thinking they should each have their own area) would need remapping beyond the APC.

**Comment by Tastyfish** [comment]
Not sure if there's an official way to say this, but the PR for this map update will probably be pretty conflicty (lots of tile changes) if anyone else is changing anything.

**Comment by Crazylemon64** [comment]
Merge it fast and furious, so there's no time for map conflicts

**Comment by Tastyfish** [comment]
Definitely on board with that

**Comment by Crazylemon64** [comment]
After all, I don't think there are any active PRs that have map edits in them, besides the organ one.... I think, however, given how long it's taking, that Fethas is expecting the map bit to require redoing one way or another...

**Comment by Tastyfish** [comment]
It should be done & pushed within a couple hours, testing it now to make sure I didn't unplug something or trash an area.
