### ISSUE TITLE
Atmos meter can not be wrenched

### ISSUE THREAD

**Issue by Artorp** [ParadiseSS13/Paradise#306]
Current workaround everyone is doing is unscrewing whatever pipe the meter is connected to.

Apparently this happens because Click() overwrites attack_by() in https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/atmoalter/meter.dm#L98-L124

**Comment by Artorp** [comment]
Looks like this will be fixed by https://github.com/ParadiseSS13/Paradise/pull/12

**Comment by FalseIncarnate** [comment]
Meters could be un-wrenched with double click, though Mark already has a PR to probably simplify and standardize this.

**Comment by Artorp** [comment]
Huh, I did not now that. All those times I've been unscrewing pipes... Anyway, that was fixed quite swiftly, good job Mark!
