### ISSUE TITLE
Plants sometimes do not mature in resonable time.

### ISSUE THREAD

**Issue by carlosfza** [ParadiseSS13/Paradise#3062]
I have been having issues in hydroponics with sometimes plants taking longer to mature (being able to be harvested). This issue usually happened in the end of the round. Some examples were:
Mutating and old tomato to bluespace tomato at 13:30, it was not ready to harvest at 14:10.
Creating a new plant from berries, splicing about 5 biochem genes into it and internally explosive, 30 minutes later I have nothing to show for it as the new plant does not give fruits.

In order to understand what was missing i looked into the hydroponics code and I found something strange that might be the cause.

    var/lastproduce = 0        // Last time tray was harvested

This happends in the tray.dm. It seems that the age when the plant was last harvested is noted in that variable.

In tray_process.dm there is a piece of code that sets trays to be harvestable. As you can see, it checks if the age of the plant - lastproduce is greater than the production. Only then is the tray harvestable.

    // If enough time (in cycles, not ticks) has passed since the plant was harvested, we're ready to harvest again.
	    if((age > seed.get_trait(TRAIT_MATURATION)) && \
	     ((age - lastproduce) > seed.get_trait(TRAIT_PRODUCTION)) && \
	     (!harvest && !dead))
		    harvest = 1
		    lastproduce = age 

In the fucntion harvest at tray.dm we can see how the lastproduce variable goes up every time we harvest a tray. Taking value of the plant's age.

    //Harvests the product of a plant.
    /obj/machinery/portable_atmospherics/hydroponics/proc/harvest(var/mob/user)
    ......
            // Reset values.
 	    harvest = 0
	    lastproduce = age

However, when a plant dies, the lastproduce variable is not reset to 0:

    //Clears out a dead plant.
    /obj/machinery/portable_atmospherics/hydroponics/proc/remove_dead(var/mob/user)
	if(!user || !dead) return

	if(closed_system)
		user << "You can't remove the dead plant while the lid is shut."
		return

	seed = null
	dead = 0

	sampled = 0
	age = 0
	yield_mod = 0
	mutation_mod = 0

	user << "You remove the dead plant."
	check_health()
	return

This causes the following case:
I tray starts at age 0 and lastproduce 0 with a new tomato plant.
I harvest the tomato at age 15, lastproduce becomes 15, harvest again at age 40, lastproduce becomes 40.
I clear the plant and plant some apples. Age is now 0, lastproduce is 40. Age - lastproduce will be negative until the plant is 40 age old. If the apple production was 5, the only at age 45 it will be harvestable.

What I propose is that when we clear a plant or weeds take over:
/obj/machinery/portable_atmospherics/hydroponics/proc/remove_dead(var/mob/user), and 
/obj/machinery/portable_atmospherics/hydroponics/proc/weed_invasion(), lastproduce should be set to 0.

I do not have experience with boynd programming other than reading the code as a wiki replacement, so this may be wrong and i would appreciate if more experienced people would test this and give their input.

**Comment by FalseIncarnate** [comment]
Thanks for the detailed report, I'll be looking into fixing this probably tonight after work.

Plant aging is also wonky, with it being a chance of increasing every cycle rather than a gaurenteed aging. This can lead to identical plants maturing at different rates. I'll likely be tweaking this to be more standardized.

Additionally, for claiming no experience with code, you were spot-on with the issue and fix. Probably was just an oversight by the original coder that I missed in my port.
