### ISSUE TITLE
Can't repair IPC faces.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#3064]
Not sure if I'm dumb or it's an actual bug, but it seems there's no way to fix an IPC's face when his head gets blown off. I tried welding the internals of a monitor, but the game just told me there's no way to use the welder. I've asked around a bit and nobody knew any other way to do it, so I'm reporting it here.

**Comment by Crazylemon64** [comment]
I didn't actually make that surgery also allow you to do it if the limb was disfigured, so I need to fix that, but - another way to do so, is to print off a new head from the exosuit fabricator, use it in place of the old head, reinsert the optics, and good-to-go

**Comment by TheDZD** [comment]
Should be fixed by #3066
