### ISSUE TITLE
"Dream Daemon killing connection" when trying to join Paradise?

### ISSUE THREAD

**Issue by Toniebardin** [ParadiseSS13/Paradise#3065]
Hi.

Haven't played on Paradise for about a year, now I'm trying to join and I get the "Dream Daemon killing connection" message. 

I tried joining a few random servers and they all seem to be ok and downloading map information.

Anyone has had this issue before?

**Comment by CrAzYPiLoT-SS13** [comment]
Seems like BYOND has some built in block for your IP or HW ID, if you
weren't banned earlier. Try changing these.

**Comment by tigercat2000** [comment]
it probably isn't byond's fault if they can connect to other servers, @CrAzYPiLoT-SS13 
Could you please post a screenshot of the message, @Toniebardin ?

**Comment by Toniebardin** [comment]
![byond](https://cloud.githubusercontent.com/assets/16503315/12067070/43193a3c-afeb-11e5-96ba-3043f60c0aeb.png)

**Comment by Toniebardin** [comment]
1. Connecting...
2. Dream Daemon killing connection.

That's all that happens. :)

**Comment by tigercat2000** [comment]
Try clearing your byond cache- open byond, hit the little blue gear icon in the top right, hit "preferences", then go to the "games" tab and hit "Clear Cache"

**Comment by Toniebardin** [comment]
It's still the same thing.. I lost hope truth be told

**Comment by CrAzYPiLoT-SS13** [comment]
@tigercat2000 Uh, as the Daemon is intentionally killing connection, it would seem our codebase has some block against him? As you stated, other servers are joinable, so the problem is in our codebase.

**Comment by tigercat2000** [comment]
@CrAzYPiLoT-SS13 That message doesn't come from our code, if our code was intentionally keeping them out, it would show up as a ban message.

@Toniebardin You may want to try updating BYOND to the latest version, as well as trying a different account, exiting and starting BYOND, and if none of that works, try again after restarting your computer.

**Comment by CrAzYPiLoT-SS13** [comment]
@tigercat2000 I don't think you understood me, I think the codebase is instructing BYOND to swat him off for whatever reason, as ban text is not there. At least I think that is the problem, or I may just be talking gibberish.

**Comment by Taaketa** [comment]
There is also a Windows 10/8.1 issue from a Internet Explorer / Flash software update issued yesterday.

This forum thread has more information:

http://nanotrasen.se/phpBB3/viewtopic.php?f=2&t=6734&view=unread&sid=f89294baa0e58d43b7335aa56695b190#unread

**Comment by Toniebardin** [comment]
Well, I did pretty much everything now, thanks for help everyone. 

Went to sleep and it didn't work, woke up, and I'm downloading resources. See you soon ;D
