### ISSUE TITLE
Ore Reclaimer not emptying Ore Boxes

### ISSUE THREAD

**Issue by Davdichan** [ParadiseSS13/Paradise#3076]
Right there on the tin.

Place an Ore Box full of materials above an Ore Reclaimer and it doesn't interact with them. Users must manually empty the ore box for any ore to be processed. As borgs can not empty boxes, this prevents them from utilizing the crates at all without someone at cargo to empty the crate.

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, I had this problem too and a mentor told me the correct way, I forgot
it though. Anyone familiar with this on the repo?
