### ISSUE TITLE
Tourrete's also makes you incapable to move/interact

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#3078]
This genetic disability appears to have gotten a ninja buff. It's as bad as epilepsy, because it keeps you locked for longer. And it's hard to tell when it's over, or if it's over at all.

It used to only make you twitch and yell obscenities. Why, why? Or I may be mistaken.

**Comment by Fox-McCloud** [comment]
@Plotron 

I think you're just mistaken here; Tourettes has always stunned---this has never been buffed or nerfed in and of itself.

One thing that is a *hair* bit different about it is that---a long time ago stuns didn't make you drop what was in your active hands, now they do--that's the only "buff" tourretes has ever received.

**Comment by Plotron** [comment]
Thanks for the clarification.
