### ISSUE TITLE
Vox *flap and *aflap don't use the proper pronoun.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3083]
It's always 'his,' no matter if you're female or your gender is obscured by a mask or such.

**Comment by tigercat2000** [comment]
not a bug and not specific to vox, it just uses 'his'

**Comment by Fox-McCloud** [comment]
old emote is oldddddddddddd

**Comment by Spacemanspark** [comment]
Wouldn't this be easily fixed with a \his thing?

**Comment by tigercat2000** [comment]
yes, incredibly easy
but why would we fix a great mistake from nearly 3 years ago
stop trying to make me replace [my ship](https://en.wikipedia.org/wiki/Ship_of_Theseus) damnit
