### ISSUE TITLE
Nations Leaders and Heirs

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#3084]
It would seem there is a potential issue where departments without people on 'Nation Start' will never get a leader (the first official person to join the Nation after the event starts if no one else is present). This may just be an oversight in the code. I had gotten a report that Cargo had no Leader or Heirs and no one could make one (else this wouldn't be a problem). While making a system to check a department a player is entering if it is empty would probably solve it relatively easily, there could also be need of nations eventually being linked to the TP, something as "nations: employee|member|heir|leader" or simply "nations: employee|heir|leader".

**Comment by TheDZD** [comment]
@ZomgPonies
