### ISSUE TITLE
Facial Reconstruction

### ISSUE THREAD

**Issue by Dragonephobe** [ParadiseSS13/Paradise#3086]
The surgery exists, and it can be done, all the steps can be followed. But the surgery itself does nothing, it neither heals the vocal cords, as the hemostat claims to do, nor fix the person in questions face. I did follow every step to a T, and attempted many other solutions, none worked.

**Comment by Fox-McCloud** [comment]
unless something recently changed, this most definitely does fix people's faces that have become mangled.

**Comment by Dragonephobe** [comment]
Have you tested it? Because one round ago it definitely did not. And many rounds ago when I needed it, it did not.

**Comment by CrAzYPiLoT-SS13** [comment]
I did it successfully in the past month many times, I do not know what
could have changed.

**Comment by pinatacolada** [comment]
I did this yesterday and it worked. It won't work on husks or if you took a enough burn damage to leave you husked
