### ISSUE TITLE
Hijack Objective not triggering properly

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3087]
The Traitor "Hijack" objective is not triggering as completed, even when no one is on the escape shuttle but the Traitor.

**Comment by TheDZD** [comment]
@Fox-McCloud @tigercat2000 Might be related to the new shuttle changes.

**Comment by tigercat2000** [comment]
i rewrote most of the hijack objective, it should work fine with -tg- shuttles

**Comment by Fox-McCloud** [comment]
All that i Know is, this was working 100% fine a couple of weeks ago; I reest my local server a lot just to specifically do so.

**Comment by tigercat2000** [comment]
@TheDZD / @Fox-McCloud you should probably mark this unable to reproduce
