### ISSUE TITLE
Body scanners not showing mechanichal parts such as mechanical eyes

### ISSUE THREAD

**Issue by Knivarn** [ParadiseSS13/Paradise#3089]
As the title suggests, body scanners do not show if the person inside has mechanical internal organs, atleast I have noticed the eyes. I don't know if this is intended behaviour, but it has worked on others servers so I'm guessing it's supposed to work.

If this IS intended behaviour, can we please have it back? It's rather annoying to open someone's head and realise you can't fix their eyes after all.
Edit: Seems to not pick up mechanical hearts too, so I'm guessing it misses all internal organs.

**Comment by RudiPardieck** [comment]
I'll fix this shortly
