### ISSUE TITLE
Infrared Emitter Weirdness

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#3094]
A few things, discovered to have never been fixed in the several months I was gone, about these li'l guys.

-You cannot rotate an Infrared Emitter that is attached to a signaller, etc. Why is the rotation handled in the right-click menu, and not in the actual emitter GUI?
-Turning off an infrared emitter doesn't turn it off. Instead of the beam being solid, it just sits there and flashes on and off. Walking into the beams while they are mid-flash will make them go away, but they show back up again. Only a screwdriver will actually turn the beam off.
-Any beam that has been turned on at least once will do that flashing thing any time it is unable to be attached and is 'ready', even if it's attached to an igniter, etc.
-Even though the beam flashes when off, walking into it doesn't activate attachments; in my test, I used an attached signaller, set to activate a signaller-igniter assembly that would spark when I broke the beam.
-Rotating an infrared emitter doesn't rotate the beam sprites, so one facing right looks like this:

(E) | | | | |

Which is bizarre and also not a beam. It works fine, it just looks weird.

Inrared emitters will shoot beams out even if they're inside a backpack. Emitters doing the 'off' flashing thing will also do so from within a backpack.

The sprite isn't at all indicative of which way the emitter is facing. Examining it doesn't help either.

Turning on an infrared emitter in your hand and walking away will produce a FLOATING BEAM! It doesn't go away until you turn it off, or until a fairly long duration passes. It will still function normally, allowing a clever chemist etc to make tripwires that are impossible to disarm for 10-15 seconds.

I'm sure some of this is intentional, but it's bizarre, and doesn't at all behave how expected.

**Comment by Kyep** [comment]
I can confirm some of this, specifically the (E) | | | | beams, which I saw yesterday.
Yes, it is not very intuitive. Most annoying for me is the fact you can't rotate the laser after the thing is completed and you realize it is pointing in the wrong direction.
