### ISSUE TITLE
The :i message mode does not work

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3095]
Stand next to an intercom, with no headset, and using :i will just result in you talking as if you were trying to use a non-existent channel. Though, since that text shows up, I suspect that the hear_say of the intercom might not be playing nice? Iunno

**Comment by Fox-McCloud** [comment]
I'm not sure if the :i thing has been a "thing" for years--I'd have to look into it.

**Comment by Tastyfish** [comment]
I don't recall it working on any branch in years either.

**Comment by Spacemanspark** [comment]
It worked until Mark overhauled the language system.

**Comment by FalseIncarnate** [comment]
I remember using this on live code sometime last year prior to the saycode stuff mark did. can confirm it doesn't work right now
