### ISSUE TITLE
Antag HUD shows after being cloned as traitor

### ISSUE THREAD

**Issue by Jackel98** [ParadiseSS13/Paradise#3099]
In a recent round, I was a traitor. I was killed, and went ghost. I turned on the Medical HUD to check on my murderer, and then I was dragged to cloning. I returned to my corpse, and when I was cloned I saw a red S above my head. And then red S's above a lot of others' heads.

**Comment by TheDZD** [comment]
@Aurorablade

**Comment by Plotron** [comment]
That's problematic. You mean Antag HUD no longer prevents your cloning?
Absurd.

**Comment by Dinarzad** [comment]
I don't think it's Antag HUD not stopping you from being cloned, but when you ARE Cloned as an antag, it shows up while alive.

I can confirm it's pretty much like Jack said. I was a Tator on round start. Things were fine and kay. I died and was revived in medical bay, and suddenly I could see the Syndicate symbol over my head and others.

**Comment by Plotron** [comment]
I'm baffled now.

**Comment by Ar3nn** [comment]
The only thing I can make sense of this is that after cloning, it showed EVERYONE as a traitor, making the hud useless.

**Comment by Jackel98** [comment]
Actually, it showed the syndicate symbol over only a few, and I confirmed them with the codewords. They were all syndicate.
