### ISSUE TITLE
Beepsky is an interdimensional robocop

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3110]
* wiznerd is spotted by beepsky
* wiznerd etherjaunts
* beepsky KNOWS
* beepsky hunts them down to the corner of maintenance they hopped off to

**Comment by Spacemanspark** [comment]
There is a reason Beepsky is considered the best security officer.

**Comment by tigercat2000** [comment]
yeah this is an issue with all types of bots
they completely ignore invisibility and alpha level

**Comment by CrAzYPiLoT-SS13** [comment]
Powered by a potato and a shot of scotch.

**Comment by Tastyfish** [comment]
Yeah looks like once Beepsky is on the trail, [it just continuously runs to the target regardless of how far away the perp is or what obstacles are in the way, etc.](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/bots/secbot.dm#L269-L271) Only way it stops is if it gets further away from the perp for 8 ticks in a row or the target is destroyed.
