### ISSUE TITLE
Wall Smoothing is Odd

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3113]
In some instances wall smoothing will just stop working and break, resulting in walls looking like adjacent squares.

Other times walls will end up pitch black, as if they were in total darkness.

@tigercat2000

**Comment by tigercat2000** [comment]
Pitch-black walls, I'm 90% sure it's the stupid fucking wall damage overlay.
Not a single clue over the wall smoothing not working, would need more details and a way to replicate it

**Comment by Tastyfish** [comment]
I saw this happening agressively in one round in an area that was bombed and then repaired (it was at least a third of the walls involved), but I can't reproduce it locally, odd.

**Comment by Fox-McCloud** [comment]
I know what's causing the smoothing to fail: it's space cleaner.

**Comment by Robertha89** [comment]
![image](https://cloud.githubusercontent.com/assets/7663878/12125462/a7b2c41e-b3eb-11e5-9e3d-2fee32a1bd62.png)

**Comment by Dinarzad** [comment]
Can confirm space cleaner is doing WEIRD shit right now.
It's 'cleaning' the gold trim off carpets and shit as well and all sorts of stuff it ought not to be removing.

**Comment by Keilden** [comment]
It also removes the color on windows like in the brig.

**Comment by Fox-McCloud** [comment]
>It also removes the color on windows like in the brig.

Not going to bother fixing. Colorful reagent colors things, and there was no way to remove that (which was annoying as hell)---space cleaner resets colors back to their initialized colors---thing is, there's a few things (mostly windows+windoors) that have their color set AFTER they're initialiazed soooo...

**Comment by tigercat2000** [comment]
The smoothing issue should still be fixed, but I still don't have a way to reliably reproduce the black icon.

**Comment by Ar3nn** [comment]
http://prntscr.com/9omsp6
Random phlogiston explosion in chemistry caused it. As far as I know, space cleaner was not involved.

**Comment by tigercat2000** [comment]
@Ar3nn that would probably be the wall damage overlays fucking shit up

**Comment by Tastyfish** [comment]
I also managed to catch the aftermath of the same explosion! (Mesons view)

![explosion](http://i.imgur.com/tp13WuN.png)
