### ISSUE TITLE
Who's the Blueshield's superior?

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#3115]
At roundstart as Blueshield you get notified that the NT Rep is your superior, however a piece of paper on your desk says it's the HoS that you should report to.

Not sure which one is intended, but either coding issue or mapping issue.

**Comment by Crazylemon64** [comment]
This, as more of a rules/role issue, might be better suited for forums discussion

**Comment by Fox-McCloud** [comment]
This is better discussed on the forums with administration; this is not a coding issue until things are clarified there, then we'll adjust the paper(s) and descriptions, accordingly, in the code.
