### ISSUE TITLE
Chrono suit has wonky movement/camera issues

### ISSUE THREAD

**Issue by Artorp** [ParadiseSS13/Paradise#313]
Chrono/TED suit movement on tg: http://a.pomf.se/qgoitd.webm

And here's paradise: http://a.pomf.se/muzfdl.webm

I know the suit is admin only as of now but might as well put this here as reference.

**Comment by Markolie** [comment]
This is largely an issue with the fact that our code's much less optimized than /tg/'s. Don't think that fixing this is viable at the moment. Bug will remain open of course.

**Comment by Artorp** [comment]
I don't know what kind of arcane arts you guys are studying, but I'd like to become an apprentice. Consider this issue fixed!

http://a.pomf.se/auwwba.webm

Holy shit, the new process scheduler is amazing.
