### ISSUE TITLE
Ion storms don't affect unbound borgs

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#3134]
Ion storms don't add laws for borgs that aren't bound to an AI. I'd assume this is an oversight and not intentional.

**Comment by FalseIncarnate** [comment]
The ion storm currently targets AIs, which then would pass their laws down to their synced borgs.

Without an AI, I do not believe anyone is affected by an ion storm. Probably to avoid things like maint drones from suddenly getting laws like "Radiation is good for humans" and then "improving" the station accordingly.

**Comment by Tastyfish** [comment]
I actually hadn't ever looked at the code and didn't know about the bot thing, that's pretty funny. I guess the actual question I have now is whether unbound borgs *should* be affected by ion laws, because it wouldn't be too hard to implement that in a non-snowflakey way that would exclude drones.
