### ISSUE TITLE
Vox Tails Overly Bright/Yellow-Green/Wrongly Coloured

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#3138]
With the new animated Vox tails implemented, an issue has become apparent.
Now, the tails have the potential to be ridiculous colours-- as per whatever the bodycolour is set to (if not black).

![voxtailcolourissue1](https://cloud.githubusercontent.com/assets/12377767/12159603/ac13e634-b4b1-11e5-985d-bcfd324b50ae.PNG)

The wrestler Vox was just part of a screenshot I had on-hand-- but the comparison is still there

~~Furthermore, the tail appears to be overlaying ontop of arms/hands as even with gloves the tail appeared to hide the hands behind it. This is the biggest problem.
Another effect of this same issue seems to be that satchels also cover arms.~~ Fixed by #3166

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
Not a bug. 

This is caused by selecting a body color other than pitch black (no color). If you set it to this, then it will match your Vox's main body color dead on; if you have it set to anything other than this, then it's going to be colored to a degree and not match.

**Comment by tigercat2000** [comment]
... the problem here is probably blindly applying body color to tails

**Comment by KasparoVy** [comment]
Uh oh.

....Fuscia Voxtails.

**Comment by Fox-McCloud** [comment]
![img](https://i.gyazo.com/766f646a5739514d4b08ba6dc6a998c4.png)

**Comment by tigercat2000** [comment]
on second thought, pink tail voxies is the cutest thing, never patch~ :heart_eyes_cat:

**Comment by Fox-McCloud** [comment]
Yaya, me is have prettiest quills.

![OHGOSH](https://i.gyazo.com/53e79f88bfbdb36e0b0bdb1b7176a66a.png)

**Comment by TheDZD** [comment]
NOPE NOPE NOPE NOPE NOPE NOPE

**Comment by tigercat2000** [comment]
... maybe not the second example but the first is cute

**Comment by Spacemanspark** [comment]
Nononononononono vox don't need to be pink nonononono.

**Comment by Fox-McCloud** [comment]
you is no like? Me is many sads....

**Comment by KasparoVy** [comment]
Lmao, that's pretty hilarious.

TFW someone jumps in a vat of paint

**Comment by Spacemanspark** [comment]
Me is normal voxy. Is no like pinks!
You is bads. Very bads. Is skreks for making pink voxy.

**Comment by Robertha89** [comment]
Time to greyscale the vox icons

**Comment by tigercat2000** [comment]
nu

**Comment by KasparoVy** [comment]
Been taking a look at it myself, I fixed preview icon generation in the character configuration menu but no dice for update_icons or datacore yet.

The reason why I didn't suggest trimming off the pixels that overlap the arms is because if a Vox has a cybernetic limb-- or is missing that limb altogether, the tail will suddenly be floating detached from the body

**Comment by Spacemanspark** [comment]
Yaya, is have floating ass in air! Is totally normals! Is use hovers technology!

**Comment by Crazylemon64** [comment]
I was thinking simply giving arm sprites higher precedence than the tails when facing the side... Or is this an impractical suggestion?

**Comment by KasparoVy** [comment]
Arm sprites are generated before anything else, mixed in with the 'base icon' part of update_icons

To keep tails behaving the way they are-- overlaying what they do, and to be overlayed by arms would mean that arms overlay some stuff that they shouldn't and, additionally, won't be affected by damage overlays and such

hmmm

**Comment by KasparoVy** [comment]
I think I accidentally fixed it, continuing to test my solution and I'll edit this post afterward. Wasn't really expecting anything to come of my fooling about but it appears all is well

**Comment by KasparoVy** [comment]
Addressed in part by 3166
