### ISSUE TITLE
A whole bunch of turfs runtime at world load

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3142]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/game/turfs/simulated/floor.dm#L49>This line, right here.</a>
It tries to call the `update_visuals` proc of a SPACE turf (`/turf/space`) here somehow, so I've got no idea what's going on there.

**Comment by Tastyfish** [comment]
I think it's specific to the moon outpost gateway level, or at least triggered there when I ran the game earlier.

**Comment by Crazylemon64** [comment]
I've got away missions disabled, so I'm not sure why that would be the case

**Comment by Fox-McCloud** [comment]
uhhhh---I've not seen this on my local copy---you mayyyy want to wait an update or two and see if this is still happening.

Yes, we've had ghost runtimes that impacted everyone for like 1-2 PRs and, despite nothing changing relating to them---they magically vanishing a few updates later.

**Comment by tigercat2000** [comment]
I have seen runtimes relating to this, but not at world start- I've seen them when playing with the admin build tools; Calling ChangeTurf() on a turf before the 5 deciseconds is up doesn't cancel any running procs, for some fucking reason
