### ISSUE TITLE
SSD people are standing

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3145]
title, it happens at random.

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, isn't this intended? I've seen it on other servers for years back.

**Comment by Robertha89** [comment]
It's not, it's been, fall over, for as long as I can remember. And you can't get em to stand, unless you buckle em to a chair or something.

**Comment by tigercat2000** [comment]
[this](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/life.dm#L831-L832) should probably be moved to `/mob/living/carbon/human/handle_sleeping()`

**Comment by FalseIncarnate** [comment]
Standing SSD typically is an aghosted admin.

Don't touch.

**Comment by Robertha89** [comment]
typically, yes, but considering I've seen this happen a few times over the past month, and I know for a fact that neither of the players are aghoster, or admins, also, honestly, aghosting should do the ssd thing. but feature requests are verbotten here.

**Comment by tigercat2000** [comment]
No, it definately should not do the same, as admin bodies should not end up in cryostorage, it makes our job harder.

**Comment by Robertha89** [comment]
But if an antag is to kill a person who is also an admin, and the admin is aghosting at the time, there would be no reason for him to check if ssd or not, because standing.

**Comment by tigercat2000** [comment]
You should always fucking examine someone who appears to be AFK before murdering them, or you can expect to be PM'ed regardless of if it's an admin or not.
