### ISSUE TITLE
Nuke ops winrate is so incredibly low

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3148]
Because ranged instastun weapons = Bullshit

I suggest making their hardsuit in combat mode block basic stuns such as tasers and the goddamn revolver, while still going some stamina damage. The thick plating "absorbs" the initial kinetic damage and only the shock of the weapon is left, i don't fucking know.
Stun batons should remain the same, because if you're allowing security to get that close you're no longer at a disadvantage, you're just bad at the game.

I put this here because about 70% of the coders have admitted to not reading the suggestions forum.

**Comment by Earthdivine** [comment]
TG Nuke Ops Eshields now properly block Stun batons.

But more then often it is entirely not equipment that is the issue, it is the players themselves that are. There are tons of problems the players themselves have that cause Nuke Ops to fail far more then "lolstunned" and saying that is the leading cause is dumb. Stuns can be gotten around by SO many equipment options it's not even funny. The fact that the nuke ops get fucked by people,stealing their nuke, the nuke ops trying to 1v6, or can't even find their desination, and further more, NOT PLAYING AS A TEAM, but rather "THE ROBUSTEST NUKE OPS", is far more the leading cause of Nuke ops failing.

That's not to say instant stuns aren't a problem. But it is certainly NOT this problem.

**Comment by TheDZD** [comment]
@Earthdivine Not to mention that one of the biggest issues for nuke ops is a large server population, as after a certain point the crew can throw bodies at them faster than the nuke ops can mow them down.

**Comment by Regen1** [comment]
>Stuns can be gotten around by SO many equipment options it's not even funny.
Adrenaline implants which are expensive, two(?) use "i am not stunned anymore, but I can be instastunned again" 

>The fact that the nuke ops get fucked by people,stealing their nuke.
That means getting close to them, see -> Stun baton

Rest of the arguments, see:
>you're just bad at the game
As in, this isn't a proposed change so that nuke ops is everyone's easy greentext happyday, but so that we'll see a least some gameplay other than the entire 75+ crew bumrush as soon as the words "red hardsuits" are uttered, meatshielding, picking up the insta stun ranged weapons which only counter is to 1: Not get hit. 2: Kill the person first.

**Comment by Fox-McCloud** [comment]
I ded, pls nerf.

**Comment by theColdflame** [comment]
this isn't a bug

**Comment by Plotron** [comment]
Nukies tend to get killed because of friendly fire, their own explosions or because of splitting up.
I do not see insta-stuns being used with much success against them, and I've observed quite a lot of these rounds.

If you're in a group, they can't stunlock all of you, they can't win. If you're alone, then you have to take the risk.

**Comment by Robertha89** [comment]
give nukies their cr20 back

**Comment by KasparoVy** [comment]
A Vox' life goal is to steal a nuke ops nuke

It just so happens to be a viable method of saving the lives of every survivor aboard the station, if only for a while

**Comment by Regen1** [comment]
>this isn't a bug

Thank you for reading the OP on why this was posted here.

>nuke ops use ballistics. ballistics are stuns. it works both ways

No they don't, revolver might be the only ballistic weapon I can think of that instantly weakens, and applies stamina damage, as well as doing 15 (soon 5) brute damage damage.

>adrenal implants render you stun-immune for several seconds after getting up, and provide healing

Stun resistant, you'll still drop to the floor, losing your items, such as your weapons or your energy shield.

**Comment by theColdflame** [comment]
Not sure why ops would be using rubber bullets in their revolvers? Regardless, 1-2 Shotgun blasts will paincrit you for several seconds, same for 3-4 pistol shots, and a burst with any automatic ballistic.

Putting aside my disagreement that nukeops are weak, I'll actually discuss the proposed changes here; Stun immune nukeops would win the vast majority of the time. Assuming they breach the station undetected, sec can do absolutely nothing until guns are distributed. I don't have any numbers, but I'd estimate 2-5 full minutes before sec are equipped to fight nukeops if none of their weapons are effective short of the baton.

you're also letting traitors buy stun immunity at a VERY reasonable TC price.

**Comment by FalseIncarnate** [comment]
The main issue here (from the OP) is RANGED stuns, of which there truly is one instant stun: electrodes.

However, just as lasers and disablers are bounced by an eshield, so too are electrodes.

If nuke ops are attacking a largely energy weapon equipped station, they'd be stupid not to invest in at least one shield and use the guy holding it as their point man.

All other ranged stuns (short of maybe a thrown stun baton, if that still works) are non instant or straight up blocked by virtue of THICKMATERIAL hardsuits and internals.

Scaling to population would be a nice buff for both sides, but is unrelated to the initial (non)issue.

Ballistics do stun via pain/stamina, but that is much less common unless the ops fumble their weapons and get mowed down by the mime. Between adrenal implants, battle chems, and recent changes to the revolver rubber bullets, not to mention the inferior ammo capacity of station ballistics, a smart ops team will have little issue countering even some of the most valid hunting bartenders and detectives.

**Comment by Earthdivine** [comment]
>Stuns are an issue, no means to fight them
>Double Esword, Eshields, Adreneline implants all are HARD counters to Tasers
>Ion Rifle drains the battery from batons and tasers.
>Syndiborg gives no fucks, they have 2 mechs they can buy.
>Can also order Carp, Visceriators, and various forms of grenades and chemicals to fight security without being in taser range, much less dealing with the grey tide.

Other then porting the Baton nerf for the Eshield from TG, There is almost nothing wrong with their equipment options. "Get good", is literally, their problem, as bad as it is to say.

**Comment by Regen1** [comment]
>"Get good", is literally, their problem, as bad as it is to say. 

With the changes to the revolver and the blueshield I have to agree

We'll see how stuff works out now
