### ISSUE TITLE
Ragin' Mages existing bugs

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3155]
Given that Ragin' Mages isn't in rotation, I assume there are some aspects that aren't working right - knowing those before I start will help me greatly in refurbishing the game mode. Any pointers?

**Comment by Crazylemon64** [comment]
Also, the nature of this mode will require a lot of players to test, and I don't plan on making 5 multis to test all of this - Any better suggestions on how to do so?

**Comment by TheDZD** [comment]
My memory isn't quite exact, but from what I remember, last time somebody tried to run it, the gamemode failed to create more mages after the first, although at this point I can't remember if it even succeeded in making the first mage.

As for testing, you could try pinging some of the coders here to see if you could arrange a time for testing the gamemode with several people. (Depending on the date and time, I may be able to help as well.

**Comment by Crazylemon64** [comment]
Well, I have some things to get in order before I dedicate a large chunk of time

**Comment by Crazylemon64** [comment]
I'll hold on pinging everyone until I've got something that works - once I do so, I'll do a massive ping to test with many people.
