### ISSUE TITLE
No body colour option at Vox Setup?

### ISSUE THREAD

**Issue by ExitGame** [ParadiseSS13/Paradise#3160]
So, as far as I can tell, there is no body color changing option in the Vox setup. So I'll be stuck with miscoloured tails.
I know it should be under "eye color" but it ain't.

I've downloaded the GitHub code and started a localhost server to check it out, but appearently I /can/ change the body color there as that option appears on that setup menu.

So I'm not sure what to make out of it.

**Comment by Spacemanspark** [comment]
Perhaps a database issue?

**Comment by TheDZD** [comment]
Did you happen to make yourself an admin on your localhost server?

**Comment by ExitGame** [comment]
Uh, yes, yes I did. Does it change anything?

**Comment by TheDZD** [comment]
Admins are allowed to change their body color regardless of whether or not the species would normally be allowed to, which explains why you were able to do it on a local server. So as-is, this isn't a bug, although #3138 is still an issue.
