### ISSUE TITLE
Flipped Tables have normal (standing) tables overlayed

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#3163]
When you flip a table, the old non-flipped table sprite does not get removed, but you also get the flipped table sprite added in under. It looks like a tablefort bunker.

**Comment by tigercat2000** [comment]
working as intended label please
(aka FUCK THE GOD DAMN BULLSHIT TABLE CODE)

**Comment by Plotron** [comment]
What is more, when you put the table back, nothing changes sprite-wise, but mechanically it works as intended.
When you flip it again, the flipped table sprite updates, but you still have a tablefort.

**Comment by Plotron** [comment]
It's even worse than I thought. By clicking on the glitched sprite, you put the item on it. Even though it's flipped. you end up with items hidden under the tablefort.
