### ISSUE TITLE
Nanotrasen Representative's stamp marks pages with Central Command Approval

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3167]
This probably shouldn't happen for kind of obvious reasons.

**Comment by Plotron** [comment]
Pfft, I just got used to it.

**Comment by Tastyfish** [comment]
I'm pretty sure that this is unironically intentional. He's by definition a representative from CentCom. (The fact that you can use the stamp to forge CentCom faxes is a fun side-effect.)

**Comment by Plotron** [comment]
You can always meta that.

**Comment by fludd12** [comment]
Isn't there a NT Rep specific stamp, though?

**Comment by Tastyfish** [comment]
In a sense, yes, because the `centcom` stamp item is named "Nanotrasen Representative's rubber stamp" but it is the one stamp that actually produces the Central Command stamp design.

**Comment by ID404-NotFound** [comment]
The chameleon stamp no longer has CC Approved stamp? My scam is over ):
