### ISSUE TITLE
Player Panel, Mob Creation bug

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#317]
This is an admin only bug, but it's still annoying to us and hopefully it can be fixed.

If you go to your Player Panel and do Rudimentary Transformation: Human, you create a human mob. If you then Aghost, put a CKey into that new body, open your Player Panel again and make a new mob through Rudimentary transformation, the Ckey of the old mob is put into the new body, rather then the Ckey of the Player Panel. This has led to some very unfortunate things, like the Infamous Pubby BSA.

**Comment by Markolie** [comment]
Next patch will include a possible fix. Let me know if it works.
