### ISSUE TITLE
The devestator LMG is invisible in hand

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3172]
http://puu.sh/mpszf/5422e6195c.png

http://puu.sh/mpsCz/3988c5f9ed.png

**Comment by CrAzYPiLoT-SS13** [comment]
And what is it supposed to look like? 
Something like this: https://www.dealspwn.com/writer/wordpress/wp-content/uploads/2011/10/AS-24-Devastator-540x265.jpg ?

**Comment by Regen1** [comment]
@DaveTheHeadcrab
