### ISSUE TITLE
Tail Icons and Icon Problems, In general

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3183]
@KasparoVy 

Please test your PRs for things before submitting them; this would have been super obvious in testing.

This happens when you wag your tail:

![img1](https://i.gyazo.com/a9c081c6d56197ca5e49da753f31a5b8.gif)

also, a good portion of your icons do not properly show up when you first join in the round, resulting in this:

![img2](https://i.gyazo.com/261e0a15d3c213ab032e8ef3ad6bd9a4.png)
![img3](https://i.gyazo.com/644433039028463fbcdf58cd87294561.png)

**Comment by Plotron** [comment]
The atrocity. The nine-tailed fox attacks!

**Comment by KasparoVy** [comment]
All sorted. Can close issue plz? :cold_sweat:
