### ISSUE TITLE
Disposals pipes/bins etc sometimes glitch their icons for specific people

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#3191]
For at least 2 different rounds on different days I know of, after a little over and hour into the round, multiple people reported both disposal pipes and bins switching to using random icons, it fixing when they relogin.
I would resign to say that this is a byond issue, but it's specific to disposal-related stuff, so something about those objs must be inducing the bug.

I'm not sure if screenshots would help, but if anyone had one, it would possibly be helpful.

**Comment by Ar3nn** [comment]
I don't have screenshots, but maybe referring to specific sprites might help the hunt for whats pointing to them? In my case, it happened twice in one round to me. At first, I noticed the disposal in the CE's office was a space tile. I ahelped to confirm it was a client-side problem, cleared my cache and logged back in. About ten or twenty tops minutes later, I notice that every disposal is now a broken MULEbot, and remains so until the round ends.

**Comment by Tastyfish** [comment]
Some examples I heard people ask in ooc are: janiborg (presumably Mop Gear Rex), some sort of bar drink, bar sign, some lattice-like chunk of something, and nothing.

**Comment by FalseIncarnate** [comment]
At first glance, this sounds like the work of an admin replacing icons via var-edits, but relogging wouldn't change them back in such a case.

Possibly some sort of cache / rsc issue, but hard to tell without more information.

**Comment by Tastyfish** [comment]
Yeah, I would agree that it's probably cache corruption somehow, (although it's excessively rare that that would ever happen to non-html resources) and it's so strange that it's exclusively the disposal stuff as far as I know.

**Comment by Tastyfish** [comment]
I don't think this has happened again after about a week or so after this originally happened, so it was probably some sort of temporary corruption/byond version bug.
