### ISSUE TITLE
Items are able to be dropped inside of Mechs

### ISSUE THREAD

**Issue by Alkheemist** [ParadiseSS13/Paradise#3193]
Step 1: Carry or wear a maint drone
Step 2: Enter a mech
Step 3: Have the drone resist to wriggle free
You have now banished a poor innocent drone to the void between dimensions. Exiting the mech doesn't eject the drone as well, and the drone doesn't drop onto the floor.

Discovered by Streather and myself. Sorry Streather.

**Comment by Fox-McCloud** [comment]
They're technically inside the mech in nullspace.

Not much that can be really done to fix this, to be honest, other than using some potential get_turf() operation when they wiggle free (though that's going to result in odd behavior like wriggling free in a closet and windg up on the turf instead of inside the locker.

**Comment by pinatacolada** [comment]
I feel like the simple way to solve this is to not being able to use resist if you're in this scenario

**Comment by Spacemanspark** [comment]
But then that might screw you over if someone grabs you, jumps into a mech, and then goes SSD.

**Comment by Crazylemon64** [comment]
I'd imagine similar things would happen, say, if you entered a cryotube while holding a drone, or a cryopod, or a dna scanner, or a sleeper or... a lot of things, let's just say. Perhaps the drone_holder object should check the resist_object proc of the location it's in, too, so this trap doesn't come up anymore.

**Comment by pinatacolada** [comment]
just realized diona nymphs probably suffer from the same problem, didn't test though

**Comment by tigercat2000** [comment]
the _simple_ way to fix this would be making mecha able to resist out of

**Comment by Crazylemon64** [comment]
I need to make mob holders check for `allow_drop` of the parent object's location...

**Comment by fludd12** [comment]
Is this still relevant with the check-under-seats verb or whatever?

**Comment by taukausanake** [comment]
Mechs have that check? I thought it was just space pods but I can't recall

**Comment by Crazylemon64** [comment]
Mechs don't have it but this will be fixed once I get #5489 done

**Comment by Certhic** [comment]
This seems to have been fixed

**Comment by Squirgenheimer** [comment]
Also confirming this seems to have been fixed. I just tested it locally and drones pop out onto the turf below.
@Crazylemon64
