### ISSUE TITLE
Some Chemistry Machines not upgradeable

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#3201]
The Chem Masters and Chem Dispensers (but not the Chem Heaters, it seems) in Science and Chemistry are unable to be upgraded. The exact same machines can be built by printing their circuits and assembling the machine normally. When fitted with max level components, the built machines are able to produce more chemicals than the default machines that exist at round start. There's a total of eight machines as far as I know, two of each kind at the two locations.

(I apologize if I did anything wrong with this bug report. This is my first GitHub post and I still don't fully understand the interface of the website.)

**Comment by Fox-McCloud** [comment]
Not a bug--definitely a feature request.
