### ISSUE TITLE
Wizards can teleport directly to the Z2 level Shuttles.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3204]
As title, the teleport scroll can target the Escape Shuttle and Syndicate Shuttles. This is obviously a very bad thing.

I assume @tigercat2000

**Comment by tigercat2000** [comment]
I think there is another issue report about this. There's nothing for stopping wizards teleporting to shuttle areas, afaik

**Comment by Earthdivine** [comment]
Jaunt and Blink are disabled on Z2, so this is the only way to teleport to them currently.
