### ISSUE TITLE
Ragin Mages will try to spawn apprentices as Wizards

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3205]
I assume its looking for the people who have Wizard selected or something, we had two wizards spawn in from the same CKey, while he was an Apprentice.

Uh, I assume, @Crazylemon64

**Comment by Crazylemon64** [comment]
If the get_candidate function is hit, and the wizard pref is enabled for at least one ghost, then spawning a wizard in should be immediate - no chance for the ck to be kidnapped by an apprenticeship. I'd like the chance to witness this first-hand, though - I'm not sure why this would be happening.
