### ISSUE TITLE
Ragin Mage spawn timer seems too short, or starts too early.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3206]
It set the amount of wizards max to an acceptable level, but we had 3 or 4 wizards spawned in by 15-20 minutes.

@Fox-McCloud for Balance stuff and @Crazylemon64 I suppose.

**Comment by Crazylemon64** [comment]
It's every 5 minutes - that's probably too short, perhaps every 10 minutes might work better...

**Comment by Crazylemon64** [comment]
How nuts do you want it by default, @Earthdivine?

**Comment by Earthdivine** [comment]
7 sounds fine for now, that would be around 20 ingame minutes for two more, which sounds far better then 4. Thanks for the quick look at!
