### ISSUE TITLE
Constructs being unable to destroy girders

### ISSUE THREAD

**Issue by Knivarn** [ParadiseSS13/Paradise#3208]
Currently, both the artificer and the juggernaut can destroy reinforced and regular walls, but leaves a grinder remain that they cannot interact with, is this intended?

**Comment by TheDZD** [comment]
Sounds like it might be an issue with the simple_animal environment_smash variable, not certain if it's intentional or not but it sounds odd enough that it is likely a bug.

**Comment by KasparoVy** [comment]
Girders man, girders

**Comment by Knivarn** [comment]
@KasparoVy Have I really called them wrong this entire time?
Damn.

**Comment by Plotron** [comment]
@KasparoVy I didn't even realize it was *GRINDERS*. Dafuq~!

Anyway, fixing this would buff these constructs, significantly. It's Hulk level of all-access.
I guess they deserve it, though.

**Comment by Knivarn** [comment]
@Plotron Being able to destroy a wall but leaving something immobile in it's place is the same as not destroying the wall in the first place. Plus, Artificer can't even remove the walls they place as it is right now, since it leaves a cult Girder.
Jesus, that's an awkward word.

**Comment by CrAzYPiLoT-SS13** [comment]
Might want to change the title to, say: Constructs being unable to destroy girders

**Comment by TheDZD** [comment]
Huh, somehow I didn't notice had spelled it as "grinders" and not "girders."

**Comment by ScratKnapp** [comment]
This also applies to Standard Guardians, which is able to punch down the walls themselves but not the girders, making this ability fairly useless unless you stand there with tools to finish the disassembly.

**Comment by Ar3nn** [comment]
Once it hits girder stage, you can wrench it in like a second if you're quick.

**Comment by Knivarn** [comment]
@Ar3nn Yeah, it's too bad constructs can't use wrenches, so when the poor artificer tries to make a base and accidentally places a wall instead of flooring he can't deconstruct it.

**Comment by Plotron** [comment]
A wall that leaks air, by the way.

Anyway, do non-reinforced walls also leave girders? If that's so, previously it was different, and only reinforced walls weren't completely breakable.

**Comment by Knivarn** [comment]
@Plotron I can personally confirm that cult walls, normal walls and reinforced walls leave girders.
Atleast I think I tried reinforced walls, but I know for sure the rest leave a grinder atleast.
I was stuck in the gravity generator room on the first "New" wizard round, can't recall the name, as an artificer.

**Comment by Ar3nn** [comment]
Ragin' Mages?

**Comment by Plotron** [comment]
That's quite bad. Girders should be left only by reinforced walls...

**Comment by Knivarn** [comment]
@Ar3nn Correct!
@Plotron I was on that train of thought too, maybe let juggernauts destroy reinforced walls, but leave the artificer to only destroy normal and cult walls instead of leaving a grinder it can't interact with? The juggernaut would obviously be able to destroy normal and cult walls aswell :^)

**Comment by tigercat2000** [comment]
okay so for actual code
they could never destroy girders, and both rwalls and walls produce girders based on RNG

but they should probably just be able to destroy them, it makes no sense for them to be able to smash the wall but not get through it

**Comment by Knivarn** [comment]
@tigercat2000 We could try that, or make it not produce girders at all. I suppose the first option would better tho since it would stop people from walling in a construct with girders :)
