### ISSUE TITLE
Diona takes fire damage at the start of the round.

### ISSUE THREAD

**Issue by RookieMaster** [ParadiseSS13/Paradise#321]
Time: Start of the game
Species: Diona
What happends: Fire damage and high temperature at the start of the round.
Job: CMO
Location: CMO OFFICE
Diona takes fire damage at the start of the round, gets injured too.

**Comment by Spacemanspark** [comment]
This also occurs when a Nymph evolves into the adult form.
Might have just been me, but it seems to last a lot longer when you spawn as an adult instead of evolving.

**Comment by Markolie** [comment]
Difficult to fix this one, as it's sort of an issue with how the game handles initialization of mobs and light.
