### ISSUE TITLE
The URL expired.

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#3215]
What it says on the tin.

http://80.244.78.90/forum works.
http://nanotrasen.se/forum/ does not.
@Fox-McCloud @ZomgPonies @Whoever else can probably fix this with donation funds or something

Mildly important.

**Comment by CrAzYPiLoT-SS13** [comment]
The forums work for me. Can you supply more details?

**Comment by Deanthelis** [comment]
I don't know what else there is to supply.
For a large number of people (who thought it was down entirely), the first link in the OP works, and the second does not.
As far as I can tell, the domain name expired. I put it here to make sure /someone/ was aware.

**Comment by Plotron** [comment]
Same, the second URL doesn't work for me.

**Comment by Fox-McCloud** [comment]
This is being addressed as soon as possible.

**Comment by CrAzYPiLoT-SS13** [comment]
Just for the record, this is a whois lookup of the domain:
http://imgur.com/PIJj446
Weirdly, it still works for me.

**Comment by Jey123456** [comment]
it still works for you because you have it cached, either locally or at your isp

**Comment by taukausanake** [comment]
Ah, so that's what happened. I was worried that the site lost it's hosting or something

**Comment by NTSAM** [comment]
Welp, back to shitposting.
:hankey:

**Comment by Spacemanspark** [comment]
Halp I can't shitpost properly now.

**Comment by Tastyfish** [comment]
you had one job @ZomgPonies

**Comment by tigercat2000** [comment]
Talking with other admins, it seems like Google's DNS probably cleared it's entry earlier than other DNS servers.

**Comment by Plotron** [comment]
Seems solved.

**Comment by NTSAM** [comment]
same

**Comment by Tastyfish** [comment]
Yes, the registration was continued.
