### ISSUE TITLE
Beepsky isn't patrolling.

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#3218]
Beepsky is consistently not patrolling. Setting it to start auto patrolling does nothing and it eventually turns off on its own after a few seconds, as if it isn't finding the beacons or something.

**Comment by TheDZD** [comment]
*Again?*

**Comment by Fox-McCloud** [comment]
guessing this is related to: https://github.com/ParadiseSS13/Paradise/issues/3219

**Comment by Spacemanspark** [comment]
Not this again...

**Comment by Fox-McCloud** [comment]
@Tastyfish 

I'll let you know when we patch; once we do, lemme know if this is still happening.

**Comment by Tastyfish** [comment]
@Fox-McCloud Yes, it does work now.

**Comment by Fox-McCloud** [comment]
@Tastyfish 

figured as much; bet you anything that air is no longer null on walls in away misisons and other areas too.
