### ISSUE TITLE
Something is Hanging Bootup

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3219]
Something his hanging the startup of the server--no idea what it is yet, but boot time to launch the server is now roughly ~3 minutes---I suspect this is generating a number of issues such as:

- null air
- https://github.com/ParadiseSS13/Paradise/issues/3218
- Likely other things

**Comment by Fox-McCloud** [comment]
Found the problem.

*scream

Will post soon.

**Comment by CrAzYPiLoT-SS13** [comment]
I was wondering why my Dream Daemon was taking so long. Glad you found the
source.

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/turfs/simulated/floor.dm#L48

THIS is hanging things. I suspect it's why Beepsky also doesn't patrol, why away missions and other things are ending up with null air and the likes.
