### ISSUE TITLE
Turf Icons

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3221]
The plasma/N2O tanks no longer properly have their overlays

*Grumps*

@tigercat2000

**Comment by tigercat2000** [comment]
i'm fairly sure this is what that little spawn() you removed did

You probably have to change the soft-coded tanks to hardcoded turfs and force them to call update_visuals

**Comment by TheDZD** [comment]
Removing the spawn() is what did that, I discussed this with Fox prior to merging the PR that removed said spawn(). That said, having the server take an eternity to initialize is not a tradeoff should be made for a hacky fix.
