### ISSUE TITLE
Beepsky exists outside of time

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3223]
Not actually related to #3110, but I wish it was

Time stop won't stop beepsky in their tracks - they'll plow right on through, into your face.

**Comment by taukausanake** [comment]
Best cop ever. Nuff said

**Comment by NTSAM** [comment]
Beepsky is actually an ex-WWII Scientist that was working on the ability to manipulate time to his liking to aid the German army

He didn't finish his research until the war ended, but did not let the effort go to waste, and now, Beepsky is able to trespass timestop barriers with the Temporal Stunbaton. This also explains his immense speed, it's not that he's too fast, it's just that time is too slow.

feature

**Comment by Ar3nn** [comment]
So what is the actual issue here? All you did was make a joke about Beepsky, nothing specific.

**Comment by NTSAM** [comment]
Beepsky won't stop when a timestop is used on him

**Comment by Spacemanspark** [comment]
@Ar3nn We have a spell that 'stops time' (Makes mobs and projectiles slow down in a field) now. Beepsky says "Fuck you" and charges through it.

**Comment by Ar3nn** [comment]
Ohhhh. I didn't even know that spell existed because I've never played wizard before (no matter how much I want to)

**Comment by Spacemanspark** [comment]
It was only recently added.

**Comment by Tastyfish** [comment]
It's probably safe to assume that this affects all forms of `/obj/machinery/bot`.

**Comment by Regen1** [comment]
This is actually because Beepsky is the quantum lock of which the universe forms around, he isn't moving, the universe is.

**Comment by Fox-McCloud** [comment]
Pretty sure this is fixed now that beepster is a mob.

**Comment by taukausanake** [comment]
Aw, should have been a feature but balance is restored I guess

**Comment by Kyep** [comment]
Saw this today. Don't think it is fixed.

**Comment by jughu** [comment]
Beepsky the time cop strikes back

**Comment by Crazylemon64** [comment]
the meme is dead :ghost:
