### ISSUE TITLE
Night Vision Science Goggle - Broken Icon

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3235]
https://gyazo.com/ca4ff1f933f17fc0db600e3f2b14ed4d

https://gyazo.com/0c7164fabfacd956224e8eeb718353ce

There seems to be a small white box around the NV Sci Goggles icon, obviously broken.
See pictures for, well, pictures.

**Comment by KasparoVy** [comment]
Issue should be fixed now
