### ISSUE TITLE
Part bug, part cyborg feature request

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#3239]
Okay, so there's been a long-running glitch where an EMP'd cyborg loses its radio use for the round. Apparently, despite there not being an interface for it, the radio unit DOES have a switch somewhere that is turned off. I'd like the interface to be put in so this isn't a crippling disability.

**Comment by Tastyfish** [comment]
A switch other than the ones that the radio does make visible?

**Comment by Ar3nn** [comment]
The radio in cyborgs does not have an interface, just the on/off toggle that every component has. However, there is still a hidden on/off switch for the speaker, which if turned off, prevents you from hearing radio transmissions.

**Comment by Tastyfish** [comment]
There's an entire radio interface that you access from a button on the HUD, it has more options than a normal radio.

**Comment by Tastyfish** [comment]
This one 

![p 1](http://i.imgur.com/bJkl8Jx.png)

![p 2](http://i.imgur.com/GclLEL1.png)

**Comment by Ar3nn** [comment]
I always forget that button is there and never thought to click on it.

**Comment by Deanthelis** [comment]
Seeing as this issue isn't an issue, closing this issue might be prudent, @Ar3nn

**Comment by Ar3nn** [comment]
Whooops, totally forgot, I'll do that.
