### ISSUE TITLE
syndicate item Pickpocket Gloves' functions not working as intended

### ISSUE THREAD

**Issue by CupcakesNHacksaws** [ParadiseSS13/Paradise#3245]
The description for the pickpocket gloves says that it allows you to look into your target's pockets, be able to silently remove their ID/pocket items, as well as place the items directly into your hand. Currently, all it does is allow you to silently remove their item, placing it at your target's feet.

**Comment by tigercat2000** [comment]
It works exactly as intended, the description is wrong.

**Comment by CupcakesNHacksaws** [comment]
What exactly is the use for it then? It's immediately obvious this way, and for 6TC it's uses are severely limited.

**Comment by Belario** [comment]
Very much so, the selling point is that you can steal shit right from under people without them realizing.
The item dropping below them makes it shockingly obvious.

**Comment by tigercat2000** [comment]
Doesn't change, it's working exactly as it was changed to do. Pretty sure there is already a suggestions thread somewhere.

**Comment by Crazylemon64** [comment]
http://nanotrasen.se/forum/search.php?keywords=pickpocket&fid[0]=12 Not finding anything

**Comment by tigercat2000** [comment]
then create one! perfect solution

**Comment by CupcakesNHacksaws** [comment]
http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=6878
