### ISSUE TITLE
Security now only able to train in anti-air angular surface simulation.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3247]
http://puu.sh/mx29a/e5c36faa52.png

Thanks, PPI, for uncovering the secret NT plot to have Security destroy any shuttle with an angled surface.

Those are the firing range dummies, by the way.

**Comment by tigercat2000** [comment]
lolwat

**Comment by TheDZD** [comment]
If the target is showing a non-target sprite, but still functioning like a target, chances are it was either adminbus or cache corruption.

**Comment by Spacemanspark** [comment]
I saw a disposal unit that decided it wanted to be a cake hat wearing a flashing top hat.

**Comment by Fox-McCloud** [comment]
It sounds like we may need to do a clean compile some time and people need to clean out their caches.

**Comment by TheDZD** [comment]
Duplicate of #3024.

**Comment by Earthdivine** [comment]
>Need to clean compile

I clean compile every other patch I'll have you know.

**Comment by Fox-McCloud** [comment]
@Earthdivine 

Alright, thennnnnn yeah, people need to clear out their caches.
