### ISSUE TITLE
Give the Tesla engine a drawback

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3252]
Right now the tesla engine is better than the singularity in every way possible, it has no drawback, is more safer for everyone to use, and doesn't need maintenance of any kind. The only way it can ever fail is if someone makes it fail by either a huge mistake or deliberately.

It should have more drawbacks than just having to wear a hardsuit and gloves to not get shocked, and have an overload similar to the singularity reaching stage 5 (stage 9 for you code nerds)
It also produces a shitton more power than the singularity could ever hope to generate without 3 rows of collectors filled with supercooled plasma.

Same reason as last time as to why this is posted here and not on the forum, because multiple coders and maintainers have admitted to not bothering reading the suggestion forum.

**Comment by Fox-McCloud** [comment]
This is a feature request; put it up on the forums, not the Git.

**Comment by Regen1** [comment]
How about a big fucking read of what it actually is written first?

>Same reason as last time as to why this is posted here and not on the forum, because multiple coders and maintainers have admitted to not bothering reading the suggestion forum.

DZD seems to be OK with it.

**Comment by tigercat2000** [comment]
@Regen1 Have you considered he did read it, and doesn't care?

**Comment by Spacemanspark** [comment]
Caring is beneficial for your health.

**Comment by Regen1** [comment]
@tigercat2000 Sounds like pretty unprofessional behavior to me.

**Comment by tigercat2000** [comment]
@Regen1 Sounds to me like feature requests go on the forums.

**Comment by Regen1** [comment]
@tigercat2000 Shit, so we have to start forcing coders to read the suggestion forums now? this will be fun

**Comment by Fox-McCloud** [comment]
Enough, please.
