### ISSUE TITLE
Lobby Kick/Ban options

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3253]
Currently, you cannot kick someone from the game if they are in the lobby, or ban them via the Player Panel.

This means that as long as someone remains in the lobby, you need to input a manual ban, then wait until they leave, or join the actual game before you can kick them out.

**Comment by Robertha89** [comment]
manual ban, manual kick, if ya can't manual kick, gib them, and then kick them, that works. and yes, you can gib new_player

**Comment by tigercat2000** [comment]
@Robertha89 Yeah, we know how to get around it, it shouldn't be a thing in the first place.
