### ISSUE TITLE
Wood floor tiles in the bar produce normal floor tiles when crowbarred.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#3254]
![](http://i.imgur.com/R2JDZyn.png)
Just the two highlighted ones. Tested over multiple rounds.
@NTSAM

**Comment by tigercat2000** [comment]
they shouldn't produce _anything_ when crowbarred which means a shitty mapper used the wrong pathtype

**Comment by tigercat2000** [comment]
.. or not

**Comment by Tastyfish** [comment]
Those are in fact plasteel tiles with a different `icon_state`, instead of actually being wood tiles. It's actually the 2 to the left of those as well.

**Comment by NTSAM** [comment]
was really spooky

**Comment by Plotron** [comment]
Wtf.
It used to work just fine!

**Comment by tigercat2000** [comment]
floor code used to be terrible

this actually is a mapping error, in a specific spot of the bar
