### ISSUE TITLE
Secured Nuke Disk Was Not As Secure As We Thought

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3259]
The captain had the nuke disk in his possession during a recent nuke ops round, was in the shuttle. The round ended, and yet the syndies were given a minor victory for the crew not having secured the nuke disk. The captain was in the shuttle medbay at the time, if that counts for anything.

**Comment by Earthdivine** [comment]
Probably @tigercat2000

**Comment by Plotron** [comment]
Yep, that's been happening for the past few weeks.
I wonder why nobody reported that. Seemed as if everyone was aware of this bug...

**Comment by KasparoVy** [comment]
What if y'all are just getting duped by a renamed green genetics data disk named 'nuke disk'
TOP KEK

Has it been only occurring when the disk was in the shuttle medbay?

**Comment by Tastyfish** [comment]
I'm thinking that whatever's happening is across the entire shuttle, since it's all the same area.
