### ISSUE TITLE
disconnecting inside a space pod makes you loose whatever you're holding on your hands to nullspace

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#3260]
step 1: be in your space pod holding onto your bag full of guns and stuff while dancing to Danger Zone
step 2: logout/crash/reconnect/thatkindofstuff
step 3: rejoin, notice the bag you were holding with the guns and the spare cell is now gone
step 4: assume fetal position and cry

**Comment by TheDZD** [comment]
It doesn't go into nullspace, it is *in* the spacepod, but can only be taken out through VV or proc call.

**Comment by theColdflame** [comment]
@Fox-McCloud @TheDZD 

#4383 fixed this

**Comment by Crazylemon64** [comment]
#5489 now prevents dropping items when inside a space pod
