### ISSUE TITLE
Going into robotic storage as robot makes you a posibrain

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#3261]
If you...
1. Go into robotic storage (the cyborg's cryostorage) as a robot, ie the form that has no meat brain _or_ positronic brain,
2. Log out, removing yourself from the game,
3. And Log back in
You will be sitting there on top of the robotic storage machine as a positronic brain, which is especially strange since a posibrain is not a component of a robot. Also you should be a ghost, of course.
- I have not tested this for other cyborg alternate types.

**Comment by Aurorablade** [comment]
not sure if this issue if valid...not surrreeeee
