### ISSUE TITLE
Admin log on grenades

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3263]
Proximity sensor and igniter assembly wrapped in a present does not show in admin logs, making it a lot harder to find out who releases whatever chemical smoke

**Comment by CrAzYPiLoT-SS13** [comment]
Calm down there, Satan. Grenade presents, so evil.

**Comment by Robertha89** [comment]
Oh, my, god, i forgot that this is a thing.

**Comment by taukausanake** [comment]
I knew grenade-ing presents was a thing but never knew how well they worked. Someone should adminbus Joker one day, that would be glorious

**Comment by Fox-McCloud** [comment]
>Proximity sensor and igniter assembly wrapped in a present does not show in admin logs, making it a lot harder to find out who releases whatever chemical smoke

Whenever a grenade is completed, it generates a log "so and so has completed a bomb at X location containing Y."...you sure those logs don't exist?

**Comment by Regen1** [comment]
It doesn't show when detonated at least
I am very certain about that
