### ISSUE TITLE
Briefcase - Icon not showing up 'behind' player.

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3265]
I'm not sure how to word this, but here I go.

Basically, the briefcase doesn't show up behind your player sprite. If it's in the right hand, and you are facing to the left, it doesn't show up in the right hand visually. (See pictures below)
In-hand: https://gyazo.com/a126ee704e0b804a992c8f976b4c12d2
Facing left: https://gyazo.com/1508a8e203dc02c20d01d1d9e0119d01

This also is the same case for the left hand. If you face right, it won't show up visually in on your icon in your left hand.
https://gyazo.com/6405456305ba995239c23d9587955c08 (Holding briefcase in the left hand.)

This has been like this since FOREVER and I don't know why. It's not exactly a game-breaking visual bug though.

**Comment by KasparoVy** [comment]
I'm yet to check, but I have a hunch that the briefcase just doesn't have east or west directional sprites
brb

**Comment by KasparoVy** [comment]
This happens because the briefcase inhand sprites don't have a left-facing icon for the right hand, or a right-facing icon for the left hand. BRB

**Comment by kylejen** [comment]
Weird! It has bothered me since forever.

**Comment by KasparoVy** [comment]
I gave both the left hand and the right hand sprites the last remaining direction sprite, and it uncovered why this issue report really exists

If a sprite is made for the right in-hand icon for when you face left, it will still overlay ontop of your sprite in the exact same manner as if it was in your left hand, and vise versa.

Furthermore, to make a sprite with a gap in the middle isn't really viable as there are many species whose legs are differently shaped

Additionally, when looking at this sprite in the right hand while facing up as an Unathi, the briefcase appears ontop of the table

I find the lack of a sprite for that one direction in each hand the greater of two evils
