### ISSUE TITLE
You can eat guardians with the Matter Eater mutation

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3272]
This is obviously not intended, and needs a check to prevent.

**Comment by tigercat2000** [comment]
you can eat any simple animal with the matter eater mutation, so, i'm pretty damn sure it's 100% intended, and doesn't need a snowflake check to prvent

**Comment by Robertha89** [comment]
You can't eat ascended shadowlings.

**Comment by tigercat2000** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/dna/genes/goon_powers.dm#L244-L260

Ascendant shadowlings are their own subtype of simple animals, `/mob/living/simple_animal/ascendant_shadowling`

**Comment by HereticChurch** [comment]
Still should be fixed, eating a guardian spirit seems kinda broken.

**Comment by Spacemanspark** [comment]
Yet another thing that makes genetics broken.
*sigh*

**Comment by Earthdivine** [comment]
Can we rip this power out yet.

**Comment by Crazylemon64** [comment]
`/mob/living/simple_animal/hostile`
This lets matter eater work on any "hostile" mob, including guardians, and presumably slaughter demons, among other things.
This DOES seem like a very generous range to give the power...

**Comment by taukausanake** [comment]
I think that's hilarious but I would say have the guardian have a way to regenerate or not die when eated. I would totally go for a reverse xeno burst for them actually

**Comment by KasparoVy** [comment]
eat a slaughter demon
no-one will complain
