### ISSUE TITLE
Mechanic's Pod tracking Console does not track pods with Tracking becons in them

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#3277]
¯\_(ツ)_/¯ you press refresh after building a new pod and installing a tracker, and still only shows the security pod

**Comment by FlattestGuitar** [comment]
You need to activate the beacon with a screwdriver before putting it inside the pod. This isn't a bug.

**Comment by AceMcLazer** [comment]
Muh bad
