### ISSUE TITLE
Objects m_amt and g_amt don't match their design

### ISSUE THREAD

**Issue by Artorp** [ParadiseSS13/Paradise#328]
While working on the autolathe queue functionality I discovered this, might've been in the game for a while. Kind of a big deal. Easiest way to fix would be to update the autolathe_designs.dm, since that wouldn't nerf robotics. Also, some values are kinda ridiculous. And more metal would be needed for the autolathe. A proper way to go about it would be to update the object's m_amt and g_amt values, *but* robotics would need twice the amount of metal.

My suggestion: Update all objects m_amt and g_amt to match their design, but change the design of metal, glass etc to their current m_amt/g_amt values (metal would keep 3750, but cost that amount). Wouldn't nerf robotics, wouldn't nerf the autolathe, and would fix the issue.

**Comment by Markolie** [comment]
What do both of these values do? I've seen them a lot, but never really bothered to find out what they did.

**Comment by Artorp** [comment]
They're used by the autolathe and the robotics fabricator to find out how much metal or glass they should be filled with. As they don't match, you can get infinite metal and glass from the autolathe from almost half of the printable items.

I'm already working on a commit to fix it through the suggestion I posted above. Seems like the best and easiest way to go about it, unless you'd want to rework how items are inserted.

**Comment by FalseIncarnate** [comment]
Yea, an item should not give more material than it takes to produce.

Theoretically, even making them worth less than they cost would even make sense. It would need to be a low amount though, no higher than 10% loss, and possibly improved with machine upgrades.

Think of it as a refinement/recycling loss of material, or waste in the fabrication process.

**Comment by Artorp** [comment]
Yeah, ideally we should just do away with the scattered m_amt and g_amt vars, and instead look up the design cost. Some sort of recycling fee could be added in the process. For now I just updated the values.
