### ISSUE TITLE
Slaughter Demon Spawning Sprite w/ Blood Issue

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#3285]
This isn't an issue on it of itself, but if someone cleans up the blood they are spawning from, the sprite stays there, in an infinite loop. Seems to be a very minor bug or oversight. It does halt their actual spawning, but the bug/oversight merely seems to be that that the sprite isn't 'removed' in the same check that stops the demon from spawning if there is no blood.

**Comment by Certhic** [comment]
Can't reproduce, probably fixed

**Comment by matttheficus** [comment]
No longer an issue, worked last I saw during a Wizard round.
