### ISSUE TITLE
Revenants gained Dream Eater.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3286]
Appearently a Revenant can devour anyone's soul if they are unconcious. This also includes if they fall asleep through the Rest verb or from a virus. I have no idea if this is intended or not.

EDIT: This also includes people under Anesthetic for surgery as well.

**Comment by Spacemanspark** [comment]
I hate Dream Eater with a passion.

**Comment by NTSAM** [comment]
same

**Comment by Regen1** [comment]
How give them hypnosis as well, for the full Gengar experience

**Comment by Spacemanspark** [comment]
Or Dark Void, @Regen1, and have Darkrai kill literally everything. :^)

**Comment by Iamgoofball** [comment]
this is intentional

don't get knocked out with renevants about

**Comment by Fox-McCloud** [comment]
Yeah, this came about with the updates Aurablade made; it's not a bug--it's a function of them.
