### ISSUE TITLE
Meteors make pAI's flinch.

### ISSUE THREAD

**Issue by Dinarzad** [ParadiseSS13/Paradise#3287]
Basically, as a pAI (Chassis folded, was being held by master.) anytime there is a meteor impact, or something that should make the screen shake, it instead turns the screen black for a second or two.

**Comment by dearmochi** [comment]
Unable to reproduce. 

Steps performed:
1. Spawn as crew member
2. `Make pAI` via Player Panel
3. Spawn dummy human
4. Call `attack_hand` on pAI item with the human as argument (to pick up)
5. Build mode throw a mini-meteor. No shake.
6. Advanced proc call `/proc/shake_camera` on the pAI mob. Shakes as intended.
