### ISSUE TITLE
Can't print ID Console access report

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#3290]
Instead of an access report the ID console always spits out an empty sheet of paper.

**Comment by Tastyfish** [comment]
The access report prints fine for me (ignoring the ugly formatting); do you know of any details behind it printing a blank sheet?

**Comment by FlattestGuitar** [comment]
Hm. I tried to print it without an access ID, just put one into the 'receiving' slot. When I clicked on print, it just spat out an empty sheet titled 'Access Report'.

**Comment by Tastyfish** [comment]
Ah, gotcha
