### ISSUE TITLE
The Emergency Escape Shuttle has gravity

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3294]
While the rest of the station does not, which is extremely amusing when people run into the shuttle and collapse for some reason. 

Disable gravity and enter the shuttle without magboots to re-create.

**Comment by Spacemanspark** [comment]
I wouldn't find it hard to believe that the shuttle has it's own gravity generator, to be honest.

**Comment by tigercat2000** [comment]
shuttle turfs don't give a fuck about gravity, so intentional

**Comment by KasparoVy** [comment]
tfw the bluespace drive doubles as a grav gen

**Comment by NTSAM** [comment]
magnetic floors?????????????
