### ISSUE TITLE
Catching a thrown item still hits you

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#3300]
![dreamseeker_2016-01-20_16-33-00](https://cloud.githubusercontent.com/assets/589709/12451714/93454660-bf93-11e5-827b-783bd83692a9.png)

**Comment by Robertha89** [comment]
Worst part is, you can't catch bullets, you used to, and it looked awesome, i would be fine with it even hurting your hand, but it was a great mechanic/bug/feature.

And yeah, it's too bad throwing items actually hits you, it's even more fun with an active stun baton.

**Comment by johannhawk** [comment]
remember when i catched a hatchet...

it hurt

**Comment by Spacemanspark** [comment]
You can technically still catch bullets with a locker, I believe, but the timing on that would have to be absolutely precise.

**Comment by granodd** [comment]
_dusts off ancient issue report_

Hi, this is still a thing. I don't think anyone's noticed because hardly anyone uses the "catch" system from what I can see, and I bet that half of the people playing don't know it exists. Either way, if this could be looked into that'd be fan-diddly-tastic.

**Comment by Fox-McCloud** [comment]
We know, we noticed, this isn't an easy fix, which is why it hasn't been addressed.

It's not that we don't care, it's that this pretty much requires a massive overhaul of multiple systems (throwing, catching, and bumping) to fix this *one* issue.

**Comment by taukausanake** [comment]
Well someone _kind of_ fixed throw code at one point I think? Worked on it at minimum.

I really want to see a feature where you can catch bullets. Maybe something like Sleeping Carp but more range defense. Then throwing them back. Bonus points if it works on lasers too
