### ISSUE TITLE
Skellingtons are absolute nothingness

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3304]
Skellingtons (The race we can spawn in) has no actual organs or anything at all. Nothing. They exist but don't. No arms or hands, no torso, or anything, so nothing can interact with them. A sad existence, really.

**Comment by LufgtHuron** [comment]
https://github.com/ParadiseSS13/Paradise/issues/3169

This is probably connected as necrosis turns the player (or is supposed to) into a skeleton.
