### ISSUE TITLE
The new 'chromeless' windows are semi-broken.

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3310]
Hard to move them and you are unable to close the windows. Only way to actually close the window is via either relogging or walking away from the object making the window.

**Comment by tigercat2000** [comment]
The patch fucked up, nothing wrong with the code.

**Comment by neersighted** [comment]
@tigercat2000 You have an old, buggy version of my drag algorithm. Bug me and I'll show you how to improve it.

**Comment by tigercat2000** [comment]
@neersighted I stripped out a fair amount of the old code, but the problem I ran into is that mouse tracking stops when the mouse moves outside of the element. And the window doesn't move as fast as a native window, so it can end up left behind.

**Comment by neersighted** [comment]
That's a solved issue; my new drag code works past the window. Try connecting to TG and dragging a window.
