### ISSUE TITLE
Script error on nano_utility.js:52

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#3311]
Should be `return NanoUtility.extend(first[key], secondVal);`, not `return util.extend(first[key], secondVal);`

**Comment by Fox-McCloud** [comment]
I tried implementing this; it didn't correct the issue.

**Comment by tigercat2000** [comment]
@Fox-McCloud That's completely unrelated and someone forgot to sanitize the fucking item names. Which issue are you refering to specifically, because there are a quite a few?

**Comment by Fox-McCloud** [comment]
The one addressed here. Changing it to NanoUtility. instead of util. did absolutely nothing to resolve this issue: https://gyazo.com/8c30fdf21ff7d699e50a31085c7b3fa3

**Comment by tigercat2000** [comment]
@Fox-McCloud there are actually like 5 uses of `util.`, anything that refers to `util` should be replaced by `NanoUtility` (whoops)
