### ISSUE TITLE
IPC Bloodsplatter when run over by MULE's

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#3313]

**Comment by NTSAM** [comment]
IIRC they also do this when a blast door crushes on them or if something hard hits them(?)

**Comment by KasparoVy** [comment]
MULES cause red bloodsplatter regardless of race
Regardless of whether you're a blueblooded Vox, Skrell, slime, or a bloodless synthetic

**Comment by NTSAM** [comment]
Oh, woops

**Comment by Robertha89** [comment]
it's blood being squeezed form the mulebot tires from the metal ipc bodies

**Comment by NTSAM** [comment]
It's red blood though

**Comment by Crazylemon64** [comment]
Face it, on SS13, blood is more common than air, and naturally, what would you fill the mulebot's tires with...?

**Comment by KasparoVy** [comment]
^ dude that's some conspiracy

**Comment by Citinited** [comment]
Fixed, will include in next PR

**Comment by DesolateG** [comment]
This needs closed
