### ISSUE TITLE
Cloaking device (Not chameleon jumpsuit/projector) not working right.

### ISSUE THREAD

**Issue by mrturkeytoe** [ParadiseSS13/Paradise#3316]
As far as i know this is a adminbus only item but it doesn't work on tails maybe ears and definitely hair.
So you end up with a floating tail, hair and ears. (Not sure about the ears part because the character i used it with was basically the same color as the floor)

**Comment by Fox-McCloud** [comment]
I'd rather kill this than fix it, since this is literally snowflaked into human/update_icons()

**Comment by mrturkeytoe** [comment]
I think it would be cool if it were fixed, it gives me nostalgia to things like MGS.
