### ISSUE TITLE
Coolers/Heaters only use the imperial temperature system. 

### ISSUE THREAD

**Issue by fj45** [ParadiseSS13/Paradise#332]
Just a minor thing.

**Comment by Artorp** [comment]
Not sure if I understand, I thought they used Kelvin?

**Comment by fj45** [comment]
Yes, and they should also be using Celsius.

**Comment by Artorp** [comment]
Oh right, yeah that would be nice.

**Comment by Fox-McCloud** [comment]
shouldn't display celsius, exclusively, either if this change is going to be made; far more temps are measured in Kelvin, in SS13, than C or F.

**Comment by fj45** [comment]
I completely agree, I have no issue with having Kelvin AND Celsius.
