### ISSUE TITLE
NanoUI Uplink Error

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3323]
@tigercat2000 

![img](https://i.gyazo.com/983c156f2b19b6eab8eefd3a4902b527.png)

This pops up any time I click a button to order something from a tator-tot uplink.

**Comment by tigercat2000** [comment]
@Fox-McCloud it's almost certainly [these lines](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/devices/uplinks.dm#L254-L257)
