### ISSUE TITLE
Gas Filters no filtering proper

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3324]
Basically, me, ce and bartender, all vox decided to rebuild the old bar into a voxbar with voxygen and all, and the only good way to do this, was using a air supply pipe with a filter, that filters the nitrogen into the room, this is the setup I made:
![image](https://cloud.githubusercontent.com/assets/7663878/12499576/ffb3c074-c0ab-11e5-8659-3341b5d45326.png)
Here is the measurements i got from West North East
![image](https://cloud.githubusercontent.com/assets/7663878/12499603/4c29c214-c0ac-11e5-8442-cb94052df6e3.png)
the west universal pipe adapter shows as expected a 20/80 oxygen to nitrogen ratio, the north universal pipe adapter shows a 55/44 oxygen to nitrogen ratio, while the pipe to the east shows a 87/12 oxygen to nitrogen ratio.
There are the settings i had on the filter:
![image](https://cloud.githubusercontent.com/assets/7663878/12499631/8eac3892-c0ac-11e5-82f8-48fd1ab75d22.png)

The filter filters nitrogen north and oxygen south, but issue is it should only filter nitrogen north, and this is what makes me believe the Gas Filter is not filtering properly.

**Comment by Tastyfish** [comment]
Are you sure the west and north pipes were empty before you turned the filter on?

**Comment by FalseIncarnate** [comment]
Possibly related:

I was working atmos on the engineering construction site and noticed gas mixers not working right either. Both inputs had gas and everything was set and on, but there was no output. Reconfiguring it to point differently resulted in input node 2 (in this case, pure O2) just treating the mixer as a bent pipe and passing through to the output.

Not entirely sure if these are truly related, but I figure they probably share SOME code regarding input/output handling.

**Comment by Tastyfish** [comment]
I just tested both at different angles and flips and was unable to reproduce either issue.
