### ISSUE TITLE
Gibber animation effects are not glued to it

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#3331]
As in, if anything that can throw stuff around hits a gibber while it's animating eating someone, the person's overlay and the gibber's overlay will end up flying around.

Caused by: 
 Gibber uses real /atom/movable objects to animate() moving people less expensively than remaking a shitload of icons every time. 

Expected results: /atom/movable objects would be stuck to the gibber somehow, either via a while(1) loop or -tg-'s object gluing system.

Actual results: It just relies on hoping that there is no spacewind/explosions/chemistry/etc near it.

**Comment by Fox-McCloud** [comment]
The issue spam is real.

**Comment by tigercat2000** [comment]
hey it's a real issue mang

**Comment by Anticept** [comment]
What are you doing tigercat

**Comment by taukausanake** [comment]
He's making Christmas in April

**Comment by DesolateG** [comment]
Wai..

**Comment by taukausanake** [comment]
Suggestion, but I don't remember if it's a good one or not. Is the gibber anchored at all? If the problem is the gibber moves then just make it not move when it's working and not work if it can move, like most machinery. That's for the gibber at least but I don't know about the person getting gibbed

**Comment by tigercat2000** [comment]
@taukausanake Explosions knock shit around

**Comment by Spacemanspark** [comment]
Lmao

**Comment by warriorstar-orion** [comment]
Okay now I got it.

![2024_01_18__13_24_49__Paradise Station 13](https://github.com/ParadiseSS13/Paradise/assets/59303604/51260991-a889-4b41-8921-50d8c9575fc9)
