### ISSUE TITLE
Nano UI is unclickable on Vista

### ISSUE THREAD

**Issue by YukiaEpin** [ParadiseSS13/Paradise#3337]
So if the title isn't enough information, my gf and I play on an outdated Paradise station from time to time, mostly because it's the style we like best and she can click anything just fine in that server, (vending machines, DNA scanner, cloning machine etc) but on the current version of paradise station it is completely unresponsive, I thought it was an issue with me hosting, but on other servers it's broken as well, and I have no idea where to download older versions of paradise station sadly.

**Comment by Spacemanspark** [comment]
@tigercat2000

**Comment by Glorken** [comment]
I use Vista as well. I could click everything fine until a patch late yesterday that was supposed to fix NanoUI issues, I think? Anyways, now I can't use anything with NanoUI.

**Comment by tigercat2000** [comment]
this should be fixed by #3363, wait for a patch

**Comment by Crazylemon64** [comment]
Is this fixed?

**Comment by Tastyfish** [comment]
I would assume so, as I haven't heard of any issues since.
