### ISSUE TITLE
Derelict Issue

### ISSUE THREAD

**Issue by SakuraTheBabyfur** [ParadiseSS13/Paradise#3341]
Any floor tiles present on round start cannot be removed on the derelict. Ones placed after round start can.

**Comment by FalseIncarnate** [comment]
This also occurs on the engineering construction site; probably anywhere with /turf/simulated/floor/airless to be honest.

VV on a tile on the construction site revealed the floor_tile var never was set (thus null), presumably being the main source of the issue as it is unable to create a floor tile and thus craps out after displaying the message about removing the floor tile.

**Comment by tigercat2000** [comment]
why the fuck don't they have floor tile types on them

**Comment by Tastyfish** [comment]
@tigercat2000 Because in #3092 ya didn't make the airless tiles be the new plasteel type.
