### ISSUE TITLE
Butterflies

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#335]
They cannot be moved like normal simple mobs, you have to wait for them to get out of the way before you can get into their square.

Maintenance Drones cannot suck up butterflies that have died, or just in general.

Will add more to this as more issues are found.

**Comment by Markolie** [comment]
Maintenance Drones sucking them up isn't going to happen, as they're mobs and not items, and we'd have to start adding snowflake status checks for butterflies.

**Comment by Fox-McCloud** [comment]
If you're on harm intent you're going to push them as opposed to swapping spots with them; this is intentional.

**Comment by Svej** [comment]
Guy threw a labcoat at them, and it spammed the attacklogs like 30x

**Comment by Markolie** [comment]
There were thirty butterflies on that tile.
