### ISSUE TITLE
undershirt and bodymarking layering issues?

### ISSUE THREAD

**Issue by johannhawk** [ParadiseSS13/Paradise#3351]
after some mindslaving shenanigans, i have discovered that unathi bodymarkings get displayed on top of undershirts...

http://puu.sh/mFNR8/eff4588afe.png

i would love if somebody that knows their salt would investigate

**Comment by TheDZD** [comment]
@KasparoVy @Fox-McCloud

**Comment by KasparoVy** [comment]
On it

**Comment by johannhawk** [comment]
cool, this is gonna get fixed, no point in keeping this open now.

**Comment by tigercat2000** [comment]
@johannhawk don't close issues manually, let the PR auto-close them or have a maintainer close it

**Comment by johannhawk** [comment]
@tigercat2000 good to know
