### ISSUE TITLE
Vulpkanins sometimes keep their tall as a changeling, and flavor text inconsistency

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3352]
When a changeling changes to a human from a race with a custom tail the tail does not go away.

This might only apply to custom tails, I am uncertain.

People also seem to keep their flavor text when changing, which can cause metagaming etc, best case scenario is that they gain the flavor text of whoever they change to.

**Comment by tigercat2000** [comment]
it's the body accessory system, didn't code anything for lings to store/get rid of/whatever it

don't even know how that's handled, guess I'll find out!

**Comment by Regen1** [comment]
Thanks tiger

**Comment by KasparoVy** [comment]
Might just need to null out the user's body accessory var after the changeling change if HAS_TAIL isn't in their bodyflags or something

**Comment by Regen1** [comment]
@tigercat2000 This is still an issue

**Comment by Will-Bohlen** [comment]
Just tested this, and looks like the tail stuff got fixed somewhere along the line, likely by #6676. 

The flavor text doesn't carry over anymore, but looks like there's a separate issue- it gets removed entirely, even when changing back to your original form.

![image](https://user-images.githubusercontent.com/15622691/175862952-dde9eba9-5b18-4983-92fa-2bdc9c113d18.png)
It's a small thing, but extra-metagamey people who happen to know that certain people have flavor text could use it to their advantage, I guess.

**Comment by Miraviel** [comment]
The tail thing is indeed fixed. To fix the flavor text issue, one needs to move `flavor_text` to dna, so the changeling can properly store it.

Right now, the transform power simply empties the flavor text, thus the issue above happens.
