### ISSUE TITLE
Exosuit Equipment Issues

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3353]
The Death Ripley's Kill Clamp does nothing but push people around, even though it states that it's supposed to destroy them and smash guts everywhere, and the Quietus Carbine for the Recitence mime exosuit doesn't fire anything. Additionally, the exosuit mining scanner tends to make the screen flash about strangely. Mounted drills cannot do anything to other mechs, not sure if that's intended.

**Comment by TheDZD** [comment]
Fairly certain that the kill clamp and death ripley are supposed to be a joke. Quietus carbine sounds like a bug, although did you check if the person you were firing at could talk? No idea about the drill thing, probably an oversight.

**Comment by shazbot194** [comment]
I have tested the death clamp, it gibs on attack, but you need to have harm intent.

**Comment by Anticept** [comment]
Confirming that intent is required for the clamping.

Quietus Carbine for the Recitence is working properly as of this testing time, it fires a projectile.

Flashing doesn't happen to me with the mining scanner.

Confirmed that the mining drill cannot attack other mechs.
