### ISSUE TITLE
Screwdiver to the eye does no damage to slime people.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3354]
Appearently screwdrivering the eyes does no damage anymore, though it seems to still stun the target. We had someone dragging another around stabbing them in the eye over and over without harming him.

How to replicate: Obtain screwdriver. Apply directly to your eyes.

**Comment by HereticChurch** [comment]
Just tested - The screwdriver does do damage to eyes. The victim in this case was a slime person, who has no eyes to be stabbed, which may have caused the issue. Should still do damage to the head in this case though.
