### ISSUE TITLE
Missing Energy Katana and Bo Staff sprites

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3355]
The Energy Katana and Bo Staff both had sprites for when they're worn on the back, and the Energy Katana had sprites for being worn on the belt, but they seem to have disappeared.

**Comment by KasparoVy** [comment]
Looked back as far as August of 2015, no such sprites seem to exist. From when do you recall you last saw these sprites?

**Comment by KasparoVy** [comment]
Looked back as far as late 2014, no such sprites seem to exist. From when do you recall you last saw these sprites @HereticChurch?

Maybe the Energy Katana just used the Katana's on-back and on-belt sprites, since it's sheathed.

There doesn't seem to be a bo-staff whatsoever.

**Comment by TheDZD** [comment]
The bo staff sprites should be somewhere in either the twohanded weapon sprites, or with thr wizard staves. Energy katana sprite should exist somewhere as I've seen it before. If memory serves, they're both from /tg/.

**Comment by HereticChurch** [comment]
I could have sworn for some time after they were added, they had proper sprites. The Energy Katana had a very similar sprite to the regular katana's back and belt sprites, but had notches of green or white on it, if I remember correctly.

**Comment by KasparoVy** [comment]
Time to go sprite-hunting!

**Comment by KasparoVy** [comment]
IDK why this didn't auto-close but its been fixed

**Comment by tigercat2000** [comment]
@KasparoVy https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

**Comment by KasparoVy** [comment]
Thanks, I thought it was just triggered by mentioning the issue haha
