### ISSUE TITLE
Revenants can interact with certain machines

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3357]
Revenants can interact with certain machines when they are stealthed, by right clicking -> Ejecting Occupant. This works with Sleepers and Cryotubes from what I noticed, which could lead to some very cheap kills or greif.

**Comment by LufgtHuron** [comment]
Can confirm, I ate many a monkey from genetics like this.

**Comment by Will-Bohlen** [comment]
Confirmed, bug still present.
![image](https://user-images.githubusercontent.com/15622691/175864888-b409120f-3a1c-4897-8fc9-7bfad3ca379d.png)
