### ISSUE TITLE
Lots of people are having NanoUI issues

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3361]
@NTSAM, and like 20 others at least are having trouble using NanoUI. The details, I'm not sure, but this is preventing a large chunk of our crowd from playing.

**Comment by NTSAM** [comment]
We can't press any buttons in most NanoUI windows. They become unresponsive.

**Comment by tigercat2000** [comment]
I can't tell you anything without more information. Try opening your byond cache folder (usually `My Documents/BYOND/cache` or `$user/appdata/roaming/byond/cache`) while a nano interface is open, and try to open one of the many `randomstringlikeAGB35123.html` files in an actual web browser, see if it'll generate any javascript errors

**Comment by Spacemanspark** [comment]
Found the screenie @NTSAM posted.
![](http://puu.sh/mysGy/fa6903dd4a.png)

**Comment by Tastyfish** [comment]
That character number / error combination doesn't match the current build, as far as I can tell.

**Comment by tigercat2000** [comment]
@Tastyfish JavaScript errors get a bit finicky with minified and uglified scripts. You have to look around the general area of the error rather than the specified character.

Specifically, this is what is breaking: https://github.com/ParadiseSS13/Paradise/blob/master/nano/scripts/nano/nano_base_callbacks.js#L27-L30

**Comment by Tastyfish** [comment]
Yeah, I was about to edit my post to say it was almost certainly that line.

**Comment by NTSAM** [comment]
If you need me to get a more up-to-date example or something i can boot up local and get you a fresher one

**Comment by tigercat2000** [comment]
No, it's fine. You provided something useful but yet confusing.

Somehow the jQuery `.each` function is returning null objects or objects with broken classLists. No idea how.

**Comment by Tastyfish** [comment]
That's just...a bizarre thing to fail like that though, since `classList` must have a value if `obj` is a DOM element.

**Comment by tigercat2000** [comment]
then it's probably returning null elements

**Comment by tigercat2000** [comment]
the real question is why it only affects half of the server

what OS, and IE version are you running on @NTSAM

**Comment by NTSAM** [comment]
IE is Version 9
OS is Vista

**Comment by tigercat2000** [comment]
http://stackoverflow.com/a/8098430
that probably applies here to your case at least @NTSAM, should probably ask the others what they are running

**Comment by Tastyfish** [comment]
We could just change that code to use the jQuery addClass and removeClass, since apparently that works fine throughout nano

**Comment by Tastyfish** [comment]
eg the code a few lines above in the same function lol

**Comment by tigercat2000** [comment]
yeah probably, i just wrote it from how tgui does it, but tgui has magic shit running and probably doesn't support ie9 anyways

**Comment by Tastyfish** [comment]
Yeah, tg's weird :confused:

**Comment by Tastyfish** [comment]
You could replace that entire blob with
```javascript
$('.statusicon').removeClass("good bad average").addClass(uiStatusClass);
```

**Comment by tigercat2000** [comment]
will try

**Comment by Tastyfish** [comment]
Somewhere, somebody's life is depending on that medicine from the chem dispenser. We can only hope.

**Comment by Cexeutoa** [comment]
Thought I should report that this is still an issue for some people on various OS's (Win 7, Vista). Not sure about IE versions.

**Comment by TheDZD** [comment]
Hasn't been patched in yet is why.
