### ISSUE TITLE
Fluff item sprite MIA

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#3364]
My beret (Lieutenant Starsong's beret) is missing its' sprite and thus is not very much of an item. It is still deposited into my bag and is examinable until I put it on my head, at which point it can't be removed by myself.

**Comment by KasparoVy** [comment]
On it.

**Comment by KasparoVy** [comment]
Was the beret pitch black, or did it have a bluish tinge?

**Comment by KasparoVy** [comment]
Was the beret pitch black, or did it have a bluish tinge @SigholtStarsong?
