### ISSUE TITLE
Prison labor system

### ISSUE THREAD

**Issue by Artorp** [ParadiseSS13/Paradise#337]
Few issues:

- The security radio notice for when the prisoner is returning doesn't work.
- The labor stacker outright deletes the minerals, ideally it should place them at the output zone since the stacker actually doesn't stack anything.
- Iron is not accepted by the machine, but all in all iron as a mineral seems useless.

The last point is more of a general mining complaint, should probably be revisited when the new tg mining system has been ported.

**Comment by Artorp** [comment]
Another thing, the labor shuttle cockpit is accessible for the prisoners (due to the door docking thingy). There should be a glass door where the blast door is currently at.

**Comment by Markolie** [comment]
While iron is useless, it is the primary resource that spawns around the labor camp which is worth very little points: this is to balance the time people have to spend mining to get out.

**Comment by Artorp** [comment]
Oh it should absolutely be worth some points, problem is that it isn't. It's simply rejected by the stacker.

**Comment by Markolie** [comment]
Will fix.
