### ISSUE TITLE
Random access enabled on atmos closet in sec maint

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#3370]
As it says on the tin, sec officers and even the BARBER have access to an atmos-only door.

**Comment by FreeStylaLT** [comment]
Is.. this still a thing? I don't think this is still a thing.

**Comment by FreeStylaLT** [comment]
![img](http://i.imgur.com/ym1mFgr.png)
Not an issue anymore. Only people with.. both Atmos and... Maintenance access can get in these. The maint access is a bit redundant, but yeah. Not a bug anymore.
