### ISSUE TITLE
Diona temperature goes above 50 when infected with any virus

### ISSUE THREAD

**Issue by Bailol** [ParadiseSS13/Paradise#3371]
Multiple times as a virologist diona, I have created a completely 100% beneficial virus and inject myself with it. Then, after the first few symptoms my temperature will gradually increase to the point of literally burning to death.

With the same virus, I will inject other races (who on the virus stamm are affected also) and they do not burn at all.

**Comment by Fox-McCloud** [comment]
That's because Diona have different body temperatures and have much lower heat tolerance compared to other races.

This isn't a bug; it's just the way the race is.

**Comment by Bailol** [comment]
Well what's the point of beneficial viruses for diona if it just kills them in the end? Why list them on the virus-compatible races at all?

Is this the same for any other race or just for diona?

**Comment by Fox-McCloud** [comment]
just diona because they're so vulnerable to heat.

Tajarans are heat sensitive too ,but not to the same degree.

It's a weakness of the race---races have upsides and downsides in different areas; the reason it's "compatible" is because that means they can be *infected* by the virus; doesn't mean anything beyond that.

**Comment by Bailol** [comment]
I suppose if it's working as designed leave it, but I find it annoying when what is supposed to be a beneficial virus ends up killing you.

**Comment by FalseIncarnate** [comment]
Beneficial or not, viral infections will trigger auto-immune responses in the host. Typically, these are indicated by a rise in body temp as the body attempts to "burn" the virus out (as well as things like increasing antibody production and such).

Diona are listed as a virus compatible race more for the detrimental virus side of virology that the beneficial. They already are a naturally regenerating race who is pressure immune and requires no air, so most beneficial viruses are going to be somewhat redundant on them. Yes, things like lantern and the mannitol symptoms are going to have obvious benefits, but are rather specific cases.

If anything, this just reinforces my assertion (IC, of course) that there is no such thing as a purely beneficial virus.

**Comment by Regen1** [comment]
With the added chance of viruses mutating when transferring, I think we can safely assume that there is no such thing as beneficial viruses for everyone.
Because that stage 4 symptom just mutated into gibbingtons

**Comment by Crazylemon64** [comment]
That kind of hoses virology's job, doesn't it?

**Comment by Fox-McCloud** [comment]
random mutation outside of the incubator have not been a thing for well over a year now; please stop informing people it is.

**Comment by tigercat2000** [comment]
@Fox-McCloud You are incorrect, viruses mutate whenever they spread. However, mutating completely different symptoms is not possible.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/virus2/helpers.dm#L90>Is that so?</a>

**Comment by Fox-McCloud** [comment]
I stand corrected, but this:

>Because that stage 4 symptom just mutated into gibbingtons

Is literally impossible (or should be unless something screwed up).

**Comment by Crazylemon64** [comment]
Oh! Yeah, now that I've looked at it further, it DOES look like that doesn't happen before... There was a nations round, where a "beneficial virus" "mutated" into a 3-patience gibbingtons that wound up scrubbing out the entire station of organics, so that virologist was even more turpid than I thought before...
