### ISSUE TITLE
Swarmers teleport into deadly places

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#3375]
I just got teleported onto the aft port solars by a swarmer. I obviously died. This shouldn't be happening according to the wiki.

**Comment by Twinmold93** [comment]
Sounds like a blacklist check of areas it can't teleport would fix this, if it isn't already fixed. Or perhaps a check that makes sure the area is actually survivable?

**Comment by Citinited** [comment]
Unable to reproduce even by removing all the air from the station. Probably just a glitch?
