### ISSUE TITLE
[Virology] Any antigen will cure any virus.

### ISSUE THREAD

**Issue by LufgtHuron** [ParadiseSS13/Paradise#3376]
Just found this today. Made one virus, injected myself with radium and cured it.The antigen was VO. 

Remade the virus on another dish with the second symptom stage being different to be sure that it won't have the same antigen, got BR or BV, can't exactly remember. Did this a couple of times to be sure and nada, the virus won't work if any antigen is present. 

Yes, Vox were an infectable race. I made a disk with all usable races plus more to never have this problem.

To test this, I injected a fresh farwa with one version of the virus. It tested positive for infection. Took the same blood, injected myself - nothing. Took farwas blood, injected myself - nothing. Took a different antigen vial, injected it into a farwa - farwa is cured. 

This is especially annoying since antigens cant be gotten rid of so if a random event causes an infection virology could be useless for the rest of the round if it will be cured. And, I did want to cough dogs all over the station which this bug left me unable to do.

**Comment by TheDZD** [comment]
Did you analyze both viruses and check if they had the same antigen? Sometimes when you mutate a virus, the antigen will be the same, and if both custom viruses used the same base, they would in all likelihood have the same antigen.

There's also a slight chance that you may have been incredibly unlucky, as there's a slight (I believe 5%) chance that immediately upon being infected, a humanoid will generate the antigen for the virus , instantly curing it and becoming immune to it.

**Comment by LufgtHuron** [comment]
I analysed the virus each time I remade it. It had a different antigen than VO. Scanned it a couple of times to be sure too. I took a different **new** virus disk, one out of a crate, not made via the copy method and spliced (1) Waiting Syndrome, (2) Hairloss (3) Lycanocoughy and pierrots throat (same disk, two versions and blood vials, also mixed the blood too to see if it would change anything) and (4) Longevity syndrome and telepathy once. From the original viruse it was different by (2) as the old version had the blackout syndrome and appetiser effect. 

I also took blood samples from the farwa and myself to check for a different antigen and found nothing new. Vox being immune to airborne agents can't be it either because transmission was via injection (as I had accidentally spread pierrots once before when it infected via air).

**Comment by pinatacolada** [comment]
just tried to reproduce this on local. Had two stamms created with the virus2 creator, stamm 1's antigen was RHZ, and stamm 2 was B. Got two humans, one infected with each virus, cured stamm 1, isolated it's RHZ antigen and injected into the human with the stamm 2 virus, didn't cure it.
