### ISSUE TITLE
MOTD Typo

### ISSUE THREAD

**Issue by Vivalas** [ParadiseSS13/Paradise#3378]
![image](https://cloud.githubusercontent.com/assets/6334647/12538980/9bd1ca5c-c2ad-11e5-9b42-7add12eed8ff.png)

CHangelog should be Changelog

Not something you can really fix with a code edit since it's a config thing.

**Comment by Gummin** [comment]
lol.

**Comment by Plotron** [comment]
yes, I pointed that out in OOC once

**Comment by Earthdivine** [comment]
My spelling is unparalleled.

**Comment by Crazylemon64** [comment]
FIX THIS DANGIT

**Comment by Earthdivine** [comment]
@TheDZD I fixed it! This can be closed.

**Comment by Crazylemon64** [comment]
AAAAAAH THANK YOU!!!! :+1:

**Comment by Gummin** [comment]
:+1:x:100: I can finally play on Paradise again, thank you.
I've been holding off for weeks.

**Comment by Vivalas** [comment]
b-buh mah grammar nazi-ism
