### ISSUE TITLE
Deathsquad Officer Beret hides hair/facial hair

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3389]
What it says on the tin. Not sure if intended or not, but muh adminbus fluff snuwflek CC characters that I spend hours in C.M.A. Admin altering and tweaking end up having their lovely features blocked by this, meaning I can't pulse destroy the blob from space in style without pressure destroying my pretty face.

**Comment by Fox-McCloud** [comment]
it's because it's a spacesuit helmet, so it has a few unique attributes about it.

**Comment by KasparoVy** [comment]
Duct taping berets to space helmets for maximum class.
