### ISSUE TITLE
Supermatter Shards exploding on Z2 effect Z1

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3399]
In the current round, an admin left a Supermatter Shard to explode in the admin testing grounds and it appearently gave Z1 toxins and hallucinations.

**Comment by Crazylemon64** [comment]
hahahaha
Man, did i miss stuff

**Comment by Regen1** [comment]
Was it the one tully spawned? Cause I threw a body into it and then we deleted it

**Comment by Earthdivine** [comment]
There was still one in the room, dunno who spawned it.

**Comment by Crazylemon64** [comment]
kek
