### ISSUE TITLE
IPC Wizard Escaping Posibrain

### ISSUE THREAD

**Issue by Glorken** [ParadiseSS13/Paradise#3401]
Recently, I played an IPC wizard, Ralfar the Gigantic, with ethereal jaunt and the ability to cast without clothing. I was caught, and shot with a laser until I exploded with my posibrain intact. Big red letters said the Wizard Federation fired me. I then click Ethereal Jaunt, and escape the posibrain. When I become corporeal again, I am a brain with eyes and have the wizard icon above me. I could be dragged, but not damaged, and then mindswapped with another IPC. I was killed and fired again, this time without a posibrain, and the other IPC was trapped in the brain for the rest of the round.

**Comment by Crazylemon64** [comment]
hahahahaha

Alright, I should probably make ethereal jaunt check if you're a brainmob, so there's no silly stuff like this. That must have been HILARIOUS!

**Comment by Glorken** [comment]
It was for me, until I died right after. And then I felt bad for the one stuck in the brain...
