### ISSUE TITLE
Ragin Mages round still ends after all wizards are dead.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3402]
This is after the Time till Chaos triggers, so I don't know if that's intended or not. Plus both rounds this happened on I tweaked the Crew to Mage var, so I don't know if that had anything to do with it.

**Comment by Crazylemon64** [comment]
Right now, it only generates the amount of wizards right at the start of the round - there's not actually a chance to tweak it. How many wizards got generated?

**Comment by Earthdivine** [comment]
3 during a 54 round population, i moved it down to 5:1, after that the next wizard that dies ended the round both times

**Comment by FlattestGuitar** [comment]
Which way this should go? Currently the admin logs just say something along the lines of "SFW is still pissed, sending another wizard. There are X left!" but `X` has the awful tendency to just go into deep negatives, somehow.

Should the round end when all wizards die?

Right now the code is poorly trying to end it, but actually doesn't do that.

**Comment by matttheficus** [comment]
Stale. Code seems to check out as well.
