### ISSUE TITLE
MULE 1

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#341]
MULE 1 seems to have broken pathing, which is odd considering MULE 2 worked fine. Everytime I tried to get MULE 1 to move it would slam into the wall it starts at and stop moving.

Oddly enough as well, opening the MULE 2 menu turns on MULE 1 at the same time. Need to see if it happens every time or just once.

**Comment by Markolie** [comment]
This is most likely an issue with our frequency code. Basically, the bot only has a destination if it's been pinged by a signal from a PDA or beacon, and this doesn't work half the time (hence the longstanding Beepsky issue we had, and Ofitser refusing to continue patrolling). Is probably difficult to fix, although I'll make a few minor adjustments.
