### ISSUE TITLE
Chaplain can't turn his Holy Sword back into a Null Rod

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3410]
Probably not exactly a "glitch," but I'd prefer to be able to go out of knight-of-the-holy-grail mode sometimes.  Maybe have a 30+ second cooldown on changing form of the rod? Or make the rod's state change depending on if you're holding the sword with armor on or not?

**Comment by Fox-McCloud** [comment]
Not a bug, fully intentional, and this is a feature request.
