### ISSUE TITLE
Please credit/ping upstream

### ISSUE THREAD

**Issue by neersighted** [ParadiseSS13/Paradise#3411]
I noticed you guys are maintaining your own fork of NanoUI (which looks pretty good by the way). However, I also can't help but notice that a lot of changes and code have come from upstream (/tg/station), and come without any sort of credit attached. I'd love for you to ping me when you downstream my refactors/changes so I can see what you did with it and assist with any issues, and I'd also love for you to notify me of any changes you make so that upstream can benefit.

I see it as a win/win. I'm sure there was no malicious intent, but it was a bit jarring to me to see my code duplicated line for line, or my Nanotrasen SVG logo all without any attribution. Thanks!

**Comment by Fox-McCloud** [comment]
Yeah, our intention is definitely not to steal anything. We utilize very very heavily from TG; usually we make a habbit of linking to the PR where changes came from (though sometimes with super old changes/PRs, this is difficult), and sometimes we just plain forget.

We exist under an AGPLv3 license, the same as TG, so there's generally not been any problems porting implementations of PRs.

In any event, We'll try to be more diligent about linking to your individual/specific PR changes in the future; apologies for not doing so for the ones we've already implemented here (largely by @tigercat2000). Another pair of eyes is always welcome here, and I'm sure Tigercat probably has a few questions for you specifically too.

Let us know if there's anything else we can do/help with or anything that further needs to be clarified!

**Comment by neersighted** [comment]
Goad to hear that. Just keep me posted on what you guys are doing and I'll be happy. If you're ever interested in porting tgui, give me a shout as well and I'll see if I can help.

**Comment by tigercat2000** [comment]
Ah, sorry, no problem. Thought I initially added you to Nano's README.md, but rereading it, I didn't.

**Comment by Fox-McCloud** [comment]
>If you're ever interested in porting tgui, give me a shout as well and I'll see if I can help.

Thanks for the offer; we may take you up on that; I know we can certainly use all the help we can get around here. I know there were aspects of tgui that @tigercat2000 was having difficulty understanding, but were features that we ultimately would like (such as the animated progress bars and such). Ideally, we'd be at 1:1 parity with TG on tgui and interfaces, for compatibility reasons and to also avoid any licensing issues down the road (with Bay/TG/yourself).

**Comment by tigercat2000** [comment]
@Fox-McCloud Complete parity would be pretty easy, Nano wouldn't be hard to completely strip out. I'm hesitant on that, though, for three reasons:
 - Templates being in Ractive instead of doT.js
 - The complexity of how all of the JavaScript compiles together
 - Needing to remake 101 UIs, both on serverside code (they have to be changed to follow the standard attack > interact > ui_interact, and data has to be moved to it's own proc), and in the templates, which are incredibly different than doT

**Comment by neersighted** [comment]
Serverside is just a matter of regex/copypasta, shouldn't be too hard, a couple people splitting it could do it in hours. Clientside otoh, would be a fair bit of work to rework templates. However, people from bay might be willing to chip in (assuming they still are interested in tgui), as they can upstream your templates.
