### ISSUE TITLE
Can't reconnect to server

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3413]
![image](https://cloud.githubusercontent.com/assets/7663878/12592566/489c4896-c46d-11e5-9acc-0259a54d2e8c.png)
I blame #3381

**Comment by tigercat2000** [comment]
yeah well get over it, make a byond feature request, control freak doesn't have a flag to let you reconnect

**Comment by Robertha89** [comment]
![image](https://cloud.githubusercontent.com/assets/7663878/12593286/94f8266c-c470-11e5-92c9-3dcd9a3f64c6.png)
Exclude the server option, and this is what it looked like untill recently, and look here, reconnect.

**Comment by TheDZD** [comment]
This is because control_freak was turned on, no way to allow this while preventing people from getting access to server tools they shouldn't have access to while debugging is turned on, and debugging is necessary for useful runtimes.
