### ISSUE TITLE
Vox don't change sprites correctly when they change species plus the "Breathing in toxic gasses" HUD element is permanently on.

### ISSUE THREAD

**Issue by LufgtHuron** [ParadiseSS13/Paradise#3414]
I.e. be a Vox - hatch - still be a Vox. The sprite does not actually change and if it does (there was *some* black colour around my sprite) then the Vox sprite overlays it and shadowling form isn't visible. Quite powerful bug, ready to be abused by lings.

Related - the hud element which shows up when you are breathing toxins (or oxygen for Vox) never goes away. 

Regens can confirm this as he had to respawn me as a human.

**Comment by Fox-McCloud** [comment]
@TheDZD

**Comment by Fox-McCloud** [comment]
editing your title a bit to be more reflective of the actual issue.

**Comment by Crazylemon64** [comment]
Well - I didn't fix the toxic gases bit, hence me not referring to this issue
I think it's best to retitle it to the toxic gas issue, then close it once THAT is fixed.
