### ISSUE TITLE
Morgue takes closets and such

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#3416]
Just as it says on the tin, I don't think this is intended
http://prntscr.com/9vcqra putting it in
http://prntscr.com/9vcrd5 closed

**Comment by Fox-McCloud** [comment]
Pretty sure this is completely intentional.

**Comment by Ar3nn** [comment]
...Why, though? Or is it more that it'd be too snowflake to exclude it from what the morgue can take?

**Comment by Fox-McCloud** [comment]
so you can hide stuff in 'em...and I don't find that unrealistic at all.

I know this was a specific strat mentioned for traitor chaplains; they can hide their surplus crates in the tray, but that they "should be cautious as it will cause the light to turn on".

**Comment by Ar3nn** [comment]
Oh, alright, I'll close it, then, since it's intended.

**Comment by FalseIncarnate** [comment]
For the sake of information:

Body bags are a subtype of closet. If you made them not accept lockers (closets), they'd reject body bags. Almost any morgue will show bodies in bags in trays, since the bag is pretty much to conceal and contain the body.
