### ISSUE TITLE
Award-karma-to-player verb doesn't properly proceed to award what kind of karma dialog

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#3418]
as it says

**Comment by Crazylemon64** [comment]
Were you not on a turf? I find that sometimes, when I'm in a container, or something, that the dialog simply fails to proceed...

**Comment by Ar3nn** [comment]
Okay, I was in a mech, but going to regular Award-Karma worked

**Comment by KasparoVy** [comment]
I know this bug well. I encounter it regularly in a variety of circumstances but it normally occurs when I'm unconscious, dead, ghosted, alive, in my body, or spectating a player. Broad, I know. It's a strange one

Occassionally what will happen is that, out of the three different award karma verbs, only 'Award-Karma' which gives you a list of all active players actually returns the confirmation message that karma was awarded to the player you choose to give it to

The others get as far as the last step and return nothing, not spending the karma

**Comment by matttheficus** [comment]
six years old and post karma refactor, stale.
