### ISSUE TITLE
Rig Combat/Travel Modes bugs

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3421]
If you activate travel/combat mode on a helmet that is attached to a suit, you're able to simply remove the helmet with your hand. You cannot place it back on your head unless you use the toggle helmet verb.

Additionally, changing to combat/travel mode on the elite syndicate hardsuit changes the name of both the suit and helmet to blood red hardsuit helmet.

**Comment by VampyrBytes** [comment]
Looking into the other part now

**Comment by VampyrBytes** [comment]
Ok, I know what's going on, it's an oversight when flags are changed. Before I publish a fix, is it only syndi suits that have travel/combat modes? They're the only ones I can find, but I'd rather make sure and get them all in one go

**Comment by HereticChurch** [comment]
I think that should be all of them. I don't think we've got the spaceproof owl/griffon/eagle hardsuits that have combat/travel mode. Just the syndi and syndi elite hardsuits.

**Comment by VampyrBytes** [comment]
Ok, thanks. I'll get the fix up now
