### ISSUE TITLE
Observing near the (Tesla?) causes crash upon approach

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3422]
I wandered near the (presumably tesla, didn't get a chance to see), and I crashed and DC'd. Attempting to rejoin immediately crashed me again.

**Comment by Fox-McCloud** [comment]
which version of BYOND are you running?

**Comment by Crazylemon64** [comment]
509.1319

**Comment by Plotron** [comment]
Had that issue a few times when I was a ghost. And since you can't really pull ghosts, I got knocked out for quite a long time.

But that was back when the Tesla got introduced. BYOND 508.1299

**Comment by pinatacolada** [comment]
i think it's a byond issue, I'm running 508.1296 and I crash everytime I jump to someone near the tesla, or if I move to fast towards it, feels like it can't load everything in time and just gives up on life and crashes. very annoying when playing as AI too

**Comment by Spacemanspark** [comment]
I run 508.1292 and I've had no such issues.

**Comment by Fox-McCloud** [comment]
This is a two-fold issue: Part BYOND, part your PC's hardware.

This is likely because of the `animate` calls relating to `orbit` because of the rotating Tesla energy balls.

**Comment by fludd12** [comment]
It's 510+ now, is this still being encountered?

**Comment by Anticept** [comment]
Never experienced this and I've observed it a lot.

**Comment by Fox-McCloud** [comment]
This is probably still a problem and always will be, but it's not really one we can do anything about, either. Going to close this.

**Comment by taukausanake** [comment]
Wasn't this back when we could give the tesla 100+ orbs? That's what I thought the issue was about, along with the money tree thing. Just a bunch of objects making the client crap itself
