### ISSUE TITLE
Vines try to sting ghosts

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3427]
vines that can sting, tries to sting observers, who are moving over them

[code]
proc name: do sting (/datum/seed/proc/do_sting)
  source file: seed.dm,152
  usr: Bryce Harrow (/mob/dead/observer)
  src: 84 (/datum/seed)
  usr.loc: the floor (142,127,1) (/turf/simulated/floor/plasteel)
  call stack:
84 (/datum/seed): do sting(Bryce Harrow (/mob/dead/observer), the strange plants (/obj/effect/plant), "r_leg")
the strange plants (/obj/effect/plant): Crossed(Bryce Harrow (/mob/dead/observer))
Bryce Harrow (/mob/dead/observer): forceMove(the floor (142,127,1) (/turf/simulated/floor/plasteel))
Bryce Harrow (/mob/dead/observer): Move(the floor (142,127,1) (/turf/simulated/floor/plasteel), 8)
PPI (/client): Move(the floor (142,127,1) (/turf/simulated/floor/plasteel), 8)
PPI (/client): West()
runtime error: undefined proc or verb /mob/dead/observer/can inject().
[code]

**Comment by FalseIncarnate** [comment]
Easy fix that somehow got past me.
