### ISSUE TITLE
Wiki thumbnail generation appears broken

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3429]
@Regen1 
Both TullyBBurnalot and I have been attempting to upload a picture of the sleeper's UI, but we're getting: 
```
Error creating thumbnail: The system cannot find the path specified.

Error code: 1
```

<a href=https://www.mediawiki.org/wiki/Manual:Image_administration>This might be helpful?</a>

**Comment by TheDZD** [comment]
@Regen1

**Comment by CrAzYPiLoT-SS13** [comment]
You can't do it through clicking the broken thumbnail. You have to do it
through the upload page and set the same name as the file needed.

**Comment by Regen1** [comment]
Uhhh..
Right.

I think I found the issue, need to get mel to fix something for me.

**Comment by Regen1** [comment]
Issue fixed (I hope)

**Comment by Crazylemon64** [comment]
Works like a charm! Thank you, Regens!
