### ISSUE TITLE
"Continuous Rounds" is Broken

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3450]
Who knows when this was broken, as we haven't used continuous rounds since late 2013, but uh...simply put, continuous rounds breaks the round properly end.

What it's supposed to do: let the round keep on going when all antags of a particular type die.

Does it do this? Yes.

Problem: When the round ends by a shuttle call and the shuttle docks at CentComm, it'll give "the round has ended", but no end of round hooks/stats will be displayed, and the game will hang forever until "continuous" rounds is var-edited to 0.

**Comment by Crazylemon64** [comment]
Well! I was wondering why this wasn't activated, now I know! Unfortunate, that I never got an answer out of anyone directly...

**Comment by Tastyfish** [comment]
Guessing it was due to the new shuttle code port?

**Comment by Tastyfish** [comment]
@Fox-McCloud Do you want the continuous mode to do a shuttle autovote when the round "should" end? Because currently the code wants to do that (although the logic was broken). Also when the shuttle vote should happen, it says "\red The round has ended!" which looks bad. Do you prefer something else for it to say?

**Comment by Fox-McCloud** [comment]
@Tastyfish 

Nah; no vote should take place; if continuous is enabled and the antag dies, the round should keep going without any changes or notifications---when the shuttle is called and it arrives, then green/redtext should be displayed, as it normally is.

**Comment by Tastyfish** [comment]
That makes the logic even simpler :+1:
