### ISSUE TITLE
IAA jackets cant mount remotely useful things onto the suit slot

### ISSUE THREAD

**Issue by johannhawk** [ParadiseSS13/Paradise#3451]
what the title says...cant put any lightsource, IAA equipment (camera, recorder, etc) onto the IAA jacket.
sure, i can use the pockets, but lightsources cant work from there...

i for one, find this to be a issue.

**Comment by Plotron** [comment]
Not even a pen?! Blasphemy!

**Comment by Ar3nn** [comment]
Flashlights, etc, do totally work from pocket unless that was changed recently.
