### ISSUE TITLE
IPCs can't kill themselves

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#3452]
Suicide verb does nothing other than create the red notification that they are biting their tongue.

**Comment by NTSAM** [comment]
Empty-handed suicide induces oxy damage IIRC, but they can still suicide with other items.
Would be nice to have a "shutdown" suicide type but idk how snowflakey that'd be

**Comment by Crazylemon64** [comment]
/me twists their own neck backwards! It looks like they're trying to commit suicide! Or maybe they just want a better look at what's behind themselves...

**Comment by Plotron** [comment]
That's ridiculous.

We've had a caught cultist being given proper treatment in Brig, but he decided to die instead. Couldn't. So the player had to ghost. Awkward as fuck.

**Comment by KasparoVy** [comment]
Lmao, that's funny.
Use your PDA pen dude, you'll sudoku

**Comment by Plotron** [comment]
Can't use pens when you're cuffed, man.

**Comment by Tastyfish** [comment]
IHMO suiciding while in processing should be against server rules.

**Comment by Spacemanspark** [comment]
I think we purposely allowed suiciding while cuffed to allow people to do that, @tastyfish.

**Comment by Ar3nn** [comment]
I'm pretty sure its sketch at best towards its legality in the rules.
