### ISSUE TITLE
Gamma Emergency Shuttle takes longer to arrive than in Red Alert

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#3454]
10 minutes vs 5 minutes, the emergency shuttle dispatch is no longer high-priority when the station is in Gamma.

Please, someone tell me this isn't intended. I mean - Red is lower than Gamma. Makes no sense.

**Comment by Spacemanspark** [comment]
It's an oversight.
IIRC, /tg/ doesn't have a code gamma.

**Comment by CrAzYPiLoT-SS13** [comment]
Fixed in #3458
