### ISSUE TITLE
Canister View Vars Read Error

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#346]
Trying to View Variables on canisters will sometimes cause a read error that kicks you from the game with "Network connection shutting down due to read error." I haven't been able to do extensive testing on it, but it may only happen with emptied canisters.

**Comment by Artorp** [comment]
Steps to reproduce:

1. Make a new canister
2. Give it a _single_ decal
3. It will now give a read error when trying to use VV

Any combination of decals works, but if there's a single decal it will give a read error. Wrenching it to a connector will stop it from being bugged.

The plasma can has a single decal but it doesn't have any issues. Emptying it and then assigning new decals will render it bugged.

Assigning a single decal via VV and then calling update_icons() will render it bugged. Assigning a single decal and then refreshing will not make it bugged, but assigning multiple items to the list will. This does not seem to be limited to var/list/decal.

Not quite sure why this happens (something related to the overlays), but I suspect carrying multiple associative lists on the main object doesn't help. Everything that's merely being used for UI reference should instead be offhanded to a datum or something, and not clutter up the VV window.
