### ISSUE TITLE
Trapped minds don't understand speech

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3460]
Borer assumes control, the trapped mind can't comprehend any speech that goes on

**Comment by Fox-McCloud** [comment]
Reason 1023423 why coders hate theses things.

**Comment by Crazylemon64** [comment]
That might be intentional, hence me posting it here. Yes or no?

**Comment by Plotron** [comment]
I actually like that.
It gives better immersion. Like you don't understand what's even going on, you feel even more alienated.

**Comment by TheDZD** [comment]
Not intentional, considering the borer can understand what's going on.
