### ISSUE TITLE
Swarmers can teleport eachother

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#3464]
I misclicked and I teleported a friendly swarmer from Virology to Gateway.

Not sure if it's intended, but it's a potentially nifty tactic when there's an emergency.

Other than that - friendly fire risk.

I still think that from a common sense standpoint they shouldn't be able to do that.

**Comment by Spacemanspark** [comment]
I don't see a particular issue with it.

**Comment by TheDZD** [comment]
Seems like interesting bit of emergent gameplay at least. Shouldn't be much of a problem unless swarmers start being dicks to each other, in which case you should probably poke an admin about it.

**Comment by Plotron** [comment]
Cool, I just wanted to make sure.
