### ISSUE TITLE
Nobreath prevents oxygen healing

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3466]
If you get nobreath from genetics, and then get oxygen damage from having low blood, but have the blood returned, you don't naturally regen the oxy damage.

**Comment by Fox-McCloud** [comment]
It doesn't prevent oxygen healing; you don't breath, which is the *normal* mechanism for recovering oxygen. If your species/person doesn't breathe, then can still take O2 damage from other sources; you can rectify it with salbutamol, omnizine, perfluoradecalin, orange juice, or cryoxadone.

**Comment by VampyrBytes** [comment]
@Fox-McCloud I'm not convinced. If your species/person doesn't need to breathe then either they don't need oxygen in which case they shouldn't take oxygen damage at all, or they've got some other way to get the oxygen, in which case they should heal from it as if they were getting it from breathing (which is what the fix does)

If it's decided that it's not a bug I'll edit the #3477 PR so the hud warnings still get the fix

**Comment by CrAzYPiLoT-SS13** [comment]
Yep, Vampyr is right. It's not just the breathing thing. IRL the oxygen
actually goes to every cell in your body. So let's assume that if you don't
need to breathe, you don't need the oxygen in your cells. So, how the fuck
would you actually get the damage to you or actually heal it?
