### ISSUE TITLE
Cap gun induced suicides actually lead to death.

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3468]
Someone attempted suicide with the cap gun, and well, died from suicide. No pulse and everything.

**Comment by fludd12** [comment]
Intentional, it also works with tasers, disablers, and foam dart guns, if I recall correctly.

**Comment by kylejen** [comment]
Huh. That's kind of funny.

**Comment by Spacemanspark** [comment]
It's technically an oversight that it works with tasers and disablers.

**Comment by fludd12** [comment]
Really? I thought those were intentional, too. I always liked that, anyway.

**Comment by TheDZD** [comment]
This is pretty hilarious, especially when a HONK squad member does it with a HONK rifle.

**Comment by fludd12** [comment]
> HONK squad member does it with a HONK rifle
Or when a normal crew member does it with a HONK rifle.
#Bring back clown planet 2016

**Comment by Spacemanspark** [comment]
@fludd12 It's not. Nobody ever bothered to program anything specific. Old tasers would just instantly stun you.

**Comment by Kerroman** [comment]
The training laser in the brig firing range will kill you too.  You might be able to argue that it's JUST powerful enough to do the job, sort of like a gun firing blanks can still be dangerous if you're close enough.  Inversely you could argue that it's shooting the equivalent of a beam from a laser pointer and shouldn't do a bit of damage.

**Comment by Plotron** [comment]
Nerf this suicide.

**Comment by ScratKnapp** [comment]
Does the cap gun need to have any caps left for this to work?

**Comment by Gummin** [comment]
I always thought this was a feature.

**Comment by Crazylemon64** [comment]
Clearly, it makes the most sense when you do a suicide with a wand of healing.
