### ISSUE TITLE
Revenants cannot eat people who were Defib'd.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3474]
Reason is obvious but still is a bug. Once you eat someones soul and they get Defibbed, you cant eat them again.

**Comment by Crazylemon64** [comment]
That's to prevent soul farming, I'd imagine - you can normally only drain a person once, and then they're added to the list of mobs you've drained.

**Comment by Earthdivine** [comment]
Well I mean, they died and were revived again. I assumed that it would technically work since they are "alive and well again". Plus when you go to eat them again, you get "their soul is dead and lifeless".

Which admittedly is funny.

**Comment by fludd12** [comment]
Instead of fixing this, make it so that defibbed soulless people get revived as zombies or something
sp00000ky

**Comment by Fox-McCloud** [comment]
Yeah, this is more a balance than than anything else, so someone can't be repeatedly harvested.

Basically, when a revenant eats someone's soul, that person is added to a list the revenant has of people he's "ate" from and he can no longer do it again.

**Comment by variableundefined** [comment]
Bit inconsistent but deliberate design
