### ISSUE TITLE
Salting tiles doesn't stun/reveal revenant. Revenant's stuns are much longer than the wiki states

### ISSUE THREAD

**Issue by CupcakesNHacksaws** [ParadiseSS13/Paradise#3475]
Just played a round where a revenant was active, so after reading the wiki I learned salting tiles will stun + reveal the revenant if they go over it. But they didn't; they were going over these tiles just fine without any repurcussion, as I essentially salted a 4x4 sqaure, and it was able to appear and use an ability in the middle, and then quickly move out. 
 
As for the stuns, the wiki states that its stuns are either 2 or 3 seconds long, with the revenant then being corporeal for 8 seconds. In actuality, the stun is as long as the Revenant's corporeality.

**Comment by Ar3nn** [comment]
You slightly misread the wiki on your second point. The stun is usually 4 seconds, but they are corporeal for 8. They can move after the ability resolves, but they remain visible after. It's a balance thing.

**Comment by CupcakesNHacksaws** [comment]
Ah sorry, I thought the stun was referring to the crew being stunned, not the revenant.

**Comment by Ar3nn** [comment]
Noooo, the stun is for the revenant.

**Comment by Fox-McCloud** [comment]
This is largely a wiki inconsistency/lack of updates rather than a coding problem/bug.
