### ISSUE TITLE
Bluespace Tomatoes do not affect Wizards on broomsticks.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#3476]
Had a wizard/revenant round where the wizard popped up in botany and wanted to get close.  I knew what was going on so I tried to stay away to avoid getting gibbed.  We'd grown some bluespace tomatoes and so I chucked one, got a definite hit, but the wizard wasn't teleported.  Since she was riding a broomstick at the time I imagine it has something to do with that but I can't be 100% sure.

**Comment by FalseIncarnate** [comment]
Possibly the result of low potency. The teleport scales off potency, so a sufficiently low potency will render the effect useless.

If you can remember, did the hit cause sparks?

**Comment by Kerroman** [comment]
There were sparks, yes.  I tested one of the tomatoes on a fellow botanist earlier and it worked fine.

**Comment by FalseIncarnate** [comment]
Strange, I'll have to try and replicate this.

Broomsticks shouldn't be granting wizards any actual protection against this that I could notice at a quick glance at the broomstick code.

**Comment by fludd12** [comment]
Was this confirmed?
