### ISSUE TITLE
Ghosts cannot access newscasters

### ISSUE THREAD

**Issue by johannhawk** [ParadiseSS13/Paradise#3484]
what the title says, i need my papers.

**Comment by NTSAM** [comment]
Intentional I think? Ghosts can see most consoles.

**Comment by Crazylemon64** [comment]
Unless they can actually CHANGE anything, that doesn't sound like a bug...

**Comment by fludd12** [comment]
I think this was meant to be can't?

**Comment by NTSAM** [comment]
Yep, definitely meant can't. Clicking on the newscaster will do nothing as an observer.

**Comment by Crazylemon64** [comment]
ohhhh Alright! Except, I'm not sure how to have them browse the caster without messing up the UI for others...

**Comment by TheDZD** [comment]
Updated the title to accurately match the described issue.

**Comment by johannhawk** [comment]
well, this is embarrassing

**Comment by SamHPurp** [comment]
This is basically never going to be fixed.

**Comment by craftxbox** [comment]
still an issue, perhaps add a special thing for ghosts to view the newscaster network without having to mess with a specific newscaster

**Comment by AffectedArc07** [comment]
Newscasters got TGUI'd and this is no longer an issue
