### ISSUE TITLE
Fish Tanks have bottomless holes

### ISSUE THREAD

**Issue by ScratKnapp** [ParadiseSS13/Paradise#3488]
When trying to fill a fishtank (any size, big or small) with water, it will display messages that you are filling the tank (and overfilling it you click it enough), but when examined, there is no water. Eggs put into the tank will result in fish for about a second before it disappears due to no water. Tested with bowls and aquariums multiple times, to this same effect. With this bug, you cant keep fish for display or food purposes!

**Comment by CrAzYPiLoT-SS13** [comment]
Yeah, this was happening two or three months back too and I talked to an
admin which was online at the time and we couldn't find the source of the
problem.

**Comment by Crazylemon64** [comment]
If you click rapidly, you'll draw water from the aquarium and splash it on the tank again. Are you sure you're not doing that?

**Comment by FalseIncarnate** [comment]
Accidental water removal is a big possible culprit here. I've done it plenty of times myself (and I coded the aquariums) without intending or realizing it.

If you can replicate this consistently though (and ensure you aren't drawing the water out), I'd appreciate the steps for investigation.

Also check for leaks. Damaged aquariums will lose water fairly rapidly as they take increasing amounts of damage.

**Comment by ScratKnapp** [comment]
I'll try for screenshots when I play next, but this was tested on both a freshly built, undamaged aquarium in my Kitchen, and one of the fish bowls that spawns in the pet shop. Each was filled with a bucket, with the tank indicating I "filled the tank with the rest of the bucket". Examining both seconds after would say it is however "completely empty".

**Comment by FalseIncarnate** [comment]
Will investigate, thanks for confirming it wasn't a spam-click giving you a false impression.

**Comment by FalseIncarnate** [comment]
Tested on live server, wasn't able to replicate this issue. Filling the tanks from buckets worked fine, and the water didn't seem to magically disappear.

I did, however, find an issue where drawing water from the tank into the bucket would then immediately splash it back onto the tank, completely wasting it all. Not quite what was reported, but a bug that will be getting fixed.
