### ISSUE TITLE
Slipping while already laying down

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3490]
It was fun in the beginning, but people are abusing this like mad now.
Simply moving people over slipable objects such as the clown PDA and a banana peel will slip people, even when they are laying down, this can be abused to basically permanently stun people, and is used to basically drag people wherever the fuck you want

**Comment by Plotron** [comment]
:+1: 
Best feature.

**Comment by IcyV** [comment]
Eh. It's one of those things that makes SS13 what it is to me. It wouldn't feel the same if I couldn't just play around and slip people a few times for a moment. Sure it can easily be argued that it is dumb and abusable, but it is a classic thing. It's fairly easy to avoid most of the time too.

**Comment by Regen1** [comment]
Slipping people is fine, being able to permanently stun someone however is not.

It wont remove your fun with the watering hose, Icy, but it will stop the clowns from borderline griefing.

**Comment by IcyV** [comment]
Fair enough. PDA slipping is extremely silly in the first place.

**Comment by NTSAM** [comment]
I think /tg/ had a fix for this.
I couldn't spamslip on local so easily.

**Comment by pinatacolada** [comment]
you can resist out of it

**Comment by KasparoVy** [comment]
Just make a PSA for resist spamming permaslip

**Comment by Regen1** [comment]
You can resist out of their grip, they can just CTRL+Click you again
And it doesn't get you out of the stun.

**Comment by theColdflame** [comment]
If I were to try fix this issue, I'd imagine the most logical way would be to remove being pulled/dragged onto a tile with a slip item slipping you. All it does is allow for stunlocks and effectively using a peel as a melee weapon (pull>drop>move). 

The fact that a joke item is useful to the point of having an established meta using it really doesn't seem logical, though slips have been the way they are for quite a long time.

**Comment by NTSAM** [comment]
Could add some kind of var to the stunned flag-thing or something to make it ignore banana peels and shit when you're already down, can you? or am I dumb?

**Comment by theColdflame** [comment]
You could still keep pulling someone back and forth between the two tiles that way, which'd give you a very good chance of keeping them stunned unless they hit a movement key at exactly the right moment.

**Comment by VampyrBytes** [comment]
Actually, if they're using the clown's pda you can already get out of it... being stunned doesn't stop you changing your intent from run to walk, and you don't slip on it if you're walking.

But ofc some items check your stance and some don't. Possibly the best fix would be to change it so most if not all check for stance, that way you're not nerfing the actual slipping but you give people an easy way out if it's being abused

Either way, one thing I will do is a ```mob.slip()``` proc as at the moment each item is handling it individually, which is just stupid
