### ISSUE TITLE
SWAT Helmet isn't spaceworthy

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#3492]
Title. The armor is, so I'm not sure why the helmet wouldn't be?

**Comment by ScratKnapp** [comment]
The SWAT helmet itself is a riot helmet, visibly similar to the bulletproof helmet and normal security helmet. The suit should really come, instead, with a matching space suit helmet with similar protective stats to the armor.

**Comment by Plotron** [comment]
SWAT Helmet used to be spaceworthy, no?
It was oftentimes coupled with Captain's armor.

**Comment by Fox-McCloud** [comment]
It's actually not meant to be; it's resistant to the cold, but it's not meant to be space proof.
