### ISSUE TITLE
Deathsquad Borg Pulse Rifle broken

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3497]
It only fires lasers on all three modes, while maintaining the modes' sound effects. Stun still makes the taser noise, and DESTROY still makes the pulse noise, but it's all lasers.

Deathsquad borgs in general are shit and need to be buffed to actually be threatening/useful but that's another issue altogether.

**Comment by johannhawk** [comment]
i have a feeling that Church has been volunteering for DS borgs alot...

one more person to keep on eye on borg and maint drone related bugs

**Comment by Earthdivine** [comment]
Actually I think I am the one who uses them the most when I am ALICE the inspection borg.

**Comment by HereticChurch** [comment]
I've mostly been using it so I spawn as a borg not linked to the AI, but not syndicate so it can access doors. Then I usually end up just changing it's module to the Peacekeeper because it's a lot more useful.

**Comment by ScratKnapp** [comment]
Allegedly fixed with a new PR.

**Comment by VampyrBytes** [comment]
I could take offence at that 'allegedly' :wink:

**Comment by Earthdivine** [comment]
@ScratKnapp Issues don't close themselves until the PR fixing them is merged in.
