### ISSUE TITLE
Minor grammatical error mk. 2

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#3498]
http://prntscr.com/9yct4w

Extremely well-hidden, im not surprised nobody noticed before now. It's the personal log generated in the RD lab on the xenomorph outpost away mission

**Comment by Tastyfish** [comment]
Maybe those people called them xenomporphs ;)

**Comment by Ar3nn** [comment]
Related http://prntscr.com/9ycys3

**Comment by Spacemanspark** [comment]
I wonder if /tg/ ever fixed this on their side.
