### ISSUE TITLE
No Click Delay when attacking cult constructs

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3499]
You can spam click constructs to attack them incredibly fast with melee weapons. This results in quick death for any construct other than the behemoth/juggernaut.

**Comment by Ar3nn** [comment]
Oh, right, I saw this. I was an engiborg and completely fucked up one of them with a wrench np gg

**Comment by Kerroman** [comment]
If this was during the cult round last night I was possibly there with you, Ar3nn.  I remember attacking the construct as soon as it popped up but not getting the normal attacking animation or sound so I backed off thinking I wasn't doing any damage.  Afterwards I saw the attack log showing that I was, in fact, hitting it and thought it was strange.
