### ISSUE TITLE
I have wings, can you see them?

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#3500]
http://prntscr.com/9ye6ub I was a borg at the time.

**Comment by Crazylemon64** [comment]
*flip

**Comment by Ar3nn** [comment]
Borgs, drones and such can also *flip. But I figured the *flap and *aflap was less fun and more likely a bug.

**Comment by Plotron** [comment]
Flap and aflap are *fun*.
Why are you a *fun hater*?

**Comment by Ar3nn** [comment]
But I don't have wings. How do I flap?

**Comment by Spacemanspark** [comment]
Nobody cares.
You just do.
NO QUESTIONS.

**Comment by Plotron** [comment]
@Spacemanspark is damn right.

**Comment by Fox-McCloud** [comment]
Not a bug, and no, this has nothing to do with Vox--this is a very old piece of SS13 history, and it's not going to be "corrected".

**Comment by Tastyfish** [comment]
It was controversial enough that I changed the pronouns to be technically correct.
