### ISSUE TITLE
Bolas can't trip the same person twice

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3509]
If you hit someone with bolas once, then remove the bolas, that person will no longer be able to be hit by bolas again, and will simply be pushed by them when thrown.

**Comment by VampyrBytes** [comment]
Ok, done some testing and can tell you what happened. When someone is hit by the bolas one of the effects is to set their m_intent (run/walk intent) to walk. But bolas only work on people who are running, so unless the intent has been changed in between having them taken off and being hit with them again they won't work the second time

If the intent is changed then they work again

**Comment by HereticChurch** [comment]
Seems odd. Still worth a fix though, yes? Since the bolas are used as much for a stun + knockdown as they are for slowing people down.

**Comment by VampyrBytes** [comment]
Fix isn't the right word, as they are clearly coded to only work on people with the run intent, But yes, I could change it so they work on walking people as well as running people.

I'm off to bed now, and I've got my kids over the weekend, so if there's no objections raised beforehand I'll do a PR Monday to change it
