### ISSUE TITLE
Alcohol Revamp?

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#3513]
Okay, so this isn't strictly a bug, but github says that's what the issue system is for and I don't want to spam the forums with code discussion.

The alcohol system is broken, because since every single drink is a subtype of ethanol they all get you drunk at the same rate. If you mix rum with non-alcoholic stuff 1:3 to get a mojito you effectively get 4 units of ethanol instead of the 1 you should have.

I can't really code properly in BYOND, so I'm asking: How hard would it be to redo the system (possibly just add a variable that actually defines how drunk you can get off of a given drink that is a subtype of ethanol, or even make ethanol a subtype of just an 'alcohol' reagent) so that it works properly?

We were discussing this more or less on [this thread](http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=7012#p54932).

**Comment by Fox-McCloud** [comment]
Feature requests don't belong on the git; they're posted on the forums.

**Comment by FlattestGuitar** [comment]
Rip issue.

**Comment by VampyrBytes** [comment]
The issue isn't dead, I've said in the forum thread I'll look into it next week. But if every feature request led to a thread here existing issues would get lost/overlooked
