### ISSUE TITLE
[Metastation]Chemistry lacks welding fuel tank

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3514]
While making a change, I noticed that medchem lacked a welding tank. Is this deliberate?

**Comment by lolzyking** [comment]
I believe its from this 
https://github.com/ParadiseSS13/Paradise/pull/3516

Wall mounted fuel chem to save space

**Comment by Crazylemon64** [comment]
I mean, yeah, I was looking at the map at the same time, but for some reason there wasn't a welding tank there, so I tried to retain feature parity with prior versions of the map. I'll see about slapping those in, then.
