### ISSUE TITLE
Budget Insulated Gloves name issue.

### ISSUE THREAD

**Issue by Gummin** [ParadiseSS13/Paradise#3526]
Recoloring Budget Insulated Gloves causes them to be renamed to Insulated Gloves.

**Comment by Gummin** [comment]
_literally unplayable please fix_

**Comment by Robertha89** [comment]
Intended. Grab tons of gloves from medical, color em yellow, throw em away in maint.

**Comment by Fox-McCloud** [comment]
Not a bug; very much intentional for shennanigans/pranks.

**Comment by Gummin** [comment]
Ah, alright.
