### ISSUE TITLE
IPC facial reconstruction is broken again.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3531]
Viewing the variables of my head has disfigured=0, but even so, I'm the Unknown (As [X])

Something's making it not update, I guess.

**Comment by Crazylemon64** [comment]
It could also be human code being overall terrible - I suspect there might be more than one variable to track disfiguredness, but I'll need to hunt down the particulars.

**Comment by fludd12** [comment]
I really hate hating hating, hatefully the redundant, repetitive code.

**Comment by Crazylemon64** [comment]
Welll.... I've found only one spot where it comes into play, but:
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/life.dm#L86>Here's where the mouse-over name is determined</a>
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/human.dm#L692-L697>And here's the corresponding check for disfigurement.</a>

Was there anything else wrong with you at the time?

**Comment by Tastyfish** [comment]
Since it's probably a bug in the actual surgery, referencing this to #2903.
