### ISSUE TITLE
Cyborgs seem to take oldblob damage

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3535]
Right now, cyborgs take 60 damage per hit from a blob, and are gibbed if hit while deactivated. Should this be reduced?

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by KasparoVy** [comment]
Seems a fair bit 2stronk

**Comment by Fox-McCloud** [comment]
Yeah, definitely intentional---blob damage was largely nerfed for humans because a lot of the damage was pushed into reagents---borgs are..well, obviously reagent immune, so they weren't really changed.

**Comment by Gummin** [comment]
So basically if your a borg, don't even think about it.
