### ISSUE TITLE
Succumb Verb Fails to Function for IPCs

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#3537]
[Link to verb](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/living.dm#L34). Just as the title says, an IPC in crit cannot use the Succumb verb to die, probably because it does oxyloss to finish them off.

**Comment by Crazylemon64** [comment]
Actually, it DOES kill them for a moment - it calls `death()`, but then it revives them immediately because they're above -100 health - if you're fast, you can ghost.

**Comment by Crazylemon64** [comment]
It should probably ghostize the user, too

**Comment by Tastyfish** [comment]
As it is, calling `dead()` outside the health processing code is already kinda a hack, I'll try to make a not-too slowflake way to fix this.
