### ISSUE TITLE
Table icons messing up

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#3544]
Not sure if anyone else has noticed but it would seem table icons are a little broken. When you have like-tables merge into a larger one it works, but you still see the normal single table underneath it. Just the icon, not the object.
![dased](https://cloud.githubusercontent.com/assets/1978025/12905181/a62cb52c-ce9a-11e5-8032-e20d7a7a2f82.PNG)
This is much more visible with glass tables as you see the single table under the merged one

**Comment by Fox-McCloud** [comment]
@Tastyfish

**Comment by Tastyfish** [comment]
I'll take a look.
