### ISSUE TITLE
MindSwap works on borgs

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#3546]
Wizard just did it this round, mindswapped into a Engiborg while he was getting beaten down.

**Comment by Fox-McCloud** [comment]
Wizards can mindswap with any living that has a mind+key in it.

Yes, that means a player controlled Renault, even.

**Comment by Tastyfish** [comment]
Being that it's magic by definition, I'm not sure if this is technically a bug.

**Comment by Regen1** [comment]
![Magic](https://33.media.tumblr.com/3a64409d22df4be1379ed2f82b4a8640/tumblr_inline_mjkz0wyGEJ1qclt3z.jpg)

**Comment by Earthdivine** [comment]
Request "working as intended" tag then, I dunno if I should close this or not so other people don't post this again.
