### ISSUE TITLE
Using admingib on someone causes issues.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#3561]
Perhaps related to https://github.com/ParadiseSS13/Paradise/issues/3401
I only did this with an IPC character, so it might just be an IPC issue. It might also be a general issue.
While testing mob capsules, I used the admin gib command on myself before closing the server, and found that I was the ghost-brain mob, only... well, not a ghost. The posibrain was still there, as well.

**Comment by Crazylemon64** [comment]
If you ghost from a positronic brain, you'll show up as a brainmob. Is this behavior what you refer to? You were still able to travel through walls and all, yes? Or did you not even actively ghost?

**Comment by Spacemanspark** [comment]
I didn't even ghost. I wasn't able to move around at all.
I think I was able to talk, though.

**Comment by Crazylemon64** [comment]
I think there's an unneeded `ghostize` tossed in there for some reason

**Comment by Spacemanspark** [comment]
This likely doesn't happen still. Closing.
