### ISSUE TITLE
IDs, pocket items, PDAs cannot be removed from golems

### ISSUE THREAD

**Issue by CupcakesNHacksaws** [ParadiseSS13/Paradise#3566]
It is impossible for others to remove these items off of golems, as they are coded as having an unremovable suit/exo-suit it would appear, as they are able to wear these items, but the items cannot be removed as they are "wearing" an unremovable adamantine shell.

**Comment by TheDZD** [comment]
Are the golems not able to take these off themselves?

**Comment by CupcakesNHacksaws** [comment]
They are, just not others. It shows up as obscured in the UI, as if someone was wearing outer clothing like a hardsuit or firesuit
