### ISSUE TITLE
You can trick plastic bags into suffocating you when they shouldn't be able to

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3577]
Put a plastic bag on your head, drag it off of your head, and press "E" quickly - this will cause you to suffocate without a plastic bag on your head.

**Comment by Gummin** [comment]
Interesting.

**Comment by VampyrBytes** [comment]
@Crazylemon64 I can't reproduce this, mainly because I can't click it off my head. When I try it opens the inaccessible inventory window for the plastic bag, it doesn't remove it. Only way I could get it off my head was dragging it back to my hand, and using e to equip it then was fine.

**Comment by Crazylemon64** [comment]
Ah, yes, this is what I mean. And be fast about belt-equipping, or it'll update and reset the `head` variable
