### ISSUE TITLE
Slime people hair doesn't work well with dark body colors

### ISSUE THREAD

**Issue by marlyn-x86** [ParadiseSS13/Paradise#3581]
Example:
![ooooops](https://cloud.githubusercontent.com/assets/5661700/13006280/b5477f66-d13c-11e5-861b-9f2edb0cb5d7.jpg)
A slime person who looks like frankenstein because of my slime hair changes.

Proposed fix: Allow slime people to fine-tune their hair color, so they can choose a particular hair color to get around this. Sound good?

**Comment by Gummin** [comment]
:+1: Inability to have separate hair color is silly in my opinion.

**Comment by DGamerL** [comment]
Heya, as of now slimepeople can change their own hair colour, making it look a lot better! This issue was fixed in #3441, which was funnily enough your own PR!
