### ISSUE TITLE
Ghosts can create dirt overlays on floor tiles.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#3586]
http://imgur.com/gpRmpgL

In that screenshot, just above my voxxy ghost, are three lockers - an oxy locker flanked by two unmarked ones.  You can see that the floor tiles behind them have the dirt overlay from someone walking on those spaces repeatedly, but they were clear when I got there and I spent a good 10 minutes walking back and forth to test whether or not ghosts could trigger the dirt overlay.  (I was bored waiting for a Nations round to end, okay?!)  Nobody else walked over those tiles in the time that I was testing this and I was a ghost the whole time.

This isn't a huge deal - ghosts affect the round more just by using the 'Boo!' spell, but it doesn't seem like it was an intentional thing so I thought I'd post about it here just in case.

**Comment by FalseIncarnate** [comment]
The dirt overlay, while a nice aesthetic touch, is honestly such a pain. It's hard to see on darker floors and effectively renders the super clean station bonus impossible to achieve for even the most dedicated janitors.

Apparently we can thank ghosts for that now.

**Comment by Fox-McCloud** [comment]
fixed
