### ISSUE TITLE
Labcoat pockets accessible from a distance.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#3588]
http://imgur.com/Md6LEMv

Note where I'm standing, by the monkey recycler.  And the labcoat is on the table.  I had previously had the labcoat in my backpack (had to remove it to wear the sweet wizard robes, you know?) and my slime analyzer was in the labcoat so I opened up the pockets, snagged the analyzer, stuck it in my backpack, and threw the labcoat onto the table.  When I picked up some monkey cubes from the monkey recycler and hit "e" to put them in my backpack they went into the labcoat pockets instead despite it being more than 1 space away.

I was able to reproduce this effect by taking the labcoat in my hand, emptying the pockets, keeping the pocket slots open by my equipment menu, throwing the labcoat, and then grabbing monkey cubes and using them with "e" again.  I'm certain this is not an effect form a genetic power (I had none) or the spell I learned (Ethereal Jaunt).

**Comment by Gummin** [comment]
It seems bugs like these are becoming a trend.

**Comment by Ar3nn** [comment]
I kept noticing this as a miner, I'd always swap out my industrial backpack for a satchel, because cool kids use satchels, and I'd end up leaving half my equipment in that backpack on the floor.

**Comment by Gummin** [comment]
@Ar3nn _just want to make sure you know you can spawn with a satchel_

**Comment by Ar3nn** [comment]
I thought that spawned you with the normal leather satchel. I'll have to look into that.

**Comment by KasparoVy** [comment]
Selecting satchel spawns you with a satchel appropriate to your department, selecting alt satchel spawns you with a leather one.

**Comment by alex-gh** [comment]
Bug seems to be purely visual right now. I was able to see the pockets after throwing the labcoat, but not interact with them.

Also making even a single step closed the inventory.

**Comment by Will-Bohlen** [comment]
Bug still present.

Empty labcoat, far away:
![image](https://user-images.githubusercontent.com/15622691/175865533-4d7d1d80-1d96-4b0b-b495-e0d1b8d1b656.png)

You can still insert items, but can't take them back out:
![image](https://user-images.githubusercontent.com/15622691/175865558-9eaf75c2-3d48-4303-9cc7-6f7f49046232.png)

Moving closes the UI.

**Comment by Sirryan2002** [comment]
Confirmed still an issue
