### ISSUE TITLE
Janitors are OP

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#3589]
Water (and mopping with water) will still slip you even while WALKING its not supposed to slip while WALKING. and its almost lube worthy slips.

**Comment by Tastyfish** [comment]
#3545

**Comment by VampyrBytes** [comment]
Sorry, my f*** up. Fix will be up soon

**Comment by KasparoVy** [comment]
water OPAF

**Comment by CrAzYPiLoT-SS13** [comment]
Remove water when?

**Comment by Robertha89** [comment]
bless the janitors water, and it will be no slip
