### ISSUE TITLE
If your summoner gets polymorphed, you, as a guardian, get to cry.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#3590]
Basically, it boots you out, but leaves your mob there. You can jump back into it, but it'll boot you out again with the message "You somehow lack a summoner, and disperse!".
You can infinitely do this, although it's irritating as fuck.
@Aurorablade

**Comment by KasparoVy** [comment]
rip

Should probably follow the mind of the player rather than the body so appearance is irrelevant-- but if they DO die, it triggers your dispersion as well or whatever the default handling for that is

**Comment by Crazylemon64** [comment]
Infinitely? The "Disperse" message SHOULD outright kill you... You could jump back to what, exactly?

**Comment by Spacemanspark** [comment]
It doesn't kill you, it just ghosts you every time you re-enter the mob after about 2-3 seconds.
You can jump back into the mob with the "re-enter corpse" button.

**Comment by Crazylemon64** [comment]
Oh. It SHOULD say, that "You have no body" - I must've fluffed something up regarding body deletion and all. I'll take a peek into ghostcode, then.

**Comment by Crazylemon64** [comment]
@Spacemanspark It looks like the same issue will come up if the summoner outright dies, too - the death logic appears to be the same. For some reason, your mind.current variable isn't being nil`d... I'd need to take a look at runtime to see what exactly is preventing things from going smoothly.

**Comment by Spacemanspark** [comment]
Has this been fixed?

**Comment by Spacemanspark** [comment]
Bumping again, curious.

**Comment by Spacemanspark** [comment]
Honk.

**Comment by Spacemanspark** [comment]
M O R T A L S, I C R A V E K N O W L E D G E

**Comment by Henri215** [comment]
Has this been fixed? (Thank me later Timmy)

**Comment by DGamerL** [comment]
Heya Timmy's and other people who are definitely not Timmy, luckily somehow this issue has been fixed over the past few years, causing many holoparas to rejoice! If it somehow happens again, feel free to open a new issue report!
