### ISSUE TITLE
Aim mode reticle screws up simple_animal sprites with a permanent reticle.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#3591]
Can we get rid of aim bot mode already?

**Comment by Gummin** [comment]
I'm pretty certain some form of this bug has been around for years.
Although I'm not sure if we should just scrap "aim bot mode" altogether or just fix whatever's causing this.

**Comment by Spacemanspark** [comment]
IS IT GONE?!

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Aim mode has been dead for a couple of weeks now.

**Comment by Spacemanspark** [comment]
...Oh duh, that HUD PR that Tiger did.
Still working on finals...
