### ISSUE TITLE
Selecting no backpack causes you to lose some starting items

### ISSUE THREAD

**Issue by Bailol** [ParadiseSS13/Paradise#3593]
As a detective, I spawned in with the 'nothing' backpack selected just to see what it would do. When I spawned, it gave me all of my normal detective equipment and a plastic bag with the spawn box inside of it but my telescopic baton was missing.

**Comment by Gummin** [comment]
Why is no backpack even an option?

**Comment by Fox-McCloud** [comment]
@Gummin 

For nerds =p

**Comment by Spacemanspark** [comment]
@Gummin 
Why not?

**Comment by Fox-McCloud** [comment]
All I can say is, this isn't really a bug; spawning in with a backpack means that you're trying to put nothing into nothing.

There's a backup for this, but that can only hold so many items (and is a work around, to be frank); if you intentionally select no backpack, then not getting all your equipment is largely on you.
