### ISSUE TITLE
Lexorin Jelly blobs cause cyborgs to take oxygen damage

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#3595]
not sure of the exact cause but a cyborg had gotten 40 oxygen damage while fighting a lexorin jelly blob

**Comment by Gummin** [comment]
I think straight up removing oxygen damage & toxin damage from Cyborgs completely should be a thing. Although I'm not sure what repercussions this could have (if any).

**Comment by Crazylemon64** [comment]
@Gummin It would prevent suicide from working on them... Otherwise, nothing else
