### ISSUE TITLE
Drones can move around and see at 0 charge

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#3607]
Can't hear or interact with things, but movement seems to be just fine with no charge. Not sure if this is intentional, but it does make being a drone really nice in terms of recharging.

**Comment by TheDZD** [comment]
Not a bug, apparently borgs can move around at zero charge, they just can't interact with things.

**Comment by Fox-McCloud** [comment]
@TheDZD 

What's odd about this is that when this was submitted, borgs definitely couldn't move around at 0 charge--dunno why drones got an exception to this.

**Comment by Spacemanspark** [comment]
Perhaps best to leave it. Drones aren't allowed to interact with the crew, and people will always ignore dead drones regardless.
