### ISSUE TITLE
Admin Brew can be summoned by silver slime cores.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3615]
This contains adminodrazine. I, at first, supported it staying, but hearing the actual effects, it really should be blacklisted.

**Comment by Robertha89** [comment]
Eh, i see no reason too, you already got this effect with a hivelord remain. But unlike hivelords, this is rng based.

**Comment by tigercat2000** [comment]
Fucking christ adminordrazine is **not** for players @Robertha89 

Problem is here: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/oldchem/chemical_reaction/chemical_reaction_slime.dm#L177
Blindly spawns subtypes of `/obj/item/weapon/reagent_containers/food/drinks`

**Comment by TheDZD** [comment]
[Related] (https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/reagent_containers/food/snacks.dm#L927).

**Comment by NTSAM** [comment]
Isn't that an adminbus item though? I mean the big variant of the roboburger.

**Comment by TheDZD** [comment]
The slime food reaction blindly spawns food, so it will spawn those as well. And those have nanites (the one that's basically just reskinned adminodrazine).

**Comment by NTSAM** [comment]
Oh. Sorry.

**Comment by Gummin** [comment]
@tigercat2000 Adminordrazine also spawns in the scrubbers backpressure event, definitely not as bad as this though. _thought I'd mention this_
