### ISSUE TITLE
I somehow managed to pick up a shuttle hatch tile.

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#3621]
http://puu.sh/n9MXT/ef0dd2b3ae.png

Shortly after, I dropped it as a test. It duplicated the shuttle tile.

To add, I haven't been able to reproduce this in a single round. Did I break something? I remember getting up after being lubed, then picking it up.

**Comment by monster860** [comment]
I suspect adminbus.

**Comment by Tastyfish** [comment]
Since it's impossible to pick up an /obj/machinery, probably safe to say this isn't reproducable.

**Comment by monster860** [comment]
Its probably a byond cache thing

**Comment by Magikarpet** [comment]
Not sure if it's a local cache issue, because as I said, when I dropped the tile it was placed on the ground as a new shuttle hatch.
