### ISSUE TITLE
Duplicate Menu on Getmore Chocolate machine

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#3623]
The Getmore Chocolate machine in Science displays a duplicate menu. If this actually is a bug, I assume all Getmore machines do this, but I play an IPC, so I only saw this one time by accident and I keep forgetting to look again since I have no need to.
![2016-02-14 18_06_26](https://cloud.githubusercontent.com/assets/16659022/13096321/971f9ef8-d4e6-11e5-8677-708608276252.png)

**Comment by NTSAM** [comment]
ClothesVends do this when you do that refill glitch thing - Can it be done on Soda machines too?

**Comment by Gummin** [comment]
@NTSAM 

> refill glitch thing

Could you elaborate?

**Comment by NTSAM** [comment]
That thing with the screwdriver and the crowbar.

**Comment by Gummin** [comment]
@NTSAM you mean refilling the machine? lol

**Comment by Gummin** [comment]
I didn't actually pay attention to the issue..
I've seen this before a couple years ago. Has it been fixed before? Or did it just magically go away?

**Comment by FalseIncarnate** [comment]
This has been a thing for a while, where rebuilding a machine will end up causing duplicate item listings. Granted, the machine restocking stuff itself is pretty poorly handled, so it probably would benefit from that being cleaned up in the process.

**Comment by Gummin** [comment]
That was it! Hm..
Yeah reworking of how this works would be great.

**Comment by FalseIncarnate** [comment]
Fixed by #3749 but never closed

**Comment by Tastyfish** [comment]
oops
