### ISSUE TITLE
Morphs can be attacked with the speed of Sanic.

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#3625]
Attack delay on morphs in borked and they can be attacked as fast as the attacker can click.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/simple_animal.dm#L417>Oooooops</a>, my bad

One problem I'm having, though, is how to let items attack something, while maintaining proper attack delays. Thoughts?

**Comment by Tastyfish** [comment]
@Crazylemon64 Try putting the `user.changeNext_move(CLICK_CD_MELEE)` before the O.attack() call; a weapon would usually return 1 on a successful hit I believe, so this extra code is never being called. Regardless, the changeNext_move should be called regardless of a successful hit or not on an attempted attack. eg:
```dm
else
    user.changeNext_move(CLICK_CD_MELEE)
    if(istype(O) && istype(user) && !O.attack(src, user))
        user.do_attack_animation(src)
         ....
```

**Comment by Gummin** [comment]
Well knowing that makes them 10x less intimidating.
