### ISSUE TITLE
Mechs, pods and the like, take damage from tasers and disablers

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3628]
title

**Comment by Robertha89** [comment]
Actually, mechs don't take 'damage' but it consumes power, and breaks things equipped, also causing various internal failures, like over pressure, requiring to recalibrate etc.
And the spacepod was almost blown like 3 times by a borg with a disabler, so that was... odd.

**Comment by NTSAM** [comment]
imo tasers should lock mechs down for a moment like an overload deal but breaking a pod with disablers and nuking a mech with balls of nonlethal energy is kinda butt.

**Comment by Robertha89** [comment]
locking mechs down with non-lethals seems silly, remember it moved via hydralics.

**Comment by NTSAM** [comment]
should at least tempdisable the electronic-y equipment for like 10 seconds so sec officers aren't always "lol dead" when trapped in a corner and facing a drillmech

**Comment by Robertha89** [comment]
well, yeah, you are also lol dead if you are facing any other mech with lethals.

**Comment by NTSAM** [comment]
tru

**Comment by Spacemanspark** [comment]
Oh, huh.
I noticed that disabler beams could destroy vehicles (The cars, motorcycle, etc.) a long while back. Perhaps related?

**Comment by TheDZD** [comment]
@Fox-McCloud Sounds like they don't have handling for stamina damage, kind of like what happened with simple_animal when stamina damage was added.

**Comment by Davdichan** [comment]
Making it just reduce power by so many watts would be nice, instead of blowing shit up. As for disablers damaging mech equipment... that actually seems really dumb. It's a disabler beam, not a mini-ion burst.

**Comment by Vivalas** [comment]
Really don't think tazers should affect mechs at all, seems like a really big nerf for mechs, a traitor has to go through a decent amount of work to obtain one. This would make the ion rifle even less used.
