### ISSUE TITLE
Wizard lair has RD bedsheet instead of the glorious wizman bedsheet.

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#3642]
This is a gamebreaking issue and shameful for all wiznerd kind.

Acceptable     [  ]
Unacceptable [x]

**Comment by Gummin** [comment]
Wow, this game is literally in an unplayable state until this issue is dealt with. :-1:x:100:

**Comment by NTSAM** [comment]
My fucking immersion is ruined
ruined
ruined
ruined
ruined
:cry:
