### ISSUE TITLE
Bug Report- Genetic's disks info changed when outside terminal

### ISSUE THREAD

**Issue by Radithor** [ParadiseSS13/Paradise#3657]
All saved buffers and buffers saved to the disks were completely changed even when the disks were out of the machine, I could not save a clean SE anywhere and basically had to take the long route to removing genetic damage. I think the buffers and disks in genetics are bugged.

**Comment by Gummin** [comment]
Thank you for reporting this.
I literally accidentally kept this in my basement for months.
This bug makes genetics **actually** literally unplayable.

**Comment by Crazylemon64** [comment]
Probably some DNA transfer code that fails to do DNA.copy().
