### ISSUE TITLE
Gas Turbine Breaks with Tier 4 Components

### ISSUE THREAD

**Issue by FalseIncarnate** [ParadiseSS13/Paradise#3661]
When upgraded with a full set of Tier 4 component parts, the gas turbine engine fails to produce power at all, due to registering 0 rpm.

When messing with the efficiency var on the compressor (the var adjusted by the upgrades), the computer fails to register a non-zero value for rpm at efficiency values greater than 3.7, with some odd fluctuation of rpm trending on the lower end at values greater than 3.0 up to the point where it just registers a flat zero rpm.

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/issues/2746 duplicate.

**Comment by FalseIncarnate** [comment]
Ah, I knew this sounded familiar but was too hasty and didn't do a search. Let that be a lesson, kids.
