### ISSUE TITLE
Exosuit console logs don't show

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3662]
**Problem Description**:
Exosuit Console logs don't show

**What did you expect to happen**: 
It should show the history of actions taken and done to the mecha

**What happened instead**:
Instead, it fails to load correctly, and doesn't re-render if you use the console again.

**Why is this bad/What are the consequences:**
Without this, you can't use the exosuit tracking console for tracking exosuits effectively.

**Comment by variableundefined** [comment]
Seems to work now?
(Tested on local server)
![](https://i.imgur.com/rfoauwf.png)
