### ISSUE TITLE
Damage to feet is not showing up on the health doll.

### ISSUE THREAD

**Issue by eljacko1** [ParadiseSS13/Paradise#3666]
**Problem Description**:
The health doll seems to not show damage to feet, at least not when i'm an IPC which i usually am.

**What did you expect to happen**: 
I expected the doll to turn yellow in the area that is affected

**What happened instead**:
The doll stayed green, even when damage was clearly present
**Why is this bad/What are the consequences:**
It's not really an important issue but i thought i'd point it out as i've noticed it happening for a while now.

**Steps to reproduce the problem**:
Well, i purposefully made my feet damaged, and i was wearing a Heath Scanner HuD which showed the damage. I then clicked on myself and it showed a check, and the feet were damaged, yet the doll stayed green. (this is what will be in the screenshot) Though it shows up after it's damaged to an orange level...so i am unsure if this is a bug or not.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not really much to say here, i've noticed it for a while but thought it could be intentional...but i thought i'd make a report just in case it is indeed a bug that has been overlooked.
![image](https://cloud.githubusercontent.com/assets/17344258/13204346/aa5f7f96-d8c5-11e5-9bb6-a6dbbf1538ad.png)

**Comment by NTSAM** [comment]
I thought someone already reported this?

**Comment by VampyrBytes** [comment]
I'm no good at spriting, so I'll leave the actual fix to someone who knows what they're doing, but the cause of this is that screen_gen.dmi is missing l_foot1 and r_foot1
