### ISSUE TITLE
CPR Failures

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#3669]
**Problem Description**:
Performing CPR on a person below 150 total damage either fails consistently, or works once and never again.
The case where it only works once goes like this: You CPR a guy, it works and gives you the 'perform every 7 seconds' message, yet you can never do it again. Every time you try, it just shakes the person instead-- despite them still being dead.

This does not happen 100% of the time however, as there is the very rare occasion where performing CPR works as intended. Though, I can only remember it working once.

**What did you expect to happen**: 
I expected to be able to perform CPR on a deceased patient again after the first attempt in order to try and prolong their life/resuscitate them.

**What happened instead**:
It worked on the first attempt, and every other attempt just 'shook' them attempting to wake them up, despite their being dead.
Furthermore, on another deceased player below 150 total damage and not decayed, it didn't work period-- not once out of 8 consecutive attempts.

**Why is this bad/What are the consequences:**
Invalidates CPR. It meant there was absolutely no way I could help a particular player.

**Steps to reproduce the problem**:
Attempt CPR on a player who hasn't decayed and is below 150 (could be 200, not sure)  total damage.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a wizard round, and the person was killed by a tesla. I had used 5 burn patches to get their burn damage below 100, and they only had 19 suffocation damage. I proceeded to do CPR-- it succeeded on the first attempt, and every other attempt following just shook them attempting to wake them up, though they were dead, still below 150 total damage, and not decayed.

**Comment by VampyrBytes** [comment]
This is working as intended. The relevant line in the code is 
`if(health > config.health_threshold_dead && health <= config.health_threshold_crit)`
so you're not meant to be able to use it on dead people or people whose damage is below the crit level.
When you're in crit you don't breathe, and so are taking oxyloss damage. CPR's only job is to counter this... all it does is remove oxyloss damage, which if you're already dead isn't much use, and if it worked when you're not in crit would make it a cureall for oxyloss
