### ISSUE TITLE
"On" welding tools fit in pockets

### ISSUE THREAD

**Issue by NTSAM** [ParadiseSS13/Paradise#3691]
**Problem Description**:
Some time ago, welders that are turned on wouldn't fit in pockets. Now, they do fit.

**What did you expect to happen**: 
The welding tool to not fit in the pocket when on.

**What happened instead**:
it did

**Why is this bad/What are the consequences:**
People can shove really hot industrial tools in their pockets.

**Steps to reproduce the problem**:
1) Turn on welder.
2) Click pocket slot.
3) Notice you're missing the skin on your entire lower region because you left a superhot flame in your pocket.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
m-muh precious welder fuel ;-;

**Comment by Fox-McCloud** [comment]
Not a bug; welding tools were changed several times, and this got changed back a veryyy long time ago. It's certainly not a bug.

**Comment by NTSAM** [comment]
oh
