### ISSUE TITLE
The "Reply" link in the chat window for PDA messages is broken

### ISSUE THREAD

**Issue by alexpkeaton** [ParadiseSS13/Paradise#3697]
**Problem Description**:
The "Reply" link to PDA messages in the chat window no longer works.

**What did you expect to happen**: 
An input box to enter a reply to appear.

**What happened instead**:
Clicking the link does nothing. No entry box appears.

**Why is this bad/What are the consequences:**
Now you have to pull out the PDA, navigate to the message and reply on the PDA.

**Steps to reproduce the problem**:
Receive a PDA message from someone else. When the message appears in the chat window, click "Reply."  I asked mentors on at the time to attempt to reproduce this, and I received a reply from one that they, too, had noticed this issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Using a Captain's PDA (not sure if that matters as I think it's just a recolor and a different cart, but on a related note, I could not remove my pen from my PDA but others reported they could, so I guess I might have missed something or that other issue is limited to Captain's PDA). This occurred with PDA messages from more than one individual.  As mentioned above, a mentor also noticed this issue.

EDIT: I should add that "I could not remove my pen" should be "received a message saying 'there is no pen loaded in the PDA'"

**Comment by Kerroman** [comment]
The first time I got a PDA message I couldn't reply using the "Reply" link in the text window.  I opened the PDA and replied through there, and then on subsequent messages I received I was able to use the "Reply" link just fine.  It might have something to do with the initial message received not being able to load the reply input box properly.

It really reminds me of the ChemMaster input lag when you first use them on any given round.

**Comment by Fox-McCloud** [comment]
@Tastyfish

**Comment by Tastyfish** [comment]
I'll look at it

**Comment by Tastyfish** [comment]
I could not reproduce the issue you had with pens, although the main issue was definitely an oversight/typo on my part.
