### ISSUE TITLE
Coronor's labcoat has bugged Open/Close jacket command

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#3703]
**Problem Description**:
When using the Open/Close Jacket command from the object tab the coronor's labcoat changes to a weird sprite and becomes impossible to take off, but you can change it back to the original sprite by using the command again.

**What did you expect to happen**: 
The labcoat should've opened and Closed.

**What happened instead**:
The labcoat changed to a weird sprite and became impossible to take off.

**Why is this bad/What are the consequences:**
Looks ugly

**Steps to reproduce the problem**:
Use the Open/Close jacket command on the coronor's labcoat

![coronor s labcoat bug](https://cloud.githubusercontent.com/assets/11246791/13324687/0fa207b8-dbdf-11e5-980c-c2ceb4508f77.gif)

**Comment by FlattestGuitar** [comment]
Too lazy to check, but this might actually fix this - [#3693](https://github.com/ParadiseSS13/Paradise/pull/3693)
