### ISSUE TITLE
Can't point while on janicart

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#3704]
**Problem Description**:
You can't use middle-click to point to things when riding the janicart.

**What did you expect to happen**: 
I expected to be able to point to things while riding the pussy wagon.

**What happened instead**:
I could not point. Had to step off the cart to point.

**Why is this bad/What are the consequences:**
Pointing is fairly useful for a myriad of reasons. A situation where the player is fully conscious, healthy, and in control of themselves but cannot point is undesirable.

**Steps to reproduce the problem**:
1) Step onto a janicart.
2) Try to point.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing else.

**Comment by kylejen** [comment]
IIRC you also aren't able to open doors (meaning you have to click on them) while on the janicart as well, unless that was fixed.

**Comment by Fox-McCloud** [comment]
It's because you're buckled to it; you can't point while buckled to a chair, either.

This isn't a bug.

**Comment by ProperPants** [comment]
@Fox-McCloud Please do. Since it was already mentioned, if you could also do something about not being able to open doors, that'd be fantastic.

**Comment by Fox-McCloud** [comment]
@ProperPants 

That's a whole other can of worms that I likely won't be touching any time soon.
