### ISSUE TITLE
Binary Talk not working with keys

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3710]
**Problem Description**:
When utilizing the binary encryption key, you can understand binary, but uitlized ":b" to speak it does nothing.

**What did you expect to happen**: 
The key states you can speak and listen to binary with the key--this is also how it functions on TG.

**What happened instead**:
I should be able to speak binary; can't--only listen.

**Why is this bad/What are the consequences:**
MAI BINARIES. Also negatively impacts traitors A LOT.

**Steps to reproduce the problem**:
Try to speak with binary on a headset with a binary key.

**Comment by Tastyfish** [comment]
This is actually an issue of the description/implementation; the binary and hivemind channels are done through a headset using the "special" channel, which is :+, ie you'd do
`say ":+Hello, AI!`

**Comment by Fox-McCloud** [comment]
@Tastyfish 

well, that's awkward! Didn't know that--I noticed the special flag, but couldn't immediately hunt down something that could trigger it (granted, I was in the middle of a round too, though, soooo). Thanks.

**Comment by Tastyfish** [comment]
@Fox-McCloud It's directly implemented in the headset type, hard and awkward to find. I actually didn't know how until I looked through the encryption key/headset code due to this issue.

**Comment by Ar3nn** [comment]
Binary keys worked fine before when they were science toys. What changed?

**Comment by Fox-McCloud** [comment]
@Ar3nn 

Saycode.
