### ISSUE TITLE
Capulettium Plus doesnt mute

### ISSUE THREAD

**Issue by jjamac** [ParadiseSS13/Paradise#3713]
**Problem Description**:
What is the problem?

When used on a person it doesnt mute

**What did you expect to happen**: 
Why do you think this is a bug?

I made some and ate a 30u pill and then ate a 50u pill and it did stop my pulse it did not mute me and according to the wiki it is suppose to silence people

**What happened instead**:
How is what happened different from what you expected?

It stopped my pulse which was expected but it did not mute me as i was talking constantly with it in my system

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It isnt much of a important issue pretty much a very minor one so it can be ignored

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

I tried this multiple times. Injection myself and took pills. It did not mute me
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by TheDZD** [comment]
@Fox-McCloud
