### ISSUE TITLE
You can't bash windows with peoples head

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3719]
**Problem Description**:
Throwing people into reinforced windows does not break them.

**What did you expect to happen**: 
For the windows to break

**What happened instead**:
They did not break

**Why is this bad/What are the consequences:**
Breaking windows with another persons skull is a time honored ss13 tradition, and has been broken for a while, it is one of the certain ways to break a window without tools, which is needed from time to time to escape various rooms and whatnot.

**Steps to reproduce the problem**:
Grab a person untill you can throw the person, throw person untill window breaks, which it does not

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Nay.

**Comment by NTSAM** [comment]
You can break windows with people's heads by aggressively grabbing them and hitting the window 2-4 times.

**Comment by TheDZD** [comment]
Feature requests like this go on the forums.
