### ISSUE TITLE
Prize Counter doesn't spend tickets.

### ISSUE THREAD

**Issue by Dumbdumn5** [ParadiseSS13/Paradise#3720]
Prize machine seems to just have the same exact amount of tickets in it after buying something, meaning you can funnel enough in to buy the most expensive thing, and buy it endlessly. All hail toys!

**Comment by Gummin** [comment]
_Shh! Keep your voice down! You don't want the coders to hear us!_

**Comment by Dumbdumn5** [comment]
VIVA LA BUGFIXLUCION!

**Comment by Tastyfish** [comment]
@FalseIncarnate

**Comment by Spacemanspark** [comment]
Dammit @Dumbdumn5.

**Comment by FalseIncarnate** [comment]
And despite this feature, I still am yet to hear of anyone getting the bike.

Kidding, mistake on my part, definitely a bug, will fix in morning
