### ISSUE TITLE
Synthetic *yes emote needs an extra S to work.

### ISSUE THREAD

**Issue by eljacko1** [ParadiseSS13/Paradise#3727]
**Problem Description**:
Synthetic's *yes command only works when putting *yess

**What did you expect to happen**: 
the emote to display when i put in *yes

**What happened instead**:
instead i got an error saying the emote *ye is unavaliable. I did this several times to check if i had misspelled it, and i hadn't.

**Why is this bad/What are the consequences:**
It's not important persay, just annoying since the emote can only be used when an extra S is used.

**Steps to reproduce the problem**:
I typed in the emote of *yes, and it didn't work (giving the error i mentioned  earlier) then i added the extra 's' and it worked fine.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing else really to say. I haven't found anything else on this issue, so if it's a duplicate then i apologize in advance. Here is a screenshot of the issue:
![image](https://cloud.githubusercontent.com/assets/17344258/13373801/4e2f6d28-dd69-11e5-8b7a-c42bba27d0c8.png)
and of the 'solution' i found
![image](https://cloud.githubusercontent.com/assets/17344258/13373804/5aaf4bf4-dd69-11e5-94e2-cefd3a9e5f10.png)

**Comment by tigercat2000** [comment]
Happens with every emote, the last S is stripped off for no reason.

**Comment by NTSAM** [comment]
@Spacemanspark said something about it being an issue with BYOND i think

**Comment by eljacko1** [comment]
ah. if that's the case i may close this...issue i guess.

**Comment by tigercat2000** [comment]
nah, leave it open, it's still a problem, we'll just need to contact byond eventually

**Comment by CrAzYPiLoT-SS13** [comment]
I know it's a shitty solution but, why just not make every emote ending in
S, just not end in it? E.g *yes becomes *ye, etc  Ya know, just for the
time being?

**Comment by eljacko1** [comment]
True, okay i'll leave it. Someone will see it sooner or later

**Comment by KasparoVy** [comment]
undercover unathi coders man

**Comment by Crazylemon64** [comment]
This isn't a BYOND issue.
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/emote.dm#L12-L13>Here's the source of the problem</a>

**Comment by Spacemanspark** [comment]
...
Is that code even necessary?

**Comment by Crazylemon64** [comment]
say *wink(s)
say *flip(s)

It's so that you can have a trailing s for grammatical purposes, but it would do just fine without it

**Comment by tigercat2000** [comment]
oh right, i found that before
then apparently forgot about it
