### ISSUE TITLE
Prize Counter: Infinite Tickets

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3731]
**Problem Description**:
You are able to infinitely buy as many toys as you want without the ticket counter going down. 

**What did you expect to happen**: 
Why do you think this is a bug?
For the ticket counter amount to go down.

**What happened instead**:
How is what happened different from what you expected?
You are able to buy as many toys as you want, depending on how many tickets you put in.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
You are able to buy as many toys as you want, spam-worthy.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Earn tickets, stick into the prize machine, buy a prize, see that the ticket amount doesn't go down.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Normal round, really, nothing that would effect the prize machine.

**Comment by mrturkeytoe** [comment]
Damn you bug fixes! I was enjoying my infinite plushies!

**Comment by Spacemanspark** [comment]
Duplicate issue of https://github.com/ParadiseSS13/Paradise/issues/3720 and fixed by https://github.com/ParadiseSS13/Paradise/pull/3728

**Comment by FalseIncarnate** [comment]
As said, reported and fixed already, just not patched to live server.

Thanks regardless for reporting!

**Comment by kylejen** [comment]
Meh, whatevs. I tried. Shall I close it?

**Comment by FalseIncarnate** [comment]
I would, though I also could see leaving it open until patched just to avoid further reports.

Up to you / maintainers on that.
