### ISSUE TITLE
Fruit spawning doesn't work - spawns generic "Fruit"

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3737]
When spawned using the admin tools, a "potato" just yields an invisible fruit - there's likely some bad implementation there.

**Comment by Tastyfish** [comment]
The `/obj/item/weapon/reagent_containers/food/snacks/grown/potato` type appears to only exist by virtue of having attackby defined for it...

**Comment by VampyrBytes** [comment]
If you can hit it with a knife and get raw potato sticks, you don't need anything else to show that it's a potato! :wink:

**Comment by FalseIncarnate** [comment]
To be fair, spawn fruit does spawn fruit...

This actually is probably a left-over admin tool from pre-botany update, which drastically changed how botany products work. The whole thing probably needs updating, not just potatoes

**Comment by Crazylemon64** [comment]
It's the "game panel" that I got the potato from - it was defined because of a proc that attempted to use it, even though no such instance would exist.
