### ISSUE TITLE
Nettle cannot be put into a microwave

### ISSUE THREAD

**Issue by Tastyfish** [ParadiseSS13/Paradise#3739]
**Problem Description**:
Nettle leaves cannot be placed into microwaves.

**What did you expect to happen**: 
It would be inserted in order to make nettle soup.

**What happened instead**:
Attempting to insert it yields "You have no idea what you can cook with this the nettle."

**Why is this bad/What are the consequences:**
Nettle soup cannot be produced.

**Steps to reproduce the problem**:
1. Hold a nettle in hand.
2. Click a microwave.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
The microwave also already included the 10 water, 1 potato, and 1 egg.

**Comment by Crazylemon64** [comment]
This is the game panel-spawned nettle - as it is not a child of fruit, it won't work in the microwave.
