### ISSUE TITLE
AI Tracker broken

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#374]
Lately (The last day or two, in my experience), using the Track on Camera verb as an AI will, as normal, pull up a list of visible mobs. However, the list of mobs seems to skip over almost everything on the station z-level. I can only seem to track the monkeys on the research outpost, miners on the asteroid within sight of the mining base cameras, et cetera.

**Comment by Markolie** [comment]
Already been fixed in the last patch.
