### ISSUE TITLE
Can't open the law sets in the AI law manager

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3742]
**Problem Description**:
What is the problem?
Pressing the "Law sets" on the AI law manager as an admin doesn't do anything
**What did you expect to happen**: 
For it to open the law sets available
Why do you think this is a bug?
Because button not do what is supposeds of doings
**What happened instead**:
Absolute fuck all
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
I can't adminbus laws
Why do you think this is an important issue?
Because I want to adminbus laws
**Steps to reproduce the problem**:
1. Be admin
2. Press button
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
@tigercat2000 This might be because of the NanoUI rework? I got no idea

**Comment by Tastyfish** [comment]
How odd, I definitely used it on live yesterday. I wonder if a specific law is crashing it.
