### ISSUE TITLE
JUKEBOX SOUNDS

### ISSUE THREAD

**Issue by M3hillus** [ParadiseSS13/Paradise#3756]
**Problem Description**:
Jukebox does not respect volume setting in preferences tab

**What did you expect to happen**: 
Upon setting volume to not 25, such a 0, for there to be a reduced sound from the jukebox

**What happened instead**:
Jukebox music pauses if set to 0, and then reverts

**Why is this bad/What are the consequences:**
the jukebox at 25, if audio settings are set to hear more quiet sounds on in game, is gorram loud, chummer.

**Steps to reproduce the problem**:
Walk into the bar, turn on jukebox, go to preferences tab, try reduce volume.

**Comment by tigercat2000** [comment]
hasn't this been fixed five times

**Comment by Tastyfish** [comment]
The jukebox system is like a porcelain figurine at a rodeo.

**Comment by M3hillus** [comment]
>delete jukebox, literally cancer.

**Comment by CrAzYPiLoT-SS13** [comment]
I agree, the jukebox is shit.

**Comment by Spacemanspark** [comment]
I think the ability to turn the jukebox on or off was fixed, not the volume part.

**Comment by Tastyfish** [comment]
Specifically a volume of 0 doesn't work now for some reason, looks like. You can just hit Mute/Silence Streaming for the same effect though.

**Comment by TheDZD** [comment]
Spacepod code 2.0

**Comment by taukausanake** [comment]
There's also being a ghost or diona moving through pipes that I notice it keeps playing after I leave the area. Sometimes it stops but maybe a different issue

**Comment by Rumiluntti** [comment]
Just let it die and dump the feature back to hell where it belongs.
It clearly wants to die.

**Comment by Vivalas** [comment]
I didn't think the jukeboxes even worked. Whenever I use them no sound comes out.

**Comment by tigercat2000** [comment]
@Vivalas you need vlc installed in internet explorer

**Comment by tristan1333** [comment]
Delet this

**Comment by taukausanake** [comment]
Yeah, fixed by #5445
