### ISSUE TITLE
Noir Sunglasses do not need to be worn on the eyes to work

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#3764]
**Problem Description**:
What is the problem?
Noir Sunglasses desaturate the screen when carried, even if not worn
**What did you expect to happen**: 
Why do you think this is a bug?
Because the glasses are intended to remove colour when worn
**What happened instead**:
How is what happened different from what you expected?
The glasses were in my pocket, and still removed the clour
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because the Noir Sunglasses are not functioning as they are supposed to
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Put Noir Sunglasses in my pocket.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Everything's already detailed.

**Comment by Fox-McCloud** [comment]
Duplicate and already fixed--just not patched yet.
