### ISSUE TITLE
Random AI Power Loss

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#3771]
**Problem Description**:
Randomly lose power as an AI, totally blinding you and slowly leading to death by lack of power.

**What did you expect to happen**: 
Not to lose power for seemingly no reason.

**What happened instead**:
I lost power in the middle of normal activities, in a room with multiple AIs, and most of them were fine. I think from seven AIs, only two of us had this and we both died around the same time from slow power loss.

**Why is this bad/What are the consequences:**
Randomly becoming blinded and later dying as an AI is obviously an issue.

**Steps to reproduce the problem**:
I can't reproduce this. I've played AI twice in the last few days, one time by joining late and one time by being a posibrain. The last time I played AI before this was months ago, and I never had a problem then. The problem just happens and is then followed by several messages involving phrases such as "power loss", "routing to APC", and "APC connection established." At the end of these messages, an APC screen opens. I assume this screen is meant to be messed with so that you can fix your power issue, but the APC I connected to the most recent time had literally zero power, so I could not do anything.

**Comment by theColdflame** [comment]
Considering there were eight AIs in the room, it might have just been a case of there not being enough power in the APC to go around. I'm not certain though.

**Comment by Fox-McCloud** [comment]
>Considering there were eight AIs in the room, it might have just been a case of there not being enough power in the APC to go around. I'm not certain though. 

Or one screwed with it.

**Comment by Spacemanspark** [comment]
There was more than enough power, and the AIs weren't touching it either, I was one of them, and survived just fine.
Two of them suddenly started complaining they were losing power and then they BSOD'd a minute later.
We were all in the same room.

**Comment by hal9000PR** [comment]
too vague to reproduce.
