### ISSUE TITLE
PDA sec records often fail to function

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#3773]
**Problem Description**:
What is the problem?
A PDA equipped with a cartridge that enables sec records access often fails to work properly, often breaking or sticking on a page
**What did you expect to happen**: 
For the PDA version of sec records to function normally
Why do you think this is a bug?
Because sec records should work properly, even on a PDA
**What happened instead**:
How is what happened different from what you expected?
I was expecing the PDA version of sec records to function normally- instead, they often hang on a single page or get entirely replaced with red text stating 'General Records Lost!' and 'Security Records Lost!
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because PDA access of sec records should work, and currently doesn't
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Attempted to use the security records on a PDA- I'm not sure exactly what causes them not to function properly; they work normally around half the time, and fail to the other half.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I'm not sure if this is a problem on my end or not- I've not seen anybody else complain about it, but it seems like something that wouldn't effect just me.

**Comment by Tastyfish** [comment]
At the very least, if the person has a missing or invalid general record, it should knock you back to the person list, so something wrong is definitely happening if you're getting a General Records Lost message. I will look into it.
