### ISSUE TITLE
Xeno leap does not need to hit the target to cause a stun

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#3783]
**Problem Description**:
What is the problem?
The xeno hunter's leap ability does not actually have to connect to stun the target
**What did you expect to happen**: 
When the xenomorph missed its leap, the target would not be stunned
Why do you think this is a bug?
Because according to all known laws of physics, something should have to hit something else in order to knock it over
**What happened instead**:
The target was stunned and (perhaps most importantly) the xeno was not, as it didn't impact with the target to cause it to be stunned
How is what happened different from what you expected?
A missed leap should not stun the target
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because xenos are already OP as shit and having bugs in their favour doesn't help
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I'm not sure exactly what caused this- I think it was either lag or the trajectory of the leap; I believe the stun is coded as part of the attack rather than an effect of the xeno hitting the target, which causes this issue.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Traitor round with xeno random event. Server was not significantly lagging at the time. I'm not certain how to reproduce this, though.

**Comment by Spacemanspark** [comment]
Honestly, xenos just need a giant nerf. We shouldn't have ported /tg/ aliens.

**Comment by Fox-McCloud** [comment]
Pretty sure this has been fixed, especially with the riot shield changes and such.
