### ISSUE TITLE
pda scanning breaks pda

### ISSUE THREAD

**Issue by billbillson** [ParadiseSS13/Paradise#3785]
**Problem Description**:
What is the problem?
you can click a pda on a paper to scan it but the pda becomes blank and useless.
**What did you expect to happen**:  That the paper would be put on notes on my pda.
Why do you think this is a bug? because it breaks pda's.
**What happened instead**: My pda broke it became blank and reseting it did nothing.
How is what happened different from what you expected?  It broke my pda that is the diffrence.

**Why is this bad/What are the consequences:**broken pda's because of a missclick, wasting time,and not being able to keep electronic copies.
Why do you think this is an important issue? because it breaks a function of pda's  a item used at all times.

**Steps to reproduce the problem**: grab pda, grab paper, then click pda on paper, scream.
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. any round you click on a paper with pda it breaks it.

**Comment by Tastyfish** [comment]
I'm unable to reproduce the problem. Is anybody else experiencing this? Is it a specific paper in the world you're clicking?

**Comment by billbillson** [comment]
@Tastyfish it might be a viro issue that us where i first found this, with the viro mutation papers.

**Comment by Tastyfish** [comment]
I'll see if there's something weird about those papers.
