### ISSUE TITLE
Chargen Organs and reattaching

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#3792]
Mostly for my own benifit and keeping geting ideas

Cannot direct attach severed robotic limbs from chargen (you could do it via the limb attachment surgery i am sure just not out in the field directly) does not affect robotic fab created limbs (though i had to do it twice for it to work).

Unsure how to fix.

**Comment by Crazylemon64** [comment]
Isn't that normal, though? Robotic limb attachment, from using a corresponding cyborg limb, and limb reattachment, from using a humanoid limb, have always been two separate surgeries - the former for applications of prosthetics when a miner failed to handle the gibtonium properly, the latter for when your IPC buddy lost their hands to a shocked door again

**Comment by Aurorablade** [comment]
yeah but i dunno if we should have like you bishop cybernetics limbs reattachable fast or not...eh...will think on it.

**Comment by Aurorablade** [comment]
i am gonna leave this as is but i will make a comment on the wiki about it when i finish updateing.
