### ISSUE TITLE
Optics added to IPCs dissapear

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#3796]
**Problem Description**:
Optics added to IPC's disapear

**What did you expect to happen**: 
Optics to get properly added to the IPC allowing sight

**What happened instead**:
after inserting the organ it dissapears

**Why is this bad/What are the consequences:**
if an IPC loses its optics its blind for the rest of the round as its sight cant be restored via IC means

**Steps to reproduce the problem**:
Remove and IPC's optics and put them back in, try to remove them again with a multitool

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: was trying to add medical HUD implant at the time which failed

**Comment by monster860** [comment]
Actually, if you cut the head of with a saw, you can attach a mechfab robot head with 2 flashes, and that will do the trick.

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/robotics.dm#L421

Errrr
@Aurorablade

**Comment by Dumbdumn5** [comment]
Seems like IPCs can't take any implants either due to this.

**Comment by Spacemanspark** [comment]
Not sure about that @Dumbdumn5, as you merely hit the IPC with the implants, instead of inserting it and it disappearing.

**Comment by Dumbdumn5** [comment]
Geeze!

**Comment by joonasm** [comment]
@Spacemanspark are you doing the right surgery? you implant cybernetics with the organ manipulation surgery like they were new organs.
I never got an issue with hitting the IPC with the implant, i could implant brain implants into the head but they vanish after the step completes
There is also another issue with you having to implant the cybernetical implants to same place you would with organics which makes HUDs impossible to implant
