### ISSUE TITLE
Synthetic limb reattachement doesnt let you attach IPC heads

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#3797]
**Problem Description**:
Selecting Synthetic limb reattachement on head and trying to attach an IPC head will give you the message "They are missing that limb!"

**What did you expect to happen**: 
for the IPC head to be reattached

**What happened instead**:
The IPC head was not attached and could only be attached using organic limb attach surgery

**Why is this bad/What are the consequences:**
Having to use _organic_ surgery for a _synthetic_ part is very misleading

**Steps to reproduce the problem**:
remove an IPC head, use screwdiver on head and select synthetic limb reattachement surgery, try to use the head on the IPC

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/limb_reattach.dm#L43

@Aurorablade IPCs don't actually use that path, use a species check instead of path check

**Comment by Aurorablade** [comment]
you need to use limb attachment surgery for both organics and synthtics...only IPCS need less steps (all you have to do is attach the part). I will eventually need to redo a check for direct attachment but for right now i am sorry for the inconvenience.

**Comment by DesolateG** [comment]
https://gph.is/2znJOBJ

This is no longer an issue.
