### ISSUE TITLE
Injecting someone with a syringe starts an operation

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#3807]
**Problem Description**:
Upon trying to inject someone on an operating table with a syringe the operation prepareation menu pops up.

**What did you expect to happen**: 
I didn't want to prepare for an operation.

**What happened instead**:
I had the operation preparation menu pop up.

**Why is this bad/What are the consequences:**
It's messy, unnecessary and makes surgeon work even harder.

**Steps to reproduce the problem**:
Have a person on a table or a surgery table, try to inject them with a syringe, the menu will pop up.

**Comment by TheDZD** [comment]
@Aurorablade
