### ISSUE TITLE
Nanopaste Not Working

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3810]
@Aurorablade 

**Problem Description**:
Nanopaste does not fix Assisted/Robotic Organs. Trauma Kits do.

**What did you expect to happen**: 
I expected Nanopaste do repair those things.

**What happened instead**:
Trauma Kit fixed it, Nanopaste didn't. Assisted Organs don't even get healed at all (see my other report).

**Why is this bad/What are the consequences:**
Well, Nanopaste is useless now, and Robotic Organs can be fixed with what amounts to bioglue.

**Comment by tigercat2000** [comment]
duplicate of #3799
