### ISSUE TITLE
Cloaked space ninja shows HUDs while invisible

### ISSUE THREAD

**Issue by marlyn-x86** [ParadiseSS13/Paradise#3820]
As per title - Med and Sec huds will show their existence, even when they should be nigh-unperceivable

**Comment by Fox-McCloud** [comment]
Guessing this is because the cloaking is handled in a really shitty way. Does this happen with the chameleon mutation, or any other form of invisibility (Vampire cloak, cloak of darkness, etc)?

If this is only the ninja suit, then it's most likely the cloak handling being....poor.

**Comment by Tastyfish** [comment]
Both vampire cloaking and the chameleon mutation work by setting the person's alpha directly, I would guess the other spells do similar.

**Comment by Fox-McCloud** [comment]
I'm guessing this is also Bay's ninja suit and not the one Dave's working on.

**Comment by Crazylemon64** [comment]
Yeah, the ninja RIG suit

**Comment by Kyep** [comment]
@AffectedArc07 RIG suits were removed, I think, and this can be closed.

**Comment by AffectedArc07** [comment]
```dm
/obj/item/clothing/suit/space/space_ninja
	name = "ninja suit"
	desc = "A unique, vaccum-proof suit of nano-enhanced armor designed specifically for Spider Clan assassins."
	icon_state = "s-ninja"
	item_state = "s-ninja_suit"
	allowed = list(/obj/item/gun, /obj/item/ammo_box, /obj/item/melee/baton, /obj/item/tank, /obj/item/stock_parts/cell)
	slowdown = 0
	armor = list("melee" = 60, "bullet" = 50, "laser" = 30,"energy" = 15, "bomb" = 30, "bio" = 30, "rad" = 30, "fire" = 100, "acid" = 100)

	var/suitActive = 0
	var/suitBusy = 0

```

This is still in the code. Awaiting confirmation from the others.

**Comment by hal9000PR** [comment]
Ninjas don't exist anymore (for the most part) and huds are removed by invisibilty by the `make_invisible()` proc which removes huds.

**Comment by Contrabang** [comment]
Ninja invisibility has been removed
