### ISSUE TITLE
Minor Description Issue

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3825]
**Problem Description**:
Becoming a Positronic Brain gives you a small, descriptive message. This message still says they can use :b to speak Binary, despite that being intentionally removed.

**What did you expect to happen**: 
As Binary was stripped from Positronic Brains, that bit of the message should not be there telling people they still have it.

**What happened instead**:
They still have the message as indicated.

**Why is this bad/What are the consequences:**
Well, it's informing players they have an ability they do not actually have, so... bad.

**Steps to reproduce the problem**:
Become Posibrain ---> Read Description Message.

**Comment by tmad40blue** [comment]
Fixed in PR #3837

**Comment by Crazylemon64** [comment]
Ah, you leave "Fixes #3825" in the fix PR, and then the corresponding issue is closed when that PR is closed.

**Comment by tmad40blue** [comment]
I've done it both ways before. Thanks for the clarification.

**Comment by Crazylemon64** [comment]
You'll need to close this PR manually, at this point
