### ISSUE TITLE
Labor Camp Prisoner ID Access

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3826]
**Problem Description**:
Prisoners in the Labor Camp do not have access to the lower half of the Prison Camp Shuttle.

**What did you expect to happen**: 
Well, the rest of the Labor Camp point system works (even tested if the Prisoner ID can send the shuttle back when the quota is matched, which it can), so I expected the person with the Prisoner ID to have access to the Points Claim machine.

**What happened instead**:
People with Prisoner IDs cannot access the lower half of the Prison Camp Shuttle, and are therefore barred from the Points Claim machine.

**Why is this bad/What are the consequences:**
This essentially makes the Labor Camp unusable without constant babysitting from Security. Not sure if this is working as intended, but if the Prisoner ID can send the shuttle back to the station on its own, why can't it actually have access to the means of doing so? This lack of access means that, regardless of how much people have mined, they cannot turn it in without Security having to open doors for them.

**Steps to reproduce the problem**:
Well, simply get a Prisoner ID and check the doors.

**Comment by Kyep** [comment]
The labor camp feature really needs major revision / remapping.

Issues:
1) Prisoners, unlike miners, are not space-immune and thus the second they breach into one of the randomly generated tunnels on the asteroid, they're in a world of hurt.
2) Prisoners, unlike miners, have very little defense against the monsters on the asteroid. Find one? Suffer.
3) Prisoners shouldn't be as easy for miners to break out of prison as they currently are. 
To really solve all these issues, the labor camp should be moved to an entirely new mining asteroid, on another z-level, which has no monsters of cave gen algorithm and is designed for prisoners, not regular miners.
4) Using the labor camp is a huge hassle, for both sec and the prisoner, and doesn't produce much in the way of resources. Thus, what incentive is there to use it?
