### ISSUE TITLE
Blindness Bug with New orangs and Diona Eyes

### ISSUE THREAD

**Issue by DisreputableSquid** [ParadiseSS13/Paradise#3827]
**Problem Description**
I have ended up being effectively blind but still able to see tiles and sprites.

**What should happen**
I used to be able to weld as a Diona without a mask, now I need one. 

**What happens**
I forget, weld without mask, get 'blinded', have eyes heal (can see all tiles and sprites normally) because of diona healing factor, then find out I'm unable to see any actions or examines.

**Why this is a problem**
What makes this such a massive problem is that firstly, Whether it was supposed to or not, Diona shouldn't suddenly need a mask to weld. Also, the blindness can go unnoticed for a long period of time as the other effects of blindness, such as being unable to see anything with examine or see the emotes of others around you, including if they are attempting to do something like forcefeed you or possibly even cuff you can easily go unnoticed if you are not heavily interacting with others or need to examine a lot of things. It also means that it leaves the player incredibly vulnerable as they cannot see any of the activity around them, and thus could be cuffed or stunned without knowing.

**possible causes and solutions**
this is a problem as this could be the diona healing factor not playing nice with the new organ and surgery code, or just the fact that Diona organs are not meshing with the new system in general. I know for sure that they did not take damage from welding before, so I feel like the current state of affairs must be a bug or an oversight.

Removing the Diona eyes ability to be damaged by welding should be a resolution to the problem, as that is how they worked before, or going over the code to ensure that the Diona's healing of organ damage also heals the effects of organ damage too. 

![image](https://cloud.githubusercontent.com/assets/17767700/13676096/66e7ddb2-e6b2-11e5-8ebf-8b4ef77eb2e0.png)

**Comment by TheDZD** [comment]
@Aurorablade
