### ISSUE TITLE
Infinihuggers 2: Electric Bogaloo

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3828]
**Problem Description**:
Facehuggers keep infecting people after dying.

**What did you expect to happen**: 
Leap ---> Infect ---> Dead Hugger

**What happened instead**:
Leap ---> Infect ---> Leap ---> Infect ---> Ad infinitum

**Why is this bad/What are the consequences:**
Well, it's supposed to be "1 Hugger, 1 Larva". Now it's "1 Hugger, Infinite Larvas"

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/alien/special/facehugger.dm#L105-L115

They can't actually impregnate, so it's not infinilarva, but they will keep jumping even if "dead"

**Comment by TheDZD** [comment]
Should be fixed by #3851
