### ISSUE TITLE
R&D/Robotics Cybernetic implants bugs

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#3835]
**Problem Description**:
R&D doesn't have implants pop up under the "Medical" category. You have to manually search for "Implant" to find them. The same happens for robotics, with random implants dissapearing(The only ones that showed up were x-ray and reviver implants, IIRC.)

**What did you expect to happen**: 
It should display all implants in said categories due to research being maxed.

**What happened instead**:
The implants were missing from the medical section of the protolathe, and the misc section of the exosuit fabricator.

**Why is this bad/What are the consequences:**
New players can miss out on the ability to construct said implants, and roboticists are unable to produce said implants despite being in the best position to implant them.

**Steps to reproduce the problem**
Step 1: access an RnD console/exosuit fabricator with research completed.
Step 2: Access the medical section on the protolathe, or the misc section on the exosuit fabricator.
Step 3: Notice that the implants are missing.

**Comment by Fox-McCloud** [comment]
Already fixed. Just not patched.

**Comment by Magikarpet** [comment]
Ah, sorry then. I completley missed it.
