### ISSUE TITLE
IPC injury sprite issue

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#384]
An IPC with a missing foot has a red injury over the sprite on that foot. However, when looking at the sprite from behind, a left foot injury is placed on the right foot. From the front it is fine.

**Comment by Markolie** [comment]
Looking into this, I think this is something which we're simply not going to fix. The way it works, is whenever your limbs take a certain number of damage, a damage overlay is added to your sprite. This pulls from an icon file which contains an overlay for every body part, however, this does not take into account whether it's front facing or back facing. To fix this, we'd have to call the update mob sprite proc every time someone turned to update the overlay, which isn't viable.

Thanks for the report, but fixing this just isn't viable.

**Comment by Ar3nn** [comment]
Alright, thanks for looking into it! I just don't want to label something a generic sprite bug and then it only happen to IPC.
