### ISSUE TITLE
Eating be borked

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3840]
Eating stuff from the snack machine prints "You take a bite" message, but looking at yourself with an advanced health analyzer displays no chems. In addition, no chems are removed from the snack.

Tested: Raisins, beef jerky

@VampyrBytes 

Pills don't appear to work either, and while patches perform their touch reactions, they don't actually inject any reagents

**Comment by Crazylemon64** [comment]
Grah, this was a local error!

**Comment by VampyrBytes** [comment]
@Crazylemon64 lol, thanks for the early morning wtf moment :wink:
