### ISSUE TITLE
Ghosts can teleport people into spacepods

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3843]
**Problem Description**:
You can teleport people into space pods as a ghost

**What did you expect to happen**: 
For me not to be able to put people into a space pod as a ghost

**What happened instead**:
I put people into the spacepod, even when they where not in the same room as the space pod.

**Why is this bad/What are the consequences:**
Well, on one hand, wizards could use this, so could cultists, but in reality it has no use. Like say putting the HoS's spider in the front seat, making it impossible to get it out, thus making the pod unusable.

**Steps to reproduce the problem**:
1. Be a ghost
2. Stand next to a space pod.
3. have anything living nearby, like a human.
4. right click the space pod and click enter.
5. choose something on the list that is not you
6. wait for 3 seconds

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Spacemanspark** [comment]
You can also do this with cyborg rechargers.
