### ISSUE TITLE
Rejuvinate Clears Augmentations

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3844]
**Problem Description**:
When Rejuvenate is used on a character that has augments (or probably any organs other than his base organs), all those augments are lost on rejuv.

**What did you expect to happen**: 
Because augments are positive and shouldn't be cleared when rejuvenated; this is also not how it happens on TG.

**What happened instead**:
All augments were wiped out

**Why is this bad/What are the consequences:**
You get griefed, admin rejuvs you, now you lost all your augments and have to beg for the right ones; likewise, said admin isn't going to know if the person is lying about which implants they had.

**Steps to reproduce the problem**:
Give yourself an augment (brain, chest, what have you) and rejuv.

Thoughts:

Could probably make a temporary container to move all the augments into at the beginning of the rejuv, then, after the rejuv is done, shove them back in. It's certainly hacky, but I dunno any other way off the top of my head.

**Comment by Crazylemon64** [comment]
It's on species change - empties the organ list, then repopulates it with things of the species list.

**Comment by theColdflame** [comment]
rejuv also replaces prosthetic body parts with their organic counterparts

**Comment by theColdflame** [comment]
@Fox-McCloud @TheDZD 

this was fixed by #4446
