### ISSUE TITLE
Internal organs never rot

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#3845]
Since organs aren't added to the processing list on remove, they will not update germ levels, nor slowly die, when removed from a body.

**Comment by Fox-McCloud** [comment]
Certainly a bug--though not one I personally mind, to be honest.

**Comment by Fox-McCloud** [comment]
Notttt sure if this has really been fixed or not.

**Comment by charliehershberger** [comment]
If a live organ is not put in an ice chest is it still a viable transplant under the current system?
