### ISSUE TITLE
AI Core camera doesn't work right if it is nonfunctional at shift start and then gets fixed.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#3846]
**Problem Description**:
The camera next to the AI Core doesn't display the turret controls if it starts the shift non-functional and gets fixed.

**What did you expect to happen**: 
That once the camera is fixed I can see the whole area in view of the camera, including the turret controls.

**What happened instead**:
Every part of the area was visible EXCEPT the wall with the AI chamber turret controls, mounted flash, and wall-mounted radio.

**Why is this bad/What are the consequences:**
AI cannot control turrets within the chamber, nor can they activate the mounted flash as a means of self-defense, and they are cut down from 3 wall-mounted radios to 2 in the event of a comms outage.

**Steps to reproduce the problem**:
Start a round as AI with the AI core camera nonfunctional (it's random as far as I know.)

**Possibly related stuff**: 
Screenshot here: http://i.imgur.com/3eV9aDM.png
As you can see we tried moving the camera to the south wall, and even having a borg stand RIGHT NEXT TO the turret controls didn't allow me to see them.  If I clicked the "AI Core" verb in the AI Commands tab that tile would briefly flash visible, and I could even right-click on the tile and point to the turret controls but alt-click did not show me anything but the static overlay.

**Comment by tigercat2000** [comment]
it's because it's normally an x-ray camera, but reconstructing it removes that

**Comment by tigercat2000** [comment]
How odd. The AI core is supposed to act as a camera.

**Comment by Spacemanspark** [comment]
This is actually ALL roundstart broken cameras that do this.
You basically have to turn the camera on, then off, then on again, and it'll work.

**Comment by FalseIncarnate** [comment]
As shown in the picture (that's me in the atmos suit), we even moved and upgraded the camera and went as far as to deconstruct the wall the controls were on in case the fake wall we made to get to the controls was responsible.

That whole mess was a wild ride of lasers, canisters, and engineering pulling the most Three Stooges act I've ever been a part of.

**Comment by Kerroman** [comment]
@Spacemanspark Yeah, usually to get roundstart cameras to work I do the on/off/on thing.  That doesn't seem to work most of the time either so then I completely deconstruct the camera and then set it up again and that always works.  Rest assured all of that was tried during the round that screenshot is from.  Also given that the AI can see around a cyborg as if there was a camera there you'd think having a cyborg stand right next to the turret controls would allow me to see them.  The cyborg definitely saw them because he was able to turn off the turrets.

I really do like the idea of having several deactivated cameras at round start.  It gives engineering something to do after they're done setting up the engines and solars and a crafty antag can take advantage of a deactivated camera to find the alarm wire and then shut off as many cameras as they like without sending any alerts to the AI.

If possible maybe just make it so that all cameras on the AI satellite are exempt from the round-start deactivation RNG?
