### ISSUE TITLE
Admin freeze doesn't properly display on the target

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3852]
**Problem Description**:
What is the problem?
The admin freeze overlay is only visible for a short duration before going away
**What did you expect to happen**: 
Why do you think this is a bug?
Because it is supposed to alert every viewer that the person is frozen by an admin and not to be touched
**What happened instead**:
How is what happened different from what you expected?
it disappeared
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because, while admin freezes are rarely used, it's very annoying to keep others from trying to "fix" the frozen person
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Freeze a mob
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by FlattestGuitar** [comment]
Not a thing anymore
