### ISSUE TITLE
Sleeping carp issue

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3853]
**Problem Description**:
What is the problem?

Sleeping carp allows you to deflect projectiles even when handcuffed
**What did you expect to happen**: 
Why do you think this is a bug?

I'd imagine dodging the bullets is a varierity of hand and leg movement, something that becomes very hard to do while handcuffed, also it makes stuff like execution by firing squad impossible and a pain in the ass by security, if you're handcuffed you've lost anyways
**What happened instead**:
How is what happened different from what you expected?

Expected them to get hit and fuck off
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

See above, why it's a bug
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Give someone sleeping carp, handcuff them and shoot them
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
Not a bug.
