### ISSUE TITLE
Syringes cause attacks when injecting

### ISSUE THREAD

**Issue by DarkPyrolord** [ParadiseSS13/Paradise#3855]
**Problem Description**:
Syringes seem to cause an attack action when injecting or drawing from players/human mobs.

**What did you expect to happen**
Just a normal injection, with one message.

**What happened instead**:
When injecting with a syringe, it also seemed to come up with an attack message along with the normal injection message.

**Why is this bad/What are the consequences:**
Pretty much anyone using syringes looks like they are attacking the one they are injecting.

**Steps to reproduce the problem**:
Just use a syringe and attempt to draw or inject into a human mob.

**Possibly related stuff**:
Screenshot: http://i.imgur.com/iYH6H1w.png

**Comment by FlattestGuitar** [comment]
While the person was on a surgery table the syringe would instead of attacking attempt to start an operation, as mentioned in [#3807](https://github.com/ParadiseSS13/Paradise/issues/3807) Since [#3813](https://github.com/ParadiseSS13/Paradise/pull/3813) fixed that, apparently, it's possible this is no longer an issue.

**Comment by Fox-McCloud** [comment]
@FlattestGuitar 

Nah, this is when you're injecting someone with something---it trigger and attack animation on them for whatever reason.

@VampyrBytes 

You may know something of this? Though it's odd because I don't believe you touched syringes?

**Comment by VampyrBytes** [comment]
@Fox-McCloud 
Nope, didn't touch syringes. I know what a mess external organs (which deal with attacks) are though, so I'd guess somewhere in there there's an
`if (sharp)`
.   `if(!syringe)`
that's been broken by #3813 changing syringes to not being sharp.
Don't have time right now to check, but I'll have a look tomorrow and see what's going on
