### ISSUE TITLE
Changeling: Absorption only resets genome counter if you have EXACTLY 4 genomes stolen

### ISSUE THREAD

**Issue by wotan90** [ParadiseSS13/Paradise#386]
Absorped one guy after i had three genomes. Got one more genome. Absorption message pops up again.

**Comment by TheDZD** [comment]
Absorbing someone shouldn't be resetting the genome counter, only transforming should do that. Did you try transforming after it gave the message?

**Comment by wotan90** [comment]
Nope i did not transform. I was under the impression, that absorbing resets it. Apologies. Seems like absorption is now only useful for reshuffling evo points.

**Comment by Fox-McCloud** [comment]
@wotan90 

Close, but not exactly; absorbing additional people makes your shield stronger and unlocks the spider ability as well.
