### ISSUE TITLE
Mouse has no in hand sprite

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#3878]
**Problem Description**:
The mouse has no in hand sprite

**What did you expect to happen**: 
The picked up dead mouse should've appeared in my hand

**What happened instead**:
i had a mouse in my hand but it was invisible

**Why is this bad/What are the consequences:**
not sure if i had an empty hand or not

**Steps to reproduce the problem**:
pick up a dead mouse

![picking up mouse](https://cloud.githubusercontent.com/assets/11246791/13749541/3f1b695e-ea02-11e5-9752-ebfac57a4abb.gif)

**Comment by KasparoVy** [comment]
Should have been fixed by #3903 but this didn't autoclose

**Comment by taukausanake** [comment]
It was merged before issue was made it seems
