### ISSUE TITLE
Megaphones don't work

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#3879]
**Problem Description**:
Megaphones will not work.

**What did you expect to happen**: 
I've used megaphones in the past and they worked fine. I expected this to be the case.

**What happened instead**:
The megaphone simply did not work. I used it in-hand while in hotkey mode with the "Z" key, and I tried clicking on it in-hand. I'm absolutely certain both of these methods worked in the past, prompting a dialogue box saying something along the lines of "What message would you like to broadcast?"
This is no longer the case, last I checked (which was a few days ago and I forgot to make a report until now).

**Why is this bad/What are the consequences:**
A feature of the game simply does not function. It's not a pressing issue, but it is a broken feature.

**Steps to reproduce the problem**:
1.) Acquire megaphone (I play Research Director, so that's where I get mine).
2.) Try to use megaphone to yell at people or get your voice heard over twelve people trying to talk to you at once.
3.) Feel sad that megaphones are broken.

P.S. I don't know why, but I get the feeling that I'm crazy and this does work. At the same, megaphones have worked before and now don't, so I don't think I managed to forget such a simple function all of a sudden.

**Comment by monster860** [comment]
Have you tried pushing page-down?

**Comment by ProperPants** [comment]
Page down does not work. Just tried. Click, Z, and page down all fail.
