### ISSUE TITLE
Docking of shuttles is bugged

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#3884]
**Problem Description**:
Whenever a shuttle docks the doors stay bolted. This includes the escape shuttle and the cargo shuttle.

**What did you expect to happen**: 
the doors to unbolt after 5 or so seconds

**What happened instead**:
they staid closed

**Why is this bad/What are the consequences:**
cannot enter the shuttle

**Steps to reproduce the problem**:
Call a shuttle, either cargo or escape.

**extra info**:
At the end of the .gif you see the door open anyway, i do not know if they used an emag, or if an admin maybe helped them. This is the round that kluys put a photocopier into his character creating 3000 buttpictures and lagging the server to hell.

![airlocks](https://cloud.githubusercontent.com/assets/11246791/13761105/ee9dece2-ea36-11e5-95bc-8c50b17cb73b.gif)

**Comment by Tastyfish** [comment]
Fixed by #3876

**Comment by tigercat2000** [comment]
fixed already, waiting on patch for #3876
