### ISSUE TITLE
Brig Timer Hourly Reset

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3888]
**Problem Description**:
On occasion, a Brig Timer will reset to over 1400 minutes (shows up as 60 minutes on the sprite) after finishing counting down to zero, rather than unlocking the cell.

**What did you expect to happen**: 
Timer gets to 0 ---> Door and locker open.

**What happened instead**:
Timer gets to 0 ---> Suddenly an extra hour wat

**Why is this bad/What are the consequences:**
Well, it's a minor, random inconvenience, but it's still an inconvenience not to have the timer properly open the door.

**Steps to reproduce the problem**:
Law of Great Numbers. Set a bunch of timers on a bunch of cells and hope for the worst.

**Comment by Spacemanspark** [comment]
Clearly this is the game punishing the worst of criminal scum.

**Comment by TullyBurnalot** [comment]
"YOU SIT IN CORNER NOW! EXTRA HOUR!"

**Comment by Fox-McCloud** [comment]
probably fixed by: https://github.com/ParadiseSS13/Paradise/pull/3876

**Comment by Tastyfish** [comment]
Looking at the code, it looks like it uses world.timeofday and always handled midnight rollover wrong.
