### ISSUE TITLE
Kinetic Accelerators instantly detonate Gibeonite

### ISSUE THREAD

**Issue by Davdichan** [ParadiseSS13/Paradise#3893]
**Problem Description**:
If a Kinetic Accelerator shot strikes unmined Gibonite (KA, Super KA or Hyper KA) the Gibonite will detonate immediately, bypassing the chain reaction. Every other method triggers a chain reaction, to include Toxin bombs and other Gibeonite Explosions.

**What did you expect to happen**: 
When a rock with Gibonite inside of it is mined, the Gibonite flashes 8 times over approx 4-5 seconds before exploding, allowing miners to run or disarm it with a mining scanner.

**What happened instead**:
Gibonite explodes instantly. No flashing or chainreaction.

**Why is this bad/What are the consequences:**
Miners who choose to use a Kinetic Accelerator can not harvest Gibonite, and the range of the explosion means the miner will always be inside the explosive radius. This is the only time Gibonite explodes instantly, using a plasma cutter, drill, toxin bomb or even other gibonite will always trigger a chain reaction. **Even the singularity does not instantly explode gibonite**

Given that only these three items do this, it seems to be either an intentional (and faulty) balance attempt, or an oversight with copypasta going on. 

If this is an attempt at balance, it's not doing much as 1) Harvesting Gibonite with a KA isn't very efficient since you still need to approach and hit it with your scanner, any lag can throw off your count of the flashes and make a weaker gibonite shard or allow it to explode, and 2) Unless you are injured you can easily run out of the radius if you accidently trigger gibonite with a drill or pick, so it's not like this can be abused to take a pot shot at gibonite and escape unharmed.

**Steps to reproduce the problem**
1) Acquire Kinetic Accelerator (any version)
2) Find Gibonite ore tile.
3) Shoot Gibonite.
4) ??? [Ka-boom]
5) Limp back to medical for limb re-attachment/replacement.

**Comment by FlattestGuitar** [comment]
I've done this more times than I'd like to admit. I think it should stay so as to balance the power of the KA with the less efficient pickaxe. 

Possibly make other FUN things trigger gibtonite as well?

**Comment by Spacemanspark** [comment]
Ya, this was something that @TheDZD warned us about when porting /tg/ mining.

**Comment by fludd12** [comment]
Gibtonite is described as being a kinetic chain reaction

And you thought shooting it with something defined as a kinetic accelerator was a good idea?

**Comment by Davdichan** [comment]
Exactly why does a KA cause it to detonate instantly when any other explosion or ranged weapon does not?

**Comment by Fox-McCloud** [comment]
This probably isn't going to be able to be fixed with out current gun code, to be honest.

**Comment by Robertha89** [comment]
I rather like this, it's like finding a pocket of gas, that instantly ignites, and explodes after a while, vs exploding the entire pocket before you even knew about it.
Hyper kinetic accelerators makes mining safer.

**Comment by Spacemanspark** [comment]
This is finally fixed with new gun code?
Thank fuck.

**Comment by Davdichan** [comment]
I certainly fucking hope so, instantly losing your leg cause the scanner lags far behind what a hyper can dig is annoying as shit.

**Comment by M3hillus** [comment]
Woah woah woah woah. Hold the train.

I thought this was a fully intended feature.

**Comment by Spacemanspark** [comment]
No, it's not.

**Comment by Davdichan** [comment]
If it was an intended feature than Gibonite would detonate instantly when chained with other gibonite. Since that doesn't happen, it's obviously not meant for a KA to bypass the countdown.
