### ISSUE TITLE
Labor Camp Ore Console

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3894]
**Problem Description**:
Cannot retrieve the ores loaded by the Labor Camp prisoners onto the Stacking Machine.

**What did you expect to happen**: 
To be able to retrieve the ores the dastardly criminals mined.

**What happened instead**:
Ores stuck in machine, everyone is sad about this.

**Why is this bad/What are the consequences:**
Well, it makes the Labor Camp, in practice useless. The point was that the prisoners would produce something good for the station, now it's just kinda stuck in the machine. It's lacking the proper console.

**Steps to reproduce the problem**:
Go mine at the labor camp, load ore into Stacking Machine, be sad at the lack of "Retrieve Ore" button.

**Comment by Twinmold93** [comment]
You use the consoles on the wall next to them to take the ores out. Not a bug, as far as I can see.
