### ISSUE TITLE
Sleeping Carp Martial Art goes away on its own. (or at least it did once)

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#3895]
I know this is a terrible issue report, but possibly there's some proc which resets the martial art that somehow gets activated and has been overlooked.

**Problem Description**:
I somehow lost the Sleeping Carp martial art during the course of a round.

**What did you expect to happen**: 
I believe the art should be permanent or at least notify the player of it not being such.

**What happened instead**:
The martial art went poof and I could no longer evade taser rounds with the sheer force of my will or twist people's wrists. I also still had the "Sleeping Carp" tab and the "recall teachings" verb, which worked.

**Why is this bad/What are the consequences:**
Muh carp

**Steps to reproduce the problem**:
Absolutely no idea how to reproduce this. I just pulled off some moves on a few people and a farwa and after some time I just couldn't pull them off anymore. I asked the HoS to shoot me with their taser and I wasn't able to evade the electrode.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The scroll was bought using a traitor PDA. I believe Klyus was messing around that round with a lot of stuff (that was the photocopier that got the server reset), but I seriously doubt he'd be somehow able to remove my martial art on accident.

**Comment by Fox-McCloud** [comment]
Going to guess you got cloned.

**Comment by FlattestGuitar** [comment]
Nope, no cloning. Just ran around a bit and suddenly it disappeared.

**Comment by TheDZD** [comment]
Did you happen to ingest a large amount of alcohol? Might have replaced Sleeping Carp with drunken brawling.

**Comment by Fox-McCloud** [comment]
Given that Eli is a career alcoholic...likely.

**Comment by FlattestGuitar** [comment]
I am dumb. That explains it. Eli sabotaged himself.

**Comment by TheDZD** [comment]
Don't drink and box kids.

**Comment by FlattestGuitar** [comment]
Well... getting drunk is in no way logically connected to losing your skills as a martial artist.

I'd still call this one a bug, because now Eli will be suspicious if he doesn't drink anything the whole shift.

**Comment by TheDZD** [comment]
Fair enough, probably shouldn't remove a martial art entirely if you get drunk. Might be worth checking if boxing gloves do this as well.

**Comment by Keilden** [comment]
Yeah I forgot to report it but I ahelped it during a round. I lost my martial arts when I put on boxing gloves. don't Think any admins Heard me since no one answerd.
