### ISSUE TITLE
'Nother MOTD Typo

### ISSUE THREAD

**Issue by Vivalas** [ParadiseSS13/Paradise#3897]
![image](https://cloud.githubusercontent.com/assets/6334647/13791506/7f286b82-eabb-11e5-930d-c7958b73dac2.png)

"effected" should be "affected"

All hail the grammar Nazi.

**Comment by Earthdivine** [comment]
*scream

**Comment by Fox-McCloud** [comment]
@Necaladun

**Comment by Vivalas** [comment]
Not even sure we still have this motd anymore.
