### ISSUE TITLE
Debug Preferences Do Not Save Between Reboots

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3900]
**Problem Description**:
Toggle debug preferences doesn't save between rounds

**What did you expect to happen**: 
The damn preference to save its status between rounds

**What happened instead**:
To toggle it off and for the damn thing to STAY off.

**Why is this bad/What are the consequences:**
debug log spam that I don't need to see 99% of the time.

**Steps to reproduce the problem**:
Toggle it off, watch as it comes back on the next time the server reboots. Utilize the *scream emote in displeasure

**Comment by Regen1** [comment]
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM
>FOX MCCLOUD HAD HIS WIZARD PREFERENCES SET TO YES SO WE ARE DRAFTING THEM

**Comment by tigercat2000** [comment]
@Fox-McCloud this was #3900
oh my god
