### ISSUE TITLE
Alien resist doesnt extinguish fires, despite text stating you extinguishes yourself.

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#3909]
**Problem Description**:
Using resist to extinguish fires is a terrible idea. It doesn't extinguish xenos, even when it states it does.

**What did you expect to happen**: 
The fire should've been extinguished.

**What happened instead**:
The fire rises.

**Why is this bad/What are the consequences:**
It allows a single chucklefuck with a clf3 spray to kill xenos if they arent fighting in space

**Steps to reproduce the problem**:
Be a xeno, get set on fire, and try to resist.

**Comment by Fox-McCloud** [comment]
@Tastyfish 

Xenos had a special override where they'd be weakened, despite the fact they normally couldn't---your change probabbbbly broke this.

**Comment by Magikarpet** [comment]
There's also a few weird interactions with stuns and xenos, being stunned seems to last less than a second(and you can crash into the same wall repeatedly within a few seconds.)

**Comment by Tastyfish** [comment]
Yeah, their stat code is so snowflakey and weird it probably is some obtuse conflict with my stat changes.

**Comment by Fox-McCloud** [comment]
having recently tested xeno extinguishing--this is definitely fixed.
