### ISSUE TITLE
Can still walk with missing leg

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#3916]
**Problem Description**: Read title.

**What did you expect to happen**: To fall over and not be able to move without a cane.

**What happened instead**: I can walk fine except maybe a bit slower

**Why is this bad/What are the consequences**: Unless you can say you're hopping around, muh immersions.

**Steps to reproduce the problem**: Get murdered by someone with a hatchet and lose your leg.

**Possibly related stuff**: It was a robotic leg so that might mean something. Then again maybe not and this is an intended feature

**Comment by Fox-McCloud** [comment]
Not a bug. This is intentional for balance reasons and overwhelming requests to have it changed.
