### ISSUE TITLE
Shadowpeople ash on death, rendering immortality from the wild west wishgranter useless.

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#3917]
**Problem Description**:
Shadowpeople ash on death, while not inherrently harmful when involving shadowlings it prevents a feature of the wild west gateway from being usable.

**What did you expect to happen**: 
Shadowpeople would not ash on death, allowing the immortality verb you gain to be used to revive your dead corpse.

**What happened instead**:
I ashed, and was subsequently prevented from using the immortality verb as that requires me to be in my body.

**Why is this bad/What are the consequences:**
This renders part of the wild west gateway mission unusable. While kill everyone/wealth/power naturally has no need to care about being ashed, Immortality is rendered to be a complete downside as a result of this(unless you somehow change your race.)

**Steps to reproduce the problem**:
Activate the wild west wishgranter and resquest immortality, before shortly being ashed and unable to use the immortality revive(as on /tg/, of course.)

**Comment by Fox-McCloud** [comment]
@Magikarpet 

Now that shadow people have been reworked, this is no longer an issue.
