### ISSUE TITLE
Autopsies are fucked with the new surgery promt

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#3928]
**Problem Description**:
you can no longer perform autopsies with the news surgery promt without performing the whole procedure on the dead body.

**What did you expect to happen**: 
Being able to cut open all parts of the body one after another to scan them with the autopsy scanner.

**What happened instead**:
unable to quit the surgery soon so i had to perform whole procedures with autopsy scans inbetween them.

**Why is this bad/What are the consequences:**
it takes litterally 10 times more time to perform an autopsy

**Steps to reproduce the problem**:
see .gif

![autopsy](https://cloud.githubusercontent.com/assets/11246791/13898190/e77782c0-edc9-11e5-8b10-4633cd9f1ec7.gif)

**Comment by Crazylemon64** [comment]
I mean you can abort the surgery with a scalpel in the primary and a cautery in the off-hand, but I concur that it is super janky

**Comment by pinatacolada** [comment]
you can actually select any random surgery, do scalpel and then do the autopsy thing, no need to abort it

**Comment by Tastyfish** [comment]
I've been doing @pinatacolada's method, because you can just blindly hit enter through the selection, scalpel, and scan. But yeah, janky.

**Comment by TheDZD** [comment]
@Aurorablade

**Comment by Aurorablade** [comment]
its fixed in https://github.com/ParadiseSS13/Paradise/pull/3849 that adds an infection/autopsy option...whitch is pretty much scalpal and caturize.
