### ISSUE TITLE
Deadchat

### ISSUE THREAD

**Issue by Svej** [ParadiseSS13/Paradise#393]
Trialmins cannot see deadchat when alive anymore. --- nevermind this, my permissions werent set correctly.

2. You can't toggle darkness off and still see other observers or the ai eye? Not sure if intended, but it's very weird.

**Comment by Markolie** [comment]
1. It's because you don't have the R_MOD permission - check with Neca to have that added.
2. This has never been possible, so it's a feature request.

**Comment by Svej** [comment]
Well the "toggle sight" command replaced toggle darkness, and you could see other observers while having darkness turned off back then.

**Comment by Markolie** [comment]
You sure about that? I'm like... 60% sure the old one didn't let you combine.

**Comment by Ar3nn** [comment]
I believe I remember being able to under the darkness system, as well.

**Comment by Artorp** [comment]
I vividly remember disabling darkness removing other observers. Like, 90 % sure.

**Comment by TheDZD** [comment]
Disabling darkness also disabled other observers, there has not been a way to disable darkness as a ghost while preserving the ability to see other ghosts.
