### ISSUE TITLE
Bandanas put on as headwear block CPR

### ISSUE THREAD

**Issue by sasanek12** [ParadiseSS13/Paradise#3948]
**Problem Description**:
What is the problem?
Putting on bandanna as head-wear seems to be causing "Remove your mask!" message.
**What did you expect to happen**: 
Why do you think this is a bug?
I expected to be able to perform CPR with bandanna put on as head-wear.
**What happened instead**:
How is what happened different from what you expected?
I received "Remove your mask!" notification
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
People dying in case of sudden medical emergency with no medicaments around.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Put on Bandanna as head-wear
Acquire person in critical/dead state
attempt to perform CPR
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by FlattestGuitar** [comment]
You sure it's limited to tajaran? This seems super weird, maybe it was an isolated issue?

**Comment by sasanek12** [comment]
Not sure, but i've seen humans performing proper CPR, and i don't play any other race than Tajara.

**Comment by FlattestGuitar** [comment]
Well, this could be a result of literally anything else. Have you tried to perform CPR on a different occasion than that one time you saw it first?

**Comment by sasanek12** [comment]
Yes, i tried to perform CPR multiple times by now, on different people with completely different clothing and issue was still present. Issue seems to be current for month or two now.

**Comment by Tastyfish** [comment]
Are you absolutely sure you weren't wearing something blocking your mouth in either your mask or head slot? There's really no other way that message can come up, unless something really bizarre is happening.

**Comment by sasanek12** [comment]
My bad. apparently bandana put on head is blocking CPR aswell, not really realistic i guess? Anyway, Issue is clear to be closed

**Comment by Spacemanspark** [comment]
Or rename the issue to be about bandanas blocking CPR.

**Comment by KasparoVy** [comment]
On it, my oversight

**Comment by Tastyfish** [comment]
@KasparoVy  The CPR code also checks if the mask was adjusted already.

**Comment by KasparoVy** [comment]
Fixing another bug while I'm at it: The ability to run internals from adjusted airtight masks
