### ISSUE TITLE
IPCs don't go blind when their heads are knocked off.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#3949]
**Problem Description**:
See title, IPCs remain with full vision.

**What did you expect to happen**: 
They should be blind.

**What happened instead**:
IPCs retain full vision.

**Why is this bad/What are the consequences:**
Pretty critical, an IPC shouldn't lose their head without going blind.

**Steps to reproduce the problem**:
-Be glorious IPC unit.
-Get into glorious melee fight.
-Lose head in three hits.
-Laugh at those petty organics as you still see them all. Now terminate them.

**Possibly related stuff**: It happened right after @Aurorablade's organ PR, so I assume it's related to that.

**Comment by TheDZD** [comment]
Most recent organ PR should fix this, we still haven't patched.

**Comment by Spacemanspark** [comment]
Ah, fair enough.
