### ISSUE TITLE
New surgery system bugged out or internal bleeding in extremities  

### ISSUE THREAD

**Issue by mrturkeytoe** [ParadiseSS13/Paradise#3954]
**Problem Description**:
What is the problem?
I had a patient with internal bleeding in their right leg and there was no surgery option to fix it.
**What did you expect to happen**: 
Why do you think this is a bug?
I expected there to be a option in the surgery list like "Internal bleeding repair".
**What happened instead**:
How is what happened different from what you expected?
There was no option to fix internal bleeding.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
They bleed out and died.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Someone with internal bleeding in a leg/arm then attempt to fix it
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
Already fixed, not patched in.
