### ISSUE TITLE
Eating a hivelord cores / admin rejuvernate removes all implants

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3974]
**Problem Description**:
What is the problem?
Eating a hivelord core removes all implants
**What did you expect to happen**: 
Why do you think this is a bug?
Because eating a hivelord core as a miner to stay alive should not be punishing
**What happened instead**:
How is what happened different from what you expected?
The hivelord core I had in my chest was removed
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because hard earned hivelord cores / implants should not be removed by being rejuvernated
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Get implants, rejuvernate / eat a hivelord core
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
@Aurorablade

**Comment by Crazylemon64** [comment]
Currently, `rejuvenate` will remove all foreign organs and implants, good and bad. This is to simplify organ replacement, though I've got a PR to fix the matter in the works.

**Comment by Fox-McCloud** [comment]
duplicate
