### ISSUE TITLE
Boost AAC range. 

### ISSUE THREAD

**Issue by PJB3005** [ParadiseSS13/Paradise#3978]
Really a range of 8 tiles is fucking nothing and I initially did it like this so people would stop complaining about "muh AAC balance" 2 years ago. 

20 tiles should on it.

**Comment by ScratKnapp** [comment]
What is an AAC?

**Comment by Fox-McCloud** [comment]
Feature/balance requests go on the forums, not on the git.

**Comment by PJB3005** [comment]
Ugh right I forgot. I'm still convinced phpBB forums are terrible to manage compared to GitHub issues for both features and bug reports.

**Comment by Fox-McCloud** [comment]
You could also make a PR for it.

**Comment by PJB3005** [comment]
@Fox-McCloud but I don't play on here. (I just felt like making the AAC live its true glory)
