### ISSUE TITLE
Unbranded heads are missing a sprite.

### ISSUE THREAD

**Issue by NTSAM** [ParadiseSS13/Paradise#3979]
**Problem Description**:
Selecting the "unbranded" option for the head as an IPC results in it being invisible on the actual in-game figure.

**What did you expect to happen**: 
For the nice tin-man head to show up on my IPC.

**What happened instead**:
The head was invisible, optics and antenna still stood in the spot.

**Why is this bad/What are the consequences:**
IPCs will have invisible heads. Completely invisible.
**Steps to reproduce the problem**:
1) Choose species -> IPC
2) Go to the prosthetics menu.
3) Select the "head" option.
4) Choose "Unbranded" as your manufacturer.
5) Oh noes, spooky headless robot!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I did choose to give the IPC a pair of antenna, so that may or may not have to do anything with it?

**Comment by Fox-McCloud** [comment]
@KasparoVy

**Comment by KasparoVy** [comment]
On it, thanks for reporting

**Comment by TheDZD** [comment]
Should be fixed by #3988
