### ISSUE TITLE
Kasparovy your sprite is messed up

### ISSUE THREAD

**Issue by lolzyking** [ParadiseSS13/Paradise#3982]
**Problem Description**: s
 Sprite from Zeng hu prosthetics is a pixel too big on the Left leg,it rips out of pants.

**What did you expect to happen**: 
 self explanatory

**Why is this bad/What are the consequences:**
 it looks ugly

**Steps to reproduce the problem**:
Select zeng hu cybernetics left leg.

**Possibly related stuff (which gamemode was it? 
I haven't checked but other legs might be messed up a bit.

**Comment by TheDZD** [comment]
@KasparoVy

**Comment by KasparoVy** [comment]
It's just that one and I've no idea why
On it
