### ISSUE TITLE
You are able to message in the PDA chatrooms while being deaded or sleeped

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3984]
**Problem Description**:
People are able to message in the PDA chat rooms from the afterlife while they are in their body. (Possibly even while unconscious)

**What did you expect to happen**: 
Expected that the ghosties wouldn't be able to spook people from the afterlife through the chat rooms.

**What happened instead**:
They are able to talk in the PDA chat rooms.

**Why is this bad/What are the consequences:**
It could be abused/used to talk with people in-game while they have died.

**Steps to reproduce the problem**:
1. Be dead (or asleep, not 100% about this one)
2. Be in a chat room
3. Have someone message in said group.
4. (I assume), you are able to click the "post" while sitting in your body, allowing you to message peeps.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

The gamemode wouldn't have any effect on the chat room, being dead and being in a chat room is really all that matters.

**Comment by TheDZD** [comment]
@Tastyfish
