### ISSUE TITLE
Losing your entire leg as a slime causes you to not have the ability to regenerate the leg/arm, and it prevents you from wearing shoes if you regnerate a foot from a missing leg.

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#3990]
**Problem Description**:
Slime regen is bugged.
**What did you expect to happen**: The ability to grow legs/arms instead of just hands/feet.

**What happened instead**:
No legs, no shoes, no fun.

**Why is this bad/What are the consequences:**
Awkward scenarios in which people are missing feet/legs, unable to wear shoes, while still being

**Steps to reproduce the problem**:
Regrow your limb, when missing the leg or arm, and having a stump. It causes limb usability issues and you can't regen it.(Edit note: it being the leg/arm, not the hand/foot)

**Comment by johannhawk** [comment]
i wasn't aware of this...

welp

**Comment by Crazylemon64** [comment]
Erwups... This is going on my stack

**Comment by Spacemanspark** [comment]
Don't get a StackOverflowException, Crazy. :^)

**Comment by Mitchs98** [comment]
This seems to be fixed. I can confirm I can regen all limbs properly as a slime boi.
