### ISSUE TITLE
Shoulder Holster's (top-left) "button" not showing up when it is attached to clothing.

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3991]
**Problem Description**:
You aren't able to use the shoulder holsters "button" whenever you attach it.

**What did you expect to happen**: 
I expected the "button" to show up when it is attached (it used to)

**What happened instead**:
The button did not show up.

**Why is this bad/What are the consequences:**
While you are still able to click on the piece of clothing with the shoulder holster on it to take out the revolver, it makes it slightly more difficult as the button disappears (when it shows up while it's in your hand)

**Steps to reproduce the problem**:
1. Have a shoulder holster in hand (https://i.gyazo.com/41ddc3eceac4008852bf387add918956.png - Note: the button shows up in the top left.)
1. Attach it to a piece of clothing (both the striped dress and hard-worn suit didn't work, so I would assume all clothing doesn't work.) (https://i.gyazo.com/49805ddfec332e484d1548debeb27da6.png - Note: No button in the top left.)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Game mode didn't matter, if clothing/equipment at the same time matters, please see the pictures above.

**Comment by FlattestGuitar** [comment]
Doesn't look like it's a thing anymore.
