### ISSUE TITLE
Hatched headslugs from non-changeling sources do not gain changeling verbs.

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#3999]
**Problem Description**:
non-changeling made headslugs, such as xenobiology/admin spawned ones do not gain changeling verbs upon bursting.

**What did you expect to happen**:
On /tg/, this is a feature for lategame xenobiology.(You can raise changelings from headcrabs, with changeling verbs/changeling hivemind.)

**What happened instead**:
The changeling became an ordinary monkey, which has to be xenobiology mutated into a human. They don't gain said verbs, or the ability to revert their form.

**Why is this bad/What are the consequences:**
This renders xenobiology into an awkward situation with headslugs, essentially making them humanoid golems instead of something unique.

**Steps to reproduce the problem**:
Inject a gold slime core until you get a headspider, offer it a sentience potion, and let it lay eggs in a dead body.

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
I don't believe this is possible with current changeling code. TG's changeling code handles things via something called "profiles"--we do not have this as our changeling code is a bit dated by now. Needless to say, this isn't a bug so much as a feature request.

**Comment by Fox-McCloud** [comment]
Sooo, I was mistaken, this was in fact possible. Fixing it now.
