### ISSUE TITLE
Voice Assemblies Don't Work Inside Backpacks

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4001]
**Problem Description**:
If you attempt to activate a voice signaler that's in your backpack (or a box in your backpack), it will not activate; it must be in your pocket or off your person.

**What did you expect to happen**: 
For an assembly to activate when I gave the proper code phrase, even if it's in my backpack--it works in pockets, afterall.

**What happened instead**:
It didn't go off

**Why is this bad/What are the consequences:**
Limits use of specific triggered grenade. Likely an issue with recursion and say code.

**Steps to reproduce the problem**:
Make a voice activated grenade...put it in your backpack--try to trigger it--it will fail. Remove grenade, use same trigger while it's in your pockets or elsewhere---it'll go off.

**Comment by Crazylemon64** [comment]
Prolly need to override their `hear_say`
