### ISSUE TITLE
Problems/ suggestions about the new surgery system

### ISSUE THREAD

**Issue by mrturkeytoe** [ParadiseSS13/Paradise#4020]
**Problem Description**:
What is the problem?
You hit people with surgical tools if you use the wrong one and if you do hit them you have to start over.
**What did you expect to happen**: 
Why do you think this is a bug?
If someone is on a operating table and i use the wrong tool i expect to get the "You don't think this will work". Be able to continue say, a ghetto surgery if i accidentally hit them.

**What happened instead**:
How is what happened different from what you expected?
If you use the wrong tool on someone it hits them. If you hit them you have to start over, killing ghetto surgery.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
You can no longer perform ghetto surgery reasonably. Using the wrong tool can kill your patient.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Stick someone on a operating table and use the wrong tool/Try to perform ghetto surgery.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/Crazylemon64/Paradise/commit/532fed2f7b5269603a3b19aa953d8b3b3bcdf350>I'm currently redoing the surgery system, so that it's stack-based</a>. I'll see to making it harder to hit your patient over the head if you're in surgical conditions, on help intent.

**Comment by Crazylemon64** [comment]
@mrturkeytoe Although, this isn't a problem with the NEW surgery system: The OLD surgery system had you have a good chance of whacking your patient if you weren't on an operating table, which would, "kill ghetto surgery" as you said. So, not actually a problem with the NEW system, and more of a feature request.

**Comment by mrturkeytoe** [comment]
But in the old surgery system you could pick up where you left off. I might be wrong about the having to start over thing.

**Comment by KasparoVy** [comment]
You don't have to start over, at least in my experience given the exact circumstances you've mentioned

**Comment by mrturkeytoe** [comment]
My biggest problem with it is that if someone's on a operating table, you're on help intent and are in the middle of a surgery you still hit them if you use the wrong tool.

**Comment by Fox-McCloud** [comment]
>My biggest problem with it is that if someone's on a operating table, you're on help intent and are in the middle of a surgery you still hit them if you use the wrong tool.

That's actually the way it used to be for eons until an update came along and made it literally foolproof if you're on help intent.

**Comment by Alex6511** [comment]
@Fox-McCloud Stuff like wiki updating and bug fixing is generally supposed to occur at the code review part of the development cycle and not after it. Meaning it should be done before it's merged.

**Comment by DaveTheHeadcrab** [comment]
@Alex6511 
Is that someone volunteering to do wiki work I hear?

**Comment by Alex6511** [comment]
@DaveTheHeadcrab I don't have time to code my own stuff, let alone document other peoples broken code.

**Comment by Alex6511** [comment]
@DaveTheHeadcrab Can I have the ID of the PR where the surgery system was overhauled? I don't follow this repo anymore.

**Comment by DaveTheHeadcrab** [comment]
#2903
