### ISSUE TITLE
Sleeping Carp users can use spray bottles

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#4026]
**Problem Description**:
After using a sleeping carp scroll, the user can still use spray bottles

**What did you expect to happen**: 
I expected to use the sleeping carp scroll and not be able to use the spray bottle,.

**What happened instead**:
I attempted to use a spray bottle and it worked

**Why is this bad/What are the consequences:**
Because the disadvantage of sleeping carp is being unable to use ranged weapons.

**Steps to reproduce the problem**:
Be a traitor, buy the sleeping carp scroll, attempt to use a spray bottle, succeed.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
This happened on a test server.

**Comment by Fox-McCloud** [comment]
Not a bug. And completely intended.

They're not allowed to use *guns*.

**Comment by johannhawk** [comment]
@Fox-McCloud does this mean i can use a minibow or other bows?

**Comment by FalseIncarnate** [comment]
No, crossbows are a child of gun.

**Comment by theColdflame** [comment]
perhaps the description text should be changed from 'ranged weapons' to 'firearms' or 'guns' then?

**Comment by Bigtimetripod** [comment]
English lessons for ye all.

Gun

1.
a weapon consisting of a metal tube, with mechanical attachments, from which projectiles are shot by the force of an explosive; a piece of ordnance.
2.
any portable firearm, as a rifle, shotgun, or revolver.

**Comment by Spacemanspark** [comment]
THIS IS MY RIFLE.
THIS IS MY GUN.
ONE IS FOR SHOOTING.
AND ONE IS FOR FUN.
