### ISSUE TITLE
You can't re-enter the slaughter demon's bloodcrawl form, once you've left it.

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#4027]
**Problem Description**:
 Slaughter demon's bloodcrawling does not allow them to re-enter the blood dimension

**What did you expect to happen**: 
they could re-enter it, allowing them to devour corpses and relocate to attack people from surprise points.
**What happened instead**:
While already exposed and materialized, all I could do is leave blood, not enter it.

**Why is this bad/What are the consequences:**
This severely limits the power of slaughter demons, effectively making then act as a one time deployment machine that's incredibly easy to murder.

**Steps to reproduce the problem**:
Attempt to use your bloodcrawl to re-enter blood.

**Comment by TheDZD** [comment]
@Aurorablade
