### ISSUE TITLE
Can Humanize Monkies with Mutadone+Unstable Mutagen

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4031]
**Problem Description**:
Simply Put if you inject a monkey with both mutadone and mutagen in a short amount of time, it will become human

**What did you expect to happen**: 
The monkey shouldn't be able to become human by the injection of two chems

**Why is this bad/What are the consequences:**
Makes it overly easy to humanize monkies--this is a process that's meant to require genetics involvement and a lot of set up. The implications of this are pretty nasty, especially for vampires and changelings, who have a guaranteed cheese strat to go to with at round start that doesn't even involve setting up a console anywhere or taking any risk what-so-ever.

**Steps to reproduce the problem**:
Inject a monkey with mutadone and mutagen at the same time

@Crazylemon64

**Comment by monster860** [comment]
Since when is humanizing a monkey hard? I've done it blind.

**Comment by TheDZD** [comment]
Hard isn't the right word, but it's supposed to be limited solely to genetics machines.

**Comment by Crazylemon64** [comment]
I mean, the two chems are both doing their jobs, but clearly mutadone doing its job, the way it is, causes problems. Probably want to revert to the baseline SE, rather than set all blocks to 0, but this will require a proc of some sort to check if there are divergences from a standard mutational state.

**Comment by Fox-McCloud** [comment]
Meh, @Crazylemon64 does have a point. I dunno.

**Comment by Tastyfish** [comment]
Well, they shouldn't be changing your species :P
