### ISSUE TITLE
Assorted PAI bugs.

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4032]
This is a list of several bugs relating to PAI's.

Firstly:
Click-Dragging a PAI foxsprite in the Resting position onto a character results in the PAI totally vanishing. They have no hold sprite in inventory or on a character's person and are unclickable/undroppable. The PAI can type Resist to go back to mobile form and become visible again.

Expected is for it to held like is normal for PAI's. The normal cute fox on shoulder sprite. Not to temporarily vanish as a game object like what did occur.

Consequences are PAI's using the fox chassis functionally vanish as game objects when picked up in a resting position. Not a major issue but there is the potential of causing problems codewise, no idea on that.

Reproduction steps: Get a PAI. Have PAI take fox chassis. Have PAI type 'rest' Attempt to scoop up PAI via clickdrag.

~

Issue 2!

PAI cannot access chat rooms whatsoever even if invited due to lacking a PDA interface.

Specifics are pretty straightforward. Main issue is they cannot join pda chatrooms period. This specific bug was stated by the PAI I encountered the first bug with. Cause is probably how PAI PDA's are handled. Issue may or may not be present with AI/borgs as well. Unknown and have not tested.

~

Issue 3!

PAI cannot shift click to examine or examine in general while being held or riding on someone's shoulder. Minor issue, pretty straightforward as to what it is. I imagine it's an issue for maint drones being carried or worn as hats as well. Maybe nymphs also. Again minor but annoying.

~

Request from PAI player that the first issue was discovered with:

Prevent random blokes from wiping. Make it so only the PAI's imprinted Master can wipe a PAI.
I honestly agree with the suggestion, it's sorta a dick move for people to do that and since it's something that can be done to players, it's just bad. It's functionally one click to kill a player.

**Comment by Crazylemon64** [comment]
Perhaps it might be better to split these issues into different responses, so that we can check them off one-by-one.

**Comment by Kevak** [comment]
Prolly a good idea. Shall I go do that?

**Comment by Crazylemon64** [comment]
Go for it!

**Comment by Kevak** [comment]
Alright, done, go ahead and close this.
