### ISSUE TITLE
Vanishing PAIs.

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4033]
Splitting the issues up for coder convenience:

Click-Dragging a PAI foxsprite in the Resting position onto a character results in the PAI totally vanishing. They have no hold sprite in inventory or on a character's person and are unclickable/undroppable. The PAI can type Resist to go back to mobile form and become visible again.

Expected is for it to held like is normal for PAI's. The normal cute fox on shoulder sprite. Not to temporarily vanish as a game object like what did occur.

Consequences are PAI's using the fox chassis functionally vanish as game objects when picked up in a resting position. Not a major issue but there is the potential of causing problems codewise, no idea on that.

Reproduction steps: Get a PAI. Have PAI take fox chassis. Have PAI type 'rest' Attempt to scoop up PAI via clickdrag.

**Comment by TheDZD** [comment]
Might want to re-name the issue reports to better reflect what each individual issue is.

**Comment by Kevak** [comment]
Kay. One moment~

**Comment by Crazylemon64** [comment]
![works_for_me](https://cloud.githubusercontent.com/assets/5661700/21791375/28eeeb9c-d697-11e6-993b-0c8086694c26.png)
