### ISSUE TITLE
PAI Examining Problem.

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4035]
Issue 3!

PAI cannot shift click to examine or examine in general while being held or riding on someone's shoulder. Minor issue, pretty straightforward as to what it is. I imagine it's an issue for maint drones being carried or worn as hats as well. Maybe nymphs also. Again minor but annoying.

Easiest way to test is be a PAI and attempt to examine.

**Comment by TheDZD** [comment]
This might apply to any mob inside of an object inside of another mob.

**Comment by Crazylemon64** [comment]
It applies to all mobs not directly in a turf. I believe it has something to do with the client eye, probably could do a get_turf() compare on both and find out if you're really just on the same tile.
