### ISSUE TITLE
Somehow, a stethoscope will allow you to hear an IPC's pulse and respiration

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4051]
Using a stethoscope on an IPC will give you the message "You place the stethoscope against her chest. You hear a healthy pulse and respiration.", despite IPCs lacking lungs or a heart.

Literally unplayable.

**Comment by Necaladun** [comment]
Clearly IPCs have a small speaker there to mimic those sounds, so they can comfort cats while cuddling them.

WAD?

**Comment by NTSAM** [comment]
electrical pulse
