### ISSUE TITLE
Begone Bucket Chemistry!

### ISSUE THREAD

**Issue by QQCucumber** [ParadiseSS13/Paradise#4055]
Right now, skilled chemists are dependent on buckets. Their 120u capacity is actually quite a big step over the 100u capacity of large beakers, because most recipes come in multiples of 3. Meaning the next step up from 90u is, yes, 120u!

Buckets just don't fit the chemistry theme, they don't display chemical graphics that make chemlabs look like colorful deathtraps, and when you insert them into chemistry machines they temporarily turn into beakers because there's no graphics for putting a bucket in one.

**Here's what this change would be, in a nutshell:**
Make Large Beakers hold 120u.
Buckets can no longer be used with chemlab equipment.

**Lower priority:**
Small Beakers hold 60u.
Buckets can hold more, since they're logically larger than large beakers.

**Comment by FalseIncarnate** [comment]
Feature requests are meant to be posted on the forums, not the issue tracker.

**Comment by QQCucumber** [comment]
That's disappointing. Alright.
