### ISSUE TITLE
Disease Stealth Values are off

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#4069]
**Problem Description**:
Assuming that Fox's update of the Wiki is correct, then the stealth values for certain symptoms are incorrect.

**What did you expect to happen**: 
I added Viral Self-Adaptation, Viral Evolutionary Acceleration, Eternal Youth, Spontaneous Combustion and Necrotizing Fasciitis to a viral sample, for a Stealth Value of 0. This should be visible to scanners and the Pandemic machine.

**What happened instead**:
It was visible to the Pandemic machine, but NOT the scanners.

**Why is this bad/What are the consequences:**
Well, if the values are incorrect, then the math cannot be correct, making precise custom viruses nigh-impossible in terms of, at least, stealth.

**Steps to reproduce the problem**:
See the above symptom list.

**Comment by Fox-McCloud** [comment]
This is a wiki problem, not a code problem, I'm pretty sure.

Virology has been stagnant for literally years, on TG---recently it received several major changes---the wiki hasn't caught up with that. Our guide to Virology is literally copy-pasted from TG, with the only change being diphenhydramine swapped out for synaptizine.
