### ISSUE TITLE
no surgery option to remove implants from the head

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#4074]
implant removal doesn't show when aiming for the head, so removing CNS rebooters is impossible, unless I'm missing something here

**Comment by Fox-McCloud** [comment]
Those are augments, not implants.

Implants are the tiny little things in the glass implant cases---augments are the things you need organ manipulation to remove.

**Comment by pinatacolada** [comment]
ech, i'm dumb, then it's probably working fine, didn't try that one
