### ISSUE TITLE
IPCs can be affected by welding without goggles

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#4084]
**Problem Description**:
IPCs get momentarily blinded when using a welding torch without goggles.

**What did you expect to happen**: 
To not be affected by welding torches in any way, since that's how it normally is.

**What happened instead**:
Welding torches blinded me for a moment. My screen filled white, but regained color rapidly. It did no damage to my organs - the problem is purely visual.

**Why is this bad/What are the consequences:**
One of the benefits of being an IPC is that welding torches can't blind you.

**Steps to reproduce the problem**:
1. Be an IPC.
2. Get a welding torch.
3. Turn it on and use it on anything, such as a normal wall to try to deconstruct it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was mixing chems and blew myself up by creating 90u of phlogiston. I was temporarily blinded and deaf (deaf lasted longer), but I **did not** lose my head. After getting fully repaired and regaining my vision and hearing, I tried to use a welding tool and became blinded for a few seconds. Future uses had the same effect of momentary blindness.

**Comment by tigercat2000** [comment]
Not a bug. 
Anything that lacks proper eye protection will be flashed when they weld something. This flash is only a visual overlay, it does nothing more.

**Comment by ProperPants** [comment]
Alright, not a bug I guess... It used to be that IPCs didn't need welding goggles at all, ever, period. It must have been changed.
