### ISSUE TITLE
Drone UI

### ISSUE THREAD

**Issue by Keilden** [ParadiseSS13/Paradise#4086]
**Problem Description**:
What is the problem?
Drones lack a UI when the module window is used. You only see the icons.
**What did you expect to happen**: 
Why do you think this is a bug?
Last time I was a drone they had a UI.
**What happened instead**:
How is what happened different from what you expected?
There was no UI.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Well for one it looks ugly but it can be hard at times to see you modules.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Be a drone, open module.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing more to tell  Edit: Also after playing some more the icons went away also, I can't pick any modules now.

**Comment by TheDZD** [comment]
Could somebody post a screenshot of this?

**Comment by Crazylemon64** [comment]
I was a drone, opened module, UI opened dandy. Any further info?

**Comment by Keilden** [comment]
Joined as a drone today and did not have any problems, no idea what went wrong that time.
