### ISSUE TITLE
pAI MULEbot safeties do nothing, NOTHING I SAY!

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#4087]
Even being a round-start MULE, with no wires cut, you can kill someone by running them over if they're lying down. This is particularly hilarious if you put someone on top of you by cutting your weight limit wire, as this makes it make them take 15-30 damage every single time you move.

**Comment by monster860** [comment]
wowwwwww.

**Comment by Spacemanspark** [comment]
This isn't a bug, normal MULEbots do this too.
Trust me, you find this out after you stand in front of a normal MULEbot and a random security officer comes over and batons you, fleeing as he realizes his mistake.

**Comment by monster860** [comment]
If they had safeties, they should stop when they see lying people.

**Comment by Spacemanspark** [comment]
Your fault for being in the MULEbots way.

**Comment by tigercat2000** [comment]
not a bug

**Comment by Tastyfish** [comment]
Yeah, the lying people thing has _always_ been the case; that said, being harmed while loaded is obviously a bug.

**Comment by fludd12** [comment]
*shrug*
