### ISSUE TITLE
Securitron icons half-work

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#4089]
Up to the point where you weld the hole for the proximity sensor the icon stops changing and you can't easily tell what step you are on. It still says in its description where it is but then it's annoying when you have a stack of them on a table together. Also when the assembly is made to the arm attachment stage the name breaks and it says, "That's a helmet/signaler/prox sensor/robot arm assembly."

**Comment by Tastyfish** [comment]
I just tested it, and the icon correctly changes on every step. Can you provide any more details?

Also, I'm not clear on what the problem is on the last statement; that is the correct name for the assembly at that stage.

**Comment by taukausanake** [comment]
I'll try again later, but I didn't see the icon for the welded hole

**Comment by taukausanake** [comment]
Well maybe it was just me or something. Okay, closing
