### ISSUE TITLE
AI antechamber guns spam the bots in there

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#4091]
**Problem Description**:
The guns in the AI antechamber shoot the bots, pingsky, the floorbot, and the cleaner bot, without seeming to want to stop

**What did you expect to happen**: 
the turrets to calm down like they always were

**What happened instead**:
they kept on shooting

**Why is this bad/What are the consequences:**
drains power and sounds horrible

**Steps to reproduce the problem**:
look at the antechamber

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
The admins told me it was because they were changed to become mobs instead of other stuff

**Comment by Tastyfish** [comment]
Amusingly, I just posted a PR fixing this.

**Comment by jguy555** [comment]
and it was fixed a second before posting this

**Comment by Tastyfish** [comment]
Yeah, you could actually keep it open and I could link it in the PR.
