### ISSUE TITLE
 ChemMaster 3000 interface is quite slow

### ISSUE THREAD

**Issue by YeAdventurer** [ParadiseSS13/Paradise#4092]
Oh, I know, all the web interfaces you have to use on BYOND are subject to lag, but I've noticed the ChemMaster in particular is much, MUCH laggier than all the other web interfaces. There's always a consistent delay when using the buffer or toggling whether the buffer should go to disposal or the beaker.

Also, as an aside, it'd be nice if it could support more then 100u.

**Comment by monster860** [comment]
@Fox-McCloud @TheDZD This was fixed in the asset-cache and nanoui PR's for chem-master
