### ISSUE TITLE
Camera monitors doesn't work

### ISSUE THREAD

**Issue by PrototypeNitro** [ParadiseSS13/Paradise#4093]
**Problem Description**:
No cameras detected on Security Checkpoint Camera monitor

**What did you expect to happen**: 
Because no cameras Detected

**What happened instead**:
All the times.

**Why is this bad/What are the consequences:**
Not important but I report it.

**Comment by Spacemanspark** [comment]
What job were you at the time?

**Comment by PrototypeNitro** [comment]
Security officer

**Comment by TheDZD** [comment]
There's a good chance that the cameras there were just disabled, as there's a slight chance a camera starts off broken at the beginning of the round.
