### ISSUE TITLE
Possible Chaplain/cult Holy Sword/Nullrod interaction nonfunctional.

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4099]
**Problem Description**:
Chaplain Holy Sword appears to not negate AOE cult runes and directed tailsmans as it should due to being a Nullrod derived item. Problem cropped up during testing of random cult stuff on a private server using current paracode. Checked the github after the fact and it appears as though only Nullrod is included in the list of items that prevent cultmagic from affecting mobs.

**What did you expect to happen**: 
Expected is a holy sword wielder remains unaffected when bloodboil, stun, deafen, and blind are cast. Or when they are paped with tailsmans.

**What happened instead**:
Holy sword wielder was fully affected by the previously mentioned runes and tailsmans. As HS is a variant of the Nullrod. Something is wrong here.

**Why is this bad/What are the consequences:**
Chaplains/paranormal ERT members converting their nullrods into Holy Swords put themselves at a major disadvantage against cultists.

**Steps to reproduce the problem**:
Grab Nullrod. Convert into Holy Sword. Be papped with a stuntailsman or have a cultist cast an AOE rune near you. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Testing took place on a private server during recording of an upcoming videobased cult guide. Chaplain volunteer was also wearing the full Crusader Armor and remained affected. Of note, Holy Sword does function as a Nullrod when used to remove cultrunes, so that bit is working at least.

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Kyep** [comment]
@AffectedArc07 Issue needs closing. Tested on live server, found holy claymore DID absorb it:
Nalkirrrka Hadii's holy weapon absorbs the talisman's light!
