### ISSUE TITLE
The turrets in the AI sat antechamber constantly fire at Officer Pingsky

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4101]
Unless they're turned off, of course.

I assume that they would fire at any of the bots, but this is pretty much the only situation where it really matters.

**Comment by Fox-McCloud** [comment]
Should be fixed already, just, ya know...lack of patching and all.

**Comment by LittleBigKid2000** [comment]
I'll go ahead and close it, then
