### ISSUE TITLE
Ctrl-T does not open the Say window

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#4103]
When you're in the default mode, aka the not-hotkey mode, you're supposed to be able to access the hotkey mode hotkeys with ctrl + the hotkey. However, this isn't functioning with opening the Say window. You can just use the input box, but since that doesn't cause the typing notification to appear on your character, that's not the best solution.

**Comment by YeAdventurer** [comment]
It seems 'Me' has the same problem.

**Comment by Ar3nn** [comment]
Say, Me and OOC have F key bindings additionally. OOC is F2, Emote is F3 and I believe Say is somewhere between F4 and F7. there being some asay and msay in-between.
