### ISSUE TITLE
Getting damaged does not seem to interrupt getting inside an exosuit

### ISSUE THREAD

**Issue by YeAdventurer** [ParadiseSS13/Paradise#4106]
So it was a really interesting round of SS13. I managed to barge in on a syndie mending their durand and I opened fire with my laser gun, hitting them in the chest. Only to my surprise that after the repeated shots they were still able to get into the exosuit just fine, it didn't interrupt them or anything like most actions that typically require the progress bar.

This doesn't seem like it would be intended.

**Comment by TheDZD** [comment]
Only stuns and movement stop actions such as that, not damage.
