### ISSUE TITLE
Turrets fire at bots such as pingsky

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#4108]
**Problem Description**:
What is the problem?
Turrets fire at bots such as pingsky
**What did you expect to happen**: 
Why do you think this is a bug?
Because they are not supposed to fire at bots
**What happened instead**:
How is what happened different from what you expected?
..
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because it keeps turrets such as the AI turrets constantly busy
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
As far as I could tell, just look at the AI sat at roundstart, if not then try forcing malf AI
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by FlattestGuitar** [comment]
I'll just leave this here... [#4101](https://github.com/ParadiseSS13/Paradise/issues/4101)

**Comment by Regen1** [comment]
It's been 3 days without matching? sheesh

**Comment by TheDZD** [comment]
Already fixed, but no patch, yeah.
