### ISSUE TITLE
Diona killed with Plant-B-Gone Defibs back to 100% HP on HUD

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#4120]
**Problem Description**:
Diona killed with Plant-B-Gone revives to totally fine status upon Defib

**What did you expect to happen**: 
Needing healing after being defibbed and having over 100 toxin damage.

**What happened instead**:
Died to death-spray, got hauled to medical, and got de-fibbed to 100% health. Climbed out of the cryopod they threw me in, picked up a health analyzer, and walked out with 106+ toxin damage in my system but 100% hp on my HUD.

**Why is this bad/What are the consequences:**
Probably should have to heal dionae after defibbing them, otherwise the death spray is sort of null.

**Steps to reproduce the problem**:
Spray Diona with Plant-B-Gone at least twice, defib, check diona's toxin damage and HUD for discrepancies.

**Comment by farie82** [comment]
Checked and not the case anymore.
