### ISSUE TITLE
Capulettium Plus does not work.

### ISSUE THREAD

**Issue by YeAdventurer** [ParadiseSS13/Paradise#4121]
Capulettium Plus is supposed to have all the effects of Capulettium plus silence. However, it instead has NONE of the effects of Capulettium and ONLY silences you.

**Comment by Fox-McCloud** [comment]
Um, no.

Capulettium plus is supposed to make your heart stop (according to health analyzers, examination, or checkign pulse) and silence you---it does do this.

Capulettium is a drug that knocks you out (and makes you *deathgasp right before you get knocked out) and makes your heart stop (again, according to health analyzers, examination, or checkign pulse)

**Comment by YeAdventurer** [comment]
Ah. Sorry for the misunderstanding...

**Comment by Fox-McCloud** [comment]
It's no big deal--chemistry is vast and complex and it's easy for misconceptions about X chemical to get passed around, too.

**Comment by Bigtimetripod** [comment]
There was a bug that Capulettium plus didn't silence, but that has been fixed. As a semi chem expert, i can say that its working as intended.
