### ISSUE TITLE
An IPC without a monitor head can still get the "smashing their own monitor" suicide message

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4122]
Suicided as an IPC with a Bishop Cybernetics head, got "X is smashing their own monitor! It looks like they're trying to commit suicide." message. 0/10 literally unplayable.

**Comment by NTSAM** [comment]
morpheus masterrace

**Comment by tigercat2000** [comment]
this would require snowflaking IPC's into the suicide code just to prevent one message
no

**Comment by LittleBigKid2000** [comment]
But I like reporting insignificant issues

**Comment by Fox-McCloud** [comment]
Pretty much what @tigercat2000 said.
