### ISSUE TITLE
I somehow started puking as an IPC after getting drunk and blowing my head off

### ISSUE THREAD

**Issue by Little-119** [ParadiseSS13/Paradise#4124]
I completely filled myself with synthahol and blew my head off with a russian revolver. After I got my head reattached, I started puking.

**Comment by FlattestGuitar** [comment]
I cry now. I shall investigate.

**Comment by FlattestGuitar** [comment]
Did you drink any more synthanol after the head got reattached?

How long did it take for you to start puking after it got reattached?

Have you drank any normal alcohol at all during that process?

**Comment by LittleBigKid2000** [comment]
I just found out that they may have attached an organic head to me. Still weird, as IPCs lack a stomach.

No

Almost immediately, I think

I only drank synthahol and synth 'n soda during the shift, maybe a bit of cola.

**Comment by LittleBigKid2000** [comment]
Yep, they attached an organic head. My real, synthetic head was on the floor when they just put me in a spiderbot.

I wonder if this counts as ic in ooc, since it's the current round

**Comment by FlattestGuitar** [comment]
Welp, that explains it.

An organic organ will make a mob return a 0 on `isSynthetic()` call, and that means they'll puke violently when drinking synthanol. Not really sure what to with this one.

On the plus side, this also makes normal alcohol work with human-headed IPCs, so that's fun.

**Comment by Spacemanspark** [comment]
You committed heresy against Synthetica!

**Comment by Fox-McCloud** [comment]
no longer a problem as the check is different.
