### ISSUE TITLE
Straight Jackets can be removed by the wearer.

### ISSUE THREAD

**Issue by Draconic-saint** [ParadiseSS13/Paradise#4128]
**Problem Description**:
What is the problem?
Straight jackets, can be removed by the wearer, if you click the exosuit slot instead of the jacket itself.

**What did you expect to happen**: 
Why do you think this is a bug?
Jacket's supposed to be unremovable

**What happened instead**:
How is what happened different from what you expected?

Jacket is now removable

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
See question 2.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Equip straightjacket, click exosuit slot, but NOT the jacket icon.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
If jacketed up, you can also remove other equipment by clicking the slot.

**Comment by YeAdventurer** [comment]
Yikes. That is a serious bug.

**Comment by FalseIncarnate** [comment]
https://github.com/ParadiseSS13/Paradise/pull/4111
Already fixed.

**Comment by Fox-McCloud** [comment]
>#4111
Already fixed.

**Comment by Draconic-saint** [comment]
Oh, didn't notice, my bad
