### ISSUE TITLE
Syndipets take oxygen damage.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#4133]
**Problem Description**:
Syndipets die in space.

**What did you expect to happen**: 
They shouldn't die in space from oxygen damage.

**What happened instead**:
I've always felt this field is redundant.
But they die in space without oxygen damage.

**Why is this bad/What are the consequences:**
Poor Syndipets.

**Steps to reproduce the problem**:
Be syndicat or syndifox.
Run into space
Die.

**Possibly related stuff**:
Why are they subtypes of corgies?

**Comment by TheDZD** [comment]
This is back again?

**Comment by Spacemanspark** [comment]
Apparently.

**Comment by Tastyfish** [comment]
This is actually a seperate issue from before, in that they're just resprites of cats, dogs, etc with no functional difference.
