### ISSUE TITLE
Borg 'Delete Image' is broken

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#4137]
I took a picture with my borg camera. While I able to view them normally (selecting 1, 2, etc) the option to delete says I have no saved images.

**Comment by Tastyfish** [comment]
The AI/borg cameras are really weird (badly coded), but essentially both the AI and borgs have photo storage. However, when the borg takes a photo or views them, they're using the AI's photo storage, if they have a master AI. The `Delete Image` verb, however, specifically acts on the current silicon's photo storage, which for a borg bound to a master, will be empty. It's just a really terrible interface but is ""technically"" working as intended.

**Comment by YeAdventurer** [comment]
I'm not sure I understand. What is the Delete Image verb good for then?

**Comment by Ar3nn** [comment]
That'd be very hacky. Just ask the AI to delete them?
