### ISSUE TITLE
Changeling ability 'Last Resort' bug.

### ISSUE THREAD

**Issue by Sotrennel** [ParadiseSS13/Paradise#4139]
**Problem Description**:
The changeling's ability 'Last Resort' causes byond to either freeze for 5 seconds, or crash byond altogether.

**What did you expect to happen**: 
I expected to turn into a brainslug.

**What happened instead**:
My game crashed the first time and froze for 5 seconds the other time.
**Why is this bad/What are the consequences:**
It ruins the ability, since lag is the thing you don't want to have when escaping.

**Steps to reproduce the problem**:
Use the last resort ability as a changeling when there are a lot of players on or processes going on.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I think the ability is resource intensive since it blinds you, makes an explosive noise and gibs you.

**Comment by Fox-McCloud** [comment]
Pretty sure this is just you or a BYOND issue, to be honest. Which version of BYOND are you using. not using 510 and playing on our server could cause issues.

We've seen many headslugs for a while now and have yet to receive complaints of this nature about them (doesn't meant they don't exist), but this sounds like a an issue specific to you as opposed to generalized. I experienced no such issues when I used the ability.

**Comment by Sotrennel** [comment]
The newest byond version.

**Comment by YeAdventurer** [comment]
Fox is wanting to know if you're using the latest stable or one of the betas. The server is running 510.1336 so for the best performance you should be using the latest beta.

**Comment by Sotrennel** [comment]
Ah, I'm using the stable version, that might be the problem.
