### ISSUE TITLE
Turrets count bots as enemies when set to lethal.

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#4140]
What is the problem?
Turrets shoot bots when set lethal, this makes them kill the bots in AI chamber too.

Why do you think this is a bug?
Officer Pingsky, Cleanbot and floorbot are AIs only true friends, not something you must exterminate.

How is what happened different from what you expected?
Turrets killed the poor bots 4noraisin

Why do you think this is an important issue?
Malf AI has less tools

The most important section. Review everything you did leading up to causing the issue.
Be AI, set turrets lethal, watch them exterminate your friends.

Anything else you can tell us.
Might be related to the pAI update

**Comment by Fox-McCloud** [comment]
How many times is this same issue going to get reported.

This has been fixed, but we haven't patched in forever.
