### ISSUE TITLE
Speech Bubbles Do Not Respect Alpha

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4161]
Simply put, speech bubbles do not respect a mob's alpha level, meaning that if someone with chameleon (or cloak of darkness or any number of invisibility spells) talks, their exact location will be revealed.

**Comment by tigercat2000** [comment]
not a bug in any way shape or form, the code is functioning perfectly, flick_overlay is doing it's job
this is a feature request
