### ISSUE TITLE
Thinking Is Optional: Syndicate Mindslave Edition.

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4163]
**Problem Description**:
Removed Mindslave Implants do not cancel the Mindslave status, the Mindslave Hud, or the Mindslave objectives. Possibly an issue with newsurgery.

**What did you expect to happen**: 
Upon removal of a mindslave, you would think you would be free to think for yourself.

**What happened instead**:
Mindslave status simply never was canceled on removal.

**Why is this bad/What are the consequences:**
It becomes impossible to free mindslaved people. That is clearly a problem.

**Steps to reproduce the problem**:
Get mindslaved. Get mindslave implant removed.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Nothing else of note.

**Comment by Fox-McCloud** [comment]
They've never removed antag status upon removal--this has nothing to do with new surgery at all.
