### ISSUE TITLE
Anomalies incapable of being stabilized

### ISSUE THREAD

**Issue by Dinarzad** [ParadiseSS13/Paradise#4167]
**Problem Description**:
Anomalies are not beign stabilized and dropping Cores when their frequency and Code is signalled

**What did you expect to happen**: 
I expected the Anomaly to stop existing and to drop a fancy core, instead it kept on existing and eventually blowing up as it normally did, despite me using 2 separate forms of signaling (PDA and a Remote Signaller Device) the Analyzed frequency and code.

**What happened instead**:
Instead of being taken care of, the Anomaly kept on keeping on, and exploded. This happened on two seperate anomalies in the same round. One Energy Flux and one Gravitational.

**Why is this bad/What are the consequences:**
It effectively means Anomalies are RNG "HAHA GET FUCKED" events that cannot be countered and means RnD cannot obtain or research Cores and Robotics can never build a Phazon ever again.

**Steps to reproduce the problem**:
Step 1: Anomaly spawns
Step 2: Analyze it
Step 3: Try to ping the frequency and make it stop doing the things.
Step 4: Cry when it doesn't stop doing the things.
This occured not only with me, as a Grey Cargo Technician, but a Kidan Quartermaster had the exact same problem. We both analyzed the core and both pinged it, and it never stabilized, just blew up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I was a Grey and a Cargo Technician, the round was kinda laggy due to a lot of explosions and atmospheric effects, but not laggy enough to have caused the problems listed, given it took well over 20 seconds from me pinging the anomaly for it to then blow up.

Not sure if just a fucked up round or if Anomalies are legitimately bugged up right now.

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, I know they were working about two weeks ago, as I deactivated one or
two myself, and I can't seem to remember any PRs altering them in the
meantime. That may just be me, or BYOND is acting up.

**Comment by Dinarzad** [comment]
This was just last night I think, but Iunno.
I haven't had another anomaly come up yet to see if it's just that one glitched up round, but if I found out either way, I'll likely make an addendum in here.
