### ISSUE TITLE
setting pAIs radio mic to on causes whispering to transmit on radio

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#4170]
**Problem Description**:
if a pAIs radio mic is on whispering as the pAI will send it to the radio

**What did you expect to happen**: 
using whisper to not transmit it to the public channel

**What happened insted**:
any whispering done by the pAI is broadcasted to the common channel

**Why is this bad/What are the consequences:**
setting microphone on should not cause whispering to be broadcasted to the common channel

**Steps to reproduce the problem**:
download a pAI, set transmit to on and have it whisper

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: was using say .w to whisper

**Comment by TheDZD** [comment]
Was the whispering person adjacent to, or on the same tile as the active radio?

**Comment by Joonasm** [comment]
the whispering person is the pAI itself, should have made that more clear in the orginal post, ill edit it now

**Comment by TheDZD** [comment]
Seems like this might not a bug then, unless it doesn't occur when humanoids whisper while holding an active radio, as whispers transmit to anything within a tile.

**Comment by Joonasm** [comment]
Normal speech doesn't transmit from the pAI or other people near, just whispering transmitted

**Comment by TheDZD** [comment]
Oh, I misunderstood what you meant. I thought that using whispering would would transmit over the radio much like Say does, but you're saying that it will always transmit if you use whisper, even if you don't include a ; at the beginning of the message?

**Comment by Joonasm** [comment]
yes, i was using .w to whisper and it transmitted to radio without the ; there like how it would if you had a normal bounced radio on you but for some reason doesnt transmit normal speech, "say .w hello" from a pAI will tranmit though it but "say hello" wouldnt, no idea if whispers from people you are being held from tranmit
