### ISSUE TITLE
pAI ED-209 Control Breaks

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#4175]
**Problem Description**:
Occasionally, pAIs become incapable of controlling ED-209s besides firing. There is rarely a pattern that I've observed as to when it happens.

**What did you expect to happen**: 
ED-209 control does not get suspended.

**What happened instead**:
A unicorn generates plasma rainbows.
(Actually, pAIs just stop being able to move in EDs)

**Why is this bad/What are the consequences:**
Your pAI stun machine gun becomes a stun machine turret. Slightly less effective. 

**Steps to reproduce the problem**:
I haven't been able to tell, really. So far, I've only seen it happen twice, once when a pAI was attacked by a xenobiologically animated blobbernaut, and a second time when I was inserted into an ED-209 with 97% health. As far as I can tell, this means it's damage related, but fixing the damage does not fix the issue.

**Comment by Fox-McCloud** [comment]
>A unicorn generates plasma rainbows.

Houston, we have a problem.

@Tastyfish

**Comment by FalseIncarnate** [comment]
Potentially can be closed as pAIs cannot be put into ED-209s anymore without var-edits to allow it.
