### ISSUE TITLE
There's a door in the labor shuttle dock that leads directly to space

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4177]
https://gyazo.com/4a959717a9332712e21068516910b818

How did this even happen? Why is it there? Who put it there?

**Comment by Fox-McCloud** [comment]
Seriously doubt this is there every round.

Please verify something is, in fact, a bug, before kneejerk submitting it as a report---that is to say, for mapping issues, in particular, make sure it persists for at least 2 rounds in the same, exact, location.

**Comment by LittleBigKid2000** [comment]
I've seen it before, several times. This is not the first time I've seen this. I see it in Dream Maker, too.

https://gyazo.com/615d712650b5d14b359ac80d20632c29

**Comment by LittleBigKid2000** [comment]
Now that I think about it, I could easily just fix the issue myself. Not sure why I reported it instead of just fixing it...

**Comment by Fox-McCloud** [comment]
...what the hell. Who...I don't even want to know.

**Comment by LittleBigKid2000** [comment]
I can't do this stuff at six in the morning, I'll fix it tomorrow if no one else does, I'm going to bed,

**Comment by Tastyfish** [comment]
must have been some mapping misclick..I guess
