### ISSUE TITLE
Roll-down-jumpsuit bug

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#4181]
**Problem Description**:
You can roll down your jumpsuit when cuffed. It also produces a really hot "DEBUG:atmos" message for whatever reason.

**What did you expect to happen**: 
To not be able to roll down jumpsuit and not get a debug message about a completely unrelated matter.

**What happened instead**:
I could roll it down and I got a debug message.

**Why is this bad/What are the consequences:**
Literally unplayable.

**Steps to reproduce the problem**:
1. Be handcuffed
2. Roll down jumpsuit
3. Profit

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was a traitor, prolly not related. Also, I was bucklecuffed.

**Comment by Spacemanspark** [comment]
Actually, I think all jumpsuits give that message when rolled down.
