### ISSUE TITLE
People who borgify because of a virus while inside an advanced scanner can't exit or be ejected.

### ISSUE THREAD

**Issue by Draconic-saint** [ParadiseSS13/Paradise#4191]
**Problem Description**:
What is the problem?
People who borgify because of a virus while inside an advanced scanner can't exit or be ejected.

**What did you expect to happen**: 
Why do you think this is a bug?
People get stuck inside scanners, that's not good.

**What happened instead**:
How is what happened different from what you expected?
I'd assume even borgs would be able to exit an advanced scanner if they entered through some weird circumstances.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
People getting stuck inside scanners like that is pretty annoying.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

A person with a disease that carried the borgification sympthon caused them to turn while inside an advanced scanner. He couldn't exit, nor could the medical personell remove him from the scanner.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
@tigercat2000

**Comment by Crazylemon64** [comment]
Basically the same thing as the spacepod item dropping bug - they're in the scanner, but lack a means of exiting

What does deconstructing the scanner do?

**Comment by tigercat2000** [comment]
@Fox-McCloud why are you pinging me
this happens because the human mob is deleted when it is robotified, therefore breaking the ref on advanced meds
not sure how we could exactly fix it, other than making robots spawn at get_turf(src), which isn't really ideal

**Comment by Tastyfish** [comment]
it probably should be at get_turf().

**Comment by KasparoVy** [comment]
Did you try screwdriver + crowbar on the scanner while they were stuck inside? I wonder what effect that would have.
