### ISSUE TITLE
Gateway never load

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4194]
Dunno if this is because a config wasn't implemented correctly or something broke due to map changes...regardless, away missions never load anymore.

@Tastyfish @Necaladun you two will have to collaborate on this.

**Comment by Necaladun** [comment]
For some reason the gate way missions weren't ticked. Will fix when home.

-----Original Message-----

**Comment by tigercat2000** [comment]
@Necaladun nonononono that's definately not the problem
ticking a map makes byond always shove it into memory, away missions are designed to be loaded by a dynamic loader, only one at a time

**Comment by Tastyfish** [comment]
@Necaladun Away missions are now in a config file, either in the main config folder, or as a backup in the config/example folder (named away_mission_config.txt). Guessing neca doesn't copy the config/example folder.

**Comment by caelaislinn** [comment]
Cabling, piping, disposals never worked with the maploader, and there might be issues with other stuff like APCs as well.

**Comment by Fox-McCloud** [comment]
>Cabling, piping, disposals never worked with the maploader

Uh, that all works just fine and has for a very very long time now. That's not the problem here; it was a config issue.

**Comment by caelaislinn** [comment]
Bay's version on live doesn't but it also doesn't have the latest updates from TG. Do you guys use away missions on live? I just spent a month updating it without checking TGs.
