### ISSUE TITLE
Cargo crates missing items.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#4195]
I ordered A contraband Crate, it didn't have any drugs in it.

Later I ordered a plasteel crate (20 pieces I think?) and it arrived completely empty.

I believe there are more but don't remember because at the time I thought I just lost the item, not realizing it was probably never there.

**Comment by Crazylemon64** [comment]
@GelatinousGlob That's a thing, you send the manifest back with a denied stamp in the crate if the contents don't match up, and you get a refund plus some bonus for catching a bad crate.

**Comment by GelatinousGlob** [comment]
Well that would have been nice to know, its not listed on the wiki and ive never even heard of it. But what about crates that are locked? I can't check locked crates. And why does it happen with 1/3 of my crates? Don't some crates lack a content list? It seems like a pretty terrible mechanic and im having a hard time believing anyone would want to code and implement it.

Also, isn't there only a single deny stamp at the desk? Inside cargo receiving there are only accepted stamps.

**Comment by QQCucumber** [comment]
@Crazylemon64 Jesus christ, cargo is worse than I thought.

**Comment by pinatacolada** [comment]
i think you can stamp it with anything, even the clown's stamp

**Comment by Crazylemon64** [comment]
@GelatinousGlob Large and locked crates don't get inventory errors - there can still be incorrect station and incorrect listed package amount errors, as well, though those have less direct effect.

**Comment by TheDZD** [comment]
Contraband crates [should](https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/supplypacks.dm#L1390) have a drug pill bottle, so I'm not sure what could be causing that, and have not been able to replicate this.

**Comment by Tastyfish** [comment]
To clarify for those not familiar with the error mechanic:
- There's a 5% chance the station destination is labelled incorrectly (still arrives, but it's a deniable manifest),
- There's also a 5% chance the items will be miscounted on the manifest (again, purely a paperwork error).
- However, also a 5% chance (this cannot happen to secure or large crates) for 1/10th, rounding up to 1, of the items to be missing in a crate.
- You get a refund for returning a denied manifest for any of the 3, even though only the last one is actually bad.
