### ISSUE TITLE
Arm malfunction inside spacepod loses item.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#4196]
Had a suspicious toolbox in the pod with me, slightly damaged robotic arm randomly shorts out dropping the item inside the pod making it irretrievable.

**Comment by tigercat2000** [comment]
this is more of a problem of "spacepods and mechs have no way to get items out of their contents"

**Comment by Fox-McCloud** [comment]
>this is more of a problem of "spacepods and mechs have no way to get items out of their contents"

Along with a billion other things.

**Comment by GelatinousGlob** [comment]
I figured, but thought I would post it anyways since i was already here.

**Comment by Fox-McCloud** [comment]
more or less a duplicate of: https://github.com/ParadiseSS13/Paradise/issues/3260
