### ISSUE TITLE
Janitorial Watertank Backpack

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#421]
The sprite for it and its Mister are missing, though the item functions perfectly fine (despite being invisible). It currently takes another person to remove it from a player's back, though, since you cannot unequip it without being able to see it.

**Comment by FalseIncarnate** [comment]
Is this limited to only the janitor variant or are all 3 missing?

**Comment by Fox-McCloud** [comment]
these all probably need recoded anyway; they're very old version (and kinda buggy) of the feature.

If updated, it could potentially mean better functionality sprayers (and allow us to give them to hydro/janitor/etc).

**Comment by ZomgPonies** [comment]
Fixed via 426
