### ISSUE TITLE
Thermal without fulfilling blood req

### ISSUE THREAD

**Issue by Quantomicus** [ParadiseSS13/Paradise#4211]
Basically this:

![](http://i.imgur.com/pJkoUoC.png)

![](http://i.imgur.com/v1IxGSi.png)

**Comment by CrAzYPiLoT-SS13** [comment]
Also, yes. I was a vampire, but had not obtained enough blood to have thermal.

**Comment by Bigtimetripod** [comment]
You could have named this, without required amount of blood, vampire has thermal vision.

Thermal=Able to see warm bodies and silicons thru walls.
X-ray= able to see thru walls.

If that was getting you confused.

Was a vamp yesterday night and i didnt have this.
