### ISSUE TITLE
Very large PDA group chats causes telecomms to echo

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#4214]
**Problem Description**:
If a PDA chatroom has enough invites sent, telecomms starts to echo what you say, and even more weird, you only actually say something after the second echo, which takes like 2 or 3 seconds to happen.

I think this might be more clear
![asdt](http://puu.sh/ojIQU/94a2dc9867.png)

reseting the servers seems to do nothing to fix it, but I haven't tested that personally

**Comment by Tastyfish** [comment]
Extremely strange if true.

**Comment by TheDZD** [comment]
Not sure if chat rooms are the cause, but this is definitely a thing that happens.

**Comment by Fox-McCloud** [comment]
I've seen it happen a few rounds---it doesn't happen all the time, and I really have no idea what causes it, either---I suspect t-commscript screwiness, but I'm not sure.

**Comment by Spacemanspark** [comment]
I've seen this happen WAYYYYYYYY before the chatrooms were ever added. A few years ago.

**Comment by pinatacolada** [comment]
i was saying it's the chatrooms because the last 3 or so times it happened, it happened at the same time a huge chatroom was created

**Comment by MarsM0nd** [comment]
I just also had this, and it was not Tcomms, to early for someone to mess with it.

**Comment by Vivalas** [comment]
Wasn't this glitch or something very similar to it reporter before/fixed? I very strongly remember something along these lines. I've seen this glitch too before chatrooms.

**Comment by Tastyfish** [comment]
The echoing is a general symptom of something lagging it down, I believe.

**Comment by variableundefined** [comment]
Chatroom got nuked
