### ISSUE TITLE
Embeded object removal on dead people

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#4217]
**Problem Description**:
I did want to remove the unknown object inside the chest of a dead Tarajan for identification. But the removal steps which needs an empty hand does only start CPR

**What did you expect to happen**: 
Empty hand on the open chest starting the removal

**What happened instead**:
I started CPR, or got messages why it wouldn't work (Remove your Mask, They don't have a mouth)

**Why is this bad/What are the consequences:**
If someone get's killed from bullets and isn't revived/revivable , you can't remove and identify the bullets.

**Steps to reproduce the problem**:
Kill someone with bullets, clone him or make the body otherwise unable to get revived with a defib or strange reagent.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The bullets where from the syndicate outpost, subject was cloned prior to surgery, tried to do it without the head connected to the body.

**Comment by FlattestGuitar** [comment]
Rip, @Aurorablade.
