### ISSUE TITLE
Death Alarms and Brig cells in the AI law List.

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#4218]
Death Alrams and Brig cells are showing up in the AI law list after they go off..and for each time they go off

**Comment by Tastyfish** [comment]
Sounds like somehow radio.autosay()... is adding them to the law list? I don't even.

**Comment by Tastyfish** [comment]
I'm unable to reproduce it though.

**Comment by Fox-McCloud** [comment]
fixed by Crazy, at some point
