### ISSUE TITLE
Plasmaman Security

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#4225]
**Problem Description**:
Plasmamen security officers don't spawn with the sec hud or the taser.

**What did you expect to happen**: 
That upon spawning I would have a taser and a sec hud.

**What happened instead**:
Are these not the basics for security officers? Plus, if the warden/HoS/Captain are busy, chances are that I will end up going the shift without a key part of the sec officer equipment, the taser.

**Why is this bad/What are the consequences:**
Really doesn't promote playing as a sec officer as a plasmaman

**Steps to reproduce the problem**:
Step 1. Log on to server.
Step 2. Click Join Game
Step 3. Join as a Security Officer
Step 4. Problem

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Every game mode. Spawning.

**Comment by pinatacolada** [comment]
duplicate of #4071, but you don't start off with a HUD, only the HOS does
