### ISSUE TITLE
IPCs can be humanized V2

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#4234]
**Problem Description**:
By using a certain sequence of transplants and amputations, IPCs can be made into an organic.
The problem according to tigercat is that the head transplant works when the brain is in the chest

**What did you expect to happen**: 
IPCs use posibrains which shouldn't allow trans-speciesm with organics. The head is supposed to pop off with the IPC still in their body.

**What happened instead**:
The head pops off and keeps the IPC's consciousness with it. Since the head transplant works with the brain in the chest this happens

**Why is this bad/What are the consequences:**
IPCs can be turned organic which really doesn't seem right as they use posibrains, not organic brains.

**Steps to reproduce the problem**:
1) Cut off IPC head
2) Put organic head on
3) Cut off organic head
4) Put head on organic body
5) Revive body
6) wait why the fuck can robots be organic

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The process instructions were handed to me by a scientist player. also im half-awake so just tap me on the shoulder if something in here is unintellignabel or whatever

**Comment by tigercat2000** [comment]
ignoring the entirely irrelavant info, the problem here seems to be head transplants working when ipc brains are in the chest

**Comment by Spacemanspark** [comment]
Oh you got to it before I could.

**Comment by NTSAM** [comment]
sorry again

**Comment by jughu** [comment]
@tigercat2000  can this be closed?

**Comment by taukausanake** [comment]
NEVER FORGET
