### ISSUE TITLE
Large Cardboard Box OP

### ISSUE THREAD

**Issue by Cotux34** [ParadiseSS13/Paradise#4235]
**Problem Description**:
Cardboard boxes protect you from all sorts of damage, I got EMP'd in one and didn't take damage. It also makes you move faster if you have a missing foot etc.

**What did you expect to happen**: 
Should die if EMP'd in a cardboard box, it shouldn't have high movement speed if missing limbs/slowed otherwise

**What happened instead**:
EMPs didn't effect me inside it, I was also almost in crit but I could move arguably faster while in the box with a missing foot.

**Why is this bad/What are the consequences:**
It prevents people from killing you with EMPs and whatnot.

**Steps to reproduce the problem**:
Step 1. Get in large carboard box
Step 2. Get EMP'd
Step 3. Don't die
Step 4. If you have a missing foot/are slowed down, move normally, you'll have a higher speed.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not really

**Comment by tigercat2000** [comment]
- EMP's don't affect anyone inside almost all objects
 - It's only really faster when you're incredibly injured

**Comment by Fox-McCloud** [comment]
A lot of stuff that impacts mobs inside containers isn't recursive--this goes for explosions, EMPs, and the likes. This isn't really a bug per se, but it's certainly a quirk with closets (which is what the cardboard box is).
