### ISSUE TITLE
Sentient mining drones cannot move

### ISSUE THREAD

**Issue by QuinnAggeler** [ParadiseSS13/Paradise#4237]
**Problem Description**:
Sentient mining drones lose the ability to move when damaged, but cannot be repaired consistently, and do not regain the ability to move even if rejuvenated by an admin.

**What did you expect to happen**: 
Sentient mining drones to move, and be repairable via welder.

**What happened instead**:
Attempting to repair the drone with a welder brought up the message "The nanotrasen mining drone is moving around too much to repair!" despite it lacking the ability to move.

**Why is this bad/What are the consequences:**
Players in mining drones are left permanently immobile, miners cannot repair their drones when needed.

**Steps to reproduce the problem**:
Turn a mining drone sentient with an AI upgrade from the mining vendor
Damage it to 30hp or lower
Attempt to repair it with a welder

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
Game mode was vampires
Mining drone most likely inflicted the damage upon itself via drilling
Mining drone had been teleported via telepad at least once

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
Were you pulling the drone, per chance, or were there any hostile mobs around?

**Comment by QuinnAggeler** [comment]
No hostile mobs, but it had been pulled prior to the teleportation
