### ISSUE TITLE
Xenobiology Plasma injections Not working.

### ISSUE THREAD

**Issue by Fhufuu** [ParadiseSS13/Paradise#4240]
**Problem Description**:
Most if not all Plasma Injection on slime extracts are not working.

**What did you expect to happen**: 
That the slime extract would give what they'd drop after being injected by the plasma.

**What happened instead**:
No Item spawn from injection.

**Why is this bad/What are the consequences:**
You cannot use the full extent of Xenobiology. Like the intelligence potion.

**Steps to reproduce the problem**:
1: Get slime extract of which require plasma injection
2: Try to inject it.
3: See that it is not working/should be working

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Extended, Secret. Both of the modes.

**Comment by QuinnAggeler** [comment]
Was it liquid plasma from a chem dispenser, or plasma dust?

**Comment by Fox-McCloud** [comment]
Plasma from the dispenser (liquid plasma) doesn't work.

You must use plasma dust, which is only acquired by grinding plasma sheets.

**Comment by Fhufuu** [comment]
To @QuinnAggeler : Liquid Plasma. Sorry I thought there was one plasma type to inject it.

@Fox-McCloud : Oh... I guess this would explain why it hasn't been working for us... Thank you good sir.

**Comment by Fox-McCloud** [comment]
@Fhufuu 

I've updated the wiki to reflect that it has to be plasma dust *specifically* and not liquid plasma.

**Comment by Fhufuu** [comment]
@Fox-McCloud You really did... Well, This was for a friend but also sorta me cause I like being harmless xeno. Anyways. Apologies for taking you guys's time. Thank you very much.
