### ISSUE TITLE
Tables spawn disconnected despite being right next to each other.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#4242]
**Problem Description**:
Tables at round-start are spawning using the wrong sprites so that they don't look like they're connected to tables right next to them.

**What did you expect to happen**: 
For tables constructed (or spawned at round-start) to be connected to each other if they're in adjacent tiles.

**What happened instead**:
In the white ship the tables by the main control console as well as in the upper right part of the room looked disconnected despite being in adjacent tiles.

**Why is this bad/What are the consequences:**
Mild issue, doesn't effect gameplay but still looks wonky.

**Steps to reproduce the problem**:
Load up the map, look at any room with multiple tables adjacent to each other.  Only noticed this with regular metal tables, not wood tables, glass tables, or plasteel-reinforced tables.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I first noticed the issue in the Mechanic workshop but figured it could just be a one-off thing.  When I found the white ship later in the round the tables on board were the same way and I knew that nobody else had been on board as all the regular loot was in its proper place.

Screenshot of the bridge of the white ship.  The tables in the lower left are untouched, the tables in the upper right I deconstructed (the middle one, at least) and reconstructed which fixed the issue.
https://i.gyazo.com/f3f31949e9f4a16844d44bfd3cbd17d4.png

**Comment by CrAzYPiLoT-SS13** [comment]
You wasted the maymay :(

**Comment by Crazylemon64** [comment]
(╯°□°)╯︵ ┻━┻
