### ISSUE TITLE
Most of the smartfridges are unbuildable

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#4251]
**Problem Description**:
We have a board (1) for a fridge.
We have five (5) different fridges that accept only their dedicated stuff.
4/5 fridges unconstuctable.

**What did you expect to happen**: 
Fridge to not be so damn picky about what I stick in it.

**What happened instead**:
Fridge was like my lovelife and didn't let me stick my stuff in

**Why is this bad/What are the consequences:**
Not only is it extremely confusing to figure what this picky little fridge wants, it also makes all other fridges be nonconstuctable.

**Steps to reproduce the problem**:
Get board from RnD, make fridge, try putting medicines in. No can do. Cry.

**Comment by KasparoVy** [comment]
Just leaving this as an idea: Multitooling the fridge board to select which fridge gets built

**Comment by Iamgoofball** [comment]
Why don't you just make smartfridges by default accept everything

**Comment by FalseIncarnate** [comment]
Fixed with #4258 but never closed
