### ISSUE TITLE
Mimes and pAIs(Not a bug.)

### ISSUE THREAD

**Issue by Fhufuu** [ParadiseSS13/Paradise#4252]
**Problem Description**:
pAIs cannot see Actions and such.. Emotes if you will unless they are physically out and looking at the Emot'er'. 

**What did you expect to happen**: 
that the pAIs should be able to see the actions of the mime From their pockets/Bag.

**What happened instead**:
It... Kinda sucks that you can't exactly communicate with your master at the risk of being taken away for some prank or other random uses..

**Why is this bad/What are the consequences:**
I mean... Its not bad really... Im just omitting something. 

**Steps to reproduce the problem**:
1:Get a pAI.
2:Do an Emote
3:pAI doesn't see it unless Unfolded.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Any kind of game mode really since pAIs are always there.

**Comment by Crazylemon64** [comment]
Wrapped mobs don't see "visible_messages", which is what emotes work with, as opposed to speech. (Meaning, this is a problem for MMIs, intellicards, and mechs, too).

**Comment by Spaghetti-bit** [comment]
Not a bug.
