### ISSUE TITLE
It's possible to obtain nanomachines.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#4256]
I'm not sure if this has been overlooked or what exactly happened here, but a lot of people said this is definitely not the way it used to be and it seems incredibly powerful to me. A chef tator will never be the same.

If you make a roboburger, you get 10u of nanomachines in it - the reagent that gives people the robot transformation disease. Once you nom on it, you get about 30 seconds to get yourself scanned in a cloner or you are stuck as a borg until the end of the round.

I have been told the reagent used to be an admin-spawn only thing, which simply isn't the case anymore.

Overlooked in a code update?
Actually intended?

Dunno, just putting it out there.

**Comment by Regen1** [comment]
uuh @Fox-McCloud Didn't you readd them in the virology update?

**Comment by FlattestGuitar** [comment]
Yup, it was added [here](https://github.com/ParadiseSS13/Paradise/commit/560eb17f9dfc24e20813f13301ebd76b30269038#diff-45fdc424d866da8ca3f18061c8abc66dR861) along with disease1. I'll make a quick PR to remove it.

**Comment by Crazylemon64** [comment]
@FlattestGuitar Are you sure you're not confusing these with NANITES? Those were found in the "Giant Roburger", and were functionally adminordrazine, which we were noticably concerned about. There's already the black slime toxin from xenobio, so this doesn't seem TOO out of line...

**Comment by FlattestGuitar** [comment]
No, Crazy, I am not. Look at the link I posted in my last comment. Nanomachines.

**Comment by Fox-McCloud** [comment]
Not a bug, not even remotely.
