### ISSUE TITLE
Virology fridge only accepts old virus plates

### ISSUE THREAD

**Issue by Glorken** [ParadiseSS13/Paradise#4259]
**Problem Description**:
The fridge in virology only accepts the old virus plates from before the switch back to disease1.

**What did you expect to happen**: 
I expected the fridge to take beakers and bottles in order to store viruses.

**What happened instead**:
The beakers and bottles were rejected.

**Why is this bad/What are the consequences:**
I have to throw all my bottles of symptoms on an unorganized table.

**Steps to reproduce the problem**:

1. Remove bottle from Virology fridge.
2. Try to put the bottle back into the fridge.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I even tried throwing the objects at the fridge!

**Comment by tigercat2000** [comment]
whoops
