### ISSUE TITLE
Slime Management Consoles Issue

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#4260]
**Problem Description**:
I was using one slime console, and accidentally clicked on the other. I ended having twice the number of icons for each console, then upon using the icon to exit the console, it bugged out. I ended up exiting both consoles, but one was still considered to be in use. I also had one set of slime console icons on my screen, except for the exit icon.

**Steps to reproduce the problem**:
Use one slime console. Use the the other. Exit one of them. RIP.

**Possibly related stuff**
Dumbdumn5 tried helping me from the admin side of things, so maybe he has some input. For some reason I can't use @ on his name.

![2016-04-21 19_16_35](https://cloud.githubusercontent.com/assets/16659022/14727266/46bf996a-07f7-11e6-9f75-49a289e07395.png)
![2016-04-21 19_16_13](https://cloud.githubusercontent.com/assets/16659022/14727267/46c9e2bc-07f7-11e6-8abb-6a48dc984a53.png)

**Comment by Fox-McCloud** [comment]
This should be improved after Abductors goes live because it has better handling for unsetting machines from users and properly calling things to clear stuff like this...buttt we haven't patched so. Going to close this for now. post here again if this problem persists *after* we patch in abductors.
