### ISSUE TITLE
Ranged Hostile Mobs Firing is Broken

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4269]
Ranged hostile mobs can only fire once, and that's it.

Simply put, if a ranged hostile mob fires even once, it is incapable of firing against---this impacts:

- Swarmers
- Stands
- Various other hostile mobs

This only impacts *player controlled* hostile mobs. Mobs that are functioning off of AI can fire as many times as they please and behave normally. I suspect between the hostile mob refactor with bees and moving some processing around with how that's handled, something may have broken.

May be related to: https://github.com/ParadiseSS13/Paradise/issues/4237

@Tastyfish @TheDZD @Fox-McCloud

One of us is most likely responsible for breaking this.

**Comment by Tastyfish** [comment]
Oddly this has been a thing for a very long time I think.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/hostile/hostile.dm#L47-L50>I found the bug, guys</a>

**Comment by Tastyfish** [comment]
I did first :stuck_out_tongue:

**Comment by Crazylemon64** [comment]
>:
