### ISSUE TITLE
Ghost AntagHUD doesn't work on round-start antagonists

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#4277]
**Problem Description**:
The "AntagHUD" for ghosts doesn't work on any antagonists that started the game as antagonists. It works for antagonists made via the traitor panel.
The antags in question have a `antag_hud = null` set on their mind datum, where one made by the traitor panel has a hidden atom_hud in a list.

**What did you expect to happen**: 
Any antagonists would be visible with the ghost AntagHUD

**What happened instead**:
Only antagonists made after the round started/made via the traitor panel are visible with the ghost AntagHUD

**Why is this bad/What are the consequences:**
Defeats the purpose of the ghost AntagHUD.

**Steps to reproduce the problem**:
Unknown.

**Comment by Lady-Luck** [comment]
Can this please be moved up in priority

**Comment by Markolie** [comment]
This is only the case for traitors and abductors, FYI.
