### ISSUE TITLE
shadowling dethralling surgery still does not work

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#4278]
**Problem Description**:
when trying to dethrall a shadowling, the step involving a light does not work

**What did you expect to happen**: 
use a light as a surgery tool to proceed the surgery

**What happened instead**:
after 'completing' the step, the surgery did not proceed

**Why is this bad/What are the consequences:**
because it prevents proper play of the shadowling gamemode 

**Steps to reproduce the problem**:
attempt to dethrall a shadowling, attempt the step that requires the use of a light

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was using a seclight rather than the penlight

potentially a dupe of #4007 but that's closed

**Comment by Aurorablade** [comment]
you can't use a seclight. it has to be a Flash (primary tool to use) or flashlight/penlight (secondary)

**Comment by theColdflame** [comment]
it was letting me (attempt to) do the surgery step, though?

**Comment by FlattestGuitar** [comment]
Uh, @Aurorablade, the seclight is a child of the normal flashlight, I'm pretty sure it should be possible.

**Comment by Aurorablade** [comment]
....you would be surprised how picky the code is when it comes to subtypes....

**Comment by Crazylemon64** [comment]
It's a `foo in list(stuff)` check, which requires an exact match, as-is...

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

You mean security will actually have to work with medical and not be 100% self-sufficient with their brig phys? *gasp*.
