### ISSUE TITLE
Check antagonist panel is broken

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#4279]
The link to the antagonists player panel does not work

Clicking it does nothing

PM and Show objective still works fine

**Comment by TheDZD** [comment]
Does this happen for all players, or just certain specific players? As no changes have been made recently, and the panel wasn't broken before.

**Comment by Regen1** [comment]
Has happened to all the players I have tried on, so about 4-5

Round does not seem to affect it at all

It also affects others, not just me
