### ISSUE TITLE
Toxin compensation doesn't work with robotic limbs

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#4280]
**Problem Description**:
When you get the toxin compensation syndrome, your robotic limbs do not heal, but toxin damage is dealt to "compensate" anyway

**What did you expect to happen**: 
Either robotic limbs being healed normally or being unaffected and the toxin damage not building up.

**What happened instead**:
The limbs were damaged, I received endless toxin damage.

**Why is this bad/What are the consequences:**
It makes the virus effectively lethal to anyone using robotic limbs, while it's often released as a "helpful" virus.

**Comment by KasparoVy** [comment]
Should probably check to see if the limb is synthetic and then don't do anything if it is
