### ISSUE TITLE
It is possible to attempt dethralling surgery with a seclight

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#4286]
**Problem Description**:
It is possible to attempt dethralling surgery using a seclight, however the seclight is unable to complete the surgery step

**What did you expect to happen**: 
I expected the seclight to either proceed the surgery or not allow me to attempt the step 

**What happened instead**:
I was able to attempt to complete the surgery step with the seclight, but the surgery did not proceed

**Why is this bad/What are the consequences:**
It leads players to believe they should be able to complete the surgery step with a seclight, when only a flashlight or penlight is capable of doing so

**Steps to reproduce the problem**:
Attempt to complete the 'cleanse contamination' step of dethrall surgery with a seclight

**Comment by TheDZD** [comment]
Somewhat related to #4278, although given that not being a bug, it probably shouldn't be able to start the surgery at all.

**Comment by DesolateG** [comment]
Not a bug.

**Comment by Shadow-Quill** [comment]
@Fox-McCloud Either no longer a bug, or it was fixed in the past.
