### ISSUE TITLE
Lighting Issues

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#429]
I felt that this was important to actually create a proper 'issue' on.
AFAIK, we randomly started having lighting issues, namely that darkness is absolute- the see_in_dark flag only affects what you can actually click on, but the overlay/shadows are still there, which means that the player is blind even when you can technically 'see' with mouse hovering.

As far as I know, this isn't intentional, and a fix has not been developed within having this bug around for at least a month.

**Comment by Markolie** [comment]
You sure this isn't just on away missions? A possible fix was introduced a week or two ago.

**Comment by tigercat2000** [comment]
If you are referring to #301, even with that patch applied, shadows still cover everything regardless of your see_in_dark flag.

**Comment by Markolie** [comment]
Yea, that one mostly took care of the absurd luminosity on machinery. I was hoping it'd fix this too.

This doesn't happen consistently by the way - shadows work fine for me most of the time, but always break on away missions.

**Comment by tigercat2000** [comment]
Really? Shadows never seem to work for me regardless of being on-station or on an away-mission.

**Comment by Artorp** [comment]
Could you post a screenshot of this glitch? Shadows seem fine on my end, with or without night vision.

**Comment by tigercat2000** [comment]
After further investigation, the issue stems from hardware problems, at least for me.
