### ISSUE TITLE
You can get the "fat" alert, even though your species can't get fat.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#4295]
As stated in the title. As a vulpkanin I got the "fat" alert even though I wasn't actually fat.
I imagine the alert should just check the species' flag for getting fat as well.

**Comment by Fox-McCloud** [comment]
This isn't a bug, it's just notifying you that you're hugely overfed; you can't get fat on TG either, but this icon is still there to let you know "Hey dork, stop cramming food down your throat".
