### ISSUE TITLE
Bees Attack and Destroy Bots

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#4306]
**Problem Description**:
Botany Bees attack and destroy bots-- specifically Cleanbots, from what I've seen.

**What did you expect to happen**: 
I expected the bees to leave the synthetic bots alone.

**What happened instead**:
The bees destroyed some cleanbots.

**Why is this bad/What are the consequences:**
Since botany is across from robotics, the bees, if loose, can just destroy bots as soon as they're set to patrol.

**Steps to reproduce the problem**:
Release bees, release bot. Fight.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by Fox-McCloud** [comment]
Bots are technically mobs, which is why they attack them, so not a bug per se.

Just need to decide if we want to keep this in or not. Quite frankly, I find it hilarious, but that's me.

**Comment by FalseIncarnate** [comment]
As satisfying as it is to watch Beepsky get wrecked by bees, it does cause some issues with bees trying to target them whenever they happen to stroll past. Kinda split opinion on whether or not they should ignore the bots...

**Comment by Fox-McCloud** [comment]
>whenever they happen to stroll past

This happens with every mob that passes by, just for clarity.

**Comment by TheDZD** [comment]
[Definitely a bug](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/hydroponics/beekeeping/beebox.dm#L17)

**Comment by Fox-McCloud** [comment]
Huh. Well then....that's odd.

**Comment by Crazylemon64** [comment]
I haven't been able to reproduce this - could you provide more details?
