### ISSUE TITLE
Spiderbot death>dc>can join game

### ISSUE THREAD

**Issue by lolzyking** [ParadiseSS13/Paradise#4309]
**Problem Description**:
 able to respawn after death and DC

**What did you expect to happen**: 
to become a ghost

**What happened instead**:
I was able to rejoin round as my character

**Why is this bad/What are the consequences:**
Its abusable

**Steps to reproduce the problem**:
Suicide, Die as a spiderbot, DC, rejoin game

**Comment by Crazylemon64** [comment]
Spiderbot death is not causing a DC in local testing, with either a posibrain or an MMI. Do you have more details?

**Comment by VampyrBytes** [comment]
I *think* he means if your character dies, and you then play and die as a spiderbot, if you close and open the game you can join the game as if you hadn't played in the round

**Comment by lolzyking** [comment]
its a bit odd actually I didn't give full details since I was still in round at the time of post
 
My character was an IPC, I died via a failed suicide, ala the stabbing of a bad roboticist that couldn't fix me. he then put my posibrain in a spiderbot. however a miner was having a squabble outside science and I got hit by  an accelerator, I was one shotted, spiderbot mob GONE, maybe it was lag but I dc'd right there.

I was then able to rejoin round on reconnect

**Comment by Markolie** [comment]
Can not reproduce.

**Comment by fludd12** [comment]
Was this ever reproduced?

**Comment by taukausanake** [comment]
Does an IPC brain even die ever? I haven't seen one die yet. I would imagine that's a perk to being made of aluminum and destroyed just by someone looking at you nasty
