### ISSUE TITLE
Cup soup causes permanent fatness

### ISSUE THREAD

**Issue by QuinnAggeler** [ParadiseSS13/Paradise#4310]
**Problem Description**:
Cup soup can cause someone to be fat in such a way that even weight loss shake can't fix it, only varediting.

**What did you expect to happen**: 
Swalling a few gulps of cup soup to alleviate hunger

**What happened instead**:
Around 3 minutes later, character burst out of their jumpsuit

**Why is this bad/What are the consequences:**
No food should cause permanent obesity, or cause obesity when consumed from a state of malnourishment

**Steps to reproduce the problem**:
Not entirely sure this is the cause, but the only linking factor in the three times I've seen this have been eating cup soup around 3-5 minutes beforehand.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
The only factor in common I can think of is the soup

**Comment by Fox-McCloud** [comment]
Don't recommend chugging the entire thing unless you're quite hungry. Right now the hunger indicators are not properly set up, so it notifies you you're hungry when you're really not. Knowing when to eat or not should be fixed next time we patch.

As with all food, take it easy with consumption; drink/eat a bit at a time---and if your hunger meter doen't go away after a bit, drink/eat some more. Just gulping the whole thing down is going to get you fat with any food.

**Comment by QuinnAggeler** [comment]
Didn't eat the whole thing each time though, just the time when I was malnourished. Most recently, it happened after 3 gulps at orange hunger

**Comment by Fox-McCloud** [comment]
Like I said, the "orange hunger" level kicks in wayyyyy earlier than it should (like 10 minutes into the round...), which is skewing results veryyy heavily here.

**Comment by QuinnAggeler** [comment]
Ah
