### ISSUE TITLE
Bots and brig cells get PDA message contacts

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#4311]
**Problem Description**:
Bots and brig cells get PDA message contacts
**What did you expect to happen**: 
To show all crew i could send messages to
**What happened instead**:
the contacts list was flooded with bots names

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
I am unsure, some bots are in the list, and some are not.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
![pdastuff](https://cloud.githubusercontent.com/assets/11246791/14882751/82961a52-0d3a-11e6-9181-13f4b1e1393a.gif)

**Comment by Fox-McCloud** [comment]
duplicate.
