### ISSUE TITLE
Re-attaching severed broken arm bug

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4319]
If you re-attached a broken arm that is then severed results in an arm that doesn't show up on scanners or health analyzers as being broken. 

Worse, still, if you perform the surgery to fix the broken bones in that arm, it will not repair them.

**Comment by IK3I** [comment]
Are you saying that reattaching a broken arm causes this bug, or you have to break the arm while it is off? (not sure if this is even possible).

**Comment by Fox-McCloud** [comment]
The arm being broken prior to it being severed is what causes this.

**Comment by KasparoVy** [comment]
I get the feeling it's because when an arm is severed, the act of it being severed clears a variable that might be the root of this issue
