### ISSUE TITLE
Lots of Temperature Related Bugs

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#434]
Long long standing bug

Basically our life proc for temperature handling worked fine--it was great; you took damage when you were supposed to and didn't when you weren't....Bay came a long and updated it so it was compatible with species temperature variations, which is great---but other things were added and it started breaking things:

-Firesuits don't protect you from a fire's temperature
-Being in the freezing cold never makes you take damage
-it seems that breathing in hot air or cold air makes you take damage every life proc as opposed to every few life procs.

Here: https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/carbon/human/life.dm
and here: https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/carbon/human/species.dm

would be good starting points as I know these work

**Comment by Markolie** [comment]
Allright, two of the above issues have been fixed. The breathing thing seems intentional though - are you sure it's supposed to fire only every few ticks?
