### ISSUE TITLE
Animal GUI (Such as: Farwa, Monkey, Stok, etc.)

### ISSUE THREAD

**Issue by Fhufuu** [ParadiseSS13/Paradise#4344]
**Problem Description**:
Ever since the new GUI update that added more information as how we are positioned, Food and such, their GUI has been... Broken.

**What did you expect to happen**: 
That the GUI was properly Working as Such: https://gyazo.com/0cbaeb167848b2938e5d80c16fd339f4

**What happened instead**:
The GUI is broken, As such: https://gyazo.com/48e94cdaf2cce23de7704b8486898a39

**Why is this bad/What are the consequences:**
Its.. not -that- important since the chance of someone being an animal as such is low.. however the Changeling -can- turn into a lesser form and this could affect his gameplay.

**Steps to reproduce the problem**:
Admins: Change yourself into farwas, Monkeys, Stock and etc.
Players: as a geneticist, or ask a Geneticist, to inject you with an Animal's SE.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Geneticist, Secret, Extended RP all gamemodes can be affected really..

**Comment by Tastyfish** [comment]
@tigercat2000

**Comment by Fhufuu** [comment]
A... bit of a Finding I guess. Two times this happened. I crashed Two times on two different server.. as in "Space station 13 Has stopped working" Crashed. And once I relogged, My backpack was made invisible, and then my GUI was... There? It... it was weird.

**Comment by Fox-McCloud** [comment]
this is finally fixed by: https://github.com/ParadiseSS13/Paradise/pull/9223
