### ISSUE TITLE
Abductors with tails

### ISSUE THREAD

**Issue by Cotux34** [ParadiseSS13/Paradise#4350]
**Problem Description**:
You can somehow get an abductor with a tail. I had a vulp character readied and when the game started I had a neon purple tail.

**What did you expect to happen**: 
Being a regular abductor without a tail.

**What happened instead**:
Had a tail as an abductor, the emotes and stuff worked too.

**Why is this bad/What are the consequences:**
It's just a visual thing, has no consequences that I could notice in the game

**Steps to reproduce the problem**:

1. Have abductor gamemode
2. Ready as a vulp character
3. Get selected for abductor
4. Have tail

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was abductors gamemode, nothing else out of the ordinary.

**Comment by Regen1** [comment]
@tigercat2000 i am guessing this is because of the alt character whatever system

**Comment by tigercat2000** [comment]
that's fucking hilarious and it's @Fox-McCloud's fault

**Comment by Regen1** [comment]
@Cotux34 do you have pictures of it? Cause it'd look hilarious

**Comment by Cotux34** [comment]
It did look hilarious but I forgot to take pictures, oops

**Comment by Cotux34** [comment]
Fixed with #4363

**Comment by tigercat2000** [comment]
@Cotux34 leave the issue over, the PR will automatically close it when merged

**Comment by Cotux34** [comment]
alright my bad
