### ISSUE TITLE
Holochess doesn't recognize valid moves

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#4358]
**Problem Description**:
Couldn't move anything but my queen for one turn, when I had many other open options that didn't involve me killing my queen for no reason.

**What did you expect to happen**: 
I shouldn't have to kill my queen when I can do ANYTHING ELSE besides move her into danger

**What happened instead**:
Couldn't move any other piece, king wasn't in check, only valid spot to move her was apparently right in front of the other queen.

**Why is this bad/What are the consequences:**
The queen is a major player in chess, usually. Killing her needlessly without reason is a no no

**Steps to reproduce the problem**:
Play chess.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by CrAzYPiLoT-SS13** [comment]
I have thoroughly tested the chess AI, and this has never happened to me.
Besides, I cannot do next to nothing about it as it's a third-party AI. I
can look at the js for some errors, but that's about it. Are you completely
sure the king wasn't in check and that you had to block the attacking piece
off?

**Comment by LightFire53** [comment]
King was actually surrounded by my pieces

**Comment by LightFire53** [comment]
Unless the opposing knights can jump your pieces, which they can't, or not supposed to be able to

**Comment by VampyrBytes** [comment]
um... last time I played chess knights could jump pieces

**Comment by LightFire53** [comment]
The way I have always played, and seen others play, was you could only jump your own pieces. Anyway, this appears to not really be the case.

**Comment by Tastyfish** [comment]
Knights can definitely jump any pieces in chess, regardless of whose pieces they are.
