### ISSUE TITLE
Blob and Blob Zombie nerf

### ISSUE THREAD

**Issue by Xperia15** [ParadiseSS13/Paradise#436]
I recently saw in the code that the blob and the blob zombies when they attack, aim for a specific body part. Those parts are ALL the limbs + the chest. 
Breaking one of these bones will make your life pretty hard considering that medical help is mostly unreachable within time or is not present due to the threat. Also if you break one of these bones, it will disable the whole limb permanently until it has been fixed by surgery, thus giving you a major drawback when fighting them.

Here is the code: http://puu.sh/gdhqq/eea5dcca82.png

**Comment by Markolie** [comment]
This is more of a suggestion. We definitely appreciate it - but it's best to keep these centralized on the forums so all players can participate.

**Comment by Xperia15** [comment]
Zomg asked me to make a issue request about exactly this topic and he himself sender me this link to where to place this...

**Comment by Markolie** [comment]
Mm, well, it's still not a bug and belongs on the forums. Just as a heads up, I plan to do a Blob rework soon which will remedy this.
