### ISSUE TITLE
Progress bars are no longer smooth

### ISSUE THREAD

**Issue by QQCucumber** [ParadiseSS13/Paradise#4361]
**Problem Description**:
Before the patch, progress bars were smooth despite any sort of latency. Now they're no longer smooth.

**What did you expect to happen**: 
Progress bars to be smooth.

**What happened instead**:
The progress bar was jittery, only showing two random intervals.

**Why is this bad/What are the consequences:**
Smooth progress bars were a wonderful new feature and now it's no longer functioning.

**Steps to reproduce the problem**:
Perform any action while not living in the country of Sweden.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Climbing over tables, washing hands, etc.

**Comment by Fox-McCloud** [comment]
![img](https://i.gyazo.com/2a0c3a311877a888b46137bb4aa1afaf.gif)

Can't reproduce this.

**Comment by FalseIncarnate** [comment]
I've seen this too, though I suspect it is lag and not the code itself at fault. Sometimes the bar won't appear until the task is nearly complete, but I also was lagging a bit in general on the shifts I noticed this

**Comment by QQCucumber** [comment]
@Fox-McCloud I was moving around and performing actions smoothly, but the progress bars were not smooth. I suspect it is related to lag, of course, but for some reason lag just didn't matter as much before.

**Comment by Fox-McCloud** [comment]
> if you're on a localhost server.

the gif above is from live. I've been doing various actions for a while now, and they're all smooth.

**Comment by QQCucumber** [comment]
Well, hopefully someone else can reproduce this. I wasn't really lagging at all, yet it was still jittery.

**Comment by QQCucumber** [comment]
@FalseIncarnate was this happening to you before the patch, or only after?

If it was happening before the patch I'll close the issue.

**Comment by pinatacolada** [comment]
I think this started happening to me after I updated my byond, but I'm not sure. It happens both on live and on a local server, it's not lag

**Comment by PJB3005** [comment]
On /vg/ there was a report too and it's a 510 thing.

**Comment by Fox-McCloud** [comment]
Ohhhhh, yeah, if you're running the *most* up to date version of 510, you're going to have issues. Might want to step it back a single version, until the issue is resolved.

**Comment by QQCucumber** [comment]
Ah, that must be it, thanks.

**Comment by Tastyfish** [comment]
It's a known bug in the rendering code of 510.1340. Revert to 510.1339. http://www.byond.com/download/build/510/

**Comment by QQCucumber** [comment]
@Tastyfish 1341 just came out, does that fix the issue?

**Comment by Tastyfish** [comment]
Wow, didn't realize he released it already! Yeah, it might. I'll check.

**Comment by Tastyfish** [comment]
1541 did fix the image sync issues. You can safely update to it.
