### ISSUE TITLE
Sprite Issue - Retractible Hardsuit Helmets

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#437]
Hardsuit helmets can be retracted normally and function as expected. However, the head sprite does not update to become transparent, so you can't see your face when it's retracted.

**Comment by Deanthelis** [comment]
This only remains that way until you pick up or drop an object.

**Comment by FalseIncarnate** [comment]
This an issue with the mob sprite not regenerating. I have also seen this occur with stripping bodies in medbay post-cloning, only to have the naked body appear fully clothed.

Regenerating mob sprite tends to fix this, but finding the source would be quite useful.

**Comment by TheDZD** [comment]
I've been trying to figure out the source of this, but have been unable to do so, it was not happening when I did my item flag refactor, nor after a few of the bugs related to it were fixed. This is something fairly recent.

**Comment by Spacemanspark** [comment]
If you click on the head slot while it's toggled down, it goes away.
