### ISSUE TITLE
Bee's currently cover the whole square, making botany a pain with them

### ISSUE THREAD

**Issue by Kavrick** [ParadiseSS13/Paradise#4374]
**Problem Description**:
When a bee is on the same tile as anything else, you can only click on the bee, even though it's tiny

**What did you expect to happen**: 
it'd be weird if this was intended

**What happened instead**:
Should be able to click on things the same tile as the bees, it stops you from feeding, watering and weeding your plants

**Why is this bad/What are the consequences:**
when you have 10+ bees and all your plants are dying so you cant do anything about it

**Steps to reproduce the problem**:
pretty simple, get a bee, try to click on anything that's on the same tile

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
This is a cosmetic issue and I doubt anyone will be bothered to come up with a solution. Best thing to do is alt-click.

**Comment by taukausanake** [comment]
Does the bee icon take up the whole tile? It has proper alpha area though

**Comment by Kavrick** [comment]
It's not the icon, the icon is tiny

**Comment by TheDZD** [comment]
Intentional, clicking anywhere on the tile clicks on the bee otherwise they'd be horrible to try to click on while moving. Just going to have to deal with alt-clicking in botany if you have bees around.
