### ISSUE TITLE
New Tesla arcs jump into engineering

### ISSUE THREAD

**Issue by SomanBat** [ParadiseSS13/Paradise#4382]
**Problem Description**:
The arcs from the smaller Tesla balls jump into engineering when the Tesla is close to the north part of containment.

**What did you expect to happen**: 
All tesla arcs should ground to the grounding rods.

**What happened instead**:
Expected arcs to hit grounding rods. Arcs hit engineer instead.

**Why is this bad/What are the consequences:**
`Arcs going into engineering kill engineers and destroy equipment. Engineers are abnormally lazy creatures, and staring at the Tesla motivates them to work. This is too much motivation.

**Steps to reproduce the problem**:
Start Tesla engine
Stand inside station, next to the southernmost PA windows.
Wait for Lady Tesla to hug you.
Die from hugging

**Comment by Fox-McCloud** [comment]
Where, exactly, was the engineer at, and how fart into engineering did the shocks reach? Did it hit any equipment, ever, or just the engineer?

**Comment by Necaladun** [comment]
Destroying equipment is bad.

Killing people who aren't insulated etc against it isn't a bad thing though...the sing was dangerousish to people nearby in the engine room. I like the tesla being dangerous too. If equipment can be protected I like it.

**Comment by SomanBat** [comment]
Extend that box by about one square in all directions Fox, and that's it.   The new arcs seem a little wild and crazy with just grounding everywhere, Rad collectors seem to get popped by the arcs quite often, along with the cameras in containment.

I am not code people by any means, it's just that part of the PA is well within the danger zone, and I'm not sure if the PA parts are able to be exploded by a tesla arc.

**Comment by Fox-McCloud** [comment]
@SomanBat 

PA parts are very specifically excluded

**Comment by Crazylemon64** [comment]
Open this again if it zaps to an unreasonable point
