### ISSUE TITLE
Crew manifest is broken

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#4384]
**Problem Description**:
Opening crew manifest in PDAs produces a blank screen.

**What did you expect to happen**: 
I expected to see the manifest as I did before.

**What happened instead**:
I saw a blank screen.

**Why is this bad/What are the consequences:**
Because it makes figuring out staffing, and finding the right person to contact, much harder.

**Steps to reproduce the problem**:
1) Open your PDA
2) Go to manifest
3) Observe blank screen

**Comment by Fox-McCloud** [comment]
duplicate: https://github.com/ParadiseSS13/Paradise/issues/4359

also already fixed (but not patched).
