### ISSUE TITLE
Plasmaman hardsuit + gloves do not protect from the tesla engine

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#4388]
**Problem Description**:
Plasmamen are shocked by the lightning arcs that are given off by the energy ball, even while wearing gloves.

**What did you expect to happen**: 
Plasmamen who wear both insulated gloves and their hardsuit should not take damage from the energy ball.

**What happened instead**:
The plasmaman is shocked and dies.

**Why is this bad/What are the consequences:**
This means that plasmamen cannot work on the tesla engine and cannot fix things such as deactivated emitters while it is active.

**Steps to reproduce the problem**:
1. Be plasmaman engineer
2. Equip insulated gloves.
3. Set up the tesla and turn it on.
4. Go outside and get shocked.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

N/A.

**Comment by tigercat2000** [comment]
not really a bug

**Comment by Citinited** [comment]
@tigercat2000 Is it not? I'd have thought that plasmamen engineering hardsuits would be able to have the same protection as normal engineering hardsuits.
