### ISSUE TITLE
Simple Animals get hurt when ventcrawling through Scrubbers

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#4393]
Most apparent when as borer.

Crawl through the scrubbers, and die. Rendering half the atmos net inaccessible. This behavior is different from before, so this is probably causing some antag issues.

**Comment by FalseIncarnate** [comment]
Not a bug or oversight.

While in pipes, you are subject to the internal atmospheric conditions. Scrubber lines tend to be either very low pressure or contain unsafe gases, just as supply tends to be a high-pressure death trap.

If an animal is not space worthy, it's signing up for a bad time in the scrubbers.

**Comment by Tastyfish** [comment]
Yeah, borers are affected by pressure and air levels by the stock simple animal values for corgis, etc, so they're gonna die in the pipes.

**Comment by Crazylemon64** [comment]
If borers are not able to go through pipes, then how are they to get anywhere without being killed within 5 seconds?
