### ISSUE TITLE
IPC face repair is broken again

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4404]
Repairing the internal structure of an IPC's head doesn't unmangle it any more

**Comment by FlattestGuitar** [comment]
Has it ever? I'm pretty sure after every single "fix" that was delivered it still didn't work.

**Comment by LittleBigKid2000** [comment]
It used to work, now it doesn't

**Comment by TheDZD** [comment]
@Crazylemon64 It's spacepods again, but with IPCs.
