### ISSUE TITLE
Reloading a Foam Force Shotgun while there's a live dart in the chamber causes the dart to disappear

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#4409]
**Problem Description**:
Reloading a Foam Force Shotgun while there's a live dart in the chamber causes the dart to disappear

**What did you expect to happen**: 
The dart should've been ejected onto the floor.

**What happened instead**:
The dart vanished and the foam force shotgun had one less dart inside of it.

**Why is this bad/What are the consequences:**
Less darts means less fun

**Comment by QQCucumber** [comment]
@FlattestGuitar

**Comment by FlattestGuitar** [comment]
This hasn't been a bug since #4515.

You can close this one.
