### ISSUE TITLE
Character icon replaced with static

### ISSUE THREAD

**Issue by Dinarzad** [ParadiseSS13/Paradise#4416]
**Problem Description**:
My character icon was replaced with a large static icon, like the kind that shows for the AI when something is out of camera range.

**What did you expect to happen**: 
I expected to remain as a human roboticist and not turn into a static block.

**What happened instead**:
I turned into a static block.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
I have. No fucking clue. I had just finished making a pair of cleanbots for the AI on it's request. I finished them, and moved them into the hallway. I messaged the AI and told them it had 2 new bots to order about and it thanked me . and not long after that, I suddenly turned into static.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: When I went to name the second cleanbot, I had a progress bar suddenly show up over my head for now reason, that was stuck at 50% progress. As soon as I finished naming the bot, it poofed away.

Pics because it totally happened.
[http://i.imgur.com/bbbLIrJ.jpg](http://i.imgur.com/bbbLIrJ.jpg)

**Comment by Dinarzad** [comment]
UPDATE: Kluys was able to fix it with admin hax, but still no idea what bugged out to begin with.

**Comment by Spacemanspark** [comment]
That's new.

**Comment by Fox-McCloud** [comment]
Did anyone else see you as this or only you?

**Comment by Dinarzad** [comment]
Everyone saw it. Multiple human characters as well as both the Cyborgs.

**Comment by KasparoVy** [comment]
I saw it, he was behind the kitchen table as a huge static square and we were all ogling him like 'damn what the fuck son' but after a while he randomly turned back into normal.

**Comment by fludd12** [comment]
Your existence was deemed hazardous by the Department of Purified Continuum, and as such, your entire being, past, present, and future, was censored from time-space.

Have a good day.

**Comment by Vivalas** [comment]
This deserves the WTF tag.

**Comment by Sirryan2002** [comment]
duplicate of #9781
