### ISSUE TITLE
Hair/Helmet problem as ERT

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#4419]
**Problem Description**:
Got random female hairstyle when I put on my ERT leader helmet as male.

**What did you expect to happen**: 
Put on my helmet. Nothing else.

**What happened instead**:
I grew an opposite gender hairstyle.

**Why is this bad/What are the consequences:**
Confusing genders, should not grow hair when helmet gets put on.

**Steps to reproduce the problem**:
1. Be Amber ERT leader
2. Put on helmet
3. ???
4. Have beautiful, long, pink hair

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Vampire round.

**Comment by Fox-McCloud** [comment]
Pretty sure you started out with this hair style and it just didn't update until you put on your helmet.

**Comment by Spacemanspark** [comment]
![](https://media.giphy.com/media/tH2oOpjPuN6I8/giphy.gif)

**Comment by CrAzYPiLoT-SS13** [comment]
I chose male. It gave me a female hairstyle. How could I have had that hairstyle?

**Comment by Spacemanspark** [comment]
It does that with ERT a bit, I've noticed.

**Comment by Gummin** [comment]
The whole ERT thing is buggy, was female, became SS13's Patented 30 Year Old Bald Man. 
_Although I believe this was under special adminbus circumstances._

**Comment by Fox-McCloud** [comment]
There's a very rare chance that ERT females (and nukies) end up with facial hair/beards/mustaches :wink:

**Comment by CrAzYPiLoT-SS13** [comment]
I know that. I don't think you understand the point. I chose male when it
asked me, I was bald with facial hair when I spawned in. When I put on the
helmet, it gave me a female hairstyle and deleted the facial hair, almost
like I chose female in the start. It is not a problem of females getting
facial hair.

**Comment by VampyrBytes** [comment]
@CrAzYPiLoT-SS13 
From what people have said (haven't looked into it) there are 2 bugs, and you got them both at the same time
bug 1 - ERT having hair/facial hair from the opposite sex
bug 2 - Icon not updating to what you really look like when you spawn in

So your character vars had the lovely pink hair when you spawned in, but it didn't show until something triggered the icon update (removing your helmet)

btw, can we get a barber's helmet that gives you a random hairstyle/colour when you put it on? :wink:

**Comment by CrAzYPiLoT-SS13** [comment]
Not really. Fox was saying that there was a prob(5) coded in for female ERT
members to get facial hair. The only bug here is me getting hair of the
opposite gender, and the icon not updating.

**Comment by KasparoVy** [comment]
@VampyrBytes I guess they need their own update_icons or regenerate_icons coded in to update each individual mob once they're spawned.

Also, the reason why they have hair/facial hair from both sexes is that the list is populated in such a way that it doesn't give a damn about gender (at least from what I can recall the last time I was poking about ERT code)
