### ISSUE TITLE
Changelings get obj to absorb/escape as vox/IPC

### ISSUE THREAD

**Issue by ZomgPonies** [ParadiseSS13/Paradise#442]
What is says on the tin

**Comment by Spacemanspark** [comment]
I thought someone fixed that...
Welp.

**Comment by Markolie** [comment]
I fixed it for the absorb objective (unless that doesn't work?) but I didn't implement it for the absorb and escape objective.

**Comment by Markolie** [comment]
Ah, looks like that isn't it. It tries to assign whoever you have assigned as an assassination objective as the escape with identity objective, but that doesn't check for species.
