### ISSUE TITLE
Nuke not nuking, round not ending

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#4420]
**Problem Description**:
Nuke didn't do the nuke thing

**What did you expect to happen**: 
Nuke should do the nuke thing

**What happened instead**:
Nuke was placed here by the nuke ops: [This was the location of the nuke](http://i.imgur.com/zvzLYqo.png) It went down to the timer all good and all, then the screen shrunk as if to play the cutscene, and to my knowledge, and according to Kharshai who was present in the round, the cutscene did not play. Afterwards, the round was stuck in limbo and no one died. The shuttle arrived (was called before hand), but upon departure literally never docked to CC, the server had to be restarted manually.

**Why is this bad/What are the consequences:**
This absolutely should not be happening ever, as the round literally wasn't capable of ending

**Steps to reproduce the problem**:
not a damn clue, other than the location, local testing would have to be done

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The only factor I can consider that might have caused this was the nuke's location? Otherwise, nothing seemed to be out of the ordinary regarding the round/nuke. It's either a consistent nuke problem or related to.. something else, I am not sure.

**Comment by Tastyfish** [comment]
Couldn't locally reproduce at that exact location, so it probably runtimed at some obscure point.
