### ISSUE TITLE
Admin log message for "loose singulo" appearing when it shouldn't

### ISSUE THREAD

**Issue by AugRob** [ParadiseSS13/Paradise#4424]
**Problem Description**:
I got the "A singulo exists and a containment field has failed." message while playing with the energy field. It kept shutting down. At no point was there a singulo. 

**What did you expect to happen**: 
I expected it to not display this alog message when what it's telling me is not true

**What happened instead**:
Told me about a false singulo

**Why is this bad/What are the consequences:**
Confusing for admins when a containment field fails period.

**Steps to reproduce the problem**:
Have admin log messages visible. 
Start a few field generators.
Allow the field to die off. 
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by tigercat2000** [comment]
it will trigger whenever there is a singularity/narsie/tesla anywhere on the map and the containment field shuts down
you probably had the academy away mission loaded

**Comment by AugRob** [comment]
Checking the logs and yeah, you're right it was academy
