### ISSUE TITLE
Can put literally anything on Renault as collar

### ISSUE THREAD

**Issue by AugRob** [ParadiseSS13/Paradise#4426]
**Problem Description**:
You can put any item in Renault's collar slot

**What did you expect to happen**: 
Only collars? (Unless this is a feature? I do like hiding the nuke disk on Renault)

**What happened instead**:
Have put a number of things in the collar slot. From IDs to pulse destroyer.

**Why is this bad/What are the consequences:**
Um. I don't think this is supposed to happen?

**Steps to reproduce the problem**:
Have an item in your active hand.
Add to Renault's collar slot.
(Profit?)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Maybe this is possible with other collar-slot-having animals as well? Haven't tested..

**Comment by Spacemanspark** [comment]
Holy shit.

**Comment by Fox-McCloud** [comment]
@Tastyfish

**Comment by QQCucumber** [comment]
The nuclear authentication disk makes a great collar.

**Comment by taukausanake** [comment]
This is awesome. Bonus, allow nuclear authentication disc to be attached to a collar and then put on as accessory :3

**Comment by Keilden** [comment]
Suicide Bomb Fox!

**Comment by Screemonster** [comment]
brb, grabbing the next tesharii I see.

**Comment by KasparoVy** [comment]
Lmfao, wicked. I do think the nuke disk + collar should be a thing, that'd be pretty funny.
