### ISSUE TITLE
"BYOND Hub reports that #### is not reachable." On Linux VPS 90% of the time.

### ISSUE THREAD

**Issue by nopm** [ParadiseSS13/Paradise#4429]
**Problem Description**:
Well, it's not a problem with the ports themselves, so please do not tell me to check if they're open. I'm currently using a Linux VPS to host paradise, and 90% of the time i boot Dream Daemon i get the ports-not-reachable error. I'm opening an issue about this since i've tested the new Goon release, /tg/ and Bay and in everyone of them, it worked. ALL ports are open in this VPS, so i'm wondering WTF is happening, why the hell is BYOND reporting the ports are not reachable? As mentioned, every other codebase works fine, Paradise doesn't.

**What did you expect to happen**:
For BYOND to report that said port is reachable and the game to appear on the server list.

**What happened instead**:
BYOND reports that port is not reachable and i'm forced to close and boot Dream Daemon unti it works.

**Why is this bad/What are the consequences:**
I THINK it's a problem related to Linux, although i'm not 100% sure. If it is however, people using LInux to host are having a serious trouble hosting.

**Steps to reproduce the problem**:
Steps? More like "Use an all-ports-open Linux VPS, and then try to host the Paradise code the way it is now". Chances are that you will have to close & boot Dream Daemon a ton of times for it to work.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It also send some sort of HTTP Error: 404 not found, and some times HTTP Error: 500

**Comment by tigercat2000** [comment]
happens to me too on windows, no idea, literally not a thing we can do anything about

**Comment by IK3I** [comment]
strangely enough, if you use an outside port checking tool when this crops up (at least on my system) it fixes it and byond starts saying it's reachable again. And no, I don't have any idea why this is the case.

**Comment by nopm** [comment]
@tigercat2000 does it also sends those HTTP erros for you?
@IK3I Well it's linux, not anything i can do about...

**Comment by Fox-McCloud** [comment]
Nothing we can really do about this, really, nor is it easily replicatable---I get this locally, all the time, but people can still connect and test things.

**Comment by nopm** [comment]
@Fox-McCloud Why not? i mean like this is fucking annoying - i had to reopen 50 times, and i'm not joking. You seriously can't fix this? Why?

**Comment by tigercat2000** [comment]
@nopm it's literally completely not on our end, none of us or the other servers have had to deal with it before
it's likely something horrifying going on in byond's own stuff which we don't control

**Comment by nopm** [comment]
@tigercat2000 But why Paradise? No other codebase (or BYOND game) has this problem, only Paradise... I know it's not on your end, but do you have at least a clue why this happens? It's a Paradise-only issue...

**Comment by Fox-McCloud** [comment]
Just going to close this.
