### ISSUE TITLE
phantom dionae shoes

### ISSUE THREAD

**Issue by TechDragon610** [ParadiseSS13/Paradise#4430]
**Problem Description**:
What is the problem?

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by TechDragon610** [comment]
I was unaware the template reset when it reasks for a title.

**Comment by FlattestGuitar** [comment]
:v
