### ISSUE TITLE
Dionae phantom shoes (real report this time.)

### ISSUE THREAD

**Issue by TechDragon610** [ParadiseSS13/Paradise#4431]
**Problem Description**:
What is the problem?
Diona keeping part of the Orange sneaker sprite once take. Off

**What did you expect to happen**: 
Why do you think this is a bug?
For dionae feet to be unbranded by the shoe once taken off.
**What happened instead**:
How is what happened different from what you expected?
While untested in other sneakers or replicating, upon taking off the orange sneakers from the perma-brig, I noticed that while the orange part disappeared, the white sprite remained on feet.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's visually out of place.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue. 
Put on orange sneakers as diona, take them off. May be prison copies, may not be.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by FlattestGuitar** [comment]
Can you post some pics of that? 

Also, were the sneakers legcuffs?

**Comment by TechDragon610** [comment]
The sneakers were not made into the cuffs as I was free to move about. When I get home I will attempt to reproduce. (getting perma'd may be the hard part...)

**Comment by TechDragon610** [comment]
was unable to recreate under similar condition. assuming it was a one time fluke.
