### ISSUE TITLE
Dehydrated Space Carp Bug

### ISSUE THREAD

**Issue by D3ception** [ParadiseSS13/Paradise#4434]
**Problem Description**:
What is the problem?
I used a dehydrated space carp, and it attacked me right after, I was a traitor at the time.

**What did you expect to happen**: 
Why do you think this is a bug?
I expected it to do as http://nanotrasen.se/wiki/index.php/Syndicate_Items#Dehydrated_Space_Carp states, and only attack other people

**What happened instead**:
How is what happened different from what you expected?
Well, it turned around and beat me half to death. Which I did not expect.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It doesn't do what the wiki says, which is pretty frustrating.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I took a bucket of water, and held the carp in the other hand, used the bucket on the carp, it spawned, then beat me quite badly.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It was an Autotraitor round

**Comment by FlattestGuitar** [comment]
[This](https://github.com/ParadiseSS13/Paradise/blob/a3fdeaa57cdf5b84dc3be2057c0eb0373a41352a/code/game/objects/items/dehy_carp.dm#L41) code attempts to make the carp to be friendly to its user, but somehow fails. This is indeed a bug.

**Comment by Fox-McCloud** [comment]
You have to use the plushie in your active hand in order to "bind" it to you. Otherwise it will attack you.

The reason that the code @FlattestGuitar pointed out doesn't "work", is because the `owner` isn't set; it's null.

This is absolutely not a bug in any sense and is just user error.

**Comment by QuinnAggeler** [comment]
Except there's _nothing_ in the documentation for the item that says it has to be the active hand. This is still an issue, and should not be considered fixed until either the code or the documentation changes.

**Comment by Fox-McCloud** [comment]
@QuinnAggeler 

Wiki problems or poor documentation are wiki problems and should be treated as such. The github is for *code* issues, not lack of information on the wiki.

**Comment by QuinnAggeler** [comment]
But the documentation is in the code, displayed in the syndicate uplink menu. All it says is "Just add water to make your very own hostile to everything space carp. It looks just like a plushie."

**Comment by FlattestGuitar** [comment]
Well, the description should be better, at least.The carp isn't "your very own" if it bites your head off if you wet it with an extinguisher instead of a sink, that makes no sense.

**Comment by QuinnAggeler** [comment]
This is a problem to which there _are_ code solutions. Dismissing it as "just user error" reflects a common designer error, which is expecting people to know what you know about the game's inner workings.

**Here are some code solutions:**
1) Changing the description in the syndicate uplink store code. Add something like "use the carp in your active hand to make an obedient killing machine, wet it in your inactive hand to make it hostile to everyone so you can play the victim"

2) Make wetting it in your inactive hand not work

3) Include a warning when attempting to wet the carp in your inactive hand

4) Store the carp's owner in the item, and have the carp mob inherit it when spawned

**Comment by Fox-McCloud** [comment]
>This is a problem to which there are code solutions. Dismissing it as "just user error" reflects a common designer error, which is expecting the players to know what you know about the game's inner workings.

and again, this is something that falls under the *wiki* purview, not the code, for the most part. The code, nor anything in it, tells you how to make a "proper" deathmix, optimal burn mix, best tox bomb, etc. These all fall under proper usage/gameplay that belong on the wiki (for the most part), and aren't "coding issues"--ergo, they do not belong on the github explicitly.
