### ISSUE TITLE
Rejuvenating any species of carbon/human deletes their hair

### ISSUE THREAD

**Issue by AugRob** [ParadiseSS13/Paradise#4435]
**Problem Description**:
Hair sprite disappears entirely when admin heal/revived

**What did you expect to happen**: 
Rejuvenate the mob

**What happened instead**:
Rejuv shouldn't make people bald

**Why is this bad/What are the consequences:**
Likely a bug from #4331 

**Steps to reproduce the problem**:
Acquire /mob/living/carbon/human[/*]
Use admin rejuvenate on them

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
![ss 2016-05-15 at 07 38 49](https://cloud.githubusercontent.com/assets/3792747/15274104/f8526f0a-1a70-11e6-90bb-ff1b0cd36c2e.png)
![ss 2016-05-15 at 07 38 56](https://cloud.githubusercontent.com/assets/3792747/15274105/fc990254-1a70-11e6-8c8a-cdd9a4a9ea4d.png)
![ss 2016-05-15 at 07 39 05](https://cloud.githubusercontent.com/assets/3792747/15274106/01516b6a-1a71-11e6-8db5-3fdba9eaa1d5.png)

**Comment by TheDZD** [comment]
@KasparoVy

**Comment by KasparoVy** [comment]
:+1: Thanks for reporting, on it
