### ISSUE TITLE
Animals can not be grabbed aggressively

### ISSUE THREAD

**Issue by IK3I** [ParadiseSS13/Paradise#4439]
**Problem Description**:
When grabbing an animal, pressing the use key, regardless of where the grab timer is, will let go of the animal. You can also grab it with both hands and attack it harmlessly with your grab hands

**What did you expect to happen**: 
Grabbing the animal and pressing the use key when the meter was full to upgrade to aggressive grab

**What happened instead**:
The use key removed the grab entirely

**Why is this bad/What are the consequences:**
Animals can not be eaten by furbeasts and you can's to anything that brags would normally allow you to do

**Steps to reproduce the problem**:
Grab any animal -> try to upgrade the grab -> fail spectacularly

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
The grab behaved like an abstract item being held, you could attack harmlessly with it and even grab the same animal with both hands and hit said animal with either hand

**Comment by Fox-McCloud** [comment]
Have you tried this multiple times? I never use anything other than the activate handheld object key to use things in my active hand, and I've eaten plenty of chickens before using this, though simple animals are difficult to get a grab on because they move around so much.

**Comment by IK3I** [comment]
This has failed with a fox and a mouse on several occasions since the most recent patch. I grab, and then when I try to upgrade the grab, even though the animals have not moved, the grab just dies

**Comment by tigercat2000** [comment]
interesting

**Comment by IK3I** [comment]
What's more interesting is that this has begun working as intended again, I don't know what changed, but something broke and then fixed it unless there's some weird edge cases involved

**Comment by Fox-McCloud** [comment]
I've been unable to replicate this---and I've seen plenty of people grabbing animals. I have a feeling this is a once of weird thing that was impacting only you.

**Comment by IK3I** [comment]
My best guess is that I somehow managed to achieve an edge case twice without realizing it. I have no idea how one would even begin to search for it though.
