### ISSUE TITLE
pAIs that die inside of a PDA don't die properly

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#4441]
**Problem Description**:
pAIs do not die properly inside a PDA

**What did you expect to happen**: 
pAIs which die should be replaced with a 'robot debris' item on the floor

**What happened instead**:
pAIs which die inside of a PDA instead remain as functional pAIs, however the personality is wiped and replaced with one named 'robot debris'

**Why is this bad/What are the consequences:**
It is not intended behavior and could potentially make pAIs reusable after death

**Steps to reproduce the problem**:
1. Have pAI inside PDA
2.Get EMPed

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
The cause of death was EMP, via revenant

**Comment by Crazylemon64** [comment]
topkek

**Comment by Tastyfish** [comment]
It seems to actually be an issue for pAI's inside their cards, in general, not specific to being inside a PDA.
