### ISSUE TITLE
Transit space oversight.

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#4459]
**Problem Description**:
Oversight on the side of transit space. 
![screenshot_32](https://cloud.githubusercontent.com/assets/9385129/15368228/0163cefe-1d2d-11e6-92df-995fad8b5af1.png)

**What did you expect to happen**: 
All of transit space should be, well, in transit.

**What happened instead**:
There is one line that is not.

**Why is this bad/What are the consequences:**
Not that important, but someone deconstructing the windows for any reason (or fixing them) will see the line of space that is not moving.

**Steps to reproduce the problem**:
Move one tile further towards east edge of shuttle(by deconstructing walls or windows) and see the magic.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was observing at the time.

**Comment by tigercat2000** [comment]
transit space isn't handled based on `/image`s
someone didn't map the transit space big enough for the shuttle
it was probably me

**Comment by CrAzYPiLoT-SS13** [comment]
Yeah, alright, will change.

**Comment by taukausanake** [comment]
Didn't we change the visible area a player could see? Maybe you forgot to increase the transits area too?

**Comment by tigercat2000** [comment]
@taukausanake we reduced visual area and also that was long before tg shuttles

**Comment by monster860** [comment]
I would like to say, the escape pods have the same problem. I've fucked around with telescience and teleported into the corner of a pod, and it showed non-transit space.
