### ISSUE TITLE
Buckets cannot be labeled

### ISSUE THREAD

**Issue by Krausus** [ParadiseSS13/Paradise#446]
A special feature of glass reagent containers is that they [can't be labeled by hand labelers](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/paperwork/handlabeler.dm#L32-L34), but are instead [labeled using pens](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/reagent_containers/glass.dm#L298-L316):
```
attackby(obj/item/weapon/W as obj, mob/user as mob, params)
	..()
	if(istype(W, /obj/item/weapon/pen) || istype(W, /obj/item/device/flashlight/pen))
		var/tmp_label = sanitize(input(user, "Enter a label for [src.name]","Label",src.label_text))
		if(length(tmp_label) > 10)
			user << "\red The label can be at most 10 characters long."
		else
			user << "\blue You set the label to \"[tmp_label]\"."
			src.label_text = tmp_label
			src.update_name_label()
```
(On an unrelated note, you can label beakers with penlights. They're pen-sized flashlights. That makes no sense.)

Because buckets are derived from glass containers, they cannot be labeled with a hand labeler, but they also cannot be labeled by pen, because they have a [unique `attackby` proc](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/reagent_containers/glass.dm#L548-L560) to handle cleanbot assembly, and it doesn't call the parent proc:
```
attackby(var/obj/D, mob/user as mob, params)
	if(isprox(D))
		user << "You add [D] to [src]."
		del(D)
		user.put_in_hands(new /obj/item/weapon/bucket_sensor)
		user.unEquip(src)
		del(src)
```
There should probably be a `..()` in there, so the pen labeling code runs, although it *may* make more sense for buckets to be an exception to the hand labeling rule.

**Comment by Fox-McCloud** [comment]
I've seen plenty of beakers, bottles, and the likes have writing on them in my life.

I've yet to see a bucket...

**Comment by Krausus** [comment]
It's never too late to start writing on buckets!

It at least needs an exception in the hand labeler code, though. As it is, trying to use the hand labeler tells you to use a pen, and trying to use a pen does nothing. It would also probably be nice to give botanists a hand labeler, since they'd be the ones taking advantage of it.
