### ISSUE TITLE
Database bans not expiring.

### ISSUE THREAD

**Issue by nopm** [ParadiseSS13/Paradise#4462]
This is the kind of help i would not ask on the forums, hence why i'm asking here. I don't know if this is a bug or something on my part, but on my server, the DB bans are not expiring. I banned a user 6pm for 1 hour, it's 8pm right now and the ban hasn't expired. I figured the forums are not the right place to ask for this kind of help (and neither is the IRC, since it's mostly dead), so that's why i'm asking here. Can you guys help?

**Comment by taukausanake** [comment]
You could ask in the Discord chat, I believe that's available as much as anything else. Otherwise the GitHub as everyone else says is for issues on the server. If this is also an issue on our server it might be looked into

**Comment by nopm** [comment]
I cannot confirm if it is an issue that applies only for me, i will ask in the Discord however. Thanks!

**Comment by Regen1** [comment]
Sometimes the logs gives weird shit like "X user's ban has expired!"

Did the server restart at all?

**Comment by nopm** [comment]
Yes it did, ban didn't expire. I checked both the DB and the Unban panel, ban is still on. I don't know what happened, and the world did restart. (Through round end)

**Comment by nopm** [comment]
Yep, i even changed the duration to 1 minute, the ban still didn't expire. This is pretty weird.

**Comment by nopm** [comment]
Yep, it was a misuderstanding. Thanks for clearing it up @TheDZD !
