### ISSUE TITLE
Disembodied brains (Including posibrains) constantly suffocate

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4463]
While it makes some sense for an organic brain, IPCs and cyborgs don't need to breathe, so neither should a positronic brain.

**Comment by TheDZD** [comment]
Suffocate how exactly? Do you mean the organ becomes unusable after a while?

**Comment by QuinnAggeler** [comment]
I've noticed this in testing, too. The oxygen starvation icon appears, and the screen continually gets darker, but it doesn't seem to stop posibrains from being able to talk, if their speaker is on.

**Comment by Spacemanspark** [comment]
As far as I can tell, it doesn't kill the posibrain.
That said, it's obnoxious when the screen continually darkens.

**Comment by Spacemanspark** [comment]
Well.
Had someone summon me and put me in their satchel for a long ass time and didn't take me out despite my screaming.
The following happened.
![Nice meme](http://i.imgur.com/idpcMTa.png)
