### ISSUE TITLE
Engineering Camera Monitor

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#448]
The Camera Monitor isn't connected to/able to connect to any cameras whatsoever, making it difficult for an atmostech manning the computers to check if, say, the PA is on too high, or the Singularity is loose, or what-have-you. Unsure if this is a bug or simply an oversight.

**Comment by Deanthelis** [comment]
http://puu.sh/geSZv.jpg

**Comment by Markolie** [comment]
That's not the point of the monitor. The engineering camera monitor displays cameras that are within an atmos alert, so engineers can view areas that are, say, on fire.
