### ISSUE TITLE
Durands are nuclear explosion proof

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#4484]
**Problem Description**:
if inside a durand when the nuke explodes you get two messages about you dying but are still alive after the cutscene

**What did you expect to happen**: 
for the person inside to die

**What happened instead**:
they survived

**Why is this bad/What are the consequences:**
isnt really important

**Steps to reproduce the problem**:
make a durand, get inside it and trigger nuclear detonation

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: it was nuke ops and the durand was inside the shuttle with ranged armor booster

**Comment by TheDZD** [comment]
In all likelihood, all mechs are.

**Comment by QQCucumber** [comment]
You can survive nukes by being inside certain things, but to be honest everything after the detonation cutscene is moot.

**Comment by IK3I** [comment]
clearly, the nuke should just be a 200, 250, 300 bomb so the z-level becomes moot after the cutscene

**Comment by Vivalas** [comment]
Are Durands made out of refrigerators?

**Comment by TheDZD** [comment]
@IK3I Actually, giant bombs shouldn't completely crash the server now, they just take a while to finish the explosion.

**Comment by taukausanake** [comment]
@TheDZD How long exactly? I'd like to know for reasons because I used to always nuke my old private server. Do you think we could get an actual exploding nuke sometime in the future?
