### ISSUE TITLE
JaniJet

### ISSUE THREAD

**Issue by ExitGame** [ParadiseSS13/Paradise#4498]
**Problem Description**:
Janicart acts as infinite jetpack.

**What did you expect to happen**: 
Normally you wouldn't be able to drift around in space like on normal tiles.

**What happened instead**:
Janicart can drive on space tiles.

**Why is this bad/What are the consequences:**
Uhm. Infinite jetpack?

**Steps to reproduce the problem**:
EDIT: 0. Be vox (???)
1. Take JaniCart and keys.
2. Go to space.
3. Drive around.
4. Enjoy your new jetpack.

**Comment by QuinnAggeler** [comment]
Probably not intended behavior, though then again it might be allowable seeing as the JaniCar is completely unique.

**Comment by Crazylemon64** [comment]
Don'tcha know? The janitor is ALWAYS a cool secret agent

**Comment by CrAzYPiLoT-SS13** [comment]
Not a bug. Totally intended.
Kidding. Also, the issue name is hilarious.

**Comment by tigercat2000** [comment]
hasn't this been fixed literally 17 times

**Comment by Tastyfish** [comment]
I actually can't reproduce this, I immediately drifted off out of control.

**Comment by KasparoVy** [comment]
Reminds me of the bug I'd encountered at random some time ago where I'd run straight out into space as a Vox and suddenly gain the ability to move about as if it was a regular floor, not a space tile where I should drift. I wonder if this is linked.

**Comment by ExitGame** [comment]
@KasparoVy Actually, I think it's not the JaniCart but the Vox + JaniCart?
Because I also gained that ability when I was Vox.

**Comment by Tastyfish** [comment]
I tested it with a vox coincidentally when I was trying to reproduce it, so that's not it, at least (or not the only thing required to summon the janijet god).
