### ISSUE TITLE
Problem with the blender/juicer and plant bag

### ISSUE THREAD

**Issue by dochomie** [ParadiseSS13/Paradise#4499]
**Problem Description**:
When adding items to the blender/juicer, if you add them from the plant bag, occasionally the blender will not read as having accepted items (the popup window reads as no reagents). NOTE: this is the blender/juicer, NOT the condimaster.

**What did you expect to happen**: 
I expect that when the blender is loaded with the plant bag, it will accept 10 of the items from the bag (like it usually does) and then allow me to blend, and refill from the plant bag.

**What happened instead**:
Occasionally (usually when trying to blend grapes) the blender will accept the items, and then show as empty (reagents not showing up in the blender). Sometimes the plant bag will lump the items into a stack of 10 that becomes a permanent item (one of the items with a little white 10 in the corner). The stack stays as a stack of 10, even when placed on a table (still shows the little white 10, even when outside the inventory).

**Why is this bad/What are the consequences:**
This occasionally renders the juicer/blender unusable, because after this happens, nothing will be accepted.

**Steps to reproduce the problem**:
I believe the issue is when the juicer is accidentally overfilled (past 10 items), either by filling one or two and then using the plant bag, or attempting to fill all 10 at once.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I was attempting to cook every item on the wiki, and was working really fast. This has happened 3 or 4 times, and it is very frustrating. Always related to overfilling or using the plant bag, and multiple times it was related to using grapes.

**Comment by DesolateG** [comment]
I can't reproduce this. Every time it has just stopped accepting things to grind when full.

**Comment by dochomie** [comment]
Thanks for the response. It's crazy that you've looked into this. It's been
years since I've fired up SS13 Paradise station. I guess I need to get back
into the game.

Keep up the good work!!!!
