### ISSUE TITLE
Can't accept pAI's

### ISSUE THREAD

**Issue by payback137** [ParadiseSS13/Paradise#4513]
**Problem Description**:
When using a pAI card, even though it shows the "additional personalities available" message, there are still none shown

**Why is this bad/What are the consequences:**
I play pAI's a load, and it means I can't be one of the few roles I really like

**Steps to reproduce the problem**:
simply using a pAI and having someone submit themselves for it

**Comment by razekpraxis** [comment]
I've seen this error before, however it seems to only happen sometimes. Not all the time, so finding out a cause could be difficult.

**Comment by CrAzYPiLoT-SS13** [comment]
As razek said, I've seen it happen on occasion, but no visible pattern.

**Comment by AceMcLazer** [comment]
This is not a bug, If the pai player, has ghosted from their body, instead of dying or observing, they are able to sign up and you receive the message. but are not on the list. "ghosting" ghosts CANNOT join the round.

**Comment by Twinmold93** [comment]
Sounds like it just needs a check for those signing up to not to have ghosted willingly to fix it.

**Comment by Crazylemon64** [comment]
Oh this might be the kitten bug or something
One sec
