### ISSUE TITLE
Abductors can use secondary languages to speak!

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#4514]
**Problem Description**:
Abductors can speak in their secondary language if one is set in character creation

**What did you expect to happen**: 
To ayy lmaos be silent like they should be

**What happened instead**:
Abductors can speak in honks and wild shit like that

**Why is this bad/What are the consequences:**
Ayy lmaos shouldn't be able to communicate at all

**Steps to reproduce the problem**:
Pick a secondary language, become ayylien, speak your secondary language, it works.

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by QQCucumber** [comment]
As an aside, could you make it so if abductors speak using /me and quotation marks, they instantly explode? :)

**Comment by Spacemanspark** [comment]
If they do that they should get a ban.
