### ISSUE TITLE
Permanent Teleporters cannot be deconstructed, and are unusable.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#4517]
**Problem Description**:
See above.

**What did you expect to happen**: 
I wonder.

**What happened instead**:
See above.

**Why is this bad/What are the consequences:**
Yes.

**Steps to reproduce the problem**:
Guess.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It seems that you can't actually click any part of a teleporter with the permanent teleporter board to load it.

**Comment by Fox-McCloud** [comment]
@monster860

**Comment by fludd12** [comment]
Updated a few of the issues I noticed.

**Comment by monster860** [comment]
I'm pretty sure you're not using the permanent teleporter correctly.

- Select the target on a *normal* teleporter.
- Screwdriver open the teleporter station
- Use the permanent teleporter board on the station
- Now build the permanent teleporter in your desired location

Anyways, the fact that the teleporter is not deconstructable is definitely an issue. I've also noticed that virtual gameboard is also not deconstructable
