### ISSUE TITLE
Reading Large Papers Screws Up GUI

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#4520]
**Problem Description**:
When you read a paper with a lot of text, it changes the tabs, removing them, and filling the box with the entire text of the book/paper, much like examining with alt+click.

**What did you expect to happen**: 
No affect to GUI. Just pull up new screen with the text contents.

**What happened instead**:
Changes the GUI, still pulls up the new screen.

**Why is this bad/What are the consequences:**
Removes all your tabs, requiring a client re-log to fix the issue. It's mostly a hassle of use.

**Steps to reproduce the problem**:
Make or find a book with a LOT of text. Open book.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing in the game seems out of the ordinary. Happened in two reported different rounds, by myself and Ace McLazer.

**Comment by AceMcLazer** [comment]
Here is a quck view of what it looks in the game like http://puu.sh/p7Pvu/7d0ce8c66d.png

**Comment by Tastyfish** [comment]
kek

**Comment by CrAzYPiLoT-SS13** [comment]
I think this deserves the WTF label
