### ISSUE TITLE
Reality can be broken by placing a box in an evidence bag in said box

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4528]
As the title says, it's possible to put a box inside an evidence bag that's inside said box, breaking reality.

**Comment by taukausanake** [comment]
and now I have a reason to try security. At least until this is patched

**Comment by TheDZD** [comment]
@taukausanake Don't, this probably results in infinite recursion.

**Comment by Fox-McCloud** [comment]
@LittleBigKid2000 

Please state EXACTLY how this is done.

**Comment by PJB3005** [comment]
Sounds pretty simple to me.

1. Get box
2. Get evidence bag
3. Put bag into box
4. Open box inventory.
5. Make sure box is in your active hand.
6. Click evidence bag inside the box inventory.
7. ??? 
8. Profit

**Comment by LittleBigKid2000** [comment]
[Here's a webm of it](https://zippy.gfycat.com/SimplisticSpanishAruanas.webm)

**Comment by monster860** [comment]
Sounds like a !!FUN!! way to teleport items.

**Comment by LittleBigKid2000** [comment]
[Here's a video of it, without the cutoff this time.](https://drive.google.com/file/d/0B-VaJY5lVmqcT2xCYVZQQ0U2akE/view?usp=sharing) Gah, why is it so hard to share a video over the internet?

**Comment by taukausanake** [comment]
Can you put the bag inside the box that the box was placed inside? I want to see how deep this can go

**Comment by Ar3nn** [comment]
You mean before or after the entire server dies trying to figure out the paradox?

**Comment by taukausanake** [comment]
Seeing as this is a paradox, the only acceptable answer to that is "yes"

**Comment by Vivalas** [comment]
I wonder if you can dupe items like this by putting them in the original box.
