### ISSUE TITLE
Xenos can no longer move via walls in space

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#453]
This seems to be a bug that came from removing Xenos space walk. We had two xeno players say they couldn't move along the walls in space.

**Comment by Fox-McCloud** [comment]
I disabled spacemove, which prevented the ridiculous 100% control in outerspace; will test this locally; I know that if you're 1 tile off from a wall onto space then you're not going to be able to do anything; will investigate further.
