### ISSUE TITLE
Engineering Cyborg Analyzer eaten by cameras.

### ISSUE THREAD

**Issue by Davdichan** [ParadiseSS13/Paradise#4531]
**Problem Description**:
Attempting to upgrade a camera as an engineering borg with an analyzer to give it x-ray removes the analyzer from the cyborg's inventory, does not regenerate while charging.

**What did you expect to happen**: 
Either the analyzer to regenerate in a charger or for the cyborg's analyzer to not be compatible with cameras.

**What happened instead**:
The analyzer disappeared and nothing short of a module reset would bring it back.

**Why is this bad/What are the consequences:**
Cyborgs lose their analyzer, preventing them from scanning future anomalies or using it's atmospheric scanning functions to check a room for breathable atmosphere for organics.

**Steps to reproduce the problem**:
Step 0: Become a Cyborg, Select Engineering module.
Step 1: Unscrew a camera
Step 2: Use your analyzer onthe camera to upgrade it.
Step 3: Upgrade your camera, loosing your analyzer permenantly or until module reset.

**Possibly related stuff**: 
Analyzers can not be held by magnetic grippers, preventing engiborgs and drones from upgrading the station's cameras.

It would seem this is an oversight, either borgs are not meant to be able to upgrade cameras, or the gripper needs tweaking to allow analyzers being grabbed and placed in cameras and the cyborg analyzer tweaked so it can't be removed.

**Comment by bgobandit** [comment]
yo https://github.com/tgstation/tgstation/pull/18516
