### ISSUE TITLE
Sanitize problem?

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [ParadiseSS13/Paradise#4553]
![screenshot_43](https://cloud.githubusercontent.com/assets/9385129/15718401/6bf9e93e-282b-11e6-9770-ca639dcd5ab6.png)
Basically this. It should be "fun™". I don't even know, it worked before.

**Comment by Spacemanspark** [comment]
I blame Monster.

**Comment by PJB3005** [comment]
Shouldn't ever have worked.

The character in question is U+2122, and since BYOND doesn't support unicode it ends up as garbage as shown in the picture.

So unless you port goon chat :^) it'll never be possible.

**Comment by CrAzYPiLoT-SS13** [comment]
Actually, last round I observed, it worked, I am sure of it.

**Comment by PJB3005** [comment]
There is literally no way that worked.

**Comment by CrAzYPiLoT-SS13** [comment]
It works on my test server at this exact moment.

**Comment by PJB3005** [comment]
I have no idea how this is possible.

**Comment by CrAzYPiLoT-SS13** [comment]
From what I've seen, it actually works up to a certain point. On my test server, it transformed into this after approximately 10 minutes. I don't even know.

**Comment by Tastyfish** [comment]
I'm pretty sure any unicode support in BYOND is purely accidental and coincidental, yeah. Wouldn't rely on it.
