### ISSUE TITLE
ПДА\Консоль не могут в кириллицу.

### ISSUE THREAD

**Issue by Templariumer** [ParadiseSS13/Paradise#4554]
**Problem Description**:
Игра не может в нормальную кириллицу везде, кроме чата.

**What did you expect to happen**: 
РУССКИЕ БУКВЫ В КОНСОЛЯХ И ПДА

**What happened instead**:
ПДА\Консоль перестает отображать вообще всё

**Why is this bad/What are the consequences:**
Ущемление прав русскоговорящих.

**Steps to reproduce the problem**:
1.Взять ПДА\Консоль
2.Написать там что угодно на русском.
3.Кричать ФЕДЯ НЕ ПАШЕТ СМЕНИ БИЛД.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Шутки шутками, а для порядка надо.

**Comment by CrAzYPiLoT-SS13** [comment]
Lol, seems like this happens a lot these days

**Comment by Gummin** [comment]
This has always happened a lot if I'm not mistaken.
