### ISSUE TITLE
HTML interfaces are kept open after server restart

### ISSUE THREAD

**Issue by d34d10cc** [ParadiseSS13/Paradise#4555]
**Problem Description**:
Title. Also, may include NanoUI.

**What did you expect to happen**: 
They should close.

**What happened instead**:
They stay open.

**Why is this bad/What are the consequences:**
Normally, it wouldn't be so much of a problem. Nothing updates without a src object. Except the gameboard. It can work without a src object and, thus, you spend your time trying to beat that damn AI, the server restarts in the meantime, you continue to play, and when you finally win, what do you get? Absolutely. Nothing.

**Steps to reproduce the problem**:
1. Use HTML/NanoUI(?) interface
2. Restart server
3. Keep using the interface

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not sure if this is actually doable from a coding PoV, but still an issue-worthy bug.

**Comment by Tastyfish** [comment]
Since all code is abruptly terminated when the server restarts, and there's no way to know that a popup from the previous round exists, that I know of, I'm not really sure how this could be changed.

**Comment by PsiOmegaDelta** [comment]
Unsure if HTML Interface is able to but tgui/NanoUI can both programmatically close down all open windows with little effort. Could easily be done just before the shutdown.

**Comment by AffectedArc07** [comment]
NanoUI and TGUI are auto-closed on server restart. However, since regular `browse()` interfaces arent tracked, we have no way to really fully "fix" this.
