### ISSUE TITLE
Most station intercoms have all the channels on them

### ISSUE THREAD

**Issue by QQCucumber** [ParadiseSS13/Paradise#4559]
**Problem Description**:
Most station intercoms have all the channels on them

**What did you expect to happen**: 
Have only the necessary channels on them.

**Why is this bad/What are the consequences:**
People finding a not often used room on the station and annoying security or command.

**Comment by FlattestGuitar** [comment]
It depends on your ID access. You can't set an intercom to security if you don't have security access. DJ station ones are exempt for prank value. 

This isn't even a bug.
