### ISSUE TITLE
View Variables on IntelliCard disconnects

### ISSUE THREAD

**Issue by d34d10cc** [ParadiseSS13/Paradise#4565]
I used View Variables on an IntelliCard with an AI in it on my test server, it said network problems but the server was still up. It reconnected 10 seconds later, I tried it over and over, it did the same thing. I would like someone to try this on live and confirm.

**Comment by PsiOmegaDelta** [comment]
Bay occasionally has this issue as well, see https://github.com/Baystation12/Baystation12/issues/11500 for example. The issue is consistent for a particular build but any changes and a recompilation and it goes away/elsewhere.
Makes debugging/fixing.. difficult to say the least.

**Comment by AffectedArc07** [comment]
Cannot reproduce, and likely a BYOND issue. This issue is also 4+ years old, so will be closed
