### ISSUE TITLE
Cable coils change colors

### ISSUE THREAD

**Issue by Cotux34** [ParadiseSS13/Paradise#4566]
**Problem Description**:
Cable coils change colors when you seperate them from the stack

**What did you expect to happen**: 
The piece from the coil should be the same color as the coil initally is

**What happened instead**:
I got a random color of wire after seperating the coil

**Why is this bad/What are the consequences:**
It's just a visual issue, nothing important

**Steps to reproduce the problem**:
1-Have cable coil in one hand
2-Seperate 1 piece off the coil
![nyw6aer](https://cloud.githubusercontent.com/assets/11062431/15755977/dd89d2b2-2907-11e6-996b-a971aac03c5c.gif)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
This only happens to me when I add a piece of cable a different color, add it to an existing stack and then remove it. I think it keeps its color even when added to a different colored coil.

**Comment by taukausanake** [comment]
Rainbow wire coil when?
