### ISSUE TITLE
Progress bars are no longer smooth

### ISSUE THREAD

**Issue by QQCucumber** [ParadiseSS13/Paradise#4579]
#4361 Continuation

This issue is still persistent up to 1545, the release version. I believe it has something to do with what version the server is running according to what I've read on the BYOND forums - it's an incompatibility. So making it an issue here, even though it's not a coding bug per se, seems appropriate. Especially because it needs testing from far more competent people than I.

1539 is the last release that the smooth progress bars work with the server.

**Comment by Iamgoofball** [comment]
downgrade for 1539, 1545 is having some issues

**Comment by QQCucumber** [comment]
Here is the BYOND thread I found in question: http://www.byond.com/forum/?post=2091432

It's been marked as 'Not a bug' because supposedly it works fine when both the server and client are running 1545

**Comment by TheDZD** [comment]
If that's the case, server needs to be updated to 1545 then.

**Comment by QQCucumber** [comment]
It needs testing. The BYOND devs have been wrong before.

**Comment by Tastyfish** [comment]
They definitely work right if both the client and server are 510.1341 or newer.

**Comment by TheDZD** [comment]
At least on a local server, running 310.1545, progress bars update smoothly.

**Comment by Iamgoofball** [comment]
>310

**Comment by TheDZD** [comment]
I dun fukt up.

**Comment by Ar3nn** [comment]
what is with these large as hell version numbers, has byond gone through that many iterations? seriously?

**Comment by PJB3005** [comment]
Yes.

**Comment by Tastyfish** [comment]
Yes.

**Comment by QQCucumber** [comment]
Is the server updated now?
