### ISSUE TITLE
shouting

### ISSUE THREAD

**Issue by Feno4ka** [ParadiseSS13/Paradise#4580]
Where is the config with replicas at the shearing?

**Comment by CrAzYPiLoT-SS13** [comment]
Shearing? I'm pretty sure we don't host sheep. If you mean the hailer, its phrases should be in its file.

**Comment by Feno4ka** [comment]
For example, when the gene is changed, or a drug

**Comment by Feno4ka** [comment]
[https://pp.vk.me/c630029/v630029885/383f7/sY4Pw8WWfEQ.jpg](url) Looks like that

**Comment by CrAzYPiLoT-SS13** [comment]
Not entirely sure what you are talking about. Do you mean the 'asks',
'talks', 'hisses' and such?

**Comment by Feno4ka** [comment]
Yes, need to be translated

**Comment by CrAzYPiLoT-SS13** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/say.dm#L78

They start here, and are defined for every species separately.

**Comment by Feno4ka** [comment]
Thank you!

**Comment by CrAzYPiLoT-SS13** [comment]
No problem! One example of what defining species say verbs would look like
is:
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/silicon/silicon.dm#L18
