### ISSUE TITLE
Silicons say everything they say over the radio to everyone in range

### ISSUE THREAD

**Issue by Little-119** [ParadiseSS13/Paradise#4585]
When any silicon (AI and cyborgs) speaks over the radio, everyone in range can hear what they said, with no indication that it was said over radio. I remember this not happening before, and it makes little sense.

**Comment by Spacemanspark** [comment]
See, I knew this wasn't happening until recently.
This is VERY ANNOYING.

**Comment by Taaketa** [comment]
I'm pretty sure all cyborgs have a radio that is basically a speaker and has always worked this way.
