### ISSUE TITLE
Thrown Projectiles "Stop" One Tile Short of Dense Atoms

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#4589]
**Problem Description**:
Exactly what it says on the tin. As a result, anything above speed 4 fails to hit, and anything thrown at point blank range will hit the thrower instead, even if above speed 4.

**What did you expect to happen**: 
For thrown projectiles to hit the whatever they're thrown at, and hit them no matter what speed the object is travelling at (see below).

**What happened instead**:
They fucking don't.

**Why is this bad/What are the consequences:**
Crossbows are worthless, anything else that throws items incredibly fast probably is too.

**Steps to reproduce the problem**:
Spawn any item that has a throw_speed below 5, such as a hatchet, throw it at a humanoid from a range. Then move into point blank and throw it again. Varedit the throw_speed to something above 4, try throwing it again from a range. Then throw it from point blank. You can repeat the same with a window pane, doesn't just happen with mobs.

**Comment by taukausanake** [comment]
I always thought the throw-at-point-blank where you hit yourself was a feature, having it bounce off whatever it hit back onto you. I think this also happens if the object is one tile away? I don't remember
