### ISSUE TITLE
Can't access terminals

### ISSUE THREAD

**Issue by TheFox00** [ParadiseSS13/Paradise#4590]
**Problem Description**:
What is the problem?

Every time I access a terminal or bring up my PDA, it ether says initiating or in the case of the PDA, comes up all weird. The only ones doing this is the things with black backgrounds. As I've seen.

**What did you expect to happen**: 
Why do you think this is a bug?

Its happened on two different plays, after the 5/2/16 updates.

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

As I play HoP alot, using the ID computer is important. I can't do that.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Nothing else to tell as far as I can tell.

**Comment by TheDZD** [comment]
@Tastyfish Seems to be due to the smooth progress bars for NanoUI.

**Comment by TheFox00** [comment]
Is there no way to fix?

**Comment by TheFox00** [comment]
Windows 7 and original internet explorer guess. I don't use it.
