### ISSUE TITLE
Sec windoors are actually blood-red because they're covered in blood

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#4592]
**Problem Description**:
The blood washes off.

**What did you expect to happen**: 
I.. I don't know if it's.. meant to wash off.

**What happened instead**:
IT WASHED OFF

**Why is this bad/What are the consequences:**
I DON'T KNOW IF I WANT THIS FIXED

**Steps to reproduce the problem**:
SEE GIF. ALSO WORKS ON THE RED WINDOWS SOMEHOW.
https://gfycat.com/PolishedFlawedComet

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: NADA

**Comment by CrAzYPiLoT-SS13** [comment]
What. Leave this in, working as intended

**Comment by FlattestGuitar** [comment]
This has always been the case. That's why you don't let the janitor into the brig.

**Comment by Fox-McCloud** [comment]
Yeah, ultimately this is a compromise.

Space cleaner cleans color off of things back to their initial color---windows are actually colored *after* they're created.

The compromise was this: colorful reagent could color objects and turfs, but there was no way to remove it, so this was added---this is an unavoidable side-effect.

**Comment by Vivalas** [comment]
The blood of a hundred clowns.

**Comment by taukausanake** [comment]
I just hope you don't start cleaning all the colored windows. Also, can that actually be considered a thing IC? A rumor at least?

**Comment by Tastyfish** [comment]
I mean, _technically_ this could probably be fixed with OOP, but it seems more fun to think they're just stained with horrible.
