### ISSUE TITLE
Days on greyed out jobs not going down

### ISSUE THREAD

**Issue by Rapidvalj** [ParadiseSS13/Paradise#4594]
**Problem Description**:
The days on time locked jobs until I can select them aren't going down. The first time I connected was about 4 days ago.

**What did you expect to happen**: 
I expected the time to go down, so after that many days I'd be able to play as the job? I'm not sure if I'm missing something?

**What happened instead**:
Well, the time isn't going down. They've been locked at various times for about 4 days. Here's a screenshot http://i.imgur.com/gjESN8e.png

**Why is this bad/What are the consequences:**
It currently prevents me from ever playing as the majority of jobs?

**Steps to reproduce the problem**:
I'm not sure, there isn't really a way to reproduce it because I have no idea why its happening and its only effecting me as far as I know. I guess just ask me if it's gone down?.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I don't believe anything out of the ordinary was happening, and it was staying the same every time I connected to the server. I've also had issues interacting with things recently, mostly the shuttle console in cargo, but this issue has been going on longer than that one.

**Comment by chopchop1614** [comment]
Having the same issue only I have a second but as well: I can't drag people onto me or buckle myself into chairs.

**Comment by chopchop1614** [comment]
Error*

**Comment by MediaGoat** [comment]
Its been a week since i started playing and the job timer hasnt moved a bit. Since then i finished a number of rounds and nothing happened. I am "MGhost" ingame.

**Comment by TheDZD** [comment]
Appears to be an SQL issue, will update you all on when it is resolved.

**Comment by megatiger78** [comment]
would this be connected to the antag preference reset?

**Comment by chopchop1614** [comment]
Any updates?

**Comment by TheDZD** [comment]
This has been fixed, days left on time-locked jobs (and antagonists) should now properly count down.

**Comment by chopchop1614** [comment]
Was this fixed an hour ago? If so, could you add the 10 days to my timer?
