### ISSUE TITLE
*johnny emote is not working

### ISSUE THREAD

**Issue by sasanek12** [ParadiseSS13/Paradise#4596]
**Problem Description**:
What is the problem?
using johnny emote gives no outcome whasoever, according to @KasparoVy it should.
**What did you expect to happen**: 
Why do you think this is a bug?
It's currently emote with no use whatsoever.
**What happened instead**:
How is what happened different from what you expected?
I expected something to happen upon using emote.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's not really that important, but could be fixed.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
type say "*johnny" into command bar
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing related.

**Comment by Fox-McCloud** [comment]
It requires a paramter; if you fail to supply one it fails. Using it with a parameter 100% works.

*johnny-Buttface McGriffer

for instance.
