### ISSUE TITLE
Cyborg connection prompt to AI sometimes bugs

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#4598]
**Problem Description**:
What is the problem?
Occassionally as AI, I'll notice that when a new Cyborg is spawned/created, it'll say the following:

New cyborg connection: <name here>

Cyborg reclassification detected: <same name>

New cyborg connection: <name here>

**What did you expect to happen**: 
Why do you think this is a bug?
I expect it to not somehow immediately reclassify?

**What happened instead**:
How is what happened different from what you expected?
It spams the chat for the AI and about half the log is pushed out of sight, which can be annoying.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Not anything major, just quality of life to fix it. It still serves its purpose of notifying the AI that the cyborg exists.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

> be AI
> have a cyborg spawned (on local, spawn a cyborg entity yourself)
> read output

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Contrabang** [comment]
Not able to reproduce and no one else has been able to reproduce it either. Fixed
