### ISSUE TITLE
Space Pods - Check Seat and Equipment Removal Issue

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#4599]
**Problem Description**:
There are two issues noted: When you use the Check Seat verb, it will pull out things that it shouldn't, such as weapons and equipment, if they are inside the spacepod contents variable, but not in the equipment_system.installed_modules variable. Doing this does not clear the system's variable itself, either, but that's because it shouldn't have to.

The second issue is when you remove equipment normally, it doesn't clear the corresponding equipment from equipment.system or item from installed_modules. It does successful clear the contents and gives the item back to the user.

It almost seems as though the issue stems from equipment_systems.installed_modules not being a list variable, or not working correctly as one. The first issue checks the variable of the installed_modules and removes anything, for equipment, not in that listing. The second issue is failing to clear either and seems to be a bug that requires further study.

**What did you expect to happen**: 
1) Since there were no missing items in the pod, nothing.
2) Remove equipment, be able to reinstall a new piece of equipment to pod.

**What happened instead**:
1) Could pull out unintended equipment with Check Seat verb.
2) Got removed equipment back, couldn't install new or old equipment to pod at all.

**Why is this bad/What are the consequences:**
1) Breaks the pod by being unable to properly pull out equipment if it's already pulled out.
2) It makes it impossible to switch out pod equipment without admin assistance. 

**Steps to reproduce the problem**:
1) Equip any two equipment to the pod. Get in pod. Use Check Seat verb.
2) Equip anything to the pod. Crowbar pod open to get to equipment. Pull equipment out. Either attempt to pull out same equipment (it teleports to you) or put in new equipment.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was reported to me by Davidchan. Observing as admin and testing it myself. Nothing seemed out of the ordinary.

**Comment by Davdichan** [comment]
The only thing I have to add to this is that the Power Cell is the only item that could be reliably removed and reinstalled. Because items weren't really 'removed' from the pod, attempting to remove it a second time would teleport [or rather clear] the item from its position to your active hand, but the item would still be in the 'remove item' list if the pod was crowbared open.

Another thing was that I couldn't eject anyone from the cargo position of the pod. Unload Cargo replied I did not have a cargo system installed, despite having a passenger on board, had to get out and grab intent the pod to pull people free.

**Comment by TheDZD** [comment]
@IK3I

**Comment by Twinmold93** [comment]
It seems there is another bug possible related to this that causes it so that when you add in the secondary seat, it doesn't increase max_passangers accordingly (or decrease it, or affect it at all). I believe it's also related to the installed_modules problem.
