### ISSUE TITLE
God Hand (And other nodrop items) can be 'put' into lockers.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#4600]
This causes you to "clone" the god-hand, which is kinda incredibly buggy. You'd have to test for yourself what I mean, because I have no way of describing what the hell is going on. It's kinda like it puts the god-hand in two places at once.

**Comment by DaveTheHeadcrab** [comment]
I wasn't able to reproduce this, tried both mousedrop and regular clicks on crates and lockers to no success.

**Comment by fludd12** [comment]
Huh. I'll see if I can get a video if I can reproduce it. Fox said this was a common error with nodrop, but I haven't seen it before.

**Comment by Fox-McCloud** [comment]
For clarity, I said this would apply to any NODROP item---I tried to replicate it, too, but I was unable.

I tried the same steps and everything, but...couldn't, either. I know it most definitely happened, as I was the one to correct this for you, in-game, but....something went realllyy haywire.
