### ISSUE TITLE
Water and buoys are draggable

### ISSUE THREAD

**Issue by Glorken** [ParadiseSS13/Paradise#4616]
**Problem Description**:
On the beach mission, the diving buoy and the water are both draggable.

**What did you expect to happen**: 
You shouldn't be able to drag the scenery, and the buoy is presumably meant to stay at sea.

**What happened instead**:
I could drag them both around like normal items.

**Why is this bad/What are the consequences:**
The water now looks ugly, and the buoy is next to the gateway.

**Steps to reproduce the problem**:

1. Go to the beach.
2. Drag the water.
3. Drag the buoy.
4. Cry because the game is unplayable.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
The gateway mission was beach, and I was a crab.

**Comment by Glorken** [comment]
Also, the buoy can be moved onto the station proper and still used.

**Comment by Glorken** [comment]
You know, you could keep the anchor-dragging in, and use it for magic tricks.

**Comment by TheDZD** [comment]
@FalseIncarnate Is this intentional or no?

**Comment by FalseIncarnate** [comment]
the bouy should not be draggable. neither should water, but i assume that was not my fault
