### ISSUE TITLE
Difficulty accessing consoles/vending machines etc.

### ISSUE THREAD

**Issue by Chieftain101** [ParadiseSS13/Paradise#4622]
**Problem Description**: 

Difficulty accessing consoles/vending machines etc.

What is the problem?

Well I'm having difficulty accessing consoles/vending machines etc. It seems that every time I attempt to access any console, vending machine or alarm it doesn't load the page and just says "Initiating." No matter how much time has passed nothing happens.

**What did you expect to happen**:  

Well I expected to access these consoles/vending machines to either;

A. Do my job.
B. Do my job/enjoyment.

Why do you think this is a bug?

Well because it's not working, I've cleared my cache twice, uninstalled and reinstalled BYOND, checked if I'm on the right version about x20 and asked an admin named Twinmold about the issue. They said to go here.

**What happened instead**:

I feel these questions are a bit repetitive. Nothing happened, the actual issue is that I can't use any of these devices.
 
How is what happened different from what you expected?

Yes.

**Why is this bad/What are the consequences:**

A. It doesn't allow me to access anything.
B. It doesn't allow me to access anything.

Why do you think this is an important issue?

Because I was just informed by Twinmold that it's happening to multiple people.

**Steps to reproduce the problem**:

Step 1: Feel like 2d spess men.
Step 2: Load up the server from my BYOND client.
Step 3: Join the server, walk to the nearest vending machine/console and find it doesn't work.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

No idea what game-mode, I was doing nothing and nothing felt out of the ordinary.

[https://gyazo.com/d500033d7da70b3c0fd6e328fe9c9834](url)
[https://gyazo.com/948909848949c5df8bc0876e72323fd1](url)
[https://gyazo.com/c411be12fd0393e7bd4d1e7f81fe7db9](url)

Hopefully these photos help a bit.

**Comment by Twinmold93** [comment]
I would like to point out that this isn't the first known instance, and has been happening a lot to people. While it hasn't affected everyone, multiple people have had this same issue.

**Comment by Cotux34** [comment]
Can confirm that, also I kind of found a temporary fix. When I host a local server and join it and open a computer in that and go back to paradise, it usually works for the entire round though it gets broken again after the server restarts at round end

**Comment by CrAzYPiLoT-SS13** [comment]
@Tastyfish, is there something you missed in your nano fix? :P

**Comment by TheDZD** [comment]
Same issue as #4590, *should* be fixed next time the server is patched.

**Comment by Chieftain101** [comment]
Thanks for commenting, I completely forgot I posted this. I don't exactly play SS13 as much as I used to so this slipped my mind.
