### ISSUE TITLE
Cyborg zipties are permanently lost when used on orange shoes

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4631]
Similar to engineering cyborgs with their analyzers being eaten by cameras

**Comment by Ar3nn** [comment]
I believe the analyzer problem was fixed I tried it recently and it was fine.

**Comment by DaveTheHeadcrab** [comment]
To make legcuffs.

**Comment by Davdichan** [comment]
Strange, I thought only actual cuffs worked on orange shoes.

But yeah leg cuffs are something you want/need for extra violent or uncooperative prisoners as it forces them to walk so they can't yakity sax if they happen to get bumped out of your grip.
