### ISSUE TITLE
Team antagonist objective swapping

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#4635]
**Problem Description**:
As a cultist, objective swapping with sacrifice is nonexistant. If someone cryos, they count as gibbed and are un-sacrificable.

**What did you expect to happen**: 
The objective to swap to another target, who isn't cryod.

**What happened instead**:
The cryod target completley denies the cultists any chance of getting their sacrifice objectives.

**Comment by Spacemanspark** [comment]
New meta: cryo entire security team and heads of staff.

**Comment by Ar3nn** [comment]
@Magikarpet just ahelp if you cannot find your objective, they'll switch your objective if its unattainable.

**Comment by Magikarpet** [comment]
@Ar3nn  I'm talking about team antagonists. IIRC unless you mess with the gamemode ticker or whatever it's impossible to do that, and even I think I'm talking out of my ass with the objective being in the antag ticker. There is 100% no way to use the traitor panel to assign a new objective, unless my knowledge on the traitor panel is ancient.

**Comment by Ar3nn** [comment]
Oh, so they physically cannot change your target? that bloooows.
