### ISSUE TITLE
Abductors replace organs

### ISSUE THREAD

**Issue by QQCucumber** [ParadiseSS13/Paradise#4640]
Right now Abductors seem to turn organs into 'fleshy mass' and this causes all sorts of confusion like 'how are they living without a heart!?' after a surgery.

Not to mention with the upcoming defib changes it's going to cause strange behavior where if you die after having the fleshy mass removed you won't be revivable.

**Comment by Fox-McCloud** [comment]
This isn't a bug, at all; it's very much intentional that the organ rips out the heart and you put the fleshy mass in, instead.

As for the latter "problem", that's easily solved by yanking out a monkey heart and putting it into the person.

**Comment by QQCucumber** [comment]
So it's intended for people to be alive without a heart?

**Comment by Fox-McCloud** [comment]
Yup.

Speshul ayylmao surgery.
