### ISSUE TITLE
AI core weirdness

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#4659]
**Problem Description**:
What is the problem?
Admin tools can't recreate an AI after removing a user from it
**What did you expect to happen**: 
Why do you think this is a bug?
Admins to be able to spawn an AI core or build one from scratch with spawned equipment and be able to insert a brain into it and it work
**What happened instead**:
How is what happened different from what you expected?
an admin built 17 AI cores from different stages of completion (from plasteel and tools to spawning a blank core and shoving parts in) and none of them would accept positronics to complete.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
De-spawning an AI (especially when it cannot be re-used) has serious impact on the round and could cause antags to fail objectives if it is overlooked.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Be AI
have yourself removed from the AI mob
be unable to re-use core
attempt to spawn new cores and fail to use them
cry
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
/shrug
Elysian_Prince was the admin on duty that round.

**Comment by Contrabang** [comment]
Going to keep this open as spawning an AI mob spawns an empty AI core object and not mob, which players cannot be assigned to easily.

**Comment by DGamerL** [comment]
Heya, this was fixed in #22769 ! Thanks for making this report!
