### ISSUE TITLE
Changeling items persists throughout deactivation

### ISSUE THREAD

**Issue by Artorp** [ParadiseSS13/Paradise#466]
Steps to reproduce:

1. Be a changeling with arm blade power
2. Activate arm blade
3. Deactivate arm blade

The arm blade will be removed from your hand and is not in our contents, but in every other way the game still thinks there's an arm blade there.

* The mob sprite is not updated
* Attacking something acts like you're holding an arm blade
* Using the arm blade power repeats the "We assimilate the blade back into our body." message.
* It is not possible to put items into the hand slot which used to contain the arm blade.

After a seemingly random amount of time the arm blade is properly removed, picking something up updates the sprite.

This also applies to every other changeling item power:

* Arm Blade
* Organic Shield
* Organic Space Suit
* Chitinous Armor

PS: Discovered this bug on a local server, have yet to confirm it on the live server.

**Comment by Markolie** [comment]
@TheDZD

**Comment by TheDZD** [comment]
Seems as if it might be related to the inventory updating issue that has popped up recently, I noticed no such behavior when they were initially implemented.

**Comment by Markolie** [comment]
That's highly unlikely. The inventory update issue only applied to masks and head items.

**Comment by Fox-McCloud** [comment]
I can confirm this wasn't an issue when DZD and I tested lings and such.

**Comment by Markolie** [comment]
Related to the NO_DROP refactor then?

**Comment by TheDZD** [comment]
Possibly, although I do not believe I noticed it happen initially. Sprites also seem to not update when stripping a mob, which may be related to the same issue.

**Comment by Markolie** [comment]
Well, this one goes a bit deeper than the sprite updating. It doesn't seem to register the armblade being deactivated, as it still shows the message.

**Comment by Artorp** [comment]
It's related to the newly ported vg garbage processor.

This commit does not have the bug: https://github.com/ParadiseSS13/Paradise/commit/43f589516d197bdbb4c239a03eaf012ec171cb4d

This commit does: https://github.com/ParadiseSS13/Paradise/commit/ae04cce2206551560b76b9397412ff3a8b74a242

**Comment by TheDZD** [comment]
I would guess it is qdel related then. Probably best to consult @ZomgPonies

**Comment by Markolie** [comment]
It is caused by the qdel'ing, yes. @ZomgPonies, for now I'm changing it to use del's, but we should definitely look into this.
