### ISSUE TITLE
Living, Heartless Bodies.

### ISSUE THREAD

**Issue by MindLeaker** [ParadiseSS13/Paradise#4664]
**Problem Description**:
After tinkering around with farwas, and then humans, it seems that it's possible to remove all vital organs aside from the brain from a body and keep them alive. Furthermore, after the heart is removed, the entire system collapses in on itself, and the lungs can also be removed and the body defibbed.

**What did you expect to happen**: 
For starters, once the heart is removed the patient should either have an unrecoverable heart attack or simply die on the spot.
Secondly, even if the heart is removed and the body stabilized, the lungs should still immediately render the body undeffibable.

**What happened instead**:
When the heart is removed, the slow damage does not kill it immediately, and the body can be stabilized by simply applying the active defib to the living person's chest. The failure message from the defib does not affect this.
The lungs should also render a body undeffibable if removed, although this seems to be a result of the code bugging out to hell once the real heart is removed.

**Why is this bad/What are the consequences:**
This obviously upsets the balance of many things, people with assisted organs can simply be removed and rendered immune to EMPs, etc.

**Steps to reproduce the problem**:

- Grab (un)willing subject, perform Organ Manipulation surgery as normal until you reach the "Manipulate Organs" step

- Remove heart, patient will then begin taking moderate oxyloss as the heart attack occurs, apply defib vigorously. Ignore the "Defibrillation Failed" message.

- Laugh maniacally as the patient magically stabilizes, the medical scanner will read a bpm of ~80, but will show no organs present

- You can also remove the lungs at this point, then defib without consequence.

- You've now made the Tin Man of the Wizard of Oz, congratulations.

From what I can see, this bug can easily be resolved by adding an instant death upon heart removal, or make the heart attack only stabilize when the defib is /successful/

EDIT: Removed a misconception I had over abductor organs

**Comment by Fox-McCloud** [comment]
>abductors organs can be extracted without consequence

Not a bug. I dunno how many times I've told people this, but this is absolutely not a bug.

**Comment by MindLeaker** [comment]
> Not a bug. I dunno how many times I've told people this, but this is absolutely not a bug.

It's not so much that it's a bug, but the organs can be removed and there's no _danger_ to remove the organ. There's meant to be a replacement needed, not an empty space

**Comment by Fox-McCloud** [comment]
Uh, no, that is absolutely not the intention of abductor organs being removed, at all. For abductors, they remove the heart without risk because woo-woo speshul behavior or something like that. Likwise, abductor organs are also non-vital and are meant to be actively removed.

This behavior (specifically) is 100% intentional and not even remotely in the realm of a bug or oversight.

**Comment by MindLeaker** [comment]
Even disregarding the sentence on abductors, this is still a very glaring issue no matter how you look at it, if I'm correct, this can extend over to IPCs as well, making their inner microbatteries removable and therefore immune to internal EMP damage. It needs to be fixed, because even when I mess around with it it feels pretty potent.

**Comment by Fox-McCloud** [comment]
Oh yes, definitely, but there's this rumor persisting that the abductor stuff is all a bug or intentional, and it absolutely isn't, so...I wanted to make that absolutely clear. The other though? Yeah, major issue.

**Comment by pinatacolada** [comment]
oh what the fuck

**Comment by MindLeaker** [comment]
Alrighty, didn't see that, I'll close it up then
