### ISSUE TITLE
Spraycan graffiti spraying is broken.

### ISSUE THREAD

**Issue by Magikarpet** [ParadiseSS13/Paradise#4666]
**Problem Description**:
Using any graffiti spray with a spraycan causes a random cluster of dots to appear, this is not the case if you use a crayon.

**What did you expect to happen**: 
The spraycan could be used to spray out graffiti.

**What happened instead**:
A cluster of dots, rendering a spraycan nearly worthless as a fun joke filled graffiti tool.

**Comment by Spacemanspark** [comment]
Literally unplayable.

**Comment by SirBloodBuske** [comment]
Does this for crayons too, my immersion is broken can't play, plz restart.

**Comment by FalseIncarnate** [comment]
I believe the issue is the ported graffiti is improperly set up for colors, thus you get a broken "grayscale" version.

**Comment by taukausanake** [comment]
I thought the random dots happen when the can is empty?

**Comment by Magikarpet** [comment]
Nope, IIRC the can dissapears when empty, at least when clicking on yourself to huff it. You can also click on players to paint their faces certain colours(With a short stun), which I've done after getting the dot spray multiple times.
