### ISSUE TITLE
Mining airlocks

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#467]
Mining airlocks will stop working halfway, making them need to turn back on to finish. This happens either way of going in or out.

**Comment by Markolie** [comment]
At what point of the round was this? If someone forced the airlock while the airlock was depressurized, refilling it may have used up the canister, which means it can't finish. You'll have to replace the air canister in that case.

**Comment by Earthdivine** [comment]
At all points, the Air canister still had air in it, but the vents would start then stop and sit there, requiring them to be turned back on.
