### ISSUE TITLE
Chaplain Null Rod Armblade Doesn't Appear in Examine

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#4676]
**Problem Description**:
Simply put, the chaplain's armblade variant of the null rod doesn't appear on examine, which can be very problematic in a changeling round.

**What did you expect to happen**: 
Examine message of armblade on chaplain.

**What happened instead**:
No additional message.

**Why is this bad/What are the consequences:**
Simply put, it makes it so the chaplain looks like a changeling, which can be a very serious issue, leading to execution for being said changeling, because there are no ways to prove he isn't a changeling, as far as I can tell.

**Steps to reproduce the problem**:
Chaplain has null rod.
Makes null rod to armblade.
Examine chaplain.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Traitor and vampire round. I was Captain. Head of Security and I noticed their armblade, which looked extremely real (because even the foam armblade has a message, iirc).

**Comment by Lady-Luck** [comment]
Honestly I wish changeling armblades appeared in examine as well. My eyesight is very poor and I have trouble seeing them.

**Comment by Spacemanspark** [comment]
This is intentional.

**Comment by KasparoVy** [comment]
CHAPLING!?!@ :SKULL:

**Comment by Fox-McCloud** [comment]
Intentional, and not a bug.
