### ISSUE TITLE
Secure Briefcase Capacity

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#4678]
Paper bins do not fit inside secure briefcases. As an avid IAA player, I find this to be a travesty, as securing my very important supply of paper is of the highest priority, and a plain briefcase just doesn't get the job done. # #

**Comment by Lady-Luck** [comment]
I think the problem is less the briefcase and more the paper bin's size

**Comment by Deanthelis** [comment]
Negative. It fits fine in normal briefcases.

**Comment by Bigtimetripod** [comment]
@deanthelis Topic is about secure briefcases, not the normal ones.

**Comment by KasparoVy** [comment]
Pretty sure I got it figured out. Testing a fix right now.
