### ISSUE TITLE
Clown Door won't melt down

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#4689]
**Problem Description**:
What is the problem?

Trying to melt the clown door for Banarium does not work.

**What did you expect to happen**: 
Why do you think this is a bug?

The door should melt into steal plates and banarium. But does not.

**What happened instead**:
How is what happened different from what you expected?

The door remains in place and produces no product.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Not important. Just clowns now have to go further afield for Banarium.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Follow the guide to deconstruction on the door. Try to weld it down (it was taken to robotics to me) and it will produce mesages. "You welded the clown plating off!" No plating will appear.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

It's the clown door. The banrium should drop from it after welding it in the final stage. Round had swarmers and traitors in it.

**Comment by pinatacolada** [comment]
jet fuel cant melt bananium doors

**Comment by Bigtimetripod** [comment]
Legends say that it takes 20,000 C temperature plasma fire to melt bananium off doors.

**Comment by Davdichan** [comment]
That's just propganda.

Everyone knows the chemical compound of nothing was specifically designed to eat through the indestructable bananium.
