### ISSUE TITLE
Ayy, NADtheft ahoy!

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4690]
**Problem Description**:
Abductors can take the NAD off f Z1 via their teleportation.

**What did you expect to happen**: 
Why do you think this is a bug?

The NAD should _Never_ be able to leave Z1. My Agent was able to teleport with it. We Ahelped upon realizing he still had it. It should have been removed from his inventory and warped randomly.

**What happened instead**:
How is what happened different from what you expected?

NAD ended up on the Ayy ship. This is a glaring problem.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

The NAD can be functionally removed from play by Abductors.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Be an ayy. Pick up the nuke disc/abduct someone who has it. Recall to ship/teleport target to ship. Remove disc from bag and place on table.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

We had a wizard and a statue running around at the time. As well as a gamma ERT.

**Comment by Davdichan** [comment]
Ayy teleportation technology, so mysterious to NT that it bypass failsafes and security systems around their most treasured item. Surey it is powered by magnets.

**Comment by KasparoVy** [comment]
Legend says it's powered by pure meme

**Comment by Spacemanspark** [comment]
ayy lmao get dat fukken disk

**Comment by Twinmold93** [comment]
The error with it is likely because it teleports immediately to Z-Level 2, which the NAD is allowed to go to. A simple fix would be adding in a contents check for the NAD on the person being teleported to the abductor ship.

**Comment by Fox-McCloud** [comment]
Dunno if this is really worth fixing or not.

If it's an abductor round, it doesn't really matter, and if it's an event, well, that can only occur after the 1 hour mark AND they have to get the person who has it specifically.

It would really be no different than an abductor getting an HoS and they kept the gun on their ship--in that instance.

**Comment by AceMcLazer** [comment]
@Fox-McCloud Yea, and this is an inconstancy in the NAD's behavior, as we're supposed to understand it IC'lly The HOS's gun does not teleport, period. so once it is left on the abductor ship, effectivlly gone forever.

 I would say its almost an inconsistency in how we're supposed to know it and.....the steal NAD objective traitor would get fucked over.

**Comment by Fox-McCloud** [comment]
Any steal objective is going to get messed up with abductors if they take the person who has that item, strip it, then keep it in their ship.

**Comment by AceMcLazer** [comment]
Yea, but The NAD's behavior should be constant. Any steal objective is not the same as NAD IMO.

**Comment by datlo** [comment]
This is working as intended as the abductor ship is on z2 and the disk is allowed to be on z2.

This is obviously a unique edge case, though, and might be worth coding a special check for.
