### ISSUE TITLE
Borgs cannot drop items from magentic gripper

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#4696]
**Problem Description**:
What is the problem?

Borgs cannot drop items from magentic gripper

**What did you expect to happen**: 
Why do you think this is a bug?

There is a drone command that allows items to be dropped from the gripper. Using the command under the drone option does not drop the item when activate on a borg unit. Press Z when magnetic gripper is active does not work either.

**What happened instead**:
How is what happened different from what you expected?

Items not dropped.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Makes borgs magentic gripper useless if they pick an item and cannot place it into the appropriate device.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Pick up any item. Attempt to drop it with the magentic gripper on, or drone command.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Traitor game mode. Trying to repair APC using a powerboard and removing the battery as borg. As a new powerboard was in the magnetic gripper and couldn't be dropped.

**Comment by Davdichan** [comment]
@Taaketa One thing I have noticed is you stometimes have to right click the gripper in your inventory slot and manually tell it the drop command. Dunno if it always works but the drone command never seems to work for me so you just have to right click and drop that way. Beats the old way of having to find a table to spit it out on.

**Comment by Taaketa** [comment]
@Davdichan I know but also using the Z key with the magentic gripper used to work as a shortcut to drop it too. So I think there is some kind of issue with the command being connected to that too.

**Comment by DesolateG** [comment]
This is not a bug. you right click on the magnetic gripper and drop item.

Z key is used on items held by the magnetic gripper to interact with, such as an airlock controller board.

**Comment by Crazylemon64** [comment]
@DesolateG This appears to be talking about the "drop item" verb under the "Drone" tab

**Comment by alex-gh** [comment]
Works for me. 

Both "right click -> drop gripped item" and "drop gripped item" in the drone tab.

I mean it is not great that it is in the Drone tab but eh...
