### ISSUE TITLE
Hungry Hungry Cryotubes (And Sleepers/Bodyscanners aaand presumably DNA Machines)

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4701]
**Problem Description**:
Cryotubes, Sleepers, Bodyscanners, and DNA Machines delete hardsuits, as well as other items if you remove them while inside one and or fall pass out inside one.

**What did you expect to happen**: 
Why do you think this is a bug?
Expected is that the item in question is dropped on the floor rather then cast into the depths of oblivion.

**What happened instead**:
How is what happened different from what you expected?
The objects in question were cast into the Void. Consumed by the Geometer, never to see the light of day. Aka they were totally deleted from the play area.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Consequences are rather valuable limited item (Hardsuits) are possible to totally remove from play, as well as anything else the person has on them and accidentally (Or intentionally) deletes.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue. 
Get placed in cryo. Due to temp resist due to hardsuit, they can drop whatever the shit and delete it before removing hardsuit to delete that also.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Nothing else of note.

**Comment by Bigtimetripod** [comment]
Did ye also deconstruct the machine? Maybe its on the bottom of the tube and just cannot reach when in a one. Try to deconcstruct ( would do it my self but workworkwork...)

**Comment by Twinmold93** [comment]
The issue is they get set into the machinery's contents, which you cannot normally access. Deconstructing it should give it back out. It might be nice for an 'eject misc' ability to eject things that get stuck...
