### ISSUE TITLE
You can't leap over lube

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#4707]
If you try to use the leap power in front of space lube, you still fall as you pass over.

**Comment by tigercat2000** [comment]
not much you can really do about this, leap literally just moves you multiple tiles quickly

**Comment by Twinmold93** [comment]
It'd require an additional value for jumping/floating (if it doesn't already exist) with a check in water/lube to not affect those who are in this state.

**Comment by FalseIncarnate** [comment]
There is a var on mobs to allow for this: `flying`

When you have this flag, you won't trigger common slip hazards like wet floors (including lube), banana peels, and even be able to cross tables and racks. It would be entirely possible to make leap briefly grant the flying var (until you land) and thus let you parkour over tables in the bar while the bartender fires wildly at you.
