### ISSUE TITLE
Forensic scanner doesn't search stuff

### ISSUE THREAD

**Issue by Cotux34** [ParadiseSS13/Paradise#4720]
**Problem Description**:
Search function of the forensic scanner doesn't do anything

**What did you expect to happen**: 
Something to happen when I input blood/name/prints

**What happened instead**:
Nothing at all
**Why is this bad/What are the consequences:**
The scanner still scans but can't search records

**Steps to reproduce the problem**:
Use scanner
Put in something, hit OK
Nothing happens

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing else

**Comment by Fox-McCloud** [comment]
@DaveTheHeadcrab
