### ISSUE TITLE
It is no longer possible to shoot yourself with guns properly.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#4728]
As the title states. It's impossible (at least as far as I can tell, and I've experimented quite a bit) to shoot yourself normally like it was possible before the gun refactor.

This especially hurts the healing staff, which you can no longer use to heal yourself, but other guns being able to shoot you were fun to have as well.

Not precisely a bug, but I think it may have been removed accidentally, so I'm just putting this here.

**Comment by TheDZD** [comment]
Were you actually able to directly shoot yourself with anything besides wands previously (outside of suicide, of course)? I'm certain if you tried that you'd just end up bashing yourself with the gun. Wands still retain there ability to use on self.

**Comment by Fox-McCloud** [comment]
@TheDZD you were able to shoot yourself with any gun, before, but I'm pretty sure this was intentionally removed by TG at some point, especially for staffs.

The staff of healing, for instance, specifically prevents suiciding with it, with the comment "stops people from healing themselves by committing suicide".

If you could self-target with guns, then you could bypass this, for sure, and it's quite obvious, from commenting, that the staff of healing isn't meant to be something you can use on yourself.

**Comment by Spacemanspark** [comment]
Well, that's what /tg/ wanted to do, yes.
Could we not re-add the functionality?
