### ISSUE TITLE
Document objective is bugged

### ISSUE THREAD

**Issue by wotan90** [ParadiseSS13/Paradise#473]
My objective was to aquire the red document from scientist vinny and to not loose the blue one. Furthermore i had to escape on the shuttle alive. I had both documents in the box in my backpack, but the objectives of getting the red one and holding the blue one counted as failed.

Screenshot: http://www.directupload.net/file/d/3913/drd66y9r_jpg.htm

**Comment by TheDZD** [comment]
I'll see if I can replicate this on a local server, I have a feeling it might be due to recursive item checks not making it all the way to the documents, which are in a folder that is in a box that is in a bag that is in a mob.

**Comment by Markolie** [comment]
A folder is not an /obj/item/weapon/storage, so its contents aren't checked. DZD, will you take care of fixing this?

**Comment by TheDZD** [comment]
I should be able to get a fix out later today when I have spare time.

**Comment by Markolie** [comment]
:thumbsup:
