### ISSUE TITLE
IPC Monitor Reconstruction. Failure to reconstruct.

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4760]
**Problem Description**:
What is the problem?
Although IPC monitors should be repairable when disfigured by damage via Cybernetic Repair surgeries according to the changelogs and code, it appears as though they do not. This appears to be a bug. Likely in the form of misplaced punctuation or something.

**What did you expect to happen**: 
Why do you think this is a bug?
As stated by the various changelogs, it's assumed that I could fix an IPC's monitor with cybernetic repair surgery targeted at the head.

**What happened instead**:
How is what happened different from what you expected?
Cybernetic repair surgery does not fix the disfigured IPC monitor.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Minor issue but it results in IPC's being permanently disfigured from EMP and high levels of damage.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Disfigure an IPC. EMP works. Rez them fully. Attempt cybernetic repair surgery on their head.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Disfigurement was induced by a Revenant EMP.

**Comment by Crazylemon64** [comment]
The reason is that the IPC is getting "Husked" - meaning they will lose their name no matter what, and fixing the monitor won't repair that

**Comment by Fox-McCloud** [comment]
Yeah, what @Crazylemon64 

This isn't a bug, per se, it's just less obvious on IPCs.
