### ISSUE TITLE
Temperature gun doesn't recharge

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#4762]
*pew, pew, pew*,
*click, click*
"Wha?"
***click, click***
***CLICK CLICK***

Temperature gun does not self-recharge as it used to. You need to use a recharger. Again, not sure if intended or not, @TheDZD

**Comment by TheDZD** [comment]
Unintended, it was probably something to do with the special snowflek battery that temperature guns had, which I nuked and replaced with a normal battery (after adjusting shot costs).
