### ISSUE TITLE
Ei Nath organ ejecting is slightly bugged

### ISSUE THREAD

**Issue by Midaychi** [ParadiseSS13/Paradise#4763]
**Problem Description**:
EI nath will eject organs, but will eject the brain separate of the head, and it won't respect if you have mechanical or assisted versions of the organs.

**What did you expect to happen**: 
If you have mechanical or assisted organs, for them to come out mechanical or assisted.

**What happened instead**:
Organic trash lie organs and brains still inside heads (unless you're a machine person I guess)

**Why is this bad/What are the consequences:**
Muh Immulshions. Also brain removal for some reason.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Have mechanical or assisted organs.
2. Get Ei Nath'd
3. Hey, my eyes used to be mechanical!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Wiz.

**Comment by LittleBigKid2000** [comment]
Did some testing. If I EI' NATH a person with mechanical eyes, then transplant those eyes to someone else, they still show up as assisted.

**Comment by Midaychi** [comment]
Weird

**Comment by Crazylemon64** [comment]
@Midaychi I don't think the eyes have a different sprite if mechanical - there's currently no way to tell the difference when the organs are outside of the body. Thus, this is a sprites issue

**Comment by TheDZD** [comment]
Yeah it's a sprite issue for mechanical/assisted organs. As far as brains, it's intended that they get popped out separate of the head with Disintegrate.

**Comment by FlattestGuitar** [comment]
Is this really an issue?

**Comment by FunnyMan3595** [comment]
Exploded someone with cybernetic eyes, got cybernetic eyes. Looks like this isn't broken anymore.
