### ISSUE TITLE
Zone Selection and Active Hand highlighting overlays are borked.

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4778]
@monster860 

The highlighted hands and currently targeted zone are no longer visible/displayed. I'm sure there's other things that have broken because of this, too.

I think you can see why this is a major major problem.

**Comment by Fox-McCloud** [comment]
Derp, this is on me; forgot to update my BYOND version.

**Comment by monster860** [comment]
Yeah, you needed to have the lastest BYOND, which has FLOAT_PLANE.
