### ISSUE TITLE
Borgs can still binary after EMP

### ISSUE THREAD

**Issue by Midaychi** [ParadiseSS13/Paradise#4782]
**Problem Description**:
What is the problem?
When Emp'd or otherwise stunned, borgs can still binary.

**What did you expect to happen**: 
Why do you think this is a bug?
I expected EMP to cut off communication and allow antags a chance to deactivate the cyborg before they report to their robotic overlords.

**What happened instead**:
How is what happened different from what you expected?
:b Robusting me in library
<ai> SEC TO LIBRARY

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's a gameplay balance issue. Emps are supposed to be the way that antags can panic hide their presence and cause panic for a short duration, in addition to hitting mechanical targets with damage.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be borg
2. Get emp'd
3. Talk on binary fine

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by tigercat2000** [comment]
not a bug afaik
binary is seperate from their radio module

**Comment by Midaychi** [comment]
But shouldn't it become disabled temp like any other communication method?

**Comment by Ar3nn** [comment]
Yeah, borgs are in complete lockdown for like 5 seconds after an EMP, but they can still :b
