### ISSUE TITLE
Lost Vox Species Option

### ISSUE THREAD

**Issue by YummyToast** [ParadiseSS13/Paradise#4783]
Posted the issue in the server a bit ago. Here's the convo that got me here.

 **Adminhelp to-Elysian_Prince: It's aight, just checking hoping to fix it before round end so I can have it working next round. I'll copy paste last message: Hey, question. I used to play on Paradise quite a bit but went really inactive since then, last time I played I remember Shadowlings being new. Anyway, back then I had purchased Vox with my karma points and played on my character Zikirakatel for quite some time. Odd thing is, now whenever I try to go to Setup character and go to his slot he's a human and I don't have Vox in my species options. In addition it shows I can buy Vox in karma shop and yet I only have 3 Karma points. Was there a reset for everyone's karma or maybe it's just a bug? I connected earlier today and noticed it but didn't have time to deal with it until now. Any ideas? Thanks. 
 Adminhelp to-Elysian_Prince: Not sure if you recognize me or not Elysian but I recognize your name. I'm a pretty old player I think by now lol.
Adminhelp from-Game AdminElysian_Prince: No, I remember your name.
Adminhelp from-Game AdminElysian_Prince: I'd send a message to Maintainers on the forums about that--I can't really do much about the whitelisting stuff.
 Adminhelp to-Elysian_Prince: Alright, I'll send something on the forums about it. Thanks man for what you can do lol.
Adminhelp from-Game AdminElysian_Prince: Hey, no worries.
 Adminhelp to-Elysian_Prince: You mind if I refer to you as the one who sent me to the forums in the post?
Adminhelp from-Game AdminElysian_Prince: Yeah, please.
 Adminhelp to-Elysian_Prince: Alright thanks.**

**Problem Description**:
Over the time that I haven't been playing, used to be really active but kinda trailed off of SS13 once I bought my new pc and could run different games, I seem to have lost access to my Vox race. My only Vox character seems to have turned human and the option to be Vox seems to be missing from the selection menu.

**What did you expect to happen**: 
To be able to use my Vox character

**What happened instead**:
He seems to be turned into a human, quite ugly might I add, and I can't change him back :c

**Why is this bad/What are the consequences:**
Other players may have encountered this same problem in the past, I can't be sure, but it sucks to have lost access to something that took a lot of patience and game time to earn. Especially once you have already had it.

**Steps to reproduce the problem**:
Be inactive over a period of many game updates? Not sure to be honest.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: All of my preferences seemed to have been reset as well whenever I logged in, including togglelobbymusic and all of my antag yes/no settings. Not sure if it's related but maybe? Here's a screenshot of what the poor bugger looks like now.
![image](https://cloud.githubusercontent.com/assets/20146466/16359806/5b7f6e3a-3b09-11e6-8d99-09c5e733daaa.png)

**Comment by YummyToast** [comment]
I don't know if it's relevant but just to get some amount of credibility on my part, I know there are some admins on the server that might recognize my name from when I played way back when. If you ask around it might ring a bell.

**Comment by KasparoVy** [comment]
I remember seeing that exact Vox name attached to a real Vox character in game a WHILE ago, but I don't have any photographic proof. It's strange that this happened, because that would indicate a database change that somehow resulted in you specifically losing your karma purchase of the Vox race

**Comment by Spacemanspark** [comment]
I vaguely remember a vox with that name.
