### ISSUE TITLE
Mining bots can't be repaired after chassis upgrade

### ISSUE THREAD

**Issue by Midaychi** [ParadiseSS13/Paradise#4784]
**Problem Description**:
What is the problem?
Upgrading mining bots with chassis upgrade renders them incapable of being welding tooled, and attempting to do so just returns null and uses fuel.

**What did you expect to happen**: 
Why do you think this is a bug?
Need to be able to repair them!

**What happened instead**:
How is what happened different from what you expected?
Can't repair health+ bots.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Rip in bots.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be mining bot
2. get welded just fine, though your health fluctuates between 48 and 63% for some reason.
3. Get upgraded
4. Welding tools no work no more
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Midaychi** [comment]
Can we move the code for mining bots out and make them actually a simple animal bot with the proper interfaces, instead of being a bizzare snowflake abomination of old monkey code copy pasta hidden away in equipment_locker.dm? That would probably fix a lot of problems, and you could put paid in them to boot.

**Comment by FlattestGuitar** [comment]
This should be fixed with [#4736](https://github.com/ParadiseSS13/Paradise/pull/4736), which is yet to get patched into the server. There wasn't that much that really needed a fix, but the code for the drone is a bit messy.
