### ISSUE TITLE
Chicks eject the ghost when they change to chickens

### ISSUE THREAD

**Issue by Midaychi** [ParadiseSS13/Paradise#4786]
**Problem Description**:
What is the problem?
If you are controlling a chick using the play as npc option, and the chick grows into a chicken, due to how the chick mob is deleted and the chicken mob is created, you get ejected back into being a ghost instead of being transferred into the new chicken.

**What did you expect to happen**: 
Why do you think this is a bug?
Muh chick all grown up.

**What happened instead**:
How is what happened different from what you expected?
Imposter poultry

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's not.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Be chick
2. Grow up.
3. ded

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Ar3nn** [comment]
Can you respawn as the chicken afterwards? If no, this is definitely something that needs fixing.

**Comment by Midaychi** [comment]
You can respawn AS a chicken. If there are multiple, it's random which.

**Comment by Vivalas** [comment]
This would be an interesting feature to simulate a change in personality as the chicks mature into chickens.
