### ISSUE TITLE
Look at this one simple trick to WIN wild west map!!!1 Mappers hate him!!

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#4788]
**Problem Description**:
There is a missing invisible wall in the wild west gateway map, this allows the cheesy nerds to skip the entire town area like the cheesemongering turdjugglers they are.

x = 129 
y = 17 
z = 8

**What did you expect to happen**: 
For the cheeseblocking magic to be actually cheeseblocking

**What happened instead**:
There's a hole for the pooper-snoopers to slip in from

**Why is this bad/What are the consequences:**
It skips the hard part of that place and allows the damn nerds to walz right into the wishgranter maze

**Steps to reproduce the problem**:
Jump to coords I gave, see that the magical cheesebuster wall is not there, cry.

**Comment by taukausanake** [comment]
Every issue should be made like this

**Comment by GeneralGoose** [comment]
👌👌👌👌👌👌👌👌

**Comment by KasparoVy** [comment]
:cactus: :clock12: ITS HHIIIIIGHH NNNOOOOOONNN
