### ISSUE TITLE
testing() is not outputting anything!

### ISSUE THREAD

**Issue by VampyrBytes** [ParadiseSS13/Paradise#4789]
**Problem Description**:
After I updated this morning, testing() is now not showing anything

**What did you expect to happen**: 
I expected it to output the testing information

**What happened instead**:
nothing!

**Why is this bad/What are the consequences:**
It makes trying to debug extremely hard

**Steps to reproduce the problem**:
update your master branch, put testing code in somewhere you know will trigger, run, trigger it, see no output

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I would guess this is related to #4744 
@tigercat2000

**Comment by tigercat2000** [comment]
@VampyrBytes yes, it tries to output to the host dialogue, if you're hosting via dream seeker directly, the output doesn't exist

host with dream daemon instead

**Comment by PJB3005** [comment]
The real issue here is running the game through dream seeker directly.
