### ISSUE TITLE
Toggle Darkness as ghost changes other ghosts

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#4793]
**Problem Description**:
Toggling darkness while being a ghost (in my case observing) changes the icons of all other ghosts into the generic white ghost or naked human icon.

**What did you expect to happen**: 
To be able to see normal ghosts and ghost brains.

**What happened instead**:
Old sprite ghosts and naked males everywhere.

**Why is this bad/What are the consequences:**
Not bad, but it's a weird thing I noticed and counts as a bug.

**Steps to reproduce the problem**:
Join as observe. Toggle Darkness under Ghost tab.

**Possibly related stuff**: 
Wizard gamemode.

**Comment by monster860** [comment]
This is probably because lighting is an invisibility value. In order to make the lighting overlays not display, the ghosts around also had to not display. This means that ghosts have to revert to using /image objects.

**Comment by tigercat2000** [comment]
yes that's how it works

**Comment by tigercat2000** [comment]
the only way to hide lighting overlays is setting see_invisible to a low value
the only way to hide ghosts is setting invisiblity to a high value
so it displays little ghost icons instead of hiding them 100%

**Comment by monster860** [comment]
I could probably put together a fix tomorrow, maybe.

**Comment by monster860** [comment]
There you go, a fix made by me in less than 30 seconds.
