### ISSUE TITLE
ghosts can interface with the traders shuttle console

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#4801]
be ghost, click on traders console, send or request docking at the station. I was observing, but I don't think it matters if you're dead or observing here

**Comment by taukausanake** [comment]
Haunted spaceship woooooooooo

**Comment by KasparoVy** [comment]
Lmao, that's hilarious.

**Comment by Spacemanspark** [comment]
Remember when they could do this with the white ship?
Only this is worse.

**Comment by taukausanake** [comment]
> Remember when they could do this with the white ship?

We need a haunted space ship now
