### ISSUE TITLE
Spriteless items! We have many for some reason.

### ISSUE THREAD

**Issue by Kevak** [ParadiseSS13/Paradise#4806]
**Problem Description**:
Multiple items lack sprites that they used to have. This is a problem

**What did you expect to happen**: 
Items to have sprites.

**What happened instead**:
How is what happened different from what you expected?
Certain items lack sprites. This is a problem.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Makes it a pain in the ass to pick them up without altclick. Makes searching things for seccies a pain in the ass. Especially as some of these are rather easy to acquire.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Spawn item or make item ingame.

Current known spriteless item list:
Bluespace Wormhole Projectors inside their lock boxes.
"Weapon" An object that can spawn within mining wizard rooms. Unsure of what the actual stats are or the item path. Would need to code delve potential wizroom spawns.
Bandolier that the barkeep spawns with.
.45 mags that SST's spawn with.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing really. Multiple rounds, rather repeatable.

**Comment by Kevak** [comment]
Aaand done.

**Comment by TheDZD** [comment]
Wormhole projector sprites are already fixed, the server hasn't patched

**Comment by taukausanake** [comment]
I thought I fixed the Bandolier?

**Comment by TheDZD** [comment]
Cross that off the list as well then, server hasn't patched in a bit over a week.

**Comment by taukausanake** [comment]
Not yet, need to test it first just to make sure

**Comment by taukausanake** [comment]
Yeah, still broke. I'll get it working again

**Comment by Alex6511** [comment]
Bandolier still broken in live

**Comment by TheDZD** [comment]
@Alex6511 Server hasn't patched, it was fixed in #480.

**Comment by Chakirski** [comment]
There's some voodoo going on with the .45 mags. There's sprites for it and the code goes along with all the other magazines, so there shouldn't be anything wrong with it, but yet there is.

**Comment by Chakirski** [comment]
Could you tell me what the description of the "weapon" is?

**Comment by Kevak** [comment]
The description of the 'weapon' was "This is a Weapon"

And ah.
