### ISSUE TITLE
Player Panel broke

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#481]
Not much explaining needed. I hope this gets fixed fast as the only means now to ban is icky manual banning.
![playpanel broke](https://cloud.githubusercontent.com/assets/10961410/6442325/914da12e-c0b4-11e4-8b56-b48b0e1a9e95.png)

**Comment by Spacemanspark** [comment]
QUICK EVERYONE START GRIEFING OVERWHELM THE ADMINS WHILE THEY CAN'T DO ANYTHING ABOUT IT EASILY.

**Comment by Earthdivine** [comment]
BRING IT ON! THAT DOESN'T STOP US!

**Comment by Spacemanspark** [comment]
NOT IF WE ALL USE BOMBS AND PLASMA FIRES.
Because ninety people using bombs and releasing plasma fires at the same time in coordination without admins noticing would totally happen.

**Comment by Earthdivine** [comment]
Upon further inspecting, it seems only that particular panels broken, I can open up player's individual panels by right clicking their mobs. So it's not as important to fix now.

Also forgot, @ZomgPonies @Fox-McCloud @Markolie

**Comment by Spacemanspark** [comment]
Darn.

**Comment by Earthdivine** [comment]
Throwing this in here so it doesn't get forgotten, Jump to Mob and Follow commands are also broken.
