### ISSUE TITLE
Mechanic Workshop Maintenance

### ISSUE THREAD

**Issue by Xantholne** [ParadiseSS13/Paradise#4811]
The second half of the Mechanic Workshop Maintenance has a major oversight in the latest Incinerator and Engineering Maintenance update as it allows anyone with Maintenance access to walk through. The problem with this as it literally lets anyone completely block access for pods in the mech workshop by just standing there in the middle even. Or going so far as a Clown or any Shittler would and build walls/move objects infront of it that permantely block the Mechanic Workshop without being removed.

Easiest way to fix this is to add Mechanic Workshop access requirement for those other two Maintenance doors to prevent people from blocking the pods completely from just leaving the Workshop.

**Comment by CrAzYPiLoT-SS13** [comment]
That really defeats the purpose of the maintenance, because it was
specifically put there so anyone could go through.

**Comment by Twinmold93** [comment]
I'm one of the people who was against adding that maint through podbay... Because it's just so... Wrong... There shouldn't be a maint access going through a podbay airlock.

**Comment by Norgad** [comment]
What @CrAzYPiLoT-SS13 said. The fact that you can walk through is **not** an oversight. Also, if someone _does_ block the pod exit, there is another airlock that the mechanic can walk through to go and unblock the path. This isn't an issue.

**Comment by taukausanake** [comment]
Yeah, letting maint pass through the Mechanic Pod Bay is not a good idea even if you can't get into the workshop through it. I mainly thought it looked unsightly and didn't even think about the possibility of blocking the way out. Just spam crates into it and laugh at the poor Mechanic
