### ISSUE TITLE
Plants too stealthy

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#4814]
**Problem Description**:
What is the problem?
Picking up a potten plant apprently doesn't remove the plant icon. Witnessed someone attacking people as a plant, got arrested and handcuffed as a plant, and buckled into a bed as a plant.

**What did you expect to happen**: 
Why do you think this is a bug?
Talked to Fethas and she freaked, I take that as a sign it's a bug.

Truthfully, I expected the plant to not work or be dropped, as it requires 2 hands to hold.

**What happened instead**:
How is what happened different from what you expected?
Never dropped the plant disguise, which is kinda jarring and can not be very fun if someones being super sneaky with it.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Its not really, just looks weird.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Pick up plant.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Was Traitor-Ling round, though I do not believe that had anything to do with it.

**Comment by KasparoVy** [comment]
Picking up a plant and dropping it means that, while on YOUR screen you'll still be a plant, other people will see you as a regular person so long as the plant is out of your hands. It just doesn't correctly clear the disguise on the client's screen for whatever reason

**Comment by Fox-McCloud** [comment]
@KasparoVy 

I've definitely seen officers that looked like plants tasing people or using batons, so.....

**Comment by KasparoVy** [comment]
That's bonkers! Haven't had a first-hand experience with that part of the bug myself
