### ISSUE TITLE
The Farting Dead

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#4821]
**Problem Description**:
Apparently the glorious goonchat broke something and you can emote even after dying if you stay in your body. This works even if you leave and re-enter your body

**What did you expect to happen**: 
For dead to not emote like some kind of fucked up immobile mimes from hell

**What happened instead**:
Dead can emote like beforementioned immobile mimes form hell. Crazy how nature do that!

**Why is this bad/What are the consequences:**
Corpses can basically speak

**Steps to reproduce the problem**:
Play spess man game
Die like you always do
Emote
Everyone sees your awesome decomposing RP

**Comment by TheDZD** [comment]
@VampyrBytes

**Comment by Spacemanspark** [comment]
That's not a result of goonchat.

**Comment by Rumiluntti** [comment]
So I have been informed, apparently it's the deathgasp fix that made this postmortem taunting possible

**Comment by Spacemanspark** [comment]
RIP
