### ISSUE TITLE
Crowbarring Station Mounted Radios repeatly dupes the electronics

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#4836]
**Problem Description**:
What is the problem?

If you crowbar a Station Mounted Radio multiple times during deconstruction it will produce as many electronics as you've been able crowbar on it.

**What did you expect to happen**: 
Why do you think this is a bug?

Only one circuit should come out of it instead of as many as you can crowbar in a short period of time.

**What happened instead**:
How is what happened different from what you expected?

Multiple circuits came out.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Duping is never good, not matter how minor.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

De-construct a station mounted radio and once at the crowbar to remove circuit stage, click as many times as possible and wait for the magic production of radios.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Also worth noting that the circuits are not included in the Engi-vend machines. So they only place to get a circuit from will be cargo autolathe I assume.

**Comment by FalseIncarnate** [comment]
For clarification, are you referring to rapidly clicking multiple times while the progress bar is up?

**Comment by Ar3nn** [comment]
that would seem to be so. Once the progress bar completes, it would be on to the next step, but it's probably not sanity checking to make sure this already happened on completion.

**Comment by Taaketa** [comment]
@FalseIncarnate Yup. During progress bar just click as much as possible.
