### ISSUE TITLE
pAI's that are on fire have no fire overlay

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#4848]
**Problem Description**:
pAI in mobile form can be on fire with no other indication than letting off light and having a HUD icon for being on fire that they can see

**What did you expect to happen**: 
pAI's to either not catch on fire or to have an overlay

**What happened instead**:
pAI catched on fire without having a fire overlay

**Why is this bad/What are the consequences:**

**Steps to reproduce the problem**:
fold out as a pAI, step into fire

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: it was a plasma fire at round end

**Comment by taukausanake** [comment]
I think a pAI having an on-fire icon would be troublesome because they have so many different forms they can be in. Not letting pAIs burn though would be inconsistent with other robotic beings. Can maint drones survive fire?

**Comment by Spacemanspark** [comment]
All synthetics can.
Minus IPCs, of course.

**Comment by taukausanake** [comment]
Borgs can survive fire? I thought their wiring would get damaged?

**Comment by Spacemanspark** [comment]
Nope, they do not take burn/ wiring damage in a fire.

**Comment by taukausanake** [comment]
So no fire damage for pAI is consistent with other robo beings. Glad that's settled

**Comment by AceMcLazer** [comment]
I was under the impression simple mobs do not catch fire? So things like ian, runtime, etc. They are not immune to fire and heat, but they cannot catch.

**Comment by taukausanake** [comment]
That makes a little more sense, but it would be nice to have an indication still if you are going to die besides the health count under Status
