### ISSUE TITLE
Human Health Updates are Non-Instant

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4849]
This was an issue with simple animals; the result of which, it made a lot of mobs far more durable than they otherwise should have been....

In any event, basically, when you take damage, your health *should* update **instantly**. That said, it does not, and is dependent on the next `life` process to catch up and update it.

This isn't terribly problematic in most cases, but it does lead to some scenarios (mostly with high damage weapons) whereby you don't lapse into crit instant (or die) the very moment you cross a damage threshold.

Would be fine if we were running something like gooncrit, as it's designed for that, but the current system is meant for instantaneous updates.

**Comment by ExitGame** [comment]
I've had situations where once I was someone in a spacesuit that got catapulted out of the station through an explosion or whatever it was, then crashed against a wall at super sanic speed, then nothing happened and 8 seconds later I immediately fell into limbs and pieces.

**Comment by Tastyfish** [comment]
Odd, since `updatehealth()` immediately updates the hud.
