### ISSUE TITLE
Eye Damage from welding space vines.

### ISSUE THREAD

**Issue by CodingCarl** [ParadiseSS13/Paradise#485]
I was on the end of a round and saw some rapid growing space vines. I started to weld them and I got damage to my eyes. Similar to welding a door or something metal with no eye protection. But the thing is I never received damage before when welding or really burning something that wasn't metal.

**Comment by Markolie** [comment]
This is intended. Whenever you don't take eye damage from welding something that is actually a bug rather than the other way around, due to the welding proc not being implemented properly.
