### ISSUE TITLE
Gun turrets on the derelict syndicate outpost do not launch their projectiles correctly

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#4850]
**Problem Description**:
The turrets on the syndicate outpost near the derelict appear to dump their live fired projectiles onto a single tile, completely negating their purpose. I didn't check other turrets.

http://i.imgur.com/E4X8Lik.png

**What did you expect to happen**: 
I expected the turrets to fire their bullets / grenades correctly.

**What happened instead**:
The projectiles launched, but were not correctly given a trajectory.

**Why is this bad/What are the consequences:**
This allows anyone who is spaceproof to trivially obtain an armoury's worth of equipment, in addition to several other very useful items.
You can also alt-click the tile the bullets are on to pick up live grenades / live bullets and stick them in a bag, which is obviously very bad (no, this isn't the Matrix).

**Steps to reproduce the problem**:
1. Go to the syndicate outpost and stand near a turret.

Nothing else weird was happening, and I'm fairly sure this has been consistent behaviour since the gun refactor update.

**Comment by Fox-McCloud** [comment]
Already fixed; haven't patched yet.

**Comment by Citinited** [comment]
@Fox-McCloud Thanks.
