### ISSUE TITLE
Issue with Antag-HUD

### ISSUE THREAD

**Issue by ErinPaige** [ParadiseSS13/Paradise#4853]
**Problem Description**: During a round after I had observed, I went into maintenance drone shortly before ghosting once again to continue observing. Having the negative self control I typically do, I toggled antag-hud and should have been forbidden from activities later on. However, the CE tried to repair a drone and I was allowed to take it. Now, while this bluescreens the drone that was reactivated; it then treats the player as though they never enabled antag-hud and allows them to potentially join ERT/Cult/Etc with all the knowledge of antag-hud.

**What did you expect to happen**: 
I believe it's a bug as the antag-hud is supposed to prevent you from joining once again after being activated, likely to prevent meta. However this can be used to bypass that prevention.

**Steps to reproduce the problem**:
Observe or die, respawn as drone, ghost, activate antag-hud, drone is repaired and you can accept or decline (however if typing and you hit the spacebar it will auto accept,) your ghost is now potentially unflagged from the antag-hud?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Game mode was cult, nothing particularly odd happening that round.

**Comment by LittleBigKid2000** [comment]
I think I was that CE. I swiped my card on a drone with no power twice.
