### ISSUE TITLE
Floorbot won't put down floor tiles.

### ISSUE THREAD

**Issue by CodingCarl** [ParadiseSS13/Paradise#486]
I turned on a floorbot to lay down tiles because a large amount of the station had no floor tiles, just plating. But the darn thing just stood there and did nothing. I played around with the settings and tried locking and unlocking it again, but to no avail. Even on patrol mode it just moved along doing nothing.

**Comment by Markolie** [comment]
I've made some improvements to floor bots, but keep in mind that 1) it needs to see the tile, not just be close to it and 2) if the floorbot can't reach a floor tile initially, it's not going to keep trying. If it can't reach the floor tile, the tile will be added to an ignore list, which will only be emptied once it's repaired a floor.

Also make sure you don't enable to many settings: only enable what you want the bot to actually do. Plus, this is BYOND, so there's only so much that can be done to make NPC's work.

**Comment by Markolie** [comment]
Oh, and keep in mind that floorbots have very limited access (engineer access). This means they can't move through science to repair tiles.
