### ISSUE TITLE
Limb Removal Damage Transfer Inconsistency

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#4863]
**Problem Description**:
Limbs don't consistently transfer damage to their parent limb correctly when removed. This means

**What did you expect to happen**: 
If I hit somebody in the leg with an energy axe, and the leg flies off, for them to still take 150 damage total.

**What happened instead**:
Sometimes they do take the full 150 damage, sometimes they only take 50 (damage cap of legs/leg stumps), and if you do it to an IPC/somebody with a mechanical leg, they will only take 25.

**Why is this bad/What are the consequences:**
People with mechanical limbs can _heal_ if a limb gets removed, people with regular limbs can do the same, albeit it's more difficult. Wand of Death cannot fucking kill IPCs, and will sometimes fail to kill people with mechanical limbs (brute damage and burn damage have the issue with mecha limbs, IPCs are immune to oxy and tox damage).

**Steps to reproduce the problem**:
Spawn an energy axe, and a few humans, and a few IPCs. Aim at one specific limb (such as a leg), and hit then rejuvenate each one until you have successfully cut off the targetted limb of every single one in one strike.

**Possibly related stuff**:
It's a relatively complex issue, due to interactions between organs, limb stumps, and the wound system.

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/organs/organ_external.dm#L231-L253
Might wanna look here

**Comment by Crazylemon64** [comment]
For IPCs, a hit to the torso will propogate to every other limb, acquiring a desired result. On limbs, it does a clean removal, not carrying the wounds further.

**Comment by KasparoVy** [comment]
Can confirm, survived many explosions just because my cyborg limbs came off.

**Comment by Fox-McCloud** [comment]
>For IPCs, a hit to the torso will propogate to every other limb, acquiring a desired result. On limbs, it does a clean removal, not carrying the wounds further.

For explosions, this is most definitely intentional, otherwise, it can result in an explosion that should only do 120 damage from doing 200+.

That said the problem specifically mentioned here is that say you damage someone's robotic arm and it has 50 brute and 30 fire damage.

They have a whopping 80 damage on them---you do 10 more brute and the arm pops off--they suddenly heal not only that 10 damage, but the combined 80 damage; they're now back at full health.

**Comment by taukausanake** [comment]
Wouldn't an round-start amputee be at full health without their arm? I wouldn't count robo limbs to count towards your full health, just limb health and being not-at-100% for full health. I mean if your arm blows off and you get treated but arm not replaced you should be completely fine I'd think

**Comment by Crazylemon64** [comment]
@taukausanake Health on a mob is tracked as a number minus damage, meaning that the total brute you have is the sum of all the brute on the limbs you have - if you lose a limb that has all your brute damage on it, your brute will drop to 0 (provided the limb removal itself doesn't damage the rest of your body)

**Comment by Fox-McCloud** [comment]
*mostly* been addressed when wound datums were removed.
