### ISSUE TITLE
Medical patches cannot be added to beakers

### ISSUE THREAD

**Issue by kadamczy** [ParadiseSS13/Paradise#4868]
**Problem Description**:
Patches cannot be dissolved into a beaker. This happens for all patches I've tried (synthflesh, silver sulfa and just a water patch). 

**What did you expect to happen**: 
When something is present in a beaker, the patch should add its units to the solution. e.g. a beaker has 5u water. I use a 20u synthflesh patch on the beaker. Now I have 20u synthflesh and 5u water in the beaker.

**What happened instead**:
The patch did not go in the beaker. it stayed in my hand.

**Why is this bad/What are the consequences:**
When you make the wrong dosage there is no way to correct it. Plus there would be no way to analyze the contents of a patch (which could have consequences if antag make poisonous patches and calls them something else)

**Steps to reproduce the problem**:
Put 5u water in beaker. Make 5u patch from beaker. Put 5u water in another beaker. try to put patch into beaker.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Vampire round. I don't think that's related though.

**Comment by Twinmold93** [comment]
In order to break down a patch, you need to put it into a grinder, like the one in chemistry, and grind it when a beaker is in it as well (which bey default is). This will allow you to change it's size, or even check what it has in it after you break it down.

**Comment by Fox-McCloud** [comment]
Not a bug. This is explicitly prevented.

Why would you be able to dissolve a piece of fabric anyway?

**Comment by kadamczy** [comment]
Okay I had a feeling that this was a change, I asked about it in the ooc but nobody seemed to be aware of the change.  As long as the grinder can be used I think that'll work fine.
