### ISSUE TITLE
You cannot escape justice. (you can cuff people with one or literally no arms)

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#4873]
**Problem Description**:
You can cuff people with one or literally no arms at all.

**What did you expect to happen**: 
GEE I DON'T KNOW ![img](http://i.imgur.com/PxLBHvT.png)
HE SURE HAS A LOT TO CUFF THERE DOESN'T HE

**What happened instead**:
OH MY GOD WHAT DO YOU THINK

**Why is this bad/What are the consequences:**
WELL GEE I SURE LIKE CUFFING MY AMPUTEE SPACEMENS. IT MAKES NO SENSE WHAT

**Steps to reproduce the problem**:
CHOP LIMB(S) PUT CUFFS ON. HAND/ARM MISSING DON'T MAKE A DIFFERNCE

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: WHO MADE THIS TEMPLATE AGH

**Comment by Ar3nn** [comment]
The template was made so that you could give us as much information as possible without making a long-ass post. It allows you to organize the information in a way that can be easily read and appreciated. All caps does not help with clarity, either. As for the issue, its a gameplay vs realism thing. I'm gonna go out on a limb here and say Fox/DZD comes by and slaps "Not a Bug" on here.

**Comment by tigercat2000** [comment]
uh no
this is clearly a bug

**Comment by Ar3nn** [comment]
But seriously, if this is a bug and they fix it, you bet your ass someone's gonna be selecting cybernetic arms just to hack them off if they're traitor.

**Comment by Spacemanspark** [comment]
Well then you stunlock them.

**Comment by theColdflame** [comment]
cuffing someone with one arm should be a thing

cuffing someone who's missing both is dumb though

**Comment by DaveTheHeadcrab** [comment]
Why the *tits* would you chop both your arms off as traitor to get away from sec?
What, precisely, do you plan to do once you've escaped? Shout harsh words at them?

**Comment by FreeStylaLT** [comment]
"OI OFFICER, HANDS OFF! I'M A FREE MAN!"

"YOU'LL NEED A HANDS-FREE APPROACH WITH ME SHITCURITAN!"

"I HAVE BEEN DISARMED!"

"I'M NEITHER A RIGHTIST OR A LEFTIST, I'M SOMEWHERE IN THE MIDDLE."

**Comment by taukausanake** [comment]
> Or activate your secret traitor chest-mounted minigun?

Why is this not a thing...

Does your image up there still have their hands? Maybe that's related? Or they could be Rayman and that's how they got cuffed

**Comment by FreeStylaLT** [comment]
They're missing both, but when you chop them off, the overlay or whatever for bloody hands appears on the sprite.

**Comment by Ar3nn** [comment]
Not both, just one. You can use your PDA hands-free, so you'll still have a hand to take stuff out of the uplink.

**Comment by Belario** [comment]
Mutilating yourself to be uncuffable should be a legitimate tactic.
Literally unplayable pls fix

**Comment by Lady-Luck** [comment]
Looking forward to playing an armless clown
