### ISSUE TITLE
Telecommunications

### ISSUE THREAD

**Issue by SparklingD** [ParadiseSS13/Paradise#488]
Something is up with telecommunications, like the server is disallowing some things to happen. Is it possible that the server is overwriting telecomms after it's gone through the change at telecomms, as it acts like it. Somethings work for silicon, so I'm guessing the server isn't checking if the sender is silicon by checking something if they are human or an actual player? I don't know. But something is definatly happening.

**Comment by Markolie** [comment]
This isn't a useful bug report. What is wrong? What is causing it? "Something is wrong with telecomms" really isn't specific enough.
