### ISSUE TITLE
Potted plant + cardboard box = TRAPPED FOREVER

### ISSUE THREAD

**Issue by Belario** [ParadiseSS13/Paradise#4880]
**Problem Description**:

Holding a potted plant and being shut inside a large cardboard box will render you stuck in there, you can move around but can't let yourself out/open airlocks/interact with anything.
They can still talk/scream/beg for mercy, but they need someone else to actually open the box for them.

**What did you expect to happen**: 

It's a bit too easy to condemn people to Tartarus, I haven't tested it but I suspect that holding items in both hands will have the same effect as you can't drop things when you're inside the box,

**What happened instead**:

You'd think a cardboard box wouldn't be that secure.

**Why is this bad/What are the consequences:**

I can forsee it being abusable if it becomes common knowledge, just imagine, stripping people naked, tabling them, stuffing donuts in their hands and sealing them inside cardboard carceri.

**Steps to reproduce the problem**:

Requires two people a large cardboard box and a potted plant, have one guy hold the plant, have the other guy shut guy one inside the box.

**Comment by TheDZD** [comment]
Did you try resisting out of the box?

**Comment by Belario** [comment]
Can't say if that'd work, I wasn't the one stuck in there thankfully.

**Comment by TullyBurnalot** [comment]
Resisting out of a box while holding 2 items does not work.

So yes, you can be permanently locked into a lock-less cardboard box if you hold two hats and someone closes the lid on you.

**Comment by monster860** [comment]
Did you try resting?
