### ISSUE TITLE
Crash on opening medical records on someone or similar records

### ISSUE THREAD

**Issue by WhiteHusky** [ParadiseSS13/Paradise#4886]
**Problem Description**:
Crash on opening medical records on someone or similar records. Stops doing so after the first record open.

**What did you expect to happen**: 
Open medical records and not crash.

**What happened instead**:
Open medical records and crash out of the game. Reconnect and look back to console with the record doesn't crash nor does opening up another.

**Why is this bad/What are the consequences:**
Knocks the character out until the player reconnects.

**Steps to reproduce the problem**:
Simply visit any console that will open medical records and attempt to open one.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing out of place and has happened twice in two different game modes, even if completely calm.

**Comment by WhiteHusky** [comment]
Seems to crash when attempting to render the image.

**Comment by CrAzYPiLoT-SS13** [comment]
Known issue. I think there is another report open on the Git
