### ISSUE TITLE
Low blood animals constantly teeter on life and death and make tons of noise

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#4889]
When an animal like say, a farwa or a monkey, is low on blood, they will spam the chat something fierce with tons of noise. You would think that would be over when you draw enough blood from them that they die, but for some reason they keep coming back to life and making even more noise.

Mainly a major annoyance, but the last part where they keep coming back from death sounds like it could be a bug too.

**Comment by Fox-McCloud** [comment]
There's a number of death oddities with these guys.

I suspect someone is using a health value of -100 instead of `species.max_health` somewhere.

**Comment by DaveTheHeadcrab** [comment]
Also occurs with humans, though humans eventually die of oxygen loss.

**Comment by FreeStylaLT** [comment]
my chat suffers

**Comment by Belario** [comment]
Dead people do this too, more than a little inconvenient when you're trying to deal with drained bodies.
