### ISSUE TITLE
Sec cameras hang every 2 seconds

### ISSUE THREAD

**Issue by Vivalas** [ParadiseSS13/Paradise#4890]
**Problem Description**:
Every 2 seconds while using cameras, the entire interface freezes up, map and rest of the UI, everything

**What did you expect to happen**: 
It not to clip.

**What happened instead**:
It's annoying as all hell.
**Why is this bad/What are the consequences:**
It's hard to type things or follow any sequence of events as the entire interface freezes up every 2 seconds.
**Steps to reproduce the problem**:
1. Open security cameras.
2. ???
3. Cry.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A Probably related to processing ticks

**Comment by Spacemanspark** [comment]
I'm not the only one?
Also, this is only with the console. Using a laptop doesn't have these issues.

**Comment by tigercat2000** [comment]
@TheDZD byond issue, map freezing can't happen from our code

**Comment by TheDZD** [comment]
@tigercat2000 Then why would it only happen with the console, and not laptops?

**Comment by Vivalas** [comment]
It's not map freezing, it's the entire damn UI freezing.

**Comment by Spacemanspark** [comment]
It's something to do with the UI, ya.

**Comment by Spacemanspark** [comment]
As a side note, this has been happening for me ever since Markolie redid the camera console.

**Comment by Lady-Luck** [comment]
Happens to me too. Laptops don't have the same issue for whatever reason??

**Comment by Fox-McCloud** [comment]
This wasn't happening to me until super recently. I could use sec cameras 100% fine, but now they freeze constantly.

**Comment by Lady-Luck** [comment]
I discovered this lag only happens when the SS13 network is selected in the UI. If you deselect it while you're looking through a camera, the lag goes away.

**Comment by HereticChurch** [comment]
This is still affecting me, but it outright causes my BYOND to crash now, the issue seems to have gotten worse. (Though that could be my computer being potato)

**Comment by Lady-Luck** [comment]
The laptop's security camera interface (which is much more simplistic and not alphabetized) does not cause this issue. As a stopgap the interface from that could be transplanted onto the security camera interface on the consoles.

**Comment by Markolie** [comment]
https://github.com/ParadiseSS13/Paradise/issues/4890 should fix this issue.
