### ISSUE TITLE
Auto Rifles fire "1 round bursts"

### ISSUE THREAD

**Issue by Vivalas** [ParadiseSS13/Paradise#4891]
**Problem Description**:
Autorifles fire 1 round bursts.

**What did you expect to happen**: 
Auto rifles to be able to switch from semi-auto to bursts.

**What happened instead**:
The autorifle switched to "1-round bursts".

**Why is this bad/What are the consequences:**
Because it pretty much makes autorifles a pistol with extra ammo.

**Steps to reproduce the problem**:
1. Get ready to unload on a motherfucker.
2.Change firemode. Get ready to suffer bitch.
3. .... What the hell is a "1-round burst"?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by Vivalas** [comment]
I would fix this myself but I am not entirely sure if they're supposed to fire actual bursts. It's still pretty silly though.

**Comment by TheDZD** [comment]
Intentional, it's not supposed to have burst fire.

**Comment by FlattestGuitar** [comment]
You can switch the rifle into 1-round burst mode or semi-automatic mode. They're both functionally the same, this should be cleaned out.

**Comment by Spacemanspark** [comment]
I haven't looked at the code, but 1 burst mode feels slower than semi-auto when I fire it.

**Comment by Plotron** [comment]
Should probably be removed altogether.

Let's just say that this gun is a neutered version of something more serious. Just like AR-15 for mall cops.

**Comment by TheDZD** [comment]
@Plotron It was already fixed in #4892.
