### ISSUE TITLE
AI can eject containers from IV drips.

### ISSUE THREAD

**Issue by razekpraxis** [ParadiseSS13/Paradise#4898]
**Problem Description**:
An AI can eject beakers/buckets from IV drips. Spooky.

**What did you expect to happen**: 
Literally nothing.

**What happened instead**:
Title

**Why is this bad/What are the consequences:**
AI dont have hands. Thus cannot eject beakers.

**Steps to reproduce the problem**:
Be AI, click on an IV drip.

**Comment by Plotron** [comment]
Spooky action at a distance.
