### ISSUE TITLE
Green Glasses & Monocle from Autodrobe don't really correct your eyesight

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#4913]
**Problem Description**:
Autodrobe Green Glasses aren't a viable alternative to normal eyeglasses, because they do not correct your shitty eyesight. Same can be said about the fancy monocle.

**What did you expect to happen**: 
Green Glasses & Monocle to correct for shitty eyesight.

**What happened instead**:
Green Glasses & Monocle did not correct for shitty eyesight.

**Why is this bad/What are the consequences:**
Inconsistency. These glasses have lenses, it's not just a fancy neon green frame. They should be resprited Prescription Glasses that could be worn by characters with crappy eyesight. As a consequence, my bad_sight enabled characters cannot look hipster enough.
I want more variety.

**Steps to reproduce the problem**:
1. Have a character with shitty eyesight.
2. Get Green Glasses/Monocle from an Autodrobe.
3. Put 'em on.
4. See jack shit.
----
I quickly looked into the code and it seems like it's just a matter of adding prescription = 1.

**Comment by FalseIncarnate** [comment]
I think that's intentional, they are costume accessories, not actual prescription glasses.

Though having a prescription monocle would be fancy, it really only matters if you have only 1 bad eye.

**Comment by Lady-Luck** [comment]
We have a loadout system now. Add prescription glasses/monocles to it

**Comment by TullyBurnalot** [comment]
@Lady-Luck Characters with bad eyesight automatically start with prescription glasses.

**Comment by Plotron** [comment]
I just checked. Green Glasses cannot be upgraded with prescription lenses, while they logically should, just like regular sunglasses.
