### ISSUE TITLE
'Escape on the shuttle alive and free' does not consider straightjackets

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#4930]
Just had this happen in a round. Straightjacketed criminal causing self harm was considered alive and free at the end of the round because he was being treated in medical.

Even had a prisoner ID on.

**Comment by TheDZD** [comment]
Not in the shuttle brig = free

**Comment by Lady-Luck** [comment]
Weird. So if a prisoner manages to get themselves critically injured and has to be transported to medical, we count that as free?

Seems like an oversight.. it should check for cuffs.

**Comment by tigercat2000** [comment]
it's not an oversight, it's intentional for "put them in the damn brig"
