### ISSUE TITLE
Remote View is completely broken

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#4947]
Upon trying to use Remote View on a specific preson, I instead get someone else completely random. Sometimes a maintenance drone. Sometimes a monkey. Anyone but the one it's supposed to work on.

**Comment by Earthdivine** [comment]
#4192

It was changed to only work on those who also have Remote View but that doesn't seem to be working?

**Comment by Lady-Luck** [comment]
Correct.
