### ISSUE TITLE
Brain Surgery bug

### ISSUE THREAD

**Issue by JarlBrolaf** [ParadiseSS13/Paradise#495]
Trying to remove a brain with the severed head in your hand results in a completed surgery but the brain fails to drop onto the ground. The brain is then stuck in a sort of limbo where it's still "attached" to the body, but you can't operate on the head anymore and any attempts to clone result in no intelligence found.

**Comment by Earthdivine** [comment]
It actually doesn't get out into limbo, the game tries to spawn it into your hand, but you can only have 1 item per hand, resulting in your character holding three objects at once.

Still would like this fixed, it seems to be happening a lot more often now.
