### ISSUE TITLE
Canister UI gets glitched when you try to change the pressure values

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#4956]
**Problem Description**:
http://i.imgur.com/LjjF0DW.gifv

**What did you expect to happen**: 
Not that.

**What happened instead**:
That.

**Why is this bad/What are the consequences:**
Well, you know, it's a bit wonky. Still usable, but wonky.

**Steps to reproduce the problem**:
I put in the tank, change the value, shit gets whack. If you close the menu and re-click, it appears fine until you change the values again. Putting in/not putting in the tank doesn't matter, changing the values at all screws up the UI.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing in particular.

**Comment by Tastyfish** [comment]
What OS and internet explorer version do you have? A _lot_ of things in that gif look wrong.

**Comment by FreeStylaLT** [comment]
Windows 8.1, IE11

**Comment by Tastyfish** [comment]
strange

**Comment by Shadow-Quill** [comment]
@Fox-McCloud Couldn't reproduce.

**Comment by FreeStylaLT** [comment]
This is ancient and no longer occurs.
