### ISSUE TITLE
Librarian's check in/out computer spazzed out.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#4967]
**Problem Description**:
Fethas was messing with the check in/out computer (the one behind the librarian's desk next to the photocopier) and took off when I showed up.  I went to click on the computer (just one click!) and got [this](https://i.gyazo.com/334ff96b1d9149efbfbb4e09ff9d7081.png).  Other than that the computer seemed to work normally.

**What did you expect to happen**: 
I expected the computer to function normally but without a wall of red error text.

**What happened instead**:
SO MANY ERRORS AAAAAA

**Why is this bad/What are the consequences:**
It didn't seem to affect usability at all and I honestly have no idea what Fethas was doing in-character as the Mime.  It's not a major issue but I figured I should report it anyways.

**Steps to reproduce the problem**:
All I did was, as the librarian, click on the check in/out computer behind the main desk in the library.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Roundtype was AutoTraitor.  I suppose the computer could've been emagged, but if it was it wasn't me who did it.

**Comment by TheDZD** [comment]
@Aurorablade What exactly did you do with the computer?
