### ISSUE TITLE
Vox tail changing color randomly

### ISSUE THREAD

**Issue by SpaceTimeNow** [ParadiseSS13/Paradise#4969]
**Problem Description**:
Vox tail changing color randomly

**What did you expect to happen**: 
It not to change randomly

**What happened instead**:
It changed randomly

**Why is this bad/What are the consequences:**
I hate it!

**Steps to reproduce the problem**:
Spawn as vox and wait, for me it happened when i was at a locker equiping gear, but no idea if that's really the cause.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I still hate that i can change the haircolor of the vox and it didn't default to the normal color. I wasn't able to propperly reproduce the old color. Totally different issue, but i also hate it!

**Comment by Fox-McCloud** [comment]
duplicate.

**Comment by SpaceTimeNow** [comment]
33 seconds, do you live here? :)
