### ISSUE TITLE
Permanent Disguises 2.0---Houseplant Edition

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4972]
It's still possible to get permanently stuck as a plant.

Dunno how it happens, but it's still happening.

**Comment by TheDZD** [comment]
@Krausus

**Comment by Taaketa** [comment]
I was looking for an existing bug posting but I couldn't find it.

I was able to disguise myself as a plant permanently only to certain people. For example, anyone who was off screen at the time I left the disguise saw me as my normal character sprite.

I used the UI drop icon to leave the plant on the ground and 3 people around me, still saw me as a plant. But anyone who came into the area after I dropped the disguise just saw me as a normal sprite. During this time, I always saw myself as a plant. I did not try reloading the byond client to see if that changed anything. But I thought this would be worth posting here.

At the time I turned into the plant permanently on my screen I was located in Security, by the consoles in Security reception just in the space between the windoor and computer.
