### ISSUE TITLE
AI repair console - cannot be repair if damaged whilst repairing AI

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#4982]
**Problem Description**:
What is the problem?

If the AI repair console in the RD's office is damaged from EMPs, Laser shots or anything else. It cannot be repaired as you receive a message saying the AI repair must be completed first (something to that effect).

**What did you expect to happen**: 
Why do you think this is a bug?

AIs get stuck in purgatory and cannot be removed from the console, nor the console repaired to fix the AI.

**What happened instead**:
How is what happened different from what you expected?

AIs being repaired and the repair fails should still be able to be uploaded to a card or the consle repaired with the AI repair being continued afterwards.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

An AI player is effectively removed from the round if the console is damaged or EMPed since it cannot be repaired if the AI was being repaired at the time the console was damaged.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Upload AI into repair console. Set off EMP near console. Try to repair console and receive warning message saying the AI isn't repaired yet.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
Should probably perma-kill the AI if you emp it while it's being restored

**Comment by Ar3nn** [comment]
Yeah, but in a not-ambiguous way, I'd think. Delete the intellicard and ghost it, this would allow the console to be restored but still keep the AI out of the round, but in a decisive way.
