### ISSUE TITLE
.getserverlog attack logs are empty

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#499]
When you pull up the attack logs via .getserverlog this is all that's within the file: http://pastebin.com/KiQSTcKp

It seems to be recording the times the server boots up but not actual attacks. How am I supposed to know the degree of someone's shittery now? Biased screenshots from butthurt nerds? UNACCEPTABLE.

**Comment by TheDZD** [comment]
Said logs are in the regular server log, and this seems to be intentional behavior, although it is a bit weird.
