### ISSUE TITLE
Random Metal Rod Turfs Northeast of the Firing Range

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#4994]
**Problem Description**:
There are metal rod turfs just floating in space northeast of the firing range.

**What did you expect to happen**: 
For there not to be weird rod turfs floating around.

**What happened instead**:
There are.

**Why is this bad/What are the consequences:**
It looks out of place.

**Steps to reproduce the problem**:
![image](https://cloud.githubusercontent.com/assets/8212178/16749441/38f9ef34-4798-11e6-8da8-80190a608d27.png)

**Comment by Tastyfish** [comment]
space debris

**Comment by Plotron** [comment]
That shit is so old, man!

Surprising that it was reported only now.

**Comment by TheDZD** [comment]
@Plotron I noticed this ages ago too, and forgot to report it.

**Comment by Chakirski** [comment]
There's also a random tile and rods far north of the HoS's office.

**Comment by Ar3nn** [comment]
I thought they were strategically placed so people had some odds of catching something if they drifted JUST THAT CLOSE to the station and couldn't hit it. If they aren't supposed to be there, it'd be rather trivial to remove I'd guess.
