### ISSUE TITLE
The "?" Button that Appeared Next to People's Names in Ahelps is Gone

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#4995]
**Problem Description**:
There used to be a little question mark button that would appear next to any names mentioned in ahelps, that caused text to pop up that gave links to do things like follow that mentioned mob, PM them, and such. Ever since #1776, it has not been appearing there.

**What did you expect to happen**: 
For that button to appear.

**What happened instead**:
It didn't.

**Why is this bad/What are the consequences:**
Mentioned names are still highlighted in a different color (I think it was black?) than the rest of the ahelp, so I initially assumed the question mark button was still supposed to be there. That said, looking at that PR's diffs (adminhelp.dm, line 90 specifically), it looks like the removal was intentional, but it was never documented anywhere, and it was a really useful feature.

**Steps to reproduce the problem**:
Send an ahelp, include a mob's name in it. The mob's name will be in black, but the button won't be there.

Not really a good tag to use for this, although it was undocumented removal of a very useful feature,

**Comment by tigercat2000** [comment]
we should use goon tooltips to restore this
make highlighting the name with the cursor pop up a tooltip
.... i don't even know if it's possible to do that kek but it'd be fun

**Comment by tigercat2000** [comment]
update: that's probably impossible
BUT WE COULD STILL USE GOONCHAT 
... i think.

**Comment by Tastyfish** [comment]
being that the tooltips are game objects, probably not

**Comment by variableundefined** [comment]
I believe its fixed

**Comment by tigercat2000** [comment]
Nope, still an issue.

**Comment by Shadow-Quill** [comment]
Could not reproduce @Fox-McCloud
