### ISSUE TITLE
Brownstar Reagent Description Type

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#4999]
**Problem Description**:
`description = "Its not what it sounds like..."`
The "Its" should be an "It's" or "It is"

**What did you expect to happen**: 
For my the grammar police to not have a job.

**What happened instead**:
It still does.

**Why is this bad/What are the consequences:**
It's grammatically incorrect English.

**Comment by Tastyfish** [comment]
nice ID padding issue report :stuck_out_tongue:

**Comment by TheDZD** [comment]
Shhhhh
