### ISSUE TITLE
Metastation No Tape?!?!?!?!!?!?!?1/1/1/

### ISSUE THREAD

**Issue by Chakirski** [ParadiseSS13/Paradise#5018]
There's no tape in the tool storage....
WHY?!

**Comment by TheDZD** [comment]
@tigercat2000

**Comment by LittleBigKid2000** [comment]
The artvend has tape. There's an artvend in primary tool storage.

**Comment by Chakirski** [comment]
:+1: :x: :100:

Now playable.
