### ISSUE TITLE
NODROP Owlman Costume Available in Metastation

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#5019]
**Problem Description**:
See: Title

**What did you expect to happen**: 
For either there not to be a NODROP item in maint that doesn't have any clue it would be NODROP.

**What happened instead**:
There is.

**Why is this bad/What are the consequences:**
If a player picks this up without knowing it is NODROP, they're stuck with it.

**Steps to reproduce the problem**:
Not entirely certain where all its locations are, or where if it can differ, but one was found in maint to the right of toxins mixing.

@tigercat2000

**Comment by Fox-McCloud** [comment]
This is because Ponies made all the costumes into NODROP for his superhero things without making a new version that was a damn subtype. *sigh*

**Comment by Tastyfish** [comment]
They really should be subtypes..particularly owl costumes are a fairly "traditional" ss13 costume.
