### ISSUE TITLE
Metastation - Chaplain starts with a Soulshard

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#5022]
@tigercat2000 

![ss 2016-07-13 at 02 52 48](https://cloud.githubusercontent.com/assets/10961410/16817717/bc94ebd8-4909-11e6-8feb-6085759de3d4.png)

Obviously this is kinda bad to have, as the chaplain will get attacked for being a cultist. Maybe. Might be good for meta though.

**Comment by tigercat2000** [comment]
intentional
i think it's fake on -tg- though

**Comment by Earthdivine** [comment]
It has /obj/item/device/soulstone here, so we got a real one. If you guys wanna make it fake that would be cool.

**Comment by Fox-McCloud** [comment]
Not a bug, this is intentional.
