### ISSUE TITLE
Metastation - Toxin doors aren't connected to controller.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#5023]
@tigercat2000 
![ss 2016-07-13 at 02 57 59](https://cloud.githubusercontent.com/assets/10961410/16817821/46480b76-490a-11e6-9a9d-44ce0c1f4b5c.png)

As it says on the title, these doors don't connect to the controller.

**Comment by FreeStylaLT** [comment]
Was fixed in some previous patch. http://i.imgur.com/WIpkIft.gifv
