### ISSUE TITLE
Metastation - The escape pods all have no lights

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#5026]
**Problem Description**:
There are no lights in the MetaStation escape pods.

**What did you expect to happen**: 
There would be lights.

**What happened instead**:
There are not.

**Why is this bad/What are the consequences:**
I can't see in the dark.

**Steps to reproduce the problem**:
Run MetaStation. Observe that the escape shuttles lack lights.

**Comment by Tastyfish** [comment]
Do all of the pod doors work at least? I remember for a bit boxstation had escape pod stuff with the wrong ID's.

**Comment by TheDZD** [comment]
I remember seeing an ahelp near the end of the round about pod doors not bolting, although I wasn't able to go and confirm it at the time.

**Comment by tigercat2000** [comment]
as far as i am aware the pod doors intentionally do not bolt or unbolt and are always unbolted

**Comment by Tastyfish** [comment]
They did at one point, put I think that was before tg shuttles.

**Comment by Plotron** [comment]
https://youtu.be/moX3z2RJAV8
