### ISSUE TITLE
[VERY MINOR]Xenoarch RNG = troll

### ISSUE THREAD

**Issue by PJB3005** [ParadiseSS13/Paradise#503]
artifact depths can conflict with eachother, so if artifact 1 is at depth 10 with clearance 4, artifact 2 can be at depth 16 with clearance 8, for example, you can still mine artifact 2 if you dig with the (in the example's case) 6 cm pick

it's very minor but still something, and might confuse some people

**Comment by Taaketa** [comment]
Maybe close this since #1476 has removed xenoarch in the meantime?
