### ISSUE TITLE
Sec Camera Station Bug

### ISSUE THREAD

**Issue by RobBrown4PM** [ParadiseSS13/Paradise#5032]
**Problem Description**:
If logged in to a Security camera station and said station looses power you can continue to cycle through the cameras until you cancel the camera view. 

**What did you expect to happen**: 
Because you shouldn't be able to view a camera from a console if it doesn't have power. 

**What happened instead**:
The opposite of what should have happened. 

**Why is this bad/What are the consequences:**
It's a minor bug. 

**Steps to reproduce the problem**:
Fix the issue. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Twinmold93** [comment]
Effectively, the simplest fixes would be A) just have it do a check every time you hit a new button, or B) if the console suddenly loses power, finds all nearby players (3x3 around console) and cancel-camera-view. A is much easier than B.
