### ISSUE TITLE
ChemMaster pill bugs

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5035]
@monster860 
The pill style interface for the ChemMaster is completely fucked. The lag I mentioned is still present so that's nothing new, when you first select 'Style' there will be a long load for the first time it has to load the pills per machine.

However the new bugs are related to selecting a new pill. When you select a new pill, it registers the selection, however the window doesn't close, and it doesn't show the new pill selection on the ChemMaster interface until the window refreshes from another action, making it extremely awkward to use.

**Comment by monster860** [comment]
I'm working on it.
