### ISSUE TITLE
pAI device racist to Kitten.pAI

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#5036]
**Problem Description**:
Crew members get notification that there is a pAI available, but the pAI device shows nothing.

**What did you expect to happen**: 
You should be able to download Kitten.AI

**What happened instead**:
pAI device refuses to have Kitten.pAI (blank screen, shows nothing)

**Why is this bad/What are the consequences:**
Everyone needs Kitten.pAI, even you Admins.

**Steps to reproduce the problem**:
Saved pAI file, Loaded pAI file, created a new pAI file and submitted with no success

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
It's been proven that crew depression gets serve without Kitten.pAI in there life.

**Comment by Plotron** [comment]
It's confusing when it happens, yes.

**Comment by Spacemanspark** [comment]
Ya, sometimes people can't download Spark.
Then they die.

**Comment by Trubuss** [comment]
Kitten most important though. :P

**Comment by Spacemanspark** [comment]
That's not how you spell "Spark"

**Comment by Trubuss** [comment]
No, no, the word was Kitten, as in how many people love Kitten.pAI. >:3

**Comment by Spacemanspark** [comment]
That's not how you spell "Spark 5.5m is amazing"

**Comment by KasparoVy** [comment]
edgy memes

**Comment by Trubuss** [comment]
Kitten.pAI owns Spark.

**Comment by Davdichan** [comment]
After reading these comments I'm not sure how the original issue is even a problem.

**Comment by Trubuss** [comment]
Then you didn't read it, Davdichan.

**Comment by Spacemanspark** [comment]
:^)

**Comment by counterfeitguise** [comment]
Ignoring the comments, it's an actual problem. pAI grabbing is a fickle mistress.

**Comment by TheDZD** [comment]
Likely fixed by #5496, since it was saving that was broken.

**Comment by TheDZD** [comment]
Nevermind, apparently not.

**Comment by alexpkeaton** [comment]
This is an unexpectedly hilarious issue thread.

**Comment by Spacemanspark** [comment]
Spark is still the best pAI

**Comment by Trubuss** [comment]
Clearly, it is not Spark, but Kitten being best pAI.

**Comment by Davdichan** [comment]
The best pAI is the one bound to the recycler.

**Comment by Spacemanspark** [comment]
I'll bind you to the recycler.

**Comment by Davdichan** [comment]
Kinky

**Comment by Crazylemon64** [comment]
Is this actually a thing

The steps provided are insufficient to reproduce it

**Comment by Spacemanspark** [comment]
I think it's been fixed honestly.

**Comment by Crazylemon64** [comment]
Yell if this comes up again, preferably with more details/a ping to join the server, so I can inspect this closer than what this issue tells me.
