### ISSUE TITLE
health_threshold_crit and health_threshold_crit_dead do not inherit values from maxHealth or total_health

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5038]
So I was looking in the code to try and figure out why monkeys don't die at -75 and I think I've found the answer.

I could not find any code whatsoever that calculates appropriate health_threshold_crit and health_threshold_crit_dead values from the species' maxHealth value or total_health value, essentially making it so the only source it's inherited from is game_options.txt

**Comment by tigercat2000** [comment]
are monkeys even supposed to die at -75
aren't they supposed to just never heal past +75

**Comment by Lady-Luck** [comment]
You may be right. The problem is that there seems to be something based off the inverse of a species maximum health because before the latest blood rework they were teetering between life and death from blood loss, and now they just seem to stop dying from bloodloss at -75.

**Comment by Lady-Luck** [comment]
Closing this for now...
