### ISSUE TITLE
Server freezes when opening telecommunications server monitor

### ISSUE THREAD

**Issue by Fruerlund** [ParadiseSS13/Paradise#5039]
**Problem Description**:
What is the problem?

Server freezes for about 30 seconds when opening said computer.

**What did you expect to happen**: 
Open console, see all chat records.

Why do you think this is a bug?
Because it' stops the server.

**What happened instead**:
Freeze, it's th. it froze!

**Steps to reproduce the problem**:
Click on computer.

I'm guessing it's because it loads 1 hour and 15 minutes of radio chat.

**Comment by monster860** [comment]
The problem is that it performs a bunch of calculations (istype) on the spot when it *could* have done those calculations upon logging the record.

**Comment by Taaketa** [comment]
Probably relates to #2953

**Comment by tigercat2000** [comment]
duplicate of #1429
