### ISSUE TITLE
Mutiny Gamemode

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#504]
-The Directive paper doesn't properly show up at the Head Loyalist's fax machine.
-The Authentification Disk Pinpointer is not order-able by Cargo due to the recent overhaul that neglected to include it.
-Certain mutiny objectives can be made impossible very easily; for example, "Terminate all female employees" can be impossible if a single female employee spaces themselves with their suit sensors off before the directive arrives.
-There does not appear to be a way to transfer funds from in-game bank accounts to other accounts using the account computer, making other Mutiny objectives impossible as well.
-Tested this morning, was captain, all of these things were true.

**Comment by Markolie** [comment]
The mutiny game mode will most likely be taken out of rotation completely very soon.

**Comment by Fox-McCloud** [comment]
There's a plethora of issues that can't really be resolved here without TONS of snowflake checks; you can destroy your authentication key as the mutineer, which all but guarantees the mutineer wins EVERY single round.

Tons of stuff like this exist with the game mode---as it was meant for a very very heavy roleplay environment.
