### ISSUE TITLE
Blob/Plant-B-Gone

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#505]
Plant-B-Gone is able to damage blob mobs and, supposedly, blob tiles. However, attempting to spray the blob tiles with Plant-B-Gone instead sprays the tile you stand in, as though you were spraying a wall, not a floor.
For obvious reasons, this is dangerous to a Diona botanist fighting the blob.

**Comment by TheDZD** [comment]
Atrazine (the chem in Plant-B-Gone) bottles doesn't do this anymore.
