### ISSUE TITLE
Security Record Printouts are bugged

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#5051]
Someone was deleting Security Records so I started making printouts of essential records, however when I went back and looked at them after the records had been deleted, the paper said that the records were deleted... which makes no sense, obviously. It shouldn't change based on the current state of the record.

**Comment by Twinmold93** [comment]
Did you leave the record screen (Back on the screen) before the machine printed out the record paper itself? That's the most common way this occurs.

**Comment by Lady-Luck** [comment]
No, I did not.

**Comment by Lady-Luck** [comment]
Woops.
