### ISSUE TITLE
Mixing Cryox and blood directly between beakers

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5052]
**Problem Description**:
What is the problem?

When mixing blood and cryox together directly in a beaker it uses all the blood up but only produces 100 units of meat in the cloning pod.

**What did you expect to happen**: 
Why do you think this is a bug?

90 units of blood mixed with 10 units of Cryox doesn't seem right for the quantity of meat produced.

**What happened instead**:
How is what happened different from what you expected?

Expected to mix a lot more blood.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

You can accidently use a lot of blood and cryox without realising it.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Stand beside the Cloning pod. (fully upgraded)
Take a beaker of 90u blood and 90u cryox, apply the cryox to the blood. 
Instantly lose 30u of Cryox and 90u of blood.
Only get 100 units of biomass in the cloning pod.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

I did this on the escape shuttle as we were on the way to centcomm.

**Comment by TheDZD** [comment]
@Fox-McCloud This has been the case for absolutely ages. Any idea if that's intentional?

**Comment by Lady-Luck** [comment]
It's weird. You have to pour the blood into the cryox. Pouring the cryox into the blood gives you that result.

**Comment by Fox-McCloud** [comment]
Yeah, not sure if this is really intentional or not, but it has been this way for literally years. Technically cheese and some other reactions are within the same category.

**Comment by Fox-McCloud** [comment]
Going to add this as a feature.
