### ISSUE TITLE
ERT ain't spawning

### ISSUE THREAD

**Issue by Jaywings** [ParadiseSS13/Paradise#5053]
**Problem Description**:
ERT appears to not spawn in the proper manner when it is called. Even if people confirm they opted in.

**What did you expect to happen**: 
The ERT spawning in and relieving the station of PAIN.

**What happened instead**:
The ERT not spawning in.

**Why is this bad/What are the consequences:**
Well, when the crew requests ERT...most of the time it is for a good reason, such as Xenomorphs or high tier threats like nukies or so. And when they can't get help, they are stuck with less resources to work with and less people.

**Steps to reproduce the problem**:
Let ERT get swiped the usual way, attempt to dispatch like normal of any code. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Occasionally, it'll force an admin to be the ONLY ERT member while spawning five other non-occupied humans with military names.

**Comment by TheDZD** [comment]
@Kyep

**Comment by Kyep** [comment]
Will look tonight

**Comment by Spacemanspark** [comment]
REEEEEEEEE
