### ISSUE TITLE
Holobadges Cannot Be Worn on Certain Armor

### ISSUE THREAD

**Issue by Chakirski** [ParadiseSS13/Paradise#5058]
I hope this is not Working as Intendend :tm:, but so far the badges cannot be added to the warden's jackets or at the very least, the detective's armor. This possibly doesn't work for the Blueshield or anyone that doesn't use the standard black vest.

**Comment by KasparoVy** [comment]
Pretty sure this is the case because the way holobadges work is that, at least with the Sec vests, once you pin the holobadge to the vest it switches the item's icon_state from the default 'armour' (no badge) to 'armoursec' (exact same sprite with a 2x2px badge).

**Comment by Fox-McCloud** [comment]
Yeah, this isn't really a bug; they're really only meant to work with the default security armor.
