### ISSUE TITLE
Telecoms Teleporter

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#506]
When calibrated once, it does not let the player move through the teleporter; when recalibrated, it allows the player to go through, but sends them randomly into space as though it were not calibrated.
Mentor Rumi said he'd had the same issue as well.

**Comment by Markolie** [comment]
Can't reproduce. You'll have to find and note the specific circumstances in which this happened, then re-open this issue.

**Comment by PJB3005** [comment]
Seems like this is more intended and under specific circumstances than a glitvh
