### ISSUE TITLE
The abductor silencer does not, in fact, silence radio headsets.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#5066]
**Problem Description**:
During an abductor round I hit several people with the abductor silencer and yet they were still able to call for help on the radio despite me hitting them BEFORE they called for help.

**What did you expect to happen**: 
For their calls to help not to be broadcast over the radio once they were silenced.

**What happened instead**:
They called for help, crew busted in and nearly dunked me several times.

**Why is this bad/What are the consequences:**
The abductors have no way to prevent calls for help.  It's a severe nerf to their abilities given that the item is specifically meant to do one thing and it doesn't actually do that thing.

**Steps to reproduce the problem**:
Be abductor.  Run in, stun someone, use abductor silencer, let them try calling for help, get dunked on.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode was changelings, but the abductor team got going about 10 minutes into the round.  Nothing else special that I noted about the round, but I was de-admin'd the whole time so I could focus on my abducting.

IMAGES:
https://i.gyazo.com/d9f3d693873d776d194dceba096d908a.png
https://i.gyazo.com/d65ab472b090096881f7d49da8c11a50.png

**Comment by EpicCharger** [comment]
Being one of the people able to call for help on two occasions. I can verify that I actually didn't even know I was hit with a silencer.

**Comment by Fox-McCloud** [comment]
I've tested this so many times, I'm not quite sure where it's breaking...because...it's inconsistent, at best--sometimes it does silence, other times it fails; not really sure under what condition it fails, but it definitely works, at the same time, as well.

**Comment by Shadow-Quill** [comment]
It seems like it just turns off the speaker, instead of disabling the headset entirely.
