### ISSUE TITLE
Detective revolver can't be reskin again after first try

### ISSUE THREAD

**Issue by GutTC** [ParadiseSS13/Paradise#5069]
**Problem Description**:
Detective revolver (And apparently those that's able to, like bartender's DB) cannot be reskin after you have done your first reskin. You can still name it with pen anytime though.

**What did you expect to happen**: 
People said you can reskin anytime and how many times you want to. So that's pretty odd.

**What happened instead**:
Eh... The gun won't reskin ever again for entire shift?

**Why is this bad/What are the consequences:**
No biggie, just having your gun changed the skin you might not like for whole shift.

**Comment by Fox-McCloud** [comment]
Not a bug, this is very much a once a shift thing.
