### ISSUE TITLE
You cannot punch lightbulbs

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5073]
@FlattestGuitar 

>Changed it so that depending on the intent you will:

>on help - check if the bulb is hot (it is if the light is on), not actually touching it, so NO ACCIDENTAL DAMAGE
on disarm/grab - try to take the lightbulb out
on harm - hit the lightbulb
Both hitting and grabbing it is now possible only once a second, so there is no way to spam the thing, making suicide as lengthy as with all other brig methods.

You cannot punch the lightbulb in harm intent, it just tries to remove the light bulb.

**Comment by Fox-McCloud** [comment]
I don't think...you've ever been able to punch lightbulbs.

**Comment by Lady-Luck** [comment]
Fixed

**Comment by FreeStylaLT** [comment]
W-why would you want to punch a lightbulb

**Comment by Lady-Luck** [comment]
I HATE LIGHTBULBS OKAY

**Comment by Davdichan** [comment]
https://www.youtube.com/watch?v=dNzGZ41KnZ8 WHY WOULD YOU NOT?1

**Comment by FlattestGuitar** [comment]
I actually added the functionality in [#4246](https://github.com/ParadiseSS13/Paradise/pull/4246), but it was later removed by tigercat in [#4367](https://github.com/ParadiseSS13/Paradise/pull/4367) in a stealthy manner.

Do we really need punching?

**Comment by Lady-Luck** [comment]
Ahh, so that explains it.
