### ISSUE TITLE
Closed false walls leak air but temperature doesn't change

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5076]
So, yeah, a closed false wall leaks air. And when space is involved, it seems for some reason, while the air isn't being kept in the station, the temperature is holding steady, for reasons that frankly make no sense to me.

A false wall leading to space creates a vacuum that engineers cannot trace the source of without pushing on all the walls. And it's easily be done by accident, one might assume it does seal the air in.

I suggest making them not leak air because that's the more fun solution, it can help facilitate daring escapes into or out of space.

Here's proof of the leakage using plasma gas, by the way: https://s32.postimg.org/hijc2ajpx/e_Jw_Fwd_ENh_CAMANBd_GIAWFCtu_Q5_Cg_OW0_J1_Phxud3vva95_m_U.png

**Comment by FalseIncarnate** [comment]
False walls can't be created if there is a pressure differential of 25 or higher between the sides. They'd have to make the false-wall in an already breached / siphoned area, which in itself would probably be a giveaway that the walls probably aren't right.

As for them not sealing gas inside while closed, that is probably an oversight, as they never update CanAtmosPass

**Comment by Lady-Luck** [comment]
>False walls can't be created if there is a pressure differential of 25 or higher between the sides.

Uh, but I came across this bug making false walls into space, not knowing of this behavior.

**Comment by Lady-Luck** [comment]
>False walls can't be created if there is a pressure differential of 25 or higher between the sides.

Uh, but I came across this bug making false walls into space, not knowing of this behavior.

Or is that what you meant by the walls not being right?

**Comment by tigercat2000** [comment]
>As for them not sealing gas inside while closed, that is probably an oversight, as they never update CanAtmosPass

It's fully intentional. You can't make a new sealed airlock at any wall, it leaks air and sometimes even light.

**Comment by Lady-Luck** [comment]
Then it should be changed, for the reasons stating above.

Besides, GRILLS block airflow.

**Comment by tigercat2000** [comment]
>Besides, GRILLS block airflow.

uh, no they don't
break a few windows and watch the air flow out

**Comment by Lady-Luck** [comment]
I was testing this earlier and I was standing right up against a grill in maintenance that led to space, I never took O2 damage.

Maybe it was a fluke.

**Comment by Lady-Luck** [comment]
But anyway, yeah, the whole 'undetectable oxygen leak' thing is a big problem.

**Comment by tigercat2000** [comment]
it really isn't, turn off the lights and put on mesons, it becomes glaringly obvious

**Comment by Lady-Luck** [comment]
So if there's no light around the wall, mesons can detect it?

**Comment by Lady-Luck** [comment]
So if there's no light around the wall, mesons can detect it?

Or are you saying they both can do it, separately?

**Comment by tigercat2000** [comment]
false walls are objects
if you couldn't normally see the wall, mesons would show plating instead of a wall, because that's the turf that really exists there

**Comment by tigercat2000** [comment]
Further testing shows this is probably a bay thing, as they seal on /tg/. 
Still a feature request, though.
