### ISSUE TITLE
PA console - Ghost sight

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#508]
Ghosts are unable to view the Particle Accelerator computer, unlike every other computer, as far as I can tell - possibly because the SM computer is 'special' in some way?
Seems to be difficult for ghosts trying to teach a newbie engineer how2singulo.

**Comment by Markolie** [comment]
It's not an actual computer, but a type of machinery (just like the power monitor) that looks like a computer. As such, the regular attack_ghost code doesn't apply to it.

Fixing this would require refactoring the console's code.
