### ISSUE TITLE
You can pull a person out of their spacepod even if they aren't actually inside the pod.

### ISSUE THREAD

**Issue by Kerroman** [ParadiseSS13/Paradise#5088]
**Problem Description**:
During a recent round the clown (a Vox played by Xantholne) was able to nab a spacepod and started flying it around inside the station.  For whatever reason the spacepod bugged out and even when the clown wasn't inside the pod you could use an aggressive grab on the pod to pull him out.  I personally witnessed him disappear from near the clown office, and I also took screenshots of a before/after where I had him stand nearby and then I pulled him out and he teleported onto the pod.

**What did you expect to happen**: 
For you to not be able to pull anyone out of an empty spacepod.

**What happened instead**:
We were infinitely able to pull the clown out of the pod, regardless of the clown's actual location, and afterwards the clown would appear at the spacepod again.

**Why is this bad/What are the consequences:**
Unless spacepods come equipped with teleporters then this should NOT be happening.  I don't know how the bug is triggered, but if it's easily reproduced then someone could abuse the pod as a quick-teleport device by leaving the pod and an accomplice at a specific location.  It would presumably even work to get someone out of the brig.

**Steps to reproduce the problem**:
Find a pod, aggressive grab, click on the pod.  If there was someone in it have them move away from the pod and repeat.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Round was traitor-ling, but there was also a chrono-legionnaire running around.  I wasn't around when the bug was triggered, I only saw the results of it because the clown told me.  Again, clown was a Vox played by Xantholne so you might check with them for more info.

PICTURES:
For this first picture I asked the clown to stand nearby while I used an aggressive grab on the pod.  The clown did not move themselves between this picture and the next one. https://i.gyazo.com/e1c9c70fece21c018263d738082e13f5.png

This picture shows the result.  I didn't move at all, and the clown simply disappeared from where they were (ignore the other guy, he was passing by) and appeared on the pod in that exact location.
https://i.gyazo.com/2f48cf515d1ef0157acc1a9f0b4d0341.png

**Comment by Twinmold93** [comment]
I believe I know the issue already and can take a look into fixing it.
