### ISSUE TITLE
Can't see welded vents while in vents.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5097]
When you're inside the ventilation pipes you cannot see which vents are welded and which are not. They all appear unwelded.

There should either be a sprite that simply doesn't give you the information on whether they're welded or not, or simply the welding should be visible.

**Comment by tigercat2000** [comment]
not a bug
images are overlayed on pipes for convenience, that includes vents
if it's welded while you are still in the pipes, you can't see the change

**Comment by FlattestGuitar** [comment]
If you leave the vents and reenter you still cannot see the welding overlay.

**Comment by tigercat2000** [comment]
reconnect and it'll probably work

**Comment by FlattestGuitar** [comment]
I'm 60% sure that's still something that should be fixed.

**Comment by tigercat2000** [comment]
I'm 99% sure that it's not fixable without massively changing how the vent images are handled

**Comment by Davdichan** [comment]
Seems I missed this, but I've noticed that you can't see welded vents while in a vent pipes, but you can see if scrubbers are welded or not, and vice versa. What black magic causes this I don't know.

**Comment by TheDZD** [comment]
Apparently fixable by updating pipe_image when a vent is welded/unwelded
