### ISSUE TITLE
Space Hotel's SNPC can be objectives for antags

### ISSUE THREAD

**Issue by Signmark** [ParadiseSS13/Paradise#5110]
**Problem Description**:
You got rare chance to take objective when you should kill/prevent/consume/etc SNPC

**What did you expect to happen**: 
Only player characters to kill/prevent/consume/etc

**What happened instead**:
Game asking antag to kill some SNPC on Space Hotel away mission.

**Why is this bad/What are the consequences:**
Antag got access to gateway = antag completed his objective.

**Steps to reproduce the problem**:
1.Be Antag (Adminbus or by Random)
2.Be lucky enough to take objective related to SNPC

**Also**:
Got this on AutoTraitor gamemode. Did not happen on other modes, but maybe im not lucky enough

**Comment by Fox-McCloud** [comment]
already fixed, just not patched.
