### ISSUE TITLE
Speaking into radio makes you talk instead of whisper

### ISSUE THREAD

**Issue by sasanek12** [ParadiseSS13/Paradise#5117]
**Problem Description**:
What is the problem?
When you talk into radio, your voice to people around is transmitted with full volume, not as whisper
**What did you expect to happen**: 
Why do you think this is a bug?
I expected to whisper into radio, so only people closest to me can hear me
**What happened instead**:
How is what happened different from what you expected?
I was speaking with normal "speaking volume", so everyone in my eyesight range could hear what am i saying into radio
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
You were always whispering into radio instead of talking on full volume, in crowded rooms it turns into complete mess.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
put headset on
Talk into radio
Greyshirt hears your call for help from other side of the room and beats you with toolbox
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by tigercat2000** [comment]
quick question
did your headset fail to send the message on whatever channel you tried to use

**Comment by Spacemanspark** [comment]
The same has been happening to cyborgs for around a month or so.
And no, Tiger, it doesn't fail to sent the message.

**Comment by tigercat2000** [comment]
well shit

**Comment by Lady-Luck** [comment]
What happens if you whisper to a channel

**Comment by Lady-Luck** [comment]
Man this is annoying.

**Comment by LittleBigKid2000** [comment]
Working as intended
