### ISSUE TITLE
Weather - Advanced darkness is too advanced

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#5118]
**Problem Description**:
The Darkness weather option does not let you choose which Z level to target with the weather effect, and it makes the screen pitch black.

**What did you expect to happen**: 
![68747470733a2f2f692e6779617a6f2e636f6d2f39653333366630333162313661353036613566663534363339383434313832312e706e67](https://cloud.githubusercontent.com/assets/10961410/17003779/1ef975cc-4e97-11e6-967f-c6b0ea9c0dd1.png)

**What happened instead**:
Pitch black, as if there was no light source at all. Toggle Darkness didnt work nor did night vision equipment. It was just a black screen.

**Why is this bad/What are the consequences:**
It's broken :v

**Steps to reproduce the problem**:
Secrets menu > Weather: Advanced Darkness. Prepare to see nothing.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was changlings but that's all.

@Fox-McCloud

**Comment by TheDZD** [comment]
The link is dead.

**Comment by Earthdivine** [comment]
fff

**Comment by Spacemanspark** [comment]
![](http://www.gdunlimited.net/forums/uploads/gallery/category_6/gallery_25428_6_104777.png)

**Comment by Earthdivine** [comment]
After using Ash Storms and seeing the image I linked was an Ash Storm thing, I am inclined to believe this is intentional, but I'll leave it up to Fox to say so.

**Comment by Fox-McCloud** [comment]
Ash storm is mining z-level only. You can't change that. Likewise, the advanced darkness is station only and is meant to make the screen literally pitch black--definitely not a bug; this is all working as intended.
