### ISSUE TITLE
You'll not believe what happened to the mining station when we took their APC! [Prank] [Gone sexual] [Gone wild] [ERP] [Banned from TV]

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5120]
**Problem Description**:

Western Mining station is missing it's APC since the re-map.

**What did you expect to happen**: 

I thought all rooms were supposed to have APCs for them to work and things.

**What happened instead**:

APCs are missing.

**Why is this bad/What are the consequences:**

Nothing works on the Western half of the mining station.

**Steps to reproduce the problem**:

Enter the mining station, go to the western half, crowbar open the door. Stand in the darkness listening to Simon and Garfunkle.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

The mining station lights on the western half have not worked for a long time without turning the light switch on and off.

**Comment by tigercat2000** [comment]
lol

**Comment by taukausanake** [comment]
clickbait yessssssss
