### ISSUE TITLE
Airlock sensors not actually detecting current status

### ISSUE THREAD

**Issue by GeneralChaos81** [ParadiseSS13/Paradise#5122]
**Problem Description**:
What is the problem?
The Airlock Controller only detects chamber pressure at 101kPa. This means pressing the inside button will open the door, but Cycle to Exterior, or the exterior button will syphon all the air, but it never detects low enough to open, so doesn't.
Screenshot: http://general-chaos.com/pics/atmosbug.jpg

**What did you expect to happen**: 
Why do you think this is a bug?
Door should let you back into the station.

**What happened instead**:
How is what happened different from what you expected?
Didn't get back into the station without AI intervention.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
What's spessmen without access to spess?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Attempt to cycle any airlock to exterior.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I think it was working in one round, but not the following two. Did not seem round related. I could also be wrong, I was messing around a lot with a newbie and don't perfectly recall, but I don't remember getting stuck in the engine area.

**Comment by Twinmold93** [comment]
That's a new bug that just came out of nowhere, which likely means one of the newer PRs broke it. This would be the same for the disposal issue you have posted.

**Comment by Crazylemon64** [comment]
As with the disposal bug, a hijacked `initialize` call didn't hit the parent, meaning it didn't get to hop in the machine processing wagon.
