### ISSUE TITLE
Camera computers and telescreens not working, and holding you back in life

### ISSUE THREAD

**Issue by GeneralChaos81** [ParadiseSS13/Paradise#5124]
**Problem Description**:
What is the problem?
Clicking on the computer appears to do nothing. But then you can't move away until you Cancel-Camera-View or click on another ... computer? That worked for me. Not sure about other items.

**What did you expect to happen**: 
Why do you think this is a bug?
Open list of cameras to view, then see far away lands

**What happened instead**:
How is what happened different from what you expected?
I couldn't see anything, and I was also stuck

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Station security, and engine maint.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Click on monitor computer or telescreen. AI might have this issue too, to some degree.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Seems to have happened every round.

**Comment by GeneralChaos81** [comment]
I saw this in another report/pull. Just make sure your ID is in your ID slot, not a PDA or anything else.

**Comment by Fox-McCloud** [comment]
been fixed.

**Comment by GeneralChaos81** [comment]
Spectacular!
