### ISSUE TITLE
Disposals units won't flush

### ISSUE THREAD

**Issue by GeneralChaos81** [ParadiseSS13/Paradise#5126]
**Problem Description**:
What is the problem?
Disposals don't flush automatically or manually.
Status is stuck on pressurising.

**What did you expect to happen**: 
Why do you think this is a bug?
Because they should

**What happened instead**:
How is what happened different from what you expected?
Used to work.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Gets rid of rubbish. Sends things to cargo. Quick escape for antags.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Insert item into disposals, or press Engage

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Since it's stuck pressurizing, maybe related to sensor issue with airlocks? https://github.com/ParadiseSS13/Paradise/issues/5122

**Comment by taukausanake** [comment]
I just noticed this myself. The disposal unit in Hydro wasn't working. This happened after the AI decided to siphon the room of all air because I had normal bees in it and traitor botanist decided to be Dr. Bees. Might be related

**Comment by Belario** [comment]
I saw this too, kept trying to disposal myself to escape sec, it isn't working.

**Comment by Crazylemon64** [comment]
I found the issue - the disposals do not do a parent call in `initialize` - which will add them to machine processing. I will remedy this now.
