### ISSUE TITLE
Security Cell UI Issues

### ISSUE THREAD

**Issue by counterfeitguise** [ParadiseSS13/Paradise#5139]
Two problems require fixing that have come to our attention after the recent map change - Brig's wiring is already being worked on in a separate PR, so here's some issues with the UI instead:

**1: Cell UI missing the Activate Flash button.**

![image](https://cloud.githubusercontent.com/assets/16391918/17023515/fbd4c070-4f53-11e6-9ca3-ae6ad062ab91.png)
> Where's Activate Flash?! Reeeee!

**2: Cell UI opening multiple times after being closed.**
I don't actually have a picture for this one, as the problem seems to be gone when hosting on a local server - but a few people have experienced the issue as well, including Love-To-Hug and Sasanek12.

Considering I have no formal coding experience, nor do I even pretend to know what I'm doing, you can take this with a grain of salt. I assume it's being worked on, but it's here for documentation regardless.

**Comment by Fox-McCloud** [comment]
@monster860

**Comment by monster860** [comment]
Ouch, I'm being poked!

**Comment by monster860** [comment]
Oookay, here's my response to this:

The lack of "Activate flash" is a mapping error - There needs to be a flash with the same `id` as the brig timer for the button to exist

The second problem.... onclose is not being called properly.

**Comment by Fox-McCloud** [comment]
@FreeStylaLT

**Comment by FreeStylaLT** [comment]
![img](http://i.imgur.com/WMH6wCZ.png)

![img](http://i.imgur.com/qGsQ19d.png)

That's on the server atm, I mean it LOOKS to be fine. Unless there's a different kind of ID I'm not aware of
@monster860
