### ISSUE TITLE
Clicking the Backpack with X4 Arms it

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#5140]
**Problem Description**:
X4 Attaches to the backpack instead of being put inside

**What did you expect to happen**: 
For it to not activate on my backpack

**What happened instead**:
It attached and activated to my backpack but thankfully I tactically threw my backpack preventing any harm

**Why is this bad/What are the consequences:**
I almost went boom

**Steps to reproduce the problem**:
1. Get X4
2. Put X4 in hand
3. Click on backpack with X4 (Not a backpack slot, just the backpack)
4. Observe rapidly flashing blinking thing in the corner of your eye and throw backpack to avoid being blown up

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
![4a8b4ddfb4c19839f7ee178b8e350f17](https://cloud.githubusercontent.com/assets/20497797/17023904/b303f17a-4f23-11e6-9945-894a1b56aa5d.png)

**Comment by TheDZD** [comment]
@DaveTheHeadcrab

**Comment by Lady-Luck** [comment]
Might be related to #5055?

**Comment by chopchop1614** [comment]
https://github.com/ParadiseSS13/Paradise/pull/5253
