### ISSUE TITLE
Xenomorph's health indicator doesn't change.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#5146]
**Problem Description**:
The xenomorph health indicator always reads at 100%

**What did you expect to happen**: 
It should go down as one takes damage.

**What happened instead**:
It stayed filled up at 100% while I took damage.

**Why is this bad/What are the consequences:**
Very difficult to see how damaged you actually are.

**Steps to reproduce the problem**:
Be a xenomorph.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was a drone at the time.

**Comment by Markolie** [comment]
Can not reproduce.
