### ISSUE TITLE
Tea Cups Have no Sprite

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#5148]
Yup, tea has no sprite

@Fox-McCloud

**Comment by Lady-Luck** [comment]
why would you put Sprite in tea, that sounds gross

**Comment by FlattestGuitar** [comment]
>why would you put Sprite in tea, that sounds gross

kek <-- this one
kek
kek

**Comment by CrAzYPiLoT-SS13** [comment]
Literally unplayable
