### ISSUE TITLE
Clicking on the body accessory button or trying to use a mirror as a mentor gives insufficient rights message (But works fine)

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#5149]
When I click on the body accessories button, it works fine, but I get the message 'Error: You do not have sufficient rights to do that. You require one of the following flags: +ADMIN.' in chat. When I try to use a mirror, it spams this message (Or a similar one, I'm doing this from memory), but, again, works just fine.
It's probably important to note that I'm a mentor.

**Comment by counterfeitguise** [comment]
this happens with the library computer too, the one behind the desk

**Comment by KasparoVy** [comment]
Seems to only happen to mentors-- not encountering that bug at all under any circumstance as a player
