### ISSUE TITLE
If your ID is in your PDA, you cannot swipe your PDA to authenticate announcements

### ISSUE THREAD

**Issue by Wheatley29** [ParadiseSS13/Paradise#5151]
Title.

**Comment by CrAzYPiLoT-SS13** [comment]
I imagine the same situation being with the authentication devices for red
alert, ERT and such.

**Comment by Taaketa** [comment]
Nor can you unlock borg covers with your ID in your PDA.

**Comment by Spacemanspark** [comment]
reeeeeeeee

**Comment by FlattestGuitar** [comment]
Same with lockboxes, you need to take your ID out of the PDA to swipe.

**Comment by Plotron** [comment]
That's a 'feature', y'know.

**Comment by Fox-McCloud** [comment]
Not really a bug.

**Comment by tigercat2000** [comment]
Some of these are definitely just using the wrong calls to get something's access.
