### ISSUE TITLE
Hot Dutch Choco Sprite missing

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5158]
**Problem Description**:
What is the problem?

It's missing it's cup sprite.

**What did you expect to happen**: 
Why do you think this is a bug?

Can't see a cup.

**What happened instead**:
How is what happened different from what you expected?

I want a cup when I buy my hot dutch choco, holding it in my hand is unacceptable.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Cups always came free. Taking free stuff away is not right.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Buy a cup of hot dutch choco from a vending machine. Hold your hands in front of it and try to drink it before you hands develop 3rd degree burns.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
figured as much.

**Comment by Taaketa** [comment]
I just realised you submitted @Fox-McCloud should I close this in favour of #5148 ?

**Comment by Fox-McCloud** [comment]
well, it's similar, but separate.
