### ISSUE TITLE
Borer bugs! 

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#516]
If a borer logs out while in a host, it loses its ability to hear anything.
It gets the same messages as if knocked out.
Borer chat seems to be broken.
Taking contol, leaving the host and coming back in host does not fix it.
Taking control and returning control without leaving the host does not fix it.

When being a host controlled by borer, you can't understand common. Not sure if bug or intended.

**Comment by TheDZD** [comment]
Being unable to hear is a problem that sleeping is set on, and borers do not tick down sleeping, which is set on whenever a person goes SSD or uses the Sleep verb, as only humans (and perhaps other carbons) will recover from sleep.

The other hivemind and host not understanding are langauge bugs, and I am not certain ofthe cause.

**Comment by CrAzYPiLoT-SS13** [comment]
Isn't this fixed? I saw something fixing the simple_animals sleep thing.
