### ISSUE TITLE
People can hide from the Tesla in cardboard boxes

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5160]
**Problem Description**:
What is the problem?

#4704 does not stop cardboard box cheese and hiding inside of them from the Tesla.

**What did you expect to happen**: 
Why do you think this is a bug?

Pretty sure the point was of the linked PR was to stop locker cheese hiding.

**What happened instead**:
How is what happened different from what you expected?

People didn't get nice and toasty like a burger king burger.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by TheDZD** [comment]
Did any of the tesla bolts actually hit the cardboard box? If memory serves, those hitting structures (closets are structures, and cardboard boxes are closets) is what calls their tesla_act, which is what should destroy the lockers.

**Comment by Fox-McCloud** [comment]
If this is broken, then it's broken for regular closets too, as cardboard boxes are a child of closets....IF it's broken to begin with.

**Comment by Taaketa** [comment]
Well I didn't see the sprite. But I died right beside someone in a cardboard box. They moved over me and opened and closed it again. So can the Tesla miss someone by one tile?

**Comment by Spacemanspark** [comment]
I have no regrets porting cardboard boxes but holy cow all these issues with them.

**Comment by sothangel** [comment]
I have seen lockers and crates get destroyed by the tesla today, fwiw.

**Comment by Fox-McCloud** [comment]
If they're getting destroyed, then cardboard boxes most certainly are, 'cause they're a child of lockers.

**Comment by Lady-Luck** [comment]
I was witness to that round and the cardboard boxes were not getting destroyed.

**Comment by KasparoVy** [comment]
Ditto. Cardboard boxes took 0 damage and their contents (players) were entirely unscathed by teslas being within a couple tiles or so while people in lockers got destroyed.

**Comment by LittleBigKid2000** [comment]
Did some testing. Cardboard boxes are destroyed by the tesla just fine.
![](https://gyazo.com/e735880f40a6269a1fd8a3a6251eea9e)

**Comment by Lady-Luck** [comment]
@LittleBigKid2000 Maybe the problem isn't that they're indestructable. Maybe the problem is that, under normal circumstances, the cardboard boxes simply aren't being targeted by the bolts when the tesla is loose.

**Comment by Spacemanspark** [comment]
Which would make sense when you think about it

**Comment by Lady-Luck** [comment]
>Which would make sense when you think about it

No. Whether something is insulated or not isn't binary, different materials have different levels of insulation. With something as strong as the Tesla, there's nothing on the station insulated enough to handle it.

**Comment by TheDZD** [comment]
Yeah this is just because the Tesla prioritizes structures dead last, and closets (and by extent, cardboard boxes) are structures.
