### ISSUE TITLE
VV's "Drop Everything" command makes mob drop all limbs

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#5163]
**Problem Description**:
It drops all limbs AND all items

**What did you expect to happen**: 
I expected it to drop all items

**Steps to reproduce the problem**:
Spawn human mob -> VV -> "Drop Everything"

**Comment by tigercat2000** [comment]
again?

**Comment by Spacemanspark** [comment]
Hahaha, that sounds hilarious.

**Comment by KasparoVy** [comment]
This must mean that cmd_admin_prison doesn't work either because it strips mobs before imprisonment in the exact same way.

**Comment by TheDZD** [comment]
[This is the proc that handles it.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/admin/verbs/randomverbs.dm#L1-L17)

**Comment by LittleBigKid2000** [comment]
No reasonable person would assume that "Drop everything" does not include limbs. PEBCAK.

**Comment by Davdichan** [comment]
Must be specifically tuned to IPCs

**Comment by Crazylemon64** [comment]
This should be fixed by #5170
