### ISSUE TITLE
Deleting a wall does not cause nearby atmos to update

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#5168]
Deleting a floor to space will cause nearby atmos to update (nearby floors getting icy, losing pressure), however, deleting a wall to space will leave nearby atmos undisturbed.

**Comment by Lady-Luck** [comment]
I think that's intended due the way walls work... as far as I can tell, there's never a floor beneath walls truly, a floor is created when the wall is somehow destroyed or deconstructed.

So if for some reason you need to delete a wall, you don't want atmos to start spreading ilke crazy.

**Comment by tigercat2000** [comment]
more "walls should never actually be deleted without some of their stupider procs called"

**Comment by Crazylemon64** [comment]
Explosions are capable of deleting a wall without updating the turfs next to it.
