### ISSUE TITLE
'Security uniform, corporate' cannot be selected in loadouts

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5174]
When you try to click on it to add it, nothing happens.

**Comment by FlattestGuitar** [comment]
The Syndicate doesn't want you wearing the stylish embodiment of corporate justice. It's their fault. 

Will fix

**Comment by LittleBigKid2000** [comment]
@FlattestGuitar Beat you to it.

**Comment by FlattestGuitar** [comment]
No fair.
