### ISSUE TITLE
Blood vomiting does not cause blood loss

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5176]
Virology problem, there's a symptom called vomiting blood, however all it does is deal brute damage when you throw up, there's no actual blood loss.

**Comment by TheDZD** [comment]
@Fox-McCloud @tigercat2000 Intentional?

**Comment by tigercat2000** [comment]
@TheDZD pretty sure it's supposed to just be a visual effect to the vomit() proc
