### ISSUE TITLE
Loadout oversights.

### ISSUE THREAD

**Issue by Faryaa** [ParadiseSS13/Paradise#5181]
**Problem Description**:
New loadout system is neat but there is some things which some jobs supposed to have but can't.

**What did you expect to happen**: 
Brig physician as medical job should be allowed to choose: Skirt: Medical
Internal Affairs Agent should be allowed to choose: Classical Security HUD(they have HUDs at round start anyway), IAA shades, you can find in their locker.
Warden should be allowed to spawn with his alternative warden suit on.
Head Of Security and Head of Personel could choose their alternative jumpsuits.
Quartermaster should be allowed to pick both cargo tech and miner things(can choose only cargo tech things now)
Bandanas as loadout items: red for security, green for botanists.

**Comment by FlattestGuitar** [comment]
Some of these are not oversights. Will fix the ones that are.

**Comment by FlattestGuitar** [comment]
All of the ones I considered issues I fixed back in https://github.com/ParadiseSS13/Paradise/pull/5182/files. The rest are more feature requests than anything. 

Some of the items are a bit too specific to be in the system in its current state, though a lot should be adjusted, in my opinion.

I'd close this one.
