### ISSUE TITLE
Unable to unlock borg with Roboticists ID inserted into PDA

### ISSUE THREAD

**Issue by 9ktbugg9** [ParadiseSS13/Paradise#5183]
**Problem Description**:
What is the problem?
Unable to unlock borg with Roboticists ID inserted into PDA

**What did you expect to happen**: 
Why do you think this is a bug?
Because normally you would have access with just your ID.

**What happened instead**:
How is what happened different from what you expected?
It said Access Denied

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's annoying to have to take out your ID whenever you need to open a borg

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Insert ID into PDA. Attempt to unlock an online borg.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Pretty self explanatory

**Comment by Fox-McCloud** [comment]
Not a bug---PDA != ID cards.
