### ISSUE TITLE
Vamp Thralls and Dethralling issues

### ISSUE THREAD

**Issue by Dumbdumn5** [ParadiseSS13/Paradise#5189]
**Problem Description**:
Admins can't Dethrall vamp thralls via the Traitor Panel.

**What did you expect to happen**: 
That I could thrall and dethrall vampire thralls at will.

**What happened instead**:
I could not do the above because angry red text without an underline said no to me.

**Why is this bad/What are the consequences:**
Because issues involving ahelps, SSDs, and other junk.

**Steps to reproduce the problem**:
Have a vamp with thralls, attempt to dethrall, profit?

(Be aware, you can't thrall people either via TP)

**Comment by Kyep** [comment]
Looking at it.
