### ISSUE TITLE
Console screen overlays can be placed/open above screen height, and are consequently impossible to close or move

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#5193]
**Problem Description**:
The upper part of the window is outside the screen

**What did you expect to happen**: 
![image](https://cloud.githubusercontent.com/assets/10612280/17099429/fc9e1b4e-5270-11e6-861d-6a6a6af3ef02.png)

**What happened instead**:
![image](https://cloud.githubusercontent.com/assets/10612280/17099421/f1e3d950-5270-11e6-9654-d90b713450ed.png)

**Why is this bad/What are the consequences:**
I can't close the camera console!

**Steps to reproduce the problem**:
1. Set screen resolution to 1366x786
2. Open Camera Console

**Comment by Lady-Luck** [comment]
Press Alt+Space and then press 'M'. This activates move mode, you can now move the window with Shift + Arrow keys.

**Comment by FireFlashie** [comment]
tgstation/tgstation#1948

**Comment by FlattestGuitar** [comment]
Are you implying we need to us TK to move the windows?

**Comment by AffectedArc07** [comment]
TGUI force opens windows where the titlebar is visible.
