### ISSUE TITLE
Shuttle admin-verbs are broken

### ISSUE THREAD

**Issue by FireFlashie** [ParadiseSS13/Paradise#5196]
**Problem Description**:
![image](https://cloud.githubusercontent.com/assets/10612280/17109867/83877638-52a2-11e6-84f2-ae3748ddd53e.png)
This buttons doesn't working! Maybe verbs was removed?

**What did you expect to happen**: 
Erm... Something?

**What happened instead**:
Nothing.

**Steps to reproduce the problem**:
Admin->Secrets->Any_Of_These_Buttons

**Comment by tigercat2000** [comment]
oversight, never removed them

**Comment by yurivw** [comment]
Jesus Christ, sorry for the spam. God damn github desktop app man, don't even think about using it.
