### ISSUE TITLE
Atmos backpack.

### ISSUE THREAD

**Issue by fj45** [ParadiseSS13/Paradise#520]
Its damn fun to use, but has two minor issues:

It doesn't start with any water loaded. People will find this out the hard way

Foam takes quite a while to form into metal. Doesn't need to be reduced by too much but currently you can be waiting for far longer then you should need to.

**Comment by Fox-McCloud** [comment]
Definitely agree with it starting off full; probably not for the foam though, or else it's going to be end up being used in an RCD like manner to easily block areas.

**Comment by fj45** [comment]
Possibly, but it doesn't take much to smash through foam and even just a small reduction would be good.

**Comment by Markolie** [comment]
This'll have to go on the forums.
