### ISSUE TITLE
Black Hoodie shows up White In Hand

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#5215]
**Problem Description**:
Something supposed to be black is white when you hold it in your hand

**What did you expect to happen**: 
For it to appear black, not white

**What happened instead**:
It shows up white

**Why is this bad/What are the consequences:**
Because white is not the new black

**Steps to reproduce the problem**:
1. Get loadout with Black Hoodie
2. Hold Black Hoodie in hand
3. Observe white thing in hand (not the hand slots, but your actual character)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by FlattestGuitar** [comment]
That's because I didn't bother doing the `item_sprite` for the hoodies, same with most of the things I've added. It's also a problem on a massive amount of other items - using a placeholder sprite carried over from something similar.

We just need a slave to sit and sprite away for 48 hours straight and we'll be golden.

**Comment by taukausanake** [comment]
Spriting is fun, if someone can do it correctly. Wasn't there a list of needed sprites somewhere in Issues? Is it still open/being worked on?

**Comment by FlattestGuitar** [comment]
Literally more than half the items we have lack item (in-hand) sprites. Just pick objects at random, most won't have one.

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/issues/4806

**Comment by Chakirski** [comment]
The code literally has it set to show a lab coat in hand.......

**Comment by FlattestGuitar** [comment]
Yes, I did it intentionally. With over 30 sprites to work on I didn't want to bother with the item sprites, so I just set it all to labcoats, which are reasonably similar.

**Comment by Chakirski** [comment]
Could set the hoodies to the blueshield coat.

**Comment by Ty-Omaha** [comment]
> if you want to appease the picky ones

kek'd
