### ISSUE TITLE
Nautical Energy Sword ( Chaplain weapon) causing crashes

### ISSUE THREAD

**Issue by Captainhandicap** [ParadiseSS13/Paradise#5216]
**Problem Description**:
This didn't happen all the time so I was not entirely sure, but sometimes when I put the nautical energy sword in my hand it would cause surrounding players to go SSD. I also ahelped about it but didn't get a response so it was a coincidence. I later confirmed it when I charged at two syndicate operatives and they claimed they crashed. 

**What did you expect to happen**: 
I expected to get gunned down by the operatives. 

**What happened instead**:
The energy sword caused them to crash ( I am almost positive this is the case)

**Why is this bad/What are the consequences:**
It is pretty game breaking if you can cause players to crash at will. 

**Steps to reproduce the problem**:
-Be chaplain
- turn null rod to nautical energy sword
- equip at belt
- walk near other players and move sword to hand
- I think 70% of the time, the players went SSD for me.
- ( The user does not crash)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was during that invasion round ( forgot the name). Its where the syndicate commander declares war on the station. Also I was in a wheelchair, not sure if that matters.

**Comment by TheDZD** [comment]
I really don't think it was the energy sword that caused this, in all likelihood it was just a coincidence.

**Comment by Captainhandicap** [comment]
Yup I tried it again, just a coincidence.

**Comment by Spacemanspark** [comment]
The SSD.
The Sword of Sudden Doom.
