### ISSUE TITLE
Liches lose X-Ray Vision on death

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5220]
Just messing around on a private server, and I noticed something peculiar with Scrying Orb

Scrying Orb Cost:2
An incandescent orb of crackling energy, using it will allow you to ghost while alive, allowing you to spy upon the station with ease. In addition, buying it will permanently grant you x-ray vision.

I bought this and later on I ended up doing myself in to see how the lich mechanic worked. Only, when I respawned, X-Ray Vision was gone, even though the power makes itself apparent the x-ray vision is supposed to be permanent and not tied to the item you get.

**Comment by Fox-McCloud** [comment]
Not a bug. There's a lot of things not retained when you respawn---your gear, the stuff you had on you, etc.

**Comment by Lady-Luck** [comment]
The reason I reported it was because it very explicitly states that x-ray vision is 'permanent', which is misleading.
