### ISSUE TITLE
Second blob crash in a row, one yesterday and one today

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5221]
Still isn't fixed! :(

**Comment by TheDZD** [comment]
Not a very descriptive report. Did it crash at the start of the round? In the middle? Anything that might have been related? The issue report template exists for a reason.

**Comment by Lady-Luck** [comment]
>Not a very descriptive report. Did it crash at the start of the round? In the middle? Anything that might have been related? The issue report template exists for a reason.

There's not a lot I have to report, to be quite honest. All I know is that it happened about an hour in, there were two blobs, and the larger one had two cores and two nodes.

A lot of people theorize it has to do with the lingering smoke problem.

**Comment by TheDZD** [comment]
As in, the spore clouds linger around when they should despawn?

**Comment by Lady-Luck** [comment]
Yes.
