### ISSUE TITLE
Agent ID doesn't seem to be working properly

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5230]
I asked mentors for help on this and they had no idea why it wasn't working, so if this isn't a bug and I'm doing something wrong I apologize.

On my private server, I purchased an agent ID. I was holding the CMO card in inactive hand, and then I clicked the agent card onto it. Nothing. I tried dropping the CMO card and testing doors to see if it copied access without giving me a message. Still nothing. Tried setting the CMO card on the floor and then clicking on it with the agent card. Still nothing.

Then I tried dragging and dropping each card onto each other, both from the floor and in my hands, vice versa... still nothing.

It certainly seems broken to me.

**Comment by tigercat2000** [comment]
you have to be a traitor to sync access on the card

**Comment by Lady-Luck** [comment]
Yes, I am a traitor, I know I set that up correctly in the traitor panel.

Suddenly it's working now without having changed anything. I have no idea what made it suddenly start working. So uh. I'll re-open this later if I can figure out what's going on.
