### ISSUE TITLE
With parallax off, AI can see all of space

### ISSUE THREAD

**Issue by LiquidNightfury** [ParadiseSS13/Paradise#5236]
**Problem Description**:
Disabling parallax allows the AI to see beyond it's cameras

**What did you expect to happen**: 
Crewmember would leave camera range on walking into space.

**What happened instead**:
I was able to track a crewmember to the edge of the space tile after the shuttle left.

**Why is this bad/What are the consequences:**
AI is capable of observing things way beyond its reach.

**Steps to reproduce the problem**:
Join as AI. Look at space. Disable parallax.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode was nuke ops. Crewmember was observed walking into space as shuttle left unexpectedly, and was tracked floating to the end of the tile, despite being off cameras. While some areas of space camera static were still in place, the majority of space around the station was still visible.

**Comment by Fox-McCloud** [comment]
Parallax was reverted, so...

**Comment by TheDZD** [comment]
@monster860 Might want to fix this once you are going through the bugs.
