### ISSUE TITLE
Borked pAI crew manifest

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#5242]
**Problem Description**:
I play alot of pai, and have noticed the Crew manifest tends to wig out and break for no seen reason.

**What did you expect to happen**: 
I expect to open the crew manifest, and it behave like the PDA one

**What happened instead**:
http://puu.sh/qic2r/c825886401.png

**Steps to reproduce the problem**:
Be PAi, Purchase crew manifest module, use crew manifest. Sometimes it works, sometimes it does the above.

**Comment by Spacemanspark** [comment]
https://github.com/ParadiseSS13/Paradise/issues/5114
