### ISSUE TITLE
CondimasterNeo Interface Errors

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5249]
**Problem Description**:
When trying to create a pill or bottle the Condimaster always yields a pack.

**What did you expect to happen**: 
Pretty self explanatory, In both cases of trying to create a bottle or a pill I get a pack in either case.

**What happened instead**:
I got a pack with said chemical.

**Why is this bad/What are the consequences:**
Machine isn't working properly due to new interface. Chef can't really create their bottles to sort ingredients for their own use.

**Steps to reproduce the problem**:
Put a beaker with a chemical in the Condimaster, Try to make a pill or bottle with the condimaster, get a pack of said chemical instead. You can't extract directly from chemical packs.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nope.

**Comment by Crazylemon64** [comment]
Is the bug here that you're getting options to make pills, even when you shouldn't be able to? The `topic` calls for the condimaster don't allow you to make pills, patches, or bottles - pills become packs, and bottles become condiment shakers.

**Comment by TheDZD** [comment]
#5292
