### ISSUE TITLE
Xenos can't harm borgs.

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#525]
Both queens fought and died to a medical borg because they could not harm it. My intent was on Harm, I do not know the other queens but I assume disarm or harm. There's also other reports that the regular xenos cant harm the borgs either. I do not know if this pertains only to Medical Borgs or all, as there was only a Medical Borg aiding the crew.

EDIT: Kluys just check for us, they can't harm any borg. We can pet them though!

**Comment by Fox-McCloud** [comment]
Yup; disarm works though; fixing this as we speak.

**Comment by Fox-McCloud** [comment]
Fixed.
