### ISSUE TITLE
Massive-scale APC Destruction Is Incredibly Expensive

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5252]
The shout itself causes massive lag to the server even if all the lights have already been broken by a previous shout. In fact, the lighting of the station refused to update until the shadowlings stopped shouting. Once the lighting finally did finish updating, a shadowling used their audible-shout again, and everything lagged to hell again.

**Comment by FlattestGuitar** [comment]
Shadowlings cannot use the scream more than once, it's only used during an ascendance.

Also, I don't believe ascendance is what directly caused the lag, but it's possible.

**Comment by Lady-Luck** [comment]
It totally was - when the lights finally updated and everything went buttery smooth for about 20 seconds, another shadowling ascended and the server lagged to hell again.

**Comment by Belario** [comment]
The same thing happens when malf AI's use their blackout ability to mass break light bulbs, it's probably the strain of so many of them smashing at once/being checked for possible smashability rather than something to with the sling.

**Comment by TheDZD** [comment]
Yeah, it's not specifically to do with the shadowling, it's the fact that mass lighting updates cause that.

**Comment by Lady-Luck** [comment]
@TheDZD Even when all the lights are already broken, though?

It feels like it's doing extra work that it shouldn't.

**Comment by Lady-Luck** [comment]
Just had another sling round where the server lagged hard for 5 minutes straight, can this be looked at? I think there's something else going on here...

**Comment by PJB3005** [comment]
Uh, it's pretty goddamn hard for the lighting updates themselves to cause it (scheck), only thing I can think of is the logic in `light_source/update()` but even that isn't bad.

Also I don't know whether you've addressed this since but the lack of pooling in spark effect systems caused a big performance problem when I was testing baylights on here.

**Comment by TheDZD** [comment]
This is apparently caused by `playsound()`, that's certainly not what I expected.

**Comment by Lady-Luck** [comment]
Vindication!
