### ISSUE TITLE
Trial admins have access to a lot of stuff they shouldn't have access to.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5266]
Trial admins, whose role it purely administrative, can modify and announce antagonist objectives. Shouldn't be the case, I believe.

**Comment by Earthdivine** [comment]
They have access to and can edit the Traitor Panel?

Also what do you mean by Announce? If you mean AOOC that's not much a problem.

**Comment by FlattestGuitar** [comment]
I mean the "announce objectives" button that is located below the objective editing stuff. AOOC should be usable, for admin purposes, but I think trialmins having no effect on the round is ultimately the point here.

**Comment by TheDZD** [comment]
Yeah this probably should check for R_EVENT

**Comment by Twinmold93** [comment]
The announce objective verb tells the traitor whom you have the TP up for what their objectives are. Useful when you change their objectives. I believe the reason Trials have access to TP, and can edit it more precisely (they should definitely be able to see it), is to change the objectives of someone if an inconsistency itself occurs (for example, target is SSD in the middle of nowhere, change traitor's target).

**Comment by FlattestGuitar** [comment]
Also, another one we spotted.

In addition to rejuvenating people, trial admins can trigger godmode.

**Comment by Twinmold93** [comment]
Rejuvenate can be useful, considering the primary usage is for countering grief or fixing strange bugs that you cannot otherwise fix as a TA (presuming you make sure there is nothing else wrong with them that rejuv would make things very... Unfair). As for godmode, I have no idea why TA even has that.

**Comment by KasparoVy** [comment]
Not an admin but :+1: to rejuv :-1: to godmode for the reasons mentioned above

**Comment by tigercat2000** [comment]
a lot of VV's options are completely unlocked
godmode barely even works

**Comment by FlattestGuitar** [comment]
You could always *trust* us to not abuse it. 

Hihi.

**Comment by Sirryan2002** [comment]
announcing and modifying objectives isn't an issue, its intended for trialmins to be able to field ahelps and needed fixes regarding antagonist objectives. However, godmode access for trialmins is an issue.
