### ISSUE TITLE
Curse of the Horsemask does not let you horsemask anyone

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#5270]
**Problem Description**:
It seems to trigger the "It would be stupid to curse X with a horse's mask!" on _everyone_

**What did you expect to happen**: 
For.. I think anyone to be able to get horse masked

**Why is this bad/What are the consequences:**
Spell is literally unusable

**Steps to reproduce the problem**:
Get spell, try to use it on anyone

>It'd be stupid to curse Jay Wingler with a horse's head!

>It'd be stupid to curse the monkey (567) with a horse's head!

>It'd be stupid to curse Dynhrherrdra Njarir'Akhan with a horse's head!

**Comment by Plotron** [comment]
Horse masks *are* stupid after all!

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/spells/horsemask.dm#L29>It looks like it's pretty stupid to horsemask a human...</a>

**Comment by TheDZD** [comment]
@Crazylemon64 I think I missed a `!` in there.
