### ISSUE TITLE
Drone talk is broken

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5271]
**Problem Description**:
What is the problem?

Using :d .d or setting default language to drone talk. Does not imitate or communicate on drone talk.

**What did you expect to happen**: 
Why do you think this is a bug?

Drones cannot communicate with each other unless audibly done.

**What happened instead**:
How is what happened different from what you expected?

Drones instead default to common and speak aloud for everyone to hear.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

I like my silent drone, never speaking, never talking, except to other drones.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Using :d .d or setting default to drone talk does not communicate on drone talk.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Taaketa** [comment]
Other Maint Drone problems by the by:

#4696 #4065 #3607 #3191

**Comment by Crazylemon64** [comment]
Drone talk is done via `;`.

**Comment by LittleBigKid2000** [comment]
That seems... wrong. Snowflakey, maybe. The drone talk language has a key (`:d`), why would it use `;`?

**Comment by tigercat2000** [comment]
drones don't actually have a language iirc
they have a radio, which means they use ;

**Comment by LittleBigKid2000** [comment]
They do
![](https://i.gyazo.com/cebe9917283bf169eb0743c16a8bab6a.png)
It's in code\modules\mob\language.dm, line 551.

**Comment by Taaketa** [comment]
@tigercat2000  .d :D and set default has always worked and I only noticed this shift. Having said that, even if they didn't have a language. Why is is listed on their known languages and can be selected as their default language and not work?

**Comment by tigercat2000** [comment]
I recall the :d hotkey definately *not* working for a time, and even noting that the help text should say `;`

**Comment by Crazylemon64** [comment]
It's probably `handle_message_mode` being overridden for a drone to not do language parsing
