### ISSUE TITLE
CREMATING a chaplain ghost sword...

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#5290]
...don't ask..

Anyway it cuased a runtime and made the creamtorium break 

[08:55:54] Runtime in morgue.dm,364: Cannot execute null.ghostize().
   proc name: cremate (/obj/structure/crematorium/proc/cremate)
   usr: Sefra'neem (fethas) (/mob/living/carbon/human)
   usr.loc: The floor (177,145,1) (/turf/simulated/floor/plasteel)

**Comment by Fox-McCloud** [comment]
I'm guessing this is a problem with the crematorium itself and how it loops through things.

**Comment by FlattestGuitar** [comment]
https://github.com/ParadiseSS13/Paradise/blob/eb0bb6da7f222040e7894e9c80fd950f75e063f3/code/game/objects/structures/morgue.dm#L354

The loop populates a list, but then removes items that are on it. Pretty sure that's the cause here. Too lazy to fix though.
