### ISSUE TITLE
Abductors dont show up as any race on examine

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#5291]
**Problem Description**:
examining abductors doesnt show up any race on the examine

**What did you expect to happen**: 
them to show as the disguised race

**What happened instead**:
the spot for race in examine text was blank

**Why is this bad/What are the consequences:**
this means anyone can identify abductors by examining them

**Steps to reproduce the problem**:
be an abductor, disguise as someone and examine yourself

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: i was a pAI at the time

**Comment by TheDZD** [comment]
I know abductors are already easily identifiable anyways, due to the fact that their disguise only affects their sprite, and not their examine text. That said I have no idea about whether or not the species thing here is intentional.

@Fox-McCloud

**Comment by FlattestGuitar** [comment]
It was my doing. There specifically is an exception for them to not show up.

I don't think I ever tested it with their camouflage on...

**Comment by KasparoVy** [comment]
Best test it with camo on to see if people can meta through their disguise by checking if it says what race they are (or doesn't) on examine

**Comment by FlattestGuitar** [comment]
This will need some snowflaking, unless we don't want to bother. 

If I'm not mistaken there's already a message on examine for camoed up abductors, so not much more meta from this one, I'd say.

**Comment by sothangel** [comment]
Abductors wearing camo still show as wearing the agent helmet and vest stuff iirc, so being able to tell that they aren't what they appear to be because of the lack of race appears trivial currently

**Comment by Fox-McCloud** [comment]
This is intentional, and as @sothangel pointed out, you can see what equipment they're *actually* wearing anyway, if you examine them--this is also intentional.
