### ISSUE TITLE
Invisible Riot Helmet Sprite for Drask

### ISSUE THREAD

**Issue by Dumbdumn5** [ParadiseSS13/Paradise#5297]
Well, when applying a riot helmet to a drask, the magics that occur behind the scenes take a cigar break and ignore that the helmet should be in front of those pesky bullets before they get to your face, and yet, by sheer force of will, the air surrounding the head blocks the bullets travelling towards the user.

**Comment by FlattestGuitar** [comment]
"Let's not add a species that will need special sprites for clothing items." 

"Nah"

*literally this*

**Comment by GelatinousGlob** [comment]
Roman legion helm is also invisible.

**Comment by QuinnAggeler** [comment]
The riot helmet? As opposed to the normal sec helmet?

**Comment by LittleBigKid2000** [comment]
Well it's either that or having what are basically human copies, Fluffiest.
