### ISSUE TITLE
Bandolier sprites are borked

### ISSUE THREAD

**Issue by mrturkeytoe** [ParadiseSS13/Paradise#5303]
**Problem Description**:
What is the problem?
Bandolier sprites are invisible.
**What did you expect to happen**: 
Why do you think this is a bug?.
I expected to see the normal bandolier sprite as bartender/when I open up a shotgun crate.
**What happened instead**:
How is what happened different from what you expected?
The bandoliers have no sprite.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
People will not be able to see or use bandoliers.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Have a bandolier.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by yurivw** [comment]
It seems that when you spawn a full bandolier the sprite does work, even when you take all the shells out. If I spawn a empty bandolier the sprite doesn't work.
