### ISSUE TITLE
Shuttle Wall Locker Stowaways = Greentext for 'Prevent X from Escaping Alive' Objective

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#5306]
**Problem Description**:
I got greentext for preventing a certain target from escaping alive when really they were just in a wall locker on the shuttle until it docked.

**What did you expect to happen**: 
I was certain I wouldn't get greentext at all because they were on the shuttle, but they were 'stowaways' in a wall locker so I suppose it didn't count.

**What happened instead**:
My target hid in a wall locker and was still in the locker when the shuttle docked, so it gave me greentext for preventing their escape.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
N/A

**Steps to reproduce the problem**:
Be a traitor with the 'prevent X from escaping alive' objective. Have X hide in a wall locker on the shuttle until it docks. Get greentext.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was autotraitor and I got traitor near the end of the round and detonated a C4 inside the wall locker with my target that caused minimal damage.

**Comment by monster860** [comment]
On the other end of the spectrum, you can get redtext if the target is in transit on any shuttle, or in any way is on z2.

**Comment by Ar3nn** [comment]
But how is being in the locker voiding being "in transit"?

**Comment by KasparoVy** [comment]
Is the locker's loc in the wall? If so, is being inside one of the shuttle body's external walls counting people as in transit or no? Those answers might help here.

**Comment by Spacemanspark** [comment]
Wall lockers aren't actually on the wall, but on the floor and their sprites just have an offset to give the appearance of such.

**Comment by KasparoVy** [comment]
Apparently the issue is a result of mobs' z-level values reverting to 0 when entering a wall locker.

_Mob z-level before and after entering a locker. Yes it goes back to 2 when you leave the locker._
![lockervoodoo](https://cloud.githubusercontent.com/assets/12377767/17457846/413293d4-5bd1-11e6-8e77-b57ad32a6ae9.png)

**Comment by KasparoVy** [comment]
Got it, PR coming shortly.
