### ISSUE TITLE
Infected Wounds can't be Cured

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#532]
I've suspected this for months but it's only since I gained ADMINPOWERS that I can effectively test my theory.
Injecting Spaceacillin into an area will reduce the germ level for that area, but the infection never goes away. I don't know why. However, I noticed that whilst the germ level for specific areas go down, the germ level for the entire mob (which seems to be seperate) remains unaffected by spaceacillin.
Even when I got the germ level for the mob to 0 and filled the mob with 1000 units of spaceacillin the germ level for the wound (in this case the chest) went to 0 but the 'infected wound' status on the health analyser never actually went away. After the spaceacillin wore off the germ level began climbing again.

The reason why this has been broken for so long is probably because infected wounds do so very little toxins damage, but it's a waste of spaceacillin.

**Comment by tigercat2000** [comment]
This is an intentional feature, IIRC
Wounds that are labeled as 'infected' on the body scanner have to be treated by surgery.
http://nanotrasen.se/wiki/index.php/Surgery#Infection_Treatment

**Comment by mwerezak** [comment]
The germ level for the entire mob is not directly related to infections. It represents how dirty you are.

**Comment by CrAzYPiLoT-SS13** [comment]
Shouldn't this be closed?

**Comment by KasparoVy** [comment]
probably

there's alot of 'issues' in the issues list that have been fixed or otherwise dismissed that are still hanging around

**Comment by Fox-McCloud** [comment]
I've been able to successfully treat both internal and external infections with spaceacillin alone--though, admittedly, cauterization is best for anything that's not an infected internal organ.
