### ISSUE TITLE
New gas sprites

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5326]
**Problem Description**:
What is the problem?

Gas sprites cover over the existing ground and make it impossible to click on objects on the ground. For example tasers or cult runes. You have to ALT-Click which isn't very good if you're in a rush as antag.

**What did you expect to happen**: 
Why do you think this is a bug?

Gas shouldn't block clicking on things.

**What happened instead**:
How is what happened different from what you expected?

As above

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Makes it hard to do anything with a gas layer over the top of things.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Was cult round, released N2O on the shuttle but couldn't pick things up underneath the gas.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Chakirski** [comment]
Duplicate #5195

**Comment by Taaketa** [comment]
Woops. Closing.
