### ISSUE TITLE
Solgov traders don't count as antagonists

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5329]
Solgov traders:
- don't show up on the "check antagonists" list
- don't have their objectives printed at round end
- don't have an antagHUD icon
- probably some other things

For the sake of fun objectives and admin sanity they should have all of those, considering they can accomplish their objectives using less than legal procedures, which might often be encouraged by a GA.

**Comment by taukausanake** [comment]
I don't know if they're supposed to be antags? Sounds a little messed up even if they are allowed to do anything illegal. They're an official group that is meant to do trading with the station by allowance of CentCom, not there to steal shit like birdmen

**Comment by FlattestGuitar** [comment]
Regardless, admins should have an easy way to check what objectives they have and locate them, as well as being able to easily identify them when aghosted. 

Giving them an antagHUD icon and adding them to the `check antagonists` panel would solve that.

**Comment by Kyep** [comment]
@AffectedArc07 Closable, not a bug. Sol Traders are not antags, don't have randomized objectives, and basically never leave the trade ship.
