### ISSUE TITLE
Taking people out of cryodorms 

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#533]
I recall fox saying that you can't take people out of Cryodorms on the fourms. Well I witnessed people taking players out of Cryodorms a few round ago, so either it was never added in or something broke.

**Comment by Fox-McCloud** [comment]
I never said this was added; I said, ideally it would be a feature to prevent people from taking others out of cryodorms.

**Comment by Earthdivine** [comment]
Ah alright then, I guess change this from an issue to a feature request then? It would help cut back on SSD's being looted, as we're starting to get an increase in civs not knowing what the room is for.

**Comment by Markolie** [comment]
Those should go on the forums.
