### ISSUE TITLE
Changeling Objectives - Diona Identity

### ISSUE THREAD

**Issue by counterfeitguise** [ParadiseSS13/Paradise#5338]
Got a mentorhelp questioning why Changelings have Diona as their "Escape With Identity" objective, since plantpeople aren't absorb-able. Figured it'd be worth posting here.

Disregard if I'm wrong.

**Comment by TullyBurnalot** [comment]
@TheDZD Cannot reproduce.

**Comment by Doukhan** [comment]
I've been on the receiving end of this a few times with diona targets, specifically diona clowns.
It's definitely real.
