### ISSUE TITLE
A Clown Syndi Traitor couldn't attach a guest pass to their ID

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5343]
This needs testing. I gave someone a guest pass and it wasn't able to attach to their ID card. I even tried to do it for them, it wouldn't work. Attached to mine just fine. What was odd is that at the end of the round, it didn't show that they had bought an Agent ID, so I'm not sure if it's even related to that.

**Comment by monster860** [comment]
The guest pass either needs to be unnamed or have the same name as the ID you are attaching it to.
