### ISSUE TITLE
Associative Lists are borked in VV

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5347]
![](https://i.gyazo.com/3bed208de079fbdf92f7ea00a1b09277.png)
That's how it looks and it shouldn't look like that. Yes, I checked on different lists, I couldn't get a single one to work.

**Comment by FreeStylaLT** [comment]
How should it look like?

**Comment by FlattestGuitar** [comment]
As you can probably imagine, the list isn't just seven words, it also assigns values to those words.
Those values should be shown, otherwise this is pointless.

**Comment by FalseIncarnate** [comment]
Actually... That is actually "somewhat working as intended (patent pending)"

The code armor[1] would return "melee"
The code armor["melee"] would return the value of the association, which is what you expected.

Sadly, to my knowledge at least, BYOND has no way of checking if a list is associative, so we'd either assume all lists are associative and or that all are not (current assumption) in VV.

**Comment by Necaladun** [comment]
It used to show the actual values for everything at once point. It was nice to see them all at once.

You can still see the values, but you have to try to edit each.

**Comment by tigercat2000** [comment]
@FalseIncarnate VV is definitely not behaving as intended. Associative lists worked perfectly fine at one point.

**Comment by VampyrBytes** [comment]
@FalseIncarnate 
Ok, this is theoretical, I haven't tested it and someone will correct me if I'm wrong, but while you can't test directly if a list is associative, you should be able to check for values. eg
```
for(var/v in listToCheck)
    if(!(listToCheck[v] == null)  // an associative list should never have a null value in it as it kinda defeats the object - we're checking directly for null as if we use (!listToCheck[v]) it would give a positive on 0 which could be valid
         dealWithAccosiativeLists(listToCheck)
        return    // or break if needs be
    //deal with regular lists here
```

I *think* that should work - As there aren't 2 different types of list object, regular and associative, I would guess all lists are actually associative but just have null as the associated value, so this should work. I'm sure @tigercat2000 will correct me if I'm wrong :wink:

**Comment by VampyrBytes** [comment]
Actually, if the theory is right, a better way would be

```
proc/checkForAssociative(var/list/listToCheck)
    if(!listToCheck || !istype(listToCheck))
        return
    var/found = 0
    for(var/v in listToCheck)
        if(!(listToCheck[v] == null))
            found = 1
            break
    return found
```

**Comment by VampyrBytes** [comment]
ok, ignore me. Finally got around to testing this and it doesn't work

Only way I can see of being able to tell if a list is associative or not is to make list based datums with a var that tells you if it's associative, and then replace every list in the game with these datums...

any volunteers? :wink:

**Comment by PJB3005** [comment]
How to see if a list is assoc: `json_encode` it and look what the first character is. If it's `{` then it's assoc.

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/commit/20eee9064c6fcdad7693fc20a41a7ac226414bf6#diff-d6caed4c71d6e079bd3710a3323e43bfR398 Dammit lemon
