### ISSUE TITLE
NT Script: Combining strings and numbers doesn't work as intended

### ISSUE THREAD

**Issue by WhiteHusky** [ParadiseSS13/Paradise#5356]
**Problem Description**:
Trying to combine a string and a number doesn't work as intended

**What did you expect to happen**: 
```
myVar = "Some Text " + $freq + " More text";
broadcast(myVar);
```
`COMMON SERVER says, "Some Text 1459 More text"`

**What happened instead**:
`COMMON SERVER says, " More text"`

**Why is this bad/What are the consequences:**
Not a game breaking issue, but annoying if you're playing with the telecom servers and writing code for them.

**Steps to reproduce the problem**:
```
myVar = "Some Text " + $freq  + " More text";
broadcast(myVar);
```

**Comment by CrAzYPiLoT-SS13** [comment]
I'm pretty sure you cannot combine integers and strings. Although, don't
take my word for it.

**Comment by FlattestGuitar** [comment]
Yeah, that's not how it works. In this case `90` isn't a number, it's a variable called "90".

Since the script can't find that variable, it goes mad.

If you want to print numbers like that just do `"Some Text 90 More Text"`

**Comment by TheDZD** [comment]
This isn't a bug, you can't add different data types.

**Comment by Chakirski** [comment]
Pretty sure you can add quotes to a variable to make it a string and then merge whatever.
