### ISSUE TITLE
Using the invisimin function makes your character (not just ghost) invisible to all non-admin players.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5357]
I knew we had plans to implement space ninjas for a while now, but this seems a bit too unbalanced.

**Comment by tigercat2000** [comment]
Uh. That's the *entire point* of invisimin. It's an admin tool for a reason.

**Comment by FreeStylaLT** [comment]
Intentional.

**Comment by FlattestGuitar** [comment]
Well, the message on toggle says it's your ghost that will be invisible, not your character in-game. Might want to chage that.

**Comment by tigercat2000** [comment]
... no
it says
```
to_chat(mob, "<span class='notice'>Invisimin on. You are now as invisible as a ghost.</span>")
```
```
as invisible as a ghost
```
which is completely accurate, your mob's invisibility is set to the same as a ghost; anyone that can see ghosts can see you

**Comment by FlattestGuitar** [comment]
Aight. I can't read.
