### ISSUE TITLE
Changelings and Tajaran appearance.

### ISSUE THREAD

**Issue by Fotum** [ParadiseSS13/Paradise#536]
Changelings who absorbed Tajaran appearance can wear shoes while Tajaran cannot wear standart shoes.
How to reproduce:
Start as changeling.
Absorb Tajaran.
Get Tajaran appearance.
Look at your equipment and ingame model (shift click on yourself will also show that you are wearing shoes).
This "bug" can easily make changeling discovered.

**Comment by Spacemanspark** [comment]
Same thing occurs if an admin turns a mob that is wearing shoes into a Tajara. If the Tajara takes off the shoes, they cannot put them back on.

**Comment by ZomgPonies** [comment]
Will be fixed once I port the Frankenstein stuff. The ability to wear shoes will be tied to the actual limb object.

**Comment by CrAzYPiLoT-SS13** [comment]
Is this fixed yet?

**Comment by tigercat2000** [comment]
can probably look into this once frankenstein is merged.

**Comment by TheDZD** [comment]
Fairly certain this isn't an issue anymore.

**Comment by FlattestGuitar** [comment]
Are you sure? I'm pretty sure I've witnessed a tajaran changeling with shoes on fairly recently. 

Transformation should check if the equipment is wearable and drop it if it's not.

**Comment by tigercat2000** [comment]
it really isn't worth snowflaking tangerines into changelings for something the player needs to remember to do, if this even happens

**Comment by FlattestGuitar** [comment]
Wouldn't be too much of a snowflake to just loop through all their equipment restrictions, I'd say.

**Comment by taukausanake** [comment]
What about that frankenstein thing? Didn't that happen back when?

**Comment by tigercat2000** [comment]
it really would be, a full inventory search for the sake of some damn shoes
@taukausanake yes, but it was never expanded upon

**Comment by FlattestGuitar** [comment]
And gloves, and anything we might ever add in the future. 

Is it meta to see a Unathi with normal shoes and accuse them of being a changeling? Maybe we should add that to the server rules? 👀

Really, transformations happen rarely enough this wouldn't be much of a performance impact.

**Comment by Fox-McCloud** [comment]
@FlattestGuitar or kill off the restriction. I know it received support on the Discord. Even Bay themselves killed it off.

**Comment by FlattestGuitar** [comment]
I don't see why not. I shouldn't be able to find *mangled* nitrile glove traces on the RD's locker and they don't really add anything to RP or pure gameplay.
