### ISSUE TITLE
NT Rep's fancy cane doesn't work as a normal cane

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5362]
You would think that a one legged NT Rep would be pretty decently off considering that they have the fancy cane, but apparently it does not provide the same benefits the normal canes do for one legged folks, which is a weird inconsistency.

**Comment by TheDZD** [comment]
[Holy fuck this is how cane walking assistance is handled.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/human_organs.dm#L81-L84)

**Comment by Plotron** [comment]
Oh, thanks for reminding me about this issue!

I should've reported it long ago...
