### ISSUE TITLE
Interact with object while your are in vent.

### ISSUE THREAD

**Issue by PrototypeNitro** [ParadiseSS13/Paradise#5363]
**Problem Description**:
What is the problem?
You can interact with object when you are vent crawling
**What did you expect to happen**: 
Why do you think this is a bug?
You can't get ghost-arm to open a locker.
**What happened instead**:
## How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Non realist
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I was vent crawling then I saw someone hiding in closet I clic on the closet a PAF, closet open
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I was drone. Someone hidding from Tesla. I was at escape. Vent crawling protecting myself from EMP

**Comment by SamHPurp** [comment]
I was able to re-produce this.

You can open lockers even if there is no 'opening' like a vent or a scrubber anywhere nearby. Should be able to be fixed with a simple if ventcrawling check.

**Comment by SabreML** [comment]
Fixed by #13768, but they forgot to add it to the PR.
