### ISSUE TITLE
Vampire Attack Grammar and Typo

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#5364]
**Problem Description**:
"[VAMPIRE] grabs the farwa's harshly and sinks in thier fangs!"

**What did you expect to happen**: 
"[VAMPIRE] grabs the farwa harshly and sinks in their fangs!"

**What happened instead**:
Grammar and typo happened. "[VAMPIRE] grabs the farwa's harshly and sinks in thier fangs!"

**Steps to reproduce the problem**:
1. Be vampire.
2. Try to suck someone's blood (?) or something, whatever that message comes from.

**Comment by Fox-McCloud** [comment]
Already fixed. Not patched.

**Comment by Plotron** [comment]
damn it, how could I miss that PR?

**Comment by Plotron** [comment]
@Fox-McCloud: That PR does not fix the grammar issue with "grabs PERSON's harshly"
As far as I know, I can grab a person harshly, but not a person's harshly.
