### ISSUE TITLE
Courtroom Wooden Floor Tiles are Metal Floor Tiles in disguise.

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5370]
**Problem Description**:
What is the problem?

Courtroom Wooden Tiles are Metal tiles. The can be crowbarred up and magically become metal tiles.

**What did you expect to happen**: 
Why do you think this is a bug?

Wooden tiles need to be unscrewed and do not normally magically change to metal.

**What happened instead**:
How is what happened different from what you expected?

Wooden should be metal.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Not at all. Just inconsistency.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Crowbar up tiles in courtroom. Lay tiles back down. Magic metal tiles.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment]
@FreeStylaLT

**Comment by Spacemanspark** [comment]
This sounds vaguely familiar...
Didn't the bar have a few tiles with this issue awhile ago?

**Comment by FreeStylaLT** [comment]
waht de fa

**Comment by FreeStylaLT** [comment]
.... oh my god /floor/plasteel has a wood sprite why? **why**
