### ISSUE TITLE
Cyrodorms storing bug?

### ISSUE THREAD

**Issue by jughu** [ParadiseSS13/Paradise#5377]
**Problem Description**:
It seems my idd got dropped when i got cyrod and ghosted

**What did you expect to happen**: 
Just a clean cyro without my idd dropping out of cyro

**What happened instead**:
The idd got out of my pda and out of my satchel and just dropped on the ground

**Why is this bad/What are the consequences:**
Since this will leave access at cyro which nobody can prevent from somoene getting it

**Steps to reproduce the problem**:
if i was right i did the following i ha clothing since those were job clothing which i gave away then i put my idd in my pda then in my satchel then jumped in cyro ghosted and idd dropped

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Traitor i was just going to cyro

**Comment by Ty-Omaha** [comment]
to hijack this a bit, now when you ghost out and use LOOC it says your ckey instead of your mob name which really irks me

**Comment by Spacemanspark** [comment]
If you're a ghost, your LOOC name will be your Ckey. This is how it's worked for a long time.

**Comment by Ty-Omaha** [comment]
I'm almost certain it used to be mob name

**Comment by Spacemanspark** [comment]
Incorrect.

**Comment by Doukhan** [comment]
@Ty-Omaha It's been that way for a while, if you re-enter your body it'll show up as whatever your corpse is currently called.

I do remember it being the other way around a looong time ago though.

**Comment by Plotron** [comment]
Less LOOC meta that way, Ty.
