### ISSUE TITLE
Uplink drink is wrong color

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#5386]
**Problem Description**:
> ![ORANGE](http://nanotrasen.se/wiki/images/2/29/Uplink_drink.png) The chemicals mix to create shiny, blue substance.

The drink is orange.

**What did you expect to happen**: Not to have color inconsistencies.

**What happened instead**: What color is it really?

**Why is this bad/What are the consequences**: MUH IMMERSIONS!

**Steps to reproduce the problem**: Create Uplink with reagents. Look at chat area when completed

**Comment by Alexshreds** [comment]
omg unplayable :-1: :x: :100:

**Comment by GeneralGoose** [comment]
piss

**Comment by Lady-Luck** [comment]
"The chemicals mix to create shiny, orange substance."

fixt

**Comment by taukausanake** [comment]
Shit did I just get a special label made? WONDERFUL

**Comment by FlattestGuitar** [comment]
THIS IS ALL MY FAULT I AM SO SORRY

**Comment by taukausanake** [comment]
YOU BETTER BE I SPENT TEN WHOLE MINUTES ON THIS WHEN I COULD BE PLAYING SPESSMEN

**Comment by Rumiluntti** [comment]
Meh emulsions is ruin!!

**Comment by Gummin** [comment]
> THIS IS ALL MY FAULT I AM SO SORRY

this should be a crime :angry:
