### ISSUE TITLE
You retain current underwear with Changeling Transform

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5392]
**Problem Description**:
When you use changeling transform, you will have the same underwear you spawned with.

**What did you expect to happen**: 
To have the same underwear as the person I turned into, or be naked.

**What happened instead**:
I retained the bikini I spawned with.

**Why is this bad/What are the consequences:**
Because people aren't going to believe I'm the real Ty Omaha when I'm wearing a bikini.
There's no way to actually remove the underwear from your character post-spawn, save cloning, so my brilliant* plan to frame him went up in smoke.

(*It wasn't actually all that brilliant but I thought it would be fun at the very least.)

Also, it should probably copy whatever underwear the real person is wearing, rather than just being naked, because there is the meta-game aspect of being able to assume the one with no underwear is the changeling and the one with underwear is the real person.

(And for the double whammy in the same round, #3217 screwed me as well. I was going to transform Ty into someone else to make him seem like a changeling. Transformation sting simply doesn't work. Completely broken.)

**Comment by theColdflame** [comment]
underwear can be changed from dressers unless that's been changed or I'm wrong

still an issue though I guess

**Comment by Lady-Luck** [comment]
News to me. Where is a dresser on the station?

**Comment by theColdflame** [comment]
locker room, captain's bedroom, probably a couple other places

**Comment by Ty-Omaha** [comment]
Well I mean.. _some_ people might believe I would wear a bikini.. but that is surprisingly not the case (at least not yet it isn't... :smirk: )

**Comment by Plotron** [comment]
Lings synthesizing underwear.

...

C'mon

**Comment by Lady-Luck** [comment]
>Lings synthesizing underwear.

It is weird but underwear metagaming due to the way underwear works is the pits.

**Comment by Doukhan** [comment]
Not body swapping and then absorbing?
Amateurs.

**Comment by TheDZD** [comment]
This isn't a bug, changelings work via DNA appearance. Underwear is not stored in DNA, if you want to switch it go use a dresser.

**Comment by Lady-Luck** [comment]
that's a disappointing ruling. metagaming ahoy

**Comment by tigercat2000** [comment]
@Lady-Luck Actually claiming changeling and killing someone over a pair of underwear is against the rules. Deciding to investigate someone because they're wearing strange underwear.. really isn't metagaming, though? Part of being a changeling is learning to disguise yourself completely.
