### ISSUE TITLE
Putting on Atmos hardsuit is enough to resist over pressure and high levels of O2

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#540]
This could be several issues in one here. By accident I overfilled atmos with too much O2 raising the O2 mix above 50% over N2. My character was still able to breath ok, even when it was at 150kpa.

I put my hardsuit on from atmos and didn't even have to run internals. Wasn't until the atmos pressure level dropped to 59kpa did I have to use internals.

**Comment by Fox-McCloud** [comment]
Could you please describe a bit more precisely what exactly happened? It's not clear what was overpressurized--your internals? The room (I'm assuming), or something else? 

Also pressure and being able to breathe are correlated, but not directly connected; there's plenty of instances where areas can be overpressurized and you can still breathe, but typically it's underpressurization that's the issue.

**Comment by Taaketa** [comment]
Sure.

Basically I had an O2 tank in Atmos. Someone released the valve on it, whilst it was being filled.

This caused the atmos pressure to reach 156Kpa and set off the atmos alarm with a warning for internals. The atmos also reached 50% N2 and 50% O2 because of the gas release. But I didn't struggle to breath nor did there seem to be any random fires. Which I thought was supposed to happen with O2 at that ratio and pressure. Put a hardsuit on afterwards and I was fine too.

I didn't struggle to breath as well until the atmos at around 50kpa (When I was cycling the air). Maybe not a bug but something does seem wrong about the high O2 levels though.

**Comment by Fox-McCloud** [comment]
Yeah, not a bug; this is functioning as intended.

The only negative effects of overpressurization are taking high pressure damage; if there's 16 moles of oxygen in each breath, then you'll be absolutely fine, even if it's 1,000,000 kPa. This if fully functioning as intended; it's only low O2 concentrations that are a hazard.
