### ISSUE TITLE
Nude fat mob doesn't show up as fat

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#5402]
**Problem Description**: A naked human who is fat does not have the fat human sprite but the normal sprite

**What did you expect to happen**: To look like this:
![I'M SEZY](https://cloud.githubusercontent.com/assets/1978025/17538734/c1c0b4a6-5e6d-11e6-9ec9-2d90316964e3.png)

**What happened instead**: This:
![I'm not as sezy](https://cloud.githubusercontent.com/assets/1978025/17538739/d048d44a-5e6d-11e6-8332-0aa2b2414b81.png)

**Why is this bad/What are the consequences**: Some clothing that does not cover up the whole body (or future additions to fat clothing) look weird and floating above the mob sprite. Also you're a fucking fatass, look like one dammit.

**Steps to reproduce the problem**: Make character with fat disability or Player Panel someone with FAT gene activated. Put on clothing and notice your body doesn't change but the size of your gut with a uniform on does.

**Possibly related stuff**: N/A

**Comment by tigercat2000** [comment]
someone broke this at one point

**Comment by Alexshreds** [comment]
Dear god more sprite voodoo
