### ISSUE TITLE
You eat forks whole when eating from them

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#5425]
You don't leave forks behind when you eat food using them

**Comment by FlattestGuitar** [comment]
Wait. People don't do that?

**Comment by Taaketa** [comment]
I love to fork my mouth.

**Comment by VampyrBytes** [comment]
wtf? afaik I was the last to touch forks, when I did my eating refactor, so I'll look into this when I get the chance (RL is still hectic, so in the meantime just enjoy the added flavour of the fork with your mouthful :wink: )

**Comment by TullyBurnalot** [comment]
@TheDZD Cannot reproduce.

**Comment by GeneralGoose** [comment]
what the fork

**Comment by Fox-McCloud** [comment]
haven't seen a repeat of this; going to assume it was a once off extremely weird/odd thing.
