### ISSUE TITLE
False reinforced-walls cannot be coated

### ISSUE THREAD

**Issue by Norgad** [ParadiseSS13/Paradise#5427]
**Problem Description**:
 You cant heat-proof a false reinforced-wall

**What did you expect to happen**: 
To be able to heat proof them

**What happened instead**:
I opened the wall

**Why is this bad/What are the consequences:**
You can know that a wall is definitely **not** false if it is coated

**Steps to reproduce the problem**:
Make a false reinforced-wall, try to coat it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This seems like it was just an oversight

**Comment by Alexshreds** [comment]
I believe false walls are just doors, not actual walls.

**Comment by Fox-McCloud** [comment]
>I believe false walls are just doors, not actual walls.

This.
