### ISSUE TITLE
IPC repairs are broken once again

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#5428]
**Problem Description**:
Limbs don't work properly, arms and legs cannot be attached normally, you can attach feet without attaching legs and hands without adding arms and MORE, like internal repairs that are fucked as well

**What did you expect to happen**: 
to be repaired as normal

**What happened instead**:
I got both my feet and hands but somehow no arms or legs i could use the hands like normal but my moving speed was horrible

**Why is this bad/What are the consequences:**
repairing IPCS is impossible/very VERY hard

**Steps to reproduce the problem**:
get an IPC to lose some of his limbs and try to attach them again

![wheres my arm](https://cloud.githubusercontent.com/assets/11246791/17619794/0858bbfe-6088-11e6-8127-1cdf5503758c.jpg)

**Comment by FreeStylaLT** [comment]
at this point IPCs breaking should be tagged "Working as Intended™"

**Comment by FlattestGuitar** [comment]
At this point it will just be easier to switch to only having Vulpkanin as a species. Imagine how much :snowflake: the code would lose...

**Comment by jguy555** [comment]
This just in, if you add a leg to the arm and then add an arm to that the arm is fixed.... what the hell

**Comment by FreeStylaLT** [comment]
__WORKING AS INTENDED™___

**Comment by Lady-Luck** [comment]
So basically IPC parts need to be attached with normal 'limb attachment' and cyborg parts that you make form the machine need to be attached with 'robotic limb attachment'.

And robotic limb attachment lets you do really weird things like attaching legs to arm slots and then you can attach an arm to that in the hand slot.

**Comment by Dumbdumn5** [comment]
If we can get back to the buggy state it'd be just like old times, and when we try to fix the bugs they'll shout that it's another unnecessary buff to the OP race!

**Comment by sothangel** [comment]
Now, this happened to my character - It seemed like I was missing my upper arms and upper legs on the health doll - But when I attempted to repair them, I fixed them and updated the doll.

**Comment by TheDZD** [comment]
The jukebox, spacepods, and IPCs. Three things that no matter how much you fix them, will always find a way to bug out.

**Comment by Crazylemon64** [comment]
I HAD a fixed IPC system, but I guess I can reconcile it with the current surgery system, too

**Comment by Taaketa** [comment]
Repaired a fully disassembled IPC today. No problems other than it's head had to be put on with limb attachment instead of robotic.

**Comment by Spacemanspark** [comment]
@Taaketa Limbs that IPCs start with seem to not count as robotic for some reason.

**Comment by Davdichan** [comment]
To say they are broken again is to imply they ever worked as planned in the first place.

**Comment by Taaketa** [comment]
There must be more to this than replacing IPC limbs. I did it last night again for someone who had lost sll their limbs and the cyborg scanner registered all their parts as robotic. Rhey didn't suffer movement and came back later for repairs relating to low pressure.

**Comment by Crazylemon64** [comment]
Fun fact: The "Can attach hands without arms" bug applies to non-IPCs, too. But it's a hilarious, hard-to-abuse bug, so I'm not gonna bother fixing it.

**Comment by Davdichan** [comment]
New species in development. Rayman.

http://www.rayman-fanpage.de/rayman3_neu/grafik_rayman/rayman_1200.jpg

**Comment by Crazylemon64** [comment]
Fun fact, all `can_use` procs for all the surgery steps were never called. I'm fixing that now.
