### ISSUE TITLE
New chocolate walls make the turbine super useless

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5433]
**Problem Description**:
What is the problem?

Get the Turbine at a nice hot white gas temp. Rwalls just melt away. Making the turbine useless.

**What did you expect to happen**: 
Why do you think this is a bug?

Added feature, making other features useless... :(

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

New features shouldn't make other features obsolete.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Make a fire in the turbine room. Let it get nice and hot, watch the R-Walls melt and spread into the Turbine room and then into space.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by TheDZD** [comment]
I'm guessing Metastation *probably* has the same problem.
@FreeStylaLT

**Comment by FreeStylaLT** [comment]
This... can't be true, I specifically changed turbine/incinerator/toxin mixing walls to coated walls to _avoid_ this. Or do you mean the outer chamber that gets melted?

**Comment by FreeStylaLT** [comment]
Yeah, what are you on about?
![img](http://i.imgur.com/WjS15PE.png)
![img](http://i.imgur.com/w10yT9F.png)

**Comment by FreeStylaLT** [comment]
@TheDZD I coated Metastation rwalls (in Turbine and Toxin Mixing) as well in the wall-melting PR, they should be fine.

**Comment by Taaketa** [comment]
Yeah but when I make the chamber bigger. The outter walls above the containment area are not coated as fire proof.

**Comment by FlattestGuitar** [comment]
Well, you need to make them fireproof.

We can't make the whole station fireproof just because someone could set up a turbine there.

**Comment by FreeStylaLT** [comment]
Well, yeah.
![img](http://i.imgur.com/Bp0CT9F.png)
They're not coated because 
A) They're not in the actual burn chamber
B) Not all of them are reinforced, the ones on the right are regular plain walls.
If you want to make the chamber bigger, you'll have to upgrade and coat the walls surrounding it yourself.

**Comment by Taaketa** [comment]
How does one make them fire proof?

**Comment by FreeStylaLT** [comment]
You use two plasteel on a reinforced wall. That coats it.

Though, honestly, at the very least the entire burn chamber bit should be surrounded by reinforced walls. I will fix that.

**Comment by Taaketa** [comment]
@FlattestGuitar I wasn't suggesting making the whole station fire proof. So I suggest you leave your sarcasm elsewhere.

Regarding the original submission I will close it since the area above the burn chamber isn't intended on being used as a burn area.
