### ISSUE TITLE
Welded firelockers have no sprite

### ISSUE THREAD

**Issue by Wheatley29** [ParadiseSS13/Paradise#5439]
![image](https://cloud.githubusercontent.com/assets/20046182/17643211/c9f0ed04-615a-11e6-83ac-5bad87fa576e.png)

No need for the template as it's literally just the title. An industrial welder was used.

**Comment by TheDZD** [comment]
Where exactly is the welded firelock supposed to be in this screenshot?

**Comment by monster860** [comment]
@TheDZD He said "firelocker" not "firelock"

**Comment by TheDZD** [comment]
I apparently cannot read.
