### ISSUE TITLE
Ghosts and Proximity Sensors

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5443]
**Problem Description**:
Ghosts can trigger proximity sensors, much like the similar pervious issue regarding these, where a ghost could activate an infrared(https://github.com/ParadiseSS13/Paradise/issues/2978). Further investigation might also reveal more bugs with ghosts and such sensors(maybe voice activated ones also pick up).

**What did you expect to happen**: 
Nothing to happen when a ghost passes by.

**What happened instead**:
The proximity sensor picked up the ghost movement.

**Why is this bad/What are the consequences:**
It isn't working like it should. It could end up in accidents too.

**Steps to reproduce the problem**:
Be a ghost, put down a prox sensor with a signaler and an igniter and a signaler on the same frequency(reciever). Pass by it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I don't think it's game-mode dependent.

**Comment by taukausanake** [comment]
We need ghost prox sensors. Made by applying ektoplasma to a sensor. One step closer to being Ghostbusters
