### ISSUE TITLE
Away missions' corpse landmark is screwed

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#5449]
![img](http://i.imgur.com/TNjZq0b.png)
They're all naked greytide with no items. I also can't imagine any of my map tweaks having broken this, since I modified turfs only, I never touched objects or effects..

Landmark's typepath is /obj/effect/landmark/corpse

/modules/awaymissions/corpse.dm is the file. I am not entirely sure what's wrong there.

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

These worked, in the past.

**Comment by GeneralChaos81** [comment]
Looking at corpse.dm /obj/effect/landmark/corpse/ is supposed to be completely naked. You've got to select one of the subtypes under corpse to get any gear.
Maybe there could be random corpse selector(s)?

**Comment by Crazylemon64** [comment]
This is UO45, right? It's got the plain-old corpses, without any equipment selected.

**Comment by FreeStylaLT** [comment]
How long has it been this way?..

**Comment by Crazylemon64** [comment]
I don't remember them being any different - do you remember anything about them being anything other than naked greytiders?

**Comment by Crazylemon64** [comment]
Other away missions should have functional corpse landmarks, such as wildwest, or spaceBattle
