### ISSUE TITLE
IPC skeleton remains on hitting a Supermatter

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5456]
**Problem Description**:
IPCs upon touching a Supermatter turn into a skeleton, rather than robotic debris.

**What did you expect to happen**: 
IPCs turn in robotic debris.

**What happened instead**:
IPCs turn into skeleton remains.

**Why is this bad/What are the consequences:**
This breaks my imersioons.(No Consequences or bad in any way)

**Steps to reproduce the problem**:
Be IPC. Slam into Supermatter.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not relevant.

**Comment by Fox-McCloud** [comment]
And the most :snowflake: species of them all continues to demand :snowflake: exceptions.

**Comment by FlattestGuitar** [comment]
I'd like to point out dionea also have no bones but gain then on death.
