### ISSUE TITLE
Spacepod Ore Storage System does not Store

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#5466]
**Problem Description**:
Spacepod Ore Storage System does not Store

**What did you expect to happen**: 
I expected the Spacepod Ore Storage System to store ore

**What happened instead**:
The Spacepod Ore Storage System did not Store?

**Why is this bad/What are the consequences:**
It is a Spacepod Ore Storage System that does not ore storage system work.

**Steps to reproduce the problem**:
Get pod, get ores, inser Spacepod Ore Storage System, fly over ore and watch ore not being collected.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was attempting to collect ore with the Spacepod Ore Storage System, I guess the Enhanced Mining Laser System kinda mines oddly, like instead of a  neat 2 wide and what, 5 long, it varies between 2-3 making an uneven mining path, but thats not really a bug.

**Comment by Taaketa** [comment]
Doesn't ore storage need a crate in it?

**Comment by TullyBurnalot** [comment]
@TheDZD Not a bug, working as intended. System is just massively counter-intuitive and lacking in any sort of explanation.
