### ISSUE TITLE
Pai abilities

### ISSUE THREAD

**Issue by pazneria12** [ParadiseSS13/Paradise#5467]
**Problem Description**:
things like the Security Records and the Atmosphere sensor dont appear to work.
PS. The door jack thing takes a few clicks to make work

**What did you expect to happen**: 
Security Records: I expected to click on a name and have something appear as it looks like you can click on a name.
Atmosphere Sensor: To be able to see what is in the atmosphere
**What happened instead**:
Security records only showed me alphabetized names, and when I tried to click on a name nothing happened.
Atmosphere sensor: Always loading, nothing changed.

**Why is this bad/What are the consequences:**
Cant be very useful to security and I cant tell if there are toxins in the atmosphere to warn my host.

**Steps to reproduce the problem**:
Download security records and atmoshpere sensor, then try to use them.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
The entire system seemed a little slow to the uptake, like when I tried door jacking I had to spam click the button in order to actually start the hack.

**Comment by pazneria12** [comment]
Oh and also another thing, pai's cant examine things while collapsed.

**Comment by taukausanake** [comment]
I think while collapsed it might be intended because once you go into mobile form you can examine. As a handheld device you're only expected to look one way and that's if you have eyes while collapsed

**Comment by pazneria12** [comment]
but that kind of limits your ability to work as a pai

**Comment by taukausanake** [comment]
If you don't want to be in a mobile form then you're only limiting yourself

**Comment by pazneria12** [comment]
as a pai for a sec officer you should NOT have to follow them around ,your gonna get stolen

**Comment by taukausanake** [comment]
That's why they hold you in mobile form. It's not difficult

**Comment by pazneria12** [comment]
pai collapsed chasis can go in pda slot
and I dont think I can examine anything while held

**Comment by TheDZD** [comment]
I'm going to guess that the examine thing is intentional, given that nobody examine objects while inside of another objects (such as a mecha or spacepod). Everything else does seem like a bug though.

**Comment by pazneria12** [comment]
well its kind of a problem for pai's as when they examine people they have the option to set them to be arrested, limiting their usefulness to security if they cant examine a person.

**Comment by TheDZD** [comment]
pAIs aren't supposed to be able to set people to "Arrest" on sechuds though.

**Comment by pazneria12** [comment]
then there you have another bug, because Im fairly sure I could.

**Comment by taukausanake** [comment]
That sounds more like a feature than a bug. pAIs only have read access for any records they get. They aren't supposed to influence the round in any way, like pets pretty much. If you're playing a pAI then you're expected to be as useful as Ian

**Comment by pazneria12** [comment]
A pai Is supposed to be useful to the person, they arent just a pet?

**Comment by Dinarzad** [comment]
> What happened instead:
> Security records only showed me alphabetized names, and when I tried to click on a name nothing happened.

When you select a record to view, it displays at the very bottom of the page. 
Basicially each record, when viewed as a pAI is not it's own screen/page, but it changes what is displayed at the veeeeeeeeeeeeeery bottom, beneath ye olde list of names.
It's niot that it doesn't display, it's just designed unintuitively.

**Comment by pazneria12** [comment]
really? huh, didnt know that, thank you, so that specific part should be in a suggestion page.

**Comment by Aurorablade** [comment]
also if you are collapsed into card form..you cannot read the atmos around you if you are in a container.
