### ISSUE TITLE
Equipping Priorities should be looked at

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5470]
Right now, the biggest inconsistency is that PDA will prefer to equip to the ID slot rather than the PDA slot, which is rather annoying if you're trying to re-equip things quickly.

However there are some other equipping priority things that could be looked at. If you're wearing a toolbelt, pressing the equip button on a tool should make it go to the belt every time, rather than a pocket. Same goes with any item that CAN be equipped to a belt, it should attempt to go to the specialized belt before anything.

And speaking of belts, if you're not wearing one, it would be nice if items tried to avoid being equipped there, preferring to go in your bag first if possible. More of a QoL thing, since after you've been cloned, items can put in the belt slot and then you're stuck holding your belt in your hands like a jackass and have to fiddle around with it a bit.

**Comment by TheDZD** [comment]
These are all feature requests, although if anyone is interested, most of the relevant code for this is [here](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/mob.dm#L256-L287).
