### ISSUE TITLE
Limb icons do not fully overlay all the gory joints

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#5478]
As a result, people look a bit bloody around their joints when fully un-clothed - this is only visible when viewed from the side.

![fatvsslimfront](https://cloud.githubusercontent.com/assets/5661700/17761417/d622c66a-64bb-11e6-8268-63e6735faf3c.png)
![fatvsslimside](https://cloud.githubusercontent.com/assets/5661700/17761418/d6245f20-64bb-11e6-9c9c-ba5af7c877c0.png)

**Comment by LittleBigKid2000** [comment]
Also, Vulpkanin don't have gory joints at all.

**Comment by Fullofskittles** [comment]
> Also, Vulpkanin don't have gory joints at all.

Even if they did it probably wouldn't be noticeable seeing as how their body is essentially tinted whatever color players pick?

**Comment by KasparoVy** [comment]
The gorey joints are resolved by https://github.com/ParadiseSS13/Paradise/pull/5416
