### ISSUE TITLE
Tajaran's fat body icons are the same as slim

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#5481]
![fatvsslimfront](https://cloud.githubusercontent.com/assets/5661700/17761562/eff54f1c-64bc-11e6-9c09-73c722cc06f9.png)
![fatvsslimside](https://cloud.githubusercontent.com/assets/5661700/17761563/eff6afba-64bc-11e6-8e27-aac024a0d6ba.png)
Although they can be fat, the two icons are the same, and so they do not visibly change when naked.

**Comment by Fox-McCloud** [comment]
Should probably just remove the ability for Tajarans to be fat, to be honest.

**Comment by Crazylemon64** [comment]
But without fat tajarans, we'll never have the chance, when we have a plump Taj NT Rep, to complain about working for the Corporate Fat Cats!

**Comment by FalseIncarnate** [comment]
But how are we expected to RP  as Garfield if we can't have fat cats and lasagna?

![image](http://static1.fjcdn.com/comments/4460612+_6668cf6465368dfc37565ee5bdc4e69e.jpg)

**Comment by taukausanake** [comment]
Wait, you got a human to appear fat? Does that mean #5402 was fixed?

**Comment by Crazylemon64** [comment]
Yeah

**Comment by Allfd** [comment]
![Tajaran](https://media.giphy.com/media/zVN0OolkDHmbC/giphy.gif)
In game animation showing intended functioning.

**Comment by Dumbdumn5** [comment]
> Should probably just remove the ability for Tajarans to be fat, to be honest.

They may take our cooldowns, but they may never take out ability to be a fatass!

**Comment by taukausanake** [comment]
If anything Unathi shouldn't have fat forms but I wouldn't know the logic for that. I also forget if slimepeople have working fat icons

**Comment by Crazylemon64** [comment]
The only 3 races with the `CAN_BE_FAT` flag set are Humans, Tajaran, and Grey.

**Comment by KasparoVy** [comment]
Beats me if any sprites exist on any server for fat cats. No way I'm going to try my hand at making them as it'd take me ages and they wouldn't look right, haha.

**Comment by taukausanake** [comment]
I think I could make fat sprites for all the races. It shouldn't be hard, spriting is fun. There are just people who are way better than me so there's that

**Comment by Puckaboo2** [comment]
I'll work on fat kitties in an hour or so.
