### ISSUE TITLE
Medbay sleeper #1

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#549]
I tried to upgrade the uppermost sleeper yesterday with the RPE. Strangely, nothing happened, so I closed it to see if it'd been already upgraded, and the RPE reported that it contained nothing at all. 
I screwdriver crowbar'd it to upgrade it manually, and it didn't have any parts or even a circuit board. 
I'm not sure how to reproduce this, as I'm fairly certain it isn't always like that.

**Comment by Fishocalypse** [comment]
As little basis as I have, this issue happened once before to me too. It appears to also cause the sleepers to contain no chemicals for injection either from what I last remember.

**Comment by SirBloodBuske** [comment]
Might that sleepers instance

**Comment by Fox-McCloud** [comment]
going to close this--can be re-opened if anyone else hears of anything similar/further about this.

**Comment by orelbon** [comment]
@Fox-McCloud never closed this
