### ISSUE TITLE
The AI is Lucifer, it brings light to places it shouldn't be.

### ISSUE THREAD

**Issue by SomanBat** [ParadiseSS13/Paradise#5494]
**Problem Description**:
AI eye emits light as if it were the AI hologram.

**What did you expect to happen**: 
Expected not to have light in dark spots as AI

**What happened instead**:
I had light!

**Why is this bad/What are the consequences:**
Light spots will give away where the AI is looking, in dark rooms.  Also lets the AI light up areas that shouldn't be lit

**Steps to reproduce the problem**:
Be AI. Look in a camera covered, but dark area

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Might be included, I had camera lights toggled on at the time. The light emitted by the AI eye was outside the camera light area.

**Comment by mrturkeytoe** [comment]
Pretty sure it's a "Working As Intended(TM)" function of the camera lights.

**Comment by Fox-McCloud** [comment]
Yeah, uh, are you sure the camera lights weren't on? Yeah, I touched Malf AI, but I didn't touch anything related to the AI eye.
