### ISSUE TITLE
Fireproof Plasteel walls don't drop more plasteel

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5498]
**Problem Description**:
What is the problem?

Walls that are fireproofed require 2 plasteel, and 3 plasteel in total to make. However, when disassembled only drop 1 plasteel.

**What did you expect to happen**: 
Why do you think this is a bug?

Most deconstructed objects drop 1 of each material from each stage of construction. In the case of reinforced walls it is 1 plasteel, 2 rods and a sheet of metal.

It'd be nice if a fireproofed wall dropped one additional plasteel.

**Comment by Earthdivine** [comment]
I guess this would be a @FreeStylaLT thing.
