### ISSUE TITLE
cannot see the chat log

### ISSUE THREAD

**Issue by simo944** [ParadiseSS13/Paradise#5501]
**Problem Description**:
What is the problem? cant see the chat log

**What did you expect to happen**: 
Why do you think this is a bug? it was working before but its been a while since i logged in to paradise station

**What happened instead**:
How is what happened different from what you expected?
screenshot of the bug: http://prnt.sc/c7z7i4

**Why is this bad/What are the consequences:**
Why do you think this is an important issue? cant see ingame actions, ooc/ic chats or anything, it just gives me that uncompleted message

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
on log in, i tried relogging and clearing cache, still the same

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Krausus** [comment]
What version of Windows are you running?

**Comment by taukausanake** [comment]
That looks like XP. It's a Zune theme. Also, not to be rude or anything but is it possible that your resolution might be related? I mean that is a small screen

**Comment by Krausus** [comment]
Ah, if it's XP, we kinda... don't support it anymore. The chat log should *mostly* work, assuming Internet Explorer is updated to version 8 (you'll probably get an error upon connecting), but NanoUI interfaces will end up completely broken.

**Comment by simo944** [comment]
this is the only server on SS13 i have this problem on

**Comment by Krausus** [comment]
I'm pretty sure that, currently, only us and VG use the port of Goonchat (which is what's breaking your chat log). We're the only server that's made IE8-incompatible changes to NanoUI, though.

**Comment by simo944** [comment]
ill get IE8 and see what happens

**Comment by FlattestGuitar** [comment]
We simply don't support Windows XP anymore. I believe we dropped support only two days ago with a patch. This is unlikely to change.

**Comment by Krausus** [comment]
Well, we never *officially* dropped support, but NanoUI has received changes over time that weren't compatible with IE8. The recent change to Goonchat's highlighting causes an error message and breaks the highlighting feature, but the chat log is otherwise functional. The NanoUI problems will probably be a deal breaker, though.

And, yeah, it's a little late to go back and try to figure out what's causing problems and how to fix them. You may want to strongly consider upgrading to one of the four major Windows versions released in the past 9 years.

**Comment by simo944** [comment]
got IE8 and I can see the logs now, thanks for your help problem solved
