### ISSUE TITLE
Different internals box contents.

### ISSUE THREAD

**Issue by Faryaa** [ParadiseSS13/Paradise#5507]
Just a small idea: make the content of that box spawning in you backpack different content regarding your job and race:
- All security members would have their breathe masks replaced with security gasmask. Because why you even need to carry a facemask when your gasmask is superior in any way?
- IPCs would have 1 emergency welder and 1 cable coil stack instead of useless mask, airtank and injector.
- Plasmamen and voxes would have emergency versions of their respectful airtanks and masks inside the box. Or their tanks would just be filled with respectful gases.

**Comment by TheDZD** [comment]
Feature requests go on the forums, not the issue tracker.
