### ISSUE TITLE
Incinerator Walls need to be fire proofed

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5529]
**Problem Description**:
What is the problem?

Incinerator southern walls are not fire proofed.

I do believe it was mentioned before when the sprite for fire proofing was added. But I haven't seen a PR yet for it.

**Comment by Earthdivine** [comment]
@FreeStylaLT

**Comment by FreeStylaLT** [comment]
Been solved already in #5530
