### ISSUE TITLE
AI sat outter tiles are in space on tile update

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5533]
**Problem Description**:
What is the problem?

The AI sat maintenance access tiles are considered in space and when a floor tile is laid down. The tile updates with 0 atmosphere and acts as such.

**What did you expect to happen**: 
Why do you think this is a bug?

For it's atmosphere not to disappear.

**What happened instead**:
How is what happened different from what you expected?

Atmosphere to stay.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Not really important. Just annoying.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Lay floor tiles in the maintenance access around the AI sat. Watch the air magically disappear.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by FreeStylaLT** [comment]
Where exactly did you put down a tile?

**Comment by Taaketa** [comment]
Check the server now and have a look at the AI sat. You'll see it's surrounding maint access has frozen over.

**Comment by Earthdivine** [comment]
While its a good example of what this issue is about, please specify what Tile it was in for future reference when working to fix this problem.

**Comment by Ar3nn** [comment]
I think I see the problem here...

![img](http://image.prntscr.com/image/a63320e662e74d1aa0b80371807c3972.png)

**Comment by GeneralChaos81** [comment]
This is probably redundant from #5579

**Comment by FreeStylaLT** [comment]
I'll be fixing this in my proper AI Sat port.

**Comment by Markolie** [comment]
I think this can be closed @Fox-McCloud.

**Comment by Taaketa** [comment]
Closing
