### ISSUE TITLE
SERAPH Access

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#554]
Just spawned a Deathsquad and the leader didn't have access to the SERAPH mech. Is the SERAPH supposed to be an admin only mech now or did it's access get messed up? I tried to find the access vars to check but I didn't see any on it.

**Comment by Markolie** [comment]
Seraph access was previously limited to access_creed. It's access_cent_commander, which only the deathsquad officer in select equipment holds. The deathsquad never had access.

**Comment by Earthdivine** [comment]
Thought it was CC Officer only, though I wanted to still check as I recall DS using it in the past. Thanks!
