### ISSUE TITLE
pAI Medical Suite/Hud

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#555]
Might be intended but with the new nano ui you cannot do a host bioscan with the Medical Hud Module anymore.

**Comment by TheDZD** [comment]
Seems to have been an intentional change on Bay, I may attempt to recreate the old host bioscan, but no promises, as NanoUI is painful to work with.

**Comment by Aurorablade** [comment]
Not knowing the full breadth of the code API but logically working it in my head.  Maybe when the Suite is active have A) seperate button readin Host Bio Scan or B) when program  is downloaded have it somewhere on the main interface window (where you download everything else). However this is one of those 'works in my head but the code will disagree with me' moments.
