### ISSUE TITLE
Drone Integrity Can Fall Below 0%

### ISSUE THREAD

**Issue by TwistedAkai** [ParadiseSS13/Paradise#5550]
**Problem Description**:
During a round as a maintenance drone, after narrowly escaping some smashing, I noticed my System Integrity was -15%

**What did you expect to happen**: 
I was surprised to see Integrity below 0% on an otherwise functioning drone.

**What happened instead**:
I expected to see my Integrity was above 0%

**Why is this bad/What are the consequences:**
It's difficult for a drone to assess its actual condition if Integrity is inaccurate.

**Steps to reproduce the problem**:
Damage a drone severely, without killing it.
Check System Integrity in the Status info panel.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
The weapon of choice was a stun baton. If chickens and dogs can attack, they may have struck, too. There were no noodles, at least.
Integrity was shown in drone UI as "Bad".
I suspect this is because death occurs at -maxHealth, rather than 0.

**Comment by Fox-McCloud** [comment]
Pretty sure this isn't a bug. Humans and borgs also have negative health values.

**Comment by taukausanake** [comment]
If you're using a percentage value instead of solid numbers, and even with mobs you don't see those numbers, then you really should be dead when you reach 0%. I don't think I've seen below 0% before as a maint drone or more commonly as a diona nymph and I die in the vents a lot as those. It sounds like a bug

**Comment by Crazylemon64** [comment]
This is not a bug. https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/silicon/robot/drone/drone.dm#L211-L218

**Comment by Ar3nn** [comment]
@TwistedAkai That's the way cyborgs do it too.
