### ISSUE TITLE
Traitor-Panel Identity Theft objective unassignable

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#5555]
**Problem Description**:
The "Identity Theft" changeling objective is unable to be added or changed from it's current target.

**What did you expect to happen**: 
<s>Isn't it obvious?</s> The ancient elders of the clan of the Seventy-Two Leaf Clover revealed it to me in a dream whilst I rested atop the seventeenth slope of Mt. Ebott. I can tell nobody what was expected, or else my heart may explode.

**What happened instead**:
<s>These questions are really repetitive, aren't they?</s> I released a shriek from my seventy brood-mouths and burrowed deep into the nether realm, uncovering the dusk-artifacts left there by the ancient sentinels to the third reality, and using them to seal my enemies into the glyphicsphere.

Oh, and you get the debug message, "DEBUG: Invalid target for identity theft objective, cancelling"

**Why is this bad/What are the consequences:**
<s>Well, when a changeling gets the objective to absorb something it can't...</s> The very fabric of reality is rended apart by my descending march, causing holes in space-time itself, which are bad for my reputation.

**Steps to reproduce the problem**:
Try to assign a changeling the objective to steal anyone's identity in the traitor panel. Sorry, this is actually something that needs to not be sarcastic.

**Comment by tigercat2000** [comment]
#5555 :scream:
