### ISSUE TITLE
Spontaneous Appendicitis Event Can Target Appendix-less Mobs

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#5557]
**Problem Description**:
See title.

**What did you expect to happen**: 
For non-existent appendices not to get inflamed.

**What happened instead**:
They do.

**Why is this bad/What are the consequences:**
You need to give somebody an appendix, then remove it to fix it.

**Steps to reproduce the problem**:
Trigger appendicitis event repeatedly until somebody without an appendix gets it.

[Code for it is here.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/events/spontaneous_appendicitis.dm)

**Comment by Fox-McCloud** [comment]
@TheDZD obviously players should give said person an appendix, then yank it back out again to cure it.

The marvels of modern medicine!
