### ISSUE TITLE
The space ruins on Z-7 can end up reaching the area borders.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5558]
Space rock can go until the level cuts off.
Like this.
![](https://i.gyazo.com/5f3c97a8a79db411232b56204f0063a3.png)

The rock should end before the level cuts off, because otherwise we get spacepods and poor spacemen embedded in rock with no way to escape.

I'd post a relevant picture, but I didn't take the screenshot in time. It was pretty hilarious though.

**Comment by TheDZD** [comment]
@Crazylemon64

**Comment by pazneria12** [comment]
thats happened to me before, but I didnt realize how it happened.
