### ISSUE TITLE
Experimental Dissection surgery (Abductor) is broken

### ISSUE THREAD

**Issue by sothangel** [ParadiseSS13/Paradise#5562]
**Problem Description**:
The heart cannot be removed during the surgery, meaning it cannot progress.

**What did you expect to happen**: 
Following the steps shown should work and progress the surgery.

**What happened instead**:
Nothing happened on click. I neither shook them, or extracted anything.

**Why is this bad/What are the consequences:**
Abductors cannot gain any points at all.

**Steps to reproduce the problem**:
Follow the steps as detailed in the Dissection Guide on the Abductor Ship, get to step 9 and be unable to do anything.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
Cult gamemode, naturally occurring Abductor event. The agent was able to shake the patient awake, which I could not do as the Scientist. I was also unable to cancel surgery or repair them, so they had open wounds and couldn't be fixed by medical staff on station either.

**Comment by Fox-McCloud** [comment]
Already fixed--not patched.
