### ISSUE TITLE
Brainrot speech impediments never going away

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5574]
Even after you completely heal someone of brainrot, and get rid of all their brain damage, they still retain the stammering or muteness. I checked their SE's at Genetics just in case, they were completely clean. I also tried mending their brain at surgery even though the advanced scanner reported no brain damage, and I even tried removing their brain, putting it back in, and defibbing. Nothing I tried got rid of the problem.

**Comment by Fox-McCloud** [comment]
Probably fixed by https://github.com/ParadiseSS13/Paradise/pull/5576
