### ISSUE TITLE
Vending Machine multi-clicking

### ISSUE THREAD

**Issue by Necaladun** [ParadiseSS13/Paradise#558]
When you click "Vend" in any machine that you have to pay for (clicking to swipe your card) you can click multiple times before it processes, allowing you to buy more product than exists in the machine, putting it into a negative number

![](http://puu.sh/gvtzY/cc7e11fe02.png)

**Comment by Deanthelis** [comment]
Don't fix this! How will I ever get 7 Midori Tabako packets?
/cry
