### ISSUE TITLE
Examining a signpost as ghost creates runtime

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#5582]
**Problem Description**:
Examining the /obj/structure/signpost creates runtime:
[08:06:52] Runtime in code/game/atoms.dm,203: DEBUG: to_chat called with invalid message/target.
   Message: '(null)'
   Target: 'MY CHAR', /mob/dead/observer
   src: The salvation (/obj/structure/signpost)
   src.loc: Asteroid (39,215,7) (/turf/simulated/floor/plating/airless/asteroid)
   usr: MY CHAR (MY CKEY) (/mob/dead/observer)
   usr.loc: Asteroid (37,218,7) (/turf/simulated/floor/plating/airless/asteroid)

**What did you expect to happen**: 
I expected not to get a runtime.

**What happened instead**:
I got a runtime.

**Why is this bad/What are the consequences:**
Because runtimes are bad.

**Steps to reproduce the problem**:
Go to the listed co-ords and examine the signpost as a ghost.

**Possibly related stuff**
Logged on as a GA. Also recently joined the round. And Ely was nearby.

**Comment by Crazylemon64** [comment]
It's a null desc. #5584 Fixes this
