### ISSUE TITLE
When an Admin ghosts out of a body they can also kick the player out too

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5597]
**Problem Description**:
What is the problem?

If an admin is in possession of a body, for example an Alien Queen. They can trigger the dead players prompt for someone to join the body before they leave it. If a player is in the body at the time the admin is in it. The admin ghosts and it also kicks the player out.

I suspect this is the problem, but only experienced it once.

Steps to replicate:

1: Admin possesses antag body (Alien Queen for example)
2: Admin triggers the prompt to take over the body without ghosting themselves from the body yet.
3: Player joins the body. 
4: Admin ghosts when the player joins.
5: Player and Admin will be ghosted together. If done close enough to the trigger. Another player can take over the antag role.

**Comment by Spaghetti-bit** [comment]
This is not happening as described. Nor is this reproducible.
