### ISSUE TITLE
Improvised Shotgun Bug

### ISSUE THREAD

**Issue by PootisMan1559** [ParadiseSS13/Paradise#560]
So.. There is a bug with the improvised shotgun. If you get a cirular saw and use it on the shotgun while holding it, it goes off. It never runs out of ammo and you can spam it.

**Comment by Spacemanspark** [comment]
Holy shit don't fix this yet, I want to try this.

**Comment by Deanthelis** [comment]
Keep in mind it just shoot you in the face 80 times.

**Comment by Spacemanspark** [comment]
Yep.
