### ISSUE TITLE
Potential Bug cloning items when switching into broken hand.

### ISSUE THREAD

**Issue by Suthek** [ParadiseSS13/Paradise#562]
Scenario:
This I stumbled upon in a round when I broke my left hand. I had some gauze in the right hand, and tried switching it to the left hand to see if it was really broken. Screamed and dropped the item as it should, but the gauze in my right hand was still there in addition to the one that I dropped from the left hand, essentially cloning the gauze. It didn't seem to be a UI bug as I could move and store both pieces of bandages as I would have expected. I tried recreating this issue a few minutes later to be sure it wasn't lag-induced and it still happened. Didn't try it with other items, nor was able to reproduce lately due to lack of broken hands.

How to recreate: 
Have a broken (left?) hand, carry an item in the non-broken hand and transfer it into the broken hand by clicking on it with the broken hand selected as active hand.

What should happen:
Character should remove item from right hand, then scream and drop the item as it enters the left.

What is happening:
Character drops item, but retains a copy/clone of the item in the non-broken hand.

**Comment by Artorp** [comment]
A roll of guize is a stack (of 5?), maybe you just split the stack?

**Comment by Fox-McCloud** [comment]
Yeah, gauze are in stacks, just like ointment, trauma kits, burn kits, and nanopaste; it's very possible you just removed one from the stack.

If you can demonstrate there's 5 units in a stack, then...once you do your trick here, there's 5 more, lemme know.
