### ISSUE TITLE
Protolathe and the associated Construction Menu to it is freezing randomly

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5626]
**Problem Description**:
Protolathe construction promts seem to freeze any sort of construction in the protolathe.

**What did you expect to happen**: 
For the protolathe to construct the said item.

**What happened instead**:
When prompted to construct a micro-manipulator it instead froze and had to deconstruct the protolathe or main computer in order to reset it.

**Why is this bad/What are the consequences:**
Halts progress of science and data levels may be lost.

**Steps to reproduce the problem**:
Unknown, it seems to occur with machine parts more often,but that's probably not the case.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No.

**Comment by AndriiYukhymchak** [comment]
Some details. Another example of this happened when I tried to construct 10 super matter bins and my assistant inserted a stack of metal immediaterly before construction initiated

**Comment by Deanthelis** [comment]
If Lemon's latest PR does fix this, it will have been ~100 lines of code to fix one of the oldest bugs in SS13.

Nice.

**Comment by AffectedArc07** [comment]
Fixed since TGUIing it.
