### ISSUE TITLE
You don't need lungs to be alive

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#5632]
**Problem Description**:
Removal of lungs causes instantaneous death, but the victim can be defibbed and continue to be perfectly healthy.

**What did you expect to happen**: 
People without lungs would assumedly take oxy damage until killed

**What happened instead**:
The target immediately died, and, when revived, took no oxygen damage

**Why is this bad/What are the consequences:**
You can live without lungs

**Steps to reproduce the problem**
remove lungs
defib spaceman

**Comment by TheDZD** [comment]
Breathing should *probably* be tied to lungs at some point.

**Comment by tristan1333** [comment]
I could try linking it in the rework I'm working on it since it has few things based on lungs. I'm not familiar with organ code tho so... Yeah

**Comment by Fox-McCloud** [comment]
Breathing is tied to lungs now.
