### ISSUE TITLE
Changeling brainslug rising results in invisiblity and no movement.

### ISSUE THREAD

**Issue by Nisahu** [ParadiseSS13/Paradise#5635]
**Problem Description**:
Rising from a headslug egg caused gamebreaking issues including invisibility and lack of control.

**What did you expect to happen**: 
After laying eggs the headslug dies, and over the course of 4 minutes the eggs grow into a monkey with the original changeling's consciousness and abilities, gibbing the corpse in the process. 

**What happened instead**:
After laying the eggs the headslug dies, and over the course of 4 minutes the eggs... gib the corpse and become an invisible (to me, at least) entity incapable of movement.

**Why is this bad/What are the consequences:**
I literally cannot play the game.

**Steps to reproduce the problem**:
Be killed. Before death, activate regenerative stasis. After death, regenerate. Activate arm blade. Kill your killer. Grab them, get noticed by security. Activate last resort. Lay an egg in your killer's corpse. Get killed by security as a brainslug. Rise from the corpse in medbay. Notice that your are invisible and cannot move.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Changeling/traitor gamemode.

**Comment by Fox-McCloud** [comment]
This ability has been used quite a bit---haven't heard of any other reports of it. Goign to close it for now unless it occurs again.
