### ISSUE TITLE
Drask shouldn't passout in Cryotubes

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#5637]
**Problem Description**:
Drask are suppose to be immune to cold, cryotubes makes them pass out presumably because they are freezing cold. 

**What did you expect to happen**: 
The Drask stays awake being immune to any low temperatures, cryotubes were invented studying Drask per lore.

Drask should be able to stay conscious during cryotube use and get out whenever they want fully conscious.

**Comment by HugoLuman** [comment]
I'd actually planned on coding this, but didn't get around to it before the merge. Not sure how to do it, though

**Comment by Fox-McCloud** [comment]
Not a bug--sometimes things are done for balance reasons or to avoid snowflaking things everywhere (like IPCs)--to that end, this is very much intentional and not a bug.

**Comment by GelatinousGlob** [comment]
Ugh I hope you reconsider in the future, its hard enough to rp as a cold being when you are never actually cold except when mining and a basilisk shoots you 5 times.

I don't see how this would change their balance much at all, cryotubes already have auto-release. Drask also heal from breathing what amounts to frozen oxygen. Being able to hear while in a cryotube isn't going to be some super ability.
