### ISSUE TITLE
Laptops with Camera Card doesn't work

### ISSUE THREAD

**Issue by WhiteHusky** [ParadiseSS13/Paradise#5643]
**Problem Description**:
Can't use a laptop with a camera card to view camera feeds.

**What did you expect to happen**: 
Open up a laptop, camera monitor, see a list of cameras after selecting a key.

**What happened instead**:
No cameras were listed.

**Why is this bad/What are the consequences:**
Just a nuisance if you would like to monitor the cameras in a random location in the station.

**Steps to reproduce the problem**:
Get laptop (as a job who would normally get cameras, like security) with Camera Card, open Camera Monitor, connect with a key. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Seems to happen anytime.

**Comment by AffectedArc07** [comment]
We purged these
