### ISSUE TITLE
Problems with construction and deconstruction of bananium airlocks

### ISSUE THREAD

**Issue by tinfoiltophat** [ParadiseSS13/Paradise#5650]
![bugz](https://cloud.githubusercontent.com/assets/11893427/18407701/6f05641c-76de-11e6-97a4-3147125e5125.PNG)
![bugz2](https://cloud.githubusercontent.com/assets/11893427/18407705/6f2917d6-76de-11e6-9939-54fcfb1c4470.PNG)
![bugz3](https://cloud.githubusercontent.com/assets/11893427/18407704/6f265988-76de-11e6-842a-adf41317d932.PNG)
![bugz4](https://cloud.githubusercontent.com/assets/11893427/18407703/6f25dcc4-76de-11e6-9c47-9033d12d457e.PNG)
![bugz5](https://cloud.githubusercontent.com/assets/11893427/18407702/6f12fb5e-76de-11e6-8615-10621238930e.PNG)

**Problem Description**:Upon starting deconstruction of a bananium airlock that is already in existence(The clown office airlock usually), it becomes impossible to reassemble it until you get to the step at which you take the bananium plating off. If you attempt to reassemble the airlock before removing the plating, the last step does not create a new airlock. It says "You finish the airlock!", but does nothing. Then, when you put the plating back on, the new airlock assembly becomes invisible. You can still assemble it fully, and it will turn into a functional airlock, but it is an inconvenience.

**What did you expect to happen**: With most airlocks, one can simply start the re-construction process after unwrenching an airlock and moving it to the new desired location, but this is not the case for bananium airlocks. Also most airlocks tend to not be invisible during the construction process.

**Why is this bad/What are the consequences:** It is a major inconvenience while building or transporting bananium airlocks.

**Steps to reproduce the problem**:
1. Begin disassembling a bananium airlock. Cut all wires except the bolts, weld it shut, and crowbar out the circuit board.
2. Add the circuit board back in. Attempt to finish the airlock using a screwdriver. It should be impossible. Seen in First picture.
3. Crowbar circuit board out. 
4. Cut wires. 
5. Wrench off the floor
6. Weld plating off. Picture 2.
7. Re-add bananium. At this point, the airlock should become invisible. Picture 3.
8. Resecure with wrench. Picture 4.
9. Re-wire.
10. Add circuit board
11. Screwdriver. You now have a finished Bananium airlock that is visible. Picture 5.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I think the problem is because disassembling the airlock leads to a machine being created titled "Bananium Airlock Assembly", whereas assembling the airlock creates a door titled "clown Airlock Assembly".

**Comment by Kerroman** [comment]
I responded to Tinfoiltophat's mentorhelp to see if I could figure out what was up.  I had him try to reset power in the room and try various tools on the assembly before completely deconstructing and reconstructing it again.  I don't know at what step it turned invisible but I was able to right-click on the tile and see that there was, in fact, an invisible clown airlock assembly there.

**Comment by GeneralChaos81** [comment]
This is a problem with mime doors too. It's because a name/material type mismatch. Confirmed the issue, and fixed it pretty easily. PR coming soon.
