### ISSUE TITLE
Bans sometimes log admin's IC name instead of their ckey.

### ISSUE THREAD

**Issue by sasanek12** [ParadiseSS13/Paradise#5653]
**Problem Description**:
What is the problem?
Bans sometimes log IC name of admin's character instead of their ckey.
**What did you expect to happen**: 
Why do you think this is a bug?
Expected banning admin's ckey
**What happened instead**:
How is what happened different from what you expected?
Got their IC name instead.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Longer unban appeal processing time.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
No idea.

**Comment by FlattestGuitar** [comment]
10/10

I think we have a few notes attributed to the IC names of the people who the notes are on.

This shit is wild, I tell ye.
