### ISSUE TITLE
Doorbolts down when removing a door

### ISSUE THREAD

**Issue by RobBrown4PM** [ParadiseSS13/Paradise#566]
Not sure if this is a bug or not, but it seems silly to have.

When deconstructing an airlock door and everything is cut but the doorbolts you can still put the bolts down, meaning if you do so that door can't be removed. I adminhelped and they were as stumped as I was on it. 

The door bolts should not be able to engage if there is no power to the door, no?

**Comment by SamCroswell** [comment]
Working as intended. Door bolts can drop, but not be raised, when power is cut. To raise the bolts simply restore power to the door by mending the correct wires.

**Comment by RobBrown4PM** [comment]
Thank you for the insight, mate.
