### ISSUE TITLE
Assasinate objective covers SNPCs

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5663]
**Problem Description**:
The system can assign SNPCs from the gateway as assasinate targets.

**What did you expect to happen**: 
SNPCs to not be taken in consideration.

**What happened instead**:
Traitor got an SNPC as an objective to assassinate.

**Why is this bad/What are the consequences:**
It's not a crew member and a player to be considered for assassination objectives.

**Steps to reproduce the problem**:
The system must pick at random a SNPC while they are at availible at round start.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No.

**Comment by FlattestGuitar** [comment]
Wasn't this fixed?

**Comment by Qinexio** [comment]
Was it patched in yet?
