### ISSUE TITLE
Syndicate TOP SECRET folders spawned in my bag while I was arrested

### ISSUE THREAD

**Issue by CupcakesNHacksaws** [ParadiseSS13/Paradise#5667]
**Problem Description**:
Syndicate TOP SECRET Folder spawned in my bag while I was being brigged and searched by security, giving away my antag status when I was otherwise clean

**What did you expect to happen**: 
Should this only spawn in a bag at round start instead of mid-game? As for why it happened, from what I could gather a new antag entered the round and spawned with a folder. Their job was to steal another folder, and thus one was spawned in a currently active antag's bag; mine.

**What happened instead**:
I got the message (http://imgur.com/a/qW8XW) as I was being hauled away by security. I didn't think this could happen mid-round

**Why is this bad/What are the consequences:**
I'm sure this hasn't been a problem in the past, as I'm sure I just got entirely unlucky with being stuck with it at the wrong time and wrong place. But maybe this should only spawn at round start? Or new-spawns?

**Steps to reproduce the problem**:
It just occurred while I was being arrested by security.  I was already a syndicate agent with a theft objective and to escape alive

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. 
 
Nothing out of the ordinary, I was just doing regular traitor/clown things when it popped up and it spawned in my bag. I was currently cuffed when it happened.

**Comment by Regen1** [comment]
Not a bug, just damn unfortunate.

**Comment by FlattestGuitar** [comment]
That's really the only objective that spawns things on you that other people can easily discover.

I think it'd be fine if we just removed it for the sake of this not happening ever again.

**Comment by Necaladun** [comment]
Wow. That's...amazingly unfortunate. The timing is just hilarious.

Not a bug sure, but could be working better. I'd prefer not to remove it because this is one of the objectives that is quite different and interesting, imo.

**Comment by Fox-McCloud** [comment]
Not a bug at all, this is just...very unfortunate.
