### ISSUE TITLE
Able to Place Items Inside of Bags While They're in Closed Lockers

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#5668]
**Problem Description**:
What is the problem?

Being able to place items (in my case an ID card) into a bag while it's still inside of a closed locker.

**What did you expect to happen**: 
Why do you think this is a bug?
I expected to not be able to place my ID (or any object for that matter) into a bag that was inside of a closed locker, or that my bag interface would close when I lost access to the bag through either not being next to it or it being inside of a closed locker.

**What happened instead**:
How is what happened different from what you expected?

I was able to place my ID into the bag that was inside of a closed locker (that I had previously locked), and then was unable to get it back out after that.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

I had to get the CE to come by to open the locker for me to retrieve my ID. Had it not been a lockable locker, then it may have been less of an issue.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Open the bag's inventory.
2. Place bag into locker.
3. Close said locker.
4. Place item that you wish to potentially never get back into the bag
5. Be unable to get the item back

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

I believe the gamemode at the time was "vampire". Other than that, it was a normal round.

**Comment by jughu** [comment]
Locker code

**Comment by granodd** [comment]
If you mean the locker type, it was an engineering locker, but I was able to recreate this bug with every other locker as well.

**Comment by Bone-White** [comment]
This seems like only a problem with IDs, and only if you lock them.  Perhaps child containers within parent containers should check to see if the parent container is accessible at the point of deposit, and not simply relying on the container interface being open?

**Comment by Kyep** [comment]
Verified that this is still happening on the live server.

**Comment by Sirryan2002** [comment]
Confirmed no longer an issue
