### ISSUE TITLE
Maintfound stetchkin pistol ammo clip turned invinsible when reloading

### ISSUE THREAD

**Issue by jughu** [ParadiseSS13/Paradise#5672]
**Problem Description**:
The stetchkin you can find in maint ammo clip turns invinsible when reloading

**What did you expect to happen**: 
It would reload normally

**What happened instead**:
It only reloaded 1 bullet and the clip turned invinsible

**Why is this bad/What are the consequences:**
you will not be able to use the stetchkin

**Steps to reproduce the problem**:
1.find stetchkin in maint
2.examine it it will say theres 1 bullet
3.remove the clip and reload it with a 10mm box
4.it turns invinsible

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)** not gamemode related

**Comment by Fox-McCloud** [comment]
@FreeStylaLT
