### ISSUE TITLE
Crossbows deal no damage

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5674]
**Problem Description**:
Crossbow bolts don't embed in people nor even hit them.

**What did you expect to happen**: 
Crossbows can't deal any harm.

**What happened instead**:
Crossbows bolts don't do anything at all, powered or not.

**Why is this bad/What are the consequences:**
Crossbows become paperweight.

**Steps to reproduce the problem**:
Load crossbow with battery or not, and a makeshift bolt.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:The person who fired it wasn't an antag, but it's probably not relevant.

**Comment by Plotron** [comment]
That sounds familiar! I think it's not the first time crossbows are broken.
Anyway, I haven't seen this bug yet, but that's because I haven't seen any crossbows lately.

**Comment by taukausanake** [comment]
Isn't this still related to throw code? That stuff still doesn't work perfectly. Maybe the bolts are moving too fast or the latest fix wasn't applied to bolts

**Comment by Rumiluntti** [comment]
It appears that the bolts stop in front of their intended targets, not hitting them at all.

**Comment by Fox-McCloud** [comment]
duplicate https://github.com/ParadiseSS13/Paradise/issues/4589
