### ISSUE TITLE
R&D Console Hanging

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#5677]
Problem Description: R&D console hangs while trying to print an object from the protolathe.

What did you expect to happen: The protolathe to print out the object I select like it should.

What happened instead: The UI becomes stuck at "Processing, Please Wait..." forever.

Why is this bad/What are the consequences: You have to disconnect the monitor of the console to fix it. This resets R&D, so if you don't sync after every single item you print out, you lose progress. If you don't sync at all, you have to start entirely over. Now, I'm pretty fast, but going from straight 1's to the max possible levels takes at least fifteen minutes, assuming mining has already delivered. I've had blobs get much nastier than they should because the x-ray lasers I tried printing hung the console.

Steps to reproduce the problem: Print shit. There's no pattern, it's hung on everything from a Bluespace RPED to a plain Matter Bin to a Universal Suppressor. 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?): This happens in every gamemode. Literally all of them in rotation do it. Nothing weird goes on, because when I do R&D, people usually just leave me alone, so it's just me, pushing buttons and jamming things in the deconstructive analyzer. I would like to point out, however, that this bug has existed since I started playing on para 2 years or so ago, but it used to be rare. Now it occurs once a day, minimum. It's not just me, either. One guy got it twice in a row earlier in the week. He did the WHOLE process twice, just to have it die again, after having rebuilt R&D from the ground up because somebody blew the first one up.

**Comment by Fox-McCloud** [comment]
duplicate.

**Comment by Deanthelis** [comment]
If it's a duplicate, why is this still an issue?

**Comment by Crazylemon64** [comment]
@Deanthelis Because it hasn't been fixed yet. The issue this duplicated is #5626
