### ISSUE TITLE
Inconsistent frequency limits

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#5680]
**Problem Description**: A remote signaling device can have a max frequency of 160.1. On the other hand a PDA with a Signal Ace 2 cartridge, and with that a signaler system, can only go up to 148.9.

**What did you expect to happen**: To be able to trigger signalers of any frequency with my PDA.

**What happened instead**: Couldn't set the PDA high enough to match the signaler.

**Why is this bad/What are the consequences**: Inconsistent.

**Steps to reproduce the problem**: Set a signaler as high as you can. Try the same with a PDA with Signal Ace 2 cartridge installed. See that you can't.

**Possibly related stuff**: Maybe it's designed to be like this but I see it as an inconsistency. I didn't bother to check the lower limits or the signal code limits however.

**Comment by Taaketa** [comment]
I tgought thus was intended because PDA carts are design to be slightly less good version of their dedicated units.

**Comment by IcyV** [comment]
I might be mistaken but I'm fairly sure this is intended and not at all inconsistent.

**Comment by taukausanake** [comment]
Wasn't sure then but wanted to check. I'll wait for a maintainer to pop in either way
