### ISSUE TITLE
Chat not visible

### ISSUE THREAD

**Issue by Darkis95** [ParadiseSS13/Paradise#5686]
**Problem Description**:
When I start the game the chat window is blank (http://puu.sh/rctkD/27a6790f25.jpg). I can however see any announcements that are made (http://puu.sh/rctHB/d95b1f0c45.png). I can still join the game and play, but I see no chat.

**Possibly related stuff**:
I have updated IE to the latest update.

**Comment by Plotron** [comment]
Have you updated your BYOND? I heard the newest version broke Goonchat.

**Comment by Darkis95** [comment]
That was the problem, thanks.
