### ISSUE TITLE
Nuke ops implants cost zero tc

### ISSUE THREAD

**Issue by DarkPyrolord** [ParadiseSS13/Paradise#5688]
**Problem Description**:
Nuke ops implants (rebooter, reviver, xray) are free to buy.

**What did you expect to happen**: 
I expected to pay TC for the implants.

**What happened instead**:
Got them for free, when they should of costed TC.

**Why is this bad/What are the consequences:**
Well, quite obvious, free implants for nuke ops.

**Steps to reproduce the problem**:
Be a nuclear operative
Buy some implants
TC count doesn't go down

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Just a normal nuke ops round, no war declared.

**Comment by Plotron** [comment]
Seriously? Wow.

**Comment by IcyV** [comment]
Can confirm this is true. I've seen it a few times and have mentioned it, just haven't gotten around to poking at it.

**Comment by Taaketa** [comment]
Hidden boon to nukies.

**Comment by Plotron** [comment]
Implant sponsorship.

**Comment by Keilden** [comment]
Nukies are full of them Augs nowdays.
