### ISSUE TITLE
Asteroid is Hot. AGAIN.

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#569]
The old 'The asteroid is burning hot' bug is back. Nearly burnt to death twice because of it. It started in the northwestern-ish side of the asteroid and eventually covered all of it.

**Comment by TheDZD** [comment]
@Fox-McCloud 
At random points, parts of the asteroid will stop being -200C and suddenly jump up to 5000C+, despite there being no pressure. Making space cold likely had the side effect of also making it transfer heat despite a 0 kPa pressure.
I'm unsure of what's actually causing the heat spikes, but I assume it has to do with air being exposed to the vacuum of the asteroid and transferring heat to it, and then the air dissipating away, reducing the heat capacity to 0 and spiking up the temperature.

**Comment by Fox-McCloud** [comment]
Guessing this is probably fixed now that we have LINDA.
