### ISSUE TITLE
ATMs stay logged in, cannot logout. Passerby spaceman can steal all my money.

### ISSUE THREAD

**Issue by Psyentific** [ParadiseSS13/Paradise#5692]
**Problem Description**:
The spaceman cannot log out of an ATM.

**What did you expect to happen**: 
The player can click the Log Out button and he will log out of the ATM and the window will close.

**What happened instead**:
Log out button does nothing - it may or may not logout the spaceman, but if it does he is immediately auto-logged in again. Even if the spaceman closes the ATM window and walks away, he's still logged into the ATM.

**Why is this bad/What are the consequences:**
Essentially, anybody who clicks an ATM opens up their bank account to anybody else who clicks the ATM, forever. I've stolen all the Captain's money doing exactly this.

**Steps to reproduce the problem**:
Be Spaceman.
Go to ATM.
Click ATM.
Be automagically logged in to ATM.
Push Log Out button
Be not logged out.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Guessing it's either a problem with ATM autologin (ie logs you in again as soon as you log out), or it could be that the logout button just doesn't work.

**Comment by theColdflame** [comment]
you can put your ID in your backpack to work around this, but yeah, it's annoying

**Comment by Plotron** [comment]
Yeah, that should be fixed.
I think it's the autologin's fault, it was never adjusted for that possibility at the lowest level of authentication.

**Comment by taukausanake** [comment]
You should just remove auto login in my opinion. Or make logout actually do its thing with auto login working. It's not actually a benefit if it has a downside.

I need to stop wearing my ID when I go to an ATM. See if any accounts are open

**Comment by Aurorablade** [comment]
07:42:05] Runtime in ATM.dm,258: Cannot read null.associated_account_number
   proc name: Topic (/obj/machinery/atm/Topic)
   usr: Alexander Anderson (shadowx20x) (/mob/living/carbon/human)
   usr.loc: The floor (172,130,1) (/turf/simulated/floor/plasteel)
   src: Nanotrasen automatic teller ma... (/obj/machinery/atm)
   src.loc: the floor (172,130,1) (/turf/simulated/floor/plasteel)
   call stack:
   Nanotrasen automatic teller ma... (/obj/machinery/atm): Topic("src=%5B0x20083e3%5D_1780&choic...", /list (/list))
   ShadowX20X (/client): Topic("src=%5B0x20083e3%5D_1780&choic...", /list (/list), Nanotrasen automatic teller ma... (/obj/machinery/atm))

possible related runtime
