### ISSUE TITLE
Admin: Setting Identity Theft Objective doesn't work

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#5698]
**Problem Description**:
When a changeling has to get a new target, when they possess the assassinate and identity theft objectives, I am unable to edit the identity theft objective, or place a new one. The following debug pops up:
DEBUG: Runtime in code/datums/mind.dm,599: Invalid target for identity theft objective, cancelling

Besides being the previously mentioned assassination target, there is no visible reason for why they should be invalid.

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
I expected to be able to assign identity theft objectives.

**Why is this bad/What are the consequences:**
It then has to be replaced with another assassination, or steal, objective, which increases the work the antag now has to do.

**Steps to reproduce the problem**:
Open traitor panel, select antagonist. Modify desired objective, select identity theft. Select a target, get the debug message. Cancels the editing of the objective.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: For changelings.

**Comment by LittleBigKid2000** [comment]
#5555
