### ISSUE TITLE
HoS has a guide to faxes book in his locker

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#5700]
**Problem Description**:
The HoS' locker has a guide to faxes

**What did you expect to happen**: 
Only people with the ability to send CC faxes would have a guide to CC faxes

**What happened instead**:
The HoS' office had a guide to faxes despite the fax machine being restricted

**Why is this bad/What are the consequences:**
The guide is redundant.

**Steps to reproduce the problem**:
Open the HoS locker and look inside.

**Comment by FlattestGuitar** [comment]
I'd like to point out this makes the game absolutely unplayable.

**Comment by Plotron** [comment]
Muh immersions are RIP.

**Comment by Codingale** [comment]
The guide actually covers faxes in general, not just to CC. I say it'd be best for the guide to stay there as new HoS players would probably be clueless on how to send a proper fax, let alone one to Central Command.

**Comment by theColdflame** [comment]
it specifically refers to the usage of faxes to contract central command throughout, with no reference to internal usage of the machines

**Comment by Codingale** [comment]
![Fax Guide](https://cloud.githubusercontent.com/assets/6324853/18797624/ccf42b3a-819c-11e6-9cb8-a0b7fa08e463.png)

That for the most part is directed at CC, but could also be helpful for people who don't know what the fax machine is. If not it could be made more generic.. I think they should have a reference.

**Comment by Lady-Luck** [comment]
I think the Guide to Faxes should be removed from the rooms that no longer have a CC fax. I think every head has one.

**Comment by Lady-Luck** [comment]
@Fox-McCloud Needs to be reopened. The CMO, RD, and CE still have fax guides, though I believe those require a map edit to remove.
