### ISSUE TITLE
PanDemic bottles invisible.

### ISSUE THREAD

**Issue by AgentoChe** [ParadiseSS13/Paradise#5702]
**Problem Description**:
Well you cant see them, nor can you interact with them

**What did you expect to happen**: 
I expected to actually see the bottle?

**What happened instead**:
......

**Why is this bad/What are the consequences:**
I cannot add or remove symptoms

**Steps to reproduce the problem**:
Attempt to create a virus bottle

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Nothing special nornal virology

**Comment by Fox-McCloud** [comment]
Already fixed. Not patched.
