### ISSUE TITLE
Abductor console "retrieve" fuckup

### ISSUE THREAD

**Issue by AndriiYukhymchak** [ParadiseSS13/Paradise#5707]
**Problem Description**:
Console at some point stopped retrieveing anyone. No message no action

**What did you expect to happen**: 
specimen or agent to be retrieved when marked

**What happened instead**:
Noting happened. At some point the button even got misaligned

**Why is this bad/What are the consequences:**
It ruins the round for the abductor team completely

**Steps to reproduce the problem**:
No idea why that happened, but we had to buy new tool and we swapped the stunbaton with other team.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
it was abductor + sling and we lost our items at some point

**Comment by Fox-McCloud** [comment]
Duplicate issue--this has happened before. ISsue is, it's difficult to pin down why this is happening. There aren't any runtimes associated with it.
