### ISSUE TITLE
Xeno Surgery

### ISSUE THREAD

**Issue by 7Komrk** [ParadiseSS13/Paradise#5710]
**Problem Description**:
Surgery on Xenomorphs stops at a certain point, disallowing organ removal, among other things.

**What did you expect to happen**: 
Attempted on 2 separate dead xeno bodies, in 2 different locations. Expected each time to remove xeno oragans, or at least the xeno brain.

**What happened instead**:
Surgery stopped at different points for each person performing the surgery at the 2 different locations.
First attempt at Medbay, OR 1. Surgery could not progress beyond the Circular Saw stage.
Second attempt at Robotics. Surgery could not progress beyond the Retractor stage.

**Why is this bad/What are the consequences:**
It basicly nulls surgery on Xeno's completely. If surgery cannot be performed, then the xeno having harvestable organs is void.

**Steps to reproduce the problem**:
Killed xenomorphs.
Dragged to Medbay/Robotics surgery tables.
Took scalpel in hand and clicked on mob
Chose Organ Manipulation
Medbay: Aimed at chest, used circular saw, nothing after that could be used
Robotics: Aimed at Head, used circular Saw, used Retractor. Nothing after that could be used.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Other's did the surgeries, I stood by and watched. Afterwards, I attempted the same surgeries, and I couldn't even get past the scalpel stage (Any tool used, if used again, even another tool, automatically ended the surgery)

ADDED:
Alright, I went back and had Keroman help me with a surgery setup, a ton of xeno simplemobs, and player controlled xeno mobs, in the Test Area.
![26a4b9b6ff6c9bdb04831604127ba988](https://cloud.githubusercontent.com/assets/22424295/18814031/093aca14-82c3-11e6-811b-f511690f3c22.png)

We both tried the following steps: 
Drag Dead/Alive Xeno (Drone/Queen/Sentinal and Hunter tested) to surgery table.
Use (any) Tool on Xeno, click Alien Organ Manipulation
Use Saw, Use Scalpel, use Retractor.
Attempted to use Hemostat to remove (any) organ/object/brain from xeno. No message appeared at all.
Attempted to use hands/all other tools, No message appeared at all.

According to Sniper Fairy, who had been browsing the code:
![5d9dce6914 1](https://cloud.githubusercontent.com/assets/22424295/18814045/5f1116a0-82c3-11e6-9b21-4957bc30a130.png)
**_______________________________________________________________________________________**
![e3c87cbee5 1](https://cloud.githubusercontent.com/assets/22424295/18814052/76cf9226-82c3-11e6-9115-9e4726cbc017.png)
**_______________________________________________________________________________________**
![64c0390351 1](https://cloud.githubusercontent.com/assets/22424295/18814062/9d0ba1a0-82c3-11e6-8857-afc942e7cbb2.png)

**Comment by Kerroman** [comment]
Just to note the xenos I spawned in the test room (see the screenshot Komrk posted) were not simple mobs like the xenos produced by a gold slime core reaction.  They were the the same type you'd see during a xeno event.

**Comment by shazbot194** [comment]
After spending probably way too much time on this with little to no results, I have found out the exact reason its not working. The surgery itself uses the manipulate organs for normal humanoids which is coded to really only work with humans (ie humans, vox, slime people, ext), and not aliens. The other reason is there are several procs that the surgery uses that are not present in the alien code. I will try again to fix it after finals.

**Comment by shazbot194** [comment]
I hate myself, after looking over all the surgery code, I never noticed 

allowed_mob = list(/mob/living/carbon/alien/humanoid)

I think I can get a fix coming soon.
