### ISSUE TITLE
Hivelord Stabilizer Doesn't have a Sprite

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#5711]
**Problem Description**:
The Hivelord Stabilizer from Mining lacks a sprite

**What did you expect to happen**: 
I expected to be able to see the stabilizer upon vending, and other interactions with it.

**What happened instead**:
I don't get to see the stabilizer

**Why is this bad/What are the consequences:**
I can't use it if I put it in my backpack, nor can I see it.

**Steps to reproduce the problem**:
1. Collect enough mining points for stabilizer.
2. Vend Stabilizer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by Fox-McCloud** [comment]
@KasparoVy @IcyV 

Or was this fixed?

**Comment by IcyV** [comment]
@Fox-McCloud Definitely broken right now, just checked. I'll get something up for that soon.

**Comment by Fox-McCloud** [comment]
Alrighty, thanks @IcyV
