### ISSUE TITLE
Mindshield implants do bewildering things

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5718]
Getting mindshield implanted while you're a dirty traitor makes you lose your traitor status BUT you keep all your objectives, memories and everything else.

This has no effect for the player as far as I can tell, but makes administration problematic.

**Comment by Lady-Luck** [comment]
It also disintegrates the moment you remove it.

**Comment by Crazylemon64** [comment]
@Lady-Luck Did you have an implant case in-hand when removing the implant? If you don't, removed implants will simply disappear. And all implants are in the chest ever since #3273.

**Comment by Fox-McCloud** [comment]
@FlattestGuitar 

Uh, care to explain? Are the objectives and such disappearing from the traitor panel or something? It's not especially clear what you're describing as happening, here.

**Comment by FlattestGuitar** [comment]
From the perspective of the player, nothing really happens. 

The person implanted loses their traitor status and doesn't show up as a traitor on their Traitor Panel, as well as on the Check Antagonists list.

Everything else functions normally, I would assume.

**Comment by Fox-McCloud** [comment]
This must be Baycode's handling of the implants---since there (AFAIK), loyalty forces RP (they have since scrubbed loyalty implants, entirely, though).

**Comment by Kyep** [comment]
@FlattestGuitar I tested this today. In my testing, implanting a traitor with a mindshield implant did not stop them showing up in the Check Antags list, or as a traitor in the traitor panel.

**Comment by FlattestGuitar** [comment]
Really weird. I guess I'll open it again if something similar happens and I know exactly why.
