### ISSUE TITLE
Cluwned plasmamen will suffocate - the mask is not internals-enabled

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#5719]
**Problem Description**:
Cluwning plasmamen (and maybe Vox) permanently disables their internals.

**What did you expect to happen**: 
Normally a 'clown mask and wig' is internals-enabled, but cluwne's no-drop version is not.
I expected to be able to live a miserable life of a cluwne as a plasmaman, but no bueno!

**What happened instead**:
I started suffocating instantly, and weird things happened to my sprite, like lying down permanently or something. Nuts.

**Why is this bad/What are the consequences:**
Speciesism! I want more rights!
I want to cluwne all night.

**Steps to reproduce the problem**:
1. Be a plasmaman.
2. Get cluwned.
3. Be unable to use your tank as the mask is not internals-compatible.

**Comment by FlattestGuitar** [comment]
H0NK!

💀 🔥

**Comment by LittleBigKid2000** [comment]
Solution: Make cluwnes not have to breathe. So there's one less way to escape the misery.

**Comment by Fox-McCloud** [comment]
Pretty sure this intentional, to be honest--given how wizard, as a game mode, functions.

@TheDZD since you did this port.

**Comment by Plotron** [comment]
!FUN! feature, yay.

But what if someone gets cluwned via a fax or other adminbooze ways?

**Comment by TheDZD** [comment]
This is a bug. Cluwnes are meant to suffer.
