### ISSUE TITLE
Leg Day

### ISSUE THREAD

**Issue by AgentoChe** [ParadiseSS13/Paradise#5723]
**Problem Description**:
According to examine I have legs, however I do not according to body scanner. Game agress with body scanner

**What did you expect to happen**: 
To have my legs if examine doesnt tell me?

**What happened instead**:
I examined and it said I had legs when in fact I did not

**Why is this bad/What are the consequences:**
You cant cut the legs off to replace them but you dont have them so its stupid

**Steps to reproduce the problem**:
be in explosion radius. No clue what has exploded. Admin told me trip mine exploded( I walked on it). He also said nothing went wrong code wise

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
nope

**Comment by Crazylemon64** [comment]
This sounds irksome to reproduce - any further details? This is rather sparse to go off of.

**Comment by Rumiluntti** [comment]
Sounds like this one: https://github.com/ParadiseSS13/Paradise/issues/5675

**Comment by Sirryan2002** [comment]
poor information, sounds like a duplicate, going to go ahead and close this as its 5 years old at this point
