### ISSUE TITLE
Ion projectiles don't deal damage spacepods

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5726]
Fire an ion rifle/carbine or an EMP shell at a spacepod. It will deal no damage at all, which, I believe, used to happen.

Tell me if I'm wrong, I guess?

Low-effort bug report.

**Comment by mrturkeytoe** [comment]
Can conffirm, ion weapons are meant to damage space pods.

**Comment by Signmark** [comment]
Why, Dean Hall? WHY YOU LET IT HAPPEN?
