### ISSUE TITLE
Disposal Chutes

### ISSUE THREAD

**Issue by PipeWizard** [ParadiseSS13/Paradise#5728]
**Problem Description**:
Stepped into a disposal chute (not a disposal bin, one of the literal chutes you can print off from the pipe dispensor) and it froze my game entirely. Luckily I was still able to use OOC and AHelp, but not LOOC. I also couldn't step out of it nor could admins track my name. I BELIEVE that this happened because it was in a stage of deconstruction to be moved to a different area.

**What did you expect to happen**: 
I expected to just step back out of it or get launched out of it because it wasn't hooked up right.

**What happened instead**:
See Problem Description above for more detail. I got stuck in it entirely.

**Why is this bad/What are the consequences:**
This is an important issue because it deletes the item you had in your hands when you entered the half deconstructed disposal chute and it freezes your character.

**Steps to reproduce the problem**:
Step 1. Weld the Disposal Trunk pipe to make it not functionable.
Step 2. Screwdriver the Chute.
Step 3. Cut the wires with a wire cutter.
Step 4. Enter.
(That should be exactly what happened although my memory is weaker nowadays)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing was going on that was odd. I set this up earlier in the round no problem and it worked great! All of engineering even used it including Solatus. From my experiences working on bug fixing in the past, I recommend making the Chute unaccessable unless there is a Trunk that is completely set up. I do not believe this should be too difficult since there is already a system in place that checks for it when you try to place an item in the Chute.

**Comment by Fox-McCloud** [comment]
Sounds like you got thrown into nullspace or something.

**Comment by Scribblon** [comment]
I have been researching this bug:
When you go in like the bug report states the following happens to the area: areaMaster [0x40000cf] = /area/start 
Trying to reproduce this bug with a disposals bin will just blow the player out in a random direction.

**Comment by Citinited** [comment]
@Fox-McCloud I believe this has been fixed by one of my many PRs that fix disposals nullspace stuff

**Comment by AffectedArc07** [comment]
Deemed fixed. If this is still an issue, please re-open your issue report.
