### ISSUE TITLE
Guardians that got tossed out by their owner aren't respawnable

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5729]
a) join as a cheerful guardian
b) be LITERALLY THE WORST holoparasite
c) get booted by your host, replaced with another ghost
d) try to play as Renault/ERT/what have you
e) not do that stuff, beacuse "You've given up your right to respawn!"

**Comment by LittleBigKid2000** [comment]
Seems like this might be intentional

**Comment by Plotron** [comment]
I mean - why would it be intentional?

You die in a game, you get booted. You're either revived or come back as a pet/drone/whatever.
Your pAI self gets turned to rubbish - sure, feel free to try again.
You mess up as a xeno, you can try again.

It's the same effing thing, except in an antag role.

**Comment by LittleBigKid2000** [comment]
The reason why I think it _may_ be intentional is based on the code alone.

**Comment by Plotron** [comment]
Oh, that's interesting.

**Comment by Markolie** [comment]
This can be closed.

**Comment by Markolie** [comment]
This can be closed @Fox-McCloud @TheDZD
