### ISSUE TITLE
Detective Bullets ignore Sleeping Carp

### ISSUE THREAD

**Issue by ExitGame** [ParadiseSS13/Paradise#5736]
As title says, detective bullets just completely ignore sleeping carp, pls fix.

**Comment by FlattestGuitar** [comment]
Was the target on the floor by any chance? When you're on the floor you can't dodge the bullets.

**Comment by Fox-McCloud** [comment]
Same with hulk.

**Comment by ExitGame** [comment]
Not quite sure. I just remember that I got shot by the Detective's bullet while running away from them and then I got hit and stunned. So. I was just a normal guy with sleeping carp.

**Comment by ExitGame** [comment]
I'm just gonna go ahead and close this since it's appearently just a one-time thing or something, dunno.
