### ISSUE TITLE
Changeling blood reaction bug

### ISSUE THREAD

**Issue by jguy555** [ParadiseSS13/Paradise#574]
Kluys told me that to confirm a changeling you can mix his blood with welder fuel and if it reacts it is changeling blood. All blood reacted with the fuel, including my own. So then i tested blood from a confirmed changeling and their blood also reacted. Kluys told me this was a bug.

**Comment by Fox-McCloud** [comment]
Not a bug; have to pay attention to the message.

If it breaks apart, it's normal blood; if it's writhes and wiggles, then it's ling blood.
