### ISSUE TITLE
Clown target issues - Antag Notes

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5740]
**Problem Description**:
Apparently this bug is kind of old but no one seems to have issued it, everytime you get the clown as your target, you get their original name instead of their curent one due to the fact that they have to namechange.

**What did you expect to happen**: 
The clown's curent name to be displayed to the traitors objectives properly.

**What happened instead**:
The clowns original name was displayed instead.

**Why is this bad/What are the consequences:**
General confusion for people first getting this kind of objective.

**Steps to reproduce the problem**:
Get a clown, get a traitor, make the traitor have the clown to assasinate them at roundstart.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Well it's a problem with antag notes in general, nothing else, they can still complete their objective by killing the clown.

**Comment by Plotron** [comment]
Same with AI's name.
