### ISSUE TITLE
Xeno Organ Manipulation

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#5741]
**Problem Description**:
You can't remove organs from xenos. Or put them in, for that matter.

**What did you expect to happen**: 
I'd expect the Alien Organ Manipulation surgery to actually do something.

**What happened instead**:
After pulling a region (brain, torso, groin, whatever) open with the retractors, no surgical tool does anything except end the surgery.

**Why is this bad/What are the consequences:**
I can't borg dead xenos, which means dead xenos are out of the round forever.

**Steps to reproduce the problem**:
1. Kill a xenomorph that is not a simple mob.
2. Put it on a surgery table.
3. Target head with help intent.
4. Begin surgery with scalpel.
5. Use a saw.
6. Use a scalpel.
7. Use retractors.
8. Lament the rarity of actually winning against xenos and getting nothing but useless xenomeat out of it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

It was a Vampire round. It doesn't matter if this is a xeno made from xenomicrobes or a real xeno from the random event, it just doesn't work. I tried it on all castes, nothing.

**Comment by Plotron** [comment]
#5710
