### ISSUE TITLE
Goliath plates disappear when someone is inside mech.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#5746]
When you try to add goliath plates to someone inside of a mech the plate disappears from existenc and says 'You can't add armor onto the mech while someone is inside!',

Goliath plate shouldnt disappear from existence, it should stay in hand.

**Comment by LittleBigKid2000** [comment]
When it displays that message and the goliath plates were deleted, the damage absorption was still updated. So, it wasn't wasted.

**Comment by GelatinousGlob** [comment]
Oh okay, that is good, it is missing the sprite update then I think but that doesn't matter much.
