### ISSUE TITLE
Odd cryotube air leak bug

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#5747]
Got an odd bug, done it three times in a row now with different pipe layout but same hookup configuration. I hooked up a gas filter to filter oxygen off of supply and feed it to the cryo cells tank oxygen system and send nitrogen to waste. It seems to work at first however soon air alarms will be going off because uncooled oxygen from the filter starts spewing out of the cryotubes uncontrollably and for no reason. I know its filtered oxygen because it raises room oxygen content and pressure, however the room will stay a perfect 20C the entire time so it seems to somehow be bypassing the cooled oxygen piping straight to the cryocell where it is expelled into the room.

![atmosbug](https://cloud.githubusercontent.com/assets/14857758/19165081/7220388c-8bd0-11e6-9b96-e23326a3e598.jpg)

**Comment by LittleBigKid2000** [comment]
Cryo cells that are on leak air. Not sure if it's intentional.

**Comment by Plotron** [comment]
Maybe it's the same thing that makes plasmamen leave plasma in the air? Y'know, breathing? :D
It makes sense.

**Comment by GelatinousGlob** [comment]
Part of the problem is it wasnt a little air it was massive amounts of air that set off alarms and such. Also it was room temperature and not cold but maybe that is a feature.

I plan on doing some further testing later and see exactly how much of what is going where.

**Comment by DEATHRATTLERS** [comment]
Does that take air from the air mix and put oxygen in cryo and filter nitrogen back into scrubbers? If so that's a beautiful idea.

**Comment by GelatinousGlob** [comment]
Yes, that was the idea, but it spews out gas far too quickly from the cryotube. Ill likely test it some more sometime soon.
