### ISSUE TITLE
Ruin Z-Level entry issues from the eastern side of the Z-level

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5749]
**Problem Description**:
The eastern side of the zlevel is mostly covered in asteroid walls , near the border.

**What did you expect to happen**: 
It's more of a mapping issue, but people can enter from the eastern side and get stuck inside, this time it happened with a space pod.

**What happened instead**:
The person with the spacepod got stuck in the asteroid. It probably happens the same with mobs as well.

**Why is this bad/What are the consequences:**
People can get stuck in the asteroid by just changing zlevels.

**Steps to reproduce the problem**:
Enter through the eastern side of the space ruin zlevel, get stuck in asteroid.
This is the area I'm talking about:
http://puu.sh/rABCy/0332a18bc6.jpg
https://puu.sh/rABIp/38a4827764.jpg

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No.

**Comment by FlattestGuitar** [comment]
https://github.com/ParadiseSS13/Paradise/issues/5558

:)
