### ISSUE TITLE
Crematorium Ignores Lich Phylacteries

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#5751]
**Problem Description**:
Cremating a lich wizard ends the round.

**What did you expect to happen**: 
Have the opportunity to respawn at my phylactery like normal.

**What happened instead**:
The round ended.

**Why is this bad/What are the consequences:**
It completely nullified my entire wizard strategy because the crematorium doesn't care, apparently.

**Steps to reproduce the problem**:
Bind soul as a wizard.
Be cremated.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It was Wizard.
I was the Wizard.
I got cremated despite having an intact phylactery.
The round ended and I lost my shot at wiznerd.

**Comment by LittleBigKid2000** [comment]
>"A dark necromantic pact that can forever bind your soul to an item of your choosing. **So long as both your body and the item remain intact** and on the same plane you can revive from death, though the time between reincarnations grows steadily with use."

This might be intentional.

**Comment by Fox-McCloud** [comment]
This isn't a bug; this is intentionally how it works. If you can manage to destroy the **brain** of the lich before he respawns, then he will, indeed, be fully killed. If you destroy their marked object, they don't die instantly either; they just can't respawn from that point forward.

**Comment by Deanthelis** [comment]
This wasn't a bug report, it was an issue. It's a shitty mechanic and, thanks to three Wizard rounds in a row where lichdom was the theme, the meta now is just to beat them down and sprint to the crematorium. It's like the cursed heart, at this point; a waste of wizard points. It being worthless would explain why it's only two points, while Lesser Summon Guns is four for some reason.

In other words, I'm aware that this is how it works. I'm saying this entirely intentional feature is garbage, to the point that it's not even lichdom, by the definition of the term.

You'd think something from /tg/ would get the actual /tg/ part of it right, but I guess not.

**Comment by Fox-McCloud** [comment]
The github isn't the place for feature requests or posting about how much you dislike a mechanic--it's for bug reports--something like this is for the realm of the forums.
