### ISSUE TITLE
Power Gloves

### ISSUE THREAD

**Issue by Codydozer** [ParadiseSS13/Paradise#5757]
**Problem Description**:
Would not do anything at all.

**What did you expect to happen**: 
To fire an arc of electricity at someone

**What happened instead**:
Literally nothing.

**Why is this bad/What are the consequences:**
This is currently a waste of 10 TC and is not even useable.

**Steps to reproduce the problem**:
1) Buy Power Gloves. 2) Use over wire at something living. 3) Observe failure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Traitor round. Kyet confirmed they did nothing the next round as well.

**Comment by sasanek12** [comment]
You have to be on harm intent to use power gloves. Did you switch to harm intent before trying to use them?

**Comment by LittleBigKid2000** [comment]
Yep. Did some testing, it seems that they are, indeed, not working.

**Comment by Plotron** [comment]
Gloves of...
the Power Of Failure. Ha-ha!

**Comment by Fox-McCloud** [comment]
@TheDZD

**Comment by Taaketa** [comment]
Aren't power gloves also connected to the amount of power in the station grid? If there is none, then they do nothing. If there is little they do very little damage.

**Comment by Fox-McCloud** [comment]
Definitely not a bug. Just tested these; they work 100% fine.

Stand over a wire and middle click on a living mob---ta-da, they get zapped.

**Comment by LittleBigKid2000** [comment]
Maybe they need to be more intuitive or explained. Maybe some text explaining how to use them when examined by an antagonist. Sort of like the text in the examine tab that no one ever looks at.

**Comment by TheDZD** [comment]
When an antag examines one, it does say that you need to be standing over a wire to zap someone with it. That said, probably should say it does so on middle-mouse/alt click.
