### ISSUE TITLE
Slime People and Dionae Bug

### ISSUE THREAD

**Issue by HUNK1** [ParadiseSS13/Paradise#576]
Slime people is simple not working in game, When you change to Dionae, it shows a sprite of a Tajaran with Dionae leafs.

**Comment by Markolie** [comment]
This just happens in the preview (setup character) screen.

**Comment by HUNK1** [comment]
But the slime people bug remains

Date: Mon, 16 Mar 2015 10:57:21 -0700

**Comment by tigercat2000** [comment]
What exactly is the `slime person bug`? What is broken with them? What do you mean by 'they are not working in game'?

**Comment by HUNK1** [comment]
The sprite is broken, You spawn with a Human Sprite instead of a slime one.

Date: Mon, 16 Mar 2015 19:13:26 -0700

**Comment by tigercat2000** [comment]
Ahah. I see. I believe this is a SQL database-related bug from #548.
It should resolve itself if you select a new slime color and save setup.
