### ISSUE TITLE
Exosuits take absolutely no damage from projectiles.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5761]
As the title says. Guess I'm not that bad of a wizard, it's just the bugs! It's always the bugs.

**Comment by TheDZD** [comment]
Would help if you specified exactly which projectiles aren't affecting mechas, as I don't think they are immune to *all* projectiles.

**Comment by FlattestGuitar** [comment]
I haven't tested every single projectile, but neither regular bullets nor laser guns actually did anything.

**Comment by sothangel** [comment]
I tried shooting a Ripley mech with the humble energy gun, dinnae do any damage.

**Comment by Fox-McCloud** [comment]
Also, which exosuit was it?

**Comment by Plotron** [comment]
At the very least, there's insufficient visual confirmation.

Previously, 'mechs would spark when hit by ranged weaponry.
