### ISSUE TITLE
Traitor Robots/AI lose status upon relogging.

### ISSUE THREAD

**Issue by lordpidey** [ParadiseSS13/Paradise#5765]
**Problem Description**:
Traitor cyborgs/robots/AIs lose traitor status when closing/reopening the client, or using the reconnect issue.

**What did you expect to happen**: 
Traitor status should persist.

**What happened instead**:
Upon relogging, you recieve the message "You have been turned into a robot! You are no longer a traitor."  Traitor status is also removed from the traitor panel.

**Why is this bad/What are the consequences:**
It can potentially remove antagonists from a round.

**Steps to reproduce the problem**:
Be a robot or an AI.  Use traitor panel to turn robot into a traitor.  File->Reconnect.   Look at text box.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**  It will happen naturally in any round that can cause robots to be traitors, or if an admin uses the traitor panel to force a robot/AI to be a traitor.
Introduced in #5752

**Comment by Markolie** [comment]
Mhm, that's something I hadn't thought of. Will fix ASAP.
