### ISSUE TITLE
Prevent Escape Alive Objective doesn't work when target is off station Z level

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5767]
**Problem Description**:
What is the problem?

I was someone's target as the Mechanic. I had buggered off to the DJ sat for the rest of the shift and was listening to the radio comms patiently waiting for the end of shift.

Saw a Traitor had the "Prevent Derrick Bloise from Escaping Alive" objective. I never left the DJ Station and was off the station Z level. The Objective came up as failed for the traitor.

**What did you expect to happen**: 
Why do you think this is a bug?

Since I did not escape on a pod or shuttle. The Traitor should've succeeded.

**What happened instead**:
How is what happened different from what you expected?

The objective should've been completed. I have seen it happen before where I was trapped on the Russian Station and the Traitor was able to greentext.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

People who clear off into space and make no effort to return to the station for the escape shuttle. Should be considered a successful target for the Traitor. It is already a difficult objective for a traitor when their target is someone who can be off station, like a mechanic, miner or someone who was fortunate enough to get Gateway explorer.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Traitor has prevent X escape alive. Have target off station and not on shuttle means objective completed.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Crazylemon64** [comment]
It's been a while, and the related code has been changed. Re-open if this is still an issue

**Comment by Taaketa** [comment]
@crazylemon64 Should I close this? I haven't been able to test it.

**Comment by Taaketa** [comment]
Old bug. Not confirmed fixed but closing anyway.
