### ISSUE TITLE
Spawning map-templates containing nudged objs breaks movement

### ISSUE THREAD

**Issue by Fruerlund** [ParadiseSS13/Paradise#5769]
**Problem Description**:
What is the problem?
Whenever I spawn a template that contains any nudged objectives on a server, movement breaks.

**What did you expect to happen**: 
Why do you think this is a bug?
Can break movement unintentionally.

**What happened instead**:
How is what happened different from what you expected?
Had three identical templates, one containing an APC (default placed not nudged), one without a APC and one containing a APC nudged to sit perfectly on a wall.

First two templates, works fine. Spawn as many as you like, third template containing the nudged APC breaks movement as soon as it is spawned. Tested with other objs such as a newscaster.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Bads

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
See what happened instead.

**Comment by Markolie** [comment]
With nudged, do you mean APC's with their step_x or step_y variable set? If so, those indeed break the movement on the server; you can not use those. Use pixel_x/pixel_y instead.

**Comment by Fruerlund** [comment]
Ive come to realize that nudging objs seems to set step y/x as you say, just a giant misunderstanding from my side.
