### ISSUE TITLE
Xenos Gamemode Bugs/Issues

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#577]
### Bugs
- Xenos cannot control their own shuttle, meaning they cannot get to the station.
- Xenos die from the cold in space.

### Balance/Player Issues
- Without space move, xenos will often just space themselves when leaving the shuttle. Granted, this is the player's own mistake, it tends to ruin the entire round.
- The hunter's pounce and the general xeno ability to permanently floor people simply makes fighting xenos frustratingly difficult, even with laser weaponry, they can easily close the distance and disarm you, or simply use pounce.

The first two frankly just need to be fixed for the gamemode to work, while the second two issues have to be discussed before any change is made.

**Comment by Earthdivine** [comment]
Every Xeno has a ranged stun, and the inability to prevent it at all is whats a big problem with Xenos in general. From Hunter jumps to a Queens Neurotoxin, a single Xeno shouldn't be able to murder a whole armed crew. 

For example, we had a round with Xenos fairly recently where the two starting hunters were new to xenos and the hive SHOULD have been wiped. But the Queen faught off security and the ERT and impregnated them all. It's silly that the Queen, the one whos not supposed to see combat, could kill them all just by being clever with resin walls and Neurotoxin, much less any antag able to do so.

**Comment by Spacemanspark** [comment]
Why we ever thought that the ranged stun was a good idea is a little beyond me. Spam able, too.
Take a page out of CM's book and have them freeze for about two or three seconds after successfully stunning someone.

**Comment by TheDZD** [comment]
Should be fixed by #609.
