### ISSUE TITLE
invisible bottles

### ISSUE THREAD

**Issue by trexter555** [ParadiseSS13/Paradise#5770]
**Problem Description**:
What is the problem?
botany fertilizer/virology culture bottles are invisible
**What did you expect to happen**: 
Why do you think this is a bug?
how can bottles be real if our eyes arent real
**What happened instead**:
How is what happened different from what you expected?
bottles are supposed to be visible
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
other than not being able to click on it, using chameleon projector makes you completely invis
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
get a bottle from botany vendor or make a virus culture bottle

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

n/a

**Comment by Fox-McCloud** [comment]
fixed, but we haven't patched.
