### ISSUE TITLE
Karma system hyperabuse ,oh noes.

### ISSUE THREAD

**Issue by Ratvar** [ParadiseSS13/Paradise#5775]
Hi,L0rd_english there,first time doing something with git.
**Problem Description**:
Eh,you can check all mobs on same zlevel ingame with "Award karma" button,like,for corticals,blobhivemind or aliens in biohazard event,or for nukies after then dock,or for shadowlings after some minute after round start,or if someone have someone else card and such.

**What did you expect to happen**: 
I expect to have only "Award karma to player" button that only checks mob around you when i am alive,and get "Award Karma" as alternative as ghost and such and only,or something nearby.

**What happened instead**:
I have button to check all mobs on same zlevel ingame to check events and gamemodes.No photo of this cause "mah round icy ocy"

**Why is this bad/What are the consequences:**
Sasanek12 said that this is a bug,than told it "halfbug",then left,while other admins and he himself before he left encourage me write this github it even if i lazyskreek. Consequences is mah abuse, "WE HAVE BLUBS!","Nah,this is just corticals.","time to prepare for nukie!".You can check freaking gamemods and events.

**Steps to reproduce the problem**:
Click "Award karma" in karma menu,done,YOU NOW KARRRRMA SYSTEM ABUSER,PREPARE FOR CONSEQUENSES (and ERP).

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I love cheese.Also sorry for language,i kinda russian ,et cetera.

**Comment by Markolie** [comment]
Were you a ghost at the time? Ghosts are able to see all antagonists on the karma list, in-game players can only see crew antags (so traitors and such, so they can't use that to metagame).

**Comment by Markolie** [comment]
In that case it should be fine - ghosts should be able to see all antags on the list.

**Comment by Ratvar** [comment]
I was alive.Alive.

**Comment by Ratvar** [comment]
I was not a ghost,i was alive,i still alive,and we checked it with admins that i can see things as aliums on same zlevel,and in past round i told them number of cortical borer

**Comment by Markolie** [comment]
Ah, my bad. This is indeed a bug then. Thanks for reporting it.

**Comment by Twinmold93** [comment]
As far as I'm aware, that's how it was coded originally, so if you WANTED to give karma to someone who isn't around you (say, end round and they died on the station, but you wanted to give them karma for doing an awesome job investigating your claim earlier), you can. It's left to the player not to use the knowledge they get from that at all, and use of said knowledge is a violation of the rules as is. They're really only going to even get that knowledge if they specifically look for the keywords of those antags, too, and more likely to just ignore it on a cursory look for the person they want to give karma to.

**Comment by KasparoVy** [comment]
I think a good way to resolve this would be to have the check for valid karma recipients be the following:

1. People you can see at the time of clicking 'award karma' who happen to be antagonists (could possibly classify antagonists as 'obvious' or 'stealthy', and only do this for the 'obvious' ones while treating 'stealthy' antagonists as regular crew-- see below.)
2. People who are not antags (regardless of where they are and if you've seen them.)
3. Simple (non-game-mode) mobs (regardless of where they are and if you've seen them.)

Yes there would still be an aspect of meta to it, but it would be significantly reduced.

**Comment by xProlithium** [comment]
This is still an issue as of the time of this reply. Please fix, can still provide meta knowledge to the current round.

**Comment by Groudonmaster** [comment]
I've reviewed all the karma related PRs and can't find anything that particularly points to this issue except for #1803 Which is older than when this was originally opened and #18375 which explicitly says that it should remove at the very least Dsquad members from the list and reviewing the file it changes it should also apply to other antag roles.

I can't really confirm this in game unless I get really lucky with a list opening but so long as the surrounding code works the way it should this issue should be resolved by those PRs?

**Comment by Contrabang** [comment]
Karma is gone #20628
