### ISSUE TITLE
CMO office lacks an APC

### ISSUE THREAD

**Issue by AndriiYukhymchak** [ParadiseSS13/Paradise#5776]
**Problem Description**:
Round starts without APC in CMO's office

**What did you expect to happen**: 
APC is in the office, powering the room, situated above eastern door.

**What happened instead**:
CMO's office has no APC and no terminal, how ever wire knot is there

**Why is this bad/What are the consequences:**
CMO doors are not powered and can be easily crowbared into. Some minor issues since computers inside are kinda useful.

**Steps to reproduce the problem**:
Start the round, hear screams from CMO, check the CMO office with crowbar

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Happened THIS round, not sure if it will happen again, but I heard that it already happened to someone else

**Comment by Earthdivine** [comment]
#5774 fixes it.

**Comment by Anticept** [comment]
Server room to the right also lacks an APC, interrogation lacks an APC or wiring problem, and firing range is miswired.

**Comment by Markolie** [comment]
This can be closed @Fox-McCloud
