### ISSUE TITLE
Voxxybible

### ISSUE THREAD

**Issue by Ratvar** [ParadiseSS13/Paradise#5784]
**Problem Description**:
Voxchaplans joining on shuttle with pockettanker spawns without bible

**What did you expect to happen**: 
Mah bible

**What happened instead**:
No bible,but menu of name ans spritechoose for bible opened

**Why is this bad/What are the consequences:**
MAH BIBLE,free box slot from start,may be usefull

**Steps to reproduce the problem**:
Join as voxchaplan after round start with pockettanker,may work with big tanker,badam

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode was RPmeteor ops:electric boogalo 3 confirmed.I was scratching my back.My chair rotated IRL in this time,spoopy.

**Comment by Mitchs98** [comment]
Found out the hard way this was fixed >.>.
