### ISSUE TITLE
Ghosts VS slings :War Cometh.

### ISSUE THREAD

**Issue by Ratvar** [ParadiseSS13/Paradise#5786]
**Problem Description**:
You can BOO lights shadowling will veil some second next.They will BOO right back into light state,and stay lightey.

**What did you expect to happen**: 
Nothing that can shit shadowling as ghost

**What happened instead**:
Something spoopy

**Why is this bad/What are the consequences:**
You can deflect all shadowwork with one shitty observer (and i just done it once,horray),or even with AI,if their lighttoggle_on_click also blink this way

**Steps to reproduce the problem**:
Be ghost,BOO light,shadowling VEIL while it BOOed-light BOO into light again

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I love cheese.

**Comment by taukausanake** [comment]
I wasn't aware you could BOO lights on. I've only ever seen them toggled when on not off. Seems like an issue but don't shadowlings normally break all the lights too? The smart ones at least, even xenos

**Comment by Ratvar** [comment]
Eh,shadows can try to attack surgery fast to save dethralled one and attack security around,or SMART nonshadowlings may build lights into glass layers.So.Ye.They cannot always focus on light smash.

**Comment by Scribblon** [comment]
I also noticed turning the lights on and off again on an APC will also reset the lights.

**Comment by Sirryan2002** [comment]
Shadowlings have since been removed, this is no longer an issue.
