### ISSUE TITLE
Attacking Xenobio slimes results in SSD attack logs

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#5789]
**Problem Description**:
Attacking a slime that was brought to sentience by xenobiology results in SSD attack logs.

**What did you expect to happen**: 
Not to get attack logs labeling slimes being actively controlled as SSD

**What happened instead**:
Attack logs of active slimes listing them as SSD

**Why is this bad/What are the consequences:**
It is misleading and has brought more than one PM back asking if the slime was actually SSD

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
@FlattestGuitar @Kyep

**Comment by Kyep** [comment]
@Fox-McCloud @LightFire53 
Either this isn't a real bug, it was a real bug but was already fixed, or it only happens under more specific/rare conditions.

I attempted to reproduce this today, using every type of slime mob, and not a single one triggered this bug.

I looked at some attack_log vars, too, but did not see it there either.
