### ISSUE TITLE
Serverroom in Science is powerless.

### ISSUE THREAD

**Issue by BiberDark** [ParadiseSS13/Paradise#5796]
**Problem Description**:
Mapproblem : Computers and the door in the Serverroom do not work.

**What did you expect to happen**: 
They should work.

**What happened instead**:
No Power from the apc in that room. Only the left side has power.

**Why is this bad/What are the consequences:**
You cant use them.

**Steps to reproduce the problem**:
Start the game.

**Comment by BiberDark** [comment]
CMO Office too   + Interrogation

**Comment by GelatinousGlob** [comment]
That would explain the air alarms from the server room I kept getting.

**Comment by Markolie** [comment]
This will be fixed next patch.

**Comment by Anticept** [comment]
Firing range is missing a tiny piece of wire as well.
