### ISSUE TITLE
Examining Mining Jetpack Gives No Description

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#5800]
**Problem Description**:
When you examine the mining jetpack from the mining vendor, it gives no description of the item.

**What did you expect to happen**: 
Player who reported it expected to get the description of said item.

**What happened instead**:
When tested by me on live along with the player, no description appeared. Not even the tag for the item's name.

**Why is this bad/What are the consequences:**
Can't examine said item...

**Steps to reproduce the problem**:
Attempt to examine mining jetpack.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Runtime logs to help pin-point error:
[13:36:34] Runtime in code/game/objects/items/weapons/tanks/tanks.dm,86: DEBUG: to_chat called with invalid message/target.
   Message: '<span class='notice'>It's <img class='icon jetpack-mining' src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAM1BMVEXAwMB/Xwqjfxw6IxR0VSdAQECmeTdUVFSZCiZ6BBxcW1twLph8L6qWPco0NDT/ADMpKSm7FWGcAAAAAXRSTlMAQObYZgAAAGR6VFh0RGVzY3JpcHRpb24AAHicU1ZwcnX39FNw8fXkKkstKs7Mz1OwVTDRM+DiLM9MKckAcoyNuDgzUjPTM0ognOKSxJJUIFNJiYszJbOoGMg05OJMK0rMTYWwlRVc/VzAJgIAmrcYC32rgUMAAACQSURBVDiN7ZHJDoMwDERZYqbYxPD/X1tDUqnYhFvVC3OIRsnTxEvXPfLqh+i+NZq8O7+nZPdEHxeANE1pJFNxDQCvGbcAmxqALDkvsn9RXAQkZxE1FddI0HXT+wTwzxLqeJRZ68gcwB5gH+GBUEMNVm3t4lgymIhxvW4rg1AAUCigEtaMvR7mWoT9hO/w33oDshwIPBkdXUoAAAAASUVORK5CYII='>the mining jetpack! If you want any more information you'll need to get closer.</span>'
   Target: '0'
   src: The mining jetpack (/obj/item/weapon/tank/jetpack/carbondioxide/mining)
   src.loc: The floor (168,72,5) (/turf/simulated/floor/plasteel)
   usr: Patrick Allen (twinmold) (/mob/dead/observer)
   usr.loc: The floor (168,72,5) (/turf/simulated/floor/plasteel)

The actual issue appears to be that the distance calculations are wrong for whatever reason, regardless of distance for the item.

**Comment by Markolie** [comment]
Thanks for providing the runtime. This makes it extremely easy to fix.
