### ISSUE TITLE
Someone Cryoing has a chance to turn everyone into a mime

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#5802]
Or it breaks say/emotes with runtime. Work around:Screwdriver cryo open and shut...

Runtimes happening are as follows:

[06:23:34] Runtime in login.dm,61: list index out of bounds
   Caught by process: machinery

06:23:35] Runtime in game.dm,212: Cannot read null.toggles
   proc name: get mobs in radio ranges (/proc/get_mobs_in_radio_ranges)
   src: null
   call stack:
   get mobs in radio ranges(/list (/list))
   Broadcast Message(/datum/radio_frequency (/datum/radio_frequency), The Dungeon Master (/mob/living/silicon/ai), 0, "says", the AI subspace transceiver (/obj/item/device/radio/headset/heads/ai_integrated), "Tio Holtzman (Librarian) has e...", "The Dungeon Master", "AI", "The Dungeon Master", "synthesized voice", null, 0, /list (/list), 1459, "states", null, null)
   Subspace Broadcaster (/obj/machinery/telecomms/broadcaster/preset_left): receive information(/datum/signal (/datum/signal), Telecommunication Hub (/obj/machinery/telecomms/hub/preset))

[06:23:35] Runtime in say.dm,247: Cannot read null.toggles
   proc name: say (/mob/living/say)
   usr: Kakicharakiti (rapidvalj) (/mob/living/carbon/human)
   usr.loc: The floor (150,134,1) (/turf/simulated/floor/plasteel)

[06:23:52] Runtime in emote.dm,51: Cannot read null.toggles
   Caught by process: npc ai
   src: Poly () (/mob/living/simple_animal/parrot/Poly)
   src.loc: The floor (114,80,1) (/turf/simulated/floor/plasteel)

by the look of it the last person that went near say code was @Markolie but it could be utterly unrelated.

**Comment by Twinmold93** [comment]
Noted log around the time of the most recent crash:

[06:49:16]SAY: Tony Briner/Timmyjones806 : take the alien off your face
[06:49:16]SAY: Fethas/(CTHULHU) : Edgar Durkheim (Chemist) has entered long-term storage.
[06:49:16]SAY: CTHULHU/Fethas : Edgar Durkheim (Chemist) has entered long-term storage.
[06:49:16]ACCESS: Logout: *no key*/(Edgar Durkheim)
[06:49:16]ACCESS: Login: Urlance L M Woolsbane/(Edgar Durkheim) from 107.185.49.93-22711177 || BYOND v510
[06:49:16]DEBUG: Runtime in game.dm,212: Cannot read null.toggles <A HREF='?_src_=holder;viewruntime=[0x21015158]'>[view]</A>

Could be an issue of the person 'not existing' causing the runtime.

**Comment by Twinmold93** [comment]
[07:07:40] Runtime in game.dm,212: Cannot read null.toggles
   proc name: get mobs in radio ranges (/proc/get_mobs_in_radio_ranges)
   src: null
   call stack:
   get mobs in radio ranges(/list (/list))
   Broadcast Message(/datum/radio_frequency (/datum/radio_frequency), Flippy (/mob/living/silicon/ai), 0, "says", the AI subspace transceiver (/obj/item/device/radio/headset/heads/ai_integrated), "P.H.A.N.T.O.M (Honkway Explore...", "Flippy", "AI", "Flippy", "synthesized voice", 3, 0, /list (/list), 1459, "states", null, null)
   Telecommunications Mainframe (/obj/machinery/telecomms/allinone): receive signal(/datum/signal (/datum/signal))
   the AI subspace transceiver (/obj/item/device/radio/headset/heads/ai_integrated): talk into(Flippy (/mob/living/silicon/ai), "P.H.A.N.T.O.M (Honkway Explore...", "headset", "states", null)

Yep... Happened when he moved to cryo and AFK.

**Comment by Fox-McCloud** [comment]
Haven't seen this in ages.
