### ISSUE TITLE
Non-Human Face Repair surgery option missing

### ISSUE THREAD

**Issue by Pennwick** [ParadiseSS13/Paradise#5825]
**Problem Description**:
Face Repair surgery does not appear in the options when operating on non humans.

**What did you expect to happen**: 
Be able to operate on a Slimeperson or Vox with damaged facial structure.

**What happened instead**:
Could not as there was no option to pick the surgery.

**Why is this bad/What are the consequences:**
All non human races are stuck with mangled faces unless they can clone around it.

**Steps to reproduce the problem**:
Find/make a mangled face on a non human organic race.
Attempt to start surgery on the head region.
Be unable to fix the face because there isn't an option for the surgery.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Looking at Paradise/code/modules/surgery/face.dm it seems that the issue might be in the 'can_start' method.  I thought it might be because it the races I have trouble on aren't human but I'm a little fuzzy on what counts as human codewise.

**Comment by Crazylemon64** [comment]
@Pennwick Are you sure that the patients were not husked? That will disfigure the face, but is not able to be treated with surgery.

**Comment by Pennwick** [comment]
They were living patients. So not husked.

**Comment by Crazylemon64** [comment]
It *is* possible to have living husked patients, but I'll assume your patients did not undergo extreme burn trauma.

I'm not seeing anything in the code that makes this species-exclusive - if they have a non-robotic head, and it's disfigured, the surgery is able to be initialized.

**Comment by Pennwick** [comment]
I'm going to set up a private server and test it just to make sure. One of the paitents did mention getting Zapped by the Tesla so this could be the issue. Though if thats the case it might be worthwhile tweaking the code in some way so husk disfiguration could be fixed as well.

**Comment by Pennwick** [comment]
Did some testing. Turns out its not a bug with species but probably just a difficulty with husked individuals. So not a bug.
