### ISSUE TITLE
Nukeops can be fat

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#5828]
**Problem Description**:
Nukeops can spawn fat, robbing them of much of their gear.

**What did you expect to happen**: 
Nukeops should never be fat. If they are fat anyway, they should have their gear.

**What happened instead**:
Nukeop spawned fat, and almost naked.

**Why is this bad/What are the consequences:**
Makes things very difficult for that operative...

**Steps to reproduce the problem**:
Happened with someone set to fat in char preferences, I think.

**Comment by mrturkeytoe** [comment]
https://www.youtube.com/watch?v=hgfbafx137A&t

GIT IN MUH BELLAH

**Comment by lordpidey** [comment]
I see three possible ways to solve this.

1.) Have a bottle of Syndicate super diet pills on the nuke outpost.  Let the pills have "Fun" effects on non operatives.

2.) Just prevent nukeops from being fat.

3.) Somehow let nukeops suits be used while fat.

**Comment by mrturkeytoe** [comment]
Nuke ops gear being compatible with fat makes the most sense, enabling Fat Bastard Ops.

**Comment by Aurorablade** [comment]
THIS IS A FEATURE NO ONE FIX IT..BAD MARK
