### ISSUE TITLE
"The improved device begans to shake" - Grammar Pliz

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#5833]
Full text, someone activated an artifact:
"The improved device begans to shake, and in the distance the sound of rampaging animals arises!"

BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS BEGANS

**Comment by orelbon** [comment]
@Fox-McCloud Fixed

**Comment by Fox-McCloud** [comment]
No, it's not.

**Comment by orelbon** [comment]
woops thought that was merged
