### ISSUE TITLE
Catwalks under flooring bug

### ISSUE THREAD

**Issue by Pennwick** [ParadiseSS13/Paradise#5834]
**Problem Description**:
If a floor tile is placed over a catwalk then you can't place anything on the plating. This includes wires and another floor tile to finish it. A little testing shows that you can pry up an invisible floor tile to get the plating to accept wires but if you place a standard floor tile it will be invisible.

**What did you expect to happen**: 
You could place things on the floor tiled catwalk.

**What happened instead**:
You can't place anything on the tile.

**Why is this bad/What are the consequences:**
Engineers working on a breach sometimes get in each others way, both placing the rod at once, this creates a catwalk that CAN be built over but mysteriously when it becomes a plating you can't interact with it.

**Steps to reproduce the problem**:
Place 3 rods in space to make lattices. On one place another rod to make a catwalk, one one place a floor tile to make a plating, and on one place a rod then a floor tile to make a glitched plating. You can lay wires on the first two but not the glitched plating. You can pry up an invisible floortile from the glitched plating to lay wires but covering it with another floor tile hides them.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This seems to often happen when multiple engineers are working on fixing a breach.

**Comment by GelatinousGlob** [comment]
You might be able to fix this IC by building a wall on top of it and disassembling it liek you originally had to do to remove catwalks. At some point somebody put in the feature to tile over catwalks and must have did something funky.
