### ISSUE TITLE
It is possible to distinguish changeling from crew by looking at their OxyLoss

### ISSUE THREAD

**Issue by AndriiYukhymchak** [ParadiseSS13/Paradise#5835]
**Problem Description**:
You can find that dead body is changeling by looking at its oxyloss

**What did you expect to happen**: 
Changelings should be indistinguishable from other crew, unless they use their visible abilities. This also means that their oxyloss is capped at 200 and does not increase after death

**What happened instead**:
Oxyloss wasn't capped or it continued to grow after death

**Why is this bad/What are the consequences:**
This may give medical crew some insight on the crewmember. Also allows some meta-gaming practices

**Steps to reproduce the problem**:
Have changeling with regeneration ability. Beat it into crit. Let it die of oxyloss. Changeling should start regeneration process. Monitor oxygen damage during that process.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I was playing changeling and died from exsessive batoning and sarin. Person with health scanner was able to determine that I was a ling because something was wrong with my Oxygen Damage. While still borging dead person for doing a capital crime is good, the reasoning behind this sounded wrong and potentially abusable. Correct me if I'm wrong

**Comment by Danuis** [comment]
I agree, remove this. It's too gamey.

**Comment by Plotron** [comment]
Holy shit - I shouldn't have viewed this issue!

Now I won't be able to stop myself from meta-powergaming!

**Comment by Twinmold93** [comment]
You can already beat a changeling and if it even STARTS to regenerate at a more rapid than nutrition allows rate, giving it away that it's a changeling.

**Comment by AndriiYukhymchak** [comment]
that actually makes you research and watch over living body for a period of time. Rarely medics scan person more than once without applying any medications.

**Comment by Crazylemon64** [comment]
Newcrit would seem to mitigate this
