### ISSUE TITLE
Admin-BSA-ing produces interesting results

### ISSUE THREAD

**Issue by AndriiYukhymchak** [ParadiseSS13/Paradise#5836]
Admin BSA-ing an implanted person produces interesting results
![image](https://cloud.githubusercontent.com/assets/5380208/19913079/bf563336-a075-11e6-8ba4-d5b733784aed.png)
The only option I had on that person's menu is to mentor-PM them.
The "object" is pull-able
![image](https://cloud.githubusercontent.com/assets/5380208/19913596/837ac5de-a07a-11e6-974d-7706bd83e442.png)
and generates blood when pulled
Stats from advanced scanner are as follows (note that organs are not there)
![image](https://cloud.githubusercontent.com/assets/5380208/19913733/a594f27e-a07b-11e6-8c6d-0b499da0ccf5.png)
I was able to remove that via crematorium

**Comment by Markolie** [comment]
Mhm, dropping a BSA doesn't really do anything special to a mob: it certainly shouldn't cause this. Either an admin also did something else to the player, or this is more of a general issue that isn't exclusive to BSA's.

**Comment by pinatacolada** [comment]
I saw this happen with an exploded nukie once too, after he died. IIRC, I alt clicked the tile the thing was on, and it had no sprite, but it was called "overlay" I think

**Comment by Markolie** [comment]
Perhaps all their body parts got dismembered/destroyed somehow, but the body didn't gib properly thus there's an invisible body on the ground that's limbless but that still counts as a mob.

**Comment by AndriiYukhymchak** [comment]
Actually I was able to operate on EVERY part of their body and received no "limb is missing" messages. They had no internal organs, true. And also I had to click on their "sechud" image to do anything at all

**Comment by AndriiYukhymchak** [comment]
what was even more creepy, is that this thing was STANDING and BLOCKING MOVEMENTS until I shot it's square with a tazer

**Comment by Markolie** [comment]
Mhm, from the looks of the first image the mime was buckled. Perhaps buckled mobs being blown up doesn't delete them properly, thus causing this issue?

**Comment by AndriiYukhymchak** [comment]
we need more... science on it!

**Comment by Plotron** [comment]
You can also punch that 'shadow of a person', and interestingly enough it doesn't generate any chat messages.

**Comment by AndriiYukhymchak** [comment]
oh it generated chat messages for me!

**Comment by Plotron** [comment]
Then maybe my memory's failing or something...
