### ISSUE TITLE
Hotkey mode delayed by server lag

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#5841]
Press hotkey mode and press a button, types in the bar. Wait for 1 second lag, now hotkey mode works, and of course the other way too; Walking along, try to talk, delay cuts off the s in say and now your text has no space bars so you cant even copy-paste or edit it to be legible.

This problem has existed for a long long while now, I remember complaining about it when it first happened. I assumed it would be fixed eventually but it is still a pain in the ass and a POS to deal with when you have anything but perfect ping, which for me is never.

On TG servers ive been on there is no delay, its a client side switch, is there a reason para's hotkey mode is based on the server? Because it is quite ridiculous even in theory to have to wait for the server response just to attempt to switch hands or drop an item. Many IC messages get fucked to ooc or movement turns to text bar spam or other bullshit because of it.

Does anyone know how to fix this? Does anyone know why the fuck it happens here but nowhere else? I cant believe it was never fixed its so annoying.

**Comment by tigercat2000** [comment]
Not a bug. Paradise's hotkey mode was made a serverside system for supporting alternative keyboard layouts, including DVORAK and AZERTY. That's not feasible when done with just the clientside BYOND switches.
