### ISSUE TITLE
Mech Mounted Plasma Cutters don't exist anymore

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5843]
**Problem Description**:
What is the problem?

The Exosuit menu in the Exofab no longer has Plasma Cutters.

**What did you expect to happen**: 
Why do you think this is a bug?

Even at full research and development. The Plasma cutter does not appear on the exofab menu.

**What happened instead**:
How is what happened different from what you expected?

Exofab to have Mech mounted plasma cutters.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Mining ripley's have their effectiveness reduced massively by not being able to have a plasma cutter added to their advanced load out. 

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Crazylemon64** [comment]
Oh! Oh! I love ripleys, I gotta fix this!
