### ISSUE TITLE
Dresser (Underwear change) not working correctly

### ISSUE THREAD

**Issue by Fraggloid** [ParadiseSS13/Paradise#5844]
**Problem Description**:
Dresser permits changing of socks, but not of undershirt/underwear

**What did you expect to happen**: 
Underwear/undershirt are intended to be changeable via this item.

**What happened instead**:
Items were not changeable.

**Why is this bad/What are the consequences:**
More of a minor inconvenience.

**Steps to reproduce the problem**:
I was playing as a Tajaran, wearing no underclothes/socks, and interacted with the dresser both when clothed and unclothed. I was able to change my socks, but not underwear or undershirt.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing else extraordinary to report.

**Comment by Fox-McCloud** [comment]
Fixed, not patched.
