### ISSUE TITLE
No sprite for Captain detonated borg brain.

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#5847]
**Problem Description**:
When a borg is detonated, the MMI/Posibrain is destroyed, resulting in the ghost sprite being invisible due to MMI/Posibrain never spawning.

**What did you expect to happen**: 
To have a ghost sprite, or for MMI/Posibrain not to blow up

**What happened instead**:
How is what happened different from what you expected?
Invisible ghost sprite.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Cause it's a pain in the ass not having a sprite.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Be a borg, get blown up by command robotics console.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by jughu** [comment]
This only should be fore emagged borgs right?

**Comment by DesolateG** [comment]
Nope..

RDs robotics console spawns an MMI or Posibrain, but when command detonates borgs (which happens quite often due to shithead captains who don't understand the concept of lockdown) the brain is destroyed, leaving no ghost sprite.

**Comment by Crazylemon64** [comment]
Wait, command ordering borg destruction should leave the MMI behind - the only time this doesn't happen should be when the borg selected "robot" as their alt job title. Are you sure these were borgs created with an MMI?

**Comment by Fox-McCloud** [comment]
Turns out the submitter had `robot` as his borg title, it would seem---which has no MMI or Posi
