### ISSUE TITLE
Station Bounced Radio signal altered by telecomms

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#5849]
**Problem Description**:
Changing the telecomm scripts can alter an SBR signal, which are meant to be completely independent form tcomms.

**What did you expect to happen**: 
Not really a bug, but rather that doesn't seem like that's how it should work if they are independent devices. This means that comms traffic even with SBRs can be destroyed with a malicious script.

**Comment by Plotron** [comment]
Yeah, that's odd. Please fix.

**Comment by Anticept** [comment]
It also alters wall intercomms. Not sure if that should happen either but I'm on the fence about it.

**Comment by Markolie** [comment]
Mhm, I guess station bounced radios are handled through telecoms if they're in range of an active telecoms system. If SBR's outside of telecoms range do not get altered by telecoms I'd say this will probably have to wait until the freeze is over, as it's more so a feature request to not have SBR's go through active telecoms.

**Comment by Fox-McCloud** [comment]
Don't think this is an issue anymore, what with the telecomms rework and how scripting was dramatically altered.
