### ISSUE TITLE
robotalk as alive

### ISSUE THREAD

**Issue by trexter555** [ParadiseSS13/Paradise#5853]
**Problem Description**:
What is the problem?
After dying and being resurrected (not cloned) can hear robot talk with the follow button besie it
**What did you expect to happen**: 
Why do you think this is a bug?
seeing robotalk as alive
**What happened instead**:
How is what happened different from what you expected?
was not expecting to hear robotalk as alive
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
metagame
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
die from strange object in experimentor, get revived, almost die again from another strange object, get healed.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

sling round

**Comment by Crazylemon64** [comment]
@trexter555 How did you get revived?

**Comment by trexter555** [comment]
i think it was defib, then put into a cryo tube
