### ISSUE TITLE
Grav Gen SMES not set up properly

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#5860]
**Problem Description**:
What is the problem?

Gravity generator SMES isn't set up so that it draws power from the main grid.

**What did you expect to happen**: 
Why do you think this is a bug?

Not really calling it a bug, perhaps an oversight?

**What happened instead**:
How is what happened different from what you expected?

The terminal and wiring appears to be set up incorrectly. I expect the SMES terminal to be connected to the main grid so it can charge, while the grav gen and PDA server is connected to the SMES. This way, if station power is lost, PDAs and the Grav gen continue to operate.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

It's not, unless the shift lasts longer than usual and the SMES is drained. Just a small quirk. Someone would still need to set the SMES to charge though, but having the wiring run and ready would be helpful. Even just changing the positioning of the terminal would be extremely helpful.

**Comment by Fox-McCloud** [comment]
This isn't a bug; the SMES is isolated from the network intentionally.
