### ISSUE TITLE
Mysterious stuttering

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5861]
During an extremely long round, my game started stuttering really bad. It was as if I had the warden's security camera interface open all the time. Even chat boxes were lagging.

I restarted my game roughly ten times, rebooted my computer, cleared my cache, and toggled hardware acceleration. Nothing worked. However, upon a new round, the bug was gone, so it must have had something to do with me as an entity. It was as if the server was somehow spamming my client with something I couldn't see, lagging Dreamseeker, and never stopped.

**Comment by Fox-McCloud** [comment]
Very likely something to do with your computer and not the game server itself--as such, not much we can really do about it.

**Comment by Lady-Luck** [comment]
>Very likely something to do with your computer and not the game server itself--as such, not much we can really do about it.

@Fox-McCloud

Nope, I restarted the game many times, and my computer, cleared the cache, toggled hardware acceleration, the works. It would not clear up until the next round of play.

The server was spamming my client somehow.
