### ISSUE TITLE
Anasthetic Tanks are broken

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5862]
I think it has something to do with @Crazylemon64's PR. People don't stay unconscious when they're breathing N2O, they keep popping right back up. #5854

**Comment by taukausanake** [comment]
That was literally merged yesterday. I don't think it has bee pushed to the server yet. I may be wrong though, someone verify

**Comment by Lady-Luck** [comment]
>That was literally merged yesterday. I don't think it has bee pushed to the server yet. I may be wrong though, someone verify

It was. Crazylemon merged it just before making a changelog for the patch.

**Comment by Fox-McCloud** [comment]
already fixed
