### ISSUE TITLE
runtimes invovleing head organs.

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#5863]
having trouble figureing this one out

07:19:04] Runtime in organ_icon.dm,97: cannot read from list
   proc name: get icon (/obj/item/organ/external/head/get_icon)

[07:24:36] Runtime in organ_icon.dm,166: undefined proc or verb /obj/item/organ/external/stump/handle alt icon(). 
   proc name: get icon state (/obj/item/organ/external/proc/get_icon_state)

**Comment by Lady-Luck** [comment]
My head was actually chopped off last round, so could #5861 be related?

**Comment by KasparoVy** [comment]
On it, this one's my fault.
