### ISSUE TITLE
Pai Radio Config

### ISSUE THREAD

**Issue by pazneria12** [ParadiseSS13/Paradise#5865]
**Problem Description**:
The Radio Config part of being a Pai doesnt appear to work at all.

**What did you expect to happen**: 
I expected to be able to activate my radio microphone as you would expect

**What happened instead**:
I clicked on change frequency and it said Im not being held by anyone, I got held, and it did nothing.

**Why is this bad/What are the consequences:**
Because I was going attempt to create a spy network.

**Steps to reproduce the problem**:
Be a pai, and try to use the Radio Config

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
Isn't the radio only configurable by someone holding the pAI? I mean I know you need someone to turn on your microphone (I think) but I haven't played in so long, since the semester started. I've forgotten a lot it seems

**Comment by pazneria12** [comment]
if that is the case why does the pai have access to it?

**Comment by Markolie** [comment]
The issue here is the radio buttons not being disabled properly, despite them supposed to be disabled.

**Comment by Fox-McCloud** [comment]
Duplicate

**Comment by taukausanake** [comment]
@Fox-McCloud Not to be rude but you really need to mention which PR it's a duplicate of
