### ISSUE TITLE
Written paper hats are invisible on the mob

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#5868]
Non-blank paper hats don't appear as hats on the mob.

Instead of seeing a pretty hat, your sprite appears as if there was no hat.

The (non-blank) paper on your head can only be seen by others via examine.

Missing sprite. It worked properly a year ago or so.

**Comment by Fox-McCloud** [comment]
This only happens if there is text on the paper itself.

**Comment by Plotron** [comment]
Thanks!

**Comment by Puckaboo2** [comment]
Kind of late, but I believe this is more of a coding issue than a sprite issue. The sprite is there; it's not coded in.

**Comment by SamHPurp** [comment]
This has been fixed as of: https://github.com/ParadiseSS13/Paradise/pull/5902

And can be closed.
