### ISSUE TITLE
Vampires Gain Nutrition from Non-blood sources

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#5869]
Vampires can gain nutrition from non-blood sources; drinking various drinks or non-standard food items will replenish their nutrition.

**Comment by Doukhan** [comment]
Can they gain nutrition from drinking non-drained-fresh-from-neck blood?
It'd kinda suck (har har) if they're doomed to eternal hunger induced slowness.

**Comment by Crazylemon64** [comment]
This seems more like a feature request, Fox, as this would be a snowflaked behavior. Unfortunately, I think it'll have to wait until after the freeze.
