### ISSUE TITLE
Missing Pipe - AI Satelite

### ISSUE THREAD

**Issue by Pennwick** [ParadiseSS13/Paradise#5873]
**Problem Description**:
Air supply pipe missing  between MiniSat Foyer and MiniSat Antechamber

**What did you expect to happen**: 
There to be a supply pipe under the tile under the doorway

**What happened instead**:
No pipes.

**Why is this bad/What are the consequences:**
The three northmost vents in the MiniSat can't get fresh oxygen if theirs is vented.

**Steps to reproduce the problem**:
Go to MiniSat, into the room with the microwave, open south door, avoid turrets and crowbar the tile. Or look at the map files.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I thought this got caught in the last map patch but it seems like this pipe was missed.

**Comment by Fox-McCloud** [comment]
@FreeStylaLT

**Comment by Kyep** [comment]
@FreeStylaLT @Pennwick I went to verify this, but it appears to have been fixed.

**Comment by SamHPurp** [comment]
@Crazylemon64 @Fox-McCloud this can be closed.
