### ISSUE TITLE
Cable Coils and Building Computers

### ISSUE THREAD

**Issue by Qinexio** [ParadiseSS13/Paradise#5883]
**Problem Description**:
Cable Coil ammount can suprisngly drop down to -1 if used to build multiple computers and the ammount somehow drops below 0.

**What did you expect to happen**: 
For the cable coild to dissapear.

**What happened instead**:
A cablecoil with infinite uses was provided ( ammount -1)

**Why is this bad/What are the consequences:**
Yay for infinite cable coils.

**Steps to reproduce the problem**:
Simply use the cable coil to build multiple computers to the point it reaches -1. Make sure you have a low ammount of coil before hand.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: -

**Comment by KasparoVy** [comment]
Thanks for the report, found what the problem was and I'm working on resolving it now.
