### ISSUE TITLE
Blob Mode runtimes

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#5888]
[23:58:17] Runtime in Blob-Reagents.dm,51: Cannot execute null.add reagent().
   proc name: reaction mob (/datum/reagent/blob/envenomed_filaments/reaction_mob)

[00:06:35] Runtime in adv_med.dm,199: Cannot execute null.blob act().
   Caught by process: obj
   src: The blob node (/obj/effect/blob/node)
   src.loc: The floor (135,93,1) (/turf/simulated/floor/plasteel)

[00:05:02] Runtime in ,: bad arg name 'ignore_lying'

**Comment by Kyep** [comment]
@AffectedArc07 Should be closable, can't find any of this runtime in the logs anymore.

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/94361095-ce90c800-00a9-11eb-8868-583162e3edb9.png)
![image](https://user-images.githubusercontent.com/25063394/94361103-d2bce580-00a9-11eb-9d4d-69f6fc7a2aba.png)
