### ISSUE TITLE
Throwing sprites on the opposite direction of your sprite.

### ISSUE THREAD

**Issue by GutTC** [ParadiseSS13/Paradise#5889]
**Problem Description**:
When you aggressively grab a sprite either NPC or an actual player and then throw them into the opposite direction of your very own sprite (behind) will results you and the person you threw flying along together for at least **_four tiles_**.

**What did you expect to happen**: 
Usually, of course, you throw people at specific location and they'd land there. Without hitting you and have you drive along with them.

**What happened instead**:
You fly along with them! Human cannon! For four tiles.

**Why is this bad/What are the consequences:**
It's dependable. While people wouldn't use grab throwing during combat and having enough robust sense to do it. Some people would prefer doing it to get a greytide outta their offices. But Importantly, if you try to space somebody, this could be danger.

**Steps to reproduce the problem**:
This happened all the time whenever someone decide to throw somebody from opposite direction. Fix me senpai.

**Comment by Lady-Luck** [comment]
God this is annoying.

**Comment by GutTC** [comment]
Fear the law of physics!

**Comment by Lady-Luck** [comment]
At the very least it would be nice to rotate in place once you grab someone.

**Comment by GutTC** [comment]
Would it work with the tighter (or even passive) grabs? Difference from pulling, they tend to move without having you walk pass them with grabs. I believe.

On the brighter side, if you are the victim you might survive from being thrown into the space airlock.
And on the very bad side. It'd take that long or forever to reposition yourself and throw someone out of your way in very-quick-needs situation especially the tight walkways like maintenances. Or that Shitcurity would accidentally throw themselves in the cell instead of the guilty greytide. Kek. I really wonder how many fucks up occurred with this theory.

**Comment by Plotron** [comment]
@GutTC - just keep in mind it's possible and quite feasible to do a grab and then *flip.
