### ISSUE TITLE
Cold Resist no longer makes you spaceworthy

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5892]
In the past, Cold Resist made you space worthy. However, with Cold Resist + No Breathing now, I suffer low pressure damage. Not sure if this was intentional.

**Comment by Regen1** [comment]
not a bug, it's been like this for quite a long time

**Comment by Fox-McCloud** [comment]
Regens is incorrect. Cold resist is meant to block pressure damage; if you were taking it, then that's definitely a bug.

Cold res block low pressure, heat res blocks high pressure.

**Comment by Regen1** [comment]
Then I guess it's been a bug since forever

**Comment by TullyBurnalot** [comment]
Cannot reproduce. Seems to work just fine.

**Comment by Lady-Luck** [comment]
>Cannot reproduce. Seems to work just fine.

Could it be that due to the new chance system the pressure resist sometimes isn't being applied? Because I assure you, I had a blue aura and was taking obscene pressure damage.

**Comment by Lady-Luck** [comment]
>Cannot reproduce. Seems to work just fine.

Could it be that due to the new chance system the pressure resist sometimes isn't being applied? Because I assure you, I had the red aura and was taking obscene pressure damage.

**Comment by TullyBurnalot** [comment]
Uh, this was attempted with COLD_RESIST and NOBREATHE. Will try with HEAT_RESIST, hold on.
