### ISSUE TITLE
Medibot +Ambulance Issues

### ISSUE THREAD

**Issue by Captaincardgage** [ParadiseSS13/Paradise#5898]
**Problem Description**:
What is the problem?
Medi-bot was detaching then teleporting back behind the paramedics ambulance.

**What did you expect to happen**: 
Why do you think this is a bug?
I had expected for the Medi-bot to remain inside the paramedics cart and not to move but can still name and identify people.

**What happened instead**:
How is what happened different from what you expected?
The Medibot had instead ripped/removed the cart from the ambulance however it re-attatches.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
more than likely a visual issue but if the paramedic is oblivious they could steal the bed trailer or just the med-bot...

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Connect a medi-bot onto the paramedics bed onto the ambulance, injure or have a injured player nearby and it will detatch itself and the bed attatchment from the Ambulance if you or it is moving to heal them.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I was the surgeon during a Traitor round it seems. As stated earlier this is more of a visual error than anything. The paramedic can merely move and the ambulance the bed will re-attatch to it but can snap off repeatedly if the medi-bot spots injured players.

**Comment by Taaketa** [comment]
Was the medbot set to patrol?

**Comment by Captaincardgage** [comment]
No but patrol should be having the same results, probably even faster.
