### ISSUE TITLE
Breaking news from Breaking news from The Archer Times!

### ISSUE THREAD

**Issue by Polkjm** [ParadiseSS13/Paradise#5901]
**Problem Description**:
When posting a new story to a news feed, the message displays "Breaking news from" twice.

**What did you expect to happen**: 
"Breaking news from The Archer Times!"

**What happened instead**:
"Breaking news from Breaking news from The Archer Times!"

**Why is this bad/What are the consequences:**
This isn't very important, but it's annoying and would take seconds to fix.

**Steps to reproduce the problem**:
1: Create a new feed channel
2: Submit a new feed story

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I'm pretty sure this is quite a simple problem. It happened in many games I played

**Comment by Taaketa** [comment]
Is it not because some people are naming their newfeeds, breaking news from XXXX when it already adds breaking news to the announcer?

**Comment by Polkjm** [comment]
That's not the case. I never put "Breaking news" before the name of the channel. It puts it automatically at two different places, as I've confirmed in the code: when retrieving the channel name and when making the actual announcement. Just remove one of those instances and this tiny bug will be fixed
