### ISSUE TITLE
Glitch into null with sepia slime

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#5904]
**Problem Description**:
If a Sepia slime is used, there's a chance of the victim, and unrelated people waking up at Null, where they've reported they were asleep, unconscious and unable to do anything. Admin intervention is needed to teleport them out of this null place, 

**What did you expect to happen**: 
They get za warudoed and that's it

**What happened instead**:
They somehow ended up waking up in null, and a botanist that weren't sepia'd at all somehow also entered null all of a sudden.

**Why is this bad/What are the consequences:**
This is not WAD

**Steps to reproduce the problem**:
Rumi ICly used a sepia slime on someone who was trying to kill him / beat him. After the slime was used, the victim reported in ahelp a while later that they are seeing a black screen and asleep. Upon following them, they were indeed in a pitch black place where i cannot seen. When their location were examined, it turn out they woke up at a place called "Null". Moment later, this also happened to a botanist that were not sepia slimed at all.

I am not sure how to reproduce this problem.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:  I can try to find relevant logs and provide it to maintainer on discord if it will help

**Comment by fludd12** [comment]
Honestly, we need /tg/'s nullspace handler.

**Comment by tigercat2000** [comment]
@fludd12 Could you elaborate on that, please?

**Comment by fludd12** [comment]
/tg/ has a special room where mobs are teleported to when they enter nullspace. It's a bit of a reference to Legend of Zelda, but it's basically a room with a button that takes you to the arrivals shuttle.

**Comment by taukausanake** [comment]
I don't remember Sepia slime cores teleporting people. A quick look at the code and I don't see that in there. This actually happens instead of timestop?

**Comment by Spacemanspark** [comment]
http://zelda.wikia.com/wiki/Top_Secret_Room
While I mostly enjoy Pokemon, Zelda is another favorite of mine.

**Comment by Sirryan2002** [comment]
can't reproduce
