### ISSUE TITLE
Vampires not showing on antagHUD

### ISSUE THREAD

**Issue by sothangel** [ParadiseSS13/Paradise#5905]
**Problem Description**:
Vampires are not showing when antagHUD is turned on.

**What did you expect to happen**: 
Because they should appear.

**What happened instead**:
Nothing happened.

**Why is this bad/What are the consequences:**
Quality of Life for ghosts, can also lead to unnecessary ahelps being sent. 

**Steps to reproduce the problem**:
Be an observer/ghost, turn on antagHUD, see vampire doing obviously vampyric things, but no HUD marker.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Traitor + Vampire round type.

**Comment by TullyBurnalot** [comment]
Cannot reproduce, Vamps showing up on HUD just fine.
