### ISSUE TITLE
W-where is my tail?!

### ISSUE THREAD

**Issue by FireFlashie** [ParadiseSS13/Paradise#5906]
**Problem Description**:
On photos in medical and security records - Vulpes and Tajars (at least) doesn't have a tail.
![image](https://cloud.githubusercontent.com/assets/10612280/20572763/e3688be4-b1bd-11e6-95a1-c294bf2b060d.png)

**What did you expect to happen**: 
Erm... Tail?

**What happened instead**:
No tail.

**Why is this bad/What are the consequences:**
Tails are... Eee...

**Steps to reproduce the problem**:
1. Create non-human-character
2. Join game
3. Open Security or Medical Records

**Comment by KasparoVy** [comment]
This one's been around for ages, just never really buckled down and tackled it properly. Going to sort it out this weekend. Thanks for the report

**Comment by KasparoVy** [comment]
Found it.
