### ISSUE TITLE
Lowercase random names

### ISSUE THREAD

**Issue by FireFlashie** [ParadiseSS13/Paradise#5907]
**Problem Description**:
When generating random name for Vulp or Tajara - first letter is lowercase instead of uppercase.

**What did you expect to happen**: 
First letter of first and second name would be uppercase.

**What happened instead**:
Lowercase.

**Steps to reproduce the problem**:
1. Open Setup Character
2. Select|Create Vulp or Tajara 
3. Click "Random Name"

**Comment by TullyBurnalot** [comment]
I have been clicking on "Random Name" for both species for... some time now. All of the results have an upper case first letter.

Cannot reproduce.
