### ISSUE TITLE
Light Switches in OR1/OR2 affect other OR as well

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#5908]
**Problem Description**:
Using a light switch in OR1 or OR2 turns off the lights in BOTH ORs.

**What did you expect to happen**: 
It should only turn off the lights in the OR the switch is in.

**What happened instead**:
It turned off the lights in both ORs.

**Why is this bad/What are the consequences:**
It isn't an important issue. Just mentioning it for completeness.

**Steps to reproduce the problem**:
Go into an OR, e.g: OR2.
Use the light switch.
Observe that this also turns off the lights in the other OR, the one you're NOT in.

**Comment by FalseIncarnate** [comment]
Light switches work off their area. If memory serves, the two ORs both use the same area, making this a mapping issue.

**Comment by KasparoVy** [comment]
Finished a fix for this, just testing it to make sure I didn't break anything in the process.
