### ISSUE TITLE
Pods can be deleted by stationary meaty ores

### ISSUE THREAD

**Issue by shazbot194** [ParadiseSS13/Paradise#5909]
**Problem Description**:
Me and my pod was deleted when running into what looked like safe meat 

**What did you expect to happen**: 
The meat was completely stationary next to a hull breech. So it should have just been normal food.

**What happened instead**:
Both me and my pod was deleted, removing me from the round without any way back other then special spawns like npc, drone, golem, ext. 

**Why is this bad/What are the consequences:**
People in pods can be deleted without any warning for what looks like a normal item.

**Steps to reproduce the problem**:
This will be harder to replicate, but find a meaty ore, run into it with a pod, or possibly be hit with it, and it should delete the pod.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a vamp round but that shouldn't have affected the meaty ore or my pod.

**Comment by jughu** [comment]
it should atleast set the pod on fire

**Comment by Twinmold93** [comment]
Stationary meaty ores are a bug with meaty ores themselves. However, the issue where when a pod is destroyed/deleted, it deletes the pilot will be resolved with my next patch to pods.
