### ISSUE TITLE
Triple Citrus is unable to be made.

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#5911]
**Problem Description**:
When mixing the three things needed for the drink, it does not form into Triple Citrus.

**What did you expect to happen**: 
The recipe should form into Triple Citrus.

**What happened instead**:
The three, should, if the the recipe is correct, form into Triple Citrus.

**Why is this bad/What are the consequences:**
It's not entirely an huge, game breaking issue, but it makes some things unable to be made, such as Colorful Reagent, and actually having the drink in the game.

**Steps to reproduce the problem**:
Put the three ingredients into a container (Lemon, Orange, and Lime. 1 part each), it SHOULD form Triple Citrus, but it doesn't seem that it does (unless some strange thing is going on.)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 

Nothing that would be relevant, you mix the three in the same container. Otherwise, there should be no interference with it.

**Comment by taukausanake** [comment]
You sure you didn't use lemonlime instead? I sometimes get them confused. Otherwise I think [this](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/recipes/drinks.dm#L768) is correct?

**Comment by kylejen** [comment]
@taukausanake I'm fairly sure it was all separate. I even checked in the chem dispenser (chemist, at the time) and it showed them all as separate reagents (lemon juice, orange juice, lime juice)

I dunno.

**Comment by Fox-McCloud** [comment]
![img](https://i.gyazo.com/846a7a4a9db8831bf79115cd0097dca2.gif)

Cannot reproduce. I'm guessing you dispensed lemonlime instead of actual lemon.
