### ISSUE TITLE
Air Supply pipes cannot be interacted with when they have no air in them.

### ISSUE THREAD

**Issue by Talboturbo** [ParadiseSS13/Paradise#5912]
**Problem Description**:
Air supply pipes cannot be interacted with when they have no air in them.

**What did you expect to happen**: 
I wanted to unwrench the pipes from the floor so I could move them to the appropriate location.

**What happened instead**:
I attempted to click on them with a wrench and nothing happened.

**Why is this bad/What are the consequences:**
Moving pipes is generally good if someone else sabotages them up, or you want to move unused pipes to a more optimal location.

**Steps to reproduce the problem**:
In your air system, unwrench one pipe, and go along the pipe as many tiles as you want but at least 2 tiles and unwrench the pipe at the other end.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This bug also may be present when placing pipes down on their own without attachments.

**Comment by Citinited** [comment]
I *think* I got this one, so will include it in next PR I do.
