### ISSUE TITLE
Mining Redemption Machine

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#5920]
**Problem Description**:
When the mining vendor looses power, you are still able to put your ID in the machine and afterwards not able to retrieve it out.

**What did you expect to happen**: 
You should be able to manually eject your ID from the machine even during power loss, and not be able to put your ID into the machine if it has no power.

**What happened instead**:
The machine 'ate' my ID and I was without an ID for the game.

**Why is this bad/What are the consequences:**
It leaves people with no ID, and for miners if their ID has points that hurts them even more than others.

**Steps to reproduce the problem**:
Two ways to cause this.
1- Put your ID in the vendor machine, machine looses power, you can not get your ID out of it.
2- Vendor looses power and you do not notice, you put your ID in it, you can not get your ID out of it.

**Comment by KasparoVy** [comment]
Was the machine ever re-powered or deconstructed while your ID was in it?

**Comment by KasparoVy** [comment]
Was the machine ever re-powered or deconstructed while your ID was in it @Denthamos?

**Comment by jughu** [comment]
If im right you can also unwrench the machine and drag it next to any ore pile and takes it up this might be another oversight but its unbolted from the floor so it shouldnt be powered

**Comment by Denthamos** [comment]
@jughu This is the mining reward vendor, not the ore redemption machine.

@KasparoVy If the machine is re powered then you can retrieve your ID however when there is large scale crisis going on or power is cut to part of the station in some manner, you will not be getting your ID back anytime soon.  And if the machine is deconstructed you do not get your ID back.

**Comment by jughu** [comment]
OHH this should be a feature then tbh the machine is depowered and has your ID in it

**Comment by taukausanake** [comment]
No one wants their ID stuck inside a machine. Why not have a manual remove_id verb for the machine? Seems like the best solution I think

**Comment by jughu** [comment]
THE MACHINE IS UNPOWERED AND YOUR IDD IS INSIDE IT CANT EJECT WITHOUT POWER JUST IRL

**Comment by taukausanake** [comment]
MANUAL. EJECTION. A save guard for that exact issue. Think coin ejector except for something more important.

A side thought: You can insert your IDs into ATMs. And let's not forget certain computers too. Are these also a problem if an ID is inside then during a power outage?

**Comment by Denthamos** [comment]
@taukausanake I actually worked on ATM's before, a maintenance technician has the capability of removing an ID manually by removing the slot that holds it, actually pretty simple to do.

I see it as a problem in game though due to how much you rely upon your ID for anything, and if the HoP is not able to print you out another one, your round is basically done if you are a miner as due to the fact you show up as an unknown in the hardsuit.
