### ISSUE TITLE
Broken floor tiles when person is ejected from chute, drops as item, floor/plating cannot be repaired

### ISSUE THREAD

**Issue by yusiangpotato** [ParadiseSS13/Paradise#5923]
**Problem Description**:
I was making ejection-type disposals hallways along CPH and twds escape, simple with a chute and trunk, so you walk in, it shoots you multiple tiles along the direction of the trunk
The bug occurs when the tile adjacent to the output has a floor tile
The floor tile is ejected as a "broken tile", which has an examine of being unobtainium.
The subfloor/plating is visible, but still shows on the bottom bar as "floor". Floor tiles cannot re-plate this floor, it remains in limbo until the round is reset

**What did you expect to happen**: 

1. Broken tiles are supposed to be unobtainium
2. The plating should be called plating, not floor, and I should be able to re-floor it, though that would be stupid if the disposal highway is still there.

**What happened instead**:
Normally unobtainable broken tile flies out (may hit person, be careful!)
Floor cannot be repaired.

**Why is this bad/What are the consequences:**
Graphical issues? Buggy? Unobtainable broken tiles in game?

**Steps to reproduce the problem**:

1. Remove floor tile.
2. Attach a trunk by wrenching,welding it to the plating.
3. Attach a chute to the trunk, wrenching, welding.
4. Walk into chute.
5. Watch broken tile fly out, and floor/plating get screwed up. Broken tile may cause brute to nearby person.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not really, no.

**Comment by FalseIncarnate** [comment]
If my memory serves, you can still crowbar up the floor where the "broken floor" came from, though its not obvious to do this, to replace it.
