### ISSUE TITLE
Changeling head is transparent

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#5924]
**Problem Description**:
Changeling icon on human bugged the hell out
http://puu.sh/sxixu/c6c36c0729.png
http://puu.sh/sxiBf/5afa83eb17.png
**What did you expect to happen**: 
Their face is literally gone

**Steps to reproduce the problem**:
Got little information here, seemingly it just happens at random

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
The current round was just changeling.

**Comment by FlattestGuitar** [comment]
Huh. I've seen it happen a few times myself, but never linked it to those being changelings.

I usually just regenerate their icons and it seems to fix the problem.

**Comment by KasparoVy** [comment]
[This PR](https://github.com/ParadiseSS13/Paradise/pull/5879) might fix it since it changes UpdateAppearance to call regenerate_icons and changeling transformation power calls UpdateAppearance.

**Comment by FlattestGuitar** [comment]
Still happening on non-changelings.

Also, not just the head, but the whole body goes invisible.
