### ISSUE TITLE
Vampire only gains nutrition through normal food, not through blood.

### ISSUE THREAD

**Issue by wotan90** [ParadiseSS13/Paradise#593]
In a recent vampire round i tried to eat blood from the living and the dead to gain nutrition. This failed though, so i got some beef jerky and 4 raisins from the vendomat mmmmh.

**Comment by Markolie** [comment]
Not sure if this is actually a bug.

**Comment by Earthdivine** [comment]
It might not be, the food icon becomes a blood drop really creates confusion on what you need for Nutrition.
