### ISSUE TITLE
Vampires can't drink blood after cloning them.  Also, they don't burn in the chapel.

### ISSUE THREAD

**Issue by Alaysian** [ParadiseSS13/Paradise#5939]
Problem Description:
Vampires, when cloned lose the ability to drink blood, hurt people with punches, and they no longer burn in the chapel.  Despite this, they keep all the other powers they have.  Also, the hud for amount of blood you have goes away, but you can check it in the vampire tab.

What did you expect to happen:
Vampires should either lose all their powers and no longer be antagonists, or should still be able to gather blood and burn in the chapel (unless they are strong enough).

What happened instead:
The ability to drink blood and become a stronger antagonist was lost early on, and it hindered the ability to be a threat.  No longer burning in the chapel meant that security was certain I was not an antag and let me free, allowing me to kill the RD despite semi-probably cause to suspect me. 

Why is this bad/What are the consequences:
If antags can't progress along the path prescribed, it may leave them feeling cheated, especially if some of their powers are left.  Keeping all their abilities would allow them to do that.  Alternately, removing them completely might alleviate some of that, as it would reinforce to them that this is a consequence of dying.

Steps to reproduce the problem:
Be an vampire, die, get resurrected, turn on hostile intent, target the head, make sure you and your target have no masks on, and click on your target.  You will not drink blood like normal.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?): Vampire round, trying to drain a naked humanized monkey after being cloned.

**Comment by KasparoVy** [comment]
Pretty sure I've figured out what the issue was. Working on a fix RN, thanks for the report
