### ISSUE TITLE
Grey Telepathy and Cloning

### ISSUE THREAD

**Issue by pazneria12** [ParadiseSS13/Paradise#5948]
**Problem Description**:
When you get cloned you lose your ability to talk to people with your mind.

**What did you expect to happen**: 
Wake up naked, afraid, and with telepathy

**What happened instead**:
I woke up Naked and Afraid

**Why is this bad/What are the consequences:**
Greys have so little between them and humans, and this just lessens that even more.

**Steps to reproduce the problem**:
Be a grey, get scanned, Die, be cloned.

**Comment by KasparoVy** [comment]
I'll try to investigate this but I've just about run out of time.
