### ISSUE TITLE
Screen freezes at random moments

### ISSUE THREAD

**Issue by daylight2** [ParadiseSS13/Paradise#5951]
**Problem Description**:
What is the problem?
Screen randomly freezes, cannot click or move the visual screen.

**What did you expect to happen**: 
Why do you think this is a bug?
screen not to freeze

**What happened instead**:
How is what happened different from what you expected?
screen froze

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
this has ruined my antag rounds twice and is generanley very annoying.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
these have been pretty random, happens abaut once every round, sometimes more, sometimes less.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
it is generaley very random, and I cannot fill this area because it has happened in so many different scenarios.

if you need the logs, then character Desmond Lee 5/12/2016 ~20:26 GMT +2

**Comment by taukausanake** [comment]
This happens to me all the time. I just relog and it fixes but a solution should be found if possible. The worst part about this is it's literally the screen and not the client. You can still move around and do things, you just can't see it. Can't remember if you can still hover your mouse over things and see their name. Maybe it is a client issue

**Comment by pazneria12** [comment]
if Its JUST the Visuals, did you try ooc Cancel Camera view? that sometimes works.

**Comment by daylight2** [comment]
i'll try that

**Comment by Crazylemon64** [comment]
We cannot really do much about this unless you provide further details. A bug that cannot be reproduced is near-impossible to debug and remove, and what you state sounds like a client-side issue

**Comment by taukausanake** [comment]
I don't believe Cancel Camera works otherwise it wouldn't be an issue for me still. And yeah, it does sound like something impossible to fix, especially if it's a Byond issue. Has it never happened to anyone else?

**Comment by TheBeoni** [comment]
It makes you completely stop not being able to move not seeing OOC or IC but you still continue to do stuff (without being able to see what you do of course) so it's most likely only animation that gets frozen in place. Cancel Camera does not fix it only relog.

**Comment by taukausanake** [comment]
The chat still works for me. I always have to type in OOC that I have to relog when it happens and I can hear everything else going on

**Comment by daylight2** [comment]
you can hear whats going on, but i never see any messages i output myself.
