### ISSUE TITLE
Admin Revive does not properly revive Cyborgs

### ISSUE THREAD

**Issue by athompson11** [ParadiseSS13/Paradise#5953]
**Problem Description**:
The rejuvenate Proc on /mob/living does not properly heal Cyborgs. It revives them, but it doesn't fix their module damage which causes them to immediately die again after the revive.

**What did you expect to happen**: 
The rejuvenate proc should revive a human controlled mob fully, regardless of type.

**What happened instead**:
It did not.

**Why is this bad/What are the consequences:**
This makes it difficult to do testing with Cyborgs when damage is involved as the Cyborg must be repaired in-game, and it also makes it difficult to deal with grief on servers that do "admin resets" of persons involved in grief.

**Steps to reproduce the problem**:
Damage a cyborg to any point, and attempt to admin revive it.
Nothing will actually happen, as it appears the code doesn't handle modules.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Additionally, there is a runtime from the robot/inventory.dm file when performing revives, as hands is a null reference during the revive for whatever reason.

**Comment by KasparoVy** [comment]
Thanks for the detail.

**Comment by jughu** [comment]
Isnt this the same with organs?

**Comment by athompson11** [comment]
@jughu, when testing it, organ damage to humanoid mobs seems to be healed correctly, but to robot components, it's not.
