### ISSUE TITLE
Items disappear from backpack.

### ISSUE THREAD

**Issue by Patar98** [ParadiseSS13/Paradise#5963]
**Problem Description**:
I watched as items disappeared from my backpack, did not appear in my hands. No character was beside me. There were no admin logs of the pick pocket. Nothing was on the ground.

**What did you expect to happen**: 
That items don't disappear.

**What happened instead**:
Items don't disappear from existence without logs.

**Why is this bad/What are the consequences:**
I lost important objects.

**Steps to reproduce the problem**:
I had a virus that made me fat. All items fell off me. I put them in my backpack. All items were present. A few disappeared. I did not click on them. They were not anywhere.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
There was a radiation storm, I was in maintenance. I turned fat. Story is above.

**Comment by taukausanake** [comment]
What items disappeared? You kind of need to give more details for something like this. Also was it a normal backpack or a bluespace backpack?

**Comment by Patar98** [comment]
Normal leather satchel. PDA and red pants.

**Comment by taukausanake** [comment]
And you said you became fat before this? Are you sure you put the pants and PDA inside your backpack? It is possible that you lost your pants due to becoming fat. Not sure about the PDA however
