### ISSUE TITLE
Welding effect when IPC

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#5964]
**Problem Description**:
When IPC's use a welder the effect of welding without goggles appears but doesn't actually damage your eyes,

**What did you expect to happen**: 
No effect should appear.

**What happened instead**:
The effect appeared.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:

1. Be an IPC.
2. Weld a wall without goggles.

**Comment by Fox-McCloud** [comment]
This isn't a bug; it intentionally blinds you, no matter what; it's only the damage they're immune to.

You can still overload mechanical eyes, afterall--they're impacted by flashes too.
