### ISSUE TITLE
Couple Vampire Issues

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#597]
Upon cloning, Vampires lose their abilities tab and cannot get it back by drinking blood, only way to fix it is to remove and re-give them Vampire antag status.

Upon acquiring 500+ units of blood, the Vampire only becomes immune to the Chapel, yet the description says that you become immune to "all holy things", which should include Holy Water, but doesn't, Holy Water still harms 500+ unit vampires when sprayed or consumed, as does space.

For the latter, I'd suggest either fixing the 500+ unit message or fixing the immunities, to reduce the confusion some people may have with the mechanics.

**Comment by Fox-McCloud** [comment]
They're always meant to taken damage from star light, just puttin' that out there.

As for holy water, I'm pretty sure that IS a bug; there's no check for splashing and the check for internal consumption seems to be....messed up.
