### ISSUE TITLE
Windoor board permissions not working correctly

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#5973]
**Problem Description**:
Go to make a new Windoor, set the door permissions to one access, set engineering and atmospherics as an engineer. Install board and set door. Can't open windoor.

**What did you expect to happen**: 
I have engineering access so it should open for me, same with atmospherics.

**What happened instead**:
It doesn't open for me or atmospherics, only someone with both access requirements work.

**Why is this bad/What are the consequences:**
I can't open my own doors unless it is one access or all access. 

**Steps to reproduce the problem**:
See step one.

I also tried doing it without switching the ALL requirements to ONE and with locking and not locking the board after setting it. In all cases I could not open the door unless I only had one access permission or no permissions.

**Comment by TheBeoni** [comment]
I am not absolutely sure but i believe it is made to work that way. I think when you set the door you need to have all of access requirements you have set or it will not open.

**Comment by GelatinousGlob** [comment]
Isn't that why it has the choice between ALL or ONE? What is the point of ONE if it does the same thing as ALL?

**Comment by SamHPurp** [comment]
Unable to re-produce

**Comment by MINIMAN10000** [comment]
After attempting to repair cargo windoor with the settings "One" "Cargo Office" "Engineering" the door did not work

Creating windoor with "One" "Cargo Office" did work

Creating windoor with "One" "Engineering" "Power equipment" as I have all of those permissions it did work.

I can confirm it is reproducible windoors "One" and "All" setting both behave as if it is set to "All"

**Comment by MINIMAN10000** [comment]
Found out why you couldn't reproduce it. The code between a plasteel windoor and a normal windoor is different. Plasteel windoors operator correctly but if you don't add plasteel it will not set "req_one_access"

The code in question is as follows [windoor_assembly.dm](https://github.com/ParadiseSS13/Paradise/blob/76631d0dab1fc04855f23b526985c6974b67b479/code/game/objects/structures/windoor_assembly.dm)
```

if(secure)
	var/obj/machinery/door/window/brigdoor/windoor = new /obj/machinery/door/window/brigdoor(src.loc)
	if(facing == "l")
		windoor.icon_state = "leftsecureopen"
		windoor.base_state = "leftsecure"
	else
		windoor.icon_state = "rightsecureopen"
		windoor.base_state = "rightsecure"
	windoor.setDir(dir)
	windoor.density = FALSE

	if(electronics.one_access)
		windoor.req_one_access = electronics.conf_access
	else
		windoor.req_access = electronics.conf_access
	windoor.electronics = src.electronics
	electronics.forceMove(windoor)
	if(created_name)
		windoor.name = created_name
	qdel(src)
	windoor.close()


else
	var/obj/machinery/door/window/windoor = new /obj/machinery/door/window(loc)
	if(facing == "l")
		windoor.icon_state = "leftopen"
		windoor.base_state = "left"
	else
		windoor.icon_state = "rightopen"
		windoor.base_state = "right"
	windoor.setDir(dir)
	windoor.density = FALSE

	windoor.req_access = electronics.conf_access
	windoor.electronics = src.electronics
	electronics.forceMove(windoor)
	if(created_name)
		windoor.name = created_name
	qdel(src)
	windoor.close()
```
