### ISSUE TITLE
You can change a Skrell's body color. 

### ISSUE THREAD

**Issue by Puckaboo2** [ParadiseSS13/Paradise#5974]
I remember you guys saying that it should not be an option for Skrell to have different body colors. Well, not only is the base sprite of the Skrell race a misty-green (as it should,) you can change the RGB values on top of it to achieve undesired results, including a change in eye color.

https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL3NMaDloLzJiNDUzNGVmNDcucG5nIn0.sC_okX9rT3BOC-4BD-dk0SSjxHQ 
(You gotta admit, that fade from purple to teal blue is sick as heck tho)

That's not supposed to happen. It's supposed to stay a misty-green color, if you guys told me the truth that Skrell are supposed to stay their base sprite color, but that is only possible if you make the Skrell's body color and body accessories 0, 0, 0.

Either I greyscale the Skrell icon and change the icon's eyes to match the Skrell's shape, and someone codes Skrell to allow Skrell to change the color of their skin...
Or we permanently set the Skrell's body color to 0,0,0, the eye color to 0,0,0, and remove the options to change Skrell's coloring.

**Comment by Spacemanspark** [comment]
Who said that wasn't a thing? I'm pretty sure this is intentional.

**Comment by tigercat2000** [comment]
This isn't a bug. Skrell were changed to allow for body colors.

**Comment by KasparoVy** [comment]
Pending a feature in the works that greyscales Skrell. I think I've still got it on one of my many branches someplace.

**Comment by taukausanake** [comment]
Rainbow Skrell when

**Comment by Puckaboo2** [comment]
Kasparo, I can just greyscale the Skrell myself; no big deal. I'm good with icons.

**Comment by taukausanake** [comment]
The moment you grayscale Skrell though you need to code them up properly to accept skin color values like Vulps and such. Personally I rather they have a set range rather than any color out there. Failing that, just specific colors. Limiting it is but it just feels correct for them

**Comment by Puckaboo2** [comment]
I can reduce the Skrell's shade, no problem.  http://puu.sh/sNxUX/ac2e268c4a.png See? I can make some dark blue eyes for Skrell named eyes_skrell_s and someone can just code those to not change color. Yanno?

**Comment by tigercat2000** [comment]
Why would we prevent Skrell eye color from changing?
