### ISSUE TITLE
Magnetic Gripper cannot grip conveyer belts assemblies or switches

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#5976]
**Problem Description**:
Magnetic Gripper cannot grip conveyer belts assemblies or switches

**What did you expect to happen**: 
the Gripper to pick those up

**What happened instead**:
the magnetic gripper gave an error message

**Why is this bad/What are the consequences:**
it makes it impossible to fix conveyer belts as cyborg

**Steps to reproduce the problem**:
print a conveyer assembly and try to pick it up with magnetic gripper.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by tigercat2000** [comment]
Oversight or Feature Request.

**Comment by Fox-McCloud** [comment]
This is a feature request for sure ( a good one, in my opinion), but as such....
