### ISSUE TITLE
Air alarm percentages add up to over 100%

### ISSUE THREAD

**Issue by yusiangpotato** [ParadiseSS13/Paradise#5977]
**Problem Description**:
Air alarm content %s add up to over 100%.
http://imgur.com/a/ZzleS

**What did you expect to happen**: 
Sum(percentages) = 100%

**What happened instead**:
http://imgur.com/a/ZzleS

**Why is this bad/What are the consequences:**
So is the air in the room actually 4% rubbish? 

**Steps to reproduce the problem**:
Not sure if repeatable. But this was from someone releasing NO2 into the CPH.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Mitchs98** [comment]
Still exists.

**Comment by Sirryan2002** [comment]
since this has been moved to TGUI, someone needs to verify that this is still an issue

**Comment by Groudonmaster** [comment]
Releasing N20 on a local server in the CPH results in the air alarm reading a total of 100.1%

Values given:
15.1% Oxygen
56.7% Nitrogen
28.3% Other

However, this was a very short duration and the system quickly corrected itself to values that add up to 100%

15.4% | 58% | 26.6%

15.7% | 59.1% | 25.2%

And a final one after 2 minutes had passed:

17.1% | 64.5% | 18.4%

It appears the issue only arises during a moment of extreme pressure change and is pretty quickly corrected by the system.
