### ISSUE TITLE
You're hit by thrown objects even if you catch them, and here's why.

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#5978]
**Problem Description**:
What is the problem?
You get hit by thrown objects even if you catch them.

**What did you expect to happen**: 
Why do you think this is a bug?
I expected the actions enacted upon me by the thrown object to end at my catching it.

**What happened instead**:
How is what happened different from what you expected?
Once I caught the object, it inflicted damage upon me anyway.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It means that, despite catching thrown objects, they will still damage, embed into and kill players.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Ensure you've got throw toggled on and get something chucked at you.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Gamemode is irrelevant.

**Why does this happen?**
This bug occurs as a result of an object's _Bump()_ proc conflicting with a mob's _hitby()_ proc because of the _throw_at()_ proc. Or maybe it's because of the _Bump()_ proc...
When hit by an object, that object's _Bump()_ proc calls *throw_impact* which then calls _hitby()_ on the mob which causes the mob to catch the thrown object,
Immediately afterward, the _throw_at()_ proc kicks in and calls *throw_impact* again which then calls _hitby()_ on the mob again as well, causing the mob to sustain damage from the item.

**tl;dr:** _The instant a thrown object comes into contact with a mob, the decision making process in the background that determines what happens makes it seem like the mob was hit by two objects, one they catch and one they don't._

**This is shown by the """""debug messages(tm)"""" in the following screenshot.**
_"What the hell, man"_ is displayed when when the _Bump()_ proc is called.
_"Wow, you caught it. What a beast."_ is displayed when the _hitby()_ proc in /code/modules/mob/living/carbon/human/human_defense.dm registers that you caught the object.
_"Why the hell did it continue running..."_ displays when the _hitby()_ proc in /code/modules/mob/living/carbon/human/human_defense.dm registers that you didn't catch the thrown object, and that it'll do damage to the mob that it hit.

![throwhitlogs](https://cloud.githubusercontent.com/assets/12377767/21141153/ae65b6dc-c109-11e6-9f5e-368f76a20209.PNG)

**Comment by KasparoVy** [comment]
Hopefully this proves useful to anyone else trying to sort out this whole throw-catching bug. I got randomly inspired to check these procs and it seems that's what's doing it, funnily enough

**Comment by Fox-McCloud** [comment]
To complicate matters even more, some objects that travel fast enough don't even register when they hit a mob--this is why crossbows are currently broken.

a lot of these issues aren't present in TG, at all---the problem is, however....it's not just a matter of fiixing throwing itself; it requires touching movement, bump, and other code--what a mess.

**Comment by KasparoVy** [comment]
Yeah. I was pretty horrified when I saw just what was involved here, but at least now it's documented
