### ISSUE TITLE
Posibrains can use Me to emote with speakers off

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#5981]
**Problem Description**:
Being able to use me command while speaker is turned off

**What did you expect to happen**: 
error message to show up about speakers being off

**What happened instead**:
the emote went though

**Why is this bad/What are the consequences:**
being able to interact with your surroundings with speakers fof

**Steps to reproduce the problem**:
turn a posibrains speaker off, try to emote as posibrain

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: i was a ghost signed up to be a posibrain that had it speaker off

Not sure if this is meant to be like this, making a bug report just in case it isnt

**Comment by TullyBurnalot** [comment]
Cannot reproduce this one either. Having speakers turned off made me unable to emote as a posibrain.

**Comment by Markolie** [comment]
This can be closed @Fox-McCloud
