### ISSUE TITLE
Nonfunctional Wet Floor sign mines

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#5988]
**Problem Description**:
What is the problem?
The wet floor sign mines do not function anymore
**What did you expect to happen**: 
Just neglect during updates
Why do you think this is a bug?
Well it waste telecrystals and is a dud in any surplus crate
**What happened instead**:
Nothing, they are literally just boring wet floor signs, no booms
How is what happened different from what you expected?
Leg blown off explosions
**Why is this bad/What are the consequences:**
(repeat)  Well it waste telecrystals and is a dud in any surplus crate (I got two from a surplus crate, ate up slots where functional gear could have spawned)
Why do you think this is an important issue?
It takes away a tool that a traitor may use. More importantly its a tele crystal sink to have it in the surplus crate pool of items
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Spawned a surplus crate, had the two wet floor sign bombs. I tried to activate one in hand, there was no indication that it was activated. I set it out in a halway after doing so. Plenty of people ran by, and after two minutes I just picked it up again.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing much more than I was a mime traitor and just got a bad roll on a surplus crate

**Comment by ktoma36** [comment]
~How is what happened different from what you expected?
NO legs blown off explosion

**Comment by AndriiYukhymchak** [comment]
it did some codedigging, you have to be janitor for it to work. I suggest adding the` surplus = 0` flag to it
