### ISSUE TITLE
Unable to complete alien organ manipulation

### ISSUE THREAD

**Issue by Moorden** [ParadiseSS13/Paradise#5989]
**Problem Description**:
Surgery on an alien queen was unable to progress at the manipulate organs step. Saw, cut and retract all worked, but once it was time to manipulate organs, a hemostat would not work.

**What did you expect to happen**: 
Manipulate organs screen pop up to allow organ removal.

**What happened instead**:
Nothing happened.

**Why is this bad/What are the consequences:**
Unable to access alien organs for transplantation prevents a fun but rare event from happening.

**Steps to reproduce the problem**:
Implanted an alien embryo found in the gateway inside a monkey; once the larva hatched, allowed it to become a queen. Once it became queen, killed it and attempted to do an alien organ manipulation surgery on it. The saw, cut, and retract steps were all able to be completed, but trying to manipulate organs with a hemostat did nothing.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by Crazylemon64** [comment]
Duplicate - #5710

**Comment by taukausanake** [comment]
Don't forget #5972 and #5741. Got to keep the tally going!
