### ISSUE TITLE
NanoMachines don't Borg correctly

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#5991]
**Problem Description**:
When you get transformed into a cyborg via nanomachines, your body explodes and the cyborg is formed, but the player doesn't get put in control, becomes invisible to everyone, and speaks from another dimension.

**What did you expect to happen**: 
People to turn into cyborgs.

**What happened instead**:
Robots are braindead, I hear dead people speaking, and they are invisible.

**Why is this bad/What are the consequences:**
This is bad. Fixing this is a pain in the tooshy.

**Steps to reproduce the problem**:
1. Find greytide.
2. Feed nanomachines.
3. After a ritualistic sacrifice resulting in them exploding, a cyborg appears, but is brain dead while dead people talk to us.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Reported over a couple of ahelps, finally remembered to post this.

**Comment by taukausanake** [comment]
Didn't we port over to some other diseases before? The one I didn't care for because no antibodies. Maybe someone forgot to do something with nanomachines because they are treated as a disdease. Else I remember this working at one point but that was a long time ago

**Comment by KasparoVy** [comment]
That's strange. I can recall this working on me a few weeks ago.

**Comment by TullyBurnalot** [comment]
Cannot reproduce. Seems to be working just fine with various methods of ingestion.

**Comment by LightFire53** [comment]
Scrub McNoob can attest that this happened.

**Comment by TullyBurnalot** [comment]
Someone add the Non-Reproducible tag so we can all despair.
