### ISSUE TITLE
Nuke Ops doesn't respect minimum age requirement

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#5992]
**Problem Description**:
Nuke ops can be chosen from new players.

**What did you expect to happen**: 
Robust ops.

**What happened instead**:
Newbie ops.

**Why is this bad/What are the consequences:**
It makes nuke op rounds horribly unbalanced.

**Steps to reproduce the problem**:
Run nuke ops. Observe that new players can be chosen as ops.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Example from Check New Players: BoosieMcHugh/(Bonk Interplanetary Operative #4)(?) (FLW): account is 3 days old

**Comment by Crazylemon64** [comment]
baby ops gogogo

**Comment by jughu** [comment]
I mean everyone needs to learn someday

**Comment by Kyep** [comment]
One person being new isn't a problem. They can learn from the others.

Most of the team being new IS a problem. It leads to things like half the team dying before they reach the station, as they don't know how to spaceproof themselves. I saw that happen the other day.

The team leader being new also results in totally screwed up situations, E.g leader never gives out nuke code, and dies early on, making it impossible for the ops to complete their mission. Or they have never been an op before, so they have no idea how to lead a team, resulting in some truly awful 'planning' sessions.

There should be minimum requirements to play nuke ops, and a higher minimum requirement to play team leader. Alternatively, selection for team leader should be weighted towards more experienced players.

**Comment by jughu** [comment]
we are number one

**Comment by AndriiYukhymchak** [comment]
I had once a NukeOps teamlead that was LITERALLY playing his first game on paradise.

This ridiculousness must be stopped

**Comment by Kyep** [comment]
Closing, as antag role eligibility is now based on playtime, not days since account creation.
