### ISSUE TITLE
Overzealous Banning Code

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#5993]
**Problem Description**:
Banning a player via the Player Panel, and selecting "No" to the IP/CID ban question, still bans their IP/CID.

**What did you expect to happen**: 
The ban to not apply to everyone on their IP/CID.

**What happened instead**:
It applied to everyone on their IP/CID, regardless of the option I selected. In order to ONLY ban their CKEY, I had to do a manual ban instead.

**Why is this bad/What are the consequences:**
It makes the question meaningless. It leads to people being banned who shouldn't be. It is annoying. 

**Steps to reproduce the problem**:
Ban people. You know you want to.

**Comment by tigercat2000** [comment]
It doesn't ban them by IP if you answer "No". It bans them by CID.

**Comment by FlattestGuitar** [comment]
Which it shouldn't for the sake of us being able to apply a ckey-only ban.

Should also ask about the CID.

👉 👉

**Comment by tigercat2000** [comment]
@FlattestGuitar I agree with you, just clarifying the issue report.
