### ISSUE TITLE
Neurotoxin spit is weird

### ISSUE THREAD

**Issue by Wheatley29** [ParadiseSS13/Paradise#5994]
**Problem Description**:
Neurotoxin from a xeno queen refuses to propel one in space.

**What did you expect to happen**: 
Because its basically a reskined taser shot

**What happened instead**:
It didn't.

**Why is this bad/What are the consequences:**
Muh space adventures

**Steps to reproduce the problem**:
Be xeno queen
Space oneself while avoiding the sudden greytide with lasers
Attempt to use neurotoxin spit to return to station
Die.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was a xeno queen

**Comment by taukausanake** [comment]
Probably not a bug? I will agree it is weird

**Comment by jughu** [comment]
Your a giantic alien do think a fat ass bastards spit is gonna push him in the opposite direction?

**Comment by TullyBurnalot** [comment]
Logically speaking, throwing  piece of paper in space when you are barreling at Mach 0.5 should not change your direction as drastically as it does, but alas.

Not sure if it is working as intended, but will... take a look. I guess.
