### ISSUE TITLE
It`s possible to hold a Plant in one hand.

### ISSUE THREAD

**Issue by DadoIs** [ParadiseSS13/Paradise#5997]
**Problem Description**:
It`s possible to hold a Plant in one hand.
**Steps to reproduce the problem**:
**1** Wrap the Plant in Package Wrapper.
**2** Open the Parcel.

**Comment by FreeStylaLT** [comment]
FFFFFFFFFFFFFF

**Comment by DadoIs** [comment]
_**(I don`t know, if it got fixed)**_

**Comment by Spacemanspark** [comment]
Diona, step aside, new plantmen are coming on station!

**Comment by jughu** [comment]
>activate esword
HALP PLANTPOD IS A TRAITOR

**Comment by taukausanake** [comment]
Best solution might be to make plants not wrappable?

**Comment by bgobandit** [comment]
https://github.com/tgstation/tgstation/issues/22378

**Comment by Shadow-Quill** [comment]
Still occurs.
