### ISSUE TITLE
Nonstandarized Walls - Metastation

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#5998]
**Problem Description**:
Nonstandard Walls near escape oods

**What did you expect to happen**: 
Standard Walls

**Why is this bad/What are the consequences:**
Technically, the walls are indestructible. Do with that as you will.

**Steps to reproduce the problem**:
Mapping issue - Escape pod near dorms/Sec Pod Pilot, apparently all escape pods.

**Comment by SamHPurp** [comment]
@Crazylemon64 @Fox-McCloud This can 100% be closed.
