### ISSUE TITLE
Metastation Space Grilles Block LoS

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#5999]
What it says on the tin. Not sure if that's intentional or not. Check near the three layers of grilles by the AI Sat.

**Comment by taukausanake** [comment]
They might have walls under them, grilles act as an extra layer of protection I thought. Could be wrong though

**Comment by Norgad** [comment]
The walls underneath seem intentional, They protect atmos from death by meteor.

**Comment by SamHPurp** [comment]
@Crazylemon64 @Fox-McCloud This can 100% be closed.
