### ISSUE TITLE
MetaStation Chef has no knife

### ISSUE THREAD

**Issue by bubbanitro** [ParadiseSS13/Paradise#6001]
**Problem Description**:
Chef station is missing a kitchen knife, not much a chef can cook without one. 

**What did you expect to happen**: 
A knife is usually on the table

**What happened instead**:
No knife on any of the surfaces, not in backpack or any locker either. 

**Why is this bad/What are the consequences:**
Can't butcher animals, can't cut cheese [haha], can't make cutlets, can't even slice a pizza or a cake!

**Steps to reproduce the problem**:
Just put a kitchen knife on one of the tables, probably the same one with the rolling pin

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Only on Metastation.

**Comment by bubbanitro** [comment]
Another guy notified me that the dinnerware vendor has kitchen knives. CRISIS MILDLY AVERTED. Still it'd be nice to have one knife laying around.

**Comment by Fox-McCloud** [comment]
yeah, this isn't an issue; the vendor has the knives; the only reason there's one on Box is becuase there used to be specific knife requirements to cut things; that's long since been abolished.
