### ISSUE TITLE
Metastation - Particle Accelerator wave goes outside containment zone

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#6008]
Again, what it says on the tin.

**Comment by Fox-McCloud** [comment]
Could you be more descriptive here? I'm really not sure if what you're describing is necessarily even a problem

**Comment by SigholtStarsong** [comment]
Sure. The particle wave that is generated goes about two tiles past the reinforced wall that is at Containment on Metastation.

**Comment by Twinmold93** [comment]
This is not just MetaStation, but Cyberiad, too, when the PA is set to power level 2. It's because the PA wave is not stopped by walls, hence it just keeps going (exactly 2 additional tiles passed the wall on Cyberiad on level 2).

**Comment by taukausanake** [comment]
Decreasing the distance would be the answer if it is an issue that the particle waves are going too far, but these are particle waves. They shouldn't be stopped by anything. All else you would imagine the singularity would eat them but I guess they are effects and not really affected by anything

**Comment by tigercat2000** [comment]
the real answer is "this isn't a bug"

**Comment by taukausanake** [comment]
Can we weaponize particle accelerators? I only know the shield generators hurt. What about the particles? I would imagine if they pass through walls without damaging then the same would go for other things but I can always hope. Damn you, Science

**Comment by SamHPurp** [comment]
@Crazylemon64 @Fox-McCloud I believe this can be closed.
