### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by Brasnak** [ParadiseSS13/Paradise#6015]
**Problem Description**:
What is the problem?
If you take a photo of someone carrying a plant, the photo shows the person, not the plant
**What did you expect to happen**: 
Why do you think this is a bug?
Because it is not showing the plant, the person is holding
**What happened instead**:
How is what happened different from what you expected?
You see the person instead
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
If someone tries stealth using a plant, a camera could spot him.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Pick up a camera, shoot a photo of a person holding a plant.

![bug](https://cloud.githubusercontent.com/assets/9626555/21395316/54cd0b18-c79c-11e6-835b-190f5e2328b6.png)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by KasparoVy** [comment]
This issue is a result of a lack of alternate appearance handling in the building of camera snapshots [here](https://github.com/ParadiseSS13/Paradise/blob/18f4aa18b98fcf8503f7173d3e294d581aa2acff/code/modules/paperwork/photography.dm)

Relevant PRs are https://github.com/ParadiseSS13/Paradise/pull/4115 and https://github.com/ParadiseSS13/Paradise/pull/4759

**Comment by tigercat2000** [comment]
feature:tm:

**Comment by taukausanake** [comment]
I would rather the plant appear as an overlay on the person so that it can partially see through the appearance. Would that be possible instead? Might require a little more work

**Comment by KasparoVy** [comment]
Another issue I found was that cameras can grant you ghetto x-ray vision in the sense that you can take pictures of mobs/stuff through walls.
