### ISSUE TITLE
pAI UI menus are fucked

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6023]
**Problem Description**:
https://youtu.be/uY9NuJD_0t4
My video should pretty much explain it.

**What did you expect to happen**: 
For everything not to break into little pieces (up to and including my synthetic heart).

**What happened instead**:
Everything broke into little fucking pieces.

**Why is this bad/What are the consequences:**
This may or may not be causing the server to freak out when this occurs. Not sure, admins aren't sure.
That, and I can't use half the features of the pAI.

**Steps to reproduce the problem**:
Be a pAI.
Get a program that requires a UI element to use (Door jack or PDA messenger for example).
Sometimes, the program will automatically open up and freak out immediately.
Other times, you open it yourself and it goes haywire then.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: ¯\_(ツ)_/¯

**Comment by Very-Soft** [comment]
Having played with the pAI a bunch to see what works and what doesn't and all that, I can confirm that the problems are consistant for me in that the interface elements for the pAI seem to get locked into a refreshing reload loop, that seems to get worse the longer you use it, to the point that I have noticed a distinct connection between server lagspikes and my using the pAI interface to do anything after enough time has passed. Anything that requires any of the secondary menu windows, such as the crew manifest, digital messenger, or host bioscan do not finish loading correctly, and closing their windows, and then interacting with the main interface window again causes all of the pAI interface elements you have interacted with to open again. The more of them that open, the worse the problems are for the server.

One can still use the AI PM tab thing in the right menu to send PDA messages, and there are a few other features that can be used without using the pAI menu, passed purchasing and activating them on the pain pAI menu. Just, anything beyond that is fuxd

**Comment by Crazylemon64** [comment]
I suspect https://github.com/ParadiseSS13/Paradise/pull/5986 may have introduced this, as it was a major UI-related change made just before this issue was opened. Inspecting now.

**Comment by Crazylemon64** [comment]
Given that this seems to cause repeated increasing processing, substantially hurting performance, this seems like a rather important bug to fix
