### ISSUE TITLE
Noir sunglasses are acting silly.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6024]
**Problem Description**:
I can activate noir mode, put down the sunglasses, move away, and still be on noir mode.

**What did you expect to happen**: 
Not to have noir mode when my noir glasses aren't on my person

**What happened instead**:
Life becomes black and white forever.

**Why is this bad/What are the consequences:**
Well, I mean, it's not that big of a deal.

**Steps to reproduce the problem**:
Activate noir mode on sunglasses
Put glasses down
laugh.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: ¯\_(ツ)_/¯

**Comment by jughu** [comment]
Crippling depression
