### ISSUE TITLE
diona nymphs die from lack of oxygen in a space pod

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#6028]
**Problem Description**:
What is the problem?
diona nymphs die from lack of oxygen in a space pod

**What did you expect to happen**: 
Why do you think this is a bug?
The spacepod had oxygen

**What happened instead**:
How is what happened different from what you expected?
I expected For them not to die of oxygen deprevation in a spacepod

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Not a high priority issue, but def a bug.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Be a diona nymph, be in someone's possesion, have them get in a space pod and fly into spac.e

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Flying in space.

**Comment by TullyBurnalot** [comment]
Pods actually have a setting that does not draw oxygen from an internal tank, which means the occupants of the pod MUST have some sort of internals.

Are you certain that the pod was not set to that mode?

**Comment by DesolateG** [comment]
Yes

**Comment by LightFire53** [comment]
Are we sure it was oxygen loss and not lack of light?

**Comment by DesolateG** [comment]
Flashing O2 symbol.

On Jan 16, 2017 11:53 PM, "LightFire53" <notifications@github.com> wrote:

Are we sure it was oxygen loss and not lack of light?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ParadiseSS13/Paradise/issues/6028#issuecomment-273028898>,
or mute the thread
