### ISSUE TITLE
AI can remove paper from fax machines and teleport them to the core

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#6029]
**Problem Description**:
The AI can remove Fax Machine papers, which places the paper underneath the core

**What did you expect to happen**: 
For the paper to merely eject, not teleport

**Why is this bad/What are the consequences:**
The AI, should it choose to abuse this bug, can make faxing practically impossible.

**Steps to reproduce the problem**:
Be AI, click Long Range fax machine, eject paper. Check under core.

Reported initially to Mhelp by Alex6511.

**Comment by taukausanake** [comment]
I blame bluespace
