### ISSUE TITLE
Cloners can produce braindead clones of SSD players

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#6030]
**Problem Description**:
If you cryo then ghost, after being scanned by an autoprocess cloner, it can create a braindead clone of you against your wishes.

**What did you expect to happen**: 
Upon cryoing and ghosting out (long term storage), the character's record should be deleted from all cloning consoles that have it.

**What happened instead**:
They kept the record, and immediately cloned the character.

**Why is this bad/What are the consequences:**
Characters can be cloned against their players' wishes, sometimes even without their knowledge. This results in braindead clones.

**Steps to reproduce the problem**:
1. Get scanned in an autoprocess cloner
2. Go cryo and ghost out.
3. Wait a few minutes - a clone will be created for you even though you deliberately left the round

**Comment by Crazylemon64** [comment]
"We at Nanotrasen would like you to know that our cryogenic preservation technology is 100% reliable, with no reported incidents of horrific mutations or loss of life. Have a secure day!"

**Comment by taukausanake** [comment]
I always wondered why you couldn't just make braindead clones of yourself, aside from game balancing. What if I want to have a meatsack of myself to play dress up with? Or fake my own death? Or play the ultimate game of hide and seek. Or kidnap someone and fake their own death? Come on, there are so many things you can do with this!

**Comment by Crazylemon64** [comment]
Yeah, I think the ability to make braindead clones out of dna data would be a neat thing to have. But auto-cloning people who get taken away via cryo is definitely anomalous!

**Comment by taukausanake** [comment]
I somehow get the cryotubes and cryo sleepers confused so just to make sure these are the sleepers, correct? You're supposed to logout after ghosting in one of those I thought

**Comment by TullyBurnalot** [comment]
Cannot reproduce with steps provided, cloning pod never started.

@taukausanake Was this an immediate reaction to ghosting, or a delayed reaction

**Comment by taukausanake** [comment]
@TullyBurnalot I don't know, I was asking if this was sleepers or tubes. It sounds like you are ghosting while in a cryotube and then you get your body into a cloner. That shouldn't happen though because you need to be in your body to actually clone. Else maybe @Kyep got the cloner and cryo mixed up??

**Comment by TullyBurnalot** [comment]
Oh, derp, I thought you were the OP. @Kyep

**Comment by Kyep** [comment]
@TullyBurnalot it took a few minutes.
