### ISSUE TITLE
Getting knocked down in the engineering shuttle even tho you are buckled to a chair.

### ISSUE THREAD

**Issue by Knivarn** [ParadiseSS13/Paradise#6031]
**Problem Description**:
You get knocked down on the engineering shuttle when you leave and when you dock even when you are buckled to a chair.

**What did you expect to happen**: 
Not get knocked down because I was smart enough to buckle myself into a chair.
Also it didn't work like this before.

**What happened instead**:
I got knocked down, then I got sad.

**Why is this bad/What are the consequences:**
Not really important since the stun is so short, but it's annoying and it didn't use to work like that.

**Steps to reproduce the problem**:
Go on the engineering shuttle, then go on the computer and leave for either the outpost or back to the station. You will then proceed to get knocked down on the floor even tho you are buckled into a chair.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
![skarmklipp 2016-12-24 17 14 26](https://cloud.githubusercontent.com/assets/14307430/21467911/37b7a322-c9fd-11e6-91ab-5d791cbef1f3.png)
Pay attention to the chat log. I suppose it could be edited but it shouldn't be any problem reproducing it.

**Comment by jughu** [comment]
The chairs are auctally just painted on the ground and your trying to be a mime

**Comment by Crazylemon64** [comment]
#5414 will fix this by bringing over -tg-'s `onShuttleMove`

**Comment by Shadow-Quill** [comment]
@Fox-McCloud Fixed.

**Comment by Knivarn** [comment]
For 3 years I waited for this change /s
Closing it up.
