### ISSUE TITLE
Turbine breaks from high pressure (and science upgrades)

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#6033]
**Problem Description**:
Ive posted a year back a turbine bug [#2746](https://github.com/ParadiseSS13/Paradise/issues/2746) and this I assume is related. If you give the turbine too much pressure/power it drops to 0 RPM 0 Watts. It happens just the same from both upgrading the burn chamber and from upgrading the components in it.

**What did you expect to happen**: 
The turbine to produce more power from being upgraded and more power from having an improved burn chamber.

**What happened instead**:
It stalls out and produces zero power with even minor upgrades. Level 2-3 science upgrades can break the default design so it stalls out, adding an extra injector or just moving the injector back so it burns more of the gasses causes it to stall out (possibly via overpressure?)

**Why is this bad/What are the consequences:**
Turbine is useless and can't be upgraded or modified.

**Steps to reproduce the problem**:
Either upgrade it with science components or add an extra injector to increase burn rate/pressure.

I had hoped this would get fixed when the TEG got fixed [here](https://github.com/ParadiseSS13/Paradise/issues/1850) but the turbine got overlooked. Now turbine has been sitting by being useless and occasionally pissing me off when I do try to use it and end up breaking it with no effort.

**Comment by Taaketa** [comment]
@Crazylemon64 @Fox-McCloud  This is a duplicate report as linked within the report. Probably close this one as the older one has more referenced work against it.

**Comment by DesolateG** [comment]
fixed by #8132 can be closed

**Comment by Shadow-Quill** [comment]
@Fox-McCloud Fixed.
