### ISSUE TITLE
Where is the Earth shattering kaboom?

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6047]
**Problem Description**:
The nuke count down stops when the AI shunts to an APC

**What did you expect to happen**: 
The count down to my earth shattering kaboom should continue.

**What happened instead**:
Count down stopped, and the security code moved to red.

**Why is this bad/What are the consequences:**
It kinda screws the AI out of the "Nuke the station" objective by using an ability.

**Steps to reproduce the problem**:
1. Role AI
2. Call that code delta
3. After losing all borgs, your heavily fortified sat gets breached.
4. To escape imminent destruction from filthy organics to die in cleansing nuclear radiation, shunt to the nearest APC.
5. Cry as the nuke disarms.

Other info: It could be a weird bug that he died and shunted at the same time, but not sure.

**Comment by Alexshreds** [comment]
The countdown only stops of the AI core is destroyed, regardless of whether you shunted or not. Otherwise, i'm fairly certain this is working as intended...

**Comment by tigercat2000** [comment]
Definitely not. If the AI successfully finishes shunting, the countdown should continue, regardless of what happens to their old core. That's, like, the entire point of shunting 😛

**Comment by Alexshreds** [comment]
Well, as long as everyone is okay with teleporting nuclear doomsday devices into apcs.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Actually, the doomsday device is meant to be tied to the AI core; it was one of the things that was specifically changed when malf AI was rolled into traitor AI---the only potential bug here, that needs to be pinned down, is if shunting automatically stops the doomsday device, or if it was a coincidence that the shunting and destruction of the AI core took place at the same time.

**Comment by Alexshreds** [comment]
I've tested it myself and it must have just been a coincidence because shunting != qdel(doomsday_device)

**Comment by Shadow-Quill** [comment]
@Fox-McCloud Couldn't reproduce.
