### ISSUE TITLE
Cyborg Mesons Don't Work

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6057]
**Problem Description**:
Cyborg Mesons don't work. At all.

**What did you expect to happen**: 
I expected meson vision.

**What happened instead**:
Nothing. No visual changes occurred.

**Why is this bad/What are the consequences:**
It nullifies the mining cyborg.

**Steps to reproduce the problem**:
1. Spawn Cyborg
2. Become one with Synthetica
3. Select Mining Module
3a. Select Engineering Module
4. Apply Mesons.
5. Cry.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This form has some really redundant questions on it...

**Comment by Davdichan** [comment]
Why hasn't Mesons just become an activatable ability like flashlight by now? Doesn't seem to be a good reason why they need to select the item/why it isn't on all the time or toggleable from the HUD/Cyborg Tab.

**Comment by LightFire53** [comment]
@davdichan because not all borgs need it, honestly. Mediborgs would have no reason for it, it is kinda unfair to give a sec borg one for any antag, service doesn't need it.

**Comment by Davdichan** [comment]
@LightFire53 Why do all borgs need Medical and Security HUDs? And why don't borgs have Diagnostic HUD? Given how other overlays are treated Miner and Engineering borg should have an always on Meson or toggleable version, having to use one of their modules to do it is just poor design, imagine if we went back to Sec borgs needing to hold a hud in their hand just to see wanted criminals.
