### ISSUE TITLE
Graffiti does not leave fingerprints

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#6059]
**Problem Description**:
Writing a graffiti letter on the floor in crayon leaves no admin-visible fingerprint that admins could use to find out who wrote it.

**What did you expect to happen**: 
I expected there to be an invisible fingerprint that admins can use to find out who wrote it.

**What happened instead**:
There was no fingerprint.

**Why is this bad/What are the consequences:**
People can write whatever they want in graffiti and admins have no way to find out who did it.

**Steps to reproduce the problem**:
1) Write something on the floor in crayon
2) VV -> no fingerprint

**Comment by FlattestGuitar** [comment]
I have a feeling this is one of these things we shouldn't keep on out GitHub.
