### ISSUE TITLE
The Anita hairstyle has some grey pixels

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#6063]
~~Muh speshul snowflek copyright Entchtut-only hairstyle~~ The Anita hairstyle has some grey pixels at the top in the side view and back view.

![](https://i.gyazo.com/c6a55112559bdbf0334f9fdcb2a4b3fc.png) ![](https://i.gyazo.com/9d83d4190ff0265da0201e253780a0f1.png)

And in case that wasn't enough, here they are, changed to hot pink.

![](https://i.gyazo.com/a2efb9fbd64f00fef94c1720d8f94a3e.png) ![](https://i.gyazo.com/fdd098409bceb7d378e46b26daef50d0.png)

**Comment by KasparoVy** [comment]
Woops. That's what I get for not cross-referencing with alpha view. Fix on the way.
