### ISSUE TITLE
Staff of Death does not kill IPCs

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#6068]
**Problem Description**:
getting hit with a staff of death does not cause IPC to die, it merely damages their chest and causes their head to detach

**What did you expect to happen**: 
I to die from getting hit with it

**What happened instead**:
I lived with a damaged chest and detached head

**Why is this bad/What are the consequences:**
it's inconsistent how the staff behaves with other species

**Steps to reproduce the problem**:
Spawn an IPC, shoot with bolt of death

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was stunned with FORTI GY AMA first and rested after it and before getting hit by death, I also had pAI unfolded on my head

**Comment by BiberDark** [comment]
An IPC is not an organic lifeform, so he cant die like one. I think this is intended. Does a staff of life work ?

**Comment by Spacemanspark** [comment]
This is not intentional and something we've tried to fix multiple times.

**Comment by Rumiluntti** [comment]
It's broken again?!

**Comment by Fox-McCloud** [comment]
>An IPC is not an organic lifeform, so he cant die like one. I think this is intended

It's not intended and it should absolutely kill them.

Magic gives no shits if you're organic or synthetic;; it's freaking magic.
