### ISSUE TITLE
Mounted sleepers slowly poison Vox

### ISSUE THREAD

**Issue by Krausus** [ParadiseSS13/Paradise#607]
A feature of the Odysseus' mounted sleepers is that they inject a steady supply of inaprovaline into anyone inside of them, as coded [here](https://github.com/ParadiseSS13/Paradise/blob/c218c1af3b6c80b6084be13e7f077bcbb8a691e0/code/game/mecha/equipment/tools/medical_tools.dm#L230-L231):
```
if(M.reagents.get_reagent_amount("inaprovaline") < 5)
	M.reagents.add_reagent("inaprovaline", 5)
```
Unfortunately, the mounted sleeper doesn't care whether inaprovaline is toxic to the person inside, and there's no way to disable the automatic injection, so loading a Vox into a mounted sleeper will slowly poison them until they're ejected.

**Comment by Markolie** [comment]
Not really a bug I'm afraid: you'll have to post it on the forums.

**Comment by Krausus** [comment]
Not a bug, sure, but could this not be considered an oversight? Mounted sleepers are intended to stabilize people inside of them, and there was a time where inaprovaline would do that without harming anyone, so it made sense to simply inject it. The appropriateness of inaprovaline changed, but the mounted sleeper didn't.

They already apply several non-chemical effects - they [directly remove oxygen damage, stunning, weakening, and stunning (a second time)](https://github.com/ParadiseSS13/Paradise/blob/c218c1af3b6c80b6084be13e7f077bcbb8a691e0/code/game/mecha/equipment/tools/medical_tools.dm#L224-L229) - so perhaps they should directly remove breath loss like inaprovaline does? Or would that still be a feature request?

**Comment by Markolie** [comment]
It's a lot like cloners and cryo - Vox simply require different medical solutions. If we'd add this, cloners shouldn't inject inaprovaline to Vox either.

**Comment by Krausus** [comment]
Fair enough. I'd argue that the injection of inaprovaline should probably at least be mentioned in some manner, but that's not really issue-worthy. Oh well.

**Comment by Fox-McCloud** [comment]
@Krausus 

Inaprov is injected largely to keep people stable as it prevents losebreath---except Vox's special snowflake nature make them take tox from any O2 or O2-derived medicine. Removing inaprov from mounted sleepers and the cloner just because one race can't use it is not a good idea.

**Comment by Krausus** [comment]
Of course. I wasn't suggesting that the mounted sleepers should stop stabilizing, and didn't even know cloners injected inaprovaline (not that it should matter to an uncloneable race). The real issue is that the mounted sleepers' inaprovaline injections aren't mentioned anywhere, so it's something one would only learn through word of mouth or noticing they accidentally poisoned a Vox. Seemed like it probably wasn't intended to do the whole "surprise poison" thing, though fixing that would require adding a new "don't inject inaprovaline" feature, I guess. Not really even worth the trouble, considering how often mounted sleepers actually get used.
