### ISSUE TITLE
pAI can set status in security records, when they shouldn't be able to

### ISSUE THREAD

**Issue by Very-Soft** [ParadiseSS13/Paradise#6071]
**Problem Description**:
What is the problem?

pAI are able to set the alive/dead/ssd status of crew, when records are supposed to be read only to them

**What did you expect to happen**: 
Why do you think this is a bug?

I expected to not be able to adjust the records

**What happened instead**:
How is what happened different from what you expected?

I adjusted the records

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

It could make pAIs rather useful to antags in ways they aren't supposed to be

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Purchase the security records software, shift click to inspect someone, click the link to their status records when it comes up, adjust as you see fit.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Didn't appear to be related to the gamemode or any special circumstances.
This might also work with buying the medical records? I wasn't able to test it, but I believe they have similar function.

(edit) Actually, am playing pAI again, and the ability to do this through the shift click inspecting seems to display all the records without needing to purchase them. And playing with it a little, it appears I am able to edit the wanted status of people as well. I cannot add comments to the security or medical records however.

**Comment by Spacemanspark** [comment]
Pretty sure this was brought up before I left, and nobody had an issue with it at the time.
The ability has been sitting around here for months, probably almost a year.

**Comment by Very-Soft** [comment]
Actually, am playing pAI again, and the ability to do this through the shift click inspecting seems to display all the records without needing to purchase them. ( I'll edit this into the bug report)
