### ISSUE TITLE
Cannot access camera list as latejoin AI

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#6072]
**Problem Description**:
Attempting to browse camera list as latejoin AI causes runtimes.

**What did you expect to happen**: 
A) To get the camera list
B) Not to get a runtime

**What happened instead**:
I got a runtime, and no camera list

**Why is this bad/What are the consequences:**
AIs cannot see camera status, nor can they jump to cameras on offgrid locations (telecomms, sci outpost, etc)

**Steps to reproduce the problem**:
Be latejoin AI.
Click camera list button (second from left on blue button row)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
[03:14:14] Runtime in tracking.dm,29: Cannot read 0.len
   proc name: get camera list (/mob/living/silicon/ai/proc/get_camera_list)
   usr: MYCHARNAME (MYCKEY) (/mob/living/silicon/ai)
   usr.loc: The floor (143,23,1) (/turf/simulated/floor/bluegrid)
   src: MYCHARNAME (/mob/living/silicon/ai)
   src.loc: the floor (143,23,1) (/turf/simulated/floor/bluegrid)
   call stack:
   MYCHARNAME  (/mob/living/silicon/ai): get camera list()
   Show Camera List (/obj/screen/ai/camera_list): Click(null, "mapwindow.map", "icon-x=20;icon-y=22;left=1;scr...")

**Comment by KasparoVy** [comment]
Thanks for the in depth report
