### ISSUE TITLE
Canceling Cult Finale Rune at the "My life for" Prompt still Draws the Rune

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#6080]
**Problem Description**:
When you select to draw the rune "Tear Reality (God)" or "Call Forth The Slaughter (Demons)", and then decide to cancle, you get the message for it, but still draw the rune. It also says "My Life for Nar-Sie!" for fire cultists

**What did you expect to happen**: 
The runes not to get drawn, and a fire cultist saying "My Life for Pyr'Kaeus"

**What happened instead**:
The rune got drawn.

**Why is this bad/What are the consequences:**
Besides costing time to revert what the wrong selected rune did without activating it, you do break your bone of the limb that gets selected for the dammage from the rune drawing

**Steps to reproduce the problem**:
Be cultist, take book, scribe rune, select God or Demons, cancel, don't cancel with it, break a bodypart.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was on a test server, gamemode originally was extended.

**Comment by Markolie** [comment]
@Aurorablade

**Comment by Crazylemon64** [comment]
You take the damage *before* you finish scribing the rune.

**Comment by Crazylemon64** [comment]
However, the cult god name thing is an oversight. Report that separately.

**Comment by MarsM0nd** [comment]
Well, my problem was that the popup that comes is as follows:
Are you prepared for the final battle?
This is the FINAL step to summon your dietys power, it is a long, painful ritual and the crew will be alerted to your presence
My life for Nar-Sie!       No
Selecting No still draws the rune.

**Comment by Crazylemon64** [comment]
Ah, then. Concise description is important. I'll re-open this, then, with a more exact title.

**Comment by Crazylemon64** [comment]
(There should be an else block here that breaks out of the function)[https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/cult/ritual.dm#L266-L275]
