### ISSUE TITLE
Cult swords can't be sharpened

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#6082]
**Problem Description**:
Trying to sharpen the sacrificial dagger made on the altar/the cult blade with the (eldritch) whetstone doesn't work.

**What did you expect to happen**: 
Getting a sharpened dagger/sword

**What happened instead**:
I only get the message "You can only sharpen items that are already sharp, such as knives." on the eldritch whetstone, also on the normal with the dagger, the sword would be to powerfull for the normal whetstone

**Why is this bad/What are the consequences:**
The eldritch whetstone seems pointless.

**Steps to reproduce the problem**:
Be cultist, make an altar, select cultist dagger/eldritch whetstone, try to sharpen it/a cult blade.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Testing on a local server, gamemode originally was extended.

**Comment by Fox-McCloud** [comment]
@Aurorablade 

the cult sword probably needs its sharp and edge vars both set to 1.
