### ISSUE TITLE
Missing icon for the empowered cultist robe

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#6083]
**Problem Description**:
When you toggle the hoodie of the empowered cultist robe, it doesn't have an inventory sprite/icon

**What did you expect to happen**: 
The icon to stay/slightly change

**What happened instead**:
The icon disappeared.

**Why is this bad/What are the consequences:**
Minor sprite bug, might confuse people.

**Steps to reproduce the problem**:
Be cultist, make a daemon forge, select shielded robe, wear it, toggle hood.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Testing on a local server, gamemode was extended.

**Comment by StreakyHaddock** [comment]
I can't seem to be able to reproduce this bug. Both the hood and the hood's inventory icon both seem to remain no matter what species I am. At some point, this must have been fixed, either intentionally or incidentally.

**Comment by Kyep** [comment]
@AffectedArc07 Tested, no longer applies, issue can be closed.
