### ISSUE TITLE
Talisman of Arming doesn't give boots/drops sword

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#6084]
**Problem Description**:
When you use the Talisman of Arming, the sword spawns on the ground, and you don't get the cultboots even if you aren't wearing any boots.

**What did you expect to happen**: 
That the Talisman of Arming works like the old talisman, where you did get boots if you didn't had any, and the sword was spawned in your active hand, replacing the talisman. The tome refers to the boots through the more informations selection, so you would expect to get them.

**What happened instead**:
The sword gets dropped, the bolas spawn in your offhand, no boots.

**Why is this bad/What are the consequences:**
You can't quickly draw the sword from the paper as you were used to be. 

**Steps to reproduce the problem**:
Be cult, make Rite of Binding, select Talisman of Arming.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Local test server, gamemode was extended.

**Comment by Aurorablade** [comment]
There were never cult shoes so nothing ead removed there

**Comment by MarsM0nd** [comment]
Cult boots do exist, and i did use them with the old cult, though they never were really seen, since no one did take off their boots before getting the robe/sword and maybe the backpack. They also get referenced by the tome, it's just a very minor issue, most people probably wouldn't realized it. And sorry for all the issues on your PR, i kinda like cult, so i did test it a good bit, also to prepare for mhelps about it.

**Comment by Aurorablade** [comment]
then i don't know where the boots would be in the old code cuase i looked on the old tailisman and no boots WERE EVER equiped...in the code..I swear i double checked i could be wrong but i checked myself there. but i will fix the rest of it.
