### ISSUE TITLE
The big-ass god summoning rune doesn't work.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#6088]
Just a regular newcult round, nine regular, living, non-ghost, cultist people standing on the rune. It didn't work, I had to call in an emergency Nar'Sie.

Glad I had him in my contacts.

**Comment by SamHPurp** [comment]
Was the summoner that shift, Everything was done as it should. There was nothing particularly goofy about our setup... or any additional context I can provide.

**Comment by Crazylemon64** [comment]
I've seen this working, since.

**Comment by SamHPurp** [comment]
@Crazylemon64 One of the PRs not long after fixed it, but I assume didn't reference this issue number.
