### ISSUE TITLE
The "sacrifice X" objective won't change its target after the target goes to cryo.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#6090]
What it says in the title. I'm not sure what the behaviour is if the target dies or gets gibbed in a different manner, but that's also worth looking into.

**Comment by Aurorablade** [comment]
it did that in old cult too...

**Comment by FlattestGuitar** [comment]
Duplicate of #4635, but I was hoping you'd take care of this one, since we have this new cult thing and all....
❤️

**Comment by Aurorablade** [comment]
I DIDN'T SAY I WASN'T FIXING IT REOPEN IT!
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by FlattestGuitar** [comment]
![](http://i.imgur.com/Em2Xkqr.png)

A CODER ASKED

**Comment by Spacemanspark** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Aurorablade** [comment]
I may have to put off this fix for a bit..i am frusterating myself with it...we need datum antags...

**Comment by SamHPurp** [comment]
This is fixed by #6987 

Can be closed?
