### ISSUE TITLE
You can resist the lures of acendant fire god by sitting in a recharger

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#6091]
**Problem Description**:
You can literally sit inside the risen Pyr'Kaeus as a borg as long as you are inside a recharger. It popped me instantly when I left

**What did you expect to happen**: 
I was kind of expecting for it to pop me and turn me into a fire thingmabob even inside the thing

**What happened instead**:
It didn't pop me!

**Why is this bad/What are the consequences:**
You can sit inside a god, because you are in a recharger. It's not too reasonable.

**Steps to reproduce the problem**:
Be borg, sit in recharger minding your own business, make Pyr'Kaeus rise and skidaddle right on top of you.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Cult round

**Comment by tigercat2000** [comment]
not really a bug? you're inside a container, it can't detect you on the turf, and it doesn't destroy objects
