### ISSUE TITLE
Drawing the Nar'Sie summoning rune doesn't warn the station.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#6093]
As the title says. Code seems to indicate that's what should be happening, but it doesn't happen.

👉 👉

**Comment by Alexshreds** [comment]
Where does it indicate this?

**Comment by SamHPurp** [comment]
Is it designed to warn the entire station? That seems a little goofy.

Anyone within eyeshot get a super obvious message for that rune in particular.

**Comment by improvedname** [comment]
Yeaah its supposed to warn the station for the location of the summoning for a lqst resort of sec

**Comment by SamHPurp** [comment]
@Crazylemon64 afaik this has been fixed.

**Comment by SabreML** [comment]
Definitely fixed by #14516.

**Comment by AffectedArc07** [comment]
Fixed since cult overhaul
