### ISSUE TITLE
Medical Cyborgs can't scan Unknowns

### ISSUE THREAD

**Issue by Onutsio** [ParadiseSS13/Paradise#6112]
**Problem Description**:
Medical cyborgs can't use their modules on Unknown people. 

**What did you expect to happen**: 
Being able to perform surgery/medical scan someone who was unknown

**What happened instead**:
Wasn't able to do so

**Why is this bad/What are the consequences:**
Medical Cyborgs can get stunted in treatment, being unable to aid anyone who fits the 'trigger' of this issue.

**Steps to reproduce the problem**:
Be medical cyborg, try to perform surgery or scan a unknown.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This bug seems rather iffy on its triggers. So, I'm not 100% sure if it's just the Unknown status doing it, or something else.

**Comment by Crazylemon64** [comment]
"Cannot use" as in... Is there a message given? Are you using the standard cyborg diagnoser? Can you provide a screenshot of the patient that cannot be scanned?

**Comment by Onutsio** [comment]
There isn't a message given at all. It just outright refuses to scan them. I'll try to get a picture of a example patient shortly.

**Comment by Onutsio** [comment]
![capture](https://cloud.githubusercontent.com/assets/24982730/21746740/bc254cb0-d51d-11e6-8921-f17bcaba64e9.PNG)
![capture1](https://cloud.githubusercontent.com/assets/24982730/21746741/be403690-d51d-11e6-9e66-35985e7480cf.PNG)
A example, from the Morgue. Though this also affects the living

**Comment by Fox-McCloud** [comment]
What do you mean by scan? As in...health analyzer scan or trying to add/alter medical records?

**Comment by Onutsio** [comment]
A health analyzer. Or use any of their modules on them, for that matter.

**Comment by Crazylemon64** [comment]
And you are able to use your modules on living people, too? Just to be certain?

**Comment by Onutsio** [comment]
They seem to work on most living people, but not on anyone who's Unknown. Living or dead.

**Comment by Crazylemon64** [comment]
That sounds like a runtime - though in that case, I wonder why it would work for humans.

**Comment by TullyBurnalot** [comment]
Cannot reproduce, seems to be working just fine on Husked/Disfigured Unknowns.
