### ISSUE TITLE
Shadowling Ascension heats broken bulbs!

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#6116]
**Problem Description**:
Lights that are broken by Shadowling ascension are too hot too touch

**What did you expect to happen**: 
Be able to remove broken bulb, and replace it.

**What happened instead**:
I couldn't replace the bulbs.

**Why is this bad/What are the consequences:**
Because light is right!

**Steps to reproduce the problem**:
Ascend slings, attempt to replace broken bulb without gloves, fail.

**Comment by TullyBurnalot** [comment]
Cannot reproduce. Ascended, broke a veritable ton of bulbs, could freely remove them without gloves.

**Comment by SigholtStarsong** [comment]
I was on the science outpost at the time.

**Comment by TullyBurnalot** [comment]
Tried it on the Science Outpost after ascension, still cannot reproduce.

**Comment by SigholtStarsong** [comment]
Try with latex gloves, I was wearing those.

**Comment by improvedname** [comment]
Latex gloves arent fireproof gloves
