### ISSUE TITLE
simple_animals have no cooldown when attacking mechs

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#6122]
**Problem Description**:
Simple animals can spam attacks on mechs with no cooldown, leading to even meek simple animals being able to solo mechs in seconds, and produce a shower of sparks.

**What did you expect to happen**: 
Simple_animals should not be able to attack mechs faster than they can attack mobs.

**What happened instead**:
They can attack as fast as they can click (or use a macro to click) no cooldown or safety.

**Why is this bad/What are the consequences:**
As above.

**Steps to reproduce the problem**:
Spawn a mech.
Spawn a simple animal.
Spam-click the mech as the simple_animal.

**Comment by Crazylemon64** [comment]
https://www.youtube.com/watch?v=ifSr0XPi8pw
