### ISSUE TITLE
Cheese is inedible

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#6140]
Caused by a `metabolization_rate` of 0, which means that a division by 0 occurs when attempting to eat it.

**Comment by Crazylemon64** [comment]
```

	if(istype(toEat, /obj/item/weapon/reagent_containers/food/snacks))
		for(var/datum/reagent/consumable/C in reagents.reagent_list) //we add the nutrition value of what we're currently digesting
			fullness += C.nutriment_factor * C.volume / C.metabolization_rate
```

**Comment by WhiteHusky** [comment]
Also noticed this.
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/food_and_drinks/food/snacks.dm#L1853-L1857

**Comment by Crazylemon64** [comment]
Well, slicing code *should* handle divvying up the cheese in the parent wheel... but directly spawning them in is going to lead to empty food
