### ISSUE TITLE
Karma notification preference is broken.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6142]
**Problem Description**:
The karma notification preference is busted, and thus it always pops up after the end of each round.

**What did you expect to happen**: 
It shouldn't pop up

**What happened instead**:
I had to fill out another one of these annoying templates

**Why is this bad/What are the consequences:**
The template is obnoxious.
That, and sometimes I want the karma notification to pop up, and sometimes I don't. REEEEEEEEEEEEEEEEEEEEEEEEEEE

**Steps to reproduce the problem**:
Can I skip this part?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: AHHHHHHHHHHH

**Comment by Lady-Luck** [comment]
YOU CAN HAVE IT ALL

MY EMPIRE OF DIRT
