### ISSUE TITLE
Gateway is borked

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6154]
**Problem Description**:
Gateway doesn't activate, says "Error: No destination available" @FalseIncarnate 

**What did you expect to happen**: 
Exploration of the gateway.

**What happened instead**:
I had to smack my head against the desk as I filled out this template.

**Why is this bad/What are the consequences:**
I have a headache/ can't explore the gateway.

**Steps to reproduce the problem**:
-Open Github
-Go to "report issue"
-Realize this annoying template still exists
-Slam head against desk

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: REEEEEEEEEEEEEEEEEEEEEE

**Comment by Crazylemon64** [comment]
@Spacemanspark It's because away missions (particularly the beach) were failing to load mid-way through. This has since been fixed by #6153

**Comment by Spacemanspark** [comment]
Well fuck
