### ISSUE TITLE
Duel-port air vents [BUG]

### ISSUE THREAD

**Issue by Codydozer** [ParadiseSS13/Paradise#6168]
**Problem Description**:
Can't remove them from Plating.

**What did you expect to happen**: 
They aren't able to be removed.

**What happened instead**:
Everything else is something you can just unwrench. This one denies it all and doesn't come unfastened.

**Why is this bad/What are the consequences:**
You can't remove it and it be used for cancerous means.

**Steps to reproduce the problem**:
Wrench a duel-port air vent down.
Cry.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tested in Atmospherics, and in a new part of the station created via building permit. Cultist round I believe.

**Comment by AndriiYukhymchak** [comment]
Can confirm. Had to call admins to delet them from existance
