### ISSUE TITLE
Chat is literally fucked

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6183]
**Problem Description**:
![](https://i.gyazo.com/8a865361447c88c284142d64261d6de6.png)
My chat, and some other people's chat, don't work at all.

**What did you expect to happen**: 
Well I mean.
The chat to work?

**What happened instead**:
I'm going to break this template. Actually, fuck it, I'm just going to remove the rest of it.
Should be obvious enough.

**Comment by FlattestGuitar** [comment]
Less salt for everyone.

**Comment by Spacemanspark** [comment]
I'm currently more salty then I've been in days, that is false.

**Comment by blobbernaut** [comment]
my chat doesn't even show up at all

**Comment by Crazylemon64** [comment]
BYOND is being awful at loading stuff non-locally, this will need some adjustment

**Comment by Crazylemon64** [comment]
As trite as it sounds: Try waiting for ~5 minutes, closing the DS interface, then connecting to the server again - does that fix the issue?

**Comment by SamHPurp** [comment]
Wait, "Literally fucked". EIther lewd, or you aren't using that correctly.

**Comment by SamHPurp** [comment]
Also, several people on Discord are also reporting this issue.

Users:
@Sargash and @Funce if you need more data points.

**Comment by Crazylemon64** [comment]
It seems this resolves itself on its own, over multiple logins? Closing, open another one if it pops up again

**Comment by Krausus** [comment]
Oh, I'm pretty sure #6209 fixed this.

**Comment by Spacemanspark** [comment]
This was fixed awhile ago.

**Comment by Fox-McCloud** [comment]
Yeah, haven't heard of any complaints on this in a long while. Closing this.
