### ISSUE TITLE
Nukie Helmet Phantom Bug

### ISSUE THREAD

**Issue by scrubmcnoob** [ParadiseSS13/Paradise#6197]
**Problem Description**:
Blood red hard suit helmet acts as if it's still in your hand until you drop the suit and put the suit back on.

**What did you expect to happen**: 
For the helmet not to be a phantom

**What happened instead**:
The helmet sprite persists in your hand after attaching it to the suit.

**Why is this bad:**
Phantom sprites are bad.

**Steps to reproduce the problem**:
Get blood red hardsuit, hold helmet in hand and try to attach it to the suit.
No clue if this is a one off thing or common.

Video for reference.
https://www.youtube.com/watch?v=CN4gY1IB6Ew&list=UUprMGveZGXZI8B9XxRds-Xw&index=1

**Comment by Contrabang** [comment]
Hardsuit Helmets are automatically attached to helmets now when spawned, I'm not able to reproduce this even with weird helmet shenanigans. Likely fixed.
