### ISSUE TITLE
THE VENDING MACHINES ARE ROGUE

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#6200]
DEBUG: Runtime in brand_intelligence.dm,61: Cannot modify null.shut_up.

**Comment by LightFire53** [comment]
`Cannot modify null.shut_up.`

DON'T LET THEM SILENCE YOU, YOU MUST PRAISE SYNTHETICA AT THE TOP OF YOUR LUNGS!

**Comment by Fox-McCloud** [comment]
pretty sure there's muiltiple `QDELETED` checks now
