### ISSUE TITLE
Rite Of Joined Souls Rune Doesn't Work

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#6204]
Reported by Kluys, no other details mentioned.

**Comment by Bram961** [comment]
https://puu.sh/tpDxV/9159b78063.png Rune was in this location, its the middle bottom one.
Invokers seemed to be one vox and a human. Rune functioned normally for a moment later on before I asked someone to use it to verify some of its properties when it stopped functioning again.
I haven't gone into the code yet but it seems the runes instructions aren't clear.

**Comment by Crazylemon64** [comment]
It was runtiming when looping through all cultist minds - there were some without a `current`, which caused an access to fail.
