### ISSUE TITLE
Chat does not load

### ISSUE THREAD

**Issue by hyenirc** [ParadiseSS13/Paradise#6208]
**Problem Description**:
What is the problem?
Chat does not load. Whenever playing the game or starting up the game, chat box is always loading despite waiting longer than up to 30min.

**What did you expect to happen**: 
Why do you think this is a bug?
All other functions of the game work. I can still say things and can see that others are saying things but I have to chat log. The game works perfect lullaby otherwise.

**What happened instead**:
How is what happened different from what you expected?
Chat stays stuck on the loading screen for the entire duration I play for.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
I can't play the game properly when I can't see what others are playing.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Upon loading the game from Byond, the game starts up properly. Except that the chat has the message "Loading... If this takes longer than 10 seconds, it will automatically reload, multiple times if necessary. If it still doesn't work, please adminhelp (F1) and tell us your operating system and Internet Explorer version."
After the game has started and even after I've played for 30min, the message remains. In-game, I am still able to do everything as I am normally. Just the chat doesn't load.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Game mode: secret, no respawn, AI allowed

**Comment by Fox-McCloud** [comment]
Quite the game, clear your BYOND cache, then relaunch. It'll work.

**Comment by hyenirc** [comment]
I have cleared the cache. It doesn't work. I've also tried reinstalling and still have problems

**Comment by taukausanake** [comment]
> Quite the game

In Spess, no one can hear you scream

**Comment by tigercat2000** [comment]
Try reconnecting multiple times and stay at least 30 seconds each time, without clearing your cache- sometimes it takes multiple logins.

If that doesn't work, could you give us your Windows/Internet Explorer version, please?

**Comment by hyenirc** [comment]
Doesn't seem to work. Internet explorer version: 8.0.7601.17514
