### ISSUE TITLE
The ability to see when pull requests are opened/ closed/ merged in game is gone and the preference missing.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6210]
I nuked the shitty template from orbit.
Basically you'll never see the neat little PR notifications in game anymore and I don't know why. Even the preference is gone. Couldn't find anything in the changelog hinting this, and nobody else I asked about it seemed to know, so I figured this is a bug.
Screenshot is as follows: 

![](https://i.gyazo.com/2232c7f81763ac49c3e993c236a48de0.png)

See? It doesn't pop up.

**Comment by FlattestGuitar** [comment]
They were never taken out, but there was never a preference for this.

I'd wager it has to do with the bot malfunctioning somehow.

**Comment by alexkar598** [comment]
If this is "not a bug" then why is it still open?

**Comment by tigercat2000** [comment]
@alexkar598 Fixed.
