### ISSUE TITLE
Unable to fix IPC face mangling if head undamaged

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#6212]
**Problem Description**:
if attempting to fix internal structure with a welder with no damage to the head the game won't let you as there is no "damage" to fix

**What did you expect to happen**: 
to be able to fix an IPCs face being mangled without having to assault them

**What happened instead**:
the message "The the head does not require welding repair!"

**Why is this bad/What are the consequences:**
It forces you to assault a patient to fix their head properly which is very silly from an IC perspective

**Steps to reproduce the problem**:
punch an IPC until the face is mangled and weld it normally, then attempt to fix it with cybernetic repair surgery
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by KasparoVy** [comment]
Seemed to work just fine in testing on a local branch for me. I beat a spawned-in IPC's head off and kept re-attaching it over and over until it disfigured, ensured it had no damage, and did the procedure to fix it by doing head-surgery for internal repair. I repaired the disfigurement.

Same thing happened when I manually set the disfigured var to 1. I was able to repair the disfigurement with the internal repair procedure on the head.
