### ISSUE TITLE
Fat humans aren't fat when they are naked. WARNING, BIG PICS

### ISSUE THREAD

**Issue by Puckaboo2** [ParadiseSS13/Paradise#6214]
**Problem Description**:
When you put clothing on a fat human, they look fat, as normal.
![image](https://cloud.githubusercontent.com/assets/13158711/22080093/7e0d4f70-dd7b-11e6-8ee0-5a587dbd584e.png)
But when they are naked, they look skinny.
https://puu.sh/tq190/c96d916f90.png
![image](https://cloud.githubusercontent.com/assets/13158711/22084788/a576d028-dd8e-11e6-94c9-87dac09fe48f.png)

**What did you expect to happen**: 
Fat, nekked humans.

**What happened instead**:
No fat, nekked humans.

**Why is this bad/What are the consequences:**
Uh. Fat naked humans should be fat.

**Steps to reproduce the problem**:
Make a human fat at startup, spawn, take off your clothes, boom, you're not fat.

**Was anything else out of the ordinary happening?)**: Anything else you can tell us.
I even tried to spawn a human and edit its nutrition to 400+. Nothing happened, but when I put clothes on it, it looked fat.
 This has nothing to do with my recent sprite revamp because I tested it on regular para code and it did the same thing.

**Comment by FreeStylaLT** [comment]
those pics look _overweight_

**Comment by KasparoVy** [comment]
Overeatduration is what makes them fat. Try setting overeatduration to 2k and watch them balloon in size.

**Comment by Fox-McCloud** [comment]
@KasparoVy 

I think means to demonstrate that they were, in fact, fat in the picture (with clothes), but they didn't look fat when they took the clothes off.

**Comment by KasparoVy** [comment]
Woops, my bad

The fix would be to ensure `update_body(0, 1)` is called during mob spawning as I feel the icons are cached before the fat mutation is applied, thus meaning that a regular `update_body()` call will not make them appear fat.
