### ISSUE TITLE
Vulpkanin cannot be fat or appear to have clone damage.

### ISSUE THREAD

**Issue by Flufflemonster** [ParadiseSS13/Paradise#6215]
Yeaaaaaah, Vulpkanin do not have fat sprites or deformed sprites. I noticed this was a problem for a while, but Fox told me not to touch them. When I showed the other race sprites in my project to the Para server, the only complaint I heard was 'Dogs need love too, pls.'

So, yeah. Permission to do a bit of a retouch, then add deformed and fat sprites?

**Comment by Fox-McCloud** [comment]
Vulp not being able to be fat is intentional.

The clone damage one is just a lack of sprites. I was wanting to defer to Skittles on that one, butttt at this rate, I'm not sure if that's going to happen.

**Comment by Puckaboo2** [comment]
I can do it if you want, Fox.

**Comment by Fox-McCloud** [comment]
I wouldn't mess with the shading, as @KasparoVy already touched up on that, but for clone damage? At this rate, sure, why not.

**Comment by Puckaboo2** [comment]
@Fox-McCloud Alright, I can do that.

**Comment by Spacemanspark** [comment]
I've always wondered why vulp can't get fat.
Aren't there fat dogs out there?

**Comment by taukausanake** [comment]
Oh yes there are. I'd link you to some I found on Google, but it's kind of depressing...

We should have fat sprites for them. It's only fair

**Comment by Davdichan** [comment]
Why the hell would vulps not be able to get fat?

**Comment by Iamgoofball** [comment]
Snowflake probably

**Comment by taukausanake** [comment]
Yeah, probably that

**Comment by Davdichan** [comment]
Is there any part of this race that makes sense?

**Comment by Iamgoofball** [comment]
The day porn makes sense I'll revert goofchem

**Comment by Spacemanspark** [comment]
The what
