### ISSUE TITLE
Invisible Animals

### ISSUE THREAD

**Issue by PotatoOS** [ParadiseSS13/Paradise#622]
Once i was walking around the halls,i bumped into something invisible,when i alt-clicked the floor,it showed "animal",nothing else,please fix the bug ?

**Comment by Spacemanspark** [comment]
Needs more details, like when this took place, for example.

**Comment by TheDZD** [comment]
This is when an animal spawns that is just a simple_animal, and has no subtype, as it has no actual sprite.
