### ISSUE TITLE
Terror Spider Cocoons block vent crawling

### ISSUE THREAD

**Issue by SkullZMinus** [ParadiseSS13/Paradise#6221]
**Problem Description**:
If you're vent crawling as a terror spider, and you would crawl through a tile that has a cocoon on it, you get ejected from the vent without a way back in.

**What did you expect to happen**: 
I expected to be able to keep crawling through vents regardless of whether or not there's a cocoon on that tile.

**What happened instead**:
The cocoon caused me to eject from the vent as though there was no pipe there, despite the pipe still appearing in the view while ventcrawling, and there's no way to tell that there's a cocoon on the vent unless you stop crawling when you can see in the room to check, which can be a problem is the vent with a cocoon on it is right against a wall that you're coming through.

**Why is this bad/What are the consequences:**
This can easily lead to terror spiders that can't open airlocks getting trapped in rooms with no way out, such as the 2x2 room above the HoP office. When you don't have a spider that can open doors for you, your round is basically over.

**Steps to reproduce the problem**:
As a terror spider, create a cocoon on anything that sits on a tile with a vent underneath it. Crawl into the vent system through a scrubber or vent opening, and try to crawl through the vent that the cocoon is on. Instead of passing it, you pop out like there's no vent there.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was an admin event during an extended round. All the spiders were spawned in a box.

**Comment by Kyep** [comment]
Cannot reproduce this.

**Comment by Kyep** [comment]
For the moment, I suggest that this issue be closed. I've tried multiple times to reproduce it, but I've never been able to verify it happening.

My suspicion is that the piping under the floors was damaged. It just happened to look like the web was causing it, because the web was on the same tile.

If anyone does get a solid reproduction case for this, though, please message me directly, and I will fix it.
