### ISSUE TITLE
AI vision

### ISSUE THREAD

**Issue by Bram961** [ParadiseSS13/Paradise#6225]
When the AI core is un-powered (by moving it onto the station through space for example) it will change views from viewing the world through the camera's to only viewing through the core as if the core was a human.
The AI is still capable of moving around their "eye" but everything besides what can be seen by their core will be black.

Should be pretty obvious how to repeat this issue.

**Comment by pinatacolada** [comment]
I was the AI, here's steps to reproduce what happened:
Be dragged from the sat through virology maintenance to the bridge. -i got the power cut in space as it should, and regained it along with vision when the core entered maintenance. 
I remained with normal vision until stepping into the bridge, where I got a very short power outage for no reason, the entire area and surroundings were fully powered. I never regained vision from this point onwards, not even by ghosting and getting back in the body. Integrity was also at 100%

**Comment by SamHPurp** [comment]
You can solve this ICly (in a dumb way) - by powering down your APC powering you, and letting yourself automatically hack into another APC near by. Once this is done, you can power yours back on again, and your vision restored.

Obviously better to get it fixed though.

**Comment by taukausanake** [comment]
Why is it possible that an AI core can be moved anyways? You have the AI card for a reason or two: to transport to a new node or restrain and/or repair an AI. I never liked being able to move an AI core, especially when powering down the unit supposedly (in the past if I recall correctly) killed the AI. It's why you always go for the APC and SMES I imagined. Removing the core from the grid as with any other machine normally powers it off. Shouldn't be different with the AI core

**Comment by Contrabang** [comment]
Not able to reproduce this 6 year old issue, likely fixed. I've seen plenty of AIs cross space to the new station and not experience this
