### ISSUE TITLE
Tripwire Mines Do Not Work

### ISSUE THREAD

**Issue by Alexshreds** [ParadiseSS13/Paradise#6229]
Infrared assemblies work as they should but using them in a grenade casing does not. No matter what option you set in the assembly menu, before or after attaching it to grenade case, it will never emit the laser required to trigger the assembly/bomb.

**Comment by jughu** [comment]
I rather use a signaller with tripwire since it foolproof but grenade qith tripwire can be buggy

**Comment by granodd** [comment]
I noticed this a lot when testing different types of bombs on a privately hosted server of mine. It seems to be completely broken when placed into a grenade, no amount of fiddling able to fix it. Even making sure the laser is visible and on before placing it into a grenade assembly immediately turns it off and makes it go inert. Infrared emitters as a whole just feel very buggy as well and a bit unresponsive, albeit barely functional.

Bring forth the glory of tripwire mines once more.
