### ISSUE TITLE
Soil / Dirt piles cannot be removed

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6232]
**Problem Description**:
Soil piles that are made from 3 sandstone bricks cannot be removed once created.

**What did you expect to happen**: 
Ability to remove a dirt pile with a spade.

**What happened instead**:
No reaction to any logically acceptable tools, such as a spade.

**Why is this bad/What are the consequences:**
Cannot clean up old dirt piles and make new ones with fresh soil.

**Steps to reproduce the problem**:
1. Build soil pile with 3 sandstone bricks in hand
2. Fruitlessly try to remove it
3. Explode botany out of frustration

It would be fine if a spade 'cleaned' up the pile without leaving anything behind, a simple attack by delete action.

**Comment by FalseIncarnate** [comment]
They used to do this, but apparently this functionality was accidentally omitted when we ported bay's updated botany quite a while ago. Amazing how little people use soil, considering how long it took for someone to catch this.
