### ISSUE TITLE
TRAIT_PRODUCES_POWER doesn't work

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6235]
Botany plant trait TRAIT_PRODUCES_POWER doesn't allow construction of batteries from plant produce.

1. Splice TRAIT_PRODUCES_POWER into a plant
2. Apply cable to plant
3. Nothing happens

Tested with glowcap plant.

Related code: https://github.com/ParadiseSS13/Paradise/blob/37a7484976441a077c36615b30d4567e01958291/code/modules/hydroponics/grown.dm

@ /obj/item/weapon/reagent_containers/food/snacks/grown/attackby

**Comment by Fox-McCloud** [comment]
You'll need to provide more details, but uh....glowcaps don't produce power, they have a separate power related trait.

**Comment by awellwisher** [comment]
You're right, I confused TRAIT_PRODUCES_POWER with TRAIT_BATTERY_RECHARG.
