### ISSUE TITLE
Double Traitor!

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6250]
**Problem Description**:
Some people are spawning as a traitor twice, getting two sets of objectives and two uplink codes, but only the second one working.

**What did you expect to happen**: 
We don't have a 2 for 1 traitor special.

**What happened instead**:
2 for 1 traitor happy hour deal!

**Why is this bad/What are the consequences:**
It makes traitor twice as hard, which can be misleading. Like getting die gloriously and hijack.

**Steps to reproduce the problem**:
Round Starts, spawn as a traitor

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This isn't a one off, it has been occuring over the past couple of days.

**Comment by Alexshreds** [comment]
@Aurorablade 

Correct me if I'm wrong but is this the issue?

https://github.com/ParadiseSS13/Paradise/blob/21b29da97a8e2264517484d1b3b5ac019b1bc8a8/code/game/gamemodes/autotraitor/autotraitor.dm#L61
```
/datum/game_mode/traitor/autotraitor/pre_setup()
//pick traitors code here
..() //this calls /datum/game_mode/traitor/pre_setup()
return 1
```

https://github.com/ParadiseSS13/Paradise/blob/37a7484976441a077c36615b30d4567e01958291/code/game/gamemodes/traitor/traitor.dm#L28-L60
```
/datum/game_mode/traitor/pre_setup()
//pick more traitors code
return 1
```

**Comment by Fox-McCloud** [comment]
I have a feeling it relates to: https://github.com/ParadiseSS13/Paradise/pull/5984

This wasn't a problem until this went through. May be wrong though.

**Comment by Alexshreds** [comment]
/////////:space_invader:
/////////:point_up: 
:space_invader: :point_left: :space_invader: :point_right: :space_invader: 
/////////:point_down: 
/////////:space_invader: 

Time to play the blame game

**Comment by LightFire53** [comment]
I blame the coders.

**Comment by Keilden** [comment]
I blame the spriters.
