### ISSUE TITLE
Unable to absorb more than 5 genomes as a Changeling

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#6251]
**Problem Description**:
As a Vox changeling you are unable to absorb any more genomes after you reach the cap of 5, even after transforming.

**What did you expect to happen**: 
After transforming you are able to absorb more genomes to reach your objective.

**What happened instead**:
I received the message "You are unable to absorb more genomes, you must transform before absorbing more" I transformed multiple times and used Regenerative Stasis before trying to both use "Absorb DNA" and "Extract DNA Sting" with the same results..

**Why is this bad/What are the consequences:**
Unable to complete objective # 1 which involves absorbing more genomes than 5 - requiring at least one transformation.

**Steps to reproduce the problem**:
Roll changeling as a Vox character.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I have had this same problem twice both after I purchased the Vox race. I have played changeling before as a human character and had no issues, however the two times I have played changeling as a Vox I have encountered this issue which has prevented me from doing my objectives.

Due to antagonist rolling system I am of course unable to test this however it has happened twice which leads me to believe it may be a bug. I will take screenshots the next time I am able to play Changeling and append them to this issue.

**Comment by uraniummeltdown** [comment]
I only play Vox and have no problems with getting more than 5 genomes, did you absorb before getting to 5 genomes?

**Comment by Birdtalon** [comment]
Yes actually in both cases I absorbed someone as my first genome and then used DNA extract for the next four.

**Comment by Krausus** [comment]
> you must transform before absorbing more
> I transformed multiple times

This message specifically means that, of the 5 genomes you currently have, you *must* be using one of the 4 most recent, because you're going to lose the 5th. Did you try extracting DNA with any of the other forms you had access to, or were you sticking with one particular form?

**Comment by Birdtalon** [comment]
When your DNA becomes stale you lose the oldest genome which you have. Yes? My oldest genome in this case is of course my original. I had transformed into one of the 4 alternative genomes when I tried to extract the DNA. When this didn't work I transformed into another of the newer genomes and had the same thing.

**Comment by Krausus** [comment]
Odd. Were you changing your DNA in some way after transforming, or otherwise modifying your appearance?

**Comment by Birdtalon** [comment]
No I hadn't changed my DNA in any way other than using the transform ability. I had also Hive Channelled some of my genomes.

**Comment by uraniummeltdown** [comment]
I always DNA sting my way to increase genomes before absorbing so I'm not sure, my changeling PR didn't touch much except removing some species checks on abilities

**Comment by Birdtalon** [comment]
I will try to recreate this issue if I roll changeling and record it.

**Comment by SamHPurp** [comment]
This is inconsistent, but I've witnessed this as well, when not a vox, when a human.

It has something to do with absorbing / using DNAs from the hive/air I'm pretty sure, but I've never been able to sit down and re-produce it.

**Comment by Birdtalon** [comment]
I think this was just a mistake on my part after a few more plays.
