### ISSUE TITLE
Posibrains cannot see the text of a CC announcement.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6255]
**Problem Description**:
Posibrains cannot see CC announcements.
I'm salty because I can't see the sweet gossip that CC is sharing with the crew.
Fix ASAP.

[![https://gyazo.com/ceac4c76313bd465efc2409f9917c921](https://i.gyazo.com/ceac4c76313bd465efc2409f9917c921.png)](https://gyazo.com/ceac4c76313bd465efc2409f9917c921)

**Comment by LightFire53** [comment]
If it makes you feel better, as an admin observing, if I don't have a news feed on screen, all I get is the log of someone using a priority announcement.
