### ISSUE TITLE
Rigsuit runetimes

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#6257]
Noted them when ely was playing with one:
[01:32:29] Runtime in rig.dm,134: 
   proc name: New (/obj/item/weapon/rig/New)

[01:32:31] Runtime in rig.dm,476: Cannot modify null.slowdown.
   Caught by process: obj
   src: The cybersuit control module (/obj/item/weapon/rig/light/hacker)

((might be unrelated:)
[01:32:53] Runtime in action.dm,48: Cannot read null.client
   Caught by qdel() destroying /obj/item/clothing/suit/space/chronos
   src: Chronosuit (/obj/item/clothing/suit/space/chronos)

@Allfd since you helped get those fixes from mars over.

**Comment by Allfd** [comment]
@Aurorablade Yep, will take a look after work.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/13748

**Comment by AffectedArc07** [comment]
Rigsuits got the purge.
