### ISSUE TITLE
"Snowman head" clothing item doesn't have a sprite

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6258]
The item called "snowman head" that is dispensed from AutoDrobe vendor does not have any sprite, neither in inventory nor when worn.

**Comment by uraniummeltdown** [comment]
It was fine before https://github.com/ParadiseSS13/Paradise/pull/6175

That PR deleted all the obj and mob icons added in https://github.com/ParadiseSS13/Paradise/pull/6087
