### ISSUE TITLE
SNPC runtimes

### ISSUE THREAD

**Issue by DarkPyrolord** [ParadiseSS13/Paradise#6261]
Just something that popped up when spawning in an SNPC, comes up once every two seconds when an SNPC is alive:
[17:33:45] Runtime in functions.dm,19: Cannot read "".len
   proc name: chatter (/mob/living/carbon/human/interactive/proc/chatter)
   src: Jadyn Ali (/mob/living/carbon/human/interactive/greytide)
   src.loc: the floor (170,22,2) (/turf/simulated/floor/plasteel)
   call stack:
   Jadyn Ali (/mob/living/carbon/human/interactive/greytide): chatter(Jadyn Ali (/mob/living/carbon/human/interactive/greytide))
   Jadyn Ali (/mob/living/carbon/human/interactive/greytide): callfunction("chatter")

**Comment by Krausus** [comment]
Turns out this was caused by a bad SNPC varedit getting saved and re-loaded. We *could* add more sanity checking, but it should be fine for now.

**Comment by Fox-McCloud** [comment]
In general, if admins are screwing around with vars they *really* shouldn't, or assign incorrect values to incorrect vars--it's largely something we don't account for.

Ie: if you try to add set the parent type of an object to a client and it causes issues, that's the admin's fault.
