### ISSUE TITLE
Theft objective items inside storage implants don't count

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#6269]
**Problem Description**:
Steal objectives will fail if the item is inside a storage implant.

**What did you expect to happen**: 
I expected that stealing something, placing it inside a storage implant, and then escaping with the implant in my body, would count as complete for the purpose of the objective.

**What happened instead**:
The objective read as a failure. Taking the item out of the implant, and putting it inside my backpack, worked fine. The problem is that items inside storage implants at round-end don't count towards steal objective completion.

**Why is this bad/What are the consequences:**
This causes antags to fail steal objectives when they don't deserve to.

**Steps to reproduce the problem**:
1) Have a steal objective
2) Have a storage implant
3) Put the item that is your steal objective inside your storage implant
4) Escape
5) You will fail your objective

**Comment by Bigtimetripod** [comment]
Haven't this been a "feature" for the past... years? Makin you take your stuff out before before the shuttle docks, giving others fraction of a second to disarm you.

**Comment by Kyep** [comment]
If you're storing something in an implant, that should count as "on you" for objective purposes. It is logical.

Forcing people to switch over to their backpack isn't a meaningful impediment to anyone who knows about the requirement. They can easily switch seconds before docking, or on a pod, or in a small room on the shuttle.
The fact that people are forced to switch over, though, is an annoyance for newer players, who don't know they have to switch it over, and feel like they've been robbed of their greentext by a game bug.

**Comment by taukausanake** [comment]
I feel like this came up before but I'm not sure, nor do I want to search the repo for a similar issue. I do feel storage implants should be counted as on your person, especially if you have hijack and end up going to the syndicate base when #6086 goes through. Sure if that then you don't need to storage implant it but that's besides the point I'm making

**Comment by Birdtalon** [comment]
Storage implants should definitely count towards your objective as it is on your person. If you've invested the TC in buying one then it should be able to be used to hide stolen objects until round-end.
