### ISSUE TITLE
Ambrosia Cruciatus (antag seeds) have error in seed_datum

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6274]
Ambrosia Cruciatus, the botanist antag-only plant seed, have incorrectly defined chems in seed_datum.

Instead of bath_salts it has "bath salts" with a space, meaning the only reason to buy the seeds doesn't work.

https://github.com/ParadiseSS13/Paradise/blob/44cb53779b7cddb0238e5e0137e01ed314723024/code/modules/hydroponics/seed_datums.dm

**Comment by Fox-McCloud** [comment]
Addressed in https://github.com/ParadiseSS13/Paradise/pull/6236
