### ISSUE TITLE
Cannot remove corpse from pod passanger seat

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6279]
Drag and drop a corpse onto a pod with a passenger seat, climb into pod and be unable to unload cargo or in any way remove the corpse from the pod.

Component removal says "someone is sitting in the seat"

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/spacepods/spacepod.dm#L418-L439

Try using grab intent while the pod is unlocked.

**Comment by awellwisher** [comment]
Arcane knowledge right there.

**Comment by Crazylemon64** [comment]
👋 ✨
