### ISSUE TITLE
Undeconstructible bar stool

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6285]
There's a bar stool in the maint old bar backroom of main station that cannot be deconstructed with a wrench or otherwise.

There's actually several of such stools that can't be deconstructed throughout the station, while others can be.

**Comment by Fox-McCloud** [comment]
Someone picked it up and set it back down.

**Comment by awellwisher** [comment]
How does that work? I can't seem to set this particular one down. While others after being set down can be deconstructed.
