### ISSUE TITLE
Gibbed wizards drop Cluwne's Touch

### ISSUE THREAD

**Issue by Draconic-saint** [ParadiseSS13/Paradise#6292]
A Ragin' Mages wizard got gibbed due to dropping into crit while holding the cluwne's touch spell. 

I very much doubt that this is intended.
![2017-01-29_16-13-12](https://cloud.githubusercontent.com/assets/13335931/22449670/e2867afe-e761-11e6-9d62-b3c9e8ef9d0d.png)

**Comment by Crazylemon64** [comment]
hee

**Comment by taukausanake** [comment]
What does cluwn touch do? Is that the item that turns people into cluwns? I can see that as being !!fun!! for others

**Comment by Draconic-saint** [comment]
!!fun!! does not come into play here. 
Touch spells are generated as undroppable single use objects IIRC.
If they do get dropped for any reason, that's a bug, not a feature.

**Comment by Spacemanspark** [comment]
Yaaaa this probably isn't something we want
