### ISSUE TITLE
Pocket fire extinguishers don't have a hit sound.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6299]
**Problem Description**:
Pocket fire extinguishers don't have a sound when they hit something.

**Comment by Alexshreds** [comment]
`hitsound = null	//it is much lighter, after all.`

looks like this was on purpose

**Comment by taukausanake** [comment]
Yeah, one of those would be small plastic compressed tanks. Then again are there any other small items that can make hit sounds maybe?

**Comment by Spacemanspark** [comment]
Oxygen tanks.

**Comment by KasparoVy** [comment]
Most likely much heavier and definitely made of a different material.

**Comment by tigercat2000** [comment]
@Fox-McCloud not an inconsistency really, it's clearly intentionally designed
