### ISSUE TITLE
Gateway maps have non-functioning wires

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6302]
Practically every gateway map with wires I encountered has relatively correct wiring, but the wires themselves do not transfer power. As in you have a straight connected cable line from roundstart, but some of the cables will need to be cut and replaced for them to work.

I suspect the object responsible for gateway destination is having similar problems, which causes the "destination not found" error.

**Comment by Aurorablade** [comment]
No the destination not found is caused by runtime errors on an object preventing a map to load. Some maps have power stuff as a puzzle but most without that don't need cable power persay I may be wrong

**Comment by Alexshreds** [comment]
@Aurorablade He means he suspects whatever error these power nets are having is similar to the error that causes the object to prevent the map to load.

**Comment by DesolateG** [comment]
@Aurorablade hotel has a turbine, xeno infestation has a generator and the NT base has 3 generators.

**Comment by Kyep** [comment]
This is too vague to reproduce.
