### ISSUE TITLE
Names with numbers don't persist between rounds.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6312]
**Problem Description**:
Named myself "Spark 5.5" in the character setup menu, and it stuck around for a single round. Next round it was "Spark . ". I have to re-add the numbers every round.

**Comment by KasparoVy** [comment]
It's because of [this line](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/client/preference/preferences_mysql.dm#L269) since there isn't a 'numbers allowed' argument (which the proc supports) passed for IPCs.
