### ISSUE TITLE
Monkey organs cannot be forcefed/grinded until they have been bitten

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6314]
Butchered a monkey with a knife, tried to grind its heart in a grinder. I couldn't insert it until I took a bite out of it, same thing with forcefeeding and all the other organs.

I'm also pretty sure they don't decay, neither do monkey limbs.

**Comment by Fox-McCloud** [comment]
This isn't a bug; they have to be converted into food objects by biting into them--organs aren't something you can eat because they don't have the necessary procs and vars associated with them for that to be possible.

**Comment by awellwisher** [comment]
Why not just add a proc to grinder that converts them on attackby? Same for forcefeed.

**Comment by tigercat2000** [comment]
@awellwisher Because it's not a bug. This is how it is meant to work. If you want it to work some different way, make a feature request on the forums.
