### ISSUE TITLE
Drone Drop Command not working on Engineering Borg

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#6317]
**Problem Description**:
What is the problem?

The Drone Tab Verb drop to drop an item from an active magnetic grabber does not work again.

**What did you expect to happen**: 
Why do you think this is a bug?

Items should drop from the magnetic gripper when the hotkey Z is pressed or the drone drop verb is used. It does not work on Engineering borgs.

**What happened instead**:
How is what happened different from what you expected?

No item was dropped from an active magnetic gripper holding an item.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Not serious. But does mean a borg can end up having their magnetic gripper useless if they don't find a way to place an item into something that the magnetic gripper is holding.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Pick up item in gripper. Try to use Z to drop. Try to use drop command from Drone tab. Neither function correctly.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by DesolateG** [comment]
Z key allows you to use the item in the gripper. Right click the gripper to drop.

**Comment by VampyrBytes** [comment]
However, @Taaketa is right that the verb isn't working... I've started looking at this and should have a fix up soon(tm)
