### ISSUE TITLE
Floor Tiles at armoury grill area do not accept wires, reinforce flooring or floor tiles

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#6318]
**Problem Description**:
What is the problem?

The armoury access area in space with the grills covering access do not allow wire, floor tiles or reinforce flooring to be placed on them.

**What did you expect to happen**: 
Why do you think this is a bug?

The floor tiles exist as walls can be built. But do not allow wire to be placed on the tile.

**What happened instead**:
How is what happened different from what you expected?

For wire to be placed on the floor tiles.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

It is not, but an annoying one.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Try to place, flooring on the base floor tile, wire or reinforced flooring. It will not work. Only way around it is to RCD in a wall and deconstruct the wall with welder and wrench to make the floor tile accept wiring.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
It must be of a floor type already, just with a different icon. Should try crowbaring it next time and see if you get a floor tile from it. If not then might be another issue

**Comment by Anoonki** [comment]
It is actually floortiles with the plating skin on it. 
For whatever reason that is, I'll never know.
