### ISSUE TITLE
Plant analyzer can't print scan reports anymore

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6340]
Scanning plants instead spams the chat which makes keeping track of plant stats really cumbersome since there's already so much scrolling the chat it.

**Comment by Fox-McCloud** [comment]
This was done intentionally. This isn't a bug, and is an explicit feature request.

**Comment by awellwisher** [comment]
It's an undocumented feature loss not mentioned anywhere in your PR.

**Comment by awellwisher** [comment]
@Fox-McCloud
I really hope someone merges https://github.com/ParadiseSS13/Paradise/pull/6123 so you can feel what it's like when someone shits all over what you like.

**Comment by Crazylemon64** [comment]
0 to 100 in wew

**Comment by taukausanake** [comment]
Yeah, I made mention to this when I tested the PR with Fox. I don't like it either and really clutters up the chat. I'm sure a revert of that specifically shouldn't be tough unless NanoUI is as much a pain as Fox claimed it was

**Comment by Fox-McCloud** [comment]
>Fox claimed it was

The plant analyzer doesn't utilize NanoUI; it uses an HTML interface.

**Comment by taukausanake** [comment]
Yeah but I would imagine any window interface would be switched to NanoUI. Am I incorrect? Thought it was more convenient/pretty/cheaper to use
