### ISSUE TITLE
Arrivals escape pods

### ISSUE THREAD

**Issue by Necaladun** [ParadiseSS13/Paradise#636]
Arrivals pods work well now - except the doors on the shuttle they go to don't open, leaving the poor people trapped in locked pods 5eva.

**Comment by CrAzYPiLoT-SS13** [comment]
Is this still appearing as an issue?

**Comment by Spacemanspark** [comment]
Yes.
It's caused by fucking around with the pod control thing (The thing that let's you override the bolts and close the door and manually take off.)
