### ISSUE TITLE
Genetic spells not working

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#6365]
**Problem Description**:
Using genetic spells, such as empath (read mind) doesn't work

**What did you expect to happen**: 
It does nothing

**What happened instead**:
[13:10:48] Runtime in ,: bad arg name 'user'
   proc name: cast (/obj/effect/proc_holder/spell/targeted/empath/cast)
   usr: Parker Johnson (sladestryker) (/mob/living/carbon/human)
   usr.loc: The floor (162,112,1) (/turf/simulated/floor/plasteel)
   src: Read Mind (/obj/effect/proc_holder/spell/targeted/empath)
   src.loc: null
   call stack:
   Read Mind (/obj/effect/proc_holder/spell/targeted/empath): cast(/list (/list), null)
   Read Mind (/obj/effect/proc_holder/spell/targeted/empath): perform(/list (/list), 1, Parker Johnson (/mob/living/carbon/human))
   Read Mind (/obj/effect/proc_holder/spell/targeted/empath): choose targets(Parker Johnson (/mob/living/carbon/human))
   Read Mind (/obj/effect/proc_holder/spell/targeted/empath): Click()
   Read Mind (/datum/action/spell_action): Trigger()
   Read Mind (/obj/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=19;icon-y=8;left=1;scre...")

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
Give yourself empath and try to target someone, it won't work
This might be all of goon's "spells"

**Comment by Crazylemon64** [comment]
oh goshdarn it someone goofed up variadic arguments somewhere
