### ISSUE TITLE
IPCs Posibrains come out of their bodies muted

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#6368]
**Problem Description**:
What is the problem?

When IPCs are gibbed their Posibrains come out muted, preventing them for calling for help.

**What did you expect to happen**: 
Why do you think this is a bug?

IPCs should be able to speak in their posibrain state.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

IPCs end up in a partial dead state and cannot ghost without being able to rejoin the round then as they are technically still alive as a posibrain. I spent one round just sitting in my brain, unable to ghost without losing my ability to rejoin. I was hidden behind my own gibs and a plant so no one could see me to save me.

Either IPCs, when gibbed should die outright like a human player or be allowed to speak so they can ask for their brain to be moved into a borg for example. Spending the rest of a round trapped in a posibrain unable to cry for help is very boring and doesn't really introduce any gameplay advantage or disadvantage to the game.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
Very much intentional. This was done so IPCs don't have an advantage, when gibbed or when their brain is extracted over that of a regular human mob.

**Comment by Taaketa** [comment]
So if I want to watch the rest of the round I have to give up a right to spawn in as any late round antags :( Big thumbs down.
