### ISSUE TITLE
HoS' Office Faxes the Syndicate

### ISSUE THREAD

**Issue by Aceluke123** [ParadiseSS13/Paradise#6370]
**Problem Description**:
What is the problem?
--The Head of Security's office allows faxes the Syndicate.
**What did you expect to happen**:
Why do you think this is a bug? 
--Usually you would need an Emag/Cryptographic Sequencer to fax the Syndicate, instead it was a shift start ability to fax them. As well as the Head of Security usually shouldn't be able to fax the Syndicate due to the way CC and the Syndicate system works with antagonists being opposite forces.
**What happened instead**:
How is what happened different from what you expected?
--Well you shouldn't be able to fax the Syndicate without an Emag and at shift start no less from the Head of [Security's](url) office.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
--Being able to fax the Syndicate as the Head of Security doesn't fit with the way the shifts usually work with the syndicate needing to fax the Syndicate utilizing a fax machine with has an Emag used on it
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
--I was being asked to hire someone as a Security Pod Pilot, which i thought needed Central's approval, but when i went to check if the fax machine in the Head of Security's office could contact Central Command, I was surprised to see it didn't allow the fax to contact Central Command but instead the Syndicate was listed as a faxing location.
**Possibly related stuff (which game mode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
--Nothing but the fact it was an odd bug i found out and was asked to report.
![glitch 2](https://cloud.githubusercontent.com/assets/25616489/22762353/953d4f56-ee24-11e6-8c2f-da4df4940f84.png)

**Comment by taukausanake** [comment]
Hey @TullyBurnalot is your NT conspiracy theory becoming more true now?

**Comment by Kerroman** [comment]
I verified that the fax machine wasn't emagged by checking the Variables as seen here:
<img src="https://i.gyazo.com/0fefeb311ccaf4493bb04359c82180d9.png">

I don't know that the Syndicate was an option from round start, however.  Before Aceluke ahelped about the issue the traitor RD had sent a fax to the Syndicate.  My best guess is that the RD emagging his own fax machine somehow made all the fax machines (or possibly just the HoS's) allow the Syndicate as a recipient.

**Comment by Davdichan** [comment]
The HoS tempting fate and sending butt faxes to the syndicakes is a time honored tradition!

**Comment by SamHPurp** [comment]
I keep seeing that with the NT Rep fax too, it could have theoretically been emagged, but its been happening with such regularity, I'm doubting it.

**Comment by DesolateG** [comment]
I can confirm that the HoS office fax despite being "local network" can fax central command
