### ISSUE TITLE
Blob Scaling Descales

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6372]
**Problem Description**:
Blob scaling falls back to 700 tiles after a blob splits.

**What did you expect to happen**: 
Blob tile requirement to either rise or stay the same

**What happened instead**:
It dropped from 1050 to 700.

**Why is this bad/What are the consequences:**
It's not working as intended

**Steps to reproduce the problem**:
1. Be Blob
2. Gather enough resources to split
3. Split
4. Cheese your way to victory because now you need to do less work.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Blob gamemode with three players initially, had a goal of 1050. One split, and the required tile count to win was dropped to 700.

**Comment by DesolateG** [comment]
Huh.. that day we had 4 blobs.. whew.

**Comment by Twinmold93** [comment]
Sounds like a bug coming from the conscious split verb. Should be easy to fix.
