### ISSUE TITLE
Syndicate turrets are shooting pAIs again

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6375]
**Problem Description**:
Syndicate turrets are shooting pAIs again for whatever reason.
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
@Markolie

**Comment by Markolie** [comment]
How did we solve this previously? And just for clarity, why shouldn't they target pAI's?

**Comment by Spacemanspark** [comment]
Because the operatives start with a pAI.

**Comment by Markolie** [comment]
I've added faction support to pAI's instead to avoid regular pAI's breaking into Syndicate areas.

**Comment by taukausanake** [comment]
Does that mean SNPCs will also shoot pAIs?
