### ISSUE TITLE
Multi-verse Sword spawning Suit-requiring species without life support

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6376]
**Problem Description**:
When you sign up for apprentice of a multi-verse sword, it keeps your race from when you were alive. As a result, I spawned in as a Plasmaman version of "Michael Smith" in a bus-round... and immediately lit on fire.

**What did you expect to happen**: 
The multi-verse sword should spawn in the player as the same species as the original holder.

**What happened instead**:
I spawned as a fart in a suit, without a suit.

**Why is this bad/What are the consequences:**
Low importance... because how often do you see a multi-verse sword. Consequences of not fixing it, is people dying when spawning in as a copy.

**Steps to reproduce the problem**:
Died as a plasmaclown.
Got the offer to spawn in as an 'apprentice of Michael Smith'
Did.
Spawned as Plasma Michael Smith.
Burnt.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Ely bus round... but I assume this is easily re-producable. ;)

**Comment by SamHPurp** [comment]
Or at least gimme a damn suit.

**Comment by DesolateG** [comment]
Yeah, mainly plasmameme's spawning in and burning to death

**Comment by KasparoVy** [comment]
I'm pretty sure the alternate species thing is intended, and I'm also pretty sure the oversight was that plasmamemememes aren't getting suits/tanks. They're going to need snowflake handling for that.

Wouldn't that mean that Vox don't get their tanks, either? (Although that could be sorted by calling their species' equip proc)

**Comment by SamHPurp** [comment]
Yeah that is quite likely the case I think @KasparoVy

**Comment by DesolateG** [comment]
The sign up shouldn't say "apprentice " should it? I mean you're not an apprentice, but another version of the Prime from a parallel universe.

**Comment by taukausanake** [comment]
I thought the multi-verse sword was supposed to spawn additional yous from different universes, not just some other being. Then again maybe I'm getting it mixed up with another sword of similar nature

**Comment by DesolateG** [comment]
In infinite universe theory there are an infinite amounts of you that are exactly the same and an infinite amount of you that might be an entirely different species or mindset.

**Comment by Crazylemon64** [comment]
Don't species have some equip proc to prevent them from immediately dying when spawning in

**Comment by KasparoVy** [comment]
The species equip proc is only called at roundstart during job equipping

Calling it manually at the end of spawning in a mob with the multiberse sword or whatever would be the easiest solution to thisd
