### ISSUE TITLE
Cannot light cigarettes with wands of fireball

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6377]
**Problem Description**:
Cannot light cigarettes with wands of fireball

**What did you expect to happen**: 
This is clearly a huge oversight.

**What happened instead**:
I couldn't light my cigarette after a kill, and didn't look !cool!

**Why is this bad/What are the consequences:**
Gamebreaking.

**Steps to reproduce the problem**:
Cigarette in mouth. Wand / staff on cigarette... and on face.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
This is a feature request, and the game is unplayable without it. Conflicted...

**Comment by SamHPurp** [comment]
More a massive oversight.

**Comment by Anticept** [comment]
I love everything about this.

**Comment by KasparoVy** [comment]
Should blow your head off if you do it, or be a suicide anim.

**Comment by Anticept** [comment]
Roll the dice. If successful, the best you do is singe your eyebrows, but the cigarette is lit and everyone nearby gets a badass message about what you just did.

Failure means you eat a fireball, but survive.

Critical failure means you explode in a fireball.

**Comment by taukausanake** [comment]
We already have suicide verbs for deaths. You can light a cig with a welder, no matter how much more safe than with a fire-death wand, without harm. A wizard with the skill to wield such power should be more than capable to light a cigarette with a wand or staff without using any charges on it

**Comment by Anticept** [comment]
That's not fun, however.

**Comment by Birdtalon** [comment]
This needs to be turned into a feature.
