### ISSUE TITLE
IPCs can eat crayons

### ISSUE THREAD

**Issue by mass595** [ParadiseSS13/Paradise#6378]
**Problem Description**:
IPCs, which do not have mouths and are not supposed to be able to consume solids, can eat crayons. Eating a crayon slightly recharges them.

**Why is this bad/What are the consequences:**
If an IPC gets a hold of a rainbow crayon, they can infinitely recharge themselves with no consequences.

**Steps to reproduce the problem**:
-Become an IPC
-Eat a crayon

**Comment by Spacemanspark** [comment]
wow

**Comment by DesolateG** [comment]
Sounds intended to me
