### ISSUE TITLE
ZAS Tweak

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#638]
The recent ZAS tweak was tested rigorously (see details in my other issue). Instead of the pushing stunning me and hitting me every few seconds, I was slammed into lockers, tables, etc. roughly 10 times per second, and died almost instantly. Telvayne also was pushed around, and him being an IPC, he popped into little robot parts in quite literally three seconds. He was solely pushed into walls, too - he didn't have objects bombarding him. As far as I can tell, it's MUCH deadlier than before - resisting the air flow pushing you just makes you hit the walls and objects more often, and staying in one place just means you get crushed against the wall.

An update: Instant death for two more crewmembers when they opened a door. Quite literally constant smacking sounds as they rammed into the wall.

**Comment by Spacemanspark** [comment]
Sounds like Bay's updated ZAS except it doesn't push you down...

**Comment by Fox-McCloud** [comment]
I anticipated the super quick slamming if you resist the airflow, as this showed up in local testing---what I didn't expect what how much damage this would do. Locally, I did slam against the wall a bunch of times in rapid succession, but the damage was tiny and roughly equal to what it was when it did stun you.

Seems there's a few cases where...uh...yeah. Will fix.

**Comment by Fox-McCloud** [comment]
Should be fixed. The sound you hear from slamming into a wall/objects is now largely for comedic effect.
