### ISSUE TITLE
Mesons allow you to see pulse-checking through walls

### ISSUE THREAD

**Issue by mass595** [ParadiseSS13/Paradise#6383]
**Problem Description**
While wearing Mesons you are able to see players checking the pulse of others (via shift-click), even when you cannot actually see either player.

**Steps to reproduce the problem**:
-Put on mesons
-Have a player check the pulse (shift-click) of another player outside your line of sight, but within view range (behind a wall).

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Experienced this while in an escape pod, had no visual on the players in an adjacent pod, but could see them checking pulse. (Via chat)

**Comment by Markolie** [comment]
I'm going to guess this is not just an issue with check_pulse, but also with other procs that use visible_message. Perhaps an issue with the see_invisible check in there, because mesons change a mob's see_invisible.

**Comment by DGamerL** [comment]
While check_pulse has been killed off, this issue will stay open because of the underlying issue.

**Comment by Spaghetti-bit** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/60483458/fe22f2f9-a40f-42d1-bc60-1bad6e4f145d)
After some testing, this hasn't popping up in a while.
