### ISSUE TITLE
Swedish Speech disability sometimes makes text invisible

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#6384]
**Problem Description**:
When you have the "swedish" disability active, any text you say that has an "a" or an "o" in it has a chance of disappearing. This is likely because the game cannot display umlaut a's and o's and instead blanks the whole sentence. The speech bubble with dots still appears over your character, but no indication that you have spoken appears in chat.

**What did you expect to happen**: 
Sentences to come out as normal, except with a swedish-style type filter as it is supposed to.

**What happened instead**:
Sentences with an "a" or "o" (or "A" or "O") don't show up in chat at all.

**Why is this bad/What are the consequences:**
This is the swedish mutation, not mute.

**Steps to reproduce the problem**:
Activate the swedish gene, then try to say a sentence with "a" or "o" in it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was on a private testing server that I have to experiment with the code, not on a session with other people. Also, I attempted to say umlaut a's and o's (using alt codes) in chat in the actual server, and the same problem occurred.

**Comment by tigercat2000** [comment]
Goonchat should fully support UTF-8 at this point- just not from player input. This is odd.
