### ISSUE TITLE
The space pod trail appears to be made from people.

### ISSUE THREAD

**Issue by streather** [ParadiseSS13/Paradise#6399]
**Problem Description**:
While in motion the space pod trail appears to be made of people

**What did you expect to happen**: 
I expected it to look like normal.

**What happened instead**:
Whenever you move the space pod, the trail behind you turns into the outline of a person.

**Why is this bad/What are the consequences:**
Because it's bloody weird.

**Steps to reproduce the problem**:
Get into a space pod.

Go into space.

Move about a bit

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: it looks like the wrong sprite is being loaded or something.

I've tried to include a screen shot showing the trail

![scrnshot1](https://cloud.githubusercontent.com/assets/16649728/22856672/050e1110-f08e-11e6-9af7-d93ec4c1f436.png)

**Comment by Spacemanspark** [comment]
...Did someone set incorporeal_move to 2 or something?

**Comment by taukausanake** [comment]
This is a FEATURE. Just imagine the additions you can make! Pimp My Space Pod when?

**Comment by DesolateG** [comment]
It's not just space pods, it's all jets. This happend on my borg with ion thrusters this morning.

**Comment by DesolateG** [comment]
https://snag.gy/qoSEAX.jpg
