### ISSUE TITLE
Colour blind and air lock hacking

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#6406]
**Problem Description**:
When you are colour blind, you still see the colour of the wires.

**What did you expect to happen**: 
You shouldn't be able to see the colour of the wires.

**What happened instead**:
Have the same debuff as colour blindness, mixing similar shades of greys, browns, and blues.

**Why is this bad/What are the consequences:**
Antags, pretty much grey tides Vulps or Tajarans can still hack air locks easily since the colours are labelled and showen as their colour. This will make them slightly over powered since they have the ability to also see in the dark.

**Steps to reproduce the problem**:
Toggling colour blind mode, unscrewing panel of any air lock or vendor.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Any mode

- Kitten

**Comment by tigercat2000** [comment]
Feature request, not a bug.

**Comment by Fox-McCloud** [comment]
The amount of snowflaking this would require to change this would be patently ridiculous. Going through the entire codebase to resolve every word text/examine color and snowflaking a check for if they had the colorblind gene (which wouldn't be consisted either seeing as some species have different color matrices) .

This is solidly in the realm of "unlikely to be feasible to happen".

**Comment by Trubuss** [comment]
Mm, all right. I didn't know how much work would be put into it. I thought it was worth mentioning.
