### ISSUE TITLE
Deep-frying an ear of corn won't make corn chips

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#6407]
**Problem Description**:
Putting an ear of corn into the deep fryer produces deep-fryed ear of corn instead of corn chips like the code and wiki say it is supposed to.

**What did you expect to happen**: 
Corn put in the deep fryer should become corn chips.

**What happened instead**:
Deep fryed corn was produced instead of corn chips.

**Why is this bad/What are the consequences:**
The code says that the corn should become chips, though the botany update might have changed the corn id or something along those lines.

**Steps to reproduce the problem**:
Get an ear of corn and put it into the deep fryer, then wait for it to come out.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I found this in the code for the deep fryer:
86 /datum/deepfryer_special/corn_chips 
87 	input = "corn" 
88 	output = /obj/item/weapon/reagent_containers/food/snacks/cornchips

**Comment by FalseIncarnate** [comment]
This wasn't updated properly with the new botany system changing how produce is handled, but i'm working on it already. thanks for the report though!
