### ISSUE TITLE
Job timer reset itself

### ISSUE THREAD

**Issue by shazbot194** [ParadiseSS13/Paradise#6429]
**Problem Description**:
The timer that lets you play heads reset when I started playing again after a month of not playing.

**What did you expect to happen**: 
I could play heads

**What happened instead**:
I wasn't able to play as a head until the timer counted down again.

**Why is this bad/What are the consequences:**
People who play heads such as myself (not so much lately) can't play their roles and it might be possible if it happens to a lot of people for there to be no heads in a round.

**Steps to reproduce the problem**:
I'm not sure how to reproduce it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I'm not sure what caussed this, the timer is almost up so I doubt anything needs to be done in my case, but I am wondering if anyone else is having this problem.
![a23f2836dba948b49bf6397a1ee7a1a5](https://cloud.githubusercontent.com/assets/22019537/22870366/0efc5d88-f153-11e6-9624-c299ffc92881.png)
(this is on my account where I have at least a month worth of time in game)

**Comment by taukausanake** [comment]
Oh boy, I should check my play times now

**Comment by Crazylemon64** [comment]
@shazbot194 Was the month worth of game time between Jan 02 and Feb 02?

**Comment by shazbot194** [comment]
I think so.

**Comment by Kyep** [comment]
@Crazylemon64 This issue can be closed. Not exempting old players from the requirements was a deliberate decision. We did give everyone a month to accumulate hours, before requirements were turned on. We knew that people who did not play in that month would lose access until they came back to the server and played a few rounds again. That was intended.

**Comment by shazbot194** [comment]
Thank you for informing me. I was not aware of this and will be closing this issue.
