### ISSUE TITLE
Moving the mech fabricator/disassembling it causes it to be impossible to re-create.

### ISSUE THREAD

**Issue by Fishocalypse** [ParadiseSS13/Paradise#643]
The spacepod fabricator could not be constructed, even with the parts necessary to build it.(upgraded or not)

BONUS ZONE: There's a plasma requirement to build basic pods, but the mechanic gets no plasma(outside of taking it from engineering/asking mining)

**Comment by Telvayne** [comment]
Not sure if this goes here, but the fabricator must be used to finish the pod now, and the civilian armor requires Solid plasma, which is not available.  However, the Plasteel is still in the pod bay, which is not used for anything pod-related anymore.  Perhaps they should be swapped?

**Comment by Fox-McCloud** [comment]
@tigercat2000
