### ISSUE TITLE
Hypodermic prickles isn't transferring chemicals when thrown

### ISSUE THREAD

**Issue by MischievousGremlin** [ParadiseSS13/Paradise#6437]
**Problem Description**:
The hypodermic prickles gene doesn't transfer reagents in plants when thrown at a target.

**What did you expect to happen**: 
Like the description of the wiki, i expected the tirizene berries i made to inject targets with tirizene when thrown at them, like a ghetto syringe gun essentially

This was the makeup of the plant i was trying to use http://puu.sh/u0Kl1/7b227cbf2b.png

**What happened instead**:
The berries splattered and the target had no tirizene in them, this was tested on three different people

**Why is this bad/What are the consequences:**
It removes a branch of gameplay from botanist, ghetto knockout syringe guns essentially and ways botanists can disable people breaking into botany to steal their spacedope

**Steps to reproduce the problem**:
1 Apply densified chemicals, liquid contents, hypodermic prickles to a plant
2 Give the plant some sort of chemical, tirizene for example
3 Chuck it at someone
4 No chemicals will be injected despite hypodermic pcikles

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Just an ordinary round of space station 13, nothing unusual.

**Comment by Fox-McCloud** [comment]
Could you please test this *without* a fruit that explodes when it hits something?

The fruit exploding is likely preventing you from being pricked---and I recall this being intentional, to prevent double proccing/benefits of certain chems that are dangerous on touch.

**Comment by MischievousGremlin** [comment]
I was told that I needed liquid contents to actually inject people with the chemicals which is what causes it to explode IIRC. I'll edit this when i test without liquid contents
