### ISSUE TITLE
AOE upgrade for KA's are broken.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6442]
**Problem Description**:
The AOE upgrade only damages mobs in a 3x3 area. It doesn't mine in a 3x3 manner like the hyper KA did.

**Comment by Markolie** [comment]
This one's not a bug - the AoE upgrade you get from the vendor is only supposed to target mobs with AoE but not turfs. In order to target turfs with AoE (or mobs and turfs) you need to get the upgrade from tendrils (not in yet) or research. I just tested this and confirmed it.

**Comment by Spacemanspark** [comment]
Huh.
@uraniummeltdown damn you
