### ISSUE TITLE
Industrial Welding Tool sprite is broken

### ISSUE THREAD

**Issue by mass595** [ParadiseSS13/Paradise#6444]
**Problem Description**:
The sprite for Industrial Welding Tools is now that of the default Welding Tool.
![welderissue2](https://cloud.githubusercontent.com/assets/25646281/22907278/44eca754-f216-11e6-8de7-edf77a95a797.png)
(Picture is of an Industrial Welder and a normal Welding Tool side-by-side)

**Comment by Anoonki** [comment]
I can confirm this.
I was really confused when I hacked an autolathe to get one.
This doesn't have a mechanical effect, it's just really confusing.
