### ISSUE TITLE
Unlimited Blood Syringes

### ISSUE THREAD

**Issue by Telvayne** [ParadiseSS13/Paradise#645]
Through a series of inject/draws, it is possible to get a syringe to drop below 0u inside, forcing it around to infinite (Or some semblance thereof).  I was able to fill up 500u worth of large beakers before I got bored and decided it was unlimited.  I will attempt to duplicate the issue as soon as possible.

**Comment by Fishocalypse** [comment]
(I feel as if there's some pattern here.)
I've had the same issue, but when the syringe was emptied out of 250 units of blood it couldn't hold reagents and just infinitely sucked them in with draw(for smaller reagent bottles around 30 units), effectively deleting reagents.
