### ISSUE TITLE
Minebot projectiles do not scale damage in pressure.

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#6453]
Minebots do 40 damage/shot even station-side

wewlads

**Comment by davidchan13** [comment]
Just watched terror bots get reamed by this cause mining bot was doing more damage than the red spiders with a half second delay (or less) per shot. Wew.

**Comment by Markolie** [comment]
Oh dear, looks like this is also the case on /tg/. Will investigate.
