### ISSUE TITLE
welding gas mask/goggles glitch

### ISSUE THREAD

**Issue by trexter555** [ParadiseSS13/Paradise#6457]
**Problem Description**:
putting on welding goggles or the welding gas mask while they're flipped up (so you can see) and then flipping them down doesn't impair vision like it should

**What did you expect to happen**: 
should impair vision when you flip them back down

**What happened instead**:
vision stays normal

**Why is this bad/What are the consequences:**
who needs welding implants when you have welding gas masks/goggles?

**Steps to reproduce the problem**:
flip welding g mask/goggles to 'up' position, put them on, use the button to flip them back down

kinda op

**Comment by Anticept** [comment]
This must be a recent thing because it used to work fine. Maybe a goonlighting related bug?

**Comment by KasparoVy** [comment]
I noticed this before both goonlights and my colourblindness PR once and I thought it was just me. Guess not.

**Comment by coldud13** [comment]
I had a similar problem as a plasmaman my vision was impaired with the welding mask even when it was flipped up.
