### ISSUE TITLE
Mindswap is force ghosting recipients and revoking respawn rights

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6458]
**Problem Description**:
Both changeling and wizard mindswap forces the recipient out of their body and ghosted, with respawn rights removed (can't even become an NPC or drone).

**Why is this bad/What are the consequences:**
This is an urgent issue. It's increasing admin load and kicking players out of a round completely.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
The recipient appears over their own body when the mind swap happens, leading me to believe that either it's not getting or passing the caster's mob info, or not actually moving control for the recipient to the caster's former body. The caster has NO issue, including the fact the stun is not being applied! **This is highly abusable right now!**

**Comment by Crazylemon64** [comment]
@Anticept This happens *every* time? What are the steps to reproduce?

**Comment by Anticept** [comment]
Mindswap a player. happens everytime as far as I know

**Comment by LightFire53** [comment]
Can confirm, the recipient is ghosted and the wizard is in. No KO either.

@Crazylemon64

**Comment by Jovaniph** [comment]
I can confirm that was an issue 2 day ago with me. I had to get FlattestGuiter to force me inside the swapped body during a changeling round when I automatically ghost.
