### ISSUE TITLE
Quantum telepad one way linking

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6462]
**Problem Description**:
What is the problem?
The ability to link quantum telepads one way only.

**What did you expect to happen**: 
Why do you think this is a bug?
Not really a bug. Just something that could potentially be abusable.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Potentially, this could be used to grief. Maybe useful for traitors, but dropping them in a box to be trapped is scummy.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Just build two telepads. Link only one. Or perhaps you build 3 and deconstruct one of them? I'm not 100% certain, I just know its possible.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I witnessed someone built one in the bar, which went to a locked room with atmosphere, but nothing else. You could not return as the telepad was not linked. This feels like it's on the "disposal trap" level of scummy play.

A simple solution might be not to allow the pad to work if there isn't a complete circular route of pads going back to the one they are standing on, and tells the player accordingly, but someone could wait until their target teleports and just decon one of them, which still leaves them abandoned offsite.

**Comment by Spacemanspark** [comment]
It's intentional, you have to manually link both together.
I do agree it could be used for rude things, but eh.

**Comment by Fox-McCloud** [comment]
Intentional, and not a bug, therefore a feature request--you can similarly nefarious things with teleporters.
