### ISSUE TITLE
Drone and borg modules with materials should not be removed when reaching 0

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6463]
**Problem Description**:
What is the problem?
Drone and borg modules with materials should not be removed when reaching 0

**What did you expect to happen**: 
Why do you think this is a bug?
Feature request.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Not important. Convenience.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Use a module like wire until you hit 0 pieces left. It disappears, requiring you to visit a cyborg recharger. I would prefer that it didn't so you could pick up materials and continue using the module. This is especially useful after a bomb goes off and knocks a large hole in the station... drones and borgs could quickly seal the breaches and being able to pick up more that is laying around would help a lot.

Also, the matter decompiler doesn't seem to exactly work with all module replenishments, like the light replacer.

**Comment by Fox-McCloud** [comment]
Feature requests do not belong on the Git.
