### ISSUE TITLE
Light replacer should pick up shards without inserting them with hands.

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6464]
**Problem Description**:
What is the problem?
Light replacer should pick up shards without inserting them with hands.

**What did you expect to happen**: 
Why do you think this is a bug?
Feature request

**What happened instead**:
How is what happened different from what you expected?
Right now, replacing a light drops the junk light on the ground. It has to be picked up with an empty hand and inserted into the replacer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I would prefer that clicking on a junk light with a light replacer inserts the shard (helps borgs and drones), AND please skip dropping the light on the floor when a replacer is used on a socket. That's just unnecessary.

**Comment by Fox-McCloud** [comment]
Feature requests do not belong on the Git.

**Comment by Anticept** [comment]
Ah. I'll check the forum then.
