### ISSUE TITLE
Ghosts cause bananium floors to squeak when walked over

### ISSUE THREAD

**Issue by Nakijimakai** [ParadiseSS13/Paradise#6467]
**Problem Description**:
Ghosts cause bananium floors to squeak when walked over

Why do you think this is a bug?
Ghosts are supposed to be spoopy, not clowns.

**Comment by taukausanake** [comment]
but those squeaks are _spooooooky_

**Comment by Anasari** [comment]
literally unplayable

**Comment by DesolateG** [comment]
they walk so fast the sound lags out my ears..
