### ISSUE TITLE
Nuclear Operative Cyborg Spawning Issue

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#6472]
**Problem Description**:
One cyborg being called in consumes both spawn items in a the players inventory

**What did you expect to happen**: 
I bought two cyborg spawning items from the uplink hoping to get two cyborgs to help with the mission

**What happened instead**:
I triggered both to start searching for a willing ghost to take over as a cyborg with about 10 seconds between each item interaction. When the first cyborg spawned in (a medical one if it helps) it canceled the other cyborg coming in (an assault one). When I examined the items they both gave me the "out of power" message indicating that they have been used.

**Why is this bad/What are the consequences:**
A syndicate cyborg is a whopping 50 TC's in the uplink. If there happens to be no admins online when this issue happens it can be severely detrimental to a nuclear operation. Even more so since to buy more than one cyborg would usually mean that the Ops declared war, making the resistance all the much greater.

**Steps to reproduce the problem**:
Have at least two syndicate cyborg spawners in ones inventory. Attempt to have each look for a suitable host with about 5-10 seconds between activation of the objects. Once one cyborg spawns check both objects to see if they both were "consumed". I am not sure if type matters but when this bug happened to me I had attempted to call in a medical cyborg and a assault cyborg in respective order.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was a nuclear operative gamemode and we had declared war upon the station. I was the teams leader and I had used the uplink generated from declaring war to buy the cyborg spawners. I had contacted an admin (although I cannot remember who it was specifically) and they had refunded the cost of the lost cyborg.

**Comment by Markolie** [comment]
This is very strange, I can't see anything in the code that would cause this. Is it possible the same player got selected and picked for both activations, thus fulfilling both but only spawning one borg?

**Comment by ktoma36** [comment]
Possibly, I triggered both to start searching for ghost with little time between them. I am not sure how that would work though.

**Comment by Contrabang** [comment]
Has been fixed at some point
