### ISSUE TITLE
Immovable rods are borked

### ISSUE THREAD

**Issue by DarkPyrolord** [ParadiseSS13/Paradise#6484]
**Problem Description**:
Immovable rods won't even spawn in when the event is triggered.

**What did you expect to happen**: 
An immovable rod would spawn and slam through a few walls.

**What happened instead**:
It gave the prompt to follow it in deadchat, but didn't spawn in at all.

**Why is this bad/What are the consequences:**
Breaks the event and doesn't allow it to be used.

**Steps to reproduce the problem**:
Open debug verbs, trigger immovable rod event, watch as nothing but an announcement happens.

**Comment by KasparoVy** [comment]
Might've just gotten busted by the wizard rodform PR

**Comment by uraniummeltdown** [comment]
Could not reproduce, works fine when I trigger the event on my test server

**Comment by LightFire53** [comment]
It worked just fine when we ran metastation.

Although, is it meant to constantly target engine containment when you spawn it?

**Comment by taukausanake** [comment]
The rods want to court Lady Tesla (fuck that was horrible)

**Comment by uraniummeltdown** [comment]
Nope, it's just generally meant to go from one end of z1 to another

**Comment by SamHPurp** [comment]
> Although, is it meant to constantly target engine containment when you spawn it?

Shouldn't be.
