### ISSUE TITLE
CC Faxes are in Comic Sans

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6485]
**Problem Description**:
All faxes sent by admins to players ignore formatting and are sent in comic sans.

**What did you expect to happen**: 
Fax to be sent as normal, not in comic sans, formatted.

**What happened instead**:
Comic Sans, ignored some formatting, like <small>.

**Why is this bad/What are the consequences:**
Because admins aren't clowns. _OR ARE WE?!_

**Steps to reproduce the problem**:
1. Be Admin
2. Send fax to any fax machine.
3. HONK.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This is responding to either CC faxes sent to, well, CC, or the create a fax button in the fax manager panel.

**Comment by LightFire53** [comment]
@Crazylemon64 game breaking bug, pls fix.

**Comment by taukausanake** [comment]
I see no problem with this
