### ISSUE TITLE
Blocked from most jobs

### ISSUE THREAD

**Issue by sandbag747** [ParadiseSS13/Paradise#6497]
**Problem Description**:
I seem to be blocked from most jobs as part of a time requirement, the mentors Necaladun and Saul Argon told me I should be exempt because as of Fed, 28 I have 1084 days of playtime on paradise so directed me here
**What did you expect to happen**: 
As stated above, I was told by mentors I should have been exempt from the playtime requirement
**What happened instead**:
I could not access half or so of the jobs
**Why is this bad/What are the consequences:**
It would probably deter long time players from playing, or at least the jobs they are accompanied to playing
**Steps to reproduce the problem**:
Just tried to set my occupation settings
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by tigercat2000** [comment]
#6429 

Did you play often/at all between Jan 02 and Feb 02?

**Comment by sandbag747** [comment]
Not real often, got a new job that severely limits my free time. Maybe 3 rounds in that period

**Comment by sandbag747** [comment]
I checked out that other issue, I was not aware older players were exempted. I don't have the time to accumulate so many hours for most of the jobs. Thanks for the quick reply tigercat2000
