### ISSUE TITLE
Telecommunications monitor creates EXTREME lag

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6502]
**Problem Description**:
Telecommunications monitor creates EXTREME lag

**What did you expect to happen**: 
You can abuse it so badly that the admins would even have trouble stopping you.

**Why is this bad/What are the consequences:**
Potential server grief at worse, harmless lag spikes at best.

**Steps to reproduce the problem**:
Let a round go for a while and generate a long chat log. Then go to the tcommsat telecommunications monitor and try to look at the communication history. Game will freeze.

**Comment by Taaketa** [comment]
#2953

**Comment by Fox-McCloud** [comment]
dupe.
