### ISSUE TITLE
[META] Mechanic's Office Permissions too strict for the Mechanic

### ISSUE THREAD

**Issue by Ralta** [ParadiseSS13/Paradise#6505]
**Problem Description**:
Mechanic cannot access the Engineering Foyer leading to the Mechanic's Workshop.

**What did you expect to happen**: 
Presumably, the Mechanic would need to access their workshop reliably.

**What happened instead**:
Door doesn't open with their access card.

**Why is this bad/What are the consequences:**
Mechanic can't get to work without always waiting for someone else to open the door.

**Steps to reproduce the problem**:
Be mechanic. Be unable to open the foyer door.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Metastation.

**Comment by Taaketa** [comment]
[META] Tag needed

**Comment by Ralta** [comment]
Woops! Thanks Taaketa. Fixed

**Comment by Aurorablade** [comment]
no Thats an oversight. The access is intended. its an oversight i forgot about when i put the workshop on the map.
