### ISSUE TITLE
Janitor Sign Bombs

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#651]
Janitor Sign bombs apparently have no timer to setting up, leading them to instantly explode on the janitor, as Tokochiro learned this round.

Also they have enough explosive power to expose multiple floor tiles to space, do not know if they are intentionally this powerful or not.

**Comment by ZomgPonies** [comment]
What? I thought they were ONLY supposed to blow legs off with a snarky little message about no running?

**Comment by Earthdivine** [comment]
We have had three people die from the explosion so apparently it got buffed somewhere?

**Comment by Fox-McCloud** [comment]
Fixed the huge explosion size (and damage).

I wasn't able to replicate the arming/timing issue as mentioned here. Is it possible he hyper-clicked it when he bought it and didn't realize he armed it?

**Comment by Earthdivine** [comment]
That seems very likely with the lack of click delay now.
