### ISSUE TITLE
[META] The whole station is hotwired

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6510]
**Problem Description**:
The whole station is hotwired by default.

**Why is this bad/What are the consequences:**
ITS NOT A GOOD THING. Death potential goes through the roof, as even benign experimentation can cause widespread death. Plus, power sinks have extremely high potential to RELEASE THE ENGINE.

**Steps to reproduce the problem**:
Just fire the engine up and check the bridge power computer. ABSURD POWER.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Engineering should have its own SMES just like the west one on boxstation, which acts like a backup battery just for the core of engineering and the emitters. The power monitoring SMES should just power the rest of the station.

**Comment by SamHPurp** [comment]
What could possibly go wrong?

But yeah, this should be a simple map edit to add in the power grid SMES, and removing any direct wiring.

**Comment by Anticept** [comment]
Added one more comment. This makes it extremely likely to release the engine by sapping power from the emitters.
