### ISSUE TITLE
[META]Death Bridge For All!

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6512]
**Problem Description**:
The shuttle bay space bridge controls is all access.

**What did you expect to happen**: 
To not have the required access as a civilian.

**What happened instead**:
The shutters all opened, revealing a massively powerful way to kill someone.

**Why is this bad/What are the consequences:**
It may be intentional, but that is a super lethal button that anyone can push. If someone is trapped in there, and you activate the button, Rest In Pieces whomever the unlucky soul is.

**Steps to reproduce the problem**:
1. Be a civilian on metastation
2. Locate Shuttle Bay Space Bridge
3. Push button.
4. Space yourself.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Metastation madness! YAY!

https://i.gyazo.com/e617347f8c7ce67f745c414c436800f5.png

**Comment by jughu** [comment]
That was auctally intentional to make you feel they open and close when the cargo shuttle arriveres but yeah i degree with the access

**Comment by KingPhilipIII** [comment]
I've actually escaped an officer on TG by running down the bridge, and then when the officer pursued me I closed the shutters on him, locking him in space.

**Comment by Fox-McCloud** [comment]
Given this is a 1:1 port of TG's map, I'm pretty sure this is intentional--especially with what KingPhillip (who plays on TG a lot) has stated, as such this a feature request change and not an actual mapping issue.
