### ISSUE TITLE
[META] Atmos alarms are located like on box station.

### ISSUE THREAD

**Issue by warior4356** [ParadiseSS13/Paradise#6513]
**Problem Description**:
The atmos computer shows the map for box station, and alarms go of constantly thinking they are in space.

**What did you expect to happen**: 
The alarms to be in the correct places.

**What happened instead**:
The map was wrong, and the alarms were always going off.

**Why is this bad/What are the consequences:**
Cant tell where the atmos isues are.

**Comment by Markolie** [comment]
To fix this, we need to find a solution for the NanoUI minimap. It needs to either generate automatically (and perhaps be cached for future rounds?) at round start or we need separate minimaps for each map.
