### ISSUE TITLE
Phrase with accents not appearing in the chats. Like á é í ó ú.

### ISSUE THREAD

**Issue by etrenat** [ParadiseSS13/Paradise#6523]
When anyone speak with an accent |é á í ó| (which is common in our language) on OOC chat or IC chat, the phrase with the accent don't appear at the chat. Below a few screenshots demonstrating the issue.

![xcvzxcv](https://cloud.githubusercontent.com/assets/25797661/23102653/ea980ed6-f68b-11e6-90e3-92e61ade7961.PNG)

![qer](https://cloud.githubusercontent.com/assets/25797661/23102655/f2f4aea4-f68b-11e6-9c07-007a0c6112cc.PNG)

![zcxv](https://cloud.githubusercontent.com/assets/25797661/23102657/fa7ac5aa-f68b-11e6-9768-a163ac26726d.PNG)

**Comment by Markolie** [comment]
@tigercat2000 A Goonchat encoding issue perhaps? Would https://github.com/d3athrow/vgstation13/pull/13537 fix this?

**Comment by davipatury** [comment]
https://github.com/d3athrow/vgstation13/issues/13158, https://github.com/d3athrow/vgstation13/issues/11682

**Comment by etrenat** [comment]
But this is for vgstation /=. Sorry im newbie in Github.

**Comment by Markolie** [comment]
You filed this correctly! We're considering porting the fixes for this issue from vg to Paradise, as we ported Goonchat from them.

**Comment by etrenat** [comment]
Ok, i will wait for this fixes. Thanks for the help ;D.

**Comment by tigercat2000** [comment]
@Markolie Those aren't complete, but yes, they are designed to help cases exactly like this.

**Comment by Shadow-Quill** [comment]
@Anasari Appears to be fixed.

**Comment by Spacemanspark** [comment]
Goonchat fixed this I believe
