### ISSUE TITLE
Shuttle engines the wrong way around

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6526]
**Problem Description**:
#6480 's new sprites have had the lefts and rights mixed up. The ones on the escape shuttle and arrival escape pods are fine... but Engineering, Security escape pods and arrival shuttle have them backwards.

**What did you expect to happen**: 
Engines should propel them

**What happened instead**:
Engines currently would cook the occupants

**Why is this bad/What are the consequences:**
Immurshuns

**Comment by uraniummeltdown** [comment]
The new shuttle engine sprites are actually correct, the old ones however had east and west mixed up and some mappers put the wrong dir on the engines. Dir = 4 and dir = 8 need to be swapped around for the incorrect engines

**Comment by SamHPurp** [comment]
So, a map problem, not a spriting problem.

Got it. @Crazylemon64 if you could alter the tags appropriately <3

**Comment by Markolie** [comment]
This is prevalent on pretty much every map file with a shuttle. Are you going to take care of fixing this @uraniummeltdown?

**Comment by uraniummeltdown** [comment]
@Markolie yeah

**Comment by Markolie** [comment]
Thank you, much appreciated!
