### ISSUE TITLE
Megaphones allows people with mute disability to speak.

### ISSUE THREAD

**Issue by Jovaniph** [ParadiseSS13/Paradise#6540]
**Problem Description**:
In the title

**What did you expect to happen**: 
Not be able to generate words when speaking with the megaphone while mute

**What happened instead**:
Being able to generate words when speaking with the megaphone while mute

**Why is this bad/What are the consequences:**
My immersion? I don't know.

**Steps to reproduce the problem**:
Grab a megaphone and use it while you have mute as a disability

**Comment by sothangel** [comment]
I believe this also permits abductors to speak.
