### ISSUE TITLE
Injecting oxygen does nothing to skrekbirbs

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6545]
**Problem Description**:
Only atmos oxygen seems to toxify them. Liquid oxygen doesn't?

**What did you expect to happen**: 
Oxygen is toxic to skreksbirbs!

**What happened instead**:
Liquid Oxygen **_isn't_** toxic to skrekbirbs!

**Why is this bad/What are the consequences:**
Its not a bug, more of an oversight. It does remove a creative way to fight vox.

**Steps to reproduce the problem**:
Go to chem. Dispense oxygen. Syringe and inject. No tox. Screeeee.

**Comment by SamHPurp** [comment]
Is it supposed to be toxic if ingested? I just assumed the toxin buildup was more due to their lungs having nothing to process.

**Comment by Anticept** [comment]
I think for consistency, any oxygen should tox them. As said, its an interesting way to kill a vox target if you wanted to go that route.

**Comment by Allfd** [comment]
It used to do things, I remember how good medbay was at killing Vox by injecting them with things to help with their Oxydamage.

**Comment by Doukhan** [comment]
Yeah dexalin meds used to be deadly for vox before we got new!chem.
Be nice to have that back.

**Comment by KasparoVy** [comment]
Salbutamol/perfluo don't kill Vox because all they do is reduce oxyloss (suffocation damage).

Oxygen in their system, however, should probably cause toxins

**Comment by taukausanake** [comment]
Well, how would it work you think? Given Vox breathing in oxygen you'd imagine they CAN breath it into their blood system but that's how they get tox damage. Similarly, if you get oxygen injected directly into the blood stream then it would do more tox damage as it would be in higher concentration

**Comment by KasparoVy** [comment]
Alright, I've got it figured out. I thought briefly of making injected reagents whose IDs matched a mob's breath type heal oxyloss but that doesn't sound quite as balance friendly.
