### ISSUE TITLE
Remember how the Anita hairstyle had some rogue pixels? The Adhara one has some, too.

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#6547]
Like ~~muh special snowflek copyrighted style~~ the Anita hairstyle previously had, the Adhara has some grey pixels. I've marked them with hot pink in the below images, because I'm too lazy to make a pr, but not too lazy to report this.

![](https://i.gyazo.com/750b817891f2d72650a1797a0cb41c9e.png)

![](https://i.gyazo.com/db16f10f372e68cae1686c8b6a9ce385.png)

**Comment by KasparoVy** [comment]
Thanks for highlighting it again. I'll have a fix up when I get back in a few hours
