### ISSUE TITLE
"Gravity!" on the russian derelict station

### ISSUE THREAD

**Issue by TYoung86** [ParadiseSS13/Paradise#6551]
**Problem Description**:
What is the problem?
Gravity returning to the station affects other locations than the station.
**What did you expect to happen**: 
Why do you think this is a bug?
Duh.
**What happened instead**:
How is what happened different from what you expected?
No other locations should be affected by the station's gravity generator.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Suddenly, "Gravity!" ... on the russian derelict.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by TYoung86** [comment]
The russian derelict also actually has gravity on interior tiles, but no gravity generator.

**Comment by taukausanake** [comment]
Now that you mention it, I think the derelict DOES have gravity on it. Weird...

**Comment by TYoung86** [comment]
Yeah, when someone was futzing with the gravity generator, I thought the
admins were trolling. I kept getting 'Gravity!' and getting knocked down.

**Comment by DanteRU0312** [comment]
TGstation derelict actually has it's own gravgen, i think.

**Comment by taukausanake** [comment]
Let's give the derelict one that is unpowered with maybe a dead APC so you can give it gravity. Sounds like the best answer to this
