### ISSUE TITLE
Plasmamen helmets do not protect from facehuggers

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#656]
The facehugger just leaps straight through your helmet, ripping your mask off and infesting you, no way to counter it without outright avoiding any contact with facehuggers.

Not sure entirely if this is intended behavior, given the fact that they cannot actually remove it and thus are permanently susceptible to the facehuggers.

**Comment by Earthdivine** [comment]
Plasman suits are children of Soft Suits, aren't they? If they are then it makes sense they don't protect against huggers, as Soft Suits don't.

**Comment by fj45** [comment]
Softs suits should maybe protect.

**Comment by tigercat2000** [comment]
This is really probably a feature request, not a bug, given that it would (presumably) be simple to add the correct flags to the plasmamen subtype suits.
