### ISSUE TITLE
Cannot make rice in new botany

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6561]
**Problem Description**:
Grinding rice stalks is not making rice, and thus cannot be used in recipes

**What did you expect to happen**: 
Rice is a needed reagent. Can't make it right now.

**What happened instead**:
Could grind rice in old botany.

**Why is this bad/What are the consequences:**
It's annoying, but not game breaking.

**Steps to reproduce the problem**:
Grind rice stalks. Get plant matter, not rice. Rice is missing as a reagent in the stalk (at least, thats what the mhelp reported when I prompted them to check)

**Comment by taukausanake** [comment]
@Fox-McCloud you dun goofed
