### ISSUE TITLE
Fax machine bug

### ISSUE THREAD

**Issue by Jared12100** [ParadiseSS13/Paradise#6565]
**Problem Description**:
After I logged into the fax machine i can't log out

**What did you expect to happen**: 
Because logging out is normal

**What happened instead**:
I didn't log out

**Why is this bad/What are the consequences:**
Anyone could use the fax machine.

**Steps to reproduce the problem**:
Log into a fax machine. Send a file. Try to log out. Fail.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
![faxbug](https://cloud.githubusercontent.com/assets/25945910/23198127/940745a2-f89b-11e6-96b2-4939e6e83750.png)

**Comment by Jared12100** [comment]
Okay so i cant take a photo of the fax screen....

**Comment by tylerh95** [comment]
Just reporting that I've replicated this issue about five minutes ago while playing. Sent some faxes, tried to log out, no dice. I tried doing it under the following conditions: 
* no ID inserted, no paper inserted. 
* ID inserted, no paper inserted. 
* ID inserted, paper inserted. 
* No ID inserted, paper inserted.
