### ISSUE TITLE
Magistrate Bridge Access

### ISSUE THREAD

**Issue by tylerh95** [ParadiseSS13/Paradise#6567]
Magistrate doesn't have bridge access, but should have it.

I think it is comparable to how his SOP counterpart, the NT Rep, does have bridge access.

**Comment by Fox-McCloud** [comment]
This is a feature request; as such, it has no place on the git.

**Comment by LightFire53** [comment]
The other things I could agree with them having is a command swipe and an announcement system. That said, as fox pointed out, unless you have code to back this up with, you are going to have to find a coder or code it yourself. Pull requests require code, and belong on git. Feature requests lack code, and belong on the forum.
