### ISSUE TITLE
Spacepod Mining Lasers

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#6569]
#**Problem Description**:
What is the problem?
Spacepod mining lasers dont fire. At all. They still use power

**What did you expect to happen**: 
Why do you think this is a bug?
Its meant to fire but it only uses energy.

**What happened instead**:
How is what happened different from what you expected?
It didnt fire.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Mining spacepods are obselete and they are really useful.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Put a mining laser in a space pod.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It happens in any gamemode.

**Comment by DesolateG** [comment]
Might be a glitch caused by modular KAs
