### ISSUE TITLE
Death Alarms work while comms are down

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6571]
**Problem Description**:
The comms message for a death implant alarm triggering still happens even when comms are down

**What did you expect to happen**: 
Comms are down. No messages should get out.

**What happened instead**:
Comms message regarding a death of the RD just happened.

**Why is this bad/What are the consequences:**
Removes counterplay of downing comms to silently silence a command member.

**Steps to reproduce the problem**:
Death implant someone.
Kill comms.
Kill that someone.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing of note.

**Comment by Necaladun** [comment]
Could be justified that they're one use SBRs.

I like the idea of shutting down comms as a counter to them though.

**Comment by SamHPurp** [comment]
I see that it could be intentional to still allow those messages to go through. But maybe then only to people with station bounce, or near an intercom? Rather than to anyone with a headset.

I still think I'd prefer it if it didn't though with comms down due to counter-play possibilities.

**Comment by Markolie** [comment]
Yea, this is more of a feature request. The way it works right now is that it sends a message like a station bounced radio, which ignores telecomms completely.
