### ISSUE TITLE
Blob picks a player to tease

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6572]
For @Kyep 

**Problem Description**:
The new blob event, picks a player to insert into the blob... then after a time, it puts someone else in the blob.

I got picked for the blob, got up to 32 resource or so... then it stopped gaining resource... and not long after, a resource blob appeared... another player was given my blob slot.

Amusingly they couldn't even find me on the player panel afterwards to ghost me either.

**What did you expect to happen**: 
If you get selected for blob... you should be the blob!

**What happened instead**:
I got forced out of the blob after a 15 or so seconds as the blob.

**Why is this bad/What are the consequences:**
I got teased by rolling well on my favourite role, then having it stripped away 👎 

**Steps to reproduce the problem**:
Event blob proc
Sign up.
Have someone else sign up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing too extraordinary, it was a tot/ling round.... and blob procc'd at 1:30 into the shift.

Admins on at the time that can verify the issue is real: Tully, Cian, Necaladun.

**Comment by Nakijimakai** [comment]
I was the blob the took his spot and yes this happened.

**Comment by Markolie** [comment]
@Kyep

**Comment by Taaketa** [comment]
This has also happened in the past with Xenos and Admin forced player candidate to fill in when someone goes afk. I reported it sometime ago but I forget when and don't have time to reference the report.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/6470/files is probably the cause.

Not sure how, though. I never noticed this while testing it.
