### ISSUE TITLE
Nuke Ops always ends with Crew Major Victory

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#6584]
**Problem Description**:
It appears no matter what conditions are met, at the end of the round with Nuke Ops, it appears to always display Crew Major victory, no matter if the crew left the disk on the station or the nuke was detonated within the station.

**What did you expect to happen**: 
If the Shuttle leaves with the Disk on board, the Crew wins a Major Victory.
If the Shuttle leaves with the Disk still anywhere on the station, the Syndicates win a Minor Victory.
If the Bomb detonates in the station successfully and the syndicate shuttle escapes, the Syndicate wins a Major Victory.
If the Bomb detonates in the station successfully but no syndicates manage to escape, no-one wins.

**What happened instead**:
It appears to always display 'Crew Major Victory' stating the crew managed to get the disk off the station.

**Why is this bad/What are the consequences:**
Syndicate Operatives cannot greentext.

**Steps to reproduce the problem**:
Blow up the nuke on the station on Nuclear Emergency.

**Comment by FreeStylaLT** [comment]
Terrorists never win.

**Comment by Spartan6** [comment]
"Five years ago, I lost 30,000 men in the blink of an eye. And the world just fuckin' watched."
