### ISSUE TITLE
My mentor PM was the same color as an admin one

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#6585]
**Problem Description**:
![](https://i.gyazo.com/3331da1ecccb48763c963ccf5f707e20.png)
I PM'd another memetor and apparently it showed up in the same color as an admin PM (to the person receiving it.). Rather ironic and amusing considering the message, but still shouldn't show up like that nonetheless. After this message it went back to the correct blue color.
I have zero idea if this is a recurring thing or a one off case, PurpleGenie just told me about it.

**Comment by Necaladun** [comment]
I checked perms at the time actually, he was just +mentor for sure.

**Comment by Necaladun** [comment]
Oh, and it showed up as light blue to me. 
¯\_(ツ)_/¯

**Comment by SigholtStarsong** [comment]
I'm pretty sure this isn't a bug. If you direct-message someone via PM, it comes up angry admin red.

**Comment by Spacemanspark** [comment]
I clicked on his name in the chat to PM him, didn't search his name with the command.
Additionally I went to test this out just now.
![](https://gyazo.com/ad8e3ec99fe1039a5988df5686e6013e)

**Comment by Anticept** [comment]
Sounds like it was appropriate for it to be badmin red anyways!
