### ISSUE TITLE
Mistform can be traceable

### ISSUE THREAD

**Issue by AndriiYukhymchak** [ParadiseSS13/Paradise#6592]
**Problem Description**:
Antagonists with mistform can leave trails when they in that form

**What did you expect to happen**: 
Floors and walls are not painted with oil or blood in completely random places for completely random reason

**What happened instead**:
![image](https://cloud.githubusercontent.com/assets/5380208/23330032/30247262-fb4d-11e6-8297-48dd566ba63b.png)

**Why is this bad/What are the consequences:**
Allows you to detect the round type by seeing a trail that goes INSIDE the wall

**Steps to reproduce the problem**:
Stay on top of robot remains. Shadowwalk into wall. Voila - painted wall

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This round just ended

**Comment by Citinited** [comment]
Could not reproduce
