### ISSUE TITLE
Cortical Speech Shortcut Broken

### ISSUE THREAD

**Issue by scrubmcnoob** [ParadiseSS13/Paradise#6593]
**Problem Description**:
Using :X to talk in cortical talk yields no message at all.

**What did you expect to happen**: 
You should be speaking in hivemind

**What happened instead**:
Nothing appears.

**Why is this bad/What are the consequences:**
It's annoying setting default language to cortical speak and confuses people. It should simply be :x for chatting in borer chat.

**Steps to reproduce the problem**:
Be a borer and type say :x message
Nothing will appear.

**Comment by MarsM0nd** [comment]
Might be an issue with the vocal cords, which get activated by :x, and since whatever handles that says it's a simple mob, doesn't have an organ, says it's done, and as such, the message gets lost.
