### ISSUE TITLE
Maintenance drones can knock on firelocks at a distance.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#6594]
**Problem Description**:
Maintenance drones can knock on firelocks at a distance.

**What did you expect to happen**: 
Maintenance drones being unable to knock on firelocks at a distance.

**What happened instead**:
Maintenance drones can knock on firelocks at a distance.

**Why is this bad/What are the consequences:**
Maintenance drones can knock on firelocks at a distance.

**Steps to reproduce the problem**:
Unequip tools, click on firelock.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Doesn't matter if there's anything in the way. Drone is the one who knocks.

**Comment by pinatacolada** [comment]
AI does this too

**Comment by SigholtStarsong** [comment]
Cyborg confirmed for same issue.

**Comment by Crazylemon64** [comment]
@Markolie

**Comment by Markolie** [comment]
Can be closed!
