### ISSUE TITLE
[GOOFCHEM] General goofchem complaint issue-thready-thingy?

### ISSUE THREAD

**Issue by Fishocalypse** [ParadiseSS13/Paradise#662]
-Silver Sulfadiazine is impossible to create without silver
-Flurosulfuric acid makes LITERALLY FUCKING NOTHING
-Styptic powder is impossible to create(American spelling of Ammonium)
-AAAAA NO MORPHINE GOOF PLEASE
-Fireball on CLF3 lasts a second, doing next to nothing

More reported as I bumble along

UPDATE:
-Synthflesh is currently not creatable due to no clonexadone, wrecking cloning

**Comment by Fox-McCloud** [comment]
the fireball+CFL3 or any pyrotechnic chem is a larger issue that likely isn't going to be resolved until LINDA gets ported.

**Comment by Fishocalypse** [comment]
Oh dear, mixed synthmeat and synthflesh up.

-The reagent heaters and coolers are missing from the research department

**Comment by Fox-McCloud** [comment]
Already been addressed

**Comment by Fox-McCloud** [comment]
All of these should now be fixed!

**Comment by IAmBigCoat** [comment]
The medical borg/bot still synthesizes some old chems in its hypospray. Can't put them in beakers and things, though. Doctor's Delight is still completely in play.

**Comment by Fox-McCloud** [comment]
@IAmBigCoat 

We've not reached that stage quite yet; new chems have been added in and are being tweaked+bugfixed.

Next will come killing off StarTrek chem.

**Comment by Fishocalypse** [comment]
-No gibsmoke, woe is SAA

**Comment by FalseIncarnate** [comment]
All botany plants still utilize old (now non-existent) chemicals. This means growing and harvesting just about anything will cause run times.

I will personally try and go through and update this to correct it. I suspect a few drinks will also need recipes adjusted.

**Comment by Flip-Sandwich** [comment]
meth is FUCKING INSANEly stupid

it makes you TELEPORT around and run at STUPID speeds and and then you fall down and literally cannot get up without being shaken up

I love it.

**Comment by Deanthelis** [comment]
Bicaridine is still required to fix Bone Snap, Charcoal isn't a substitute for Anti-Toxin when dealing with genetic issues, and so on. These need to be transplanted in for genetics to not horribly kill themselves or their test subjects.

**Comment by Fox-McCloud** [comment]
That's already been addressed in the current PR to axe StarTrek Chem.

**Comment by Fishocalypse** [comment]
Grinding down burnt messes doesn't give ????

I cant make bath salts

**Comment by Fox-McCloud** [comment]
should be fixed by: https://github.com/ParadiseSS13/Paradise/pull/700
