### ISSUE TITLE
Feeder Fish unbreedable

### ISSUE THREAD

**Issue by tylerh95** [ParadiseSS13/Paradise#6623]
Reported to me by a player, needs to be replicated for confirmation.

According to the person who reported it over mhelp, feeder fish eat each other and it makes them extremely difficult to breed.

**Comment by LightFire53** [comment]
Seems intentional if you ask me. It may be helpful to anyone trying to reproduce this if you edited the above into the format that is provided

**Comment by taukausanake** [comment]
Wouldn't the fish eating each other make them pop out a new fish for each that was bred? It might be better for them to not eat their own kind or make them not able to eat other fish to start with.
Semi-offtopic, am I the only one who thinks that these fish are tiniest fattest fucks around? Every time you look at them they look hungry inciting you to feed them. Maybe some timing should be added as well?

**Comment by FalseIncarnate** [comment]
Fish only breed if the following conditions are met:
1. There are at least 2 fish of ANY type in the tank
2. There is room for at least 1 more fish in the tank
3. There is a sufficient food level in the tank

Feeder fish convert themselves into food if the food level is low and they aren't the last fish in the tank, so if you stay close with a can of fish food, you can avoid this by feeding frequently.

That said, the aquariums need more tweaking, such as the food consumption rate, which I was planning on doing soon (this week if time allows) so I'll make sure breeding feeder fish isn't too tough.

**Comment by Fox-McCloud** [comment]
Sounds as though this is just lack of understanding on mechanics. Closing this.
