### ISSUE TITLE
Cannot see or remove items from plasmamen without removing their suits.

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#6624]
**Problem Description**:
What is the problem?

There is no way to see or remove items such as sunglasses from a plasma man without removing their suit and thus causing them to ignite.

**What did you expect to happen**: 
Why do you think this is a bug?
You should be able to see items they are wearing and remove them without having to injure or kill them.

**What happened instead**:
How is what happened different from what you expected?

In order to remove other items you have to remove their life dependant suit.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Can be abused, and can kill them if you want to do a thorough search.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Try to see items that a suit covers up and remove them, you cant

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

This feels like a major mechanical design oversight for a species whose life literally depends on wearing that suit in environments that aren't 100% plasma.

**Comment by Necaladun** [comment]
This...makes me wonder how they put them on in the first place.

But yeah, really feels like an oversight.

**Comment by davidchan13** [comment]
It's because their suit is an exosuit. The original plasmeme suit was a jumpsuit was a jump suit with a matching helmet/hood.

Not sure why we went to exosuit a when job specific suits are often missing features of their hardship counterpart, like tesla protection

**Comment by SamHPurp** [comment]
Its an exosuit, its the same reason you can't remove things from under people's void suits....

**Comment by Necaladun** [comment]
I do understand the reason behind why it can't be done, but it does cause a lot of unintended consequences - such as being unable to remove sunglasses without killing them so sec can flash them, or even strip them of stolen goods, etc.

The solution to it I'm not sure of.

**Comment by SamHPurp** [comment]
Vox and plasma snowflake suits for prisoners.

It takes time to equip, just like the straight jacket. and other than the 'no-interaction' thing it acts like it too. It replaces the exosuit slot with a new exosuit thing. Which enables people to remove things from them....

But even more crucially, it has a voxygen/plasma tank in the exosuit slot... that cannot be removed.

One of the big problems with Vox/Plasma into perma... they'll just break the glass and skiddaddle.

**Comment by DesolateG** [comment]
@samhpurp that's how I break out of perma with my vulp.

**Comment by Fox-McCloud** [comment]
>The original plasmeme suit was a jumpsuit was a jump suit with a matching helmet/hood.

Not sure why we went to exosuit a when job specific suits are often missing features of their hardship counterpart, like tesla protection

Nah, it started out as an exosuit, and TG later made it a jumpsuit; I'd like to do the same, here, but there's loads of complaints about it.

**Comment by taukausanake** [comment]
I think it's alright that plasmamen get space suits. Makes sure they don't burn out as much. Could you imagine one getting stabbed and then bursting to flames because the uniform got torn? Then again it makes you wonder if that would happen with exosuit...

If you can't take things off from under the exosuit then you shouldn't be able to put anything on from under it either. That seems like a reasonable solution. Too bad it might put plsmamemes on par with Kidan because glasses

**Comment by Fox-McCloud** [comment]
not applicable anymore
