### ISSUE TITLE
Pipe fitting on atmos table disappears upon placement.

### ISSUE THREAD

**Issue by Rommel459** [ParadiseSS13/Paradise#6625]
**Problem Description**:
in the southwest of atmospherics is a table, upon that table is a pipe fitting, when you try to install that pipe fitting, it disapears into the nether never to be seen again

**What did you expect to happen**: 
no other pipe fitting does this. most pipe fittings will either connect to the existing pipes you've installed next to them, or disappear until you install a pipe next to them and then reappear attached to that pipe 

**What happened instead**:
The pipe essentially despawns when you try to install it, it doesn't matter whether pipes are already connecting to it or not, if they aren't already there placing other pipes next to it will not respawn it.

**Why is this bad/What are the consequences:**
well, it breaks immersion for me at least quite a bit, i don't know why the server does this with the item,  but i suppose it might add more to lag in addition the item is mostly unusable for anything other than visual ambience

**Steps to reproduce the problem**:
pickup the pipe from the table, set it somewhere, wrench it to install.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by DesolateG** [comment]
@Rommel459 a pipe that isn't connected to anything will disappear... it's been like that for a long time. In order to see it again alt click on the tile while standing next to it and unwrench it from the interface window on the right.

**Comment by taukausanake** [comment]
You could also connect another pipe next to it, that normally updated the icon for me whenever I had invisible pipes. Pretty sure this happened with other pipes, dispensed and un/rewreched around

**Comment by Rommel459** [comment]
I understand both of those facts. this pipe disappears upon wrenching regardless of whether it's next to a connected pipe or not, wrenching in place a pipe next to it  doesn't affect it once it has disappeared.

This particular pipe fitting hasn't followed the laws of any other pipe fitting any time i've ever used it, i get that the issue i'm describing is similar to how unconnected pipes act normally, but it's a separate issue. 
I'll try to remember to post a couple screenshots tonight when i have more time if that helps.

**Comment by Rommel459** [comment]
here we have the pipe fitting in the lower left of the screen.
![new bitmap image 3](https://cloud.githubusercontent.com/assets/26057588/23401079/465b480c-fd5b-11e6-8ef4-1573e528acb9.jpg)
picked it up, and have placed it where a pump was previously located between two pipes
![new bitmap image 4](https://cloud.githubusercontent.com/assets/26057588/23401085/4bfde062-fd5b-11e6-8d96-222076ddb689.jpg)
I have wrenched it into place, thus despawning? the pipe fitting due to the bug
![new bitmap image 5](https://cloud.githubusercontent.com/assets/26057588/23401090/50ce67ce-fd5b-11e6-89e6-44f2caad8f68.jpg)
The pump can be reinstalled as though the pipe fitting isn't there. 
![new bitmap image 6](https://cloud.githubusercontent.com/assets/26057588/23401095/5596717a-fd5b-11e6-97f6-f2bc6dd71afa.jpg)

**Comment by Anticept** [comment]
(E) (C) (M) pipe_type = null 

That should be 0.
