### ISSUE TITLE
Borers inconsistent with inheriting colourblindness

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6626]
**Problem Description**:
Infested someone with Colourblindness, wasn't colourblind when in their head, only when I had Assume'd Control.

**What did you expect to happen**: 
When using the eyes of a host, regardless of control, the borer should see colourblindly.

**What happened instead**:
Only was colourblind when I had taken control of my host.

**Why is this bad/What are the consequences:**
Inconsistency's sake. Also it might convince borers to give up a host who is colourblind if they can't hack it. :)

**Steps to reproduce the problem**:
Be borer. Infest colourblind Unathi. No see colourblind, unless Assume'd Control

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing extraordinary.

**Comment by Crazylemon64** [comment]
Would need some `reset_perspective` handler to take care of that, though it wouldn't be too involved to do. It's not like mobs inside of a backpack lose their vision, either, though

**Comment by SamHPurp** [comment]
Right, but if you are literally latched into their brain, and using their organs for stuff like sight, it'd make sense.

**Comment by Crazylemon64** [comment]
This is veering closer to a feature request

**Comment by SamHPurp** [comment]
@Crazylemon64 Unsure I agree, its inconsistent to only have the colourblind gene when you are the one in control, rather than when you are just in that persons head.

**Comment by KasparoVy** [comment]
@SamHPurp Looking into this
