### ISSUE TITLE
MIDI from highlander playing even if you have admin sounds disabled

### ISSUE THREAD

**Issue by sugoikore** [ParadiseSS13/Paradise#6641]
Just that, also, the music volume is stupid high, you should fix for those that also have the midi turned on.

**Comment by tigercat2000** [comment]
Not a bug, highlander plays it's own sound.

**Comment by sugoikore** [comment]
Then allow to disable ALL musics in game.

**Comment by taukausanake** [comment]
At that point you might as well lower Dream Seeker's volume with the mixer or lower your speakers completely because there won't be much else playing sound-wise, except the murder and decapitation of your former crew mates

**Comment by Kyep** [comment]
If there is no way to mute it, then it should not be so loud.
Loud, unskippable audio is annoying.

**Comment by sugoikore** [comment]
taukausanake, that makes no sense, it's a workaround for something that has a easy fix.

The volume of the MIDI is broken and it should be mutable. Since we already have a way to mute music, why not use that? 

And this is not a feature, if you can justify the need for the music within the game design you can call it a feature, if you can't, it's just something that someone forgot to do.

**Comment by tigercat2000** [comment]
I don't really mind changing this. But that doesn't change that this isn't a bug, and doesn't belong in the issue reports.

**Comment by sugoikore** [comment]
It's a issue.

Anyway, not going to argue semantics, just make it play like admin music, at least. I think you should also lower the volume of the playback, but, if I'm not listening to it, it's when some admin decides to meme the shuttle, I'm ok.

**Comment by Fox-McCloud** [comment]
Most definitely a feature request, as such, it's going to be closed.

>Loud, unskippable audio is annoying.

BRB, making a PR to remove screaming, AI Vox, and Captain's alarm...

**Comment by sugoikore** [comment]
Yeah, it's the same thing, a sound that has game design value and a MIDI that someone put just because.

And it isn't a feature request, it is a fucking music, played by admin event that is playing.
