### ISSUE TITLE
Wolf O'Donnell gets two tails after cloning

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#6643]
**Problem Description**:
After reviving by cloning, changeling, is awoken with my tail and default vulp tail.

**What did you expect to happen**: 
To have my tail, not the default vulp tail.

**What happened instead**:
I am a two tail dog demon.

**Why is this bad/What are the consequences:**
I mean, multiple tails are great but looks weird.

**Steps to reproduce the problem**:
Cloning Wolf O'Donnell

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Cloning, or Changelings when they take my body.
![vulp error](https://cloud.githubusercontent.com/assets/20448049/23444681/71296a7e-fdeb-11e6-91fa-e4998dffa27e.png)

**Comment by KasparoVy** [comment]
I was wondering who played that character.
Anyway, the issue isn't that you have two tails, it's that tail marking rendering isn't checking tails_allowed.
I'll sort that in a bit, thanks for the report.

**Comment by Trubuss** [comment]
I tried to get a better picture but couldn't. It actually does show two different tails. The white tip tail is mine. Then the first bushy tail is there as well. If I could get a picture behind it I could show that.

**Comment by KasparoVy** [comment]
The white tail-tip is the tail marking you seem to have on that character (judging by the ghost portrait). It doesn't render two whole tails, just the default Vulp tail and the old tail marking you used to have. Managed to replicate this on a local environment by killing myself in an autocloner.

**Comment by Trubuss** [comment]
Ah okay! Then you are right, sorry for thinking this was a bug. It is still little weird.
