### ISSUE TITLE
Captain PDA is Unexplodeable

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6645]
**Problem Description**:
Targeting the captain PDA with the Detomatrix cartridge is generating success admin logs, but no explosion.

**What did you expect to happen**: 
To either explode and generate a success admin log, or fail and generate a failure admin log.

**What happened instead**:
Doesn't explode, but generates a success admin log.

**Why is this bad/What are the consequences:**
Captain is immune to this traitor device, and yet no one else is.

**Steps to reproduce the problem**:
1. Purchase and Install your Detomatrix cartridge into your PDA.
2. Open the messenger on your PDA, locate the captain, and select the detonate button next to the captain's name.
3. Cry as the captain doesn't explode, while the following admin log appears: ADMIN LOG: lightfire53/(PR Officer Acaleus Thorne)(?) (FLW) just attempted to blow up PDA-HIU-288 (Captain) with the Detomatix cartridge and succeded

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Only appears to affect the captain; HoS, Warden, BS, and Sec officer PDA's all exploded.

**Comment by KasparoVy** [comment]
Maybe their PDA is extra robust.
Maybe it's a property of the Valu-PAK cartridge.

*shrug*

**Comment by taukausanake** [comment]
That would be a good feature of the Valu-PAK. Should the captain be that easy to take down or get at?

**Comment by Krausus** [comment]
The captain's PDA is explicitly flagged as unable to be detonated (`detonate = 0`). Problem is, this is checked by the code that's supposed to do the explosion, *not* by the Detomatix code that attempts to blow it up.
