### ISSUE TITLE
Janicart, more like jetpackcart

### ISSUE THREAD

**Issue by trexter555** [ParadiseSS13/Paradise#6646]
**Problem Description**:
Janicart can be used as a jetpack if someone else is in it and you're dragging it in space

**What did you expect to happen**: 
not being able to move around freely
**What happened instead**:
move around freely as if i had a jetpack

**Why is this bad/What are the consequences:**
janicarts are too op
**Steps to reproduce the problem**:
put someone in a janicart, drag it into space, move around freely

**Comment by taukausanake** [comment]
Duplicate of #4498 and #4803. Hasn't this been fixed?

**Comment by trexter555** [comment]
apparently not

**Comment by davidchan13** [comment]
It's a feature! /s

**Comment by taukausanake** [comment]
It should get a jetpack mod. How else is the janitor going to clean up all that space dust?
