### ISSUE TITLE
Night vision as rev does not toggle on.

### ISSUE THREAD

**Issue by Fraility1** [ParadiseSS13/Paradise#6650]
**Problem Description**:
Night vision as rev does not toggle on.

**What did you expect to happen**: 
I have experienced this twice now and it should work.

**What happened instead**:
Dark areas are still dark and not light.

**Why is this bad/What are the consequences:**
makes it hard for a rev to find bodies in dark areas.

**Steps to reproduce the problem**:
Play a rev toggle night vision. If it doesn't work there is a problem

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: traitor ling with a rev spawned in.

**Comment by Markolie** [comment]
You mean night vision from the goggles?

**Comment by ktoma36** [comment]
I had this issue also when I gotten reverent. It made it particularly difficult because the round was a shadowling round. The basic "night" vision worked in that nothing was hidden in the solid black fog of war, but it did not have any lighting.

**Comment by Jovaniph** [comment]
line 98 in revenant_abilities.dm is what is breaking the night vision

`to_chat(src, "<span class='revenwarning'>You are not close enough to siphon [target ? "[target]'s":"their"] soul. The link has been broken.</span>")`

more proof? https://gyazo.com/ab9ea9f97a0ab30995fac85dde99c07d

**Comment by Markolie** [comment]
Welp, so we're talking about revenants and not revolutionaries. I'm a derp.
