### ISSUE TITLE
Blanket antag ban are unreliable / doesn't work on conversion antag

### ISSUE THREAD

**Issue by Anasari** [ParadiseSS13/Paradise#6657]
**Problem Description**:
If you apply blanket antag ban by clicking on antagonist ban, it won't stop them from being a conversion antag.

**What did you expect to happen**: 
They get banned and ghosted

**What happened instead**:
Those bastards ban evaded and didn't got ghosted, isntead they got converted as usual.

**Why is this bad/What are the consequences:**
Justice must prevails

**Steps to reproduce the problem**:
1. Apply blanket, non-antag ban on a non-mentor/admin
2. Attempt converting them as a cult / shadowling
3. They don't get ghosted

**Comment by FlattestGuitar** [comment]
I believe this is also the case with security jobbans. We've had people evade these not knowing they had 'em.

**Comment by Markolie** [comment]
Yea, every antag ban should also check for the "Syndicate" ban which encompasses every antag.
