### ISSUE TITLE
Default all vents to internal pressure sensors.

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6667]
**Problem Description**:
What is the problem?
All vents are using an external pressure sensor (which is the air alarm), which works great on ZAS, but not so great on linda. 

**What did you expect to happen**: 
Why do you think this is a bug?
It's not a bug. But it's still something that should be changed.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It creates huge and sometimes dangerous fluctuations, especially when the air alarm is far from the vents.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Make a long hall. Put an air alarm in one side, and a vent in the other. There will be a *SIGNIFICANT* overpressure by the time the air alarm reaches safe levels.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Changing all vents to internal by default in all settings and on the map means a few things:

1. don't need an air alarm in every single little room or on both sides of every single divider. at present, an vent in a room without an air alarm will keep pumping air when the local zone's air alarm triggers. The pressures will reach obscene levels.
2. stops the oscillating pressure fluctuations that are caused by the slow equalization of LINDA, which can sometimes approach bone crushing pressures.
3. Plays better with LINDA, period.

**Comment by taukausanake** [comment]
Everyone's going to call this a feature request which does not belong on the GitHub.

Besides, we all know LINDA is shit

**Comment by Anticept** [comment]
Moving it over to suggestions.
