### ISSUE TITLE
Removing the trunk beneath a disposals chute causes you to go into nullspace when you enter it, and prevents you removing the chute

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#6671]
**Problem Description**:
Removing the pipe trunk beneath a disposals chute causes the chute to be unremovable, and sends anyone unfortunate enough to enter it to nullspace.

**What did you expect to happen**: 
I expected to be spat out of the chute. I also expected to be able to remove the chute with tools.

**What happened instead**:
I was sent to nullspace and could not leave without admin intervention. I was also unable to interact with the chute at all, even to remove it.

**Why is this bad/What are the consequences:**
This means you can create an impassible obstacle that eats anyone who enters it. This is bad for a number of reasons.

**Steps to reproduce the problem**:
1. Install a disposals trunk pipe.
2. Install chute on top of it.
3. Remove trunk.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Bug also appears to happen with disposals bins...

**Comment by Crazylemon64** [comment]
What a fitting avatar

**Comment by Citinited** [comment]
It's basically akin to an event horizon, yes. You can't even speak while in nullspace or hear the radio!

**Comment by Anticept** [comment]
Related https://github.com/ParadiseSS13/Paradise/issues/5728

**Comment by Anticept** [comment]
Somehow, I missed the part where you said you can't remove it either.
