### ISSUE TITLE
Colour blind Tajaran

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#6672]
**Problem Description**:
As a Vulp, I could see in the dark if I was colour blind. As a Tajaran, I cannot.

**What did you expect to happen**: 
Too barely see in the dark as a Tajaran

**What happened instead**:
Pitch black, cannot see without a light

**Why is this bad/What are the consequences:**
Not sure if this is a bug or not, I know my vulp can see in the dark, so why can't Tajaran?

**Steps to reproduce the problem**:
Pick Tajaran. Choose colour blind disability, go in to a dark area without light.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: All gamemode

**Comment by KasparoVy** [comment]
Did you have mechassisted or mechanical eyes?

**Comment by Trubuss** [comment]
No mech eyes or assisted. Colours do change, which are different from a colour blind vulp.

**Comment by KasparoVy** [comment]
I would've loved to've been able to view your mob's variables to see what your see_in_dark value was. That's strange, I don't see why that would've happened if you had organic eyes.

Were you wearing any glasses? Any eyewear at all?

**Comment by Trubuss** [comment]
Nope, nothing.

**Comment by Trubuss** [comment]
I am DJ Hharar if you want to see variables right now

**Comment by KasparoVy** [comment]
I don't have those rights. I suppose I'll just try to reproduce it myself.

So you spawned in with colourblindness and that was it, no eyewear, just walked into maint and saw the dark_view part wasn't working for Tajara?

I'm unable to reproduce this on a local branch with up-to-date (as of 15 seconds ago) code. I see the full 8 tiles into the dark as a colourblind Tajara.

**Comment by Trubuss** [comment]
I can't seem to duplicate,  but I can see in the dark after next round

**Comment by KasparoVy** [comment]
Wierd! Must be lag related or something.

**Comment by Lady-Luck** [comment]
@KasparoVy It was because there was a round where Goonlights was reverted for testing.

**Comment by KasparoVy** [comment]
Ah, right. Thanks a ton for clearing that up. I guess this could be closed then.

**Comment by davidchan13** [comment]
#ReasonsWhyWeHaveChangelogs
