### ISSUE TITLE
Vampire Bats Attack Thralls

### ISSUE THREAD

**Issue by scrubmcnoob** [ParadiseSS13/Paradise#6683]
**Problem Description**:
Vampire bats attack vampire thralls

**What did you expect to happen**: 
My wingman would be fine and the bats would attack non-thralls.

**What happened instead**:
My thrall got destroyed by swarms of bats.

**Why is this bad/What are the consequences:**
It fucked my thrall up.

**Steps to reproduce the problem**:
Thrall a person and spawn bats.

**Comment by SamHPurp** [comment]
Thats intentional isn't it?

**Comment by scrubmcnoob** [comment]
why would a vampire want their thrall eaten by their own bats
this seems very counterproductive to their evil plans 🤔

**Comment by SamHPurp** [comment]
As in, the spell's tooltip itself says "It'll attack everyone but the caster".

It gets quite messy when you start introducing, but the caster and its thralls... and how are the bats going to know who the thralls are?

**Comment by scrubmcnoob** [comment]
F.A.C.T.I.O.N.S
alright, i'll look into a PR for this then.
