### ISSUE TITLE
Job title preference doesn't get used on the ID.

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#6685]
**Problem Description**:
You join as a job that has more than one name, take a non standart name, you get equiped as the name, the crew manifest lists you as that, but your ID and PDA say the standart name.
The case i had was Medical Doctor, jobtitle Nurse, the char correctly get the diffrent jumpsuit, listed in the manifest as Nurse, ID and PDA said Medical Doctor.

**What did you expect to happen**: 
The ID and PDA should have said Nurse

**What happened instead**:
The ID and PDA said Medical Doctor

**Why is this bad/What are the consequences:**
The job title does have some RP aspects most of the time, for medical, there even is diffrent SoP for the diffrent title, join as Nurse, Id says medical doctor, which SoP do you follow now?

**Steps to reproduce the problem**:
Take any multi-named job, set it to a non-standart name, join as that job.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I'm only aware of this issue for certain for Medical Doctor, someone else did tell me it did happen to them with the coroner title.

**Comment by jughu** [comment]
Promotion? 🤔
