### ISSUE TITLE
Chaplain Dark Blessing

### ISSUE THREAD

**Issue by Varghh** [ParadiseSS13/Paradise#6702]
**Problem Description**:
If you click an open locker with chaplain Dark Blessing a copy of the item will be created inside

**What did you expect to happen**: 
Locker closing

**What happened instead**:
I got a Dark Blessing copy

**Why is this bad/What are the consequences:**
Well, actually i love the fact to multiply dark blessing, but you can't drop it, so it might be a problem, also unlimited weapons.

**Steps to reproduce the problem**:
Open a locker and then try to close it with the Dark blessing in your active hand

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing at all

**Comment by jughu** [comment]
This might be with all no drop

**Comment by Varghh** [comment]
I just tryed to make another one but if you move the dark blessing away and try to copy another one the first one will teleport back to the locker

**Comment by jughu** [comment]
Try this with god hand

**Comment by Varghh** [comment]
I just tryed to pick up the new one, i can have two dark blessing but i see in my "hands" that i have only one, but both my arms are blades

**Comment by Markolie** [comment]
I see the issue, will push a fix

**Comment by Anasari** [comment]
Also. If you cut off one arm's dark blessing the other one's gone too.

**Comment by Varghh** [comment]
My god is just too strong and twisted for this world

**Comment by Markolie** [comment]
This was only an issue with secure closets it seems.

Closet code is really a major mess.
