### ISSUE TITLE
AI go Blind

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6712]
**Problem Description**:
AI goes blind when you move the core off the sat via space walking

**What did you expect to happen**: 
Vision to be restored upon being repowered.

**What happened instead**:
Blindness

**Why is this bad/What are the consequences:**
It appears to be irreparable. I tried rejuvinating, depowering and repowering the APC, nothing.

**Steps to reproduce the problem**:
1. Unbolt AI from floor.
2. Take AI of satellite via space walk.
3. Enter Cyberiad.
4. Be blind.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Spacemanspark** [comment]
I haven't had this issue...

**Comment by SamHPurp** [comment]
Weird, every time I've had this happen, de-powering the APC so that you go into emergency power backup location mode (takes 1-2 mins), then re-enabling APC, works.

**Comment by taukausanake** [comment]
You also Issued this back in #5302 but closed it. Same thing as back then?
