### ISSUE TITLE
I can not unmuted adminhelp

### ISSUE THREAD

**Issue by darklink43** [ParadiseSS13/Paradise#6723]
**Problem Description**:
I can not hear adminhelp. nor when I click "Hear/silence adminhelps" in the preference menu do i get message in my chat telling me that it is on or off.

**What did you expect to happen**: 
I expected to hear a weird sound.

**What happened instead**:
I can not hear anything when a admin pm me.

**Why is this bad/What are the consequences:**
I got permabanned **TWICE** cause I miss the admins messages cause of all the shit that was going on IC. If I can not hear the sound then this is a problem.

**Steps to reproduce the problem**:
I don't even know how this happen, or if this is just a one time thing.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Sorry

**Comment by AndriiYukhymchak** [comment]
do you click _save preferences_ after you enable it?

**Comment by Krausus** [comment]
> nor when I click "Hear/silence adminhelps" in the preference menu do i get message in my chat telling me that it is on or off.

Oh... regular players aren't supposed to even have that. That verb literally does nothing for non-admins, as regular players are not intended to be able to silence the bwoink.

That said, we took a look at your preferences, and somehow, you *did* have the bwoink disabled. It's been fixed, so you should now hear adminhelps again.
