### ISSUE TITLE
Chat window dose not load.

### ISSUE THREAD

**Issue by hyperfox5** [ParadiseSS13/Paradise#6731]
**Problem Description**:
What is the problem?
My chat window never loads. I can play the game just fine, but I cannot see my own text or anyone elses. It just stays blank as soon as I log in. And I don't have access to the little gear icon either it not even there.
And it only happens on paradise station not other ss13 servers.

**What did you expect to happen**:

Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

I just loaded the game for the firat time and nuthin, blank chat box.
 
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

It only happens on paradise station, chat loads fine on other ss13 servers.

**Comment by Markolie** [comment]
What version of BYOND are you on? Try updating to the newest version or switching to the unstable/beta version.

**Comment by hyperfox5** [comment]
I tried updating and switching versions and still no chat. I have an older version of Internet Exsplorer, that wouldn't cause it would it? I'm working with an older computer I revived. This computer is on windows Vista, service pack 1.

**Comment by Markolie** [comment]
You could try updating it, IE causes a lot of issues in BYOND.

**Comment by hyperfox5** [comment]
That fixed it, updating to IE 9 solved my problems. Thank you for your help.
