### ISSUE TITLE
AOE KA upgrade from Mining Vendors does not work

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#6755]
**Problem Description**:
What is the problem?

The AOE upgrade from Mining Vendors does not create an AOE effect other than graphical. The AOE upgrade from Science does work.

**What did you expect to happen**: 
Why do you think this is a bug?

AOE upgrade should provide a AOE blast.

**What happened instead**:
How is what happened different from what you expected?

AOE blast doesn't happen other than graphical.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

2000 points lost on an upgrade that doesn't work.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Buy the AOE upgrade from the vendor. Apply to the KA. Fire at rocks, get no AOE effect.

Get AOE from RnD printer. Apply to KA, get AOE upgrade to work.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Markolie** [comment]
The AoE damage from the mining vendor only does AoE damage to mobs, not to turfs. To do AoE turf damage you need to get the one from research. So this isn't a bug.

**Comment by tigercat2000** [comment]
@Fox-McCloud ^ not a bug
