### ISSUE TITLE
Fluff sprite is unselectable as cyborg

### ISSUE THREAD

**Issue by SigholtStarsong** [ParadiseSS13/Paradise#6759]
What it says on the tin - my sprite has to be forced every shift.

**Comment by SigholtStarsong** [comment]
Apparently, this is an @Allfd issue?

**Comment by Allfd** [comment]
Umm, it could also be a crazy issue, looking at the config now!

**Comment by Allfd** [comment]
@SigholtStarsong @Crazylemon64 

Config is updated, will take place on whatever the round is after this post.  If it does not work PM me on discord but you should be all set.

Issue can be closed.

**Comment by SigholtStarsong** [comment]
@Allfd Still unselectable.

**Comment by Allfd** [comment]
Issue was corrected for specific borg names and a change to how sprites were handled removes all future concerns, safe to close.

**Comment by tigercat2000** [comment]
As Alffd said, all good now.
