### ISSUE TITLE
Job title selection is broken

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#6763]
**Problem Description**:
When choosing job preferences in the preferences tab or in character creation, clicking on a job title will not open the window to change the title.

**What did you expect to happen**: 
The title menu to appear when the job title is clicked on.

**What happened instead**:
No such menu appeared.

**Why is this bad/What are the consequences:**
Job titles appear to be broken, given that the menu always used to appear when you click on a job title in the preferences menu.

**Steps to reproduce the problem**:
Go to the character creation menu at the start of the game or the game preferences menu during the game (same thing essentially), then the "Job Preferences" button, then attempt to change a job title.

EDIT: This only seems to be affecting the preferences menu when you are in the game, it seems that you can still use the menu at the start of the game to change your titles.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Changing the chance of you getting a job (NEVER/Low/Medium/High) seems to be unaffected, which means that the whole menu is not broken, just the title changing window.

**Comment by SamHPurp** [comment]
@ModDownloading was this before the round started?

This happens when you've readied up already, and should work if you un-ready.

**Comment by ModDownloading** [comment]
No, this happens if you attempt to change your (future) title by going into the game preferences menu in-game.
Also, you cannot save or load slots in-game, which makes it hard to make new characters if you are spectating a match.
