### ISSUE TITLE
Diona Nymphs - Changeling Hivemind

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#678]
Diona Nymphs that steal blood from a Ling can hear and talk over the Hivemind.
This seems to be an oversight and should be resolved - They are unwittingly ruining rounds for people because of this bug.

As a side note, it may be possible for them to learn Trinary from humanized IPCs (IPCs whose heads were removed, placed on a human corpse, and cloned) and xenomorphs. Have not tested, only speculation.

**Comment by Earthdivine** [comment]
Already been posted here, #610 I believe

**Comment by Deanthelis** [comment]
Ah, didn't see it on the first page or so of issues. Closed, surprised it hasn't been handled, mostly because I've no idea how hard it'd be to fix.
