### ISSUE TITLE
Pyr'Kaeus slaughter demon 4th objective not working.

### ISSUE THREAD

**Issue by Aracino** [ParadiseSS13/Paradise#6780]
**Problem Description**:
The objectives for the demons to eat 10 people didn't count any of their meals.

**What did you expect to happen**: 
The objective always fails.

**What happened instead**:
It failed the objective with 0 meals eaten

**Why is this bad/What are the consequences:**
It's an objective that'll count at failed no matter the circumstance.

**Steps to reproduce the problem**:
Summoned the slaughter, ate half the crew, none of the crew will count when the shuttle docks at CC.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Cult round, this is a bit of info

The cult wins! It has succeeded in serving its dark masters!

Cultists escaped: 0
The cultists' objectives were:
Objective #1: Convert 15 crewmembers (30 cultists at round end). Success!
Objective #2: Sacrifice Flintich Nassau-Owen, the Brig Physician. Success!
Objective #3: Bring the Slaughter. Success!
Objective #4: Offer 10 humans for Pyr'Kaeus's first meal of the day. (0 eaten) Fail!

**Comment by Aurorablade** [comment]
That's not for slaughter demons to eat people that's for the cultists to sacrefice 10,crew members

**Comment by Anoonki** [comment]
@Aurorablade If that were the case, it still doesn't work.
I sacrificed three or four people in escape before the shuttle arrived.

**Comment by Aracino** [comment]
...Why though? The objective of the demons is to kill people, going to be hard to sacrafice people while your doing that.

**Comment by Markolie** [comment]
Looks like it wasn't counting the sacrifices at all.
