### ISSUE TITLE
Changling Bugs

### ISSUE THREAD

**Issue by Necaladun** [ParadiseSS13/Paradise#6788]
**Problem Description**:
A couple of bugs of late reported with Lings:

After transforming, they can't absorb any more people, and get the same message as if full, even at 3 people.

They're getting impersonate objectives on IPCs which doesn't seem intended.

**What did you expect to happen**: 

Not that.

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**

People ahelp me to fix it and I can't.

**Steps to reproduce the problem**:

You'll see the objectives. For lings, absorb a few DNAs, then transform.

**Comment by Markolie** [comment]
I can't reproduce the sting issue (transforming is properly resetting the number of stings you can perform), but will fix the IPC issue.

**Comment by SheepFighter** [comment]
By the by, the speech-patterns thing is slightly broken. It's no big deal, but it could be symptomatic of worse. Basically, if you swap bodies, then absorb your old one, you get things you said whilst in it.
