### ISSUE TITLE
Borg Keyboard shorcuts 

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#6790]
**Problem Description**:
Borgs aren't able to enable emergency door access with ctrl+shift+click like AI's

**What did you expect to happen**: 
The door would enable emergency access 

**What happened instead**:
You examine the item 

**Why is this bad/What are the consequences:**
Slows down Borgs when activating emergency access 

**Steps to reproduce the problem**:
Be a borg, use ctrl+shift+click

**Comment by tigercat2000** [comment]
not a bug, borgs use this hotkey for examine

**Comment by orelbon** [comment]
Could it made to be the same as the Ai then?

**Comment by tigercat2000** [comment]
Yeah, this isn't a bug.
