### ISSUE TITLE
Terror Spider Hallucigen Debuff persists after cloning

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6792]
I'm not 100% on how terror spiders work, but I do know they do something that makes you hallucinate. I got hit by it, died, got cloned, and still hallucinated.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/blob/58b4425b5ce87ccc75a61e265adc4972334874d0/code/modules/mob/living/simple_animal/hostile/terror_spiders/chem.dm#L46

Their spit contains a venom that causes hallucinations.

It was never meant to persist across cloning, though.

@davipatury given that you changed hallucinations recently, any idea what is going on here?

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/6679 now fixes this.

**Comment by Kyep** [comment]
Turns out the problem was that her venom was not depleting properly. I've replaced her venom with a one-time hallucinogen, similar to how changeling sting works.
