### ISSUE TITLE
Terror Spider Queens can still lay eggs as a corpse

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6793]
Heard about this in ghost chat, the queen terror spider said she could still lay eggs as a corpse.

**Comment by Kyep** [comment]
A fix for this will be included in the PR.

Not a super-big deal, though. Corpses of TS decay quickly, and Queen has an egg timer too. Its unlikely she could lay more than one egg while dead, and even this would die quickly to a few hits (given the fact she died, you have to assume there are hostiles around).

**Comment by Kyep** [comment]
I believe this was fixed in the last TS PR.

**Comment by Kyep** [comment]
I have tested this on the live server, I can confirm this bug was fixed, and the issue should be closed.
