### ISSUE TITLE
Airlock power logic is broken

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6803]
**Problem Description**:
The door power logic appears to be broken in regards to multitooling. Someone in discord was asking me about hacking doors. They swear they cut both power wires, so I went codediving to examine if there's more than just main and backup, and sure as hell there is! See https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/wires/airlock.dm#L13

`var/const/AIRLOCK_WIRE_MAIN_POWER1 = 2
var/const/AIRLOCK_WIRE_MAIN_POWER2 = 4
var/const/AIRLOCK_WIRE_DOOR_BOLTS = 8
var/const/AIRLOCK_WIRE_BACKUP_POWER1 = 16
var/const/AIRLOCK_WIRE_BACKUP_POWER2 = 32`

That said, of interest are a few places:

https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/wires/airlock.dm#L92
and 
https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/wires/airlock.dm#L102

Cutting them works properly. Cutting either AIRLOCK_WIRE_MAIN_POWER1 or AIRLOCK_WIRE_MAIN_POWER2 cuts power on main systems, AIRLOCK_WIRE_BACKUP_POWER1 or AIRLOCK_WIRE_BACKUP_POWER2 cuts backup.

HOWEVER.

https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/wires/airlock.dm#L168
and
https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/wires/airlock.dm#L179

are NOT working properly! Pulsing AIRLOCK_WIRE_MAIN_POWER2 or AIRLOCK_WIRE_BACKUP_POWER2 is NOT triggering power for them. Main and backup 1 are working correctly.

**What did you expect to happen**: 
Because the code logic is supposed to allow pulsing either main or either backup to 

**What happened instead**:
The code says otherwise.

**Why is this bad/What are the consequences:**
It isn't important, but it is something that isn't working to the clear intention of the developer.

**Steps to reproduce the problem**:
Grab multi tool and screwdriver. VV the door, look up wires in datums, and cross reference with the airlock wires file. You will find that pulsing primary2 and secondary2 do nothing, despite the fact the code above says it should.

**Comment by Anticept** [comment]
@SamHPurp

**Comment by tigercat2000** [comment]
that would be because this syntax is fucked lol
multiconditions in a switch are comma seperated, not logical OR'd together
these should look like `if(AIRLOCK_WIRE_MAIN_POWER1, AIRLOCK_WIRE_MAIN_POWER2)`

that said it's probably better to rip it out than fix it

**Comment by Lady-Luck** [comment]
It's inconsistent with wirecutting as well, actually. One of the backups will cut power for a bit if snipped, but the other backup will only cut power IF main power has been snipped previously.

**Comment by Anticept** [comment]
@tigercat2000 it should be consistent with wire cutting. if not, then we should remove the second primary and second backup wires.

**Comment by Anticept** [comment]
@Lady-Luck Just to be clear, by design, airlock backup power is not supposed to do anything at all, unless the primary power is cut. That said, I'm still not 100% on what the original issue that you brought up was, but we can clearly see there's issues regarding these extra wires anyways. To fix them will probably take more than just couple one liner fixes.

**Comment by Lady-Luck** [comment]
Right - one of the backups DOES temporarily halt power if cut, even if no other wires have been cut (which is what led to this in the first place, me thinking it was main or secondary).

**Comment by Anticept** [comment]
So basically, doors have primary power, and they have secondary power. Let's not talk about wires for a moment, lets just talk about how the power system works and pretend there is only one wire for each.

When a door is in an unaltered state, backup power is off, main power is on.

Pulsing backup power first will start the 60 second timer on backup, but has NO effect on the door power mode because main power is on.

Conversely, if you pulse main power first, it starts the 60 second timer for main. This causes the door to lose power, because backup power has a delay of 10 seconds. Main power is still counting down from 60.

If you pulse BOTH main and backup, both of those power modes count down from 60 seconds, meaning the door is offline for the entire duration.

Cutting the wire completely disables that power mode that the wire was related to. So if you cut main power, it is permanently disabled, but backup power will come online after 10 seconds. Cutting backup power without touching main does nothing to the door. Cutting both SHOULD permanently disable door power.

Now, according to the discovery here as a result of your testing, Main power 1 and 2, and backup power 1 and 2, should not change any of this logic. It just means that messing with either wire group should offline the power mode it is connected to.

**Comment by tigercat2000** [comment]
> it should be consistent with wire cutting. if not, then we should remove the second primary and second backup wires entirely.

that is what i meant
being broken for this long they might as well not exist

**Comment by Anticept** [comment]
I would, honestly, just prefer that.

Besides, someday we might have more interesting uses for those door wires, especially if someone gets around to making vault doors really complex, like was originally planned!
