### ISSUE TITLE
It is impossible to deconstruct chem dispensers/chem masters

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6806]
Given the recent attitude on here regarding everything being deconstructable, I've always found it really, really annoying how you can't do anything with these machines even if you really need to. The only tool they interact with is the multitool, which when you zap it onto a chem dispenser enables 'mad scientist mode', which just enables a 'Toxin' option that's pretty much useless.

**Comment by uraniummeltdown** [comment]
The ones you can't interact with are the roundstart ones, I'm guessing to prevent crippling medbay by antags walking in and quickly screwdriver+crowbarring the machines. The chem machines you can build from RnD boards can be upgraded/(de)constructed.

**Comment by Lady-Luck** [comment]
Ugh, I hate inconsistencies like that.

I feel like they should work like computer consoles where you can't move them but you can deconstruct them.

**Comment by Anticept** [comment]
This actually is annoying, and they aren't upgradeable either. I do see where @uraniummeltdown is coming from.

That said, I feel that there SHOULD be a delay in crowbaring machines. 5-10 seconds. Right now you can ninjadecon with a macro if you wanted to be a shitter.

**Comment by uraniummeltdown** [comment]
Yup there definitely should be a delay on crowbarring machines, I'd say 4-6 seconds so that people have time to react.
