### ISSUE TITLE
Greys can't project thoughts after using Mutadone

### ISSUE THREAD

**Issue by DevilishMilk** [ParadiseSS13/Paradise#6809]
**Problem Description**:
After taking mutadone, people with the Grey species can no longer project thoughts.

**What did you expect to happen**: 
I expected to keep the project thoughts ability.

**What happened instead**:
There was no ability after taking mutadone.

**Why is this bad/What are the consequences:**
If you're a Grey using wingdings, you no longer have any way to speak.

**Steps to reproduce the problem**:
Be a grey, take mutadone and you can no longer project thoughts.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)** It happens in any gamemode, if you take mutadone at all, you'll no longer have the ability you get by default as a Grey.

**Comment by Anticept** [comment]
This appears to be the code that sets the telepathy:

https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/species/station.dm#L734

I think this is the mutadone processing:

https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/medicine.dm#L668

Don't have a clue how this works right now, but maybe that might make it easier for bugfixers.

**Comment by DevilishMilk** [comment]
Well, I'm really glad you guys are onto this this quickly.

**Comment by PJB3005** [comment]
```dm
/datum/reagent/medicine/mutadone/on_mob_life(mob/living/carbon/human/M)
    M.SetJitter(0)
    var/needs_update = M.mutations.len > 0 || M.disabilities > 0

    if(needs_update)
        M.dna.struc_enzymes = M.dna.struc_enzymes_original
        M.dna.SE = M.dna.SE_original.copy()
        domutcheck(M, MUTCHK_FORCED)

        // Might need to update appearance for hulk etc.
        if(ishuman(M))
            var/mob/living/carbon/human/H = M
            H.update_mutations()
    ..()
```

Try that code, might work. Can't test though.

**Comment by DevilishMilk** [comment]
I think there should be a Para test server to test new PRs.

**Comment by fludd12** [comment]
You can make a local server to test your changes, you know. PJB simply was too busy to, at the time.

**Comment by taukausanake** [comment]
Yeah but some PRs need multiple people to test if something works and some (most) people don't know/can't port forward for some reason. An official server would be nice but then you'd need to manage which PR is tested when and keep track of them if you run the server. It can get messy. Maybe the OP should be in charge of any testing and other maintainers could join in. Again port forwarding will need to happen but that's unavoidable

**Comment by tigercat2000** [comment]
DNA code is gross.
