### ISSUE TITLE
Transforming into another person does not clear HUD warrant

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6810]
Similar problem to #6775, you'd expect that if your DNA changes to someone else's, your arrest warrant would be cleared, but that is not the case.

**Comment by Citinited** [comment]
You sure it's not just that the person is carrying a wanted ID?

**Comment by Lady-Luck** [comment]
Quite positive. Had to ahelp it to get the warrant removed.

**Comment by Citinited** [comment]
Fair enough, was just checking!
