### ISSUE TITLE
Ling Space Suits

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#682]
Ling Space suits apparently don't protect against the cold of space. Might have been an oversight when we made space cold again.

**Comment by Fox-McCloud** [comment]
Wasn't able to replicate this.

I became a ling, put on my suit, then hopped into space...no cold damage--cast off my space suit and I instantly started taking cold and pressure damage.

Are you sure the person wasn't cold *first* then put on the space suit? It takes time for the cold to wear off and sometimes putting a suit on when you're already cold can delay how quickly you warm back up.

**Comment by Earthdivine** [comment]
Might have been, the ling had died in space before a helping about it
