### ISSUE TITLE
Collaborators are useless.

### ISSUE THREAD

**Issue by gt33** [ParadiseSS13/Paradise#6828]
WHAT USE ARE THEY BESIDES A FREE EOC CHARGE OR DEATH?

**Comment by Spacemanspark** [comment]
Why did you post this here?

**Comment by LightFire53** [comment]
They are meant to be people who you can RP with who would be willing to help you to some degree.

That said, the setting it checks is your NT relationship, and generates the list from anyone who has it set to the negative values. Which could be a security officer.

In short, it is a relic from the Medium level of Role Play. Your guess is as good as mine as why people don't capitalize on it.

**Comment by SamHPurp** [comment]
@LightFire53 lets remain positive about increasing roleplay levels, not mourn the death.

Some simple edits to this could be good, but I'd argue it isn't an 'issue' more a 'feature request' and should be on the forums.

Such as, ban mindshielded roles from coming up as potential collaborators.
