### ISSUE TITLE
Blank books

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6835]
**Problem Description**:
There are a number of round start books in departments such as Engineering that are 'blank' that should be full of information.

**What did you expect to happen**: 
Colleague released the engine. After he got revived, I hit him a few times with the guide to setting up a singularity, then told him to sit down and read it... I expected him to learn.

**What happened instead**:
The book was blank, and I had to sheepishly give him paper and a pen and have him write the book for me to prove he knew how to do it. These books should have info in them!

**Why is this bad/What are the consequences:**
Having them rely on OOC resources like the wiki when cool IC things already exist.

**Steps to reproduce the problem**:
Enter engineering, Go to the table above the Emitter SMES's... over half those books are blank.

**Comment by Necaladun** [comment]
I swear we've fixed this 20 times. They just keep resetting fml.

**Comment by DesolateG** [comment]
I just thought that was apart of the joke @Necaladun 


"How to do optimized cloning!" "The book is completely blank!"

**Comment by taukausanake** [comment]
I think part of the problem is that the books are referencing the wiki pages. Would it be more possible to have the books reference some other web page/ HTML file that is kept on the server or better yet in the code for easier editing?

**Comment by FalseIncarnate** [comment]
I keep meaning to fix this. Thank you for reporting it so I can remember to do it. (dibs)

**Comment by Mitchs98** [comment]
Still exists.
