### ISSUE TITLE
OOC Messages with £ symbol don't display

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6836]
**Problem Description**:
No messages including the £ symbol will display in OOC.

**What did you expect to happen**: 
My message to be sent!

**What happened instead**:
My message wasn't sent.

**Why is this bad/What are the consequences:**
Oppressing muh currency!

**Steps to reproduce the problem**:
Talk about glorious British currency. Be denied.

**Comment by Anasari** [comment]
WAD, Paradise opposes Brexit

**Comment by SamHPurp** [comment]
Euros don't work either my dear @Anasari , just checked for you.

**Comment by Anasari** [comment]
Fuck the european too

**Comment by SamHPurp** [comment]
Yeah well Hong Kong.... damn, dollars. You win this round.

**Comment by fludd12** [comment]
This is more of a problem with rendering unicode in goonchat than anything - unicode likes to break lots of things. Consider using the emoticon system instead?

**Comment by tigercat2000** [comment]
This is pretty much just a BYOND bug, the only way we can really fix it is by using PJB's library for getting around the unicode input restrictions.
