### ISSUE TITLE
Mining Reward Machine eats IDs if power dies

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6839]
**Problem Description**:
If power dies while you are claiming your sweet sweet mining rewards, you can't get your ID out of the machine.

**What did you expect to happen**: 
My ID should automatically pop out, or gain the get ID verb like the HoP console has.

**What happened instead**:
ID Eaten.

**Why is this bad/What are the consequences:**
Totally stuck in that room

**Steps to reproduce the problem**:
Place ID into Mining reward machine. Power dies. Cry

**Comment by taukausanake** [comment]
#5920 maybe?
