### ISSUE TITLE
PA Console screen sprite is on at round start

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6840]
**Problem Description**:
The PA console screen sprite is lit up as if its turned on and ready when at round start. When this isn't the case, its neither wrenched nor even wired...

**What did you expect to happen**: 
Things without power shouldn't appear to be powered.

**What happened instead**:
Incorrect sprite shown

**Why is this bad/What are the consequences:**
Inconsistency/error, could confuse newbies

**Steps to reproduce the problem**:
Start server. Look at PA console lit up.

**Comment by Anticept** [comment]
It also turns off once you wrench it.

**Comment by SamHPurp** [comment]
@Anticept thanks for highlighting that PR, I meant to mention that it started then!
