### ISSUE TITLE
You can hear cult chat while unconscious

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6841]
**Problem Description**:
You can hear cult chat while you are unconscious.

**What did you expect to happen**: 
Dreaming sweet dreams.

**What happened instead**:
I heard my cult brothers screaming in victory as they began summoning demons.

**Why is this bad/What are the consequences:**
You're unconscious, you should be missing these messages while you are out of it.

**Steps to reproduce the problem**:
Be cult. Receieve anesthesia in surgery. Have a cult brother chat using the commune action button.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Cult

**Comment by Necaladun** [comment]
Seems unintentional, but I think it can stay. It makes sense they can talk through your dreams, after all.

**Comment by Anticept** [comment]
It also makes it possible to discover them early, so I don't think that's a good idea, @Necaladun

**Comment by Anticept** [comment]
Additional idea: if you DO want to keep this going for effect, then I propose an anti-valid method: the game records snippets of acolyte chat and plays them back to sleeping people occasionally even on non-cult rounds.

**Comment by tigercat2000** [comment]
@Anticept 

>It also makes it possible to discover them early

I'm pretty sure this only occurs if you are a cultist, you hear the other cultists regardless of current state, which is probably unintentional but not bad.

**Comment by Anticept** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhh I derped SO HARD.

I thought sam was saying ANYONE could hear them.

**Comment by tigercat2000** [comment]
@Fox-McCloud I'm 99% sure this isn't actually a bug, it works the same way on /tg/

**Comment by Fox-McCloud** [comment]
Taking @tigercat2000 word for it.

**Comment by SamHPurp** [comment]
@tigercat2000 @Fox-McCloud Whether TGs works while asleep or not is neither here nor there for how -we- decide to implement it, surely?

Regardless if the current thought from the Maintainers/Headmins is that this is cool, then thats fine!

**Comment by tigercat2000** [comment]
@SamHPurp Context matters as to classifying this as an actual bug vs feature request, which we do to keep the issues section of the Github repo clean. Given that the rest of that file is nearly identical to /tg/'s, it's fair to assume that it was intended as they have not "fixed" it, and therefore this isn't a problem with our code.

**Comment by SamHPurp** [comment]
@tigercat2000 Aye, that all makes sense. We're saying this isn't a bug, but the door isn't shut on a 'feature' change to remove their ability to hear cult chat while asleep.

Personally I won't be bothered to make that PR as the appetite seems that actually people are fine with it.
