### ISSUE TITLE
Welding tool sprite doesn't update on/off

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6844]
**Problem Description**:
The inhand welding flame sprite doesn't update when you turn on/off your welder. But it does update if you turn it on, belt it, remove it from belt again.

**What did you expect to happen**: 
Turning on welder shows the welder on.

**What happened instead**:
Looked like it was turned off.

**Why is this bad/What are the consequences:**
Inconsistent, the sprite exists, it should update. Can't see immediately if others have their welders enabled.

**Steps to reproduce the problem**:
hold welder in hand. Activate welder. See no flame.

Hold welder in hand, activate welder. Belt welder. Hold welder in hand. See flame.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tried this with the emergency welder, the Upgraded welder and the Experimental welder, all had this issue... assume its the case for all the variants.

**Comment by KasparoVy** [comment]
Can't reproduce. Just tested on live and emergency welder, regular welder, all other welders seem fine.

**Comment by SamHPurp** [comment]
@KasparoVy Reproduced... made you a little video to show it:

https://www.youtube.com/watch?v=tqj9zTjwKF4

**Comment by Tayyyyyyy** [comment]
I just tested this. If you hit the z key to activate the welder, the sprite on the character updates, but if you click on the welder, the character on the sprite doesn't update. Also, if the welder dies while you're welding, the sprite on the character doesn't update, but the sprite in your hand does.

**Comment by tigercat2000** [comment]
Is this still an issue?

**Comment by SamHPurp** [comment]
@tigercat2000 unable to get into game to test it - but afaik it is still an issue.

Its around sprite updates being called by hotkey and not hand activation clicking, or visa versa.
