### ISSUE TITLE
Shooting fireaxe cabinet deletes cabinet and fireaxe

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6845]
**Problem Description**:
Shooting at the fire axe cabinet deletes it, and the fireaxe contained within.

**What did you expect to happen**: 
Expected it to break, drop the fireaxe to the ground... or nothing at all..

**What happened instead**:
It just straight up deleted the cabinet and the fireaxe.

**Why is this bad/What are the consequences:**
There are only 2 fireaxes on the map. Straight deleting one of them seems silly.

**Steps to reproduce the problem**:
Equip gun, I chose a .357.... shot the cabinet a few times on the bridge. Despair

**Comment by Fox-McCloud** [comment]
I just looked at the fireaxe cabinet code.

My soul died a littel inside.

**Comment by taukausanake** [comment]
I dunno, I like it :)
