### ISSUE TITLE
Health analyzer nades do not explode when gibbed by wiz magic

### ISSUE THREAD

**Issue by sugoikore** [ParadiseSS13/Paradise#6847]
**Problem Description**:
The health analyzer didn't trigger upon being hit with the wizard magic

**What did you expect to happen**: 
The grenade being triggered when killed

**What happened instead**:
It didn't trigger at all

**Why is this bad/What are the consequences:**
No working properly?

**Steps to reproduce the problem**:
Make a grenade with a health analyzer + igniter assembly, have it on your bag and get gibbed by the wizzard magic.

**Comment by Necaladun** [comment]
WAD I believe. When gibbed you're not even dead, you're just gone. No kill like overkill.

**Comment by taukausanake** [comment]
I didn't even know you could combine those things. Poor man's dead alarm?

**Comment by Crazylemon64** [comment]
If your body is destroyed outright, the analyzer doesn't get the chance to detect that you are injured, because at one moment, you're perfectly fine, and the next, you are no longer there. The health detector detects health, not death.
