### ISSUE TITLE
Autolathes keep hacked recipes if dehacked

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#6849]
**Problem Description**:
If you fix a hacked autolathe, it still allows you to construct hacked designs

**What did you expect to happen**: 
Autolathe stops displaying hacked recipes once it is fixed

**What happened instead**:
Autolathe should stop displaying these recipes once dehacked

**Why is this bad/What are the consequences:**
Not really bad but could lead people into thinking a department has no access to hacked designs when they do

**Steps to reproduce the problem**:
1. Hack autolathe.
2. Fix autolathe.
3. Observe available hacked designs

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Tested on two editions of the codebase I have, nothing else weird

**Comment by taukausanake** [comment]
Might be intentional? It's not like the designs have a requirement of hacked wire to exist, just to be unlocked. At least that's my thought on it. Fixing a wire isn't going to short out a machine's memory and remove things

**Comment by Citinited** [comment]
Possibly. If it's not an oversight then maintainers can provide feedback / close this
