### ISSUE TITLE
Station Bounced Radios don't transmit inside space pods

### ISSUE THREAD

**Issue by Tayyyyyyy** [ParadiseSS13/Paradise#6860]
**Problem Description**:
When inside a pod with an SBR, with microphone and speaker toggled to on, the speaker works, but the microphone doesn't transmit anything spoken. You have to get out of the pod to say stuff into the SBR. This happens whether you're in space or on station.

**What did you expect to happen**: 
I expected SBRs to work the same inside a pod as outside

**What happened instead**:
Words were spoken but nothing was transmitted

**Why is this bad/What are the consequences:**
You have to get in and out of the pod every time you want to say something if telecomms are down, making it really inconvenient.

**Steps to reproduce the problem**:
Enable SBR microphone, enter pod, and try to talk. Alternatively, enable the microphone on the pod. Neither works.

**Comment by pinatacolada** [comment]
you have to use :r I think to use SBR inside of pods, same for mechs

**Comment by Tayyyyyyy** [comment]
That worked! Thank you!
