### ISSUE TITLE
Ian the Medium

### ISSUE THREAD

**Issue by james5734** [ParadiseSS13/Paradise#6863]
**Problem Description**:
What is the problem?
I can see everything through walls and also see ghosts as Ian.
**What did you expect to happen**: 
Why do you think this is a bug? Its a bug because as far as I know Ian didn't sell his soul to see dead people and look through walls.

**What happened instead**:
How is what happened different from what you expected? I saw ghosts and stuff behind walls. People, pets, etc.

**Why is this bad/What are the consequences:** 
Why do you think this is an important issue?
If this bug continues metagaming will be very prominent as every player could respawn as Ian and tell who the ghosts are or search maint and see a murder in progress happen right behind two sets of walls.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I reincarnated as Ian, then I could see through walls and see ghosts.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. Nope

**Comment by LightFire53** [comment]
Pretty sure it's the cats that see the supernatural... :thinking:

**Comment by taukausanake** [comment]
Needs to be a feature. Animals can sense the supernatural or after death and rebirth. It's not like they can/should talk anyways.

Did something not get set properly when you went from ghost to Ian?

**Comment by james5734** [comment]
As far as I know, no. If I had to guess, the error happened because something in code displayed that I was still a ghost even though I was Ian.

**Comment by ktoma36** [comment]
I believe the AI, borgs, PAI's, cordial borers (passive/controlling host) and audio recorders can be used to communicate with animals effectively.

**Comment by taukausanake** [comment]
I can never understand Ian as a pAI. It's really strange and I'm supposed to with the Universal Translator? I know I've seen some other players understand a pug I played once

**Comment by alexkar598** [comment]
i dont think there is anything preventing animals fron talking to humans apart from good rp and admins

**Comment by tigercat2000** [comment]
This definitely doesn't happen normally, I'm not sure how to reproduce this.

**Comment by Shadow-Quill** [comment]
@Anasari
