### ISSUE TITLE
The Powered Crossbow doesn't work

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6866]
When you attempt to fire a makeshift bolt from the powered crossbow (with power, mind you) it just plays the disarm attempt sound and then the makeshift bolt disappears. Nothing else actually happens.

(Small unrelated issue if you're looking into fixing this: Now that plastic can be harvested from plastic flaps, it might be a good idea to remove plastic from the recipe so there aren't lots of flap disappearances around the station once it is fixed.)

**Comment by Spacemanspark** [comment]
Additionally, it no longer fits on my back.
I'm sad about this.
