### ISSUE TITLE
MetaStation - SciChem is part of Xenobiology, this is bad

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6871]
Come on. SciChem is breached all the time by accident. Making it part of xenobiology is just going to screw over xenobiologists when someone makes an oopsie.

**Comment by tigercat2000** [comment]
This definitely isn't a bug. Map feature requests go on the forums too.

**Comment by Lady-Luck** [comment]
We were told in game to report issues with the map on github.

**Comment by tigercat2000** [comment]
It's not an issue. It's a feature request.

**Comment by Lady-Luck** [comment]
is·sue
[ˈiSHo͞o]
NOUN
an important topic or problem for debate or discussion:
"the issue of global warming" · [more]
synonyms: matter · matter in question · question · point · point at issue · affair · [more]

**Comment by Aurorablade** [comment]
It's not an issue it's a map feature

**Comment by Lady-Luck** [comment]
OOC: Commandhat: Paradise are testing out an edited Metastation on Extended! Full map here, press fullscreen and doubleclick, then click+drag to explore: https://www.dropbox.com/s/uuiv5orxtffqt5p/metastation%20map.png?dl=0 --- Report issues (like robotics not having a posibrain) here: https://github.com/ParadiseSS13/Paradise/issues

**Comment by Aurorablade** [comment]
It's the design of the map and is on purpose . Those a feature and not something missing

**Comment by Lady-Luck** [comment]
Whaaaaatever

**Comment by Necaladun** [comment]
(like robotics not having a posibrain)
We want to pass over all actual mistakes and bugs first. That's what issues in the coding sense means. Eg, robotics is clearly meant to have a posibrain (As per cyb), but it doesn't because a mapper missed putting it in there

A forum post is better for these kinds of things that are this subjective, and not clear mistakes.

**Comment by commandhat** [comment]
This is an ingame copypasta I made because the admins were literally spamming announces with the issue report link.

I'm still correcting it ingame ("robotics not having a posibrain" is now "no airlocks")
