### ISSUE TITLE
META: 'Tinted Window' usage

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6878]
Not sure if this is actually a feature, but I notice a lot of windows use the more 'tg' style windows that's all like, one object, rather than our style which is 4 reinforced windows.

![](https://i.imgur.com/TvnqUq7.png)

(also, some that are Paradise-style use regular windows instead of reinforced windows, but that might not be a mistake either?)

**Comment by commandhat** [comment]
The four reinforced windows is a tgstation building tile. If someone hits it, it changes into four reinforced windows.

**Comment by Lady-Luck** [comment]
>The four reinforced windows is a tgstation building tile. If someone hits it, it changes into four reinforced windows.

Yes I'm aware of that. It's not the way we do our maps though, traditionally. So I'm not sure if this was intentional or not.

**Comment by Fox-McCloud** [comment]
Intentional; not a bug.

**Comment by tigercat2000** [comment]
All windows on metastation are full tile windows, not 4 panes, definitely isn't a bug
