### ISSUE TITLE
Armed NPC mobs cant aim at pAI's in their mobile form

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#688]
this can be easily seen at the gateway map with syndicates armed with machine guns, if you stand near an NPC mob with a gun it will target you and shoot at you but none of the bullets will hit you, you can abuse this to make one of them shoot other NPC mobs.

**Comment by Spacemanspark** [comment]
Same deal happens with with emitter blasts or the machine turrets on the syndicate outpost.

**Comment by TheDZD** [comment]
This has to do with the fact that the simple_animal AI does not aim directly at other mobs when shooting, but rather at turfs, and you can't hit a mob with its density var set to 0 (able to share a space with other mobs, such as pAIs or carbons using the Rest verb) unless you specifically target it.

**Comment by TullyBurnalot** [comment]
@TheDZD Mob density is apparently intentional, as per yourself, please close when possible.

**Comment by TheDZD** [comment]
This is technically still an issue, as neither this, nor having pAIs be able to shove people around is ideal.

**Comment by taukausanake** [comment]
Well why not just make it so NPCs don't target mobs with density 0? Or a whilelist so they don't?

**Comment by jughu** [comment]
Tactical PAI distraction

**Comment by jughu** [comment]
Keep this it makes the pai usefull in its way and it cant do anything without a owner anyways

**Comment by jughu** [comment]
FEATURE

**Comment by alexkar598** [comment]
Pai are made to not interact with the world so them not being aimed by npc is perfectly fine

**Comment by Joonasm** [comment]
The issue was them Shooting at the pAI but missing every time which meant you could distract the mobs and help out others with it. I believe this might be fixed now so i'll close it

**Comment by taukausanake** [comment]
Sure would be nice if it was referenced somewhere
