### ISSUE TITLE
Gummy Bear's animation briefly turns into a space bear.

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6881]
![](http://i.imgur.com/FlvgwbB.gif)

**Comment by Necaladun** [comment]
Lmao...I'm kinda ok with this ascending from bug to feature.

**Comment by Fox-McCloud** [comment]
Intetnional

**Comment by FalseIncarnate** [comment]
Definitely not a bug. Gummy worm version briefly becomes a borer and alien larva. These things are made with space drugs, they are trippy.

**Comment by taukausanake** [comment]
Never even seen that. Amazing
