### ISSUE TITLE
META: All IVs can be walked over

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6889]
**Problem Description**:
IVs such as the one in the brig physician's office can be walked over.

**What did you expect to happen**: 
To be unable to occupy the same tile as them, as on Boxstation

**What happened instead**:
On top of it .Somehow.

**Why is this bad/What are the consequences:**
Inconsistent, looks goofy.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Metastation

**Comment by Anticept** [comment]
This is being changed so IVs don't have density and can be walked through on boxstation

**Comment by SamHPurp** [comment]
This can be closed it #6895 gets merged.

**Comment by SamHPurp** [comment]
This got merged. This issue can be closed! 🎉
