### ISSUE TITLE
Table Surgery is remarkably inconsistent

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6897]
For some reason, when you're dealing with someone on a table... starting surgery sometimes works, and then sometimes it doesn't, for no particular reason it feels like. Really dicked me over when I was short on time and trying to operate on a dead patient.

I think the main problem is that just doing the prepare step has a chance of failing, and if it fails that step, surgery can't happen at all until they move or lay down again. The prepare step should have a 100% chance.

**Comment by Fox-McCloud** [comment]
It's inconsistent because it's meant to be---it's like your hand "slipping up" during the actual surgery itself. If it fails, you whack the person instead.

The person does not have to lie down and get back up; you merely have to keep trying, as with any surgery step.

Not a bug and definitely not inconsistent.

**Comment by Lady-Luck** [comment]
Fox, you've misunderstood the problem. The problem is the 'preparation' itself is considered a step, as in selecting a surgery before you even start.

**Comment by Fox-McCloud** [comment]
Yes, I'm perfectly aware of what you meant, and that's fully intentional as part of the process.

**Comment by Lady-Luck** [comment]
How on earth does it make sense to accidentally stab someone while you're deciding what surgery to perform? =/

**Comment by Lady-Luck** [comment]
That's like your gun jamming before you fire it... it just doesn't make sense. 'Preparing to operate' is for selecting what surgery you're performing from the dropdown menu. Why would it be intentional or desired for accidental scalpel stabbing to happen at that point?

**Comment by tigercat2000** [comment]
Because preparing means cutting open their skin in the correct place with the scalpel.

**Comment by Lady-Luck** [comment]
>Because preparing means cutting open their skin in the correct place with the scalpel.

No, that's making the incision, the step that comes after preparing.

**Comment by tigercat2000** [comment]
You're... right, actually. I didn't realize that. @Fox-McCloud I think this is actually an issue

**Comment by Lady-Luck** [comment]
#6899 is the issue I opened after this was closed... not because I was trying to be defiant or anything but I just genuinely thought I botched the explanation here.
