### ISSUE TITLE
Scrolling through follow as Ghost/observer Lags Screen

### ISSUE THREAD

**Issue by Fhufuu** [ParadiseSS13/Paradise#6898]
**Problem Description**:
As I scroll through the "Follow" list and/or "Jump to mob", the screen of whats happening, with the sprites and everything. Freezes as I scroll through it. 

**What did you expect to happen**: 
The game to proceed as smoothly as before. It does not when scrolling through Follow and Jump to mob.

**What happened instead**:
The screen lags/Freezes when you scroll, and resumes when the scrolling stops.

**Why is this bad/What are the consequences:**
Because it did not work as such before, everything happened smoothly as I was scrolling through the names and mobs. Consequences? Not.. that much, only that its not a smooth gameplay like before. probably a low-medium level bug importance.

**Steps to reproduce the problem**:
Observe the current ongoing round.
Click Follow OR Jump to mob with people moving on your view.
Scroll up and down the lists.
Profit.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I believe it was just.. normal traitor round. I was observing. Not, Dead and ghosting. Observing. Nothing was reaaaally going on. There were a lot of explosion and atmos breach here and there. But they were quickly patched up.

**Comment by Birdtalon** [comment]
I tried this and had no issues. Is it your client possibly?

**Comment by Henri215** [comment]
Could replicate, this is still an issue.

**Comment by DGamerL** [comment]
Indeed still happens, scrolling through any large list will lag your client out a lot.

**Comment by DGamerL** [comment]
We don't use these old lists anymore, almost all have been replaced by TGUI lists, which are lag free!
