### ISSUE TITLE
Ghetto Surgery 'Preparation' is a step that can fail and lead to damage

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6899]
Hopefully this one is explained better. 'Preparation' should not be considered a surgery step, it's just selecting what you want to do on the menu, and it leads to misunderstandings.

Everything following that causing damage is fine. But the actual preparation doesn't even give you any feedback like 'your hand slips', it just swings the weapon at the person.

**Comment by Crazylemon64** [comment]
What's going on here is that your choice of operating table makes every click have a chance to register as a regular weapon use
