### ISSUE TITLE
Arrest status persisted after hiding identity

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6902]
Was set to arrest, put on a voicechanger, mining hardsuit/helmet, another persons ID that was not set to arrest. Checking on sec huds I was still set to arrest, when examining myself I couldn't unset the arrest because the identity I was wearing wasn't set to arrest. Had to reequip my old ID and set that one off of arrest.

**Comment by Contrabang** [comment]
This still happens from time to time, not sure why

**Comment by Spaghetti-bit** [comment]
No longer an issue, seemed to be caused by an issue with updating visibility of the person's face.
