### ISSUE TITLE
IPC/Slime Person Suicide

### ISSUE THREAD

**Issue by mass595** [ParadiseSS13/Paradise#6914]
**Problem Description**:
-While attempting to suicide as an IPC or Slime Person, the command doesn't fully kill you, and leaves you in a hard crit until enough damage is taken from an outside source to finish you off. This is likely due to the fact that committing suicide at full health only takes you into hard crit, and relies on suffocation to finish you off, but races not needing to breathe, such as IPCs or slimepeople are left in that state.

**Comment by AffectedArc07** [comment]
Also IPCs can be revived after suicide which NEEDS to be fixed

**Comment by granodd** [comment]
Use the "Succumb" verb to finish the job. As for IPCs being able to be revived after suicide, I'm not sure if that's a bug or a feature, as I'm not too familiar with how suicide works mechanically.

**Comment by mass595** [comment]
I know you can use the 'Succumb' verb to finish yourself off, this is more of a quality of life thing, and for players that don't know about the verb.

**Comment by taukausanake** [comment]
I can never spell "succumb" correctly when I need it. Not even Google can save me then with it's superior spellcheck
