### ISSUE TITLE
Value-PAK Cartridge does not include MULEbot Control

### ISSUE THREAD

**Issue by NovaNine** [ParadiseSS13/Paradise#6915]
**Problem Description**:
While being the captain, with the original PDA (including Value-PAK Cartridge) the PDA offers all other roles' controls except for MULEbot control.

**What did you expect to happen**: 
I expect that the Value-PAK Cartridge contains all the features of all other PDA Cartridges.  Particularly it has QM's "Supply Records" feature which points to the fact that it should have cargo dept features.

**What happened instead**:
The MULEbot control menu option was not available on PDA with Value-PAK Cartridge.

**Why is this bad/What are the consequences:**
This is inconvenient if a captain wishes to control a mulebot as it requires to swap another cartridge in (ex. HumanResources9001 from the HoP office).  This is particularly inconvenient on a low-pop server where there is no cargo staff on hand.

**Steps to reproduce the problem**:
Checkout current Paradise code.  Build.  Double-click package.  Change character options to Captain: High.  Start round.  Go to MULEs and attempt to control via captain's PDA, menu will not be available.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: See above.

**Comment by Fox-McCloud** [comment]
Features request, not a bug.

**Comment by tigercat2000** [comment]
@Fox-McCloud Actually, no, this is not a bug.
It was mistakenly removed in commit a8f9ea20865b727fca2

**Comment by Fox-McCloud** [comment]
Ahh. Oki doke; was wrong then. Thanks @tigercat2000
