### ISSUE TITLE
Book Binder won't accept paper bundles

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6916]
The Book Binder is essentially useless because it won't accept paper bundles, so unless you want to print one page books there's not much point to it.

**Comment by fludd12** [comment]
It would require a complete rework of how the SQL system writes and requests books, as well as more space dedicated to book storage. You'd be surprised just how much a single page can hold as-is.

**Comment by Lady-Luck** [comment]
Not enough. I wanted to port over some of our on-forum guides over as books but discovered the book binder was not sophisticated enough for the job.

**Comment by fludd12** [comment]
At the moment, unless you find someone to fix up the book system, you could make a _book one, book two, book three_ style series.

**Comment by taukausanake** [comment]
Books can have _pages_? I thought they were just imaginary pages when I was scrolling down the window. If books are going to have actual pages then you need a limit on how much text appears on each _page_. And I never ever thought of creating a book using multiple papers, just one paper with everything you want in it.
This is more of a Feature Request than a bug
