### ISSUE TITLE
Hidden Surgery Room IN Chapel Maint has duplicates

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#6918]
**Problem Description**:
What is the problem?

The surgery table, computer frame, IV drip, sleeper are all Duplicated on the same spot.

**What did you expect to happen**: 
Why do you think this is a bug?

Pretty sure there shouldn't be two of everything there

**What happened instead**:
How is what happened different from what you expected?

Should be only thing there.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

People can get 10 plasteel very easily from the Duplicate surgery table.

**Comment by SamHPurp** [comment]
@Taaketa will fix this now on #6911

**Comment by tigercat2000** [comment]
I believe this is fixed now, due to the fact that the maintenance was reverted.
