### ISSUE TITLE
Unlimited supply points.

### ISSUE THREAD

**Issue by nopm** [ParadiseSS13/Paradise#692]
How can i make the supply points in my server unlimited using admin commands? and also, i made an 9999 slot bag of holding, it can hold 9999 items, but only 7 backpacks, when i try to add more than 7 backpacks to it, it says "full",how can i make truly unlimited?

**Comment by Robertha89** [comment]
there is no way to make it unlimited, and there is probably a var you can edit for it, but the location of it is, well, who knows, now as far as I have found out, you got two methods, 1 spawn a sheet of plasma, set number to a million, and you get half a million points, or you can activate debug verbs, and create the supply point bonus to happen.
Regarding the backpack, well did you modify the max_combined_w_class var?
