### ISSUE TITLE
[Metastation] Viral Fridge isn't stocked upon round start

### ISSUE THREAD

**Issue by RobBrown4PM** [ParadiseSS13/Paradise#6920]
**Problem Description**:
Upon round start the viral fridge isn't stocked and is completely barren

**What did you expect to happen**: 
I expected the regular viral materials to be there

**What happened instead**:
As stated already

**Why is this bad/What are the consequences:**
You can't effectively do your job upon round start

**Steps to reproduce the problem**:
Stock the fridge

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was

**Comment by jughu** [comment]
Tbh you should be able to create a virus from your own blood but thats just me
