### ISSUE TITLE
[Metastation] Xenomorphs can't ventcrawl into Virology

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#6926]
**Problem Description**:
Virology has no vents/scrubbers connected to the main station. 
Xenos, etc, cannot get in because of this.

**What did you expect to happen**: 
I expected there to be a way in. Some way. Not necessarily an obvious way, but at least a possible way to ventcrawl in there.

**What happened instead**:
I was locked out. Like a sad panda.

**Why is this bad/What are the consequences:**
Very different to current map.

**Comment by Fox-McCloud** [comment]
This isn't a bug, this isn't an oversight, this is an explicit feature request. 

Metastation is a 1:1 port from TG--we have every intention of keeping it as close to parity as possible, with obvious exceptions that we have to account for (Karma jobs).
