### ISSUE TITLE
[Metastation] Medical Lockers have a screwdriver

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6928]
**Problem Description**:
Medical lockers seem to have a screwdriver added to them on metastation.

**What did you expect to happen**: 
To have the same contents in the locker as boxstation

**What happened instead**:
Same as boxstation, but with the bonus of a free screwdriver! ### Just pay extra shipping and handling.

**Why is this bad/What are the consequences:**
Inconsistency 

**Steps to reproduce the problem**:
Open a medical locker in the medbay storage room on metastation.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by jughu** [comment]
Thats for the defivs to remove the battery

**Comment by Anoonki** [comment]
This is something that Boxstation should have as well, to be quite honest.
Some chucklefuck always runs off with the one screwdriver the medbay gets anyways.

**Comment by taukausanake** [comment]
We need medical screwdrivers now
