### ISSUE TITLE
Keeping the popup for cryogenic freezers open allows you to enter it from afar

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#6942]
**Problem Description**:
You can teleport into a cryopod from across the map if you keep the popup to enter cryosleep open and then move away from it.

**What did you expect to happen**: 
I expected that the cryopod would not allow me to enter it if I moved away from it.

**What happened instead**:
Instead, the popup remains open so I can enter the pod when I'm getting cuffed by security

**Why is this bad/What are the consequences:**
This allows anyone to have a get out of jail free card for near enough any situation, provided they can remain still for a few seconds.

**Steps to reproduce the problem**:
1. Drag yourself onto a pod and ignore the popup.
2. Move away from the pod.
3. Click "enter" when you wish to teleport, and remain still for a few seconds.
4. You will appear in a cryopod.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by KasparoVy** [comment]
Lmao, confirmed.. Able to reproduce this no problem.
