### ISSUE TITLE
Collecting paper or runed paper and then burning them leaves a ghost runed paper or paper thing

### ISSUE THREAD

**Issue by TYoung86** [ParadiseSS13/Paradise#6943]
**Problem Description**: 
What is the problem?
Collecting paper or runed paper and then burning them leaves a ghost runed paper or paper thing

**What did you expect to happen**: 
Why do you think this is a bug?
Should all just burn up.

**What happened instead**:
How is what happened different from what you expected?
Left a thing behind that can't be burned.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
What the heck. No idea.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Collect sheets of paper or runed papers into a stack. Proceed to use a torch on them until none are left.
Something will remain.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
Could you explain this a bit more?

**Comment by TYoung86** [comment]
I can try. Don't put too much effort into it.
There's no significant value associated with the "artifact" it creates.

Spawn a bunch of runed paper.
Stack them into one hand.
Spawn a lighter.
Activate the lighter.
Burn the stack, repeatedly, until none are left.

You are left with a useless "artifact", a "stack" of no runed paper.
