### ISSUE TITLE
Screen deselects on the plasma monitoring computer.

### ISSUE THREAD

**Issue by Jallen700** [ParadiseSS13/Paradise#6945]
**Problem Description**:
When setting an output value on the plasma monitoring computer in atmos, the screen constantly deselects, making it very difficult to input a value.

**Why is this bad/What are the consequences:**
Its particularly annoying when trying to set a new output value, and can cause issues if multiple windows get opened at once.

**Steps to reproduce the problem**:
Just try to set a new output value. Happens every time.

**Comment by Citinited** [comment]
For reference: this happens on every tank monitor, including on all multitool menus, not just the plasma one

**Comment by DesolateG** [comment]
It's due to the constant change and update of the window. If you want to change the output value simply click it and close the initial window.

**Comment by Sirryan2002** [comment]
This should just be TGUI'd at this point as a fix

**Comment by Contrabang** [comment]
TGUI'd
