### ISSUE TITLE
Dead hearts have no effect after being revived.

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6949]
**Problem Description**:
Have a dead heart. Get revived. Live forever.

**What did you expect to happen**: 
ITS A DEAD HEART. You should be dead too.

**What happened instead**:
You should be dead. Instead you aren't.

**Why is this bad/What are the consequences:**
...

**Steps to reproduce the problem**:
Have dead heart. Die. Get revived by SR. Laugh until it goes septic and poisons you to death.

**Comment by Fox-McCloud** [comment]
It's only mostly dead.

**Comment by king5327** [comment]
Yeah. That one guy with a dead head was also fine.

**Comment by ktoma36** [comment]
I have encountered people with dead lungs able to breath just fine after being revived

**Comment by Anticept** [comment]
related: https://github.com/ParadiseSS13/Paradise/issues/2988
