### ISSUE TITLE
Improve Cyborg/Drone headlamps.

### ISSUE THREAD

**Issue by Nikitaw99** [ParadiseSS13/Paradise#6959]
**Problem Description**:
The problem is, you gotta always click multiple times to just turn it off.

**What did you expect to happen**: 
This isn't technically a bug, but I will explain anyways. I expect to have atleast some options in the `Objects` or `Robot Commands` menu that allow you to select a *specific* option.

**What happened instead**:
...I am always trying to multiclick the button to turn off the headlamps.

**Why is this bad/What are the consequences:**
It could be a problem when trying to *stealth*, for example.

**Comment by DesolateG** [comment]
No an issue.. a feature request.. this gunna get closed.

**Comment by Fox-McCloud** [comment]
Feature request.
