### ISSUE TITLE
Emagged door resets on shuttle launch

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6964]
**Problem Description**:
Emagged doors reset when the escape shuttle launches.

**What did you expect to happen**: 
The emagged cockpit door to remain emagged

**What happened instead**:
The door reset itself and closed.

**Why is this bad/What are the consequences:**
Inconsistent, could have impact on the crew trying to stop antagonists hijacking.

**Steps to reproduce the problem**:
Emag cockpit. Emag console.

**Comment by Lady-Luck** [comment]
Happens with pretty much all shuttles and shuttle equipment, actually. I emagged an ERT shuttle's doors and launch computer. The moment it took off their states reset as if they had never been emagged.

**Comment by Fox-McCloud** [comment]
I believe the emagged refactor for doors fixes this.
