### ISSUE TITLE
Energized fireaxe - atmos traitor item - isn't under 'job specific items' on uplink

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6965]
**Problem Description**:
Energized fireaxe - atmos traitor item - isn't under 'job specific items' on uplink

**What did you expect to happen**: 
The fireaxe to appear to the job specific items

**What happened instead**:
It was mixed in with the rest of them.

**Steps to reproduce the problem**:
Traitor atmos tech. Open uplink.

**Comment by Anoonki** [comment]
Is this actually job specific? 
Because as far as I remember, *anyone* can buy one of these.

**Comment by SamHPurp** [comment]
It -should- be Atmos tech only...

```py
/datum/uplink_item/dangerous/energizedfireaxe
	name = "Energized Fire Axe"
	desc = "A fire axe with a massive electrical charge built into it. It can release this charge on its first victim and will be rather plain after that."
	reference = "EFA"
	item = /obj/item/weapon/twohanded/energizedfireaxe
	cost = 10
	job = list("Life Support Specialist")
```

**Comment by Anoonki** [comment]
Tried to buy it as a paramedic, couldn't find it in my uplink.
My mistake.

**Comment by jughu** [comment]
Could fixed it yourself but oh well gimme a second

**Comment by SamHPurp** [comment]
@jughu Yes, I absolutely could have. But as I'm working on something else at the moment, I figured I'd put the report up.

**Comment by jughu** [comment]
Putting fix up now
