### ISSUE TITLE
PDAs do not reveal your identity in the PDA slot, but still work as an ID

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#6968]
**Problem Description**:
If you put a PDA in your PDA slot, it will still work for access, but it will not reveal your identy.

**What did you expect to happen**: 
It wouldn't allow you to have free access without fucking over your anonyminity

**What happened instead**:
Unknown opens the armory door!

**Why is this bad/What are the consequences:**
Balanz

**Comment by Anoonki** [comment]
As much as I used this, I'd love to see it fixed.

I assume this is just an oversight when making the PDA slot.

**Comment by SamHPurp** [comment]
I use this a lot, I assumed it was intentional behavior in that it could scan it while in the PDA.

**Comment by Robertha89** [comment]
Is this not working as intended? If you put your id into another container, and if your face is covered, you will be shown as unknown, the only difference is having the pda in your hands or not.

**Comment by Fox-McCloud** [comment]
>I use this a lot, I assumed it was intentional behavior in that it could scan it while in the PDA.

This is working as intended, absolutely--I think Tiger's point is more that it hides your identity while doing so.

I'm not even sure if this is worth fixing, TBH, for the number of players that actually bother to consistently use PDA as ID (and how little impact it actually has).

**Comment by Robertha89** [comment]
I use that and wallet for the sake of having access while being shady without an identity, its great fun being arrested by beepsky every few rounds for that.

**Comment by Birdtalon** [comment]
I thought this was intended.

**Comment by tigercat2000** [comment]
@Birdtalon The access is definitely intentional, the "you don't know who this unknown is" is less so
