### ISSUE TITLE
Adv Scanner Printouts do not include "dead" status on limbs and organs

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6972]
**Problem Description**:
Adv Scanner Printouts do not include "dead" status on limbs and organs

**What did you expect to happen**: 
That it would state if something is dead. It shows all the other ailments as far as I know

**What happened instead**:
It doesn't print that a part is dead

**Why is this bad/What are the consequences:**
If there are several dead organs, it requires the person to memorize it.

**Steps to reproduce the problem**:
Have dead organ. Scan. Print. Not dead anymore! Oh wait...

**Comment by tigercat2000** [comment]
You should probably edit the title and page to make this more clear that you're talking about *organ* dead status

**Comment by Anticept** [comment]
Arms aren't organs though, are they? I wasn't sure how to categorize the components of a person...

**Comment by taukausanake** [comment]
I think limbs are counted as a type of organ? Code is weird like that I think

**Comment by KasparoVy** [comment]
Yeah, they're external organs as far as code is concerned
