### ISSUE TITLE
Swarmers dissasembling dirt piles

### ISSUE THREAD

**Issue by Captaincardgage** [ParadiseSS13/Paradise#6977]
**Problem Description**:
What is the problem?
Swarmers can convert piles of dirt into metal.

**What did you expect to happen**: 
Why do you think this is a bug?
expected it should've said the integrated recycler cannot work with the pile of dirt.

**What happened instead**:
How is what happened different from what you expected?
I had deconstructed the pile of dirt into several sheets of metal. 

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Established cold sweats to botanty if they try to use dirt piles once their hydroponic trays are dissassembled/destroyed

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
-Become a swarmer.
--Go to the dirt pile in perma or garden.
---ctrl + click on said dirt piles and you can deconstruct them for metal.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Round was cultist but obviously that shouldn't act as anything to the swarmers.

**Comment by taukausanake** [comment]
Make it turn into glass instead. Sand is turned into glass or sandstone, and then into dirt from sandstone. Makes sense
