### ISSUE TITLE
Bomb Guardian makes more sec pods

### ISSUE THREAD

**Issue by Aracino** [ParadiseSS13/Paradise#6979]
**Problem Description**:
When you make a bomb on a sec pod (or maybe all pods) it makes a duplicate pod for the duration of the bomb.

**What did you expect to happen**: 
Unless guardians are suppose to be super sekret mechanics, not sure this is intended.

**What happened instead**:
I expected the pod to be armed as a bomb..IT made a new pod to be the bomb.

**Why is this bad/What are the consequences:**
It can block off sec pods from windows.

**Steps to reproduce the problem**:
Buy a injector, pick bomb guardian, bomb a sec pod, boom, new sec pod.

**Comment by taukausanake** [comment]
And now we won't be able to bomb pods anymore. I think it was said in deadchat that it makes an effect or a clone of the object that is armed to explode and puts it right on top of the original object. Not duplicating objects in this case.
Working as intended?

**Comment by DesolateG** [comment]
it specifically happened while i was still inside the pod. The holopara made my secpod a bomb, i moved, it made a duplicate secpod. Once it disappeared my secpod magically teleported back to the original position the bomb was made at.
