### ISSUE TITLE
Projectiles are blocked by windows that are not in the way

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6984]
i ded pls fix

![](https://i2.uploadit.us/bwGo6.gif)

**Comment by Fox-McCloud** [comment]
`Bump` code at it's finest.

Don't expect this to be fixed any time soon.

**Comment by TYoung86** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/structures/window.dm#L86
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/structures/window.dm#L93

 Check for directionality of window sprites in addition to PASSGLASS?

**Comment by KasparoVy** [comment]
Unfortunately, it's neither of those. Testing/debug messages indicate that throwing an object along a corridor with windows on each side returns 1 from both these procs, meaning it should be able to pass-- but another proc is coming into play.

**Comment by KasparoVy** [comment]
Soon(tm) sooner than we thought
