### ISSUE TITLE
SecHud comments not functioning

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6985]
**Problem Description**:
Can't add comments to a person's file from a sec hud

**What did you expect to happen**: 
Used to be able to.

**What happened instead**:
Used to be able to

**Why is this bad/What are the consequences:**
This is extremely important to a functioning security. This NEEDS to be restored.

**Steps to reproduce the problem**:
Be magistrate or other security. Examine someone. Try to add a comment to their file. It ends up blank.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
This may have started a month or two ago. I know PAIs used to be able to update records using their sec hud, and I suspect the two are related.

**Comment by davipatury** [comment]
Probably caused by #6500.

**Comment by tigercat2000** [comment]
Is this still a problem?

**Comment by Anticept** [comment]
Very much so.

What happens, is it's inserting empty comments or something. If a person's file is empty, normally it says there are no entries. After trying to add an entry, it then just doesn't display this message. So something is emptying out the text a person enters before adding it to their file.
