### ISSUE TITLE
Incomplete Throws Permaflipping

### ISSUE THREAD

**Issue by SamCroswell** [ParadiseSS13/Paradise#699]
An incomplete throw (IE one that does not connect with a solid object) will leave the thrown object permaflipped until it collides with something in another throw.

Appears to only affect mobs.

**Comment by Spacemanspark** [comment]
Can we please keep this.

**Comment by Fishocalypse** [comment]
Or at least keep it in the form of fliptonium

**Comment by SamCroswell** [comment]
Fixed, closing issue.
