### ISSUE TITLE
Firelock functionality needs a bit more tweaking

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7009]
**Problem Description**:
Atmos alerts are causing firelocks to close, but they are not opening on their own. This requires you to toggle the fire alarms to reset them.

In addition, they do not re-close during an atmos alert if you toggle the fire alarm.

**What did you expect to happen**: 
It's an unintended effect of the firelock changes.

**What happened instead**:
Firelocks should open when atmos alerts AND fire alarms are cleared. If either one is active for the area, they stay closed.

**Why is this bad/What are the consequences:**
Depends on the situation, they can be more than just inconvenient.

**Steps to reproduce the problem**:
Cycle a room with the air alarm. Firelocks will not reopen until you toggle them with a fire alarm.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
@Markolie 👍

**Comment by Lady-Luck** [comment]
Also this #7023

**Comment by Allfd** [comment]
Also sometimes firelocks won't close when the fire alarm goes off due to fire.

**Comment by Citinited** [comment]
Is this still an issue? I attempted replication but failed.

**Comment by Couls** [comment]
can confirm this is still happening on the live server, you can find rogue firelocks that remain closed randomly and have to toggle the fire alarm to reset them.

**Comment by Fox-McCloud** [comment]
Oh. Well.

**Comment by Anticept** [comment]
Blast from the past here. Similar problems exist on Baystation that I'm working on.

I'm converting all alerts to bitflags, and the machinery subsystem checks periodically if they should be set/unset. Any set flag keeps the doors shut. When all are cleared, they open.

Air alarms and fire alarms call a proc on the firedoors that close the doors and trigger these checks to occur at next tick, clearing those alarms will not open the doors immediately, rather instead triggering the checks at next tick and they'll open on their own.

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/pull/13751 might fix this?

**Comment by Sirryan2002** [comment]
old issue, this system has been refactored so it's likely this was fixed, if there's continued issue, a new report should be opened
