### ISSUE TITLE
Underwater sea tiles block clicks

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#7021]
I'm sure everyone knows about this but hoo boy was it painful watching a popular SS13 youtuber Randolph P Checkers (or well, popular by our standards) struggle with this: https://www.youtube.com/watch?v=cCkwtjupD-0

Is there anything we can do to make it so the sea can be 'clicked through'?

**Comment by SheepFighter** [comment]
Alt-click works fine.

The issue is that SS13 is horribly unintuitive. Some sort of in-game tutorial for newbies would be wonderful.

**Comment by Lady-Luck** [comment]
Considering underwater comes up every once in forever, it would just be better if you could click through.

**Comment by SheepFighter** [comment]
@Lady-Luck Fair enough.

**Comment by SamHPurp** [comment]
So this seems intentional:

`/turf/simulated/floor/beach/water/New()
	..()
	overlays += image("icon"='icons/misc/beach.dmi',"icon_state"="water5","layer"=MOB_LAYER+0.1)`

I can simply remove the layer increase and everything will look like this, and be targetable:

![image](https://cloud.githubusercontent.com/assets/7415122/24657626/e14539e6-193e-11e7-9327-6b6f04531cd6.png)

But, you don't get the cool water overlay effect to make everything look like its underwater... hmm

**Comment by Lady-Luck** [comment]
Can't we click through (most) gasses?

**Comment by SamHPurp** [comment]
A fair point, let me have a peek at that code.

**Comment by SamHPurp** [comment]
eeeek.. if I'm understanding this right, it looks like a lot of work to make it work that way...

**Comment by alexkar598** [comment]
i think i got something to fix it

**Comment by alexkar598** [comment]
Lol no i dont

**Comment by SamHPurp** [comment]
@alexkar598 that was exactly my process too... "OH I GOT IT"... "nope lol"

**Comment by alexkar598** [comment]
Also while messing with everything I could,when I varedited mouse_opacity to 3 it worked AND the overlay worked properly

**Comment by alexkar598** [comment]
I don't really what mouse opacity dose tho

**Comment by alexkar598** [comment]
I think I got a solution that works now... And if my fix is right the that means that the person who made water overlay is not a person who is good at making overlays.anyways I got to wait till tomorrow before I can test my fix
