### ISSUE TITLE
Plasma & Tech Disks have to be in crates to count for cargo point redemption!

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#7022]
Just more unintuitive stuff from watching Randolph P Checkers play on our station: https://www.youtube.com/watch?v=C-7oyTz8Vgs

Basically, if the tech disks or plasma aren't in a crate, you don't get any points for it. Pretty dumb. Should be changed because it's silly, unintuitive, and probably unintentional?

**Comment by Aurorablade** [comment]
Can't tell if troll.....

**Comment by Lady-Luck** [comment]
Why would it be a troll?

**Comment by Aurorablade** [comment]
It IS intentional for it to be like this so this is more a feature request then a bug. The same works for manifests and mostly any item sent back. It has to be in a crate. And stamped in the case of manifests.

It is not so wrong to ask someone to take a brief moment to put something in a crate.

**Comment by Aurorablade** [comment]
And if someone wants to make comments like that that is there problem.

**Comment by Crazylemon64** [comment]
I agree it's unintuitive but this isn't really an issue with the code - perhaps you should build up a list of unintuitive things to make more intuitive that you can implement across various feature PRs
