### ISSUE TITLE
Firelocks very near shuttle entrances are closing due to atmos changes

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#7023]
Basically, when a shuttle arrives, firelocks nearby close because of the change in atmos. This is very annoying, especially if you don't have a crowbar handy.

Been like this since #6721 as far as I know.

**Comment by Citinited** [comment]
Trying to figure this one out. It seems that anything that's a child of `obj/machinery/door` and is on a shuttle will trigger adjacent firedoors to close.

In addition, any firedoors located on a shuttle will close when the shuttle arrives or departs. iunno 🤷‍♂️
