### ISSUE TITLE
Rapid cable layer cannot be produced

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7028]
**Problem Description**:
The RCL isn't in any of the design code, so it cannot be produced at this time.

**What did you expect to happen**: 
That clearly wasn't the intention when it was added. It was meant to be a useable item.

**What happened instead**:
It's missing from the design files. https://github.com/ParadiseSS13/Paradise/tree/master/code/modules/research/designs

The RCL itself: https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/RCL.dm

**Why is this bad/What are the consequences:**
Makes it unusable without adminbussing

**Comment by Fox-McCloud** [comment]
Not a but. Feature request.

**Comment by taukausanake** [comment]
Fox-McCloud
> Not a butt

**Comment by Fox-McCloud** [comment]
hue.

**Comment by Anticept** [comment]
@Fox-McCloud not that it matters, since the PR is open, but this isn't a feature request. It's an oversight.

**Comment by Fox-McCloud** [comment]
It was ported and implemented; the CL and PR made no comment about it being made available to anyone, as such, requesting something be added would be a feature request and not a bug.

**Comment by Anticept** [comment]
Oversights are not bugs either. Bug is unintended consequence of code. Oversight is unintended consequence of design.

**Comment by davipatury** [comment]
It was supposed to be possible to produce it, but I probably forgot to implement the design or the PRs I was basing on didn't contain the RCL design.
