### ISSUE TITLE
Lockers are EMP-proof (Might only apply to welded ones)

### ISSUE THREAD

**Issue by sothangel** [ParadiseSS13/Paradise#7031]
**Problem Description**:
Being inside a locker makes you immune to EMPs.
**What did you expect to happen**: 
Probably unintended behaviour?

**What happened instead**:
Expected death, didn't die.

**Why is this bad/What are the consequences:**
Because lockers shouldn't shield from EMPs.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was a welded shut locker, uncertain if it works with lockers closed normally.

**Comment by SamHPurp** [comment]
Testing to see if I can re-produce now.

**Comment by SamHPurp** [comment]
Reproduced, tried with an IPC implanted with a death implant, any locker works, and in any state, as long as its closed. Doesn't matter if its welded, locked etc.

Weird inconsistency to note too: When locked with an ID, that one bursts open.

**Comment by tylerh95** [comment]
@SamHPurp 

Perhaps a better implementation of secure locker EMPing would be the same effect as if emagged. Lock light turns off, and it's unlocked.

**Comment by Fox-McCloud** [comment]
Kinda makes sense, really; they'd discharge the pulse quite well.

**Comment by Ty-Omaha** [comment]
https://en.wikipedia.org/wiki/Faraday_cage

**Comment by Lady-Luck** [comment]
Considering EMPs do not work on locker locks it makes sense to me that they'd be EMP proof.

**Comment by SamHPurp** [comment]
@Lady-Luck re-read my reply, it -does- work on locker locks. Bursts the lockers open, but doesn't count as emagging the lock.

@tylerh95 I agree, I'm not certain that being EMP proof in the locker is a bug. However, it seems a little inconsistent that it doesn't break the locker emag style.

**Comment by Lady-Luck** [comment]
Strange, I've EMPed locked lockers in the past to no effect. I wonder what has changed.

**Comment by tigercat2000** [comment]
Feature:tm:
