### ISSUE TITLE
medibots runtime when using internal beaker

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#7037]
```
[20:54:45] Runtime in y_pos,522: Cannot read null.overdose_threshold
   Caught by process: npc ai
   src: The Medibot () (/mob/living/simple_animal/bot/medbot/adv)
   src.loc: The floor (138,108,1) (/turf/simulated/floor/plasteel)
```
:eyes:

any reagent runtimes

**Comment by SamHPurp** [comment]
Couldn't seem to re-produce

**Comment by pinatacolada** [comment]
You have to tell the bot to use the internal beaker, otherwise its tunning from the synthesizer which works fine

**Comment by SamHPurp** [comment]
@pinatacolada Did that, inserted a beaker of acid, set behaviour to use the inserted beaker.

**Comment by pinatacolada** [comment]
Oh the runtime isnt show on the chat window, its in the runtimes panel

**Comment by SamHPurp** [comment]
![image](https://cloud.githubusercontent.com/assets/7415122/24652423/bd4e2ca6-1929-11e7-8c97-e5599db1728c.png)
This thing? The Runtime viewer? Thats what I was looking for it under.

**Comment by pinatacolada** [comment]
Yes that thing. Runtime happens when the bot starts trying to inject someone

**Comment by SamHPurp** [comment]
@pinatacolada Thanks.

Reproduced:

`[11:31:03] Runtime in artificer_health0,522: Cannot read null.overdose_threshold
   Caught by process: npc ai
   src: The Medibot () (/mob/living/simple_animal/bot/medbot/adv)
   src.loc: The floor (176,121,1) (/turf/simulated/floor/plasteel)`
