### ISSUE TITLE
It's Reticence, not Recitence

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7041]
**Problem Description**:
How long has this been misspelled?

**Comment by SamHPurp** [comment]
I always thought it was referencing something I didn't know...

Checking sister codebases and they all agree with you.

Fixing.

**Comment by Anticept** [comment]
Lesson learned.

If you want something fixed right away, misspell it.

**Comment by SamHPurp** [comment]
Or spot something easy-ish for me to fix. ;)

**Comment by Anticept** [comment]
Also, I forgot to say, reticence means "disposed to be silent or not to speak freely; reserved."

**Comment by SamHPurp** [comment]
I am, personally, the opposite of reticence ;)
