### ISSUE TITLE
The RCD cannot properly construct on escape pod

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#7044]
I was just trying to leave via escape pod 2 at arrivals (the easternmost one), I figured since there was commotion outside I'd deconstruct the window and instead put a wall there.

Well, the window deconstructed, but I couldn't put anything in its place.

This does not seem like intended behavior, as I've used the RCD on the escape shuttle just fine in a similar way.

**Comment by SamHPurp** [comment]
RCD doesn't work on shuttles / pods - by design... like 95% sure.

**Comment by Lady-Luck** [comment]
It lets me deconstruct but not construct, and I've used it to construct walls on the shuttle before.

**Comment by SamHPurp** [comment]
`if(istype(A,/area/shuttle)||istype(A,/turf/space/transit))`

Fairly sure you are mis-remembering constructing walls on the shuttle. That code + my own tests literally just now.

You can de-construct, but never construct - via an RCD - on the shuttle.

**Comment by Lady-Luck** [comment]
It was the southeastern most window on the main part of the shuttle. There was someone outside, I took apart the window, wirecut the grate, and dragged someone floating out in space back into the ship. Then I used the RCD to make a wall there. This was yesterday.

**Comment by Anticept** [comment]
@SamHPurp it used to be allowed. It's how i plugged holes in windows and such. Although I remember it being buggy and I was only able to make walls, not windows.

@Lady-Luck probably because of its abuseability. Put walls in the doors, laugh as you trap everyone on the shuttle.

**Comment by Fox-McCloud** [comment]
Pretty sure this is intentional.
