### ISSUE TITLE
Autopsy scanner Printing

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#7046]
**Problem Description**:
Autopsy scanner can only print the paper if its put down somewhere like a table

**What did you expect to happen**: 
To be able to print an autopsy without putting the device down

**What happened instead**:
I had to put the device on a table before print paper option showed up

**Why is this bad/What are the consequences:**
Its very confusing, at worst someone thinks you cant print autopsy and at best its a minor inconvinience

**Steps to reproduce the problem**:
Take a autopsy scanner, try to print a paper, find out the verb is missing

**Comment by SamHPurp** [comment]
@Joonasm I was doing this in my hand literally just yesterday... What else was going on? Anything odd?

**Comment by Joonasm** [comment]
no idea, this is my object menu with the autopsy scanner in my hand 
![image](https://cloud.githubusercontent.com/assets/589709/24669212/3c302400-1972-11e7-8976-741b4b30ce2c.png)
and this is it with it on a table next to me
![image](https://cloud.githubusercontent.com/assets/589709/24669222/46aae64a-1972-11e7-9d55-dc4585348fde.png)

perhaps you had a autopsy scanner in hand an another one next to you?

**Comment by SamHPurp** [comment]
@Joonasm Tested on an updated branch - and you are correct.
