### ISSUE TITLE
Shotgun Tranquilizer Darts don't have a sprite

### ISSUE THREAD

**Issue by Anoonki** [ParadiseSS13/Paradise#7048]
**Problem Description**:
Shotgun Tranq Darts don't have a sprite

**What did you expect to happen**: 
My tranquilizer ammo not to be hypothetical knockdown darts

**What happened instead**:
My Tranquilizer ammo was hypothetical knockdown darts.

**Why is this bad/What are the consequences:**
Invisible items are misleading as fuck.

**Steps to reproduce the problem**:
Go pick up the box of tranquilizer darts in the armoury and hit Z to pull one out. Be confused

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: [Roundtype is irrelevant, but here's a screenshot](http://i.imgur.com/P1OQ0mL.png)

**Comment by FlattestGuitar** [comment]
That's actually a feature. You're not meant to use them anyway, because they're so crap.

**Comment by Anoonki** [comment]
>That's actually a feature. You're not meant to use them anyway, because they're so crap.

Holy shit, I made this before actually using them.
Good god almighty what's in those? Post-nerf Neuro-Toxin?
:^)
