### ISSUE TITLE
Laptop deletes text files

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#7049]
**Problem Description**:
Laptop deletes text files made with file manager after about a minute

**What did you expect to happen**: 
text files to not be deleted

**What happened instead**:
The file deleted itself

**Why is this bad/What are the consequences:**
It makes it impossible to use it for much else than printing a single paper before having to rewrite the paper

**Steps to reproduce the problem**:
Buy a laptop, write a text file. wait few minutes

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I printed the paper after each time, also i had upgraded hardrive and battery, normal CPU, Advanced Network card, Tesla thing, Miniprinter and an ID slot

**Comment by Joonasm** [comment]
I did some further testing and it deletes files with text in them, if you make empty files they stay

**Comment by alexkar598** [comment]
Nt should get better quality products

**Comment by MarsM0nd** [comment]
It seems you can save something by uploading and downloading it with the P2P transfer programm, though it did break the programm on the receiving computer.

**Comment by tigercat2000** [comment]
#7966
