### ISSUE TITLE
Pie Cannon has no range

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#7064]
I have a fully loaded pie cannon. I stand two spaces away from someone, and I fire it directly at them. The pie comes out and only goes one tile, falling to the ground.

Okay, so, I figure maybe I need to be point blank. However when I try that, it simply makes the pie travel 0 spaces, hit me in the face, and I do a flip. Which, in itself, is funny, but given I'm wearing a mask anyway no one can even tell I was pied.

**Comment by Lady-Luck** [comment]
Not related to #7065 as the pie never even makes impact.

**Comment by tigercat2000** [comment]
![https://i.imgur.com/328uKgE.png](https://i.imgur.com/328uKgE.png)

🤔 
🤦‍

**Comment by SamHPurp** [comment]
@tigercat2000 😱

**Comment by tigercat2000** [comment]
I'll throw this in with my throw refactor, though it's not related to our shitty throw system.

**Comment by SamHPurp** [comment]
OK, that was going to be my next question, if you were picking that up, or if I should fix it with my next wave of bug fixes.
