### ISSUE TITLE
Shadowling announcements are visible and audible from the lobby

### ISSUE THREAD

**Issue by Tayyyyyyy** [ParadiseSS13/Paradise#7067]
**Problem Description**:
Given that we disabled seeing and hearing normal announcements in the lobby, I feel like it's weird that these can be seen too. Also, I believe this also applies to cult rounds when the veil tears.

**What did you expect to happen**: 
I expect only OOC to be visible in chat when I haven't joined the game.

**What happened instead**:
I saw the shadowling announcements and heard the sound. Startles me sometimes when I leave the game open.

**Why is this bad/What are the consequences:**
It's not really that bad, but kind of annoying, especially given how much slings like to meme these days. It's inconsistent with other announcements not appearing.

**Steps to reproduce the problem**:
Connect to the server during a shadowling round. Don't join the game and wait for ascension.

**Comment by FalseIncarnate** [comment]
Shadowling announcements can only be made after they ascend, so the round is effectively over anyways. If anything, seeing these lets you know the round is nearly done and you should just wait a few minutes for the restart rather than joining.

**Comment by Tayyyyyyy** [comment]
Oops, forgot to say, #7196 fixed this!
