### ISSUE TITLE
New limb decapitating system gives ridiculous decapitating, people act like pop up pirates now

### ISSUE THREAD

**Issue by Fishocalypse** [ParadiseSS13/Paradise#707]
Shooting someone in the head 2-3 times with heavy ballistic and laser weaponry will cause people to explode violently like IPCs, losing all their limbs. Kinda comedic, but ruins any chance of defibbing them.

**Comment by TheDZD** [comment]
Yep, say you dismember an arm, oftentimes other limbs will pop off as well, including the chest and head. Might be related to dismembering the dead/dismembering with a killing blow.

@ZomgPonies

**Comment by ZomgPonies** [comment]
Does this still happen?

**Comment by SirBloodBuske** [comment]
Exploding heads is more common than my foot breaking. :p

**Comment by ZomgPonies** [comment]
Should be fixed now.
