### ISSUE TITLE
Grammar Nazi 3: Electric Boogaloo

### ISSUE THREAD

**Issue by Vivalas** [ParadiseSS13/Paradise#7074]
https://i.gyazo.com/7c8c3c2ce425c958b873d773538caddd.png
![image](https://cloud.githubusercontent.com/assets/6334647/24833874/e5067360-1c9a-11e7-8bdf-34d230ef9e24.png)

Seriously whoever writes these MOTDs needs to proper Engrish :1st_place_medal:

**Comment by FlattestGuitar** [comment]
At this point I'm convinced this stuff is intentional. 

Every single MOTD I've ever seen around had a typo.

I'm done.

**Comment by tigercat2000** [comment]
Fixed a while ago.
