### ISSUE TITLE
Chaplain Does not have bible on roundstart

### ISSUE THREAD

**Issue by IK3I** [ParadiseSS13/Paradise#7076]
**Problem Description**:
The chaplain does not have his bible before or after completing the prompts on spawn

**What did you expect to happen**: 
He used to spawn with a bible in hand

**What happened instead**:
After completing the prompts, I had no bible to speak of in my inventory or around me

**Why is this bad/What are the consequences:**
It forces the chaplain to have to go to the library and either hop the table to print one or hope the librarian isn't being a dick about it.

**Steps to reproduce the problem**:
Play as a roundstart chaplain

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
This has happened every time I've played chaplain for some time. The only thing that could potentially prove useful is that I am always an IPC.

**Comment by tigercat2000** [comment]
Technically they do start with a bible, but it gets lost inside of them forever because *someone* (definitely not a 🐯 :eyes:) forgot an equip call.

**Comment by IK3I** [comment]
So what you're saying is, The chaplain eats it moments before the round starts because mmm, tasty tasty paper.
