### ISSUE TITLE
RIIR

### ISSUE THREAD

**Issue by moonheart08** [ParadiseSS13/Paradise#7084]
**Problem Description**:
Space station 13 is not in rust

**What did you expect to happen**: 
Space station 13 should be in rust 

**What happened instead**:
Space Station 13 was in DM

**Why is this bad/What are the consequences:**
It makes Space Station 13 shitty.

**Steps to reproduce the problem**:
1. Look at SRC

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: You dont realise this is a meme, do you?

**Comment by Anticept** [comment]
If this includes removing vulp and IPC, I don't think anyone would object.

**Comment by Crazylemon64** [comment]
danke, we will be considering your feedback carefully and will let you know when we have a fix

**Comment by Crazylemon64** [comment]
(the fix died on its way to its home planet)
