### ISSUE TITLE
Station-bounced radios don't work inside spacepods

### ISSUE THREAD

**Issue by articulateSPLINE** [ParadiseSS13/Paradise#7086]
**Problem Description**:
Station-bounced radios don't work inside spacepods, the pilot has to exit the pod to make use of it on any Z-level.

**What did you expect to happen**: 
The radio should be able to send and receive radio communications within a spacepod.

**What happened instead**:
The pilot spends a lot of time talking to themselves, missing out on whatever's happening on the station if they're out of radio range.

**Why is this bad/What are the consequences:**
Security pod pilots can't communicate from within their pod if comms are down for whatever reason, and the mechanic/anyone else has to brave the vaccuum to get their message out (assuming they lack a space suit)

**Steps to reproduce the problem**:
1) Acquire pod
2) Fly to Z-level outside of station radio range
3) Turn on the microphone and talk
4) Repeat outside the pod to make sure the radio works

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I've experienced this on probably every gamemode, so it's probably not related to that or anything specific to one round. I also feel like I was able to use SBR's from within the pod at one point though I can't confirm that really. Probably not specific to any one type of pod as well, ie security, civilian, industrial, etc.

**Comment by Tayyyyyyy** [comment]
You used to be able to use ":r" to use the radio inside space pods but recently in a shift I did today that didn't work. It was in my hand and I could use it outside the pod but not inside.

**Comment by articulateSPLINE** [comment]
I should add that the SBR won't work from inside the pod regardless of whether it's in my hand, my bag, belt, pocket, etc. It just doesn't work inside the pod at all.

**Comment by Tayyyyyyy** [comment]
Have you tried using ":r"? I feel like sometimes it works, and sometimes it doesn't. Just had a round where ":r" didn't work but getting outside of my pod did.

**Comment by taukausanake** [comment]
> ":r" didn't work but getting outside of my pod did

I think that is the issue being mentioned? Maybe the radio won't work inside the pod because it's in some storage position in the pod where it doesn't physically exist. Is that a possible explanation?

**Comment by Tayyyyyyy** [comment]
It seems inconsistent to me. Sometimes I have it in my hand, other times I have it in a bible in my satchel, and it still works. Other times it won't even work with it in my hand. The expected behavior is that you use say ":r bla bla bla" to talk into your radio on a space pod.

**Comment by Tayyyyyyy** [comment]
Took a look at the code and figured it out. 

So ":r" means "right ear" and ":l" means "left ear".

```
if("right ear")
			var/obj/item/device/radio/R
			if(isradio(r_ear))
				R = r_ear
			else if(isradio(r_hand))
				R = r_hand
			if(R)
				used_radios += R
				R.talk_into(src, message, null, verb, speaking)

		if("left ear")
			var/obj/item/device/radio/R
			if(isradio(l_ear))
				R = l_ear
			else if(isradio(l_hand))
				R = l_hand
			if(R)
				used_radios += R
				R.talk_into(src, message, null, verb, speaking)
```

If you have a headset in your left ear (which is default), you can't talk into a radio you're holding in your left hand, since it looks at your ears first. So, depending on which hand you're holding it in, you should use the corresponding ":R" or ":L" prefix.

**Comment by articulateSPLINE** [comment]
As of yesterday, neither :l nor :r worked for me, and I had the station bounced radio in both hands. The command works when I'm in range of the station or asteroid or telecoms - but the regular headset ;blahblah does too.

The SBR doesn't transmit messages from within a pod, nor does it receive messages from within a pod. Maybe that's the point, but station bounced radios work normally if I exit the pod on Z-levels that lack radio coverage so I'm not sure why the pod needs to act like a Faraday cage.
