### ISSUE TITLE
Pod Pilot Suit is broken on drask

### ISSUE THREAD

**Issue by Wheatley29** [ParadiseSS13/Paradise#7087]
![image](https://cloud.githubusercontent.com/assets/20046182/24900248/22eb7bf6-1e9b-11e7-92a9-fe8919c07698.png)
I do not believe the suit is meant to look like this, it really effects how cool I can make my character look

**Comment by taukausanake** [comment]
Sprite issue? Did Drasks get specie specific icons for jumpsuits? I can't remember

**Comment by Twinmold93** [comment]
Of course there was a sprite I missed when I was fixing Drask sprites. I got a lot of other sprites, but not this one... Alright, alright. Let's see... Shouldn't be hard to fix at all.
