### ISSUE TITLE
Can't Equip Someone as an Abductor

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#7098]
**Problem Description**:
Using the equip button, after making an abductor mob an abductor via the Traitor Panel, doesn't work.

**What did you expect to happen**: 
I expected to be equipped as an abductor agent/scientist, as per the prompt.

**What happened instead**:
Runtimes! Got a sweet empty grey backpack though.

**Why is this bad/What are the consequences:**
Is broken, pls fix.

**Steps to reproduce the problem**:
1. Spawn an abductor mob
2. Make them an official abductor in the Traitor Panel
3. Select the Equip button, followed by either agent or scientist
4. Cry with your backpack.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Agent Runtime**

 [01:38:05] Runtime in abduction.dm,246: Cannot read null.team
   proc name: equip agent (/datum/game_mode/abduction/proc/equip_agent)
   usr: Johnathan Digson (lightfire53) (/mob/living/carbon/human/abductor)
   usr.loc: The floor (216,42,2) (/turf/unsimulated/floor)
   src: abduction (/datum/game_mode/abduction)
   call stack:
   abduction (/datum/game_mode/abduction): equip agent(Johnathan Digson (/mob/living/carbon/human/abductor), null)
   Johnathan Digson (/datum/mind): Topic("src=\[0x2102b474]_1295;abducto...", /list (/list))
   LightFire53 (/client): Topic("src=\[0x2102b474]_1295;abducto...", /list (/list), Johnathan Digson (/datum/mind))

**Scientist Runtime**

[01:38:31] Runtime in abduction.dm,264: Cannot read null.team
   proc name: equip scientist (/datum/game_mode/abduction/proc/equip_scientist)
   usr: Johnathan Digson (lightfire53) (/mob/living/carbon/human/abductor)
   usr.loc: The floor (216,42,2) (/turf/unsimulated/floor)
   src: abduction (/datum/game_mode/abduction)
   call stack:
   abduction (/datum/game_mode/abduction): equip scientist(Johnathan Digson (/mob/living/carbon/human/abductor), null)
   Johnathan Digson (/datum/mind): Topic("src=\[0x2102b474]_1295;abducto...", /list (/list))
   LightFire53 (/client): Topic("src=\[0x2102b474]_1295;abducto...", /list (/list), Johnathan Digson (/datum/mind))

**Comment by SamHPurp** [comment]
Weird, this must have been recent. I was doing this on my test server less than 2 weeks ago.

**Comment by Crazylemon64** [comment]
@Fox-McCloud did an abductor refactor that got merged within the past two weeks: #6894

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/mind.dm#L1106-L1126

**Comment by Twinmold93** [comment]
Why is it referencing the gamemode to do the equipment unlike everything else that references ticker?

**Comment by Fox-McCloud** [comment]
Because the abductor equipping is a game mode proc.
