### ISSUE TITLE
Wires changing colors in hands

### ISSUE THREAD

**Issue by SalazarJosh** [ParadiseSS13/Paradise#7104]
**Problem Description**:
White wire (in hands) changes to red wire when connecting it to red wire.

**What did you expect to happen**: 
There was white wire in my hand (right), I connected it to a red red wire on the solars and it changed to red in my hand from white.

**What happened instead**:
I expected the white wire to not change to red.

**Why is this bad/What are the consequences:**
It's not really important. As far as I could tell it didn't change the amount of wire I had or anything else, really.

**Steps to reproduce the problem**:

1. Have a red wire node on the ground
2. Pull white wire from backpack (might not be needed) and place it connecting to red wire node. It might be of note to specify this red node was a generated red node in solars on the forward starboard side.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not sure the gamemode. The game is still going on. Nothing else out of the ordinary was happening. I just finished a spool of orange wire, pulled the white wire out and placed it.

**Comment by IK3I** [comment]
That's just the behavior of white wire. I don't know why whoever made the wire did it that way, but white wire will always change to the color of the first wire it's used on.

**Comment by Taaketa** [comment]
This is a function of all wire. Wire adopt the colour of the wire laid on the tile. It's not a bug but simply a function of how byond recalls the sprite from storage.

If you want to change the colour of wire,simple cut a single piece off the desired colohr of wire then with it in hand click on the coil of the undesired piece. It will then fill your hand with a white wire bundle, if that is what you desire.

**Comment by tigercat2000** [comment]
Uh, this definitely isn't a feature. Cable coils should not be changing their color from placing it on the turf, and the turf wire shouldn't retain it's color- it should adopt the cable coil's color.

**Comment by Taaketa** [comment]
@tigercat2000 That's the way it has worked for as long as I have played SS13 for.
