### ISSUE TITLE
Possessable borer ghosts

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#7107]
**Problem Description**:
When I joined as a borer using the join as NPC command, I was placed into the nonexistant body of a borer ghost.

**What did you expect to happen**: 
To be placed into one of the many borers left lying around.

**What happened instead***
I was placed into a ghost, unable to move or do stuff.

**Why is this bad/What are the consequences:**
Spooky brain slug ghost possessions.

**Steps to reproduce the problem**:
Join as a borer using the join NPC tab. All I did, I have no idea what else might have happened to cause this.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Meh. Not really. I only know I became a spooky ghost borer because when I said fuck it and ghosted, there was a borer ghost on my tile with the same name as me.

**Comment by IK3I** [comment]
I couldn't replicate this in my testing, perhaps the borer died of an atmos issue as you joined it? They're quite fragile in that regard.

**Comment by KingPhilipIII** [comment]
Maybe. There was no body and no pipe under that tile to my knowledge. When I used things in my action tab it would respond in the negative solely because I lacked a victim for the powers.
