### ISSUE TITLE
Microbomb self detonation

### ISSUE THREAD

**Issue by Jovaniph** [ParadiseSS13/Paradise#7112]
**Problem Description**:
When implanting yourself with a microbomb. There is a chance of it self detonating.

**What did you expect to happen**: 
Microbomb detonated by choice

**What happened instead**:
Microbomb self detonates randomly without warning

**Why is this bad/What are the consequences:**
Playing as a traitor and already gain a lot of momentum against the crew just to see it all go to waste by exploding at random

**Steps to reproduce the problem**:
I don't know exactly, but it seemed someone else triggered the bomb causing mine to go off as well.

I had Flattest look into it. I didn't detonate the bomb myself. He said that its a glitch so I'm posting this issue about it.

**Comment by Fox-McCloud** [comment]
Did you use the emote *deathgasp or happen to unintentionally click the icon and inadvertently hit enter, confirming you want to blow to bits?

There's literally zero other ways that this could happen.

**Comment by Jovaniph** [comment]
I didn't use deathgasp and did not intentionally click it. Flattest looked into the logs and it wasn't me behind the trigger. Something else caused it.

**Comment by Taaketa** [comment]
Was this directly after implanting?

If not, how long from implanting did the bomb go off?

Where did the bomb explode?

Where you in a fight when the bomb exploded?

What condition was your health?

**Comment by SamHPurp** [comment]
@FlattestGuitar could you expand on the situation?

**Comment by Lady-Luck** [comment]
What race were you?

**Comment by Jovaniph** [comment]
I had the implant in me for a good 20-30 minutes I think. I was not in critical condition, however my lungs were collapse, but I had a medical HUD and took 1 sablutomel (Can't spell) to heal suffocation damage. I also had broken bones. Other than that, my health was fine as long as I maintain my ruptured lungs with the pills and not overdose. I was still standing and running around the station normally.

**Comment by Lady-Luck** [comment]
It sounds like you died from heart damage and the microbomb detonated.

**Comment by SamHPurp** [comment]
@Jovaniph Sounds like you had a heart attack. Broken chest etc for a long period of time will cause you to have a heart attack and die.

**Comment by Lady-Luck** [comment]
It's too bad that there's no real in-game indication that your heart health is getting low, you just straight up die.

**Comment by Jovaniph** [comment]
gay
