### ISSUE TITLE
Xenomorph Flippocalypse

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#7124]
**Problem Description**:
Xenomorph can flip without cooldown

**What did you expect to happen**: 
Standard emote cooldown

**What happened instead**:
Acrobatic xenomorphs

**Why is this bad/What are the consequences:**
Spam! Oh the glorious spam!

**Steps to reproduce the problem**:
1. Become ayy lmao
2. Flip endlessly

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by SamHPurp** [comment]
@KasparoVy I suspect this is from your latest PRs on this subject?

**Comment by Anoonki** [comment]
[This is perfectly fine](http://i.imgur.com/KJPWIJ4.gif)
[For real.](http://i.imgur.com/GMsxWUZ.gif)

**Comment by SamHPurp** [comment]
Working as intended ™

**Comment by Spacemanspark** [comment]
...This is actually my fault. I added the *flip emote to xenomorphs, but didn't anticipate the fact that... xenomorphs have no emote cooldown like other mobs do.
