### ISSUE TITLE
Tranq darts have no sprites

### ISSUE THREAD

**Issue by DarkPyrolord** [ParadiseSS13/Paradise#7131]
**Problem Description**:
As it states, the tranq darts for shotguns have no assigned sprite.

**What did you expect to happen**: 
This was ahelped, they had expected it to show like any other bit of shotgun ammo.

**What happened instead**:
A spriteless tranq dart on the floor.

**Why is this bad/What are the consequences:**
Well, can't load a shotgun with spriteless ammo that easily, or see the trails left behind from it.

**Steps to reproduce the problem**:
Just take a tranq dart box out of the armoury, remove shell and see as there is no sprite.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing related to gamemode, but there is a screenshot to tag along with it.
![TranqDarts](https://i.gyazo.com/63f0832bf9da70cf1a4fbb454ef3fc80.png)

**Comment by SamHPurp** [comment]
Duplicate of #7048 and #6808

**Comment by DarkPyrolord** [comment]
How did I not see that before, heh, didn't get enough sleep last night.
