### ISSUE TITLE
Turbine in meta station

### ISSUE THREAD

**Issue by Valkuma** [ParadiseSS13/Paradise#7143]
The turbine controls dont work at all.

Thats it.

**Comment by SamHPurp** [comment]
Which ones in particular? I had fixed some of them, I thought?

**Comment by Valkuma** [comment]
Sorry it took so long to reply

The outer door controls simply dont function so you cant get into the turbine to modify any of the pipes/walls/turn anything on. from what i remember the computer console doesnt work either.

**Comment by SamHPurp** [comment]
Thanks for confirming... when I do my next pass of bug fixes, I'll manually sit down and setup Turbine in its entirety on my test server, just to catch anything I missed with this.

**Comment by taukausanake** [comment]
@SamHPurp Don't forget #6872 as it's the exact same issue but with Toxins

**Comment by SamHPurp** [comment]
@taukausanake how'd my search miss that one...

Must have been the hyphen in meta-station? I'll ensure this is caught for the next pass @taukausanake
