### ISSUE TITLE
[META] I don't get shocked

### ISSUE THREAD

**Issue by R1f72r** [ParadiseSS13/Paradise#7145]
**Problem Description**: shocking things don't shock
What is the problem? When I was diagonal of something, it would not shock me, even though I had nno protection and normally I'd be a fried lizard.

**What did you expect to happen**: I expected to become a fried lizard
Why do you think this is a bug? I am normally supposed to be shocked from shocked appiances right

**What happened instead**: I did not fry
How is what happened different from what you expected? I was still alive rather than super super dead

**Why is this bad/What are the consequences:** It's bad because it interrupts with a somewhat vital aspect of things
Why do you think this is an important issue? While I HATE being shocked it's pretty nessecary

**Steps to reproduce the problem**: hack any door or item that can shock you, activate the shock wire, then keep spamming that wire and realize it's doing nothing to you if you're diagonal from it
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. It has been over two shifts now at metastation

**Comment by SamHPurp** [comment]
Can you give me an example of an exact door you were using, and which side you were on?

**Comment by R1f72r** [comment]
On the hotel gateway, the right Dinnerware, and the right door at the entrance were the most recent examples. I also had the same experience the round before that hacking into botany.

**Comment by SamHPurp** [comment]
I have been entirely unable to re-produce this.

**Comment by SamHPurp** [comment]
@Crazylemon64 @Fox-McCloud I believe this can be closed. I cannot re-produce this at all.
