### ISSUE TITLE
[META] Shuttle flies sideways

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7146]
**Problem Description**:
When the shuttle leaves, the stars etc are flying as if the shuttle is going north, when the shuttle is setup to go east.

**What did you expect to happen**: 
Laws of physics not to be broken

**What happened instead**:
Chaos... or the shuttle was doing a power slide?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: METASTATION

**Comment by Aurorablade** [comment]
@tigercat2000 cause I have no idea unless it's the shuttle not rotating

**Comment by taukausanake** [comment]
It's a feature. The shuttle is drifting through space

**Comment by deep-fried-faceplant** [comment]
[It's not a bug, it's a feature](https://www.youtube.com/watch?v=dv13gl0a-FA)
