### ISSUE TITLE
[Meta] No garage for Paramedic

### ISSUE THREAD

**Issue by Kirbyroth** [ParadiseSS13/Paradise#7147]
**Problem Description**:
What is the problem?

Paramedic has no garage and therefore none of their equipment.

**What did you expect to happen**: 
Why do you think this is a bug?

Paramedic needs their equipment especially their ambulance.

**What happened instead**:
How is what happened different from what you expected?

Expected to spawn in my garage as a paramedic but just spawned in medbay lobby instead.

**Why is this bad/What are the consequences:** 
Why do you think this is an important issue?

Slows down paramedic without their trusty ambulance and space suit.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Be a paramedic try to find garage but fail to find it cause it don't exist.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.  

Meteor + evil pyro.

**Comment by SamHPurp** [comment]
Oh god. That'll be fun to fix. Thanks for the report.
