### ISSUE TITLE
This is weird

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7149]
**Problem Description**:
What is the problem?
new law icon when im human
**What did you expect to happen**: 
Why do you think this is a bug?
im human human are FREE!!!
**What happened instead**:
How is what happened different from what you expected?
i got the new law icon
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
i dont know if the ai had or had not a law change but if yes then its a warning that ai got subverted
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
i dont know.....
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

lots of booms that round,was sec officer

image cause i was fast to screenshot it:
![space station 13 2017-04-22 073101](https://cloud.githubusercontent.com/assets/25136265/25304099/4957b516-272e-11e7-845a-1a989f5a9140.png)

**Comment by SheepFighter** [comment]
I had this happen to me as a vox. I've still got no idea what triggered it.

**Comment by SamHPurp** [comment]
Ugh, wish I could look at your variables as this happened.

**Comment by alexkar598** [comment]
@SamHPurp im still in the round

**Comment by SamHPurp** [comment]
@alexkar598 were you hallucinating? This is one of the new types of Hallucination.

**Comment by alexkar598** [comment]
I don't think I was.unless lacking o2 for couple seconds makes you hallucinate

**Comment by TravellingMerchant** [comment]
As SamHPurp said, it's a new Hallucination.  It can come from the usual sources. Drugs, radiation, etc.

**Comment by alexkar598** [comment]
It's probably drugs since there was drugs everywhere that round. Anyways closing since its not an issue
