### ISSUE TITLE
Briefly appeared as wrong species on examine

### ISSUE THREAD

**Issue by Spess-Rando** [ParadiseSS13/Paradise#7152]
![dreamseeker_2017-04-22_19-29-54](https://cloud.githubusercontent.com/assets/12747768/25306670/347ea8a2-2792-11e7-97b0-dab62cf8c3f4.png)

If you look carefully, the sprite on the second one is different.

**Comment by KasparoVy** [comment]
HAH! That icon was me.
Happens when a new player spawns in, it seems.

**Comment by PJB3005** [comment]
`bicon()` with player mobs is a fucking mess and it's probably related.

**Comment by tigercat2000** [comment]
Icon refs are tricky things, bicon caching doesn't work terribly well

**Comment by Fox-McCloud** [comment]
yeah, anything with `bicon` is horrendous when it comes to the icon for mobs showing up consistently.

This happens in VV as well.

**Comment by Fox-McCloud** [comment]
we don't use `bicon` for this anymore.
