### ISSUE TITLE
Embellished Enigma cigs do not appear to have nicotine in them when scanned

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7154]
**Problem Description**:
Embellished Enigma cigarettes only show the randomized reagent when scanned by a reagent scanner, until they are smoked, then the nicotine appears.

**What did you expect to happen**: 
The nicotine should appear in the cigarette even before the user lights it.

**What happened instead**:
Only the other reagent showed up when the cigarettes were scanned.

**Why is this bad/What are the consequences:**
The nicotine should not suddenly appear the moment someone lights the cigarette, it is supposed to always be there (and if it is not there, it might cause issues when attempting to grind cigarettes and no nicotine coming out).

**Steps to reproduce the problem**:
Get embellished enigma cigarettes, scan them with the reagent scanner on a PDA, light them, then scan them again when they are lit.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The embellished enigma packet I had was the one that spawns in the maintenance below science, I used a ChemWhiz cartridge in the PDA to scan it, and I lit the cigarettes with a cheap lighter (also from maintenance).

Edit: well, that's weird, halfway through the round they show nicotine in them when scanned

**Comment by alexkar598** [comment]
nicotine is bluespaced into the cigarette by NT

**Comment by Fox-McCloud** [comment]
Pretty sure the nicotine is added to cigs when you remove them from their packet, for the first time.

**Comment by IK3I** [comment]
embellished enigma cigs do not in fact contain nicotine all the time.
They are randomly assigned a chem when they get added to the box and filled with those. It's the roulette of cigs.

**Comment by ModDownloading** [comment]
Well, that explains why scanning them for reagents did not show nicotine the first time, I remember now that I scanned them when they were still in the packet. I only removed them because one of them said "Mannitol" and I had Brainrot.
