### ISSUE TITLE
Game Breaking bug 4/22/2017

### ISSUE THREAD

**Issue by SirBloodBuske** [ParadiseSS13/Paradise#7155]
**Problem Description**:
What is the problem?
I cannot copy ians butt.

**What did you expect to happen**: 
Why do you think this is a bug?
I CANT DO IT, HOW CAN I FAX CENTCOMS IANS BUTT?

**What happened instead**:
How is what happened different from what you expected?
i expected to copy ians butt and send a fax to CC

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
This is game breaking

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
take ian, or any animal.. put them on the copy machine.. PROFFIT! 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Trying to send a fax to CC.

**Comment by Aurorablade** [comment]
This is a feature request NOT a bug.
Please do not click bait us into thinking it is a bug. Even if it is amusing.

**Comment by taukausanake** [comment]
Should have saved it for a meme number. Like issue 7777. I know what I'm doing now
