### ISSUE TITLE
Putting on a holster/suit accessory using fast equip button leaves icon in hand

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#716]
As above. I've experienced this several times as detective, don't know about other jobs. The only fix is restarting the game. I'm not sure about reproducibility being reliable, but it's happened several times. I've only ever gotten it with a holster, but suit accessories aren't that common.
![untitled](https://cloud.githubusercontent.com/assets/11774300/6968601/dcae297c-d95f-11e4-9c04-4cac6b2afab5.png)

**Comment by Plotron** [comment]
You can fix it (AFAIR) by removing the accessory and putting it in the same hand, and then normally equipping it (not fast equipping), unless it was changed or it works only for me.
