### ISSUE TITLE
Nukeops (and presumably other spawn antags) retain the descriptions of the original characters

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7165]
**Problem Description**:
When someone becomes a Nukeops member, they get a random human to control as normal, but examining them displays their standard character description.

**What did you expect to happen**: 
Nukeops to have no personal description or to have a description set during the round.

**What happened instead**:
The Nukeops leader (Newton Interplanetary Team Director) appears to have a description stating he is a Tajaran, which I assume is the player's original description for his character.

**Why is this bad/What are the consequences:**
Descriptions should not carry over to someone who is (in-game) a completely different person.

**Steps to reproduce the problem**:
Be Nukeops (or maybe another antag that spawns into the game as someone other than their own character) with a description, then examine yourself or have someone else examine you.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing, except nukeops clowns (but really, nothing else weird).

**Comment by taukausanake** [comment]
Nukeops clowns sounds amazing. Honkops dropping a bananium bomb that makes everyone squeak and honk. Guns that shoot sonic honk blasts, all the banana grenades
