### ISSUE TITLE
Message spans are sampled by message distortion procs

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7172]
**Problem Description**:
What is the problem?
seeing things you should not see
**What did you expect to happen**: 
Why do you think this is a bug?
its code and code should not go in chat
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
its not
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
DIE!!!!!

this was in chat:

... You can almost hear someone talking ...

... You can almost hear someone talking ...

**...You hear something about...class='reallybig'>HELLO**

...You almost hear someone talking...

You're about to lose consciousness.

_________________________________________________________________________

...You almost hear someone talking...

... You can almost hear someone talking ...

**...You hear something about...class='reallybig'>Hurry**

...You hear something about...me

**Comment by Crazylemon64** [comment]
It's a snippet of text that gets sampled across formatting marks. We'd need a mild refactor to get this to not happen - and we had similar issues with slurring/stammering in the past, too.

Also, use a more useful issue title than "bug" please, this is an absolutely unhelpful title for searching stuff in the future. How about "Message spans are sampled by message distortion procs"?

**Comment by alexkar598** [comment]
thanks i had no idea of a title

**Comment by Sirryan2002** [comment]
has not been reproduced or brought up in 5 years... closing as likely fixed
