### ISSUE TITLE
HTML formatting Bug

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7174]
**Problem Description**:
What is the problem?
unexpected characters
**What did you expect to happen**: 
Why do you think this is a bug?
cause it should show up normally
**What happened instead**:
How is what happened different from what you expected?
showed html/i_dont_know_what   codes
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
its not
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
name a slime nasiaf'fuiafbuis
hover over it

![capture](https://cloud.githubusercontent.com/assets/25136265/25364124/fe572662-292d-11e7-9639-d37b3a814799.PNG)

i wont be in contact with tech for 4 days so i wont be able to change title just yet

and its a PAI type slime( personnel automatic ian)

**Comment by KasparoVy** [comment]
Come on man, try to make a title when you write the bug

What window is this?

**Comment by alexkar598** [comment]
Lower left corner

**Comment by alexkar598** [comment]
When examining or interacting it shows correctly in char

**Comment by alexkar598** [comment]
Chat* and I hate mobile

**Comment by SamHPurp** [comment]
HTML character encoding symbols such as apostrophes. I'm on my phone but I think this is likely a dupe issue.

**Comment by Fox-McCloud** [comment]
It's not that hard to think up a title; don't be lazy about it, please.

**Comment by Will-Bohlen** [comment]
Just tested this, and it looks like the issue is no longer present- likely fixed by #11515, I'd guess. 

![image](https://user-images.githubusercontent.com/15622691/161649253-5d294cdd-07b7-4a00-80c7-522e5f5f83d7.png)

**Comment by alexkar598** [comment]
its been 5 years

**Comment by alexkar598** [comment]
I don't even remember making this issue

**Comment by Sirryan2002** [comment]
likely fixed by now, poor issue documentation
