### ISSUE TITLE
Ranged Projectiles Blocked by Armor Cause Halloss

### ISSUE THREAD

**Issue by SamCroswell** [ParadiseSS13/Paradise#719]
If a projectile that deals damage is blocked by armor, even partially, the party that would be taking the damage is instead given a crippling dose of halloss and immediately collapses.

**Comment by Spacemanspark** [comment]
Pretty sure it's stamina damage they're taking, not Hallos.

**Comment by SamCroswell** [comment]
It's Halloss. I know that for a fact.

**Comment by Spacemanspark** [comment]
I thought they were supposed to take Stamina. That's odd.

**Comment by SamCroswell** [comment]
They aren't supposed to take ANY kind of damage under this circumstance, as the armor blocked the shot.

**Comment by Spacemanspark** [comment]
Oh, duh, armoured.
