### ISSUE TITLE
T-ray scanners turning pipes and wires transparent

### ISSUE THREAD

**Issue by deep-fried-faceplant** [ParadiseSS13/Paradise#7191]
**Problem Description**:
When using t-ray scanners, if a floor tile is removed while the pipes and wires underneath are being revealed, they remain transparent. Replacing the floor tile covers the pipe, but the pipe still remains transparent when the tile is removed.

**What did you expect to happen**: 
The pipes and wires should be normal when the floor tile is removed.

**Why is this bad/What are the consequences:**
The pipes and wires remaining transparent is just a graphical bug.

**Comment by Anticept** [comment]
THATS WHY THAT WAS HAPPENING.

This was an extremely annoying thing, but it never occurred to me it might be the t-ray doing it.

**Comment by Sirryan2002** [comment]
Can not reproduce, this was likely fixed at the same time as #13863
