### ISSUE TITLE
Popcorn-flavored jelly bean has no jelly bean requirement in recipe

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7193]
**Problem Description**:
I went code diving, and found an inconsistency in the fact that the popcorn-flavored jelly bean in the candy maker recipes file only requires popcorn and no jelly bean.

**What did you expect to happen**: 
For the popcorn jelly bean to require an actual jelly bean like all of the other jelly bean recipes.

**What happened instead**:
It appears that you can make the popcorn bean using only popcorn.

**Why is this bad/What are the consequences:**
Not too big of an issue, but it seems odd that this recipe is the only jelly bean recipe that does not actually require a jelly bean (besides, how exactly would you get the popcorn into that shape otherwise? A vice press?).

**Steps to reproduce the problem**:
Make popcorn, put popcorn into the candy maker, turn the candy maker on.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I code dived for this, so I have not actually tested it yet. According to the code though, no jelly bean is in the recipe.

Edit: Just tested it, and it indeed only requires popcorn to make a popcorn bean at the current moment

**Comment by FalseIncarnate** [comment]
Whoops, minor oversight on my part, must have accidentally deleted the line requiring a jelly bean before committing that code and no one noticed. Easy fix though, will do so soon.

Also amazed someone noticed this, which means someone made jellybeans!

**Comment by ModDownloading** [comment]
er, actually FalseIncarnate, that was me code diving for fun, I only made jellybeans after to test it on a private server of mine.
