### ISSUE TITLE
Gum made in the candy machine has no item image

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7194]
**Problem Description**:
When you make gum in the candy machine, the resultant gum is invisible instead of having the appearance shown on the wiki.

**What did you expect to happen**: 
For the gum to be visible (and perhaps flavorable like the rest of the candy, but that is unrelated)

**What happened instead**:
The gum was invisible, and could, in practice, be chewed indefinitely (I'm not sure if this is a feature or not)

**Why is this bad/What are the consequences:**
This object should have an appearance.

**Steps to reproduce the problem**:
Put 5u Corn Oil, 5u Sugar and 5u Water into the candy machine, turn it on, then right-click the tile the candy machine is on when it is finished.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was tested on my private testing server running the current version of Paradise Station (as of 4/29/2017).

**Comment by FalseIncarnate** [comment]
Seems the icon_state got deleted when I shuffled the food icon files around, will fix soon.

**Comment by FalseIncarnate** [comment]
Gum also can't be chewed indefinitely, it just has an incredibly small bitesize so it takes a lot of chewing to finish off.
