### ISSUE TITLE
Combat Borg Icon...again

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#720]
Combat Borg Icon still doesn't update, however when I played with it and tried to force the Icon, the game would bug out, remove part of it then replace the icon with the default robot and set the path back to the default.

**Comment by CrAzYPiLoT-SS13** [comment]
You mean the sprite?

**Comment by Earthdivine** [comment]
Yea, from what I noticed with the pathing though it doesn't seem like there should be anything FORCING the path back to default, even unfinished sprites in the folder "work" and allow themselves to be used.

**Comment by CrAzYPiLoT-SS13** [comment]
I checked every piece of related code and sprites. Found nothing unusual.

**Comment by Earthdivine** [comment]
Got the chance to mess with it again and it seems to be working, so I will chalk this up to a one time bug and close this.
