### ISSUE TITLE
Eating deep fried foods with a fork prints wrong message.

### ISSUE THREAD

**Issue by deep-fried-faceplant** [ParadiseSS13/Paradise#7203]
**Problem Description**:
When eating deep fried foods with a fork, the food shows up as Deep Fried Food Holder Obj. http://imgur.com/a/PJfdS

**What did you expect to happen**: 
Expected to see deep fried boiled spider leg.

**Why is this bad/What are the consequences:**
Muh immershun.

**Steps to reproduce the problem**:
Eating with a fork, sitting down, food was on a table, food was deep fried.

**Comment by SamHPurp** [comment]
Reproduced.

This only happens with deep-fried food.

```
You scoop up some the frosted donut with the fork!

You take a bite of the donut.

You finish eating the donut.

Deangelo Rahl finishes eating the donut.

You put the the fork into the tray.

You put the donut into the deep fryer.

You put the the deep fried donut into the tray.

You scoop up some the deep fried donut with the fork!

You take a bite of Deep Fried Foods Holder Obj.

You finish eating Deep Fried Foods Holder Obj.

Deangelo Rahl finishes eating Deep Fried Foods Holder Obj.
```

**Comment by Fox-McCloud** [comment]
kek.
