### ISSUE TITLE
Radiation Mines Affect IPCs

### ISSUE THREAD

**Issue by mass595** [ParadiseSS13/Paradise#7205]
**Problem Description**:
The radiation mines, such as in the "Wild West" away mission, give IPCs genetic disabilities.

**What did you expect to happen**: 
IPCs do not have DNA and are not supposed to be able to receive any genetic disabilities, thus it is expected they should be completely immune to the effects of the radiation mines.

**What happened instead**:
When an IPC triggers a radiation mine, they receive a genetic disability anyway.

**Why is this bad/What are the consequences:**
This is clearly not supposed to happen, and can be extremely detrimental to IPCs attempting to clear the away mission, as they now have additional debuffs to deal with.

**Steps to reproduce the problem**:
-Be an IPC
-Trigger a radiation mine
-Receive genetic disability

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: After a small discussion, an easy fix would likely be to just have the mines check for 'no_dna' flag before applying a genetic disability to the mob. This is similar to the problem covered in a recent PR {6931} that patched DNA scramblers, which were previously able to be used on IPCs.

**Comment by Citinited** [comment]
Fixed, including in next PR
