### ISSUE TITLE
Enthralling Logs

### ISSUE THREAD

**Issue by Twinmold93** [ParadiseSS13/Paradise#7206]
**Problem Description**:
Attack logs do not show when someone is enthralled by vampire on either the one doing the enthralling (only states they casted Enthrall, not on who) or that the person was enthralled (and by whom) in their own logs.

**What did you expect to happen**: 
The logs to say who the person enthralled and that the person was enthralled by x.

**What happened instead**:
Only the vampire doing the enthralling had any logs, but not stating who they cast it on.

**Why is this bad/What are the consequences:**
Harder to find out who enthralled who, when someone was enthralled, who their master is, if they were dethralled.

**Steps to reproduce the problem**:
Have vampire enthrall someone. Check both logs.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Traditional vampire round.

Should ensure that if someone is dethralled (that's possible, right?) that they

**Comment by Aurorablade** [comment]
"Entralling"

**Comment by taukausanake** [comment]
I thought the word was "thrall". Looks _really_ weird like this

**Comment by KasparoVy** [comment]
Apparently this was resolved by https://github.com/ParadiseSS13/Paradise/pull/7208 @Twinmold93 @Fox-McCloud
