### ISSUE TITLE
You can put grabs into display cases

### ISSUE THREAD

**Issue by sasanek12** [ParadiseSS13/Paradise#7212]
**Problem Description**:
What is the problem?
as the title says, you can put various grab levels into display cases
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
-Grab someone
-Click on the open display case
-Be proud of your strength becoming more than just blunt force
https://i.gyazo.com/dca1220dd1934ec78552ab93843580e7.mp4

**Comment by tristan1333** [comment]
Feature please

**Comment by taukausanake** [comment]
I was hoping this was going to look way more funny. I was disappointed. Alternatively it would be nice to stick someone into a display case. Broken as a containment/trap but funny all the same

**Comment by scrubmcnoob** [comment]
it's called abstract art you uncultured swine

**Comment by taukausanake** [comment]
Thank you, @scrubmcnoob

**Comment by sasanek12** [comment]
When I think about this, I actually love it. @taukausanake @scrubmcnoob _Time to cover up this issue report_

**Comment by GelatinousGlob** [comment]
I think you can deep fry grabs too.

**Comment by Anticept** [comment]
The deep fry grabs is a feature that was pulled.

https://github.com/ParadiseSS13/Paradise/pull/7055

**Comment by FalseIncarnate** [comment]
@Anticept I believe they were referring to deepfrying the grab "object", not deepfrying what you have grabbed, since that is similar to the issue being reported, though I don't think you can actually deepfry the grab object like you can shove it into a display case.

**Comment by Anticept** [comment]
I uhh.... just saw the video. That's... really crazy.
