### ISSUE TITLE
Welding helmet provides the blindness overlay, not the normal one.

### ISSUE THREAD

**Issue by Kharshai** [ParadiseSS13/Paradise#7215]
What is the problem?
When wearing a normal helmet, your overlay is the blindness one, not the usual welding one.
https://puu.sh/vEdWn/1e6cafeb50.png

Why do you think this is a bug?

It's providing the wrong overlay.

How is what happened different from what you expected?

It should've provided the welding overlay, yet it displayed the blindness one.

Why do you think this is an important issue?

It limits visibility even further than it should.

The most important section. Review everything you did leading up to causing the issue.

Simply equipped a welding helmet.

 Anything else you can tell us:

The problem only arises with the normal welding helmets, the eye slot welding goggles do not cause this effect.

**Comment by Crazylemon64** [comment]
Are you wearing anything else that would carry `tint`?

**Comment by MarsM0nd** [comment]
As you do have the sechud active, i would figure you have the sechud on, which would have tint, and sunglasses+welding helmet = blind. Also Crazy did beat, damm fast.

**Comment by taukausanake** [comment]
Wow, that's a pretty neat feature. I wonder why we didn't know about it until now?

**Comment by Kharshai** [comment]
Yep, that worked fine, apologies for the false bug report!
