### ISSUE TITLE
Status and Lobby tabs inverted

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7218]
What is the problem?
The Status and Lobby tabs were inverted

Why do you think this is a bug?
cause normally its Status then Lobby

The most important section. Review everything you did leading up to causing the issue.
i dont know

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

it was before the round started

**Comment by tigercat2000** [comment]
[Not a bug](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/new_player/new_player.dm#L70-L71)

**Comment by alexkar598** [comment]
Please explain
