### ISSUE TITLE
Roundstart Science Positions Stack Nerds

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7219]
What is the problem?
at round start two scientists can spawn in the experimentor control room at the same EXACT turf 
Why do you think this is a bug?
cause impossible physics

How is what happened different from what you expected?
cause its impossible physics

The most important section. Review everything you did leading up to causing the issue.
selected scientist at roundstart --> be teleported

How to fix: add an other roundstart position for scientists

**Comment by SamHPurp** [comment]
There are only 4 spawn locations for sci-nerds. Easy to map in a few more.

**Comment by FalseIncarnate** [comment]
While your issue titles are starting to get slightly better, they do still need some work. This could be "Roundstart Science Positions Stack Nerds" or such.

Interesting that no one has really mentioned this before though... easy to fix map-issue.

**Comment by taukausanake** [comment]
I think the issue is having more jobs that job spawn locations maybe? Did any of those +1 job PRs go through without adding any start locations?

**Comment by SamHPurp** [comment]
@taukausanake none

**Comment by KasparoVy** [comment]
RIP stack 'o' nerds
