### ISSUE TITLE
pAI windows glitch out

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7220]
**Problem Description**:
After opening enogh windows the pAI only show a website error

**What did you expect to happen**: 
To pAI to keep working

**What happened instead**:
An error Screen showed up and consistently came up after every time opening it again

**Why is this bad/What are the consequences:**
It prevents pAI's from doing anything other than talking and if erased from becoming a pAI again as trying to sign up shows the same error

**Steps to reproduce the problem**:
Get downloaded as pAI, Open the software interface and close it
Repeat until it stops working

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was downloaded as pAI from an away mission. The software i got was universal translator and then host bioscan. Reconnecting did not fix the issue but restarting byond did

![dreamseeker_2017-05-03_23-28-43](https://cloud.githubusercontent.com/assets/589709/25681375/c1c3131a-305c-11e7-9473-5c663ecc2dfe.png)
As it stops working

![2017-05-03_23-22-11](https://cloud.githubusercontent.com/assets/589709/25681403/dba41f5e-305c-11e7-912a-5d74977d733a.png)
First time you try to access one of the windows

**Comment by taukausanake** [comment]
Why do you have a map? Also an error? It sure would be nice for pAIs to have map apps. That or a PDA cartridge.

Sounds like a BYOND issue?

**Comment by Joonasm** [comment]
the map thing seems to show up when the windows break, also showed up with a firealarm window. No idea why a map shows up. Might be nanoUI issue

**Comment by tigercat2000** [comment]
It's a BYOND bug. What you're seeing there is nano's CSS completely failing to load- it's just showing the bare template, which includes the map.

**Comment by AffectedArc07** [comment]
Closed since being TGUI'd
