### ISSUE TITLE
Tracker electronics aren't electronics in the way that other electronics are.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#7233]
**Problem Description**:
Magnetic gripper cannot hold Tracker Electronics, the main component of Solar Trackers. nor can they be obtained in any way other than cargo shipments.

**What did you expect to happen**: 
Tracker electronics to operate like airlock electronics, APC electronics, or circuit boards, being produceable in a protolathe or circuit imprinter.

**What happened instead**:
Magnetic gripper couldn't hold Tracker Electronics, the main component of Solar Trackers. nor could they be obtained in any way other than cargo shipments.

**Why is this bad/What are the consequences:**
Borgs can't fix solar trackers without someone else's hands. And cargo.

**Steps to reproduce the problem**:
Attempt to use a Solar Tracker as a borg or drone or obtain them in a way other than ordering from Cargo.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Your gripper cannot hold the tracker electronics.

**Comment by taukausanake** [comment]
Grippers can't hold a lot of things I've noticed before. Kind of annoying when I go as drone. Kind of stopped because of it

**Comment by IK3I** [comment]
Flippers are supposed to be able to hold all circuitry and stock parts. This is an inconsistency in regards to that behavior.

**Comment by mass595** [comment]
The Magnetic Grippers are also unable to pick up the restocking units required to construct the various vending machines, making it impossible for drones to construct/reconstruct vending machines.
