### ISSUE TITLE
Lethal medical patches

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7241]
Using droppers/pipettes you can put any chem inside a medical patch (like a 1u manitol patch) for instant chem application on any victim, without breaking the patch seal.

**Comment by KasparoVy** [comment]
Intended or not? @anyone

**Comment by Fox-McCloud** [comment]
Droppers are such epic pieces of shit, it's not even funny.

**Comment by taukausanake** [comment]
I don't know @Fox-McCloud, it made me laugh
