### ISSUE TITLE
Teleporting to centcomm using RCS

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7243]
You can teleport to centcomm by wrenching the crate sender destination pad onto the supply shuttle, sending the shuttle to centcomm and teleporting someone/something inside a locker using the rapid crate sender.

**Comment by Anoonki** [comment]
I can't see this being the biggest issue, because the "Centcomm supply shuttle dock" is actually just a square of adminium walls around the shuttle and nothing else, iirc.

**Comment by taukausanake** [comment]
Can't you also just go to CentComm by being on the shuttle when it is sent back? Sure you can't DO anything because walls and doors but you are still on that z-level

**Comment by Anoonki** [comment]
@taukausanake Can't dispatch the shuttle with certain things on it, most commonly people.

**Comment by taukausanake** [comment]
Didn't know that. Used to be possible

**Comment by FalseIncarnate** [comment]
Easy fix would to be just add the pads to the shuttle content no-fly list. Which oddly isn't on there yet the standard `/obj/machinery/telepad` path is... Guess no one thought about the cargo pad not being a subtype of that (it's `/obj/machinery/telepad_cargo`)

**Comment by KasparoVy** [comment]
Working on it, lumping it in with fix for the other rcs issue
