### ISSUE TITLE
Cult structures can be overlapped

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7244]
Building multiple cult structures (altar, forge, archives etc.) at the same time by queuing up build dialogues allows to circumvent the limit of one per tile.

**Comment by taukausanake** [comment]
Like many other structures. Pretty sure you can build multiple machines on the same tile just no one does it because it becomes harder to use them. Maybe an issue with cult structures because they have passive effects but not something you can fix I want to say?

**Comment by Crazylemon64** [comment]
I'm pretty sure you can do the same with regular machinery, if you finish each machine before working on the next - just that the laundry list of objects normally required keeps you moving

**Comment by Crazylemon64** [comment]
Could do a `density` check on the tile to prevent the sort of thing you are talking about

**Comment by taukausanake** [comment]
@Crazylemon64 I think a few machines, namely the microwave and maybe the grinder too, would look horrible if placed on the floor rather than a table. Wouldn't a table affect that `density` check?
