### ISSUE TITLE
Infinite food from chem reactions

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7245]
Cheese, weird cheese, chocolate and bread can be easily replicated in huge quantities using chemical foam or single chem grenades. In case of regular cheese this creates chemically empty cheese object which is only useful for cooking.

**Comment by taukausanake** [comment]
#7209 Related......?

**Comment by Fox-McCloud** [comment]
This is the inherent nature of all food chems, and has been brought up multiple times, in the past (even more than a year ago), and is an intentional feature.
