### ISSUE TITLE
Being revived while a clone is in process results in hopping from one live body to another

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7251]
**Problem Description**:
What is the problem?
double bodies

**What did you expect to happen**: 
have only one body

Why do you think this is a bug?
cause i had two bodies

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
cause inconsistant

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
DIE!!!!!
get scanned and clone cycle started
get revived using defib

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
gamemode: round still going

**Comment by SamHPurp** [comment]
Firstly, don't submit issue reports for in-progress rounds...

Secondly how is 'double bodies' a description.

-----------

If I'm understanding the issue you are trying to report: If you get de-fib revived while being actively cloned, your Mind gets put in control of two bodies. Yes?

**Comment by alexkar598** [comment]
no i only control the cloned one but the other still exist

**Comment by alexkar598** [comment]
first i was in control of the defibbed one then i magicly teleported my mind to the cloned one

**Comment by KasparoVy** [comment]
Do we want cloners to 'dissolve' the body if it detects the OG is alive and well, or do we want cloners to still spit out the body but not transfer the mind?

**Comment by taukausanake** [comment]
Awww, and that was actually a good meme title

**Comment by alexkar598** [comment]
Been fixed 2 months ago
