### ISSUE TITLE
You can forget how to use something you can't use

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7254]
**Problem Description**:
What is the problem?
You can forget how to use the cryogenic freezer when you click on it

**What did you expect to happen**: 
Why do you think this is a bug?
Cause you can't forget how to use something you can't use

**What happened instead**:
How is what happened different from what you expected?
It showed the message you momentarily forget how to use this even if the machine in question doesn't have anything in attack_hand

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Get brain damage under 60 --> spam click the cryogenic freezer

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by alexkar598** [comment]
Sorry if what I wrote is not understandable English is not my first language

**Comment by SamHPurp** [comment]
But you can forget that you can't do anything with it. This seems fine and not a bug to me.

**Comment by Fox-McCloud** [comment]
This is on the parent of all machinery so it doesn't have to be added to every single machine in the game.

**Comment by taukausanake** [comment]
Is this some feature that you don't know exists unless you are really stupid (in IC)? I feel like that is something that should be expanded upon. Bay12 had their job or knowledge expertise thing which was mainly OOC stuff. Maybe use that to not meta so much with all gear?

This seems weird that I wouldn't know if it's a bug or not. Really need some explaining and usage cases for it

**Comment by alexkar598** [comment]
Fuck this,would be too weird to fix anyways without snowflakes
