### ISSUE TITLE
Wolf's fluff item does not appear on character when equipped 

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#7257]
**Problem Description**:
The golden thermal eyepatch does not show on Wolf when equipped

**What did you expect to happen**: 
It should cover his eye

**What happened instead**:
Nothing shows

**Why is this bad/What are the consequences:**
I paid money to have a fluff item.

**Steps to reproduce the problem**:
Open dufflebag
Select golden eye patch
Put in eye slot of character doll

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Any mode
![broken eye patch 1](https://cloud.githubusercontent.com/assets/20448049/25784636/94b177f6-3325-11e7-8a64-146458dc6f0a.png)

**Comment by SamHPurp** [comment]
@FlattestGuitar
