### ISSUE TITLE
Why is the corgi suit missing from the AutoDrobe?

### ISSUE THREAD

**Issue by Ultimate-Chimera** [ParadiseSS13/Paradise#726]
It was in the vending machine in the past, but now it's gone. I would like to know why because I really liked the corgi suit. 
![test1](https://cloud.githubusercontent.com/assets/9296792/6992041/6f71e98c-da74-11e4-9662-db91c7ff53b5.png) ![test2](https://cloud.githubusercontent.com/assets/9296792/6992042/6f759e92-da74-11e4-8ea9-c535be1f021b.png)

**Comment by Markolie** [comment]
It was removed, not sure why do. The issues section isn't the place to ask though.
