### ISSUE TITLE
Barber's Uniform is invisible

### ISSUE THREAD

**Issue by FearTheBlackout** [ParadiseSS13/Paradise#7273]
**Problem Description**:
The overlay for the Barber's Uniform just plain out doesn't show up.

**What did you expect to happen**: 
The Barber's Uniform sprites would show up as normal.

**What happened instead**:
They were invisible, or didn't show up properly, making my character appear nude.

**Why is this bad/What are the consequences:**
Makes playing Barber far less enjoyable if you can't wear your own uniform.

**Steps to reproduce the problem**:
1. Spawn as Barber
2. Examine icon

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was playing as a Grey when this happened; I haven't tried it with any other race.

**Comment by Aurorablade** [comment]
its probaly one of the ones missing from my sprite update..i may need some help fixing it.... @KasparoVy maybe...or..someone...

**Comment by KasparoVy** [comment]
Is it the icon for the uniform in your hand? Does it show up on your mob?

**Comment by Aurorablade** [comment]
he means on mob i am pretty sure..i know not all suit sprites were there...

**Comment by FearTheBlackout** [comment]
It doesn’t show up on my character, period, in-hand or on-body.

Sent from Mail for Windows 10

**Comment by KasparoVy** [comment]
@Aurorablade I whipped up a Grey Barber uniform and fixed a bug with the green suit having a rogue pixel in the bottom-left of the sprite when facing south.
[grey uniform dmi.zip](https://github.com/ParadiseSS13/Paradise/files/988657/grey.uniform.dmi.zip)
