### ISSUE TITLE
IPCs Requiring Facial Repair

### ISSUE THREAD

**Issue by mass595** [ParadiseSS13/Paradise#7275]
**Problem Description**:
-Sometimes after repairing IPCs from beyond death, even after the IPC re-activates their screen, they are shown as an Unknown when inspected; as if they needed facial repair surgery, which, being IPCs, they cannot receive.

**Possibly related stuff**: 
-I have not had a chance to thoroughly test it yet, but this appears to happen particularly when the IPC was beheaded either at the time of, or after, their death.

**Comment by Fox-McCloud** [comment]
This is caused by being burnt extremely badly; this applies to humans as well, and is definitely not a bug--you can't recover from being husked.
