### ISSUE TITLE
Embedded items causes flavortext to become bold

### ISSUE THREAD

**Issue by deep-fried-faceplant** [ParadiseSS13/Paradise#7277]
**Problem Description**:
The flavortext that prints from examining someone is bold if that someone has something embedded in them.

**What did you expect to happen**: 
For it to not be bold text.

**Why is this bad/What are the consequences:**
Muh consistency

**Steps to reproduce the problem**:
The problem is likely that the examine text code for embedded objects doesn't have a closed bold tag.

**Comment by SamHPurp** [comment]
Sounds like an unclosed <span> - I'll have a look. Thanks for reporting.
