### ISSUE TITLE
Using space cleaner on colored wires turns them red.

### ISSUE THREAD

**Issue by deep-fried-faceplant** [ParadiseSS13/Paradise#7283]
**Problem Description**:
Using space cleaner on tiles that have colored wires laid cleans the wires of their color.

**What did you expect to happen**: 
Expected the wires to retain their color.

**Why is this bad/What are the consequences:**
Unless NT simply dips the insulated wires into dye vats, it shouldn't be possible to clean a color off. I was under the impression that the insulation itself is colored. ~~Hey, if these wires are insulated, why is it possible to shock yourself on laid wire by just clicking on it? Weird!~~

**Steps to reproduce the problem**:
Wire was laid on the floor, space cleaner was applied by spraying it from a bottle. 
`/datum/reagent/space_cleaner/reaction_obj(obj/O, volume)
	if(O && !istype(O, /atom/movable/lighting_overlay))
		O.color = initial(O.color)`
I think this is the code block in question. I'm assuming that the initial color for all wires is red, which is why space cleaner strips colored wires of their color. It would be snowflakey to exclude just wires from the conditions, as well as create issues when cleaning colorful reagent off of wires.

Alternatively, we could just say fuck it to all of this and accept that NT sucks at making insulation that comes in different colors, and that NT does indeed dip red wire into vats of dye in order to color it. If this is the case, coloring a coil of wire by washing it with a crayon would be an interesting feature/fix.

**Comment by SamHPurp** [comment]
Yeah there are a bunch of cable issues... this is one of many...

**Comment by taukausanake** [comment]
It's a feature. NT does in fact dip cables into paint and send them off as a different color.

That being said, I think an advanced or insulated cable would be nice. Something Engineers could use if they don't have gloves

**Comment by tigercat2000** [comment]
This isn't really an issue with cables so much as space cleaner. Someone had the bright idea to make it blindly reset all color vars without adding any way to exempt objects that intentionally use it. It'd make blood white if it didn't flat out delete it. It really deserves a full refactor.

**Comment by Shadow-Quill** [comment]
Unable to reproduce.
@Anasari
