### ISSUE TITLE
HUDSunglasses look wrong on a vox

### ISSUE THREAD

**Issue by lithorse** [ParadiseSS13/Paradise#7286]
**Problem Description**:
HUDSunglasses look strange on vox, almost as if they don't fit. Up until a few days ago it looked fine.

**What did you expect to happen**: 
The HUDSunglasses to fit the vox sprite.

**What happened instead**:
It looks like [this.](https://imgur.com/a/MuP9E) It almost seems as if the glasses are positioned for the human sprite instead of the vox sprite.

**Why is this bad/What are the consequences:**
It looks stupid.

**Steps to reproduce the problem**:
Be a vox, wear HUDSunglasses.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: -

**Comment by SamHPurp** [comment]
afaik nothings changed.

These look goofy on IPCs too: #5839

**Comment by Birdtalon** [comment]
A lot of items have this problem with the Vox sprite actually.

**Comment by Aurorablade** [comment]
birdtalon, is it something recent cuase alot of the sprites for vox are covered..

**Comment by SamHPurp** [comment]
@Aurorablade ah its something new from your PR, gotcha.
