### ISSUE TITLE
Only Able to Examine Players Wearing Masks

### ISSUE THREAD

**Issue by scrubmcnoob** [ParadiseSS13/Paradise#7292]
**Problem Description**:
You can only examine other players who are wearing any mask item.
**What did you expect to happen**: 
To be able to examine that man with no mask on.

**What happened instead**:
I could only examine the mongoloid who had a mask on.

**Why is this bad/What are the consequences:**
It's borked yo

**Steps to reproduce the problem**:
Examine someone with a mask and then try to do on someone with no mask.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
everything

**Comment by FlattestGuitar** [comment]
This was addressed by https://github.com/ParadiseSS13/Paradise/pull/7289

I checked three times now.

The code just isn't live yet.
