### ISSUE TITLE
two handed weapon and damaged hand

### ISSUE THREAD

**Issue by JustinHornsby** [ParadiseSS13/Paradise#7294]
**Problem Description**:
found a bug where if a player has a two handed weapon, like a spear and one of their hands is injured. they will "drop" the off-hand icon, but the weapon will remain in two-handed use.

**What did you expect to happen**: 
I expected the spear to return back to one-handed use.

**What happened instead**:
The spear remains two-handed, despite my one hand being unusable.

**Why is this bad/What are the consequences:**
Players can do dual handed weapons while only using one hand.

**Steps to reproduce the problem**:
1.Create spear.
2. have in left hand (or right)
3. have other hand disabled (drops items on pickup)
4. tell spear to use both hands.
5. player will scream and "drop" the off-hand icon.
6. the spear remains two-handed despite only having one hand.

**Comment by SamHPurp** [comment]
Working as intended :tm:

Thanks for reporting... that sounds fun to fix.

**Comment by taukausanake** [comment]
Does the off-hand icon drop on to the floor? If it does then that's perfect

**Comment by FunnyMan3595** [comment]
This has been fixed sometime in the intervening years.
