### ISSUE TITLE
AI Camera Crashing

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#7295]
**Problem Description**:
I find that when I am playing AI (as of very recently) that in certain instances when I move my camera (without the speed throttle feature on to where it constantly accelerates in any given direction) or whenever I hit the "AI Core" verb to return to my core with the camera that it will sometimes crash me. It does not always do this, but it has become enough of an issue as of late that I feel justified in submitting an issue report in the hopes that someone might investigate this. More specifically, the camera had entered a specific area or condition to where every time my dream seeker boots to rejoin the game from the crash, it immediately stops responding and crashes again.

**What did you expect to happen**: 
I expected to have my camera move to the intended location without resulting in my client crashing.

**What happened instead**:
My client, in certain circumstances, will outright crash when it tries to move the camera back to he core, or if the camera somehow snags something that results in a crash. As of recently, it snagged something that caught me in an indefinite crash loop whenever I tried to rejoin the game, locking me out of it effectively.

**Why is this bad/What are the consequences:**
As stated before: crashing clients are no bueno.

**Steps to reproduce the problem**:
While difficult to describe what exactly is causing this issue, I will do my best.
1. Playing an AI
2. Moving your camera about without the speed throttle enabled, jumping to certain locations.
3. Using the "AI Core" verb.

It does not seem to be consistent, or if there are consistent circumstances that must be met for this crash to occur, I am not aware of them, though hope that the guys who deal with code and the like might be able to sniff out something.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
The first couple of times that this has happened where the client crashes but isn't caught in a continual crash loop was Cultist and Traitor/Vampire/Changeling. The case with the infinite crash loop was a wizard round (I believe). The "indefinite crash loop" eventually fixed itself, though is still probably something worth looking into.

**Comment by BiberDark** [comment]
Yes i can say that two, i played in the last time 3 rounds as an AI, and after a certain time dreamseeker is crashing you. Nothing helps. Clearing cash didn´t work, restart of byond didn´t help either. If you are login you see the one ms a interface and then app crash.  And it is everytime : It is like you clicked track a person 25 times and now you have a constant crash.

Byond : 511,1384
Win 10 Pro.

**Comment by tigercat2000** [comment]
This definitely seems like some sort of BYOND issue. There's not really much we can do with the information you have, we need to be able to reliably replicate it to debug it any further.

**Comment by lithorse** [comment]
This has happened to me a lot lately and I believe I've found at least some of the contributing factors. Every time it has happened I've been looking at atmos (or at least had some part of atmos on my screen) and then tried to either track a crew member or return my view to my core. 

I'm not sure if it crashes everytime you do this since after it happens I can't even get back in without admin intervention. I try to avoid looking at atmos at all as AI, but it's so easy to forget.

So steps to reproduce may be:

- Be AI

- Look at atmos

- Track a crew member OR move view back to core

**Comment by AffectedArc07** [comment]
No news on this in over 3 years, nor any reports of it happening. Closing issue.
