### ISSUE TITLE
Vampires have short term memory issues about their servants.

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#7298]
**Problem Description**:
Upon reconnection as a vampire after my game crashed, I lost my HUD indicator for my thrall even though he was still my thrall.

**What did you expect to happen**: 
I expected to be able to identify my still loyal servant without thinking his thralldom had worn off.

**What happened instead**:
I assumed his thralldom had worn off and my unfortunate servant became lunch before the misunderstanding was rectified.

**Why is this bad/What are the consequences:**
Just kind of annoying. And can be kind of a hassle to figure stuff out.

**Steps to reproduce the problem**:
Be vampire.
Thrall crew member
Disconnect as vampire
Reconnect as vampire
Accidently eat thrall because the HUD icon vanished.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing in particular. Ordinary vampire round.

**Comment by SheepFighter** [comment]
This also happens if you're wearing a Med HUD while thralling someone.

**Comment by lewcc** [comment]
Closing this since I'm sure whatever caused this was gutted in the vamp rework.
