### ISSUE TITLE
autopsy scanners won't print if it's an undamaged body

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#7299]
scalpel and scan with the autopsy scanner someone unfortunate enough to die due to loss of headitis, cry as you press Z and click the scanner and it doesn't print anything or react at all

**Comment by TullyBurnalot** [comment]
Decapitated someone, made an incision on their chest, printed out autopsy report by clicking on the scanner and pressing Z.

Then, made an incision on their non-existent head (somehow), still managed to print out an autopsy reports.

What steps did you take for this "bug" to show up?

**Comment by pinatacolada** [comment]
oh this is one of the fun ones eh

the guy was decapitated by an armblade I think, so it might have had the stump limb thing for a head.

I did the incision on the chest and an arm, scanned both successfully, then pressed Z and nothing happened. He was also full nakey, so it was showing as unknown

**Comment by Fox-McCloud** [comment]
You don't need to make incisions with the autopsy scanner anymore, guys.

It's a two step process:

1) Make sure patient is on a surgery table
2) Scan the zone you want to gain information from

If they have no head and you try to scan it...of course you can't get info about the head; it's gone.

Unless I'm misunderstanding something.

**Comment by pinatacolada** [comment]
Oh yeah i forgot about that. Regardless, the problem is that i tried scanning the torso, which it said it had scanned, then tried to print it, and nothing happened. I made the issue while the round was still playing, maybe if we pull logs it will show a runtime or something

**Comment by pinatacolada** [comment]
i think i got new info on this. from last time i played, i couldnt print the report from two different bodies, but what set these appart from the others was that these bodies died without any damage or wounds (ie removing the brain or brain death from brainrot)

**Comment by Fox-McCloud** [comment]
Yeah, you're not going to get results if something like that happens.

The autopsy system is horrifically snowflakey, so you're going to get hundreds of exceptions to the rules for how it functions.

**Comment by tigercat2000** [comment]
Pretty much exactly what @Fox-McCloud said, the autopsy system requires tons of calls in random places that no one anticipates to actually function correctly. It's unlikely to ever have full coverage of every possible death.
