### ISSUE TITLE
Anti drop implants result in undroppable items (shocking)

### ISSUE THREAD

**Issue by Anoonki** [ParadiseSS13/Paradise#7300]
**Problem Description**:
After being forced to drop an item that had nodrop, as part of my antidrop implant. (Hands got knocked off as an IPC), (After getting my hands fixed) I picked the item back up, and couldn't relax my hands or drop the item.

**What did you expect to happen**: 
For my anti-drop implant to be able to be turned off as normal.

**What happened instead**:
Super glued a baton and teleshield to my hands, turning me into Harmbaton law enforcement

**Why is this bad/What are the consequences:**
I lost use of my hands until an admin came and Varedited my baton and shield to be droppable.

**Steps to reproduce the problem**:
Spawn as an IPC, acquire an antidrop, pick up two items of your choice, activate your antidrop, damage your hands until they come off, reattach your hands, (Deactivate your Antidrop implant before picking up dropped items)pick up dropped items, have them replace your hands for eternity.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Should be covered in the rest of the report. [But have this image too.](http://i.imgur.com/PfOL23v.png)

**Comment by Anoonki** [comment]
I looked and couldn't find a duplicate issue, so if this' already reported (which I imagine it is), lemme know to close this.

**Comment by Tayyyyyyy** [comment]
I ran into this issue too when I was decapitated, losing the skill in the upper left corner. When my head was reattached, activating the no-drop spell didn't actually affect me.

**Comment by TullyBurnalot** [comment]
Cannot reproduce.

Spawned as IPC, picked up items, activated anti-drop, got my hands chopped off, reattached hands, picked up items again, could freely turn off anti-drop and drop all items.

**Comment by Anoonki** [comment]
Odd, maybe I'm missing a step, but Flattest (and I think Marsmond) ended up having to fix it for me. 
Given what they were telling me, the Anti-drop implant was toggling on and off, but my items just had a permanent undroppable value of 2 until manually varedited otherwise.

**Comment by Anoonki** [comment]
@TullyBurnalot Found the missing link after spending like half an hour testing. After getting repaired and my hand reattached, I deactivated the antidrop implant *before* picking the dropped item(s) back up [As seen in this image](http://i.imgur.com/T0k91UC.png) (At the end, after I relax my hands, then get the notification "not holding anything, hands relaxed" I picked the items up and started toggling the implant to keep relaxing my hands but not really.)

Worth noting as well, is that when one of an IPC's hands break with a nodrop implant on, they drop both of the active items they're holding, including the one in the undamaged hand.

**Comment by TullyBurnalot** [comment]
Jesus fuck, I hate super specific bugs like these...

**Comment by IK3I** [comment]
Just did some testing, good news is this bug applies to humans and therefore every species as well.
Replication method:
pick something up -> activate anti-drop -> cut your hand off -> drop both items (bug one) -> deactivate anti-drop -> pick something up with other hand, reattached hand, doesn't matter -> can't put back down

Additionally, the implant stops sending the grip tightening message when activated and only sends the relax message when deactivated.
