### ISSUE TITLE
blue light wont show up when object trown in disposal

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7302]
**Problem Description**:
What is the problem?

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Crazylemon64** [comment]
Use your words!

**Comment by alexkar598** [comment]
i was editing it to add the description i pressed enter too fast

**Comment by Crazylemon64** [comment]
Are you editing the description, @alexkar598 ?

**Comment by Crazylemon64** [comment]
guess not
