### ISSUE TITLE
Cowboy clothes description has typos

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7307]
**Problem Description**:
After code diving, I noticed some typos in cowboy clothing items.

**What did you expect to happen**: 
No typos allowed, chaps.

**What happened instead**:
There were indeed typos when I was code diving for fun.

**Why is this bad/What are the consequences:**
Well, typos are typos, and as such are a definition of something misspelled (its probably just an accident though, not criticizing anyone's language skills here).

**Steps to reproduce the problem**:
Spawn in the "Shortsleeved black cowboy shirt" or "white cowboy shirt" and notice in the description "ooks" or "oks" instead of "looks"

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I have not actually tested this in game, I was merely code diving for something completely different (taking a look at what all of the medals were for).

**Comment by SamHPurp** [comment]
oh god damn it @Xantholne

**Comment by TullyBurnalot** [comment]
:eyes:
