### ISSUE TITLE
[IPC] IPCs take damage from injected Welder Fuel

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#731]
IPCs take damage from welder fuel that cannot be repaired. It doesn't cause it to suffer burn or brute damage. It lowers the IPC's health and also causes it to slow down but cannot be repaired via welding or replacing wire. Injecting Charcoal doesn't work either.

**Comment by Iamgoofball** [comment]
The not healable part is a bug but taking the damage is intended.

**Comment by Fox-McCloud** [comment]
Tested this out myself; charcoal most definitely heals IPC's tox damage.
