### ISSUE TITLE
Those spawned from ghost bar spawners can be assassinate objectives

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7310]
**Problem Description**:
Those spawned from ghost bar spawners (the long range cloner) can be assassinate objectives

**What did you expect to happen / why is this a problem**: 
You can't kill admin memers

**Steps to reproduce the problem**:
Spawn in an admin area via a ghost bar spawner
Have a tot's target cryo
Become new tots target

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 

@Spacemanspark was the target and might be able to expand more.

**Comment by Spacemanspark** [comment]
I spawned in a long distance cloner, used it to spawn in as Spark. I had not been in the round in any way prior to that.
Ended up being a traitor target to Sollessa, who had no idea of where I was. RIP.

**Comment by Kyep** [comment]
This could be fixed by altering /obj/structure/respawner/attack_ghost to set mind.offstation_role = TRUE after the mob is spawned in.
