### ISSUE TITLE
Sugar doesn't force borer from body

### ISSUE THREAD

**Issue by borers** [ParadiseSS13/Paradise#7314]
Borers can't be effectively countered by anything.

Eating sugar doesn't remove a borer from body, and in fact makes them unable to leave your body. Even when you eat sugar, then they can communicate that you did x y to all other borers and get you killed. Meaning the moment one gets into you when you're an antag, you might as well cryosleep because your round is over. The borer has no reason to care about your or his own life because they are immortal while inside your body, and they can just respawn even if you somehow miraculously managed to kill them due to the number of eggs they can lay in short time. Surgery requires turning yourself in and thus getting removed from the round due to arrests.

And since it's completely ok according to the Head of Staff TullyBBurnalot for a borer to forever sabotage an antag that killed their host yet didn't harm a borer, there's no counterplay involved besides slowly dying as a fatso to sugar overdose - and even that will let the borer live and is inaccessible to antags without chem dispenser access.

**Comment by SamHPurp** [comment]
Sugar disables a borer, to allow you to get them removes.

Working as designed.

**Comment by borers** [comment]
You didn't design it please don't speak as such.

**Comment by SamHPurp** [comment]
I never stated as such. You're salty. I ded plz nerf.

Bitch elsewhere, this is not the place.

**Comment by borers** [comment]
Please stop personally attacking me. I did not give you any reason to be hostile.
