### ISSUE TITLE
Lesser animals are eternally in pain

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7316]
**Problem Description**:
Using genetics empath powers on lesser animals, including monkeys, farwas, stoks, Pun Pun (though this case might be justified) it states that they are in "mild pain" even at full health.

**What did you expect to happen**: 
For the animals to "feel good", on account for them having full health.

**What happened instead**:
Apparently, the animals are in a constant pain for being a lower species than the humanoids, or something along those lines (at least, in a anthropocentric philosophy they are).

**Why is this bad/What are the consequences:**
Its a minor bug that is probably due to lesser animals having less maximum hp and as such showing up as "mild pain" due to having below 60 health, since empath runs off of the amount of hp left instead of the percentage of hp left.

**Steps to reproduce the problem**:
Get the empath trait, ~~Proceed to rob bank account numbers~~ use empath on an undamaged animal, observe the health description.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This bug was located on my private testing server while I was screwing around with genetics.

**Comment by SamHPurp** [comment]
@Crazylemon64 This might be related to something I saw a while back...

Araneus has 250 max hp, and 200 hp at round start.

I assumed this might have been intentional to weaken them early-round, and have them regen back up to full later on... to help stupid HoS's that attack their spiders.

**Comment by taukausanake** [comment]
I think I remember something similar to this too because a max_health var wasn't being used or something. Can't find it though
