### ISSUE TITLE
Insert Missing Grey Sprites here

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#7317]
Okay i know one is the sexy mime outfit but if you come across any grey clothing sprites not showing up on your character please list them here so i can try to fix them.

**Comment by pinatacolada** [comment]
the solgov sprites don't either

**Comment by taukausanake** [comment]
Wouldn't it make more sense to compare and contrast the different .dmi files for any inconsistencies? And while at it put them in a sane order to easier find an icon? Maybe alphabet order?
