### ISSUE TITLE
Phantom hand is capable of pulling the magazine out of the 'Bulldog' Shotgun

### ISSUE THREAD

**Issue by deep-fried-faceplant** [ParadiseSS13/Paradise#7318]
**Problem Description**:
Unloading the 'Bulldog' Shotgun puts the magazine into the character's free hand, even if the character is missing said hand.

**What did you expect to happen**: 
Expected to be unable to unload the shotgun, or for the magazine to fall to the ground.

**What happened instead**:
The magazine went to my non-existent hand. There's a Metal Gear joke in all of this, somewhere.

**Why is this bad/What are the consequences:**
The problems are self-evident.

**Steps to reproduce the problem**:
Loose an arm/hand, pick up the 'Bulldog' Shotgun with the other hand, then click on the shotgun to unload it. This bug might be possible with other firearms, so it's worth testing other ballistic weapons that use similar reloading mechanics.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
~~I'm nuuuuclear, I'm wiiiiilld~~ It was nuke ops, I was a human, the bulldog was empty.

**Comment by taukausanake** [comment]
Does it work with hands that are broken/unusable? I think those have better checks though

**Comment by imsxz** [comment]
Had this happen when using a C20R. Was able to hold, refill the magazine with ammo(via an ammo box), and put it back into the gun all while holding it in the hand that didn't exist.
To answer @taukausanake's question, I'm pretty sure it drops it with broken hands, no clue about deformed though.
