### ISSUE TITLE
More phantom hand shenanigans

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7331]
**Problem Description**:
After losing a hand to an explosion, I can still remove objects (namely janitorial signs) from a janitorial cart using my missing hand.

**What did you expect to happen**: 
For the signs to stay where they are when I move my nonexistent left hand towards them.

**What happened instead**:
Janitorial sign is somehow grasped in a hand that is not there.

**Why is this bad/What are the consequences:**
Well? I was missing a hand wasn't I? I don't really see how I can pick up a wet floor sign.

**Steps to reproduce the problem**:
Put floor signs into janitorial cart (the actual CART, not the one you ride on), lose your hand, select your missing hand slot and open the cart menu, then take a sign out of it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I lost my hand in an explosion, I was holding a mop in my other hand, here is a picture. This issue might be connected to #7318 
![space station 13 2017-05-17 114321](https://cloud.githubusercontent.com/assets/25691743/26163370/7d28af8a-3af7-11e7-9472-bf5a8b6c4cf2.png)

**Comment by SamHPurp** [comment]
@TullyBurnalot fyi, you poor soul.

**Comment by TullyBurnalot** [comment]
Nope.

I'm not fucking delving into inventory code again.

**Comment by CrAzYPiLoT-SS13** [comment]
I don't see how this is related to inventory code, at all? This looks like
a simple missing sanity check in the janitorial cart code.

**Comment by TullyBurnalot** [comment]
@CrAzYPiLoT-SS13 Basically, everything that uses put_in_hands as a proc eventually routes through mob inventory code.

Mob inventory code is a fucking mess. It's literally just a dozen different variations of x_hand variables and NO TABBING WHATSOEVER.
