### ISSUE TITLE
Beer and absinthe bottles don't break like the rest

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7339]
**Problem Description**:
Hitting people with beer and absinthe bottles on harm intent force feeds them the contents instead of breaking it on them.

**What did you expect to happen**: 
For my character to crack a beer bottle over a bystander's head during the end-of-round chaos at centcomm.

**What happened instead**:
My character attempted to force feed the contents of the beer bottle instead, the same happened with an absinthe bottle.

**Why is this bad/What are the consequences:**
These bottles should be the same as the other bottles, and should be able to be broken over someone's head.

**Steps to reproduce the problem**:
Control: Get a vodka bottle, set to harm intent, smack someone with it
Experiment: Get a beer bottle, set to harm intent, attempt to smack someone with it

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was during the end of round chaos at centcomm. After I tested it with a beer bottle, I decided to bring a copious amount of alcohol (some of which I drank) on the escape shuttle in a duffelbag the following round, then, after the end results were displayed, attempted to break them over people's heads. The vodka, rum and patron bottles broke over people's heads, but the beer and absinthe bottles did not. All bottles were filled with the corresponding alcohol. I tested the beer bottle with the cap on and with the cap off, both times I could not break it over the other person's head.

**Comment by taukausanake** [comment]
Maybe they aren't big enough bottles? Either way inconsistent

**Comment by Fox-McCloud** [comment]
The absinthe definitely wasn't a bottle if this happened; it was probably just a drinking glass with absinthe in it.

The beer bottle is because it's a can, and not an actual bottle; one that you can pop the top off of.

Ya can't have both without copious amounts of copy-pasting.
