### ISSUE TITLE
Posibrains accidentally the cult

### ISSUE THREAD

**Issue by Anoonki** [ParadiseSS13/Paradise#7340]
**Problem Description**:
IPC Sacrifice targets don't work.

**What did you expect to happen**: 
Nar'sie to accept my sacrifice and pat me on the head at centcomm.

**What happened instead**:
Nar'sie accepted my sacrifice, body and all, but refused round-end greentext headpats.

**Why is this bad/What are the consequences:**
Cults shouldn't be redtexted by those filthy IPC powergamers :^)

**Steps to reproduce the problem**:
Spawn an IPC, however many cultists you need for a sacrifice, designate said IPC as the sacrifice target, sacrifice 'ol robocop, call the shuttle, redtext. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I've really got nothing. This is something I noticed a few months ago (like, september/august 2016), as the sacrificed IPC, and brought up on discord today, was asked to reproduce it, and reproduced it flawlessly. Followed the steps above, got a stern talking to by nar'sie at centcomm.

**Comment by Aurorablade** [comment]
its probaly not ipcs but sac targets in general..a bug i thought i fixed.

**Comment by Aurorablade** [comment]
also was the message you got "Yes! This is the one I desire! You have done well." OR ""I accept this sacrifice."

**Comment by Aurorablade** [comment]
...Wait posibrains? Did you try to sacrefice and IPC or a POSIBRAIN

**Comment by Anoonki** [comment]
http://i.imgur.com/zD2LVIJ.gif "I accept this sacrifice"

**Comment by Aurorablade** [comment]
Thats the message that happens when you sacrefice something thats NOT your target. Does this happen on ANY OTHER race?

**Comment by Anoonki** [comment]
I didn't test this extensively, and didn't test with many other races, I only tested it to confirm that it was still the case with IPCs.
And I'm certain that the IPC was designated as the target, so I don't know what to tell you about that one.

**Comment by borers** [comment]
Actually I accidentally sharded the sacrifice target IPC HAZEL, no bugs here only stupidity on my part and no safeguards on sharding.

**Comment by Anoonki** [comment]
Huh, aight, I totally thought I saw someone slap down a rune under him. Disregard.
