### ISSUE TITLE
Cult members can cut open mechanical limbs to write in blood

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7342]
**Problem Description**:
In a cult round I was spectating, a cultist made the rune that summons Nar'Sie by cutting open a metal limb and somehow extracting blood from it.

**What did you expect to happen**: 
For that lad to get blood out from one of his other non-mechanical limbs.

**What happened instead**:
That lad cut open his mechanical leg and wrote the rune in the spontaneously generated blood that came out of it.

**Why is this bad/What are the consequences:**
Last I checked, those are robotic/electronic/mechanical limbs, not some kind of metal covering for your skin, and you can't just extract blood from a metal limb.

**Steps to reproduce the problem**:
Be a cultist with a mechanical limb, select that limb and try to create a rune.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The mechanical limb was the lad's left leg. Two other cultists were able to make runes by cutting open their mechanical left hand and mechanical right foot as well.
~~4th bug report this week, i'm on a roll!~~

**Comment by taukausanake** [comment]
IPCs can also bleed for cult purposes so might be a related issue
