### ISSUE TITLE
Downloading Files

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7349]
**Problem Description**:
If you download a custom made text file, and restart the P2P client, the screen stays blank

**What did you expect to happen**: 
Getting the normal screen to download more ~~RAM~~ files.

**What happened instead**:
Screen stays blank.

**Why is this bad/What are the consequences:**
You can't even use the computer unless you remove a vital component that does shut down the programm or computer.

**Steps to reproduce the problem**:
Take two modular computers, get the P2P programm, make a text file (with contents), share it with the world, download it with the other computer, cry as you broke your computer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Did also try to set a password afterwards on the file, and download it again, might have broke it also. The P2P for the other computer works fine, so not a cache issue.

**Comment by MarsM0nd** [comment]
Also did get the runtime error:
```
Runtime in nttransfer.dm,189: Cannot read null.filename
  Caught by process: nanoui
  src: /datum/nanoui (/datum/nanoui)
```
and the callstack would be
```
  /datum/computer_file/program/n... (/datum/computer_file/program/nttransfer): ui data(Charname (/mob/living/carbon/human), "main", /datum/topic_state/default (/datum/topic_state/default))
  /datum/nanoui (/datum/nanoui): open()
  /datum/computer_file/program/n... (/datum/computer_file/program/nttransfer): ui interact(Charname (/mob/living/carbon/human), "main", /datum/nanoui (/datum/nanoui), 1)
  the console (/obj/item/device/modular_computer/processor): ui interact(Charname (/mob/living/carbon/human), "main", /datum/nanoui (/datum/nanoui), 0, null, /datum/topic_state/default (/datum/topic_state/default))
  /datum/nanoui (/datum/nanoui): update(0)
  /datum/nanoui (/datum/nanoui): process(1)
  /datum/nanomanager (/datum/nanomanager): update uis(the console (/obj/item/device/modular_computer/processor))
  /datum/nanoui (/datum/nanoui): Topic("src=\[0x2101969e]_184;action=P...", /list (/list))
  ckey (/client): Topic("src=\[0x2101969e]_184;action=P...", /list (/list), /datum/nanoui (/datum/nanoui))

```

**Comment by tigercat2000** [comment]
#7966 confirmed to fix the problem, make a new issue report if there are any other bugs with this.
