### ISSUE TITLE
Coroner Labcoat has no vox sprite

### ISSUE THREAD

**Issue by IK3I** [ParadiseSS13/Paradise#7355]
**Problem Description**:
No sprite for coroner labcoat on vox

**What did you expect to happen**: 
Every other labcoat has one

**What happened instead**:
Put on coat, no sprite is displayed

**Why is this bad/What are the consequences:**
It's inconsistent and if there's no sprite, it looks like you're not wearing something that is capable of storing objects

**Steps to reproduce the problem**:
Be a vox, put on coroner labcoat

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing out of the ordinary, Not even being naked showed any sprite.

**Comment by KasparoVy** [comment]
On it.
