### ISSUE TITLE
Round start disabilites broken

### ISSUE THREAD

**Issue by Necaladun** [ParadiseSS13/Paradise#7369]
**Problem Description**:
As a human, unable to toggle on/off any disability apart from obese.

**What did you expect to happen**: 
That they could toggle on.

**What happened instead**:
They did not toggle on.

**Why is this bad/What are the consequences:**
Mostly because you can't toggle them off, either.

**Steps to reproduce the problem**:
Go into lobby
Make char
Select disabilities
Try toggling them on/off
Cry

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Obese works, nothing else tho?

**Comment by Crazylemon64** [comment]
#7019 may have something to do with this - it was the most recent PR to touch prefs code

**Comment by KasparoVy** [comment]
WOOPS. On it.
