### ISSUE TITLE
Unattached scrubber to pipe network; Central Primary Hallway Air Scrubber #1

### ISSUE THREAD

**Issue by Turnip-Fruit-Chews** [ParadiseSS13/Paradise#7373]
**Problem Description**:
There's a scrubber that is not attached to the scrubber pipes network, it merely is connected to three pipes that obviously should connect to the tile NEXT to where they end.

**What did you expect to happen**: 
While roaming around as a drone I popped out in the middle of a wall, not into a network of pipes through the scrubber in a public area. I expected the scrubber to be correctly connected, with no modification/sabotage from the start of the shift.

**What happened instead**:
The pipe leads up three tiles and ends in the reinforced wall north of the scrubber. The scrubebr network has a manifold that ends at the maintenance door right next to it, as if the scrubber and pipes in the hall had been shifted over one tile.

**Why is this bad/What are the consequences:**
It seems like an inconsistency with how the rest of the station is correctly piped, and this extremely public and high-traffic area has an unconnected scrubber.

**Steps to reproduce the problem**:
T-ray scanner while one tile south of the maintenance door, three tiles north of the Central Primary Hallway Air Scrubber #1

**Comment by SamHPurp** [comment]
Someone borked a load of atmos at some point in the past few weeks. I fixed a bunch of them, but not all.

I'll try to get into this one later. Thanks for reporting!

**Comment by FalseIncarnate** [comment]
For reference, is this at the junction above the bridge? If so, that may have been caused by the repiping resulting from the brig remap.

**Comment by Turnip-Fruit-Chews** [comment]
Yes, it's the area just north of the bridge, specifically next to the maintenance tunnel entrance there.
