### ISSUE TITLE
No lawnmower needed

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7378]
**Problem Description**:
Grass plant won't produce grass.

**What did you expect to happen**: 
To be able to harvest grass.

**What happened instead**:
The grass never became harvestable

**Why is this bad/What are the consequences:**
You can't make grass, so no astroturf, which can be used for decoration or sand.

**Steps to reproduce the problem**:
(Might be optional, or the cause:)Modify the grass to have the a good production speed and yield.
Plant grass.
Never see the tray blinking green.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Grass has a maturation of 2, with a production speed of one, might be to fast. Both times i've seen it happen should have been in a gaia tray. Think the first time i've seen it, the grass became harvestable when it was dying from old age.

**Comment by Wh00pAss** [comment]
I just had this happen twice (separate trays) maxed grass 2-1 speed in a gaia tray that had been robusted to remove mutation. It was harvestable after 33 cycles
