### ISSUE TITLE
Changling Transform runtime

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#7383]
THEY BE MISSING HEADS
(Name/ckey of person taken from redacted)
[02:25:10] Runtime in organ_icon.dm,110: cannot read from list
   proc name: get icon (/obj/item/organ/external/head/get_icon)
   usr: (/mob/living/carbon/human)
   usr.loc: The floor (131,164,1) (/turf/simulated/floor/wood)
   src: the head (/obj/item/organ/external/head)
   src.loc: (/mob/living/carbon/human)
   call stack:
   the head (/obj/item/organ/external/head): get icon(0)
    (/mob/living/carbon/human): update body(1, 0)
   (/mob/living/carbon/human): update eyes()
   (/mob/living/carbon/human): UpdateAppearance(null)
   Transform (/obj/effect/proc_holder/changeling/transform): sting action( (/mob/living/carbon/human), null)
   Transform (/obj/effect/proc_holder/changeling/transform): try to sting( (/mob/living/carbon/human), null)
   Transform (/obj/effect/proc_holder/changeling/transform): Click("Changeling", "infowindow.info", "left=1")

**Comment by KasparoVy** [comment]
Wheeeeere's yooooo heeeead aaaaaaat...

**Comment by Aurorablade** [comment]
@KasparoVy gonna ping you on these related head runtimes.

 Runtime in dna2_helpers.dm,227: Cannot modify null.eye_colour.
   proc name: write eyes attributes (/datum/dna/proc/write_eyes_attributes)
   src: /datum/dna (/datum/dna)
   call stack:
   /datum/dna (/datum/dna): write eyes attributes(null)

Runtime in update_icons.dm,1032: Cannot read null.alt_head
   Caught by qdel() destroying /obj/item/organ/external/head
   proc name: update inv wear mask (/mob/living/carbon/human/update_inv_wear_mask)

**Comment by Aurorablade** [comment]
@KasparoVy okay with some testing i got issues with slimes and golems 
[01:13:03] Runtime in dna2_helpers.dm,227: Cannot modify null.eye_colour.
  proc name: write eyes attributes (/datum/dna/proc/write_eyes_attributes)
  usr: Woodrow Price () (/mob/living/carbon/human/golem)
  usr.loc: The floor (49,137,1) (/turf/simulated/floor/plasteel)
  src: /datum/dna (/datum/dna)
  call stack:
  /datum/dna (/datum/dna): write eyes attributes(null)
  Woodrow Price (/mob/living/carbon/human/golem): UpdateAppearance(null)
  Woodrow Price (/mob/living/carbon/human/golem): New(the floor (49,137,1) (/turf/simulated/floor/plasteel), "Golem", 0)
  Woodrow Price (/mob/living/carbon/human/golem): New(the floor (49,137,1) (/turf/simulated/floor/plasteel))
  /datum/admins (/datum/admins): Topic("src=%5B0x2100ddc4%5D_134&filte...", /list (/list))
  Fethas (/client): Topic("src=%5B0x2100ddc4%5D_134&filte...", /list (/list), /datum/admins (/datum/admins))
[01:13:17] Runtime in dna2_helpers.dm,227: Cannot modify null.eye_colour.
  proc name: write eyes attributes (/datum/dna/proc/write_eyes_attributes)
  usr: Boppop Bopboop () (/mob/living/carbon/human/slime)
  usr.loc: The floor (52,137,1) (/turf/simulated/floor/plasteel)
  src: /datum/dna (/datum/dna)
  call stack:
  /datum/dna (/datum/dna): write eyes attributes(null)
  Boppop Bopboop (/mob/living/carbon/human/slime): UpdateAppearance(null)
  Boppop Bopboop (/mob/living/carbon/human/slime): New(the floor (52,137,1) (/turf/simulated/floor/plasteel), "Slime People", 0)
  Boppop Bopboop (/mob/living/carbon/human/slime): New(the floor (52,137,1) (/turf/simulated/floor/plasteel))
  /datum/admins (/datum/admins): Topic("src=%5B0x2100ddc4%5D_134&filte...", /list (/list))
  Fethas (/client): Topic("src=%5B0x2100ddc4%5D_134&filte...", /list (/list), /datum/admins (/datum/admins))

the issue is coming from a null list issue with eyecolors..but i am not really good with the system to know what to lookg for to fix..or where to put a safety check.

**Comment by Contrabang** [comment]
This has been fixed at some point
