### ISSUE TITLE
Sparking ghosts

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7386]
**Problem Description**:
Having the door interface open as (admin)ghost while that door is shocked does cause it to spark.

**What did you expect to happen**: 
Ghost beeing undetectable while checking on the door

**What happened instead**:
Door is sparking.

**Why is this bad/What are the consequences:**
Ghosts should be unable to cause observeable effects for ingame players.

**Steps to reproduce the problem**:
Shock door, aghost, click door.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Electrification wire was cut, door welded, wirepanel open.

**Comment by SamHPurp** [comment]
I guess this is triggering on all interacts... and if you have advanced interactions enabled as an admin....

**Comment by taukausanake** [comment]
S p o o k y

Not sure if bug or working as intended. I'd vote the latter but some might want to be completely invisible

**Comment by TullyBurnalot** [comment]
Unsure if this is even a bug. AFAIK, Adminghosts are supposed to be able to interact with most of everything.

**Comment by SamHPurp** [comment]
@TullyBurnalot Aye, if anything, it might warrant a quick check if its an admin interact, then not to issue the sparks... but, I'm not certain its that important to do tbh.

**Comment by Fox-McCloud** [comment]
fixed
