### ISSUE TITLE
Unable to see pipes when vent crawling the brig.

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7389]
**Problem Description**:
I was un-able to see any pipes when I was crawling through the brig's piping system just now.
![image](https://cloud.githubusercontent.com/assets/7415122/26464103/8342bc3e-417e-11e7-89f2-00c0a5923701.png)
At the time of the screenshot, I was a Terror Spider in that blue pipe. You can see from the blue pipes down the hall, that I cannot physically see, the pipes still show up for me. However they do not once in the brig.

![image](https://cloud.githubusercontent.com/assets/7415122/26464285/1fb9000a-417f-11e7-9048-7d43d7049f76.png)

This MAY be a result of the **manual valve** I had to crawl through, because you cannot see the manifold or the one in the wall just after it.

**What did you expect to happen**: 
Continue to see all the pipes..

**What happened instead**:
Could only see the visible pipes.

**Why is this bad/What are the consequences:**
Blind crawling isn't fun.

**Steps to reproduce the problem**:
Be terror spider. Crawl vents. Go to brig. Cry.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was a Terror Spider, nothing else is out of the ordinary.

**Comment by pinatacolada** [comment]
you can actually see the pipes once you exit and reenter a vent that is inside of brig, which is p weird

**Comment by Anticept** [comment]
I believe it is because it's two different pipenets. Add a vent to the above tile pipes in atmos, vent crawl, and I'm willing to bed you won't see any of the under-tile pipes around the station until you leave and re-enter.

**Comment by Crazylemon64** [comment]
Right now, pipecrawl code doesn't support handling moving between pipenets while crawling. There was some part of that in the works, but then it got splintered.
