### ISSUE TITLE
Hijacked / rotated shuttles engine + heater don't rotate properly

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7395]
**Problem Description**:
When you rotate a shuttle, the engine & heater rotate twice.
This is what it looks like when you hijack from Box station
https://cdn.discordapp.com/attachments/145700319819464704/317682346528866305/unknown.png

This is what it looks like when you arrive at Box's z2 from MetaStation (don't worry about that detail too much ;) )
https://cdn.discordapp.com/attachments/145700045008797697/317678286178222090/unknown.png

It LOOKS LIKE, they are rotating TWICE.

**Why is this bad/What are the consequences:**
Inefficient aerodynamic design.

**Steps to reproduce the problem**:
Hijack shuttle from Box Station is the easiest way to see this in action.

**Comment by taukausanake** [comment]
Wasn't there an issue with the direction sprites for some of these? Was a proper fix applied to them back then? It sounded at the time it wasn't but I cannot recall

**Comment by Sirryan2002** [comment]
This appears to have been fixed, rotation is done properly now.
