### ISSUE TITLE
Mindslave Gets New Master When His Old One Cryos.

### ISSUE THREAD

**Issue by SheepFighter** [ParadiseSS13/Paradise#7402]
**Problem Description**:
I was mindslaved by a traitor. My master went SSD, and was eventually cryoed. Upon this happening, I was informed that my "target" was out of reach and that a new one was being selected. Checking my notes, I found that my master was now the Security Pod pilot.

**What did you expect to happen**: 
I honestly hadn't considered this scenario, but it would have made sense for the mindslave to revert to his old loyalties

**What happened instead**:
What's going on here is fairly obvious. 
As far as the game is concerned, a mindslave is a traitor with the Protect objective.  His master is technically his target. So, when his master cryos, the game does precisely what it should, technically: It randomly selects another player for him to protect.

**Why is this bad/What are the consequences:**
As bugs go, this is comparatively benign. But it's still glaringly broken and will, if nothing else, confuse the dickens out of someone. The new master isn't made aware of his new servant, which makes it even more awkward.

**Steps to reproduce the problem**:
This requires two players.
Player A, being a traitor, mindslaves Player B. 
Player A then heads to cryogenic storage and logs out. 
Then, *boom*, a new master for B!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I expect that this also applies to vampire thralls, which would be even more confusing for the poor player.
I'm not sure about shadowling thralls, but it's not like a hatched shadowling is going to cryo.

**Comment by Crazylemon64** [comment]
oh huh I think this is a silly abuse of an "assassinate" objective

**Comment by FalseIncarnate** [comment]
Actually, I believe it is the "Protect" objective.

**Comment by SteelSlayer** [comment]
No longer an issue, was fixed in #16947.
