### ISSUE TITLE
Deleting People Leaves Gear Behind

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#7416]
**Problem Description**:
Using delete on a mob leaves behind gear. Specifically, gear on their limbs (meaning head, arms, legs.)

**What did you expect to happen**: 
Everything should be deleted

**What happened instead**:
Admin specific gear was left behind because it was on a limb

**Why is this bad/What are the consequences:**
Delete should remove everything from existance, and should not leave things behind.

**Steps to reproduce the problem**:
1. Spawn Mob
2. Equip Mob with gear
3. Delete Mob
4. Loot the sweet tasty pile of loot left behind.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Admin delete command, accessible from the right click menu.

**Comment by scrubmcnoob** [comment]
Please fix, quite annoying.

**Comment by KasparoVy** [comment]
Seems recent. I can recall this not being the case some time ago. I think it's in relation to GC changes?

**Comment by SheepFighter** [comment]
Funnily enough, I just noticed this. That said, the code I was using was from the 6th or 7th of this month, so who knows when it popped up?

**Comment by TDSSS** [comment]
Tried to reproduce this, didn't manage to. I think this might be fixed by now.
