### ISSUE TITLE
Meth, It's lightspeed in a bag

### ISSUE THREAD

**Issue by IK3I** [ParadiseSS13/Paradise#7418]
**Problem Description**:
Drugs, such as meth, still have broken movement speed modifiers

**What did you expect to happen**: 
A substantial but not relativistic boost to movement speed

**What happened instead**:
What movement delay?

**Why is this bad/What are the consequences:**
Meth is already a strong anti stun chem with good movement speed. Adding more speed just makes it impossible to deal with as you can literally outrun some projectiles.

**Steps to reproduce the problem**:
Be a person that processes chems. Take meth. Fly away

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by Fox-McCloud** [comment]
This wasn't really changed; Meth has always made your *absurdly* fast. This is definitely one thing not impacted by the movement refactor; it's always made you have sanic speeds.
