### ISSUE TITLE
Superfart is broken.

### ISSUE THREAD

**Issue by SheepFighter** [ParadiseSS13/Paradise#7419]
**Problem Description**:
What the title says. The Superfart power does not actually do anything. You get the message about gritting your teeth, but that's it.

**What did you expect to happen**: 
I expected the power to work like it did until several months ago. 

**What happened instead**:
Instead there's no fart, let alone a super one.

**Why is this bad/What are the consequences:**
It's straight-up broken. And it's a rather fun power. Not to mention that it affects your genetic stability without anything to show for it.

**Steps to reproduce the problem**:
Get the superfart power, either by using an SE injector or through the "Add Power" option on the view variables panel (Admin-only.)
Activate the power. 
Watch as nothing actually happens.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
There's not much else to add. It's gone under the radar for a while now, which doesn't help matters. Perhaps someone who regularly plays genetics can tell us when it broke.

**Comment by Allfd** [comment]
This is probably a good thing

**Comment by SheepFighter** [comment]
_De gustibus non est disputandum_ and all that, but that's the province of a PR. Removal by atrophy is bad design.
