### ISSUE TITLE
Server is crashing due to illegal operation - "update icon"

### ISSUE THREAD

**Issue by tmad40blue** [ParadiseSS13/Paradise#7421]
Unable to start the Paradise server due to an illegal operation.

Hastebin startup/crash log: https://hastebin.com/nokavazido.sql

**Steps to reproduce the problem**:

1. Download and compile Paradise source.
2. Start server with `DreamDaemon paradise.dmb <port> -trusted`
3. Crash.

**Comment by SamHPurp** [comment]
Is this with parent Paradise code out-of-the-box, or have you made modifications?

**Comment by tmad40blue** [comment]
Do configs count as modifications? If so, then yes, I've edited files in the config/ directory only.

**Comment by tmad40blue** [comment]
@SamHPurp 

After testing with a fresh download from Github, with no modified config files, I'm now receiving a slightly different crash: https://hastebin.com/ecucurapag.sql

**Comment by SamHPurp** [comment]
Interesting...

Silly question, you are opening this in DM and compiling before attempting to launch?

**Comment by tmad40blue** [comment]
I'm on Linux, so I run

`DreamMaker paradise.dme`

but yes, I'm compiling in DreamMaker prior to running.

**Comment by tigercat2000** [comment]
Our codebase has never functioned correctly under Linux for some reason. There's not really much we can do about it.

**Comment by tmad40blue** [comment]
Well that sucks. Guess I'm not running Paradise then.

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2291810#comment23342874

Fixed in 512.

its a regex issue.

https://github.com/ParadiseSS13/Paradise/pull/7266
