### ISSUE TITLE
EMP Flashlight not killing headsets

### ISSUE THREAD

**Issue by IK3I** [ParadiseSS13/Paradise#7424]
**Problem Description**:
EMP flashlight fails to EMP the headset thus allowing your victim to scream for help over comms

**What did you expect to happen**: 
The headset to turn off

**What happened instead**:
The headset remained active allowing the victim to continue speaking over comms

**Why is this bad/What are the consequences:**
It's common knowledge that EMPs shut headsets down. A localized EMP should replicate this behavior for the sake of consistency as it leads to situations like the above

**Steps to reproduce the problem**:
Blink EMP flashlight at someone -> watch in amazement as the're headset evolves EMP shielding

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a tator vamp round, I had blinked an officer and then proceeded to do vampire things only to see that he was still able to call for help. I blinked him multiple times with no effect at that point and finally gave up and stripped the headset entirely.

**Comment by Birdtalon** [comment]
@Crazylemon64 this was fixed.
