### ISSUE TITLE
Shadowlings Rapid Re-hatch Not Fixing Eyes

### ISSUE THREAD

**Issue by scrubmcnoob** [ParadiseSS13/Paradise#7425]
**Problem Description**:
The eyes of a shadowlings do not heal, even after using rapid re-hatch.

**What did you expect to happen**: 
I expected my eyesight to be 10/10 again.

**What happened instead**:
My eyes stayed really blurry and disgusting. Very hard to play this way.

**Why is this bad/What are the consequences:**
It's really annoying to play with blurry vision.

**Steps to reproduce the problem**:
Take a flash and spam it on a sling. Their vision will be messed up

**Possibly related stuff (which gamemode was it? 
It was shadowlings my dude.

**Comment by Fox-McCloud** [comment]
I think you mistake the purpose of re-hatch.

It's largely meant for becoming a shadowling again if someone extracts your brain and clones you or manages to find some other way to de-shadowling you.

It just sets your species back to shadowling and re-equips all the necessary gear; it's not meant to do anything else.
