### ISSUE TITLE
MetaStation: Pipes outside Turbines

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#7427]
**Problem Description**:
Unable to unwrench the pipes from engineering airlock to turbine airlock.

**What did you expect to happen**: 
It's a pipe. You should be able to unwrench it.

**What happened instead**:
It stays wrenched in place

**Why is this bad/What are the consequences:**
You cannot redirect the pipes

**Steps to reproduce the problem**:
Select wrench. Select corner pipe or straight pipe.

**Comment by SamHPurp** [comment]
Have you tried ripping up the tile? Does it work then?

I'll look into this in the morning, but that might work for you.

**Comment by Trubuss** [comment]
There was no tile to rip up. Would have gone to space. Had no hard suit to check.

**Comment by SamHPurp** [comment]
I cannot reproduce this at all.

![image](https://cloud.githubusercontent.com/assets/7415122/26653764/195a4f44-464c-11e7-8745-bd0cc9e798ad.png)

**Comment by Trubuss** [comment]
How odd... I had to get an admin to delete it. Maybe a one time thing? I will have to try again.
