### ISSUE TITLE
Outpost cameras don't show.

### ISSUE THREAD

**Issue by Forenzek** [ParadiseSS13/Paradise#7428]
**Problem Description**:
What is the problem?
The mining outpost cameras do not show on any of the monitors on the bridge or HoP's office even though it is listed at the top as able to be added.

**What did you expect to happen**: 
Why do you think this is a bug?
Because there is a monitor dedicated to these cameras but they are not viewable.

**What happened instead**:
How is what happened different from what you expected?
see above.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Broken feature, and makes the outpost unable to be monitored should the need arise.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Open the console like normal and try to view.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by SamHPurp** [comment]
This is a MetaStation issue.

I'll fix this on my next set of fixes. Cheers.
