### ISSUE TITLE
*Metastation* Missing Telecomms Key

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#7430]
**Problem Description**:
The decryption key note does not appear to spawn in the RD's office, assuming it wasn't stolen before I joined.

**What did you expect to happen**: 
On Box Station the key spawns on the RD's desk at round start.

**What happened instead**:
See description.

**Why is this bad/What are the consequences:**
The RD needs that key to perform a part of their job, namely, monitoring the PDA server when necessary, as well as keeping the key itself safe.

**Steps to reproduce the problem**:
Check the RD's desk at round start.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by SamHPurp** [comment]
It spawns on the CE's desk on MetaStation.

I do agree though, the RD should have it.
