### ISSUE TITLE
[Metastation] Chapel shutters are transparent

### ISSUE THREAD

**Issue by coldud13** [ParadiseSS13/Paradise#7432]
**Problem Description**:
You can see through the shutters in the chapel when they are closed.

**What did you expect to happen**: 
I expected the shutters to block vision when closed.

**What happened instead**:
I could see through them when shut.

**Why is this bad/What are the consequences:**
Unable to get privacy from any space carp.

**Steps to reproduce the problem**:
Press either of the shutter buttons in the chapel.
Watch as you can see through the other side.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The round was testing the new atmos system, I didn't see if the closed shutters still blocked atmos.

**Comment by SamHPurp** [comment]
Damn, I fixed about 80 other instances of this, just missed this one.

Will get on the next fix run, thanks!
