### ISSUE TITLE
[Metastation] Engineering secure storage blastdoors don't block air 

### ISSUE THREAD

**Issue by Allfd** [ParadiseSS13/Paradise#7433]
**Problem Description**:
Engineering secure storage blast shutters don't block atmospherics.

**What did you expect to happen**: 
Secure storage blastdoors to be air tight.

**What happened instead**:
Gasses freely pass when blastdoors closed

**Why is this bad/What are the consequences:**
Giant plasma fire in engineering.

**Steps to reproduce the problem**:
Do air stuff on one side with doors closed, watch it pass.

**Comment by SamHPurp** [comment]
@Allfd 

Cool, so this is actually a bug with the doors. Once opened the atmos passing doesn't get denied again when closed.

So if you do this at round start without opening the doors, they don't leak atmos.

The reason this doesn't happen on BoxStation is that there are firelocks there that drop at the detection of plasma.

I'll do two steps to fix this, I'll look into the Blast door code... and I'll add firedoors to Meta.

Cheers
