### ISSUE TITLE
Security Camera Computer Cannot Deconstruct

### ISSUE THREAD

**Issue by Alexshreds** [ParadiseSS13/Paradise#7438]
**Problem Description**:
Instead of disconnecting the computer after hitting it with a screwdriver nothing happens and the camera window pops up, regardless of it being powered (window doesn't pop up when not powered as usual).

**Why is this bad/What are the consequences:**
These computers are now permanent for the most part.

**Steps to reproduce the problem**:
Build a security camera console and then try deconstructing it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was on the engineering outpost.

**Comment by SamHPurp** [comment]
Duplication of #6802
