### ISSUE TITLE
(Boxstation)  Cell 6 vent is not actually connected to the atmospherics system

### ISSUE THREAD

**Issue by Draycros** [ParadiseSS13/Paradise#7442]
Quite simply.  Spawned as mouse on top of the vent.  Went to crawl through it to leave the cell and popped out on the floor on the other side of the window having taken damage due to no atmosphere being in the pipe.  Got in a nearby vent to see what was up and noticed the cell simply was not connected to the atmos loop in the Brig

![image](https://cloud.githubusercontent.com/assets/6957354/26717112/c6c5f5fc-4741-11e7-94ca-5cd99fad1bb9.png)

**Comment by FreeStylaLT** [comment]
Curses.
