### ISSUE TITLE
R&D problem after the new port??

### ISSUE THREAD

**Issue by MasterrExploder** [ParadiseSS13/Paradise#7446]
Problem Description:
R&D is still usable at round start

What did you expect to happen
I expected to join in as a scientist, and do nothing the whole game.

What happened instead:
instead, R&D was still semi-functional, I had to beg people for random items from other departments and command

Why is this bad/What are the consequences:
All science is the work of the devil, and is heresy. The consequences could be anything from people having an easier job because their machines are upgraded, and/or people having fun, which is contrary to paradise's HRP standards.

Steps to reproduce the problem:
remove the entire science department, soon all those dirty power gaming scumlords will move on to sci chem and toxins, so we should nip that before it starts

Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?): 
Any round where fun might happen.

**Comment by Fox-McCloud** [comment]
please post actual issues instead of meaningless snark.

**Comment by Aurorablade** [comment]
Greetings. Please do not clog out bug report system with Meme reports.
