### ISSUE TITLE
IPC's and disabilities.

### ISSUE THREAD

**Issue by swordsith** [ParadiseSS13/Paradise#7447]
**Problem Description**:
When I attempted to use a disability on a machine type species (colorblindness specifically) it resulted in nothing happening, While I assume the other disabilities may not work either i'm too lazy to check. 

**What did you expect to happen**: 
My view should've been in black & white, when i entered the round as X machine character.

**What happened instead**:
My view was in normal color when i entered the round as X machine character.

**Why is this bad/What are the consequences:**
Not quite bad but MUH RP'

**Steps to reproduce the problem**:
>Join server
>Setup character
>Load or create machine type character
>Select disabilities option 
>enable colorblindness
>save character
>join round.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
Nop

**Comment by Fox-McCloud** [comment]
This is 100% intentional. All disabilities are genetic, by nature, and as such, all IPCs are immune to disabilities as they're machines.

**Comment by swordsith** [comment]
@Fox-McCloud I assumed it may be better just to remove the button when you have the IPC class selected to remove confusion but i see where you're coming from.

**Comment by KasparoVy** [comment]
@swordsith Good idea.
