### ISSUE TITLE
Virology issues (Symptom impossible to get and missing stats)

### ISSUE THREAD

**Issue by ProcessedSpecimen** [ParadiseSS13/Paradise#7454]
**Problem Description**:
The level 5 symptom Hyphema is impossible to roll when carrying out virology and the stats for the symptom Projectile Vomiting are incomplete.

**What did you expect to happen**: 
I Expected to be able to roll Hyphema using weakened virus plasma and I expected Projectile Vomiting to have all of the stats available

**What happened instead**:
I have tried for two shifts to roll Hyphema while working as a virologist, after this I set up my own private server to try to get the symptom to appear but had no luck. There are only four working level 5 symptoms so it shouldn't be that hard to get the symptom to appear.

Whilst checking the github I found that the Projectile Vomiting symptom looks to be incomplete. 

The description says:
Projectile Vomiting
	Very Very Noticable.
	Decreases resistance.
	Doesn't increase stage speed.
	Little transmittable.
	Medium Level.
Bonus
	As normal vomiting, except it will spread further,
	likely causing more to walk across the vomit.

But the code only gives:
/datum/symptom/vomit/projectile

	name = "Projectile Vomiting"
	stealth = -2
	level = 4

/datum/symptom/vomit/projectile/Vomit(mob/living/carbon/M)
	M.vomit(6,0,1,5,1)

Whereas all other symptoms have values for the other stats like so:
/datum/symptom/vomit/blood

	name = "Blood Vomiting"
	stealth = -2
	resistance = -1
	stage_speed = -1
	transmittable = 1
	level = 4
	severity = 5

**Why is this bad/What are the consequences:**
One of the symptoms is impossible to get which makes building certain viruses impossible and one of the symptoms is incomplete.

**Steps to reproduce the problem**:
Use a pipette to add 1 U of cold virus to a beaker and then add 1 U of weakened virus plasma (Virus food + Plasma Dust = Virus Plasma + Diphenhydramine = Weakened virus plasma) to that beaker. Repeat this many times, Hyphema will not show up.

For the other symptom just look in the code for the missing stats.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Attempted on many different game modes and on a server with only me online.

**Comment by Alexshreds** [comment]
Projectile vomiting isn't incomplete. The variables 'missing' are defined under the parent 
```
/datum/symptom/vomit
	name = "Vomiting"
	stealth = -2
	resistance = -1
	stage_speed = 0
	transmittable = 1
	level = 3
	severity = 4

**Comment by ProcessedSpecimen** [comment]
Ok, thanks, that was a misunderstanding on my behalf. Have you managed to find any problem with hyphema?

**Comment by Alexshreds** [comment]
I don't see anything blatantly wrong but I can't roll it either.

**Comment by variableundefined** [comment]
the fix didn't work
