### ISSUE TITLE
Unconscious people can hear formatting

### ISSUE THREAD

**Issue by MarcellusPye** [ParadiseSS13/Paradise#7457]
**Problem Description**:
I received these lines while unconscious
...You hear something about...color=#204090>HoP
...You hear something about...color=#ff1ac6>AI

**What did you expect to happen**: 
Not to hear formatting

Why do you think this is a bug?
Most people don't hear formatting

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
It's immersion breaking

Why do you think this is an important issue?
It's a bug

**Steps to reproduce the problem**:
Be unconscious, have a script over the comms that includes colour formatting. Send lots of coloured things over the comms and wait.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I was an IPC, It was a vampire/traitor with alians. There was a comms script that coloured key words, this is probably the important part

**Comment by MarcellusPye** [comment]
This can probably be fixed by cutting out anything between braces before passing it to the segment selection function

**Comment by HereticChurch** [comment]
That moment you get knocked out so hard you can hear colour

**Comment by MarcellusPye** [comment]
I'm working on a fix. Just so nobody wastes their time.
