### ISSUE TITLE
BYOND Members treated too well

### ISSUE THREAD

**Issue by outbools** [ParadiseSS13/Paradise#7472]
**Problem Description**:
Majority of BYOND Members is unrelated to SS13. We're separated from BYOND community long time ago and BYOND dev seems to care about them with their Dragon Ball and Bleach Servers more then about us who almost exceeded every BYOND limit. 

**Why is this bad/What are the consequences:**
Why we should give them benefits? Why we should manipulate players to donate to BYOND by this benefits? It's should be their own choice.

**Related**
Yeah it's pile of oldcode inherited from /tg/ and when it's seems to making little sense to change it (benefits are small), i see zero reasons to have it remain as it is (this is still benefits). You got a Patreon though and this things can belong to Patreon.

**What im suggesting to do**
1. Remove every BYOND Membership mention from code. Not fair, i'm agree.

2. Remove any benefits from being BYOND Member. Leave an option to donate to BYOND. This will make any donation being 100% pure choice of the donator.

3.Treat BYOND Members as Goons treats them:

https://github.com/goonstation/goonstation-2016/blob/d8a2d60915fd3b74653a1b7d4b8a0910c6fc2f19/code/obj/machinery/bot/chefbot.dm#L79

**Comment by Citinited** [comment]
Can we please not carry on with this?

**Comment by outbools** [comment]
It's present in Para code and thus can be discussed here. I'm deadly serious about it.

**Comment by theOperand** [comment]
lol

**Comment by Spacemanspark** [comment]
Amazing.

**Comment by outbools** [comment]
Received NO from headmins and host on discord and forums.
