### ISSUE TITLE
Additional windows (vending machine, pda, etc) do not load

### ISSUE THREAD

**Issue by Balthusdire** [ParadiseSS13/Paradise#7477]
**Problem Description**:
When attempting to open additional windows such as PDA, vending machines, consoles, the window remains blank. 

**What did you expect to happen**: 
Opening an additional window allows you to interact with that object (such as pda)

**What happened instead**:
Upon opening the window, the new window remains blank, or occasionally loads the NT background, but nothing else appears.

**Why is this bad/What are the consequences:**
Makes the player unable to interact with many essential objects, makes the game almost entirely unplayable.

**Steps to reproduce the problem**:
Selected a vending machine, console, or any other object like that, issue presents itself immediately.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Repeatedly opening and closing the window, restarting the game, client, and pc have no effect. I tried updating and fully reinstalling byond, my graphics drivers, so far there is no difference.

Additional info: If a window is left open for a long time I get a "Navigation to page cancelled" web page error.

**Comment by Ralta** [comment]
This will be on your end, not an issue with the codebase. 

Have you tried updating Internet Explorer, and ensuring that Javascript is allowed to run in IE?

**Comment by Alexshreds** [comment]
I remember this happening on some strange occasions. You'll have to try reinstalling BYOND or clearing the BYOND cache if the above does not work.

**Comment by KasparoVy** [comment]
Happened to me lately as well, haven't been on to do the cache trick. I suspect that would fix it.

**Comment by Balthusdire** [comment]
IE is up to date and javascript is fully enabled. Tried reinstalling BYOND and clearing the cache. It worked for a few days and now just stopped again, tried doing the cache again, no difference.

**Comment by TDSSS** [comment]
I just had this error happen on my local test server. Everything as usual, except it displays an error message when the window tries to load. Close it and I get the usual 'everything is just white' issue.

Namely, "browser.receiveUpdateData failed due to jQuery or NanoStateManager being unavailable."

![untitled](https://user-images.githubusercontent.com/32099540/31826114-7ae0c126-b5b4-11e7-9f70-7ba54559c327.png)

**Comment by PacifistDalek** [comment]
I by some weird chance, this still exists, might TGUI fix it?

**Comment by Spacemanspark** [comment]
Yeah this is a NanoUI issue that does not happen with TGUI
