### ISSUE TITLE
unnecessary mech weapon logging

### ISSUE THREAD

**Issue by Bram961** [ParadiseSS13/Paradise#7478]
![Image of logs](https://puu.sh/wbQAf/97536dbfcb.png)
Lots of unnecessary log clutter because mech weapons log both every instance where they hit someone AND every instance where they are fired. The latter logs are simply unnecessary especially considering that actual attacks are also logs and the already unnecessary logs only logging the location of the mech upon firing thus lacking any direction.

**Comment by FunnyMan3595** [comment]
This is intended.
