### ISSUE TITLE
Traitor objective stealing does not count when you arrive in Centcomm with the item in your hands

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7483]
**Problem Description**:
When the shuttle or pod arrives at Centcomm, if you have a stolen item in your hands and are standing up, it does not count that you stole the item.

**What did you expect to happen**: 
For the reactive teleport armor I was holding in my hands to be considered stolen so I would get complete greentext for it.

**What happened instead**:
The item was not counted towards greentext, so I only completed two objectives instead of three.

**Why is this bad/What are the consequences:**
Well, I DID have the requested item in my hands, and just because I arrived while standing up it should not change this.

**Steps to reproduce the problem**:
Be an antag with a steal objective, obtain item, get on a shuttle or pod to escape, be standing inside the shuttle (not buckled into a chair) when it arrives while holding the item in one of your hands.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I think this bug has something to do with the item falling out of your hands when the shuttle arrives, I am asking that this check be conducted when you arrive but before the code to trigger you falling over takes place. I mean, its not like the item falling to the ground (and not breaking, mind you) means that you did not steal it. Also, I was robbed out of greentext because of this, but I suppose there is always next time.

**Comment by Ralta** [comment]
This sounds like it's working as intended to me - the item fell out of your hands, so it is not in your possession when the shuttle arrives.

**Comment by ModDownloading** [comment]
I know it fell out of my hands, its just that I think it is more sound to do the check first then the actual arrival code that makes you fall over, so other people don't get the same accident I had.

**Comment by tigercat2000** [comment]
This isn't a bug, and it wouldn't be trivial to fix either.
