### ISSUE TITLE
Writing parameters do not work on photos

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7484]
**Problem Description**:
When attempting to use a writing parameter on the back of a photo, it will not work.

**What did you expect to happen**: 
For me to be able to autograph random photography.

**What happened instead**:
The photo has [sign] written on the back instead.

**Why is this bad/What are the consequences:**
Photos should not be an exception to writing parameters.

**Steps to reproduce the problem**:
Get a photo, attempt to sign it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The pen in question was a red pen, the photo was just a random 1x1 picture I took of the floor.

**Comment by tigercat2000** [comment]
Not really a bug, photos have never used papercode.
