### ISSUE TITLE
clicking "take" on mhelps/ahelps is revealing the IC name to players.

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7485]
**Problem Description**:
clicking "take" on mhelps/ahelps is revealing the IC name to players.

**What did you expect to happen**: 
To only show ckey

**What happened instead**:
It shows ckey and IC player name.

**Why is this bad/What are the consequences:**
It's revealing IC info to players.

**Steps to reproduce the problem**:
Click take on an mhelp/ahelp. The player will inform you, regardless of their privelages, what your IC name is.

EDIT: I was observing at the time. In case this is relevant.

**Comment by tigercat2000** [comment]
Fixed by #7486
