### ISSUE TITLE
the setup character dose not show alt job equipement

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7487]
**Problem Description**:
What is the problem?
the preview of character in the setup character dose not show the alt job equipement insteed it shows  the normal job equipement
**What did you expect to happen**: 
Why do you think this is a bug?
cause inconstant between preview and game
**What happened instead**:
How is what happened different from what you expected?
i expected it to show my alt job equipement
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
is it?
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
select doctor on high
select surgeon
watch doctor preview
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
i selected surgeon not sure if issue if present on others alt jobs with special equipement

**Comment by tigercat2000** [comment]
This probably won't be fixed until we move to the /tg/station and Baystation method of preview icon generation- spawning a human, equipping it with all the right things, and rendering it to an icon.
