### ISSUE TITLE
surgery holosign switch shows at on when tho the sign is off

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7488]
**Problem Description**:
What is the problem?
surgery holosign switch shows at on when tho the sign is off
**What did you expect to happen**: 
Why do you think this is a bug?
cause how can a swith be on if the thing is off
**What happened instead**:
How is what happened different from what you expected?
i expected it to be off at round start
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
its not
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
join
see????
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
normal round

**Comment by Twinmold93** [comment]
This just sounds like round start. Just needs an icon change, maybe variable.
