### ISSUE TITLE
Support parasite telepad does not work reliably

### ISSUE THREAD

**Issue by ProcessedSpecimen** [ParadiseSS13/Paradise#7491]
**Problem Description**:
Only one out of the three times I tried to get my support parasite to teleport me did it work. The other times they said there was a message saying the pad wasn't safe or it wasn't possible even though nothing had changed.

**What did you expect to happen**: 
To be able to teleport to the pad.

**What happened instead**:
Got error messages saying teleporting wasn't possible

**Why is this bad/What are the consequences:**
Part of the support parasites functionality doesn't work.

**Steps to reproduce the problem**:
Act as a support parasite for someone, place a teleport pad down, try to recall your host to the pad.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Traitor gamemode, I was a miner, I had Lazarus balls on me... Not sure if any of this is related.

**Comment by imsxz** [comment]
Where'd you have your beacon placed?

**Comment by ProcessedSpecimen** [comment]
We tried it to the right of mining in the maintenance, then tried it in the old bar in maintenance then finally where the shuttle would spawn (That didn't work because the tile was deleted). But we had issues with the first two spots too.

**Comment by ProcessedSpecimen** [comment]
This issue is still occuring, I played as a support holoparasite today and had the same issue. I could place the pads but when I tried to teleport people to them I was given a message saying they were not safe.

The location had an atmosphere with no breaches.
