### ISSUE TITLE
no fire lock on east of cryo bay

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7492]
**Problem Description**:
What is the problem?
there is no firedoor between cryo bay and cloning
**What did you expect to happen**: 
Why do you think this is a bug?
its 2 areas
**What happened instead**:
How is what happened different from what you expected?
i expected a firelock

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
join
see
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Citinited** [comment]
Is this on metastation?

On box the firelocks exist as they should do

**Comment by tigercat2000** [comment]
Please confirm if this is Box or Meta @alexkar598

**Comment by SamHPurp** [comment]
This can be closed imo @tigercat2000 - its on Box, and is how it should be.
