### ISSUE TITLE
Pushing over cardboard cutouts removes the drawing

### ISSUE THREAD

**Issue by deep-fried-faceplant** [ParadiseSS13/Paradise#7500]
**Problem Description**:
Shoving over cardboard cutouts removes the drawing on them, if it had one.

**What did you expect to happen**: 
Expected the drawing to stay.

**Why is this bad/What are the consequences:**
I guess crayon rubs off cardboard easier than I thought. Was this intentional?

**Steps to reproduce the problem**:
Harm intent on a cardboard cutout, pick it up and right it.

**Comment by FalseIncarnate** [comment]
Entirely intentional.

**Comment by tigercat2000** [comment]
Yeah, this is intentional.
