### ISSUE TITLE
Spaghetti typo

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7505]
**Problem Description**:
Spaghetti is spelled "spagetti" in game.

**What did you expect to happen**: 
For ALL of the words to be spelled properly!

**What happened instead**:
There is a TYPO!

**Why is this bad/What are the consequences:**
Typos are a bug, bugs need to be removed, therefore typos need to be removed.

**Steps to reproduce the problem**:
Its a typo, make a plate of boiled spaghetti and look at it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The captain's blanket has a period at the end of its name, I don't know if this is a typo or just exemplifying the importance of his blanket.

**Comment by trexter555** [comment]
literally unplayable
