### ISSUE TITLE
Can buy his Grace as non-hijack chaplain

### ISSUE THREAD

**Issue by imsxz** [ParadiseSS13/Paradise#7508]
**Problem Description**:
As the Chaplain, I could buy his Grace as a traitor. I got autotraitor'd mid round.

**What did you expect to happen**: 
I expected to not be able to purchase his Grace.

**What happened instead**:
I saw his Grace on the list of items I could buy.

**Why is this bad/What are the consequences:**
Chaplains without hijack can buy a HIJACK ONLY item. It's hijack only for a reason, I think that alone explains it.

**Steps to reproduce the problem**:
Be chaplain, get selected as traitor naturally in the middle of the shift, open uplink, look at the job specific items.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was autotraitor, I got traitor in the middle of the shift. I guess it has something to do with hijack only items.

**Comment by SamHPurp** [comment]
What were the objectives you had? That shouldn't have happened, maybe an Auto-tot problem? hm

**Comment by imsxz** [comment]
Steal CE boots, kill CMO, escape alive&free.

**Comment by Fox-McCloud** [comment]
Did you actually try to purchase it?

It always appears, no matter what; it's only if you purchase it, that it fails.

**Comment by imsxz** [comment]
ohhh. no I didn't try to purchase it, it wouldn't've helped with my objectives. I was tempted to click it though. Feel free to close this PR then, I've never been traitor chaplain before.

**Comment by Fox-McCloud** [comment]
yeah, it always appears, because there's not a good framework for adding/removing things via checking for objectives, especially since uplinks can exist independent of that....so, for now, it just displays them and tells the user "no" if they try to buy it.
