### ISSUE TITLE
Karma Reminder Still Appears Even if Karma is Spent

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#7509]
![image](https://user-images.githubusercontent.com/22057974/26955183-374897f8-4c83-11e7-855d-a9a95054c584.png)

What it says on the tin. The reminder will pop up even if karma is already spent for the round. Pretty minor thing, but having it not pop up after you've spent karma seems like it should be a thing.

**Comment by SamHPurp** [comment]
Odd, when I tested this, I never had a problem!

It even popped up twice!

Was there anything odd happening that shift?

**Comment by granodd** [comment]
This was during a shift when I was mining and hand went SSD in a mining outpost room so that I could eat. Came back to tesla being loose, and may have spent my karma before disconnecting to go SSD. It may throw this heads up if you reconnect your client, but I can't be sure.

**Comment by SamHPurp** [comment]
```
for(var/mob/M in player_list)
   if(!isnewplayer(M) && !M.client.karma_spent && !M.get_preference(DISABLE_KARMA_REMINDER))
      to_chat(M, "<i>You have not yet spent your karma for the round; was there a player worthy of receiving your reward? Look under OOC tab, Award Karma.</i>")
```

Hmmm... check if they aren't in the lobby, check if they haven't spent karma yet, and check if they don't have it disabled.... Why the fuck did that appear.

**Comment by Citinited** [comment]
Is it possible that `client.karma_spent` returns `null` if you disconnect then reconnect? It's a new client (even though your ckey spent their karma already).
