### ISSUE TITLE
UI style doesn't save between games

### ISSUE THREAD

**Issue by ProperPants** [ParadiseSS13/Paradise#7510]
**Problem Description**:
The UI style will always default to midnight when a new round starts.

**What did you expect to happen**: 
I expect that when I change the UI style to "plasmafire" and press "save setup," I will have plasmafire UI next shift.

**What happened instead**:
I changed my UI style to "plasmafire" on multiple shifts, pressed "save setup" multiple times, and I still start new rounds with the default "Midnight" style.

**Why is this bad/What are the consequences:**
It'd be nice if saved preferences actually saved.

**Steps to reproduce the problem**:
Change UI style to plasmafire. Play a match with your sexy orange UI. Join the next match. Cry when your UI is greyish blue again.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I really didn't want to report this as a bug in case it's just me being stupid, but I don't know what to do at this point. You can set the UI style as plasmafire both from the preferences tab in-game and at the lobby screen, and it will still revert back next shift.

**Comment by FlattestGuitar** [comment]
Did you press the "save preferences" button, or whatever it's called? Could be that.

**Comment by ProperPants** [comment]
Yeah, more than once.

**Comment by ProperPants** [comment]
@FlattestGuitar Yup, it happened. I played a whole shift with "plasmafire" style, saved more than once (meaning I pressed the button more than once and did that multiple times over the course of the shift).

The UI style preference does not save from round to round.

**Comment by tigercat2000** [comment]
Can't reproduce this, and it definitely saves in the database correctly.
![https://i.imgur.com/sCnkHpH.png](https://i.imgur.com/sCnkHpH.png)

**Comment by Cactus2388** [comment]
I have this problem too! It's definitely reproduceable on my end.

**Comment by tigercat2000** [comment]
@ProperPants @Cactus2388 Important question- is this on a local test server, or the live server? If it's the former, I may have an idea of what the issue actually is

**Comment by ProperPants** [comment]
@tigercat2000 It's the live server - Paradise itself. I also asked a friend to test it (also on the live server), and it happened to him as well.

**Comment by Cactus2388** [comment]
@tigercat2000 Live server, my UI style never saves when I save the preference.

**Comment by AffectedArc07** [comment]
Still an issue
```dm
UI_style		= sanitize_inlist(UI_style, list("White", "Midnight"), initial(UI_style))
```

This needs to sanitize against the list of UI styles
