### ISSUE TITLE
Meteor Satellites will not go back in their crates

### ISSUE THREAD

**Issue by Ralta** [ParadiseSS13/Paradise#7511]
**Problem Description**:
Ordering the meteor shield satellites crate for the station goal delivers a crate with three meteor satellites inside. Opening the crate will have all three satellites on top of each other, but the crate will not close again. This is presumably because the satellites cannot be picked up and may be treated the same as things like lockers, vending machines etc. 

**What did you expect to happen**: 
Since they fit in the crate to start with, I would expect them to go back into the crate.

**What happened instead**:
The crate will not close, even if you try it with a single satellite.

**Why is this bad/What are the consequences:**
Few reasons: 

First, cargo will often, if they have access, open crates to ensure they have the correct number of items inside. This means engineers will have to drag the satellites away from cargo one by one, which is frustrating and slow.

Second, it makes transporting them slower. Being able to put them in a locker for transporting would allow teams to drag several satellites around to various positions rather than running back to engineering every time (which is just pointless busywork).

Third, it would give the mechanic the ability to carry a crate / container with satellites inside to assist in placement around space. And giving the mechanic things to do is ALWAYS good.

**Steps to reproduce the problem**:
Order a Shield Satellite Crate. 
Open the crate on arrival.
Try to close the crate again with one or more Meteor Shield Satellites over the crate's sprite.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A.

**Comment by tigercat2000** [comment]
Particle accelerator parts are the same, this is intentional as far as I know.

**Comment by Citinited** [comment]
This is an issue with machinery not being able to fit inside crates. The same happens with stuff like radiation collectors and emitters.

Not really an issue per se

**Comment by Ralta** [comment]
I feel it is an issue, albeit a small one. I absolutely understand the reasoning, but it feels like it makes meteor shields unnecessarily irritating to place.
At least the PA and various engine parts come in engineering crates, so require CE approval to open and access.
Come to think of it, I think Apiaries do the same as well.

**Comment by taukausanake** [comment]
Best advice for cargo techs: don't open crates meant for other departments. Let the department deal with it and missing items. Communication is healthy after all

**Comment by Ralta** [comment]
Truer words are rarely spoken, @taukausanake 

If this doesn't get "fixed" it's honestly not the biggest deal but I do think it'd be a beneficial change. If nothing else, adding a small reason to let the mechanic join in with engineering work is nice.

**Comment by SamHPurp** [comment]
This is wholly intentional. There are many instances of this.

**Comment by Fox-McCloud** [comment]
Not really a bug, and as @SamHPurp there's lots of things like this.
