### ISSUE TITLE
Sprite glitch with bowman headset and pen

### ISSUE THREAD

**Issue by trexter555** [ParadiseSS13/Paradise#7514]
**Problem Description**:
Bowman headset sprite dissapearing from head when a pen is put on the other ear

**What did you expect to happen**: 
bowman headset should stay

**What happened instead**:
the bowman headset dissapeared

**Why is this bad/What are the consequences:**
minor issue

**Steps to reproduce the problem**:
Wear magistrate's bowman headset on one ear
put gilded pen on other ear
bam the headset on your character sprite is now invisible

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: i was a kidan magistrate

**Comment by Citinited** [comment]
Curiously, if you put the pen in the left ear and the headset in the right, it displays the bowman just fine 👍

**Comment by taukausanake** [comment]
Maybe we should get proper sprites for both left AND right ears? Pretty sure we only use one ear for actual sprites but both ears use them

**Comment by tigercat2000** [comment]
The separate ear slots are evil.

**Comment by taukausanake** [comment]
I agree with Tiger, it is pretty bad but it almost makes sense. Would be nice if separate ear slots worked with things that cover them both like earmuffs. Ear slots might require a refactor soon?

**Comment by Henri215** [comment]
Could replicate and its still a problem. Like it has been said it does happen only when you put the pen in the right ear.
