### ISSUE TITLE
DAT FUKKEN DISK - issues with spacepods and mechs

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#7525]
**Problem Description**:

1. You can enter a mech with a nuclear disk equipped.
2. Spacepods and mechs can load a crate containing a nuclear disk.

**What did you expect to happen**: 
1. I expect the game to prevent this (similar to spacepods)
2. I expected this to be impossible.

**What happened instead**:
Nothing. Disk was in my inventory and in the crates, without it jumping back to the station.

**Why is this bad/What are the consequences:**
This allows the station to easily cheese nuclear operatives.

**Steps to reproduce the problem**:
1. Get dat fukken disk
2. Put it in a crate and load it into a spacepod or mech. Watch nothing extraordinary happen.
3. Have the disk in your inventory and enter a mech, see that the disk does not prevent you doing this.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

N/A

**Comment by Alexshreds** [comment]
Store the disk with the tesla and baby ops are swiss cheese

**Comment by Citinited** [comment]
Nuclear operatives are immune to the tesla (unless they take their gloves or hardsuit off for whatever reason)

**Comment by taukausanake** [comment]
I thought the tesla also dusts you if it touches you, not just you touching it?

And sure, put the disk with the tesla. Maybe they'll release it :wink:

**Comment by Citinited** [comment]
It does, however the chance that will happen once the tesla is released is slim to none. It's really not a viable strategy.

**Comment by alexkar598** [comment]
If they release tesla I'm not sure but I think I saw the tesla kill the nuke once

**Comment by Anticept** [comment]
Also, as long as you are near a grounding rod, touching the ball no longer dusts.

**Comment by Twinmold93** [comment]
My question is is this worth changing? Mechs are usually expected to remain on station, hence you would realistically be able to grab it and go. With pods, it's too easy to end up outside station range. Also so much harder to counter to get the disk.

**Comment by taukausanake** [comment]
> enter a mech with a nuclear disk equipped

And if you drop this disc is it gone forever? If I recall correctly there is no "check under seats" verb while in mechs

**Comment by Citinited** [comment]
@Twinmold93 As I see it -- the spacepods one certainly should be. If you know what you're doing in a spacepod, it's very difficult to accidentally go to another z-level, so you can just fly away from the operatives while shooting them with disablers or something.

@taukausanake If anything is dropped while in a mech, it ends up *inside* the mech, and lost forever. When the mech is destroyed it also deletes its "inventory" (in the case of the disk it gets respawned on-station though)

**Comment by Twinmold93** [comment]
I agree it shouldn't be permitted in pods, however at the same time nukies have means of tracking said disk and pod, and if they circle round on it, couple ion shots will spell disaster for the pod, on top of bullets.

**Comment by hal9000PR** [comment]
not an issue, 
and this issue annoys me when I search for balance.
