### ISSUE TITLE
Hidden Emergency Locker

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#7527]
**Problem Description**:
There is an emergency locker hidden beneath a time display.

You won't know it even exists unless you right click. I found it by utter accident some shifts ago.

![hiddenlocker](https://user-images.githubusercontent.com/12377767/27006800-779b6ad0-4e0c-11e7-9832-93b83f847816.PNG)

B/W morgue and cloning, right of that other room.

**Comment by Fox-McCloud** [comment]
The hidden locker is the deadliest.

**Comment by taukausanake** [comment]
Possible someone planted it there? Might be interesting to find out

**Comment by KasparoVy** [comment]
Not at all, it's persistent b/w rounds. It's also proven to be EXCEPTIONALLY deadly! Muahahaha.

**Comment by taukausanake** [comment]
@KasparoVy I meant in editing. Maybe someone put it there where no one would find it except them

**Comment by SamHPurp** [comment]
Looks like my fuckup when I had to fix the Conflict errors to merge Coroner, must have missed that one.

**Comment by Anticept** [comment]
Best place to hide my blueprints, I would think.

**Comment by taukausanake** [comment]
Best place to hide a body maybe

**Comment by Ralta** [comment]
Best place to hide my shame, probably.
