### ISSUE TITLE
end round report acting bad on abductors

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7532]
**Problem Description**:
What is the problem?
insteed of " _cid_ was _name_ the abductor and _status_ " it wrote " _cid_  was  _name_ the **MODE** and _status_ "

Why do you think this is a bug?
cause theres no antag called MODE

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
have abductor round
end round
see

it wrote : 
The abductors were:
Alexkar598 was Aiden Stone the MODE and had their body destroyed
Objective #1: Experiment on 6 humans. Fail.
Saul Argon was Aurora-Greenwood the MODE and died
Objective #1: Experiment on 6 humans. Fail.

**Comment by SamHPurp** [comment]
I tried fixing this a while ago, and was told it wasn't possible to do it properly without re-doing that whole system.

**Comment by Fox-McCloud** [comment]
Yeah, what @SamHPurp said.

Unfortunately, the assigned_role has to be "MODE" or else it'll throw runtimes at various points, but our system also doesn't support it being displayed as the proper title and name, either.

**Comment by tigercat2000** [comment]
This will require a gamemode refactor at some point.

**Comment by Fox-McCloud** [comment]
addressed.
