### ISSUE TITLE
You can once again permaslip people who are sharing lockers with soap 

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#7533]
**Problem Description**:
Opening and closing lockers with people inside them are treating this as if they had moved, which allows for all sorts of silly behaviour.

**What did you expect to happen**: 
Them not to slip.

**What happened instead**:
They slipped.

**Why is this bad/What are the consequences:**
This allows you to permaslip someone (or trivially kill them if you put a shard of glass in there with them while they have no shoes)

**Steps to reproduce the problem**:
1. Add bar of soap and a mob to locker.
2. Open and close the locker repeatedly, observe.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

(I think) #6081 brought this behaviour back after it was fixed. Commit fe62b212b449fb3c342ec506bcc1c806d57aabed was the commit which did this, so it should probably be fixed or something.

**Comment by tigercat2000** [comment]
Yep, #6081 broke this again, it even has a comment warning about it.
