### ISSUE TITLE
#845 strikes back

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7536]
**Problem Description**:
Can't choose Sinta'unathi or Siik'tajr as default language.

**What did you expect to happen**: 
You should be able to choose your known languages as default language to talk in.

**What happened instead**:
Default language, if any, doesn't change.

**Why is this bad/What are the consequences:**
You need to add the language key every time you want to talk in that language, instead of defaulting to it when you know you will mostly use that.

**Steps to reproduce the problem**:
Be Tajaran or Unathi, try to choose your language.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing.

**Comment by Anticept** [comment]
This must have been fairly recent, I used to be able to set them as default. I can set default other languages just fine.

**Comment by tigercat2000** [comment]
Oh, so _that's_ what those quotation marks were for........
