### ISSUE TITLE
You can eat people

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#7542]
**Problem Description**:
It is possible to eat a person. 

**What did you expect to happen**: 
I expected that a human-sized mob wouldn't be able to eat another human-sized mob.

**What happened instead**:
It happened anyway.

**Why is this bad/What are the consequences:**
It means that people with the FAT gene can hide corpses perfectly. They kill someone, eat the body... there's no evidence. Perfect corpse hiding.

**Steps to reproduce the problem**:
Have FAT gene. Kill someone. Eat the body. Perfect crime.

https://github.com/ParadiseSS13/Paradise/blob/da958cbe0bd03f39cddb6a0013cf47e45530e82d/code/modules/mob/mob_grab.dm#L390

**Comment by tigercat2000** [comment]
Confirmed this to be the _FAT_ gene, not _matter eater_. This is an intentional feature.
