### ISSUE TITLE
Donator loadout has insulated gloves

### ISSUE THREAD

**Issue by karmapay2win** [ParadiseSS13/Paradise#7552]
Furgloves in https://github.com/ParadiseSS13/Paradise/blob/463af0af7386c86d2b77b683b8458bc6b03515e2/code/modules/mob/living/simple_animal/tribbles.dm have a siemens_coefficient = 0, making them insulated.

**Comment by FlattestGuitar** [comment]
Para officially pay to win

**Comment by Regen1** [comment]
Someone's getting whipped

**Comment by Allfd** [comment]
Pay to win!!!!


Definitely an oversight.
