### ISSUE TITLE
Prions from brain burger can be extracted

### ISSUE THREAD

**Issue by karmapay2win** [ParadiseSS13/Paradise#7555]
Prions can be easily obtained from brain burgers and used in grenades/sleepy pens.

I'm going to assume the intent with brain burgers was to behave similarly to a donk pocket and merely cause an illness on consumption rather than directly containing a weapon of mass murder.

What prions do is they force an incurable disease when above a few units enters the target. This disease will then kill the person in a very short time. There is no counter to this chem other than death and cloning. I would compare it to pre-nerf plasmadust grenades but this even more broken.

**Comment by FlattestGuitar** [comment]
All food items can have their contents extracted and used. I don't see why it would be different here.

**Comment by karmapay2win** [comment]
I'm not sure you understand what prions do, none of the syndi chems or any other chems bar admin spawns even come close to how strong it is.

**Comment by FlattestGuitar** [comment]
https://github.com/ParadiseSS13/Paradise/issues/4256
Over a year ago. ;c

**Comment by karmapay2win** [comment]
Difference is that can be cured, prions are 100% no counter death after infection.

**Comment by taukausanake** [comment]
It's a good thing you need to kill someone first and take their brain. As a chef don't expect to get any brains or dead bodies, let alone monkeys, for extra meat. And if you do this and you're not an antag, or not helping an antag by their request while not doing antag actions (like murder, etc.), then I'm pretty sure an admin is going to boink you

**Comment by tigercat2000** [comment]
This isn't a bug. Balance problem, perhaps, but that's for the forums, not the issue tracker.
