### ISSUE TITLE
Venus human traps can fire through solid objects

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7559]
**Problem Description**:
Venus human traps can fire through solid objects. Walls, firedoors, all of it.

**What did you expect to happen**: 
It can lead to situations where the crew can do nothing about it.

**What happened instead**:
Shouldn't be able to attack through solid objects

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

![image](https://user-images.githubusercontent.com/521038/27165053-8a10c682-515f-11e7-8a03-e2587a223706.png)

**Comment by Spaghetti-bit** [comment]
No longer an issue. Venus fly traps leave a "tether" for a few moments but it goes away ~3 seconds max.
