### ISSUE TITLE
flOUrine instead of flUOrine

### ISSUE THREAD

**Issue by karmapay2win** [ParadiseSS13/Paradise#7564]
https://github.com/ParadiseSS13/Paradise/blob/12c4b2933ccbb0f52271532d6af503546d1499ba/code/modules/hydroponics/hydroponics.dm has flourine on lines 575 and 576 instead of fluorine

**Comment by tigercat2000** [comment]
This actually means that fluorine doesn't behave correctly in plants.

**Comment by Regen1** [comment]
>Karmapay2win

🤔
