### ISSUE TITLE
Infinite metal/glass from autolathe

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7566]
1. upgrade lathe to max
2. copy syringe gun/whatever design onto design disk
3. import to design to lathe
4. print super cheap syringe guns and recycle them in the same lathe for massive profits

**Comment by Birdtalon** [comment]
Cannot reproduce using rapid syringe guns. I assume that's what you mean as you cannot upload syringe gun to a data disk with the RnD console.

**Comment by jughu** [comment]
New object saves material costs
Old objects that are made before upgrade goes for more

**Comment by Shadow-Quill** [comment]
Cannot reproduce.
@Anasari

**Comment by AffectedArc07** [comment]
Cannot reproduce
