### ISSUE TITLE
Mech Missile Rack Projectiles Do Not Fire Properly

### ISSUE THREAD

**Issue by Xantholne** [ParadiseSS13/Paradise#7575]
**Problem Description**:
When you fire a missile from any* missile rack (SRM but likely others as well) it will not actually fire and instead fall onto the ground below the mech which can then be picked up and thrown as a handheld explosive

**What did you expect to happen**: 
Missiles to actually behave like missiles

**What happened instead**:
They fall down onto the floor instead

**Why is this bad/What are the consequences:**
You can use it to lug around at least three missiles on foot to throw out of a mech as well as making missile racks pointless on mechs that have them/construction

**Steps to reproduce the problem**:
Attach Missile rack to a mech/use ERT Maurader/ Mauler, raise it, fire. Cry as it lays on the floor below you

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Blob at the time, did not seem to affect it.

**Comment by Twinmold93** [comment]
I saw this issue. Needs fixed soon.

**Comment by dexofan23** [comment]
Fix this shit pls.
