### ISSUE TITLE
Chem Dispenser: Removing Reagents

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#758]
@Artorp 

Haven't been able to contact you any other way, so I'm going with this rather clunky method.

In any event, I'd like to request a new feature on chem chem dispensers/their childrnen; the ability to remove reagents in the chem dispenser window in the same way the chem master can: -1, -5, -10, -ALL next to each reagent that is currently in your beaker.

The lengthier recipes make switching back and forth from the dispenser to the heater and the chem master a chore, at best, to make new reagents; this should help alleviate some of that burden and make things easier for people, overall.

**Comment by Artorp** [comment]
Sure, I'll look into it.
