### ISSUE TITLE
Light shines out of bags inconsistently

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7585]
**Problem Description**:
Typically bags such as backpack don't allow light to shine around, if there is a flashlight etc within. Unless its on the floor.

**What did you expect to happen**: 
The bag shouldn't emit any light even with a torch inside it.

**What happened instead**:
Backpack with an active seclight lit everything up when on the floor.

**Why is this bad/What are the consequences:**
Inconsistent

**Steps to reproduce the problem**:
Seclite + any backpack

* On my back -> Dark

* In my hand -> Dark

* On the floor -> Lit

**Comment by taukausanake** [comment]
Oh yeah, this was happening with Botany bags and glow plants too. Guess it's will all inventory storage

**Comment by tigercat2000** [comment]
This isn't really a bug, it's how the lighting system works. If something is two layers deep in an inventory, it can't light anything up, whereas anything only one layer deep can.

**Comment by taukausanake** [comment]
Doesn't sound intentional unless you WANT things inside inventories to light up the area around them. In which case I hope it's some new meta for Shadowling fighting

**Comment by tigercat2000** [comment]
Yeah, this isn't a bug. The way the lighting system works with lights inside mobs and objects is intentional- it was designed to avoid the pitfalls of luminousity and inventories.
