### ISSUE TITLE
Missing limb issues

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7596]
**Problem Description**:
People with various missing limbs still have discernible features and sometimes floating parts. This includes horns floating midair and seeing "a stupid expression" on someone's face when they don't have a head, and also socks floating in midair when the person has no legs/feet,

**What did you expect to happen**: 
For socks or horns or facial expressions to be invisible given that the target lacks those traits.

**What happened instead**:
Horns and socks floating midair, visible facial expressions on a headless corpse.

**Why is this bad/What are the consequences:**
No matter how much mirror treatment you go through, that missing limb is still not there, and as such should not be able to hold a sock or horns up.

**Steps to reproduce the problem**:
Give a humanized animal (or just a person) horns with genetics, remove their brain, decapitate them and examine.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I discovered this through my ~~organ farm~~ "hospital" as shown here:

![space station 13 2017-06-20 130738](https://user-images.githubusercontent.com/25691743/27347755-b0df904a-55bf-11e7-8f87-5fb943266f68.png)

I also drained the blood of the neara afterwards, and all the internal organs are gone too.

This is the other log, bolded part is an issue:

This is  Unknown, a skrell!
He isn't responding to anything around him and seems to be asleep.
He does not appear to be breathing.
**He has a stupid expression on his face.
It appears that his brain is missing...
He is missing his head.**
He has a ripped cut, several tiny bruises, and several bleeding bloody stumps on his upper body.
He is missing his left arm.
He is missing his left hand.
He is missing his right arm.
He is missing his right hand.
He is missing his lower body.
He is missing his left leg.
He is missing his left foot.
He is missing his right leg.
He is missing his right foot.
He is starting to smell.

**Comment by taukausanake** [comment]
This would require a refactor of certain many things. It it matters, you can cut off a changeling's arm that is also an armblade and the armblade is still there floating about.
As for the other things you have in bold, maybe those shouldn't be showing up. Need some sanity checks maybe for if the head is missing or not?

**Comment by Twinmold93** [comment]
For sprites would require a refactor of massive proportions for, honestly, little return. The horns would be easy, as a sanity check much like the messages would. However, socks and things like that would need new sprites that separate the pair of socks to their own icons, as example. Floating limbs would need organ code work, I believe.

**Comment by taukausanake** [comment]
I believe most of these issues could be solved if you assigned certain things to the actual limb organs rather than to the mob. A whole lot of things would be solved by doing them that way but a huuuuge refactor of too many things

**Comment by Spaghetti-bit** [comment]
Still an issue, requires a refactor to remove socks.
