### ISSUE TITLE
Blob is severly underpowered for over 100 players.

### ISSUE THREAD

**Issue by Ataman** [ParadiseSS13/Paradise#7597]
The blob, especially the mid round blob, doesn't stand a chance with our current playercount. Almost all of them get located and devastated not even 5 minutes in. (Personally I never saw a mid round blob winning).
This is not surprising with a crew consisting of over 80 people at prime time.

Round start blobs are in a better position, but even they fail a lot of times.

A very simple solution in my opinion would be checking the player count on the server before spawning the blob. If there are over a hundred people online, spawn one additional blob.

**Comment by FlattestGuitar** [comment]
The game already spawns a core for every 30 players that are there at roundstart.

We really need to get our shit together and try to balance these out more, but this isn't really a bug per se, it's just a balance issue. Those, ironically enough, don't go in here, but on the forums.

**Comment by Citinited** [comment]
`The Issues section is not a place to request features, or ask for things to be changed because you think they should be that way; The Issues section is specifically for reporting bugs in the code.`

Post this on the forums

**Comment by Ataman** [comment]
If roundstart already does it then mid round blob could use the same code basically.

Off topic:
I'm not sure if fragmenting "Issues with Paradise" on two seperate platform is such a good idea. Some people only read Github while others only use the forum.
Looking at it from a practical viewpoint: There is a balance label for issues and a PR in the future can be linked nicely to this issue which is good for documenting the thing.

**Comment by tigercat2000** [comment]
Yeah, this isn't a bug, it's a balance thing.
