### ISSUE TITLE
Lightning bug

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#7598]
this is weird to explain but basically, here I am with the air alarm on the left rendering correctly
![ss 2017-06-20 at 11 43 31](https://user-images.githubusercontent.com/13833056/27359239-a42a1cd2-5612-11e7-9351-74031214427c.jpg)

However, if I walk one tile south, the air alarm renders as if it was in full light
![ss 2017-06-20 at 11 43 55](https://user-images.githubusercontent.com/13833056/27359259-b3d70bc2-5612-11e7-9079-c4258f204bc2.jpg)

This happens with anything mounted on walls, so I guess it's caused by these things being nudged into the wall

**Comment by tigercat2000** [comment]
This isn't a bug, this is just one of the weird parts of how BYOND's view system works- because that wall is hidden, the lighting overlays don't appear on top of the alarm.
