### ISSUE TITLE
Safety typo

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7599]
**Problem Description**:
Yet another typo in our midst! "Safety" is misspelled "Saftey" on both posters and on the pool temperature controller.

**What did you expect to happen**: 
For ALL the typos to be gone!

**What happened instead**:
I can still spot TYPOS!

**Why is this bad/What are the consequences:**
This typo appears in multiple spots, increasing severity

**Steps to reproduce the problem**:
It is a typo, nothing more.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: We must remove ALL of the TYPOS!

**Comment by alexkar598** [comment]
NO TYPOS ALLOWED!!

**Comment by SamHPurp** [comment]
Update your Paradise installation, I fixed the posted ones ages ago.

The only one left that I missed it seems is  the one in the pool controler NANO UI Template file.

**Comment by ModDownloading** [comment]
Whoops, sorry about the first one being false alarm, I didn't know it was fixed.
