### ISSUE TITLE
Bullet/implant removal surgery and stump-removal surgeries are broken.

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#760]
Stumps cannot be removed by any conceivable method or procedure, making decapitated people impossible to repair without getting them a new body

Bullets/implants also cannot be removed, at least from the chest, hemostat refuses to function and if you use the scalpel as if preparing to remove an organ such as lungs/heart, the implant or shrapnel do not show up in the selection.

**Comment by theColdflame** [comment]
I can confirm bullets can be removed from the head (I was patient not surgeon though, so I'm not 100% on process).

**Comment by CrAzYPiLoT-SS13** [comment]
I'll look into this.

**Comment by TheDZD** [comment]
Try testing using the surgery steps found on the Baystation wiki, those may well be more accurate that the one currently on our wiki.

**Comment by TheDZD** [comment]
This should be fixed now by #814.
