### ISSUE TITLE
Vampires get told they aren't antagonists - Collaborator system

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7604]
**Problem Description**:
Vampires can be made collaborators, and as such told they aren't antagonists:
![image](https://user-images.githubusercontent.com/7415122/27379775-894559c4-5674-11e7-9696-7dd1f8213a60.png)
Note the "YOU ARE NOT AN ANTAGONIST"

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Vamp/tot round... spawn as vampire, get made collaborator as well.

**Comment by tigercat2000** [comment]
@FalseIncarnate

**Comment by Citinited** [comment]
Best fix is probably just to change `You are NOT an antagonist` to `Unless otherwise stated, you are NOT an antagonist`

**Comment by SamHPurp** [comment]
Depends if we want Vampires to be able to be chumps/collaborators or not.

If yes, just altering the wording works.
