### ISSUE TITLE
Station not destroyed yields negative points

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7605]
**Problem Description**:
During a nukeops round, if the station is NOT destroyed, the crew LOSES points, when it should probably be the other way around.

**What did you expect to happen**: 
For the station still being non-vaporized to either give the crew points or have no impact on the score.

**What happened instead**:
The crew lost points because the Cyberiad was still intact (well, mostly)

**Why is this bad/What are the consequences:**
I think there is some degree of spite happening if the crew loses points because they survive, -1000 points for the nuke not detonating on the station does not seem right. Besides, this is not a score for the nukeops, given that the crew still gets points if nukeops members are dead.

**Steps to reproduce the problem**:
Finish a nukeops round where the station does NOT spontaneously combust into a ~~mushroom~~ spherical cloud of nuclear matter (mushroom clouds cannot form unless there is gravity).

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This has been happening for a while now by the looks of it.

**Comment by Bram961** [comment]
The station being non vaporize doesn't have an impact on the score, the issue here is that the nuke going off on station doesn't either.

The way to fix this would be to remove a large number of points for having that happen.

**Comment by taukausanake** [comment]
On the subject matter but justly off topic too, can nuking the station also count as a station that is 100% clean?

**Comment by SamHPurp** [comment]
This isn't a bug. Its a fluff metric regarding the state of the station and certain things happening positively.

This is entirely unrelated to the state of whatever antagonists comes knocking.

**Comment by tigercat2000** [comment]
Actually, @SamHPurp it's an inconsistency, the scoring in the code should really be different. It doesn't make much sense this way.

**Comment by SamHPurp** [comment]
Having re-read it, I mis-understood the issue you raised. Apologies!

**Comment by Twinmold93** [comment]
I think the easiest fix would simply be make nuking the station remove more points than just having damage does. Crew can fix damage (and therefore gain points) so that's you counter to losing points from damage.

**Comment by FunnyMan3595** [comment]
This has been fixed sometime in the intervening years.
