### ISSUE TITLE
Area Atmos Computer in Atmos Connects to UO45

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#7610]
**Problem Description**:
Area atmos computer shows only UO45 (gateway mission) items, despite being intended to connect to the Cyberiad.

**What did you expect to happen**: 
It to show Cyberiad atmos devices.

**What happened instead**:
It showed UO45 devices.

**Why is this bad/What are the consequences:**
It makes the computer more or less unusable for atmos techs.

**Steps to reproduce the problem**:
Set undergroundoutpost45 as the away mission. Load game. Use atmos computer.

**Comment by ModDownloading** [comment]
I am sorry that this is not strictly related to the bug, but how exactly do you set a specific away mission? I have been trying to do that for a while on my private testing server.

**Comment by MarcellusPye** [comment]
Perhaps this could be fixed by setting the rcon_setting of the UO45 to false? Will test when I have time.

**Comment by Kyep** [comment]
@ModDownloading In the away mission config file, simply comment out every other entry. It will only have 1 choice of what to load.

**Comment by ModDownloading** [comment]
Thank you, I didn't know that the config file could do that. I am sorry that I can't help with this issue.

**Comment by MarcellusPye** [comment]
It's fine authough the coder section of the dischord would probably have been a better place for the question.

**Comment by MarcellusPye** [comment]
The air alarm does not appear to care about it's rcon_setting.

**Comment by MarcellusPye** [comment]
@Kyep My pull fixed this, it can be closed now.

**Comment by tigercat2000** [comment]
@MarcellusPye Future reference: Put `Fixes #7610` anywhere in the OP and it'll automatically close issues when it's merged, see https://help.github.com/articles/closing-issues-using-keywords/
