### ISSUE TITLE
detomatix card shows the nuke shuttle door button

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7611]
**Problem Description**:
What is the problem?
when the detomatrix card is inserted into a PDA you can see a button nammed "Toggle Door" which i suppose is for opening the nuclear ops shuttle blast door

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
can make some people new at the game confused on this weird button

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
be traitor
buy detomatix
insert into PDA
go to main screen
see???
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
dont rememeber gamemode ,i was traitor

**Comment by Citinited** [comment]
```
/obj/item/weapon/cartridge/syndicate
name = "Detomatix Cartridge"
icon_state = "cart"
var/initial_remote_door_id = "smindicate" //Make sure this matches the syndicate shuttle's shield/door id!!	//don't ask about the name, testing.
```

Looks like it *is* intentional, but as to why the demomatix would have this ability, I'm not sure... Can @tigercat2000 @Crazylemon64 @Fox-McCloud confirm / deny this should be the case?
