### ISSUE TITLE
end round report(again for more...)

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7612]
**Problem Description**:
What is the problem?
when on traitor it switchs between antagonist and traitor when writing if successfull or not

example: The traitors were:
Alriac was Slippy Joe (survived) (used 11 TC) 
Objective #1: Assassinate Joseph King, the Chief Engineer. Fail.
Objective #2: Escape on the shuttle or an escape pod alive and free. Success!
Objective #3: Acquire the "Blue" secret documents held by Cindy Fay, the Civilian and syndicate agent Success!
The **antagonist** has failed!
Meowingston was Cindy Fay (survived) (used 20 TC) 
Objective #1: Acquire the "Red" secret documents held by Slippy Joe, the Clown and syndicate agent Fail.
Objective #2: Steal the nuclear authentication disk. Fail.
Objective #3: Escape on the shuttle or an escape pod alive and free. Success!
The **traitor** has failed!
Freedomcaged was Mimera (survived) (used 0 TC) 
Objective #1: Steal a nasa voidsuit. Fail.
Objective #2: Assassinate Teival Lichonn, the Medical Doctor. Fail.
Objective #3: Escape on the shuttle or an escape pod alive and free. Success!
The **antagonist** has failed!

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
seems weird

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
have traitor round?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

successfull traitors all showed as traitors

traitor-vamp round

**Comment by Kyep** [comment]
@AffectedArc07 Haven't seen this in years, should be safe to close.
