### ISSUE TITLE
Special charecters in unconscious text are cleaned

### ISSUE THREAD

**Issue by MarcellusPye** [ParadiseSS13/Paradise#7613]
**Problem Description**:
strip_html_properly calls sanitize before returning. sanitize calls html_encode converting charecters like " to &quot;

**What did you expect to happen**: 
Not to hear &quot;

**What happened instead**:
&quot; was included in an unconsciousness message.

**Why is this bad/What are the consequences:**
It's immersion breaking.

**Steps to reproduce the problem**:
Be unconscious, hear html reserved charecters.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This is after I added strip_html_properly to the unconscious string selecter.

@Fox-McCloud Ironically this was not the issue I was thinking of.

**Comment by Spaghetti-bit** [comment]
No longer an issue. Spent plenty of time unconscious and this has not arised within the past year.
