### ISSUE TITLE
Player Panel Permission Error.

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7635]
**Problem Description**:
When I open a player of someone, it opens like normal, but also spews: 

> Error: You do not have sufficient rights to do that. You require one of the following flags: +EVENT.

**What did you expect to happen**: 
Should open like normal and no error message.

**What happened instead**:
Got an error message that does not have any other effect.

**Why is this bad/What are the consequences:**
Further, unneeded logspam.

**Steps to reproduce the problem**:
Don't have the +EVENT flag, open a PP.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I would figure it's checking for the Bless/Smite, which would need +EVENT, and is reachable from the player panel.

**Comment by SamHPurp** [comment]
@Kyep think this is part of what you changed?

**Comment by tigercat2000** [comment]
Someone forgot the optional silencing arguments for check_rights, probably.
