### ISSUE TITLE
Cultists can use teleport talisman while stunned

### ISSUE THREAD

**Issue by imsxz** [ParadiseSS13/Paradise#7636]
**Problem Description**:
As a cultist, I can run around with a teleport talisman primed ready to teleport, even when stunned.

**What did you expect to happen**: 
I expected to not be able to teleport while tazed, while not holding the teleport talisman.

**What happened instead**:
I was able to cheese the fuck out of security by teleporting when tazed.

**Why is this bad/What are the consequences:**
This is an EXTREMELY abuse-able cheese that is very unhealthy to the game, and seems like an unintended interaction.

**Steps to reproduce the problem**:
Make a teleport rune, make teleport talisman, use it in hand, put it in pocket. Select your teleport destination whenever you feel like it, don't know if it works while restrained/asleep but it works while stunned.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not sure if it works while sleeping/dead/cuffed, but it definitely works while stunned.

**Comment by KasparoVy** [comment]
😱

**Comment by Twinmold93** [comment]
Just needs a check that the paper is in active hand, not stunned, and not cuffed.

**Comment by Birdtalon** [comment]
@Crazylemon64 this was fixed in #8166
