### ISSUE TITLE
Space heartworms can eat through a mechanical heart

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7641]
**Problem Description**:
If someone has the space heartworms reagent in them while having a mechanical heart, the heartworms will somehow destroy the metal heart as though it was a regular one.

**What did you expect to happen**: 
For a mechanical heart to be impervious to the effects of heartworm burrowing.

**What happened instead**:
Somehow, the heartworms were capable of destroying a mechanical heart.

**Why is this bad/What are the consequences:**
Worms lack the strength or other means (such as acid) to destroy a mechanical heart, and therefore should have no effect on someone with a mechanical heart.

**Steps to reproduce the problem**:
Make a character with a mechanical heart, put Space Heartworms into them, watch and take notes as they perish, preferably with a coldly calculating gaze.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I conducted this experiment on a private testing server, 50u of Space Heartworms were added to the subject using the Player Panel, and I am well aware how little of an impact this has on actual gameplay.

**Comment by Aurorablade** [comment]
I was not aware heartworm was a thing where on our code is it as I cannot find it

**Comment by karmapay2win** [comment]
"heartworms" with an S

https://github.com/ParadiseSS13/Paradise/blob/e1ea5646428be7074444dae8c707b2666f172a73/code/modules/reagents/chemistry/reagents/disease.dm

**Comment by Fox-McCloud** [comment]
This is a balance/feature request more than anything else.

These are space heartworms--not regular heartworms!
