### ISSUE TITLE
fastmos issues

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7648]
**Problem Description**:
What is the problem?
got to crit form full health cause of fastmos,items launched into me at high velocity

**What did you expect to happen**: 
Why do you think this is a bug?
insta crit not fun

**What happened instead**:
How is what happened different from what you expected?
i expected normal when firedoor opened

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
inta crit is not fun

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
have tile with a lot of items under pressure --> open a hole to that tile --> go in crit maybe die cause i weared armour

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

fastmos!!!

**Comment by MarcellusPye** [comment]
Fire doors exist for a reason.

**Comment by granodd** [comment]
Fastmos is supposed to be dangerous, though there are certain ways around some of its dangers. Though one thing I've noticed is that if you don't have mag boots, you're fucked; if you do have mag boots, you're fucked as well seeing as items that get thrown around by fastmos can't go through you if you're not prone, which mag boots disallow. Therefore, the item will slam into 50,000 times, which is kind of detrimental, for example, if you were a nukie with magboots who gets shot into hard crit from full health by a _light tube_. Thankfully adrenals helped prevent my round from being over there, though others likely don't have the same relief.

The issue more so here is the fact that fastmos likes to slam items into you multiple times if you're not prone, which you can't be when you're wearing the boots that you need for fastmos. Less so the fact that you shouldn't be opening firelocks on fastmos...

**Comment by scrubmcnoob** [comment]
This is not a bug. This is an intentional feature of fastmos.
Space is dangerous, heed firelocks with caution.

**Comment by alexkar598** [comment]
the thing is that there is no counter if you need to rescue somebody as even if you have magboots the items(20-50) will hit at high velocity

**Comment by MarcellusPye** [comment]
This is SS13, there's allways a counter. The door is blocked by debris? Go around, destroy a wall. And secondly if 30 shards of glass where lauched at me with 100kPa behind them I woulden't be walking away either.

**Comment by alexkar598** [comment]
Have you seen only once one click that makes 100+ damage in less than 10 seconds?

**Comment by MarcellusPye** [comment]
Toxins, plasma fires, meat spike, admin rifle, landing shuttle, empress terror spider... there are lots.

**Comment by alexkar598** [comment]
Making this only need a couple of thing including air pump air tank and glass.

Toxins can't do 100+ damage that fast

Plasma fire is hard to do if you don't have the right job

Meat spikes never seen them

Admin rifle well admin only

Landing shuttle has a big warning time

Empress terror spider you won't be able to see that every round

**Comment by taukausanake** [comment]
The real issue here is that we don't have ZAS.

Maybe make it so items have a chance of passing through you after they hit? How possible would that be?

**Comment by Vivalas** [comment]
If this is not a meme issue then this reaction is known by the clinical community as *hugbox withdrawal*.

One does not simply create insane pressure gradients without getting pelted by a million objects at once. Welcome to the wonderful world of breaches being somewhat dangerous.

**Comment by MarcellusPye** [comment]
By toxins I mean toxins bombs, also chefs special sauce, Her Grace, advanced chem mixes, emping IPCs, need I continue? ^also what he said

**Comment by Rumiluntti** [comment]
Wait, you opened a firelock that is flashing with red lights and warns you not to open it, then you got assblast-obliterated by the outcome?
And this is somehow a bug now?
Don't think it's a bug at all but I hope you learned something

**Comment by alexkar598** [comment]
actually i did not open it

**Comment by Kyep** [comment]
@Allfd

**Comment by Allfd** [comment]
This was from 6 months ago @Kyep 

A few PRs are open to address some of these.

#8386 addresses the object death blender under certain conditions.
#8454 removes all stunning associated with fastmos (It is waiting on a fix to throw code)
#8451 covers an issue where the large scrubbers could suck you into them under certain conditions.

**Comment by Crazylemon64** [comment]
Not a bug, but the mechanic is undergoing several rebalance PRs
