### ISSUE TITLE
Unique IPC Head Sprites No Longer Working

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#7649]
**Problem Description**:
When you select one of the "Company" heads that is not the normal "human-looking" head (for instance, the monitors or the distinctly robotic, though not monitor head), and load in, you will instead have the sprite of your head be that of the human-appearing head model.

**What did you expect to happen**: 
I expected to load in with the head sprite that I had as opposed to the human-appearing model.

**What happened instead**:
I was given the human head instead.

**Why is this bad/What are the consequences:**
Sprites that IPC players can select are effectively "disabled" as they just default to the human-appearing head. IPC players who had certain customization in place will also notice that their customization options are no longer working.

**Steps to reproduce the problem**:
• Go to create an IPC character
• Select one of the company brand heads that is not the third option, nor is it Zheng Hu Pharmaceutical
• Load into the game
• Observe as you do not have the head that you had originally selected in creation 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Here are some screenshots that I took while investigating what the issue was. The Before portion of the images was of the private test server I was running before #7595 got merged in (which I believe may be what's causing the issue here, if not something else that was recently merged). The after is the up to date  private test server I have.

All IPC prosthetic options:
![image](https://user-images.githubusercontent.com/22057974/27618375-0aea7206-5b8a-11e7-992d-fc4789c2f023.png)

A more personal example:
![image](https://user-images.githubusercontent.com/22057974/27618381-15142f1a-5b8a-11e7-9ba9-430042c562b2.png)

I originally noticed that something was off while playing Serenity, as her face was more protruded and flat, as opposed to what it usually is. My suspicions were confirmed that there was something amiss when I played Jeriko, and saw what is presented here. It wasn't until I went and compared the current test server to an older one that I found what the issue was.

**Comment by Fox-McCloud** [comment]
I can't replicate this locally; any other IPC players that have this issue? 

I'm still able to have the correct head type.

**Comment by granodd** [comment]
@Fox-McCloud You went and created an IPC, selected a head (for instance one of the company monitors) and was able to load into the game with it displaying as that head type and not the other head types (the company normal and not the alt./mtr.)?

I ask because I am still able to recreate this issue on the live server. I will have to ask other players to test this as well, but there's got to be something here that's causing it.

**Comment by shazbot194** [comment]
I wonder if it has I do with #7595 and more specifically this little bit of code;
https://github.com/Fox-McCloud/Paradise-1/blob/f1746e011eede64ef040243020a34c3aa2f51382/code/modules/surgery/organs/robolimbs.dm

**Comment by TravellingMerchant** [comment]
Yep, its definitely a problem in live. Scrubmcnoob helped me out in testing. @Fox-McCloud 

![](https://puu.sh/wwAWH.png)

![](https://puu.sh/wwB48.png)

It seems to be spawning in the IPC with the "standard" of each manufacturing company.

**Comment by granodd** [comment]
So I went ahead and commented out line 15 and line 16 of the code and the heads worked just fine afterwards. The only issue that still remains is that it seems that the code is forcing the head to match the torso. The unbranded heads are still in the game, but seeing as I use a Ward-Takahshi chest for Serenity with an unbranded head, it forces it to be a Ward-Takahashi. I confirmed that this was the case when I changed her chest to be unbranded, at which point her head was the correct one. Which line of code is causing this, I do not know.

**Comment by KasparoVy** [comment]
It was a PITA to get this to work the first time around.

**Comment by granodd** [comment]
#7659 Fixes this, so closing this.

**Comment by Fox-McCloud** [comment]
Lemme know if it's *actually* fixed.
