### ISSUE TITLE
Shocked doors spark when items are thrown through them

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7654]
**Problem Description**:
Shocked doors spark when items are thrown through them

**What did you expect to happen**: 
No sparks

**What happened instead**:
Sparks

**Why is this bad/What are the consequences:**
Odd, shouldn't happen.

**Steps to reproduce the problem**:
shock and bolt open a door. throw an item through. This doesn't work for all items. Flashlights, penlights, RCDs do.. Blueprints, telebatons do not.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Nothing out of the ordinary. Assume this is to do with movement refactor?

**Comment by tigercat2000** [comment]
Sparks are always annoying in the code- did you know that hitting a borg with _anything_ can cause sparks?

**Comment by SamHPurp** [comment]
@tigercat2000 I haven't looked into it, but it was interesting that it was consistent with specific items NOT causing sparks.

**Comment by Citinited** [comment]
This is fixed, adding to next PR
