### ISSUE TITLE
CE's jumpsuit has the wrong in-hand icon.

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7655]
**Problem Description**:
CE's jumpsuit has the wrong in-hand icon.

**What did you expect to happen**: 
The same item to be in my hand as on the floor/inv etc.

**What happened instead**:
Got a green jumpsuit in my hand. 
![image](https://user-images.githubusercontent.com/7415122/27631381-38065bd6-5bf0-11e7-966a-f65379263a3a.png)

**Why is this bad/What are the consequences:**
Inconsistent

**Steps to reproduce the problem**:
hold CE jumpsuit.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I was Plasmeme CE, spawning with CE jumpskirt, which auto-drops the jumpsuit. I picked up jumpsuit, noticed the problem.

**Comment by Twinmold93** [comment]
I know why. Apparently when I was fixing some of the jumpskirt sprites, I never noticed the in-hand icon was incorrect. Could be just a missing hand sprite. Shouldn't be too hard to rectify.
