### ISSUE TITLE
Some Organ Code bugs

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#766]
@ZomgPonies 

Going from human to monkey drops everything, and I mean EVERYTHING, on the floor underneath them. Kinda hilarious to see a Ling drop a whole buncha organs while running but still a problem.

Going from Monkey to human appearently causes MASSIVE brute damage to the point it literally explodes the now corpse into a sea of blood.

Sometimes corpses keep their features still on the sprite but also have them scattered on the ground. We had one corpse make two heads this way.

**Comment by ZomgPonies** [comment]
This'll be fixed once I port monkeys to the species system. Shouldn't be long.

**Comment by ZomgPonies** [comment]
Fixed via monkey port.
