### ISSUE TITLE
NPC terror spiders have bad nightvision.

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#7660]
**Problem Description**:
Right. So some people were in the gateway(I was watching as a spooky ghost.) and they noticed that the terror spiders were standing there without attacking. Apparently NPC Terror spooders don't attack if it's dark because they don't see you.

**What did you expect to happen**: 
For those people to get mauled when they tripped into terror webs like morons, surrounded by a bunch of red spiders.

**What happened instead**:
They beat the unresponsive spiders to death with bats.

**Why is this bad/What are the consequences:**
Cheesing Terror Spooders is bad.

**Steps to reproduce the problem**:
Spawn terror spiders. Smash the lights. Watch as your docile maneating spiders do not respond.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nope.

**Comment by Kyep** [comment]
Technically, Terror Spiders are _meant_ to always have thermal vision, like changelings. 

That said... there are issues with giving NPC spiders thermal vision. Given that some of them can smash walls, giving them this would potentially enable them to see you, from the next room, and _smash through the wall_ to path towards you. 

They definitely should have nightvision, though. I'll fix that. Not sure if I will give them the full thermal vision they're meant to have, though.

**Comment by KingPhilipIII** [comment]
Well. They're NPCs. It's not like anyone will ever notice if they don't have thermals like they should. As long as playable terror spooders do, I don't see an issue with an inconsistancy like that for the sake of gameplay. And they did at one point have thermals I think. I remember several instances of the purple terror spider in front of the bridge smashing it's way out to greet us. Maybe something else triggered it but meh.

**Comment by Kyep** [comment]
I tested this. NPC TS do appear to have nightvision.

**Comment by KingPhilipIII** [comment]
Oh really? Then I wonder what was wrong with them. Something wasn't working right in any case, but I guess this wasn't it.

Shut it down I guess.
