### ISSUE TITLE
Decreasing a turret's shot_delay will not speed up its firing rate, while increasing shot_delay will

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#7667]
**Problem Description**:
Modifying a turret's `shot_delay` to below 15 does not speed up the turret firing speed. However, raising it to above 15 works as intended.

EDIT: after some more testing it seems that the turret actually fires once every 2 seconds (not 1.5 seconds, like `shot_delay = 15` would imply). This is pretty weird...

**What did you expect to happen**: 
I expected the turret to fire more quickly if I modified its `shot_delay` to below 15

**What happened instead**:
Instead the turret appeared to be capped to firing to once every 1.5 seconds

**Why is this bad/What are the consequences:**
This is inconsistent behaviour and reduces options if you were to add new turrets in future.

**Steps to reproduce the problem**:
1. VV a turret's `shot_delay` to a small number.
2. Watch turret not fire quickly.
3. VV a turret's `shot_delay` to something big.
4. Watch turret fire extremely slowly.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I tried to fix it but nothing in the turret file seemed to fix this, so I suspect the fix to the problem lies elsewhere. (Maybe something else limits their firing?)

**Comment by Crazylemon64** [comment]
You'll need to call `makeSpeedProcess` if you want it to process faster than every 2 seconds
