### ISSUE TITLE
Broken Rainbow Crayon Color Change

### ISSUE THREAD

**Issue by Kirbyroth** [ParadiseSS13/Paradise#7676]
**Problem Description**:
What is the problem?

The rainbow crayon wont change colors it stuck on yellow. Even after selecting a diff color it still stays on yellow.

**What did you expect to happen**:  For it to change to the color I selected.

**Why do you think this is a bug?**

It supposed to be able to change to diff colors.

**What happened instead**:  When selecting a diff color in the menu it stays on yellow

How is what happened different from what you expected?

It should change to the color selected like it supposed to. 

**Why is this bad/What are the consequences:**  Stuck with only yellow force to use normal crayons.

Why do you think this is an important issue?
Clowns need more colors. 

**Steps to reproduce the problem**: Get a rainbow crayon attempt to change it colors in color palette menu after using the crayon in your hand. After selecting any color the color box stays yellow and drawing anything get drawn in yellow still.

The most important section. Review everything you did leading up to causing the issue.
Walked around station for awhile. Lent the rainbow crayon to barber but he couldn't
get it to change colors so I tried and didn't work for me either.

**Possibly related stuff (which gamemode was it? cult What were you doing at the time? trying to change crayon color. Was anything else out of the ordinary happening?)**: Anything else you can tell us. nope just the rainbow crayon not changing colors.

**Comment by Citinited** [comment]
Amusingly, if you drop the crayon while picking a colour, it will change fine 😄. I'll be fixing this

**Comment by ktoma36** [comment]
I think this is also the same with the mimes crayon
