### ISSUE TITLE
Sulfuric Acid is still harmful to grey even after rework

### ISSUE THREAD

**Issue by SplinterGP** [ParadiseSS13/Paradise#7685]
**Problem Description**:
Simply, even after grey rework sulfuric acid is still harmful to greys

**What did you expect to happen**: 
Sulfuric acid being non-harmful to grey

**What happened instead**:
Sulfuric acid still being harmful to grey as it was before the rework

**Comment by Fox-McCloud** [comment]
@fludd12

**Comment by fludd12** [comment]
friiiiiick
