### ISSUE TITLE
Bottler Units break after one use

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#7686]
**Problem Description**:
Bottler units appear to only be usable one time.

**What did you expect to happen**: 
You put the ingredients in, tell it to process, it makes your drink, and then it goes back to being ready to accept more ingredients.

**What happened instead**:
When you tell it to process it will show a screen saying processing is in progress, and it will dispense the drink after a few seconds. It appears to hang on that screen though, and if you close the window you can't reopen it, and also can't put more ingredients in the unit. You can still recycle bottles and cans though.

**Why is this bad/What are the consequences:**
It costs 35 cargo points to even get a bottler unit, so I should expect more than a single drink from one.

**Steps to reproduce the problem**:
Order or spawn a bottler unit, then follow any of the valid recipes for it.

**Comment by Jountax** [comment]
I'm not sure, but I think it might also be using the sprite for paradise punch no matter what recipe you use. This is a guess though, based only on the fact that bottles and cans have two P's printed on them, as I have never used a unit before whatever broke them broke them.

**Comment by FalseIncarnate** [comment]
I'll have to look into the base issue reported, but I can tell you without investigation that the sprite is correct and not an issue.

The Double P logo is actually for Paradise Pop, which is the "brand" of drinks the machine creates. The reagents only dictate the name and description of the bottle, as well as the filling color (just like other reagents). The bottle (or can) sprite itself is static.

**Comment by Jountax** [comment]
I tried with both apple-pocalypse and berry banned (the non poison kind) and both times the machine froze,

**Comment by StreakyHaddock** [comment]
This is still a thing.

**Comment by Birdtalon** [comment]
poptar4551 - Today at 10:01 AM
I put in three apples, then processed it into a metal can(mind you this happened before except i bottled it into a plastic bottle I believe) and then it occured.

Another user encountered this error.
