### ISSUE TITLE
The Chapel has been defiled and is no longer a holy place. (Vampire related)

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#7692]
**Problem Description**:
Right. As a vampire I walked through the chapel, forgetting I was supposed to burst into flames upon entry, but nothing happened. I walked through completely unharmed and proceeded to scurry into maintanence before my luck ran out and I did ignite.

This isn't the first time this has happened either, just the first time I acutely noticed.

**What did you expect to happen**: 
Crispy vampires.

**What happened instead**:
Rather undercooked and still alive vampires.

**Why is this bad/What are the consequences:**
Well. If you say vampires are supposed to burn in the chapel, they should. I mean, it's not like the chapel ever really can be used, since it's considered against SoP to toast vampires as a means of execution. I guess now you can't run in there either to escape one, but I doubt it sees much use as a safehaven anyway.

**Steps to reproduce the problem**:
Be vampire. Walk into chapel. Survive.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nope,

**Comment by Fox-McCloud** [comment]
It takes time for this to happen, now; it's no longer a "on chapel->on fire" thing; you have to stay in it for a while now; just passing through isn't a death sentence anymore.

**Comment by Aurorablade** [comment]
Theres a delay to it and it dosen't affect full powered.

**Comment by KingPhilipIII** [comment]
Huh. Guess I missed that changelog at some point. No further complaint then.
