### ISSUE TITLE
Runtime in Spacevine.dm - 306

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7695]
```
[16:10:05] Runtime in code/modules/events/spacevine.dm,306: DEBUG: to_chat called with invalid message/target.
  Message: 'You cut yourself on the thorny vines.'
  Target: ''
  src: thorny (/datum/spacevine_mutation/thorns)
```

On a test server, but nothing out of the ordinary happened that may have influenced this.

**Comment by moxian** [comment]
HOW?
https://github.com/ParadiseSS13/Paradise/blob/f7c76befff2432f41bc2c9b7726cb0f59b053b1e/code/modules/events/spacevine.dm#L302-L306

There's an `istype` check right there!
Can we blame this on old byond not handling types in argument somehow, and needing an *extra* `istype(M)` after the "true" typed `var/mob/living/M` is created??

**Comment by hal9000PR** [comment]
Likely an old byond bug
