### ISSUE TITLE
Cult structures cannot be deconstructed

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7699]
**Problem Description**:
Cult structures cannot be deconstructed.

**What did you expect to happen**: 
I expected there to be a way to remove them, even if it could only be done by the chaplain.

**What happened instead**:
Briefly looking over the code, I didn't see any deconstruction code that the crew could use.

**Why is this bad/What are the consequences:**
While destroying runes is simple enough, destroying the cult structures should be possible as well.

**Steps to reproduce the problem**:
Create a daemon forge. Try all sorts of ways to remove the structure.

**Comment by alexkar598** [comment]
Bomb?

**Comment by Anticept** [comment]
Edited, should say deconstruct. You shouldn't be bombing as a non antag.

**Comment by Birdtalon** [comment]
It seems to me like they were created with the intention of being vulnerable as they have health variables but they don't seem to take damage. I tested this with a variety of weapons and structures and the only way of destroying them seems to be explosives.

**Comment by Anticept** [comment]
TGstation has a damage system. It's being ported slowly, but I bet that's what the health vars are for.
