### ISSUE TITLE
Having two sleeper UI open causes weird issues

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7705]
**Problem Description**:
What is the problem?
If you open 2 sleeper UI at the same time the buttons will only interact with the first UI opened 
**What did you expect to happen**: 
Why do you think this is a bug?
No explainarion required
**What happened instead**:
How is what happened different from what you expected?
I expected buttons to work properly
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Not being able to use a medical machine Is pretty bad
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Find 2 sleepers you can interact with both at The same time(shuttle med bay)-->open both UI-->watch as click buttons in the second sleeper will interact with first one
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Not the first time it happened but always happened on the shuttle but I did not test in normal station

**Comment by pinatacolada** [comment]
Happens on station too, and worst than that, it can completely break them, first thing that happens is that the health bars stop smoothing values, and instead jump from like 20 styptic to 10 styptic for example, then the window stops updating altogether and you need to close it or click the sleeper again. But when the window opens again, the problems persist. Ive also had happen clicking on sleeper A, and opening a window for sleeper B, but it doesnt always happen

**Comment by alexkar598** [comment]
The only solution I know of is opening both sleepers an go out of UI range

**Comment by AffectedArc07** [comment]
Assume this got fixed when we migrated to TGUI, and was unreproducable before that. Closing.
