### ISSUE TITLE
Respawing into the round.

### ISSUE THREAD

**Issue by ViaticThrone** [ParadiseSS13/Paradise#7713]
**Problem Description**:
I got my posibrain removed by an antag as a IPC was able to respawn into the round as if I missed round start. So there was two of my characters in the round but with different jobs.

**What did you expect to happen**: 
I expected to rejoin the round as my posibrain

**What happened instead**:
Well I joined the round as the a person with a different job

**Why is this bad/What are the consequences:**
This is bad because it can be used to metagame and so all sorts of bad stuff

**Steps to reproduce the problem**:
I don't know how to reproduce it but I can say what I did leading up to the event. So I was emped by a vampire as they needed to steal my brain so they de-brained and because I was a IPC I can talk to them while they hold my posibrain, so I did just that but then I got the red notification in my chatbox saying I have lost connection to the server so I pressed the reconnect button in the top left corner and it took me the lobby screen and from there I could join the match as if I was late.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a vampire round, I was getting bad ping at the time, I was the RD and a IPC.

**Comment by Miraviel** [comment]
Could not reproduce this, it was probably fixed sometime.
