### ISSUE TITLE
Immovable Computer Windows

### ISSUE THREAD

**Issue by Beardbeardd** [ParadiseSS13/Paradise#7719]
**Problem Description**:
When using computers or handheld crew monitors, the window that opens has the top portion cut off, making it immovable and forcing you to use Alt F4 to close it. Because these windows use the new style with no edges, you can't simply double click to recenter them.

**What did you expect to happen**: 
I expected to be able to move the computer window.

**What happened instead**:
I could not move the computer window.

**Why is this bad/What are the consequences:**
It makes computers unusable.

**Steps to reproduce the problem**:
Use a computer or handheld crew monitor that uses the new window style. If it helps I'm playing on a 1366x768 monitor.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
That's about it.

**Comment by Citinited** [comment]
Disabling fancy NanoUI should fix your problem

**Comment by tigercat2000** [comment]
Define "the top portion cut off". Are the browser-based buttons cut off, or is the border disabled? The latter is intentional, the former is not.

**Comment by Beardbeardd** [comment]
I mean the part you have to click on to move the window around, and also to close or minimize it.

**Comment by taukausanake** [comment]
Did you try clicking on the very top of the window that was open and drag it around? NanoUI does have a border believe it or not, it's just a bit weird to use

**Comment by Beardbeardd** [comment]
I clicked on the top of what was available to me, but that's just part of the main window so it does nothing.

**Comment by Crazylemon64** [comment]
There's like 12 of these issues so i'm closing this one. not sure how to fix besides not making the borderless UI the default
