### ISSUE TITLE
Virology mechanics

### ISSUE THREAD

**Issue by Picard25** [ParadiseSS13/Paradise#7723]
**Problem Description**:
When mixing plasma dust and Virus food an issue arises where the two combinations will not combine, Leaving them both inside the beaker and when a virus is applied, Only 1 of them will disappear.

**What did you expect to happen**: 
I expect them to mix together properly.

**What happened instead**:
Most of the time it mixes, But when the first "Dud" mixture happens it becomes more frequent.

**Why is this bad/What are the consequences:**
Delaying an already tedious progress of getting the right symptoms

**Steps to reproduce the problem**:
You need only a beaker, plasma dust, and virus food, Putting them in the beaker with the pippete 1 unit a piece.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Happens most of my play throughs as Virologist.

**Comment by farie82** [comment]
Problem lies with the virus food. After 5 pippete drains the virus food will not react with anything. It might be a float error or something.
