### ISSUE TITLE
Box's vacant office is missing a firelock on its entrance

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#7732]
**Problem Description**:
^

**What did you expect to happen**: 
All rooms should have firelocks leading into them

**What happened instead**:
Firelock is missing

**Why is this bad/What are the consequences:**
Inconsistent

**Steps to reproduce the problem**:
1. Join boxstation
2. Observe lack of firelock

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
This is on boxstation

**Comment by SamHPurp** [comment]
Dunno if I'd say its necessarily an issue, there are loads of places that lack firedoors.

But I don't see a reason not to have it, fine either way.
