### ISSUE TITLE
The howl emote is WAY too loud

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#7733]
**Problem Description**:
The howl emote is way too loud compared to other sounds, it should be lowered

**Comment by Fox-McCloud** [comment]
1. Features Request

2. It's really really not:

Here's howl: 
![img](https://i.gyazo.com/9487c5f66a2acb98ddf8040f4ddec5fa.png)

Here's the male scream:
![img2](https://i.gyazo.com/6b283e6ddf09efd45c830961016a1fa3.png)

Here's the female scream:
![img3](https://i.gyazo.com/98ca5a0706ae5c185520c58fc9376d05.png)

**Comment by Allfd** [comment]
Closed, however before I ported, I made sure to level the amplitude with all other emotes.
