### ISSUE TITLE
Vox vulernable to EMP

### ISSUE THREAD

**Issue by Anasari** [ParadiseSS13/Paradise#7736]
**Problem Description**:
Vox are vulnerable to dying from cortical stack damage

**What did you expect to happen**: 
Vox to be able to use EMP implants/disabletech without endangering themselves

**What happened instead**:
Vox dies from cortical stack damage from EMP, 3 direct hit with an ion rifle (Heavy pulse) or 4 indirect hit (light pulse) will kills them

**Why is this bad/What are the consequences:**
Unintentionally nerf vox and make them unable to use emp implant safely. 

**Steps to reproduce the problem**:
1. Get vox
2. Shoot with ion rifle thrice directly / four time next to them
3. Vox dies

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: An (unintended?) result of organ-induced death being fixed.

**Comment by Fox-McCloud** [comment]
Working as intended ™️

**Comment by GunDOSMk1** [comment]
Yes, I believe this is intentional as @Fox-McCloud said. Cortical stacks are mechanical organs and thus are damaged via EMP's. it's one of there drawbacks I think.

**Comment by DarkPyrolord** [comment]
I'm going to say one thing here... IPSkree.
_That joke was horrible, end me now._

**Comment by Rumiluntti** [comment]
It's an unintentional drawback that has not been discussed or mentioned anywhere.
Also known as oversight

**Comment by DesolateG** [comment]
How much damage does an emp flashlight do to them?

**Comment by scrubmcnoob** [comment]
No different from other species having mechanical parts on or in them.

**Comment by FlattestGuitar** [comment]
Well, it's not a bug, but a piece of code that nobody knew about. I can imagine thanks to this issue report people might actually start using EMP against Vox.

**Comment by tigercat2000** [comment]
This is technically intentional behavior, but no one really realized it would happen.... I'll leave this open, but we'll have to see how it works out in practice.

**Comment by SirBloodBuske** [comment]
Working as intended

**Comment by Robertha89** [comment]
This is a bug that was fixed before, I even reported it, and it got fixed.

**Comment by Ralta** [comment]
Bug? The lore states clearly that the cortical stack is an implant; it should be pretty obvious that it'd take damage from EMP. This mechanic was added to the Wiki on 28/06/17, so granted it's a reasonably recent addition to the Wiki, but from a mechanics perspective, it just makes good sense. I main Vox, and I'm fine with the EMP damage.

**Comment by taukausanake** [comment]
I highly doubt the Vox would make some mechanics and implant themselves with said mechanics if they knew it would kill them by being EMP-ed. I would imagine it being resistant to EMPs because it is their brain after all. Technology advanced, put some shielding on that.

Why don't IPC brains explode to EMPs? Are they a different kind of mechanical?

**Comment by Robertha89** [comment]
Lore also states that it is bluespace tech, and bluespace tech is not susceptable to emp in anyway, neither is any other implant, except for the two explosive implants.  
It also explains a few mysterious deaths.
To re-state something I have said many a times, EMP's are powerfull, like wowzer, its one if not the outright strongest mechanic in the game available to players, IPC's are susceptable to EMP's, but in return, they are almost impossible to permakill, their brains never expire, their easy to repair, and so on.
