### ISSUE TITLE
[HONKBREAKING] Honk Squad members cannot understand or speak clownish

### ISSUE THREAD

**Issue by r3valkyrie** [ParadiseSS13/Paradise#7737]
**Problem Description**:
Honk Squad members cannot understand or speak clownish.

**What did you expect to happen**: 
The Honk Squad members, being the elite clown beings they are, should be able to speak and understand clownish.

**What happened instead**:
Many honks, zubs, wuffs, baps, and other clowny noises.

**Why is this bad/What are the consequences:**
If the Honk Squad fails to speak clownish, it proves that they are not, in fact, real clowns. This means the crew is 100% more likely to murder you (based on a scientific study by Solgov University).

**Steps to reproduce the problem**:
1. Be spawned in as Honk Squad.
2. Attempt to speak or understand Clownish.
3. Fail to speak or understand Clownish.
4. Get lynched by the crew for not being a real clown.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
N/A

**Comment by tigercat2000** [comment]
Not a bug, this is a feature request.

**Comment by alexkar598** [comment]
@tigercat2000 honk mother will be mad at you.
