### ISSUE TITLE
ERT does not function properly

### ISSUE THREAD

**Issue by Anasari** [ParadiseSS13/Paradise#7738]
**Problem Description**:
ERT does not give a message when sent, when people click yes on ERT, some of them do not spawn in, or only spawn in many many minutes later.

**What did you expect to happen**: 
A message to be given out and ERT filled up

**What happened instead**:
See description

**Why is this bad/What are the consequences:**
Muh ERT is broken

**Steps to reproduce the problem**:
1. Respond to an ERT / Dispatch ERT
2. Click yes
3. Sometime only 1 - 2 ERT will spawn, despite way over that amount of ghosts volunteering.
4. Sometime the message is not shown at all, resulting in ERT being sent and the crew not knowing. The message often show with a very large delay. This seems to mean that ERT spawn in late for some reason.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Seems to be consistent regardless of gamemode

**Comment by FlattestGuitar** [comment]
All ERT members spawn in order. Person 1 picks their gender and role and spawns in, only after that happens does Person 2 get the query. If one of the people who signed up for an ERT either leaves or just goes afk with the prompt on their screen they will hold everything up. The game doesn't really have any way to handle that, but the system is needed if we want to enforce limits on certain roles - 1 Commander, not more than 3 Sec, Engi or Med ERT members and so on...

We could probably add a timer that checks if people went afk somewhere in there...
