### ISSUE TITLE
Getting blob infection after roundstart doesn't give you 5 minutes to prepare

### ISSUE THREAD

**Issue by Alriac** [ParadiseSS13/Paradise#7746]
**Problem Description**:
What is the problem?
If you get the blob infection 3 or 4 minutes after the round started, you will explode at 12:05 anyways.

**What did you expect to happen**: 
Why do you think this is a bug?
I think you should have 5 minutes from the time you got the antagonist role, not from round start.

**What happened instead**:
How is what happened different from what you expected?
I got the blob infection message at 12:03 and exploded two minutes later.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
You don't have time to prepare at all, you will probably explode in a hallway.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I have no idea what happened. Maybe there was already a blob player but he disconnected and the antag role jumped to me?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It happened about 50 minutes before posting this issue.

**Comment by Taaketa** [comment]
I don't think this is a bug. Blob players before they burst aren't really meantto have prep time. After all it isn't your character that will be a Blob but the hostile orgasim that has been feeding on your body.

**Comment by Alriac** [comment]
In that case, shouldn't every crewmember that got infected warn everybody over comms and get somewhere where the blob can be easily exterminated? The wiki advice it to find a good place and even hack the cameras.

Anyway, I was talking a about a code bug, not gameplay design. I have played as blob 3 times and the first two I got the message at roundstart and brusted after 5 minutes approx, so I thought there must be something wrong with the code.

**Comment by taukausanake** [comment]
Yeah this sounds like an issue. When you find out you are a blob carrier then you are automatically an antag and need to prepare as one. It's your job to make the round fun and challenging for everyone else. Two minutes of prep time when you should have five is a problem. You don't want to burst in the middle of the hall and start having tide smash away at you with toolboxes. Might as well be a lone wizard then, ten minute long round inbound

**Comment by SamHPurp** [comment]
I tried repeatedly and failed to reproduce this... with how the spawns and sleeps work, I don't see how this is happening? It seems to be tied to the blob in particular, not the gamemode? 🤔 

Perhaps a recent change fixed this?

**Comment by Shadow-Quill** [comment]
@Anasari looks like this is fixed.
