### ISSUE TITLE
More Organ/Surgery Bugs

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#775]
Few bugs that I noted recently with the organ code.
1. Limb stumps cannot be removed, meaning you can't attach heads back to bodies that have been beheaded.
2. Organs take a lot of damage upon being removed, meaning you can't transplant a brain from a dead person to a humanized monkey.
3. Implant removal surgery does not work, hemostat step after the saw > retractors steps does nothing.
4. ~~The fix-o-vein step of organ reattachment that is supposed to come after you shove the organ back in just attacks the person.~~ This is due to organ damage, nevermind.

@ZomgPonies

**Comment by Taaketa** [comment]
Add to this that IPCs cannot have their limbs replaced. No tools work on them to clear their limb. Any attempt at reattaching/cleaning the affect limb will result in a "Limb is missing"

**Comment by M3hillus** [comment]
Not only that, Robotic limbs seem to transform into normal limbs upon removal from the body.
