### ISSUE TITLE
Vox Flag missing in hand sprites

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#7752]
**Problem Description**:
Vox Flag has no sprites when held in the hand

**What did you expect to happen**: 
It to have a sprite for Vox flag

**What happened instead**:
No sprite!

**Why is this bad/What are the consequences:**
This is incredibly game breaking.

**Steps to reproduce the problem**:
Buy a Vox flag and hold it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Citinited** [comment]
Seems like an easy enough fix, I'll sort this one out
