### ISSUE TITLE
Coffee mesons bug

### ISSUE THREAD

**Issue by starberryshot** [ParadiseSS13/Paradise#7765]
**Problem Description**:
When you spawn in as Coffee and go into the vent it gives you this mesons-like vision and when I got out the vision lasted still

**What did you expect to happen**: 
uh, I dunno. Maybe because that's not how eyes work?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
I don't really think it's important but it's weird to have mesons as Coffee

**Steps to reproduce the problem**:
Nothing out of the ordinary, just went into the vent in chemistry and walked out the same vent I went into and boom, mesons on crab.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by Bigtimetripod** [comment]
I have had this happen with a mouse also.

**Comment by Citinited** [comment]
This happens with basically every mob that ventcrawls. I'm going to guess that when you leave the vent, the game doesn't disable the mesons flag

**Comment by taukausanake** [comment]
Maybe you should just get pipe vision when moving in pipes. I really don't think you should be able to see the world above if you are in an enclosed space like a pipe. Just give the max vision of all pipes while inside a pipe?
