### ISSUE TITLE
New blood system issue with transfusions

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7766]
**Problem Description**:
Blood transfusions with IV are not increasing patients blood levels. Had SEVERAL cases with this and had to use admin tools to rectify.

**What did you expect to happen**: 
Hooking up the IV should have increased their blood level.

**What happened instead**:
It went into their "container", which is no longer used in the new blood refactor.

**Why is this bad/What are the consequences:**
Makes some patients unrevivable.

**Steps to reproduce the problem**:
Remove some blood from someone. Hook them up to an IV. Notice their blood level isn't rising, but it is going into their container like a reagent.

**Comment by Fox-McCloud** [comment]
Not able to reproduce.

Blood does go into a mobs reagent container now (this is intentional), but the volume volume is being increased, whether they're dead or alive. Tested with syringes, IVs, and force drinking.

**Comment by Anticept** [comment]
I'll try to gather more info, but we had several ahelps with this problem.

@Fox-McCloud what if they are dead?

**Comment by Fox-McCloud** [comment]
@Anticept 

>whether they're dead or alive.

**Comment by Anticept** [comment]
Sorry, missed that. I've been up for almost a full day.

**Comment by Anticept** [comment]
Ansari just had this issue with a slime person. Injected 330u water, it would not work at all.

**Comment by Anticept** [comment]
@Fox-McCloud i did some first hand medical. Biggest issue is the fact that blood is reacting with cryox. This is extremely annoying on vamp rounds, because some people are both bled and robusted, so you end up doing a mix of blood and cryotubes.
