### ISSUE TITLE
the tesla can destroy the nuke

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7767]
**Problem Description**:
What is the problem?
the tesla can destroy the nuke
**What did you expect to happen**: 
Why do you think this is a bug?
cause its normally undestructible
**What happened instead**:
How is what happened different from what you expected?
it disapeered
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
ruins nukies
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
have a nice nuclear bomb
cry as the tesla takes your toy
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
tested on private server with both syndi and non syndi one

**Comment by tigercat2000** [comment]
This is definitely intentional looking at the code, but I'm not sure why- It makes references to a loop of neverending explosions.

**Comment by Twinmold93** [comment]
One could imagine it could overload the system and set off the Nike, maybe? Not necessarily a good idea for gameplay, however.

**Comment by alexkar598** [comment]
the Nike,huh?

**Comment by Twinmold93** [comment]
Damn phone's auto-correct bullshit.

**Comment by Fox-McCloud** [comment]
Yeah, not a bug

**Comment by taukausanake** [comment]
New meta: releasing the tesla/singularity to kill the nuke before it kills everyone. I would love to see that actually work

**Comment by alexkar598** [comment]
then the tesla would not be happy that it has been used for a good purpose so it proceed to kill everybody on station
