### ISSUE TITLE
Advanced Pinpointer points towards engineering Cyborgs 

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#7769]
**Problem Description**:
The Advanced Pinpointer points towards a cyborg when set to point towards the Station Blueprints.

**What did you expect to happen**: 
The pinpointer to point towards the real blueprints

**What happened instead**:
It pointed to a nearby engineering cyborg

**Why is this bad/What are the consequences:**
It's very confusing to try to find them with the pinpointer.

**Steps to reproduce the problem**:
Have an advanced pinpointer and an engineering cyborg nearby, I assume closer than the real blueprints. Set the pinpointer to locate the station blueprints.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Should be reproducible with the above information.

**Comment by FlattestGuitar** [comment]
Likely might also have an issue with RCDs or whatever else cyborgs have that might trigger it.

**Comment by SamHPurp** [comment]
Nah its #6177

**Comment by Agameofscones** [comment]
![AltText](https://media.giphy.com/media/fV2IbuksC6yW9hFHFW/giphy.gif)

Tested on latest version, the blueprints are called "Station Schematics" for borgs now, the pin pointer only points to station blueprints now. This issue can be closed. @Fox-McCloud

**Comment by Birdtalon** [comment]
👍
