### ISSUE TITLE
Runtime:Blood Tracks

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#7771]
[20:40:14] Runtime in tracks.dm,69: Cannot execute null.Copy().
   proc name: Uncrossed (/obj/effect/decal/cleanable/blood/footprints/Uncrossed)
   usr: (/mob/living/carbon/human)
   usr.loc: The floor (108,88,1) (/turf/simulated/floor/plasteel)
   src: the blood (/obj/effect/decal/cleanable/blood/footprints)
   src.loc: the floor (107,88,1) (/turf/simulated/floor/plasteel

**Comment by Fox-McCloud** [comment]
dna is somehow null, then.

**Comment by FunnyMan3595** [comment]
There's not enough information to reproduce this, and it's likely that it has been fixed sometime in the intervening years,
