### ISSUE TITLE
Vampire Runtime

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#7772]
[21:20:52] Runtime in water.dm,213: Cannot read null.vampire
   proc name: reaction mob (/datum/reagent/blood/reaction_mob)

**Comment by SteelSlayer** [comment]
Vampire code has been datumized and this proc has been refactored since. It's no longer dependant on doing things with `mind.vampire`.

![Code_8RP2tZS63k](https://user-images.githubusercontent.com/42044220/174498819-c5155e3a-0098-4f4d-8e18-b1de0bf68c2d.png)
