### ISSUE TITLE
Cable Layer thinks its an event

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#7773]
21:22:06] Runtime in event.dm,151: undefined variable /obj/item/mecha_parts/mecha_equipment/cable_layer/var/severity
   proc name: New (/datum/event/New)

**Comment by Fox-McCloud** [comment]
.......how.

**Comment by moonheart08** [comment]
we need to have a 'shitty code' label for these types of errors.

**Comment by SabreML** [comment]
Fixed by #14774.
