### ISSUE TITLE
BYOND Bug - Setting a gun cell to near-int-cap values causes the entire server to crash

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#7774]
**Problem Description**:
If you set a cell's charge hilariously high with view vars, then fire a weapon with it loaded, the server crashes

**What did you expect to happen**: 
Server shouldn't crash

**What happened instead**:
Server crashes

**Why is this bad/What are the consequences:**
Infinite cells are infeasible

**Comment by taukausanake** [comment]
Wait, so normal infinite cells don't work? Is the charge value being too high which kills DD? I'm guessing a check for the value isn't going to work because it has to be accessed and that's what is crashing the server

**Comment by matttheficus** [comment]
as per label, cannot/will not fix

**Comment by Spaghetti-bit** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/60483458/6979d2bd-bb00-478f-97e2-c305b99d64bb)
No longer an issue. Fired it No issues.
