### ISSUE TITLE
BYOND Bug - SDQL Sometimes produces links in SELECT queries that will crash the server

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#7775]
**Problem Description**:
SDQL will sometimes create links in SELECT queries that point to an object that doesn't exist, and, when attempting to use the view variables link, will crash Dream Daemon

**What did you expect to happen**: 
Server wouldn't crash from clicking a link

**What happened instead**:
Server crashed

**Why is this bad/What are the consequences:**
Admins can totally accidentally crash the server by not knowing the warning signs (no name, value is a weird significant hex string)

**Steps to reproduce the problem**:
No way to consistently reproduce it, it was just on the live server for using a `SELECT /client` query for a temporary period (probably between Dream Daemon process restarts).

**Comment by matttheficus** [comment]
as per label, cannot/will not fix
