### ISSUE TITLE
Unable to Place Metal into Circuit Imprinter

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#7788]
![image](https://user-images.githubusercontent.com/22057974/28184562-d840d9ee-67e1-11e7-8b48-3eca639cc066.png)

**Problem Description**:
You cannot place metal into the circuit printer.

**What did you expect to happen**: 
The ability to place the resources required for certain items from the imprinter into the imprinter.

**What happened instead**:
The inability to place metal into the imprinter.

**Why is this bad/What are the consequences:**
Certain items cannot be printed from the imprinter even if the research is available for such.

**Steps to reproduce the problem**:
• Acquire the research required for an item in the circuit imprinter that requires metal
• Be unable to place metal into the imprinter and therefore unable to print the item

**Comment by SamHPurp** [comment]
dupe of #7515

**Comment by granodd** [comment]
Woopsie.
