### ISSUE TITLE
Meteor Mode and the shuttle

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#779]
If a Meteor hits the shuttles console, apparently it causes the shuttle to lock up and never launch the shuttle, causing the round to never end.

**Comment by CrAzYPiLoT-SS13** [comment]
Emergency or crew transfer?

**Comment by Earthdivine** [comment]
I believe it was Emergency, however I came into the round after an admin asked for help on the staff chat so I do not know specifically.

**Comment by CrAzYPiLoT-SS13** [comment]
And this specifically happens only when a meteor hits the console?

**Comment by Earthdivine** [comment]
I wish I had thought ahead and got a screen shot of the shuttle, but the shuttle itself was still intact and all 6 doors were closed, most of the damage was at the bridge of the shuttle and that was missing consoles and broken window

I unfortunatly haven't been able to test it due to the nature of replicating it.

**Comment by CrAzYPiLoT-SS13** [comment]
And that is meteor gamemode or meteor event? I know it says mode in the heading, but I couldn't find anything in the gamemode files.

**Comment by CrAzYPiLoT-SS13** [comment]
Nevermind. Nothing in the console files, nor event files. Maybe one-time bug. And even if it isn't, there is a low chance we will ever see it again.

**Comment by Earthdivine** [comment]
It was meteor mode, and it probably won't come up very often, yes, as it needs two meteors to hit the nose of the shuttle dead on to replicate. Still worth noting for future reference though.

**Comment by veganzombeh** [comment]
I've seen this happen twice, actually. It's occurs when the console is destroyed/damaged(?) by a meteor. I suspect it has something to do with the shuttle datum's can_launch proc, but I'm not 100% certain.

**Comment by CrAzYPiLoT-SS13** [comment]
I will look into it again, but I didn't notice anything the first time.
