### ISSUE TITLE
AI Quarantine Law defaults to Law 8

### ISSUE THREAD

**Issue by Anasari** [ParadiseSS13/Paradise#7791]
**Problem Description**:
AI Quanrantine law defaults to Law 8

**What did you expect to happen**: 
It used to be an ion law / hacked law. 

**What happened instead**:
It is at law 8

**Why is this bad/What are the consequences:**
Because with the current priority, the quarantine law is in fact, utterly useless when bolted after crewsimov. While not technically a bug, this qualifies as an oversight.
**Steps to reproduce the problem**:
Upload quarantine lawset

**Comment by SamHPurp** [comment]
By design.

Read the law again, it infers that the AI is unable to harm the crew in its attempts to stop them leaving. Meaning it can kill them, and won't be harming them.

**Comment by Anasari** [comment]
By harming the crew while preventing them from leaving, Law 8 contradicts Law 1 in the case of Crewsimov. As following Law 8 (Which state crew cannot be harmed while being prevented from leaving) violates Law 1 by harming the crew, it leads to Law 8 being effectively, useless. 

It is also why onehuman / onecrew must be applied as a hacked law instead of after the normal lawset

**Comment by SamHPurp** [comment]
"It is impossible to harm the crew" not "you cannot harm the crew" - nothing they do can possibly harm the crew, even if its slamming them to death with a door.

This never used to be an ion. This is how its always been.

**Comment by Spacemanspark** [comment]
No, it hasn't. It used to be a law 0.
It does not override crewsimov in this situation. I don't know where you're getting that from, but law priority will go in order, with 1 being the highest priority law.

**Comment by SamHPurp** [comment]
@Spacemanspark

"The station is under a quarantine. Do not permit anyone to leave. Prevent, by any means necessary, anyone from leaving. It is impossible to harm anyone while preventing them from leaving."

It is re-defining harm.

Its been like this ever since I've been on Paradise.

Here is a commit from 2014: https://github.com/ParadiseSS13/Paradise/commit/587de30588d5cb8d2b3b316eb17828aceafb5686


```
laws = list("The station is under a quarantine. Do not permit anyone to leave. Prevent, by any means necessary, organics from leaving. It is impossible to harm an organic while preventing them from leaving.")
lawpos = 8
```
is the relevant code...

**Comment by alexkar598** [comment]
Because of cresimov law 2 you can just say ignore law 8 and the au should follow your order

**Comment by alexkar598** [comment]
Not au but ai damn autocorrect

**Comment by Anasari** [comment]
By re-defining harm, you are causing crew harm. Which in itself contradicts law 1. As quarantine is Law 8, that means Law 1 > Law 8, thus rendering the entire quarantine law moot.

It seems I've in fact misunderstood what the quanrantine module was. However, in 2015, when blob mode started, quarantine was in fact a zeroth law: https://github.com/ParadiseSS13/Paradise/pull/170/files 

Quarantine module should be made into an ion law (Not zeroth, as it would override traitor AI) or altogether removed and reserved for admin only.

**Comment by Anticept** [comment]
What's wrong with just making it law one, and bumping the others down one? I don't think we should be making it an ion law. It's meant to be an actual lawset.

As for the 0 law: its entirely possible to just check the AI for the special character flag before uploading, so it doesn't overwrite law 0.

**Comment by taukausanake** [comment]
Maybe you can have a special slot that the quarantine law takes up so it doesn't override any other? Or maybe a totally new lawset designed for quarantine. I don't think pushing a law into the list and moving the others up would be favorable

**Comment by Tayyyyyyy** [comment]
We had discussed this issue in [this forum post](https://nanotrasen.se/forum/topic/10298-fix-quarantine-law-priorities/#comment-85388). Quarantine law is seriously messed up and doesn't work well with any lawset. It may be best off being its own lawset.

@Anticept That avoids the whole issue with quarantine law overriding antag laws but I think it also suffers from the issue of how quarantine could be lowered if the AI is supposed to prevent the lifting of the quarantine at all costs. Also no other module does that so it would require a tiny bit of snowflaking.
