### ISSUE TITLE
Adv trauma kits do not fix the bleeding status in the blood refactor

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7803]
**Problem Description**:
Adv trauma kits do not fix the bleeding status in the blood refactor

**What did you expect to happen**: 
It's a trauma kit, which should include fixing bleeding.

**What happened instead**:
It doesn't fix bleeding, and in fact prevents gauze, which DOES fix bleeding, from working.

**Why is this bad/What are the consequences:**
It's inconsistent and can set people in a state where they cannot stop bleeding without getting smacked again.

**Steps to reproduce the problem**:
Get bleeding status. Apply trauma kit. Still be unable to stop bleeding.

NOTE: My local copy of dream maker can't seem to compile and run the recent version of the codebase without crashing, so I can't do anything more than report what has come through in ahelps.

**Comment by Anticept** [comment]
Got my local copy working. Disregard, I cannot duplicate the issue.

**Comment by Fox-McCloud** [comment]
They don't stop bleeding; this is part of the changes to how trauma kits work under the bleeding refactor--it's unavoidable.

Bandages, however, will stop bleeding.

**Comment by Anticept** [comment]
Got it!

So basically, the adv trauma kit itself doesn't stop the bleeding, but if they are healed enough, it will. This is still an issue for someone on the brink of death, as it means you have to find gauze and use it. If they are already treated with adv trauma kits, then you CANNOT gauze them. You have to hit them again, then gauze.

**Comment by Fox-McCloud** [comment]
Why would you not be able to use gauze on them if they've been treated with a trauma kit?

**Comment by Anticept** [comment]
It says they are already bandaged.

**Comment by Anticept** [comment]
Replication is irregular, and I learned a lot more about the system and gauze. It's quite a bit different in thinking from the old system, and its nuances are going to take some getting used to.
