### ISSUE TITLE
Diona nymphs die without oxygen

### ISSUE THREAD

**Issue by Ataman** [ParadiseSS13/Paradise#7807]
**Problem Description**:
Nymphs die without oxygen unlike grown dionas.
 
**What did you expect to happen**: 
Not to die due to oxygen loss.

**What happened instead**:
Dying to oxygen loss.

**Why is this bad/What are the consequences:**
From time to time, oxygen in the vent or scrubbers is not available due to "unusual" circumstances. This prohibits any future travelling through the vents for dionas. Space walks or locations without oxygen atmosphere result in death as well.
Also, it doesn't make any sense.

**Steps to reproduce the problem**:
Be diona nymph, go into space.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Simple bug really. Issue #6028 is probably related to this and fixing this bug should logically fix the other one.

**Comment by Ataman** [comment]
UPDATE:
It seems being in space kills the nymph even with fixed atmos requirements. Trying to figure that out now...

**Comment by Anticept** [comment]
I would like to see the nymphs be able to survive without O2. It's a bit inconsistent with gestalts.

**Comment by Ataman** [comment]
Ya me too.
Just made them space worthy on my local branch by changing atmos requirements and minbodytemp. I should have a pull request up tomorrow fixing both this and the other issue.

**Comment by DesolateG** [comment]
They'll die from lack of O2 even in a pod.

**Comment by Ataman** [comment]
@DesolateG PR #7808 removes the O2 requirement from nymphs so they can't die from lack of O2 in pods.
