### ISSUE TITLE
Xray gene persists through cloning.

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#7810]
ERT member with Xray and hulk. Died, cloned. XRAY still active as a fresh clone.

**Comment by Crazylemon64** [comment]
Cloning spawns you with the same DNA as you had before the scan - so if you had a positive mutation that'd be kept and passed to your clone. Though, did hulk transfer, or did the %chance for that to manifest not proc?

**Comment by DesolateG** [comment]
Hulk didn't stay, only Xray, and of course there's the thing of ERT members becoming random baldies.

**Comment by FlattestGuitar** [comment]
Hulk is the one and only gene that can be removed without changing genes. If you get 100 damage it just turns off automatically.

**Comment by Crazylemon64** [comment]
Oh, right, the high amount of clone damage would be able to cause hulk to fall off. It looks like everything is working just fine, in your example?
