### ISSUE TITLE
New blood mechanics with slime person

### ISSUE THREAD

**Issue by Varghh** [ParadiseSS13/Paradise#7812]
**Problem Description**:
You can ramp up your blood level as a slime just drinking sink water, but you can also go up to 357% blood level with a 2000cl hard cap.

**What did you expect to happen**: 
Drink water to see if i can recover blood level

**What happened instead**:
I was able to do that and also increase my blood level to 357%

**Why is this bad/What are the consequences:**
You can up your level so high to the point you can survive with several internal bleeding for a good time

**Steps to reproduce the problem**:
Just drink water, blood level will go up
![bloodlevel](https://user-images.githubusercontent.com/26222480/28251070-0819fdb4-6a4c-11e7-98cb-2dcdaf7bea46.jpg)

**Comment by Crazylemon64** [comment]
drink up

**Comment by EvadableMoxie** [comment]
*squish

Slime Supremacy!

**Comment by taukausanake** [comment]
Just make it so that slime people get fat if they drink too much water. ~And gib/melt if over too much.~ I think it's interesting to have extra fluids as a slime person but maybe make them bleed more? Or not at all because fuck slipping on blood-water. Maybe you can't balance this

**Comment by ktoma36** [comment]
I wouldnt mind having a mechanic in place that would make us slimes blob out a bit, actually I think it would be kind of cool. Also, you guys seem to overlook the fact that even if you could survive several internal bleeding cases at once, you would most certainly have had the crap beaten out of you. Also, blood seems to pour out faster if you have a lot of it. I took a .50 cal to the arm during a nuke ops round, I kept chugging water but more blood started seeping from my wound and through my bandages

**Comment by KasparoVy** [comment]
Was this not resolved by #7821?

**Comment by taukausanake** [comment]
Maybe @Fox-McCloud forgot to add the fixes keyword?

**Comment by Fox-McCloud** [comment]
Oops, forgot to put fixes: this_par in that...yeah, this isn't an issue anymore.
