### ISSUE TITLE
Virus will now mix with each other when you use an IV with a monkey with 3 viruses

### ISSUE THREAD

**Issue by Varghh** [ParadiseSS13/Paradise#7813]
**Problem Description**:
I've been playing viro for a good amount of time and have come with a perfect mix of 3 viruses, i was able to put 3 of them inside a monkey and then milk is blood with an IV and a 100u beaker

**What did you expect to happen**: 
I will get 100u of blood with the 3 viruses i put inside the monkey

**What happened instead**:
All 3 viruses mix each other all the time the IV take blood, letting you with just one virus with random symptoms. This also happen if you take blood with a syringe and drop it inside a beaker, if you put 5u you have the viruses, bud add the syringe one more time and the blood will mix and end up with a random 1 virus of mixed symptoms

**Why is this bad/What are the consequences:**
You can still create a super healing 3 part viruses, but you need to add 5u of blood with syringe, make 5 pills, add 5u, make 5 pills and repeat to the ends of time.

**Steps to reproduce the problem**:
Put 3 viruses inside a monkey and milk his blood with IV, beaker now will have one virus of random symptoms. Same happen if you add 5u from a syringe to a beaker 2 times.

**Comment by alexkar598** [comment]
Virus mixing is part of virology

**Comment by Varghh** [comment]
Before the blood revamp, after you mix 3 separate viruses, let's say virus 1, 2 and 3, you where able to take 100u of blood from a monkey with the IV having that blood with virus 1, 2 and 3, now it mix them togheter and you end up with 1 virus with mixed symptoms from the 3 viruses

**Comment by matt81093** [comment]
That is different. Good to know if that's intentional
