### ISSUE TITLE
Changeling Swapbodies weirdness

### ISSUE THREAD

**Issue by Aracino** [ParadiseSS13/Paradise#7822]
**Problem Description**:
 When you use the ability to swap bodies with someone, eventually IF said person was your objective to kill/become by the end of the round, your objectives will go to plan (a,b,x,y,z whatever)

**What did you expect to happen**: 
I expected to complete my objectives, having done all of it beforehand.

**What happened instead**:
 I got a fresh new set to complete instead of the old ones which I already completed.

**Why is this bad/What are the consequences:**
Major bug, screws with changeling plans. Mine was a very delicately woven ruse. This caused major issues.

**Steps to reproduce the problem**:
Be a changeling.
Body swap with your assassinate/become objective.
(not sure if this is the case) Kill both sides, clone the changeling in the swapped persons body, incinerate the changelings old body)
Wait like...30 minutes...ish.
SUDDENLY YOU HAVE NEW OBJECTIVES!
(Unsure if the players disconnection caused the objectives to change)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was in a cling round, outside of this, nothing odd. Also, you don't get the person you swapped bodies with information. Stuff like their PIN and such.

**Comment by Spaghetti-bit** [comment]
Changelings can no longer be cloned. This issue doesn't happen anymore, thankfully.

> Also, you don't get the person you swapped bodies with information. Stuff like their PIN and such.

You're not supposed to get this unless you directly absorb them, body swap does not do this.
