### ISSUE TITLE
Corpses causing IPCs to vomit.

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#7825]
**Problem Description**:
As my IPC I've been vomiting due to bloated corpses. 

**What did you expect to happen**: 
IPCs shouldn't be able to vomit.

**What happened instead**:
Not vomiting.

**Why is this bad/What are the consequences:**
IPCs lack the internal organs to produce and eject vomit. MUH IMMURSION!

**Steps to reproduce the problem**:
Be an IPC.Stand near a bloated corpse. Puke.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by Citinited** [comment]
Unable to reproduce. Maybe there was something else going on?

**Comment by Ralta** [comment]
Don't spose you have a log file? Or possible the time/date of when this occurred?

**Comment by ZN23XZ** [comment]
Odd. Happens to me all the time so I can reproduce it if needed. How do I pull a log file?

**Comment by ZN23XZ** [comment]
Or I can give an exact time and date next time it happens. Which I can do next round I'm in.

**Comment by ZN23XZ** [comment]
12:38 PM EST 7/18/17. Round timer 12:47. And multiple times after that. *buzz2

**Comment by taukausanake** [comment]
Make them vomit oil

**Comment by shazbot194** [comment]
I also have had this issue, I did catch a screen shot.
![nl6ny_y4rdmtqqk1cdxh7g](https://user-images.githubusercontent.com/22019537/28350093-0f3870be-6bf3-11e7-85f4-3437a9e1eb7a.png)

**Comment by Fox-McCloud** [comment]
seems IPCs have olfactory sensors now.

**Comment by Allfd** [comment]
This is the greatest thing ever.

**Comment by adamkad1** [comment]
add robopuke plz

**Comment by taukausanake** [comment]
Blame it on bluespace if you do
