### ISSUE TITLE
Change in the effect of EMPing a mechanical heart

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#7834]
This has been going on a while, and I always assumed the change was on purpose till I started reading other bugs that have been reported. Currently when my snoflek human with a mechanical heart gets EMPed I instantly black out and die due to oxyloss before waking up. A while back (2-3 months ago?) It used to be get EMPed, immediately suffer oxyloss damage eventually leading passing out and death. The big difference is I wouldn't pass out instantly after being EMPed. This would give me the opportunity to say "Gah! My heart!" or, more notably, beat a nukie to death with my baton before passing out due to oxy loss. I wasn't sure if the instantly passing out feature was on purpose or maybe a bug created by something else that was added.

**Comment by Fox-McCloud** [comment]
Intentional, not a bug, and was a deliberate documented balance change.

**Comment by ZN23XZ** [comment]
Just wanted to check. Thanks for the quick response!
