### ISSUE TITLE
No external access for new arrivals airlock 

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#7840]
**Problem Description**:
The new cycling airlock at arrivals doesn't have a button to activate it from the exterior.

**What did you expect to happen**: 
To be able to enter from the exterior.

**What happened instead**:
Unable to enter.

**Why is this bad/What are the consequences:**
Forced to break/create entrance or go to a different airlock.

**Steps to reproduce the problem**:
Attempt to enter arrivals airlock from exterior.

**Comment by SamHPurp** [comment]
@ZN23XZ It does.... It might need its placement altered slightly. But its there. 100%.

**Comment by ZN23XZ** [comment]
Is it under the poster?

**Comment by SamHPurp** [comment]
It might be hidden under the r-glass on the tile below it.

I'll double check and fix in #7837

**Comment by ZN23XZ** [comment]
Ahhh yea I see it. Sorry. Yea it's sorta hidden in the glass.

**Comment by ZN23XZ** [comment]
Forgot to update this. The button is there but cannot be pressed unless you remove or break the glass.

**Comment by SamHPurp** [comment]
Yep, I'm fixing it in the previously mentioned PR.
