### ISSUE TITLE
Unable to respawn - changeling 

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#7846]
**Problem Description**:
After being mind switched and finding body, removed my brain from body, ghosted while in surgery, tried to enter back brain via "return to corpse" and get the error, "you've given up your right to respawn". Note that after the brain was removed from body when I ghosted.

**What did you expect to happen**: 
Be able to return to brain.

**What happened instead**:
Lost the ability to respawn completely.

**Why is this bad/What are the consequences:**
It wasn't player forced.

**Steps to reproduce the problem**:
Have changeling body switch with you
Lay on surgery table
Have someone remove brain of body
Ghost when brain is removed
Ghost tab, enter corpse

**Possibly related stuff (which gamemode was it? Changeling event. I was mute stung and mind switched by a changeling.

**Comment by Trubuss** [comment]
I add, 
make sure the changeling is dead.
The new body was a wolpin, UI to look like myself.

**Comment by Trubuss** [comment]
Scanned my headless corpse to get the UI and injected to the mindswapped body I was in.

Sorry I keep remembering but and pieces

**Comment by Sirryan2002** [comment]
cant reproduce
