### ISSUE TITLE
Unconnected Scrubber, Central Primary Hallway

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#7852]
**Problem Description**:
The scrubber in Central Primary Hallway is connected to a broken section of pipe that doesn't connect to the waste loop.

**What did you expect to happen**: 
The pipes should be properly layed down so the scrubber is connected.

**What happened instead**:
They aren't.

**Why is this bad/What are the consequences:**
Mostly because the hallways are already relatively low on scrubbers, so having one of the most central locations unable to filter any gases can be troublesome.

**Steps to reproduce the problem**:
Just walk up to the Central Primary Hallway Air Scrubber #1 and follow the pipe. It is unconnected 3 tiles up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I got a capture if that helps, with the relevant piping.
![pipes1](https://user-images.githubusercontent.com/7857084/28497186-76c899fc-6f81-11e7-81bb-09e126460b46.png)
![pipes2](https://user-images.githubusercontent.com/7857084/28497188-76cee640-6f81-11e7-8b1f-216b2786f3c9.png)

**Comment by Citinited** [comment]
This gets fixed in #7735

**Comment by Ataman** [comment]
That explains how people keep getting stuck in maintenance there when ventcrawling.
