### ISSUE TITLE
[MetaStation] Broken tophat

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#7861]
**Problem Description**:
The top hat that spawns on the bar can not be picked up. This same issue persisted across multple rounds. You can drag it, though.

**What did you expect to happen**: 
Because one tends to be able to pick up and wear top hats.

**Steps to reproduce the problem**:
Launch Metastation, attempt to pick up the top hat in the bar.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
It was on metastation.

**Comment by SamHPurp** [comment]
That is fucking weird.

I'll investigate.

**Comment by Fox-McCloud** [comment]
make sure its `throwing` var isn't set to `1` on the map, itself.

**Comment by FalseIncarnate** [comment]
Legends say that he who can lift the hat is the only worthy of wearing it.

Or something.

**Comment by SamHPurp** [comment]
@Fox-McCloud Yeah that was it... who the fuck set that var.... Fixing now.
