### ISSUE TITLE
[Metastation] No Pet supply vendor

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#7863]
**Problem Description**:
I searched that station as well as I could, and did not find the pet supply vendor. So it's not there or it's waaaay out of the way.

**What did you expect to happen**: 
I was expecting, or at least hoping, metastation would have one.

**Why is this bad/What are the consequences:**
Chef can't make sushi, and people can't rename mice.

**Comment by taukausanake** [comment]
Furries also can't put collars on their uniforms anymore either

**Comment by SamHPurp** [comment]
> Furries also can't put collars on their uniforms anymore either

Feature
