### ISSUE TITLE
abductors can't abduct

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#7866]
**Problem Description**:
Attempting to recall a cuffed/marked person as abductor scientist can result in your agent being recalled. It worked several times before this, but once it got in this state, it never worked again. The agent was ALWAYS recalled instead of the cuffed person, even though the cuffed person had been marked, was targeted, etc, and it had been working fine previously.

**What did you expect to happen**: 
I expected abductors to be able to abduct.

**What happened instead**:
At a certain point, something bugged out and abductors could no longer abduct any victims, because the console would not teleport them.

**Why is this bad/What are the consequences:**
Pretty much wrecks abductors.

**Steps to reproduce the problem**:
Unknown. Happened halfway through the round. All abductions before worked. All afterwards did not. Might have been related to buying a replacement science tool from the console with points. The original tool worked - the replacement tool never seemed to.

**Comment by Aracino** [comment]
I was the agent. Randomly I got flashed and got KOed for a good bit. It failed to work after I was in a cryotube for a bit, Note, by randomly flashed I mean this:

Abductor Mindlink, Mothership Upsilon Scientist gibbers, "West"

Simon Straub has stunned Harkness Lamb with the advanced baton!

You switch the baton to sleep inducement mode.

Simon Straub has induced sleep in Harkness Lamb with the advanced baton!

You switch the baton to restraining mode.

Simon Straub begins restraining Harkness Lamb with the advanced baton!

You handcuff Harkness Lamb.

Harkness Lamb snores.

You silence Harkness Lamb's radio devices.

Your eyes cry out in pain!

**Comment by Fox-McCloud** [comment]
Wait....as I was the one who stopped your abduction attempt....

I took both your science tool and your baton.

As far as I know you didn't teleport in and get the originals back (maybe you did).

Did you purchase a new tool? If you did, did you link it to the console?

**Comment by Kyep** [comment]
Yes, we bought a new tool. No, we did not link it to the console, as neither of us realized that was required.
The tool seemed to work to mark things, etc. It just did not seem to work to retrieve people.

While that could (should?) be clearer, the original issue (it doesn't work) isn't really accurate. It may work... you apparently have to link it first. Closing.

**Comment by Fox-McCloud** [comment]
Yeah, just looked up the code on this; you'll have to link it, or it won't work properly.
