### ISSUE TITLE
Physical Ghosts

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7867]
**Problem Description**:
Ghosts, if thrown with the buildmode mode, do smash into people and other objects.

**What did you expect to happen**: 
Non-coporeal ghosts passing through objects not affecting anything.

**What happened instead**:
The thrown ghost smashed into grilles, destroying them on the second hit, hit mobs, moving them.

**Why is this bad/What are the consequences:**
You might affect the living while toying around with ghosts.

**Steps to reproduce the problem**:
Enable buildmode, cycle to throw mode, select ghost to throw, throw them somewhere.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tested with hitting a human, ai core, and window grills, if you attempt to throw the ghost past them, you hit it. You do also get stopped on machinery and doors, but not by walls.

**Comment by Bram961** [comment]
Seems like a strange idea to implement extra code to fix something that only happens when you use a mode meant for building to throw around ghosts.

**Comment by Rumiluntti** [comment]
Seems like a fantastic adminbus feature to me.
Spirit bomb!

**Comment by MarsM0nd** [comment]
Yeah, it's not really that bad, but might point out that some interaction checks might be needed. Figure the scouting holoparasite does get thrown by black matter, and probably behaves the same there.
