### ISSUE TITLE
All seeing camera console

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7871]
**Problem Description**:
The advanced camera console can be used to see everything

**What did you expect to happen**: 
The camera console to only show what cameras can see.

**What happened instead**:
I was able to see things where no camera was even near.

**Why is this bad/What are the consequences:**
You can look into hidden areas.

**Steps to reproduce the problem**:
Activate an advanced camera console
Go to the area where you want to look at, but currently can't
End the camera view with the GUI button
Activate the console again
See that you can see what you shouldn't see

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tested only with the /obj/machinery/computer/camera_advanced, not the subtypes, spawned in on z2.

**Comment by Shadow-Quill** [comment]
@Anasari Cannot reproduce.
