### ISSUE TITLE
Hand implants

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7872]
**Problem Description**:
If you spawn an implant with the game panel in your hand, it becomes "implanted" in that handslot.

**What did you expect to happen**: 
Getting the implant to be used like normal in the characters hand

**What happened instead**:
The full implant functionality was added, and i had a undroppable implant in the hand it spawned in.

**Why is this bad/What are the consequences:**
Implants need to be spawned on the floor, which is unhygienic.

**Steps to reproduce the problem**:
Game panel, create object object, set where to "In own mob's hand", spawn implant.

**Comment by taukausanake** [comment]
I can only see this as a bluespace error where the spawning item spawns in the exact same place as your hand. Sounds hilarious

**Comment by Fox-McCloud** [comment]
`Implants need to be spawned on the floor, which is unhygienic.`

This is just plain incorrect.

Also, what do you mean by implant? Implants? Augments? People use those two interchangeably and it causes confusion.

**Comment by MarsM0nd** [comment]
Oh, yeah, the cyberimplants, or augments, and the spawning on the floor being unhygienic was a joke, know there is no mechanic behind it, just found the problem that you can't spawn in hands.

**Comment by Fox-McCloud** [comment]
Which one did you spawn?

**Comment by MarsM0nd** [comment]
The combat arm implant and xray, i had xray vision, and was able to get the weapons after having set the combat implant to the left hand, as it spawned in my right.

**Comment by Crazylemon64** [comment]
This is something that only happens when fooling around with admin tools to push code in a way it won't work.
