### ISSUE TITLE
His Grace (Chaplin Hijack Item) can be bought without having hijack objective

### ISSUE THREAD

**Issue by EldritchSigma** [ParadiseSS13/Paradise#7874]
**Problem Description**:
The Traitor Item "His Grace"/Artistic Toolbox which costs 20 TC is supposed to be a Hijack only item. You can buy it regardless of the objective. 

**What did you expect to happen**: 
I expected that I cannot buy it as a chaplin traitor with regular objectives like "Steal the NAD" or "Murder the Captain". 

**What happened instead**:
It was able to purchase the Toolbox despite not having the right objective. Did not click on it to test it out, but considering it popped up it might work. If it doesnt then treat this issue as fixed please.

**Why is this bad/What are the consequences:**
New people might think "Hey its 20 TC, might be good" and buy it not knowing it is really only supposed to be used when you have to hijack.

**Steps to reproduce the problem**:
Reproduceable. Have rolled 3 times Chaplin traitor so far. All 3 times none hijack. Was able to buy the toolbox at any given point.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode was Traitors.

**Comment by Fox-McCloud** [comment]
If you try to purchase it, it will fail. The toolbox is always on your list, regardless of if you have the objective.
