### ISSUE TITLE
Femto Manipulators Protolathe bug

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#7883]
When you upgrade the protolathe with more advanced manipulators it makes the protolathe work faster except for the Femto Manipulators, which drastically slow down the protolathe.  It takes over a minute to print a stack of 10 parts with femto manipulators installed.  I would expect, based on the trend of the other manipulators installed that femtos would decrease the time it takes to build stuff.  The problem is easy to reproduce, just install femtos on the protolathe and test it.  This is a fairly annoying problem as it can take 10 minutes just to print the parts to upgrade the station with femtos installed in the protolathe.

**Comment by EldritchSigma** [comment]
I can confirm... I thought this was some kind of feature, but now that someone actually mentions it... feels very weird. For the other upgradeable devices it seems to work normally like it should though.

**Comment by bigfatbananacyclops** [comment]
I knew something was wrong with the proto, i can agree this is true
