### ISSUE TITLE
GUI problems on 1366x768 displays.

### ISSUE THREAD

**Issue by RogueYun** [ParadiseSS13/Paradise#7884]
**Problem Description**:
On 1366x768 displays large interaction GUI's are uncontrollable and drift farther off screen after subsequent openings making access to essential buttons near impossible or impossible.

**What did you expect to happen**: 
The top of the GUI to be accessible to allow for movement of the GUI, access to the essential buttons, and easy closing.

**What happened instead**:
I can't access buttons at the top of the screen..

**Why is this bad/What are the consequences:**
It makes one of my favourite roles rather unplayable. It is perhaps a problem for other rolls as well that have to interact with large GUI's. It is possible to sometimes leave the server and open it again to reset the position of the GUI and see part of the buttons (see the example at the bottom of this issue). But that really makes the game near unplayable.

**Steps to reproduce the problem**:
Set monitor size to 1366x768 (my max size) or perhaps smaller. Try to access some of the screens in atmos. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

Here is an example of what it looks like initially and after accessing the same panel over and over again. There are several other panels in atmos that behave in the same way.
https://i.imgur.com/RVeh8kZ.gif

Perhaps an easy way to fix this is to provide a way to move GUI's from the bottom.

**Comment by FlattestGuitar** [comment]
Alt+space is your friend in any windows app that opens additional windows. We can't really fix this, as it's an issue with BYOND.

**Comment by RogueYun** [comment]
It's a shame they didn't teach me shortcuts in school. Thanks.

**Comment by RogueYun** [comment]
Actually, I don't think alt+space even works... which is a real bummer. It is only the title bar that allows for the GUI window movement. Wow... Thanks BYOND.

**Comment by RogueYun** [comment]
Would it be possible to decrease the max size of gui's (without ticking too many people off) to something about 50-75 pixels smaller? It's not too much of the screen. A slightly smaller gui would be a nice solution as well.

**Comment by RogueYun** [comment]
After doing some searching on the internet I came across this solution. [alt + spacebar] [m] [directional arrow keys] this allows you to move the window with just the keyboard.

**Comment by AffectedArc07** [comment]
Turn `Fancy NanoUI` off in your game settings, then you can get full windows

**Comment by adamlwgriffiths** [comment]
I get this too, except the window tries to move downwards (I have my taskbar at the top, perhaps its running away from it?).
The initial state is ok, but any attempt to move the window (and sometimes clicking the X close button goes through and triggers a move operation) causes the behaviour.
The bottom half of the window is cut off and inaccessible.
The window, while being dragged, animates itself jumping between the title bar being at the bottom most extremity of the screen, to nearly halfway, in quick succession.

I've tried the alt+space trick, but this is a game window and not an actual "windows" window, so the menu comes up for the root window instead.

**Comment by adamlwgriffiths** [comment]
BYOND are saying that it may be an issue with SS13

http://www.byond.com/forum/?post=2306425

Seems there's confusion as to where the bug truly lies

**Comment by adamlwgriffiths** [comment]
> Turn Fancy NanoUI off in your game settings, then you can get full windows

Where is this setting?

**Comment by Crazylemon64** [comment]
@adamlwgriffiths It's in "Game Preferences", although much time has passed and this information is likely no longer pertinent.

**Comment by adamlwgriffiths** [comment]
I ended up finding it in one of those menus. It wasn't obvious. I believe it was in-game rather than part of the app menu bar.
That did fix my problems though, but it would be nice if it worked out-of-the-box.

**Comment by AffectedArc07** [comment]
No comments in over 2 years, and this also seems like a user error not a codebase error. Closing.
