### ISSUE TITLE
Phlogiston does NOT ignite on hit when fired via syringe gun, doesnt reignite either even if the target was previously set on fire.

### ISSUE THREAD

**Issue by EldritchSigma** [ParadiseSS13/Paradise#7889]
**Problem Description**:
Phlogiston is supposed to ignite and reignite a target when shot via a syringe gun or ingested by any other means. It doesnt do that anymore loosing its main function when fired via syringe which is the psychological effect of being set on fire. It does still apply the burn stacks and damage however. Essentially targets burn from the inside now only without any visual indication of burning. This can be helpfull or not so helpfull depending how you see it.

**What did you expect to happen**: 
What I expected was that, after the Fluorosulphuric Acid nerf, that Phlogiston was unaffected and still ignite targets when injected via Syringe Gun. This is not the case. Phlogiston is supposed to ignite the target as soon as it is in the system and reignite it when extinguished. It does it when used as smoke, but not anymore on syringes. I tried setting the target on fire by other means (Napalm followed by a welder) and extinguished them. They did not reignite despite having Phlogiston in their system.

**What happened instead**:
I expected that Phlogiston, when fired by a Syringe Gun, still applies its burn effect and not only adds up stacks and stacks of burn damage.

**Why is this bad/What are the consequences:**
Phlogiston looses its function as a crowd control weapon when used via Syringe Gun/Pure Shotgun Darts. People probably wont even notice if they get hit by Phlogiston till they start seing that they burn on the inside. This can be beneficial or incredibly bad depending on the situation and feels rather wonky.

**Steps to reproduce the problem**:
Simple. Make Phlogiston, shoot it at any humanoid. They wont ignite, but still take the stacking burn damage after the first cycle like before. Also if they are already burning the Phlogiston wont reignite them anymore like it used to.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Any Gamemode, just requires a syringe, a syringe gun and Phlogiston.

Next to check: Other chems which might got affected, namely Frost Oil and Mutadone.

**Comment by Fox-McCloud** [comment]
Phlog ignites on TOUCH or INGEST. Syringe guns don't proc INGEST anymore. Not a bug.

Phlog doesn't re-ignite based on `on_life`, either. 

This is 100% working as intended.
