### ISSUE TITLE
Syndi-Bee Venom affects IPCs.

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#7891]
**Problem Description**:
Syndi-Bee Venom seems to affect IPCs.

**What did you expect to happen**: 
While I was being stung, the attack message said it didn't affect me. Also IPCs can't be poisoned, which means that any attempts to cure them of poison is impossible.

**What happened instead**:
I was taken to Robotics, revived but I never got out of the critical state before dying again. This happened multiple times.

**Why is this bad/What are the consequences:**
Permanant Death and a misleading attack message.

**Steps to reproduce the problem**:
Be an IPC. Get Stung by Syndibee. Try to get revived afterward.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Not sure.

**Comment by Birdtalon** [comment]
I am Investigating this.

**Comment by Birdtalon** [comment]
I so far haven't been able to recreate the bug on several IPC characters using syndicate bees. All were able to be repaired using cable/welder as usual and returned to life from death.

**Comment by Fox-McCloud** [comment]
Syndi-bees inject fluorsulfuric acid, which most *certainly* impacts IPCs.

I'm guessing the message it gave was "the blueish substance isn't concentrated enough to hurt you", which applies to everyone. You're getting injected with it, and the injection amount *isn't* enough to proc acid melting, but it is still getting injected into you, which will cause damage over time.

**Comment by StreakyHaddock** [comment]
Are you sure it should be killing me over and over again though?

**Comment by Fox-McCloud** [comment]
If you had a lot in you? you bet.

They'd repair you, you'd revive, then you'd start processing reagents again, while alive, and thus the remaining acid would continue to damage you; you'd die again, then the process would repeat all over.

Eventually the acid would deplete---I'm guessing you got stung * a lot*.

**Comment by StreakyHaddock** [comment]
And that's... a feature?

**Comment by matt81093** [comment]
Should probably be a way to extract reagents from people with a syringe..

**Comment by Fox-McCloud** [comment]
@StreakyHaddock 

Yeap.

**Comment by taukausanake** [comment]
I thought the bees would just do brute damage to IPCs instead of injecting them with chemicals that don't really have a way of removal

**Comment by StreakyHaddock** [comment]
That's my issue. If just trying to out-heal the poison for ages is the only solution that seems kinda inelegant and strange. But the thread's been closed and syndi-bees aren't really a common occurance.

**Comment by granodd** [comment]
Seems inconsistent, unless Syndi-bees have stingers made of adamantium. Syringes ping off IPC, and Spider venom don't end up in IPCs (or at least, if it does, there's no way of telling (cyborg analyzer showing reagents contained when?)). That aside, fluorosulphuric acid working on IPC ain't weird, how it got into them kind of is.

**Comment by taukausanake** [comment]
Maybe it works with normal bees too. I wonder how much salt could generate with robo-bees stinging IPCs :3

**Comment by matt81093** [comment]
@taukausanake robo-bees? But yeah I guess a question would be.. should IPC get injected. Syringes apparently don't with IPC's.. so what should?

**Comment by taukausanake** [comment]
Depends if you have a way to remove their reagents. I guess this can be countered if you make a reagent that purges everything inside an IPC. Cybernetic carbon/charcoal (that sounds like an oxymoron). If no one can agree with IPCs not getting injected by anything then that would have to be the next solution. That or have IPCs process non-IPC reagents faster because _why are they in there to start with_

**Comment by FalseIncarnate** [comment]
Flurosulphric acid is a reagent processed equally by synths and organics, on purpose.

Acid doesn't care if it is flesh or metal, it just wants to corrode stuff and so it does.

As for a purgative... how about that Degreaser reagent you have been able to make in chemistry since the introduction of synth drugs? You know, the one that LITERALLY purges reagents like charcoal does, except for synths...

**Comment by taukausanake** [comment]
@FalseIncarnate I did not know that existed. I guess issue is completely solved
