### ISSUE TITLE
Frozen headpockets

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7892]
**Problem Description**:
Headpockets are recovered when a skrell cryos.

**What did you expect to happen**: 
It's part of their body, and such, should go into cryo with them.

**What happened instead**:
A spriteless headpocket (/obj/item/weapon/storage/internal) could be recovered with the cryogenic oversight console.

**Why is this bad/What are the consequences:**
Skrells will need head surgery after a cryosleep.

**Steps to reproduce the problem**:
Cryo a Skrell, recover items.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing.

**Comment by SamHPurp** [comment]
I'm on it.

**Comment by taukausanake** [comment]
The original PR has them as `obj/item/organ/internal`. What happened there?
