### ISSUE TITLE
Obsolete science console in bridge

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#7895]
#**Problem Description**:
What is the problem?
There's a science console left over in the bridge, while the science outpost has been removed.
**What did you expect to happen**: 
Why do you think this is a bug?
- It's a simple oversight
**What happened instead**:
How is what happened different from what you expected?
- It's a simple oversight
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
- No consequences, just a simple oversight
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
- Remove the console
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by AffectedArc07** [comment]
Put a proper ID console there instead

**Comment by SamHPurp** [comment]
Got a PR to fix this on BoxStation, but it doesn't actually exist on MetaStation @Crazylemon64 so, its not an issue there.

Cheers
