### ISSUE TITLE
Mimes can howl

### ISSUE THREAD

**Issue by Little-119** [ParadiseSS13/Paradise#7899]
**Problem Description**:
Mimes can howl

**What did you expect to happen**: 
Mimes not being able to howl

**What happened instead**:
Mimes can howl

**Why is this bad/What are the consequences:**
Mimes are supposed to be silent

**Steps to reproduce the problem**:
Be Vulp mime. Howl.

**Possibly related stuff**: Nothing

**Comment by FlattestGuitar** [comment]
I think the issue is that howling is a thing in the first place.

🐺 ⛔️

**Comment by SabreML** [comment]
Fixed by #13353.
