### ISSUE TITLE
Sake is non-alcoholic

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#7901]
**Problem Description**:
Today I chugged about 100 units of sake, and never felt any effects at all.

**What did you expect to happen**: 
To get drunk, just like every other type of alcohol.

**What happened instead**:
I did not.

**Why is this bad/What are the consequences:**
It's just inconsistent.

**Steps to reproduce the problem**:
Make a bunch of sake, then drink it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I drank it out of condiment bottles, if that would affect it for some reason.

**Comment by Fox-McCloud** [comment]
Wrong: https://github.com/ParadiseSS13/Paradise/blob/da7bea7c6101c8c59b5e77e5ef00d1c89b6bd7c1/code/modules/reagents/chemistry/reagents/alcohol.dm#L147

**Comment by Jountax** [comment]
Huh. Maybe I drank less than I thought.
