### ISSUE TITLE
Legless Character bug invovling being unbuckled from chair

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#791]
I have a char i rp legless (odd i know), with the new limb code when i unbuckled from my chair i tend to do Scream then collapse unable to move. While i realize the best solution is to not unbuckle, I could rpeviously unbuckle and pull myself around so i could help pull a person to safety or an object.

Suggestion:Make it so i can pull objects or people VIA some form of rope with my chair. However i do realize there would probaly be so many balance and/or grieffing issue to consider with that and it wouldn't hurt my feelings either way.

**Comment by Fox-McCloud** [comment]
this is actually a feature of the limb overhaul; if you even have one leg missing there's a chance you fall down and screams.

**Comment by Aurorablade** [comment]
Figured it might be but it was doing it every time for me...I REFUSE TO SET THIS CHAR UP WITH PROSTHSIS! DOWN WITH LEGS! ((Seriously good work on the limb overhual and wasn't sure if it was buggy))
