### ISSUE TITLE
Forensic Scanner Bug

### ISSUE THREAD

**Issue by Threeinone** [ParadiseSS13/Paradise#7911]
**Problem Description**:
Forensic scanner does not accept Copy/pastes

**What did you expect to happen**: 
The DNA strand to paste into the scanner and get a name

**What happened instead**:
I hit paste and nothing happened

**Why is this bad/What are the consequences:**
This make the Forensic scanner DNA lookup take ages

**Steps to reproduce the problem**:
select DNA strand, right click, hit "copy", click on forensic scanner in your hand, click into the window, right click, select "paste.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Birdtalon** [comment]
I have pasted DNA strings into the scanner just fine, are you sure it wasn't on your end? @Threeinone

**Comment by Threeinone** [comment]
Hi there!
Yes, after posting it seemed to work just fine, so i may very well be a
problem on my part.
thanks. -Threeinone
