### ISSUE TITLE
Power Gloves Don't Work

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#7915]
**Problem Description**:
Power gloves don't work. Attempting to use them (harm/disarm intent on a mob, while standing on a live power wire) does nothing.

**What did you expect to happen**: 
Target mob should get zapped.

**What happened instead**:
Nothing.

**Why is this bad/What are the consequences:**
They're unusable.

**Steps to reproduce the problem**:
Wear power gloves.
Stand on a live wire. (I used wire in engine room)
Use disarm/help intent.
Click a mob.
Observe nothing happens.

**Comment by SamHPurp** [comment]
@Kyep You need to point at them, using middle click.

**Comment by Aurorablade** [comment]
yeah i have seen them work.

**Comment by Kyep** [comment]
We did not know you had to middle-click.
Last time I used them, simple click was enough.
Closing unless it can be repro'ed with middle click.
