### ISSUE TITLE
Squashed camera

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#7921]
**Problem Description**:
If you are watching a shuttle dock with advanced camera console, the center being inside the area where the shuttle lands, you can only see black, and after using cancel-camera-view, you are back in control of your normal char while still keeping the buttons and the console being in use.

**What did you expect to happen**: 
The surveilance to continue like normal.

**What happened instead**:
As described, destroying the console didn't stop the use.

**Why is this bad/What are the consequences:**
Permanently disables a console that's can't be removed as it is "in use" without admin intervention.

**Steps to reproduce the problem**:
Watch a shuttle dock, break your camera.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was watching a modified escape shuttle dock, with the /obj/machinery/computer/camera_advanced

**Comment by Crazylemon64** [comment]
pfffff

**Comment by SamHPurp** [comment]
Seems like it the camera's eye needs to be added to the white list of things the shuttle won't destroy (To give you a hint, ghosts will already be in that list, look for that code)

Good first issue this one.

**Comment by Sirryan2002** [comment]
fixed
