### ISSUE TITLE
Fake Grass Turfs

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#7922]
These two turfs are not actual grass turfs; pull them up and put them back down and it messes up:

![img](https://i.gyazo.com/62024662d15b699ed3bc16b7e041757f.png)

Location: BoxStation kitchen garden area.

**Comment by LittleBigKid2000** [comment]
It seems that there's two 'floors' on the tile. One being the border thing and the other being the grass. A simple fix would be removing the borders.
