### ISSUE TITLE
rnd server console is unable to delete research

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7928]
**Problem Description**:
What is the problem?
you used to be able to delete research items in the research server console but now the list is empty
**What did you expect to happen**: 
Why do you think this is a bug?
its not supposed to be empty
**What happened instead**:
How is what happened different from what you expected?
i expected the list to not be empty
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
you can disable certain research items with it now you cant
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
sync
go see console
its empty
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by SamHPurp** [comment]
I'm pretty sure this got removed ages ago, and I was against it then.

I could entirely be mis-remembering though.

**Comment by alexkar598** [comment]
never removed: https://github.com/ParadiseSS13/Paradise/blob/1fffea7aa8f86cb23066599cdd0721dd0ca3d81e/code/modules/research/server.dm#L320
