### ISSUE TITLE
Swarmers able to directly kill AI.

### ISSUE THREAD

**Issue by SomanBat** [ParadiseSS13/Paradise#7929]
**Problem Description**:
Swarmers are able to directly kill the AI with melee stun hits

**What did you expect to happen**: 
Swarmer shouldn't be able to directly kill AI

**What happened instead**:
AI died.

**Why is this bad/What are the consequences:**
Swarmers should not have the ability to directly kill the AI via stun shocks.

**Steps to reproduce the problem**:
Be swarmer. Spam AI with melee stun shocks.

**Comment by Aurorablade** [comment]
If the ai core is a machine typenit may have taken that long to dismantle it otherwise yes it may be a bug

**Comment by SomanBat** [comment]
It wasn't decon actions, it was the melee shock attack, that gets used on organics.

**Comment by taukausanake** [comment]
What does the shock attack do to borgs? Is it similar by chance?

**Comment by SomanBat** [comment]
Borgos take no damage from the melee shock attack.

It feels similar to an old issue with xeno eggs. There was no sanity checking on damtype, so the fastest way to pop xeno eggs was with stam damage from disabler shots.
