### ISSUE TITLE
Cyborg Heads Brandable, IPC heads Unbrandable

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#7936]
**Problem Description**:
Cyborg heads are brandable - which can't be attached to beheaded IPCs and is overwritten when the borg  chooses a module. So why would you want to brand them? Replacement IPC heads spits out a Morpheus Cyberkinetics Head. My guess is, since it's already a branded head, it can't be rebranded.

**What did you expect to happen**: 
A generic replacement IPC head to be produced, which can be rebranded when activated in hand, like every other robotics limb.

**What happened instead**:
It produced a Morpheus Cyberkinetics head which cannot be rebranded by activating it in hand.

**What are the consequences:**
Generic Heads, really. I take a kind of pride to restoring someone to being just as/better than they started. It feels a bit sloppy and incomplete to just fix a monitor to their head.

**Steps to reproduce the problem**:
Fill Exosuit fabricator with metal and glass, head to misc, print out the replacement IPC head, pick up the head and then activate in hand.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Can't see anything else affecting this really. Seems like a pretty reliable problem to reproduce.

**Comment by DesolateG** [comment]
Cyborg heads are brandable for synthetic prosthetic purposes. Next time the surgery you want is prostethic limb attachment

**Comment by StreakyHaddock** [comment]
So... you can use cyborg heads to replace IPC heads? Then what's the point of the replacement IPC head?

**Comment by DesolateG** [comment]
You can use it to replace organic heads too.

**Comment by StreakyHaddock** [comment]
this is life changing

**Comment by StreakyHaddock** [comment]
the ipc head seems irrelevant, but cyborg heads can be used as head replacements, so this issue is pointless. (Remove the weird morpheus replacement head!)
