### ISSUE TITLE
META STATION: Windows on the Escape shuttle are indestructible to blunt force

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#7938]
**Problem Description**:
The windows seem to be unbreakable by any mortal means

**What did you expect to happen**: 
To be able to break into the shuttle to get my friends away from a raging plasma fire

**What happened instead**:
Smacked the window with a duel esword for two minutes before having to abandon my friends to a fiery death

**Why is this bad/What are the consequences:**
If escape is compromised people will need to break on board. It also makes hijacking harder when they can only board through the airlocks.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a nuke ops round and I had the disk. I was trying to get the surviving crew on board the shuttle. The syndi suit I had was fire proof, but my friends werent. I smacked the window with a duel esword for a full two minutes before everyone around me died.

**Comment by SamHPurp** [comment]
Funky. I'll have a look.

**Comment by SamHPurp** [comment]
Entirely unable to re-produce.

![image](https://user-images.githubusercontent.com/7415122/28996219-8783fbb6-79f3-11e7-8081-7dd1b885f609.png)

**Comment by ktoma36** [comment]
Not those ones, the shuttle windows

**Comment by ktoma36** [comment]
When the shuttle comes in, the windows are right next to those

**Comment by ktoma36** [comment]
It seems that all the shuttle windows are unbreakable actually

**Comment by SamHPurp** [comment]
I broke literally all windows on the bottom side of the station.

**Comment by alexkar598** [comment]
He's talking about the windows ON the shuttle

**Comment by SamHPurp** [comment]
He said window **TO** the shuttle. Seems to me that isn't the shuttle itself. I'll check that out later.

**Comment by ktoma36** [comment]
Sorry if I didnt make it clear, I am refering the the windows on the shuttle. Sorry about the grammatical mishap

**Comment by FalseIncarnate** [comment]
Shuttle turfs are a strange beast. You can typically unfasten the windows with a screwdriver, and I believe vamp screams can break them, but they don't behave exactly like normal windows. I honestly am not surprised they withstood that beating.
