### ISSUE TITLE
[Bug] Incendiary Mitrochondria has broken targeting

### ISSUE THREAD

**Issue by scrubmcnoob** [ParadiseSS13/Paradise#794]
The unknown power, Incendiary Mitrochondria, will set you on fire every time you attempt to use it even if you try targeting another person. Apparently this is an old bug and would be nice if it could be fixed.

To recreate the bug you simply need to get the power and attempt to set some one on fire then watch yourself burst into flames.

**Comment by Spacemanspark** [comment]
Intentional, actually. It was used for grief and had to be nerfed.

**Comment by Fox-McCloud** [comment]
Yeah, it's not meant to be targeted.

**Comment by scrubmcnoob** [comment]
Well then the Wiki needs to be updated if it is just going to stay jihadi flames and only set yourself on fire.

**Comment by Keilden** [comment]
It should set an entier Opera house audience on fire.

**Comment by scrubmcnoob** [comment]
Whelp closing this then since it is intentional.
