### ISSUE TITLE
Nanotrasen minebots are not affected by EMP

### ISSUE THREAD

**Issue by Squirgenheimer** [ParadiseSS13/Paradise#7946]
**Problem Description**:
Nanotrasen minebots are not affected by EMP pulses of any sort

**What did you expect to happen**: 
Given that they appear in game to be synthetic they should be damaged&stunned, or killed by an EMP pulse. There are no real reasons IC for them not to be affected. 

**What happened instead**:
Nothing happened. The minebot was not damaged or stunned. 

**Why is this bad/What are the consequences:**
When minebots need to be taken out, the method which is most effective for synthetics does not work on them. This could allow groups of minebots to go on rampages easier than rogue borgs given that their KA seems to do significant amount of damage.

**Steps to reproduce the problem**:

1. Create minebot cube

2. Create minebot from minebot cube

3. Use any variety of emp weaponry on the minebot (ion rifle, traitor emp grenade, chemical emp grenade, emp implant, emp talisman)

4. Observe, or if you're in a testing scenario you can assume control over the minebot to see the health it is at.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
None, I think. 
I believe this is due to them being a "simple animal" and possibly having no defined emp_act proc.

**Comment by ktoma36** [comment]
Dear god yes, while at it fix the range damage booster making it them do full damage in pressurized environments
