### ISSUE TITLE
Some items cannot be interacted with with the matter decompiler/trash bag

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#7947]
**Problem Description**:
What is the problem?
Some items cannot be interacted with with the trash bag or the matter decompiler.
The following items are the ones I know of:
- Cup ramen
- Hot drinks machine items
- Glasses (drinking glasses, etc)

**What did you expect to happen**: 
the items are either decompiled or put in a trash bag
Why do you think this is a bug?

Because this did not happen.

**What happened instead**:
Totally nothing. I don't even get a message that the items is too big/small or anything. It's just .. silent. The items is there on the floor, but well, it's just nonexistant to the trash bag or decompiler

How is what happened different from what you expected?
Small trash items should be able to be decompiled or put in a trash bag

**Why is this bad/What are the consequences:**
A filthy station. It also triggers me.

Why do you think this is an important issue?
See above.
**Steps to reproduce the problem**:
Get one of these items, try to decompile or trash bag said item.
The most important section. Review everything you did leading up to causing the issue.
See above.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Nope.

**Comment by FalseIncarnate** [comment]
This probably is because cup ramen and hot drinks products are considered types of drinking glasses. Matter decompiler has very specific things it can decompile (which frankly needs to be cleaned up because it is a disgustingly huge if chain), and trash bags likewise have a set list of things they will collect from the ground. With trash bags, though, I assume you can put those items in manually. An extra step perhaps, but does prevent you from swiping an entire bar rail of drinks with a click.

**Comment by FalseIncarnate** [comment]
I will state that I have made the same mistake trying to decompile those ramen cups and been dismayed I can't clean them as a drone. On the bright side, I don't think they count against station messes uncleaned since they aren't a trash item or cleanable decal

**Comment by Landerlow** [comment]
I don't mind if they count as station mess or not, it's just very crap. It's trash. I want to be able to clean it up. Properly. 

#7954 is related to this issue.

**Comment by tigercat2000** [comment]
This is a feature request- The suggestions forum would be more appropriate for this.
