### ISSUE TITLE
Production Speed is broke

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#7949]
**Problem Description**:
With the new nerf to botany, stats need upgrades before you can get better genes for them in the gene machine. However, out of the gate production speed is capped at 9, and even with upgrades is still capped at 9.

**What did you expect to happen**: 
to be able to get faster production speed (lower number) genes once the machine was upgraded.

**What happened instead**:
Trapped at 9 the whole shift.

**Why is this bad/What are the consequences:**
9 Production speed is worse than damn near every single plant species is by default. Compare this to the 50 potency cap without upgrades, which is _better_ than damn near every species out of the box. I would at least hope to be able to get better genes once science gets around to us.

**Steps to reproduce the problem**:
Extract production speed from wheat without upgrades, upgrade machine, extract again. you will be capped at 9 both times.

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/hydroponics/gene_modder.dm#L344
Yup! You are 100% right! One moment!

**Comment by Jountax** [comment]
Yield also seems to be capped at 8 with upgrades, but 8 is at least still pretty good.

**Comment by Crazylemon64** [comment]
Wait no
did you make sure to upgrade the scanning module

**Comment by Jountax** [comment]
I have no idea, science handles upgrades.

**Comment by Fox-McCloud** [comment]
I just tested this, in game; you need to upgrade the scanning module; once you do, it's absolutely fine.

You need tier 4 parts in order for it to extract *any* value (though potency is still capped at 95)
