### ISSUE TITLE
Detonating mousetrap bombs while unconscious

### ISSUE THREAD

**Issue by tinfoiltophat** [ParadiseSS13/Paradise#7950]
**Problem Description**:
You are able to detonate a mousetrap bomb while incapacitated or in crit.

**What did you expect to happen**: 
To NOT blow up the shuttle with 900u of potassium and water while in crit.

**What happened instead**:
I blew up the shuttle with 900u of potassium and water while in crit.

**Why is this bad/What are the consequences:**
Accidental detonations, and people being able to detonate bombs when they shouldn't be able to.

**Steps to reproduce the problem**:
Step One. Make a grenade or bomb using a mousetrap-igniter assembly as the trigger.
Step Two. Arm the device.
Step Three. Put the bomb in your backpack, or in a box inside your backpack.
Step Four. Have a kind friend (or those fucking space bats) incapacitate you.
Step Five. Look inside your backpack or box.
**Possibly related stuff**:
I know it's not an excuse, but I'm sorry anyway guys.

**Comment by dapocalypse** [comment]
I am unable to get my backpack open while incapacitated. Unable to reproduce.

**Comment by tinfoiltophat** [comment]
Try dragging the backpack onto your sprite rather than clicking, iirc that worked.
