### ISSUE TITLE
VR ISsues and runtimes

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#7951]
This is a bug with the VR console, that while admin spawned still makes some issue that in if you join a room and click cancel while in lobby space..it may delete your mob....thats bad

**Comment by Aurorablade** [comment]
associated runtime

**Comment by Crazylemon64** [comment]
@Aurorablade They're intended to be used inside the VR realm - you're normally intended to use the goggles to get to the lobby

**Comment by Aurorablade** [comment]
ohhhhhh

**Comment by Aurorablade** [comment]
...sometimes the VR will body swap people...

**Comment by Citinited** [comment]
Body swapping is a Feature™️

**Comment by SamHPurp** [comment]
@warior4356

**Comment by JKnutson101** [comment]
Necromancy! Yet it's for a purpose. With #12341 this issue should be closed.
