### ISSUE TITLE
Service Cyborg drinks Shaker can't be inserted inside the soda & booze vendors

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#7953]
**Problem Description**:
Service Cyborg's drinks shaker cannot be inserted inside the Bar's vending machines, so they are stuck using the vending machine, which is a hideously slow and messy way of bartending.

**What did you expect to happen**: 
I'm pretty sure the medical borg can insert their beakers inside chemical machines. Either way, it makes the Service Borg useful only for dispensing glass, dice, shaving heads and regular beer bottles.

**What happened instead**:
The Cyborg Shaker can only be used to hold reagents drawn in with the industrial dropped. Which is terrible.

**Why is this bad/What are the consequences:**
It makes the Service Cyborg kinda useless. They can't prepare drinks using chem heaters, and one may argue that borgs are supposed to be worse than the crew at a particular job, but... come on. It's the SERVICE cyborg. If they can't be a good bartender, then they're literally just useless jokes that are a burden upon their AI.

**Steps to reproduce the problem**:
Be a Service Cyborg. Activate Drinks shaker. Place in Vending machine.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by alexkar598** [comment]
You can't insert the med Borg beaker in a chem dispenser or booze dispenser

**Comment by taukausanake** [comment]
If you were able to then problems would arise. It's best that the borg is not able to interact with machines like that.
Maybe an option is to have a module that gives them the functionality of the drink machines, an addon like other cyborg upgrades

**Comment by Citinited** [comment]
Cyborg shaker synthesizes reagents put inside it; it is most definitely not useless

**Comment by taukausanake** [comment]
@Citinited but then you need an existing drink in order to make a drink? That demands a bartender or shotgun fodder to make a drink first for the borg

**Comment by Citinited** [comment]
@taukausanake I think you underestimate the strength of a reagent container that continuously synthesizes any reagent put into it.

However, for making drinks it's kind of awkward. Perhaps they could have bottles of different alcohols that regenerate, so they could make certain beverages? That would be a feature addition, though.

**Comment by Landerlow** [comment]
@Citinited  that would be nice. Additionally, use this with certain chemicals, for the med borg. As it is, we have to beg for others to put reagents into a container, then take our dropper, then put it into beaker/shaker.  

I would really like to see the service module be more used. And the medical module could also help out in chemistry, a bit.

**Comment by Landerlow** [comment]
Perhaps limit the reagents/drinks to some simple ones. Obviously, do not give medical borgs omnizine because well, I think everyone knows what would happen. If you give them Iron, water, sulfur, oxygen, perhaps a few others, then they could make very basic medicines. Advances medication would still require actual human labor. 

The service module borg currently is the biggest pain in the ass and the least played module, which is sad. Perhaps a new module where a service borg could generate one-bite snacks?? Bar snacks are nice.

**Comment by StreakyHaddock** [comment]
Sure, a reagent container that synthesises eteranlly is powerful. But it's not FUN to serve the bar with.

**Comment by Landerlow** [comment]
Agreed

**Comment by BiancaWilkson** [comment]
Service cyborgs now get around this by having an in-built soda and booze dispenser.
