### ISSUE TITLE
Tray cannot pick up Drinks and Glasses

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#7954]
**Problem Description**:
Kitchen Tray cannot pick up Drinks and Empty Glasses

**What did you expect to happen**: 
It can pick up food. Drinks seems like a natural next step.

**What happened instead**:
I can't pick up drinks.

**Why is this bad/What are the consequences:**
Service Cyborgs are suggested to be more bar focused, and cannot even pick up the drinks they serve.

**Steps to reproduce the problem**:
Be a Service Cyborg, or be a regular guy with a tray. Click on empty glass or full drink with tray in active in hand.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by alexkar598** [comment]
Feature request

**Comment by Citinited** [comment]
Last time I played chef, I definitely remember being able to pick up glasses with trays. I'll take another look though

**Comment by Birdtalon** [comment]
@Citinited he means as a cyborg.

**Comment by tigercat2000** [comment]
Feature request.
