### ISSUE TITLE
Autopsy Scanner stopped functioning

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#7955]
**Problem Description**:
Autopsy Scanner can scan this body and ONLY this body but data can't be printed off.

**What did you expect to happen**: 
To be able to print off my findings. To be able to scan another body to see if it reset whatever's wrong.

**What happened instead**:
Activating the autopsy scanner didn't produce a result. When used on another body, I couldn't scan it. Yet I can use the scanner on his body just fine.

**Why is this bad/What are the consequences:**
It turns the autopsy scanner into a useless brick.

**Steps to reproduce the problem**:
Brainless body with entirely shellguard munitions limbs. Use scanner on head first, then body then try to print. I screwed up the spare scanner by scanning the body first, so it seems replicable.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

He also had mechanical eyes and a mechanical heart.
![brokenautopsy](https://user-images.githubusercontent.com/4000322/29046336-049ce834-7bbf-11e7-99b5-a18b779a2629.png)

**Comment by StreakyHaddock** [comment]
Happened again with another brainless body, though the glitching to the scanners doesn't seem as permanant as I first thought.

**Comment by Pckables** [comment]
Odd to comment on a year old bug report, but it's relevant again.
Tried to autopsy scan a corpse with some standard brute damage all over the body, and a skull fracture, but the autopsy scanner never printed anything. Attempted to use a different scanner, as well as have another person (the CMO) attempt a scan, but yielded no results.

**Comment by Birdtalon** [comment]
Tried to reproduce. The autopsy scanner worked fine on multiple bodies and printed just fine. Do you have any more information?

**Comment by Pckables** [comment]
For whatever reason the bug seems to have dissapeared on its own.
The body was definitely on a surgery table. I have changed no steps between when it wasn't working and when it was. Some bodies worked, some didn't.
Either way, the bug mysteriously vanished, so I guess there is no problem.

**Comment by alex-gh** [comment]
Oh I think the bug is still there. Stumbled upon it while working on #9524 

And I can reproduce it reliably. Spawn as a coroner, spawn in a tajaran, grab a fork from the bar and stab them in the eyes until they die, scan starting from the eyes.

Report can not be printed, and I have no idea why. No runtime errors about it are popping up.

**Comment by Pckables** [comment]
It seems holoparasite attacks are not detected by the autopsy scan either, which explains why I had some bodies with a ton of brute damage but no printable autopsy.

**Comment by ID404-NotFound** [comment]
I've had reports of people not being able to print scans from autopsy scanners, as well as not working for when I tried to myself. Nothing really to go on for it, as there doesnt seem to be anything unusual in any case.
