### ISSUE TITLE
Diona internal bleeding?

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#7959]
**Problem Description**:
Diona showing internal bleeding and blood on Advanced Body Scanner AND the bleeding having no effect.

**What did you expect to happen**: 
I beleive Diona to lack blood and the ability to bleed internally or otherwise.

**What happened instead**:
Showing as having blood and internal bleeding.

**Why is this bad/What are the consequences:**
Muh immursion? Confusion when attempting to repair the damage that isn't in fact doing and damage.

**Steps to reproduce the problem**:
Have a Diona sustain damage that would create internal bleeding. Scan in body scanner 

I have a screenshot if needed

**Comment by ktoma36** [comment]
I've always been bugged by this as well, although it may be an intentional thing done to nerf diona healing since a diona with internal bleeding can not regenerate health. Then again it does make no sense for a creature that has no blood to have internal bleeding.
