### ISSUE TITLE
E-mag is unable to unlock cryostorage

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#7961]
**Problem Description**:
Emag can't unlock cryostorage

**What did you expect to happen**: 
To be allowed to retrieve the HoS' gun from cryostorage

**What happened instead**:
I couldn't

**Why is this bad/What are the consequences:**
Because you then need to get an HoP level ID to dispense whatever you need

**Steps to reproduce the problem**:
>Be traitor with goal to take HoS gun
>Have HoS gun in cryostorage
>Buy emag
>Try emagging the oversight console

**Comment by alexkar598** [comment]
FEATURE REQUEST

Murder a head for access :D

**Comment by Fox-McCloud** [comment]
Freature Request, to be honest.
