### ISSUE TITLE
Slimepeople genecheese

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#7964]
**Problem Description**:
Slimepeople can take blind as one of the genetics disability but as they are slimes, they do not go blind.
Functionally they get one free major disability to use for their gene stability.
Same goes for obesity

**What did you expect to happen**: 
To be a fat and blind degenerate

**What happened instead**:
Be a fit and seeing superhero

**Why is this bad/What are the consequences:**
Slimepeople can cheese the system to get superpowers for free

**Steps to reproduce the problem**:
Be slime, get fat and blind gene, enjoy your free gene stability

**Comment by taukausanake** [comment]
Slimes don't have organs, do they? Could that maybe be the problem here? Maybe they should get some basic organs; I think it would be cool to transplant slimeperson eyes into someone

**Comment by KasparoVy** [comment]
The fix would be to have in the code for the gene a check whereby you detect if the mob is of a species that can be fat or has eyes.

**Comment by ktoma36** [comment]
IMO Slimes shouldn't even have bones nor internal bleeding because they are a gelatinous mass of slime. Internal organs would make no sense at all.
 On topic though I do agree that getting free mutations is bad, like Kasparo said a check for if the species is viable for the mutation would be nice

**Comment by tigercat2000** [comment]
Slimes shouldn't be immune to blindness at all, I'm not sure why they are currently. The fact that they don't literally have eyes shouldn't matter, they see somehow.

**Comment by Rumiluntti** [comment]
Apparently you don't see attacklogs when you do this, but otherwise you keep your vision.
Wat...

**Comment by ktoma36** [comment]
Slimes have the benefit of not having internal organs with the downside of cold absolutely destroying them. Also blood loss causing toxic damage instead of oxygen damage too. Being immune to blindness has always been one of the appeals for slime people, not having to worry about welding stuff (does flash you when you do it) and security getting overzealous with flashbangs. Blindness is handled on the eyes correct? Since slimes have no eyes they cant be blind. Do you see the slimes in xenobio having proper eyes?

**Comment by Rumiluntti** [comment]
How is that even relevant in any way?

**Comment by ktoma36** [comment]
@Rumiluntti  I was replying to tigercat's comment and I was a little tired at the time :3

**Comment by Kyep** [comment]
@AffectedArc07 Close this, I've tested it on live by spawning a slimeperson and giving them blindness (DNA Blocks: BLINDNESS) and it does affect them.
