### ISSUE TITLE
Spiderbot Hide doesn't work.

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#7968]
**Problem Description**:
What is the problem? Spiderbots Hide function in the animal tab doesn't work properly.

**What did you expect to happen**: 
Why do you think this is a bug?
They should be able to hide under objects like a drone or other small animal, hence having the ability
**What happened instead**:
How is what happened different from what you expected?
Wasn't able to hide under a table, or be under anything else.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's a bug.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Click to hide "You are now hiding"
Try to go under a table.
Can't go under a table.

**Comment by DesolateG** [comment]
@Fox-McCloud

**Comment by tigercat2000** [comment]
@DesolateG To be clear, are they actually not rendering below tables, or can they not _walk under tables_?

**Comment by DesolateG** [comment]
can't walk under the table
