### ISSUE TITLE
Sink not acknowledging onehandedness

### ISSUE THREAD

**Issue by tinfoiltophat** [ParadiseSS13/Paradise#7970]
**Problem Description**
If you use a sink, and only have one hand, it says "you start washing your hands" instead of "you start washing your hand"

**What did you expect to happen**: 
For the game to acknowledge my disability.

**What happened instead**:
I was mocked. Humiliated. Shunned.

**Why is this bad/What a

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by tinfoiltophat** [comment]
Ahhh shit I hit the button accidentally because mobile sucks and I don't see any edit button so rip

**Comment by tinfoiltophat** [comment]
**steps to reproduce the problem**
1. Get the clown to blow off one of your hands.
2. Wash your hand in a sink
3. Cry.

**Comment by FalseIncarnate** [comment]
How are you washing a single hand effectively anyways? It's like the sound of one hand clapping...

**Comment by taukausanake** [comment]
Now I just want sinks to abuse one-handed people even more. False does make a point though, but I think that's _exactly_ how you would wash your hand in that case

**Comment by tinfoiltophat** [comment]
Alright, there were a surprising number of results when I googled this. If you're curious, here is how one handed people wash their hands:
https://youtu.be/EjwnBJSBemY

**Comment by FalseIncarnate** [comment]
I am aware they can, I'm mostly saying that I doubt they are quite as quick and effective at it as a two handed person could be in the same timespan.

Though on the topic, would a one-handed person need longer to wash their hands? Would they be able to use the clap emote? How about air guitar?

We can easily fix the grammar on this, but there are plenty of other oddities regarding one-handed characters that are more complex than a single `s`.

**Comment by tinfoiltophat** [comment]
PR dedicated entirely to one handedness when

**Comment by taukausanake** [comment]
I think they can air guitar but they can't clap. This really does require its own PR and research group. I'm going to lose sleep if I think about it too much

**Comment by Sirryan2002** [comment]
this is a feature request not an actual issue.
