### ISSUE TITLE
Missing Surgery options for IPCs

### ISSUE THREAD

**Issue by Very-Soft** [ParadiseSS13/Paradise#7974]
**Problem Description**:
IPCs are missing 3 of their surgery options

**What did you expect to happen**: 
To be able to implant/remove things from IPCs apart from standard components
![expected](https://user-images.githubusercontent.com/24854483/29242526-17fe266c-7f5d-11e7-9ab5-20b22bb58cd3.png)

**What happened instead**:
Those surgery options are missing.
![actual](https://user-images.githubusercontent.com/24854483/29242536-488bb93e-7f5d-11e7-8e41-ded0f5d1c21f.png)

**Why is this bad/What are the consequences:**
Unable to remove implants, store or remove things inside of IPCs, or remove embedded objects.

**Steps to reproduce the problem**:
>Perform surgery on an IPC
>Be confused

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

These options were there in previous updates, but are missing from the latest one. Seems to be independent of any other factors.

**Comment by alexkar598** [comment]
Were you targetting the eyes? If so then its not a bug

**Comment by Very-Soft** [comment]
I targetted the chest, groin, and head. All three are missing these options, where they had them before.

**Comment by MarcellusPye** [comment]
I also had this happen

**Comment by StreakyHaddock** [comment]
they also can't have shadowling tumours removed

**Comment by Aurorablade** [comment]
some surgerys were condensed with the embed refactor and may only show up if a condition is met.
I can remove thermal eye implants, was another implant causing issues?

Shadowling is an issue. investigating now.
