### ISSUE TITLE
Morphism and Polymorphism don't cooperate with skin color

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#7980]
**Problem Description**:
If you use Morphism and Polymorphism in tandem, colors (namely skin/tail color of nonhumans) appears gravely off.

**What did you expect to happen**: 
For me to be able to use Morphism to change my appearance, Polymorphism to change into someone else, Morphism again to change the appearance OVER the new identity, finally Polymorphism again to seamlessly become a new person.

**What happened instead**:
The effects are not consistent, after altering the body of the new identity (using Morphism for the second time) I tried polymorphing into someone new and it locked my skin and tail color to a reddish-grey rather than the purple skin the target had. This skin color could not be changed either through Morphism or Polymorphism.

**Why is this bad/What are the consequences:**
Morphism and Polymorphism should be able to function properly regardless of your appearance or transformations before it.

**Steps to reproduce the problem**:
Be a race other than human (or IPC, sly lads). Get Morphism and Polymorphism (with something like Nearsighted to balance it). Use Polymorphism to become someone else with the same race as you. Use Morphism to change the skin color under the new identity. Use Polymorphism again on another person of the same race without the same skin color.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: All subjects in this experiment were Unathi.

And yes, I know that the process is horribly convoluted, but it happened, because I am a metamorphosing madman (~~Wannabe changeling~~).

**Comment by Spaghetti-bit** [comment]
This is intentional as polymorph is described as you actively focusing on you being like that person. While morph is you changing YOUR appearance.
