### ISSUE TITLE
Emoji's are waaaaay too huge

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#7987]
**Problem Description**:
An emoji in the chat fills the entire box

**What did you expect to happen**: 
for it to be smaller

**What happened instead**:
I got a huuuge one

**Why is this bad/What are the consequences:**
Makes a single OOC message take up a whole chatboxes worth of messages

**Steps to reproduce the problem**:
Start byond, login to SS13 and wait for emoji

![image](https://user-images.githubusercontent.com/589709/29293364-8859c1c6-8153-11e7-878b-9d92e133d585.png)

**Comment by Joonasm** [comment]
Unless they been doing that every single time i've been on for the past few months. probably. Havent had a time when they did display correctly

**Comment by SamHPurp** [comment]
🤔

**Comment by taukausanake** [comment]
:thinking: Interesting indeed

**Comment by Fox-McCloud** [comment]
🤔

**Comment by Birdtalon** [comment]
🤔

**Comment by KasparoVy** [comment]
:thinking: I've never seen this even once my man.

Windows and i.e. up to date?

**Comment by Joonasm** [comment]
I belive my windows is up to date, on win 10. Been having this problem since emoji's got added

**Comment by taukausanake** [comment]
🤔 Awww @Joonasm you broke the pattern

**Comment by Joonasm** [comment]
🤔 Well uh, i reinstalled windows because unreleated issues and now they seem to work? 🤔

**Comment by FalseIncarnate** [comment]
:thinking: Then can this be closed since it seems to be a system error or at least no longer an issue?

**Comment by SamHPurp** [comment]
🤔 we're done here, lets go home

**Comment by AffectedArc07** [comment]
:thinking:

**Comment by Birdtalon** [comment]
🤔 I thonk this can be closed now.

**Comment by tigercat2000** [comment]
🤔
