### ISSUE TITLE
you can still crash the server by radio spamming

### ISSUE THREAD

**Issue by awesine** [ParadiseSS13/Paradise#7994]
**Problem Description**:
My wgw bind crashed the server

**What did you expect to happen**: 
Crash the server

**What happened instead**:
Crash the server

**Why is this bad/What are the consequences:**
CRASH THE SERVER

**Steps to reproduce the problem**:
Spam wgw with an alt + \ bind

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: CRASH THE SERVER

-- from the guy that crashed your server five minutes ago

**Comment by alexkar598** [comment]
Doesn't the say verb had a cool down ?

**Comment by taukausanake** [comment]
@alexkar598 Yeah, it's called typing what you want to say. /s
I don't know if the say verb has a cooldown. I don't think there was ever a reason to give it one, let alone macro it to the level it would need one. I guess now we do have a reason?

**Comment by SigholtStarsong** [comment]
... Shouldn't this also serve as a confession of intent to break rules by spamming WGW?

**Comment by Birdtalon** [comment]
They already got banned when they crashed the server. It was probably a throwaway anyway.

**Comment by taukausanake** [comment]
The fact it got reported probably means something. Isn't this the same guy after all? 5 minutes of whitehat glory I say. Or maybe grayhat all things considered

**Comment by Shadow-Quill** [comment]
@Anasari Looks like spamming the radio has been fixed.

**Comment by awesine** [comment]
nice
