### ISSUE TITLE
Head texture bug

### ISSUE THREAD

**Issue by iwanesko** [ParadiseSS13/Paradise#7995]
**Problem Description**:
Texture problem

**What did you expect to happen**: 
I thought that the head would have a texture.

**What happened instead**:
 But on the one hand it is, on the other - no

**Why is this bad/What are the consequences:**
So the head is easier to hide, and this can have negative consequences

**Steps to reproduce the problem**:
If you cut off head oh Tajara, then you can see that when moving, or rather, turning, the head of the part of the texture disappears

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the or Anything else you can tell us.

![default](https://user-images.githubusercontent.com/29836662/29569320-5a517208-877d-11e7-9264-9dd5261574f7.png)

**Comment by LightFire53** [comment]
That's their hair style. It's a black pony tail

**Comment by Ralta** [comment]
I think that's what the head looks like upside down, so if you're dragging it it's flipping over. I could be wrong though.

**Comment by iwanesko** [comment]
It's random long hair

**Comment by Fox-McCloud** [comment]
Similar to the other, this is just how the sprite system works.
