### ISSUE TITLE
Tale texture bug

### ISSUE THREAD

**Issue by iwanesko** [ParadiseSS13/Paradise#7996]
**Problem Description**:
If I cut leg Tajara or Vulpkanin, Part of the tail is not displayed. The tail is as if hanging in the air

**What did you expect to happen**: 
Part of the tail is not displayed. The tail is as if hanging in the air

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
Cut the leg of vulpkanine or tajaran and turn his back to the top.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

![1](https://user-images.githubusercontent.com/29836662/29569464-d64be55a-877d-11e7-82b1-ad4fab9b86a1.png)

**Comment by taukausanake** [comment]
Intended. That's how the tail is sprited. Maybe should try fixing that some time, give tails a proper layer

**Comment by Fox-McCloud** [comment]
>give tails a proper layer

It does have its own layer; that's not the issue in question. It's more of a limitation of the overall system of how sprites work, in general. 

I don't think this is really possible to fix, in the slightest.

**Comment by Fox-McCloud** [comment]
Closing this; this isn't really possible to fix; tails do have their own layer, but their placement has to be in particular spots for it to build properly--likewise, overlap is generally to be avoided as it can cause blending issues...as such, this is an unfortunate issue that will have to remain for the time being.
