### ISSUE TITLE
Laughter demons (and possibly slaughter demons) Can hit pods as fast as they can click

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#8006]
**Problem Description**:
What is the problem?
A laughter demon ripped my pod to shreds in quite literally a second
**What did you expect to happen**: 
Why do you think this is a bug?
I thought I was going to be able to keep a laughter demon off a person long enough for them to hop in the passenger seat of my pod
**What happened instead**:
How is what happened different from what you expected?
My pod instantly got lit up as around 9 alerts came up at once about getting attacked. I bailed and it blew up shortly afterwards
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Demons shouldnt be able to destroy a pod in an instant by spam clicking
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Get a pod, get a demon, have it spam click the pod til fireworks happen
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Wizard round, was just about to head out exploring when a man came screaming in with a demon on his tail.

**Comment by Gummin** [comment]
Whoops.

**Comment by Citinited** [comment]
Same goes for a lot of other mobs such as terror spiders.

**Comment by matt81093** [comment]
I'm curious if mobs in general are supposed to have a melee click delay when attacking.

**Comment by taukausanake** [comment]
Technically everything should have a click delay/cooldown. If they don't then it's most likely an issue unless it's too meme to get rid of

**Comment by ktoma36** [comment]
Is it an issue with the mobs or pods in general? Also I noticed that xenos could hit apcs as fast as they could click, though it was a while ago so it could of been fixed

**Comment by alexkar598** [comment]
Time to get that sweet autoclicker/macro!

**Comment by matt81093** [comment]
@tigercat2000 should all attacks have a click delay?

**Comment by MarsM0nd** [comment]
Issue still persist, and to answer the question if it's any simple_animal mob, that's the case, if they can attack, a player can attack as fast as they can click.
