### ISSUE TITLE
Terror spider web can get you stuck through a wall/ window

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#8027]
**Problem Description**:
What is the problem?
I got caught in a terror spider web that was inside the station... from outside the station
**What did you expect to happen**: 
To be able to space walk around the station to scope out spiders with xray

**What happened instead**:
I got stuck in a web somehow in space and a spider busted through a wall to kill me

**Why is this bad/What are the consequences:**
Webs arent meant to go through walls/windows (I was too surprised at the time to notice which one it was.)

**Steps to reproduce the problem**:
Space walk outside the station with terror webs filling the maint (Will include pic to sho what I mean). Just hug the wall as you go by

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was the clown, had xray, remote view, and a jetpack on. Terror spiders showed up obviously

![for bug report](https://user-images.githubusercontent.com/10539415/29879996-aa6b44e2-8d74-11e7-9c2a-abef5d1bd79d.png)
 Where the backpack is is where I was caught in a web. As you can see there is no web there. The walls were there when it happened (queen terror spider busted them down when they saw me collapse). I really have no idea why or even how it happened

**Comment by Kyep** [comment]
Terror spiders can't spin webs in space. (Just tested, and confirmed)

I have no idea how a web even got there.

**Comment by tigercat2000** [comment]
Very weird.

**Comment by ktoma36** [comment]
Yeah, when it happened I just sat there dumbfounded. I ahelped to see if an admin could save a copy of the logs for review, though never got a response (I do know that they are not supposed to share logs to regular players)

**Comment by Kyep** [comment]
This should be closed, I've not seen it happen in a very long time, I am pretty certain it was fixed.

**Comment by ktoma36** [comment]
This is still open? Ima close it
