### ISSUE TITLE
Suicidal Cyborgs

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#8028]
**Problem Description**:
A suiciding cyborg can get oxygen damage, no outside clue that they did suicide, and what the damage would be.

**What did you expect to happen**: 
The cyborg to give some message about internal processor error that fried something, and you would need to remove the brain to salvage the chassis or so.

**What happened instead**:
All that gets shown is:
> It looks barely operational.
> It looks like its system is corrupted and requires a reset.

**Why is this bad/What are the consequences:**
A roboticist will try to revive the cyborg, and fails.

**Steps to reproduce the problem**:
Get a cyborg, let them suicide.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The cyborg wasn't rebootable after some oxygen damage was removed.

**Comment by Ralta** [comment]
Oh, is THAT what was happening last night? I was wondering why the restart didn't fix it when you were talking to that guy.
