### ISSUE TITLE
Ai hologram affected by no gravity

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#8029]
**Problem Description**:
What is the problem?
Ai holograms are affected by 0 gravity 

**What did you expect to happen**: 
Why do you think this is a bug?
To not be affected

**What happened instead**:
How is what happened different from what you expected?
Floaty ai holograms!

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Be ai
Get no grav
Move as hologram
See your hologram go away
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Twinmold93** [comment]
Do you mean it continues to move even after you stop moving or just the float effect?

**Comment by alexkar598** [comment]
I meant that it continues to float away when I stop moving

On 2017-08-31, at 4:00 PM, "Twinmold93" <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean it continues to move even after you stop moving or just the float effect?

**Comment by Contrabang** [comment]
Fixed at some point, hologram are no longer affected by no gravity
