### ISSUE TITLE
Flashes need a cooldown on use.

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#8034]
The flashes that sec officers, borgs, and command get are too effective at blinding shadowlings because they can just spam click on or even just near the shadowling and flash them multiple times in a second.  Because of the shadowlings vulnerability to light, the flash will easily blind the shadowling without even burning out.  I have no problem with flashes being able to blind a shadowling when used enough times, but the fact that any security officer or borg that gets near a shadowling can effectively and easily blind a shadowling is silly.  Shadowlings have no means to protect themselves against flashes like normal crew do other then having a thrall install a welding shield implant I think.  I'm not able to code so I hope someone sees this and can open a PR for me.  I found the code for the flash, it's here: https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/devices/flash.dm
I was thinking of a cooldown of like a second or half a second.  It shouldn't effect how they are used in other situations and at the same time prevent sec and borgs from being able to instantly blind shadowlings.  Thank you for reading.

**Comment by Fox-McCloud** [comment]
Feature/balance request, and one that's unlikely to be adjusted.

Shadowlings are meant to be weak to flashes and other lights form, and likewise, flashes burn out VERY rapidly if you spam them.

**Comment by Sollessa** [comment]
I'd like a little more respect with the tags please.  I didn't post this because I was angry.  I posted it because I think it's unbalanced..

**Comment by SamHPurp** [comment]
Snark is only allowed from Maintainers on Github.

**Comment by matt81093** [comment]
As an aside, I wonder if flashes should have an incredibly low chance to.. not flash.
