### ISSUE TITLE
medibot emergency announcement "follow" button not working properly

### ISSUE THREAD

**Issue by McRamon** [ParadiseSS13/Paradise#8035]
**Problem Description**:
As a ghost, after clicking "follow" in medibot emergency announcement instead of teleporting to medibot location it teleports to paradise welcome picture sprite location somewhere in space. 

**What did you expect to happen**: 
i believe  i should have been teleported to medibot location

**Why is this bad/What are the consequences:**
button not working as expected

**Steps to reproduce the problem**:
Be ghost. Wait for " [Medical]  (Medibot) (follow) says, "Medical emergency! Spessman is in critical condition at the Aft Primary Hallway!". Press "follow"
not sure either all locations are being affected or aft primary hallway only or maybe even some special part of it.
![bug](https://user-images.githubusercontent.com/31545294/29977591-97c2d368-8f46-11e7-8765-c97b8497d676.png)

**Comment by alexkar598** [comment]
It happens on all bots including beepsky

**Comment by Sirryan2002** [comment]
cannot reproduce

**Comment by Contrabang** [comment]
Fixed sometime, the follow on medbots and security bots are fixed
