### ISSUE TITLE
Plasmamen Shadowling Thralls not showing as being thralls

### ISSUE THREAD

**Issue by Balthusdire** [ParadiseSS13/Paradise#8049]
**Problem Description**:
Examining a thralled plasmanman in a sling round does not show anything that indicates they are a thrall, with or without their suit on.

**What did you expect to happen**: 
Examining an unmasked person shows if their facial features are drawn and tight or not.

**What happened instead**:
A thralled plasmaman did not have drawn and tight facial features.

**Why is this bad/What are the consequences:**
Thralled plasmamen are undetectable.

**Steps to reproduce the problem**:
Enthrall a plasmaman and examine them

**Comment by Citinited** [comment]
Tested this on a local world and was able to see the thrall status of a plasmaman.

It's not their suit that stops you seeing if they are a thrall - what matters is whether their face is obscured. You should be able to see if a plasmaman is a thrall by having them take off their mask, and then examine them.

**Comment by SamHPurp** [comment]
Hey - they probably swapped to a gas mask instead of the breathing mask.

Hidden plasmaman trick I used a lot.

**Comment by tigercat2000** [comment]
As detailed, it's not a bug.
