### ISSUE TITLE
Nuke ops internal organs

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#8056]
**Problem Description**:
Half the time I'm a nuke op I die to friendly EMP because my regular character's mechanical heart carries into the Nuke op

**What did you expect to happen**: 
Not need to be deathly afraid of EMP the rare few times I'm able to be a Nuke op (about a half dozen times in nearly a year)

**What happened instead**:
Die to EMP, ruin the round for myself as well as the other nuke ops who now have reduced manpower.

**Why is this bad/What are the consequences:**
Same as above.

**Steps to reproduce the problem**:
Have a mechanical heart in character preferences, spawn as nuke op, eventually get EMPed by accident.

**Possibly related stuff**: I've been told by admins in the past to have the heart removed via AHELP at the beginning of the round. Any time I've asked for this the admins available don't know how to do it.

Make it so nuke ops spawn as a generic human with no mechanical parts or organs.

**Comment by Ty-Omaha** [comment]
Should probably do this with wizards as well 

> after seeing a wizard EMP himself in the den and die

**Comment by ZN23XZ** [comment]
Yea like any role where you spawn as something completely different from your normal self. Would I keep my mechanical heart as an abductor? Vox raider? (I'm aware those are nearly non existent)
When I respawn as ERT do I have a mechanical heart or does it only count for round start spawning?

**Comment by taukausanake** [comment]
I thought this was touched up on before, or was that only with disabilities? It should have been for organs too

**Comment by ktoma36** [comment]
I agree for any role that is completely different from your regular character. Wizards though use the character you have loaded though, so I dont really see why that is an issue :3. 

Also I thought this issue was looked at before, but looking back there have been no PR's to fix it

**Comment by tigercat2000** [comment]
Character loading code is a truly a pain in the neck.

**Comment by ZN23XZ** [comment]
I have a fix for this so this can be closed.
When I spawn as a nukie or wizard I'll contact admins with instructions.
Right click my mob
View Variables
In the top right drop down, click add organ
In the list find and select "obj/item/organ/internal/heart"
Doing this overwrites my mechanical heart with an organic one. Nothing visibly happens to my mob. I no longer die to EMP  (tested) It's seamless. 
Even tested it as a Nukie to make sure it won't trigger my explosives. It doesn't.
👌

**Comment by ZN23XZ** [comment]
I didn't close this myself just in case you still wanted to try to sort this out but for my purposes I'm all set.
