### ISSUE TITLE
A glitch in the matrix

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#8060]
Ok so here is what happened from beginning to end, after getting gibbed during surgery the overlay for my body was still there. The reason I got gibbed was from a terror spider egg stuck in me by a spider from the gateway. The Cmo had a crazy idea, taking the overlay and setting it off to the side of surgery. They proceeded to get robotic limbs and organs from storage (previously harvested from bodies in the morgue). They put my gibbed body, which was just an overlay only visable with huds, back onto the surgery table and proceeded to shove back in all the vital organs (including the cortial sac since I was a vox). After doing so they put my brain back in the body and resurrected me with SR. I was able to pick stuff up, talk, interact with things yet I was unable to move nor was I visible on anything other than huds. After ahelping I was told by a flabbergasted admin that I technically didn't exist. They teleported me to the admin testing zone where we did some funny test together. It turns out I could not die in that state even when my health went lower than -100. I could be tased and shot with or without huds as well. I was also able to grab said admin into a strangle hold. After the shenanagens were done he tried to change me into a standard vox mob... which turned me into a stark white human. This did not get rid of the overlay body as well. All in all strange. The admin that was with me was Spacemanspark. 

**Problem Description**:
Gibbed bodies can leave an overlay if the person gibs mid surgery

**What did you expect to happen**: 
Gibbed, nothing left

**What happened instead**:
The doctor was able to implant my brain back into my none existent body... leading to a lot of weird things

**Why is this bad/What are the consequences:**
Its not really, just something really weird that may cause issues later. It could be used to do some funny things I guess

**Steps to reproduce the problem**:
Read through the top, portion

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a cult round, I was a vox, and terror spiders from the gateway put eggs in me which gibbed me on station mid surgery

**Comment by SamHPurp** [comment]
Ya'll are nuts.

**Comment by warior4356** [comment]
So to surmise for testing, gib someone while surgery is going on.

**Comment by Kyep** [comment]
Um, could you please edit this, and use the template? It would be way, way more readable if you did.

**Comment by taukausanake** [comment]
I think this is readable enough as it is. Also very _very_ amusing. I want to see the underlining cause of this

**Comment by ktoma36** [comment]
@Kyep Added the template, though I really didnt know how to describe the problem through it in the first place.

**Comment by Sirryan2002** [comment]
yet to see this bug reproduced, it's also been 5 years, closing
