### ISSUE TITLE
Shitter changelings transform sting people into [x popular metaplayer here]

### ISSUE THREAD

**Issue by Fishocalypse** [ParadiseSS13/Paradise#807]
jesus fucking christ this is annoying and should be reworked

EVERY FUCKING CHANGELING ROUND.

**Comment by Iamgoofball** [comment]
sounds like you need to Git Gud(tm)

**Comment by Fishocalypse** [comment]
But I play the shitter races that powergame and are unable to be transformed


it's annoying watching 90% of the station become the same person

**Comment by Iamgoofball** [comment]
well that sounds like a personal problem

**Comment by Fishocalypse** [comment]
i am triggered by this situation

**Comment by Fox-McCloud** [comment]
And people wonder why I've pushed for homogenization of races when comments like that get thrown out there.

**Comment by theColdflame** [comment]
make it use the genome

problem solved
