### ISSUE TITLE
Crew leaving the station and cult summoning their god results in cult victory

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#8070]
**Problem Description**:
If the crew manage to successfully evacuate the station and those couple pesky cult left manage to band together and summon their god, it results in a cult major victory.

**What did you expect to happen**: 
The crew managed to successfully evacuate, the shuttle has left, the cult just cheesed it in the last two minutes. Either it should be a crew victory or a draw.

**What happened instead**:
Game results in cult major victory, which equals a lot of OOC salt from both sides, admins telling everyone's it's a bug and so forth.

**Why is this bad/What are the consequences:**
People are confused about who won and both sides feel butt hurt over it. Plus, it adds an easy victory solution to the cult; convert everyone, do objectives, then camp off station and wait for crew to leave before summoning, win everytime.

**Steps to reproduce the problem**:
Call the emergency shuttle, have it leave with the crew and while it is in transit back to CC, summon thy cult god.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I mean, it was the slaughter demon god, I dunno if that meant anything but probably not. Staff and players were saying it was a bug that they won while other players celebrated the cult cheese.

**Comment by taukausanake** [comment]
Technically it would be a cult victory I think, unless the shuttle leaving forfeits the cult summoning ritual which I would think it does. For a case like this I'd make it Cult Major Victory and Crew Minor Victory for getting away. How long is that god supposed to be hanging around anyways? Forever? Until CC thinks a BSA might be fun to try? Or maybe it can only manifest for a short time. Lore kind of comes into play here to make a decision

**Comment by FalseIncarnate** [comment]
To be fair, the cult's objectives in that case are to simply summon their god, not to kill everyone on the station by doing so.

I don't see this as a bug so much as people being upset they left enough cultists behind to let them finish the job in solitude.

**Comment by Spartan6** [comment]
It was a one off that appeared to not upset people because they were told it was a bug. 

What's to stop this happening every round if we just accept it's the norm? Much easier to wait until the shuttle is gone and then do it rather than fight the crew.

**Comment by FalseIncarnate** [comment]
Its unintended gameplay perhaps, but that doesn't make it an outright bug. Its easily corrected by checking various world and shuttle states, I'm just saying that as it stands there is nothing to prevent this so it's not a bug in the sense that there is no code acting incorrectly, but rather just a case that wasn't considered.

**Comment by Spartan6** [comment]
Well, that doesn't make it not an issue...

**Comment by DesolateG** [comment]
The real cheese is calling the shuttle.

**Comment by SamHPurp** [comment]
The goal is to summon the god, not murder everyone. So if they've summoned while the shuttle is travelling back to Centcom... that is indeed still a victory for the Cult......... This is not an issue.
