### ISSUE TITLE
you can switch with the ai if you are in help intent regardless of the bolted status of the ai

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#8071]
**Problem Description**:
What is the problem?
you can switch with the ai if you are in help intent regardless of the bolted status of the ai

**What did you expect to happen**: 
Why do you think this is a bug?
cause its bolted

**What happened instead**:
How is what happened different from what you expected?
I EXEPTED THE AI TO BE BOLTED

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
cause you can steal the ai with enough time

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
get to help intent 
smack your face against the ai
look

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by scrubmcnoob** [comment]
Can't reproduce.

**Comment by alexkar598** [comment]
just tested now,you cant switch tiles wiht it when its an empty ai core but when its filled with an ai you can

**Comment by Vivalas** [comment]
Can confirm this bug, I've almost died to it before by switching with the AI as a wizard.

**Comment by TDSSS** [comment]
Likely related to/caused by the same thing as #3346
