### ISSUE TITLE
Kidan Bioluminescence doesn't work.

### ISSUE THREAD

**Issue by VeryDankestMeme** [ParadiseSS13/Paradise#8073]
**Problem Description**:
What is the problem?
Kidan Bioluminescence doesn't work.

**What did you expect to happen**: 
Why do you think this is a bug?
To make light.

**What happened instead**:
How is what happened different from what you expected?
I didn't make light.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
I can't make light.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Play kidan, try to use bioluminescence, fail horribly.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It's happened every game I've played since bioluminescence was added, but only for me. I have seen other kidan use the feature fine but it doesn't work for me. I have tried it with every hunger level and most exosuits, including completely naked, and it just won't work.

**Comment by taukausanake** [comment]
What happened here?
