### ISSUE TITLE
AI Intellicards have cameras

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#8086]
**Problem Description**:
Intellicard with an AI in it will have a camera

**What did you expect to happen**: 
There to be no camera

**What happened instead**:
There was a camera i could tune in centered on the AI card

**Why is this bad/What are the consequences:**
Antags who need to steal a functioning AI will easily be caught

**Steps to reproduce the problem**:
Card an AI, search the camera network for strangely named camera

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I think the AI was EMP'd before carding

**Comment by DesolateG** [comment]
That's interesting

**Comment by moonheart08** [comment]
I'd call this a accidental feature. Just add a disable switch to it for the card's holder.

**Comment by taukausanake** [comment]
I'd remove it. Seems like an oversight if you ask me

**Comment by Contrabang** [comment]
![image](https://user-images.githubusercontent.com/91113370/228079169-9f3e54b1-6096-4684-b9ea-337776ee3466.png)
