### ISSUE TITLE
Other Changling Regenerate Issue

### ISSUE THREAD

**Issue by MasterrExploder** [ParadiseSS13/Paradise#8089]
**Problem Description**:
As a changeling, I dropped into regenerative stasis after a fight, and i was captured by security. While i was in processing my regenerate kicked in, but before i came back i swapped my abilities to better fight my way out. i chose to re-adapt, and after clicking the option i lost all my abilities as normal, but i couldn't pick new ones, and the option to regenerate disappeared.

**What did you expect to happen**: 
i expected to be able to change my abilities while in stasis, and then to still be able to regenerate

**What happened instead**:
i lost all my abilities, remained dead, and was cremated

**Why is this bad/What are the consequences:**
This doesnt sound like an intended function, and if the intent was to prevent changelings from swapping abilities, the option to regenerate should remain, so the changeling isnt stuck in stasis

**Steps to reproduce the problem**:
Die as a changeling, enter stasis, wait til you can regenerate, and then choose the option to re-adapt your abilities.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It was a normal cling round as far as i can tell.

**Comment by scrubmcnoob** [comment]
I think #8137 fixes this.

**Comment by uraniummeltdown** [comment]
It sure does
I would have tagged this issue had I known about it

**Comment by tigercat2000** [comment]
Fixed by #8137
