### ISSUE TITLE
ATM bug?

### ISSUE THREAD

**Issue by Harmony123** [ParadiseSS13/Paradise#8091]
**Problem Description**:
What is the problem?
ATV it does not work ( Unable to connect to accounts database, please retry and if the issue persists contact NanoTrasen IT support)

**What did you expect to happen**: 
Why do you think this is a bug?
I think it's a mistake because I did not find any computer to reconnect ATMs

**What happened instead**:
How is what happened different from what you expected?
There are no fields to enter the password

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
you can not interact with money

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Try to get money out of an ATM

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Gamemode is Secret 
Playing assistant

**Comment by Spacemanspark** [comment]
The ATM system goes down on its own sometimes, it's an intentional in game event.

**Comment by Harmony123** [comment]
how is it repaired?

**Comment by Twinmold93** [comment]
Time. It should, after so long, self-repair (reconnects).
