### ISSUE TITLE
IPCs get Respawnability: No when they ghost, even when they're dead.

### ISSUE THREAD

**Issue by VeryDankestMeme** [ParadiseSS13/Paradise#8096]
**Problem Description**:
What is the problem?
IPCs get Respawnability: No if they ghost, even when dead.

**What did you expect to happen**: 
Why do you think this is a bug?
Ghost and actually have respawnability: Yes

**What happened instead**:
How is what happened different from what you expected?
I got Respawnability: No 

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because it ruins the rest of the round for any IPCs who don't do succumb.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Died on the mining Z-Level while in a straight jacket and cuffs. Died from a borg self-destruct.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I have died as IPC a lot before (super unrobust yay) and NEVER had this happen to me. I died as IPC yesterday and this didn't happen.

**Comment by alexkar598** [comment]
Did it show you a confirmation dialog when you clicked ghost?

**Comment by taukausanake** [comment]
I didn't know you could ever respawn after playing a round

**Comment by alexkar598** [comment]
He means respawnability that shows up in the status menu to say if you can play as a drone/mouse/npc//mid round antag

**Comment by Crazylemon64** [comment]
Re-open if this is still a thing
