### ISSUE TITLE
You can play as a nov when your dead

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#8104]
**Problem Description**:
What is the problem?
Npc means non playable character but I am able to play as a non playable character after I die
**What did you expect to happen**: 
Why do you think this is a bug?
You are PLAYING as a NON PLAYABLE CHRACTER
**What happened instead**:
How is what happened different from what you expected?
It jammed differently
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It hurts my feelings
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Die
See the play as npc button
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Birdtalon** [comment]
Waste of time.

**Comment by alexkar598** [comment]
Well fucked up the title and I'm on mobile,making a other one

**Comment by Birdtalon** [comment]
This isn't a bug.

**Comment by alexkar598** [comment]
Fine I won't make an other one

**Comment by Spacemanspark** [comment]
Was this meant to be a joke or am I not understanding this correctly.

**Comment by alexkar598** [comment]
It's a mix of me being both tired and bored

On 2017-09-15, at 10:09 PM, "Tom Heeren" <notifications@github.com<mailto:notifications@github.com>> wrote:


Was this meant to be a joke or am I not understanding this correctly.
