### ISSUE TITLE
Assorted shower bugs

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#8107]
**Problem Description**:
Showers spawn with the incorrect orientation.

![dreamseeker_2017-09-15_20-21-49](https://user-images.githubusercontent.com/25027759/30499846-fd811b2a-9a53-11e7-9022-7d10236ec227.png)

Mist effects are produced infinitely when the shower is set to "hot" and never despawn

![dreamseeker_2017-09-15_20-23-01](https://user-images.githubusercontent.com/25027759/30499890-1dc56648-9a54-11e7-85c2-bfc09c6c0b12.png)

**Why is this bad/What are the consequences:**
It's a bug

**Steps to reproduce the problem**:
Load the map. Showers seem to spawn in the incorrect orientation, despite showing correctly in DM.

![dreammaker_2017-09-15_20-27-53](https://user-images.githubusercontent.com/25027759/30499957-61766da6-9a54-11e7-9a74-66beb839ffc5.png)

Use a wrench twice to set the shower to "hot."
Turn the shower on and off again as many times as desired to generate "mist" objects.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by Birdtalon** [comment]
@FalseIncarnate related to #7827 ?

**Comment by FalseIncarnate** [comment]
The showers already were floating like that, as confirmed in the comments for https://github.com/ParadiseSS13/Paradise/pull/7856

At some point they ended up having their offsets messed with or something. I'll look into fixing that at some point in the near future as that likely will take a map-edit to correct.

As for the mist, I apparently deleted a check for if mist is associated with the shower prior to creating a new one. Easy fix, stupid mistake.
