### ISSUE TITLE
Text bug with IPC extension APC 

### ISSUE THREAD

**Issue by Harmony123** [ParadiseSS13/Paradise#8110]
**Problem Description**:
What is the problem?
When you try to use the extension feed with an apc in IPC race, you get this message
The implant doesn't respond. It seems to be broken. (is organ, no implant)
problems and confusion when it comes to repair

**What did you expect to happen**: 
Why do you think this is a bug?
because the description is wrong

**What happened instead**:
How is what happened different from what you expected?
problems and confusion when it comes to repair

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
because it causes confusion

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
try repair with wiki guide
(Removing implants from the body. Also removal of things from body cavities.)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Secret
Playing robotic

**Comment by Spacemanspark** [comment]
You probably got EMP'd or heavily damaged.

**Comment by alexkar598** [comment]
I think hes saying that the message tells you that it is an implant while its actually an "organ"

**Comment by Harmony123** [comment]
alexkar598 Right

**Comment by taukausanake** [comment]
Well I don't remember organs not being organ-ic so that might be the issue. Or it could be intended. I'm thinking the latter

**Comment by Crazylemon64** [comment]
There's "Implants" the thing used by the implanter and "Implants" the cybernetic implants that are actually organs. The latter need a good differentiating term to reduce confusion, but this is not a bug.
