### ISSUE TITLE
VV Attack Log

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#8115]
**Problem Description**:
It appears that the attack logs have been sanitized. This changes them from their lovely coloured state into a less lovely pure black state with HTML tags

**What did you expect to happen**: 
To see the aesthetically pleasing attack log section of the VV of a mob

**What happened instead**:
https://i.gyazo.com/d33edf507b41ed74f5eff94e104e95b5.png

**Why is this bad/What are the consequences:**
Change is bad.

**Steps to reproduce the problem**:
1. Find a mob with attack logs
2. VV the mob and search for the attack logs variable
3. ???
4. Profit

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by tigercat2000** [comment]
Incase I don't get this tomorrow, it's trivial to fix: just add
```dm
if("attack_log")
     return debug_variable(var_name, vars[var_name], 0, src, sanitize = FALSE)
```
to this switch https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/datumvars.dm#L36
