### ISSUE TITLE
Plasmaman Warden unable to set cell time??

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#8120]
**Problem Description**:
As warden who is plasmaman, I cannot seem to set up cell timers for in-mates.

**What did you expect to happen**: 
Timer to count down after name and crime was inputted.

**What happened instead**:
Screen is blank but sheet prints stating it was set. No timer is set. Timer countdown on screen is at zero

**Why is this bad/What are the consequences:**
As warden unable to fulfill job

**Steps to reproduce the problem**:
Be plasmaman, be warden.
Lock locker by yourself, not with timer.
manually close windoor, not with timer.
Select ANY cell timer, input crime and name.
Press start timer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Changeling.

**Comment by Birdtalon** [comment]
Have you tried to re-create this in another round or locally? Race should have absolutely no impact on this feature.

**Comment by Birdtalon** [comment]
Unable to reproduce locally with multiple plasmaman characters.
