### ISSUE TITLE
Synthesizer (Instrument) is broken

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#8121]
**Problem Description**:
What is the problem?
Synthesizer is unable to have the instrument its emulating be changed 
**What did you expect to happen**: 
Why do you think this is a bug?
The synth is supposed to be able to imitate all instruments 
**What happened instead**:
How is what happened different from what you expected?
Its just a mobile piano (which is still nice but not what I wanted)
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
The reason for its existence isnt working :3
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Buy a synthesizer, realize it can only be a piano
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Birdtalon** [comment]
Unable to re-produce. The feature is working correctly.

![dreamseeker_2017-09-20_18-09-52](https://user-images.githubusercontent.com/25027759/30657277-ebfb30d2-9e2e-11e7-9f26-bdbc2392a379.png)

![dreamseeker_2017-09-20_18-10-23](https://user-images.githubusercontent.com/25027759/30657290-fb8da2be-9e2e-11e7-8779-a6cf7a128217.png)
