### ISSUE TITLE
Abductors using cuffed crew as disguises

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#8128]
**Problem Description**:
If the Abductor Agent uses a crew member who was cuffed at time of disguise capture, then they can run around as someone who appears cuffed but is in fact totally mobile.

**What did you expect to happen**: 
I'm honestly not sure. This is something that's clearly abusable but given the way the abductor disguises work, it's happening exactly as it should. Not show cuffs on the disguise? I

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**

It feels a bit meta. Head to the brig via cameras, wait for someone to get cuffed and since the disguise is re-usable you basically have an almost perfect disguise that is going to fool the vast majority of people into thinking you're totally harmless.

**Steps to reproduce the problem**:
Honestly not sure. I've never played scientist. My guess is you get the disguise while the guy is cuffed and then you can apply it to the agent at will.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the o
![cuffedabductor](https://user-images.githubusercontent.com/4000322/30775986-f06389f8-a095-11e7-8328-41a5cbf534c5.png)
rdinary happening?)**: Anything else you can tell us.

**Comment by tigercat2000** [comment]
I'm not sure there's any way to fix this, handcuffs are baked into the human sprites. Abductors only use the final render, not the overlays individually.

**Comment by StreakyHaddock** [comment]
that's kinda what i suspected.

**Comment by Varghh** [comment]
For me it's a good feature, i had caught people sitting in a chair cuffed, they just get close to "uncuff" you and you get them.

**Comment by scrubmcnoob** [comment]
I feel like this is a feature for the advance alien image technology and not a bug. Crew should be able to discern a guy opening a door with fake cuffs on.

**Comment by taukausanake** [comment]
Yeah, this sounds like a feature. I would totally meta as someone who is cuffed just to trick them into getting close. Also how often are you going to disguise as someone who is cuffed? Heck, maybe disguise as the person you just trapped and chain them, but I've never played abductor so I wouldn't know if that's possible to micro

**Comment by Fox-McCloud** [comment]
Yeah, this can't really be fixed, and it definitely has a few advantages with it too "oh, a cuffed guy..."
