### ISSUE TITLE
Blood type: Purple Short-sleeved Shirt

### ISSUE THREAD

**Issue by ProcessedSpecimen** [ParadiseSS13/Paradise#8133]
**Problem Description**:
Someone died and I was planning on extracting their blood as the coronor for use if we run out, when trying to find out what blood type they were I found their blood type was listed as "Purple Short-sleeved Shirt".

**What did you expect to happen**: 
I expected A, B, AB or O plus or negative

**What happened instead**:
They had a blood type of Purple Short-sleeved Shirt.

**Why is this bad/What are the consequences:**
It's not a blood type i've ever heard of.. And it could potentially cause problems when transfusing blood to and from them.

**Steps to reproduce the problem**:
I'm not too sure on this one, the person's name was Boris Boris, so do whatever Boris Boris did when they set up their character. Scan them with the medical analyzer, look at their blood type.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
The person had been killed by electrode.
![short-sleeved shirt](https://user-images.githubusercontent.com/6432309/30782952-0c721a54-a133-11e7-9213-88c1a6179b4d.png)

**Comment by FalseIncarnate** [comment]
SQL error. When some new character selection thing got added at some point in the past, it wasn't handled properly when updating SQL, leading to this.
