### ISSUE TITLE
Triple AI secret doesn't Triple AI

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#8142]
**Problem Description**:
Using the Triple AI secret in the admin OOC secrets appears to do nothing.

**What did you expect to happen**: 
AI hivemind consisting of 3 AI.

**What happened instead**:
Only one empty AI core.

**Why is this bad/What are the consequences:**
I'm being mislead.

**Steps to reproduce the problem**:
1. During round lobby, select the admin secret from the secrets panel "Triple AI" under the OOC secrets
2. Let the games begin
3. Notice absolutely nothing different.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Both rounds I tried this on, the AI core ended up starting empty.

**Comment by FalseIncarnate** [comment]
This COULD have been no AI players were signed up at round start. Hard to say if there is an issue with this if the round starts without any AI anyways.

**Comment by alexkar598** [comment]
Why don't we just remove triple ai?

**Comment by LightFire53** [comment]
It appears it was just a lack of AI candidates... three times in a row...

**Comment by taukausanake** [comment]
I'll join in as Ciri AI more often then. That should be fun
