### ISSUE TITLE
Chainshocking doors

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#8147]
**Problem Description**:
If you electrify a door (through a remote signaller), and then click on the door (with the cover unscrewed), you get shocked, and keep getting shocked untill you are death.

**What did you expect to happen**: 
Getting shocked once, and that's it.

**What happened instead**:
You die instantly without anything you can do against it, besides being insulated.

**Why is this bad/What are the consequences:**
An instakill through rapid shocking, while doors seem to have a delay put on it's shocks itself and on the person getting shocked.

**Steps to reproduce the problem**:
Get a remote signaller, and a second device to send a signall to it. Unscrew the cover, attach the signaller set to recive to the shock wire, activate the signaller, die when you have the wire interface opened, and no shock protection. Keep getting shocked even when you close the interface.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Device used to activate was a PDA, PDAs interface was kept open.

**Comment by taukausanake** [comment]
That sounds amazing. I want to see this in action now

**Comment by Vivalas** [comment]
This might have been related to being pushed around by atmospherics or some other funky move stuff.

**Comment by taukausanake** [comment]
If that's the case then I'm a lot less impressed. Dammit LINDA

**Comment by nicetoolbox** [comment]
When I try to reproduce this, after sending the signal you collapse and the panel closes. Maybe the panel closing is new behavior. So this bug was fixed, unless there is a way to not fall over while being shocked?
