### ISSUE TITLE
Bots from emergency crates are invisible and intangible

### ISSUE THREAD

**Issue by Pathid** [ParadiseSS13/Paradise#8149]
**Problem Description**:
Emergency crates from cargo supposedly contain floorbots and medibots, in addition to gasmasks and oxygen tanks. The bots don't appear to be inside, _however_ they still say voice lines.

**What did you expect to happen**: 
The bots to be visible and to function.

**What happened instead**:
See above.

**Why is this bad/What are the consequences:**
This limits the usefulness of the emergency crate, makes it overpriced for its cost and causes the manifest to be inaccurate.

**Steps to reproduce the problem**:
Order an emergency crate, drag it out of the supply shuttle and open it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing else unusual. Mode was Traitor with some custom objectives. Other crate in the order was a machine prototype crate. As far as I know the same thing happens no matter the circumstances.

**Comment by Birdtalon** [comment]
When you right clicked or alt clicked the crate did it show the bots just with an invisible sprite?

**Comment by Pathid** [comment]
It didn't show them at all, no.
