### ISSUE TITLE
Nar'Sie unfairly withholds the spirits of the sacrificed.

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#8152]
**Problem Description**
Upon sacrificing victims as a cultist, you will receive a message that the victim's soul has been imprisoned within a soulstone, but no soulstone, nor any bound shade, is produced from the ritual. At the end of the round it will also list them as cultists with their bodies destroyed, "Shade of Griff McHarmbaton". 

**What did you expect to happen**: 
To either produce a soul shard with my victim or for NarNar to not lie to me.

**What happened instead**:
It said I captured the spirit, but no stone was produced, and neither was any shade.

**Why is this bad/What are the consequences:**
Either a pretty major bug, or just an issue with unused code being where it shouldn't.

**Steps to reproduce the problem**:
Be cultist.
Murder victim.
Draw rune.
Place victim on rune.
Use rune.
Read chatbox and see that it says their spirit was ripped from them.
Search through pile of gear and see no soulstone.
Cry internally.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I think this is cannibalized from TG code, where sacrificing someone produces a soulshard with their shade trapped within. Doesn't do that for us, but says it does.

**Comment by Pathid** [comment]
This happened to me. It makes you a ghost with a shade sprite for maximum confusion.

**Comment by matttheficus** [comment]
Cult reworked. Stale.
