### ISSUE TITLE
Garbage cans are marginally functional, don't accept items on click

### ISSUE THREAD

**Issue by Pathid** [ParadiseSS13/Paradise#8159]
**Problem Description**:
Garbage cans require you to climb on top of them to put trash in.

**What did you expect to happen**: 
For open garbage cans to accept items the way an open crate or disposal bin would.

**What happened instead**:
Trash in hand doesn't go in. Thrown items bounce off. Items click-dragged from the ground display a "x stuffs y in the garbage can" message and still don't go in.

**Why is this bad/What are the consequences:**
Results in mostly useless garbage cans cluttering up the place in front of the kitchen, at the mining outpost and wherever else they're mapped in.

**Steps to reproduce the problem**:
Try to put garbage in a garbage can without climbing on top of it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Of course it's possible I missed something obvious here but I couldn't get an answer out of mhelp.

**Comment by FalseIncarnate** [comment]
For clarity, what do you mean by "don't go in" when you hold the item and click the can? Do the items not get placed on the can (sorta like a table), or are you expecting them to "disappear" like a disposal chute?

The garbage cans are subtypes of crates, so you have to open it, put the item(s) "on" it, then close it to make them actually be inside it.

**Comment by Pathid** [comment]
> Do the items not get placed on the can (sorta like a table)
Correct.

> The garbage cans are subtypes of crates, so you have to open it, put the item(s) "on" it, then close it to make them actually be inside it.
This doesn't work.

**Comment by Pathid** [comment]
Putting items "on" an open can is the part that doesn't work, for maximum clarity.

**Comment by Ralta** [comment]
Just to check, is this the one at the kitchen? I vaguely recall having a similar issue the other day with a plate - did the usual click on the container like a crate and it didn't accept it. Eventually just chucked it back on the table.

**Comment by Pathid** [comment]
The front of the kitchen has one and there's one in the mining break area.

**Comment by FalseIncarnate** [comment]
Thank you for the clarification. I'll look into this.
