### ISSUE TITLE
Gray Bugged Sprites

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#8174]
I'm going to eschew the templates here given the simplicity of this issue.

Adjusted Sec Masks do not appear from the front, only the sides.
Formal, Corporate and Dispatch Jumpsuits are invisible on greys.
Coroner's Scrubs are invisible on Greys.
Blueshield Uniform is invisible on Greys.
Grey Heads protrude from biohoods and bee hoods.
Head of Personnel formal suit is invisible on greys.
HoS masks have some ugly clipping,
Psychiatrist's Turtleneck is invisible.

I'll add more as I remember them.

**Comment by StreakyHaddock** [comment]
Tan Pants and Blue Navy Suit don't have sprites.

**Comment by StreakyHaddock** [comment]
Went through all the under/rank/ jumpsuits in the admin game panel and checked them for bugged sprites.
Then went through the autodrobe and clothes vendors. All of these are missing grey sprites.

/under/rank/psych
/rank/psych/turtleneck 
/gimmick/rank/captain/suit 
/under/sailordress 
/under/pants/red 
/under/pants/khaki 
/suit_jacket/navy 
/under/soviet 
/under/gladiator 
/under/sundress 
/under/stripeddress 
/rank/centcom/diplomatic 
/under/pants/khaki 
/rank/medical/mortician 
/under/singery
/under/singerb 
/under/jester 

Also Undershirts

/rank/centcom/diplomatic 
/rank/ntrep/skirt 

/rank/security/skirt 
/rank/security/pod_pilot 
/rank/warden/formal 
/rank/head_of_personnel_whimsy 
/rank/blueshield 
/rank/blueshield/skirt 
/under/rank/dispatch 
/rank/security/corp 
/rank/security/formal 
/security/brigphys/skirt

**Comment by datlo** [comment]
The nasa voidsuit helmet does not show up at all on greys. The replica dark and red spacesuit helmet has the regular sprite (the real syndi spacesuit has a grey unique sprite)

**Comment by kugamo** [comment]
I went through this list and they all seem to have sprites, except tan pants. But Kakhi pants do have sprites... beyond that single item they are all good as of now August 2020

**Comment by taukausanake** [comment]
Maybe they don't have their sprite sheets included properly. I can't remember the last time I was going through code and saw Greys included in any sprite sheets list. It's usually just Vox
