### ISSUE TITLE
Of package wrapping and bombs

### ISSUE THREAD

**Issue by RatElemental** [ParadiseSS13/Paradise#8188]
When a bomb goes off inside of a package wrapping (or right when you open it in the case of proximity mines), the bomb sticks around in a glitchy state. Interacting with it like this tends to cause you to be unable to move.

**Why is this bad/What are the consequences:**
Grief potential, I suppose. Also prevents antags from putting bombs in packages.

**Steps to reproduce the problem**:
Make a proximity mine or time bomb, activate their timers and then wrap them. Let the timer run down then open the package. Poke weird ghost bomb until you can't move.

**Comment by Jountax** [comment]
It appears disconnecting and reconnecting fixes the inability to move.

**Comment by taukausanake** [comment]
You sure it's inability to move and not the game window freezing? I ask because of the disconnect/reconnect fixing it, it's a known issue and a Byond one I think too

**Comment by Jountax** [comment]
@taukausanake You can still talk, and hear, and be moved by other people. I once persisted in this state for the rest of the round by scooting another person who'd been affected by it forward, for them to do the same to me.

**Comment by Jountax** [comment]
It may be the case that bombs are just doing this in general.

**Comment by Shadow-Quill** [comment]
@Anasari Can't reproduce.
