### ISSUE TITLE
The CMO has a Flash but no way to block its effects

### ISSUE THREAD

**Issue by AntoneAlpha** [ParadiseSS13/Paradise#8193]
**Problem Description**:
What is the problem?
The CMO has a flash in his locker, but it is pointless because they have no protection from it.

**What did you expect to happen**: 
For the CMO to be-able to effectively use a flash to help in subduing targets, and protect against the bright lights of it.

**What happened instead**:
How is what happened different from what you expected?
Using the flash is pointless because it blinds me, too.

**Why is this bad/What are the consequences:**
All Heads except the CMO can utilize the flash to its fullest potential, why shouldn't the CMO?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Play CMO, look in your locker, or on your person. You have no sunglasses, or welding goggles.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Maybe we could give the CMO an advanced medical HUD, like the Brig Phys has.

**Comment by taukausanake** [comment]
I say give the CMO Medical HUD sunglasses like how the HoS has a SecHUD sunglasses. Blue tinted HUD sunglasses sound niiiiice

**Comment by imsxz** [comment]
This is a feature request, not a bug.
Also advanced health scanner HUD does exist, blueshield and brig phys get them *and yes they are nice, blue tinted sunglasses*.

**Comment by alexkar598** [comment]
Also when you wan to subdue a target click on them using the flash it will not flash yourself or anyone else apart the one you clicked on and it will make them drop the items they hold

**Comment by FalseIncarnate** [comment]
Sounds like a feature request and not a bug.

**Comment by Fox-McCloud** [comment]
Feature request, not a bug. 

The CMO not having a way to block flashes is intentional.

Just because he doens't have a way to block a flash doesn't mean he can't use it against others.

It'd be asinine to suggest that you can't use a firearm because you're not bulletproof, yourself.

You don't have to have protection to use it against someone else or use the AoE flash on it.

If it gets disarmed from you and then you get flashed, that's on you.
