### ISSUE TITLE
Wizard Phylactery Wierdness

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#8199]
**Problem Description**:
Making your phylactery a card and then sticking said card into a deck of cards causes it to remove its special "ensouled" status

**What did you expect to happen**: 
To be able to hide my phylactery cleverly in a deck of cards

**What happened instead**:
My phylactery got deleted and it wouldnt allow me to rise

**Why is this bad/What are the consequences:**
Its something that can make or break a wizard round

**Steps to reproduce the problem**:
Be a wizard, get the soul bind spell, bind soul to card, stick card in deck, pull out every card and realize your phylactery went into nullspace. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was messing around on a test server when I found this bug

**Comment by taukausanake** [comment]
Technically every wizard round is broken. Because you know, it's _wizard_.

Sounds like when you put the card into the deck it deletes the object but make a reference to the card value in the deck? Probably not a bug

**Comment by imsxz** [comment]
I suppose the easy solution would just be to add a check for if the card is a phylactery, and not allow it to be added to the deck.

To fufill this neat idea of hiding a card in the deck, you'd have to make it track individual cards and stuff and I'm too lazy and inexperienced to do that :thinking:

**Comment by Fox-McCloud** [comment]
Not really a good solution to this, to be frank.

It's like complaining about making a specific sheet of metal your phylactory, inserting it back into a stack and then complaining that it didn't save you.

Code wise, we can't make *every* item a direct, inherent unique instance. For the purpose of performance (and sanity and GC purposes...) some things are only created when they're needed, then discarded when they're no longer needed.

Likewise, the alternative (adding unique snowflaked checks everywhere for such items and this spell) is equally as detestable, from a coding standpoint.

My best advice? Stop trying to game the system.
