### ISSUE TITLE
Queen Bee auto-ejects from Hive

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#8202]
**Problem Description**:
When placed inside a hive, the queen bee appears beneath the player instead.

**What did you expect to happen**: 
Without a queen, the hive doesn't produce bees or honey. The Queen is meant to be inside the hive.

**What happened instead**:
Queen Bee appeared beneath me when I placed it in the hive instead.

**Why is this bad/What are the consequences:**

No queen means no bees. Honey has very little use, but bees are /so good/ for increasing potency and yield of plants. I mean, they can also synthesise reagents but that's not why I get them.

**Steps to reproduce the problem**:
Get a queen bee crate from cargo, open it, fill the apiary with honey trays, pick up the queen bee, put her inside.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by Birdtalon** [comment]
On it.
