### ISSUE TITLE
portal gun oversight

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#8209]
**Problem Description**:
What is the problem?
you can make fuel tanks go boomy if you shoot one with the _bluespace wormhole projector_no its a portal gun

**What did you expect to happen**: 
Why do you think this is a bug?
cause its not a laser,its not a bullet, its a hole(worm)

**What happened instead**:
How is what happened different from what you expected?
it got bommy

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
since people with portal guns arent ubvious that they will make harm but people with shotguns and e guns are

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
make a portal gun
find your victim fueltank
shoot it with your portal gun
get bwoinked by an admin because you made the fuel tank go bommmy

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
Is that the `bullet_act()` proc doing its thing again?

**Comment by FalseIncarnate** [comment]
Portal gun fires a beam projectile which does not have `nodamage` set.

Simply setting that var to 1 will make it harmless to the tanks. You can see this in action with the Floral Somatoray which has that var set.

**Comment by Fox-McCloud** [comment]
not a bug.
