### ISSUE TITLE
Respawn as NPC bug/ oversight.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#821]
If you click on observe before a round starts, you can click on 'respawn as NPC' and actually start playing an NPC before the round starts. Perfect for trolling the HoP as Ian by flipping over tables and moving lockers, to see their faces when they actually do spawn in.

**Comment by Midaychi** [comment]
or wait till the round starts and buckle them into their chair as a mouse

**Comment by Spacemanspark** [comment]
This is still a thing.
