### ISSUE TITLE
Outlet Trajectory is Off (Namely at the Recycler)

### ISSUE THREAD

**Issue by RogueYun** [ParadiseSS13/Paradise#8221]
**Problem Description**:
Outlet Trajectory is inconsistent. Possibly it is only Right/Left facing outlets? Possibly only right facing outlets? I did some science and it doesn't always happen this way. Could be purposefully random but if so once a game starts it will always shoot one tile off. I've done some test games where the recycler never misses and I assumed that this bug was patched, but I think it is just inconsistent.

**What did you expect to happen**: 
Why do you think this is a bug?
It prevents some things from functioning as they should, like the recycler never recycling during an entire round.

**What happened instead**:
How is what happened different from what you expected?
I expect outlets to eject objects in a straight line (for the most part, I guess one or two pieces that come out skewed would be okay).

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
My OCD doesn't let me have any peace about it. But it also prevents disposals from doing it's job or possibly messing up the plans of antags if they just want a functioning killbox with chutes/recyclers. Maybe some other engineering projects are hampered by box.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Joined many games, observed, noticed how the right facing outlet in the recycler tends to miss 80% of the the games joined, but if it misses it will miss the rest of the round. I'm sure if you removed some of the walls to the side of an right/left facing outlet you would occasionally have a game where it would be off.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Here is an image. Though I recommend fixing outlets to always aim straight a possible temp fix would be to add a piece of reinforced glass just below the outlet in the recycle room. I'll attach an image and mark it in green. It wouldn't fix the main problem but it would put my OCD to rest.
![outlet_bug](https://user-images.githubusercontent.com/10092955/31411547-379784aa-adcf-11e7-85a9-3679f9b8cfce.png)

**Comment by RogueYun** [comment]
Having the belt on/off also seems to influence it. When it is on it doesn't seem to miss? I'm not sure. It's a tough bug for me to pin down.

**Comment by RogueYun** [comment]
Someone shut the belt off and now it works fine.. I don't know. Maybe I'm going crazy... :/

**Comment by Shadow-Quill** [comment]
Haven't seen this issue in a while.

**Comment by Shadow-Quill** [comment]
@Anasari I think this can be closed.
