### ISSUE TITLE
Autolathe infinite ammo/metal

### ISSUE THREAD

**Issue by imsxz** [ParadiseSS13/Paradise#8232]
**Problem Description**:
Ammo boxes always recycle in autolathe for the full metal amount, even if empty.

**What did you expect to happen**: 
To get little to no metal when I recycle an empty ammo box.

**What happened instead**:
I got the full metal amount that I printed it for returned.

**Why is this bad/What are the consequences:**
So long as you have the metal to print 1 ammo box, you can effectively have infinite reloads for your gun.

**Steps to reproduce the problem**:
1. Print ammo box from an autolathe
2. Fill up a magazine with it, or otherwise remove ammo from the box
3. Click autolathe with ammo box to recycle it
4. Observe that the amount of metal it was recycled for is equal to the amount you printed it for, despite having less ammo in the box.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Blah blah my paracodes outdated I'll update it later, though I'm sure it still works unless I missed a pull request.

**Comment by Anoonki** [comment]
It might be worth mentioning that revolver loaders do the exact same thing.
You can take all the bullets out of the loader in whatever way you want, then put the now empty loader back into the lathe and get the full amount of metal refunded.

**Comment by KingPhilipIII** [comment]
@Anoonki 

That was an intended function I think. I even remember reading somewhere tips for the .357 is that used loaders can be recycled.

**Comment by FalseIncarnate** [comment]
Recycling loaders is intended. The empty loader giving the metal to create a loaded one is likely not (as you are essentially just getting free bullets). Best method would be to probably make the loader or ammo box themselves recycle into a small amount, and then give a "per bullet" return on top of that, so partially full boxes return more than empty ones, and full ones return more than that.
