### ISSUE TITLE
Neat trick to become an Australian in space

### ISSUE THREAD

**Issue by imsxz** [ParadiseSS13/Paradise#8234]
**Problem Description**:
Sprites can get forever:tm: upside down with meatspikes and teleporting 

**What did you expect to happen**: 
I expected my sprite to be upright when I got teleported off the meatspike.

**What happened instead**:
I became an Australian IN SPACE; upside down.

**Why is this bad/What are the consequences:**
muh immersion

**Steps to reproduce the problem**:
1. Meatspike someone/thing/vulpkanin
2. Throw a bluespace crystal at them, or other means of teleporting (I've seen it work with swarmers teleporting people off of them as well, so I'm assuming it works with all teleportation shit)
4. G'day mate

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Something something outdated paracode I'm at school I'll update when I get home. I don't think anything has changed though.

**Comment by taukausanake** [comment]
Sounds like working as intended to me

**Comment by MoreRobustThanYou** [comment]
# G'DAY, MATE

**Comment by Ralta** [comment]
This should be left in. Call it a Feature™

**Comment by Contrabang** [comment]
This is reproduceable still, but with shoving instead I believe.

**Comment by FunnyMan3595** [comment]
Does not reproduce with either shoving or bluespace crystals.

**Comment by Spaghetti-bit** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/60483458/e03593f4-9705-4ed3-ac59-f80e6ec7b3d6)
tested with admin teleporting. You get Un-Australian'd now.
