### ISSUE TITLE
Bola

### ISSUE THREAD

**Issue by IntentEldiablo** [ParadiseSS13/Paradise#8243]
**Problem Description**:
If missing a leg and getting bola'd it is impossible to remove the bola, rendering the person stuck with slow movement

**What did you expect to happen**: 
Nothing, I should not have been able to be bola'd

**What happened instead**:
I was stuck with a permanent bola on me restricting movement unable to remove it

**Why is this bad/What are the consequences:**
Permanent slow movement

**Steps to reproduce the problem**:
I was in space, missing a leg after a pod explosion and i got bola'd by a syndicate agent, after staying still trying remove the bola it would not come off, stuck with slow movement

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tratorlings was the round and nothing special otherwise

**Comment by FalseIncarnate** [comment]
Can't seem to find anything that would prevent you from resisting out of a bola with only one leg, but I think the bigger issue is that you were able to be bola'd in the first place with only one leg.

Shouldn't be too hard to introduce a check into the bola code to ensure the victim is able to be legcuffed (has both legs, isn't legcuffed already) prior to actually legcuffing them (which a bola does). Might also be worth ensuring legcuffs are properly dropping when the leg is removed, just for the sake of sanity and testing.
