### ISSUE TITLE
Pipe connection weirdness 

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#8244]
**Problem Description**:
What is the problem?
If you place a lot of pipes (it only did it on floor with tiles but I haven't tried to put it on plating) there is a chance a pipe will disappear, the pipe will still work and placing a pipe next to it will remove the bug

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Can cause confusion

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Place a shit ton of pipe and wrench me
Watch as one of your pipe enabled a nano cloaking device

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

I checked :

Under the tiles with a crowbar

Under the tiles with a t ray

Asked an admin to see if I'm the only one who had the bug(I wasn't)

Tried using messons(not that I excepted anything)

**Comment by taukausanake** [comment]
This is a known issue. To make the pipe reappear just get a pipe to connect next to it. Updating the icon I think.

Do we even know why this happens?

**Comment by Certhic** [comment]
Fixed

**Comment by Henri215** [comment]
Couldnt replicate, very likely to be fixed.

**Comment by Henri215** [comment]
Issue has been fixed by https://github.com/ParadiseSS13/Paradise/pull/10004.
