### ISSUE TITLE
Atmospherics Pipe Bugs

### ISSUE THREAD

**Issue by Shadeykins** [ParadiseSS13/Paradise#8245]
**Problem Description**:
Certain atmos devices are horrendously broken.

**What did you expect to happen**: 
For them to not be broken.

**What happened instead**:
They've been broken since forever, so they continued to be broken.

**Why is this bad/What are the consequences:**
It makes atmos hell, and pipenets are probably something that shouldn't be easily broken.

**Steps to reproduce the problem**: (Not really steps so much as a holistic listing of issues)
1) Passive vents only reliably work in N and W orientation. They will often break when the connection to them comes from the north (South orientation) or from the West (Easy orientation). Furthermore, passive vents can be obstructed by placing single-pane windows on them in a box formation. This only seems to obstruct when the passive is in SOUTH orientation (with the connection coming from the north).

2) Volume pumps require a gas pump prior to them. Doubling on volume pumps, or a volume pump with no preceding gas pump can break pipenets. The volume pump despite being 'on' will not move any gas whatsoever. This can be fixed by either adding a gas pump somewhere prior in the line, or by removing the volume pump and replacing it with a straight pipe. When it breaks in this fashion, replacing it with any other device won't fix it.

3) Doubling up on valves breaks pipenets. By using multiple valves on the same line you can horrendously break the line, and cause gas to stop moving past the valves.

4) Unary vents set to siphon will occasionally fail to siphon. I'm unsure of the exact reproductive steps for this, because it happens seemingly at random.

5) Air injectors are horrendously broken. They can't be appropriately toggled, and to remove them you need to cut the environmental power from the APC.

6) The TEG has a tendency to mix gas between its hot and cold lines even when they're isolated. This manifests as your cold loop bleeding into your hot loop. It can be reproduced by building a TEG setup using cyclical passive/uvent chambers.

7) The TEG breaks when it exceeds e007 power. It starts spasming, and turning on and off repeatedly.

8) Air injector pipe connections are sometimes misaligned. This can usually be seen over by Toxins, or the AI satellite.

9) Unconnected pipes that are wrenched down lack a sprite, and turn invisible despite being wrenched to the floor.

10) Holding tanks overstate their contents to some degree. It is possible to blow through the stations entire N2, CO2, and N2O supply in half a shift if they're at full draw. This may just be a volume difference, as O2 and Plasma tanks are unaffected by this (you can draw from them at max all shift with no issues).

11) Disposal networks are prone to breaking/stalling their contents at random points. I have absolutely no clue how this one happens, but it manages to get the occasional person stuck in the disposals network from time to time.

12) If you have single-pane windows doubled up on a space tile and an adjacent station tile, crowbarring the floor tile will result in atmosphere being lost to space - despite there being no way for this to actually happen.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A. This is consistent across all round types.

**Comment by FalseIncarnate** [comment]
Possibly related: #8017

**Comment by ktoma36** [comment]
There are a few more things that I have seen happen with atmos recently that made it almost unplayable.

- Sometimes pumps will not function if there are more than two gasses in the pipe

- HE pipes interfere with the placement of uniary and scrubber devices, even though there is no physical reason for it

I have videos showing both these issues if needed

**Comment by Certhic** [comment]
9 is fixed

**Comment by Spaghetti-bit** [comment]
As of MILLA being introduced this issue hasn't been noticed.
