### ISSUE TITLE
Delta Station Brig Fuckery

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#8249]
**Problem Description**:
The prisoner computers on brig cells aren't there.

**What did you expect to happen**: 
For consoles to exist for prisoner management and sentence serving.

**What happened instead**:
I wasn't even security, just running around and I noticed it. I imagine there was a problem but not one I endured.

**Why is this bad/What are the consequences:**
Unless you want to manually time sentences it's a pain in the ass.

**Steps to reproduce the problem**:
Load Delta. Look at map. Cry when the greytide rises.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
So Delta Station isn't even ported yet but there are already issues for it? I thought the maintainers didn't want it?

Also it seems _really weird_ that issues are being made for something we don't really have

**Comment by KingPhilipIII** [comment]
Play test you donk. They ran the map for a round.

**Comment by taukausanake** [comment]
Still feels weird having issues for something that isn't even merged yet. If you're going to you might as well make a `Delta Station` label

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
