### ISSUE TITLE
Delta Station Brig is fucking bad

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#8251]
**Problem Description**:
- No timers on cells.
- There is laughably so few cells.
- The armoury is wide open and laid out terribly.
- There are two brigbays.
- There is a massive security office that serves no purpose.
- There is no processing.
- There is a massive meeting room that serves no purpose.
- CAMERAS DO NOT WORK AAAAA: The Camera console displays zip cameras.

**What did you expect to happen**: 
Brig to function.

**What happened instead**:
*scream

**Why is this bad/What are the consequences:**
*SCREAM

**Steps to reproduce the problem**:
DELTA STATION

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: *DEATHGASP

**Comment by Ty-Omaha** [comment]
Also how the "Magistrate's office" is literally a massive courtroom

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
