### ISSUE TITLE
Deltastation Robotics Metal and glass

### ISSUE THREAD

**Issue by Jfrost6** [ParadiseSS13/Paradise#8252]
**Glass and metal had to be used and welded or wrenched back to be put into the exosuit fabricator**:

**The glass and metal should just go in**: 

**i made an animation as if i was hitting the exosuit fabricator with the metal and glass**:

just replicate it by using the metal and glass that spawns in the delta station robotics lab

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
