### ISSUE TITLE
DeltaStation has no scichem

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#8257]
**Problem Description**:
DeltaStation needs a SciChem

**What did you expect to happen**: 
Paradise is balanced around the assumption that scientists will have access to scichem.

**What happened instead**:
SciChem is not included.

**Why is this bad/What are the consequences:**
Science is very unbalanced.

**Steps to reproduce the problem**:
Load DeltaStation

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: DeltaStation only issue

**Comment by KingPhilipIII** [comment]
A science nerf I can get behind.

**Comment by Fraggloid** [comment]
Scichem's in Xenobio on Delta.

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
