### ISSUE TITLE
Delta Station - Engi outpost shuttle "missing"

### ISSUE THREAD

**Issue by Fraggloid** [ParadiseSS13/Paradise#8258]
**Problem Description**:
https://i.gyazo.com/a8e9d744a68c44a05b719334929672b7.png

**What did you expect to happen**: 
Well, the shuttle should... work.

**What happened instead**:
https://i.gyazo.com/a8e9d744a68c44a05b719334929672b7.png

**Why is this bad/What are the consequences:**
removes Engi outpost functionality

**Steps to reproduce the problem**:
self explanatory

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
