### ISSUE TITLE
DeltaStation isn't balanced for Paradise Station speed.

### ISSUE THREAD

**Issue by AquaVirus** [ParadiseSS13/Paradise#8259]
**Problem Description**:
Title.

**What did you expect to happen**: 
Not taking 5 minutes to get to Hydroponics from the Kitchen.

**What happened instead**:
It took 5 minutes to get to Hydroponics from the Kitchen, or anywhere, really.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
1. Walk around in DeltaStation.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing

**Comment by KingPhilipIII** [comment]
On the record the kitchen and botany are literally right next to each other so either you got lost or you're full of crap.

**Comment by AquaVirus** [comment]
There's still the fact that it's not balanced for Paradise Station speed.
_and yes I got lost_

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
