### ISSUE TITLE
Blob zombies/spores/yellow things are broken, leading to them being overpowered. 

### ISSUE THREAD

**Issue by fj45** [ParadiseSS13/Paradise#826]
Bugs:
They can teleport to bodies, meaning that you can have a body snatched out of your hands, and they can latch on from a screen away. It is almost impossible to drag bodies away.

Balance issues:
The blob summon command gives the blob too much control and allows blob zombies/spores/yellow things to stampede.
Blob zombies/spore/yellow things are ridiculously fast, making aiming and running away impossible. 
Blob zombies/spores/yellow things seem to have very high damage, even against people with high level armour.

Might be a few other things I have missed, but short of it is that to win blob rounds all you need is more blob thingy-mo-bobs.

**Comment by Spacemanspark** [comment]
What really sucks is that the hostile NPC AI likes to go OLE at you and dodge lasers when you fire lasers at it from a distance.
