### ISSUE TITLE
Delta Station: Disposals Destination tags not working (drone?)

### ISSUE THREAD

**Issue by Fraggloid** [ParadiseSS13/Paradise#8260]
**Problem Description**:
See title

**What did you expect to happen**: 
They should work

**What happened instead**:
You're sent to maint disposals.

**Why is this bad/What are the consequences:**
Screws up maint drone travel, and parcel delivery

**Steps to reproduce the problem**:
tag something, toss in disposals.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
