### ISSUE TITLE
Missing Things/Broken Things: Delta

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#8261]
**Problem Description**:
Several things are missing, mostly from maint. And the holodeck doesn't work at all.

1. Starters, rubber duckies are no where to be found on the station at all that I've seen. Like, not a single one. Not in maints, no where. 

2. No secondary booze-o-mat. Now literally impossible to set up your own secondary bar without cargo.

3. Metal. Cargo lacks it at round start.

4. Pretty sure Kitchen lacks an oven?

5. We're missing SEVERAL of the clothes vendors.

6. Cryodorms.

**What did you expect to happen**: 
For this stuff to be there.

**What happened instead**:
It was not.

**Why is this bad/What are the consequences:**
Mostly not really round breaking or anything. I just like the stuff.

**Steps to reproduce the problem**:
Load the map.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: idk

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
