### ISSUE TITLE
Deltastation Atmospherics Panic Syphoning (fastmos)

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#8264]
**Problem Description**:
>Panic siphon an overpressured room
>Have the siphons reset back to scrubbing while the "DEACTIVATE PANIC SIPHON" button remains

**What did you expect to happen**: 
For it to not reset on me

**What happened instead**:
It didn't continue to panic siphon

**Why is this bad/What are the consequences:**
(most) Crew relies on atmospherics to live

**Steps to reproduce the problem**:
Have an overpressured atmospherics department
Go to one of the air alarms and panic siphon
observe scrubber status change back to "Scrubbing" from "Siphoning"
Turn panic siphon off and on again

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Fastmos was on as well

**Comment by Fox-McCloud** [comment]
Report on PR, not here.
