### ISSUE TITLE
Double welding an open closet to dissasemble it deletes your welding tool

### ISSUE THREAD

**Issue by MoocowTG** [ParadiseSS13/Paradise#8267]
**Problem Description**:
If you double click any open closet (like the one you can build with metal) with any welding tool such that there are two progress bars, your welder will be irrecoverably deleted once the disassembly is complete.

**What did you expect to happen**: 
That the closet would disassemble and I would get to keep my welder.

**What happened instead**:
the closet disassembled successfully, but I didn't get to keep my welder.

**Why is this bad/What are the consequences:**
Any welder, no matter how valuable can be deleted accidentally, potentially stranding a person.

**Steps to reproduce the problem**:
Click twice on any open closet with an active welder such that a second progress bar appears during the first progress bar. Reproducible every time.

![2017-10-17_08-59-22](https://user-images.githubusercontent.com/12851666/31676028-349cf860-b31b-11e7-8cff-36f9157db566.gif)

**Comment by FalseIncarnate** [comment]
I suspect (though this is simply from a quick glance at the code, so may be proven wrong by testing or further inspection) that what is happening is that the closet is being deleted in the first progress bar, so the second progress bar fails its `do_after` but do to indentation on the return is then continuing to be placed on the locker's location, which has been moved to nullspace. making it seem as if your welder has somehow deleted itself. If I am correct, removing a single tab will fix this.
