### ISSUE TITLE
Hair Dye Bottles bug.

### ISSUE THREAD

**Issue by bigfatbananacyclops** [ParadiseSS13/Paradise#8268]
**Problem Description**:
Hair dye bottles won't dye people's hair/facial hair to different colours

**What did you expect to happen**: 
I expected it to dye other hairs to different colour.
**What happened instead**:
It did not work and it doesn't dye hair/facial hairs to other colours when it haves a colour from the dye generator

**Why is this bad/What are the consequences:**
I can't even do my barber job gimmicks with these

**Steps to reproduce the problem**:
Tried to dye someone's hair and my hair to a different colour and it did not work, rarely, when i dyed someone's hairs to purple, example, it dyed to complete black.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Was making a barbershop, until i got patients, i noticed it wouldn't dye a thing and it sometimes dye it all to black.

**Comment by Jountax** [comment]
I think the colors are just broken entirely, I tried to get dyed pink as a slime and got dyed black. none of the other colors I picked out worked either.

**Comment by Quantum-M** [comment]
Yeah, it also doesn't work if you due someone's body
