### ISSUE TITLE
Jump to Network doesn't work with new map

### ISSUE THREAD

**Issue by Sancronis** [ParadiseSS13/Paradise#8274]
**Problem Description**:
For the AI jump to network command, the network names do no correspond to locations (Tcomms is the courtroom, research is the chapel, Minisat is Viro).

**What did you expect to happen**: 
Well, I'd expect it to go where it's labelled as.

**What happened instead**:
See Problem description.

**Why is this bad/What are the consequences:**
The AI's response time is extremely limited.

**Steps to reproduce the problem**:
Just use the jump to network command as AI.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything N/A

**Comment by taukausanake** [comment]
If this is for Delta Station you should comment on the actual PR #7770

**Comment by SamHPurp** [comment]
@Sancronis Yep, this has been reported, I'm working on fixing it.

Unfortunately the issue is a dumb one, they don't draw from area name on round start... they have to all be manually set, both the C_name and the network.

Meaning I gotta slowly and methodically edit every single camera.

**Comment by taukausanake** [comment]
@SamHPurp Maybe open a separate PR that does make them operate on area? That would be a much better solution to the issue and it would help out in the long run too for other map edits

**Comment by SamHPurp** [comment]
@taukausanake Issue with that though, is you'd end up with some areas with 3-4 duplicated camera names... so like the long hallways could have 4 cameras with the same name.... whereas if I'm manually tagging them, I can say "Central Hallway Outside Medbay" etc

**Comment by taukausanake** [comment]
@SamHPurp I see your point I guess. That's really shitty, wish there was an easier way

**Comment by Citinited** [comment]
You could do something like `name = "[camera_area] ([x][y])"` to give a unique (though 6-digit) identification string to each camera.

Or do `name = area + rand(1,999)`
