### ISSUE TITLE
Plasma glass panes don't protect from fire

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#8276]
**Problem Description**:
What is the problem?
Fire can spread from a burning plasma mix to a non burning plasma mix through a plasma glass pane

**What did you expect to happen**: 
Why do you think this is a bug?
If they protect air from passing from 1 side to an other why should it not block fire spread

**What happened instead**:
How is what happened different from what you expected?
My plasma and my soul burned

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
I don't know IT COULD SET ATMOS ON FIRE .

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Make a plasma glass room
Put plasma in it
Put plasma outside of it
Set plasma in it on fire
See as the plasma at the exterior starts to catch fire!!!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

It took a bit of time before it spread the fire from inside to outside

Inside pressure was much much much larger than the one on the outside

Glass panes did not break and the burning reaction was stable inside the chamber once the exterior plasma finished burning

**Comment by warior4356** [comment]
Was this a single pane or a full window with a grill?

**Comment by alexkar598** [comment]
Single pane no grille

On 2017-10-18, at 8:51 PM, "warior4356" <notifications@github.com<mailto:notifications@github.com>> wrote:


Was this a single pane or a full window with a grill?

**Comment by Citinited** [comment]
Did you screw the window down?

Also I found a workaround is to rotate the windows 360 before securing them. Not sure why it works but it seems to 🤷‍♂️

**Comment by alexkar598** [comment]
Yes the panes were screwed crowbarred and screwed again

On 2017-10-18, at 9:06 PM, "Citinited" <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you screw the window down?

Also I found a workaround is to rotate the windows 360 before securing them. Not sure why it works but it seems to 🤷‍♂️

**Comment by hal9000PR** [comment]
This was fixed ages ago
