### ISSUE TITLE
Ion rifle in shoulder holster

### ISSUE THREAD

**Issue by PrototypeNitro** [ParadiseSS13/Paradise#8282]
**Problem Description**:
Ion Rifle can fit into the shoulder holster

**What did you expect to happen**: 
Try to put a RIFLE under your shoulder. Even super militay guys can't. Only pistol.

**What happened instead**:
-

**Why is this bad/What are the consequences:**
Antag can abuse of that. Get that into hydro and hide a Rifle. A rifle I mean Pistol ok but Rifle.

**Steps to reproduce the problem**:
Get a shoulder holster and holster the rifle

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Vamp round and he get that ion rifle from his shoulder to robust a borgy. I was a Ghost. No.

**Comment by jughu** [comment]
Feature 

The magic caused by the wizard added a bluespace pocket in the holster
