### ISSUE TITLE
ERT com channel doesn't have a keycode

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#8293]
**Problem Description**:
Each channel in the game should have a key which lets you talk on that channel, including the ERT channel. But there doesn't seem to be one.

**What did you expect to happen**: 
To be able to talk on ERT channels while wearing a headset with access to that channel and to be told what the code is when examining a headset.

**What happened instead**:
You have to use .h or :h to talk on ERT channels as ERT, which is the code for your department's channel.

**Why is this bad/What are the consequences:**
You cannot talk on ERT channels using the normal code. You can talk using .h, I know that. But .h is the code for 'department channel'. It is nothing but a workaround, taking advantage of the fact that ERT members have the department ERT. It also means that examine text of ERT headsets is misleading/useless.

**Steps to reproduce the problem**:
Become an ERT member or simply admin-equip yourself as an ert member. Examine your headset which tells you to use "-", then try using ":-" in order to talk on ERT channels. Find out it doesn't work.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Seems to not work on all gamemodes

EDIT: I was dumb. I misread the examine text. It usually says something like ":c - Command" In the case of ERT, it just lacks the code and just says "- Response Team". Issue has been adjusted. There still should be a letter code to talk on ERT channels.

**Comment by LightFire53** [comment]
:h is for ERT, :- is used by deathsquad for their special ops channel. We have other options for department channels as well. Seems to just be a typo, though

**Comment by TDSSS** [comment]
:h is not for ERTs.
To quote the code:

> 	  ":h" = "department",	"#h" = "department",	".h" = "department",

It is the code you use for whatever your department is.

**Comment by taukausanake** [comment]
I agree with @TDSSS. You really should give them an actual keycode unless the purpose for not having one is so that others can't talk on the channel if they steal a headset. Would be kind of moot though, they'd still be able to listen on it and that's the only thing that matters

**Comment by tigercat2000** [comment]
Resolved by https://github.com/ParadiseSS13/Paradise/pull/8294
