### ISSUE TITLE
Slimes and Surgery

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#8296]
**Problem Description**:
So, apparently I was told that slime people are supposed to be immune to surgical pain for surgery with the recent change? Or in general? I'm not sure, that's what Landerlow and a few others told me. Apparently it's a bug that they DO actually feel surgery pain and they should not. Basically just get surgery as a slime and continue to have the standard fail chance that you have for every other race while being awake during surgery.

**What did you expect to happen**: 
I expected slimes to be immune to the pain from surgery as it makes no real sense that they'd feel it in general as normal slimes do not. Apparently they were supposed to be exempt from it in general and well, it's a bug that they are not.
**What happened instead**:
Having to be dosed with a HUGE amount of painkillers/ether/morphine as a slime in order to receive surgery. Roughly 60u of ether or enough morphine to cause an addiction.

**Why is this bad/What are the consequences:**
Unneeded time in surgery, as I'm 90% sure slime people process chemicals differently leading to the issue with ether/morphine in general. And well, from what I'm told it's a bug anyway.

**Steps to reproduce the problem**:
1. Get broken anything as slime.
2. Go to surgery.
3. Get surgery without anesthetic and good luck fixing it.
4. Need to be pumped full of 60u of ether or 30u+ of morphine.
5. Get an addiction/stay asleep for 10 minutes after as most doctors don't filter it out.
6. Be bored.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Dunno

**Comment by taukausanake** [comment]
> broken anything as slime

That itself should still be a bug. And what are you going to surgery on a slime anyways besides removing their core? There's nothing really inside them, not even eyes. It's _weird_

**Comment by alexkar598** [comment]
Internal bleeding

**Comment by taukausanake** [comment]
@alexkar598 But they're nothing but goo/water inside them. _It's weird_

**Comment by Ziiro** [comment]
Slimes have bones as well.

**Comment by FalseIncarnate** [comment]
Slimes are not a NOPAIN race, whoever told you they should be exempt from the pain surgery fail chance outright lied to you.

They don't have internal organs (except their core) and don't breathe, but they definitely feel pain. Since they don't breathe you would need to resort to chemical anesthetics, like hydrocodone or simple ether.

**Comment by FalseIncarnate** [comment]
For clarity: not a bug, working as intended

**Comment by Ralta** [comment]
For the record, using an IV drip of ether set to 1u works quite well.

**Comment by ktoma36** [comment]
Slimes shouldnt have bones tbh... or at least be able to fix them with their regrow ability. Internal bleeding on a slime person is completely ridiculous as well. Where is their water blood leaking into? Oh, into more of their water blood but instead being drained somehow

**Comment by Landerlow** [comment]
Slimes should not feel pain, according to wiki/lore. Thus, should also not be affected by pain during surgery. Other than that: They have no bones, so the fact that they can get broken bones is stupid. They are *slime*. 

If you find the above too OP, find a drawback perhaps?

**Comment by ktoma36** [comment]
With no bones their limbs could be severed quite easily :3

**Comment by Fox-McCloud** [comment]
slimes are not immune.

Have to give them painkillers.
