### ISSUE TITLE
Blast doors unable to be emagged if opened and closed again

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#8300]
**Problem Description**:
Blast door is unable to be emagged again if someone re opens and closes them

**What did you expect to happen**: 
For the blast door to open again after emagged

**What happened instead**:
It did not

**Why is this bad/What are the consequences:**
Because then you're SOL

**Steps to reproduce the problem**:
Have closed blast door
Emag said blast door
Press the blast door buttons twice
Try emagging blast door again

**Comment by FalseIncarnate** [comment]
I'd say the real issue is that you can close them once emagged.

**Comment by TDSSS** [comment]
Couldn't reproduce this when I tried. Did you use any particular blastdoors? I tried those on bridge and in medbay and both worked without issues.

**Comment by Ty-Omaha** [comment]
Yeah it seems to be fixed, just tried myself.
