### ISSUE TITLE
Female clown masks are unmorphable

### ISSUE THREAD

**Issue by Doukhan** [ParadiseSS13/Paradise#8303]
**Problem Description**:
Sexy Clown masks can't be morphed.

**What did you expect to happen**: 
That I could morph my sexy clown mask like I can the normal clown mask.

**What happened instead**:
Unmorphability.

**Why is this bad/What are the consequences:**
Female clowns can't morph their masks and freak sec out with their variety.

**Steps to reproduce the problem**:
Be a female roundstart clown, try and fail to morph your mask.

**Possibly related stuff**:
The masks from the autodrobe/everywhere else are also unmorphable.

**Comment by taukausanake** [comment]
Feature request. Need more sexy clown mask icons. I wonder how you would do most of those though...
