### ISSUE TITLE
Give players a spawn message for xenobio spider babies

### ISSUE THREAD

**Issue by Very-Soft** [ParadiseSS13/Paradise#8305]
So, you play on para, whatever role, you go along and eventually you murder the heck out of spiders for laying webs, and that's all well and good. They may have come from changelings, or come from some other spawn source. They are generally considered antagonists.

Then you're sitting around as a ghost, observing in general, of have been knocked out of the round, unlikely to recover, 'Do you want to be a spider?' and when you click yes, after a short while, there you are, you're a spider sitting in the abandoned office or where ever. And that's all there is. There's no instructions or rules presented, no objectives. 

Now, an experienced player might know that these ones came from xenobio spiders laying eggs. But even still, it's not super clear exactly where your character stands without someone telling you. 

In round today it was apparently enough of a problem that an announcement had to be issued:

shadeykins Announces:
Xenobio spawned spiders are not antagonists. Attacking people with them is self-antagging, fullstop. Consider this the only warning for this round.

It makes me question, if these spiders aren't antags, but also aren't differentiated by the crew as non antags, then why are they playable? They can't talk. They don't look any different from normal spiders. They serve no purpose except to be shit on by normal characters, and to be punished if they should retaliate. Which is all well and good for the rexular sentient xenobio spiders, because those ones at least get some intro text telling them what's up.

In my opinion, xenobio spider babies are an unintended trap. Newbies or people who don't die often or stay dead for long might see the option, click yes, and then retaliate when they are invariably attacked by some rando, as I did today.

I know I didn't do it to break rules or be an ass, or disruptive. I always do my best to contribute positively to the round when I do play, to obviously questionable success. I am pretty familiar with the rules, and yet, these spawns rules are clearly written (apparently), but said rules are not presented to the player upon taking control. It's not a fun role to play to begin with with said rules in place. 

I think that the rules need to be presented to the player, or the xenobio spider babies need to not be playable by players. 

As is, the role is functionally the same as playing a mouse, except you CAN attack people, but aren't ALLOWED to. And again, I can't stress this enough. The game doesn't TELL you this. It's a trap that will only get people into trouble, and that needs to change.

[Also I'm turning giant spiders off, because heck.]

**Comment by Birdtalon** [comment]
Very good point.

**Comment by FalseIncarnate** [comment]
While this is TECHNICALLY a feature request... I also can understand it as a possible issue/bug, or at the very least an inconsistency.

This probably is also going to take some internal debate within the staff to determine where xeno-bio mobs stand in terms of what they are and are not allowed to do and when (obviously "sentient" mobs are to be handled differently than normal ones) before we determine what sort of  message we want to put on these.
