### ISSUE TITLE
Whiteship Cult Issue

### ISSUE THREAD

**Issue by bigfatbananacyclops** [ParadiseSS13/Paradise#8306]
**Problem Description**:
Cultists keeps cheesing the white ship and it's walls are undestructable, it's a ship that you can move anywhere so the cults can escape easily, they set Corporal shield runes in every entrance and it's clearly impossible to enter.

**What did you expect to happen**: 
I expected to find a way to get in but it's clearly not possible.

**What happened instead**:
Everytime i raid the whiteships, what happens instead is that they go into the room and lock them selves with corporal shield runes, after that we cant do anything to get them neither deconstruct walls.

**Why is this bad/What are the consequences:**
This is bad because it's clearly the most easiest way for cults to win leaving it unfair for everyone, the only way to get in is through telescience but thats litterally gonna take so much time to calculate, and they will move the ship more and more, and with those corporal shield in any entrance, it's impossible to raid. Whenever they get their objectives done, they will move the whiteship to the station and they will just summon from their own whiteship leaving it impossible for the crew to stop. There is barely even chaplain players, and they never come to destroy the cult base,

Why do you think this is an important issue?
Because it's about balance, there's clearly no way to destroy their cultist base with this ship.
**Steps to reproduce the problem**:
Just get the whiteship board and make runes there.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was the cult game mode and i was security, trying to stop the cults, we found their base apparently and found it to be the white ship, we were trying to find a way in but it had corporal shields, and the walls are undestructable, those windows on the front allowed us to enter but the cultists ran into a small room with more corporal shield runes, and we couldnt do anything.

I believe the solution to this is by either making runes not possible to be made on the whiteship, or just entirely remove corporal shield rune.

**Comment by Very-Soft** [comment]
Alternate solution: Make the white ship walls destructible?

**Comment by taukausanake** [comment]
Better solution: Telescience :)

**Comment by SkeletalElite** [comment]
or make on station base more viable and in space base less viable

**Comment by alexkar598** [comment]
Feature request move to forums and never underestimate the power of telescience

**Comment by uraniummeltdown** [comment]
How are cultists supposed to summon from the White Ship? They can only summon in certain areas.
The solution is to make shuttle walls deconstructible, not blacklisting runes and definitely not removing the wall rune (wtf?)

**Comment by Brasnak** [comment]
chaplain can also remove runes and you can mop them with holy water, as far as i remember

**Comment by bigfatbananacyclops** [comment]
Not everyone knows telescience, the ship can move throughout many locations, and Deep space too, it would take time to set up a telescience lab, and the bluespace crystals and techs, then you have to go get the damn coordinates of where their ship is, security aren't gods who can predict if their base is going to be the whiteship. And as soon as they find it, it's impossible to get in unless you have a chaplain with you or try to xray laser gun the hell out of them but this is what they do ''just get in a locker''. yeah no, im not even sure if a bomb is enough to destroy the walls but they need to be undestructable

**Comment by Bigtimetripod** [comment]
Best way to fight cheese is to cheese back. If cult has white ship, science is maxxed. Juat get bluespace beakers and make near maxcap pot + water and plant em near the walls cult is. Wall will not ofc be removed, but the explodion power goes thru walls and will delete anything behind em. Also if ye look hard enough, there are calculators for telepad so that makes telescience alot easier. Also yeah, turning back to the chaplain version. Just bash the runes or get holy water and make holy water sprays/grenades/foam and remove the runes. Bridge of the whiteship can easily be captured cause there is like 1x5 window that can be broken down easy. After that take the whiteship board and they are immobile. Easy way would be to just laser the whiteship console and break it for temp immobility.

**Comment by ktoma36** [comment]
Also the whiteship has only three possible locations it can go, north west of the telecoms sat, north of security station z level, and deepspace (cant remember which z level that ones on). Also a maxcap toxins bomb will make short work of any base, walls or no walls. Potassium and water bombs are also good as @Bigtimetripod said. Also holy water is simple enough to mix at any chem dispenser if the chaplain isnt available/dead.

**Comment by HugoLuman** [comment]
> If cult has white ship, science is maxxed.

Implying whiteship cult won't consist of culted science :P

**Comment by Crazylemon64** [comment]
Not really a bug - take this to the forums.
