### ISSUE TITLE
Alien larvas don't actually spawn when there a prompt for the ghosts.

### ISSUE THREAD

**Issue by AquaVirus** [ParadiseSS13/Paradise#8308]
**Problem Description**:
Title.

**What did you expect to happen**: 
I expected 2 alien larvas to spawn and ghosts to take control of them.

**What happened instead**:
There was a prompt asking me if I wanted to be an alien, I pressed yes, but no alien larvas spawned.

**Why is this bad/What are the consequences:**
Removes xenomorphs from the game.

**Steps to reproduce the problem**:
Be a ghost - Pray for an alien spawn - Wait some time after the prompt appears - Press "Jump To Mob" and see that no aliens spawned.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing really. Might have been caused by the PR that made 2 aliens always spawn, because it was working just fine before that got merged.

**Comment by KasparoVy** [comment]
Not an issue 👍 ❌ 💯

**Comment by SigholtStarsong** [comment]
Same issue occurs for other ghot-polled antags

**Comment by imsxz** [comment]
feature, the game knows what is best

**Comment by variableundefined** [comment]
Cannot verify, closing
