### ISSUE TITLE
Roboticist missing stuff that makes life hell.

### ISSUE THREAD

**Issue by Kyutness** [ParadiseSS13/Paradise#8317]
**Problem Description**:
Missing a few things, notably, a starting posibrain, component analyzer. May be more, but those were the most immediate and painful realizations.

**What did you expect to happen**: 
If an IPC gets vandalized early, best I can do is blind repairs, and hope he can come online and tell me what's hurt.

**What happened instead**:
I expected to be able to build a body, pop in a robobrain, send the new borg on it's way. As well as I expected to be prepared for damaged IPCs

**Why is this bad/What are the consequences:**
As previously stated, if early on, a wizard fireballs an IPC, he's getting blind guesswork surgery.

**Steps to reproduce the problem**:
Play roboticist

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nope. Not really. I may be aware it is a cult round but that is because my friend asked questions and I am nice and won't go REEE and stab her repeatedly with a screwdriver.

**Comment by FalseIncarnate** [comment]
Which map was this?

If Delta, please report on https://github.com/ParadiseSS13/Paradise/pull/7770

Otherwise, please let us know if this was Meta or Box

**Comment by taukausanake** [comment]
Most likely Delta. Boxstation has a those things
