### ISSUE TITLE
Slime Cores are affected by EMP

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#832]
EMP from singularity and the 'emp' from changelings actually damages the slimecore, it's also impossible to fix without surgery. Where you treat it as brain repair in the chest.

**Comment by TheDZD** [comment]
I assume the slimecore in question is a slime person's brain? Should be an easy fix if so.

**Comment by Fox-McCloud** [comment]
likely the robotic var on slime cores: https://github.com/ParadiseSS13/Paradise/blob/7c739e474599ccddee25212399556c9a7eb9a7cc/code/modules/mob/living/carbon/brain/brain_item.dm#L81
