### ISSUE TITLE
Med Borgs Cant do Surgery on Non-Operating Tables

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#8322]
**Problem Description**:
When you try to ghetto surgery as a med borg (syndi or regular) you just hit the person (even on help intent)

**What did you expect to happen**: 
Be able to ghetto surgery as a borg when a operating table is not available.

**What happened instead**:
Hit them

**Why is this bad/What are the consequences:**
Makes Nukie Med Borg Surgery tools practically useless
Need to heal my Nukie friends man
Also useful on (regular) med borgs in emergencies

**Steps to reproduce the problem**:
Be med Borg
Put someone on regular table
Attempt surgery
Hit them instead of doing surgery

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nuke Ops in the case of syndi borgs but applies to regular borgs on non nuke ops as well.

**Comment by alexkar598** [comment]
you should put them on a roller bed,last time i checked it works
