### ISSUE TITLE
Air Injectors borked up

### ISSUE THREAD

**Issue by R1f72r** [ParadiseSS13/Paradise#8328]
**Problem Description**:
What is the problem? Injectors not turning on/not turning off once on, making impossible to remove by conventional meansor are exceptionally uncooperative to operate via a PC or by air alarm

**What did you expect to happen**: 
Why do you think this is a bug? It is not working as intended unless i missed a patch on how injectors work

**What happened instead**:
How is what happened different from what you expected? I expected to be able to sync to the air alarm in the room or at the very least have some semblance of consistency with turning on and off 

**Why is this bad/What are the consequences:**
Why do you think this is an important issue? Injectors are very useful in atmos, and in general them not working properly makes things a lot less efficient if someone were to build a SuperMatter engine or just in general any sort of thing that uses injectors

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue. Honestly i forget all the steps i took, i just remember i was doing an SM setup south of biohazard disposal and i accidentally turned on the injector and for the life of me i could not get it off, it was stuck on and in the position, meaning i couldn't remove it, this was on Boxstation, then on metastation me and Dryker were making a very very rough outline of a SM engine, and the injectors would not turn on nor function properly.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. the game mode was traitor then nuclear operatives (honkular operatives really)

**Comment by FalseIncarnate** [comment]
Already reported in #8245

**Comment by Citinited** [comment]
You can work around this by using a connected air tank console / AAC to toggle them. They really should be made easier to turn on / off, though.
