### ISSUE TITLE
Greys can use the swimming pool

### ISSUE THREAD

**Issue by Tayyyyyyy** [ParadiseSS13/Paradise#8330]
**Problem Description**:
Greys are not harmed by the swimming pool.

**What did you expect to happen**: 
Since water is like sulfuric acid to greys, going in the swimming pool should be like bathing in sulfuric acid.

**What happened instead**:
Nothing

**Why is this bad/What are the consequences:**
Seems inconsistent

**Steps to reproduce the problem**:
Make a grey character and walk into the swimming pool. Lying down only results in suffocation damage from drowning.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
@fludd12

**Comment by fludd12** [comment]
:scream_cat: 
I despise everything about the way water is treated here.
Anyway, I started college about three months ago, and haven't had the energy to *play* Paradise, let alone *code* for it.

**Comment by Tayyyyyyy** [comment]
Aww, good luck with college!! 😊

**Comment by StreakyHaddock** [comment]
The way the swimming pool is mapped, if you have bad latency and you're entering fitness through bar maint you WILL end up in the pool. Sweet christ please don't fix this.

**Comment by taukausanake** [comment]
Europa water physics when? Then not only can spessmen drown but Grey's can _melt_

**Comment by FalseIncarnate** [comment]
This likely also applies to the ocean for the beach away mission (especially the scuba section).

Probably can be fixed by making the pool/sea controllers call water_act on mobs in addition to handling things like drowning and temperature adjustments.

**Comment by HugoLuman** [comment]
> The way the swimming pool is mapped, if you have bad latency and you're entering fitness through bar maint you WILL end up in the pool. Sweet christ please don't fix this.

Just remap it so pool entry isn't pointing at doors?

**Comment by FalseIncarnate** [comment]
@HugoLuman the pool is moved in the Arcade remap PR, so that won't be an issue when that is merged
