### ISSUE TITLE
Devil mode does not support check_antagonists

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#8333]
**Problem Description**:
In the devil gamemode, the check_antagonists admin button does not show who the devils are, or any other useful information about the game mode.

**What did you expect to happen**: 
I expected to see a list of devils, including TP links for each.

**What happened instead**:
I saw a blank, white popup.

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/5890

Don't post stuff as an issue report for test merges.
