### ISSUE TITLE
Cannot take out ID's from depowered ATM's

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#8339]
**Problem Description**:
^

**What did you expect to happen**: 
To be able to pull an ID out from the atm regardless of it being powered

**What happened instead**:
The ATM keeps your ID

**Why is this bad/What are the consequences:**
People need their ID's

**Steps to reproduce the problem**:
Do some banking then have the power cut mid transaction, cry when you cant remove your ID

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was attempting to help someone mentor helping this issue during a shadowling round

**Comment by alexkar598** [comment]
Makes sense, your Id is IN the machine so you can't just pull it out since its out of your reach

**Comment by ktoma36** [comment]
Every ATM I have ever gone to never sucked a card inside of it, much less put it out of reach.

**Comment by Very-Soft** [comment]
My bank's ATM pulls the card inside of it, and gives it back when you finalize your transaction.

I DON'T THINK IT SHOULD WORK THIS WAY IN SPESS, but, it is a thing that does happen irl.
