### ISSUE TITLE
Hair Dye Doesn't Work

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#8348]
Someone changed genetics again, dramatically, and didn't update something--now hair dye is borked.

**Comment by Fox-McCloud** [comment]
@KasparoVy You're most familiar with this. Any ideas?

**Comment by taukausanake** [comment]
#8268
So it's just dying and not the bottles? Also doesn't work if you dye bodies

**Comment by Fox-McCloud** [comment]
Bodies just get turned black.
