### ISSUE TITLE
Sulphuric acid hurts Greys

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#8349]
**Problem Description**:
What is the problem?
Greys get burn/toxic damage after drinking Sulphuric acid
**What did you expect to happen**: 
Nothing
Why do you think this is a bug?
Greys shouldn't be hurt by Sulph. Acid.
**What happened instead**:
They DID get hurt/
How is what happened different from what you expected?
See above
**Why is this bad/What are the consequences:**
Death
Why do you think this is an important issue?
Life.
**Steps to reproduce the problem**:
Be Grey, drink sulph. acid
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Fraggloid** [comment]
literally unplayable until this is fixed

**Comment by taukausanake** [comment]
I thought this was fixed?

**Comment by Fraggloid** [comment]
Nope, just tested; still a thing.

**Comment by taukausanake** [comment]
So #7693 didn't fix it. Are these guys ever going to work properly?
