### ISSUE TITLE
Tranquillite walls seem to be broken

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#8358]
**Problem Description**:
If you try to add tranquillite to a wall girder, it just gets completely deleted, taking the metal with it. If you try to add it to a displaced girder as if making a secret door, the tranquillite vanishes but nothing happens to the girder.

**What did you expect to happen**: 
I was hoping for invisible or at least mime themed walls.

**What happened instead**:
Disappointment.

**Why is this bad/What are the consequences:**
Consistency issue with other metals?

**Steps to reproduce the problem**:
Set up wall girders, try to add tranquillite. Displace with crowbar, try to add tranquillite.

**Comment by uraniummeltdown** [comment]
the problem is there are no tranquillite walls or falsewall
there is a tranquillite "wall" you can make by using tranquillite in hand but it's just a crappy invisible wooden barricade

**Comment by taukausanake** [comment]
No icons or no turf for it? Should be a simple fix until you try and decide how it should function

**Comment by uraniummeltdown** [comment]
No icons or turf or falsewall object
