### ISSUE TITLE
Cold pockets cause Vox to move slow in space, even if the Vox themself isn't cold

### ISSUE THREAD

**Issue by Midaychi** [ParadiseSS13/Paradise#836]
Walking through pockets of cold in space, such as certain tiles or the resulting tile from mining an asteroid tile will cause vox to move like they are in molasses, or like they're under the old freezing slowdown system. But the vox's temperature is fine and well above freezing.

It feels like there's some sort of legacy freezing slowdown effect in place that shouldn't be there.

**Comment by Fox-McCloud** [comment]
Not really a bug...Vox and Machine people are resistant to cold *damage*, but they're not completely immune to cold itself.

**Comment by Midaychi** [comment]
This happens even when wearing one of the few hard suits vox can wear, makes being a miner a slow motion affair, but as this buggy ass legacy code is clearly an intentional affair, I shall close this and get out of your hair.
