### ISSUE TITLE
extreme lag since 10-10-2017

### ISSUE THREAD

**Issue by seanpermana** [ParadiseSS13/Paradise#8360]
Problem Description:
okay it's not a bug probably, but since after yesterday(10-10-2017), my ping always reach into very high lag(lowest is 190, average ping is 300-600, highest ping is 1400). in several days ago and the first day i start playing this server, my ping is 160-170.

What did you expect to happen: 
massive lag, lagging movement, unresponsive key.

What happened instead:
just as i expected.
Why is this bad/What are the consequences:
my movement are lagging, always late to respond someone, cannot point to moving object and people without the lag, and sometime my movement freezing and responding again. worse, i cannot hit someone without the lag problem, and always the first one to get wrecked in every fight, plus always late to catch the shuttle.

Steps to reproduce the problem:
just login to the server, wait the loading, and watch the ping as it start to show.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?):
it's secret mode, just as usual in paradise station. tried to walk, but always ended up stop in front of wall due the lag.

this is my first time i make a feedback, so sorry if there's so many errors on this issue.

**Comment by taukausanake** [comment]
> yesterday(10-10-2017)

> today (11-10-2017)

There's probably a lot of underlining issues about the connection and ping. You're kind of not the only one in this regard. I can't say anything about the physical server, that's @Allfd's domain and I asked him about it once before too. It's more closer to Paradise's code and/or the population it has that causes the general slowdowns I believe, nothing that can be fixed soon if ever

**Comment by seanpermana** [comment]
welp, then in the short word: i'm screwed.

**Comment by Allfd** [comment]
@seanpermana If you send me your byond login I can help you figure out whats going on.

Guessing you are in AUS or NZ by your times.

During the last two days we have been averaging 232 ms delay to AUS and 233 to NZ

UK was hit very hard from around  11/8 4PM to around 2AM server time.

![image](https://user-images.githubusercontent.com/8165455/32674402-200a303e-c621-11e7-8047-cfe0698841c1.png)

Latency is a bit harder to measure, but CPU tends to follow player count.

![image](https://user-images.githubusercontent.com/8165455/32674494-7ae17454-c621-11e7-9d47-01533c051536.png)

**Comment by seanpermana** [comment]
@Allfd 10 points for you, i live in AUS neighborhood country, probably my country also affected by the AUS lag too.

**Comment by Fox-McCloud** [comment]
Not really something that should be on the Github. This is a server and not codebase issue.

**Comment by taukausanake** [comment]
Well it's good talking about it anyways. Not like it would be done anywhere else that much
