### ISSUE TITLE
Embedded Objects are impossible to remove

### ISSUE THREAD

**Issue by RatElemental** [ParadiseSS13/Paradise#8377]
**Problem Description**:
If you get an embedded object, the surgery to remove it is bugged and impossible to complete. The only way to do so seems to be to amputated the limb it is stuck in.

**What did you expect to happen**: 
For it to be treatable without going all medieval.

**What happened instead**:
I sat in surgery and bled to death while the surgeons tried to fix it.

**Why is this bad/What are the consequences:**
Makes the throwing star incredibly overpowered, especially if it embeds in the head or lower body.

**Steps to reproduce the problem**:
Throw a throwing star at someone, watch as they are helplessly condemned to a bloodless existence.

**Comment by adamkad1** [comment]
i though that you get a yank out object verb when you get something stuck?

**Comment by Jountax** [comment]
It said I could examine myself if I was feeling cheeky and wanted to pull it out myslef. I did that, and clicked the line that said I had an embedded object in me (my cursor changed to indicate I could click on it) Nothing happened.

Even if it were possible that way, the surgery still needs to be fixed or removed, preferably fixed because it would indeed be the safer method of removal.

**Comment by adamkad1** [comment]
i dont ever remember it saying you could examine yourself to pull it out, only a verb in a new tab when you got something

**Comment by GuppyLaxx** [comment]
intended, you can't remove throwing stars from yourself, only way is surgery as they cannot fall out either

**Comment by Jountax** [comment]
@GuppyLaxx The issue I'm presenting here is that the **surgery** couldn't remove them either because it was bugged.

**Comment by Aurorablade** [comment]
Cannot reproduce. Can infact remove throwing stars following proper embedded object removal surgery steps. Scalpal > Hemo > Retract > Hand.

**Comment by Fox-McCloud** [comment]
I also could remove it myself by yanking it out of myself--got hit by one of these the other day.
