### ISSUE TITLE
Light placed in wrong position in OR1 of the new medbay.

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#8382]
Don't feel the need for the template. Just a simple light placement issue in the new medbay OR 1. 

![image](https://user-images.githubusercontent.com/23273289/32975050-0b8bdc72-cbc9-11e7-9944-905968ceb2b7.png)

**Comment by FalseIncarnate** [comment]
@FreeStylaLT

**Comment by IK3I** [comment]
pretty sure I fixed this in passing on my utility PR. Maybe hold off till that gets merged and check again.
