### ISSUE TITLE
Everything of type /obj/item/clothing/suit/storage runtimes when it's picked up.

### ISSUE THREAD

**Issue by MarcellusPye** [ParadiseSS13/Paradise#8423]
**Problem Description**:
Everything of type /obj/item/clothing/suit/storage runtimes when it's picked up.

**What did you expect to happen**: 
You to be able to pick up clothes.

**What happened instead**:

[06:09:55] Runtime in storage.dm,16: Cannot execute null.handle attack hand().
   proc name: attack hand (/obj/item/clothing/suit/storage/attack_hand)
   usr: Gunner Cressman (marcelluspye) (/mob/living/carbon/human)
   usr.loc: The floor (160,35,2) (/turf/simulated/floor/plasteel)

**Why is this bad/What are the consequences:**
Everything of type /obj/item/clothing/suit/storage is practically unusable.

**Steps to reproduce the problem**:
Spawn anything of type /obj/item/clothing/suit/storage, I tested:  /obj/item/clothing/suit/storage/labcoat
/obj/item/clothing/suit/storage/paramedic
/obj/item/clothing/suit/storage/ntrep

And attempt to pick it up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
_How?_

**Comment by MarcellusPye** [comment]
_Makes spagitti code noises_

**Comment by MarcellusPye** [comment]
Further investigation has revealed that this only occurs when I spawn them.

**Comment by tigercat2000** [comment]
Not a bug. They were spawned with the admin deserialization tool, but don't have the proper metadata.
