### ISSUE TITLE
Monkeys can apparently phase through things on tables

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#843]
No time to confirm the limits of this, but, found this while testing something else
![oh god what](http://i.gyazo.com/987167b8833171f6f2d8b3915ddf5291.gif)

**Comment by CrAzYPiLoT-SS13** [comment]
I think it can pass through the holes. Maybe this was on purpose. Try it on other stuff.

**Comment by SamCroswell** [comment]
Things that pass over tables (Monkies, Xenos, Etc) can also pass over security barriers and wooden barricades.

I do not think this is a bug, but it might be an oversight.

**Comment by CrAzYPiLoT-SS13** [comment]
I just checked, this isn't any of the two. It is meant to be like this. In deployable.dm:

**Comment by tigercat2000** [comment]
this might not be a bug but I am pretty sure it's not intentional

**Comment by CrAzYPiLoT-SS13** [comment]
Just check the file, will ya?

**Comment by tigercat2000** [comment]
oh
i misunderstood your post
okay not a bug nevermind
