### ISSUE TITLE
Everyone BUT Drask heals from Drask lungs

### ISSUE THREAD

**Issue by HugoLuman** [ParadiseSS13/Paradise#8432]
**Problem Description**:
Rather than regenerating while breathing cold air, Drask TAKE brute damage. Every other race heals if using Drask lungs and breathing cold air

**What did you expect to happen**: 
As per #7832 , Drask (and anyone with their lungs) are still supposed to heal brute damage while breathing supercooled air.

**What happened instead**:
Drask take brute damage, others heal.

**Why is this bad/What are the consequences:**
Literally the major feature of the race is now turned into a massive weakness. Only non-Drask benefit from having the lungs members of that species are born with.

**Steps to reproduce the problem**:
Be a Drask. Wear and open supercooled internals. Be any other race with transplanted Drask lungs, do the same.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tested on private server running latest version of repo. Adminspawned internals tank with mixture temp lowered via VV. Tested Drask, Plasma, Human, and Unathi, all with Drask lungs.

The code reason is because in the Drask lung definition, it sets the cold damage amounts to negative, but in the breath code, it multiplies temperature damage by the species modifiers. The Drask cold modifier is -1, so the double negative makes a positive.

**Comment by taukausanake** [comment]
Question: So a Plasmaman with not-Plasmaman lungs can breath differently? I take it with human lungs they can breath without internals but still need their suit on. That sounds like so much fun and I'd love to see more science with switching out organs

**Comment by HugoLuman** [comment]
Yes, that's how it works now

**Comment by HugoLuman** [comment]
AAAHH THIS IS LIVE NOW
