### ISSUE TITLE
Autopsy scanner is not working

### ISSUE THREAD

**Issue by TheGoodDocMoose** [ParadiseSS13/Paradise#8435]
**Problem Description**:
Scanner will not print report

**What did you expect to happen**: 
a report to print when item was used

**What happened instead**:
it did not print

**Why is this bad/What are the consequences:**
autopsy reports are needed

**Steps to reproduce the problem**:
try and use the autopsy scanner

**Possibly related stuff (which gamemode was it? What were you doing at the time?
A normal game mode scanning a body in the morgue

**Comment by taukausanake** [comment]
Duplicate of #7955?

**Comment by StreakyHaddock** [comment]
my issue is that if you scan a corpse without a brain, then the scanner won't print out. Can you confirm this is what happened in your case, @TheGoodDocMoose ?
