### ISSUE TITLE
Cult Shades Virtually Invincible

### ISSUE THREAD

**Issue by Machofish** [ParadiseSS13/Paradise#8437]
**Problem Description**:
Cult Shades seem to be immune to melee damage when deployed from their soul shards.

**What did you expect to happen**: 
I expected that Cult Shades should die after receiving enough direct damage, considering that Wraiths and Juggernauts are meant to be the melee expressions of Cult Constructs, while shades are supposed to be fragile.

**What happened instead**:
https://i.imgur.com/tigEtdu.png
Pictured - A Shade surviving several dozen harmbaton swings while continuing to slap around a cyborg until it lost its modules due to damage and it had to retreat. Bonus points since the shade moved faster than the cyborg, and was able to catch up to the cyborg while continuing to attack it.

**Why is this bad/What are the consequences:**
Step 1 - Obtain 2 or 3 Soul shards. Step 2 - Don't bother actually putting the shards in any shells and just send them amok to murderbone. Step 3 - All of the crew are now dead due to high-speed invincible murderghosts.

**Steps to reproduce the problem**:
Unknown. Presumably all Cult Shades work on this principle, but this would require testing - I was observing at the time of this.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode seemed to be cult. I was in an observer role at the time.

**Comment by Jountax** [comment]
That is odd, I've observed shades to be super fragile. Maybe stun batons just do no damage if powered?
