### ISSUE TITLE
Service Borg shaker and fabricator

### ISSUE THREAD

**Issue by ManiacalSymphony** [ParadiseSS13/Paradise#8443]
The service borg shaker sometimes ends up refilling itself, making it hard to mix new drinks unless you empty the shaker into glasses and be quick with mixing your drink

The service fabricator can't spawn items on the floor if the floor is clicked, and instead gives the message:
"The fabricator can only be used on tables and floors"
which makes me believe, you supposedly are able to spawn things on the floor, instead of looking for a table

**Comment by Jountax** [comment]
The borg shaker is meant to do that when you fill a glass from it. To empty it without it refilling, use your borg dropper to pull the reagents from it.

**Comment by variableundefined** [comment]
..WAD?
