### ISSUE TITLE
Mentors can see stealthmin

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#8448]
**Problem Description**:
Mentors can see admins when they have stealth mode engaged. Or at least see when they are speaking in OOC. Mentorchat still shows the administrators username.

**What did you expect to happen**: 
Mentors to see the stealth username when an admin is speaking in OOC while in stealth mode.

**What happened instead**:
Stealthmin/(Adminname): Memes in OOC

**Why is this bad/What are the consequences:**
This makes it hard to spy on mentors while they are under the guise of being unsupervised.

**Steps to reproduce the problem**:
1. Have an admin and a mentor on server.
2. Admin activates his trap card: Stealthmin!
3. Admin proceeds to goad OOC into an argument.
4. Mentor notices Stealthmin/(Admin)! OWO, WATS THIS?!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by Ralta** [comment]
WHY YOU SPYIN THO

**Comment by SigholtStarsong** [comment]
"Admin proceeds to goad OOC into an argument"

This seems uncomfortably close to entrapment.

**Comment by ExitGame** [comment]
Why is that bad though?

**Comment by Spacemanspark** [comment]
Integrity. What you do when you (think you) are alone.

**Comment by LightFire53** [comment]
@ExitGame The same reasons that headadmins have a super stealth mode to spy on game admins.

**Comment by SamHPurp** [comment]
@ExitGame to instill fear and remind people who their betters are at all times.

**Comment by davidchan13** [comment]
There is already logs that can be checked...

**Comment by AristoVagrant** [comment]
But why though? Trying to super sekret club even harder?
