### ISSUE TITLE
Sinta'Unathi can't be set as a default language.

### ISSUE THREAD

**Issue by nachomeep** [ParadiseSS13/Paradise#845]
No matter how much you click, it stays galactic common.

**Comment by veganzombeh** [comment]
Yep, just tested this. Siik'tajr also has the same issue. I'm not seeing any obvious cause either. It /might/ have something to do with the apostrophes in the languages though.

**Comment by tigercat2000** [comment]
problem probably exists on bay12 dev as well, needs further testing
