### ISSUE TITLE
interactive objects have the chance to teleport to you when using telekinesis

### ISSUE THREAD

**Issue by streather** [ParadiseSS13/Paradise#8452]
**Problem Description**:
If you have telekinesis and use an item that is interactive like sheets of metal, the resulting item teleports to your hand.

**What did you expect to happen**: 
Not entirely sure.

**What happened instead**:
I used metal sheets that were in another room to build floor tiles and the tiles teleported into my hand from the  other room.

**Why is this bad/What are the consequences:**
I wouldn't say its important, its a bug.

**Steps to reproduce the problem**:
Get tk from genetics, find something like sheets of metal that you can interact with, try to use them to build something like you would if it was in your hand like normal.

**Possibly related stuff (which gamemode was it? What were you doing at the time? nothing out of the ordinary to put here really,

**Comment by HugoLuman** [comment]
I'm guessing the code creates the new item with its loc defined as your empty hand
