### ISSUE TITLE
Air alarms heating to extreme temperatures

### ISSUE THREAD

**Issue by SakuraDuff** [ParadiseSS13/Paradise#8457]
**Problem Description**:
When air alarms heat areas with no or extremely little air, for example a fully depressurized room or anywhere on the construction site, air alarms will heat the tile in front of it to between 2500 and 7000 degrees kelvin, increasing the lower the pressure goes.

**What did you expect to happen**: 
As there is little or no air, the air alarm should not be able to heat it. 

**What happened instead**:
The air alarm would heat the area to thousands of degrees kelvin, then the heat would lower to 0 kelvin, before rising again on about a one second cycle. While testing to reproduce the bug, I wore an ERT leader hardsuit with the heat resist mutation on and was still taking huge amounts of damage because the heat was so high. 

**Why is this bad/What are the consequences:**
People building in the construction area or trying to repair an area that was completely depressurized will result in them taking massive burn damage no matter how resistant they are.

**Steps to reproduce the problem**:
Either remove all tiles around the tile immediately in front of an air alarm to depressurize it quickly, or build an air alarm in somewhere like the construction site. Once it is activated the tile in front of the air alarm will heat to extreme temperatures almost immediately, and if left like that, will heat adjacent tiles as well

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing really I can think of

**Comment by KasparoVy** [comment]
I believe this just occurred in the round that ended 2017-12-19 at 11:35PM EST (UTC -5.00).
It caused an integer overflow that resulted in atmos breaking and hyper-pressurizing everywhere with super-cold gas.
