### ISSUE TITLE
Deconstructing rusted reinforced walls yields black sprites.

### ISSUE THREAD

**Issue by GunDOSMk1** [ParadiseSS13/Paradise#8460]
**Problem Description**:
When rusted reinforced walls are deconstructed, the sprites for the steps are not there. And therefore black.

**What did you expect to happen**: 
Sprites for deconstructing rusted reinforced walls, or an error in deconstructing them.

**What happened instead**:
Black tiles instead of the sprites I expected.

**Why is this bad/What are the consequences:**
Reduction in emersion

**Steps to reproduce the problem**:
Find a rusted reinforced wall, attempt to deconstruct.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
N/A

Pictures:
![rusted walls](https://user-images.githubusercontent.com/26494404/34081388-b2abc3fa-e343-11e7-80f1-3600ad0bdf76.png)

**Comment by alexkar598** [comment]
with what did you deconstruct it?

**Comment by SamHPurp** [comment]
If this is the same bug as the one I had year or two ago, thats what happens when you simply wirecutter it, as the first stage of de-construction.
