### ISSUE TITLE
Unable to perform dental implant ghetto surgery

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#8505]
**Problem Description**:
Dental implant surgery does not work with ghetto surgery. Using the knife to start the surgery works but attempting to use a pen or rod as the drill just causes me to either stab or beat the patient. It is not the surgery failing as it can with ghetto, it's just not registering the action.

**What did you expect to happen**: 
To be able to implant dental implants with ghetto surgery

**What happened instead**:
Didn't work. Why can ghetto surgeons be doctors but they can't be dentists? Madness.

**Why is this bad/What are the consequences:**
When officers ask me for dental implants I cannot comply.

**Steps to reproduce the problem**:
Target mouth with help intent and knife in hand. Start dental surgery. Attempt to drill tooth with pen or rod. Also want to note I haven't attempted to do this by starting the surgery with a scalpel or glass AND haven't tried using a drill after the knife so I don't know the cause.

**Comment by GeneralChaos81** [comment]
Ghetto surgery has a few holes. I've found it impossible to remove the brain during ghetto surgery. Operating on a severed head flat out doesn't work.

**Comment by Serkket** [comment]
You need to use a screwdriver

**Comment by ZN23XZ** [comment]
Didn't even realize I also had this one open. Resolved under #8642.  Wiki for ghetto surgery has now been updated.
