### ISSUE TITLE
Blood splatters stack way too much on a single tile

### ISSUE THREAD

**Issue by Squirgenheimer** [ParadiseSS13/Paradise#8508]
**Problem Description**:
Blood effects that are created when a person gets hit can stack onto a tile forever
Even trying to alt click to avoid game freezes can yield a huge huge list

**What did you expect to happen**: 
For blood to be limited, maybe to two or three times
I don't think this happened before pull request #7848 
**What happened instead**:
There was enough blood to fill a pool on a single tile

**Why is this bad/What are the consequences:**
Makes it difficult to locate items on tiles that are affected by this. 

**Steps to reproduce the problem**:
1. blob with a bunch of factories
2. get hit by multiple blobs at the same time

Or just hit yourself a bunch. More testing may be required.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I believe this mostly concerns melee attacks
I was getting hit by multiple blob attacks rapidly the first time I saw this happen
The second time a prisoner appeared to have been beaten either by themselves or by an officer
![screenshot_548](https://user-images.githubusercontent.com/30324965/34545923-65288176-f0be-11e7-9373-8690a66ff015.jpg)
![screenshot_547](https://user-images.githubusercontent.com/30324965/34545924-67eadfda-f0be-11e7-9aed-7ef80b132f37.jpg)

**Comment by Aurorablade** [comment]
@KasparoVy you think https://github.com/ParadiseSS13/Paradise/blame/82054cdf2408ec1c76a50a63b641b1d01c30623d/code/modules/surgery/organs/blood.dm#L264 may be messing with the locate detetion on tiles somehow cuase there should be a if statment saying 'if this is on a tile do not make another' something is messing up the check.

**Comment by Aurorablade** [comment]
i need another set of eyes on this i cannot figure out why its doing this.

**Comment by Aurorablade** [comment]
okay from what i can tell its just not seeing the splatter decal on the tile when it calls locate in the above line (and lines like it) so it makes a new one. so question is whats preventing it from seeing the decal?

**Comment by KasparoVy** [comment]
Sorry for the delay, super busy. I'm taking a look now as well, but nothing is immediately apparent. Fiddling some to see if I can pin it down
