### ISSUE TITLE
Travis takes over 10 minutes to compile, causing CI failure

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#8512]
Paradise currently takes a long time to compile, long enough to make Travis give up when performing CI. We'll need to cut down compilation time in order to get that working again.

**Comment by SamHPurp** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/.travis.yml#L10

Bet its to do with 512 compilation, mate.

**Comment by Shadow-Quill** [comment]
@Anasari Pretty sure this is good to be closed.
