### ISSUE TITLE
METASTATION: Camera not mounted on wall.

### ISSUE THREAD

**Issue by Wolfsyndrome** [ParadiseSS13/Paradise#8518]
**Problem Description**: 
The camera located in Medical's Cryo-cell room, left of the cloning room, appears to be mounted onto thin air, instead of on a wall. 

**What did you expect to happen**: 
Because the camera is clearly mounted into thin air and looking into a corner, instead of looking into the room.

**What happened instead**: 
Explained above.

**Why is this bad/What are the consequences:**
This isn't bad per se, I believe it just requires a small direction-readjustment. 

**Steps to reproduce the problem**:
No steps needed. I just flew by in observer mode and found it like this.

In the image blow, the camera I'm speaking of is two tiles in front of my Ghost, on the lower left corner of the small table.
![scrnshot1](https://user-images.githubusercontent.com/23321184/34614714-a3ad079e-f232-11e7-892f-6cb69b177d30.png)

**Comment by SamHPurp** [comment]
Aw fuck, thats on me, when I re-did all of Meta's medbay. Real easy fix for someone.
