### ISSUE TITLE
The Ocean is Cold as Shit

### ISSUE THREAD

**Issue by Dumbdumn5** [ParadiseSS13/Paradise#8521]
**Problem Description**:
Went into the ocean with cold resist, hardsuits, softsuits, being lit on fire, etc. still chilled to the bone.

**What did you expect to happen**: 
For protective gear or mutations to protect nerds.

**What happened instead**:
Protective gear did nothing and the ocean depths acted like frost oil and ignored basically any protections

**Why is this bad/What are the consequences:**
People can't really traverse the ocean floor without being totally 100% fucked by freezing.

**Steps to reproduce the problem**:
Climb down the buoy into the depths, freeze your ass off worse than a deep antarctic winter or literally the void of space.

**Comment by Citinited** [comment]
Working on this one
