### ISSUE TITLE
New atmospherics bug with freezers / heaters

### ISSUE THREAD

**Issue by Kalrirr** [ParadiseSS13/Paradise#8523]
**Problem Description**:
Atmospherics freezers / heaters dissapear completely after attempting to dismantle them.

**What did you expect to happen**: 
The parts should appear on the ground with a machine frame on the tile.

**What happened instead**:
Everything dissapeared and the tile is empty.

**Why is this bad/What are the consequences:**
This is a new bug, freezers / heaters can easily be replaced but it's still a nuisance.

**Steps to reproduce the problem**:
Use a screwdriver on a freezer / heater inside atmospherics and then crowbar it to dismantle.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No further notes needed, this bug can always be reproduced, even after round restarts.

**Comment by GeneralChaos81** [comment]
This is also an issue with cryo cells, which are also part of machinery/atmospherics/unary group. other things just in machinery appear all OK, like autolathes and borg chargers.
