### ISSUE TITLE
Save Chat Log freezes Dream Seeker

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#8540]
**Problem Description**: Whenever I try to save my chat log Dream Seeker freezes and no amount of time recovers it

**What did you expect to happen**: To get the option to save my chat log

**What happened instead**: Ded

**Why is this bad/What are the consequences**: Because I want to remember all the things I did as a fun pAI and for possible logging on the player side, say someone griefs you and the admins don't catch it

**Steps to reproduce the problem**: Go to Goonchat gear icon, click and go to Save chat log. Then reload Dream Seeker because it froze

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Might be just an issue with my system or Internet speeds but if it can be replicated then maybe not. I even tried early at round start with little text to save and still got a freeze

**Comment by IK3I** [comment]
so after a quick check, the problem is with the xmlhttprequest in browseroutput.js.
Set it to run async and the rest of the proc finishes out without hanging. I'll see about making that request actually return the file it's looking for.

**Comment by IK3I** [comment]
My fix is kind of on hold/hiatus while I figure out logistics of the task. For now, don't hit that button!
