### ISSUE TITLE
One handed people can be cuffed

### ISSUE THREAD

**Issue by awesine** [ParadiseSS13/Paradise#8547]
**Problem Description**:
One handed people can still be handcuffed/bucklecuffed

**What did you expect to happen**: 
One-handed people can't be cuffed

**What happened instead**:
One handed people can be cuffed

**Why is this bad/What are the consequences:**
You can't cuff someone with one hand

**Steps to reproduce the problem**:
1. remove hand
2. try to get cuffed
3. get cuffed
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
not really anything else important

**Comment by Ralta** [comment]
Feel like even if this isn't intentional, it should be. Losing a hand should not make you uncuffable imo. Maybe they're just cuffing your wrist to your bicep or something :P

**Comment by TechDragon610** [comment]
Iirc this was in fact intentional. IRL it is standard to cuff those with one hand to a belt loop or similar restraint.    This was put in place to avoid greytides chopping off their hands to become unable to be arrested.

**Comment by davidchan13** [comment]
Definitely intentional. 12-18 months ago tides/antags were lopping off one hand so they could tide until beaten into crit/straitjacketed.

**Comment by MarcellusPye** [comment]
@tigercat2000 @Fox-McCloud @Crazylemon64 
Appears to be working as intended. If otherwise please tell us.

**Comment by taukausanake** [comment]
Would multi-buckling do anything for this? If you can still cuff someone but their hand is still free then you can buckle that hand to something else. I kind of like the idea of someone making a sacrifice to avoid getting caught but I understand why it would be powergame-y
