### ISSUE TITLE
Lazurus capsule bug

### ISSUE THREAD

**Issue by FisherKnight** [ParadiseSS13/Paradise#8549]
Mobs placed inside Lazarus capsules are able to attack things while inside them.

I feel like things inside laz capsules should be unable to do anything, really.

This is an issue because it means a mob hidden away in someone's bag can damage things like windows and breach things to space with seemingly no real way to stop it besides going into the bag and manually removing it from the capsule.

The exact thing I did to cause this little problem is as follows:
1: find the "creature" mob, the green slimy monster thing
2: stick the corpse with a laz injector and then pop it in a capsule
3: go near an object it would normally be able to attack from outside the capsule.
4: witness its telekinetic ability to destroy the object

It may have to be damaged while in the capsule to trigger the magic breaking powers, atmos hurts things while in the capsule dunno if that itself is also a bug or not.

**Comment by Spacemanspark** [comment]
Did you emag the Lazarus injector prior to using it to revive the mob, before you used the capsule?

**Comment by FisherKnight** [comment]
No emags were involved

**Comment by FunnyMan3595** [comment]
This has been fixed sometime in the intervening years.
