### ISSUE TITLE
IPCs can drink now despite code having an exception for it.

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#855]
http://puu.sh/hmSAq/9ed908f9fd.png (reagens\reagent_containers\food\drinks.dm - line 29)

Code hasn't changed at all with goonchem, yet IPCs are still able to drink for some reason.

**Comment by Earthdivine** [comment]
I think fox said he let them be able to drink during the addition of goonchem

@Fox-McCloud Please verify this.

**Comment by tigercat2000** [comment]
@Earthdivine wouldn't make sense, code still exists to prevent it, not commented out, just.. doesn't work
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/reagent_containers/food/drinks.dm#L48-L50
>			if(H.species.flags & IS_SYNTHETIC)
				H << "\red They have a monitor for a head, where do you think you're going to put that?"
				return

**Comment by SamCroswell** [comment]
IPCs may have had that flag removed, silly as that would be. Will verify.

**Comment by veganzombeh** [comment]
@SamCroswell IPCs still have the flag. I have no idea why this isn't working correctly. Another issue though, is that the "They have a monitor for a head, where do you think you're going to put that?" message should be given to user, not H.

**Comment by Iamgoofball** [comment]
They don't have the flag, as all IS_SYNTHETIC was used for was for chem based stuff like drinks, and when we enabled chems and ipcs they lost that flag intentionally

**Comment by Keilden** [comment]
IPCs could drink certain stuff befor GOONCHEM. like space beer out of the bottle.

**Comment by tigercat2000** [comment]
@Iamgoofball [Are you sure they don't have the flag?](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/species.dm#L708)
>	flags = IS_WHITELISTED | NO_BREATHE | NO_SCAN | NO_BLOOD | NO_PAIN | IS_SYNTHETIC | NO_INTORGANS

**Comment by Iamgoofball** [comment]
Huh.
