### ISSUE TITLE
"Dreamseeker Invalid Argument" Character creation

### ISSUE THREAD

**Issue by SpectreSpecter** [ParadiseSS13/Paradise#8552]
**Problem Description**:
Just as the title says. For some reason when I tried to recreate a character in the CC menu, I happened upon something that looked like a bug directly on your face, not sure what it exactly was but I remember it was in a tint of green. I saved my character like that thinking that it would be interesting to see it. Unfortunately when I played it, it never really showed up. Now I am back 2 months later and for some reason I get a "encountered an improper argument" when I try to get in to SS13 with Dreamseeker. I am not certain if this is the main problem, but as far as I know I updated both BYOND and Adobe just today so I don't think anything wrong is in there. The problem is because of this, I can only go so far as the "New Player Options" and cannot access anything further because of an "improper argument"

**What did you expect to happen**: 
Why do you think this is a bug?
As far as I know, I messed with the character creation a bit too much

**What happened instead**:
How is what happened different from what you expected?
I wanted to play a game, I can no longer. Not sure if you fixed that problem for it not showing so people couldn't get it, but because of that, my safe file for that has been corrupted supposedly.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
I can no longer get in to play a game

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Mess with the CC (Probably hair) until you get a bug on your face and safe game.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Gamemode of Character Creation.

**How would you like us to help you because we know you would severely need the help because this is a serious problem only we can fix and because you already took the time to delete everything BYOND based upon your computer including the Cache and Cookies, redownloading BYOND in its entirety.** 
If anything, reset my game account either going by the username "TheUsergamer" or my ingame name "Celusia Keleos"

**Comment by IK3I** [comment]
if this hasn't been fixed yet, you should message an admin directly. CC is stored in the SQL db so having someone with access drop your entry is probably the first thing to try.

**Comment by SpectreSpecter** [comment]
Thank you for the comment, just did that right now.

**Comment by Regen752** [comment]
I'm also having this problem. Refuses to let me join. It seems to occur on some other servers aswell.
