### ISSUE TITLE
Snow tile still on the map after Christmas

### ISSUE THREAD

**Issue by Cactus2388** [ParadiseSS13/Paradise#8557]
**Problem Description**
There's snow underneath the door that leads to the chinese restraunt

**What did you expect to happen**: 
It's no longer christmas, snow shouldn't be hidden underneath an airlock

**What happened instead**:
Snow is on the map after christmas

**Why is this bad/What are the consequences:**
Muh immersion

**Steps to reproduce the problem**
Go to dorms, look underneath the door heading to the chinese restraunt, see snow, IMMERSION RUINED

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: it was forgotten after the christmas area in dorms got removed

**Comment by FreeStylaLT** [comment]
![img](http://i0.kym-cdn.com/entries/icons/facebook/000/013/306/2dd.jpg)
