### ISSUE TITLE
Unable to call Shuttle

### ISSUE THREAD

**Issue by ZombieBisque** [ParadiseSS13/Paradise#8563]
**Problem Description**:
During the end of the shift I (captain at the time) tried to call the Shuttle, and no matter what I entered for the reason, it kept rejecting it and saying I needed to input a reason.  Eventually an admin messaged me and was able to call the shuttle through the console or whatever.

**What did you expect to happen**: 
An admin asked me to come here and report it so I figure it's not supposed to happen like that.

**What happened instead**:
Shuttle option kept rejecting my requests despite inputting reasons for calling the shuttle

**Why is this bad/What are the consequences:**
Ending the round with the shuttle is kind of important

**Steps to reproduce the problem**:
- Be Captain
- Try to call the shuttle (round was about an hour and a half in)
- Enter a reason for the shuttle
- If rejected confirm that you're logged into the console and try again
- If rejected again go to captain's office and try that computer
- If rejected again, pray

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Earlier when I tried to set the clown to "execute" in the security records computer on the bridge for being a changeling it kept saying that my access was denied, despite being captain and having the captain's ID.  I thought that might just be someone messing with my access or the computers but since I also couldn't call the shuttle later while also on the bridge it might be related.

Gamemode was just traitors and a changeling from what I could tell by the end of round details.

**Comment by Ralta** [comment]
I wonder if this was a client-side issue with the interface. Regardless of the bug, it may be worth clearing your BYOND cache on the off chance it is client side so at least it won't happen to you again 😄

**Comment by TechDragon610** [comment]
Has the issue persisted between your rounds as captain?

**Comment by ZombieBisque** [comment]
I'll try clearing my BYOND cache tonight before I try playing again.  I haven't played a round since this one but I'll try again tonight.  I didn't have any issues before this round though, either calling the shuttle or changing someone's status on the security records console.  My last captain round was probably...a week or so ago before last night, and I had no trouble calling the shuttle then.  Let me know if you have any other questions :)
