### ISSUE TITLE
THERES A PIECE OF SNOW UNDER THE DOOR OF MR CHANGS

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#8564]
![5bd7ee6db0](https://user-images.githubusercontent.com/13833056/35064476-18833aaa-fbc2-11e7-8af4-30e1a5a551e1.png)

![2ab4c9b7a7](https://user-images.githubusercontent.com/13833056/35064492-248ef82a-fbc2-11e7-95fc-2d8ebad7e669.jpg)

@FreeStylaLT THIS MAKES ME VERY UNCOMFORTABLE PLS ADVISE

**Comment by taukausanake** [comment]
Duplicate of #8557, but this one has an image

**Comment by FreeStylaLT** [comment]
![img](https://i.warosu.org/data/g/img/0481/86/1432756870303.png)

**Comment by taukausanake** [comment]
Uhhhh are you sure about that @tigercat2000? I mean I haven't checked lately but I'd like to know

**Comment by FreeStylaLT** [comment]
this will forever haunt us won't it

**Comment by taukausanake** [comment]
It must not be an issue anymore I guess ¯\_(ツ)_/¯
