### ISSUE TITLE
Carbon/Human Icobase and Deform Sprite Issue

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#857]
![Image](http://i.gyazo.com/dfd6d616d3bc0ac0a50dda125d797661.png)
Pictured left to right: a Human (invisible), Tajaran, Unathi, IPC, Skrell, and Kidan (invisible). They were spawned in via Spawn as human/human, human/tajaran, etc. The issue also seems to extend to set_species, where changing a humanoid's species does not update their icon.

**Comment by Fox-McCloud** [comment]
@ZomgPonies
