### ISSUE TITLE
Typo when being dethralled

### ISSUE THREAD

**Issue by D00MGUY** [ParadiseSS13/Paradise#8572]
**Problem Description**:
When being dethralled it says "A small part of your pulses with agony as the light impacts it." your should be you

**What did you expect to happen**: 
I expected "you" instead of "your"

**What happened instead**:
It said "your" instead of "you"

**Why is this bad/What are the consequences:**
Not so much as an important issue, just kindof irritating I guess

**Steps to reproduce the problem**:
Fix the typo

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Shadowling gamemode

**Comment by TechDragon610** [comment]
so it seems that it looks for a variable called [braincase] to insert into that blank so "A small part of your (skull) pulses with agony as the light impacts it." which would be grammatically correct....except now I have to dig and find what a braincase is determined by. What race were you playing?

**Comment by D00MGUY** [comment]
I was playing as a human
