### ISSUE TITLE
Throwing mob holders causes runtime

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#8574]
**Problem Description**:
Throwing mob holders causes runtime. This means that drones/diona/mice runtime when someone tries to throw them; equally, it causes another runtime when someone picks them up, because they have already been given a half-completely throwing ticker.
Should be simple enough to fix by adding a `if(!src)` check somewhere in this proc https://github.com/ParadiseSS13/Paradise/blob/master/code/game/atoms_movable.dm#L232

**What did you expect to happen**: 
Runtime would not happen, throwing would fail gracefully.

**What happened instead**:
Runtime occured.

**Steps to reproduce the problem**:
Pick up drone, throw, observe runtime log.

**Comment by Certhic** [comment]
Seems to have been fixed
