### ISSUE TITLE
[Bug] Training bombs timer issues

### ISSUE THREAD

**Issue by MaxIsJoe** [ParadiseSS13/Paradise#8578]
**Problem Description**:
Training bombs countdowns can't be set again after a second time

**What did you expect to happen**: 
When setting a training bomb's timer to X amount of seconds it should set it from Z amount of seconds to X amount of seconds

**What happened instead**:
When hitting ENTER the count time does not change from Z amount of seconds to X amount of seconds

**Why is this bad/What are the consequences:**
Could lead into RP issues with security training in the future.

**Steps to reproduce the problem**:
1-Grab a training bomb
2-Set the timer from 30 seconds to 90 seconds
3-Enable the countdown
4-Fail at disarming the bomb

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing to note of that can be related to this issue

**Comment by Certhic** [comment]
Can't reproduce. Might have been fixed since report.

**Comment by MaxIsJoe** [comment]
I guess it is fixed then.
