### ISSUE TITLE
Drone (maybe cyborg too) can not use magnetics gripper

### ISSUE THREAD

**Issue by Bakit** [ParadiseSS13/Paradise#858]
Today, i tried to set up some lights in the maintenance but when i use the magnetic gripper on the wall (with the item) it said: You push the wall but nothing happens! After that i tried to set an apc to see and the same thing happen

**Comment by veganzombeh** [comment]
It does this because it's [returning attack_hand](https://github.com/ParadiseSS13/Paradise/blob/bc9a6fe09e62c8a474da3e2bab8f92dc0d0272f0/code/game/turfs/simulated/walls.dm#L500). I'm not sure if this is intentional or not though, since grippers are supposed to be fairly limited in use.

**Comment by alphaJackal** [comment]
Can confirm this bug, and drones and borgs used to be able to attach light figures before this.
