### ISSUE TITLE
Can't get autopsy scanner to work on just one guy (not debrained)

### ISSUE THREAD

**Issue by paragonofevil** [ParadiseSS13/Paradise#8581]
**Problem Description**:
Cannot get autopsy scanner to print a report on one guy in particular.

**What did you expect to happen**: 
I got several other people to print out reports no problem. Even stopped trying to get the report to print on this guy, got it to print for other people, and went back to the guy, just for it to not work again.

**What happened instead**:
I leave my other hand empty for a report to print into. Instead nothing happened at all.

**Why is this bad/What are the consequences:**
The detective came in asking about a DIFFERENT dead guy. If he wanted info about this dead guy, he'd be very much out of luck. This basically prevents me from doing a major part of my job.

**Steps to reproduce the problem**:
Loaded corpse onto operating table. Put scanner in active hand, scanned several different parts of his body. Each part said it scanned normally. Clicked the scanner, no printout. Turned on hotkeys and pressed Z with it in active hand, no printout. Several more body scans and clicks later, still no printout.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Other scans and printouts worked fine. I asked Streaky, he said this was a known problem for people who were debrained... but this guy had a brain (and head) still intact. Here's his Health Analyzer results:

You have analyzed Monty Clark's vitals.
Analyzing Results for Monty Clark:
	Overall Status: dead
Key: Suffocation/Toxin/Burns/Brute
Damage Specifics: 0 - 0 - 0 - 360
Body Temperature: 20.0001°C (68.0002°F)
Time of Death: 12:43
Localized Damage, Brute/Burn:
Upper body: 80-0
Lower body: 70-0
Left arm: 50-0
Right arm: 50-0
Left leg: 50-0
Left hand: 30-0
Right hand: 30-0
Subject bloodstream oxygen level normal | Subject bloodstream toxin level minimal | Subject burn injury status O.K | Severe anatomical damage detected
Subject contains no reagents.
Subject is not addicted to any reagents.
Unsecured fracture in subject left arm. Splinting recommended for transport.
Unsecured fracture in subject right arm. Splinting recommended for transport.
Unsecured fracture in subject left leg. Splinting recommended for transport.
Unsecured fracture in subject left hand. Splinting recommended for transport.
Unsecured fracture in subject right hand. Splinting recommended for transport.
Bone fractures detected. Advanced scanner required for location.
Internal bleeding detected. Advanced scanner required for location.
Subject is bleeding!
CRITICAL blood level 8 %, 49.4196 cl, type: O+
Subject's pulse: 0 bpm.
Subject's genes are stable.

**Comment by Ralta** [comment]
I've come across this before; I think it's an issue with the scanner itself, as I have seen admins deleting the scanner and spawning a fresh one to fix it.

**Comment by paragonofevil** [comment]
Nope. I had two scanners and both had the same problem.
