### ISSUE TITLE
PM's with  ° (and likely other characters)

### ISSUE THREAD

**Issue by Necaladun** [ParadiseSS13/Paradise#8587]
**Problem Description**:
A PM sent containing  ° gives the bwoink sound and is logged, but is never displayed in chat. In the logs, it's displayed as "\xB0", as in 

ADMIN: PM: Necaladun->Rhythen: Temperature: 32024 \xB0C

**What did you expect to happen**: 
'cause i should see the PM

**What happened instead**:
no one saw it

**Why is this bad/What are the consequences:**
Not improtant but annoying when copy-pasting atmos stuff to people

**Steps to reproduce the problem**:
PM someone. Insert "Temperature: 32024 °C" or whatever in the message, and watch it not show.

Send it to them repeatedly and they only hear bwoinks but don't know who is doing it which is kinda fun.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Prolly a bunch of other characters too

**Comment by Ralta** [comment]
I'm gonna abuse the SHIT outta this!

Not really. But I totally should.

**Comment by MarcellusPye** [comment]
This appears to be an issue with the byond proc html_encode

**Comment by IK3I** [comment]
to_chat() isn't even that bad, it's the secret function hidden underneath that you should fear. Anyway, it's probably an issue with encoding because \xB0C is &#xb0c

**Comment by IK3I** [comment]
actually, a string replace might be the solution. \x isn't proper html, &#x is. Still doesn't explain the busted message issue though.

**Comment by MarcellusPye** [comment]
I didn't see any runtimes when replicating, but I don't know if something this deep would report properly.

**Comment by AffectedArc07** [comment]
Assuming this is fixed since 512 and 513 have proper unicode support.
