### ISSUE TITLE
Wizard mindswap can target borgs

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#8591]
**Problem Description**:
A wizard who targets a cyborg with a mindswap spell causes the wizard round to end instantly.

**What did you expect to happen**: 
Wizard mindswap spell should not be able to target silicons.

**What happened instead**:
Wizard mindswap spell can target silicons.

**Why is this bad/What are the consequences:**
Causes instant round end in wizard rounds, due to the cyborg counting as dead.

**Steps to reproduce the problem**:
Be a wizard in a wizard round.
Target a cyborg body with the mindswap spell.
Observe that this causes instant round end.

**Comment by Ralta** [comment]
That's pretty fuckin funny. I wonder if targeting a borg with an MMI would work?

**Comment by SkullyRoberts** [comment]
@Ralta for objective purposes, being a borg is being dead. Doesn't matter what type of borg it is. Same thing as being a brain.
