### ISSUE TITLE
Higher custom FPS causes slower animations

### ISSUE THREAD

**Issue by Squirgenheimer** [ParadiseSS13/Paradise#8600]
**Problem Description**:
The higher a person sets their fps in preferences, the slower and more jagged looking the smoothing animations get.
This is especially jarring as people move around and change directions.

**What did you expect to happen**: 
The smoothing to be synchronized across various framerates

**What happened instead**:
Normal:
![Gif: Normal (Set to 0)](https://i.imgur.com/2zUPWeD.gif)

600 FPS:

![Gif: FPS set to 600](https://i.imgur.com/FyqUP96.gif)

**Why is this bad/What are the consequences:**
Higher framerate should provide a better experience, not a worse one
Effects of this can be noticed even when setting it to reasonable numbers

**Steps to reproduce the problem**:
1. Set FPS to a stupidly high number
2. Observe that the game now looks laggier
3. Test this further by moving one tile a time

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I would think this is a simple fix, probably just needs a divisor somewhere but I don't know where

**Comment by FlattestGuitar** [comment]
I think this is just down to the fact that you're forcing the client to render 600 frames. Other places have it limited to 144, because there's no reason for anything higher than that, now that I think about it.

**Comment by Squirgenheimer** [comment]
Like I said, you can see it at reasonable numbers like 60.

**Comment by Squirgenheimer** [comment]
[More footage](https://gfycat.com/AmusingWeeAsiaticlesserfreshwaterclam)

**Comment by tigercat2000** [comment]
https://github.com/tgstation/tgstation/issues/21839
http://www.byond.com/forum/?post=2178421
http://www.byond.com/forum/?post=2127554

Seems that BYOND behaves oddly when the following isn't satisfied: 
`Do 40 or 100 fps.
It should to be a multiple of the server fps (20) that evenly divides into 1000. That is basically 40 fps or 100fps. `

**Comment by Regen1** [comment]
@tigercat2000 Then we shouldn't allow players to set it manually, and just allow a drop down to choose from

**Comment by tigercat2000** [comment]
@Regen1 Not really, just a disclaimer that other results may not work well

**Comment by Spaghetti-bit** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/60483458/0f6b9776-a4cd-4d7b-a6ec-bb5474878353)
No longer an issue as we cap our FPS at 120.
