### ISSUE TITLE
FPS setting doesn't save

### ISSUE THREAD

**Issue by Tayyyyyyy** [ParadiseSS13/Paradise#8608]
**Problem Description**:
Client FPS resets every round

**What did you expect to happen**: 
client FPS to be saved so I don't have to reset it

**What happened instead**:
It's always 0 at the beginning

**Why is this bad/What are the consequences:**
Inconvenience

**Steps to reproduce the problem**:
Set a different FPS on one shift. Wait for server restart. Check your FPS setting.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
@uraniummeltdown

**Comment by tigercat2000** [comment]
Well, I horribly fucked up applying this PR to the server, but I'm not sure why this wouldn't work.
