### ISSUE TITLE
METASTATION - Fire alarm floating off of wall.

### ISSUE THREAD

**Issue by Wolfsyndrome** [ParadiseSS13/Paradise#8610]
**Problem Description**:
There's a fire-alarm floating off of the wall, as shown in the imagine attached.

**What did you expect to happen**: 
Not really applicable.

**What happened instead**:
Also not applicable.

**Why is this bad/What are the consequences:**
No real consequences, it just looks weird.

**Steps to reproduce the problem**:
No idea, I found it as is. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Happened on the Meta-station. It's in the Brig's Gear room, one up and one right from my Vox.
![scrnshot1](https://user-images.githubusercontent.com/23321184/35475148-7c1db1b0-0399-11e8-87a9-f7d7630e4c83.png)

**Comment by SamHPurp** [comment]
Whoops
