### ISSUE TITLE
Characters with glasses cannot become Captain, but characters without any limbs can.

### ISSUE THREAD

**Issue by SkullyRoberts** [ParadiseSS13/Paradise#8614]
**Problem Description**:
What is the problem?
Recently a feature was added so that certain characters can't become HoS or Captain, because they have disabilities that make doing their role almost impossible.

**What did you expect to happen**: 
Why do you think this is a bug?
Seizures, deaf, blind, mute, tourettes, can't speak properly, and needs glasses all prevent a character from being able to select Captain or HoS in their job preferences. Presumably characters without legs should also be excluded.

**What happened instead**:
How is what happened different from what you expected?
Characters without any limbs can become Captain. Characters without any limbs cannot actually perform any of the functions of a Captain.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because characters with a minor disability with extremely easy workarounds, namely needing glasses, cannot become captain. But a character without any limbs can still become Captain.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1) Have a character that has any of the following disabilities:
Seizures, deaf, blind, mute, tourettes, can't speak properly, and needs glasses
2) Go to job preferences.
3) Notice that HoS and Captain are crossed out with "DISABILITY" written instead.

4) Make a character without any legs.
5) Go to job preferences
6) Notice that you can still become HoS or Captain.
7) Cri every time.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by alexkar598** [comment]
loss of limbs as captain is fine..they only need a mouth and a headset

**Comment by Kyep** [comment]
This is not actually a bug.

The way this works was an agreed compromise between myself, the headmins, etc, at the time. It was deliberately chosen to work this way.
