### ISSUE TITLE
Random night vision

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#8622]
**Problem Description**:
What is the problem?
I joined the shift, and somehow had full night vision.

**What did you expect to happen**: 
Why do you think this is a bug?
Even though kitties have night vision irl, in game tarajans are not really suppossed to see everything in full bright

**What happened instead**:
How is what happened different from what you expected?
^
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Free night vision is free advantage I'm not suppossed to have

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
In lobby screen I pressed ready, joined shift, afked like 5 minutes. When I came back and went to maints, I noticed everything is fully bright AND I can see objects and players from far, as If I really had nightvision

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I think I had bit less fps, but I think it's normal, and related to having night vision.
![what](https://user-images.githubusercontent.com/35972878/35586601-8957692a-05fb-11e8-9405-e514fd8a0ee6.png)

**Comment by tigercat2000** [comment]
Well, Tajaran do have night vision, but not like this - The lighting overlays are entirely not rendering for you. I'm not totally sure what could cause this.

**Comment by DesolateG** [comment]
@tigercat2000 this was caused by lighting system bugging out. I've seen similar issues.

**Comment by Deelite34** [comment]
I'll close this, as I dont see it being fixed. It seems to be hardware-likeish issue, it happens when you let game load up, while having demanding game maximised, and taking up your graphical/etc resources
