### ISSUE TITLE
Oxygen Tanks Cannot Be Refilled Safely

### ISSUE THREAD

**Issue by Velleos** [ParadiseSS13/Paradise#8624]
If you allow an oxygen tank to become critically low, to the point you begin taking damage,
then remove, refill, and try to use it again, you'll still take damage from it as if it were empty.

How to reproduce:
Put on mining hardsuit with helmet and mask.
Place oxygen tank into a blue oxygen canister.
Fill to 1013psi.
Use until you see the oxygen warning, take damage, and the screen starts going dark.
Remove the oxygen tank, and then attempt to refill and use it.

I've had this happen several times, and I always have to grab a new tank.  I can safely fill the new tank
to 1013psi using the same canister as the bad tank, but I can never use the bad one again.

**Comment by MarsM0nd** [comment]
Don't think that's a bug, if a tank does drop the pressure below your distribution pressure, the distribution pressure does get set to it's maximum, which is the pressure of the tank. So simply resetting the distribution pressure of the tank should work.

**Comment by Velleos** [comment]
I'll check that.  Closing this report for now then.

**Comment by Velleos** [comment]
Also thanks.
