### ISSUE TITLE
Debug log generation with carded AI when clicking things at edge of vision

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#8630]
**Problem Description**:
What is the problem?
Guiltybeans bwoinked me saying I'm creating a bunch of debug logs in a round while I was carded. With experimentation, we found that clicking the feet of a vox that was on the extreme edge of my vision was causing it. Clicking on their head however did NOT cause it.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Be carded on the shuttle bridge in captain's pocket. Turn off UI with F12. Click on vox where circled. Enjoy debug logs.

![image](https://user-images.githubusercontent.com/521038/35669858-7f47371c-0704-11e8-94e9-596b8b450e3a.png)

**Comment by GuiltyBeans** [comment]
I have the debug logs here, just so it's clear on what ones were being produced.
![minlog1](https://user-images.githubusercontent.com/19163995/35669932-a2fb15e8-06eb-11e8-8669-a393b29f3c65.PNG)

**Comment by FunnyMan3595** [comment]
This has been fixed sometime in the intervening years.
