### ISSUE TITLE
Chugging from soda cans/ beer bottles/ anything that you need to open first.

### ISSUE THREAD

**Issue by IIWOLFII** [ParadiseSS13/Paradise#8638]
**Problem Description**:
You can chug contents of closed bottles which need to be opened first without opening them.

**What did you expect to happen**: 
I expected to not be able to chug through closed cans/bottles.

**What happened instead**:
Character chugs liquid of closed cans/beer bottles/etc.
**Why is this bad/What are the consequences:**
Muh immersun

**Steps to reproduce the problem**:
1. Get fresh space cola can from robust softdrinks
2. Hold it in hand
3. While holding it in hand drag can's sprite onto your character
4. Finish off the Space Cola!
5. Open the drink with an audible pop!
6. _None of Space Cola left, oh no!_

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Happens not only with space cola, but with all cans and beer bottles, everything like that

**Comment by taukausanake** [comment]
Bluespace magic

**Comment by davidchan13** [comment]
What kind of 3rd dimension primitive needs to open a bottle to drink from it? Next you're gonna complain about being able to eat a burger while wearing a gas mask in the middle of an N2O cloud.
