### ISSUE TITLE
Medhuds continue to be broken

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#8639]
**Problem Description**:
Dead mobs don't show the black bar of death, instead showing a non flashing critical.

**What did you expect to happen**: 
Dead mobs to show up dead on medhud.

**What happened instead**:
![dead corgi](https://user-images.githubusercontent.com/16112919/35761785-88d7e040-0841-11e8-9d87-56851164f7c0.png)

**Why is this bad/What are the consequences:**
Medhuds are still broken

**Steps to reproduce the problem**:
1. Be around a dead mob
2. Have a medhud/ghost medhud active
3. Wonder as to how death is considered critical condition in the case of triage.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by ScientistMan** [comment]
seems to be half broken, as it shows the skull, but seems to show the flashing bar as well. Blueshield/BrigMed Medical Sunglasses seemed to show all the station pets as some form of near death or severly injured, some more than others. I think it's an issue with the pets moreso than the huds themselves.

**Comment by DesolateG** [comment]
It also shows Runtime  (the cat) as being dead when alive

**Comment by taukausanake** [comment]
> Runtime as being dead when alive

Sweet. Now we just need a CMO named Schrodinger

**Comment by DesolateG** [comment]
Oh god

**Comment by alexkar598** [comment]
@LightFire53 , bug fixed please close
