### ISSUE TITLE
Some steps of ghetto surgery not working.

### ISSUE THREAD

**Issue by ZN23XZ** [ParadiseSS13/Paradise#8642]
**Problem Description**:
Cable coils are not working as a hemostat for the step of "Organ Manipulation" where you remove the organ.
Metal rods and pens do not work for drilling teeth for a dental implant.
After posting this I'll test as many surgeries as I can think of to see if there are any other steps that aren't working.

**What did you expect to happen**: 
I'm expecting to be able to perform all steps of any surgery with ghetto surgery.

**What happened instead**:
Can't perform all steps. In the specific example with organ manipulation the patient ended up dying because I needed to go get a hemostat.

**Why is this bad/What are the consequences:**
Unable to complete all surgeries with ghetto surgery. RIP my meme brig doc.

**Steps to reproduce the problem**:
Try performing ghetto surgery doing organ manipulation or dental implant, accidentally beat your patient repeatedly when you get to the step that fails.

**Comment by DesolateG** [comment]
Try mousetrap

**Comment by ZN23XZ** [comment]
Mouse trap didn't work either  (whether engaged or not). I also tested all other standard surgeries. The 2 listed in my initial post are the only steps I found that don't work.

**Comment by Serkket** [comment]
Fork is meant to take organs out and a screwdriver should be used for dental implants. Not sure where you're getting these steps from.

**Comment by ZN23XZ** [comment]
Just going by the tools the wiki lists.

![screenshot_20180210-030954](https://user-images.githubusercontent.com/26615673/36060110-5485c166-0e10-11e8-97d7-40b410ad9c82.jpg)

I dunno where the fork and screwdriver came from but I tested and they work. A fork to remove an organ makes me LMFAO as a bonus. Maybe I'll learn how to update the wiki and fix ghetto surgery.
