### ISSUE TITLE
Cargo Shuttle Gravity Problems

### ISSUE THREAD

**Issue by Renaultius** [ParadiseSS13/Paradise#8644]
**Problem Description**:
The 'Gravity!' popup occurs and I am dropped as if the gravity came on, whenever I try to step off of the mining shuttle.

**What did you expect to happen**: 
Since gravity is working both on the shuttle, off it, and on the spaces that the fall occurs, it seems like a bug.

**What happened instead**:
I got dropped on the ground for no apparent reason.

**Why is this bad/What are the consequences:**
It's mostly just a mild annoyance, but it could potentially have weirder gravity problems if shuttles are fucking up their gravity.

**Steps to reproduce the problem**:
The gravity was off for awhile from a power outage as the shuttle was returned; this indicates that the gravity coming back on and the shuttle returning happening at once causes the problem. I can't know for sure, though.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: That's about all I've got.

**Comment by Contrabang** [comment]
Was fixed at some point
