### ISSUE TITLE
MedHUD showing health of all creatures

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#8645]
**Problem Description**:
The Medical HUD shows the health of revs and borers, it may show the health of other creatures but I've not seen others yet.

**What did you expect to happen**: 
Not a health bar.

**What happened instead**:
You shouldn't be able to see a rev while he is invisible, the medHUD allows you to do this.

**Why is this bad/What are the consequences:**
It makes revs visible.

**Steps to reproduce the problem**:
Get a medical HUD and you can see the health bars above the rev.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I think the medical HUD is showing the health of all creatures instead of crew only.

**Comment by Aurorablade** [comment]
it supposed to show the hud of all creatures now.
 but rev is a bug.
