### ISSUE TITLE
[Meta] Arrivals pod bay outside freeze over

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#8647]
The tiles for the civi pod bay tend to feeze over. 

https://puu.sh/zgObV/45ab1a732b.png

**Comment by DesolateG** [comment]
Metastation?

**Comment by Eddyskingdom** [comment]
i think becouse the place spawns with air that is why it freezes becouse the atmost in game think it is a part of the station i needs air ter but becouse of being in space that happens but easy fix just need to move the shutter doors up one tile or make it that the atmosterics in game wont count the tiles

**Comment by SamHPurp** [comment]
@Eddyskingdom Nah, its a simple turf change, we have turfs that spawn with air and those that spawn without it.... and the wrong turf is used there. Would take seconds to fix.
