### ISSUE TITLE
Screen doesn't black out while unconscious.

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#8653]
**Problem Description**:
When unconscious due to having surgery happen to me, the screen didn't properly black out everything but my character.

**What did you expect to happen**: 
To not be able to see anything while unconscious.

**What happened instead**:
To see lots of things. See picture.![untitled](https://user-images.githubusercontent.com/32099540/35834252-29486974-0ad5-11e8-9383-52502cbef7a7.png)
Notice how I can still examine things and get the proper reply that I should while unconscious.

**Why is this bad/What are the consequences:**
You see what happens around you during surgery, I guess.

**Steps to reproduce the problem**:
I don't know.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I got attacked by a holopara and went to get surgery.

**Comment by DesolateG** [comment]
What damage did you have?

**Comment by florodude** [comment]
Were you under anethesia?

**Comment by TDSSS** [comment]
Yes, I was under anesthesia. That's why I was asleep. And I don't remember what damage specifically, but a lot of brute damage I think.

**Comment by Fox-McCloud** [comment]
Pretty sure this hasn't happened since.
