### ISSUE TITLE
Slime Management Console can see into maints adjacent to xenobiology

### ISSUE THREAD

**Issue by ID404-NotFound** [ParadiseSS13/Paradise#8655]
when using the slime management console, moving around with the [  ] selector, you can move it against the left walls, and see into the maint tunnels.

**Comment by taukausanake** [comment]
Already known. It's because the xeno area is part of the wall connecting to maint. Not something that's going to be fixed

**Comment by IK3I** [comment]
actually, probably very easy to fix. Just redefine the wall's area to maint instead of xeno....
