### ISSUE TITLE
Shadowling Thrall Icon covered by Mindshield.

### ISSUE THREAD

**Issue by EldritchSigma** [ParadiseSS13/Paradise#8677]
Well yeah got bwoinked and asked why I killed a deathsquad thrall, have send this as an answer:

https://imgur.com/a/H9g37

The Icon for the Mindshield covers the thrall icon. In the right corner of the screen. Not sure if it affects regular sec show up as thralls when mindshielded as one, but might be worth a look. For Streaky it looked like antag hud which basicly means it looks normal.

Why is this problematic? Thralls killing other thralls for not being able to see the icon.

Any ways to replicate? Become Deathsquad, get thralled, get robusted by a vox warden thrall with sec huds because the mindshield icon covers the thrall icon.

**Comment by taukausanake** [comment]
You can get mindshielded while thralled/thralled while mindshielded? That seems like the real issue here

**Comment by KingPhilipIII** [comment]
Mindshields buy you another ten seconds or so before thralling finishes but otherwise they're not foolproof for thralling.

**Comment by taukausanake** [comment]
It should maybe destroy the mindshield then unless it's intention is to make you still show up as shielded when you're against the corporation

**Comment by KingPhilipIII** [comment]
It does destroy the mindshield. But if you go get a new one so people don’t notice you’re missing it. Well. Here we are now.

**Comment by AffectedArc07** [comment]
Icons were changed ages ago, and you cant thrall mindshielded people anyways anymore. Closing.
