### ISSUE TITLE
Air Supply Vent in Execution Chamber doesn't Work

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#8687]
**Problem Description**:
The vent that is connected to a manual valve in the execution chamber for the unary vent in there doesn't actually work.  The vent is on and powered and the valve will be open but it doesn't actually pump air into the room.

**What did you expect to happen**: 
Air to be pumped into the room.

**What happened instead**:
Air wasn't pumped into the room.

**Why is this bad/What are the consequences:**
It makes it a huge pain in the ass to re-pressurize the execution chamber if security decides to execute someone via spacing or the vents are opened for whatever reason.

**Steps to reproduce the problem**:
Just suck the air out of the room, turn the valve in the execution chamber for the vent and see that it doesn't actually work.

**Comment by Sollessa** [comment]
Someone brought up that the problem might be the shutters in the execution chamber not being airtight after they are opened once, so the problem might not actually be the vent.

**Comment by SamHPurp** [comment]
I can't seem to re-produce so I assume this has been fixed, and never got closed?
