### ISSUE TITLE
Pod tracking device doesn't work on console

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#8694]
**Problem Description**:
What is the problem?
installing a space pod with a tracking device doesn't track it on the tracking console.

**What did you expect to happen**: 
Why do you think this is a bug?
It doesn't do what it's supposed to do

**What happened instead**:
How is what happened different from what you expected?

No tracking, the only pod tracked on the console is the secpod.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Redundant part that doesn't work and doesn't track space pods

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
build space pod tracking device
Install in spacepod
Check tracking console
refresh tracking console
see it doesn't track the spacepod

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by RyanSmake** [comment]
You did not activate the tracker.

**Comment by DesolateG** [comment]
Activate in hand or?

**Comment by RyanSmake** [comment]
Screwdriver, I think.
