### ISSUE TITLE
Vampire do not always show up on antaghud

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#8695]
**Problem Description**:
Roundstart vampires don't always show up on antaghud.

**What did you expect to happen**: 
I expected all vampires to show up as vampires on antaghud.

**What happened instead**:
Some roundstart vampires don't show up as antags at all on antaghud.

**Why is this bad/What are the consequences:**
Misleading.

**Steps to reproduce the problem**:
During a vampire round, enable antaghud. Check every vampire. Observe that not all of them have the red vampire symbol on antaghud.

**Comment by matt81093** [comment]
Not huge, but still odd

**Comment by Contrabang** [comment]
This has been fixed with datumization of vampires
