### ISSUE TITLE
Bugged Voxxy Sec gas mask

### ISSUE THREAD

**Issue by SplinterGP** [ParadiseSS13/Paradise#8697]
Problem Description: When you wear the sec gas mask as vox the sprite bugs 
![vox bugged](https://user-images.githubusercontent.com/29824735/36378702-8c649ab6-155a-11e8-9a26-7c48c37d3fe2.png)

Steps to reproduce the problem:Wear Sec Gas Mask as vox

Possibly related stuff : not sure but the way the sprite stays remembers me of the burned down face

**Comment by SplinterGP** [comment]
Now it turned that all masks Bugged my face , Reeee
![bugs](https://user-images.githubusercontent.com/29824735/36378939-8e0840e2-155b-11e8-999a-9c67a7e249d3.png)

**Comment by RedWolfie** [comment]
Could not reproduce

**Comment by Sirryan2002** [comment]
could not reproduce, closing
