### ISSUE TITLE
Dark Hephaistos IPC Screen Oddities

### ISSUE THREAD

**Issue by JordantheKitty** [ParadiseSS13/Paradise#8698]
**Problem Description**:
What is the problem?
Whether intentional or unintentional, by pressing the Random button for IPC heads in character creation, I obtained the mysterious Dark Hephaistos Screen. It looks pretty nifty and it isn't on the normal list of available heads, either in the creator or in-game IC actions which allow you to change the display.

![](https://i.imgur.com/JdSAwSa.png)
![image](https://user-images.githubusercontent.com/36649088/36401255-db9196a2-159b-11e8-9b3d-23d49b3db2b4.png)

It also doesn't work after the character's death. The screen remains in a black, broken state forever until I change it to one of the available screens with the Change Display command, and those don't work either. It only displays in a very pale grey, with very very little differences within the screen, for example,
Scanline only blinks one line sometimes off to the side of the character's face, like so
![image](https://user-images.githubusercontent.com/36649088/36401174-4e4a426c-159b-11e8-937f-68d230a84663.png)
![image](https://user-images.githubusercontent.com/36649088/36401182-59384b38-159b-11e8-950a-92eefffe94ce.png)
Here's Rainbow
![image](https://user-images.githubusercontent.com/36649088/36401204-7ab95996-159b-11e8-9c7f-1da412fabe8c.png)
And here's Nature
![image](https://user-images.githubusercontent.com/36649088/36401214-8f5fd0dc-159b-11e8-961e-1d2a9719eae8.png)
This might be because of my color option for the screen, which is pretty white

**What did you expect to happen**: 
It's odd that the screen didn't show up in the list and that it basically disappears after it breaks 

**What happened instead**:
Detailed above

**Why is this bad/What are the consequences:**
I don't know if I'd call it an IMPORTANT issue but here it is anyway, I'd like the head to not be taken away from me and for it to continue working after death, as it makes me feel special and unique

**Steps to reproduce the problem**:
I suppose see if you can get it to come up after clicking random on the screen(hair) selection, same as I did, and try out the different screens with different colors selected, and also die with the screen on the character

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing really here I can think of, but feel free to ask any questions you might have, and thank you for your time!

**Comment by variableundefined** [comment]
This is likely because random selection don't account for models_allowed which leads to a screen style fro hesp being applied to normal IPC head.

**Comment by Spaghetti-bit** [comment]
No longer an issue. I sat down for 5 minutes clicking random.


![image](https://github.com/ParadiseSS13/Paradise/assets/60483458/85f81ca1-85ba-4ff5-87f0-e001d7ee24a2)
It's also not available even through a magic mirror as it was before.
