### ISSUE TITLE
SECURITY CAMERA MAP STILL HAS SNOW IN IT

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#8702]
![f4375048f2](https://user-images.githubusercontent.com/13833056/36454813-622ddc30-1695-11e8-87fe-653c423ef219.png)

**Comment by RyanSmake** [comment]
Wait, since when do we have camera maps?

**Comment by alexkar598** [comment]
Since crew monitors?

**Comment by taukausanake** [comment]
Why was snow even put into the minimap anyways?

**Comment by alexkar598** [comment]
You can't choose what you want in the mini map,it just turned out the mini map was generated while the Xmas update was out

**Comment by taukausanake** [comment]
I really want to learn how to generate those maps

**Comment by SamHPurp** [comment]
This is really easy to fix, I've done pretty much all the minimap updates lately.

Ping me on Discord and I'll walk someone through it.
