### ISSUE TITLE
Changeling Last Resort Bug

### ISSUE THREAD

**Issue by Threeinone** [ParadiseSS13/Paradise#8703]
**Problem Description**: After laying eggs in a corpse as brain slug and bursting out caused HUD to disappear, pressing f12 seemed to fix the problem
What is the problem?

**What did you expect to happen**: Bursting out of the corpse as a monkey with the appropriate HUD for monkey/human after regaining human form
Why do you think this is a bug?

**What happened instead**: No HUD at all, active hand, inventory, nothing. morphing an armblade caused item sprite to hover over where the active hand should have been
How is what happened different from what you expected?

**Why is this bad/What are the consequences**: unknowing players of the f12 function could be helpless after this, not being able to play properly
Why do you think this is an important issue?

**Steps to reproduce the problem**: use last resort as changeling, lay eggs in human corpse and subsequently die, burst out as monkey, use powers to re-obtain human form.
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was at about 8% health. it was a particularly rotten corpse. it was naked in the chef's meat locker
Anything else you can tell us.

**Comment by dapocalypse** [comment]
Once they accept this will be fixed.

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/9223 fixes this
