### ISSUE TITLE
Borgs performing surgery do not have a fail chance on unanesthesized patients

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#8716]
**Problem Description**:
Medical cyborgs performing surgery on unanesthetized patients have no fail chance

**What did you expect to happen**: 
For surgery to go horribly wrong as the patient squirms around in pain

**What happened instead**:
Patient does not squirm around in pain and surgery steps are completed without a hitch

**Why is this bad/What are the consequences:**
Borgs should have to anesthetize people before operating on them just like regular crew do

**Steps to reproduce the problem**:
Do surgery on a non-catatonic person without anesthetic / painkillers and observe how if you are a borg performing the surgery it works but if you are not a borg then it will probably fail

**Comment by DesolateG** [comment]
Why would a machine with precision servos and pinpoint calculations slip during surgery?

This goes beyond a doctor with steady hands.

**Comment by Ty-Omaha** [comment]
Because the patient would be squirming about in an unpredictable manner that can't be instantaneously calculated by a machine.

But okay - Let's run with the argument of how they have instant calculation and can predict how someone will move. The body parts in question would still be open and subject to trauma caused by the squirming.

**Comment by taukausanake** [comment]
Yeah, I think they'll need to be under still in order for perfect surgery to be performed. Do borgs have any way to put someone on anesthetic or some other numbing drug? I would imagine they'd have access to ether

**Comment by DesolateG** [comment]
They have hydrocodone in their hyposprays, much better than ether.

**Comment by Denthamos** [comment]
I thought borgs were given Hydro in their hypo-sprays specifically for the surgery PR?  Yeah, seems like an oversight then if borgs have a 0 fail chance.

**Comment by DesolateG** [comment]
They were, and it is an oversight

**Comment by matt81093** [comment]
Has anyone taken this on?

**Comment by Birdtalon** [comment]
Seems like an intentional design choice.

https://github.com/ParadiseSS13/Paradise/blob/73cd6795e38a2676f1d7fe330ffbf05526fc4d75/code/modules/surgery/surgery.dm#L125
