### ISSUE TITLE
Xenobio console crash

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#8719]
This happend to jay a few times. I think it was switching out of console mode, unsure how hard its going to be to reproduce or if it related to the byond beta version.

I saw no runtimes relating to consoles.

**Comment by alexkar598** [comment]
Do we support beta yet?

**Comment by Aurorablade** [comment]
we support 512 or base support...but its cuase jay was running an old beta version..he fixed it when he upgraded.
