### ISSUE TITLE
Pipe dispenser pipes dissapear when wrenched

### ISSUE THREAD

**Issue by joonasm** [ParadiseSS13/Paradise#872]
taking a pipe out of the pipe dispenser and wrenching it to the floor will make the pipe dissapear

**Comment by TheDZD** [comment]
Yep, I've seen this happen before, although consistently replicating it can be a bit difficult. Once it does happen however, there doesn't seem to be an easy way to fix it, because atmospherics code is incredibly obfuscated.

**Comment by IAmBigCoat** [comment]
Fixed in #1068
