### ISSUE TITLE
Nitrogen has low specific heat

### ISSUE THREAD

**Issue by Pennwick** [ParadiseSS13/Paradise#8728]
**Problem Description**:
Nitrogen's specific heat value is low despite all material indicating that it absorbs heat well.

**What did you expect to happen**: 
When an equal number of moles of Oxygen and Nitrogen are mixed it should be mostly the temperature of the Nitrogen.

**What happened instead**:
It comes about about exactly average.

**Why is this bad/What are the consequences:**
The wiki stating that dumping lots of cold N2 to drop the temperature of a fire quickly is incorrect. Nitrogen is roughly on the same level as oxygen though obviously it has the slight advantage that it does not react. It also means that no gas has an appreciable heat capacity near plasma. This denies atmos techs the technique of dumping cold or even room temperature nitrogen into a room to help cool it down.

**Steps to reproduce the problem**:
Cool a nitrogen canister to -20 and leave an oxygen canister at +20. Mix the two and it comes out at 0. To test another gas that DOES have high specific heat cool a plasma canister to -20 and again use oxygen at +20, you'll get something below -10.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: [gas_mixture](https://github.com/ParadiseSS13/Paradise/blob/18f4aa18b98fcf8503f7173d3e294d581aa2acff/code/datums/gas_mixture.dm) code seems to confirm this. Nitrogen and oxygen are bunched together at 20 under air. Plasma is at 200. Further down it looks like N2 (oxygen_agent_b) is supposed to be 300, greater than even plasma. It looks like at some point the values were changed to match other codebases that have more gasses available including those with higher heat capacity. However we don't have these gasses at this point.

**Comment by MarcellusPye** [comment]
Working as intended

**Comment by tigercat2000** [comment]
Could you point out what materials indicate this? I suspect this is more of an issue with outdated documentation than a codebase error; supercooled N2 canisters were a far more popular strategy before LINDA was ported.

**Comment by taukausanake** [comment]
~~LINDA ironically breaking more things~~

**Comment by Pennwick** [comment]
Seems that things are working as intended. My mistake.

**Comment by davidchan13** [comment]
I know this is closed, but IIRC the reason the wiki calls for cooled N2 over something like CO2 is because Nitrogen is the least harmful of the gases to dump on a fire, CO2 had better heat capacity but it also suffocates any unfortunate soul that walks into the area after words.
