### ISSUE TITLE
Vending machine interface is just pure black.

### ISSUE THREAD

**Issue by lolzalolka** [ParadiseSS13/Paradise#8730]
**Problem Description**:
Every time I use the vending machine or any other activatable object I just see a black screen.

**What did you expect to happen**: 
It is supposed to show me a menu of items to purchase-.

**What happened instead**:
Instead a black screen appeared.

**Why is this bad/What are the consequences:**
I am unable to use any vending machine or any other machine that requires a menu to be operated.

**Steps to reproduce the problem**:
I went on Paradise station and attempted to purchase some seeds in botany, When I activated the seed vending machine it just turned out black.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing was out of the ordinary just a normal day abroad the station. No computer issues or anything, I've played on another server and the vending machine interface was fine.
https://cdn.discordapp.com/attachments/246712328232501249/420321864309800962/unknown.png

**Comment by taukausanake** [comment]
What version of Internet Explorer are you using? I think it has to be something above IE8 or 9 now because of BYOND but I can't recall the correct version

**Comment by alexkar598** [comment]
What windows version are you using?

**Comment by lolzalolka** [comment]
Win 7

**Comment by alexkar598** [comment]
Try going in preferences and where it is talking about nanoUI set it to no trills

**Comment by lolzalolka** [comment]
I'll try.

**Comment by lolzalolka** [comment]
This is a little embarassing but where is the NanoUi thing located?

**Comment by alexkar598** [comment]
assuming you are already in a game:
preferences tab --> Game preferences --> Fancy NanoUI --> needs to be at no

other wise:

Setup Character --> Game Preferences --> Fancy NanoUI --> needs to at no

**Comment by lolzalolka** [comment]
Alright thanks for clearing it out, i'll try it now.

**Comment by alexkar598** [comment]
did it fix anything?

**Comment by lolzalolka** [comment]
I can't actually do it currently, I'll have to try in about 10minutes

**Comment by lolzalolka** [comment]
I tried, its still just a black screen.
