### ISSUE TITLE
Ferry shuttle issues

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#8740]
This is a number of QOL improvements that could greatly benefit ferry shuttles.

1. Apply a spool up delay and shuttle spool up sound.
- This stops the inadvertent spacing of people as they are entering and exiting the shuttle when the shuttle transitions. Importance: Serious.

2. Immediately close and lock airlocks upon shuttle spool up.
- This stops fastmos issues under normal circumstances. The doors should be FULLY CLOSED before the shuttle leaves. See issue #8659 Importance: Low

**Comment by Aurorablade** [comment]
do you mean the admin ferry?

**Comment by Aurorablade** [comment]
also i am pretty sure the airlock thing has nothing to do with the shuttles, its gonna require the tiny fans needing to be added to the airlock areas or cycling airlocks. thats gonna need a maping change and/or system addition.

And not alot of people like the tiny fans for some reason...

**Comment by Anticept** [comment]
Any shuttles need to have their doors bolted closed (or rather, attempt to) before the shuttle moves. That's the core of the problem. They move before the doors close, and thus begin to vent before it finishes bolting.

And I mean all of them. Engineering, supply, labor, emergency shuttle, all of them.

**Comment by Aurorablade** [comment]
the doors do bolt and close on move last i knew. I think borgs can open them in flight i am unsure.

**Comment by Anticept** [comment]
They are supposed to bolt. They used to, anyways.

**Comment by Anticept** [comment]
They should close and bolt BEFORE the shuttle departs. The issue is that all shuttles begin to move before the doors are fully closed. Thus the atmos issues.

**Comment by matttheficus** [comment]
Stale request, closing.
