### ISSUE TITLE
Borg radio replacement issues

### ISSUE THREAD

**Issue by Zaraka** [ParadiseSS13/Paradise#8747]
**Problem Description**:
Borg came with destryoed parts, radio was one of them. After the replacement when borg tried to speak to it, message was relayed but he insisted he cant see radio communication.
borg analyzer reported 0 dmg, I've replaced radio several times with no results.
Probably worth investigating.

**What did you expect to happen**: 
Replacement radio should provide borg fill full radio experience.

**What happened instead**:
Borg could speak and send message, but he insisted he "can't hear himself"

**Why is this bad/What are the consequences:**
After people destroy our borgs radio, we can't fix them.

**Steps to reproduce the problem**:
1) Have a borg
2) Destroy his radio component
3) Replace broken radio component
4) Try relay and receive radio messages as that borg

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
It was the security model, lot of brute dammage, other components were destroyed as well, but replacemnet were working without problems.

**Comment by Citinited** [comment]
Did they forget to turn their internal radio on?

**Comment by DesolateG** [comment]
He didn't set his radio channels.

**Comment by Zaraka** [comment]
goddamit
