### ISSUE TITLE
infinite fish from fish bowls

### ISSUE THREAD

**Issue by rb303** [ParadiseSS13/Paradise#8753]
**Problem Description**:
you can get an infinite amount of fish using a fish scoop and fish bowl

**What did you expect to happen**: 
you should only be able to take out the amount of fish that's in the bowl

**What happened instead**:
you can get as much fish as you want

**Why is this bad/What are the consequences:**
gives the chef an infinite food source, could spam-create glofish during shadowling rounds, be annoying by creating a wave of clownfish, etc.

**Steps to reproduce the problem**:
1. put desired fish eggs in a fish bowl filled with water
2. use the fish scoop on the bowl, but ignoring the popup asking what fish you want to take out and instead keep clicking on the fishbowl with the fishscoop 
3. spam click "ok" and watch as the fish magically clones itself for every time you've pressed "ok" despite there being only one fish in the bowl

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by rb303** [comment]
![image](https://user-images.githubusercontent.com/25644617/37252648-bd52c8d8-251c-11e8-8fea-37c0f2bbe0ba.png)

**Comment by Spacemanspark** [comment]
Oh, it's the old poster ripping bug but fish

**Comment by FalseIncarnate** [comment]
Thought we fixed this, but if we did it got undone at some point.

Gist of the root cause is that it's only checking for fish when you initiate the harvest attempt, and not re-checking when you make the selection. Easy enough to correct, will fix tonight after work if someone doesn't beat me to it.
