### ISSUE TITLE
Teleporting via disposal bin

### ISSUE THREAD

**Issue by SkullyRoberts** [ParadiseSS13/Paradise#8758]
**Problem Description**:
What is the problem?
Basically, if you move a disposal bin without dissassembling or destroying it, it stays linked to the trunk it was built on. If you flush anything down the bin, it enters the disposals system via the linked trunk, regardless of distance.

**What did you expect to happen**: 
Why do you think this is a bug?
First off, you probably shouldn't be able to move disposals bins in the first place. They should break or dissassemble when removed from their trunk.
Second off, if somehow the bin IS moved from it's trunk, it shouldn't let you flush anything. The items should spit out, or the flush option shouldn't be available.

**What happened instead**:
How is what happened different from what you expected?
Turns out there are multiple ways to move disposals bins without destroying or deconstructing them, allowing them to stay linked to the trunk they were built on, regardless of distance.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It allows you to teleport items or people instantly without using any teleportation tech or magic.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1) Move a disposal bin without deconstructing or destroying it (the two ways I have found are putting an object set to recall inside it, then recalling it, bringing the bin with the recalled object; or using meteorshot to launch it back a few tiles)
2) Put an object or player inside of the disposal bin.
3) Flush said object
4) Gasp in amazement as the objects or player enter the disposal system via the trunk it was connected to, regardless of distance.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
Wow that's pretty cool. Recall spell can actually do that because it transports the storage item the linked item is in. I kind of thought that was a little weird though and gamey if done correctly. Maybe recall spell shouldn't do that?
Meteorshot (I'm guessing the shotgun shell and not the toy) does that?

**Comment by SkullyRoberts** [comment]
I have been told that meteorshot knocks them back if they hit it. But I haven't actually tested it yet.

**Comment by Citinited** [comment]
Imagine swapping two disposals bins with this method, and watching the confusion unfold

**Comment by SkullyRoberts** [comment]
@Citinited I mean, unless someone gets flushed down it, it probably won't change much. the biggest effect I could think of would be having disposal bins on station that would flush you into space

**Comment by taukausanake** [comment]
@SkullyRoberts or flush you into an emagged grinder

**Comment by matt81093** [comment]
There are some odd ways to use that..
