### ISSUE TITLE
Lower body and brains missing

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#876]
If an ipc takes enough damage they drop their lower body, and if you examine them, it doesnt say it's missing making it hard to re-attach legs and whatnot.
Also, if a head is experiencing enough force to cause it to explode, it does not drop a brain.

**Comment by TheDZD** [comment]
Head exploding not dropping a brain happens to everyone if they get their head delimbed by brute damage from a non-sharp source.

**Comment by ZomgPonies** [comment]
Fixed via #961
