### ISSUE TITLE
Cannot go into server 

### ISSUE THREAD

**Issue by roymz** [ParadiseSS13/Paradise#8768]
**Problem Description**:
![image](https://user-images.githubusercontent.com/37434381/37507426-54259b2e-28e6-11e8-8f81-9688405ac9d6.png)

when logging in the server, it shows this image then nothing happens. 

**What did you expect to happen**:

Log in the server 
Why do you think this is a bug

Because it prevents me from logging in 

**What happened instead**:

I was not able to log in 
![image](https://user-images.githubusercontent.com/37434381/37507460-7af139f2-28e6-11e8-967e-424b757ded0f.png)

How is what happened different from what you expected?

It usually just logs me in the server 

**Why is this bad/What are the consequences:**

I am not able to play on the server
Why do you think this is an important issue?

i am not able to play on the server

**Steps to reproduce the problem**:
Log in the server 
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by alexkar598** [comment]
Did you click on the link?

**Comment by roymz** [comment]
yes

**Comment by alexkar598** [comment]
What version of Internet explorer and widows do you have?

**Comment by roymz** [comment]
i have no clue, why does it matter

**Comment by Spacemanspark** [comment]
Byond uses IE a lot, unfortunately.
Windows can be related depending on the version, I believe, though not sure how.

**Comment by roymz** [comment]
ok. i just downloaded the most recent version and it's still broken :(

**Comment by matt81093** [comment]
@roymz Unfortunately, this isn't a code base issue, so this shouldn't really be here. Regardless, I suggest clearing your byond cache by opening the byond settings menu, navigating to Games, and selecting 'clear cache'. Failing that, try reinstalling byond?
