### ISSUE TITLE
Admin tickets bugs and issues.

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#8771]
- [x]  Preferences toggle doesn't work.
- [ ] My tickets shows other people's ahelps.
- [x] Mhelps bleed into admin tickets.
- [ ] Tickets being assigned to the wrong user.

Potential Features / extensions
- [ ] SQL Database Integration.
- [ ] Admin PMs have the option to open a ticket.

**Comment by Ty-Omaha** [comment]
Mhelps also bleed into them sometimes iirc

**Comment by Tayyyyyyy** [comment]
It might be sorta nice if you could initiate a ticket. Maybe if you PM someone, there could be an option of opening a ticket for the conversation, if you anticipate that it's going to be more lengthy.

**Comment by Tayyyyyyy** [comment]
I've just noticed issues with PMs from other tickets being added to the wrong ticket.

**Comment by FunnyMan3595** [comment]
It's likely that this has been fixed sometime in the intervening years.
