### ISSUE TITLE
Examining Holodeck Tiles Freezes Game

### ISSUE THREAD

**Issue by mass595** [ParadiseSS13/Paradise#8786]
**Problem Description**:
Whenever you Examine any tiles in the Holodeck, (via Shift-clicking or by right-clicking and selecting Examine) your client freezes for a couple seconds

**Steps to reproduce the problem**:
- Go to the Holodeck
- Examine any tile within the Holodeck
- Feel the wrath of Lag'sie

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This has been tested with multiple users both in-game and observing, consistently freezing each client for a couple seconds. The bug only seems to happen with certain Holodeck rooms, particularly the combat simulation rooms or those with Plating tiles in them.

**Comment by alexkar598** [comment]
Plating tiles?

**Comment by MarsM0nd** [comment]
Yeah, it seems to be only the tiles that look like the plating without a floortile. That's there in the thunderdome court, for example, and checking it with VV, i found this:
```
icon_plating = "plating"
icon_regular_floor = "dont_use_this_floor" 
icon_state = "dont_use_this_floor" 
```
What i think is the issue: The icon_state is no valid state, so for examining, it falls back to send every icon in floors.dmi, which causes the extreme lag. For what's lying on the floor, i figure it's either falling back to the normal plating icon. 
I did edit the icon_state to plating, and when examined, that tile didn't cause problems anymore.

**Comment by Spacemanspark** [comment]
This also happens on the Trurl with certain plating tiles near the ferry shuttle.

**Comment by taukausanake** [comment]
Wait, the Trurl is an actual location in the map files? I don't remember seeing that anywhere, unless it's part of some area of Centcomm

**Comment by Spacemanspark** [comment]
Trurl is the name of Central Command, where the shuttle docks at the end of the round

**Comment by taukausanake** [comment]
Always thought the Trurl was some offsite comms station and CC was just called CC. The more you know

**Comment by Crazylemon64** [comment]
Oh, did someone remove that icon state? I had that there to make sure people didn't use the base-level turf due to it not having a lot of important functionality defined.

**Comment by Crazylemon64** [comment]
oh my glob am I stupid it's called "dont_use_this_tile" not "dont_use_this_floor" im smrt
