### ISSUE TITLE
[PS -> StonedMC] Processes to be converted

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#8799]
This serves as a tracker for the Process Scheduler -> StonedMC milestone.

Processes to be converted:
 - [x] alarm https://github.com/ParadiseSS13/Paradise/pull/11361
 - [x] event https://github.com/ParadiseSS13/Paradise/pull/11360
 - [x] fast_obj https://github.com/ParadiseSS13/Paradise/pull/11364
 - [x] fires - #8798
 - [x] garbage https://github.com/ParadiseSS13/Paradise/pull/8824
 - [x] lighting https://github.com/ParadiseSS13/Paradise/pull/11357
 - [x] machinery https://github.com/ParadiseSS13/Paradise/pull/8947
 - [x] mob https://github.com/ParadiseSS13/Paradise/pull/8947
 - [x] nanohunter https://github.com/ParadiseSS13/Paradise/pull/9476
 - [x] nanoui https://github.com/ParadiseSS13/Paradise/pull/8820
 - [x] npcai https://github.com/ParadiseSS13/Paradise/pull/9459
 - [x] npcpool https://github.com/ParadiseSS13/Paradise/pull/9459
 - [x] obj https://github.com/ParadiseSS13/Paradise/pull/11364
 - [x] radio https://github.com/ParadiseSS13/Paradise/pull/11350
 - [x] shuttles https://github.com/ParadiseSS13/Paradise/pull/9477
 - [x] sun https://github.com/ParadiseSS13/Paradise/pull/8810
 - [x] ticker https://github.com/ParadiseSS13/Paradise/pull/11368
 - [x] timer https://github.com/ParadiseSS13/Paradise/pull/8946
 - [x] weather https://github.com/ParadiseSS13/Paradise/pull/9050
 - [x] voting https://github.com/ParadiseSS13/Paradise/pull/11350

**Comment by alexkar598** [comment]
Should we not use github's project feature inserted or clogging the issues tracker?

**Comment by alexkar598** [comment]
Inserted meant to be instead ,damn mobile

**Comment by tigercat2000** [comment]
@alexkar598 Nah. I tried projects and it's like a shitty version of trello. This works with milestones, which are easier to manage.

**Comment by MrMagolor** [comment]
With tigercat gone, is this project dead, too?

**Comment by Fox-McCloud** [comment]
No. Just ongoing.

**Comment by AffectedArc07** [comment]
SSlighting is up on #11345 if that needs editing in, or do we wait till the PS is closed, whatever the PR Is linked here now

**Comment by KasparoVy** [comment]
Congrats
