### ISSUE TITLE
Using vision altering equipment like Thermals, or the shadowling's Darksight causes the game window to freeze and require a relog.

### ISSUE THREAD

**Issue by Samarai** [ParadiseSS13/Paradise#8800]
**Problem Description**:
To extend on the already-wordy title, using darksight, or thermal goggles will often cause the game window to freeze, but only the game window. This means that you can still see chat, hear sounds, and even interact with the world around you, including mousing over objects, but all graphics will be frozen, rendering the game pretty much unplayable until you relog.
**What did you expect to happen**: 
I expected using darksight to, well, work without causing this bug.
**What happened instead**:
Using darksight causes the graphics to freeze.
**Why is this bad/What are the consequences:**
If it isn't obvious, especially when working as an antagonist such as a shadowling, having to relog can be a death sentence, and considering how often it happened to me on a recent round it rendered me useless.
**Steps to reproduce the problem**:
1. Enable darksight as a shadowling.
2. Walk around for a bit, or just wait. The time it takes is completely random for me, at times it would take a few minutes, and before I gave up on the round it happened as soon as I had relogged back into the game to solve the issue in the first place.
3. Eventually the game window freezes. 
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a shadowling round, I was a shadowling. It always happened whilst using darksight, it was just a matter of time. No other bugs were happening.

**Comment by alexkar598** [comment]
Byond version?
