### ISSUE TITLE
attack code runtime

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#8815]
[14:28:00] Runtime in item_attack.dm,20: undefined proc or verb /mob/living/carbon/human/attack obj(). 
   proc name: attackby (/obj/attackby)
   usr: CHARNAME (CKEY) (/mob/living/carbon/human)
   usr.loc: The floor (158,132,1) (/turf/simulated/floor/plasteel)

Also potentially this one too:
[12:45:47] Runtime in walls.dm,332: undefined proc or verb /turf/simulated/floor/plating/dismantle wall(). 
   proc name: attackby (/turf/simulated/wall/attackby)
   usr: CHARNAME (CKEY) (/mob/living/carbon/human)
   usr.loc: The plating (155,64,1) (/turf/simulated/floor/plating)
   src: the plating (154,64,1) (/turf/simulated/floor/plating)
   call stack:
   the plating (154,64,1) (/turf/simulated/floor/plating): attackby(the welding tool (/obj/item/weapon/weldingtool), CHARNAME (/mob/living/carbon/human), "icon-x=21;icon-y=-17;left=1;sc...")
   the welding tool (/obj/item/weapon/weldingtool): melee attack chain(CHARNAME (/mob/living/carbon/human), the plating (154,64,1) (/turf/simulated/floor/plating), "icon-x=21;icon-y=-17;left=1;sc...")
   CHARNAME  (/mob/living/carbon/human): ClickOn(the plating (154,64,1) (/turf/simulated/floor/plating), "icon-x=21;icon-y=-17;left=1;sc...")
   the plating (154,64,1) (/turf/simulated/floor/plating): Click(the plating (154,64,1) (/turf/simulated/floor/plating), "mapwindow.map", "icon-x=21;icon-y=-17;left=1;sc...")

Probably related to: https://github.com/ParadiseSS13/Paradise/pull/8674

**Comment by uraniummeltdown** [comment]
I myself have never experienced these, if anyone has info on reproducing these do tell

**Comment by Kyep** [comment]
For the first case, it is here:https://github.com/ParadiseSS13/Paradise/blob/76631d0dab1fc04855f23b526985c6974b67b479/code/_onclick/item_attack.dm#L20
It uses I.attack_object()
If you pass in a human mob as I, for example, by doing M.attack_object(something), you will get that runtime.
The runtime suggests that, somewhere.... something is calling mob.attack_object(something else). Not sure where, but somewhere.

The second one appears to be here:
https://github.com/ParadiseSS13/Paradise/blob/76631d0dab1fc04855f23b526985c6974b67b479/code/game/turfs/simulated/walls.dm#L332
Specifically that the proc is being called from an instance of /turf/simulated/floor/plating somehow. No, I'm not sure how. But that's what the runtime suggests.

**Comment by Citinited** [comment]
I think the second one will be fixed by #11700 - this is triggered by welding the same wall twice, and then waiting for both timers to run down. The first one works fine, then the second one fails, as by that time the wall is no longer a wall, but itself.

**Comment by Fox-McCloud** [comment]
object damging and tool behaviors fixed this
