### ISSUE TITLE
Constant screaming and the inability to leave, if you have no legs and you are placed on a mulebot

### ISSUE THREAD

**Issue by Tename** [ParadiseSS13/Paradise#8828]
**Problem Description**:
Putting a person with no legs on a mulebot causes them to constantly scream and collapse they are also unable to leave the mulebot https://i.gyazo.com/bcdbfb3db8cfb64721d7963e4cc11e88.gif

**What did you expect to happen**: 
To be able to sit on the mulebot

**What happened instead**:
Constant screaming 

**Why is this bad/What are the consequences:**
You can put someone with no legs on it and they will not be able to leave unless they get outside help also the screaming is annoying

**Steps to reproduce the problem**:
Have no legs hack a mulebot have someone put you on it

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing that would be related

**Comment by taukausanake** [comment]
That gif is _so small_! But yeah that guy is falling all over that mulebot

**Comment by KasparoVy** [comment]
Don't drink and ride.

**Comment by Citinited** [comment]
I'm going to assume that the mulebot trampling over prone mobs is to blame

**Comment by taukausanake** [comment]
but the mob was above the mulebot, as in loaded on to it I think OP is saying? Was the person taking any damage?

**Comment by Tename** [comment]
No damage was being taken.
