### ISSUE TITLE
When non-cultist releases you from shard, message you receive is bugged. ((and 2 more minor issues))

### ISSUE THREAD

**Issue by BottomQuarks** [ParadiseSS13/Paradise#8833]
**Problem Description**:
I was killed and sharded by cultist Otsuka Misaka. Security captured them.

First issue: I was able to pull cultist from officer grip when I was still shard and in cultist backpack.

Second issue: I was released from shard form by security officer that was NOT cultist.
I recieved message "You have been released from your prison, but you are still bound to Kaizen-5's will. Help them succeed in their goals at all costs." Kaizen-5 was security officer that released me.

Third issue: No idea if it's intended, but as Shade I was able to access others equipment and take off their equipment ((and cuffs))

**What did you expect to happen**: 
I really have no idea what should happen. I got so confused that I decided to a-help that. I literally had no idea if I have to serve security now. But from what admins said, that should not matter at all, and I should recieve message that I still serve the cult.

**What happened instead**:
I recieved message "You have been released from your prison, but you are still bound to Kaizen-5's will. Help them succeed in their goals at all costs."

**Why is this bad/What are the consequences:**
Well I recieved information that I am bound to security officer now. I a-helped that, but some players will help security. Also at the time admins responded, cultist that sharded me, was already deconverted.

**Steps to reproduce the problem**:
Step by step:
-I was killed and sharded.
-Security detained cultist
-Cultist ordered me to pull her out from officer grip, and as shard in her backpack I was able to do that.
-Officers brought cultist to processing, Kaizen-5 released me from the shard.
-I received information that I am bound to Kaizen-5
-I a-helped that. Cultist got deconverted.
-When I got information that I am still part of the cult, I escaped brig.
-Later I as shade, pulled another cuffed cultist from officer grip, took off the cuffs.
-I was killed by officer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Well It was cult gamemode, Beside the things I mentioned, everything was normal

**Comment by Crazylemon64** [comment]
One issue per issue report please
