### ISSUE TITLE
Clown Can Kill Himself with Toy Double E Sword

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#8838]
**Problem Description**:
Clown Can Kill Himself with Toy Double E Sword

**What did you expect to happen**: 
The Clown not to impale himself with a Toy

**What happened instead**:
I near killed myself by hitting someone with a toy

**Why is this bad/What are the consequences:**
The Clown can kill himself with a Toy (one that can be used for pranks at that)

**Steps to reproduce the problem**:
Get Toy double e sword, be clown, attack someone with it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by taukausanake** [comment]
That is hilarious. [This](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/twohanded.dm#L227-L236) proc in `/code/game/objects/items/toys.dm` needs to be overridden in the toy object. Shouldn't be tough to do

**Comment by davidchan13** [comment]
I don't see any issue here /s

(Seriously please don't fix this :laughing:)

**Comment by Fox-McCloud** [comment]
I'm not sure if this should be fixed or not, to be honest. This is rather hilarious.

**Comment by KasparoVy** [comment]
Agreed

**Comment by taukausanake** [comment]
Guess I can't be bothered then
