### ISSUE TITLE
Space Vines are Indestructable 

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#8839]
See title.

@uraniummeltdown

**Comment by Crazylemon64** [comment]
Indestructible, as in they don't take damage, or as in they're ridiculously robust and can outpace reclamation efforts?

**Comment by KasparoVy** [comment]
They have become immune to damage not dealt by goats, weed killer, or bombs.

**Comment by LightFire53** [comment]
Gentlemen, we are experiencing evolution at its finest. All hail the Great Vine.

**Comment by shazbot194** [comment]
I will say, I was able to drill them in a mech while this bug was going on

**Comment by KasparoVy** [comment]
Because drilling calls `ex_act(2)`.
https://github.com/ParadiseSS13/Paradise/blob/1fffea7aa8f86cb23066599cdd0721dd0ca3d81e/code/game/mecha/equipment/tools/mining_tools.dm#L35
