### ISSUE TITLE
Cheese Wheel (and other food items) need to be cut with any sharp items

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#8842]
**Problem Description**:
Cheese Wheel, Bread and other stackable food items can only be cut by a kitchen knife and nothing else that'd count as sharp - such as a glass shard or an activated energy sword.

**What did you expect to happen**: 
I don't think the kitchen knife should be the only thing that could cut up food items, it makes no sense.

**What happened instead**:
If you try to cut food with an esword or a glass shard, it gets inserted instead.

**Why is this bad/What are the consequences:**
This has become problematic balance-wise and I think it should be fixed to prevent nukie rounds becoming boring. The last two weeks, in every nukie rounds I participated, the strategy is this: get as many cheese wheels as you can, even (quite literally) milking the biogenerator for milk if needed, put the NAD into the first one, put the wheels into each other, make sure the nukies cannot get a kitchen knife. (All knives vended, autolathe is probably blown up in Cargo.)

I know there is a storage capacity now and you could eat the cheese wheels but as a nukie I am always well-fed for the movement speed buff so I doubt I could eat two or three entire wheels.

**Steps to reproduce the problem**:
1) Get a cheese wheel
2) Try to slice it with an esword
3) Lose esword

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by alexkar598** [comment]
Sorry,not a bug it's a feature request

**Comment by FalseIncarnate** [comment]
Technically a feature request as Alexkar stated, however it also is viewable as a consistency issue, as many other sliceable things can be cut up with any sharp object.

Would probably be best to give the user an option between "slice" and "stash" for anything sharp, so you can hide a knife in a cake to deliver to your brigged fellow antag, or use it to serve up some slices.

**Comment by Miraviel** [comment]
You're right @alexkar598 , apologies.

I should've opened this as a PR but I could not find the part responsible for slicing.

**Comment by Birdtalon** [comment]
@Miraviel 
https://github.com/ParadiseSS13/Paradise/blob/971ef9216ad0f014d521b65f2a4941a0e212ef9f/code/modules/food_and_drinks/food/snacks.dm#L135-L166
