### ISSUE TITLE
You can use cryo as a way to metagame and respawn

### ISSUE THREAD

**Issue by Shadowflame909** [ParadiseSS13/Paradise#8844]
**Problem Description**:
I entered cryosleep on a long going round and ghosted. Then I re-entered my body, all I got was a black screen. It was weird, So I thought I crashed and re-connected. I came to onto the lobby screen with the ability to rejoin the game as crew.

**What did you expect to happen**: 
I expected it to say when I tried to rejoin my body, "You have no body."
**What happened instead**:
I re-entered my body, my screen became black. My visual hotkeys were there, but my body was black as if I died.
**Why is this bad/What are the consequences:**
This is an important issue because it's an easy street to metagame the antag, "Oh boy cult/shadowlings time to go roam maint" and no admins were on at the time when I found it.

**Steps to reproduce the problem**:
1. I played for a while, an hour and 11 minutes into the round. I got bored and went into cryo-sleep and ghosted. 
2. I re-entered my body to see what happened. 
3. Instead of being greeted with "you have no body." I re-entered my body with a black screen, my visual hud hotkey and a black visual on my body as if I died. 
4.But for the most part, it seemed that I lost connection, so I re-connected. Putting me back in the lobby.
**Possibly related stuff (which game mode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was ling + vampires, but nothing really out of the ordinary was happening.  Just the round went on for an hour and 11 minutes.

**Comment by alexkar598** [comment]
Respawn would be a nice thing to try but this is a bug regardless

Also did you get the gravity icon while in that black screen?

**Comment by alexkar598** [comment]
I meant lack of gravity icon

**Comment by Shadowflame909** [comment]
Maybe? I don't believe so.

**Comment by Anticept** [comment]
Confirmed that this does work.

**Comment by tigercat2000** [comment]
@Anticept Could you provide more detailed instructions on how to reproduce this?

**Comment by Anticept** [comment]
The post already has the information required to reproduce. I showed it to @DarkPyrolord
