### ISSUE TITLE
Tracking Implants vanish when dropped or stored in bag.

### ISSUE THREAD

**Issue by davidchan13** [ParadiseSS13/Paradise#8863]
**Problem Description**: Tracking implants cases deleted/disappear, rendered unusable.

**What did you expect to happen**:  Placing a tracking implant cases in any location will keep it there for later use.

**What happened instead**: After picking up a tracking implant cases, setting the case down, dropping it, placing it on a table or putting it in your bag, box or other storage item destroys the implant. No message in the chat window indicates this is intended. Bag slots are 'filled' but not interactable. Examining the tile via alt click or right click does not show implants that should be there.

**Why is this bad/What are the consequences:** No other implant does this. Being unable to move/store tracking implants means that security can not be restocked.

**Steps to reproduce the problem**:
(RnD does research, Print Tracking Implant)
Pick up implant.
Place the implant case anywhere or drop it.
Implant case will disappear, if placed in bag slot will be 'empty' but unable store item or interacted with without emptying bag entire by drag dropping.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

Removing the implant from the case (via Implanter) allows case to be moved around as normal. Placing implant back in case and interacting with it causes it to be deleted upon being set down.
Dragging implant cases does not produce this effect.
Round type was secret - Traitors.

**Comment by SkeletalElite** [comment]
This reminds me, as of late I've had to have a few traitors have their storage implants removed and unless there was some major incompetence going on from the doctor (because they said they saw the implant and removed it) the storage implants disappear after being surgically removed. Possibly related.

**Comment by Plotron** [comment]
@SkeletalElite, as far as I remember (and I'm a relatively old player) that surgical implant removal thing was intended. It was discussed somewhere in this repo a few years ago.

**Comment by davidchan13** [comment]
The fact that it doesn't have a description of the item being destroyed makes me doubt any of this is intentional, especially when empty implant cases can be moved around freely.

To reiterate, these items were being deleted the moment they left a person's hand. Even alt + clicking to examine and entire tile's contents did not show any sign of them. Given that there is a lockbox in the HoS office and armory full of these implants, I find it extremely unlikely that these items were never intended to be stored for later use, let alone setting them upon a table.

**Comment by Plotron** [comment]
@davidchan13, of course this particular behavior is NOT intentional. I even lost a couple of death alarm implants this way as well. It used to work, now it doesn't.

I was talking about surgical implant removal some long time ago.
