### ISSUE TITLE
deactivated swarmers are invincible

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#8873]
title

**Comment by KasparoVy** [comment]
Disposal machine

**Comment by Citinited** [comment]
message

throw them in the recycler

**Comment by theColdflame** [comment]
lasers and emps destroy swarmers

deactivated swarmers are swarmers

deactivated swarmers ren't destroyed by lasers and emps

**Comment by tigercat2000** [comment]
Not a bug. They're items. To fix this would require rewriting half of item code to let them be destroyed by damage types.
