### ISSUE TITLE
Windoors require the same damage as a door to actually start taking damage

### ISSUE THREAD

**Issue by Bram961** [ParadiseSS13/Paradise#8878]
Essentially to break a windoor right now your only option is to steal one of the sparse amount of axes on the station or get your hands on things that do higher damage like syndicate gear to be able to break a windoor.

I think this is an oversight from when the new damage system was implemented. what should happen is that windoors are still just window doors that can be "easily" broken, that being after 10 or 20 hits from something like a wrench.

EDIT: I mistakenly thought the windoors had the same damage values as doors. what is actually happening is that it is lower but not low enough for all tools that usually functioned to break them to actually break them. as a result it is sort of arbitrary what does and does not break the windoors.

**Comment by R1f72r** [comment]
To be fair one is metal the other is a glass, reinforced albeit but still glass. I think it’s intentional or at the very least I think it’s fine as-is.

**Comment by mass595** [comment]
I am pretty sure it is fine as-is. Windoors are thin, entirely glass window-doors, as their name suggests. I do not think they are meant to be as durable as thick, reinforced Airlocks.

**Comment by taukausanake** [comment]
Yeah, I would understand if it was made out of plain glass but all windoors are some kind of reinforced. I think the plain windoors should be plain glass and whatever the secure windoors are to be reinforced, but that's a different subject altogether

**Comment by Fox-McCloud** [comment]
This is working as intended. Nothing is wrong here. Windoors have a force threshold of 10. If they start sparking when you hit them, you're damaging them, otherwise, you're not accomplishing anything.
