### ISSUE TITLE
Issues are overrated

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#8888]
Solves 8888 being overrated.

closes: https://github.com/ParadiseSS13/Paradise/issues/8888 ?!?

**Comment by Citinited** [comment]
RIP

**Comment by KasparoVy** [comment]
Ah, the deep end.

**Comment by R1f72r** [comment]
;-; dammit

**Comment by taukausanake** [comment]
Well someone had to do it. Now to wait for #9999 whenever it comes
