### ISSUE TITLE
The cloner biomass can go into the negatives.

### ISSUE THREAD

**Issue by veganzombeh** [ParadiseSS13/Paradise#889]
I can't be very specific because I don't know how it occured, but the cloner biomass went into the negatives and we essentially had infinite biomass.

http://imgur.com/I02wdIB

**Comment by Spacemanspark** [comment]
I think we should get rid of Biomass anyways.

**Comment by tigercat2000** [comment]
I've seen this before- I believe it has to do with autocloning, it must skip the biomass check when going straight to a new record
