### ISSUE TITLE
You can't deconstruct airlocks with an RCD

### ISSUE THREAD

**Issue by uraniummeltdown** [ParadiseSS13/Paradise#8890]
**Problem Description**:
Cannot deconstruct airlocks with an RCD

**What did you expect to happen**: 
"Deconstructing airlock..." and then the airlock being deleted

**What happened instead**:
The airlock opened (if I had access) or beeped deny

**Why is this bad/What are the consequences:**
Can't quickly decon airlocks

**Steps to reproduce the problem**:
Set RCD to Deconstruct mode, try to deconstruct an airlock

**Comment by Anticept** [comment]
A workaround for this was to set harm intent. Removes and RCDs would then work.
