### ISSUE TITLE
Slime People body sprites are.. iffy at best

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#890]
Already reported on the coderchat, posting here as well for more detail

Slime People's new r_ icobase stuff is broken. By broken, I mean that things are out of place, and generally just don't make any sense. The entire thing is supposed to be greyscaled, but there are still random blue pixels around. Female and Male body sprites are no different, they are exact duplicates as far as I can tell. The really *really* big issue is the r_foot sprite.

This is the right foot file
![ugh](http://puu.sh/hs367/f1d14337d8.png)

This is the left foot file
![oh god why](http://puu.sh/hs38e/a9752c5e1a.png)

See the problem yet? 
Compare it to the human version;
![ugh](http://puu.sh/hs367/f1d14337d8.png)![so much better](http://puu.sh/hs3lR/ed415179a8.png)
![oh god why](http://puu.sh/hs38e/a9752c5e1a.png)![yesss](http://puu.sh/hs3nx/f1d228a131.png)

**Comment by Fox-McCloud** [comment]
@ZomgPonies

**Comment by tigercat2000** [comment]
I would also like to note that the slime people sprites, with being their own icobase and having no human sprite under their overlay, look flat and just really bad to me- but that might be a personal thing

**Comment by ZomgPonies** [comment]
They've been fixed via well something or another.
