### ISSUE TITLE
Slime brain

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#891]
The slime brain is the core, and this is in the upper body, currently, the mind is not bound to it, and is instead bound to the head, thus decapitation killing and sticking the mind in the decapitated head.

**Comment by TheDZD** [comment]
The slime brain is not in the upper body, it is located in the head. It is a parent object of regular brains, and since it does not redefine the parent organ defined [here](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/brain/brain_item.dm#L14), it inherits it.
