### ISSUE TITLE
Too many attack logs.

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#8910]
**Problem Description**:
A bunch of un-needed attack logs appear in round.

**What did you expect to happen**: 
Us to only have to deal with the pain of boxing gloves and the holodeck.

**What happened instead**:
We see all types of action happening, such as disarms, passive grabs, hugging...

**Why is this bad/What are the consequences:**
If my chat scrolls any faster I'll have a seizure.

**Steps to reproduce the problem**:
Try and administrate a server at peak time for five minutes and attempt to remain sane.

**Comment by tigercat2000** [comment]
Please provide specific log examples you would like disabled @Spartan6

**Comment by Allfd** [comment]
DEBUG: WORLD/TOPIC: "status&key=****" is one I keep seeing.  I am calling that like every 10 seconds from the backend..

**Comment by Dumbdumn5** [comment]
Options to toggle things that aren't damage dealing attacks, i.e. old attack logs that were pretty much only attacks that dealt damage, stuns, and stun batons, though for whatever reason, boxing gloves were included in that.

At the moment we see hugs, shakes, grabs, disarms, and the works.

**Comment by Spartan6** [comment]
`ATTACK: Weaponized toaster/(Mr Beret)(?) (FLW) vs Weaponized toaster/(Mr Beret)(?) (FLW): Shaked`
`ATTACK: Bet100214/(I.D.107)(?) (FLW) vs Administrator/(monkey (636))(?) (FLW): Disarmed`

`ATTACK: Bet100214/(I.D.107)(?) (FLW) vs Administrator/(monkey (636))(?) (FLW): Pushed over`
`ATTACK: Skruples/(Phoenix Rahl)(?) (FLW) vs INVALID/(monkey (755))(?) (FLW): Melee attacked with fists`

Also fuck these while we’re at it.
`ATTACK: tayi/(Tilakakiki)(?) (FLW) vs tayi/(Tilakakiki)(?) (FLW): Melee attacked with Boxing`
`ATTACK: tayi/(Tilakakiki)(?) (FLW) vs tayi/(Tilakakiki)(?) (FLW): attacked with Holographic Energy Sword (INTENT: HELP) (DAMTYPE: STAMINA)`

**Comment by Kyep** [comment]
We don't need to see:

- when someone attacks themselves
- when someone attacks someone else with any weapon that does 0 damage

**Comment by Tayyyyyyy** [comment]
Can we also get rid of this one?
`ADMIN LOG: Game mode failed to find ANY chumps. Possible causes: no one is opposed/skeptical, or FalseIncarnate can't code.`
