### ISSUE TITLE
Crematorium tray affected by gravity

### ISSUE THREAD

**Issue by Aracino** [ParadiseSS13/Paradise#8914]
**Problem Description**:
When you open the tray in the chaplains crematorium in 0 g, like when the gravity gen is out of power, it floats away. Closing the crematorium magically pops the tray back into place.

**What did you expect to happen**: 
The tray to not float away.

**What happened instead**:
Said tray floated south.

**Why is this bad/What are the consequences:**
It can make opening the tray annoying during 0 gs. Also I don't believe it's intentional.

**Steps to reproduce the problem**:
Turn off the grav-gen, open up the crematorium tray. Watch the tray float away, close to teleport it to the crematorium.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: None at the moment, outside of this possibly affecting the morgue trays as well? I haven't tested it.

**Comment by davidchan13** [comment]
Seems related to #2540 and likely overlooked but not fixed by #7341

**Comment by tigercat2000** [comment]
#notabug #workingasintended

**Comment by tigercat2000** [comment]
(aka this is now an official feature because it's hilarious and doesn't do anything gamebreaking)

**Comment by davidchan13** [comment]
@tigercat2000 If we're gonna be dedicated to the joke you could at least update the crematorium with some blurb about not opening in zero gravity situations to avoid getting ash everywhere.

**Comment by taukausanake** [comment]
@tigercat2000 and maybe also actually spread ashes everywhere if you do. Lots of black smoke and maybe some mess effects on the floor
