### ISSUE TITLE
Large windows unclosable

### ISSUE THREAD

**Issue by TinyFox42** [ParadiseSS13/Paradise#8917]
**Problem Description**:
What is the problem?
Whenever I open up a large window in the game, like the alarm monitoring console, the header of the window (and the exit button) will be above the top of the screen:
![image](https://user-images.githubusercontent.com/29414385/39218527-36fabdd2-47f3-11e8-8dda-614b93ae81f5.png)
The only workaround I have found so far is to reconnect to the game, which causes me to go SSD for a few seconds.

**What did you expect to happen**: 
Why do you think this is a bug?
I should be able to close it without that much effort.
**What happened instead**:
How is what happened different from what you expected?
I need to reconnect and go SSD for a few seconds.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's annoying, making me less willing to open up those windows, which can make jobs harder.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

1. Open up the alarm monitoring console with a screen size close to mine.
2. See that you can't close it easily.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Probably only for screen sizes close to mine, otherwise it would probably have been reported by now. My screen size is (as best as I can figure out) 1366 X 768.

**Comment by tigercat2000** [comment]
This is technically a bug with Windows, but we can probably shrink some windows by default

**Comment by Chronarch2954** [comment]
As a fix (workaround?) for this: Preferences tab ==> Game Preferences ==> Turn "Fancy NanoUI" OFF

**Comment by Citinited** [comment]
It's a bit late but you can alt-f4 the window to close it, if you click on it :P
