### ISSUE TITLE
Monkey cubes do not grow in a shower

### ISSUE THREAD

**Issue by Soyweiser** [ParadiseSS13/Paradise#892]
If you unwrap a monkey cube and put it under a shower it does not grow into a monkey.

**Comment by Fox-McCloud** [comment]
Not really a bug, per se---and to be honest, not something I'm really willing to fix, personally.

Monkey Cube respond to water universally---and they have a snowflake check for sinks--another one would have to be made for showers.

Given how snowflakey showers already are and how niche activating a cube in a shower is---eh.

**Comment by Soyweiser** [comment]
Snowflakey? Don't really know that term. You mean like a special exception case I assume.

I assume the whole monkey cube code is one big exception then. As it is not the same as corgium. Due to the cubes being an actual object.

**Comment by CrAzYPiLoT-SS13** [comment]
Snowflakey = not really optimal level of coding

**Comment by tigercat2000** [comment]
Fixed by #983.
