### ISSUE TITLE
Nano-UI is gone from exosuit fabricators

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#8923]
**Problem Description**:
Exosuit fabricators has reverted to using a simple UI

**What did you expect to happen**: 
For Nano-UI to be utilized as before when using exosuit fabricators.

**What happened instead**:
A simple text UI was brought up.

**Why is this bad/What are the consequences:**
Losing Nano-UI on something that had Nano-UI before is not good, since we are trying to standardise on Nano-UI.

**Steps to reproduce the problem**:
Open up an exosuit fabricator.
https://puu.sh/Aa9cb/6a6c2d5370.png

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This is probably a direct result of #8901

**Comment by Fox-McCloud** [comment]
That said, this style UI that it previously had *will* be returning. Its reverting to the white UI was a full on mistake on my part.
