### ISSUE TITLE
Emptying Laden Satchels of Holding & Ore-boxes can Hang/Crash

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#8943]
**Problem Description**:
You are able to hang/crash the server by sufficiently filling ore boxes/satchels of holding. Although ore-boxes are ever-so-slightly less crashy, but that may be random chance.

**What did you expect to happen**: 
No-one should have this ability

**What happened instead**:
I expected the satchel/ore-box to spew my loot without crashing the server

**Why is this bad/What are the consequences:**
You can hang/crash the server with 100% reliability, but it takes time to mine the ore to do so.

**Steps to reproduce the problem**:
Mine the entire mining z-level with an ore box or satchel of holding, then empty it

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
There were a ton of pugs/corgis/foxes on station along with about 60 active players, 80 clients, but this hangs/crashes the server regardless of other load

**Comment by KasparoVy** [comment]
Might be a job for `CHECK_TICK` or some other voodoo.

**Comment by KasparoVy** [comment]
[This](https://github.com/tgstation/tgstation/blob/a1b89c36432b924e298298c6a43ee923f44bea93/code/datums/components/storage/storage.dm) is definitely relevant. Ties into components.

**Comment by Allfd** [comment]
@KasparoVy Thank you!  This is super helpful.

@Fox-McCloud @tigercat2000

**Comment by Fox-McCloud** [comment]
`This issue would probably be resolved by implementing /datum/component/storage`

Probably not, to be honest. Having dumping things call `CHECK_TICK` will help some, but the problem still exists, unfortunately.

Making ores a `stack` will help an ok amount; maybe together they can prevent this, but, to be honest, if someone makes a deliberate point of collecting every single ore on the asteroid, then dumping it all at once---notttt much to prevent that.

**Comment by KasparoVy** [comment]
Thanks for the insight, `/datum/component/storage` looked promising which is why I thought I'd mention it

**Comment by Fox-McCloud** [comment]
Oh, it is promising. It'll be a pain in the butt to implement, but it's infinitely better than storage being either some copy-pasted nightmare snowflake or relying on something to be a child of `/obj/item/storage`

It's one of those "needed badly, extremely good ideas, but burdensome to implement and no one really wants to do it".

**Comment by Fox-McCloud** [comment]
Should be resolved *for now*.
