### ISSUE TITLE
Aurora Caelus Notifications are Missing Punctuation

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#8945]
**Problem Description**:
The Aurora Caelus finale message is missing some punctuation, namely spaces and capitalization.

**What did you expect to happen**: 
We've got punctuation most everywhere else.

**What happened instead**:
There are numerous punctuation and spelling errors.

**Why is this bad/What are the consequences:**
Game breaking lack of punctuation ruins immersion.

**Steps to reproduce the problem**:
Be in a round with the Aurora Caelus mini-event.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Secret rotation, nothing out of the ordinary. Happens every Caelus event.

See below:
![image](https://user-images.githubusercontent.com/12377767/39407350-b7b08216-4b92-11e8-9f50-f24d0647471f.png)

**Comment by Citinited** [comment]
Also Aurora Caelus should be capitalised

**Comment by KasparoVy** [comment]
Updated preview pic

**Comment by Spartan6** [comment]
There's also an error in the first event I believe, with a lack of spacing.

**Comment by KasparoVy** [comment]
Title amended to vaguely reflect the fact that all notifications, both before and after the event, should be checked

**Comment by Tayyyyyyy** [comment]
Meteorology is also spelled wrong!

**Comment by KasparoVy** [comment]
God speed.
