### ISSUE TITLE
Returning player unable to select any roles except for Civilian Jobs and Karma Unlocks

### ISSUE THREAD

**Issue by Novacro** [ParadiseSS13/Paradise#8952]
**Problem Description**:
Some returning players may be unable to select any job except for Civilian jobs and whatever else they had unlocked via the Karma system

**What did you expect to happen**: 
Returning players who had the prerequisite time unlocked prior to leaving should be able to select any role

**What happened instead**:
I wasn't able to select any jobs except for Civilian Roles and the NanoTrasen Representative (my only Karma unlock).

![ss13 bug](https://user-images.githubusercontent.com/38815537/39411223-dff3f78a-4bba-11e8-93e2-ba7428f6bdc9.PNG)

**Why is this bad/What are the consequences:**
Returning players may want to play some role other than Civilian. In this case, I was hoping to be able to jump into an Internal Affairs role before immediately jumping back to NT Rep. It should absolutely be noted that the timers **do tick down** with time spent playing, so it will very quickly become a non-issue for most players.

**Steps to reproduce the problem**:
Likely very difficult for anyone else to reproduce. When I had first taken a break from the game, there was no time-gating system in place for roles (that I was aware of.) I rejoined some time after its implementation.

**Possibly related stuff**
I had attempted to rejoin the server with an out-of-date BYOND client, was unable to join, and reinstalled the client to join. Returning player is "Novacro" on the server.  Issue persists through multiple restart attempts.

**Comment by Fox-McCloud** [comment]
If you haven't played in like 2 years, "tough luck". We gave a grace period, but that time has long since passed.

Would need to know exactly when you stopped playing.

**Comment by alexkar598** [comment]
So,is this an issue or not?

**Comment by tigercat2000** [comment]
`If you haven't played in like 2 years, it's a "tough luck" situation. We gave a grace period, but that time has long since passed.`
