### ISSUE TITLE
Duplication with igniter assemblies

### ISSUE THREAD

**Issue by Flip-Sandwich** [ParadiseSS13/Paradise#896]
Basically, if you can click really quick enough you can duplicate igniter/*thing* assemblies, basically fooling the game into thinking an igniter or a remote signaller or a timer what have you. Fool the game into thinking that you didn't already use it. Can use this to get two igniter/timer assemblies for the price of one or what have you.

**Comment by Fox-McCloud** [comment]
Tried to replicate this, but was unable to.
