### ISSUE TITLE
metastation map curruption issue

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#8961]
![image](https://user-images.githubusercontent.com/25136265/39446940-23e32154-4c8e-11e8-8464-4a7963326c40.png)

**Comment by tylerh95** [comment]
Could this also have to do with the two rotated chaplain carpet tiles and #9012 ?

**Comment by alexkar598** [comment]
Chaplain tiles probably but not #9012, that one is a problem with the away mission loader and has nothing to do with currupted keys in meta's file

**Comment by alexkar598** [comment]
Are the chaplain tiles on meta?
