### ISSUE TITLE
Entering Cryo with a Holopara

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#8962]
**Problem Description**:
If you enter cryo when you have a holopara it breaks the AI and they keep spamming comms with "insert name here as entered cryo storage"
**What did you expect to happen**: 
For the person to be put in cryo storage like any other person

**What happened instead**:
Well as the holopara when I was ghosted I was stuck with a black screen and teleporting didnt fix it. Re logging fixed the black screen
and also AI was spamming chat with the person entering cryo storage

**Why is this bad/What are the consequences:**
[insert name here] has entered long-term storage
[insert name here] has entered long-term storage
[insert name here] has entered long-term storage
[insert name here] has entered long-term storage

**Steps to reproduce the problem**:
Have a holoparasite, enter cryo

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by alexkar598** [comment]
You were probably sent into null space

**Comment by Fox-McCloud** [comment]
I can't replicate this; care to explain exactly what happened/where the holo para was, and what the master and guardian both tried to do?

**Comment by SkeletalElite** [comment]
So I was a holopara (standard type I believe, hard to remember) for someone. Then they entered cryo but their body didn't get put into long term storage right away. So I waited for a few minutes then eventually I got turned into a ghost in the middle of a black screen which I could only escape via relogging. When this happened AI kept repeating that the person had entered long term storage over and over again until I assume an admin intervened and fixed it. I was not manifested. Not once did I manifest.

**Comment by Birdtalon** [comment]
Related

```[2018-05-23T21:55:29] Runtime in mob.dm,538: type mismatch: null -= Guardian Spirit (/mob/dead/observer)
   proc name: reset perspective (/mob/dead/reset_perspective)
   usr: Guardian Spirit (ducktalon) (/mob/dead/observer)
   usr.loc: The floor (42,146,1) (/turf/simulated/shuttle/floor)
   src: Guardian Spirit (/mob/dead/observer)
   src.loc: the floor (42,146,1) (/turf/simulated/shuttle/floor)
   call stack:
   Guardian Spirit (/mob/dead/observer): reset perspective(the floor (42,146,1) (/turf/simulated/shuttle/floor))
   Guardian Spirit (/mob/dead/observer): Login()
   Guardian Spirit (/mob/dead/observer): Login()
   Nickel Daisy (/mob/living/simple_animal/hostile/guardian/punch): ghostize(1)
   Nickel Daisy (/mob/living/simple_animal/hostile/guardian/punch): ghostize(1)
   Nickel Daisy (/mob/living/simple_animal/hostile/guardian/punch): Destroy(0)
   Nickel Daisy (/mob/living/simple_animal/hostile/guardian/punch): Destroy(0)
   Nickel Daisy (/mob/living/simple_animal/hostile/guardian/punch): Destroy(0)
   Nickel Daisy (/mob/living/simple_animal/hostile/guardian/punch): Destroy(0)
   Nickel Daisy (/mob/living/simple_animal/hostile/guardian/punch): Destroy(0)
   ...
   Osbert Allen (/mob/living/carbon/human): Destroy(0)
   Osbert Allen (/mob/living/carbon/human): Destroy(0)
   Osbert Allen (/mob/living/carbon/human): Destroy(0)
   Osbert Allen (/mob/living/carbon/human): Destroy(0)
   Osbert Allen (/mob/living/carbon/human): Destroy(0)
   Osbert Allen (/mob/living/carbon/human): Destroy(0)
   Osbert Allen (/mob/living/carbon/human): Destroy(0)
   qdel(Osbert Allen (/mob/living/carbon/human), 0)
   Osbert Allen (/mob/living/carbon/human): Ghost()```

**Comment by Contrabang** [comment]
Fixed when cryo was refactored by Farie for simplemobs cryoing
