### ISSUE TITLE
Cassette Tape cannot be removed from container; behaves like police tape

### ISSUE THREAD

**Issue by Glorken** [ParadiseSS13/Paradise#8973]
**Problem Description**:
If you put a cassette tape into a container, it cannot be removed. You receive the message, "You lift the tape, allowing passage," as if it were a tile of police tape.

**What did you expect to happen**: 
I thought that I would be able to remove the tape from my backpack.

**What happened instead**:
See problem description.

**Why is this bad/What are the consequences:**
A container's slots become full of cassette tapes.

**Steps to reproduce the problem**:
Stick a cassette tape into a bag. Try to remove the cassette tape.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Possibly related to #8951

**Comment by Fox-McCloud** [comment]
Ahhhhhhhhhhhhhhhahahahahahahahahahahah. Hhahahah.

Oh my gosh, so that's why tape doesn't work.

`/obj/item/tape` already existed.

`/obj/item/device/tape` because `/obj/item/tape`.

Oh my goodness, Fox, you dunce.

**Comment by Glorken** [comment]
So it's an issue with #8927?

**Comment by Fox-McCloud** [comment]
Yep.
