### ISSUE TITLE
Mining Issue

### ISSUE THREAD

**Issue by TonyOrcy** [ParadiseSS13/Paradise#8986]
**Problem Description**:
After some time mining in the Asteroid Mine, the log goes blank and new text appears and disappears repeatedly.
Not only that, but restarting the game causes it to crash every time it finishes loading up.

**What did you expect to happen**: 
Log should continue to function normally and no crashes should occur.

**What happened instead**:
The opposite.

**Why is this bad/What are the consequences:**
Game becomes unplayable. Which is frustrating. (Specially when you are a miner lost somewhere with a box filled with juicy minerals ready to recharge the station and fill my wallet of points and can't do shit about that, possibly dying without oxygen in the middle of nowhere)

**Steps to reproduce the problem**:
Use the Kinect Thingie, spend 25 minutes of round time in the Asteroid Mine mining as much ore as you can. Pull a box with you everywhere, emptying your bag in it at every chance you have, intermittently. Watch your game slowly break.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I am not a very experienced player, yet. I can tell it looked like any regular round, stuff was going on in the radio, but i was out there in the Asteroid Mine.
So, what i can tell is: It happened twice, each time on a different computer (my PC and my notebook).
I am really convinced it has something to do with the amount of minerals inside the box, causing the game to go nuts. (I am a really competent miner, without false modesty)
The first time the crashes didn't occur once i tried to log back in, because of that (very possibly): I restarted JUST after loading the ores in the machine on Cargo. Fixing my game's log, chat and everything, completely.
When i decided to restart the game, still with the ore box filled astronomically, i just couldn't connect back in, it would crash 100% of the times i tried, until a new round started.

**Suggestion**:
The lazy way would be to simply give the Ore Box a maximum limit of ores it can have. Thought that would make mining quite a bit more tiresome.
Making the ores inside the box completely "ethereal", appearing inside of it completely subjectively, could perhaps, make it less resource intensive?
I also suggest someone investigate it, because if that's really the problem, that infinitely filled ore box, even if the chances are low, could potentially become a grieffing nuke.

**Comment by KasparoVy** [comment]
Have never run into this, personally, even after strip-mining the entire asteroid

**Comment by TonyOrcy** [comment]
Hmmm... Could be, i recently got the crash problem again, so it's probably unrelated. Got me confused because it never happened before, and now twice in a row.
However the log problem happens every time and follows just as i stated. Since the crash is unrelated, this is a very minor issue.
Apologies for the mistake.

**Comment by KasparoVy** [comment]
Thanks for reporting it though. I wish I could give you a straight answer but unfortunately crashes like this are a mystery

Assuming Windows OS my advice would be to:
1. Back up your data
2. Make sure everything is updated (drivers etc)
3. Clean the registry w/ CCleaner
4. Test RAM and CPU stability
5. Roll back to a known good restore point
Then as a last resort perhaps a fresh install of Windows

Good luck
