### ISSUE TITLE
Cult Joined Souls Unable to Pull Through Cuffs/Holy Water, even with three people.

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#9007]
Problem: The cult's joined souls rune is currently intended to be able to pull cultists with cuffs on them, or holy water in them, if the rune is on the same Z-level and has three summoners instead of two.

What I expected: After using the rune with three people on the same Z-level, to have the target pulled to the rune. If not enough cultists were there, then to be prompted that three are needed.

What happens: The rune fails to pull anyone with handcuffs or holy water.

Why is this bad: Cultists are getting confused on why it doesn't work, and Joined souls as a rune has lost a lot of its use outside of forcing slow cultists to get to the summon rune.

How to reproduce: Slap cuffs on a cultist or feed them holy water, then try to summon them with 3 invokers.

Other Information:
I took a look through the cult/runes code, and I suspect the problem is just with line 878, trying to call invokers < 3  instead of invokers.len < 3 as other runes requiring multiple invokers uses.
I have no idea how to test code myself though, so I can at least submit a bug report.

**Comment by FalseIncarnate** [comment]
Would probably be the fact that it is looking for `< 3` (more than 3 invokers) instead of `<= 3` (3 or more invokers) in the code. As a result, you'd currently need 4 invokers to summon a restrained cultist despite the message saying 3. Changing this to a `<=` will make it work with 3 as the message says

**Comment by Pckables** [comment]
You're misreading it, as < 3 is Less Than 3. The code checks a bunch of fail-states, rather than a success, and having less than 3 cultists while holywater/cuffs are present leads to a failure.

Also, Invokers is an array, not a variable.
