### ISSUE TITLE
Map Loader cannot place /obj/item.

### ISSUE THREAD

**Issue by Fruerlund** [ParadiseSS13/Paradise#9010]
**Problem Description**:
Placing map templates with debug tools will place the map template fine, but all items of path /obj/item/... will not be pasted. 

`[2018-05-12T22:42:00] Runtime in code/modules/awaymissions/maploader/reader.dm,239: Bad path: /obj/item/weapon/paper_bin
   Source String: /obj/structure/table/reinforced,/obj/item/weapon/paper_bin{pixel_y = 5},/obj/item/weapon/pen,/turf/unsimulated/floor{icon_state = "dark"},/area/centcom/specops
   dpos: 72
   src: /dmm_suite (/dmm_suite)
   usr: Logan Ghost (fruerlund) (/mob/dead/observer)
   usr.loc: space (71,96,2) (/turf/space)`

**Comment by tigercat2000** [comment]
This isn't a bug, your saved map template uses the `/obj/item/weapon` typepath, which was removed wholesale. You need to mass-replace `/obj/item/weapon` with `/obj/item`.
