### ISSUE TITLE
fastmos oversight(item blenders)

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#9011]
**Problem Description**:
What is the problem?
fastmos is too powerfull to kill anyone

**What did you expect to happen**: 
Why do you think this is a bug?
its ridiculous a single tile breach is more deadly than a syndicate minibomb

**What happened instead**:
How is what happened different from what you expected?
i expected to not insta die

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
insta death are bad gameplay and i do not think a single breach killing 5 people is normal

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
collect many items near a single tile
rcd deconstruct the tile
laugh as no one can fix the breach before getting nuked

How to fix: insteed of throwing the objects,move them(i think its step() but i could be wrong)

**Comment by tigercat2000** [comment]
Issue reports are for *bugs*, unintended problems with the code.
This is literally an intended feature that has had multiple PRs to create and adjust it.
