### ISSUE TITLE
Gateway has no destination.

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#9012]
**Problem Description**:
What is the problem?
Gateway has no destination

**What did you expect to happen**: 
Why do you think this is a bug?
Until about 1 or 2 weeks ago, you could enter gateway. Then, something changed and you can't enter anymore

**What happened instead**:
How is what happened different from what you expected?
You are not able to enter gateway.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It completelty removes point of gateway

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Turn on gateway
2. Try to walk into it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Muhdir** [comment]
This is probably why this is happening
![gateway](https://user-images.githubusercontent.com/38748088/39970226-38379306-56e8-11e8-8b11-612ba300bcb3.png)

A whole chunk of the gateway is just gone. I saw it happening twice now. Unless this is admemed ofcourse.

**Comment by Fox-McCloud** [comment]
@tigercat2000
