### ISSUE TITLE
putting glass sheets into backpack doesnt automatcally fill them into a stack

### ISSUE THREAD

**Issue by chesse20** [ParadiseSS13/Paradise#9027]
**Problem Description**:
What is the problem?
if you put sheets of glass into your bag indvidually they just stay as seperate bugs
**What did you expect to happen**: 
Why do you think this is a bug?
doesnt make sense
**What happened instead**:
How is what happened different from what you expected?
i expected them to automataclly make one stack
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
harder to pick up glass
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
put 1 stacks of glass into backpack

**Comment by taukausanake** [comment]
Not a bug. Click the glass in-had on to the stack if you want to add it together. Otherwise keeping separate stacks is preferred because maybe you want a certain amount at a time.

**Comment by theColdflame** [comment]
not a bug, decent idea for a feature tho

**Comment by Fox-McCloud** [comment]
Suspect you come from TG or a TG codebase. This isn't a feature here, so definitely not a bug.
