### ISSUE TITLE
Laser tag gun projectiles make melee attack sound when striking mobs

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#9034]
**Problem Description**:
Laser tag gun projectiles play the default "clunk" sound when they strike a mob.

**What did you expect to happen**: 
The projectile to play a laser sound effect when it collides with a mob.

**What happened instead**:
It played a melee hit sound

**Why is this bad/What are the consequences:**
Playing an unintended sound

**Steps to reproduce the problem**:
Shoot a mob with a laser tag gun

**Comment by alexkar598** [comment]
Were you at melee range?

**Comment by Birdtalon** [comment]
No it was a ranged attack.

**Comment by KasparoVy** [comment]
Can verify, happens all the time
