### ISSUE TITLE
Aliens Hatching in a Xenomorph Hunter's Stomach can't be regurgitated.

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#9048]
Problem:
If a Xenomorph hunter devours a an infected person (maybe they are trying to get them out of surgery), and that infected person then bursts inside the hunter, the larva is still birthed, but stuck inside the Hunter, unable to be regurgitated.

What Should Happen:
The larva should either be able to be regurgitated, or the infected person should not be able to be devoured.

Why it's Bad:
I don't think larvas appreciate being trapped in a Hunter's stomach, possibly unable to die.

How to Reproduce:
As a hunter, devour someone close to bursting, and have an observer accept the alien pop-up. When they burst, the alien will be inside the hunter but the hunter will not regurgitate anything.

Possibly related stuff:
I was ventcrawling during the burst when I first encounted this, but testing outside the vent proved similar results.

**Comment by tigercat2000** [comment]
The issue here is that they're not in the hunter's stomach, they're in their contents, as if they were a locker. This... isn't really trivial to fix.

**Comment by Crazylemon64** [comment]
This could be fixed with `drop_location`
