### ISSUE TITLE
re-enter corpse button has broken interaction with demons

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#9049]
if you ghost after being dragged to hell and then re-enter corpse you're taken to a black screen with HUD. from here, you cannot ghost using the movement keys and ghosting via verb forfeits respawn rights. this is not ideal as players who use the re-enter corpse verb are forced to stare at a black screen until the demon is dead or forfeit their respawn right.

**Comment by tigercat2000** [comment]
This is kinda odd, because humans get put inside the slaughter demon after getting 1000 brute. Unghosting should give you a view of the slaughter demon and ghosting shouldn't forfeit rights since you're dead.

**Comment by alexkar598** [comment]
edge case

**Comment by theColdflame** [comment]
this is an edge case and is easy to avoid if you know about it but it's still something that would be fixed eventually in an ideal world

**Comment by Contrabang** [comment]
Not able to reproduce after 5 years of needing verification
