### ISSUE TITLE
Medbay airalarm placement

### ISSUE THREAD

**Issue by Allfd** [ParadiseSS13/Paradise#9059]
**Problem Description**:
Medbay air alarm is blocked during emergencies.

**What did you expect to happen**: 
The air alarm to receive updated information.

**What happened instead**:
If the fire shutters close, the air alarm is cut off from receiving new air samples.

**Why is this bad/What are the consequences:**
Unpredictable atmospherics behavior.

**Steps to reproduce the problem**:
Pull the fire alarm.

![image](https://user-images.githubusercontent.com/8165455/40398198-b75df94a-5e04-11e8-95dc-9ffb9f756aa0.png)

**Comment by FreeStylaLT** [comment]
They're for Engi+ only, this enforces that properly.
![img](https://cdn.discordapp.com/emojis/422715225662554113.png?v=1)

**Comment by Crazylemon64** [comment]
duplicate of #8823
