### ISSUE TITLE
Tajaran night vision is based on movement.

### ISSUE THREAD

**Issue by Draxtheros** [ParadiseSS13/Paradise#9089]
**Problem Description**:
What is the problem?
Whenever a Tajaran is not moving, his sight stops working on seemingly random tiles. Some things I can still see bright as... night, but I can see them, others just turn black. I haven't yet picked out any correlation between what decides what I can and can't see while standing still.

**What did you expect to happen**: 
Why do you think this is a bug?
I'm not a reverse T-Rex, mostly. Also it didn't work like this a couple of weeks ago

**What happened instead**:
How is what happened different from what you expected?
I can't see when I don't move.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
One of my racial perks isn't working unless I pace restlessly in the dark

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I stepped into the darkness. Beyond that, it's been a persistent issue for a couple of weeks now.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
![8](https://user-images.githubusercontent.com/39882288/40888558-94c3d512-671e-11e8-825d-ad39d057a5ae.png)
![9](https://user-images.githubusercontent.com/39882288/40888559-94d273e2-671e-11e8-9bf2-42ab3043dabf.png)

**Comment by KasparoVy** [comment]
It's a bug with BYOND prevalent on other servers using a similar lighting system from what I can tell, happened after a recent beta patch.

**Comment by tigercat2000** [comment]
https://secure.byond.com/forum/?post=2369592

This should be fixed in the latest BYOND versions when both the server and client are running them.

**Comment by KasparoVy** [comment]
Sweet.
