### ISSUE TITLE
Round Start m onkeys Gib with Mutagen, Monkey Cube monkeys don't.

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#9101]
Something has recently changed that has reversed the monkey cube monkeys and roundstart monkeys regarding unstable mutagen.

Now, the roundstart monkeys will gib with mutagen, but the monkey cube monkeys will only get DNA powers/defects, and from the looks no humanization.

**Comment by davidchan13** [comment]
No more humanized monkeys? I'm okay with this, fuck cling/vamp cheese.

**Comment by granodd** [comment]
The roundstart monkeys used to not be able to gib with the double mutagen injection. Monkey cube monkeys always gib when you double mutagen inject them, which is what a lot of scientists do to get brains and hearts for R&D.

Do you mean that the monkeys are exploding (or a lack thereof) after only one injection?

**Comment by DesolateG** [comment]
Monkey cube monkeys don't gib at all, and roundstart will gib with 5u of mutagen
