### ISSUE TITLE
I messed with Byond itself a year ago and have royally screwed myself.

### ISSUE THREAD

**Issue by SpectreSpecter** [ParadiseSS13/Paradise#9103]
**Problem Description**:
I remember that I had a friend and I wanted to invite him to Paradise, but who didn't have a PC at the time and he had something of a mac or was on the phone. I don't clearly remember, however I tried at the time to use my PC to use a BYOND Webclient By Pirion (link: https://secure.byond.com/developer/Pirion/WebClient). Whether it worked or not, I'm not curtain, however it has caused an anomaly in which I am not curtain to fix.

**What did you expect to happen**: 
I expected with some hard effort, I could learn then teach the ways of how to set a webclient of Byond on a mac and we could play together.

**What happened instead**:
Instead, for some reason which I forgot, The webclient didn't work, something deep in the byond's structure as a game changed that I cannot fix with updating or uninstalling the game and it doesn't even work when I am the one who created the server. (Using: (https://nanotrasen.se/wiki/index.php/Creating_your_own_paracode_server). Ah, I should say that the Error was... and I quote; "Encountered an improper argument."

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's bad because once I realized I basically locked myself out without knowing how, I couldn't invite him even if I wanted to. 

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Make a friend who doesn't own a PC and instead owns only a mac. Think of inviting that person to a Paradise game, then realize that the downloaded version only works for windows. So try to make a webclient, which in your mind might work for a Mac and see how you could change it to do so. Once going to far as you realize that you do not know the proper way back, panic and try to remember for the life of you how you came to this point. Once Paradise Station is forgotten for a month in your mind, a year passes and a video from Cry and Russ appears to show you the fun and idiotic side of Paradise station again. Realize after one year the same problem you had last and this time try to download the game so that you could run it on a server, only to see that it's not a valid in connection. Then try to ask the community if they know a way to clean and delete **EVERY. SINGLE. TRACE. of BYOND** from there computer, including things such as from REGEDIT and unknown places of the like.

**Is there anyway that we as a community can help to provide assistance in the matter that you are having difficulties in?**
If you know a way to clean and delete **EVERY. SINGLE. TRACE. of BYOND** from my computer, including things such as from REGEDIT and unknown places of the like... Then please tell me. I need to know to play Paradise Station.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
The gamemode was Life. I was assisting a friend. I probably stopped the end of the world, but who cares about that with you have a problem like this.

**Comment by Taaketa** [comment]
Eh, shouldn't you contact Byond support and not some random server that uses the Byond engine?

**Comment by KasparoVy** [comment]
They'll revert to us eventually I'm sure due to the nature of games having varying levels of browser compatibility

**Comment by alexkar598** [comment]
@SpectreSpecter 

double check the circled thing is setted to English(United States)
![image](https://user-images.githubusercontent.com/25136265/41177189-3322cff4-6b31-11e8-8f93-b096db7dd76b.png)

**Comment by SpectreSpecter** [comment]
@alexkar589 While that did work, I do find that strange. From what I know in the past, I always used Japanese Locale and it still worked. Was it a god awful timing that BYOND changed when I did that or was it something else to begin with? Anyways thank you so much!

**Comment by alexkar598** [comment]
It's a bug on para known for months now,unfortunately it's a BYOND issue of some vague something so we cannot fix it. Also you should close the issue
