### ISSUE TITLE
Putting a string on a coin doesn't update its icon

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#9106]
**Problem Description**:
Title

**What did you expect to happen**: 
Visible string

**What happened instead**:
Icon didn't change

**Why is this bad/What are the consequences:**
It used to be that way

**Steps to reproduce the problem**:
1. Attach string to coin
2. See no string

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
NA

**Comment by taukausanake** [comment]
I wish we still used coins to buy things from venders 😞

**Comment by alexkar598** [comment]
Do I hear nostalgia?

**Comment by Citinited** [comment]
To be fair, coins are basically useless after one person gets the insulated gloves from tool storage (unless you're smart, but even then they have little use). I know it's off-topic for this issue but they could do with more uses - maybe some kind of slot machine? :thinking:

**Comment by alexkar598** [comment]
doesn't the slot machines in chapel maint near old bar use coins?

**Comment by Citinited** [comment]
Not unless it was recently changed

**Comment by Vivalas** [comment]
Upon investigation it appears the icon state needed for the string overlay is missing from items.dmi

Figuring who dun it is almost impossible, to my knowledge, as it's a binary file. Probably a shitty conflict resolution or something

If someone gives me the original overlay icon I can fix this

**Comment by Shanewayne9** [comment]
The string isnt in items its in economy

**Comment by Shanewayne9** [comment]
overlays += image('icons/obj/items.dmi',"coin_string_overlay")

it should be economy instead

**Comment by Shanewayne9** [comment]
`overlays += image('icons/obj/items.dmi',"coin_string_overlay")`
Should be economy instead of items

**Comment by Vivalas** [comment]
O.o how did you figure this out? It's been in items for 4 years according to blame

**Comment by Citinited** [comment]
Because when you change a .dmi file it doesn't runtime if you end up having an `icon_state` that doesn't exist any more. A recent PR will have moved the string overlay to a different file

**Comment by Vivalas** [comment]
Hm? I think it just has to do with the fact .dmi is binary so blame doesn't really work at all

**Comment by Citinited** [comment]
Closing as a fix for this has been merged
