### ISSUE TITLE
Large cardboard box returns less cardboard sheets then when created.

### ISSUE THREAD

**Issue by IIWOLFII** [ParadiseSS13/Paradise#9118]
**Problem Description**:
You require 4 cardboard for large box. If you fold said large box flat, you'll get only 1 cardboard sheet in return, though.

**What did you expect to happen**: 
I expected my 3 cardboard pieces not to be sent into redspace.

**What happened instead**:
they **gone**

**Why is this bad/What are the consequences:**
Crafting material literally disappears.

**Steps to reproduce the problem**:
1. Get 4 cardboard pieces.
2. Click on large box (4 cardboard sheets).
3. Use that large box to fold it.
4. Get only 1 cardboard sheet in return.

**Comment by Plotron** [comment]
Cardboard is eco! Cardboard can be recycled! Why u break when folded >:(

**Comment by MINIMAN10000** [comment]
I can tell you why. Because all cardboard breaks down into an item not a stack so quantity was never even considered.
