### ISSUE TITLE
Rubber ducky sprte raise bug.

### ISSUE THREAD

**Issue by IIWOLFII** [ParadiseSS13/Paradise#9119]
**Problem Description**:
When flying in space and constantly hitting yourself with rubber ducky, your sprite moves slightly higher than your actual character's position.

**What did you expect to happen**: 
To squack myself to oblivion.

**What happened instead**:
Literally squacked myself to oblivion.

**Why is this bad/What are the consequences:**
Prolly gamebreaking a little.

**Steps to reproduce the problem**:
0. Use hand teleporter to get into open space. (Probably not the cause)
1. Fly to north/south in space, while constantly hitting yourself with captain's rubber ducky.
2. See your sprite raise up.
3. Panic.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was playing vox that time. If you hit anything, or do flip and fall down, sprite goes back to normal. Pretty much any sprite update, i guess. It also resets the moment you touch floor or plating.
![image](https://user-images.githubusercontent.com/11389033/41465673-c63b29aa-70a7-11e8-997a-e69845f9785b.png)
Red circle is voxxy's actual position.

**Comment by tigercat2000** [comment]
Ugh, this is a result of matrix modifications stacking upon one another. It's really not trivial to fix, especially with how buggy space floating already is.

**Comment by IIWOLFII** [comment]
Fair enough

**Comment by MINIMAN10000** [comment]
"To squack myself to oblivion." "Literally squacked myself to oblivion." Nice working as you expected :P
