### ISSUE TITLE
Voxxy spawns with no first aids kits!

### ISSUE THREAD

**Issue by IIWOLFII** [ParadiseSS13/Paradise#9120]
**Problem Description**:
When you latejoin (probably same when you join from beginning of game.) as vox medical doctor, you have your vox tank in your hand which replaces red first aid kit which medical doctors should get, pretty much deleting the kit.

**What did you expect to happen**: 
To spawn both with first aid kit and specialized n2 tank.

**What happened instead**:
Only specialized n2 tank spawned, and no first aid kit.

**Why is this bad/What are the consequences:**
Deletes first aid kit item on spawn.

**Steps to reproduce the problem**:
1. Be voxxie.
2. Join games, pick medical doctorings as job.
3. Is has voxxygenes in hands, but no first aids kits nowhere to be seens!!
4. **SCREEE**

**Comment by Citinited** [comment]
Issue is similar to #8615.

#8620 tried to fix this but was closed due to being stale

**Comment by davidchan13** [comment]
Can't we just force spawn the small tank into their pocket or the large tank onto their back?

**Comment by IIWOLFII** [comment]
What about check which spawns tank into second hand if first one is occupied?
