### ISSUE TITLE
Add: change ion law from human to crew

### ISSUE THREAD

**Issue by IIWOLFII** [ParadiseSS13/Paradise#9125]
**Problem Description**:
Random ion law which says "only assistants and mime are **human**" should be replaced with "only assistants and mime are **crew**" because of species diversity on this server, asimov AI lawset is not utilized, and in turn, this ion law is useless.

**What did you expect to happen**: 
I expected for ai to lynch all non assistant and mime crew.

**What happened instead**:
No lynch ;c

**Why is this bad/What are the consequences:**
An oversight.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Greytide stationwide.

**Comment by MINIMAN10000** [comment]
Ah it was an issue you were planning to submit gotcha, yeah I have no problem with changing the ion law to be more relevant to current lawsets.
