### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by Luxyleathehat** [ParadiseSS13/Paradise#9133]
**Problem Description**:
When ever i move the window that pops up for any of the consoles in SS13, it bugs out and goes strait to the bottom of my screen and will not move from it. Minimizing the window works however when you put it back to normal, it will return to it's bugges state

**What did you expect to happen**: 
I originally expected the window to simply move where i was wanting to move it like a normal window

**What happened instead**:
Magnetized to the bottom of the screen and refused to leave it.
**Why is this bad/What are the consequences:**
It prevents me from using any consoles until i relog on the server
**Steps to reproduce the problem**:
Step 1. Open any console that has a UI menu that pops up
Step 2. Move the window

**Comment by alexkar598** [comment]
Are you using 2 screens?

**Comment by Luxyleathehat** [comment]
No i am not
