### ISSUE TITLE
Defibing a slime ultra kills them

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#9143]
**Problem Description**:
Defibing a slime person gives them 200% brain damage

**What did you expect to happen**: 
For that not to happen

**What happened instead**:
They take massive amounts of damage, and brain damage, to such an degree that defibbing once or twice permakills without Strange Reagent.

**Why is this bad/What are the consequences:**
You can't defib a slime person then

**Steps to reproduce the problem**:
Defib a dead slime person

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing

**Comment by taukausanake** [comment]
I mean, slimes are technically 100% water. Of course they would get tased the fuck up. I don't see a problem here unless we're talking another way to kill a special specie

**Comment by ppi13** [comment]
Fixing this bug would nerf Malpractice bay, which is required.

**Comment by Plotron** [comment]
That doesn't seem like a coincidence. Are you sure it isn't intentional?

**Comment by Crazylemon64** [comment]
Slime people are extremely vulnerable to brain damage - a defib revival leaves some brain damage from the time without oxygen, and this is amplified to the point for slime people that without extra care, they will not survive.
Make a new issue if you're sure that this isn't the case.
