### ISSUE TITLE
Game frequently crashing, hanging, and disconnecting.

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#9146]
This issue appears to be impacting a decent percentage of the playerbase, and occurs on both beta and stable branch. it appears to affect people playing on windows 10.

**Comment by Plotron** [comment]
I guess it's BYOND.

**Comment by Allfd** [comment]
Hmm...

We are still doing a 512 test.  I don't know if its related or not.

**Comment by IntentEldiablo** [comment]
yeah, can confirm, i play windows 10, have the same issue a lot, crashing, disconnecting, it forcing a reconnect, freezing the works, happened recently ish, last few months, tried reinstalling, cache, the works
