### ISSUE TITLE
AI can be set on fire and burn indefinitely and there's no fire overlay

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#9156]
**Problem Description**:
AI can be set on fire (for instance in an explosion) and burn indefinitely with no visual feedback on the outside. People (and borgs) can be set on fire by it and it also might make pulling by normal crew hard or impossible. Fire does not harm AI, so what's the point?

**What did you expect to happen**: 
Not to be set on fire, the fire to fade out or the fire overlay to display on top of the core.

**What happened instead**:
Got set on fire indefinitely with no visual feedback for others.

**Why is this bad/What are the consequences:**
AI does not get harmed by the fire (so AI becomes a living torch for no good reason), there's no fire overlay, it's generally confusing.

**Steps to reproduce the problem**:
1. Get set on fire as AI.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:  Caused by an explosion.

**Comment by KasparoVy** [comment]
And it burns, burns, burns...
