### ISSUE TITLE
No "White Noise" in AI camera view.

### ISSUE THREAD

**Issue by zubora** [ParadiseSS13/Paradise#9169]
**Problem Description**:
Basically, there's barely to none of those "white noise" thingie that always sits where the camera shouldn't reach. At round start, I could see almost all of space, and almost all of maintenance.
Since, obviously, it was round start, cameras weren't X-rayed with Analyzers and no cameras were in Maint. I could even get to the Mining station and see things I weren't supposed to, like rocks on the asteroid and even monsters. I still ahd the darkness, though, but I could see everything.
Examining is impossible, probably because the game thinks I shouldn't see there, so the "white noise" object is still programmed there, but hovering over, I could see the name of the item/character/object on the bottom of the client. When I shift+clicked them, no description would show up, and in that way, I know where and what I could roleplay ICly and not.
For instance, in the round that this occured, it was Cult. I could see the Cultists base in one of the Mining Stations on the Asteroid. I adminhelped, asking if I could use that to my advantage, like notifying security since, when Examining the characters and tomes and runes, returned me no description. They said no, so I didn't, and just pretended I never saw that.
Examining items where I shouldn't be examining returned an error in the log, an Admin said.

**What did you expect to happen**: 
Obviosuly, I expected to have the "white noise" sprite wherever I couldn't see as an AI, but it either only would show up in random places, or it would show up in random places and then dissapear, allowing me to see everything, but still no examine ability. Sometimes, some places would just stay white noised for the rest of the round, but this only occured in a few places.

**What happened instead**:
I basically had X-ray as AI, like if all my cameras had analyzers in them. Weird enough, I could even see space, and like, even very far from the station, which is impossible in normal gameplay.

**Why is this bad/What are the consequences:**
In my opinion, players could use this to meta or powergame as an AI, being able to see everything and report everything in roleplay. It happened twice to me, and I think it can happen again. Clearly, it's easy to see why this bug would be bad.

**Steps to reproduce the problem**:
I am not sure if other AIs experienced this, but I am using an old laptop (though I doubt hardware is the problem here) and with all the normal settings on. I did turned off the GPU acceleration option before cleaning the cache to resolve lag issues before this started happening, in the BYOND upper-right gear thingie, but it was turned back on, I don't know how, before this issues started happening; so I highly doubt it's something to do with that.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode was Cultists, the second time. First time happened with Traitors. I did report the first time to the admin Rifter but they said they weren't aware of such bug, so I just thought that engineering had upgraded cameras (it was fairly late into the round (around 30 minutes) when I first noticed), but things got suspicious to me when I noticed that I was also able to see a large section of space, where any cameras in the station are able to reach.
Also, no images at the moment because of the crappy laptop I'm using. If that is desired, I'll be mostly happy to provide some.
Ckey is Lorenzz, and I usually play with Argyro Lakkotrypis.
And also, it's late, and I'm kinda tired. I can provide images tomorrow.

Lastly, thank you for your time and sorry for the trouble!

**Comment by Spacemanspark** [comment]
What's your Byond version?

**Comment by zubora** [comment]
I'm running the latest Beta version, as the server is asking for it.

**Comment by tigercat2000** [comment]
This is a bug in 1432, 1433, and 1434. There's nothing we can do about it, basically. The server version doesn't matter, only the client version does. We could blacklist those client versions, but it'd just make it a pain in the ass to install the correct version.
