### ISSUE TITLE
items ejected out of canisters/chem mixers etc are underneath the machine's layer

### ISSUE THREAD

**Issue by ID404-NotFound** [ParadiseSS13/Paradise#9173]
**Problem Description**:
What is the problem?
when I take a plasma or oxygen tank from the rack, or an airtank I fill up in a canister, or even beakers with the chem mixers, they all appear UNDER the machine, rather than being on the top layer

**What did you expect to happen**: 
Why do you think this is a bug?
normally if I eject a beaker from the chem mixer, it's on top ready to be grabbed.

**What happened instead**:
How is what happened different from what you expected?
it was under the mixer, and I had to right click, or use alt-click to get the beaker, etc.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
takes more time to grab what I ejected.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
The only thing I've done differently was change to BYOND 512, but it consistently happens.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Plotron** [comment]
Used to work fine. Shame.

**Comment by Fox-McCloud** [comment]
This is a 512 problem. Not a problem in 511. We're bacck on 511; until we officially update to 512, I'd stick with 511, for now.

**Comment by Crazylemon64** [comment]
Fixed by #9334
