### ISSUE TITLE
Xenomoprh nested prisoners able to attack while nested

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#9174]
**Problem Description**:
Players captured and nested are able to still attack you via disarm, punching, or helping, or even freeing nearby players from other nests

**What did you expect to happen**: 
That nested players should be treated like bucklecuffed prisoners, unable to do anything but resist out of it.

**What happened instead**:
As a queen I was disarm spammed by multiple players nearbly constantly preventing me from fighting back against enemies.

**Why is this bad/What are the consequences:**
It makes managing a xenomorph nest hell at the start when it may just be one player as the queen doing everything.  Nearly impossible for them to walk around without being pushed down constantly.  You cannot just kill the people like terror spiders because you need live hosts.

**Steps to reproduce the problem**:
Capture a person, put them in a nest, watch them disarm spam attack you nonstop when you get close.

**Comment by Plotron** [comment]
Sounds like a very old bug to me.
Back when we had customs...

**Comment by taukausanake** [comment]
Maybe it's because the xeno nests are just subtypes of beds and you aren't restrained in a bed unless you are cuffed. Maybe you need some surgery beds that restrain your patient and by that you can introduce a new var and functionality to beds

**Comment by variableundefined** [comment]
this bug's been here since I started playing. that's 2014

**Comment by Kyep** [comment]
Yeah, this bug is really bad, and should be fixed.
Disarm spam is one thing, but with the latest mining weapons its possible to kill xenos with chain attacks faster than they can kill you - even though you're meant to be secured in a nest.
