### ISSUE TITLE
Changeling slugs give no feedback that they're dead

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#9187]
**Problem Description**:
Dead changeling slugs don't look dead when they're dead.

**What did you expect to happen**: 
All other mobs do that, such as borers, xeno larvae, animals...  I expected either a sprite change or a simple text upon examination telling me that it's dead.

**What happened instead**:
Dead slugs look alive.

**Why is this bad/What are the consequences:**
It's confusing. **"IT'S DEAD!"** people scream. Sure, right, better throw a punch or two! 

**Steps to reproduce the problem**:
1. Look at a healthy brainslug.
2. Make the said brainslug so unhealthy that it dies.
3. They should look identical.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by Fox-McCloud** [comment]
they turn upside down. You have to look closely, but there absolutely is a difference.
