### ISSUE TITLE
Necro-wizard chemical effects

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#9194]
**Problem Description**:
The wizard when using Necro and becoming a skeleton is able to be affected by chemicals like sleep chems, toxins, and other such things.

**What did you expect to happen**: 
Because as a literal skeleton you should not be affected by sleep chems and the like.  You should have no organs and blood to process the chems in order to be put to sleep or get toxin damage.

**What happened instead**:
Wizard was put to sleep by tranquilizer darts, ether syringe guns, and other meme chem mixes.

**Why is this bad/What are the consequences:**
It is pretty much the only possible counter to memechems the wizard may have, yet it does not work allowing them to be hard countered by it.

**Steps to reproduce the problem**:
Be a wizard, become a skeleton via Necro spell, get put to sleep by chems.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Wizard mode, shot by sec tranq darts, medical with ether loaded syringe guns, and science with memechem mixes in rapid syringe guns.

**Comment by datlo** [comment]
I'm not sure this is an issue. Liches already get strong benefits from having no organs, no internal bleeding, immunity to plasma fire/lack of atmos,, and a strong, easy to get healing reagent (milk doot doot), on top of the ressurection mechanic.

This would also prevent a crafty wizard from making his own positive memechems.

If you need a rational explanation as to why a skeleton process chemicals... magic?

I don't think liches need another immunity thrown on top.

**Comment by Citinited** [comment]
If you want immunity to syringe guns, buy the hardsuit

**Comment by Fox-McCloud** [comment]
And Instant summons so you can recall it to your new lich body when you inevitably die.
