### ISSUE TITLE
Surgery Infection

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#9209]
**Problem Description**:
What is the problem?

Massive amount of surgery infections that shouldn't even be occurring. Especially based on this from Tigercat;

> Not sure it's worth doing this way, given how absolutely ridiculous the surgery infection is (and the fact that it's not been enabled for a long time due to bugs), it's pretty likely it's gonna get ripped back out.

**What did you expect to happen**: 
It was working fine until the cybernetics updates. Now it does not.

**What happened instead**:
One example is recent as in yesterday. Squishy gave me a water pill implant with entirely clean gloves and no blood on the table. Turns out later on that I had a bunch of infections in my head and core from it.

**Why is this bad/What are the consequences:**
In some cases it's caused instant death, at worse a whole lot of infections that shouldn't be. Infections are obviously lethal and obviously shouldn't occur in every surgery.

**Steps to reproduce the problem**:
1. Be surgeon/anyone doing surgery.
2. Slap patient onto board.
3. Be entirely sanitary with clean gloves.
4. Surgery.
5. Watch as patient dies from sceptic infections suddenly.
5a. Watch as patient gets a hundred different infections and you have no idea why.
6. Realize you have to stand under a shower and wear a sterile mask to successfully surgery.
7. Realize that doesn't always work.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Plotron** [comment]
#9202?

**Comment by Mitchs98** [comment]
It's ah...not really vague? Clean gloves entails clean hands. Entirely sanitary I.E Clean Gloves/Hands, Clean Table/OR, and washed/blood free tools. It doesn't happen 100% of the time but it DOES happen. Squishy gave me a water pill implant with clean hands and later on my head and core were infected and I was incurring brain damage.

Again,not 100% of the time.

Another instance was very recently where I was operating on someones' chest to fix broken bones. Next thing I know they have heart and lung damage with mild+ infections. Didn't even touch the organs, chest itself was 100% fine.
