### ISSUE TITLE
Circuit imprinter does not require acid

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#9210]
**Problem Description**:
Circuit imprinter doesnt require acid to print things
![image](https://user-images.githubusercontent.com/25063394/42727290-bef4e27a-879b-11e8-930a-9ba8f9bde31f.png)
*Expected an acid requirement, but no. Acid count also does not decrease*

**What did you expect to happen**: 
I expected it to use and require acid

**What happened instead**:
It did not require acid

**Why is this bad/What are the consequences:**
Glass is the only requirement to print things

**Steps to reproduce the problem**:
Use a circuit imprinter, print a board.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Nothing else relevant

**Comment by Fox-McCloud** [comment]
Not a bug, this was an intentional change a while ago.

**Comment by Plotron** [comment]
I recall that there was a discussion whether the machine should require acid or not (there isn't really any good reason for it). My guess is that the requirement itself was removed but the UI and the acid capacity were left unchanged.
