### ISSUE TITLE
Bandages are gone and Ointments don't heal.

### ISSUE THREAD

**Issue by notafed** [ParadiseSS13/Paradise#9214]
**Problem Description**:
Ointments don't seem to heal anything anymore.

**What happened instead**:
The ointment is applied directly to the injury, but even after 5 minutes between each application, no damage whatsoever was healed (neither brute or burn). Gauze can't be applied either and it seems actual "bandages" don't exist anymore.

**Comment by Taaketa** [comment]
I believe ointment and gauze only stop bleeding now
