### ISSUE TITLE
Make Gauze from Cloth and other Ghetto healing items.

### ISSUE THREAD

**Issue by notafed** [ParadiseSS13/Paradise#9215]
More of a suggestion, but I found it surprising when I tried to stem my bleeding wound with a roll of cloth, but it didn't work! And I couldn't find a recipe to craft the gauze either, which would be intuitive imo.

This made me think of other ways of crafting ghetto healing items that should be simple enough to make in the field. Maybe a knife or sharp object can be used on clothing to give cloth (like butchering), and gauze can be made straight from raw cloth or require ointment (since it's otherwise broken and useless atm) or the cloth itself can be used as an inferior substitute. 

And splints could easily be made with a rod and gauze, and it wouldn't be op since they frequently fall off and don't actually heal the break itself until you make it back to medbay.

And maybe there can be a way to assemble and disassemble rolling beds, just like you can assemble wheelchairs from scratch, but this'll give you a better way to transport and do emergency/ghetto surgery out in the field if necessary (gateway missions, woo!). Think of the possibilities!

**Comment by FalseIncarnate** [comment]
Suggestions should be posted to the forums, not as issue reports.

That said, we've had a few minor discussions internally about healing items, being able to make gauze (bandages) would definitely make sense if we pursue some of our thoughts.
