### ISSUE TITLE
Round start timer should be increased.

### ISSUE THREAD

**Issue by Emanthealmighty** [ParadiseSS13/Paradise#9224]
**Problem Description**:
There is not enough time to get in game after the previous game ends.

**What did you expect to happen**: 
There to be more time, at least 60 seconds more.

**What happened instead**:
Byond keeps failing to connect, sometimes multiple times in a row, before letting people in. This results in many people joining when the round already begun.

**Why is this bad/What are the consequences:**
The consequence is that this decimates the chances of many people to be an antagonist, since the most interesting ones only occur if you "declare ready" before the round begins.
This is a huge problem for me, and it's gradually turning me down from playing this game.
What is described below ALWAYS happens to me. It's not just me, either, because I can see many other people also joining right as the round has started.

**Steps to reproduce the problem**:
Play the game.
Round ends and the connection fails.
Close the game window and try to reconnect to the server.
Connection fails 5 times in a row.
Finally connect
Round has already started.

There is no bad side to increasing the timer before the game starts.

**Comment by datlo** [comment]
Have you tried leaving the byond window alone for a bit when it says failed to connect? I've seen it sometimes and it manages to connect for me after some time.

Concerning the PR, I don't have the stats but if this is an issue for a lot of people, sure, why not.

**Comment by Emanthealmighty** [comment]
It only works some times. If it doesn't work, say goodbye to your chances of being an antagonist. Trying to relog will be useless, and it will only work when the round has started.

100% of the times where I don't get roundstart despite having played the entirety of the previous round, I systematically manage to join when it says "welcome to the station, enjoy your stay". This is insulting, to say the least.

**Comment by FalseIncarnate** [comment]
Technically this is a change request disguised as an issue report... But if people are having trouble reconnecting before the round starts that should be looked into.

On average, how long would you say it takes you to fully reconnect and be able to ready up (or, in the case of latejoins, press the join button to select a role)?

**Comment by Emanthealmighty** [comment]
It takes no time to join mid-round, it will always work correctly both for the connecting and joining part.

If the round is restarting, however, it goes two ways.
1) client reconnects automatically and there are no problems
2) client loses connection and is forced to relog
3) relog doesn't work
4) client is able to join only when the round has already started.

**Comment by FalseIncarnate** [comment]
So what you are saying is you sometimes can connect while the server is still in pre-game lobby (ready up), but sometimes you can't connect at all until after the round has actually started (latejoin). By that response, it seems that extending the lobby time won't actually benefit you since it would either not affect reconnecting in Case A, or make you wait even longer in Case B?

**Comment by Emanthealmighty** [comment]
I don't think it's actually connected to when the round starts, but rather, the time it takes for byond to fix itself and work kind of coincides with how long it takes for the round to start.

**Comment by Plotron** [comment]
I also have that problem, but for me the 'workaround' to just wait three more seconds after receiving the "connection failed" message works. Total wait time becomes 33-35 seconds.

I agree that we should give people more time - at least 30+ seconds.

**Comment by Emanthealmighty** [comment]
Right, problem resolved. Timer's been increased.
