### ISSUE TITLE
Research Director Sec HUD Stray Pixel

### ISSUE THREAD

**Issue by Agameofscones** [ParadiseSS13/Paradise#9228]
The Research Director's Sec HUD Icon has a stray pixel on it that's just, floatin' there, hangin' out, bein' all chill.

https://i.imgur.com/XxiK23q.png

You can see it right there in the .dmi

Super easy fix, but minor enough to not warrant a full recompile, I'd (personally) fix it then stuff it in with the next big update.

**Comment by Plotron** [comment]
Nice find.
