### ISSUE TITLE
wheelchair players cant unhandcuff or remove stuff from others

### ISSUE THREAD

**Issue by chesse20** [ParadiseSS13/Paradise#9230]
**Problem Description**:
You can't unhandcuff or remove stuff while in a wheel chair

**What did you expect to happen**: 
you should be able to unhandcuff and remove peoples stuff in a wheel chair it makes playing security with no legs harder than it already is
**Why is this bad/What are the consequences:**
security officers in wheelchairs can't do their job 
**Steps to reproduce the problem**:
set your preferences to have no legs

**Comment by chesse20** [comment]
@optimumtact can you fix this

**Comment by Plotron** [comment]
Isn't it similar to the way secway works? I do remember some glaring limitations of using such vehicles.

**Comment by Citinited** [comment]
Not sure if it's the exact same thing, but as a cyborg I couldn't use an extinguisher while buckled into either a wheelchair or an office chair
