### ISSUE TITLE
Shadowlings darkvision and insulation seems to be broken

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#9236]
I was playing shadowling just now and the Darkvision didn't let me see people through walls and I got shocked by a door.  If I recall correctly shadowlings shouldn't be able to be shocked like that and they should have night vision + thermal vision.

**Comment by FlattestGuitar** [comment]
- darkvision is just vision in the dark, not thermals
- I can't reproduce the other one, doors don't shock unless you find a way to remove the chitin gloves
![2018-08-28_11-12-50](https://user-images.githubusercontent.com/15747030/44713445-6975dd00-aab3-11e8-9860-c4ebf69c9190.gif)

**Comment by Fox-McCloud** [comment]
This *was* a bug, but it's since been fixed.
