### ISSUE TITLE
Wrong body experience while under in surgery

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9237]
**Problem Description**:
When I was under in surgery I saw the hands of the doc who was threating me. I could also see the bag he used.

**What did you expect to happen**: 
I saw the item the doc was using.

**What happened instead**:
I was supposed to see my own empty hands

**Why is this bad/What are the consequences:**
It's a minor thing since you can't do anything with it.

**Steps to reproduce the problem**:
I opened the bag, while it was on the table (drag on my sprite), then laid myself on the surgery table and was given the tank by the doc. Afterwards I noticed it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Picture of it:
![image](https://user-images.githubusercontent.com/15887760/43044566-5f8c88d4-8da8-11e8-810a-bcef2fa263b5.png)

**Comment by alexkar598** [comment]
Its a problem with item containers and opening said container at the same time as another person,here caused by you probably click dragging the surgery bag to your sprite and the doctor doing the same.
