### ISSUE TITLE
legless security is too weak

### ISSUE THREAD

**Issue by chesse20** [ParadiseSS13/Paradise#9243]
**Problem Description**:
one of the game admins complained when i played security with no legs
**What did you expect to happen**: 
i could play with no legs without admins boinking me
**What happened instead**:
BOINK
**Why is this bad/What are the consequences:**
i want to play security but my charater is a diona with no legs
**Steps to reproduce the problem**:
be security with no legs when dragonslayer932 is online
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Can you please add buffs for when you spawn roundstart with no legs so that i dont get admin boinked when i play legless dioana security officer

if your character has no legs upon roundstart/spawning you should be able to crawl and or shoot while laying on the ground

**Comment by chesse20** [comment]
@optimumtact can you help me code a fix for this

**Comment by Plotron** [comment]
We can be strict about it and ban it in code just like short-sighted (or with any other disability) characters cannot play as Captain/HoS.

**Comment by taukausanake** [comment]
I'd be okay with a disabled security member no problem, but a _Diona_ with no legs? That's kind of weird for a collective like that

**Comment by Fox-McCloud** [comment]
Consider this your last and final warnign for wasting everyone's time on the Github.
