### ISSUE TITLE
Parked space pods get moved when white ship moves

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#9245]
**Problem Description**:
Moving the white ship makes spacepods get moved into walls.

**What did you expect to happen**: 
The spacepods to remain where they are.

**What happened instead**:
they got stuck in walls

**Why is this bad/What are the consequences:**
You can still move out of the wall, but it is still bad.

**Steps to reproduce the problem**:
Park pod in podbay of white ship, move ship using the console.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
See after picture below
![untitled](https://user-images.githubusercontent.com/32099540/43109020-edd91390-8ee4-11e8-92cb-4f09b59c4af4.png)

**Comment by Citinited** [comment]
I wonder if the white ship should act like other shuttles, in that it gibs / pushes anything in its way when it lands.

Either that or we hire interstellar traffic wardens :^)

**Comment by taukausanake** [comment]
@Citinited maybe it should just hit people very _very_ hard and boost them through space

**Comment by Taaketa** [comment]
Pretty sure this is just shitty podcode.

**Comment by Twinmold93** [comment]
Looking at the imagine, I imagine when you parked the pods they were facing to the right, which would have been outside the walls. When the ship moved, since it 'updates' only the main tile of the pod (which is always the front left), it reset orientation. I'll have to take a look at it in the near future.
