### ISSUE TITLE
Unathi with short snouts Rug robot parts

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#9253]
Unathi with short snouts bug out robotic parts icon generation for the head.

This is for a pretty simple reason; the head `icon_name` gets changed from `head` to `head_sharp`; the robotic parts only operate on the assumption that the `icon_name` is `head`. 

@KasparoVy 

Any ideas for how to fix?

**Comment by KasparoVy** [comment]
Sorry- will take an in-depth look at this when I get home tonoght @Fox-McCloud and will try to write a fix. Thanks for letting me know

**Comment by Fox-McCloud** [comment]
Thanks!
