### ISSUE TITLE
Voice Analyzer is spelled as Voice Analyser in Autolathe

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#9279]
Makes searching harder. It still produces Voice Analyzer, not Analyser.

**Comment by Birdtalon** [comment]
While I would argue that Analyser is the correct spelling. Consistency is more important and it is spelt analyzer most other places. Here's some other instances of it being spelt Analyser, compared with the 71 matches of "Analyzer"

https://github.com/ParadiseSS13/Paradise/blob/05a2208e2bb35ccb75bb2dfb34bf92b6a36f6f12/code/modules/research/designs/autolathe_designs.dm#L546

https://github.com/ParadiseSS13/Paradise/blob/604f26f2ecec8b8a2e5d878b9e2e27ade2e17618/code/modules/awaymissions/mission_code/UO71-terrorspiders.dm#L184

https://github.com/ParadiseSS13/Paradise/blob/e72efe68fef63295f775153a68f42dcc902fc145/code/datums/uplink_item.dm#L217
