### ISSUE TITLE
Borers can no longer be labeled (aka: given names)

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#9296]
**Problem Description**:
Hand labeler no longer works on cortical borers. "XXX gently taps cortical borer with the hand labeler".

**What did you expect to happen**: 
The hand labeler to work on a cortical borer, giving it a name in parentheses.

**What happened instead**:
"XXX gently taps cortical borer with the hand labeler". No label was applied.

**Why is this bad/What are the consequences:**
Cortical borers are often used as personal pets in late game. Labels (names) were previously used to differentiate between different pets so the owners could keep track of them. This also bolstered medium RP, as labeled borers were more likely to be docile and/or friendly.

**Steps to reproduce the problem**:
1. Use a hand labeler.
2. Turn it on and input a string.
3. Tap the cortical borer with the active hand labeler.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:  Must've been a side-effect of one of the refactors. It used to work and I'm sure it's going to be classified as semi-intended, but I'm posting this here just for the sake of documentation.

I bet the labeling-thing was actually not intended in the first place. A bug-feature, I'd say.

**Comment by variableundefined** [comment]
It seems to be intended that mob cannot be labelled at all.

**Comment by taukausanake** [comment]
Let's instead give them pet collars

**Comment by KasparoVy** [comment]
"general earrape"

**Comment by Crazylemon64** [comment]
If you want to re-add this behavior, you could try rigging something up with pet collars or similar.
