### ISSUE TITLE
problem in virus database

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#9304]
![image](https://user-images.githubusercontent.com/25136265/43600630-24375df4-9659-11e8-88eb-7197e8ee80a7.png)

**Comment by Plotron** [comment]
So basically the displayed name is wrong. But you didn't tell us whether it's consistent for every other virus in database.

**Comment by alexkar598** [comment]
Only happens on this virus but the other virus could benefit from a standardization of the names as they are highly inconsistent.
