### ISSUE TITLE
Forensic scanner

### ISSUE THREAD

**Issue by M3hillus** [ParadiseSS13/Paradise#931]
Multiple object types don't leave prints or fibers when used. Like ATM machines.

**Comment by SirBloodBuske** [comment]
src.add_fingerprint(user) 

:D

**Comment by CrAzYPiLoT-SS13** [comment]
No need to tell us that you know it.

**Comment by TheDZD** [comment]
Yeah, that's the main problem with the forensic scanner, EVERYTHING needs snowflake code to account for it.
