### ISSUE TITLE
 Syndicate Radio Encryption Key causes duplicate radio messages (major nuisance for AI)

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#9310]
**Problem Description**:
The Syndicate Encryption Key intercepts messages on channels you already have access to. Specifically terrible for AIs, as they basically get all messages duplicated.

**What did you expect to happen**: 
To be able to either turn off intercepted messages easily, or get the 

> (Intercepted)

 messages only for channels that I don't have access to normally.

**What happened instead**:
Intercepted messages caused duplicates as the normal radio and the intercepted radio worked simultaneously for relevant channels.

**Why is this bad/What are the consequences:**
Chat spam.

**Steps to reproduce the problem**:
1. Be traitor AI.
2. Talk on radio.
3. See duplicate radio messages.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I've got a feeling that I did in fact manage to turn off that nuisance as traitor AI once, but I have no idea how to reproduce it, as shutting down channels via radio management simply causes all relevant radio to not be heard.

**Comment by Fox-McCloud** [comment]
All intercepted messages work like this. This isn't unique to traitor AI.
