### ISSUE TITLE
Cannot put a pet collar on farwa's neck

### ISSUE THREAD

**Issue by uzername** [ParadiseSS13/Paradise#9311]
**You cannot put a collar to a farwa neck**:
It is impossible to make farwa as a pet. Game says that it is impossible to do so.

**The collar instead should land on farwa's neck making it a pet**
I want a special pet, not just dragging farwa around

**Steps to reproduce the problem**:
Bring farwa to pet shop, purchase a collar, drag farwa icon over your icon with having a collar in hand. It is possible to put a collar only in farwa's hand.

**Comment by Plotron** [comment]
Farwas aren't exactly simple mobs. They're a primitive version of a fully-grown playable humanoid, so I am not surprised.

**Comment by taukausanake** [comment]
Yeah, put the collar on a suit and then a farwa/letter human mob and then you'll see it. Or we could get neck inventories and wear them whenever...

**Comment by Fox-McCloud** [comment]
Not a bug; they're a human mob, not a simple animal.
