### ISSUE TITLE
Chain door shocking

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9313]
**Problem Description**:
When pulsing the shocking wire I got shocked around ~50 times. I got dragged away from the door after 3-5 times but I kept getting shocked even when I was a department away. Needless to say my character died from this, unable to be defibbed due to the damage.

**What did you expect to happen**: 
You're supposed to be shocked once.

**What happened instead**:
I got shocked way more. Even when I was pulled away from the door.

**Why is this bad/What are the consequences:**
It kill characters if you're not wearing insulated gloves.

**Steps to reproduce the problem**:
I was testing the wires on the maint door below the janitor. Just south east. I pulsed it once and nothing more.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I've found a related issue using remote signallers: [https://github.com/ParadiseSS13/Paradise/issues/8147](url)
Although the door was not tampered with.

**Comment by alex-gh** [comment]
Tried it, could not reproduce.

**Comment by Birdtalon** [comment]
Couldn't reproduce. Needs more info.

**Comment by Birdtalon** [comment]
@KasparoVy do you mean #8247

**Comment by Fox-McCloud** [comment]
Yeah, this is a repeat of 8147.

**Comment by KasparoVy** [comment]
Yeah @Birdtalon my bad haha, thanks for the correction
