### ISSUE TITLE
Stealing a crewmember's brain objective does not complete if the crew member was pre-scanned.

### ISSUE THREAD

**Issue by DrewTuber** [ParadiseSS13/Paradise#9315]
So this is more of a semantics issue with the objective, but it only states that I have to steal the brain of my target. It does not say to make sure the target then does not get cloned at a later time. So, despite having the target's brain in my pocket, the objective red-texts at round end.

![image](https://user-images.githubusercontent.com/9029918/43678731-23efad4e-9819-11e8-85fa-a3a7a73ac52c.png)

**Comment by Birdtalon** [comment]
https://github.com/ParadiseSS13/Paradise/blob/ddec761f1511c8aba711b1039a01c3434fc6a9e6/code/game/gamemodes/objective.dm#L137-L142

Relevant code for information. It checks for the brainmob not the actual brain item.

**Comment by Fox-McCloud** [comment]
Needs to be the brain that has the "soul".

This is intentional and not a bug.
