### ISSUE TITLE
Dark sight eyes not glowing in the dark

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#9318]
**Problem Description**:
Drask white eyes don't glow in the dark. This may apply to other bright colors.

**What did you expect to happen**: 
White colored eyes to 'glow' as white dots.

**What happened instead**:
There was no glow on drask eyes. Instead, it was a dark spot where I should have the three glowing orbs.

**Why is this bad/What are the consequences:**
It's an issue for various other dark sight races, as each of them is supposed to have glowing eyes in the dark, from what I know.

**Steps to reproduce the problem**:
Set your drask's eyes to white, or a very light color, and it will not show up in the dark. This may apply to other races as well.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: If it happens to drask, it may be affecting other dark sight races.

**Comment by KasparoVy** [comment]
It only shows up for darksight over 7, of which Drask have 5. Their eyes do not meet the 'shine' threshold.

**Comment by KasparoVy** [comment]
Please refer to this PR https://github.com/ParadiseSS13/Paradise/pull/8489 for clarification.

**Comment by KasparoVy** [comment]
All good man! Perhaps those Drask had assisted/cybernetic eyes.

**Comment by Breenland** [comment]
Are we entirely sure that drask eyes never glowed in the first place? Would it be possible to have it adjusted, based on the physiological lore of the race?

**Comment by KasparoVy** [comment]
Yes as there have not been any changes to the eye shine threshold. No idea who you'd talk to to pass that adjustment as it'd require the entire eye shine threshold to be dropped by 1, where the original intention was to restrict it to only TOP-LEVEL darksight-bearing eyes and cybernetics and 5 is decidedly middling.

**Comment by Fox-McCloud** [comment]
Thank you @KasparoVy
