### ISSUE TITLE
AI, Cyborg, Drone: Unable to use windows for Computers, Airlocks, etc.

### ISSUE THREAD

**Issue by CodingCarl** [ParadiseSS13/Paradise#9320]
**Problem Description**:
As a AI, Cyborg, or Drone I will occasionally have all other windows that pop-up, be they from computers, airlocks, air alarms, or whatever; show up as blank. Completely white. Sometimes it will be fixed if I restart the game or the byond client. But often doesn't fix the problem.

The frequency of it happening is also skewed. It will happen:
90% of the time as AI
50% of the time as Cyborg
20% of the time as Drone

**What did you expect to happen**: 
I expected to be able to use computers and other interfaces. Being able to control computers, airlocks, air alarms, APCs and etc. Is a major part of the job for these jobs. An AI who can't use the crew locator computer to find someone is fairly bad.

**What happened instead**:
It didn't work. Just white screens instead.

**Why is this bad/What are the consequences:**
I would be unable to use a vital part of the game and do a lot of my job.

**Steps to reproduce the problem**:
If I try to use one of the computers that seems like it requires a lot of resources then it happens more frequently. Such as the medical crew locator computer. Also just being an AI and interacting with a lot of computers does it too.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Mostly I was just being very busy as an AI.

**Comment by Plotron** [comment]
I get NanoUI Manager not available (or something like that) errors popping up when Nano UI doesn't want to load, mostly at round-start. It either fixes itself after a few minutes or I have reconnect. Not a deal-breaking bug in my case.

**Comment by Crazylemon64** [comment]
@tigercat2000

**Comment by Kyep** [comment]
https://github.com/ParadiseSS13/Paradise/issues/13728
