### ISSUE TITLE
Can't examine IPC's after dead

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9323]
**Problem Description**:
After an IPC dies you can't examine it anymore. Even though it's alive again

**What did you expect to happen**: 
That you could examine him

**What happened instead**:
You should be able to examine the person

**Why is this bad/What are the consequences:**
People become hard to identify this way. And you can't see what they are wearing.

**Steps to reproduce the problem**:
Kill an IPC. I've seen this happen with EMP deaths and deaths that contain dismemberment. Not sure if required. Shift click on the person or examine him using the right click menu. Won't show info.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I've seen this happen with an EMP dead and a holo parasite murdering the IPC. Not sure if the dismemberment matters.

**Comment by Crazylemon64** [comment]
I'm having difficulty reproducing this. Could you post more detailed steps?

**Comment by farie82** [comment]
Sorry for the late post. I've seen this happen when an IPC died after anything really. And after they die they become un examinable. It's mostly random but can break the game quite a bit. Their names are visible and you can interact with said IPC no problem. Brenden also found this bug: https://github.com/ParadiseSS13/Paradise/issues/9387
I've myself not seen it as of late so I can't confirm myself if it's still here.

**Comment by Crazylemon64** [comment]
Repost if you can get this to reproduce reliably.
