### ISSUE TITLE
New Space Sector Derelicts

### ISSUE THREAD

**Issue by FerenGraves** [ParadiseSS13/Paradise#9332]
**Problem Description**:
One of the new additions to the space sectors, a derelict shuttle with broken mechs and yellow floor tiles has a "shuttle console" that is directly linked to the station's mining shuttle console, able to send and recall the shuttle. There are also floor tiles missing under blast doors for its shuttle docking area.

**Why is this bad/What are the consequences:**
Assuming it was used as a general "shuttle console" but had the same ID as the console in the mining office, meaning it simply feels unintentional. Missing floor tiles seem like a general oversight as well but have no gameplay impact.

**Comment by Crazylemon64** [comment]
This sounds like you've found one of the space ruins - seems like one of them has a mapping issue.

**Comment by Agameofscones** [comment]
In regards to this the Syndicate listening outpost with the PDA messaging monitor has no system of generating power, nor a Tele-Comms BUS allowing the suspicious intercoms from working. The space ruins do actually have a lot of issues at the moment. I might go through and fix a few.
