### ISSUE TITLE
Unmovable alien artefacts.

### ISSUE THREAD

**Issue by SentRoses** [ParadiseSS13/Paradise#934]
So, last round, I dig up two different alien artefacts and brought them on the research outpost. After analysing them, I bring one to the Exotic Particle Harvester and put it on the Anomaly Scanner Pad. I charge a cell with it, leave, then come back later to test the charged cell. When this cell got depleted, I put another in the Harvester, but the machine tells me "Cannot harvest. Source already being harvested.", even though nothing is happening. I try pulling the artefact out of the Pad, but nothing works, it just stays there, it can't be pushed/pulled, and the Pad cannot be deconstructed or otherwise damaged. The effect (a toggleable ontouch energy field around the artefact) still works fine.
I put the second artefact in the other Harvester, charge a cell, test it, and I can move the artefact fine, so I leave it there, on the Pad.
Later on, I come back, and both of the artefacts now suffer the same fate : impossible to move.
I adminhelp it, the Head of Staff answers and teleports one of the artefacts next to the Scanner Pad... but it still won't move at all.

This might be the same issue as in #502, but it only mentions a problem with the Scanner in Anomalous Materials, which worked fine for me.

**Comment by Krausus** [comment]
For the forcefield artifacts, those seem to anchor when activated, and then *don't unanchor* when deactivated. That's probably a bug.

It looks like the artifact analyzer also screws up anchoring. When you begin a scan, it's supposed to anchor the artifact you're scanning, but will instead anchor the *previous* artifact you scanned, and never unanchor it.

I'd imagine there's probably something wrong with the harvester, too, but I don't have time to dig through its code right now.

**Comment by SentRoses** [comment]
Okay, that makes sense then. I did try to analyse a third useless artefact after putting the second one in the Harvester, which would explain why I could move it fine before but not after that.
So yeah, it's actually the Anomaly Analyser (or the artifact analyser as it's called in the code) that anchors things up. I can see where it's supposed to anchor the artefacts in the code, but why the hell it does it to the previous one is beyond me.

**Comment by Krausus** [comment]
> but why the hell it does it to the previous one is beyond me.

Because the code sucks. I already have this fixed in a local branch, and will be putting up a PR including it soon™.
