### ISSUE TITLE
SMES from scratch/spawned is broken.

### ISSUE THREAD

**Issue by ingles98** [ParadiseSS13/Paradise#9345]
**Problem Description**:
Building a SMES from scratch will automatically set it as broken and therefore non-functional. 

**What did you expect to happen**: 
Shouldn't happen i guess. SMES should be fully functional

**What happened instead**:
SMES is broken after putting everything together and screw it.

**Why is this bad/What are the consequences:**
Can't build/spawn aditional SMES.

**Steps to reproduce the problem**:
Constructing it from scratch, after the last screw, it will show up as broken. Setting the power terminal and plugging the cables won't do anything else.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
#9334 is the latest change to machinery but still doesn't seem the changes could affect this. 
Also, deconstructing it to machine frame will show it as "slightly damaged"

I talked to admin Blessedtuna and he even tried to spawn new full SMES that also came already with the broken flag. I will myself try to look into it and PR if success but i'm fairly new to BYOND coding.

**Comment by Crazylemon64** [comment]
#9334 hasn't even been merged yet, so it cannot have any effect.

**Comment by ingles98** [comment]
What does this "disassembled" flag do ?
/obj/machinery/proc/spawn_frame(disassembled)
(code/game/machinery/machinery.dm)
