### ISSUE TITLE
Welding goggles gone in atmospherics.

### ISSUE THREAD

**Issue by DesolateG** [ParadiseSS13/Paradise#9358]
When the new atmos hardsuits were added the 2 welding goggles weren't placed back on the moved table.

As per @Jovaniph 

@Kyep

**Comment by Citinited** [comment]
Atmos never had welding goggles though. Welding helms yes, but not goggles

**Comment by Jovaniph** [comment]
They did because I was the one that added them in a previous PR long ago

https://github.com/ParadiseSS13/Paradise/pull/7151

**Comment by Citinited** [comment]
TIL, I stand corrected
