### ISSUE TITLE
Dismantling regular walls gives hypothetical poster item

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#9376]
**Problem Description**:
When using a welder to dismantle a wall which has a ripped poster on it, the ripped poster will appear upon the resulting girder as item "hypothetical poster - "

**What did you expect to happen**: 
I did not expect the poster to make any kind of appearance whilst dismantling the wall; I expected it to more-or-less vanish.

**What happened instead**:
The appearance of the "hypothetical poster - " item seems to be an unintended consequence, judging by the item's description. Seeing it appear, I thought at first that the poster may have bugged and been restored to its full state before being ripped, but instead, the item mentioned had been created.

**Why is this bad/What are the consequences:**
The item does not seem to be intended to be shown or used in any kind of gameplay that is not a test mode.

**Steps to reproduce the problem**:
Have a regular wall (not sure if it works with rwalls). Have a poster on said wall. Rip the poster off (do not remove it with wirecutters). Dismantle the wall to girder-state using a welder. The item "hypothetical poster - " will be between the metal and the girder. Note that this only works once.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
https://puu.sh/BfKLh/b1d43697e3.gif Gif of the event in action.
https://puu.sh/BfLSu/f923fdebda.png Screen of the item description.

**Comment by taukausanake** [comment]
That's actually kind of funny

**Comment by Birdtalon** [comment]
This seems to only occur in escape.
