### ISSUE TITLE
Admin prison does drop bodyparts

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#9378]
**Problem Description**:
Admin prisoning someone does create external bodyparts that are the ones the prisoner is currently using in the locker.

**What did you expect to happen**: 
No body parts inside the locker.

**What happened instead**:
All external bodyparts are inside the locker, staying together and looking like a naked clone of the prisoner.

**Why is this bad/What are the consequences:**
The body parts inside the locker do have the NODROP flag enabled, and are the same ones the prisoner has. After picking them up, can't remove them easily, a deleting does also cause the prisoner to loose the limb.

**Steps to reproduce the problem**:
Take a human mob, open the player panel for them, hit "Prison", open the locker that got created.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Found it while testing my changes from href to UID, locate was still used, so effectivly there should have been no changes to it, as the addition from UID gets ignored.

**Comment by DesolateG** [comment]
rather creepy isn't it?
