### ISSUE TITLE
Changeling Transform ability removes attached hardsuit parts

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#9381]
**Problem Description**:
When transforming from a Drask to another race (in this case, human) with the hardsuit equipped having helmet and magboots deployed, the magboots and helmet disappear entirely. Attempting to remove the items shows they are not there at all. I did not see them on the ground, and I have not replicated this just yet to verify if it's transforming race or transforming in general.

**What did you expect to happen**: 
To transform, and still have my hardsuit helmet and magboots.

**What happened instead**:
The helmet and magboots were not there.

**Why is this bad/What are the consequences:**
If you happen to transform in space, or later have difficulty acquiring replacement parts, it could prove bad for your cover, or dangerous.

**Steps to reproduce the problem**:
1. Be a drask (unsure if other races)
2. Be a changeling (good luck!)
3. Acquire hardsuit, and attach helmet+magboots.
4. Transform
5. The hardsuit helmet and magboots should be gone.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Changeling, I was transforming. I was in a dark tunnel, so the items could have been left behind there, but a search did not reveal them.

**Comment by Birdtalon** [comment]
Tested this.

The helmet and boots appear to be deleted, however the hardsuit registers that they are still present via `attached_boots = 1` and `attached_helmet = 1`. The icons in the inventory do not display them. You are still be able to toggle the helmet visually using the verb however the hardsuit's `contents` are empty

**Comment by Breenland** [comment]
After I took off the hardsuit, I wasn't able to toggle the helmet again and had to attach a new one, as well as a new pair of boots.
