### ISSUE TITLE
IPC null description makes Examine return nothing

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#9387]
**Problem Description**:
When attempting to examine an IPC with no description, the game returns nothing in the chat. Nothing on their name, what they're wearing, what they're carrying, or anything.

**What did you expect to happen**: 
When shift+clicking or context menu Examining the character, I would get a list of what they're wearing and such, as well as a description if they have one.

**What happened instead**:
Nothing appeared in the chat log. 

**Why is this bad/What are the consequences:**
It makes it impossible to tell what someone is carrying if they do this, making it difficult to prepare for something possible bad. Additionally, this makes it impossible to tell if someone like this is affected by certain objects, such as 'covered in something flammable,' they have been thralled by a shadowling, or even tell how damaged they are without a medHUD or cyborg scanner.

**Steps to reproduce the problem**:
1. Set IPC description to nothing (null?)
2. Attempt to Examine the character.
3. Nothing appears in the chat log.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I'm not entirely sure this is the cause, as I did ahelp with Kyet at the time. I was a ghost, and was also able to examine other IPCs and characters just fine.

**Comment by FlattestGuitar** [comment]
Can't reproduce this the way you're describing. The description doesn't have anything to do with examining humans, so that's not the cause here.
