### ISSUE TITLE
Cannot secure diamond statue to escape shuttle floor

### ISSUE THREAD

**Issue by uzername** [ParadiseSS13/Paradise#9405]
**Problem Description**:
Unable to secure the diamond statue with wrench to escape shuttle floor. It says "floor must be present"

**What did you expect to happen**: 
The statue should be fixed on place

**What happened instead**:
The statue was able to be moved after applying wrench to it.

**Why is this bad/What are the consequences:**
It should not be moved by Command trying to pull it to their cabin.

**Steps to reproduce the problem**:
Build diamond statue. Pull it to escape shuttle. Try to secure it to floor using wrench. A message is given that floor should be present

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by variableundefined** [comment]
Working as intended. As far as I know, on Centcomm and certain shuttle tile construction is not allowed because of how weird it would be.

**Comment by taukausanake** [comment]
Yeah but that "floor must be present" message might need to be changed. Be a lot nicer if it said "You cannot secure thing to this floor"
