### ISSUE TITLE
People Losing Their HEads: Can't Revive

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#941]
People who lose their heads can't be revived in any way---this is showing up again.

@ZomgPonies

**Comment by TheDZD** [comment]
Does the brain get destroyed or can they just not be rejuvenated?

**Comment by Robertha89** [comment]
head gets destroyed, brain does not drop.

**Comment by Fox-McCloud** [comment]
Yeah, I think that's the issue here after seeing a few more things.

**Comment by TheDZD** [comment]
That's an issue that popped up after I fixed one of the droplimb runtimes (runtime prevented the external organ from deleting), although I could never seem to pinpoint the source of it. From what I could tell, the code is there and organs should be tossed out of a limb when it's destroyed in that manner.
