### ISSUE TITLE
Something is causing crashes near the captain's office/teleporter/bar.

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#9422]
**Problem Description**:
What is the problem?
Title. Plenty of people are going SSD in that general area.

**What did you expect to happen**: 
Why do you think this is a bug?
People shouldn't repeatedly crash in one area
**What happened instead**:
How is what happened different from what you expected?
They did
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
I want to play the game
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I believe this only affects people on byond 512 as I didn't crash before upgrading. So.

1. be on byond 512
2. be near captain's office/teleporter/bar
3. ???
4. crash

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Shadeykins** [comment]
This is more than likely caused by the well-known bug w/ picture inserts onto a piece of paper (IE: a printed picture from a security record).

**Comment by datlo** [comment]
So how would you go ahead and prevent that from happening?

**Comment by Crazylemon64** [comment]
This is a common issue with a lot of objects that create their icons dynamically. We do not know how to fix this.
