### ISSUE TITLE
Antags becoming IRC keep their objectives and powers

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9423]
**Problem Description**:
If an antag is borged via becoming an IRC they keep their objectives and powers

**What did you expect to happen**: 
Them becoming an IRC without said powers or objectives. Like a borg would

**What happened instead**:
They become an IRC with the mindslave objective added. And they keep their origional objectives and powers.

**Why is this bad/What are the consequences:**
A vampire keeps their powers if they become an IRC. And they can still greentext as one due to them just changing bodies.

**Steps to reproduce the problem**:
Get the brain of an antag and put it in an IRC.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I've not yet seen it with clings but it might be possible to have cling IRC's. With vampires and agents it does work. Slings not yet tested.

**Comment by Crazylemon64** [comment]
@farie82 Putting an MMI in an IRC doesn't "slave" them - it's the "robotic brain" itself that enforces the laws, and non-robotic brains do not have this effect.

**Comment by taukausanake** [comment]
Isn't an IRC the bastard child between borgs and IPCs? Should they still have their powers in that case? Half the issue was they keep objectives which is intended but is a robo vampire intended too? If a changeling keeps its powers does that mean it can change from IRC into something else?
