### ISSUE TITLE
Hidden walls/doors bug

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#9440]
**Problem Description**:
You can tell apart hidden walls/doors on walls from a glance on regular and reinforced walls by shift + click examine or right click examine as hidden walls/doors do not have the "It looks fully intact" text.
https://imgur.com/ATtAKlb
regular wall with no hidden door
https://imgur.com/ef3Sppq
regular wall with hidden door 
**What did you expect to happen**: 
Hidden door walls should also display their integrity status to not easily give away their hidden nature.
**What happened instead**:
You are able to examine easily for hidden doors from a glance and not from actual interaction or with mesons.

**Why is this bad/What are the consequences:**
Makes spotting antag's hidden rooms easier for security/hunters minimizing their available actions

**Steps to reproduce the problem**:
Make a hidden door in a regular wall or reinforced wall.  Examine it in comparison to normal walls.

**Comment by taukausanake** [comment]
Working as intended? They're meant to  be hidden, not foolproof

**Comment by Crazylemon64** [comment]
This seems to be more in the domain of balance - take it to the forums.
