### ISSUE TITLE
Mapwriter Troubles

### ISSUE THREAD

**Issue by GuiltyBeans** [ParadiseSS13/Paradise#9444]
**Problem Description**:
After saving a map, one created from build-mode or other means, when trying to upload and place said map after saving it, the map will break and fail to load. This causes the species controller to break and makes any player that spawns in after the break do so as a brain dead (somtimes) bald human that will have their sprite vanish completely if they make any update happen to their icon.

**What did you expect to happen**: 
I expected, with knowledge that saving ghosts, blood and other DNA containing objects would cause the maploader to break, to load a map containing none of these things to break. 

**What happened instead**:
Uploading a map containing atmos piping caused the map to break and thus caused the species controller to break and cause the round to require a restart.

**Why is this bad/What are the consequences:**
Every time this occurs the round must be restarted in order to fix the species controller and allow new arrivals to spawn in correctly.

**Steps to reproduce the problem**:
I created a map using build-mode for the plating and used an rpd to create a cold loop with multiple gas filters. This was all to make a template for a sustainable super matter shard containment. When the map saved I then uploaded the next shift to work on it more and when I tried it failed to load and caused the species controller to break.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Used buildmode and an RPD to build most everything that was placed. I can also share the dmm for the map if need be. Unsure if this particular issue with the maploader has been reported, but there we go!

**Comment by Crazylemon64** [comment]
This is a problem with the map saver, not the map loader. I'll adjust the title accordingly.

Certain vars are "shared", but I can't say what happened without seeing the DMI.

**Comment by GuiltyBeans** [comment]
Aaaah, gotcha. I can send you the map over Discord!

**Comment by Sirryan2002** [comment]
This is an administrator-caused error and map writer issues with map dirt have since been patched. Closing as not an issue anymore.
