### ISSUE TITLE
Bounced Radio's and Pods

### ISSUE THREAD

**Issue by IntentEldiablo** [ParadiseSS13/Paradise#9448]
**Problem Description**:
Bounced Radios do not work within security pods

**What did you expect to happen**: 
In hand use of radios to work and broadcast like any regular bounced radio when on

**What happened instead**:
Radio did not broadcast when inside pod

**Why is this bad/What are the consequences:**
a radio not working is bad for communication when tcomms is compromised, and forces pod pilots to exit their vehicles in order to communicate

**Steps to reproduce the problem**:
have a bounced radio in hand turned on inside a pod and attempt to speak into it

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
Nukie game mode, 29/08/18 at 16:00

**Comment by Taaketa** [comment]
I think this is the same issue with meths exist.

**Comment by taukausanake** [comment]
Duplicate of #7086

**Comment by IntentEldiablo** [comment]
If this is a duplicate from over a year ago how has it taken a year to fix?

**Comment by taukausanake** [comment]
Well maybe not a duplicate but related. I think it's because the radio is in a container rather than the world so it's not feeding out

**Comment by variableundefined** [comment]
If it's taking too long, fix it yourself

**Comment by Taaketa** [comment]
@intenteldiablo Your question reeks of entitlement. This github is maintained entirely by volunteers who give up their free time. You can easily see yourself there is over 500 issues and currently a feature freeze to try and get that number down. Duplicate bug reports like this simply slows down this process. I know issues I've submitted in the past I've curated myself and closed where I was unable to duplicate them. Eitherway it's already reported no further need to keep this open. It will not speed up the process of fixing it.

Also podcode is a batch and is not maintained by anyone particular. I've seen numerous times that it'd be better to rip it out than to try and patch a bad job in the first place.
