### ISSUE TITLE
Viruses cannot be distributed by hypospray/sleepy pen/syringe gun

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#9458]
**Problem Description**:
What is the problem?
Injecting someone with infected blood/a vaccine won't give them the virus/vaccine if done through sleepy pen, hypospray, or syringe gun

**What did you expect to happen**: 
Why do you think this is a bug?
Injected person should be infected

**What happened instead**:
How is what happened different from what you expected?
Person isn't infected

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's still injected blood and is inconsistent. Even spray bottle'd blood will infect if the guy gets the blood in him.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Step 1. get a virus bottle, put it in hypospray/sleepy
Step 2. Inject
Step 3. no virus
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

I'm currently working on a PR to fix this, should be up soon.

**Comment by Fox-McCloud** [comment]
This isn't a bug; this is an intentional balance point largely because these methods are all non-delay instant injection devices.

It also ruins the stealth attributes of some of them.
