### ISSUE TITLE
Shadowling Issues

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#946]
Post them here, keep them here, it'll be simpler for me to keep track of them.

- ~~AntagHUD for ghosts needs to be added.~~
- ~~Early round Central Command Report does arrive.~~
- ~~Thralls do not show up on Check Antagonists.~~
- ~~Forgot to turn Ascendant Commune into a langauge.~~
- ~~Shadowling organs are strewn about on the floor after hatching.~~
- ~~Hardsuit helmets are not turned off by Veil.~~
- ~~Jobs such as NT Rep, Sec Pod Pilot, and IAA can be shadowlings.~~

Anything crossed out here has been fixed.

**Comment by Robertha89** [comment]
the shadowling should probably absorb his gibs, cause thats kinda telling and would promote metagaming. Also, possible a destroy light spell.

**Comment by wotan90** [comment]
PDA (and possibly hardsuit) lights will still damage a Shadowling after he casted "Veil". Observed that in two slings rounds and got confirmation of the shadowlings.

**Comment by Robertha89** [comment]
Heads of staff can be shadowlings

**Comment by Spacemanspark** [comment]
That's intentional. Those with loyalty implants can also be enthralled.

**Comment by Robertha89** [comment]
There are no way to deconvert other then straight down murdering, starting with the power of a head is  about as good of an idea as letting antags prey on the SSD. There is also no protection, there is nothing you can do. There is no actual balance to the mode, if you start as a head, you can just convert your staff, and bam, you have em convert everyone else, and you will be unstoppable, without ever acending. There is also no way to check for tralls, or pre-hatched shadowling, and the only thing you can do when shadowling is confirmed is to equip 3 flashlights, and a helmet with a light and walk around maint.

**Comment by Spacemanspark** [comment]
If a shadowling dies, the ones the SL enthralled are automatically deconverted.

**Comment by TheDZD** [comment]
@Robertha89 
 - Post 1: Thought I had fixed that, will take another look at it.
 - Post 2: Which heads of staff in specific? CMO, CE, RD, and HoP being possible candidates is not a bug.
 - Post 3: As of right now, loyalty implants will slow down conversion, but there is no way to outright prevent it. That much is intentional, although may be changed depending on how things pan out.

@wotan90
- I think hardsuit lights are a problem /tg/ has as well, but are you certain PDA lights aren't turning off?

@Spacemanspark No way to deconvert just yet, decided on keeping a mostly 1:1 port and then adjusting as needed.

**Comment by wotan90** [comment]
@TheDZD 
Iam not entirely certain as i was only observing with darkness toggled off, but i remember a shadowling complaining that altough he veiled a pda on the ground, he was dying from it. The PDA holder was glared and stunned, so he should not have been able to switch it back on.
In the next round another shadowling took damage and died, although he used veil in maint. Maybe his enemy flicked the light back on.

**Comment by TheDZD** [comment]
If it was due to the light being immediately toggled back on by the person using it, that's intentional.

**Comment by wotan90** [comment]
Yeah, seems like the PDA lights are reacting how they should.

**Comment by Earthdivine** [comment]
Probably not intended to interact with one another but Xenos seem to be largely immune to the Shadowling powers. I tried to Flash Freeze them when I got caught and they rightfully ignored it.

**Comment by Robertha89** [comment]
shadowling trumps man, man trumps xeno, xeno trumps shadowling.

**Comment by TheDZD** [comment]
@Earhdivine, I'm not entirely certain as to how xenos interact with body temperature, it should be cooling them a good bit, but I'm not certain that it'll actually do much to them.

**Comment by Spacemanspark** [comment]
They should be immune to the cold, shouldn't they?

**Comment by TheDZD** [comment]
Ah, right, they may have been made cold-immune when space was made cold.

**Comment by Robertha89** [comment]
Wait, would that mean that having that genetic power would make you immune?

**Comment by Earthdivine** [comment]
Viel only works on lights you can see, while this was probably made this way so you dont accidently toggle the lights in a room next to you, I think it's keeping Viel from toggling lights in pockets and other places on a person, as I was dieing to the HoS and had taken off their PDA before hand.

**Comment by TheDZD** [comment]
@Earthdivine Veil [specifically checks for lights inside of humanoids](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/shadowling/shadowling_abilities.dm#L62), although again, the light can immediately be toggled back on.

**Comment by Earthdivine** [comment]
He was cuffed and I used Viel on him while in a cloud, was still dieing after I removed all the light I could find off him
