### ISSUE TITLE
Double Energy Sword  too strong

### ISSUE THREAD

**Issue by Harmony123** [ParadiseSS13/Paradise#9463]
Problem Description:
the sword is very unbalanced, I do not think I should block 100% of the shots of all kinds.

What did you expect to happen:
that blocks 50% more or less.

Why is this bad/What are the consequences:
it's obvious, 100% block laser, % block disarm.

Steps to reproduce the problem:
tested with several people

Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?): 
Gamemode sandbox, tested items

**Comment by Birdtalon** [comment]
This is just your opinion not exactly an issue.

**Comment by Taaketa** [comment]
Not a bug. Balance discussion should be on the forum.

**Comment by Harmony123** [comment]
I'm reporting it as an unbalanced object

**Comment by davidchan13** [comment]
Block chance is only 75. And balance issues go to the forum. Also i ded plz nerf

**Comment by Harmony123** [comment]
Laser is 100%

**Comment by variableundefined** [comment]
Stop posting balance issues here. This is for bug report and inconsistency.
