### ISSUE TITLE
Revolution Gamemode Ends Instantly

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#9466]
**Problem Description**:
Rev gamemode ends instantly.

**What did you expect to happen**: 
Revolution gamemode to last more than 5 seconds.

**What happened instead**:
Revolution gamemode instantly ended in a rev victory.
https://i.imgur.com/7nBynaN.png

**Why is this bad/What are the consequences:**
Rev gamemode is unplayable.

**Steps to reproduce the problem**:
Start rev gamemode.
Observe it ends instantly.

**Comment by Shadeykins** [comment]
VIVA LA FRANCE

**Comment by Taaketa** [comment]
Was there command staff? Who were they? When the round started had all players been assigned their roles?

**Comment by Kyep** [comment]
@Taaketa Yes, there were command staff. See screenshot. Roles were assigned and command staff spawned in, but the round still ended instantly.

**Comment by taukausanake** [comment]
It's also interesting to see that the station starts out with a negative score at round start, not that it matters.

_You're all fired_

**Comment by davidchan13** [comment]
Even the code itself doesn't want to play Rev.

**Comment by KasparoVy** [comment]
Working as GOD intended. I'd be happier if it didn't exist at all.
