### ISSUE TITLE
Traitor item mysterious scroll 100% block bullets, laser and fireball wizard

### ISSUE THREAD

**Issue by Harmony123** [ParadiseSS13/Paradise#9470]
Problem Description:
the mysterious scroll is very unbalanced, I do not think I should block all bullets, laser and fireball wizard

What did you expect to happen:
that blocks 50% more or less, or that deteriorates with the blocks

Why is this bad/What are the consequences:
it's obvious, 100% block is 100% unbalance

Steps to reproduce the problem:
tested with several people

Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?):
Gamemode sandbox, tested items

**Comment by datlo** [comment]
again this is balance not a code issue

**Comment by Birdtalon** [comment]
The whole point is it costs 17TC. There's ways of countering it. It forces your play style down a single track route, no ranged weapons. It's not really unbalanced it just means you have to think in order to counter it instead of repeating one strategy.
