### ISSUE TITLE
Sec Helmet Doesn't Hide Vox Head Quills

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#9472]
**Problem Description**:
Your quills still appear even though you're wearing a helmet with a closed top.

**What did you expect to happen**: 
The Quills to not stick through the top of the helmet.

**What happened instead**:
Quills are not hidden by the helmet

**Why is this bad/What are the consequences:**
It looks weird, and doesn't make sense.

**Steps to reproduce the problem**:
Be vox, have quills, wear helmet.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was using Vox Quill Mohawk but it happens with other styles too.

**Comment by Agameofscones** [comment]
This also happens with all skrell 'hair styles' and any other 'hair' sprite that might be larger than the helmet. It's because the sec-helmets are missing the var HIDEHAIR, though I _think_ it might be intentional?

**Comment by KasparoVy** [comment]
It's intentional AFAIK 'cuz Skrell tentacles are a lot more massive than hair you can stuff in a helmet (probably). Vox quills maybe, not sure there.

**Comment by Spaghetti-bit** [comment]
This would require helmets to have a toggle mode since the previous PR had a lot of pushback.

Toggle hair being visible or not.
