### ISSUE TITLE
Chaos Holoparasite Abilities Not Working

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#9482]
Problem:
Nothing happens when the Chaos Holoparasite attacks in dispersion or deception mode. Dispersion mode flat out doesn't work. If deception mode works, there is little indication of it.

What should happen:
Dispersion mode should teleport people away when attacked. Deception mode could do whatever it wants, just something at least.

What happens:
Nothing. The holoparasite attacks with no additional effects.

Why is this bad:
Chaos Holopara is just a massively inferior Standard type that sets people on fire when it walks through them.

How to reproduce:
Attack anyone as the Chaos Holoparasite.

Other notes:
I honestly have no idea if deception does anything, or if it has ever done anything, because there is no indication of it taking effect. Depending on its intended effect, it would be nice if it gave some kind of afflicted sprite to show it worked.

**Comment by SkeletalElite** [comment]
It did used to do something at one point in time, but it broke at some point

**Comment by Breenland** [comment]
I can confirm that at some point, Deception mode worked, as people started yelling everyone was a clown and attacking each other. I've never seen Dispersion work, however.
