### ISSUE TITLE
Scrubbers and Vents on Extended Mode

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#9483]
**Problem Description**:
What is the problem?

Scrubbers on Extended mode can take gases through standard 4x4 windows that are anchored appropriately and from a different room. Vents also beside windows appear to be able to push their gases out past the window into another room.

**What did you expect to happen**: 
Why do you think this is a bug?

Scrubbers should only be able to take gas from the room they are in and vents should not be able to push gases into other rooms that are sealed off.

**What happened instead**:
How is what happened different from what you expected?

The scrubber was taking gas from a corridor beside the room. The vent was pushing pure nitrogen into the corridor unbalancing the atmosphere. The room was sealed off from the corridor.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Probably low priority a temp fix is simply not put scrubbers and vents by windows for now.

**Steps to reproduce the problem**:

An example of this would be at the Assembly line, place a scrubber by the windows near engineering (seal the windows up obviously) and then activate either a panic siphon or set the scrubber to extended mode (use Vox atmos setting).

Then notice, especially on siphon mode, that the atmosphere near south engineering / maint access is lowering despite the scrubber being behind a door or window. It's worth noting in this scenario I have also moved the firelock and door 2 tiles up and 1 tile left and replaced the door with another window.

Repeat the above and have the vents set to push gases out rapidly and it will fill the nearby corridor as well.

You can also test it by having some loose objects nearby and they will get sucked towards the windows and in some cases, break it because the gases being taken almost create a vacuum in the immediate area around the glass.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Windows were doubled checked for being anchored correctly, several were broken when I was trying to figure out why there was a vacuum and were replaced but the scrubbers were still able to pull gas through them and the vent was able to push gas. 

The gas mix in the windows was standard 20% Oxygen and 80% Nitrogen. As I did not drain them before changing the atmosphere in the room.

It is also worth noting that this seems to only affect player built windows and not round start windows as I had scrubbers on the other side of the assembly line and maintenance did not seem affected by a lack of atmosphere despite scrubbers being right against the round start windows there.

**Comment by FunnyMan3595** [comment]
This has been fixed sometime in the intervening years.
