### ISSUE TITLE
Traitor Changelings do not appear on AntagHUD

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#9494]
**Problem Description**:
Changelings who happen to also be traitors do not appear on the AntagHUD with any icon.

**What did you expect to happen**: 
Either a Red S or a changeling symbol to appear next to them with AntagHUD enabled.

**What happened instead**:
They have no symbol next to them, making them appear non-antag.

**Why is this bad/What are the consequences:**
It can lead to players reporting non-antags if they have AntagHUD enabled, or admins mistakingly believing at first that the player also may be non-antag until further investigation.

**Steps to reproduce the problem**:
Have a traitor changeling spawn in a round.
Observe it with AntagHUD on.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode was Traitor Changeling a while ago, been meaning to write this for a while, it may also effect vampire traitors.

**Comment by SkeletalElite** [comment]
I was wondering why I saw a changeling with no icon on antag HUD yesterday.
