### ISSUE TITLE
Air Injecotrs not toggling correctly

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#9495]
**Problem Description**:
New air injectors not being recognized properly by tank console

**What did you expect to happen**: 
They use to work, now they work 1/10 times randomly

**What happened instead**:
Tank computer has an Error, injector not found

**Why is this bad/What are the consequences:**
They dont work right and vents are not a replacement for air injectors

**Steps to reproduce the problem**:
Place air injectors, set frequency and label with multitool. Setup tank computer nearby, input frequency and label of injector. Computer doesn't recognize, at some point it randomly worked for label 'Shit', 'Shit 1', but not "shit 2' or any other single digit. Duplicate problem last week, couldn't turn them on at all, this time after 45 minutes of fucking I got 2 out of 3 to turn on then stopped working again.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
Air injectors shouldn't be this hard to turn on and off anyways, they should be atleast be togglable with a multitool, if not with the air alarms themselves, now with the shittastic tank control computer that barely functions

Edit: Oops, cant edit title?

**Comment by Citinited** [comment]
Was the injector in an area powered by an APC?

Did you try adding the injector to the multitool buffer then linking it to the tank computer that way?

**Comment by GelatinousGlob** [comment]
Yeah it was happening in fully powered areas in the station itself.

Yes I tried using the multitool buffer and it input, but the computer itself still didn't identify it. I later tried again and had the same problem, then fucked with the injector names and frequency a couple time, then randomly a few would work and be accessible, but not reliably even under the same frequency and naming scheme.

**Comment by GelatinousGlob** [comment]
If air injectors were togglable with just a multitool itself, without having to setup entirely new computers, that would make this a non-issue. Right now if you want say a second injector in the turbine you have to steal the nitrous tank control computer, set it up int he turbine, setup the frequency and labels on the injector with a multitool, input it onto the computer with the multitool, and then have identical setups sometimes identify and sometimes not. If there was a hard on/off switch when multitooling the injector to turn it on the computer wouldnt be necessary.

**Comment by GelatinousGlob** [comment]
I may have figured out the reason they arent turning on, you have to undo and reattach the pipe immediatly before them and some started working, however this can be rather difficult when there is a fireproof reinforced wall that has to be removed to do so.

**Comment by Calecute** [comment]
This seems related to #9574. I did some test in a private server and can confirm I was having problems getting the tank control to interface with the air injector, and taking the pipe before the air injector out and putting it on again fixed it.

**Comment by Burzah** [comment]
This appears to have been fixed with https://github.com/ParadiseSS13/Paradise/pull/19867.
Testing it as of now, you can link an air injector back to a control console using a multitool.
Thank you for the report!
