### ISSUE TITLE
Game tries to use non-existent emotes

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#9498]
**Problem Description**:
While getting surgery/unconscious, I saw the message

> "Unusable emote 'writhes in her sleep.'. Say *help for a list."

**What did you expect to happen**: 
Not to get such messages when I don't try to use emotes.

**What happened instead**:
said message appeared

**Why is this bad/What are the consequences:**
It shouldn't do that

**Steps to reproduce the problem**:
get surgery done on you, maybe?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I got bit by a grey terror spider in gateway and went back to get surgery, emote happened while I was getting operated on.

**Comment by Superhats** [comment]
This emote is your character having a dream. As you can see, it's very much broken
