### ISSUE TITLE
Data management for RnD servers doesn't work

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#9503]
**Problem Description**:
The data management option of the 'RD server controller' console seems completely non-functional

**What did you expect to happen**: 
to be able to see the tech of the connected servers

**What happened instead**:
Instead I see this (with maxed research levels): 
![untitled](https://user-images.githubusercontent.com/32099540/45254666-61a01d80-b37c-11e8-8f34-966ae931c0bd.png)
A very unhelpful page  (It also has a typo, what with the P after Data Management'

**Why is this bad/What are the consequences:**
You can't remotely look at known tech/designs without using an RnD console. The server monitoring console has a completely useless options

**Steps to reproduce the problem**:
Start round, use the RD server controller in RnD's server room, click 'Data Management'

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing

**Comment by alexkar598** [comment]
Dupe of Ana ancient issue I made

**Comment by TDSSS** [comment]
Huh, I did search for 'server' in open issues and didn't find anything, can you link it?

**Comment by alexkar598** [comment]
It got closed because some people don't read issues or pea before closing them
