### ISSUE TITLE
Removing a lightbulb from a light fixture while resting causes the bulb to disappear

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#9513]
**Problem Description**:
Exactly what it says in the title. If you remove a lightbulb while your character is resting, the removed lighbulb will be nowhere to be found.

**What did you expect to happen**: 
The lightbulb should either not be removed, or fall to the floor, as resting characters can't hold items.

**What happened instead**:
The lightbulb was removed from the fixture and disappeared from the game.

**Why is this bad/What are the consequences:**
It's bad because items are disappearing.

**Steps to reproduce the problem**:
- Equip black gloves
- Rest beside light fixture
- Click on fixture
- Lightbulb is removed and disappears altogether

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Seems like it happens on both on and off lights. I can't think of anything else to note.

**Comment by Taaketa** [comment]
New sling meta confirmed.
