### ISSUE TITLE
Radiation storm error

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#9525]
**Problem Description**:
During the radiation storm event there is a place in arrivals garden which is not effected

**What did you expect to happen**: 
All non maint/shuttle areas should be effected

**What happened instead**:
Refer to the picture

**Why is this bad/What are the consequences:**
Not high priority, just something to be fixed when someone can works on it.  Consistency issue.

**Steps to reproduce the problem**:
Start the radstorm event.  That one tile is not included and is safe on it.

https://imgur.com/cbBblKW

**Comment by SamHPurp** [comment]
There is another one to the right of Medbay.

Waiting for some existing map edit PRs to merge before I try to fix though....

**Comment by Agameofscones** [comment]
In medical maints there is an area with a space heater in it that is not shielded, despite being in a maintenance tunnel.

**Comment by SamHPurp** [comment]
Yeh thats the one I mentioned.

Once you guys merge #9539 I'll PR the fix for these (and a few other issues creating by the maintainenance/medbay rework....
