### ISSUE TITLE
´ character breaks examining and a bunch of other stuff

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#9530]
**Problem Description**:
People with a ´ in their flavourtext will break a whole bunch of admin verbs, examining etc.

**What did you expect to happen**: 
To be able to examine them, use VV, player panel etc.

**What happened instead**:
Examine won't work, other admin verbs won't work @Spartan6 experienced this

**Why is this bad/What are the consequences:**
It's a bug
We had to use Adv Proc-call to VV them...

**Steps to reproduce the problem**:
Add a ´ into flavour text

**Comment by Breenland** [comment]
I hope this is the final cause. It's been around on various people but couldn't ever figure out what caused it...

**Comment by Spartan6** [comment]
@Breenland I tested it and it certainly is a confirmed cause, I don’t know if it is the only cause though.
