### ISSUE TITLE
Pressing Cancel Button when Selecting Holopara type doesn't cancel

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#9544]
**Problem Description**:
Title

**What did you expect to happen**: 
Cancel should  not give you a holopara

**What happened instead**:
End up with a standard holopara

**Why is this bad/What are the consequences:**
No way for sec officers to tell if a holopara injector is used without using it

**Steps to reproduce the problem**:
Use holopara injector. Press cancel when choosing type.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not relevant

**Comment by variableundefined** [comment]
I think it's better to just have it indicate whether it is used on examine. However that'd be a feature.

**Comment by variableundefined** [comment]
Actually, I am doubtful this is really a bug - you are not supposed to cancel at that point. A confirmation prompt, plus what I said above, would be a better solution.

**Comment by SkeletalElite** [comment]
Yeah thats what I was thinking, but I just repoted it as it was. Probably best to add a confirmation prompt BEFORE you reach that point

**Comment by Contrabang** [comment]
Fixed by #15178
