### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#955]
When scrolling up in chat to see previous messages new messages will make it go all the way back to the bottom.

**Comment by TheDZD** [comment]
Chat scrolling has a few issues, most of which I assume are caused by BYOND, such as the fact that it will scroll up every time a new message appears if you have any text selected.

**Comment by Fox-McCloud** [comment]
Yeah, most of these are BYOND related; the most recent beta version, for example, will automatically delete text for no reason at all and start populating the box again--was annoying enough I reverted back.

**Comment by ZomgPonies** [comment]
507.1284 fixes this issue. Go update your BYOND.

**Comment by Iamgoofball** [comment]
hallelujah
