### ISSUE TITLE
Small Typo in Ling Speech. 

### ISSUE THREAD

**Issue by Wolfsyndrome** [ParadiseSS13/Paradise#9561]
**Problem Description**:
There's a small typo in the speech section whenever a Ling whispers to the other Lings. There are two words to describe the fact the Ling is being quiet, when there really only should be one.  It's all shown in the image. 

**Why is this bad/What are the consequences:**
Not necessarily a bad thing, just a small typo. 

![untitled](https://user-images.githubusercontent.com/23321184/45599795-47a4b180-b9f2-11e8-990d-5e0597c8f420.png)

**Comment by DesolateG** [comment]
That's tajaran language and whispering. It's not a typo but a problem of very specific conditions being met where two adverbs are being placed.

Those conditions are a speech_verb, whispering, and speech_problem_flag.

Example: speech_verb - mrowls, rawrs, clicks.

The speech verb has to be used, and not overridden by yells, stutters, etc.
