### ISSUE TITLE
Stuck after using 'observe' verb

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#9563]
**Problem Description**:
As a ghost, if I use the 'observe' verb under OOC to follow the singulo/nuke disc and so on, I am stuck following things and cannot move away from whatever I am observing

**What did you expect to happen**: 
To be able to break free like when using the 'follow' verb, to be able to teleprot around as a ghost and otherwise freely observe the round.

**What happened instead**:
I am stuck observing whatever I picked to observe. I can use the observe verb again to follow other things, but I cannot use the follow or teleport verb, use the arrow keys to move around or click the 'follow' behind people's names in comms.

**Why is this bad/What are the consequences:**
It makes it a lot less fun to be an observer. I haven't been cloned after doing that yet, but maybe it would mess with you then too? Restarting my client frees me.

**Steps to reproduce the problem**:
Be a ghost, use the 'observe' verb to follow the singularity, try to move with the arrow keys/wasd

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I joined directly as a ghost/observer, haven't tried it yet after dying yet.

**Comment by Superhats** [comment]
That's because the "observe" and "follow" verbs work differently.
Follow moves your ghost to the mob, while observe just moves your "camera". There should be a verb in the OOC tab called "Cancel camera view" which returns the view to your ghost

**Comment by TDSSS** [comment]
Oh. Well that's just a taaaaad counter-intuitive. Especially since usually moving breaks you out of a camera view. But not a bug I guess. Thanks
