### ISSUE TITLE
Space Pods Immune to Tesla

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#9565]
**Problem Description**:
The Tesla does nothing to space pods.

**What did you expect to happen**: 
The space pod to blow up.

**What happened instead**:
It can freely fly around in the tesla with no harm to it or it's pilot.

**Why is this bad/What are the consequences:**
Tesla supposed to zap and kill/dust people and blow up machines, can use space pod to not give a fuck.

**Steps to reproduce the problem**:
Fly a pod around a tesla.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Irrelevant

**Comment by Ty-Omaha** [comment]
Pretty sure this is intentional. Planes get struck by lightning all the time and they are fine. You can hide in a locker to protect yourself against the tesla, or wear a hardsuit with insulated gloves.

**Comment by Taaketa** [comment]
@Ty-Omaha Isn't this just the fact that no one is actively working on podcode and no one wants to touch it either cos it's awful?

**Comment by Citinited** [comment]
> You can hide in a locker to protect yourself against the tesla

You haven't been able to do that for over two years

**Comment by Citinited** [comment]
It's possible the bolt went past the closet (looking as if the bolt bypassed the closet entirely), but closets do certainly blow up when the tesla zaps them

**Comment by TavishMacdoogle** [comment]
this "bug" happened to me recently 
![teslabug](https://user-images.githubusercontent.com/46586139/51012440-11ec8100-152b-11e9-8ca0-973b8c8d4c2c.PNG)

**Comment by Twinmold93** [comment]
I'll have to look into this in the near future. I'm not sure if a 'zap' should cause anything major to a pod other than perhaps battery drain/charge (random chance?), though a direct hit should obviously destroy the pod. I'll need to discuss this with other people.

**Comment by davidchan13** [comment]
As someone who bought pod pilot, I'd be okay with pods being removed.
