### ISSUE TITLE
Plant bag changes plants

### ISSUE THREAD

**Issue by TatsumakiMagi** [ParadiseSS13/Paradise#9573]
**Problem Description**:
Sometimes, using a plant bag on a stack of plants and then clicking the plant bag again to dump the plants out will change the plants from one to another, in my case wheat containing earthsblood was turned into nettles containing nothing. 

**What did you expect to happen**: 
The plants to stay the same, with the same chemical contents and traits

**What happened instead**:
The wheat was turned into nettles

**Why is this bad/What are the consequences:**
It makes it difficult to transport your plants around, having to pick them up one at a time

**Steps to reproduce the problem**:
Create wheat containing earthsblood, use a plantbag on the picked wheat, click the plant bag to dump the wheat and see nettles (Does not always happen)

**Comment by DesolateG** [comment]
I can't reproduce.

**Comment by Birdtalon** [comment]
This is really odd and I can't explain why this would occur. I am also unable to produce? Did this happen more than once or was it a one off?

**Comment by FalseIncarnate** [comment]
If it were just the icon changing it could have been cache corruption or something, but if the entire item has changed... that's a weird one. You could maybe have forgotten about some nettles in there, which would explain why it wouldn't reproduce?

**Comment by TatsumakiMagi** [comment]
It is an odd one,it has only happened the once for me and I had the other botanist repeat it too so I don't think it was me misplacing the nettles. I'm not too sure how else I can help with finding the cause of the issue though.
