### ISSUE TITLE
Shadowlings can use abilities while jaunting

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#9580]
**Problem Description**:
While jaunting shadowlings still have full use of their abilities

**What did you expect to happen**: 
Shadowling abilities should be on cooldown until they fully manifest back out of jaunt.

**What happened instead**:
Shadowlings were jaunting past security officers and other crew while chilling/screaming them

**Why is this bad/What are the consequences:**
It leaves little to no counterplay as you do not even realize you are under attack until the shadowling has already left the area as they just 'fly' past you in ghost form and out into another area.

**Steps to reproduce the problem**:
Be shadowling, have powers.  Jaunt and move around, still use powers while jaunted.

**Comment by taukausanake** [comment]
This has been mentioned before in [#8005](https://github.com/ParadiseSS13/Paradise/issues/8005#issuecomment-326557446) but nothing more after that. This will fall more under a balance change rather than bug even though they shouldn't have powers while jaunting

**Comment by Breenland** [comment]
Also part of this, they will break glass tables and fall on the ground if they happen to move over one while jaunting.

**Comment by Crazylemon64** [comment]
Unsure where to file this, Neca says it's a matter of balance, however, so closing. Take it to the forums if you want this changed.

The glass tables breaking is a flaw of our current movement system, and would require some refactoring to resolve. Nonetheless, it is a bug, and you may want to open another issue for that.
