### ISSUE TITLE
IPC can not change the color of the head in mirrors

### ISSUE THREAD

**Issue by Harmony123** [ParadiseSS13/Paradise#9585]
**Problem Description**:
What is the problem?
IPC can not change the color of the head in mirrors

**What did you expect to happen**: 
Why do you think this is a bug?
many menu options do not work

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
can not paint your ipc if you lose your head

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
try to change the color of my head in a mirror

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Secret, try to change the color of my head in a mirror

**Comment by Crazylemon64** [comment]
The color of the head is based on the IPC's "Skin color". I don't believe that can be changed in a mirror.

**Comment by Harmony123** [comment]
> 
> 
> The color of the head is based on the IPC's "Skin color". I don't believe that can be changed in a mirror.

So, if I have a white body and I wear a black head I should be able to change it in the mirror, like the hair color

**Comment by taukausanake** [comment]
Pretty sure that's not how it works. I think this might be the same case for all IPC body parts? Even if the same model type. There isn't any update icon for their color. Maybe something could be implemented after the freeze that let's Roboticists change IPC body colors or the cyborg charger can do it. Or maybe you just need to cover yourself in paint
