### ISSUE TITLE
Cyborg/Android tools spamming themselves.

### ISSUE THREAD

**Issue by The-Driker** [ParadiseSS13/Paradise#9594]
**Problem Description**:
When equipping a tool as a cyborg/android/robot. The tool will spam it's use function, making things like welding impossible and interrupting the player with context windows. 

**What did you expect to happen**: 
The tools shouldn't be activating themselves without player input. 

**What happened instead**:
The tools will keep using themselves.

**Why is this bad/What are the consequences:**
It makes it difficult to function. Especially in engineering.

**Steps to reproduce the problem**:
Be a cyborg and then equip any tool or item/

**Comment by Birdtalon** [comment]
Couldn't reproduce with a variety of tools/modules.

**Comment by The-Driker** [comment]
After testing today, I also could not reproduce the issue again. Whatever was happening, isn't anymore, so I'll go ahead and close this issue.
