### ISSUE TITLE
Humanised farwa, wolphin and stocks are not usable in genetics

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9595]
**Problem Description**:
If you humanise a farwa/wolphin or stock you can't use them in genetics. Their DNA structure is ruined beyond recognition.

**What did you expect to happen**: 
You used to be able to do this before. And it works for neara's and monkeys.

**What happened instead**:
That you can manipulate the genes as usual. Not getting the message shown below.

**Why is this bad/What are the consequences:**
It won't stop genetics from working but it makes it harder and it's confusing to say the least. Multiple mentor helps have been about this.

**Steps to reproduce the problem**:

1. get a lesser form farwa/wolphin/stock
2. Inject them with a block injector with the needed block (55) or manipulate block 55 using the machine
3. The machine will now tell you that the DNA is unusable.
I've tested all 3 creatures with the block injector method and the block manipulation method. All give the same result.

What the machine will show you:
![image](https://user-images.githubusercontent.com/15887760/45917258-806ddc00-be73-11e8-952c-116c1692d158.png)

**Comment by Ty-Omaha** [comment]
https://github.com/ParadiseSS13/Paradise/pull/9497

**Comment by variableundefined** [comment]
Fixed
