### ISSUE TITLE
Xenomorph Larva Balance

### ISSUE THREAD

**Issue by Corocan** [ParadiseSS13/Paradise#9602]
**Problem Description**:
Xenomorph larva are capable of pulling facehuggers to attack targets. Combined with a pretty formidable movement speed, this allows for a pretty much unstoppable rush combination where larva will divebomb populated areas while pulling facehuggers, giving the crew no time to react.

Even worse, larva can ALSO drag the facehugged bodies straight back to the hive.

**What did you expect to happen**: 
Larva should be focusing on growing and staying alive. Their movement speed should not be used for a combative advantage. It is granted to them as a method of avoiding damage and to balance out their inability to directly fight.

Two potential fixes that come out to me would be to either greatly lower the speed of larva **or** add a flag to larva that prevents them from pulling entities. In my opinion, the later seems more reasonable because larva shouldn't be able to pull _anything_ from both a realism standpoint and a balancing one.
 
**Why is this bad/What are the consequences:**
It results in a very unbalanced tactic of larva dragging facehuggers into areas, letting them facehug someone, then dragging that person back to the hive while facing zero risk of being killed or otherwise impeded.

**Comment by Taaketa** [comment]
Maintenance Drones can't pull certain objects. I'd say apply the same rules they adhere to, to Larva.

**Comment by Corocan** [comment]
> 
> 
> Maintenance Drones can't pull certain objects. I'd say apply the same rules they adhere to, to Larva.

The way Maintenance Drones are coded, they can't pull anything above 'small' size items. I'm not sure if there's a NOPULL flag or not. We could cookiecut the code used for maintenance drones and just paste it into the larva's code, but we'd have to adjust it for the fact that huggers are considered 'tiny' class objects. I suppose this ultimately completes the same goal anyways.
