### ISSUE TITLE
Fork EAST sprite is the wrong way.

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#9603]
**Problem Description**:
The in hand sprite for the fork is wrong when facing East

![dreamseeker_2018-09-23_18-46-50](https://user-images.githubusercontent.com/25027759/45931149-5d215a80-bf61-11e8-966e-ffbfd23341fc.png)
![dreamseeker_2018-09-23_18-46-54](https://user-images.githubusercontent.com/25027759/45931150-5d215a80-bf61-11e8-88a5-85a9e8edee58.png)

**Comment by Necaladun** [comment]
ffs now i can't enjoy ss13 at all anymore

**Comment by Birdtalon** [comment]
Absolutely game breaking.

**Comment by uzername** [comment]
That's fine, I sometimes carry fork in the same manner at home too, not to stab someone with it by occasion.

**Comment by Corocan** [comment]
Tactical fork

**Comment by taukausanake** [comment]
I hold things like that so I don't accidentally stab someone with the thing I'm holding, but I'm ready to if I need to
