### ISSUE TITLE
Duct Tape, Package Wrapper, Wrapping Paper missing proper stack description

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#9607]
**Problem Description**:
Certain items have odd descriptions when in a stack, such as duct tape, package wrapper, and wrapping paper.

**What did you expect to happen**: 
When inspected, the item to say, "There are XX [objects] in the stack," such as "There are 25 sheets in the stack." 

**What happened instead**:
When inspected, the items say, "There are XX s in the stack," such as "There are 25 s in the stack."

**Why is this bad/What are the consequences:**
It's not particularly important, just annoying and inconsistent.

**Steps to reproduce the problem**:
1. Find a roll of duct tape, package wrapper, or wrapping paper.
2. Examine.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Those three I know for certain have this issue, but I'm not sure if there are more.
![2018_09_24_11_55_32_paradise_station_13](https://user-images.githubusercontent.com/38596550/45966531-02cfda80-bff1-11e8-85ca-a048eca6ef66.png)

**Comment by dapocalypse** [comment]
Will get on this.
