### ISSUE TITLE
Headslugs not showing clearly that they are dead in form of sprites or examine text

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9613]
**Problem Description**:
When a headslug dies it won't change it's examine text and the sprite does not reflect it good enough.

**What did you expect to happen**: 
A different sprite or his examine text changing to reflect his state.

**What happened instead**:
His examine text did not change and the sprite is not clear enough.

**Why is this bad/What are the consequences:**
It makes it hard to see if one is actually dead or not. You can see using a medical hud or just beating it a lot.

**Steps to reproduce the problem**:
1. Spawn one in
2. Kill it

**Comment by farie82** [comment]
Yes the changeling slugs. The borer slugs do a kinda similair thing if they die. But they have a better dead sprite. The headslugs just turns upside down. Which is almost the same as the normal sprite.

**Comment by variableundefined** [comment]
A very easy fix is to just add in a they are dead descriptor when they'd well, dead.
