### ISSUE TITLE
4k Resolution Support Isn't Under A Relevant Submenu

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#9614]
**Problem Description**:
What is the problem?
The new 4k resolution support shows up under the root of the 'Icons' setting menu instead of under `Icons\Size`

**What did you expect to happen**: 
Why do you think this is a bug?
It disobeys the convention set by every other view scaling option.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Inconsistency

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Click the `Icons` setting menu.

**Other related info**:
A by-product of #9406 
![scalingfailingparadisess134ksupport_20180925](https://user-images.githubusercontent.com/12377767/46053435-5e55b180-c132-11e8-8958-242b054fb673.PNG)

**Comment by Fox-McCloud** [comment]
@FlattestGuitar 

This is why you update your master before adding things
