### ISSUE TITLE
There is no Click Cooldown on Grille Shocking when Dragging

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#9615]
**Problem Description**:
What is the problem?
You can Alt-Click and drag a guy into a grille as fast as you can click, husking them in seconds if not quicker

**What did you expect to happen**: 
Why do you think this is a bug?
You can instakill someone with a shocked grille

**What happened instead**:
How is what happened different from what you expected?
I expected a click cooldown

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's already robust but this is unreal

**Comment by variableundefined** [comment]
Probably just need a cooldown on grille before allowing another shock.
