### ISSUE TITLE
Plasmafolk doctors spawn with two penlights

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#9622]
Related PR: #9621 
Look for that PR on how to fix it.

Details:
When a plasmafolk doctor, you will get two penlights, instead of one.

**Comment by Taaketa** [comment]
I'm curious what exactly does good first issue tag mean?

**Comment by SamHPurp** [comment]
@Crazylemon64 have you checked that HoS Plasmas dont' get two guns. I kinda have a sinking feeling they do after that merge.

**Comment by variableundefined** [comment]
They did. I noticed it, that was what the PR is for. (It is actually a good first issue because the underlying problem has been fixed, literally just a two line / one line change)
