### ISSUE TITLE
Deadminning messes up verb descriptions

### ISSUE THREAD

**Issue by Ty-Omaha** [ParadiseSS13/Paradise#9634]
**Problem Description**:
Things such as pressing LOOC to type in, not to toggle, appears as "Globally Toggles LOOC". It functions normally though.

**What did you expect to happen**: 
For it to give the correct description

**What happened instead**:
It didn't

**Why is this bad/What are the consequences:**
It's annoying

**Steps to reproduce the problem**:
Deadmin
Go into OOC tab
Hit OOC / LOOC
Observe weird descirptors

https://i.imgur.com/7sHUVNx.png

https://i.imgur.com/jtJskRy.png

**Comment by DGamerL** [comment]
Two people could not reproduce this bug, meaning that it most likely has been fixed along the way! One PR I could see that could have fixed it was #18896. Thank you for reporting this, and if it happens again, feel free to make a new issue report!
