### ISSUE TITLE
NSS Cererbron Telecomms APC Runs out of power too quick. 

### ISSUE THREAD

**Issue by Wolfsyndrome** [ParadiseSS13/Paradise#9645]
**Problem Description**:
The APC located in the Telecomms room in the AI sat on the Cerebron station runs out of power too quickly, to where it auto-shutsdown the entire room's machines when it gets too low.

**What did you expect to happen**: 
I guess I expected the APC to be able to handle the machines well until after the end of a 2-hour shift? 

**What happened instead**:
The power ran so low the auto-setting shut down all the machines, so I no longer received alarm messages as the AI. 

**Why is this bad/What are the consequences:**
It's very easy for the AI to miss important alarms when all the machines are shut down, and we don't get a warning message the APC's run low, either. 

**Steps to reproduce the problem**:
Run the station for 2+ hours and see for yourself? 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
No real additional stuff of note. Maybe as a possible solution, attach like 10 solar panels to the AI sat so it has its independent power and can charge the SMES already in the sat to keep the APC charging? 
![untitled](https://user-images.githubusercontent.com/23321184/46256387-820a5600-c4aa-11e8-897c-24466df4336a.png)

**Comment by SamHPurp** [comment]
Rounds lasting longer than 2 hours, it runs out of power?

There is both an SMES with a pacman, and un-completed wiring towards the station.

If a shift it going on for more than 2 hours, well, an engineer is going to have to do 10 seconds of work.

This can be closed imo.

**Comment by Taaketa** [comment]
All APCs cells are basic cells. They have 5000 watt storage. Tcomms will eat that up but as far as I concerned Tcomms should remain that way. I don't know of any location with an APC that contains a cell any larger than basic.

The actual ingame fix is to have the solar arrays tracker turned on. Lately tcomms have had the solar tracker disabled by default for some reason. It was on by default during the last tcomms sat overhaul. But again I have no issue with this. It's a simple fix for AI, Captain, RD, CE or HOP to go and resolve. In otherwords the above power problems, I feel can be dealt with ingame.
