### ISSUE TITLE
Broken metastation bot pathing

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#9652]
**Problem Description**:
What is the problem?
Bots move only on small L shaped path in escape, not patrolling rest of station.
On attached screenshot I marked their path with red line.

**What did you expect to happen**: 
Why do you think this is a bug?
Bots should patrol whole meta station, not just escape

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I found them there, I assume It was since round start
![1](https://user-images.githubusercontent.com/35972878/46260201-1c868b80-c4e3-11e8-9412-5cc8c7d5942a.png)

**Comment by SamHPurp** [comment]
God that was tedious to fix, remapped the whole pathing for the area.

Will be in the next update, just fixing something else, and will push the update.
