### ISSUE TITLE
IPCs Stun Immunity

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#966]
IPCs are currently immune to stuns that use the Stun() proc or stunned var, I can't quite seem to find what's causing it.

**Comment by Krausus** [comment]
[Species that cannot feel pain can also not be stunned.](https://github.com/ParadiseSS13/Paradise/blob/e004610827b13ca14204d7ebc1a8b37dad0e0ef0/code/modules/mob/living/carbon/human/life.dm#L1810-L1816)
```
/mob/living/carbon/human/handle_stunned()
	if(species.flags & NO_PAIN)
		stunned = 0
		return 0
	if(..())
		speech_problem_flag = 1
	return stunned
```
So Diona should be immune to stuns, too.

**Comment by Iamgoofball** [comment]
Are you kidding me? Why are they immune to stuns? Remove that.
