### ISSUE TITLE
The Flagbearer fluff items not spawning

### ISSUE THREAD

**Issue by TheFlagbearer** [ParadiseSS13/Paradise#9665]
**Problem Description**:
I am supposed to spawn with my Arachno-Man fluff items but they do not spawn in. They should be available for all jobs.

**What did you expect to happen**: 
I should spawn with a full Arachno-Man set of Mask, Costume, and Boots.

**What happened instead**:
Only the Mask and Costume spawn in at roundstart when spawning as Civilian and none of the items spawn in for other jobs.

**Why is this bad/What are the consequences:**
I'm missing my fluff items on certain jobs.

**Steps to reproduce the problem**:
Load character and join game as Willow Walker.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Applicable to all rounds.

**Comment by Crazylemon64** [comment]
This will need a db edit, one moment
