### ISSUE TITLE
Tile graphical overlay bugs

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#9668]
**Problem Description**:
Some tiles appear completely blacked out (even with darkness off), or using inappropriate overlays.

**What did you expect to happen**: 
Tiles look correct/physically possible.

**What happened instead**:
Some tiles appear to have overlays over a plain black square.
Other tiles are just plain black.

**Why is this bad/What are the consequences:**
It looks bad.

**Steps to reproduce the problem**:
View the hidden room in arrivals maint.

![tile_overlay_bugs](https://user-images.githubusercontent.com/16434066/46332409-eb55aa80-c60b-11e8-9fcf-d66af93cf06d.PNG)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Seems to happen consistently between rounds.
https://github.com/ParadiseSS13/Paradise/pull/9611 is probably responsible.

**Comment by SamHPurp** [comment]
Welp, I thought I got them all.

Super easy fix if someone wants to take it from me, just make it normal flooring, then apply the /landmark/damaged decal over the top.

If not I'll do it soon!
