### ISSUE TITLE
Virus symptoms stacking when using multiple virusses (balance)

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9671]
**Problem Description**:
It is possible to stack virus symptoms using multiple virusses. These symptoms include toxic filtering and toxic compensation for example.

**What did you expect to happen**: 
The symptoms not stacking on top of each other and instead picking the best working one from the virusses.

**What happened instead**:
The symptoms stacked.

**Why is this bad/What are the consequences:**
Combining all the beneficial symptoms and some side effects together in a smart way you can heal up to 27.7 health per tick. This is the max. Average is lower due to random chance.

**Steps to reproduce the problem**:
Create a healing virus with Toxic filtering in all the 3 the virusses. And add some side effects to min max.

This itself might not be a bug but it's hella unbalanced at the moment.
I won't include the symptoms to create this bizarre virus due to it being able to be abused to hell. This virus includes all the beneficial symptoms though. Aka: Sensory restoration, self resperation, toxic compensation, toxic filtering *3, stimulants and weight even.

I'm posting this to get some feedback to see if people actually want it changed or not.

**Comment by FlattestGuitar** [comment]
Isn't this, like, the entire point?

**Comment by farie82** [comment]
I'd say it's a bit to OP. healing potentially 27.7 health per tick. (And this is if you don't maximise it for the brute/burn/toxin healing only).

**Comment by IrkallaEpsilon** [comment]
Lower the heal and its fine I guess?

**Comment by Sikroth** [comment]
I think virology could use a full rework of some sort. The healing it *can* provide is stupid high, while also requiring a lot of dumb RNG work, and the use of literal powergamy, no-rp symptoms no normal person would wan to suffer. It's in a very awkward spot, to be honest. /tg/'s implementation has some good ideas (conditional healing, neutering symptoms) that I particularly enjoy. They also don't use a triple virus system, instead having only one virus effect you and higher resistance viruses overriding lower ones.

That said, that's kinda out of the scope of this issue. I believe having the symptoms not stack would be a good idea. It reduces *some* of the variance from a regular virus to a perfectly crafted minmax triple virus and gets rid of the OP healing you describe. If you just lower the numbers altogether you'll make non minmaxed viruses suck hard.

Just my opinion though.

**Comment by Crazylemon64** [comment]
As a balance thing, this should be handled on the forums
