### ISSUE TITLE
[Delta] Invisible locker in dorms

### ISSUE THREAD

**Issue by PootisMan1559** [ParadiseSS13/Paradise#9682]
**Problem Description**:
Invisible locker in Dorms

**What did you expect to happen**: 
The locker being visible when closed.

**What happened instead**:
The locker is invisible when it is closed.

**Why is this bad/What are the consequences:**
You could hide all sorts of stuff in there, and no one would find it since it is invisible.

**Steps to reproduce the problem**:
Go to dorms on delta station, next to the black, grey, green, pink and mixed wardrobe is a locker called "yellow wardrobe" which is invisible, the only way of opening and closing it is with the "toggle-open" command, or clicking on it with alt-clicking the floor first.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It is visible when opened, but not visible when closed.

**Comment by Crazylemon64** [comment]
I'm not sure what would cause this - the kind of error doesn't seem like something based on the map, unless there's something with weird vars set
