### ISSUE TITLE
Bag stacking and medical patches

### ISSUE THREAD

**Issue by M3hillus** [ParadiseSS13/Paradise#969]
When  #951 was added, I noticed when I put multiple medicinal patches in my bag, they stack. No matter the name or reagent involved.

I had two of "Patch N" And two of "Patch C". I place 2N In bag. They stack. I then place 2C in bag. 2N becomes 4C, but when I remove 2C, It returns to 2N.

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
Resolved via #970
