### ISSUE TITLE
[Delta?] Body Scanner Consoles are created invisible

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#9691]
**Problem Description**:
Creating a /obj/machinery/body_scanconsole can result in an invisible object with no sprite.

**Why is this bad/What are the consequences:**
Aside from the fact that people cannot see the object they made, it also results in an invisible wall.

So far, only confirmed to happen on deltastation, but that may be because nobody makes them on the regular station.

**Comment by lass9030** [comment]
Couldn't find anything at the coordinate or by search. It might have been an in-round thing?

**Comment by SamHPurp** [comment]
I also cannot locate anything near the co-ordinates that you're talking about @Kyep

**Comment by Kyep** [comment]
Saw it happen again today. Apparently it only happens with body scanner consoles constructed in round.
Description/title updated.

**Comment by SamHPurp** [comment]
I really need more info, screenshots, VVs... something.

I can't reproduce!

**Comment by Kyep** [comment]
Did you try constructing the console?

**Comment by Certhic** [comment]
Admin spawned consoles and bodyscanner seem to be invisible. Regularly created ones aren't.

**Comment by AffectedArc07** [comment]
These dont exist anymore
