### ISSUE TITLE
Borgs cannot interact with crew members if a surgery has been started on them (Except to perform the next step in said surgery).

### ISSUE THREAD

**Issue by EvadableMoxie** [ParadiseSS13/Paradise#9692]
**Problem Description**:
If a crew member has a surgery in progress, a borg cannot interact with them in any way other than to do the exact next step in that surgery.

**What did you expect to happen**: 
Borgs should be able to do other things like us a medical analyzer or inject crew with their hypospray during surgeries.

**What happened instead**:
Borgs cannot do anything except the next surgery step.

**Why is this bad/What are the consequences:**
This creates a lot of issues especially for medical borgs.  For example if a patient dies on the operating table, you can't defib them with an ongoing surgery.  For IPCs, if someone has begun a surgery, a medical borg can't nanopaste them.  A medical borg can't inject Epi into someone if they start to crash during surgery.  An engineering borg can't repair a synthetic limb on an organic crew member if a surgery is in progress. 

**Steps to reproduce the problem**:
Start a surgery on a crew member, try to do anything else. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by farie82** [comment]
The problem is caused by the line in surgery.dm on line 92-93
`if(isrobot(user) && user.a_intent != INTENT_HARM) //to save asimov borgs a LOT of heartache`
`		return 1`
