### ISSUE TITLE
[Delta] Something in sec causes crashes

### ISSUE THREAD

**Issue by Raeschen** [ParadiseSS13/Paradise#9704]
**Problem Description**:
Being in sec causes a crash. In the brig area.

**What did you expect to happen**: 
crashing is bad

**What happened instead**:
i crashed??

**Why is this bad/What are the consequences:**
crashing is bad.

**Steps to reproduce the problem**:
Be in sec

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was engineer? had engineer stuff. tried to build machine.

**Comment by SamHPurp** [comment]
Seems to only have happened in that round. Its not happened in the rounds since, at least that I've seen....

Weird.

**Comment by KasparoVy** [comment]
Build 'em up and take the server down

**Comment by SamHPurp** [comment]
Hasn't happened any other time... fingers crossed it was non-delta related lol.
