### ISSUE TITLE
Prayer Bread Act Like Normal Prayer Beads

### ISSUE THREAD

**Issue by VeteranKyl** [ParadiseSS13/Paradise#9707]
**Problem Description**:
The Chaplain Prayer Bread acts like normal Prayer Beads.

**What did you expect to happen**: 
The Prayer bread is described on the wiki as having the ability to drain the color from clowns and silence them. This doesn't seem to work.

**What happened instead**:
The bread act like prayer beads, healing those it is used on, including the clown.

**Why is this bad/What are the consequences:**
A person will chose the bread to use on the clown, only to find it doesn't work. The bread doesn't serve the purpose it's described to be use for.

**Steps to reproduce the problem**:
Take a round start clown, a chaplain with the prayer bread, and use the bread on the clown. It'll act like normal prayer beads instead of prayer bread.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was during a normal traitor round. The clown was a Vox. My chaplain character was a vulpkanin.

**Comment by Kyep** [comment]
Can confirm that prayer bread now works. This can be closed.

**Comment by Kyep** [comment]
@AffectedArc07
