### ISSUE TITLE
Collector arrays do not collect power from walking on uranium floors.

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#9708]
**Problem Description**:
What is the problem?
Radiation engine is (fun) obscure thing to make as engineer when you are bored as engineer(Like paper engine).
Monkeys being moved by conveyor tiles on uranium floor creates radiation, the more monkeys, the more radiation.  However, the radiation collector array do not collect radiation from walking on uranium floor tiles.

**What did you expect to happen**: 
Why do you think this is a bug?
I expected power output as the cherry on the cake when one shift I did "nuclear reactor". I ended up with a LOT of radiation emission and 0 power from all that radiation.

**What happened instead**:
How is what happened different from what you expected?
Radiation collectors generated no power at all.
Collector arrays should generate power from any nearby radiation source, not only singularity engine.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Making fun mini project loses its secondary point of making at least minimum of power. 

![bug](https://user-images.githubusercontent.com/35972878/46526954-13edd680-c890-11e8-835c-0a5b03de2bdf.png)

**Comment by Deelite34** [comment]
No (obscure) fun allowed ☹️.At least you can make chernobyl reactor, that'll collapse your body into pure hydrogen in few minutes

**Comment by DesolateG** [comment]
Not a bug, radiation collectors only collect singularity and SM radiation
