### ISSUE TITLE
AI not spawning/given out on new round, latejoining not possible

### ISSUE THREAD

**Issue by IrkallaEpsilon** [ParadiseSS13/Paradise#9717]
**Problem Description**:
AI Job not given out at round start

**What did you expect to happen**: 
AI being given out at roundstart

**What happened instead**:
Noone got AI, no latejoin possible

**Why is this bad/What are the consequences:**

No Doorknob/AI

Why do you think this is an important issue?

AI is kind of an important role.

**Steps to reproduce the problem/Other information**:
Unknown, seems to happen at roundstart. Really inconsistent, started to happen recently, like a week or so ago.

**Comment by SamHPurp** [comment]
related to #9620 likely

**Comment by variableundefined** [comment]
Are you certain this happened after initialization?

You cannot latejoin as AI or roundstart as AI before the game is initialized.

**Comment by IrkallaEpsilon** [comment]
I clicked the ready button, 60 seconds before roundstart. Wasnt put into AI. No AI on station. No Latejoin option aviable.
