### ISSUE TITLE
Infinite amounts of ductape gags

### ISSUE THREAD

**Issue by DittoMitto** [ParadiseSS13/Paradise#9718]
i seem to get the gag and remove it, repeating. i can fill a room with ductape gags.

if someone gags me or i gag myself with a ductape then press the mask parts over and over again it gives me a gag then i rip it, repeating.

not much of an important issue but people can spam click and fill the station with ductape gags using bare hands

**Comment by DittoMitto** [comment]
the bar is in the process of getting filled with tape.

**Comment by variableundefined** [comment]
1. Please don't report on current round event
2. Please use the proper issue formatting.
