### ISSUE TITLE
Removing your own tape gag spawns an invisible tapegag in hand.

### ISSUE THREAD

**Issue by Squirgenheimer** [ParadiseSS13/Paradise#9743]
**Problem Description**:
When removing a tape gag from your character, the game spawns an old duct tape item onto the turf the player is standing on, but it also creates an invisible ~~old duct tape~~ item in the hand that can be thrown or dropped (upon which ~~it may be visible~~ creates an additional old duct tape item).

**What did you expect to happen**: 
Only item to be created on the ground.

**What happened instead**:
Two were created: one on the ground and an invisible one in the active hand.

**Why is this bad/What are the consequences:**
Players may not notice that they have an invisible item in their hand, causing confusion while trying to do other actions.

**Steps to reproduce the problem**:

1. Pick up tape roll
2. Tape gag yourself by clicking on your player character
3. Switch to empty hand and remove tape gag by clicking on it
4. Observe that interacting with other items with the same hand will behave as if you are holding an item. Try throwing or dropping.

**Possibly related stuff**: Does not occur when stripping someone else of a tape gag (only the one on the ground is spawned).  Tested on 512.1448

**Comment by Squirgenheimer** [comment]
In addition:
Equipping the invisible item to the mask slot and clicking repeatedly afterwards results in the creation of a never ending stream of old duct tape on the ground. Seems to indicate that the invisible item is actually of the tapegag type.

**Comment by Certhic** [comment]
I'll take a look at this

**Comment by Citinited** [comment]
Okay I've tried my best to fix this bug without refactoring `dropped` and `unEquip` and I can confidently say it's been the most irksome process in all my years coding

Sorry but it'll have to wait for another PR
