### ISSUE TITLE
Mining Satchel and Mining Drop Issues

### ISSUE THREAD

**Issue by Moryl** [ParadiseSS13/Paradise#9748]
**Problem Description**:
What is the problem? Mining satchels and Mining Nodes only dropping a single ore.

**What did you expect to happen**: 
Why do you think this is a bug? RNG does not usually roll to give you single ores every time you hit a rock or such.

Also for the satchel? It's not automatically picking things up as normal.

**What happened instead**:
How is what happened different from what you expected?

In less that 24 hours. It went from automatic pick up and randomized ore drops into single drop and no automatic pick up

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Its a deviation from the norm.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue. 

Go mining. While an event is going on. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

I cannot tell anything about the game mode. I just know it was some random SCP event.

Additional info:

https://i.gyazo.com/2b5be0aa5ec8cf20a705f75e8477fecb.gif

https://i.gyazo.com/3a8902fd2f786bd2274f6e6bbdb4dfc9.gif

https://i.gyazo.com/2eff25a19857ef03f7807c7610c5841b.gif

**Comment by SamHPurp** [comment]
Likely the test merge of #9343 caused this, @variableundefined

**Comment by variableundefined** [comment]
Is a test merge issue. The fix has been pushed.
