### ISSUE TITLE
Dead Mining NPCs Look Alive

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#9767]
**Problem Description**:
What is the problem?
After death, the icons of dead mining monsters revert to their living state. They do not move and you can fire over them.

**What did you expect to happen**: 
Why do you think this is a bug?
They should look dead. I cannot tell if they are dead or alive until I've taken a hit or fired a bunch of times.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
This is bad because you cannot tell if that basilisk is alive or dead and will end up taking a hit eventually because of it.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Kill and watch.

![undead basilisk ss13 20181007](https://user-images.githubusercontent.com/12377767/46591893-707a0d00-caad-11e8-973e-fe1f39595743.PNG)

**Comment by KasparoVy** [comment]
This occurs with all mining NPCs from what I can tell.

**Comment by variableundefined** [comment]
Was this broken recently or was it always this way?

**Comment by Agameofscones** [comment]
I've never seen this before, will go test on latest local branch to confirm

**Comment by Crazylemon64** [comment]
I've got a fix baking in the works. Unsure how this was introduced.

**Comment by KasparoVy** [comment]
Thanks guys, yeah I think this just broke today. Like, late today at least after 3PM EST
