### ISSUE TITLE
Magboots

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#977]
Magboots wont stop you from moving when the atmosphere is shifting

**Comment by Fox-McCloud** [comment]
Not a bug. This is how it's meant to function on LINDA.

This may be changed, but it's not a bug.

**Comment by Spacemanspark** [comment]
Ya... This should be changed.

**Comment by fj45** [comment]
Really needs to be changed. That makes mags useless.

**Comment by Robertha89** [comment]
it's technically a Linda oversight

**Comment by ZomgPonies** [comment]
Fixed via #988
