### ISSUE TITLE
Reactive armor not turning off when used

### ISSUE THREAD

**Issue by Quantum-M** [ParadiseSS13/Paradise#9773]
**Problem Description**:
The reactive armor doesn't turn off when it's teleportation function activates., even though the flavor text indicates it turns off.

**What did you expect to happen**: 
For it to shut off, and maybe have a cooldown, after use.

**What happened instead**:
Got teleported, saw that the armor didn't turn off (as in it still had it's active sprite).

**Why is this bad/What are the consequences:**
May create a overpowered item that can be used to teleport around when shot without it having a cooldown

**Steps to reproduce the problem**:
Wear the armor.
Activate armor
Get shot or hit by something.
Examine the armor.
See that it didn't turn off

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing odd, it was a traitor round

![reactivearmor](https://user-images.githubusercontent.com/32376559/46636563-57a14400-cb0d-11e8-9076-2e73a7980b01.PNG)

**Comment by lass9030** [comment]
Haven't looked through the code yet, but it's possible that the text is simply misleading.
In that case, it's a simple edit of the text.
