### ISSUE TITLE
burned matches can be relit by using them on shoes

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#9779]
**Problem Description**:
burned matches can be relit by applying them to your shoes.

**What did you expect to happen**: 
They should not be relit

**What happened instead**:
They started burning as if new. Using it again on the shoes unlits them and makes you able to store them for later use.

**Why is this bad/What are the consequences:**
My immersion! No but this is probably an easy issue to fix.

**Steps to reproduce the problem**:

1. Light a match.
2. Let it burn out or use it on your shoes.
3. Light it again with your shoes.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Any shoes will work.

**Comment by variableundefined** [comment]
Literally unplayable.

I'm shutting down the codebase.

**Comment by Birdtalon** [comment]
https://github.com/ParadiseSS13/Paradise/blob/e2a9b0f84e70c348fae9d1dee366365962c4d5fb/code/modules/clothing/clothing.dm#L385-L400

**Comment by SamHPurp** [comment]
good issue for someone new to Git to fix
