### ISSUE TITLE
You can see static as a non-AI, somehow.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#9781]
![2018-10-09_14-49-24](https://user-images.githubusercontent.com/15747030/46670477-9ea53d00-cbd2-11e8-95fd-8083afa0f679.gif)

EDIT: It wasn't just me seeing that, but both of us had 512.1452 on.

Explain this, atheists.

**Comment by DesolateG** [comment]
@Necaladun  caused these issues before too.. with pipe manifolds.

**Comment by Certhic** [comment]
Might be #4416

**Comment by Sirryan2002** [comment]
Someone needs to verify that this is still happening and hasn't been fixed

**Comment by PacifistDalek** [comment]
Not sure how to reproduce this, and i just dig through 6 months of discord comments containing the word static, and there’s no mention of this bug

**Comment by Sirryan2002** [comment]
can't reproduce issue, new issue report should be opened if a new instance of this bug is discovered.
