### ISSUE TITLE
Runtime in unsorted, 2037.

### ISSUE THREAD

**Issue by lass9030** [ParadiseSS13/Paradise#9786]
Runtime in landmarks.dm and unsorted.dm
Full server log attached.
https://pastebin.com/Myg8gibv

EDIT:
This happened later in the same round, might be related.
https://pastebin.com/EbZntBgT

I have tested this, it only seems happens on spacehotel.dmm.

**Comment by Birdtalon** [comment]
Runtime in landmarks.dm,279 is a duplicate of #9735

**Comment by Birdtalon** [comment]
Duplicate of #9735

**Comment by lass9030** [comment]
The issue in unsorted.dm might also be related to #9736.

**Comment by SamHPurp** [comment]
These are dupes and can be closed
