### ISSUE TITLE
Remote Ambulance Siren

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#9787]
**Problem Description**:
After dismounting the Ambulance, I could still turn its Siren on & off from a distance.

**What did you expect to happen**: 
I only expected to turn the Siren on/off while on the Ambulance.

**What happened instead**:
I managed to turn the Siren on/off while in a different room.

**Why is this bad/What are the consequences:**
Could allow someone to get on the Ambulance once and constantly turn its Siren on/off for the rest of the round.

**Steps to reproduce the problem**:
1. Get on Ambulance (with keys?).
2. Get off Ambulance.
3. Move away from Ambulance.
4. Turn Siren on/off using hotbar in upper-left corner.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No.

**Comment by Ty-Omaha** [comment]
This used to not do that, weird
