### ISSUE TITLE
Borers can Stun/Dominate post mortem

### ISSUE THREAD

**Issue by IrkallaEpsilon** [ParadiseSS13/Paradise#9791]
**Problem Description**:
Borers which are in the targetting selection for "Dominate Victim"/Stun are able to stun their victims post mortem should they not stun them prior to death and can repeat this without any delay forever unless they reconnect to the server.

**What did you expect to happen**: 
Not being able to stun people post mortem as a borer.

**What happened instead**:
I was able to Stun Isthel and Brooke a while back remotely. I dont think I have reported this issue yet, I thought I did, but I am unable to find it on here nor any fix for it. So easiest explanation is I forgot to submit the issue.

**Why is this bad/What are the consequences:**
It basicly allows people to grief others.

**Steps to reproduce the problem**:
Be a borer. Get close to 2 or more people adjacent to eachother. Select the stun ability/Dominate victim. Targetting screen opens up. Get killed in targetting screen. You can still stun people. And that can be done forever till you reconnect to the server.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing else. Issue should have been reported about 3-4 weeks ago, But I forgot because... I forgot.

**Comment by Citinited** [comment]
This probably means you can line up multiple dominates / stuns on any number of people.

I hate the `input` proc sometimes :smile:
