### ISSUE TITLE
Tile rendered as a black square

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#9799]
![dreamseeker_2018-10-09_22-05-07](https://user-images.githubusercontent.com/25027759/46701725-996ae100-cc18-11e8-9957-783ea8485ebc.png)

Quite hard to see here but the tile next to my character is just completely black with no detail.

**Comment by SamHPurp** [comment]
@Birdtalon this can be closed. My PR thats already up fixes this. #9790

**Comment by Birdtalon** [comment]
👍 gotcha
