### ISSUE TITLE
Sand in wild west gateway is completely black

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#9802]
**Problem Description**:
The sand tiles are completely black

**What did you expect to happen**: 
I don't think they are supposed to look like that.

**What happened instead**:
I see:
![untitled](https://user-images.githubusercontent.com/32099540/46742864-2e68eb00-cca8-11e8-990f-6ce77cb1a0da.png)

**Why is this bad/What are the consequences:**
Looks pretty damn ugly

**Steps to reproduce the problem**:
I guess take a look at the wild west gateway? I don't know.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I joined as an observer like 2 hours into the round and took a look as a ghost.

**Comment by variableundefined** [comment]
WAD
