### ISSUE TITLE
Random Death Mid Abductor Surgery

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#9823]
**Problem Description**:
Pretty much right what it says on the tin. I was abducted while passed out drunk alongside Squishy. They begin the surgery though I die before they start removing my organs. I'm not sure how, at all really. I had nearly perfect health but I just...died. Squishy was surgeried just fine and lived on until the round ended. So I'm at a loss as to what happened. For reference; she was drunk and passed out too, so I don't think that's why.

**What did you expect to happen**: 
I expected to not die on the operating table for no reason.

**What happened instead**:
I died.

**Why is this bad/What are the consequences:**
Obviously problematic to die to an abductor and be spat out in a random area when you shouldn't of died. Unsure if it's related to slimes only or if it's an RNG bug altogether.

**Steps to reproduce the problem**:
1. Be drunk.
2. Pass out.
3. Get abducted.
4. Die mid surgery.

Honestly not sure how to perfectly reproduce it or if that's relevant to the bug happening at all, but, there's the info.

https://i.gyazo.com/9b076c9111db0c4a3ae65329afbba384.png

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Drinking and passing out.

**Comment by SamHPurp** [comment]
Going to need more info if we're going to be able to track this down. Any admin on at that time able to shine a light?

**Comment by alex-gh** [comment]
It is a long shot but: Could it have something to do with wound infections?
I know you need over 1000 germ_level for necrosis like that, but having a lot of people close by during surgery could quickly add up.
