### ISSUE TITLE
Voice analyzer activates when it should not

### ISSUE THREAD

**Issue by FlimFlamm** [ParadiseSS13/Paradise#9833]
**Problem Description**:
Voice analysers activate when they hear certain sounds other than the message they're supposed to check for.

**What did you expect to happen**: 
For the voice analyser/igniter rig to only trigger when it hears the correct pass-phrase.

**What happened instead**:
It activated when it heard an excited floorbot.

**Why is this bad/What are the consequences:**
Someone blew up the bridge this way while bringing bombs to mining.

**Steps to reproduce the problem**:

- Make a voice analyzer activated igniter assembly, 
- Give it a unique pass phrase
- Stand around floor-bots until they beep excitedly.

When i was testing this, at first the floor-bots did not cause it to activate, but i placed it on the ground, left and came back, and it triggered every-time. I believe this also happens with other sounds, such as mouses speaking.

**Comment by ID404-NotFound** [comment]
it will also activate on any emote, such as *snap or *sneeze, even though you set it to a word or phrase.

**Comment by Allfd** [comment]
Thats kinda odd.

https://github.com/ParadiseSS13/Paradise/blob/613587fb9f207ca15bae303850c5af8de1969f67/code/modules/assembly/voice.dm#L25-L37

It should only ever pulse if `else if(findtext(msg, recorded) && type == recorded_type)` is true

I wonder if either its not getting set, or somehow resets itself.

**Comment by FlimFlamm** [comment]
> I wonder if either its not getting set, or somehow resets itself.

I did some quick testing. The message is retained, but emotes and some other messages activate it anyway.
