### ISSUE TITLE
Changelings Stuck Unconscious After Regeneration.

### ISSUE THREAD

**Issue by Pckables** [ParadiseSS13/Paradise#9835]
**Problem**:
After a changeling recovers from Regenerative Stasis, they are stuck unconscious, unable to wake up, even after shaken.

**Why is this bad/What are the consequences:**
Changelings can't regenerate without admin intervention, breaking the gamemode.

**Steps to reproduce the problem**:
Enter Regenerative Stasis as a cling, and then successfully regenerate. You will be stuck unconscious.

**Possibly related stuff**: 
Both times I observed this bug, it happened on human changelings. Sollessa experienced this herself, and could not wake even after 3 regenerations.
Unsure if it's a consistent problem or one that happens occasionally, but it's a round-ruining bug.

**Comment by Birdtalon** [comment]
#9221 again I imagine.
