### ISSUE TITLE
Borg cannot be repaired properly - Debilitating bug

### ISSUE THREAD

**Issue by SilvernKell** [ParadiseSS13/Paradise#9836]
**Problem Description**:
Borg becomes damaged and needs new components, upon repairs, Self Diagnosis reads nominal but the hud indicator still reads as poor/bad and system integrity still reads as critical (-21% etc)

**What did you expect to happen**: 
I expect the borg to become repaired and able to use modules 2 and 3 again without error

**What happened instead**:
Modules 2 and 3 were unusable

**Why is this bad/What are the consequences:**
Makes it very difficult to play, and if all modules were offline, literally impossible

**Steps to reproduce the problem**:
Get damaged badly enough to need replacement components

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Admin tried to fix me in multiple ways. Admin respawned me and I remained damaged. Module reset was tried, and the bug remained. Relog did not fix it, Stable or Beta version client did not fix it.
Admin had to spawn in a new borg chassis and move me into it.

**Comment by Birdtalon** [comment]
Which admin?

**Comment by SilvernKell** [comment]
Admin was Normalyman.

**Comment by Ty-Omaha** [comment]
This has been a bug for a while

**Comment by Taaketa** [comment]
Yeah the only way to fix this is a new borg body. Just ripping out the MMI and resetting chest and head. Will count as a new body.

I suspect the reason it occurs is attempting to repair with some but not all damaged modules removed.

**Comment by SilvernKell** [comment]
According to the self-diagnosis, all modules were undamaged and replaced/repaired, so no damaged parts were left.
