### ISSUE TITLE
Newscaster photo assets not transfering to user cache fast enough

### ISSUE THREAD

**Issue by FlimFlamm** [ParadiseSS13/Paradise#9840]
**Problem Description**:
When viewing a new newscaster story, sometimes the photos do not populate.

**What did you expect to happen**: 
All the photos to populate

**What happened instead**:
only one or none of the photos populated

**Why is this bad/What are the consequences:**
Causes frustration and dis-incentivizes the reading and making of news stories.

**Steps to reproduce the problem**:
Have a news feed channel with several stories with photos. Delete the photos from your user cache (tmp_photo0 -tmp_photoN), and then reopen the news feed channel.

**The Cause**

The exact cause of this bug is due to the nature of the nanoUI. The newscaster.dm code transfers photo assets to the user cache whenever they are viewing a news feed channel. The moment the feed channel is opened, the assets begin transferring, but the newscaster.tmpl file (the nanoUI template) starts composing the UI before all the photo assets are done transferring, and so only the first one, or none, will be visible. Exiting and immediately re-entering the same news feed causes all the photos to render properly (because they have had time to transfer).

I watched the assets trickle into my byond cache when loading a news feed channel, so I'm positive this is the source of the problem. I'm opening this issue because hoping someone can suggest the ideal kind of fix (I'm unfamiliar with asset DM management). One solution would be to force a delay on the loading of the nanoUI, and another option would be to store the assets globally so that nobody has to re-cache them each time they view a feed channel. Is that even possible?

**Comment by Kyep** [comment]
@dearmochi 's TGUI newscasters should fix this.
