### ISSUE TITLE
You can drag people when you are dead

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#9848]
**Problem Description**:
What is the problem?
You can drag people when you are dead and in your body, if you click fast enough. Also dead people don't get fog/limited vision.

**What did you expect to happen**: 
Why do you think this is a bug?
I don't think zombie rising is supposed to happen, or start happening with being able to drag objects while dead.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Breaking immersion, ghotst should not be able to interact with living that way.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1.Die
2.Enter body
3. Have someone dragging your dead body
4. While being dragged, spam click control + lmb on draggable object you are passing.
5. Object might get dragged by you for 1 tile, before you losing grab of it.

[My ic name is Bo'Ndugo]
![rising of the dead](https://user-images.githubusercontent.com/35972878/46917972-a5fe8900-cfcc-11e8-88c3-0c1e9a8a9360.png)

**Comment by Taaketa** [comment]
Has your computer got a Trump filter? Cos that screenshot is super orange.

**Comment by Deelite34** [comment]
It's flux, it removes blue colours from screen, resulting in warm colours, which are sooo much nicer and better to look in evening, when it's dark.

**Comment by craftxbox** [comment]
f.lux has some crazy code that normally PREVENTS screenshots from capturing the filter.
