### ISSUE TITLE
Mime can Cult Commune without breaking Vow of Silence

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#9861]
**Problem Description**:
Mimes can can commune with the cult without breaking their vow of silence, making it a silent, safe way to talk with the cult.

**What did you expect to happen**: 
As a Mime, you're unable to talk or make most noise with your Vow of Silence intact. Thus, I expected to not be able to commune.

**What happened instead**:
I was able to commune without any whispering from my character, but the message still appeared in cult chat.

**Why is this bad/What are the consequences:**
While I'm not sure if it's important, I do believe that the cult whispers are one of the good ways to identify a cultist, and this could be a workaround. Additionally, this could work for mute characters, though I'm not sure.

**Steps to reproduce the problem**:
1. Be Mime Cultist
2. Commune
3. Watch your message appear silently!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing I can think of.

**Comment by Taaketa** [comment]
I feel this fits.

**Comment by Breenland** [comment]
Either way! It lets the Mime do cult stuff and also still be a mime, or they have to break their silence to talk with the cult. I found it good fun on the round I learned it worked. What I'm not sure about, is if you have the Mute disability, does it have the same effect?

**Comment by davidchan13** [comment]
Proof that Mimes are truly evil and emissaries of a eldritch horrors from beyond our realm. /s

**Comment by taukausanake** [comment]
More reason that we need clown and mime cults

**Comment by Breenland** [comment]
> @Breenland Yeah it should work the same with the mute disability as the whisper shiz will be stopped by rhe mute effect in saycode

As in, people with the Mute disability won't be able to commune, but mimes still will?

**Comment by Shockpoint** [comment]
@Breenland It affects anyone who has their mute block enabled for any reason, silencing any whispering of such.

**Comment by Aurorablade** [comment]
This isn't really a bug but a balance concern.

**Comment by variableundefined** [comment]
One should create an issue for the communing not showing for mute people instead
