### ISSUE TITLE
Mob spawners are broken

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#9863]
**Problem Description**:
@Aurorablade 's PR to add mob spawners is borked. There are several instances of these already existing in the maps like on Wild West. You can click these, and attempt to spawn in. See images:

![image](https://user-images.githubusercontent.com/7415122/46980071-61a5e280-d0cb-11e8-8ac4-25fa3be4d733.png)

![image](https://user-images.githubusercontent.com/7415122/46980076-666a9680-d0cb-11e8-98be-7894d3262379.png)

![image](https://user-images.githubusercontent.com/7415122/46980087-6b2f4a80-d0cb-11e8-95ae-751944dca51d.png)

Also bizarrely appears to have added a ^ to my name in deadchat.... no idea.

**What did you expect to happen**: 
This is clearly not the intended behaviour. This also showed up superfluously on the list of playable mob spawners.

**Steps to reproduce the problem**:
Go to WIld West. Go to kitchen. Click remains.

Go to doughnut room. Find bizarre doctor flooring, including remains. Click remains.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

This'll be from @Aurorablade 's PR I suspect. #8211

**Comment by Aurorablade** [comment]
It was most likely a mapping type error, cuase you see any toher maps this occurs on?

**Comment by SamHPurp** [comment]
@Aurorablade are these not supposed to be mapped? Because these exist are remains. Then you click on them. You become a standing up corpse. Surely thats not intentional?

**Comment by Aurorablade** [comment]
By mapping type error it means, 'I put a player spawner landmark where a corpse spawner landmark should be'

**Comment by SamHPurp** [comment]
Ah I see, @Aurorablade https://github.com/ParadiseSS13/Paradise/blame/master/_maps/map_files/RandomZLevels/wildwest.dmm#L37

Hm

**Comment by Aurorablade** [comment]
No that definatly should be a dead miner marks spawning there. Can you reproduce it on two seperate instances of the server running?

**Comment by SamHPurp** [comment]
Yeah this happens everytime, both on my instance and the live paradise server.

**Comment by SamHPurp** [comment]
I only caught it because I'm working on adding a Ghost Role Mob Spawner menu (similar to TGs)... and these popped up. Did some investigating, saw this happen. Did some investigating on a clean master branch. Still there. Tried it on the live server. And yep.

**Comment by FalseIncarnate** [comment]
Appears the mob_name var isn't set on most of the spawner definitions. This var is supposed to be pulled for that dialog box ([code](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/awaymissions/corpse.dm#L43)), and initializes as a blank string (no default assignment like "mob").

Should be an easy fix, though it will need to be done for most of the spawner types declared. Probably best to check that other vars are being properly declared/handled on the spawners too.

I'll fix this after dinner.

**Comment by Aurorablade** [comment]
Well there are WORSE things to be left undecalred..

**Comment by SamHPurp** [comment]
A separate issue, but yes good to be solved too.
