### ISSUE TITLE
Autolathe Cable Coil Queue Issue

### ISSUE THREAD

**Issue by Breenland** [ParadiseSS13/Paradise#9865]
**Problem Description**:
Creating stacks of cable coil results in an odd name generated in the autolathe queue.

**What did you expect to happen**: 
It should say 'Cable coil (x30)'.

**What happened instead**:
It says 'Cable Coil (xvalue.multiplier)

**Why is this bad/What are the consequences:**
It's not really, but it looks really dumb.

**Steps to reproduce the problem**:
1. Find autolathe (possibly hacked)
2. Print 30x cable coils (it might do it with 5x too)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a hacked autolathe, but I don't think that has any bearing on the issue.
![2018_10_15_18_15_31_](https://user-images.githubusercontent.com/38596550/46987911-d113d600-d0bb-11e8-83f5-1edb5408a47e.png)

**Comment by farie82** [comment]
Fixed by the PR referenced above
