### ISSUE TITLE
Agreeable seizure inducing glasses

### ISSUE THREAD

**Issue by exeroxide** [ParadiseSS13/Paradise#9868]
**Problem Description**:
What is the problem?
Toggling off noir glasses causes bad side effects
**What did you expect to happen**: 
Why do you think this is a bug?
the color inst what it suppose to be
**What happened instead**:
How is what happened different from what you expected?
i expected the color to become normal when i toggle the agreeable glasses off
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It induces seizures and makes it unplayable without relaunching

 the game
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Put on agreeable glasses
toggle noir on
toggle it off
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Secret heard something about a blob

![capture 2](https://user-images.githubusercontent.com/44187496/46993441-10462500-d0c4-11e8-9103-c57e6b2feaf4.PNG)

![capture](https://user-images.githubusercontent.com/44187496/46993442-12a87f00-d0c4-11e8-9bfa-fc1264131402.PNG)

**Comment by alex-gh** [comment]
Could reproduce, but only on 512, 511 works fine.

**Comment by alex-gh** [comment]
Fixed in the latest beta.
