### ISSUE TITLE
Borgs can be stunned indefinitely.

### ISSUE THREAD

**Issue by alex-gh** [ParadiseSS13/Paradise#9871]
**Problem Description**:
Borgs can be stunned indefinitely, for example when fighting Goliaths.

**What did you expect to happen**: 
Be stunned, be unstunned after a short while. 

**What happened instead**:
Get stunned forever.

**Why is this bad/What are the consequences:**
Simple stuns remove you from the game, potentially forever.

**Steps to reproduce the problem**:
1. Be mining borg.
2. Go fight a goliath.
3. Get stunned.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 

Getting hit gets you unstunned as does aghosting and coming back.

**Comment by FlattestGuitar** [comment]
You mean to say that stuns never wear off for borgs?

**Comment by alex-gh** [comment]
At least Goliath stuns never do. Also I know of a borg who got stunned indefinitely by a sling.

**Comment by alex-gh** [comment]
No idea. I only have second hand info on the borg. It would make sense for these to be related.

**Comment by farie82** [comment]
Confirmed. I've tested this with both the goliath and the sling unearthly_screech. Both caused the borg to shutdown for good. It seems that the borg goes unconcious according to the logging. After 2 screeches and after 1 goliath stun.
