### ISSUE TITLE
Somehow becoming monkey and getting genes, then getting genes clean with mutadone removes your sight forever

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#9872]
**Problem Description**:
What is the problem?
I got genes from genetist:
blindness, xray, clown speech, feeling buff, monkification.
I could see everything around me with xray gene, but could not examine stuff due to blindness gene.
I got broken bone, got surgery, I went to sleep so it could be performed.
When I woke up, I was fully blind.
I went to medbay, ate mutadone. I lost all my gene mutations and got unmonkified but still was blind.
According to ruum(not sure whats ckey), I lost sight vv

**What did you expect to happen**: 
Why do you think this is a bug?
You should never lose variable that lets you have sight, or do anything else.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Gamebreaking bug, even reseting my guy didn't fix the issue.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. I was tarajan
2. I got genes: blindness, buff, no breathe, swiftness, x-ray, sober, clown speech, monkification
I could see everything with x-ray, but could not examine anything as if I was blind.
3. I went to sleep for surgery
4. When I woke up, I was fully blind
5 Mutadone removed all genes blindness gene too, but I was still fully blind.
6. According to ruum I lost sight vv.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

![sadasdasd](https://user-images.githubusercontent.com/35972878/47019136-a460cc80-d156-11e8-8f7d-c912a6ec4387.png)

**Comment by IrkallaEpsilon** [comment]
The fact that blindness and Xray Vision works by giving you Xray Vision to see through walls but no examine option is kind of a bug on its own I think.
