### ISSUE TITLE
Tajaran detective with Noir Glasses effect

### ISSUE THREAD

**Issue by JustinHornsby** [ParadiseSS13/Paradise#9873]
**Problem Description**:
playing Paradise Station. started as detective and put on Noir glasses, with Noir effect.
once removed (near southern maintenance) colors return, but then become super bright black and white color. I also had seclite on.

**What did you expect to happen**: 
my eye sshould return to normal.

**What happened instead**:
everything is noir, except super bright.

**Why is this bad/What are the consequences:**
cant see colors. i can either choose Noir, or Super Bright Noir, even if glasses removed.

**Steps to reproduce the problem**:
played as Tajaran detective. put on noir glasses. enabled noir effect. equipped seclite. moved to southern maintence and turned off noir effect (seclight light enabled) everything still black and white, but super bright now.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
was on secret gamemode.

**Comment by Ty-Omaha** [comment]
#9868
