### ISSUE TITLE
Fluff Item not spawning

### ISSUE THREAD

**Issue by ScratKnapp** [ParadiseSS13/Paradise#9874]
Hello,
I'm not certain if this is the right place but I'd rather not just bug Neca about this and see if anyone else can see what might be the issue.

I donated for a fluff item around 2-3 years ago. It was an acoustic guitar, and it worked for the longest time. After a hiatus, I returned and noticed the character I got it for (S.A.M.) doesn't spawn with it anymore.

I spoke with Nec and eventually dove into the code myself to figure out why. It turns out all instrument items were moved into their own folder, and thus the database entry that would have it spawn on me pointed to a nonexistent file. Helping him a bit, I gave the path to the new instruments folder and also decided to have it changed to the electric guitar instead. However even now, it simply does not spawn on me. 

What could be the cause of this issue?

**Comment by taukausanake** [comment]
It could be that the server or SQL hasn't been updated yet. When did you and Neca get around to this? That might be the case

**Comment by ScratKnapp** [comment]
the 29th.

**Comment by Birdtalon** [comment]
It'll likely be a database issue unrelated to the code and therefore nothing we can help with. You'll have to contact the heads (or community manager?)

**Comment by variableundefined** [comment]
Please contact a maintainer directly on discord with your ckey.

**Comment by tigercat2000** [comment]
@ScratKnapp Hey, I fixed it for ya. Do what Ansari says anyways though, it's been a long time 😛
