### ISSUE TITLE
Held Medistan Flag Issue

### ISSUE THREAD

**Issue by ThePuppay** [ParadiseSS13/Paradise#9876]
**Problem Description**: Medistan Flag Issue
What is the problem?
When held in the right hand and facing North, Medistan Flag appears to use its facing East sprite.
**What did you expect to happen**: My character to hold a flag normally
Why do you think this is a bug?
Because the flag clips through my body sprite.
**What happened instead**: My character has an arm inbetween his crotch, aswell as having a random hole through his backpack.  This is how he was able to hold the flag.
How is what happened different from what you expected?
I expected it to not clip through my character.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It probably isn't game changing, but it is an aesthetic issue.
**Steps to reproduce the problem**: Face North with Medistan Flag in Right Hand.
The most important section. Review everything you did leading up to causing the issue.
I picked up the Medistan Flag and started to head out of Medbay, but it seemed to clip through my character's sprite.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Shouldn't be necessarily important, but the area was Medbay Reception.

**Comment by SamHPurp** [comment]
Real easy fix if its as it sounds.

**Comment by lass9030** [comment]
Issue seems fixed, this can be closed.
