### ISSUE TITLE
Borg module changes get reported incorrectly to the AI

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#9877]
**Problem Description**:
A borg switched to janitor but the game tells me he loaded the security module
![untitled](https://user-images.githubusercontent.com/32099540/47057277-351fc280-d1c0-11e8-9d4a-5098505645e1.png)

**What did you expect to happen**: 
to be informed correctly.

**What happened instead**:
It said he loaded a module he didn't load

**Why is this bad/What are the consequences:**
You might yell at your borg for picking a useless module he didn't actually pick. You have to manually check what module your borg loaded.

**Steps to reproduce the problem**:
Be AI
Have borg pick module
???
profit

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was AI, obviously. Can't think of anything else relevant.

**Comment by Kyep** [comment]
Attempted to reproduce this, but could not.
Choosing a borg module as a newly-spawned borg produces a message to the AI about the rename, but NOT module selection. The rename message is correct.
Resetting a borg and then having it pick a new module does indeed give the 'chosen module' message to the linked AI, but the message appeared correct when I tested it (on live).

**Comment by alex-gh** [comment]
Tried this as well, could not reproduce.

**Comment by TDSSS** [comment]
Seems to not always happen, but I don't know what the borg did special that one time. Maybe picking a module and then cancelling? Next time I see it I'll ask the borg if he did anything unusual.

**Comment by variableundefined** [comment]
Cannot reproduce, closing
