### ISSUE TITLE
effect_system/spark_spread runtime log messages

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#9880]
**Problem Description**:
[2018-10-17T01:08:20] Runtime in unsorted.dm,2034: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait
   proc name: stack trace (/proc/stack_trace)
   src: null
   call stack:
   stack trace("addtimer called with a callbac...")
   addtimer(/datum/callback (/datum/callback), 20, 0)
   /datum/effect_system/spark_spr... (/datum/effect_system/spark_spread): generate effect()
   ImmediateInvokeAsync(/datum/effect_system/spark_spr... (/datum/effect_system/spark_spread), /datum/effect_system/proc/gene... (/datum/effect_system/proc/generate_effect))

**What did you expect to happen**: 
Sparks to not generate runtimes.

**What happened instead**:
Certain sparks generate a stream of runtimes in the log.

**Why is this bad/What are the consequences:**
Runtimes in the log.

**Steps to reproduce the problem**:
Unable to find a consistent reproduction for this so far. Directly spawning sparks does not seem to cause it, but something is causing lots of them.

**Comment by Fox-McCloud** [comment]
this isn't a runtime so much as a logged warning for future use, to be honest.

**Comment by Kyep** [comment]
I assumed we'd want this fixed, since (1) it puts messages in the runtime log, and (2) it does warn that in future such timers may no longer work.

**Comment by Fox-McCloud** [comment]
It's for future reference so we can find all the places where this is *potentially* problematic if/when the timer system is ever changed. It's not an *actual* runtime.
