### ISSUE TITLE
Pipes disappear when fastened without a connecting pipe.

### ISSUE THREAD

**Issue by IAmBigCoat** [ParadiseSS13/Paradise#989]
Straight pipes and Bent Pipes (of regular, scrubber, supply, and insulated flavor,) Universal Pipe Adapters, and heat exchange Junction Fittings will disappear when fastened without a proper connecting pipe.

Manifolds and 4-way manifolds display "There's nothing to connect this pipe section to!" which I assume is working as intended.

If I had to guess, I'd say it's a problem with the switch statement [here](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/pipe/construction.dm#L416), because the sound still plays, and the notification still runs

Also Scrubber and Supply pipe caps don't have the same offset as their other pipes, so they kinda look silly.

**Comment by tigercat2000** [comment]
This has been a bug for absolute ages, through multiple overhauls of the atmos system. Pipenet doesn't get along with non-connected pipes and deletes them.

The bug here is that someone disabled the code that prevent them being wrenched down at all.

**Comment by Robertha89** [comment]
there is also time this happens when there are connected pipes, making fixing pipes a paint in the pantalones.

**Comment by tigercat2000** [comment]
@Robertha89 I should have specified- Pipenet doesn't get along with any amount of pipes that are not connected to at least one machine like a vent, mixer, or others.

**Comment by Robertha89** [comment]
I was setting up atmospherics in the old bar, and needed to pipe into library to get the vent pipe there as only scrubbers passes in maint, so i set up a went and set up pipes and it went all good untill i was gonna cross the old scrubber pipes, after removing the pipe i was unable to make it go across the tile even when it was connected to several vents. I will see later today if i can replicate this.

**Comment by IAmBigCoat** [comment]
[Fixed it!](https://github.com/ParadiseSS13/Paradise/pull/1068)
