### ISSUE TITLE
Cyborg extinguisher

### ISSUE THREAD

**Issue by BoiCalledFyrd** [ParadiseSS13/Paradise#9901]
**Problem Description**:
So I was a medical borg and someone (gee I wonder who it was) released a virus that caused people to combust every now and then. I put people out for a while until I ran out and discovered that there is no way to refill the extinguisher.

**What did you expect to happen**: 
Most things refill at the cyborg recharge station, such as all the medical supplies.

The extinguisher seems to be the exception.

**Why is this bad/What are the consequences:**
I kinda just had to twiddle my borgy thumbs while people burned to death.

**Steps to reproduce the problem**:
I wasn't doing anything out of the ordinary, again, just running around medbay trying to put people out.

**Comment by alexkar598** [comment]
Slap them in a cryo cell next time,it extinguishes people. This is still a bug tho

**Comment by BoiCalledFyrd** [comment]
Okay noted about the cryo thing, but also I didn’t think a fire extinguisher would use water but I’ll try that next time I guess.
