### ISSUE TITLE
Reagents do not scale in grenades.

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#9912]
**Problem Description**:
Reagents do not scale in grenades. For example, advanced grenades use a small amount of reagent, but will give the full effect reach time.

**What did you expect to happen**: 
It to give a tiny effect and scale on reagents used.

**What happened instead**:
It gives the full effect of reagents. Dark matter grenades are a good show of this.

**Why is this bad/What are the consequences:**
Can be completely broken and make extremely overpowered, nigh uncounterable grenade combinations that can fit in your backpack.

**Steps to reproduce the problem**:
Make advanced grenade
Add voice activator
Make advanced grenade filled with dark matter.
Use it on whim.
Full effect each time. You can fit like 8 of these in your bag.

**Comment by alex-gh** [comment]
To clarify: The issue is not that reagents do not scale in grenades, but that some reagents do not scale: period.

**Comment by warior4356** [comment]
As alex-gh stated this is not a bug, this is, in fact, working as intended. Perhaps it is a balance issue but it is NOT a bug. Some reagents and reactions don't scale based on volume.
