### ISSUE TITLE
IPCs are job-banned from becoming borgs

### ISSUE THREAD

**Issue by Sylvaratayn** [ParadiseSS13/Paradise#9918]
**Problem Description**:
IPCs are job-banned from being borged and posibrains cannot be fit into Cyborg chassis.

https://i.imgur.com/2erw0Zc.png

**Comment by tigercat2000** [comment]
Are you sure you aren't just job-banned yourself? Could you give us more details around what exactly makes you believe this is a problem, or gives any context whatsoever to your screenshot of the code?

**Comment by variableundefined** [comment]
I am certain you're jobbanned yourself instead.
