### ISSUE TITLE
Still Can't Rejuv Head Exploded Cases

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#992]
Rejuvinating someone who's head has exploded will still wind up with the person dying instantly after the rejuv.

Their head rejuvinates properly and their brain is moved back into the head, but the they still die.

This seems to be a bug relating to the brain_op stages not being reset to 0 and staying at 4.

**Comment by Robertha89** [comment]
Rejuv needs a bit of a re-work, im not sure if it fixes all body damage vars, like being brained, reset body decomp stage, and properly restore icons, and i think there is an issue if you rejuv an ipc, and their organs are no longer robotic, so snowflake code for organ check, what organs they should have, also maybe checking the players personell settings regarding robotic legs and organs. Not sure how much of this is fixed or not, as i last played around with rejuv half a year ago.
