### ISSUE TITLE
Atropine not being accepted in the Medical Hypospray

### ISSUE THREAD

**Issue by RunkoParadise** [ParadiseSS13/Paradise#9936]
**Problem Description**:
Atropine being classified as a harmful substance in the Medical Hypospray

**What did you expect to happen**: 
Atropine should be a valid substance in the Medical Hypospray, its effects are very useful when in the field as a paramedic

**What happened instead**:
The Medical Hypospray immediately destroyed the substance and said that "a harmful substance has been detected and immediately purged"

**Why is this bad/What are the consequences:**
Increases the effectiveness of the Medical Hypospray

**Steps to reproduce the problem**:
Use a beaker with Atropine in it on a Medical Hypospray.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No

**Comment by Fox-McCloud** [comment]
@Pckables nailed it. This isn't a bug.
