### ISSUE TITLE
Can't target hands with a syringe

### ISSUE THREAD

**Issue by Edern76** [ParadiseSS13/Paradise#994]
If you click on yourself with a syringe in draw mode while targeting your hand, the game will think you're targeting your body. However, it works correctly if you target your head.

So, you have to either put your headgear or your clothes off if you want to draw blood from yourself, you can't simply remove your gloves.

I haven't tried with legs/feet, but I think it's the same.

Not high priority at all, but still a bit annoying.

**Comment by Fox-McCloud** [comment]
If you're referring to "there is no exposed flesh on", this is because just about anything that has THICKMATERIAL covers the entire body.
