### ISSUE TITLE
Semicolon title on paper causes all tabs on the interface to dissapear.

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#9944]
**Problem Description**:
When a semicolon is used to title/name a piece of paper, it causes all tabs to disapear.

**What did you expect to happen**: 
Causes all of the tabs (Status, Examine, IC OOC etc) to dissapear.

**Why is this bad/What are the consequences:**
Removes the ability to preform 

**Steps to reproduce the problem**:
Right clicking on a piece of paper, then renaming it ; will cause it to happen.

**Comment by Certhic** [comment]
Seems sanitize doesn't catch everything

var/n_name = sanitize(copytext(input(usr, "What would you like to label the paper?", "Paper Labelling", name) as text, 1, MAX_MESSAGE_LEN))

**Comment by charliehershberger** [comment]
Is sanitize our function that we can add semi-colon removal to, or is that not under our control?
