### ISSUE TITLE
Missing pipe sprite

### ISSUE THREAD

**Issue by Certhic** [ParadiseSS13/Paradise#9946]
**Problem Description**:
'exposed00' is missing from icons/atmos/pipes.dmi. This is the sprite used for when a wrenched down pipe is not connected to other pipes. 

**Why is this bad/What are the consequences:**
This causes invisible pipes

**Steps to reproduce the problem**:
1) Create a regular straight pipe with a rapid pipe dispenser
2) Wrench it down without connecting it to any other pipe

**Comment by SamHPurp** [comment]
I suspect the RPD is assigning the wrong icon, rather than the correct one being missing.  But I haven't checked this myself yet.

**Comment by Certhic** [comment]
The RPD is not required. You can also use the regular pipe dispenser, or just rip one out from the station. 

Any icon set by any tool gets ignored.  The atmos pipes get their icon from an icon cache
/datum/pipe_icon_manager/

**Comment by Twinmold93** [comment]
I investigated a little bit and this is the same issue I was running into, paired with the fact the dispenser would not allow output of more than one pipe at all.
