### ISSUE TITLE
Missing legs = permastun

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#995]
this really needs to get fixed, yeah sure it's somewhat realistic, but this is a game, and if losing legs as an antag as a deathsentence that it's stupid and needs to be fixed, i mean seriously?

This has been reported before, and you should be able to crawl even without legs. 

Please fix.

**Comment by MrBauer24** [comment]
This one may take a little while..I will see what I can do though.

**Comment by Plotron** [comment]
Mostly a problem for handicapped people in wheelchairs. It's very easy to grief, abuse and generally be a jerk.
No more chasing around people, trying to find your wheelchair - one unbuckle and you're on the ground, not being able to move an inch.

**Comment by Robertha89** [comment]
![image](https://cloud.githubusercontent.com/assets/7663878/9701940/2a982064-5446-11e5-8f88-f57c861a5558.png)
This is still an issue, and lossing a single foot should not permanently stun you, high priority this please.

**Comment by Robertha89** [comment]
So I found the source of this in https://github.com/ParadiseSS13/Paradise/blob/6a2c7a82ff97613cfd579ebfa9793b8031916a95/code/modules/mob/living/carbon/human/human_organs.dm#L92
No clue how to fix this yet.

**Comment by TheDZD** [comment]
@Robertha89 Probably by nuking all or some of [this](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/human_organs.dm#L73-L78) section.

**Comment by tigercat2000** [comment]
@TheDZD that would also break slowdown based on hurt limbs, stance_damage isn't exclusive to that

Only way to do it would be [touching this](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/human_organs.dm#L92-L97) and either increasing the threshold or removing that part

**Comment by TheDZD** [comment]
@tigercat2000 Removing the lines 75-76 in specific, or reducing their stance damage to 1 will prevent permastunning when you are missing both legs.

**Comment by Robertha89** [comment]
Currently, the only thing we need to do is make sure can_stand = 0 if 2 or greater instead of this collapse bs. Sadly, I do not know how to define a mob's var like that in a var withing a var within a part of the organ. or something like that.

But TL;DR can_stand = 0 and can_move = 1 would fix it all.

**Comment by tigercat2000** [comment]
@TheDZD It would also mean they suffer literally no slowdown from missing a god damn leg.

**Comment by Robertha89** [comment]
Also, what tiger said, the code itself works perfectly, but how it make it so you can't stand is done kinda bad, since we got var for standing.

**Comment by tigercat2000** [comment]
@Robertha89 It Weaken(5)'s you if you have more than or equal to 4 stance damage; One missing leg therefore means it constantly Weaken(5)'s you every single Life() tick, which is essentially a permastun.

**Comment by Robertha89** [comment]
Yeah, oddly enough the weaken runs outside the check if standing var, lets see what happens if i put it inside.

**Comment by Robertha89** [comment]
As expected, it makes you stand up again when it ends, and then restarts the check.

**Comment by tigercat2000** [comment]
@Robertha89 If you want to get rid of the bullshit permastun stuff, just set [this](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/human_organs.dm#L92) to `>= 8`; That'll mean that you have to have 8 stance damage, or, 2 destroyed/missing/dead/malfunctioning legs
