### ISSUE TITLE
Tablet computers appear broken until activated.

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#9952]
**Problem Description**:
When a tablet computer is bought from the computer vendor in Primary Tool Storage on the Cyberiad map, its initial sprite is the broken tablet computer sprite. Once turned on, it appears normally. **Edit** Addendum, after purchasing the tablet computer, turning it on, and then turning it back off, it returns to its normal unpowered sprite.

**What did you expect to happen**: 
The tablet computer seems to initiate its broken sprite instead of its unpowered sprite somehow as soon as it appears when bought, causing what appears as a broken tablet being bought until its first use. I have before received the tablet computer in its initial state with no problem, and expected that.

**What happened instead**:
Instead, I received the tablet with the broken screen sprite.

**Why is this bad/What are the consequences:**
The first time this happened, I genuinely thought the tablet computer was broken, and went to the trouble of deconstructing it instead of simply powering it on. This could cause similar troubles to other users.

**Steps to reproduce the problem**:
1: Buy a tablet computer from the computer vendor in Primary Tool Storage. The 'stats' of the tablet computer do not matter.
2: See it appear 'broken'.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I've observed this happening a few times. The roundtype doesn't seem to matter. I can't comment on if it happens in other maps.
![img1](https://user-images.githubusercontent.com/26665535/47331902-548b8380-d6c9-11e8-9ceb-2607d9633570.png)

**Comment by Birdtalon** [comment]
This just made me laugh. 👍
