### ISSUE TITLE
Everything is bitter

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#9956]
Almost every food in the game tastes like bitterness because it has the nutritional reagents in it, which are all set to taste like bitterness. They should taste more interesting and not misguide people into thinking they're bad cooks.

**Comment by taukausanake** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents.dm#L30
`var/taste_message = "bitterness" //life's bitter by default. Cool points for using a span class for when you're tasting <span class='userdanger'>LIQUID FUCKING DEATH</span>`

I think the real problem is that everything that doesn't have a taste... doesn't have a taste...

**Comment by Spartan6** [comment]
We're just bitter.

**Comment by FalseIncarnate** [comment]
While I get this is self-deprecating humor (you added the taste system), probably should still try to avoid calling anyone a retard or idiot in issue reports (even yourself).

That said, nutriment previously had a taste assigned of “bland food”, but this was removed in #8750 which results in it now pulling the default value of “bitterness”

I think you either need to reintroduce a taste message or (if possible) exempt nutriment from the system so the other food reagents can shine more

**Comment by FlattestGuitar** [comment]
Fair point! I think my joke might've been too much.

**Comment by taukausanake** [comment]
I thought it was satirical enough. Still, name calling might be bad.

My vote still for making missing taste_messages rather than changing the default one!

**Comment by FlattestGuitar** [comment]
But there are only like four reagents that govern that taste. You can't just do that. You'd have to code a more complex system that somehow grabs the actual food items and forces their taste onto the nutriment stuff.

**Comment by Pennwick** [comment]
Potentially it could be more types of nutrient that are made for each of the main flavors of sweet, sour, bitter, salty and savory. Cooked foods could add a small amount of this kind of nutriment to each food to give it that flavor. It'd still be a pretty big job though.

**Comment by KasparoVy** [comment]
All around me are familiar faces
worn out faces, worn out places

**Comment by variableundefined** [comment]
This is not really an issue but more of a design problem. TG's taste system should be ported in a future date.
