### ISSUE TITLE
Ghosts can unflip tables

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#9977]
**Problem Description**:
Ghosts can unflip flipped tables

**What did you expect to happen**: 
Ghosts don't have hands silly, so they can't right tables

**What happened instead**:
I could unflip the table

**Why is this bad/What are the consequences:**
Haunted tables are never good

My emulsions

**Steps to reproduce the problem**:
1. Be spoopy
2. Find flipped table
3. Right-click > Put table back

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
N/A

**Comment by farie82** [comment]
Easy issue for starters
