### ISSUE TITLE
Humanitarian Crisis in TG station

### ISSUE THREAD

**Issue by variableundefined** [ParadiseSS13/Paradise#9999]
**Problem Description**:
They're removing felinids

**What did you expect to happen**: 
They don't remove felinids

**What happened instead**:
There's a caravan of felinids heading our way

**Why is this bad/What are the consequences:**
We don't got no felinids in our codebase

**Steps to reproduce the problem**:
1. Remove felinids
2. Be listed server
3. Bawk at refugee crisis

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Gamemode was forum vote

**Comment by KasparoVy** [comment]
MERGE MERGE MERGE
